* ב.
** רש"י ד"ה הכל שוחטים -
עיין במה שמזכיר רשי. לא פשוט למה רשי מזכיר את זה כאן; לכאו', אינו כל כך נוגע. נראה שאולי הוא מפני שגמ' ידון על משמעות של מילים אלו, ואז מבאר רשי למה לא דן בלשון של "הכל," אלא רק בשאר משמעויות שלו. עדיין מעניין שעל המשנה, ולא על הגמרא, הוא, שהרי כשאנחנו עומדים במשנה, לא יודעים כבר מה שידון בו הגמרא.
** רשי ד"ה הכל נערכים -
עיין במה שפירש. נראה שההוה אמינא הוא שערך הוא, בעיקר, שווה לדמים, והוא שחייב את הדמים שלו. אבל, כיון שלא קל תמיד לחשב כמה הוא שווה, הוא מנדב באופן שלא צריך לחשב, והוא שרק נקח אומד של שוויות שלו. אז, אם הוא מוכה שחין, ואז פשוט כמה הוא שווה, שהוא שווה כלום, לא ישלם כלום.
ודע שאין כל ענין של ערכין כל כך פשוט לי. כמו שרמזתי, היה נראה לומר שאין בו אלא נדבת כסף בלשון מעניין. ותחשב על זה.
* ב:
** רשי ד"ה תרתי דיעבד -
הכי הו"ל- רשי מפרש שהיה אפשר לומר "הכל שוחטים חוץ....." יש לדון, שאולי אז הוה אמינא שאם שחטו, אינו פסול בדיעבד. אז, צריך לומר לשון של "כולם ששחטו...."
** כקדש -
היה אפשר לומר שהקא משמע לן של המשנה אינו שמותר אף שיש בו דינים של הקדש (כיון שאין בו גזרות של הקדש, ורק דינים דאורייתא שלו), אלא שאין בו דינים של הקדש בכלל. בפשטות, גמרא ידע שאין זה הדין, אלא יש בו קדושת קרבן. גם אפשר שפשוט שזה יכול להיות הקא משמע לן, וגמ' רק בא לומר שאף יכול להיות הקא משמע לן שאף שאין חילוק בין הקדש לחולין בטהרת קדשים, עדיין בדינים דרבנן יש לחלק. גם אפשר לומר שלא מסתבר שמשנה שלנו יגלה לנו חידוש בדין של חולין על טהרת הקודש (או מפני שאין הסוגיה מדבר בזה או שהיה לומר בפירוש שמדברים בשל מוקדשים). ותחשב.
* ג.
** רשי ד"ה צריך שיהא -
יש להעיר שזה רק אפשר אם נאמר שבדיעבד רק משמע בדיעבד, ולא משמע כלום על לכתחילה (אלא שממה שלא אומר לכת', משמע שלכת' אסור). היה אפשר לומר נגד זה, אלא שלשון של בדיעבד משמע שאינו מותר לכת' (תחשב למה זה נכון, אבל נראה לי שאולי הוא נכון). אז, יותר מחודש לומר בו לא זו אף זו, שאינו מוסיף על הראשון, אלא מבטל אותו במקצת. ותחשב על זה.
* ג:
** רשי ד"ה ואף על פי שאין מוחזקים -
רשי מזכיר שני בעיות; עיין לקמן בגמ' שרק ידון בחשש שני של רש"י.
** הכל מומחים שוחטים -
הדרך לקרוא את זה הוא "הכל- מומחים- שוחטים."
** קסבר -
רצה לומר, סבר כאותו תנא שאמר שגרי אריות הם, ולא רצה שיהיה סתם משנה נגד שיטה שלו. (וא"ת מה לנו כמי הלכה, אחרי מה שיאמר גמ' לקמן. ויש לומר שאף על פי כן, יש מה שמסתבר לו, והוא שמס' לו איזה תנא נכון (מסתמא הוא מן הקראי), וקשה לו לומר שתנא טעה, ואמר מה שלא מסתבר.)
** רוב מצויים -
יש לדון אם בכל מקום שסומכים על רוב במשנה צריך לומר שהוא סתם משנה נגד רבי מאיר. (הדרך לדחות הוא לומר שכשאומר רוב, רצה לומר רוב שנגדו יש רק מיעוט שלא מצוי.)
* ד.
** כעומד על גביו דמי -
יש להעיר שגמ' משנה את הלשון שבו משתמש כשמיישב שיטת רבא וכשמיישב שיטת אביי. היה משמע שלא אומר תשובה שווה. ותחשב.
** ודילמא סימנא -
ואם תאמר דילמא לא חושש לספק (אבל אנן נחוש לספק). צריך לומר שזה גופא ספק הוא, ונמצא שבין הכל ספק ספיקא הוא, ואז הוא מותר. ויש לדון, שאינו ממש ספק ספיקא (שרק מסופקים באותו אחד שממנו יאכל הישראל, ולא במהו הפרופורשי"ן), אלא הוא ספק אם יש לנו הוכחה להתיר. במילים אחרים, הוא ספק איסור, וספק אם יש לנו הוכחה. צריך לומר שנחשב כעין ספק ספיקא כיון שצריכים שני הנחות כדי להתיר. ותחשב.
** אחזיקו -
קצת צריך ביאור, באמת, למה מוחזקים בו, כיון שלא כתוב בתורה. נראה שצריך לומר שהם מפרשים אותו בתוך קרא אחר. אבל, אז צריך ביאור למה לא נסמוך עליהם, ומה ההסבר של החולק. נראה שצריך לומר שהוא דבר שכנראה הם מפרשים בתוך קרא, אבל אנו יודעים שאינו, באמת, בתוך הקרא, ואז חוששים אנו שיחזרו בהם. יותר מזה, נראה שאולי הוא דבר שאינו כל כך בתוך קרא. הרי, קרא אומר שצריך לזבוח. לא פשוט מהו זביחה, ומדעתם (צריך ביאור איך יש להם דעת על זה) מפרשים מהו זביחה. כיון שדבר זה רק בא מפירוש זביחה, ולא בא מפסוק, יש לחוש שיחזרו בהם.
** כל מצוה -
יש לדון איך לקרוא את זה, אם הוא "כל מצוה שהחזיקו בו הרבה, אז הם מקפידים על זה," או שכל מצוה שהחזיקו בו, הרבה יותר מקפידים בו." ותחשב.
** אחזיקו -
כדי להכשיר אותו, צריך לומר ששומרים אותו לשם מצה. נמצא שאף בזה הם מוחזקים. לא כל כך פשוט איך נדע את זה; צריך לומר שמאמינים להם (אולי יאמרו כפי תומם) שלכך הם שומרים. ותחשב.
** כיון דאיכא היתירא -
קשה מהו הצד להחמיר בזה, שהרי פשוט הוא שיקל. אפשר לומר שחוששים שכל מומר לתיאבון ייעשה מותר אף בלי תיאבון, כמו שאומר רב הונא (שנעשה כהיתר). גם אפשר לומר שכיון שלא כל כך קל לשחוט בכשרות ישחוט בפסול. במילים אחרים, אולי החילקו שבין שחיטה כשרה לשחיטה פסולה הוא מספיק להיות תיאבון לו. ותחשב. (ודע שלא פשוט, כל כך, למה לא, לפי רבא, נחשב תיאבון, אם הוא שיכול בקל לשחוט בכשרות או שיכול בקל למצוא אחר לשחוט לו. אין השני כל כך מסתבר לי, שבדרך כלל שוחט מקבל שכר. ותחשב.)
וצריך לעיין לקמן בגמרא, שיביא ראיה לרבא; צריך לראות לאיזה דבר יש ראיה.
* ד:
** לדבר אחר -
יש לדון, שהיה אפשר לחלק לומר שערלות האו יותר חשוב, שהוא סימן של יהדות. אז, צריך לפרש שניהם. ויש לדון, שאז היה לו רק לומר רק ערלות. ויש לדון, שאולי הו"א שרק בזה הוא ממיר, כיון שיש בו צער גדול.
** מפני -
קשה, שאלי רק מחליפים כיון שיודעים שאז יכולים למכור לבני ישראל.
** רשי ד"ה מפני שהם -
עיין במה שפרש רשי. יש לדון אם, באמת, הוא יותר קל (שהנאה יותר קל מאכילה) או שסומכים שלו נראה יותר קל.
** יש לדון
מהו הצד שמומר לדבר אחד יהיה מומר לכל התורה כולה, אם הוא שחוששים שבאמת הוא מומר לכל התורה או שהוא כאילו הוא מומר לכל התורה, שרואים שלא מקבל מרות של ה', ומה לנו, אז, בשמירת שאר המצוות, או שיודעים שיהיה מומר לכל התורה כולה, וכיון שעומד לכך, כבר יקבל דין של מומר.
* ה.
** עורבים -
עיין בגמ' במנחות שאומר ש"אין דבר טמא יורד מן השמים."[fn:1] לא נראה שכך מכוונים לומר כאן; צריך לומר שירידה מן השמים שע"י עורבים שונה.
** דיבור -
לכאו', רצה לומר שה' אנה את ידם לקחת מן המותר ולהביא לו. יותר מזה, אולי גרם שיהיה כשר, שישוב בשעה ששוחטים. (דע שרק נאמר כצד ראשון אם נאמר שפסול זה הוא רק מחמת חשש, ולא פסול בעצם, או אם נאמר שהיה צדיק אחד שנמצא שם.) גם יש לומר שכיון שהיה על פי דיבור, שה' הראה שרצה שיאכל ממנו, התיר את האיסור, כמו בהוראת שעה. עיין ברשי שאמר כצד אחרון הזה. יש לדון למה אמר כן. צריך לומר שסבר שלא היה אף צדיק אחד שם, ושזה איסור בעצם, ולא חשש. גם יש לומר שרשי מצרף אותם, והוא שה' התיר לו שלא לחוש. אבל, יש לדון, שהייתי אומר שה' לא מתיר לו, אלא שאז אין חשש, שה' לא יאכיל לו איסור. צירך לומר שאולי ה' יאכיל לו איסור. אם כן, בעיקר אומר כצד אחרון, ואין הראשון מוסיף כלום. ותחשב.
** שמייהו עורבים -
משמע ששם של כל אחד מהם היה "עורבים." קשה, אז, למה נחשב שהיו שנים, ולא אחד. (אולי הקרא מדב בלשון יחיד.) עדיין קשה למה לא נאמר "עורבימים." אז, יותר היה נראה לומר ששם של כל אחד היה "עורב." צריך לומר שכך כוונת גמ', וכשאומר, "שמייהו עורבים," רצה לומר שבין שניהם, יש "עורבים," אף שאין שם של אחד מהם "עורבים." ותחשב. כן נראה ג"כ מן הקרא שמביא, שהוא מדבר על איש שמו "עורב." ויש לדון, שאולי רק מוכיח שיש שנותנים שם על עוף זה (כמו שמצאנו הרבה בני אדם ששם שלהם אריה או זאב), ואז כמו שיתנו שם של עורב אחד, כך יתנו שם של עורבים. ותחשב.
** שכל הכופר בה -
צריך ביאור למה משנה את הלשון מ"כופר" ל"מודה." הפשטות הוא ש"מודה" רצה לומר כופר, והוא לשון סגי נהור. אז, קצת קשה למה רק אומר לשון סגי נהור גבי כפירה בכל התורה, ולא גבי כפירה ראשונה. אולי אפשר לומר ש"מודה" רצה לומר "מודה לכפירה שלו," שאף בזה האו כופר. דחוק, עדיין, למה נאמר לשון כזה, ולמה לא רק נאמר "כופר."
** רשי ד"ה עורביים -
נמצא שרשי מפרש שאין בעיה לקרוא לבני עיר עורב עורבים, אלא שכיון שיש לו משמעות אחרת, היה לו לנקוט דרך אחר לקרוא להם. כעין זה מצאנו שבני מצרים נקראים "מצרים," וגם "מצריים."
** רשי ד"ה עורביים -
יש להעיר שקצת מעניין שיש, באמת, חשש שנחשוב שהיו עורבים ממש, שזה דבר מאד מחודש (בין במציאות, ובין בדין, שהוא הוראת שעה). אז, מעניין שלומדים ממה שלא אמר "עורביים."
** פושעי -
זה מזכיר לי שכמו שמפרש רשי כאן ש"פושעי ישראל" רצה לומר מזידים (כך מתחיל רשי לפרש, אבל מסוף פירוש שלו, יותר משמע שרצה לומר מרדים), כך "פושעי ישראל בגופם" יהיה רק אם עושה כן במזיד ובמרד. ותחשב.
** ה: דלכפרה -
יש לדון אם הענין הוא שלא רוצים שיקבל רשע זה כפרה (או שרוצים שלא יקבל כפרה) או שלא מסתבר שיוכל לקבל כפרה, שכפרה בא ממה שלא היה עושה אותו אם לא שהיה שוגג. ותחשב.
** רשי ד"ה דורון -
עיין במה שכ' רשי. נראה שכוונת רשי לומר שכל זמן שמקבלים קרבן, יהיה לטובת ה' או לטובת המקריב. הרי, חטאת הוא לטובת המקריב, שצריך הוא להביא את הקרבן. אבל, עולה הוא לטובת ה'. כיון שרשע הוא, אין בזה טובה לה'. ככה היה נראה לומר מדיבור זה של רש"י. אבל, עיין לקמן ברש"י, שנראה שהחילוק הוא שיש סברה לחייב את החוטא כיון שלא יהיה חוטא נשכר. באמת, לא כל כך פשוט למה אין זה נוגע בעולה, שהרי גם בעולה, אחרי שנידב אותו, חיוב הוא. (נראה שאין זה כל כך קשה לראשון, שעדיין, ממה שצריך לנדוב אותו, רואים שענין שלו הוא טובת ה'.) נראה שכיון שלא צריך לחייב את עצמו, לא נחשב חוטא נשכר, שיש דרך אחר לפטור את עצמו. ותחשב.
** רשי ד"ה היכי איסתעייא -
שום שטן- לשון זה מעניין.
* ו.
** וגזר -
משמע שדין של רבי מאיר הוא דין דרבנן. גם במקום אחר יש משמעות לזה (שכחתי איפה), אבל עיין בתוס' שם שדוחה אותו).
** אינהו -
קצת קשה למה לא אומרים שרצה לומר שהוסיפו על הגזירה עד שהיו עובדי כוכבים גמורים.
** מביא תקלה -
יש לדון אם רצה לומר שאף מה שמיוחס לצדיק לא גורם רע או שרצה לומר שלא מגיע רע לצדיק על ידי בהמתו (שרק מיוחס לו).
** עושים -
נמצא שמותר כיון שיאכל על ידי תערובת, אף שלא לוקח על ידי תערובת.
* ו:
** מיגזל -
היה אפשר לדחות שיש שגוזלים ויש שלא גוזלים. אם גוזלת, לא תחזור לה כלום. אם לא גוזלת, לא תחליף.
* ז.
** גברא רבא -
עיין במקום אחר (נראה שהוא בסוף פרק רביעי או חמישי של ברכות). שם, היה אפשר לומר שרצה לומר שכיון שמדברים על אדם גדול, מסתמא כוון (עיין שם). אבל, מן גמ' זה רואים נגד זה, אלא רצה לומר שאדם גדול הוא המעיד, ומסתמא דקדק בעדות שלו. כך פירש רשי שם.
** מקום הניחו -
צריך להגדיר את זה, שבפשטות נמצא שלפעמים אין חיוב הוכחה וביעור רע, כדי שדורות אחרים יהיה זכאים לבער את הרע.
* ז:
** מה בחייהם -
צריך ביאור למה זה נוגע בכלל.
** מימיו -
לשון גמ' משמע שאין זה "מיום שעמד על דעתו," אלא אף קודם לו. צריך לומר שאין סמיכה על שולחן אביו בכלל "פרוסה שאינה שלו."
* ח.
** רשי ד"ה ליבן -
עיין בשני הלשונות. לכאו', שני הפשטים באים מפני שכשדבר נעשה חם מאד, נעשה לבן או אדום (ולבן יותר חם מן אדום).
** חידוד -
יש לדון אם הוא מפני שהוא קטן (רצה לומר, אין הרבה מקום חם שנוגע בו) או מפני שלא מכה אלא חותך. ותחשב.
** ליבן -
אם, באמת, חותך קודם ששורף, קצת צריך ביאור למה ילבין. בסכין, אינו כל כך קשה, שנוכל לומר שעשה אותו או תיקן אותו, וממילא ליבן אותו. כמו כן בשפוד, יש לומר שהיה על האש, כדרכו, ולכן נתלבן.
* ח:
** טרידי לאפוקי -
יש לדון למה הענין הוא שהם טרודים להוציא, ולא שהסכין טרוד להכניס, ולכן לא מוציא. (אין המציאות כל כך פשוט לי (איני יודע למה הוא נכון), ואז לא קשה לומר שמה שאמר גמ' הוא האמת.
** רשי ד"ה דוחקא -
לכת'- היה אפשר לחלוק על זה, ולומר שאין איסור לכת'. אבל, אין מי שיעשה כן (ויטריח על עצמו או יצטרף א"ע לקלף), ולכן שונה אותו בלשון בדיעבד. יש לדון בזה.
* ט.
** בחזקת היתר -
לשון זה קצת קשה; לכאו', לא רצה לומר שהוא חזקה, אלא רוב. אולי איה"נ, ורק נקט לשון זה אגב הרישא של המאמר. עיין לקמן ברשי, שנראה שקורא לזה רוב. (וע' בב"ב, שאומרים שחזקה שאין אדם פורע תוך זמנו. לכאו', אף זה רוב, אבל לא נראה כן מאותו גמרא. אז, אולי משמע שיש סוג חדש של חזקה, והוא כשלא יודעים הפראבוביליט"י בכלל, אבל מסתבר לדעת כן. ותחשב.)
** בחזקת טומאה -
אפשר לפרש שחולקים באם נאמר תוצאה מן החזקה או לא נאמר. גם אפשר שחולקים ביחס בין שני דברים אלו, הטומאה והאיסור. ותחשב על זה. גם אפשר לומר (אבל זה מחודש) שאף בהמה בחייה יש לה סיבת טומאה, אלא שיש מניעה על הסיבה ממה שהיא בחיים, ואין בעל חי טמא. אז, אולי (ולא פשוט שיהיה כן) נשאר באותו חזקה, שיש סיבת טומאה, והרי יודעים שאין מניעה, שאינו חי עוד.
** במה נשחטה -
לשון זה מוזר; רצה לומר, "עד שייודע לך שנשחטה."
* ט:
** ספק טומאה -
יש לדון מה מכוון גמ' לומר כאן- או שכל ספק דאו' לקולא או שספק דאו' עם חז' היתר לקולא. יש להעיר שמביא ראיה מן טומאה; אינו חזקה השווה לשל כאן שם. ותחשב.
יש להעיר שהיה קל לחלק בין סכנה לאיסור באופן אחר. קל לומר שאיסור תלוי בה'- הענין הוא שצריכים להקשיב לציוויים של ה'. הרי, לא קשה להבין שה' יתן לנו כלל של חזקה, ואז אף אם נמצא שאכלנו דבר איסור, לא היה אסור לנו. אבל, סכנה הוא מציאות. אז, כיון שלמעשה ספק הוא, אין חזקה עושה כלום. יש לדון, שאולי על זה ישמר ה' פתאים. דחוק.
* י.
** רשי ד"ה מפני שדרכן -
מלשון רשי קצת משמע שיכולים לעשות רוב על ידי מנין כמה דברים יכולים לקרות. יש להעיר שזה דומה לצד אחד שאמרו המפרשים בספק ספיקא.
** אין ספק מוציא -
זה מעניין, שיכולים לומר שזה וזה פגם אותו. אולי מדברים בשרק נמצא בו פגם אחת. אבל, אז אינו ספק שמוציא מידי וודאי, אלא בוודאי לא פגם כבר. צריך לומר שיש בו פגימות רבות, ורצה לומר שכיון שבוודאי עצמות פוגמים, אין הוכחה שהיתה פגם מיד אחרי שחיטה. ותחשב על זה. (לכאו', הענין יהיה שאין התעוררות ספק. כל ענין התעוררות ספק אינו ענין פשוט; עיין במה שדנינו בזה בחרב אל הבדים על פרק אלו נערות.)
** בעצם -
קצת קשה, שאם הסברה שלו הוא שאין ספק מוציא מידי וודאי, כאן נאמר שאין ודאי נוציא מידי ודאי. ותחשב.
** עד אחד נאמן -
משמע שזה משיב גם שמניחים שאדם אחד לא טועה. ותחשב. (מעניין, שהיה אפשר לומר שזה רק נכון כשמעיד על דבר, שבתוך עדות שלו, כמעט מעיד שהוא מכיר בדבר זה. אבל, כאן בא לבאר למה לא צריכים בדיקת חכם, ולמה סומכים עליו. אולי הוא מפני שאדם לא ישקר לעצמו לומר שיכול לבדוק, שאין עד אחד משקר. יש לדון, שאולי ישקר לעצמו, ולא לאחרים.)
** ודילמא אדנפיק -
יש להעיר שאין זה נפקא מינא גדול, שהכל תלוי במאמר הכהן. (יש לדון, שאולי זה רק שטהור אם לא מטמא אותו כהן, אבל לא להיפך.) אבל, לא נראה שזה יעשה חילוק במקור.
** כהן גדול -
קצת יש לחלק, שה דרך יציאה מן קדשי הקדשים, מה שאין כן כאן, שלא תמיד יוצאים מן הבית הזה כן.
** היכא דאתחזק -
נמצא שעדיין קצת סומכים על חזקה. אבל, הענין הוא שאין ללמוד מזה לשאר חזקות (וזה היתה נידון של הגמ'). אולי היה אפשר לפרש שגמ' אומר דבר אחר (אין זה כל כך נשמע מן הלשון, אבל מסתבר שיאמר זה), והוא שזה רק אומר שגדר של צרעת הנראה הוא צרעת הנראה באור שלו, ולא באור חלונות. אבל, יודעים כבר שזה צרעת הנראה. אבל, יש לדון מהו קושיית הגמ', אם הוא שלא פותחים חלונות לראות נגע, שאז נראה שבא לנו תשובה, או שמקשה שאולי שינה, עד שהוא הנראה רק לפי אור חלונות. לזה, אולי רצה לומר שהיה נראה בו, אז, שינוי, שאם היה נראה כבר בלי חלונות, יהיה מאד חזק עם חלונות, והרי רואה, אז, חזקות שלו. ותחשב.
** צרעת -
נראה שזה יכול להיות מקור לחזקה להקל ולהחמיר, שהרי יש בזה חומרא (מה שחייב לנהוג דיני טומאה) וקולא (שיש לבית דין הכוח לכוף אותו לנהוג אותם דינים). ותחשב.
** תניא דלא -
ההוכחה קשה להבין. הרי, כולי עלמא מודו שסומכים על חזקה. אז, בוודאי הדין הוא כמו שאומר הברייתא, אחרי שיש מקור לסמוך על חזקה. אבל, רק דנים אם נדע לסמוך על חזקה מדין זה, ואם דין זה מוכיח סמיכה על חזקה. אז, לא נראה שבריי' זה הוא נגד ר"א. אולי הבריי' קצת משמע שזה יוצא מן הקרא, ולא מן הדין של חזקה. דחוק.
* יא.
** כגון דקיימי -
נראה בזה שני דברים מחודשים. הראשון הוא שיכולים לסמוך עליהם, ולא צריכים ראיית כהן. אולי זה מצטרף עם חזקה (ואז עדיין משמשים בחזקה, כמו דיחוי של גמ' לעיל). גם מחודש שסומכים על דיבור של בני אדם, שאף בה צריך חזקה, שיש זמן בין אמירת הראשון לשמיעתו (שלכן יש דרא של גברי, ולא רק גבר אחד). אין לומר שיודע אחר כן ממה שלא אמרו לו שמשנה, שאז יש לומר שצריך הכהן לבדוק אחרי כן. ויש לדון, שאלי עדיין לא יודע בשעת הסגר, וזהו הבעיה. אבל, עדיין לא נראה, שאז לא צריך דרא של גברי, אלא רק גבר אחד שם. ותחשב.
** בתר רובא -
יש להעיר שמשמע מזה שספק דאו' לחומרא מדאו', שצריך מקור לסמוך על רוב, ורק מצאנו מקור (לכאו'; אבל אולי אינו כן לצד ברש"י שנלמד מהל' למשה מסיני) לרוב, ולא לספק. ויש לדון, שאלוי צריך למקומות שלא סומכים על ספק, כמו אם יש חזקה. אבל, אז צריך ביאור למה רוב נגד חזקה צריך דיון בגמ' בכלל. קשה לומר שאותו דיון גופא הוא אם ספק דאו לחומרא מדאו' או לא. ותחשב, שאולי יש נפק"מ אחרות בין רוב לספק דאו' לצד שהוא לקולא מדאו'.
* יא:
** מאי נפקא לן מינא -
קשה למה לא אומר שיש נפקא מינא כיון שאז ייפסל לקרבן (ואז נחוש לאותו אחד). אולי לא פשוט לו שאי אפשר לבדוק אותו אחד. אין לומר שפסול כיון ששניהם צ"ל שווים, כיון שזה רק לכת'. אבל, אז קצת קשה למה הביא גמ' אותה נקודה.
** משום איבוד נשמה -
זה מחודש, שבדרך כלל מנסים להציל בני אדם מחיובי מיתה. ותחשב.
** היכא דאפשר -
מעניין שעדיין מותר לסמוך כדי לאכול בשר. קצת משמע שאין הענין שרק דחוייה, ורק סומכים עליו בדוחק, אלא שיש יותר סיבה לסמוך על רוב שם. היה נראה לבאר שחלק מרוב הוא שסומכים שכך הוא כיון שאין דרך אחר לחשב אותו. במילים אחרים, אם אשאל מהו, אין לך שום תשובה כי אם סמיכה על רוב, ולכן סומכים. אבל, אם אפשר לבדוק, יש לך תשובה אחרת. ממילא, אין הרוב קובע מהו כל כך.
** דחייש למיעוטא -
אין לומר שזה רק מיעוטא דמיעוטא, שאז קשה מהי"ת לרבנן מיעוט. ויש לדון, שאולי מסתבר לרבנן שזהו נקודת החילוק, כמו שהוא ברוב שהוא לפנינו.
** דחייש -
לכאו', רואים מכאן שרבי מאיר סובר כן מדאו', שאם רק מדרבנן סובר כן, קל לומר שחילוק כזה רק מהני על דין דרבנן. ויש לדון. יש להעיר שהיה אפשר לומר שרבנן גופא חולקים על רבי מאיר בסברה זו, ולכן רבנן סומכים על רוב ורבי מאיר לא סומך. במילים אחרים, אין זה סברה הפשוטה לדרוש, ומה שרבי מאיר דורש אותו לא יוכיח שרבנן דרושים אותו, שמצאנו מחלקת ביניהם שיכול להיתלות על זה.
** דילמא במקום נקב -
מעניין שלא אומרים שיבדוק בשעת שחיטה. נראה שהוא מפני שחוץ שלו הוא אדום, ואי אפשר לבדוק אותו.
* יב.
** אפשר -
עיין במה שכ' רשי בביאור המקור. היה אפשר לומר שמס' הגמ' הוא שאפשר ללמוד ממה שאי אפשר לבדוק, והוא שכולי עלמא מודו שכשאין שום טורח בבדיקה, אין סומכים על רוב. (כך שמעתי בשיעור של הגר"ק.) אז, נראה שכמו שרבי מאיר למד מאי אפשר ממש (גבי פסח, שצריך לאכול) לשחיטה (שרק טורח הוא), כך נלמד למה שיש בו קצת טורח. אף אם לא נאמר כן, ייצא לנו, לצד שהל"מ הוא, שלא הכל הל"מ, שאם אי אפשר (או, כמו שבארנו, קשה) לבדוק, ייצא מן הקרא.
** קדשים -
קשה למה לומדים מזה; הרי, הפסוק מתיר לאכול בשר תאווה. אז, קרא אומר בפירוש לסמוך על רוב.
** שמא ישהה -
יש להעיר שיש בעיות שיותר מסתבר לקרות בין שני סימנים מבסימן ראשון (כמו שהייה וחלדה), ואז קצת מחודש ללמוד משחיטת סימן אחד לחברו.
** רשי ד"ה פסח -
הל"מ- כיון שכן, קשה למה צריכים קרא לרוב שהוא לפנינו. אולי הל"מ אינו על זה. וא"ת למה ייגרע. ויש לומר שאף שאין סברה שייגרע, אין דורשים מן הל"מ. צריך להגדיר את זה, שנוכל לומר שזה דין אחד. ותחשב. ונראה שצריך קרא לרוב של סנהדרין, שלא נראה פשוט שיש בו, באמת, ענין של רוב. ותחשב.
* יב:
** אין מוסרים -
לכאר', האיסור יהיה בל תשחית.
** מעשה -
לכאו', שואל למה לא שאל את שניהם, ולא שישאל את מעשה, שלא נראה שיש סיבה לשאול את זה יותר מזה.
** רשי ד"ה מאן -
לחתיכה- כך יאמר גמ' לקמן. נמצא שיש דעת לקטן, שאם לאו הכי, אף לא מכוון לחתיכה. (אולי זה מפני שיש לו מעשה, שעשה דבר שמוכיח בבירור שרוצה לעשות מעשה חתיכה. אבל, נראה שצריך להיות שאין צריך לומר כן, שהרי לא מביאים ראיה לדין מעשה ממשנה שלנו, שנלמד מכאן הכשר דאו'. ויש לדון.) אולי הוא גם שרק יש דעת פשוט לקטן, והרי חתיכה הוא דבר פשוט, ולא דבר קשה לחשוב עליו. יותר מזה, אולי אין דעת רוחניות לקטן. אז, לא חושב על קנינים ויחסים וחלותים וכדומה, אבל יכול לחשוב על חתיכה.
** רשי ד"ה מאן -
כולן- גם היה אפשר ללמוד מ"יקלקלו." נראה שהיה אפשר לדחות שהקילקול הוא שלא מכוונים.
** שהלכה -
איני מבין בכלל איך דבר כזה יכול להיות. מבין אני אי יכול להיות שהלך, אבל לא איך הלך והביא, שכמעט אי אפשר לדבר כמו סכין לעשות באוונ"ץ לאחוריו באופן שעוד יכול לחתוך (שאין חידוד שלו במקום נכון, ואינו מהר מספיק). ותחשב.
** מאי שנא מעשה -
כנראה, לא קשה שלא יודע משנה, אלא מפני שיש לנו סיבה לחשוב שבאמת יודע את המשנה. נראה שאולי זה רק מפני שהוא משנה בסדר ובענין טהרות, שלא היה נלמד כל כך. ודע שמעניין שמנייח שאם ידע מקצת המשנה, ידע את כולו. נראה שאולי לא היה רגיל כל כך ללמוד אותו סדר, אבל אם למד אותו, למד אותו, ולא היה לומד רק חצי משנה, אלא היה גומר את המשנה.
* יג.
** ושחט -
יש לדון אם חשב שהיה שואל לדין לכת' או שהיה שואל לדין דיעבד, ושכבר ידע פסוק אחרת (שהוא, אולי, יותר מפורש).
** לרצונכם -
קורא לדעת רצון, כיון שאם אדם יודע מהו עושה, ועושה אותו, צריך להיות שרוצה לעשות אותו דבר. לאידך גיסא, גם כן, רק נוכל לומר שאדם באמת רוצה דבר אם יודע מהו.
** רשי ד"ה ר' אמי -
נבלה- וא"ת הרי רשי ממש כופל דיוק של הגמרא. לא כל כך קשה לומר כן, לומר שרשי כופל מה שאומר גמ' לבאר שיהיה פשוט לפי רב אמי, אבל לא נראה שצריך לומר כן. נראה שגמ' לומד כן ממה שרק מדמה אותו לנבלה, ולא לדבר יותר חמור. אם היה דומה לדבר יותר חמור, יש דמיון יותר טוב לנקוט, והוא דבר יותר חמור. אבל, רשי דורש ממה שדומה לנבילה הוא, והרי לנבילה יש היתר הנאה. במילים אחרים, לפי שיטה ראשונה שבגמרא, לא צריך להיות דומה לו בכל דבר, אלא שאם אינו דומה לו בכל דבר, היה לו לנקוט דבר היותר דומה לו. אבל, לצד שני, צריך להיות דומה לו בכל דבר. ותחשב.
* יג:
** מורידים -
הכל שכן מעניין, שהיה אפשר לומר שמה שעושה ישראל האו יותר גרוע, ולכן מורידים אותו.
** רשי ד"ה ולא בעובדי -
זה מראה מקום.
* יד.
** רבי יהודה -
צריך לחשב כל גמרא זו עם מה שאומר רמבן בנוגע לדין פירות הנושרים, למה יש בו רק גזירה, ולא איסור מוקצה.
** הובררה -
וא"ת אם כן אין מוקצה. צריך לומר שזה רק אם חושב ברירה, והוא שחושב שאולי יהיה לו תכלית, ולכן מתנה כן קצת. ותחשב.
* טו.
** הא רבי מאיר -
לא מבאר גמרא איך יודעים, באמת, שמשנה לא מכוון לאסור ליומו מחמת איסור זה. ותחשב.
* טו:
** והבריא -
יש לדון למה אינו נחשב מוקצה לחצי שבת. צריך לעיין באותו סוגיה.
** מוכני -
לכאו', הדרך לשחוט במוכני הוא שיש גלגל חדוד, ומגלגלים אותו על צוואר בהמה. גלגול חידוד הסכין שווה להבאת סכין, ואז שוחט. עיין ברשי, שלא משמע כן. באמת, צריך לחשוב על כל זה, שהרי גלגל בהכרח דוחף ודורס. אבל, צריך להגדיר את זה, שאם לא דורש כלל, פשוט שאי אפשר לחתוך.
** רשי ד"ה כגון שקצץ -
יש להעיר שגמ' מצדד שזה רק בדלעת רכה (כן אני חושב; צריך לעיין). אם כן, אולי היה אפשר לתלות שינוי בלשון בזה (באם מדברים בדלעת רכה או קשה).
* טז:
** סכין למעלה -
צריך לעיין בסוגיה זו, ששמעתי מדוד שלי א.י. שצריך להיות שהסכין הוא למעלה, ולכן הרבה מגאוני א"י פוסלים כמעט כל שחיטה בארה"ב (שאינו חוקי לשחוט ככה בארה"ב; אבל, להגביר פראידמאן (שקנה את בית השחיטה של רובאשקין) יש משהו שמתיר הממשלה, שהוא בעיקר רק שמכסה את הבהמה כשמהפכים אותו לתת סכין למעלה (אבל לא מבינים כן הממשלה). ותחשב. אולי רב פפא חולק על מה שמתיר הגמ'. כן נראה מן רשי. ותחשב.
** רשי ד"ה סכין -
תלויה- איני רואה למה צריך להיות תלויי (גם איני רואה כל כך איך לשחוט בלי דריסה), ולמה לא נמצא שהוא עומד, והוא שוחה קצת. ותחשב.
** רשי ד"ה רב פפא -
בהמה- נמצא, אז, שלפעמים בהמה רוצה לומר בהמה ולפעמים רוצה לומר חיה ולפעמים אף רוצה לומר עוף. 0יש להעיר שאף בימינו לפעמים יאמרו בני אדם "אנימאל" לכלול עוף, ולפעמים למעט עוף.)
* יז:
** מיחלשא -
אין זה כל כך מובן לי, שכיון שכבר גמרא הליכתו, והתחיל הבאתו, אין הפגם חוזר לאותו מקום. אז, מעינין שיכולים שני הפעמים של הפגימה עם הדדי. ותחשב.
** בדיקת סכין -
קשה למה לא מת' שאף שרק צ' בדיקת חכם מדרבנן, צריך בדיקה של השוחט (אם יכול) מדאו', ושבזה מדבר הפסוק. ואם תאמר שפשוט הוא, כמו שאומר גמ', נוכל לתלות אותו במוחזק להיות כשר. אולי לא מס' לגמ' ששם חייב.
** פגימות -
צריך ביאור למה לא מדבר על פגימת מזבח עצמו. צריך לומר שרצה לומר שיש שלש או ארבע כמותו, ולכן פשוט שהוא כמו עצמו, ולכן לא צריך למנות את עצמו. אבל, אין הלשון משמע כן כל כך.
** בחולין -
הוא גם נוגע בקדשים. צריך לומר שכיון שהוא נוגע בחולין, לא מונה אותו. יותר מזה, אף כשנוגע בקדשים, אולי לא נוהג להיות דין קדשים, אלא להיות דין חולין. לא כל כך פשוט שיש כזה מושג, אבל אולי הענין הוא שיש רע, אבל אין הרע סוג מיוחד של רע שנקרא רע של קרבן, אלא הוא סוג אחר של רע. אבל, כל זה חידוש, שהייתי חושב שקדשים הוא טוב מיוחד (או מעשה מיוחד), ופסולים שלו הם רק דברים שגורמים שלא בא אותו הטוב. ותחשב.
* יח.
** מעברים -
מעניין שעושים כן אף שרק צריך לתת לחכם כדי לכבד חכם. נראה שאולי אין הרבים יודעים כן, ואז יש לחוש שעשה כן מפני שחושב שלא צריך בדיקה (שסובר שהוא מפני צורך לבדיקה טובה שניתן לחכם).
** מכריזים -
לכאו', רק מכריזים על אותו בהמה עצמה, שאי לאו הכי, מה חילוק יש אם נמצא יפה לאם לא נמצא יפה. יש לדון בזה, שיש לדחות שרואים מזה שה' לא שומר אותו פתי מן עבירה, ואז יש לחוש שייתפס עוד בטריפה. ותחשב. באמת, ממה שמעברים אותו, משמע שאינו רק אם על אותו בשר שנכריז, שכנראה קונסים אותו על דברים אחרים. אולי יש לומר שלפעמים קונסים אדם כפי הרע שעשה, אף אם לא ידע שבוודאי יבוא הרע ממנו. אלא, הכל תלוי כמה רע בא, למעשה, ממנו. ותחשב.
** פוסלים ומכשירים -
יש לדון אם דווקא אומר ששווה למכשירים או שגם נוכל לומר ששווה לטהרה.
** השוחט מתוך -
לשון זה קצת מעניין; היה יותר נראה לומר שאם לא שחט, לא כשר, שהחידוש הוא מה שפוסל, שעוד לא השמיע לנו פסול של הגרמה.
* יח:
** מרב יהודה דאפילו -
יותר מזה, רב יהודה היה הרב של רבי זירא (שמצאנו שהיה ירא ממנו כשרצה לעלות לא"י.)
** רשי ד"ה הכי קאמרי -
צריך לחזור ולעיין על הלשונות.
** מכולי עלמא -
אולי לכן היה סיני (כמו שראינו בסוף הוריות).
** איקפיד -
מעניין שלא הקפיד על כבודו, אלא הקפיד לומר שעל כל פנים שמועה זו טובה היא.
** פגע -
צירך לע' בזה, שלא פשוט מן הגמ' ורש"י אם כוונת נגע הוא שממש רק נגע או שחתך חלק מהם. ותחשב.
* יט.
** רשי ד"ה והיינו -
מרשי משמע ש"והיינו" רצה לומר שהוא אותו שיטה. לולי רשי, היה אפשר לומר שאומר שהוא בתנאי ששייר. ותו"ת.
** רשי ד"ה לא חילק -
היה אפשר לומר כפשט ראשון של רש"י, ושפשט שני של רשי (שזה רק היה דבר שהיו אומרים) נכון אחרי שנאמר כאן. ותחשב.
* יט:
** שחיטה מפורעת -
מעניין שגמ' לא מבאר מהיכי נחשוב כן. אז, לא הוסיף על מה שידענו כבר, ואין בתשובה תשובה אמיתית.
** רשי ד"ה שחיטתו -
מרש"י זה היה משמע לי שרשי סובר שהסיבה שאין בהמה נעשה טריפה באמצע שחיטה הוא מפני שמעשה שחיטה הוא. היה נראה לי לבאר שאין מה שקורה באמצע מעשה גורם שאין עיקר תועלת המעשה נדחה. צריך לעיין יותר ברש"י זה ובנקודה זאת.
* כ:
** רשי ד"ה כל המעכב -
עיין במה שכ'. יש להעיר שזה מחלקת תנאים. אפשר לומר שרק מדבר בניטל עור של אותו מקום. אבל, צריך ביאור למה לא אומרים שנמצא אם כבר נחתך, ולא ניטל. ותחשב.
* כא.
** זקנה שאני -
מן הפסוק משמע שהוא זקנה וכבידות.
** כהבדלת -
צריך ביאור למה יבאר אותו כן, באופן שפי' של מה שאמר תלוי במחלקת תנאים.
* כב.
** בני יונה קטנים -
לכאו', רצה לומר יונה קטנים..., שהרי נקראים בני יונה כיון שהם קטנים.
* כב:
** לא לישתמיט -
מיד לקמן בגמ' לא נראה שזה המקור; ע"ש.
* כג:
** פרה -
לכאו', הוא הדין לכל שחיטה שצריך. יש לדון אם מכוון לשחיטת חולין או קדשים, ונקט לסתם בהמה להיות שור, או שמכוון לפרה אדומה. אף שלשני יותר מסתבר למה נקט אותו בהמה, קשה עדיין למה נקט פרה אדומה. אולי זה יותר דומה לעגלה ערופה. דחוק. הפסוק שמזכיר הוא בפרה אדומה.
* כד.
** יה"כ -
היה אפשר לחלק בין עבודת יה"כ, שהוא קדשים, ולכן לא כל כך קל להיות מעכב (שצריך שישנה עליו קרא), לפרה, שלכאו' אינו קדשים.
** כשר -
גם כאן, יש שפסול בה ובזה, והוא מי שיש לו פסול שנים ופסול מום.
** שלא ראה -
לימוד זה מעניין. הייתי אומר שכל אדם צריך חמש שנים ללמוד, ונלמוד מזה שאף תלמוד טוב צריך חמש שנים קודם שיעסוק בדבר. אבל, ק"ק מהיכי תיתי שלא לומדים עוד.
** חמש -
מניח, לכאו', שהענין הוא חמש שנים, ולא עשרים וחמש ושלושים.
* כד:
** בן שמונים -
יש להעיר שר"ח היה רופא (עיין בגמ' ביומא), ומסתבר, אז, למה חי לזמן ארוך.
** רשי ד"ה קול אחד -
קצת משמע, לכאו', שלא היה להם שום הארמונ"י, ורק מאלאד"י. ותחשב על זה. צריך לעיין באיזה זמן בעולם נתחדש הארמונ"י. אגב, דבר מעניין, יש שמעוררים על מה שלא נמצא בתורה שום ריי"ם. אנו, שמאמינים שמה' בא התורה, צריכים לומר שהמחבר ידע ענין של ריי"ם, ועדיין לא רצה להכניס אותו. אולי זה מפני שלא היה סיבה להכניס אותם, ואולי היה מניעה, כיון שהיה ריי"ם ידוע לבני אדם, ולא היה חשוב להם. ותחשב על זה. (נראה שאולי חשש ה' שאם יהיה ריי"ם, יהיה קל לזכור, ויאמרו אותו בעל פה, ולא יכתבו אותו, והרי דברים שבכתב אי אתה רשאי לאומרם בעל פה. ויש לדון, שזה לא נוהג בכל מקום, כמו שמבארים הפוסקים.)
* כז.
** ותו -
לשון זה בקושיה הוא ק"ק, שאין זה מוסיף על קושיה ראשונה. קושיה ראשונה היה בא לומר שאין זה המקור ששחיטה היא מן הצוואר. זה רק אומר שיש דין אחר שצריך הל"מ. ותחשב.
* כז:
** רשי ד"ה אין שחיטה -
משמע שדין שחיטה לענין אכילה ולענין טומאה תלויים זה בזה; לא הייתי אומר שצריך להיות כן.
* כח.
** וכי מה -
לכאו', יש דברים שלומדים מצבי ואיל (ע' בבכורות), אלא אומר שגם בא ללמד ונמצא למד. כמו כן מצאנו בסנהדרין ופסחים (גבי נערה שנאנסה).
* כח:
** מחצה -
יש לדון למה לא מחשבים באי אפשר לצמצם בכל הסוגיה (שגמ' רק מדבר בו בענין אחד). וע'.
** תרי רובי -
אין סברה זו כל כך פשוטה. צריך לומר שאין הענין שמחצה הוא חשוב, אלא שמחצה נחשב כאילו הוא רוב או כאילו הוא כולו. לא כל כך פשוט מהו הסברה. אפשר לומר שהוא שבני אדם לקוראים לרוב של דבר או למחצה שלו אותו דבר, ואז יש לו שם של אותו דבר. אבל, אי אפשר לשני דברים להיות לו אותו שם. גם אולי יש לבאר על פי מה שאמרו האחרונים, והוא שכדי לומר שרובו ככולו, צריך להיות שכולו בעולם (אף שאין לכולו אותו קרק'). אז, אולי כדי לעשות רוב, צריך צירוף מיעוט, ואז אי אפשר לכפול. ותחשב.
* כט.
** כדי שחיטה אחרת -
מעניין שלא פוסלים אותו כיון שמיעוט של השחיטה נעשה בפסול (כמו שידון בו גמ’ לקמן).
** טרפה -
מעניין שגמ’ תולה טרפות במה שהוא רוב. אולי זהו דיחוי של הגמרא. (באמת, לא פשוט מהו דיחוי של הגמ’, שרק אומר, ולא מבאר. אומר שהגדר הוא שונה- ולכאו’, כבר ראינו את זה בתוך הקושיה- אבל לא מבאר למה יהיה כן.)
** דלדם -
זה קצת מעניין. לכאו’, בין כך ובין כך ייצא כל הדם. לכאו’, החילוק הוא רק כמה זמן הולך עד שיצא הדם. ותחשב על זה. (איני יודע אם זה, באמת, נכון. הרי, יש דם שנשאר בגוף (נקרא "דם איברים"), ואולי יש יותר דם שנשאר אם לא חותך הרבה. כמו כן, יש דם שאינו דם הנפש. איני יודע מציאות של דברים אלו, שאיני רגיל להרוג או לראות הריגת בעלי חיים (חוץ מן מיסקיטואים).) כמו כן צריך לעיין בדין שחיטת וורידים, שהרי בין כך ובין כך ייצא דם. (יותר מזה, יש לדון למה לא אומרים שכיון שכבר שוחט את הוורידים, נדחה חילוק זה. אולי מסתבר שגם צריכים דם של שחיטה, דהיינו שבא ממקום שחיטה. אבל, יש לדון אם יכול להיות שתורה יאמר שישחוט יותר, שעדיין אינו ממקום שחיטה. נראה שמקום שחיטה הוא הסימן, ורק אומר ששחיטת מחצה של הסימן מהני במקום שחיטת כולו.
* לא.
** רשי ד"ה דמן חבריא -
עיין במש"פ רשי. יש להעיר שלפשט שני שלו, קצת מעניין שמזכיר שהיה מבית מדרש. מסתבר אם היה אמורא שבגמ’, היה בבית מדרש. יש לדון, שאולי היה צד שהיה מי שלמד בפני עצמו, שלא בבית מדרש. גם אפשר לומר שהוא בבית מדרש אחר, ואמר שהיה בסתם ב"מ סתם שלהם, והיה חבר שלהם.
* לב.
** או פסק -
יש להעיר שבשניהם אומרים פסיקה על הגרגרת. לכאו’, הדין הוא כן אף אם פוסק את הוושט ושוחט את הגרגרת. (היה נראה לומר שאומר מה שיותר מצוי. הרי, קשה לשחוט את הגרגרת, ואז אפשר להיות שאדם יאמר לעצמו שכיון שמסתמא בין כך ובין כך לא יישחט כהלכתו, יפסוק אותו.
* לב:
** אלא -
כמובן, קצת קשה איך נאמר ש"אלו טרפות" רצה לומר "אלו אסורות.” יותר היה מסתבר לומר שרצה לומר אלו טרפות, ואגב הטרפות אומר עוד דברים. אבל, עיין בלשון רשי, שלא נראה שמבאר כן.
** רשי ד"ה לא זזה - -
שכחוה
מן רשי משמע שהענין הוא שלא שכחו אותו התנאים, וממילא היה בכלל המשנה. גם אפשר שרבי לא רצה לשנות דבר שהיה נגד התנאים, והרי הם לא יוכלו לשכוח אותו. אבל, אינו מפני שרבי רצה לכבד את התנאים הקדמונים, וגם אינו מפני שאם יחליפו, ולא ישנו מה שהיו רגילים לשנות, ישכחו הרבה (אבל אולי אפשר לדחוק לומר כן.)
** רשי ד"ה לא זזה -
סדר למשנה- עיין על זה, שמעניין הוא. לכאו’, צריך לומר שלא אומרים שיש סדר מפני שכך קרה ממילא- שככה היה כותב אותו- אלא שרבי תקן בו סדר, כדי שלנמד ממנו ענין סתם משנה. יש לדון, אז, למה לא עשה כן בתוך סדר של משניות. ותחשב.
* לג:
** רשי ד"ה ונוקמה -
עיין במה שפרש"י. עיין ברשי בתחילת מגילה. לפי פשט שלו שם, יש לדון למה לא אומרים שהוא מפני שרבי עקיבא סתימתאה. (צריך לעיין שם, שאין כל הנידון כל כך פשוט. הרי, יש בוודאי שני מאמרים, ובוודאי שניהם מזכירים נקודה שווה- שרוב סתמי משניות כרבי עקיבא. אז, אינו כל כך פשוט באיזה נקודה הם חולקים, אם הוא מה שמשניות הם כר"ע או כר"מ אליבא דר"ע או אם הולכים רק על משניות או אף על בריי’. וצריך לעיין בו ולחשוב יותר.)
** ודלא כרבי יהושע -
צריך לחשוב על זה קצת. לא פשוט מהו קבלה זו. אם נאמר שהוא כעין נדר, אז קשה איך יכול להיות ביטול דעת (כפי שמזכיר רשי). אולי מניחים שנדר מפני שהוא רוצה לעשות דבר טוב, וביטול דעת מורה שזה לא דבר טוב. קשה למה ייתלה בדעת, אז, ולא במה שאינו טוב. אולי יכול להיות נקרא ביטול דעת, אף אם מה שמבטל דעת שלו אינו דעת שאר בני אדם, אלא מה שאינו כפי תנאים הפשוטים מדעתו. (אולי, באמת, כל ביטול דעת כן, ודעת אחרים הוא רק סימן לדבר.) ותחשב. גם אפשר לומר שאינו בלשון נדר, ורק חל כנדר מצווה. אם כן, יש לומר שכיון שאינו טוב ואינו מצווה, ממילא לא חל. אבל, עדיין צריך ביאור למה רשי מזכיר ביטל דעת, שהענין יהיה שאינו, באמת, מצווה. ותחשב. אולי הוא אמונתו במה שהוא מצווה שעושה שיותר קל לו לחול, ולא צריך כל לשון נדר. אולי על זה נאמר שאמונתו ומחשבתו בזה לא חשוב, כיון שבטל דעתו בדעת שאר בני אדם. ותחשב על זה.
* לד.
** טומאה משיעורים -
מצאנו במקומות אחרים שאומר פירכא על ידי זה. צריך לומר ששונה הוא כאן כיון שאין דרשה אמיתית, אלא הוא סברות בדין דרבנן.
* לה:
** בהנאה -
יש לדון למה לא אומרים שכיון שמדמים אותו למים, דינו כמים לכל דבר, שמותר בהנאה ושמכשיר. צריך לומר שלא מס’ לדרוש מכאן כי אם מפני הייתור, ואז זה רק מהני לדרשה אחת. ותחשב.
** ישתה -
כנראה, כיון ששתייתו קרויה שתייה, רואים שיכול להכשיר. זה נראה מחודש לי.
* לו.
** עד גמר -
צריך לחשוב על זה, שלכאו’ נמצא שאם הוא שם בשעת גמר השחיטה, נחשב דם שחיטה, אף שלא בא מן גמר השחיטה. וצריך לעיין/
* לז:
** מהכא -
יש להעיר שלכאו’ יוצא מזה שבדברים אלו אין איסור ממש. אם כן, אין איסור במחשבה ביום שמביא לידי איסור בלילה, כיון שרק עושה את העבירה בגמא. ותחשב. אולי יכול למנות את זה כיון שהוא על כל פנים דבר שאין רוב בני אדם שומרים, כיון שהוא דבר קשה מאד. (שמעתי מש.ו. שפעם בנו יארק סיטי עשו אינרנט חנם להמון, אבל עזבו אותו כשהבינו שיותר מרוב היה בשימוש לדברים שאסורים לראות. לא ראיתי מקור לזה. יש להעיר שזה היה, לכאו’, ברוב בני אדם בלי בתים, ולא שאר בני אדם.)
* לח:
** בסוף -
כנראה מניח שכיון שזה בסוף, גם זה בסוף. גם יש להעיר שלפי רבא, דמיון זה צריך ביאור, שאין כל זה שייך לחיות, אלא למעשים בסוף. ותחשב.
** שלא יהיה הכל -
צריך ביאור, שיש חילוק פשוט, שהרי בקדשים, אי אפשר להיות שליח של הישראל, מה שאין כן בשחיטת חולין. יש לומר שאף בכהן השולח קרבן, אין מחשבת הבעלים מהני. גם יש לומר שעל כל פנים לא יהיה מחשבת גוי שייך, שאין בו שליחות.
* לט.
** הא מקמי -
זה קצת מראה מקום.
* לט:
** אם הוכיח -
הרי, יש בזה מחלקת (כמו שרואים מגמ’ שלנו), ועדיין רק מוסיף בתוך ה"חסורי מחסרא" שיטה אחת. מצאנו מקומות אחרות בגמ’ (ע’ בביצה קרוב לדף כה, נראה לי) שלא עושים ככה.
* מ.
** לשום -
מזה משמע שאין הפשט שלא נאסר מחמת עבודה זרה, אלא שאינו עבודה זרה. ויש לדון, שהרי מצאנו איסור של כיסוי שלו. יש לדון, שאולי יותר מסתבר להיות שאינו עבודה זרה, ועדיין יש איסור (שהרי, למעשה, נעשה לזה מעשה של כפירה בה’) מלומד שנחשב עבודה זרה ואין מה שנשחט לו נאסר. ותחשב. (היה אפשר לומר שבאמת עבודה זרה הוא, והענין הוא שעומד להיבטל (יש לדון למה נאמר כן). אז, כל דבר קרבן או עבודה, שאינם דברים שנמשכים בהכרח לזמן, לא אסורים. אבל, כיסוי, שהוא דבר שננשך לזמן, נאסר. ותחשב.)
* מ:
** עולא מעשה כל דהו -
לומד גמ’ כן ממה שנקט סימן אחד (ע’ ברשי). יש לדון, שאולי רק שחיטת סימן אחד, שהוא חשוב בעוף, נחשב מעשה מספיק.
* מג.
** הל’ כסתם -
צריך לחשוב על זה, ולעיין ברשי. ודע שאולי זה יכול להיות נוגע לסוגיא שבתחילת ביצה.
** ניסא -
נמצא שלא היה הטורח להביא אותו קרוב למיתה ולא להמית אותו, שזה עשה על ידי נס, אלא היה לעשות אותו הנס.
* מג:
** איתחזק -
משמע שבלי איתחזק איסור, ספק דאו’ לקולא. אם נאמר שהאיסור נלמד מאשם תלוי, נאמר שתלויים זה בזה. ותחשב.
* מד.
** בתורא -
יש לדון איך לקרוא את זה- אם אומר שהוא בתור, שהוא בעל שער, או שאומר שהוא בתור שהוא בעל שער. ותחשב. מסתבר כראשון, שאי לאו הכי, קשה למה ינקוט שור בעל שער. יש לדון, שאולי אין סימן אחר, ויותר טוב לנקוט בהמה מוזרת משלא לתת משל. יש לדון, שלא יוודע מה נחשב "בעל שער" אם לא נדע דין זה. יש לדון, שאולי יש שני מיני שוורים. ותחשב.
* מד:
** והא כתיב -
וא"ת הרי גמ’ הניח לעיל שדברים אלו אינם אסורים. ויש לומר שאם יחזקאל מתגאה על כך, היה לו גם כן להחמיר בו.
** הרואה -
עיין ברש"י. מעניין, שזה, כמובן, רק במי שרואה טרפות לעצמו, ושנכון הוא לו לראות לעצמו. מניחים שבני אדם לא יכסו את השוחד של עצמם מעיניהם. לולי רשי, היה נראה לומר שבדרך כלל, אדם צריך לקבל מתנה מאת הרב בפסק שלו, כיון שאי אפשר לתת לו דבר לפסק שאולי ייצא ממנו טוב לו. אבל, אם אף מכיר לראות טריפה לעצמו, לא צריך לקבל מתנת פסק מאחר. ותחשב.
* מה.
** אתייקורי -
תמיד יש טוב שיוצא להמיטיב, ולכן הוא עושה אותו, כמו שמבאר מארק טווין ב"וואט איז מאן.” אבל, נראה שהחילוק הוא אם טובה של הנותן בא ממה שבא טוב למקבל או לא. כאן, לא בא מחמתו, אלא בא ממה שנראה לבני אדם שנותן לו. ותחשב על זה. אבל, עדיין יש לדון למה זה יחלק.
** לרובא -
כנראה, אף שאין חסרון, יש מקום אויר הנראה. לכאו’, מתפשט כיון שיש נקב.
** רשי ד"ה כדי שיכנס -
עיין במש"פ. לולי רשי, הייתי אומר ש"לרחבו" מגיד לנו שצריך להיות נכנס כל עיגול שלו. (רצה לומר, כשנחשוב על פאני, יכניס אותו כשאברהם לינקולן מצדד כלפי הנקב, ולא כשהצד הנמוך (שאין בו לא אברהם לינקולן ולא בית) מצדד כלפי הנקב. ותו"ת.
* מה:
** מסתברא -
בזה (ובכמה דברים אחרים) קצת מעניין שיש לו מה שהוא מסתבר בזה.
** רשי ד"ה מתני -
מעניין שרשי נוקט איזה לשון יותר מסתבר. חושב אני שמצאנו שגם הרשבם יעשה כזה.
** רשי ד"ה אבא -
לצד שקרא לו אבא חברי, מסתבר שעל שם שמו קרא לו כן. ויש לדון, שאולי היה רב שלו וחבר שלו או שהיה חבר חשוב שלו, ולכן קרא לו כן.
* מו.
** פרשיות -
צריך לעיין בסוגיה זו.
* מו:
** כמאן -
מעניין לתלות שניהם זה בזה.
* מז.
** רשי ד"ה יתיר -
זה קצת מעניין, שהיה אפשר לומר שתלויים זה בזה, שיתר כמאן דנטול, ואולי חילוף הוא רק חסרון ויתרון. אבל, עדיין משמע כן מלשון הגמ’.
* מז:
** רשי ד"ה ככוחלא -
עיין במה שמבאר רשי. הדרך שמבאר אותו קצת מעניין.
* מט.
** אימא אוכלים -
נמצא שלא צריכים הוכחה שלא נקב אותו, אלא רק צריך שאין הוכחה שנקב אותו. צריך לעיין את זה.
** ישמעאל כהנא -
לא נראה שמוכרח שהיה כהן, שאולי רק נתן סימן במה שהיה ישמעאל ידעו שהיה כהן, שהוא ישמעאל כהן גדול.
** רשי ד"ה אין הל’ -
עיין במש"כ; זה מעניין.
* מט:
** רשי ד"ה התורה -
צרי עין- יש להעיר שהם אוהבים את הממון שלהם יותר, ויותר מסתבר לחוש לממון שלהם.
* נ.
** רשי ד"ה אמר מאן דהוא -
מעניין שאמר אותו בלשון רבים. אולי הוא על שם רבינא ורב אשי, ואולי הוא על שם כל הישיבה. (עיין ברשי לעיל גבי קביעות פסק.)
* נ:
** כמה יתר -
צריך ביאור למה לא רק אומר שהוא יותר מסלע, שהרי שיעור זה נראה שוהא מאד יותר קל לחשב משיעור שנותן גמ’.
** רשי ד"ה גדולה -
נראה שבא למעט מן הצד שרצה לומר שהגיע לגדלות שלו.
* נא.
** אפילו הכי -
יש לדון אם הצד הוא שבדקו (וחשו לרבינא) או שמצאו כרבינא.
* נא:
** שיצא דרך דופן -
לא ידעתי שזה מותר בי"ט.
** הא קדמיה -
ק"ק, שעדיין צריך מלא קומתו, וקשה להגדיר כמה יהיה. כמו כן, צריך ביאור למה מים דקיימי ומים שהולך לאידך גיסא שווים.
* נב.
** רתח -
נמצא שיש הנחה שת"ח ירתח על טעות בדין (וגמ’ אף מצדד שהוא אף דבר שלא יביא לידי עבירה).
** רשי ד"ה בר זכאי -
לכאו’, רשי בא לומר שאינו בר זכאי הידוע, שהוא ר"י בן זכאי.
* נג.
** בדכוותיה -
מעניין לי שיש עופות דקות כגודל נץ. (זה משמע שאינו אייג"ל.)
** ונמצא -
לכאו’, הסיבה שלא מסתבר שבא מן הכותל הוא שלא מסתבר שיפול מן הארי לתוך כותל, כמו שלא מסתבר שיפול ממנו לתוך בהמה. אז, לכאו’, מה שרוצה לומר הוא שאין כאן הוכחה, שהרי מה שנמצא צפורן לא מוכיח כלום. ותחשב.
** כל -
זה לאו דווקא, כמו שמעורר גמ’ ביבמות (לז) וכתובות (טז).
* נג:
** רשי ד"ה לפרסומי -
קליש- מעניין, שהיה נראה לומר שכל גופו קלוש, ולכן הוא מת בארס של הנץ. ויש לדון. גם לא פשוט שחלקים ממנו שהם גרועים וגורמים לזה הם אותם חלקים שמרשים לו לראות. ותחשב.
* נד.
** ולא נהירא -
זה מראה מקום. אגב, זה גם משמע שר"ל היה תלמיד עם רבי יוחנן. ע’ בגמ’ ב"מ וברשי ותוס’ שם.
* נד:
** רשי ד"ה מפניהם -
רשי מזכיר כבר מה שיאמר גמ’ לקמן.
* נה:
** שהרי חותכה -
בכ"מ, רשי נותן משל השני לזה, ולא הראשון. (ע’ בב"ח.)
* נו.
** מקום שעושה -
לא רצה שעושה אותו טריפה אם הכה בו, שזה לא אומר כלום, אלא מקום שעושה אותו טריפה אם יש בו נקב.
** אגב רוכביה -
אז, יש לשאול לאידך גיסא למה לא חוששים לאיבוד ממון. צריך לומר שאין דרך יותר טוב לבדוק. גם יש לומר שחולקים מה יקרה אז, שחולקים במציאות הקרום. דחוק. גם יש לומר שחולקים איך בודקים, אם דוחפים בכוח או בקלות.
** עקומות -
מעניין שלא אומרים שכמו שנסתם הנקב עכשיו, נסתם עד כדי שלא ימות ממנו. נראה שבדרך כלל, אינו כל כך אדוק לעצם כמו שהוא עכשיו, ורק עכשיו, שדוחק, אדוק הוא. ותחשב.
* נו:
** בטרפחת -
כעין זה מצאנו בשבת.
* נז.
** אין ריאה -
זה מראה מקום.
** אינו בקי -
מעניין, שלכאו’ היה פוסק שאלות לבני אדם, וקשה איך קרה שלא ראה ריאה של עוף.
* נז:
** רשי ד"ה אהימנותיה -
רוח הקודש. יותר מזה, היה יכול לדבר עם בהמות, ואז אפשר להיות שדבר עם נמלה. ויש לדון אם היה יכול לדבר עם נמלים, שאולי היו קטנים יותר מדי.
* נח.
** ספנא מארעא -
מעניין שלא אומרים שהקרקע גרם עמו. ותחשב.
* נח:
** ואסורה -
יש לדון בזה, שגמ' אמר לעיל שמשנה לא רצה לומר "או טרפות," אלא "אלו אסורות., כיון שזה נמשך מן אותו המשנה, קצת מעניין שלא נאמר בו אותו דבר. ותחשב.
** סם המוות -
אינו כל כך מובן איך יאמר שיש שני מיני סם המוות, שהכל יהיה נכלל כבר ב"סם המוות." נראה שאולי סם המוות רק משמע סם, ולא אוכל שממית. ותחשב.
** מים מגולים -
יש לדון למה לא חוששים לסכנה כאן. צירך לומר שכיון שכבר היה במעי בהמה, לא הורג עוד.
* נט.
** שני -
איני מבין כל כך איך יכול להיות לו רק אחד, ומה עשוה אותו קשקש. אולי רק בא לומר שלא צריך יותר משנים. ותחשב.
* נט:
** כי הוה מתרחק -
אולי זהו שייך לסיפור של מט. ויסוויאוס.
* ס:
** מכאן -
מניח שבאמת יש חיה כזה. לכאו', אם אדם כתב אותו, לא ירצה לשקר ככה, שימצאו אותו בדאי.
** דרי שיני -
נראה שהיה מנהג שלהם ללבוש שינים, אולי כעין נאקל"ס, ועל זה אומר שהיו להם כמה שורות.
** גלוותא -
קל למצוא מזה נכפל במאה.
** גלוותא -
נראה שאולי לכן מזכיר ה' מה שהיינו עבדים, לא רק מני שאז לא נהיה רעים לגרים, אלא אף שנכיר שאין אדם פוסל במום שלו.
** רשי ד"ה לשרפם -
מן רשי משמע שאסור לחבר דברי תורה עם דברים בטלים.
* סב:
** באתרייהו -
יש לדון למה הולכים אחר מקום שלהם, שאינו רוב העולם.
* סג.
** אין -
מעניין שמשיב כן, שאינו תלוי במנהג, אלא בפרס ועזזניה. באמת, ק"ק למה לא ייתלה במנהג, שמצאנו הל' שתלויים בזה. יותר מזה, יש לומר שלמקצת מקומות יש מסורה ולמקצת מקומות אין מסורה.
** ההוא ביידא -
כנראה לא חשש גמ' למה שאינו סימן כל כך טוב.
** זה עורב -
דיון גמ' זה (וע' ברשי כאן ולקמן) מעניין; כ' לפני זמן קצת שיעור עליו.
* סד.
** אם ריקמה -
נמצא שחייב על ביצת שרץ. איני יודע מהו המקור לזה.
* Footnotes
[fn:1] אגב, נראה שזה המקור למה שחיברו שיר עם המילים "אין דבר רע יורד מן השמים." אולי בכלל לא הבינו את הגמ' או אולי יש להם שום מקור שמביא את זה מוסר שיש בו. מסתבר לי שרוב דרשות של מוסר הם כעין אסמכתות של רמב"ם, שהוא דרך לתלות אותו בתורה, והרי תורה היא דבר חשובה, ונזכרת. ותחשב.
