* ב.
** אמר ליה -
משמע שהיה רב אשי מקשה קושיא זה. ר"ל, בדרך כלל, כשגמרא מקשה קושיא, אומרים ש"גמרא" מקשהו. בדרך כלל ההבנה לזה הוא שכדי לסדר גמרא, יכתוב ר"א את הקושיא שיהיו עסוקים בו. אולי כן קרה כאן, אלא שדנו במה עסוקים, אבל יותר משמע שהיה דבר קשה לו, ואז אמרו אמורא בגמרא בסתם. זה מעניין. ותו"ת.
** ואף ר"מ -
המקור לזה הוא מגמרא נדרים (שאי לאו הכי, אין המשנה שם יכול להיות כשום תנא). יש להעיר ששם יש דרך אחרת לבארו שמוכרח להניח שאומר ר"מ דינו בכל, ואף ב"הרי עלי.”
* ב:
** אנא שחיטתן כשרה קשיא לי -
לשון זה מעניין, שמשמע שהיה אומר שלא היה קושייתו מן הסתירה אלא מלשון שחיטתן כשרה. זה אינו, שעדיין מקשה מסתירה. רק אומר שאם כן, ששניהם בדיעבד, שחיטתם כשרה קשיא לי. ותו"ת.
** תרתי דיעבד -
היה יכול גמרא להשיב לומר שמרבה שני ציורי דיעבד. יש לדון, שאולי שניהם יהיו נתרבים מראשון. יל"ד.
** אהייא -
לכאורה, ההכרח שאינו על חרש שוטה וקטן יכול להיות שלשון כלם משמע שקאי על יותר מאחד. יש לדן אם זה מה שאומר גמרא (אם לא זה, מקשה שאומר נאו"ן שוב, ואף שכבר היה דן בהם, ואין צורך לעוד נאו"ן).
* ג.
** קשיא -
עיין במקום אחר במה שבארנו איך ידחה גמרא קושיא זה. גם יש לומר שכיון שרק מקשה למה אומר לשון רבים (אולי- ועיין לעיל). אם כן, אולי אומר שכיון שזה מתירו, ואף שהוא לכתחילה, יכול לומר לכולל שניהם בלשון זה. ויש לדון בשאר. ותו"ת.
** המניח -
עדיין הוא קשה לאביי, שהרי אינו צריך (ולא מהני) שיטעום, אלא בלי זה מותר.
** מומר למאי -
היה אפשר לומר שאומר דין מומר לע"ז. נראה שנקט כרבא כיון שכן הלכה.
* ג:
** יודע לומר הלכות שחיטה -
מעניין למה לא אומר "יודע הלכות שחיטה.”
** לעלופי לא חיישינן -
אומר לשון חלוק מ"רב מומחים.” משמע, אולי, שהוא סברה חלוקה. יש לדון מהו. גם יש להעיר ששולחן ערוך כולל שניהם בלשון אחד של "רוב הרגילין לשחוט הם בחזקת מומחין ומוחזקין.”
גם יש להעיר על לשונו של "רב… מוחזקים,” שלכאורה, רב אינם מוחזקים, אלא רב לא מתעלפים, שמוחזק לא אומר שלא יתעלפו, אלא שיש לנו ידיעה מכבר עליו שאומר שלא יתעלף. ותו"ת.
** רב מצויין -
יש להעיר שלשון גמרא משמע שהוא רק רב שמצויין לשחוט (דהיינו, שממה שרוצה לשחוט יש להוכיח היתר זה), ולא שרב בני אדם כן הוא.
* ד.
** אלא כיון -
לכאורה, כאן אין צריכים זה, שמה שנוהגים כן מראה שסוברים שנכתב בתורה.
** מן התורה -
לא בא למעט צד שהוא הלכה אלא למעט צד שנלמד מהיקש.
* ד:
** כדרב ענן -
נמצא, אז, שכיון שאיתותב ר"ע, יש ראיה לרבא.
** אחאו -
מעניין שלא היה נחשב מין. (ואולי רק אחאו היה כל כך אדוק, אבל לא אנשיו.) ואולי יש אותו דין למין. עיין לקמן שאומר שאינו כן, שיש לחוש שמכוון לעבודה זרה.
** אחאו -
יש להעיר שלכאורה, רב אנשי אחאו היו עובדים מאהבה ומיראה. אפשר שלכן חולק רבא (לשיטתו בסנהדרין), ואז יש לו ראיה מאותו ברייתא, ואז סובר שמומר לשחיטה כשר. גם יש לומר שזהו קושיית גמרא שמצריך "מושל מקשיב.” (צד ראשון יאמר שמה שלא מתו כדי שלא לעבוד מאהבה ויראה גם עושה אותם רשעים. ויש לדון, אלא שלכאורה, כעין זה מוכרח, דאי לאו הכי, לא ימות לעבודה זרה לעולם, שבהכרח יהא ליראה. ותו"ת.)
* ה.
** לא היה מפלג -
כיון שהגענו לזה, אפשר שזה ידחה כל שאר הקושיות. ויש לדון.
** לא היה -
כיון שנדחה דברי ר"ע, יש לדון איך לדחות ראייתו מכאן.
** מאי גורן -
צריך ביאור מה זה אומר.
** על פי הדבור -
צריך לומר שעובדיה ידע שהיה על פי דבור. אפשר שלא ידע שבא מבית אחאו.
** על פי -
יש להעיר שהיה יכול להקשות לרב שהוא בשר שנתעלם מן העין. (לזה, אי אפשר לומר מש"כ בד"ה על פי הדבור).
** קטנה דמן -
היה אפשר לומר שהיא נערה דמן קטן, אלא שלא מצינו מקום הנקרא כן. (אבל גם לא מצאתי מקום הנקרא נעורן).
** מומר לנסך -
אין צריך כל זה כדי להקשות, שמקשה ממה שאומר "מנסך…” ואולי בא להפקיע מדיחוי שלא ר"ל מומר אלא מין.
** מכם -
מעניין מה שמניח גמרא שמה שהוא מומר לזה יהא מומר לזה, שלכאורה, כאן הבעיא הוא (ויש לדון) שמא פסל את השחיטה, ולא שמומר פסול בעצם. ותו"ת. (יש להעיר שמומר לאותו דבר פסול בחטאת. מעניין מה שלא מקשים מזה לרבא. משמע ששם פשוט לגמא שהוא דין שרק שייך לחטאת.)
* ה:
** ואמרינן -
נראה שהביא זה להוכיח שאין לומר שזה קאי על מומר לחד דבר. ותו"ת.
* ו.
** אינהו -
היה אפשר לתרץ שהוא לענין שבת (כהמשך גמרא).
** אלא… ולא קבלו -
יש לדון, אז, למה הוצרכו למה שאמר להם; כבר היה ידוע מימות ר"ג מה רצה לגזור. אפשר שלא ידעו אותו מעשה (וצריך לומר שאנו שיודעים אותו יודעים אותו ממקור שלא היה ידוע להם. עיין כעין זה בשיחתא דש"י (פאה פ"א ה"א).).
** אפשר גזרו -
משמע שאף אי לא ידעו להתירו, כיון שהו מותר, אינו נחשב תקלה. כמובן, יש לציין לגמרא חגיגה וכ"מ שאומר ר"ע "וכי מה חטא… אלא [שכוונה לחטוא שלא ידעה שבעלה התירה." גם יש להעיר למה שכ’ שי"ח ש"י להוכיח שתלוי במה שחושבים לאיסור. צריך לומר שתלוי בשניהם. ותו"ת.
* ו:
** בן זרוז -
יש להעיר שהיה אשת ר"מ ברוריה בת ר"ח. אם כן, קשה איך היה בן חמיו בן זרוז. אפשר שהיה לו שני נשים (או בזמן אחד או בשני זמנים). גם אפשר שמפני שהיו רודפים משפחת ר"ח, היה משנה את שמו.
** והלא -
לא ר"ל שידוע לנו שכן עשו, שהרי לא עשו כן, שלא ביערו את זה, אלא ר"ל שמסברה היה נראה לנו שבערו את הכל. גם אפשר שר"ל כל שאר ע"ז. ויש לדון.
* ז.
** הולך -
לכאורה, שני "הולך"ים חלוקים, שחד אומר שהולך לעשות מצוה וחד אומר שבהליכתו עושה מצוה.
** דבמצוה -
יש לדון למה לא אמר שהוא מבני לוויה. אפשר שזה סיבה יותר חזקה. גם אפשר שיש רעות רק אי כל בני חבורה באו חוץ מן אחד. ותחשב.
** אלא
- עיין בתוס’. משמע שסברו שהיה מותר לקיימו. לא משמע כן ממה שאומר גמרא שמקום הניחו…. וצריך ביאור.
** מה בחייהן
- עיין ברשי. גם יש לומר שקאי על מה שהיה תור. גם משמע כן, שהרי היה רוצה להנות.
** אלא אם כן -
אפשר שזה רק לר"ח, שלשאר בני אדם יש כשפים.
* ח:
** אגב דוחקא -
מוזר מה שיש דוחקא שאין לדחוק, שאז נטרף.
** אבר מן החי -
יש לדון למה לא מזכיר דם.
** אבר מן החי -
זה רק אם נאמר שהוא עומדת לאברים, שאין צוואר, לכאורה, אבר.
* ט:
** ספק -
יש לדון למה צריך לימוד בין ללימוד ספק לחומרא ולקולא גבי טומאה.
* י.
** ואילו -
קשה, שכאן יש רב (כמו שמבואר מרשי).
** עצם -
יש להעיר שאין ודאי אלא שעצם פוגם, ולא שכל שבא לידו כבר נפגם.
** הרי טבל -
יש להעיר שגבי בהמה בוודאי שינה ממצבו הראשון, שמת, אבל כאן, מי יימר שקרה לו כלום.
* י:
** חזקה -
לא מוציא למסקנא מקור לו. ואולי צ"ל שהוא הלכה למשה מסיני.
** דקיימי
- יש להעיר שמשמע שסבר שאף שלא ידע כהן שלא פשה, אמירתו מטמאו. אף זה, משמע, הוא רק אם, למעשה, לא פשה. ותחשב.
** דלא אכל בשרא -
מעניין למה מקשה רק על זה. אפשר שהוא מפני ששאר אינם מיעוטים המצויים. יש לדון אם זה נחשב מצוי.
* יא.
** רב מצויין -
לכאורה, יש מכל גמרא זה ראיות שרב מוחים אצל שחיטה. אם כן, קשה איך חולקים בזה אמוראים. יש לומר שיש אמוראים שסוברים שתנאי הוא. ויש לדון.
** חד סימן -
משמע שאם ראה ששחט אחר שלם בטוב, מוחזק. יש לדון למה, שלא נחזק בחד פעם. ויש לדון.
** אמר רבא -
עיין לקמן שמקשה גמרא למה צריך רבא לבאר שני פעמים שזה הוא שיטת ר"נ. יש להעיר שכאן גמרא הוא שמניח שאין זה שיטת הכל. אפשר שמניח (וצריך ביאור מהיכי תיתי. ואולי היו שם, ואז ידעו) שרבא הוא השואל, ושואל כדי להשיב זה. גם יש לומר שהיה יכול לומר שזה דברי הכל. צריך לומר שהיה דן מי הוא התנא ולא רק מי סובר שאין צריכים דעת.
* יב:
** מאי שנא -
משמע שלולי זה לא היה קשה, ואף שלכאורה, היו המשניות ידועים. ואולי רק אומר מה שהוא יותר קשה. ותחשב.
* יג:
** אמר ר"נ אמר רב"א -
יש להעיר שמה שמפרש גמרא לקמן (כשמביא גמרא את זה ודן בו) משמע שאין זה הדין שמכוון רב"א לומר. וצריך ביאור.
* יד.
** ברירה -
מעניין שנוכל לומר על ידי ברירה שהיה עומד לזה (ויש לדון למה לא), שאז, לכאורה, בהכרח לא יהא שום מוקצה. ואולי יש אם חשב בפירוש על דבר לתשמיש אחר. ויש לדון.
* יד:
** אוכל דאיפרת -
לשונו משמע (מדלא רק אמר "כאן הוא עושה מלאכה, שעומד לאכילה) משמע שלא אמר שלאותו מלאכה היה עומד (ויש לדון למה לא). אלא, משמע שסבר שדין זה (של עמידה למלאכה ראשונה) הוא רק אם שינה. ותחשב.
* טו:
** כגון שהיה חולה -
קשה למה לא אמר, אז, שמשנה הוא כשאין לו חולה.
* טז.
** אמר ר"פ -
תלוי בדיון גמרא (בכ"מ. ונמצא בקידושין במימרת ר"ל שיש להוקים כשני ציורים) אי יש להוקים משנה בשנה טעמים או שני תנאים. ותחשב.
* יז.
** בשר נחירה -
יש לדון מהו צד ראשון:
1. הפשטות הוא שאומר שכל דבר אסור היה מותר להם, ואז בוודאי היה זה מותר להם.
2. אפשר שיודע שרק שלל מגויים מותר, ורק סבר שסברה זה (שהיה מותר כבר בעת שחיטה) הוא סברה יותר חזקה מסברת שלל גוים. ותו"ת.
* יח.
** אלא… חדא מילתא -
יש לדון אם ר"ל שאז מוכרח נגד מה שאמר רבי יוחנן, שרק אלו יכולים להיות חד מילתא, או שר"ל שכמו שאלו יכולים להיות חד, אלו יכולים, ואז אין לומר שמדויקת משנה כן.
* יט.
** כי נפקא… רובא -
מעניין מה אומר, שאם אומר שצריך שרובו בשחיטה, אינו צריך להיות אותו חצי. אלא, צריך לומר שר"ל שכשנשחט רובו, רוב של רובו (שכן משמע) צריך להיות בשחיטה. זה מעניין. ותו"ת.
** לא תהדר בך -
רצה לומר שלא רק הוא אמר כרב, שכן מוכרח מדין ראשון שאמרת משמיה דרב. ותו"ת. ותח’.
* יט:
** מסרק -
היה יכול לחלק לומר ששם לא נגמר שחיטה בהגרמה. אפשר שלא סבר שזה בעיא. גם אפשר שסבר שאין חידוש, אז. ותו"ת.
* כא.
** שדומים -
קשה מה, אז, כוונתו כשאומר, “או רב שנים,” שכבר אמור. ותו"ת.
* כב:
** דומה -
מעניין, אז, למה אומר דין תורים קודם בברייתא כיון שאי אפשר לדעת אותו עד שיודע כבר דין שני שבבריי’.
** מן -
יש לדון מהו דרשה זה:
1. אומר שיש זמן שפסול בשניהם. יש לדון אם לשון דרשה משמע כן כל כך.
2. אומר דרשה אחרת לומר שאין זה בגדולים ואין זה בקטנים. שוב מגדיר מה נחשב גדול וקטן. ותו"ת.
(אולי על פי שני, יש לומר למה שהק’ ד"ה דומה, שאולי גמרא לעיל הניח כדרשה זה).
שוב ראיתי שמקושיית גמרא (צריכים קרא למעט ספק), לכאורה, רואים כצד ראשון. ותו"ת.
* כד.
** כשר בכהנים -
יש להעיר שכאן רק ר"ל שיש שכשר בכהן… ולא שכל הכשר, פסול ללוי.
** פוסלים -
קצת קשה למה לא אמר, “מה לכהנים שחסרון בגדים פוסל בהם.” משמע שמה שעושה חסרון בגדים אינו חסרון של כהונה (אף שאומר שכהונתם עליהם רק כשבגדיהם עליהם). גם אפשר שיודע גמרא שלא פוסל חסרון בגדים באופן שווה לפסולים אלו. ותחשב.
** קול -
ואם תאמר למה לא ממעט גם את זה מ"זה אשר ללויים.” יש לומר ששאני זה שיש קרא לרבותו. גם יש לומר שאין זה פסול בלוי (אין זה משנה את גופו), אלא עושה שלא יכול לעשות עבודה (יש בעיא במעשה). ויש לדון פסול זה כן ואם אין כל פסול כן. ותו"ת.
* כד:
** טמא בכלי חרס -
שניהם נטמאים במשא וכדומה. אז, יש מה ר"ל:
1. יש מקומות שטמא… (כמו שבארנו גבי כהן).
2. בענין טומאת מגע, כל מקום שכלי חרס… . זה מניח שנוכל לקרוא טומאת אויר של כלי חרס טומאת מגע (ויש להעיר שהוא טמא בכל זמן שיש טומאת מגע).
3. יש להעיר שזה לא יהני אם נאמר שאהל נקרא מגע.
4. גם יש להעיר שלכאורה יש עדיין שוויון אחד ביניהם, והוא נגיעה על פנימי. יש לדון, שמוכרח שלא יהא שייך בכלי חרס.
** העידה -
משמע שתורה לא עושה טומאה, אלא מעיד שהוא שם. ותו"ת.
* כה:
** אמרי לה -
יש לדון אם קאי על ריב"י או חולק עליו.
* כו:
** קודם -
יש לדון מה חילוק יש, שבהכרח יפסיק לאחר קול ראשון של תרועתו. אולי יש נפק"מ אם אחר כן יתקע תשע או שמנה. גם יש לומר שזה סמך לתקוע כמה שעושים מקצת בנה אדם שהוא undulating קול.
* כז.
** וורידים -
לשון משנה משמע שקאי ת"ק על "שחיטתו כשרה,” אבל מגמרא מבואר שרק קאי על היתר בשר, אף שלא היה משנה דן בו. אולי יש לבאר לפי צד ראשון שכתבנו בד"ה אלא (יח.). ותו"ת.
** על רובו -
נראה אולי שגמרא בקושייתו הניח שלא היה "השוחט" קאי על "רובו של אחד…" לומר, “ו[השוחט] רובו של אחד…,” אלא היה אומר שרב סימן יש לו דין כולו, ואז אם חותכו נחשב חיטה. באמת, יש לדון אם דין רוב נאמר כאן על מה שעשה רב מעשה שחיטה או מה ששחט רב הסימן. במסקנא, אולי סבר שעליו קאי. גם אפשר שסבר שכיון שהם קרובים, אף שלא עליו קאי, אמר לשון דיעבד אגבו. ותו"ת.
** חתהו -
לכאורה, אין צורך לו לומר כן ולא לומר חטהו.
** ותנא -
צריך ביאור למה אמר כן כיון שכבר אמר שיטת תנא דבי ר"י, שהיה תנא כמו זה.
** ר"ח -
לכאורה, גם על זה קשה איך ידע הלכות שהייה וכדומה. ונראה שהיה מקשה גמרא למה לנו לדורשו; ממה שיש הלכות למשה מסיני עליו, מסתמא מבאר את הכל (שלא יהיו הל"מ שלא אומר כל המצות). קרא זה לא מיותר בדרשתו. ודחוק. ודע שזה גם כן קשה על ר"א.
* כז:
** אסיפה -
היה אפשר לומר ששאני הכא שהוקשה לבהמה. יש לדון, שאם כן, נאמר שיש לעוף להיות לו דין בהמה, ואז אף דג יהא הוקש, ולא יידרש, ואין מה להפקיע עוף מאותו דין. ותו"ת. ואולי שאני כיון שהוא היקש מהיקש. ותו"ת.
* כח:
** מחצה -
עיין במקום אחר שהערנו שמוזר מה שמניח גמרא שכל דבר תלוי בכל. אפשר שלא מניח כן אלא מפני שכן אמרו, שלשונו משמע שחולקים בכל, ולא רק בשחיטה.
* לא:
** סתם -
היה אפשר לדחות כהוה אמינא של גמרא לעיל (ע"א) שאין לדייק.
** ועוד -
קשה, שלכאורה, זה אותו קושיה. ותחשב.
* לג.
** מסייע -
יש לדון מהו הסיוע:
1. אולי מוכיח שהוא מותר.
2. אולי מוכיח שיש דבר טוב בו.
* לד.
** על טהרת קדש -
מעניין, שאף אי לא הוכשר, אי היה קדש, היה הוכשר. ותו"ת.
* לח.
** עד -
לכאורה, היה יכול לדחות שהוא קל מדרבנן רק במה שיכול להיות בתחילה. נראה שמניח שלא קאי על זה ממה שלא אמרו בפירוש.
* לט.
** יש לדון איך לר’ יוחנן
נוכל ללמוד חוץ מפנים, שיש פרכה דר"י. צ"ל שיסבור כצד שאמר גמרא שהוא מחלקת תנאים. ותו"ת.
* מב.
** מנא לן -
יש להעיר על הלשון, שלעיל שאל לרמז (ולא מקור), וכאן אומר "מנא לן."
* מג:
** רובו -
יש לדון אם זה רוב ארכו או רחבו. ותו"ת.
* מד.
** כאן לאחר -
יש לדון למה איחר את מה שהיה קודם. אין לומר שמשנה לא זזה ממקומה, שלכאורה, יש סדר בתוך משנה, ואז אין לומר כמה שבאר רשי לעיל (סוף פרק שני?)
* מה.
** ארוך -
יש לדון למה צריך אותו אחד ארוך; בכל זמן שיצטרפו יהא הדין כן.
** אין בהם חסרון -
במקום אחר, הקשיתי איך יצטרף כיון שאין לו חסרון. נראה שאף אי אין חסרון, אין כתלי נקב נוגעין, אלא שמה שמנקב דוחק הכתלים. החילוק בין אי יש חסרון לאי אין חסרון הוא שאי אין חסרון, רק דוחק, ואי יש חסרון, דוחק ומוציא. מה שמצטרף, אז, הוא רוחב הפתח שנעשה בדוחקו על ידי מה שנכנס.
* נ.
** מקיפים בקנה -
יש לדון אם זה אומר שמקיפים באותו קנה או בקנה אחר, אלא שצריך להיות החוליא שכבגד אותו חוליא. ויש לדון.
* נ:
** לפני רבי -
קשה, אז, מהו הדיון, שרבי כתב המשניות, וסבר שכן הוא. אולי החולקים סבר שזה לא קרה או שרבי לא קיבל את זה. ואם תאמר אם רבי כתב את המשנה, למה היה צריך למי שיגיד לפניו; ידע למה כיוון. ויש לומר שלפני המשנה, היה ברייתא שאמר אותו לשון, ועליו דנו.
** נמצא עליה -
לקמן מבואר שקאי על ניקב מצד אחד. אז, לכאורה, אם ניקב משני צדדים, אף אם אין דם, טרפה הוא.
* נא.
** קורט דם מניין -
מניח שאין מכה של צד אחד עושה קורט דם.
** צימרא -
אף שר"ל חמימות, כמה שאומר רשי, היה אפשר לטעות לומר שר"ל צמו. אז, אולי טעות זה הוא המקור למה שאומרים שה"fur flies” במריבה. ויש לדון.
* נב.
** והילכתא -
כיון שהלכה לעולם כר"א (איני יודע המקור לזה, אבל כן מניחים פוסקים), אף פושט מהו המחלקת.
** והאמר ר"י -
היה אפשר לומר שחולק, כמו שמצינו שחולק כמה צריך. אולי לא משמע שמה שהוא כל כך פשוט לרב עד שגער קצת יהא רבי יוחנן חולק עליו. ויש לדון.
* נב:
** מתקף -
לכאורה, זה לא קאי על דיון גמרא לפני זה. ותו"ת.
* נג:
** אי בעית -
לכאורה קאי על מה פירוש "לא שמיעא לי.” יש לדון אי אף כאן רצה לומר שלא ס"ל כן, שסובר שחזר בו, או שר"ל שממש לא שמע כן, והוא שלא שנו את שיטתו כיון שחזר בו.
* נד.
** ולא נהירא -
משמע שהיה ריש לקיש תלמיד של רבי. אפשר שרק היה רבי יוחנן כבר אומר מי היה רב לו. ותו"ת.
* נה.
** אסור -
קצת קשה, שאז לא מלמד דין שבא ללמד, שדלמא היה ניתר בשחיטת בהמה, אלא שבהמה טרפה.
** ניקב -
קשה, שאם כן נאמר כן לעיל גבי חסרון ריאה. ועיין שם.
* נו.
** בפלוגתא -
יש שני דרכים לקרא את זה:
1. אפשר שהוא "בפלוגתא של ר"י ור"נ …” לא משמע כן, שאם כן, היה לו לומר "דחד.”
2. אפשר שהוא "בלוגתא, שהרי …. “ אם כן, משמע נגד רשי בבא קמא (עד) בביאור לשון בפלוגתא. ויש לדון. ותו"ת.
* נז:
** מתנוונה -
יש לדון מהו הדין אם לא משנה. אולי זה לא קורה. גם צרך לדון על מה מתנוונה- על עצמה? קשה, שאז כל זקנה יהא טרפה. על חבירה? אם כן, אפשר להיות שלא עדיך ולא גרוע.
* נח.
** בנקבה -
יש לדון אם זה רק אי אף לא חיה או לא. גם יש לדון אם צריך להיות שלא יולדת אם לא חיה (דהיינו, שאפשר שיש סימן בשנים ביחד אלו, אפשר שיש סימן רק בזה, ואפשר שיש סימן באיזה מהם.)
** אי הכי -
לשון זה מוזר, שהוא קשה לכולי עלמא.
* נח:
** עד כאצבע -
לא הבנתי כל כך מה זה אומר.
* נט.
** מישתלח -
יש להעיר שראש בנזיר מנסה למצא ציור שלא יהא לאדם שער ולא עור … . היה אפשר לו לנקוט שאין לו צער מחמת זה (שאכל זה). ותו"ת.
** גמל -
עיקר תירוצו הוא, לכאורה, שאומר חוץ מגמל. אם כן, קשה למה צריך לשנות את כל המימרה. ותו"ת.
* סב:
** כי רפי -
יש לדון בשקלא וטריא:
1. אפשר שסבר גמרא שכמו שכאן מקילים לומר שאינו צריך להיות נקלף ממש, נקיל אף בסכין. אומר גמרא שהם קולות חלוקות.
2. אפשר שסבר גמרא שכיון שנקלף בסכין כשהוא קשה, ייקלף ביד כשהוא רפוי. אומר גמרא או שאינו כן או שררק נקלף בסכין כשהוא רפוי.
* סג.
** יג מדות -
יש לדון למה צריך לזה, שלכאורה פשוט הוא, שהרי אומר קרא "[אלו העיפות] … ,“ ואז בוודאי מונה את העופות.
** שהביא -
עיין בגיטין (ע?) כשאומר מעשה זה, ששם אומר שלא ממש הביאו, אלא נטלוהו בניהו ממנו.
** שנהגו -
היה אפשר לומר שר"ל שמחלקת הוא, ותלוי במנהג ככמה דינים. צריך ביאור ל"ל אומר כן.
** זה הנץ -
צריך ביאור למה אינו מקשה כמו שהקשה על עורב.
** לא -
מעניין שמצינו ש"לא" יאמר "לו" (ונדרש ממנו), אבל לא מצינו ש"לו" יהא אומר "לא.” נראה שאולי וי"ו ואל"ף יכולים לשמש לחלק מנקודה. אז, “לו" הוא, בעצם, “ל," אלא שברוב פעמים יש לו נקודה אחרת (ואין בעיא אם יהא נקודה אחרת לו. ויש לדון.) “לא" הוא "לא,” שלאיזה סיבה ידע גמרא שאין אלף נקודע, אלא אות שלא. אז, אי אפשר להיות שייכתב בלי אלף זה. אבל "לו" אפשר ליכתב בלי אותו "ו" ואפשר שיהא לו עוד נקודה אחרת, שהוא אלף, וצריך לומר שצריך שום הוספת נקודה, שאם לא כן יהא מוזר מה שלא מצינו ש"לו" יהא "ל". ואולי אין רוצים שיהא מילה שהיא אות. ויש לדון.
* סו:
** וכן תנא -
מעניין שעושה תנא דביר"י וכן לאמורא. יש לדון.
** יגדיל תורה -
קשה, שיכול לומר עוד ועוד סימנים, אז. משמע שיש שום ענין בז. ויש לדון.
* סז:
** בהמה בשחיטה -
עיין ברשי. אם כן, יש לתמוה כמו שכתבנו במקום אחר. לולי רשי, היה אפשר לומר שגמרא (שכחתי איפה) משמע שצורך שחיטה תלוי על כמה חיות יש בו. אולי אלו גדילים מבהמה יש להם חיות מרובה. כיון שמיתת בהמה לא ממיתם באופן כל כך דיירק"ט, אין שחיטה מועיל להם. נראה שאולי ענין בן פקועה הוא שהוא (בדר"כ) בהמה חלושה, שהרי מת אמו קודם שילדו (יש לדון). אז, נראה, נחשב שחוט, שגרם שחיטה (באופן קצת דיירק"ט) שיחסר חיותו. נראה גם כן שלכן אומרים שיש לו ד סימנים, והוא שנשאר חיות די ששחיטה יהני (ואם תאמר יהא עדיין כסימן אחר. ונראה שיש חשיבות לחיות שיש לו בשעת שחיטה כיון שאז הוא גדול, ויש חשיבות לשל אם כיון שאז היה אב החיות. ויש לדון אם אמו טריפה ושוחט את הוולד מיד, שאולי למש"כ לא יהא כשר. ולעולם יש לומר ל"פ.) ותו"ת.
* ע:
** קל וחומר -
יש לדון מה קל וחומר יש כאן, ולמה זה נחשב קל וזה חמור. ותו"ת.
** בהמה טמאה -
מעניין שיהא סברה לחלק, שאף שאין לימוד שייך, רק מצינו חילוק באיסור אכילה, ויש לדון למה יש צד לומר שנחלק לטמאו יותר. ותו"ת.
* עב.
** עתיד לצאת -
נראה שבהוה אמינא סובר גמרא ששאני עובר שמצד עצמו מוכרח לצאת, והוא שלא רק יש סיבה שתצא, אלא שיהיה בעיא אם לא יצא, שיגדל עד שפקע האשה. ויש לדון.
** ור"ע עובר -
היה אפשר לומר שסבר שאין הוה אמינא, ולכן חולק, אלא שיודע גמרא ממימרת רב יוסף שאינו כן (והוא יודע מקבלה), ובין כך ובין כך קשה להוה אמינא של ר"י.
