* ב.
** אוכלא דאפרת -
לכאו', רצה לומר שכיון שהתרנגול היה מוכן מבעוד יום, וזה חלק מן התרנגול, ששניהם עומדים לאותו דבר, גם הוא נחשב מוכן מבעוד יום.
** דאית ליה מוקצה -
היה נראה מן הסברה לומר ששני החלקים חידוש (ולכן אומר שניהם), שהיה אפשר לומר שרק מוקצה מותר, שכיון שהיה בעולם בתחילת, היה קצת ראוי למלאכה, והיה אפשר לומר שרק מוקצה אסור, כיון שהיה עומד שלא לעשות בו מלאכה ביה"ש, ונתקצה ונדחה, אבל נולד לא היה עומד לכלום. אבל, עיין לקמן (כח היתירא עדיף) שלא משמע כן. ויש לדון, שאולי רק אומר שזה חידוש להיתר, ואף שהיה גם משמיע חידוש להיתר אילו אמר דין תרנגול.
** שאור בכזית -
גבי יום טוב- מעניין שרש"י קורא דין שאור "דין יום טוב," שהיה נראה לומר שיש שני סוגי דינים בפסח, יש דיני יום טוב ויש דיני פסח, וזה מדיני פסח. אז, יש רק מה שזה נוהג ביום טוב. (ויש להעיר גם כן שזה נובג גם שלא בפסח, שהוא נוהג בערב פסח, מאמצע היום.)
** קא סלקי -
לא ידע- משמע שאילו ידע, בוודאי היה מהני. אם כן, היה אפשר להוקים אותו כשידע שתרנגולת שלו יוליד ביצה (וכך מצוי, שהרבה תרנגולתים מולידים פעם אחת ביום)[fn:1]. ואולי רש"י אומר שלא יודע קרק' של הביצה שיוליד, ואז אין מחשבתו עליו.
לולי רש"י, היה אפשר לומר שאין מחשבה מהני להכין מה שאינו שם, כמו שאין יכולים לעשות חלות עליו. ותחשב.
** גבי שבת דסתם -
היה אפשר לתרץ שמסתבר לרב נחמן לחלק בין שבת ליו"ט, כמו שיאמר גמ' לקמן לתרץ לרבי.
* ב:
** מכדי מאן סתמיה -
היה אפשר להקשות גם סתירה בדברי בית הלל וסתירה בדברי בית שמאי. (ואם תאמר הרי לא תי' לסתירה בדברי בית שמאי. וי"ל שקל לת' שמחמירים יותר בדבר היותר חמור.) ונראה שזה לא כל כך קשה, שיש לומר שחולקים תנאים (תנא הסותם של שבת ותנא הסותם של ביצה) מה אמר ב"ש ומה אמר ב"ה.
** מאן סתמיה -
רצה לומר, כולו חד תנא הוא, ואז יש סתירה.
** מאן סתמיה -
לא רק מקשה שאגב מצאנו סתירה, אלא מקשה שכיון שכבר סותר את עצמו, למה נניח שב"ה שנאמר בשבת הוא כסתם של שבת וב"ה שנאמר ביו"ט הוא כסתם של יום טוב. ותחשב.
** מאן סתמיה -
מפי המרובים- מעניין, שהלכה כסתם משנה יותר משהלכה כרבים, שהלכה אינו כרבים אם מסתבר כיחיד, אבל הלכה כסתם משנה, אף אם לא מסתבר כן. (ההוכחה לזה הוא תוס' ביבמות (מד) שכ' שאף שאין הלכה כסתם ואחר כך מחלקת, עדיין הוא כרבים. אפשר שרש"י חולק על תוס'.) יש לומר שאם רבי עשה אותו כרבים, היה נראה לרבי. אז, יודעים שהוא רבים שמסתבר טעמו. במילים אחרים, רבי לא חש שבני אדם יראו שהוא של רבים, אבל יחשבו שלא מסתבר כן, שרבי סבר שמסתבר כן, וממילא גם אחרים יחשבו כן. אז, היה די לו לכ' אותו בסתם. יודעים שלרבי היה מסתבר טעם שלו ממה שעשה אותו כרבים בכלל. ותחשב.
* ג.
** לאפוקי -
לא צריך לומר שקרק' אלו שייכים כלל לגזירה. אלא, כל זה הוא רק גזי' שמא יבוא לעשות כן (או דומה לכן, באופן יותר אסור) גבי פירות או גבי מי פירות. אז, כיון שיש איזה קרק' שמחלק בין זה לפירות, אף שזה לא שייך לאיסור, אולי זה מספיק לעשות שלא ילמדו בני אדם מזה לזה.[fn:2]
** מתנה -
ואם היום... הרי נעשה תרומה- לכאו', אין זה חלק מן הדיבור שלו, שלא צריך לומר כן, אלא זהו מה שכבר קרה. אז, נראה שזה רק חלק מן הביאור שאומר רש"י. ותחשב.
* ד.
** לא בטיל -
רצה לומר, כמו שמבאר רש"י, לא מותר ספק שלו. מוזר שלא רק אומר כן, כיון שזה מה שבא לבאר (והיה כבר מניח שלא בטל). ותחשב.[fn:3]
** כתנאי -
לא יודעים מהו הסבר של מחלקת תנאים, שלא צריך להיות שחולקים במה שחולקים רב ורבי יוחנן.
** מיומא טבא -
לכאו', לא נעשה יו"ט אחרי הסעודה, אלא בצאת הכוכבים. לכאו', פשוט שלא היה מדבר קודם סעודתו, ואז רש"י מזכיר הזמן הנוגע. יש לדון בזה, שהיום הרבה רבנים מדברים קודם סעודתם. אולי אף אחד לא מדבר אחרי צאה"כ וקודם סעודתם.[fn:4]
* ד:
** ספוקי מספקא -
קשה איך הבדיל, שיחוש לומר ברכה. אולי הבדיל בלי ברכה (אמר, "ברוך המבדיל בין קודש לחול").
** כוותיה -
איני מבין כל כך מה חושב גמ'. צד האחר של הגמ', שרק מקיימים הספק שהיה לאבותינו מחשש שמא נצטרך לזה עוד, מובן. אבל, צד זה לא מובן לי. למה יהיו שני ימים טובים. אולי הוא שהיה ספק, ורבנן קבעו (וצריך ביאור למה יקבעו כן) שמחמת ספק נעשו יו"ט אחד שלם. כיון שכבר הגדירו אותו כן, אף אחרי ביטול הטעם יהיה נשאר. אז, ממה שנשאר, נוכיח שעשו כן. ותחשב.
* ה.
** עד המנחה -
יש לדון למה לא אומרים שרק עשו אותו יום אחד כשבאו עדים מן המנחה, באותו יום. יותר מכך, יש לדון למה לא אומרים שלא קבעו קדושה לשני ימים, אלא קבעו קדושה לזמן שעדים באים עם יום שני. ותחשב על זה.
** שובו לכם -
יש להעיר שבכל ציורים האלו, היה טעם לאסור, ורק באו לבטל כיוןן שאין הטעם הזה נוהג עוד. אבל, לא רואים מה יהיה הדין אם החכמים הבאים חושבים שהראשונים טעו. וצריך לע' בשאר מקומות שנאמר.
** בכיצד מברכים -
צריך ביאור למה רש"י מזכיר את זה כאן. אולי הוא מפני שגמ' כאן מזכיר מילת "כרם," ובא רש"י לומר שזה מחלק. דחוק, שאז יעשה רש"י כן בכל מקום שנזכר נטע וכרם רבעי. (צריך לחפש, אבל אני לא חושב שעושה כן.)
* ו.
** וכי מה בין זה -
זה קושיה לכו"ע, שאף שמואל צריך טעם של "הואיל ומתיר עצמו בשחיטה."
* ז.
** יציאת רובה -
נראה שאולי "יציאתה" משמע לו הפרוס"ס של יציאה (שאי לאו הכי, היה לו לומר, "אחרי שיצא"), ואז אומר שאף כשיוצא הוא נגמר, והביאור הוא שנגמר אחרי יציאת רוב.
** ספנא -
ואינו אלא- לשון זה של רש"י מוזר.
* ז:
** דשמעה -
עיין בתוס'. יש להעיר שתוס' מניח שהענין הוא שבשעת תשמיש מכיר שיש מה שראוי להשתמש עמו. לולי תוס', הייתי אומר שהוא שכל זמן מכיר כן, ולא סופן, ששומע ביום וכל שכן ששומע בלילה
** שיעורו -
הל"מ- אם כן, קשה למה מביאים קרא. נראה שקרא מוכיח לבית שמאי שמסורה שלהם, ולא מסורה של בית הלל, נכון. (וצריך מסורה כיון שקרא רק מוכיח שאין שיעור שלו כזית. אבל, עדיין אפשר להיות ששיעור שלו דבר אחר, כמו שאומר רש"י.)
** במקום אחר
(בשי"ח ש"י על פסחים, בגלגל שני), הערנו שמרשי שם בביאור גמ' זה יוצא שבל יראה הוא רק גזי' דאו' על אכילת חמץ, שכן מפרש פירכא של בית הלל. היה נראה לומר שאולי הוא כן גם לפי בית שמאי (אבל יש לדון למה לא אומר, אז, פירכא של בית הלל), ולכן נקט שיעור של יישוב דעתו, שיש לו תאווה לאכול אותו.
* ח.
** אפר כירה -
עיין בתורי"ד (מובא בהגהות וציונים). היה אפשר לפרש שגמ' סבר כן גם בהו"א (אולי אף בלי שינוי גי'), והקשה למה שייך בזה מודים, שלא היה להם שום מחלקת בדבר הנוגע בזה. הרי, חלקו רק בהיתר שחיטה וכיסוי ביום טוב, ולא דברו כלל מה נחשב מוכן. (אבל, ע' בסופ"ק של יבמות שמצאנו כעין זה.) ואז אומר שאין זה חלק מן ה"מודים," אלא הוא דין אחר שנוגע לזה שתנא אומר.
* ח:
** דקירה אחת -
מעניין שלא אומרים שיש בילה, ואז כל דקירה נצרך.
** מוכן -
בתמיה- רש"י מפרש כל התי' עם הקושיה להיות קושיה אחת ארוכה.
* י.
** אף להחזיר -
עיין ברשי. עדיין קשה למה לא אומרים שחולקים אם יש בנין, ואז שמחת יו"ט לא מספיק, או אין בנין, ושמחת יו"ט מספיק. ותו"ת.
** משימות -
בביאור ברירה כאן, קצת צריך ביאור, שרק אומרים שנברר כשבורר אחד בדעתו, ולא כשיוצא שם. ותחשב.
* י:
** שלש ומצא שנים -
יש לדון מה יקרה אם שנים יצאו, אם נאמר בזה חזקה שיוצאים. ואגב, צריך ביאור למה דן במשניות אלו בשנים ושלש, ולא באחד ושנים. (אולי הוא מחמת מש"כ, להוכיח שבשלש צריך ששנים ישארו. אבל, אם היה אומר אחד, הייתי אומר שנקט אחד ושנים כיון שהוא המועט. ותחשב.)
* יא:
** אין בנין -
עיין בגמ' לעיל, שאמר כן. ונראה שאין בנין בכלים מדאו', אלא מדרבנן, ואז צריך נקודה זו. גמ' לעיל רק אמרה שיש מחלקת אם בנין בכלים מדאו' או מדרבנן, ועל זה מיוסד מחלקת אם התירו כאן או לא. ותחשב.
** ורחבה -
עיין בפשט של רש"י. זה מעניין. גם מעניין שמביאים אותו כמה שאמר, ולא כמה שהיה נקרא בדרך כלל. (ויש להעיר שלא מצאנו מקום אחר שיהיה כן בגמ', וצריך ביאור למה לא.)
* יב.
** ערוב הוצאה לשבת -
יש לדון למה לא רק אומר שחולקים ב"אין עירוב הוצאה ליו"ט," ולמה מזכיר מה שיש ערוב והוצאה בשבת. נראה שהוא מפני המקור (שהוא מיעוט משבת). אבל, עדיין יש לדון למה מזכירים את המקור בהזכרת הדיון.
** לפלגו באבנים -
עיין במש"כ רש"י. יש לדון, אז, למה גזרו טלטול אף על פחות מכשיעור.
** בשר בחלב -
יש לדון למה לא לוקה מחמת נהנה מבשר וחלב.
* יב:
** גזרה שווה -
יש לחפש בש"ס מקומות שאומרים בהם ג"ש ולימוד דרבנן, שיש הרבה, כמו כאן, ובתחילת פרק רבי עקיבא, ובתענית. ותחשב.
** אינה משנה -
לכאו', לא אומר שלא נשנית כלל, אלא רצה לומר שלא נשנית כך, ובוודאי יש טעות בגי'. (שוב נראה לי שזה, באמת, הוא שאלת "אסמייה," ששואל אם בכלל אין ענין בו או צריכים לשנות את הגי'.)
* יג:
** מאי טעמא -
צריך ביאור איך רבא מוסיף כלום. (עיין במה שכ' רש"י בביאור שיטת רבא. עיקר חסר מדברי רבא.)
** כל הקדרות -
נראה שהחולק סובר שכמו שצריך לטרוח להכין תבלין קודם לכן, צריך לטרוח לחשוב איזה קדירה רוצה לפני כן.
* טו:
** ושוין בדג -
עיין במה שכתבנו לעיל (ח.) בד"ה אפר כירה.
** מכאן סמכו -
נראה שהביאור הוא ש"את אשר תאפו" אינו רצה לומר "את המאכלים אשר תאפו," אלא "את הבני אדם רוצים לאפות."
** מנא -
לכאו', אין להקשות כן, כיון שלא יודעים שיש קרא, אלא יש להקשות למה הוא כן. צריך לומר שהמקשה ידע את התשובה.
** ותנא -
קל לומר שרק כאן הוא, שלא מביא מקור אלא סמך.
** למי שלא הניח -
מצד השני משמע שלכתחילה צריך לעשות א"ת לעצמו. יש לדון למה. נראה שהוא כדי להזכיר אותו להכין או להזכיר אותו על דיני יו"ט, ואז יעשה לעצמו. ויש לדון למה מהני שאחד יעשה. וי"ל שמסתמא ישמור שאחד יעשה אותו, וזה יזכיר אותו קצת. ותחשב.
** שמחת יו"ט מצווה -
עיין בשבת גבי תפלה בזמן תורה. צריך ביאור.
** לא היה לו להניח -
עיין בביאור רש"י. נמאצ שמספיק שהיה קשה לו, ולא צריך שממש לא היה אפשר לו.
** יטע -
יש לדון אם מכוון לומר שמחמת זה לא מאמינים למחזיק או מחמת זה לא יעיז פנים לטעון כן.
* טז.
** מזונותיו -
יש לדון, אז, מה ענין של שאר ימות הדין, שכל ענין ממון כבר קבוע.
** פחת -
הפשטות הוא שרצה לומר שיבוא לו מאה דולר, ויפסיד חמישים ממנו על שבת. אם מפסיד רק ארבעים, רק נותנים לו ארבע. אבל, גם אפשר לומר שמפסיד יותר מזה, והוא שדמי מזון שלו- דמים שהוא נהנה, ושלא הולך לשבת ויו"ט ולימוד בנים- נפחת.
** והוצאת -
יש לדון אם כן הוא בכל מצוות או רק באלו.
** לכבוד שבת -
עיין בביאור רש"י. קצת קשה, שלא צריך לאכול את זה כדי לקנות את האחר, שיכול לקנות ולאבד את זה. (ויש לדון, שאסור לאבד אוכלים.) לולי רש"י, הייתי אומר שרצה לומר שכל מה שאכל היה נקנה לכבוד שבת (ולכן היה כל כך טוב), שקנה אותו כדי לאכול אותו לכבוד שבת.
** שכל מעשיו -
איני יודע מה כוונה של זה בקנטקס"ט זה. נראה שרצה לומר שלא חש שיכוון מסעודה שאינה של כבוד שבת, שכל מה שעשה כבר היה לשם שמים. אז, לא שמר על עצמו לאכול תמיד לכבוד שבת. (אבל, אז צריך לומר ששמאי עשה כן בכוונה לאכול לש"ש. נראה שלא צריך לומר כן, אלא אולי תנא מקשה על הלל איך עשה כן, ואיך הוא לא עשה כשמאי בכוונה לאכול לש"ש.)
** ב"ש -
מעניין שאומר תנ"ה, אם זה שמאי והלל וזה ב"ש וב"ה. (אינם שווים, כמו שיוצא מגמ' בפרק ראשון של שבת.)
** מחד שביך -
עיין בביאור רש"י. גם יש לומר שרצה לומר שמחד בשבת יאכל לכבוד שבת, כמו שעשה שמאי. ותחשב.
** כזית -
משמע שבו בפני עצמו יש כזית. מוזר שיקרה כן, ומשמע שכזית אינו גדול. (נראה שאם נניח סכין שהוא שש אינש"ס, ושמנונית עולה חצי אינ"ש, והוא עב חומש אינ"ש, יוצא שיש לנו, בין הכל, כמו עשרים גרמ^3. אף אחד לא סובר שכזית הוא קטן כזה.
* טז:
** שיעור למעלה -
יש לדון מהו ההו"א שיהיה לו שיעור למעלה.
** עד תחום -
יש לדון מה יהיה הדין אם הם יכולים לבוא לו, והוא לא יכול לבוא להם (כמו אם עירבו).
* יז.
** שבת שחל -
לשון זה מעניין, שבדר"כ אומרים הפוך, ומדברים על ר"ח שחל להיות בשבת. ויל"ד. וע' בתחילת מגילה.
** וכדתי' רבינא -
אם ר"י גם אומר חלק זה, צריך לומר שרבינא הקדמון הוא.
** למיקני -
זה לא נותן טעם, אלא כופל הדין.
** ממלאה אשה -
עיין ברשי. גם יש לומר שיש חילוק איך נאפה כיון שיש דברים אחרים ששואבים את החום.
** קמחו
יש לדון למה לא מצדד שרק גזרו על קמחו, ולא עליו.
* יז:
** עבר ואפה -
נראה שסובר שאף שאסור הוא, נשנה אותו, כיון שכל הציור הוא "דאי," שאסור להכניס לזה.
** אפשר בשאלה -
יש לדון למה לא אומרים שאף כאן יש היתר, שיכול לאכול משל חברו. אולי חוששים שלא ירצה לתת לו. אבל, קשה למה לא מקנה משלו לאחרים.
* יח.
** ארבע אמות -
קצת קשה, שלא מצוי שיתחיל ברשות הרבים.
** מזהר זהיר -
גם יש לומר שהוא חושב עליו תמיד, וממחת זה נמצא שחושב גם על מה שמותר לעשות עמו ומה אסור לעשות עמו, ואז הוא ציור שיש בו חילוק שמודיע שאין טעם לגזור.
** נגזר -
לא פשוט למה מניח שכל גזירות אלו שוות.
* יח:
** יוה"כ -
זה קשה לכ"ע, שבוודאי אסור לרחוץ אז.
** רבי -
צריך לסכם גמ' זו.
* כ.
** בבא בן בוטא -
כמו כן מצאנו גבי רבי יוחנן החורני בסוף פ"ק של יבמות.
* כ:
** לסמוך -
איני מבין כל כך, שמתחילה היו מדברים על הקרבת עולה, ועכשיו הם מדברים על סמיכה.
* כא.
** כי קא זכו -
תחשב מה לנו בזה, כיון שסוף סוף יש בו אוכל נפש. נראה שהו"א שמכשירים של אוכל נפש הוא, כיון שרק גורם שה' נותן אוכל נפש לכהנים. ותחשב.
* כא:
** מדורה -
כיון שזה נשנה לפי בית הלל, צריך לומר שזו ואצ"ל זו הוא.
** לא יחם -
נראה שאולי צריך להיות ראוי לשתיה, שהרי צריך לשתות קצת ממים שרוחץ בהם (כמש"א גמ' בשבת). אבל, יש לדון אם ייחשב לשתיה. נראה שהשתיה חלק מן הרחיצה, ואז לא יותר.
* כג:
** כובשת -
מעניין שזה מותר, שלכאו' אם יחפור על ידי כבישה יהני. אולי הוא מפני שלא עושה כן או אולי לא יהני, כיון ששם האדמה קשה ביותר.
** תרי תנאי -
יש לדון למה לא אומר שתנא זו סובר כר"י בדבר אחד וחולק עליו בדבר אחר.
** ואין נותנים -
מעניין שאומר שדגים אוכלים קרקע. מסתמא, בא להם איזה מינאראליים או ויטימיאונים משם.
* כד.
** מעשה -
נמצא שיש מחלקת בספק מוקצה, אף שלכאו' דין דרבנן הוא. ויש לדון מהי"ת מן המשנה שיש מחלקת שם. אולי אם היה ברור, לא היה צורך להביא סיפור. ויש לדון, שמצאנו כעין זה בשבת (גבי מעשה בגשר).
** גמרא -
עיין במה שמסביר רש"י. זה מעניין.
* כד:
** אם יש -
מעניין, ששם גמ' אומר לשון שצריך דחייה בידים.
* כה.
** שהות ביום -
מעניין שלא אומר, "אלא אם כן מכוון לאכול...." משמע שהואיל מתיר.
** ד"א -
כמו כן מצאנו במגילה שלומד ד"א מאכילת מזבח.
** והא תני -
עיין איך רש"י מפרש את הקושיה. גם יש לומר שרק דן אם יש איסור לאכול ככה או רק אינו ד"א. אבל, האיסור יהיה מפני שאינו ד"א.
** חוץ -
שאינו מכירו- ועוד שאין לחוש שישלח אותו, שאז בא בשבילו, ויאסר. אולי נחוש שישלח בעד חברו, ורש"י אומר שא"צ לחוש, שגוי לא ילך בשביל מי שלא מכיר, ולא נחוש לשני בני אדם שמכירים אותו גוי.
* כה:
** מגסי -
נראה שנקט לשון רבים כיון שגסי רוח מצויים.
** דתיהם אש -
יש לדון אם רצה לומר שתורה שלהם מכלה את כוחם, והוא כמו אש, או שדתיהם שיש להם חוץ מן התורה אש, ולכן צריך תורה, או שדתיהם שיהיה להם לולי התורה הוא אש. ותחשב על זה.
** רנב"י -
אולי צריך לומר שמ"ש אינו שמואל או אולי צריך לומר שרנב"י היה קצת קדמון. (אולי זה משמע שהיה סתם רב נחמן, שהיה ג"כ קדמון. ודע שמצאנו ראשונים שכ' שהיה קדמון וחי זמן רב, אבל לא היה רב נחמן.)
** מקטע -
יש לדון אם הענין הוא שאנו עושים רע לה' שבע פעמים, כמו המבשל התורמוס, אבל אנו לא חוזרים לאהוב אותו, או שה' מעניש אותנו הרבה פעמים, אבל אנו לא נעשים טובים. ותו"ת.
** דוחקא -
גם יש לומר שחששו שמא יפלו, מפני הרבה בני אדם.
* כז:
** סתמא -
נמצא שאף שיש מעשה שבא אחריו- עם שם- נחשב סתמא.
* כח.
** הכלי אין -
יל"ד למה חושב שיש חילוק.
** משמך -
מעניין שלא אומר, "משמא דמר."
* כח:
** דפסקא -
יש לדון אם זה קאי על היום או אתמול (ערב יו"ט). מרש"י נראה כצד ראשון.
* כט.
** בסורא -
עיין במש"פ. גי"ל שהיו אומרים כן במקום "זוז," והיה מובן שר"ל זוז. אבל, כיון שזה רמז, היה מותר. ויש לדון איזה רמזים נכנסים להיות חלק מן הלשון.
* ל.
** דדרו -
אף שיש קצת טורח בהגעת הרגלא או בן אדם השני, אין טורח זה נאסר, שאינו טורח שחושבים עליו למלאכה. ותחשב.
** מדאו' -
משמע שיש יותר חי' בין דרבנן לדאו' בדרבנן, ולכאו' הוא מפני מש"כ אחרונים שאיסור דרבנן הוא רק מרידה, והרי אין מרידה בשוגג (חוץ ממה שלא למד מה שהיה לו ללמוד[fn:5]).
** תוספת יוה"כ -
יש לדון למה לא הקשה בזה בתחילה. נ' שאז הו"א שרק בדאו' חוששים למזיד, שמחייב אותם, והוא חמור מאד.
* ל:
** איסורייתא -
צל"ע בסוכה לראות אם בטלים לסכך די להיות כשרים (וזה סימן וסיבה). ותחשב.
** אתרוג -
לכאו', רצה לומר שעושה שיש שבע מצוות, כיון שיש יונ"ט (יום), מה שאין בסוכה, שאין יונ"ט שיכולים לחלק לתוכו.
* לא.
** דתניא -
נמצא שאף בבריי' מניחים שיחיד שאומר דבר יש בו רבים שחולקים עליו.
* לג:
** מוסתקי -
עיין בביאור רש"י. נראה שמילה זו יש לו שייכות עם מולית גו"ם, שמצאנו שחברה אחת של גו"ם קראו להם "מוס"ט," וגם מה שרש"י מפרש כאן הוא נקרא באנגלי"ת גו"ם (אבל לא טשויינ"ג גו"ם).
* לד.
** שצריך לבדקם -
בכל כעין זה, צריך לומר שהוא מצוי שלא יקבלו ליבון שלהם עד שהוא ספק. מעניין, שנמצא שהיו עושים לבנים שרק היה להם חמישים אחוז יכולת להיות קיים.
** אחרון -
כמו שמבאר גמ', הוא רק אם מביא את אש אחרון. אז, היה אפשר לומר, "המביא את האש חייב." ותחשב. ויש לדון למה לא כלל כל זה בתוך כלל אחד ואמר שהמביא את האש וכל הבאים אחריו חייבים.
* לד:
** עד שירשום -
לכאו', צריך להיות יותר מזה, שאז לא צריך לרשום, אלא לומר, "זה אני נוטל." ותחשב.
** לא נגמרה -
יש לדון למה לא יקבע שבת אם לא נגמר מלאכתו:
1. כיון שלא נגמרה מלאכתו, יותר רחוק הוא מן הקביעות.
2. כיון שלא נגמרה מלאכתו, מוקצה הוא, ואין כוח של שבת שולט בו כל כך.
* לה.
** לא יגמור -
יש לדון אם זה מפני שכבר היה מעשה זה (או כעין זה) נחשב קבע (בשבת) או מפני שכבר חל חיוב מעשות (או דין קבע) על המאכל. ותחשב.
* לה:
** לא משתבש -
יש לדון מה רצה לומר:
1. אחד בוודאי טעה בגי', אבל שני הגירסאות אומרים מה שמכוונים לומר טוב.
2. אולי היה גי' כזה וגי' כזה. כיון שכ"א אומר כן, וכל אחד מסתברמסתמא לכל אחד יש מקור.
** י"ט דקיל -
גי"ל להיפך, שבי"ט שהוא קל יקילו יותר.
** דאיכא דעדיף -
יש לדון מהו הכוונה:
1. אינו כל כך מצווה, כיון שלא צריך להיות שהוא יעשה אותו. (יש לדון למה זה ממעט במצוה. ותחשב.)
2. אינו כל כך מצווה, שיותר טוב שלא ידון, אלא חברו ידון.
לשני, מובן למה צריך להיות שחברו יותר טוב ממנו, ולא שווה לו.
** תיתי -
נמצא שאומר לשון שכר לכוון לעונש.
** שמא יצא -
ע' במש"פ. גי"ל שתמיד יש קצת חשש שיצא מן התחום, אבל בדרך כלל לא מצוי שילך כ"כ רחוק, כיון שקשה. אבל, בסוס לא קשה ללכת רחוק. (ואם תאמר אם כן יהיה אסור לערב. וי"ל שיש יותר צורך שם. גי"ל שכיון שהוא קבע את הגבול שם, לא ישכח אותו. ואם תאמר אם כן ירכב על סוס כשערב. וי"ל שלא פלוג רבנן.)
** והא מצווה -
בא רש"י לפרש שאין כוונת הגמ' להקשות שמחמת זה יהיה מותר, שיש הרבה במשנה שיש בהם מצווה, כמו שאומר משנה בפירוש. ותחשב.
* לז:
** יש ברירה -
אין ענין יניקה כל כך פשוט לי. אם נאמר שכיון שחי מחלק חברו, ושזה עושה איסור, אני מבין. אבל, מרש"י משמע שאז אי אפשר לעשות ברירה. צריך ביאור למה לא, שהרי יש דבר שנברר. אפשר לומר שלא מחלקים בעלות בתוך חלק אחד, ואז אם יש בו דם שנברר שהוא של חברו, לא נאמר שהדם הוא של חברו והבשר הוא שלו, ואז אי אפשר לומר ברירה. ותחשב על זה.
* לח.
** ואר"י -
יל"ד למה מביאים ראיה מזה, כיון שר"י רק מבאר שיטת ר"י (והרי מוכרח כן בשיטת רבי יהודה, ואף אחד לא חולק על רבי יוחנן בזה).
** ר"א -
מגמ' זה נמצא שרב אושעיא ורב הושעיא הם אותו אדם.
** רבי אבא -
לא היו רגילים לקרוא "רבי" לבן בבל. נמצא שקרא לו כך על שם העתיד. ותחשב.
* לח:
** הבורר -
איני מבין, שהקשו עליו קושיה בנוגע למין במינו, ואז אין זה משיב לקושיית הגמ'.
* לט.
** דבר שיש לו מתירים -
כמובן, רב אשי כאן הוא לשיטתו, שמחמיר בדבר שיש לו מתירים באיסור דרבנן.
** מפני רוטבה -
מבין אני למה זה עושה שאין המים בטלים, שעשו לו דבר חשוב, במה שהוא רטוב, אבל קשה למה אין המלח בטל. וי"ל שכיון שיש הרבה מים, צריך הרבה מלח לטעם. דחוק.
** דמאיס -
יש לדון אם רצה לומר שהשלבת מאיס, אף שאינו ע"ז, ואז לא צ' גזי', או שע"ז של איסור מאוס, ולא צ' גזי' שירחיק ממנו.
** דמאיס -
יש לדון אם מאוס לבני אדם כיון שעובדים אותו לאלוה או כיון שהוא טמא.
** ותיפ"ל -
יש לדון למה לא אומרים שהוא בטל. צריך לומר שאף שדבר יכול להיות בטל לפחות משיעורו, לא יכול להיות בטל לשלהבת, שאין בו כלום.
** כרגלי הממלא -
מעניין לומר ברירה על ההפקר. ותחשב. (ויש לדון אם אומר כן לענין קנין או רק לענין תחום, שאולי ברירה עושה שהוא עומד קצת לו, ולכן נקבע תחומו ככה.)
* Footnotes
[fn:1] שוב ראיתי במייקריסופ"ט אינקארט"א, שכתב ש" egg producing hens produced about a hundred eggs a year." גם בבריטאניק"א ראיתי כמו זה שכ' ש"egg production has increased from 104 in 1910." אז, נמצא שיודע שמסתבר שיוליד אז, אבל אולי לא יודע בדיוק שאז יוליד. ויש לדון, שאולי בכל זמן קורה באחד משלש ימים, באותו יום בדיוק. ויש לדון, שכמובן, אז היה עושה יותר ממאה. ותחשב.
[fn:2] נראה שלא צריך להיות שיבינו בני אדם שיש חילוק ביניהם, אלא לא יחשבו על זה בנוגע לזה. על פי זה נראה לבאר מה שאומר רש"י בגיטין (טז:), שמבאר שלא ילמדו בני אדם מדבר שלא מצוי. אולי אין הענין שיראו שזה חלילוק (ששםפ, באמת, אין חילוק), אלא שלא יחשבו על זה בנוגע לזה. ותחשב.
[fn:3] שו"ר שגמ' לקמן משמע שיש חולקים לומר שלא בטל. אז, נראה שר"א גם קאי על זה. וצריך לעיין.
[fn:4] כאן, אזכיר סיפור שקרה כשהייתי בירושלים. שם, הייתי מתפלל בבית הכנסת שמואל הנביא (של עדת התרגום) שהוא בפינת שמואל הנביא ובית ישראל. בערבית של שמחת תורה, התחיל רב אחד (רבי יעקב, שהיה קצת רב וקצת חזן וקצת גבאי) לדבר דברי תורה. דבר ראשון מצחיק, אופיר (שהיה חצי חזן (לא שרק התפלל חצי תפלה, אלא שהתפלל כל תפלה בזמן של חצי תפלה) ומקצת גבאי) שאל אם הוא עוד סוכות, שרוצה לישון באמצע השיעור. דבר שני שמצחיק, באמצע השיעור, מישהו שאל לרבי יעקב אם כבר הגיע זמן ערבית, וענה לו רבי יעקב שאכן הגיע, והפסיק השיעור שם, מבלי לגמור מה שהיה רוצה להגיד.
[fn:5] יש לדון למה ילמוד, אז, שאין בו רע. ותחשב. צריך לומר שעדיין יש בו קצת רע.
