** ב: גמרא כל היכא דאיכא תרתי -
יש להעיר שבאותו ציור שמביא גמרא, על כל פנים יש בו שני בחשבות (רוצה עצים, ורוצה טובת העץ). כאן, רק רוצה בטוב אחת (טובת העץ[fn:1])
** ג. גמרא אהני תולדות -
ואם תאמר הרי חרישה הוא אב מלאכה, ואינו תולדה. נראה שאם היינו מחויב עליו, היה מדין תולדה, שקרא כבר גילה לנו שהעיקר לענין שביעית הוא זריעה, ואז חייבים על תולדות זריעה. ותחשב.
גם יש לומר שלענין שביעית, מה שנקרא תולדה הוא או דבר שאינו דבר עיקרי או דבר שלא נכתב (שאין משכן להחשיב דברים). אם כן, שפיר היה חרישה נחשב תולדה. ודחוק לומר שכך הוא תולדה.
** ג: גמרא רבי אלעזר -
יש להעיר ששני אמוראים אלו היו מא"י. אז, לא בא רב דימי ואמר לבני בבל ודנו בו; לכאורה, מה שקרה היה שאמר שאמרו במערבא אותו דבר קשה להבין ושם אמרו שני פירושים. גם יש לומר שגמרא מביא איך, למעשה, נתפרש, אחר שהביא ששאל אותו רב דימי.
** אם כן נתנה תורה -
שמעתי מאת גר"ק צד ש"אם כן נתת דבריך לשיעורין" הוא שמשנה משמע שיש שיעור אחד, ולא הרבה שיעורים. רש"י כאן כותב (ואינו מוכרח לבאר גמרא כרש"י, בפרט כיון שלמעשה גמרא עצמו לא אומר לשון זה) שטענת רבי שמעון שווה לטענת "אם כן נתת דבריך לשיעורים.” אם כן, קשה לומר כגר"ק. ויש לדון, שאולי היה ידוע מילות של הגזירה. ודחוק, שהיה לו להזכירו.
** ד. גמרא הלכתא לרבי ישמעאל -
ואם תאמר אם כן מצאנו מחלקת באם יש הלכה למשה מסיני (ורמב"ם אומר שלא חולקים). ויש לומר שכיון שרואים שיכולים ללמוד הלכה למשה מסיני מחברו כאן, צריך לומר שהיו בהלכה אחת[fn:2]. (יש לדון, שאולי לומדים ממה שבני בית מדרש כללו את שניהם ביחד.) אם כן, אל חולקים בכל ההלכה, אלא במה כלול בו. על פי זה, אולי יש לתרץ הרבה מקומות, לומר שכל הלכה שחולקים עליו היה עמו הלכה אחר. ותחשב.
** הלכתא -
יש לדון אם עדיין דין ילדות קיים. יש להעיר שבוודאי לא קיים לרבי עקיבא, שלא לומד ההלכה למשה מסיני, ואז אין לו מקור לאותו קולא.
** אתיא גזירה שווה -
עיין ברש"י שמבאר שמקשה שצריך להיות לגזרה שווה מקור מסיני. קשה מהיכי תיתי שאין לו מקור מסיני. אולי היה מקור, אבל לא ידעו ממש מה לדרוש (כמו שמצאנו שראשונים אומרים שמקור היה רק למילים של גזרה שווה, אבל לא למקום של אותו מילים, שיכול להיות בכמה מקומות). אולי צריך לומר שרש"י חולק על אלו ראשונים, ואומר שהגזירה שווה ממש ניתן.
לולי רש"י, היה אפשר לפרש שמקשה שלמעשה יש הלכה, ויש קרא, ואז מוכרחים לדרוש, ומה יעשה גזירה שווה. ונראה שאין זה ראיה, שאולי לא היה כל כך פשוט לדרוש קרא (כמו שאמר רבי ישמעאל), ולא היה הכל גורס ההלכה (רבי עקיבא), ואז הכריח כמי שלא דרש וכמי שלא גורס מאותו גזירה שווה.
** מי גשמים גופייהו -
ר"ל, מי גשמים יעשה אותו בור למי קילון. קצת צריך ביאור למה יש יותר סיבה, אז, לגזור. נראה שהוא שאז לא רק יש לחוש שיעבור, אלא אף יודעים שמצוי הוא המי קילון לעבור בו. ואם תאמר אם כן יודה רב אשי אף בלי זה בציור שיש לו כבר מי קילון. ואולי אין הכי נמי. גם יש לומר שלא היו רבנן גוזרים אם לא שמוכרח כך. ותו"ת.
** ה: גמרא מוטב ישרפו -
מעניין שלא חוששים שלא יכירו בטומאה, ויאכלו בטומאה.
** רש"י שלא להפסיד -
לשון שהוא עושה שהוא טמא מעניין. אולי רק ר"ל שעושה לו דיני טומאה. גם אפשר שרבנן עושים לו טומאה דרבנן ממש. ק"ק, אז, ל"ל יגזרו בלי לעשות אותו טומאה. ואולי אינם יכולים. דחוק.
אגב, יש להעיר שלשון רש"י כאן, באמת, הוא כבר לשון גמרא, שאמר גמרא (ביצה) ש"אפושי טומאה…,” לומר שרבנן לא גוזרים דיני טומאה.
** ו. גמרא הא אמרן -
זה יתרץ שני הקושיות. ויש לדון, באמת, ל"ל נתרץ כך.
** ז. גמרא להקל -
לא הבנתי, שמיצר לו, שאם אינו אומר טהור, ידע שהוא טמא. ויש לדון, שאולי רק ידע שהכוהן לא יודע, ושצריך לחשוב עליו. ויש לדון, שרבי יוסי, כנראה, סובר שכל שלא אומר טהור הרי הוא מטמא אותו (כן נראה מגמרא). אם כן, א"א לומר כמש"כ.
** ח: גמרא אין נושאים נשים -
יש לדון למה אין בזה משום אין עושים מצוות חבילות חבילות. אולי זהו "אין מערבים שמחה בשמחה.” דחוק. גם יש לומר שאין שמחת נשואים כל כך מצווה. ויש לדון, שיש עוד ציורים בגמרא (יום טוב של שמחת מקדש) שנראים שהם מצווה.
** לפי שאין -
היה אפשר לומר שהוא מחשש שימעט שמחת רגל. ואם תאמר אם כן הוא שווה לתירוץ שני. ויש לומר שזה אומר שהוא וודאי, וזה אומר שהוא רק ספק (ויש לומר לכל צד). גם יש לומר שזה אומר (לכאורה, השני) שמבטל שמחת רגל כולו, וזה אומר שרק ממעט אותו. לא נראה ככל אלו, שאז, לכאורה, לא היינו צריכים מקור.
גם יש לומר שהענין הוא שאינו טוב להיות כל כך שמח. ויש לדון, שלכאורה, אלו הם (ובפרט בשם מקדש) שמחות של מצווה. ויש לדון, שאולי עדיין אינו טוב.
** בחגיך ולא באשתך -
לכאורה, קרא זה רק אומר הדין, וצריך ביאור איך יותר נשמע כמאן דאמר אחד מחבירו. ותחשב. אולי הוא מפני שמשמע שנובע ממה שאינו שמח ברגלו. זה, לכאורה, צריך להניח שלא רק דורשים דיוק, שלא משמע כן, אלא דורשים שצריך שמחת רגל, וזה אינו אפשר אם שמח באשתו.
דע שזה, לכאורה, יגלה נגד צד שכ’ לעיל באין מערבים שמחה בשמחה. ותו"ת.
** ט. גמרא ודלמא מינטר -
יש לדון למה אין בעיה של מצוות חבילות חבילות. באמת, זה קשה על המשנה, כמו שפרשנו לעיל. ותו"ת.
** ט: גמרא לקל טבלא -
לכאורה, זה ר"ל שיש מקומות שבו דומות, ואף לזה דומות. ויל"ד.
** רש"י לא תבוש -
היה אפשר לומר שמברך שלא יבייש ולא יתבייש. אולי אינו מסתבר שייתן לו ברכה לזה, שהכל בידי שמים חוץ מיראת שמים, ואז אי אפשר לברך אדם שלא יבייש חברו. ויש לדון.
** י. גמרא סבר לה כיש אומרים -
וכשיטת רב יהודה.
** י: גמרא נראה שזה
הדף היחידי שבש"ס שמזכיר בו שם שאול ומילת חייט. ועיין בו ותמצא.
** שקל -
גמרא זה גם כן איתא בבבא בתרא בחילוף (עיין שם). שם, הסדר אינו כסדר כאן; יש לדון למה.
** יא: גמרא תניא -
היה אפשר להוקים את המשנה גם כרב אשי, ולומר שהוא כמאן שמתיר. ויל"ד.
** יב. גמרא מסייעים -
נראה שר"ל שאם הגויים מקבלים אותם לזמן, אבל נחשב עבודת נכרים, ורק מסייע להם בעבודתם, ולא מסייע מלאכתו, ואז אינו אסור. ויש לדון.
** רש"י שרשויי -
משמע מרש"י שכיון שלא מקבל שכר, אינו מלאכה[fn:3]. זה מעניין. היה אפשר לומר שכיון שאין שכר, אינו נחשב בא ממנו, והוא בא מעבדים. ותחשב.
** בר שית -
גם היה אפשר לומר שבר שית ר"ל שהוא בר שש שנים, שאולי כשמישנו נעשה יותר טוב. איני יודע אם אותו מציאות הוא נכון (חושב אני שגמרא דן בזה, אבל אולי אינני נכון בזה).
** יב: גמרא אדם חשוב שאני -
רש"י מפרש (וכן משמע מגמרא) שזה קאי על שניהם. יש להעיר שגמרא ביבמות (פרק רביעי) אומר שאין היתר זה למי שאינו בן תורה. אם כן, נמצא שהוא רק לבני תורה שאינם חשובים כל כך.
** חזי -
צריך ביאור ל"ל פשוט שהוא חזי לשומשמים. אולי אין עיקר נטיעתו לכך, ואז אינו כל כך פשוט שהוא ראוי לזה. וצריך ביאור למה נוטעים אותו.
** יג. גמרא צרם אזן -
גם היה אפשר לחלק ששם נהנה מעוון אביו, שהרי לו בכור מותר, אבל כאן לא נהנה, שאילו לא עבר אביו, היה המלאכה כבר נעשה.
** לצורך המועד או לצורך -
מפשטות המשנה היה נראה לומר שצריך להיות צורך המועד- בין ללוקח (שצריך זה), ובין למוכר (שצריך ממון). בגמרא, יש שני מהלכים. מעורר גמרא שהשני מיותר, שאין סיבה לומר ש"לצורך מועד" קאי רק על לוקח. אז, אולי ראשון מרבה עוד ציור (שכר פעולה ולא חפץ), או מפרש ציור של צורך מועד. ק"ק למה צריכים ציור לבאר אותו.
** שכר פעולה -
צריך ביאור למה יהיה זה חלוק משכר לחפץ.
** רש"י משום צורך -
עיין במה שכתב, שאומר שאף כל מלאכות למי שאין לו מה לאכול מותרים. אם כן, לכאורה, חוזר קושיית גמרא (שנתיר כל מצוות). וצריך ביאור, אז, מה אומר.
** יג: גמרא מוכרי -
לכאורה, דיון גמרא מעניין, שרבי יוסי אומר שכן נהגו, ואז היה אפשר לצאת ולבדוק. אולי לא היו שם בזמן גמרא (או לא היו קרובים למקום גמרא).
** יד. גמרא כדי שלא יכנסו -
צריך ביאור למה אמר לפרש את זה ולא אמר אותו מתחילה על המשנה. אולי שמע את זה ראשון. זה מעניין.
** יד: גמרא מענה את דין -
מעניין שכלא עושה דין כלל, אף ששוהה לפסק לזמן שווה, אינו נחשב מענה, ורק נחשב כן אם כבר דנו. ותחשב.
** טו: גמרא מה הן -
בכל אלו, צריך ביאור מהו ההוה אמינא.
** טז. רש"י אבר לו -
לפי תומו- לכאורה, זה היתר לכמה מיני לשון הרע. וצריך לדון. ואולי לא היה מותר כאן, ורש"י רק מבאר איך נעשה שחכם גדול כמותו נכשל בלשון הרע, ורש"י אומר שנכשל בו כפי תומו, וזה קשה להינצל ממנו.
** טז: גמרא על גבי
כרים- משמע שישב ללמוד. ק"ק מגמ’ סוף סוטה. וצריך ביאור.
** רש"י והוא דוד -
מזל- מעניין שתלוי במזל.
** יז. גמרא מאי טעמא -
עיין ברש"י, שפירש שנותן טעם שהיה מקובל כלל. לולי רש"י, היה אפשר לומר שנותן טעם למה לא היה כל כך חשוב, והוא שהלך למקום אחר ועבר עבירות. ונראה שרש"י לשיטתו, שסובר ש"יעשה כל מה שרוצה" ר"ל שלא ירצה לעבור, ואז לא יעבור. אם כן, אין רע בזה, שלא עובר.[fn:4]
ואם תאמר למה צריך זה לבאר למה לא היה כל כך חשוב; לא היה כל כך חשוב מפני אותם מעשים שהיו מדברים עליו. ויש לומר שאי אפשר שהיה חשוב והיה עובר עבירות כך. אז, דן מה קרה.
ויש לדון, שאם באמת עשה כר"א, לא יידעו מי הוא, ולא ידברו עליו. ויש לדחוק.
** אגנובתא -
לכאורה, עשו שמתא, למעשה, על הכלב, ולא על גנובתא. ויש לדון.
** רש"י שמע מינא -
לאו מזליה- מעניין שתלוי במזל. יש לדון ל"ל אמר שמע מינא שהדין שאומר נכון הוא.
מרש"י נראה שסברו שאינו נכון, אבל מזליה אומר שלא נעשה כן. וצריך ביאור.
** יח. גמרא פרמשתקו -
יש להק’ על זה מגמ’ ב"מ שאומר שאמת איש גדול כפי גודלו (כמו שכתיב, “כאיש גבורתו"). ויש להעיר ששם קאי על שומן, ולא על גובה. אז, אפשר שהיה פרעה שומן ונמוך.
** אף על גב דאית -
יש לדון למה. אולי כך מצוי יותר. יותר קשה לומר כן בתירוץ לקושיה שניה של גמ’.
** יט. גמרא שאם לא גילח -
יש לדון למה יהיה כן. אולי עבירה לצורך רגל הוא מה שמפסיק אותו. גם יש לומר שרק מפסיק בשביל יום טוב. ותחשב.
** יט: גמרא שני ימים -
עיין ברש"י על המשנה. לכאורה, יהיה תלוי בגמרא זה.
** שלושים -
יש עוד מקור בנזיר, אבל פשוט להקשות עליו, והדיון בו קשה וארוך, ואז לא הביאו כאן.
** כ. גמרא שכבר נתעסקו -
רצה לומר, שאין עוד סיבה לזה, שכבר נתקיים סיבתו, אבל יש עוד סיבה לשאר דיני אבילות.
** ההוא מיבעי ליה -
זה מעניין. ותחשב.
** שמועה קרובה -
נמצא שאין החיוב על השבעה ימים אחר המיתה, אלא על שום שבעה ימים. כן רואים גם כן מציורים שמתאבלים אחר יום טוב.
** אלישע -
מה ששאלו לו, ומה שקרו לו כן (ולא אחר) משמע שזה היה קודם שסרח.
** רש"י כי סליק -
גם היה אפשר לומר שמצא רב חייא בבבל (שהיה דר שם מקודם). אולי רש"י יודע שהיו אביו ואמו של רב בבבל. ותו"ת.
** כא. רש"י ואם באו -
עיין במה שבאר. גם יש לומר שהאבל נתרבה אם באים יותר בני אדם. ויש לדון.
** כא: גמרא קרוב -
יש לדון למה נחלק על פי מקום שהיה שרוי.
** רש"י שיש -
נראה שמלשון רש"י משמע שהכל תלוי באם יש גדול מן הבא שנשאר בבית. ותו"ת.
** כב: גמרא חולץ -
איני יודע אם הדין הוא שצריך לקרוע עד שכתפו נראה או רק שצריך שיהיה כתבו נראה.
** ולשמחת מריעות -
יש לדון אם קאי על היתר לאחר ל’ יום או על איסור לפני כן (שאף שאינו שמחה כל כך, אין צורך ללכת). מלשון רש"י ד"ה אמר רבה נראה כראשון.
** כג. גמרא כרבי -
היה אפשר לומר כר"א. אולי רק ר"ל אף כרבי, וכש"כ כר"א. גם יש לומר שאילו כן, לא היה לובש לבן.
** רבא -
נמצא שלא לבשו רק לבנים באותו זמן.
** כג: גמרא עולה -
לכאורה, ראית גמרא הוא שלא יעלה אם לא נוהג. צריך ביאור מהו הדיחוי, שלא נאמר דין שאינו נכון מפני האגב. ויש לדון.
** כד. גמרא דמסתפינא -
לכאורה, היה עוד איש, שגמ’ ב"ק (פ) אמר שהיה תלמיד של רב יותר גדול משמואל. ויש לדון, שאולי ידע יותר, אבל לא היה יכול להק’ עליו (אולי היה צריך לשהות כדי להבין הקושיה או כדומה). אולי לכן פירש רש"י שקאי על "להקשות עליו.”
** קורעו לאחוריו -
לכאורה, ר"ל שנותן קורעו שם (ולא שקורע שם, שאינו קורע כלל).
** כד: גמרא שבעה -
לכאורה, ר"ל שכיון שיש שבעה ימים כלולים בעצרת, שיש לו תשלמוים, נחשב כשבעה ימים. זה מחודש. צריך ביאור מה יהיה בסוכות למאן דאמר תשלומים לכל אחד. גם צריך ביאור למה זה נכון גבי ראש השנה, שאין לו קרבן שיש לו תשלומים. ותחשב.
** כה. גמרא ערבונא -
ועוד צריך ביאור איך יעשה שיבכה. אולי מחמת זה יכיר בחשיבותו. גם יש לומר שיותר עליל הוא לבכות כיון ש הוא עצב.
** בהספדו -
צריך ביאור, אז, לאיזה נקפ"מ אמר לו הראשון. אולי יש נפק"מ אם יספידו אחר כך עוד, שכבר באו להספד. גם יש לומר שיש נפק"מ אם יספידו לו במקום אחר, ויהיו אנוסים לבוא.
** כה: גמרא חליץ -
סונסינאו פירש שלא יגלו כתפם. זה נשמע טוב בגמרא כאן, אבל אם כן, גמרא יבמות לא אומר דבר שווה לכאן. אז, לא נראה כן. ותו"ת.
** אבד חנינו -
היה קל לומר שהוא פו"ן, ומכוון לאביו ששמו חנין. ממה שרש"י לא באר זה, נראה שלא סבר כן. צריך ביאור ל"ל.
** רש"י נשים לילות -
היה אפשר לומר שמזהיר להם ללמוד כמו שעשה. ותו"ת.
** כו. גמרא לשנים -
ק"ק, שגמ’ דרש מזה כבר.
** זה נשיא -
יש לדון איך יודעים נשיא שאינו מלך. זה מניח שהיה לשאול דין מלך, אף שלא בא מבית יהודה. אולי לא היה דינו חלוק מנשיא.
** רש"י פגע -
יש לדון אם צריך לבוא בתיבה ממש או רק שלא לראות את ירושלים. לשונו משמע כראשון.
** כז. גמרא רבן גמליאל -
זה מעניין, שלכאורה, היו בימי רבן גמליאל, ולא ר"ג הזקן.
** כז: גמרא זוזי -
יש לדון אם מכוון לומר שזה גדול או קטן. ותו"ת.
** כח. גמרא חיה -
יש לציין לגמ’ יומא (כן אני חושב) שגם אומר מילת "חיה" על מי שיולדת, ולא על מי שמסייע לה.
** אמר רבא -
לכאורה, צריך לומר שעל רבה מדבר, ולא על רבא, שהרי רבא, שהרי רבא הוא המדבר, ולא ידע כמה יחיה, וגם לא יאמר שהוא גדול כר"ח. ויש לדון, שאולי גמרא אומר כן. אם נאמר שעל רבה קאי, יש סיבה לומר כתוס’ בגמ’ ר"ה יח. נראה לי שאולי להיפך הוא, שאולי יש להקשות איך גמ’ אומר שתלוי במזל, שאולי בדרך כלל לא תלוי במזל, אבל כאן היה עליו קללה. ותחשב. אולי זה משמע שלא היה רבה מבית עלי; אם כן, צריך לומר כרש"י באותו גמ’ בראש השנה.
** כח: רש"י לפתוח ראשון -
עיין במש"כ. עיין ברש"י בגיטין בזה.
** כט. גמרא לך -
נראה שאולי גופא מה שהוא רע הוא מפני שהוא לשון של מתים. ותו"ת.
* Footnotes
[fn:1] ואין לומר שאם כן, שרק רוצה בטוב אחת, איך יש צד שיחייב בחרישה, שחרישה הוא עשיית שינוי בקרקע לטובת העצים שהם עכשיו (או שיהיו להבא) בקרקע.
[fn:2] צריך ביאור קצת מה נחשב "הלכה אחת.” עיין בתמורה גבי חטאות צבור שלא מתות כעין זה.
[fn:3] לכאורה, הוא סימן. ויש לדון.
[fn:4] ויש לדון, שצריך לעיין בפשט זה של רש"י, שמקושיית גמרא חגיגה על מאמר זה, לכאורה, מוכרח שיחטא כאן. ועיין שם (הוא בפרק שני, בסוף האגדתות).
