* ב.
** רש"י סוכה -
לעולם ישנה- יש להעיר שזה קצרה שהיא ארוכה, שבין הכל הוא יותר גדול, שהרי צריך לשנות גם כן כל תקנה. ונראה שיש מעלה במה שכל משנה אינו כל כך גדול.
* ב:
** רש"י מחלקת -
אמוראי- לא אמר כן בשנים ראשונים כיון שיש לומר שלא חולקים, ומר הזכיר אחד ומר הזכיר אחד. ונראה מגמרא שכיון שלמעשה הוא מחלקת אמוראי, מסתבר שאף חולקים כולם במה אמר רב, ואז מסתבר שזה לא סובר כזה וזה לא כזה (ורש"י מבאר קודם שיודעים שהוא מחלקת מה אמר רב).
* ג:
** גמרא חצר לפי -
נראה שהסברה לזה הוא שכל מי שיש לו יותר פתחים ישתמש יותר בחצר. אז, החצר יותר שלו (או שזה סימן שבקנין ראשון, קנה יותר ממנו, או שכיון שחסר יותר בחילוק חצר, שחסר חצר שבו היה משמש יותר, ממילא נוטל יותר). ותחשב. ויש לדון.
* ד.
** גמרא דחזיא -
תחשב מה לנו בזה, שלכאורה, זה פסול בסכך, ולא בדופן. ותחשב. גם יש להעיר שלכאורה, יכול להיות דופן אם מניחים סכך באמצעיתה. צ"ל שאז כבר נשנה (ואין הגבוה נחשב הדופן).
* ה.
** גמרא כלי -
נראה שההוה אמינא ללמוד מציץ יכול להיות שציץ מרצה, ואז הוא ככלי. אפשר שמסיק שאף על פי כן, אינו כלי, או שחלוק כיון שהוא אף תכשיט או שרק מרצה על ידי היותו תכשיט. נראה שזה תלוי באם מרצה אם אינו על מצח כהן גדול.
* ה:
** גמרא פני כרובים -
נמצא שפני קטן הם שווים כפני גדול (ששל יצחק גם כן היו טפח).
** רביא -
נראה שהוא לשון סגי נהור (כיון שאינו רב, אלא זוטר).
* ו.
** גמרא ארץ שכל -
לכאורה, לשון זה קשה להבין. נראה שר"ל שא"י מקולס על מה שהוא ארץ שבו יש יותר סיבות למצוות. אם כן, עליו ביותר נאמר כל השיעורים. ותחשב.
** רש"י דבש -
עיין במה שמבאר. אם כן, אף שלא"ק יהיה בכלל דבש (ואולי זה סיבה להתירו, שהרי אומר קרא שדבר מותר). ותחשב.
ועיין בבכורות שדן בזה בגמרא. ויש לציין לרש"י זה שם.
* ו:
** גמרא לגופיה -
צריך ביאור למה לא דורשים עדיין ממה שהוא בלשון רבים. ותחשב. ואולי אינו מיותר לומר גופו, שכל בני ישראל בדר"כ לא יושבים בסוכה אחד. רק אם הוא רק קרא מיותר שבא לגלות דין, אז אף לשון רבים מיותר, ודורשים ממנו.
** טעמא דר"ש -
לכאורה, רצה לומר שזה מגלה מהו "סוכה,” ומזה מגרע ההל’.
* ז.
** כארבע -
עיין בציור. לכאורה, רק נראה כשלש מחצות, אבל נראה שסתמו אותם שלש.  ותחשב.
* ז:
** גמרא ככבשן -
יש לדון למה לא אמר לשון של אחרים. ונראה שאולי חולק עליו כיון שלא ידע עליו (ואז לא יכול להביאו). ואפשר שסבר שאינו נכון (וצ"ל שידע כן מסברה). ותחשב.
* יג:
** גמרא הקשין -
יש לדון בזה, שרוצה בפירות, שכיון שבטלים לסכך כשר, לכאורה, מרבים בסכך. ותחשב.
* טו.
** גמרא ולא גזר -
קשה, שאולי סובר כצד כאן שלא גזר.
** רישא -
לכאורה, הוה אפשר להפך.
* יז.
** רש"י פסולה -
גבי אויר נמי- יש לדון ששם אין אומרים הלכה זה (שהוא הלכה בלי טעם). ויש להוסיף קצת טעם שהוא ששם רואים שאינו שם, משא"כ כאן, שהוא מכוסה.
** קשה למה
לא יפסול סכך פסול שיש בו דופן עקומה כיון שיהיה כפסל היוצא (עיין רש"י לעיל). ונראה שאולי אינו כפסל היוצא, כיון שהוא הדופן, או הוא על גב דופן. ותחשב.
* כו:
** גמרא דמר כדרב -
ק"ק למה אמר שם כולם; לכאורה, רק מבארים שיעורו, ואז היה לו רק לומר השיעור. אף אם רוצה לומר ביאור אחר של אותו שיעור, אין צרכים כל כך ביאור. ותחשב. ואולי בא לשבח כל הני גדולים.
ועיין ברש"י, שנראה שבא לומר שזה למד מזה…[fn:1]. ועדיין קצת יש לדון בזה על פי גמרא בנדרים שאומר שרק מזכירים ראשון ואחרון. זה כבר אינו כל כך קשה, שהרי מצאנו כמה גמרות שמזכירים יותר מזה; אז, אולי כבר מוכרח שרק אומר שאין צורך להזכיר יותר, אבל אם רוצה, יכול. ויש לדון למה ירצה, ולה לא יעשה כמה שאומר גמרא בפסחים ש"לעולם ישנה… קצרה.”
* כז.
** גמרא דאביי -
יש לדון אם מניח ששיעורו חלוק משיעור כביצה או שמקשה ממה שלא הקשה על רב יוסף מברייתא.
* כז:
** גמרא יצא -
יש לדון למה ייצא, שכבר נעשה. ואולי רע ליהנות ממנו.
* כח.
** גמרא ראויים -
וא"ת לא קם כמשה. ויש לומר שאין זה לנביאות. גם יש לומר שלמעשה לא קם.
** ואסמכינהו -
משמע כצד שאומר רמב"ם שהוא רק סימן (ונראה שאין זה בעיה לריטב"א, שרק חולק כיון שסובר שלא היו אומרים דבר שלא סובר קרא שהוא נכון בתוך קרא).
** רש"י הלכות -
מעניין למה מפרש אלו. ונראה שנקט אלו שנמנים במנין. ויש להעיר שיש מאלו שהם מח’.
* כט.
** גמרא שוהה לבא -
יש להעיר שלכאורה לא יהיה אופן לה’ לגלות שיבא על יושבי מזרח מהר (או להפך). ותחשב.
** מי שפך -
יש לדון אם אומר שעבירות בני ישראל וכדומה הם השפיכה או שאומר שקיום סוכה- קיום מצווה אחר שחטאנו כל כך- הוא השפיכה. ותו"ת.
** רש"י תרתי -
עיין לעיל, שלא אמר רש"י כן בביאור "שיאור.” דע שחלקו (ביאור הלכה סימן נח) מהו הארת המזרח. לכאורה, רש"י אומר כשני הצדדים. ונראה שרש"י מניח שהוא עלות השחר, אלא שממה שברייתא אומרו בשני דיבורים, משמע שאינו כן. אז, צ"ל שהוא זמן אחר. אז, הוא סתירה- וזהו מה שמקשה. יש לדון למה נוח להניח שהוא סתירה ולהקשות כן ולא להניח שהוא כופל את עצמו ולהקשות את זה. ותו"ת.
* כט:
** רש"י יבש -
ק"ק למה אין אומרים כן גם כן גבי אגד לולב. ויש לומר ששם אינו חלק מגופו.
** כדי לנענע -
משמע שהסיבה לזה הוא לעצור רוחות רעות, ולא רק שעושה כן.
** לנענע -
יש לדון מהו המקור שצריך לנענע (שצריך להיות, לכאורה, דאו’, שהשיעור מיוסד בו).
* לא.
** גמרא אבל גזל עצים -
שינוי מעשה- יש לדון איזה מעשה יש בזה, שיהיה כציור שבונה אותו בביתו. ואולי רגיל לשנותו כשנותנו בסוכתו (למשל, גוזזו כדי לעשות שיבא בקל).
* לב.
** גמרא ש"מ כאביי -
זה רק מוכיח שיש גדר, אבל לא שהוא כמש"א אביי.
* לב:
** גמרא לא דק -
מעניין שאומר כן אף שנמצא שאומר ממש כשיטה החולק. ותו"ת.
** רב עליו -
שנים- לכאורה, אין זה מוכרח, שיש לומר שנשרו שלש מזה ושלש מזה… ויש לומר שאם כן, עדיין יהיה חסר שילוש, ולא חש לפרש.
* לג.
** גמרא במקום אחד -
אף שצ"ל רוב של כל, ואף לא באותו מקום. זה קצת קשה לי.
** שלשה בדי -
הפוסקים מבארים שר"ל שבכל בד נשאר עלים. ודחוק, שלמה צריך להזכיר כאן מנין הבדים. ולולי זה, היה אפשר לומר שצ"ל שלש בדים יוצאים ממנה עם העלים אם יוכשר על ידי זה.
* לג:
** גמרא של אשירה -
משמע שהוא שלו (שאל"ה, כבר אמר אותו פסול, ועוד שיש לו לבאר עפ"ז כיון שהוא יותר פשוט, שכבר אמרו. ויל"ד.)
** רש"י לא צריכא -
ממה שלא פירש שהוא מחמת שאז הוא "לא איכפת ליה" משמע שסובר שאף זה אסור.
** האי תנא -
יש לדון אם כוונת רש"י לומר שאף רבנן מודו שיש ענין באגד (וכמו שאמר גמרא) או שאף רבנן מודו שיש ענין שיהיה ממינו. ויש לדון למה.
* לד.
** גמרא רבא בר יוסף -
סתם רבא הוא בן יוסף (כן אומר גמרא בנדרים). אם כן, יש לדון אם זה רבא (מה שלא אמר שמו סתם משמע שאינו רבא סתם).
* לד:
** גמרא מ"ט -
קשה, שדילמא הוא מפני שסובר כמותו, כמה שאומר גמרא. ושו"ר בתוס’.
** אם נטל כשר -
לכאורה, רצה לומר "יצא.”
* לה.
** גמרא לא אפשר -
עדיין צריך ביאור איך דורשים ששם מיירי בפלפלים ולא באתרוג. ויש לומר שאם היה דן באתרוג לא היה חידוש.
** רש"י מסיקה -
לו ולא לאורו- קשה, שאף אם לא היה צד שילך לאורו, היה אומר "לו" למעט ציור שאין לו תשמישים ממנו (בטומאה). וצריך ביאור. ותחשב.
* לה:
** גמרא וחזי -
נראה להעיר שאולי כאן יותר מסתבר מבשאר מקומות, שהרי כאן בי"כ ובי"כ אינו ממש מותר באכילה, שהוקצה למצווה. ויש לדון, שזה רק דרבנן. ותחשב.
* לו.
** גמרא דלמא לא היא -
זה מוכיח שבכל זמן שאומר כן גמרא, רצה לומר שממש סוברים זה כזה, ולא רק שיש אותו יסוד. ותו"ת.
** רש"י הכא מאי -
צריך ביאור איך מניח רש"י שקיימי סמפונות, שאז קשה:
1. אם כן, אין זה ציור של טרפות.
2. אם כן, אין ראיה מ"תפח,” שיש לומר ששם תפח לגמרי.
* לו:
** גמרא שנוהגת -
ממה שנחשב חומרא גבי לולב, נמצא שההוה אמינא הוא ליתן חיוב אחד ללילה ואחד ליום, ולא לעשות שיכול לקיימו בין בלילה בין ביום. ויש לדון.
** שנוהגות -
היה אפשר לומר שהקו"ח אינו מקלות וחומרא, אלא מכמה מצוי הוא, אלא שגמרא לקמן מבואר שלא דורשו כך. ויל"ד למה לא.
* לז:
** גמרא כדי לעצור -
זה משמע שהוא סיבה לתנופה כמש"כ לעיל.
* לח.
** רש"י וכן לולב -
משמע שהוא רק על מה עושה, אבל מרש"י לעיל מבואר נגד זה. וצריך ביאור. ואולי בלולב, אין זה סיבתו, אבל בתנופה, זהו סיבתו. רש"י לעיל לא משמע כן. ותחשב. ואולי משווים תנופה ללולב (ולא לנענע), וזה אין כל סיבת לולב, אלא ניענוע). ותחשב.
* לח:
** גמרא עיין במקור
לדין שומע כעונה. לשון המקור משמע שהוא ממש כקורא (ולא רק שמקיים על ידי שמיעה).
* לט.
** גמרא מוסיף -
צריך ביאור איך ידע גמרא שלא להחליף לומר שרבי רק כפל "אודך.” ותו"ת.
** הלוקח -
שנה דין זה בלוקח כיון שמיירי בקונה מעם הארץ, ועם הארץ לא ידע וישמע לדין זה.
* מא:
** גמרא אלא אם כן -
לשון זה קצת מוזר, שאם נתנו לו, אז אינו עדיין של חבירו. ואולי בא לחדש דין מתנה על מנת להחזיר, וכיון שעומד לחזור לחבירו, קורא אותו שלו. ודחוק.[fn:2]
** לאו מצווה -
משמע שיש מצווה בלולב, אף שלכאורה, כבר יצא. ואפשר שרק רצה לומר שיש פעם שהוא מצווה להשיאו. ויש לדון מה לנו בזה.
* מד:
** גמרא אייבו -
מעניין, שהיה, לכאורה, בזמן רבי, שהיה אביו של רב, ור"צ היה בזמן המקדש.
* מז:
** גמרא מ"מ -
משמע שאין חיוב לשתות יין בחול המועד.
* מח.
** גמרא ארבעה -
קשה למה לא פוחת שלש, שאז אין לבוד. ואולי רצה לומר מן הצד. וקשה למה לו לעשות כן. ואולי הוא יותר קל. ותחשב.
** רש"י לרבות -
קל וחומר- יש לדון מהו הכש"כ. גם יש לדון למה אין פירכא ממה שאין לפניו קדושה. משמע קצת שאין זה פירכא (ואין זה סיבת הדין, אלא הדרשה הוא סימן). ותחשב.
* מח:
** רש"י נפגמה -
על ידי אבנים- קשה, שזרקו אתרוגים.
* מט:
** גמרא קרבן -
נראה שר"ל שהוא כנגד כל זבח, אבל רק אחד (ור"ל שהוא נגד שום זבח), שאומר זבח סתם. ותו"ת.
* נ:
** רש"י חשובה -
יש לדון מהו החשיבות במה שבא משיתין שהוא ישן הרבה. ויש לדון.
* נא:
** גמרא קרא -
יש לדון מה קרא מוכיח, שאינו מוכיח שיש לחוש לזה, שהרי כבר ראו שיש לחוש, ואין לומר שמוכיח שהוא רע, שזה לכאורה, פשוט.
* נב.
** רש"י וספדה -
ק"ק למה נקט חד פשט (עיין לקמן).
** שעוסקים -
יש להעיר שמה שאומר שכבר נשחט אינו לאותו פשט שאמר בדיבור הקודם. ותחשב. גם יש להעיר שזה משמע שיכולים בני אדם לחטוא בלי יצר הרע.
* נב:
** בהדי ר"ח -
נגאה שהוא ר"ח בגדתאה, ולכן נקרא כן (כצד שברשי שאומר "בעל אגדתא").
* נג.
** על דאטפת -
קשה איך גלגל צף. ונראה שהיה עמו בשר (שהיה נחתך ונשלך), ובשר, כשנרקב, מוציא gas ואז צף. ועיין בMarie Roget של Edgar Allan Poe. ותו"ת.
** קמיה -
משמע שעשו כן אף שלא בזמן הבית.
** רש"י תרי כושאי -
יפה- כמו שאומר תורה על צפורה. יש לדון למה לא אומר שהוא כושי ממש. ותחשב.
* נג:
** גמרא חנקא -
יש לדון איך היה יכול לומר כן כיון שקללת חכם בא, ואז ממית אדם. ואולי לא ידע.
** לעשות שלום -
יש לדון למה מניח שהוא לעשות שלום. גם ק"ק למה לא אמר ששם הוא רק ספק. ואולי אף כאן היה ספק. ומעניין להיות מסופק בדבר כעין זה, שלכאורה, אין כל כך סיבה לחשוב כן. ותחשב.
* נה.
** רש"י אמבוה -
מצינו, אז, סימן לסימן.
* נו.
** גמרא מה מכרו -
יש לדון בזה, שלכאורה, דוד תקנם (וכדומה). ואולי הכריחם למכור. ותו"ת.
* נו:
** ואע"פ -
גורס רש"י "כל,” אף שמצינו שאינו כן (מצינו בגמרא שיש שאינו כן). ותחשב.
* Footnotes
[fn:1] ועיין בכעין זה ברש"י ביבמות (צג.)
[fn:2] ויש להעיר שמיד מביא מעשה שדן בדין מתנה על מנת להחזיר. ותחשב. ונראה, אולי, שזה גם כן יבאר למה צריך מעשה, שהרי פשוט הוא, לכאורה, איזה דין יוצא ממה שאומר שצריך לתת אותו; ונראה שמחדש לשון שצריך לומר שלמתנה ע"מ (שצ,ל מתנה ע"מ ולא שאלה), ולכן צריך מעשה. ותו"ת.
