* ב.
** אלא שהכפרים -
לשון "אלא" קצת מעניין, שמשמע שהאמור נכון, אלא אבל לא כל כך. יש לומר שר"ל שכן עיקר דינו (רצה לומר, זמן שבו מצווה יתקיים הכי טוב), אלא… גם יש לומר שמקיים באלו ימים מפני יחסם ליום יד (כמו כן, יש לומר שר"ל שבא לזכור מה שקרב ביום יד). ותחשב. ועיין בשיח שי על פסחים כעין זה. אם כן, רק יד זמנו.
** זמן קהילה לכל -
תחשב על זה. וצריך ביאור, שאינו כשר לשאר בני אדם.
* ב:
** ולאו ישראל נינהו -
צריך לחשוב מהו קושיה זו, שיש לומר שרק ישראלים מיוחדים נתחייבו. ואולי יש קרא האומר צווי על "ישראל.”
** כדי -
מעניין מה שבכ"מ נחלף כדי ברבא. אם היה אדם ששמו כדי (שני צדדים שנדון בהם הם שני צדדי רש"י), יש לומר שהיה שום שוויות בינו לרבא. אם רק רצה לומר "שום תלמיד חכם" צריך ביאור. ואולי שם רבא (אבא) הוה מצוי, ואז, אחר, ששמו היה אבא, נשכח, ואז רצה לומר שאו רבא או שום אבא אחר אמרו. גם יש לומר שידוע שהיה אבא, אבל חששו ש"אבא" הנאמר רצה לומר תלמיד חכם (כן מצינו לפעמים), ואז, הוא שום תלמיד חכם.
** כיון דאית ליה פרזי פרזי -
ק"ק למה צריך שום קרא, שחי’ בין פרזים לכרכים בפירוש במגילה (וכל דיניה למדים לעיל). ואולי צריך להזכירו ללמד שאר דיני מקרא זה.
עיין ברש"י בכל זה. לולי רש"י, היה אםשר לומר שמדינה מיותר לחד דין דר’ יהושע ויש עוד מיותר ללמד דין שני. ולא נראה ששני "בעיר"ים הם, לכאורה, מיותרים. ותחשב.
* ג.
** שאין נביא עתיד -
לעיל אמר "רשאי.” לכאורה, כאן רצה לומר שלא מגיע לו נבואה שישנה ויחדש דבר. כיון שלא יגיע לו, פשוט שאי אפשר לשנות, שאז ממציא נבואה מדעתו.
** שמבטלין ת"ת -
ואם תאמר הרי מקיימים תלמוד תורה על ידי שמיעת מגילה. ויש לומר שחוששים שלא יבאו כולם. ונראה אולי שלכן לא נחשב ביטול תורה דרבים, שרבים ילמד בין כך ובין כך).
** במעמדן -
מעניין שאומר לשון ברייתא, ולא הביא ברייתא. אולי לא ידע שהיה ברייתא, אלא ששמע מרבו כן, ולא ידע שרבו למדו מברייתא. ויש לדון, שהיה לו להביאו בשם רבו.
** לבטלה -
רצה לומר, בשקר. ומעניין שנמצא לשון שווא לומר לבטלה (שבועת שווא או שם ה’ לשווא) ושקר (עדות שווא).
** דלא מפקי -
משמע ששידם מצויים. ושי לדון, שאולי כך נבראו (שזה אי אפשר להם). ויש להעיר שמצינו שכר לשדים (גיטין), ושד שנתחייב ממון (חולין).
* ג:
** מהקרבת תמידים -
אולי יש לחלק בין תמיד של ביה"מ לשל במה.
** של רבים -
קצ"ב, שאם כן יחיד צריך להפסיק, נמצא שהפסיק של רבים. ואולי רצה לומר שלא היו רבים לומדים בין כך ובין כך. ועיין במה שתירצנו לזה לעיל (ג.) דבור המתחיל שמבטלים.
** כרך שישב -
ק"ק איך נדע (שהיה מזמן קודם).
** שחרב מעשרה בטלנים -
אם כן, קשה למה צריך שני מאמרים. וצריך לומר שאמוראי חלוקים אמרו שניהם, וחד דין הוא.
* ד.
** ולטעמיך-
1. זה קשה על מש"א שאלפעל בננהו.
2. הוה ליה להקשות בזה (ומצינו “לטעמיך” כזה בכמה מקומות). ויש לדון איזה היה יותר טוב להקשות ממנו.
** משה תקן -
מקשה העולם שהרי צריך ללמוד שלשים יום קודם. יש לומר שהוה אמינא שביום טוב אין צורך ללמוד, שכבר למד לשלושים יום . ותחשב.
* ד:
** לא תקינו רבנן -
אכתי קשה למה לא. ויש לומר שצריך להיות קרוב לזמן הנס.
** שמספקים מים -
כיון שהגענן לזה, יש לומר שחוששים שלא יספקו בלי שכר זה.
* יב.
** איהו בקרי -
נראה שיש בזה קצת פון, שדן בביאה.
* יב:
** מכאן שההדיוט -
יש לדון אם רצה לומר שלומד שאף הדיוט יכול או שכן דרך הדיוט.
* יג.
** דלא קטליה -
ק"ק למה לא אמר שבנימין הוליד את מרדכי.
* יג:
** לא יגרע מצדיק -
אולי דורש עיניו לעניו. עיין ברש"י נגד זה. אגם, גם יש לומר שדורש עיניו לומר שנוטל שכר על מה שאין בני אדם נותנים עיניהם בו. ותו"ת.
* יד:
** שהנשים רחמניות -
צריך ביאור מה לנו בזה; מה שתשמע תאמר.
* טז.
** שני שכיכות -
לא הבנתי איך רואים מזה שני שכיכות.
* טז:
** שדעת זקנים -
לכן נתן יין יותר זקן לזקנים בסעודת אחשורוש (עיין לעיל).
* יז.
** ארביסר -
זה רק מוכיח שהיה שום מצווה שמפנהו לא נענש, ולא מהו אותו מצוה, שמי יימר שלמד באותו זמן. ויש לומר שתפסת מועט…, ורק הניח שתלמוד תורה, שהוא הכי גדול, יכול לעשות שלא יענש. ותו"ת.
* יז:
** מנין שאומרים אבות -
ק"ק ל"ל דורש סדר אלו. ואולי כן סדר קראי.
* יח:
** נקט -
קשה, שאם כן יאמר אין הלכה, וזה נגד שיטתו.
** מידכר -
יש לדון אם רצה לומר שאז זוכר אם מזכירים לו או אם רצה לומר שלאחר כן זוכר מה שקרה אז אי מזכירים לו. ותחשב. חושב אני שיש רש"י שאומר כחד צד.
* כ.
** מן המתיר -
ואם תאמר מהו ההוה אמינא שנביא ראיה. ויש לומר שלא היה ה’ עושה ששום רע יבא לו, ואם כן, צריך לומר  שיצא. אומר שאנוס הוא כשיטתו, ואז אין בעיה. ותחשב.[fn:1]
* כ:
** מנלן -
צריך ביאור מהו ההוה אמינא.
* כא.
** וכרבי יוסי -
צריך ביאור למה צריך להיות כר"י, שאף לרבנן יכו"ל כל היום, אלא שיש צורך אחר (רצה לומר, שאם מאחר סילוק, נמצא בסוף היום, ואם מקדים, נמצא בתחילה). ותו"ת. עיין ברש"ש יבמות כט. כעין זה.
ואגב, יש לדון אם זה (רצה לומר, מה שיכול להיות בכ"י) סיבה או סימן. ותו"ת.
* כב:
** כולן מברך עליהם -
או מביא ראיה ממש"א שמברך עליהם או מביא ראיה שמה שלפניהם הוא ברכת המצוה.
** כנגד מי -
לשון "מי" מעניין, שמניח שהוא כנגד מי, ולא מה. ותו"ת. ויש להעיר שלתירוץ גמרא, אינו, לכולי עלמא, כנגד מי. ותו"ת.
* כג:
** וחמשה ישראלים -
עיין בסנהדרין, שמביא קשיא זה בשם אמורא.
* כו:
** לנטורי… קמ"ל -
כמובן, יש לדון אם קא משמע לן שאינו לשמרו או שאף לשמרו נחשב תשמישי ק’.
** מלא וריקם -
לכאורה, אין רואים טלטול ריקם.
** הדר הוה -
קצת יש לחלק, שאין כאן מה לחול ק’ עליו.
* כז.
** כיון דלא מעלי -
צריך לחשוב במו סברה זו. אי אפשר לומר שקל שיש גנאי במכירה, ואפשר רק אי יש מעלה, שדן גמרא אף בלי מכירה. ותחשב.
* כז:
** ברב עם -
צריך ביאור איך זה דוחה מש"א ר"מ. ותחשב.
** ברכתיך -
יש להעיר שאין כל כך טוב אם יענה כמו שנתקיים לו. ותו"ת.
** רבי פרידא -
כמובן, ק"ק שידוע שבא ממעשה של תלמיד שחזר עמו ד’ מאה פעם. ויש לומר שכבר היה זקו או שזה וזה גרמו לו (כמו שאומר גמרא בביאור הא דקרי ללוי (תענית?)). ותחשב.
* כח.
** עיניו כהות -
יש לדון אם מוסיף (כנ"ל) או חולק.
* כט:
** טבי -
זה שם עבד ר"ג. או נתן לו ר"ג שם יהודי או ר"ט היה לו שם עכו"ם או שקרא לאחד בשם דבר אחר (או שר"ט נקרא כן כיון שהיה כל כך כשר או שעבד נקרא כן כיון שהיה כעין ישראל).
* Footnotes
[fn:1] זה גם כן נוגע למה שהוכחנו בשיח שי חולין (גלגל רביעי) שדין של "בהמתם… צדיקים עצמם לא כש"כ" הוא רק לדבר שהוא אסור לשיטתו.
