* ב.
** לא פחות ולא יותר -
לשון זה מעניין, שלכאורה, היה לו לומר שלא יקרא קודם לכן ולא אחר כן.
** רבי עקיבא -
מצאנו בכ"מ שר"ע דורש אף דברים קטנים. כן דורש כאן, וכמו כן מצאנו שדורש וי"ו. כמו כן דורש "את"ים. יש לציין לגמרא סוטה (מט.) שאומר שהיה כבוד תורה בטל במיתתו, כיון שהיה דורש כל כך טוב (עיין ברש"י שם).
** כימים -
יש לציין לגמרא ברכות (ג:) שבו יש מחלקת בפירוש "כחצות,” שיש אומרים שר"ל שהוא ביום אחר בחצות, והוא כחצות של עכשיו, או שר"ל דבר אחר. נראה שזה שייך לדיון של גמרא כאן. ותו"ת.
** אלא הכי -
[
לשון אלא קצת מעניין, שמשמע שהאמור נכון, אבל לא כל כך. יש לומר שרצה לומר שכן עיקר דינו (רצה לומר, זמן שבו מצוה יתקיים
טוב), אלא.... גם יש לומר שמקיים באלו ימים מפני יחסם ליום יד. ותחשב על זה. עיין בשי"ח ש"ח על פסחים. אז, רק יד זמנו, אף שיכול לקרוא אותו בימים אחרים. ותו"ת.
כמו כן, יש לומר שמה שיד' הוא עיקר זמנו הוא שבא לזכור מה שקרה ביד'. אז, יד' היה לו להיות זמנו. ותו"ת.
** תיובתא -
נמצא שר"י איתותב רק לשיטתו, שאם אין משנה שלנו ר"ע, יש לומר שלפני זמן הוא, ור"ע (משנה) סבר כר"י.
** זמן קהילה -
צריך ביאור, שלמעשה לא כשר לבני יד’.
** סתומתאה -
ויש מפרשים- לא ר"ל שסתמות כמותו (שכ’ "תלמידיו"), אלא שאף ברייתא וכדומה כמותו. קצת צריך ביאור  למה יצטרך גמ’ את זה בענין סת"מ כמותו. ותו"ת.
* ב:
** כיון דפרזי פרזי -
צריך ביאור מהיכי תיתי שדורש פרזי פרזי, ולא דורש מכאן. ותו"ת.
** לאו ישראל נינהו -
צריך לחשוב מהו קושיה זה, שי"ל שרק ישראל מיוחדים חייבים. נראה שקושיית גמ’ אומר שיודעים סיבת החיוב, והוא שהיו נהרגים, ואז פשוט שאף אלו חייבים, שאף אלו היו להם להיות נהרגים.
** כדי -
מעניין שמצאנו בכ"מ שכדי נתחלף ברבא. אם היה אדם ששמו כדי, יש לומר שהיה שום דמיון ביניהם. אם רק ר"ל "שום ת"ח,” צריך ביאור. אולי שם רבא (אבא) היה מצוי מאד, ואז מי ששמו אבא נשכח. ותו"ת.  (דיון זה בשם כדי הם שני צדדים ברש"י.)
** כיון דאית ליה פרזי פרזי -
ק"ק למה צריך שום קרא, שחי’ בין פרזים לכרכים בפירוש במגילה (וכל דיניה למדים לעיל). ואולי צריך להזכירו ללמד שאר דיניו מקרא זה.
* ג.
** ולא הוה ידעי -
צריך ביאור איך זה חלוק מ"שכחו.” אולי ר"ל שלא הודיע ה’ כלל איזה יהיה באמצע ואיזה בסוף. קשה, שנראה איזה היו בלוחות או כדומה.
** חגי זכריה -
לכאורה, חיו לזמן הרבה, ולא חי יונתן לזמן הרבה, שהרי גמרא אומר שאף ראו את רדב"ה. ותו"ת.
** דאינהו -
נשתלח- משמע שהיה נביא (ר"ל, שבא לו נבואה), אלא רק לא נשתלח. יש לדון מהיכי תיתי לרש"י זה. גם יש לדון איזה מעלה יש בהיות נשתלח לבנ"י.
** אמש- הבנתי איך יכולים להבין שגם הקפיד על ת"ת, שזה היה "עכשיו" (אלא שעדיין צריך ביאור איך נאמר שלא היה מצווה אחר שבטלו, כמו ק"ש של ערבית או פו"ר), אבל בוודאי צריך ביאור איך נדע שהיה המצווה האחר תמיד. ותחשב. עבודה שהיא חמורה -
יל"ד מהי"ת.
** אין נביא עתיד -
לעיל אמר רשאי. לכאורה, כאן ר"ל שאין נביאות שמחדש דבר מגיע לו. ממילא, כיון שאין לו נביאות, אסור לו להגיד נביאות כזה, שאסור לשקר כך.
** ת"ת -
ואם תאמר הרי יוצאים ת"צ על ידי שמיעת מגילה. ויש לומר שחשש שלא יבואו כולם. ונראה אולי שלכן לא נחשב ביטול תורה של רבים, אף שמסתמא היו רבים לומדים שם, והוא מפני שיש שלומדים בין כך ובין כך.
** מעניין
שאומר רב לשון ברייתא ממש, ולא הביא ברייתא. משמע שלמד מרבו לשון זה, אבל לא ידע שבא מברייתא. יש לדון, שלא אמרו בשם רבו. גם יש לדון ל"ל אמר לו רבו שהוא ברייתא. אולי אמר ושכח. אולי גמרא אמר אותו בלשון ברייתא, שגמרא ידע את הברייתא. אם כן, צריך לומר שאין גמרא אומר ממש מה שאמר אמורא. ותו"ת.
** לבטלה -
ר"ל בשקר. ומעניין שמצאנו לשון שוא ושקר בתוך משמעות מילת שוא.
** שם שמים -
משמע ששדים מצוווים. ויש לדון, שאולי כך נבראו (ובאמת, קצת נראים שאין להם בחירה על כעין זה). ויש להעיר שמצאנו שכר לשדים (בגיטין), וכן חיוב לשלם ממון (בחולין).
* ג:
** יש לדון אם למעשה
מבטלים תלמוד תורה דרבים למגילה. עיין לעיל שכתבנו צד שלא שייך. מרש"י קצת נראה שלא מבטלים, אבל יש לדון.
** תמידים -
אולי יש לחלק בין תמיד של בית המקדש לשל במה.
** קצת צריך
ביאור, שאם כן יחיד צריך להפסיק, נמצא שבטל של רבים. אולי יש חילוק בין אם כל יחיד יושב ולומד לאם לומדים ביחד. גם יש לומר שבדרך כלל, אין רוב בני אדם לומדים בזמן שמפסיקים.
** את לא תעשה -
עיין ברש"י. לא נראה כן מגמרא שם, אלא נראה שקאי על דיני דרבנן. עיין שם. והלאו אז, הוא לא תסור.
** שישב -
עיין ברש"י. צריך ביאור למה אמרו רק לענין זה, שלכאורה, הוא אף למגילה, שנלמד מיניה. אולי אמר דין שהוא אף לרבי יהושע. גם יש לומר שאמר דין שבא ממקור שהביא.
** כרך שישב -
קצת קשה איך נדע (שהיו מזמן קודם).
** שחרב מעשרה -
אם כן, קשה למה צריך שני מאמרים. וצריך לומר שאמוראי חלוקים אמרו שניהם, וחד דין הם.
* ד.
** ע"ש זמנם -
מה שאומר רש"י ומה שאומר גמרא לא משמעים להיות דבר אחד. ותחשב.
** ולטעמיך -
זה קשה על מה שאמר שאלפעל בנאו. גם היה לו להקשות מזה (מצאנו לטעמיך כך בכ"מ).
** משה תיקן -
מקשה העולם שהרי צריך ללמוד שלשים יום קודם. יש לומר שהוה אמינא שביום טוב אין צריכים שכבר למדו בשלשים יום קודם לחג.
** ולשנותה -
עיין ברש"י- אף שאין קוראים ביום זעקתם, צריך לומר שיש שייכות. כן רואים בחד פ’ של יום כניסה, שפירש שהוא יום שבו התפללו.
** סבור מינה -
עיין ברש"י. אם למדו בלשון הקודש, צריך ביאור למה כתבו ש"ס (ובפרט אלו, שכתבו ירושלמי) בלשון ארמי או סורסי.
** למיתני -
עיין ברש"י. יש לדון מה עשו קודם שהיו להם משנה. יש לומר שחזרו על הלכות שידעו.
** יזמרך -
עיין ברש"י. יש לציין לגמרא ערכין (י:) שאומר שבקריאת מגילה הוא הלל של פורים.
* ד:
** לא תקינו רבנן -
עדיין קשה למה לא. ויש לומר שצריך להיות קרוב לזמן הנס.
** מיום הכניסה -
ק"ק ל"ל. יש לומר שחלק מן התקנה היה לצרכם. קשה אז ל"ל דוחים של ר"י כך.
** לר שחינן -
רצה לומר לא היתירו בני אנשי כנסת הגדולה. אולי מכוון להם, או ר"ל רבנן, והוא מפני כן. ותו"ת.
** שמספקים -
כיון שהגענו לזה, יש לומר שחוששים שלא יספקו בלי שכר זה.
** שאני הכא דלא אפשר -
לכאורה, חולקים איזה יותר נחשב דמיון חשוב.
** אף כאן -
צריך ביאור למה כופל על כל זה.
** והואיל ונדחו -
יש לדון למה יותר טוב לדחותם לאז. גם יש לדון ל"ל אומרים שיג’ יותר טוב כיון שהיה זמן קהילה לכל. ותו"ת.
* ה.
** אכתי לא מטא -
ואם תאמר הרי אחר כן, קדושה ייצא. ויש לומר שיותר קל להשאר כתובה מלהיות לה לקרוא. ותחשב על זה.
** בזמנה -
כבר יש פרסום, כיון שכ"א קורא.
** שאין אסור
(ברש"י)- משמע שלא מקיים כלל.
** וחגיגה -
למחר- הוא אחד שיו"ט (קצת), שק’ אחת היא. ויש לדון אם צריך להיות אחר יום טוב או באותו יום (כג בחדש).
* ה:
** טובים השנים -
עיין ברש"י. ואם תאמר טוב השני, ולא השנים. ויש לומר שהשני לא ידע שאר הדינים. ויש לדון אם זה קשה, שפשוט שהכל משכחים, וצריך שני, וזה היה הטעם שכאן השני מועיל, ואז בכל פעם צריך שנים. ותו"ת. אז, מה שקרה כאן לא מוכיח כן, אל הוא איליסטריישי"ן.
** וכי פשיטא -
ק"ק ל"ל נאמר שפשוט שהוא של יד’.
** באתריה דרבי לא נהוג -
גם יש לומר שלא היו עמי האץ, ולא היה בעיה בזה. עיין שם בפסחים, שכן מפרש (שהוא רק כשיש ע"ה).
** משום הכי -
קשה, שנלמד ג"ש.
* ו.
** פרקמטיא שלו -
יש לדון אם לא מצליח בחלזון או בכל. ואם תאמר קשה לראשון ביחיד שנוטל. ויש לומר שלא יצבע יפה. גם יש לומר שאם רק ליקח לעצמו, לא יגזול אותו. עיין ברש"י.
** בל יראה גאות -
אם כן, נמצא שידע יצחק שהיה עשו רשע.
* ו:
** סייעתא -
ויש יגע- משמע שאין מוציא בלי יגיעה. אולי זה יותר פשוט.
** אם יאמר לך -
מעניין לומר לשון כזה. נראה שמחדש שלא רק כן קורה, אלא שיודע הזוכה בזה. ותו"ת.
** ואילו סדר פרשיות -
נראה שר"ל שרק דן בדיני פורים.
** דאין מעבירים -
ק"ק, אז, למה צריך קרא. אולי קרא מגלה שיכול. יש לדון מהו ההוה אמינא בלי קרא. אולי הוא שצריך בשניהם.
* ז.
** קבעוני -
לשון זה מעניין.
** אומתו -
יש להעיר שעיקר מחלקת בושתי היה דיון באיזה אומה יותר נאה.
** וייודע -
ק"ק, שזה רק אומר שהיה למרדכי רוח הקדש, אבל לא שיהיה לו בכתיבת מגילה.
** כאומתו -
מענייין ששאל אחשורוש לאומתו, אף שהיתה נראית לו כאומנתו.
** כאומתו -
ידוע כן או ממסורה, או מפני שכן אמרו בני אדם. יש לדון מה קרה כיון שבני אדם חשבו עלה אומנות אחרות, שמסתמא יכירו שהיתה נראית חלוקה לבני אדם חלוקים. ותחשב.
** פרסתקי -
ק"ק שדילמא שקרו.
* ז:
** קיימת בנו -
צריך ביאור למה אמר לשון רבים.
** בין ארור המן -
היה אפשר לומר צד (אבל אינו כל כך טוב מלשון גמרא) שלא יודע בין ארור המן להמון הארור, וכן גבי מרדכי, אבל בוודאי לא מחלף ארור המן וברוך מרדכי.
** איבסום -
עיין ברש"י. נמצא שאף ר"ז נשתקר, ולא רק רבה.
* יב:
** הדיוט -
יש לדון אם ר"ל שאף הדיוט יכול או שכן מדת הדיוט לקפוץ לפני גדול ממנו.
* יג.
** דלא קטליה שאול -
ק"ק ל"ל אמר שבנימין הוליד מרדכי.
* יג:
** מצדיק עיניו -
אולי דורש עיניו לומר ענו. עיין ברש"י נגד זה. אגב, גם יש לומר שדורש עיניו לומר שנוטל שכר על מה שאין בני אדם נותנים עינים בו.
** דם נדה לחכמים -
יש לדון איזה נפק"מ לה, שהיתה מסוכנת ליבעל. ויש לומר שצריך לספירת נדתה (שאם לאחר זמן לא תסכן, תדע אם היא נדה וכדומה). גם יש לומר שצריכה למרדכי.
* יד.
** נבואה שהוצרכה -
מניח שאינו מלאכי. עיין לקמן.
** חוץ ממקרא -
יש להעיר שהיה מרדכי קיים בימי בית שני, כמו שאומר גמרא במנחות (קרוב לדף ע). אפשר שלא היה עוד נביא.
** נבואה -
ואיהו לאו נביא- יש להעיר שרש"י לעיל היה משמע שהיה נביא, אלא רק לא אמר נבואה. עדיין לא יהיה בכלל מנין זה, שהרי לא אמר נבואה שנצרכה לדורות.
** נראה שמנה רק
הצריכים לדורות כיון שבא לבאר מימרה שלא עשו תשובה על ידי אלו ששלח ה’ (ושי לדון, שזה רק במימרא ראשונה).
** בחו"ל -
ק"ק, שזה מפריך הקל וחומר. אולי זה דבר שנוגע רק להלל. יש לדון למה יהיה כן.
* יד:
** שהנשים רחמניות -
צריך ביאור מה לנו בזה; מה שתשמע תאמר. אולי לא ישלח לה ה’ רע כיון שיצער אותה ביותר.
** מבני בניו -
ר"ל, מבני בנותיו.
** בבית אל -
ק"ק שאולי לקחם אחר שמת צבא סנחרב. זה אומר שאולי לא החזירו הבני אדם.
* טו.
- כמה חי מלאכי- עם היה עזרה….
** רשע בן רשע -
נראה לפ’ על פי מש"א חז"ל שבא עונש אב לבנים אם עושה כמעשה אביו.
** בזכירתה -
יש לדון אם מוסיף על רחב. גם יש לדון כמה צריך לזכור אותה. כמו כן, יש לדון אם צריך לזכור את רחב, או רק לומר שמה. ותו"ת.
* טו:
** שיהרג -
ל"א- לא הבנתי איך אפשר לומר כן, שהרי רואים שלא בטל במיתת המן. אולי טעתה. גם יש לומר שהאחד מהם לא ר"ל אחד מן השרים, אלא אחד מבני מלכות, וכוונה כאן היה לאסתר. ואם תאמר אם כן תמית א"ע. וי"ל שרצתה להמית גם את המן הרשע, כיון שהיה רשע. ועוד שאילו חי, היה גוזר עוד.
* טז.
** שני שככות -
לא ידעתי איך רואים מזה שני שככות.
* טז:
** שדעת זקנים -
נראה שדעתם נחה כיון שמראה להם שזקנות עושה דבר יותר טוב.
** שדעת זקנים -
נראה שלכן נתן יין יותר ישן ליותר זקנים בסעודת אחשורוש, כמו שפרש גמרא לעיל.
* יז.
** ארביסר -
זה רק מוכיח שיש שום מצווה שמפניהו לא נענש, ולא מהו אותו מצווה, שמי יימר שלמד באותו זמן. אולי היה לו לפרש איזה מצווה הוא. ממה שלא פירש, מסתבר שהוא ת"צ, שכבר אמר שאהב יעקב ללמוד תורה, שהיה יושב אהלים.
* יז:
** מנין שאומרים אבות -
ק"ק ל"ל דורש סדר אלו. אולי כן סדר קרא. עדיין הול"ל כן.
* יח:
- גם יש לומר שחייש לו אם קצת יותר מסתבר.
** נקוט דרב ביבי -
קשה, שאם כן יאמר אין הלכה, וזה נגד שיטתו.
** הא בכולה -
קשה, שאומר "אותיות.” ואולי ר"ל כל אותיותיו. קשה למה מזכיר כלל. יש לומר שכל מילה פסול בכך. ותו"ת. גם יש לומר שר"ל שהוא רוב. ותחשב.
** וכי מדכרו -
ויש לדון אם ר"ל שאז זוכר אם מזכירים לו או אם ר"ל שלאחר כן זוכר מה שקרה אז כשיזכירו אותו. ותחשב.
** אתרמויי -
עדיין יש לסייע ממה שמניח כן משנה לסתם ציור. יש לדון, שאולי פשוט כן, כמו שמוכיח גמרא.
** שלא מן הכתב -
יש לדון ל"ל:
1. שמא ישכחו לא יכתבו כראוי.
2. דרבים שבכתב לא יבואו מבעל פה.
ממעשה של רבי מאיר, נראה כראשון. יש לדחות שממה ראה אותיות לפני עינו, כיון שידע כל כך טוב. יש לדון אם זה נחשב בעל פה או לא. (יש מאמר ידוע מאור שמח על רוגוצובער בענין זה.) מדין תפילין, נראה כאשון.
** דבי בר חבו -
שכיחי-
1. כיון שכ’ ככ"כ התירו לו.
2. היו שכחין כיון שהיה יכול לכ’ בלי כ’.
** והלכתא -
עיין ברש"י. היה אפשר לומר שר"ל שכן הדין. ויש לדון אם רש"י יאמר זה אף על כ’ מכתב. אם לא, מעניין ל"ל פ’ על כולו.
* יט.
** ככתבם -
ק"ק מהיכי תיתי שזה עברית. אולי לא מסתבר להיות דבר אחר שעליו יקפיד. יש לדון, שאולי מתחילה, מס’ נכ’ בפרס, ולכן קפיד שיהיה באותו לשון. גם ק"ק איך אז יקרא בלעז. אולי צריך קרקטרים של לשון הקודש.
** קורא עמהם -
צריך ביאור למה כתב את זה כאן, ולמה כתב שניהם באותו משנה.
** אבל אין עתיד -
לאותו יום- משמע שיש לו סיבה באותו יום. גם היה אפשר לומר שאין סיבה לחייבו, אלא מחמת שהוא באותו עיר, בא בחיוב שלהם. דחוק. יהיה נפק"מ אם אין אחר בעיר. ותו"ת.
** הכתובה -
עיין ברש"י. קשה למה צריך זה, שאף בשלנו אפשר. אולי אומר שבשלנו אינו כל כך מחובר, וכשר. דחוק, שמחובר.
** תני קורא עמהן -
אם כן, אין חלק ממנו דיקא.
** משולשים -
יש לדון אם צריך כן לעולם, ואומר שאף שיש להקל, יחמיר קצת, או שאומר שרק בזה צריך כן.
* יט:
** מחט -
בכ"ז, יל"ד אם ר"ל עין של מחט, או נקב שעושה מחט.
** מחו לה -
נראה שלא חל’ בהלכה למשה, אלא לא ידע טעם, ואז חשב שמוכרח שהוא הלכה למשה. אבל, לא היה לו מסורה שהוא כן. יש לציין לירושלמי בתחילת פאה שאומר שיש כמה הלכות למשה שהם במשניות, ולכן יש לפסוק כמשנה, אף אם לא יודעים טעם.
** שהראהו -
עיין כעין זה בפאה גבי שני מינים ושני גרנות. שם, נראה שר"ל שהוא הלכה למשה מסיני ממש, ואז אינו דין זה. ויש לדון למה אינו הלכה למשה מסיני כאן. יש לומר שה’ לא אמר לו שטוב או שלא אמר לו לעשות, אלא אמר שכן יעשו.
** ודיעבד -
אין לומר שאולי פסול כיון שאינו בן דעת, שפשוט שזה יכול לדבר, וגמרא בתחילת חגיגה קורא לו בן דעת.
* כ.
** וכולן שעשו -
עיין ברש"י. זה מעניין.
** לאזניך -
ק"ק ל"ל יעכב. גם צריך ביאור למה מניחים שכל המצוות שווים.
** רבי מאיר היא -
נמצא, אז, שמסופקים אם משנה שלנו הוא רבי יוסי, רבי יהודה, או רבותיו של רבי יהודה.
** אין מביאים -
ואם תאמר מהו ההוה אמינא שנביא ראיה. ויש לומר שלא היה ה’ עושה ששום רע יבוא לו, ואם כן, צריך לומר שיצא. דוחה שאנוס הוא כיון שסבר כשיטתו.
- ק"ק שגמ’ בכתובות אומר שנאמן קטן על דינים דרבנן. אולי שם א"א שטעה (עיין שם), אבל כאן חוששים שטעה. ותחשב.
* כ:
** מנלן -
צריך ביאור מהו ההוה אמינא.
** יכפר עליכם -
יש לציין למש"כ גמ’ בכריתות ויומא שכפרה של יום הכיפורים קורה רק ביום.
** וסמך ושחט -
אולי היקש הוא, ואולי הוא שצריך להיות קרוב בזמן. הפסק לילה ויום מכריח רחוקם.
* כא.
** בגליון
כ’ ששייך למשנה לעיל. בכ"מ עושה כן רש"י. נראה שהיה מבלבל אם מפרש את המשנה ומחכה עד לגמרא. אז, פירש על גמרא. ויש לדון, שלא עושה כן בכל מקום.
** כרבי יוסי -
יש לדון למה צריך להיות כרבי יוסי, שאף לרבנן, יכול להיות כל היום, אלא שיש צורך אחר. זה אומר שאם מאחר סילוק, הוא בסוף היום, ואם מקדים, נמצא בתחילה, ויכול להיות כל הזמן בינתיים. עייןן ברש"ש יבמות כט. כעין זה.
** לא יברך -
עיין ברש"י. גם יש לומר שלא יכול לברך, והוא ברכה לבטלה.
** ואין מוסיפים -
ושבת במנחה- לכאורה, מוכיח שאכלו סע"ש אחר מנחה. אולי אין הכי נמי, כן עשו, אבל לא הצ’, אלא כך נהגו. גם יש לומר שרצו ללהתפלל מערב מיד וללין.
** יושב ושונה -
קשה ע’ לשון "ויושב ומלמד" גבי משה, וכן גבי למוד משה לאהרן.
- כ"נ, שאל"ה, אין גמ’ שלנו מפרש מה אומר.
** וישנה לתלמידו -
יש לציין למש"א דווד שעשה לכבד לרבו, שרבו ישב על גב כר וכסת ודוד ישב על גב קרקע (הוא בתחילת ברכות). אולי היה בקשים או כדומה, כמו בגמרא לקמן. יש לדון אם יהיה חי’ בין דין כד של רב לתל’. זה תלוי במש"כ לקמן.
** קרקע -
יש לדון אם זה אחר ר"ג או לפני ר"ג. ותחשב.
* כא:
** מנ"ח -
עיין ברש"י. גם יש לומר שמ"ם ר"ל מצוה, שהוא ברכת מצווה. עיין בדיבור הבא.
** לפניו -
ק"ק ל"ל אמר כן בשאר ברכות לפניו (שאינם ברכות המצוה). אולי משמע שהם כולם ברכות מצוה.
** כל המצות -
יש להעיר שלומ’ דברים מלאחר (עיין יומא ד: ומק"א).
** מברך עליהם עובר -
אולי מביא ראיה ממה שאומר שמברך עליהם או שלפניהם הוא ברכת המצווה.
** מי -
לשון "מי" מעניין (מניח שכנגד אדם הוא, ואינו נכון).
** אלא הא דתני -
יש לדון מה שייך "אלא,” שמשמע שלא היה מקשה בלי מש"כ לעיל. יש לומר שאז לא מוצא דבר דומה להיות תולה עלו עשר. ק"ק, שיוצא מגמרא שאצ"ל דומה, ואם כן, זהו הת’ (אצ"ל דומה), ורק זה הול"ל. גיK שאמר שכיון שהנחת שצ"ל כנגד דבר, מה זה כנגד.
** בראשון -
לכאורה, אז, יש סתירה. וצ"ב.
* כב.
** דאפשר בהכי -
כאן, אפשר לקרא עוד שבע קראי.
** לא שכיחי דמנחי ס"ת ונפקי -
יש לציין לגמרא ברכות.
** ואמצעי -
יש לדון אם ר"ל שהוא כופל ראשון או שני.
** שמואל -
ק"ק לל"א שלא היה שם. אולי היה מניח לכהנים אלא אם כן הוא היה הכי חשוב בעיר. ודחוק.
* כב:
** מיפק -
נ’ שהוא מפני שרב היה שם. גם יש לומר שהוא כ"כ רע, כמו שמפורש בתחילת ברכות.
** קמיה דרב -
צ"ב מה לנו בזה.
** לא משני -
ק"ק, שבין כך ובין כך שינה.
* כג.
** אין מוסיפים -
ל"ל:
1. אינו כנגד, עוד.
2. טירחא של צבור.
3. מונע מזמן לעונג שבת.
** מפני -
ממנינא- ר"ל, אז הם שווים- יש קורא זה ויש קורא זה. אבל כאן לא שווים, שאין מי שרק קורא נביאים.
** הני שלשה -
כבר פ’ שלשה. אולי ר"ל, “הני שלשה. חמשה ושבעה כנגד מי?”
** מפני כבוד צבור -
צריך ביאור למה אין בעיה של קול באשה ערווה. אולי נח’ כמו דיבור. ויש לדון.
** שיקרא בתורה תחילה -
לא הבנתי למה זה עושה שאינו מקיים בזה, שיהיה, אז, שני סיבות בקריאתו, ולמה זה בעיה. אולי הוא כעין עשיית מצוות חבילות חבילות. וצריך ביאור. גם אולי צריך להיות ניכר שיש שביעה. צ"ב.
* כג:
- כתבתי "2 דברים.”
** ואימא -
וכן ט- עוד יש לומר שאם נצרך כל המיעוטים, נמצא חמש ריבויים. ותו"ת.
** וחמשה ישראלים -
עיין בסנהדרין, שמביא זה בשם אמורא.
* כד.
** משום אינצויי -
עיין בביאור רש"י. קשה, שעדיין יחלקו מי ישיג מפטיר.
** על ידו -
יש לדון אם זוכים כיון שזכה או הפטיר. גמ’ נ’ כשני.
- נ’ שכ’: “יל"ד בנביא בעא ביותר מכרי."
** אביו או רבו -
יש לדון אם ר"ל שיכול לכבד אותם, או אם ר"ל שהם עוברים כיון שלמדו לו להפטיר, ואז הם במקומו. כמובן, יהיה נפמר אז אם רוצה בזה, אבל האחר למדו.
- קשה, שערטילאי ר"ל ערום (עיין בסוטה), ואז פחת צריך לומר יחף. לא נקרא כן לכרעיו נראים. ותחשב.
* כד:
** קטן - -
לא יראה בך
צריך ביאור למה זה רק איסור אם הוא ש"ץ.
** כהן שיש -
עיין ברש"י. קשה, שרק בזמן בית המקדש היה כן, כמו שכ’ בכגיגה טז..
** פניו -
צריך ביאור למה, שלא נראה.
** החיצונים -
אולי זה קצת פון, שהרי נתנם בחוץ. או שציפה בחוץ.
* כה.
** ורבה לחדודי -
נראה שרצה לזכותו לשתקו.
** ואינן אלא גזירת מלך -
זה מעניין.
כמו כן אומר בברכות.
** על הטובה -
מזכיר ברכות כדי שלא תאמר שהדמיון הוא שמברך אותו ברכה.
** המכנה -
אלא שכינה- מאלו מקומות, נראה כרש"י, אבל מלשון "מכנה" לא נראה כן. היה נראה לומר שר"ל מכנה שם, ובציורי רש"י הרי קרה להם בשם של אחר, שאומר למשל, אויבים של במקום בני ישראל. ותו"ת.
** ואינן אלא -
יש לדון אם אומר שאין סיבה או שגזר אותם כדי שנכוף, ונקט אלו שאף יש קצת סיבה.
** האל הגדול -
צריך ביאור למה אנו מוסיפים, ואומר, “קל אליון, גומל חסדים טובים….”
** ודלמא מעיקרא -
נראה שמקשה שאולי רק נראה כלא כוון. אז, ת’ שלא יהיה שלא יכוון.
** תני ר"י -
הו"א, לולי רש"י (מזה בא לאפוקי), שהם עצמם פ’, נגד משנה, כמה שדחה משנה.
** מעשה -
ראוי- כ’ רתוי בחגיגה.
** חברותא -
יש לדון אם אומר שלא יעשה כן, שאטו הוא כבר של ה’, או אומר שבני ישראל יחשבו שעושה חבר לה’, וחושב שיש שני רשויות.
* כה:
** דהויא להו כפרה -
כיון שעדיין יש עונש עליו, צריך כפרה. ק"ק, שחושב אני שיש גמרא שאומר שכבר כלה. חושב אני שיש גמרא שחולק, ואז יש לומר שאומר כחולק.
* כו.
** אבל מכר -
קשה למה צריך מקור שמעלים. גם יש לדון במקורות שאמר, שגמ’ במנחות הפכם. ותחשב.
** אבל מכרו שבעה -
לא הבנתי מהו הח’, שעדיין יהיה קדש.
** וכן במותריהם -
קדושתו פחותה- קצת צריך ביאור למה צריך להיות כן, שצ"ב מה עולה ויורד בק’, שאם הוא רק נכזיהם, הרי עולה, ולא יורד כלל. אולי לא כל כך קדש כמו שהיה, שפחות בדמים. וצ"ב. גם יש לומר שצריך  להיות כל דמיו דמים של דבר קדוש. ויש לדון למה פשוט שדמי ק’ גדולה יותר קדוש מק’ קטנה עצמה. ותחשב על זה.
** דאדעתא דידי -
לכאורה, ר"ל שרק באים כיון שאני מניחם לבוא. גם יש לומר שהיו באים כיון שאני דורש. ותו"ת.
** אקראי -
נראה שחול’ אם מה שמק’ אותם הוא מה שתשמשתו קדוש (ר"ל, עומד לדבר של ק’) או תשמיש קדש עצמו. ותחשב. עיין לקמן שאומר שצריך להתפלל בו. אולי עדיין יש לומר שצריך שניהם.
** לפיכך -
יש לדון מי אומר כן.
** דרבים -
יש לדון לל"א שבני עיר בעלים, ומניחים לאחרים לבוא.
* כו:
** תילא -
תל עולם- שדרכו של העצים ואבנים של הבית ליעשות תל.
** אי לאו דהוה ליה -
ק"ק שרש"י פי’ שזביני מותר כיון שיש דבר שעליו יחול הק’ק. כאן, אין דבר, שלכאורה, אין אותו הנאה נק’ (בכ"מ א"א, ועוד שלכאורה אין זה הדין).
** אסיר -
ואם תאמר הא הסיק שהוא תשמש, ולא תשמיש של תשמיש. ויש לומר שעדיין לא משמשו לזמן רב.
** קמ"ל -
יש לדון אם קמ"ל שאינו לשומרו או שאף לשמרו נחשב תשמיש ק’. גם יכול להיות קמ"ל, והוא ששמירה מעכברים הרי הוא גופא כבוד, שמכבד אותו במה ששמרו.
** וריקם -
לכאורה, לא רואים טלטול ריקם.
** כזביני -
קצת יש לחלק, שכאן אין מה לחול קדושה עליו.
* כז.
** כיון דלא מעלי -
צריך לח’ מהו סברה זו. אי אפשר לומר שרצה לומר שיש גנאי במכירה, ואפשר רק אם יש מעלה, שדן גמרא אף בלי מכירה. ותחשב.
** לא ימכור אדם ס"ת -
לכאורה, לא מביא זה לראיה על שאלת גמרא, שלא מוכיח כלום.
* כז:
** ברב עם -
צריך ביאור איך זה דוחה מה שאמר רבי מאיר. ותחשב. ר"ל, עדיין ק"ק למה יכול, שמוריד אותו. נראה שהענין הוא שרבי מאיר מניח שק’ החפץ לא בא (רק) מקדושת הגוף, אלא במה שיכול לגרום מצווה. רבנן יחלקו על יסוד זה. וצריך לחשוב.
** ברב עם -
משמע שזה מוסיף ק’. ותחשב.
** כי ברכתיך -
יש להעיר שאין כל כך טוב אם יענה כמו שנתקיים לו.
** ר"פ -
כמובן, ק"ק שידוע שבא ממעשה של תלמיד שחזר עמו ת’ פעמים. ויש לומר שכבר היה זקן או זה וזה גרמו לו. יש לדון למה יחשוב שאינו רק מחמת אותו מעשה. אולי הוא מפני שכבר בא לו שכר (עיין שם, שנקט שכר שכל דורו יכנס לעה"ב).
ודע שיש שני קושיות:
1. ל"ל אמר ר"פ כן.
2. למה שאל לו.
לשני, קל לומר שלא ידע. ראשון יותר קשה. אולי אמר להם מה שיעזור להם (שאף הם יעשו כן). זה מניח כמש"א שזו"ז גרם. יש לדון איך רבי פרידא ידע. אולי זקן היה לפני אותו מעשה, כת’ ראשון כתבנו, אבל עכשיו, אין צריך לומר שמעשה של כאן קרה לפני מעשה של ת’ פעמים.
* כח.
** מתנותיה -
נמצא שיש אף על מה שאינו מד"ח.
** בשוין -
יש לציין לגמרא לעיל גבי עליית רב בראשון.
** קלון -
אולי זה סימן, שלא עשה שקלון אחר יכבד אותו. ותחשב.
** שונא מתנות -
ק"ק ל"ל רק הביא קרא.
** עינוי כהות שנאמר
יל"ד אם מוסיף (כ"נ) או חולק.
** שותפות -
לכאורה, סבר שלא היו גויים, שבלי זה, אסור מדין אבוה דשמואל.
** בתוך ביתי -
נראה שר"ל וקל וחומר בחוץ.
* כח:
** בנות ישראל -
כן אמר כיון שהיו בדרך, ואין להטריח בדבר הלכה (“אל תרגזו בדרך"), וגמרא בברכות אומר שזה הלכה קלה לומר לפני תפלה.
- כתבי: “באמצע מס’".
* כט.
** להתפלל -
יש לדון אם אף התפלל. כמו כן, יש לדון אם זה אף אם נכנס ללמוד וכדומה.
* כט:
** טבי -
זה שם עבד ר"ג. אולי נתנו לו ר"ג שם יהודי. גם אפשר שהיה לו שם גוי, ונקרא בשם גוי. גם אפשר שנקרא אחר עבד ר"ג כיון שהיה כשר.
** דמסקי -
יש לדון איך מחלקים פרשיות.
** מאי הוי עלה -
שואל ושואל ודן ודן. ותו"ת.
* ל:
** ואיזו -
זטו- זה מ"מ.
** לסדר פרשיות -
יש לדון ל"ל חולקים בפירוש אם קוראים פרשיות רגילות באותם שבועות.
* לא.
** תנו רבנן -
עיין ברש"י. מעניין שגמרא יעשה כן למשה, ומעניין שמניח שכל ברייתא בא מא"י (שהיו תנאים בבבל).
** הבן -
נמצא ש"זכור אזכרנו" הוא דבר טוב. ראיתי במחזור שלי ש"זכור אזכרנו" (וכן כל הקרא עד "על כן המו…") הוא בלשון תמיה (אטו הוא בן שעשועים…). רש"י משמע דלא כזה.
** קוראים בעריות -
עיין ברש"י. יש לציין לגמרא ערכין שהכל נכשלים בעריות.
* לא:
** מנהני -
רש"י בא לפרש למה אי אפשר לומר שנלמד מסברה פשוטה.
** עצרת ר"ה -
קשה ל"ל קוראים בשאר ר"ה.
* לב.
** הגולל -
נראה שמניח שכשאדם גולל, מהפכו על ברכיו עד כדי שרחבו של תורה (המקום שיש שני עמודים) נמשך מפני שלו לחוץ. אם כן, צריך לגלל לצד פנים, ולא לצד חוץ. היה אפשר לומר שרחבו אינו כן, אלא הוא הוך, ואומר שיאחוז בעצים שבצד חוץ לגלל, ולא שבצד בפנים, שיאחז בהם , וירחיק ידיו מגופו (שכן צריך לעשות כדי לגללו), ואז ס"ת יפול. ותחשב.
גם כתבתי:
מסתברא- הרי מחלקת הוא (כז.)
משמע מגמרא (שרק שואל גבי ס"ת שאם אפשר להעלות, צריך להעלות.
אשה נמי- משמע שהיה הו"א להביא ראיה ממנו. ההוה אמינא קצת צריך ביאור, שאם כן נלמוד לכל מצות. צריך לומר שידע שהוא מצוה חשובה, אבל לא ידע שהוא כל כך חשובה. גם יש לומר שהניח שת"ת כנגד כולם, אבל כיון שידע שזה היה תכלית כל הבריאה, ידע שהוא יותר טוב. יש לדון מה גילה לו כן. אולי הענין הוא שתורה רק
טוב מפני שמביא לידי מעשה, אבל זה מביא לידי כל העולם, שבשביל זה נברא עולם. ויש לדון, שאין קיום שמביא. גם קשה למה לא פשוט כבר לגמרא שמביא כיון שבלי מצוה זה אין אדם נברא. ויש לדון, שזה קיום של אביו, ולא קיום שלו. ותו"ת.
- אינו רואה- האיש- ממנו או סתם
דמי מכירה.
למישתא (כו:) רשי
