* ב.
** סתומתאה -
וי"מ- לא רצה לומר שסתמות כמותו (שכתב "תלמידיו"), אלא שאף ברייתא וכדומה כמותו. קצת צריך ביאור למה יזכור גמרא את זה בענין בתם משנה כמותו. ותו"ת [fn:1].
** בזמן הזה -
דמקדימין- נמצא שר"י איתותב רק לשיטתו, שאם אין מתניתין ר"ע, יש לומר שלפני זמן הוא, ורבי עקיבה (משנה) כרבי יהודה.
* ג.
** דאינהו -
לא נשתלח- משמע שהיה לו נבואה, אבל לא היה נשלח.
* ג:
** תלמוד תורה דיחיד -
יש לדון אם למעשה מבטלים תלמוד תורה דרבים למגילה. מרש"י נראה שלא מבטלים. ויש לדון.
** את לא תעשה -
דכתיב- לא נראה כן מגמרא שם, אלא נראה שקאי על דינים דרבנן (והלאו הוא "לא תסור”). ועיין שם.
** שישב ולבסוף -
צריך ביאו למה אמור רק לענין זה, שלכאורה, הוא אף למגילה, שנלמד מיניה. אולי אומר דין שהוא אף לרבי יהושע. גם יש לומר שאמר דין הבא ממקור שהביא.
* ד.
** ולשנותה -
זכר- אף שאין קוראים ביום זעקתם, צריך לומר שיש שום שייכות. וכן רואים בחד פירוש של יום כניסה (רא”ש ?) שפירש שהוה יום שבו התפללו.[fn:2]
** סבור מינה -
בלשון הקודש- אם למדו באותו לשון, מעניין שעשו הש"ס בלשון אחר. ויש לומר שלמדו בלשון כעין ש"ס בבלי, שהוא בעיקר לשון הקודש עם שינויים מארמית. אם כן, אין לומר כן לירושלמי, ואולי שם לא למדו בלשון הקודש.
** למיתני -
משניות- ק"ק מה עשו קודם שהיה להם משנה. ויש לומר שהצריכו לחזור על ההלכות שידעו.
** יזמרך -
שמפרסמים- יש לציין לגמרא ערכין שאומר שיטה שקריאת הלל בפורים הוא גופא הלל שלו.
* טו.
** שיהרג הוא -
נ"א- לא הבנתי איך אפשר לומר כן, שהרי רואים שלא ביטל במיתת המן. ואולי טעה.
* כג:
** ואימא חמש -
עוד יש לומר שאם נצרף את כל המיעוטים, נמצא חמש ריבויים. ותו"ת.
* Footnotes
[fn:1] איני מבין כל כך מה היתה כוונתי כאן, אבל נראה שהוא מעניין, ואז יש לחשוב.
[fn:2] יש בזה שני ענינים:חידוש לומר שיש שום שייכות בין זעקה לקריאה, כיון שאין קוראים באותו יום. על זה, יש להביא סמך מאותו פשט.מעניין מה לנו שזעקו ביום, שלא על יום זה זעקו.
