פרק א
משנה א
לא תאכל- מבעוד יום-
אינו כל כך פשוט לי במה חולקים, אבל נראה שחולקים אם זה אוסר בדיעבד או רק לכתחילה. גם אפשר שסוברים שרק אסור אם הכין בידים, ולא אם התרנגולת הכין (ובפרט כיון שלא הכין בבחירה, אלא קרה ממילא בתוך גוף שלו. ויש לדון אם עושה שום דבר בבחירה.). ותחשב.
לא תאכל- מותרות-
צריך לעיין בסיכום שכתבתי על ביצה שנולד בי"ט, ששם בארנו שהיתר זה נמצא בבריי', אבל גמ' רק מבאר היתר זה לפי רבה. לכאו', לפי רב נחמן, לא מובן למה יהיה היתר, שאף שאינו מצוי, כיון שטעם האיסור שייך בו, לא יהיה מותר. עוד בארנו שלפי ר"י ור"י, יש לדון אם טעם הגזי' שייך בו. ותחשב. על כל פנים, אולי היתר זה הוא רק לרבה, ושאר השיטות סוברות שהבריי' ב"ש הוא. (ויש להעיר שגמ' (ג.) מבאר למה השיטות לא סוברות זו כזו. היה אפשר לומר שרבה לא סובר כשיטה אחרת מחמת בריי' זה, שלא רוצה שיהיה סתם בריי' כבית שמאי. אבל, גמ' רצה לתת טעם לכולם- למה כולם חלקו על רב יוסף ולמה כולם חלקו על רב יצחק- וזה רק מספיק לרבה. לכן, לא מזכיר טעם זה. ותו"ת.
בכותבת- בענין השיעור-
ואם תאמר מהי"ת ששיעור של חמץ הוא בכותבת, ולא בד"א. רש"י תי' שמסתבר שהוא שיעור כותבת, כיון שהוא שיעור של יישוב הדעת (לכן הוא השיעור גבי אכילת יוה"כ). יש לדון אם יש סיבה לחשוב ששיעורו ייתלה ביישוב הדעת או רק שזה השיעור הכי קטן, לאחר כזית, שמצאנו בו חשיבות. (עיין במה שכתבנו בזה בשי"ח ש"י.) רש"י גם תי' שהל"מ הוא. ואם תאמר הרי בית שמאי מוכיחים כן מקרא. צריך לומר שבית הלל לא היה מודה למסורה של בית שמאי, ולכן הוצרך בית שמאי להביא קרא להוכיח שאין בית הלל נכון, ואין שיעור שלהם שווה. ואם תאמר למה צריך שקרא יזכיר שאור, אחרי שיש הל"מ. ויש לומר שלא רצה ה' לומר האיסור בתוך הל"מ, אלא רק השיעור. יותר מזה, יש להוסיף שיש חילוקים בין איסור שנאמר בהל"מ לאיסור שנאמר בקרא (יש שכ' שלא עונשים על איסור שנאמר בתוך הל"מ).
יש להעיר שלא פשוט מהי"ת ששיעור שאור (ושיעור חמץ לב"ה) הוא בכזית. כמובן, אם נאמר ששיעורים הל"מ, אינו קשה. אבל, אם נאמר כצד ראשון, שלכאו' לא רצה לומר כן מפני ההערה שכתבנו, צריך ביאור. (עדיין אפשר ששיעור שאור הוא הל"מ, אבל שיעור חמץ בלי הוכחת קרא לב"ש, ולמסקנא לב"ה, קשה.) עיין בטעם של בית הלל, שיוצא שיש תלייה באכילה. (רש"י בפסחים משמע שאיסור בל יראה ובל ימצא הוא רק סייג לאיסור אכילה. (יש להעיר שהיה אפשר לומר שזה רק הו"א. אבל, למסקנא, ששניהם נאסרו, אינו כן.) לולי זה, היה אפשר לפרש שחמץ אינו רק "עיסה שנחמצה," אלא "עיסה שנחמצה וראוי לאכילה." לכן, השיעור שלו הוא שיעור של אכילה, שהוא כזית.) אבל, יש להעיר, זה רק שיטת בית הלל, ובית שמאי לא מודה לזה. צריך לומר שאף ב"ש מודה לזה במקצת, וצ"ב. ותחשב.
משנה ב:
בית שמאי אומרים יחפור בדקר ויכסה- עיין בהשלמות-
גמ' במקומו (ז:) לא מבאר למה בית שמאי מקילים. נבאר את הסוגיה, ואז, אולי, יבוא לנו בהירות על זה. לכאו', יש עשה שאומר לו לשחוט (שמחת יו"ט). גם יש עשה שאומר לו לכסות, אחרי ששחט. יש לאו שאומר לו שלא לכסות, והוא איסור יו"ט. אפשר להיות שב"ש סובר שאומרים שעשה דוחה לאו. לכן שוחט, ולכן מכסה. אבל, ע' בפסחים (פד.) וכן בשבת (כד., קלג.), ששם חולקים אמוראים אם יו"ט הוא רק לאו או עשה ולאו. צריך לומר או שבית שמאי סובר שלאו הוא, או שבית שמאי סובר שכיון שבין הכל מקיים שני עשיים  (שמחת יו"ט וכיסוי) ועובר על לאו ועשה, נדחה הלאו ועשה. (יש להעיר שלא מקיים שמחה, לכאו', עד שיאכל. אז, אינו דוחה בעידנא שמקיים אותו. גם, לכאו', יש דרכים אחרים לקיים מצוות שמחת יו"ט באופן שאין עליו חיוב. ותחשב.)
אבל, לקמן (ט.) אולי יוצא ביאור בשיטת בית שמאי. שם, גמ' מקשה מה שמצאנו כאן שבית שמאי מיקל מפני שמחת יו"ט ומה שמצאנו במק"א שלא מיקל מחמת שמחת יו"ט. דוחה שאולי רק כאן מיקל כיון שיש דקר נעוץ. עיין שם, שאולי רבי יוחנן לא מודה לזה[fn:1]. כן יוצא, לכאו', מגמ' (ח:), אבל יש להעיר שמניח כרב אשי. גם אפשר שזה רק בבית הלל שם. וצריך לעיין.
אם נניח כפשטות הגמ' (ולא כמה שאולי רבי יוחנן אומר, ולא נהפך שום משנה) נמצא לנו ביאור בדברי בית שמאי. נמצא שהוא שווה למה שאומר גמ' בביאור קטע של המשנה לקמן (גבי "מודים שאם שחט"), שהוא טוב, כיון שמשתמש באותו לשון. אז, הפשט של המשנה יבואר לקמן, בתוך שי"ח ש"ח על המשניות, על "מודים שאם שחט."
ראיתי שכן מפרש הרמב"ם בפירושו על המשנה, וכ"פ הרע"ב.
ומודים שאם שחט שיחפור בדקר ויכסה- ואין חשש מוקצה-
לא כל כך פשוט למה מוקצה הוא כל כך חמור, עד שרק מתירים גזירת בית הלל (שאוסר בדרך כלל), ולא מוקצה. אולי הוא מפני שיש שני איסורים דרבנן או אולי הוא מפני חומרת איסור מוקצה. עיין לקמן (כד.) שיש שסוברים שספק מוקצה לחומרא. אז, מצאנו חומר מיוחד לו.
ומודים שאם שחט שיחפור בדקר ויכסה- ואין חשש מוקצה-
יש להעיר שאם בית שמאי סוברים שצריך זה כששוחט לכתחילה, לכאו' עדיין יסבור שלא צריכים שיהיה דקר נעוץ לפי רב נחמן, כיון שלפי רב נחמן, אינו חושש למוקצה. אז, צריך לומר שמה שאומר גמ' לקמן שבית שמאי מיקל כיון שיש דקר נעוץ אינו לפי רב נחמן (אבל, לפי רב נחמן הוא אמת במה שמיקל כיון שלא כותש ומפני שסובר שאין מוקצה).
יש להעיר שאם בית שמאי מדבר בציור שיש דקר נעוץ, ואז יש עפר מוכן, מה שאומר בית הלל שצריך שיהיה עפר מוכן אינו רצה לומר שצריך שיהיה מוכן מדין מוקצה, אלא שצריך להיות מוכן בהכנות שיעשו שאין איסור אחר בו. ותחשב.
מוכן הוא- ולא לספק-
נמצא שמה שהיה מוכן לדבר אחד אין משתמשים בו לדבר אחר בשבת.
משנה ג:
הקדמה- אסור להוליך אותו-
לכאו', זה רק ברשות הרבים. אבל, ברשות היחיד, נראה שיש צד להקיל, שלא יהיה חלוק משאר מראית עינים של רשות היחיד. אז, אולי דין שלו שווה לשל משנה שלנו (ומי שלא אומר כן בגמ' סובר שב"ה מיקל גם ברה"ר).
הקדמה- אסור להוליך אותו-
זה לא ברור לי. כן אומר גמ' בפירוש (ט:), אבל שם קאי על בריי' שחולק על משנה שלנו בביאור ציור של מחלקת בית שמאי ובית הלל. אז, יש לומר שרק שם אמר דין זה, אבל לא כאן. ותחשב. (ודע שאם נאמר כן, צריך לומר שבני רב חייא, שהקילו על פי אותו משנה, ורק טעו במה ששל עלייה אסור, פסקו כאותו בריי' נגד משנה שלנו. זה לא כל כך נראה, ואז יותר נראה לומר שסולם של עלייה אסור בכל אלו.) אבל, נראה שהוא כן, כיון שדייק כן מאותו בריי', ואותו דיוק נמצא גם במשנה שלנו.
ובית הלל מתירים- רבי דוסא-
לא פשוט אם רבי דוסא סובר כן בציור של משנה שלנו, שמעורר כן על בריי' שמפרש שיטת ב"ה וב"ש באופן אחרת. אז, יש לומר שרק על אותו משנה מדבר. ותחשב.
מתירים- משום שמחת יו"ט-
מזה יוצא שיש ענין של שמחת יו"ט במה שעושה בתוך השובך. כן יוצא מן ההו"א של גמ' לקמן (שרוצה לתלות את מחלקת בית שמאי ובית הלל בדיון על שמחת יו"ט). לכאו', סובר שהולך לשם כדי להביא ביצים ויונות ליו"ט. ותחשב.
משנה ד:
מותרים- עיין בהוספות-
גמ' מביא מחלקת בין רבי ורבנן במאתים ומצא מנה, שרבי מניח שהמנה בא מן המאתים ורבנן לא מניחים כן. חולקים אמוראים באיזה ציור חולקים- כששני המנים הם בכיס אחד או בשני כיסים.
אם נאמר שהם בשני כיסים, אז היה נראה לומר שמשנה שלנו הוא שיטת רבי. גמ' דוחה שרבנן מודים בעופות כיון שהולכים בפני עצמם. לפי צד זה, לא יודעים מה הדין אם העופות קשורות, אם יהיה אסור לדה"כ, אם יהיה מותר לדה"כ, או אם רק יהיה מותר לרבי.
אם נאמר שהם בכיס אחד, גמ' מפרש אינו ממש כיס אחד, אלא שני כיסים שמקושרים זה לזה. באמת, נוכל לומר שמשנה שלנו הוא כדברי הכל. גמ' מוסיף שאף אם משנה מדבר בעופות המקושרים זה לזה, יכול להיות כשיטת רבנן, כיון שעופות מהלכים ויוצאים מן הקשר בפני עצמם.
מתירים אף להחזיר- אסור להחזיר אותם-
גמ' מזכיר כל זה מיד אחרי שהזכיר תנא שמשנה את מחלקת בית שמאי ובית הלל. אז, אפשר לדון אם כל זה הוא רק לשיטתו. אף אם לא נאמר כן (ולא נראה לומר שמחמיר, על כל פנים), יש לדון אם אסור גם לסלק.
משנה ו:
שהורמו מהיום- עם דברים מותרים-
גמ' אומר מחלקת זה אם מוליך עם מתנות שנשחטו מהים. יש לדון אם הוא גם בדברים אחרים מותרים. אפשר לומר שרק בכעין זה מתיר רבי יהודה, כיון שזה מוכיח לחילוק שיש בין תרומה למתנות, שמתנות נתחייבו בו ביום. לאידך גיסא, י"ל שבדברים מותרים אחרים שאין בהם אף קצת סיבה לגזור, אחרים יודה לרבי יהודה. ותחשב.
משנה ו:
משלחים אותו- בהוספות-
איני מבין זה כל כך. נמצא כאן הגדרה חלוקה ממה שהנחנו לעיל. לפי זה, קשה דין סנדל המסומר. רש"י כ' שהוא מפני גזי' שמא ילבש אותו. לכאו', אז, גמ' משנה ממש"א לעיל, ומחלקת הוא. אבל, עדיין צריך ביאור למה אין גוזרים כן בכל דבר שאסור בי"ט. ותחשב. אולי הוא מפני שקשה לזכור גזירת סנדל המסומר, שאין בו כל כך טעם. גם צריך ביאור מהו הסיבה לדין זה, לפי בית הלל. ותחשב. כיון שאנו לא מבינים הגדרה זו כל כך, מניחים את הכל עם הגדרה של החולק, ורק מזכירים השיטה כאן.
בין שהורמו מהיום- יבוא להוליך תרומה-
לכאו', חושש שיבוא להוליך תרומה, ואז יבוא להרים תרומה.
את המתנות- עיין בהוספות-
פרשנו לעיל (על פי רש"י עה"מ) שב"ש גוזרים שמא ירים תרומה. קשה, שאומרים טעם אחר כאן. אולי צריך לפרש שר"ל שאחרים יאמרו שתרומה ומתנות שווים, ואז ישוו את דינם, ויתירו אם לא מחמירים. דחוק.
לא זכאי בהרמתה- יש פעמים-
יש לדון אם באותם פעמים מותר להוליך אותם.
דינים היוצאים מן המשנה- כולי עלאמ לפי רבי יהודה ואחרים-
יש לדון אם מותר, לפי רבי יהודה, עם מתנות שהורמו מבהמה שנשחטה בי"ט.
משנה ז:
עץ הפרור- כף גדול-
לכאו', הענין הוא שהוא חתיכת עץ שלא עשוי (ועוד, אולי אינו כל כך טוב) להיות מדוך. אולי חלק מן הענין הוא שהוא מיוחד לדבר אחר. ותו"ת.
בית שמאי- שיטה אחרת-
כמעט בכל משנה כאן יש שיטה אחרת בביאורו) כמו כן מצאנו שבתמיד גמ' תמיד מביא לשון אחר (אבל זה בתוך הגמ' עצמו).
משנה ח:
בורר כדרכו- אם יותר קל-
לא פשוט למה; אולי לא התירו רבנן בלי צורך, ואין זה צורך, או אולי יש בזה איסור טירחא.
משנה ט:
הקדמה- יש צורך י"ט-
לכאו', אז הדמיון לחול נדחה. גי"ל שאז אין דמיון לחול.
פרק ב
משנה א
כל שהוא- כזית-
ע' בגמ' בב"ב, שמוכיח שדבר הוא כל שהוא ממה שאומר "כל שהוא." נמצא שמניחים ש"כל שהוא" הוא ממש, ולא כזית. אולי יש לחלק שכזית הוא הכי מועט לדברים אחרים, ואז יכול להיות נקרא "כל שהוא" לאותם דברים. במילים אחרים, מילת "כל שהוא" אומר "כל שהוא דבר אחד." בדרך כלל, פשוט שרצה לומר, "כל שהוא בעולם." אבל, יכול להיות משמע גם "כל שהוא קצת חשוב," והרי יש חשיבות שיש רק למה שהוא כזית. ותחשב על זה. (לא מוכרח שזהו כוונת "כל שהוא," אלא יכול להיות שרצה לומר שמהנה, כל שהוא- דהיינו שהדבר מהנה, בכל מצב שהוא, בין אם הוא גדול בין אם הוא קטן. ותחשב. אף שהמילה משתמשת שלא ככה, אלא אומרים שרק צריך כל שהוא, אולי המילה גדלה מתשמיש הראשון שלה. ותו"ת.
אכלו או שאבד צריך לשנות את שניהם-
אולי יש לחלק לומר שהו"א שאינו כן אם נאכל, שעשוי להיאכל. תחשב מה לנו בזה.
משנה ב:
הקדמה- לא שייך בטבילת בני אדם-
בוודאי הדין כן, אבל יש לדון למה זה פשוט, שאולי נחוש שיביא טאוו"ל עמו.
הקדמה- לא שייך-
בוודאי הדין כן, אבל יש לדון למה זה פשוט, שנחוש שיסחוט את שערו.
הקדמה- לא שייך-
בוודאי הדין כן, אבל יש לדון למה זה פשוט, שנחוש שישהה טהרתו.
הקדמה- בין השמשות-
יש לדון למה. אולי זה כשיטת רבי, שאוסר כל שבות ביה"ש. וא"ת א"כ למה אמרו. וי"ל שכיוון להתיר כל שאר ימים, נגד שיטת רבי שמעון.
מלפני- את האדם-
לכאו', איסור אדם צריך להיות כטעם רביעי שכתבנו, ולא נראה כמיקר. גי"ל שאדם אסור גזי' אטו כלי.
משנה ג:
לא מטבילים - לטהר-
יש לדון אם רק נאסר אם מכוון לטהר את הכלי.
אבל לא מטבילים- מביא חולק-
גמ' מביא בריי' שבו רבי אוסר בשניהם, ורבנן מתירים בשניהם. גמ' מקשה מזה על המשנה. שם, נותנים שני תי'. תי' הראשון הוא שמשנה שלנו כרבי, שאוסר בשניהם, אבל משנה שלנו בי"ט, שהוא יותר קל (לא פשוט לי למה י"ט יותר קל. י"ל שהגעת מים הוא אוכל נפש.). אז, דין מטבילים כלי הוא גם בי"ט, אבל דין השקה של בריי' הוא רק בשבת. תי' שני הוא שמשנה שלנו בשבת, שהוא יותר חמור, והוא כשיטת רבנן. אז, דין השקה של בריי' הוא בשבת, ודין מטבילים הוא בי"ט, כלעיל. ותו"ת.)
חבורה לחבורה- שבת-
יש לדון אם, באמת, מותר בשבת. אם רישא דבר בשבת (עיין לעיל), מסתבר לומר שאף זה מדבר בשבת. אם לא, יש לדון אם דין זה נכון גם בשבת. לא נראה שנתיר רק בי"ט, כיון שאין צורך בו, ולא יהיה י"ט יותר קל. ותחשב. ויש לדון, שאולי הוא בחר שלא להשתמש עד שטובל, ואז יש צורך שיטבול.
חבורה לחבורה- שאין צורך-
ואם תאמר למה אין סיבה ראשונה ושניה שייכים. וי"ל שזה לא מצוי.
משנה ד:
הקדמה- לכם-
גם מצאנו שדורשים את זה ממש"כ, "וחגותם," שמשמע שרק חגיגה מותר. נראה שצריך לומר ששם לא מכוון לומר ש"חגותם" משמע שאין לעולה דין זה, אלא שבא לומר ש"וחגותם" לא משמע שיש לעולה דין זה, וממילא הוא בכלל המיעוט של "לכם."
הקדמה- קבוע זמנו-
לכאו', לכן מוסיפים אותו לדרשת "לה', ואינו מן הנתמעטים מ"לכם."
הקמה- נדרים ונדבות-
במקצת מקומות בית הלל רק מתיר שלמים של נדרים ונדבות, שאוכל בי"ט, אבל לא עולות של נדרים ונדבות. אבל, יש מקומות שלא מוכרח כן; מדרשה שלהם מ"לה'," היה נראה שאף עולה מתירים. וצריך לעיין.
הקמה- משלחן גבוה-
לא פשוט איך זה מתרץ, שעדיין הוא לצורך שלו, שעדיין הוא אוכל אותו בי"ט ושמח.
אין סומכים- אין חיוב סמיכה-
יש להעיר שאם ב"ש אומרים שאין שום חיוב לסמוך, היה אפשר לומר שרק מזכיר חיוב סמיכה אגב, ואף ב"ה לא אומרים שצריך לעשות כן בי"ט. דחוק, שאינו שייך בכלל לשמנה שלנו אז. ותחשב.
משנה ה:
ראויים לשתיה- מתוך
רואים בזה שבית שמאי מודים קצת לענין מתוך. נמצא שמתוך שראוי הוא לאוכל נפש, יכולים לעשות בו מלאכה לסיבות אחרות. אבל, יש להעיר שאם אומרים הואיל, יכול להיות שזה מותר מחמת הואיל. אבל, ע' בתוס', שכ' שלב"ש צריך לשתות ממנו.
כל גופו- דומה לאוכל נפש-
לא פשוט לי למה זה דומה לאוכל נפש. הרי, אין אוכל נפש הנאה לכל גופו. הוא הנאה לפיו, ולאחר זמן גם למעיו. ויש לדון. גם זה אינו הנאה לכל גופו, שאינו הנאה לפיו ואינו הנאה למעיו. באמת, שניהם הם בדיוק הפוכים.
משנה ו:
טומנים- בכלל כדי חייו-
לא מוכרח שזהו המחלקת, שאולי חולקים אם מותר כדי חייו או לא. אבל, היה נראה, אז, שיזכיר בישול עצמו. ויש לדון, שאולי רבן גמליאל אומר שהוא אף מחמיר על הדרבנן של הטמנה.
טומנים- אם מהני-
הייתי אומר שכמו שלא צריך להיות מבשל דבר, אלא צריך להיות שנתבשל, כך לא צריך שיהיה דבר טמון אז, אלא שיהיה לו דבר שהיה, לפני כן, טמון.
מנורה- חתיכות-
קשה מפ’ גמ’ על משנה שלעיל (גבי תריסיים), שפי’ ששניהם סוברים שיש בנין. גם צריך לע’ בשבת (מו.) ששם אומר ששל חוליות הוא אסור. אבל, שם אומר שמנורה שנראה כשל חוליות הוא, לפעמים מותר, והור כשהוא קטן, ואף שם מחלקת אמוראים הוא. אולי כיון שר"ג סובר כב"ש, אף סתם הגמ’ שם מניח כב"ש. כמובן, לא נראה כן מסוף המשנה שלנו. ותחשב. אולי, להיפך, רק על אותו דבר אחד נאמר, למעט שאר חלקי המשנה. ושו"ר בתוס’ כאן. זה מחודש, ראשון שאז צריך לומר שהוא איסור דרבנן, ושני מפני שלכאו’ אין סיבה לרבנן להקל באיסור זה בי"ט. ותחשב. אבל, תי’ שני שלו אינו כל כך מחודש. אבל, דע שהוא קצת קשה מאותו סוגיה, למה לא מפרשים שהוא באותו מין מנורה. וי"ל שלא רוצים שמח’ אמוראים יהיה מח’ זה של ב"ש וב"ה. ויל"ד מהי"ת שלא לפ’ מחלקת שלנו בנ’ כפרקים. ותחשב. אולי יותר מסתבר להקל בזה, ויותר מסתבר שיחלקו אמוראים ושנחמיר שם. ותחשב.
עבה- הרבה לחם-
יש לדון אם צריך כן לי"ט או לא. יש להעיר שאם לא צריך כן לי"ט, תלוי כבר במחלקת אמוראים אם אומרים "הואיל.” ויש לדון, שאולי לא צריכים, אבל אם עושים יאכל. גם יש לומר שהוא מותר לפי שיטת ר"ש, שיכולים למלא תנור, כיון שזה משנה איך נתבשל. אפשר שהוא גם אם לצורך י"ט הוא, שב"ש סוברים שגם לצורך י"ט לא מותר לטרוח כל כך. וצריך לע’ ברש"י ותוס’ כאן, שחול’ בפירוש שלהם, ודנים בענינים אלו.
עבה- הרבה-
לא כל כך פשוט לי שזהו מה שאומר משנה. הרי, לשון "רקיקים" לא משמע כן. גמ’, באמת, אומר כן על ביאור בריי’ אחר, שמביא על המשנה, שגמ’ מסיק ש"עבה" שם רצה לומר "מרובה.” אולי צריך לומר גם במשנה שלנו כן. וע’ בלשון סוף המשנה. אם רק רצה לומר "הרבה לחם," צריך ביאור למה אומר שלש הלשונות. ותחשב. צריך ביאור למה לא מפרש גמ’ הלשון בפירוש. וצריך לע’ ברש"י ותוס’ כאן, שחול’ בפירוש שלהם, ודנים בענינים אלו.
משנה ז:
מוגמר- מח' בין ר"ג לרבנן-
גמ’ לא מפרש למה רבנן חולקים. נראה שסוברים שאינו שווה בכל. אין זה מוכרח; י”ל שגזי’ מחמת מין ראשון הוא.
בלילי פסח- גדי של ק"פ-
לכאו’ הנהיג כן לזכר לקרבן פסח. ויש לדון אם הנהיג שיעשו כן או רק הנהיג שאין בעיה בזה.
משנה ח:
פרתו- שלא מוציא דבר-
איני יודע מהו הגדר של דין זה, שלכאו’ לא חייב לבדוק את שורו קודם שיוצא, לראות אם יש עליו כלום. ויש לדון.
פרתו- לכוון-
יש לדון אם זה נכון, שרק מצאנו שזה יהני כאן. אבל, אולי לפעמים אף לא צריך לכוון כך. ותחשב.
משנה י:
עגלה- לשחוק-
ע’ בק’ תוס’. נראה שרש"י מפרש שוהא יושב שם לשחוק, כיון שרש"י סובר שההו"א הוא שאין ישיבה לשחוק (או אין ייחוד ישיבה לשחוק) נחשב ישיבה. ותחשב.
תלמים- שיעשה תלמים-
יש לדון אם רבנן סוברים שעושה תלמים או שגוזרים מחמת שאר כלים. נראה כצד שני, ואז יהיו לשיטתם. אבל, ע’ ברש"י, שכ’ בפירוש כצד ראשון.
פרק שלישי:
משנה א:
אין נותנים לפניהם מזונות- לכם-
נמצא מרש"י שרק מלאכות אסורים לעשות להם, שרק אלו נתמעטו מ"לכם.” אבל, אין סיבה לאסור לתת לפניהם מזונות. לשון משנה לא משמע כן, שרק מדבר על נתינת ממון לפניהם. אז, היה יותר נראה לומר כתוס’, והוא שאסור לתת להם מזונות שמא יבוא לצוד אותם. אבל, דע שזה קצת חידוש, שעל כל פנים בדגים, קל לתת להם מזונות אף בלי לראות אותם. ויש לדון. אולי רש"י סובר שאסור אף לתת להם מזון, גזירה שמא יתן להם מזון מוכן. אולי גוזרים שכיון שהם שווים, יחשב שכמו שזה מותר, כך זה מותר; או אולי, כעין תוס’, כיון שנותן להם מזון שיש לו, ימלא עליו תאוותו להכין להם מזון.
ביברים- ביבר קטן-
באמת, גמ’ תחילה אומר שחולקים רבי יהודה ורבנן בזה, ושוב אומר שרק מותר בביבר קטן. יש לדון, אז, לפי מי הוא המשנה, אם הוא לפי רבי יהודה או לפי רבנן. אפשר לומר שרצה לומר שמותר ממין ביבר, ולרבי יהודה הוא בקטן, ולרבנן הוא רק בגדול. אבל, יותר נראה לומר שביבר רצה לומר קטן, והוא כרבנן.
ביברים- מגיע צל-
צריך ביאור, שזה תלוי גם כמה גבוה הם המחיצות. וי"ל שהיה גובה סתם של ביברים. גם אפשר שהצל הוא סיבה, שלא רץ כיון שהוא רגיל לשבת תמיד בתוך צל. דחוק, שהוא אף אם רק הובא שם אתמול. גם אפשר שהוא מפני שבשעת צידה יושב בתוך צל. אבל, אם כן, יהיה מותר רק אם יש צל באותו שעה. ותחשב.
ביברים- במילים אחרים-
לקמן, יאמר גמ’ שזה לא חולק על ר"ש, והרי ר"ש אומר שהוא כל זמן שלא אומרים להביא מצודה. (אפשר שאין זה רבי שמעון, אלא כלל של המשנה, ואז בוודאי לא חולקים.) אז, קשה למה צריכים גדר זה. נראה שגמ’ שם לא בא לבאר את הגדר, אלא לבאר את המילים, מה הם המילים "מחוסר צידה.” דחוק. גם אפשר שקשה לו שאם בא לדון מה נחשב צידה, אי אפשר לומר שצידה הוא על דבר שצריך צידה. לזה, אומר שכשאומרים "צריך צידה,” לא מניחים כבר מהו צידה, אלא אותו צידה רצה לומר שבני אדם אומרים לצוד אותו. ותחשב. על כל פנים, אז יש לומר שאין אותו גדר כ"כ טוב, וגמ’ מוסיף גדר אחר. אבל, אם לא נאמר כן, זה גדר שגמ’ אומר, וצריך ביאור למה לפעמים אומר גדר זה ולמה גדר זה. וי"ל שזה הגדר הכי טוב בכלל, וזה הגדר הכי טוב בביברים (שהוא יותר טוב איפה שנוגע, אבל הוא נוגע רק בביברים). ועיין שם בגמ’ עם דיון על אווזים, שאולי זה מוכיח שאינו גדר כל כך טוב (או שאולי מחמת זה גמ’ משנה תי’ שלו, ואז אין מה שכתבנו נכון. וצל"ע.)
מזונות- רק בימי החורף-
לפי תוס’, לכאו’ יהיה נוהג תמיד, שמותר לצוד אותם.
רשב"ג- לא חולקים-
כן אומר אביי, ולא נראה שרבה חולק על זה, שרק משיב שאף שאין חולקים, אינו רע להגיד כי הלכה כן. ויש לדון, שאפשר לפרש השקלא וטריא ביניהם להיות שרבה אומר שהלכה הוא כן, ואביי מקשה משמע שרבנן חולקים, ואז, סובר אביי, לא יהיה הדין נכון. אלא, הדין נכון מחמת סיבה אחרת. השיב לו רבה מה לנו לחלוק מה יהיה הלכה אם נאמר שרבנן חולקים, שאני סובר שחולקים והלכה כרבי שמעון ואתה סובר שלא חולקים, ואז בוודאי הלכה כרבי שמעון. אביי משיב שיש לחלוק, שיש נפקא מינא איך לומר את הדין.ותחשב. כן קצת נראה, שגמ’ מדייק בכמה מקומות ממה שפוסקים הלכה שיש מחלקת, והיינו צריכים לומר שרבה חולק על כל הדיוקים.
דינים היוצאים מן המשנה- ביברים בהמה גדולים-
איני יודע אם זה נכון, אבל כיון שנאמר עם חיה, כן נראה. ויש לדון.
משנה ב:
מצודות- לא צ' הזמנה-
נמצא שאף שלא קל לקחת אותם כיון שכבר יש לו מצודות שם ויודע בהם נחשבים מזומנים. זה נראה חידוש לי.
ר"ג- ספק-
יש לדון אם לא הגיד לרבן גמליאל או שלא נאמן. בדרך כלל, לא מצאנו נאמנות לגוי, אלא כפי תומו, ואף שם, רק כשיש צורך, כמו לעדות אשה. אבל, זה רק איסור דרבנן, ואולי הקילו יותר. ותחשב.
מותרים- בטלטול-
יותר מכך, יכולים לקחת אותם, ואף שזה קצת הנאה, שקבלתם עכשיו עושה שיכולים לאכול אותם לאחר זמן.
משנה ג:
כזית- כזית-
איני יודע למה צריכים אכילת כזית, שלכאו’ נאמר שמתוך שהורת לצורך אכילה הותרה נמי לצורך אותו הנאה של אכילה פחות מכזית. צריך לומר שהנאה זו לא גדולה כל כך, ולא הותר לו. ותחשב.
כזית- שלא רוצה-
נמצא שאף אוכל שלא רוצה לאכול כל כך, ואז ממילא צריך לומר שאין בו כל כך הנאה, הוא מותר. ותחשב.
חי- שלא יפסיד-
קל לומר כן, כביאור שכתבנו לעיל מגמ’ בפסחים לצד שאין אומרים הואיל. אבל, נראה שמוכרח שלא צריכים כן, שהרי גמ’ בפסחים לא מקשה "לטעמיך.” (יש לדון על פי מש"כ תוס’ בכ"מ שמצוי שלא יקשה גמ’ "לטעמיך" אף שיכול להקשות. אז, צריך לומר שר"ע אומר שכיוןן שיש אפשרות לאכול כך, אף שלא מסתבר כלל שיקרה, אומרים הואיל. יש לציין לתוס’ שמקשה למה לא אומרים הואיל על כל דבר, כיון שהוא מותר אם יש חולה שיש בו סכנה. תי’ שלא מצוי. צריך לומר שזה יותר מצוי. (גם יש לומר שמצרפים הספקות כאן.) ותחשב על כל זה.
במוט- אוושא מילתא-
מושג של אוושא מילתא לא כל כך פשוט לי. הענין הוא, כנראה, שמכריז מלאכה, אף שנעשה בהיתר. כמו כן מצאנו בריחיים שמשמיעים קול בשבת. איני מבין הבעיה כל כך. אולי רצה לומר שאם הרבה בני אדם רואים אותו, יהיו בנ"א שיחשבו שמלאכה נעשה. ותחשב. וגם צריך לע’ ברש"י בע”ב, ששם מביא על זה גמ’ כמה דינים אחרים, ורש"י מבאר שהם אסורים כיון שהם דרך חול. איני מבין כל כך למה הם דרך חול, אבל על כל פנים רואים יחס בין שני בעיות אלו. וצריך לחשוב על זה.
משנה ד:
יעלה וישחוט- מה שכתבנו למטה-
זה אחד מפירושים של רש"י. איני מבין אותו כל כך, שאיני מבין מה לנו במום עראי, כיון שלא שוחטים עליו, ואז עדיין יהיה מוקצה. אולי מדבר במין של מום עראי שעשוי להיות קבוע. ותחשב. פירוש אחר של רש"י הוא שלא ישחט אותו מחמת דין מוקצה, כקושיה שלנו. אבל, אז איני יודע למה דנים בבור כלל, וכקושיית גמ’. ותחשב.
מן המוכן- דיינים יושבים-
יש לדון אם זה גם למסקנא, שאפשר לומר שכיון שלמס’ אם ביד בני אדם לגמרו, מותר הוא, גם זה מותר, כיון שהוא בידו. ויש לדון, שכיון שצריך חכם להתיר אותו, אולי לא נחשב בידו, מה שאין כן בבישול (זהו ציור של הגמ’ שיש בו היתר של בידו) שאפשר ע"י כל אדם.
דינים היוצאים- רבי יהושע-
כן אומר גמ’. אבל, נראה שאולי זה רק בהו"א, שאולי למס’ יש לומר שרק מתיר בערמה כשיודע בוודאי שיכול לשחוט אותו, אבל כאן אולי לא יוכל לשחוט אותו.
משנה ה:
לא יזיזנה- כרבי שמעון-
מזה קשה לרב נחמן שאמר (ב.) שסתם משנה סובר שבי"ט יש מוקצה.
משנה ו:
אין משתמשים- אם תלוי הוא-
מסתבר לי שכשלא תלוי, לא יכול לשקול. אבל, עדיין נותן בו דבר כדי לשמור אותו, וזה מה שנתחדש לאיסור כאן.
כל עיקר- להכיר גודל הבשר-
ארקמידי"ס הכיר את זה, כמו שרואים מבריטאניק"א, שכ’, “ The volume of displaced fluid is equivalent to the volume of an object fully immersed in a fluid or to that fraction of the volume below the surface for an object partially submerged in a liquid.” כמו כן ראיתי באינקרט"א, וכן ראיתי מיצחק אסימוב. אומרים שראה את זה בתוך בית המרחץ, אחרי שהמלך רצה לבדוק את הטבעת שלו. הוא חי שלש מאות שנה קודם החורבן, ואז היה הדרך שלו כבר ידוע בזמן הגמ’.
כל עיקר- להכיר גודל הבשר-
גמ’ אומר שהוא בטבח אומן. לכאו’, קשה למה הוא רק באומן, שהכל יכולים לעשות ככה. עיין בהגו"צ של עוז והדר, שיש שלא גורסים "טבח אומן.” נראה שאולי צריך הגי’, כיון שבדרך כלל מוכרים על פי משקל, וזה רק מגלה הנפח, וצריך טבח אומן לדעת הרישי"ו בין המשקל לנפח. ותחשב.
לשקול- ביד- אומן-
יש לדון אם רבי יהושע מודה לזה.
משנה ח:
מצוי מדות- אם לא מקפיד-
כן נראה מן הגמ’. ויש לדון, שאולי אותו פסק רצה לומר נגד החכמים. ותחשב על זה.
רגיל- כמה עולה-
השני הוא רק אם נניח שמשנה סובר שלא יזכיר כמה משלם.
חנווני- סכום השיעור-
עיין שם, שיש לדון אם יש חולק על זה.
חנווני- סכום בדמים-
גם בזה יש לדון אם יש חולק. ואם תאמר פשוט הוא שאין חולק, שהרי משנה אמר לעיל שאסור להזכיר דמים. וי"ל שזה כרשב"א. יותר נראה לדחות שלא מזכיר דמים של כל חפץ, אלא של כולם ביחד, ולכן אינו כל כך כמקח וממכר. ויש לדון. ותחשב על זה.
למלא כלי- לשאול למדה-
הנחתי ששמואל מודה לזה, אבל אולי לא מוכרח.
פרק רביעי
משנה א:
בסל- אין להוסיף-
אין דין זה כל כך פשוט לי, שצריך להגדיר כמה טורח אסור להוסיף, שבוודאי יש טורח שמוסיף אם לא עושה כדרך חול, שיש סיבה שלא עושה כן בחול.
משנה ב:
סמוך לה- שני ציורים-
יש לדון אם שני התירוצים של הגמ’ חולקים זה על זה.
סמוך לה- איגוד-
יש לדון אם זה רק בסכך, שאין בו קשרים. ותחשב.
משנה ג:
קרדום- הולך עם הכלים-
כן נראה מרשי. לולי רשי, היה אפשר לומר שהוא עובדא דחול. ויש להעיר שלפי רשי קשה למה מותר אם חציו קרדום. ותחשב על זה. צריך לומר לומר שהחשש הוא כשמשתמש בו. ותחשב.
פוחת- לבנים בלי טיט-
רשי כ’ שמפני זה אין בו איסור דאו’. אבל, אף בלי זה, אין איסור דאו’ אם לא שמכוון לבנותו שם. ותחשב. אולי מניחים שיבנה אותו שם.
משנה ד:
פחמים- מרחץ-
לא פשוט לי למה לא מותר לטשולינ"ט (ומצאנו בשבת (סופ"ק) בשר על גחלים).
פחמים- כלי-
לא כל כך פשוט לי מהו כלי. אולי הוא דבר שיש בו תשמיש. אם כן, קשה למה מותר לעשות אש. אולי צריך להיות נתקיים, או צריך להיות קל להביא ממקום למקום. וצריך לחשוב.
באור- שני פיות-
נמצא שאין איסור בעשיית כלי, אם לא נראה ככלי. אפשר שאין זה נחשב עשיית כלי, שכבר יש פתילה, אבל נראה כעשיית כלי. ותחשב.
משנה ו:
כל מה שבחצר- חולקים-
יש לדון אם גם לפי רבנן יהיה אותו מחלקת. איני יודע למה לא. אבל, יל"ד, אז, ל"ל חלקו בו ברבנן.
משנה ז:
עצים-
הדרך שזה היה מצוי היה על ידי עץ שהכניסו לתוך חור, ועשו שהוא מגלגל בתוך החור מהר מאד, עד שמוציא שלהבת.
אבן-
היה מצוי מאד שבני אדם יתחילו אש כזה, עם אבן הנקרא פלינ"ט.
מים- רשי מפרש-
נראה שגורם אש כיון שמים מגדל כל מה שרואים בצד האחר שלו, ואז עושה יותר חמימות מחמת השמש. שאלתי את ד.ת. אם זה מסתבר על פי מציאות, ולא ידע, אבל גם הוא שמע ממק"א שעושים אש ככה.
שביעית- ר"א והלל-
גמ’ אומר שזה רק שיטת הלל, אבל מוכח מגמ’ שלנו שאין זה נכון, אלא אף רבי אליעזר הוא. ותו"ת.
דינים היוצאים- אם יש ברירה-
(איני יודע למה צריך לומר כלום.)
פרק חמישי
משנה א:
משילים פירות- אינם מוקצים-
כ"נ מסברה, וכ"נ ג"כ ממה שאומר פירות. אין לומר שהוא לאו דווקא, כמו שאומר גמ’ (לו.).
וכן כדי- טבל-
איני יודע למה הם מוקצים, כמו שפי’ רשי לעיל (על משנה של סתירת בנין), שהרי איסור לתקן אותם הוא רק דרבנן. וצריך ביאור.
משנה ב:
קידושין- אין לו בנים-
איני יודע אם גם צריך שאין לו כבר אשה. אגב, ע’ בלשון גמ’ שאומר שרק יש מצווה אם יש לו אשה ובנים. משמע שאף אם אין לו אשה, יש בו מצווה, כמו שאומר ביבמות. ותחשב. ועיין ברשי שלא משמע כן.
משנה ד:
ששאלה- הפקר-
כן נראה, אבל לא הבנתי את הקושיה, שנאמר שיש לו חשיבות מספקת לתת לו דין תחום, אבל לא שלא להיבטל, ודין זה לא היה שייך בו. ותחשב.
ששאלה- לטעם-
איני יודע אם הכוונה הוא שנעשים לטעם או שנותנים טעם.
מים- הרבה רוטב-
עיין שם בלשונו, שמשמע ששם, ורק שם, מלח ומים לא בטלים. ויש לדון, שמסברה היה יותר נראה לומר שרק דן במים.
משנה ה:
גחלת- שביתה-
אם הייתי למדן, הייתי דן אם הענין הוא שאין לו שביתה או שאי אפשר לו להיות חוץ ממקום שביתתו. ותחשב.
כרגלי הממלא- אם יש שביתה-
יש לדון מה יקרה אם יש שביתה לדבר הפקר וגם יש ברירה. אולי אי אפשר לסבור שניהם.
משנה ז:
אם זיכה- כיון שזיכה-
עיין בגמ’ שאומר שני צדדים, אבל הם נראים כאחד. מה שכתבנו הוא מה שמפרש רשי לשני, אבל לא פשוט לי מהו הראשון. נראה שצריך לומר שהדיון הוא אם מהני כיון שהוא נותן אותו ביותר לרשות שלו או כיון שמגלה דדעת לענין מקומו. ותחשב על זה. צריך ביאור למה יהיה יותר ברשות שלו אם זיכה אותו. ותחשב.
בייתות- רבי-
לא פשוט לי איך נאמר שהם ראויים (אם נאמר שכרבי יהודה הוא) רק מפני שפעם בשנה חוזרים, שהרי צריכים להיות ראויים בבין השמשות. נראה שתמיד הם ראויים, ולא צריכים צידה וכדו’, ורק דן אם חושב עליהם. אם לפעמים חוזר לו, הוא חושב עליהם להיות שלו, וחושב עליהם תמיד לעומדים לשחיטה, ולכן דעתו עליהם. אבל, אם אינם חוזרים לו, לא חושב על שחיטה שלהם.
* Footnotes
[fn:1] שם, מביא הרבה קושיות כעין זה, ובכל אחד מהם, רבי יוחנן מהפך וגמ' דוחה את הקושיה. יש לדון אם גמ' אומר שבזה רבי יוחנן לא מוכרח, או שלא בזה רבי יוחנן אמר שצריכים להפך.
