** פרק ראשון א-א א. אין להם שיעור -
כמובן, יש שני מיני שיעורים:
1. שיעור למטה.
2. שיעור למעלה.
יש להעיר שיש מאלו שהם שיעורים למטה ויש מאלו שהם שיעורים למטה. בגמרא חגיגה דן אם ראייה יש לו שיעור למטה או לא. מסיק שאין לו שיעור למטה, וכן אומר פני משה כאן. ובכל שיעור למטה יש לדון, שצריך לעשותו פעם אחת, וזה יהיה שיעור. וצריך לומר שזה אינו שיעור, אלא שבלי זה, אינו נעשה. ותחשב. וצריך ביאור מה זה אומר. באמת, בכעין תרומה, אין זה כל כך קשה, שיכול להיות פרי היותר קטן שבפרות, ואז במניעה אינו מדין, אלא ממה שאין פרי יכול להיות יותר קטן. אבל בראייה, שאין לשער על פי גודל פרי או כדומה, שכל ראייה שווה, אם הוא הכנסה לעזרה, אז קצת יותר צריך ביאור. ותחשב.
ויש להעיר שאולי מה שאומר שאין שיעור הוא מפני שכמה מאלו אינם חיובים כלל. ויש לדון, שאולי יש שיעור עדיין לקיום, כמו שכתבנו.
** יש להעיר
שבתפלה אומרים משנה זה באופן חלוק. נראה שהיו כמה ברייתות שהיו להם מנין הדומה לזה. אב ליש לדון למה נאמר ברייתא, ולא נאמר משנה. ותחשב.
** ותלמוד תורה
- עיין במש"כ. צריך ביאור, שאם כן, לכאורה, יש שיעור שהוא למטה, והוא שצריך לעשות כל היום. אולי רק אומר שאין שיעור למעלה. ותחשב. אולי זה לא נחשב שיעור, שהמצווה הוא ללמוד כל היום, ואינו שיעור. צריך ביאור מה זה אומר. ותחשב. נראה שהוא שחלק מן הטוב הוא עשיית כל זה, ולא רק שמוסיף טובה כמה שהוא עושה. למשל, במצה, טוב לעשות מצה, ויותר טוב לאכול יותר מצה (כן מסתבר אבל אין זה כל כך פשוט באחרונים). כאן, אינו כן, שחלק מן הטובה שבמצווה זה לא נתקיימה אלא אם לומד כל היום, ובטל לגמרי אם לא לומד. אז, אין לה שיעור לאותו מצווה. ותחשב.
וצריך לומר שמה שהוא בכל יום הוא חלק מן המצווה, ולא רק מה שהוא כל היום, שבלי זה גם כן יש שיעור. ותחשב על זה.
גם אולי יש לומר שאין שיעור קצוב, שתלוי במה יכול לעשות. יש לדון, שכל דבר הוא כן. ותחשב. ויש אחרונים שאומרים לומדות מוזר כמו זה גבי עוסק במצוה שפטור מן המצוה, שהוא חייב גבי ת"ת כיון שאין אף צווי אם אי אפשר לקיים. ותחשב.
** אין אדם עושה -
יש לדון מהו תירוץ של גמרא:
1. אין שיעור למעלה, שיכול לעשות את כל מה שחייב (100%) לפאה. בתרומה, אינו כן.
2. אין זה שיעור, שאין זה מפני המצווה, אלא מפני המעשה שצריך כדי לקיים המצוה. ותחשב. ונראה שזה אומר דבר, אבל צריך לבאר אותו.
יש לדון מה יהיה הדין אילו היה חייב בפאה של שיבולת ראשונה, שלכאורה, אז אינו נותן כל מה שחייב. ויש לומר שאז היה יכול ליתן אף אותו שיבולת לפאה. גם יש לומר שהיו שני מיני חיובים. ותחשב. גם יש לומר כתירוץ שני שבארנו לעיל. וצריך ביאור.
** ונשרפה -
לכאורה, זה אם תמצא לומר, שאם יכול לחייבו בפאה, ואז צריך לומר שיכול לעשות כל שדהו- והוא בכלל- פאה (עיין לעיל), אז צריך לומר שמפריש פאה אחר שעשה אותו פאה. ותחשב.
** הקדיש -
יש לדון שרק רואים שנותן על ההפקר, ולא שהפקר מחייב אותו בפאה. ותחשב. מניח שאילו לא היה מחייב בנתינת פאה, לא היה נותן כנגדו. מסתמא, זה מפני שמה שנותן כנגד השדה הוא שכל חלק מחייב פורתא. ויש לדון, שהשיעור הוא דרבנן, וזה לא הסיבה שנותן כנגד כולו, אלא הוא מפני ששיעורו רבנן מה נותן כפי הרווחת השדה. וצריך ביאור.
** נשמעינא -
בסוף השדה- צריך ביאור קצת מה נחשב סוף השדה. לכאורה, הוא כשמכוון שלא לקצור עוד. יש לדון מה הדין במוכר (שהרי, לא קוצר אותו עוד):
1. צריך לכוון שלא ייקצר. זה, אולי, ייקצר. אז, אינו מכוון שלא ייקצר, אלא שלא חש אם ייקצר או לא, שמה לו בזה.
2. צריך שלא לכוון שיקצר, אבל זה מכוון למכור אותו, ואולי יקצר (כפי מה שרוצה הלוקח). ותחשב.
** א: מהו שתחזור -
יש לכתוב צדדים בזה:
1. חייב:
  1. רק פטור כיון שאי אפשר להשאיר את זה. כאן, אין החיוב להשאיר, ואפשר לעשות מה שצירך לעשות (לתת לעניים) בזה.
2. פטור:
  1. אולי אין דבר שיעשה חיובו (שאין דבר שהיה נקצר בשדה שהיה קיים).
  2. אולי חיוב עומר לא בא מסיבת חיוב קמה, אלא ממה שהיה חיוב פאה שלא נעשה. עיין בפני משה, שנראה שסובר שזה הוא מסקנת הגמרא. ויש לעיין בלשונו.
** יש לה שיעור למטן -
יש להעיר ששיעורו הוא, לכאורה, רק מדרבנן.
גם יש להעיר שגמרא זה נוגע לאם משנה דן בשיעורים למטה, למעלה, או כל מה שיש (במילים אחרים, כל מה שאין). לכאורה, נראה כצד שלישי, שאינו דן בלמטה, שאין כל דבר כן, ואין דן רק בשיעור למעלה, שאז לא היה לזה להזכיר מה שאין שיעור למטה. ויש לדון, שאולי רק מזכיר דין, ולא קאי על משנה.
** הוסיף -
עיין במה שבאר פני משה. יש לדון למה יהיה הראשון שנתן חייב במעשר, כיון שלמעשה הוא פאה, ואז פטור מן התורה:
1. אולי חייבו אותו מדרבנן.
2. אולי מכוח הפקר בית דין, יכלו לעשות שאינו פאה. זה תלוי במהות פאה. ותחשב.
** עיין בגרח"ק
שפירש שדן אם מה שמוסיף חייב במעשר או לא. מדאורייתא, לכאורה, אינו פאה, ואז יחייב. יש לדון למה יפטור:
1. אולי פטור כיון שרבנן הפקירו אותו. יש לדון, שרבנן גם טענו שהוא של עני, ואז אינו הפקר די לפטור. ויש לדון, שאולי הפקר לעניים הפקר די לפטור (ולכן פאה פטור), רק שבדרך כלל לא חל. ותחשב.
2. כמו כן, יש לומר שרבנן עשו חלות של הפקר עליו, אלא שאין אדם יכול לקנות אותו חוץ מעני. זה גופא עשה קנין לעני, אבל כיון שהיה step שבו היה הפקר ממש, פטור. לא נראה, שלמעשה, לא היה אחרים יכולים ליקח, ועוד שלא היה באותו step לשום זמן. ותחשב על זה.
3. איני יודע את הדין כשאדם נותן פאה עוד. אולי הוא פטור, ורק דנים כאן כיון שאל כיוון לתת פאה, אלא לקיים חיובו מדרבנן. נראה שדן אם נתינה כזה נחשב נתינה לעשות פאה.
4. אולי רבנן עשו שהוא עוד חייב בפאה מן התורה על פי הפקר בית דין הפקר. זה תלוי בגורם לחיוב פאה.
5. אולי רבנן עשו שמה שנתן בפעם ראשון אינו פאה, וממילא חייב עוד בפאה. יוכלו לעשות כן מחמת דיני הפקר בית דין הפקר. ותחשב.
** אלא דברים -
גם יש להעיר שרק מונה מצוות, אבל במנין זה ששואל, יש דברים שהם הכשרים. אולי מה שאומר גמרא הוא רק סימן לזה. ותחשב.
** ולמה -
יש לדון איך יכולים לומר שאין לו שיעור, אבל צריך להיות נראה לעיני דיינים. לכאורה, זה שיעור. יש לומר שהוא חלק מן המצווה, כמו שכתבנו לעיל. ותחשב.
** הדא
- יכול- מה שאמר יכול, ולא ”חייב“ הוא שלא מצוי שמחמת זה יהיה חייב, שרק חייב כשאין פאה בלתי מה שנשאר בשדה, כמובן. אז, יש רק ציורים מיוחדים שיחייב. ותו"ת.
** ב. חכמים הם -
לכאורה, ר"ל שמקשה שמברייתא זה משמע שלא רק אין שיעור מן התורה, אלא שמן התורה, שיעורו הוא מה שהו. זה אומר שתורה משמע ששיעורו משהו, ולא רק לא נותן בו שיעור. אז, יותר קשה לרבנן לשנות את זה. יש לדון איך משמע כן מן הברייתא, שאולי אומר שמן התורה שיעורו הוא מה שהוא, כיון שלא נתן בו שיעור.
אפשר לבאר שכשרבנן מכריעים לומר מהו שעירו, יש להם כוח זה כיון שהם מפרשים את הקרא (מפרשים לאיזה שיעור כוון קרא).[fn:1] אז, אם היה כך כאן, לא היה לו לומר שמדאו‛ יש לו שיעור אחד, ומדרבנן יש לו שיעור אחר, אלא שמדאורייתא יש לו שיעור שקבעו רבנן.
יש לדון בכל זה, שלא משמע כן מפני משה, שמשמע שרבנן קובעים לפי מה שרוצים, שאומר שקובעים לפי הזמן. ויש לדון. ואולי יודעים (צריך ביאור איך) שקרא אמר שהשיעור הוא מה שאומרים רבנן. צריך ביאור.
באמת, צריך ביאור, אם לא נאמר כעין זה, איך יהיה לרבנן כוח זה. אולי סובר ר"ה שיש לרבנן כוח לדחות דין תורה, ואף בקום ועשה. ותחשב.
** כדעתיה -
ק"ק, שגמרא פירש למה ר"י מקשה כאן בייחוד (מחמת אותו ברייתא), ושוב אומר שהוא לשיטתו, שאומר כן בכל דבר. נראה שאולי אומר שיכול לומר שאין שיעור זה דרבנן כאן, שיכול להיות לו מקור אחר לשיעור זה, והוא מהלכה, שסובר ששיעורים נאמרו בהלכה למשה. ודחוק.
** קושיית רבי
יוחנן צריך ביאור, שלמה לא יעשו רבנן שיעור, שרק מחייבים אותו להביא יותר גדול, ואין זה עוקר דיני תורה. ותחשב.
** רבי הושעיה -
צריך ביאור איזה הוא רבי הושיעה השני (שגמרא רק הזכיר אחד). יש שגורסים שקושיית רבי יוחנן היה על רבי הושיעה (אם כן, הלשון יהיה משמע שרבי הושיעה הוא תלמיד של רבי יוחנן. יש לדון אם זה אמת.). אז, הענין יהיה שסובר ששיעורים הם מדרבנן, ואף כאן סובר שהשיעור מדרבנן. לכאורה, זה לא בא לתרץ קושיית רבי יוחנן, שעדיין הוא קשה. ותחשב.
** שמא יעמוד -
יש לדון אם חושש שמשיח יבוא בזמנו, ויהיה יכול להקריב, או שצריך להביא בזמן ביאת משיח.
יש לדון אם חייב אחר ביאת משיח. ותחשב.
יש לדון, אגב, אם בבהמה שהפריש כבר כשחי, ואחר כך מת, הוא חטאת שמתו בעליה. ותחשב. ואם תאמר אם אינו נחשב מתו בעליה, למה ממיתים חטאת; נשהה עד שיבוא משיח. יש לומר שכבר נדחה. גם יש לומר שמה שמת הוא גורם חיוב להמיתו, ולא רק מה שאי אפשר להיקרב.
** דשמא יעמוד -
לכאורה, גמרא מבואר שהוא חייב כשיעור של זמן הקרבה. אם חייב כשיעור של זמן אכילה, יכתוב או שחייב או שפטור.[fn:2]
אז, צריך לומר (ויש לדון למה) שחייב כזמן הקרבה. יש לדון, עדיין, למה לא כותב כמה אכל (שאולי שינו את השיעורים, אבל לא די). אולי זה לא כל כך קל לזכור, שאכלו כבר, ואינו שם. ותחשב.
** אלא צריך -
ראיה זה מעניין, שאם הוא מדרבנן, הוא עדיין חזק להביא חולין לעזרה וכדומה. ותחשב.
** ב: עד היכן -
עיין במה שפירש פני משה. יש להעיר שהיה הלכה למשה מסיני. צריך לומר ש"עד היכן" ר"ל עד היכן היה בין שכחת הלכה למשה מסיני ותקנה זה.[fn:3]
יש להעיר שלכאורה, היה אותו שיעור של תרומה שיעור למטה (כמו שהוא גבי תרומה). אז, צריך לומר ששיעור של חומש הוא גם כן שיעור למטה.
עיין בפני משה שכתב שהשיעור הוא "חומש ולא יותר.” משמע שזה שיעור למעלה. אולי הוא שניהם. ודחוק. עדיין, לשונו משמע שגמרא דן בשיעור למעלה. אז, לכאורה, צריך לומר ששיעור שדומה לשל תרומה הוא שיעור למעלה. ותחשב.
יש לדון לפי פני משה מה הוא קושיית גמרא שייצא בלי שום ממון; הרי אינו צריך לתת. נראה שאומר ששיעור למעלה הוא כדי שלא יעני; אין זה מעכב אותו מלעני, שאף בזה יעני. ותו"ת.
** כתרומה -
יש לדון אם ר"ל שהוא כשיעור בינונית של תרומה, או שכמו בתרומה יש כאן כמה שיעורים (אחד לבינוני, אחד לטוב עין…). לשון פני משה משמע כצד ראשון. יש לדון למה נחשבו כן בגמרא.
** בגופו -
לכאורה, גמרא צריך להיות כבר יודע שהוא הלכה למשה מסיני, שאם הוא רק תקנה, אז הוא רק דין מדרבנן. כיון שכן, נאמר שהוא כעין ראייה, שיש לו שיעור דרבנן. ויש לדון, שלפעמים מונים שיעור דרבנן, כמו, אולי, בפאה. ותחשב.
** חומש שכר -
היה אפשר לומר שהוא חומש כמו עשירותא דבי רבי (כמו שאומר בנדרים), שהוא חומש מן הנשאר. אולי עדיין יעני יותר מדאי.
** בשם ריב"ח -
מעניין שהיה ריב"ח תלמיד של רבי יוחנן (שכחתי המקור לזה; אולי הוא בסדר תנאים ואמוראים). אם כן, מעניין שריש לקיש, שהוא חבר של רבי יוחנן, יאמר דבר משמו. ותחשב.
** ואין אדם טופל
- לא הבנתי תלייה זה כל כך. לכאורה, לרבי יוחנן נמצא שיש שיעור דאורייתא, שצריך להיות שני מעה, וגם יש דין דאורייתא שצריך להיות מחולין. כאן, שאין לו ממון די, צריך לדחות אחד מהם. נוקט לדחות השני. צריך ביאור למה. אולי דין שני הוא מדאורייתא רק על מקצתו. לחזקיה, יש שיעור דרבנן של מעה, ומה שצריך להיות מחולין. יש לדון למה נוקטים לדחות זה מזה. ותחשב על זה.[fn:4]
** ג. ולא מית אלא שלא ימות -
עיין בבבלי שאומר דלא כזה, שאומר שמציל ממיתה ממש. אולי מימרה זה חולק, ואולי המלך היה טועה.
** שאלו את רבי יהושע -
עיין בבלי מנחות שאומר שבן דמא בן אחותו של רבי ישמעאל שאל כן לרבי ישמעאל. אולי שניהם קרו.
גם נראה להעיר שלא מצאנו כמה גדולים שהיו nephew שלהם תלמיד חכם. מצאנו כן ברבי ישמעאל (באותו גמרא במנחות), ומצאנו כן (אולי, שתלוי בגירסא) ברבי יהושע (שהיה "ר"ח בן אחי ר"י). אולי מפני ששאל לו nephew[fn:5] החליפו שני תלמידי חכמים שהיו לו nephews שהיו תלמידי חכמים. ותחשב.
** רבי בריה -
מצאנו, אז, רבי חוץ מרבי הסתם. אולי נקרא על שם שנקרא רבי (כמו שתינוק נקרא על שם נתן הבבלי בבבלי שבת).
** אדמה לו -
עיין במש"כ. אם כן, אין צורך לומר שקאי על דמיון לה’, אלא כל דבר טוב. ותו"ת. אולי הענין הוא שאי אפשר להיות דומה ממש לה’, ואז לזה לעולם מאווה, שאינו משיגו לעולם. ותחשב.
** מכם -
יש לדון אם הדרשה הוא שאם הוא רק, הוא רק מפניכם, שאתם לא מיגעים בו, או אם הוא שאם הוא רק הוא רק מכם, ר"ל רק לנגדך, שאתה בלחוד חושב שהוא ריק. ותחשב.
נראה כראשון. ועיין בלשון פני משה, ובלשונות לקמן. ותו"ת.
** צדקה
- עיין במש"כ. היה נראה לומר כן מחמת המשך גמרא, אבל לא נראה ככן לגירסה שלנו, שגורס "שקולות,” שאם קאי על גמילות חסדים בלחוד, היה לו לומר, “שקולה.” ותחשב.
** משקלה זהב -
קשה, שאז נטל שכר כיבוד אב ואם.
** ד. שאר מצוות -
מילה- לכאורה, ר"ל מצווה למול את עצמו, שמצווה למול את בנו אין לו סכנת נפש עצמו. ותו"ת.
** גדול
- והטעם- לכאורה, זה יהני רק להאומרים ביאור זה שאומר. יש שאומרים שהוא מפני שאז מקיים ציווי מאת ה’. אם כן, יותר קשה לומר כמש"כ (ואולי יש טוב, שמקיים שני ציווים. לא נראה כן, שאין ציווי של פרעון חוב ממש מחייב אדם בכיבוד אב ואם.).
** יבוא עורב
- שני הדברים שאומר הם סותרים, שאומר שכיון שהוא היה אכזר, יבוא אכזר כמותו, וכיון שלא היה רחמן, יבוא רחמן. ואולי יש ענין בכל אחד מהם. ותחשב.
** יבוא
- ואם תאמר הרי עורב יזכור שאף הוא היה לבן. ויש לדון, שאולי לא יזכור. גם יש לומר שיחשוב שזה מפני שאביו היה לבן (שאף הוא נגרש מקינו), אבל הוא, שהוליד כשהיה שחור, יוליד בן שהוא שחור.
** אינן שוות -
קשה, שהמשנה אומר שת"ת הוא כנגד כולם, אבל לא יותר.
** רב אבא -
קשה, מי היה אביו של רבי אבא- רבי אבא או מרי. אפשר שמרי היה אמו[fn:6][fn:7], או שהיה שם אחר של רבי אבא. גם אפשר שהיה אחד מהם stepfather. גם אפשר ש"בר מרי" חוזר על רבי אבא הראשון, ואז היה זקן של רבי אבא ואב של רבי אבא. ותו"ת.
** גדולות -
היה אפשר לומר שהוא רק כנגד שנים מהם, ולא כנגד אף השלישי.
** חשודים -
משמע שלא ידע שעברו, אלא שהיו חשודים. ותחשב.
** ד: תני ר"נ -
לא הבנתי, שאוסר תורה דבר אחד, ואולי הוא מפני שיש בכללו לשון הרע, או שיש בכללו רכילות, ולא מפני שיש בכללו שניהם. ותחשב על זה.
** זו רכילות
- עיין במה שבאר. נראה שזה רק לגירסתו, שגורס, “זו רכילות לשון הרע.” לגירסה שלנו (שהוא "זו רכילת לשון הרע") נראה שאומר דבר אחד, והוא רכילת לשון הרע. ותחשב על זה.
** יש להעיר
שיוצא מגמרא זה שרע של רכילות ולשון הרע הוא שסותר שלום. ותחשב.
** דברו כתובים -
לכאורה, ר"ל שכן דיבר ה’.
** לשון בדאי -
יש לדון, שמה שלא ראינו שיעקב אומר כן אינו ראיה שלא אמר כן.
** ה. יש לה פרי -
קשה, שיש הרבה עבירות כך, לכאורה, שאם גוזל, יש לו החפץ…
** איבד זה כל -
עיין ברב אלחנן שכ’ שלא איבד סיבות טובות, אלא קיום רצון ה’. לשון כל המימרה לא משמע כן. ותחשב.
** ה: א-ב ולפי הענוה -
לכאורה, לצד ראשון ענווה רק ר"ל צדקות. ויל"ד.
יש להעיר שלכאורה, לצד ראשון, ק"ק ל"ל הביא מקרא שאומר שהיה משה ענו או כדומה. ותחשב.
לצד שני, לכאורה, צריך ביאור למה נותן יותר מכפי ששים, שזה כפי ששים של מה שמוציא, לכאורה. אולי כיון שלא חסר כל כך בעשייתו (שזרע מעט), חייב יותר.[fn:8]
** ו. א-ג שלא תאמר -
זה מעניין, שלכאורה, דין לוקח הוא שמי שקוצר את השדה הוא מי שחייב בפאה. אם כן, רק הפודה יחייב, ואין בו חידוש.
מזה משמע שהענין הוא שכל מי שיש לו השדה בזמן שהוא ראוי להיקצר ולהתחייב בפאה יש לו החיוב. אז, כיון שהיה אז להקדש, והיה אז נפטר, הוה אמינא שלא יתחייב.
צריך ביאור למה נחשב כצד זה. ותחשב.
** ו: אפשר לומר -
יש עדיין נפק"מ להיותו פאה, כמו מה שמותר רק לעניים. היה יותר נראה לומר שממה שאומר שהוא פאה, רואים שהוא פוטר, שלמה לא יפטור כיון שהוא פאה. ותחשב.
** ז. מתכוון -
לא הבנתי כל כך שאלה זה, שאם כבר קצר אותו, ואינו מתכוון שיפטור שדהו, אז הכל כן, ואין ר"י מוסיף כלום. אולי צריך לתת אותו לעני. ותחשב.
גם לא הבנתי כל כך ברייתא של תירוץ גמרא עם התירוץ. וצריך לחשוב עליו.
** א-ד ז: זורעים -
עיין בפני משה שמפרש ל"ל לומדים כרם מקרא שאוסר כלאים בשדה. אם נאמר שאילנות לא נקרא זריעות בשדה, קשה איך לומדים כרם מזה. צריך לומר שגפנים וכרמים חלוקים. צריך ביאור למה. ותחשב.
** כלל -
ואם תאמר שני צדדים סותרים זה את זה במציאות, שזה אומר שספיחים יותר מסתבר לאכול, וזה אומר שיותר מסתבר לצבוע. אולי אין הכי נמי, חולקים במציאות, שלא היה המציאות נודע. גם יש לומר שספיחים כולל שני מינים. כולל ספיחים שנזרעו לזמן מועט ושנזרעו לזמן רב (ואולי מתחילה נזרעו לצורך, אבל עבר זמן רב, עד שנקראים ספיחים כיון ששהו לזמן). מה שאומר פני משה ראשון קאי על כלל ראשון; מה שאומר שני קאי על כלל שני.
** ובאילן
- סומק- נקראים כן כיון שמילה זה אומר "אדום" בארמי (וגם, כמובן מכאן, בערבי).
** ח. ואית דבעי נשמעינא -
אפשר שמביאו לא רק לפרש פשט אחר במשנה, אלא שאז אפשר לומר שאין אילן נקרא שדה, ואז יכולים לתרץ עוד קושיית גמרא. ותו"ת.
** דבר שהוא שווה -
יש לדון למה לא לומדים פרט מכרם, שיש לדון מהו הפירכא. אולי גפן חשוב כיון שמנסכים ממנו. ותחשב.
** ע"ד רבנן -
היה יכול לומר שכיון שכבר חייב בפרט, יותר קשה לחייב גם כן בפאה, שכבר חסר. עיין כעין זה בקידושין (כ) לשיטת רבי שמעון. ויש לדון, שאולי אז שני הקל וחומרים סותרים זא"ז. יש לדון אם זה בעיה, שקל וחומר רק אומר שלא נדע ללמוד. ותחשב.
** כרם וזית -
נמצא שאילו היה כתיב באילן, היינו לומדים ממנו כרם. קשה, אז, למסקנא, ל"ל כתבו באילן, שלמעשה נוהג הוא בכרם.
** בן חקולי -
מסתמא, היה אביו חקלאה (farmer).
** א-ה ט: רבי ורבי יהודה הנשיא -
ואם תאמר הרי אלו אדם אחד, ובוודאי לא חלקו כלל. ויש משנים שם אחד לעשות שהם בני אדם חלוקים. גם יש לומר שהיה לרבי שיטה אחת כשהיה קטן ושיטה אחת כשנזקן (כמו שמצאנו בתחילת פרק הזהב). אם כן, יש לדון למה קורא לשיטה אחת בשם רבי ושיטה אחת בשם רבי יהודה הנשיא. אפשר שרק לא רצה לקרוא לשניהם בשם אחד, שאז היה בולט שהם מאיש אחד (ואולי בני אדם לא יבינו תירוץ זה שאנו כותבים). גם יש לומר שבזמן אחד בחייו היה רבי נקרא רבי ובזמן אחר היה נקרא רבי יהודה הנשיא. איני יודע איזה קידם.
** פרק שני ב-א י: ואלו מפסיקים -
נותן נפק"מ אחד. יש עוד נפק"מ באם יכול לתת מזה על זה (תלוי בדיני באמצע שבאר גמרא לעיל).
** אינו מחובר -
יש לדון מה זה:
1. אפשר הוא שאינו כולל כל אורך השדה, שיש הפסיקים בו. אז הוא כך:
2. אפשר שהוא על אורך השדה, אבל לא במקום אחד. אז הוא כך:
לשון פני משה נראה כראשון. ויל"ד.
** יא. אתא רב חנינא -
החילוק הוא אם עשה בו תחומי ארץ ישראל או גבולים שבין שבטים. גם היה אפשר (ואולי קצת משמע כן מלשון פני משה) שרק חולקים באיזה לשון נאמר (שחייב אדם לומר בלשון רבו).
** מן מה -
מניח שאז יותר מסתבר לזרוע דבר קטן. אולי הוא מפני שכיון ששדהו קטן בין כך ובין כך, לא יהנה ממה שלא מופסק. גם יש לומר שכיון שלא אפשר לו להיות יותר ממין אחד אלא בהפסק, מסתבר לו לעשות הפסק.
** חייב בפאה -
לכאורה, זה סימן, שחייב בפאה כיון שהוא קצירה. כיון ש כן, נמצא שיש קצירה חלוקה בין שני השדות.
** יב. לא הבנתי כל כך
דיחוי גמרא, שלכאורה, נכון במה שאומר שאינו מוכרח שהם סוברים כן, אבל איני יודע למה מניח הדינים שאומר. אולי אין הכי נמי, אין צורך להניח כן, אלא נותן אפשרות אחר, ויש כמה עוד אפשריות. ותו"ת.
** ב-ג מה כותש -
פשט ראשון שאומר הוא שדן אם צריך להיות האילנות הנוגעים זה בזה נוגעים בגדר או לא. לא הבנתי פשט שני שאמר.
** יב: עשרה טפחים -
לא הבנתי את זה כל כך. פשטות גמרא משמע, לכאורה, שיש נטיעות שצריך להיות קרוב בד"א, ויש שצריך להיות קרוב בעשרה טפחים. גמרא אומר שי"ט הוא מנוף לנוף. צריך לבאר מהו מנוף לנוף, שלכאורה, דנים בקירוב האילן. אפשר שנוף הוא קצת חוץ לאילן. פני משה אומר שד"א הוא מגדר. לכאורה, לא מוכרח כן.
עיין ברח"ק שאומר שי"ט אומר שלא צריך להיות נוגע ממש. אם כן, לשון נוף לנוף טוב, אבל הדין זה מחודש, שאז נמצא שיכול להיות יותר רחוק מזקנים. זה נגד סברה שאומר פני משה. אולי אף זקנים א"צ שיהיו נוגעים, אלא תוך ד"א. אז, לשון משנה שאומר כותש קשה, שלא קאי על זה ולא על זה. וצריך ביאור.
** חצי אגדו -
לכאורה, לא צריך מה שהוא חצי אגדו וחצי שמומית, שאף בלי זה, הרי לא כילה את שדהו. ותחשב. אולי כאן מיירי במפריש בסוף, ולא כילה את שדהו הוא כשמפריש באמצע. ותו"ת.
** וכל -
צריך ביאור מהו החילוק. יש לומר שמחשבה על כל השדה (שהוא מה שחייב) יותר חזק ממחשבה על חצי השדה. ותחשב.
** ולחרובים -
עיין במה שפירש. גם היה אפשר לומר שכל הרואים לא תלוי במי שעומד קרוב לחרוב, אלא בחרוב עצמו, דהיינו אילו היה חרוב יכול לראות, אם היה יכול לראות חרוב אחר הם כשדה אחד. ותו"ת. יש לדחוק לומר שכן כיוון לומר.
** ב-ד יג. מרובין -
כן אומר גם בבבלי גיטין (ס:).
** אכתוב
- צריך ביאור מה נתמעט מזה, שהיה נראה לומר שממעט הלכות למשה מסיני. כן נראה גם מרש"י בגיטין שם. אבל מפני משה לא נראה כן, שאומר שהוא, “דבר אחד נלמד מחבירו על ידי דרשת חכמים.” צריך ביאור מה אומר, שלכאורה, לשון דרשה לא בדרך כלל נופל על כעין זה. אם, אף על פי כן, נאמר שמכוון לומר דבר שנלמד מדבר אחר, קשה, שזה לכאורה, מה מצינו, והוא אחד מן הי"ג מדות. ותחשב.
אפשר שהוא מדה רק אם הוא מדין לדין, ולא מציור לציור. צריך ביאור איך מציור לציור יהיה נחשב יותר על פה.
** כמו זר -
לכאורה, ר"ל שאף הם יכולים לקרוא תורה שלנו. יש לדון אם אומר שבמציאות יכולים, כיון שכתוב, או שמן הדין יכולים, שהוא מותר להם ללמוד. לצד שני, צריך לומר שזה מוכרח ממה שנכתב (שאם לא כן, נאמר שנאסר קריאתם). אולי, אז, בזמנינו יש להתיר לנכרים ללמוד אף גמרא. ויש לדון, שאולי תלוי באופן נתינה, ומה שאי אפשר לכתוב אחריו אינו מאותו טעם שניתן, אלא מטעם אחר. ותחשב.
** תלמיד ותיק -
משמע שכל דרשות וקל וחומרים וכדומה כבר נאמרו הלכה למשה מסיני. אולי אין זה בכלל "לחדש.” צריך ביאור, אז, מה בכלל "לחדש.” אולי בא לכלול דבר שאמור בלי מקור בקרא, אלא ממשנה או כדומה. ותחשב.
** מן ההלכות -
עיין במה שמפרשים ראשונים את זה בבבלי ב"ב. מכאן, היה נראה שקאי על הלכה למשה מסיני.
** אמר ליה
- אם כן, אי אפשר לעולם ללמוד מרבו (ואף אם אמר הלכה בפירוש)[fn:9], אלא אם כן אמר שלא שמע אותו ממעשה, ולא שמע ממי ששמע ממעשה…. ותו"ת.
** ב-ה יג: שלא תאמר -
הוה אמינא זה מעניין, שכאן כבר קצר אותו בפטור, ובהקדש כעין זה, לא היה חייב.
** חזרה פאה -
זה מעניין. יש לדון אם אומר שאז מותר לקצור השאר ולתת מעומרים. אם מותר, מעניין, שהרי מדאורייתא אסור. אם אינו יכול, צריך ביאור מהו חידוש של חזרה זה. אולי הוא שיכול לתת מכל עומר שרוצה, ולא רק זה שקצר. לכאורה, זה קצת פשוט. ותחשב.
** יד. פרק שלישי ג-א בזורע -
לקמן, יבואר שמיירי בזורע כל שדה משבת וחרדל, אף שזה מוזר, וקוצר קצת קצת.
** אם ברצופים -
יש כמה גירסאות בזה. יש להעיר שהגירסא שנדפס בעוז והדר הוא, לכאורה, מוטעה, שהוא סותר את עצמו, שמחליף בין הוה אמינא למסקנא אם רצופים או מרווחים יותר מסתבר להיות כבית הלל. לכאורה, לקח הוה אמינא מדפוס זה, ומסקנא מדפוס אחר. ותו"ת.
** שלשה תלמים -
צריך ביאור אם דין של משנה הוא בשיעור של זרע אחר (ואז דן גמרא אם מעורבים מצד אחד אינו נחשב עירוב כלל או נחשב עירוב), או שמשנה שלנו הוא אף כשאין בו שיעור (כיון ש אין שדה של ערוגות אלו, אלא ערוגות), ואז פשוט לגמרא שעירוב זה מועיל קצת. ותו"ת.
** אילו תנן
- לולי פני משה, היה נראה לומר שמברייתא היה סובר שדן באילנות שהם פטורים בפאה.
** אילו
- צריך ביאור איך לומדים מכאן שהאילנות חייבים, שיש הוה אמינא לומר שחולקים בדבר שפטור ובדבר שחייב. אולי לא מסתבר שחולקים בשניהם, ולא מחלקים בין חייב ופטור בפאה. צריך ביאור למה. אולי הוא מפני שאי היו חולקים בשניהם, היה להשמיע רק מה שהוא יותר חידוש לקולא. ותחשב.
** יד: המנמר -
פירושו של אותו קרא אינו כמו שאומר גמרא שבת (תחלת פרק שמנה שרצים).
** לח ויבש -
לולי גמרא זה ושאלתו, היה אפשר ללמוד שמשנה דן בנקיטת יבש עם יבש (אם מפרישים מזה על זה), ולא בהפרשה על יבש. ואולי אפשר לומר שבזה דן גמרא כאן. גם יש לומר שדן בזה אף ביבש באמצע, ודן באם שני הלחים מצטרפים. ותחשב.
** חציו לח
- צריך ביאור למה מניח שזה יותר נראה יותר כשדה אחד וזה נראה יותר כשני חלקים. ותחשב.
** טו. שמואל אמר -
ואם תאמר הרי הוא כן אף בתבואה, שחציו היה לח וחציו היה יבש. ויש לומר שלא היה מוכרח מן המין להיות כן. ותחשב.
** על דעתיה
- צריך ביאור למה בני אדם יאמרו יותר שהוא שדה בפני עצמה אם הוא לח באמצע. ותחשב.
** טו. ג-ב כאן בשאין -
אם כן, היה אפשר לומר, "והוא…" על זה.
** לשוק -
זה מעניין, שמשמע שפטור כיון שאינו מכניסו לקיום. קשה, אז, למה הוא חייב אם לא מידל את הכל. אולי אז נראה שלוקח לבית.
לולי כל זה, היה נראה לומר שפטור כיון שלא לוקחו כיון ש רוצה לאכלו. ותחשב.
** אלא מה עבד
- ק"ק ל"ל פשוט לומר שמחייב כיון שמינו חייב. ותחשב.
** אפילו כל שהוא
- מעניין, שקורא לדבר גדול בשם "כל שהוא.”
** טו: ג-ג רב -
עיין בפני משה למקור זה. העיר א.מ.ו. שאולי רב שהיה מא"י נקט לשון ירושלמי. ויש להעיר שאף שמואל היה בא"י לזמן (עיין בפרק שביעי מב"מ). ותו"ת.
** רבנן -
צריך ביאור למה מקשה רק לזה על רבנן, שבין אם זה פשט בר"י בין אם אינו פשט, צריך לדחות אותו. ותחשב. ואולי אז היה אפשר לשנות הציור, אבל אז אי אפשר לומר כן בר"י. ותחשב.
** ג-ד חזרו וחלקו -
גי’ זה מוזר, שחלקו הוא, לכאורה, שווה ל"נשתתפו.” ותו"ת.
** טז. ג-ה קלחי אילן -
יש לדון אם מוכר כולם על גב אילן אחד, ואף על פי כן חייב בכל אחד ואחד (מסתמא מפני שיש ביניהם עצים שאינם שלו), או קלחים באילנות חלוקים (וחייב על זה בפני עצמה כיון שיש שדה ביניהם).
** חוץ מחובתו -
לכאורה, ר"ל שהתנה בשעת מכירה שזה יפריש.
** ריב"ל -
נראה שריב"ל קאי על זמן שראוי לחייב אילו קצר, ור"י קאי על זמן שעומד לחייב (שמסתבר שיקצור אז).
** טז: ג-ו כלאים -
מה שנקט בית רובע, אף שהוא השיעור רק לסאה, ואינו השיעור בדרך כלל, הוא, לכאורה, מפני שבית סאה נחשב מדה רגילה. ותחשב.
** מה שדה… עומרים -
שם, הוא שיעור למעלה. כאן, הוא שיעור למטה. לכאורה, יכול לשנות כיון שלא מסתבר להיות שיעור למעלה כאן. ותו"ת.
** יז. ג-ז ובבכורים -
יש לדון, שאף בחטה ושעורה צריך המקום לזרוע אותם, אלא שבזה המקום יותר גדול.
ונראה לי לפרש (ונראה שזה שייך לתחילת המסכתא) ששיעור ר"ל שיעור שלא נשמע מן עיקר ביאור המצווה. עיקר ביאור המצווה הוא להביא חטה זרועה; אז, פשוט שצריך שיעור של מקום זריעתו. לא פשוט מזה שיעור של אילן. ותחשב.
כמו כן, פשוט שכדי לקיים גמ"ח, צריך עשייה פעם אחת, ואז אינו שיעור. ותחשב.
קצת קשה על זה ממה שמקשה גמרא לקמן (“הגע עצמך"), שיש לומר שאין זה שיעור, אלא הוא מעצם המצווה. אולי זה לא פשוט כל כך. ודע שלכאורה, זה קשה בכלל, שאף הוא חלק מעצם המצווה. וצריך לומר שכאן לא מיירי בשיעור כלל, וכל שהוא לא אומר שאין שיעור, אלא אומר (אף) כל שהוא, ומקשה גמ’ שאף אם אין שיעור, והיה אפשר להימנות, למשל, בגמרא לעיל, אינו כל שהוא. ותו"ת.
** עליה פרוזבול -
עיין בלשונו. לא נראה, אז, כצד שאומר שפרוזבול הוא שהפקר ב"ד הפקר עושה שיש חוב חדש, שאם כן, אין נקטת קרקע זה סמל לכלום. ותחשב.
** עליה
- לא הבנתי כל כך למה גבוי קרקע גורם שיכול לגבות החוב, שאם הקרקע פחות, יש לומר לומר שישאר הקרקע. ותחשב.
** שיבולת -
ואם תאמר ייתן קרנ"ל אחד. ויש לומר שכשאומר כאן שבולת, מכוון לקרנ"ל. דחוק. גם יש לומר שכיון שאין חיוב במחובר, אין חיוב בתלוש. זה טוב אם נאמר שהחיוב בתלוש בא ממה שלא נתן במחובר. גם יש לומר על פי גמרא לעיל (א:) שאמר שלא חזרה פאה לעומרים. ותו"ת.
** קלח אחד -
ואם תאמר אם כן ל"ל אפשר לתרץ שיש שבולת אחד עם כמה קרנ"לים, וקצר רק אחת. ויש לומר שקצירת אחד אינו דרך קצירה, ורק קצירת שבולת אחת הוא דרך קצירה. ותו"ת.
** יח. אמר ר"י -
צריך ביאור למה צריך קנין במשנה שלנו, שלכאורה, מתנת שכיב מרע במקצת לא חוזר אף בלי קנין; רק צריך לשון קנין כדי שלא יחזור בו אם כתב כל נכסיו. ותחשב.
** יח: היה רבו -
ק"ק מה לנו ברבו שני ושלישי, שרק קונה משכיב מרע בשעת מיתה. אולי ירושלמי לא סובר כן.
** בריא -
לא תקנו- זה מעניין, שלכאורה, אין אותו לשון תקנה.
** פרק רביעי ד-א כ: חזרה פאה -
לכאורה, הסיבה לחלק הוא ששם, אף אם משליך אותם לבזבז, יכול לכוון קצת, שהוא משליך אותם. ואם תאמר אף גבי מחובר הוא כן, שיכול לבחור מה לקצור. ויש לומר שקצירה אינו כל כך מהר, וידעו מה יקצור קודם שייתן פאה. ויש לדון בזה. גם יש לומר שידעו שעל כל פנים צריך להיות בפאה אחת של השדה, ולא באמצע (אבל, עיין לעיל, יכול להיות רובו באמצע).
** כא. ד-ב ואפילו כריכות -
גמרא אומר שני דברים, “עד כדון מזיד ואפילו שוגג,” ו"ואפילו כריכות.” פני משה מפרש שהראשון הוא שאלה, והשני הוא מימרה. קצת צריך ביאור למה אומר כן. אולי לשון "עד כדון" משמע שהוא שאלה.
** אדם זוכה -
עיין בפני משה, במש"כ בג’. יש להעיר שגי’ זה לא רק משתבש קצת, כמו שאומר, אלא אומר דין אחד לגמרי. ותו"ת.
ולכאורה, המשך גמ’ מוכרח נגד גירסה שלנו לשני סיבות:
1. ממשיך גמרא לדון בקנין ד"א.
2. הראיה שמביא מן הקרא לא אפשר לפי קרא זה. ויש לדון, שאולי הוא שלו כיון שחברו קנה לו, ואינו ברשותו כיון שלא בא לעולם לרשותו, שהיה לעולם ברשות חברו, שקנה לו. ויש לדון, אז, מהיכי תיתי שהוא מציאה. ועיין לקמן בע"ה, שנתרץ לזה.
** ואני בעניי -
ואם תאמר במה מוקים אותו- במציאה; הרי איזה מציאה יהיה כל כך גדול. ויש לומר שלא מוקים אותו במציאה, אלא לומדים יסוד ממנו, והוא שיש לאדם יחס למה שהוא קרוב לו. יודעים מסברה שבמציאה זה יכול לקנות (ובדברים אחרים אי אפשר לקנות).
גם יש לומר שסובר שיטה זה שלומד מקרא זה שהדין הזה הוא כן אף במתנה. אם כן, אולי זה מתנה, ולא מציאה. עיין לקמן בגמרא ופני משה אם זה נכון.
** כא: שנים שהיו -
המילה באה מלשון כתישה, כמו גבי תבואה. אז, הוא דומה בשני משמעויות אלו למילת "pound” באנגלית (שעושים כן לתבואה, ויכול גם לומר ששני בני אדם עשו כך זה לזה).
** עוד היא בשלא -
לכאורה, היה אפשר לומר פשט אחר, והוא שכיון שהיו מריבים עליו, לא היה סיבת תקנה מתקיים, שסיבת התקנה היה כדי שלא ינצו, אבל כאן רבו עליו. ונראה שאם כן, תבטל כל התקנה, שכל אחד, כשרוצה החפץ, אף אם בדרך כלל לא ירב עליו, עכשיו ירב עליו, כדי לבטל התקנה. ותו"ת.
** רובה דר"י
- לא הבנתי למה מניח מחלקת בר"י. ותחשב.
** כב. היא גיטין -
עיין בפני משה. מעניין, שלכאורה, זה רק דין דרבנן. אם כן, מעניין שרבנן יעשו שהוא כאילו נדרש ההיקש.
** ד-ג כדי שלא -
כשיבואו- משמע שבוודאי יבואו עניים לקטטה. ותו"ת.
** יושבים ומשמרים -
ואם תאמר הרי אמר שהוא גזל כיון שלא ישבו. ויש לומר שישבו, ואף על פי כן, יקח מהם. גם יש לומר שיש חשש לזה ויש חשש לזה. גם יש לומר שיש כזה ויש כזה, ובכל ציור, יהיו מקצת שנגזל מהם, ומקצת שישבו. מה שיתן לקרוביו אז, אף שיש עניים אחרים הוא שיש פחותים.
** ד-ד תינוקות -
נמצא שדרך תינוקות הוא לשכב עד זמן מאוחר. אף היום, עדיין עושים כן.
** כב: ד-ו רבי יוחנן -
עיין ברש"י על בבלי (יב:) שמפרש שהוא משום איבה. אם כן, אין ללמוד מזה.
** ריש לקיש -
הראיה הוא כך. ריש לקיש מפרש שפועל לא היה קונה לבעל הבית אלא אם כן הוא כמו עבדו. אז, מקשה שיכול לחזור בו, ואז אינו כעבדו (אין לרבו שליטה עליו).
היה אפשר לו לומר פשט אחר, והוא שמניחים שפועל מגביה לבעל הבית. גמרא מניח שמה שלא אמר כן הוא מפני שסובר שאי אפשר, כיון שאין אדם יכול להגביה מציאה לחברו ולהקנותו לו.
ויש לדון, שהיה אפשר לומר סיבות אחרות למה לא אמר כן; למשל, אולי לא סבר שיכולים להניח שסתם פועל נוטל מציאה כדי לזכות לבעל הבית שלו. ותו"ת.
** כג. עני -
יש להעיר שאם ראוי ליתן זכה, אז צריך ביאור בשיטת חכמים. נראה שראיית גמרא הוא שאז צריכים לומר שום צד אחר (למשל, המצווה אומר שצריך בעל הבית להפקירו, ולא לזכות בו לעני), שיעשה שאי אפשר לחלק. ותו"ת.
** והעבד
- שאינו בתורת שליחות- ר"ל שאינו בתורת שליחות זה, שאינו בתורת גיטין וקידושין. אבל, הוא בעולם שליחות סתם, כמו שפשוט ממה שגמ’ היה מצדד לומר לעיל שמיירי בעבד. ותו"ת.
** יש קנין -
מניח שאז אין יכולת בידו להפקיר אותו. לכאורה, זה מפני שהוא קצת של לויים כדו’, שחייב במעשר. אם כן, לכאורה, יהיה אסור לו אף לאכול אותו. ותו"ת.
** כג: קל הקילו -
לא הבנתי כל כך מה שאומר פני משה, שנראה מסוף דבריו שאומר שאם כן, כל תבואה שלו פטור, ופשוט שזה גם בלקט ושכחה. אם כן, לשון גמרא מוזר.
** הקלו רבנן -
ק"ק, שלכאורה, פטור פאה הוא דאורייתא. ועיין בביאור גרח"ק.
** עליה -
אם כן, נמצא שהמחלקת ב"יש קנין…" הוא רק אם חייב או פטור כשקונה אותו מן הגוי כשהוא עדיין בקרקע. ותו"ת.
** ד-ז כד. תוך יד -
נראה שר"ל שנופל לתוך ידו. זה אומר שכשהם נופלים, אפשר שהוא אוחז בו למטה, ומה שהוא למעלה הוא כבד, והוא slanted כלפי חוץ, שאז נופל כלפי חוץ.
** כד: ישראל שעקרו -
צריך לחשוב על סברה זה.
** יהיה -
יש להעיר שבדרך כלל, זה אומר שאותו חפץ נשאר בהווה. כאן, לא ידוע שהוא אותו חפץ. ותחשב על זה.
** פרק חמישי ה-א אומדים -
עיין במה שפירש בכדי נפילה. עיין רש"י בב"מ שלא פירש כן. צריך ביאור, לפי פני משה, מהו החילוק בין שני השיעורים שבמשנה.
** קנס -
יש לדון מה עשה רע, שהרי יתן מה שהוא דרכו להיות לקט:
1. אולי אפשר שהיה יותר לקט. יש לדון, שגם אפשר שהיה פחות. אז, בין הכל, לא עשה רע או טוב.
2. אולי עושה שצריכים להמתין יותר זמן.
ודע שעל זה תלוי, לכאורה, אם דין חטים על גב שעורים, וכדומה, הם גזרות ממש או לא פלוגים. יש להעיר שיש לגמרא, על כל פנים, סברה לומר כצד ראשון, שאי לאו הכי, לא היה חטים על גב שעורים חידוש. ותו"ת.
** כה. שביעית -
מניח שהוא מפני ביטול מעשר. גם אפשר לומר שהוא כדי שלא יהיה השנה שבו אי אפשר לזרוע יותר ארוך, שזה יעשה שקשה להיות מזון לכל אחד. ותו"ת.
** הפקר בית דין -
ממה שיש לגמרא צד שחייב בהפקר, צריך לומר שלא חל ההפקר מן התורה. אם כן, לכאורה, צריך ביאור מהו חידוש הקרא. לכאורה, אין לומר שלא נלמד מקרא, שאם לא כן, יהיה גזל, ואז הוא נגד דין דאורייתא בקום ועשה. אז, צריך לומר שלומד מקרא. נראה שצריך לומר שכאן תורה נתן להם כוח- לא הכוח לעשות חלות, אלא ללכת נגד התורה בקום ועשה. ותו"ת.
ואם תאמר אם כן יתקנו אף פטור מעשר. ויש לומר שרק תיקן שיכול ללכת נגד תורה בקום ועשה בדיני ממון, ולא בדיני מעשר. גם יש לומר שכיון שהוא תוצאה של דיני ממון, יכולים לתקן פטור מעשר, אבל אין סיבה לו, שכבר מקויים סיבת תקנה בעשייתו הפקר. ותו"ת.
** כדי נפילה -
לא הבנתי מה אומר גמרא, ואיך מוכיח מזה שקאי על כור של תבואה. עיין בפני משה.
** ה-ב ראשה
- זה מיותר, ומשמע שמוסיף שלא רק צריך שאם נכוף זה לזה וזה לזה באמצע, יכולים לקצור את כולם כאחד, אלא צריך שזה בא לזה ואז נקצרים כאחד, והוא שנקצר עם קצירת זה הרגיל. ותחשב על זה.
זה אומר שעושים כך:
ולא כך:
** כה: סביב -
נראה שר"ל שאם אינו קרוב לקמה, אלא כל מה שקרוב לו הוא מה שכבר נקצר, אלא עדיין קם, ששכח אף אותם, כיון ששכח הרבה שעומדים ביחד, ראוי הוא לחזור לו, ואינו שכחה.
אין זה דומה לפנימי שיבאר גמרא לקמן. פנימי הוא כשאינו קרוב לקמה די, ואינו קרוב לקמה אחר שבקציר, שאין כל כך קמה די לעשות שאינו שכחה. אלא קרוב לדבר שהוא קרוב לקמה די.
** היתה יכולה -
ואם תאמר איך זה אפשר. אינו קשה, שיכול להיות אם אחד יותר גדול מחבירו, שזה מגיע למקום קצירה של זה, זה לא מגיע למקום קצירה של זה. ותו"ת.
** אם שוהה -
ביאור כל גמרא זה הוא כך. אם יש שישי, צריך שיעשה החמישי לגמרי קודם שיעשה הששי, שאז יודעים שלא היה כוונתו לחזור מששי לרביעי כסדר.
אז, מתחילה לא רואים ששכח, שאולי כוון לחזור מששי לחמישי, אבל אחר שהתחיל ליטול מחמישי, אחר שעמר, רואים ששכח.
** כו. שנים -
צריך ביאור למה זה מהני, שעדיין אפשר שהאחר הוא לקט. עוד קשה, שיש לחוש שמה שנתן הוא מעשר. ותחשב.
** עשו שאינו זוכה -
צריך באור מה זה. עיין בלשון פני משה (“עשו כאילו זה נטל ונתן"). גם יש לדון למה יהיה צריך חילוף. ותחשב.
** ת"ק -
ר"ל, נותן אחד לחילוף, ואז עושה מה שאומר תנא קמא לשני. ותו"ת.
** כו: ה-ג מידל א"א -
לא הבנתי למה אי אפשר לשום זה.
** עד שלא
- גם היה אפשר לומר שמחריב את הזרעים. משמע שאילו היה יכול עני לבוא לו מיד, היה יכול להציל אותו, אלא שצריך לשהות, ואז הפירות נפסדים.
** ולמי הוא -
עיין בפני משה על מה זה קאי. לכאורה, אי אפשר לפרש כן למי שגורס קטע זה של משנה אחר גמרא זה.
ויש להעיר שבמהדורה ישנה, גורס קטע אחר זה, אבל בפני משה, גורס לפני זה. במהדורה עוז והדר, בשניהם גורס אחר זה. אם כן, קשה על פני משה לשיטתו. אז, נראה שאינם נכונים.
** ה-ה כז: פועל -
עיין במה שבאר. מעניין שנקרא גוזל לבעל הבית, כיון שרק חושב שהוא גוזל לו.
** ה-ו קצירך -
יש לדון איך יודעים שלא לדרוש להיפך, שכדי שלא יהיה שכחה צריך שבעל הבית ופועל זוכרים אותו. ותחשב.
** אחרים -
לכאורה, ר"ל שאחר רואה אותו וזכור, ואף שבעל הבית ופועל שוכחים. זה מעניין. לכאורה, צריך לומר שאין עני בכלל זה, שאי לאו הכי, אי אפשר לעני לקחת לעולם שכחה.
** ה-ז ממנו לגורן -
יש לדון למה:
1. כבר היה שעת שכחה.
2. לא כיוון לזה מתחילה.
ותחשב.
** כח. פרק ששי ו-א יש לדון אם
בית הלל סוברים שאינו הפקר, או שאף שהוא הפקר, חייב במעשר.
לכאורה, אין כל כך נפק"מ, שבהפקירו, אמר שמתיר לכל אחד לקנות. נראה שאולי יהיה נפק"מ באיך יחזור בו. ותחשב.
לשון פני משה, שרק מזכיר נפק"מ לענין פאה וכדומה משמע כצד שני. כן קצת משמע ממה שהוא נשנה בזרעים, ולא בנזקין, בדיני קנין. ויש לדחות, שלא מצאנו דיני קנין כל כך סדורים (כמעט לעולם באים באגב).
ועיין לקמן בגמרא.
** אגב, נראה שאפשר
שמה שאומר שם של רב אילא "לא" או של רב אבון "בון" לא היה רק מפני שמקצר, אלא שכך קראו להם, שהיה כמו nickname. זה יבאר למה רק תלמוד של א"י עושים כן לאותם אומראים, שבני בבל לא ידעו אותם כל כך טוב, ולא דברו בnickname שלהם. ותו"ת.
** רבי מאיר -
לכאורה, ר"ל שכיון שחלות הפקר נעשה על ידי סילוק זכות, כיון שמסלק את עצמו, ממילא מותר לכל. זה אומר שלא רק כן נעשה הפקר בדרך כלל, אלא לא מניחים שכשפורט שרוצה תוצאה שלא היה נעשה על ידי הפקר כזה שעושה הפקר חלוק. אולי אי אפשר לו לעשות הפקר חלוק. ותו"ת.
עדיין צריך ביאור איך רבי מאיר מבאר שיטת בית הלל. כיון שנמצא שהפקיר לכל, צריך ביאור למה חולק, לרבי מאיר, בית הלל על בית שמאי, שהרי עשה חלות של הפקר רגיל. וצריך ביאור.
** כח: לזמן -
עיין במה שבאר פני משה. יש לדון ל"ל חוששים שגופא עושה כן כדי להערים. אולי לא חוששים שיבין לעשות כן. צריך ביאור.
** לזמן -
אז, קשה מה שהקשה ר"ז שבטלת הפקר, שיש עדיין הפקר כשמפקיר לזמן.
** בר בי רבי -
צריך ביאור מהו ביאורו, שצריך ביאור למה מחלקים, ויותר קשה, צריך ביאור איך מחלקים לשני שורות, ששורה הוא שלש. אולי אמר גמרא שהוא שלש רק לנסות לתרץ, אבל אינו צריך להיות כן (ואולי לעולם ידע שיש של שלש ויש של ארבע. ותו"ת.).
** כט. ו-ב עיין בפני
משה שכ’ שיש לתרץ לפי ר"א וראב"ע. יש לדון בזה. מפני משה, נראה שהקושיה אינה איך יכול להיות הדין כן במה שאינו מסויים (שאז היינו יכולים לומר שלרבי אליעזר אינו קשה, שיש דבר לצרף למה שהוא מסויים), אלא איך משנה כולל אותם ביחד, כיון שזה מסויים ביותר, וזה לא כל כך מסויים. אם כן, עדיין קשה, שעדיין לרבי אליעזר צריך מה שהוא מסויים.
נראה שהבעיה בכוללם יחד הוא כך: פשוט שאין סיבה שווה, שהרי זה יותר מסויים מזה. אם כן, כיון שאומר שאין כל הענין מה שהוא מסויים, יכול זה להיות הטעם. אז, אינו קשה עוד למה כולל שניהם ביחד. ותו"ת.
** עיין בפני משה
שמביא שהברייתא הוא מתוספתא. עיין במשנה כתובות, שגם אומר כעין זה. אולי לא אומר אותו לשון ממש, וגמרא מביא את זה מן התוספתא. ותו"ת.
** כט: ו-ג יחיד -
צריך ביאור מה אומר, שאם זה מתחיל מקצה זה וזה מתחיל מקצה זה, גם יסיימו בזמן אחד. אם רק בא להוציא ל"ל יתחלו מראש אחד, לכאורה, יש עוד בעיה, והוא שרק צריך אחד לקצור. ותחשב. וצריך ביאור.
** מנין -
שתלינן- יש לדון אם חידוש התורה הוא שספקו להקל או שבוודאי אין זה מתת עניים (שהמתנה הוא רק מה שהוא וודאי).
מלשון פני משה (בד"ה מנין לראשי שורות) משמע כצד ראשון. ותו"ת.
** כי תקצור קצירך -
עיין בביאור פני משה בזה. צריך ביאור קצת איך ממעט מזה, שרק אומר שצריך להיות שכבר כוון לקצור אותו. צריך ביאור איך ממעטים ספק מזה; ספר יהיה רק ספק אם זה נכון. ותחשב.
לולי פני משה, היה נראה לומר שממעט מקום שלא קצר, שאם קצר מקום, ולא קצר כולו, ששכח ממנו, הוא שכחה, אבל אם לא קצר אותו מקום לגמרי (ולכאורה, צריך להגדיר), אינו נעשה שכחה.
נראה שפני משה קצת לשיטתו בזה, שאילו היינו דורשים כמה שכתבתי, היה משמע שאין בו דין שכחה, בוודאי, ולא שתלינן לקולא, כמו שאומר פני משה. ויש לדון. אז, פני משה לא מפרש כן. יש לדון, כמובן, מה גורם למה. ותו"ת.
** סוף שורות -
צריך ביאור למה נחשבו בזה יותר שיהיה שכחה; להיפך, לא נאמר עליו שהוא בשיבה, שאינו אחריו. יש לומר שכיון שהיה עומד להגיע לו, יותר נחשב או יותר נראה כשכחו, אבל אם לא התחיל בו, לא היה עומד ונמנע. ותחשב.
** עימר מזרח ומערב -
כיון שהוא אותו בעיה, צריך ביאור למה שואל אותו שני פעמים. אולי כן הוא דרך הירושלמי.
** ל: ו-ה ובלבד -
יש לדון אם הוא גם לענין מין אחר. לשון "ובלבד" משמע שהוא רק לענין שבלים.
** ו-ו מה אם -
מה שלא לומד מקמה שמציל על קמה הוא ששאני התם שהוא מינו, ואז אין ללמוד שיציל עומר את קמה. אם כן, לא היה צריך מעלה זה לקל וחומר, והיה אפשר לומר מעלה של אותו מין (שעומר יציל עומר כיון שהוא אותו מין). הדרך לתרץ יהיה שהוא מעלה ששייך רק גבי קמה (למשל, שענינו הוא שהם אחד, ורק קמה, שמחובר לקרקע, ואז להדדי, יכולים להיות אחד. ותחשב עוד.).
** רשות בעל האמצע -
יש לדון אם רק ר"ל שאינו ממש סאתיים, שמסתמא לא יהיה כולו שלא, שיהיה ממנו לעניים, או דבר אחר (למשל, שעני יותר מיוחס לו כיון שעומד לקחת חלק ממנו). יש נפק"מ אם לא עומד לפחת מסאתיים, שמסתמא לא יהיה יד עני ממעטו כל כך. ותו"ת.
** לא. ו-ח לא סוף דבר -
לא הבנתי, שהיה נראה לומר שיש יותר חידוש גבי גסים, שהרי היה מחפש לגסים, ושכח את אלו, ולא לדקים. ותחשב.
** פרק שביעי ז-א בשמו -
יש לדון אם צריך להיות כל אלו או רק אחד מאלו. עיין בפני משה לקמן. לא הבנתי כל כך מה אומר, אבל נראה שהוא נוגע לזה.
** בשמו -
משנה רק מזכיר אם הוא לטוב. יש לדון אם הוא אף לרע. הענין הוא שבוודאי יזכיר אותו. כאן, יש לדון, שאולי מה שמזכיר אותו הוא מפני שחושב על פריו ביותר כיון שהוא יותר טוב. ותחשב.
ונראה שיש עוד דרך, והוא שלא עומד לזוכרו ביותר, אלא שזכירתו יהיה יותר, אם זוכרו. זה אומר שאם יזכור, יזכור קרק’ יותר מסויימים של אותו דבר ששכח. אז, אינו כל כך נשכח, שיכול להיות יותר זכור.
אז, לכאורה, אין הקרק’ צריך להיות בטוב (אם לא שנאמר שאין רוע אילן דבר שחושב עליו כשזוכר שצריך אילן (שהניחא אם הוא טוב, חושב, “אבדתי אילן טוב,” אבל אם אינו טוב, חושב "איבדתי אילן"). ותו"ת.
** לא: אמר’ לא -
בהרבה מקומות, כופל פני משה את שמו לומר שהוא רבי לא (רבי אילא), ואין "לא" חלק מן המימרה.
** ד’ כיפלסים -
יש להעיר שלעיל אמר סיבה (שיעשה שני שורות). לכאורה, זה לא שייך כאן. ותחשב.
** נשמעינא מן הדא -
ק"ק ל"ל נביא ראיה מרבנן שחולקים. ותחשב.
אולי מניחים שאינו מחלקת כלל.
** אלא כך הוא
- לא הבנתי מה אומר כאן.
** לב. ז-ב ממשנה ופני משה
משמע שצריך להיות נטוף ושל סאתיים כדי להיות שאינו לקט אף אחר שהתחיל בו. ואם תאמר למה חלוק מעומרים, ששם רק צריך שיהיה סאתיים. ויש לומר שכאן כבר התחיל.
** נודיין -
לא הבנתי זה כל כך.
** מסייע
- עיין בבביאורו. שניהם, אז, אינם שכחה, והחילוק הוא רק שכשאומר, “אינו שכחה" ר"ל שאינו שלו. דחוק. צריך ביאור.
** כל זמן -
מסתמא- עיין במה שפירש. גם יש לומר שכל זמן שיש לו לנקוט מה שתחתיו, אין רביעה מתרת, שהרי ילקוט מה שבאילן, אלא שעדיין צריך לנקוט מה שתחתיו. זה אומר שמה שנוקט מה שהוא תחתיו תחילה, שהוא יותר קל. ואם תאמר למה שהה למה שהוא תחתיו. ויש לומר שמה שזה עדיין לקט הוא סימן שנעשה לקט יותר מאוחר. ותו"ת.
** לב: ז-ג שנייא -
צריך להגדיר, שאם נאמר שצריך להיות שאין דבר שם כשמתחיל ליפול, אז, צריך להוקים משנה שלנו בכעין זה, וזה דחוק.
** אם ספק
- עיין במה שפירש. דחוק, שלכאורה, אינו ממש ספק, אלא דבר שהוא בין השני דברים שהם כבר מבוארים. ותו"ת. אולי הוא ממש ספק, ופוסק כן מדין ספק. אם כן, הוא הדין גבי ספק ממש, ואותו הדין אומר. היה אפשר לומר, אז, שמשנה רק אומר ספק ממש, אלא שפני משה מדייק, מסתמא, ממה ששאר המשנה בא לבאר דין צורתו. ותו"ת.
** לג. מרכיבים -
משמע שהיו מרכיבים הטלה על גבי הגמל. כמובן, זה מוזר, שהיה לו ללכת. אולי היה שמן ביותר, והיה קשה לו. צריך ביאור איך גמל יישא כבש גדול כזה.
** אייתון קומי -
יש להעיר שגמרא דן (מנחות, או ראש השנה) בזמן שמתחילים לזרוע לעומר. קשה מגמרא זה. יש לומר שזה היה נס, ואין סומכים על הנס. וצריך לדון באותו גמרא.
** והייתי עולה -
כמובן, זה מזכיר "Jack and the Beanstalk.”
** ונפשח
- אף על פי כן- לכאורה, ר"ל, "אף שהיה רק חציו, שכבר נחלק….”
** יש שני מעשים
עם רבי. צריך ביאור למה רק גירה בארץ אחר ראשון. אם נאמר שמעשה ראשון שאומר גמרא קרה תחילה, צריך ביאור איך קרה השני. אולי בראשון ביטל רק שהיה גדול, ובשני ביטל אף מה שהיה מהר.
נראה שזה גם כן יבאר בטוב למה לא היה רבי יודע, שאף ששמע אותו, אולי, סבר שביטל אותו.
** לג: שותף -
קצת צריך ביאור למה נאמר שהוא שותף, שלכאורה, תורה אומר שהפרט הוא של עני, ואם כן יקנה פרט, וזהו. אולי קנה האילן לפרט שלו, וזה עושה, עד שבא לו פרט, שותפות. קשה, שאם כן, יעשה, לכאורה, שותפות בכל. אולי ר"ל שצריך לתת לעני פרט, אבל אינו שלו עד שמפקירו לו. עד אז, הוא רק צריך לבוא לו, והוא רק שותף בו. ותחשב.
** הגע עצמך -
איני יודע אם לשון זה אומר שיקשה קושיה, אבל זה לא נראה כקושיה, שלכאורה, אין הוכחה שאין דין זה נכון.
** רבי יהודה -
גמרא כאן רק מתרץ לסתירה שבשיטת רבי יהודה. עיין לעיל בביאור שיטת רבנן.
** ז-ה שביעית -
קצת צריך ביאור, אז, למה יחייב בפרט. אולי יש פרט בשביעית.
** אם הייתי
בריסקר, הייתי אומר שלבית שמאי, יוצא שיש שני דינים של כרם רבעי, דין כרם רבעי, ודין מעשר שני.
** לד. פרט לנטע רבעי -
יש לדון למה צריך קרא למעט אותו, שמהיכי תיתי לרבות כיון שהוא לא נלמד ממעשר שני. ותחשב. אולי אומר מקור אחר לומר שלא נלמד. ותו"ת.
** יש בהם מעשר עני -
לא הבנתי מה לנו בזה, שלכאורה, קושיית גמרא מיוסד על מה שאומר גמרא שזה נלמד ממעשר שני. אם כן, יילמד ממעשר שני אף לפטור אותו בשנה ששית, ומה לנו שמעשר אחר נוהג. אולי ר"ל שפטור מעשר שני בא ממה שיש חיוב מעשר עני, ואף מגדירים פטור שלו להיות שניתן מעשר עני במקומו, אבל אי אפשר לתת מעשר עני במקום נטע רבעי. חוץ מן החידוש שיש בזה, גם יש לדון ל"ל נוכל לומר שמעשר עני הוא במקום שניהם. אולי הוא מפני שאין זה מעשר, ואז אין מ"ע יכו"ל במקומו.
** אתייא
- לא הבנתי כל כך איך מפרש פני משה את זה. ותחשב.
** לד: ולא ר"י היא -
לא הבנתי, שמשנה אומר שיטת ב"ש, ואין צורך להניח שסוברים כרבי יהודה בשיטה אחרת שיש לו. רק יודעים שר"י ג"כ סובר כב"ש. אם כן, עדיין יש לשאול אליבא דבית שמאי מהו הדין. ותו"ת.
** ז-ו כי תבצור -
מעניין שאין אומרים שאחר בצירת עולל ראשון חייב. יש לומר שלא נחשב בצירת עולל בצירה. גם יש לומר שכיון שלא חייב תורה בעוללות כבר, לא חייב בעוללות כלל. לא נראה כן, שרק לא חייב בו תורה קודם זמן חיוב שלו, כמו בכל שדה. ותו"ת.
** המקדיש שדה אילן -
לא הבנתי כל כך למה נחלק לומר שרבנן חולקים על בני יריחו רק בקורות. ותח’.
** דלא היא
- לא הבנתי למה פני משה מניח שהיו רבנן מסופקים, ולא שחשבו בוודאי שבני יריחו טעו.
** לאוכלו בלי פדיון -
לא הבנתי כל כך מה אומר פני משה לבאר את זה. אולי הענין הוא שאם נותן ממון לו, הרי הוא (נראה כאילו) סחורה בפירות שביעית. ודחוק. ועיין בגרח"ק.
** לה. ליתה הדא
- עיין במה שפירש. אם כן, לכאורה, צריך ביאור למה הוא אף אם לא יכול ליטול אותה, שאף שם נאמר שכיוון לעשות כן ולא עלה בידו. אולי לא קורה כן בדר"כ. גם יש לומר שכמו טעות של שכחת פרי עושה דין זה, כך כל טעות שגורם שצריך לחזור לו עושה דין שכחה. זה מחודש. ותו"ת.
** פרק שמיני ח-א רביעה -
פני משה מבאר שאין זמן זה קבוע. אם כן, לכאורה, לא תלוי בזמן שבדרך כלל יורד הרביעה, אלא בזמן שיורד. ותו"ת.
** לה: ח-ב נאמנים -
לא הבנתי כל משנה זה כל כך על פי דינים של נאמנות של עד אחד באיסורים. לכאורה, היה להיות כל אחד נאמן כיון שבידו לתקן אותו. אם כן, לכאורה, פשוט שיהיה נאמן בכל זמן כאן. אפשר לבאר במשנה שאם יש מוכיח כנגדו, שמה שאומר מוזר, לא נאמן נגד זה. עדיין לא מובן כל דיונים כל הגמרא.
** מתניתא -
לא הבנתי הדיוק שמדייקים, שלכאורה, מה שלא הזכיר מחלקת של ר"א אינו מוכיח שאין מה שאומר תלוי במח’ של ר"א. אפשר שר"ל שאם ר"ל כר"א, היה לו לומר ציור של רבי אליעזר (לכאורה, כדי שיהיה יותר פשוט[fn:10]). ותחשב.
** ראה
- כשיעור- לכאורה, אין זה שום ראיה, שרק הפריש מעשר ממה שיש לפניו, אלא שר"ל שאומר כן, וגם אפשר להיות, שהוא כשיעור….
** לו. ח-ד חזקיה… אבוי -
רש"י כ’ שהיה אביו רב חייא.
** למי נצרכה -
יש לדון למה, למעשה, הוא כן. ויש לומר שיש לזה מעלה יתירה, שדוחה הרע שבו. היה אפשר לומר שאינו כל כך רע כבצלים, אבל לשון פני משה משמע יותר כצד ראשון.
** בשר חי -
דעתן יפה- נראה שאולי זה לשון סגי נהר לומר שהוא מקולקלת.
** לו: שליש -
יש להעיר שפני משה אומר שזה שליש לבר. זה מחצה. מעניין, שיותר מצוי שנאמר לבר אם מוסיפים אותו מנין עליו. כאן, לא עושים כלום, שהולכים מחצי קב לרובע. ותו"ת.
** הנותן נותן -
צריך ביאור מהו החידוש בזה, שפשוט שיוכל לתת. יש לומר שאומר שצריך לתת. לא נראה כן מפני משה, שכ’, “אינו צריך לחוש.”
אז, נראה שהחידוש הוא שיכולים לתת מתמחוי.
** ח-ו אין מדקדקים פרנסים-
קשה, שאם אין מעמידים פחות משלש, איך נגבה בשנים. נראה שלא מכוון למה שאומר בבלי שממנים שנים, ששם קאי על מי שיש לו שררה. כאן לא אומר כן מחמת שררה, אלא מחמת שדנים ומזכים ממון.
ואם תאמר הרי קל לומר שצריך שלש כיון שהפקר בית דין הפקר. נראה שזה לא יהני, שאין רק בעיה של ממון כאן, אלא אף בעיה של איסור, והוא של צדקה, שצריך לדון מי לפרנס. ותו"ת.
** וחרנא אמר -
דפוס ווילנא גורס כאן: “חד אמר מדקדקים בחיי נפשות וחרנא אמר אף בכסות אין מדקדים.” לכאורה, זה מוזר, שהראשון סבר שרק בכסות אין מדקדקים. אז, לשון "אף" הוא מוזר על כסות. צריך לומר שחולקים בשני דברים:
1. אם צריך לדקדק במזונות.
2. אם יותר פשוט שידקדק בכסות או במזונות.
אפשר לעשות שאינו שני מחלוקתים, שאפשר שיש לכולי עלמא שום מקור שאין צריך לדקדק על כסות. מי שאומר שיותר פשוט לדקדק בכסות (השני) יאמר שאז לא צ’ לדקדק בשני הדינים. מי שאומר שאינו יותר פשוט (ראשון) יאמר שרק אין צריך לדקדק במזון.
בדפוס ויניציא (וכן כ’ בעוז והדר, וכן כ’ בפני משה) גרס, “חד אמר מדקדקים בכסות ואין מדקדדקים בחיי נפשות. חרנא אמר אף בכסות אין מדקדקים.” זה יותר מובן, שאז חולקים באם מדקדקים בכסות, שזה אומר שמדקדקים, וזה אומר שאף בו אין מדקדקים. ותחשב.
** ח-ו לז. ואת כלי -
עיין בביאור פני משה. נמצא שיכול ליטול צדקה ולשאר כליו, ויכול ליטול לקט ולשאר כליו, ורק אם לוקח צדקה, וגם משאר, לא יכול ליקח לקט. צריך לחשוב על זה.
** ודאי איתתא -
נראה שמניח שמיירי בעדיין נשואה לו, שקורא לה אשה, ואז צריך לומר שלא דוחקת, שאינה יכולה לגבות כבר.
** מן מאתים -
עיין במה שפירש פני משה. יש לציין לדפוסים (כפתור ופרח) שגורסים "מן מאתים פחות מעט.”
** וכי ערומה
- עיין במה שדורש מממה שהם מיוחדים לה. נראה שר"ל שהם כל כך חשובים עד שלא תלווה לאחרים.
** שמואל ערק
- מחמת כעס- יש לדון כעס של מי היה.
** לז: מעניין
שמניח גמ’ שיכול אדם שלא זוכה בצדקה ליטול צדקה לתת אותו לעניים אחרים. גם קצת יש  לדון למה עושה כן, שצדקה יעשה כן. אולי לא האמין שצדקה יוכל למצוא מי רמאי ומי אינו רמאי. יש לדון אם זה יהני אף לק’ ראשונה. ותו"ת.
[עיין בפני משה במה שמבאר ב"גדול ממאתים,” שמאתים ר"ל מעין. עיין בסנהדרין קה: שאומר כעין זה. ותו"ת.]
* Footnotes
[fn:1] יש לדון איך ידעו שאומר כן קרא. ואולי הוא מסברה. ותחשב.
[fn:2] יש לדחוק ולדחות שחוששים שיראה שאמר שהוא חייב, אבל יזכור שלא אכל כשיעור (שלא יזכור ששינה השיעור), ואז יבוא לומר שטעה. ותחשב.
[fn:3] קצת קשה, שמביא קרא לזה. צריך לומר שהוא רק אסמכתא. ויש להעיר שבאמת בבלי מביא קרא לחומש (אבל אולי סובר שאינו הלכה למשה מסיני או תקנה. חושב אני שלשונו משמע שהוא תקנה. עדיין יש לדחות שדרשו משם שיכול לתת חומש, ואז אסרו רק יותר מזה.)
[fn:4] ואגב, עיין בשיח שי על חגיגה (גלגל רביעי), שהוכחנו שבבלי חולק על תלייה זה. ותו"ת.
[fn:5] אף שהיה בן אחות, ולא בן אח.
[fn:6] צריך ביאור למה יהיה נקרא על שם אמו. ותחשב. ואולי לא רצו לקרוא לו בן אבא, שהכל הם בני אבא.
[fn:7] יש להעיר שאם הוא שם האם, אולי אינו Muhri אלא Mary. ותו"ת. ויש להעיר שמצאנו שמות של אנשים שהם מרי. אינו כל כך בעיה אם שם זה דומה לשם של אשה, שמצאנו כן אף בשלום (כמו אימא שלום). ואם השם הוא Mary, אז אולי יש לומר שהם שני שמות חלוקים, אלא שנכתבים שווה. (ואולי הוא כן אף באימא שלום, שאולי הוא Sheeloom).
[fn:8] ויש לדון, שאולי קנה השדה ליותר.
[fn:9] ונראה שהשואל לא הבין סברה זה, ואז היה אומר שהוא אף מעשה שראה מרבו. ותו"ת.
[fn:10] גם אפשר שהוא סימן, שלאותו סיבה שבחר בו ר"א, אף הוא יבחור. יש לדון, שאולי זה נשאל לר"א. ותחשב.
