** פרק ראשון א-א א. יש להעיר
שיש שני מיני שיעור המנויים במשנה:
א. הגדרת חפץ (כמו שוויותו).
ב. מנין חפץ או מעשה.
** תלמוד תורה -
יש  להעיר שיש לו שיעור, שחייב ללמדו ביום ובלילה. וצריך לדון מה נחשב שיעור ומה נחשב חלק מעיקר המצוה (כמו שלמשל אין אומרים שיש לתרומה שיעור כיון שצריך להפריש חטה אחת).
** גמילות חסדים -
יש להעיר שמשמע מתחלת דבריו שמחלק בין אי חייב בכל זמן שבא או לא. מהמשך דבריו נראה שמחלק בין אי יש שיעור קצוב שצריך לתת או לא. ותו"ת.
** מפני המחלקת -
יש להעיר שלכאורה מבואר מזה ש"אין לה שיעור" משמע בין למעלה בין למטה. נראה שיש לדון למה:
א. אפשר שסתימות הלשון משמע כן (שמשמע שאין לו שיעור כלל).
ב. אפשר שמה שמונה תנא אחרים שאין להם שיעור משמע שכוונתו למנות אותם שאין להם שום שיעור.
ג. אפשר שרוצים שידמו, ולא שאי אפשר לומר זה בלשון או בדין משנה.
גם צריך לדון אם הבעיר הוא שסובר שאינו נכון או שלא רוצה למנות מחלקת (כבתחלת יבמות. ויש להעיר שכנראה זה בא ביותר במנינים). אם כשני, אפשר שהבעיא הוא רק שנראה כמונה מחלקת, שאולי יחשבו בני אדם ש"שיעור" ר"ל אף למעלה, ויהא מחלקת.
** אבל אין אדם -
יש לדון אם הבעיא הוא שאז אין דין משנה נכון או שאז רק לא דומה (ואולי לא במה שיש לו שיעור, שאולי אין זה נחשב שיעור. וצריך להגדיר איזה חילוקים ימעט דבר מהיות במשנה).
** אין אדם
- עיין בטעמו. לולי זה, היה מצי לומר שהענין הוא שצריך להרימו ולהפרישו, ואז בהכרח ישאר. (וזה אינו אומר כן, שזה מחלקת בעירובין. ועיין שם.) לכאורה לא ייחשב שיעור אז, אלא חלק ממצוה. אם כן, אולי כן סובר ר"א.
** פאה -
יש לדון אם אומר שאינו מיעוט כיון שלא שייך או שיכול לעשות כולו פאה, כעושה כל מה שראוי ליעשות פאה לפאה. ותחשב.
** פאה -
מעניין שאי אפשר להפריש פאה לפני חיובו, שיכול להפריש תרומה לפני מרוח. אולי אז יש כבר מקצת סיבות. גם יש לומר שהבעיא בפאה הוא שאין מעשה לעשותו פאה, שהמעשה הוא מניעה מלקצור כשהיה לו לקצור, והוא כשגילה בדעתו שקוצר שדהו. ותחשב. (ועיין לקמן בגמרא, שאולי תלוי בדין נשרף.)
** אפשר -
קצת קשה למה לא פירש שהוא פלא כיון שהפריש עליו כל שדהו.
** א: עומרין -
יש לדון למה אין גמרא שואל גבי משייר בשדה כמה צריך לשייר, ולמה שם יותר פשוט. ותחשב. ואולי פשוט שכיון שלא היה לעולם חייב, אינו צריך להפריש עליה, ורק יש צד שיחייב כיון שכיון שנקצרו כיולם, נעשים חד כלל, שיש שם שווה עליהם, ואז יכניס בכללם לחייב. גם יש לומר בצד שנכתוב לקמן בס"ד.
** עומרין -
יש לדון אם חיוב עומרים הוא אותו חיוב של פאה או חיוב חלוק, ורק חייב אם לא הפריש פאה. אולי ההוה אמינא לחייב לשיבולת הוא צד שני, שאז אינו אותו חיוב של פאה, ואולי מה שהוא חלק מן השדה, אף אם לא היה חייב בפאה, יתחייב בו.
אפשר שר"י אומר כראשון או שאומר שכיון שחיוב פאה יכול לעמוד במקומו, ואף שאינו על שיבולת, צריך לומר שאף זה אינו על שיבולת.
** אין להם שיעור -
יש לדון אם מפרש המשנה או מפרש הדין. מפ"מ על המשנה משמע כשני. כן נראה, דאי לאו הכי. צריך ביאור למה חלוק מתרומה. ותחשב.
** אית תנא
- מהמשכו, נראה שסבר שחולקים שני ברייתות. לולי זה, היה אפשר לומר  שחולקים שני שוני ברייתא מה אמר ברייתא. אם כן, אולי קושיית גמרא מן המשנה הוא שלא נניח שברייתא חולק אם יש דרך אחר לגרוס בו.
אגב, יש להעיר שיש דרך אחר להבין הקושיא, והוא שאולי כיון שברייתא זה בא לפרש משנה זה, לא יאמר דבר שיגרום שיהא סתירת משניות. ויש לדון אם מפרש משנה זה (עיין לעיל. ויש לדון, שאולי אף לראשון נחשב מפרשו.)
גם אפשר שלא מקשה,אלא רק דן במה חולקים. ותו"ת.
** אפר -
יש להעיר שיש לאלו שיעור, שהוא כדי שיראו. ואולי צריך לומר שזה מ"עצם המצוה.” וצריך ביאור.
** ב. ר’ ייסא -
מה ששם "יוסי" נעשה "ייסא" (אם לא שנאמר שהם בני אדם חלוקים, ופני משה לא גורס יוסי בגמרא) משמע שאומרים חולם כמו "אוי,” כמו שעושים בני ישיבה, ולא כמו שעושים בני YU.
יש להעיר שגם מוסיף אל"ף כמקום יו"ד, ואין מי שאומר שניהם שווה. ואולי יש חיריק תחת האל"ף. ודחוק.
** לא חכמים -
לכאורה, אי אפשר לומר שאלו הם דינים דרבנן, שיש שיעורים שמקילים על דיני תורה (לכאורה, אף בקום ועשה. ויש לדון. ותחשב.). אז, נראה שרק ר"ל שמסרן הכתוב לחכמים.
** רבי הושיעא -
לכאורה, אז, אינו מקשה לר"י, שאין הכרח שסובר כר"ה.
יש לדון למה אין להקשות ען לכולי עלמא, שלכאורה רק מקשה איך יש כח לרבנן לעשות שיעור. ונראה שלש מהלכים:
א. אפשר שאי לא כתוב, יש לרבנן כח, שמה שלא כתבו אומר לנו שניתן לחכמים להכריע, כמו שמצינו בבכור ובכ"מ.
ב. אפשר שקושיית גמרא הוא שכיון שכתבו בפירוש, אי אפשר לרבנן לתקן נגדו, כמי שסובר שאין לרבנן כח לתקן נגד מה שנכתב בפירוש.
ג. אפשר- ואולי זה רק ביאור של צד שלישי- מה שאומרו תורה (אולי מפני שהוא מיותר) מגלה שיש צורך יותר קטן בגידול שיעור כאן מבמקומות אחרים. ותחשב.
** כל השיעורים -
אין זה מוכיח שאף זה מדאורייתא (ואולי מדייק מלשון כל, שאז יש הוכחה. לא נראה, שלכאורה דין כזית בברכת המזון אינו כן), אלא שאין שיעור כל מדרבנן. ותחשב.
** צריך לרשום -
יש לדון מה זה אומר:
א. מביאור הגרח"ק נראה שהוא שצריך לכתוב שיעור שאכל, ולא רק אי חייב קרבן כיון שאפשר שישנו את השיעור, ויצטרך לידע אם חייב כפי שיעור החדש. כן כותב בבלי ביומא (פ.), אבל יש להעיר ששיטת הבבלי בדרך כלל הוא שכל השיעורים הם הלכה למשה מסיני, ואז כשאומר כן, אי אפשר שאומר אותו דבר שאומר הירושלמי כאן, אלא אומר שאפשר שיכריעו חכמים ששיעור תורה הוא חלוק. אם כן, פשוט למה יהא חל למפרע. לבבלי, קשה למה יהא חל למפרע. ואולי גזרת רבנן על שיעור (זה, לכאורה, הוא רק אם גזירה, ולא קביעות למה שמסר תורה להם) תלוי בסיבה השייך להבאתו. ותחשב. ועל כל פנים, אכתי לא דומה לבבלי (ויש להעיר עוד ששם מביאו בשם ר"א, ולא ר"ה).
ב. אפשר שאומר שצריך לכתוב מה היה השיעור לחייב בעת שאכל כדי שידע אם צריך להביא קרבן או לא. יש לדון למה לא רק יכתב שחייב קרבן. ואולי חוששים שיזכור שלא אכל כשיעור החדש, ויחשב שטעה במה שכתב שחייב קרבן, ולא יזכור ששינו את השיעור. לשון פ"מ משמע כן, שאומר ". . . השיעור בזמן שהיה אוכל," ולא רק "השיעור שהיה אוכל.” (לאידך גיסא, קצת משמע נגד זה ממה שכתב שצריך כן לדעת אם חייב קרבן, ולא לזכור שחייב קרבן. ותח’.
** רבי יונה ורי -
יש להעיר ששנים אלו היו החולקים על ר”י (ר’ יוסי חלק, ור’ יונה תירץ לקושיית ר’ יוחנן).
** טופל -
מעניין, שאף שסבר שבהמה שניה אינו חלק מחיוב לחייב אותו להיות מחולין, הוא חלק עד כדי כך שיכול לצרף. ונראה פשוט שהוא מפני שלא יצא עדיין.
** אלא צריך
- עיין במה שמבאר. ונראה, אולי, שאם הוא דין דרבנן, הענין הוא רק שצריך להיטיב לה’ ליתן לו יותר. אם כן, טיפול יהני. אם הוא דיין דאורייתא, אפשר שאינו צריך להיות כאותו שיעור כדי ליתן יותר לה’, אלא שהוא קרק’ של בהמה שצריך כדי ליקרב, כמו מה שצריך להיות בהמה ולא חיה. אם כן, אינו אפשר שיהא צריוף. ותחשב.
** ב: אין טופלים -
יש לדון למה לא; הרי אינו חוב. אפשר שמה שהוא חוב הוא סימן שמקיים בו דבר גדול (לכן, נתחייב בו). אולי אף אם כבר יצא, מקיים דבר גדול בהקרבתו, ולאותו דבר צריך, כמו כל קרבן חובה, שיקריבנו מן החולין.
** עשר -
יש לדון למה אין לשאול כן אף על כלם שביום ראשון חוץ מן הראשון. אפשר שכיון שהוקרבו ביום ראשון, שהוא זמן חגיגה, בודאי הם נעשים חגיגה (עושים טובת חגיגיה, כמה שכתבנו בד”ה אין טופלים). יום שני אינו זמנו. (זה או למאן דאמר שכולם תשלומים של ראשון או שאף אי יש חיוב מיוחד לכל יום, אין חיוב אלא אם כן לא הביא כבר, ואז אינו יום של חיוב. הצד שידחה הוא לראשון שהוא יום קרבן לאחרים, אף שאינו לו ולשני שיש חיוה שווה בכל יום, וכל יום הוא בעל חיוב. ותחשב.)
** עד דו אמר -
יש לדון אם צריך לומר כן קודם הקרבה (יש לדון, שבדרך כלל, אין לו כל כך כח אז) או קודם הקדש. יש להעיר שלשני, קצת קשה למה אומר לעיל שהקדיש את כלם קודם שיביא חגיגיתו.
** ר”י אומר -
יש להעיר שאין דין שאין טופלים בהמה, לכאורה, לשיטתו, שאף שצריך להיות מדאורייתא שווה שנים, כמו העיקר, אין רואים שום חילוק בין עיקר לשאר לשום שיטה. ותחשב.
** גמילות חסדים -
משמע שענין צדקה הוא שגומל חסד. עיין בשי”ח ש”י בברכות (לג?).
** הדא דתימר -
בדרך כלל, לשון זה אומר שמכאן רואים. כאן, לכאורה ר”ל במה דברים אמורים. אפשר שפירושו הוא “הא דאמרינן [הוא] בגופו.”
** עד היכן -
יש לדון אם זה שיעור למעלה או למטה. בפשטות, הוא שיעור למעלה, שהרי היה שיעור של אושא כדי שלא יהיו בני אדם עניים. אבל, ממה שמזכיר לענין תרומה, שהוא שיעור למטה, משמע שזה אף שיעור למטה. לא מבאר הטעם שתקנו את זה; רק מבאר למה תקנו שיעור למעלה.
ותו”ת
** ריב”ח -
יש להעיר שהיה תלמיד ר’ יוחנן, ומעניין שר”ל יאמר דבר משמו. ותחשב.
** תבואתך -
יש להעיר שאין שיעור לתרומה מדאו’. ואולי גילה קרא שיענין לדמותם, וכשתקנו על תרומה, אף נתקן עליו.
** נמנו
- אחד- יש להעיר היו שם שני פעמים מן העשר. ועיין בר”ה.
** לחמש -
מניח שמשלם וחד מחמש ממה שהיה לו. צריך ביאור למה זה יהא. ותחשב.
** ואנוהו -
מעניין שלא אמר ש"אנוה מצות.” גם צריך ביאור איך זה (ומה שכתבנו) מבאר לשון המילה. ותו"ת. ודע שלדון "התנאה לפניו" משמע כמה שאומר פני משה.
** ג. ואנוהו -
עיין במש"כ. ודע שרשי לא פירש כן בשבת. גם יש להעיר שמוזר איך דורשו, שאוה רק ר"ל "רוצה,” ואם כן, אין הכרע מה ירצה. אפשר ש"אוה למושב" דן בדמיון לה’, וקרא זה הוא רפרינ"ס לאותו קרא. לא משמע כן, שאז נמצא שקרא שבתורה יהא רפרנ"ס למה שהוא בתהילים. יש לדון. גם מוזר מה שאומר כן אף שכבר דורש "לדבקה בו.” אולי רק ר"ל שהוא מה שאנו, שדורשים כרבנן, דורשים מ"לדבקה בו.”
** ר"ג -
צריך להיות שלא ידעו מעשה זה כשתקנו, ורק מצאוהו אחר כן, שאי לאו הכי, אינו מיגיעתם, אלא ידעו בקל כיון זהיה מעשה זה.
** מכם -
יש לדון אי ר"ל שבא מכם, ממה שלא יגעת, או שבא מכם, מפרספשי"ן שלכם.
** מונבז -
צריך ביאור איך היה מותר לו. ואולי היה קודם תקנה (או בין שני תקנות). אפשר שאין לומדות זה גבי מלך, שלעולם יכול לחייב מס לאחרים (כדאיתא בהוריות).
** שהצדקה -
יש גורסים אלא. זה נראה, שאז אומר ששניהם טובים, אבל אחד יותר טוב. אם לא גורס אלא, יהא מפני ש סובר כמש"כ פני משה, והוא שאומר "[כל מה שאמור היה ל]צדקה[, אבל] גמילות חסדים שקול… "
** אינו יום -
צריך ביאור, שלקמן גמרא אומר שהוא מחמת מוסרות. ותחשב.
** דמא -
יש לדון מה הוא מעליותא בזה:
1. אפשר שהוא שלא קיבל ממון לכיבוד.
2. אפשר שהוא שלא נתן מיד, אף שהיה לו לחוש שישאלו לאחר, ולא יוכל למכור להם.
** אלף -
יש לדון למה לא רק אמר להם שלא היה יכול להשיגו כיון שהיה אביו ישן שם. יש לומר שאמר כן, אלא שלא האמינו אותו, וחשבו שהיה דוחה אותם. גם יש לומר שהיה מנסה לעשות שישארו שם כדי שיקנו ממנו.
** פרה -
מעניין שקיבל את זה, שאף הוא הנאה הבא מכבוד אביו. ואולי לא ידע.
** ג: יאית -
לא הבנתי כל כך למה שייכים אלו מעשים למימרה זה.
** פטור
- מפרש שמודה לה’ על זה, שאי לאו הכי, קשה מה אומר, שפשוט שאין לו חיוב לכבד אב ואם כיון שאינם כאן.
ואגב, יש לדון למה לא חייב בדיני כבאד שלאחר מיתה. ויש לדון. ואולי זהו חידושו. יש לדון, למעשה, למה פטר. גם אפשר שרק ר"ל שהיה פטור מדינים הקשים. אולי זה היה הכרח פני משה, והוא שאם אמר שהוא פטור, ממה שלא חילק, משמע שקאי על הכל. אבל אם אמר הודאתו, רק אומרו על מה שצריך להודות, ועל אלו היה פטור.
** פליגא דו -
יש לדון למה אינו בעיא שנמצא שהוא נגד תנא.
** פליגא דו -
יש לדון למה אין אומרים ששאני כאן שאין לו לאב. ויש לדחות שאף אי לעני אין לו, אין חייבין ליקח חיטים לעשר לו.
עוד קשה מהו ההוכחה שהוא מאב; דלמא שאני הכא שאין לו לאב. זה מניח- ועיין לקמן- שחייב בן מממונו אם אין לאב.
** אמר רב אבין -
זה לכאורה חולק על מה שאמר לעיל "חמורה שבחמורות.”
** שהוא פריעת חוב -
יש לדון מהו הענין:
1. אולי אינו עושהו כל כך מפני ה’, שהיה צורך לעשותו בליזה.
2. אולי אין כל כך טירחא בזה, שיהא לבו מצערו אם אינו עושהו, שהוא שכלי.
** מכל
- מתן שכרה בצדה- עיין בגמרא חולין (קמב.) שמשמע שלא ר"ל כן, שאומר שכיון שמתן שחרה בצדה, עולם הבא תלוי בה, ואז, בוודאי לא ר"ל ששכרו מיד ולא לעתיד, שענינו שם הוא שהוא רק לעתיד. אלא, לכאורה, צתן שכרה בצדה רצה לומר (כן כתב רשי חולין קי:) שנחתב מתן שכרה בצדה.
** ד. גדול הוא -
יש לדון למה:
1. עיין בפני משה, שכתב שהוא שמצער יותר על מה שהוא שכלי, שיש לו יותר רצון שייעשה. מעניין שזה יעשה שהוא יותר טוב כיון שאינו מצער כדי שיעשה מצוה שבו, שלא מפני המצוה מצטער יותר.
2. אפשר שר"לש יותר צורך יש לו (שהוא פרעון).
** נשר -
אז,יש להקשות על נשר כמו שמקשים על חסידה, והוא למה טמאה היא לרמבם שאומר שטמאים הם האכזרים.
** עורב
- עיין בביאורו. יש לדון למה צריך לומר שלאחר כן נעשו שחורות. נראה שבא לבאר איך זה קורה עוד, שיראה שהוא לבן. אז, צריך לומר שנעשה שחור. יש לדון למה לא זוכר שאף הוא היה כן בעת לידה. יש לומר ששכח, ואינו כל כך חכם. גם יש לומר שחושב שמי שרק התחיל ללבן לא יהא לו בן לבן, שעכשיו אינו לבן (ואינו מכיר שכן הוא בכל בן).
** וכופין -
יש לדון למה אין אומרים שאין כופים כיון שמתן שכרה בצדה. יש לציין לתוס’ שמקשה כן על צדקה. אולי תירוצו שם יהני כאן.
** וכופין -
יש לדון למה כופים:
1. סבר שהוא משל בן.
2. סבר שכיון שאין לאב, לכולי עלמא הוא משל בן.
יש שכתבו שכיון שאין לאב, כופים את הבן. יש לומר כן בוודאי לשני, ואולי אף לראשון, שאולי אין כופים מחמת מצוה בדרך כלל (כיון שנכתב מתן שכר). יש לדון למה יהא זה חלוק. ותחשב.
** כופים -
יש לדון מה סובר מאן דאמר אין כופים:
1. אולי סבר שאינו חייב. כן משמע מפני משה, שכתב שהוא מפני שמבן הוא. אם כן, דן בו בכפייה כיון שמדבר מאן שמחייב, ולא זה יותר מחודש.
2. יש להעיר שמעניין, אז, שנתן לו עצה לבזותו לשני טעמים:
  1. מעניין שיהא נתבזה בזה, שהרי אין לו חיוב. יש לדון, שאולי עדיין יודעים בני אדם שהוא נכון לעשות.
  2. מעניין שמותר לבזותו לגרום שייתן לאב דבר שאינו חייב ליתן. אולי עדיין מקיים מצוה כשנותן לאב (בוודאי חסד הוא, ולכאורה אף כיבוד אב ואם הוא), ואולי לכן מותר לבזותו. ודחוק.
3. אולי סבר שחייב, אבל לא כופים.
** דנור -
קשה, שכבר אמר שהיה של אישתא. ותו"ת.
** רדיפה -
כיון שנלמד מזה, יש לדון אם יש סיבה לחשוב שהוא אף בבקשה. אפשר שלכן מביא ודורש גמרא את הקרא לומר שרק רואים אותו ברדיפה, ואז רק שם יש אותו שכר. גם אפשר שהוא בשניהם כיון שכד קרא הוא. אם כן, יש לומר שמביא ודורש את הקרא להוכיח שבכלל הפסוק יש יותר מרדיפה, ואז אף על אותו הייתור, דהיינו בקשה, יש שכר זה. ותו"ת.
** אבא אבוי דר"א בר מרי -
קשה, שאז היה שם אביו אבא, ולא מרי, שזה אביו (הנחתי שתרגום "אבוי" הוא אביו. אולי איני נכון.) אפשר שחד היה אביו וכד היה אבי אביו.
** חד אמר -
קצת משמע- ויש לדון- שחולקים, דאי לאו הכיל למה יזכיר שזה אמר זה וזה אמר זה; שניהם סוברים ששניהם אמת. ויש לדון. על כל פנים, עיין לקמן שמדמיון הדרשות, קשה למה נחלק. ואולי סוברים שחפצים וחפציך שווים. דע שאם חולקים כשמבאר גמרא לומר שחפצים וחפציו חלוקים אינו כשום שיטה. ותו"ת.
** מרגלי…
- עיין בגמרא לקמן שאומר שלא היה לו שוויות, ואומר כאן פני משה שהוא ממש. יש להעיר שאומר גמרא גיטין (נט?) שהיה רבי הכי עשיר בזמנו. אפשר שיכול להיות ששווה היה לאחר. אולי רק ר"ל שכן היה אחר שהשיג אותו אבן. (ואם תאמר יהא כאלו שאמר שם שהיה בתחילת ימיו גדול אחר ממנו. ויש לומר שזה לא ר"ל שהיה אחר גדול ממה שהיה אז, שאם כן, הכל יהיו כן, שהרי כשהיו נולדים, לא היו תלמידי חכמים הכי גדולים. אלא, נראה שרצה לומר שהיה אחר בתחילת ימיו שהיה גדול ממה שהיה אותו חכם כל ימיו. ותו"ת.)
** הכרת תכרת -
עיין בסנהדרין שדורש "הכרת בעולם הזה… "
** גדול -
יש לדון איך זה מוכיח שיש בו פירות בעולם הזה וקרן קיימת לעולם הבא. אפשר שנלמד מגזרה שווה מעבודה זרה. נראה שאולי גם אפשר שיודע גמרא (יש לדון איך יודע) שיש ארבע עבירות כנגד ארבע מצוות. רק דן איזה עבירות הם, ומסתבר שהם הכי גדולים.
** גדול… מנשוא -
אפשר שהמקור הוא כגילוי עריות. גם אפשר שנלמד ממה שנחשב גדול מנשוא, דהיינו שגדול מלהיות לו עונש בעולם הזה. כיון שהגענו לזה, אפשר ללמוד גילוי עריות ממנו בגזרה שווה, אלא שלא משמע כן מגמרא שרק מביאו אחר ג"ע.
** גדולות -
יש לדון מהיכי תיתי שאינו רק כנגד שנים מהם . ויש לדון. שוב ראיתי בבבלי בערכין טו:.
** אמר"י בן פזי -
יש לדון אם סובר שמה שאמר כולם נכון או שמבאר לכל אחד מהם.
** אמר רבי יהודה בן פזי -
יש לדון אם רק מבאר המשך הקרא או אומר מקור. (יש לדון מהו הדרשה, וגם יש לדון מה בא להשמיע.)
** ד: בשמים -
נראה שאז מדה כנגד מדה, נענשים בשמים ובארץ.
** גדולים
- כוללם- משמע שלא רק שקול כנגד כולם, אבל יש בו מכלם. ותו"ת.
** שלום -
נוקט סיבתו כיון שידון בה’, והרי יש לו רק סיבה ולא ציווי.
** דפקד -
יש לדון, שלא לעולם מזכיר קרא מה שקרה. ואפשר שכיון שמזכיר שהיה פקוד היה לו להזכיר פקידה. ודחוק. ותחשב.
** נופלים -
מעניין, שהרי היו נופלים זה ביד זה. אז, מה יקרה אם היו נוצחים- אותו דבר. ואפשר שלא היה להם למוות כלל (שיש תוצאה טובה של מה שהיו חיים). אם כן, באחאב היה לו לומר שלא מתו, אלא שאמר יותר מזה, והוא שאף נצחו את אויביהם (שלא היו מהם).
** שלא היו -
מעניין, שמומר לעבודה זרה הוא (אולי) מומר לכל התורה כולה.
** יוסף -
היה אפשר לומר שלא עשו כן למצוה, אלא שחשו שימיתם. מניח, לכאורה, שלא היו משקרים שלם למצווה. יש להעיר על כל גמרא זה שאם נאמר שלא היו מקיימים את התורה, ראיה זה צריך ביאור.
** שהורג -
עיין בערכין, שמרשי שם מבואר נגד מה שמשמע כאן, שכאן משמע שהוא נקרא לשון שלשי כיון שהורג שלש. רשי מבאר שנקרא כן כיון שהוא עושה את עצמו שלשי, וגם אומר ירושלמי, אומר רשי, שאותו לשון שלישי הורג שלש.
** ריב"ל -
יש להעיר שרב אלו אומרים שלא מת מחמת לשון הרע, ואז "ארבע" לא יבואר.
** ה. מקומן -
נראה שאולי לא רק ר"ל שלא הורג במקום האומרם (כמו שחנות וכדומה הורג במקום שמשתמשים בו), שלא משמע כן הלשון, אלא נראה שאולי ר"ל שאף הורג מי שלא היכה, והוא שממית שלש. יש לדון, שאף המכה אדם חייב מיתה. יש לומר שאין דרכו להמית כיון שאין דרכו להיות נמשך ליותר בני אדם כמו לשון הרע. ותו"ת.
** הניח -
לכאורה, זה מוכיח שמבערים לזמן רב, ולשון הרע כן הוא.
** מצאם -
נראה שלא הכיר כיון ש,אולי, הניחם בירושלים, ורק ראה אותם כיון שעלה לרגל.
** אלא כל -
עבודה זרה- יש לדון למ הנחשב שיש לה פרות, שלכאורה, אין לה תוצאות. אולי רצה לומר שנראה, ואז ילמדו בני אדם ממנו, וזהו פרותיו. יש לדון, שגילוי עריות כמעט בהכרח נראה לחד אחר, והוא אותו ערווה. יש לומר שלא גורם שתעבור, שרואים שאף לפני עבירתו היתה נחה לעבור. ויש לדון.
** מה טעם -
לשון זה מעניין, שאין זה טעם אלא מקור. ואולי רצה לומר שזהו הטעם למה שחושב כן. ודחוק.
** עוון -
נראה שמדייק מזה שכובש ולא נושא, והוא שאז לא גורם שיהיו כל עבירות נשתנות (שישאם) אלא רק אחד. יש לדון, שעל ידי נקיטת זה, כלם עולות. אפשר שאינו כל כך דיירק"ט. גם יש לומר, ואולי לכן צריך פני משה לכתוב כן, שלא נוטל מן הכף, אלא לפני שבא לכנף, ואז רק מונע ירידתו, ולא גורם שעולה.
** אז נדברו -
לא מביא מה שאומר בבלי שהוא עיקר הדרשה, שהוא "ולחושבי שמו.” אולי דורש באופן אחר. יש לדון.
** ובאחרונה מרד -
שמעתי שהקשה ראל"ש איך, אז, יש צד שיכולים לקיים מצות אף בכוונה שלא לקיים. יש לחלק ששם מכוון לעשות המעשה, וכאן תוהה על כל המעשה. יש לדון אם זה יחלק.
** מעויין -
רצה לומר מחצה על מחצה. נראה שלשון עיון הוא, והוא שצריכים לעיין עליו למצא דינו.
** ה: בעי -
מוזר הוא, שהוא השואל והוא המשיב. יש לומר שלא שואל מה קורה, אלא למה קורה כן. אז, תירוץ גמרא הוא שאינו קשה שכן ייעשה, ורק מבאר, כשאומר שאינו כלכ ך בעיה, מה קורה. ויש לדון.
** ובלחוד
- מלשונו משמע שאין הענין רק שלא ישוב לאותו עבירה, אלא שלא ישוב על צדקתו כלל, וכיון שבטל מלהיות צדיק, בטל משמירה זה לכל.
** א-ב ענוה -
עיין בפשטו הראשון. יש להעיר שלזה, חלוק הוא, לכאורה, מן השאר, שהשאר הם חיובים (ויש לדון. וכן נראה ממה שיש חולק עליהם, ולא מסתבר שאומר שאין טובה בהם.), וזה מדת חסידות. ותחשב.
גם יש להעיר על פשטו השני שיש לדון, אז, למה צריך לומר שדה; יהא כנגד כמה גדל בה (וזהו ענבה) בלחוד. וצריך ביאור. ותחשב. אולי השדה אומר שאף צריך להיות אחד מששים של שדה עצמו. אז, אם יש לו חמש גדולת ומאה קטנות, לא יכול ליתן רק אחד מן הגדולות, אף שמאכל שיש בו הוא אחד מששים. גם יש לומר ששיעור של שדה שייך אם יצטרך להביא גמלים.
** אין אומרים -
לפשט ראשון זה אומר שאז אין אף מדת חסידות (כל כך) ולשאר הפשטים זה יומא שאין חיוב. אז, ראשון מחודש. ויש לדון.
** מתניתא -
עיין במה שבאר שהוא דיוק גמרא. גם היה אפשר לומר שמדייק ממה שאמר "גודל" ולא מיעוט, שמשמע שהוא מרבה את השיעור. יש לדון.
** א-ג מתחילת -
ואם תאמר הא אינו חייב עד שיתחיל לקצור. יש לומר שכאן מיירי בשהתחיל כבר בשיבולת אחת. יש לדון, שאם כן הוא שווה ל"אמצע.” אז, אולי יש לומר שחידוש של המשנה הוא שכיון שלא חוזר לו בסופו, נחשב שמפרישו, ולעולם מפרישים אותו אחר שהוא נתחייב. (ההוה אמינא הוא או שיש חיוב להפריש פאה מסוף כיון שכן משמע המילה (ולא מבאר טעם לזה, אלא מקור. כן משמע מפני משה.) או שנלמד מסברה (ואולי זהו הטעם לפשט ראשון), שיש צד לומר שאין תחילתו חייב בפאה עדיין, שאולי מה שמחייב בפאה אינו מה שהתחיל בו (באותו שדה), אלא מה שעומד הוא לקצור, והוא שכבר התחיל לקצור מה שלפניו. אולי, אז, זה לא נתחייב בפאה, ואולי, אז, אי אפשר להפריש ממנו פאה. ותחשב.
** רש"א -
יש לדון מה סובר:
1. אפשר שסובר שצריך להפריש בסוף שדהו, אלא שיכול לחלק שדהו, לעשות שאמצע הוא סוף של אותו שדה קטנה. (יש לדון, אז, אם שאר השדה כבר נתחייב.) אז, נחשב פאה, אבל רק על שדהו. עדיין קשה, אז, איך תחילה נעשה פאה, שלא קצר כלום עדיין. ועיין לעיל.
2. אפשר שסובר שיכול להפריש פאה בתחילה, אלא שלא נתחייב דבר עד שהוא בעצמו נקצר. אז, רק מה שכבר קצר נפטר במה שמניח באמצע. יש לדון, שאכתי יהא מה תחילתו קשה. יש להעיר שלזה נמצא שאף שאין פאה עצמו חייב, יכול להפרישו לפאה, אלא שצריך להיות על מה שכבר נתחייב.
** אם שייר -
משמע שרבנן ור"ש חולקים, שהיה אפשר לומר שתנא קמא אומר דבר ונתפרש (או מר"ש או מר"ש ור"י).
** ה: ובקוצרכם -
משמע שרק צריך קרא אחד, אף שלומדים דין תחילה ודין אמצע.
** ר’ יונה -
יש לדון אם דורש רק מייתור או ממשמעות (רצה לומר שדורש שיש יכולת פאה אף כשעדיין צריך לקצור). כמו כן, יש לדון בריב"ל אם דורש מייתור או ממשמעות (להוה אמינא, לשון קצירה משמע שיש מה שנתחייב כשקנהו רק לקצירה. למסקנא, אומר שיש שני מיני קצירה, ולכן חילק כתוב שני מילות של פאה).
** ר’ יונה -
אין הכרח שחולק, שיש לומר שלא אומר שצריך שניהם (וכן אולי משמע, שלא לעולם צריך שניהם, שיכול לעשות רק ראשון. ויש לדחות שדורשים שלפעמים צריך שניהם.) אלא ששניהם מועילים.
** קציר הקדש -
קצת מחודש, שלכאורה, לוקח חייב רק אם כבר התחיל לקצור, שאז עליו חל החיוב. ויש לדון. ואולי מיירי כשכבר התחיל הקדש לקצור (וזה מחייב את כולו).
** ו: דתני -
קשה למה לא הביא ראיה מן המשנה, שאומר "ובלבד… " שמשמע שהוא פאה, דאי לאו הכי, קשה על מה מתנה.
** ז. מוסיף -
נראה שמניח שכיון שמכוון, הוה כאומר שזה יפטר את שדה שלו. אם כן, אי אפשר להוסיף. יש לדון, שעדיין אולי מכוון שיהא פאה, ולא שיפטר כי אם בצירוף דבר אחר עמו. ויש לדון.
** מתכוון -
צריך לבאר מה נחשב שיור אם איין צריך כוונה, שבוודאי יהא חד הנשאר. ואולי צריך להיות נשאר מאד אחר שאר או כדומה.
** א-ד ז: והחרובים -
נראה שצריך לומר כן כיון שלא תני בהם מה שאומר בתבואה, והוא ש"אלו בכלל… ," אלא שאלו חייבים. אולי משמע שאינם חייבים מפני שהם בכלל של משנה, אלא הם יוצאים מן הכלל. אם כן, אולי אין ללמד מהם. ויש לדון. יש לדון אם המסקנא הוא שיש ללמוד מהם או שהם חלק מן הכלל. מוזר, אז, למה לא אמר, למעשה, אותו לשון כתבואה. ויש לדון.
** לקצור -
לכאורה, כבר דרשנו את זה.
** חרצנים -
לא מבואר שדן בעיקרו; אולי ר"ל שזרע חרצין ממש. אולי היקשו לאילן לא משמע כן. ויש לדון, שאולי הוא קנטרס"ט.
** לקיטתם
- הרבה- משמע שאינם צריכים להיות כולם כאחד. ותו"ת.
** שאין דרך -
משמע שלשון תורה תלוי על מה אומרים בני אדם. אי אפשר שזה ממש נכון, שבני אדם משתנים דיבורם, ועוד שמצינו בכמה מקומות בנדרים שמחלק תורה בין לשון תורה ללשון בני אדם. אלא, נראה שאומר גמרא שהוקבע על פי לשון של אותו דור או כדומה. ותחשב. גם יש לומר שאומר סימן למה שהוא, באמת, נכון בלשון הקודש. ויש להעיר שכל זה לא נצרך, שרק ר"ל שבעצם אינו זרע, אלא שיש ריבוי קרא. אלא נראה אולי שאם היה בלשה"ק שלא היה זרע, לא נאמר שריבוי מלשון זרע ירבה אותו (עיין לקמן). אז, צריך לומר תחילה שמיעוטו אינו מפני שאינו זרע אלא מפני שלא נקרא זרע. ותחשב.
** ח. ברם הכא -
יש לדון מהו הדרשה:
1. אפשר שדורש מלשון זרע המיותר. מעניין שדורש אותו לשון לרבות מה שאינו זרע. אולי קצת יכול להיות זרע (עיין במש"כ לעיל). יש להעיר שאז מצינו שלש לשונות בגמרא, וקשה איך נבאר השאר. יש לומר שחד לגופיה. עדיין יש עוד אחד מיותר. אפשר שיש שום דרשה מן השני. קצת קשה, אז, למה הביא כלם. יש לדון, שאולי רק הביא את הקרא. ותחשב.
2. אולי הוא מיעוט אחר מיעוט. יש לדון, שיש שלש קראי (ועיין רשי הוריות ג. שאומר שאין דורשים מיעוט אחר מיעוט על כעין זה). אפשר שלא דורשים מיעוט אחר מיעוט אלא ממיעוטים, ולא ממה שלא נתרבה. אולי יש להגדיר שמיעוט הוא מה שנאמר על דבר אחר שכבר אמר הגדרה על מה קאי אותו דין. אולי, אז, יש לומר- ויש לדון, שכבר הגדיר קצת כשאמר שדה- שאין הראשון מיעוט, אלא הגדרה.
** לא תפאר - פא ר
לא הבנתי איך זה נלמד מפאת הראש, ששם כתיב לשון פאה. אם אומרים ששני לשונות שווים, אז, אין, לכאורה, צורך להביא קרא של פאת הראש, שנלמד מפאה עצמו. אולי דורש ש"פאר" אומר "
ת ה
אש," ואומר גמרא שמציין לו, ובו נאמר לשון פאה. ותחשב. ודחוק וסתום.
** זית שהוא פטור -
רואים כעין זה בערכין (שם הוא מחלקת תנאים). נראה שביאור הדבר הוא שאומר שאולי יש יותר חסרון כאן, שמאבדו אחר שכבר איבד חלק ממה שהיה לו. הסברה להיפך שבגמרא הוא שרואים יותר צורך.
יש צד לומר (עיין ברח"ק) שכאן אומר שהעינין הוא דבר שיצא מן הכלל… . (עיין שם; ונראה שהוא מתרץ שכאן לא יהא כתוב, אלא נלמד, ויש בוודאי פירכא, אף שיכול להיות כן אם היה נכתב בחלק מפרט.
** א"ר אבין
- בנין אב משניהם- חוקרים אם יש חד מלמד או שנים (לא כל כך מבואר מה זה. חושב אני שכתבנו על זה קצת במרגנליא.). משמע מכאן ששניהם מלמדים.
** ח: אמר רב אנון -
צריך ביאור מה אומר. לכאורה, אומר שיש כבר לימוד מן הכלל, שלומדים מ"שדה" לחייב אילנות (זה צריך להיות חזרה מצריכותא שאומר גמרא, שכיון שיש כבר לימוד באילנות, יש ללמוד מזה. גם יהא חזרה ממה שאומר גמרא שלומדים מזית (מצד השווה).). אז, אי היה רק זה, היה קושיא; אבל כיון שיש קרא יתירה בזית, נאמר שממעט בכרם. אז, צריך קרא לרבות כרם. קשה, שלמסקנא, לא נכתב זה ולא נכתב זה. אולי דבר הנלמד מן הכלל טרח וכתב ליה. עדיין היינו לומדים מזית למעט כרם, שאומר גמרא (למשל, בריש קידושין) על כעין זה שבכל מקום שאפשר לדרוש דורשים. דחוק ומחודש.גם אפשר שיש שום דרשה שלא מזכיר גמרא שלומדים מזה למעשה. ותחשב.
** רבנן -
יש להעיר שהיה אפשר לומר שמזנה דן בשאר מיני תמרים. לפנ"מ, כיון שאומרו סתם, לא משמע כן. דגם היה אפשר לומר שלא מוכיח כן ממשנה, אלא ממה שאומר בבריי’ "ר"י בר"י," שמשמע ששאר חכמים חולקים. עיין ברשבא (ב"ב קל.) שאומר כעין זה.
** שאור -
קשה, שאז יטלו אותם אז, ולמה אינם ניטלים ממש בשעה אחד. אולי הם יותר טוב אם שוההים להם.
** ט. רבי יוסי -
יש לדון מי אמר מה בשם מי. נראה שר"ל שרבי יוסי אמר דבר בשם שני בני אדם שאמרוהו בשם רבי יוחנן. גם אפשר שאמר דבר בשם רבי אבהו, ור" מטי בה בשם ר’ יוחנן או שר"נ ור"י מטי בה מרבי יוחנן או שאמרו משם שני בני אדם, ורק השני מטי בה מרבי יוחנן או שאחר (ולר ר"י, ולא אחד משנים, אלא אחר שלא נזכר) מטי בה מרבי יוחנן. ותחשב.
עיין בפני משה שאומר "תשובת ר"י,” שמשמע שרק היה ר"י דן בו.
** ט: קנס -
יש לדון למה אין קונסים אם קונהו לאחר זמן. אולי צריך לומר שמפסיד על ידי זה (יש לדון), שצריך לתקנו, ואז אין לחוש כל כך. גם יש לומר שאז אינו עומד להיותש ל כהנים, וכדומה, ואז אינו מפסידם (שלא היה כבר שלהם). ותחשב.(דע שזה אי אפשר אם הבעיה הוא שהוא ככהן המסייע בבית הגרנות.)
** ואתיא -
יש לדון למה לא יסבור רבי עקיבה כדינם. (תחילה, יש לדון מהו מקורו שלא סובר כדינם. אפשר שהוא מסברה, ואפשר שהוא שכיון שנחרבו מחמת זה, לכאורה, אינו טוב. יש לדון, שאולי רבי עקיבא יסבור שלא לכך נחרבו.).
אפשר שלא יפטור הלוקח. יש לדון, שאם עוולתם היה שלא עישרו לוקח, קשה מה לנו בבעלי חנויות, ולמה היו נחרבים. אפשר שהיו נחרבים מפני הלוקחים (כדי שלא יוכלו ליקח שם עוד). ויש לדון. גם אפשר שהיו המוכרים אומרים ללוקחים שאין צורך לתרום. גם אפשר שהיו המוכרים מערימים ליקח זה ממכרו של זה ולחזור ולמכור אותו לו כדי לפטרו ממעשר (כפי דעתם).
גם אפשר שלא יפטור המוכר. אולי זה מפני שאף שלא נותן להם אכילה, נותן להם ממון, שהוא הנאה המביא לידי אכילה. יש לדון, שאף זריעה עושה כן. יש לדון, שאולי אינו כל כך דיירק"ט או שצריך זמן יותר רב. ויש לדון. גם יש לומר שכיון שמוכרים אותם ליאכל, חייבים, שרק צריך שסוף הפרי ליאכל. יש נפקא מינא בין טעמים אלו- אם מוכרם שלא לאכול, שלראשון עדיין יחייב, ולשני יפטור.
** קנס -
נראה שהבעיא לפני משה בזה הוא שהיו כהנים עשורים לעולם נוטלים תרומה, שרק הם יכלו ליקח גרנות. לולי זה, היה נראה שהוא (נראה כ)כהן המסייע בבית הגרנות.
** רבי ור"י הנשיא -
קשה, שהיה רבי רבי יהודה הנשיא. אפשר שהיו שני ברייתות, חד אמר שם זה וחד אמר שם זה, והיו שני תנאי אליבא דרבי או שחזר בו. גם אפשר שסתם רבי של ירושלמי לא היה סתם רבי של בבלי. לא נראה כן, שלכאורה, נקרא כן מפני שכתב משנה, וזה סיבה שווה לבני בבל ובני ארץ ישראל. ויש לדון. יש שגורסים ר"י נשיאה. מעניין שיחלוק עם רבי, שהיה רבי תנא, ולכאורה, היה רי"נ אמורא. ותחשב. עיין בפני משה שגורס, “רבי יהודה הנשיא,” אבל כותב "רבי יהודה נשיאה.” גם יש גורסים כאן "ברבי.” ודע שיש נפקא מינא מכל זה איך פוסקים. ותחשב.
** מצוי הוא ללוות -
קשה, שמה שכתבנו לעיל בביאור הבעיה אינו אפשר כאן, שכאן כל מי שרוצה לקנות יכול, שלא יותר קל לעני זה ללוות מלעני זה ללוות (ויש לדון). ואולי רצה לומר שכולו ילך לעני אחד, ולא ייחלק, ואז, אף שיש לכל עני יכולת להיות אותו עני שלו ילך כולו, אינו טוב.
עדיין קשה למה לא אומרים גבי גורן שאין לחוש שרק עשירים יוכלו לקנות, שהרי יכול עני ללוות. שם אי אפשר לומר שבלי זה, היה מחלק תרומה, שלכאורה, אין זה הדרך (ויש לדון אם יכול). אולי מי שאין צריך הלוואה יותר קל לו ליקחו.
** פרק שני ב-א י": הקבוע -
יש לדון אם זה קאי גם כן על דרך או לא.
** אלא אם כן -
ואם תאמר כבר שנה שאז מפסיק. ויל"ד אם זה בעיא. ואולי מחדש שזה אף שזרעו וקצרו כבר (הוה אמינא שיש חילוק מפני מה שלא זרע כיון שאינו שדה זרע. זה שדה זרע של שנה זה, אלא שהוא שדה זרע שכבר נקצר. ויש לדון.
** מחובר -
יש מפרשים שזה רצה לומר מחוור (עיין בר"ח קנייבסקי). יש להעיר על מילת מחוור שלכאורה בא ממילת חוורתא, שהוא לבן, ואומר שהוא נקי ונכון. ותחשב.
כמו כן, יש להעיר ש"מקצת" (חצי) בא מ"מ (מן) קצה," שהוא דבר שבא מקצה (ולא מגיע לקצה אחר, שאז לא יהיה רק מן קצה אחת). ותחשב.
** מחובר -
יש לדון, אם לא מחובר, אם הוא הופסק ממש או שרק אינו חד flow. נראה כשני, שלא מבאר שיעור רחיקתם (והיה נצרך לצד ראשון).
** מחובר -
יש לדון אם זה כן אף בשאר דיני המשנה. נראה שאותו לימוד מגדר שמלמד דין נחל מלמד אף דין שאר מנויים שבמשנה (שהם בכלל כל). אף בלי זה, אותו אופן לימוד (מחד דבר לכבירו המנוי במשנה) ילמד מנחל לאלו. יש לדון, שאולי זה רק אי בא לעשות contrast. ותחשב.
** יא. לא קדשה -
ק"ק למה לא אמר נפק"מ לענין פטור שדה שני. ואולי גמרא לא משמע כן. יש לדון למה לא אומר כן גמרא. ותחשב.
** רב חסדא -
רצה לומר שרצה לומר. ק"ק למה לא רק אמר שרצה. ויש להעיר שכן דרך בני הישיבות בימינו, לומר, למשל, “אבל הקצות רצה לטעון.” ויל"ד למה. ותחשב. (ואולי בא ממה שכמה ספרים אומרים שיאמרו טענותים לולי דמסתפינא, שמשמע שלא ממש אומרם, אלא היה אומרם, ורוצה לאומרם.
** תיחם -
יש לדון מהו החילוק
1. אולי ראשון אמר שחילק בין שבטים ושני אמר שגדר מה חלק מארץ ישראל.
2. אולי רק חולקים איזה לשון אמר, שמצווה לאומרו בלשון רבו.
** מכיון -
היה אפשר לשאול למה צריך אף דרך יחיד כיון שיש שביל יחיד. אולי זה מפני ימות חמה וימות גשמים. אם כן, היה אפשר לומר כן בו, ולא בשליל רבים. ויש לדון איזה יותר טוב לנקוט.
** שלולית -
על פני כל שדה- משמע שהוא שלא מושך על כל שדה, ולא רק שהוא מים שלא מושך, אלא יושב. אם כן, לכאורה, זה דומה למחובר. יש לדון למה אין גמרא או פני משה מזכיר דמיונם. משמע שאין שניהם דומים.
** יא: פטור פאה -
אם כן, צריך להיות ששיעור של ר"י קרוב לשל רב (או שאין דרך בני אדם לזרוע בשיעורים שביניהם). יש להעיר שאין ר"י כל כך בהיר, שאומר רק ארך השיעור, ולא רחבו (ואם יהיה קרוב לשל רב, צריך להיות, כמו רובע, מקום2. ותו"ת.
** קטן -
יש לדון בביאור דין זרע אחר:
1. אולי כיון שכל השדה קטן, קשה לחלקו ולקראותו כמה שדות. אז, כולו נקרא חד שדה, אלא אם כן זרע אחר גדול מאד.
2. אולי זרע אחר מפסיק רק אם נזרע (או נראה שנזרע) כדי להפסיק. אז, יזרע רק קטן. אולי בשדה קטן, אין להוכיח שלכך כיוון, שאולי רק לא היה לו כל כך מקום לזרוע.
3. ואם תאמר אם כן לא יהיה דבר גדול מפסיק. יש לומר שמפסיק בשני אופנים- אחד הוא מה שזכרנו, והשני הוא שלפעמים הוא גדול וחשוב עד כדי שמפסיק.
** והתני -
נראה שמניחים שמיירי בשל בית רובע מפני שלא תנא בו שיעור. משמע שיש שיעור שהוא מסתבר להיות שיעורו של זה. גמרא אומר שזה שיעור בית רובע, שהוא שיעור חיובו, והוא (מחמת סימן או סיבה) שיעור חשוב לענין פאה. ותחשב.
** מני -
קצת קשה מהיכי תיתי שאינו רבי יהודה.
** חיוב בפאה -
הענין הוא שצריך שמה שבין שני השדות הוא דבר חשוב, והוא דבר נקצר. מה שחייב בפאה הוא או סיבה או סימן לחשיבות זה.
יש לדון, אז, למה אין שדה שקצרה רגילה מפסיק. ואולי הוא שאז שווים הם, ששניהם עומדים לחד דבר, ונעשים אחד. ותחשב.
** מני
- שאין מה שנשאר- יש לדון, שהיה לו להיות חייב על שאר השדה. ואולי דרך גוביי הוא לאכול את כולו. ויש לדון. ואולי אינו מחייב את השאר, שאין השאר ראוי להיות נקצר (אולי זה עושה שאין קצירה עושהו עומד ליקצר). ותחשב.
** יב. ב-ב אינה יכולה -
זה מחודש, שהיה אפשר לומר שכיון שממקום אחד (באמצעיתו) יכול לקצור שני צדדים כאחד, נקרא שיכולה להקצר כאחת.
** ולא פלגין -
מניח ששלולית הוא אמת המים. עיין בגמרא בבא קמא שדן בזה.
** אבל -
לשון זה מעניין, שאין זה סותר מה שאמר, אלא מוסיף עליו. ותו"ת.
** אינה יכולה -
יש לדון אם זה סימן או סיבה. אולי דין עומד באמצע תלוי בזה. ויש לומר לשני צדדים. ויש לדון.
** ב-ג מצד אחד -
יש לדון מה זה:
1. אולי הוא שרק צריך להגביה אותו מצד אחד, ואינו צריך להניחו על הקרקע, שנופל מאבן על הקרקע בפני עצמו. ואם הוא גבוה ביותר, לא יהני, שלא יפול בטוב, שנחוש שישבר או כדומה.
2. אולי אומר שכשבא מצד זה צריך להגביה, אבל מצד זה אינו צריך להגביה, והוא מפני שמשופע (ארץ או אבן).
** כל הרואים -
יש לדון אם רצה לומר שיכול לראות, ואף שיש גדר, שרואה על גב גדר, או שר"ל כל שהיה יכול לראות איל או גדר. לא נראה  שפני משה סובר כן, שאומר שכל העיר הוא הוספה על זה, והרי, אם לא היה הפסק, היה רואה מאד יותר מעיר אחד. ותו"ת.
** כל הרואים
- היה מצי לומר שאינו מה שמי שעומד קרוב לו רואה, אלא מה שחרוב, אילו היה רואה, היה רואה. יש נפק"מ באיזה חלק מן האילן דנים- קרוב לול בקרקע או אף גובהו. ויש לדון.
** אשכח תני -
יש לדחות שרבי יהודה רק במה שלא קבוע. אולי אין זה מסתבר לגמרא. גם יש לומר שממה שלא דן ברייתא בזה כלל, נראה שסובר שאינו מפסיק כלל אם אינו קבוע.
** גדר -
קצת יש לדון למה מה שנוגעים בגדר עושה שלא יפסיק. ונראה שאולי כיון שנוגעים נחשב הגדר להיות רק חלק מן האילנות. ודחוק (אבל כן משמע מפני משה).
** כותש -
לא הבנתי למה נקרא כותש (שהוא מלשון מכתשת).
** יב: אמצעים -
לכאורה, כן יהיה הדין בקרנות עיר. ק"ק למה לא נקט זה כיון שכבר היה דן באותו בבא.
** והן -
קשה למה יעשה כן לילדים כיון שיזקנו. זה יש לומר שאין הכי נמי, ואף על לפי כן, יש יותר הנאה בכעין זה. עוד קשה איך נאמר שדרך זקנים בזה כיון שכבר נטע אותם כשהיו קטנים. ויש לומר- ואלו יתרצו את הראשון- שדן שני (ואולי הוא רק טוב בזה) כשזורע אילן זקן. גם יש לומר שחותך שבע מהם. גם יש לומר שדרכו של שדה הוא שרק שלש ישארו, ששבע ימותו מעצמם.
** ב-ד שני גרנות -
יש לדון אם זה אומר רק שמכניסם בשני שמנים ל מקום גורן או שקוצר אותם בשני זמנים (ומיד אחר שזורע מכניס גורן). נראה כראשון, שלשני קשה למה ינקט סימן ולא העיקר. ואולי זה מגדיר מה נחשב זמן אחד לענין קצירה (שאינו צריך להיות ביום אחד ממש).
** שקיבל מאבא -
יש לדון אם רצה לומר שקיבל מאביו או מאב של ר’ מישא.
** שמומית -
עיין בפני משה, שלפעמים אומר שהוא שחור, ולפעמים אומר שהוא אדום. ועיין, חושב אני, בגמרא ב"ב.
** יג. שהרי כמה הלכות -
נמצא שאף שהיה קבלה על ההלכה למשה, לא היה קבלה שהיה הלכה למשה מסיני.
** יאות -
יש לדון, שאולי אף שהיה שמועה כן, לא היה משנה אומר אותו דין ולא לפרש, והרי משנה כאן מפרש. אפשר שלא מניח שמשנה יעשה יותר ממה שברייתות שלפניו עשו. גם אפשר שמניח שלא היה ידוע לרב בני אדם, ואז, לא מסתבר שמשנה ידע את כלם. ותחשב.
** אלא כיני
- מעניין מה שאומר שאומר שבכלל בעל פה הוא מה מצינו, שלכאורה, אין לומדים מה מצינו מהלכה למשה מסיני (על כל פנים, אומר כן גמרא על קל וחומר). אם כן, צריך לומר שרק רצה לומר לימוד ממה שנכתב על ידי סברה, ולא על ידי דבר הנכתב. ותחשב. (גם יש לציין לרש"י (?) שאומר מה שיכול לדרוש אותם מדעתו הוא שלא נמסרו למשה מסיני. אם כן, מוזר שאומר שהם בכלל שבעל פה. ותחשב.) שוב הבנתי שלכאורה, יש הלכה שאומר שיש לדרוש מה מצינו, אבל לא שאומר איזה יש לדרוש. ויש לדון.
** אלא כיני -
רצה לומר, יש תירוץ אחר לקושיה זה, ולבאר דבריו (שמרובה… ) נאמר שחביבה… . ויש לדון. ותו"ת.
** ואיני יודע -
עיין לעיל שאמר שעל כל פנים מה שנדרש מן הפה יותר חשוב.
** אם קיימת -
צריך ביאור למה שינה ממה שאמר לעיל (וממה שאמר גבי בעל פה) לומר קיום ולא שמירה.
** מקרא -
אומר שלש דרשות ומונה ארבע. שוב ראיתיי שר"ח קניבסקי אומר שמקרא נלמד מפשוטו של הקרא.
לכאורה, דבר שתלמיד עתיק מחדש הוא בכלל תלמוד, שהוא כל הנאמר לבאר משנה או כעין זה.
יש לדון באיזה כלל הוא דבר הנאמר לבאר פסוק. אולי לא נמצא שאומר הלכה (שאי לא כן, הוא אגדה) שאינו כבר במשנה. ויל"ד.
** מה שתלמיד -
בפשטות, זה אומר שבכל זמן שאומר אדם תורה, אם מסתבר הוא, לכאורה הוא נכון. אז, מסתמא נאמר למשה מסיני. אם כן, מה שנקט תלמיד ותיק הוא רק שהוא מי שרגיל לחדש תורה. עיין בר"ש סירליאו שאומר שותיק הוא ענו (כן אומר רש"י בברכות), וכיוןש ענוה מביא לידי רוח הקודש, מצוי שענו יאמר דבר שהוא נאמר למשה מסיני. אם כן, החידוש כאן הוא או שיש לו רוח הקודש (ויש לדון, שהרי אומר כן, שאומר כבר שענווה מביא לרוח הקודש (כן אני חושב). ואולי מחדש שאף יכול להביא לאותו רוח הקודש שיגלה דבר חשוב כתורה), או שיכול להיות שיש הלכה למשה שאינה ידוע, וצריכה להתחדש. ותחשב. אם כן, אומר תלמיד ותיק מםני שותיקותו הוא הגורם לו אותו רוח הקודש שבו מיירי. ותו"ת.
** מה טעם -
אין זה טעם, אלא רק מבאר שאומר כן קרא, לכאורה. ותו"ת.
** כולם -
לכאורה, אי אפשר להיות שכולם במשנה, שאף מה שאומר תלמיד ותיק נאמר למשה מסיני. ואולי רצה לומר שאמרו כל מה שאינו מסתבר (שהם הדברים שאין אחרים יכולים לחדש. גם יש לומר שתלמיד ותיק מחדש פשט במשנה או כדומה.
** אלו התוכחות
- לכאורה, מפרש את הקרא להיות לשון תמיה (“זר אתם?”). לולי זה, היה אפשר לומר שמפרש קרא לשון רגיל (וגמרא בלשון תמיה) ואומר שקרא אומר שאף שהוכיח ה’ את בני ישראל, עדיין אינם טובים, והם כזרים.
** רבי אבין
- יש לדון מה הטעם הזה:
1. אולי אומר שכמו שיש לגויים ספרים שלהם, יהיה לנו ספרים שלנו. כיון שה’ נתנם בעל פה, יש לנו חילוק במה שתורתינו בעל לפה.
2. אולי אומר שאם יכתבו יהיה תורה לנו ולגויים, שיוכלו לדעת תורה שבעל פה.
לשונו של "יש להם ספרים," וכן לשון גמרא, משמע כצד ראשון. לשון "אין להם מזה" משמע כשני. ויש לדחות שאומר שאין להם מכמו זה (רצה לומר, ממה שהוא בעל פה) כלל. ותחשב.
** רבי אבין -
לכאורה, זה הסיבה שאין לכתוב דברים שהם בעל פה.
** וחבירו
- מפרש שהוא משה; ואין צריך לזה, שיכול להיות חבירו תלמיד חכם שיודע הלכה למשה מסיני. ואולי לא מסתבר שידע כיון שתלמיד ותיק לא יודע.
** וחבירו
- מפרש שלעולמים רצה לומר לשני עולמים. לכאורה, רצה לומר שמכוון לשעת מתן לתורה, שגרם לשני עולמים. לולי זה, היה אפשר לומר שהוא מלשון לעולם (ואולי אז לשון רבים קשה. כמו כן יש לומר שאז היה לו לומר שהוא מעולם.), והוא אומר שהוא מהלכה למשה שהיה מעולם. יש לדון, שאם כן, קשה מהיכי תיתי שהוא מהלכה למשה; דילמא הוא רק אמת וחלק מתורה. צריך לומר, אז, שרק מחדש שיכול להיות חלק מתורה, ולא שנאמר, שפשוט שכיון שהוא חלק נאמר. ותחשב. גם אפשר שקורא נתינת התורה מעולם כיון שקרה לפני כל כך כמה שנים. ותחשב.
** אין למדים
- משמע שדין זה הוא רק שאין לדמות (והוא, לכאורה, או מפני שלא קל להבין טעמם (ולא משמע כן מדבריו) או שיש מושג שאף שכנראה אין דבר נכון, כיון שאמרו אדם חשוב, יש לעשות כן, אבל אולי רק במקום שאמרו (אולי הוא מכבדו או כדומה ואולי הוא שאז נצרף עמו ספק שאולי רק כאן אמור. ותחשב.). עיין בגמרא נדה (במה שאומר שם שמואל (ואגב, הוא לכאורה, לשיטתו כאן)), שאז צריך לומר שאין חידוש שמואל שכן הלכה, אלא שאף יכולים ללמוד (ואולי אינו בעיה, ובפרט לצד שני, שאז מחדש דבר בענין היותו הלכה כן, וכמה נסמוך עליה). עיין כאן שרשו אומר לשון ש"אין לסמוך עליה." אולי, אז, סובר שאומר שניהם. יש לדון איך ידע כן. לכאורה, משמע מלשונו (שאומרו אחר "לפיכך" שבא מ"לכך" על מה שאין ללמוד ממנו) שאומר שהוא אותו דבר. אז, אולי סומך רק רצה לומר סומך עליו בכל מקום (ואולי זה יותר טוב לצד שני).
ויש להעיר שגמרא, לכאורה, אומר על כל פנים, שהוא לענין ללמוד ממנו לדבר אחר מקושיתו מרחב"ש. ותו"ת.
** מן ההלכות -
יש להעיר שפני משה כתב שאלו הלכות למשה מסיני. אם כן, פשוט שכלל זה הוא שלא ללמוד דבר מדבר, ולא שלא לסמוך עליו. יהיה מעניין שאומר שני דינים (שלא ללמוד מהם ושלא לסמוך) בחלק מן הציורים שהביא, ואומר רק אחד במקום אחר. ותחשב.
** המחליק -
צריך ביאור למה אינו אפשר. עיין במהר"א פולדא שאומר שר"ל שכיון שאינו כל כך דומה לדין חטים, לא היה נשכח. עיין בפני משה שכתב, “ודאי דלא נשנו.” משמע שיש הוכחה שלא נשנו. ואולי רצה לומר שיש הוכחה כן, והוא מה שלא ידעו אותו דין. ותחשב.
** מן המעשה -
אף שזה מעשה שעשה רב, וזה הוראה שנתן לאחר, לכאורה, אין חילוק ביניהם. ותחשב. וצריך ביאור.
** דסבר
- עיין במה שכתב. לולי פני משה, היה אפשר לומר ש"סבר" רצה לומר שסבר כן, ואמר שרק יכול להיות סמך, ולא מקור. גם יש לומר שלא אומר שצ"ל שכבר סבר תלמיד כן, אלא שרב סבר כן, אבל לא פסק כן להלכה, שאז מסתבר לומר שפוסק כן להלכה כיון שסובר כן, ואינו משום טעם אחר. ותו"ת.
** אמר ליה
- צריך ביאור למה אומרים שרבו יכול לטעות, ולא אמר שהוא יכול לטעות (ודע שרשבא, באמת, כתב בשני). נראה שאולי רבותא אמר, שאף אם שאל לרבו, ורבו אמר שדווקא הוא, לא מהני. וקשה לדין זה איך רב נאמן לעולם, שאולי שמע מרבו, ולא דקדק, שכן הוא חשש זה. אם כן, למה ליה למנקט מעשה.
** אמר
- צריך ביאור מה לנו אם יש מחלקת; בין כך ובין כך, צריך להיות מקום לטעות, שאם לאו הכי, אין צורך ללימוד. ותחשב.
** ב-ה שחובת הקציר בכמה -
קשה למה אין אומרים כן אם קצר את כולו לעצמו. אולי שאני הכא שלא כיוון לקצור את כולו, ואז יש דבר שמשייר ומפריש, מה שאין כן אם בעל בעצמו חותכו. ותחשב. אם כן, אולי אם הפריש וחזר בו, יהיה פטור מן העומרים. ותחשב.
** יג: לישראל -
עיין במפרשים שדנים אם השדה של ישראל או של גוי. דע שאם של גוי הוא, אין ראיה מברייתא שמביא, שאולי שם של ישראל הוא.
** לקט -
מניח שאין לחלק בין מתנות חלוקות.
** אין בקיאין -
עיין במה שפירש. היה אפשר לפרש שלא אומר דין, אלא אומר עצה טובה, והוא שאין לעשות אותם לשוכריו, שכיון שאין בקיאים בדינים אלו, יש לחוש שיחמירו ביותר, ויפסיד. ותחשב. (ודע שכמו כן מצינו (פסחים?) שגרים, כיון שאינם בקיאים, מחמירים יותר מדי.)
** שלא לאיבוד -
רח"ק כתב שבזה חייב הגנב. עיין בפני משה. יש לדון אם ה"הוא" שאומר הוא הגנב (ואומר שבעל הבית חייב על הכל, שיש פאה ממה שקצר גנב, והוא נשאר בקמה, שחיוב על קמה.) או הבעל הבית (ואומר שרק על מה שקצר בעצמו חייב.) אם נאמר כשני, פשוט מה אומר חולק, והא שכיון שאין קרקע שלו, אי אפשר לו להפריש מקמה. אף שאם כן יחייב להפריש מעומרים, אולי יש חיוב רק על קמה, אלא שכיון שביטל אותו חיוב, חל חיוב על מה שהיה עליו חיוב מעיקרא. ותחשב. לראשון, צריך ביאור יותר. אולי אומר שאין חיוב לגנב, ואז אין חיוב לבעל הבית, שכייב רק כיון שפאה של גנב ברשותו. עיין בלשון רש"י. נראה שאומר שאין קרקע נגזל, ואז צריך להפריש ממה שנקצר, ואז הוא עצמו חייב על עומרים שבידו. אם כן, אין פאה נשאר ברשות בעל הבית. יש לדון בלשון גמרא של "פאה במחובר… ," שמשמע שזה סיבה לדין.
** לישראל -
אף שאין שליחות לגוי, לכאורה, אין צריך שישראל יעשה קצירה, אלא שיגרם אותו.
** הלוקח מהו -
יש לדון למה לא שאל את זה במוכר, כומ ששאל את הראשון. יש לומר שכיון שאמר שיש ללמוד זה מזה, אין צורך לשאלו ממוכר כיון שכבר שואלו כאן. אז, אומרו בלוקח שבו מיירי. יותר נראה שאין שאלה זה במוכר, שלמה לא יוכל ליקח. יש שאלה גבי לוקח רק מפני שבזמן לקיטת פאה, השדה שלו. ותחשב. (ויש לדון, שעדיין יש קצת מקום לספק במוכר, כיון שיש מן הקציר שהוא שלו, וגם שהפריש חלק מפאת אותו קצירה. ותו”ת.)
** רבי ור”י -
עיין לעיל שבארנו איך יכול להיות שיחלקו. ונראה שמה שבבבלי קוראים אותו ר”י נשיאה ובירושלמי קראו אותו ר”י הנשיא מפני שבירושלמי, לא היה קל לדעת על איזה מהם היו עוסקים, שנכתב ירושלמי קרוב לזמנו, ואז קל לדעת אם מדברים על חכם של אותו דור או שלפניו. בבלי נכתב מאד אחריו, ואז שניהם היו ללפני זמן. ואלי, אז, לא היה כל כך קל לדעת על איזה מהם קאי. אז, צריך לכנות שם אחר לר”י הנשיא. ותחשב.
** קצירת חו”ל -
יש לחלק שקצירת חו”ל משנה את הזרע, ושל הקדש הוא חילוק בבעל. רצה לומר, שאפשר שבזה אין סיבה לפאה, ובזה, רק נדחה כדי שהקדש יפטר. ויש לדון. (ואפשר שמקשה מחמת דמיון לימודיהם. ויש לדון.)
** יד. קצר הגזבר -
הצד שיפטר הוא שאולי מה שחייב בעל כשקצר שני הוא אינו מחמת חיוב פאה שחל כשקצר, אלא שראשון חייב בפאה, והשאר פאתו בשדה. אם כן, נמצא ששדה של שני חייב. הצד שהוא חייב הוא או שאף בשל הקדש נאמר כן, שנשאר פאה בשדה, אלא שאין הקדש חייב ליתן אותו. גם יש לומר שסובר שיש חיוב חל כשאדם קוצר שדה ליטול פאה על כל השדה. חיוב זה הוא על השני. ותחשב.
** פרק שלישי ג-א מרוחקות -
יש לדון בביאור זה:
1. אפשר שהוא שמביאים אותם לטובת אילנות. יש לדון איזה טובה יש בה:
  1. אפשר שאין קרקע יכול להחיות כל כך אילנות, ואז צריך לשבתו על ידי זרעים.
  2. אפשר שאין כל כך מקום כיון שיש ענפי אילן בין אילנים.
2. נראה שלשון גמרא כשמגדיר את השיעור אינו משמע כזה, שלזה לכאורה צריך להיות שיעור של הרחק (ואף שיכול למצא כן בשיעור עשר לבית סאה, היה לו לומר אותו שיעור הרחק בפירוש). ותחשב.
3. אז, כיון שהוא לטובת אותו שדה נעשה חלק מאותו שדה. אז, כולו חד שדה (שאילנות, שהם ביניהם, לא מפסיקים, שהם חלק מאותו חד שדה). אז, מפריש פאה מן הכל. יש לדון למה אין אומרים,אז, שמפריש מאילן על תבואה. ואולי יכול. גם אפשר שאי אפשר שאינו אחד מששים ממה שיש בשדה אלא אם כן יש בו מכל מין (ואם כן, צריך לומר שכשאומר שמין אחר מפסיק, רצה לומר זה (שאם הוא סיבה כאן, יהיה סיבה שם). אם כן, לכאורה, חלוק הוא משאר דיני משנה.).
4. אם אילנות כבר מרוחקים, אין צורך לזה. אז, אינו חלק באותו שדה אחד.
5. אפשר שהענין הוא שכולם לצורך האילנות, ואז לכלם יש חד צורך, מה שאין כן אם צורכם הוא להיאכל, שאז לכל אחד יש סיבה חלוקה- לאכול אותו חלק. זה רק מהני לצד ראשון שבצד ראשון לבאר צורכו (שאז כולם לכל האילנות).
** דבית רבי -
מעניין, שלכאורה משנתינו נשנו מרבי. אז, לכאורה, משנתינו הוא של בית רבי. וצריך לומר שרבי שנאם, ושוב חלקו (אחר מיתתו) מה אמר משניות. גם יש לומר שכוץ ממשניתויו (שהיו עיקרי הברייתות, או שהברייתות שחשב להיות בהכרח נכונים, ולא משובשים), גם שנה ברייתות.
** שאין דרך -
יש לדון מהו ה"מה שאין כן… ":
1. מה שאין כן אם הוא מצומצם, שאז הוא הדרך.
2. מה שאין כן אם הוא מצומצם, שאף שאין דרך, מצטרפים. עיין לעיל, שבארנו אותו צד.
צריך לבאר למה יהיה צד ראשון ביאור לצירוף (וזה מוכרח בין כך ובין כך, שאומר גמרא כן גבי רווחים (שהיה סיבה אילו היה אמת)). אולי אז יותר נחשב שדה אחת, שדרכם להיות יחד. ותחשב.
** מסתבר -
יש לדון אם אומר חד דיבור, והוא שמסתבר שבית שמאי אומר כר"י, ור"י לא אומר כבית שמאי, או שהוא הוה אמינא ומסקנא, והוא שאומר גמרא שנראים דברי בית שמאי ורבי יוסי שווים, ודן אי צריך לומר אז שר"י סובר כב"ש או רק שב"ש סובר כר"י. נראה מגמרא (וכן נראה מפני משה) כצד ראשון.
** שכן דרך -
יש לדון איזה הוא אותו שיטה שמאחדן:
1. צריך להיות כדרך.
2. יש גדר יותר חמור מה נחשב כדרך.
** בצד אחד -
עיין פני משה. יש לדון מהו שני צדדים לפי פשטו הראשון:
1. אפשר שרצה לומר שמעורב תלם אחד מזהואחד מזה על ראשים חלוקים, כזה:
2. אולי רצה לומר שיש שני שורות, היוצא מזה לזה, והיוצא מזה לזה, אבל אינם צריך להיות בראשים חלוקים, כזה:
3. אולי שורה יצא מזה ומזה, והגיע של זה לשל זה, כזה:
גם תלוי באם “ראשי שורות” רצה לומר ראש vertically (בציורינו) או horizontally. ותחשב ותבין. ונראה דלא כשלישי, שלכאורה, קשה מה לנו בזה.
גם צריך לבאר לצד ראשון שבפני משה מהו “שלש…” אפשר שהוא רוחב השורה.
** ולמה לי כר”ע -
יש לדון למה מניחים שסתם המשנה הוא כרבנן, ולא כר”מ (שסתם משנה ר”מ), ולא ר”ע (שסתם משנה אליביה).
** שני מינים -
נמצא, אז, שאינו אף כר”ע (שדן רבי מאיר בהפסק, ולזה צריך שני מינים).
** יש לדון
למה לרבנן, אם הוא שני מינים, יחייב אם קוצר באמצע. ותחשב.
** טו. והמחליק -
לפשט ראשון שאמר, יש לדון למה כאן נקרא מחליק, שאינו מחלק, אלא כולם לצורך אחד. ואולי עדיין הם בזמנים שונים (שאם לא כן, לכאורה, פשוט הוא), ולכן נקרא מחלק. גם יש לומר שרמבם הוא האומר אותו פשט, ולכאורה כאן סובר שהוא מחלק. ונראה שזה מבאר למה לא נאמר פשט ראשון, שלכאורה, מאד פשוט הוא לומר כן. הסיבה שלא לאומרו הוא, לכאורה, קושיה זה. (גם יש לומר שאם כן, היה לו לומר, “המחלק,” ולא “המחליק.”
** והמחליק על יד
- עיין ברמב”ם. לכאורה, רצה לומר שמה שקצר, עשה לחד דבר, והשאר הוא לדבר אחר. אז, היה לו להיות כרישא של משנה, אלא שכיון שהוא חלק גדול, נשאר חלק מן השדה (אי אפשר לקראותו שדה בלתיהו), ואז יש לו פאה אחת. רק אם הוא חלק קטן, נקרא שדה ען קצת שנתוסף, ואז, כיוףןש אינו חלק באותו שדה, אין פאה. גם אפשר לומר שכולו לחד תכלית, אלא שנקצר בשני זמנים, ואולי זה די לחלקם (לא נראה), אלא אם כן, הוא חלק חשוב (כמה שכתבנו).
(דיון זה שכתבנו ברמב”ם שייך למה שכתבנו לעיל ד”ה המחליק. ועיין שם.)
** המוריג -
אם רק רצה לומר שיש פעם שנחלק על פי זמן שקוצר, קשה למה לא אומר שהוא שני מיני תבואות. צריך לומר ששם כיון ששניהם לגורן, אף שהם גורנוות חלוקות, שווים הם. גם נראה שאולי יש לדון שם אם זה מגלה שחושב עליהם לשני מינים או שזה המחלקם. נראה שאם נאמר כראשון, יש לומר שרוצה ציור שהמחלק הוא זמנם, ולא שזה הסימן.
** קציחה
- בפני משה אומר שהחידוש הוא שחייב פעם שני. אז, לכאורה, זה שייך לגמרא נדרים שדן בזה בכל זרעים (בשזרעו כלה, ובשלא כלה, ואם בטל…). קשה, אז, מלשון גמרא (שמשמע שדן בו כיון שהוא נקצר לזריעה), ומחילוק גמרא (מה לנו במה שרובו לזריעה; אם מה שכבר הפריש ממנו די, למה נחלק, ואם לא די, גם כן קשה למה נחלק.). וצריך ביאור.
לולי פני משה, היה נראה לומר שדן אם צריך להוציא ממנו פאה כיון שעומד לזריעה. עדיין יש לדון מה לנו מה שרובו עומד לו. יש לומר שרצה לומר שכל אחד לא עומד כל כך לזריעה. ויש לדון. גם יש לומר שחיוב פאה הוא על השדה, והרי אין השדה עומד לזריעה. (אולי זה יהני למה שהקשינו על פני משה. ותחשב.)
** ע”ד דרבי ירמיה -
צריך ביאור מהו קושיה זה; לכאורה, לא חולקים מהו המציאות במינו. אפשרשחולקים, ולכן זה מוקים כזה וזה מוקים כזה. קשה, שאז צריך לומר שחולק על משנתינו. גם קשה לומר שחולקים במציאות. אפשר שסובר גמרא שצריך שיהיה מגדל ממין זה לקיום. לר’ ירמיה, יש לו חלק שמכניס לקיום. לר’ יוסי, אין לו. קשה, שאולי ר’ יוסי מיירי כשעשה כן לחצי שדהו, אבל נשאר חלק ממנו לקיום. אולי מה שלא זורע רב אינו אומר שכן עושה בדרך כלל, אלא שכן עשה כלל. אם כן, אולי רצה לומר שבהכרח לא הכנים חלק חשוב לקיום. ותחשב.
** גמור - די לא כן -
יש לדון אם צריכים מה שיכול לקיימו או מה שיש במינו מה שמקיימים (או שיש במינו מה שיכול לקיים). לראשון, אומר שכיון שגמור, יכול לקיימו. לשני, אומר שכיון שגמור, מין בצלים של יבש הוא.
משמע שמפרשו לומר, “דאי לא [אמר גמרא] כן… מה [היה ההוה אמינא].” לולי פני משה, היה אפשר לומר שהוא, “דאי לא אמר כן [אלא אמר שהדין אינו כן], מה את אמר [לבאר למה].”
** מה עביד ליה -
נראה שזה מקור למה שבני אדם אומרים על קשיא, “מה [אחרון] זה עושה בזה…”
** עיסה -
יש לדון מהו החידוש של “לעיסה”:
1. אפשר שהוא אינו חידוש, אלא “כל שהוא” הוא החידוש, ואגבו אומר זה, שאולי אינו מלקט כל שהוא לזה.
2. אפשר שהוא שהוא יותר קבוע ויותר חשוב.
עיין לקמן בגמרא,
שאומר, לכאורה, שדין זה הוא רק כשעושה עיסה כיון שהוא חשוב וגומר מלאכה. אז, נראה כשני.
ודע שמוזר לומר שאומר כן מפני דין שצריך לשייר, שלא הוא עצמו אמר שצריך לשיייר. יש לומר שרק אומר כן כיון שהוא יותר מחודש, וממילא דין שצריך לשייר קאי רק עליו. ויש לדון. גם יש לומר שמדייק ממה שאומר כן דווקא על מימרה שדן ברק כעין זה. ותחשב על זה.
** אפילו כל שהוא
- עיין במה שמפרש, “אפילו מה שהוא… “ צריך ביאור מה כוונתו בזה; אם לא פוטר על זה, על מה פוטר. נראה שכוונתו הוא לבאר לשון גמרא, והוא ש”כל שהוא” אומר “כל מה שהוא לוקט.”
** אפילו
- אלא שבתחילה- משמע שהפטור הוא  מה שהתחיל באופן מוזר (שקצר רק חלק ממנו). לולי זה, היה נראה לומר שכולו מוזר כיון שקצר כולו (חוץ משיבולת אחרון) מעט מעט כשהיה לו לקצור את כולו. פני משה לא משמע כן, אלא שרק תחילתה מוזר. כיון שכןן, לכאורה, דין זה יקיים אף אם קצר כולו לבסוף. ויש לדון. אולי הבעיה בזה הוא רק שאז אינו נחשב חלק מאותו קצירה ראשונה.
** מגל -
יש לדון אם רצה לומר שקצר כולו במגל או שסיים במגל (כפי מש"כ בביאור פני משה לעיל שאולי צריך להיות מוזר רק בתחילה). אם נאמר כדרך שני, יש לדון אם רצה לומר שיכול לעשותו במגל מעט מעט או שאף יכול לעשותו כדרכו (ומגד הוא סימן לזה). עיין בפני משה שאומר שקצרם מעט מעט. ותו"ת.
** והוא ששיר -
יש לדון על מה קאי- אם על מגל או אף על כל ציור. נראה ממה שמקשה גמרא ולא מתרץ שזה במגל וזה אינו במגל כצד שני.
** שייר -
יש לדון מה לנו בזה. נראה שני דרכים:
1. אפשר שכיון שעשה כל שדהו כך, גילה שזהו רגיל לו. ויש לדון. זה מניח שפטורו הוא מה שהוא מוזר (וכן נראה מרש"י), אבל היה אפשר לומר שקרא מוציא דרך זה של לקיטה. יש לומר שאולי לא נתמעט אם עושה אותו בדרך רגיל, שאז הוא נקרא לקיטה, ולא רק ריטוף. ותו"ת.
2. אפשר שכיון שאז יפטר מפאה, חייב. צריך ביאור למה יהיה כן (ואולי רק תקנה הוא. ודחוק.) נראה כצד זה קצת מפני משה. עיין שם.
** נגמר -
לשני, יש לבאר שאומר שכבר נתחייב קצת בפאה, ואי אפשר לסלקו מעניים. לראשון, יותר צריך ביאור. אפשר שהוא שאינו כל כך מוזר, שאז רק משנה איך קוצר, ולא משנה גם כן במה שמקצר כלל.
** כשביקש -
יש לדון אם אומר שגמרא מלאכה הוא המחייבם או שקצירה לגמר מלאכה מחייבם. משמעות גמרא (שדן רק בקצירה) הוא כשני.
** טו: ג-ג פורגרה -
נראה שהמילה באה ממיל. “לפרוק,” שהוא לפדות. אף שאין ממירים בלשון פדיון לא חל, דומים הם תמורה ופדיון, ואולי יכולים שניהם להיקרא בלשון זה. נראה שגימ”ל במקום קו”ף כמו שרגילים קצת מן הספרדים לדמותם. ותחשב.
** בזכה -
יש לדון, אז, למה ר”י חולק. נראה שני דרכים:
1. אפשר שסבר שאין הוכחה מזה שלא הפקירם.
2. אפשר שסבר שכיון שלמעשה יכול אדם ליקח (שהרי, לא נדע כשלוקחים שלא הפקירם, ונצטרך להניח שהפקירם), פטור.
** אף על פי -
צריך ביאור מה אומר כאן. עיין פני משה, שנראה שמפרש שרב נכנס לקיום, אבל מיעוט נכנס. קשה, אז, מה אומר, “אף על פי… ,” שזה סיבה לחייבו. גם קשה לשון, “אינו מתקיים.” וצריך ביאור. אפשר שאומר שאף שאין מתקיימות רצה לומר שאינו מתקיים לו, וצריך לשלם, ואז הוה אמינא שכיון שכבר נתן פאה קצת, אין כל כך צורך ליתן עוד (כמו שכתבנו גבי "שייר" לעיל). קשה, אז, מהו המשך אותו דיבור של גמרא (ועיין שם).
- יש להעיר שלכאורה גמרא עדיין רק כשהוא נוטל אחד אחד, שאי לאו הכי, יהיה הוכחה שמפקירם, שהניח גמרא שכן מוכרח ושאי אפשר לרבנן לחלוק על זה. ותחשב.
** הבקר -
עיין במה שאומר שהוא מפני שמעט הוא. יש לדון מה לנו במה שהוא מעט. אולי זה סימן (שממה שלא עשה כן עם כל בצליו, נראה שלא רוצה אותו כל כך. ויש לדון, שאולי אין צורך ליותר.). גם יש לומר שהוא שכיון שאין צריכים כל כך בצלים לעשות כן, אם אחרים יקחו את שלו, אינו מקפיד כל כך, ואז מפקירם. יש לדון, שבוודאי אסור ליקח אחד שייחד לאכילה, אף שחסרון שווה (שבפשט זה, הענין צריך להיות שכיון שאין צריכים כל כך בצלים לזה, יכול להביא אחרים). גם יש לומר שכיון שאין צריכים כל כך בצלים כדי לעשות כן, וקל לעשות, הרבה עושים כן, וכיון שיש כל כך supply, אינו כל כך חשוב. ותחשב.
** ג-ד חזרו -
נראה שיש חידוש בזה, שיש צד לומר שכיון שהיו נחלקים בבעלות כל זמן גידולם, נחשבים שני שדות חלוקות.
** זה צפונו
- מתחילה- נראה שבא למעט אם רק עשו כן אחר שלקטו. ותו"ת.
** חזרו -
כל סוגיה זה צריך ביאור. היה אפשר לפרש שדין ראשון הוא שצריך להפריש מחלקו, והוא שהוא קצר קמה לו, ואז חייב, וצריך להיות מחלקו, ולא מן הקמה, שאינו שלו כשנעשה חייב, שרק נעשה חייב כיון שאין לו עוד לקצו. (ויל"ד). אז, על זה אומר גמרא שאף אם חזרו להשתתף, אינו מפריש מאותו חלק על של חבירו, שנשתתפו רק לאחר כן. צריך ביאור למה, שהיו שותפים כשקצר, ועוד שהיו שניהם שלו כשחל החיוב. אפשר שאין "בתחילה" רצה לומר חלק של קצור, אלא חלק של קצה קודם שנקצר. קשה למה נחלק בין קודם קצירה ללאחריו.
אבל פני משה לא פירש כן. מפרש שפטור לגמרא, שהניח בשדה חבירו. צריך ביאור, אז, דין שני של גמרא, ששם לכאורה, כל הפאה יהיה בקומה, וכשקוצרים אותו שדה, יתחייבו בו, ושניהם יטלוהו ממנו ביחד. אז, צריך ביאור מהו, “ולא מתחילה… " ותחשב על זה.
ושוב ראיתי בגר"ח קניבסקי שאומר שדן כאן בשלא היו שותפים על שדה ראשונה כשקצרו. זה מבאר, אז, למה אי אפשר להפריש על שבתחילה מזה על זה.
** מתחילה -
קשה, שפשוט שאי אפשר, שהרי חייב להפריש מקמה. ונראה שהיה אפשר לומר שאין הכי נמי, וכן אומר גמרא כאן. ויש לדון. נראה יותר שאולי דן בדין בדיעבד (אם כבר קצר). אולי לשון גמרא (שאומר שקצר) משמע כן. הדרך לדחות את זה הוא לומר שר"ל שכבר התחיל לקצור, אבל לא קצר ממש.
- דע שבכל דיני שותפות אלו (שחילקו אחר כך), צריך לדון מה יהיה לצד המובא בביצה שיש ברירה ושכל שותפות הוא רק ברירה. אולי כיון ששותפים היו, אף שאינו שלו, יכול להפריש מזה על זה. ותחשב.
** מעניין מה שתולה
על של מי הוא כשקוצר אותו חצי שני, שהיה נראה לומר, אולי, שחייב על כל השדה כשהתחילו, ועל שעה זה נדון. ותחשב.
** טז. ראשון -
עיין איך מפרש למה קרא כן. קשה, אז, למה לא מפרש אמצע כמו כן ואומר שהוא בדרך כלל באמצע שדהו (שהרי אומר שמה שקצר כבר הוא בראשו).
** קצר -
כמובן, לשון מימרה זה מוזר, שלא קצר חציו.
** דר’ יהודה -
מעניין שיאמרו כן, שאין חולק על ר"י, לכאורה, שרק מפרש. ותחשב.
** חובת קציר -
צריך ביאור מהו שני צדדים אלו. נראה שצד הראשון הוא שחייב לוקח להפריש פאה, אבל יכול להפריש משדה חבירו (נותן לו שום זכות לזה). לשני, מי שנתחייב הוא השני. ויש לדון.
לפי זה, הראיה מראשית הגז הוא שצריך ליתן לו לכהן, ולא רק להניחו, ואז אי אפשר לומר שמפריש הלוקח, שאי אפשר להפריש משל אחר. ויש לדון, שאולי חייב ליתן של אחר. ואולי אם היה צריך לעושת מעשה, היה אומר כן. עיין בפני משה, שלשונו לא משמע כן. ותחשב.
לפי זה, אינו כל כך פשוט למה "הפריש" (למה חל כשמפריש לוקח), שהרי אין החיוב עליו. ותחשב.
** נשרף -
יש לדון אם אומר שנשרף, ואז אין חיוב שמה שהיה עליו החיוב בטל או שנשרף וממילא חייב להפריש, ואין מה לתבוע. ונראה, באמת, שהדין יהיה תלוי מתי נעשה (ויצאו, אז, שני דינים חלוקים בין שני הצדדים), והוא שאם נשרפו קודם שקצר שדהו, חייב להפריש, וכיון שאין שדה חברו קיים שיפריש ממנו, חייב להפריש משלו, ואין לו לתבוע (ודע שעדיין יכול להיות אם חבירו קוצר את שדהו, יוכל לתבוע, שאולי משעבד את עצמו שלא לעשות כן.), אבל אם פאתו על המוכר, יש לו לתבוע. גם יש לומר שאם הלוקח הוא המפריש, אז, יש לומר שכיון שקצר שלו, ולא של מוכר, יש מעשה הפרשה, אבל אם מוכר הוא המפריש (שכן הוא לצד שני), כיון שלא היה קוצר, לא עשה שום הפרשה עד שנותן אותו לעני, והרי לא הפריש עדיין. אז, עדיין יש חיוב פאה. ותו"ת.
** ג-ו לקצור ולשנות -
נראה שהמקור לזה הוא שתורה אמר שצריך לקצור ולשייר. אז, צריך להיות לו כדי קצירה ושיור. מה שלא אומר כר"ע הוא או שמניח שתורה אומר שהוא כדי לקצור באופן רגיל (דהיינו, שאף שיחייב בלי זה, כשדן תורה בדין פאה, מצבו שדן בו הוא מצב שיש בו אותו שיעור) או שסובר שצריך לקצור קנה שלם.
דיון גמרא אם צריך להיות קצרה רגילה הוא או דיון בתוך צד ראשון או שני (מה נחשב רגיל) או דיון אם הענין הוא ראשון או שני. מה שמוכיח ממה יש בו לשון קצירה משמע כצד ראשון.
לא נראה שפני משה אומר כן, שאומר לצד גמרא שצריך להיות רגילה ממש שצריך להיות ששניהם רגילים ממש. לפי מש"כ, הענין יהיה רק שראשון צריך להיות כן כדי לעשות חיוב על הנשאר. יש לדון כשאומר שלא לקצור שאר משמע שצריך להיות ששאר הוא ראוי להיקצר. ותחשב.
** רובע -
ואם תאמר למה לא לומדים מלימוד זה שצריך להיות סאה. יש לומר שזה שיעור למעלה, ולא למטה. לא מסתבר שנלמד שיהיה שיעור למעלה כאן, שלא  מסתבר שיהיה שיעור למעלה כאן. ותו"ת .
עדיין יש לדון  למה אין אומרים שיהיה שיעור של כאן רובע עם משהו, שרק בזה צריך להיות כלאים. יש לומר שאין זה שיעור, שאין צריך כן כיון שקרקע כזה חשוב, אלא כדי שיהיה בו שני דברים חשובים. ותחשב.
** צריך ביאור למה
לא ידרוש ר"י כר"א כיון שר"א דורש ממילה היותר דומה (ועוד שר"א מחמיר).
** ג-ז יז. חמש -
צריך ביאור למה נקט חמש, שהיה לו לנקוט מנין היותר קטן כמו שנים. ותחשב.
** ולכתוב עליו
- אין לה אונאה- יש לדון אם אומר שאין אונאה מפני שאין בו שוויות או שאין אונאה ולכן אין בו שוויות.
** יז: וידוי -
חולקים רש"י ותוס’ אם נגרוס את זה במשנה. תוס’ מביא ראיה שלא לגורסו מקושיית גמרא זה. אפשר שרש"י סבר שגמרא מקשה למה לא אומרו משנה (וכן נראה מפני משה כאן בד"ה שמעותיה).
** בשם חזקיה -
נמצא שיש שלש אמוראים שאומרים דיבור זה בשם חזקיה. צריך ביאור למה כולל שניהם לומר "שניהם אומרים בשם…" ובאחר לא אמר כן.
** מדוני -
אולי אפשר לבאר שמזכיר את מקומו כיון שר"ל שהיה גר (וזה לא רק היה מקום מולדו אלא אומתו), ולכן רצה ליתן (שלא היו לו יורשים).
** יח. תמן תנינן -
יש עדיין ראיה, לכאורה, מראיה ראשונה. יש לדון למה, אז, מביא זה:
1. אפשר שרוצה שני ראיות כדי שאם נדחה אחד מהם, יקיים על ידי שני. כמו כן מצינו בכ"מ גבי, “לימא תיהוי תיובתא נמי מהא.”)
2. אפשר שסובר שאין ראיה ראשונה כל כך חזק, שיכול לומר כדחיית גמרא.
3. אפשר שמקשה כאן- מקשה למה לא נאמר ראיה ממשנה. ויש לדון למה יותר טוב להביא ראיה ממנו. ויל"ד.
ויש לדון שלולי פני משה, אין הכרח לומר שמביא זה לראיה. ודע שלמש"ה פני משה על מה שאומר לשון, “תמן,” ולמה שאמר לבארו, לכאורה מוכרח שמביא ראיה, שאי לאו הכי, אינו מביאו מסוגיה של קידושין.
** קפץ -
יש לדון מה אומר:
1. אולי אומר שנעשה חולי מאד בלי תחילת חולי.
2. אולי אומר שהתחיל חולי, ונעשה רע מיד לאחר כן. ותו"ת.
** עבד -
לכאורה, אין זה שאלה לרבי ירמיה, שאינו צריך להיות קרקע. ויש לדון, שאולי דן גמרא אם זה דבר שמפרנסו אם חי, שבלי ממון אחר, אין כל כך לעשות אם עבד, כי אם למכרם או כדומה. יש אולי נקודה מוספת, והוא שאם היה רוצה לשייר כדי שימכור אם יבריא, היה לו רק לשאר ממון או לשאר מה שהיה קונה. ויש לדון, שאולי אין לו או כדומה. ותחשב.
** תני -
אם לא יודע, ק"ק למה אומרו כלל. יש לדון, שאולי חשבו שכשיזכירו אותו, יזכור אחד, ויזכיר את תלמידי החכמים.
** א"ר יוסי
- אם כתב קנין קשה למה יכול לחזור אם לא שייר. נראה שהענין הוא שיש שני חזרות:
1. אם מת, יכול לחזור בו קודם שמת, שרק מתנת שכ"מ הוא.
2. אם חי, יכול לחיות שרק נתן כיון שחשב שימות.
נראה שסובר שכתיבה רק מהני לראשון, ולא לשני, שהוא מקח טעות, וזה מקיים אף בקנין שבא על ידי כתיבה. ותחשב.
** יח: רב -
לא הבנתי, שרב הוא הסובר ש"ארכשיה אתרי ריכשי" (ואולי חולקים בדעת רב, שהוא רק בי רב בשם רב שם), ואם כן, צריך לומר שסובר שיכול לחזור במתנת שכיב מרע. אולי שם בלא שייר. גם יש לומר שכאן אינו כמה שאומר פני משה, אלא ראשון רצה לומר ראשון שנותן לו, ושוב נתנו לשני, ושב רוצה לחזור ממנו. כיון שכבר נתנו לשני מאחר, וגילה דעת חזקה שיהיה לו, אומר רב שלא יכול לחזור בו. ויש לדון. ולשון גמרא לא קצת לא משמע כן.
שוב הבנתי שלכאורה, דנים כשכותב לשון מתנה. ותחשב. (כן נראה מהמשך גמרא.)
** רבי יוסי בר"ח -
עיין בבלי שלא אומר כן משמו. ודע שאולי מסתבר, אז, שהוא האומר שמקולי כתובה הוא. אם כן, אולי בשיטת בבלי מסתבר לומר שאומרו  רק לריב"ח. ויש לדון, שכאן קאי על שמואל ורב, ואולי מסתבר שכן הוא אף שם. באמת, יש לדמותם גם כן לומר ששם בבבלי ריב"ח אומרו, אלא שכמו כאן, אומרו לשיטת כולם.
** ג-ז יט: הכותב -
יש לדון בביאור תנא קמא. אפשר שמניחים שאותו קרקע ששייר הוא העבד. יש לדון, שאם כן, זה שווה לר"ש. אפשר שהחילוק הוא שר"ש סובר שלא קורא אותו קרקע או מטלטלין (מה שכתבתי שהוא אף על מטלטלין הוא מפני שגמרא אומר שהדין הוא כן אף במטלטלין. היה אפשר לדחות שהוא אליבא דר"ש. הדרך לדחות זה לומר שר"ש לא סובר שנקרא קרקע או מטלטלים, אלא עבד.) יש לדון אם רבנן סוברים שהוא נקרא כן או שיכול להיות שמכוון לו אף שלא אומר שמו, שאומרו בלשון שמחנף לו. יותר נראה מפני משה שהענין הוא שכיון ששיר זה, שייר עוד, ואולי אף שייר עבד.
** וכשבא
- חוץ משדה- לכאורה, קאי לפי ר"ש. ויש לדון (שאולי כאן אי אפשר לומר שמכוון לעבד). ועיין במהר"פ.
** פרק רביעי ד-א כ. לא תכלה -
עיין במש"כ שהוא קרא מיותר. קצת מחודש למה צריך כן, שהיה אפשר לומר שכן משמע לשונו, שלשון לא תכלה משמע שלא לקוצרו, שמכלה אותו על ידי הקצירה. ויש לדון, שאולי "לא תכלה" אומר שלא יכלה את הפירות קודם שיתן אותו. ותו"ת. ויש לדון שאז היה לו לנקוט המעשה של נתינה; אבל בקצירה אינו כן, שאין מעשה נתינה, אלא שלא קוצרו. ויש לדון, שאולי יש מעשה של מה שמכניס עניים לשדהו. ויש לדון.
** דקטן מושל -
משמע שהענין הוא שאז אינו fair לקטן. יש לדון בזה (שלעולם אינו כל כך fair. ויש לדון.) לקמן משמע שהוא שיש סכנה. אולי לא אומר זה שם כיון שזה אינו סברה, ושם צריך סברה. יש לדון, עדיין, למה לא אומר כאן מה שאומר לקמן. ואולי אף שהוא חשוב בסברה, אינו, בדרך כלל, קרק’ כל כך חשוב. ויש לדון.
ודע שאפשר שזה רק סימן, ולעולם סיבה הוא מה שהוא סכנה. ויש לדון, שאינו, לכאורה, צירך סימן (וזה כמש"כ לעיל; ויש לדחות כמש"כ לעיל).
** דלית
- יש לדון למה יש בזה סכנה. נראה שכוונתו הוא לדבר שהוא על גב עצים או אבנים שיכשילו את הבאים עליהם. ותו"ת.
** קטן
- ובהם בעה"ב- משמע שבעל הבית, כשמחלקם, מחלקם בשווה. עיין לקמן.
** כ: סכנה -
יש לדון אם סיבה לדין זה הוא שצריך לחוש שלא ליתן אותם במצה סכנה, או שהוא דין בנתינה, והוא שהוא צריך ליתן אותו באופן שמהנה לעניים, אבל זה, אולי, ימית אותם, ולא מהנה אותם. ויל"ד.
** סכנה -
אין לומר, לכאורה, שיש סכנה ממש:
1. אם כן, אין צריכים קרא. יש לדון, שאולי כן מגלה קרא (רצה לומר, שמגלה קרא לאיזה דרגא של חשש נחוש, שהוה אמינא שאין כל כך סכנה כאן עד שצריך לחוש, ומחדש שהוא די. גם יש לומר שהוה אמינא שאין צריכים לשמור את עצמם מכסנה שהם עצמם מביאים על עצמם (שלא צריכים, ולא כפופים, לעלות באילן).
2. אם כן, לא יוכל בעל הבית לעלות. יש לדחות שכיון שיש רק אחד עולה, אין סכנה (למשל, לא יפול האילן, שאין כל כך כמה בני אדם עליו).
3. מהמשך המשנה, משמע שיכול לעשות שיבזבז אם כולם רוצים כן. קשה, שיש בזה סכנה. יש לדחות שיש סכנה רק מפני שכולם רצים וכולם דוחים זה את זה (כמו מעשה של פייס ביומא).
** אין תימר
- משמע ששאלת גמרא הוא מהו הנפקא מינא. קשה, שיש, כמובן, נפקא מינא פשוטה, והוא מתי יקרא שם. יש לדון, שזה מניח שיש חיוב לקרוא שמו ממש. אפשר שאין צורך לקרוא שם; רק רצה לומר שחל, אז, לפאה. ויש לדון.
** למעלה -
נראה שהיה יכול לומר שצדדים אלו תלוי באם הוא דין סכנה, שאז נראה שחייב בפאה כשהוא על האילן, וקורא שם אז, אלא שמדין סכנה, צריך להורידו להם, או אם הוא מדין נתינה, שאז חלק מנתינתו הוא להורידו, ורק אז יכול לעשותו פאה. ויש לדון.
** רבי מאיר -
קצת צריך ביאור למה אומר שלא דורש קציר, ולא שלא דורש לא תכלה. ותו"ת.
** רבי מאיר -
נראה, ונראה אולי שפני משה מכוון לרמז לזה, שהוא לשיטתו, שחושש למיעוט. ותו"ת.
** התנו -
צריך ביאור למה לא מהני; יהיה כמחילת כולם. יש לדון, שאולי של כל עניים הוא, והם לא מחלו. ויש לדון, שייאשו (ועיין בזה). גם קשה שאם כן, מה לי אם כולם התנו. נראה שאולי לא מהני מחילתם כיון שלא בא לידם. עדיין קשה למה מהני מחלו כולם. אולי הוא מפני שבידם לגרום כן. ודחוק.
לולי פני משה, היה אפשר לומר שלא דן כלל בדין ראשון של גמרא (אבל עיין לקמן בגמרא. ותחשב.), אלא בדין שני, שהוא באילנות גבוהים, שלא שומעים אף אם התנו, שכיון שזה לא רוצה בו, אף שכפוף לו, יגרום סכנה לאחרים (והוא על פי מש"כ שאולי יש סכנה רק אם רצים ומפסידים זה את זה). ותו"ת.
** מעשה -
במה שכתב שלכן גזר ר"ש, יש להעיר שני הערות:
1. אפשר היה לומר שר"ש אומר כן לראיה, ואותם שעושו כן לא סברו כמותו. ותו"ת.
2. מוזר לומר שגזר ר"ש; לכאורה, היה לו לומר שלכן ידע שיש בו סכנה. ותו"ת.
** מעשה
- היה אפשר לומר שאינו לסייע לר"ש, אלא לר"מ, שאף הוא סובר כמו ר"ש בזה (רצה לומר, יסמך שניהם, אבל אולי בא אגב ר"מ, או שבא לסייע לו. ותחשב.)
** שלא יראה -
משמע שלא מחלקו בשווה, אלא נותן לאיזה שירצה. עיין לעיל. וצריך ביאור למה לא יהיה הדין שצריך לחלקו בשווה. ותחשב. ואולי אין הכי נמי, היה אז, יכול, ואומר שמשנה מיירי כשלא רק התנו לחלק, אלא לחלק כן (שנותן בעל לאיזה שירצה). יש לדון, שאם היה הדין כן, מה בעיה אם נותן לקרובו; כן התנו. יש לומר שאולי לעולם, מחלק בשווה, ונחוש שיתן מנה יותר טוב לקרובו. ודחוק.
** ד-ב כא. נטל -
יש לדון למה קנסו אותו; לכאורה, לא עבר שום איסור ולא עשה שום דבר רע שנקנס אותו; חשב שיכול לקנות על ידי זה, ולכן ניסה לקנותו בזה. נראה בזה שני דרכים:
1. אפשר שלא קונסים אותו מפני שעשה דבר רע, אלא קונסים אותו כיון שרע שיעשו כן, והוא מפני שאם בני אדם חושבים שזה יקנה, יהיה בלבול רב מי קונה מה, וזה לא טוב. לכן, גזרו כדי שלא יהיו בני אדם עושים כן, ולא יהיו עושים כן וחושבים לקנות.
2. אפשר שלא מכוון כאן לקנות, שיודע שלא קונה, אלא מכוון לרמות את שאר העניים, שאומר שקנה אותו, והם יפחדו מאיסור גזל, ולא יקחו אותו. זה אינו fair (יש לדון למה. ואיני יודע מהו fair, אבל אני מדרהר שאין זה fair. אולי הוא מפני שהוא משקר. ותחשב.). לכן, קונסים אותו.
** נטל
- תלוש על המחובר- זה לאו דוקא, שאין צורך שיהיה מה שזרק עליו מחובר, שבין כך ובין כך אינו יכול לקנותו. רק נקט כן כיון שבדרך כלל, פאה שלא נלקט הוא מחובר, שאסור לבעל הבית ללקטו, וכשלקטים אותו עניים, קונים אותו. ותו"ת.
** נפל
- שאין- עיין לקמן (ובפרק קמא של בבא מציעא) שחולקים בזה.
** תני בשם ר"מ -
יש לדון אם זה אומר שתני ברייתא שאומר, “בשם ר"מ אמרו… " או שאומר שתנא ברייתא שאמר, “ר"מ אמר…" ותו"ת.
** ואפילו כריכות
- פני משה מפרש שזה מימרה. נראה שני צדדים אחרים שיכולים להיות:
1. אפשר שבזה משיב לשאלה, ואומר שלא רק בשוגג קנס, אלא אף בכריכות. ויש לדון, שאינו כל שכן כלל.
2. אפשר שאומר עוד שאלה, והוא ששואל אם הוא אפילו בכריכות. ותו"ת.
** במקדש ראשון -
כמובן, צריך להיות לאט הרבה כדי שלא יהיה בשום פעם עשיר. ותו"ת.
** ואני בעניי -
לכאורה, צריך לומר שאין הענין רק שעכשיו אינו בתוך ד"א, ואז אינו כל כך ברשותו, שהרי אם כן, היה יכול לאוקמיה כשהיה לו דבר שקנה על ידי משיחה, ושוב הוציאו מרשותו, והוא יושב על רשות הרבים, אבל עדיין שלו הוא. אלא, צריך לומר שאז עדיין נחשב ברשותו, ור"ל שהוא שלא לעולם נכנס לרשותו. ותחשב.
** על פשט ראשון ושלשי
של גמרא, צריך ביאור למה לא היה נאסר כיון שנתן יותר מחומש (לראשון, מוכרח שנתן יותר מזה, שאם נתן ראשון ראשון, ועיכב ארבע חומשים, לסוף לא יהיה עני. ויש לדון, שאולי אומר שהתחיל כשהיה עני. ודחוק מאד.. לשלשי, מוכרח כן כיון שאם לא כן, לא היה בעוני, שנשאר לו ממון הרבה לקנות סעודה, שלכאורה, אין לך סעודה שהוא גדול מארבע פעמים של זה. ויש לדון, שאולי רצה נכסיו לדברים אחרים (כן נראה קצת, שלכן צריך להשאיר אותו ממון- כדי שלא יעני. אז, אי אפשר, אולי, לאכלו ולבזבזו. ויש לדון.))
ואין להשיב שלא גזרו עדיין, שלעיל (ג.) אומר גמרא שהיה הל"מ שנשתכח, וחזרו ויסדו אותו. גם אין לומר שבימיו כבר נשתכח, ששם גם כן אומר שרבן גמליאל עשה כן קודם ששכחו.
** מתענה -
עיין במה שבאר. לולי רש"י, היה אפשר לומר שהקדיש סעודתו ממש (ואז צריך לומר שכשאומר זהב, רק אומר שוויותו), ולכן נתענה, שהיה צריך לשהות. ויש לדון, שהיה לו לפדותם. ויש לומר שהטורח היה שלא היה לו ממון על יד. כמובן, הוא דחוק. ותחשב.
** כא: מכתשים -
יש לדון, שאולי חלוקים מי בא קודם.
** מדעת אחרת -
עיין במה שאומר, שגבי רבי יוחנן מפרש שהוא שיש דעת אחרת מקנה אותו. זה אי אפשר, כמובן, גבי ר"ל, שאין כל שכן יכול להוכיח כן, שזה אומר מה קרה, ולא מה יקרה, ואז צריך לומר שם- וכן אומר פני משה- שאומר מה שיכול אדם לקנות לחבירו. מוזר שישנה בין שניהם. יש לדון, שאולי לא היה אפשר לומר מש"א בר"י בר"ל כמו שבארנו, ולא היה אפשר לומר מה שאומר בר"ל בר"י, שאין הוכחה מה סובר בזה. ויש לדון, שהיה אפשר לפרש שידע גמרא (מצינו כעין זה, שיודע גמרא מה סובר אמורא, אף אם אין הוכחה לו ממה שהובא בגמרא. ועיין בכעין זה ברשבם בפסחים). ותחשב.
** כב. וכן לענין
- רש"י מפרש שקושיית גמרא הוא שכל אלו הם בכלל מתנה. יש לדון, שאולי מקשה שהיה לו להזכירו. ויש לדון, שבין כך ובין כך (מה דינם), היה לו להזכירו. ויש לדון, שאולי כן מקשה. לא משמע כן, שאם כן, היה לו להקשות בלי ברייתא ודין שמהיא . ותו"ת.
** שרוק -
רצה לומר (כן יוצא מפני משה) שאחר כך נאבד, ואז מקויים מה שאמר. (לכאורה, או אומר שאחר כן נזרק לים או שמניחים (או שכן אומר, וגמרא שאמר דבריו אינו דווקא (ויש להעיר שלא ממש אמר דבריו; רק אמר שיכול לומר כל מה שרוצה. אם כן, אולי זה רק סימן והוכחה שיכול להיות שאמר שרצה בכל איבוד שיהיה), או שאמר כמו שאמר גמרא, ומניחים שכן רצה) שזריקה לים לאו דווקא, ורוצה אף בכל איבוד.)
** היא גיטין -
מסתמא, זה יהיה שייך ללומדות של קנין כסף בקדושין. ותחשב.
** ד-ג כדי שלא יכו
- עיין במה שאומר. גם יש לומר שאין חוששים שיכו זה את זה כשהם מקטטים, אלא חוששים שכיון שהם קרובים זה לזה, כשזה קצר, יכה את חברו. (המעלה לומר כן הוא שאולי לא מסתבר כל כך לחוש שאדם יכה את חברו במגל בדעת. ויש לדון.)
** שלש אבעיות -
יש לדון למה צריך להיות שבעל הבית שם:
1. אפשר שהוא מפני שרשותו הוא, ולא יכולים לבא שם שלא מדעתו. אז, צריך להתיר אותם לבוא; זמנים אלו הם זמנים שצריך להתיר אותם לבוא בהם.
2. יש להעיר שקצת מעניין שיקפיד על ביאתם לשדה שלו, שכבר קצר את הכל, שהרי נותן פאה. ויש לדון. (ויש להוסיף שאולי לכן מוסיף הא דמשפחת נמר, שאומר שאין לתמוה שנותן פאה בסוף, ולכן, לא יקפיד על ביאתם, ואין נפק"מ, שהרי יש שעושים(וטוב לעשות) כבית נמר, שהיו נותנים אף כשהיו קוצרים. ותו"ת.
3. אפשר שהוא מפני שצריך ליתן. זה טוען שצריך להתיר להם לבוא, ולא שיהיו מותרים ועומדים. ויש לדון.
** אבעויות -
עיין במה שפרש גמרא במילה זה. יש לציין לגמרא בראש בבא קמא (ג:) שאומר מקרא זה לשמואל שמבעה הוא שן, שהוא נגלה.
** שלא יפחתו -
שיש צורך לבוא באותם זמנים, שיש מי שצריך לקבל אז. אם לא בא, אותם בני אדם יפסידו, וזה רע. גם יש לומר שהוא כדי שידעו מתי לבוא, שיודעים שיבאו אז, ויהיה פתוח להם לבוא.
** שלא יוסיפו -
לכאורה, הוא שלא ירבה בזמנים כיון שיש עניים שלא יכולים לבוא באותם זמנים, ויפסידו כיון שיש אחרים שיכולים לבוא בכל שאר זמנים ויבואו אז. ויש לדון, שעדיין יהיה אותו בעיה, שאולי יפתח תחילה בבקר, והוא אינו יכול לבוא אז. ותחשב. גם יש לומר שהבעיה הוא שלא יודע מתי פותח תחילה, ואז, אף שיודע זמן אחד שפותח, יפסיד זמנו (כמו שאומר גמרא לקמן) כיון שישהה לתחלתו כיון שרוצה שלא יבואו אחרים לפניו ליקח את הכל. ותו"ת.
** בית נמר -
עיין בגירסת פני משה, ועיין בקרא שמביא. ק"ק איך לדחות אותו קרא, שאומר נמרה, ולא נמר. אפשר שמי שגורס כגמרא שלנו יאמר שאינו אותו משפחה של הקרא. גם אפשר שהוא שווה, וכמו שמצינו חילוקים קטנים בשמות (למשל, בני בנימין), אף כאן הם שווים. ותו"ת.
** נמושות -
לכאורה, זה מוכרח כרבי יוחנן בבבא מציעא (כא:) (כמו שאומר פני משה כאן), שאם אומר שהוא לקוטי בתר לקוטי, יכולים לבוא בזמן שבאו בראשונה. ויש לדון. ותחשב.
** הא אם רצה -
יש שני גרסאות בזה:
1. גורסים בגמרא, “הא… אינו פוחת.” לכאורה, אז, “הא" אי אפשר להיות דיוק, שלכאורה לא מדייק כלום. יש לדחות שאומר שלא יוסיף, וקל וחומר שלא יוסיף. ויש לדון אם הוא קל וחומר (עיין לעיל). ותחשב. גם יש לומר שאינו דיוק, אלא אומר אבל (כמו כן מצינו גמרא אומר בפסול צרת מחזיר גרושה (או כעין זה) בפרק ראשון של יבמות). אף זה קשה, שלכאורה אין אבל טוב כאן, שהוא דומה, ולא חלוק. יש לדון בכל זה, שלשון, ”אלא שלא … " משמע שהוא רק זה. ותו"ת.
2. גורס בגר"א, “הא… פוחת.” לכאורה, אז, אין תנא הסובר כמו שאומר פני משה להלכה (ד"ה אלא כדי שלא יפחתו). אפשר שהוא גורס כראשון. ותו"ת.
** לשבח -
עיין במה שאומר. קשה, שאם הפרישו באמצע, יהיה בעיה של רבי שמעון. יש לומר שהיה ידוע שעשו כן (שנקטו זמן קבוע), ולא היה בעיה. גם יש לומר שחולקים.
דע שלולי רש"י, היה אפשר לומר שהטובה הוא שלא יקטטו כל כך, והוא מפני שיש יותר פארימיטא"ר (כן הוא, שכל שיותר רבוע, יותר פחות בפורימיטא"ר). לכן, יכולים יותר עניים לבא, ולא יהיו כל כך clustered. כמו כן, יש לומר שיהיה נחלק יותר, ולא יהיו שנים או שלש עניים בראש שיקחו הכל, והוא מפני שיש יותר פארימיטא"ר, וכמו שבארנו. ותחשב. ותו"ת.
** לגנאי -
לכאורה, אלו ביחד כיון ששניהם בפאה. היה אפשר לומר עוד יחס ביניהם, ואולי שכיון שנהנו לעניים באופן אחד, הורו היתר לתת פחות. ותו"ת.
** ביטול -
לכאורה, אין בעיה של זה ושל גזל כאחד, שאם ישהו, אין גזל, ואם לא, אין ביטול. ותחשב.
** ויהא בורר -
צריך ביאור מה אומר בזה, שלכאורה, היה לו לומר שרק לא יתן. ותחשב. ואולי מניח שבני אדם יתנו כיון שצריכים, אלא שיורו היתר, ויתנו הרע, ויאמרו שכבר נתנו טוב. ואם תאמר מי שלו נתן ידע. ויש לדחות שלא אמר להם למה נותן אותם.
** לא תכלה -
עיין בגמרא שבת (כג:) שאומר שזה שווה לרמאות (ואולי כאן אומר שני מינים שני רמאות, והם שאולי לא יפרש כלל, ואולי לא יפרש מן הטוב. ותחשב.) . ועיין בגירסה שמביא פני משה.
** ד-ד במחלקת
- נראה שהענין הוא שבחד מקום אומר גוי שלא יכלה רק את חלקו, אלא שניהם יקצרו את כולו ביחד, ובחד מתיר לו לקצור את שדהו בפני עצמו. ותחשב. החילוק הוא או שבראשון כיון ששלט גוי (אף שבשני היה יכול, אם רצה, לשלוט), מיוחס לו ביותר, או שבראשון לא נחשב חלוק עד שמחלקים אותו ממש (אחר שקצרו), אבל בשני, נחשב כבר חלוק, שישראל קוצר בפני עצמו. ותחשב.
** שותפות -
צריך לדון למה אי אפשר לו לומר שמכר חלקו לגוי, והוא החייב. ויש לדון בשותפות. ותחשב.
** ד-ה שבשעת חובתם -
יש להעיר שמשמע שמה שמחייב במעשר הוא מעשה של גמירה, ולא מה שהוא נגמר, שהרי כשקונה מהקדש, הוא אז נגמר והוא בידו. ודע שאם הוא מעשה, יש לדון אם הוא צריך לעשות אותו מעשה או לא(מה אם קוף גמרו). ותחשב.
ועיין לקמן שדן בפעמים שנעשה ממילא (כגון הבאת שליש). אז, נראה שאינו המעשה אלא שינויה לזה. ותחשב. ואולי הוא מחמת נקודה זה שצריכים לכפלו. ותו"ת.
** כב: וכדברי הכל -
לא הבנתי מה אומר כשאומר שגמרא חוזר לומר שאולי יכול להיות אף לאחר מירוח, שלכאורה, לא שינה דבר בהכרח גמרא, ורק הוכיח שצריך להיות כרבע עקיבה או כרבנן, ורק לענין אותו לשיש. ותחשב.
** ד-ו יתננו לעני הנמצא ראשון -
יש לדון מה קורה:
1. אפשר שלא קונה אותו עני את הפאה, שאין לו כוח לזכות לאחר כיון שצריך ליתן אותו. יש לדון אם ענין זה הוא שאינו כל כך שלו, שצריך ליתן אותו, או שלא מניחים שממש רוצה ליתן לאחר, כיון שזה אסור.
2. אפשר שקונה אותו עני, אלא שעדיין יש חיוב ליתן אותו לעני, שלא סילק חיוב פאה בזה. יש לדון, עדיין, איך יכול בעל הבית ליתן דבר שהוא חפתו של עני:
  1. אפשר שכיון שעני חייב ליתן לו, ועומד זה לעשות, יכול אחר לעשות כן לו.
  2. אפשר שחיוב על בעל הבית דוחה קנין העני.
עיין בגמרא שמשמע שדנים באם קנה או לא. ויש לדון, שאולי רק דנים כמה קנה, אם קנה די לדחות חיוב ליתנו (ידחה או חיוב ליתנו, שיהיה שלו עד כדי כך שיכול לעשות עמו מה שרוצה, או שידחה יכולת של בעל הבית ליתן אותו, ורק עליו יש שום מצוה. ותו"ת.). ויש לדון.
** אדם זוכה -
יש לחלק, שכאן, לכאורה, כבר קונה אותו קצת, ואז יש לו יותר כוח עליו. (ודע שצריך לבאר קנינו בו, שאם ממש קונה אותו, לא יהיה יכול לזכותו לאחר, שאינו יוצא מרשותו. ותחשב. ואולי הוא שלו אבל, מחמת החיוב, אינו ברשותו, ואז נמצא שבא לרשות אחר כשמזכהו. ודחוק. ותחשב.
** דבר אחד -
היה אפשר לומר שר"א לא סובר כריב"ל, ופוסק כר"א, אלא שכיון ששמותי הוא, ונגד רבים הוא, לא מסתבר לגמרא שפסק כן.
** רבי יוחנן -
לא הבנתי הדמיון כל כך. ואולי מניח שמה שנעשה של אב כשהם סמוכים על שלחנו אינו מחמת שום זכות שיש לאב, אלא מפני שמניחים שמכוונים לזכות לו. אז, צריך להיות שמהני כשמכוונים.
** כג. לצדדים -
יש להעיר שאולי אינו כל כך קשה שמשנה על מי דן בלי לומר כן, שאולי דן על אותו אדם אחד, והוא הראוי, ורק זה שינה, והרי על שינוי זה, אין צורך לפרש שישנה, שהוא פשוט. ותחשב.
** מילתא דריב"ל -
ק"ק, שלכאורה, נמצא שהחולק סובר כרבי אליעזר. וקשה, שאם כן, רק חולקים כמי ההלכה במתניתין. ותחשב.
ואינו כל כך קשה לומר פשט אחר במשנה, אלא שהענין הוא שאז אי אפשר לחלק בין עני לעשיר. וצריך לחשוב מהו אותו פשט אחר.
** אפילו הפקירו -
לכאורה, זה רק נוגע כשהפקיר דבר שאינו לקט, שלקט לכאורה יפטור כיון שהוא לקט, וכיון שאין קנינו מפקיע מדיני נתינה, יש עליו דין ליתן. ויש לדון, שאולי זה רק רצה לומר שהפירות שווים לפירות א"י של ישראל, ויש להם אותו קדושה, אבל אין חיוב על גוי ליתן. אז, אינו נחשב לקט. אם כן, לא יפטור ממעשר.
** אפילו -
צריך ביאור למה אינו אפשר לו להפקיר. אולי רצה לומר שחייב ליתנו ללקט, ואז אי אפשר לו להפקיר. זה נגד מש"כ בד"ה אפילו הפקירו, ומה שהקשינו שם, אז, יהיה קשה כאן.
אפשר שכיון שקנינו אינו חזק כדי לשנות הפירות, רואים (או זה עושה) שאין בו כל דיני קנין, ואף אינו יכול להפקירו. גם יש לומר שמה שאין קנינו מפקיע הוא שאין לגוי כוח לפטור פירות, בין על ידי קנין, ובין על ידי, מחדש גמרא בזה, הפקר. ותחשב. ויש לדון מה אם מקדישו. אולי שם הקדש הוא הפוטר. ויש לדון, שכאן נאמר שהפקר הוא הפוטרו. ואולי כיון שאין מי שהוא הפקר, ורק יש מי שהוא הקדש, נוכל לתלותו בהקדש אבל לא בהפקר. וצריך ביאור.
** רבי יוסי -
מה שלא מהני עשייתו לקט הוא או שסבר שאף שאין קנינו מפקיע, זה רק לענין מעשר, אבל לא ללקט, או שסבר שאין חיוב עליו ליתן, אלא שיש לו קדושה.
** כג: קל הקילו -
לכאורה, החולק יאמר שחייב ישראל כיון שקונהו (רצה לומר, שכיון שיש מירוח ביד ישראל, חייב). לשון גמרא לא משמע כן כל כך, שלהפקיע מזה אומר שלקט רק עושה קולא. משמע שהחולק סובר שעושה חומרא. אולי אומר שעושה חומרא כיון שהוא העושה אותו של ישראל, וזה העושה חומרא. ודחוק. ותחשב. (אבל עיין בגמרא לקמן, שמשמע שכולי עלמא פוטר כשיש לגוי לבסוף. אם כן, לכאורה, צריך לומר שחולקים רק כשהוא של ישראל לבסוף. אם כן, אי אפשר לומר כמש"כ. ותחשב.)
** בביאור ר"פ
, עיין בגרח"ק שמבאר שמקשה שבין כך ובין כך, לא יהיה החיוב מעשר אלא דרבנן, שהרי יש לגוי קנין פירות. נמצא שאומר ר"י שמה שאינו ממש לקט פטור מן המעשר דרבנן הזה.; וכן נאמר לשיטה שאין לו קנין, שאף שם אינו ממש חיוב מעשר. (הוא מפרש בביאור סברת ר"י שהוא שאם יש לו קנין חייב דרבנן, ואז יקילו רבנן בלקט, ואם אין לו קנין, בהוה אמינא של גמרא, יחייב מדאורייתא, ואז לא יקילו רבנן. מפ"מ לא משמע כן, אלא משמע שהענין הוא שאם יש לו, פטור, וכיון שכן, אינו חייב במעשר כשהוא לקט. אז, נמצא שקל שהקילו לגרח"ק לא אומר מה שהאומר לפ"מ, שלפ"מ, לכאורה, אומר שאין סביה להחמיר מחמת זה, שהוא רק קולא. לרח"ק אומר שהוא סיבה להקל על חיוב דרבנן. ותחשב.
** ד-ז איזהו לקט -
שחייבתו- נראה שבא להפקיע ממה שהיה אפשר לומר שאולי לא מזכיר חיוב התורה של לקט, אלא קאי על משה שלעיל שאמר שלקט פטור ממעשר, אבל לא לקט של גוי, ואז מבאר איזה לקט פטור ממעשר, ואולי אין זה כל לקט שחייב בו. אז, מבאר פ"מ שמבאר חיוב תורה (או מפני שלא בא אגב זה, אלא אגב שנזכר לקט, מבאר מהו, או שכל לקט פוטר, ואז הם שווים).
** תוך היד -
וא"ת אם רואים עניים לקט, איך יוכלו ליקח אותו, ואיך לא חוששים שנפל מאחורי ידו. ויש לדון איזה יותר מצוי. גם יש לומר שאדם מכיר בנפילת לקט, ואם לא היה לעניים, היה קונהו לעצמו. ותחשב.
** שספק -
ואם תאמר, איך מותר לעני ליקח אותם, שדילמא אינו לקט. ויש לומר שחייב בעל הבית ליתן או למחול אותו לו (ואולי חייב בזה בכל לקט, כמו שצריך ליתן תרומה).
גם יש לומר שמחמת הספק, נעשה לקט ודאי, דהיינו שדין תורה הוא שלקט הוא מה שקרה מה שאמור במשנה לו או מה שאולי קרה לו כן.
** תוך -
יש לדון אם אחורי ידו הוא פטור בפני עצמו או סימן שנפל מחמת אונס. גם יש לדון אם הפטור הוא שהוא אחורי ידו או שאינו לפני ידו. הנפק"מ יהיה אם, לשום סיבה, קוצר בשני ידיו (ויש לדון, שאולי זה עצמו עושהו דומה לאחוריו, שאינו דרך קצירה, וכמה שאומר פני משה), שאז יכול להיות לאחורי יד ולפני יד. ותו"ת.
** שספק -
היה אפשר לומר שכולי עלמא מודה לזה, אלא שסובר ר"מ שחוששים למיעוט, ורבנן סוברים שהולכים בתר רב, ורב התבואה שהיתה שם לא היה לקט. ולא נראה כן מגמרא, שאז היה אפשר לחלק בין ציור זה לציור של ריב"ח. ויש לדון שאולי אף רבנן יכולים לומר כריב"ח, וגמרא רק אומר שר"מ בודאי אומר כריב"ח, שאף כשחושש למיעוט, לא נעשה יותר מספק.
** פרק חמישי ה-א אומדים -
צריך ביאור למה לא אומרים שספק לקט לקט. ואולי אין הכי נמי, רבי מאיר חולק על זה.
** רשבא -
לא הבנתי, שאם כדי נפילה אומר כדי שרגיל שיפול מאותו שדה, הרי זה שווה למה שהוא ראוי להיות לקט ממנו, שזהו לקט. ותחשב.
** קנס -
יש לדון מה עשה רע. אולי הוא שאפשר שחיסר לעניים, שאולי היה יותר מכדי לקט שם. יש לדון, שגם אפשר שהיה פחות. ותחשב.
** אפילו שוגג -
צריך ביאור למה מניח כן, שחלקו בכמה מקומות אם גוזרים שוגג אטו מזיק. ונראה שאולי לא פושט אלו מסברה אלא מסתימות משנה. אולי, זה יש לפשוט אך את זה כן (לומר שצריך להיות כתנא שאומר שיש לקנס שוגג).
** כה. דב"ש -
ואם תאמר מהיכי תיתי שהוא בית שמאי; הרי משנה לא אומר שהוא פטור ממעשרות, אלא רק אומר שצריך ליתן לעניים. ויש לומר שאם היה חייב במעשר, היה צריך ליתן שיעור לבאר כמה חייב במעשר וכמה פטור.
** הפקר בית דין -
צריך ביאור מה אומר, שלכאורה, כולי עלמא יודו לזה, ואין זה שייך לאם פטור ממעשרות. ותחשב.
** ומניין שהוא פטור -
צריך ביאור למה יפטור. אולי אומר שהפקירו את המעשר. יש לדון אם יש להם כוח לעשות כן. (נראה כן, שכן, לכאורה, עשה עזרא בתקנתו. ויש לדון.) עדיין צריך ביאור למה יעשו כן. אולי רצה לומר שלא עשו שינתן לעניים, ולא נתנו אותו להם, אלא עשו שאין שום אחר יכול לקנותו. ויש לדון, שאז אין צורך ליתן אותו לעניים- וזה מחודש. ותחשב.
** לא פטור -
זה מחודש, שהיה אפשר לומר שרק יש להם כוח להוסיף על שנה, וכיון שהוא שנת שביעית ממילא פטור. אבל, אולי כשמפקיר אותו, אין להם כוח לעשותו הפקר עד כדי כך שיש לו אותו פטור. משמע שדן אם בדר"כ דיני חכמים יש להם תוצאה זה. ותו"ת.
** לא פטור -
לכאורה, מניח שהוא פטור ממה שאומר עליו לשון מעוברת סתם, ולא אומר שאינו מעוברת לכל דיניו.
** אבל משהתיר -
לכאורה, עדיין יש בעיה של הפקעה ממעשר. אפשר שר"ל שבין כך ובין כך לא יקחו מעשר, שלוקחים מחו"ל. גם יש לומר שזה מהני רק בצירוף מה שהוא קשה. כן משמע מפני משה, שמביא טעם שמאריך עליהם איסור.
** עד כדון -
צריך ביאור מה שינה בין הוה אמנא למס’, שפשוט שיש לחכמים כוח לעבר שנים, שהרי דוחים י"ט מפני זה. אולי זה מחדש. גם יש לומר שר"ל שהוא כוח שהוא בפירוש בתורה, ולא רק נלמד מדברי נביאים, ואז הוא יותר חזק.
** כה: והוא -
לא הבנתי כל כך מה אומר, שפשוט שאם לא קצר סביבותה שכן הוא הדין, שהרי אז נקצר עם אחרים. ולולי פני משה, היה אפשר לומר שמחדש שהוא אף אם אינו נקצר עם אחרים, שאין קמה סביב לו, שאין כלום סביב לו; ומחדש גמרא שאינו נחשב ששכח אותו עד שיקצור מה שסמוך לו, אבל לא אותו. ותחשב.
** היתה -
כמחוברת- לשונו משמע שהעין הוא שכיון שיכול לקצר עמהם, נחשב חלק מהם. היה אפשר לומר שהענין הוא שאז אין להוכיח ששכחו ממה שלא קצר עם סביביו, שיש לומר שיקצור עם אלו, שנקצר עמהם. יש לדון, שאם כן, מה שאומר גמרא שאין צריך שאחרים נקצרים עמו הוא קצת פשוט. ויש לדון, שאולי הוה אמינא שכיון שעושה שיותר קשה לו, שצריך לקצור מצד אחד, לא מהני. ויש לדון. גם י"ל שהו"א כפנ"מ. גם נ’ שאולי פנ"מ לשיטתו, שלעיל לא אמר שענין סביביו הוא כמה שכתבנו, ונראה שהוא מפני שסבר שרק צריך שישכח, ולא שיהיה מוכח ששכח. אם כן, לכאורה, אף כאן, מה שאינו מוכרח ששכח לא יהני לעשות שאינו שכחה. (שוב ראיתי שגמרא לקמן דן בזה; אז, אולי רש"י לא רצה שמשנה יהיה תלוי בזה. ויש להעיר שציור זה קצת חלוק, שכאן אין חילוק בין אי זוכרו או לא זוכרו (שיעשה כמעט אותו מעשה), אבל בגמרא לקמן, יעשה מעשה אחר, ורק לא נודע אם שכחו. ותו"ת. ולא נראה, שמה לנו בזה. ותח’. ועוד עיין לקמן, שאינו כל כך פשוט מתי אומרים כן, שהרי אם אין שם חמישי, אןי אומרים שמיד נעשה שכחה. אז, עדיין צריכים להגדיר דין זה. ותחשב.)
גם יש להעיר שלפעמים (כמו בציור של פנימי וחיצון) מרבה עליו טירחא, שאין כלם נקצרים כאחד. ותח’.
** מתניתין… רבי הושיעא -
מעניין למה תלה אותו בר"ה, ולא בר"ח. ונראה שאולי לא מסתבר שהיה רבי יוחנן חולק על ר"ח, כיון שהיה ר"ח תנא (ואולי אף היה חבר של רבי). לכן, צריך לומר שכוונתו היה לומר שלא כן אמר ר"ח. אם כן, כמובן, אי אפשר להק’ על ר"ח.
** א"ר בין -
לא הבנתי למה צריך לשהות אם רוצה לקח שלש בבת אחת. ואולי לא גמר ששי עדיין. עדיין לא הבנתי למה אומר פני משה שלפעמים מתחיל מצד זה…, שהיה לו לומר שמתחיל מאמצע, ועושה אותם שלש שלש. ונראה אולי שמה שמסתבר שיעשה כלו בבת אחת, ולא ישהה ביניהם הוא מפני שהם קרובים זה אצל זה. אז, הדרך לדחות הוא שעושה מצד האחר. זה רק מסתבר אם יש ששי. יש לדון למה. ותחשב.
** דבר שאינו -
עיין במה שבאר פני משה בזה. ודע שהיה אפשר לדון אם הצד שלא מציל הוא שלא אפשר להציל או שבשכחת קמה, אף עומר נעשה שכחה, ואז, אין מה שיציל. מפני משה, נראה כצד ראשון. ויש להעיר שאפשר שזה רק אם זוכרו באותו זמן (שאחר ששכחו, והיה צריך לקמה, שוב זכרו).
וצריך ביאור למה יציל. אולי רצה לומר שכשהיה ניצול, והיה סמוך על הקמה, היה קצת בטל לקמה. אם כן, אולי עדיין דינו כקמה, ואז, כמו קמה מציל.
נראה לבאר אולי החילוק שבין עומר לקמה בהצלה לומר שהענין הוא שמה שהוא זכור לא די לעשות שאינו שכוח, אלא כל מה שהוא זכור עושהו פחות שכוח. צריך זכירה חזקה- רצה לומר שמחשב עליו, ושדעתו עליו מאד- לדבר כזה שרק נזכר אגב דבר אחר. אז, צריך להיות קמה, שכיון שצריך מעשה ואינו כל כך קל, צריך מחשבה יתירה. מה שיש מחשבה על הקמה מועיל לעומר או מפני שנעשה חלק ממנו קצת, ויש לו מחשבה שיהני לו, או מפני שמחשב על כל מה שעם מה שלוקט (וצריך לומר שזה מחשבה חזקה כיון שהוא מחשב על מעשה קצירה תמיד, שאז אף מחשב על מה שעושה עמו). נראה שאם נאמר כן, כיון שעליו מחשבת קמה, יכול לטור קמה. עדיין זה לא באר למה נשאר אותו מחשבה אחר ששכח את הקמה. ותחשב.
** רב יונה -
היה אפשר לומר שמתנה שאם הוא לקט טוב, ואם לא, יהיו מעשרות באחד משני שיבולות, שבודאי אין שניהם לקט, אלא שמה שאומר ר"י מצריך פחות שיבולות.
ולא הבנתי מש"פ פ"מ בר"י, שאולי זה שנתן הוא זה של מעשר, שאולי שניהם טבל, ואז רק הראשון מתוקן והשני, לא יכול לתקן בראשון, כיון שראשון כבר מתוקן. ותחשב.
** דר"י -
קשה איזה כהן יכול לבא כן ולומר לו ליתן לו ממ"נ, שהיה אפשר לומר שהיה נותן לכהן אחר אילו היה בכור. ותחשב. (ואולי מיירי בשמכיר כהונה הוא ורגיל ליתן שניהם לחד כהן). ותחשב.
** רב בא -
לכאורה, רב בא סובר שכיון שניתן לו חילופו, כהן מפקיע את עצמו. ר"ל לכאורה סובר שאין כהן מפקיע את עצמו. לכאורה, זה יהיה מפני שאינו יכול להפקיע את עצמו. לכן, צריך ליתן אותו לו, והוא יחזיר אותו.
ודע שאי אפשר לומר לר"ב שרק מפקיע את עצמו, שהרי אם כן יכול  עני לעשות אותו. אז, אולי הענין הוא שצריך שיגרום בכור שיהיה שה יתירה לכהן. קשה, שבדרך כלל אי אפשר ליתן תמורתו אם רוצה. ותחשב. ואולי הוא כמה שמצינו מושג שיכול אדם לשעבד את עצמו אגב הנאה שמקבל. ותחשב.
** יש לדון
מה היה ההוה אמינא של גמרא להוקים שר"א הוא כר"י. אם כן, צריך ביאור למה חולק ת"ק עליו. יש לומר שסובר כר"מ. (כן משמע ממה שלא ידע לת’ שר"ל קאי על רישא. ויש לדון, שאולי רק סבר שר"ל קאי על רישא וסיפא.) צריך ביאור איך זה יהיה, שלא נתן כלום לידיו, אלא רק נתן חליפי לקט. ותחשב. ואולי סבר שלקט חלוק משאר מתנות, והענין הוא רק שיהיה לעני מזון, ואז אין צורך ליתן לקט בדווקא. ותחשב.
** בשיטתם -
לא הבנתי כל כך למה כאן בדווקא יודו רבנן לר"א, שמה לנו שאף נותן שאר הגדיש; הרי נותן לקט, ולרבנן, זה דבר שאי אפשר לו לעשות. ותחשב.
** ושמין של בעה"ב -
זה מעניין. היה אפשר לומר שר"מ רק סובר שחייב ליתן לעני, ואף שמפסיד על ידי כך. אם כן, לא שומים הפסדו. מגמרא משמע ששומים ושנוטל אותו ממון (שאם לאו הכי, קשה למה שומים) מעניים. קשה למה יהיה כל החסרון לעניים. ואולי חולקים באותו הפסד. גם יש לומר ששמים רצה לומר ששמים כתנא של ברייתא, שאם של בעל הבית גדול, יכול לרבץ. (ודע שאם אמת הוא שמשלם עני לזה, יש לבאר על פי זה תנא של ברייתא, שכשהפסד של בעל הבית גדול, פשוט שאין ליתן לעניים, שרק יחייבו להחזיר לו. ותחשב.)
** ולמי הוא משלם
- בגמרא שלנו, אותו משנה נאמר אחר אותו דיון של גמרא. אז, אי אפשר לפרש כמה שאומר פני משה. צריך לומר שדן למי נותן מה ששם לחסר עניים. ק"ק למה לא פירש פני משה כן (שלכאורה, אותו שאלה שייכת; וכבר היה דן גמרא בזה, ואז היה לו להמשיך לשאול בו השאלה.).
** לעניי אותה העיר -
יש לדון למה חייב להם. משמע שלא חייב כיון שאכל מה שהוא של עניים, שאם כן, ישלם לכל עני שרוצה. משמע שחייב כיון שנמצא שאלו לא זכו בלקט שלהם. קשה, שזה גרמא. יש לומר שלקט רק שלהם, ששאר עניים כבר ייאשו. גם יש לומר שבעצם חייב להחזירו להיות לקט כדי שכל עניים יכולים לזכות בה, אלא הוא כעין "הפוכי מטרתא למה לי,” שיודעים שאם כן, עניי אותו עיר ילקטו את כולו, ואז אין צורך לטרוח לעשותו לקט ממש, אלא יתן לאותם עניים. ויש לדון, שעדיין יהיו חילוקים, כמו איזה עני מאותו עיר יקח אותם. ותחשב.
** יש לדון
אם יסוד חיובו הוא מחמת היזק (ששל העניים הוא) או שאולי הוא כמו מפני שיש סיבה שיהיה להם לקט (לא קנין, אלא סיבה אחרת שטוב שיהיה לקט שלהם). אם נאמר כשני, אז אולי יש לומר שעשה תורה שיהיה ענין צדקה של לקט באופן שכל עניים יתפרנסו, שיש לכלם עיר שלו קרובים. אם כן, יש לומר שכאן, כדי לקיים ענין שדחה, צריך ליתן לעניי אותו עיר. אבל, בדין, אי אפשר להוציא, שדין הוא רק על ענין ראשון. ועיין לקמן שנבאר בע"ה מעלת פשט זה.
** למדת -
לכאורה, אומר שאף שנראה כר"י מסברה, אינו כל כך פשוט, ולא נוציא ממנו מחמתו. זה מעניין, שלשון גמרא כשאומר סברת ר"י משמע שחושב שהוא דבר פשוט (שאומר שאם לא כן מה אנן אמרין, שאין צד אחר. ויש לדון שרק אומר שכיון שצריך ליתן לאחד, והם היותר טובים נותן להם, אבל לעולם יותר טוב אם היה נשאר בהפקרו הראשון. אם כן, לא אומר שפשוט לעשות כן, שמהו הצד האחר, אלא אמר שרק עושים כן מפני רעת צדדים אחרים (שכל רעה שיש לצד זה יש לצדדים אחרים עם עוד הוספות. ותחשב.). ויש לדון, שאולי לר"י היה פשוט, אבל רחב"א חולק. גם יש לומר כמש"כ בדיבור הקודם, והוא שכולי עלמא מודו שפשוט שלענין נתינה יש חיוב ליתן לעניי אותו העיר, אבל כשבאים לבית דין, לא על אותו חיוב המחייב כן באים, אלא על חיוב ממוני, ועל זה לא יכולים להוציא.
** שליש
- עיין במה שמבאר פני משה. נמצא שהחילוק הוא שמה שחייב ליתן ללקט אינו שלו. נראה שגם אפשר לומר שיש חילוק באם יש לו שום קנין על הקרקע (שכן יהיה אם באלו חלק מן הפירות, שלכן בא לו), או רק  במעשה ידיו. אולי חיוב לקט וכדומה באים מקנין על קרקע. לכן, כשיש לו שליש של מה שקצר, פטור. ותו"ת.
ועיין בלשון גמרא לקמן. ויכו"ל כשני הצדדים, אבל לכאורה אין סיבה שלא לומר כפנ"מ.
** על מנת שילקט -
יש לדון למה לא, שלכאורה, מיד אחר ששכחו אביו, נעשה לקט, ואז יכול בנו ליקח. ויש לומר שמשנה ממה שהיה עושה (לתת בזמנים מיוחדים, כמו שאמר גמרא גבי פאה לעיל), ונתן בזמן זה. גם יש לומר שעשה שלא יכנסו עניים אחרים באותו זמן. ואינו נראה, שאז אף בלי איסור של משלם שכרו בלקט, יש עוד איסור. ואולי אה"נ, יש עוד איסור. ותחשב על זה.
** בנו -
לכאורה, אין זה כל כך מסתבר לעשות, שמסתמא הפועל "ישכח" יותר, כיון שיודע שכל מה שישכח ילך לו. ויש לומר שחושש לאיסור גזל. גם יש לומר שיכיר בעל הבית אם מכזב. (גם יש לומר שהוא גוזל עניים כיון שלא יודעים שיש כאן לקט כלל. ויש לדון, שלעולם נאמר על פי כעין זה שגוזל (הוא יותר מהר, ולכן קבלם, או כעין זה).)
היה אפשר לומר שבנו אינו עני, אלא שלא נראה כן מפני שאז המשנה פשוטה.
** אל תסיג
- עיין במה שמבאר לשון כבוד. לולי פני משה, היה אפשר לומר שלשון סגי נהור אינו מחמת כבוד, אלא הוא מפני שלא רוצים לדבר על דבר רע (כמו שאומרים "שונאיהם של ת"ח שיושבים בד…"), ואז אומרים דבר טוב.
** הרי זה גוזל -
מעניין שמניח שעליו קאי לשון זה במשנה, שלכאורה, אומר משנה עליו שהוא אסור, ושוב אומר, “ציורים אלו… גוזל עניים.” ואפשר שאינו אומר שמשנה אומר כן, אלא מבאר שכן הוא. ויש לדון, אז, למה לא יאמר כן משנה. ותו"ת.
** פועל שעושה -
וא"ת למה נחשב גוזל עניים; הא בנו עני, ויכול ליקח. וי"ל שאסור כיון שמכניסו בזמן שאין עניים אחרים יכולים לבא.
** מבעה"ב -
מעניין שמחשיבו גוזל מבעל הבית, שאילו ידע בעל הבית, לא היה מנכה, שאסור לנכות. ויש לדון, שאולי כיון שזה היה עושה כן בין כך ובין כך, אינו אסור, שאינו גורם הפסד לעניים. ראשון, יש לדון אם זה אמת, שאולי אין הבעיה שגורם הפסד אלא שמשתמש ונהנה משל עניים. שני, יש לדון בהנחה שלא מפסיד אותם, שלכאורה, אילו לא היה רווח לפועל על ידי זה, אולי לא יעבור, ולא יקח את זה לחלק משכרו.
ונראה שאינו גוזל כיון שאילו היה אומר לו כן…, אלא זה רק סימן, והכוונה לומר שמה שבא לו מבעל הבית יותר גדול ממה שנתן לבעל הבית.
ויש לדון למה לקט נחשב דבר שבא לו מבעל הבית, שאין בעל הבית יכול ליקח אותו או ליתנו או לעשות שום דבר עמו. ואולי צריך לומר שמה שהוא ממש שלו (יש לדון בזה) עושה כן. ותחשב. (ומעניין שייחשב שלו, אף שאי אפשר לו להשתמש בו, שלכאורה, יידמה לו כאיסורי הנאה. ותחשב.)
