1. סוכה
2. א.
ע’ בב"ח, שכידוע סובר שצריך אדם לכוון בסיבת ההלכה, וסובר שהטור משמע כן. לכאו’, גמ’ זה משמע כשיטתו, שפוסל סוכה כיון שהוא לא יכול להכיר שה’ הושיב את בני ישראל. דבר ראשון, יש להעיר שלא פשוט לי שיוצא מזה שצריך לזכור מה בדיוק עשה ה’. ענין של סוכות הוא שה’ תמיד שומר עלינו, ותמיד נותן לנו כל מה שצריכים. אולי כיון שהוא זוכר זה, אף אם לא חושב על מה שקרה בפרט במדבר (אולי עכ"פ צריך לחשוב שדבר כזה קרה לבני ישראל כבר, אבל אולי לא על הפרטים), אולי יכול לצאת. ותחשב. דבר שני, נראה שנוכל לומר שזה רק בא להורות שיעור, ולא דין בכלל (כמו רש"י בסוף העמוד). אבל, רש"י רק אומר כן מן ההכרח (ע"ש, שפי’ שאם דירת עראי מהני, כל שכן שדירת קבע יהני). אז, לא נראה לומר כן כאן. אבל, עדיין אפשר לומר שהוא פסול כיון שצריך להיות "ראוי לבילה.” אבל, ישל דון, שאם הוא יותר מארבע אמות, הוא קצת "ראוי לבילה,” שעדיין יכול להיות שהוא יזכור על ידי ראייתו, אלא רק לא מצוי. ותחשב.
1. ב.
עיין לקמן בגמ’ (ז:) שמביא שיטת רבי יוחנן שצל יכול להיות גם מחמת הדפנות. אז, לכאו’, אם רבי יאשיה סובר כתנא זה של המשנה, מוכרח לומר כפשט אחר בו.
1. ג.
גמ’ דוחה מקור של רבא, ואומר שאותו פסוק אולי בא לידיעה של דורות. קצת צריך ביאור מה אמר גמ’. אולי בא לומר דין של הב"ח; בא לומר שצריכים דורות הבאים לדעת שה’ הציל את בני ישראל, ולא בא לומר שיעור. גם יש לומר שפסוק זה בא לומר את הטעם, כדי שדורות שיבואו ידעו. במילים אחרים, ה’ היה אפשר לומר לבני ישראל- אני הושבתי אתכם בסוכות, אבל רצה שכל זמן שישיבו בסוכות יחשבו על זה. אז, כאילו אמר להם- סוכה מזכיר לכם את זה, אבל אמר אותו באופן שאמת הוא, והוא ממש מזכיר לנו שה’ הושיב אותנו. ותחשב. עיין ברשי, שלא כל כך פשוט לי מה מכוון לומר.
1. ד.
בחרתי את הלשון שלי בדקדוק. הרי, היה אפשר לי לכתוב שכן יוצא מן הפשט של רבה, אבל לא נראה לי שזה מוכרח לפי הפשט של שלו. גמ’ רק אומר שמי שאומר קולא זו סובר כרבה. אז, מה שיודעים הוא רק שלפי רבה- ורק לפי רבה- אפשר לנו להקל על ידי זה. אבל, לא יודעים שמוכרחים אנו להקל. ותחשב.
1. ה.
בגמ’ (ב:) מפרש ש"רבי יהודה מכשיר עד ארבעים וחמישים אמה.” בכ"מ דן גמ’ בפירוש שיעור כזה, שיש בו שני שיעורים, אבל כנראה מחלקת הוא בסוף בבא קמא אם דווקא הוא. גם יש להוסיף סברה שאף אם שינוי שיעורים הוא דווקא, אולי כאן רק אומר גוזמא, ואינו דווקא. יכול להיות שרק מכשיר פחות מזה או שאף מכשיר יותר מזה. צריך לעיין בזה.
1. ו.
עיין בצד זה. נמצא שסומך על הפסוק, אף שאחרי שיש לנו הל"מ, הפסוק אינו מדוקדק, שאינו מגן בעדו אם צד אחד הוא רק טפח. אפשר לומר שמה שטפח הני הוא ש"רואים אותו" להיות מחיצה מלאה. (איני מבין ענין של רואים; הייתי אומר שהוא ממש שרואים, דהיינו שהוא כשר כיון שהוא נראה בעיני בני אדם כן. אבל, אולי אינו כן; אולי יש ציורים שמשמע שאינו כן. ותחשב.) אז, רואים אותו להיות דבר שמציל. ותחשב.
1. ז.
בשי"ח ש"י הערנו על רש"י זה, וכתבנו:
“מענין שכלום יכול לבטל דבר (יש לדון, שאני מניח שהאויר מבטל את הסכך; אולי גמ’ משמע ששמש מבטל את הצל. ותחשב מה זה אומר.). לולי רש"י, הייתי אומר שצ"ל בעל צל, ואז צריך להיות רובו צל. כנראה, ראשי סובר שזה לא יפסול, כיון שהוא יושב תחת צל, אף שיש מקומות בסוכה שאין בהם צל. כמו כן, יש לומר שכיון שמה שלא מביא צל הוא רק אויר, נוכל לומר שכולו סכוך. דחוק. [ודע שאולי זה נוגע למה שדנינו ביישוב הסתירה.]”
1. ח.
גמ’ מקשה שאולי יכול אדם לשבת בתוך סוכה שתחת סוכה, כיון שכתיב "סוכות.” מענין, שהפסוק אומר שישב בסוכות. הרי, אם הוא יושב בסוכה שלמטה מסוכה, אינו יושב בסוכות, שאינו יושב בעליונה, אלא בסוכה שתחת סוכה, שרק יושב בתחתונה. הראיה לזה, שישיבה שלו הוא בתחתונה, הוא מה שאומר רש"י שמודדים את העשרים אמה (של גובה, לפסול את הסוכה) מגג של סוכה ראשונה). נראה שיש שני מהלכים לדחות. אפשר לומר שיכול להיות שני קרקעות לו. כל מה שלמטה מן הגג- ואף מה שהוא בתוך סוכה התחתונה- נחשב בתוך סוכה העליונה. אבל, לא מודדים משם למי שעומד בקרקע גבוה שלו (בגג התחתונה). נמצא שלא תמיד מודדים ממקום הכי נמוך שבסוכה, אלא אם הוא על הגג, מודדים משם. ותחשב. גם אפשר לומר שגמ’ לא מקשה שלא נוכל למעט יושב בסוכה שתחת סוכה מכאן, אלא מקשה שנלמד מן הפסוק שהוא כשר. במילים אחרים, אומר לדרוש את הפסוק לומר שיכול לקיים את מצוותו אם יושב בתוך שתי סוכות. זה יוכיח לנו שני דברים. ראשון, יוכיח לנו שיש ציור כזה, ומזה נראה שסוכה עליונה מודד מן התחתונה, ושני, יוכיח לנו שציור כזה כשר. אפשר לומר (ואולי זה יכול להיות מהלך שלישי) ששני דברים אלו- מאיפה מודדים ופסול סוכה התחתונה- שייכים זה לזה. אם נאמר שפסול לא בא כיון שהוא תחת גג של סוכה עליונה, אלא כיון שהוא תחת סוכה עליונה, יש לומר שאם אינו תחת כל סוכה העליונה, אלא הוא חלק מסוכה עליונה, לא ייפסל. ותחשב.
1. ט.
בשי"ח ש"י כתבנו:
“יש לדון אם סובר גמ’ שיותר פשוט לפסול סוכה הנעשה בתוך בית, ורק מדייק ממה שמביא הדמיון, או לא סובר כן. אם סובר כן, יש לדון למה הוא נכון. ותחשב. אם לא, מימרא של המשנה קשה להבין, שאז יוצא שאמר דבר שאין בו הבנה, שכאילו אמר: “ציור שאין אתה יודע בו הדין, הרי דינו שווה לציור השווה שאין אתה יודע בו הדין.” אפשר לבאר שהמשנה מניח שכבר יודעים את פסול של "בסוכות,” ומה שבא לומר הוא שהפסול של עושה סוכותו תחת אילן הוא רק אם הוא כעושה תחת הבית. נראה שיש מהלכים שונות לקרוא את זה לתוך במשנה. אולי אומר שהעושה סוכה תחת אילן, כעושה בתוך הבית, במה שבשניהם יש פסול רק אם צלתו מרובה מחמתו. כמובן, זה קצת קשה, שאין ציור חוץ מזה בבית, ולא פשוט שנדמה דיניהם לומר ככה, ולא לומר שבכל ציור פסול. גם אפשר לקרוא שהוא שאומר כעין "כיצד,” שאומר: “העושה סוכתו תחת אילן [שהוא פסול, מהו הציור: כשהוא עושה אותו באופן שהוא] כאילו עשה אותו בתוך הבית.” ותחשב.”
יש להעיר גם כן שלא נכון שהוא דומה לשל בית, שיש גם פסול השני שבארנו למטה על המשנה. ותו"ת.
1. י.
יש הרבה בעיות בענין צירוף זה ובענין ביטול זה, ובשי"ח ש"י הערנו על זה. גם יש להעיר שממה שמשנה רק פוסל אם צלתה מרובה מחמתה, צריך לומר שהמשנה מדבר בשחבט אותם. אבל, אז צריך ביאור למה הוא סוכה שתחת אילן, שהוא סוכה שסככה מצורף עם צלת אילן (שלכן יכול לבטל). יותר מזה, אף אם צלתה מרובה מחמתה יהיה כשר, אם מרובה צילת הסוכה, שעדיין יבטל אותה. וצריך לחשוב על זה.
1. יא.
כן הנחתי, אבל לא מוכרח, שאולי כשאומר רבי יהודה שצריך להיות שראוי לדור, משמע שהוא כל ציור שיכול לדור, ואף על ידי הדחק, וזה מה שבא להוסיף. יש לדון.
1. יב.
במשנה הבאה (י.), רב חסדא יאמר שסדין שעל הסכך הוא רק פוסל אם לא נעשה כדי לנאות (יש לדון אם רצה לומר שמנאה את הסוכה או את הסכך; מרש"י נראה שהוא לכל צורך חוץ מלהיות גג). יש לדון אם זה נכון גם במשנה שלנו. כמובן, לא נמצא ציור כזה בבא ראשונה, אם לא שנחדש שאילן הוא כן, כיון שלא נעשה לשום דבר, או שנחדש שתלוי במחשבתו בבנין הסוכה תחת האילן. אבל, עדיין יש לדון בבבא שנית. עיין ברש"י שם, שמבאור שסובר שלפי רב חסדא אינו נכון, ובין כך ובין כך פוסל, כיון שהוא פסול אחר לגמרי, שהוא סיכוך על סיכוך, ושם הוא, לכאו’, ביטול סכך הכשר, כמו שנבאר בע"ה. אבל, נראה שיש לדון בזה, שרש"י לא נראה מוכרח לנו, שהוא מדבר בסכך על סכך, שהוא סכך למטה. אז, יש לומר שרש"י דוחה אותו פשט שמביא כיון שמוכיח שאין סיכוך על סיכוך אם הוא למטה מסיכוך הכשרה, ולא על גבה. אבל, אם סיכוך שבו רוצה להכשיר הוא התחתונה, אז מה שלמעלה ממנו הוא סיכוך על סיכוך. אם כן, נוכל לומר עוד שהיתר של רב חסדא קיים. ותחשב על זה.
1. יג.
יש לדון בזה. רשי, באמת, רק מזכיר זה להקשות עליו בציור שני של המשנה. אז, אפשר שרש"י רק חולק בסיכוך על גב סיכוך כיון שסכך הכשר האו למעלה.אבל, אולי כאן יודה לטעם זה. אבל, לא כל כך מסתבר לומר שסמך אותם במשנה, ובפרט כיון שמשנה שלפני זה מדבר בסיכוך על סיכוך, והיה לו לשים את בבא ראשונה של משנה שלנו בתוך משנה שלפניה. ותחשב.
1. יד.
רש"י לא מבאר מהו הפסול. נראה לי שני מהלכים. מהלך ראשון הוא שסכך הפסול מבטל את סכך הכשר. לכאו’, אין זה כל כך פשוט, שצריך להיות שסכך פסול יותר גדול מסכך הכשר. הרי, צריך ביאור איך למדוד גודל של דבר, אבל לא נראה שבדר"כ סדין יותר גדול. גם נראה מחודש שנחשב תערובת עד כדי שבטל, אבל גם היה נראה מחודש לומר כן באילן, ועדיין אמר כן הגמ’. גם אפשר לומר כמו שאומר רש"י לקמן, והוא שלא יושב בתוך סוכה, אלא בתוך דבר אחר. אבל, לא נראה כן אם נאמר שרש"י חולק על ביאור של סיכוך על סיכוך לשני הדברים שבמשנה, שאז צריכים לבחור אם יושב בתחתון או בעליון, ולא נפסול בשניהם. יש לדון, שאולי לא כל כך יושב בסוכה כיון שגם יושב בעליון. דחוק. גם אז קשה למה צריך פסול סיכוך על סיכוך לאילן. יותר נראה לומר, אם נרצה לומר את זה, שסדין הוא מאד חשוב, ולכן בו הוא יושב. עדיין יש לדון, כיון שהוא כל כך קרוב לסכך. ותחשב.
1. טו.
כן אומר רש"י, ומקשה עליהם קושיה חזקה. צריך ביאור מה אלו השיטות משיבות. נראה שיכול להיות שני מהלכים. מהלך הראשון הוא שכאן לא צריך ארבע טפחים (או מפני שהוא למטה ממנו או מפני שסדין הוא, אולי, סיכוך חשוב). מהלך השני הוא שרק אמרו כן בבבא ראשון, ורשי מניח שאם הוא נכון בבבא ראשון, צריך להיות גם בבבא שני, ולכן מקשה. אז, זה נוגע לביאור של בבא זו.
1. טז.
לכאו’, כאן פשוט שהפסול יכול להיות שני הדברים שהזכרנו לעיל (באות יד).
1. יז.
נראה שיכולים לבאר את זה בשני דרכים. דרך הראשון הוא שכיון שהוא בא מחמת סכך (או כיון שהאו בא מחמת סוכה) בטל הוא לסכך. השני הוא שכיון שלא בא לצל, אלא רק לנאות, אינו כל כך חשוב לפסול. ההגדרות (איזה סיבות יפסלו ואיזה סיבות לא יפסלו) ייתלו בזה.
1. יח.
יש לדון אם זה נוהג גם בבבא ראשון של המשנה. גמ’ רק אומר כן על השני, וממה ששהה עד שם לאומרו (יש לדון; עיין בתחילת נדרים ונזיר) נראה שרק שם נוהג. מן הסברה גם כן יש לדון. ויש להוסיף שאולי כמעט לא נוגגע בראשון, שלא ייעשה שם כדי לנאוות אותו. ויש לדון, שאולי לנאותו אינו דווקא, כמו שכתבנו בהוספות אות יז. גם אפשר שהוא עושה אותו נאה לבני חוץ. ותחשב.
1. יט.
מי שאומר שפסול משמע שהטעם להכשר הוא שבטל לסכך. אז, אם הוא רחוק מן הסכך, לא בטל.
1. כ.
רש"י מעורר שלפי זה, מרבים גם בהמות, ואז יכולים לסכך בעורות. אבל, רש"י אומר, זה רק לפי הצד הזה. כשחוזר גמ’ מן הצד הזה, גם חוזר מן אותו הדין. נראה שאין זה ממש מוכרח. תחילה, יש להעיר שלא נכון שאין חגיגה מקבל טומאה, שהרי חגיגה הוא בשר, ומקבל טומאה. אז, צריך לומר שלא מדובר בבהמה שחוטה, אלא בבהמה חיה. אז, נראה שאפשר לומר שרק בהמה חיה נחשב, לפי פשט זה, להיות גדל מן הארץ. הביאור יהיה שכיון שהבהמה נשתנה כל כך מחיותה למיתתה, אומרים שהבהמה המתה לא באה מן הקרקע, אלא באה מן הבהמה. ותחשב. אז, נראה שנוכל לומר שזה רק מגלה לנו שיכולים לתת בעל חי ממש על סוכה, ואכן אולי יכולים. ותחשב.
1. כא.
כן אומר הגמ’. ודע שאפשר לומר שבאמת מחלקת תנאים הוא, כמו שמצדד גמ’, ואז לא צריך להוקים אותו בריי’ ככה, ואז אולי רב מכשיר בכל אופן, אבל כיון שאין סיבה לחשוב שגמ’ חזר מזה, וגם אין סיבה לחשוב שתנאי הוא, לא נראה לומר כן.
1. כב.
עיין במשנה ראשונה, שבארנו איך שרש"י משמע, והמשנה משמע, שכדי להכשיר צריך להיות רק מחצה ומחצה. אבל, גמ’ כאן לא משמע כן. ותחשב.
1. כג.
ע’ בלשון גמ’ שהוא שמראה שהוא רק לכת’ כיון שמדאו’ כשרה. יש לדון אם מדרבנן כשרה או לא כשרה. היה נראה שאינה כשרה, מקונטראס"ט עם סיפא. יש לדון, שאולי זה אף אם כיוון לשם צל. ותחשב. ועיין בלשון הגמ’.
1. כד.
יש להעיר שאז "כולם" ראשון שונה מ"כולם" שני. ותחשב. לולי רש"י הייתי אומר שהוא מדבר בכל החבילים, והוא הדין לכל סכך כשר. אולי לא היה לו לומר אותו באופן שצריך ללמוד ממנו, כיון שזה רק פסול מדרבנן. (יש לדון, שנזכר גם פסולים דאו’ במשנה. ויש לדון, שאולי כשאומר לשון לכתחילה, רק מדבר על דין דרבנן, אבל לאידך גיסא אפשר שרק כולל דין דרבנן עם פסול דאו’. ותחשב.) גם אפשר לומר ש"כולם" כאן הוא רק בפסולים דרבנן, ולא בא להכשיר סתם דפנות, אלא דפנות המעמידים סכך, ואומר שזה פסול בסכך הפסול, אבל כשר בסכך הפסול בדרבנן. איני יודע אם זה הדין.
נראה שאולי קשה לרש"י לשון "כולם" הראשון, כמו שהערנו בפי’ על המשנה. אז, אולי אומר שהוא אגב סיפא. אז, לא יכולים להוקים את הסיפא כשאותו הקושיה עוד קשה. ותחשב.
1. כה.
אז, יוצא לנו חידה. באיזה זמן מכשיר אדם סוכה על ידי קציצת סכך? אם היה מחובר. באיזה זמן פוסל אותו על ידי קציצת סכך? אם על ידי זה עושה אותו לאגוד של שני דברים.
1. כו.
לא כל כך פשוט לי מהו החילוק בין פחות משלשה טפחים לגדול שלשה טפחים. מתחילה, אומר גמ’ שאם פחות משלשה טפחים הוא, אינו פסול כיון שאינו נסר אלא קנה. לכאו’, משמע שהענין הוא שאין שמו שווה. אולי רבנן רק רצו לגזור על דבר אחד, ואז גזרו על "נסר,” שיש בו המכשול הכי גדול. גם אפשר שכיון שיש לו שם שונה, בעיני בני אדם שונה הוא. אבל, לקמן גמ’ תולה את זה בדין לבוד. לא כל כך מסתבר לומר שזה הסיבה לשינוי השם, בפרט לצד שני, שאז תלוי בדרהר של בני אדם. מחודש לומר שכיון שיש הל"מ של לבוד, יש שינוי בדרהר של בני אדם. אבל, יש להעיר שכל ענין לבוד בזה מעניין, שלא מצאנו לבוד אמיתי בזה, שאומרים לבוד להמשיך דבר כשאין דבר שם. אבל, כאן, כבר יש דבר שם, ולא מובן מה לי לבוד. ותחשב על זה.
1. כז.
קצת צריך ביאור, שעיין בגמ’ בב"ק (עג) שקורא לעצים משופים כלי. צריך לומר שהוא כלי אבל אינו מטמא, שהוא נחשב כלי (ששם רק צריך לבאר אותו בלשון המשנה), אבל אינו מקבל טומאה, כיון שהוא פשוטי כלי עץ, ואין בו בית קיבול. ותחשב. גם אפשר לומר ששם רק עומד להיות כלי, וזה מספיק. דחוק. יותר נראה לדחות, אם נרצה לדחות, ששם מדובר בעצים שכבר יש להם בית קיבול. ותחשב.
1. כח.
לא פשוט מהי ההגדרה של גזירה זו. הרי, יודעים שגמ’ אומר שיהיה אוסר סיכוך בחיצים זכרים (שאין להם בית קיבול) מחמת סיכוך בחיצים נקיבות (שיש להם בית קיבול). יש לדון אם זה רק מפני הדמיון, ואז לא נותן לנו הגדרה חשובה, או שההגדרה הוא שאוסרים כל דבר שהוא כלי, אף אם אינו מקבל טומאה. ותחשב.
1. כט.
עיין שם בגמ’, שמוכיח שרב לא סובר כן ממה שמכשיר כלים. צריך עיון למה לא אומר שרב מכשיר כרבי יהודה. צריך לומר שיותר יש לגזור באותם שאומרים רב, ולא מסתבר שיהיה הרחק כל כך גדול בין שיטת רבי יהודה ורבי מאיר. ותחשב.
1. ל.
הביאורים שנזכיר כאן הם הביאורים שנותן הגמ’ בדיון שלו על המשנה. אבל, יש להעיר שאותו גמ’ מניח כצד ראשון בגזי’ המשנה- שהוא גזי’ מחמת תקרה של בית- ומפרש כאותו הצד. לא פשוט איך נפרש הרבה דברים לפי צד השני בגזי’ המשנה (שהוא גזי’ מחמת כלים). צריך לעיין בזה.
1. לא.
יש לדון אם זה נכון גם במסקנא. כן אומר, אבל אומר כן כדי להשיב לקושיה, וגמ’ מוצא תשובה אחרת. אז, אולי לא מסיק כן. (זה יותר טוב כפי מה שהערנו שיש בעיות גדולות בזה.) אבל, לא נראה כן כל כך, שרבי יוחנן אמר שזהו התי’, וכנראה סבר שאין תי’ אחר תי’, אלא זהו התי’, ולמה נניח ששמע שאר התי’ אחר כך וחזר בו מחמתם. ותחשב.
1. לב.
אני אומר כן כיון שגמ’ תולה את מחלקת הזה במחלקת אמוראים בעומד כפרוץ. צריך לעיין, שגמ’ מסיק נגד זה בחולין, ואומר שם (לענין מחלקת אחרת) שמוכרח שצריך רוב. וצריך לעיין. באמת, לא פשוט למה נחשוב לדמות אותם. וצריך עיון. יותר מזה, נראה שמחודש לדמות פרוץ ועומד לכשר ופסול, שפרוץ הוא מה שאין דבר, ולא שיש דבר פסול. ותחשב.
גם יש להעיר שדנינו לעיל במחצה על מחצה (על משנה ראשונה). לכאו’, מגמ’ זו יוצא שהוא מחלקת אמוראים. אז, יש לדון למה רש"י נקט לפרש כמי שמכשיר. מסתבר לומר שרש"י הולך כפשטות של המשנה הזאת.
1. לג.
אין זה פשוט. הרי, גמ’ בב"ב אומר נגד זה במציאות (ואף מקשה עליו). לכאו’, נראה לומר שיש חילוק בין אם פתוח מן הצד לאם הוא סגור מן הצד. הרי, שם מדובר בארון, והיה סגור מכל צד (חוץ מלמעלה). כאן, מדובר בסכך, ואפשר לומר שלא מכניס אותו לתוך עובי כותלי הסוכה, ואז נמצא שפתוח מן הצד.
1. לד.
יש להעיר שעדיין יש להקשות שהכשר שווה לפסול, כיון שמדובר כשלא מצמצם. צריך לומר שהוא מצמצם את הכשר. אז, נמצא שנצטרך לומר שכשאומר שיש רווח לכיוצא בו, רצה לומר שיש רווח לכיוצא בו אם לא מצמצם, אבל למעשה מדובר כשלא מצמצם. דחוק. אולי צריך לומר שלא מצמצם, אלא שאומרים לבוד, וזה עושה סכך כשר, ולא סכך פסול. יש לדון, שחולקים אמוראים אם אומרים לבוד באמצע הסוכה. ותחשב.
1. לה.
לכאו’, יש לדון אם הביטול הוא בחפץ או בצל. אם הוא בחפץ, הביאור יהיה שמסתבר הם שווים בגובה, והרי סכך הכשר גדול ברוחב. (אבל, כיון שהוא על גב סכך הפסול, ק"ק למה מניחים שהם שווים.) אם הוא בצל, הביאור יהיה שיש שני מיני צל- מה שבא מן הכשר ומה שבא מן הפסול. יש חלק מן הצל שבא משניהם, וזה מיוחס לשניהם. אז, יוצא שבין הכל יש יותר שמיוחס לכשר. ותחשב.
1. לו.
עיין שם וברש"י, שאין זה כל כך פשוט. יש להעיר שאם זה נכון, מעניין שלא מחלקים את המעשה שלו לשנים אלא אם כן כבר היה טפח מלפני כן. ותחשב. אפשר לפרש שרש"י אומר שאין זה מעשה המכשיר, אלא זה מעשה המתקן. (לכאו’, אין מעשה המכשיר, ואין זה פוסל אותו. מעניין שייפסל כשיש מעשה המכשיר בדבר חוץ מן הסכך, אבל לא כשאין מעשה המכשיר. ותחשב.) צריך לומר שאף אם חטט מלפני כן, אין זה מעשה המכשיר כיון שאינו כשר. ותחשב.
1. לז.
יש לדון אם זה פוסל אותו מדאו’ או מדרבנן. לכאו’, זה תלוי באם יש דיחוי אצל מצוות לקולא. אף אם יש דיחוי, צ"ל שאף שלפעמים להיה נראה קודם שנדחה, עדיין פסול. חולקים אמוראים גם בזה. אבל, לא קשה לומר שהוא מדרבנן, כיון שהוא דומה לכלי.
1. לח.
יש לדון מה לנו בהליכת גדיים. אפשר לומר שזה מוכיח שאין מחיצה שם, שיש חילוק גדול בין אם היה מחיצה שם לאם אין מחיצה שם. אז, אי אפשר לראות אותו כאילו הוא שם. גם אפשר לומר שהוא מפני שמחיצה הוא דבר השומר. הרי, כיון שגדיים באים לתוכו, לא שומר עליו. ותחשב.
1. לט.
אם הייתי ישיביש, הייתי דן אם רבי יוסי סובר שרואים שאין גדיים יכולים ללכת תחתיו או שלא איכפת לו שגדיים יכולים ללכת תחתיו.
1. מ.
איני יודע למה צריך לזה, ומהיכי תיתי שצריך שהמחיצות יגעו בסכך. אבל, למעשה פוסלים במרחיק אותו שלשה טפחים במשך. צריך לומר שידוע שצריך להיות יחס כזה בין מחיצות לסכך. מסתמא הוא מפני שעיקר סוכה הוא הסכך. הרי, ידוע שצריך להיות לסוכה- דהיינו, לסכך- שלשה דפנות. אם אינו “לסכך,” כיון שהוא רחוק, אין לסוכה שלש דפנות.
1. מא.
כתבנו את זה באכסדרא כיון ששם הוא שהגמ’ מדבר בה. החילוק שיש בין אכסדרה לבית בזה הוא שיותר קל לומר אותו בבית כיון שדפנות נעשים לתוכו. (כן נראה שיוצא מן הגמ’, אבל איני מבין אותו, שלא מדובר כאן במחיצות כלל, אלא בפי תקרה. צריך לומר שרק מהני בצירוף מחיצות שיש. (אבל צריך לע’ שם בגמ’, שבציור של רב ושמואל אין שום דפנות אחרות כלל. צריך לומר שמדבר באותם פצימים שיש. באכסדרה, אף הם לא נעשרים לתוכו. ותחשב.
1. מב.
לכאו’, יש סתירה לזה בגמ’ לעיל שאומר שאין בכילה גג, כיון שרק שיפוע אוהל הוא. תוס’ מפרש שהולך כשיטה שאין שיפועי אהלים כאהלים. קשה, שהרי לכאו’ בכילה יש גובה טפח. צריך לומר שאינו כן, ואין אפילו גובה טפח בלי שיפוע. ותחשב.
1. מג.
עיין שם שמביאים ראיה ממה שגשמים הם סימן קללה. איני רואה את זה כל כך, שאולי הוא קללה כיון שאין רוב בני אדם עושים כן (ויותר מזה, אולי לא קל לעשות כן, ונמצא שצריכים טורח גדול).
1. מד.
עיין בשי"ח ש"י שדנינו בביאור שיטת שמואל. שם כתבנו ככה:
“נמצא שמה שרואים אותו מהני גם לראות צל במקום חמה (אף שזה רק תוצאה מן הראיה). אבל קשה, שבוודאי לא אומרים כן, שהרי אז כל סוכה שצילתה מרובה מחמתה יוכשר מחמת לבוד. (אין לומר שהוא כשיש אויר יותר משלש, שאז יפסל מחמת אותו האויר. ותחשב.) אולי כאן מדובר בשצילתה מרובה מחמתה, וצריך חבוט וכדומה כדי לעשות שיש סיכוך אחד שהוא צילתה מרובה מחמתה, ולא שני סככות. תחשב על זה. לא משמע כן מן הגמ', שאומר ששמואל תני שנים. לזה, היה לו לומר ששמואל תני אחד, שראשון צריך שני, ודין של שני כבר נלמד מראשון. ותחשב על זה. (אפשר לומר שכאן סומך על חבוט רמי, ואז רואים אותו כצל, ורק לא רואים אותו בלבוד. יש לדון מהיכי תיתי לחלק. יותר מזה, קשה שאביי אומר שסומכים כאן על לבוד. יש לדון, שאולי אומרים חבוט רמי אף בדבר קטן אם הוא בתוך שלשה טפחים. מחודש לומר כן. ותחשב.) עיין ברש"י ד"ה אמרינן חבוט רמי, שכמעט בפירוש אומר נגד צד זה.”
1. מה.
יש לדון בזה, שיש לדון אם רב חולק על שמואל בדין או לא חולק עליו בדין. זה גם תלוי במה אומר שמואל (שיש דברים שיותר קל לחלוק עליהם). כאן, מפרשים כצד שיותר מסתבר לומר שרב מודה לו. ותחשב.
1. מו.
צריך לעיין בדברי רבי עקיבא, שאיני מבין למה זה נכון. לכאו', פשוט מן הסברה שיהיה תלוי ברוח מצוי של העולם. אולי הולכים אחרי רוב העולם (אף שרוב העולם שונה כיון שהוא במצב שונה). ותחשב. גם אפשר שאף רוח כזה לא כל כך מצוי בים, וחולקים כמה מצוי צריך להיות עד שיכול לעמוד בו. ותחשב.
1. מז.
יש לדון כמה צריך ללכת. נראה שיכול להיות שני מהלכים. אפשר שצריך ללכת עד שנפסל הסוכה, ואפשר שצריך ללכת עד שאינו עוד במקומו. וא"ת איך יכול להיות כדרך הראשון; הרי, זה היה כבר פשוט לגמ’ לעיל, כשבאר מחלקת רבן גמליאל ורבי עקיבא, וכאן דן בו, ומקשה עליו. יש לדון, שאולי מה שפשוט לגמ’ אח"כ הוא רק מפני שיודעים מימרא זו. יותר נראה לומר שיש חילוק, ששם רוח מצוייה מבטל אותו מלהיות מחיצה. כאן, אף שפוסל את הסוכה, לא נפסל מלהיות סוכה. יש להוסיף שאולי צריך להיות שחוזר אחרי שנגמר הרוח. אז, בוודאי יש חילוק גדול. לדרך שני, יש לדון כמה צריך לזוז, אם הוא כל זמן שאין מקצתו איפה שהיה מקצת או שצריך להיות בתוך שלשה טפחים ממקומו הראשון. גם יש לדון כמה ממנו צריך להיות במקומו הראשון, אם הוא כולו, רובו, עשרה טפחים, רוב עשרה טפחים, או שיעור אחר.
1. מח.
צריך לעיין בזה. נבאר מה שאנחנו יודעים בוודאי, ושוב נדון בזה.
1. יודעים משנה לעיל. אמר ש"[סוכה שנעשה] בְּרֹאשׁ הָאִילָן אוֹ עַל גַּבֵּי גָמָל, כְּשֵׁרָה, וְאֵין עוֹלִין לָהּ בְּיוֹם טוֹב. שְׁתַּיִם [מן הפנות נסמכות] בָּאִילָן וְאַחַת בִּידֵי אָדָם, אוֹ שְׁתַּיִם בִּידֵי אָדָם וְאַחַת בָּאִילָן, כְּשֵׁרָה, וְאֵין עוֹלִין לָהּ בְּיוֹם טוֹב.” לכאו’, דין של המשנה הוא שכשחלק חשוב מן הסוכה – דהיינו, חלק מן הסוכה שצריכים כדי להכשיר את הסוכה – נסמך באילן, אינו מותר לעלות לתוכו בי"ט, כיון שנחשב שמשתמש באילן.
2. יודעים גמ’ בפי’ משנה שלנו. גמ’ מקשה מהו החידוש של המשנה, אחרי שיודעים שהמשנה מדבר במחיצה שנעשה מענפי אילן שקשורים זה בזה. מבאר שהוא שהו"א שנגזור שמא ישתמש באילן. נמצא שאף לא מצדד שזה נחשב תשמיש (ונראה שבמשנה שלעיל נחשב תשמיש, ואינו רק גזירה, מסתימת המשנה והגמ’), אלא אף למסקנא מתיר אותו.
נראה שיש שני מהלכים לבאר את זה. מהלך ראשון הוא לחלק בין דפנות שסומכים על אילן לדפנות שהם אילן. לא פשוט לי למנה נחלק; היה נראה שצריך לומר פשט כעין זה – תשמיש האילן הוא רק אם הוא או מה שצריך סומך עליו; אבל, מה שצריך לאילן לא נחשב תשמיש. מהלך שני הוא שגמ’ לא דן, כשמזכיר חידוש של משנה זו, אם עולים לה בי"ט, אלא בדבר אחר. לכאו’, יש קצת הוכחה לזה, והוא שאם עיקר חידוש המשנה הוא שעולים לה בי"ט, היה לו לומר כן, ולא היה לו לומר רק שהוא כשר. לפי זה, הביאור יהיה שהו"א שאף בחול אינו כשר, שמא יעלה לתוכו בשבת וי"ט. וא"ת למה שונה ממשנה שלעיל. צריך לומר אחד משני דרכים. דרך ראשון הוא שכאן יותר משתמש באילן, ויהיה יותר גרוע אם עושה אותו בשבת וי"ט. דרך שני הוא שכאן יותר מסתבר שילך לתוכו בשבת וי"ט, אולי מפני שלא חושב על עצמו כמשתמש ואולי מפני שיותר קשה לתקן אותו. ותחשב. (עיין בתוי"ט על המשנה, שלא נראה כן.)
1. מט.
יש להסתפק אם עיקר הדין הוא שצריך ישיבה כעין דירה או שצריך אכילת שתי סעודות. הנפקא מינא יהיה היום, שאין רגילים לאכול שתי סעודות ביום, אלא שלש. (בין כך ובין כך חזר בו ר"א, ואז אין נפקא מינא.) מסתבר לומר שישנה עם הזמן.
1. נ.
צריך לעיין בזה. הרי, גמ' אומר שזה מספיק להשלים הסעודה שחסר. לכאו', אותה סעודה צריך להיות של לחם (שהוא סעודה ראשונה, ולמדנו אותו מן פסח). אבל, שם, מביא עליו בריי', שאומר שאם השלים בשל פרפרות יצא. עיין בלשון רש"י. כשדיבר ב"סעודה השנית," קצת משמע שחשוב שזה נאמר על סעודה שנית שביום ראשון. זה יבאר לשון הגמ', שאומר שיוצא. לשון זה קצת מוזר אם מדבר בהשלמה. יש לדון בזה, שיוצא השלמה, אף שלא יצא עיקר המצווה. על כל פנים, אולי מרש"י יוצא שהבריי' אומר שלרבי אליעזר סעודות אלו לא צריכים להיות של לחם. (אפשר שעדיין אחד ביום צריך להיות לחם.) וא"ת אם כן מהו הראיה. אולי לא מכוון להביא ראיה חזקה, ורק מוכיח שיש חשיבות לאכילת פרפרת. גם אפשר שסובר לתלות אותם זה בזה, שאותו מין סעודה שצריכים בשאר ימים הוא המין שמשלים. צריך ביאור למה זה יהיה נכון. ותחשב.
1. נא.
רשי פי' שהוא מפני שלעיל אמר שהחיוב הוא לאכול אותו בתוך הסוכה. נראה שפי' שאי אפשר להשלים מצוות אכילה בסוכה על ידי אכילה חוץ מסוכה. אבל, חיוב של לילה ראשונה הוא רק חיוב לאכול, כמו בליל פסח. אבל, אין זה כל כך פשוט, שיש שטוענים שמה שלומדים מפסח הוא שחייב לקיים את מצוות היום. (אבל, אפשר לומר שלכן חולקים רבנן.) אפשר לומר שאם סובר כדין ראשון שלו, אין מצווה לאכול, אלא המצווה הוא ישיבה בסוכה כעין דירה. אין זה בכלל כעין דירה, שאין השלמתו שלו מוסיף "כעין דירה" לסוכה, ואין זה השלמה. אבל, אם יש מצווה לאכול או לקיים מצווה בלילה אחת, אם עושה מעשה הדומה אחר כך, אולי השלים. ותחשב. אבל, אין זה נראה מלשון רש"י.
לולי רשי, היה נראה לי שמקשה ממה שדן בלילי י"ט ראשון, ולא בכל סעודות של כל ימי י"ט.
ודע שבי"כ ובי"כ, ק"ק למה לא אומר שיש השלמה רק לחיוב של ליל ראשון, ולא לשאר חיובים. צריך לומר שאם סובר שצריך ישיבה כעין דירה, לא ידרוש מקל וחומר עוד חיוב בלילה ראשונה, שאין זה מוסיף כלום. צריך לומר שמה שזה מוסיף דין השלמה לא מספיק. (אף שהוא דאי להחמיר, שגמ' אומר שהתורה אומר, צריך לומר שלא יאמר אותו. אולי רצה לומר שאם היה אומר אותו, היה אומר אותו באופן יותר פשוט, שהיה אומר דין השלמה, ולא עיקר החיוב. דחוק, שיש דינים אחרים שנלמדים מכאן, ולכן לימד אותו באופן זה. ותחשב.)
1. נב.
עיין במה שאמר תוס’. לא פשוט איך לבאר את זה מן הסברה, אם לא שנאמר שיש לרבנן איזה מקור (ואולי הל"מ) שככה התנה ה’ בכל מצווה. ותחשב. ודע שגמ’ לא משמע כל כך כזה, שגמ’ מדייק מלשון "פוסלים,” ולא "לא יצא" שדין דרבנן הוא. הרי, אף אם דין דרבנן הוא, יוצא שהיה לו לומר "לא יצא.” יש לדון, שאולי דיוק של הגמ’ אינו ממה שלא נקט "לא יצא" אלא ממה שנקט "פוסלים,” שאולי "פוסלים" משמע שרבנן פסלו אותו. צריך לחשוב למה יהיה כן. ות"ת.
1. נג.
עיין בדיון גמ’ בחיוב נשים בישיבת סוכה. צריך ביאור איך יש הו"א שהם פטורים מחמת שהוא מצות עשה שהזמן גרמא, שלכאו’ נאמר שאף הן היו באותו הנס, שבין אם נתקן מחמת ענני הכבוד ובין אם נתקן מחמת סוכות שבמדבר, בוודאי היו צריכים לאותו הנס. צריך לעיין בפי’ מדוקדק של אף הן היו באותו הנס, אבל נראה שאפשר לומר שהוא מפני שנשים של אותו הדר היו צדקניות, ולהן לא היה נס, שהיו ראויות לזה. אז, לא יתחייבו במצוות אלו. ותחשב. (צריך לעיין איפה אומרים שאף הן היו באותו הנס, שאני זוכר אותו בגמ’ רק בחנוכה ופורים, שהם מדרבנן. אז, יש לומר שזה רק סברה שיתחייבו מדרבנן. כשרבנן עושים תקנה, מסתמא יעשו אותו כדין תורה, דהיי’ שכיון שהוא כעין מצוות עשה שהזמן גרמא, לא יתחחיבו בו נשים. אבל, כיון שיש סברה אחרת, שאף הן היו באותו הנס, חייבו את הנשים. אבל, אין זה מחייב נשים במצוות עשה שהזמן גרמא.
1. נד.
יש לעיין אם קרא זה מגלה חיוב לנשים או מצווה לנשים כדי להשלים לחיוב בעלים שלהן. יהיה נפקא מינא גדולה בפנויה, שלצד ראשון אולי תתחייב, אבל לצד שני בוודאי תהיה פטורה.
1. נה.
צריך לבאר למה שיעורים אלו שייכים למצוות סוכה. (לכאו’, נקט דברים אלו כיון שכשהוא לא גדול בענינים אלו, קשה להושיב אותו בסוכה.) רואה אני איך השני שייך לשינה בסוכה (ואולי כיון שלא חייב בשינה, לא רצו לחייב אותו באכילה), אבל איני רואה איך הראשון שייך. צריך לומר שהוא רק סימן, שידוע רבנן שבזמן שבא זה, גם יותר קל להאכיל אותו בסוכה.
1. נו.
גמ’ דורש את זה בכמה וכמה מקומות, אבל אינו יודע מהו, באמת, המשמעות. רק אומר לשבת בסוכה, וצירך ביאור איך יודעים מזה שצריך לשבת כעין דירה בבית. אולי זהו המשמעות של ישיבה בסוכה. כשגמ’ אומר "תשבו כעין תדורו,” אולי מפרש מילת "תשבו,” ואומר "תשבו – [רצה לומר] כעין תדורו.” ותחשב.
1. נז.
יש לדון אם זה חיוב או רק מצווה. פשטות של המשנה יהיה שחיוב הוא, אבל איני חושב שזהו הדין.
1. נח.
יש לדון אם זה מדין מצטער או אולי הוא מפני שקשה לו לעשות מה שרוצה לעשות בסוכה (אבל אין בזה צער). לצד שני, יש לדון אם רק בתורה זה פוטר אותו מלשבת בסוכה, או גם בדברים אחרים כן. ודע שלא רואים שזה פוטר מלאכול בסוכה כשהוא עושה כן, אלא רק שלא ישב בסוכה כשעושה כן. ותחשב.
1. נט.
איני מבין מהו הדרשה לזה, שאיני רואה איך זהו המשמעות של "ענף עץ עבות." אולי הוא מפני שבדרך כלל פרי יותר חשוב מעץ. מה שבאר אותו על שם עץ שלו משמע שעץ שלו ופרי שלו שווים. אבל, לא נראה כן, שאז יכול להיות כל עץ סרק. אולי מצרף עם מה שצריך להיות עבות (ומעדיף במה שלא צריך למעט זיתים וכדומה מ"עבות").
גם קצת קשה מהיכי תיתי שלא יטול עץ של אתרוג, שחז"ל אומרים שטעם עצו ופריו שווים. אולי גם זה נתמעט ממה שצריך להיות "עבות."
1. ס.
המשנה לא מזכיר פסול של אינו עבות. נראה שזה מפני שאם לא עבות לא נקרא "הדס." בגלל זה, שמתי אותו כאן במשנה, ולא בסופו.
1. סא.
איני יודע אם זה נכון. עיין בגמ' שאומר שאם נשרו רוב עלים, כשר אם נשאר שלשה עלים בשלשה בדים. למדתי מזה שאם לא נמצא כן, פסול, ושצריך כן כדי לפסול אותו. אבל, לא מוכרח כן, שאפשר לומר שהוא פסול אף אם לא יבשו רוב העלים, אלא רק מקצתם, כל זמן שאין שלש בשלש בדים. מה שנקט גמ' שיבשו רוב הוא לומר חידוש שאף שם מקילים אם שלש אלו לחים.
ודע שיש לדון בהדסים שאין להם שלש בדים, ולא שיבשו אלו שלמעלה בשלש בדים. ותחשב. אם נאמר שצריך רוב עם פסול ראשון כדי להיפסל, קל לומר שהם כאילו כבר נתיבשו. ותחשב.
גם יש לדון מה קורה אם העץ של ההדס נתיבש, אם יש בו שום פסול, ומתי קורה אותו הפסול.
1. סב.
לכאו', לפי רש"י (שזה כשנשרו) מובן מה שאומר המשנה, שהוא פוסל כשנשרו העלים. אז, הדין הוא כמו שאומר הגמ' (לב:), שנפסל אם נשרו עד כדי שאין עוד עבות. קצת דחוק לומר כן במשנה, שלכאו' אין זה מדין נפילת עלים, אלא מפני שאינם עבות. אולי זהו הדרך שהמשנה מזכיר לנו דין עבות (שהערנו שקצת קשה למה אין המשנה מזכיר את הדין). יש לדון, שהיה לו לומר אותו יותר בפירוש. גם יש לדון אם זה רק אם נשר אותם לעץ, כמו שנראה גבי לולב. לרי"ף ורמב"ם, לכאו', כאן מדברים כשנדלדלו. לתוס', לא פשוט איך לפרש את זה. מסתמא מבאר אותו, אבל אנחנו לא עיינו בו. ותחשב. אולי הוא שהעלים ממש נחתך לשנים. דחוק לומר כן, שלא נראה שזה קורה בדר"כ בהדסים.
1. סג.
יש לדון אם נחשבים מין של עלים רק לענין שלא יפסלו או אם גם יצרפו עמהם להתכשר. יש לדון כמה הם ממין עלים, ויש לדון אם יכולים להיחשב "עבות," שאולי זה דבר שרק אפשר בעלה, בהכרח.
1. סד.
אין כל זה כל כך פשוט לי. הרי, גמ' מתחיל ואומר שערבה הוא דבר שגדל על נחל. אבל, אחרי כן ממשיך ודורש מקרא אחר שלא צריך להיות גדל על נחל, ומספיק אם הוא גדל בהרים וכדומה. אבל, שוב ממעט צפצפה שגדל על הר. נראה שהביאור הפשוט הוא שצריך להיות דבר שגדל במקום שיש הרבה מים. לכן, משנה מכשיר מה שגדל בשדה בעל, כיון שהוא מקום שאין צריכים להוסיף לו מים. אבל, ממעט צפצפה, שבדרך כלל גדל במקום שצריך יותר מים. גם אפשר לפרש שערבה הוא מין שגדל בנחל, וגמ' דורש לרבות שכשר אף אם גדל במקום אחר. משנה רק אמר בעל כיון שבדרך כלל רק יגדל במקום שיש בו הרבה מים, כמו בעל. אבל, אף אם גדל במקום אחר, אולי יהיה כשר. המיעוט של צפצפה הוא מפני שהוא מין שגדל בהר, ולא בנחל. גם אפשר להיות שמחלקת הוא, שיש דרשה אחרת שמזכיר תנאים מ"ערבי נחל," והוא שיהיה משוך כנחל. אפשר לומר שחולקים אם צריך להיות שגדל על הרבה מים (ואז ממעט של בעל) או שעלים שלו משוכים. ותחשב.
גם צריך ביאור מהו ערבה. הרי, רק יודעים שהוא דבר שגדל על הרבה מים. אבל, לא יודעים כלום על אותו דבר שגדל. לא נראה שמכוון להכשיר כל דבר שגדל שם. הגמ' נותן מקצת סימנים; כיון שלא נראה מקור להם מן התורה, מסתבר לומר שיש הל"מ או שידוע שיש פירוש למילת "ערבה," שידוע איזה מין ירק הוא. אם דורשים שצריך להיות שעלים שלו משוכים כנהר, אולי לא כל כך קשה לומר שרק צריך להיות דבר שעלים שלו משוכים כנהר, ובדר"כ גדל על הרבה מים, שאין כל כך כמה דברים כזה. אבל, נראה שזה מחלקת, שתנא אחד מזכיר דרשה אחרת, וגם שלקמן במשנה ממעטים מין מפני שגדל בהרים, אף שגם אומר שעגול הוא, ונראה שאז צריך לומר שלא מושך כנהר. ותחשב.
1. סה.
כן היה נראה, שהגמ' לא מפרש את הדרשה, אלא רק מביא את הפסוק, ורש"י לא מפרש את הדרשה. אז, משמע שהוא דרשה פשוטה, ומשמע שהוא דרשה שכבר הזכרנו. יש להעיר שאז יוצא ששני התנאים שלעיל דרשו "ערבי" חולקים על רבי ישמעאל, ורבי ישמעאל יחלוק עליהם.
1. סו.
עיין בגמ' לעיל שאומר שרבי יהודה סובר שאתרוג לא צריך להיות הדר כיון שדרוש כרבי אבהו. לכאו', היה אפשר לדרוש גם כרבי או כבן עזאי. אם כן, נמצא שהרבה תנאים סוברים שאתרוג לא צריך להיות הדר. (אם נאמר שכן האו שיטת רבי טרפון, ולא רק שלא לומד מאתרוג להדס, נמצא שאף פוסקים כן.) אבל, לא נראה שזה מוכרח, שאפשר לומר שאם סוברים כרבי יהדוה, צריך לדרוש דבר אחר מ"הדר," אבל אם דורשים דבר אחר מ"הדר," לא צריכים לסבור כרבי יהודה. אולי יכול להיות שני דרשות ממנו. קצת יש לדון איך, אבל יש להעיר (ונראה שזה יעזור לנו לבאר איך) שיש לדון אם מה שצריך להיות הדר הוא דרשה או פשטות הקרא.
1. סז.
מעניין שיש מחלקת תנאים ובאמצע (אף לא בסוף) מכניס רבי אבהו את ראשו ומבאר מקור אחר.
1. סח.
עיין במה שכתבנו. כן נראה מן הסברה, אבל לא נראה שהוא מוכרח. נראה שיכול להיות שאף לאחר יום ראשון, לא צריך להיות שלו ממש, אבל צריך להיות קצת שלו. אם שואל אותו, נחשב קצת שלו, ויכול לצאת בו. אבל, אולי אם אין בו דין ממון או אם אין בו היתר אכילה, אינו שלו כלל. (וא"ת אם שואל דבר אין בו היתר אכילה. וי"ל ששם היה אפשר להיות לו היתר אכילה, כמו אם הבעל מרשה לו. אבל, כאן, אי אפשר, ואז יותר נחשב שאינו שלו. ותחשב.)
1. סט.
נראה שכך הוא כוונת רבא (לו:), שנראה שבא לומר שאף שנעשה דפי דפי, נחשב שהוא כברייתו, שלא צריך להיות כל כך דומה לברייתו. אבל, אין זה מוכרח, שאולי בא לומר שלא צריך להיות כברייתו הכי מצויה, אלא אף אם הוא כברייתו שקצת מצויה – כמו אם נעשה דפי דפי – מספיק. ותחשב.
1. ע.
כן אומר הגמ' (לא:), ומכריח אותו שם. אבל, עיין לקמן, שגמ' מביא בריי', ובו רבי יוסי הביא ראיה לשיטתו ממה שרבי עקיבא הביא אתרוג גדול מאד. דוחה רבי יהודה שהזקנים אמרו לו שאין זה הדר. לכאו', קשה איך זה מתאים עם שיטת רבי יהודה. צריך לומר שהכיר שהיה חולק עליהם בדין הדר. כוונתו היה לומר שאין להיא ראיה משם, כיון שבאמת פסלו אותו. אז, אולי אם לא היו סוברים שצריך הדר, היו פוסלים אותו מטעם אחר, דהיינו מה שאמר רבי יהודה, ומה שלא אמרו כן הוא רק מפני שכבר פסלו אותו מטעם היותר חמור. ותחשב.
1. עא.
לכאו', אז, יוצא שהשיעור הוא שצריך להיות יכול לאחוז אותו אתרוג ולולב בידו האחת. אז, קשה מהו השיעור של שני אתרוגים ביד אחת. אולי שני השיעור שווים. לא נראה כן, שנראה שאתרוג יותר גדול מלולב. אולי זה רק אתרוגים שלנו, כיון שאנו לא פסוקים כרבי יהודה. אבל, אולי כדי להיות ששניהם הולכים לתוך ידו, גודל שלו יהיה שווה ללולב. גם אפשר שיש מיני אחיזה שונים. כשאומרים שצריך להיות ראוי לאחוז שני אתרוגים, מדברים על אחיזה אחת, וכשמדברים בטילטול לולב, מדברים באחיזה אחרת. אז, יש לומר שלכן מה שיכול להגביה שונה. ותחשב.
1. עב.
לכאו', אז, לא צריך להיות של לולב תחתיהם, אלא שגם יש של לולב. יש לדון, שיל"ד למה מחשיבים של לולב להיות האוגדים, ושל זהב להיות מיותר, ולא להיפך. אפשר לומר שהוא מפני שאז כשר. אבל, אולי הוא מפני ששל לולב למטה. תחשב על זה.
1. עג.
משנה אומר שהוא "תחילה וסוף." אבל, באמת אינו תחילה, אלא הוא אמצע ההלל. קל לומר שנקט מילת תחילה אגב סוף. (יש להוסיף על זה, שנגד הסוף, אולי האמצע נחשב תחילה.) עיין ברש"י, שנראה שלא מפרש כן, אלא מפרש שהוא תחילה וסוף של אותו הפרק.
1. עד.
עיין שם בגמ', שהיה אפשר לומר שזה אינו ביום ראשון, שכיון שהוא חיוב מדאו', מפסיק את הסעודה לו. אבל, נראה שאין הכרח לומר כן מן הגמ'. גמ' רק מחדש חילוק זה בין דאו' לבין דרבנן כדי לתרץ סתירה. אבל, כיון שנמצא שאין זה מתרץ את הסתירה, ויש דרך אחר לתרץ אותו, אפשר לומר שאין החילוק מחלק. לכן, לא הזכרנו אותו. ותחשב.
1. עה.
עיין ברש"י. אולי יותר נראה שרש"י רק אומר כן אם יכול לקרוא בפני עצמו, ועדיין אלו עוזרים לו. אם אינו יכול לקרוא בפני עצמו, לא בא קללה מחמת זה – אין לו ברירה, ואז אין כל כך בזיון בזה – אלא כיון שלא יודע איך לקרוא. אבל, יש להעיר שאז מה שהם עוזרים לו הוא סימן ולא סיבה.
1. עו.
עיין בגמ' (לט.) שמזכיר מנהג של רבי ומנהג של רבי אלעזר בן פרטא, ועיין בפירוש רש"י שם. נראה שיש שני דיונים פשוטים. ראשון, יש לדון אם מה שאומר גמ' שיכולי לנהוג לפשוט מכוון שלא לכפול כלום או מכוון לעשות כרבי. מה שקורא לזה גמרא "כופל," ולא מבאר שזה נקרא "פושט" במשנה משמע שהנוהגים לפשוט היו פושטים את הכל. שני, יש לדון למה היה כופל מ"אנא" עד הסוף, ולא מתחילה. נראה שיש לבאר על פי מש"א גמ' לעיל (בדברים הנלמדים מאמירת הלל), והוא שכיו כופלים כדי שיבינו בני אדם שיש שנוהגים לכפול, ושיכולים לנהוג כן.
1. עז.
צריך ביאור איזה זמן קובע שביעית ללולב. בשאר פירות, הולכים אחר זמן חנטה. אבל, איני יודע אם יש זמן חנטה ללולב. אם אין, אולי הולכים אחרי שעת חנטה של שאר האין. גם אפשר שהולכים בתר שעה ראשונה שנראה שם תחילת לולב. ותחשב.
1. עח.
עיין במה שבארנו. יוצא, אז, שאף אם מה שיום הנף כולו אסור הוא מדרבנן, ולא מדאו', עדיין אין טעם שלו שווה לטעם של לולב בשבעה ימים, שהוא גזירה, ולא כדי שיזכור את ירושלים. ויש לדון, שאולי מה שגוזרים לחשש רחוק כזה מראה חביבות המקדש לנו, ואף הוא נחשב דרישה עליה.
1. עט.
לכאו', אותו הטירדא היה יותר מ"רשות," אלא היה "מצווה." אולי, אז, נראה לפרש שאינו כן, שאסור לטרד כשיכול לבוא לידי איסור, אלא חייב לשמור על עצמו. אבל, אם טרוד כדי לעשות מצווה, אין לו מה לעשות להרחיק את עצמו מן הטירדא – שהרי, צריך לקיים את המצווה – ואז טירדא שלו הוא ברשות. ותחשב.
1. פ.
לכאו', יש מחלקת שיהיה נוגע לזה, והוא מחלקת שבין רבי יהושע ורבי אליעזר בענין טועה במצווה ועושה מצווה. יש מחלקת תנאים, גם כן, איך לפרש את המחלקת שלהם. צריך לעיין, אז, בשבת (בענין מילה) ובפסחים (בענין שחיטת קרבן שלא לשמו) וביבמות, שיבאר גמ' אותו מחלקת.
מן הגמ' בשבת יוצא שיש שלש שיטות בביאור מחלקת בין רבי אליעזר לרבי יהושע:
מגמרא בפסחים יוצא שאם כבר עשה המעשה שדוחה שבת, חולקים רבנן ורבי מאיר אם יהיה פטור, שרבנן אומרים שחייב ורבי מאיר אומר שפטור.
מגמרא ביבמות יוצא צד שרבי יהושע פוטר רק אם זמנו בהול.
יוצא שיש חמש פקטורים:
1. אם היה טרוד במצווה.
2. אם קיים מצווה.
3. אם היה זמנו בהול.
4. אם ניתנה שבת לידחות.
5. אם כבר עשה מה שדוחה שבת. (ראוי להעיר שלא נראה מן הגמ' שזה בכל ציור, שלא מצאנו שיהיה נוהג בציור שעשה את של שבת בערב שבת, ששם רבי מאיר סתם פוטר. יש לדון, שאולי צריך להיות שרבנן של כאן חולקים על אותה השיטה.)
הראשון הוא רק שחושב שמקיים מצווה. לכאו', כולי עלמא מודו שצריך זה.
השני הוא שקיים מצווה. חולקים אם צריך זה, שרשב"א אומר שצריך ורבי מאיר אומר שלא צריך.
השלישי הוא אם זמנו בהול. מן הגמ' ביבמות יוצא שצריך זה.
הרביעית הוא אם, באמת, ניתנה שבת לידחות. רק רבי מאיר סובר שצריך זה. (לא מצאנו שרשב"א מודה לזה או חולק על זה.)
החמישית הוא אם כבר נעשה המלאכה. חולקים רבנן ורבי מאיר אם צריך שלא נעשה כבר או לא צריך.
1. פא.
איני רואה למה יהיו מוקצים, שאף שאינה מקיים ציווי על ידי הטילטול, גם לה יש מצווה, שמקיימת את המצווה באופן של אינה מצווה ועשוה. אז, איני רואה למה יהיה מוקצה. לולי רש"י, שמדבר במוקצה, הייתי אומר שהדיון הוא בענין טלטול שלא לצורך שמתקן דבר (כמו סיפא של המשנה), והוא שמותר לעשות כן רק לצורך. מה שמשאיר ללולב נחשב צורך. אבל, הו"א שכיון שאין אשה צריכה לכך, שאין לה חיוב, אינו נחשב צורך לה. אבל, נראה שענין תשמיש של מוקצה (שהוא כל דבר שרוצה לעשות) יהיה פשוט שנחשב תשמיש. ותחשב.
1. פב.
עיין ברש"י, שמשמע שהוא טירחא. אבל, יש לדון בזה, שאפשר לומר שמה שנחשב טירחא הוא רק חילוק (ואולי לכן אסור ביום טוב). ותחשב.
1. פג.
אין זה כל כך ברור לי. מחודש לחוש לזה כיון שהוא רק נוהג במקדש (ומה שרק נוהג במקדש יוצא מן הגמרא שמקשה שלא ידחה שבת כלל). באמת, לשון רבה, בגזירה שלו, הוא ש"הכל מצווה ואין הכל בקי." יותר מזה, אם המצווה הוא לשים אותו על המזבח, נראה שרק כהנים יכולים לקיים אותו. אז, בוודאי מחודש הוא לחוש. ותחשב על זה.
1. פד.
וא"ת למה נותנים אותו להם, ולא מפקירים אותו. יש לדון למה יותר טוב להפקיר. נראה שלא יפקיר, כיון שאז קונה אותו בשבת, והרי אסור לקנות בשבת. יש לדון, שכאן גם כן קונה אותו. אולי כיון שיש הקנאה לו מערב שבת אינו כל כך רע. גם יש להעיר שאם עושה מתנה, צרי ךלומר שסובר שיש ברירה, שאם אין ברירה, לא בירר למי נותן אותו במתנה. ותחשב.
1. פה.
מסתבר שיצא ממס המלך כיון שהיו נוטים משם את הערבות. ויש לדון, שמסתמא היה צורך אחר בו, שאין ארץ שרק עושה ערבות לזמן אחד בשנה.
1. פו.
עיין בגמ', שלא פשוט אם זה מה שמכוון לומר. אפשר לפרש בגמ' שסובר שמילה זו משמע שהיו גבוהות. אבל, לא נראה לי כן, אלא נראה שקודם מפרש שמרביות רצה לומר רבות, ושוב מפרש כמה היו גבוהות. (ועיין שם, שיש שני גי' שם.)
* Footnotes
[fn:1] גמרא לא מפרש מהו הדין כאן.
