* כא.
** גמרא כל שעה -
כמו שאומר רש"י, החידוש של המשנה אינו מתי מותר להאכיל לבהמה, אלא מתי לא מותר להאכיל לבהמה. אז, קצת קשה למה לא אומר כן, ולמה אומר מה שמותר, והעיקר אומר בדיוק. אולי לא רוצה לדבר על איסור (אולי זה לשון נקי), ואז מדבר על מה שמותר.
** גמרא וקאי עליה בבל יראה -
לכאו', לא רק בבל יראה ובל ימצא יעבור, אלא גם יעבור בעשה של "תשביתו." קצת קשה למה לא אמר העשה, שהיה נראה שהוא יותר חמור. לאו רק יותר חמור מעשה כיון שעונשים עליו, אבל אין מלקות לבל יראה ובל ימצא. (אף אם לפעמים יש, זה לא מצוי כלל, ולא לבל יראה של מלקות חוששים.) צריך לומר שאף בלי עונש לאו יותר חמור. גם אפשר שאינו דווקא, ורק נקט מקצת הסיבות לגזור.
יש להעיר שדנו הפוסקים מתי חלים איסורים של בל יראה ובל ימצא, אם חלים בשעת איסור חמץ או שחלים בפסח. מה שמזכירים כאן חשש לבל יראה ובל ימצא, ולא מזכירים חשש לעשה של תשביתו, אף שהוא בוודאי מתחיל בשעת איסור חמץ (כן מוכרח מן הגמ' בתחילת פ"ק) משמע שאף בל יראה ובל ימצא נאסרים מאז, שאי לאו הכי, מה שהערנו לעיל יותר קשה. מחודש לומר שכל כך רצה לנקוט לאו עד שנקט אותו אף שעובר על העשה קודם (ואז יש לחוש יותר לעשה, שאין לו הרבה זמן לתקן קודם שיעבור).
** גמרא קודם פסח -
יש לדון אם זה דווקא, או שרצה לומר "קודם זמן איסור חמץ." אם נאמר שדווקא הוא, צריך לומר שאין בו תשביתו, כיון שעכשיו אי אפשר להשבית אותו, ורק יש בו בל ימצא, וצריך לומר שבל ימצא מתחיל רק בפסח, ולא בשעת איסור חמץ.
* כא:
** גמרא אין חוששים לקידושיו -
יש לדון אם רבנן, כשעשו אותו הפקר, הוציאו אותו מקנינו, או שכיון שאסור מדרבנן בהפקר, ממילא אינו ברשות שלו. ותחשב.
** גמרא עבר זמנו -
עיין במה שאומר שהוא החידוש מזה. מבין אני איך זה חידוש לדין, אבל איני רואה איך זה חידוש במשנה, שהרי המשנה אומר שמותר בהנאה כל זמן שמותר באכילה. אז, פשוט שלאחר כן אסור בהנאה. צריך לומר שהו"א ש"מותר באכילה" רצה לומר "מותר באכילה מדאו'." אבל, כיון שאומר עוד לשון איסור על עבר זמנו, יודעים להקדים את אותו הזמן לכלול זמן שיש איסור מדרבנן. ותחשב.
** גמרא מדאיצטריך -
וא"ת אולי צריכים קרא זה לומר שגר קודם לגוי. רש"י מתרץ שלא צריכים קרא לזה, אלא רק צריכים כן כיון שכתוב קרא שכולל את שניהם. (עיין לקמן, שנראה שרש"י סותר לזה.) וא"ת אולי היה ידוע מסברה, אבל רצה לטרוח ולכתוב אותו. ויש לומר שלא היה טורח וכותב דבר פשוט כזה שיוצא מן הסברה. גם יש לומר שבכל מקום שאפשר לדרוש דורשים, וכאן אפשר לדרוש.
* כב.
** גמרא רבי שמעון פוטר -
נמצא, אז, שיכולים לעשות מזה חידה: איך אפשר שאדם שחט ואכל מבהמה טהורה, ואסור, ושחט ואכל מבהמה טמאה, ומותר. התשובה היא גיד הנשה, אם אין בו טעם, שרק נוהג בבהמה טהורה, ולא בבהמה טמאה.
* כב:
** רש"י למאי -
לכאו', רש"י זה סותר מה שאמר לעיל (כא:) לבאר איך לומדים מקרא זה לפי רבי מאיר. נראה שאין הכי נמי, ורש"י כאן הוא רק בחזקיה, ומבאר שקל לבאר למה חזקיה חולק על רבי אבהו. אבל, רש"י לעיל היה מבאר שיטת רבי אבהו.
** גמרא דם שנשפך -
לא רצה לומר שצריך להיות ממש נשפך, אלא שצריך להיות ראוי. אולי צריך להיות דומה למים במה שהוא ראוי להיות נשפך, ואולי צריך להיות דומה למים במה שהוא נשפך, אלא ש"כל שהוא ראוי לבילה...." לא נראה כצד שני, שאז אם שפך אדם דם קדשים, אף שאין לעשות כן, יהיה מכשיר, כיון שהוא דומה למים. נראה שאף אם בפועל נשפך, אינו דומה למים, שמים נשפך בלי איסור ובלי שום בעיה, מה שאין כן בדמי קדשים.
** גמרא מנין שלא יושיט -
קצת קשה מהיכי תיתי לדייק כן, שאפשר שמדובר במשיט בלי קבלת הנאה. ויש לומר שבדרך כלל בני אדם מקבלים הנאה, ואז סתם הציור הוא כשיש לו הנאה. יש לדון, שנכון הוא שכל מעשי בני אדם הוא לתועלת טוב להם, אבל לא פשוט לי שבסתם ציור זה ייחשב הנאה.
** גמרא עד שבא -
אפשר לומר שאחרי שאמר כן רבי עקיבא חזר בו נחמיה העמסוני. אבל, ממה שרש"י קורא לו בכ"מ מי שלא דורש "את"ים לא משמע כן. אפשר לומר, אז, ש"עד שבא ר"ע" קאי על מה שהיו התלמידים שואלים אותו. אחרי שמצאו מי שיכול לדרוש אותו, אם כל כך רצו לדרוש "את"ים, הלכו ללמוד ממנו.
** גמרא את לא דריש -
רש"י מבאר שכיון שיש אחד שאי אפשר לדרוש, לא נדרוש שום "את." קצת קשה מהיכי תיתי לו לנחמיה העמסוני לומר כן. הרי, מצאנו דברים שרק דורשים אם אפשר, ואם לא אפשר, לא דורשים, כמו שאומר גמ' בתחילת סוטה ובתחילת קידושין. אפשר לומר (אבל לא נראה שזה מתאים עם רש"י) שסובר שהוא בזיון לה' לשים מילה שאפשר לדרוש אותו, אילו היה בו דרשה, לרבות לכבד עם ה'. אז, לא היה מסתבר לו שמילת "את" היא מילת דרשה.
* כג.
** גמרא לכתחילה -
נמצא, אז, איסור דאו' שהוא רק לכתחילה.
** רש"י וצריכי -
בכ"מ לעיל, בארנו שרש"י זה משמע שבל יראה הוא גזירה שמא יאכל את החמץ. אפשר לומר שזה רק בהו"א של הפסוק. אבל, כיון שאוסר גם שאור, לא מסתבר לומר שהוא גזירה שמא יאכל אותו, וצריך לומר שיש בו איסור אחר. (יש להעיר שאפשר להיות שרק בשאור, שחמוץ מאד, יש איסור אחר. אז, יכול להיות ששני האיסורים שונים מאד למסקנא. אבל, זה מחודש, שבדרך כלל, רוצים שדברים יהיו יותר פשוטים מזה.[fn:1])
* כז:
** רש"י ודנו דין אחר -
עיין בלשון רש"י, שקורא לזה גזירה שווה. מעניין לקרוא לו כן; כנראה הוא על דרך מה שאומר גמ' "זו היא שיבה זו היא ביאה." אז, קצת צריכים לפרש למה אין כל מה מצינו גזירה שווה. אפשר שאם יש הל"מ שאומר לדרוש אותו, נכון הוא שגזירה שווה הוא. ותחשב.
* כז:
** גמרא סמוכים לא דריש -
קשה מהו צד אחר, שבוודאי סובר כן רבי יהודה, כמו שרואים מגמ' בסנהדרין. אפשר לומר שאף שבדרך כלל לא דורש סמוכים, יש סיבות שידרוש סמוכים, ואולי יש בזה אחד מן הסיבות. נראה להוסיף שאולי הסיבה שיש בו היא שכבר מקרא זה דורשים. כעין זה מצאנו בתחילת פרק ששי של יבמות, שמצאנו שרוצה תורה לתת כל הדרשות בפסוק אחד. רואים משם שיותר טוב להיות דרשות דבוקים זה לזה. אז, אולי בקרא שאם נדרוש אותו יהיה לנו דרשות דבוקות זה לזה, יותר קל לדרוש סמוכים, עד שאף רבי יהודה מודה לדרוש. ותחשב.
** גמרא כתיב בהאי -
עיין בתוס' בשבת שדן אם טרח וכתב קרא במה מצינו. לכאו', הוא מחלקת תנאים כאן. (וא"ת כולי עלמא יודו שנדרוש אם יש מה לדרוש. ויש לומר שלא כל כך קל לדרוש כאן, ונקרא אי אפשר לדרוש. צריך ביאור למה נחשוב. יותר נראה לומר שאולי מה מצינו גרוע מקל וחומר, שבקל וחומר יש יותר סיבה לחשוב שהוא נכון, שיש כל שכן. רק אז אומר שדורשים אם יכולים לדרוש. אבל, אם מה מצינו הוא, תמיד לא דורשים.)
** רש"י בן נכר -
ולא לכל התורה- לכאו', כוונת רש"י כאן הוא שבן נכר שמדובר כאן אינו מומר לכל התורה כולה, שאי לאו הכי, מה לנו לתת לו צוואה, כיון שלא עושה מצוות. אלא, צריך לומר שהוא מין אחר של מומר. צריך לעיין בתחילת חולין, שיש הרבה מינים, ויש לדון על איזה מהם נאמר דין זה (בין המיעוט מפסח ובין הריבוי לחיוב מצה).
* כט:
** גמרא שלא במינו -
עיין ברש"י שמבאר למה לא גוזרים. רש"י לא נותן הרבה ביאור, אבל לכאו', הענין הוא שכיון שאינו עוד פסח, כבר בדיל מיניה (קצת מוזר שזה חל בדיוק בגמר פסח; אולי לא רוצים לחלק בתוך פסח, אבל באמת חל באמצע פסח), ואז הוא שווה לשאר איסורים.
* לא:
** גמרא קל וחומר -
קצת צריך ביאור למה קל וחומר הוא. אפשר שהוא מפני שקנין של גוי יותר גרוע, ויותר קל לדחות אותו. זה מניח שפשוט שעושה סיבת קנין, והדיון הוא רק אם יש מה שמונע אותו מלקנות. ותחשב.
* לב.
** גמרא דלא גרע -
יש לדון אם זה אומר שעל כל פנים יהיה חיוב גזלן או שמה שצריך לשלם מדין אוכל תרומה משוגג לא יהיה גרע מחיוב גזלן (יש לדון, אז, מהיכי תיתי). עיין ברע"א, שקושייתו מניח כצד ראשון.
** גמרא לפי דמים משלם -
נראה שלא צירך לומר שכיון שהזיק וחסר אותו, צריך לשלם לזה. אלא, אולי צריך לשלם אותו חפץ. אבל, אי אפשר לשלם אותו חפץ, שכבר נאכל. הקרק' החשוב שצריך לדמות לו הוא כמה שווה, ולא איזה מין אוכל הוא. (קצת יש לדון למה זה יהיה. תחשב. אפשר להוסיף שחלק מן הסיבה הוא שאוכל הוא, ואדם תמיד קונה אוכל, ואז העיקר הוא כמה כסף השאיר לו. ותחשב.)
* לג:
** גמרא מאן ציית -
חושב אני שמצאנו פעמים אחרים שרב חסדא מחפץ על רבי יוחנן, שאומר שאפילו אם שמע מפומיה, לא ישמע.
** גמרא מכוונת -
צריך ביאור למה לא חוששים כיון שאי אפשר לצמצם. אף אם נאמר שספק הוא, הרי נאמר שברשות היחיד יהיה טמא. ותחשב. (אולי הולכים עדיין בתר רוב, ומה שיכול להיות פחות מכביצה ומה שיכול להיות כביצה עושה רוב.)
* לד.
** אביי בר אבין -
צריך להוסיף אלו למנין אחים שלנו (בחידות).
** ומאי קשיא -
וא"ת מהיכי תיתי שהיה שום דבר קשה לו; אולי רק רצה ללמוד איזה דבר. ויש לומר שאם כן, היה לו לשאול מה למדו, ולא לפרוט באיזה סוגיה רצה לדעת מה למדו.
** איתיביה רבי יוחנן -
כמובן, היה אפשר לריש לקיש לומר שתנאי היא, שבריי' זה שדן בו רבה צריך להיות כמותו.
** משום הכי בעי עיבור -
באמת, מקשה על כל מושג של עיבור צורה, שתחילת עיבור צורה יעשה היסח הדעת, וממילא ייפסל מיד.
* לה.
** בתרומה אין בקדשים לא -
עיין ביבמות שדורש את זה מפסוקים. (כמו כן, בתחילת ברכות דורש את זה מפסוקים.) אז, נמצא שמביא כאן מעלה דאו'. (יש לדון אם מכוון להוכיח מעלה דאו' כאן, ומעלה דרבנן שמביא הוא להוכיח שיש מושג כזה בדאו', שרבנן עשו דברים הדוממים לדינים דאו', או שמכוון להוכיח מעלה דרבנן כאן, וממה שיש מעלה כזה בדאו', מסתבר שיהיה מעלה כזה בדרבנן. לא נראה כראשון, שלא נראה שיש מקור לחדש שיש מעלה מדאו' ממה שמצאנו מעלות אחרות מדאו', שיש הרבה מקומות שאין מעלה.)
* לו.
** לחם שעונים -
לשון הגמ' קצת משמע שעיקר המחלקת הוא כמה להחשיב מה שנקרא "לחם עוני," שאם מחשיבים אותו ביותר, נדרוש ממנו דרשה חזקה, ולא רק דרשת שמואל, שאינו מחדש הרבה דינים. ותחשב.
** כעין תורא -
עיין ברש"י. יש לדון אם רצה לומר שנותן מעט כמו מה שהשור אוכל 0שאוכל מעט) או מה שעושה לשור (שלא עושים לו הרבה). ותחשב. גם אפשר שצריך לאכול אותו מיד, כמו ששור אוכל אותו מיד.
* לו:
** מצות מצות ריבה -
נמצא שמניח שאינו מסתבר ללמוד מריבוי זה לרבות רק דבר אחד, אלא נרבה ממנו כל דבר. ותחשב.
** אשישה -
כמובן, זה בא מן הלשון "אחד מששה."
* לז.
** נפישא בלישה -
יש לדון אם רצה לומר שעב יכול להיות משמע נפישא או שהוא עב כשלש אותו. לצד ראשון, קשה למה לא אומר שהלחם שיוצא משם נפישא. משמע שרק אומרים לשון זה כשצריך לעשות מעשה לזמן רב, ולא כשיוצא דבר גדול. ותחשב על זה.
* לז:
** כמאן דפריסא -
נראה שהביאור הוא שהבעיה במה שהוא פרוס הוא שאינו שלם. מה שהוא קצת חי הוא לא שלם בבישול ובהכנה שלו. לכן, האו דומה למה שהוא פרוס. אבל, נראה שהוא יותר טוב ממה שהוא פרוס, לא רק מפני שמה שחסר אינו דבר פיזיקא"ל, אלא חלק מן המעשה, אלא מפני שיכול להשלים אותו, שיכול לאפות אותו עוד. ותחשב.
** בתנור אחד -
אם כן, לכאו' גם יחלקו אם בשלו אחרי שאפו. יש לדון, שיש לומר שכיון שמגיע לו שם של לחם כבר, לא נתבטל על ידי בישול. (גם אפשר שהוא שצריך להיות שאפייתו בא על ידי תנור אחד. אבל, כיון שהמצב שבו עומד הלחם שנבשל ושוב אפה בא גם מן הבישול, לא יכולים לומר כן. אבל, אם נאפה תחילה, רק אותם שינויים של אפייה נחשבים האפייה, ושאר הדברים הם ביטול והוספה על האפייה. ותחשב.
** יתיב -
משמע מזה שרבה ורב יוסף היו בדור של תלמידים של עולא.
* לט.
** כעולשי -
קשה למה לא רק אמר שיוצא בו, וקשה למה נקט שנים אלו. אפשר לומר שבה מראה סדר ההקדמה באלו. אבל, יש לדון מה מראה, שנקט שנים. אולי אמר שהוא כאחד מן השנים, ולא יודע כאיזה אחד. דחוק. גם אפשר שבא לומר שלא ידוע כאיזה, אבל הוא כאחד מאלו. גם יש לומר שבא להורות שלא מורה הסדר, שאילו אמר כן סתם, היה נראה שמוסיף בסוף המנין, ושאומר שהוא האחרון במנין. ותחשב. ויש להעיר שרבי מאיר לא אומר שמה שהוא מוסיף הוא כדבר אחר.
** רבי יוסי אומר -
יש לדון אם חולקים (והמחלקת יהיה בהגדרת המין) או שרבי מאיר שמע דברים אלו, ואמר אותם, ולא ידע מה הם באמת, ורבי יוסי הגיד לו. ותחשב.
** ותנא -
יש לדון אם צריך כל אלו להורות שמה שהוא בתחילה הוא בדווקא, או שצריך אלו כדי להראות כמה מקורות שסוברים שזה הכי טוב.
** חסא -
יש לדון אם זה סימן (שמראה שהוא היותר טוב ממה שנקרא חסא) או סיבה (שכיון שהוא נקרא חסא, הוא היותר טוב). כמובן, יש לדון מי נתן לו את השם הזה.
** חסא -
נמצא שבאכילת מרור, לא רק חושבים על מרירות העבדות, אלא גם על הגאולה. (יש לדון, שאולי צריכים לחשוב כמה ח עלינו ה', כדי להכיר כמה רע היה.)
** מרור חד -
עיין במה שכ' רש"י. לולי רש"י, הייתי אומר שהוא חסא. ותחשב.
* מ:
** אמר רבא -
נמצא שרב פפא היה פוסק במקום רבא. (אין זה קשה; לפי רש"י, שרבא מת כשהיה בן ארבעים, לכאו' היה רב פפא גדול מרבא, שרואים שרבא קרא לו זקן בגיטין בשני מקומות.)
* מא.
** מאי חייב -
אולי רבא הולך לשיטתו, שאומר שתמיד לוקים על הלאו של "כי אם צלי אש."
** אגב
[
, עיין בסוף נזיר, שגמ' מסיק על הרבה שאלות "אינו ידוע תיקו." נראה שאולי בא לומר שאינו רק תיקו, אלא אין אנו יודעים בכלל על הקושיות, ואין לסמוך על ה"אם תמצא לומר," כמו שסומכים בדרך כלל. ותחשב.]
** אגב
[
, יש להעיר שמחודש שיכול אדם להחליף כמה דברים במקום אחד של חולין, שהרי, כדי להחשיב אותם דומים זה לזה,  צריכים לדון על כולם כאחד, ורק אז ניתן להם אותו קרק' של שווה במדה או בשוויות.]
- יש לדון למה לוקים, לפעמים, שנים, אם הוא מפני שמה שיש שני לאווים בעצם מחייב שני מלקות או שמה שיש לאו מיותר מראה שיש עוד מלקות.
** לאו שבכללות -
אם לוקים על לאו שבכללות בפני עצמו, לפי אביי, קשה למה כתוב לאו פרטי.
* מב.
** בלאו מנין -
זה מראה מקום.
** לאו אמור -
אולי זה משמע שהתורה מגיד לנו פארפאפריי"ז של מה שאמר ה', ולא אותם המילים שאמר ה', שלכאו' ה' לא אמר "לאו אמור," אלא ה' אמר הלאו. ותחשב. ושי לדון, שאולי כדי שיהיה לאו, רק צריכים שמשה הגיד לבני ישראל שיש לאו, ולא שיש ציווי של לאו מאת ה' עצמו. אז, יש לומר שאומר אותם המילים שאמר משה לה', וה' אמר ככה, ומשה ציווה לבני ישראל שיש לאו. ותחשב.
** אמרי -
לכאו', רצה לומר "כיוונתי." יש לומר שאמר כן לאמורא, ואמורא אמר לכולם מילה בעברית שמבלבל, שאולי רק האמורא היה מדבר בעברית, והאו היה מדבר לו בארמית.
** אמרי -
מגמ' זה יוצא שלמדו בעברית. צריך לומר שידעו עברית. עיין בתוס' בברכות (ג.). צריך לומר שרק לת"ח לימדו בעברית, ואלו שטעו כאן ובתחילת מגילה היו ת"ח. ותחשב. גם אפשר שתוס' שם רצה לור שלאחר זמן שינו את לשון הקדיש, אבל בימי התנאים נכון שהיה בעברית.
** ואלו עוברים -
עיין ברש"י. יש לדון למה לא מפרש שהולך על אכילה. אולי הוא מפני שזה נזכר בסוף המשנה.
* מג:
** הני נשים -
עיין בקושיית תוס'. צריך לעיין, אבל אפשר לומר שבחיובי כרת יותר מסתבר להקל, שיותר מסתבר שרצה ה' להציל נפש מישראל (כיון שכרת ממית מוקדם). ותחשב.
** אגב
[
, עיין בכתובות נט., שנראה ששם יש שלש מילים, זה על זה, שהם שווים, שהם "יוחנן בן נורי." עיין שם. כמובן, זה מזכיר לנו גמרא בערכין, בתחילת פרק שני.]
** רש"י אין היתר -
אולי זה המקום הכי קל לטעות בין חלב לחלב.
* מה:
** הכא בקפידא -
לכאו', היה קל לגמ' לומר שיש שני דברים שאומר המשנה. דבר ראשון הוא שתלוי באם הוא כזית או לא, ודבר שני הוא שיש עוד פקטור שהוא חשוב, והוא אם מקפיד עליו. אפשר שלא מסתבר ששני הפקטורים שייכים, שאינם דומים זה לזה. יש לדון. גם אפשר שאז אינו דומה, ולא היה לו לומר "וכן." גם אפשר שאם כן, היה לו לפרש, שהיה לו לפרש אם קפידא שייך כשהוא כזית או כשאינו כזית. לא נראה כן, שבין כך ובין כך לא פירש כראוי, שצריך להיות שחסורי מיחסרא. ותחשב.
* מו.
** איסורו חשוב -
יש לדון אם זה מדין אגב (אם יש כזה דין בשום מקום) או שאז שם אוכל שלו יותר חשוב כיון ששם חמץ שלו יותר חשוב, כיון שיש בו איסור. ותחשב.
** רשי חרש -
אין אדם עומד על דעתו- משמע שלא ידוע דעת חרש. עיין ביבמות, שדן בזה גמ'. תחילה, יש לדעת שמחלקת תנאים הוא, שחולקים רבי אליעזר ורבנן בזה, ולפי רבנן, בוודאי אין לו דעת. רק לפי רבי אליעזר יכול להיות שלא ידוע דעת שלו. אבל, נראה שאף לפי רבנן, ידוע שאין לו דעת הנצרך, אבל עדיין פשוט שיש בו קצת דעת, ואותו דעת לא נודע. אולי לא נודע כמה הוא, ואולי לא נודע מה הוא (לא נודע מה חושב). ותחשב. אבל, מה שרש"י אומר שלא ניכר אם הוא שומע או לא קצת קשה, שלכאו' ניכר שלא שומע, שלכן אומרים שהוא חרש. אולי רצה לומר שלא ניכר אם מבין. דחוק. אולי רצה לומר שאף שאנו יודעים מבדיקות שלא שמע, למי שרואה אותו, לא ניכר אם שומע אותו או לא. (אולי זה גם יכול לבאר מה שהבאנו לעיל לענין דעת. ותחשב.)
** רש"י ד"ה לגבל -
איני מבין כל כך מהו הדיון. אפשר לומר שכיון שכלי בעלי בתים טמא, מניח שכלים שבהם באים החלה הם טמאים. אבל, לא חייב לטהר אותו קודם שמגבל אותו (ומתחייב בחלה) אם הוא רחוק. גם אפשר לומר שכיון שכלי בעלי בתים טמא, צריכים להניח שכלים שלו טמאים. כדי שלא יטמא את של חברו, צריך ללכת לטהר אותם, אבל לא אם הם רחוקים מאד. ותחשב. נראה שהראשון נכון.
* מו:
** רש"י ד"ה הואיל -
עיין ברש"י, שמזכיר כאן שני דברים. מזכיר מה שאין קבוע על אחד שם חלה, ומזכיר מה שיכול לשאול עליהם. (פשוט איך לשון "הואיל" יכול ליפול על השני, שהוא הואיל ויכול לשאול. לשון "הואיל" נופל גם על הראשון שהוא הואיל ויכול לקדש אחר במקומו.) עיין לקמן (שגמ' ינסה לפרש שחולקים רבי אליעזר ורבי יהושע ב"הואיל), שרש"י נותן הסברים אחרים. בין אותו הגמ', וגמ' שלנו, נצטרך לעיין כמה דרכים יש לפרש מחלקת רבי אליעזר ורבי יהושע. ותחשב.
* מז.
** ולרבן שמעון בן גמליאל -
לכאו', אף אם לא היה הגמ' טוען שאסור כיון שרק התירו שבות קרובה, עדיין היינו צריכים לבאר שיטת רבן שמעון בן גמלאיל, והוא שחולק על מה שאומר התנא קמא. אולי אין הכי נמי, ורק מסביר אותו כאן כיון שמסביר שיטה של החולק על עליו. גם אפשר שלא מסתבר לגמ' שיהיה מחלקת באיזה שבות התירו, ויותר מסתבר שיהיה מחלקת באם צורכי שבת נעשים ביום טוב. ותחשב.
** דיום טוב ביום טוב -
הקל וחומר מעניין, שהרי צורכי שבת הם יותר חשובים, כיון ששבת יותר קדוש, על כל פנים לענין חומר העונש, מיום טוב. ותחשב. אפשר לטעון שפשוט לגמ' (צריך ביאור למה) שמה שיכולים לעשות צרכי שבת הוא מפני שנחשב צורכי יום טוב, שעושה הכנה לשבת, וזה צורך. ותחשב.
ואם תאמר, כיון שמקשה גמ' שכאן צורכי יום טוב הוא, למה לא קשה לכולי עלמא. ויש לומר שצורך יום טוב הוא, אבל אינו אוכל נפש. רק מי שמחדש שצרכי שבת מותרים יסבור שצורכים כזה יהיו מותרים. ותחשב.
* מז:
** חזי לכיסוי הדם -
עיין בביצה (ח) שחולקים בית הלל ובית שמאי אם מותר לשחוט כדי לכסות. אז, לא פשוט שנוכל לומר הואיל. כנראה, כיון שמותר לכסות בדרבנן, ואז יהיה מותר לשחוט מדאו', נחשב ראוי לכך מדאו', ולא יחייב, כיון שיש לומר הואיל מדאו'. ותחשב. (אולי יש לצרף לזה מה שתוס' מקשה למה לא אומרים שעל כל דבר יהיה פטור הואיל ומותר הוא לפיקוח נפש. תוס' משיב שאין אומרים כן כיון שלא מצוי. אז, אולי אם רק איסור דרבנן מונע אותו, יש לומר כעין זה, שיש יותר דברים שדוחים דין דרבנן. אולי קצת שכיח שאחד מן הדברים יקרה, ואז אולי אומרים הואיל מחמת אותם דברים. ותחשב.)
** לא תעשה כל מלאכה -
ואם תאמר גם זה יהיה מותר מחמת אוכל נפש. הניחא אם דין דרבנן הוא, נוכל לומר שהחמירו רבנן בדין שלהם. אבל, כיון שהוא דין דאו', קשה למה יהיה אסור באוכל נפש. נראה שמן הפסוק מוכרח שאסור, שהרי המקור הוא מ"והכינו את אשר יביאו." שם, בפסוק, פשוט שמדבר באוכלים. אז, צריך לומר שאין היתר אוכל נפש באיסור מוקצה. ותו"ת.
** משום הבערה -
רשי מבאר שאין בו צורך. יש לדון אם הענין הוא שאין אכילת איסור נחשב צורך או שלא מניחים שיאכל אותו. ותחשב.
[אגב, שמעתי מרד"ו שיש שאומרים שאין ענין ערבות במצווה בדיעבד. נראה שזה רק אם יכול לשהות לקיים אותו לכתחילה, שאז יש לומר שלא מקיים ערבות בזה, שלא עושה לו דבר טוב ברוחניות, שאם לא מוציא אותו, יוכל לקיים אותו בענין יותר טוב. אבל, אם הוא אחרי זמן הטוב שלו, ובא לעשות אותו בדיעבד, נראה שיש ערבות להוציא אותו.]
* מח.
** רשי מן המאתים -
רשי אומר שיש מקור לזה. חשבתי ששיעור זה הוא דרבנן, ואיני רואה איך יש מה שהוא מקור אמיתי לו. ותחשב.
* מח:
** אתי לידי קולא -
נמצא שאין להפקיע דבר מקדושה. כמו כן רואים בתחילת בכורות. יש להעיר שאפשר לטעון (ואולי כן יוצא מגמ' בבכורות) שזה רק אם מוציא אותו מן הכהן. אפשר להסביר זה על פי גמ' בסוף יומא שאומר שאין כפרה על איסור שבין אדם לחברו עד שישאל לו למחילה. כמו כן יש לומר כאן, שאולי ה' לא יתיר חסרון של כהן. תחשב על זה.
** זה הכלל -
לכאו', מה שאומר רבי עקיבא פשוט, וקשה מה ישיבו לו רבנן. נראה שאפשר לומר ששני חלקים של מה שאומר רבי עקיבא תלויים זה בזה, והוא שאולי אומר רבנן מודים שיש כמה מינים של תנורים, ובגלל זה גוזרים שימהרו כאופן שאומרים במשנה, שאז בוודאי לא יחמיץ. אבל, רבי עקיבא אומר שכיון שיש דרך לתקן אותו אם מתחיל להחמיץ, אין צריכים לחוש. אבל, עיין בגמ' שלא משמע כן. ותחשב.
* מט.
** קוברה -
יש קושיה פשוטה, והוא שבוודאי אחד יקבור את השני. עיין ברש"י שמכוון לתרץ את זה כשאומר שקובר קודם הזמן של מיתה. נראה שגם אפשר לומר שהחידוש הוא שאחד קובר את השני, ולא הבנים קוברים. אולי הקלל הוא שלא יהיו להם בנים, כמו שאמר לעיל, או שהבנים לא ירצו לקבור אותם, אלא ימרדו, או שיהיו עניים, ולא ירצו לקבור אותם, כיון שאין ירושה (כמו שאומר גמ' ביבמות). ותחשב.
** סעודת רשות -
אזכיר כאן מה שחידשתי לפני כמה שנים, והוא שקשה למה גמ' בבבא מציעא מזכיר כמה שמנים היו האמוראים ותנאים. אפשר שבימיהם זה היה דבר חשוב, אבל נראה יותר לבאר אותו על פי גמ' זה, והוא שקשה איך אכלו הרבה, וצריך לומר שהלכו להרבה סעודות מצווה, ושעשו הרבה סיומים. ותחשב. על פי זה גם נראה לבאר למה אביי עשה סיום לכל הישיבה בכל זמן שאחד גמר מסכתא, והוא שמה שאוכלים כשאינו רשות הוא בדין בדיעבד, שצריכים לאכול. אז, אם אפשר לעשות אותו לסעודת מצווה, בוודאי נעשה אותו כן. (נמצא שבסיום הש"ס, כשתמיד מדברים על של אביי, אולי לא מקיימים אותו, כיון שלא נותנים מזון לכולם. אני לא מכוון לומר שיתנו מזון לכולם, אלא לומר שלא ידברו על אותו הגמ', בפרט כיון שידוע שכל אחד מן הדורשים שם ידברו בו.)
** תלמודו משתכח -
וא"ת הרי כבר מת, שמאלמן את אשתו. ויש לומר שזה קורה ראשון. אבל, עיין ברש"י, שאומר שנותן להם אלמנות בחיים. על פי זה, מסתבר למה מדבר על אשתו ועל בניו, שיכול להיות אחד בלי השני. ותחשב.
* מט:
** בת ע"ה -
יש לדון אם זה אומר שלא ישא בת ע"ה בכלל, או שרק לא ישא אותה אם יש אפשרות לישא אחרת. ותחשב.
** כאילו -
עיין ברש"י. איני יודע מי מבייש. הייתי אומר שמבייש את הארוסה, אבל אז היה לו לומר אותו בלשון נקבה. ותחשב על זה.
** וחזרתו -
רש"י אומר שזה דין דרבנן. זה היה המקור שלנו לענין הפסד מרובה מדאו', אבל לפי רש"י אינו מקור. אז, צריכים למצוא מקור חדש, אם יש. ותחשב.
* נ.
** יהודה אזיל ונסיב -
ואם תאמר הרי שמעון נסיב, שהרי היה לו בן "שאול בן הכנענית." יש לומר שאם שלו היתה תגרתא. גם אפשר שלא נשא אותה, אלא רק בעל אותה, ואז אולי אין בעיה. גם יש לומר שרק ליהודה, שהיה קצת מנהיג ומלך של בני ישראל, היה בעיה. ותחשב. (נראה שיש לחדש שידוע שבטים שיהיו שנים עשרה שבטים. הבינו שבלי יוסף, לא אפשר, ואז חשבו שרק אחד מהם ימשיך, ויוליד שנים עשרה שבטים. יהודה יהיה אותו אחד, כיון שהיה מנהיג. כיון שהוא האחד, היה צריך שלא לישא כנענית. ותחשב.)
* נ:
** שמותי -
צריך ביאור למה לא אומר שאסור כאן, ושם לא אומר שאסור. משמע שממה שאומר שלא בא לו הרווחה מסתבר שגם מכוון לאסור אותו.
** שפל ונשכר -
נמצא שבא לו שכר למי ששומר את עצמו מעבירה, אף שאין לו תאווה. יש לדון, שאין זה עבירה, אולי, שאפשר שהענין הוא שאז שומר שבת יותר טוב. אז, מקיים עשה יותר טוב. אולי רק על זה בא לו שכר אם עשה אותו בלי תאווה נגדו.
** מתורגמנים -
יש לדון למה מותר לתת להם שכר, שיהיו כמלמדי תורה. ותחשב.
** עושים לשמה -
נראה שאפשר לפרש עכשיו שלא מכוון לומר שזה נותן שכר עד לשמים וזה נותן שכר מעל שמים, אלא שזה נותן שכר מעל שמים, וזה מגיע אותו לעד שמים, והוא שמביא אותו לידי מצווה לשמה. ותחשב.
* נא.
** חומרי מקום -
וא"ת אם יש בזה חומרי מקום שבא לשם, אין נפקא מינא לדין של "אי אתה רשאי להתירן." ויש לומר שנמצא אם אינו מנהג, אלא שעושים כן בלי שום ידיעה. יש לדון אם זה לא נחשב מנהג, ובפרט לפי מה שאומר אבייש ענין של מנהג הוא מפני מחלקת (עיין לקמן). גם יש לומר שנמצא לעשות לפני אדם, אף אם אין מנהג המקום לאסור, אבל איש זה סובר שהוא אסור.
* נא:
** רבא אמר -
יוצא שאביי סובר שהסיבה שעושים כמנהג המקום הוא משום מחלקת. יש לדון מה סובר רבא, שאין הכרח שסובר כן. אולי משמע שלא סובר כן, ממה שלא פירש כאביי, אבל אין הכרח לזה, שיש לומר שלא מסתבר לו שקאי על רישא, שנאמר אחר סיפא. יש לדון, שאולי היה לו לומר שקאי על שניהם. אבל, לא נראה כן, שהיה אומר דבר שונה על שניהם. ותחשב. עיין ברש"י בע"א, שמשמע שסובר שרבא סובר כאביי, שמפרש אותו גמ' על פי מש"א אביי בטעם שהולכים אחרי מנהג מקום שבא לשם. ותחשב.
* נב.
** במדבר -
יש לדון למה אין אומרים על זה ש"כל דבר שאסור ברשות הרבים, אסור אפילו בחדרי חדרים."
* נב:
** כרחבה -
מה שמביא שרחבה דייק הוא צדדי.
* נג.
** כמקדיש -
קשה, שהרי אומר כן על בשר, ולא על בהמה. אולי לאו דווקא הוא, ורצה לומר שאין לומר כן על בהמה. זה קולא גדולה. גם אפשר שהחשש אינו שבזה מקדיש אותו, אלא שמראה שקידש אותו. ותחשב.
** דמינטר -
לכאו', יש שני דברים. הראשון הוא שאי אפשר להיות קרבן פסח, והשני הוא שיש סיבה אחרת למה יפרש שלפסח הוא. אז, אפשר לדון אם צריכים אחד (ואיזה אחד) או שניהם. ותחשב.
** עגלים -
עיין ברש"י. נראה שכולי עלמא יודו בעגלים, כיון שגדלים לשורים, כמו שאומר גמ' בבכורות גבי עובר. אבל, יש להעיר שאין זה כל כך פשוט לי, שמי שזוכר שבא מישראל, יזכור שמכר כשהיה קטן, ולא היה ראוי למלאכה אז. אבל, בשבור אינו כן. ותחשב.
* נג:
** על אחת -
קשה, שלנו יש חשבון של נפש יהודי. משמע שהענין של פיקוח נפש אינו שנפש של ישראל חשוב, אלא שכשה' ציווה לאדם שלא לעבור על עבירות, לא עשה כן אם אדם מפסיד דבר שהוא מאד חשוב לו, דהיינו נפש שלו. אז, אין חילוק בין אדם לצפרדע. (אבל, פשט של רש"י ב"מאי חזית" לא משמע כן.)
** ומדליקים -
צריך ביאור מה זה אומר. אולי רצה לומר ששם אין סיבה שלא להדליק, וכבוד יום להדליק, ואז הכל נוהגים להדליק.
** לא רבי שמעון -
עיין ברש"י שפירש שרבי יוסי סובר שאין אדם מוציא דבריו לבטלה. זה מבאר למה רב פוסק בזה כרבי מאיר (שאין אדם מוציא דבריו לבטלה) בתחילת ערכין.
** לא -
עיין במה שכ' רש"י בענין גדי מקולס. איני מבין כל כך מה מכוון לומר כשדן מה יקרה אם אמר שהוא לפסח.
* נד.
** המכתב -
בסוף רשי זה משמע שכתב, לפי' ראשון, הוא קריאה. אבל, לעיל, משמע שהוא שם של האותיות, ולא קריאה. ותחשב על זה.
** אור דידן -
קשה למה לא אומר שאור של גיהנם עלה במחשבה בשני ונברא בע"ש. אולי רצה שכל דבר על כל פנים עלה במחשבה בשבוע ראשון. גם יש לומר ש"עלה במחשבה" רצה לומר שניתן כוח ויכולת לגרום כן, וזה יותר קל לומר באור שלנו. גם יש לומר שמובן למה לא נברא מיד, שהיה שבת. אבל, לא מובן למה לא ייברא גיהנם מיד.
** פרד -
קשה למה לא מברכים על פרד שרואים במוצאי שבת. אולי אינו כל כך חשוב כמו אור.
** שקדיה -
קשה, שאז לא מראה שאהרן הוא הבחיר, שמטה שלו גדל שקדים ופרחים כיון שנברא במיוחד עם שקדים ופרחים מששת ימי בראשית. ותחשב. אולי הראיה היא ממה שזכה לאותה מטה.
* נד:
** יום נחמה -
עיין ברש"י. משמע שהוא מתי לא דואג עדו, ולא מתי אינו עוד עצוב. נראה שזה מפני שידוע שמת משתכח מן הלב לאחר שנים עשרה חדשים.
** שיסריח... שישתכח -
יש לדון למה צריך שניהם בצירוף. ותחשב.
* נה.
** מוחלפת -
משמע שלא חש לדעת איזה מחליפים. זה שייך לדיון גמ' בביצה (ט).
** חד מקצת -
אולי זה מפני שדבר מציאות הוא, ומה שאומרים בו מקצת היום הוא שכל שנשאר בו פחות מיום בתחילת היום לא נשאר בו דבר חשוב, וכאילו כבר נגמר. ותחשב.
** שהתחיל -
קשה שרבי מאיר לא אוסר, אלא תולה במנהג. צריך לחשב כל זה.
* נו.
** ולא היו מפסיקים -
עיין ברשי. נראה שאפשר לומר שרשי סובר שענין של מאריך באחד הוא שמאריך אחר שאומר מילת אחד (וקורא לזה מאריך באחד כיון שהוא עדו עומד באותו מילה כיון שלא התחיל אחרת; זה יותר קל לחזון איש שאומר שעדיין יכול לחשב בו). אז, לא קשה איך יכול להאריך דל"ת. ותו"ת.
** מוכן לאדם -
צריך לעיין בסוגיה כזו בביצה ולצרף לכאן.
* נז.
** כריך -
יש לדון למה לא אומרים שלקיחה על ידי דבר אחר שמו לקיחה. נראה שדורשים מ"הכהן" שצריך קדושת כהן ליגע בו. אולי הענין הוא שצריך נגיעה לנגיעה, ולא לפרט במעשה. יש לדון. (נראה שרש"י צריך להוסיף שהוא בזיון כיון שבלי זה אולי נאמר שדבר שהוא משום כבודו אינו חציצה, כמו שאומר גמ' שם בסוכה.)
* נז:
** ולא יאכל ממנו כזית צלי -
קשה, שגם א יאכל פחות מכזית, שפחות מכשיעור אסור מן התורה.
* נח.
** דרחמנא -
רצה לומר "אשר עליהם רחמנא אמר...."
** צריך לסכם כל גמרא זו.
* נט:
** רש"י ורבי יוסי -
דבוק- איני מבין כל כך מהו כוונת רש"י במילה זו. נראה שאולי רצה לומר שלפי רבי יוסי אומרים "דבוק," עם חולם, והוא שאומרים שמדביקים את את שני הדברים שאמר ביחד, כאילו אמר את שניהם ביחד.
* ס.
** לאוכליו ושלא לאוכליו -
איני מבין הראיה כל כך, שלכאו' אינם דומים זה לזה, שמחשבה לאוכלים ושלא לאוכלים שכשר הוא כשחושב על שניהם ביחד, ולא כשחושב תחילה על זה ושוב על זה. אולי איני נכון בהנחה זו, או אולי עדיין כיון שבעבודה אחת היא, יש לצדד להביא ראיה ממנו.
* ס:
** מידי אריא -
וא"ת למה הביא ראיה זו, שכבר הראה שצריך לומר שאין כל המשנה מדבר בציור אחד. נראה שיותר דחוק לומר כן אם שני חלקים של המשנה מדברים דווקא בציור אחד, וזה אינו באותו הציור. ותחשב.
** דילמא ממשכי -
מעניין לומר כן, שהייתי חושב שרק צריך לכוון על "בעלים" של הקרבן. בוודאי עומד ל"בעלים," מי שהוא, אלא שאין "בעלים" כל כך קבוע. אז, הייתי חושב שנחשב שעומד למחשבה נכונה. ותחשב. משמע מזה שעיקר הכוונה הוא על הבעלים דווקא, ולא על הכלל הסתם של "בעלים." אין זה מכריח שצריך לחשוב על הבעלים, שעדיין אולי יכול לחשוב על "בעלים," אבל זה מהני רק כיון שבזה חושב על הבעלים. ותחשב.
גם צריך לחשוב על הזמן בזה. הרי, לא משנים בעלות אחרי שחיטה, וכאן דנים על מחשבה בשעת שחיטה. עיין ברש"י, שמשמע שהענין הוא שאינו כל כך סתמא, כיון שאינו כל כך נודע. לשמו של קרבן נודע, שרק צריכים לדעת מה קרה מתחילה. אבל, כאן צריך לדעת גם שלא נשנה. מעניין שמה שלא כל כך קל לדעת עושה שאינו סתמא כל כך.
עיין במה שנכתב בע"ה לקמן על רש"י, שנראה שהוא נוגע מאד לדין זה.
** שינוי בעלים -
לכאו', זה מאד נוגע למה שיש לדון למה מחשבה שלא לשמו עושה אותו לקרבן אחר. אפשר לצדד שהוא מפני שמחשבה לשם קרבן אחר עושה שאינו כל כך קרבן פסח. (אין לומר שמחשבה לשם קרבן אחר עושה אותו קצת קרבן אחר; זה לא מספיק, שהרי לא תמיד נעשה אותו קרבן, אלא נעשה שלמים. (יש להוסיף שאולי יש סיבה שיכול להיות רק או פסח או שלמים. (נגיד שיש איזה דמיון לכל אחד מהם.) רק אחד מהם יכול להיות עולה, והוא שלמים, כיון שכשר שלא לשמו. אז, כיון שנעשה קצת עולה, נעשה יותר דומה לשלמים מלפסח. ותחשב.) אבל, אפשר לומר שנעשה אותו קרבן אחר קצת, וזה עושה שנעשה שלמים, וגם אפשר לומר שנעשה פחות פסח, ולכן נעשה שלמים.) לא מסתבר שמחשבה שלא לבעלים יעשה כן. אז, צריך לפרש שכיון שדוחה אותו מלהיות פסח כשר (רצה לומר, שנדחה לא רק בזמן, אלא גם באופן אחר, דהיינו מחשבה), אינו כל כך פסח, ונעשה שלמים.
** נוהג פסולו -
עיין ברש"י. יש להעיר שיש דיון פשוט בענין מחשבות שלא לשמו, והוא שיש לדון ביחס בין פסול שלא לשמו בפסח וחטאת ומה שלא עולה לו בשאר קרבנות. מסתבר לומר שפסול של פסח וחטאת שווים (אבל אין הכרח לזה), כיון שדינים שלהם שווים, אבל יש לדון בשלא לשמו של שאר קרבנות, שאין לו אותו הדין. גמ' זה, לכאו', משמע שהם דין אחד. ותחשב.
** פסח ששחטו -
רש"י כ' שלא גורסים "לשמו." יש לדון אם רש"י רק בא לומר שאין לגרוס כן, אבל אינו משנה את הדין, או שסובר שאם חושב עליו לשמה, אינו ניתק מלהיות פסח, שהרי חושב עליו להיות פסח. (גם אפשר שרש"י לא רוצה שנדון במחשבה לשמו של פסח, כיון שאז נצטרך לדון בשיטות התנאים שקרבן שנשחט לשם פסח פסול.)
** דתנן -
רש"י כ' שעדיין אפשר שימנו עליה חולה וזקן. מעניין שצריך לזה; הייתי אומר שהענין הוא שבני אדם אחרים יכולים למנות על זה, ואלו יכולים למשוך את ידם. אז, מה שעומד לו – שחיטה לשם אלו – לא עומד לו כל כך. אבל, מרש"י משמע שיש סתמא של "בעלים כשרים," וגמ' בא לומר שאין זה כל כך סתמא, כיון שאפשר לשנות. ותחשב על זה.
* סא.
** ובלבד -
נראה שלשון זה קצת מוזר, ונצטרך לבאר אותו. יש שני משמעיות למילת "בלבד":
1. דין נאמר, ומגדיר אותו, לומר שלא תמיד נוהג.
2. דין נאמר, ומחמת דין זה, נחשב שדינים אחרים נוהגים. אבל, אינו כן, אלא דינים אחרים נוהגים.
אם נפרש אותו כצד ראשון כאן, לא מובן, שאינו ממעט את הכשרות, שאף אם אין אחר ממרס אותו, אלא זורקים אותו מיד, כשר. (אין לומר שבא לומר שצריך למרש, ולא יכול להניח אותו, שאם יש מה לזרוק, בוודאי כשר, ואם אין מה לזרוק, פשוט שפסול. יש לדון, שאולי בא לחדש שצריך לזרוק אותו, ולא יכול למרח את הדם הקרוש, או שאולי בא לחדש שלא יכול לתת מים בדם הקרוש, לעשות אותו משקה.)
אז, צריכים להעיר שיוצא שהפירוש כאן הוא כשני. מדין שאמר, הייתי חושב שאף לכתחילה יכול להקריב את שאר הקרבות לפני תמיד של בין הערבים. אז, אומר "בלבד" אין דין זה נוהג, אלא עדיין צריכים להמתין לכתחילה לזריקת דם של תמיד של בין הערבים קודם שזורקים דם של פסח.
** לשון סורסי -
איני מבין מה זה שייך לדרשה זו. כנראה מרש"י, מביא ראיה שבשעת שחיטה מדברים. איני יודע אם זה פרט אחר בדין זה שת"ק לא מדבר עליו, או שמזה לומדים דין של ת"ק. איני מבין איך יכולים לומר השני, אבל חיסרון שלא בהבנה לא ימנע צד מלהיאמר.
עיין ברש"י בע"ב, שנראה שאומר כצד שני, והוא שמוכיח שבשעת שחיטה אומר. שם,  רש"י מבאר שתנא קמא לומד אותו מהמשך הפסוק. לא מבאר למה לא לומד רבי משם.
* סב.
** לחומרא —
יש להעיר שיש קולות שיוצאים מחומרא זו, כמו חולין לעזרה. יש לדון, שאולי צריך למנות עם אחרים שבוודאי חייבים. אבל, דע שאולי זה לא קשה, שאולי לא רצה לומר שמסופק, ואז אומר אותו רק להחמיר, אלא אולי רצה לומר שיש כמה מיני נפקא מינא, ויש חילוק ביניהם בענין איך לדון בהואיל. צריך לחשוב על זה.
* סב:
** נימא הואיל -
צריך לעיין בזה, שהייתי אומר שזה מין שונה של "הואיל." גם צריך לעיין לעיל (ובפירוש רש"י) שבעיקר דיון של הואיל, היה נראה שיש מינים שונים של "הואיל," בענין מחלוקת של רבי יהושע ורבי אליעזר שם.
** כפייה -
איני מבין מה קרה כאן; כנראה, כפה את רבי יוחנן ללמד לו מה שלא רצה ללמד. זה קצת קשה להבין.
** וכהה מאור עיניהם -
אולי יש יחס בין מה שזה נקרא מאיר עיני חכמים, ומה שרבי מאיר נקרא כן על שם שהיה מאיר עיני חכמים, וברוריה, שהיתה אשת רבי מאיר, היתה למדנית בענין זה. (אולי רצה לומר שאף ברוריה, שהיתה למדנית בזה, והיתה נשואה לרבי מאיר, שהיה עיקר הלמדן בזה, שהיה מאיר עיני חכמים. גם אולי רבי מאיר נקרא כן על שם שלמד מברוריה והרחיב על מה שידעה (שאל"כ, היא תקרא מאירה).)
נגד זה, נראה שיש לומר שלכן גמ' אומר שהיה מאיר עיני חכמים בהלכה, והוא שבא לומר שלא נקרא רבי מאיר מפני הארה זו (אולי לא האיר בזה או האיר בזה, אלא שלא נקרא על שם זה), אלא על שם הארה שלו בהלכה.
** תלת מאה -
כמובן, יש לדון אם זה שלש מאה מכל אחד או מכולם. (לשני, קשה מה לנו כמה רביים היו לה. ויש לומר שקל לשנות מרבי לרבי, ואז ייותר קל כיון שיש לה הרבה רביים.) אין כל כך חילוק, כיון שבדר"כ שלש מאות הוא גוזמא, ואין זה דווקא.
* סג:
** בהתראה -
עיין ברש"י. נמצא שהתראת ספק תלוי בספק של המתרה.
** לא ילין -
קשה למה אין זה גם ממעט שוחט. ויש לומר שכיון שפשטות הפסוק הוא על חמץ שלו, לא מסתבר למעט אותו.
* סד.
** שחט ישראל -
עיין ברש"י. כן יוצא מגמ' לקמן. דע שהייתי אומר שבדווקא נעשה כן, כיון שצריכים כהנים לשאר עבודות, כיון שהיו הרבה בני ישראל. קצת קשה לל"א גמ' כן.
** אם גמרו -
עיין ברש"י. קצת קשה למה צריך רבים שוחטים; משמע שלא יתחילו אם אין לחשוב שיכולים לגמור. גם צריך ביאור למה רק דן בשחיטה, ולא בשאר עבודות. אולי הכתים היו רק לשחיטה, ואולי פשוט שזריקה קרה מיד, שכהנים היו זריזים מאד. לא נראה כצד שני, שגם בני חבורה זריזים, כמו שאומר גמ' בשבת. יש לדון.
* סד:
** ישראל -
איני מבין למה חושבים ש"ישראל" הוא עשרה בני אדם. נראה שאינם נעשים ביחד דבר אחד של "ישראל" אלא אם כן הם עדה; פחות מזה, הם יחידים. במילים אחרים, מה שמיחס אותם בשם ישראל הוא אותה חשיבות של עדה. (אבל , עדיין לא פשוט מהי"ת שאין "ישראל" יחיד. אולי היה משתמש במילה אחרת.)
** מעוכים -
יש לדון למה קרא לו לשון רבים. אולי הוא מפני שהוא דומה ל"מעובים." גם אפשר שהרבה בני אדם היו מעוכים, ורק אחד מת.
** שמא יניחום -
לכאו', אין צורך שלא להיות להם שוליים, שאינו נקרש. כנראה, רוצה שיהיו הכל דומים.
** טעון יסוד -
קצת קשה למה לא לומדים מזה שגם צריך מתן שנים שהם ארבע. אם לא לומדים זה, עדיין מחודש שיכולים ללמוד מקצת דין זריקה, שהיה אפשר לצדד שהוא דין אחד. אולי אין דבר אחר ללמוד מזה. אולי זה מלמד לנו שאינו דבר אחד, ואולי זה מלמד לנו מקצת דין. ותחשב.
* סה.
** מי שבניו -
זה קצת שונה, שלא בחר בזה. (יש לדון בזה; עיין בגמ' בשבת ונדה, שיש דרך לעשות שהנולד זכר.) נראה שבעיקר מביא ראיה ממימרא ראשון שלו (אומנויות). נראה שלכן אומר שני המימרות, שהראשון מדבר על דבר שהוא בידו, ובא מן הבחירה שלו, והשני בא מדבר שאינו בידו, ובא מן המזל שלו. (גם יש לומר שבידו הוא, שהיה לו להתפלל או לעשות מעשים טובים. ותחשב.)
** ורבי נתן היא -
יש לדון למה לא אומר "שלא ברצון רבי נתן." (אולי כיון שהיה רבי נתן רבי של רבי (עיין בגמ' בב"ב), מסתבר שרבי נתן חיבר את המשנה הזו, ולכן אמר לשון זה. ותחשב.)
* סה:
** טעייות -
איני יודע מה מכוון לומר, אם מבאר מהו, או אומר שאין לעשות כן. תחשב.
* סו.
** שמעתי ושכחתי -
מענין שרש"י מוסיף שגמ' יפרש. הרי, לכאו', לא יהיה לנו קושיה גדולה מתי שכח. עדיין רש"י צריך לפרש. אולי רש"י לא רוצה שנחשוב רע על הלל, ששכח את הלימוד שלו, ואומר שגזירה מן השמים היתה. ותחשב.
** הנח -
יש לדון למה לא עשו כן בשאלה אחרת שלהם. מסתמא, רק יש לסמוך על זה כשאין ברירה. כמו כן יש לומר שרק יש לסמוך על זה אם מסתבר שיש מי שרואה ויכול להבחין אם זה כהלכה או לא. הלל היה כן, שהיה רואה אותם, וזה מעורר את הזיכרון. יש לדון, שלא אומר שיראה אם עושים כדין, אלא מניחים שמה שעושים כדין הוא. ותחשב.
* סו:
** כהלל -
כנראה, כולם כבר לימדו את זה ממנו, שרואים שנהגו כן, אף שרק התחיל להיות נשיא. (יש לדון בזה, שאולי שני הסיפורים של הלל היו כמה שנים זה מזה. יש להעיר שאם נאמר כן, אולי יכולים לתרץ מה שהקשינו בד"ה הנח, שאולי רק יש לסמוך על זה אם כבר יש להם רב גדול כהלל, שאז יש לסמו ששמעו ממנו, ורק הוא שכח. ותחשב.)
* סז.
** נתקו -
מרש"י משמע שהעשה הוא העונש, ולכן אין עונש אחר. נמצא שמחדש שני דברים – שעשה עונש, ושאין עונש אחר כשיש כבר עונש זה. שניהם נלמדים, לכאו', ממשמעות של פסוק של העשה שמנתק ללאו.
ודע שיש לדון אם רש"י באמת אומר כן ללומדות של הדין או לא. רש"י בכ"מ אומר לומדות אחר. אז, אולי מסתבר לומר שאין כולם לומדיות, אלא מקצת מהם הם ביאורים של משמעות הפסוק, והוא שפסוק משמע, למשל, שזה העונש היחידי. בוודאי לא מפני זה פטור, אבל על ידי זה אומר לנו הפסוק שפטור. (מה שמשמע זה הוא שזה סברה פשוטה, אף שאינו נכון.) כמו כן יש לומר להיפך, שמה שאומר רש"י במק"א הוא המקור, וזה הסברה. ותחשב.
* סח:
** כשירים כל הלילה -
נמצא שמניחים שדחוייה היא, ולא הותרה.
* סט.
** שמא ימצא זבח פסול -
יש לדון אם הסיבה שלא חוששים לזה, למסקנא, הוא שלא חוששים שיהיה פסול, או שכיון שעשה כן בהיתר, שמניח שהוא כשר, בוודאי אין בו איסור. ותחשב. (במילים אחרים, יש לדון אם, כשנמצא פסול, יש איסור או אין איסור. בוודאי אין ציווי של איסור (אין זה ממש מוכרח, אבל כן נראה), אלא יש לדון אם יש ס"ר. אם רק נדחה הוא, נראה שלא יכול להיות נפקא מינא. ותחשב.)
** בשחיטה -
יש להעיר שלכאו' לא מת בשחיטה, כמו שאומר גמ' בסוף ברכות. אולי זה דומה לשחיטה או אולי נמצא ששחטו אותו על ידי זה, שנטלו את הסימנים שלו, וכמעט היתה שחיטה. אולי כיון שזה היתה על חנם, לא חל. אבל, קשה, ש"קללת חכם, אפילו על תנאי, היא באה." ותחשב. צריך לעיין שם, אם הוא גם אם לא הבין מה קורה, וקלל על טעות, או רק אם עושה תנאי, ולא קורה. ותחשב.
* סט:
** והכי קאמר אימתי -
יש לדון למה צריך לומר כן, שלשון "הכי קאמר" משמע שמשנה משמעות המשנה. איני רואה איך עושה כן. נראה שרצה לומר שלא רק מזכיר דין זה אגב, אלא שהדין שחסר מן המשנה שלעיל הוא שלא נקרב חגיגה בשבת. אז, ממשיך מזה ושואל – כיון שלא נקרב בשבת, מתי נקרב? ותחשב.
** דליכא -
עיין ברש"י. דנים ראשונים אם יש חיוב כרת על כל יום או חיוב כרת כללי. (יש לדון אם צד ראשון רק חולק מתי חל או סובר שיש חיובים שונים. אין זה עושה נפקא מינא בעונש שלו, שכבר הוא חייב כרת, אבל אולי עושה נפקא מינא בשמים.) אם רש"י סובר שיש חיוב כרת כללי, בוודאי מובן מה שאומר. אף אם לא, יש לומר שכיון שממתין עוד יום, יש חיוב כרת על אותו היום, שגילה שאין האונס מה שמאנס אותו. מחודש לומר שזה עשוה שאינו פטור מחיוב כרת. ותחשב. ודע שיש לומר כעין זה גם לצד שני, שיש לומר שחומרת כרת שונה על פי כמה הוא שוהה מלמול. אבל, אז לא כל כך פשוט שיש חילוק גדול בין שני הצדדים. ותחשב.
* ע.
** ליום ולילה -
קשה, שאין קרבן פסח נאכל ליום ולילה, שאינו נאכל עד לילה. אפשר שרצה לומר שיש בו שני דינים – נאכל ליום וללילה, ויש מניעה אחרת על אכילה ביום. יש לדון אם דין שני גם נוהג בחגיגה, אבל אף אם נוהג, יש לומר שרק מזכיר דין ראשון שלו כאן, ולא בא להזכיר דין שני. (דין ראשון הוא "זמן," כעין של שאר קרבנות, ודין שני הוא דין אחר. אם הייתי בריסקר, הייתי אומר שדדין ראשון הוא דין קרבן שלו, ודין שני הוא דין מצוות פסח שלו.)
* ע:
** דרשנים -
יש לדון מה רוצה לומר. אולי רוצה לומר שהם חכמים בדרשות, ואז היה להם לדרוש את זה. וא"ת זה בכלל "חכמים גדולים." ויש לומר ש"חכמים" רצה לומר שיש להם סברה נכונה. כדי לדרשו דבר, צריך לדעת שני דברים. צריך לדעת כללי דרשות, שבלי זה, כמובן, לא תדע מתי ואיך לדרוש, וצריך לדעת סברות ישרות, שאין לדרוש דבר שהוא נגד הסברה אלא אם כן יש הכרח גדול. אז, אומר שיש להם שניהם. גם אפשר לומר שרצה לומר שהם מוסרים דרשות טובות. העם אוהבים אותם, ורוצים לשמוע להם. אז, אין לחוש שאף אם יאמרו כן לא ישמעו להם העם. אז, העוולה גדולה, שלא רק מבטלים את עצמם, אלא גם מבטלים את כל העם. ותחשב.
** פירש -
איני מבין למה פירש. אם היה יכול להקריב אף שגדולי הדור לא הקריב, היה לו להישאר שם ולהקריב. אם לא היה יכול להקרב, כבר היה אנוס, ואין צורך לצאת. אפשר לומר שרק רצה להרחיק מרשעים כזה שיש בידם לעשות טוב ולא עושים. אבל, רש"י לא כ' כן, וגם נראה מחודש שמחמת זה ירחיק את עצמו מבני אדם שהיו "חכמים גדולים ודרשנים גדולים," ובפשטות היו, חוץ מזה, צדיקים גדולים. ותחשב.
** תרי ספיקי -
אולי זה קצת סמך למה שיש לבאר בספק ספיקא שהוא מחמת דרהר של בני אדם. רואים מכאן שבני אדם אכן מדרהרים ספק ספיקא. (אבל, יש לומר שרק מדרהרים כן כיון שהוא הדין.)
** אבין -
נמצא ש"רבין" הוא "רב אבין," כמו שאומר רשב"ם בב"ב. (אין זה ממש מוכרח, שיש לומר ש"אבין" הוא כינוי ל"רבין." לא נראה כן, שאינו כינוי מסתבר. יש לדון, שגם הוסיפת חיריק בסוף מילה אינו כל כך מסתבר, אבל עדיין אנחנו עושים אותו לכינוי. ותחשב.)
* עג.
** עבודת מתנה -
יש להעיר שאין העבודה מתנה, אלא העבודה היא הקבלה או האכילה. ותחשב. גם יש להעיר שגמ' דורש מזה (ביומא) דינים בענין עבודה ממש.
** לא בעי עקירה -
צריך לעיין בדרשת "היא" בתחילת זבחים.
* עה.
** לבסוף -
אולי זה כעין כלל ופרט. ודע שצריך לעיין בגיטין (פרק הזורק) ובכמה מקומות שדורש מכעין "ונתן בידה," שלא צריך להיות בידה ממש. הייתי אומר שמשם נדרוש שצריך להיות כפרט. ותחשב.
[יש להוסיף הערה שהייתי אומר אילו הייתי משגיח. לפעמים, רואים ילד קטן שבוכה לאם, וצועק לאם, ומכה לאב, ועושה דברים רעים, ואינו מפני ששונא לאם ושונא לאב, אלא מפני שאוהב אותם. הוא מאד רוצה לקבל את האטנשין שלהם ולקבל את האהבה שלהם. עושה רע כדי שיפנו להם. כמו כן אנו אם אבינו שבשמים. כמה פעמים, אנו עושים רע, ואנחנו לא יכולים לגמור. צריכים לדעת שלפעמים, הנשמה צועקת אל ה', ועושה את הכל כדי שיפנה ה' לנו ויאהב אותנו. זה לא נשמע כל כך טוב בעברית, אבל אם הייתי משגיח, הייתי יכול לעשות משהו ממנו.)
** מנוקבת -
איני מבין את זה כל כך; איני רואה איך יכול להיות שאין שום מתכת שנוגע בבשר. אולי המתכת קבועה בדבר אחר, ומפני זה לא נוגע בבשר.
* עה:
** אי אש... מחצה -
נמצא ש"אש" משמע כזה (אולי משמע שיהיה מחצה מחצה או משמע שיהיו גחלים חדשות), ואז נאמר כן גם בקרבן פסח. אולי רבי, כשמתיר, מדבר בזה. דחוק.
* עו.
** כדאמר -
יש לדון למה אמר כן על הסיפא, ולא על הרישא. כמו כן מצאנו בתחילת ביצה. עיין במק"א (נראה שהוא סוטה) שגמ' אמר דבר, ומקשה, ומתרץ על פי מה שאמר אחר במקום אחר, ואותו מקום אחר רק נוגע אחרי התירוץ לקושיה ראשונה. לא קל לסכם כאן מה שקורה שם, אבל מה שיוצא משם הוא שמוכרח שהראשון נאמר ראשון. אפשר לומר שאמר כן על דבר ראשון, ואמרו כן משמו בכל מקום שנוגע, ולפעמים רק זכרו מקום אחד מן אותם המקומות. גם אפשר שמישהו אחר תי' כבר במקום הראשון, ולא זכרו מי, ורצו להביא אותו ממקום שיכולים להביא שם האמורא שאמר אותו. כן נראה לי. ותחשב.
** שאינו נאכל מחמת מולחו -
עיין ברש"י. גם אפשר לפרש (וזה ייצא כדין שאומר רש"י) שצריך להיות שאין המלח עושה שנאכל. מילים אחרים, "אינו נאכל מחמת מולחו." ותו"ת.
* עו:
** תערובת טעמים -
לכאו', רצה לומר תערובת של ריח, ולא של טעם. אפשר שהסיבה שתערובת ריח יאסור הוא שגורם לטעם. (נראה שהדיון הוא אם טעם שבא על ידי ריח חשוב.)
** ה"נ מסתברא... אפילו -
ק"ק, שאולי בזה משמיע לנו שאינו מפני תערובת הגוף, אלא מפני תערובת טעמים.
* עז.
** אלא רבי יהודה -
קשה, שרק שמענו שני תנאים, רבי יהודה ורבי שמעון. בדר"כ, הלכה כרבי יהודה נגד רבי שמעון. צריך לומר שיש תנא אחר. אולי יש דיון אחר בזה בגמ', ושכחתי איפה הוא.
** קרא עלי מועד -
עיין ברש"י. צריך לעיין שם בגמ', אבל משמע שמועד הוא יום שלושים. נמצא שזה נחשב ראש חודש, אף שיום שלושים הוא. דנו הפוסקים בזה.
* עז:
** כל היכא -
משמע שחולקים בכלל זה. כמו כן מצאנו בכלל כזה בתחתילת סוטה. אבל, דע שלא צריך להיות שחולקים בכלל, שיש להעיר שתמיד יכולים לדרוש משהו, שיש מושג של "אם אינו ענין." (עיין בגמ' בפרק שני דפסחים, שלפעמים אומרים כן אף שרחוק הוא מאד מן הסברה.) אז, צריך לומר שרק נקרא "אפשר לדרוש" אם הדרשה מסתברת (אולי מסברה או אולי בקרא). אז, יש לומר שחולקים כמה מסתבר הוא או כמה מסתבר צריך להיות. ותחשב.
** דם דכי ליתיה -
עיין ברש"י. צריך ביאור למה לא רק אמר כן גמ' – דם מעכב כיון שעושה כפרה, וכהנים אוכלים משולחן גבוה.
* עח.
** רבי אליעזר -
מהמשך גמרא מוכרח שיש מחלקת בין רבי אליעזר ורבי יוסי אף שרבי אליעזר היה רבו של רבי עקיבא רבו של רבי יוסי. (עיין ביבמות, שתוס' לא רוצה שיהיה מחלקת בין רבי אלעזר בן עזריה ורבי מאיר.) אפשר לדחות שרבי יוסי זה הוא רבי יוסי הגלילי.
** ביחיד -
עיין ברש"י. יש להעיר שאז קושיה ראשונה עדיין קשה. ועיין לקמן בגמ' שממלא את הדין.
* עט.
** כחצי -
יש להעיר שהיה אפשר לדון ביחס בין שני דברים שמקריבים בעולה, אם הם אותו מצווה או מצווה שונה. מן הצירוף כאן ובפיגול ממשע כצד שני. ותחשב.
* עט:
** לישנא קמא... -
מסתמא, יהיה טוב לעשות סיכום מגמ' זה.
* פא:
** מועדו -
משמע שלומדים הל"מ מגזרה שווה. עיין במכות (י:), שנראה שזה מחלקת.
** משובר -
משמע שסומכים על זה אף אם רוב הוא נגד זה (שהרי לא מסתבר שכך קרה).
** הציקנים -
קשה למה מתירים להם לשרוף מעצי הקדש, כיון שאין צורך בזה. אולי יש טוב במה שהם מתביישים, אלא שלא מטריחים אותם להתבייש. אבל, אם רוצים, כן עושים.
** וטומאת -
עיין ברש"י. זה מראה מקום. אבל, דע שאולי גמ' זה אומר כעין "ומהיכי תיתי שהל"מ? דאיתמר...."
** טמון -
שמא- נמצא (ולכאו', כן מוכרכח מן המציאות), רק צריך שאפשר שאף אחד לא הכיר בו, ולא צריך להיות שבוודאי אף אחד לא הכיר בו. ותחשב.
* פב:
** כדאמר -
הסיגנון מעניין; חוזר לתי' שכבר אמר, ולכאו' לא משנה אותו, אלא מבאר אותו. ותחשב.
* פג.
** חל י"ט -
נמצא שבגמ' זה יש ט"ז, י"ז, וי"ט.
** רבי יעקב -
אולי אינו רק רבי יעקב, ואולי גם רבי סובר כן (עיין לעיל).
* פד.
** תניא כוותיה -
אין זה ראיה, שכולי עלמא מודו שי שתנא שסובר כן. אולי לא מסתבר שיהיה סתם בריי' כי"א שבמשנה. יותר נראה שלא מביא ראיה לרבא נגד שאר השיטות, אלא מביא ראיה שסגנון זה אפשר. ותחשב.
** דדרמא לך הא -
נראה שאף שלא מזכיר אותו, שאל אותו. בדר"כ לא מזכיר שהולך.
* פד:
** האי פסול הוא -
מעניין שנחשב פסול. לכאו', זה רק אפשר אם דחויה. ויש לדון, שאולי מה שהותרה רק מה שיכול להקריב, ולא הכשרות שלו.
* פה.
** והתניא -
אין זה ראיה לכל השיטה.
** חיבור -
משמע שכדי להיות טומאת סתרים, צריך להיות חיבור.
* פה:
** וכן לתפילה -
יש לדון אם רצה לומר שמצטרף כשכבר יש מנין או מצטרף להיות מנין. עיין ברש"י, לראות מה ממשע.
* פו:
** בושה -
יש לציין לגמ' בכתובות, שאומר שיביטו בה. אבל, לבסוף דוחה אותו.
** ווהא דעיילי -
עיין ברש"י, שנראה שסובר שמדבר בשעת יציאה. לולי רש"י הייתי אומר שמדבר בשעת התחלת הסעודה, והוא שלא ממתין למי שמאחר לבוא. ותחשב.
* פז.
** מצאתי -
בהגהה זו ברש"י כתב, בסופו, "והושע קודם לכולן." קשה, שלכאו' מסיק גמ' שלא אומר הפסוק שהיה הושע קודם, אלא אומר שהיה הושע הגדול שבהם. (באמת, צריך ביאור למה אומר שהיה תחילה שבארבעתם, שבשני הדברים שאומר – מוקדם וגדול – בוודאי אינו כן כלפי כל שאר נביאים, אלא הפסוק רק אומר שהוא כן כלפי אותם הנביאים שניבאו באותו הפרק.) אפשר שכשאומר "קודם" מכוון לומר "גדול," ואפשר שרש"י סובר שכשאומר "גדול" מכוון לומר "קודם." גם אפשר שרש"י לא מכוון לומר כאן מה שאומר גמ', אלא דבר אחר מעורר רש"י שהוא נכון, והוא שהושע היה הראשון שבהם. ותחשב. (ודע שאפשר ליישב, על ידי זה, מה שהקשינו לעיל, למה מניח שרצה לומר שהוא הגדול. אולי, כמו שאומר רש"י לא צריך פסוק זה לראות שהושע היה הראשון שבאותם ארבע. אז, אם אומר שהוא מוקדם, צריך לומר שהוא הנביא הראשון שבעולם. זה בוודאי לא נכון, וצריך לומר שרק על אותם ארבע מדבר. אינו אומר שהוא מוקדם, שזה פשוט, וצריך לומר שאומר שהוא גדול.
** גומרים בה -
עיין במה שאומר רש"י. יש להעיר ששני מיני גמר זה הם מאד שונים, וקצת מוזר להרכיב את שניהם בפירוש מילה זו. אפשר לומר שפירוש של גמר הוא שיש דבר שלא נשאר כלל. מה שלא נשאר כלל הוא יכולת לביאה. יכולת לביאה בא משני דברים – מיכולת פיזיקאלי ומרצון. כדי לגמור את היכולת לביאה, צריך להיות ששניהם נגמרו, הוא כמו שאומר רש"י, שנגמרו ביאתם (ואז יש מניעה פיזיקאלית), ונגמר תאוות לבם (ולא רצו עוד יותר מזה).
* פז:
** גירים -
כמובן, יש לציין לגמ' ביבמות שאומר ש"קשים גרים לישראל כספחת."
** שקרוב לשונם -
אולי רצה לומר שאז לא צריכים ללמוד עוד שפה (וכבר מבינים שפה של מקום גלות) או שאז אף בגלות, אף אם קצת שוכחים את התורה, יהיה קל לחזור לו, שלא צריכים ללמוד עוד שפה כדי לחזור לו.
** אותיות פורחות -
נמצא לשון זה בשני דברים – אותיות הלוחות (כאן) ואותיות ספר תורה (בעבודה זרה).
* פח.
** על ידי -
לא משכחת – לכאו', יש ציור אחד שנמצא, והוא באיילונית, לפי המד"א שנעשה גדולה למפרע, אם נאמר שלא נעשה בוגרת למפרע, ואז עדיין היתה אמה. אבל, נראה ששניהם תלויים זה בזה, ואז לא נראה.
** שקראו -
לשון זה מעניין, שהם לא קראו אותו שום דבר, אלא כן נקרא בפסוק שמזכיר סיפור שלהם עמו. אולי מסבר שנקט כן על שם לשון שלהם. ותחשב.
** בדקפדי -
מעניין שזה נחשב הנאה, אחרי שנאכל על השובע.
* פח:
** במלך -
נראה שלא מקפידים כל כך כיון שיכולים לאכול כמו זה בכל שעה שרוצים. אז, אף אם לא בא הכי טוב להם עכשיו, יבוא בזמן אחר. אבל, שאר בני אדם מקפידים, שרק בשעה זו אוכלים בהמה כזה. ותחשב.
** במלך -
כמובן, יש לציין לסיפור בסוף כריתות (ובפסחים) במחלקת גדול בין מלך ומלכה לענין כבש או עז.
** כל שכן אבריי' -
צריך לחשוב על החילוק.
** והא איכא חד -
קשה למה לא אומרים ללכת בתר רוב. אולי לא נאמר כן כאן כיון שיוצא מזה סתירה (שכולם פטורים). צריך לחפש בשאר דיני רוב כזה.
* פט:
** לתקוני -
יש לדון אם רצה לומר שקבלו אותו אף שידעו שאוכל הרבה שרצו שאם צריכים יש מי שיכול לאכול את כל השאר או שלא רצו אותו, אבל הוצרכו לקבל אדם, כיון שצריך מי שיאכל אותו, אבל עדיין לא רוצים שיאכל יותר מחלקו. במילים אחרים, יש לדון אם ההצלה מנותר באה על ידי אכילה יותר מחלקו או על ידי אכילה כחלקו. ותחשב.
* צ:
** ביום ההוא -
קשה, שאולי אותו היום הוא יום ששי. ותחשב.
* צא.
** שהוא -
עיין ברש"י; יש לדון אם אומר שאי אפשר להיות במת ציבור בשעת איסור הבמות או שלמעשה לא קרה.
** ופרכינן -
לאו פירכא כולי האי- יש לדון בזה, שיש לומר שגמ' ידע כללי דרשה, וידע איזה יותר מסתבר. כנראה, רש"י גם ידע כללי הדרשה. ותו"ת.
* צא:
** נשים -
לכאו', נצטרך שלש פסוקים: אחד לפטור נשים, אחד לומר שלא יקריבו בפני עצמן, ואחד לומר שיצטרפו לקרבן. כנראה, מניחים שכיון שלא חייבות, אין מביאות בפני עצמן.
** ידקדקו -
יש לדון אם ישרפו אותו על מה שאינו באמת פסול או דיקדוק שלהם יביא לפסול ממש. מרש"י אולי משמע כראשון. ותחשב.
* צב:
** מי שהיה -
עיין ברש"י זו. צריך לחזור עליו, שאינו פשוט.
* צג.
** תשלומים דראשון -
משמע מזה חילוק בין אונס למי שלא היה בכלל חיוב. צריך לחשוב מה זה. (נראה ששייך למה שמצאנו שלמשל לבישת בגד של ארבע כנפות גורם חיוב ציצית. יש דבר שמשנה עד שיש צורך לעשות דבר. איני מבין מה משנה, שתמיד הוא הכי טוב לעשות אותו, אבל מה שישנה אולי יורה על זה. צריך לחשוב.)
* צג:
** לדידי חזי לי -
מעניין שמניח שאותו מקום נשאר בגודל שלו, אף שהלך מסדום, והרי כל סדום נהפך. (במילים אחרים, אפשר להיות שלוט הלך יותר או פחות, ושאותו מקום נשנה, כיון שחלק ממנו הוא בסדום, והרי שינוי גדול קרה לסדום.)
** לדידי חזי לי -
קצת קשה איך יש הו"א לדמות לוט, שמסתמא היה רץ, להליכת שאר בני אדם. ותחשב. (אפשר לומר שלא היה רץ, שבטח שה' יושיע לו, שמלאכים היו עמו.)
* צד.
** סומכא דרקיע -
לכאו', זה מיוסד על מה שיאמר גמ' לקמן, והוא שחמה מהלת למעלה מן הרקיע בלילה. אז, מניח שיש דבר שהוא "רקיע," והולך למעלה ממנו (ולא באמצע שלו), ואז יכולים ללמוד את העובי מן הזמן שבין יום ללילה.
** ארבע מאות -
אין זה צריך להיות קשה, שהרי זה מדבר בארי"א, ורבא היה מדבר באורך. אבל, לא מסתבר שיהיה לו ארי"א של ששים פעמים ששים פעמים ארבע מאות על ארבע מאות פרסא, ועדיין יהיה לו אורך של שש אלף פרסא.
** תחת כוכב אחד -
קשה, שאולי שאר הכוכבים הם להלן מן הקרקע. צריך לומר שכשרבא דיבר על "העולם," לא היה מדבר על הקרקע (אר"ט), אלא על העולם ממש.
** אלא בין -
כיון שהוא תחת כוכב אחד, צריך לומר שיש כוכבים בין המזלות.
* צד:
** תנאי היא -
עדיין קשה למה לא אומרים לו ליכנס כשהוא חוץ מירושלים, שגם זה קל. יש לדון, שאולי מפני שהיו הרבה בני אדם שם, לא נכון שהוא קל ליכנס לתוך עזרה ולשחוט קרבן פסח. ותחשב.
** ידוע שחז"ל
טעו מאד בענינים אלו (של אסטרולוגי"א). נראה לבאר על פי מה שיש להעיר שקשה למה בגמרא – שהוא תורה – דנו בזה; הרי, זה לא שייך ללימוד תורה (ובאמת, לא נראה שהוא נוגע לנו כלל). נראה שהסיבה שדנים בו הוא מפני שיש איזה מוסר ללמוד ממנו. אז, אפשר שאף אם טועים, עדיין יש ללמוד אותו מוסר ואותו לימוד ממה שעשה ה' עולם שנראה ככה. למשל, אם לומדים איזה מוסר ממה שהחמה מסבב את העולם, יכולים ללמוד אותו ממה שעשה את ה' עולם שנראה ככה, אף שאינו ככה. אז, לא דקדקו כל כך אם נכונים, שאין נפקא מינא מזה. ותחשב.
** בן בנו -
עיין ברש"י. כעין זה מצאנו "מה... תלמיד של משה...," אבל שכחתי איפה (נראה לי שהוא בסוטה).
* צה.
** אסור בבל יראה -
מעניין שמזכיר את זה לדין של פסח, שהיה נראה לומר שאין יחס בין דינים אלו של החג. ותחשב.
** תלמוד לומר -
מן הגמ' הזה משמע ש"לא יראה" הוא לאו הניתק לעשה. זה נוגע לגמ' בתחילת ביצה. יש לדחות שנחשב כעין לאו שניתק לעשה כיון שאין עליו עונש. אבל, זה תלוי באם יש דמיון בין כל לאווים שאין בהם עונש, אף אם הסיבה שאין להם עונש שונה. (יש להוסיף שאולי זה תלוי באיך עשה גורם שאין עונש. ותחשב.)[fn:2]
* צה:
** מפני טומאה דחיתיו -
איני יודע למה לא נאמר כרבי יהודה, שלכאו' סברה שלו מסתבר. לא רואים שאין להקריב קרבן פסח בטומאה אלא כיון שיכולים להמתין לפסח שני. אפשר שלא צריך מקור לזה, שבדר"כ אין להקריב קרבן בטומאה. ותחשב על זה.
** אפשר -
עיין ברש"י, שכ' שדבר מצווה צריך הלל. משנים את הגי', וכן נראה, שיש הרבה מצוות שלא אומרים הלל עליהם. אולי צריך להיות מצווה של שמחה. ותחשב.
* צו.
** מקחו בעשור -
עיין ברש"י. נראה שהיה קשה לרש"י שכיון שיש צורך לביקור, בוודאי יקח אותו בעשור. (יש לדון, שאולי בא לומר שלא יכול לקנות אותו קודם. יש לדון אם זה היה הדין בפסח מצרים.) אז, מפרש שהחידוש הוא שלא צריך לומר בעשור שהוא לשם קרבן פסח, אלא רק צריך לבקר אותו. ותחשב.
** אותו -
קשה, שאולי "ועבדת" ממעט מזה, וזה ממעט דבר אחר.
** בן נכר -
עיין במה שכ' רש"י. דע שזה מחלקת שם בהערל.
* צו:
** אסמכתא -
נמצא שיש אסכמתא למה שהוא פשוט עד כדי שלא צריך פסוק. ותחשב.
* צז.
** למה לי קרא -
קשה למה לא משיב שזה אסמכתא. צריך לומר שאין לו דרשה אחרת מן הפסוק, ואז צריך לומר שזה דרשה אמיתית. ותחשב. (יש לדון אם לשון ראשון מודה שזה ראיה, ורק לא מביא אותו, או סובר שאינו אף ראיה. ותחשב על זה.)
* צח:
** רבי שמעון -
כאן מוסיפים חידוש, כיון שזה אינו להכשיר את המביא. (עיין שם בזבחים.)
* צט.
** אין מביאים עמו חגיגה -
דין זה מעניין, שעדיין נאכל על השבע. כנראה, לא החמירה תורה לחייב אותו קרבן כדי לשמור שיאכל אותו על השבע. ותחשב.
* קא:
** ברכה אחריהן -
יש לדון אם מה שהוא במקומן סימן או סיבה. אם הוא סימן, הוא סימן לחשיבות הברכה. אז, הוא עוד עומד באמצע אותה הסעודה, כיון שמחוסר ברכה חשובה. כן נראה מרש"י. אם הוא סיבה, הוא שעוד מיוחס לאותו מקום, כיון שצריך לחזור לשם לברך. ותחשב.
* קב.
** תניא כוותיה -
יש להעיר שלעיל היה יוצא שתנאי הוא. אז, אין זה מוסיף כוח לר"ח.
** תניא -
עיין ברש"י. לכאו', בא לבאר למה לא מדייק גמ' בפירוש מלשון עקירה. אומר שאינו רק מפני שכבר דייק אותו דיוק לעיל, ואז לא צריך לפרש אותו, אלא מפני שאין צריכים דיוק זה כאן, כיון שנאמר בפירוש.
* קב:
** קידוש והבדלה -
עיין במה שכ' רש"י. נראה שלשון רש"י משמע שאומר שני דברים. דבר שני פשוט, והוא ששניהם מזכירים קדושת יום שני, שקידוש אומר אותו בפירוש, והבדלה אומר "בין קודש לקודש." הראשון לא כל כך פשוט. אולי הוא רק מפני ששניהם מדברים על (ואולי אף משנים) קדושת היום. זה מחודש, שהבדלה ממעט קדושת היום. נראה שאפשר לומר פשט אחר.
קשה למה מברכים לה' על הבדלה. הרי, שבת הוא קדוש, ואיך אפשר שמודים לה' על סילוק קדושה. נראה שהביאור הוא שקדושת שבת רק אפשר כיון שאינו נוהג כל הזמן. הענין הוא העלאת קדושה, ולא רק מה שיש בו קדושה. אז, אפשר לומר שברכת הבדלה וברכת קידוש דומים, ששניהם הם על מציאות אחד של העלאת קדושה – אחד הוא על מה שאין קדושה בזמן אחר, ואחד הוא על מה שיש קדושה אז. ותחשב. (אבל, דע שהם עדיין על קדושות שונות, שאחד הוא על יום ראשון, והאחר הוא על יום שני. ותחשב.)
** דאית ליה -
עיין ברשב"ם. קשה איך יהני לתת אותו בארבע כוסות, שכבר יש מצווה מזה. באמת, ק"ק למה לא מזכיר גמ' עשיית מצוות חבילות שבא מארבע הכוסות. ותחשב.
* קג.
** הילכתא כרבא -
קשה למה צריך זה, שתמיד הל' כרבא. (כעין זה מקשה גמ' בעירובין (כעין מד), על הכללים של הלכה כתנא זה או זה.) אולי כאן מכריעים, ואז הו"א שאין כלל זה נוהג. (יש לדון אם זה מלמד לנו שכלל זה מלמד, או מלמד לנו שהל' כרבא, אף שאין הכלל נוהג.)
** נהגו -
מעניין שהיה מקשה לו על זה, כיון שכך כבר נהגו העם (ואינו תמיהה לו). ותחשב.
** ורבה -
עיין ברשב"ם שכ' שיש סתירה בין זה לזה. זה סתירה למה שאמר גמ' שהם דבר אחד. צריך לומר שזה מכחיש כוח זה, אבל מה שעושה יש בו ג"כ דמיון. (מצאנו כעין זה בכ"מ, שמה שהוא אפוזי"ט הוא ג"כ דומה.)
** מן הגמ' והפי'
משמע שאמירה על הכוס אינה אמירה על הכוס, אלא אמירה עם ברכת "בורא פרי הגפן." ותחשב.
* קד.
** חנניה אחי -
יש להוסיף את זה למנין אחים ת"ח שלנו.
* קה:
** כי היכי דלא ליהוו -
לשון גמ' מעניין, שלא אומר שהוא כדי שלא יראה כמשוי, אלא כדי שלא יהיה כמשוי. אולי הוא מפני ש"החיצוניות מעוררות את הפנימיות."
* קז.
** שיכרא -
צריך ביאור למה לא אף שאל לו אם הוא חמר מדינה. גם צריך יבאור למה הביאו לו עוד אחרי שלא הבדיל בו. אולי רובם לא זכרו.
** ש"מ תלת -
גם ש"מ שמבדילים על חמר מדינה.
** למירמי -
יש לדון אם רצה לומר שאין להקשות על שום גידול, או שיש להקשות רק על "גידול" הסתם. (במילים אחרים, יש לדון (וזה יכול להיות שונה בכל שם[fn:3]) אם מה שזה סתם וזה סתם עושה שיש סתירה. עיין בכעין זה ביומא, בסתירה גבי מחיקת שם ה' וטבילה בזמנה, שמסיק ש"רבי יוסי" אינו סתם רבי יוסי, אף שנאמר סתם.)
* קז:
** כארבע -
אז, בין כך ובין כך יש חידוש. ותחשב.
** מיגרר -
קשה, שאולי לא עושה כלום. ותחשב.
** מיגרר -
קשה, שגמ' אומר שזן. צריך לעיין בזה.
* קח:
** רובא -
קצת משמע שצריך מי שישתה את השאר, ולא מספיק לשמות רק רוב, וזהו. אבל, נראה שאין זה ההלכה. נראה שהסיבה לדין זה יהיה שרק אומרים רוב על כל. מפני זה, אין שש בני אדם מנין, אלא אם כן יש עשרה. אז, נראה שיש לדון אם הענין הוא רוב היין או רוב השתייה. ותחשב.
* קי.
** אפי שוקא -
אז, קושיית הגמ' לעיל (לענין זוגות של ארבע כוסות) הוא קשה מפני שמניח שיש שהולכים לישון או הולכים לשוק. ותחשב.
** רבא ואביי -
אז, יש תי' אחר לקושיית הגמ' לעיל.
* קי:
** טמא -
רצה לומר, מצטרף. אבל, זהו ציור ההיתר מחמת זה, ואז אינו "טמא."
* קיא.
** חמימי -
לכאו', אין הענין חמימי לחמימי, אלא שלענין דבר אחר יש מזיגה. ותחשב. (אז, גם אם אחד קר ואחד חם, כן הוא הדין.)
* קיא:
** לדידיה -
יש שמשנים את הגי'. נראה שנקטים לשון שו, ומדבר בלשון כזה כדי שלא לדבר על מיתתו, כמו שאומרים בגמ' "שונאי ישראל" כשמכוונים לת"ח.
** שעה -
משמע שהוא מפני השעה. עיין בגמ' לעיל, שנראה שאמר שהוא מפני שנשא בת כהן.
* קיב.
** פלניא -
לכאו', לא אומר "פלניא," אלא אומר השם שלו.
** כדתנן רבי יהודה בן תימא -
צריך לעיין איך זה שייך לכאן.
** כשהיה חבוש -
זה מעניין, שהיה מוסר נפש מאד לתורה על ידי אמירת דברים אלו, ואינו נראה שהם אף תורה, שנראה שהם רק עצות טובות. ודע שהגדרת "תורה" לא כל כך פשוט לי, שכפי מה שנראה לי, יש חלקים גדולים של ש"ס שאינם "תורה," אבל זה קשה ומוזר לומר.
* קיב:
** איכא דאמרי -
עיין בסיפור שמביא רש"י. יש להעיר שרב פפא היה בעל בשר, כמו שאומר גמרא בבבא מציעא. אז, לא קל לחשוב שהרג אותו בישיבה עליו. ותו"ת.
* קיג.
** אי לאו דרמאי -
אני חושב שלעיל אמר שהוא מפני שנשא בת כהן. צריך לומר שזה וזה גרם.
* קיג:
** ת"ח שבבבל -
יש לציין לגמ' במק"א שמדבר איך ת"ח שבבבל היו לוחמים זה עם זה, ובא"י היו מרצים זה את זה. (אבל, לאידך גיסא, "מחכו עליה במערבא," ובתחילת יומא, אומר ר"ל (בן א"י) ששונא את בני בבל.)
** אין הדעת -
עיין ברש"י. נראה שמוסיף שני דברים – שאף לאחרי חרטה, נבזים, ושבפני עצמם נבזים. איני יודע מהו מקורו של רש"י להוסיף נקודות אלו.
* קטז.
** קפא דכולהו -
עיין במה שפרש"י. גם יש לומר שכיון שקפא של זה נתקן בזה, ושל זה בזה... עד שמגיע לחמים, נמצא שלפעמים צריך ללכת על כולם עד שמגיע לחמים. אז, אפשר שלא מתקן את כולם, אלא שבאכילת אחד מהם, יגרום אכילת השאר, ואז נמצא שצריך חמימי לתקן את כולם ולגמור את הגלגל הרע. ותו"ת.
* קיז.
** למעני -
איני יודע למה מזכיר את כל הלשון פעם השלישית, אחרי שכבר לא מזכיר אותו בפעם השנית, ולא יזכיר אותו שאר הפעמים. ותו"ת.
* קיח.
** אינו מקפח -
משמע שיש למלאכים שכר. נראה לדחות את זה על פי מה שיש להקשות איזה חידוש יש במה שה' לא מקפח שכר של כל בריה, שפשוט שזה הדבר הנכון לעשות, ולא נראה בזה גדלות. יש לדון. נראה שאפשר לומר שאף שלא זכאי ממש בשכר, שאין למלאכים שכר, שאין להם בחירה, עדיין נותן שכר. (יש לדון למה עושה כן; כנראה, יש טוב בנתינת טוב תחת טוב, חוץ מן השכר שזכאי בו.) זהו הגדלות במה שעושה ה'. ותחשב.
* קיט.
** עיין ברש"י
בביאור למה הביאו את הממון שלהם למלחמה. נראה שלולי רש"י יש לומר שהוא מפני שחששו שלא ינצחו, ושהנוצחים ירצו את הכסף שלהם, ואז יבואו לעיר שלהם, ויקחו את הכל. כשהם שם, גם יחרבו את העיר. אין מי שמציל את העיר, שכולם נהרגו במלחמה. לכן, הביאו את עושר שלהם עמהם, כדי שלא ילכו הנוצחים אל העיר שלהם כדי לקחת את כל הכסף. ותחשב.
* קיט:
** רבי יוחנן -
יש לדון אם רבי יוחנן חולק על שמואל, שלא נראה חילוק ביניהם. אבל, מה שמביא את דבריו, ומה שאף מביא בריי' כמותו משמע שחולק. אפשר לומר שמוסיף שאף אכילה מועטת (אולי שאינה כל כך חשובה, ואולי אין לה טעם גדול) אסורה אחרי אכילת מצה. ותחשב.
* קכ.
** כולם -
עיין ברש"י. לא פשוט לי עדיין למה אסור לאכול מצה אחר שישנו. עיין בהוספות שבעוז והדר. אבל, אז נמצא שאין כל כך יחס בין דין מצה לדין פסח. ותחשב.
* Footnotes
[fn:1] יש להעיר שכמו כן אומרים בכמה דברים – בין בתורה, ובין במילי דעלמא – והוא מה שנקרא תער של אוקה"ם. אינו כל כך פשוט למה הוא נכון, ולמה אומר כן. יש סיבה לומר שפשט שלא עושה הנחות הוא יותר נכון, שלא צריך לדחוק להניח דברים, וזה דומה לדבר זה, אבל לא נראה שהוא שווה. צחשב על זה.
[fn:2] ודע שאפשר לומר שממש שווים הם, שיש לומר שפשוט שהעשה מנתק אותו לגמרי, ועושה שאין איסור הלאו קיים עוד. אז, פשוט שלא לוקה. החידוש היותר גדול הוא שאינו לוקה אף קודם שקיים עשה. אבל, אולי הסיבה לזה הוא שמחשיבים את האיסור שלו להיות שלא קיים עשה (שזה ינתק את הלאו). אז, הוא לאו שאין בו מעשה. ותחשב.
[fn:3] בוודאי יש שמות שאפשר להקשות כן, שזהו כל סתירה בין ר"מ ור"מ, ובין ר"י לר"י, וכדומה.
