* יא:
** או אונס -
יש לדון ל"ל רק מזכיר אונס, ויכלל כל מיני אונס בו. עיין בגמ’ גבי אבל, שמזכיר חידוש. נראה שגם מחדש ש“הטעהו פועלים“ נחשב אונס. הוה אמינא שחייב למצוא פועלים, אפילו ביוקר, כדי שלא לעבוד בחול המועד. ויש לדון למה, שהרי הוא גופא יהיה דבר האבד. ותחשב. גם יש לומר שהיה לו להכיר שיטעו אותו; יותר מזה, היה לו להתנות בכל פעם באופן שאי אפשר להטעות אותו. ותחשב.
** פתח -
היה נראה בפשטות לפרש המשנה (ואולי כן מפרש צד ראשון שבגמ’) שזה ציור של אונס שיכול לקרות לו. (אבל, לא מוכרח שהוא מפרש כן, שאפשר שכוונתו לפרש שנקט אבל לומר שאחריו אסור, שדבר בו ולא אמר היתר. דחוק, אבל אולי משמע כן ברש"י.)
* יג.
** אלא אמר ר“א -
אז, לכאו’, אף דוחה מש"א לעיל שמותר משום שמותר להדיוט בחולו של מועד.
* יג:
** מי שנשאל -
זה מחודש, שהו“א שהיה לו לשאול קודם.
** ואלו מגלחים -
מעניין שמתחיל במי שמגלח, ולא מתחיל לומר שבדרך כלל אין מגלחים.
* יד:
** השתא משמתינן -
יש לדון ל"ל נאמר שמשמתים אותו עכשיו, ולאחר יום טוב יחול. אולי מסתבר שכיון שלא חל מיד, לא יחול לאחר זמן. ויש לדון מהיכי תיתי. גם אפשר שסובר שאותו סיבה שעושה שלא יכול לנהוג נידוי יעשה שלא יכול לעשות נידוי. (למשל, אם הענין הוא שרוצים שיהיה שמח, ואין מי שנוהג נידוי שמח, כיון שחשוב על נידוי שלו, אז מסתבר שלא יכול לחדש נידוי, שזה בוודאי יסיר ממנו שמחה.
* טו.
** מנודים לשמים -
מחדש אביי, אז, שכשאומר ”מנודים“ רצה לומר מנודים לשמים. זה מחודש, לשני טעמים. ראשון הוא שאומר אותו סתם ושני הוא שלכאו’ הם מנודים לשמים, דהיינו שחוששים שה’ לא שמח עמהם. אז, אינם כמו מנודים לשמים, אלא כך הם. צריך לומר שאף שכנראה אין ה’ כל כך שמח עמהם, עדיין אינם ממש מנודים לשמים.
** מנודים
- עי’ ברש"י. נמצא שגמ’ בשאלתו ידע את התשובה. אולי שאל אותו כדי לומר אותו באופן של שו“ת, אולי אגב שאר (שאולי לא ידע) או אולי מפני שיותר קל לזכור או להבין, ואולי שואל ראשון לא ידע, אבל המסדר סידר אותו ככה.
* טו:
** מנודה לשמים דקיל -
מסתבר לומר שהוא חמור, כון שלה’ הוא מנודה. אבל, צריך ביאור למה יהיה יותר קל.
* טז.
** יש לדון
כמה מדברים הנזכרים כאן הם חיובים ממש.
** אמר ליה -
נמצא שלשון הרע מותר לפי תומו. אולי בוודאי חטא, אלא שלא מסתבר שחטא במזיד. אבל, יש לדון ל"ל אמר שסבר שהיה תועלת בזה, לצורך כבוד בית נשיא.
* טז:
** אלמלי -
כמובן, יש לציין לגמ’ שאומר שטוב שה’ אוהב אותך, ש"שאול באחת….“
** רבה בר בר -
עיין בסנהדרין, ששם גרס ”רבה בר חנא.“ נ“ל שיש תוספות שכ’ שרבה בר חנא אינו רבה בר בר חנא. אולי שניהם היו אחיינים שלו או אולי צריך לשנות גי’ שלא אחד מהם.
** שאני גוזר -
צריך ביאור במה זה ”כמוני,“ שלכאו’ זה יותר ממני. אולי אף אם היה דוד גוזר היה ה’ מבטל אותו. (ויש לדון, שאינו כן גבי צדיק, שגוזר וה’ מקיים.) ותחשב.
* יז.
** עביד דינא -
קשה, שכל אדם עושה כן, כמו שמפורש בב“ק.
** מאי טעמא -
עיין ברש"י. גם היה אפשר לומר שאלו היו השמועות רעות. ויש לדון, שכל הענין הוא שלא יכירו בו; אם עשה כן, לא היו מכירים בו.
** וילבש שחורים -
לכאו’, הכוונה היא שילבש בגדים שאינם מראים שהוא אדם חשוב. (גם יש לציין למש“א גמ’ בשבת שהיו ת“ח לובשים בגדים נאים בבבל.)
** אדרבא -
יש לדון למה זה חל; כיון ששמתא ראשון לא חל, נמצא שאין לו טענה. אולי מה שאמר שהוא בשמתא, שהוא בזיון מחמת בני אדם שלא מבינים שלא חל, הוא די לחייב אותו בשמתא. באמת, יש לדון מהיכי תיתי שדבר כזה מחייב שמתא. ותחשב.
* יח.
** דאמר -
לכאו’, רצה לומר: ”ויודעים אנו שכן אומר שמואל, שהרי אומר….“ וצריך ביאור. (ודע שמצאנו לשון כזה כ“פ בברייתות.)
** ואסתייעא -
לא רצה לומר שגרם אותו, שה’ אמר שלא עלה על לבו, אלא רצה לומר שכיוון אל האמת. אז, קשה איך לומד משם. ותחשב.
** אמגושי -
ע“ש, שכאן מדבר רב, ונ“ל שאחד מאלו רב הוא. וע"ש.
* יח:
** בכל יום -
יל“ד ל"ל מקשה מ“ארבעים יום קודם.“ אולי זה רק לגבי נישואין ראשונים, אבל זה הוא אף גבי נשואים שני. שם תלוי במעשים, ונתחדש בכל יום. אז, היה אפשר לטעון שרק גבי זה מהני רחמים. זה מעניין, וצריך לחשוב.
* כ.
** עצרת -
ואם תאמר נדרוש לחומרא. וי“ל שכיון שאינו מדאו’ (שנלמד מעמוס), לא נדרש לחומרא.
** שמועה -
יש לדון למה אין דבר כמו פסח, ול“ל דן גמ’ בזה.
* כ:
** א“ל -
וקשה לי שהוציא- נראה שהחולקים סוברים שאינו כל כך רע כיון שהבין פתאום שאינו האמת. נראה שאולי אף רש"י מודה שאינו ממש שקר, שהרי רש"י לא אומר שקשה שיאמר שקר או שיעבור על הלאו, אלא שיוציא שקר מפיו. ותחשב.
גם יש לציין לגמ’ ביבמות (גבי נשים רעות) כמה החמיר רב בשקר. ותחשב.
* כא.
** ומת בנו -
קצת מעניין, שהרי מגמ’ בשבת משמע שרק היו לו חמש בנים, והיו כולם חשובים. צריך לומר שחי די להיות חשוב ועדיין מת בימי רבי יוסי.
** משלישי -
אז, קשה למה אמר ”שלש ימים אסור.“
* כב.
** אין הלכה -
קשה, ש“כל מקום ששנה רשב"ג במשנה הלכה כמותו.“
** אגב, נראה
שאביי היה יתום מפני שאביו מת מוקדם, כיון שהיה (כמו אביי) מבית עלי. ותחשב. (יותר מזה, נראה שאולי מסתבר שאף אמו היתה, שמי ירצה לישא מי שימות חוץ מאחרת שתמות מוקדמת.)
* כה.
** כדי -
למס’, נראה שיכולים לומר מילים אלו, והוא ש“כדי“ רצה לומר שניטל ממנו אם לא בוכה כדי שיבכה. אבל, אז, צריך לומר שהוא כעין קנס, דהיינו שנענש כדי שלא יעשה כן.
** לס“ת -
קשה, שכבר יש תורה בתוך ספר התורה. (אגב, אם אדם דומה לס“ת, קשה למה יכולים לשבת על כסא שבו יושב אדם אחר. אולי הוא מפני שיש לו אותו קדושה בעצמו.) נראה שקורעים כיון שאי אפשר ללמוד ממנו עוד. זה אי אפשר ללמוד ממנו, שמתחילה היה אפשר לו ללמוד ולללמד. ותחשב. כמו“כ, קורעים על מה שיש יכולת ליותר תורה, שנאבד- זה מפני שאי אפשר ללמוד ממנו, וזה מפני שהוא אי אפשר ללמוד. ותחשב.
* כה:
** כי מטו -
איזה מקום אחר בש"ס מצאנו כזה? ב“ק (פ).
* כו.
** לגבי דידיה -
זה מעניין, שלא קורעים על מי שיוצא ממנו לים. אולי שם לא מוכרח ממש.
** לגבי דידיה -
נמצא שלא בא ללמוד עמו כמו עם ת"ח אחרים. ויש לדון, שאולי רצה לומר שלא בא באותו בחינה שהיה יודע ומכיר אותו.
* כו:
** כל שהוא -
יש לדון אם מהני אם רק מרחיב עד שהקרע יותר גדול, אבל לא קורע יותר. ותו"ת.
** רבה… ארבעים -
אם גורסים רבא ביבמות וראש השנה גבי בני עלי, יש לדון אם אף כאן גורסים רבא או סובר ששניהם חיו ארבעים שנים. אם גורסים כאן רבא, מעניין, שרבא היה צריך לדחוק כלפי שמיא כדי לקבל מטר. ויש לדון, שאולי זה רק שלא בעתו, אבל בעתו היה נענה. גם יש לומר שכיון שלבסוף נענה, נמצא שהביא גשמים. דחוק, שעדיין יש חילוק ביניהם.
** בר נתן -
ואם תאמר אם כן למה חכה לו בפעם ראשונה. אולי היה רק ראוי למלוך לאחר שלשים יום אחרי מיתתו, שידונו בו מתחילה. אבל, ע"שה שלא ידונו בו. ותחשב.
* כח:
** ארבע זקנים -
צ’ על’ בפרק אחרון ש לגיטין, לראות איזה מאלו באלו ואיזה מאלו באלו.
** מצווה אחת -
קשה, שהיו ”קרובי,“ שבם ה’ מקדש את עצמו, ומסתבר שעשו הרבה מצוות. ותחשב.
** דבר אחת -
מעניין שלא קורא אותו מצווה, אלא דבר טוב.
** דבר אחת -
ק"ק מגמ’ בסנהדרין שאומר שהיה חצי חוב וחצי זכות.
** חתן -
יש לדון מה קורה אם יש חתן ואבל. אולי אחד יושב בראש זה ואחד בראש אחר (שיש שני ראשים לשולחן). כמו“כ, אולי יושבים בראש בהדדי. אבל, כל זה רק דוחף את השאלה, שאם יש עשה חתנים ועשרה אבלים, יש לדון מה לעשות. ותחשב.
