* ב:
** כפרת מקדש -
מעניין, ששל ראש חודש הוא על דבר קצת חלוק. ותחשב.
* ג:
** קשיא דר"י -
שמעתצי מרש"ש שליטא על ראש הוריות גבי "רבי היא ונסיב… " שלכן אין בעיא שאין הלכה כן, שלא סתמו כיון שסבר שכן הוא ההלכה, אלא מפני סיבה אחרת. קשה, אז, למה אין גמרא מתרץ כן כאן. (וזה יותר קשה כיון שיש שני סתמי, שאז פשוט לומר זה לסיבה למה ננקוט את השני.)
* ד.
** אלא מעיקרא -
לכאורה, הוא אותו דבר של סתם ואחר כך מחלקת. קשה, אז, למה לא אומר שהוא כן. אולי משמע שאינם שווים. צריך ביאור למה לא יהיו שווים.
** לא תימא -
יש לדון- ועיין ברשי- אם דן בביאור רב יוסף או שאומר שאולי אין לומר כמו שאמר.
** סבירא ליה -
הניח כבר שהוא סתם משנה. רק משנה אי סבר כן רבי. לכאורה, רק אי נאמר שסתם משנה הוא שיטת רבי (כמו שהוא שיטת רשי כאן ובביצה) נוכל לומר שאומר שלא נחשב סתם (ושעל זה דן). (דע שלרשי, אז, נמצא שאין שום סתם החולק על רבי, ואפ חולק או חזר (ומניחים שהסתם היה בסוף ימיו) או שהאחר טעה.)
** אלא אמר -
לכאורה, אין צורך לשנות, שיכול להיות עדיין ר"י.
* ה.
** אלא דקתני -
קשה, אז, מהיכי תיתי שקרא לא דן בזה (ומהיכי תיתי שני ידיעות).
* ה:
** דלא כר"ע -
יש להעיר שכבר הוכחנו שמשנתינו אינו כרבי עקיבא.
* ו.
** לומר שמצטרפים -
יש לדון איך מגלה כן. מרשי קצת משמע שהוא שאומר שסידורו חשוב, וצריך להיות כיון שהוא מצטרף ורק כסדר שינוי. יש לדון, אז, למה צריך להביא ראיה עדיין מר"ע למה שרק מצטרפים זה למעשה מזה. אולי רק מביא ראיה למה תולדה של מה. ותחשב.
** ואילו מסיד -
רצה לומר, שהיה לו לומר שיש לשנות שנים אלו, ועל ידי זה נגלה מה יצטרף עם מה. זה יגלה, אז, שיש צירוף, וסדר צירוף.
** ואילו מסיד -
יש לדון למה זה יותר טוב לומר.
** והתניא -
אם כן, אין צריכים הוכחת גמרא לעיל, שרבי עקיבא חולק בפירוש.
* ו:
** לכאורה, גמ’ לא
מסיק עם לימוד שרבי עקיבא יחלוק על משנתינו.
** תרי מלכי -
חזרת גמרא לא משנה מה נעשה, אלא משנה איך נאמר (שיש לומר מלך עם שר שלו). ותחשב.
* ז.
** תנהו ענין -
יש לדון למה לא מקשים שנימא שניתן ענין לתרומה.
* ח.
** נזיר נמי -
עדיין מחודש שמביאו על חטאו.
* ח:
** שאם מת -
קצת קשה למה זה יהא, שהרי חטא, ולא בא לו כפרה, שאם תאמר שבא לו, אקשה לך למה מקריב קרבן כשנודע.
* ט:
** נשבר -
לא אמר שיש נפקא מינא אם אינו לובשו, שלשיטת רבי שמעון (ריש יומא) אין צריכים שילבש אותו.
* י.
** איברא -
שאל לי ש.ל. מהו החילוק בין לשון איברא ללשון לאי (שלכאורה, שניהם בלשון ארמי. יש לדון. ויש לעיין בירושלמי לראות מה אומר). אפשר שלאי נאמר כששואל וזה נאמר כשמכחיש.
* י:
** מאי שנא -
צריך ביאור למה מקשה "אם זה… ," שלכאורה, אין נקודה ראשונה לשו נצרך.
** אותה לא משמע -
יש לציין לגמרא נדרים (עג.). למש"כ הרן, לא יהני לשיטתו שאנו אומרים.
* יא.
** לב בית דין -
אין זה אומר שמתנים אם לקדש או לא, שאם כן קשה למה צריך פדיון. אין לומר שהוא תקנת חז"ל כדי שלא יראה כהקדש היוצא בלא פדיון, שהרי מקשה גמרא שיגרום קדושת הגוף. אם כן, צריך לומר שהוא קדושת דמים ממש. (יש לדחוק ולדחות שרצה לומר שלא יתקנו רבנן כן כיון שלא היה פודהו אי היה מקדיש קדושת דמים.) יש לדון למה בית דין יעשו כן. גם יש לדון איך בית דין יעשו כן, שהניחא אם הוא תנאי, אז יכול לחול ככל תנאי (אם כל תנאי חל בלי ברירה (עיין רש"י גיטין כו. וצריך ביאור)), אבל אם רק מתנים על מה חלות יחול, יוכרח להיות ברירה (דהיינו, שאז לא עושה מניעה לחלותו או כדומה, אלא תולה מה ייעשה על מה ירצה לאחר זמן. ויש לדון, שיכול לעשות כמו שאמר גמרא עירובין ולהתנות, אלא שאותו גמרא צריך ביאור.). ק"ק, שרבי יוחנן סובר שאין ברירה.
עיין ברשי שמשמע (כיון שאומר, “דלא לקדשינהו קדושת הגוף אלא הצריכים… ") שמקדשים איזה שצריכים. אם כן, יש עוד ברירה בו. וצריך ביאור.
אפשר לומר- לקושיא ראשונה- שקדושת הגוף הוא רק הוספה על קדושת דמים (ואז, הוא רק תנאי). (אף אם אינו כן בדרך כלל, אולי יכול לקדשו בקדושת דמים עם קדושת הגוף, שמה לו בו.) ותחשב.
* יא:
** פודה -
צריך למה צריך לזה (ואולי אין צריכים), שיכול להאכילו מחיים, שהתיר ה’ שבע מצוות. יש לדון מתי התירם. (גם יש לדון אם אינו אוכלו לאברים. וצריך לעיין בגמרא חולין.)
* יב:
** זבח -
זה מעניין. שאינו רק שלו. ועיין בערכין גבי שקלי כהנים.
* יג.
** תלמיד -
משמע שהיה תלמידו. אולי רק אומר שהיה בדור שלאחריו.
** הא רבי -
אם כן אין הוכחה מה סבר ר"י. ותחשב.
* יג:
** ומית -
קשה למה לא אומר ש"אי עבר, מכפר… לא כל שכן שלא נחשב עבירה.”
* יד:
** שנים שהם ארבע -
מקשה כמו כן בשבת.
* טו.
** ממין -
יש לדון, שלכאורה, יש מעלה בזה. ועיין.
* טו:
** אחת -
זה שייך, אולי, לענין מה נחשב "חד.”
* יז.
** כשעיור -
יש לדון למה שאל את זה בארוכה וקצרה, ולא בשהה שיעור השתחוויה (שבוודאי שייך אף בזה, כמו שאומר גמרא לקמן). ותחשב.
* יז:
** בעינא -
צריך ביאור, שאי יש לו טעם, יאמרנו, ואי לא, קשה למה רוצה לאומרו. ותחשב.
** אסרה -
העיר ש.ל. שלשון אסור מעניין, שהיה לו לומר לשון טומאה. (ואיסור שייך, לענין לכנס לקודש אחר כן, אבל אינו עיקר הנפקא מינא, אלא רק תוצאה. ותחשב.)
* יח.
** נועץ עשר צפרניו -
עיין בסוטה (לו:) שאומר לשון זה בכעין זה ביוסף.
* יח:
** פתק ביה -
עיין במה שמפרש רש"י. משמע שכתב בו, וזרק לו. כמובן, קשה למה לא רק אמר לו. ואולי היה קרוב עד שיכול לזרוק, אבל לא עד שיכול לזרוע. קשה למה לא, באותו זמן שהיה כותב וזורק, רק הלך לו. ואולי היה קשה לו ללכת. גם קשה איך כתבו. אפשר שאף שמחדש שזה הטעם, כל כך פשוט הוא מן הקרא שכן הוא עד שנכתב תורה שבכתב. נראה שאולי לכן כתבו (לגלות לו כן).
ודע שנראה שהיח יכול לבאר לשון זה (ואולי כן אומר רש"י) על פי גירסת גליון ביבמות (סוף י.). ותחשב.
** אי בשרץ -
יש לדון אם טומאת מטמאים חלוקים חלוק (הוא "מין טומאה" חלוקה) או שהוא רק מין שווה, אלא זה יותר חמור מזה בפרט זה וזה חמור מזה בפרט זה. ותחשב. אפשר שזה המחלקת כאן. ויש לדון.
* יט.
** לכדרבי -
עיין בראש סוטה, שר"ע הוא החולק על ר"י כשאומר כמה דינים על פי חידוש זה של תנא דבי ר"י. מכאן, לכאורה, מוכרח שלא חולק על אותו יסוד. ותו"ת.
* יט:
** מקצת -
לכאורה, רצה לומר שיש לו כל חלקי ידיעה שיאמרו לו שהוא טמא, אבל לא כולם בבת אחת. ויש לדון למה זה חלוק מדין ידיעת בית רבו. ואולי שם יודע את כל החלקים בבת אחת, אבל לא שם לב להבין שאז הוא טמא. ותחשב.
** אבל מגמרא -
לכאורה, הסיבה לחשוב כן הוא או שלא ראינו שחולק (ואולי היה לו למשנה להשמיענו שחולק) או שעל פי זה קל לתרץ משנה ראשונה של המסכתא. ותו"ת.
* כ:
** כלפי לייא -
ק"ק למה לא אמר שכשם שלוקה על שעבר (דכתיב לא ינקה) אף לוקים על הבא (ואף שאין בו מעשה), ואיך יודעים ר"י ור"ל שלא לדרוש כן. ותחשב.
* כא.
** רבי יהודה -
לכאורה, צ"ל שרק אומר שיטת רבו, אבל ליה לא סבירה ליה, שהרי רבי יהודה סובר שלוקה על כל לאו, אף שאין בו מעשה. (ועיין במכות טז. שמשמע שרבי יוחנן (שאומר מימרה זה) סובר שרבי יהודה סבר שאין לוקים על לאו שאין בו מעשה. אם כן, לשיטתו הוא (ואולי זה מקור לשיטתו שם).
* כא:
** כבריה -
יש לדון מהו ענין בריה:
1. הוא דבר חשוב. יש לדון למה הוא חשוב:
  1. אולי חשוב כיון שם בפני עצמו. אם כן, יהיה דומה לצד שני, והחילוק יהיה איך גורם ששיעורו קטן. וצריך לחשוב.
  2. אולי הוא חשוב כיון שהיה יכול לעשות כמה דברים שהיה חי…. ).
  3. אולי חשוב כיון שיש לו שם (בריה) שבדרך כלל הוא חשוב לענין מאכל (ש,למשל, שה שלם הוא מאכל חשוב).
2. יש לו שם בפני עצמו. וצ"ב.
כמו כן כאן, יש לדון אם חשוב הוא כיון שאמרו בפני עצמו (וזה סימן שהוא חשוב לו) או שהוא נתן לו שם בפני עצמו (הוא ה"נשבע"). ותחשב.
* כב:
** תיקו -
שאל לי א.ס. מתי אומר תיקו ומתי לא פושט בעיא. נעניתי לו שאומר תיקו כשאין לו יכולת לדון בו. כן הוא בדרך כלל, שלא מוצאים שידון גמרא ושוב יאמר תיקו. קשה, שכאן היו לנו ראיות מברייתות שנדחו, ויש לנו לדון בו. אפשר שצריך להיות יכולים לדון מסברה. ויש לדון.
* כג.
** גלי אדעתיה -
מעניין מה שאין אומרים שכיון ששתה, גלה אדעתיה שלא השביע לשתות. אפשר שכאן, אין זה רק גילוי, אלא רצה לומר שקרה בתוך כדי דיבור, והוא חזרה. ודחוק.
** צריך ביאור למה אינו
מושבע מהר סיני מחמת דין חצי שיעור (אם הוא מדאורייתא).
* כג:
** ודילמא ממין אלו -
קשה, שאלו ממין אלו (ואין לומר שמדייק למעט אלו ממה שלא אמר "אלו," שיש סיבה אחרת שלא אמר "אלו,” והוא שרצה לרבות מינם).
** באיסור הבא מאיליו -
צריך לחשוב למה זה יהיה. אפשר שכיון שהיה יכול לומר רק אחד מהם , יכס שניהם אינו כל כך חלוק לעשות אגב זה לחול. ויל"ד.
* כד:
** רבא בריה דרבה -
רואים מזה, לכאורה, שאין שם רבא ורבה שווים, שאין נותנים לבן שם אב. יש לדחות שמת רבה קודם שנולד בן זה.
** רבא -
נמצא שבחד דור היו רבא בירה דרבה (כאן), רבא סתם, ורבא בא רב יוסף (?).
** הא אוקמינן -
יש להעיר שלא אוקמינן כן באי בעית אימא זה.
** חמש כגון -
יש להעיר שאז משכחת יותר, שיש לעשות כמה וכמה שבועות, וכל אחד כולל יותר. אולי, אז, יבטל כל המשנה. ותו"ת.
* כו.
** אמר רב אשי -
יש לדון מתי אמרו, שכבר דחהו רבינא. אפשר שחלק על קושיית רבינא (ואולי שייך למה שיש לדון אם "אלא לא שנא" הם מדיבורי רבינא או סתם הגמרא (שלשני, אולי ר"א מודה (א. בדר"כ הלכה כן, ואז אולי מניחים שכל מי שיכול להסכים מסכים. ב. אולי סתם גמרא ר"א.)). ואפשר שאמר שניהם בבת אחת. ותחשב.
* כח.
** ולא היא -
יש לדון מה הוא ההוה אמינא, שאם מכפר בכתפה, לא יהיה מותר להלקותו. אם לא ילקו אותו, אין כתופה בזיון, לכאורה (יש לדחות שהביזיון הוא שהכל רואים שחטא). אם כן, גלגל החוזר הוא. ותחשב.
** רץ -
יש לדון מה בזיון יש בזה- לכאורה, רגיל הוא להיות ירא. ותחשב.
** אמר רבא -
מעניין שזמן התנאי הוא הקובע. ותחשב.
* כח:
** אחוה -
יש לדון אח מי (רבה או עיפא).
שוב ראיתי שהוא אח של עיפה. ועיין בפ"ק דסנהדרין ורשי מנחות (יז.). ותו"ת.
* כט.
** גמל -
כיון שכבר יש מה שנקרא גמל פורח (עיין רש"י מכות), מוזר מה שיתן לו אותו שם. ויש לדון. גם יש לדון אם היו כולי עלמא קוראים דבר מרוצה כן. ויל"ד.
** גמלא פרחא -
יש לציים למה שהיה airplane הנקרא Sopwith Camel. אז, לכאורה, הוא דבר רגיל לחשוב על גמל פורח. ותחשב.
* ל.
** בתובע ונתבע -
יש לדון מה אומר. אולי אומר שדנים בסתם תובע ונתבע. לא נראה, שנאמר כן אף בעדים (ולא נמעט נשים. ויש לדון, שדרשות חלוקות הם, ואולי זה יותר משמע.). יש לומר ששאני שם שאפשר לדרוש ממנו להיות דווקא (אבל כאן לא מסתבר לדרוש כן). גם יש לומר שאומר שנקראו שנים כיון שיש שני כללים (תובע ונתבע).
* ל:
** אפרח -
יש לדון אם רצה לומר שזרקו או שעשה שיפריח לו.
** דיתיב כמאן -
לא הבנתי את זה כל כך, שכבר עמד, לכאורה. ותחשב.
* לא.
** פוזמייכו -
עיין בשבת (י.) ששם גם כן רבה בר"ה החשיב פוזמקאות.
** אבל משחק -
עיין בביאור רש"י. דע שדנים מתי אומרים זה (שכיון שמחמת ספק או מדרבנן אינו אפשר, נקרא אינו אפשר). יש גמרות הסותרות זה את זה. אפשר שמחלקת הוא (כאן), ויש גמרות כזה ויש כחולק.
* לא:
** לימא -
קשה, שבין כך ובין כך תנינא משנה שאומר נדרי אונסים. צריך לומר שלא מפרש מהו.
** שיכול -
משמע שאין הודאה חוץ מבית דין נחשב הודאה. חושב אני שיש דיון בזה. יש לדחות שכאן לא היו עדים.
* לב.
** עד דאמרי -
יש לדון בזה, שהענין אינו מה נחשב בלומדות לחד זמן, אלא אם מוכרח שלא להיאמן. ונראה שהענין הוא שעד זה יכול לחזור בו. ועיין לקמן, שחושב אני שעל פי זה, יש קושיות (למשל, קו”ח דגמרא בע”ב). ותחשב.
** ממון -
אם כן, יש מי שסובר שאין קידושין צריך אלא עד אחד (עיין בקידושין, שלומדו מממון). על פי זה, היה אפשר לתרץ כמה ברייתות שמק’ בקידושין.
* לג.
** כיון דאילו -
תחשב על זה.
** ממון -
יש שמדייקים מזה (ומראשונים האומרים בפירוש שחלק מהלכה למשה מסיני הוא שהוא ממון) שאין הלכה למשה מסיני רק פוטר חצי נזק, שאם כן פשוט הוא שהוא ממון, אלא מחדש חיוב על חמי (או שעושה שניהם, או שנדע ראשון מסברה). נראה שיש לדחות או שלא היה ידוע מה עושה, ואז היה צורך לומר נקודה זה או שלא היה ידוע שהוא הלכה למשה מסיני (עיין ירושלמי פאה (יג.)), ואז צריך לומר זה בהלכה למשה.
* לד.
** או דביטוי -
יש להעיר ששם חלוק, ש"או" ראשון קאי על שניהם. ועיין שם.
** הכישו -
יש לדעיין אם זה מיתה הראוייה למי שהמית (חושב אני שאחר הקשה כן).
* לה.
** תניא נמי -
יש לדון מהו הראייה מזה. נראה שהוא שלא אמר ציור של עומד עליהן לציור שבו חייב.
* לה:
** חוץ מזה -
מעניין שאומר שיטה זה קודם- וכל הקורא גמרא יקרא את השם בשם- אף שהלכה הוא שאסור לעשות כן, שלהלכה הוא (על כל פנים לחד שיטה, אבל כן פוסקים) קדש. אולי יכול לומר שם ה’ כיון שקורא גמרא שמביא אותו קרא, ולומדו. ותחשב.
* לו.
** אבל באיסורא -
עיין במה שפירש רמבן (ב"ב קכו:) בדיני תנאי. אם כן, גמרא זה צריך ביאור (למה יהיה כן כשאומר כן קרא או כשאומר תורה כן), שלכאורה, אין אלול רק משחקים. ויל"ד.
** אית ביה -
צריך לחשוב מה לנו בזה. ותחשב על כל זה.
* לז:
** תיובתא -
אם כן, נמצא שסתם גמרא לעיל הקשה שלא אליבא דהלכתא (כשהקשה על שני כיתי עדים). נראה שזה סמך לר"ן (נדרים מה:).
** אלא מהא -
ואם תאמר מה מוציא מדיוק שני (שכיון שנתרבה, אינו קשה למה לא שנאו, שהרי שנאו). ונראה שעדיין קשה למה רבה אותו על ידי כלל, ולא אמרו בפירוש. ויש לדון איך מתרצים כן בכל זמן שמרבה דבר על ידי כלל. ותחשב.
* לח:
** לא שבק -
לא הבנתי למה לא יחשב על שניהם.
** שהוא כמשיב -
יש להעיר שלכאורה, אם אינו כן, יחייב קרבן, שאין סברה שלא יעז. אם כן, אולי הוא מערים. ותחשב.
* לט.
** כולהו -
יש לציין לגמרא חגיגה עם ר"ג. ותו"ת.
** שכן מצינו -
אם זה מפני שלא יפירו, לשון "שכן מצינו" קשה, שכאן אין הפרה. אפשר שרק מביא לראיה שיכול לעשות כן (להשביע אחר על דעתו). ותחשב.
* לט:
** שיש בידם -
רצה לומר, שהיה להם לחשוב שהיה בידם (עיין שבת פרק חמישי).
* מא:
** אנא -
רואים, אז, סברת מד"א המלוה… בעדים. גם רואים שיש צד שאף בלי זה יש לומר כן (מסברה, אלא שאז יש קושיא זה).
* מב:
** סבר עד דהוי -
הקשה לי ש.ל. למה, אז, צריכים לכופו, שרוצה לשלם לאחר זמן. אפשר שרוצים שישלם מיד.
* מג.
** אדמיפלגי -
היה אפשר לומר שנקט רבותא ברבנן. זה היתר לנשבע, שהוא הנתבע. אז, זה קשה לראשון (שכחתי מי, וחושב אני שהוא רמ"ה בב"ב קלב.) שאומר שקולא הבאנר גבי ממון הוא לטובת נתבע, אם גם נניח כרשבם בפסחים האומר (עיין שיח שי) שאין "כח היתירא עדיף" כמו שאמר רש"י בביצה, מפני שיותר קשה להתיר (שהרי כאן יותר קשה לגרום שבועה). ותו"ת.
** שמא נשבע -
לא הבנתי מהו הבעיה בזה. אולי רצה לומר שאם יכול לגרום שלא יהיה שבועה שאפשר להיות שקר, נעשה כן. ולא משמע כן.
* מה.
** שניהם רוצים -
לכאורה, זה שווה ל"טריחא ליה מילתא,” והוא שלשניהם יש בזה טורח. ק"ק למה משנה לשונו. אולי טורח משמע מין הנאה מיוחדת (שאינו צריך כל כך מעשה או שהוי). ותחשב.
* מה:
** כמה מעליא -
במקום אחר מקשה גמרא שאין לומר כן. ק"ק למה לא מקשה אותו כאן.
* מו:
** שאין -
יש כמה פקטורים כאן, וצריך לפרש מה הדין עם כל הצירופים שייך. ותחשב. ועיין ברש"י כאן.
** שבועת ביטוי -
ממה שלומד ממה שנשנע על זה שקל אחר בעיניו, משמע שיש איסור שווה להם. היה אפשר לומר ששבועת ביטוי עושה מעשה רע, אבל שאר שבועות הם בעיקר רק שקר. גמרא לא משמע כן, אז. ותחשב.
* מז:
** אמר ליה -
מעניין שרבי שואל לר"ח. דנים ראשונים בזה.
** אמר רבי -
צריך ביאור, כמובן, איך רבי לא ידע משנה. ותו"ת. יש לומר שרק כתבו אחר כן. אם כן, בוודאי קבלו ממנו. יש לומר שחלק על דין משנה (שכן מוצאים כמה זמנים).
** יד בעל השטר -
לא הבנתי למה מודים בזה, ולמה אינו שווה לשני מלוים ולווים (ששם מוציא מחמת ספק). וצריך לחשוב על כל ציורים אלו.
* מח.
** יפה כוח -
זה המקור לזה בכל מקום.
