* ב.
** תולה -
מרשי (והוא, באמת, מוכיחו מגמרא) רואים שנענש קודם ידיעה.
* ב:
** אמר להו -
נראה ממשנה שרק דנים בשל חוץ. נראה שהוא מפני שהוא ששל פנים יש לו כמה דינים חלוקים (נכנס בפנים, צריך הגרלה) עד שמסתבר שאין זה כשר לזה.
** על הראש -
מעניין, שפאה רק רצה לומר סוף, ואזף היה אפשר להיות כל סוף הראש, ומהיכי תיתי שהוא בלחי. ואולי הל"מ הוא.
* ג.
** דזוטרן מילייהו -
לשונו קצת מעניין. יש לדון אי קאי על מילייהו, ומפרש שמילייהו רצה לומר שני פרקים אלו או או שאומר שלא ק קצר מפני שהוא רק שני פרקים, אלא אף מפני ששני פרקים אלו קטנים.
* ג:
** אחר לא תעשה -
עיין בלשונו בביאורו למה פטור. עיין במקום אחר שדנינו בזה.
** לא מן -
נראה שבא לבאר שיותר טוב לומר סברה זה כיון שעושה שאין סיבה למלקות, ולא רק שיש מניעה (או שסיבה מתקיימת בדבר אחר). ותחשב.
* ד.
** ומשנה -
עיין במה שפירש. יש להוסיף שלולי אותו משנה, לא היה שייך לכאן, והיה כל צורות המסכתות משנים.
* ה:
** שנים-
יש לדון למה לא אמר זה על המשנה. וצריך ביאור .
* ו:
** הי -
העיר ש.ל. שמרשי זה יוצא ש"שבור" הוא שם שמשתמשים בו בפני עצמו, ואף בלי "מלכא."
* ט.
** הביאו -
מעניין שעל "כפרה" פירש רשי שמפיס דעת. ותחשב.
* ט:
** שעיר -
כל המלמד- עיין שם, שלא נראה שהוא כן, שנראה שיש עוד שאין דנים, כמו היקש עם גזרה שווה. ותחשב.
* יא:
** דלא שכיחא -
לרשי, קאי על הקרבן שבו מתנים. לולי רש"י, היה נראה לומר שקאי על הפסול. כן, לכאורה, נראה, שעל זה מתנה- על הפר, יודע שבא, ואז פשוט שחש. אולי אין בית דין של אותו זמן המתנים, אלא של לפני כן, ואז לא יודעים שיבא פרה.
* יג.
** מגלה -
בוזה- לשון זה מעניין, שבדרך כלל אומרים מבזה.
* טו.
** שהן -
הק’ ש.ל. למה שינוהו. יש לדון, ואולי אינו בעיה.
* טז.
** תחתונה -
משמע מזה שענין ווידוי מעשר הוא כדי שיפריש ביותר טוב. שמעתי כמו כן מר.ד.ו.
* יח.
** פרישה -
רצה לומר שאין להקשות כן על התנא ששנהו ראשון, שאולי לא שנה משנה אחר שמשמיע דין זה. רק קשה הוא על רבי, שהוא שנה שני המשניות.
* יט.
** פרט -
נמצא שרש"י סובר שמי שטעה מהו חפץ (יודע שרוצה לעשות דבר לחפץ זה, אבל אינו יודע מה זה) אינו מתעסק. תוס’, חושב אני, חולק על זה. ודע שאולי זה שייך לדיון רב יוסף ומחכו עליה אם נחשב העלמת שבועה. ותחשב.
** כלום פירש -
לולי רש"י, היה אפשר לומר שהענין הוא שלא פירש אלא מחמת ידיעת שניהם, שידיעת רק אחד לא ישנה את מעשיו. רש"י לא משמע כן, אלא משמע שהענין הוא שרק הבין בשני מחמת הבנת ראשון. אז, לכאורה, אם לק קרה כן (ואם אין ל"פ), הדין כר"א. ותחשב.
* כו:
** תרומה -
יש לדון למה אין אומרים שקרא של דברי נביאים (שאינו יכול להיות המקור, אלא רק מגלה שיש שום מקור) מוכיח לימוד מאותו קרא של תורה, ואז אינו שני כתובים הבאים כאחד. אפשר שאם כן, לא היה לו לכתוב קרא בנביא (ורק עושים כן, אולי, אם אינו מקור כל כך פשוט. ויש לדון.)
* ל.
** מצוה -
לכאורה, רצה לומר שאין מקרא יוצא מידי פשוטו. ויל"ד.
* ל:
** דביתהו -
צריך ביאור מהיכי תיתי. אולי אם לא כן, היה ר"ה בא.
* לב:
** ומח’ -
שמא היו מודים- לכאורה, היה אפשר לומר ששמא היו מתות מחמת המים. ותחשב.
* לג.
** אי -
בציר- משמע שאינו ממש גורם לממון. ויש לדון, שכשפוסקים, הוא ממון, ואז הוה גורם לממון.
* לד.
** מאי בינייהו -
מניח שכשאומר שסומך עליו, רצה לומר שמחלק במה שאומר. לא נראה כן, שאז דבריו לא שייך לברייתא זה, שהוא מקורו לאותו דין (ויש לדון). ואולי רצה לומר שמסכים שיש לדרוש כן, אבל אינו כל כך ברור לדרוש כן, עד שצריך מקור אחר עמו. ויש לדון. אם כן, שאלת גמרא כאן אינו מניח שמוכרח שיש חילוק (והיה אפשר לומר שמשמעות דורשין).
* לו:
** ושאני -
היה אפשר לדחות שרק מקשה לר"מ ששנה סתם משנה.
** אלא -
הא פרישנא- אין צריך לזה, שמפרשים אותו לאחר כן (על זה, אני חושב). ותו"ת.
* מ.
** דינר -
לולי זה, היה אפשר לומר שלא רק דנים מה כוונת משנה כשאומרו סתם, אלא מה כוונת האומרו. אם כן, יש להביא ראיה באופן דיירק"ט. ותו"ת.
** איכא -
נמצא שמותר לשתותו מים בבית מדרש (ולולי רש"י, היה אפשר לומר שלא אמר לו ר"י את זה בבית מדרש).
* מ:
** הכא עיקר -
כולא מסכתא- אין שני פרקים ראשונים בדיני שבועות.
* מא:
** כיון -
זה מעניין, שהרי אמרם בפירוש לפני זמן. צריך לומר שכיון שעשה מעשה נגדם, צריך עוד דיבור. מעניין שזה אותו בעיה של דברים שבלב. ותחשב.
* מב.
** אין נתינת -
עיין במה שמפרש שדורישים מ"איש.” כן נראה, לכאורה, מסברה, אבל לשון גמרא לא משמע כן, שבדרך כלל כשאומר דרשה כזה, אומר "איש, ולא …,” אבל כאן לא אומרו. משמע שדורש מלשון נתינה או כעין זה. וצריך ביאור.
* מג.
** אלא בדרבה -
עיין במה שמפרש למה נקרא טענת עצמו. נראה שגם היה יכול לומר שנקרא טענת עצמו כיון שהוא הגורם שיאמרנו, ולא אחר, שאינו נצרך (כיון שאין העזת פנים בו). לא נראה, שזה גופא המחלקת. ויש לדון.
* מז.
** משחק בקוביא -
עיין שם בסנהדרין, שמחלקת הוא. ק"ק למה לא נקט הטעם שבוודאייש תנא אחד הסובר. ותו"ת.
* מט:
** אי הכי -
עיין בב"מ, שחושב אני שדנים בזה. ותחשב.
