** ג. כינויים דאורייתא -
לכאורה, שניהם מדאורייתא, שידות נלמדים מדרשה. אז, נמצא שמשתמשים בלשון “דאורייתא” אף לומר “יותר מפורש בתורה.” כמו כן מצאנו בכ”מ שאומרים “דאורייתא” לומר שדבר אינו הלכה למשה מסיני, אף ששניהם ניתנו מרועה אחד, ושניהם הם חיובים דאורייתא. ותחשב.
** ואי בעית אימא -
ק"ק למה נותן עוד תירוץ, שעדיין יש קושיות שמוכיחים שאינו דווקא. אם כן, מוכרח שתירוץ ראשון נכון. ויש לומר שיותר רוצים לומר שאין דבר נגד הכלל. לפעמים, נמצא שתנא לא חש לכלל שלו, אבל רוצים למעט אותם פעמים. זה אומר שתנא היה חש לכלל שלו בדרך כלל, אלא שיש יוצאים מן הכלל (היה מאד עצל אותו היום), אבל לא נניח שכן קרה הרבה פעמים. ותחשב.
** לאו דווקא -
משמע שהוא שתנא לא חש. כן נראה מר”ן גם כן, שאומר שתנא משמיע כן. לולי כן, היה אפשר לומר שתנא אינו דווקא כיון שיש יותר מתנא אחד, שרבי ליקט מברייתות חלוקות, ויש תנא שרוצה להקדים מה שהוא ראשון ויש שרוצה להקדים מה שהוא אחרון. ותחשב. אולי כן הוא, ו”לאו דווקא,” וכן מה שאומר ר”ן, הוא שרבי לא חש לתקן אותם להיות בשיטה אחת. ותחשב.
** מפתח פתח בכינויים -
קצת צריך ביאור למה מה שהוא מדאורייתא הוא סיבה להקדים לענין נושאים, ומה שהוא דרשה הוא סיבה להקדים לענין פרטים. עיין בר”ן, שנראה שבא לבאר זה בד”ה כי פתח.
** אף נזירות -
יש לציין לקובץ הערות שבאר שמה שיכול אב להפר הוא שכל נדר של אשה הוא עד שאישה מבטל אותו (כך מבאר “על דעת בעלה,” ולכן לא קשה למה לא בטל למפרע). לזה, היה אפשר לפרש בגמרא זה, אבל רש"י לא מפרש כן כאן, ואין ר”ן מפרש כן, שאומר שכיון שהוא לשלושים יום, לכאורה, אי אפשר להזיר כך.
** בל יחל -
אין כל דינים אלו כל כך פשוטים לי. ר”ן כ’ בפירוש שעובר על בל יאחר בנדר של קרבן, ועובר על בל יחל בנדר של איסור. יש לדון אם הוא אף להיפך. (בדרך כלל, לא נמצא לא תאחר על נדר של איסור, אבל נמצא אם הוא נודר לעשות דבר, שאומר שדבר זה עליו לעשות. ויש לדון אם יכול לעשות כן.) שניהם נלמדים מחד קרא של נדר, ואז צריך לדון באיזה הוא, אם הוא של איסור או של קרבן. אז, יותר משמע ששנים אלו הם באותו חד דין שממנו לומדים. ותחשב.
** הקישא למה לי -
לכאוהר, לא מקשה למה כתבה תורה את ההיקש, שהרי צריך לשאר דינים. אלא, מקשה למה אמרה ברייתא. אין זה כל כך קשה, שמצאנו מקומות שיאמר גמרא על כעין זה שתנא ר"ל שאילו לא היה לנו קרא זה, היינו דורשים אותו מזה.
** ג: דילמא השתא מיית -
צריך ביאור מה אומר גמרא זה. לכאורה, הענין כאן הוא שלא חל נזירות מיד כיון שלא אמר שהוא נזיר, אלא אמר שיעשה את עצמו נזיר באופן שבוודאי יקיים מקצת נזירות. אם כן, לכאורה, לא צריך להוקים אותו בציור כזה, אלא יש לו להוקים אותו בציור שנשבע להזיר היום. כמו כן, יש לדון למה נחשב בל תאחר כאן, ולמה לא אומרים שעובר על שבועה. גם צריך ביאור למה הוא דין נזיר, ולא דין שבועה.
** ד. הוי נזיר לכל -
צריך ביאור מהו ההוה אמינא ששייך קלות לידור בנזיר לדין בל תאחר של קרבנו.
** ד: דלא אית ליה -
עיין לעלי במה שבארנו בזה.
** שאם גילח -
במילים אחרים, החידוש הוא שתוצאה של אותו הקרבן נעשה על ידי קרבן אחר. מעניין, שתוצאה של הקרבן יותר גדול משל אחרים. אז, למשל, עולה, לא רק נעשה היתר שעושה על ידי אחר, אלא לא עושה היתר כלל. (ואין לומר ששאני כאן שכל מה שעושה נעשה על ידי אחר, שאין זה נודע. באמת, נראה שלא נעשה, שחייב להביא כל שלשתם.)
** ה: לימא קסבר שמואל -
רק רואים שסובר שמשנה סובר כן. לכאורה, מניחים שסובר כאותו משנה. ואם תאמר למה; הרי יש תנא שחולק עליו. ויש לומר שסובר שהלכה כסתם משנה. ויש לדון, שיש מחלקת בו במשנה בגיטין. גם אפשר לומר שהחולק הוא ברייתא שממנו הקשה גמרא לעיל.[fn:1]
** לימא -
רבא היה לו לומר שהוקים משנה כזה כיון שסובר שאין תנא חולק, שהרי כן סובר רבי יהודה בהכרח, ולא מצאנו תנא אחר שחולק, שאין הוכחה שרבנן חולקים על רבי יהודה, שאולי גיטין חלוק. אולי בא לפרש שאין להביא ראיה משיטת שמואל לשיטתו, אלא אף יכולים לבאר לפי אביי.[fn:2] שוב הבנתי שמוכרח שיש תנא שחולק, כמו שמבאר גמרא לעיל. נראה שאולי אין זה די, שעדיין כיון שאן אותו תנא אף נזכר במשנה, לא נניח שמשנה כמותו. רק מקשה גמרא, לכאורה, כיון שאותו תנא הוא רבנן. ותחשב.
** לך -
יש לדון איך ידחה אביי את זה.
** ו: יש יד -
יש להעיר שיוצא מגמרא זה שיש ארבע סוגים:
1. יש מה שאינו יד. זהו דבר שמשמע ממש מה שאומר.
2. יש יד מוכיח. זה דבר שאינו ממש משמע מה שאמר, שלא גמר דיבור שלו, אבל הוא משמע.
3. יד שאינו מוכיח. זה דבר שאינו משמע כל כך.
4. יש שאינו אף יד. זה דבר שאינו משמע.
יש לדון אם מה שכתבנו ב2, שהוא דבר שלא משמע כל כך כ1, נכון, שאפשר לומר שאינו כן, אלא הוא רק דבר שלא גמר דיבור שלו. נראה שמגמרא זה רואים כמה שכתבנו מתחילה, ולא כדיחוי זה, שהרי גמרא מנסה לומר צדדים לדחות מילת, “ואת.” אילו היה החילוק בין 2 ל1 רק אם גמר דיבור שלו, הרי כאן בוודאי לא גמר. אם כן, כבר יש סיבה לחשוב שהוא יד.[fn:3]
** יש יד -
דיון זה אינו, באמת, אם יש דין יד או לא, שנראה יותר שדן אם יש ציור של יד או לא, שאולי ציור שהיינו חושבים שהוא יד הוא משמע די. אם כן, הוא שאלה חלוקה מבפאה. ותחשב. (שוב נראה לי שאין זה מוכרח; עיין לקמן בד”ה הדין נפקותא. אם כן, צריך ביאור מהיכי תיתי שיש לו יד. ותחשב.)
** הדין לנפקותא -
לשון זה משמע שאין גמרא שואל אם לומדים מקרבנות או לא. עיין בר”ן שכ’ ששואל כן, וצריך ביאור ל"ל ישאל כן (וכן, באמת, מבאר גמרא שאלתו לקמן). אז, נראה שצריך לומר (וזה ישנה ההוכחות שכתבנו לעיל) איך, למעשה, מפרשים מה שאומר- אם אומרים שיש יד, וממילא דיבורו הוא מפורש כך (ר"ל, נוהגים בו כן) או אין יד ואז דיבורו לא מפורש כך. ותחשב.
** ז. היינו צדקה -
יש לדון, שהרי לא הוקש. אולי כיון שיהיה אותו טוב של צדקה (שיקחו עניים), מסתבר לגמרא ששוים. ותחשב.
** חדא מגו חדא -
היה אפשר לומר ששואל להיפך, ששאל אם זה נחשב זימון ומהו הדין אם נחשב זימון. נראה שלא מסתבר כן, כיון שצד של “נחשב זימון” כבר אומר שיש דין שתלוי בו, ואז, לכאורה, היה צריך לדון אם יש, באמת, דין שתלוי בו.
** הא קמ”ל -
קשה, שאף בלי זה, היה לו לומר שכיון שיכול ללמוד דבר אחר, לא מצווה בזה.
** ז: לישנא דנדוייא -
צריך ביאור איך גמרא מצדד ש”מנודה” אינו לשון נדוי אלא לשון שמתא, שהרי ממש אומר נידוי. נראה שאולי הוא מפני שנידוי ושמתא הם כמעט שווים, שנידוי הוא רק דרגא יותר מעולה של שמתא. אז, אינו קשה לקרוא לאחד בשם של חבירו. ותחשב.
** ח: כך אי אפשר -
לכאורה, ק"ק ל"ל אומרים שהוא ספק ספיקא, שאולי הנידוי לא היה נכון, ואף אם היה נכון, אולי ההיתר נכון. אולי אין צד שני צד, שהרי צריך להיות בו בר. גם יש לומר שאם הנידוי לא נכון, אין ההיתר נכון. אז, צריך לומר שהנדוי נכון. אם כן, אם ראה אף דבר אחר בחלומו, מותר.
** ופליגא דר”ש בן לקיש -
יש לדון מהו המחלקת. אולי הוא שריש לקיש משמע שהוא רק לעתיד לבוא, ואביי משמע שהוא אף היום. גם יש לומר שאביי משמע שבא למעט לילה, וריש לקיש דורש דבר אחר מיום. ויש לדון, שפשוט שאינו בלילה, שאין חמה אז. ויש לומר שר”ל בין שקיעה לצאת הכוכבים וכדומה. ותחשב.
שוב נראה לי שאולי חולקים למי מוציא ה’ חמה. ותחשב.
** ט. כנדרי רשעים לא -
מחודש שהיינו יכולים לפרש כן, שה”לא” הוא, לכאורה, חלק גדול מדיבור שלו.
** כנדרי רשעים -
צריך ביאור ל"ל אומרים שאף נדר בנדר, ואסר על עצמו לאכול אותו ככר (שהרי לשונו משמע ביותר נדר).
** י. לפי שאין -
יש להעיר שתוס’ אומר שכלל של “בהמתם של צדיקים...” הוא רק בעניני אכילה. גמרא זה משמע שאין ה’ מביא שום תקלה על ידם. ותחשב.
** לפי -
לכאורה, ר"ל שהיו מתאווים כיון שלא היו מקריבים. היה אפשר לקרוא (אבל אינו כל כך טוב) שהיו מתאווים. לפי שלא הביא ה’ תקלה, הוצרכו לעשות זה.
** לפי שאין -
מעניין שיוצאים תאוותם בזה, שהוא חטאת חלוקה. ותחשב.
** מתנדב ומביא תודה -
נמצא שיכול אדם להתנדב תודה.
** יא. תרי תנאי -
היה אפשר לומר שהוא תרי תנאי אליבא דרבי מאיר.
** יב. והא נותר ופיגול -
יש להעיר שכאן הפוך הוא, שאסור עכשיו, והיה מותר לפני כן. ותחשב. אפשר שדן אם מתפיס אדם בהיתר או ביאסור (כן משמע קצת גבי היה נדור ובא מאותו היום, שהרי שם אין זה יום ראשון הראשון). ויש מקומות שלא נראים כן. ותחשב.
** והא נותר -
היה אפשר לומר שכאן לא נתן חתיכה, אלא אמר שהוא כמותו. ותחשב. אולי אז אין חידוש. יש לדון.
** יב: הא קא משמע לן -
עיין בהגהות וציונים שכתבו שלא לגרוס “הא קא משמע לן” כיון שלא משמיע לנו. ונראה שהדרך לקרוא אותו הוא כך: “הא גופא קא משמע לן, [שהרי] קורא לתרומת לחמו תרומה.” ותו”ת.
** יג: הא קרבן -
משמע שה"ה דומה לחי"ת. זה טוב לפי הדרך שהספרדים מבטאים.
** טו. רבינא -
צריך ביאור מה מהני רבינא (כמו שהערנו על הר"ן ביד:). גם צריך ביאור לרבינא מהו החידוש כיון שכבר אמר המשנה שבסוף פרק ראשון דין זה.
** מי איכא בל יחל -
צריך לבאר מוה השאלה, וצריך לבאר מהו התשובה.
מהו השאלה: מה שצריך ביאור הוא שלכאורה אומר שיש דין דרבנן שבא מלא יחל. קשה למה אי אפשר להיות כן, ולמה צריך ראיה. אם הסיבה שלא יכול להיות כן הוא רק שאין כל כך סיבה לאסור זה, אז קשה מה מביא מאותו ברייתא.
אז, נראה שדן אם נקרא שם לא יחל על איסור כזה. כמו כן, יש לומר שדן אם לוקים על איסור כזה (כ"כ ראשונים).
מהו התשובה, אז, הוא מובן, שכאן רואים דין שהוא מדרבנן (לכאורה, צריך לומר שגמרא יודע שהוא מדרבנן ממה שאין דרך לדרוש אותו מן הקרא. כמו כן, יש לומר שיודעים סברה שלו, ממקום שנוהג, ואינו סברה שרגיל תורה לומר, אלא נראה כסברה דרבנן.), ואף על פי כן אמרה תורה עליו לאו דלא יחל. כמו כן, יש לומר שמה שאומר עליו לאו של לא יחל אומר לנו שלוקה, כמו שהיה גמרא מדיייק ממשנה שלנו כן (שאי לאו הכי, למה לו לשאול איך יש לו מלקות).
** טז: מאי שנא -
היה אפשר לומר שאין הכי נמי, אין איסור בל יחל, אלא יש איסור חפתא של נדרים (ר"ן כ' בפירוש שיש שני איסורים, אחד שהוא איסור גברא, ואחד שהוא איסור חפצא). ותחשב.
באמת, לפי הר"ן צריך לפרש מהו תירוץ של גמרא. אפשר שואמר כמו שאמרנו שיאמר, אבל אם כן, לא שייך לשון שאומר, אלא מה שאינו אומר "דברו" באותו איסור. אז, נראה שאומר שכיון שרק אסר ישיבת סוכה עליו, אינו כל כך נגד המצווה. וקצת קשה, שרק אסר כן באיסרו חפץ, אבל איסור גברא מוכרח להיות איסור עליו לשבת בסוכה. אולי עדיין כיון שאל אמר אותו במילים אלו, חל. יותר נראה לומר שאיסור לאו הוא לשמוע לדברו, ולא שלא לשבת בסוכה. אז, אינו נגד חיוב סוכה כל כך. ותחשב.
** אסיפא דאידך -
אם כן, היה לו להביא את זה לראיה לרבינא (וצריך ביאור מה ידחה צד אחר בגמרא). וצריך לומר שלא היה מי שאמר צד אחר, אלא גמרא דן מהו נכון, וחשב שזה נכון, ושואב אמר רבינא פשט אחר, ונמצא שהוא נכון.
** מצוות לאו ליהנות -
נראה שעדיין יהיה אסור, שהרי לא יכול להנות, ואיך ישב שם בלי הנאה, אבל מקשה שאז חל השבועה. וקשה, שאם כן, בין כך ובין כך יחול השבועה,ש אף שלא חל על הנאה של קיום, יחול על הנאה של צל, ויאסר ישיבת סוכה. אז, צריך לומר שקושיית גמרא הוא שאין הנאה חוץ מקיום המצווה, ואז לא יהיה חל. ויש לדחות, אולי, שכיון שיש הנאה יותר ויותר גדול, שמקיים מצווה, מניחים שכך הוא ההנאה שלו כיוון. ויש לדון ל"ל נניח שכיוון לשניהם.
** יז. נדר בתוך -
לא הבנתי סוגיית נזירות בתוך נזירות כל כך. לכאורה, אם נדר בנזיר, ושוב נדר עוד בנזיר לאותם ימים, הדין הוא (מחלקת הוא, אבל לרב הונא) שרק חל אחד. אז, נמצא שאין השני יכול לחול כיון שכבר יש אחד. אבל, אם מוסיף יום, אז חל. מדין שאומר גבי שאלה, לכאורה, מוצאים שלא יכול לחול לאותם ימים, אלא חל מיום שלושים. צריך לבאר מה עושה שזה לא יחול, ולמה לא עושה שזה לא יחול, שהרי שניהם לא יכולים לחול כמו שאמר. ותחשב.
גם צריך לבאר למה חל שניהם אם אמר אותם בבת אחת. לא פשוט, אז, מה יקרה, אבל רב שמעון שקאף אמר שאז יהיה ספק איזה חל, אבל רק אחד יחול. ויש לומר שאולי כאן חלוק, שאחד יכול לחול לאחר זמן, ואין בשניהם סתירה. קשה, אז, ל"ל חל אחר אחר שכבר נזר. וצריך לחשוב על כל זה.
** יש נדר -
גמרא משמע שעיקר החילוק הוא שכאן הוא רק תנאי, אבל התנאי לא שייך לכאן (וצריך ביאור למה הובא), אלא עיקר הענין הוא שיכול שני נזירויות לחול, אבל לא יכול שני שבועות לחול כך. משנה נוקט ציור מיוחד שבו שני נזירויות יחול, והוא אם התנה.
** יח. אלא משום דכ' -
צריך ביאור למה לא אומרים שמה שחל לפעמים על מה שלא חל שבועה הוא פירכא. וצריך לפרש מה נחשב פירכא ומה נחשב מן הדין (שהם שני דינים חלוקים, וכמו שלא פורכים שאין על נדר לאו של שבועה, לא נפרוך זה). אולי הסיבה שאין שני חומרות שמנה ראשון נחשבים חומרות הוא שנחשבים מעיקרי המצוות. ותחשב על זה.
** כ. ד דברים -
גמרא מפרש לקמן שאינו ר"ל מלאכי השרת, אלא רבנן. אם כן, ק"ק למה אומר שהוא רק ד' דברים, שמסתמא אמרו לו יותר דברים. אולי ר"ל שאמרו ארבע דברים בענין זה.
** שהופכים -
לכאור, ר"ל שהנולד כן בו ממי שהופך. היה אפשר לומר שאם אדם הופך, לפעמים נתגלגל לחגר.
** כ: יפיפים -
מצאנו לשון כזה בתהילים (“יפיפיתה”).
** באשה אחרת -
ואם תאמר מה ממזרות יש בזה. ויש לומר שדומה לממזרות, שחושב על אשה אחרת. אף זה מחודש, שלא דומה לממזרות, שהרי איש יכול לבעול איזה נשים שירצה. אולי חשש שיחשוב על אשה שאסורה לו. גם יש לומר שחוששים שמא יזנה. אפ יזנה הוא, תזנה היא (כמו שאומר גמרא בסוטה). אם כן, יהיו הבנים ממזרים. (לזה, טוב למה אומר “בניו,” שלא רק אומר לשון סגי נהור על עצמו, אלא אומר ממש בנים של אחר. מעניין שרק חושש לממזרות, ולא לאיסור אשת איש ולאיסור אשתו עליו. מצאנו בכ"מ כעין זה, כמו בפרק השולח בגיטין, שנראה שיותר חוששים לממזרות מלאיסור אשת איש. ותחשב. גם יש לומר שמחמת זה, מחשבה לבעול אחרת נחשבת כעין ממזרות. דחוק.
** הא אינהו בקיאי -
צריך ביאור מתי אומרים לא בשמים היא. אולי כאן לא נוגע כיון שאין נפקא מינא, שאין איסור והיתר, והוא רק עצה טובה. ותחשב.
** כא: צדיקים אומרים מעט -
וזה משיב למה שאומר לו בעל הבית. אבל, נמצא, אז, שזה אומר הרבה (שאף לא יאכל קימעא), אבל לא עושה כל כך. ותו"ת.
** אין חילוק בין חרטה לפתח אחר כל כך
פשוט לי. אולי ענין של חרטה הוא שרק עכשיו לא רוצה, אבל עדיין רוצה בין הכל. לא נראה כן מלשונו, וכן מן הגמרא ור”ן כאן. אלא, אולי ענין חרטה הוא שידע שלא היה יכולת לו שלא לשבוע, אף שהוא יותר טוב לו, שיודע שלא היה מאמין לכל מי שהיה אומר לו. ויש לדון, שכמעט אי אפשר שאילו בא לו אליהו הנביא, והראה לו מופתים, ואמר לו שלא ירצה בו, שעדיין ישבע. אולי ר"ל שלא היה מניח לאליהו לדבר. אף זה מוזר. ותחשב.
** כב: בידוע -
ק"ק, שמשה כעס על בני ישראל.
** כה. צריך ביאור
איך היה אפשר להשביע אותם על תרי"ג מצוות, שהרי רמב"ם מעורר שיש יותר מאלו, אלא שלא נמנו (כמו מה שאינו לדורות). אולי צריך לומר שאלו לא צריכים שבועה. זה מחודש.
** כח. באומר בלבו -
יש להסתפק מהו הדין אם אומר בלבו היום כשדין של מלכות דן (רצה לומר כשצריך לתת לאותו מוכס), שנראה שקל לומר, על פי מה שאמר ר"ן, שכיון שהוא רק נודר מחמת שלא רוצה לשלם ממון, יש למילים שלו אותו משמעות. ויש לדון, שאולי לא מניחים בני אדם שעובר, ולכן אין לו אותו משמעות. ותחשב על זה.
** כח: פדאן חוזרות -
יש לדון ל"ל אומרים ש"מה מכורה כבר…,” ואז לא יועיל פדיון שלהם. (יש נפק"מ לתפוס את דמיהם.) ותחשב.
** כט. שור זה עולה -
היה אפשר לומר שלא חל קדושת הגוף אז, כמו אילו אדם מקדיש מקצת הבהמה ועושה שלא יפשה הקדושה (כמו בתחילת מסכת קידושין). ותחשב.
** כט: הניחא -
ואם תאמר אם כן מהו החידוש, שהרי כן סובר בדרך כלל. ויש לומר שכאן הוא מקור שלו. יש לדון איך יכול ללמוד מכאן, שמה שמתרץ גמרא יהיה חילוק. גם יש לומר שכיון שרק נלמד מסברה, אינו קשה שמשנה יחשיב אותו להיות חידוש די. ותחשב.
** לא: מתניתין בזבינא מציעא -
נמצא, אז, שהדין הא כך:
בזבינא דרמי על אפיה: אז, בין אם הוא שווה בשווה, בין אם הוא ביוקר, טובת המוכר הוא. אם הוא במכר זול, טובת הלוקח הוא.
בזבינא מציעא: אז, אם הוא ביוקר, הנאת מוכר הוא. אם הוא שווה בשווה, הנאת שניהם הוא. אם הוא בזול, הנאת לוקח הוא.
בזבינא חריפא: אז, אם הוא ביוקר, הנאת מוכר הוא. אם לא, הוא הנאת לוקח.
היה אפשר לומר שדין של שמואל הוא רק בזול. ותו"ת.
** לא נקרא שלם -
ואם תאמר זה רק מפני שהוא היה האחרון. ויש לומר שאין הכי נמי, אבל הוא גדול במה שמי שלא קיים אותו לא נקרא שלם. אולי כל המצוות כן, ואז כל המצוות גדולות, אבל רואים כן במילה (ולא רואים כן בשאר מצוות). ותחשב.
** לב. לא נתקיימה -
צריך ביאור ל"ל אומר ברא, כמו שאומר במשנה וכמו שמשמע מן הקרא. ותו"ת.
** ואתנה בריתי -
לכאורה, ר"ל שאף שנמצא שהיה חסר, ה’ עדיין רצה לתת בריתו לו. לכאורה, הסיבה הוא שהיה אותו חסרון דבר שלא היה יכול לשלם, שהיה אסור לעשות כן לעצמו. ותחשב.
** הפריז על מדותיו -
כמובן, יש לציין לגמרא סנהדרין שאומר שה’ היה מתרגז על משה כשעשה כן, ואומר שהיה רוצה באבות שלא עשו כן.
** שהוריקן בזהב -
לא יכול לומר שהוריקן בתורה (כפירוש שני של ר"ן) לשיטתו לעיל. ויש לדון, שעדיין היה אפשר לומר שקרה, אלא שלא היה הסיבה לעונש.
** והא בל"א -
קשה מגמרא סוטה (לא.). שוב ראיתי שמציינים לזה במסורת הש"ס.
** לב: שני עינים -
בו רואים דברים אסורים, ובשני אזנים שומעים דברים אסורים (שקול באשה ערוה), ובראש גוויה עושים מעשה.
** לד: דאי אזמניה -
משמע שכשאדם מזמין אחר, לא נותן לו האוכל.
** גזלה -
יש לדון, שאולי חשש שיגנוב, כיון שהוא רק לאו הניתק לעשה, אבל לא שיעבור על נדר.
** להורישה -
נמצא שהדין הוא שאדם מועל לפי הנאה שבו לו, אף שההנאה בא מכל החפץ. ונראה שאולי אף בלי זה, יכולים לומר שכיון שנהנה שווה פרוטה, מעל לפי כולו, אבל מבאר איזה הנאה מחשבינן לאותו פרוטה. ותחשב על זה.
** לה: מלמד הוא את בניו -
קצת צריך ביאור למה, שמבואר מגמרא שההנאה הוא מה שאין חבירו צריך לתת לו שכרו. לכאורה, היה נותן לו שכר ללמד לבניו.
** הכל צריכים דעת -
יש לדון אם זה סימן או סיבה. לכאורה, הוא סימן, שצריך ביאור מהו הסיבה. אם כן, צריך ביאור מה אומר גבי אשתו, שלא לומד ממנה, כיון שלא מביא חטאת. אבל, עדיין כך היה הדין אילו היתה מביאה חטאת. נראה שחושב שאולי לא יהיה הדין כן- ומה שלא אומר כן תורה הוא מפני שלא שייך. ותחשב.
** לו. ומזכה את אחיו -
עיין בגמרא בפסחים וגיטין, שמבאר פשט אחר (שהקנה לכולם, ורק עשה את זה לזרזם).
** לו: לא הויין פירי -
יש להעיר שהיו יכולים להיות תרומה על מה ששייר בשלו. אם כן, לכאורה, רובו נעשה תרומה עם טובת הנאה למפריש. ואולי כיון שהפריש על כרי של חברו, נמצא שאינו קדוש בלי כרי של חברו. ותו"ת.
** לז. ולענין -
אגר בטלה- אז, צריך לומר שמשנה הוא כשכבר שילם אגר בטלה, או כשאין בטלה. דחוק.
** לז: ועיטור -
כיון שיש מושג כזה, קל לדחות כמה פסוקים יתרים. ויש להגדיר את זה, שאולי כל זמן שיכולים לדרוש, דורשים, כמו שמצאנו גבי דברים אחרים (כמו: שני לאווים (פסח פרק שני), מילתא דאתיא בקל וחומר (קידושין פרק ראשון), ופרשה שנתחדש בה דבר (תוס’ בפ"ק של סוטה, וכן יוצא, חושב אני, מגמרות).
** קריין -
יש לדון מתי אלו נקראים. אולי היו מפטירים אותם. גם יש לומר שר"ל שנלמדים.
** לח. אלא למשה -
אולי לכן רוב בני הוראה הם מבני לוי (כמו שאומר גמרא ביומא). ויש לדון, שאם כן יהיה לווים בדווקא, ולא כהנים.
** ארוך וקטין -
צריך לשמור שלא היה בעל מום. לולי רש"י, היה נראה לומר שהראיה הוא ממה שהגביה את הקורות. אז, שואל שאולי היו הקורות קטנים (מסתמא ר"ל שלא היו אמר על פני כולם, או שלא היו דנ"ס), ואז היו קלים.
** גדול מה שנאמר בשמואל -
אולי כנגד זה אומר גמרא ברכות (פרק חמישי) ששמואל גדול ממשה, שכ’, “משה ואהרן בכהניו ושמואל בקוראי שמו.”
** ואשלך -
יש לדון אם הראיה הוא ממה שהיה יכול לישא אותם או ממה שהשליך אותם.
** פסל לך -
יש להעיר שלכאורה, היה נביא אף קודם לכן.
** לח: ומדעתה -
קשה, אז, מהו החידוש.
** המודר -
נראה שאולי הביאור הוא על פי מה שכ’ ר”ן לעיל, והוא שסתם נודר, אוסר בהנאה. אולי זה מיירי בסתם נודר, והנאה שאוסר בו הוא רק הנאה גדולה, אבל לא הנאה כזה. אם כן, אולי אין דין זה אם הוא אומר בפירוש לאסור הנאה.
לשון גמרא לא משמע כן כל כך, שמשמע שאוסר בהנאה. ויש לדון אם אלו לא נחשבים הנאה (ואז מותרים אף בכל איסורי הנאה) או שלא מניחים שאדם מכוון לאסור אותם כשאוסר בהנאה. ותחשב.
** לט. בשנכסי -
לכאורה, למסקנא, לא תלוי בנכסי מי אסורים על מי, אלא תלוי במי נדר, שאם חולה נדר, אז לעצמו לא נדר, ולכן מותר.
** לט: ואם לאו -
ק"ק מהו הצד שגיהנם לא נברא עדיין, שקשה מה קרה לרשעים. יש לדון, שאולי הם בדומה, עד אחר זמן. ותחשב.
** צריך ביאור
מהו הראיה מן הברייתא. אולי מניחים שידע משה כל תורה. מה שהוא בברייתא מוכיח שהוא חלק מן התורה. גם יש לומר שלא היה ידוע אילו לא היה ידוע למשה, שרק נדע אם ה’ אמרו למשה ומשה אמר לבני ישראל. גם יש לומר שברייתא אומר שדברים אלו מוכרחים, ואז היה למשה לדעת מסברה שלו. לא נראה כן, שמי אומר שאותו סברה מוכרח ליחשב; רק אומר שהסברה נכונה. ותו"ת.
** כל מצות נמי -
ואם תאמר זה רק אומר שלא ידוע השיעור. ויש לומר שאי אשפר להיות שאין שיעור ממש, שהרי לכל דבר צריך להיות שיעור (ויש לדון), ואז צריך לומר ש”אין לה שיעור” ר"ל שאין לה שיעור ידוע.
** חוזרות וחולקות -
יש לדון אם בריא שבא לחולה נעשה קצת חולה. אם כן, יש לדון אם חוזרים וחולקים (כמו גבי עשרייתא דבי רבי) או לא.
** מ. בתרייתא -
עיין במה שפירש ר”ן. גם יש לומר שיתפלל לו למות, כמו שאומר ר”ן בד”ה אין מבקש עליו רחמים.
** הקב”ה -
נראה שזהו הביאור של מה שאומר גמרא בפרק הערל שחולי זן את החולה.
** מ: ר’ אמי -
נראה שר"ל רבין, שמסתמא לכך מביאו (שגמרא הביא כמה מימרות מרבין אמר רב).
** מא. אקרוקתא -
מעשה זה מוזר מאד, שמוזר לומר שהיה הולך על צפרדע, וששוב המיתו על ידי נשיכה. מזה נראה שהוא קרוקודיי”ל. נראה שלשון “אקרוקתא” אף שווה ל”קרקודיי”ל.”
** מא: בחנם -
צריך ביאור למה אסור בשכר, שהרי ר”ן כ’ לעיל שמותר לתת שכר, והוכיח כן. ונראה שר"ל שאם אין הרופא נוטל שכר, ונכסיו אסור על חולה, אז מותר רק בשל חנם.
[אגב, בציור שמלמד לקטן, צריך ביאור למה גמרא מחשב את זה למהנה, שלכאורה ההנאה הוא שלא צריך לשלם, אבל אין חיוב על קטן, ואז בוודאי לא צריך לשלם. אולי מה שיכול להביא דמים עושה שיש לו שוויות, ואז הלימוד עצמו לו הוא ההנאה. ותחשב.]
** מב: כי פליגי בנכסי -
אם כן, עדיין צריך ביאור למה הוקימו את המשנה במה שהוקימו. צריך לומר שאם יכולים, יותר טוב לומר שמשנה בנכסים אלו, אבל מה שהוא יותר טוב אף מזה הוא לומר שמשנה אומר שמותר בהגיע השמיטה. דחוק.
ועיין לקמן, שלמסקנא, לפי הר”ן, נמצא שיותר טוב לומר שמיירי בדברים אלו ואסור אף אחר שביעית.
** עולא -
נראה שהוא לשיטתו, שהרי חלק על שמואל שהיה צריך לרשב”א לתרץ שיטתו לעיל.
** לא ישאלנו -
לריב”ח, צ"ב למה אמר שניהם.
** מג: מקצתם לראשון -
ואם תאמר אולי שאני הכא שלא חל ראשון. ויש לומר שהעושה החלות, מסתמא, חושב שחל הראשון, ואז יעשה שישאר. ותחשב. ויש לדון אם יהיה דעת בטעות.
** ודילמא אתי -
צריך לבאר באיזה ציור, לרבי יוסי, פטור ממעשר, שהרי דורשים פטור מעשר, ור"ן אמר שלפעמים לרבי יוסי יפטור, אבל צריך ביאור באיזה זמן. כאן, משמע שיחשוב שאחר שלש ימים לא יהיה הפקר; קשה למה לא, שאחרי שהפקיר ליותר משלש יום, הוא הפקר גמור. אף שיכול לחזור בו, והוא כעין מתנה, הרי כל הפקר כן. ותחשב.
** מז: לאשה -
גמרא אומר שמחלפת שעיבוד של בעלה בשביל מזונות. ותו"ת.
** לכתחילה -
עיין במה שפירש ר"ן. לכאורה, אז, תירוץ גמרא השני, שאומר אותם מילים, ואף אומר "נמי,” אינו אותו תירוץ. ותחשב.
** מח. עמדו אבותיהם -
יש לדון אם מפני שלא רצו שיאסרו הכל על הכל, עשו כן; או שכן קרה ממילא כיון שהיו הכל נודרים ומוצרכים לכתוב לנשיא. לשון גמרא משמע כראשון.
** בבל -
אם הם הפקרים, לכאורה, נמצא שאדם יכול לקנות הר הבית. כמובן, זה דרך קל להיות עשיר. שאלתי את ר.ש.ש. והיה פשוט לו ש"הפקירו אותם עולי בבל" ר"ל שבית דין היה בעולי בבל, והפקירו את אלו ב"הפקר בית דין הפקר,” ואז אין שום אחד יכול לקנות אותם.
** מח: מן השתא -
לכאורה, זה רק קושיה אחרת איך יכול להיות קנין סודר בכעין זה חל, אבל לא שייך לדיון גמרא של קני על מנת להקנות.
** לאתויי כי האי -
לכאורה, זה רק אפשר אם נאמר כצד ראשון, שיש חילוק ביניהם, ולא כצד שני, שאומר שמחלקת רבנן ורבי אליעזר הוא. ותחשב. ויש לדון, שאולי ר"א הוא תנא של משנה, ובא לומר שאף רבנן מודים לו בזה. לשונו עדיין מוזר.
** מט. והא קרא -
כן צריך לומר בין כך ובין כך, כיון שאמר שרק זכר הוא. אז, צריך לומר שאינו דווקא.
** רתחתה -
איני יודע כל כך מה זה, אם ר"ל דבר שנאכל חם, או דבר שהוא חם, או דבר שיש בו מים וכדומה חמים…. ותחשב.
** מט: קצירי -
יש לדון אם הראיה הוא ממה שאומר שת"ח צריכים תפלה או ממה שנקראים מריעי. היה אפשר לומר שהם קצירי, שהם קצירי דעת, שהם בועטים כנחש. (גמרא יומא ושבת אומר שכל תלמיד חכם שאינו נוקם ונוטר כנחש אינו ת"ח.)
** נא. בירקני -
עיין במה שפרש ר"ן. צריך ביאור איך היה מותר, ולא היה קול באשה שהוא ערווה. אבל, כמובן, כל מעשים אלו צ"ב, שנראים שהם גנאי לת"ח.
** לא לחנם -
יש לדון אם ר"ל שבא לו דבר מחמתו או אם ר"ל שהיה דבר מעולה. ויש לדון מהו מעולה בו.
נראה שהיה הוה אמינא שהוא על חנם כיון שאחר ימים, לא היה לו עוד אותו תספורת, ששערו גדל. אז, לא ידעו למה בזבז אותם.
** הנודר ממעשה -
לכאורה, משנה זה כבר שנוייה לעיל. עיין בעוז והדר שמעוררים כן.
** נג. דרך היוצא ממנו -
לא מבאר מהו הדין אם הפוך הוא, שדרכו ליאכל, ואין דרך היוצא ממנו ליאכל. נראה שזה יותר פשוט להתיר.
** ספק איסורא -
אינו ספק מחמת שכל מי שמסתפק מזה, קורא לו שמן סתם, וכל מי שמסתפק מזו, קורא לו שמן סתם, שאם כן, נלך אחר רוב, ונתיר. אלא, מחמת שרוב בני אדם לא מסתפקים מזה, יש איסור שקול איזה הוא בכלל סתם שאמר. ותחשב.
** נה: מכנסים -
עיין בגמרא נדה (פרק שני) שאוסר ללבוש מכנסים. אולי אומר שמותר להנות מהם (כמו למכור אותם לגוי). ויש לדון אם גוי מוזהר בזה (עיין שם). גם יש לומר שהם כעין של מקדש. גם יש לומר שדן אם יש עוד איסור של נדר. גם יש לומר ששל נשים הם, ולובשים דבר אחר, כדי להיות צנוע, עליו. ותחשב.
** נז: עיקר -
יש לדון אם ענין עיקר הוא שבא ראשון, שמוכרח לבוא ראשון, או ששאר באו ממנו.
** ישמעאל -
נמצא, לר”ן, אז:
א. גמרא מתחיל בשאלה אם גידול נעשה כעיקר בציור שהיה חומרא להיות כעיקר. לכאורה, אז, יש שני סיבות שיהיה כעיקר:
1. בא מן העיקר.
2. חומרא הוא לתת לו דין עיקר.
3. פסק שאין לו דין עיקר.
4. ב. הביא ראיה ממימרא שאומר שדבר של איסור שנטעו, ורבו גידול על עיקר, מותר. אז, רואים שאין גידול אותו דבר של עיקר.[fn:4]
5. ג. הביא שני קושיות, ממימרות של דבר איסור שגדל היתר, ששם מחמירים. אז, צריך לומר כאחד משני צדדי איסור שכתבנו.
6. ד. הביא עוד ראיה מציור שגידולי איסור אוסרים עיקר של היתר. דוחה גמרא שזה חומרא. עדיין אפשר לדון בשני הצדדים, שאולי מחמירים בכל מקום, או אולי הולכים אחר עיקר, אלא מחמירים ללכת אחר גידול.
7. ה. מביאים ראיה מברייתא שדן בביטול בשביעית. מניח גמרא (וצריך ביאור למה) שאף דן בביטול של גידולים, ולא רק בתערובת. ממה שיש ביטול, צריך לומר שגידול אינו כעיקר. דוחה גמ’ שאין הול’ אחר גידול אלא לחומ’. לכאו’, גם מחדש שהוא חומ’ (שבלי זה, לא היה הכרח, שהיה אפשר לומר שדן בפירות שהלכו משנה שביעית לשמינית).
8. ו. מביאים ראיה מברייתא שאומר שמה שנשחר (ואז צריך לומר שהוסיף מקרקע) בשביעית אסור. צ”ל שגידול מעלה עיקר. מה שנשחר במ”ש מעלה את העיקר. דוחה גמ’ שדיכן אותם.
9. ז. מביאים ראיה מברייתא שאומר שני דינים: מנכש עם כותי בטבל שנתדגן אוכל כאילו לא נתדגן (מח’ גידול). פירות של חשוד על שביעית מותר כשגדלו אחר שביעית. אין לדחות שדכנם, שלא מסתבר שחשוד ידכן. אין לדחות שזרעו כלה, שאומר בפ’ בבריי’ נג”ז. אין לדחות שתערובת הוא, שאומר נג”ז. אז, יש לנו ראיה. גמ’ מפרש שזה רק בשביעית, כיון שאיסורו בא מקרקע. לכאו’, הענין הוא שהשינוי בין גידול לעיקר הוא יותר חשוב, שהוא הקרק’ שגורם האיסור.
10. ח. מק’ שנאמר כן במעשר (שקרקע גורם). בריי’ אומר שאם זרעו מעשר טבל, גידול כעיקר (אלא שעל עיקר, צריך להפריש בפני עצמו). דוחה שקרקע לא גרם מעשר, אלא דיגון.
11. ט. מק’ ממשנה שלנו, שאוסר גדולי גדולי דבר שזרעו לא כלה, ואין הגידול מתיר. דוחה שלא בטל כיון שדבר שיש לו מתירים הוא. דן אם יש לו מתירים, ומסיק שכיון שמצווה לשאול, יש לו מתירים.
12. י. שוב דן גמ’ על מימרא שאומר שגידול של איסור אוסר אף עיקר[fn:5]. מקשה למה יהיה.
13. יא. מביא ראיה מו’ כמותו. דוחה שרק קאי על גידול. מק’ ממה שרשב”ג אומר כן. ת’ שכולו רשב”ג. אז, קשה על מימרא. מת’ שרשב”ג הוא רק כשלא טרח לזרוע, אבל אם טרח וזרע, אז עיקר כגידול.
14. יב. מקשה ממה שהביא בח’, שרואים שאין גידול משנה דין עיקר. דוחה ששם הוא מפני שלא רגיל לזרוע איסור.
15. ס:
16. ביום אחד- נראה שהגזירה יהיה שסובר שכל זמן שנודר להתענות יום, רק מתענה עד אותו זמן שפסק עכשיו. קצת פשוט שאין לחוש לזה, שקשה מה יהיה הצד שיתענה עד אותו זמן בדווקא. אולי חוששים (אולי רק כאן גוזרים או גוזרים כל ציור אגב כאן) לציור שבו סוף נדרו הוא בזמן מסתבר, כמו שקיעה (או אולי חצות). כמו”כ, י”ל שחוששים כל זמן שנדרו כלה אח”כ, שאחר שאמר לו חכם שמותר, יחשוב שמותר כיון שעבר עליו חצות, ולא מפני יום אחד.
17. כמו כן, מוזר לומר שישכח שנדר באותו זמן ביום שלעבר, או לומר שלא יחשוב שמחמת זה הותר. וצריך ביאור.
18. סא.
19. שנה כהשנה- יש לדון אם החידוש הוא ששנה כהשנה, או שיש נקודה בהשנה שעושה שהוא פשוט, ואף אם שנה הוא כהשנה, אין בו אותו נקודה. צריך לחשוב מה הוא אותו נקודה.
20. סד.
21. כבוד אביו- צריך ביאור למה יפחד מלומר את האמת. אולי הוא מפני שזה יגרום צער לאביו ולאמו. גם אפשר שהוא מפני כבוד עצמו, שנראה כעבריין.
22. סה.
23. במדיון- לכאורה, מניחים שלא רק אומר שה’ התיר את נדרו במדיון, שזה פשוט, שאי לאו הכי, האיך חזר לפני שה’ התיר את נדרו. אז, צ”ל שר”ל שהיה צריך להיות במדיון בדווקא כדי שלהיות לפני יתרו. ויש לדון איך היה לפני יתרו. אולי ה’ עשה לפניו, ושמע כן. גי”ל שהגיד למשה איך להתיר את נדר עצמו (באיזה פתח ישמש). יש לדון אם נחשב חכם. ויש לדון אם צריך להיות חכם, כיון שה’ אמר לו הפתח. נראה שצ”ל חכם, שאי לאו הכי, לא הועילו כלום, שיתרו לא ידע שה’ נתן לו פתח; ואם יאמין לזה, רק יאמר לו שה’ התיר את נדרו. ותחשב על זה.
24. סז.
25. אם כן ואסרה- צריך ביאור, שהרי רק דורשים שזה דן באב מחמת וי”ו שמוסיף על אותו קרא. אם לא היינו כותבים אותו קרא, אז לא היה שום מקור שאב מתיר כלל. נראה שמקשה שהיה לו לומר אותו באופן שרק אומר דין אחד, ולא באופן שמוסיף עוד דין. ותחשב.[fn:6]
26. אימא אב לחודיה- ואם תאמר הרי אומר קרא שבעל יניא אותה. ויש לומר שזה עושה שיקיים. שוב ראיתי שר”ן כ’ כן (כן אני חושב).
27. לאו משום שותפות- ואם תאמר אולי בשותפות יפר בקודמים, ושלא בשותפות יפר שלא בקודמים. ויש לומר שיש רק קרא אחד. אם נוקים אותו קרא בהפרה בשותפות, לא נמצא לנו קרא אחר לחדש שיכול להפר בפני עצמו בלי אב. וזה פשוט. ותו"ת.
28. ע.
29. בנעוריה- ק"ק שצריך מקור לתת לו כוח בזה, ולמנוע כוח בזה. אולי הוא מפני שקרא משמע שנותן לבעל כוח יותר ממה שמשמע שנותן לאב. אז, מניחים יותר כוח לבעל. ותחשב. גם יש לומר שצריך אחד כדי שלא נלמד מחברו. ותחשב.
30. ואני- יש להעיר ששאני “ואני” שבשעת קיום לא אמר שהוא רק לשעה. (אולי זהו תירוץ הגמרא; שהרי, לא קל לבאר מהו תירוץ גמרא, שלא באר.)
31. עא.
32. תניא כוותיה- לא הבנתי מה רואים מברייתא שלא רואים ממשנה.
33. עב.
34. שמע אב- לנקוט ציור שצ"ל שזה שמע וזה לא שמע הוא קצת מוזר. ותחשב.
35. עג.
36. ראוי לבילה- לא מפרש ל"ל נאמר כן.
37. עה.
38. מיחל חלים- צריך באיור איך נבאר את הקל וחומר אם חלים ובטלים. ותחשב. אולי הוא יותר קל כיון שכשהיה חל, היה כבר עומד להיות נכחש. ותחשב.
39. (עיין בר”ן, שנראה שמבאר שזה קושיית גמרא. עדיין התירוץ צריך ביאור.)
40. עו.
41. מכורה כבר- יש להעיר שכאן יכולה לחזור ולנדור. אם כן, יהיה תלוי במחלקת רב ושמואל בערכין.
42. עז:
43. טלי ואכלי- לעיל, הלשון שאמר לא היה טוב. צריך לומר או שהוא לשון גרוע, או שהוא חול, וכב”ש, או שאין עמו דעת. ותחשב.
44. עח:
45. מועדי ה’- ר”ן באר שדורשים מ”אלה,” שממעט.
46. שותק סתם- היה אפשר להוקים אותו בשותק על מנת לקיים לאחר זמן (עיין בר”ן עט.).
47. עט.
48. ע”מ למיקט- צריך ביאור למה כל כך פשוט לגמ’ שאין חילוק בין אם מכוון להתיר (ע”מ למיקט) או לא (ורק לא יודע שיכול להפר). ותחשב.
49. פא.
50. מפני שהם- ואם תאמר הרי אינם כבר ת”ח. וי”ל שקודם שהם ת"ח כבר עושים כן, ולכן לא נעשים ת”ח. גי"ל שר"ל שאביהם עושים כן.
51. ר”ש בדר”א- קל להעיר שהרי הוא בן של ת”ח.
52. פא:
53. שלא מצאנו- אולי זה כעין משלות שועלים. (בכ”מ ראינו שיש ענין במשלות שועלים. אבל, גמרא אומר שרק נשאר לנו שלש מאלו שאמר שלמה, ואין זה בכלל.)
54. פג.
55. דלמא- מעניין שנסתפק בזה, כיון שאמר אותו סתם. לכאורה, מקשה שיהיה לו רק אותו כוח, ולא יוכל להפר את הכל. ותחשב.
56. פג:
** דיספד -
יש לדון אם זה נחשב עינוי, שאף שהיא מתה אז, יש צער לנשמה שלה, או שמצערת מחמת שיודעת שכן יקרה. ותו"ת.
** פד: כהנים -
נמצא שאף שנותן לו דבר, אינו אסור. רק אסור אם טובת הנאה שלו נחשב ממון. וצריך לחשוב למה הוא כן.
** פז. אמרו לו מת -
לכאורה, יש שלש ציורים:
1. אמר שקורע על אביו, ונמצא בנו.
2. אמרו לו שמת אביו, וקורע סתם, ונמצא בנו.
3. אמרו לו שמת, והניח שהוא אביו וקורע סתם.[fn:7]
4. יודעים שבראשון לא מהני, ובאחרון לא מהני. יש לדון מהו הדין בשני. ותחשב. נראה לדייק ממה שברייתא רק אומר השלישי שדין שני הוא כדין ראשון.
5. אמרה- יש להעיר שהיה אפשר לצדד ששהיה הוא קיום. יש שיטות במשנה זה שלכאורה הם נגד זה. ותו"ת.
6. פז:
7. אמר רבא- שבועה שיאמר- יש שלא גורסים “קונם” גבי כ”א במשנה. צ”ל שעדיין נחשב חלוק לפי ר”ש. לכאורה, ההוחכה יהיה שאין תנא אחר שמצריך כל כך חילוק, ואז צריך לומר שהוא רבי שמעון. ותחשב.
8. פח.
9. ואי אמרת- עיין במה שמבאר. עיין גמרא במכות שאומר שזה מיעוט אחר מיעוט. לכאורה, רואים מכאן מהו דרשת מיעוט אחר מיעוט (אם לא נניח, נגד הר”ן, שהם חולקים).
10. ויש להעיר שצריך לומר שלא רק לא ממעט סומא, אלא אף מרבה אותו. ותו"ת.
11. פח:
12. כמאן אזלא- לכאורה, בין כך ובין כך, זה קשה על רבי מאיר. ונראה שרק קשה כיון שלא מסתבר שאומר לשון זה בדווקא. ותו"ת.
13. כל שיצא- ר"ל, אם לא הפר באישות ראשון, לא יכול להפר ע"י אישות השני.
14. צ.
15. מאן חכים- חושב אני שמצאנו רבא אומר כן על אמוראים חלוקים. ממה שמשמע שאין חכם כזה בלי הוא, צריך לומר שיש שהיה הכי טוב בענין זה, ויש בענין אחר....
* Footnotes
[fn:1] ודע שאז צריך ביאור ל"ל הקשה ממנו על רבא.
[fn:2] ויש להעיר שזה רק מהני במסקנא (שאף אביי סובר שיש מי שחולק עליו), אבל בהוה אמינא בין כך ובין כך חולק על שמואל, שסובר שמואל שיש תנא שחולק על רבנן. ויש לדון, שעדיין אפשר לומר שרוצים למעט את המחלקת.
[fn:3] ועיין בר”ן ד”ה מכלל דאי אמר, שגם הוא משמע כמסקנא שלנו.
[fn:4] יש להעיר שבסוגיה זה, מצאנו שדן ב”רבה על....” יש להעיר שזה יהני רק לביטול דאורייתא, אבל מדרבנן עדיין יאסור. צריך ביאור, שלא משמע כן כל כך כאן. אולי “רבה עליו” ר"ל שרבה עליו עד שמבטל אותו. ועיין.
[fn:5] יש לדון אם דן אם אוסר אותו מן התורה או מדרבנן. יש להעיר שמה שמביא ביב’, שאומר שעיקר עדיין צריך להפריש ממנו בפני עצמו מוכרח שרק דן בדין דאורייתא, שאי דן בדרבנן, יש לומר שדרבנן אסור, שמדאו’, גידול כעיקר. צ”ב למה פשוט לגמ’ שאינו חומ’ מדרבנן. ותחשב.
[fn:6] יש לדון אם הענין הוא מה שמוסיף דין או מה שמוסיף מילים. ותחשב.
[fn:7] גם אפשר להיות שאמרו לו סתם ואמר שהוא אביו, אבל לא נראה לי כל כך שזה ישנה כלום.
