** ב: הלין -
עיין במה שבאר בלשון ראשון. לשון שני מסתבר (מפרש למה יקדים). לא מפרש למה יקדים מה שהוא יותר מרובה ראשון.
גם יש להעיר שיש סיבה להקדים בביאור, וזה דוחה סיבה לעשות כסדר. אז, צריך ביאור ל"ל אומר אותו סדר בתוך תחילת משנה. באמת, גמרא לקמן מקשה כעין זה; עיקר התירוץ הוא שיש סיבה להקדים מה שמקדים, וזה יותר חזק מן הסיבה להשוות אותם. ותחשב.
** ג. מאי איכא -
שניהם אתיין מדרשא... דרבנן נינהו- צריך לבאר מה אומר, שלכאורה, אילו אתיין מדרשה, לא היה מדרבנן, אלא היה דין מדרבנן. גם צריך ביאור, אז, למה שניהם שווים, שאחד בא מדרשה. אולי דרשה שלו הוא רק מדרבנן, הוא רק אסמכתא. יש לדון ל"ל יהיה דאורייתא, שנראה שוהא דרשה טובה. אולי לא נתקבל, ורק אסמכתא הוא. אם כן, כל שאר דינים שדורשים ממנו הם גם כן אסמכתות, ובזה הוא כל דיון של הגמרא. לא משמע כן מן הגמרא. ותחשב.
אפשר שחומר הדין אינו, בהכרח, סיבה להקדים דין; רק תלוי כמה פשוט וידוע הוא. אם דבר נודע על פי רבנן- בין אם חידשו אותו, ובין אם דרשו אותו- אז הוא שווה בזה. אם כן, רש"י יכול לומר כן. עדיין לשון “דרבנן נינהו,” שמשמע ששניהם דרבנן, קצת קשה, וצריך לומר שהוא דבר שהודיע לנו רבנן.
** ז. כי מתו כל האנשים -
צריך ביאור למה מזכיר מה שהיה דתן ואבירם, שעיקר הענין הוא שנעשו עניים. נראה שמוכיח שלא מתו ממש ממה שהיו דתן ואבירם, ויודעים שחיו זמן רב אחר כך.
** כל מקום שנתנו -
עיין במה שפרש כאן. מעניין שזה נחשב נתינת עינים בהם. ותחשב. גם יש להעיר שצריך ביאור מה עושה, שכבר צריך ליפול בעניות. גם צריך ביאור למה צריך הוכחה שעניות כמיתה. ותחשב על זה. אולי הענין הוא שכיון שעניות כמיתה, כמו שעניות מצוי בו, אף מיתה מצויה בו. רוצים שזה לא יקרה, ואז נותנים רבנן עיניהם בו, ואז יעני. ואם תאמר דילמא ימות. ויש לומר שתלוי בדעת חכמים. זה מחודש.
גם מחודש הוא שמה שנעשה כאן נחשב נתינת עינים בו. ותו"ת.
עיין בר"ן שלא פירש כן. לר”ן, יש לדון ל"ל נעשה, לפעמים, סומא או נעשה שאין לו בנים. (אגב, יש להעיר שמצאנו בכמה קללות שנעשו שאין להם בנים, כמו בשבת (קיח) ובבבא מציעא (פרק תשיעי).
** ח. יהיב שלמא -
עיין במה שכתב. זה חלוק ממה שמפרש ר”ן (עיין שם), שמשמע שמתיר לגמרי. נראה שחולקים מה אומר “עד שבא...,” אם רצה לומר שצירך לעשות כן בדרך עד בטוח שבא עשר והשיבו לו, או שצריך לעשות כן פעם אחת עד שיכנס עשר, ושוב יתירו לו. ותו"ת.
** ט: סבר -
כאותו- נראה שבא לןומר שלא צריכים שסבר כשמעון, אלא רק צריכים שהיה כאותו שבא לפני שמעון. ויש לדון, שהיה אפשר לומר שסבר כשמעון שאין זה רע, שהיה אפשר לומר שאף שכיוון לשם שמים, הרי ציער את עצמו. ועוד, אולי יש לחוש שמא חזר בו. אז, צריך לסבור כשמעון הצדיק. ותחשב.
** יג: חלים על המצווה -
עיין בלשון שאומר. יש להעיר שאומר לשון נדר בו. אם כן, לכאורה, צריך לומר או שסובר שהאו דין דרבנן כאן, או שסובר כמה שאומר ר"ן שלא צריך לומר לשון "יאסר פי עלי" דווקא. גם יש לומר שלשונו לאו דווקא, כמו המשנה.
** יד. דהא כתיב -
ונימא נמי עד- ואם תאמר היה לו לומר שיכול לידור בדבר הנדור, ולא שהוא עד שידור בדבר הנדור, שהרי אף יש קרא שאומר לנו שצריך לידור בדבר הנדור. נראה שכוונתו לומר כר"ן. (גם יש לומר שמקשה שיש שני קראי שמשמעים כן, וקשה איך יודעים איזה לדרוש. ויש לדון, שלכאורה, יותר מסתבר לדרוש שצריך להיות בדבר הנדור, שהרי יותר משמע נדר, שאם חל הנדר יהיה כדבר הנדור, ואז אומר נדר. ויש לדון, שאולי בדבר הנדור יש יותר זמן היתר, ויש לומר שבזמן היתר תופס. ותחשב. גם יש לומר שאם אומר לשון איסור, מחזק את דיבור (ואף שאינו, באמת, כאיסור, אומר שהוא כעין נעשה איסור מאת ה', ולא צריך נדר), אבל אם אומר שהוא כדבר הנדור, היה לו רק לידור. ותחשב.
ודע שאפשר לומר שכשרשי אומר "עד" לא בא לאפוקי מנדרים, אלא לאפוקי מדברים אחרים. ויש לדון מה הוא שיכול לדמות לו שאינו נדור ואסור. אולי הוא דבר שמותר. קצת קשה, שזה לכאורה, פשוט. ותחשב.
** מקום אחר -
גם יש לומר שרצה לומר מקום חוץ מכבוד אמו. (ויש לדון ל"ל יפתחו לה פתח ממקום אחר, שלכאורה, סובר שכל הבעיה הוא שיזלזל עוד בכבוד אמה, אבל אם מתירים לו כן, יבין שהוא נגד כבוד אמו. ויש לומר שלא ישמע לנו, ויעבור ויזלזל בכבוד אמו עוד. ויש לדון, שאם כן, צריך לומר שמה שת"ח לא עושה כן הוא מפני שהוא צדיק, ולא רק שיודע את הדין. ויש לדון, שאולי יודע יותר תורה, ויודע כמה הקפידה תורה על איסור זה.
** טו. והאמר -
כיון שנדר- מלשון מפרש, משמע שרבי יוחנן מחייב כאן על נדרו. יש לדון אם הוא מפני שנדר נדר שווא, או הוא מפני שמוכרח יעבור על נדרו (ומותר לעבור רק מפני שבין כך ובין כך יעבור). רש"י כ', "לאלתר מלקים אותו שיישן." לכאורה, ר"ל כצד שני. ויש להעיר שאם כן, יש חידוש גדול, והוא אחד משנים אלו:
1. אין איסור נדר מה שעושה נגד הנדר, אלא אמירה שנתכחש. לא נראה כן, שאם כן, לא יהיה איסור חלוק מתנאי. ויש לדון, שאולי כל החילוק הוא איך חושבים עליהם בני אדם, ואז יעשה תנאו ולא איסור שלו. אבל, יש עוד דינים כשוגג והתראה שמורים נגד זה.
2. יכול אדם ללקות על איסור קודם שעובר. זה מעניין, שהיה אפשר לומר שעונש מתקן לרע שעשה, ואולי רק יכול לעשות כן אם יש כבר רע. ותחשב.
** יח: לשון אחר -
החילוק בין שנים אלו הוא אם "פירושיהם" ר"ל פירוש שמפרש לאחר זמן או פירוש שמפרש בשעת הנדר (והוא תלוי באם קאי על משנה זה או משנה שלאחר מכן). באמת, היה נראה לומר שהוא שניהם, וש"פירושיהם" ר"ל כל פירוש שמסתבר. אם רק מפרש לאחר כן, ממה שלא פרש מיד, אינו כל כך מסתבר, ואז צריך להיות יותר מסתבר כדי שיהיה כן. ותחשב ותבין.
** יט: אמר לא תניא -
עיין במה שמפרש. יש להעיר שזה מחלקת תנאים. אז, צריך ביאור מה מוכיח ממה שתניא, שיש לומר שזהו החולק שתניא כן. גם, באמת, לשון תירוצו צריך ביאור, שהיה לו לומר שהוא כאותו שיטה שסובר שאין נזיר שמשון. אולי לא ידע שיש מחלקת.
** כ: דמצייני -
ק"ק, שהרי הכל לובשים ציצית. (לולי רש"י, היה אפשר לציין לגמרא בשבת שאומר שהיו תלמידי חכמים בבבל נוהגים ללבוש בגדים נאים. ויש לדון, שאז צריך לומר שהיו אמוראי א”י אלו דנים בת”ח של בבל.) גם צריך ביאור, שלכאורה לא לובשים מלאכים ציצית, שאינם מצווים בציצית. ויש לדון, שמצאנו שדים שיש להם שכר וחיוב ממון, כמו שכתבנו בתחילת מגילה ובכ”מ. ותחשב. ויש לומר שיחסם לה’, שבא מן הציצית ושנראה מן הציצית, הוא דמיון שלהם למלאך. ותחשב.
