** ב. כל כינויי -
עיין בראיה שהביא מריש נזיר. יש להעיר שבגמרא כאן מקשה כן. צריך לומר שר"ל כך: בהכרח, חולקים גמרא כאן וגמרא שם אם זה קושיה טובה או לא.. לא מסתבר שהיה משנה בקושיה זה (שלריש לקיש הוא דין דרבנן), שהוא בוודאי קושיה טובה (ויש לדון, שאפשר שחולקים בדין, אם הוא דרבנן או לא), אלא צריך לומר שהוא קושיה אחרת (ועיין לקמן איך ר”ן יבאר אותו קושיה). ותו"ת.
** ב: איידי -
צריך לבאר את זה. לכאורה, “עיקר לשון נדר ושבועה” צריך ביאור. אם אותו לשון מעכב, אז אף אם אינו סימן לשום דבר אחר, עדיין יש דבר חשוב באותו לשון. (מסתמא, מה שהוא מעכב עושה שמוכח שעושה דבר חלוק, אבל אולי אין זה מה שאומר גמרא.) אבל, כיון שיכול לעשות בכל לשון, צריך ביאור מהו “עיקר הלשון.” יותר מזה, קשה מהו החילוק ביניהם, שנראה שהם דבר אחד. ותו"ת. לכאורה, צריך לומר שיש חילוק יסודי ביניהם, שאחד ממש עושה איסור חפץ ואחד עושה איסור גברא, ו”עיקר לשון” רצה לומר הלשון שהוא יותר קרוב למה שקורה. אז, עיקר החילוק כאן הוא מה קורה (עדיין יש לדון אם “עיקר הלשון” הוא סימן לזה, וכן ר"ל גמרא, או אם “עיקר הלשון” ר"ל רק מה שבני אדם אומרים, או כדומה, וזה יתרץ ק’ ראשונה, ומה שכתבנו יהיה נצרך רק לשני. ותחשב.)
** להיות נודר בו -
עיין שם. לכאורה, הענין הוא שאילו לא מזכיר אלא שם ה’, אינו שבועה, ואז הוא לבטלה. יש להעיר שאף אם הזכיר לשון שבועה, כיון שלא היה צריך להזכיר שם ה’, לכאורה, עדיין מוציא שם שמים לבטלה. ותחשב.
** לנדור נדר -
ר"ל, לעיל היינו צריכים לפרש המשנה. המשנה בוודאי למד מהיקש, ואז מקשה למה צריכים לימוד מהיקש. היה אפשר גם להקשות למה צריכים קראי, אלא שזה לא כל כך קשה בפני עצמו, שיש לומר שקראי הם לאחר שכבר לימד הקש. אבל, כיון שאין הוכחה שהיקש מלמד כן, יש לומר יותר שקראי מלמדים כן, ולא דורשים היקש לזה.
הסיבה שיותר מסתבר לדרוש כן הוא שבכל מקום שיכולים לדרוש דורשים. לכאורה, אין צריך זה, שיש לומר שהוא יותר מסתבר כיון שאז אינו קשה למה צריכים ההיקש. ותחשב. שוב הבנתי שהוא מפני שאין ההיקש מיותר, שיש דברים אחרים שלומדים ממנו. אז, כל קושיית גמרא היתה רק למה מזכיר אותו התנא. אבל, עכשיו יכולים לתרץ שלא הזכיר אותו אלא תנא שלא דורש מקרא אחר. ותחשב.
** ג: הניחא אי ס"ל -
ר"ל, שם פשוט לגמרא שחל זה על זה. אז, צריך לומר שבצד זה, שלא דורש שחל על נזירות. אז, צריך לומר שאותו גמרא לקמן נלמד מסברה. (לכאורה, גם היה אפשר לומר שחולק עליו, ואותו גמרא הוא אמורא אחר.) עדיין לא מבאר מהו הסברה ולמה לא שייך כאן.
** אמר מר -
לא שייך- לכאורה, שייך הוא במקצת נדרים. אולי לא מסתבר לגמרא שיהיו נדרים שעובר יותר עליהם. לא נראה כן כל כך מר”ן. ויש לדון, שאולי ר"ל שלא שייך, שאין לומר שלנדר עושה ס”ר של עושה לאו, שלא לעולם קורה. ותחשב.
** ד: קשריא -
עיין במה שבאר. לא יכל לומר שהוא מה שמתיר אותה, שהרי אף בנזיר מתיר אותו. ואם תאמר הרי כבר מותר, שרק צריך להביא אחד. וי"ל שכבר תירץ כן. ויש לדון, שזה אומר, אז, ששני התירוצים אומרים דבר שווה, ורק חלוקים הם בנקודה זה. היה אפשר לומר נגד זה, והוא שאולי תירוץ ראשון מראה דין בנזיר, ולא בקרבו, אלא שדן נזיר מוכיוח דין קרבנו. ותחשב. אז, צריך לומר שמתיר קדשים, שהוא מצווה. ויש לדון, שלכאורה, יש אף מצווה ביין, כמו קידוש. אולי אין קידוש על היין מצווה דאורייתא.
ואם תאמר מה לנו במה שהוא מצווה. ויש לומר שאז יותר רע אם הוא מאחר אותו, שגם מאחר את המצווה. ותחשב. גם יש לומר שקרבן כזה מרצה מאד, כיוהוא עשוה דבר חשוב, שגורם מצווה. דחוק.
** תיתי -
נמצא שאין לוקים על מה מצינו, כמו שאין לוקים על קל וחומר. (ודע שמצאנו חילוקים ביניהם, כמו לענין לומר שטרח וכתבו קרא.)
** ה: אלא הכי (המשך) -
היה אפשר לומר שמוכרח שאסור, שאי לא ר"ל במשא ומתן וכדומה, אז ר"ל בהנאה, ונאסר בכל. ויש לומר שיש מאלו שאינם בכלל הנאה; אז, לא יאסרו מאותו ממה נפשך.
** ו: בעי ר”פ -
אפילו בדיבור בעלמא- ר"ל לא צריך כל כך לעשות החלות, ואז אף לא צריך כל כך דיבור. כמובן, היה אפשר לומר להיפך שכאן הדיבור יש עמו מעשה. ותחשב.[fn:1]
** או דילמא -
עיין בכלל שכתב. יש לדון אם דיונו הוא בכלל זה או דיון שלו הוא שאולי כאן כל כך מסתבר ללמד עד שאף שאין כלל של אין היקש למחצה קיים, מקישים (שאולי רק צריכים כלל זה אם אינו מסתבר להקיש). ותחשב.[fn:2]
** יש יד -
כך פירשו רבותי- עיין במה שהקשה. נראה שיש חילוק בדין (אבל אולי אין אני נכון בזה), והוא שיש חיוב לתת פאה בכל זמן, בין אם יש עניים בין אם אין עניים, אבל אין חיוב לתת צדקה אלא אם כן יש עניים. ותחשב. עדיין יש לדון אם זה יעשה שפאה יותר חמור, שבכל זמן צריך לדון מה נחשב חלק מן הדין ומה נחשב חומרא (שהרי נאמר שצדקה יותר חמור, שרק חייב אם יש לו שדה). ותחשב.
** ז: שנאמר כי -
יש להעיר שגמרא גם לומד מזה שעני נחשב כמת. אם כן, לכאורה, צריך ביאור מהיכי תיתי שהיו עניים, שאין לומר עוד שהוא מפני ששאר נחשבים כמת לא יועילו, שיכול להיות כל שיועיל, ונאמר מזה שנחשב כמת. צריך לומר שמה שהוא הכי מסתבר להיות שמועיל וגם נחשב כמת הוא עני. ותחשב.
** נדהו -
עיין בגזירה שכתב. יש לדון, אז, למה מותר אם אינו בפניו. לכאורה, צריך לומר ששלא בפניו ר"ל שלא ידע עליו כבר. גם יש לומר שכיון שלא היה לפניו, אפשר לו לומר שבדקו רבנן ומצאו שלא קרה. דחוק, שאם חושב כל כך, לכאורה יחשוב שהתירו לו.
** ח. הא קמ”ל -
צריך ביאור, שכן אומר גמרא בפירוש במנחות (צט).
** עשרה -
שכינה עמהם- נמצא ששכינה עם העשרה אף כשרק משיבים שלום, ואף אם אינם שם בחד זמן, שאי לאו הכי, מה מהני נתינת שלום להם. ויש לדון, שאולי לא צריך שכינה, שרק מגין מייסורים. ויש לדון למה מגין.
** ח: בעל מהו -
אלא לשון- אף מצאנו חילוק במה שעושה (אם חל למפרע או לא), אבל כוונת ר”ן הוא לחילוק דינים, ולא לחילוק תוצאות.
** שמע מינא -
יש להעיר שקצת קשה מהיכי תיתי שלא רצה להתיר עם שלש, אלא שהיה יותר קל ללכת לרבו להתיר יחידי.
** יא. דתנן -
חפצא- זה מעניין מאד. צריך לבאר, באמת, ענין של איסור שיש בו חפצא, אבל מה שזה נחשב איסור שיש בו חצפא אולי יבאר אותו ואולי יבאר ענין נדר (או שניהם).
** אלא רבי יהודה -
זה מעניין, שהרי גמרא גופא הקשה מזה.
** יג. מיבעי ליה -
בורר- לשון זה שאומר הוא קצת מעניין. היה לו לומר שעושה יותר מכך; הוא לא רק בורר, אלא מקדש. קצת משמע שלא עושה כן, אלא מה שחטא ומה שחייב מקדש, אלא הוא בורר. זה מחודש.
** באומר -
זה מחודש, והוא כלל שטוב לדעת. יש לדון ל"ל רק אומר שנעשה כאומר.
** באומר -
צריך לדון באיזה ציורים אומרים שיש נדר בלשון שבועה ולהיפך. ותו"ת.
** הרי זה מותר -
עדיין צריך ביאור למה שנה תחילתו (שאלו מותרים). יש לדון, שאולי תנא רצה לתת הקדמה, שיותר קל להבין מה שאומר תנא כשיודעים איזה סוג יאמר. ותחשב.
** האומר -
אפילו בדבר הנדור- יש יותר חשש כאן משני טעמים:
1. יותר מצוי שידור אותו בדבר האסור, כיון שיותר מצוי שידור אותה.
2. יותר מצוי שידור אותו בדבר הנדור, כיון שיותר מצוי שידור אותה.
יש להעיר שנראה מלשונו שהבעיה הוא שחוששים שמא ידור בדבר הנדור. עיין במפרש (יד.) שמשמע שהבעיה הוא שידור עוד באמו, והוא גנאי לה. יש לדון למה הוא גנאי לאמו, שלכאורה, מראה שמחשיב אותה, שנודר בשמה. ותחשב. גם יש לדון למה זה רק בעם הארץ. לכאורה, הוא מפני שע"ה לא יודע שיש איסור לבזות אמו.
** יד. הילכך -
איסור וקדושה- זה מעניין, שמשמשע שחפץ של נדר יש עליו קדושה. אולי רק ר"ל שלפעמים יש עליו קדושה, כמו אם נדר להביא קרבן. דחוק, שנדר הוא כשאמר עלי, ואז אין לשום חפץ קדושה, לכאורה (אלא שצריך ביאור למה נקרא נדר, אם הם כל כך חלוקים). גם יש לדחות שקדושה רק ר"ל דבר שחלוק או דבר האוסר (כמו בתחילת קידושין). לא נראה כצד שני, שאם כן לא מוסיף כלום כשאומר כן. ותחשב.
** יד: ואי לימא -
קשה, שאף אם חל, יהיה דבר שאי אפשר לקיים, כמו שמקשה גמרא. ותחשב.
** טז: אלא -
הכא במאי עסיקנן- לר"ן לעיל, לא ממש עוסקים בכן, אלא נעשה כמי שאמר כן.
** כשמזכיר שם -
צריך ביאור למה יהיה כן.
** יז. מה שאומר שיש
חלות, אבל מנין נזירות רק בא לאחר כן הוא מעניין. אולי נזירות טוען שימנה שלשים יום שהם לנזירות בלחוד. אז, מונה שלשים לאחד ושלושים לאחד, ואז נמצא שמהני, אבל כל אחד היה טעון כן ואוסר אותו עד שעשה כן. ותחשב. אבל, אז צריך ביאור ל"ל יכול לחול אם אינם בבת אחת ואם אינו מוסיף, שהרי בוודאי יוסיף, שמוסיף עוד שלשים יום שמונה לו ולא לדבר אחר, וזה עושה שצריך להיות נזיר לעוד שלשים יום.
** יז: תנן יש נדר -
לא הבנתי כל כך מה אומר בר"ן זה.
** יח. הכא במאי עסקינן -
פשיטא- עיין במה שכתב. לכאורה, היה אפשר לומר שיש הוה אמינא שיהיו שניהם עולים במנין אחד. ותחשב.
** הכא -
עיין במה שכתב שיש איסור גברא ואיסור חפצא בנדרים. אולי ר"ל שיש עשה, והוא איסור חפצא, ויש לאו, והוא איסור גברא. לא משמע כן כל כך ממה שאמר. יותר משמע שיש איסור שבא מחמת נדר, והוא לא מפורש בקרא, שלא נעשה בידי ה', אלא על ידי הנודר, ויש ציווי מה' לשמוע לאותו איסור. צריך ביאור.
** יט. מאי איכא -
צריך ביאור למה לא אפשר לומר כמו שאומר בכוי אף כאן, והוא לומר שמחמיר בספקות דרבנן, אלא שסובר שבני אדם מכוונים שלא להקדיש במצב ספק. ותחשב. (נראה שזה קושיה, אבל לא נראה שזה ממש מה שאומר בביאור כוי, שנראה שאז אולי אומר שמחמת הספק, בני אדם לא חושבים עליו ל"בהמה," ואז לא מהני. בנזיר, אי אשפר לומר כן. ותו"ת.)
** יט: אין אחד -
מעניין שאומר שר"ט אמרו, ור"י נתן בו טעם; היה לו לומר שר"ט אמר אף הטעם, ור"י אמר שניהם משמו.
** אלא להודיעך -
ויש לדון למה אינו חשב כוח היתר לגלות שכך הוא טעמו (ואז, ממילא, מקיל ביותר ציורים).
** כ. אל תהי רגיל -
עיין במה שמבאר. ואם תאמר יאמר להקפיד בשבועות. ויש לומר שכש"כ הוא. גם יש להעיר שמעניין שיותר חוששים לשבועה, כיון דאית בה עונש חמור, מנדרים, אף שיותר מצוי לבוא מנדרים. ויש לדון, שאולי אמר כן כדי לחדש שאף יש לחוש כן ולא לשבוע. ויש לדון, שאז היה אפשר לומר שזהו הסיבה שאמר שבועות כאן. אלא, נראה שאם חוששים לנדור שמא ידור, אף נחוש לשבע שמא ישבע. אז, נראה שלא צריכים כך.
** אשתו נדה -
עיין במה שכתב. גם יש לומר שאז מתאוו טפי (ר"ל, יש יותר חשש שיבעל אותה), ואז יותר אסור.
** כא. שניהם רוצים -
עיין במה שאמר. היה אפשר לומר שהוא מפני שאין פיו ולבו שווים. ואיני כל כך ברור באותו דין.
** כד. הריני -
עיין בשיטת רשב”א שמביא. לכאורה, זה רק מפני שיכול להחזיר אותו, שאי לאו הכי, צריך ביאור מה אומר שהוא רק הפוכי מטרתא. אז, קשה, שיכול לומר הנותן שלא היה מקבל אותו. אז, אינו הפוכי מטרתא. ותחשב.
** כד: ודילמא קינא דשומשי -
עיין במה שמבאר ר”ן בכל הסוגיה. צריך ביאור מהו קושיה זה, שלכאורה כן הוא אומר, שאומר שמותר, והוא מפני שלא מקיים תנאי שלו, אלא ראה. אז, צריך ביאור מה אומר. אף אם לא נאמר כר”ן, ונגרוס כאן שאסור, עדיין צריך ביאור למה חלוק שבועה מנדר בזה, שבנדר אומרים שלא קיים תנאו. ותחשב.
** ולענין -
ואי הכי היכי פסקינן- מניח שהכלה כמותו בכל מצב. עיין לעיל, שדן בזה.
** נדרי הבאי -
ר"ל שכיון שתנאי שלו יתקיים, צריך לומר שלא רצה שהפירות יהיו אסורים, שלמה להו לומר, אז, לשון תנאי. ויש לדון, שבין כך ובין כך, צריך לומר שעשה תנאי זה לחנם. אז, צריך ביאור מהיכי תיתי שלא רצה שיחול על פי התנאי; נמצא שאין הוכחה שלא חשב מה שאמר. ותחשב.
** כך שבועת -
נמצא שכשאדם אומר שבועה ולא עושה בזה שבועה, נקרא שבועת שווא, ולא רק כשאדם עושה שבועה שאי אשפר להתקיים.
** כו. לא נחלקו -
מעניין מה שאומר, שנמצא שמחלקת הוא איזה יותר חשוב, אף שכאן שניהם נכונים, ואז לא חולקים איזה יותר חשוב בציור כזה. ותו"ת.
** כט. ותב הרשב"א -
לכן מקשה לבר פדא- יש להעיר שאף בלי זה, הקושיא יותר חזקה לפי בר פדא, שרהי אי אפשר לו לומר ששניהם בקדושת דמים. ותו"ת.
** ואף הרשבא היה חוכך -
יש להעיר שנראה שזה מטעם אחר ממה שבאר רן לעיל.
** הכא נמי -
אין דין זה כל כך פשוט לכאורה, שהרי גמרא בערכין דן בכעין זה, ורק אומר שבוודאי אי הקדושה מתפשטת ונעשה קדושת הגוף בדבר שאינו ראוי (כמו בעל מום), כשקידש רק אבר אחד. לכאורה, סובר של צריך שרק קדש אבר אחד. ותחשב.
** וכתב הרשב”א -
עיין במה שאומר שממה שדן רבי יוחנן כאן אליבא דבר פדא.... יש להעיר שלכאורה יוצא מן הירושלמי שרבי יוחנן הוא החולק על בר פדא.
אולי סובר שירושלמי חולק על הבבלי, אבל ק"ק למה יניח כן, ולא יאמר שרבי יוחנן רק מבאר בר פדא, ולא אומר כמותו. אולי מניח (ואף בזה, ק"ק למה מניח כן) שרבי יוחנן חולק, אבל רואים מכאן שסובר שהלכה כמותו. ותחשב.
** לא: שהיא שקולה -
במשנה שלנו, אין זה בגירסא. עיין בעוז והדר, שמבאר את זה.
** ואומר והיה -
הענין הוא שמניחים שערל ר"ל ערל ממש, אם לא שכתיב ערלי לב באותו קרא. אז, חושבים שאולי ר"ל ערלי לב, ואז אי אפשר להביא ראיה ממנו. ותו"ת.
** לב. שנתעסק -
בין כך ובין כך, נמצא שנתרשל. יש לדון למה זה יותר קל לומר, וגם יש לדון איך ידע שריב”ק לא כיוון לומר זה. (שוב הבנתי שזה הערה על גמרא, והיה לי לכתבו שם.)
** שנתעסק -
רק קשה לשיטתו, אבל אם לא נאמר כמה שאמר לעיל, יכולים לומר שרק יום שלישי הוא יותר כאב, ואז היה כל כך קרוב שלא היה צריך ללכת עוד שלשה ימים. זה כעין מה שתירץ, אבל הוא יותר פשוט. ותחשב ותבין.
** לו: אלא -
אדעתא דנפשיה- צריך ביאור, שאילו רוצה לתת לו דבר, היה לו לתת דמי תרומה עצמו. אז, לא רווח כאן כלל. ויש לדון, שאולי לא יקבל אם לא בתרומה. ותחשב.
** לז. קטן -
עיין בר"ן. נראה שיש עוד בעיה, שלכאורה, ההנאה הוא מה שאינו צריך לתת שכר. אם כן, קטן, שלא צריך לתת כלום, לא נהנה. אולי הלימוד עצמו נחשב הנאה, כיון שיכול לתבוע בעדו ממון. ודחוק.
** לז: את דהוגד -
ואם תאמר ל"ל נוהגים כגמרא. ויש לומר שחוששים שהם טעו, ולא אנו. גם יש לומר שחוששים שמי שגרס את הגמרא טעה, ולא מי שגרס ס"ת שלנו.
** לט. משום דלא אדריה -
נראה שהר"ן כאן הוא לשיטתו, שכ’ לעיל שכשאומר "בני מילי" וכדומה, כוונתו לומר שכן הוא הדין לעולם, ונעשה כאילו…. אם כן, בוודאי כן אומר גמרא כאן. ותחשב.
** מ: אם כל
נהרות באים מפרת, אז נאמר שכולם אחד. אז, יהיה תלוי ברוב של אותו מים, ודין מים שלפעמים מכזבים יהיה תלוי במחלקת ראב"ד ורמב"ם, אבל רק אם נפסוק כאבוה דשמואל. וצריך ביאור.
** וכי תימא אמאי -
ויש לומר שחשש שרק פרת נתרבה, אבל שאר ימים לא מתרבים מימיו. צריך לומר שפשוט לו שמה שאמר לעיל לבאר את זה נכון הוא.
** מיהו איכא -
יש להעיר שלזה, היה יכול אבוה דשמואל להטביל את בנותיו שם.
** מא: תניא לא ירחץ -
נמצא שגוזר אף בימות החמה בגדולה, אף שיש שני סיבות להקל, והוא גזירה לגזירה.
** אבל לא מן התמחוי -
נראה שאולי מה שזה נחשב מהנה לו הוא מחמת כוונתו. וא"צ לזה.
** מו. אי אמרת -
ולא איפשיטא- לא הבנתי ל"ל אומרים שמה שמביא ראיה, ולא משיב עליו, נחשב שפשט הבעיה.
** מז. קונם -
לאו דווקא באותו מקום- יש לדון מהו, אז, הגדר. אולי הוא כל שנחשב ביתו. גם יש לומר שהוא כל מה שהיה לו אותו גודל, או דמיון אחר, לבית ראשון, ואף שהוא במקום אחר.
** מח: זימנים -
עיין במה שפירש. נראה שהענין הוא שכאן, רצה יותר שיבוא על ידי נחלה. אף שבוודאי לה לא בא, הרי יש דבר אחר שרוצה יותר. גם יש לומר שכאן לא רוצה אופן אחד של ביאה יותר (שלא רוצה שיבוא ממנו, כיון שלא בא על ידי ירושה). ותחשב.
** מט. ולענין -
עיין במה שכתב מגמ’ קידושין. נראה שסבר שמה שאומר גמרא שם שהוא פחות מפרוטה הוא מפני שלא נהנה בשווה פרוטה, שהרי צריכה להחזיר אותה. אין זה כל כך פשוט שם; ועיין שם בגמ’ ובראשונים.
** הנודר -
נראה ש"שלוק" ר"ל שלא מתבשל כדרך בישול שלו, וממילא כולל אם נתבשל יותר או פחות. עדיין ק"ק שיאמר אותו כשרק ר"ל אחד ממשמעויות שלו. ותחשב.
** נ: ומן -
צריך ביאור למה מפרש כל מעשה זה, אף שהובא בגמרא, ולא מבאר מעשה של קטיעא בר שלום (מסתמא, כיון שהוא מפורש בגמרא).
** נא: דלמא פלטיה -
עיין במש”כ. לכאורה, זה מטעים טוב עם מה שאמר ש”גדול” ו”קטן” תלוי בדרך בני אדם לדבר. ויש להעיר שכאן לא רק נקרא קטן מפני דמיון לראשון, אלא אולי היה קטן לנגד בליעת אדם. זה אומרש כשאומרים שדג בלע אדם, זה מכריח גידול שלו, שהיה מגודל אדם עד יותר מאד מכך. היה קטן בתוך אלו גדרים.
** נג: אבל במקום -
עיין במה שכתב. זה מחודש (אבל משמע כן מגמרא, שמשמע שרק משנה הדין באופן אחת, ולא בשנים). ואם תאמר למה הוא כן, שלא יהיה חלוק משאר שנה. ויש לומר שכיון שלא יכולים לאכול ירקי גנות אלא מחו”ל, יותר קל לאכול ירקי גנות. כמו כן, יש לומר שכיון שירקי גנות הפקר, יותר קל לאכול אותם. אז, אוכלים שניהם.
** נד: ולענין הלכה -
יחיד, דהיינו רשב”ג- יש להעיר שהכלל הוא שהלכה כרשב”ג בכמעט כל מקום. אין זה כל כך קשה, שכבר אמרו שכלל זה הוא רק במשנה, אבל לא בברייתא. אבל, יש להעיר, כאן שיטת רשב"ג הוא במשנה, ורק לא מונה את שמו במשנה. אם כן, צריך לומר שאף בזה, אין אומרים שהלכה כרשב”ג בכל מקום.
גי”ל שהלכה כמותו אף בכעין זה, ושאני הכא שהוא נגד הכלל שהלכה כר”ע מחבירו, ולכן נדחה. ותחשב.
** ולענין -
אפילו אסר שלושים יום- היה נראה לומר להיפך, שאוסר אותו כדי שלא יאכל, אף אם נתרפא. רק אם אומר נדר רק לזמן שבטוח שעדיין יהיו מכאיבים לו, יכולים לומר שבהכרח לא נדר מדג. ותחשב.
** נה. מאי דכתיב -
עיין במה שכתב. לכאורה, ר"ל שאמר כל דרשה זה כדי להודיע כן לו, והשאר בא אגבו. לולי זה, היה אפשר לומר שאמר לו כדי לומר שמוחל לו, שטוב להיות כמדבר, ושימחול לו. אולי כוון לשניהם, וזה פשוט, ולכן לא באר אותו הר”ן.
** מאי דכתיב -
נמצא שר"י עצמו ידע פירוש של הקרא, ורק שאל כדי שיבין רבא כשמזכיר את התירוץ. ותו"ת.
** נה: ואם אמר -
אם כן, מסתמא, “שנה” שאומר גמרא לאו דווקא, שלא יכול לחיות על האוכלים שלא אסר לשנה.
** סא: ולענין הלכה -
בנדרים- צריך ביאור מה אומר, שלכאורה, כוונתו לומר שכיון שזה בעיקר מקומו, יותר יש לסמוך עליו. ראשון, צריך ביאור מהו הסברה לזה. אולי ר"ל שאז דקדקו בו יותר. ותחשב. גם קשה שהוא סתירה בין קידושין לנדרים, ולמה מניחים שנדרים הוא יותר מקומו מנדרים. אולי הוא מפני שהוא ראשון, ואז עיינו בו. באמת, היה נראה לומר להיפך, שהכירו בסתירה בפעם ראשונה כשלמדו דבר השני. ותחשב. אולי הוא מפני שהסתירה שהוא יותר מפורשת (הברייתא והמשנה) קרה כבר בנדרים. ותחשב.
** סב: עבדא דנורא -
עיין בעוז והדר, שמוסיף “לישנא אחרינא.” צריך ביאור, שלפשט ראשון שאומר, הרי הוא משנה דיבורו, והיה לו לגמרא למנות אותו באלו מציאות. ודע שמוזר שזהו מה שדן רן בו בשני לשונות, שלא מזכיר כ”כ בפירוש בפשט ראשון למה מותר, ואז לאנראה שבזה דן. ותחשב.
** סה. והיכא -
מצוות המלך- אבל, אז קשה איך צווה אותם. ויש לומר שאין הכי נמי, עשה שלא כדין. ויש לדון, שיש גמרות שמשמע שהיה צדיק.
** והכא -
יש להעיר שבדרך כלל, אין לשמוע למלך במקום איסור. (אומר גמרא כן בפירוש; אולי בסנהדרין.) אבל, אולי חלוק כאן, שכל האיסור נגזר רק שלא במקום מצווה, ואז עשייתו אינו אסור.
** רבי יוחנן -
נראה שהוא כמו שפירש ר”ן על המשנה, והוא שיסוד של נולד הוא שאינו מצוי. אז, זה דומה לנולד במה שאינו מצוי.
** סז. קמ”ל -
מאי זו ואצ”ל...- לא הבנתי כל כך מה אומר. ותחשב.
** סז: ואיבעית -
עיין במה שכתב. יש להעיר שבאותו קרא, לכאורה מצאנו שהווייה ר"ל שהיה נשואין, ואז אולי כן אומר כאן. אז, אין הוכחה אלא ממה שכבר יש קרא לזה. צריך ביאור.
** סח. מיגז -
מפרש שאחד מן השנים יהיה מותר. כל חלות כזה מעניין, שצריך ביאור איך נבחור אחד להיות מותר. יש לדון אם יש אחד שיותר קל ליעשות מותר, או אם יש אחד שיש לאב יותר כוח עליו ואחד שיש לבעל יותר כוח עליו. (אם נאמר כן, יש לדון אם נדרה מלהגביה שני דברים ליום, והפר בעל, והגביה אחד, ושוב נדרה עוד פעם, ליום אחר, והפר בעל, והגביה האחר. אולי לפעמים זה נעשה של בעל, ולפעמים זה נעשה של בעל. ותחשב.)
** ולתנא -
חכם הוותיק- יש לדון אם זה אותו שהזכיר לעיל (סה:).
** עב: מצינו -
נגדיר את התירוץ. יש דבר שעושה החלות עצמו. יש דבר שנותן כוח לעשות החלות. הדרך להגדיר הוא כך: אם נעשה בזמן החלות, שמיד אחריו חל החלות, אז הוא ממין ראשון. אם לא, הוא ממין שני. אז, מפרש שצריך שבעל יש לו כל דבר שנותן כוח לעשות החלות. ותחשב.
** עג: ואיכא דילפי -
לא הבנתי את זה כל כך, שאם רק זכה אותו תורה לבעל באופן כזה- הרי כאן אינו בעל שלה. נראה שרק צריך להיות לו מקצת יחס בעלות, וכאן יש לו, ולהיות שנודרת על דעתו. ותחשב.
** עה: תא שמע -
עיין במה שכ’. לכאורה, נמצא שגמ’ הביא ראיה מסברה, ודחה שהלשון משמע כצד האחר. (לכאורה, יהיה עדיין אפשרות לבאר אותו, שאי לאו הכי, הסברה מוכחת שהלשון לאו דווקא.) זה שלו”ט מעניין.
** הא כדאיתא -
עיין במה שבאר. וצריך ביאור, שכיון שכבר באר שמה שיכול לבטל נדרי עצמו הוא, בעיקר, מפני שנמצא שהוא נדר טעות, אז צריך לדון. אם כן הוא גבי אשה (זהו “על דעת בעלה), אז תירוצו קשה. אם לא, אז קשה איך נלמד שום קל וחומר ממנו. ותחשב.
** עו: להקל ולהחמיר -
כמו כן מצאנו (והערנו עליו בשי”ח ש”י) בערכין (גבי קולא וחומרא בערכין).
** עח: אבל הרמבם -
היה אפשר להוכיח מגמ’ בפ”ק ברבינא ור”א. אולי העיר שם ר”ן כן.
** רב הונא -
אז, רואים שהיה ר"ה שלא היה ריש גלותא (והיה אחד שהיה ריש גלותא, בסוף כלאים).
** עט. מתיב רבא -
עיין במש”כ. כ”כ ראשונים אחרים במק”א. יש להעיר שרואים מזה שאף שאומר “תיובתא,” לא יודע בברור שאי אפשר להיות תירוץ לאותו קושיה.
** פג. א”ל אביי -
עיין במה שפ’, שרוצה שיאמר לשון מיוחד. ק"ק ל"ל אמר אביי אותו לשון. נ’ שאותו לשון היה משמע כן, ואז היה לו לרבה לומר כן. אבל, כיון שכבר היה מי שלא אמר כן, רצה אביי להדגיש כן, ואז אמר לשון שאומר אותו יותר בפירוש.
** פה: אר”א -
אם אין לו מקור, צריך ביאור למה מקשה.
** פז. והל’ -
עיין בפשטו הראשון. לכאורה, אומר שאין משמעות מילה שלם בלי שיהוי אחריו. אם כן, צריך ביאור איך מהני גבי קריעה. ותחשב.
** פז: שמעתי
שהרא”ש כאן הוא יסודי. ותו"ת.
** עיין בר”ן.
לא כל כך פשוט לי מה בכלל חצי ידיעה ומה נחשב שאינו ידיעה כלל.
פח.
** מתני’ -
עיין בפשט ראשון שאמר. לכאורה, אומר שקנין בא רק כשהיא אוכלת, ואז אין בעלה רוצה אותו עוד. יש לדון למה צריך להקנות כלל. גם צריך ביאור מה אם קונה דבר בממון (שמס’ כן תעשה). גם צריך יבאור למה צריך דיבור ראשון. ותחשב.
** צ: השמים -
עיין במה שפ’. זה רק אפשר למה שמסיק גמרא שאין בנ"א שיודעים כן חוץ ממנה. ותו"ת.
* Footnotes
[fn:1] ויש לדון אם שייך לזה כלל מה שדנים אם מעשה ודיבור הם פרטים במחשבה (מחזקים אותו) או סיבות בפ”ע.
[fn:2] יש להעיר שאילו היה הדיון אם כלל זה נכון, לא היה אפשר לחלק בין פאה לצדקה (עיין בד”ה יש יד לצדקה). ר”ן לא מזכיר טענה זה, ואז נראה שלא סובר כן. אז, לא נראה שכך היה הדיון לפי הר”ן.
