* ב.
** גמרא עידיהן -
יש לדון למה יום טוב שלהם כן:
1. מעידים ע"כ, וגם באותו היום עובדים ע"כ. אז, יש שום יחס. דחו"מ.
2. מעידים על מה שעשו באותו יום.
** רש"י לפני -
וכולהו- קשה למה חוששים לזה כיון שהתיר ה’ את המצוות. ויש לומר:
1. העיר מ.י.ב. שאולי יש מצווה שלא לגרום עבודה, דומה למצוות "לא ישמע על פיך.”
2. אולי כיון שגורם עונש לגויים, אסור הוא. יש להעיר שאם נאמר כן, ונאמר שאיסור של "לפני עור" הוא מפני שגורם רע לאדם שעובר, הוא דומה לפשיטות לשונו (שמדבר על היזק גופו).
3. אולי עדיין יש ס"ר.
שוב ראיתי שרש"י לקמן דן בזה. נראה שאומר כצד 2 (וגמרא דן אם הענין הוא ראשון או לפני עור. ודע שממה שרש"י לא הקשה אלא על צד של לפני עוור, משמע שאין איסור לגרום ששם עבודה זרה נשמע על פי מי שאינו מצווה. ויש לדון, שאולי חכה עד הסוף, שאף שם היה צריך פירוש, ושם פירש.).
* ב:
** גמרא חשוב… מקמי דליפוש -
צריך ביאור למה חשיבות של רומי עושה שטוב שיצטדק דינו (ושידון קודם שיפוש חרון אף). ותחשב.
** כל מה -
משמע שאין טוב במה שגוי עושה מצווה שלא לשמה. אם כן, כשרש"י בר"ה אומר שהטעם שאין “סלע לצדקה בשביל…" טוב לגויים הוא ש"עובד כוכבים אם אין מטיבין לו כגמולו קורא תגר,” צריך לומר שאינו אומר שבעצם, יש טוב בשלא לשמו, אלא שיש רע אחר, והוא שאולי קורא תגר בה’ אם לא ישמע לו, שהרי כאן לא התנו עם ה’, ואין מה לקראות בו תגר (וכמו, כן, לכאורה, ב"כדי שאזכה…"), ואלא צריך לומר שהוא שכיון שכן, רואים שהוא כולו שלא לשמה, ואז אינו טוב, וכדי שדבר יהיה טוב, צריך להיות קצת שלא לשמו. ותחשב.
ויש להעיר שכמובן ק"ק איך נאמר שאין שלא לשמו טוב לגויים, שהרי מאמר שבו גמרא אומר שהוא טוב הוא מימרת ר"י ש"מתוך שלא לשמה…,” וזה גופא נלמד ממעשה של בלעם, שהיה גוי. ותחשב.
אז, הניחא אם היינו אומרים שיש טובה של שלא לשמה, אלא שהיה קורא תגר, אולי טוב, שעדיין יש אותו טובה, וזה מוכיח. אלא אם נאמר כמש"כ, משמע (ואולי יש לדחות שבכל של"ש יש רעה ממילא, אבל רק אם כולו של"ש. ודחוק.) שאין לו סיבה לטובה זה. ותחשב.
** כסף וזהב -
קשה, שהם הרבו אותו. משמע שלא היה להם בחירה על מעשים הנוגעים לכסף. וצריך ביאור.
** דהא חשיבא -
העיר מ.י.ב. שצריך ביאור איך רואים מקרא זה שהוא חשוב (שמה שבא שני בקרא לא מהני, שרומי באה אחרון).
** סתרי -
ואם תאמר, הרי לא היה זה טענת ה’. ויש לומר שמפני זה הקפיד ה’ עליהם לטעון יותר טענות. גם יש לומר שרק ראו רומי באה ויוצא בפחי נפש, ומסתמא ידעו מה היה רומי רוצה לטעון (שפשוט שרק זה יכול לטעון), ולא ידעו מה טען ה’, וחשבו שהוא שסתרו בית המקדש. גם יש לומר שממה שסתרא בית המקדש, ידע ה’ שלא היה לשם שמים, אבל על פרסיים, לא היה אותו הוכחה. ותו"ת.
** רש"י מקמי דליפוש -
קשה, שגם יש לומר שעשו זכויות, ואז זה ייתן לה’ רחמים יותר. ויש לדון אם כן הוא, שאולי ה’ מתחיל ברב רחמים עד כדי שרק יכול למעט ולא להרבות יותר על זה. (גם יש לומר שכאן, על כל פנים, מסתמא לא ירבה רחמיו).
* ג.
** גמרא מקבלים -
העיר מ.י.ב. שזה קאי על קבלה, ולא קיום. ויש לומר שאם לא קיימו אותם, נמצא שלא היה קבלתם קבלה. גם יש לומר שאף אי הוה קבלה, כל טובת קבלה הוא רק קיום, ומה שיבטלו אם לא קיבלו צריך להיות מפני שלא היו מקיימים אותו. אם כן, אם לא קיימו אותו ממש, בוודאי לא היו שמים וארץ מתקיימים.
ועיין בתוס’. וצריך ביאור, אז, איך לתרץ לקושיה זה.
** יש אב -
שהרי, גמרא בב"ב מסיק שאין פסול קורבה חשש משקר.
** יבא בלדד -
צריך ביאור מה שייך. ואולי מעיד באיוב. קשה למה לא אומר כן. גם, אז, צ"ל למד"א שהיה איוב ישראל.
** רש"י לומר -
בב"ק, מפרש רש"י שאין חיוב, ואף על פי כן, יש עונש. משמע שעונש בא על ס"ר, ואז אין צריכים צווי, כי אם להגיד שהוא רע. ויש לדון, שאולי ענש אותם כדי שלא יהיה חוטא נשכר. ותחשב.
** אברהם -
מעניין שזה מהני לקיום שמים וארץ וכדומה, שהרי לא היה שייך לקבלת התורה. ואולי איה"נ, ורק שייך לטענת גויים (שהרי, היה אב של בני ישראל). ותחשב.
** בראש גגו -
גם אומר בב"ב שרוב תשמשתם בחצר. מסתמא הם מיני תשמיש חלוקים. ויל"ד.
** תוס’ נוגעים -
ע’ במה שהקשה. ואינו כל כך קשה, שהרי יש לומר שה’ הבטיח שיחרב אותם אם לא מקבלים ומקיימים בני ישראל את התורה, ואז דן ה’ אם מקיימים (שהרי ה’ דן בכל דבר, ולא רק עושה, אף שיודע את הכל). אז, בזה דן אם ראויים הם להיחרב. ותחשב.
* ג:
** גמרא כיון שרואה -
משמע שתמיד רואה כן. ותו"ת.
** שומר נפשו -
פ’ מ.י.ב שמדייק מלשון זה, שמשמע שנפשו- דהיינו, חייו- צריך שמירה.
** רש"י ובלילה -
שירות- עיין בגמרא ברכות שם, שאין זה כל כך פשוט.
* ד.
** גמרא אשר לא יעזוב -
קשה איך דבר יעשה שלא יעזב להם שורש בעולם הזה, כיון שמיירי אחר עולם הזה. ואולי הוא רק בימי דין של עולם בזה. גם יש לומר שהוא אומר דבר אחר הנעשה לרשעים, ואף קודם לכן. ותו"ת.
** כאן ביחיד -
יש לדון אם רצה לומר שקם כיון שהחמה הוא על ציבור או שקם כיון שהוא חלק מציבור, אף שעליו לבדו חם ה’.
** כאן ביחיד -
הקשה מ.י.ב. איך קם אדם הראשון. יש לומר שאולי הוא, בפני עצמו, היה ציבור. מ.י.ב. ת’ שאף בלי זה, אולי חווה היתה ציבור עמו. גם ת’ שלא זעם אז (שהרי, לא היה עבודת כוכבים, כמו שיזכיר גמרא לקמן שזה מזעים אותו). ותו"ת.
* ד:
** גמרא אלא ליתן פתחון -
רש"י מפרש שר"ל שה’ גרם שיעשו כן כדי…, גם היה אפשר לומר שאומר שבני ישראל כיוונו כן, ועברו עבירה לשם שמים.
** רש"י לבי חלל -
עיין בב"ב, שחולקים (סוף פרק קמא) אם זה, באמת, אומר שלא היה לו ייצר הרע.
** מוספי כל שנה -
יש לדון מה בא לומר:
1. אולי בא לבאר למה הוא רק במוסף של ראש השנה. יש לדון אם היה צריך כן, שאולי רק בראש השנה, שהוא יום הדין, יש חשש זה, שהוא נדון ביותר.
2. אולי בא לבאר איך נאמר שיש דין במוסף של ראש השנה, שהרי מוסף אינו תפלה שמזכיר דין. מעורר רש"י שזה רק בשאר מוספים, אבל מוסף זה מזכיר דין.
** תוס’ רגע -
העיר מ.י.ב. שמוכרח שהולכים בתר זמן התחלה ממה שיש מושג של תפילה עם הנץ החמה, אף שהוא זמן ארוך. יש לדחות:
1. אולי הוא זמן ארוך (ורק צריך להיות קרוב לאותו זמן הנצה). כן אומרים כמה פסוקים בנוגע זמן להתחיל.
2. אולי כיון שאמר תורה שיש להתפלל בהנץ החמה (זה מניח שיש מקור לזה, ואינו רק מפני שיודעים שהוא זמן הטוב לתפלה), מוכרח שהוא זמן טוב להתחיל בו תפלה. אבל, אולי שאר דברים אינם כן.
* ה.
** גמרא לאותן העומדים -
יש לדון למה אינם בכלל, “להן.” ת’ מ.י.ב. שאולי כיון שהיו קטנים, לא היו בכלל. גם יש לומר שר"ל שכיוון לעוברים שהיו אז.
* ה:
** גמרא לתת -
לכאורה, גמרא כאן דן בצד שחייב מחמת איסור של לפני עור. יש להעיר שמעניין שיהיה רק על בהמה, אף שמשנה לא הזכיר בהמה. ותו"ת.
** שואלים -
מעניין שמניחים שזה מפני קרבן פסח.
* ו.
** גמרא תמים כתיב -
עיין בתוס’, שתולה אותו במה ידע נוח (ולכן לא מביא ראיה ממה שחי אחר כך). קשה, אז, איך ידע שאמר ה’ עליו שהוא תמים. אם ידע, ק"ק למה לא נכנס בכלל "מקצת שבחו לפניו.” ואולי יש חילוק בין שבח הנאמר לפניו לשבח שנודע לו. ותו"ת.
** חשיב -
רצה לומר, שאז אמר ר"י דין על יום אחד שני פעמים, ולא נניח שעשה כן.
** אידם של עובדי -
לכאורה, הוא מפני שלשון "אידם" מיותר. ויש לדון, שאולי אומר אידיהם וגם…. לכאורה, כיון שלא כתיב שם "ו,” לא מניחים כן. ותו"ת.
* ז.
** גמרא אין סדר -
קשה, שעדיין יהיה כיחיד ורבים, כמו שאומר תוס’ ביבמות. ואולי יש צד שרבי מאיר יותר מסתבר כאן. וצריך ביאור.
ואי בעית אימא- לכאורה, רצה לומר שכיון שהיה כל כך בהיר לו, מסתמא לא חזר ממנו.
** רש"י מחלקת -
קמו רבנן- רש"י בכ"מ (ריש ביצה, ריש שבועות, פרק החובל) אומר שרבי סתם משניות; מוזר, אז, למה מזכיר כאן רבנן.
* ז:
** גמרא מאן חכמים -
נמצא שכשאומר כן, לא רק רצה לומר, “כמי סובר…,” אלא ממש מי הוא. מעניין שיאמר לשון רבים על יחיד זה.
** בדגנניתא -
יש לדון אם חולקים במציאות, במה נחשב ראוי די, או אם נחשבים חד מין, ואותו מין ראוי, אז. ותחשב.
** בר מינה דההיא -
קשה, ששאל איך לעולם הוא נגד הכל, והשיב לו זה, שאינו נגד הדין, ודחה שאינו נגד הכל. צריך ביאור, כמובן.
* ח.
** גמרא אם בא… יוה"כ -
משמע שאי אפשר בתוך תפלה- לכאורה, מפני שהוא הפסק.
** אמר -
יש שגורסים בעי. אם כן, צריך לומר ששאל ור"י וריב"ל השיבו. גם יש לומר שר"ל "אמר,” כמו שמצאנו שירושלמי עושה כ"פ (ואמוראים אלו הם מא"י).
* ח:
** גמרא איקלע -
צריך לומר שאף שכבר אמר, עדיין צריך שלא לאכול.
** הכי -
יש לדון אם התנו כן על מלך ראשון, או אם התנו כן על כל מי שיבחר מלך (כל מלך יבחר מלך אחר, ואם בחר מישראל…). ותחשב.
** רבי -
עיין ברשב"ם פסחים (קיח:). ויש לדון איך מפרש מה שאמר ששאל לשלש דברים (לצד שהיה בפעם אחת). ותחשב.
* ט.
** רש"י תנא תוספאה -
לא הבנתי, שהרי לעיל אמר פשט אחר. ותחשב.
* י.
** גמרא ממאי -
קשה, שנלמד גופא ממה שלא היה הכותב טועה (שהוא אותו הכרח של אם מנו משעת יוונים). ותחשב. ויש לדון, שכאן צריך שני הנחות (שלא טעה, וששאר בני אדם מונים כך). אז, יותר קל לומר שטעה. ותו"ת.
** ממאי -
עיין בשיח שי שהערנו שמצאנו נפק"מ מדרש שעליו חולק רמב"ן. אז, אי אפשר לומר שחולקים ראשונים על תנאים ואמוראים בביאור קראי רק מפני שרק אגדתא הוא, ואין ממנו נפק"מ.
אין זה נכון, שרש"י מבאר שהחשבון הוא רק שיש אלף שנה מזה לזה. אם כן, אף אם יציאת מצרים היה בשלש אלפים וחמש מאות שנה, היה החשבון שווה. ותו"ת.
* י:
** גמרא מלכותא קטיעא -
נראה שלכן נקרא בר קטיעא.
** רש"י חיטי -
כמובן, לא הגביהו אותו (וק"ק למה לא חש שיגביהו). ואולי לא היה דרך אחר לו, וזה היה הכי טוב.
** בלא מיכסא -
משמע שיש טוב במילתו, אף שאינו גרות טובה, שאין שלש עמו. ואולי אין טוב, וטעה.
* יא.
** גמרא ואילו הקב"ה -
יש לדון אם זה מראה חביבות ישראל או טובת ה’.
** שורפים -
הקשה מ.י.ב. למה אין זה בל תשחית. נ’ לי שהוא כעין מה שאומר גמרא בשבת שיכול אדם לקרוע כדי להראות שהוא בכעס.
* יא:
** רש"י קרקפלו -
עדיין- יש לדון אם אמר כן על זמן גמרא או זמניו. נראה כצד ראשון, שלא נראה שהיה יכול לדעת על זמניו. ועיין במסורת הש"ס. שם קאי על זמן רומיים.
** מעניין
שאומרים שבני רומי טעו בלשונם, שהוא ממש דומה למה שעשה יעקב כשזייף ("אני בכורך עשו"). נמצא שהם טעו לשיטתם, ואנחנו עונים לשיטתינו.
** בגולה -
מניח שהוא איסורים דרבנן. עיין לקמן (ע"א) שרש"י דן בזה, אבל אומר שהוא רק אם פשוט שהוא מתיבת עצמו. ותחשב.
* יב.
** גמרא ששפתו -
יש לדון, שאין כל כך ראיה, ששני איסורים הם, ושני מציאותים. ותחשב.
* יב:
** גמרא מטיל מום ממש -
עיין ברש"י שקורא את זה קושיה על רבא. לכאורה, הוא אף קושיה על אביי, שהיה לו לתרץ כן (לומר שאסור הוא משום שמטיל מום). ויש לדון, שאולי לאביי יש קרא יותר מפורש.
** ממעטי -
יש לדון למה רוצים בזה:
1. לא רוצים שגויים יהיו חזקים, אולי יעשו רע לנו.
2. לא רוצים שיהיה לנו כל כך ממון לתת לעבודה זרה.
* יד.
** גמרא זה וזה -
לכאורה, צריך לומר שאמר "לבן ואדום,” שהרי אמירת זה אינו בעיה. עיין ברש"י שכן אומר.
* יד:
** רש"י קורייטא -
יש לדון למה; שאולי לא הכירו באותו שם, ולא ידעו שהוא אותו מין.
** מפני שחשודין -
אף בזה יש לדון במה שהותר להם מצוותם.
* טו.
** גמרא ושמעה -
נמצא שיש איסור רק אם ישראל מנהיג אותו (ולא אומרים שכשגוי עושה כן בבהמה שלו, נראה כאומר לגוי לעסוק בבהמתו). אם כן, יש עוד תירוץ לומר בשאלה. אם כן, ק"ק מה מסקנת גמרא שיכול להיות בשאלה. ויש לומר שאמר זה רק לרווחא דמילתא, ואין צריכים שיהיה משמיעתו. גם יש לומר שחוששים שמא ישראל ינהיג מה ששאל.
** לא קניא -
צריך ביאור מהו דיון זה. לכאורה, אי אפשר לומר שיש צד שיש לו קנין הגוף, שרש"י אומר שלעולם כשאומרים קנין לזמן, הוא קנין פירות[fn:1] (ויש לדון, שאולי זה רק מפני גמרא זה). אם כן, צריך לומר שיש רק פירות. אולי דן אם הוא כקנין הגוף- אבל קשה, שזה כבר מחלקת ידוע. אולי שאני הכא שכבר זוכה המשאיל בזכות, והוא שמשאילו. ויש לדון, שכן הוא בנותן מתנה, שיש לו זכות של נתינה. ותחשב.
** רש"י יאכילנה -
אומר שני דברים:
1. אין לו תובעים.
2. הוא כנותן לכוהן זה.
לכאורה, צריך שני כיון שצריך לתת לכוהן. צריך ביאור למה צריכים ראשון. ותחשב.
** אימור -
טמאה- משמע שלא אוכלים במהות טמאות. ויש להעיר שיש, היום, בהמות טמאות שאוכלים, כמו חזיר וארנבת, ויש שאין אוכלים, כמו סוס.
* טז.
** גמרא דמגנו -
יש לדון מה זה אומר:
1. אין חוששים שיבוא לנו רע, שהם שומרים אותנו.
2. אף שחוששים שאולי לאחר זמן יבוא לנו רע, כדאי הוא, כיון שכאן באים לנו טוב ממנו.
** שור של פטם -
אם הבעיה הוא שמא ישהו ליה, קצ"ב. אם חוששים שיראו אותו כשהוא מפוטם, צריך לומר שבני אדם לא יכירו בחילוק שבין מכירת שור פטם למכירת שאר שוורים. אם כן, בלי ראייה, יהיה בעיה במכירה עצמו. אם נאמר שיראו אותו לאחר זמן, כשאינו פטם, צריך לומר שמניחים שידעו עדיין שמישראל בא. ותחשב.
ונראה שאין בעיה זה בשבורה, שאפשר אדם לראות בשבורה מיד לאחר המכירה, ושלא להכיר שהוא שבורה. אבל, נראה שבשור פטם אינו כן, שכולו גדול. ותחשב.
** רבי מיעקר מילתא -
אם כן, לכאורה עדיין יש ראיה, שרבי רצה שלא יתנו אותו שור. לא הבנתי מה שאומר רש"י שביטלו אותו מפני שהוא מנהג בזיון, שזה מבטל קושיית הגמרא (ולא משמע שכך דוחה המסקנא).
** בית רבי -
נראה שלא היה רבי עצמו (ולא היה בזמן רבי), שהיה רבי קרוב למלכות של ימיו.
** רש"י שור של פטם -
גם היה אפשר לומר שאז הוא עומד לשחיטה. ותו"ת.
** מרחצאות -
ק"ק למה עשו מרחצאות כן, ולא רק עשו קרקע במקום נסרים.
** פרכוס -
דבהמה מסוכנת- לשונו משמע- ויש לדחות- שענין פרכוס הוא שאם לא מפרכס מגלה שהוא מסוכנת ומסוכנת אסור. ותחשב.
* טז:
** גמרא רב נחמן -
מעניין שמקשה ר"נ לרבינא ור"א. אולי היה רבינא ור"א אחר (מצאנו אחר מוקדם) או ר"נ אחר. אם כן, נמצא שני סתם ר"נ. גם יש לומר שר"נ האריך ימים הרבה.
** רש"י פתיא אוכמא -
מגמרא שמביא רש"י (כלי מגונה) משמע שאינו מפני שמצטער אותו בתורה, אלא מפני שאז דעתו שפלה. ותחשב. גם נראה שעל פי מה שאמר רש"י שרק לא כבסו בגדיהם, ולא שהיו מכוערים, יש לבאר איך היה ר"י וכדומה ת"ח כ"כ גדולים, שאולי היו מכוערים אז.
** פתיא אוכמי -
עיין במה שפירש. גם יש לומר שהיה על שם שהיה "קטנא כרוך…,” שהיה שחור מן האש.
* יז.
** גמרא לכהן גדול -
צריך ביאור למה הוא רק של כהן גדול. לכאורה, כל בית המקדש היה לו בית הכסא, ואז היה לו לשאול אף לבית הכסא שאינו לאיש שהוא כל כך מכובד. אמר מ.י.ב. שאולי בזה היו נותנים ממון ביותר זמנים. לא נראה כן, שלא היו משתמשים בו כל כך. ותחשב.
** הרחק -
נמצא שהוא מדה כנגד מדה, שלא הרחיק ממינות בענין זונה, ואז נתפס מרשות. ויש לדון אם מיים תפסוהו בפני עצמם או מרשות. ותחשב.
** ואם ישובו -
אין זה משיב לקושיה, לכאורה, שהקשה איך שייך ישיגו אם לא ישובו, ומת’ ששייך אם ישובו. וצריך ביאור.
** ורבנן -
משמע שזה היה דבר מינות, ולא רק רע כיון שבא ממין.
** רש"י ופליגא -
גם יש לומר שלשון שני, שדורש שכולל עבירה, חולק עליו.
* יז:
** גמרא ונקבל -
משמע שאף שבטוחים שתורה ישמור עליהם, ואז לא היו צריכים אף לבחור שלא לזנות, בא להם שכר. ויש לדון. ותחשב.
** אי סייפא -
יש לדון, שריש לקיש עשה שניהם. לא מסתבר לומר שכיון שהיה לפני זמן לא יהיו ממיתים אותו עליו. יותר נראה שאין הכי נמי, אלא שלא ידעו רומיים שיכול להיות כן. כמו כן יש לומר שרק רצה לומר שלא מצוי שיהיו שניהם באיש אחד.
** מדהא ליתא -
היה אפשר לומר כן, אז, על כל הטענות. ואולי היו אחרים תובעים אותם טענות. ותו"ת.
** קא שבקת -
קשה, שאסור לישראל. אמר מ.י.ב. שאולי מיירי כשהכה אותו בשן ועין.
** כאשר -
לכאורה, מה שלא אמר כר"א הוא שהיה ידוע ביותר מה עשה, ולא היה מקום לשקר וליצול את נפשו.
** רש"י קרו לך רבי -
מעניין שאין זה חלק מן עליל של תלמוד תורה. ונראה שאחד הוא שלמד ואחד הוא שלימד.
* יח.
** גמרא נזדמנו -
אולי רצה לומר שזכרו אותם פסוקים או שממש נפלו לתוך פיהם (וצ"ב איך נדע שכן קרה).
** פתח פיך -
צריך ביאור, שהיה מדבר.
** קפץ -
צריך ביאור איך לא נענש על מה שהמית את עצמו.
** זילא -
מעניין שלא חששה לזילותא של אחותה או לעבירות של אחותה. יש לומר שלא חש שתעבור עבירות. העיר מ.י.ב. שרואים שהיה ר“מ חושש. ויש לדון, שרק חשש מפני שאם כן, לא היה נס נעשה, ואולי היה נהרג. ותחשב.[fn:2]
** דשתנא -
מעניין שהיו נוהגים דיני נדה. אולי הוא בכלל דינים שהיו חייבים לקיים. יש לדון, שלא הקפידו עליהם, והופקרו. עיין בתענית גבי ההוא שהיה בן עולם הבא, שמבואר שהיו נוהגים בו גויים. עיין בגמרא נדה שאומר שהוא מצוות שכלי, כדי שלא ישנא איש את אשתו. יש להעיר שאין טעם זה שייך בזונה.
** מאי אעביד -
הק‛ מ.י.ב. איך סומכים על הנס.
גם צריך ביאור למה סומכים רק אחר חצי, שאם סומכים, נסמוך בכולו, ואם לא, וכל מה שיש לו צריך ליתן, לא ישאיר בידו חצי. ותחשב.
** רש"י להתלמד -
מ.י.ב. הקשה למה אומר רש"י שמותר במילי אחרי כגון אלו, ולא כמו הוגה את השם שלא בפרהסיא, כמו שמבואר מכאן. ויש לומר שאלו הם ציורי דברים שמותרים בפרהסיא. ויש להעיר שאותו מעשה של סנהדרין היה רק בין ר"א לר"ע.
* יח:
** גמרא ואם נתחשב -
לכאורה, כבר באר זה.
** נופל -
חושב אני שגמרא בב“ב אומר כן על מי שלא לומד. כיון שמתלוצץ בטל מתורה, כבר יודעים זה. ותחשב.
** רש"י הא למדת -
ק"ק מה לומדים מזה, שלכאורה פשוט הוא שבזה מבטל תורה. אולי אומר שאי אפשר בו ”ביטולו זוהי יסודו.“ גם יש לומר שאומר שמבטל אותו לאחר זמן. ודחוק.
* יט.
** רש"י רב ששת -
נראה שדומה לעוף כיון שהוא מעט מעט שאוכל.
* כא.
** גמרא חובת הדר -
יש לדון מהו הענין:
1. קצת אמר מ.י.ב. שאולי הענין הוא שמסתמא הוא ידור במקום אחר, ואז יחייב במזוזה.
2. נראה יותר שהוא למאן דאמר שתבואה של גוי חייב במעשר, ואז התבואה נאכלת בטבל לגוי. זה רע, אף שאין גוי מצווה עליו.
** כיבוש -
יש לדון, אז, למה אין דינו ממש שווה לדין א“י.
** הלכה -
יל“ד למה צ“ל כן, שלעולם הלכה כר“י נגד ר“מ. אולי לא סובר כאותו כלל. ותחשב.
* כב.
** גמרא לפני עוור -
ק"ק ל"ל אמר שכותי הוא גוי, ואז אין לפני עוור עליו, שלא מצווה.
* כה.
** גמרא כשם שעמדה -
לכאורה, כך עמד לחזקיה כשנתרפא.
** אתיא -
יש לדון אם הלימוד הוא שאף במעשה של אותו קרא החמה הופסק או שאף למשה, שגביו כתיב האי קרא, הופסק החמה. ותחשב.
** רש"י דכתיב -
סתם מלחמה- לולי זה, היה נראה לומר שדורש שהלחמו ראשון כיון שידעו מלחמה יותר טוב. אז, מסתבר שלימדו לבני ישראל מלחמה.
* כז.
** גמרא וכי היכן -
מעניין שלא חושש שיש איסור במה שעושים לו דבר ומכוונים אותו לעבודה לע"ז. לכאורה, יש שני בעיות:
1. נעשה לו עבודה שהוא ע"ז. אולי אין בעיה בזה.
2. על ידו נעשה ע"ז, ונמצא שגרם ע"ז. אולי אין זה בעיה (אבל לא נראה כן מפרק ראשון), ואולי מניחים שהיו עובדים בדרך אחר בלי זה.
** המול ימול -
ואין לומר שדורש מזה לאפוקי גוי, שאינו מל, שהרי רבי יהודה שסובר שצריך להיות לשמה, סובר שגויים מותרים למול. ותו"ת.
** מנין למילה -
צריך ביאור ל"ל יאמר הקרא שאומר ברייתא לעיל.
** בערלי ישראל -
ואם תאמר הרי הקרא, כשאומר שלא לאכול ערל קרבן או כדומה, קורא להם ערלים. ויש לומר ששם שאני, שפשוט שמדבר בערלי ישראל, שבין כך ובין כך, גוי לא היה אוכל (יש לדון אם דין זה נכון). אם כן, כאילו פירש שם.
** כמאן דמהילא -
ר"ל שהיא הותרה, שאין לה סיבה. אם כן, צריך לומר שמי שלו הוא פקוח נפש לא הותרה אלא דחויה. ותחשב.
** לאיניש אחרינא -
יש לדון למי. אולי נתנה לעבד (שלכאורה, יהיה כשר אף אם אשה לא כשרה, שהרי הוא נימול). אולי נתן למשה. לשון גמ’ לא משמע כן. גם י"ל שהיה יוצא מן הנחש רק אחר שהתחילה. יש לדון. גם יש לומר שנתנה לבנה אחר. יש לדון, שאינו בר דעת. תלוי, אז, במחלקת לעיל. יש לדחות שציפורה היתה הגדול עומד על גביו. לכאורה, זה יהני.
* כז:
** גמרא שיולי משאיל -
אפשר שזה אף אם אינו רופא מומחה, שלא מזכיר גמרא שהוא רק במומחה. ויש לדחות, שאולי ממה ששואלים אותו, פשוט שהוא מומחה, ואז אין צורך להזכירו.
** ופורץ -
אמר כן כדי שיידעו שלא נשכו נחש מחמת עבירה על דין דרבנן. ואפשר שמוכיח את זה ממה שלא היה עובר על דברי חבירו אף עכשיו. ויש לדון, שאולי אחר נשיכת נחש, למד תוכחה.
** דמשכה -
יש לדון אם חשש שהמין ימשך אותו, או שהמין הוא יותר רע מפני שהוא נמשך. ותו"ת.
* כח.
** גמרא דרי -
רש"י מפרש שהוא שורות שינים. אם כן, יש דם בין שורות שינים. צריך ביאור מה זה אומר, שאין שורות של שיניים קרובות. אפשר שר"ל שהם שיש בגו"ם שבין שני שורות. גם ראיתי כושי אחד שהיה לו הרבה שורות שיניים. אולי בזה מיירי.
* כח:
** גמרא עין -
העיר מ.י.ב. שלא אומר שמתה, אלא שפקע עינה, ואז קשה למה יוצא מזה שהוא סכנה. ונראה שזה מבאר כשאומר שעין ולב תלויים, אבל צריך להוכיח ראשון שהוא רע לעין.
** לדידך -
יש לדון למה. אולי הוא כעין "שוויה אנפשיה.” צריך לדון בביאור זה. ותו"ת.
* כט.
** גמרא מראה -
העיר מ.י.ב. שק"ק למה מותר לאיש לראות במראה. אולי זה רק באשה. גם יש לומר ששאני כאן שלא רואה בדרך אשה, לראות יפיתו. גם יש לומר שלא רואה, אלא מניחו אצלו. גם יש לומרש הוא פקוח נפש. לא רנאה כן, שלא צריך להסתפר. ותו"ת.
* ל.
** גמרא פש להו -
לא הבנתי כל כך איך יביא נחש מים. אולי נתנו בפה שלו ופלטו. גם אפשר שהביאו בזנב שלו.
** אימת גברא -
הק’ מ.י.ב. למה צריך אימת גברא להוכיח להם לעשות כן. אולי לא שותים, אלא זוכרים, ואחר כך מאבדים את היין. גם יש לומר שר"ל שנחש לא מפחד מהם, שרק מפחד מאיש. אינו כל כך קשה שלא יודעים זה. ענין ארמיים הוא שלא סומכים על יראתם, אלא, מחמת נקיותם, מכסים אותו.
** רש"י מזוג -
עיין שם, שרוב מזיגות אינם כן. צריך ביאור למה מזכיר זה. אולי כוונתו להגדיר "מזוג ואינו מזוג" של לקמן. דחוק, ועוד שצריך ביאור מהיכי תיתי להגדיר כך.
** מי בארג -
יש לדון ל"ל ישתה מהם כיון שהם טובים. אינו כל כך קשה, שאולי מה שהוא טוב לנו אינו טוב לנחשים. ותו"ת.
מ.י.ב. אמר שאולי הוא מפני שאינו רגיל, ואז יראים ממנו. צריך לומר (וכן צריך לומר, לכאורה, בגמרא לקמן) שיודעים כן קודם שטועמים אותו. גם יש לומר שבטעימה לא נכנס (כל כך[fn:3]) ארס.
* ל:
** גמרא שומר -
ואם תאמר נאמר כן בכל. יש לומר שצריך להיות שאינו כל כך סכנה כדי לומר כן. ותו"ת.
** שוקע -
יש לדון למה שוקע. מ.י.ב. אמר שאולי הוא שפולט ביותר כוח. אף אני חשבתי על זה, אבל דחיתי כיון שאז צריך ביאור מה יהיה היחס בין זה לחזקו. גם לא מסתבר כן כל כך במציאות (שיתן בו כל כך כוח). גם לא משמע כן מרש"י. יותר נראה שמניחים שחלק מן הארס הוא ארס, וחלק ממנו הוא מים. אז, אם יש יותר ארס, ישקע יותר, שממה ששוקע כלל, צריך לומר שהארס משקע אותו. אם כן, צריך לומר ששל בחור יותר חזק, שיש בו יותר ארס. גמרא דוחה שאף שיש בו יותר ארס, אין ארס של בחור כל כך חזק. ותו"ת.
* לא.
** גמרא מקום שיפול העץ -
לכאורה, זה מילים של "The apple doesn’t fall far from the tree.” לכאורה, אין פירושו שווה לפירוש אותו פתגם.
** וכי כייף -
קצת יש לדון מתי מכיר שיש שני קשרים. אם רק מכיר אחר שמתיר אחד, יש לדון אם יהני.
* לא:
** גמרא אלא מעתה -
העיר מ.י.ב. שלכאורה, לשון "אלא מעתה" ק"ק, שזה היה קשה בין כך ובין כך. נראה שקאי על מה שהאיסור הוא מחמת גילוי.
** גזרה ישן -
קשה, אז, מה אומר שישן מותר. אולי מותר לשתותו, אבל אסור ליישנו. דחוק. אמר מ.י.ב. שאולי מרש"י משמע שמותר בכל דבר חוץ מיין (אולי לא שותים נחשים מאלו כל כך, או אין מיישנים כל כך, או לא שותים קודם שנתיישן כל כך). ותו"ת.
* לב.
** גמרא בנו -
יש לדון אם זה היה רשב"ג או בן אחר. ממה שלא אמר שם של רשב"ג משמע שלא היה פשוט לתנא שהיה רשב"ג. אם כן, נמצא שהיה לו אח. לכאורה, היה לו כבר רחב"ג.
** בעיניה -
לכאורה, ר"ל כיון שיכול (ואולי אף עומד) לעשות ממנו יין.
** רש"י גודע -
אחר כך- לכאורה, בא לבאר למה יודו לזה ולא לזה, ואומר שהיו בזמנים שונים. יש לדון, שהיה אפשר לומר שאמרו לבני אדם אחרים. ותחשב.
* לג.
** גמרא דאביק -
אפשר שאומר שאז מסתמא יחזור לאחר זמן, ואפשר שאומר שאז יחזור יותר קלוש, או שאומר שיזכור את זה יותר, או שיודה על יותר. ותחשב.
** חמרא -
אם זה יין, צריך לומר שדמי סתם יינם מותר. יש לדון מהו הדין.
** קשורים -
יש לדון אם זה עושה שיש יותר פייר פראשיר או שאין כל כך מניעה, שיותר קל ללכת.
** גרודים חדשים -
עיין במה שבאר רש"י בזה (שאחד הוא שניהם ביחד, ואחד ר"ל או). אפשר שמקורו הוא מה שאומר "ו" גבי אחד ולא גבי האחר.
* לג:
** גמרא לכתחילה -
היה אפשר לומר שדן אם מותר לתת בהם יין ולעשות כן, אבל מהמשך גמרא מבואר שדן אם מותר לתת שם ציור לכת’ ולשתות. קצת היה צריך ביאור למה יהיה רק בדיעבד, ומה משתנה אם כבר נתן בו ציר. ותו"ת.
** רב אחא -
ק"ק, שבפסחים (עד:) מבואר שהלכה לעוללם כמיקל.
** רש"י לא חש -
דשיכרא- יש לדון אם בא כאן לפרש למה שכרא מהני. לא נראה כן. אמר מ.י.ב. שאולי מפרש למה אינו כל כך חשש, שבין כך ובין כך רק יתן שכר אחר כך, ויאבד הכל. יש לדון, שלכאורה, עדיין יש חשש שכמו שטעה לתת יין, טעה ולא יתן שכר כלל.
* לד:
** גמרא פרש -
מניחים שאינו חלק מן הבהמה די לאסרו רק בגלל היותו חלק מן הבהמה, אלא רק בגלל שעושה דבר לענין העבודה זרה. ותחשב.
* לה.
** גמרא ניקור -
ר"ל גילוי. צריך ביאור למה אומר לשון זה. אולי לשון זה נאמר גבי דבר שהוא גוש, ולא לח. לא נראה, שנראה שגמ’ חושש לזה לפני שמיבש לגבינה.
* לה:
** גמרא מלכיא -
חושב אני שזה הזמן המיוחד שבא ר"מ או ר"מ בש"ס שלא מזכיר המחלקת מי אמר מה. אולי הוא מפני שכבר הז’ אותו לעיל במסכתא זה.
** לא זזה -
אם כן, לכאורה רואים שכתוב משניות חולין קודם למשניות נזיקין. דנים אם יש סדר לסדרים. אם אין סדר, אז אין זה קשה. אם יש סדר, צריך לומר שכך הוא הסדר, שקדשים קודם נזיקין, ולא כסדר שלנו.
** קשיא -
מוזר איך יהיה אותו קושיה שבא גמ’ לת’ לרבי יהושע קשה לתירוצו. (ר"ל, אין זה רק קושיה טובה, אלא זה עיקר הקושיה שבא לתרץ.)
** יין וחומץ -
צריך ביאור למה לא אסור בהנאה, שהרי יש בו יין. ויש לומר שמיירי בשאין חשש (למשל, ישראל נותן לו יין ועומד על גביו), ויש רק חתנות. ותחשב.
** כלבית -
עיין ברש"י. לכאורה, מה שר"ל הוא שזה כשאין שם דג כלבית, דהיינו שאין שם כלבית, ואז אין רואים שהוא טהור. אגב, רש"י גם מוסיף שכלבית הוא דבר טמא. צריך לומר שלא בא משם, אלא בא ממקום אחר, ובא לשם.
כל זה דחוק, ויותר צריך ביאור. גם יש לומר שהוא אף יש שם כלבית, אם אין שם דג, שמה שלא נגדל בשל טמא הוא רק אם הדג הוא שם. דחוק.
** איבו -
היה איבו שהיה אב של רב, אבל נראה שאין זה אותו איבו, שהרי היה כמה זמן לפני רבא. גם היה שני יו"דים בשמו.
** רש"י זלפתם -
ואם תאמר אם הוא מחמת טומאה, למה צריך לפרש שהוא בליעה. ויש לומר שרש"י הוא קאי רק על מסקנא, שמזכיר איסור. עדיין צריך לומר, אז, שכל מה שאומר רש"י משנה בין הוה אמינא למס’. יל"ד. גם אפשר לומר שאין כלי עצמו נטמא, אלא המשקים עדיין טמאים, ואז צריכים פליטתם. ותו"ת.
* לו:
** גמרא תמר -
נמצא שהיתה בת ישראל. אולי נתגיירה אחר שנולדה או אולי נולדה ישראלית.
** תמר -
יש להעיר שנמצא, אז, שיש סיבה טובה למה רצו להרוג אותה, ולמה שינו את דעתם כשגילה יהודה שהוא בעל אותה.
** עובדת כוכבים -
זה מניח שבת דווד היתה ישראלית, אף שהיתה בת יפת תואר. מסתמא, גיירה. ותחשב.
** רמז -
כוונתו לדין דאו’, אף שאומר שהוא רמז.
* לז:
** גמרא רשות הרבים -
יש להעיר שבין כך ובין כך היה צריך לציין, שהקפידו הבעלים שלא ילכו שם. ותו"ת.
* לט.
** רש"י מאנשי ביתיה -
קלא אילן- עיין במנחות שמבאר שיש תקנה לזה, שיכול לברר אם הוא קלא אילן או לא. לכאורה, יש עוד חשש, והוא שאולי כלל עמו צבע הנסיון.
* מ:
** גמרא במקומו של רבי מאיר -
אין צורך לומר כן, שהיה אפשר לומר כל מיעוט, כמו כל מקום שהיה כן, או שבכל מקום היו מיעוט שלהם נעבדים.
** אמר"י אמר שמואל -
יש לדון מה בא לעשות. אולי בא לבאר שיטת רבי מאיר. גם אולי אפשר לומר שבא לתרץ מ"ט. יש לדון איך מבארו. אולי חולקים אם מה שעושים לכעין אלו נחשב עבודה זרה. וצריך לחשוב.
** ובעומדים -
יש לדון אם מוסיף או חולק על שמואל. אם מוסיף, יש לדון אם צריך שניהם או אחד מהם. לשונו (הוי"ו) משמע שמוסיף. מעניין שיהיה ר"י מוסיף על שמואל. ותו"ת.
* מא.
** גמרא עטרה למלך -
מעניין, שהרי גמרא לעיל אמר[fn:4] שזה רק בתמונות של מלכים. אם כן, צריך ביאור מה רואים ממה שיש לו עטרה, שהרי אולי זה מחמת שהוא מלך. ותחשב.
** שחותם -
יש לדון אם הלשון שאינו גנאי משנה "את עצמו" או משנה "למיתה.”
* מא:
** גמרא שני כפות -
היה אפשר לומר שכפות חלוקים, שהם כעין תמונת יד ורגל.
* מב.
** גמרא נפל -
מניח גמ’ שאילו היה בבור וודאי האהיל עליו. איני יודע למה זה כל כך פשוט.
* מב:
** רש”י ולא מועלים -
מדאורייתא- עיין במעילה (וברשי שם), שלכאורה מבואר שזה אף מדרבנן.
** ודגים -
צריך ביאור למה מזכיר דגים. לכאורה, היה נראה לומר שכיוון לומר “דרקון.”
* מד.
** גמרא כתת -
ואם תאמר איך היה מותר לו לכתת אותו כיון שלא היה שלו. ויש לומר שמותר כיון שהוא מלך. גם יש לומר שהיה צריך להפריש בני אדם מן האיסור, ו"עת לעשות….”
** ויוציאו -
יש להעיר שהיה קטן אז. מעניין שהולמו כשהוא קטן וכשהוא גדול. ותחשב.
** רש"י ואין אדם - [fn:5]
כוח להקצותו- זה מעניין, שהיה נראה לומר שאף אם מקצה אותו, אינו אסור. ותחשב.
* מז:
** גמרא סייד וכייד בגופה -
יש לדון מה צריך ליטול. אולי צריך ליטול מה שסביב מה שכייד, עד שלא נראה עוד חקיקה. גם אפשר שמה שהיה נראה מאת מה שנחקק (ר"ל כשחקק, היה אבון במקום החקק. זה היה נראה, והיה חלק מן הצורה) גם כן צריך ליטול. ותחשב.
* מח.
** גמרא גידעו -
היה אפשר לומר שהוא מפני ששינה את האילן, ואז הוא כעשה אילן חדש, ומה שבא, בא לאילן החדש. מרש"י לקמן לא נראה כן, אלא הוא כנוטע כיון שגרם שאחרים יבוא, שזה עושה שאילן יגדל.
* מח:
** גמרא עבר -
שאלה זה מעניין. לכאורה, אין איסור להיות תחתיו כלל, אלא שאם עושה כן, יהיה טמא. אז, קשה מה שואל כאן. צריך לומר שיש איסור להיות טמא (כן כותב רש"י במקום אחר, אבל עדיין חידוש הוא שהוא אף בטומאה דרבנן). גי"ל שכאן מיירי בציור שאסור לטמא (כמו הולך לשחוט קרבן פסח). זה לא נראה ממעשה שהביא גמרא. גי"ל שכיון שעשו רבנן שהוא כמת, אסרו לכהן. זה מחודש, שלכאורה, לא מצאנו מקור אחר לזה. ותחשב.
** שאם נטע -
יש להעיר שדינם של דברים שמתירים לא שווים, שאם נטע, עדיין יש בו שני ערלה, אבל רק לא נאסר מחמת איסור הנאה של אגוז של ערלה. אם הבריך והרכיב, אין אף הוה אמינא שיאסור מחמת איסור הנאת ערלה, אלא מחדש שאין שני ערלה נוהגים בו. ותחשב.
** מכלל דבצל -
רש"י מפרש שזה בלשון תמיהה. אם כן, לכאורה, צריך לומר שסבר שאין חידוש מדין זה, שסובר שהוא פשוט. ויש לדון. ותחשב.
* מט.
** גמרא אודו לי מיהת -
לשון זה מעניין, שלא מודים לו בדין. צריך לומר שיש לו שני סברות:
1. שיהיה זה נחשב זה וזה גורם.
2. שזה וזה גורם מותר.
אומר שיודע שלא מודים לסברה שניה, אבל על כל פנים יודו לסברה ראשונה. ותחשב. עיין כעין זה בב"ח.
* מט:
** רש"י ונשתרי -
ליתיה לאיסורא- קשה, שאמר שביין נסך איתא לאיסורא. נראה שכן צריכים לגרוס (עיין במהרש"א) ומבאר למה צריך לחלק ולומר ששם אין שיטה שמותר לפדות אותו.
* נ.
** גמרא ברבי סימאי -
אולי לא היה שם אביו כן, אלא נקרא כן מפני שהיה מסמא את עצמו, שלא היה רואה במקומות שלא ראה לראות. (ויש לציין למה שנקרא בנן של קדושים. באמת, יש צד (חושב אני שאולי תוס’ דן בזה) שאביו לא ראה. ותו"ת.)
** מת אין לה בטילה -
יש לדון שאם מסריח ממש לא יטמא. כן אני חושב, אבל אולי אין אני נכון. ויש לדון, שאולי גמ’ רק ר"ל שאין ביטול מבטל מת, אלא צריך דבר אחר. ותחשב.
* נ:
** רש"י עד ראש השנה -
מדרבנן- לכאורה, זה אי אפשר למי שדורש מ"חריש וקציר תשבות" לרבות ששי שיש לו קצת דיני שמיטה.
* נב:
** גמרא צריך ביאור למה
גמרא מניח שכל שאסור מדרבנן שווה, שאולי בית חוניו חלוק מעבודה זרה דרבנן. ותחשב.
* נג:
** גמרא מלמד שאוו -
ואם תאמר אם כן בטל ברוב, שרק רצו בזה ליום אחד. ויש לדון אם ע"ז בטל ברוב. גם יש לומר שכל ע"ז עד אז נאסרו, שגילו שרצו בע"ז, ומחלו על האיסור. ותחשב.
* נד:
** גמרא דבר שאין צורך -
ואם תאמר הרי לכל דבר יש צורך שאי לאו הכי, לא היה ה’ בורא אותו. ויש לומר שכבר בטל צורכו. לא מאבד ה’ אותו כיון שאין סיבה לשינוי זה. ויש לדון. גם יש לומר שאין הכי נמי, היו יכולים להשיב כן, אלא שיותר קל לומר זה. ותחשב. גם יש לומרש יש דברים שמסתבר שהטוב שבא על ידי קיום שלהם אינו כל כך טוב כמה שהיה בא אילו מאבד אותם, ואז לא יעבדו אותו. ותחשב.
** שגזל סאה -
יש להעיר שלידה הוא אחד מן הדברים שהם ביד ה’. גם אומר כן על גשם; אולי זהו ענין של סאה שלא היה נצמח הוא שלא היה גשם. לא צריך זה, שהרי יהיו דרכים אחרים. ותחשב.
** על אשת חברו -
מעניין, שלכאורה, אינו כשאר ציורים, ששם על ידי זה לא יעברו, אבל כאן, לכאורה, עדיין יעברו. ויש לדון, שאולי באים כדי להוליד. דחוק. גם יש לומר שרוצה למנוע הרע של היות ממזרים. זה אומר שרע שיש ממזרים בעולם. יש לציין לגמרא בגיטין (לג.) ויבמות (לו:) וחגיגה (גבי מעוות לא יוכל) שמשמעים כן.
** אם מת -
משמע קצת שאין הקושיה שכיון שהוא רע יאבדנו, שלכאורה, כבר השיב על זה, אלא משמע שהקשה שאין צורך בהם. ותחשב. (עדיין יכול להיות שאומרים שרק אין סיבה שישארו, ואז יאבד אותם כיון שהם רעים.) ותחשב.
* נה.
** גמרא שהחליקן -
זה מעניין. משמע שה’ עושה דברים לעשות שבני אדם יטעו. עיין בלשון רש"י כאן שלא משמע כן כל כך. קצת צריך ביאור, שהרי גמ’ משמע כן, שאי לאו הכי, קשה איך עונה לשאלתו. ועיין ברש"י יומא לח:.
* נו.
** גמרא משיקפה -
- עיין במה שמבאר רש"י במילה זה. נראה שר"ל לעלות, ודבר שצף עולה. יש לדון איך יודעים שהשמרים עולים ולא היין. ותחשב.
ואם תאמר הרי "קפאו" באז ישיר לא אומר כן. ויש לומר ששאני התם, והוא שורש אחר, שיש בו אל"ף בסופו. ואם תאמר אף רש"י כותבו באל"ף כאן. ויש לומר שרש"י כותב המילה הארמית. ותחשב.
** מן הגת -
קשה לל"א שנשאר קצת שם אחר שנתן בחבית, כמו שאומרים שנשאר אחר שבא לבוא. ויש לומר שכשנותנים בחבית, דרכם היה להוציא את הכל. ותחשב.
** להך קמייתא -
ק"ק ל"ל אומרים שלא נשנה את הראשון, והוא שיטת ת"ק.
* נו:
** גמרא גרגותני -
נראה שהענין הוא כך: נוטל מן הגת, ונותן בתוך הבור מן הגרגותני. מה שהוא בתוך הגת אסור, שהרי מחובר על ידי נצוק (או שנוגע בו כיון שהוא מלא). אחר שחוזר לגת, ליטול עוד לתת בבור, נוגע ומערב בו, ואז אוסרו. ותחשב.
** חבור -
כיון שחבור אוסר, ק"ק ל"ל אסור כיון שנתמלא הבור, שאז כולם נוגעים זה בזה. ותחשב.
* מז.
** גמרא גדולים -
היה אפשר לחלק לומר ששל גדולים אף אסור בהנאה, וזהו כוונת משנה זה. אולי פשוט לגמרא שאם אינו בר דעת, לא ייאסר בהנאה.
* נח:
** גמרא בליליא -
מעניין שאף שהוא לילה, ולא יכול לראות מה שותים, מניח שלא יתן לו לערות אם הוא יין. צריך לומר שיש דבר אחר שיעשה שלא יחשבו שהוא טוב (למשל, לא דבר להם באופן טוב). גם יש לומר שחשב שלא יתנו למי שלא יודעים אם הוא טוב את היין. ותחשב.
** ואימא מזגו -
עיין בחולין (קלז:) שגם שם ר"י אמר כן. ויש להעיר ששם אמר לאחד ששמו איסי בן היני. יש לדון אם זה רב אסי (שהוא כאן).[fn:6] יש לציין למה שכתבנו בשיחתא דשי שלכאורה, היה רב אמי נקרא ר’ אימי. אם כן, אולי כן הוא בר’ אסי. ותו"ת.
** לך לך -
יש להעיר שגבי נזיר, אפשר שהענין הוא שאם בא לשם, מסתמא ירצה כל כך לאכול שיאכל. אין זה הענין כאן, לכאורה, שרואים שלא עשה יותר ממזיגה זה. ותחשב.
גם יש לדון למה אין זה גזירה לגזרה. ויש לדון. אולי ר"ל שהוא לך לך מחמת איסור יין נסך עצמו. אולי עיין לקמן בע"ה.
* נט:
** גמרא נקטוה לידיה -
מעניין שישכשך בעלייתו, אבל לא בירידתו.
** מיקלא קלייה -
לכאורה, זה נזק שאינו ניכר. לכאורה, אז חיובו הוא מדרבנן או מדאורייתא, ותלוי על גמ’ בגיטין. ואפשר שגוי יהיה יותר חייב, כמו שאומר גמ’ בב"ק (שהפקיר ה’ את נכסיהם). באמת, ק"ק למה צריך ראיה לזה. אולי בא להוכיח שאין דמי היזק נחשב הנאה. מעניין. ותחשב.
** משום שני דברים -
עיין במה שמבאר רש"י. צריך ביאור, שסברתם יתיר למכור לכולם. אז, צריך ביאור איך מתירים על ידי זה לגבות דמי היזק. ותחשב.
* ס.
** גמרא לא הבנתי כל סוגיה
של חיבור מן הצד וכדומה. לכאורה, צריך ביאור איך נאמר שכולו מחובר אם נוגע מכאן, ואין כולו מחובר אם נוגע ממקום אחר. ותחשב.
** עד הברזא -
נראה שאולי תלוי באם הבעיה כאן הוא שנוגע או שמעמיד.[fn:7]
** לכאורה,
קשקוש הוא רק אם היין הולך בתוך הכלי, ולא אם הכלי הולך, ויין הולכים עמו. קיל"ד למה. ותח’.
** רש"י חמרא אסור -
בהנאה- אינו כיין מזוג כיון שכאן מכוון לשפוך. ותחשב. ויש לדון ל"ל נאמר שאף שם מכוון לשינוי מקום היין, שצריך זה כדי לערב אותו עם מים ולמזגו. ותחשב.
עדיין צריך ביאור למה קרקוש רק עושה איסור שתיה. אולי לא רוצה בשינוי מקומו. ותחשב.
** חמרא -
מעניין שהוא רק מח’ לך לך, ולא עיקר גזירת סתם יינם, שהרי הוא אותו מעשה של ניסוך. ויש לומר שר"ל שהוא לך לך מחמת עיקר יין נסך, וזהו עיקר איסור של סתם יינם. מוזר, אז, מה שרש"י צריך להביא ראיה. ותחשב על זה.
אולי היה אפשר לומר שענין סתם יינם אינו מחשש שמא נסכו, אלא כדי שלא יגעו ביין. אז, מה שנוגע אינו אם מה שעשה נראה כמערה, אלא אם מה שעשה יגרום שיעבוד עם יין. ותחשב. חושב אני שיש לשונות שלא משמעים כן. ותחשב.
* סא.
** גמרא המטהר -
חושב אני שדין רישא של סיפא הוא אותו דבר של רישא. ותו"ת.
** דאבדה ליה בהמה -
יש לדון מהו הענין:
1. אולי כיון שהיה רגיל ללכת שם, בהמתו הולך לשם.
2. אולי הוא גבוה, ומגביה א"ע עליו כדי לראות בהמתו. ותו"ת.
** רש"י דקאזיל -
ואם תאמר נאמר שהוא נוגע ע"י ד"א. ויש לומר שכאן לא נוגע בו בכל שעה, אלא מגלגל אותו. אז, צריך לומר בעיה אחרת. ותחשב.
* סא:
** גמרא אף שמפתח וחותם -
זה חוזר להיות מה שאומר ר"מ, ולא מה שאומר ר"י לגרוס.
** להקל -
עיין ברש"י שכ’ שהדיון הוא אם נכתב בלשון תימה או לא. נראה שאפשר שזהו הדיון בכל מקום שאומר גמרא שדבר לא מסויים איזה תנא אומר מה. ותחשב.
** רש"י מסקנא דמילתא -
עיין במש"כ בשכשוך ומגע שהם לך לך. לכאורה, הם עיקרי הגזירות, ואעפ"כ כ’ שהם לך לך. אם כן, משמע שכל גזירת סת"י הוא לך לך. (אגב, יש לדון ל"ל נאמר שהוא גזירה. אולי יש דבר מיוחד בגזירות אלו. צ"ב למה.)
* סב:
** גמרא העלה לי -
צריך ביאור ל"ל מקילים כן לריבית ואונאה וכדומה. אולי גזרו רבנן על זה. צ"ב ל"ל גזרו כאן. אולי לא כל כך מצוי שיעשו כן, שאין כל כך רווח. ותחשב.
** לכאורה,
רבא רק מבאר מה שאמר רבי יוחנן. ותחשב.
** קברינהו -
ואם תאמר אולי לא קברינהו כיון שאז יצמחו. וי"ל שמותר אם נצמח. יל"ד אם זה נכון. גי"ל שא"כ לא צ’ לשרוף, אלא יתן אותם בתיבה. ותחשב.
* סג.
** גמרא מעכשיו -
גמרא משמע שמדגיש שני דברים:
1. מה שכבר קנה.
2. מה שאינו עוד בעולם.
צריך ביאור מה כל אחד עושה ולמה צריך כל אחד (ואם צריך כל אחד). נראה אולי לציין לגמ’ בפרק בהמה המקשה, שמשמע שאם אין הדבר בעין שהיה לו להיגלות שהוא נשתנה למפרע, לא משנה. היה אפשר לומר שזה ענין מש"א גמ’, ושאלת גמ’ גבי הקדש הוא שהוא בעין, אבל לא באופן שעכשיו יכול להיאסר, כמו שאמר תוס’.
** דר"א גופיה -
היה אפשר לומר שידע שר"א היה מסופק, אבל אז לא היה שואל אותו, שידע שר"א כבר שאל ולא ידע. יש לדון, שאולי יכולים לחדש ראיות. ותחשב.
** אי דקאי בחצירה -
צריך ביאור ל"ל הקשה כן אף בתירוץ ראשון, שאף שם גוי קנה קודם משיכה. ותחשב.
בטלה- נמצא שלא חל אם לא מפרש על מה קאי. ויש לדון ל"ל אומרים כן ב"אחד מכם מקודשת לי" בקידושין. ותחשב.
** רש"י עובד כוכבים -
זה מניח שמשיכה קונה מדאורייתא. חולקים בזה רבי יוחנן וריש לקיש בכ"מ בזה. אפשר שרש"י סובר שגמ’ זה אפשר רק אם נאמר כר"ל שהוא מדאורייתא. גם יש לומר שאף לרבי יוחנן, שמשיכה מדרבנן, יכולים לומר שלא תקנו כן לגויים, שתקנו להצלת קונה. אם כן, רש"י אומר כר"ל כיון שכן (אולי) הלכה. ותו"ת.
* סג:
** גמרא לא משום שביעית -
נראה לי שכך הוא פירוש של גמרא זה: גמרא מניח שיש בעיה במה שנותן ממון בחילוף איסור. אין הבעיה רק מה שגורם לאכילה של איסור, שבהכרח עושה כן, אלא יש בעיה במה שמחליף לאכילת איסור. אז, אומר שבהכרח חילוף הוא. מתרץ שכאן כבר נתן, ולכן הוא חילוף. גם מתרץ שכאן נשא ונתן האיסור ביד, ואין האיסור החילוף בשביל איסור (ואולי זה אף לא אסור), אלא האיסור הוא שנתן האיסור ביד. ותחשב על זה.
* סד.
** גמרא מדר"י -
היה אפשר לחלק לומר שכאן לא נקרא מתנת חנם, שלא רוצה בהנאת גוי, אלא רוצה בביטול כלאים ובטוב שמים.
* סד:
** רש"י אלו לא באו -
יש להעיר שמצדד גמרא שהתיר ה’ את המצוות לבני נוח (ע"ז ב:, ב"ק לח.)
* סה.
** גמרא איזהו גר תושב -
יש לדון למה, אז, היה מותר לשלוח לו מתנה. נראה שסבר שאין איסור לא תחנם על נתינת מתנת חנם (כמו שאומר רבי מאיר בפסחים (כא:). עיין גמרא לעיל (סד.) שרק אמר כן לפי ר"י. גם יש לומר שנתן אותו באופן שלא נחשב מתנת חנם (כמו בחולין מה.). יש לציין לגמרא חגיגה (ה:), שהוא גם כן גבי רבא (ומעשה שני כאן הוא גבי רבא).
** כמין -
נראה שמקשה ממה שמחשיבו כמין; משמע שהוא יותר ממה שאמר לעיל (אינו רק גר תושב). אגב, יש לדון למה הוא כן. (אולי הוא קנס.)
** רש"י לאברדינא -
לא ר"ל שם של ע"כ ממש, שלא עבד לע"ז. נראה שבאמת, רוב ע"כ כן, שהרי לא עובדים כוכבים. על כל פנים, רואים שאומרים לשון זה אף על מי שלא עובד ע"ז.
* סה:
** גמרא שרא רבא -
ואם תאמר ייאסר בהנאה. ויש לומר שמיירי במין יין נסך שרק אסור בשתיה (כמו כוחו על ידי דבר אחר). גם יש לומר שלא נהנה מיין, אלא מן החיטין. רק לא מותר לאכול אותם מפני טעם של היין. ותח’.
* סו.
** גמרא רבי יהודה -
לא מצאנו כל כך שרבי מאיר יאמר דבר בשם רבי יהודה. גם מצאנו כן בחגיגה לענין גוד אסיק (יט:).
** מצטרפים -
לכאורה, איסור זה צריך קצת הגדרה. לכאורה, אינו רק בדברים שאסורים לאכול, שגמרא אומר אותו גבי בשר בחלב. גם אינו רק גבי דברים שאסור לעשות, שהרי אומרים כן כאן. (ויש לדון, שאולי הוא גבי דבר שאסור לעשות). ותחשב.
** מצטרפים -
לכאורה, ר"ל שלא מצטרים, עדיין, לאיסור שלהם, אלא מצטרפים לאותו איסור אחד של "לא תאכל כל תועבה.”
** חלא שנפל -
עיין במה שמבאר רש"י. יש להעיר שנעשה מין במינו אחר שנפל. צריך לומר שמה שלא ניער הוא מפני שדבר שכבר בטל לא נער. ותחשב.
* סו:
** גמרא ריחא מילתא -
כמו כן דן גמרא בפסחים (עו:). שם, ולקמן כאן, ר"ל שריח הוא אוסר בתערובת וכדומה. כאן, לכאורה, ר"ל שאסור להנות בריח. יש לציין לגמרא פסחים (כו.) שכ’ שיש מעילה בריח.
* סז.
** גמרא כל שטעמו וממשו -
לכאורה, ר"ל שנותן טעם בתערובת, ואז לא בטל, וגם ממשו הוא שם, שלא נתבטל.
* סז:
** גמרא ולא ממשו -
עיין ברש"י. מצאנו בכ"מ (למשל, עיין ביבמות בסוף פרק הערל (פב.)) שמניח גמרא שמה שנימוח אינו עוד בעין. יש לדון למה. ותחשב. אולי שינה משעה שהיה בו סיבת איסור. צריך להניח שאין עליו עכשיו סיבת האיסור. אולי רק צריך שהוא חלוק בחילוק חשוב משאר בני מינו. צריך ביאור מה לנו בזה.
* סח.
** גמרא שאינה ראויה לגר -
לכאורה, אם צריך להיות סרוחה, אז הוא בעיה במאכל (המאכל חלוק, ולכן אינו נבלה). אם הוא בכל זמן שהוא כן, יש לדון אם הוא בעיה במאכל או במעשה. ותחשב.
** נבלה -
מניח שלומדים מנבילה לכל איסורים. ותחשב.
* סח:
** גמרא והא קתני נפל -
היה אפשר להוכיח מזה בפני עצמו, שאם מודים בהשביח ושוב נפגם, צריך לומר שחולקים חכמים על רבי שמעון בנפגם מעיקרא. ותו"ת.
** הערלה וכלאי הכרם -
עיין בגמרא שם (מעילה יח.) שלא מפרש משנה כן. באמת, היה אפשר לפרש כן (שקושייתו אינו קשה לפי מש"כ גמ’ זה, שאז נמצא שיש נפק"מ בצירופם). ותחשב.
** ואפילו הכי -
נראה שר"ל שלא צריכים איסור לעשות שבני אדם לא יאכלו ממנו. אז, צריך לומר שעשה כן למה שבני אדם לא ירחיקו כל כך ממנו, והוא תערובת, שאינו כל כך מאוס. אין צריכים לזה, שיש לומר שהוא רק מיותר, ואז צריך להרבות זה, אבל נראה שדרך זה יותר מטעים.
* סט.
** גמרא המניח אף על פי -
ב"ח גורס, “אף על פי,” ויש שלא גורסים אותו. אם גורסים, מעניין הוא, שכבר אמרנו שמניחו שם. אז, זהו הכי טוב שאפשר. ותחשב.
** אימרוטי -
צריך ביאור מה זה עושה, שעדיין יהיו אותם חתיכות קטנות בטילים. ותחשב. אולי ניכרים הם, ולא בטלים. ק"ק, אז, למה צריכים להיות כשיעור, שיצטרפו. ותחשב.
* ע.
** גמרא דאי מנטרי -
היה אפשר להיות שיודעים על היתר זה, וחושב שיסמוך עליו. צ"ל שרק ידע שאין זה המציאות.
** דאי -
היה אפשר לומר שרק לא נושאים אותם קרוב לשבת.
** ולא ידעי -
יש לציין לגמרא בתחילת פרק מי שהחשיך (קנג) שיוצא שלא מקילים כך אם יש גוי, שנותנים לגוי. נמצא שכמעט אי אפשר לגוי לדעת זה, שהרי אסור ללמד להם תורה, ואי אפשר שיראו אדם מקיל על פי זה. ותחשב.
** רובא גנבי -
לכאורה, זה מפני שרוב בני אדם שם היו בני ישראל.
** רש"י יצרא דיין -
לולי רש"י, הומ"ל שימר הרע של אכילה מבאר, והוא שאוכלים כולם בו, ודנים אם זה ראיה שהוא טוב. ותחשב. מרש"י נראה שבכל זמנים אלו הוא ביד ישראל לקבוע אם ינסכו או לא.
* עא.
** גמרא רמות רוחא -
לכאורה, ר"ל שאילו חזרו היה נראה כגסות. אז, לא חוזרים. ותו"ת.
* עא:
** גמרא מדמטי -
עיין במה שבארש"י. מעניין שיש קנין הגבהה קודם שמגביהה, כיון שבא לאויר כלי שלו. ותחשב.
** האמר רב -
עיין במה שפרש"י. היה אפשר לומר שלא מניח שסובר כרבי יוחנן, אלא מקשה שיודעים שרב אמר שכן הלכה, ואומר שרב אמר כן רק לענין חבית בחבית שם. דחוק שנדע רק חצי המאמר. ותחשב.
** משום דמיחזי -
ק"ק ל"ל אמר שהוא מקח טעות. אם ענין מק"ט הוא שהוא אומדנא, אולי הענין הוא שנראה כמק"ט. עדיין ק"ק לל"א מק"ט, שגמ’ אומר כן בכ"מ.
** אינו קונה אמאי נהרג -
משמע שמה שעושה גניבה תלוי על מה עושה קנין.
* עב:
** גמרא דנפק לבראי -
קשה, שהרי אסרו המוזג. ותו"ת.
* עג.
** גמרא מים -
נמצא שיש מים נסך שנאסר.
** מעניין
שמים נותן טעם בדבר. אינו כל כך קשה, שאומרים שהוא קצת watery. ותחשב.
** רש"י ונשברה -
ר"ל, ואז בנקב ראשון, נמצא הכל חלק מן הבור.
** היתירא לגו -
צריך לומר שהיתר חוזר וניעור אחר שיש די היתר. גם יש לומר שאחר שבטל טעם איסור, לא יכול להיות נחשב איסור. ותחשב, שאם כן צריך לומר שהוא כן בכל יין נסך או לומר חילוק אחר.
* עג:
** גמרא תנן נמי הכי -
צריך ביאור מה מוסיף בזה, שכבר הביא ברייתא. אולי מחדש מה שיש משנה. ותחשב.
** חטה אחת פוטרת -
לכאורה, ר"ל שהוא חשוב כיון שהוא חלק חשוב מן התרומה. ותחשב. עיין במה שכתב רש"י. קצת צריך ביאור עדיין.
* עד.
** רש"י בשר בחלב -
לכאורה, כדי שיהיה תערובת, צריך לומר שהוא מין במינו, שאי לאו הכי, קל לדעת מהו מה. כן אומר רש"י, אבל צריך ביאור, אז, לשמואל למה לא אומרים שכל דבר לא בטל. אולי מין במינו הוא רק בתערובת לח ויבש כיון שאז תלוי בנותן טעם (באמת, יש לדון במה תלוי בדבר יבש כזה. ותחשב.) לא נראה כן מגמרא בהערל גבי חתיכות במחלקת רבי יוחנן וריש לקיש. ותחשב. ותחשב.
** בשר -
ואפילו לרב ושמואל- לכאורה, ר"ל שאף לרב ושמואל לא יהיה כן הדין.
* עד:
** גמרא של חרס -
לא מניח שהוא במזופף, שהרי אוסר אף אם קולף.
** חרס -
קשה, שלא יודעים שכן הוא הדין אף אם לא דרך. יותר מזה, יש לומר שאז נמצא שחרס שבמשנה יותר חמור אבל שבברייתא יותר קל. זה מוזר.
** נעווה -
נראה שאינו בחרס, ששם צריך הסיקו בפנים. אלא, נראה שנתן עצה אחר שיכולים לעשות במינים אחרים.
* עה:
** גמרא אשכול וכל -
לא הבנתי גמרא זה כל כך.
* עו.
** גמרא ואידך -
לכאורה, מכוון לומר מקור שלו. יש לדון למה צריך מקור, שמבאר גמרא לעיל שלא סובר כדיין גבי נבילה שהוא מקור לדין נותן טעם לפגם. ויש לומר שהיה דורש כן בנבלה אחלן לא היה לו הוכחה זה. ותחשב.
** ואידך -
לכוארה, הוא מקורו. יש לדון למה מביא מקור כאן. לכאורה, הוא מפני שדנים במחלקת, וכבר הביא רובו של אותו מקור. גם אפשר שהובא אגב מה שהובא על רחבבדר"י לעיל. גי"ל שגמרא מקשה שכיון שידוע שזהו מקורו, קשה, שנדחה. אז, צריך לבאר איך יכו"ל מקורו. ותחשב.
** הכא -
ר"ל התם (מהפך אותם). יש שמשנים את הגירסא.
** אי הכי -
יש לדון אם ר"ל שרק הכי היה ראיה או שאם כן יותר היה לו לשנות כך. לצד שני, צריך ביאור למה היה לו לשנות כך. ותחשב.
* עו:
** גמרא גדפנא -
עיין בביאור רש"י. יש להעיר שצריכים לעשות לעשות שיהיו ניצוצות במקום שהיו לפני זמן. אז, צריך זה, לכאורה כדי שיהיה בכל מקום. יש לדון אם זהו כוונת רש"י, שקצת משמע שרק חושש שלא יהיו שום ניצוצות.
** רש"י ונועצה -
וי"א- לכאורה, זהו ביאור שיפה. אם כן, היה לו לפרש אותו על המשנה, ולא כאן.
* Footnotes
[fn:1] שוב הבנתי שאינו כן ב"אחריך.” צריך למצוא אותו רש"י..
[fn:2] ויש לדון, באמת, אם רצה לומר שלא היה נס קורה, ולא היה ניצול מן הרומיים, או שלא יוכל לקחת אותה. אפשר שחש לשניהם. ותחשב.
[fn:3] אם נאמר שנכנס קצת ארס, צריך לומר שלא חוששים שכמה נחשים שתו ממנו.
[fn:4] אבל עיין לעיל, שאולי יש חולקים על זה. עדיין, צ"ב לקצת אמוראים.
[fn:5] כתבתי קצת בנוט"ס.
[fn:6] לכאורה, לא מסתבר שהוא אותו איש, שלמה יטעה פעם שני. ותו"ת.
[fn:7] אגב, יש להעיר שאם לא היה מעמיד, היה נופל אף קצת מן התחתון, שילך מה שקרוב לו, וכח ביאתו יעשה שיגביה מה שלמטה. ותחשב אם זה נכון.
