* מ:
** גזר שאר מקומות -
לשון זה מעניין. לשון גזר משמע שהוא מדרבנן.. אם כן, משמע ששיטת רבי מאיר הוא מדרבנן. לא נראה כן מתחילת גיטין (ממה שצריך לתרץ אף לרבי מאיר שם, כיון שבין כך ובין כך יש חשש דרבנן). ותחשב.
אולי כאן אינו אף מיעוט, אבל רק נגזור אם חוששים למיעוט. צריך ביאור. לכאורה, הענין הוא שמיעוט שאינו מצוי מותר, אבל כיון שהוא יותר קרוב למה שהוא אסור מדאורייתא לרבי מאיר ממה שהוא לרבנן, רבי מאיר גזר בו, ורבנן לא גזרו בו.
ויש להעיר שיש לדון מהיכי תיתי שרבי מאיר גוזר כאן, ואינו סובר שהוא מדין תורה.
אפשר שרבי מאיר סובר שאיסור חשש למיעוט הוא גזירה לחשש למה שאינו מיעוט. ותחשב.
* מא.
** תבנית יד -
יש לדון אם זה שייך רק בכפרים, או רק לרבי מאיר, או אולי אף אם הוא יד או רגל שאוחז במטה וכדומה.
עיין לקמן שגמרא מוקים סתם כרבי מאיר (מחמת שאומר כן על צלמים). לא הבנתי כל כך הדיוק, כפי מש”כ, אלא אם כן נאמר שלומד מייתור של המשנה. אגב, ק"ק ל"ל ת’ שם כמו שאומר גמרא כאן לשמואל. ותחשב.
* מב.
** הא תרגמא שמואל -
משמע שריש לקיש מביא דברי שמואל. אין זה מצוי. אולי רק אמר התירוץ, וגמרא מוסיף מה שאף שמואל אמר כן. כמו”כ מצאנו במק”א (עיין ברשב”ם בפרק חזקת הבתים). ותחשב. גם יש לומר שבני ישיבה דנו בזה אחר ריש לקיש ורבי יוחנן.
אגב, יש להעיר ששמעתי מר.ש.ש. שחי ר”י לזמן רב, וכיון שמשמע מגמרא ב”מ שמת מיד אחר ר”ל, לכאורה אף ריש לקיש חי מאוחר. אם אינו כל כך מוזר שיביא דברי שמואל.
** קפחסה -
קשה, שאם חוששים שסובר שלא מקפיד על מה שנפסח, איך יש בזה ביטול. אולי אין סיבה שגוי ירצה בזה כי אם מפני שסובר שאין זה טוב לע”ז. ותחשב.
* מב:
** ורבי אבהו -
צריך לומר שעדיין אילן עצמו בוודאי אסור, שאי לאו הכי, קשה לר”י למה אסור לעלות עליו. צריך ביאור למה אילן חלוק. אולי הוא לא נשתנה על ידי אותו נפילה ממנו. וצריך לחשוב.
* מג:
** איתי הגיתי -
יש להעיר שאם נאמר שאין גר תושב מבטל ע”ז (גמרא דן בזה), נצטרך לומר שלא היה איתי אף גר תושב, אף שהיה מאנשי דווד.
* מד.
** כל הראוי -
יש לדון למה אי אפשר לבדוק כל מי שאומר שהוא משיח כך. יש לדון כמה קשה הוא להולמו, שאם יש ממש בקעה בראשו, אין צריכים אותו כתר כדי לבדוק, אבל אם צריך אותו כתר לבדוק, קל להבין למה אין אנו בודקדים. ותו"ת.
* מה:
** וריב”י -
כיון שהגענו לזה, לא הבנתי מהיכי תיתי שריב”י לא אומר כחכמים. אולי הוא מחמת מה שאומר גמרא לקמן (דומה להרים).
* מו.
** דבעי חזקיה -
זה מוכיח שחזקיה סתם הוא חזקיה בן ר”ח. רש"י גם כן מבאר כן במקום אחר.
* מז.
** יש דיחוי -
זה מעניין, שבאותו שעה היה פסול מחמת סיבה אחרת, שעדיין מחובר. ותחשב.
* מז:
** הכניס לתוכה והוציאה -
משמע שאילו לא הוציאה, היה אסור. לא נראה כן, שלכאורה, לא יהיה יותר רע ממרחץ של אפרודיטי.
** ותיתסר כולה -
יש לדון מה למעשה נאסר, שלכאורה, צריך ליטול את החידוש, אבל אם חקק בו, אין חידוש. לכאורה, צריך להוציא מה שעשה את החקיקה, והאו מה שנשאר. צריך לומר שכשמגיע לאבן שלא נחקק (ר"ל גוף האבן תחת החקיקה), מותר. ויש לדון, שאולי קליפה תחתונה של זה הוא חלק ממה שעשה את החקיקה. ויש לדון. ותחשב.
** בגופה -
לכאורה, ר"ל שחקק בגוף אבן, ולא רק הוסיף עליו דברים.
* מח.
** המשתחווה לאילן -
צריך ביאור ל"ל מתרצים כמו שת’ גמרא לעיל, והוא שאם עשה כן אסור אף אם לא השתחווה לה. ותחשב. אולי יודע שאין זה הדין. גם יש לומר שגידוע לעבודה זרה יהיה מעשה לעבדו. אם כן, צריך ביאור למה אינו כן בבית. אולי הוא מפני שאין בית עד שעושה כן, ואז אין דבר לעבוד, מה שאין כן כאן. ותחשב.
* מח:
** זה וזה גורם -
מעניין שזה נחשב זה וזה גורם, שהוה אמינא שנחשב הנאה, אבל לא נחשב שזה סיבה, אלא הוא הנאה במה שעשה שסיבה אחר יכול לעשות דבר עמו. אולי זהו כל מה שאומר זה וזה גורם, שאולי לא נמצא בציור שהיה צריך להיות סיבה. וצריך לחפש.
** מה שמשביח -
מעניין, שכיון שנופלים, לכאורה אין צל. אולי ר"ל שיש צול מן העצים עצמם. דחוק, שאין כל כך צל. גם יש לומר שיש צל בימות השנה שיש נבייה. אם כן, אין הפגימה צריך להיות באותו זמן ובאותו דבר של ההנאה. ותחשב.
* מט.
** אחר אחרון -
יש להעיר שהיה הקושיה רק מי סובר שזה וזה גורם מותר. אז, בין אם ר”א אומר כאביי בין אם לא אומר כאביי, לכאורה מוכח שרבנן חולקים ואומרים שזה וזה גורם מותר. אם כן, אין צריך לחפש בביאור רבי אליעזר, שאותו שיטה יכול להיות רבי יוסי. ותחשב.
** מי יימר... כאביי -
נראה שרצה לומר שאולי אף אביי רק יודע זה כיון שרואה שיטת רבי אליעזר במקום אחר. יש להעיר שכיון שהגענו לזה, אין צורך לדעת אותו מקום אחר, שאביי בוודאי ידעו. ותו"ת.
* מט:
** אבא בר ר”ח -
אולי אומר דבר בשם בנו. מוזר, אז, ל"ל אומר בני. אולי גמרא אומר לשון זה. יש לדון, שלא לעולם משנה לשון כך. אולי היה בן של ר”ח אחר. גי”ל שהיה אביו )ואולי לכן קורא לו אבא), שמצאנו בכמה מקומות שאדם נקרא אחר שם אבי אביו. אם כן, אולי היה כן אף ברב חסדא. ותשחב.
** שפאה מותרים -
אולי זה מפני שע”ז ששברה מותר, אף אם לא קרה ביטול, אבל לא נראה שאותו סברה הוא שע”ז לא יכול לשמור את עצמו, אבל כאן סובר שזה טוב לע”ז. אלא נראה שהוא מפני שמחשיב שאינו עוד חלק מן הע”ז, וע”ז לא כולל אותו. ותחשב.
* נ.
** אלא אימא שנמצאו -
ועכשיו מוסיף על המחלקת, לומר שחולקים אף בבתוך ארבע אמות. (כן מוכח מסתירה שמביא גמרא על שיטת רבי ישמעאל.) יש להעיר שלכאורה כיון שחולקים על בתוך ארבע אמות, אין הוכחה שחולקים על רחוק ממנו. ותו"ת.
** מנין לתקרובת -
קצת קשה, שרש”י לעיל פירש שאינו תקרובת, אלא עבודה זרה עצמה.
* נ:
** נגר... בר נגר -
ואם תאמר מה לנו בהיותו בן תלמיד חכם; “אי בר אורייתא הוא יאי,” כמו שאומר גמרא במנחות. ויש לומר שאם הוא בן של תלמיד חכם, אפשר ששמע מאביו. אז, מצדד שאף הוא לא קובע ללמוד בפני עצמו, ולא יודע כל כך כמה דברים, אבל אולי זה יודע, שאולי זה שמע. ועיין במה שנכתב בס”ד על רש"י.
* נא.
** צואה לחה -
לא הבנתי ל"ל אומרים שאין זה דבר שעובדים בו כמו אבנים, ואז אינו עבודת פנים. ותחשב. אולי זה רק לענין היותו תקרובת. וצריך לומר כעין מה שפרש רש"י גבי מקל, שעבודה שלה הוא באותו חפץ.
** בצרן מתחילה -
מסתמותו, משמע שלא צריך להיות לפני העבודה זרה להיאסר בבצירה זה. מעניין; ותחשב.
* נא:
** טובת אחרים -
אם כן, לשון “בין” קצת צריך ביאור.
* נב:
** אחרים תחתיהם -
קשה איך מוכיחים כן מן הקרא.
* נג:
** בדרך אחרת -
יש לדון אם זה סימן או סיבה. ותחשס.
* נז:
** אלא למד”א טמא -
משמע שכולי עלמא מודו בדין רוק של עבד, ורק חולקים בשל בן שפחה. קצת קשה למה נחלק (שרש”י כ’ שסיבה לדין זה הוא שמלו ולא טבלו לא שכיח. א”כ, לא נחלק. ותחשב.). ושוב ראיתי שרשי לקמן מפרש שקושיית גמרא אינו שאין דינים שווה, אלא שהוא פשוט. ותו"ת.  קצת צריך ביאור למה רק מפרש כן לקמן, ולא כאן.
* נח.
** אקפן -
נמצא מח’ אביי ורבא שהל’ כאביי. אולי שאני כיון שחזר בו רבא. צריך לומר שבתיובתא לא חזר בו.
* ס.
** מצידיה -
לא הבנתי כל זה כל כך, שלכאורה תחתון נעשה בסיס לצד כמו שנעשה ליין של פיהו. ותחשב.
* סא:
** היה נראה לומר
מכל גמרא זה שיוצא שלש דרכים לגוי לאסור יין:
1. אם נוגע ביין עצמו. ציור של זה הוא בחבית מלא.
2. אם משכשך יין.
3. אם מעמיד יין (כמו אם נתבקע).
4. על כולם, יש שלש דינים שיכולים להיות, והם מותר בשתיה, אסור בהנאה, ואסור בשתיה ומותר בהנאה.
5. גמרא דן במי שלא מכוון, ובמי שלא יודע מה עושה.
* סג.
** ליתיה בשעת ביאה -
יש לדון למה זה כל כך פשוט לגמרא, שהרי, אף שלא קרה ביאה כבר, נתן את זה לה בחילוף הביאה, שבגלל נתינה זה תיבעל לו.
** ואי מצטריך -
עדיין צריך ביאור מהו החידוש, שהרי אמר לה שאם צריכה, יכולה לקנות מיד, והרי קנתה. באמת, זה שייך למה שהערנו לעיל, למה צריך להיות בעולם בשעת ביאה.ח נראה שהענין, בביאור כללי, יהיה שצריך יחס בין ביאה לטלה. אם טלה אינו בעולם בשעת ביאה, חסר אותו יחס. אם יש לו להיות בעולם, אלא אם כן נצרך, אז יש עדיין יחס. ותחשב.
* סג:
** מקיפו -
קשה, שעדיין חסור משיכה וכדומה. אולי מה שסומך עליו די לעשות שהוא שכרו. ותחשב על זה.
* סד.
** ודאי בטלה -
קשה, אז, למה צריך למכור את העבודה זרה קודם, שיכול לבטל אותו ולגייר, שאז יכול להנות ממנו כשהוא ישראל. נראה שהמכירה הוא מעשה של ביטול.
יש לדון למה מכירה הוא מעשה ביטול. אולי הוא מפני שמוכיח שלא רוצה אותו עוד. צריך לדעת שהוא חושב כן, ולא רק שרוצה הממון, ואז צריך מה שיגייר. גם אפשר שמכירה הוא לעשות שבטל הוא כדי שיהיה ממון כשהוא ישראל ולא יכול לבטל אותו. אז, הוא מעשה שמוכיח שמגייר, וזה מבטל עבודה זרה. ותחשב. יש להעיר שצד השני הוא כעין גלגל החוזר. ותחשב.
** מדרבי יהודה -
יש לדון, שיש לחלק שאין זה נדחה, אלא הותרה, שאינו מתנת חנם, שאף הישראל נהנה ממנו במה שממעט איסור. משמע שזה יוכל להתיר אף איסור רוצה בקיומו. תחשב על זה. באמת צריך ביאור כל מקור לאיסור של רוצה בקיומה. ותחשב.
* סד:
** נבילות -
צריך ביאור מה מיוחד גבי נבילה שרק הוא לא צריך לקיימו כדי להיות גר תושב. ותחשב.
* סה.
** אנא מיהא -
לכאורה, אם לא ידע שיש עליו אימת מלכות, היה שמחה שלמה. אם כן, שמח כאילו היה בגן עדן. נראה שהיה מקשה לרבא שהיה לו אותו שמחה, ואמר רבא שיש לו יראה ממלכות. טען שלא היה לו אותו יראה, אבל ממה שבא מלך אחר כך, רואים שהיה משקר. ותו”ת.
** אבוה דראבדר”א -
אם כן, היה רב איקא. מצאנו כמו כן במק”א.
* סז.
** לא נחלקו אלא -
קצת יש לדון מהיכי תיתי שדין שניהם שווים.
** קדירה זו -
יש לדון אם ר"ל שעושה פגם של אותו דבר אחר או שמתוקן כאותו דבר אחר. ותחשב. מרשי נראה כראשון.
* סח.
** ראוי לגר -
יש לדון אם הענין הוא שאז אינו כל כך נבילה (חלק ממה שנותן שם נבילה הוא מה שיכולים לאכול אותו בטוב), או שאז אין אכילתו טוב, ואז אין אכילתו אסור. אפשר ששני גם יעשה שאין שם נבילה. ותו"ת.
* סח:
** מעניין למה
הוא חידוש שדבר מאוס יש בו איסור וטומאה. אולי כיון שהוא לא כל כך חשוב, מעניין שיהיו עליו דינים. ותחשב.
* עג.
** ראשון בטל -
קשה למה מביא ראיה מאיסרו כל שהוא, ששם בוודאי הוא כן אף בנופל לתוך היתר, שאין לומר שכל טיפה בטל.
** היתירא לאיסור -
קשה למה לא אומרים שאז כל טיפה של היתר שבא לכאן בטל.
* עה:
** שצריך הזאה שלישי ושביעי -
צריך ביאור למה הוה אמינא כן, שהרי אין נדה צריכה כך.
** תלמוד לומר אך -
צריך לומר ש”וטהר” לא היה יכול לומר כן בפני עצמו. יש לדון ללמה לא, שלכאורה אומר שאחר טבילה בפני עצמו טהור הוא. ותחשב. אולי היינו רוצים לקיים שני המקראות, ולפחת אחד מזה ואחד מזה, כיון שיכולים, ולפשר שצריך הערב שמש. ותחשב.
** מדיחן ומטבילן -
מעניין שצריך להדיחם, שלכאורה טבליה יעשה הדחה. אולי צריך להיות כבר ראוי לאכילה קודם טבילה.
