* מ:
** באנדרטי -
מרשי משמע שרק מבאר רבי מאיר. היה אפשר לדון אם זה גם מבאר רבנן. ותחשב.
* מא.
** הרי אלו -
עיין במה שבאר רש"י. יש לציין למחלקת בזבחים בענין אם מחמירים בביטול עבודה זרה. לכאורה, שם יש גם כן ספק ספיקא, ועדיין מחמירים. צריך לעיין, וצריך לחשוב.
אפשר ששאני התם שאיקבע איסורא, שבוודאי יש בעולם, בתוך ספקו של זה, עבודה זרה.
* מב.
** שלו ושל -
עיין לקמן, שדן בזה, שאולי בא לרבות גר תושב.
* מד:
** נוי מיהא -
עיין במה שמבאר. אם כן, לכאורה יהיה אםור אף אם בא אחריו. אולי רק ר"ל שלסיבה זה אינה גנובה, אלא יש גניבה אחרת. דחוק.
* מח:
** התם קאזיל -
יש להעיר שכל זה רק לפי השיטה שעבודה זרה ששבר מעצמה מותר. חלקו בזה ר”י ור”ל.
** שאם נטע -
גרמא- לכאורה, ר"ל שהוא סיבה כחוש, וזהו הדמיון בין זה לכל מיני גרמא. ודע שכל גרמא הוא אף זה וזה גורם. צריך לדון אם הוא אף אסור מחמת זה או כיון שהאו אף גרמא מותר. גם צריך לבאר מתי נחשב אותו סיבה אחר גרמה ומתי נחשב חלק מן הסיבה. ותחשב.
* מט:
** ונשתרי -
אגב, בשיטת ר”ש, קשה ל"ל נאמר שנהנה כיון שיקנה אותו יותר, שנותן יותר יין לממון, שלא תובע ממון לכל היין. יש לדון, שאולי לא נותן כל היד, אלא מאבד מקצתה. ותחשב.
** ואיבעית -
דקים- משמע שחילקו בין שברי שברים לשברים לא תלוי כמה זמנים שבר, אלא כמה דק הוא. זה מעניין. לולי רש"י, היה אפשר לומר שאותם פרקים היו נעשים מפרקים....
ודע שאין הוכחה, לכאורה, לגמרא לומר שאלו דומים לשברי שברים, ולא שדומים לשברים, ושברים אסורים, אבל אלו אולי מותרים. ותחשב.
** אלא דרך -
מעניין שמחשיבים מה שנפל להיות אחד שנפל בכמה חלקים, ולא נבייה זה בפני עצמה וזה בפני עצמה. ותחשב.
* נ.
** כעין פנים -
לא כל כך פשוט שאין עובדים לאבנים, שהרי זורקים דמים למזבח אבנים. אז, נראה לומר כגירסא שאומר עוז והדר, שאין עובדים באבנים. ותחשב.
אין לומר שר”ל שבבית המקדש עובדים לה’, ולא לאבנים, שהרי יש לומר כן בכל עבודה זרה אז, שבבית המקדש עובדים לה’, ולא לעץ ואבן. ותחשב.
* נ:
** נגר בר נגר -
אין זה כגירסא שלנו. יש להעיר שלזה מה שהערנו על גמרא בשי”ח ש”י לא כל כך קשה, שחכם בן חכם רצה לומר חכם גדול, כמו שנראה מפרק שביעי של בבא מציעא (רבי ורבי אלעזר בן שמעון). עדיין יש לדון ל"ל אומר “חכם גדול”; ואולי זה יותר פרטי כמה גדול הוא.
ודע שהנחתי שרשי לא גורס כמו שאנו גורסים בגמרא, אבל אין זה מוכרח, שאפשר שרש”י לא רצה לומר, “נגר בר נגר,” אלא “נגר... בר נגר,” ומפרש שזה חכם, וזה בן חכם. לא נראה כן, שכיון שפירש אחד, פשוט מהו חברו. אז, צריך לומר שדן בשניהם כיון שהם חד פריי”ז. אם כן, צריך לומר שלא גרס כגירסא שלנו. ותחשב.
* נח.
** לא הבנתי
כל כך מה שאומר גבי דמי דההוא חמרא, שאומר ששאר היין מותר. צריך ביאור מה נחשב אותו יין, ומהו שאר היין, ולא הבנתי אם רש"י אומר שאביי חולק על זה, ולמה לא הדר בו, אז, רבא.
* ע.
** יצרא דיין -
גם יש לומר שר”ל יצר לשתות אותו יין, שהרי היה לנו לחוש שהגוים נסכו. ועיין בגי’ שמביאים בעוז והדר על זה. ותחשב.
* עג.
** רואים -
לא הבנתי איך רואים כאן שחולק, שאולי יין במטל אם בא איסרו קודם. ותחשב.
