* ב:
** יש לדון מה בין
רוב מה בין רוב לסתם:
1. רוב יותר מעט מסתם.
2. אולי אחד הוא סטסיסטי"ק, ואחד הוא שמניחים בני אדם שכן יהיה. גם יש לומר שאחד הוא שכן נראה שיהיה על פי סברה.
* ג.
** משום עיגונא -
משמע שצריך שנים:
1. ראשון לא מהני להז’ אחד.
2. על פי ראשון, הו"א כעין דאו’.
** לאורועי נפשיה -
לא הבנתי למה צריך הא דאמר מר.
** ופסיל ליה -
ק’, שאף כאן, יכול על ידי שנים, ואיך זה חומרא. וצריך לומר שקולא הוא להפסיק בני אדם מלעשות מה שאינו טוב להם. ומעניין.
** בדין -
נראה שר"ל ממ"נ אם על שטר מעיד, אין חלוק בין זה לשאר שטרות. ואם על עדות מעיד, או שכיון שנוגע לעדות, צריך נאמנות, או ששטר עדות כעדות (ומעיד על שטר), צריך שנים, כעריותו שהעריות הוחזקו.
** אתי לאחלופי -
אטו בית דין יטעו:
1. בית דין יטעו.
2. בני אדם יטעו, ויחשבו שבית דין טועים.
3. בני אדם יטעו, ורע שיחשבו דבר שאינו נכון.
4. [כשיגלו] דין ק"ש, יפסלו את זה (יוציא לעז).
** מי אתי:
1. הנאמן (זה א"א מגמרא).
2. בני אדם.
3. מאן דחזי (ק’ על זה כעל הנותן. ועיין ברש"י)
בעל דבר מהימן- קשה; נלמד אף את זה כמו ע"א. (ויש לחלק שבע"א מסתבר כן (וכן הדין מדאורייתא), ובאלו אינו מסתבר כן (יש לדון אם זה דין דאורייתא). אלא בגט, שיש נאמנות לאשה, [ובס"ד]באומרת נתגרשתי. (וח’ שזה יעשה אותו מסתבר לעשותו מסתבר לכל אשה.)
בקיום שטרות דעלמא- ק"ק שהול"ל כמו באחרים, “כאן בפני מותר…" ואולי אף (וצריך ביאור למה לא. ואולי קבעי רבנן לשון. אולי שתהא קלייר, ואולי שלא יאמרו שצריך בפני. וקשה אם כן למה מבני באשה. ואולי אף זה קולא.) שם מועיל, ומה שלא ת’ בשאר ק’ הוא כמש"כ (ד"ה בעל דבר), ויש לתרץ, אז, אף את זה.
* ג:
** ולא בעי חתימה לשמה -
יש לחלק ששם זגירה ראייה (או אטו נתינה), וכאן אטו כ’.
** יש עליו… -
נראה שצ’, “אין… עדים" לרבותו לקולא, וע"א לרבותו לחומרא. ושו"ר שכ"כ תוס’.
- עיין ברש"י. ונראה שר"ל שיש בשניהם גם כן דבר יותר קל, שזה ביד הבעל וזה בעד, ויותר חמור, שזה בלי עדים, וזה רק בכסופר ומי יימר מי שכרו.
* ד.
** אנן מדאורייתא -
וזה קצת לשון מוזר.
** מיבעי ליה אלא לעולם -
ואם תאמר אם כן מהו הח’. ויש לומר שכיון שאינו מפו’ למה מחשיר ר"ש לעיל, פ’. ולי רשי, יש לומר שזה ק’ גמרא, “אטו צריך לגלות קרא, “ שאף שאינו קרא, רצה לומר שפשוט באד הוא. ודחוק.
מיבעי- יש לדחות שנקט לשון דיעבד. וצריך ביאור למסקנא למה נקט לשון בדיעבד.
** בגיטין -
יש לדון אם כיון שנגד סתם הוא הלכה כמותו. ותלוי באי אל שאין רוצים שזה אקספשי"ן (שלא נאמר שיש קרס’ במימרא) או שאין רוצים שאין הלכה כסתם משנה, שקשה למה סתמו (נראה שזה אפשר רק אם נאמר שלא כוון לעשות מה שעושה בכל סתם, אבל אם נאמר שרק אין הלכה כן, אינו קשה.)
* ה.
** דלא שכיחא -
קצת לא שייך.
ואמר ר"י- צ’ לת’.
* ה:
חולק
1. אינו בע"ד (שליח).
2. אינו נוגע (ועד הוא, שנמצא משקר)
3. דיין צ"ל יותר נקי מבע"ד.
4. אין שליח נעשה דיין (ששנים נעשים).
5. - אם כן, אין ק’ גמרא טוב (וק’ למה א"א כן)
שליח נעשה עד –> עד נעשה דיין ---> מש שייכות"
1. קצת בע"ד.
2. גדר בע"ד פסול (בכ"א חלוש)
3. בע"ד שאינו נוגע
4. תחשוב עוד.
** דעד נעשה דיין -
ק’, שהל’ שנים. וי"ל שכול קיימינן ליה. ועוי"ל שהל’ כר"י נגד ר"ח. ועפ"ז נוכל למבין מי אמר מה. ויש לדון, שאולי זה אקספשי"ן.
ולא סמכי עלה- ועוד אולי לא שכיח כמש"כ לעיל. ואולי זה רק באשתו קאמר.
לאתויי גיטא- כל דמגרש ע"ד רבנן. וק’ שלא אמר כדת משה… ואולי זה רק סימן. ויש לומר שר"ל אישות בידיהם.
הפגירו לגט.
* ח:
ק’ טעם רבנן הוא מפני שאף על עבד כןןם
ןךא מגד רבא
מס’
* ט.
לשחרורי- קשה הא אין עיגונא.
1. נעשה בזה דין ישראל, וזה טוב. קשה, שאסור לשחררו.
2. עיין תוס’.
3. נראה שהת’ למה שהקשה הוא שהאיסור נעשה כבר או לא, והדין רק במה נחשבו מספק. ותחשב. ויש עו"ק שאסור מראה שרע לו לעשות מעשי ב"ח. וצריך לומר שאיסור רק להיות ב"ח. ותחשב.
- למה צריך להביא שצריך להיות כריתות גמור, ולא רק שמניחים שלא כרתו.
