* ב.
** המביא -
כדאמר לקמן- מה שאומר לקמן הוא שנחשב לזה בבל כא"י. ואם תאמר הרי בכלל מדינת הים הוא, אלא שמשנה לאו דווקא אמר. ואולי צריך לומר דלא כזה (וכן, אולי, נראה, שלכאורה, אין צורך לים כדי לבא לבבל). גם יש לומר שכיון שיש לו שם אחר שנקרא, אינו בכלל שם יותר כללי. ויש לדון אם בימי תנאים היה כל כך חשוב עד שיהיה לו שם בפני עצמו (ומצינו שיש תנאים (כמו ר"נ ור"ח) שדרו שם). (יש להעיר שיש לדון מה מחשיבו. ויכול להיות כמה דברים, ואפשר שהוא מה שהיו שם ישיבות).
גם אפשר שרש"י רק אומר מתי דין משנה נכון, ולא מבאר הלשון. לשון רש"י לא משמע כן כל כך.
** רבי יהודה -
למזרחו- ומשמע שבעולם הוא פלא"ט. ואולי לשון שמבינים בני אדם נקט.
* ג.
** גייז -
יועד יש לומר שלא על מילים, אלא על דברים, קאי.
* ג:
** אין כותבים -
ומפסיל כדפירשתי-
1. יבא ל"גרש" בו.
2. יהא בל תשחית
לולי רשי:
1. לא יבינו בנ"א בין חתם במחובר.
  1. יחשבו שחתם במחובר כשר.
  2. יחשבו שהעיקר הנתינה, לאחר חתימה, וזה בתלוש.
* ד.
** ומיעיקרא -
ומהדרינן- אינו מק’ על מה שדחקנו לומר מזוייף שאי"ז דוחק, שכן, למסקנא, הוא הדן לר"מ ואינו [נתח] מפני זה. כן נ’ לשון גמרא.
* ה.
** אי הכי -
דלמדו- דעל זה קאי (ויש לדון מה מח’).
* ו.
** עשינו -
אולי משמע רק אז.
למה א"א כהו"א.
* י.
** חוץ -
ועוד שאין קונים גוף, ואז אינם בתורה זה.
- משחריים ממון.
- נשתחררים.
