1. ב”א רש”י ד”ה שלנה- עיין לקמן, שדן בגמרא בפירוש זה.
2. ב”א גמ’ כמה דחנקינן- ע’ לקמן, שי”א שמעילה של מת’ הוא מדרבנן. א”כ, החידוש הוא גופא שיש מעילה. ק”ק למה פשוט שיש מעילה, אחר שיש מד”א בגמ’ שאין בזה מעילה. צ”ל שמד”א זה הוא רק אחר ממרת ר”י.
3. ב”א הואיל וקבל בצפון- לכאו’, מניח שפסול בשחיטה אינו פוסל כ”כ. יל”ד אם זה נחשב פסול בשחיטה, שעושה שהדם לשאר דברים פסול.[fn:1] אפשר שאומר שפסול בדם אינו כ”כ פ’ כפ’ במעשה. תח’. וא”ת שנת’ ששניהם פ’ בחפץ, ופסול קבלה יותר גדול, כיון שקבלה יותר חשוב. אין לת’ כך, שהרי עדיין בשח’ יש פ’ בדם של קבלה, משא”כ בקבלה. יל”ד, שאולי אין לפ’ דם של קבלה, שאצ”ל דבר מסויים, שאולי אף הוא רק להכשיר דם לזרוק.
4. ב”א גמ’ מרצה- יש לדון אם זה סימן או סיבה. אם סימ’ הוא, אומר שכיון שמרצה לפיגול, צ”ל שאינו כחולין לגמרי. אם סיב’ הוא, צ”ל שכיון שעושה ריצוי זה, חשוב, ועושה ריצוי אחר.
5. ב”ב רש"י ד”ה מהו שירדו- לכאו’, בא לפרש שאם ירדו, לא רק יכולים לרדת, אלא חייבים. כן הוא הדין, אבל נ’ שי”ל שנקט לשון זה כיון שמה שלא צ’ לירד יהיה מפני שלא יכול. דנים אם מז’ עושה איסור לירד שדוחה איסור לקיימו על מזבח.[fn:2]
6. ב”ב גמ’ מעילה- יל”ד מהו הראיה מכאן. אפשר שאילו לא היה קודש, לא היה מזבח עושה שהוא טוב להק’. גם אפ’ שאז היה יותר רע להק’, עד שהיה טוב של מזבח נדחה. (צדדים אלו מניחים שאם עלו לא ירדו דוחה חיוב לרדת. אפשר שמתיר, שמשנה עד שאין ח’, ואז פשוט שיש לומ’ רק צד אחד. אף בזה יש לדון אם שינוי של מז’ אינו כ”כ גדול, ואז לא הותר, או שהאיסור חלוק, ואז לא  הותר.)
7. ב”ב גמ’ דרבנן- מעניין שמסכת מעילה יתחיל עם מעילה דרבנן.
8. ב”ב רש"י ד”ה חומש- מפני איל- יש גו’ בהדי. יל”ד אם ר"ל שאיל מהני לחומש או שחומש מהני לאיל (או שניהם).
9. ב”ב גמ’ אבל קדשים- יל”ד למה בדילי מנבילה. אולי הוא מפני טומאתו. סתימות רש"י לא מש’ כן. גם י”ל שהוא מח’ שבדר”כ לא יכול לאכול אותם. יל”ד, שיכול להנות. גי”ל שסתם בהמה שמת מאיליה הוא מאוס, שאולי הוא חולה. יל”ד מה אם מת בלי שחיטה, אבל ע”י אדם.
10. ב”ב גמ’ בדילי- לכאו’, היה קל לת’ שכיון שהוא כ”כ פסול, הו”א שאין מעילה מדרבנן, שאין צורך, שאינו כמצב מעילה דאו’.
11. ב”ב גמ’ עד שיפגם- לכאו’, ההסבר הוא שמה שעשה אינו קרק’ של חפץ כיון שהחפץ לא חשוב מח’ גופו, אלא מח’ מה שיכול לקבל ממון, ולא עשה דבר ששיך לזה. יל”ד, שזה מניח שצ”ל שמעשיו הוא קרק’ של חפץ. אולי זהו מה שמחלל אותו. ותו”ת.
12. ב”ב גמ’ נמי תנינא- עיין בפרש”י שזה  מוכיח שאין מעילה.לשון "תנינא" מעניין, שבדר"כ אומר שכבר נשנה. לולי רש"י, הומ"ל שמק’ שכבר תנינא, שלמה נחלק. ע"ז תלוי אם גור’ בת’ כב"ח או לא, שאם לא גור’ כב"ח, צ"ל נגד רש"י, ואם גור’ כב"ח, צ"ל כרש"י. ותו"ת.
13. ג"א גמ’ בדילי- לכאו’, הסברה שבדילי כ’ רש"י ש"מחיים בדילי.” נמצא שרש"י סובר שלאח"מ בדילי כיון שמחיים בדילי. לכאו’, זה כיון שהיה לכפרה, והוא קדוש מאד. אם לא בדילי, אז יהיה הענין שהוא מרגיש שהוא שלו, שעושה לו דבר (כפרה).
14. ג"א רש"י ד"ה חטאות- לשון "כגון" מעניין, שמש’ שיש עוד ציורים כך.
15. ג"א רש"י ד"ה לא נהנים- הוכח’ ק"ק. אולי מכוון לומ’ שאם ר"ל שאין מעילה מדאו’, שמשמע שיש מדרבנן, הרי כבר אמ’ שאין נהנים. זה אינו, שלא הוכיח הדיוק, כי אם מ"לא נהנים.” אם ר"ל שממה שאמר שלא נהנים, רואים שאין מעילה, שלא נהנים משמע שרק לא נהנים, ולא יותר, אף זה אינו, שק’ למה מש’ כן, שרק מש’ שאין נהנים, וזהו. ותח’.
16. ג"א גמ’ תיובתא- א"כ, נפ’ כר"י. ק’, שהל’ כרבה חוץ משלש. צ"ל ששייר. גי"ל שרק מז’ מקו’ שפוס’ כן בלי חזרה מרבה. דחו’.
17. ג"א גמ’ רב יוסף- יש לצ’ לגמ’ הוריות שקורא לר"י סיני.
18. ג"א רש"י ד"ה איתיביה- בפ’ הסמוך ליה- מוזר שלא הז’ שמו. אולי שכח רש"י.
19. ג"א גמ’ קלטוה מחיצות- יל"ד מה קלט אותו: המחיצות או מה שעומ’ למזבח.
20. ג"ב גמ’ אפיל’ לר"י- יל"ד ל"ל יק’ מזבח: אם הוא מפני שלא קדוש כ"כ, או מפני שלא קדוש למזבח.
21. ג"ב רש"י ד"ה תיקו- צ"ב מה רש"י אומ’, שנ’ שאומ’ שלהי’, יש כאן ראיה שהיה מסו’. לא נ’ שזה אפ’, שאין ראיה, שאולי סבר כר"י, ולכן שאל. ותח’.
22. ג"ב גמ’ ואינו מביא- יל"ד ל"ל יכו"ל רק גבי קק"ד, ונדע שני הדינים, ששניהם שייכים בקק"ד. יל"ד, שזה מניח שמעילת קק"ד אחר זריקה שווה לשל קק"ל. יל"ד, שאולי הוא שרק נשאר. לא נ’, שעכ"פ, לא יהיה חלוש מקק"ל. י"ל שכיון שיותר ק’, פיגול יותר פ’, ואין מעילה.
23. ג"ב גמ’ עד שלא קרמו… אחת- יל"ד למה. אולי הוא מפני שכשיש סיבה על הרבה דברים, אם לא חל כולו, לא חל כלל. לכאו’, זה מפני שהסיבה הוא על כלל של כולם. ותח’.[fn:3] גי"ל שכדי שיק’ צ’ לא רק שחיטה בכש’, אלא אף שיש טוב בק’. כשיש פחות מארבעים, אין טוס, ואין ק’.
24. ג"ב רש"י ד"ה ולחמה- על בסמוך- צ’ רק על, אלא שרש"י מפ’ שעל כאן ר"ל סמוך. ותו"ת.
25. ג"ב גמ’ אלמא פיגול- יל"ד מהו הראיה, שלא אומ’ שמוע’. אולי אם ק’, מוע’, שזה ממשעמעות קדו’. גי"ל שאין נפק"מ לג’ חוץ ממעי’ כאן. גי"ל שאם יש דיני ק’, זה סימן שיהיה אף דיני מעי’, שלמה יהני זרי’ פיגול לזה ולא לזה.
26. ג"ב רש"י ד"ה קומץ פיגול- דמיפרת- יל"ד למה הדין נכון גבי קומץ. אולי הוא מח’ שכולו נח’ חפץ אחד, אף שאל מחוב’, כיון שהוא כולו עושה כפרה אחת. גי"ל שאותו הרצאה שעושה מז’ כשדבר מושל בו עושה דבר לכל הקומץ. ותו"ת.
27. ג"ב גמ’ איסורא- לא הבנתי מהי"ת שפגל בק’, שאולי הוא חפץ של קומץ, והוא פיקול, שפגל בהק’. וי"ל שכן מבואר גמ’, שכוונתו להוכיח כן ממה שיכולים לפגל בהק’.
28. ק"ק איך יש הוכחה כיון שאינו מח’ פיגול, שהוכ’ ממה שלא מונע עשיית פיגול. צר"ב מהי"ת שפג’ של קמ’ מונע פיגול.
29. ד"א רש"י ד"ה מחלוקת- צריך להג’ מח’ של מתחילה וע"סוף. אם מי שסובר שהוא בסוף סוב’ שאין תח’ חלק מן העבודה, ואז מח’ בו לא פוס’, קשה איך שום מח’ פוסל, שצ"ל בסוף, ואז אין בו זמן. אולי רק צ"ל מקצת המח’ אז. יש לצ’ לתוס’ בקללת בלעם. גם אפשר שסוף רק ר"ל סימן שני, וכל הסימן. א"כ, ק"ק למה א"א לח’ בו שני מח’. אז, נ’ שא"א לומ’ כן. ויל"ד, שאולי יש רק זמן למח’ אחת.
30. ד"א גמ’ אי בשתי- ילה"ע שיוצא שמח’ חול"ז בזמן שלא מפגל מונע מפיג’. אעפ"כ, אילו כבר חשב לפיג’, נתפגל בזריקה.[fn:4]
31. ד"א גמ’ לאו לחיובי- לא הבנתי, שמי יימר שזרק במח’ פ’. גם ק’ ל"ל הק’ כן מיד.
32. ד"א גמ’ אי דלא זריק- ועוד של’ לעולם לא מש’ כן.
33. ד"א גמ’ מאי למימ’… פשיט’- יל"ד למה אומ’ שני לשונ’. אולי לא נשמע טוב אם אומ’ דבר א’ שני פעמ’ זה קרול"ז. (יש לצ’ לרש"י שכ’ בסו"ד פשיטא מאי למ’.)
34. ד"ב גמ’ רישא מאי- ק’, שלכאו’, הוא אותו ראיה.
35. ד"ב גמ’ בידים- ק’, שלא עושה בו מעשה. ויש לומ’ שהוא מח’ שלא עשה מעשה. ק’, שפיגול הוא מח’ שחשב. י"ל שחיל’ בין אם חשב ללא חשב אינו דבר שיש בו מעשה (או שמורגש). אינו כן בהלנה, שיש חיל’ שמורגש. יל"ד, שהיה דרך אחר שלא יהי’ פיג’, והוא אם לא זר’. א"כ, יש חי’ מורגש. וי"ל שלא רק מחפ’ לחי’ בין אילו היה פסול זה לאי לא היה, אלא לח’ בין אילו היה כשר ליש בו פסול זה. לא היה כשר בלי זרי’, ואז אין ח’ מורגש. גם י"ל שר"ל שהלנה עושה שינוי בקרק’ של חברו. ואם תאמר פיגול גם משנה קרק’ של חפץ, שנח’ עליו. י"ל ששינוי בחפץ אינו הסיבה לדין. גי"ל שאינו שינוי כ"כ גדול. יל"ד בזה.
36. ד"ב גמ’ לימא הואיל- יל"ד אם ר"ל שנימא שסיפא ראיה לדין של ר"ג, ואז נפ’ רישא כך. ק"ק, שכיון שיש לנו ראיה, לא צ’ עוד ראיה להיו’ מיוסד עליו. אז, נ’ שאומ’ שכיון שסיפא הוא בסגנון זה, אף רישא כן. קשה, שאז דחי’ של גמ’ (על ראשון) לא מובן. גם לא מש’ כן מלשון "הואיל ומסייע…,” שאינו נל’ ממה שסיפא מסייע.
37. ד"ה גמ’ פסיקא ליה- ילה"ע שלא פסיק, שהוא רק בקק"ל, כמו שזה לא פסיק, שהוא רק לאחר זרי’. י"ל שלא פסי’ במה שהוא רק לאחר זרי’, ורק בבשר, ולא באימורים. אז, יש שני ממעטים.
38. ד"ב גמ’ בר פדת- הע’ לי א.מ.ו. שאולי זה ר"א בר פדת.
39. ד"ב גמ’ היתר- יל"ד אם דנים מתי מותר או רק מתי אין מעיל’. ותו"ת. אם דן בהיתר אכילה, אז, מובן למה ינקוט כל אחד להיות זמן של היתר מעילה. אם דן בהיתר מעילה בלחו’, מובן למה ינקוט היתר אכילה (שאז, ממה שאוכלים, רואים שאין מעילה)[fn:5], ולמה ינק’ היתר זריקה (שאז עומ’ להיתר אכיל’, שרק צ’ זריקה). צ"ב למה ינק’ היתר שחיטה. אולי סוב’ שאף זה עומד להיתר אכיל’. גי"ל שסובר שלא תלוי בהיתר אכילה (יל"ד במה תלוי, ומהו המקו’). ותח’ ע"ז.
40. ה"א גמ’ ושקבלו- צ"ב איך יבאר חזקיה את זה.
41. ה"א גמ’ וזרק’ כשרים- ק’, אז, למה צ’ להז’ אותו כלל, שהול"ל רק שק’ פ’.
42. ה"א גמ’ חטאת פ’- היה אפשר לבאר צד לומדי בכביסה. אפשר שאינו דין בדם (צ’ לכבס מה דם כשר), אלא דין במזבח. בביאור יותר, הענין הוא שנמצא שהבגד עשה מעשה מזבח, שקבל זריקת הדם[fn:6], ולכן צ’ כיבוס. נ’ שאולי זה יבאר למה דין זה רק כשנפל עליו דם חט’ כ’, ולא פ’. גם יבאר למה דין זה רק אם לא כבר נז’, והוא שכיון שנז’, כבר עשה מז’ מעשה מז’, וא"א לזה לעשות מעשה מזבח. ותח’.
43. ה"א גמ’ כיבוס- יל"ד למה צ’ כיבוס, אם הוא כדי להסיר הדם, שצ’ שלא יהיה דם חטאת ק’ בו, או לסיבה אחרת[fn:7]. ותח’.
44. ה"ב רש"י ד"ה ואי ק’ לך- ילה"ע שבדר"כ גמ’ מבאר למה אומ’ דבר שהוא ל"ד. מעניין שכאן גמ’ לא מבאר, וצ’ שרש"י יבאר.
45. ויל"ד מהו ת’ של רש"י. אולי הוא שתני פסול זה אגב שאר פסו’, כיון שאף בו הדין נכון. גי"ל שר"ל כמש"א גמ’ ביבמות (לה) שבלע ציור שדומה כיון שהוא דומה. כמו"כ י"ל (וחוש’ אני שמצאתי כעי"ז במק"א) שכיון שדרך של אלו להימנות ביחד, כ’ את כולם אגב רהטת לשונו. ותח’.
46. אפ’, באמת, שאלו הם הפ’ בכל אגב, שאצ"ל שהוא כדי שיהיה נראה טוב, או כדי שיהיה קל לזכ’, אלא אולי הוא מפני שהיה תנא כבר עוסק בלשון כעי"ז ברישא. אולי לכן יותר קשה לומ’ רישא אג’ סיפא, שמניחים שכ’ רישא קודם סיפא, ואז יותר קל לומ’ טעם זה (ואולי צ’ לשנות הטעם כשאומ’ שרישא אגב סיפא).
47. ודע שאין ק’ גמ’ דוח’ מש"כ כאן, שאולי רק לא נניח בכעי"ז סברות שכ’, אבל בשאר אגב שאומ’, נניח. ותו"ת.
48. ה"ב גמ’ תרי- לא הבנתי למה יותר קל לשנות אחד שהוא ל"ד. נ’ שר"ל שאילו היה אומר אחד דווקא, וחבירו אגבו, היה טוב. יל"ד למה יותר קל לומ’ שהוא אגב זה מלומ’ האגב שאומ’ רש"י. ותח’.
49. ק’, שאילו היה ר"ל כן, אז היה אומ’ רק כראי’ גמ’ לעיל. היה אפ’ לומ’ שאף בא לדחו’ ראי’. לא נ’ כן מרש"י. אז, נמצא שצ’ שלשניהם יהיה סיבה. צ"ב, אז, בלשון ק’ זה.
50. ה"ב רש"י ד"ה לאו כלום- א"נ- לכאו’, צ"ל שדין ראשון של רש"י נכון, שזה בא גמ’ לומ’. אולי רק דן אם דין שני נכון. יותר נ’ לומר שרק מביא עוד דין, ואינם שני לשונ’, אלא שני נפק"מ.
51. ה"ב גמ’ עושה שיריים- לכאו’, זה אומר שק’ וז’ פ’ עושה דבר. אפ’ שהוא מפני כוח מז’ (כמו שמק’ כל פ’). (תלוי באם דין זה אף אם רק קבל, ולא ז’. ויל"ד, שאף שם נ’ שיוכ"ל שהכלי מק’.)
52. ודע שצ’ לחקור אם שיריים זה הוא אותו שיריים של ריצוי רגיל או לא. אולי תלוי על זה מה שאומ’ רש"י שעושה שצ’ ללכת ליסוד. ותו"ת.
53. ה"ב רש"י ד"ה הא קמ"ל- יל"ד בחי’ בין פגול לשאר פ’. אפשר שפגול הוא פסול ביותר. ק"ק, שבדר"כ לא אומ’ כן, כיון שמרצה לפיג’. אפשר לומ’ שמזבח לא מנתק אותו לכשרות כיון שכבר עושה עמו ד"א, שהוא פגול. גי"ל שפס’ ר"ל שאין בו כש’, ואז מז’ נותן בו כש’, אבל פגול ר"ל שיש דבר רע נתוסף, ואין מז’ נוטל זה. (אפשר לומ’ גם להיפך, אבל לשון שמזבח מק’, ולא מטהר, לא מש’ כן.)
54. ע’ לקמן שיאמר גמ’ שריצוי לפיג’ הוא סיבה שיעשה שיריים. קל להפך שני הסברות האח’. גם קל לומ’ שיש קצת סיבה לכשרות כבר, שמרצה לפיג’. ותח’. גי"ל שריצוי לפיג’, ואף לא ריצוי של כש’, עושה שיריים. ותו"ת. (זה חלוק משל מש"כ לפני"כ, שזה אומ’ שאין הענין ששל פיג’ דומה לשל כש’, אלא עשוים שיריים אעפ"כ. יל"ד. ותח’ עוד.)
55. ה"ב גמ’ ר"ל מר"י- ילה"ע שר"י גופא צ’ לחלוק ע"ז, שלא סובר שהיתר ז’ שנו כאן, אלא היתר א’. א"כ, צ"ל שסובר שמשנה אינו דווקא. אולי מניח גמ’ שעדיין יש לו להניח שאחד דווקא. דחוק.
56. ה"ב גמ’ אלא חוץ- היה יותר טוב אם היה אומר חוץ מחוץ לזמנו או כדו’. המבין יבין שזה קצת מיל’ דבדיח’.
57. ה"א גמ’ היתר אכילה- יל"ד למה לא יהני היתר זריקה, שאז הוא עומד להיות מותר. יל"ד אם יסוד מח’ הוא אם עומ’ מהני לזה או אם הוא עומ’. ותו"ת.
58. ו"א רש"י ד"ה ולא הוה שהות- צ"ב למה צ’ שאוכל בלילה, שאף אח"כ, אינו כשר להק’, שלן, ונמצא שלא היה לו שעת הכשר. ותו"ת.
59. ו"ב גמ’ רבי אליעזר- יש לדון למה יוצא ונכנס אין זריקה מועיל לו. נראה ששני צד’ העיקרים הם שהוא מח’ פס’ או מח’ שלא מיוחס די לדם. ביטול יחס הוא או פסולו או מחמ’ שהיה זה פסול, שהיה יוצא. ותו"ת.
60. הקל וחומר יובן על שני הדרכים, שמה שאינו מגופו הוא יותר פסול, במה שאינו חלק מן הקרבן, ואינו כל כך מיוחס, שאינו מממנו. ותו"ת.
61. ו"ב רש"י ד"ה לאתויי- מניח שהחי’ הוא שזה חומ’ וזה קול’, ומס’ שיכול לעשות חומ’ משיכול לעשות קול’. יל"ד, שאולי רק אומ’ שהכנסה להק’ הוא חלות יותר קל. ותו"ת.
62. ו"ב רש"י ד"ה איתמר- מש’ שהוא מפני שתוצאת זריקה ע"ז גורם כך על זה. היה אפשר לומר שגם אין פסול בזה מח’ שאין פס’ בזה. נראה שהיה אפשר להק’ בכ"ז ל"ל אומ’ להיפך. נ’ שצ"ל שמה שיש בו דבר גורם למה שאין דבר (שנותן דבר, וא"א לתת העדר דבר). ויל"ד. א"כ י"ל שפסול הוא דבר (אי"ז מוכרח, שי"ל שהוא רק שאין בו ק’), ואז היה לנו לפ’ את כולו. הרצאה הוא דבר, ואז יש לנו לרצות את כולו. (הול’ בתר הרצאה כיון שהוא מה שיותר נוגע, שבו דנים.) ותו"ת.
63. ז"א רש"י ד"ה עומד- הוכיח- מעניין שזה נח’ עומד, ושאין לו דין שאר עומד, כיון שנחשב עומד. נ’ שזה מת’ לזה, שלא ממש עומד, ורק קורא להם עומד מח’ זה. ותו"ת.
64. ז"א גמ’ ומי אמר ר"א הכי- לא מת’ לזה, לכאו’.
65. ז"א גמ’ תנ"ה- אי"ז כ"כ ראיה, שי"ל שהוא ר"א. אולי לא הו"ל לנקט ציור זה, שהוא יותר פשוט להיות כדינו.
66. ז"א גמ’ בב"א- כמובן, קצ"ב כיון שא"א לצמ’. אולי ר"ע סובר שאפשר. ותו"ת. וצלע"ש. נ’ שאם נאמר שיש לש’ מתחילה וע"ס, אינו ככ"ק, שיש המשך זמן, ואולי לא צ’ להתחיל זה בשעה שמת’ זה. לא נ’ כן, שלכאו’ בתחילת שח’, ידחה זה. ויל"ד.
67. ז"ב גמ’ להח’- צר"ב למה משנה כופל ע"ע כ"כ.
68. ז"ב רש"י ד"ה פגול- רש"י מניח שפגול נמנה במשנה לעוד חומ’ של לאחר זריקה. הומ"ל שרק מונה חומ’ של מעיל’. זה רק בא אגב (כיון שדן בדינים שמשנים בין לפני זריקה ללאחריו).
69. ח"א גמ’ נמלקה- יל"ד מה לנו במליקה. י"ל שזה מקריב אותו לכפרה. גי"ל שאז עושה בו מעשה חטאת העוף (ומיוחד לו, שאין כ"כ סיבה לעשות כן אא"כ רוצה להק’). כמוכי"ל שכיון שעושה שרק עומד להק’, הוא יותר ק’. ותו"ת.
70. ח"א גמ’ איסור יוצא- יל"ד אם איסור זה שייך לאיסור מעילה (למשל, אין זריקה פועל עליו די) או לא (ורק הובא כאן אגב). אם נאמ’ כשני, הוא מאד אגב; ואפשר לד’ בקל שבא לבאר דינם לענין מעילה (כיון שהיה כבר דן בהם), ואגב, כיון שהוא אסור, קרא לו בלשון זה.
71. ח"א גמ’- יל"ד אם לאחר זריקה, אין סיבת מעילה, או רק אין איסור. הצד שאין סיבה הוא שחלק מן הסיבה כולל מה שה’ ייחדום לעצמו, ולא לבנ"א. ותו"ת.
72. ח"א גמ’- צ"ב ל"ל מתחיל ודן בקרבנות, אלא בעופות. ותו"ת.
73. ט"א גמ’ תראה- ק"ק למה יתלה בזה, שלכאו’, הענין הוא שכבר נתרם, ולא שנראה לדשן. י"ל שר"ל שרק נ’ לדשן. ותו"ת.
74. ט"ב גמ’ שפקעו- לכאו’, העני’ הוא שהיותם ע"ג מזבח הוא שנותן להם ק’. ותח’. קצ"ב איזה מעילה שייך, שצ’ שעדיין הוא במז’. אולי יש מעילה אם נוטל אותו מעל מז’, שמוריד אותו מק’. ותח’.
* Footnotes
[fn:1] באמת, אפשר שאין פסול בשחיטה חוץ מזה, שרש”י כ’ שענין שחיטה הוא רק להוציא הדם לזריקה.
[fn:2] אולי הוא יותר חזק, ואולי שב ואל תעשה עדיף. נראה כצד שני, שאי לאו הכי, קשה למה לא יעשה כן לכתחילה, שנמצא שהוא עושה טוב. ותחשב. היה אפשר לדחות שאיסור העלאה חלוק מאיסור קיומו שם, ולא רק מפני שזה קו”ע.
[fn:3] צ"ב מה זה אומר. יש לדמות אותו לענין של קרבן ציבור. צריך ביאור אף בזה.
[fn:4] ר"ל, שלא יכו"ל שענין זמן הוא רק למח’ פיגול, ולא למח’ חול"מ.
[fn:5] יל"ד אם זה סימן או סיבה.
[fn:6] יל"ד, שלכאו’, א"צ שיבא לדם מח’ זריקה כשרה. עדיין, אולי דומה די.
[fn:7] למשל, הדם משנה הבגד באופן שהבגד צ’ כיבוס. לכאו’, קל למצוא אם זה נכון, שיש לעיין אם כל הבגד צ’ כיבוס או רק אותו מקום של הדם. ותח’.
