* כה:
** רש"י היו עליות -
שוערים- גם יש לומר שפתחו וסגרו השערים. עיין בגמרא ערכין יא: שמשמע כן. ותחשב.
* כו.
** גמרא מי שטבל -
יש לדון אם צריך ומר להם ממש, שמסתמא יבינו למה בא.
** רש"י קרות הגבר -
עיין ביומא, שהוא מחלקת שם.
** רב אשי -
צריך ביאור מה אומר. לכאורה, גמרא דורש שנכתב לשון שמירה שלש פעמים. ויש לדון, שאולי חד למשה, חד לאהרן, וחד לשני בניו. נראה שכיון שאינם בחד מקום, כל אחד במקום עצמו. יש לדון למה מניחים כן. ותחשב.
* כו:
** רש"י אמר אביי -
ובבית קדש הקדשים- קשה, אז, למה צריך שמיר. ותחשב.
* כז.
** גמרא ואיכא תנא -
לכאורה, ר"ל שכמו שמצאנו מחלקת שיש אומר שהיו שמנה, גם אולי יש חולק אחר שאומר חמש. זה צריך ביאור, כמובן. ויש לדון, שאולי כיון שרואים שלא היה הקבלה בזה כל כך טוב, יש לחשוב שהיה עוד טעות בו. ותחשב. עדיין יש לדון ל"ל עושה כן גמרא במקומות אחרים.
* כח.
** גמרא אלמא לאו בפייס -
קשה, שנדייק מזה גם שלא תלוי בריצה, שרק תלוי ברצונו. אולי מדייקים שלא באים כמה בני אדם, שאי לאו הכי, לא יכול להניח שיהיה לו, וממילא פשוט שאין פייס. ותחשב. גם יש לומר שמסתמא מי שיותר רוצה ירוץ יותר, ויזכה. ודחוק.
** אבוקות של אור -
קשה, שלכאורה, כל אבוקות הם של אור. ותחשב.
** ורשות היתה לו לשרוף -
יש לדון בחילוק שני לשונות אלו:
1. היה חייב לעשות ראשון, אבל רק היה לו רשות לעשות השני.
2. היה רשאי לעשות שניהם, ודרכם היה לעשות הראשון.
לא נראה כצד שני ממש"א גמרא שהיו אומרים שהוא קולו של בן לוי שהיה בגדו נשרף. ותחשב.
** רש"י קל וחומר על אונס שינה -
יש להעיר[fn:1] שאינו אנוס, שלא לעולם בא לשינה (fall asleep) מחמץ אונס. ונראה שמביא גמרא ראיה ממה שלא משמע שמחלקים בין שינה[fn:2], שלפעמים אדם נופל לשינה מחמת אונס, ואף על זה היו שורפים.
* כח:
** רש"י צבר -
וקים להו- מעניין, שאין זה השלכה רגילה של עוף, ששם אומר גמרא שרואים מזה כמה חזקים היו הכוהנים, שהיו יכולים לזרוק כך. ותו"ת.
** מפני שהוא -
שבח הוא לבני אהרן- יש להעיר על לשון אותו גמרא שלכאורה משמע שהוא שבח לבני אהרן ולא למזבח. צריך ביאור למה יהיה שבח להם[fn:3], ולמה על זה מקפידים יותר משבח המזבח.
על כל פנים, אז אי אפשר לרש"י להביא ממנו ראיה כאן. ותו"ת.
* כט.
** הן-
היה אפשר לקרוא שזה התירוץ שכן הוא, אלא יש שאינם כשרים. הבעיה בזה הוא שאז היה לו לומר שאינו כן. אז, מפרש רש"י ש“הן“ הוא חלק מן השאלה. (עדיין קצ"ב ל"ל אומר, ”לא.“ ויש לדון אם צריך לומר כן, שאומר את הדין שיבאר את זה.)
** הן -
מעניין שמצאנו שני פעמים שמשניות אלו שואלים ומשיבים, מה שלא מצאנו ששאר משניות עושים. נראה לבאר על פי מה שמבואר בזבחים ויומא שמצאנו מסכתות שנתחברו מתנא אחד לכל מסכתא. אם כן, אולי תנא של משניות אלו כתב כן. ותו"ת.
** רש"י בעומד ה -
צריך ביאור למה אין שני דברים שהזכיר (אין עניות במקום עשירות והתורה חסה על ממונם של ישראל) לא רק עושים סתירות כאן. וצריך לחשוב.
* כט:
** רש"י עיין בקושייתו
איך היה מקום לכהן ללכת. אין זה כל כך קשה, שאולי דחק את הפרוכת קתץ כשהלך. ויש לדון אם יכול לעשות כן.
* לא.
** רש"י נטל -
כל כך כמו הראש- יש לדון אם יש יותר דם על ראש או שדם על ראש הוא יותר מגונה.
* לא:
** גמרא כעקידת -
יש לדון איך יודעים איך היה עקוד (ואף אם יודעים, מוזר לתלות בו, שהוא תלי בדלא תניא).
** רש"י שמעלין -
לגירסתו, שיש עשר שולחנות, קשה ל"ל מונה את של משה. ותו"ת.
* לב.
** גמרא ולא כסי בה מידי -
יש להעיר שיש דרך קל לדעת מי נכון, והוא לראות אם החמה הוא יותר גדול באמצע מבמערב. ותחשב.
** מניח גמרא שחמה
רק הולך עד סוף העולם, ולא שהולך עד רחוק ממנו לפני שיורד. ודע שאפשר ש“סוף העולם“ ר"ל סוף הליכת שמש, ולא סוף של הקרקע.
** חמרי לובאי -
יש לדון ל"ל אמרו כן מתחילה.
* לב:
** גמרא באתרך -
קשה, שאולי בא לכבוש, ורק אחר כך הכיר שלא היה יכול לכבוש. אולי שואלים למה לא חזר לעירו. לא משמע כן מרש"י, ולא נראה שהוא קושיה טובה, שהיה קשה.
** רמב"ם שלש ברכות -
קשה, שמזכיר ארבע.
** ואין הלכה כרבי אליעזר ב"י -
קשה, שהכלל הוא שהלכה כמותו בכל משנה, שמשנתו קב ונקי.
** בגדים -
היה אפשר לומר שזה רק אומר שצריך לשנות בגדיו. אם כן, לא צריך להיות פחותים. ותחשב.
* Footnotes
[fn:1] באמת, יש להעיר אותו על גמרא, אבל התירוץ שנשיב הוא יותר דחוק בלשון רש"י.
[fn:2] שלא אומר שהיו שואלים אותו קודם שהיו שורפים את בגדיו וכדומה.
[fn:3] אולי מגלה שהם עובדים אף אם הוא קשה להם, שיטנף אותם.
