הואיל וכתיב- לכאורה, אין צריכים זה; היה לנו לומר,”הואיל ואמר מר,” שאמרו כאן, גבי סוכה. וצריך לומר שגמרא רוצה לבאר שגבי סוכה אומרו, שאינו כל כך פשוט לכל קורא הגמרא, ואז מביא קרא שכתוב כאן.
בני עבודה- לכאורה, הענין הוא שאי אפשר לשכוב עם אשתו שמא יטמא, ואז לא יוכל לעבוד. היה אפשר לומר שהוא בשעת עבודה, ואינו אפשר לדור עם אשתו כיון שאין אשה בעזרה. לכאורה, אין חילוק ביניהם לענין מה שנדון בו, שאף שם אילו היה בבית במצב כעין זה, היה אותו בעיה. העיר לי אחד שאם היה בשעת עבודה ממש, לא היה חייב כיון שהיה עוסק במצוה.[fn:1] גם הק’ לי איך יאכל כשעובד. השבתי לו על שניהם שלכאורה, הענין הוא פטור כשהוא שוהה שם להיות עבודה נעשה. ותו"ת.
בלא שעת- נמצא שהיה הוה אמינא של גמרא, לכאורה, לפטור אותו שלא בשעת עבודה ומזה חוזר. לכאורה, ממה שצריך להזכיר פטור של שעת עבודה, צריך לומר שזהו מה שאומר עליו שאינו דירה כיון שאין אשתו עמו (ולשון גמרא, אז, קצת מוזר, שהיה לו לומר שעה שהיה לו להיות שוכב עם אשתו. צריך לומר שר"ל זמן שמעשיו משונים מחמת עבודה שצריך לעשות.). אם כן, דן גמרא אם אומרים שכיון שיש פטור בחצי יום טוב, יש פטור לאחר כן. יש לדון למה ייפטר:
1. אולי כיון שאינו דר שם (או אינו יכול לדור שם) לזמן, אינו דומה דירתו לבית.
  1. אפשר זלפי זה, אם היה דר בכעין זה בביתו, אף שכשאין אשתו עמו, לא נחשב דירה, כשאשתו עמו, נחשב דירה, שלאחר סוכות, ידור כן. אם כן, נמצא שהוא דירה אילו היה בבית. (ויש להעיר שאף בסוכה יכול להיות דר לזמן ארוך, שיכול לדור שם אחר סוכות. אז, צריך לומר שהוא עמידה לדור שם לזמן. גם יש לומר שבדרך כלל, דירה בסוכה לא נקרא דירה; רק בסוכות, שצריך לדור שם, מעשיו נתחשבים. ותחשב. ולא נראה, שלכאורה, זה גלגל החוזר, שהוא חשוב כיון שתורה אומר לדור בו, והיה אפשר לומר כן רק כיון שהוא חשוב. ויש לדון, שאולי אינו בעיה כיון שידע ה’ שכיון שיצווה כן יחשיב. ויש לדון, שנחשב רק מפני שאפשר לקיים בו מצווה, וזה רק קורה כשהוא חשוב. ותחשב.)
2. אולי כיון שאי אפשר ללון שם (ולא לעשות מעשה דירה, כעין אכילה, שלינה חשוב) לאותו זמן עושה שאינו דומה דירתו לבית.
3. יש לומר כ1 או 2, ולומר שאין הענין שלא יכול לדור בו לזמן, אלא שאף ליום אינו יכול, שצריך לישן אותו לילה בלי אשתו.
4. אפשר שאומרים שחיוב סוכה הוא שיהיה שם דירה לשבעה ימים. כאן, בין כך ובין כך אין דירה הוקבע שם[fn:2],  שעושה מעשה שבדרך כלל עושה דירה, אבל לא עושה אותו באופן של דירה בסוכה. (ולא מסתבר שזה די לעשות שאינו נחשב דר שם.)
5. היה אפשר לומר צד אחר, והוא שאולי סובר גמרא שהדרשה הוא דרשת סימן, דהיינו שדורשים מזה שה’ מגדיר את ציווי של סוכה להיות לשבת שם באופן נורמלי. אז, פשוט שלא חייב ה’ כהנים בשעת עבודה, שישיבתם לא יהיה נורמל. אז, צריך לומר שאז פטורים. יותר מסתבר לגמרא, אולי, לומר שפטורים מחמת כהנתם מלומר שהם פטור מחמת שאינו נורמל.
יש לדון מהו מסקנת גמרא:
1. לצד ראשון:
  1. אולי אומר שכיון שאף בבית לא היה דירתו דירה, חייב.
  2. אולי אומר שכיון שאין מה שאין דירתו דירה נגרם מסוכה, חייב.
2. הקושיא על שני צדדים אלו הוא מה שנקשה לקמן בע"ה ממה שפטור בשעת עבודה. תירוצים שלנו שם לא מתרצים, לכאורה, לזה, שיעשו שאף זה יפטור (אלא אם כן נאמר, לצד ראשון, שזה דבר שאפשר לסלק, שמה שפוטרו אינו רק שאינו שם לעולם, אלא שזה עושה שחושב עליו באופן חלוק מדירה רגילה. ודחוק.)
  1. אולי אומר שאינו כל כך חלוק, ונחשב דירה, כשדר שם רק לפעמים (ולא ידור או ילון שם בזמן אחר).
3. כן הוא אף לצד שני ושלישי.
4. לצד רביעי:
  1. אפשר שאומר שדירה שלו הוקבע שם כיון שלא היה יכול לעשות מעשה דירה שם. אז, דירתו נמשך שם מסתם (כמו מה שאומרים שאדם דר בביתו, אף אם אינו שם ממש באותו זמן), ואין מה שעושה מעשה דירה במקום אחר מוציאו. אולי זה רק מפני שמעשה דירה של מקום אחר אינו כל כך מעשה דירה, שהרי הוא בלי אשתו.
  2. אפשר שאומר שיש טוב להיות דר שם בכל זמן, ולא רק להיות דירה של שבעה ימים.
5. לצד חמישי:
  1. אולי מסיק שאינו דרשת סימן.
  2. אולי מסיק שיותר מסתבר לפטור מחמת שאינו נורמלי.
  3. אולי אומר שיש משמעות שלא רק אומר שהוא פטור אם אינו נורמל, אלא שחייב כשהוא נורמל. אז, צריך לומר שכהן בשאר ימים חייב, שאז הוא נורמל.
6. יש להעיר שדמיון להולכי דרכים לא משמע כן, שלכאורה, אין סברה זה לפטור מי שהולך בדרך בסוכות. ותחשב.
אז, כך היא הוה אמינא ומסקנא של גמרא. לכאורה, רואים ממסקנתו שמי שמצטער (או יש לו שום סיבה שאין דירתו נחשב דירה), ואף בבית היה מצטער, פטור מסוכה, שמסיק גמרא שבשעת עבודה פטור. יש לציין לגמרא סוכות וראשונים שאולי אומרים נגד זה.
גם יש להעיר שכאן אין הצער בא מן הסוכה. אם כן, גם כן, אולי לא יפטור.
יש לדחות כל זה:
1. אולי אין הכי נמי, לעולם פטור, אף אם היה מצטער בין כך ובין כך, אלא שאז חייב לסלק צערו. כאן, אי אפשר לסלק מה שפוטרו.
2. יש לומר שכיון שיהיה בביתו לזמן ארוך, אף שאין אשתו עמו, נחשב דירה. זה מחודש, שלכאורה, אין שני הקרק’ שייכים זה לזה.
3. אולי יש לומר- וצריך להגדיר- שפטור אם יש קרק’ לגרעון לחוק מדירה רגילה. נראה שאפשר שמי עמו הוא קרק’ חשוב. צערו אינו קרק’ חשוב (ואינו כל כך חלק מדירתו- ואולי הוא מפני שאינו פיזיקא"ל) עד שהוא גדול עד שאף אם היה ביתו, היה יוצא. ותחשב.
- עיין ברש"י (ד"ה קמ"ל) שכ’, “דאע"ג דלא אפשר להו כעין תדורו כי היכי דאפשר להו איחייבו.” ב"ח גורס שאומר, “… תדורו היכי דאפשר…" לכאורה, הראשון משמע שאף שלא מקיים תשבו כעין תדורו, צריך לעשות כמו שיכול. השני משמע שאף שלפעמים לא יכול לישב כעין דירה, כשאפשר לדור שם, חייב.
על ראשון, יש לבאר שמסקנת גמרא משנה כמה צריך להיות דומה לבית. (יש להעיר שעדיין אינו ממש "כי היכי דאפשר,” שאינו חייב בלילה, אף שעושה כי היכי דאפשר.)
על שני, יש להעיר שמשמע שבהוה אמינא ידע שאפשר לעשות כעין תדורו שלא בעת עבודה, וסבר לפוטרו כיון שאי אפשר לעשות כעין תדורו בשעת עבודה. משמע, לכאורה, כצד רביעי או חמישי. גם יש לומר כשאר צדדים אם נאמר שכשאומר ש"היכי דאפשר" רצה לומר שהמעשה בפני עצמו- ולא מצד מה שקורה לפני כן- אפשר לעשות כעין תדורו. ותו"ת.
ובני (תוס’)- ומטעם הולכי דרכים- יש לדון מה בא לומר. לכאורה, מקשה שיאמר גמרא שיפטור מדין הולכי דרכים. יש לדון, שגמרא אומר דבר דומה לזה, שהם מחד קרא, ולה יותר טוב לומר ממה שאומר תוס’. ואולי אז רק צריך להביא ברייתא, שיש בייתא שאומר זה בפירוש בסוכה.
ויש להעיר שלכאורה חוזר לביתו בלילה (ויש לדון). אם כן, לא מפסיד על ידי זה לינה (ובוודאי לא מפסיד כל יום מן השבעה ימים). אם כן, מוכרח שסובר תוס’ שאין נקודות אלו מעלימים את ההוה אמינא.
- עיין בגירסת שיטה מקובצת. לזה, נמצא שההוה אמינא דומה (אלא שאי אפשר לומר הצדדים שתולה אותו במה שפטור מלינה; ואפשר לומר שסובר כעין זה, אלא הפוך, והוא שדירת יום יותר חשוב. גם אי אפשר לומר שנתקיים בכל שבעת ימים, שלכאורה, עובד רק ליום אחד (או שני ימים)). ותחשב.
יש להעיר שאז נמצא שלא רק שאין הוכחה מגמרא שאין מה שלא יכול לדור עם אשתו פוטר אותו, יש הוכחה שלא פוטר, שהרי מסקנת גמרא הוא שחייב בלילה. יש לדון, שאולי רק מחייב בלילה שלפני יום שלא יעבוד בו. מה שלא אומר שיפטור מחמת שפטור אז הוא או מפני שכבר אמר זמן אחד שיפטור או מפני שאינו דירת יום, ואינו כל כך חשוב.
אם חייב, יש לדון אם הוא מפני שאינו מוזר לדור בלי אשתו לפעמים (למשל, עושה אותו כשהיא נדה), או מפני שהיה כן אף אם היה בביתו, מה שאין כן ביציאה לבית המקדש, שהיה יוצא מביתו לעשותו, ואין לו צער זה אם היה הולך.
- ועיין רע"א על שו"ע שכ’ שרש"י משמע שחייב אף בלילה, ופטור עבודה שאומר גמרא הוא ענין בפני עצמו (ואינו מה שהיה גמרא דן עליו לפני כן). לכאורה, גורס "כי היכי,” ואומר שר"ל שצריך לעשות כמה שיכול. עדיין צריך ביאור מהו הוכחה שלו, שהרי יש פעמים שיש פטור מחמת שאינו כדירה. אם נאמר ששם הוא ממש אינו כדירה כלל, קשה מהיכי תיתי שלא לומר כן כאן. אולי סבר שלא היה רש"י צריך אותו לשון לרבות שאר זמנים. לא משמע כן כל כך, שאם סבר בהוה אמינא שיפטור אף על אלו (וכן צריך לומר, שאם לא כן, מעצם גמרא יהיה ראיה נגד זה), אז צריך לומר שהיה הוה אמינא לפטור את אלו מחמת שאינם כדירה. ויש לומר על פי צד רביעי או חמישי לעיל. וצריך ביאור.
גם יש לדון למה, אז, יפטרו בשעת עבודה. אולי שם אינו דירה כלל. גם יש לומר שפטור מחמת שהוא עוסק במצווה. ותחשב. לא משמע כן כל כך מגמרא, שאם כן מהו ה"נהי…" שזה לא הוזכר כלל לסיבה לפטור (ועוד שלכאורה אינו סיבה לפטור. וזה יש לדחות לומר שיכול להיות מוכיח שצריך להיות כעין דירה.).
* Footnotes
[fn:1] יש שלדון אם נוכל לתרץ שכיון שאפשר לקיים מצווה (אם אפשר אם פטור מחמת עסק מצווה), לא יפטור מחמת זה לשבע הימים. ותחשב.
[fn:2] היה לי נקודה להוסיף על זה, והוא שלא יוכל ללון שם אף לילה אחת, או שלא יוכל להיות לו יום שלם של דירה, כיון שבכל שבעה ימים יצטרך לצאת מאשתו. ויש לדון, שאם הוא במשמר שבא ביום ראשון, יהיה מותר בימים שלאחר כן. נראה שאפשרלומר שזהו "זמן עבודה" ו"שלא בזמן עבודה,” והוא שאם כבר עבד, אינו זמן עבודה לו. ותחשב.
