* תפלות חובה
** שלש שחרית מנחה ערבית ריב"ח ריב"ל מפי אבות מפי חז"ל
חייב אדם להתפלל
תפלות בכל יום:
,
. ו
. חולקים
ו
אי תפלות נתקנו
או
כנגד קרבנות תמיד (כו:).[fn:1]
יש לכל אחד זמן מיוחד, כנגד קרבן:
1. שחרית: תחילת זמן שחרית הוא עלות החמה (?). סוף זמנו הוא חצות (לרבנן) או סוף (כז.) ארבע שעות (לר’ יהודה. וכן הלכה, שכן העיד ריב”ב בעדיות (כז.)). זמנו כנגד זמן קרבן תמיד של שחר (כו:).
זמנו המובחר הוא עם ביאת שמש (כו.), מפני שכתיב "ייראוך עם שמש" (כט:).
1. מנחה: תחילת זמנו הוא חצי שעה אחר חצות[fn:2] (?). סוף זמנה הוא שקיעה (לרבנן) ופלג המנחה (הוא פלג מנחה אחרונה (כו:), כשיוצא פלג ראשון (כז.), שהוא יא’ שעות חסר רביע (כו:)) (לר’ יהודה). להלכה, יכול אדם לעשות כרבנן או כר"י (כז.). זמנו כנגד תמיד של בין הערבים (כו:).
זמנו הנבחר הוא עם שקיעת החמה, דכתיב, “ייראוך,” אלא שאין לעשות כן מחשש שמא יאבד זמנו (כט:).
1. ערבית: תחילת זמנו הוא אחר סוף זמן מנחה (כן משמע מכז.[fn:3]). סוף זמנו הוא עלות השחר (?). זמנו כנגד הקטרת חלבים ואימורים (כו:).
** מוסף שלש
חייב אדם בשלש אלו בכל יום. ביום טוב ושבת מתפללים עוד תפלה שתקנו חז"ל כנגד קרבן מוסף, והוא המכונה בחכמתם הגדולה
(כו:). לא בכל מצב בודאי מתפללים תפלה זה. יש
שיטות מתי מתפללים:
1. חכמים אומרים שלעולם מתפללים אותו.
2. רבי יהודה לשיטת ראב"ע אומר שאי יש חבר עיר, אין מתפללים אותו אלא בחבר עיר. אם אין חבר עיר, מתפללים אותו ביחיד.
3. משנה לשיטת ראב"ע אומר שרק מתפללים אותו בחבר עיר (ל.).
** א ב
חולקים אם הלכה כ
או כ
(ל:).
** ? רבנן ר’ יהודה
תחילת זמנו הוא עלות השחר (
). סוף זמנו הוא שקיעה (ל
, אלא שאף לרבנן לא ישהה כל כך לכתחילה, שנקרא פושע (כח.)) או שבע שעות (ל
) (כו.).
** ?
ביום הכיפורים, יש עוד תפלה שהוא תפלת נעילה (
). (זמנו ???)
כל אלו הם זמנים שבו נחשב תפלתו "תפלה בזמנה.” אם לא התפלל (בשוגג או באונס (אבל במזיד נחשב "מעוות לא יוכל לתקון" (כו.))), יכול להתפלל עם התפלה שלאחריו (כו.). זה נוהג בכל התפילות (כו.). הדרך להתפלל תפלת תשלומין הוא: בתפלה הבא אחר מה שעבר (כו.), יתפלל שני תפילות של מין של אותו זמן (אלא שהבדלה, שרק צריך אמירה אחרת, נאמר רק בראשון. אם החליף, חולק ברייתות.) (כו:).
* מה מתפלל
חולקים מה מתפלל בתפלות אלו:
1. רבן גמליאל אומר שצריך להתפלל תפלת עמידה מלאה (בדרך כלל, זה תשע עשרה ברכות מלאות) (כח:). עיין לקמן, שנבאר כמה ברכות יש, ולמה אומר מנין זה.
2. רבי יהושע אומר שרק צריך לומר מעין עמידה (כח:). חולקים מהו "מעין עמידה":
  1. רב אומר שמקצר כל ברכה כשמברכו.
  2. שמואל אומר שאומר נוסח קבוע שהיה ידוע משם הביננו (זה רק בתפלות שאין בהם הוספת הבדלה או שאלת גשם) (כט.).
3. רבי עקיבא אומר שמי שאינו בקי יאמר מעין שמונה עשרה ומי שהוא בקי יאמר שמונה עשרה (כח:).
* מיני שמ”ע
** ארבע
יש
מיני שמונה עשרה:
1. בחול, מתפללים יט ברכו[fn:4]ת. יח מהם נתקנו מתחילה:
  1. ר’ הלל בדרשב"נ אומר שהוא כנגד יח אזכרות שאמר דוד ב"הבו לה’.”
  2. רב יוסף אמר שהוא כנגד יח אזכרות שבקריאת שמע.
  3. רב תנחום אמר שהוא כנגד יח חוליות.
הוסיף שמואל הקטן ברכת המינים:
  1. ר’ הלל אומר שהוא כנגד "אל הכבוד הרעים.”
  2. רב יוסף אומר שהוא כנגד "אחד.”
  3. רב תנחום אומר שהוא כנגד חוליה קטנה. (כל זה כח:).
לא אומר יותר (כתענית) מפני שמקור להוספת ברכות של תענית רק מקור ליום של רחמים, כמו אותו יום (כט.).)
1. בשבת, מתפללים שבע, כנגד שבע קולות שאמר דוד על המים (כט.).
2. מה שלא מתפללים יותר הוא מפני עונג שבת (?).
3. במוסף של ר"ה מתפללים תשע, כנגד תשע אזכרות שהתפללה חנה (שהיתה נפקדת בר”ה).
4. מה שלא מתפללים יותר הוא מפני עונג יום טוב (?).
5. בתענית, מתפללים כד, כנגד כד רננות שאמר שלמה כשהכניס את הארון לקודש הקדשים (כט.).
* תפלות אחרות
- יש פעמים אחרים שיש להתפלל:
1. יש להתפלל (כמו שעשה רנבה"ק) בכניסה לבית המדרש (“יהי רצון מלפניך ה' אלהי שלא יארע דבר תקלה על ידי ולא אכשל בדבר הלכה וישמחו בי חברי [ילעוג עלי כיון שטעיתי] ולא אומר על טמא טהור ולא על טהור טמא ולא יכשלו חברי בדבר הלכה ואשמח בהם”) וביציאה ממנו (“מודה אני לפניך ה' אלהי ששמת חלקי מיושבי בית המדרש ולא שמת חלקי מיושבי קרנות שאני משכים והם משכימים אני משכים לדברי תורה והם משכימים לדברים בטלים אני עמל והם עמלים אני עמל ומקבל שכר והם עמלים ואינם מקבלים שכר אני רץ והם רצים אני רץ לחיי העולם הבא והם רצים לבאר שחת”) (כח:)
2. יש ענין (יל"ד אם הוא חוב) להתפלל בשעת צרה (כח:). חולקים מה אומר:
  1. ר’ יהושוע במשנה אומר שיתפלל:”הושע ה' את עמך את שארית ישראל בכל פרשת העבור יהיו צרכיהם לפניך ברוך אתה ה' שומע תפלה.” (כח:).
  2. ר' אליעזר אומר שיתפלל: "עשה רצונך בשמים ממעל ותן נחת רוח ליראיך מתחת והטוב בעיניך עשה בא''י שומע תפלה.”
  3. ר' יהושע שבברייתא אומר שיתפלל: "שמע שועת עמך ישראל ועשה מהרה בקשתם בא''י שומע תפלה.”
  4. רבי אלעזר ברבי צדוק אומר שיתפלל: "שמע צעקת עמך ישראל ועשה מהרה בקשתם בא''י שומע תפלה.”
  5. אחרים אומר שיתפלל: "צרכי עמך ישראל מרובין ודעתם קצרה יהי רצון מלפניך ה' אלהינו שתתן לכל אחד ואחד כדי פרנסתו ולכל גויה וגויה די מחסורה ברוך אתה ה' שומע תפלה." כן הלכה (ל.).
3. כשאדם הולך בדרך (ליותר ממיל (בה”ג ברש”י (ל.)), יתפלל תפלת הדרך בתוך מיל הראשון שהולך (רש"י (ל.)), והוא: “יהי רצון מלפניך ה' אלהי שתוליכני לשלום ותצעידני לשלום ותסמכני לשלום ותצילני מכף כל אויב ואורב בדרך ותשלח ברכה במעשי ידי ותתנני לחן לחסד ולרחמים בעיניך ובעיני כל רואי בא''י שומע תפלה"- בלשון יחיד לסתם גמרא ובלשון רבים לאביי (כט:. ל.).
4. חולקים ר"ח ור"ש אי צריך לעמוד לזה או לא. להלכה, אינו צריך לעמוד (ל.).
* תפילת קבע
- צריך אדם להיזהר שלא יהא תפלתו "קבע.” חולקים מהא "קבע”:
1. רבי אושיעה אומר שהוא תפלה שדומה עליו למשוי.
2. רבנן אומרים שהוא תפלה שאינו נאמר בלשון תחנונים.
3. רבה ורב יוסף אומרים שהוא תפלה שבו אינו יכול לחדש דבר.
4. אביי בר אבין ורחב"א אומרים שהוא מי שאינו מתפלל עם דמדומי חמה (כט:).
* תפלה קצרה; הביננו
- יש שלש חילוקים בין תפלה קצרה להביננו:
1. בהביננו אומר שלש ברכות ראשונות מלאים; בתפלה קצרה, לא אומר שלש ברכות ראשונות.
2. יוצא אדם חובת שמונה עשרה בהביננו; לא יוצא בתפלה קצרה.
3. הביננו, להלכה, מעומד; תפלה קצרה לא צריך להיות מעומד (ל.).
* עדות ריב”ב
- על חמשה דברים העיד ר"י בן בבא:
1. ממאנין את הקטנה כדי שתיבם צרתה.
2. משיאין את האשה על פי עד אחד שאומר שמת בעלה.
3. שתרנגול שהורג נפש נסקל.
4. שיין בן ארבעים יום נתנסך על גבי המזבח
5. שתמיד של שחר קרב בארבע שעות (כשיטת ר’ יהודה) (כז.).
* תפלת שבת בע”ש
- לשיטת רבי יהודה, שיכול אדם להתפלל ערבית קודם שקיעת החמה, אף יכול אדם להתפלל תפלת שבת בערב שבת ושל מ"ש בשל שבת (כז). לא רק נעשה מותר לו להתפלל אז, אלא אף יכול לקדש ולהבדיל (כז:). אם מתפלל של שבת בע”ש, אסור במלאכה מיד[fn:5], אלא אם כן טעה (שלא נתכוון להתפלל כל כך מוקדם). בצבור, אף אם טעו, אין מטריחים אותם לחזור[fn:6] (כז:).
* מעשה של תפלת רב
- אומר גמרא מעשה: “רב איקלע לבי גניבא וצלי של שבת בערב שבת, והוה מצלי רבי ירמיה בר אבא לאחוריה דרב; וסיים רב ולא פסקיה לצלותיה דרבי ירמיה.”
** שלש
מזה, לומד גמרא
דינים בעניני תפלה:
1. יכול אדם להתפלל אדם של שבת בערב שבת אם רוצה, כשיטת רבי יהודה.
2. יכול תלמיד[fn:7] להתפלל לאחורי רבו.
3. אסור לעבור בתוך ארבע אמות של מתפלל. (כז:)
* נמס המן
- כתיב בקרא שהיה המן נמם לאחר שלש שעות. יש שני מהלכים לבאר מהו המקור לזה:
1. לפי רבנן, בקר הוא שש שעות ראשונות של יום. אומר קרא שנמס אחר בקר, אלא שמכפל אותו מילה. זה אומר לחצות את הבוקר לשנים. נמצא שנמס אחר שלש שעות.
2. לפי רבי יהודה, בקר הוא ארבע שעות ראשונות של יום. אומר קרא שנמס אחר בקר, אלא שמכפל אותו מילה. זה אומר לנכות שעה מבוקר. נמצא שנמס אחר שלש שעות .(כז.)
* הקדם תפלות
- לפעמים יהיו שני תפלות בזמן אחד. הכלל בזה הוא שיש להקדים את התדיר (כיון דכתיב, "מלבד עולת הבקר אשר לעולת התמיד תעשו את אלה" וכתיב "כאלה תעשו ליום שבעת ימים.”). יש מוציא מן הכלל, והוא תפלה שיגמור זמנו מיד[fn:8].
* טעימה קודם תפלה
- יש שני דינים בנוגע טעימה קודם תפלה:
1. ריב"ל אומר שאסור לטעום ממנחה קטנה (שבת ט:) עד שיתפלל.
2. רב הונא אומר שאסור לטעום[fn:9] עד שיתפלל מוסף. (כח:)
אין הלכה כריב”ל ואין הלכה כרב הונא.
* טעה ש"ץ
- אם טעה ש"ץ, ימתינו קהל עד שיזכור. יש שני ציורים שבהם יעלו אחר:
1. אם לא זוכר.[fn:10]
2. אם טעה בברכת המינים, שחוששים שהוא מין (כט.).[fn:11]
** רב הונא רב אסי[fn:12]
אם עולה אחר, לא יסרב (אף שבדרך כלל יש לסרב קצת (“פעם ראשונה יסרב, שניה מהבהב, שלישית יורד”), כאן אין לסרב (לד.). יתחיל מתחילת ה"ברכה" שטעה בו חבירו (כמו שהיה יחיד שטעה חוזר). אז, אם טעה בשלש ראשונות, חוזר לתחילת שמ"ע, ואם טעה בשלב אחרונות, חוזר לעבודה, שאלו כלם חד ברכה. אם טעה באמצעים, חולקים
ו
אם חוזר לתחלת ברכה רביעית (שכלם ברכה אחת) או לתחלת אותו ברכה ממש.
(לד.)
- לפעמים, אדם משתחווה[fn:13] בתוך עמידה. יש שלשה מיני בני אדם בזה:
** א. רבנן רבא
אדם רגיל- דינו הוא שמשתחווה בתחילה וסוף של אבות וסוף (
, ואף תחילה ל
) (לד:) של הודאה. לא יוסיף. (לד.)
** ב. בר קפרא ריב"ל
כהן גדול- חולקים
ו
אם משתחווה בסוף כל ברכה או בתחילת כל ברכה.[fn:14]
** ג. בר קפרא ריב"ל
מלך- חולקים
ו
אם משתחווה בתחילה וסוף של כל ברכה או שמשתחווה בתחילת שמ"ע, ואינו זוקף עד סופו. (לד)
** שלש
יש
שיטות מה עושה בהשתחוואה:
** א. רבי יהושע בן לוי
אומר שצריך שיכרע (שישתחווה) עד שיתפקקו כל חוליות שבשדרה.
** ב. עולא
אומר שכורע עד כדי שיראה איסר (מין מטבע) כנגד לבו.
** ג. רבי חנינא רבא
אומר שכיון שנענע ראשו שוב אינו צריך
מבאר שזה רק אם מצאר נפשו עד שנראה כאילו כורע. (כח:)
- כתבנו שיש להשתחוות בהודאה. זה מכוון להודאה שבשמ"ע. יש שלש הודאות:
** א.
הודאה שבשמ"ע- בארנו לעיל את דינו.
** ב.
הודאה שבהלל.
אין לכרוע בזה.
** ג. רבא
הודאה שבברכת המזון. ל
, אין לכרוע בזה.[fn:15] (לד:)
- צריך אדם לצדד את עצמו לבית קדשי הקדשים (ואם רוצה חכמה, יצדד את עצמו קצת ל-----, ואם רוצה עושר, יצדד את עצמו קצת ל----- (-----)) (ל.). אם אינו יכול , רק יכוון את לבו לשמים (ל.)[fn:16]
- יעמד אדם בתפלה אם יכול. אם זה יטעון שימסור חמורו לאחר, חולקים רבי (וכן הלכה) ורבנן אם חוששים לביטול כוונתו או לא (ל.).
- מצינו שש דברים שמהם אין עומדים להתפלל:
** א. ב. ג. ד. ה. ו.
עצבות.
עצלות.
שחוק.
שיחה.
קלות ראש.
דברים בטלים. (לא.)
** שלש
יש
דברים שמהם עומדים להתפלל:
** א. רבנן
כובד ראש. כן אמר משנה, וכן עשו
(לא.). אומר גמרא ----- מקורות לזה:
** א. חנה דוחה
לומדים ממה שאומר קרא שהיה
"מרת נפש.”
גמרא ששאני חנה שהיתה בצער.
** ב. דוחה
לומדים ממה שאמר שדוד, "אשתחוה . . . ביראתך.”
גמרא ששאני דוד שהיה מצער את עצמו בתפלה.
** ג. דוחה
לומדים ממש"כ, "השתחוו לה׳ בהדרת קדש" (אל תקרי בהדרת אלא בחרדת).
גמרא שאולי אומרים ש הדרת, ומלמד שצריך אדם לציין את עצמו לתפלה.
** ד.
לומדים ממש"כ, "וגילו ברעדה,” שאומר שבמקום גילה[fn:17] (תפילה), שם תהא רעדה (ל:).
** ב. רב אשי
הלכה פסוקה. כן עשה
.
** ג.
דבר הלכה. (ל:)
מצינו שני דברים שיש בהם גמירה מיוחדת:
** א.
כל הנביאים נגמרו בדברי שבח ותנחיומים.
** ב.
היוצא מחבירו יצא בדבר הלכה. הסיבה לזה הוא שזה גורם שזוכרו. (לא.)
- מפרשת חנה, לומדים עשר דברים:
** חמש הלכות תפלה
מהם הם ב
:
** ארבע אחרים
גם מצינו
דינים
: 							(כל טבלאות אלו הם מלא)
- חסידים היו שוהים שעה אחת קודם תפלתם (ל:)[fn:19] (דכתיב "אשרי יושבי . . .”), ומתפללים לשעה אחת, ושוהים שעה אחת (דכתיב "ישבו ישרים את פניך”). יש לדאול איך למדו וטרחו בפרנסתם, שזה עולה תשע שעות. יש לומר שכיון שהיו חסידים, בעשה בסייעתא דשמיא. (לב:)
- אין להפסיק תפלה אלא לדבר שיש בו סכנת נפשות, כמו מלך רומי או עקרב. (לב:).
- יש, בעיקר שלש הזכרות שרגילים להוסיף לתפלה:
** א.
מזכירים גבורת גשמים- עושים כן בברכת תחיית המתים, מפני ששקולה כתחיית המתים. אם טעה, צריך לחזור.
** ב.
שואלים גשמים- עושים כן בברכת השנים, כיון שיש בשניהם ענין של פרנסה. אם טעה, אומרו בשמע קולנו. אם טעה אף בזה, חוזר לראשון.
** ג. שלש
מבדילים- יש
שיטות בזה:
** א. ר"ע
אומר שאומרו לברכה רביעית בפני עצמו.
** ב. ר"א
אומר שאומרו בהודאה.
** ג. חכמים שני
אומרים שאומרה בברכת הדעת. יש
טעמים לזה:
** א.
יש בשניהם ענין חכמה.
** ב.
כיון שהבדלה הוא חול,עשהו בתחלת ברכת חול.
(יש לתמוה איך יהיה מחלקת בזה; נראה מה תקנו אנשי כנב"ג. יש לומר שבתחלה, תקנוהו בתפלה. כשעשירו, תקנוהו רק על כוס, ושכחו מה נתקן בתפלה. חזרו והענו, והתקינו[fn:20] בתפלה, ואז חלקו איך להתפלל.)
אם טעה, אומרו על הכוס. אם טעה בזה ובזה, אומרו בתפלה. (לג.)
יש עוד הזכרה, והוא לא רגיל, והוא הנקרא "מעין המאורע.” דורשים מ"---” שצריך לומר בכל יום קדוש מעין המאורע (-----). אומרו בעבודה. אם שכח, חוזר. אם צבור שכחו, כיון שהזכירוהו פעם אחת ביום, אין צריכים לחזור. יש רק דין אחד היוצא מן הכלל, והא שאם שכח של ר"ח בערבית, אינו חוזר. חולקים מהו הסיבה לדין זה:
** א. אמימר
אמר שדין זה אומר שאם שכח בלילה ראשונה, כיון שיש לילה שניה, וכיון שאין מקדשים חדש בלילה, אינו צריך לחזור.
** ב. ר"א
אומר שדין זה אומר שכיון שאין מקדשים חדש בלילה, אין צריך לחזור אם שכח בליל ר"ח. (ל:)
** ארבע
בכל אלו, הדין שאם שכח חוזר תלוי במתי הבין ששכח. אם עדיין בשמונה עשרה הוא, חוזר לאותו ברכה. אם כבר סיים שמונה עשרה, חוזר לתחילתו. הגדרת "סיים שמונה עשרה" ששנוי במחלקת לשונות. נמצא למסקנא
ציורים:
** א. לא עקר רגליו רגיל לומר
אם סיים שמ"ע ו
, אם
שם תחנונים, לא נחשב שסיים.
** ב. לא רגיל לומר
אם . . ., אם
תחנונים, חולקים לשון שני ולשון ראשון אם נחשב שסיים או לא.
** ג. עקר רגליו רגיל לומר
אם
, אם
תחנונים, חולקים לשון שני ולשון ראשון אם נחשב שסיים או לא.
** ד. לא רגיל לומר
אם . . ., אם
תחנונים, נחשב שסיים. (כט:)
אם טעה מתפלל[fn:21], סימן רע הוא (שלא יענו תפלתו) לו או לשולחיו, דכתיב, “בורא ניב שפתים.” (לד:)
- מזכיר גמרא חמש דברים הרעים לומר בתפלה:
** ארבע
בתפלה:
** שלש
על
משתקים אותו:
** א.
לא יאמר "על קן צפור יגעיו רחמיך.” חולקים מהו הסיבה לזה:
** א. ריב"א ריב"ז
/
אומר שהוא שמשמע שגזירות ה’ אינם גזירת מלך אלא רחמנות.
** ב.
האחר אומר שהוא שמטיל קנאה במעשה בראשית, שמשמע שרק על צפור מרחם.
** ב.
לא יאמר "מודים" שני פעמים. הסיבה לזה הוא שנראה כמדבר לשני רשויות.
** ג.
לא יאמר "על טוב יזכר שמך.” הסיבה לזה הוא שיש לברך את ה’ אף על הרע. לג:)
** אחד
הוא רק רע:
** א.
לא יאמר יותר שבחות מ------
** אחד
בקריאת שמע:
** א.
לא יכפול פסוק[fn:22] של ק"ש, שנראה כאומרו לשני רשויות. על זה משתקים אותו. (לג:)
- אסור לברך ברכה שאינה צריכה, שעובר משום "לא תשא.” (לג.)
- אסור לעבור לפני מתפלל (כז.). גם אסור לישב בתוך ארבע אמות של מתפלל, שאומר, “אני האשה הנצבת עמכה.” (לא:).
- אם סוטה נמצאת טהורה, יש לה "שכר" לענין בנים. חולקים מהו:
** א. רבי ישמעאל
אומר שאם היה עקרה, יולדת בן.
** ב. רבי עקיבא
אומר שבנים שיולדת יהיו יותר טובים. לא מפרש כר"י, שאם כר"י, יהיו כל העקרות נעשות סוטה.
* העברת נשיא
- מעשה ברשב"י (כח.) כשהיה תלמיד ששאל את ר' יהושע אם ערבית רשות. אמר לו שרשות היא. שאל את רבן גמליאל וא''ל שחובה היא. הזכיר ר"ש מה שאמר לו ר"י. כשנכנסו לבית מדרש, עמד השואל ושאל תפלת ערבית רשות או חובה א''ל רבן גמליאל חובה ושאל אי יש אדם שחולק. אמר לו ר' יהושע שלא היה חולק. אמר לו ששמע שהוא היה חולק.בזה את ר"י. כיון שזה היה הפעם השלישי שביזה ר"ג את ר"י
** א. ב.
(
בקביעות ר''ה צעריה.
במעשה בבכור של ר' צדוק צעריה. 	ג. כאן צעריה.)
עברו את ר"ג מהיות נשיא. חקרו מי לשים לנשיא. היו להם שלש צדדים:
1. רבי יהושע- דחהו כיון שהיה בעל המעשה (והיה ר"ג מצטער).
2. ר' עקיבא- דחהו כיון שלא היה לו זכות אבות (שהיה גר) להצילו מעונש שיענשו ר"ג.
3. ר' אלעזר בן עזריה- לא היה בו בעיא, שהיה חכם (ואי מקשי ליה מפרק ליה) והיה עשיר (ואי יש צורך לפלוחי לבי קיסר אף הוא אזל ופלח), והיה עשירי לעזרא (ויש לו זכות אבות).
נעשה לו שמנה עשר שורות (אף שהיה רק בן שמנה עשר)[fn:23] זקנה, ואז הסכים להיות נשיא.
אותו היום, סלקו את שומר הפתח (לפני כן, היה ר''ג מכריז ואומר כל תלמיד שאין תוכו כברו לא יכנס לבית המדרש), ונתוספו ארבע מאה או שבע מאה ספסלים. באותו היום, נשנו עדיות (וכל היכא דאמרינן בו ביום ההוא יומא הוה),ולא היתה הלכה שהיתה תלויה בבית המדרש שלא פירשוה. לבסף פייס ר"ג את ר"י. רצו להחזיר את ר"ג להיות נשיא, אבל לא יכלו לסלק ראב"ע, כיון שאין מורידין בקדשה. לכן עשו שר"ג דרש שני שבתות, וראב"ע דרש אחד. (כז:, כח.)
* מי שהוא בדרך בשעת ק"ש
- אם אדם צריך להיות בדרך בזמן ק"ש, חולקים שני ברייתות אם יתפלל קודם (כדי שיעמוד) ושוב לאחר זמן ק"ש, יקרא ק"ש (בדרך), או שטוב יותר לאחר תפלה לק"ש (כדי לסמוך גאולה לתפלה), אף שאז לא יוכל לעמוד לתפלה. (ל.)
* מקום תפלה
מונה גמרא שלשה דינים בענין מקום לתפלה:
** א.
יתפלל אדם במקום שלומד (ל:).
** ב. קוב להתפלל בבית שיש בו חלונות, דכ’, ""ומין פתיחן ליה בעליתיה." ג. אין להתפלל בבקעא, שנחשב חוצפא. (לד:)
* כבוד רבו
גמרא מונה ----- דברים שחייב תלמיד לעשות לכבוד רבו. (דברים אלו הם רק בתלמיד אל רבו, ולא תלמיד חבר אל רבו.) אלו הם:
1. לא יתפלל כנגד רבו.
2. לא יתפלל אחורי רבו.
3. לא יתן שלום לרבו. רש"י מוסיף שחייב אדם לומר שלום לרבו, אבל זה אומר שלא לתת שלום בלי להזכיר "שלום רבי.”
4. לא ישיב שלום לרבו. מש"כ בשם רש"י לעיל נכון אף כאן.
5. חולק על ישיבתו של רבו. איני יודע כל כך מה זה.
6. האומר דבר שלא שמע מפי רבו.[fn:24]
על חמש אחרונות, אומר ר"א בברייתא שהעושה כן גורם לרבו שיסתלק.[fn:25] (כז:)
* Footnotes
[fn:1] יש, אולי, הבדל בין שאר תפילות לתפלת ערבית. שאר תפלות הם חובות; חולקים רבא ואביי (וכן חלקו תנאים) אי תפלת ערבית רשות או לא (כז:).
[fn:2] עיקר זמנו הוא אחר חצות, אבל לא קשה לדייק מתי הוא חצות. לכן, זמנו הוא אחר חצי שעה אחר חצות.
[fn:3] הראיה הוא ממה שתולה בו זמן תפלת ערבית של שבת וערב שבת.
[fn:4] ברכות ראשונות הם סידור שבת, אמצעים הוא בקשות, וסופו הוא הודאה. (לד.)
[fn:5] יש לדון מהו הדין אם מתפלל של מ"ש בשבת, אם מותר במלאכות.
[fn:6] גמרא אומר דין זה גבי תפלת מ"ש בע"ש. יש לדון איזה דינים בזה הם אף בזה.
[fn:7] אם הוא תלמיד חבר (כז:), אבל אם הוא תלמיד, עיין לקמן.
[fn:8] בציור של גמרא, יגמור בתוך חצי שעה.
[fn:9] לא מבאר ממתי. ויש לדון.
[fn:10] כן נראה מסברה. ודע שאם ירצה, יכול לשהות כמה שעות לזכור (כט.).
[fn:11] יש שני יוצאים מכלל זה:א. אם כבר התחיל אותו ברכה, שאז לא חוששים שהוא מין.ב. אם היה לעולם צדיק. כן אומר אביי, אבל רבא חולק. תלוי הוא במחלוקתם אי יוחנן כה"ג (שנעשה צדוקי) היה לפני כן רשע (ינאי) או לא. (כט.)
[fn:12] יש להעיר שיש גירסא בגמרא (רש"י) שאיתותב ר"א.
[fn:13] יש להעיר שכוונתנו בזה הוא למה שנקרא "בא"וו,” ולא למה שבדר"כ נקרא בלשון תורה "השתחוואה,” שזה פישוט ידים ורגלים (שנאמר, "להשתחות לך ארצה.”). יש להוסיף שמצינו שלש מיני השתחוואה:א. השתחוואה- הוא מה שבארנו לעיל.ב. קידה- הוא על אפים(שנאמר, "ותקד בת שבע אפים ארץ").ג. כריעה- הוא על ברכים (שנאמר, "מכרוע על ברכיו"). (לד:)
[fn:14] יש גורסים שלריב"ל משתחווה בתחילה ובסוף.
[fn:15] עיין שם, שסתם גמרא לא מניח כמותו. יש לדון אם חולק בדין או שרק סובר שלשון "הודאה" לא נאמר עליו או שסבר שהוא פשוט.
[fn:16] יש להעיר שבכח: אומר שיכוון את לבו לבית קדשי הקדשים. יש לדון אם הם חלוקים.
[fn:17] קרא זה, עם "בכל עצב יהיה מותר” ו"אז ימלאו שחוק פינו,” גם כן מלמד שצריך להיות אדם לעולם ברעדה (אלא אם כן לובש תפילין,) (ל:).
[fn:18] יש להעיר שיש, לכאורה, מחלקת בזה לעיל בפרק שלשי.
[fn:19] ואולי כל אדם צריך לעשות כן (לב:)
[fn:20] חולקים ר’ יוחנן ורב אחא אם אומר שניהם או רק אחד שרוצה (לג.).
[fn:21] יש שני לשונות בגמרא בזה שחולקים אם זה רק בברכה ראשונה או בכל הברכות (לד:).
[fn:22] אם רק כופל מילים, הוא רק מגונה, ולא משתקים אותו (לג:).
[fn:23] זה הפשט במה שאמר, “הריני כבן שבעים שנה.” (כח.)
[fn:24] רבי אליעזר אמר זה, אבל נראה שחולקים עליו, שמזכיר גמרא סוכה את זה לדבר שרק ר"א עשה.
[fn:25] עיין שם; ונראה לי שזה קאי על כל אחד שבברייתא. יש לדון, שאולי קאי על כולם (הוא רק אם עושה כולם), ואולי קאי רק על האחרון.
