** משנה
אומר זמני תפלה של ארבע תפלות. על שלש מהם מביא חולק המקדים את הזמן.
על דין ראישון שבמשנה, מק’ ומת’, ומק’ על הת’ ומת’.
כדי לתרץ לק’ שניה, הביא דין תפלת תשלומין. שואל בו. מביא דמיון ודוחהו. פושטו. מק’ ומת’.מביא סמך לת’. מז’ עוד שני דינים באותו ענין. על השני, מק’.
שואל גמ’ מי תקן תפלות. מביא שני תשובות ובריי’ לכל חד. (באמצע, דן בשיטת ר”י במנחה.) מק’ חד מהבריי’ על החול’ ומת’.
שואל גמ’ בשיטת ר”י. מביא ראיה לשני הצדדים ודוחה ראיה ראישונה. מביא עוד ראיה לצד שני.
פוסק כר”י בתפלת השחר. מפ’ למה פסק כן.
מביא קרא במן ובריי’ המפ’. מק’, ומוק’ לר”י ולרבנן. מבאר בריי’ המפ’.
שואל גמ’ אי הל’ כר”י בתפלת מנחה.מביא ראיה לשני הצדדים, ומסיק ששניהם נכונים.
מביא מעשה ולומד ממנו שלש דינים. על השני, מק’ ממימרא ומבריי’ ומת’. מביא ראיה לת’.
הוז’, אגב, דין תפלת שבת בע”ש.שואל ומשיב. מק’ על התשובה ומת’. מק’ על אותו תשובה ומשיב.
מז’ דין תפלת שבת בע”ש ושל מוצאי שבת בשבת. על שניהם שואל שאלה הדומה ומשיב.
מז’ מעשה בתפלה קודם זמנו. חול’ מה קרה.
מק’ על לשון המשנה ומת’ שמחדש דין. חול’ תנאים באותו דין. מביא מעשה דהעברת ר”ג (שהיה שייך לאותו דין). (מז’ העברתו, בחירת אחר, מה קרה בב”מ אז, והחזרתו ואחריתו.
אומר ר’ יוחנן מימרא על דין (מוסף) שבמשנה.
חול’ תנאים אי מוסף או מנחה קדם. פוסק. דן מי פוסק.
מביא קרא רע שנאמר על מאחר מוסף. מביא שני מקורות שהוא רע.
מז’ הנהגת אחד. שאל לו אחר ארבע שאלות. השיב על כלם חוץ מן האחרון.
מז’ גמ’ שני איסורי טעימה ופוסק נגדם.
** משנה
מז’ שני תפלות של ר”נ בן הקנה.
גמ’ אומר כל לשון שניהם.
מביא גמ’ שני מעשים בחלת שני אמוריאם.
** משנה
אומר שלש מימרות בתפלות קבועות (מח’ תנאים (שלש שיטות) מה אומר; עצה לתפלה; דין מי שא”א לצדד). אומר דין בתפלות שאינן קבועות (מהלך במקןם סכנה).
שואל גמ’. מש’ שלש תש’. שואל שאלה אחרת. מש’ שלש תש’ (ובאר שלשי). שואל שאלה השייכת לשאלה ראישונה. משיב  תש’ לשיטתם.
לשאלה שלישי, הוז’ ברכת למלשינים. מז’ מי תקנו. מז’ מעשה שקרה לו בו. מק’. מת’, מק’ על הת’, ומת’. מק’ על ת’ שכבר הק’ עליו. מת’ לשיטת התרצן. מת’ לק’ על המעשה לחול’.מביא מימרא לסמך דין של אותו ת’.
שואל שלש שאלות כעין שאלה ראישונה. משיב. מק’ על שלישי ומת’.
חול’ אמוראים בדין ראישון במשנה בתפלה קבועה.
מז’ מימרת פסק על אותו מח’ תנאים.
הוז’, אגב, דין הביננו. אומר חד זמן שא”א לאמרו. מק’ ומביא סמך לק’. מת’ ודוחה הסמך. מק’. מז’ עוד זמן שא”א לאמרו. מק’ מ’ שניה שנראישון ומת’ (מבאר למה א”א לת’ כן בראישון.). מק’ ומביא סמך לק’. מת’ ודוחה סמך.
הוז’, אגב, מימרא בדין טועה. הוז’ שלש דינים. מק’ על השני ומת’. מק’ מלשון מימרא. מת’ ת’ אחר לק’ ראישונה.
אומר מימרא עם שני דינים. מגדיר דין שני ומז’ מקור. אומר מימרא להגדיר עוד אותו דין. יש אומ’ שאותו מימרא מגדר הגדר.
חול’ ארבע אמוראים בביאור דין שני שבמשנה. על שלישי, אומר מימרא. לרביעי מביא מימרא  וקרא.
הוז’ דין דמדומי חמה בשני מקומות. לייט על שני. מבאר למה.
על דין תפלה שאינו קבוע, אומר שני לשונות של מימרו לפרש.
מביא ארבע חול’ על אותו דין שבמשנה. פוסק כרביעי.
מז’ שלש מימרות מאליהו (שלישי שייך לגמ’ שלנו, שדומה לדין משנה). מפרש שלישי, שהוא תפלת הדרך. אומר לשונו. חול’ אמוראי אי נאמר בלשון יחיד או רבים. שואל, ומשיב. מביא מח’ אמוראים, ומעשה. (לאח”כ, פוסק.)
אומר שלש חי’ בין תפ”ק להביננו.
על דין שלישי במשנה בדין תפלת חוב, מביא מח’ תנאי’ בציור הדומה. פוסק.
בריי’ אומר שני מימרות ששייכין למשנה. מז’ קרא השייך.
חול’ תנאים. מבאר סיבת מח’. כבר הובא אמורא שנהג כחד.
מז’ מעשה. מז’ עוד מעשה. מק’ על שני ומת’. מק’ עוד ומת’.
** משנה
מביא שלש תנאים החול’ מתי אומ’ מוסף.מבאר מהו מח’. פוסק. מביא מעשה כזה. יש חול’ על הפסק. מז’ מעשה להוכיח פסק. מק’ על ההוכחה ומת’.
אומר מימרא.
מז’ שוב הפסק.
אומר מעשה. אומר דרך לבארו. דוחה מבריי’. אומר עוד דרך ומק’ מבריי’. מת’ ומפרש מריי’.
הוז’ ציור  שצריך לחזור על תפלתו. שואל. משיב בשני לשונות תשובה אחת. מביא קרא לשני הלש’.
אומר מימרא וטעמו. מגדיר מימרא. דוחה ההגדרה מן הטעם.
** משנה
אומר אומר ארבע דינים בתפלה. שנים הם לפני תפלה (ושני רק ממדת חסידות) ושנים הם בתוך תפלה.
שואל למקור. אומר ארבע תש’. דוחה שלש ראשונות. מפ’ רביעי.
אומר מעשה השייך לדין אחר מאותו קרא. אומר מעשה שמביא מקור אחר לאותו דין. אותר שלש מעשים השייכים לאותו דין. אומר עוד מקור ומביא עוד מעשה.
אומר בריי’ שחולק על משנה. מבארו בשלש משלים. מביא עוד שיטה. אמר שיש נוהגים כמשנה ויש כבריי’.
דינו שייך אף ללוויה, אוז השכיר שלש מעשים בזה.
אומר דין בתפלה. אומר מעשה ששייך לדין זה ודין אחר.
אומר עצה לתפלה.
אומר מקור למתי ואיך יתפלל.
לומד חמש דיני תפלה מחנה, לומד ארבע דינים אחרים ממנה, אומר חד אגדתא דתפלה עליה, ודורש שש פסוקים בה. בחד, מק’ לשיטה שמביא מבריי’ ומת’. חד הוא מח’ שלש אמוראי. בתוך כך, נאמר ביאור על מעשה אחר של חנה.
הובאו כמה מימרות בעניני חנה מר”א. אז, מביא עוד שני מימרות מר”א. [fn:1]
מביא קראי שאומרים שאין לנו כל כך בחירה.
מביא קראי ודורש בתפלת משה להציל לבני ישראל.
אומר סדר תפלה.
אומר שלש מימרות מר”א של דמיון.
אומר שני מימרות מר”א ברע שקרה לאחר חורבן בית המק’.
אומר עצה לתפלה. מק’ ממימרא ומת’.
אומר מימרא על ארבע דברים שדומים.
דורש קרא שעוסק בדיבור בין ציון לה’.
מביא מקור לדין של מדת חסידות. מביא בריי’ שאומר כן.
מוסיף שני דינים על אותו דין משנה. מק’ ומת’.
אומר מיעוט על דין של סוג שני שאמר משנה. מק’ ומת’. אומר מעשה.
אומר אותו מיעוט על דין שעמו במשנה. מק’ ומת’.
אומר חוקי סכנה. אומר מעשה.
** משנה
אומר שלש דינים בהזכרות תפלה. על שלישי יש מח’ שלש תנאים.
שואל טעם כל דין ומשיב. על שלישי משיב שני תשובות.
הוזכר דעה. אז, אומר גמרא שלש אגדות בו.
אומר אגדה הנדרש באופן הדומה לשני שלעיל. מקשה ומתרץ ומביא סמך.
מקשה גמרא על דין שלישי ומשיב. מביא ברייתא שהוא סמך לאותו יישוב. מביא עוד מימרא שאומר כדין אותו יישוב. מקשה מברייתא ומשיב על ידי שינוי ברייתא. מביא עוד מימרא האומר אותו דין. שואל דין דומה. לומדו מאותו דין. מביא מימרא ומוכיח שחולק על אותו דין.
שואל ומשיב.
פוסק כאותו דין (שדנו בו לעיל).
על מחלקת שבמשנה מביא מעשה שפוסק כחד תנא בציור מיוחד. מקשה. מקשה על קושיא שני קושיות ומשיב. חולקים ארבע אמוראים באיזה לשון נאמר הדין. אמר אמורא לסמוך על חד, שנאמן הוא. מדמהו לאחר ומוכיח נאמנות אחר.אומר עוד שיטה.
** משנה
אומר שלש דברים שאומרם נשתק.
מבאר שני דינים אחרונים. שואל על דין ראשון ומשיב שני תשובות. אומר מעשה עם מי שאמר אחד מאלו.
אגב אותו מעשה מזכיר מעשה עם אחר שאמר דבר שלא היה לו לומר. אומר משל לזה.
אומר מימרת אגדתא מאותו אמורא (ר’ חנינא) ודורשו מקרא. מקשה על אותו קרא ומשיב. אומר משל.
על דין שלישי שבמשנה אומר דין הדומה. מקשה מברייתא ומתרץ. מקשה ומתרץ.
** משנה
אומר משנה שני דינים בחד ענין ושני דינים בענין אחר. מוסיף פרט באחד מאותם דינים.
אומר גמרא דין שיש לדייק מן המשנה ומבארו. אומר מימרת אגדה על דברים הדומים לזה.
אומר אמורא שלש דינים. חולק אמורא על שני. מקשה גמרא ממשנתינו (לשניהם. דוחה השני ומשיב) לו (רק לראישון).[fn:2]
אומר דין על חילוק מיני ברכות (מפני שדין הקודם היה דן בחילוק ברכות).
אומר שני מעשים בבני אדם שהתפללו בדרך מוזר ולמב אינו רע.
לומד גמרא דין מקרא שהובא בביאור למה לא עשה רע.
אומר ברייתא דין ופרט בו. מוסיף אמורא שני דינים בשם אמורא. חולק אמורא לומר שאותו אמורא שהביא ראשון אמר דבר חלוק בשני הדינים.
ברייתא מפרש שלש מיני השתחוואה ומביא מקור לפרש כל אחד ממנו. אומר הנהגת שני אמוראים בזה.
אומר ברייתא. מקשה מברייתא אחר. מתרץ. מביא מעשה של אמורא אחד שלא נהג כאותו יישוב, ומפרש איך יישב הברייתא. מקשה עליו מברייתא ומתרץ.
** משנה
אומר מימרא הנוגע לדין של משנה שלפניו. מוסיף פרט בו. אומר מעשה של אותו מימרא.
אומר אמורא מימרא לפרש משנה. אומר גמרא שיש גורסים אותו מימרא על משנה אחר.
אומר מקור לדברי משנתינו.
אומר גמרא שלש מאמרות מרחב”א בשם ר”י לענין למי נאמרו נביאות. על השני חולק אמורא. מבאר גמרא איך מבאר קראי. על שלישי חולק אמורא שמביא ראיה מקרא. דוחה גמרא אותו ראיה.
דורש גמרא קרא שהביא לעיל. חולקים מה לדרוש.
אומר מעשה על רחב”ד על מימרת המשנה. אומר עוד מעשה עליו.
אומר אמורא מקום להתפלל ומביא קרא ומקום שבו מחוצף להתפלל. אומר עוד דבר שהוא מעשה מחוצף.
** משנה
אומר שלש דינים. על שנים הראשונים אומר אחד יוצא מן הכלל (אחד לכל דין), ועל השלישי חולק תנא.
שואל גמ’ למקור משנה. מת’ ומק’. מת’ לחד מד"ולחד מד"א בחד מד"א. מק’ לכל שאין זה מקור לכל הדין ומת’ לאותו ק’ שני. מק’ שאין זה מקור לכל. מת’ ומק’ ומת’ ומק’. אומר מימרא צדדי, ומק’ עליו ומת’. מת’. (מק’ ק’ שני שהק’ לעיל, ומת’ כמו שת’ לעיל). מק’ שני קושיות. חוזר מכל תשובה זה ואומר אחר.
אומר שני אגדות על חיוב ברכות. אומר כאחד מהם מחמת סתירת קראי. אומר עוד שני אגדות.
מק’ גמ’ סתירת קראי ומת’.
חולקים תנאים ביישוב עוד סתירה. אומר גמ’ מה קרה בהנהגה כשניהם. מז’ אמורה שאמר לתל’ כאחד מן התנאים.
* Footnotes
[fn:1] אינו כל כך פשוט מהו המשך כל גמ’ כאן. ע’ בשי”ח ש”י (גלגל חמישי-כאן).
[fn:2] יש שני גירסאות בגמרא זה. מה שכתבנו ב( ) הוא גירסת רש”י; מה שאינו ב( ) הוא גירסת גמרא שלנו.
