** הדין:
הכללים:
נלמד בהיקש:
מלמד בהיקש:
לא מלמד:
1. צריך להקיש אשם לחטאת ועולה ללמד שנשחט בצפון, ולא מספיק להקיש לחטאת, כיון שנלמד מהיקש לעולה.
2. צריך לכ', "כאשר יורם" בפר כהן משיח כדי שיוכל ללמד דין יותרת הכבד ושתי הכליות מפר העלם דבר  לשעיר עבודה זרה, כיון שבפרק העלם דבר נלמד מהיקש.
מלמד בג"ש:
לא מלמד:
1. צריך היקש ללמד שחיטת צפון באשם, ולא מספיק ג"ש מופנה של "קדשי קדשים" לחטאת.
מלמד בקו"ח:
מחלקת:
1. תנא דבי רבי ישמעאל – דורשים.
2. רבי – לא דורשים.[fn:1]
מלמד בבנין אב:
ספק.[fn:2]
נלמד בג"ש:
מלמד בהיקש:
מחלקת:
1. רב פפא – דורשים.
2. רזבדר"מ – ספק.[fn:3]
מלמד בג"ש:
דורשים.
מלמד בקו"ח:
דורשים[fn:4]:
1. נלמד בקל וחומר מהיקש, שאף שאינו מלמד בהיקש, מלמד בקל וחומר. כש"כ ג"ש, שמלמד בהיקש, מלמד בקו"ח. מקור זה רק אפשר לפי רב פפא, ולא לפי רזבדר"מ.
2. נלמד בקל וחומר מהיקש, שאף שאינו מלמד בעצמו (שאינו מלמד בהיקש), מלמד בקל וחומר. כש"כ ג"ש, שמלמד בעצמו, מלמד בקו"ח.
מלמד בבנין אב:
ספק.
נלמד בקו"ח:
מלמד בהיקש:
מחלקת:
1. רב פפא – דורשים. נלמד מקו"ח מג"ש, שאף שלא נלמד בהיקש, מלמד בהיקש. כל שכן קו"ח, שנלמד בהיקש[fn:5], מלמד בהיקש.
2. רזבדר"מ – ספק.[fn:6]
מלמד בג"ש:
דורשים:
1. לומדים בקו"ח מג"ש, שמלמד בג"ש, אף שאינו נלמד מהיקש. כל שכן קו"ח, שנלמד מהיקש, שמלמד בג"ש.
מלמד בקו"ח:
דורשים:
1. לומדים בקו"ח מהיקש[fn:7], שמלמד בקו"ח, אף שלא נלמד בהיקש. כל שכן קו"ח, שנלמד מהיקש, שמלמד בקו"ח.
מלמד בבנין אב:
ספק.
נלמד בבנין אב:
מלמד בהיקש:
ספק.
מלמד בג"ש:
ספק.
מלמד בקו"ח:
ספק.
מלמד בבנין אב:
ספק.
מתי כל זה נוגע:
1. זה רק נוגע בקדשים. חולקים רב פפא ורזבדר"מ אם זה נוהג כשמלמד ראשון הוא חולין. אבל, אם למד ראשון (שהוא מלמד שני) או למד שני הוא חולין, דורשים.
2. חולקים אם דורשים "הימנו ודבר אחר," שהוא כשחלק מן ההלכה נלמד בהיקש מהיקש, וחלק מן ההלכה נלמד באופן אחר. אף אם לא דורשים כל "הימנו ודבר אחר," יש דורשים "בחדא זמנא," שהוא כשחלק מהלכה נל' מהיקש דבר הכתוב בפי', וחלק אחר נלמד מאותו היקש דבר הנלמד מהיקש.
* Footnotes
[fn:1] לא מביא מקור לזה. בכ"מ בסוגיה זו, גמ' לא מביא מקור, אלא מביא ציור שבו מצאנו שדורשים או שלא דורשים. קצ"ב איך יודעים כל זה בלי מקור. נראה שהוא חלק מהל"מ, כמו שכל ענין הדרשות הם הל"מ. (אז, ק"ק למה לפעמים יש מקור, כמו גבי היקש מהיקש. אפשר שאף שהוא הל"מ, טרח וכ' אותו קרא.)
[fn:2] אבל, מסתבר שלרבי לא יכולים ללמוד, שלא יהיה כוח בנין אב חזק מקל וחומר, שקל וחומר הוא בנין אב עם הוכחה יתירה.
[fn:3] מגמ' יוצא שזה תלוי במחלקת שיחלקו ב"מתי כל זה נוגע."
[fn:4] הגמ' משמע שכוע"מ שדורשים. אבל, יש להעיר שאף מקור שני שלו רק מהני לפי תדר"י, ולא לפי רבי. אז, לפי רבי אין מקור שנדרוש, ולכאו' יישאר בספק.
[fn:5] כמו שהערנו לעיל, לכאו' זה יכול להיות מקור רק לפי תדר"י, ולא לפי רבי.
[fn:6] הולך לשיטתו לעיל, שסובר שאין מקור שג"ש מלמד בהיקש.
[fn:7] כן אומר גמ'. היה אפשר לנקוט לימוד מג"ש ג"כ, כמו שעשה לעיל.
