משנה א
א.
לא פשוט מהו הכוונה של מקום מעשה. לכאו’, פשוט שיש מקום לחפץ, אבל לא קל להבין איך יהיה מקום למעשה. כנראה, כאן סובר שהוא מקום של החפץ של המעשה – של החפץ שעליו נעשה המעשה.
אף זה, אולי, לא מדוייק, שיש לדון על איזה חפץ נעשה המעשה. יש בזה שתי שאלות, כמו שנבאר.
הראשונה היא ביאור "חפץ שעליו נעשה מעשה." נראה שהכוונה היא, לכאו’, דבר שנשתנה ביותר מחמת המעשה. (יש לדון אם צריך להיות ששינוי הכי גדול קרה לו – ואז קשה למצוא שני חפצי מעשה – או רק צריך ששינוי חשוב קרה לו (ואולי מה שהוא השינוי הכי גדול מספיק לעשות שהוא שינוי חשוב). אפשר שכוונתו מאד חשוב לזה, שכיון שמכוון לעשות תוצאה על חפץ, אותו תוצאה יותר חשובה, ועל אותו החפץ נעשה המעשה. (זה לא צריך להיות מחמת חשיבות התוצאה, אף שבארנו אותו כן, ויכול להיות מחמת חשיבות החפץ, או מחמת יחס החפץ למעשה, במחשבתו.))
השנית היא ביאור החפץ. יש לדון אם בזה מדובר על כל החפץ או רק על חלק ממנו. למשל, כאן, יש לדון אם כל הבהמה יצטרך להיות בצפון, או רק הצוואר (ואולי אף לא כל הצוואר, אלא רק מקום השחיטה ממש).
ב.
חולקים תנאים בהכשר המזבח לשחיטת קדשי קדשים:
1. רבי יוסי סובר שיכול לשחוט קדשי קדשים בכל המזבח. לומד את זה ממש"כ, “זבחת עליו את עולותיך ואת שלמיך,” שאומר שיכול לשחוט על המזבח שלמים, שהם קדשים קלים, ועולות, שהם קדשי קדשים.[fn:1] [ב]
2. רבי יוסי ברבי יהודה סובר שיכול לשחוט קדשי קדשים בחצי מזבח הצפוני. לומד את זה ממש"כ, “וזבחת  עליו את עולותיך ואת שלמיך,” שאומר שיכול לשחוט על חצי המזבח שלמים [ג], שהם קדשים קלים, ועל חצי המזבח עולות, שהם קדשי קדשים.[fn:2][fn:3] [ג] [ד]
לפי רבי יוסי, נמצא שמוסיף כל מקום המזבח על צפון, ולרבי יוסי בר"י, נמצא שמוסיף חצי מקום מזבח על צפון. אבל, רבי יוחנן אומר שרבי יוסי סובר שכל המזבח עומד בצפון. אז, נמצא שלפי רבי יוסי, אין מקום שמוסיף על המזבח.[fn:4] אבל, רבי יוסי בר"י אומר שהמזבח היה נוטה לדרום. אז, לפי רבי יוסי בר"י, מוסיף מקום כשרות. אבל, אולי אפשר שיש תנא שסובר כשיטת רבי יוסי כאן, ולא סובר שכל המזבח עומד בצפון, ואז יוסיף כל מקום המזבח על צפון.
ו.
נראה שהקבלה צריכה להיות ביד, ולא רק שיכולה להיות ביד. כן נראה, שהרי דורש אותו מפסוק, ומסתבר שהפסוק אומר מה שצריך לעשות. אבל, לא מוכרח כן, שיש לומר שכיון שהיא קבלה, כבר ידוע שכשרה בכלי, והפסוק רק בא להוסיף עוד הכשר.
ז.
וא"ת למה לא מזכיר מה שהקבלה בצפון. צריך לומר שכיון שלא מזכיר את כל ההלכה, לא מזכיר אף את מקצתו. יש לדון למה; יש לדון אם זה מפני שלא מזכיר דמיון בכולו או מפני שאז יצטרך להזכיר השינוי בשאר ההלכה. גם יש לדון אם אולי נוכל להוכיח מזה איזה תלייה בדינים, לומר שמה שהוא ביד ומה שהוא בכלי עושה שמה שהוא בצפון לא שווה. ותחשב.
וא"ת למה לא מזכיר שאר דברים שנוהגים בכל קדשי קדשים. אף כשמקשה הגמרא, מקשה רק מזה, ולא משאר ההלכות. ותחשב. אם נאמר שעיקר המשנה הוא בשחיטה, וקבלה בא אגב, וכל הסדר בא אגב שמזכיר סדר, יש לומר שכאן הסדר אף לא התחיל, שרק הזכיר שחיטה. (לפי זה, אפשר לומר ש"זבחים" לא רצה לומר קרבנות, אלא רצה לומר "שחיטות," שזהו פירוש הפשוט של זביחה. אבל, נראה שאז היה אומר "מקום הזביחות," ולא "מקום הזבחים.") אבל, קצ"ב למה נאמר ששחיטה היא עיקר המשנה, שלכאו’ כמו שמשנה ירצה ללמד לנו דין שחיטה, כך ירצה ללמד לנו שאר הדינים. ותחשב. אולי לא קשה לגמ’ שלא יזכיר כל דבר (צריך ביאור למה לא), ורק מקשה שדין שחיטה טוען דין קבלה, כיון שהם כל כך דומים. (יש לדון אם הוא שדומים בדין או שדומים בלומדות.) ותחשב.
אבל,  צריך לחשוב אם יש דינים כזה, שאין דין זריקה שווה, ואין דין אכילה שווה. נראה שעדיין דין מעילה שווה. אבל, המשנה לא מזכיר דיני מעילה בכלל (מסתמא מפני שהמשנה מדבר בעבודה בזבחים, ולא באיסורי זבחים).
ח.
חולקים אחרונים אם קבלת הדם של אשם מצורע ביד צ"ל בצפון או יכול להיות בכל מקום בעזרה.
ט.
גמ’ מקשה למה לא להתחיל בעולה, כיון שעיקר דין שחיטה בצפון כתיב בו.[fn:5][fn:6] דוחה גמ’ שחטאת שבא מדרשה חביב לו.[fn:7] מקשה גמ’ למה לא מתחיל בחטאת חיצוניות[fn:8]. משיב גמ’ שמזכיר אלו מפני שדמם נכנסים לקדש קדשים. [fn:9]הנחנו שזה תשובה אחרת, והוא סיבה גם להעדיף של יה"כ לעולה. אבל, אינו מוכרח כן, שאולי מצטרף לטעם ראשון, שמה שנלמד מדרשה חביבה לו. ותחשב.
י.
צריך לעיין בזה; צריך לציין לקמן למקורות. לכאו’, צריך לומר שכיון שמרבים הרבה מיני חטאות, מניחים שנוהג בכל חטאת, אף ששאר נלמדו זה מזה בתחילת יבמות, ואין של יה"כ בכלל אותו חשבון. גם אפשר שנתרבה מן ההיקש שמצאנו לעיל (מ), שמ"לפר" הכתוב בפר העלם דבר מרבים פר של יה"כ. אפשר שזה משווה את דינם לזה. אבל, עדיין צריך מקור לשעיר של יה"כ. גם אפשר ללמוד אותו מקל וחומר שנזכר שם, לפי רבי ישמעאל, כיון שהוא אותו מין של פר חטאת (שהוא דומה בכל דינים לשעיר יה"כ, אף שאינם מין אחד, וכש"כ ששווה לפר העלם דבר, שהוא מאותו המין. וכמו כן, מבאר, לומדים שעיר יה"כ משעיר ע"ז. דע שבין כך ובין כך קשה לבאר מהי"ת עיכוב לרהבדר"נ (מא:) בשעיר של יה"כ. צריך לומר שיש איזה לימוד שמשווה את דינו לדין הפר.
יא.
כן נראה מסברה, שאין מקור שיהיה בצפון. אבל, קצת קשה למה לא נאמר שמיעוט מ"אותו" ממעט אותו רק מדין בדיעבד, ולא מדין לכתחילה. אז, לכן נצטרך שני פסוקים, כמו שמביא גמרא, ולא יהיה מקור שהמקבל צריך להיות בצפון. אם כן, מסקנת הגמרא קשה. משמע שמפסוק אחד יכולים למעט גם דין לכתחילה. אבל, איני יודע למה.
יב.
כמו שנבאר, בע"ה, זה כתוב פעמיים. כל אחד יכול להיות מקור בפני עצמו, אבל כתב שני מקורות כדי ללמד דין אחר, כמו שנראה, בע"ה.
יג.
יש להסתפק אם הוא מעכב. לכאו’, אין סברה לחשוב שמעכב, שלא מצאנו שכפל בו תורה. אבל, יש הוכחה שמעכב, שהרי יש שפירשו שרק מזכיר כלי שרת בקבלה, ולא בשחיטה, כיון שבשחיטה הוא רק חיוב לכתחילה, אבל בקבלה מעכב. כנראה, סוברים שמעכב, אבל איני יודע איך מפרשים מקור לזה. צריך לומר שאין זה דין בקבלה, אלא זה מהות קבלה, ואז אין צריכים שיכפול עליו הפסוק לעכב. יש בזה חידוש במה שלא צריכים כפל פסוק לעכב אם נאמר שהוא ממהות העבודה, אבל זה נראה מסתבר. יותר מחודש לומר שזה ממהות הקבלה; אפשר לומר שמה שצריך להיות בכלי הוא ממהות הקבלה, אבל מה שהכלי צריך להיות כלי שרת לא נראה שהוא ממהות הקבלה, ובוודאי לא יותר ממה ששחיטה צריכה להיות בכלי שרת. יש לדון, שאולי כיון שאין שחיטה עבודה, כמו שאומר גמ’ בכ"מ (ולומד אותו מן ההכשר בזר), לא כל כך מסתבר שמה שצריך להיות כלי שרת הוא חלק ממהות העבודה. עדיין זה צריך ביאור.
יד.
יש שמדייקים מכאן שרק קבלה צ"ל בכלי שרת (כמובן, כל זה נוהג בכל קרבנות), אבל שחיטה לא צ"ל בסכין של כלי שרת. יש שדוחים שמזכיר אותו בקבלה לומר שגם הכלי צריך להיות בצפון. (איני יודע מהו המקור לזה, שהבאנו מקור למקום קבלה ומקור למקום הכהן, אבל אינו יודע המקור למקום הכלי. אפשר שמניחים שמקום הכלי הוא מקום הקבלה. אבל, אז, צריך לומר שאף על פי כן, לא אומרים כן בשחיטה. ותחשב.) אבל, בוודאי לכתחילה צ"ל בסכין של כלי שרת, כמו שאומר גמ’ בזבחים (צז:) שם , דורש ממש”א, “וישלח אברהם את ידו ויקח את המאכלת ,” שנאמר גבי עולה שהקריב אברהם לומר שצריך סכין בעולה. לומד מ”זאת התורה…” להשוות את הכל לעולה, לומר שכולם צריכים סכין. (איני יודע אם הדיון כאן הוא אם יש חילוק בין שחיטה לקבלה – ואף בזה, איני יודע אם  הדיון הוא אם בשחיטה מעכב או אם בקבלה מעכב – או אם המשנה היה מזכיר אותו בלי עיכוב. ותחשב. צריך ביאור איך נחלק בין מה שצריך כלי בשחיטה למה שצריך בקבלה, שלכאו’ שניהם נלמדים בכמעט אותו לימוד, שהוא מקור ממעשה שהיה, ולימוד מ”זאת התורה.” ותחשב.)
טו.
עיין בסדר עבודה, שאומר שמתחיל במזרחית צפונית, וגומר בדרומית מזרחית. איני יודע למה גומר בדרום קודם מזרח, אף שלא התחיל בצפון קודם מזרח. ותחשב.
טז.
איני יודע מהו המקור שנותן על כל ארבע קרנות שלו, שכמו שנראה לקמן (בפרים ושעירים הנשרפים) מה שכתוב שניתן על מזבח הפנימי לא אומר שניתן על כל ארבע הקרנות. אולי זה נלמד מפרים ושעירים הנשרפים. כמו כן, צריך ביאור איך נלמד שצריך להיות אחד ושבע, ולא רק שבע. צריך לעיין בכל מקורות אלו.
יז.
וא"ת הרי יש יותר דם פר מדם שעיר.[fn:10] חולקים תנאים ביישוב לקושיה זו. רבי יהודה סובר שאין דם מבטל דם כיון שהם מין אחד. מזה לומד רבי יהודה הכלל ש"מין במינו לא בטל.” רבנן סוברים שאין דם  מבטל דם כיון ששניהם עולים על המזבח. מזה (וממקורות אחרים שנמנו בזבחים (פא)) לומדים רבנן הכלל ש"אין עולים מבטלים זה את זה.
יח.
כנראה, יש איזה לימוד מפר של יה"כ לשעיר של יה"כ. צריך לעיין מהו. אבל, הרבה דינים יצרכו ללימוד זה. יהיה שייך בכמה מקומות להלן; לא נבאר אותו בכל מקום, כיון שכבר הערנו אותו כאן.
יט.
קצת קשה למה צריך פסוק לזה, שאף בלי זה, נאמר ש"אין מעבירים על המצוות,” וכיון שמתן דם שלו לפנים, בהכרח שם פוגע ראשון, ושם צריך לתת הדם.
אפשר לומר שכאן גופא הוא המקור לכלל ש"אין מעבירים על המצוות"; צריך לחפש ולעיין בזה. יש לומר שבלי פסוק זה, הדין יהיה שאם עבר (אולי ממש עבר, או אולי מחמת איזה אונס) והוציא את הדם כבר, ועכשיו הוא יותר קרוב ליסוד הדרומי, ישפוך את הדם שם. כדי לומר שזה הנפקא מניח, צריכים להניח שני דברים. דבר ראשון שנניח הוא שאם אדם עבר על מצווה, כשחוזר לעשות המצווה, לא אומרים שצריך לחזור למקום שעבר (למשל, היה אפשר לומר שאותו מקום כבר "זכה במצווה.” כן נראה.) אבל, אף אם זה לא היה נכון כשעבר, מסתמא זה יהיה נכון כשעובר באונס, ואז יישאר נפקא מינא. הנחה שנית הוא שאחרי הפסוק ההלכה היא ששופכים במערבית, אף כשאינה יותר קרוב לו. כן נראה, שהוא עדיין קרוב לפתח אהל מועד. אז, אף אם נלך בלשון פשוט של הדרשה, כן נאמר. ותחשב.)
כ.
צריך לעיין, שנראה שיפגע בזה באותו זמן שפוגע בזה. אז, קשה למה לא נאמר שיכול לבחור איזה שרוצה. אולי כן הוא הדין, וכן רצה ללומר.
כא.
צריך לעיין בכל זה. מקור ראשון הוא רק בפר, ושני הוא בפר ושעיר. לכאו’, אז, נמצא שטעם ראשון של עיכוב נוהג רק בפר. אם נאמר שזה המקור לעיכוב, למי שאומר שמעכב, יאמר עיכוב רק בפר. אבל, אפשר שיש איזה דרשה שמשווה את הדינים שלהם.
כב.
עיין במקור ראשון, ששם רבי אומר כן. עליו, רבי ישמעאל ורבי עקיבא אומרים מקור שני. אבל, מקושיית גמ’ (שיעכב), ומפי’ רש"י עליו (שהוא מפני ששינה עליו הכתוב, כיון שיש קו"ח), רואים שלא חולקים. אבל, עדיין אפשר שרבי ישמעאל ורבי עקיבא מוסיפים על רבי, אבל רבי לא סובר כמותם. אולי רבי סובר שלא יכולים לדרוש קל וחומר (אולי מה שניתן על גבי מזבח החיצון יכול להיות נחשב פירכא, אולי מפני שיש בו חומר, ואולי מפני שיש בו סיבה שישפוך שיריים במזבח החיצון, כיון שדמו ניתן על מזבח החיצון. ותחשב.) וא"ת איך אפשר שמוסיפים על רבי, כיון שחיו לפני רבי (וזה קשה בין אם חולקים על רבי בין אם לא חולקים). ויש לומר שתנא מביא שאמרו קו"ח, ותנא מוסיף שיטת ר"ע ור"י על שיטת רבי, וכאילו אומר שיש שתי שיטות בזה. ותחשב. אבל, יש להעיר שמהמשך הגמ’ מוכרח שר"ע ור"י הם האומרים שלא מעכב. צריך ביאור.
כג.
יש לדון למה אין עוד מקור: בפר כהן העלם דבר של ציבור כתיב, “לפר,” לומר שדין חטאת יה"כ שווה לדין פר העלם דבר. לקמן, נבאר מקור שדם של פר העלם דבר של ציבור צריך להינתן על יסוד מזבח החיצון.
כן הייתי חושב, על פי מה שכתבנו לעיל, אבל גמרא לא אומר כן. איני יודע למה, שלכאו’ זה יכול להיות לימוד. אולי מניחים שלא יכול ללמד דין שיריים, שאין בו עיכוב. ותחשב. גם אפשר שלא משווה לכל דבר, אלא רק מלמד דין אחד. צריך ביאור למה נאמר כן, שבדרך כלל, היקש מלמד כל הדינים.)
כד.
נראה שזהו כוונת הגמרא. אבל, איני יודע למה אין עשה יכול להיות מעכב. ותחשב. אולי הענין הוא שלא מצאנו דינים בדיעבד בעשיין, שהרי (חוץ משני יוצאים מן הכלל) אין עונשים על ביטול עשה. ותחשב. אף שזהו פשטות הגמ’, אפשר לומר שגמ’ רצה לומר שניתק אותו מן העיכוב בפסוק זה, ודורש אותו כרבי עקיבא, וסובר ש"כיפר" משמע מתנות, ומשמע שלא מדבר על שיריים (לא רק שלא משמע שיירים, אלא שמשמע לא שיריים).אבל, לשון "ניתקו לעשה" לא משמע כן.)
כה.
וא"ת אם כן למה כתוב; לא לכתוב פסוק ששינה עליו, ולא לכתוב פסוק שעושה אותו לעשה. ויש לומר שרוצה לשים בו עשה, אבל אילו היה כתוב רק עשה, זה היה נחשב שינוי עליו לעכב. לא נראה כן. יותר נראה שטרח וכתב התורה מה שיכול להילמד מקל וחומר. יש להוסיף שאין הקו"ח כל כך פשוט, שהחומרא שאומר שישים בשיריים הוא שהדם ניתן בפנים. כיון שאלו לא תלויים כ"כ זה בזה, מסתבר שיטרח הפסוק לבאר מה שנלמד בקו"ח כזה.
כו.
אין זה כל כך ברור לי, אבל נראה שאף אם לא ידוע מה מעכב, יודעים שמתנות עצמם שונות משפיכת שיריים. אולי הענין הוא שהמתנות מוסיפים לכפרה, אבל שיריים לא עושה כן. (אולי צריך אותו כדי שמתנות יכפרו, כמו שצריך שחיטה, אבל בוודאי אינו הכפרה. ותחשב. על פי זה, נראה שאולי הסיבה שאין השיריים בכלל "כילה" אינו רק מפני שאינו עבודה חשובה, אלא מפני שהפסוק אומר שאם כילה כיפר. אפשר שקוראים את זה לומר שאם כילה, אז במה שכילה כיפר. אז, בוודאי לא כולל שפיכת שיריים, שאף אילו היה מעכב, לא היה חלק מן המכפר. ותחשב. זה מניח שבצד שיעכבו, הם לא מכפרים. יש לדון במקור (מן הפסוק) לזה.)
כז.
וא"ת, הרי פשוט שאלו מעכבים, שהרי הם מכפרים. אפשר שהחידוש הוא ששאר הדברים לא מעכבים. אבל, מוכרח מן הגמ’ נגד זה, שגמ’ מביא שתי דרשות אלו, ומצדד שאין חילוק ביניהם. עדיין, מצדד ששיריים מעכבים. יש לדון, שאולי סובר שיש תנא שלא דורש את הפסוק בכלל. אבל, עדיין לא נראה כן, שגמ’ לעיל (בדיחוי למקור ראשון) לא משמע שאומר זה. אילו זה היה כוונת רבי עקיבא, היה אומר כן.
משנה ב
כח.
יש גם דינים אחרים שהם דומים, כמו מה שכל המתנות מעכבות.
כט.
גם פר של יה"כ נשרף, אבל כבר דיבר בזה, ואז אינו נכלל במשנה. כמו"כ, גם שעיר של יה"כ נשרף, אבל כבר דיבר בו. אבל, בסוף המשנה יאמר "אלו ואלו," ויכלל גם שנים אלו באותו הדין.
ל.
לא כל כך פשוט לי מהו המקור לזה. רמב"ם על המשנה פירש שנלמד מחטאת של כהן משיח. אבל, רמב"ם לעיל (ד-ד) פירש שנלמד מפר העלם דבר של ציבור. כמו"כ, כ’ רמב"ם בהקדמה שלו לסדר קדשים. עיין שם, שכ’ שהוא בנין אב, אבל גם מביא ממש"כ, “חטאת הקהל היא.” אז, לא ברור לי אם הוא רק בנין אב, או אם יש לימוד מפסוק לזה. (הפסוק שמביא משמע יותר שהוא היקש, שכולל חטאות הקהל לדבר אחד.) עיין ברע”ב על משנה זו, שכ’ שנלמד מהיקש לפר העלם דבר של ציבור, וכמשמעות שני של מש”כ הרמב”ם בהקדמה ולעיל.
שוב ראיתי שגמרא לעיל לומד אותו מפר העלם דבר של ציבור מפסוק המיותר של "החטאת” ו”חטאתם.”
לא.
לכאו’, חילק קרבנות יה"כ בדברים ששונים בהם, כמו מתן דם. אבל, יש להעיר שגם מזכיר בו דברים השווים (כמו מקום שחיטתו וקבלתו). אז, קצ"ב מה מזכיר במשנה ראשונה ומה מזכיר במשנה שלאח"ז.
לב.
צריך לעיין אם צריך שבעה ואחד מתנות, כמו גבי פר ושעיר של יה"כ. גם צריך לעיין איפה נותן ההזאות, אם הוא כנגד בין הבדים, כמו בשל יה"כ. ותחשב.
לג.
איני יודע סדר נתינתו, אבל מסתמא נותן כמו שנותן בשל יה"כ.
לד.
קצת קשה לפי זה למה לא ניתן על השולחן, שגם לו יש קרנות של אהל מועד. צריך לומר שרק נותנים איפה שמסתבר לתת, ורק מצאנו שדם הולך על מזבח, ולא על מקום אחר. ויש לדון, שאף שלא רואים שדם ילך על שולחן, רואים שילך על מקום שאינו מזבח, שהולך על פרוכת, ולפעמים גם לארון. ותחשב.
לה.
צריך ביאור מהו המקור לזה. אפשר שיש לנו איזה פסוק (אולי הוא בכלל מש”כ, “הדם הוא בנפש יכפר”), וגם אפשר שלא יכול ללמד על סמיכה, כיון שיודעים שבעלמא לא מעכב (מחמת הפסוק שהבאנו לעיל). כיון שיודעים שלא נוהג בסמיכה, לא יכולים להניח שנוהג בכל דבר, אף שיש חילוק גדול בין סמיכה למתן ארבע, והוא שבסמיכה תמיד לא מעכב. אבל, כיון שלא הולך על כל דבר, צריכים לחוש שרק הולך על דבר אחד. ודע שקצת קשה למה לא אומר שההו"א הוא שלא נוהג במתן ארבע כיון שבחטאת החיצון יש מתן ארבע (אף שהוא במקום אחר) ואין כל מתנה מעכבת. אפשר שכן הוא כוונתו, ורצה לומר שכיון שלא תמיד מעכב, הוא כעין סמיכה. אבל, סתימות גמרא ורש"י לא משמע כן.
לו.
צריכים אחד מן הפסוקים ללמד דין הזאות, שכתובים בו בפירוש, וצריכים האחר ללמד דין לכתחילה של האימורים, שלא כתוב בו.
לז.
גמ’ דורש את זה ממש"כ, “ושרף אותו כאשר שרף לפר הראשון.” קשה למה לא אומר שהוא מפני שלכל דבריו הוקשו שני הקרבנות זה לזה, כמו שדורש גמ’ בזבחים (לט). בי"כ ובי"כ צריך לסמוך על אותו גמ’, כדי ללמד את הדין לפר יה"כ וכדומה.), וגם כ’ שהוא שווה למקום הוצאת הדשן.
לח.
גמ’ דורש את זה ממה שאומר שנשרף ב"שפך הדשן.” אבל, קשה, שחולקים בזה רבי יוסי ורבנן, ללשון אחד בגמ’, שלרבנן, לא צריך להיות במקום הדשן. צריך לומר שעדיין נקרא מקום השדשן כיון שהוא באותו מקום לענין יציאה ממחנות של דשן. ותחשב.
משנה ג
לט.
הלשון קצת לאו דווקא, שראש חדש נקרא מועד, כמו שאומר גמרא בתחילת ראש השנה, ובכ"מ.
מ.
הנחתי שבאמת יכולים ללמוד זה מזה כאן. הנחתי כן כיון שנראה לי שהוא נכון, ומפני שמבאר למה צריכים "אותו,”כמו שנראה לקמן, ומפני שמבאר איך יודעים שאר מיני חטאות לקמן. אבל, יש לדון, שזה נלמד מהיקש, שנלמד מהיקש עם עולה. אז, לא פשוט שיכול ללמוד לכל שאר מיני חטא. צריך לעיין איך הם נלמדים, וצריך לעיין איזה לימודים לומדים בקרבנות. ותחשב.
מא.
וא"ת למה צריכים הפסוק הראשון, שיכולים ללמוד מפסוק השני. אפשר לומר שאין הכי נמי, וכתוב רק כיון שדבר הנלמד מדרשה טרח וכתוב בפירוש. גמרא לא כ’ כן, אלא הביא גם פסוק של שעיר נשיא, כיון שהולך בסדר שהפסוקים כתובים, ואין כל כך שינוי שיוצא בין הדרך שהגמ’ מביא אותו למה שהוא באמת. ותו"ת.
אבל, יותר נראה לומר שהוא מפני שכתיב "אותה" בחטאת יחיד. אבל, כתוב כן בכבש, שהוא פעם האחרון שכתוב. אז, כיון שהוא כתוב אחרון, יש להסתפק בזה, שאולי מזה רק נוכל למעט עיכוב. אז, עדיין צריכים רק פסוק לומר עיכוב בשאר חטאות חוץ מיחיד. ויש לדון, שאולי המיעוט מפסוק אחד אומר שמה שהיה נלמד מפסוק אחד, שהוא הדין לכתחילה, ממעט. ותחשב.
מב.
כמובן, יש לדון אם השחיטה פסולה או הקרבן פסול. בין כך ובין כך, הקרבן פסול, שקרבן צריכה שחיטה, אבל יש חילוק בלומדות.
מג.
איני יודע אם זה, באמת, נלמד מלשון המשנה. המשנה רק אומרת, “שחיטתן בפצון.” אפשר לומר שזה רק לכתחילה. אבל, הגמ’ מחפש למקור מפסוק לזה, ולא מביא מקור אחר ממשנה לזה, ומשמע שידוע ממשנה שלנו. ותחשב.
מד.
זה מפני הכלל שמצאנו שכדי שדין יהיה מעכב בקדשים, צריך ששנה עליו הכתוב לעכב. יש לדון למה זה נכון. אפשר להיות שאין טעם, אלא שכן הוא ההלכה למשה מסיני. אפשר להוסיף קצת הבנה, לומר שהוא דומה למה שאין לומדים מהיקש מהיקש, והוא שבשניהם רואים יסוד אחד, והוא שדרשה יותר קשה.
נראה שהביאור לשניהם יכול להיות שכיון שאין דברים אלו כל כך מובנים לנו, אין סברה לדרוש (או שאין הדין הכתוב כל כך "כתוב,” שרוב דינים הכתובים גם כתובים וגם מובנים קצת). ותחשב. אבל, יש לדון אם נכון שזה יותר לא מובן. הרי, רואים הרבה דינים שלא מובנים, כמו פרה אדומה, וכמו טרפה, שלא לומדים זה מזה.
מה.
לא כל כך פשוט לי מהו הדרשה. אפשר שהוא סמיכות, ואפשר שהוא היקש (מצאנו היקש כעין זה, אבל צריך לחלק בין היקש כזה לסמיכות. אולי אין חילוק, אלא שלפעמים קורא לו זה ולפעמים קורא לו זה. במילים אחרים, אולי הוא מין של היקש שנקרא סמיכות, ולפעמים קורא לו בשם כללי שלו ולפעמים קורא לו בשם פרטי שלו. גם אפשר שהוא מפני ההמשך, שלא מזכיר שהולך ממקומו. עיין בראשונים ביבמות (ד) שדנו בכעין זה.)
מו.
פסוק זה בשעיר נשיא. לכאו’, לומדים אותו לשאר חטאות, כמו שבארנו לעיל, שבדר"כ לומדים מחטאת לשאר חטאות. אף שממשיך מפסוק שבו כתיב מיעוט, אין בו עצמו המיעוט. יותר מזה, לא דורשים מזה המיעוט למסקנא, כמו שבארנו.
מז.
כן הנחתי. צריך לחפש אם זה נכון. ותו"ת. אבל, איני יודע מהו המקור לזה, שלא מצאנו מקור לו, אלא רק מצאנו פסוק אחד. אם  כן, לכאו’ לא יעכב. אולי אחרי שמצאנו שדין צפון מעכב בשחיטה, מסתבר שכשנאמר בקבלה, גם נאמר לעיכוב. ותחשב.
מח.
מסתמא, ראשו ורובו צריך להיות שם, כמו בסוכה. אבל, איני יודע, שהרי כל הכהן מעכב לקבלה, שלא יכול להיות כהן חסר. ותחשב. כמו כן, כולו צריך להיות לפנים, בעזרה. אז, אולי גם כולו צריך להיות בצפון.
מט.
אין זה כל כך ברור לי. אני בארתי שהדרשה הוא שכמו ש"ולקח" רצה לומר בצפון, כך מה שנדרש משם אומר כן. אבל, לא מוכרח כן, שיש לומר שמה ש"ולקח" אומר צפון אינו סיבה, אלא הוא סימן. כמו של"ולקח" יכולים לדרוש צפון, כמו שבארנו לעיל, כך ל"לו יקח" יכולים לדרוש צפון. ותחשב. (אבל, יש להעיר שאחד מן הביאורים שכתבנו הוא שלא מזכיר ששינה את מקומו, וממילא מקבל בצפון. אבל, כיון שאין השוחט בצפון, רק נלמד מזה שהקבלה היא בצפון, שרק נלמד שלא נשתנה מקום הבהמה. ותחשב.)
נ.
לא ברור לי למה נדרוש מ"ולקח" כן. אפשר שמצרפים את הו"ו ללמ"ד בתחילת המילה. אבל, דע שאין זה עומד למס’. אבל, מקשה גמ’ ממנו, וצריך לומר שיש הו"א טוב לומר כן.
נא.
כן הנחתי. צריך לחפש אם זה נכון, אבל עיין במשנה ראשונה שבמעילה, שמשמע שהוא נכון. ותו"ת. אבל, איני יודע מהו המקור לזה, שלא מצאנו מקור לו, אלא רק מצאנו פסוק אחד. אם  כן, לכאו’ לא יעכב. אולי אחרי שמצאנו שדין צפון מעכב בשחיטה, מסתבר שכשנאמר בקבלה, גם נאמר לעיכוב. ותחשב.
נב.
גמ’ לא מביא מקור לזה, אבל לכאו’ המקור הוא מפשטות הפסוק, שהפסוק אומר לתת דמים על הקרן. אז, רק יכול לתת אותו על הקרן עצמו, שהוא מקום הראשון.
יש להעיר שהמשנה אומר שהולך על הסובב. הסובב היה גבוה ששה אמות. כיון שהקרן היה באמה העשירי, לא פשוט איך יגיע לשם אם ילך על הסובב. אפשר שסתם בן אדם יכול להגיע יותר משלש אמות, שהוא כמדת גבהו. גם אפשר שחלק זה של המשנה אינו כשיטה זו. ודע שאינו יודע המקור שיעלה בסובב. נראה שאין מקור, אלא שיותר קל לעשות כן מלכרוע. אם כן, יותר מסתבר שאין זה הולך כשיטה שלנו, שאף אם יכול להגיע לשם, עדיין לא נראה שיהיה יותר קל מללכת על המזבח ולכרוע. ותחשב.
נג.
לומד זה מפסוק שאומר שהמזבח היה ארבע אמות. בוודאי לא היה, באמת, ארבע אמות, בין בגובה בין ברוחב, ואז מפרשים שרוצה לומר שהקרבנות יש להם רשות של ארבע אמות, שאם נתן מן חוט הסיקרא עד הקרנות, כשר לחטאת, כאילו נתן על הקרנות.
נד.
לא כל כך ברור לי מאיזה חלק מן הפסוק לומד כן, שהפסוק אומר: “וההראל ארבע אמות ומהאריאל ולמעלה הקרנות ארבע.” איני יודע אם לומד מן התחילה או מן הסוף. לכאו’, לשניהם אין מובן – לראשון אין מובן כיון שאינו נכון, ולשני אין מובן כלל. לשון גמ’ משמע שקושייתו הוא שאינו נכון, ולא שאין לו מובן, ואז ממשע שלומד מן הראשון. אבל, עדיין צריך ביאור; צריך לעיין בזה.
נה.
כמו שנראה, אולי בית שמאי יחלקו גם כאן; זה יהיה תלוי במקור לכאן.
נו.
לכאו’, נלמד מכאן ששפיכה גם מהני בדיעבד. יש לומר שלצד זה אמר לשון שפיכה כיון ששמע שניתן פעם אחת (שבדר"כ אחרי ששופך, לא נשאר שם עוד דם.). אז, אין לדקדק מכאן שיכול לשפוך, שזה רק דרך לומר שנתן מתנה אחת.
נז.
ק"ק איך נלמד מחטאת, שמצאנו בו קולא על עולה, כיון שאין כולו נשרף.
נח.
אולי סובר שדון מינה ואוקי באתרא, או אולי סובר שאחרי שהפסוק אומר אותו כן, ואולי כן נראה מסברה, עיקר הדין הוא לשים באיזה נקב שיבוא בו, בדר"כ, ראשון. ותחשב.
נט.
נמצא, אז, שאין דבר ניתן ביסוד דרומי. אם כן, קצת צריך ביאור למה יש נקב שם. אולי שיטה זו סוברת שיכול לתת באיזה שירצה, שהדרום דומה למערבי של קרבנות הפנימיוןת, ומערבי דומה למערבי של קרבנות הפנימיות. אבל, לא נראה כן, משלשה טעמים. טעם ראשון הוא שגמ’ לא מזכיר כן, אלא רק אומר שהוא במערבי. טעם שני הוא שדרשה כזו מחודשת, שלא, בדר"כ, לומדים שדבר צריך לדמות בענין אחד משני עניינים. טעם שלישי הוא שכיון שפוגע בדרומי ראשון, חייב לשפוך לשם ברוב פעמים. אז, לא נראה שגמ’ יאמר שישפוך למערבי, אם יש חיוב אחר – חיוב של אין מעבירים על המצוות – שהולך נגד זה. ותחשב.
ס.
לכאו’, יכולים ללמוד זה מזה, כיון שהוקשו, כמו שאומר גמ’ ביבמות. אבל, מהמשך הגמ’, לפי רש"י, לא נראה כן. צריך לומר שזה רק לענין מה מביא, ולא איך מביא. אבל, מה שאומר גמ’ לענין מקור לשחיטה לא משמע כן, אולי. צריך ביאור.
סא.
יש לדון אם הוא ממעט מנתינה בפנימי, ואומר שלא רק אין לעשות כן, אלא אי אפשר, או שהענין הוא שיש שני דברים נלמד מפסוק זה - שיש יסוד לחיצון, ושיתן שם, ובא למעט פנימי משניהם.
סב.
יש לדון אם מכוון ליסוד או לנקבים בו. למעשה, אין לו יסוד, ויל"ד מהי"ת שלא מכוון רק לנקבים.
סג.
וא"ת הו"א שלא צריך לישפך כלל. ויש לומר שהו"ל לומר שנשפך ביסוד, ולא לפרט איזה יסוד.
סד.
רש"י מזכיר שבחטאת חיצוניות כתיב פעמיים שצריך נתינת דם ליסוד. איני יודע למה צריכים פסוקים אלו למסקנא. צריך לעיין בזה.
סה.
גמ’ רק אומר שמרבים חטאת ואשם. אבל, הנחתי שמכוון לרבות כל קדשי קדשים, שלכן נקט לרבות שני דברים, ולא רק אחד מהם (או חטאת או אשם). ותחשב. ע’ במנחות (צא:).
סו.
יש לדון אם חוששים שיאכל אחרי עלות השחר או שלא יאכל לפני עלות השחר, ויצטרך לשרוף. גם יש לדון אם חוששים למה שאינו נאכל (ולא מקיים אותו מצווה) או למה שנשרף או נאכל באיסור.
משנה ד
סז.
יש לדון למה הקדים אותו לאשם. אין צריך להיות סיבה גדולה, שלמה לא יקדים אותו. אבל, קשה, שיש סיבה שלא יקדים אותו, שהרי מה שנלמד מדרשה חביבה לו, כמו שאמר בפירוש (מח.). נראה שיש לומר כמה שצדדנו בהערות שזה נדחה, ולמסקנא מה שכתוב בתורה היא העיקר. אז, יש לומר שעולה הקדים לאשם כיון שכתוב בו צפון בפירוש. ותחשב.
סח.
איני יודע אם זה מפני כלל בלימוד או מפני קל וחומר. כלל בלימוד אומר שכיון שדין נוהג בחטאת מחמת פסוק שאומר שהוא כעולה, מוכרח שאותו דין נוהג בעולה. קל וחומר אומר שיש יותר סיבה שדבר יהיה מעכב כיון שכתוב בפירוש, ולא נלמד מהיקש, שהוא יותר חמור. עיין בלשון הגמ’, שמשמע שהוא קל וחומר. ותחשב.
סט.
לכאו’, נלמד מזה לעשות כל דינים שבעולה מעכבים. יש לדון, שאולי הוא רק עושה דין אחד מעכב, ומסתבר לגמ’ שהדין שמעכב הוא דין צפון, אולי אף מפני סברה של מקור ראשון. גם אפשר שאולי רק מה ש"עושה אותו לעולה" – ויש לדון מה בכלל זה – הוא נכלל בדרשה זו. ותחשב.
ע.
איני מוצא מקור לזה. כנראה, צריך לומר שנלמד מחטאת. אבל, לצד שני של הגמרא, שאומר שלא לומדים עולה מחטאת, ואז לומדים מפסוק מיותר, קשה איך נלמד כל זה. גם אם לומדים אותו מחטאת, חידוש גדול הוא לומר שיכולים לומר כן. לכאו’, רק יכולים ללמוד דין שחיטה, כיון שמקור של חטאת הוא שכתיב, “ושחט אותו במקום אשר יחשט העולה,” או כדומה. זה מדבר בשחיטה, ואז מובן שנלמד מזה דין לשחיטה. כדי ללמוד מזה דין קבלה, צריך לתלות שני הדינים זה בזה (וצריך להיות שזה פשוט עד כדי שיכולים ללמוד דין – ואף עיכוב – ממנו. לכאו’, יש שני דרכים לתלות אותם. אפשר לומר ששניהם תלויים בדבר אחד, ואפשר לומר שאחד תלוי וחברו (שאחד הוא רק דין בחברו). כמובן, לשני, יש לדון איזה הוא העיקר, ואיזה הוא הטפל. ותחשב. לביאור שני בגמ’ לעיל, נראה שצריך לומר שכיון שגילה שעולה וחטאת דומים אף בענין עיכוב, יכולים ללמוד מזה לזה, להשוות אותם. דחוק. יש להעיר שגמ’ ימצא מקור גם לעולה (בע”ה, נבאר את זה לקמן). אבל, עדיין לא אפשר לומר שנלמד מצד השווה, שיש לחלק שאולי רק נוהג בקרבנות שמכפרים על לאווים. אבל, אולי כיון שנמצא ביותר מקומות יותר קל לומר שמן הסברה הבינו שזה דין כללי. ותחשב. יש להוסיף שלצד שני, המקור הוא “העולה.” יש לומר שמפני המשמעות, זה יכול ללמד שכל דין לכתחילה מעכב. (אבל, כמו שהערנו, יש לדון אם זה, באמת, הוא הדין, ואם, באמת, זה הלימוד.) אם כן, אולי אפשר לומר שצד זה סובר שיכולים ללמוד מחטאת דין לכתחיה, וכיון שנלמד, לומדים מפסוק זה שמעכב. ותחשב.) (גם איני יודע אם דין זה כולל שהמקבל צריך להיות בצפון. ממה שלא חילק בלשונו, נראה שהוא כולל אותו. ותחשב.)
עא.
יש להסתפק אם לימוד זה גזרה שווה או רק שמפרש מילת "סביב,” לומר שמסתבר שהוא אומר דבר דומה כאן ובחטאת.
עב.
מלשון הגמרא מוכרח ששניהם יכולים להיות בביאור המשנה. יש לדון בזה, שהמשנה אומר ש"דמה טעון שתי מתנות שהן ארבע.” הרי, לפי רבי ישמעאל, יש ארבע מתנות. צריך לומר שנחשב שתי מתנות, כיון ששתים שבקרן כל דך קרובים. אבל, זה דחוק, שדורשים מ"סביב" שיידמה לחטאת, והוא דומה לחטאת גופא במה שהוא בארבע מתנות. אז, לקרוא לארבע מתנות שתי מתנות הוא דחוק. אפשר שיש לומר ש"מתן" לא מדבר על המעשה, אלא על הפעולה. אז, יותר קל להחשיב אותם לאחד כיון שהולכים על קרן אחד.
עג.
לכאו’, צריך לומר שרבי שמעון איש המצפה סובר כשמואל, שלפי רב תמיד נותן במתנות חלוקות. לשונו בוודאי נראה כן, אבל אפשר לומר את הדין שלו גם לרב, שאפשר ששנים הראשונים ניתנים בזריקה, ושנים האחרונים ניתנים באצבע. ותחשב.
עד.
יש לדון אם צריך לשפוך שתי מתנות שהם ארבע או רק צריכים לשפוך פעם אחת. במילים אחרים, יש לדון אם מה שלא מעכב הוא דין זריקה או גם דין סביב. מנפקא מינא של גמ’ בסוף פסחים, נראה שרק צריך שפיכה אחת. ותחשב. אבל, דע שאותו גמ’ צריך ביאור, שגמ’ מקשה איך נלמוד שני דברים מ"דם זבחיך ישפוך,” מסיק שאי אפשר. אז, צריך לומר שמי שסובר שניתן דם מעשר ופסח בשפיכה לא דורש שדם זריקה שנתן בשפיכה מהני. באמת, כן אומר גמ’ בפירוש. אם כן, אין מי שסובר שיכול לברך ברכת פסח על זבח ולא ברכת זבח על פסח, שאם שפיכה מהני לזריקה, אין דם פסח בשפיכה. צריך עיון.
משנה ה
עה.
כנראה, הם קדשי קדשים, והם גם שלמים. שם של קרבן יכול לבוא על אחד מארבע דברים – על המעשים שלו, על הקדושה שלו, על התוצאה שלו, ועל התכלית שלו (זה דומה לתוצאה, אלא שתכלית היא התוצאה הכי חשובה ונצרכת). יש לדון במה הם שלמים ובמה הם קדשי קדשים, ויש לדון אם יש סתירה במה שהיא שלמים וקדשי קדשים,  שאולי לא יכול להיות קדשי קדשים ושלמים באופן אחד מן הארבע אופנים. ותחשב.
עו.
יש לדון למה כולל שנים אלו במשנה אחד. כנראה, הוא מפני שלכל דברים שמזכיר במשנה, אין חילוק ביניהם. ותחשב.  כמו כן יש להעיר בתודה ואיל נזיר. כמו כן צריך ביאור השלש שכלל בסוף הפרק במשנה אחת.
עז.
איני יודע אם הוא מפני שהם קרובים. זהו הפשטות, אבל לא מוכרח, שאפשר להיות (או אולי צריכים שניהם) מפני שיש להם סגנון דומה. ותחשב.
עח.
לא מפרש איזה סוג לימוד הוא. לכאו’, צריך להיות מה מצאנו, שלא מצאנו לימוד אחר ביניהם, ועוד שאז היה לו לרש"י לפרש. אבל, איני יודע. דע שמצאנו כזה רבים, ואפשר שהוא כעין סתום שנלמד מן המפורש, שלא מפורש כאן אם צריך להיות ביד או לא, ושם מפורש שצריך להיות.
עט.
לא פשוט למה מנה אותו כאן, ומפני זה לא רצה למנות אותו בתחילת הפרק. אפשר לומר שכיון שקצת נוהג, רצה לשנותו רק במקום אחד. (כמו כן, יש לומר שרצה ללמד לנו שנוהג ושלא נוהג. אז, במקום אחד לימד שנוהג, ובמקום אחר לימד שלא נוהג.) נקט לומר את הדין בעיקר ציור של אשם מצורע. מלשון הגמ’, היה אפשר לומר שתנא של משנה ראשון לא הכיר שלפעמים נוהג, וחשב שיש רק מין שני של קבלה. אבל, לא נראה כן מסברה, ואז לא נראה שאומר כן. עיין ברש"י, שמשמע שהוא מפני ששם נאמר עם כל הקדשים. גם כאן נאמר עם קדשים, ואז לא קל להבין מה מכוון רש"י לפרש. אפשר שכוונת רש"י הוא רק ששם נאמר עם יותר דברים, אבל יותר נראה שרש"י ר"ל שכיון שנאמר אשם מצורע בפירוש כאן, כאילו הדין נאמר במיוחד עליו, עם השאר, ולא שנאמר עליו לכלל עם האחרים. (זה מזכיר לנו מחלקת תנאים בשבועות במה נחשב שבועה אחת ומה נחשב הרבה שבועות.)
פ.
גמ’ לא מביא מקור שמעכב, ואיני יודע מה יהיה המקור. דע שהלימוד לא כל כך פשוט, שגם צריך ללמוד שאר דיני קדשי קדשים. אולי מאיפה שלומד אותם, גם לומד דין עיכוב.
כשגמ’ אומר הראשון, משמע שרק בא לומר ששחיטתו צריכה להיות בצפון, שזהו דין היחידי שמזכיר בלימוד. אבל, יש דינים אחרים שצריך מקור להם, כמו כל שאר דיני משנתינו. כשגמרא מביא מקור שני, לומד  משם שהוא קדשי קדשים. יש להסתפק, באמת,  מה מכוון גמרא לומר בזה. נראה שיש שלש צדדים. צד הראשון הוא שאין זה עוד לימוד, אלא שרצה לומר שלומדים שהוא קדשי קדשים במה ששחיטתו בצפון. כמו כן מצאנו, לפי רשי, בתחילת פרק שני של קידושין, שאומר דרשה, ומתחיל לומר כלל הדרשה. אבל, יש לחלק מחמת שני דברים. הראשון א ששם הכלל נכון בכל ענין, ולא רק לומדים אותו לענין אחד כמו כאן. השני הוא ששם לומד כמה דינים, ןמסתבר שירצה לומר כלל אחדלכלולל את כולם. א ל, כאן, שרק לומד דבר אחד, לא כל כך מסתבר שירצה לומר אותו בלשון אחר. צד שני הוא שחוץ מלימוד דין זה, גם לומד שהוא קדשי קדשים. זה מניח שיש דין שדבר נחשב קדשי קדשים. אין זה פשוט, שהיה אפשר לומר שקדשי קדשים אינו דבר, אלא הוא מילה שכוללת כמה דינים, כמו דין מקום, דין מעילה, ודין אכילה. (בעזרת ה’, נחזור לנקודה זו.) לפי צד זה, נמצא שלא רק לומדים מזה דבר אחד, אלא גם לומדים מה שהוא קדשי קדשים. צריך ביאור אם גם יכולים ללמוד כל דיני קדשי קדשים מכאן או לא. אם לא יכולים, צריך לומר שלומד לו קדושת דשי קדשים ממה שלומדים לו דין אחד של קדשי קדשים, שכיון שיש לו דין אחד (אולי בפרט דין זה, אבל לא נראה), מוכרח שיש לו קדושת קדשי קדשים. צד שלישי הוא שכשאומר שלומדים שהוא קדשי קדשים רצה לומר שלומדים כל דיני קדשי קדשים. ואם תאמר אם כן מקום שחיטה שלו נכלל במה שהוא קדשי קדשים, ולמה כופל אותו גמרא. ויש ךומר שגמרא כאן הולך על מה ששחיטת השלמים בצפון (אולי רק מפני שזה נאמר ראשון המשנה), ומטרה של הגמרא הוא למצוא מקור לזה. אז, אחרי שמביא פסוק שהוא מקור לזה, אומר שהפסוק מלמד כן. לכל הצדדים, קשה למה לא אומר זה בדרשה ראשונה. לצדדים שיש שינוי בלימוד, כמובן, יותר קשה, שאם יש שינוי רק בדרשה, יש לומר שכיון שאין הראשונה עומדת, לא דק בלשונו. אוליצריך לומר שאף אם לשון זה מוסיף דרשה, היינו דורשים כן גם לראשון, ויש  ביניהם רק לשון.
ואם תאמר מה המקור לשאר הדברים שבמשנה, שמזה רק דורשים שהשחיטה שלו בצפון. למקצת צדדים שכתבנו לעיל, דורשים כל דיני קדשי קדשים מזה, כמו שבארנו. אז, אין להקשות. אבל, אם לא נאמר כן, צריך לומר שנלמד ממה שמצאנו מקור לשחיטת צפון ולאכילה לזכרי כהונה, שאז מסתבר לתת לו כל דיני קדשי קדשים.
המקור שנאכל רק לזכרי כהונה הוא המקור הראשון הנדחה. ואם תאמר למקצת צדדים שכתבנו, קשה למה צריך מקור לזה, שזה נכלל בקדשי קדשים. ויש לומר שכיון שלומדים מעולה, ועולה אין בו דין אכילה, לא יכולים ללמוד דין 5כילה שלו. אבל, עדיין אולי קשה לצד אחד שבצד שני, שצד זה אומר שאין דיני קדשי קדשים דינים חלוקים. ותחשב.)
פא.
וא"ת לצד שכתבנו לעיל שכל דיני קדשי קדשים שבשלמי ציבור נלמדים ממקור שנשחט בצפון, קשה למה לא אומרים כן באשם. צריך לומר שהוא מפני שבפסוק שמקיש נאמר שחיטה, ואז רק הוקש לשחיטה. אבל, בפסוק שמקיש שלמי ציבור לעולה, לא נאמר שחיטה, ואז הוקש לכל דבר. אולי מפני זה לא נוכל ללמוד כל דבר לפי מקור ראשון שם (עיין לעיל, שדנינו בזה), שכיון שהוא על פסוק של "ועשה,” לא דורשים היקש לכל דבר, אלא רק לעשייה (ואולי יש לומר שפירש "עשייה" שם הוא שחיטה). ותחשב.
פב.
גמרא לא מביא מקור לזה. נראה שצריכים להניח שיש דינים שתלויים בקדשי קדשים, והם נוהגים בכל קדשי הקדשים. אז, כיון שדרושים שדבר הוא בכלל קדשי קדשים, שיש לו מקצת דיני קדשי קדשים, נותנים לו שאר דיני קדשי קדשים. צריך ביאור, שיש קרבנות שיש להם מקצת דיני קדשי קדשים, כמו תודה שנאכל רק ליום אחד, שאין להם שאר דיני קדשי קדשים.
שוב ראיתי שרמב"ם תולה מקום קבלה במקום שחיטה תמיד. בנושאי כלים כ’ שהוא מפני שכתיב "ולקח הכהן מדם החטאת.” הביאור הוא שמקור שבחטאת קבלה בצפון הוא מפסוק זה. נושאי כלים כ’ שדורשים מחטאת לשאר קרבנות. נראה שהוא מפני שהוא כלל, אינו שצריך צפון, אלא שמדמים מקום קבלה למקום שחיטה, דורשים לכל מקום. אז, זה המקור לכל קדשי קדשים. עדיין, ק"ק מהיכי תיתי לעכב, שזה נלמד מפסוק אחר שכתוב רק בחטאת. ודע שאפשר שאינו מעכב בשום מקום אחר. יש לדון, שיש לדון מהי"ת לגמ’ לשאול מקור לעיכוב. משמע שידע שמעכב. לכאו’, ידע מפני לשון המשנה. אם כן, צריך לומר שכן הוא הדין בכל הקרבנות, שהלשון שווה. יש לדון, שיש לומר שצריך שאחד מעכב, ואז נוכל לומר שכולם אגב אותו אחד. דחוק. אבל, אפשר שגמ’ רק ידע את הדין, ולא מפני שיש לו מקור מן המשנה. כעין זה, עיין בריטב"א ביבמות (ג:). ותחשב. באמת, כעין זה מצאנו בכמה וכמה מקומות.
פג.
עיין ברש"י שכ' שהוא לימוד מעולה. רש"י מביא לימוד מהיקש של מקום שחיטה (ומעניין שמלמד על מקום זריקה). לכאו', יסבור ששלמ"צ נלמד מהיקש של "על עולותיכם." קשה למה לא לומד ממש"כ סביב, וכיון שלא לומד משם, קשה מהי"ת לומר כן בשאר קרבנות. ותחשב.
פד.
אין זה בפי’ בגמ’, שגמ’ אומר שזה המקור רק שנאכל רק לכהנים. אבל, רע"ב מביא אותו למקור. כן מסתבר, שלא מצאנו מקור אחר, ומסתבר שיכול להיות מקור לזה כמו לזה. כמו"כ מוכח ממה שנקט גמ’ אחד מהם; אילו היה אפשר ללמד רק אחד, היה לו לגמ’ להקשות מהי"ת שזה הנלמד, ולא זמן אכילה שלו. ותחשב.
משנה ו
פה.
אין זה כל כך פשוט. באם יש חיוב כשקרה לו אחד מן ארבע דברים האלו, יש מחלקת ראשונים. רש"י (כת"י) במנחות (עט:) כ’ שהוא חובה. שטמ"ק חלק עליו, שאין מקור לזה מן הפסוקים.  יש שכ’ שהחיוב הוא על כל אחד מן הארבע חוץ מיורדי הים. גם חלקו אם יכולים להביא תודה בנדבה. רש”ש כ’ שלא יכול להקריב, וחת”ס חולק. יש גמרות שמשמע כחת”ס.
פו.
באמת, גמרא אומר כן במשנה הבא, שמדבר בשלמים. אבל, שם אומר גמ’ שזה המקור לדיני קדשים קלים. כמו כמה דברים שבפרק זה, אין אנו יודעים איך נלמד משלמים לשאר קדשים קלים. ותחשב. ודע שבזה גם צריך לדון מה היה ההו"א. (זה מאד נוגע למה ששאלנו איך לומדים משלמים, כי בפשטות ההו"א יהיה שיכול לשחוט בכל מקום שרוצה. (יש להגדיר את זה – מה כשר בכלל "כל מקום שרוצה" – אבל, בוודאי לא צריך להיות בצפון, כי אין מקור שיהיה בפרט בצפון. אבל, אולי כדי לבאר למה יש, למסקנא, לימוד לכל קדשים קלים, נצטרך לומר שמובן שקדשים הולכים לכלל אחד, ודין שנוהג באחד, נוהג בכולם שבאותו כלל. אז, נראה שאילו לא נתחדשו דיני קדשים קלים, נאמר שכל הקדשים הם בכלל קדשי קדשים, ואז ההו"א יהיה שצריך להיות בצפון. וא"ת א"כ למה צריך ליכתב בחטאת, עולה, ואשם. ויש לומר שצריכים פסוק רק אחרי שנתחדש כלל של קדשים קלים. ותחשב. גם עיין ברש”י כאן, שנראה שמפרש שההו”א הוא שצריך להיות ממש כנגד הפתח. אז, מכשיר קצת מן הצפון וקצת מן הדרום. ותחשב. )
פז.
כן אומר הגמ’. ויש להעיר שכשמדברים על דלתות ההיכל, לכאו’ הכוונה היא על דלתות האולם, שהאולם היא אולם להיכל. אבל, להיכל אין פתח אחר.
פח.
נראה שהוא כל דבר שאינו כנגד פתח. צריך ביאור מהו ההגדרה של “כנגד פתח,” שכמו שרואים, לא צריך להיות כנגד פתח ממש. נראה שצריכים שלא יהפוך על קרן זוית כדי ליכנס לפתח. ותחשב. צריך ביאור אם זה נכון לפי רבי אליעזר, אם אולי יש לו מקור אחר לזה, או אם יודע אותו מסברה (שאין ריבוי לצידי צדדים), או שחולק על זה. ותחשב. גם יש להעיר שלא מצאנו שהוא נוהג, אלא היה פתח לפני כל חלק של העזרה. אבל, גמ’ אומר שבלשכה שלא כנגד הפתח לא יכלו לשחוט, לכאו’ מפני פסול צידי צדדים. אבל, צריך לעיין מהו “שלא כנגד הפתח” לענין לשכה. ותחשב. רש”י מפרש שצריך שפתח הלשכה מכווון נגד פתח לאהל מועד. תפרש מה שהיו שלשה פתחים, בין הכל, להיכל.
פט.
גמ’ מבאר שת"ק סובר שלא צריכים פסוק להכשיר צפון, שנלמד הכשר שלו מקל וחומר מהכשר צדדים. יש לדון למה רבי אליעזר חולק על זה. אולי חולק על הקל וחומר (יש לדון למה; אולי סובר שמה שיש לו מקום הכשר לא מראה שיש לו עוד מקום הכשר, שאולי יש מקום הכשר לזה ומקום הכשר לזה. למשל, לא נאמר שכשר להקריב פר לקרבן חטאת יחיד, מקל וחומר מחטאת ציבור, כיון שמוסיף חטאת יחיד על חטאת ציבור כשרות שעירה וכשבה. ותחשב. (באמת, יש לדון למה לא. אולי הוא מפני שאין סברת קו"ח נוהג כאן, שיש סברה שיהיו חלוקים, ולא שיוסיף עליו. תחשב על זה. גם אפשר שיכולים להפוך כל קל וחומר, כמו בפרק שני של זבחים.)), או שסובר שטרח וכתב ליה קרא (וא"ת יש מה לדרוש כאן. ויש לומר שרבי אליעזר סובר שאין מה לדרוש, ולא צריך פסוק לפסול צדי צדדים. גם יש לומר שלא פשוט מה בכלל "יש מה לדרוש.” כיון שיש סיגנון דרשה של "תניהו ענין" תמיד יש דרשה שיכולים לדרוש מזה. ואין לומר ש"יש מה לדרוש" ממעט דרשה ב"תניהו ענין,” שאין זה כלל חלוק, אלא יש ספאקטרו"ם של דרשות, שהולך מנכתב בפירוש ל"תנהו ענין.” אז, יש לומר שלרבי אליעזר, אין כאן מה לדרוש.), או שסובר שקרא ראשון מרבה רק צפון, ולא שאר צדדים, ואז אי אפשר ללמוד קל וחומר ממנו (ויש לדון בזה, שיש לדון מהו, באמת, הקל וחומר, אם נלמד מהכשר שאר הצדדים (ואז צריך לומר שת"ק, שלא חש לומר כרבי אליעזר, סובר שיש משמעות בפסוק להכשיר את כל הצדדים (ואולי המשמעות הוא רק מה שלא הוציא שום משמעות לצפון יותר משאר צדדים)), או שנלמד ממה שמקצת שאר צדדים הוכשר בתוך "פתח אוהל מועד,” שהרי קצת מן הדרום הוא כנגד הפתח, שהפתח הוא באמצע (וצד זה אפשר רק אם ההו"א הוא כמו שפירש רש"י, וכמו שכתבנו לעיל). ותחשב.)
צ.
לא פשוט לי איך לומדים מקרבן לקרבן. הרי, פסוק שני כתוב בשלמים. לא פשוט לי מהי"ת ללמוד מזה לזה, ובפרט כיון שמצאנו חילוקי דינים ביניהם. אבל, כנראה כן עושה. ותחשב.)
צא.
אין הדרשה כל כך פשוט לי. גמ’ דורש ממש"א שצ"ל במקום טהור, שאטו אלו הבאים לפניו לא צ"ל במקום טהור. אלא, זאת אומרת שיכול להיות במקום טמא. צריך ביאור מהו הדרשה. רש"י כ’ שהוא מפני ששינה ממקום קדוש למקום טהור. קשה, שאולי זה רק מפני שזה באמת אינו במקום קדוש, כמו שלומדים מפסוק ראשון. אפשר שגם רש"י יודה לזה, אלא שרש"י מפרש לפני שידע גמ’ על פסוק ראשון שהבאנו. לולי רש"י, אינו כל כך ברור לי מהו הדרשה, אבל עיין בפרק הערל שמצאנו דרשה כעין זה. אפשר לומר שהדרשה הוא שכיון שנאמר עוד "טהור,” מרבה עוד דבר להיות בכלל טהור. גם אפשר שהוא כעין מיעוט אחר מיעוט. (אולי, באמת, זהו ענין של מיעוט אחר מיעוט. אבל, לא נראה כן.) ותחשב.)
צב.
לא כל כך ברור לי למה זה קשה, שהייתי חושב שלכולם יש קצת קדושה. אז, מסברה נוציא אותו מכולם. אבל, כשאומר שהוא במחנה שיש בו טהרה, צריך להכניס לאחד, ואז מכניסים המעט, ומכניסים לאחד. ותחשב.)
צג.
קשה, שכבר דרש מזה שתודה מין שלמים, שהוא נוגע לענין מחשבת לשמה, שאם חשב לשם שלמים, נחשב לשמה.
צד.
נראה שאולי הוא בכלל הדרשה רק על הצד שהוא דבר שחייבים להקריב. משנה שלנו אולי סובר שאינו חיוב, ואז לא דורש. גי"ל שתלוי במה שחולקים שם בפסחים אם להקיש אותו קרבן לקרבן פסח או לא להקיש. אולי אם מקישים כבר נאכל רק כזמן קרבן פסח, שנבאר זמנו לקמן. אולי כן סובר תנא של המשנה, ולכן לא הביא אותו כאן. ותחשב. ודע שקצת צריך ביאור איך נדרוש שני מיני שלמים מכאן. צריך לומר שדורשים כל מין שלמים שיש לחלק בינו לבין שלמים הרגיל. צריך לעיין בזה.
משנה ז
צה.
יש להעיר שגם נקראים נמוך משלמים במשנה ראשונה, ואז יש לומר שמפני זה הקדים שלמים להם.
משנה ח
צו.
גם יש להעיר שמשניות כסדר משנה לקמן (פט), לענין דם, אבל לא לענין אימורים.
צז.
נמצא שלא דורשים מג"ש כיון שיש שנים (או שלשה) כתובים הבאים כאחד. (אין לומר שהוא בדווקא מפני שיש שלש כתובים הבאים כאחד, שמן הגמרא משמע שרק צריכים כן מפני השיטה שדורשים אף שיש שני כתובים הבאים כאחד. אבל, יש לומר שהיה אפשר להקשות גם ממה שיש גז"ש. אבל, בי"כ ובי"כ, נראה לי שיש ראיות אחרות ליסוד שכתבנו כאן. ותחשב.)
צח.
קשה מהי"ת לרבות את שניהם. גם צריך ביאור למה צריך זה בכלל, ולמה לא נאמר שנלמד מעשר מבכור בג"ש שמשווה את כל הדינים שלהם. אפשר לומר שהדרשה אינה דווקא, ושכך כוונת גמ’. אבל, לא נראה כן, שלא מצאנו תנא שמחצה, וסובר כרבי יוסי הגלילי רק במעשר בהמה. ותחשב.
צט.
לפי זה, צריך ביאור מהו המקור לרבות קרבן פסח.
ק.
קשה מהו המקור למעשר ופסח. אולי צריך לומר שהוא בכלל "ובשרם,” כמו שאולי נצטרך לכתוב לקמן.
קא.
לכאו’, כבר אמר זה, כיון שאמר "נאכל לכהנים… לכל אדם….” רש"י לא גורס את זה, אבל הוא כ’ שלא לגרוס כיון שאינו נכון בבכור, ורק במעשר. לא מעורר מה שכתבנו – שאף במקום שהוא נכון, כבר כתב אותו.
קב.
עיין שם, שנראה שהענין הוא שכיון שלא נאמר זמן, מסתבר שהוא כמו קרבן אחר. רק דנים אם הוא כמו קרבן שלמים או כמו קרבן חטאת. בוודאי אינו קדשי קדשים, שהיה צריך מקור שהוא קדשי קדשים, ואז מניחים שהוא קדשים קלים. (יש להעיר שהיה אפשר לומר שכיוןן שלא נאמר בו זמן, אין בו זמן, ותמיד נאכל. כנראה, מניח שהוא כמו כל שאר קדשים במה שיש לו זמן.)
קג.
קשה למה לא נדמה אותו לעולה. אולי עכ"פ מכפר על עשה, ואז לפעמים בא עליו.
קד.
קשה למה לא אומר שיותר טוב ללמוד ממה שדומה לו ביותר אופנים מללמוד ממה שדומה לו רק במיעוט אופנים (כמו כן  - שילמד ממה שנפישי - מצאנו בכמה וכמה מקומות בגמ'.). אף שגמ' מזכיר שנים כזה ושנים כזה, בוודאי יש יותר דרכים שבו דומה לקדשים קלים, שהרי זה כולל כמה דינים. אבל, אפשר שכמו שדן בדין זה, כן מכוון לדון בשאר הדינים, ואז אולי לא נכון ש"נפישי." ותחשב.
קה.
לא מפרש איך השאר נלמדו. אולי נלמדו ממקור ראשון, או אולי נלמדו מבכור, שדומים לו במתן דם. גם אפשר שנתרבו מלשון רבים של “ובשרם,” שאולי כולל מעשר ופסח. (ע’ בגמ’ (לז), שמשמע כצד אחרון שכתבנו.)
* Footnotes
[fn:1] וא"ת הרי רק מכשיר שחיטת עולה, ולא שחיטת שאר קדשי קדשים. כמו שנראה בכ"מ, לפעמים מניח גמ’ דין אחד לכל קדשי קדשים, או דין אחד לכל קדשים קלים. לא כל כך פשוט לי למה עושה כן; כנראה, כיון שכבר רואים שני כללים השווים בהרבה דינים, מניח שלענין כל דבר שאינו מפורש הם שווים. ותחשב.יש להעיר שלפעמים מצאנו שיש ג"ש שנלמד ממה שכתוב בשני קרבנות "קדשי קדשים." אפשר שהרבה דינים נלמדו מגזירה שווה כזה.
[fn:2] על חצי המזבח של עולות גם יכול להקריב שלמים. לכאו’, המקור לזה הוא קל וחומר מעולות (או קל וחומר ממקום שפסול לעולות). עיין שם בגמ’, שמוכרח שרבי יוסי בר"י דורש הקו"ח, שלכן דורש שחציו לשלמים וחציו לעולה, כיון שאל"ה היה לו לכתוב רק עולה. (אבל, אין הכרח שרבי יוסי לא דורש הקל וחומר, שיש לומר שמפרש למה הפסוק הוסיף מילה, ולא מפרש שבזה הפסוק מלמד דין. כיון שיש הו"א חזקה שלא לדרוש הקל וחומר – אף שלמעשה היינו דורשים אותו – לא קשה שהתורה יוסיף מילה, ואז לא דורשים ממנו. זה צריך להיות יותר חזק מ"טרח וכתב לה קרא,” שהרי כאן יש מה לדרוש, כמו שאומר רבי יוסי ברבי יהודה, ועדיין לא דורשים ממנו. ותחשב.) יש להעיר שכמו שנראה, חולקים תנאים אם דורשים קל וחומר כזה. אבל, עיין שם בהערות, שבע"ה נבאר שלא פשוט אם באמת חולקים אם יכולים לדרוש קל וחומר זה, שאולי כוע"מ שיכולים, ורק חולקים שם אם דורשים. (גם עיין שם, שאולי אף אם חולקים שם, לא יחלקו כאן, שאולי הצד לדחות הקו"ח שם הוא לומר שלכל אחד יש חלק לעצמו. אבל, אחרי שכבר דרשנו כשרות שלמים בצפון, אולי מוכרח שלא לדרוש כן.)נמצא, אז, שהפסוק אומר שחציו מותר לשלמים ואומר שחציו מותר לעולה, ובאמירתו שחציו מותר לעולה, נמצא שגם מותר לשלמים. אז, סוף סוף, מה שאומר ששוחטים עליו את השלמים ומה שאומר ששוחטים עליו את העולה לא שווה, ששוחטים את השלמים על יותר, שכולו כשר לקדשים קלים. אבל, בא ללמד דבר שווה, שהוא כשרות חצי המזבח. ותחשב.
[fn:3] וא"ת הרי פשוט שהוא כשר, שהרי הוא עומד בצפון, וזה מקום כשרות שלו. אפשר לבאר כמו שנבאר בע”ה, שהיה נפסל כיון שכתיב, “על ירך.” אבל, רבי יחנן אומר שלא צריך כן, אלא מקבל שלפי רבי יוסי בר"י, אילו היה שחט אותו שם בקרקע (ונמצא אם מיעוט מקום המזבח), היה פסול. מרש"י יוצא שהוא מפני שהמזבח לא היה ממוצע, אלא היה נוטה לדרום. אז, חצי המזבח הצפוני לא היה עומד כולו בצפון, אלא מקצת ממנו היה עומד בדרום.אבל, אינו מוכרח כן מן הגמ’, שיש לומר שרק "על ירך" המזבח כשר, ולא במקום המזבח. עיין שם בגמ’, ששקלא וטריא של הגמ’ הוא כן: המשנה מביא את המחלקת בין רבי יוסי לרבי יבר"י. רבי יוחנן אומר שלרבי יוסי כל המזבח עומד בצפון. מקשה גמ’ שאם כן גם נאמר שלפי רבי יוסי בר"י המזבח עומד באמצע. מקשה ממש"א רבי יוחנן שאם שחט שם בקרקע, השחיטה פסולה. יש לדון אם הקושיה מוכיחה שאין המזבח באמצע – כמו שפירש רש"י – או שאולי מקשה שאי אפשר שזה פירוש של שיטת רבי יוסי, ומה שהמזבח עומד בצפון לא יכשיר את השחיטה. ותחשב.
[fn:4] וא"ת למה צריכים פסוק להכשיר אותו, שהרי עומד במקום כשרות שלו. ויש לומר שהו"א שצריך לשחוט על הארץ, ולא יכול לשחוט על המזבח. אם כן, נמצא שאחרי שרק מכשיר את המזבח, אם תלה אותו ושחט, לא יהיה שחיטתו כשרה. באמת, כן אומר גמ’ לעיל (כו.), ודורש אותו ממש"כ, “על ירך.”
[fn:5] יש להעיר שאף שעיקר דין לכתחילה של צפון כתיב בהם, לא פשוט שדין עיכוב של צפון נכתב בהם, שצד אחד של הגמ’ אומר שבאמת נלמד מחטאת. אבל, כיון שנלמד ב"לא יהא טפל חמור מן העיקר,” פשוט שעדיין עולה נחשב יותר עיקרי, ויתחיל מעולה. יש לדון, שזה מניח שמה שיתחיל מן הנכתב בפירוש הוא שנחשב יותר עיקר; יש לדון, שאולי הוא מפני שהוא "נודע" ראשון בדרך דרשות. נראה שעולה יקדים כיון שאם רק נדע עולה, עכ"פ נדע דין לכתחילה, אבל אם רק נדע דין חטאת, לא נדע כלום, שבלי דין לכתחילה, אין דין בדיעבד, וצריך עולה כדי ללמד דין לכתחילה. ותחשב.
[fn:6] מעניין שגמ’ רוצה לתלות בדין שחיטה בצפון. אולי הוא מפני שהוא דין ראשון, ואולי הוא דין העיקרי של המשנה, שבזה בעיקר בא לדון, והשאר בא אגבו. יש לדון למה יהיה כן. ותחשב.
[fn:7] יש להעיר שאין זה כל כך "דרשה,” שהפסוק אומר שהוא כעין של עולה. אילו, למשל, היינו אומרים שענין "מילתא דאתיא מדרשה חביבא ליה" הוא שחביב כיון שמראה כוח חכמים, שסומכים על ביאורם בפסוק, לדרוש דינים, לא קל לומר כן כאן, שלא צריכים שום כוח כדי לדרוש כן, שהדרשה כתובה בפירוש, שכ’ ששוחטים את החטאת במקום ששוחטים את החטאת. ותחשב.
[fn:8] לכאו’, הצד להתחיל בהם הוא שהם יותר מצויים. גם אפשר שהוא מפני שהלימוד מעולה כתיב בהם.
[fn:9] קצת קשה למה לא אומר שהוא מפני שנלמדים מחטאות חיצוניות ומעדיף מה שלמד מדרשה. נראה שהוא מפני שיש חטאות חיצוניות שגם נלמדים ממקום שכ’, “במקום אשר ישחט,” כמו של יה"כ. אז, אין סיבה להעדיף של יה"כ. וא"ת אם כן נדחה טעם שני שכתבנו. יש לומר שמקצתם כתוב בהם בפירוש, ומקצתם נלמד ממנו, ואז יש נלמד מדרשה ויש גם כתוב בפירוש, וזה הכי טוב. צריך לעיין בפסוקים, לראות אם זה נכון, שכל הדרשות הם צריכות ביאור. ותחשב.
[fn:10] כן מקשה הגמ’. אבל, איני רואה שיש מקור גדול מכאן, שאף  ששי יותר דם בפר מבשעיר, לא מערב כל דם הפרה בכל דם השעיר,  אלא מערב דם שבמזרק בדם שבמזרק. אז, איני רואה למה אין אומרים שבשניהם יש דם שווה, שבשניהם היה מזרק מלא, ובשניהם נתן מנין שווה של מתנות. אפשר לומר שבוודאי אחד יותר גדול, שאי אפשר לצמצם (ויש לדון אם נאמר רוב בציור שהם כל כך דומים; קשה לצייר שנאמר שאחד בטל, ולא נדע איזה הוא הרוב לומר שהוא מבטל את השני.); אבל, גמ’ לא אומר כן, אלא אומר שבוודאי של פרה יותר גדול, שלפרה יש יותר דם. ותחשב.
