1. פרק איזהו מקומן:
ידוע שאומרים שפרק איזהו מקומן הוא פרק שאין בו מחלקת. יותר מזה, יש ראשונים שכתבו שכולו הלכה למשה מסיני[fn:1]. (על פי זה, בארו למה נאמר בו שקדשי קדשים נאכלים "לפנים מן הקלעים." הרי, היו קלעים רק במשכן, ולא בבית המקדש. מבארים שאומר לשון זה כיון שמשניות אלו היו קיימות מזמן המשכן. כיון שהיה ידוע שלפנים מן הקלעים כנגד העזרה, נשאר כן.)
יש להעיר שאף שאין בו מחלקת בפירוש, יש בו דברים שהם תלויים במחלקת, כמו זריקת דם של מעשר בהמה ופסח, וכמו סוף זמן אכילת קרבן פסח. צריך לומר שתנאים חלקו בלשון משניות אלו, ושלנו הוא של תנא מיוחד. (אבל, אז אפשר לומר גם בפרק שיש בו מחלקת שהיה עיקרו הל"מ, אלא שהיה בו מחלקת, ואז הכניסו לתוכו המחלקת, ולא רק הדפיסו ההל"מ של תנא אחד.)
כמו כן, העיר הגר"ק שיש בו גזירה מדרבנן, והוא מה שקדשי קדשים נאכלים עד חצות. באר שאחרי שגזרו, שינו את המשנה, כדי שהמשנה לא יאמר דין שלא נוגע עוד. (מעניין ששינו את מה שאמר, ולא רק הוסיפו בו דין, לומר שמדרבנן צריך לאכול אותו יותר מוקדם.)
1. מיני קרבנות:
קדשי קדשים:
מיני קדשי קדשים[fn:2]:
יש חמש מיני קדשי קדשים.
חטאת:
חטאת נכנס לכלל של קדשי קדשים כיון שכ' בו "קדשי קדשים."
עולה:
עולה נכנס לכלל של קדשי קדשים כיון שכל בשרם הולך לגבוה (רש"י נג:).
אשם:
אשם נכנס לכלל של קדשי קדשים כיון שכ' בו "קדשי קדשים."
שלמי ציבור:
שלמ"צ נכנס לכלל של קדשי קדשים כיון שהוקש לעולה, שכ', "על עולותיכם ועל זבחי שלמיכם." (נה.)[fn:3]
אימורי קדשים:
אימורי קדשים (בין קדשים קלים בין קדשי קדשים) נכנסים לכלל של קדשי קדשים כיון שהולכים לגבוה (רש"י נג:).
דיני קדשי קדשים:
בקדשי קדשים מצאנו חמש[fn:4] דינים מיוחדים:
** :
מעילה
לפני זריקה, מועלים בכל חלקי הקרבן של קדשי קדשים. אחרי הזריקה, מועלים רק במה שנקרב על המזבח. (לא מועלים באימורי קדשים קלים קודם זריקה, אף שהם קדשי קדשים.[fn:5])
מקום שחיטה וקבלה:
קדשי קדשים נשחטים בצפון העזרה, ודמן נתקבל שם. חולקים תנאים אם צריך להיות כנגד מקום המזבח, או שאף יכול להיות משם עד ההיכל, או שאף יכול להיות מפתח העזרה עד ההיכל, בצד צפון. גם חולקים אם יכול לשחוט על חצי הצפון של המזבח או על כולו. (כמובן, אין זה נוגע לאימורים.)
מי אוכל:
קדשי קדשנים הנאכלים נאכלים רק לזכרי כהונה. (כמובן, אין זה נוגע לאימורים.)
זמן אכילה:
קדשי קדשים הנאכלים נאכלים ליום ולילה. מדאו', נאכל עד בוקר, ומדרבנן נאכל רק עד חצות. (כמובן, אין זה נוגע לאימורים.)
מקום אכילה:
קדשי קדשים הנאכלים נאכלים רק בעזרה. יש שני נפק"מ לזה – אסור לאכול אותם חוץ משם, וכשיצאו חוץ משם, נפסלו. פסול זה של יוצא יכול לפסול בשר מלאכול, אימורים מלהיקרב, ודם מלהיזרק. (כמובן, אין דין ראשון נוגע לאימורים. אבל, דין שני נוגע להם.)
קדשים קלים:
מיני קדשים קלים:
יש ארבע מיני קדשים קלים. בכולם, אין מקור שהם קדשים קלים, אלא שהם קדשים שאין מקור שהם קדשי קדשים.
שלמים
בכור
מעשר
פסח
דיני קדשים קלים:
בקדשי קדשים מצאנו חמש דינים מיוחדים:
** :
מעילה
לפני זריקה, לא מועלים בקדשים קלים. אחרי הזריקה, מועלים רק במה שנקרב על המזבח  (שהוא קדשי קדשים).
מקום שחיטה וקבלה:
קדשים קלים נשחטים בכל מקום שבעזרה, חוץ מצדדי צדדים[fn:6] (מקום שאין פתח פתוח לשם) , ודמן נתקבל שם.
מי אוכל:
קדשים קלים נאכלים לכל ישראל. יש שני יוצאים מכלל זה – מורם משלמים ובכור. שנים אלו נאכלים רק לכהנים, ולבנותיהם, נשיהם, ועבדיהם.
זמן אכילה:
קדשים קלים נאכלים לשני ימים ולילה אחד. יש שלש יוצאים מן הכלל – שני מיני שלמים (תודה, ושלמי נזיר), שנאכלים כזמן קדשי קדשים, ופסח (שנאכל רק לילה אחד; חולקים תנאים אם מדאו' נאכל עד סוף הלילה או רק עד חצות. מדרבנן, בוודאי אינו נאכל אחרי חצות
מקום אכילה:
קדשים קלים נאכלים בירושלים. יש שני נפק"מ לזה – אסור לאכול אותם חוץ משם, וכשיצאו חוץ משם, נפסלו. פסול זה של יוצא יכול לפסול בשר מלאכול, אימורים מלהיקרב, ודם מלהיזרק.
1. מזבח:
** חמשה
יש
חלקי מזבח[fn:7]:
1. גוף המזבח – גוף המזבח הוא גבוה תשע אמות, ורחב עשרים ושמונה אמות.
2. יסוד – יסוד הוא מקום גבוה אמה ורחב אמה שסובב את גוף המזבח. חולקים לוי ורב כמה מן המזבח היה סובב. לפי לוי, היה סובב את כולו. לפי רב, היה סובב את כל צדדי מערב וצפון, ושתי אמות מצד מזרח, אצל הדרום, ושתי אמות מצד צפון, אצל המערב.[fn:8][fn:9][fn:10][fn:11]
3. סובב – סובב הוא מקום גבוה שש אמות ורחב אמה שסובב את גוף המזבח.
4. קרנות – קרנות הם מקומות שהם אמה על אמה על אמה על גג המזבח. יש ארבע קרנות, אחד בכל אחד מארבע הקרנות.
5. כבש – כבש הוא כבש ארוך ששה עשר אמה ורחב שלושים ושתים אמה שהוא בדרום המזבח.
נמצא שבאמה הראשונה שלו, המזבח היה שלושים ושתים על שלושים ושתים (אלא שחולקים אם היה מרובע ממש). מאמה השנית לאמה השישית, היה שלושים על שלושים. מאמה השביעית עד אמה התשיעית, היה עשרים ושמונה על עשרים ושמונה. באמה עשירית, היו רק ארבע קרנות של אמה על אמה, אחד על כל קרן של המזבח.
אבל, דורשים שלא כל אמות שוות, אלא יש שני מיני אמות: אמה בת ששה טפחים, ואמה בת חמשה טפחים. רוב האמות הם של ששה טפחים, חוץ משלשה יוצאים מן הכלל: גובה יסוד, כניסת סובב, וגובה רוחב ואורך קרנות. אז, כל גובה המזבח הוא חמישים ושמונה טפחים (שאמת היסוד ואמת הקרנות חסרה).[fn:12]
1. מקום מזבח:
מקום המזבח במזרח- מערב היה כנוס עשרים ושנים אמות משפה מזרחית של העזרה (יותר למערב ממקום הילוך רגלי ישראל (אחת עשרה אמה) ומקום הילוך רגלי כהנים (אחת עשרה אמה)), ומאה שלושים ושלש אמות משפה מערבית של העזרה  (יותר למזרח מאחורי בית הכפורת (אחת עשרה אמה), ההיכל והאולם (מאה אמה), ו  בין האולם למזבח (עשרים ושתים אמה)).
חולקים תנאים איך היה מקום המזבח בצפון-דרום של בית המקדש. מצאנו ארבע שיטות:
1. כל המזבח היה בצפון העזרה.[fn:13] מצאנו שתי שיטות שסוברות כן:
  1. רבי יוסי סובר כן. גמרא מביא ושלשה מקורות לזה, ושנים מהם דחויים:
    1. רבי יוסי אומר שקדשי קדשים שנשחטו בראש המזבח כשרים. הרי, צריך לשחוט קדשים קדשים בצפון; הכשרם בראש המזבח מוכיח שמזבח היה בצפון. דוחה גמ’ שידוע שמקום המזבח בקרקע לא כשר לשחיטה[fn:14], כיון שהוא מקום מזבח, ולא מקום עזרה. אז, צריך להיות מקור אחר להכשרו על המזבח, שאינו יכו"ל מפני שעומד בצפון. אכן, גמ’ אומר שלומד ההכשר ממש"כ, "וזבחת עליו את עולותיך." כיון שכן, אין הוכחה שעומד בצפון, ואז מקור זה דחויה.
    2. רבי יוחנן ידע מקבלה שרבי יוסי סובר שהמזבח עמד בצפון.
    3. [fn:15]משנה אומרת שמערכה שניה של קטרת (שצריך להיות כנגד פתח של ההיכל, ששם מקטיר קטורת) היתה במשוך ארבע אמות מן הקרן כלפי צפון[fn:16]. משנה זה שיטת רבי יוסי, שמזכיר עליו סימן בבריי’. גמרא מזכיר במשנה זה שני פשטים, ולפי פשט ראשון, יוצא מקור שרבי יוסי סובר שהמזבח היה כולו בצפון. :
      1. המזבח עומדת בצפון[fn:17]. פתח ההיכל היה רחב עשר אמות, והיה באמצע הצפון-דרום של העזרה. אז, חמש אמות שבמזבח היה כנגד פתחי היכל. לא היה יכול לשים את המערכה באמה ראשונה, שנית, או שלישית, שהמערכות היו על גג המזבח, ולא על היסוד, הסובב, או הקרנות[fn:18]. לא היה יכול לשים את המערכה באמה רביעית, שזה היה מקום הילוך הכוהנים (ולא יכולים ללכת על המערכה). אי אפשר לשים אותו מאמה שישית ולצפון, שאינו כנגד הפתח. אז, צריך למשוך אותו ארבע אמות מקרן דרומית מערבית[fn:19]. לפי זה, אומר שצריך לשים אותו משוך ארבע אמות – לא פחות ולא יותר – מן הקרן.[fn:20]
      2. המזבח עומד באמצע, חציו בצפון וחציו בדרום.[fn:21] פתח היכל היה רחב עשר אמות, אבל פתח אולם היה רחב עשרים אמות. קדושת ההיכל ואולם אחד, ואז המערכה יכולה להיות כנגד פתח אולם, ולא צ"ל כנגד פתח ההיכל. כשאומר שצריך למשוך ארבע אמות, לא כולל אמה יסוד ואמה סובב[fn:22]. אומר שצריך למשוך ארבע אמות, כיון שאחרי אותם ארבע אמות מתחיל פתח האולם (שהמזבח הוא רחב שלושים ושנים, והפתח הוא רחב עשרים, ונמצא שהמזבח עדיף עליו שש אמות לכל צד. אז, צריך למשוך שש אמות.) אז, צריך למשוך אותו שש אמות מקרן דרומית מערבית. לפי זה, אומר שצריך לשים אותו משוך שש אמות – לא פחות – מן הקרן; אבל, יכול לשים אותו יותר משש אמות מן הקרן, עד עשרים ושש אמות.[fn:23]
  2. רבי יוסי הגלילי סובר כן. המקור לזה הוא בריי’ שבו אומר ריה"ג שדורש שכיור היה בין המזבח לאהל מועד, אבל לא כנגד פתח ההיכל. דורש שצפון צ"ל פנוי מכלים, ואז צריך להיות בדרום. מסיק שאינו ממש בין המזבח לאהל מועד, אלא משוך מן המזבח, והוא בדרום, בין האהל מועד ומקום שהוא כנגד המזבח. אם המזבח היה עומד באמצע, היה יכול להיות בין האוה"מ ומזבח ממש (שיש אחד עשרה אמות (אם קדושת היכל אינו קדושת אולם) או שש אמות (אם קדושת היכל ואולם אחד)); ממה שאומר שהוא בין אוה"מ ומקום שהוא כנגד המזבח רואים שסובר שכל המזבח עומד בצפון.[fn:24]
2. המזבח היה עומד באמצע העזרה ממש. אז, חצי המזבח הוא בדרום, וחצי המזבח הוא בצפון. מצאנו שיטה אחת שסוברת כן:
  1. רבי יהודה סובר כן. הוא אומר כן בפירוש.
3. כל המזבח היה בדרום העזרה. מצאנו שיטה אחת שסוברת כן:
  1. רבי אליעזר בן יעקב סובר כן. הוא אומר כן בפירוש, שדורש שאין שום כלים – כולל מזבח – בצפון.
4. המזבח היה עומד באמצע עזרה, משוך לדרום, (רוב המזבח היה בדרום). שיטה זו יוצאת ממשנה בתמיד. שם, מבאר מה היה במאה שלושים וחמש אמה של צפון דרום של העזרה. המשנה מונה שבע דברים:
  1. הכבש היה שלושים אמה, בדרום העזרה[fn:25] - יש לנו שלושים אמה.
  2. המזבח היה שלושים ושנים אמה, צפון ממנו – יש לנו ששים ושנים אמה.
  3. בין המזבח לטבעות היה שמונה אמות, צפון ממנו – יש לנו שבעים אמה.
  4. מקום הטבעות היה עשרים וארבע אמות, צפון ממנו – יש לנו תשעים וארבע אמות.
  5. בין הטבעות לשולחנות היה ארבע אמות, צפון ממנו – יש לנו תשעים ושמונה אמות.
  6. בין השולחנות לננסים היה ארבע אמות, צפון ממנו – יש לנו מאה ושנים אמות.
  7. בין הננסים לכותל עזרה היה שמונה אמות, צפון ממנו – יש לנו מאה ועשר אמות.
יש עוד עשרים וחמש אמות שלא מבואר במשנה, וגם יש שלש מקומות שלא מבוארות במשנה – מקום שולחנות, מקום ננסים, ובין הכבש לכותל עזרה. רש"י מבאר בזה שלש מהלכים:
  1. מקום שולחנות היה ארבע אמות. חצי המקום הנשאר (עשר אמות וחצי) היה מקום ננסים, וחצי מקום הנשאר (עשר אמות וחצי) היה בין הכבש למזבח. אז, מזבח היה בין ארבעים וחצי אמה מן הדרום לשבעים ושנים וחצי אמה מן הדרום, ונכנס חמש וחצי אמות לצפון.
  2. מקום השולחנות וננסים היה כמו חצי המקום הנשאר (שלשה עשרה אמות), ובין כבש לכותל היה כמו חצי מקום הנשאר (שנים עשרה אמה).[fn:26] אז, מזבח היה בין ארבעים ושנים אמה מן הדרום לשבעים וארבע אמה מן הדרום, ונכנס שבע אמות לצפון.
  3. רש"י מצדד שבין כבש לכותל יש חמש וחצי אמה, והשאר (תשע עשרה וחצי אמה) נחלק בין ננסים לשולחנות (ולא מפרש איך נחלק). לפי זה, משנה לא סוברת שרובו בדרום, אלא שכולו בדרום, וזה כשיטת רבי אליעזר בן יעקב.
* Footnotes
[fn:1] לכאו', לא ממש רצה לומר שכולו הלכה למשה מסיני, שרובו נלמד מדרשה, כמו שנבאר. יש להעיר שיש דיון גדול בראשונים ואחרונים בענין הדרשות, שיש כתבו שדינים הנלמדים מדרשות נלמדו למשה בסיני, ולא רק נאמר לו האופן לדרוש אותם, והם גם כן הלכות למשה מסיני, אלא שהם גם בתוך התורה. (וא"ת א"כ לפי דברי הרמב"ם שאין מחלקת בהל"מ, לא יכול להיות מחלקת בשום דבר הנלמד מדרשה. יש להעיר שבי"כ ובי"כ יש המון קושיות על הרמב"ם. אבל, קושיה זו לא כ"כ קשה, שהרמב"ם רק מדבר במה שאין לו מקור חוץ מהל"מ. ותחשב.) לפי זה, אפשר שהפרק נאמר בהלכה למשה מסיני. אף לשיטה אחרת, יש לומר שמקצת דרשות נאמרו גם למשה בסיני. יש להעיר שגמ' כאן לא רק אומר מקור, אלא לפעמים מחפש מקור. צריך לומר שגמ' ידע – אף שכבר ידע שיש הל"מ על זה – שזה נלמד מדרשות. (אם נאמר שכל דרשה נאמר למשה בסיני, זה יהיה קשה על הרבה גמרות.) צריך לומר שהיה לגמ' מסורה – אולי זה היה חלק מהל"מ – שיש עליו דרשה. ותחשב.
[fn:2] נראה שיש קרק' של "קדשי קדשים," ואינו רק שם שנאמר עליו כדי לומר שיש בו כל דינים אלו. כן משמע מדרשת הגמרא שבו מלמד שזבחי שלמי ציבור קדשי קדשים, וכן נראה ממה שהתורה אומר בחטאת ואשם שהם קדשי קדשים (ומדרשות הגמ' מבואר שאינו אומר בו הדינים כשאומר כן). ותחשב.
[fn:3] אבל, עיין שם, שיש דינים של קדשי קדשים שלומד מהיקש לחטאת. צריך ביאור למה לא נלמד ממה שהוא קדשי קדשים. כנראה, כיון שנלמד מעולה, ויש דיני קדשי קדשים שלא נוהגים בעולה, כיון שלא נאכל, אף שיודעים שהוא קדשי קדשים, צריך מקור אחר לדינים אלו.
[fn:4] עיין ברש"י (נג:), שמזכיר שלעולה יש דין קדשי קדשים, לענין להיפסל בטב"י ובמחוסר כפורים. אבל, תוס' שם מעורר שאין דין מיוחד בקדשי קדשים לענין טב"י ומחס"כ. צריך ביאור מהו כוונת רש"י.
[fn:5] נראה שזה מפני שלא נחשבים אימורים, שלא עומדים להיות נקרב על מזבח כל כך, עד אחרי הזריקה. באמת, היה יותר טוב לכלול את זה לומר שקדשי קדשים יש בהם מעילה, חוץ מבשר אחרי זריקה, וקדשים קלים אין בהם מעילה.
[fn:6] גמ' מרבה כל מקום, ואפילו צדדים, אבל לא צדי צדדים. לא כל כך פשוט לי מהו צדי צדדים, אבל נראה שהוא כשיש קרן זוית בינו לבין פתח, שאז אינו "פתח אוהל מועד."
[fn:7] נתתי את השמות כאילו יש מזבח באמצע, והוא כל הגובה, וסביב לו יש סובב ויסוד. היה אפשר לי לבאר אותו כאילו יש מקום רחב למטה, שהוא היסוד, ומקום למעלה ממנו, שהוא הסובב, ומקום על זה, שהוא שאר המזבח. אין, באמת, חילוק, שנראה שכפי האמת כולו אחד, ואינם חלקים שונים. ותחשב.
[fn:8] זה כולל המקום שהיסוד הוא בקרן, במזרח ובצפון, או במערב ובדרום. המקום שהיה הקרן רק בצד מזרח היה אמה, והמקום שהיה הקרן רק בצד דרום היה אמה.
[fn:9] אף שלוי סובר שהיה יסוד סביב כל המזבח, מודה קצת לשיטת רב. דורשים שדמים צריכים להינתן על מזבח במקום שלמטה ממנו יש יסוד. מודה לוי שלזה רק כשר מקום שרב אומר שהיה יסוד.
[fn:10] גמרא מבאר שהטעם לזה הוא שאותו מקום שהיה לה יסוד כשר היה שייך לבנימין, ומקום שלא היה לה יסוד (או היה לה יסוד לא כשר) היה שייך ליהודה. כיון שבנימין דאג שיהיה ביה"מ בחלק שלו, רק מה שהוא בחלקו כשר לזריקת דמים. טעם זה רק אפשר למד"א שירושלים נחלקה לשבטים. למי שסובר שלא נחלקה לשבטים, לא ניתן טעם לדין זה.
[fn:11] יש להוסיף שרש"י כ' שהיה בליטה קטנה בקרן מזרחית דרומית. לקבל דם של עולת העוף שיורד מן המזבח. יש לדון אם זה נכון גם לפי המד"א שהיה שם יסוד, אלא שלא היה מקודש.
[fn:12] איני יודע אם רוחב המזבח הוא שלושים ושנים, אלא שגוף המזבח, אז, רחב עשרים ושמונה ושני טפחים, או שרוחב המזבח הוא שלושים ושנים חסר שני טפחים. גמ’ בהו"א מניח כעין צד ראשון (אלא שאח”כ שם מצדד כעין צד שני). אבל, מה שאומר שגובה המזבח הוא רק חמישים ושמונה טפחים יתאים יותר אם נאמר כצד שני, שלא נדונים סכום הכולל באמה בת ששה טפחים. ותחשב.
[fn:13] לכאו’, לא ידוע איפה נמצא בתוך צפון העזרה; רק יודעים שכולו היה בצפון העזרה. אבל, למקצת המקורות ייצא הכרח איפה עמד, כמו שנראה בס"ד.
[fn:14] עיין שם, שרק אומר שם בשיטה שחולקת על רבי יוסי, ומשם מוכיח שיש אפשרות לדרוש. נראה שמה שלא אמר כן ברבי יוסי הוא שידע שרבי יוסי לא סבר כן. ותחשב. אז, יוצא שרבי יוסי מכשיר כיון שהוא בצפון. אבל, אז קשה למה צריך דרשה (כמו שמביא גמ’). לכאו’, צ"ל שדרשה זו מגידה לנו מקום המזבח או שדרשה זו מגידה לנו שכנגדו בקרקע כשר. ותחשב.
[fn:15] עיין בגמ’, שלא אומר את זה למקור בפני עצמו, אלא אומר אותו למקום שמוצאים בריי’ שמזכיר קבלת רבי יוחנן.
[fn:16] לא פשוט לי אם הבריי’ מכוון לומר שגם ימשוך למזרח, או רק לצפון. עיין בלשון הבריי’, שרק מזכיר המשכה לצד צפון; אבל, מזכיר המשכה מן הקרן, ולא מן השפה. בוודאי, לא היה כנגד הקרן, שבצד הקרן לא היה אמה מהלך כהנים (שאם היה, היה כנגד כל הצד, ואף משיכה ארבע אמות לא יציל). אז, מה שמזכיר המשכה מן הקרן משמע שגם משך למזרח. ותחשב. עיין לקמן, בע"ה, שנבאר את זה לפי הצדדים בביאור הבריי’.
[fn:17] גמרא אומר את זה בשני צדדים. בצד ראשון אומר שהוא כשיטת רבי יוסי. בצד שני, אומר שהוא שיטת רבי יוסי הגלילי, ומוציא בריי’ שבו רבי יוסי הגלילי סובר שכל המזבח היה בצפון. לכאו’, עדיין עומד הוכחת הגמ’ שמשנה זה כשיטת רבי יוסי; צריך לומר שסובר שאינו ראוי לחדש על פי זה חידוש גדול – שיטת רבי יוסי – כיון שיש דרך אחר לפרש המשנה. יל"ד, שאין זה חידוש גדול שרבי יוסי יסבור כזה. ותחשב.
[fn:18] וא"ת ישים את המערכה כנגד הקרן בצד מערב, אמה אחת משוך מן הדרום. אפשר לדחות שלא רוצה לשים מערכה במקום קרנות – רצה לומר, בכל צד של הקרנות.
[fn:19] יש להעיר שלא היה יסוד בכל צד מערבית. אז, יוצא שכשנכנס ארבע אמות למזרח, כולל מקום יסוד אף שלפי רב לא היה שם יסוד. אבל, כמו שנראה, אולי המשיכה רק מדובר במשיכה לצפון.
[fn:20] יש להעיר שלכאו’ זה רק לענין צפון, אבל יכול לשים אותו יותר רחוק למזרח. אבל, נראה שכיון שצריך להיות קרוב להיכל, לא יכול למשוך אותו לצד מזרח, שזה מרחיק אותו מן ההיכל.
[fn:21] לפי צד זה, אומר גמרא שהבריי’ הוא שיטת רבי יהודה. לכאו’, אותו ראיה שהיה רבי יוסי עוד קיים. אלא, כיון שבוודאי רבי יוסי סובר שכל המזבח בצפון – שנשאר לסוף מקור מקבלת רבי יוחנן – מוכרח שאין זה רבי יוסי, אף שאומר עליו סימן. (עיין בגמ’ שמקשה למה לא נוקים אותו להיות כרבי יוסי, ומשיב שהוא מפני שמצאנו שרבי יהודה סובר שהמזבח היה ממוצע. לכאו’, צ"ל  שגמ’ לא דק, ולא ר"ל שלא מצאנו שרבי יוסי סובר שמזבח ממוצע, אלא שמצאנו שרבי יוסי לא אומר שמזבח ממוצע. יש לדון, שאפשר שגמ’ סובר ששאר אמוראים לא משעובדים לקבלת רבי יוחנן, ואם יש להם סיבה לחשוב שאינו נכון, יחלקו עליו. ותחשב.)יש להעיר שאולי רבי יהודה גם הולך לשיטתו במה שאומר שקדושת אולם והיכל קדושה אחת (שכן צריכים להניח לפי צד זה, כמו שנראה בע"ה), שמצדד גמרא בתחילת עירובין שכן סובר רבי יהודה.
[fn:22] איני יודע אם זה מפני שרק מונה מה שיש בו גג, או מפני שמונה מן הקרן (כמו שמשמע מלשון הבריי’).
[fn:23] יש להעיר שלפי זה, רק מושך ארבע אמות לדרום, אבל למזרח לכאו’ מושך שתי אמות (כנגד הקרן וכנגד מקום הילוך הכהנים. שהוא כנגד הפתח. (עיין לעיל, שדנינו אם המשנה מזכיר משיכה למזרח. לצד זה, מוכרח שלא מזכיר. אבל, צ"ב למה לא יזכיר, שצריך למשוך שתי אמות. נראה שאולי לפי צד זה, יכול לשים את המערכה על צד הקרנות, ואז לא צריך למשוך שום דבר, ולכן לא הזכיר אותו. זה יבאר למה הוציא מחשבון ארבע האמות יסוד וסובב, שאינם כל כך ראויים, ולא הוציא קרן ומקום הילוך כהנים.)
[fn:24] יש להעיר שעדיין אפשר שמקצתו בדרום, אלא שאותו מקצת צריכה להיות פחותה מעשר אמות. כנראה, מניח שאם אינו באמצע ממש, צריך להיות כולו בדרום או כולו בצפון.
[fn:25] באמת, היה שלושים ושנים, אבל שתי אמות שלו היו עודפים על המזבח, ואז לא מנינו אותם.
[fn:26] לכאו’, זהו הסיבה לחלק ככה. נותנים חלק הגדול למקום שולחנות וננסים, כיון שהוא שני דברים. אבל, עיין ברש"י, שמקשה עליו למה לחלק כך.
