מיני קרבנות:
קדשי קדשים:
מיני קדשי קדשים:
יש חמש מיני קדשי קדשים.
חטאת:
חטאת נכנס לכלל של קדשי קדשים כיון שכ' בו "קדשי קדשים."
עולה:
עולה נכנס לכלל של קדשי קדשים כיון שכל בשרם הולך לגבוה (רש"י נג:).
אשם:
אשם נכנס לכלל של קדשי קדשים כיון שכ' בו "קדשי קדשים."
שלמי ציבור:
שלמ"צ נכנס לכלל של קדשי קדשים כיון שהוקש לעולה, שכ', "על עולותיכם ועל זבחי שלמיכם." (נה.)[fn:1]
אימורי קדשים קלים:
אימורי קדשים קלים נכנסים לכלל של קדשי קדשים כיון שהולכים לגבוה (רש"י נג:).
דיני קדשי קדשים:
בקדשי קדשים מצאנו חמש[fn:2] דינים מיוחדים:
** :
מעילה
לפני זריקה, מועלים בכל חלקי הקרבן של קדשי קדשים. אחרי הזריקה, מועלים רק במה שנקרב על המזבח.
מקום שחיטה וקבלה:
קדשי קדשים נשחטים בצפון העזרה, ודמן נתקבל שם. חולקים תנאים אם צריך להיות כנגד מקום המזבח, או שאף יכול להיות משם עד ההיכל, או שאף יכול להיות מפתח העזרה עד ההיכל, בצד צפון. גם חולקים אם יכול לשחוט על חצי הצפון של המזבח או על כולו.
מי אוכל:
קדשי קדשנים הנאכלים נאכלים רק לזכרי כהונה.
זמן אכילה:
קדשי קדשים הנאכלים נאכלים ליום ולילה. מדאו', נאכל עד בוקר, ומדרבנן נאכל רק עד חצות.
מקום אכילה:
קדשי קדשים הנאכלים נאכלים רק בעזרה. יש שני נפק"מ לזה – אסור לאכול אותם חוץ משם, וכשיצאו חוץ משם, נפסלו. פסול זה של יוצא יכול לפסול בשר מלאכול, אימורים מלהיקרב, ודם מלהיזרק.
קדשים קלים:
מיני קדשים קלים:
יש ארבע מיני קדשים קלים. בכולם, אין מקור שהם קדשים קלים, אלא שהם קדשים שאין מקור שהם קדשי קדשים.
שלמים:
בכור:
מעשר:
פסח:
דיני קדשים קלים:
בקדשי קדשים מצאנו חמש דינים מיוחדים:
** :
מעילה
לפני זריקה, לא מועלים בקדשים קלים. אחרי הזריקה, מועלים רק במה שנקרב על המזבח.
מקום שחיטה וקבלה:
קדשים קלים נשחטים בכל מקום שבעזרה, חוץ מצדדי צדדים[fn:3] (כמו אחורי ההיכל ובתוך ההיכל) , ודמן נתקבל שם.
מי אוכל:
קדשים קלים נאכלים לכל ישראל. יש שני יוצאים מכלל זה – מורם משלמים ובכור. שנים אלו נאכלים רק לכהנים, ולבנותיהם, נשיהם, ועבדיהם.
זמן אכילה:
קדשים קלים נאכלים לשני ימים ולילה אחד. יש שלש יוצאים מן הכלל – שני מיני שלמים (תודה, ושלמי נזיר), שנאכלים כזמן קדשי קדשים, ופסח (שנאכל רק לילה אחד; חולקים תנאים אם מדאו' נאכל עד סוף הלילה או רק עד חצות. מדרבנן, בוודאי אינו נאכל אחרי חצות
מקום אכילה:
קדשים קלים נאכלים בירושלים. יש שני נפק"מ לזה – אסור לאכול אותם חוץ משם, וכשיצאו חוץ משם, נפסלו. פסול זה של יוצא יכול לפסול בשר מלאכול, אימורים מלהיקרב, ודם מלהיזרק.
* Footnotes
[fn:1] אבל, עיין שם, שיש דינים של קדשי קדשים שלומד מהיקש לחטאת. צריך ביאור למה לא נלמד ממה שהוא קדשי קדשים. כנראה, כיון שנלמד מעולה, ויש דיני קדשי קדשים שלא נוהגים בעולה, כיון שלא נאכל, אף שיודעים שהוא קדשי קדשים, צריך מקור אחר לדינים אלו.
[fn:2] עיין ברש"י (נג:), שמזכיר שלעולה יש דין קדשי קדשים, לענין להיפסל בטב"י ובמחוסר כפורים. אבל, תוס' שם מעורר שאין דין מיוחד בקדשי קדשים לענין טב"י ומחס"כ. צריך ביאור מהו כוונת רש"י.
[fn:3] גמ' מרבה כל מקום, ואפילו צדדים, אבל לא צדי צדדים. לא כל כך פשוט לי מהו צדי צדדים, אבל נראה שהוא כשיש קרן זוית בינו לבין פתח, שאז אינו "פתח אוהל מועד."
