* יט:
** איסורא מממונא -
יש לדון מה נחשב ממון:
1. אולי יש נפקא מינא של דין ממון (שלא צריך להז'). לכן, נחשב ממון. יש להעיר שיש גם נפקא מינא באם צריך להחזיר. (אין זה יוצא מזה, אלא יש נפקא מינא באיסור, שהוא נפקא מינא בענין מה לעשות עם ממון.)
2. אולי מלמד דין ממוני. זה אומר שאולי מה שאין איסור כאן הוא שנדחה זכות הבעל, ולא שנדחה האיסור. א"א ללמוד מזה לאיסור. ותחשב.
* יט:
** המוצא כלאים -
קצת צריך ביאור למה מביא זה כאן. אולי הוא מפני שדן בקובר מת מצווה לקמן. רצה לומר, רק מביא אותו לראיה לזה, והרי משנה שלנו דן בקבורת מת. ותחשב.
* כ.
** תנויי -
לכאו', זה רק מוכיח שאנו יודעים יותר, ולא שלומדים יותר. אולי בשני דר' למדו רק נזיקים, או כדומה, ואז אנו למדנו מהם, ויודעים במהירות מה שהוצרכו ללמוד לאט. אז, יכולים ללמוד טהרות.
** רב גידל -
צריך ביאור למה מביא את זה כאן.
** לקראת מלכי -
קשה, שזה כבוד מלך, ולא כבוד הבריות. אולי קל וחומר הוא. לא משמע כן מרש"י. עוד שק"ק, שכבוד חברים הוא, לכאו', בכבוד שיותר נצרך. נראה שאולי למלך, כבוד הבריות הוא טוען אותו כבוד מלך. דחוק, שמסתמא אף לא ירגיש שכהנים באים. ותחשב.
ואם תאמר איזה כבוד יש בגויים. ויש לומר שאין הכי נמי, ולא מביא מהם ראיה. גם יש לומר שמחמת זה יכיר יותר בגדלות מלאכים אחרים, כמו שאומר גמרא, ויכבד אותם יותר. (יש להעיר שאז הוא רק הכשר מצווה של כבוד הבריות.)
** קצת קשה
איך נאמר שנדחה לאו, שרק צריך לשמוע לרבנן, ורק לא אמרו רבנן כאן. וצריך ביאור.  אולי זהו כוונת רש"י (עיין בלשון שלו), שאולי אומר שר"ל שאין איסור דרבנן, ומז' לאו כיון שהלאו הוא המלמד לנו שצריך לשמוע לרבנן. ותחשב.
** גדול -
אם רק לא תק' שם, לשון גמרא שמשמע שזה מראה גדלות קצ"ב. ותחשב.
** רש"י שוב -
לא כה"ב -
יש לדון מהיכי תיתי שזה הותרה ושזה נדחה. ותחשב. גם יש לדון מהו ס"א של איסור טומאת כהן שיעשה שהותרה כאן. ותחשב.
** הויות -
יש לדון אם רצה לומר שמשניות אלו קשים כמו שהיו הקושיות קשים או שיש להקשות עליו קושיות גדולות כמו שהקשו אז. ותחשב.
** תפילין -
לילה ושבת -
לא צריך שניהם. ותו"ת.
* כ:
** ואית ביה מלכות שמים –
יש לדון מה אומר:
1. אולי הו"א שמעשהז"ג דחויה (שק' ביותר). זה כ"כ טוב ונצרך שעדיין יהיו חייבים.
2. אולי הו"א שמעשהז"ג הותרה (אין הסיבה שייך לנשים). יודעים סיבתה, ומסתמא שייך לנשים.
3. אולי הו"א שהוא פרט במצוות קבלת מלכות שמים, וכיון שאותו מצווה חייבת בה, חייבת אף בזה. צריך ביאור מה זה אומר. אולי רצה לומר שמהנה לאותו מצווה, והרי היא בכלל אותו מצווה. גם יש לומר שזה יהיה סימן שהיא בכלל אותה סיבה. ותחשב.
** תפילין פשיטא -
יש לדון, שאולי הו"א שאין זמנו גרמא, וחייבים בלילה ובשבת.
** ערב ובקר -
לכאו', קשה מה לנו בזה, שהוא חיוב דרבנן, וקרא זה לא קאי על החיוב. יש לומר שקרא מפרש הסיבה והטוב, אף שלא מזכיר חיוב. כיון שתלוי הסיבה בזמן, אולי לא חייבו רבנן נשים, שלהם אולי אין הסיבה כל כך נוגעת. זה רק מהני אם נשים במ"ע שהז"ג הותרו ולא נדחו. קשה בדר"כ למה נחלק בין דרבנן לכאו'. אולי כיון שכתיב, סמכו על קרא, ורצו לתקן כאילו היה באותו קרא. ותחשב מה זה אומר.
** פשיטא -
יש לדון למה כל כך פשוט שבה"מ נח' מ"ע שאין הזמן גרמא, שלא נוהג על יוה"כ. צריך לומר שהוא מפני שאין זה זמן, אלא מפני שלא אוכלים אז. גם יש לומר שהוא מפני שנוהג למי שאוכל מחמת פק"נ. גם נוהג אם אכל לפני התענית, ושכח לברך. יש לדון, שלא נוהג אחרי שעת עיכול.
** קצת יש לדון מה
נחשב זמן לענין זמן גרמא, שהוא זמן בשבוע (כמו שבת), והוא זמן ביום (כמו תפילין), והוא זמן בשנה (כמו סוכה). ותחשב.
** והא דב"ת -
נראה שאביי סבר שבריי' ר"ל שחייבות כיון שאנשים חי' מדבר תורה, ולכן תק' רבנן עליו. גם יש לומר שר"ל מדבר תורה של "לא תסור.” יש לדון למה מזכיר אותו כלל. ויש לומר שמז' אותו להראות שדינים של רבנן הם דינים דאו'. ותחשב.
** נחייב -
וא"ת מהי"ת שלא חייבים. יש לומר שמשנה אומר שפטורות. לכאו', דחוק לומר שר"ל שפ' מדאו', ובפרט כיון שאף דן בתפילה, שכל חיובו מדרבנן, וצריך לומר ששם ח' ופ' ר"ל מדרבנן. גי"ל שמדייק ממה שלא מצאנו משנה אחד שיאמר כן. ותחשב. גם יש לומר שמדייק ממה שמשנה זה אומר כן על קידוש בלחוד. ותחשב.
** כל שישנו -
וא"ת נדרוש להיפך. ויש לומר שמקישים לחומרא. ויש לדון אם כל כך פשוט שזה חומרא, שמתירים לו לומר שם של ה'. ויש לומר שזה הותרה, ולא דחויה, שהרי לצורך הוא. יש לדון אם זה יהני שייקרא קולא, ולא חומרא. ותחשב. ודע שכ"ז על הצד שברכה לבטלה היא אסור מדאו'. גם יש לומר שבוודאי אינה ברכה לבטלה, שבוודאי יש בו קיום. ותחשב.
** זכור ושמור -
לא מפרש אותו כאן, אבל נלמד ממה שהוציא אותם בדיבור אחד.
** זכור -
זה  נמצא שני מקומות בש"ס – ברכות (כ:) ושבועות (כ:). זה מעניין, שהם באותו דף ועמוד.
** למאי נפקא מינא -
גם יש נפקא מינא בדין ספק ברכה.
** לאפוקי רבים -
רצה לומר, אנשים.
** כדאשכחן -
אז, צריך ביאור למה הרהור מותר. אולי איסור זה הוא רק בלימוד תורה, ואינו נקרא לימוד אם לא מוציא מפיו. ותחשב. דחוק, שלא רק אומר שיכול לקיים מצוותו בהרהור, אלא שהרהור כדיבור, שמשמע , לכאו', שיהיה כמותו לכל דבר, ואף לדינים אחרים. גם יש לומר שת' גמ' הוא שרק דומה להר סיני כשמדבר. יש לדון למה. ותחשב.
** הרהור כדיבור -
אם כן, קשה למה לא יהרהר בדרבנן. אפשר שרבנן לא חייבו אותו להרהר, שהוא טורח לו. וא,ת הרי חייבו לו לדבר. ויש לומר שיותר קל לדבר מלהרהר. נראה שצריך יותר כוונה להרהר מלדבר. ותחשב.
** והוא יושב -
קצת מעניין שצריך זה, שלכאו' לא מכירים בני אדם על מה הוא חושב. אז, א"א שצריך זה לאחרים. ותחשב, אז, למה צריך זה.
** צריך ביאור למה
תק"ע היה רק על מדבר. יש לומר שצריך קיום ת"ת, ורק מקיי' ת"צ בזה. גם יש לומר שצ"ל דומה לקבלת תורה, ושם (אולי) היו עוסקים בו כעין בדיבור.
* כא.
** היה עומד -
קשה, שאולי רק ר"ל שלא יתחיל בדיבור, אלא בכוונה.
** תפילה -
קצת קשה למה לא יתרץ שאינו לומד. אולי נחשב לימוד, שיודע יותר טוב מה להתפלל. ותחשב. אם נאמר שכל אמירת דבר שבקדושה אסור, גם כן יכולים לתרץ, אלא שקצת צריך ביאור למה יהיה כן. ותחשב.
** והרי תפילה -
ראיתי ק' תוס'. יש לומר שבברכת קריאת שמע, נח' עסוקים בק"ש, שהם לצורך קריאת שמע (או מחמת קריאת שמע, שאפשר שקריאת שמע עושה צורך), והוא קורא ק"ש.
** רש"י ואית דגרסי -
בדברי תורה -
צריך ביאור, שעדיין יש חיוב דרבנן של זכירת יציאת מצרים שלקמן.
* כא:
** קמ"ל -
יש לדון למה לא אמר שאם מת' בצבור, וזכר שהת' ביחיד, פוסק. משמע שלא פוסק, ובצירוף שני סוגיות אלו, הדין נשתנה.
** אתחיל -
אז:
1. יותר קל לו (לא צריך לטרוח כל כך, וגם לא לעבור כל כך) להשלים התפילה.
2. אולי אם לא משלים, הוא יותר רע, שאז נמצא שברך ברכות שלא הועילו להיות שמונה עשרה.
** כמאן דלא צלי -
לכאורה, לא צריך כל כך; יהיה רק כחידוש דבר אחד.
** ומצא ציבור -
שמעתי שחולקים פוסקים אם זה אף אם לא בא מאוחר או רק אם בא מאוחר. לשון גמרא משמע שמיירי כשבא מאוחר. אם אינו דווקא, נאמר שמזכיר ציור הרגיל, ואין סברה לחלק. ותחשב.
לפי מי שיחלק, יש לדון למה נחלק:
1. אולי עיקר ענין דין זה הוא כדי שיחרט על שבא מאוחר, ויבוא בזמן. אבל, בעצם, אינו טוב שימתין להם. ודחוק.
2. אם אינו מאוחר, יותר רע לשהות להת'. לכאו', זה מפני שיכול להתחיל עם הציבור, ואין עליו לאבד את זה.
3. אם הוא מאוחר, יותר רע לאבד ק' וכדומה, שלא נחשב אנוס מחמת תפילתו, אלא הוא מחמת דבר רע שעשה. ותחשב.
כמו כן, יש לומר שלא צריך לשהות מחמת שהוא טורח, אלא אם כן עבר. יש לדון מה טורח יש. אולי מחמת זה יוצא מבית הכנסת מאוחר. גם יש לומר שיש צער כיון שנראה מוזר.
תחשב אם יש נפקא מינא בין סברות אלו שכתבנו.
** כי אתא ר"ד -
יש לדון כמה מזה הוא מימרא של ר"ד. ותו"ת.
** רש"י רב הונא -
והוא אינו כורע -
קצת קשה למה לא יכרע בתוך שמונה עשרה שלו, שאז נראה שאומרו. ותחשב. אפשר שהוא הפסק, שהוא כמו מרמז בעיניו, שמגיד דבר – “אני מודה לה' של אלו" – על ידי מה שעושה בתוך שמונה עשרה. ותחשב.
** למימרא -
הוה מצי לומר שדורש שלא ילמד, וכאן רק מתיר לו לחשוב. נראה שאולי מה שאף מתיר לאחריו, אף שהוא כבר חייב מדאו' משמע שמחלקת נוגע אף לשם, שחולק לטעם חלוק מהיתר של אחריו. שו"ר גמ' לקמן.
לא נראה כן, שלשון רבים של ר"י משמע שקאי על ק"ש עם לחם. אם כן, אולי לכן הז' לפניו. אבל, כיון שהגענו לזה, קל לומר שמדייק ממה שבשניהם אומר לשון רבים. ותחשב.
** דברי תורה -
כמובן, צריך ביאור למה ברכות אלו הם בכלל דברי תורה. ותחשב. אולי הוא מפני שהלכה אומר לומר ברכה, ומזכיר שצריך לומר לשון כזה. ויש לדון. ותחשב.
** דהא ר"י -
לא צריך כל מימרא זה, אלא להביא מה שדורש סמוכים גבי אנוסת אב. ויש לומר שגם צריך לבאר למה דורש, כדי להוכיח שידרוש כאן.
** כאלו -
יש לדון אם הוא כאילו קבלה האב או הבן. מלשון הגמרא, משמע כראשון. מעניין, שאינו אף לומד. ותחשב.
** וכי מפני -
משמע שאילו לא היה נפקא מינא כל כך חמור, היינו דורשים. לכאו', הענין הוא שיותר קשה להרוג אדם משלא להרוג אדם. אז, אם אנו מסופקים בדרשה, לא נהרוג אותו. אז, היה אפשר לומר שרק בכעין זה לא דורש ר"י. אז, ידרוש שלא ללמוד תורה בהיות בעל קרי. ותחשב.
** רש"י עשאן –
לכאו', קאי על כל הברכות שבמשנה. ותחשב.
* כב.
** באימה -
אם מה שפוסל בע"ק הוא מה שאינו באימה די, קצת צריך ביאור למה פסול, שטומאתו (ובפרט טומאת פולטת) בא מקלות ראש שלפני כמה ימים. אולי אם היה דעתו כל כך קל לפני כמה ימים, לא יהיה באימה עכשיו. אם כן, עדיין צריך ביאור דיני אשה, שיהיה תלוי בזמן, ולא באם עדיין אפשר לה לעשות וולד. אז, למשל, אם כבר פלטה הכל, עדיין יהיה אסורה בתוך שלשה ימים (או איזה זמן שננקוט). ותחשב. אולי צריך לומר שנעשה כעין לא פלוג. אבל, עדיין יש לדון, שלכאו' יש גדרים יותר טובים לנקוט. ותחשב. אולי כיון שיש רושם של קלותו, עדיין חושב עליו, ומקיל את ראשו. דחוק.
** מכאן -
לכאו', רצה לומר שאמרו אף שאלו מותרים, בע"ק אסורים. לכאו', לא לומ' מכאן היתר שאר טמאים, שאין מקור לאיסור להם.
** רש"י ובועל -
אם טבלו -
אין צריך זה, לשני טעמים:
1. אפשר להיות טמא כך אם בא עליה ולא נעשה בעל קרי, שלא הזריע. ותחשב. אולי יוצר מצוי שכבר טבל.
2. מרש"י משמע שלאחר יום, כשראוי לטבילה, לא יהיה לו בעיה של בעל קרי. זה תלוי במה שדנינו לעיל, למה אין לבעל קרי אימה ראויה.
גם יש להעיר שלר"י (במשנה שבסוף הפרק) כיון שיש לו טומאה אחרת, לא צריך עוד טבילה לבעל קרי. עיין ברש"י עצמו, שקצת מעורר זה ברש"י, שמציין למשה. לכאו', רוצה לאוקמוה כמו רבנן.
** עדיין לא
הבנתי למה צריך תק' עזרה עם דין של סמוכים. ותחשב. אולי גמ' יבאר.
** מציע את המשנה -
אם גמרא הוא רק פירוש משניות (כמו שאומר רש"י בקידושין ובכמה מקומות), קשה איך מציע את המשנה ולא גמרא, שלכאו' הוא אחד. לכאו', הענין הוא שאפשר לומר פי' המשנה, אבל לא פירוש הפירוש. אין זה מוזר, שפשוט שיכול להיות פירוש לפירוש. ותחשב.
** אזכרות -
סתימות שאר התנאים משמע שסוברים שיכול לומר האזכרות שבו.
** אזכרות שבו -
יש לדון במה (בכל או רק בגמרא שמציע). לא נראה למה נחלק.
** כתנאי -
לכאו', כבר הביא לעיל שהוא תנאי. ותות.
** רש"י נראה בעיני -
נראה שמקורו לזה הוא שלא מביא סיוע, אלא מביא התנא שסובר כאותו שיטה.
** רש"י אפשר -
קצירי -
צריך ביאור מה לומד משם, שרק אומר שמת' על רבנן עם החולים. אולי לא צריך תפילה אם אינם נח' חולים. דחוק.
** רש"י שתבע -
קצת קשה למה מזכיר איסור ייחוד, שלכאו' תבע אותה לבעל לו (ולכן היה צריך לטבול). אולי רש"י סובר שאיסור פנוי הבא על הפנויה הוא מדרבנן, וגזרו כשגזרו על ייחודו (אלא שצריך ביאור למה גזרו, אז, על הייחוד). ותחשב.
** רש"י תקן -
קה"ת -
ק"ק ל"ל אמר לפני ק"ש או תפילה. אולי זה בכלל ק"ת, כמו שהוא בכללו לדין זה. גם יש לומר שמניח (ויש לדון מהי"ת) שלמדו קודם שהתפללו וקראו קריאת שמע, ואז מז' הראשון. זה מניח שרש"י ר"ל ת"ת. לשונו קצת משמע שר"ל קה"ת של רבים (כמו שני וחמישי). אז, א"א לת' כמש"כ. ותו"ת.
* כב:
** רש"י אמר רבא -
רנב"י בתראי -
מעניין, שרש"י אומר שהיה רנב"י ר"נ סתם, והרי רבא אומר בכ"מ בשם ר"נ. אז, לא היה רק אחר רבא, אלא היה גם רבו. אולי אפשר שהיה לרבא רב שהיה שמו נחמן, ולא היה רנב"י. סתם ר"נ של גמרא הוא רנב"י, אבל כשרבא מזכיר סתם ר"נ אינו אותו ר"נ. גם יש לומר שקודם רבא היה נקרא ר"נ, ואחר ימי רבא (אחר שנעשה תלמיד של רבא) היה נקרא ר"נ בר יצחק. (צריך ביאור למה.)
** רש"י אמר רבא -
אפלוגתא -
מרש"י משמע שלא סובר שרבא פוסק כן לדין, אלא רק מכריע בין אלו לומר שאילו היה רק שיטת רבנן, כך היה פוסק. יש לדון למה יזכיר כן. אבל, אחר כך ממשיך לומר שהל' כר"נ כיון שהוא בתראי. אם כן, צריך לומר שסובר שרבא חולק. אז, צריך ביאור מה עושה בתחילת הדיבור.
** רש"י אמר רבא -
בתראי -
גם היה אפשר לומר שהל' כר"נ מח' המנהג, שהרי אומר שהמנהג כמותו. לכאו', רבא לא אומר שלא נהגו כן, אלא שאין הלכה כן. אז, אולי נוקטים כר"נ כיון שההלכה הוא כמו המנהג.
* כב.
** ר"נ תקן חצבא -
נמצא שכשאמר גמ' שנוהגים כריב"ב, אין הכל נוהגים כן, שיש מחמירים, שאם לא כן, למי תיקן.
** ר"נ תקן -
קשה לרש"י שאומר שסתם ר"נ הוא רנב"י, שרנב"י פסק לעיל כריב"ב. צריך לומר שהחמיר על עצמו. גם יש לומר שתקן לאחרים שסוברים שאין הלכה כריב"ב.
* כב:
** מ"מ -
נראה שיש שני דרכים לפי מה יכול להיות החילוק בין כלים לקרקע (לא סיבת החילוק, אלא החי' בדין):
1. טבילה בכלים לא צריך להיות בארבעים סאה. כמו שטבילה צריך ארבעים סאה, אבל שפיכה צריך תשעה קבים, כל שאינו במקווה רק צריך תשע קבים.
2. טבילה בכלים לא מהני, שצ"ל במקווה. כן נראה מרש"י.
** לאחרים -
יש לדון מהו הבעיה:
1. שילמד כשהוא בעל קרי. רצה לומר, דבר גדול הוא ללמוד תורה, ואינו טוב לבע"ק.
2. שתלמידו ילמוד מאת בעל קרי.
** רש"י לא האי -
קצת קשה, אטו לא ראה קרי מימיו. אולי לא היה נשוי, והיה כמו יעקב אבינו. לא נראה כן. הוה מצי לומר שטומאת קרי הוא ממש רק ליום אחד, כיון שזה פחות של טומאה, אם נאמר שדין זה סימן לקלות ראש, מחמת קלות ראש שהיה מיקל בשעת ביאה, ואז כבר עבר יומו, אבל רש"י לא היה משמע כן לעיל.
לולי רש"י כאן, היה אפשר לומר שר"ל שלא נשפך עליו, ולא טבל כיון שסובר כריב"ב. אז, אומר שיש לו לברך, שהוא כפי שיטתו יותר טוב מהם לשיטתו, שמעולם לא טען כלום. ויש לדון מה לנו לשיטתו, שאחרים הוא מוציא, והיה לנו לחוש לשיטתם. נראה שמהני רק אם נאמר כפשט ראשון בד"ה לאחרים, ולא כפשט שני. ותחשב.
** רש"י ולית הלכתא -
לצד ראשון, יהיה ק"ק למה הל' כרנב"י נגד זה, כיון שר"נ אינו בתראי נגד סתם גמרא.
** רמ"א -
לכאו', רצה לומר שאינו רשאי אף בגמגום כשהוא באמצע קה"ת. גם יש לומר שלא בא לחלוק על דין זה, אלא אגב דין זה מפרש כמה יכול לקרוא. ותחשב.
** זבח רשעים -
לכאו', מניח שעשה כן קצת במזיד, שהיה לו לבדוק. יש לדון אם הוה ליה לבדוק בכל ציור או רק אם מצוי. וא"ת אם אינו בכל ציור למה מקשה רבא. ויש לומר שמקשה כיון שאמר, “אף על פי שחטא,” שמשמע שחטא, והיה לו לבדוק (שלא יאמר שחטא אם לא היה לו מה לעשות).
** זבח רשעים תועבה -
צריך להגדיר מתי אומרים כן לתפילה, שבקרבנות לא רק אומרים כן אם הרשע בקרבן זה, אלא אף אם הוא קרבן של רשע בכל דבר (כמו ק' גמ' גבי נדחים). אז, לכאו' כן יהיה הדין גבי תפילה. ותחשב. אם כן, אולי בעל תשובה שלא כבר קבל על עצמו כל המצוות אולי לא באמת מתפלל. יש לדון למה לא חוששים, אז, לברכה לבטלה. אולי אינו לבטלה כיון שמרגיל אותו ומחנך אותו, וגם שמביא אותו לתשובה. גם יש לומר שכל ברכה טוב, ואז יכולים לברך, אבל לא עולים לשמים. מוזר לומר שהם טוב, כיון שהם תועבה. אולי התפילה תועבה, אבל כל ברכה טובה. ותחשב.
** יש גורסים
כאן "מאי תקנתיה להדר ולצלי.” לכאו', כפי מש"כ בדיברו הקודם, צריך לשוב קודם, כדי שלא יהיה רשע עוד.
* כג.
** האי אם שהה -
נראה שידחה גמרא (רצה לומר, מי שאומר פשט זה) שבא להשמיע לנו עוד דין, והוא שצריך לשהות.
** שמור נקביך -
משמע שלא תשתין בשעת תפילה. אם כן, קצת קשה, שהיה לו לומר שלא תתפלל כשצריך לנקביו. אולי כן רצה לומר, אבל אין הלשון משמע כן כל כך. אז, קשה, שא מצאנו שאין להשתין בתוך תפילה. אולי רק רצה לומר שאינו כבוד, ואז צריך לשמור ממנו. ותחשב.
** הכון -
לכאו', זה לא מעכב. אם כן, אינו אומר כמו שאומר חוזר לראש (אלא שאולי מיירי בשיכול לשהות).
** תפילתו תועבה -
משמע שלא יצא. אם כן, יש לנו ראיה על המחלקת לעיל. צריך ביאור למה לא הביא גמרא את זה לראיה.
** להשתין -
יש להעיר שפשוט שאין האיסור רק ללבוש בשעה שנפנה בביה"כ קבוע, שאסור בתוך ארבע אמות. אז, נראה שאפשר שאיסור הוא ללבוש אותם קרוב לבית הכסא קבוע, אבל צריך שיחשב ביה"כ קבוע, והוא שבא מח' כך. אם רק משתין, אינו כן. גם יש לומר שצריך להרחיק לבישת תפילין מהפנה, והרחק זה הוא ד"א (אולי זה הרחק מקום, ואולי זה הרחק מעשים, שיש ביניהם מעשה של הרחקתו ד"א). עדיין צריך ביאור דין "עשאו קבוע,” שכיון שהוא קבוע, לא עושה דבר בו. אם נאמר שבשעה שנפנה, בב"א הוא קבוע, ואז נפנה בקבוע (או שמניחים שנפנה בשני טיפות), אז לפשט שני שכ', היה צ' להרחיק ד"א מתחילה. יש לומר כפשט ראשון. גם יש לומר שיש כבר הרחק מעשה, והוא שעושה ביה"F קבוע באמצע. אז, יש עשייה חשובה זה שמחלק בין לבישת תפילין להפנותו (של תוך בה"כ קבוע). ויש לדון, שאינו באמצע, שהם בב"א. ותחשב.
שוב נראה לי שאולי אפשר לומר צירוף, והוא שאולי צריך להיות קרוב לפנותו (מעשה פנייתו) וקרוב לביה"כ קבוע. יש זה רק אם הולך לבה"כ קבוע לפנות, ולא אם הולך לביה"כ קבוע להשתין, ולא אם הולך לבה"כ עראי לפנות (אבל יש אם הולך מביה"כ שנפנה שם). ותחשב.
** חיישינן -
יש לדון אם מי שאסר אסר מחמת זה או לא. אם לא אסר מחמת זה, יש לדון למה יאסר:
1. סיבה אחרת של רבא (רצה לומר, גמרא דן בשני צדדים ברבא (או, אולי, רבא אמר שני היכולות). אולי סובר רק כאחד, ואולי רבא לא סובר כאותו אחד.
2. אסור להיות בתוך ד"א של בה"כ קבוע עם תפילין. וא"ת אם כן למה דן בהולך להשתין, ולא רק בהולך:
  1. לחידוש במותר. (א. לא חוששים לחשש של רבא. ב. מותר להשתין וללכת להשתין בתפילין.)
  2. אולי צריך שמחשיב אותו לבית הכסא, ואף אם אינו מחשב אותו לביה"כ קבוע (על"ע ד"ה להשתין).
** ביה"כ קבוע -
יש לדון ממה צריך להרחיק:
1. מבית הכסא קבוע.
2. מן הצואה.
** ונופל ומת -
וא"ת מהי"ת שזונה עשתה כן. ויש לומר שאמרה. גם יש לומר שמניחים שכן קרה, שמס' אין תלמיד רשע כל כך. גם יש לומר שכיון שהמית את עצמו, רואים שאינו רשע. יש לדון, שגם ח.ו. הרג את עצמו.
** חלונות -
צריך ביאור מהו החיל'.
** קל וחומר -
אין הענין לכאו', שיש שני דרכי דיון, ועל פי דרך זה היה יוצא דין זה, אבל על פי דרך אחר, היה יוצא דין אחר. לכאו', יש קל וחומר, והקל וחומר נכון, ואומר שאין איסור במה שהוא משתין בעצמו. אבל, יש עוד בעיה, ועל אותו בעיה, אין קל וחומר להתיר, שלא מצאנו מקום שמותר אף שיש לו חשש ניצוצות. ותו"ת.
** הנכנס -
מה שהוא גנאי הוא, אולי, מח' מש"א גמ' (חולין) שבתוך סעודה, צריך להראות שרחץ את ידיו, ואז ממילא הכל ידעו שנפנה. גם היה אפשר לומר שאינו גנאי, אלא אינו טוב לאכול כשצריך לנקביו. אולי זה אינו רק כשמרגיש שצריך, אלא אף אם צריך. ותחשב.
** ועד אימת-
יש לדון מה רצה לומר. אולי רצה לומר "עד אימת לובשם? עד זמן ברכה.” גם יש לומר שרצה לומר "ע"א חולצם? עד שעת הברכה אחרונה.”
** אזמן וצר-
יש לדון אם הענין הוא שיש שני יחסים לתפלין, או שאחד מהנה את חברו. יש לדון מה מהנה למה. אולי אם הזמינו, יותר בטל הוא לתפילין (כמו שאומר גמרא לעיל, ואולי לכן הביא אותו כאן.) גם אפשר שמה שצר בו עושה שההזמנה יותר חזק, ויותר עומד לכך.
** רש"י עם מעותיו -
יש לדון מהיכי תיתי. אולי רק מסתבר לו שזה נחשב דרך בזיון. ותחשב.
** רש"י עשרה פעמים-
נראה שפי' שבכל פעם בודק, שאם לא כן, אין חי' בין עשר פעמים ארבע וארבע פעמים עשר, ולא היה לו לשנות שניהם. ויש לדון, שאולי יש חילוק כמה טור"נים יש, ומתי עשה את הטור"נ. ותחשב.
* כג.
** רש"י כובע -
כיס שלהם -
לכאו', רצה לומר שהוא כיס של תפלין. אם כן, קצת קשה למה מניח גמרא שהוא תחת ראשו ממש, שההוכחה היחידי לזה הוא מש"א גמ': “תחת מראשותיו,” והרי אף שמואל אמר כן.
לולי רש"י (ואולי כן ר"ל) יש לומר שכובה רצה לומר הא"ט, כמו כובע בעברית. אז, מניח שהוא בראשו ממש, ששם לובשים כובע.
** אצבע קטנה -
רצה לומר, יכול להיות אף פחות מטפח, ואסור.
** רש"י היה ישן-
מד"ה ומפירוש שלו, נראה שגרס רק ב"ב. אם גורסים "בנו וב"ב,” אז הראיה שב"ב כולל את אשתו הוא שאל"ה מי כולל, שכבר אמר בניו. ק"ק, שאכ"ק למה יאמר ב"ב, ולא רק אשתו. יש בזה שני נקודות:
1. למה קורא לה בלשון רבים. יש לומר שמדבר על כמה נשים שיש לו.
2. למה אומר, “בני ביתו,” ולא "נשיו.”
** לאסתכולי -
לכאו', דיונים אלו אינם בכל בשרה, שרואים פניה, ואי"ז אסור. אולי הם רק במקומות שבדר"כ מכוסות. גם יש לומר שהוא בכל בשרה, אבל רק אם רואה בדרך תאווה. ותחשב. על תי' ראשון, ק"ק, שצריך להניח שדרכה לכסות אצבע שלה. ותחשב.
** רש"י שוק -
באש"א -
וא"ת א"כ נק' כמשה"ק' גמ' לעיל. לתי' ראשון, יש לומר שמח' שנח' מקום שמכוסה. לתי' שני, יש לומר שאוסר אף אינו דרך תאווה.
** יתלו חייו -
איני יודע כל כך מהו "יתלו חייו.” אולי רצה לומר שהם תלויים בדבר, ואולי לא יחיה.
** אני ראיתי -
רש"י מניח (וכן נראה מגמ') שמיירי בתוך התפילה. יש לדון מהי"ת. אולי ידע גמ' (עיין רשב"ם בפסחים שכ' שלפעמים גמ' יודע על מה מדבר מימרא). גם יש לומר שבלי זה אין חידוש.
* כד:
** אפשר כדר"י -
לכאו', רצה לומר שכן עשה רבו.
** לא סבירא ליה מר -
גמרא במקום אחר כ' שרבינא היה תלמיד חרב של רב אשי. אם כן, לא היה צריך לומר לו "מר.” (עיין גמ' לקמן בפרק רביעי). ויש לומר שקרא לו כן כיון שהיה אז ראש הישיבה. אולי אינו כן לקמן. ותחשב. גם יש לומר שבדברים היה תלמיד שלו ובדברים היה חבר שלו, ואז בדברים אמר לו מר ובדברים לא אמר לו מר. ותחשב.
** אילו -
מעניין, שבא לשמוע מר"י, ורק שמע בריי' שנשנה לפניו. אפשר שלכך היה צ"ל עליו לשון זה, שמשמע שהוא מעט.
** דיי -
נראה שר"ל שהיה די שלי – מתי שאני אגיד "די.” ותחשב.
** אילו -
משמע ששמע יותר. נראה ששמע בריי' זה, אמר שהוא טוב מאד, וידע שר"י יפרש וידון בו (שזה היה דרכו, שאל"ה, למה היה שם). אז, אמר שאף אם רק שמע הבריי' שעליו ידון ר"י, ולא דיון של ר"י עליו, היה מספיק לו. ותחשב.
** ואינו יכול-
מעניין, שהבעיה בניביאי שקר היה למי התפללו, ולא מה שהגבהו את קולם. אם כן, לכאו'ק, בריי' לא מבאר מהו הבעיה כאן. ותחשב.
** הוה משתמט -
נראה שאפשר שלא רצה לשמוע ממנו שלא ללכת לא"י, שיש יותר צורך לת"ח כששמע ממנו בפירוש, כמו שמבואר מגמ' פסחים (נא:). אפשר שזהו מש"א לקמן "אילו אמר"י בפומיה.” אולי לכן הביא אותו כאן.
** רש"י עד שיכלה -
נודף-
נמצא שלשון זה נאמר אף על רוח רע.
** רש"י ואומר -
מופ' ועומד -
אם מופסק, צריך ביאור איך חוזר למקום שפסק. יש לומר שאינו ממש הפסק בדרגא שלא יחזר אלא הוא הפ' לכת', ואומר שדבר הופ' בהפ' לכת'. ותחשב. שוב נראה יותר שלעלם לא חזק להפסק, אבל אין להפסיק, ואז כיון שכבר הפסיק, יפסוק עוד. רק חוזר להיסח הדעת. כמו"כ יש לומר שרק לא יפסוק, שמא יסוח דעת. אם לא סח דעתו כבר, מסתמא לא יסח עכשיו (ובפרט כיון ששייך למה שהוא בתוך תפילה). אינו משמע כן מלשון רש"י. ותחשב.
** בעומד -
לכאו', הוא מפני שיותר מיוחס לאותו מקום,  שלא עומד לצאת ממנו. נראה שבמהלך, מה שלא נח' שם כל כך אינו רק מפני שעומד (שאם ממשיך במה שעושה (מהלך) כן יקרה) לצאת למקום שלא מטונך, אלא שעל כל מקום ומקום ממש, עומד לצאת ממנו מיד, ואף שהולך למקום מטונף אחר. ותחשב.
** חוץ מבית המרחץ -
קצת קשה למה לא מז' מבויות מטונפים.
** לדידך -
כל גמרא זה משמשע שאם שוהה בזמן שלא צריך, אינו מפסיק. עיין ברש"י שכ', “לדידי לא הייתי….” לכאו', היה לו לומר, “לדידי לא היה הפסק, שלא צריך להפסיק. אולי כן ר"ל, אבל לא משמע כן כל כך. אז, קצת משמע שרש"י סובר שאף אם לא צריך לשהות, הוא הפסק. גמרא רק מביא ראיה ממה ששתיקת ר"י משמע שהיה נחית למה שהיה שותק. מת' שלא היה נחית, אלא רק בא לבאר הדין אחרי ששתק. דחוק לומר כן בלשון הגמרא. וקצת צריך ביאור מה יהיה החילוק. נראה ששני דרכים פשוטים יש לבאר מהו הבעיה של הפסק:
1. אין חלק ראשון ושני מיוחסים זה לזה. אז, אם בהכרח לא ייחסו זה לזה, יש יותר הפסק, שיחסם יותר גרוע.
2. אולי צריף של ראשון ושני כולל את מה שבאמצע. זה משנה אותו, ולא יכול לצאת בו עוד. מה שנצרך עושה שנכלל יותר, וגם עושה שיותר משנה אותו, שהוא חשוב. ותחשב.
* כה.
** ידו בבית הכסא -
קצת קשה למה לא דן בידו בתוך ד"א. ותחשב. היה אפשר לומר שענין ד"א הוא דבר שלא שייך ליד. צריך ביאור.
** אגב
מצאנו שיש חשיבות לד"א לכמה דברים (כאן גבי בה"כ, יציאות שבת, קנין ד"א), ומצאנו שיש חשיבות לכדי הילוך ד"א. מסתבר לומר ששניהם מיוחסים. אפשר שכדי הילוך ד"א הוא חשוב כיון שהוא זמן שבו משנה את מקמו בשינוי חשוב. גם אפשר שד"א כיון שכיון שצריך זמן חשוב לבוא מזה לזה. ותחשב.
** מקום מטונף-
מצאנו שהקורא בתוך מקום מטונף לא יצא וגם עבר. מסתמא, מה שעבר אינו מפני שלא יצא. אבל, יש לדון אם מה שלא יצא הוא מפני שאינו טוב, מפני שהוא רע, או מפני שעבר. גם יכול להיות צירוף ביניהם. ותחשב.
יש להעיר שגמרא דורש מ"כל עצמותי.” אם לא יוצא כיון שעשה רע, לכאו', מניח שכיון שכל עצמותיו יאמרו, נמצא שידו אומר אותו במקום שאינו טוב. אז, יש רע. יש לדון מהי"ת שהוא רע די, שאולי הוא יותר רע אם יותר איברים מדברים שם, ורק אז לא יוצא. אם רק לא טוב, מניח גמרא שצריך שכל עצמותיו יאמרו, שהרי כאן, פה שלו וכדומה אומר אותו בחוץ. לכאו', כיון שתורה אומר לקרוא, וסתם קריאה נעשה בכל אבריו, צריך שכל איבריו יקרא. ותחשב.
** צואת אשפה שריחה רע -
צריך ביאור מה אומר. לכאו', רצה לומר שצואת מינים אלו הוא אף אם אין ר"ר, כמו שאומר רש"י, אבל של שאר מינים אסור רק אם יש ר"ר. אם כן, צריך ביאור מה לנו אשפה. אפשר שצואה ל"ד, ורצה לומר אשפה שריחה רע. קורא לה צואה כיון שהוא דבר שלא נצ', כמו שקורא לצואת העין. שוב ראשיתי שיש גי', “ולא כנגד אשפה.” ודע שעדיין יש לדון בצואה של שאר מינים, שאולי כיון שאין דרכם שיהיה להם ר"ר (אם זה אמת), אין ר"ר שלהם כל כך חשוב ואסור. דחוק. במילים יותר טובים, ר"ר רע לא רק מפני שמריח רע, אלא שמריח חפץ שמוציא ר"ר. אולי יותר רע אם  אף דרכו להוציא ריח רע. ותחשב.
** רש"י לית הל' -
מניח ש"לתוכן" שאומר גמרא הוא קאי על כלבים וחזירים. היה אפשר לומר שרק קאי על כלבים.
** כו"ח -
מה שרק נוהג בשל כו"ח, ולא בשל שאר מינים (וכן משמע מבריי'), אולי תלוי במה אוכלים או במה קורה להם כשאוכלים אותם.
** עורות -
צריך ביאור מה לנו בזה. אולי עיין לקמן (שאולי הוא מח' שמוליד ריח).
** רש"י כו"ח -
רש"י פי' ששל בנ"א אין להם ריח רע. רק אומר כן באדם, אבל לא בשל כלבים וחזירים, ואולי משמע שאינו נכון. קשה, שאז יהיו בכלל אשפה. אולי הו"א שהוא רק אם  הריח בא ממה שבאשפה, ולא מצואות אלו (ואף למס', אינו בשאר מינים. ויש לדון, שאולי רק מפ' תנא שאין לצואתם ר"ר. ויש לדון, שלא צריך בריי' לזה, אלא אם אדם מריח, לא יתפלל.)
ושי לדון בהם ובכל כעין זה אם החיוב הוא להרחיק מהם או מן הריח שלהם. (וא,ת נביא ראיה ממה שא"צ להרחיק מריח שאין לו עיקר. ויש לומר שלא מיוחס לעיקר עושה שלא כל כך חשחוב. ויש לדון למה. אולי הוא שעומד לצאת. עדיין יהיה כחזיר. אולי לא צריך מעשה עד שיוצא. ותחשב עוד.) יש לומר שר"ה ור"ח חול' בזה, אבל לא מוכרח, שיש לומר שר"ה אומר שלא יכול להיות במקום שריחו הוא בתוקפו ויש לומר שר"ח מגדר ההרחק מדבר על פי מה שאותו דבר מוציא (דהיינו ריח שלו, שחשוב מפני שהריח שמוציא שהוא סיבה לדין זה).
** עיקר -
לכאו', רצה לומר שיש חפץ שמוציא אותו תמיד בהיותו שם. אם אין לו עיקר, בא על ידי מעשה שנעשה זמן אחד או שני זמנים. ויש לדון כמה מן הקרק' שכתבנו מעכבים. ותחשב. ויש לדון אם ענין זה הוא שלא כ"כ מיוחס לעיקר או שאין העיקר כל כך רע. לצד שני, יש להוסיף שהוא שאין כל חלקי העיקר מוציאים. ויש לדון מה אם  צואה מחובר לאבן, מה נחשב חפץ אחד או שנים. ותחשב.
** לדידיה -
צריך ביאור מהו החילוק. אולי הוא שלא היה לו להפיח. אם נאמר לרש"י שכל הפחה הוא לאונס (עיין לעיל), אולי יש לומר שהיה לו להרחיק ממקומו. גם יש לומר שיותר חשוב לו, שעיקרו יותר חשוב לו, שהוא הוא עצמו. דחוק.
** וכסית את צאתך-
עיין ברש"י. צריך ביאור, אז, למה צריך להיות בחוץ כלל. אולי שם מצוי שיהיו לומדים, ושמא יפסק בעמוד עצמו. גם יש לומר שאינו סאניטארי.
לולי רש"י, היה נראה לומר להיפך, והוא שאם הוא בחוץ, אין אדם שם, ואז לא צריך לכסות אותו. רק בפנים צריך לכסות. אז, צריך לומר ש"כסית" קאי על מ"ר. נקרא צאתך לא מחמת שיוצא מעיר, ולא ממילת צואה, אלא כיון שהוא יוצא מגוף שלו. אז, נמצא שיכול להשתין בפנים, ואף שנשאר מ"ר שם. נראה שיש על זה קושיות:
1. למה לא חוששים לעומד עצמו. יש לומר שאינו לזמן ארוך, ולא מניחים שיפריע לבני אדם.
2. למה צריך לכסות. אולי הוא מח' ר"ר. גם יש לומר שאינו סאניטארי.
3. אם כן, למה לא מכסה צואה. חושב אני שגמ' יאמר שיהני כיסוי צואה. יש לדון, שאולי נשאר ליותר זמן, וחוש' שיתגלה. ודע שאם דין זה נכון, אין זה רק ק' על פשט זה, אלא בדר"כ קשה, שקשה למה לא יכסה ויפנה בתוך מחנה. אולי אז הו"מ לומר שחוששים כשנפנה, ולא כיסה עדייןן. ותחשב. עדיין אפשר לומר כן, אלא שאז צריך לומר שאינו כל כך מהר וקצר כמי רגלים. ותחשב.
ויש להעיר שלרש"י יוצא (ואולי בין כך ובין כך פשוט שיכול גמרא לעשות כן) שכשאומר, “הא בגדולים" ראשון, קאי על קרא שני. עיין בגמרא נדרים ונזיר שדן מתי מפרשים ומבארים דבר אחרון; אולי זה כעין מש"כ שם. ותחשב. (ודע שנראה שמסקנות שני הגמרות (נדרים ונזיר) שונים, אף שהגמרא בלשונו לא משמע שחושב שהוא שונה. ותחשב.)
** לדידיה -
עיין לעיל. נראה שאולי הענין הוא שכל דין הוא שכיון שא"א להח', הקילו לו רבנן (עיין ברש"י ד"ה וה"מ לגרסא). אם כן, יש לומר שאין דין זה א"א, שאם צריך להפיח, ילך לחוץ. אף שזה לא יהני אם כבר הפיח, עשו רבנן דין זה כדי שיפיח בחוץ. ותחשב.
** רש"י שרא ליה -
ימחול -
יש לציין לגמרא נדרים (כה:) שאומר שאף בנדר כזה אין איסור. נראה שזהו כוונת שרא ליה מריה. אם כן, יש לומר שאינו אומר שימחול, אלא שמותר. אז, אינו תפילה, אלא אומר שזהו הדין.
** מפלא אפלויי-
לא אמרו שיעור זה לעיל. יש לדון למה אומר:
1. אולי זה פי' אחר ב"קרמו פניה,” שצריך להיות נקרם הרבה. אז, סובר כר"י אמר רב.
2. אולי זה סובר כרבה אמר רב, וזה סימן למתי נפרכת (ולא בדק אם נפרכת, שלא רצה ליגע בו). מסתבר שהוא סימן טוב, שכשיש הרבה בקעים בו, יותר קל לו להפריך.
3. אולי זהו ביאור חדש ב"כחרס,” שחרס לא נתבקע כך, ובזה צריך להיות כחרס להיות אסור. ותחשב.
4. אולי זהו שיעור חדש שלא נאמר לעיל.
** יבשו -
לכאו', רצה לומר שאינו שם (שחושב אני שאין החמה עושה אותו דבר גוש), כמו בנבלע, ומחדש שמותר, אף שהיה שם. אם כן, לכאו', אין סיבה לחלק בין זה לנשפך (אלא אם כן נאמר שמה שנעשה בידי אדם מגלה שלא רצה שיהיה בתוך הכלי, ומבטל יחס כלי לו. ותחשב.)
* כה:
** והא בטופח -
במילים אחרים, תי' של גמרא הוא שרק הוכחנו שת"ק לא סובר כר"י, ולא סובר שהשעור הוא כ"ז שמטפיח. לא הוכחנו ששיעור תלוי ברשום, ואז יש לומר דבר אחר (כמו טופח על מנת להטפיח) שתלוי בו. ואפשר לומר שחלק מן הראיה הוא מפני שחשב שאין דבר אחר שמסתבר.
** והרי לבו -
קצת קשה מהיכי תיתי שיתכסה עד לבו; אולי יתכסה באופפן שלא יהיה לבו רואה ערווה.
** במים עכורים -
משמע שבצלולים לא היה קשה לגמ' מה שלא חצץ על צווארו (אגב, עיין בגמ' לעיל שאמר שצ' לחצוץ על צוארו. יש לדון מה צריך שלא יראה את הערווה, אם הוא עיניו, פיו, או מוח שלו, או דבר אחר. גם יש לומר שהוא כל מקום נשימה, כמו שאמר גמרא לעיל בעמוד א.) לכאו’, זה מפני שאחד ע”ג מים ואחד תחתיו. יש לדון אם הוא חציצה מפני שקשה לראות (איני חושב שזהו המציאות, שסורפיס של מים משנה אור יותר ממים עצמו (כשיושב במים ורואה במים), או מפני שהוא במקום אחר. ותחשב.
** עקבו רואה -
צריך ביאור למה יהיה חילוק בין עקב לשאר חלק הגוף. ותחשב. רצה לומר, הניחא לב מבין ומחשב, אבל לכאו' עקב לא עושה כן. ותחשב. ויש להעיר שצ"ל שאף ש"כל עצמותי" תאמרנה, אין בכלם איסור זה, ששוקו בדר"כ רואה ערווה, ואינו אסור. אולי, אז, הגדר הוא שאסור אם דרכו אינו שרואה את הערווה. אבל, עיין לקמן בגמ' שמש' שאינו דבר קל ורגיל שלא יהיה נראה, שאומר ש"לא ניתנה תורה….”) אפשר לדחות שאי אפשר לקיים כל דין כל עצמותי, כיון שלא ניתנה תורה למלאכי השרת, וכיון שהותר לשוק, הותר אף לזה, מסתמא כיון שלא רצה שיהיה חילוק בדין בלי סיבה טובה. אין זה כ"כ ק', שיש לומר שבדר"כ לא רואה, אבל קשה שלעולם בשעת קריאת שמע יקפיד. ויש לדון אם זה נכון. גם יש לומר שהוא מפני שאין טוב כיון שכבר עצמותיו אינם בק'. יש לדון. לא נראה כן (קאי אלעיל), שאם כן כוע"מ ש"לא ניתנה,” ורק חולקים אם אומרים ל"פ מח"ז. לשון גמ' לא משמע כן כל כך, אלא משמע שחולקים אם אומר לא ניתנה בדין זה. ויש לדון.
** והרי לבו -
עיין בתוס' ד"ה והרי. הומ"ל שסמך על ביאור גמרא לעיל (כד:) שיש מח' בזה לה' על שיטת אחת.
** רש"י והרי לבו -
עיין לעיל, שכ' כעין זה, וע' במש"כ עליו. לכאו', רש"י לא צריך זה בלבו, שאז יש לומר שחשוב כיון שבו מרגיש ומחשב (אם נניח כן), וממנו בא דם לכל הגוף. נראה שרש"י מפרש למה ממשיך הגמ' להק' מעקב, והוא שמניח שכן הוא גבי לב, וזהו הטעם שנאסר. ותחשב.
** מבטלת ברוק -
מרש"י נראה (וכן מסתבר) שהוא אותו דין של עששית וכדומה, והוא שמכסה אותו. אף שנראה ברוק, עדיין מהני, כמו גבי עשיית.
** בכסוי-
עיין לעיל, שכ', אולי, להפך את הקראי ממש"א רש"י. ודע שאז גם צריך ביאור מהו המקור שכיסוי יהני. ויש לומר שסברה בעלמא הוא. ותחשב.
** רש"י וכמה מיא רמי -
עיין במה שפי'. גם יש לומר שר"ל שניהם מים, ואין מין במינו בטל. לשון גמ' לא משמע כן כל כך. יש להעיר שלרש"י ק"ק למה אומרים כן במי הרעים. איני יודע מה הם מים הרעים, אבל מרש"י משמע שהוא מים שיושב לזמן יותר ארוך. לא היה נראה לי שזה רע למים, אבל אפשר שהוא כן. אם כן, יכול להיות אף דבר מועט. ותחשב.
** תחת המטה -
טמונים בארץ -
לכאו', הענין בטח שהם כטמונים, אבל לא נ' כ"כ פשוט שהם כטמונים בארץ, שאף אם אומרים שהם כטמונים במטה, יהני (ולא כל כך פשוט לי מה נעשה מה בלבוד, שלמשל גבי סוכה, מצאנו שהאויר לא רק נתמלא, אבל נתמלא בסכך כשר. כמו"כ במבוי, נתמלא במה שמעמיד לבינה. אפשר שנתמלא במה שצריך כדי להקל.
** עשרה ודאי -
עיין במה שפי'. יש לדון מה אומר אביי:
1. אולי אביי אומר שנכון ר"י, שיש הפסק רשות בין קרקע לזה (שזה נעשה רשות כבר, ובוודאי לא בטל). אם כן, אומר כר"י וכטעם של ר"י.
2. אולי אביי אמר כר"י ולא מטעמו, שלא היה שואל כיון שפשוט לאידך גיסא. כיון שמטה רשות בפני עצמו הוא, וזה תחת אותו רשות, נחשב שהוא במקום אחר.
3. אם נאמר כצד זה, קצת קשה למה לא יפ' רש"י כן ברב יוסף, ולמה יעשה מחלקת בין ר"י לאביי. אולי צריך לומר, אז, שרש"י מוכרח כצד ראשון.
4. אפשר לטעון שלשון ר"י לא משמע כצד שני, ואז צריך לומר שחולקים. ר"י אומר ששאל ו, ז, ח, ט, וודאי לא שאל י. אולי לשון ודאי אמר שעל אלו היה מסופק אם ישאל, ושאל, ואף שהיה לו צד שלא ישאל, אבל על זה היה ודאי שלא ישאל. ותחשב. אם כן, מסתבר (לא מוכרח) שמשמע שהוא המשך של מה שבא לפניו. לכא'ו, פשוט שאינו רשות שם (ויש לדון), ואז צריך לומר שכ"כ פשוט שאם גבוה עשר, לא בטל לקרקע. ותחשב.
** דיון -
יש לדון אם כסה (או הרחק) כזה מהני לצואה או רק למ"ר, שהוא רק מדרבנן.
** רשות -
אם עשוה שהוא ברשות אחר, יש לדון אם זה מתיר אף קרוב לו או רק עושה שאין כל הבית מלא ממנו. ותחשב.
** רש"י סכנתם -
כמעט-
יש לדון לל"א סכנתם, ולמה מוסיף כמעט. אולי רק פאראפרייז את "איכו השתא לא אתאי.” גם יש לומר שאף אילו בעל, לא ודאי שימות. קשה, שסכנה לא רצה לומר שבוודאי ימות. אולי זה לא כל כך מצוי שימות להקיראות סכנה. ותחשב.
** אסור -
וא"ת מהיכי תיתי שחיוב מיתה היא. ויש לציין לגמרא עירובין שאומר שעל איסור דרבנן לעולם חייבים מיתה.
** עד שיוציאם -
לכאו', פשוט שאומר איסור זה על מקום שיש בו ס"ת, והרי אין בו ס"ת.
** כלי שהוא כליין -
יש לדון מה אם הוא יותר מטפח, שאז התיר גמ' לעיל בתפילין. מגמ' כאן משמע שאסור. אולי חלק. גם יש לומר שבס"ת, שיש בו יותר קדושה, כולי עלמא מודו לאסור. ותחשב.
** כלי אחד -
מעניין. אם היו כולם בטלים לס"ת, כיון שהם כליו, לא יהיה אף כלי אחד. ושי לומר שגמ' לאו דווקא, וכן רצה לומר. דחוק, שלא הבנתי למה יאמר כן אם לא רצה לומר כן. אפשר שיש שני דברים שעושים שדבר בטל:
1. יש לו יחס של קורבה.
2. יש להם יחס של רגילות, והוא שרגיל בה להיות עם זה או לשמש זה כך.
בכליו שנוגע, יש שניהם ובטל. כלי אחד שאינו כליו לא בטל, כיון שיש רק אחד. בכלי החוץ שהוא כליו, גם יש רק אחד, ולא בטל. ותחשב. גם יש לומר שאינו בטל לו, אלא כיון שכל כלי מיוחד לאותו דבר (ואותו ייחוד חשוב עכשיו, שכך הם עושים, ויותר, שמפני ייחודם עושים כן), הם בטלים זה לזה, ונחשבים אחד. ותחשב. אפשר שהיה בטל לתפילין, אלא יש יותר סיבה לכל הכלים לבטל זה לזה, ואז אי אפשר לבטל כלי, שיש מכלי זה שלא נוגע בו, ואינו כל כך קרוב לו. לא נראה, שיהיה ככלי עב, שלכאו' בטל. ויש לדון. ותחשב.
** אגב
אגב, ראיתי שש"ע כ' שאם כלי שני הוא כליין, לא מותר. משמע שאם ראשון כליין, מותר. ויש לדון. יש לדון מה נחשב ראשון, אם הוא הפנימי או החיצון. ותחשב. יש לומר סברה לכל צד:
1. אולי יש בעיה אם פנימי כליו כיון שהוא כליו ונוגע בו. אז, בטל לו. אבל, אם אין כלי שהוא כליו ונוגע בו, אין כלי בטל, ונחשב כלי בכלי.
2. אולי יש בעיה אם  חיצון כליו כיון שאולי הבעיה הוא שמשמש בפני הכלי, ואין כלי אחר שמפסיק. ואם תאמר אם כן יהיה אסור בכלי אף בלי ס"ת. ויש לומר שכלי חשוב רק כיון שבטל לספר תורה או כיון שקרק' שנותן לו קדושה, שמשמש ספר תורה, קיים, הואו שמשמש בו עכשיו. ותחשב. נראה שאולי מה שצריך שני כלים הוא שאם רק אחד היה, אז היה בטל לספר או היה בו קדושה, והיה אסור בפניו, ולא שהוא נחשב עוד בפני ספר תורה.
נראה שמקור לשלחן ערוך הוא מאקמטרא, שנראה שיש דבר על אגז, ואותו דבר חיצון אינו כליים. אולי זה מפני שדרכו להיות רק בחיצון. ותחשב. אם כן, יודעים כוונת שולחן ערוך. ותחשב. ויש לדון, שאולי הוא ארגז לספרים אחרים, ולא לס"ת זה, או שהוא ארגז לספרים אחרים, ולא ס"ת ואולי אף לא לס"ת.
** כליין -
יש לדון אם כליין רצה לומר כלי לספר תורה או לספר תורה זה. שולחן ערוך כ' ציור שיש לו מאה כלים. זה אפשר רק אם כלי שרגיל להיות חיצון נקרא כליו או שלא צריך להיות של ספר תורה זה, אלא יכול להיות של אחר, או שיכול להיות כליו רק לזמן, ונשאר עליו דין כליו. ותחשב.
* כו.
** רש"י ורבי יהודה -
קס"ד -
לכאו', הוא ספק בגמ'. אולי מפרש (ואולי סתימות לשון גמקרא משמע כן, שלא דן במשנה אלא בסברה) שגמ' מודה שרק אומר דינו בבעל קרי שהיה נדה מכבר, ורק דנים אם זה דווקא. ודחו"ק, שאז גמ' לא מסיק כצד אחד, אלא שלא כך פי' של ר"י. ותחשב.
** הערה -
קצת צריך ביאור מה היה ההו"א של הגמ', שלכאו' פשוט שר"י אף אמר דינו על משמשת וראתה דם, שאף הוא במשנה. נראה שהו"א שהוא רק לחידוש ברבנן. קצת קשה, שפשוט הוא לרבנן. אולי כיון שרק זה מקשים להוכיח, לא כל כך קשה לגמ' לטעות בזה. ותו"ת.
** לאו בר -
משמע שלא דן לומר שבעצם יפטור, אבל אולי כיון שכבר חייב, חייב. אלא, אומר שבעצם יחייב, אבל כיון שכבר לא היה בר טבילה, פטור. יש לדון, שלעולם הוא כן, שהיה טהור קודם שנקרה. ויש לומר שקודם כן היה טמא שאינו בר טבילה. זה מה שצריך להיות עכשיו. ותחשב.
** תפילת השחר -
קצת קשה למה לא פירש תחילת זמנו, כמו שעושה בפרק הראשון. גם קשה איך מתחיל בלשון זה, שקשה על מה קאי, שאין כאן קרא כמו שיש בקריאת שמע. ויש לומר שקאי על המשנה (כף) בפרק שלישי שאומר שנשים חייבות בתפילה. אפשר שזמן תחילתו כבר נשמע ממה שנקרא תפילת השחר. לכאו', לא רואים זמן התחלת מנחה, אבל יש לומר שלא נאמר, אגב שלא נאמר בתפיפלת שחר. ותחשב. (ודע שאם קאי על של נשים, צריך לומר שיש להם זמן תפילה. אין זה כל כך פשוט לפי הרמב"ם.)
** בשחרית שנים-
יש לדון אם צריך להיות עם תפילת שחר בדווקא. נראה שתלוי בפירוש מילת "בשחרית,” אם הוא בשחר או בתפילת שחר. לשון שחרית משמע כשני, אבל אין אותו הדין כ"כ מסתבר. ותחשב.
** בטל קרבנו-
יש להעיר שלקדשים לילה הולך אחר יום.
** כיון שצלותא הוא -
לכאו', רצה לומר שכיון שהוא רחמי, לא מסתבר לו זמן קבוע.
** מעות לא יוכל -
לכאו', א"א שע"ז ממש קאי קרא, שזמן תפילה הוא דין דרבנן. לרמב"ם, שיש חיוב להתפלל פעם אחת מדאו', לא כל כך קשה. בל"ז, יש לומר שאין זה עיקר הפי' הקרא או שנאמר על שם עתיד. גם יש לומר שכבר גזרו אז רבנן. לא נראה כן.
** הערה -
יש לדון לפי הרמב"ם מה יהיה הדין אם משלים תפילה לאחר זמן – אם הוא מקיים את חיוב שלו דאו' או לא. אם לא מקיים, צריך ביאור למה לא נוקים קרא בזה. יש לומר שלשון משנה לא משמע כן. ותחשב.
** הערה -
לכאו', ענין תפילת תשלומין הוא שלעולם יש אותו חיוב על אדם להתפלל, אלא שלאחר זמן תפילתו, לא יכול לקיים ענין תפילה בזמנו. כיון שעדיין יכול לקיים ענין תפילה, מתפלל. אם לא צריך תפילה בזמן מיוחד, אז, לכאו', יהיה הדין שאם אדם כבר התפלל, לא יחייב להתפלל עוד, אף שהתפלל קודם זמנו. אפשר שבתוך זמנו חייב להתפלל כדי שלא יסמוך על תפילה שלא בזמנו (כמו שאסור לאחר זמן תפילה), אבל לאחר זמן לא יצטרך עוד תשלומין. ויש לדון, שאולי אין תפילת מי שלא חייב, ולא חסר תפילה, כל כך טוב. צריך ביאור למה לא. ותחשב.
גם יש לומר שאין תפילה של כל זמן שווה, וזמן שלפני זמן הנכון חלוק מזמן שלפני זמן הנכון, שבשני כבר בא הזמן הנכון לעולם. אז, רק יכול להשלים אחרי כן. ותחשב.
** מיתיבי -
מפשטות המשך הגמרא, נראה שזה רק קשה על שלא אומרים שעבר יומו בטל קרבנו. זה מפני שלולי כן, היה אפשר להיות מעוות אם משהה עד יום שלאחריו (ואין זה נוגע רק במנחה, ושם בשאר תפילות).
** הערה -
לכאו', מקושיית גמרא יוצא שיכול להשלים ת"ת אף לאחר כמה תפילות, שאם לא כן, קשה למה לא מתרץ כן. ויש לדון, שאולי היה לו תי' יותר טוב, כמו שתירץ. ותחשב.
** מזיד -
לעיל, בארנו שלכאו' מקיים ענין תפילה לאח"ז, ולכן חייב, ורק לא מקיים ענין תפילה בזמנו. כן משמע מגמרא עצמו. אם כן, צריך ביאור מהו הסיבה לדין זה. אולי הוא כעין קנס. אם היה יכול להשלים, כן היו כו"ע עושים. קצת מוזר שנחוש לבני אדם שחוששים לתפילה, אבל לא לתפילה בזמנו. ותחשב. הצד האחר יהיה שביטול במזיד עושה שאין תפילתו אחר כך כל כך טוב. יש לדון למה. אולי הוא שכבר הראה שלא מחשיב תפילה, שלא חשש לעשות אותו בזמנו. ויש לדון, שאולי כן הראה, אבל אולי עכשיו חוזר בו, שרוצה להתפלל. ותחשב.
** מבדיל בראשונה -
צריך ביאור למה יצטרך להקדים תפילה של אותו זמן. נראה שהענין הוא שתפילה ראשונה שמתפלל באותו זמן ממילא יהיה תפילה בזמנו, ולא יחייב עוד תפילה בזמנו. כיון שכן, שני לא יהני לתפילה בזמן, שלא מקיים בו חיובו, שאין חיוב. ותחשב אם זה יהני לבאר דינים של גמרא זה. עיין ברש"י ד"ה שניה שלא נראה כמש"כ.
** רש"י שניה -
צריך ביאור מהיכי תיתי ולמה צריך להבדיל בתפילה שעולה לזמנו, ולא בשום תפילה. משמע שמהנה את התפילה, ולא רק תפילה עושה שיש כאן הבדלה כשרה.
** רש"י גילה -
קשה למה צריך כך, שהוא של מ"ש כיון שהוא ראשונה, כיון שראשונה כבר נפסלה. משמע שיכול להשלים אחר תפילה פסולה. אולי הוא מפני שהוא עדיין מקיים שום דבר, ואולי הוא מפני שנ' כתפילה. ותחשב.
** תוס' ואין שיחה -
עיין בתוס'. וא,ת מהו התי'. ויש לומר שמוכיח שכן עשוה גמרא. עדיין צריך ביאור מהו התי'. יש לומר שהתי' הוא שיש רק פשט אחד שיהני בשני הקראי. עדיין ק"ק, שעיקר חסר מן הספר. ותחשב.
** אבות -
יש לדון מהו נדון גמרא כאן:
1. מי תיקן תפילות. קצת קשה, שלא נראה צד שני משיב על זה. אולי רצה לומר שמח' קרבנות נתקנו, ואז צריך לומר שהיה מרבנן, ולא מן האבות. על זה יש להקשות:
  1. מי אמר שלא תקנו אבות מח' קרבנות העתידים (כמו שאומר גמ' ביומא, שקיימו דברים שיבואו לעתיד). יש לומר שא"כ, היו להם להקריב קרבנות בבמות, ולא להתפלל. כמו"כ, קשה מי יאמר שלא תק' מח' שאלו היו זמני קרבן (ואף אז היו אותם זמנים ראויים לקרבן).
  2. אם כן, למה לא יאמר צד שני מי תקן אותם, ולמה רק אומר ההוכחה:
    1. לא יודעים מי בדיוק תקן אותם, ואז לא אמר אותו. עיין ברש"י שמפ' מי תקן אותם.
    2. אומר כעין מש"א בריי'. אם כן, צריך לומר שידע בריי'.
  3. למה נתקנו תפילות. לזה, קשה מה אומר צד ראשון. יש לומר שאומר שאין אנו חייבים מח' תקנות אבות (ויש לדון למה לא, שאנו בניהם. אולי לא תקנו לכל זרעם לעלום. גם יש לומר שבהר סיני, נשתנו בנ"י. ויש לדון, שמיוחסים להיות לנו זכות בנים), אלא אנכה"ג מח' תקנתם. ממה שרש"י מפרש כן בחולק (שאנשכה"ג תקנו), לא נראה כן.
** הערה -
יש לדון איך יודעים בדיוק כל הזמנים שאבות תקנו בהם תפילה. צריך לומר שכן מחלקים את הזמנים מסברה. נראה שאין חצות מחלק לילה כמו שמחלק יום בסברתינו, כיון שאין ששמ, אז, להורות שהוא חצות. עדיין, זמנים של ר"י לא כל כך פשוט מסברה.
** מוסף -
זה מוכיח לנו קצת יותר וקצת פחות. קצת יותר מוכיח במה שמוכיח שלא רק תקנו זמן, אלא אף תקנו עוד תפילה. פחוץ הוא מוכיח שלא מוכיח שהיו משנים זמן של תקנה אחרת, שאולי כיון שכבר יש לו סיבה, לא ישנו את דינו, שלא שייך כל כך לקרבן, ועוד שיש סיבה להיות לו זמן אחר.
** הערה -
לכאו', צריך לומר שתפילות חלוקים עושים דברים חלוקים, שהרי אל"ה ת"ת יהני כתפילה בזמנו. ותחשב. ויש לדון, שאולי יכול להיות רק תפילה לזמן.
** קרבנות -
קצת יש לדון בדמיון תפילה לעבודה. היה נראה לומר ששניהם עושים ריצוי (וריצוי זה חלוק משאר ס"ט).
** הערה -
לכאו', צריך לומר שזמן ערבית של היום חלוק משל מחר, שאם לא כן, נתפלל ת"ת אז. גם יש לומר על פי מה שכתבנו לעיל. ותחשב.
* ל:
** אין עומדים -
יש לדון אם זה חוב
(א. חייב אדם להתפלל בדרך טוב, בדרך שיגרמו ויעשו תפילתו מה שצריך לעשות.
ב. בזיון הוא להתפלל שלא מתוך כובד ראש.)
או מעלה (מפני אותם סיבות שהזכרנו) או עצה טובה כדי שיישמע תפילתו.
ואפשר שלא יודע גמרא אם הוא חוב ושתלוי על מקור. גם אפשר ששל ברייתא חוב ושל משנה מעלה או להיפך או כדומה. ותחשב ותבין.
** מצער -
יש לדון מה ר"ל:
א. היה ירא מפני שבא לפני מי שלו יתפלל, ולא כדי להתפלל. היה ירא מפני שבקש רחמים עד שביב מצער את נפשו.
ב. לו היה חוב לצער את עצמו, שכיון שצער עצמו כל כך בתפילתו, היה יותר סיבה. ותו"ת. (נ’ שזה יותר טוב לצד שסיבתו בזיון. ויש לדון.)
ג. אולי רק מהני כשאדם מצער את נפשו (בעיקר,זה שווה ל2, ורק דנים אם יש שום סיבה אם לא מצער נפשו.
ד. אולי רק ר"ל שרק עצה טובה היא, ודוד הקפיד על זה. אם כן, צריך לומר שהכיר שמשנה סבר שחוב הוא. יש לדון איך ידע. אולי לשונו משמע כן או שמה שנשנה במשנה משמע כן (יש לדון שמביא הא דר"א.).
ה. אולי כעין זה יש לומר שרואים שהרבה בתפלה, ואז יודעים שהיה עושה דברים בתפלה בלי חוב. אם כן, אולי אף זה כן, ואין עליו חוב.
** מציין -
ק"ק, שזה כבר נלמד מ"הכון" (שבת- י.). ואולי לרבא שם צריך קרא לציין את עצמו. נצטרך לומר אז שסבר ש"הכון" משמע שצריך להכין את עצמו, ולהכין, על ידי זה, את עצמו לתפלה, וקרא זה אומר שצריך להדר את עצמו.כדי ליישב הסתירה, אולי הם בזמנים אחרים (כהמשך גמרא שם בשבת) או שצריך לעשוות את זה קצת ואת זה קצת. אולי אז צריך אותו קרא. עיין בשי"ח ש"י בשבת). ותח’.
מעניין מה שלא מביא אותן מעשים שם בשבת כאן. אולי שם מציין את עצמו באופן חלוק (זה יתרץ מה שהקשינו בד"ה מציין.) ותח’ בזה (בק’ ובת’ שכתבנו).
* לא.
** כברייתא -
קשה איך יפסוק כברייתא נגד משנה. אפשר שסבר (וקצת קשה מהיכי תיתי) שלא חולקים, אלא שיכול לעשות איזה שירצה. ותח’.
יש להעיר שמתוס’ ד"ה רבנן עבדי לא משמע כן. ויש לדון, שאולי "קיימא לן" לא רצה לומר לדין, אלא שסוברים שזהו הכי טוב. ותחשב.יש להעיר עוד שחקרנו לעיל (ד"ה אין עומדים) במדרגת דין זה. אם כוב הוא, נוכל להבין מדרגת הא דמשנה והא דברייתא- בשניהם יוצא, אלא שחד יותר טוב. אם לא כן, צ"ל שהענין הוא ששניהם טוב, אלא שחד יותר טוב. יש לדון אם חולקים איזה יותר טוב או לא. אי לא, צריך ביאור למה לא יאמר היותר טוב. יש לומר שמחדש שאף על ידי זה יוצא או שאף בזה יש ענין. ותחשב.
** אלא מתוך -
לכאורה, רוצה לומר שני דברים בזה:
א. אין עומדים אלא . . . .
ב. עומדים מתוך הלכה.
והוא שמחדש איסור דבר שצריך עיון והיתר דבר שאינו צריך עיון ומה שהוא לא רק מותר אלא טוב. יש לדון אם מחדש ענין שלישי. יש לציין למה שדנינו באם משנה וברייתא חולקים. ותחשב. גם יש להעיר שאם חולקים, פשוט שאומר ענין שלישי.
** אין - וכן . . . דב"ה -
צריך ביאור למה לא אמר היותר מחודש- “ולא מתוך כובד ראש.” משמע שאינו אסור (או שלא חולק או שלא סובר שכל זה חוב. גם אפשר שרק מנה (יש לדון למה) דברים רעים, ולא דברים שאין להם הטוב הנצרך. גם יש לומר שמנה את הרעים קצת. גם יש לומר שאינו יותר מחודש, שאף שאין כל כך בעיה בתפילתו, אין כל כך רווח.
כמובן, ה"וכן" צריך ביאור.עיין בגר"א. לכאו’, לכן שינהו. אפשר ששווים במה שיש להם אלו הרעות. ותחשב. גם יש להעיר שה"וכן מצינו" צריך ביאור (ואי אפשר לומר כמה שכתבנו. ותחשב.) ודע שמהא דמרי, נ’ שרצה לומר דב"ה (ששם, לכאורה, קאי על דב"ה, שזהו דבר הנזכר. וכן נ’ ממעשה.) עיין בגר"א שגם כן לא גורס "וכן.” אפשר לגרוס "וכן" ולומר שקאי על לעיל. אם כן, צריך לומר שיש סיבה לסיים עם דבר הלכה, ולא רק שאין איסור (עיין בד"ה אלא מתוך, שדנינו בזה). ותו"ת.
** לבו לשמים -
צריך ביאור מה זה ר"ל. אולי רק ר"ל שכוונה  בתפלה (מסתמא כוונה שעומד לפני ה)’ חוב. יש לדון, שזה פשוט, לכאורה.
