* ב.
** מיום טוב אחרון -
ואם תאמר הרי עדיין אז הוא סימן קללה. ויש לדון, שאולי הוא ביום שמיני, שאין יושבים בסוכה, ואין בו סימן קללה. גי"ל שצריך להזכיר אותו, אלא שממעטים. זהו המיעוט שמזכיר ר"י. ותחשב.
** מראש השנה -
לכאו', אומר שכיון שנדונים אז על מים, צריך להזכיר אז. צריך ביאור למה אין זה סיבה לפי ר"י לעשות כדברי ר"א. נראה שאף ר"י מודה שהוא סיבה, שהרי אף ר"י מודה שמתחילים להזכיר קצת בסוכות, אלא שרק אומר שכל מה שיכולים למעט, ועדיין נקיים אותו ענין, ממעטים. עיין לעיל.
גם יש לומר שלא מחמת זה מזכירים בסוכות. מזכירים בסוכות כיון שהוא זמן גשמים. מחמת זה יודעים שצריכים ריצוי לה', כיון שהוא דבר שעליו דן. ותחשב. ודע שאם לפי ר"י רק מזכיר בשמיני עצרת, הרי לא מזכיר ביום הדין. ויש לדון אם הדין נמשך עד אז או לא. ותחשב.
ויש להעיר שגמ' בע"ז משמע שה' דן באדם אחד, ושוב בחברו…. אם כן, אולי ידון קודם שמיני עצרת. ויש לדון, שאולי גשם"ש הוא בדר"כ נוגע לכל העולם, דן בו ה' על כולם.
** ואמר רבי יוחנן
- ביחד- לכאו', לא רואים כן מאותם קראי, אבל רואים כן ממה שקרה עם אליהו. לולי רש"י, היה נראה לומר שאלו הם דברים שבדרך כלל לא ניתנים לשליח.
** ואמר
- לא רק לא נתנו כולם ביחד, אלא אף לא נתנו שנים ביחד, כמו שגמ' מבאר גבי אליהו.
* ב:
** אליה אלקים -
ואם תאמר אולי כאן ה' עשתה שתלד, אבל יכול אחרים לעשות כן. וצ"ב. (ודע שבאמת, יכולים אחרים, אם רואיים, אא"כ יש להם מפתח אחר.)
** גמרא -
משמע שלשון זה לא אומר שהוא ג"ש (חושב אני שדנים בזה). אולי הוא חלוק כאן כיון שהוא פשוט מגמ'. גי"ל ששמע שהיה הל"מ כך, ושמע שיש שאמרו שלא היה הל"מ. באר איזה הל"מ שמע.
ויש לדון אם מקור של ר"א הוא, באמת, מהל"מ, או לא. אם לא, מסתמא הוא מסברה שלו.ממה שמקשים ומתרצים, נראה שמקורו הוא מסברה שלו.
** תחיית המתים -
אין שיטת ר"א כל כך פשוט לי. אם יש חילוק בין סוכות לשאר ימים (וכן נראה, שנראה שאז יש חיוב, ובשאר ימים רק יכול), אז צריך ביאור מה מביא מתחיית המתים, שאף הוא דומה שחלוק כאן. אם לא חלוק, קשה מה מביא מלולב. אולי שיטתו משתנה, מפני קושיית רבי יהושע.
** צריך ביאור
איך יבאר רבי יהושע למה עושים לולב שמרצה, בסוכות. אולי הוא מפני שיותר טוב לרצות משלא לרצות, ואין זמן אחר שיכול לרצות. ויש לדון, שהיה לו להודות לר"א, שיותר טוב להזכיר. אולי כיון שמזכיר לאחר זמן, אינו יותר טוב.
גם אפשר שהבעיה לרבי יהושע אינו שרע לרצות לה' על זה. אלא, הוא שנראה רע, שנראה שאומר לה' שהוא גדול כיון שעושה דבר רע. אז, יש לומר שגבי לולב, שאל נראה כן, שלא מכירים על מה מרצה, אין בעיה. נראה שאולי זהו מה שמקשה ר"א מתחיית המתים, שאף שם, נראה רע, שאומר שה' טוב על דבר שלא קרה. נראה שמה שלומד מלולב הוא רק מתי צריך להזכיר. אז, יש לומר שר"א אומר שצריך לומר מפני אותו סיבה (ר"ל, מוכיח שהוא זמן שראוי לרצות, ואז יהיה חיוב). ר"י מודה, אלא סובר שיש מניעה. מוכיח ר"א מתחיית המתים שאין זה מניעה, ואז סובר שאומרים . ר"י סובר עדיין שהוא מניעה, ואז סובר שלא אומר. ותחשב.
** דכולי יומא זמנא -
יש לדון אם ר"ל שהיה טוב בכל יום שיבוא או שיכול לבוא בכל יום. ויש לדון אם יכול לבוא בכל יום, שאולי יודע שלא בא עדיין אליהו. (אף אם אולי הלך לבית דין הגדול, בני בית דין לא יזכרו אותו. אולי תקנו שמ"ע על פי רוב בנ"א.) ויש לדון, שהיה אליהו יכול לבוא לפני היום. ותחשב. (וכמובן, אם לא קרה, לא היה אפשר לקרות. אז, צריך ביאור מהו בכלל אפשר. אולי כל דבר שיש בו בחירה לא נקרא מוכרח לקרות כן, ואז היה ראוי לקרות. .ותחשב.)
** והתנן יצא ניסן -
צ"ב ל"ל רק אומר שאינו לעולם זמנו, כיון שסוכות אינו זמנו, כמו שמפורש במשנה בפירוש.
* ג.
** האמר -
צריך ביאור למה פשוט לגמ' שיום טוב השמיני הוא "יום טוב אחרון," ולא שיום שביעי הוא כן. נראה שהוא מפני שיום שמיני אינו יום יטוב, והיה לו לומר שהוא יום אחרון של חג.
** לפי-
לבתר- לכאו', שם דן ברוח שלאחר כך, אבל כאן מזכיר אותו לפני כן. יש לדון אם רש"י רק מביא ראיה למושג שרוח טוב למטר או שרש"י סובר שאף כאן, כן הוא, ולא מזכיר אותו כסדר.
* ג:
** לא מנכרא -
עיין ברשי. צריך ביאור למה לא חששו לזה כשנשבע אליהו.
** חזיא -
לכאו', ר"ל שנצרך הוא לזה.
* ד.
** הטי נא -
ואם תאמר הרי התפלל אחר כך שבזה יראה לו ה'. גם קשה שיחוש שהיא כנענית. לשני, י שלומר שכיון שיצא מכנען, לא חשש שתהיה מבנות כנען. עדיין לא פשוט שתהיה ממשפחת אברהם, וצריך לומר שלא היה זה עיכוב.
** יפתח -
לא היה זה שאלה, אלא היה תנאי שהתנה בתוך שאלה.
** את שואלת -
יש להעיר שכאן לא שאל באופן שאולי היה בעיה, אלא שה' עשה שנעשה לטובה, אלא שאל דבר שלא כל כך טוב, וה' נתן דבר אחר. נראה שה' אמר שהוא יעשה שכל זמן הוא זמן הטוב, וממילא והא כטל. אם כן, הוא חלק מן השאלה, ולא מחדש דבר אחר. ותו"ת.
** והיינו -
משמע שהיה חל. ויש לדון אם היה חל ל"ל הקריב אותה. ויש לומר שהיתה עולה, אבל אסור להרוג אותה (ועוד שהיתה קדושתה דחוייה, שלא היתה כשרה). אז, היה אסור להנות ממנה, מחמת קדושתה, אבל לא נקרבת.
ודע שמטענה זה, משמע שהיה הנדר חל. ויש לדון, שאולי היה לו לפנחס לומר לו שהנדר לא צריך היתר. לא משמע כן.
** אפילו-
לא חוששים לכשיכיר, שאז לא יקח, נגד תפלתו. אבל, חשש שלא יכיר. באמת, זה לא נוגע לשאלתו, שבכל זמן יש לחוש שלא היה מוצא מום. נראה שאולי חוששים שמחמת תפלתו לא ימצא, שיחשב שה' הביא לידו אשה טובה. וצריך ביאור.
** צריך ביאור
מה היה אומר אליעזר, שהרי לא שאל שתהיה נאה או שום דבר, אלא התנה בלבו כן. אז, אינו שאלה, וגם אז קשה למה אמר כן. שני לא כל כך קשה; אולי זה היה סימן לו של מי היה טוב. ותחשב. ודע שלולי כל זה, היה אומר שהתפלל, והתפלל שתהיה רואייה. אז, שאל כהגן. ותו"ת.
* ד:
** גברא אגברא -
נראה שההו"א הוא שר"א אומר כר"י, כמו שאומר גמ' ביבמות, שהיה דרכו לומר דברי ר"י תמיד בלי הבאת שמו.
* ה.
** בימי יואל -
צריך ביאור איך יכולים ללמוד, אז, מאותו קרא, כיון שהיה בשנה שלא היה רגילה.
** אכלו בשר-
מקצתם- יש לדון אם ר"ל שמקצתם אכלו בשר בניהם או שאכלו בשר מקצת בניהם. בשניהם, צריך ביאור מהיכי תיתי.
* ה:
** שקולה כשנים -
יש להעיר שגמ' גם אומר שמי שכופר בה כאילו כופר בכל המצוות (שבועות, נדרים, הוריות).
** ימיו -
עיין במה שבאר מירושלמי. יש להעיר שירושלמי שם ג"כ אומר סיבה אחרת למה מת אז. (וקצת קשה הוא כיון שהוא חד דרשה שם. וע"ש.)
** ואף על פי -
זה רק טענה על הכותיים, ולא על הקדרים.
** אדזוטר -
לא רק מפני שהוא צעיר, אלא אף מפני שהוא בתוך ימי כרת. ויש לדון אם היה בימי כרת קודם שמת בו.
** היכי -
מעניין שלא אומרים כעין זה לציור של "יש נספה בלא משפט" בחגיגה. אולי זה נחשב משפט, כיון שהיה צורך.
** שני שנים -
עיין בתמורה, שאומר שלש שנים. נראה שאותו שנה שמלכו ביחד עם שמואל נחשב לו חציו. גם יש לומר שנחשב שמלך עמו כיון שזה עשה שש חדשים וזה עשה שש חדשים, אבל, לא באמת מלכו יחד. ותו"ת.
** אין מסיחים -
ואם תאמר אם כן איך מקיימים דין שכל סעודה שאין בו ד"ת הוא כעין זבחי מתים. וי"ל שצריך לדבר קודם או אחר אכילה. ושי לדון מהו בכלל ה"סעודה," שבו צירך לומר דברי תורה.
** יעקב אבינו -
אף יעקב לא ידע שלא ימות, שטרח בשביל מקום קבורתו. ויש לומר שידע שיקברו אותו, ולא רצה שיהיה במצרים. ק"ק ל"ל אמר להם שלא לקבור אותו. וי"ל שכש"כ שהיו עובדים אותו, וזהו מה שלא רצה. אז, י"ל שעשה כל אותם הכנות כדי שלא יבינו שלא ימות. דחוק למה צריך לטרוח כל כך (נראה שזה יתרץ ברכות שנתן, אבל לא מה שעשה שהוצרך יוסף לטעון לפרעה שישאל על שבועה שלו. ויש לדון, שאולי לא ידע שזה יקרה.).
* ו.
** תלמוד לומר -
נראה שמזכיר כל זה לחלק מן ההו"א עד שמגיע למקור. דחוק.
** מה מלקוש -
יש לדון אם ההו"א הוא שאז אי אפשר להיות שמלקוש הוא לקללה או שאז על כל פנים אינו לאותו קללה, ועדיין נלמד שאין אותו יורה לקללה. מקושיית גמ', וממה שאי אפשר ללמוד מהיקש למסנא, רואים כצד ראשון. ותחשב.
** תלמוד לומר בעתו -
צריך ביאור איך לומד מ"בעתו" נגד זה. ותחשב. ודע שבלי רש"י, צריך ביאור למה מניח ש"בעתו" קאי על מלקוש יותר משקאי על יורה (שקרוב לו). ויש שאין גורסים אותו.
** ז ימים-
אז, ר"ל ארבע ימים. ודע שאין צריכים כך (גשם ולא גשם עד שבע ימים, ושוב גשם לשבע ימים) למצוא כרבי יוסי. ותו"ת.
* ו:
** קודם ועצר -
יש לדון אם ר"ל קודם תחילתו או קודם סופו.
** מאימתי -
עיין שם, שחזור מתירוץ זה.
** רוב -
מעניין שרש"י מוסיף בי"ת. ותו"ת.
* ז.
** מיום שניתנה -
ואם תאמר איך אפשר שיהיה גדול מנתינת התורה. אולי שייך למה שאומר גמ' שבוודאי נתכפרו עוונות בנ"י. ועיין במה שנכ' שם בס"ד.
** לשמה -
אפשר שרש"י סובר שאין קללה באה לו אף אם עושה כן כדי שיהיה נקרא רבי, אלא שרק לא בא לו טובה.
** כי ממנו תאכל -
יש לדון למה לא מביא אותו בחגיגה גבי אחר. ויש לדון. ויש לדון מהו בכלל אכילה, שאולי אינו רק לימוד. ותחשב.
** תלמיד -
אם אינו רוצה ללמוד ממנו, מוזר שאומר שיבוא לת"ח.
** יפוצו
- יש לדון ל"ל מפרש שהוא תורה. ותחשב.
** חרב אל הבדים -
שמעתי פשט בזה שהוא רק אם יושב עם אחר ולא לומד עמו, שיבטל עמו, ולא מחדד. לא נראה כן מגמ' זה.
** תלמוד שאינו הגון -
קשה, שלא יכול ללמדו. אולי יש דרגות של הגון.
** אין מתקיימים -
רק מביא ראיה ביין. ודע שיש לודן אם מים נסרח או נשוך על ידי נחש.
* ז:
** חטאת -
מעניין שלומד מקרא שאומר חטאת, ולא עוון.
** אלא -
רק דורשים מאלו שהוא מחמת זה, ולא שהוא רק מחמת זה.
** העז -
לכאו', לא ר"ל שרק דבר זה מתיר כן, אלא ר"ל שאף אם רק יש בו רע זה, יכול לקרוא לו רשע.
* ח.
** בעל הלשון -
צריך ביאור מה ר"ל, שאני נהנה כשאני מדבר לשון הרע. וצ"ב.
** ולך -
אדם הראשון- צריך ביאור מה זה שייך לכאן.
** בצבור -
משמע שצריך להיות לב מקצת מהם שלם לה'.
** דומה לאשה -
איני מבין מה משל זה מלמד.
* ח:
** שובע לחיי -
נראה שהחי' הוא שזה שאלה שיתן טוב, ולא שימנע רע. ותחשב.
** אי לא דצריך -
מוזר שיש כל כך ראנ"ג אם הוא טוב או לא. ויש לדון, שאולי כו"ע מודים שכיון שנצרך הוא טוב, ורק אומר שיש בו רע גדול.
* ט.
** בשביל יחיד -
היה אפשר לומר שלא אומר שבא בשביל יחיד הצריך, אלא שבא בשביל יחיד שזוכה (שבא בזכות יחיד לרבים). לא צריך להיות שרש"י יאמר שלא בא בשביל יחיד (שמצאנו שבא ליחיד לקמן), אלא אולי פרנסה אף לא בא לרבים בשביל יחיד.
אבל, רש"י מיוסד על גמ' לקמן, שאומר שכיון שרבים צריכים לו, כרבים הוא. אז, אומר שלא תלוי בזכות מי תלוי, אלא למה נצרך. ויש להעיר שזה קצת מחודש, שלכאו', הסיבה שלא יבוא הוא שאין הטובה כל כך גדול. אם רק אותו היחיד זוכה, אז לכאו', ה' רק רוצה בטובה של אותו היחיד, ואז מה לנו בטובת הציבור. ויש לדון, שאולי לא יכולים לעשות בפני עצמם שיפרנס, אבל בהכרח יצטרפו.
ולולי רש"י, היה אפשר לומר שאותו גמ' לקמן אומר שהיה לו לשמה דין של רבים, כיון שהיו רבים צריכים לו. אז, היה זכות של רבים. נראה שלא מסתבר לרש"י שזה יתן לו דין של רבים לזה, שלכאו', הענין של רבים הוא שבא למי שזכה, אלא שהם רבים, ואז בא לרבים. כאן, לא זכה אותם רבים. ותחשב על זה.
** נסתלק מים -
קצת יש לדון, אז, מה הועיל מן, שאי אפשר לחיות בלי מים. אולי עשה שרק ימות בצמא, ולא רעב. דחוק.
** נסתלק -
חושב אני שיש חז"ל שאומרים שלא האמינו בנ"י שמת אהרן. אבל, קשה, שיראו שנסתלקו ענני הכבוד. וצריך לחשוב.
* ט:
** מלוחים -
לכאו', מבאר רש"י איך יודעים שאין מי גשמים מלוחים. קשה למה לא אמר שיכולים לטעים שאינם מלוחים.
* י.
** מתמצית -
היה אפשר לומר שהענין הוא שא"י גבוה, ואז יורד מטר משם למק"א, ואז מק"א לא צריכים כל כך מטר. נמצא שכל מטר א"י בא מה', ובא תחילה, אבל של מקומות אחרים בא מא"י.
** מנליה -
קצת צריך ביאור למה יצטרך מקור לזה, כיון שקל לו לומר שידוע לו שהם באים מים, וידוע לו שים מלוחים, וידוע שאינם מלוחים, ואז צריך לומר שממתקים בעבים. נראה שאולי היה אפשר לדחות שרק בא מתיקות המים, ולא מליחות שלו לעבים. (אבל, קשה שזה הוא מה שחכמי דורינו אומרים שקורה באמת.)
** תתאי -
עיין במה שפירש. לא נראה כן כל כך, שאף שמואל היה בא"י, כמו שאומר גמ' בב"מ (ויש לדון, שאולי רק למד שם, ולא גר שם), ועוד שבא"י מזכירים קודם וקודם לכן (ויש לדון, שעדיין נמצא שהוא מוקדם). לולי זה, היה אפשר לומר שנהרדעא היה מקום שלא היה צריך כל כך מטר כל כך מוקדם, דלא כסורא. ותחשב.
* י:
** בכי טוב -
עיין במה שבאר רש"י בלשון זה. לשון קצת מוזר הוא, שלא מצאנו במקום אחר, לכאורהף שנקרא "כי טוב." ותחשב. אולי מזכיר אותו באותו שם כיון שדן בטובתו.
** בכי טוב -
עיין בביאור של רש"י. צריך באור, שחושב אני שחלקו תנאים אם הוא אותו אור שיש לנו. ותו"ת. ואם אומר כן מחת שלכן נקרא אור טוב, אולי הוא רק סימן שאף אור קלוש שלנו טוב. ותחשב.
* יא.
** וליוסף -
עיין לקמן שאומר קרא שאם לא קיים פרו ורבו עדיין, מותר לו לשמש מיטתו. אם כן, צריך לומר שלא רק היו לו בנים אלא היו לו בנות גם כן, שבלי בנים (אולי) לא קיים מצות פרו ורבו.
אבל, נראה שאולי יוסף לא קיים את כל התורה (על כל פנים בחו"ל), ואז אולי הוא היה, לעולם, כאילו היו לו בנים ובנות, שלא היה צריך לקיים פו"ר. אף אילו החמיר ע"ע לקיים מצוות התורה, אולי אין זה דוחה הבעיה של ביאה בשעת הרעב. ותחשב.
* יא:
** ליכול -
יש לציין לגמ' שבת (קנה:). אולי לכן גם כן נקרא רעב "רעב ככלב" בגיטין (נו), אלא שיש להעיר שבשבת משמע שאל אוכל כל כך, אבל שבע במעט.
** אין ת"ח -
יש לדון אם זה אף בתעניות שיחידים עושים (שאז אולי רק יחידים שאינם ת"ח (יש לדון אם זה אפשר) מתענים).
* יב.
** ייסר -
לא הבנתי למה זה אפשר רק אם אומרים שייסר בצלותיה, ולא שייסר בפיו בכל זמן מנחה. אולי אין הכי נמי, וחילוק ייסר ויאסר הוא לאו דווקא, והכוונה הוא רק אם ר"ל בצלותיה או לא. לא משמע כן. ותחשב.
* יג.
** בצונן מותר -
ואם תאמר נדייק להיפך, שממה שאמר שאסור ברחיצה אחר שכבר אמר שנועלים את המרחצאות רואים שאסור אף בצונן. ויש לדון, שאולי הו"א שרק אסור אם רבים עושים כן, אבל לא אם כל יחיד בפ"ע עושה כן. גי"ל שאז לא הייתי אומר שמרחצאות דווקא. ויש לדון, שאילו היה כל רחיצה אסורה, אהיה לו לומר רחיצה, שאף משמע צונן- ואף בלי זה, הוא יותר בהיר, כיון שהבעיה הוא רחיצה, וכן אומר.
** אבל -
מתו לפניו- לכאו', זהו הנקרא אונן, ולא מה שהוא, בדרך כלל, נקרא אבל. ותחשב.
* יג:
** תכבוסת -
היה אפשר לו לדייק מבריי' שאמר לעיל שרק מותר גבי מי שתכפוהו אבליו. נראה שהו"א ששם בא לחדש שאף לו אסור בחול, אבל היתירו אולי הוא בכל אבל.
** מאי שייר -
עיין במק"א שדננו אם הענין הוא שיותר קל לתנא לשייר שנים מאחד, או שלא מניחים ששייר כלל, ומניחים שיש דרך ליישב כדי שלא נצטרך לומר ששייר, אבל אם שייר שנים, קשה ביותר לתרץ, וצריך לומר ששייר. (אבל,, לשני, דע, שקצת צריך ביאור, שאם מסתבר הוא למצוא תירוץ לאחד, אבל לא לשנים, לכאו', הוא שבכל אחד יכול למצוא תי' בפ"ע, אבל לא מס' ששניהם נכונים, שכל אחד ממעט הצד שהוא נכון. אז, ק"ק מה מהני אם מצא תי' לאחד. ויש לדון בזה. ותחשב.)
מרשי נראה כצד ראשון. ותחשב.
** ותו -
עיין בב"ח. עיין בתוס' בתחילת פרק מרובה.
* יד.
** אידך פירקא -
צריך ביאור ל"ל תירץ כמו שאמר לעיל. וצ"ב.
** נקוט -
עיין בביאור שנותן. עוד צריך קצת ביאור למה אי אפשר לחלק את התעניות ולומר שמעוברת מתענה מקצת מן השבע.
** מי שרי -
היה אפשר לומר ששרי כאן, בשעת הצורך, כמו שתפלה מותרת כאן כיון שהוא שעת הצורך.
* יד:
** אין מטריחים -
סברה זה מחודשת לי, שהרי אילו לא מתענים, לא יש לחוש יותר שלא יבוא מטר, ואז יטרח הציבור הרבה.
** לגרמיה-
עיין בברכות שלא פירש רש"י כן. אולי אי אפשר לפרש מה שכ' שם כאן, כיון ששם רש"י מפרש גמרא שאומר מעשה בתנא. אפשר להיות שאותו תנא חולק על תנאים אחרים, שהרי תנא הוא, ואז כן אומר. אבל, כאן, אילו היה חולק, היה מוטעה, שהוא אמורא החולק על תנאים. לכן, אומר שלא כן נתפרש לשון זה, שאי אפשר לומר עליו לשון שחולק. אז, אומר שעשה להנאת עצמו. ותחשב.
אב, עדיין לא פירשתי ל"ל מפרש שם כמו שמפרש כאן, כדי שיהיו כל המקומות שווים. אולי יותר נהנה מפירוש שפי' שם, שהוא יותר טוב, ממה שהיה נהנה אילו היו שניהם שווים.
** מתניתא -
תי' זה הוא פשוט ביותר, וצריך ביאור מה חשב המקשה. אולי סבר שכיון שהיה רבי יהודה בדור שלפניו, לא ירצה לחלוק עליהם.
* טז.
** מבי כנשתא -
אז, משנה, שאומר שמוציאים אותו לרחוב העיר, משמע שהטעם אינו משום גלות. אולי מי שאומר כן ידחה שמשנה שלנו מבאר מה קורה בעיר שיש לו בית הנכסת אחת. גי"ל שמבאר מה יכול לקרות בכל עיר. (ויש לדון, שזה מניח שמותר להוליך אותו מחוץ לבית הכנסת אף אם אפשר להוליך אותו לבית הכנסת אחר.)
** קברי עכו"ם -
עיין ברשי. משמע שרק אפשר לעשות כן בדיעבד (אם אין קברי ישראל). אז, הנפקא מינא הוא אם יש צורך ללכת לאותו בית הקברות או אין ענין. ותחשב.
** כדי שיבקשו -
מראה מקום הוא שיכולים מתים לבקש עלינו רחמים, ויכולים אנו לשאול להם לבקש.
** אפר -
אז, דיון זה בטעמים הוא מחלת תנאים לעיל.
** מי נדחה -
לא הבנתי למה מזכירים את זה עכשיו.
* טז:
** זה המעמיד -
אין גי' של רש"י כגי' שלנו.
* יז.
** דבעי -
ועוד, שהם תקנו ברכת הארץ. (זה יכול להיות סימן, ויכול להיות סיבה.)
** ויודע שבתי אבותיו -
משמע שבלי זה, מחמת הספק מותר. אבל, קשה, שמי שלא מכיר את שבוע שלו אסור, אף שכל שבוע הוא ספק לו. ותחשב. אולי שם קבוע איסור שלו, שבוודאי אסור הו א ביום אחד.
אבל, באמת, צריך ביאור ל"ל סומכים על רוב. נראה לומר (ואולי זה ג"כ יתרץ מה שהקשינו לעיל) שאין הענין שאולי אסור לו היום, אלא הוא שצריכים שיהיה כהן לעבוד. אז, אף מחמירים על הספק, ואז כיון שמתירים רק למי שאינו יודע, אין בעיה בזה.
* יט.
** שלא תבא -
גם אפשר שאומר שמתענים [כדי] שלא תבוא. אבל, גם אומרים לשון זה על הלל (בערכין), ושם לא אפשר לומר כמה שכתבנו, אלא כמה שרש"י כותב.
* כ.
** יודע אני שלא הרעיש -
אם כן, ק"ק למה היה מותר לנקדימון לעשות כן (ויש לדון שאולי היה טעות עכו"ם), שהיה לילה, אלא שהיה שמש. אולי לא בא שמש כלל, ורק היו עננים. דחוק, שמשמע שתפלתו עשה כן. אולי חזרת שמש עושה שהוא יום אחר. זה מחודש.
ודע שמן המעשה, לא הייתי אומר ששמש חזר, שאפשר שרק היו עננים, והיה נראה כלילה, והראה ה' שלא היה לילה, אבל כן משמע מדמיונו למשה ויהושע.
