* ה:
** גמרא: דכתיב -
לכאו’, שמואל לא אמר כן, שהרי לא היה הפסוק כתוב כבר, שהוא בסוף תהילים (שחבר אותו דוד המלך), אלא גמ’ מביא אותו להוכיח מה שאמר שמואל. (ויש לדון איך ידע שמואל ששקל כשניהם. אין זה כל כך קשה, שמסתמא מי שהוא חשוב ככה יכול לדעת איך הוא חשוב.) ויש לדון אם זה מוכרח, שאולי חלק של תהילים (שאולי כולל מזמור זה) כבר נאמר בימי שמואל. אז, אולי הכיר שמואל בזה.
** לא בטלו -
יש לדון בזה, שהיה מה שעשה משה שבטל בימיו, כמו מה שמנה אהרן להיות כהן גדול. עוד יש להעיר שבין כך מה שהיה קיים היה מה שעשה שמואל, שהרי שמואל גם משח דוד. ותו"ת. (אפשר לומר שלא רצה שבני אדם יטענו עליו. אולי לא נודע שמשח את דוד (שעשה אותו בסתר כדי ששאול לא יהרוג אותו).
** אקפיץ עליו זקנה -
מוזר שלא יבינו ויזכרו שקפץ עליו זקנה. ותו"ת.
** ויבוא לידי סכנה -
לשון זה קצת מעניין. לכאו’, אילו נחנק, זהו הסכנה, ולא שבא לידי סכנה. אולי זה לא נכון, שעדיין אפשר שיוציא אותו, ואז הוא רק בא לידי סכנה. כמו כן, אילו רק קדם קנה לוושט, אולי לא יסתכן. גם אפשר ש“יבוא לידי סכנה“ רק רצה לומר יהיה סכנה.
** אמר רבי יוחנן -
ואם תאמר איך אמר זה גופא בתוך הסעודה. ויש לומר שאילו לא היה אומר כן, היה חברו מדבר, ואז עשה כן להציל אותו. ויש לדון, שלא מסכנים כדי להציל את אחרים. (ויש לדון, שזה חשש קטן, ואינו ממש סכנה.) (ויש לדון בזה, שהיה אפשר לומר לו, ”שתוק,“ ומסתמא היה שומע. ויש לדון.) גם אפשר ששהה לזמן אחד, ואמר כן. אבל, לא רצה לומר דברים אחרים, שרצה לאכול.
** יעקב אבינו לא מת -
זה דבר קצת מוזר להתחיל דיבור של תורה עמו. ויש לדון.
** מה זרעו -
מניח גמ’ שהוא בחיים בזמן ”מיתתו“ (כן מוכרח מקושייתו). יש לדון אם זה מפני שזרעו היה בחיים אז, או מפני שזמן של הקרא הוא שעת ביאת משיח, ואם הוא חי אז, מסתבר שלא מת עד אז, אלא חי עד אז. (ויש לדון בזה.)
** אנא אמינא -
לכאו’, כן היה מוכרח ממה שבעל השמועה אמר אותו (והרי אסור לעשות עצמו לבעל קרי). ויש לדון, שאולי אף ר“נ הבין שצריך להיות בקנטקס"ט של רחב, ולא במימרא עליה. (גם יש לפרש שכוח התורה שאומר באותו מימרא (ויש לדון למה נחשב תורה; אין הגדר לזה כל כך פשוט, שיש חלקים גדולים של תורה (כמו כל עניני רפואה ובריאות) שלא פשוט למה נחשבים (או אם נחשבים) תורה) מציל אותו מקרי.) ויש לדון איך ניסה אותו ר“נ לדעת את זה. ויש לומר שלא מסתבר לו שהוא כעין כישוף, אלא הוא שהיא כל כך נאה, שכל חלק ממנה נאה, ואף שמה נאה. אמירת שם נאה כל כך מביא לידי קרי. אז, אמר ר“נ שהשם אינו נראה כל כך נאה לו, וסובר שיכול לומר אותו שני פעמים מבלי להיעשות בעל קרי. ותו"ת.
** יודעה ומכירה -
אם כן, אין נפקא מינא עוד לאותו מימרא.
** רש"י: ימיו של שמואל -
כד חדש- יש לדון בזה, משני סיבות. ראשון, מניח רש"י שנער נגמל בשני שנים. עיין בכתובות (גבי חיובי אשה לבעלה) שאין זה מוכרח להיות. שני, במה שאומר רש"י שרק עד אז נקרא תינוק (כוונת רש"י הוא שמילת ”תינוק“ בא מלשון יניקה[fn:1]), ק"ק מגמ’ בכתובות (יד:), שממה ששם דן בצד פסול, צריך לומר שהיתה יתירה משלש שנים, ועדיין קורא לה תינוקת.
** אף הוא -
במה שמתרץ רש"י לקושיית גמ’, יש להעיר שמעניין שרש"י בורא תירוץ כשגמ’ לא אומר תי’. צריך לומר שרש"י מפרש שגמ’ יש לו תירוץ, שבהכרח יש תירוץ, וגמ’ לא רצה לומר כיון שבין כך ובין כך הוכיח אותו. לא רק דחה על ידי תירוץ, כיון שתי’ דחוק הוא.
בתי’ שרש"י אומר, יש להעיר שקצת צריך לדון מה בכלל ”חיים,“ שלא כל כך קל לחשוב שחי מת, שיש הארטביי“ט, ויש פול“ס, ויש אויר שיוצא. ויש לדון, שאולי יש ענין יותר רוחני שנקרא חיים.
גם צריך ביאור למה רש"י כופל תירוץ זה (שכבר אמר אותו לעיל).
** יודעה -
תוס’ פי’ שאחד הוא ביאה ואחד הוא ראייה[fn:2]. אז, יש לדון למה צריך שניהם, שלכאו’ קל וחומר הוא, שמי שבא עליה כבר ראה אותה. אף אם נאמר שבא עליה בלי ראייה, עדיין קל וחומר הוא, כיון שבביאה יש הרבה יותר תאווה. ויש לדון בזה, שיש לומר שכיון שכבר מילא את תאוותו, לא מתאווה לה כל כך. ויש לדון, שגמ’ אומר ש“יש אבר אחד…“ בסנהדרין ובסוכה[fn:3]. אולי זה אינו באותו אשה או אינו לאחר זמן.
ויש לדון, לפי רש"י, איזה הוא, ביאה או ראייה. לשון רש"י בד“ה יודעה משמע שהוא ראייה.
** ופירותיו מתוקים -
עיין ברש"י. צריך ביאור למה לא רק אומר שפירות שלו מתוקים, ולמה מדחיק לומר שהם מתוקים למי שרעב.
** אמת המים -
לולי רש"י, היה אפשר לומר שאז האילן בטוח, שתמיד יש לו מים. לפי רש"י, יש להעיר שלכאו’ אין זה קרק’ של האילן. אז, מעניין שנאמר שהאילן נותן כל כך מנוחה לאדם, שהרי חלק מן המנוחה שבא לו אינו בא מן האילן.
* ו.
** גמרא: יורה גופיה -
אז, ק"ק למה הביא מקור אחר (שדוחה) לעיל. גם יש לדון למה זה רק מקור ליורה, שגם אומר שם מלקוש. וצריך על’ בפי’ הקרא (באמת, איני יודע פי’ שלו כלל).
** לישנא -
יש להעיר ששני לשונות הם חלוקים לגמרי. ראשון, פוסק אם נאמר איזה שייכות בין שני המחלקתים, פוסק כתנא אחר. וע’ בגי’ רש"י. שני, לא נ’ שיש שום שייכות ביניהם, שגמ’ לקמן מפרש שלא תלוי מתי בא גשם, אלא מתי נתפלל לגשם, שלא רוצים לעשות רע לעולי רגל. ויש לדון, שאולי יש לומר שאף ה’ מחכה לכך, ואז אינו זמן יורה עד אז. ותחשב. כמו כן, יש לומר שאינו זמן מטר כיון שלא התפללו. ותחשב על זה.
** שבעה ימים -
רצה לומר גשם ושבעה ימים, וגשם ושבעה ימים.
** רש"י: יהיו כמותך -
יש לדון למה רש"י אומר לשון חלוק גבי תורה וגבי עושר. ותו"ת.
** יהיו -
כבוד- איני יודע איפה מצאנו כבוד, שכבוד אינו נזכר, אלא בנים נזכר. אולי כך גרס רש"י בגמ’. (ודע שזה יותר טוב, שבגמ’ שלנו, יש להעיר שלכאו’ לא מצאנו שיש צעצועים לאילן, ואז זה היה צריך. לכן, זה כלול בתוך ברכתו, ומסתבר שזה כלול אף בתוך ברכה זה.)
* ו:
** גמרא: הנודר -
אז, כשדן בזה, דן בכוונת בני אדם. כמו בכל כעין זה, צריך ביאור ל"ל בודקים מה אומרים. אולי לא קל להבחין, ואולי לא פשוט מה קובע בענין לשון בני אדם (כמה צריכים לומר כן או באיזה דרגא צריכים לומר כן). ותחשב.
** והא אמרי -
נמצא עוד פעם שמקשה גמ’ ממה שאמרי אינשי, וצריכים להוסיף את זה לחידות. (ויש להעיר שמעניין שר“פ הוא המקשה, שכבר מצאנו שהוא מחשיב מה שאומרים בני אדם, כיון שהוא תמיד מביא מאי דאמרי אינשי.)
ודע שכאן מסתבר להקשות ממה שבני אדם אומרים כן, שמה שאומר גמ’ מציאות הוא, ומסתבר שבני אדם לא טועים. ויש לדון, שבני אדם טועים הרבה פעמים בדברים כעין זה, כמו שרואים בעינינו, איך שחשבו שרפואות כמו של גמ’ עשו כלום. ותחשב.
* ז.
** גמרא: אי חכמה -
רצה לומר, אין חכמה. גם אפשר לומר שצריכים לקרוא אותו ככה: ”אי חכמה מפוארה (אם חכמה שלך מפוארת), בכלי מגונה [יהיה]?“
** אתון דחשביתו -
לכאו’, לא היה לו לתלות אותו בחשיבות שלהם, אלא בחשיבות היין (דומה לתורה). אולי זהו מה שמחשיב את היין, שהיה של הקיסר. ויש לדון, שמסתבר שהיה לקיסר יין חשוב, ואז לא צריך מה שהוא של קיסר. ותחשב.
** רש"י: יפוצו -
משמע שכל זה רק בסתרי תורה. אבל, בדברים אחרים, יש לומר גם לאחרים שאינם כל כך טובים.
* ז:
** גמרא: נתחייבו -
ואם תאמר אם כן למה לא מוצאים שה’ מכלה אותם. ויש לומר ש“חייבים“ רצה לומר על פי דין. אבל, ה’ מרחם עלינו. גם יש לומר שלא נעצרים לעולם, אלא מתפללים עליהם, ובאים, וזה מפני שאז לא חייבים כלייה.
** נתחייבו -
זה, לכאו’, נגד מש"א גמ’ שאם בא, כפרו כל עוונת שלהם, שאי לאו הכי, שרק אפשר שבני ישראל חייבים כלייה או הם כולם זכאים, וזה לא כל כך מסתבר. ויש לדון.
** סוף נכשל בעבירה -
צל“ע בזה, בסוטה.
** מותר לקרותו -
אולי זה מדה כנגד מדה, שהוא עז פנים כיון שקורא לעצמו תמיד ”צדיק.“ אז, אתה יכול לקרוא לו ”רשע.“ (יותר מכך, יש לומר שזה מה שמשפר אותו, לאותו סיבה שהזכרנו.)
** אין הגשמים נעצרים אלא -
כיון שכל אלו אומרים ”אלא,“ לכאו’ צריך לומר שחולקים זה על זה. (ודע שצריך ביאור מהיכי תיתי מאותם קראי שהוא ”אלא,“ שכולם רק מוכיחים שהוא אחת מן הסיבות האפשרות.)
[אגב[fn:4], נראה שענין פלייאנ“ג קארפיט“ס[fn:5] בא כיון שהיו רגילים הרבה בני אדם לשבת עליהם. אז, כשחשבו כמה כיף יהיה לפרוח באויר, חשבו לעצמם מפריח עליהם, לשבת (שכך ישבו). ותו"ת.]
* ח:
** רש"י: קשה יומי -
צרכיהם- יש לדון אם ממש רצה לומר צורכים שלהם, או רצה לומר שקשה להרחיק די ללכת לבית הכסא. ותו"ת. מסימן הקללה נראה כצד ראשון, אבל אין הכרח, שיש לומר ששם הוא כדי לעשות צרוך ממש. ותו"ת.
* ט.
** גמרא: לרבים -
יש לדון אם רצה לומר שרצה פרנסה זה לרבים (ואז נמצא שלפעמים דן בפרנסה ליחיד, ואף כזה צריך רבים) או שרצה לומר שזכותו בא ממה שהיה מעשיו לרבים. ותחשב.
** רש"י: כדעבוד -
עיין במה שפירש רש"י. אם הייתי רוצה להיות מחודש ומשוגע, הייתי טוען שלא רצה שיהיה כל כך שמוקע בתורה. אז, אומר שכמו שהגדיל את ריש לקיש, כך יעשה לו. ותחשב. אבל, גם אפשר לומר, לולי רש"י, שחשבה שר"ל נכון נגד רבי יוחנן (במה שר“י זלזל בו)[fn:6], ואמר שיעשה לך רעה כזה, שיזלזל בך בלי סיבה וצורך. ותחשב.
** כי -
שום כי בעולם- זה מעניין. צריך לעיין בסוף סוטה (שצריך לדקדק אם כזה יוצא מרש"י שם).
* ט:
** גמרא: ואף ר“ל -
מצאנו כזה בכ“מ. יש לדון למה יאמר ”אף ר“ל,“ ולא ”וכן ר"ל.“
** ורבי יהושע ההוא -
אז, אינו כר“א. ונראה שרק מוקים אותו כר“א בתוך הקושיה, לומר אטו רק כר“א הוא.
* י.
** גמרא: עד לא עשה ארץ וחוצות -
לכאו’, הדרשה הוא ש"ארץ“ הוא ארץ ישראל (כמו שהיום קוראים לארץ ישראל בשם ”ארץ“), וחוצות הוא שאר העולם. מזכיר ארץ לפני חוצות לומר שארץ נברא תחילה. אבל, בפי’ הקרא היה נראה לומר הפוך זה, כיון שכיון שכבר מזכיר שהיה עד שלא עשה ארץ, פשוט שהוא עד שלא עשה חוצות. (היה אפשר לטעון שארץ וחוצות הוא שאר כל הארץ[fn:7], אבל אומר שכבר מלך ה’ קודם זה, וכיון שאין מלך בלי מה למלוך עליו, צריך לומר שכבר היה דבר נברא. מסתבר שזה א“י. אז, אינו מוכיח מזה שא“י קדם, אלא מוכיח מזה שהיה סדר, ולא היה הכל בבת אחת.)
** מנליה -
ואם תאמר מקורו פשוט, שהם מתוקים, ובאים ממים מלוחים. אולי היה דרך אחר לדחות (שהיה אפשר לדחות, כמו שאומרים חכמי האומות בימינו, שרק שותה מים המתוקים מן הימים).
** רש“י: בתחילה שותה -
כך שמעתי- יש לדון אם רש"י אומר ששמע שזהו הפי’ (שלא כל כך פשוט שכוונת "שותה“ הוא שמקבל מי גשם) או ששמע שכך הוא במציאות.
** תנינא -
ע’ ברש"י בביאור איך זה יפקיע שערים. מעניין שחוששים לזה, שלכאו’ יחזור אחר כך. אבל, גמ’ במק"א אומר שכיון ששער הופקע, לא חוזר להיות כל כך טוב. וצל“ע.
* י:
** רש"י: יצא אדם בכי טוב -
כמו- לכאו’, נקרא כן על שם קרא זה. אז, לשון ”כמו“ ברש"י קצת מוזר.
* יא.
** גמרא: אגידול -
לכאו’, היה אפשר לומר שרק רצה לומר מופרש, שאכן הוא מופרש. יש לומר שאין צורך לומר כן, וגם יש לומר שאין קדוש משמע הפרשה אלא בענין טוב. ותחשב.
* יב.
** גמרא: יש לדון
אם אדם יכול לקבל תענית בתוך מעריב אם מתפלל בפלג המנחה; יש לדון בזה לשני השיטות.
* יב:
** גמרא: ואפילו בשבת -
יש לדון אם מביא נקודה זה אגב (כמו שמצאנו בכ"מ) או שמוכיח מזה כמה צורך יש במה שהוא אותו יום. גם יש לדון אם כוונת גמ’ הוא לומר שאי אפשר לוזיף ולפרוע, שאין תענית שלמחר כל כך טוב, ואינו בחילוף תענית זה, או שלא רוצה לוזיף ולפרוע, שאין תענית שלמחר כל כך טוב. ותו"ת.
* יג:
** גמרא: והאמר ר“ח -
יש לדון, שהיה אפשר לומר שהא גופא, שהוא קולא מיוחדת לבוגרת. ויש לומר שלשון השמועה לא משמע שהוא היתר, אלא חיוב עליה שלא לנוול את עצמה. ותו"ת.
** ע’ בגמ’
בברכות שמבאר יח כנגד מה ויט כנגד מה. לכאו’, לא מבאר כה’ (שיש בתענית, אחר הוספת ברכת המינים) כנגד מה. ותחשב. ודע שהיה אפשר לומר שבתענית היו כוללים שנים לאחד, כמו שאומר ירושלמי (לחד צד) לעשות בכל יום. (וצל“ע בירו’ אם אפשר לדחוק אף בו שרק דן בתענית.)
** רש"י: אין הבוגרת -
שני שערות- צריך ביאור מהו כוונת רש"י, שבוגרת היא מי שכבר שהתה ששה חדשים משעת הבאת השערות. ותחשב.
* יד.
** גמרא: מילי דצינעא -
בכל כעין זה, צריך ביאור למה רק מבאר אותו כלל.
* יד:
** גמרא: דאפילו -
יש לדון בזה, שלכאו’ שאלתם הוא כיון שצריכים אז, ומה שהוא ”אפילו“ לא שייך. יותר מזה, יש לדון אם יש, באמת, מקום בעולם שצריך כל השנה, ולא רק שהוא הפוך. ויש לדון, שיש שמגיע להם בכל השנה, כמו בארה“ב.
** רש"י: לגרמיה -
ע’ ברש"י בברכות, שלא מפרש כך.
* טו.
** גמרא: ולישרי לב -
כאן, אומר וי“ו, ואז אין להקשות כמו שאומר גמ’ לעיל. (אבל, לא הבנתי כל כך דיוק של הגמ’ לעיל. וצריך לעיין בקרא.)
** תחתיהן -
כיון שיש צורך להיות אותו מנין של ברכות, כמו שמפרש גמ’ בברכות (שהם כנגד מש"א שלמה).
** רש"י: ישרים עדיפי -
יש לדון בזה, שכל אחד, משמע מגמ’, לא מקבל מה שחברו מקבל. אז, היה נראה לומר שהם חלוקים, וזה יותר טוב באופן זה וזו יותר טוב באופן זו.
* טו:
** גמרא: הנחש -
ע’ בגמ’ גבי ”ראשית ואחור יצרתני“ (או דבר כעין זה).
** מן הגדול -
יש לדון אם מדייק ממה שאמר לאהרן תחילה (וסדר הקרא הוא סימן לזה) או מדייק ממה שנזכר ראשון עצמו, והוא שמזכירים גדול ראשון כשדנים בדבר גדולה (וכש“כ שיש לו גדולה ראשון). ותחשב.
** אתון חשביתו -
צריך להגדיר את זה, שיש לומר כן בכ"מ, שיש לומר גבי קללה שאת כל כך חשוב שהיית יכול לעשות כל כך טוב וכדו’, ואז אתה יותר ראוי לקללה.
** אינו דומה -
יש לדון ל"ל לעשות כן לכל אדם. אולי טורח גדול הוא, ואז רק עושים אותו בשני הציורים שמוסיפים ביותר.[fn:8]
* טז.
** גמרא: לבי כנישתא -
ואם תאמר למי שאומר שיכולים לגלות לבית הכנסת, ל"ל גולים לשם. ויש לומר שבדרך כלל לא היו שני בתי כנסיות (או שני ב“כ גדולות) בעיר. גם יש לומר שכוע"מ שטוב לכתחילה לקיים שניהם, ורק דנים אם חיוב הוא. ותחשב.
** למה מוציאים -
יש לדון לל“א שצריכים אותו שם, להתפלל עמו. צריך לומר שאין צורך בו לתפילה.
** כלי צנוע -
יש לדון בזה. אכן, צנוע הוא, אבל לכאו’ אין צורך לזה, אלא שבדרך כלל כן הוא. ותחשב.[fn:9]
** כדי שיבקשו -
נמצא שרוצים שמתים יבקשו עלינו מלפני ה’.
** קברי עכו“ם -
לכאו’, גם היה אפשר לומר שיש נפק“מ בקברי בנ“י רשעים.
* טז:
** רש“י: היינו -
ע’ ברש"י. גם אפשר לומר שמקשה שכפי הבנה פשוטה, הם אותו דבר.
* יז.
** גמרא: ענני ה’ לשון צעקה -
יש לדון למה נאמר ככה, ולא נאמר כמש"א משנה, שהוא מש“כ בפי’ בפסוקים.
** יונה בתר -
מניח גמ’ שהסדר תלוי במתי חיו. יש לדון אם זה מפני שכן מסתבר שיהיה או שכן מסתבר שהוא. במילים אחרים, יש לדון אם לא היינו יודעים אתה סדר, נחשב שיהיה תלוי במתי חיו, או שיודעים הסדר, ומה שמסביר כמעט כולו הוא שתלוי במתי חיו. אז, מקשה שזה לא טוב, כיון שלא תלוי במתי חיו.
** כהן שאינו מכיר -
יש לדון ל"ל תולים לקולא, כיון שיש רוב.
** לא לירבו כלל -
יש לדון איך יעשו זה, שאי אפשר להם לחתוך אותו בכל רגע. נראה שיודעים שעובדים בשבת, אף שגוזז אסור. (יש לדון, שאולי הותר לזה.) אז, נדע מזה שיעור, שהוא כמו יום. ותחשב.
** רש"י: דאינהו -
מעניין שנקרא על שם דוד.
** דאינהו -
עיקר- יש לציין למה שיש שיטה שבטל קדושת א“י כשאין בית המקדש.
* יז:
** גמרא: אי הכי -
יש לדון מהו ה“אי הכי,“ שבין כך ובין כך זה קשה. ויש לומר שבלי זה, היה אפשר לומר שלא רוצים לשהות אף קצת. ותחשב.
** רביעית -
אז, היום מותר לשתות, על כל פנים, רביעית.
** כל שכן -
כיון שמהני לרביעית, איני מבין כל כך ה"כל שכן.“
** כי גמירי -
אם גורסים זה (או אם מניחים שכן כוונת גמ’, אף לא גורסים זה), נמצא שאין אסמכתות כל כך מכוונות עם ההלכה. ותו"ת.
* יח.
** גמרא: לא אחים -
יש לדון אם ר"ל שאנו אחים עם רומי, ואז למה שונאים אותנו, או שאחים עם שאר אומות אנו, ואז למה אנו חלוקים מהם.
* יח:
** גמרא: לוליינוס -
צריך להוסיף אותם למנין אחים ת“ח. ויש לדון, שאולי רק היו צדיקים, ולא ת“ח. כמובן, זה לא כל כך מסתבר, שאין עם הארץ חסיד.
* כ.
** גמרא: נקדימון -
יש חלק מ“נקדרה חמה בעבורו“ שלא נזכר בשמו, ויש חלק משמו שלא שייך ל“נקדרה חמה בעבורו.“ ותחשב. וע’ לקמן בגמ’ שאומר ”נקדמה,“ ולא ”נקדרה.“
** כאלמנה -
נראה שמניח שאין צורך לומר סימיל“י[fn:10] כיון שיותר קצר לומר מאטיפו“ר, ואז מפרשים שאומר מאטיפו“ר, ומדמים אותה לאשה שהיא כאלמנה. ותו"ת.
** רש"י: אתיא אחל -
מרש"י משמע שזה ממש ג“ש, ולא ”רק דרוש.“ (לכאו’, זה מה שבא רש"י לבאר, שבלי זה, מש"א רש"י הוא קצת פשוט.)
* כ:
** גמרא: כיון שידע בעצמו -
לכאו’, פשוט הוא שחטא.
* כא.
** גמרא: ואח“כ פינו -
ואם תאמר כיון שלא יפול כל זמן שהוא שם, למה חשו (אחרי שגילה להם). ויש לומר שלסיבה אחרת היו מוציאים אותו משם. גם יש לומר שחשו לכלים אחר מיתתו.
** ההוא דיורא -
קשה למה הלכו לו עוד, שלכאו’ היה להם להכיר שהוא גנב מהם, ואז לא יאמינו אותו. ויש לומר שהכירו ושמרו את חפציהם, ואז לא חששו. גם אפשר שהלכו בכמה מקומות, ולא בדקו את חפציהם אחר כל אחד ואחד. ויש לדון, שהיה להם ללכת למקום שלא הלכו בו לפני כן. אולי לא היה מקום כזה.
* כא:
** גמרא: אבא -
כמובן, על כל זה ק"ק מש"א גמ’ ש“טוב שברופאים לגיהנים.“
* כב:
** גמרא: מלמד -
יש לדון איך מלמד ככה, שהייתי אומר שרק עשו דבר שהחלה אותו מאד.
** והקיאום דרך -
מוזר שיכולים עצמות ללכת דרך זבל. נראה שאולי ”דרך בית הרעי“ רצה לומר שנכנס לשם, ושוב הוציא אותו מאפיו. במילים אחרים, בלע אותם עד שם, ושוב השתחווה לאליל של פורסולין.
* כג.
** גמרא: כל העם להר הבית -
יש לדון מה עשו טמאים. אולי היה סכנת נפשות.
** שני אליהו -
מעניין שיש איזה חשש לזה, שמבואר מאותו גמ’ שזה לא דבר מצוי כלל. ואולי רק ר"ל שאילו היו שנים כזה שהיה שבועה, והחשש הוא שה’ השביע (כמו שמצאנו בגמ’ בב“ב, שה’ רצה שאחד יתיר שבועה לו).
* כד.
** גמרא: חמרא -
כמובן, זה מזכיר לנו גמ’ בחולין (ז, אולי). צריכים להוסיף את זה לחידות.
** קודמים לבתי -
צריך ביאור למה, כיון שעניי משפחתך קודמים.
* כד:
** רש"י: שחונא -
עיין בפרש“י, שמשמע שכוונתו הוא לומר שאם הוא שחונה, אז תהיה גשומה, ואם לא, לא צריך להיות גשומה. ונראה שהיה אפשר לפרש שיש שני מיני שנים- שחונא וגשומה. ותו"ת. אז, מתפלל שאם היה ראוי להיות שחונא (שהוא רע), יהיה גשומה. ותחשב.
* כה:
** גמרא: ולשמואל -
משמע שלא פשוט לגמ’ שכוע“מ (ר"ל, כל החכמים מודים) לזה. ותחשב.
** ונימא -
משמע שלא קשה לו מה שאכלו, אלא מה שלא אמרו הלל ראשון. אז, על כל פנים לא צריך לומר שהסיבה שאוכלים הוא כדי להלל.
* כו.
** גמרא: של כהנים -
כמו שמבואר ברש"י, הכהנים והלווים היו חלוקים מן הישראלים, שלא באו רק בשביל כך, אלא גם באו לעבוד. ויש לדון למה צריכים ישראלים להיות במקום ישראלים, שכולם חלק מעם ישראל, ואף כהן יהיה יכול להיות שליח של ישראל. (לכאו’, לא מצאנו שכל שבט צריך שלוחים.)
* כו:
** גמרא: שבהן -
לכאו’, זה לא קאי על יוה“כ. ותחשב.
* כז.
** גמרא: בא שמואל והעמידן -
המקום אחר שבש“ס שיש אותו לשון (מכות), אומר אותו לומר שמיעט אותם (אבל כאן הוא מרבה). ותחשב.
* כז:
** גמרא: נביאים -
לכאו’, נביאים היו הקובעים כיון שהיו גם המנהיגים. יש לדון, שלכאו’ עזרא היה המנהיג שלהם. ויש לדון.
** מנהני מילי -
לכאו’, רצה לומר ”מאי טעמא.“
** ואני מוחל -
יש לציין למה שאומרים בתפלה (בקרבנות), ”ונקריב לפניך קרבן התמיד שיכפר בעדינו.“ מעניין, שלא מצאנו כפרה גדולה בעולה.
* Footnotes
[fn:1] אין לומר שביאור שלו הוא שהוא לשון עתיד, שתינוק, שהרי לילד קוראים תינוק. מוזר לטעון שכמו שיש דברים שאינם נקבות שנקראים בלשון נקיבה (כמו ספינה) כך ילד כן. גם, אז, מילת תינוקת קשה.
[fn:2] ויש לדון- וזה יהיה קצת נוגע למה שנבאר לקמן למעלה- אם ראייה דווקא או לא, ורק רצה לומר הכרה (ואף הכרה על ידי קול או כדומה מהני).
[fn:3] עכשיו, אנחנו מפרשים כמו שאומר רש"י בסנהדרין. עיין ברש"י בסוכה, אבל עיין במה שהערנו על זה בשיח שי, שזה נגד אותו גמ’ בסנהדרין, והוא ממש פלא.
[fn:4] זה ממש לא שייך כלל.
[fn:5] שמצאנו כמה סיפורי שטות, בעיקר מסין וכדומה, שמדברים על מחצלות שפורחים באוויר.
[fn:6] ואולי בגלל זה לא שמע רבי יוחנן לה בב"מ.
[fn:7] מסתבר לומר, אז, שארץ הוא הארץ, וחוצות הוא מה שאינו הארץ, כמו המים והאוויר.
[fn:8] כיון שלא מוסיף, לכאו’, סכום קבוע, אלא כופל מה שיש. אז, כל זמן שיש יותר בושת, מוסיף יותר. ותחשב.
[fn:9] ויש לדון, שלאיזה סיבה, מכיר אני שבני אדם חושבים על דברי קדושה להיות דברים צנועים.
[fn:10] סימיל“י הוא דמיון שמשמש בכ“ף הדמיון. אגב, יש להעיר שנראה שזה שייך למה שאומרים שדבר הוא סמל של דבר אחר. ותו"ת.
