גמרא אומר שאם אדם קבל תענית עליו, אומר תפלת תענית (עננו). אבל, בלילה שלאחריו, אף אם עדיין מתענה, אינו מתפלל תפלת תענית. גמרא שואל אם סובר שאין תענית לשעות תענית או רק סובר שאינו מתפלל בו תפלת תענית. מרש"י נראה שיש שני נפק"מ- אם צריך להתענות, ואם יש עליו שם תענית.[fn:1] גמרא משיב שאולי לא סובר כאחד מן הצדדים, ואין זה תענית לשעות.
רש"י פירש בציור זה ש“לן כל אותו לילה לשם תענית עד הבקר.“ לקמן בציור זה, רש"י מפרש שלא היה בדעתו להתענות מאתמול, ולא היה מכוון להתענות עד שעברו מקצת שעות לילה[fn:2].
בפירוש ציור זה במסקנא, כ’ רש"י שלא קיבל עליו מאתמול. לכאו’, אז, צריך ביאור מה משנה בין ההו“א למסקנא. אפשר לומר שמה שמשנה אינו ציור זה, אלא שאלת גמ’. אולי ידע גמ’ שלנו שהיה מושג של ”תענית לשעות,“ והיה בו דיון. אולי סבר שזהו הציור של תענית לשעות, אבל חזר בו ואמר שאין בזה שאלת של תענית לשעות, ואותו שאלה היא בציור אחר.
עיין בב"ח שלא פי’ כן ברש"י, אלא פי’ שגמ’ משנה ציור זה, ואומר שלא קבל עליו אף בלילה, אלא רק ביום. אז, כשרש"י אומר כאן אתמול, לא ר"ל אתמול להל’, אלא קודם בוקר.
ויש לדון אם הבעיה הוא שלא קבל עליו אתמול או שלא קבל עליו כלל, שעכשיו מכוון לאכול מיד, אבל קודם שיאכל, רוצה לומר עננו. ותו"ת.
לקמן, פוסק גמ’ שמתענים לשעות. גמרא מפרש שזה רק אם משלים את התענית שלו. מקשה גמ’ שאז אין בו חידוש, ופשוט שמתענים. רש"י מפרש שסובר גמ’ עכשיו שקבל עליו (לא מפרש מתי) להתענות חצי היום, ושוב התענה (יש לדון אם חזר וקבל) כל היום, פשוט שנחשב (יש לדון איזה חצי נחשב כן) תענית.
רש"י מפרש שמקשה סובר שתענית לשעות הוא תענית אומר שיכול להתענות עד חצי היום ונחשב תענית. לא באר עדיין דין קבלתו, אלא אומר שתענית שאינו לכל היום נחשב תענית.
גמ’ משיב שיש חידוש בציור שממליך אמלוכי. רש"י מפרש שלא כוון כלל להתענות, אלא התענה חצי היום, ושוב קבל עליו אותו חצי האחר.
אז, היה נמצא שהדין הוא שאם לא קבל עליו (או, אולי, אם קבל עליו לאחר לילה), אינו תענית. אם קבל עליו בתוך לילה, הוא תענית אם מתענה כל היום.
אבל, לצד אחד בגמ’ (המקשה), הדין יהיה שאם קבל עליו מבעוד יום (שלכאו’, כן סובר ממה שסבר שאין חידוש), אם מתענה למקצת הזמן חל. (אין זה מטעים עם מה שאומר גמ’ לעיל (במקבל לאחר לילה ובתוך לילה, שלצד זה, אין אחד מהם חל.)
שמואל אומר שצריך לקבל עליו תענית מבעוד יום. לכאו’, זה נגד הדין של תענית לשעות. אבל, קשה, שפוסק הלכה כשניהם. אולי דין של שמואל הוא רק אם לא מתענה כל היום, אלא מקצתו. אבל, קשה, שהיה אפשר לתרץ כן לקושיה שמקשה ממנדבי עצים. אז, נראה שגמ’ לא סבר שדין זה נכון. צריך לומר ששמואל יחלוק על אותו מקשה. אף שחולק על סתם גמ’, הל’ כשמואל.
ראיתי בערוך השלחן שת’ שבתענית שעות, רק שעות שלאחר כן נחשבים חלק מן התענית, ומהני כיון שהם אחר שקבלו אותו. אז, אינו צריך להיות ביום שלפניו, אלא לפניו. (ק"ק לשמואל שאומר שצריך לקבל אותו במנחה. אולי יכול לקבל בכל תפלה.)
נמצא שאם קבל בשום זמן, יכול להיות מה שבא אחריו תענית. אולי (תלוי על מה שדיננו לעיל)  יש יוצא אחד מן הכלל, והוא שאם לא קבל כבר בלילה, אי אפשר לקבל אחר כך.
* Footnotes
[fn:1] לכאו’, הנפק"מ הוא אם מכפר לו כמו שעושה תענית. (אגב, ק"ק איך לא יהיה מכפר, שמרשי משמע שמה שמכפר בתענית הוא הצער שמצער א“ע.)
[fn:2] צריך ביאור מה יהיה אם חשב כן בתחילת לילה. אולי בין כך ובין כך צריך להיות ספק, שהרי אי אפשר לצמצם. דחוק, שעדיין היה לו לבאר מהו הדין, ולא רק מה יקרה כשעושה כן.
