* ב.
** תנא היכא קאי –
מכלל דפשיטא –
מרש"י משמע שקושיית הגמרא הוא שהמשנה התחיל בשאלת "מאימתי מזכירים גבורת גשמים," שמניח שמזכירים גבורות גשמים. ממה שלא פירש הנחה זו, צריכים לומר שכבר היה פשוט לו שמזכירים. אז, שואל גמ' מהיכי היה פשוט לו.
לולי רש"י, היה אפשר לומר שקושיית גמ' הוא למה שנה את זה בתחילת תענית, שלא נראה שהוא שייך לשאר המסכתא. אלא, צריך לומר שהוא ממשיך ממסכתא אחרת.
אבל, לא נראה לפרש כן, מכמה טעמים. טעם ראשון הוא שלכאו' הוא נוגע למסכתא, שהרי המסכתא מדבר בתענית שבא, בדר"כ, על עיכובכ גשם. אז, מתי מזכירים ושואלים לגשמים הוא מאד שייך לזה. טעם שני הוא שאז תי' שני של גמ' הוא, בוודאי, לא נכון. כמו שאומר גמ', תי' שני משיב על השאלה, אלא שאז יש קושיה אחרת. אבל, לפי צד זה, קושיית גמ' אף לא משיב לשאלת גמרא. טעם שלישי הוא שעדיין קשה למה נכנס לתחילת תענית, ולא נכתב בסוף אותו מסכתא. אבל, יש לדון, שיש לומר שכבר היה פשוט לגמ' שכיון שזה מסכתא קטן נשנה כאן. ויש לדון.
** מאי שנא דשבקיה –
סדר מועד –
אילו היה מחכה כמה מסכתות באותו סדר, זה לא היה קשה. אולי זה מפני שעדיין אינו הרחק כל כך גדול או אולי זה מפני שאין סדר למשניות, ואולי הם זה מיד אחר זה. אבל, כיון שהוא בסדר אחר, אי אפשר לומר כן (שבוודאי יש סדר בתוך סדרים – לא שבוודאי סדר זה בא קודם סדר אחר, אלא שבוודאי משניות שלו באו בזמן אחד), ואז יכולים להקשות.
** ראש השנה –
נמצא, אז, שיש סדר למשנה קצת, שיודעים שראש השנה בא קודם (ואולי אף מיד קודם) לתענית. ותחשב על זה. כמו כן מצאנו בנשים, כמו שמבאר גמרא.
** שלש מפתחות –
ביחד-
גם היה אפשר לפרש שלא נמסר אף אחד מהם, חוץ מיוצאים מן הכלל. ותו"ת. גם אפשר – וקשה למה לא פירש – שלא ניתן רובם ביחד לשליח, כמו שיאמר הגמרא. ותחשב.
* ב:
** וידעתם כי אני ה'... –
הראיה הוא ממה שאומר, "בפתחי," שמשמע שה' עצמו יעשה כן. אבל, אין הראיה ממה ש"ידעתם כי אני ה'," דהיינו שנדע שמי שפותח אותם הוא ה', שאין אחר יכול לפתוח, שהרי, רש"י פי' שאין גמ' אומר שאין אחד מהם ניתן לשליח, אלא שאין כולם (או רובם) ניתנים ביחד לשליח. ותחשב.
עיין ברש"י, שנראה שלשונו משמע כצד ראשון, ומפרש ש"בפתחי" רצה לומר על ידי עצמי, ולא על ידי ה', כיון שכ', "אני ה'." ותחשב.
** דכולי יומא זמניה –
יש לדון למה כל יום זמנו:
1. כל יום יכול להיות זמן שלו. יש לדון בזה, שאם אליהו לא בא אמש, בוודאי אינו זמן שלו. (כמו"כ, ידוע שיש ימים שלא בא משיח, כמו שמזכיר גמרא.)
2. כל יום הוא זמן שטוב לבוא. לא בא, כיון שאין אנו זכאים בו, אבל היה טוב אם בא. יש לדון במושג זה, שיש לטעון שאילו היה טוב אם בא, היה בא. ויש לדון.
* ג.
** לפי שאין נעצרים –
יש לדון למה זה סיבה שלא נזכיר אותו בשמונה עשרה. אולי הענין הוא שרק מזכירים להקדמה לשאלה, ואז רק מזכירים דבר שנשאל. כיון שזה בא ממילא, ולא נשאל, אין צורך להזכיר אותו. גם יש לומר שכיון שהוא מוכרח לבריאה, כשמזכירים שה' ברא את הכל, כבר נזכר. ותחשב.
** ואילו טל-
קשה, שאולי לא החזיר טל, ולכן לא אמר טל. ותחשב.
* ד:
** אשתבועי למה ליה –
לכאו', היה לו להקשות יותר מזה, שכיון שבוודאי יבוא, לא רק שאין צורך לשבועה שלו עליו, אי אפשר לו לשבוע עליו, שבוודאי יבוא, ושבועותו שקר. נראה ששבועתו היה רק שלא ישתמש במפתח שלו לתת טל. אבל, כיון שהוא מוכרח לעולם, אינו בידו. אז, אינו נגד שבועתו, אבל שבועתו לא עשה כלום. ותחשב.
** אפילו אמר –
רש"י מפרש שרצה לומר שאם אמר אותו בלי סיבה, לא מחזירים אותו. לולי רש"י, היה אפשר לפרש שאם אמר טל, במקום גשם, לא מחזירים אותו, שהזכיר שה' משנה את האוויר לצורך העולם. ותחשב.
* ד.
** שאלו שלא כהוגן –
מעניין שקוראים לאלו "שאלות." לכאו', לא שאלו לכלום, אלא אמרו תנאי, ותנאי שלהם לא היה טוב. (יש מהם  ששאלו, כמו אליעזר, אבל לא כולם שאלו.)
** השיבו כהוגן –
מעניין שזה היתה השבה כהוגן, שהרי היתה איילונית. גם יש להעיר שכנראה החשש הוא רק לגידמת, ולא לרשע. אולי כיון שיודעים שנתן מים לו ולגמליו, בוודאי לא היתה רשע.
** ולא עלתה –
אין זה שלא כהוגן –
יש להעיר שאף אם היה זה שלא כהוגן, היה סוג אחר של "שלא כהוגן," שתלה על דבר שלא טוב לה' לעשות. אבל, באלו, מה שאינו טוב הוא מפני שתלה בדבר שאפשר לקלקל לו. ותחשב. צריך לעיין בזה, שלא בארתי את החילוק טוב.
** ויבוא –
סימן קללה –
קשה למה אמר שפעמים לא נתבקש כיון שהוא סימן קללה, שהיה לו לומר שלפעמים לא מתבקש כיון שהוא עצמו קללה. במילים אחרים, לפעמים אינו רק סימן שיהיה קללה, אלא הוא עצמו רע, והוא עצמו הוא הקללה.
* ה:
** ששקולה כשתים –
דכתיים –
לולי רש"י, הייתי מפרש שהשתים הם "אותי עזבו" – שעזבנו את ה' – ו"לחצוב בארות נשברים" – שתלינו את עצמינו בעבודה זרה שאין לו כוח. הרעה הראשונה היא שעזבנו את ה' שיש לו כוח אמיתי, ושעשה לנו טובות גדולות. הרעה השנית הוא שעזבנו את ה' כדי לדבר לדבר שאין בו שום ממשות כלל.
לפי רש"י, קשה למה מזכיר שנים, שכותיים וקדריים אינם כ"כ דווקא, שיש הרבה עבודות זרה כזה. אז, קצת מוזר שיתלה בשנים אלו. ותחשב.
גם קשה לפי רש"י מה שנעורר בע"ה לקמן בד"ה מים.
** מים –
לכאו', מובן מה שמכוון לומר בעובדי אש, שידוע שאין לאש כוח אלהות, שהרי מים מכבה אותו. אבל, קשה איך רואים שאין למים כוח אלהות. אולי הוא ממה שאש יכול לגרום שמים עושה איואפורישי"ן. אבל, ק"ק, שגמ' לא אומר כן. אולי הגמ' אינו דווקא, ור"ל שכותיים עובדים כמו הקדריים, אף שאלהים של זה מכבה אלהים של זה. אבל, לשון גמ' לא משמע כן כל כך. ותחשב.
עיין לעיל, שהערנו שלפי רש"י אי אפשר לומר שאינו דווקא. ותחשב.
** אמר ליה –
מסיפור הזה לא מוכרח מי אמר למי לברך אותו. יש להעיר שלא מצאנו לרב נחמן בנים תלמידים חכמים. גם לא מצאנו בנים ת"ח לרב יצחק, אם לא שנאמר שהיה אביו של רב נחמן בר יצחק. (ודע שיש אמוראים שלא נקראים בשם אבותם, ואפשר שאחד מהם היה הבן של מי שקיבל ברכת הסוגיה הזו. ותחשב.) כמובן, גם אפשר שברך אותו, ולא חלה ברכתו, שלא היו בנים כמותו. זה לא כל כך קשה, שהרי גם לבנים היה בחירה. אף אם היו נוטים להיות צדיקים מחמת ברכה זו, בוודאי לא היה מוכרח. ותחשב.
** אף הוא –
ודחנטו –
נמצא, אז, שרש"י משיב על קושיה שגמ' לא משיב עליו. גם נמצא שיש דרשה שלא היו כל בני יעקב יודעים (שהניחו להם לחנט אותו). ותחשב.
* ו.
** לברכה –
דרשה זו קצת מוזר. מתחילה לומד יורה ממלקוש. לכאו', הענין צריך להיות שאף אם הוא של קללה, אינו של קללה באותו אופן של יורה. שוב לומד מלקוש מיורה. אבל, שוב מוצא מקור אחר ליורה. קשה למה צריך לכך; צריך לומר שחוזר מלימוד ראשון. אבל, לא מזכיר הו"א ומסקנא, ולא מראה לנו שחוזר משם. אז, השקלא וטריא קצ"ב.
** דבר שמל –
שכשאינו יורד –
נמצא שאומר שהוא דבר שמל קשיותם של ישראל, אף שלא הוא מל קשיותם של ישראל, אלא העדרו מל קשיותם של ישראל. לולי רש"י, היה אפשר לומר שכיון שרואים שאחרי שמתפללים הוא בא, הם מבינים למה לא בא, וזה מחזיר אותם לה'.
** רביעה -
כיון שדינים הנוגעים מאלו תלויים בדברים שונים (כמו שיצא מגמ' בהמשך), מעניין שיהיה כל כך תלייה ביניהם (שתנא שמקדים את זה מקדים את זה ותנא המאחר את זה מאחר את זה). ותחשב על זה.
* ו:
** אין בהם משום ועצר –
יש מאלו שיכולים לפרש שאלו לא נעצרים אף ב"ועצר." אבל, מן הסוגיה יותר נראה לומר שכיון שיש אלו, בידוע שאינו בגדר של "ועצר," שאלו טובים מאד. ותחשב.
** אל ההודאות -
ק"ק למה לא אומר "כל ההודאות." היה אפשר לטעון שיש כאן טעות סופר שבא ממה שבנ"א רגילים לומר "אל" כמו "קל," שאז הוא דומה ל"כל." אז, כ' "אל" כיון שחשב ששמע "קל," ובאמת היה "כל." ותחשב על זה.
* ז.
** רשעי –
עיין בפרק חלק, שיש גם רשעים מבני ישראל שלא עומדים בתחיית המתים, כמו שמפורש שם. אבל, הם מועטים, ולכן לא מזכיר אותם, אלא מזכיר רשעי אומות העולם.
** לשמה –
כדי להקרות רבי –
ידוע שגמ' זו קשה כיון שמשמע שלא ילמד אדם תורה לשמה, אבל "לעולם יעסוק אדם... שלא לשמה, שמתוך שלא לשמה בא לשמה," וגמ' בסוטה אומר שבדר"כ שלא לשמה טוב. הראשונים מבארים שנחשב סם המוות רק אם הוא לקנטר. (חושב אני שגם רש"י אומר כן.)
אז, הדיוק מרש"י זה קשה, שבלשמה של גמ' זה, שהוא נגד שלא לשמה שהוא סם המוות, אומר שהוא אינו להקרא רבי. משמע שזה בכלל "שלא לשמה." צריך לומר שגמ' זה מזכיר רק שני דברים משלש. יש שלש סוגים – לשמה שמפרש רש"י, כדי להקרות רבי, ושלא לשמה, שהוא לקנטר.
** כדאמרה ליה –
לכאו', מבאר שהסיבה שדברי תורה מתקיימים בבני אדם שאינם נאים הוא מפני שממילא דעת שלהם שפלים. יש להעיר שלא רואים את זה כלל מן הכלים, וק"ק מה היה מראה לה. (כנראה מן הסיפור, לא היתה חכמה גדולה, ואז לא כל כך קשה שדחאה בהבל.) נראה שהיה מראה לה שאף שדבר יש בו מעלה גדולה לענין דבר אחד, לא מוכרח שהוא טוב לדבר אחר, אלא אולי הוא יותר גרוע. ותחשב.
* ז:
** בהיסח הדעת –
נראה לבאר על פי גמ' בסנהדרין שמי שלומד תורה, תורה עומלת לו במקום אחר. אז, לא משכח שום דבר, שכל זמן שהוא לומד, תורה עומלת על כל מה שכבר למד. ותחשב. אבל, מרש"י ד"ה בהיסח הדעת לא משמע כן, אלא משמע שרש"י אומר שדבר נשכח בהיסח הדעת ממנו. ותחשב.
** מותר לקרותו רשע –
יש לדון אם רצה לומר שזה עושה אותו לרשע או שכיון שיש לו זה, בוודאי הוא רשע (אולי שבוודאי יעבור מחמת זה או שבוודאי עבר ולכן הרשה לעצמו להיות עז פנים). (במילים אחרים, יש לדון אם זה סימן או סיבה.)
* ח.
** מחולדה –
עיין בסיפור שמביא רש"י. כנראה מסיפור זה (וכן מוכרח בלשון רש"י) מה שנשא אחרת היה נגד אמונתו, אף שהיה יכול לישא שתי נשים. כנראה, הדרך היה לישא רק אשה אחת, אף קודם תקנת רבינו גרשום. (אבל, צריך לומר שלא תמיד היו נושאים רק אחד, שהרי הוצרך רבינו גרשום לתקן, ואין אדם מתקן על דבר שאין בו צורך.) ותחשב.
* ח:
** כמין קובה –
זה משמע כשיטה רבי יהושע שבא מן השמים. ויש לדון, שאולי מים בא לאותה קובה מן הארץ.
אם נאמר שקובה זו ר"ל עננים, נמצא שגמ' הולך כמסקנת גמ' עירובין שאומר שהמים הוא שם למעלה, ולא שנברא בשבת. ותחשב.
** הנכנס למוד –
במקום אחר הקשינו למה אין זה כמתפלל על עובר להיות זכר (אחר ארבעים יום), שהרי כבר הוקבע. נראה שהוא על פי מש"א גמרא זה, והוא שביום הגשמים אפילו פרוטה שבכיס מתברך, ואז יש לומר שגם זה מתברך. ויש לדון, שמסתמא לא ממש מתגדל, אלא יכול לקנות יותר בו. ויש לדון.
* ט.
** אמר ליה –
צריך לשנות את הגי' בסיפור זה, שמנין ה"אמר ליה"ים לא מסתבר, שנמצא שבן ר"ל משיב את כל שאלות של רבי יוחנן.
** לינוקא –
בן אחותו-
מגמ' זה הקשה רב שלום על המסורה שיש מן הגאונים שחי רבי יוחנן לזמן ארוך מאד. הרי, יודעים שמת מיד אחרי מיתת ריש לקיש, כמו שאומר גמ' בב"מ. אם לא שכולם חיו זמן רב, אז, צריך לומר שהיה חי בזמן תנאים. זה לא נראה, שרואים מגמ' (רש"י כ' כן בפי'; נראה שהוא בכתובות (ח)) שלא היה תנא. אז, צריך לומר שחיו לזמן ארוך. נמצא שלא רק שחיו לזמן ארוך, אלא שגם אחותו הוליד כשהיתה זקנה מאד (או שהיו כמה וכמה שנים בינו לבין זקנו), שילד זה, אחרי מיתת ר"ל, היה קטן. ותחשב.
לולי רש"י, היה אפשר לומר שאותה אחות לא חיה לזמן רב, וזה היה בן של אשה אחרת של ר"ל. אבל, רש"י כ' נגד זה. ותחשב.
** ולא רמזה –
נמצא שלכל דבר שבנ"ך יש סמך בתורה. עיין בגמ' שכשדורש מקורות מנ"ך מקשה איך ידעו אותו קודם ימים של הנ"ך, ומסיק ש"גמרא גמיר ליה." לכאו', צריך לומר שנרמז בתורה. כמו כן, עיין ברשב"א בתחילת פרק מצוות חליצה. ותחשב. אולי הלכה למשה מסיני נכלל ב"רמיזה באו'."
** מטר... פרנסה –
עיין בתחילת המסכתא, שרבי יוחנן לא חילק בין מטר לפרנסה, אלא כללם לאחד. ותחשב.
* ט:
** ואתא מיטרא –
צריך ביאור למה לא רק התפלל שיבוא מטר איפה שהיה נצרך. ותחשב. כנראה, אף הוא היה צריך לעשות השתדלות שלו.  אבל, צריך ביאור למהלא רק השקה אותה, כיון שכבר היה שם. ותחשב.
* יא.
** על אחת כמה וכמה –
אין זה קו"ח ממש, שהרי כאן רק מונע את עצמו ממנו ליום אחד, משא"כ שם שמונע את עצמו לשלשים יום, לכל הפחות.
* יא:
** לשעות –
גמרא קורא לתענית זה של לילה "שעות," אף שמכוון לגמור את היום כיון שתחילתו לא היתה בקבלה, ואז לא עולה לתעניתו. נמצא שהוא רק מתענה (בקבלה) סוף היום. לכן, נחשב כתענית לשעות. גמ' מסיק שלא היתה קבלה טובה על שום חלק ממנו, ואינו אף תענית לשעות. ותחשב.
** ייסר בצלו –
מרש"י היה נראה לומר שעיקר החילוק הוא אם גורסים "בצילו" או לא. אבל, לשון הגמרא לא משמע כן. יותר נראה לומר שאם  גורסים "ייסר," אז אומר שצריך לאסור את עצמו. אבל, זה כבר אמור, שאומר,  "כל אדם שאסר את עצמו קודם לכן." אז, אם הוא מוסיף שהיה צריך להיות בתפילה, ניחא. אם לא, אז הוא קשה. דוחה גמ' שאומר "יאסר," שאז הוא אומר שהוא נאסר, שאומר הדין, ואז יכולים לפרש לשני הצדדים שאומר שהוא נאסר בתעניתו. ותחשב.
** בצלו –
לבד –
נמצא שרש"י סובר שאין שום חלק אחר מן התורה (חוץ, כמובן, מתורה שבכתב) נכתב בימי האמוראים חוץ ממגילת תענית. ותחשב.
* יג:
** אין הבוגרת –
שהביאה שתי שערות –
אין זה בוגרת, אלא נערה, אלא בוגרת הוא ששה חדשים אחרי זה. כנראה, ט"ס נפל ברש"י זה. (גם אפשר לומר שנערה ובוגרת של כאן שונה משל כל הש"ס, אבל לא נראה כן.)
** הא נערה –
שאינה ראויה –
לולי רש"י, היה אפשר לומר שאין הענין שאינה ראויה להנשא, אלא שאין כל כך צורך שתינשא, שיש לה זמן, ואם לא נשאת עכשיו, תינשא לאחר זמן. ותחשב.
** מאי שייר –
ולשיורי חדא –
במקום אחר צידדנו שענין של "תנא ושייר," שלא נאמר באחד, הוא שלא רוצים שישייר אחד, אבל יכולים לדחות אם יש רק אחד. אבל, אם יש שנים, לא מסתבר לדחות, וצריך לומר שאותו תנא שייר. ותחשב. רש"י זה מוכרח נגד אותו הצד. (אבל, בדר"כ צריך לעיין באותו צד, שצריך ביאור אז איך יקשה שלפי שיטה אחת שייר אחד. נראה שרצה לומר שידוע שאין תירוץ אחר חוץ מלומר שהוא לא צודק. אבל, כיון שמצאנו ששייר עוד אחד, מוכרח שתנא זה הוא משייר, ואז יש לומר שגם זה שייר. צריך לעיין בזה. ותחשב.)
* יד.
** קרי לה –
לשון זה משמע שרק חולקים בלשונות, אבל לא נראה כן בבריי'. ותחשב.
* יד:
** אברוונקי –
יום שממליכים אותו –
יש להעיר שלא כל בן מלך נעשה מלך.
** רשאי –
לבזות –
משמע שהוא רק אסור בפני הציבור. אם  נענה, יש לדון אם הותרה או דחויה. ותחשב.
** אא"כ –
יודעים –
לשון רש"י משמע שתולה אותו בידיעת הקהל, ולא בידיעת עצמו שיענה. ותחשב.
** לא הכל –
נענים –
מעניין שכאן רש"י פי' שלא הכל נענים, ולא שלא הכל רשאים. כנראה, רש"י סובר שכל אדם יכול לעשות כן, שלעולם אין איסור, ורק שלא תמיד נענה בזה. ותחשב.
