ב.
- כאשר זמם ולא לבנו- קצת צריך ביאור, שאם מה שזמם לעשות לבנו נכלל בזה, אז יחייב גם הוא כך. אם לא, אז קשה למה אומרים שבעינן כאשר זמם וליכא, שהרי הוא שפיר כאשר זמם. זה אומר שאם הוא בכלל הקרא, נעשה לו, ואם לאו, נעשה מה שאומר קרא. ותו"ת.
שוב הבנתי ש"לו ולא לזרעו" לא אומר ש"זמם לעשות לו" ממעט זה, אלא "ועשיתם לו" ממעט זה, שאין לתת לו העונש, שהוא ניתן לבניו. ויש לדון ל"ל אומרים שמה שהוא בכלל "לו" זה הוא בכלל "לו" זה. ותו"ת.
- ועוד- מאי קא בעי תנא כיצד- לכאורה, ר"ל למה יקשה אותו שני פעמים.
- תנא התם קאי- נראה שאולי תנא עשה כן בדווקא, כדי שבסוף מסכתא אחד נזכור איזה מסתכא בא אחריו. אז, יותר קל לומר אותו בעל פה.
- לו ולא לזרעו- יש לדון אם דורש מייתור או ממשמעות.
ב:
- ומה הסוקל- א"צ כל זה; יש לומר ומה הסוקל לא מת בלי התראה, הבא לסקול…, וממילא נפטור כל עד זומם כיון שאי אפשר להתרות. אפשר לומר שלא מקשה מן התורה, אלא מקשה שיודעים שאין הדין כן. אם כן, אולי היה אפשר לומר שאם תורה גילה שאינו כן, הרי גילה, ואז צריך לומר שאין אומרים קל וחומר זה. ותו"ת.
- כפרה- מעוררים שמשמע מכאן שגלות הוא כדי לכפר, ולא כדי להציל. ראשון, היה אפשר לומר שעשה תורה צורך להצלה כדי לכפר. גם יש לומר שכל זה רק בדיחוי של גמרא, שאומר שאי אפשר להוכיח מזה, שאולי הוא כדי לכפר. יש לדון, שלכאורה, צריך סברה כעין מה שאומר גמרא לחלק בין שוגג למזיד למסקנא. ותחשב.
- מאי טעמייהו דרבנן- יש לדון אם צריך זה בלי רב פפא, שאולי אז יש לומר שהבינו בסיבת החיוב מסברתם, ואז ידעו מה חייב. ותו"ת.
- מזדבני- זה שייך לנדון של איזה קרק’ נחשבים כשאומרים שדברים שווים (ר"ל, הוא קרק’ לנגד אדם, ובכל זמן יש לדון אם מהפכים איזה אדם הוא). ותו"ת.
ג.
- העדתי- יש לדון אם ייחשב עמנו הייתם, שלא היה שם, והיה עם עצמו במקום חוץ משם. ויש לדון, שצריך לומר שטוען שלא היה שם, ולא שרק לא קרה כלל. ותו"ת. ויש לדון, שאולי המקום נקרא על שם מקום שבו קרה אותו מקרה. אם לא קרה, נמצא שלא היה באותו מקום. ויש לדון.
- איהו נמי לא מחייב קמ"ל- יש לדון למה אין שום הוה אמינא לחייב שניהם. צריך לומר שיותר קל ללכת נגד עדות אחד מלחייב אדם על פי מה שאינו נאמן (הוא רק עדות של אחד).
- מעידים אנו- אי אפשר לומר שנחייב אותם לתת כתובה, ואם מגרש את אשתו, יחזר להם את הממון, שהרי, לא דנים מהו הרע שהיה יוצא ממעשה שלהם, אלא דנים מה זממו לעשות. זה מעניין, ולכאורה, הוא שייך לביאור הרע שעשו, שצריך לומר שתלה ה’ ממש במה שזממו, ולא באיזה רע היה קיים. ותו"ת.
- כיצד שמים- זכותו גדול- על שם מש"א גמרא, “בוצינא טוב מקרה.”
- אמר ר"פ- יש להעיר שיש כמה שינויים בין פשטים אלו, ולכאורה, לא מוכרח להיות תלויים על הדדי. ויל"ד.
ג:
- הורידו את המקוה- עבמש"כ. גם היה אפשר לומר שהורידו ר"ל להוריד המים (להוציא את המים, עד שהורד המים) כיון שהוא פסול, ואין צורך במים (ואולי אף יכשיל בני אדם שחושבים שהוא כשר).
- לא פסלוהו- מעניין שאותו פסול הוא מדרבנן. ויש להעיר שלכאורה, יהיה ביטול מדאורייתא, ויהיו נחשבים כמים, ואז יהיה פסול שאיבה. כדי לדחות את זה, היה צריך לומר שאין זה פסול כי אם מדרבנן. ואולי הולכםי בתר חזותא וכדו’ אף מדאו’ (אינני זוכר).
ד.
- אמר"י- אגב, נראה שרב יוסף חלה ושכח ונעשה סומא (שמסתמא, שניהם באו מאותו חולי) כשהיה כבר ראש ישיבה. לכאורה, לא היה קודם שהיה רבה ראש ישיבה, שרצה למנותו ראש ישיבה, וצריך לומר שעדיין זכר לימודו. לא היה כשרבה היה ראש ישיבה, שאומר גמרא שאףלא היה צריך רופא (ודע שיש פירושים שונים באותו גמרא). אם כן, צריך להיות כשהיה ראש ישיבה).
- רב יוסף- נמצא שהיה רב יוסף תלמיד של רב יהודה.
ד:
- שמעתי מאת ר.א.ש. שמאירי כ’ שרבי מאיר סבר שלוקים על לאו שאין בו מעשה. אמר לי כשהייתי בן עשרים שלפני שבע שנים הקשיתי לו קושיה על זה, והזכיר לו שהיה מזכיר אותו לבחורים בשמי.
נראה שהקושיה הוא שאי אפשר שרבי מאיר סובר כן, ששיטתו מיוחד על מה שסובר כרבי עקיבא, אבל שיטת רבי יהודה (שלאו שאין בו מעשה לוקים עליו) מיוסד על מה שלא סובר כרבי עקיבא. אם כן, אי אפשר לר"מ לסבור כר"י.
- אין צריכים התראה- העיר לי מ.ש. שלכאורה, אי אפשר להתרות למוציא שם רע, שלא יודעים שמכוון כלל לעשות כן עד שבא לבית דין ואומר כן; אבל גמרא כאן שלא עושה צד השווה משמע שצריך התראה. צריך ביאור.
- לאזהרה- מעניין שצריך אזהרה חלוקה למלקות מלדין כאשר זמם. ותחשב.
ה:
- הוחזקה זו- לכאורה, זה מוכיח כמש"א תוס’ שרע הוא לפסוק על פי עדים שקרנים או כדומה, אף אם הדין נכון. לכאורה, הראיה הוא שאם נניח שהיתה לה עדים כל הזמן, אין רע בהבאת עדים פסולים, שהרי בין כך ובין כך היא נכונה. אז, לא הוחזקה. ויש לדון, שאולי יש עדיין רע בעדים פסולים, אף אם אין רע בפסק בית דין. ותחשב.
- עונש שמענו אזהרה מניין- בדרך כלל, כשאומר כן גמרא, לא אומר מה שאומר גמרא כאן, אלא אומר שמצאנו עונש, אבל לא מצאנו אזהרה. אפשר שנקט לשון זה אגב אותם לשונות.
- אראה- וגמרא- היה אפשר לומר שר"י הפכו לברכה, אבל עדיין היה אומר מה שרצה לומר כיון שפשוט מה היתה כוונתו.
- אמר ליה- לפני שבע שנים, הערתי שקצת מוזר שדחו אמוראים בתראי את דברי תנא קדמאי, שמה להם בזה, שקרה לפני כמה וכמה שנים. ויש לדון.
ו.
- במקיימי דבר- לכאורה, ר"ל במי שבא ומעיד, ולא במי שרק ראה, ולא העיד. זה גם מבאר ל"ל מצילים עד על פי ספק שמא ראה קרוב. ותו"ת.
ו:
- השונא- לכאורה, יש שני סיבות שיפטור:
1. לא כיוון להרוג.
2. לא יודע שהוא אסור להרוג.
לכאורה, מה שהוא שונה רק דוחה הראשון, ולא השני. יש לומר שלא חוששים לשני. ק"ק, שאומר שאשת חבר לא צריכה התראה, ולכאורה, שם הענין הוא השני.
ז.
- מפני זכותה- עיין במה שבאר. לול"ז, היה נראה לומר (ואולי זהו הפ’ במש"א) שהוא מחמת "אוירא דא"י מחכים.”
- אף הם מרבים- לכאורה, אומר שאילו עשו כן, היו מרבים שופכי דמים בישראל. היה אפשר לומר שבית דין מרבה שופכי דמים, ויש להם להרוג יותר. גם יש לומר שאילו הוא היה בבית דין, היה אף מרבה שופכי דמים, והוא שלא היה הורג, אף אם זה גורם שיותר בני אדם יהרגו, שרק יגרום. ותו"ת.
ז:
- לאחריו- קצת צריך ביאור למה מבאר אותו כן, שהיה לו לומר ירידה ועלייה. ותו"ת.
- הא דאיתלע- עיין במה שבאר. היה אפשר לומר שכשאדם בא למדרגה, לא כופפו למטה מיד, אלא רק כשהוא הולך ממנו, שאז דוחפו ברגלו כדי לעלות. אולי אם התליע, לא יגיע לזה, אלא יפול מיד. רק אם לא התליע יבוא לזה, ונמצא שהוא דרך ירידה.
ח.
- אף על גב דגמיר- קצת צריך ביאור, שלכאורה, אם לא היה צריך שום, לא היה מצווה. אולי ר"ל שלא שייך שלא צריך כלום. יש לדון איך רואים זה מאותו קרא. ותחשב.
- מה יער- צריך ביאור איך יודעים כן. אולי אין שום מצווה שיכוף אדם לכנס ליער. יש לדון אם זה אמת.
ט.
- אומר מותר- יש להעיר שמגמרא זה יוצא שאדם נחשב אומר מותר אם רק טועה מהו החפץ (אם היא נשואה), ולא רק אם טעוה בדין.
ט:
- נביא- יש להעיר שלכאורה, אם היה לאבימלך להבין, לא היה מה שעשה אברהם כל כך חכם, שלא יציל אותו. ותו"ת.
- בלי דעת- ואם תאמר איך ממעט סומא, שיש לו דעת. ויש לומר שזה לא אומר שאין בו דעת, אלא אינו יודע (מה שצריך לדעת כאן), אבל בציור רגיל, יודע. סומא בכל זמן לא יודע, שלא רואה, ואז פשוט שלא יידע על המתת אחר. ויש לדון.
י.
- יש לדון למה נבחר ראובן כיון שאומר גמ’ בסוטה שמי שמתחיל בדבר ולא גומרו הוא רע. ותו"ת.
י:
- בשני בני אדם- ק"ק, שגמרא אומר שמי שחייב מיתה בא לו דינו (כארבע מיתות), וזה דומה לסקילה, לכאורה, ואינו דינו. ותו"ת. אז, היה למי שצריך לגלות ליפול על מי שחייב סקילה, ומי שחייב מיתה למות באופן אחר.
יא.
- חביבי- אחי אבא- גם היה אחי אמא. יש לדון ל"ל מזכיר זה. אולי לא מפני זה נקרא חביבי. יש לדון מהי"ת.
- נמצא כאן מחלקת אם כשלומדים היקש, לומדים רק דינים הכתובים או אף הלכות למשה מסיני. יש לדון אם חולקים רק כאן או בכל מקום (ר"ל, שאולי יש לחלק על פי כמה מסתבר הוא לומר אותם דינים).
- ההוא סבא- עיין בתוס’ חולין (ו.). אם כן, היה אליהו הנביא בפירקיה דרבא. אולי אף כאן, אינו כן (כמו שמביא שם). גם יש להוסיף שאולי זה רק אם לא מוסיף מי היה (כמו כאן, שאומר שהיה אחד מתלמידי רבא).
- על תנאי- צריך ביאור מהו החילוק בין "על תנאי,” ו"על חנם.”
יא:
- לפרוקי קושיה- עיין בסוטה שאומר שלא ידע לאסוקי שמעתתא אליבא דהילכתא. אולי שני הענינים אחד, ואולי לא ידע שניהם, אף שהם חלוקים, ואמר אחד כאן ואחר כאן (אולי כדי להראות שניהם). ותחשב.
- כתוב בגמ’ שלי: “אפשר לתלות במח’ שמואל ורי"נ בקדושין.” איני ידוע מה זה אומר.
יב.
- מה תחילתו- ק"ק למד"א שנהרג אף בהליכה לבית דין. אולי עדיין  היה יותר חמור, ששם יש שני ת"ח עמו. אף זה מחלקת. על"ע.
יב:
- באילן- אין צריכים לזה, שהיה אפשר לומר עדיין כת’ ראשון שאמר, ורק לומר כן לת’ סתירת ברייתות אחרונות.
יג:
- מעניין לפטור מחיוב מלקות מחמת חיוב כרת. יש לומר שמלקות יותר חמור, שאי אפשר לשוב. קשה, שיש כמה גמ’ שלא מניחים כן. אולי כולם כרבנן שאומרים שמלקים. ותחשב. גם אפשר שאינו כל כך קשה אם נפטר מן הכי חמור. ותחשב. ועיין בכתובות, שלא פשוט לו, אם חייב ממון במלקות או להיפך, אם חייב הכי חמור.
- לקרבן- ר"ל, אף שא"צ אזהרה לכרת, צריכים לקרבן, ואז הוא לאו שניתן לאזהרת קרבן.
- לקרבן- היה אפשר לדון אם עובר על כלום אם עושה עבירה בשוגג. לכאורה, אי אפשר לומר שיש ציווי בשעת מעשה, שבאותו שעה לא יודע על הציווי, ואיך נצווה מי שלא יודע בציווי. אולי הציווי הוא שיהיה תמיד חושב אם עובר על זה. גם יש לומר שהוא שלא ישכח (ושעת שכחה הוא שעת האיסור). היה אפשר לומר נגד אלו, שאינו נגד שום ציווי, אלא שיודעים שהוא רע לעשות, כיון שיודעים שבורא רע שהיה רוצה ה’ לצוות לו שלא לברא. לכאורה, גמרא זה מוכרח נגד צד זה, שאומר שהאזהרה על זה. ויש לדון, שאולי ר"ל שאזהרה עושה שה’ מגלה שאינו רוצה בלאו זה, והיה מזהיר, ולכן יש חיוב קרבן. ותו"ת.
יד:
- ברדלא- נראה שצריך להזכיר כן כיון שבדרך כלל, מביא אבא כהן ברדלאה. אולי הוה אמינא שאין זה שמו, אלא שום הוספה על שמו (מקומו או כדומה), וזה אותו איש. יש לדון איזה נקודה דוחה רש"י כאן.
טו.
- כתיבא ותנינא- נמצא שאומרים זה (אף) אם רק מביאים ראיה משניהם ביחד. יש לציין לגמרא בבא קמא (סו). ותחשב שם אם יש ראיה מאחד בפנ"ע.
טו:
לטעמייהו- יש להעיר ששם היה רק בשיטת ר"י. אולי גמרא אומר שהקימו ר"י כן מפני שרצו שלא יחלוק רבי יהודה על שיטתם. ותו"ת. גם יש לומר שמניחים שיסברו כר"י. יש לדון למה.
טז:
- אין צריך- אם הודיע להם ששניהם במיתה, ק"ק ל"ל שהה מלגזור עד שראה אם קבלו או לא. אולי שהה, ולא שינו, ולא הזכיר רש"י את זה. דחוק.
יז.
- כל שהוא- לכאורה, הראיה הוא ממה שאמר ששיעור הוא רק לכזית, ולא שהשיעור הוא אף אם אינו בריה. גם יש לומר שהראיה הוא שאמר שהשיעור הוא לקרבן, והרי במה שמחייב קרבן, היה השיעור אף למלקות, שהרי אין אחד מהם שיש בו בריה פחות מכזית. יש לחשוב ולעיין אם זה נכון.
יז:
- דלמאי דס"ל- עדיין צריך ביאור איך יכול לעשות כן, ול"ל נדרוש באופן אחר שאינו כל כך מחודש.
- איסורא בעלמא- נמצא שהוא אסור, אם מזהיר מן הדין, ורק לא נענש.
יט.
- ולא מצי אמר- ק"ק ל"ל אומרים שאם אינו ראוי לבילה….
יט:
- לא בערתי ממנו- לכאורה, אין קרא זה חלק מן המקור, שלקמן בברייתא וגמרא יביא מקור.
כ:
- רבי יהודה בר חביבא- אולי היה בן של רבי חייא (יודעים שהיה לו בן בשם רבי יהודה, וקרא לו רב לר"ח חביבי)
- ואותבינהו- בביאור למה אינו התראת ספק, יש להעיר שצריך ביאור זה בכ"מ, ולא יותר כאן. הוא ביאור נאה, אבל אינו כל כך שייך לכאן יותר מבמק"א. אינו כל כך קשה, שלא היה ריב"ן כותב פ’ על ש"ס חוץ מזה, ואולי, אז, כתב בו כל היסודות שרצה להודיע.
- במסייע- ק"ק לל"א שמסייע אין בו ממש. יש לומר שיש איסור לסייע, ואז, לענין אותו איסור, יש בו ממש. ותו"ת.
- דאמר לך- לא הבנתי כל כך ביאור ראשון.
כא.
- מחוי- עיין בגמ’ יומא שמפ’ למה לפעמים הראו דבר, ולא אמרו. י"ל שא"צ זה כאן, שכאן אולי יותר קל להראות מלבאר. ותו"ת.
- ביד- שאין עבודתה- יש לדון מהיכי תיתי. גם ק"ק ל"ל מנה אותו עם שאר עבודות שהם כך (כגון שחיטה) בסנהדרין. וצר"ב.
כב.
- אלא הכא- אז, אפשר להק’ ל"ל יחייב עוד מחמת עצי אשירה, ונוקים…, כשאר ק’ גמ’ כאן.
כב:
- בידי אדם- קשה, שאף זה בידי אדם. אולי צר"ל ביד מי שמתחייב עליו. ותחשב.
כג.
- קלה- יש לדון מהיכי תיתי שהוא ברעי, ולא במים, שלכאורה, רק ייתלה במחלקת לעיל.
כג:
- ה"נ קראי- יש לדון, ששם אין חולק, ואז בהכרח דורשים קראי, כיון שהם מסתבר. ותו"ת.
- שאילת- לכאורה, רק רואים שמותר. אולי לא היה מותר אילו לא היה דבר טוב שמקיים בו. עדיין, היה אפשר לומר שאותו טוב שקול לרע שבא מזה. אם כן, עדיין יהיה רשות.
- בית שמאי- ואם תאמר אולי שם היו הלל ושמאי חיים. יש לומר שאילו כן היו צריכים להיות חיים זמן רב מאד[fn:1]. ויש לדון, שלא יודעים מתי חי "בית הלל" ו"בית שמאי,” שאולי היו רק בזמן זוגות. גם יש לומר שאם כן יחלקו ביותר משלש מקומות (עיין בשבת).[fn:2]
כד.
- הללכו כושיים- לכאורה, כתבו את זה מחמת הצינזו"ר. גם יש לומר כמש"א גמ’ שנקראים כושים כיון שהם משונים במעשיהם, שהם רעים ביותר.
* Footnotes
[fn:1] צריך לעיין בגמרא בתחילת סנהדרין (כן אני חושב) שמדבר במיתת הלל, שאולי נלמד מזה.
[fn:2] אין לדחות שכיון שיש מי שחולק עם כל אחד, אינו נמנה, כמו ציור שבפרק שני של חגיגה, שנראה שאין תלמידם מן המנין, ששם גם כן, חושב אני שחלקו אף תלמידם. אולי אין הנחה זה נכונה; וצריך לעיין שם.
