** פרק שני [fn:1] משנה   [fn:2]
הַבְּצָלִים הַסָּרִיסִים[fn:3], וּפוֹל הַמִּצְרִי, שֶׁמָּנַע מֵהֶם מַיִם שְׁלֹשִׁים יוֹם לִפְנֵי רֹאשׁ הַשָּׁנָה[fn:4], מִתְעַשְּׂרִין לְשֶׁעָבַר, וּמֻתָּרִים בַּשְּׁבִיעִית, וְאִם לָאו, אֲסוּרִים בַּשְּׁבִיעִית, וּמִתְעַשְּׂרִין לְשָׁנָה הַבָּאָה. [fn:5]  וְשֶׁל בַּעַל שֶׁמָּנַע מֵהֶם מַיִם שְׁתֵּי עוֹנוֹת[fn:6], דִּבְרֵי רַבִּי מֵאִיר.[fn:7] וַחֲכָמִים אוֹמְרִים, שָׁלֹשׁ[fn:8]:
** משנה   [fn:9]
הַדְּלוּעִין שֶׁקִּיְּמָן לְזֶרַע, אִם הִקְשׁוּ לִפְנֵי רֹאשׁ הַשָּׁנָה [fn:10]ונִפְסְלוּ מֵאֹכֶל אָדָם, מֻתָּר לְקַיְּמָן בַּשְּׁבִיעִית[fn:11]. וְאִם לָאו, אָסוּר לְקַיְּמָן בַּשְּׁבִיעִית. הַתְּמָרוֹת שֶׁלָּהֶם[fn:12], אֲסוּרוֹת בַּשְּׁבִיעִית. וּמַרְבִּיצִין[fn:13] בְּעָפָר לָבָן[fn:14], דִּבְרֵי רַבִּי שִׁמְעוֹן[fn:15], רַבִּי אֱלִיעֶזֶר בֶּן יַעֲקֹב אוֹסֵר. מְמָרְסִין[fn:16] בָּאֹרֶז בַּשְּׁבִיעִית, רַבִּי שִׁמְעוֹן אוֹמֵר, אֲבָל אֵין מְכַסְּחִין[fn:17]:
** פרק שלישי [fn:18] משנה א [fn:19]
[fn:20]מֵאֵימָתַי מוֹצִיאִין זְבָלִים לְאַשְׁפַּתּוֹת[fn:21], מִשֶּׁיִּפְסְקוּ עוֹבְדֵי עֲבוֹדָה[fn:22], דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, מִשֶּׁיִּבַשׁ הַמָּתוֹק[fn:23]. רַבִּי יוֹסֵי אוֹמֵר, מִשֶּׁיִּקְשֹׁר[fn:24][fn:25]:
** משנה ב [fn:26]
עַד כַּמָּה[fn:27] מְזַבְּלִין[fn:28], עַד שָׁלֹשׁ שָׁלֹשׁ אַשְׁפַּתּוֹת לְבֵית סְאָה שֶׁל עֶשֶׂר עֶשֶׂר מַשְׁפֵּלוֹת שֶׁל לֶתֶךְ לֶתֶךְ. מוֹסִיפִין עַל הַמַּשְׁפֵּלוֹת[fn:29][fn:30], וְאֵין מוֹסִיפִין עַל הָאַשְׁפַּתּוֹת[fn:31][fn:32]. רַבִּי שִׁמְעוֹן אוֹמֵר, אַף עַל הָאַשְׁפַּתּוֹת[fn:33]:
** משנה ג [fn:34]
עוֹשֶׂה אָדָם אֶת שָׂדֵהוּ שָׁלֹשׁ שָׁלֹשׁ אַשְׁפַּתּוֹת לְבֵית סְאָה. יָתֵר מִכָּאן, מַחֲצִיב[fn:35], דִּבְרֵי רַבִּי שִׁמְעוֹן[fn:36]. וַחֲכָמִים אוֹסְרִין[fn:37], עַד שֶׁיַּעֲמִיק שְׁלֹשָׁה, אוֹ עַד שֶׁיַּגְבִּיהַּ שְׁלֹשָׁה[fn:38]. עוֹשֶׂה אָדָם אֶת זִבְלוֹ אוֹצָר[fn:39]. רַבִּי מֵאִיר אוֹסֵר[fn:40], עַד שֶׁיַּעֲמִיק שְׁלֹשָׁה, אוֹ עַד שֶׁיַּגְבִּיהַּ שְׁלֹשָׁה. הָיָה לוֹ דָבָר מֻעָט[fn:41], מוֹסִיף עָלָיו וְהוֹלֵךְ. רַבִּי אֶלְעָזָר בֶּן עֲזַרְיָה אוֹסֵר, עַד שֶׁיַּעֲמִיק שְׁלֹשָׁה, אוֹ עַד שֶׁיַּגְבִּיהַּ שְׁלֹשָׁה, אוֹ עַד שֶׁיִּתֵּן עַל הַסָּלַע[fn:42]:
** משנה ד [fn:43]
הַמְדַיֵּר[fn:44] אֶת שָׂדֵהוּ, עוֹשֶׂה סַהַר לְבֵית סָאתַיִם[fn:45], עוֹקֵר שָׁלֹשׁ רוּחוֹת וּמַנִּיחַ אֶת הָאֶמְצָעִית. נִמְצָא מְדַיֵּר בֵּית אַרְבַּעַת סְאִין. רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, בֵּית שְׁמוֹנַת סְאִין[fn:46]. הָיְתָה כָל שָׂדֵהוּ בֵּית אַרְבַּעַת סְאִין, מְשַׁיֵּר מִמֶּנָּה מִקְצָת, מִפְּנֵי מַרְאִית הָעַיִן, וּמוֹצִיא מִן הַסַּהַר[fn:47] וְנוֹתֵן לְתוֹךְ שָׂדֵהוּ[fn:48] כְּדֶרֶךְ הַמְזַבְּלִין[fn:49]:
** משנה ה [fn:50]
לֹא יִפְתַּח[fn:51] אָדָם מַחְצֵב[fn:52] בַּתְּחִלָּה לְתוֹךְ שָׂדֵהוּ[fn:53], עַד שֶׁיִּהְיוּ בוֹ שָׁלֹשׁ מוּרְבִּיּוֹת[fn:54], שֶׁהֵם שָׁלֹשׁ עַל שָׁלֹשׁ עַל רוּם שָׁלֹשׁ[fn:55], שִׁעוּרָן עֶשְׂרִים וְשֶׁבַע אֲבָנִים[fn:56][fn:57]:
** משנה ו [fn:58]
גָּדֵר שֶׁיֶּשׁ בּוֹ עֶשֶׂר אֲבָנִים[fn:59] שֶׁל מַשְּׂאוֹי שְׁנַיִם שְׁנַיִם[fn:60], הֲרֵי אֵלּוּ יִנָּטֵלוּ[fn:61][fn:62]. שִׁעוּר גָּדֵר, עֲשָׂרָה טְפָחִים. פָּחוֹת מִיכַּן, מְחַצֵּב וְגוֹמְמוֹ עַד פָּחוֹת מֵהָאָרֶץ טֶפַח[fn:63]. בַּמֶּה דְבָרִים אֲמוּרִים, מִתּוֹךְ שֶׁלּוֹ, אֲבָל מִתּוֹךְ שֶׁל חֲבֵרוֹ, מַה שֶּׁהוּא רוֹצֶה, יִטֹּל[fn:64]. בַּמֶּה דְבָרִים אֲמוּרִים, בִּזְמַן שֶׁלֹא הִתְחִיל בּוֹ מֵעֶרֶב שְׁבִיעִית. אֲבָל אִם הִתְחִיל בּוֹ מֵעֶרֶב שְׁבִיעִית, מַה שֶּׁהוּא רוֹצֶה, נוֹטֵל[fn:65]:
** משנה ז [fn:66]
אֲבָנִים שֶׁזִּעְזְעָתַן הַמַּחֲרֵשָׁה[fn:67], אוֹ שֶׁהָיוּ מְכֻסּוֹת וְנִתְגַּלּוּ[fn:68], אִם יֵשׁ בָּהֶם שְׁתַּיִם שֶׁל מַשְּׂאוֹי שְׁנַיִם שְׁנַיִם[fn:69], הֲרֵי אֵלּוּ יִנָּטֵלוּ[fn:70]. הַמְסַקֵּל אֶת שָׂדֵהוּ, נוֹטֵל אֶת הָעֶלְיוֹנוֹת, וּמַנִּיחַ אֶת הַנּוֹגְעוֹת בָּאָרֶץ[fn:71]. וְכֵן גַּרְגֵּר שֶׁל צְרוֹרוֹת[fn:72] אוֹ גַל שֶׁל אֲבָנִים, נוֹטֵל אֶת הָעֶלְיוֹנוֹת, וּמַנִּיחַ אֶת הַנּוֹגְעוֹת בָּאָרֶץ. אִם יֶשׁ תַּחְתֵּיהֶן סֶלַע אוֹ קַשׁ[fn:73], הֲרֵי אֵלּוּ יִנָּטֵלוּ:
** משנה ח [fn:74]
אֵין בּוֹנִין מַדְרֵגוֹת[fn:75] עַל פִּי הַגֵּאָיוֹת עֶרֶב שְׁבִיעִית מִשֶּׁפָּסְקוּ הַגְּשָׁמִים, מִפְּנֵי שֶׁהוּא מְתַקְּנָן לַשְּׁבִיעִית[fn:76]. אֲבָל בּוֹנֶה הוּא בַּשְּׁבִיעִית מִשֶּׁפָּסְקוּ גְּשָׁמִים, מִפְּנֵי שֶׁהוּא מְתַקְּנָן לְמוֹצָאֵי שְׁבִיעִית. וְלֹא יִסְמֹךְ בְּעָפָר[fn:77], אֲבָל עוֹשֶׂה הוּא חַיִץ[fn:78]. כָּל אֶבֶן שֶׁהוּא יָכוֹל לִפְשֹׁט אֶת יָדוֹ וְלִטְּלָהּ[fn:79], הֲרֵי זוֹ תִּנָּטֵל[fn:80]:
** משנה ט [fn:81]
אַבְנֵי כָתֵף[fn:82], בָּאוֹת מִכָּל מָקוֹם[fn:83]. וְהַקַּבְּלָן, מֵבִיא מִכָּל מָקוֹם[fn:84]. וְאֵלּוּ הֵם אַבְנֵי כָתֵף[fn:85], כָּל שֶׁאֵינָהּ יְכוֹלָה לְהִנָּטֵל בְּאַחַת יָד[fn:86], דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יוֹסֵי אוֹמֵר, אַבְנֵי כָתֵף כִּשְׁמָן[fn:87], כָּל שֶׁהֵן נִטָּלוֹת שְׁתַּיִם שָׁלֹשׁ עַל הַכָּתֵף[fn:88]:
** משנה י [fn:89]
הַבּוֹנֶה גָדֵר בֵּינוֹ וּבֵין רְשׁוּת הָרַבִּים[fn:90], מֻתָּר לְהַעֲמִיק עַד הַסֶּלַע. מַה יַּעֲשֶׂה בֶּעָפָר, צוֹבְרוֹ בִּרְשׁוּת הָרַבִּים וּמְתַקְּנוֹ, דִּבְרֵי רַבִּי יְהוֹשֻׁעַ. רַבִּי עֲקִיבָא אוֹמֵר, כְּדֶרֶךְ שֶׁאֵין מְקַלְקְלִין בִּרְשׁוּת הָרַבִּים, כָּךְ לֹא יְתַקֵּנוּ[fn:91]. מַה יַּעֲשֶׂה בֶּעָפָר, צוֹבְרוֹ בְּתוֹךְ שָׂדֵהוּ כְּדֶרֶךְ הַמְזַבְּלִין. וְכֵן הַחוֹפֵר בּוֹר וְשִׁיחַ וּמְעָרָה:
--------------------------------------------------------------------------------
פרק ד
--------------------------------------------------------------------------------
פרק ד - משנה א
בָּרִאשׁוֹנָה הָיוּ אוֹמְרִים, מְלַקֵּט אָדָם עֵצִים וַאֲבָנִים וַעֲשָׂבִים מִתּוֹךְ שֶׁלּוֹ, כְּדֶרֶךְ שֶׁהוּא מְלַקֵּט מִתּוֹךְ שֶׁל חֲבֵרוֹ, אֶת הַגַּס הַגָּס. מִשֶּׁרַבּוּ עוֹבְרֵי עֲבֵרָה, הִתְקִינוּ שֶׁיְּהֵא זֶה מְלַקֵּט מִתּוֹךְ שֶׁל זֶה, וְזֶה מְלַקֵּט מִתּוֹךְ שֶׁל זֶה, שֶׁלֹּא בְטוֹבָה, וְאֵין צָרִיךְ לוֹמַר שֶׁיְּקַצֵּץ לָהֶם מְזוֹנוֹת:
--------------------------------------------------------------------------------
פרק ד - משנה ב
שָׂדֶה שֶׁנִּתְקַוְּצָה, תִּזָּרַע בְּמוֹצָאֵי שְׁבִיעִית. שֶׁנִּטַּיְּבָה אוֹ שֶׁנִּדַּיְּרָה, לֹא תִזָּרַע בְּמוֹצָאֵי שְׁבִיעִית. שָׂדֶה שֶׁנִּטַּיְּבָה, בֵּית שַׁמַּאי אוֹמְרִים, אֵין אוֹכְלִין פֵּרוֹתֶיהָ בַּשְּׁבִיעִית, וּבֵית הִלֵּל אוֹמְרִים, אוֹכְלִין. בֵּית שַׁמַּאי אוֹמְרִים, אֵין אוֹכְלִין פֵּרוֹת שְׁבִיעִית בְּטוֹבָה, וּבֵית הִלֵּל אוֹמְרִים, אוֹכְלִין בְּטוֹבָה וְשֶׁלֹּא בְטוֹבָה. רַבִּי יְהוּדָה אוֹמֵר, חִלּוּף הַדְּבָרִים, זוֹ מִקֻּלֵּי בֵית שַׁמַּאי וּמֵחֻמְרֵי בֵית הִלֵּל:
--------------------------------------------------------------------------------
פרק ד - משנה ג
חוֹכְרִין נִירִין מִן הַנָּכְרִים בַּשְּׁבִיעִית, אֲבָל לֹא מִיִּשְׂרָאֵל. וּמַחֲזִיקִין יְדֵי נָכְרִים בַּשְּׁבִיעִית, אֲבָל לֹא יְדֵי יִשְׂרָאֵל. וְשׁוֹאֲלִין בִּשְׁלוֹמָן, מִפְּנֵי דַרְכֵי שָׁלוֹם:
--------------------------------------------------------------------------------
פרק ד - משנה ד
הַמֵּדֵל בַּזֵּיתִים, בֵּית שַׁמַּאי אוֹמְרִים, יָגוֹם. וּבֵית הִלֵּל אוֹמְרִים, יְשָׁרֵשׁ. וּמוֹדִים בְּמַחֲלִיק, עַד שֶׁיָּגוֹם. אֵיזֶה הוּא הַמֵּדֵל, אֶחָד אוֹ שְׁנַיִם. הַמַּחֲלִיק, שְׁלֹשָׁה, זֶה בְצַד זֶה. בַּמֶּה דְבָרִים אֲמוּרִים, מִתּוֹךְ שֶׁלּוֹ, אֲבָל מִתּוֹךְ שֶׁל חֲבֵרוֹ, אַף הַמַּחֲלִיק, יְשָׁרֵשׁ:
--------------------------------------------------------------------------------
פרק ד - משנה ה
הַמַּבְקִיעַ {ה} בַּזַּיִת, לֹא יְחַפֵּהוּ בְעָפָר, אֲבָל מְכַסֶּה הוּא בַּאֲבָנִים אוֹ בְקַשׁ. הַקּוֹצֵץ קוֹרוֹת שִׁקְמָה, לֹא יְחַפֵּהוּ בְעָפָר, אֲבָל מְכַסֶּה הוּא בַּאֲבָנִים אוֹ בְקַשׁ. אֵין קוֹצְצִין בְּתוּלַת שִׁקְמָה בַּשְּׁבִיעִית, מִפְּנֵי שֶׁהִיא עֲבוֹדָה. רַבִּי יְהוּדָה אוֹמֵר {ו}, כְּדַרְכָּהּ, אָסוּר, אֶלָּא אוֹ מַגְבִּיהַּ עֲשָׂרָה טְפָחִים, אוֹ גוֹמֵם מֵעַל הָאָרֶץ:
--------------------------------------------------------------------------------
פרק ד - משנה ו
הַמְזַנֵּב {ז} בִּגְפָנִים וְהַקּוֹצֵץ קָנִים, רַבִּי יוֹסֵי הַגְּלִילִי אוֹמֵר, יַרְחִיק טֶפַח. רַבִּי עֲקִיבָא אוֹמֵר, קוֹצֵץ כְּדַרְכּוֹ, בַּקַּרְדֹּם אוֹ בַמַּגָּל, וּבַמְּגֵרָה, וּבְכָל מַה שֶׁיִּרְצֶה. אִילָן שֶׁנִּפְשַׁח, קוֹשְׁרִין אוֹתוֹ בַּשְּׁבִיעִית, לֹא שֶׁיַּעֲלֶה, אֶלָּא שֶׁלֹּא יוֹסִיף:
--------------------------------------------------------------------------------
פרק ד - משנה ז
מֵאֵימָתַי אוֹכְלִין פֵּרוֹת הָאִילָן בַּשְּׁבִיעִית, הַפַּגִּים מִשֶּׁיַּזְרִיחוּ, אוֹכֵל בָּהֶם פִּתּוֹ בַּשָּׂדֶה. בִּחֲלוּ, כּוֹנֵס לְתוֹךְ בֵּיתוֹ. וְכֵן כַּיּוֹצֵא בָהֶם בִּשְׁאָר שְׁנֵי שָׁבוּעַ, חַיָּב בַּמַּעַשְׂרוֹת {ט}:
--------------------------------------------------------------------------------
פרק ד - משנה ח
הַבֹּסֶר, מִשֶּׁהֵבִיא מַיִם, אוֹכֵל בּוֹ פִּתּוֹ בַּשָּׂדֶה. הִבְאִישׁ, כּוֹנֵס לְתוֹךְ בֵּיתוֹ. וְכֵן כַּיּוֹצֵא בוֹ בִּשְׁאָר שְׁנֵי שָׁבוּעַ, חַיָּב בְּמַעַשְׂרוֹת:
--------------------------------------------------------------------------------
פרק ד - משנה ט
זֵיתִים, מִשֶּׁיַּכְנִיסוּ רְבִיעִית לִסְאָה, פּוֹצֵעַ וְאוֹכֵל בַּשָּׂדֶה. הִכְנִיסוּ חֲצִי לֹג, כּוֹתֵשׁ וְסָךְ בַּשָּׂדֶה. הִכְנִיסוּ שְׁלִישׁ, כּוֹתֵשׁ בַּשָּׂדֶה {יא} וְכוֹנֵס לְתוֹךְ בֵּיתוֹ. וְכֵן כַּיּוֹצֵא בָהֶם בִּשְׁאָר שְׁנֵי שָׁבוּעַ, חַיָּבִים בְּמַעַשְׂרוֹת. וּשְׁאָר כָּל פֵּרוֹת הָאִילָן, כְּעוֹנָתָן לַמַּעַשְׂרוֹת, כֵּן עוֹנָתָן לַשְּׁבִיעִית:
--------------------------------------------------------------------------------
פרק ד - משנה י
מֵאֵימָתַי אֵין קוֹצְצִין אֶת הָאִילָן בַּשְּׁבִיעִית. בֵּית שַׁמַּאי אוֹמְרִים, כָּל הָאִילָן מִשֶּׁיּוֹצִיא. וּבֵית הִלֵּל אוֹמְרִים, הֶחָרוּבִין מִשֶּׁיְּשַׁלְשֵׁלוּ, וְהַגְּפָנִים מִשֶּׁיְּגָרְעוּ, וְהַזֵּיתִים מִשֶּׁיָּנֵצוּ, וּשְׁאָר כָּל אִילָן מִשֶּׁיּוֹצִיא. וְכָל הָאִילָן, כֵּיוָן שֶׁבָּא לְעוֹנַת הַמַּעַשְׂרוֹת, מֻתָּר לְקָצְצוֹ {יג}. כַּמָּה יְהֵא בַזַּיִת וְלֹא יְקֻצֶּנּוּ, רֹבַע. רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, הַכֹּל לְפִי הַזַּיִת:
--------------------------------------------------------------------------------
פרק ה
--------------------------------------------------------------------------------
פרק ה - משנה א
בְּנוֹת שׁוּחַ, שְׁבִיעִית שֶׁלָּהֶן, שְׁנִיָּה, שֶׁהֵן עוֹשׂוֹת לְשָׁלֹשׁ שָׁנִים. רַבִּי יְהוּדָה אוֹמֵר, הַפַּרְסָאוֹת, שְׁבִיעִית שֶׁלָּהֶן, מוֹצָאֵי שְׁבִיעִית, שֶׁהֵן עוֹשׂוֹת לִשְׁתֵּי שָׁנִים. אָמְרוּ לוֹ, לֹא אָמְרוּ אֶלָּא בְנוֹת שׁוּחַ {א}:
--------------------------------------------------------------------------------
פרק ה - משנה ב
הַטּוֹמֵן אֶת הַלּוּף בַּשְּׁבִיעִית, רַבִּי מֵאִיר אוֹמֵר, לֹא יִפְחֹת מִסָּאתַיִם, עַד גֹּבַהּ שְׁלֹשָׁה טְפָחִים, וְטֶפַח עָפָר עַל גַּבָּיו. וַחֲכָמִים אוֹמְרִים, לֹא יִפְחֹת מֵאַרְבַּעַת קַבִּים, עַד גֹּבַהּ טֶפַח, וְטֶפַח עָפָר עַל גַּבָּיו. וְטוֹמְנוֹ בִמְקוֹם דְּרִיסַת אָדָם:
--------------------------------------------------------------------------------
פרק ה - משנה ג
לוּף {ב} שֶׁעָבְרָה עָלָיו שְׁבִיעִית, רַבִּי אֱלִיעֶזֶר אוֹמֵר, אִם לָקְטוּ הָעֲנִיִּים אֶת עָלָיו, לָקָטוּ. וְאִם לָאו, יַעֲשֶׂה חֶשְׁבּוֹן עִם הָעֲנִיִּים. רַבִּי יְהוֹשֻׁעַ אוֹמֵר, אִם לָקְטוּ הָעֲנִיִּים אֶת עָלָיו, לָקָטוּ. וְאִם לָאו, אֵין לָעֲנִיִּים עָלָיו חֶשְׁבּוֹן:
--------------------------------------------------------------------------------
פרק ה - משנה ד
לוּף שֶׁל עֶרֶב שְׁבִיעִית שֶׁנִכְנַס לַשְּׁבִיעִית, וְכֵן בְּצָלִים הַקֵּיצוֹנִים, וְכֵן פּוּאָה שֶׁל עִדִּית, בֵּית שַׁמַּאי אוֹמְרִים, עוֹקְרִין אוֹתָן בְּמַאֲרוּפוֹת שֶׁל עֵץ. וּבֵית הִלֵּל אוֹמְרִים, בְּקַרְדֻּמּוֹת שֶׁל מַתָּכוֹת. וּמוֹדִים בְּפוּאָה שֶׁל צְלָעוֹת, שֶׁעוֹקְרִין אוֹתָהּ בְּקַרְדֻּמּוֹת שֶׁל מַתָּכוֹת:
--------------------------------------------------------------------------------
פרק ה - משנה ה
מֵאֵימָתַי מֻתָּר אָדָם לִקַּח לוּף בְּמוֹצָאֵי שְׁבִיעִית, רַבִּי יְהוּדָה אוֹמֵר, מִיָּד. וַחֲכָמִים אוֹמְרִים, מִשֶּׁיִּרְבֶּה {ה} הֶחָדָשׁ:
--------------------------------------------------------------------------------
פרק ה - משנה ו
אֵלּוּ כֵלִים שֶׁאֵין הָאֻמָּן רַשַּׁאי לְמָכְרָם {ו} בַּשְּׁבִיעִית, מַחֲרֵשָׁה וְכָל כֵּלֶיהָ, הָעוֹל, וְהַמִּזְרֶה, וְהַדָּקָר. אֲבָל מוֹכֵר הוּא מַגַּל יָד {ח} וּמַגַּל קָצִיר, וַעֲגָלָה וְכָל כֵּלֶיהָ. זֶה הַכְּלָל, כָּל שֶׁמְּלַאכְתּוֹ מְיֻחֶדֶת לַעֲבֵרָה, אָסוּר. לְאִסּוּר וּלְהֶתֵּר, מֻתָּר:
--------------------------------------------------------------------------------
פרק ה - משנה ז
הַיּוֹצֵר, מוֹכֵר חֲמִשָּׁה כַּדֵּי שֶׁמֶן וַחֲמִשָּׁה עָשָׂר כַּדֵּי יַיִן, שֶׁכֵּן דַּרְכּוֹ לְהָבִיא מִן הַהֶפְקֵר. וְאִם הֵבִיא יוֹתֵר מִכָּאן, מֻתָּר {י}. וּמוֹכֵר לְנָכְרִים בָּאָרֶץ {יא}, וּלְיִּשְׂרָאֵל בְּחוּצָה לָאָרֶץ:
--------------------------------------------------------------------------------
פרק ה - משנה ח
בֵּית שַׁמַּאי אוֹמְרִים, לֹא יִמְכֹּר לוֹ פָרָה חוֹרֶשֶׁת בַּשְּׁבִיעִית. וּבֵית הִלֵּל מַתִּירִין, מִפְּנֵי שֶׁהוּא יָכוֹל לְשָׁחֲטָהּ. מוֹכֵר לוֹ פֵּרוֹת {יג} אֲפִלּוּ בִּשְׁעַת הַזֶּרַע, וּמַשְׁאִיל לוֹ סְאָתוֹ אַף עַל פִּי שֶׁהוּא יוֹדֵעַ שֶׁיֶּשׁ לוֹ גֹּרֶן, וּפוֹרֵט לוֹ מָעוֹת אַף עַל פִּי שֶׁהוּא יוֹדֵעַ שֶׁיֶּשׁ לוֹ פּוֹעֲלִים. וְכֻלָּן, בְּפֵרוּשׁ, אֲסוּרִין:
--------------------------------------------------------------------------------
פרק ה - משנה ט
מַשְׁאֶלֶת אִשָּׁה לַחֲבֶרְתָּהּ הַחֲשׁוּדָה עַל הַשְּׁבִיעִית נָפָה וּכְבָרָה {יד} וְרֵחַיִם וְתַנּוּר. אֲבָל לֹא תָבוֹר וְלֹא תִטְחַן עִמָּהּ. אֵשֶׁת חָבֵר מַשְׁאֶלֶת לְאֵשֶׁת עַם הָאָרֶץ נָפָה וּכְבָרָה, וּבוֹרֶרֶת וְטוֹחֶנֶת {טו} וּמַרְקֶדֶת עִמָּהּ {טז}. אֲבָל מִשֶּׁתַּטִּיל הַמַּיִם, לֹא תִגַּע אֶצְלָהּ, שֶׁאֵין מַחְזִיקִין יְדֵי עוֹבְרֵי עֲבֵרָה. וְכֻלָּן {יח} לֹא אָמְרוּ אֶלָּא מִפְּנֵי דַרְכֵי שָׁלוֹם. וּמַחֲזִיקִין יְדֵי נָכְרִים בַּשְּׁבִיעִית, אֲבָל לֹא יְדֵי יִשְׂרָאֵל. וְשׁוֹאֲלִין בִּשְׁלוֹמָן, מִפְּנֵי דַרְכֵי שָׁלוֹם:
--------------------------------------------------------------------------------
פרק ו
--------------------------------------------------------------------------------
פרק ו - משנה א
שָׁלֹשׁ אֲרָצוֹת לַשְּׁבִיעִית. כָּל שֶׁהֶחֱזִיקוּ עוֹלֵי בָבֶל, מֵאֶרֶץ יִשְׂרָאֵל וְעַד כְּזִיב, לֹא נֶאֱכָל וְלֹא נֶעֱבָד. וְכָל שֶׁהֶחֱזִיקוּ עוֹלֵי מִצְרַיִם, מִכְּזִיב וְעַד הַנָּהָר וְעַד אֲמָנָה, נֶאֱכָל, אֲבָל לֹא {ב} נֶעֱבָד. מִן הַנָּהָר וּמֵאֲמָנָה וְלִפְנִים, נֶאֱכָל וְנֶעֱבָד:
--------------------------------------------------------------------------------
פרק ו - משנה ב
עוֹשִׂין בְּתָלוּשׁ בְּסוּרְיָא, אֲבָל לֹא בִמְחֻבָּר. דָּשִׁים {ג} וְזוֹרִין וְדוֹרְכִין וּמְעַמְּרִין, אֲבָל לֹא קוֹצְרִין וְלֹא בוֹצְרִין וְלֹא מוֹסְקִים. כְּלָל אָמַר רַבִּי עֲקִיבָא, כָּל שֶׁכַּיּוֹצֵא בוֹ מֻתָּר בְּאֶרֶץ יִשְׂרָאֵל, עוֹשִׂין אוֹתוֹ בְּסוּרְיָא:
--------------------------------------------------------------------------------
פרק ו - משנה ג
בְּצָלִים שֶׁיָּרְדוּ עֲלֵיהֶם גְּשָׁמִים וְצִמֵּחוּ, אִם הָיוּ הֶעָלִין שֶׁלָּהֶם שְׁחוֹרִין, אֲסוּרִין {ד}. הוֹרִיקוּ, הֲרֵי אֵלּוּ מֻתָּרִין. רַבִּי חֲנִינָא בֶן אַנְטִיגְנוֹס אוֹמֵר, אִם יְכוֹלִין לְהִתָּלֵשׁ בֶּעָלִין שֶׁלָּהֶן, אֲסוּרִין. וּכְנֶגֶד כֵּן, מוֹצָאֵי שְׁבִיעִית, מֻתָּרִין:
--------------------------------------------------------------------------------
פרק ו - משנה ד
מֵאֵימָתַי מֻתָּר אָדָם לִקַּח יָרָק בְּמוֹצָאֵי שְׁבִיעִית, מִשֶּׁיַּעֲשֶׂה כַיּוֹצֵא בוֹ. עָשָׁה הַבַּכִּיר, הֻתַּר הָאָפִיל {ו}. רַבִּי הִתִּיר לִקַּח יָרָק בְּמוֹצָאֵי שְׁבִיעִית מִיָּד:
--------------------------------------------------------------------------------
פרק ו - משנה ה
אֵין מוֹצִיאִין שֶׁמֶן שְׂרֵפָה וּפֵרוֹת שְׁבִיעִית מֵהָאָרֶץ לְחוּץ לָאָרֶץ. אָמַר רַבִּי שִׁמְעוֹן, שָׁמַעְתִּי בְפֵרוּשׁ, שֶׁמּוֹצִיאִין לְסוּרְיָא וְאֵין מוֹצִיאִין לְחוּץ לָאָרֶץ:
--------------------------------------------------------------------------------
פרק ו - משנה ו
אֵין מְבִיאִין תְּרוּמָה מֵחוּצָה לָאָרֶץ לָאָרֶץ. אָמַר רַבִּי שִׁמְעוֹן, שָׁמַעְתִּי בְּפֵרוּשׁ, שֶׁמְּבִיאִין מִסּוּרְיָא וְאֵין מְבִיאִין מִחוּצָה לָאָרֶץ:
--------------------------------------------------------------------------------
פרק ז
--------------------------------------------------------------------------------
פרק ז - משנה א
כְּלָל גָּדוֹל {א} אָמְרוּ בַּשְּׁבִיעִית, כָּל שֶׁהוּא מַאֲכַל אָדָם וּמַאֲכַל בְּהֵמָה, וּמִמִּין הַצּוֹבְעִים, וְאֵינוֹ מִתְקַיֵּם בָּאָרֶץ, יֶשׁ לוֹ שְׁבִיעִית וּלְדָמָיו שְׁבִיעִית, יֶשׁ לוֹ בִּעוּר וּלְדָמָיו בִּעוּר. וְאֵיזֶה זֶה, עֲלֵה הַלּוּף הַשּׁוֹטֶה, וַעֲלֵה הַדַּנְדַּנָּה, הָעֻלְשִׁין, וְהַכְּרֵשִׁין, וְהָרְגִילָה, וְנֵץ הֶחָלָב. וּמַאֲכַל בְּהֵמָה, הַחוֹחִים וְהַדַּרְדָּרִים {ב}. וּמִמִּין הַצּוֹבְעִים {ג}, סְפִיחֵי אִסְטִיס, וְקוֹצָה. יֶשׁ לָהֶם שְׁבִיעִית וְלִדְמֵיהֶן שְׁבִיעִית, יֶשׁ לָהֶם בִּעוּר וְלִדְמֵיהֶן בִּעוּר:
--------------------------------------------------------------------------------
פרק ז - משנה ב
וְעוֹד כְּלָל אַחֵר אָמְרוּ, כָּל שֶׁאֵינוֹ {ד} מַאֲכַל אָדָם וּמַאֲכַל בְּהֵמָה, וּמִמִּין הַצּוֹבְעִין, וּמִתְקַיֵּם בָּאָרֶץ, יֶשׁ לוֹ שְׁבִיעִית וּלְדָמָיו שְׁבִיעִית, אֵין לוֹ בִּעוּר וְאֵין לְדָמָיו בִּעוּר. אֵי זֶהוּ, עִקַּר הַלּוּף הַשּׁוֹטֶה, וְעִקַּר הַדַּנְדַּנָּה, וְהָעַרְקַבְנִין, וְהַחַלְבְּצִין, וְהַבֻּכְרִיָּה. וּמִמִּין הַצּוֹבְעִין, הַפּוּאָה וְהָרִכְפָּא, יֵשׁ לָהֶם שְׁבִיעִית וְלִדְמֵיהֶן שְׁבִיעִית, אֵין לָהֶם בִּעוּר וְלֹא לִדְמֵיהֶן בִּעוּר. רַבִּי מֵאִיר אוֹמֵר, דְּמֵיהֶם מִתְבַּעֲרִין עַד רֹאשׁ הַשָּׁנָה. אָמְרוּ לוֹ, לָהֶן אֵין בִּעוּר, קַל וָחֹמֶר לִדְמֵיהֶן:
--------------------------------------------------------------------------------
פרק ז - משנה ג
קְלִפֵּי רִמּוֹן וְהַנֵּץ שֶׁלּוֹ, קְלִפֵּי אֱגוֹזִים וְהַגַּלְעִינִין, יֵשׁ לָהֶם שְׁבִיעִית {ה} וְלִדְמֵיהֶן שְׁבִיעִית. הַצַּבָּע, צוֹבֵעַ לְעַצְמוֹ, וְלֹא יִצְבַּע בְּשָׂכָר, שֶׁאֵין עוֹשִׂין סְחוֹרָה בְּפֵרוֹת שְׁבִיעִית, וְלֹא בִבְכוֹרוֹת, וְלֹא בִתְרוּמוֹת, וְלֹא בִנְבֵלוֹת, וְלֹא בִטְרֵפוֹת, וְלֹא בִשְׁקָצִים, וְלֹא בִרְמָשִׂים. וְלֹא יִהְיֶה לוֹקֵחַ יַרְקוֹת שָׂדֶה {ז} וּמוֹכֵר בַּשּׁוּק, אֲבָל הוּא לוֹקֵט וּבְנוֹ מוֹכֵר עַל יָדוֹ. לָקַח לְעַצְמוֹ וְהוֹתִיר, מֻתָּר לְמָכְרָן:
--------------------------------------------------------------------------------
פרק ז - משנה ד
לָקַח בְּכוֹר לְמִשְׁתֵּה בְנוֹ אוֹ לָרֶגֶל וְלֹא צָרִיךְ לוֹ, מֻתָּר לְמָכְרוֹ. צָדֵי חַיָּה עוֹפוֹת וְדָגִים שֶׁנִּזְדַּמְּנוּ לָהֶם מִינִים טְמֵאִין, מֻתָּרִים לְמָכְרָן. רַבִּי יְהוּדָה אוֹמֵר, אַף מִי שֶׁנִּתְמַנָּה לוֹ לְפִי דַרְכּוֹ, לוֹקֵחַ וּמוֹכֵר, וּבִלְבַד שֶׁלֹּא תְהֵא אֻמָּנוּתוֹ בְכָךְ. וַחֲכָמִים אוֹסְרִין {ט}:
--------------------------------------------------------------------------------
פרק ז - משנה ה
לוּלְבֵי זְרָדִים וְהֶחָרוּבִין, יֵשׁ לָהֶם שְׁבִיעִית וְלִדְמֵיהֶן שְׁבִיעִית, יֵשׁ לָהֶן בִּעוּר וְלִדְמֵיהֶן בִּעוּר. לוּלְבֵי הָאֵלָה וְהַבָּטְנָה וְהָאֲטָדִין, יֵשׁ לָהֶם שְׁבִיעִית, וְלִדְמֵיהֶן שְׁבִיעִית, אֵין לָהֶם בִּעוּר וְלֹא לִדְמֵיהֶן בִּעוּר. אֲבָל לֶעָלִין יֵשׁ בִּעוּר, מִפְּנֵי שֶׁנּוֹשְׁרִין {יא} מֵאֲבִיהֶן:
--------------------------------------------------------------------------------
פרק ז - משנה ו
הַוֶּרֶד וְהַכֹּפֶר וְהַקְּטָף וְהַלֹּטֶם, יֵשׁ לָהֶם שְׁבִיעִית וְלִדְמֵיהֶן שְׁבִיעִית. רַבִּי שִׁמְעוֹן אוֹמֵר, אֵין לַקְּטָף שְׁבִיעִית, מִפְּנֵי שֶׁאֵינוֹ פֶרִי:
--------------------------------------------------------------------------------
פרק ז - משנה ז
וֶרֶד חָדָשׁ שֶׁכְּבָשׁוֹ בְּשֶׁמֶן יָשָׁן, יְלַקֵּט אֶת הַוֶּרֶד. וְיָשָׁן בְּחָדָשׁ, חַיָּב בַּבִּעוּר. חָרוּבִין חֲדָשִׁים שֶׁכְּבָשָׁן בְּיַיִן יָשָׁן, וִישָׁנִים בְּחָדָשׁ, חַיָּבִין בַּבִּעוּר. זֶה הַכְּלָל, כָּל שֶׁהוּא בְנוֹתֵן טַעַם, חַיָּב לְבַעֵר, מִין בְּשֶׁאֵינוֹ מִינוֹ. וּמִין בְּמִינוֹ, כָּל שֶׁהוּא. שְׁבִיעִית אוֹסֶרֶת כָּל שֶׁהוּא {יח} בְּמִינָהּ, וְשֶׁלֹּא בְמִינָהּ, בְּנוֹתֵן טָעַם:
--------------------------------------------------------------------------------
פרק ח
--------------------------------------------------------------------------------
פרק ח - משנה א
כְּלָל גָּדוֹל {א} אָמְרוּ בַּשְּׁבִיעִית, כָּל הַמְיֻחָד לְמַאֲכַל אָדָם, אֵין עוֹשִׂין מִמֶּנּוּ מְלוּגְמָא לָאָדָם, וְאֵין צָרִיךְ לוֹמַר לַבְּהֵמָה. וְכָל שֶׁאֵינוֹ מְיֻחָד לְמַאֲכַל אָדָם, עוֹשִׂין מִמֶּנּוּ מְלוּגְמָא לְאָדָם, אֲבָל לֹא לִבְהֵמָה. וְכָל שֶׁאֵינוֹ מְיֻחָד לֹא לְמַאֲכַל אָדָם וְלֹא לְמַאֲכַל בְּהֵמָה, חָשַׁב עָלָיו לְמַאֲכַל אָדָם וּלְמַאֲכַל בְּהֵמָה, נוֹתְנִין עָלָיו חֻמְרֵי אָדָם וְחֻמְרֵי בְהֵמָה. חָשַׁב עָלָיו לְעֵצִים, הֲרֵי הוּא כְעֵצִים, כְּגוֹן הַסִּיאָה וְהָאֵזוֹב וְהַקּוֹרָנִית:
--------------------------------------------------------------------------------
פרק ח - משנה ב
שְׁבִיעִית, נִתְּנָה לַאֲכִילָה וְלִשְׁתִיָּה וּלְסִיכָה, לֶאֱכֹל דָּבָר שֶׁדַּרְכּוֹ לֶאֱכֹל, וְלָסוּךְ דָּבָר שֶׁדַּרְכּוֹ לָסוּךְ. לֹא יָסוּךְ יַיִן וָחֹמֶץ, אֲבָל סָךְ הוּא אֶת הַשָּׁמֶן. וְכֵן בִּתְרוּמָה וּבְמַעֲשֵׂר שֵׁנִי. קַל מֵהֶם שְׁבִיעִית, שֶׁנִּתְּנָה לְהַדְלָקַת הַנֵּר {ג}:
--------------------------------------------------------------------------------
פרק ח - משנה ג
אֵין מוֹכְרִין פֵּרוֹת שְׁבִיעִית, לֹא בְמִדָּה {ד}, וְלֹא בְמִשְׁקָל, וְלֹא בְמִנְיָן, וְלֹא תְאֵנִים {ה} בְּמִנְיָן, וְלֹא יָרָק בְּמִשְׁקָל. בֵּית שַׁמַּאי אוֹמְרִים, אַף לֹא אֲגֻדּוֹת {ו}. וּבֵית הִלֵּל אוֹמְרִים, אֶת שֶׁדַּרְכּוֹ לֶאֱגֹד בַּבַּיִת {ז}, אוֹגְדִין אוֹתוֹ בַּשּׁוּק, כְּגוֹן הַכְּרֵשִׁין וְנֵץ הֶחָלָב:
--------------------------------------------------------------------------------
פרק ח - משנה ד
הָאוֹמֵר לַפּוֹעֵל, הֵא לָךְ אִסָּר זֶה וּלְקֹט לִי יָרָק הַיּוֹם, שְׂכָרוֹ מֻתָּר {ח}. לְקֹט לִי בּוֹ יָרָק הַיּוֹם, שְׂכָרוֹ אָסוּר {ט}. לָקַח מִן הַנַּחְתּוֹם כִּכָּר בְּפוּנְדְּיוֹן, כְּשֶׁאֶלְקֹט יַרְקוֹת שָׂדֶה אָבִיא לָךְ, מֻתָּר. לָקַח מִמֶּנּוּ סְתָם, לֹא יְשַׁלֵּם לוֹ מִדְּמֵי שְׁבִיעִית, שֶׁאֵין פּוֹרְעִין חוֹב מִדְּמֵי שְׁבִיעִית:
--------------------------------------------------------------------------------
פרק ח - משנה ה
אֵין נוֹתְנִים, לֹא לְבַיָּר, וְלֹא לְבַלָּן {י}, וְלֹא לְסַפָּר, וְלֹא לְסַפָּן. אֲבָל נוֹתֵן הוּא לְבַיָּר לִשְׁתּוֹת. וּלְכֻלָּן, הוּא נוֹתֵן מַתְּנַת חִנָּם:
--------------------------------------------------------------------------------
פרק ח - משנה ו
תְּאֵנִים שֶׁל שְׁבִיעִית, אֵין קוֹצִין אוֹתָן בְּמֻקְצֶה, אֲבָל קוֹצֶה אוֹתָם בַּחַרְבָּה. אֵין דּוֹרְכִין עֲנָבִים בַּגַּת, אֲבָל דּוֹרֵךְ הוּא בָּעֲרֵבָה. וְאֵין עוֹשִׂין {יב} זֵיתִים בַּבַּד וּבַקֹּטֶב, אֲבָל כּוֹתֵשׁ הוּא וּמַכְנִיס לַבּוֹדִידָה. רַבִּי שִׁמְעוֹן אוֹמֵר, אַף טוֹחֵן הוּא בְּבֵית הַבַּד וּמַכְנִיס לַבּוֹדִידָה:
--------------------------------------------------------------------------------
פרק ח - משנה ז
אֵין מְבַשְּׁלִין יָרָק שֶׁל שְׁבִיעִית בְּשֶׁמֶן שֶׁל תְּרוּמָה, שֶׁלֹּא יְבִיאֶנּוּ לִידֵי פְסוּל. רַבִּי שִׁמְעוֹן מַתִּיר. וְאַחֲרוֹן אַחֲרוֹן, נִתְפָּשׂ בַּשְּׁבִיעִית. וְהַפְּרִי עַצְמוֹ, אָסוּר:
--------------------------------------------------------------------------------
פרק ח - משנה ח
אֵין לוֹקְחִים עֲבָדִים וְקַרְקָעוֹת וּבְהֵמָה טְמֵאָה מִדְּמֵי שְׁבִיעִית. וְאִם לָקַח, יֹאכַל כְּנֶגְדָּן. אֵין מְבִיאִין {טו} קִנֵּי זָבִים וְקִנֵּי זָבוֹת וְקִנֵּי יוֹלְדוֹת מִדְּמֵי שְׁבִיעִית. וְאִם הֵבִיא, יֹאכַל כְּנֶגְדָּן. אֵין סָכִין כֵּלִים {טז} בְּשֶׁמֶן שֶׁל שְׁבִיעִית. וְאִם סָךְ, יֹאכַל כְּנֶגְדּוֹ:
--------------------------------------------------------------------------------
פרק ח - משנה ט
עוֹר שֶׁסָּכוֹ בְּשֶׁמֶן שֶׁל שְׁבִיעִית, רַבִּי אֱלִיעֶזֶר אוֹמֵר, יִדָּלֵק {יז}. וַחֲכָמִים אוֹמְרִים, יֹאכַל כְּנֶגְדּוֹ {יח}. אָמְרוּ לִפְנֵי רַבִּי עֲקִיבָא, אוֹמֵר הָיָה רַבִּי אֱלִיעֶזֶר, עוֹר שֶׁסָּכוֹ בְשֶׁמֶן שֶׁל שְׁבִיעִית, יִדָּלֵק. אָמַר לָהֶם, שְׁתֹקוּ, לֹא אוֹמַר לָכֶם מַה שֶּׁרַבִּי אֱלִיעֶזֶר אוֹמֵר בּוֹ:
--------------------------------------------------------------------------------
פרק ח - משנה י
וְעוֹד אָמְרוּ לְפָנָיו, אוֹמֵר הָיָה רַבִּי אֱלִיעֶזֶר, הָאוֹכֵל פַּת כּוּתִים כְּאוֹכֵל בְּשַׂר חֲזִיר. אָמַר לָהֶם, שְׁתֹקוּ, לֹא אוֹמַר לָכֶם מַה שֶּׁרַבִּי אֱלִיעֶזֶר אוֹמֵר בּוֹ:
--------------------------------------------------------------------------------
פרק ח - משנה יא
מֶרְחָץ שֶׁהֻסְּקָה בְּתֶבֶן אוֹ בְקַשׁ שֶׁל שְׁבִיעִית, מֻתָּר {כ} לִרְחֹץ בָּהּ. וְאִם מִתְחַשֵּׁב הוּא, הֲרֵי זֶה לֹא יִרְחֹץ:
--------------------------------------------------------------------------------
פרק ט
--------------------------------------------------------------------------------
פרק ט - משנה א
הַפֵּגָם, וְהַיַּרְבּוּזִין הַשּׁוֹטִים, וְהַחֲלַגְלוֹגִית, כֻּסְבָּר שֶׁבֶּהָרִים, וְהַכַּרְפַּס שֶׁבַּנְּהָרוֹת, וְהַגַּרְגֵּר שֶׁל אֲפָר, פְּטוּרִין מִן הַמַּעַשְׂרוֹת, וְנִלְקָחִין מִכָּל אָדָם בַּשְּׁבִיעִית, שֶׁאֵין כַּיּוֹצֵא בָהֶם נִשְׁמָר. רַבִּי יְהוּדָה אוֹמֵר, סְפִיחֵי חַרְדָּל, מֻתָּרִין, שֶׁלֹּא נֶחְשְׁדוּ עֲלֵיהֶן עוֹבְרֵי עֲבֵרָה. רַבִּי שִׁמְעוֹן אוֹמֵר, כָּל הַסְּפִיחִין מֻתָּרִין, חוּץ מִסְּפִיחֵי כְרוּב, שֶׁאֵין כַּיּוֹצֵא בָהֶם בְּיַרְקוֹת שָׂדֶה. וַחֲכָמִים אוֹמְרִים, כָּל הַסְּפִיחִין אֲסוּרִין:
--------------------------------------------------------------------------------
פרק ט - משנה ב
שָׁלֹשׁ אֲרָצוֹת לַבִּעוּר, יְהוּדָה, וְעֵבֶר הַיַּרְדֵּן, וְהַגָּלִיל. וְשָׁלֹשׁ שָׁלֹשׁ אֲרָצוֹת לְכָל אַחַת וְאַחַת. גָּלִיל הָעֶלְיוֹן, וְגָלִיל הַתַּחְתּוֹן, וְהָעֵמֶק. מִכְּפַר חֲנַנְיָה וּלְמַעְלָן, כָּל שֶׁאֵינוֹ מְגַדֵּל שִׁקְמִין, גָּלִיל הָעֶלְיוֹן, וּמִכְּפַר חֲנַנְיָה וּלְמַטָּן, כָּל שֶׁהוּא מְגַדֵּל שִׁקְמִין, גָּלִיל הַתַּחְתּוֹן. וּתְחוּם טְבֶרְיָא, הָעֵמֶק. וּבִיהוּדָה, הָהָר וְהַשְּׁפֵלָה וְהָעֵמֶק. וּשְׁפֵלַת לוּד כִּשְׁפֵלַת הַדָּרוֹם, וְהָהָר שֶׁלָּהּ כְּהַר הַמֶּלֶךְ. מִבֵּית חוֹרוֹן וְעַד הַיָּם מְדִינָה אֶחָת:
--------------------------------------------------------------------------------
פרק ט - משנה ג
וְלָמָּה אָמְרוּ שָׁלֹשׁ אֲרָצוֹת, שֶׁיִּהְיוּ אוֹכְלִין בְּכָל אַחַת וְאַחַת עַד שֶׁיִּכְלֶה הָאַחֲרוֹן שֶׁבָּהּ. רַבִּי שִׁמְעוֹן אוֹמֵר, לֹא אָמְרוּ {ה} שָׁלֹשׁ אֲרָצוֹת אֶלָּא בִיהוּדָה. וּשְׁאָר כָּל הָאֲרָצוֹת, כְּהַר הַמֶּלֶךְ. וְכָל הָאֲרָצוֹת {ו}, כְּאַחַת לַזֵּיתִים וְלַתְּמָרִים:
--------------------------------------------------------------------------------
פרק ט - משנה ד
אוֹכְלִין עַל הַמֻּפְקָר, אֲבָל לֹא עַל הַשָּׁמוּר. רַבִּי יוֹסֵי מַתִּיר אַף עַל הַשָּׁמוּר {ז}. אוֹכְלִין עַל הַטְּפִיחִין וְעַל הַדּוּפְרָא, אֲבָל לֹא עַל הַסִּתְוָנִיּוֹת. רַבִּי יְהוּדָה מַתִּיר כָּל זְמַן שֶׁבִּכְּרוּ עַד שֶׁלֹּא יִכְלֶה הַקָּיִץ:
--------------------------------------------------------------------------------
פרק ט - משנה ה
הַכּוֹבֵשׁ שְׁלֹשָׁה כְבָשִׁים בְּחָבִית אַחַת, רַבִּי אֱלִיעֶזֶר אוֹמֵר, אוֹכְלִין עַל הָרִאשׁוֹן. רַבִּי יְהוֹשֻׁעַ אוֹמֵר, אַף עַל הָאַחֲרוֹן. רַבָּן גַּמְלִיאֵל אוֹמֵר, כָּל שֶׁכָּלָה מִינוֹ מִן הַשָּׂדֶה, יְבַעֵר מִינוֹ מִן הֶחָבִית {ט}, וַהֲלָכָה כִדְבָרָיו. רַבִּי שִׁמְעוֹן אוֹמֵר, כָּל יָרָק, אֶחָד לַבִּעוּר. אוֹכְלִין בָּרְגִילָה {י} עַד שֶׁיִּכְלוּ סִגָּרִיּוֹת מִבִּקְעַת בֵּית נְטוֹפָה:
--------------------------------------------------------------------------------
פרק ט - משנה ו
הַמְלַקֵּט עֲשָׂבִים לַחִים, עַד שֶׁיִּיבַשׁ הַמָּתוֹק. וְהַמְגַבֵּב בַּיָּבֵשׁ {יא}, עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה. עֲלֵי קָנִים וַעֲלֵי גְפָנִים, עַד שֶׁיִּשְּׁרוּ מֵאֲבִיהֶן. וְהַמְגַבֵּב בַּיָּבֵשׁ, עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה. רַבִּי עֲקִיבָא אוֹמֵר, בְּכֻלָּן עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה:
--------------------------------------------------------------------------------
פרק ט - משנה ז
כַּיּוֹצֵא בוֹ, הַמַּשְׂכִּיר בַּיִת לַחֲבֵרוֹ עַד הַגְּשָׁמִים, עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה. הַמֻּדַּר הֲנָאָה מֵחֲבֵרוֹ עַד הַגְּשָׁמִים, עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה. עַד אֵימָתַי עֲנִיִּים נִכְנָסִים לַפַּרְדֵּסוֹת {יג}, עַד שֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה. מֵאֵימָתַי נֶהֱנִין וְשׂוֹרְפִין בַּתֶּבֶן וּבַקַּשׁ שֶׁל שְׁבִיעִית, מִשֶׁתֵּרֵד רְבִיעָה שְׁנִיָּה:
--------------------------------------------------------------------------------
פרק ט - משנה ח
מִי שֶׁהָיוּ לוֹ פֵּרוֹת שְׁבִיעִית וְהִגִּיעַ שְׁעַת הַבִּעוּר, מְחַלֵּק מְזוֹן שָׁלֹשׁ סְעֻדּוֹת לְכָל אֶחָד וְאֶחָד. וַעֲנִיִּים אוֹכְלִין אַחַר הַבִּעוּר, אֲבָל לֹא עֲשִׁירִים, דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי יוֹסֵי אוֹמֵר, אֶחָד עֲנִיִּים וְאֶחָד עֲשִׁירִים {טו} אוֹכְלִין אַחַר הַבִּעוּר:
--------------------------------------------------------------------------------
פרק ט - משנה ט
מִי שֶׁהָיוּ לוֹ פֵּרוֹת שְׁבִיעִית שֶׁנָּפְלוּ לוֹ בִירֻשָּׁה אוֹ שֶׁנִּתְּנוּ לוֹ בְּמַתָּנָה, רַבִּי אֱלִיעֶזֶר אוֹמֵר, יִנָּתְנוּ לְאוֹכְלֵיהֶן. וַחֲכָמִים אוֹמְרִים, אֵין הַחוֹטֵא נִשְׂכָּר, אֶלָּא יִמָּכְרוּ לְאוֹכְלֵיהֶן, וּדְמֵיהֶם יִתְחַלְּקוּ לְכָל אָדָם. הָאוֹכֵל מֵעִסַּת שְׁבִיעִית עַד שֶׁלֹּא הוּרְמָה חַלָּתָהּ, חַיָּב מִיתָה:
--------------------------------------------------------------------------------
פרק י
--------------------------------------------------------------------------------
פרק י - משנה א
שְׁבִיעִית, מְשַׁמֶּטֶת אֶת הַמִּלְוָה בִּשְׁטָר וְשֶׁלֹּא בִשְׁטָר. הַקָּפַת הַחֲנוּת, אֵינָהּ מְשַׁמֶּטֶת, וְאִם עֲשָׂאָהּ מִלְוָה, הֲרֵי זֶה מְשַׁמֵּט. רַבִּי יְהוּדָה אוֹמֵר, הָרִאשׁוֹן הָרִאשׁוֹן מְשַׁמֵּט. שְׂכַר שָׂכִיר, אֵינוֹ מְשַׁמֵּט, וְאִם עֲשָׂאוֹ מִלְוָה, הֲרֵי זֶה מְשַׁמֵּט. רַבִּי יוֹסֵי אוֹמֵר, כָּל מְלָאכָה שֶׁפּוֹסֶקֶת בַּשְּׁבִיעִית, מְשַׁמֶּטֶת, וְשֶׁאֵינָהּ פּוֹסֶקֶת בַּשְּׁבִיעִית, אֵינָהּ מְשַׁמֶּטֶת:
--------------------------------------------------------------------------------
פרק י - משנה ב
הַשּׁוֹחֵט אֶת הַפָּרָה וְחִלְּקָהּ בְּרֹאשׁ הַשָּׁנָה, אִם הָיָה הַחֹדֶשׁ מְעֻבָּר, מְשַׁמֵּט {ב}. וְאִם לָאו, אֵינוֹ מְשַׁמֵּט. הָאוֹנֵס, וְהַמְפַתֶּה, וְהַמּוֹצִיא שֵׁם רָע, וְכָל מַעֲשֵׂה בֵית דִּין, אֵין מְשַׁמְּטִין. הַמַּלְוֶה עַל הַמַּשְׁכּוֹן, וְהַמּוֹסֵר שְׁטָרוֹתָיו לְבֵית דִּין, אֵינָן מְשַׁמְּטִין:
--------------------------------------------------------------------------------
פרק י - משנה ג
פְּרוֹזְבּוּל, אֵינוֹ מְשַׁמֵּט. זֶה אֶחָד מִן הַדְּבָרִים שֶׁהִתְקִין הִלֵּל הַזָּקֵן, כְּשֶׁרָאָה שֶׁנִּמְנְעוּ הָעָם מִלְּהַלְווֹת זֶה אֶת זֶה וְעוֹבְרִין עַל מַה שֶּׁכָּתוּב בַּתּוֹרָה (דברים טו) הִשָּׁמֶר לְךָ פֶּן יִהְיֶה דָבָר עִם לְבָבְךָ בְּלִיַּעַל וְגוֹ', הִתְקִין הִלֵּל לַפְּרוֹזְבּוּל:
--------------------------------------------------------------------------------
פרק י - משנה ד
זֶהוּ גוּפוֹ שֶׁל פְּרוֹזְבּוּל. מוֹסֵר אֲנִי לָכֶם אִישׁ פְּלוֹנִי וּפְלוֹנִי {ה} הַדַּיָּנִים שֶׁבְּמָקוֹם פְּלוֹנִי, שֶׁכָּל חוֹב שֶׁיֶּשׁ לִי {ו}, שֶׁאֶגְבֶּנּוּ כָּל זְמַן שֶׁאֶרְצֶה. וְהַדַּיָּנִים חוֹתְמִין לְמַטָּה, אוֹ הָעֵדִים:
--------------------------------------------------------------------------------
פרק י - משנה ה
פְּרוֹזְבּוּל הַמֻּקְדָּם, כָּשֵׁר, וְהַמְאֻחָר, פָּסוּל {ח}. שִׁטְרֵי חוֹב הַמֻּקְדָּמִים, פְּסוּלִים, וְהַמְאֻחָרִים, כְּשֵׁרִים. אֶחָד לֹוֶה מֵחֲמִשָּׁה, כּוֹתֵב פְּרוֹזְבּוּל לְכָל אֶחָד וְאֶחָד. חֲמִשָּׁה לֹוִין מֵאֶחָד, אֵינוֹ כוֹתֵב אֶלָּא פְּרוֹזְבּוּל אֶחָד לְכֻלָּם:
--------------------------------------------------------------------------------
פרק י - משנה ו
אֵין כּוֹתְבִין פְּרוֹזְבּוּל אֶלָּא עַל הַקַּרְקַע. אִם אֵין לוֹ, מְזַכֶּה הוּא בְּתוֹךְ שָׂדֵהוּ כָּל שֶׁהוּא. הָיְתָה לוֹ שָׂדֶה מְמֻשְׁכֶּנֶת בָּעִיר, כּוֹתְבִין עָלֶיהָ פְּרוֹזְבּוּל. רַבִּי חֻצְפִּית אוֹמֵר, כּוֹתְבִין לָאִישׁ עַל נִכְסֵי אִשְׁתּוֹ, וְלַיְתוֹמִים {יב} עַל נִכְסֵי אַפּוֹטְרוֹפִּין:
--------------------------------------------------------------------------------
פרק י - משנה ז
כַּוֶּרֶת דְּבוֹרִים, רַבִּי אֱלִיעֶזֶר אוֹמֵר, הֲרֵי הִיא כְקַרְקַע, וְכוֹתְבִין {יד} עָלֶיהָ פְּרוֹזְבּוּל, וְאֵינָהּ מְקַבֶּלֶת טֻמְאָה בִּמְקוֹמָהּ, וְהָרוֹדֶה מִמֶּנָּה בְּשַׁבָּת חַיָּב. וַחֲכָמִים אוֹמְרִים, אֵינָהּ כְּקַרְקַע, וְאֵין כּוֹתְבִין עָלֶיהָ פְּרוֹזְבּוּל, וּמְקַבֶּלֶת טֻמְאָה בִּמְקוֹמָהּ, וְהָרוֹדֶה מִמֶּנָּה בְּשַׁבָּת, פָּטוּר {טו}:
--------------------------------------------------------------------------------
פרק י - משנה ח
הַמַּחֲזִיר חוֹב בַּשְּׁבִיעִית, יֹאמַר לוֹ מְשַׁמֵּט אָנִי. אָמַר לוֹ אַף עַל פִּי כֵן, יְקַבֵּל מִמֶּנּוּ, שֶׁנֶּאֱמַר (דברים טו) וְזֶה דְּבַר הַשְּׁמִטָּה. כַּיּוֹצֵא בוֹ, רוֹצֵחַ שֶׁגָּלָה לְעִיר מִקְלָט וְרָצוּ אַנְשֵׁי הָעִיר לְכַבְּדוֹ, יֹאמַר לָהֶם, רוֹצֵחַ אָנִי. אָמְרוּ לוֹ, אַף עַל פִּי כֵן, יְקַבֵּל מֵהֶם, שֶׁנֶּאֱמַר (שם יט) וְזֶה דְּבַר הָרוֹצֵחַ:
--------------------------------------------------------------------------------
פרק י - משנה ט
הַמַּחֲזִיר חוֹב בַּשְּׁבִיעִית, רוּחַ חֲכָמִים נוֹחָה מִמֶּנּוּ. הַלֹּוֶה מִן הַגֵּר שֶׁנִּתְגַּיְּרוּ בָנָיו עִמּוֹ, לֹא יַחֲזִיר לְבָנָיו. וְאִם הֶחֱזִיר, רוּחַ חֲכָמִים נוֹחָה מִמֶּנּוּ. כָּל הַמִּטַּלְטְלִין, נִקְנִין בִּמְשִׁיכָה. וְכָל הַמְקַיֵּם אֶת דְּבָרוֹ, רוּחַ חֲכָמִים נוֹחָה מִמֶּנּוּ {יח}:
* Footnotes
[fn:1] פרק שני
[fn:2] משנה
[fn:3] בצלים שלא עושים זרע.
[fn:4] גמרא (ו.) מפרש שהוא מפני שנעשה כזרע. כיון שדין זרע הוא שנתעשר לשנה שעברה, כך דין אלו. כיון שמנע ממנו מים לשלשים יום נעשה זרע כיון שדרך זרע הוא שלא להשקותו תידר. אז, כיון שמנע ממנו מים, נעשה כעין זרע.מפני משה לא נראה כן, אלא נראה שמפרש שכיון שלא השקה אותו שלשים יום לפני ראש השנה (ולא השקה אותו אחר כך), נמצא שלא היה לו אפשרות לגדל בשנה הבאה. אז, דינו כשנה הבאה.
[fn:5] נמצא שיש שני נפק"מ למה שדינו כזרע (ואז נגרר בתר שנה שעבר):אז, מתעשר כאותו שנה.אז, דין שמיטה הולך אחר אותו שנה.יש עוד נפקא מינא מדין של משנה, והוא שנחשב זרע. זרע חלוק מירק, ואין מעשרים מזה על זה. אז, חולקים מתי נעשה זרע, אם הוא בתוך שלשים יום או רק לאחריו. יש נפק"מ.
[fn:6] עונה הוא זמן רגילה שבו משקה אותו.
[fn:7] גמרא לא מבאר דין זה, אבל מסתמא ביאור שלו הוא שווה לביאור של רישא שלו, והוא שכיון שמנע ממנו מים נעשה זרע. ותחשב.
[fn:8] כן הלכה.
[fn:9] משנה
[fn:10] אין זה פרט אחר שנצרך, אלא אם הוקשו, נפסלו. פסולם הוא סיבה לדין, ומשנה מזכיר אותו כעין "מה הטעם." (ו., ועיין בשי"ח ש"י)
[fn:11] שאז דינים כזרע, וזמנם הולך אחר נטיעתם. זה קרה בשנה ששית, ואז מותרים הם.
[fn:12] איני יודע כל כך דין זה. אפשר שהם דברים שלא נאכלים, ואז הו"א שדינם כזרע. אם כן, קאי על הסיפא. גם אפשר שהם נאכלים, ולכן אין דינם כזרע. אם כן, קאי על הרישא. ותחשב.
[fn:13] מרביצים במים כל העפר שבין האילנות. (נראה שמרביצים רצה לומר שנותנים מעט מים, כדי שלא יעלה העפר. נקרא מרביצים על שם שיעור המים שנותנים בו, על שם כוונתו, או על שם שניהם.)
[fn:14] בשביעית עצמו.
[fn:15] גמרא (ו:) מפרש שיש פעם אחת שאפשר שרבי שמעון אוסר, והוא כשיש שני תנאים:במרווחים. ר"ל, כשיש פחות מעשר אילנות לבית סאה. שם, הדין הוא שאסור לרבץ במועד לפי רבי שמעון, אבל מותר לעשות בשביעית. גמרא דן מהו החילוק, אם הוא מפני שאיסור מועד בא מטורח, ולא נאסר טורח בשיעית, או מפני שיותר נצרך בשביעית, כיון שהוא זמן ארוך.לצד שני, שבע ימים אחרונים של שביעית אסור, שאין עוד זמן שביעית ארוך. (יש להעיר שלפי זה, היה אפשר לומר שרק מותר יום אחד בתוך כל שמנה ימים של שביעית. וצריך להגדיר). גמרא מוכיח מברייתא נגד דין זה.אף אם נאסר, עדיין רבי שמעון אומר שמותר אם יש עשר או יותר אילנות לבית סאה. אף אם יש פחות, מותר להמשיך מים מאילן לאילן, ורק אסור לרבץ ביניהם.
[fn:16] פני משה פירש שמערבים עם מים. איני יודע כל כך למה לא אומר מילת השקאה, אבל אולי זה משמע שנותן יותר מים, או שאחר שנותן מים, מערב בידיו.
[fn:17] זומרים עלים כדי שיתגדל ביותר.
[fn:18] פרק שלישי
[fn:19] משנה א
[fn:20] דין זה נוהג בשביעית. דן גמרא אם נוהג דין זה אף בתוספת מדרבנן גמרא; וכאורה, אם תוספת מדאורייתא, לא יהיה דינו שווה משביעית עצמו), ומסיק שלא נוהג.
[fn:21] הענין כאן הוא כך: אסור לאדם לזבל שדהו בשביעית. כאן, אסרו, מחמת מראית עין, להוציא זבל כיון שנראה כמזבל שדה שלו. לכאורה, חוששים שמיד יפזר אותו ויזבל את שדה שלו ממנו.
[fn:22] יש גורסים עוברי עבירה. שני הגירסאות אומרים דבר שווה: אחר שאינו רגיל לזבל שדה, מותר, שיודעים בני אדם שלא מכוון לזבל מיד, אלא משאר אותו על השדה, ואף ללאחר שביעית.
[fn:23] מתוק הוא מים שבא בתוך בקעים קטנים. אחר זמן הגשמים, החמה מגיע אצל בקעים אלו ומייבש אותם.
[fn:24] ר"ל, הזבל נתקשר, ואינו עוד לח. ר"ח אומר (ז.) שמתיר אף אם רק עליון נקשר. (מד"א אחר מפרש בגמ’ שצריך להיות "קשרים קשרים.” אין אני יודע אם כוונתו לחלוק על ר"ח.
[fn:25] גמרא מפרש (ז.) ש"קרובים אלו להיות כדברי אלו.” לכאורה, אומר ששלש אלו הם דומים בשיעור שלהם.
[fn:26] משנה ב
[fn:27] ר"ל, כמה מזבלים.
[fn:28] ר"ל, בזמן שמותר לזבל (שמפורש במשנה לעיל).
[fn:29] אבל, אין ממעטים את המשפילות. רבי ירמיה אומר שממעטים מהם אם אף ממעטים מן אשפות. (לא הבנתי ל"ל אומר ר"י שממעטים אם לא מוסיפים אשפתות, שכן יצא משיטתו במה שאומר על "מוסיפים על האשפתות.” עיין בשי"ח ש"י.) רבי יוסי חולק ואוסר. (ז.)
[fn:30] כן הוא שיטת רבנן, אבל רבי מאיר חולק. (ז.) נראה שרבי מאיר גוזר הוספה על אשפולים מחמת הוספה על אשפתות.
[fn:31] לכאורה, יכול להיות שלש ציורים:כשנותן יותר מעשר משפלות באשפה. לא מפרש גמרא הדין בזה, ואז נראה שהוא שווה ל2.כשנותן עשר אשפלות באשפה. רבי ירמיה מתיר, ורבי יוסי אוסר (ומביא הוכחה מברייתא).כשנותן פחות מעשר אשפלות באשה. כאן, כו"ע מודה שמשנה מתיר, שהרי יותר נראה כמזבל. (ז.)
[fn:32] לא מפרש אם יכולים למעט אשפתות, אבל מסברה פשוט שמותר. רבי ירמיה מתיר אף אם ממעט אשפלות (כמו שכתבנו לעיל), ורבי יוסי חולק.
[fn:33] לכאורה, אז, לרבי שמעון, אין שיעור לאשפתות, שלכאורה מותר למעט אשפתות, ור"ש מתיר אף להוסיף על אשפתות. גמרא מוסיף בהלכה שני (ז.) שאף יכול לתת עד שלש אשפלות לאשפה, ואף כשמרבה אשפתות.
[fn:34] משנה ג
[fn:35] רבי שמעון מתיר יותר. (יש גירסאות משונות במשנה זה, אבל נפרש כפי הפני משה. כמו שאמר מסתבר בירושלמי.)
[fn:36] מקשה גמרא (ז.) שזה אותו שיטה שאמר במשנה א. מפרש ששם התיר אם נותן עשרה אשפולות בכל אשפה, וכאן מתיר אף אם נותן פחות מכך. גמרא מפרש (ז.) שלא יפחות משלש אשפלות לאשפה.
[fn:37] לכאורה, זה לשיטתם, כבשמנה לעיל.
[fn:38] אז, הוא ברשות בפני עצמו. אז, אינו נחשב בתוך שדה שלו, ופשוט שרק מאצר אותו.
[fn:39] שפשוט שנותן אותו שם לאצור עד שיפזר לאחר זמן, אבל לא מוכח שיפזר אותו מיד. אם כן, אין מראית עין.
[fn:40] שבני אדם יאמרו שממה שמביא כל כך כאן, צריך לומר שיפזר מיד.
[fn:41] גמרא (ז:) מפרש שחולקים אם יכול להוציא אשפה בפחות מכדי אשפה כשדעתו לגדלו עד שיש אשפה. (בגמרא דן אם רבנן מתירים אף להתחיל אשפה כן או רק להוסיף.) (כן נ"ל בגמ’. עיין בשיחתא דש"י.) ראב"ע אוסר מאחד משני טעמים:מראית עין, שלא מבינים בני אדם שעושה אוצר. רבנן דוחים שכליו מוכיחים עליו.חוששים שמא לא יוציא כדי אשפה ונמצא שזבל.
[fn:42] לכאורה, היתר זה יתיר בשאר ציורי משנה גם כן. יש לדון למה רק שונה אותו כאן.
[fn:43] משנה ד
[fn:44] ר"ל, מביא בהמות שם, ומזבלים את השדה.
[fn:45] לא מבאר למה אסור לעשות יותר. אולי נראה הוא שמזבל את שדה שלו, ואז נראה לבני אדם כמלאכה (ואף שבאמת מותר כיון שהוא עושה אותו על ידי בהמות).
[fn:46] יש שני פשטים בזה. אולי אומר שבין הכל, לא מזבל בית ארבע סאים, אלא מזבל בית שמנה סאים. אז, עושה ארבע מקומות, כל אחד נוגע לחבירו בצד אחד, ויתד אחד לכל אחד. פני משה כתב שמוסיף שמונה סאים. אז, עושה כעין cross.
[fn:47] מוציא זבל.
[fn:48] רצה לומר, לתוך אשפתות.
[fn:49] גמרא (ח.) דם אם מתיר אף קודם שפסקו עובדי עבודה, כיון שלא נראה כמזבל, אלא כמפנה סהר, כיון שהוא לעולם מלא, או שמתיר אחר שפסקו עובדי עבודה, וצריך משנה להשמיע כן כיון ש הו"א שרק מחצר, שדרך לפנות ממנו לנקותו, מותר.
[fn:50] משנה ה
[fn:51] גמרא (ח.) שזה אף אם לא פותח, אלא שכבר פתח, אם אין לו אבנים. לכאורה, כן מוכח מן המשנה, שהרי מתיר רק אם יש פא’ אבנים. אם אין שם, צריך לומר שכבר התחיל, שיש אבנים, אבל עדיין אסור.
[fn:52] מחצב הוא מקום שחוצבים ממנו אבנים. פתיחת מחצב הוא כשאדם מתחיל לחצוב משם.
[fn:53] איסור זה הוא מפני מראית עין, שנראה שמוציא משם כדי לתקן את שדהו (שלא יהיו בו אבנים). לכאורה, הבעיה בתיקון זה הוא שמוכיח שכוונתו לזרוע.
[fn:54] ר"ל שלש תלים.
[fn:55] פני משה מבאר שכל אחד הוא שלש על שלש ברום שלש. אז, לכל אחד, יש עשרים ושבע אבנים.
[fn:56] יש לדון אם השלש מרביות מעכב (וצריך להיות אותם עשרים ושבע מסודרים כך) או לא (ומשנה רק מזכיר אותם לדרך להזכיר כמה צריכים, שכך היו מסודרים). נראה כצד ראשון, שאי לאו הכי, היה לו רק לומר עשרים ושבע.גם יש לדון אם צריך להיות שאלו היו לו מתחילה (יש לדון בשיעורו), ושוב מחצב, או אם יכול אדם לעשות אלו ומיד לחצב. ותחשב.
[fn:57] גמרא (ח:) מביא מחלקת בציור של משנה. רבי יהודה אומר שמשנה שלנו הוא בסתם אדם, אבל אם נראה שלא מתקן שדהו (למשל, אין דרך שלו לתקן שדה שלו), אז מותר אף בלי זה. רשב"ג סובר שמשנה הוא רק במי שלא נראה שמתקן שדהו, אבל באדם סתם, אף בכעין משנה שלנו, אסור.
[fn:58] משנה ו
[fn:59] עיין לקמן, שאין זה השיעור לנטילת אבנים מאת שדה שלו. נראה שאולי החילוק הוא שלא היה, בדר"כ, אדם סותר גדר כדי לבנות, ורק היה סותר גדר כדי לזרוע. יש לדון.
[fn:60] כל אחד הוא של משאוי של שני בני אדם.
[fn:61] ר"ל, מותר ליטול את כל האבנים (ואף הקטנים מאלו; פ"מ כ’ ש"מתוך שהותרו אלו, הותרו כל האבנים).
[fn:62] אבל, בלי זה, לא ינטלו, מאותו טעם של משנה הקודם. במשנה זה גם כן חלקו רבי יהודה ורשב"ג אם משנה שלנו רק בסתם אדם או רק במי שלא נראה כמקתן.
[fn:63] ר"ל עד שנשאר טפח סמוך לקרקע, אבל לא יעשה שמה שנשאר בארץ הוא פחות מטפח. (כ"כ פ"מ)
[fn:64] שלא נראה כמתקן, כיון שאינו שלו.
[fn:65] קטע זה אינו מבואר. לכאורה, מה שיוכיח לנו ביאור שלו הוא הקושיה שיש להקשות ממה שאומר גמרא שריקה אסור, ומפרש פני משה שכבר פתחו לפני שביעית, אבל לא נשאר משם אבנים. לכאורה, שני דינים אלו סותרים זה את זה. נראה שיש שלש חילוקים שיכולים לומר:אולי יש לחלק בין מחצב לגדר. אולי אותו דין הוא רק במחצב, ודין זה הוא רק בגדר.אולי יש לחלק בין אם היה נוטל ממנו כל זמן לאם הפסיק באמצע. ויש לדון מהו השיעור של ההפסק.אולי שם אין אבנים נשארים. אז, לא יודעים שכבר התחילו. אבל בגדר, אם התחילו, ידוע הוא.
[fn:66] משנה ז
[fn:67] גמרא (ח:) מבאר שלא צריכים שממש זעזעתם, אלא זה שיעור בעומקם, שצריכים להיות בעומד שיזעזע אותם המחרישה. הראיה לזה הוא שאבנים גדולים כאלו בוודאי לא יזעזו. (צ"ב מה בכלל שיעור זה, אם הולכים אחר עומקם או אם הולכים בתר איזה פרסנ"ט הם הוא בקרקע.)
[fn:68] לכאורה, בא לחדש שאף שיותר הם כחלק מן השדה, היו מתחילה מכוסות, ולא היו נתזעזים, כיון שעכשיו הם רק בעומק שיזעזו, מותר להוציא אותם.
[fn:69] כ"א הוא משאוי של שני בני אדם.
[fn:70] איני יודע אם רק אלו מותר להוציאם או שאז מותר להוציא את הכל. לשונו משמע שרק שנים אלו מותרים.
[fn:71] ר"ל, אם אינו כשיעור זה, אז רק יכול להוציא מה שאינו נוגע בקרקע.
[fn:72] הוא שווה לאבנים, אלא הם יותר קטנים.
[fn:73] ואז לא נוגעים בארץ שרוי להיזרע.
[fn:74] משנה ח
[fn:75] לפעמים, היו זורעים על הרים. כשעשו כן, עשו מדרגות כדי שיוכלו לזרוע שם.
[fn:76] גמרא (ח:, ט.) נותן שני ביאורים לזה:אסור כיון שהוא מתקן לשביעית, והתורה אמרה שלא לתקן לשביעית בערב שביעית, שהוא תוספת שביעית. אז, זה רק קודם שבטלו אותו דין. מקשה גמ’ שא"כ אף ייאסר לעשות בשביעית לשמינית, ומתרץ שרק אסרו דבר שהוא מעשה לשדה. (לא מבאר למה מניחים שאסרו דבר שאינו מעשה בשדה בהכנה לשביעית. נראה שמלאכת שביעית צריך להיות בגוף השדה. בתוספת קודם, הוא לזריעת שביעית, וזריעה הוא מלאכה בשדה. אבל, בתוספת לאחר כן, הוא בנין בשביעית, וזה אינו בשדה. ותחשב.)אסור כיון שמראה שהוא יזרע בשביעית, שאל"ה היה שוהה עד זמן יותר קרוב לשמינית. מקשה גמרא שכיון שלא מניחים שאדם יזרע בשביעית (שהרי מותר לחרוש בתוספת לפני שביעית), יהיה מותר לתקן כל שביעית, ולא רק לאחר שפסקו גשמים. (לא מבאר למה לא מקשה מזה על איסור תוספת שביעית. אולי יש הוכחה שהיה לו לשהות עד יותר קרוב לזנה שמיני רק אם בנה בתוספת שביעית, ולא אם הקדימו בשנה שביעית עצמו.)
[fn:77] לא יתקן את עפר השדה שקרוב לו.
[fn:78] עושה מחיצה קטנה בינו לשדה. יש לדון מהו הדין במחיצה גדולה.
[fn:79] ר"ל, כשהוא עומד על המדרגות, יכול לשלוח ידו וליטול אבן.
[fn:80] מסתמא, הוא מפני שאז נראה כתיקון מדרגות, ולא כתיקון השדה. (ויש לדון למה, שאינו על המדרגה, ואז אינו מונע את המדרגה כלל.)
[fn:81] משנה ט
[fn:82] משנה יפרש מה הם.
[fn:83] ר"ל, נוטלות אותם מכל שדה, ואף שדה שהוא שלו.
[fn:84] ר"ל יכול ליטול פחותים מן השדה שמקבל.
[fn:85] איני יודע למה אין דין זה נגד מה שאומר לעיל (גבי אבנים שיזעזע אותם המחרישה). אולי דין זה כשלא נוגעים בארץ, וכסיפא שאל אותו משנה.
[fn:86] ואז ניטלים על כתף.
[fn:87] לא הבנתי מילים אלו, שאף לר"מ, נקראים כן ע"ש כתף, שאחת ניטלת על הכתף. (ויש לדון, שאולי ניטלת בשני ידים.) גם יש להעיר שלכאורה, יש דברים שצריך ארבע עד שניטל בכתף, וממעט אותם. אז, אינו כל שהוא בכלל השם.
[fn:88] נראה שר"ל שכשיש שיעור זה ניטלים על הכתף. אבל, ממעט אלו שצריך יותר להיות ניטלים על הכתף.
[fn:89] משנה י
[fn:90] הוא דווקא בינו לר"ה, שאז יוזק בלי כותל. הוא גם דווקא אם לא נשאר שם קצת גדר. אבל, אם נשאר שם קצת גדר, אסור"ש לא יוזק. (אבל, אם מה שנשאר יזיק בני ר"ה, מותר.) (ט.)
[fn:91] לכאורה, ר"ל שאין מקלקלים רשות הרבים, אף על מנת לתקן אותו לאחר זמן.
