* ב.
** מפני מה אמרו -
צריך ביאור איזה טעם יש בזה; הוא רק תוצאה. צ"ב.
ועיין במאירי (“תמה בעצמו היאך היה תולה משנתנו שטעם רביעי הקבוע נזכר בה מדין טענת בתולים במשנת הגיע זמן שאין בה סרך לרביעי כלל שהרי כל הימים שוים להגיע הזמן") שאומר שכן היה קושייתו על עצמו. (אז, ביאור גמרא הוא שתלה מה שפירש טעם (רצה לומר, משנה שאומר בו דבר שיכול לפרש טעמו) בדלו מפרש טעמו (רצה לומר, בדבר שאינו יכול לפרש טעמו). ותו"ת.
* ב:
** דלא מציא אמרה -
שלא נעשה נדה מפני מזלו, שמסתמא היתה נעשה נדה בלי זה, שלעולם נעשה נדה אז. יש לדון, שאולי נשא אותה לפני אותו זמן מחמת מזלו[fn:1]. ותחשב. ונראה שאולי תלוי מהו סברה זה, אם הוא שכיון שרואים שרע בא לו (שאי אפשר לו לישא), רואים שרצה ה’ לענשו, ואז מסתבר שרצה ה’ שעיכוב זה יגרום רע לו, או שהןט שמסתבר שבא לענשו (כיון שדרם רע לו), ואז נמצא שהוא הגורם שלא ישאו. כיון שכן, חייב. נראה שרק לראשון יש לומר כמה שכתבנו. (ויש לדון לשני, שלא גורם שלא ישאו עכשיו, אבל גורם שזמן שהייתה גדול על יב חדש.ותחשב.)
** כיון דאיכא -
לא הבנתי למה הוא חלוק מחלה, שאף יש נשים שנעשים חולה מעצמם (ולא לעונש החתן). ותחשב.
** היא גופא -
קשה, אז, למה לא אומר ברייתא, אז, דין זה בפירוש. ותו"ת.
** אונס -
יש לדון למה יהיה אונס בגיטין. לכאורה, הוא שיש אומדנא שכן מתנה.
** איהו דאפסיד -
לשון זה מעניין, שלכאורה, היה לנו לומר שאז משמע שהוא אף שם. מלשון זה, משמע שהוא שהוא גרם הפסידו; ומשמע שהסיבה שלא היינו אומרים כן הוא שאין לו להפסיד. ותחשב.
* ד.
** תניא -
יש להעיר שלא אומר באיזה מקום הוא, ואז היה אפשר לומר שאינו אומר כר"ח. (ואפשר, אבל לא מסתבר) שבשאר מקומות אין חילוק בין אם נתן מים או לא, ואז כשמחלק, מוכרח כר"ח.)
** אפירסה -
לכאורה, כן מוכרח, שהרי כאן בהכרח בעל בעילת מצווה, ולא קשה רק שאין הדין כן, אלא שאי אפשר לחלק בזה, שיש רק ציור אחד. ואולי זה קושיית גמרא.
* ד:
** קילא -
מניח שהוא יותר קל לו. היה אפשר לומר שהוא מפני שהוא יותר חמור (ויותר רע אם יעבור). לכאורה, אין זה נראה, שאיסור נדה יש בו חיוב כרת.
** באפה -
יש לדון למה מתאבל:
אפשר שהוא מפני יחס למת. אפשר שהוא שהוא- כאחד מן הקרובים- חייב באבילות מחמת מיתה. צריך לומר שכדי להיות מיוחס למת, צריך להיות עמה.
אפשר שהוא מפני יחס לאשה. יש בזה שני צדדים:
אפשר שהוא שצריך לנהוג בצער כיון שרואה אשתו בצער.
אפשר שהוא שצריך לנהוג בצער לכבד אשה (כדי להראות שהוא עמה בצרה).
** רב אשי -
יש לדון אם מחלק באבילות שלו, שלה, או שניהם. גם יש צד, והוא שרק אומר חילוק, ואינו יודע באיזה ציור יחלק הדין, ואפשר כזה ואפשר כזה. ותו"ת.
* ה.
** של מצווה -
יש לדון אם הותרה או דחוייה. אם דחוייה, אולי יש לומר שמשנה אומר שיש לו לשהות עד יום אחר, שאז מקיים שניהם. ותו"ת.
** ידחה -
קל לדחות קשיא זה לומר שיותר קל לדחות נשואים מלדחות יום הכיפורים. ונראה שר"ל שבית דין ידחו את החדש, וזה אינו כל כך קשה.
** השתא דאתית -
עיין ברש”י לקמן שדן אי ידע מי ששאול על ביאה בערב שבת אותו ברייתא. יש לומר שידע אותו, אבל ידע שיש לדחות כגמרא כאן.
* ה:
** מיפקד -
קצת צריך לבאר למה זה חלוק מכל דם, שכל דם יושב בarteries ובveins, כמו זה. ויש לומר שרצה לומר שזה רק יושב, ולא עושה כלום, מה שאין כן שאר דם שהוא הולך מלב וללב. ותחשב.
* ו.
** דבי רב -
בדרך כלל, בי רב הוא בית מדרש. כאן, ממה שאמר ר"נ, רואים שר"ל בית מדרש של רב. יש לדחות שאף ר"נ רק אומר שנראה שאלו מקילים לעצמם ואלו מקילים לעצמם, שנראה בית רב להיות בית מדרש של  רב, אבל באמת אינו. ותו"ת.
* ו:
** כדשמואל -
קשה למה צריך לומר כן, ששמואל התיר אף ביאה בשבת. ויש לדון, שאולי כאן אינו מפקיד. ותחשב. גם יש לומר שרבא מבית רב. קשה איך נהרדעי יפרשו את זה. נראה שאין הכי נמי יאמרו שהוא ראיה לשמואל רבם, שלא ישנו שיטת שמואל שאומר רבא. גם יש לומר שיאמרו כאותו דין מסברה.
** טרדו למה -
לא הבנתי גמרא זה כל כך. יש לדון מהו קושיה זה:
אפשר ששואל למה יטרד לבעול כיון שקל לו. לא נראה, שהרי טרדה הוא מפני ששמא לא ימצא דם. אז, נראה שאולי מקשה שבין כך ובין כך הוא לא ימצא דם. קשה, אז, מהו תירוץ גמרא, שרק לכעין לו מותר לעבור, ואז אין טרדה לאחר:
אפשר ששואל בטירדה על שלא יכול לבעול, ומקשה למה לא יבעלו בקיאים, ואז לא יטרדו, ואומר שאין הכי נמי, ועל מי שאינו בקי קאי. ויש לדון, שאז יש בוודאי מי שפטור, והוא בקי, שיכול לבעול, ואז טרוד. ואולי אומר כצד ראשון בזה, שלא יטרדו.
צריך ביאור מה חוזר גמרא להקשות על זה- אם כן יאמרו. אולי רצה לומר שאם כן יאמרו שרק זה חייב בק"ש. ודחוק. (עיין במאירי שאומר: “לענין ביאור סוגיא מה שאמרו כאן טורד למה פירושו אחר שבקי בהטיה מהו טרדו ליפטר מק"ש ואחתן קאי ותירץ למי שאינו בקי והקשה ויאמרו בקי מותר וזו ודאי אבעילת שבת קאי כלומר אחר שאתה מחלק בפטור ק"ש בין בקי לשאינו בקי אף בבעילת שבת יש לך לחלק ואם כן יאמרו וכו' והשיב רוב בקיאין הן וכל אחד דנין אותו אחר הרוב ומותר הא לענין ק"ש על כרחיך כל שאינו בקי טריד הוא וטרדתו פוטרתו.” קצת צריך ביאור מה אומר, שקשה למה דנים אותו בתר רוב, שאם יודע הוא שאינו בקי, למה נדון אותו כן יותר מבק"ש, ואם אומר שספק הוא, ואז אומרים שהוא כרב, קשה איך נדע לפוטרו מקריאת שמע. נראה אולי שכל שאינו בקי הוא ספק, ואז יכול לבעול בשבת, אבל פטור הוא מק"ש, שמחמת אותו ספק, טרוד הוא. ותו"ת.
** מתיב -
צריך לחשב בכל קושיית גמרא מה מוכיח, שידוע שאולי יש חילוק בין שני תנאים, ואז צריך לבאר איזה צד דוחה.
* ז.
** פטור -
קשה, שזה רק מפני צער (כן משמע בשבת). ואולי כאן כיון שיש צורך מצווה, הוא כצורך צער. גם יש לומר שיש צער מטירדתו.
** פקיד -
יש לדון מהו הענין:
אפשר שהענין הוא שאז דומה ונראה ככל דם איברים, וגוזרים עליו. דמיונו הוא רק מה שקצת נבלע כמותו.
בארנו שחילוק בין zדם שמיפקד לשאר דם הוא, אולי, אם מהנה לגוף (וזה מסתבר, שאיסור של הוצאת דם הוא שחיטה, וזה, כמובן, הוא רק אם ממית או עושה כעין זה. אם דם מיפקד פקיד, הענין הוא שאינו מהנה אותו, ואז לא גורם שיסלק חיות כשמוציאו). אולי, אז, כאן כיון שמובלע, קצת מהנה אותו. אז, במה שהוא עושהו מלאכה, דומה לו.
** הוראה -
יש לדון למה לא יהיה הוראה:
אפשר שדן אם כשפוסק בעיון להחמיר נקרא הוראה, כיון שמעיין, או לא, כיון שהוא הוראה של מה שאין בדרך כלל מעיינים (או שהוא הוראה עם עיון שלא היה נצרך, שיש לנהוג כמותו אף בלי העיון, ואז מה שעיין לא חשוב).
אפשר שדן אם הוראה משמע שעיין או לא.
אפשר שדן אם יכול לעיין לחומרא, שאולי כיון שאין כל כך נפקא מינא (רצה לומר שכיון שחושב בסברה חיצונה שהוא אסור, מסתמא כן הוא, וכיון שמסתמא לא יהיה בו שינוי, אין לו לעיין), נחשב ביטול ת"ת קצת. ותחשב.
** עליך -
בפשטות, רצה לומר שעל דינך אומרת תורה…. היה אפשר לומר שאומר "אטו עליך, שאתה רוצה מוגמר, אמר קרא?!- לא! אמר קרא….”
* ז:
** לפרסומי -
מעניין שצריך זקנים כדי לפרשס. ואפשר שמה שצריך עשר לפירסום אינו שאז ידעו יותר בני אדם, שמניחים בדרך כלל ששלש בני אדם מוציאים קול (בלשון הרע) או שנים (בחזקה) (ויש לחלק שכאן, אינו כל כך מעניין לבני אדם, ולא ידברו בו כל כך. נראה שאולי צריך זקנים כיון שלהם הוא מעניין, וידברו עליו.). אלא, נראה שאולי הוא שפירסום הוא מפני שיראו שכל כך כמה תלמידי חכמים קבלו דבריו. ואף בלי זה, ידון אם הוא קשה. ותחשב.
** רבי יוחנן -
משמע שהוא אמורא (וכן אומרים ראשונים), שלא אומרים שתנא הוא ופליג.
* ח.
** ולבסוף נברא אחד -
יש לדון מהו "אחד" או "שנים":
אפשר ששנים הוא שנבראו שני בני אדם (אדם וחוה).
אפשר ששנים רצה לומר שיהיו שני בריאות, שה’ יברא אחד עם זנב, ויברא אחד מזנב.
נראה כראשון, ממה שאומר שלבסוף נעשה אחד, והוא מפני שידוע לנו שלמעשה רק אדם נעשה. ויש לדון. אפשר לדחות שזה רק מפני שגמרא הוא עכשיו על הצד שאחד נברא, ולא שנים. אם כן, צריך להסיק שכם נעשה למעשה. ויש לדון, שאף שמתרץ לאותו צד, אין אותו מימרא ממש צריך לסבור כאותו צד. יש לדון, שאולי בלי זה, יש לומר שנאמר בריאה אחת כיון שכן נברא מתחילה, ושני בראיות כיון ששני קרה לאחר זמן.
* ח:
** רבים ישתו לא -
יש לדון, שרק אומר שלאחר זמן ימות, וזה בוודאי יהיה. אולי יש צד שמשיח יבא, ולא יהיה מיתה (אולי), ואז מונע אותו.
** יושנו -
משמע שעל זה לא נעשה שכור. עיין בשיח שי (פרק ערבי פסחים (בשני מקומות)).
** לא לימא -
יש לדון אם רק אומר שאף שהוא אמרו (באותו מעשה שלעיל), אין לאומרו, או שאמר שלא אמרו. ותחשב. לשונו משמע כראשון.
* ט.
** מאי קמ"ל -
יש להעיר שכאן לכאורה מחודש הוא שהוא רק איסור דרבנן (אם ספק דאו’ לחומרא הוא רק דרבנן). אולי משמע שאינו מדרבנן. ויש לדון. (אפשר שתלוי באם אומרים שאמירה זה יש בו שום נאמנות, או שהוא כעין נדר (איני יודע כל כך מהו צדדים אלו, אלא שיודע אני שדנים בו אחרונים), שאולי לשני אין לחלק.)
** לא קים -
אף שאין זה, אולי, כל כך מסתבר, נראה שאולי רצה לומר שאז יש ספק ספיקא (שמתחיל בספק, כמו שאומר גמרא).
** קמ"ל -
יש לדון אם הקמ"ל הוא שאין מניחים כן, או שאף בלי זה, כיון שהוא אומר שהוא חושב שהיא אסורה לו, זה מהני לאסרה עליו (ואף שבית דין חושבים שהוא טועה. ותחשב.) ויש לדון, שאולי אף הוא מודה שאינו קים ליה כל כך.
[דקטעין- נראה שר’ שמעי’ כתב גמרא זה, ש"טען טענה… "]
* י.
** והא ר"נ -
נראה שסבר מקשה שכיון שהוא רשע (ומכיר), אינו נאמן, שרשע הוא.
** אין כמותם -
עיין גמרא תמיד (כז:) שמשמע נגד זה.
* י:
** ספק נדה -
מעניין שלא מזכיר מה שמותר לבעול אותה לעולם, שלא תהיה נדה.
** במנחה -
מעניין למה לא אומר ש"כאן במנחה… "
* יא.
** זכין -
משמע שיכול לזכות לקטן.
* יב.
** כדי שיהא לבו גס -
יש לדון למה רוצים זה; לאחר זמן אחר שישאו, יהיה לבו גס בה. ותחשב.
* יב:
** כיון דחזו -
יש לדון אם הוא מפני שהוא רק מנה- ואז, אף מזלזלים על אלמנות ישראל, אלא שלא חשו לזה, שאינן טעונות כל כך כבוד- או מפני שהם כל כך פחותים מבתולות של מינן.
** עושים -
ק"ק למה לא יעשו; יכול אדם להוסיף כל מה שרוצה.
** מגו -
עיין לקמן, שמוכרח לר"י שאין מגו.
* יג.
** הלכה -
היה אפשר לומר שאינו קשה הל’ על הל’, שאין הלכה כשמואל כשפסק כן (מוצאים שיאמר אדם הלכה, ואין גמרא פוסק כן).
* יג:
** בשלמא -
נראה שמה שמזכיר שנים הוא שבחד מקום יש לחוש יותר שהיתה נבעלת, ולא הוה ספק כל כך.
** אמר רבה -
יש לדון מה סובר רבי יוחנן. אפשר שסבר שיש חזקה. גם אפשר שסבר שהדין כן אף בלי חזקה. יש לדון למה. אולי הוא כדי שלא נחלק בין דינם, ואפשר שהוא מפני שהיא ממש נאמנת כיון שטוענת ברי. ותחשב.
** שבויה -
משמע שהדיון הוא אם נבעלה או לא. יש לדון, שרק אומרת שלכשר נבעלת, אבל מודה שהיתה נבעלת. נראה שאולי דן באם היתה נאמנת לומר שלא נבעלת, שאז יש מגו, כמו שאומר גמרא לקמן (ריש פרק שני). ותו”ת.
* יד.
** ברי -
כיון שהגענו לזה, אי אפשר לומר ש"בודקת . . ." שמה לנו במה שדרכה לבדוק; הרי כאן לא טוענת בברי. אז, מוכרח הוא לתרץ לר"י באופן חלוק, ולכן לא מבאר כתירוץ גמרא לעיל. ודע שאפשר שרצה לומר שאמו נשא מי שהיה אולי חלל, ומניחים שבדק אמו. ותחשב.
** הלכה -
היה אפשר לדחות שאמר הלכה רק לבאר איזה סברה נראה יותר. ויש לדון.
* יד:
** רבי יוחנן בן נורי כמאן -
דע שהיה ריב”נ חבר של ר”י ור”ג. אם כן, יכול לחלוק. אפשר שרק אומר שלשון גמרא לא משמע שחולק.
* טו.
** מרובא -
קשה, שאף בסיעה נאמר כן. יש לומר שענין סיעה הוא שכיון שאינם במקומם, לא ילכו לנשים. אלא, מסתמא תבא להם. ותחשב. גם יש לומר שכשבא להם, אומרים ששניהם הלכו להדדי, שהרי אף הוא הולך, אבל אם אשה הלך לבן העיר, נחשב שרק היא הלכה. ותחשב למה. ויש לדון.
* טו:
** ומודה -
דע שיש חוקרים בכוח מרי קמא, אם הוא מוחזקות של מוציא מחבירו עליו הראיה או חזקת איסור (מה שמניחים שאין דברים משתנים). נראה שממה שמניחים שזה שייך למחלקת ר"י ור"ג, אף ששם שייך למוציא מחבירו עליו הראיה משמע כצד ראשון. ויש לדון, שאולי מניח ששניהם דומים, או שעדיין ציור שווה הוא עם מחלקת דומה. ותחשב.
* טז.
** ואם יש עדים -
יש אומרים שאין חזקה כשיש מגו, והחילוק הוא אם כבר טען לו. קשה, אז, למה אומר ציור זה, ולא ציור שכבר טען לו. אפשר שלא מצוי כן. ודחוק.
** ודקארי -
לכאורה, היה מצי לומר שחשב שחלקו אף על ציור של נתארמלה, והרי שם, אם נאמר שהיורש הוא בנה (וזה מצוי), פשוט שהיורש הוא רק ספק, שלא היה שם לדעת.
** לכהן -
ואת תאמר למה לא אמר שיש עוד נפ"מ למנה ומאתים. ויש לומר שזה מחלקת. ותחשב.
* טז:
** אי אפשר -
לא הבנתי למה באחד יותר אפשר מחברו (עד שרק כאן אומרים שיש ראיה). ותחשב.
* יז.
** רבי יהודה -
יש לציין לברכות (סוגיה של בעל קרי) שחושב אני שאומר שביטל תלמוד תורה לכלה.
* יח.
** אי אליבא דראב”י -
למסקנת גמרא, אינו כן, שזה רק כשיש שום טאנה, לכאורה (ויש לדון, שאולי לא יעיז שלא להודות), אלא מוכרח בזה כרבנן. קשה, אז, למה אי אפשר לומר כראב”י, ולכן רק אפשר להיות בדלא טען. וצריך ביאור. ותחשב. (ויש להעיר שאם היה כן, היה טוב למה לא תני אותו ציור בציור הקנטרס”ט, והוא שאין לו דין שקנטרס”ט מאד. ותו”ת.)
* יח:
** שוב אינו חוזר -
היה אפשר לומר שכלל זה שאינו חוזר ומגיד הוא רק שמוכרח שבאחד מהעדאיו הוא משקר. מניחים, אולי שהוא השני. יש לדון למה. ואולי עיין בצדי צדדים על פרק יש נוחלין, שדברנו בו קצת. (אחר כך נתעורר לי שאולי לא מניחים שבראשון שיקר מפני שאז אולי יהיה גלגל החוזר, שעל ידי זה נמצא רשע, ואז לא יהיה כוח עדות בעדות שני. ויש לדון, שנראה שאין צריך כוח עדות בצד זה, שרק צריך לדחות כוח עדות ראשון, ובצד זה מניחים שהוא שקר, ואין לו כוח. ויש לדון אם אין לו כוח. גם יש לומר שאין צריכים כוח עדות כיון שכבר שקר הוא, ואינו צריך לידחות. ותו”ת.) מגמרא זה לכאורה מוכרח נגד כן, שכאן, אין הוכחה ששיקר חד פעם; היה לנו לומר שלא משקר כלל, ונאמין את דיבורו השני. ותחשב. אולי ביאורו הוא שכיון שהיה כבר הנחה כן, שם המצב הוא כן, וקשה לסלקו, אף על ידי עדות. כמובן, זה מחודש מאד. גם יש לומר שכל עד שמעיד פעם שני הוא בעל דבר, שהוא אחד מן העדים (וזה יהיה תלוי בסיבת פסול של בעל דבר. ויש לדון. ועיין,  אולי, בחרב אל הבדים ב”ב זמן חורף (מג.)). נמצא שפסול אף שאינו, לכאורה, נוגע בדבר. ותחשב.
** אמר רמי -
רשי מניח שדין זה הוא אף בפוסל את עצמו מחמת קורבה. יש להעיר ששם אינו פסול מחמת האיסור; הענין הוא, לכאורה, שאסור להעיד. אם כן, אולי יותר מחודש שלא אומרים פלגינן בכעין זה. ותחשב.
גם יש להעיר שכאן נאמנותו בא מפה שאסר, ואם כן, לכאורה, אין בעיה של פסול קרוב (שכל האומר פה שאסר מעיד על עצמו). ואולי עדיין יש פסול רשע. ותחשב.
* יט.
** כר"נ- נמצא שלר"נ (עכ"פ, לזה), לא רק יכול לשלם למי שחייב לו מלוה, אלא צריך, שאם לאו הכי, יאמר שלא משלם לו. ויש לדון. ותחשב. ודע שצריך ביאור קצת, שאם משקר, אין להאמינו, ואם לא, אף שחב יש להאמינו. נראה שהענין הוא שכיון שאינו רק רע לו, מניחים שמשקר. אם כן, אולי לא צריך להיות בודאי רע לאחרים, אלא שכיון שיכול אחר לשלם לאחרים מהני. ותחשב. מודה בשטר -
יש לדון למה זה יהיה. אולי לא סובר שיש שום מושג של פה שאסר, ואז כיון שידוע שחבירו יש לו שטר אינו נאמן לפוסלו. וצריך ביאור.
* יט:
** מילתא אחריתי -
צריך ביאור מה זה אומר. צריך לחשוב למה אי אפשר לסתור דיבורו (כלל של כיון שהגיד שוב אינו חוזר ומגיד). אפשר שהענין הוא שאינו משנה את החלות, אלא מוסיף שאולי יש מונע. אין צריך זה, שאפשר שאף אם שטר עושה שצריך יורת לחלות, אינו משנה מה עושה שטר, אלא משנה דבר אחר לגרום שחלות צריך יותר. כמו כן, יש לומר שרק עושה מניעה שעושה שאינו יכול לעושת סיבה. גם יש לומר שעדיין יותר דומה למה שהיה, ואין שינוי כל כך, שעדיין יש קצת סיבה לו לחול, ועדיין אפשר לחול.
יש להוסיף שיש לדון מהו הצד שלא מהני:
נחשב סתירת הגדה כיון שעל ידי זה נתלה. אז, אין כל כך שינוי, אבל בוודאי נעשה.
נחשב סתירה כיון שלמעשה, עשה שלא חל. הדרך שלא לומר כן הוא שאין התנאי בפני עצמה עשה כן, אלא אף מה שלא חל. כמו כן, לא העידו על הכל, שלא העידו על מה שלא חל, ואף אינו ידוע בפירוש (ואז לא בוודאי עשה תנאי שלא חל). ותחשב.
עיין בלשון רש"י של, “לא אתי בעל פה ומרע לשטרא.” צריך ביאור מה אומר, אבל משמע שאינו רק שכיון שהגידו אינם חוזרים ומגידים.
* כ.
** ידי אחר -
יש לדון, שעדיין נחוש שיש לו שטר בידו ממנו, ולכן יכול לזייף.
* כא.
** על כתב ידם -
צריך לחשוב מה זה. דע שאם אומר שממש מעידים שקורה, נצטרך שזוכרים אותו (כמו מה שאומר כגמרא לעיל).
* כב.
** סברה -
יש לדון מהו הסברה. אולי הוא כעין מגו, אלא שיש יותר ראיה, שהיה יותר סיבה לו להיות שותק. גם יש לומר שהוא שכיון שמחמתו היה איסור נוהג, יש לו יחס מיוחד לו שעושה נאמנות. גם קצת משמע מלשון גמרא שהוא כעין אגב, שאגב שנאמן לגבי איסור זה לאסרו, נאמן לגבו להתיר אותו.
ויש לדון, שבדרך כלל, לא אומרים כעין זה, אלא אומרים פלגינן.
** אנשים מהוגנים -
מעניין שבאו עליה מהוגנים אחר שאמרה שהיא כבר נשאת. אולי אמרה להם שאינה נשאת, באמת. ודע שאין הוכחה שהוגנת ר"ל שהם טובים במצוות, שאולי היא כוונה לומר הוגנת לה, וזה שהיו בעלי עושר או כדומה. עדיין מעניין שבאו לה כלל.
** אף בזו -
צריך ביאור למה נחלק.
* כג.
** אם איתא דאגרשא -
היה נראה יותר לומר להיפך, שהרי קידושין הוא דבר של שמחה, אבל גירושין הוא בושת.
** שמואל -
יש להעיר שיודעים שלמעשה היו בנות שמואל נבעלות, שהרי מזה נולד רב מרי בן רחל.
* כד.
** נאמן -
לא הבנתי כל כך נפק"מ של יוחסים. עיין ברש"י. וצריך ביאור. אולי ר"ל שהוא רק אם יכול לומר שהוא כהן, ואין נפק"מ לדין, אלא שאשה רוצה לישא אותו אם אומר כן (ויהיה נפק"מ לדין אם עושה תנאי).
** דרבי יהודה אדר"י -
בכל מקום, רבא הוא האומר כן.
* כד:
** בשכלי -
ק"ק, שאולי מכוון לתקן אותם ולמכור אותם.
* כה.
** לא במידי -
ק"ק למה צריך להזכיר שניהם. ויש לומר שמילתא דאתיא בקל וחומר טרח וכ’ ליה קרא. גם יש לומר שרוצה שיהיה אזהרה אחר שאין מזהירין מן הדין.
** שמעת מילי -
יש לציין לגמרא יבמות (ולירושלמי ברכות, תחילת פרק ראשון) שאומר שלא היה רגיל ר"א לומר שמועת ר"י בשמו.
* כו.
** מדהנך -
נראה שאולי הענין הוא שחולק בשווה, ואף שלנגדו אינו שווה כל כך, שצריך למכור אותו, ולא לאכול אותו. אולי הוה אמינא ומס’ חולקים מה היינו עושים אם היה צריך למכור אותו, אם נותנים בשווה או נותנים לו יותר. ותו"ת.
** יש לדון
למה לא דן מה בין ת"ק לאלו. אולי אלו מפרשים ת"ק. גם יש לומר שגומלים איכא ביניהם. אם כן, לצד ראשון שבגמרא, קשה מה בין ר"י לאלו. ותו"ת.
* כז.
** אי אפשר -
צריך ביאור למה מחמירים כל כך לחוש לכל זה.
* כז:
** שפיר -
לכאורה, אין נפק"מ לזה, שבלי זה, לא היינו מאמינים אותו, אלא אמר כן דרך אגב. ותו"ת.
** תרתי -
אינו ממש תרתי, שזה מניח שיודעים שאינו כן, ומעידים שהוא כן, ואפשר שלא יודעים כלום. ותו"ת.
** ואף על פי כן -
צריך לומר שלא גירשה, שאי לאו הכי, יהיה אסור, כיון שהיה כהן (וצריך לומר שהיה כהן, שבלי זה, לא היתה אסורה לו, שהיא נאנסת).
* כח.
** תנא באב רבתי כו’ -
אפשר שגמ’ אומר כו’, אבל גם אפשר שהמקשה אמר כן, שלא הוצרך לומר כל הברייתא עד שהמשיב הבין כוונתו.
** אימתיה -
נמצא שאדם ירא מרבו יותר מאביו.
* כח:
** בהמתם -
קשה לשיטת תוס’ שאומרים כן רק על איסורי אכילה. ואולי היה גורם איסור אכילת תרומה, וזה די. מסתמא, תוס’ כבר דן בזה.
* כט:
** רבי שמעון -
מעניין שרוצים שרבי עקיבה יהיה טוב עם ר"ש בן מנסיה. חושב אני שגמ’ בביצה (כו) אומר שרשב"מ היה בימי רבי.
** לקיים -
יש לדון מהו המקור.
* ל.
** כל מילי -
זה תירוץ, ואומר שהזהיר אותם על כל דבר, ואף על חיות וכדומה.
** חיה דורסתו -
צריך ביאור למה זה דומה לסקילה, שלכאורה, לא מת מהפלת חיה. ותחשב.
* לא.
** שאכל וקרע -
יש לדון מתי נקרא זמן אכילה. זה שייך לדיון גמרא לקמן של "עקירה צורך.”
** עקירה -
יש להעיר שמימרה ראשונה היתה על יציאת חץ מידו, שהוא חלק מן המלאכה, וגמרא ממשיך לדון בו בהגבהת דבר, שהוא נצרך כדי להוציאו, אבל אינו חלק ממנו. ויש לדון, שאולי מיירי כשמגביהו כשהוא הולך. ויש לדון ל"ל דחה, אז, שהוא עומד כשמגביהו.
* לב:
** אם כן ביטלת -
לא הבנתי את זה כל כך, שמה הרע בביטול הזה אחר שהתורה אמר שתיבטל (שגילה כן על ידי הג"ש). אולי אז קשה למה אמר לאו. משמע שהיה חייב ממון בלי לאו. ותחשב. גם, לכאורה, צריך לאו כדי שלא יעשו כן בני אדם (שהלאו אוסרתו). ותחשב.
* לג.
** אמר ר"א -
ק"ק, שמצאנו פעמים שלוקים (בגוב"ח). שוב ראיתי שרש"י מבאר את זה.
** אישתלין -
נמצא שזהו המקור שאי אפשר להתרות קודם תוך כדי דיבור.
* לג:
** בריה דרב אשי -
אם כן, לשון גמ’ לא מסתבר, שלא מדבר לו בלשון כבוד. אולי גמרא רק אומר פאראפריי"ז. כמו שאומר גמ’ קידושין (בסוגיה של כבוד אב ואם). גם יש לומר שמניח כאן שהיה בן רב אסי. גם יש לומר שהיה בן של רב אשי אחר.
* לד.
** כיון דשחט -
כל גמ’ זה משמע שדבר שאסור בהנאה אינו נחשב להיות של הבעל. ותו"ת.
** שאולה -
לכאורה, ר"ל שאילו היה חייב כבר באונסים, היה חייב ארבע וחמשה. זה מעניין, שלכאורה, לא היה כבר גנב עליו. לכאורה, משמע שאין צורך להיות גנב לחייב בד’ וה’. גם יש לומר שיכול להיות גנב בשבת, אבל רק שלא יחייב, ואז יפטור מד’ וה’ כיון שאין חיוב גניבה. ותו"ת.
* לז.
** ממנעי -
מניח גמ’ שאין חשש זה אם לא אוכלת בתרומה. ותו"ת.
* לט.
** משמשות במוך -
ק"ק למה מותר לשמש כלל, שיהיה לבטלה.
* לט:
** והא לא מצי -
ואם תאמר אם כן לא יהיה שום קנס. ויש לומר שאז חוטא נשכר.
* מ:
** אחד כדרכה -
צריך ביאור מה אהני בזה. אולי בא לומר שלא רק יש חילוק בעל מי עושה כן, אלא אף יש חילוק בין תוצאה של מעשיו (אם גורם פגם או לא). לא נראה כן מקושיית גמרא. אלא, אולי אומר שאם כן יושוו שנים (שני מעשים) שהם יותר חלוקים.
* נב.
** מה לי -
קשה, שעדיין אולי מרמה אם מקיים אותו אחר כך. אולי כיון שלא יכול לעשות כן בכל זמן, לא חוששים כל כך לאותו רמאות.
** ואותבינך -
לכאורה, ראוי בתחילה, ורק לא בסוף. אז, תלוי במחלקת לעיל.
* נג:
** ממאנת איכא -
לכאורה, צריך ביאור ל"ל תזון, שהרי ממאנת עוקר הקידושין למפרע. ויש לדון, שאולי אינו כן. צריך לעיין ביבמות.
* נד:
** שכנגדי -
יש לציין לגמרא ב"מ שאומר בו רש"י שהיה ר"ל תלמיד ותיק של רבי יוחנן.
* נו.
** הלכה למעשה -
משמע שבשאר מקומות שאומר "הלכה,” אינו הלכה למעשה. ויש לדון, שאולי צריך לומר כן כאן כיון שלט עליה רב נחמן.
אגב, קצת קשה למה אומר "הלכה" הראשון, שהיה לו רק לומר, “הלכה למעשה….”
** חיבת חופה -
אינו רק חיבה במה שהוא עומד לבעול, כמו שמבאר גמרא לקמן.
** שוברתה -
קשה למה לא חוששים שאשה תמחק אותו. אולי הכתובה הוא ברשות הבעל מונח בדרך כלל (ואין חוששים שימחק כל הכתובה כיון שהוא תנאי בית דין, ובהכרח ישלם[fn:2]).
** אביי -
זה מעניין, שכיון שמחלה, הממון יהיה שלו, כמו אילו פרע. אם כן, יש מון הנאבד כמו בכל ציור. אם כן, צריך ביאור למה נחלק.
* נו:
** מאי כתב -
ואם תאמר נאמר כן כאן גם כן. ויש לומר שעדיין קשה למה צריכה אשה לומר כלום; הרי לא צריכה לומר התקבלתי בברייתא אחרת של רבי יהודה.
** מילתא דלא שכיחא -
מכאן רואים שלא רק לא גזרו רבנן על מילתא דלא שכיחא, אלא שהרי גזרו לתת את זה, אלא אף לא החמירו כל כך. יש לציין לבכורות (ג.) כעין זה.
* נז:
** כתבועה -
קשה, שהיה לו לומר כאלמנה או כבתולה, שאי לאו הכי, מה אומר לנו; הרי אינו כתבועה, אלא היא תבועה, שבה מיירי. ויש לומר שר"ל שהיא כתבועה אחרת, ואין לה שיעור בפני עצמה.
** בוגרת וששהתה -
אם כן, לא הזכיר מה שבוגרת שאל שלשים יום, אף שצריך לזה.
** לקיט -
קשה ל"ל מהפך השאלה, שבעל הבית כהן לא יאכל בפני לקיטו, שהוא ספי ליה.
* נח.
** קנין כספו -
כיון שיכולה אשה לאכול כיון שהיא "קנין כסף" של כוהן, משמע שאדם קונה אשה בקנין כסף מן התורה. קצת קשה ל"ל הביא רש"י ראיה זה (בגיטין לג.). ויש לומר שקנין כספו קאי על עבד וכדומה, שקונה בכסף, ורק לומדים שקנינו אוכל. ותו"ת. ויש להעיר שאי אפשר שזה ראיה מוכרחת, שהרי לא לומדים מזה קנין כסף של קידושין. ותו"ת.
** שיכול לכופה -
אם עושה דבר לידים עצמה, אז יהיו הקדש מיד ולכל. וצריך לחשוב.
** אימת קודש -
אם הוא קודש לאחר מיתה, צריך ביאור למה הוא חלוק ממעשה ידים. ותו"ת.
* נט.
** לשעיבודיה -
לא הבנתי כל כך אז איך מתרץ גמרא, שאם הוא קדוש עכשיו, אז יהיה אסור, ואם לא קדוש עכשיו (מפני שעיבודו), אז קשה איך נעשה קדוש לאחר זמן. אולי אין צריך שיהיה קדוש עכשיו אלא שיהיה אותו יחס של בעלות שעושה שיכול לקדשו, אף שכאן יש מניעה. וצריך לחשוב על זה.
* ס.
** הלכה… בשלמא -
קשה, שאם לא חולקים, למה אומר הלכה. ותו"ת. אין לומר שכשאומר, “הלכה" חידושו הוא לומר שאין חולקים, שאף אילו היו חולקים, היה ההלכה כך, שהלכה כרבי יוחנן נגד רב. אולי גמרא אומר שקשה למה לא רואים מתי לא יונקים. הניחא רב ור"י, יש לומר שכיון שיש קטן כזה, ויש קטן כזה, אפשר לחלוק, שאחד אומר לשער בקטן כזה…. אבל, אין קטן כמו שאומר שמואל, ואז קשה להבינו. ותחשב.
** מהלכי שנים -
קשה למה נקרא אדם כאן מהלכי שנים, ולא אדם. אולי לא רצו שגויים ישמעו את זה ויאמרו שבני ישראל אוכלים דם אדם[fn:3], שהוא מאוס. ויש לדון.
** אפילו מצוות פרישה -
מניח גמרא שזה בחלב. עיין בכריתות שמניח שזה בדם. צריך לומר שפשוט לגמרא שקאי בשניהם. גם יש לומר שפשוט לגמרא שהדין באחד יהיה הדין בשני. יש לדון למה.
* ס:
** ועוד -
משמע שלא חולקים תנאים אם חלקו בית שמאי ובית הלל. אם כן, מוזר שתנא יאמר כבית שמאי. אולי "ועוד" ר"ל, ואף אם תאמר שאין הלכה כמי שאומר שלא חלקו בית שמאי ובית הלל בזה. ודחוק לומר כן על לשון "ועוד.”
** ההיא שוטה הוה -
לשון גמרא קצת משמע שגופא לומד שהיא שוטה ממה שעושה כן. זה אומר שיש לגמרא סברה שאשה לא עושה כן, ואומר שמעשה לא ידחה אותו סברה, מפני שיש דרך לדחות ולקיים הסברה, והוא שהיתה שוטה.[fn:4]
* סא:
** רומאה -
איני יודע אם היה גוי (רומי) או אם היה ישראל הדר ברום. גם איני יודע אם אותו אשה היתה בת ישראל, שאולי מזכיר מעשה שקרה עם שני גויים, כדי להודיע מה שאומר גמרא. ותו"ת.
** צרעת -
יש לדון כמה מזה היה נס. לכאורה, לא היה נס שהיה בו חלק מצורעת, שהרי ידע כן, שראה כן. אפשר שהיה נס לצורך מר זוטרא, שהיה צריך לאכול, ואז פסל ה’ אותו למלך. גם אפשר לומר שרק באר למה ידע לומר שהיה מצורעת, אבל לא למה נתן למ"ז, שרק נעשה מצורעת אחר כן, והיה נס. גם אפשר שהנס היה שהיה במקום שאמר להם לבדוק. ותו"ת. לא נראה כן, שגמרא לא רק אומר שהיה נס, אלא שסמך על נס, ואז צריך לומר שקאי על מה שעשה כן רב אשי, או על מה שאמר כן רב אשי. ותו"ת.
ואם תאמר אם קאי על מה שעשה כן, קשה איך ידע, אם היה הרוח על מר זוטרא. ויש לומר שמתוך שתאוו לו היה רוחו עליו[fn:5]. דע שלולי רש"י, היה אפשר לומר שאותו רוח היה על גב המאכל. ותו"ת.
** יולדת נקבה -
יש להעיר שיכול להיות ציור יותר ארוך מזה בזבה (תלוי במתי לא רואה).
** מידי דכשיח -
מעניין שאומר שמדיר את אשתו הוא מידי דשכיח.
* סב.
** וכי מאחר דהכי -
מעניין שהיו כל כך חזקים, מאחר שתורה מתשת כוח.
** מה אניח -
לכאורה, רואים מכאן שאמוראים חשבו שאקסירסיי"ז עושה שאדם יהיה יותר חלוש.
* סג:
** אינו דומה -
מעניין שנדה נחשבת פת בסלו. אולי הוא מפני שעומדת להיתקן.
* סה:
** קטן בן שש -
צריך ביאור מה שייך שניהם להדיי. היה אפשר לומר שהוא רק סימן, שרק אז הוא נגדל עד שיכול לחיות בפני עצמו קצת. עיין ברש"י שלא נראה כן כל כך. אולי הענין הוא שיודעים שאמו יתן לו, ואז הוא, בעיקר, נותן מזון לאשתו. אם כן, אם מגרש אותה, לא חייב עוד. ותחשב.
* סח.
** רמאים -
ק"ק, שאם לא נותנים מחמת רמאים, אילו לא היו רמאים, היו נותנים. אז, צריך לומר שאף בלי רמאים, לא היו נותנים. אם כן, קשה מה לנו שיש רמאים. נראה שאין הענין שעושים דבר רע, אלא שיש לו סיבה טובה לתלות בו, שאז נראה שצריך לתלות באותו סיבה. ויש לדון. אלא, נראה שהוא שהרע הוא מה שלא מקשיב לצער עני, אבל כאן, אינו עושה כן, שלא חושב שיש לו צער. ותו"ת.
** ומי אמר רבא -
קשה, שמגמרא לא משמע שרבא אמר כן, אלא ששאל לר"ח אם אמר כן, ואמר ר"ח שאכן, הוא (ר"ח) אמר כן. אולי צריך לומר שממה שידע, אז, רבא שר"ח אמר כן (ובצירוף, אולי, מה שלא הקשה), מניחים שרבא אמר כן גם כן.
** אחד משנים עשר -
היה אפשר לדחות שכך עלה מפני שאין עישור עישור ממש, כמו שיפרש גמרא. ואולי אין הכי נמי, אלא גמרא עדיין בהוה אמינא, ורק לקמן יבאר פרט זה בשיטת רבי.
* סט.
** שמיע -
משמע שאפשר להיות שיחלוק על רבי, אף שהיה רבי תנא ורבו של רבי יוחנן. ותו"ת.
** מהני ניכסי -
צריך ביאור מה לנו מאיזה נכסים בא. צריך ביאור, באמת, מהו כל סברה זה. לכאורה, הממון כבר משעובד לה מקודם לדבר, ואז תטול, אף שכבר רווחה. אולי ר"ל שאז לעולם בציור כזה תהיה כבר מרווחת (ר"ל, הציור ישתנה דינו רק על ידי קרק’ חשובים). ותחשב.
* סט:
** גברא דלא ידע -
ואם תאמר הרי אומר תוס’ שלא ידעו אמוראים קראי. ואולי אין הכי נמי, היה יכול להיות ת"ח, ולא לדעת קראי, אבל אי אפשר שיהיה ראוי לקרוא כן לרב הונא ושלא לדעת קראי. גם יש לומר שאז גילה שלא ידע אותו הלכה, שנלמד מאותו לשון של הקרא (עיין לקמן, שזה מחלקת). ותו"ת.
** מן הנשואים -
לא הבנתי כל סוגיה זה כל כך. לכאורה, הענין הוא שייתן לה רק אחר שתנשא. אם כן, כולי עלמא מודו שכיון שיכולה היא לקבל ואז ליתן לבעלה, יכול בעלה ליקח. רק חולקים אם יכול כן אף אם לא יכולה לתת לבעלה עכשיו, שלא נשואה לו, אלא יוכל לאחר זמן. ועדיין צריך ביאור. וצריך לחשוב.
** של מת -
משמע שבדווקא דברי מת צריך להישמע. צריך ביאור למה. אולי הוא מפני שאי לאו הכי, יש קצת לועג לרש במה שאינו יכול לשנות כדי שיהיה כדבריו. ותו"ת.
* ע:
** גלגל עמו -
לא הבנתי כל זה, שלמעשה, אם חייב, לא יכול לנדור, ואם לא, למה שולח. ותחשב.
** עביד שליח -
ק"ק ל"ל יעשה שליח אחר לשלשים ימים אחרים. אולי אף הוא לא יעשה שליחותו אחר חדש מהתחלת שליח ראשון. צריך ביאור למה. גם יש לומר שהוא טורח די ליקח שליח חדש כל חודש.
* עא.
** שלוחו -
צריך ביאור מהו הבעיה.
** נדרה היא -
מניח שהוא יותר מסתבר לשאול מלה, שהרי היא לא נפסדת כל כך, שנוטלת כתובה. אם כן, למי שלא מצריך כתובה, נאמר שהיא תשאל, ואולי ישאר נשואה לו, אלא שאולי לא מקפידים על זה אם בין כך ובין כך לא נפסד. ותו"ת.
* עא:
** רדופה -
ר"ל, הזכיר רגל, שאז לכולי עלמא הוא הדין, והזכיר שלש, שאז לכולי עלמא הוא הדין. רק רצה להזכיר דבר שהוא פסיקא ליה.
* עב.
** שלא תשאל -
לכאורה, ר"ל שלא תשאל או שלא תשאיל. ואפשר שהזכירם ביחד לומר שאף שהוה אמינא שאז לא יוציא שם רע, שהניחא אם היתה רק נוטלת, ולא נותנת, היו שונאים אותה, אבל עכשיו, מי יקפיד, אף על פי כן, יהיה שם רע די.
** שיקרא -
יש לדון אם צריך שאותו חכם יאמר לו, “אכן טמאתי,” או אף שאמר לה, “לא היו דברים מעולם,” שאז נניח שכיון ששקרה על סיבת טהרתה, שקרה על טהרתה.
* עב:
** הוה קפידיה -
זה מעניין, שלכאורה, יכול אדם להקפיד על כל מה שרוצה אם עושה תנאי. לכאורה, היה לו לומר שלא מניחים שהוא בכלל התנאי. אולי ר"ל שמניחים שכן ר"ל, אבל מילים שלו לא גילה כן כראוי (ק"ק, שכבר כתבתי שמניחים שכן אמר), ואז נחשב דברים שבלב, ואין אותו קפידה קפידה. דחוק.
** אסיפא -
נראה שהסיבה להניח שאינו מילתא באנפי נפשה הוא שסיפא בא אגב רישא (ורישא בא אגב סיפא). אז, רוצים לייחס אותם להדדי כפי האפשר. ותו"ת.
* עג.
** שאין אדם -
לכאורה, זה לא נוגע בציור של קטנה, שהיתירו רבנן קידושי קטנה. אז, פשוט שאינו אותו מחלקת. ותו"ת.
* עג:
** הכי נמי -
ואם תאמר ישנה אותו. ויש לומר שאין חי’. גם יש לומר שכבר משמע כן קצת. ויש לדון.
** אי הכי גט נמי -
ר"ל שאין לה כתובה כיון ש אין הבעל גורם לזה, אלא האשה. זה אומר שמה שבעל עושה במה שמקפיד ולא רוצה להיות נשושאה לה עוד הוא רגיל. כיון שאומרים כן, מקשה גמרא שלא יהיה הקידושין חל, שרגיל שלא לרצות בקידושין כזה.
* עד.
** רב אחא -
אם הוא בר אחתיה של רב אחא או של רב איקא, יש איסורי ערווה. ראיתי בסדר הדורות שהוא בר אחתיה של רב אחא בר יעקב.
** על תנאי -
יש לדון אם אומר שבזה לא חולקים, או שבזה חולקים, ופוסק כאחד מהם.
* עה.
** באשה חשובה -
יש לדון מה זה עושה, שגמרא רק מזכיר סיבה שלא רוצה לישה לה כלל, ולא רק לגרש אותה. אבל, צריך סברה למה חש לאשה נדרנית, כיון שהפירה. ותחשב.
** מיישא -
יש להעיר שלכאורה, שם זה בא מ"משה.” אם כן, משמע שאומרים חולם ל"אוי,” שרק על ידי זה נעשה "משה" ל"מיישא.”
* עה:
** חזקת הגוף -
לא הבנתי, שצריך ביאור איך יודעים שהיתה לעולם בלי מום. אולי אין דרך של מומים לבוא מזמן לידה. ויש לדון.
* עו.
** חדא במקום תרתי -
לכאורה, חסר חזקת “כאן נמצאו….”
** העמד ממון -
לא הבנתי, שזה יהני רק לממון שבו[fn:6], ולא לאם נישאת. אולי דין זה נגרר אחר זה. ותחשב. גם יש לומר שכל קידושין נחשב דבר שבממון.
* עח.
** יש לדון מה
היה תירוץ של רבן גמליאל:
1. אולי כוונתו לומר שהם קטיגוריים שונים, ואז אף שקבעו דין בזה, יכולים שלא לקבוע דין בזה. קצת צריך ביאור למה מתחילה יהיה הדין נקבע רק בזה ולא בזה. ותחשב.
2. אולי אומר שבזה יש יותר סיבה, ואם נאמר בזה, לא נאמר באחר. עיין בע"ב, שנראה שכן אומר שם, אבל רק לראשון. יש לדון, שאולי שם אף לא צריך מה שהוא דבר שאינו כל כך מובן בשאר מקומות, אבל כאן צריך אותו נקודה. גם אפשר שרק חולקים ומחלקים בלשון שאמר.
נעשית נשואה- כבר זכתה.
* עח:
** לא חל’ -
צריך ביאור מהיכי תיתי.
* עט.
** מצחק -
היה אפשר לומר שהוא כרבנן החולקים על רבי שמעון, ואז סוברים שאל יבריח ממון בזה, ואז מסתמא נתן, שאינו לנגד נפשו עוד. אולי עדיין מניחים שנותן חושב שמבריח. דחוק.
* עט:
** פירא דפירא -
צריך ביאור ל"ל אומרים שכיון שהפרי לבעל, הוולד שלו, והרי הוא, אז, זוכה בכפל. אולי יש לו קנין הגוף, ולא קנין פירות, על הפירות, ואז לא זוכה בכפל. ותחשב על זה.
* פ.
** אכלה שביעית -
לולי מש"א גמרא שהוא לשיטתו, היה אפשר לומר שמימרה שלו שם הוא שאף אם עבר בו, מחזק. מגמרא זה לא נראה כן, שאי לאו הכי, אין הוכחה שקאי על זמורות.
* פא:
** משום איבה -
קשה, שכשם שמגרש אותה בלי איבה, שאומר לה מה עושה, כך יעשה זה. לולי רש"י, היה נראה לומר שאף במגרש יש איבה, אלא שלא יכלו לאסור גירושין, שבכ"מ הוא רוצה לגרש. ותו"ת.
* פג.
** עודה ארוסה -
גמ’ מקשה למה אינו בכבר נשואה. היה אפשר לומר שהוא שם, וגמרא רק מחדש שהוא אף כאן, שלא זכה בו, ואז הוא כנותן מה שלא בא לידו. לא נראה, שלשון התירוץ לא נראה כן. ועוד, הוה אמינא זה סובר שבנשואים לא זכה בו, ולכן יכול לומר לשון זה, ואז יהיה אותו חידוש. יש לדון, שאולי יש לו קצת זכות בו- די לתת, אבל לא די שיצריך לשון יותר טוב.
* פג:
** לעולם אפירות קאי -
ק"ק, שאז הוא מיותר. אולי זה אינו כר"ע שדורש לשון מיותר.
** מכירה לא שכיחא -
זה מעניין, שהרי לא נהנית עכשיו, ואז אולי מסתבר לה למכור.
** פירות מהיכא -
לא הבנתי ק’ זה.
* פד.
** כושל -
לא הבנתי למה ילך למי שכושל בראיה. ותח’.
* פד:
** ר"י נפחא -
כיון שיודעים שהיה קרוב לר"ג, אולי מסתבר לומר שהיה אביו של ר"נ בר יצחק, שהיה לפי רש"י, חתן של ר"ג. אולי לכן נעשה חתן או לכן היה ר"י קרוב לר"ג. ותו"ת.
** עשית -
עיין ברש"י, שלא ר"ל כשל תורה, אלא כשל הלכה למשה מסיני. דחוק.
* פה:
** מחול -
עיין במה שבאר רש"י (שלאו בעל דברים…). ר"ל שזכות של הלוקח לא עושה שאין ההלוואה של מלוה יכול לחול, שהרי אין לו זכות בפני עצמו. וצריך לחשוב יותר.
* פז.
** אבא שאול -
צריך ביאור למה נקרא בשם אמו. אולי אביו היה גוי.
* צו.
** איבה -
קשה, שאף מעשי ידים הוא כדי שלא יהיה לבעל איבה מחמת מזונות. אולי אינו כן, אלא הוא כדי שיהיה פייר. ותחשב.
* צז.
** בעי לפרושי -
לא הבנתי, שמה לנו בפירושה, שיכולה לשקר בכתבה זה. ותחשב.
** לא שמיעא לי -
במק"א דיננו אם לא שמיעא לי אומר שלא סבר כן או שלא שמע כן (עיין רש"י בשבת). יש להעיר שאם לפעמים אומר זה ולפעמים אומר זה (תלוי במה שאומר עליו גמרא), יש לדון איך יידע גמרא. ויש לדון.
** לכאורה,
נמצא מגמרא זה שהדגרת מק"ט הוא שצריך להיות שכבר עומד מה שעושה שהוא טעות. ותו"ת.
* צז:
** נפיש חן -
היה נראה שהוא שלא איכפת לאשה כל כך, שברוב ציורים (אלא אם כן מת או מגרש מתוך אירוסין), לא יבוא לה רע זה. עיין ברש"י שדן בחובת ביאה; צריך ביאור מה מכוון לומר, שלכאורה, ענין חן הוא שאז ירצו ולא ימנעו מלישא. אז, צריך ביאור מה אם כבר נבעלה. ותחשב.
** וגרושה -
למד"א משום חן, נמצא שהוא ר"ש, ושוב רבנן, ושוב ר"ש. דחוק.
* צח:
** הכל לבעל -
ואם תאמר נאמר כן גם במוכרת מאתים למנה, שנעשה כאילו היא מוכרת, ושוב מקבלת מה שבאה להם בזה. וצריך לחשוב.
** הלכתא דבר -
לא מסתבר לגמרא שאומר שהלכה כרבי יוסי, שהרי נימוקו עמו, וכבר פשוט.
** בדאוזיל -
עיין במה שבאר רש"י. צריך ביאור למה זה חוזר, שאין אונאה לקרקע. אם תתרץ שכאן אינו אונאה, אלא מקח טעות, קשה למה אין כל אונאה שבקרקע מקח טעות. ותחשב. שוב הבנתי שלכאורה הוא כעין "לתקוני שדרתיך.” יש לדון, שכיון שמחזרת להם, לא חשים. ותו"ת.
* צט:
** בקטיני -
מעניין שמביא ראיה מזה. הניחא לעיל, דן אם חל חצי של חלות שלא יש יכולת לחול כולו. כאן, לכאורה, רק דן אם שולח מקפיד על עשיית חצי חלות. כאן, אולי לא צריך רצון היתום, שהרי חייבים לתת לה כתובתה, וכך היא נוטלת. ותחשב.
* ק.
** מעשה של רבי -
יש להעיר שהיה אפשר לומר שרבן שמעון בן גמליאל שאומר "אם כן מה כוח בית דין יפה" הוא לשיטתו, שאומר כן בגיטין (לג.). אי אפשר לומר כן עכשיו, שרואים שרבי מודה לזה, והרי שם רבי הוא החולק. ותו"ת.[fn:7] שוב ראיתי עוד בגמ’ שם. וע"ש, שמה שכתבנו כאן אינו נכון.
** לא איבעי לך למיטעי -
יש לדון מה זה אומר:
1. אולי זה סימן, והוא שממה שזה ממש טעות, ואין בני אדם עושים כן, רואים שהוא יותר רע.
2. אולי זה סיבה, והוא שבני אדם הם רוגזים יותר אם אבדו מחמת טעות, שאז יש מי שיסבול את הblame. ותו"ת.
** בן בנו של ר"פ -
יש לדון מי היה בן בנו.
* ק:
** ודאי טעו -
לכאורה, לא מתרץ לזה למסקנא, שעדיין הוא טעות. צריך לומר שקושיית גמרא אינו על לשון טעו, אלא מניח שטעו ר"ל דין של משנה שלנו, ואומר שוודאי הוא דין של משנה שלנו, ואז מתרץ שהוא רק כעין טעו, שאינו ממש ציור של משנה שלנו, ורק דומה לו.
** בשטרי פסיקתא -
ואם תאמר איך יכול להיות בהודאה; הרי אי אפשר להודות כיון שאי אפשר לחייב את עצמו. יש לומר שיכול לחייב את עצמו אם חברו מהנה אותו בגללו. ואם תאמר אם כן נאמר כן במשנה. יש לומר שלשון משנה לא משמע כן.
גם יש לומר שמחלקת ר"ל ור"י אינו אם נחשב הודאה או לא. הסיבה לומר שהדיון הוא אם נחשב הודאה הוא מה שדן בהודאה באמירת אתם עדי[fn:8]. אולי זה נשתנה למסקנת הגמרא. ותו"ת.
* קב:
** שעיבודא -
ק"ק ל"ל חילק להיפך ששם יש לומר שהיה מחנק אותו בשוק, מה שאין כן כאן. יש לדון, שאולי אף כאן, רצה ממון, ואז חנקו. ויש לדון, שכאן יודעים שהיה הלואה, ומסתבר שהיה דואג עליו עד שיחנק אדם. יש לדון בזה.
* קג.
** לעז -
יש לדון איך יודעים שאין שאר תלמידי חכמים באים. אולי מפני שאינו ידוע. יש לדון.
** דלא לימרו -
קשה, שמתו קודם לו, ואז אי אפשר לומר שזכותו היתה מחיה אותם. ויש לומר שכשקרוב למות, היה זכותו חלוש, שלא היה יכול להתפלל עליהם. גם יש לומר שמתו אחריו, ורק היו נקברים קודם לו, וזה אומר שמתו מיד אחריו.
* קג:
** תורה ומצות -
צריך ביאור מהו תירוץ זה. אולי אומר שאין הכי נמי, סימן רע הוא לבכות, אלא כאן היה צריך לבכות, ולא היה קל להעמיד את עצמו. גם יש לומר שבכיה כזה אינו רע, שהוא על תורה.
** דע שהיה
אפשר לומר שכיון שכבר יש לו סימן רע (שהיה חולי מעיים), לא היה צריך לאותו סימן. דחוק.
* קד.
** ק"ק ל"ל
לפי רבי מאיר, שלכאורה, כמו שממעטים לגמרי לאחר זמן, נמעט ונשלש. ותחשב.
* קד:
** מנה -
לכאורה, מדיון גמרא גבי מרתא בת בייתוס שאינו רק במנה ומאתים. באמת, קושיית גמרא ממרתא ק"ק על הצד שלא מניח כן, שאם לא כן, קשה למה מרתא מקבלת אחר כד’ שנה. אולי לא אומר שלפי גמלא שיכנא. ותחשב.
** הלכה כמי -
ק"ק למה אינו פשוט שהלכה כרבנן, ולא כרבי מאיר. ותו"ת.
* קה.
** שנים… שלש -
היה קל לתרץ שאין הכי נמי, הם מנין חלוק, ומה שעשה חלוק- מפני שהיו חלוקים! אולי היו שלש גוזרי גזילות, ושני גוזרי גזירות. ותו"ת.
* קה:
** אני שלא נטלתי -
יש לדון אם ר"ל אני שאל נטלתי לדון, ואז לא בא לי סמיות עין שאומר קרא, או אם ממש לא בא לו הממון, שלא קיבל אותו. ותו"ת.
** אם מרחם -
לכאורה, מה שר"ל הוא שאם יכולים להוכיח מזה שהם מרחמים, אוכיח כן על כולם, ואם…. גם יש לומר שאומר שאם אחד מרחם לי, מסתמא כולם מרחמים לי, ואין דיני סיבה שלא ירחמו לי, שזה רק לזמן, שחוזרים מיד אם אזכה אותם.
* קו.
** צריך ביאור
איך עושים שאין אלו הבנים נעשים טמאים, שלכאורה, אמם מגדל אותם, ואיך נדע שלא פירסה נדה אז. אולי אין הכי נמי, אם פירסה, היינו חוזרים ועושים כן לבן אחר. ותחשב.
* קז.
** רב פפא אמר -
אולי ר"פ לשיטתו, שגם לא אומר כצד שחוששים לצררי אתפסיה בסוף בבא בתרא.
* קז:
** כבר פירשה -
עיין בגמ’ חולין שמשמע שלא היה ר"י מכבד שמואל כל כך מתחילה. יש לדון אם מעשה זה לא היה די לעשות שיכבד אותו. גם אפשר שמעשה זה קרה אחר כן. צריך לומר ששמע ששמואל אמר כן לפני זמן, שממעשה זה יוצא שסבר ר"י שכבר מת שמואל.
** רב זביד בקוניא -
לכאורה, זה לא נוגע לכאן.
* קח.
** מציאה -
משמע שאין מעשה ידים משום איבה. היה אפשר לומר שמה שנותנים דבר בחילוף הוא מחמת איבה. מזה נראים נגד זה, אלא שנותנים לו דבר כיון שהוא פייר. עיין ברש"י בגיטין עז: שלא אומר כן.
* קח:
** כיסופא -
צריך ביאור ל"ל שייך זה לפי חנן. עיין ברש"י. אולי הוא מפני שלא פסק עמו שיהיה כן. ותחשב.
* קי.
** לא הוה מזבין -
צריך ביאור למה חושבים כן.
** חזרתי ולקחתי -
נמצא שאף שאין מגו למפרע, יש פה שאסר למפרע. זה מעניין.
** הכא דקלא -
צריך לחשב על זה.
* קי.
** לחמש -
צריך ביאור מה לנו בחמש ועשר למסקנת גמ’. אולי למס’ חוזר מזה.
** תפס -
עדיין יש נפק"מ.
* קיא.
** רב יהודה משבח
בבל, וגם סובר שאסור לצאת מחו"ל. יש לדון אם הם לשיטתו. הדרך לומר כן הוא לומר שלא היו בני ישראל נשבעים אלא אם כן בבל הוא גם כן טוב ומשובח לדור בו.
** עם הדומה - [fn:9]
לזמן רב, נסתפקתי אם הדרשה הוא "עַם הדומה לחמור,” או "עִם הדומה לחמור.” ממה שגמרא זה אומר שזה שייך ל"לעם עליה,” צריך לומר כראשון. ותו"ת.
מה שמניח לשון עם באותו דרשה הוא מוזר, שלכאורה, לא נצרך, שהיה אפשר לומר כצד שני, ואז יאמר עם כמו שאומר הקרא. וצריך ביאור.
* קיא:
** ממה שאר"נ שהוא רי"נ,
ולא אמר שהוא אביו, משמע שאין רי"נ אב של רנב"י. יש לדון, שאולי אמר אותו לשון, וגמרא פירש מי הוא אביו. ותו"ת.
* קיא:
** פשטיה -
נמצא פשטות שהוא כבר קצת דרוש.
** קלח של כרוב -
כל אלו מזכירים מעשה של יעקב ופוליו.[fn:10]
** עמי הארץ -
קצת צריך לפרש למה אין זה סותר מה שכל אחד מישראל יש להם חלק לעולם הבא. ותחשב. אולי אין צריך לקום להיות חלק בעולם הבא, אלא מקצת ממנו קם לאותו חלק. גם יש לומר שבא לו לפני קימה (במוות). ותחשב.
** עמי הארצות -
ק"ק לל"א "עמי הארץ.” יש לדון.
* Footnotes
[fn:1] יש להעיר שאם כן, יש לומר כן גם כן בצריך לשהות עד יום רביעי. ותחשב. (ויש לדון, שאולי גמרא שואל אף על זה. יש לדון למה לא ישאל עליו בפירשו (כיון שדן בו לעיל), ולמה יאמר ציור קמפליקייטי"ד כזה. ויל"ד.)
[fn:2] קשה, שאם כן נאמר שלכן אי אפשר לעשות כמו שאמר ר"י כאן, וצריך לכתוב שובר, שאף אם כתובה נאבד, גובים אותו. אלא צריך לומר שלא גובים כתובה אלא אם כן הנייר בעין. אם כן, קשה לומר שמניחים אותו גבו.
[fn:3] גם אולי חששו לליבולי"ם של דם. לא נראה כן, שהיו בזמן אחר מזמן של תנאים. ותו"ת.
[fn:4] כעין זה מצאנו בגמרא אחר (שכחתי איפה) שאומר, “ואף… ההוא עזות יתירה…" או כעין זה.
[fn:5] יש לדון אם היה מתאווה לאותו מאכל, או רק מתאווה למאכל.
[fn:6] לכאורה, אין ממון שבו ר"ל ממון של קידושין, שאז יתלה באם כבר נתן מעות קידושין לבעל, אלא ר"ל לדין ממונות של קידושין.
[fn:7] אפשר שהוא עדיין חד שיטה, אלא שזה הוא לאופן יותר גדול. ותו"ת.
[fn:8] כמובן, אם נאמר שכל הודאה ה"ה נתינה, קל לתרץ. עדיין יש לדון, שמה שעושה אינו הודאה, שפשוט שאינו נכון. כיון שכן, לא מחייב את עצמו. ויש לדון.
[fn:9] אפשר לדחות שרק דורש ממה שהם שווים באותיות. דחוק.
[fn:10] Jack and the Beanstalk
