** ב.
1. עיין במאירי שאומר:”ומשנתנו ראיה ברורה שכונס ברביעי ובועל בלילה [להוכיח שאינו צריך לשהות שבעה ימים אחר שנכנסה לחופה].” יש להקשות על ראייתו, שהרי שבעה ימים אחר יום רביעי יהיה אז ביום רביעי, ורוצים שיותר רק אז ביאה. נראה שלא סבר שצריך לשהות מעת לעת, אלא שבעת ימים. כן נראה, שהוא מחמת חשש נדה. אז, יוכל לבעלה ביום רביעי, והרי אין בית דין עד יום חמישי. היה צריך, אז, שיינשאו ביום חמישי.
2. עיין במאירי בביאור למה לא יהיה אונס בגט. כתב ראשון:”מה שכתבנו לענין מזונות הוא מצד אונס הבא מצד הארוס כגון חלה שהאשה נתקדשה לו על דעת שכשיגיע זמן תתרצה היא לינשא לו אם לא ישאנה יעלה לה מזונות והרי הוא כאלו קדשה על תנאי שיעלה לה מזונות בהגעת זמן שהרי תנאי ב"ד הוא וכשהגיע זמן ורצתה היא לינשא לו היה לנו לומר שיעלה לה מזונות ואונס שלו מועיל לו כאלו היה התנאי שלא לזון עד שיעבור האונס שאומדין את דעתו שאינו אלא כל זמן שיוכל לעשות כן ובגיטין אינו כן.” שמשמע שהענין הוא שאומדים דעתו שמתנה על גיטין. (אומרו שלא בדרך תנאי, אלא בדרך שיור, שהיה משנה את חלותו. ותחשב. לקמן, אומר, לבאר מה היה אם לא היה דין מחמת צנועות ופרוצות, “הא בכל מקום אונס רחמנא פטריה מולנערה לא תעשה דבר.” קשה, שאומרים כן אף במקום שפשוט שאין תנאי מועיל, כמו לפוטרו מחיוב מיתה. וצריך ביאור. גם יש לעיין במה שאומר לקמן גבי מכר (שרק טוענים טענת אונס כשהוא לטובת שניהם) שהענין הוא שאין רע נעשה לאדם מחמת אונס, שאי לאו הכי, לכאורה, יש אותו אומדנא. ותחשב. שוב ראיתי ששם גופא מבאר הוא שתלוי במחשבה, אלא שיש מחשבת שניהם. קשה, שיש רק מחשבת אחד, וצריך של שניהם. ואולי יכול להצטרף עם מחשבה קלה של מי שנאנס (שעושה, אולי, עדיין חלק מחלות).
3. עיין במה שאומר "ולדעתי יש לחלק בין תנאי שאעשה…” נראה שר"ל שכדי לקיים תנאי, צריך להיות משמע ממש כן, ואז צריך להיות שכן קרה, ושכן רצה. אז, בשני המקומות, לא חל. ויש לדון, שאם כן, עיקר קצת חסר מן הספר. ותחשב.
