* ב.
נתקררה- מעניין שצריך זה, שהיה יכול לומר שחוששים שמא היא אסורה, ואז, אם ישהו שני ימים, יבעל אותה שני פעמים, ועל הצד שהיא אסורה לו, יעבור על יותר איסורים. אולי לא מניחים שאדם יבעל מי שספק אסור לו (ומי שספק נבעלה לאחר וזנה עליו).
* ג.
שוויה- עיין בקושייתו על האומרים פשט שני. לכאורה, מניח שכל דיני אשת איש שאומרים גמרא הם על המתקדשת בכל אופן. לכאורה, סבר שכן משמע סתימות גמרא.
* ה:
הלכה- דכי אמר”י- עיין בלשונו, שמשמע שזה רק כשהוא דבר שאינו מתכוון. יש לדון אם מצרף היתירים, או אם הענין הוא שאם כוון לו, אז החשיבו, ולא נקרא מקלקל כל כך.
* ו:
שמשיר- עיין במה שמשמע שהוא ספק. קשה, אז, למה לא אומרים שספק דאורייתא לחומרא. אולי רצה לומר שאינו כל כך מצוי. ותחשב.
חייב- ויבן- עיין שם, שיש חולקים על זה לומר שלא רצה לומר שממש בנאה. ויל"ד. וע"ש.
* ח:
בצרדא- משמע שאומר שאף יכול ללבוש דבר רע כזה. לולי זה, היה אפשר לומר שאומר שיכול ללבוש דבר טוב כזה, כיון שאינו כל כך טוב, ואין לחוש שיהיו אחרים עושים.
* ט:
דכתיב- ישי- כוונתו לגמרא (יבמות פרק הערל) שאומר שהיה ישי בצבא של שאול.
יהודה- קשה, שביהודה יש אותו הוכחה שאינו משקר. וצריך ביאור.
* י.
חכמים- יש לדון מה לנו שהוא דרבנן; עדיין יתלה במה חושבים להיות נכון, וזה לא ישנה. נראה שר"ל שכיון שבין כך ובין כך, אין כל כך סיבה, שרק דרבנן הוא, אין להוציא מספק.
ודע שלולי רש"י, היה אפשר לומר שמחדש שאף שהוא דרבנן, ואולי הוה אמינא שצריך חיזוק, נאמן.
* י:
יפין- יש לדון אם רצה לומר שנעשה מעוברת יותר מרוצה או שהעיבור אינו כל כך ארוך.
בגדתאה- במק"א אומר גמרא שהיה בעל אגתדתא. מוזר שכאן, שהוא כמעט מקום היחידי בש"ס שנזכר באמירתת אגדתא, לא מזכיר את זה. ובאמת, מוזר הוא איך נאמר שהיה בעל אגדה, שלא אומר כל כך אגדתא. אפשר שאומר אבל לא הובא בש"ס. גם אפשר שאומר שהוא רב חנא סתם של אגדתא. יש לדון אם נמצא רב חנא באגדתא. ותחשב.
הכניסום- צריך לומר שחשב רבי שהיתה בתולה, שהרי התיר לו לבעול אותה. אם כן, לא היה צורך לגרום שתראה דם. ותו"ת.
מזיח- קשה, שאף למסקנת גמרא, צריך ביאור למה צריך שמזיח כיון שכבר מכפר, וממילא יזוחו. ואולי כל רצה לומר. ותחשב.
משלשלן- יש לציין למעשה של עולא בפסחים.
* טז.
אי אמרת- עיין איך מפרשו. לולי רש"י, היה אפשר לומר שר"ל שמסתבר שמיירי ביצור שחולקים (ולשון גמרא אומר שמסתבר שדנים בציור שיכול להודות לו), שהרי מודה כאן, וצריך לומר שלפני כן היו חולקים על דבר. אם כן, אומר מה שמשנה רק ר"י הוא מסתבר. ותחשב.
* טז:
וזה- לכאורה, קשה אז למה יש בעיה זה כשיש עדים, שאז מצא, ומה שלא מצא יותר הוא שאין צורך ליותר עדים. וצריך ביאור. ולולי רש"י, ואולי כן רצה לומר, הוה אמינא שקול הוא שמדברים עליו בני אדם. אם אין עדים שימצא, פשוט שאין קול ראוי. אף אם יש עדים, יכול להיות שאין קול. ודחוק.
* יז.
מכאן- לולי רשי, היה אפשר לומר שאומר שבית הלל אומרים שמדין זה של מקח אמרו כן, והוא סוף דבריהם. גם יש לומר שאומר כן גמרא, אבל מוכיחו מראית בית הלל, שממה שאומרים בעצמו אין ראיה, שאולי הוא כדי שלא יגרש אותה, ויקיים פרו ורבו. וילד בזה.
* יז:
ורב הונא- יש לדון אם אומר שהוא ידועה, ואז היה לו לדעת אותה ולהביאו, או שאומר שהיתה ידועה, ואין צרוך להביאה. נראה שתירוץ גמרא יכול להיות לשני הצדדים.
* כ.
** התלילות -
עיין במה שאומר. ודע שלולי רש"י, היה אפשר לומר שהיה תל כיון שקברו בו, והוא שלא היה כל כך קל לחפור, ואז הביאו כל עפר שיוכלו למצוא ועשו ממנו תל על המת. ותו"ת.
* כא:
** משחתמו -
צריך ביאור מה לי חתמו. ראשון, יש לדון מהו “חתמו.” אם חתמו אומר שכולם, ואף הפסול, חתמו, אז היה אפשר לומר שהוא מפני שהם חתומים עם מי שהוא פסול. רש”י לא אומר כן, אלא שהוא שישבו בדין עם מי שהוא פסול. עדיין אפשר לומר שיש בעיה רק אם חתמו, שאז יש ראיה לגנותם. ויש לדון, שיכולים לגנוז הכתב (שבין כך ובין כך הוא פסול). אם חתמו רצה לומר ששנים אלו חתמו, לא אפשר לומר כן. אז, צריך לומר שכיון שהם חתמו, הם יותר בדין (שגמרו אותו), ועשו חלק שלו עם הפסול, ואז יש גנאי. צריך ביאור.
* כב.
** בי דינא -
משמע שהיה רב נחמן בר יצחק בימי רב אשי. רש”י גם אומר שהיה רבו של רבא (שהיה רב נחמן סתם), ורבא מת ביום שנולד רב אשי. יש להעיר שרש”י סובר שרבא לא חי לזמן ארוך (עיין בראש השנה (כח) בענין בני עלי). ותו”ת.
** את בתי נתתי -
אלמא בדידיה- לשון זה מענין, שרש"י לא רק אומר שמזה רואים שהוא נאמן, אלא שהוא בעל של הנתינה, ולכן ממילא הוא נאמן. ויש להעיר שמן הקרא לא רואים כל כך, שמירי במוצא שם רע, ושם הבעל אומר שנשא את האשה. ויש לדון, שעדיין אפשר שהאשה מכחשת, ולא נמית אותה על דברי בעל. ותחשב על זה.
* כג:
** רבי יהודה -
אפילו ליכא גומלים- לכאורה, זה לא פשוט בגמרא, ותלוי בשני תירוצים שלו.
* כה.
** ומסקינן -
משמע שאילו לא היה תרומה מדאו’, לא היה אסור לזר לאכול תרומה דרבנן. זה מחודש, שאם כן, צריך לומר שאין סובר שאסור לזרים ושניהם דרבנן. בפשטות, היה נראה לומר שאסור מחמת תרומה דאורייתא. ותו"ת.
* כז.
** לבעול -
היה אפשר לומר שאין כל כך זמן בבעילה כמו בשתיית יין.
* כח:
** נאמן התינוק -
מעניין מה שרש"י מניח שנאמן רק כשנגדל. צריך ביאור למה. אולי לפני זה, אינו נאמן כיון שחושש שהוא משקר. ותחשב.
* ל:
** ושמתי -
עיין במה שפירש רש"י. לולי ז"ה היה אפשר לומר שאף שאינו אומר שום דמיון ביניהם, מה שהם ביחד בקרא זה הוא היקש ביניהם. אולי רש"י אומר שההיקש בא לא רק ממה שהם קרובים בקרא, אלא בא מיחסם באותו קרא, שהם נדמים.
** כרת -
עיין במה שמפרש להיות החילוק. נראה שמפרש זה, ולא גיל מיתה, מפני שזה לא היה באזהרת יעקב אל הבנים (שהוא הראיה לזה לאביי לעיל ל.). ותו"ת.
* לב.
** מפותה -
מעניין שאומרים שכיון שהכל לה, יכלה למחול, שלא חל חיוב קנס עד כאן, שחל רק כשבית דין מחייב אותו. אז, מעניין שיכולה למחול. ותו"ת.
* לד:
** היה פרה -
צריך ביאור ללנגרוס מש"א רש"י, שלכאורה, הפטור שווה, והוא שאין חיוב של קרן כבר. ותח’.
* לה:
** על כרחך -
כוונתו לבאר שיכול לומר כשיטה ראשונה בביאור המשנה, אלא שגמרא אומר שאף אם נכוון לשוות דעתו לר"ל, לא נשווה אותו יותר מר"י. ותו"ת.
* לז.
** דאיכא איבוד -
היה אפשר לומר שהוא שכיון שיש איסוד נשמה, אין העונש השני כל כך עונש עליו, שהוא כבר מת.
* לז:
** מיתה יפה -
מהר- גם יש לומר שהוא יפה כיון שהוא לא נראה מגונה אחר שמת. אולי לא חש לזה, שכבר מת. אולי בשעת מיתה נראה מגונה, ומקפיד בזה.
* נב.
** חביבי -
אחי אביו- ואמו. צריך ביאור למה רש"י רק מזכיר אביו.
* נד.
** כיון דאית -
אי נמי- לא הבנתי איך יכול לומר "אי נמי זה, שמשאלת גמרא, לא נראה שתקינו. אפשר שרש"י אומר בצד זה שדיון גמרא הוא אם רבנן תקינו. צריך ביאור ל"ל ידון בזה בעצמו.
* נו:
** והרי חמרים -
אפשר לומר שאין הכי נמי, כבר נאמן לומר שהוא ישן, אבל חברו מחזיק אותו. אולי אין מסתבר לו לעשות כן אם לא היה צריך. ותחשב.
* נז.
** הא קמ"ל -
זה אומר לנו מה הוא "אלו ואלו דברי.” נראה שני צדדים בכוונת רש"י:
1. שני הסברות נכונים.
2. לפעמים, זה נכון ולפעמים זה נכון.
3. שניהם; שני הסברות נכונים, ולפעמים זה ידחה זה…
ויש לדון למה זה סיבה להניח שכן הוא, שלמעשה, אחד מהם השמיט טעם, ואמר שאינו עיקר, ובזה טעה. ותו"ת.
* נח:
** בשאינה נזונת -
ק"ק לל"א שלא זונה. ואולי בית דין כופים אותו. גם יש לומר שטוב שלא לאוקמיה בציור שאדם עובר על איסור, ש"דאי לא אמרינן.”
* סא.
** אבל מוזגת -
עצה טובה- זה מעניין.
* סב.
** שאני התם -
מצווה דיליה- קשה, שיש לה שכר מלימודו, כמו שאומר גמרא בכ"מ. יש לומר שדן במה שחושבת.
* סג:
** כלתיה -
לכאורה, יכול להיות שמרדה בכל מין מרדה. אז, ק"ק מה כוונת רש"י. אולי סובר שגמ’ משמע שמביא את זה מפני השייכות עם מה שאמר לעיל. דחוק.
* סט:
** אילפא -
לא מר היה מלך- יש לדון למה, שהרי רק ר"י שמע שיהיה גברא רבא. ויש לומר שה’ רצה שיגדל, ואז החזירו. ותו"ת. גם יש לומר שבני אדם אלןו טעו.
** הא מני -
אינו אלא ירושתו כפי צוואו- זה מעניין.
* עב.
** אזהרה -
יש לדון איך רואים מזה אזהרה:
1. רואים שהוא דבר מגונה לבת ישראל, ואז מניחים שהוא אסור. דחוק.
2. אולי רואים שהיא נענשת על מה שעשתה כן לגלות ולנאוות את שערה לבועלה. אז, צריך לומר שהיה רע בגילוי כן לבועל. זה יותר נראה.
* עב:
** כה"ג -
סתמה- משמע שלא היה קושיה אילו לא סתמה. לכאורה, היה לו להקשות למה רבי שנה אותו שני פעמים.
* עד:
** לא יחזיר -
ילא אומר שהוא יותר פרוץ כיון שעושה לפני בני אדם, אלא כיון שהוא נדר יותר רע, שאי אפשר להפר. כן רואים ממה שמניח גמרא שזהו הדין לפי ר"י. ותו"ת.
* עה.
** וכולם -
עיין במש"כ. יש להעיר שמגמרא לעיל משמע שהוא מפני שאז נראית חשובה, ולא מפני שמזנות.
* עז.
** צואת כלבים -
עיין במה שפירש. היה אפשר לומר שלא היה לצורך גופו, אלא כדי שלא יהיה צואה בכל מקום. אולי מה שהוא של כלבים בדווקא משמע נגד זה. ותו"ת.
* עח.
** אימר -
זה מעניין, שנמצא שקנין של קידושין תלוי במה יעשה לאחר זמן, אם יעשה נשואין או לא. אם כן, לכאורה, נברר את הספק, ואז נדע הדין. אולי אין הכי נמי, ומיירי בדין קודם לכן. גם יש לומר שתלוי במה היה עומד לו באותו שעה, ולא יודעים אם מה שעשה הוא מה שהיה ראוי לו. ותו"ת.
* עט:
** והא עבדים -
לשם- גם היה אפשר לומר שחושבת שאולי יגרש אותה קודם שמכלה אותם, ורוצה שיהיו בעין כדי שתקח אותם. ותו"ת.
* פט:
** מר קשישא -
אין להביא ראיה מזה שיכולים לתת שם אחד לשני אחים, שאולי אחד מת קודם לידת שני.
* צז:
** מגו’ וא"מ -
מן האירוסין- קשה, שאז פשוט שאין לה מזונות, שכל ארוסה אין לה מזונות. אם לא גרסינן ליה (עיין במהרש"א), אז ק"ק ל"ל בא לה מזונות. וצריך לחשוב למה בא מזונות בכלל, שהרי ממון של בעל הוא. אולי כיון שהיא נשואה היא מוחזקת. אולי אין סברה זה באלמנה. ותחשב.
** למזונות -
עצה טובה- על"ע, שזה תלוי בבעיה שלא פשט גמרא. ותו"ת.
* צט.
** אמאי מעל -
לא הבנתי מה מתרץ רש"י כאן. נראה שהוא שבני אדם חושבים על זה להיות בתוך מה שאמר או שלא בתוך מה שאמר על פי אם בדרך כלל נחית לזה או לא. זה תלוי, אולי, באפושי שטרא. ותו"ת.
** דאמר ליה -
עיין במה שפירש רש"י. גם יש לומר שאולי רק מוזיל בבגד, ולא בטלית, ואז ממילא היה מקבל ההזלה אם קנה בכל ממונו בגד. ותו"ת. המשך גמרא נראה כרש"י, אבל ק"ק ל"ל יאמר כמש"כ. אולי לא מסתבר שיוזיל רק לדבר אחד.
* קג:
** ממלא מקום -
זה מעניין, שרש"י בשבת לא אומר כן, אלא אומר שהוא חשוב כאביו. נראה שר"ל שהיה ממלא את אביו יותר או שווה לשאר אביו, כיון שזה דבר שהיה צריך ללכת לבנים. ותו"ת. שם לא מיירי בדבר שצריך ללכת לבנים. ותחשב.
* קח:
** נכסים מועטים -
עיין שם, שמחלקת הוא (ושם נראה שלא מסיק כמה שאומר רש"י כאן).
* קי:
** במרום -
לולי זה, היה נראה לומר שהוא מפני שעפר נופל. כן משמע לשון גמרא.
* קיא.
** סוד -
ואם תאמר הרי זה כבר אסור, שאי אפשר ללמד תורה לגוי. יש לומר שכאן מוסיף עוד שבועה. דחוק. יותר נראה לומר שהוא סודות של תורה שבכתב, ואולי יש לו גם כן דין תורה שבכתב. דחוק.
