* לו:
** ויאמר יהודה והוציאוה -
ק"ק:
1. דלמא נשרפת מפני זיקתה.
2. אם כן, קשה, שתשטף ותשרף מפני ביאת ער ואונן. ואולי לא היו נחשבים בני ישראל. ויש לומר שאף היא היתה יהודית ולא הכירו בזה. ודחוק מאד, שידעו מי היתה.
* לט.
** דברי חברות לכתחלה -
נראה שהוא לשיטתו שמרבה מהו חבירות (עיין בדמאי).
* מ.
** ר' זירא -
צריך ביאור למה לא שמר אותו ה', שהרי "בהמותם של צדיקים...." אולי ה' עשה שלא בא שום טמא לפני ר"ז שנראה כטהור. יש לדון בזה, שעדיין עבר על איסרו במה שאכל אותו, ולא חש לספק. אולי אין הבטחה זו על מצוות אלא על סיבות רעות. גם אפשר שאינו עבירה כל כך גדולה, שהוא רק שלא חש לספק כשלא ידע את הדין. ותחשב.
* מ:
** במקומו של ר"מ -
לכאורה, אצ"ל מקומו דווקא, אלא חד מקום, אולי הניח שלא ידע כ"א אי הוה במקומו.
* מא.
** מפני שכיוצא בהם נעבד -
יש לדון אם רצה לומר שאכתי יש לחוש שעובדם או שאז השבירה ביטול חשוב (שלא משנהו כל כך).
** מצלה ליה -
יש לדון אי ר"י לא סבר שביטלוה או שסבר שצריך ביטול על ידי מעשה, ולא רק ביטול עם מעשה.
** ואין ספק מוציא מידי ודאי -
יש לדון אם הודאי הוא שעובדים אותו או שהוא אסור. ברש"י ד"ה אין םפק נ’ כשני.
* מג.
** בטיב עבודת כוכבים -
ק"ק מהיכי תיתי, שדילמא צריך דעת כדי לבטלו, ואין לקטן דעת.
** משכח לה -
מניח גמרא, לכאורה, שאי ע"ז עושה שא"א לה להיעבד, מוכרח שאינו ע"ש (כמו אם ישבר). (אגב, לכאורה, גם מניח כר"ל. ויש לדון, שאולי יש לחלק בין שבירה לעשייה שלא יעבד.) וק"ק, שאז כיון ששיש חד צד שיעבד (שגוי ימצאנו). יש לומר שסובר שעושה ע"ז שזה יקרה. וא"ת יבטלנו כיון שנמצא שיהודי מצאו. וזה א"א מגמרא שמוסיף הא דנכרי. וק’. ואולי נאסר לא כשגוי חושב עליו לה’ אלא לנעבד. וצריך ביאור למה. ואינו ק’ קשה לזה, שי"ל אז שאין סברה והוכחה שע"ז גורם שיעבד. ויש לדון, שמסתמא ענין העבודה הוא שע"ז רומה בו. ואז, יעשה שיעבוד. ויש לדון.
* מד.
** ק"ק למה
יעשו גויים עטרה הטוב רק לדוד.
** אם היה כבר
סימן זה, ק"ק למה צריך משיחה לסלק מחלקת (חולקים ראשונים אם לכן צריך משיחה אם יש מחלקת). ואולי אין הכל יודעים בסימן זה. גם יש לומר בדוחק שיחלקו בני אדם כיון שיש רעותא במה שלא נמשח. ודחו"מ, שאין צורך למשיחה. גם יש לומר שמה שלא הוה טוב על אדניה לא מהני שמי יימר שיהיה על שלמה. יש לדון למה לא היו בודקים את שלמה. ויש לדון, שאולי לא היה קנדידי"ט אחר. קשה גם כן למה לא בטל מחלקת אדניה. אז, צריך לומר כעין מש"כ לעיל. גם יש לומר שידעו בזה רק אחר שבדקו כמה מלכים. ויש להעיר על כל זה לשון גמרא של "עדות.”
* מה.
** הנכרים -
רצה לומר, ההרים הנעבדים.
* מח.
** הא מני -
לא הבנתי למה אי אפשר לת’ כמה שת’ גמרא לעיל (שמיירי בדלא השתחווה). שו"ר תוס’.
* מט.
** שאור של חולין -
כיון שהגענו לזה, יש לומר שרבנן דכאן הרי הוא ברייתא המתיר וברייתא האוסר כרבנן דמשנה.
* מט:
** ושפאה -
נראה שהחולק יסבור שמשנה דעלים (דר"י, שהובא לעיל להק’ ע"ז) חולק.
* נ.
** במה יאסרו -
משמע שדן כעין פנים ה"ה אף בדרכו בכך.
** לעצמה -
צירך לחשוב על זה.
* נב.
** דאמר ר"ל -
לכאורה, ר"ל לה"א ד"ר"א.”
* נב:
** אדעתא דנפשיה -
תחשב מה רצה לומר.
** שותפות -
משמע:
1. שיש קנין. קצ"ב, שלכאורה, אסור הוא בהנאה.
2. שקנין ישראל הוא העושה שנחשב שלו. יש לדחות שלעולם עבודתו הוא שעושה שלא יבטל, והו"א שקנין גוי יתן לו כוח. ואפשר שזה מכוח, “אין אדם אוסר דבר שאינו שלו.”
* נד:
** שלא תתעבר -
צריך לחשוב, שאלו הם רק תוצאות מעבירה, ולא יהא ביטולם [ענע?] עבירה. ודלמא בגזל יעשה כן, ויל"ד, שימכרנו).
* נז.
** מפיהם -
נוכל, לכאורה, להבין השיעור למאן דאמר ש"בכתה את אביה" קאי על זה, שאם כן הוא אותו שיעוט. ויש לדון, שיש חילוקים בין מה נעשה לשניהם.
* ס.
** לא הבנתי כל כך
מהו ענין הצדדת גוי, שמרש"י משמע שכוחו הוא. נ’ שהענין הוא- וכן נראה ממש"כ מריאיח שגורים שקילוח משכשך יותר. ק"ק למה ת’ זה, שבפנ"ע משכשך כ"מ שכבר הוה בתוכו. ותחשב. ואולי מה שהוא משונה עושהו כחו (כדין אם נותנו על גב קרקע) או שרק הילוך לא נחשב שחשוך (שצריך לשיי"ק). ותחשב.
* ס:
** בחמתו -
צריך ביאור מה לנו בחמתו; אף אי לא כוון, אסור, ואולי זה כוחו.
** מעשה לבינה -
לכאורה, אל שיחסו לו יותר קטן כיון שא"צ כל כך כמה קרק’ חשובים שלו לעשותו. ותחשב.
* סג.
** מעכשיו -
ק"ק מה חי’ יש בזה, שפשוט הוא, שבודאי יחול תנאי, ואולי הוא שאין זה בכלל "לכשתצטרך,” שמסתמא לא תרצה זונה כל כך בקרבן.
* סד.
** בטלה -
ק"ק, אז, למה צ’ מכירה. ואולי צריך מעשה ביטול.
** מעות טול -
ק"ק, שאכתי רוצה בקיומה, לנגר שאינו שם כלל, ואף אי זה א"א להיות.
* סח.
** מחלקת -
לכאורה, זה נגד ר"כ. ותו"ת.
* סח:
** בדמתא -
אכ"ק מהי"ת חידוש קרא.
* סט:
** סתמא -
משמע שסבר שהלכה כסתם משנה. ואולי רצה לומר שבאותו משנה הוא (כמו שמצינו בתוס’ ביבמות(פרק שנים עשר)). ויש לדון, שכאן חול’ כבר באותו מחלקת. ותו"ת.
** פשיטא -
ק"ק, דילמא משמיענו שסבר שהלכה כמותו כיון שנסתם.
** שייכא -
לא הבנתי למה אין אומ’ חשש זה במתניתין.
** דעבירה -
צ’ שהוא מפני שזה נקטל וזה רק נסמה. ויל"ד.
* ע.
** האמר -
לא הבנתי איזה איסור יש במה שישמור יינו. ותחשב.
* עא.
** פנאי -
משמע שיש יותר יצר הרע לבעול. כן נ’ מגמרא לעיל (ע.).
