* לז.
** אבל… בת תשעה -
מניח רש"י מנין זה; יכו"ל כל זמן שנעשית ערמה, ואולי בת שש או כדומה. ותו"ת גם מעניין שמניח רש"י שאינו חד שנה קודם לאיש כמו דעת.
* לח.
** קמ"ל -
דאין בישול- משמע שאם כוון לבשל, אפילו דבר אחר, אסור. ותחשב.
* מ.
** ביצת -
כוכורי"ל- לכאורה, רצה לומר קרוקודיי"ל. משמע שצפרדע הוא מין קרוקודיי"ל.
* מא:
** על בסיסן -
ודאי- משמע שצריך להיות ודאי.
* מב.
** כהן -
חכם- צריך ביאור למה צריך זה; יש לומר שרק שלחוהו לבדוק אי הוה זכר (וק"ק לרש"י איך לא ידע שיש איסור לו לטמא למת[fn:1]. ואולי סבר שיכול לסמוך על חולדות.) (ויש לדון- בהוה אמינא ובמסקנא- אי זה מותר לכתחלא. ואכתי ממעט הבעיה. וצריך לומר שאף שחשב שזה הדין הצריכו לשאל לחכמים.)
** אלא -
הפקר- ק"ק, שא"צ אף הגבהה לקנותה (ע’ ב"ק (ל?) ברש"י שם.
* מב:
** צורת חמה -
אפשר, אולי, לחלק בין צורה לצלם. ותחשב.
** אמר אביי -
אין לך המותר- משמע שבעצם יהיה אסור. קצ"ב מהיכי תיתי שצ’ זה.
* מג.
** מצא טבעת -
ולא הגביהה- גם יש לומר שכוון שלא לקנותו. ואגב, ק"ק איך יקנהו; הרי אסור הוא בהנאה. ויש לומר שא"ת אלא שיבא ברשותו. אולי לכן אין מחשבתו שלא לקנות מהני. ותחשב.
* מז:
** אף על פי -
תנא דידן- לכאורה, כל תנא סובר כן, אלא שחד סובר כן בישראל וחד בעכום. אם כן, כיון שמשנה לא פירש, יכול להיות לכולי עלמא. ועיין.
* מח:
** צל צלה -
לכאורה, זה גם כן ביאור דבבואה דבבואה (עיין רש"י בכריתות ו.).
** שחרית -
לכל דבר מאד- פשט זו נ’ מלשון "צל קומתה.” ותו"ת.
* סב:
** וכנגדו באתנן -
כמובן, צריך לחשוב על כל זה.
* סד.
** מרש"י
נ’ שאסור כלאים הוא רצון קיומו. ק’, שלכאורה, האיסור הוא הקיום. ותחשב.
* סד:
** אי נימא -
זה מחלקת לקמן.
* סו.
** שבתורה -
ק"ק למה צריך להיות במיני מתיקה.
* סז.
** שני ימים -
משמע שענין שיעור הזמן הוא לצרפו לחד אכילה.
* סט.
** ותיגוב -
דמינכרא- או שלא חששו שיעשה כן שירא מיהודי, או שכיון שלשא ניכר חור, מניחים שלא עשה חור. הנפק"מ הוא אי צריך לבדוק לחיור. ונ’ כראשון, שלשני ק’ לרבנן (עיין בגמרא) ל"ל נבדק ונדע.
* עב:
** ומשני -
דמיא- צריך לומר שיש צד שגרוע.
* Footnotes
[fn:1] שוב מצאתי שכן מקשה רש"י בנדה טו:.
