* ז.
** הילך מנה -
העיר א.ד.ר. שיקנה מדין ערב ועבד. ואולי צריך לכוון לאותם דינים, וכאן לא כוונה.
** ניחא לה -
יש לדון בזה, שהרי, למעשה, צירך ש"פ, ועל זה לא משנים דבר. וצריך לחשוב.
** ונפשטו -
יש לחלק שאין קדושין לחצי אשה (אבל רגל של בהמה יכול להיות אסור). ותחשב.
** והקדישה -
יש לדון למה צריך שיקדישה, ולמה לא יפשוט קדושה אחר כך מעצמה. ואולי מרבה אף ציור זה שחצי קדושה לא בא מקדושה ראשונה הדחוייה (ואולי יש אף צד שאותו קדושה שניה יפשוט וידחה קדושה ראשונה (כיון שהוא כשרה, ולא דחוייה), ואז יהיה הקרבן כשר. ותחשב.).
* ז:
** קרקעך -
נראה שהסיבה לחלק בין זה לפרה הוא שיכול לקנות קרקע בכסף, ויש יותר צד שנתן בו כסף. (גם, אולי, יש לומר שיותר מזור לאדם שלא ליתן מעות לקרקע, כיון שהוא חשוב. גם יש לומר שמוזר ליתן מעות פחותים בפרה (שלכאורה, הוא אונאה). אין בעיה זה בקרקע, שאין אונאה בקרקעות.)
* ח.
** וכיון -
לכל צד בר"י, היה אפשר לרבה לדחות שאומר כצד האחר. משמע שרבה בוודאי חולק על שניהם. ותחשב.
** מונה והולך -
לא מפני שמונה כמה מהם, שבראשון יהיה קדושין. אלא, הענין הוא שכשנתן אותו ראשון, אמר, “אחד,” ולא רק נתנו בשתיקה (או באמירת אחרת).
* ח:
** איבדקה -
עיין לקמן בגמרא שמשמע שזה אסור מחמת לפני עור (ואולי הוא רק שם שירתח לאביו).
* ט:
** רבי -
נראה שאין לו הוה אמינא של רבי יוחנן כיון שידחה שכיון שנלמד ג"ש לכסף, לא נניח שצריך דבר אחר לקנות. ויש לדון בזה.
* י.
** כל הבועל -
אם כן, כה"ג, שמותר לו רק בענין אחד, יכוון דלא כזה, לכאורה. ויש לדון. (ויש לדון אם רצה לומר שדעתו לקדש בסוף ביאה, או שאומר שחלק מן הביאה שמחשיב הוא סופו, וממילא, זה קונה. מש"כ לכאורה רק לראשון. ותחשב.)
* יא.
** פשטה ידה -
לא הבנתי, שאם דן בפשטה ידה, יהיה אפילו בפחות מדינר, ואם לא ראתה, נתת דבריך לשיעורים. ותחשב.
* יא:
** כי יתן -
צירך ביאור למה, לצד ראשון של רש"י, אומרים שהוא מעה שם, ולא דינר.
* יג.
** אין שקלי -
מביא לשון זה ממעשה דר"א (ב"ב).
* יג:
** לכו"ע נמי -
א"כ, קשה למה צירך לומר, “לא תהיה אשת המת החוצה.”
* טז:
** עמך -
יש לדון למה יובל יותר נחשב מעמך מגרעון (שלא רוצה אדון באותו שילוח).
** עמך -
משמע שמגרע בלי רצון אדון. עיין לקמן בגמרא שלא משמע כן.
* יז:
** גזירה -
יש לדון אם זה קאי על ירושה או על דין חילוק זה (ואומר שכיון שירושה שלו דרבנן, יש לומר שדין זה גזירה….).
** טול אתה -
צירך לחשוב על כל זה בדעת של מחלקת אם ירושה יש לו ברירה או לא. ותו"ת.
* יח.
** ולא עם יורשי -
אולי לא דורש כן (וחולק על הדין או יש לו דרשה אחרת), או שסובר שאינו מיותר (אומר אותו דרשה רק ממשמעות), או שרק אומר שמקורו יותר טוב כיון שהוא יותר מפורש. ותחשב.
** אם לא יעדה -
נראה שר"ל שעודפת שיש בכללה… וגם יש בכללה…, אף שהם ציורים חלוקים.
* יח:
** ר"א -
אפשר להיות שברייתא לפי ר"א (ואצ"ל ר"ש).
* יט:
** משל -
יש לדון איך ר"נ יבאר שיטה זה של ריב"י. ותו"ת.
* כ.
** ניתיב -
יש להעיר על זה:
1. מעניין שנקרא אז שלא יוצא כעבדים, שהרי רק ניתן לו ממון, אבל אין יציאתו חלוק. ותחשב.
2. יש אומרים שיוצא עבד חנם לתשלומי היזק. אם כן, קשה איך ישלם וישחררנו.
** מ"ט -
לכאורה, טעם זה יתקיים גם במוכר עצמו. ויש לדון, שאולי כיון שנכתב אחריו (ולא כבת, שלא כתוב שם כלל), יודעים שאינו כן. גם יש לומר שכיון שלא רוצה להיות עבד לא מוכר את עצמו.
** לידחי -
נראה שלשון זה בא ממה שסוקלים אחר שמפילים. אז, כמו בסקילה, נדחה אבן אחר מי שנפל.
** לעובד כוכבים -
לכאורה, הכל יילמד מזה (מגזירה שוה).
** א"ל -
נמצא ששאל לו אם נלמד בג"ש או לא ילמד, ואמר לו שלא ילמד מג"ש, אלא מלימוד אחר. אם כן, אינו משיב כאחד מן הצדדים.
* כג.
** זה פירש -
חושב אני שמביא לשון זה ממקום אחר (שאין לשון "פירש לחיים" כל כך שייך הכא). ואולי בא מלשון גבי עובר. ושוב לא מצאתי אלא ברש"י.
* כד.
** מבי נשא -
עיין רש"י בשבת שדן מהו בי נשא. נראה ששני היכולות אפשרות כאן, שיכול להיות אביה או כמיו. ותו"ת.
* כה.
** צריך ביאור
מה אמר תנא קודם ששמע בן עזאי, ואיך נדע דין רבי על לשון (שהניחא עכשיו, יש לדחוק לומר שאף על בן עזאי קאי “אף.”). ואולי אף זה לא ידע.
* כה:
** הדר -
יש לדון איך יודעים ממה הדר. ויש לומר שמסתבר שיאמר כסת"מ. גם יש לומר ששמע ממנו.
** מתקיף לה -
יש לדון אם מקשה על ר"ש או מכריח שלא אומר שהוא רק בהגבהה. יש לדון מה רוצה להוכיח מזה. אז, לכאורה, צ"ל כצד ראשון.
* כו:
** איכפל -
יש לדון מה רוצה שהתנא יאמר, שאטו יטרח לדעת מהו החפץ הכי קטן שירצה אדם לדעת בו דין זה.
** מחט -
לכאורה, לא נמצא כיון שיתן לו לשליח לקנות כיון שאינו שוה כל כך. גם יש לומר שיש טירחא בכל קנין אגב (שבדר"כ, נותן קרקע כדי ליתן מטלטלין), וכיון שאינו רוצה, לכאורה, כל כך בנתינת מחט, לא יטרח.
* כז.
** ור"ח -
צריך ביאור איך יודעים שלא חולקים (כיון שיש מה לחלוק עליו). ותחשב.
** כל הני -
יש לציין למש"א ראשונים גבי למה לא כופל משניות תנאים שלהם.
* כט:
** שבעה -
חושב אני ששמעתי (ואולי חדשתי) שהוא מפני שיש ז השתחוויות בשמ"ע (אם נרבה שלש של "עושה שלום").
* לא:
** כגון אבימי -
מעניין, שאבימי הוא מי שאמר מימרא על כיבוד אב (מיד לפני זה). ואולי לכן מביא גמרא אותו מעשה כאן בדוקא.
* לב.
** מניח אני -
ואם תאמר הרי הוא עב"מ. ויש לומר שאין לאב יכולת לחייבו לעשות דבר נגד מצוה. אז, יש סיבה רק למצוה אחת. גם יש לומר שמיירי בדלא התחיל מצוה אחת.
* לד:
** אי הכי
(שני כתובים הבאים כאחד)- ה"אי הכי" מעניין, שבין כך ובין כך היה קשה. ואולי רצה לומר שגלה גמרא שסבר כמאן דאמר שלא דורשים. ויש לדון, שמבאר לשני הצדדים. ואולי רצה לומר שגלה גמרא שחושש לאותו שיטה. ותחשב.
** אקיש -
קשה, שאף לתורה. ונראה שמניחים שיוקש לחומרה, ויחייבו. ותחשב.
* לה.
** איש -
מעניין שכיון שבדרך כלל לא יכולה לעשות, תורה לא יצווה אותה כלל.
** חס -
משמע שהוא חסד מה’ להיענש. יש להעיר שלולי לא היה קרא זה, לא רק לא היו בכלל עונשים, אלא ללא היו בכלל לאווים. אם כן, מחודש שנחשב חסד.
גם יש לציין לגמרא סנהדרין (נה:) שאומר, לכאורה, סברה הפוכה (ולא נראה לומר שזה רק לחיוב מיתה, שזה מרבה נשים אף לחיוב מיתה). ותחשב.
* לה:
** חס רחמנא -
לכאורה, הענין הוא שישמרו יותר משמירה כדי שלא יהרוג אותה. אם כן, לא רק חס עלה, אלא אף על זכרים, שגודל שמירתה יגרום מיתת זכרים עם נקבות (שקשה לומר ששומרו לנגד זכרים, אבל לא לנגד נקבות). ותחשב. גם ק"ק, שלכאורה, אין זה קנס, ולא חייב כדי שישמור בהמתו. ואולי זה חלק מן הסיבה. ותחשב על זה.
* לו:
** בן צאן -
הק’ א.ד.ר. למה לא רק אומר, אז, שדן בבן צאן. ונראה שלא מצאנו שנקרא זריקתו בשם הזרה. (ובאמת, צריך ביאור למה לא.) (ואין להקשות איך יש ללמוד ממנו להזאה, שעדיין הוא כנגד הזאה, כמו ששחיטה כנגד מליקה.)
* לז.
** על האדמה -
לכאורה, דורש שמשמע על כל האדמה. הק’ לי א.ד.ר. שגמרא דורש מכעין זה במגילה רק לארץ ישראל (גבי “למען ירבו ימיכם”). אין לומר שכאן דורש ריבוי אחר ריבוי, שאם כן לא היה חוזר לדרוש "בארץ.” ואולי עדיין מילת "בארץ" יכול לגלות על זה שכוונתו לומר בכל האדמה.
* לז:
** צריך ביאור איך יודעים
שאין מצות מלך בחו"ל (ואולי, באמת, יש מצווה), שאינו תלוי בארץ, ולכאורה, אין מה שהוא רק לאחר ירושה וישיבה מוכיח כלום, שאולי רק צריך דירה, ולא דירת ארץ ישראל. ותחשב.
* לח:
** לא נצרכה -
יש לדון מה היה קושיית גמרא:
1. מה היה ההוה אמינא שלא יתקיים בחוץ לארץ.
2. למה אומרים שלא היה מצווה עד ביאתם לארץ. כן אומר רש"י; אבל יש להעיר שאם כן לשון "לא נצרכה" בתירוץ גמרא מוזר.
** למעוטי זרעים -
נמצא שרבנן אוסרים דבר שהותר בפירוש בתורה. (ואולי יש לתרץ לצד שכלאי זרעים מותרים, ולומר שזה כלאי זרעים. לא נראה כן, שלא אומר רש"י כן, ועוד שאינו כל כך פשוט לגמרא להתיר אותו בחוץ לארץ.)
* מא.
** ושלח -
קשה למה לא יוצא מזה ארבע דרשות (“ושלח" שני פעמים, ו"ה" שלו שני פעמים). ונראה שאין לשון שילוח מיותר, אלא יש בו משמעות של שלחות. אם כן, כיון שדורשים שליחות ממנו, אין לדרוש עוד. ותו"ת.
* מא:
** דתנן -
יש להעיר על זה שני הערות:
1. לכאורה, יש משניות יותר פשוטים שמגלים מה שיש ענין של חבורה. יש לדון למה לא מביא אותם. אולי זה ראשון. ויש לדון.
2. לכאורה, אין ראיה מכאן לשליחות, שאולי כאן חלוק כיון שיש להם שותפות.
כמובן, יהיה דרך לתרץ שניהם אם נוכל להוכיח שאין כאן שותפות. ואולי לא יכול לקנות בשני שבא להם, וממנו מכוון גמרא להביא ראיה. לא נראה כן מקטע שמביא.
* מב.
** מהכא -
יש לדון מה מקשה גמרא:
1. היה לו ללמוד ממקור שהבאנו. יש לדון בזה, שהרי יש דרך שלא לסבור כמקור שלנו (אם סבר ששוחטים על יחיד).
2. היה לנו ללמוד ממקור שלו.
** מכרן בטל -
לשון מכר כאן מעניין, שלכאורה, רק שמים. ואולי מיירי בששם כדי למכור קרקע שלהם כדי לשלם חוב. ואם תאמר למה ישמו קרקע; יתן הקרקע לבעל חוב. ויש לומר שרק יש לו חוב כנגד חצי הקרקקע, אבל אולי אין מכירת חצי עולה לאותם דמים (שבקרקע נתגדל יותר מערכו, אולי, על פי גדלות השדה). אז, אם לא נמכר, היה מפסיד לווה. ותחשב.
* מב:
** כלקוחות -
משמע שאינם לקוחות ממש אלא שדינים כלקוחות. לאידך גיסא, עיין לקמן, שאומר ש"מכרן" בטל. ויש להעיר שאם הוא מכר, יהיה כעין מש"א שיטה אחת בגמרא שאחים שחלקו לקוחים, והוא שלכל אחד בא חלק מיוחד, ולא יודעים מהו, ומוכר זה חלקו לזה. אם כן, לא יודעים כמה מוכרים, שלא יודעים מה בא לו מחלקו הראשון. אם כן, לא יכולים לחשב כמה יהיה כדי אונאה. ותחשב.
** נפלוג -
לשון גמרא כאן קצת משמע שתלוי בדיבורו, והוא שבכל מצב, ישאלו לשום אדם לשום את הקרקע, ואם שאלו לבית דין, ולא קבעו שבאים לשאול בית דין, אין אומרים שכוח בית דין יפה. ותחשב.
* מג.
** אין אתה -
ואם תאמר, למה לא אומר שלא נענש עליו כיון דאין שליח לדבר עבירה. ויש לומר שעדיין יש לו עונש על זה (כמו שאומר גמרא לעיל).
ויש להעיר (על שמאי, בעיקר), שלכאורה, לא עשה דוד בני עמון (שהרגו לאוריה) שלוחים, שלא היו עושים מלחמתם לשמו. ויש לומר שהיה מעשה הריגה נתינתו במקום שמוכרח למות (כמו נתינת אדם לפני ים), וזה היה מעשה יואב ע ל פי ציווי דוד. ותחשב.
* מג:
** אין צריך -
ואם תאמר אם כן למה צריכים עדים כאן. ויש לומר שציירי בציור שיש לאחר הוכחה אחרת שלא שילם לו (למשל, יש לו עדים). ותחשב.
* מה.
** אחר אישות -
היה אפשר לומר שהוא כתנא שאומר שיכול למכור.
** איהי -
צריך ביאור, שלכאורה, אף זה לא מהני אלא מחמת שמניחים שרוצה בו. וצריך לומר שחושב גמרא שלא חל כיון שהוא עושה כן, וקבלתה היה לו, אלא שמוחל על זכותו, וממילא קבלתה מהני. ותחשב.
* מו.
** צריכה -
זה מעניין, שהרי אם צריכה דעת האב, נמצא שקידושין ראשונים לא הייה כלום, ויכולה למחול. משמע שיש דבר שכבר קנה ממנו באותו חלות ראשון, אלא שלא חל כל קידושין. ותחשב. ויש לדון מה יקרה אם לא יודה אב ותגדל. ותחשב.
* מו:
** וקסבר בעל הבית -
יש לדון למה היה גמרא סובר לגזור רק על כהן ולא על בעל הבית. ותחשב.
* מח.
** ורבנן מספקא -
צריך ביאור מהיכי תיתי שהם מסופקים,ולא שסוברים כרבי מאיר. ואולי הוא ממה שלא אומרים ש"אם לא, לא חל,” אלא משתקים. וצריך לומר, אז, ,שפשוט לגמרא כגירסא שאומר רש"י לפי התירוץ הזה, ולא שהיה לו שני הגירסות. ותו"ת.
* מח:
** איכא דניחא -
יש לחלק טובא, שחומץ ויין לא עושים דבר שווה, אלא שמה שעושה אחד הוא יותר חשוב ממה שעושה חברו. כסף וזהב עושים חד דבר (קונים דברים), ואז אפשר להיות שאחד יותר טוב מחברו. ותחשב.
* מט:
** אפילו הרהר -
משמע שעברה אחת עושה אדם רשע. ואולי רק עבדה זרה כן (ששקול ככל המצות).
** על מנת שאני רשע -
יש להעיר שלכאורה, מי שאומר כן אינו כל כך צדיק (שלמה לו לאדם לומר דבר כזה אלא אם כן מתפאר ברשעות. ותחשב.)
** שהטעתו -
לשון זה מבלבל, שאין הענין מה שהטעה זה את זה, אלא מה שלא נתקיים התנאי.
* נא.
** המרבה -
לכאורה, היה אפשר להקשות ממה שיכול אדם לתת (ובאמת, אף חייב לתת) יותר מחיטה אחת לתרומה. ותחשב.
* נב.
** גזל דידה -
יש לדון למה דידה, שהרי מקדש חמש נשים, ואז, לכאורה, של חמש נשים הוא. נמצא שמקדש אף בשל חברה. ואולי מקדש כל אחת בחלקם בו. ותחשב.
* נב:
** רבי יהודה אמר -
ואם תאמר כבר אמר שציור זה אי אפשר. ויש לומר שאמר אותו לנפק"מ אחרות, וגמרא אומר שיאמר דין כאן. גם יש לומר שאמר כן אחר שרבי יוסי באר לו איך יקרה. ותחשב.
* נג.
** גרגרים -
כיון שהיו חוטאים ונוטלים חלק אחר, היה אפשר לומר שהיו חולקים בחטא, אלא שאין צורך. גם, לכאורה, מוזר למה ינוחו לעבור על זה ולא על זה(ובאמת, חד דבר הוא, שחלוקה לא עושה כלום, ואז אין סיבה להם  לחלוק).
* נד.
** ת"ש -
היה אפשר להקים את זה במזיד.
** ת"ש -
לכאורה, זה מוכיח שיכול למעול בו. לכאורה, זה קשה לשני הצדדים ברבי מאיר. וצריך לומר שסובר גמרא שאפר שאכלו (או ביערו) כאן, ולכן חייב.
* נד:
** יש להעיר שלר"מ
, שאין מעילה אלא באכילה, לכאורה, אין למוד לשליחות בו (ויש לדון, שאולי נמצא אם נהנה, ושלח חברו לעשות מעשה שגורם אותו הנאה). אם כן, זה שייך לדרשת שני כתובים הבאים כאחד לעיל. ותחשב.
* נה.
** עולות -
לא רצה לומר שאומר שמסופקים בעולות, שמשמע שהוא עולה ודאי, ואז רצה לומר שחייב מה שיהיה עולה ודאי (שינדב מעות לעולה) אם פודה אותו. ותו"ת.
** קו"ח -
יש לדון, שאולי רק מה שהוא קדוש ביותר נתחלל ע”כ שקדושתו יוצא. ותו"ת.
* נה:
** כונסה -
נמצא שדין חמש חטאות הוא בכל שאינו ראוי, ולא רק חמש.
* נו.
** להוציא -
רצה לומר, לאכול באיסור. אם כן, כשאומר שמכוון להוציא מעות לחולין, או אומר שרק מכוון זה, אבל לא מכוון כלום על הבהמה, או רצה לומר שמוציא אותם (ותוצאתם) לחולין. ותחשב.
* נו:
** הא לא ברח -
היה אפשר להקשות על ברייתא ראשון שהביא, אבל דרך גמרא הוא שמדייק ממה שעליו קאי.
** מכרן -
מעניין שיכול למכור אותם, שלכאורה, צריכים להיות שלו, ואם אסורים בהנאה הוא, אולי אינם שלו. ותחשב. ואולי רק נותנים לו ממון ועושה להם עבודה- מוציאו מביתו להם. ותו"ת. (ויש לדון אם יתפוס דמיו, אז, אף אי היה לו דין תפיסת דמים).
** השתא דנפקא -
יש לדון מהיכי תיתי, שאולי רק אם שחטו אסור בהנאה. כנראה, גמרא מניח שאם אסור כיון ששחטו, ייאסר אם סקלו.
* נז.
** בני מעים -
ונקרא נמצא כיון שלא היה יכול להוודע קודם.
* נח.
** שחיטה שאינה ראוייה -
נראה שהענין הוא שעושה צעשה קדשים- אילו שחיטה זה היה בקדשים, היה כשרה. אז, כל פסול פוטרו חוץ מפסול של מה שאינו קודש. (ואם תאמר אם כן בעל מום יהיה בעיה. ויש לדון שעדיין שחיטה כשרה, ועושה כל מה שצריך לעשות, אלא יש בעיה בכפרה. ותו"ת.)
** הוא -
יש לדון למה צריך שני מיעוטים. גם צריך ביאור למה אין אומרים ששני המיעוטים מרבים (ש"אין ריבוי אחר ריבוי…").
* ס.
** מהו דתימא -
יש לדון אם הקמ"ל הוא שכל האומר לשון זה לדבר אחד מכוון או שאחד לא יאמר דבר זה וכיוון לשני דברים חלוקים.
* ס:
** עד כאן -
יש לדון מהיכי תיתי. ואולי אם חולקים בר"י ור"ה, היה להם לחלוק בציור אחר (שאין לטעות שחולקים בזה). ותחשב.
** זרוזיה -
ואם תאמר הרי זה דברים שבלב. ויש לומר שמפרשים שאמר, “על מנת שתתן לי. תן לי לאחר שלשים יום.” ויש לדון.
** בדיסקתורא -
אולי לכן נקט בקעה, שהוה אמינא שחלק בפירות שיש לו בכל הקרקע מצטרף. ותחשב.
* סא:
** היכא דניחא -
יש לדון למה לא אמר כל זה ב"הן.”
* סב:
** אם ילדה -
וא"ת הרי זה דומה לשדה שצריך מים כיון שצריכה לאכול. ויש לומר שזה עומד להיות, שכל אדם מאכיל את עצמו. ותחשב.
** לא תסגיר -
יש לדון אם בכל ציורים אלו הרי הוא כאילו כבר הוא שחת. ותחשב.
* סג.
** משום איבה -
יש לדון מה איבה מהני כשלא חל, שהרי כבר גלה דעת שלא רוצה לינשא לאשתו. ויש לומר שאז לא יעשו כן בני אדם.
** ש"מ -
לכאורה, לא לומדים זה מכאן, אלא לכן צריך לומר כן. ועיין בכעין זה בנדה ובכ"מ. ועיין בחרב אל הבדים- זמן קיץ.
** מלמדים האב -
מחודש שזה מהני, שלכאורה, יהיה תלוי במה רוצה, ולא במה שאומר.
** אחר -
יש להעיר שלכאורה, מוכרח שאחד משקר. אם כן, הוא חמישים- חמישים. אז, צריך לומר שבדרך כלל (אם אין אחר), הוא אף פחות מזה. גם צריך ביאור למה מתירים חמישים- חמישים. ואולי כיון שהאחר החליט לתת גט, מסתבר שהוא המשקר.
* סד:
** מוחלחת -
עיין ברש"י חולין איך מפרש את זה. ותחשב.
* סה.
** הא פסח -
כיון שהגענו לזה, אין צורך להחליף, ואז יש לדון אם נאמר כברייתא או כמשנה.
** עד אחד -
צריך ביאור למה דנים באחד, ולא במקדש בלי שום עד. ותחשב.
** הן הן -
לכאורה, היה אפשר לומר שאף אם לא נחשב עדים מחמת זה לקיום, אולי א"צ לקיום, אלא אומר שנחשב ראיה אז. ותחשב.
* סו.
** חולין בעזרה -
לכאורה, רצה לומר היה לו לחוש שיחייבו אותו, וזה יהיה רע כיון שאז מביא חולין לעזרה (אף שבי הוכחה זו, לא יהו, באמת, מחייבים אותו).
** מנא אמינא -
מצינו בכ"פ שיביא שני מקורות שאומר עליהם ,מנא אמינא…" לכאורה, אפשר שהיה לו שני מקורות, ואפשר שחשב על זה אחר שהיה מקורו הראשון נדחה.
* סז:
** לא תקדוש… לא כש"כ -
קשה, שאין מזהירים מן הדין.
* סט:
** אשר העלה ואשר הביא -
לכאורה, היה אפשר לדחות שממקומות עמוקים, כמו בבל, “העלה,” וממקומות גבוהים "הביא.” נראה שדורש ממה שמילת העלאה מיותרת. ותחשב.
** יונה -
ק"ק, שנמצא שכבר אמר אותם. ויש לומר שאמר שכמו שאמר על הני, אואמר על עוד.
* ע.
** נראה אולי
שמה שלא היה ר"נ מדבר כראוי הוא שאולי בא מא"י. נראה שאולי לכן נשא בת נשיא. זה מניח שהיתה בת נשיא, ולא ריש גלותא. עיין רש"י שלא אומר כן. גם יש להעיר שמגמרא לקמן משמע שהיה ר"נ מודה שטעה. ויש לומר שרק אמר שהיה לו ללמוד דיבור של בני בבל.
* עב.
** דבעו -
עיין בפירש שני של רש"י ובתמיהתו עליו. ונראה שר"ל שאז היה לאחר מעשה, ולא היה יכול לפסוק.
* עב:
** רבי מאיר -
היה אפשר לומר שבזה חולקים, שר"מ סובר שלא יבטלו לעתיד לבא, ואז מחמיר טפי. ותחשב.
* עג.
** אפסידו -
יש להקשות על זה:
1. הרי אמר רבא בעצמו שלא לומר כן לאנשי אותו עיר.
2. איך אמר רבא שלא לומר כן לבני אותו עיר, שהרי הוא טובה להם, שיש להם לישא כל מי שרוצה.
לראשון, יש לומר שקרה זה אחר זה. זה גם כן יבאר שני (שיש לומר שלא הכיר שהיו שונאים אותו על זה עד שאמרו. אחר כן, תמה על מי שלא הבין ממה שקרה לו.). גם יש לומר שסבר שכיון שהיו אוהבים אותו חלוק. גם יש לומר ששאני לו שהיה לו סיבה שנית (עיין לקמן).
לשני, יש לומר שלא היה לול לחשוב שיתנו לו פנאי לבאר, אלא אם כן כבר היו אהובים שלו. גם יש לומר ששקר. גם יש לומר שסברו שאם מותר לממזר, אסור לכהן. ותו"ת.
ויש להעיר שאולי מה שאומר, “כי האי,” ולא רק "זה" הוא שכוונתו היה לומר לא שלא היה לו לומר מילתא זה, אלא שלא היה לו לומר מילתא באופן כזה, אלא היה לו להקדים טובתם. ועיין לעיל. ותחשב.
** מעלה עשו -
לכאורה, הוא מעלה מחמת ממזר (שאם הוא מפני שמא ימצא אחותו, נגזר כן לכל אסופי לישא אשתו.). ותחשב.
** כיון דאיכא -
קצת משמע- ועיין ברש"י חולין גבי סוגיית איסור וסכנה שגם כן משמע קצת כן- שענין רב הוא שמונים מה יעשה זה ומה יעזה זה, אף אם זה יותר מסתבר.
* עג:
** אמר"י -
יש להעיר שהיה ר"י תלמידו של רב. מעניין שיאמר דבר בשם מי שאמר בשם… רב. ותו"ת.
* עה.
** אימא מודי -
ק"ק למה אין מתרצים את הסתירה, אז, על פי זה.
* עה:
** ס"ל -
לא הבנתי,שכל אחד יכול להיות גוי או ממזר, אבל בוודאי אינו ישראל כשר. אם כן, צריך ביאור למה אסור. ותחשב.
* עז.
** מקוה טהרה -
יש לדון:
1. מה מחלל בן חלל- חלל או עבירה ראשונה.
2. מה מכשיר בת ישראל- יחס לבת ישראל, או שזה משנה את החלל. לכאורה, יותר קל לומר כשני אם נאמר כצד ראשון שבדיון ראשון.
לשון "מקוה…" משמע שמשנות את החלל, כצד שני שבשני. ויש לדון, והדרך לדחות את זה הוא לומר שרק מבאר מה יוצא להיות הדין. ותו"ת.
* עז:
** חייב על כל אחת -
יש לחלק ששם שותה יין חלוק, אבל כאן בועל אותה אשה.
* פ.
** חזקות -
עיין בגמרא מכות שדן אם יכולים להמית כיון שחוששים שהנהרג טריפה. לכאורה, יהיה חזקה שאינו טריפה. ותחשב.
