* ה:
** אף -
בלי אירוסין- לשון זה מוזר, שלכאורה, רצה לומר שיהיה אירוסין.
* ו:
** ואסור -
יש להעיר שרש"י במק"א אומר שהבעיה הוא שהוא כאילו נותנו לו בתורת שכר, ונמצא שלא נתן תרומה. כאן, אינו כן, שאינו חייב לו שכר כי אם אם נניח שצריך ליתן לו. ותו"ת.
* ז.
** וכן -
היה אפשר לומר שקאי על דין רבא של אדם חשוב. ותחשב.
* ח:
** מנה -
שהרי משכון אינו מתנה- צריך ביאור מה אומר, שלכאורה, מקנה לה משכון, כמו בכל משכון, והענין הוא שרק לא מכוון לקנות אותה בו. ותחשב.
** במשכון -
חוב- צירך ביאור למה לא אומר שקדשה במשכון. ואולי כיון שחייבת להחזירה אם ניתן לו חוב, אינו ש"פ.
* יב:
** צער -
לכאורה, לא ילד יהודה וחזקיה בבת אחת(כן אומר גמרא נדה). אז, צריך לומר שאף על פי כן, מה שהיו תאומים גרם לה צער, או שקאי על אחותיהם.
* יג:
** מלוה הכתובה -
נמצא שהיזק (שגמרא בערכין אומר שהוא כתובה בתורה) הוא רק גזירת מלך.
** מלוה -
יש להעיר שגמרא בנדה מבאר למה חייב (שר"ש אומר שבשעה שכורעת לילד…). ואולי מה שאז חייבת הוא גזירת מלך. ותחשב.
* יד.
** ולא לה -
נראה שיש שני דרכים לקרוא רש"י זה:
1. … ששמותיהם שווים, ופסול כיון שאין שני נשים…. אם כן, קשה למה צריך להיות להם שם אחר, שאומר, “פלוני ופלוני נשיו.”
2. … ששמותיהם שווים, שאי היו חלוקים, פשוט שפטור…. ויש לדון מהו המקור לזה. ותחשב.
* יח:
** יש אם -
הי"מ לומר שעושים קצת כזה וקצת כזה, כמו שאומר גמרא בזבחים. ונראה שאף שעושה פשרה שם, לא מקיים שניהם. ותחשב.
* יט:
** מה למקדשה -
לכאורה, המקור הוא קו"ח, וזה אומר שממה שיוצאה יוצא מה שלא יחול. יש לדון,אז, למה לא לומד ממה שיותר קל להוציא מאמות ממקידושין. ותחשב.
* כא:
** הירך -
יש להעיר שלחד צד שם, ר"י לא פשיט כן. אם כן, מוזר מה שגמרא דורש כזה בכ"מ.
* כו:
** ולקח -
גם היה אפשר לומר שהוא הגודל שיכול ליקח לסלע אחד.
* כז.
** נתון -
צריך ביאור למה מביא כל מעשה זה מספרי אחר שאמר שהוא בגמרא ערכין.
** מיתה -
יש להעיר שבערכין מבואר שכיון שרק היה מסייע, אין חיוב מיתה, אלא שהוא גזירה.
* כח.
** שלא -
יש אומרים שמהני עד אחד (אלא שצריך שנים לקינוי).
** מנלן -
עיין בחלוקו. לכאורה, רצה לומר שיותר קל לגלגל כיון שהוא דומה. ותחשב.
** גופו -
יש לדון אם רצה לומר שהוא כע"כ שהוקש לקרקע או שהוא חלות ולא רק דין ממוני. לשון רש"י משמע כראשון. ויש לדון, שיש עדיין עוד חילוקים. צריך לומר שאין אלו שייכים לדיני קנין.
* לב.
** כך כתוב -
יש לדון מהו החילוק. אולי הוא שמראה לו כל הקרא, ולא אומר לו הדין. אולי כן משמע ממה שאומר רש"י שהבעיה הוא אם מודיע אותו פתאום.
* לב:
** אין זקן -
נוטריקון זה לא מפורש בגמרא כאן (ולהיפך גמרא אומר, “מי שקנה"). ואולי אם לא כן, אי אפשר ללמוד מאותו קרא, שרק אומר לשון "קן,” ולא לשון "זקן.” ותחשב. וצריך לומר שצריך קרא כיון ש"זקן" הוא רק נוטריקון של זה שקנה, ולא אומר חכמה בו.
* לה:
** פאת -
בנין אב- צריך ביאור איך לומדים בנין אב, שהחמיר התורה יותר בכוהנים. ותחשב.
* לז.
** חוץ -
סופרים- גם אומר בגמרא שהוא הלכתא (עיין לקמן בדף זה). לכאורה, חולקים; ויש לדון למה רש"י נקט זה יותר מזה. ויש לדון עמי סובר אותו גמרא בע"א, שלא מביא תנא. ואולי אומר לשון הלכתא על דין דרבנן. זה מחודש.
* לח.
** ויש היתר -
אם עומר- יש להעיר שבין כך ובין כך מותר, אלא שאולי הוא בזמן אחר.
גם יש לדון למה רש"י נקט שעומר מתיר, שחולקים בזה רב ושמואל עם רבי יוחנן וריש לקיש. וכמדומה, שיש כמה גמרות סתמות שמשמע כרב ושמואל. ותחשב. (ומוזר, שלכאורה, הלכה כרבי יוחנן נגד רב ושמואל. ואולי רב ושמואל ביחד דוחים דבריו.)
* מ.
** והאי מקיפים -
יש לדון, אז, למה אומר שלא מקיף; הרי אומר שמעיין. ולולי רש"י, הייתי אומר שהוא לשון של עשיית דבר דומה, וכן צריך לעשות כדי לעיין בביעי, שצריך לעשות אחרת דומה לו. ותחשב.
* מא.
** דו -
מעניין למה לא מתרץ שכיון שהיא שלחה שלוחה, מחלה. ואולי משמע שאין אדם יכול למחול על זה. ותחשב.
* מד:
** איכא -
לא שנא שידכו- צריך ביאור, שגמרא לעיל היה משמע שאי אפשר לסבול שאמר כן אף אם שידכו. אם כן, קשה למה גמרא כאן אומר כן.
* מח.
** במעמד -
אין טעם- לכאורה, יש עדיין שום טעם (כמו שמצינו במקומות אחרים שאומר כן, כמו מה שעשה אשתו אפיטרופוס. לכאורה, גמרא רק רצה לומר שנראה כהלכה שאין לו טעם, שנראה מחודש ומוזר. ותחשב. ולכאורה, פשוט שיש לו טעם, שאילולי הטעם, לא היו עושים כן. ותחשב. (ואולי עשו כן כדי לעשות דין דרבנן, כדי להראות שיש להם כוח, וזה לא נחשב טעם, שאינו טעם לדין בעצם. ותחשב מה זה אומר.)
* מט:
** תשעה -
ממזרים- מעניין, שערביא נטל זנות. לכאורה, צ"ל ששם רצה לומר זנות של פנוי ופנויה.
* נא.
** ליתנהו -
ממה שאומר שזבחה מקדש אותם, משמע שהענין הוא שבשעת זבחה, אינו אפשר לחשוב על יותר מאחד, וממילא אי אפשר לקדש זה אחר זה. מעניין, שהבעיה שאי אשפר לשנים בשעת שחיטה בזה אחר זה הוא בעיה צדדי (אין קדושת ראשון מעכב קדושת שני). גם ק"ק למד"א שישנה לשחיטה מתחילה ועד סוף.
ואולי צריך לומר שרש"י רק מזכיר דין זה אגב, אבל לעולם כוונתו לומר שאי אפשר לקדש זה אחר זה כיון שרק צריך ארבעים חלות. ותחשב.
** כי יקח -
קשה, מה לנו איזה סוג קידושין הוא. ויש לומר שמחדש שאינו קידושי ביאה (שאז אי אפשר לדעת בשעת קידושין איזה קונה,ועוד שנתון כבר לביאה זה).
* נא:
** דלא מחית -
מעניין שחוששים בני אדם לזה. ותח’.
* נג.
** יכול -
רש"י קורא אותו מכירת חלק. כמו כן נראה מגמרא שמדמה אותו לקידושין. ק"ק למה לא אומרים שיש לו זכות ליקח חלק, אבל לא בא לידו, ואז לא יכול לתת אותו, אבל כיון שבא לידו, יכול לתת אותו.
* נג:
** אונסא -
צריך ביאור למה אינו כמש"א גמרא לעיל גבי דבר שפחות משו"פ, שאם הוא שו"פ במק"א מקודשת. (ואולי שינוי בין ירושלים לשאר מקומות יותר גדול. ותחשב למה.)
* נז.
** לא מצינו -
עולם- שמצינו לר"ל משולחת קודם שילוח.
* נז:
** רבא -
אסמכתא- היה אפשר לומר שזה רק די לבאר איזה איזה, אבל עדיין צריכים קרא. ולא נראה, שכל מקורו הוא לימוד מן הנשחט; לא היה נלמד מפני פרכה זה. ותו"ת.
** ה"ג -
חיה- יש לדון מהיכי תיתי עופות, אז.
* נח.
** ישרפו -
העיר א.ד.ר. שהיה לו להקשות שכיון שאסור בהנאה, אפילו דרבנן, לא יחול קידושין, כמו שאומר גמרא פסחים גבי חמת לאחר ששי.
* נח:
** בשכר -
לימוד זה מעניין.
* סב:
** דילמא -
עיין במה שאומר. לולי רש"י, היה אפשר לומר שעושה שני החלותים יחד, ואז כיון שחל חד, חל השני. על מה שאמר רשי, יש להעיר שבבת אחת, אי אפשר לשני לחול.
* סד:
** רבי -
אין אדם- מעניין שצריך זה, שהיה אפשר לומר שאף שלא דוחה חזקה לגמרי, עדיין כיון שיש עליו מה לי לשקר, הוא יותר חזק ממנו. ותחשב.
** כולן -
שאלה לחכם- זה מעניין; לולי רש"י, היה נראה לומר שלא נוקט דבר שמביא לידי איסור מחמת אותו ספק. ותחשב. ויש לדון לר"י עדיין למה יותר מסתבר שאומר על גדול שבגדולים. ויש לומר שהיה לו לנקוט שם אחר, ויותר קשה למצוא שם אחר לגדולה שבגדולים. ודחוק. גם יש לומר שממה שעשה כן, צריך לומר שלא חשב שהוא ספק, שלא חשב שיש יותר מגדול אחד. צריך לומר שאותו גדול אחד שחשב שיש הוא הכי גדולה. ותחשב.
** בההיא -
שבח הוא לאדם- מעניין, שהוה אמינא שאינו שבח לאיש, אלא לבתה.
* סו.
** סמוך אהני -
היה אפשר לדחות כמה ש"לא נמצא" משמע שנמצא שלא היה בעיה כלל, ולא רק שהיה ספק, ונעשה כחזקה. ותחשב.
* סז:
** שבא -
יש לדון אם אומר קרא זה לראיה (והסיבה הוא או שהכנענים היו הכי חשובים או שהיו הנזכרים ראשון (וזה אולי מפני שהם הכי חשובים או שלא היה צורך להקדים אחר. ותו"ת.) או לסיבה (נקראו בלשון כנען כיון שארצם נקרא כן. אולי ארצם נקרא כן מפני שרובו כנענים.).
* סח.
** וכי יש -
עיין במה שמפרש. לולי רש"י, היה אפשר לומר שמפני זה יודע גמרא שלא רצה לומר אהובה לבעל, אלא אהובה לפני המקום, ואז מקשה שאין אהובה לפני המקום, ולא יתן ה’ שכר כזה. אז, מת’ שאהובה רצה לומר…. ותחשב.
* סט:
** עיסה -
עיין במה שפירש. עיין לקמן עא. (ויש לדון למה לא כ’ כן כאן). ודע שמעניין מה שאחד נדמה לקמח ואחד לעיסה (שהם דברים הדומים, ומסתמא המשלים שייכים זה לזה). ותחשב.
** אלא למ"ד -
צריך ביאור למה זה תלוי, שלכאורה, בין כך ובין כך הפרישם. ויש לומר שאם לא הופרשו לבא, מוכרח שבאו מאיליהם. אם כן, אולי באו לתוך מחניהם כשבאו. ותחשב.
* עב.
** כי קא ניחא -
מעניין שרבי ניבא.
* עב:
** היום -
אחרונים- מעניין שקורא לרנ"ב יצחק אחרון, שסובר שהוא ר"נ סתם שאומר מאמרות בשם שמואל. ותחשב על זה.
* עג.
** שמא ישא -
אבל אין באב בעיה זה כיון שהוא מותר לכל, ולא היה זנות אילו הוליד. ויש להעיר שנמצא גם כן שיהיה מותר אם היתה מגורשת באותו זמן. ואין זה קשה, שאין הכי נמיף אלא הזכיר הציור היותר מצוי.
* עג:
** משום אסופי -
אף שאפשר שלא הכיר הבעל, ולכן בעל אותה, אף שלא היה בנו, נראה שאז לא היה משליף אותו. וח’.
* עד.
** וניחזי -
אולי רצה לומר שכיון שזה עדיין בידו יזכור. ויש לדון, שאם שניהם נתנו ממון, עדיין הוא בידו. ותחשב.
* עו.
** לפי -
מן הבקיאים- אף אם אינו מן הבקיאים, אפשר שלא קרה פסול במשפחתו.
* עט.
** וכי תימא -
לא גריס- עיין בנדה, שאומר כן. ואולי אף שם רש"י לא גורם כן. וצל"ע.
* פא.
** בעלה -
להלקות- משמע שעדיין יש איסור.
* פא:
** בת תשע -
קשה, שאף למד"א שהוא סימן, שזה רק לאחר שנים. ולא משמע שצריך לשהות רק לראות אם ישרו הסימנים. ותחשב.
