בסיכום זה, ננסה לבאר שני דברים:
1. מתי מתחילים לשאול למטר, ולמה.
2. מהו היחס בין שיטת רבי יהודה (תענית- א- ב) ושיטת ת“ק ור“ג (תענית- א- ג).
גמרא (ד:) אומר בשם רבי יוחנן שהלכה כרבי יהודה. מקשה שרבי יוחנן אמר שהלכה כרבן גמליאל. מתרץ ארבע תירוצים:
1. חולקים שני האמוראים בשיטת רבי יוחןנ.
2. לכאו’, לזה מה שייצא הוא ששני המשניות הם בשאלה ובהזכרה בכל ציור (לקמן בע“ה נדון בזה), וחולקים שני המשניות. רבי יוחנן פסק כאחד מהם, וחלקו אמוראים כאיזה אחד מהם פסק.
3. משנה ראשונה הוא בהזכרה, ומשנה שניה הוא בשאלה. דוחה גמ’ שרבי יוחנן אמר שזמן שאלה שווה לזמן הזכרה.
4. משנה ראשונה הוא לבני א“י, ומשנה שניה הוא לבני בבל. דוחה גמ’ שכמו שיש צורך לבני בבל לאחר[fn:1], כך יש צרוך שלא יהיו לבני א“י מטר, מחמת עולי רגלים.
5. משנה ראשונה הוא בזמן שאין בית המקדש קיים, ומשנה שניה הוא בזמן שבית המקדש קיים, שאז צריכים לשהות כדי שיחזרו עולי רגל. (ועיין בבבא מציעא (כח.), שאפשר שמשנה הוא רק בבית ראשון, אבל בבית שני, שוהים זמן יותר ארוך, כיון שמחמת גנבים, לא היו יכולים ללכת בלילה.)
צריכים להעיר שאף שגמ’ יוצא עם שני מהלכים- ראשון ורביעי- לכאו’, צד שני עדיין אפשר למסקנא, שיכולים לתרץ שחולקים אמוראים אם אמר ר“י שזמן הזכרה שווה לזמן שאלה.[fn:2] אז, למעשה, הייתי אומר שיוצא חמש יכולות.
צריך לבאר קצת דיחוי לצד שלישי. לכאו’, זה יכריח לנו שאף לצד ראשון, ישאלו רק כשיכולים לחזור עולי רגלים לחזור לבתיהם. אז, צריך לומר אחד משני דברים: אפשר שמשנה ראשונה הוא רק בזמן שאין בית המקדש קיים (אם אין בית המקדש קיים, עדיין לא ידוע מתי מאחרים אותו); ואפשר לומר שסובר שאף בני בבל שואלים לאחר חג (ואז מימרת גמ’ (י:) שמאחרים הוא רק למשנה שניה, או אולי אינו לצד זה כלל, שמתרץ כצד שלישי), ואף שלא צריכים עד אחר כך, כיון שמטר טוב לסתם שדות באותו זמן. ותחשב.
כמו כן, צריך לדעת למה שמנה שניה חולק וסובר שמאחרים אותו. צריכים לדון אם חולקים אם מאחרים אותו אף בזמן שאין בית המקדש קיים או לא. גם יש לדון אם יאחר אותו יותר בזמן שבית המקדש קיים.
כמו כן, ייצא שזמן של משנה שניה הוא אולי רק אם יש עולי רגלים. לא יודעים מה יהיה הזמן בלי עולי רגלים, שיודעים שעולי רגלים הם סיבה לאחר זמן ההזכרה.
(לקמן, בע“ה, נבאר ענין זה.)
1. מתי מתחילים:
  1. בארץ ישראל:
    1. בזמן שבית המקדש אינו קיים:
      1. צד ראשון- אולי חולקים שני המשניות.
      2. צד שני- לא ידוע; אפשר שהוא קודם של זמן משנה אחרונה. אבל, אין משנה ראשונה מגיד כלום, שלא מבאר זמן שאלה.
      3. צד שלישי- זמן של משנה ראשונה.
    2. בזמן שבית המקדש קיים:
      1. צד ראשון- אולי חולקים שני המשניות.
      2. צד שני- זמן של משנה אחרונה.
      3. צד שלישי- זמן של משנה אחרונה.
  2. חו“ל:
    1. צד ראשון- אולי חולקים.[fn:3]
    2. צד שני- זמן שאומר גמ’ (מתחילים מיום ששים (כן אומר רב, וכן הלכה) או אחר ששים יום (כן אומר שמואל) אחר תקופה).
    3. צד שלישי- כצד שני.
עכשיו, יש עוד דבר שהוא קשה, והוא סיבה לדין משנה שניה. לצד שלישי שבארנו לעיל, יהיה מפני שצריכים זמן לעולי רגלים לחזור. כמו כן משמע מלשון של רבן גמליאל.
אבל, גמ’ (ו.) אומר שרביעה ראשונה (זמן בכירה של רביעה) נוגעת לענין שאלה. לא מסתבר שזמן רביעה תלוי בזמן של עולי רגל, ואז קשה למה מניח שרבי יוסי יחלוק על משנה שלנו (עיין שם), וגם מוזר שיהיו באותו יום. אז, משמע שטעם של משנה שלנו הוא מחמת שאז הוא זמן רביעה.
אפשר שגמ’ שאומר כן הוא לפי צד רשאון או לפי צד שני. אפשר שאז אין חילוק בין א"י בזמן שבית המקדש קיים לזמן שאין בית המקדש קיים, או שיש חילוק, אבל אין זה החילוק בין המשניות. יש לדון, אז, אם שני המשניות הם אם בית המקדש קיים או אם בית המקדש אינו קיים.
אפשר לומר שגמ’ לעיל (הסתירה) לא היה מפרש שיטת ת“ק, אלא ר“ג. (שם, בא לבאר רבי יוחנן שפסק כר“ג, אבל אנו מחדשים שאין דין של ת“ק ור“ג מיוסדים על סיבה שווה.) אז, יש לומר שזה בא לבאר שיטת ת“ק. עדיין קצת מוזר שזמן של רבי יהודה יקרה להיות אותו זמן של ר“ג.
אבל, רש"י מגיה לפסוק כרבי יהודה כדי שיהיה הלכה כרבן גמליאל. יש להעיר שגמ’ שתולה אותו במחלקת רביעה אי אפשר להסכים לרבנן גמליאל.
נמצא שסיבה של משנה שניה הוא קשה להבין, שנראה שיש שני גמ’, ואומרים סיבות חלוקות. ותחשב.
* Footnotes
[fn:1] לא מבאר גמרא מהו אותו צורך. יש לדון אם יש להם צורך שלא יהיה להם מטר או שאין להם צורך למטר.
[fn:2] יש לדון, שאותו מאמר נאמר בלי שם, אלא נאמר סתם שרבי יוחנן אמר כן. אז, אולי יותר קשה לומר שיש חולק עליו.
[fn:3] לעיל, חקרנו אם מחלק משנה ראשונה בין דין חו“ל לדין א“י. אף אם מחלק, אפשר שמה שאומר גמ’ מיוסד על מה שמניח שמנה שניה במחלקת שלהם. ותחשב.
