* ה:
** מאן חברך -
מעניין שקורא לו חברו, שהיה רבו. אפשר שאין זה לשון כבוד לומר לרבו, ואז לא רצו תלמידי רבי אליעזר לומר כן לו. גם אפשר שר"ל בית דינו של רבי יוחנן, ובו היו תלמידי ר"י, ובכללם היו חברי ר"א. אם כן, קצת מוזר שלא היה ר"א על אותו ב"ד.
* ו:
** מוכן לאדם -
לא הבנתי ל"ל נאמר שחולקים שני התנאים במוכן לאדם הוי מוכן לכלבים (וכולי עלמא כרבי יהודה, ולא כרבי שמעון במוקצה).
* ז:
** רבי זריקא -
אם כן, אין להקשות מזה כמש"א גמרא לעיל.
* ח:
** ואין דעתו לספק -
זה מעניין. היה נראה לומר שאין דעתו לספק כיון שאולי לא יקרה, ואז לא ישתמש בו. אם כן, קשה, שהרי כאן אין הספק אם ישחט או לא, שבוודאי ישחט, ואז בוודאי ישתמש בעפר. הספק הוא רק אם צריך עפר. כיון שצריך מחמת הספק, ובודאי ישתמש עמו, צריך ביאור ל"ל יהיה נחשב הוקצה. ותחשב.
** דבהדי -
ר"ל, לא חוששים שיעקר, שמסתמא אם יעקור, יעשה אותו כך.
* י:
** בדף -
מעניין, שלא יודעים שהיה בדף שום אחד. צריך לומר שמוחזק שיש אחד שם, ומעלה של קרוב במה שהוא וודאי לא די לדחות.
* יב:
** מעניין שאין
תיקון בבשר. לכאורה, מרש"י משמע שהוא מפני שאין הבשר טבל. אף על פי כן, הבשר אסור. יש לדון, שאין הבשר אסור, אלא שאסור לאכלו כיון שיש חיוב מוטל עליו. צריך ביאור מה זה אומר, אבל נראה שהם המילים לתרץ. ותחשב.
** לא הוה בידיה -
קצת פו"ן, כיון שדן במלילה בידו.
* יד:
** נימא -
לא הבנתי הציור כל כך, שלכאורה, קשה להיות נימא שהוא בפני עצמו כלאים. אולי ר"ל חתיכה קטנה. ותחשב על זה.
* טז.
** בניו -
חושב אני שאין זה כל כך ידוע.
** דלא מלפתא -
מעניין שמניחים שאין הולכים בתר בבליים.
* יט:
** בחג… היינו -
קשה, שאולי החילוק הוא אם חג אחרון או גורם.
* כא:
** לכם ולא -
אם כן, קשה, שאין מי שאוסר לגויים ולבהמה. אם כן, בוודאי מותר. צריך לומר שאחד מן התנאים סובר כאידך, ורק מוסיף עליו. כמובן, אי אפשר שר"ע מוסיף על ריה"ג. ותו"ת.
** ראויה -
מעניין שזה מהני, ולא צריך שממש רוצה לשתות אותו. עיין בתוס’ לעיל שכ’ שאולי משמע שצ"ל ראוי לצורך באותו חפץ עצמו. אם כן, צריך ביאור במחלקת ב"ה וב"ש.
* כד.
** מזונתן -
צריך ביאור מה לנו בזה. לכאורה, הוא סיבה להניח שקל לצוד אותם (הוא סיבה או סימן לעשות שיותר קל לצד אותם).
* כד:
** רשב"א -
יש להעיר שלא יודעים אם אסר לקבל או לאכול (עיין לקמן).
* כו.
** איצטריכא -
לכאורה, ר"ל שכולי עלמא מודו שאסור להגביה אותו, ואז מראה חידוש זה לכולי עלמא, ומוסיף עליו מחלקת זה.
** לשחיטה הא תם -
היה אפשר להקשות כן אף בלי פירוש שאמר בביאור המשנה לעיל.
* כו:
** אין זה מן המוכן -
צריך ביאור מהו הסיבה לחלק (לשיטה שמחלק) בין אם בא קודם יו"ט או לא. נראה שהוא נחשב יותר היתר בראיה אם בא מום ביו"ט, שלא היה כבר עומד להיתר. ואם תאמר בשניהם היה מום קודם ראיה. ויש לומר שבאחד היה המום מחול עומד להיות נראה, שאז מותר לגמרי להראות אותו. ותחשב.
* לד.
** אחרון חייב -
יש להעיר שהיה אפשר לו לומר שהמדליק חייב, שמיירי, כמו שיאמר גמרא, כשהאחרון הוא המביא את האש. אז, לעולם הוא אותו אחד שחייב. ויש לדון, שאולי בא לומר שאחרון לעולם חייב, בין אם הוא מביא אש, בין אם הוא אחר, שאם הוא אחרון, חייב בהכרח. ותו"ת.
* לו.
** דקיל -
יש הוה אמינות שיכולות להיאמר בכמה מן השאלות שלא נאמרו אלא בשאלה אחת, וקצת צריך ביאור למה.
** בטיבלא -
מניח שהוא מוקצה, אף שיכול להרימו מדאו’ בשבת. עיין גמ’ לעיל שהניח נג"ז.
** ה"נ מסתברא -
קשה, שכל דיוקו ידע נקודה זה, וגופא דייק שממה שבא לייתר, ולא אמר חידוש, מוכיח שאין אותו חידוש נכון. ויש לדון, שאולי לא חשב כן הו"א. יש לדון מהי"ת לא, ולמה לא יהיה נכון. קצת משמע כן (כמו שכתבנו) מרש"י לעיל. וצ"ב.
* לז:
** דקא ינקי -
קצת צריך ביאור מה זה אומר. אם אומר שלא יודעים מה של זה, שזה ינק משל זה בשבת, שהרי יש ברירה. ותו"ת. אפשר שיחס זה של יניקה עושה שצריך לנהוג כתחומים של שאר. ותחשב.
* לט.
** בדלית ליה שיעורא -
יש לדון ל"ל אומרים שבטל לשלהבת, שהוא רק לנשוא אותו. ותחשב.
