* ב.
** קא סלקא דעתין -
לא מקצי- משמע שהמחלקת הוא, על כל פנים בהוה אמינא זה, אם אדם מקצה או לא, ולא אם מה שמקצה עושה נפק"מ בדין. ותחשב.
* ב:
** סתמיה -
ואם תאמר אם כן, למה כוחו מרובה מכוח הסתם. מבואר שכוחו מרובה מכוח הסתם ממה שתוס’ כ’ שסתם ואחר כך מחלקת הוא כרבים. עדיין אומר גמרא שאינו כסתם משנה. יש לדחות שרש"י לא סובר כתוס’. עדיין יש ראיה ממה שמקשה גמרא בכל זמן שמצאנו שרבי יוחנן פוסק נגד סתם משנה. לא בכל זמן פוסקים כרבים.
נראה שהחילוק הוא שכאן לא רק יש רבים, אלא רבי גם הוכיח לפסוק כאותו רבים, שאי לאו הכי, לא היה לו לעשות אותו לרבים. אז, צריך לומר שהלכה כמותו, אלא לא היה רבי יכול לעשות שבוודאי יהיה הלכה כמותו, ולכן סתמו לעשות שנראה כסתם.
* ג.
** ומשני -
ואי אפשר לשנות להיפך, שהרי שני השיטות שם בעירובין סוברים שאסור, ורק חולקים אם יש איסור ביום שני.
* ה.
** הא לן והא להו -
לא הבנתי כל כך מה אומר, שלכאורה, לא יהיה ראש השנה עכשיו חלקו משאר ימים טובים.
* ז.
** אפושי -
עיין בקושיית רש"י. ודע שהיה אפשר לומר שגמרא רק מצדד שרבי יעקב יחלוק שם גם כן. ויש לדון, שאולי לא מסתבר שחולק בכל כך כמה מקומות ולא מודיע לנו. (ועוד שלמה נניח מחלקת.)
* ט.
** והאמר -
מקשה מרב- זה מעניין. עיין במקום אחר (בבא מציעא?) שאומר כן רש"י על כל אדם שהיה ח
** והאמר -
שמואל- יש לציין לגמרא בב"ק (פ.) שמבואר שהיה שמואל קטן אף מתלמידי רב.
* י:
** לימא מתניתין -
זה מעניין, שמצאנו הרבה סתמים שהם כיחידים. אפשר שלא רוצה כן גמרא, אלא שלמעשה נעשים, וקשים הם קצת. דחוק. גם ק"ק שאין הל’ כסתם יחידאה.
ויש לציין לרש"י בפרק החובל שאומר שגמרא רוצה להוקים משנה כרבי. נראה שזה רק מפני ששם לא חולק על רבים. ק"ק ל"ל אומר ששם הלכה כרבי מחברו, ולכן רוצה להוקים משנה כמותו. וצריך ביאור.
* יא:
** רחבה -
רבו מובהק- זה מעניין. לא הבנתי למה מה שהוא רבו מובהק עושה שיותר היה רוצה שלא יחשבו שהוא רב יהודה אחר; להיפך, יהיה פשוט, שלעולם מביא רבו. ותחשב.
לולי רש"י, היה אפשר לומר שכיון שהיה רבו, היה מכבדו בזה.
* יב.
** ליפלגו -
עיין במה שבאר. לכאו’, אם אינו מותר לטלטל דבר, זה יעשה שלא יעשה אף שאר מלאכות, אבל לא מפני אלו נתקנו, אלא מחמת הוצאה. ותחשב. רש"י לא מוכיח שהוא מחמת הוצאה, אלא שמהני להוצאה.
* יב:
** הכא -
עיין בתוס’. קשה, אז, למה חייב לפי בית שאמי. צריך לומר שכיון שאסור לאכלו, לא נחשב צורך די. ותחשב.
באמת, לא הבנתי מה אומר, שלא צריך צורך, שרש"י אומר שבלי צורך, הוא אסור מדרבנן. אפשר שסובר שכיון שבדבר זה, אין שום צורך, לא נאמר מגו דהותר…. אם כן, מה שכתבנו לעיל אינו נכון, שמיירי כאן במבשל שלא לצורך. גי"ל שחולק על רש"י.
* טו:
** מ"ט -
אסמכתא- מה שאומר שאין עירוב משתמע מיניה ורק אסמכתא משמע כפירוש רמב"ם ולא ריטב"א באסמכתא.
** רב אשי -
לכבוד יום טוב- זה מעניין.
* יז.
** אטו שבת -
משמע שבלי ישראל, לא היה קדוש, אף שלכאורה, רק היה הכל מעובר. חושב אני שיש דיון בזה.
* כב:
** בזריזין -
בית גרמו- מעניין שגמרא רק אומר שהיו האומנים שבו, אבל לא בדווקא היו האופים. וע"ש.
* כד:
** ולערב -
עיין במש"כ. יש להעיר שאם מה שצריך לשהות כדי שיעשה הוא כדי שלא ירוויח, שאז יחטא, אז לא נראה לומר כרש"י, שעדיין מרוויח. ותחשב.
* כו.
** אם יש בו מום -
אם רואים מכאן שלר"י יש מוקצה, נוגע למה שדן גמ’ בשיטת רבי בכ"מ מה סובר במוקצה.
* כז:
** עיין בצורה
שכ’ רש"י. צריך ביאור ל"ל עשו רק טרייאנגיל, ולמה חקקו באמצע. ותו"ת.
* ל:
** הכא אדם -
וכי נביא- עיין לשון כעין זה בפסחים (ט:) גבי חולדה.
* לב:
** ארקתא דפרת -
עיין במה שפרש. עדיין איני יודע אם ר"ל שבא משם, ולא גבלו, או שגבלו, אבל סובר שאינו שינוי חשוב, שהיה יכול לקחת כן מפרת, ואז לא שינה אותו בשינוי גדולה.
* לה.
** והלא מוחזרים -
אין לך חזרה כזו- לשון זה מוזר; לכאורה, ר"ל כעין אין לך חזרה גדולה מזו. אולי אומרו בתמיהה, והוא שאטו אין כעין זה נחשב חזרה. דחו"ק.
