מבוא
** חברנו
ספר קטן זה
על הר ה' מי יעלה
לא אנחנו, לא על זה
מי יחמול ומי יכסה
** פעמים
מאה הוא נכפל
מאיגרא רמה הוא נפל
עטרת ראש הוא כבר נטל
כי בתורה אני דל
** מה שהוא
, הוא אינו פשט
לסמוך עליו בשעת הדחק
סחורה טובה בא וקח
אבינו, לנו, נא תסלח
** טרחנו
נורא ואיום
זריז לעבודת היום
כתבנו כולו, כל עד תום
ויאמר אל תקרב הלום.
** עכשיו
, זמן לתת תודה
לכותבה וללומדה
למי שנתן עיניו בה,
למי שהתפרנס אותה
** נשמר
את זה לאוהביו,
וגם לשומרי מצוותיו
לכל מי שיביט עיניו
בסוטה בדף לו.
פתיחה
קרא אומר, "התורה אדם כי ימות." חז"ל דרשו ממנו ש"אין דברי תורה מתקיימים אלא במי שממית את עצמו עליהם." אבל, לכאורה, גם כתיב, "זאת חקת התורה…" גבי פרה אדומה. צריך לבאר מה לומדים משם בענין התורה.
נראה שהלימוד הוא שתורה אינו דבר מובן. כמו שפרה אדומה הוא דבר ש"אמרתי אחכמה והיא רחוקה ממני," ואפילו שלמה לא היה יכול להבין, אף כל התורה כולה הוא דבר שלא קל להבין, והוא דבר שצריכים שלא להבין.
נראה שיש קצת יותר, והוא שגמ’ ביומא מקשה מהו קשה בדיני פרה.
מקושיא זה, רואים יסוד אחר מדיני פרה, והוא שאף אם דבר נראה שהוא מובן, ודבר נראה פשוט וברור, עדיין צריכים לחשוב עליו עד שלא נבין אותו.
ברוך ה', בימים שלנו, יש הרבה ספרים שנכתבו שהם קלים לאדם שלא להבין. לא צריכים לטרוח כמו בימי הקדמונים שלא להבין; יכולים להביט ברב ברוך בער ויכולים שלא להבין מיד.
ולא רק ברב ברוך בער יכולים להביט, אלא אף בספר קטן זה, ששמו "נכפל במאה (ואחד)", יכולים להביט, ושלא להבין.
בספר זה, לא רק כתבנו דבר אחד או שני דברים שלא תוכל להבין, אלא כתבנו פשט אחד שהוא הפתח שלא להבין את כל התורה כולה. חזרנו על הפשט הזה כמעט מאה פעמים - ולכן קראנו לספר זה בשם הקדוש "נכפל במאה (ואחד)"- עד שלא תבין אותו כלל וכלל, כמו שאומר גמרא בעירובין שצריך אדם להיות צייד רמאי וקובץ על יד.
בראשית
א
כתיב שה’ ברא את האדם בצלם אלהים ובדמות דיוקנו. צריך לבאר איך אדם יכול להיות בדמות דיוקנו של ה’ כיון שאין לה’ דמות. נראה לבאר ש"דמות דיוקנו של ה’" אינו אומר "הדמות שיש לה’,” שאין דמות לה’. אלא רצה לומר דמות דיוקנו של אותו איש של ה’, והוא שכמו שנראה ה’ לו, כן הוא האדם. מי שחושב על ה’, מי שמרגיש ה’, להיות אדון כל ולהיות אלהים ממש, הרי הוא דומה לו, ומקיים מה שאמרו חז"ל לדמות לה’, וקונה מדות אלו. להפך, אם אדם חושב על ה’ להיות מי שאינו חנון, אף הוא לא יהיה כן. אז, נמצא שמה שאדם חושב על ה’ יש לו כוח לפעול עליו.
ואיך זה נעשה? לכל אדם יש חלק מה’ ממעל. כשאדם חושב על ה’, ומכיר בטובת ה’, אז נשמה שלו נתעלה להיות כמה שחושב, שכל דבר נשתנה על פי מה שנחשב עליו. על ידי זה, כשאדם חושב על ה’, הוא עצמו נשתנה להיות כן, ונשתנה להיות כמו ה’, בכל זמן שחושב עליו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן דרשה דומה של "דמות דיוקנו.”
נראה לבאר הסיבה שמהות האדם תלוי בחושבו על ה’ שהוא שאם אדם חושב על ה’ להיות מי שאינו חנון, מדה כנגד מידה, לא יתן ה’ אותו מידה. אז, ה’ נוהג עמו, כמו שאמר גבי יוסף, כאילו אינו חנון, ועושה אותו דומה לה’ שאינו חנון. זה מפני שכשחושב על אדם, נעשה כך.
ב
מרש"י יוצא שכל דבר נברא מיד, בתחילת העולם, ורק בא לעולם ביומו. קשה, שגם אומר שכל הבריאות רק באו לעולם ביום הששי, אחר שנברא אדם. צריך לתרץ סתירה זו.
נראה שהביאור הוא שכבר באו לעולם. אבל, בלי אדם לחשוב עליהם להיות בא לעולם, לא ממש באו לעולם. מה שמגדיר את החפץ הוא, בעיקר, מה שחושבים עליו, כמו שמצאנו שאדם הוא כן.
אם חושבים על אדם להיות ישר, הוא איש ישר. אם חושבים על אדם להיות צדיק, הוא צדיק. אבל, אם חושבים על אדם להיות רשע, הוא רשע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
נח
א
נח עסק בבניין התיבה לזמן רב, למאה ועשרים שנה. חז"ל מבארים לנו שרצה ה’ שיעסוק לכל כך זמן כיון שאז יראו אותו בני אדם, ישאלו לו מה עושה, ויגידו להם שיהיה מבול ושצריכים לשוב. קשה; אחרי מאה שנה, לכאורה, ידעו כבר מה עושה, ואז לא יועיל בנינו.
נראה לבאר שלא היה רק כדי שיאמר להם שיהיה מבול, אלא כדי שיראו שיש מי שעדיין מנסה להשיב אותם. נמצא שהיה חושב עליהם לבני אדם שיכולים לשוב. כיון שכן, יוכלו לחשוב על עצמם לבני אדם שיכולים לעשות רצון ה’. אז, עדיין היה תקווה שישובו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
אמרו חז"ל שנח היה מקטני אמונה. קשה להאמין איך מי שבנה תיבה למאה ועשרים שנה היה מקטני אמונה. גם קשה לומר שמי שטרח ה’ בעדו להצילו מן המבול אף לא האמין בה’.
שמעתי מאדם חשוב שהיה נח מקטני אמונה בעצמו. לא חשב על עצמו להיות כל כך צדיק, ולא חשב על עצמו להיות יכול להציל את כל דורו.
נראה שזה מבאר דבר שהוא פלא גדול. קשה: איך לא עשה אף אחד תשובה בימי נח. נח היה איש חשוב, והיה טורח ליותר ממאה שנה להציל בני אדם - איך אפשר שלא הצליח אף באדם אחד?
נראה שלא הצליח כיון שלא חשב על עצמו להיות אדם חשוב ואדם שיכול להצליח.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
אחר שיצאו מן התיבה, הותר לבני נח לאכול בשר בהמות. צריך לפרש למה דווקא עכשיו נשתנה דין זה. לכאורה, זה לא נוגע כלל לשאר דברים שבפרשה זו.
נראה לבאר שהמבול בא על שבני ישראל היו חושבים על עצמם לבהמות - בהמה עושה מה שהוא רוצה, ואני עושה מה שאני רוצה. ממילא, היו חוטאים. ה’ אמר להם - לא! בהמה חלוק ממכם, ואעשה בזה רושם גדול, שאתיר בהמה לאכילה, ואאסור אדם לאכילה. אז, תחשב על עצמכם להיות אדם, ולא בהמה, ותחשב שאדם אינו דומה לבהמה. כשאתה חושב על עצמך כן, בוודאי לא תחטא.
רואים מכאן שאם אדם חושב על עצמו להיות אדם חשוב, אדם שלא יחטא, נכון הוא, ולא יחטא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
לך לך
א
אברהם לחם עם ארבעה מלכים והיה יכול לכבוש אותם. מבאר גמרא בתענית (כא.) שהיה לו עפר מיוחד שכשנזרק, היה נהפך לרמחים. אבל קשה איך היה אברהם יכול לבטוח על נס כזה וללחום שלא בדרך הטבע.
נראה לבאר שהיה אברהם חושב על עצמו להיות מי שה’ עמו, ומי שה’ לוחם בעדו. כיון שכן, היה בוודאי מנצח, וממש לא היה לו יכולת שלא לנצח. אז, לא היה סומך על הנס, אלא היה פשוט לו שה’ יעזור בעדו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
דורשים חז"ל שה' הבטיח את אברהם ש"בך חותמים," ובני ישראל יגמרו ברכה ראשונה של שמונה עשרה עם שם אברהם, שאומרים, "מגן אברהם." צריך ביאור למה אברהם ירצה את זה. אטו הוא מעוניין בכבוד מאת בני בניו?!
נראה שהביאור הוא שידע כמה וכמה בני אדם יאמרו שה' מגן של אברהם, והוא שיברכו על שם קדושת אברהם וייחסו עם ה'. אז, הכיר איך יחשבו עליו. כיון שכן, היה יכול לחשוב על עצמו כן, וממילא היה יכול לעשות את עצמו כן ביותר קלות.
רואים יסוד חשוב - הוא כל כך חשוב, וראוי לכתוב עליו ספרים וספרים - והוא, שמה שחושבים בני אדם על אחד ממש משנה אותו אחד על ידיהם בשינוי נפלא, על ידי שמשנה איך שחושב על עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
וירא
א
קשה איך היה יצחק יכול להסכים להיות עצמו נעקד; מי ימסור נפש כך על ציווי שלא היה נודע לו כלל?
נראה שהענין הוא שכיון שאמר לו אביו שהוא לקרבן, וכיון שהוא ראה אותו למי שהוא ראוי להיות קרבן, היה יכול לראות את עצמו לקרבן, והיה יכול לראות את עצמו למי שראוי להיות קרבן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
כשהגר נגרשה מבית אברהם הלכה במדבר, וכמעט מתה מחסרון מים. בא לה מלאך, וגילה את עינה וראתה באר מים. צריכים אנו לבאר למה הגר לא ראתה הבאר בעצמה, בלא עזרת המלאך, אם היה ממש בפניה.
הגר היתה במצב רע. אדונה, שהיתה הרעביצין והמורה שלה, גירשה מביתה, והיתה במדבר. כמה פעמים, כשאדם במצב רע, כיון שחושב על עצמו לולא כלום, רגיל שלא לחשוב ששום טוב יכול לבוא לו. לכן, לא היתה הגר יכולה לראות המים. כשבא מלאך, גילה את עינה - גילה לה מה היתה באמת, ומיד ראתה את המים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
התורה מספרת איך שנמצא שבא לוט על בנותיו, והולידו ממנו בנים. הבכורה קרא לבנה מואב, שבא מאביה, והצעירה קרא לבנה עמון, שדומה ל'בן עמי.' גמ' מספר שכיון שלמואב היה שם מגונה, נענש. צריך להבין למה זה גורם לו עונש, ומה לנו שיש לו שם גרוע.
נראה שכל זמן שאדם היה קורא לו, היה זוכר, “אני ממזר; אני איש גרוע." כיון שכן, היה ממש איש גרוע, ומחמת כן נענש.
רואים מזה שאם בני אדם חושבים על אדם שהוא רע וגרוע, יהיה רע וגרוע ממילא. אז, כל כך יקר הוא מה שאנחנו חושבים על חברינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
חיי שרה
א
אומר רש"י שרבקה באת ליצחק "והנה היא שרה.” אבל זה קשה, שלא היתה שרה. יש פשטים דחוקים, אבל עושים שדברי רש"י הקדוש אינם מכוונים. אז, צריך ביאור איך יאמר תורה שהיא שרה.
נראה שהענין הוא שכשקוראים אנו בשמות לדברים, הם רק שמות שבני אדם מכנים. אז, אם כל בני אדם מכנים לה שם שרה, הרי היא שרה. נראה שכל בני הבית חשבו עלה להיות שרה, ולהיות אשה חשובה הראויה להיות אם של בני ישראל.
ולכן זה יבאר איך אשה שגדלה בפני רשעים כבתואל ולבן היתה יכולה להיות אם של בני ישראל; מפני שבני אדם חשבו עלה לאם, היתה יכולה להיות אם.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
אומר קרא שכשרבקה ראתה את יצחק בפעם ראשונה, נפלה מגמלה. וקשה מה קרה לה ליפול. נראה שהענין הוא שראתה יצחק, וראתה חשיבותו, ולא הכיר בחשיבות של עצמה להיות נשואה לאיש כזה, ולכן נפלה. רואים מזה שאף שאחרים חושבים על אדם להיות חשוב, צריך אדם לחשוב על זה ולעשות שאף הוא חושב על עצמו כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
אף שיוסף היה כבר נחשב להיות חשוב, אנחנו רואים שחז"ל דברו בגדולתו. לכאורה, צריך לומר שעשה דבר חשוב - ואותו דבר חשוב הוא שהיה יכול להוציא את הכח ממה שחשבו עליו אחרים, ולעשות שאף הוא יחשוב על עצמו לטוב.
ג
הקרא כותב שחיי שרה היו מאה ועשרים ושבע שנים. יש חז"ל ידוע שדורשים שכשהיתה בת מאה, היתה כמו בת כ', שלא היו לה עבירות. יש שני קושיות פשוטות.
הראשון הוא איך אפשר להיות שחיה עד בת מאה בלי עבירות. הרי, אנחנו לא חיים כל כך זמן, בדרך כלל, והרי אנחנו מלאים עבירות כרימון.
השני הוא למה בוחרת התורה לגלות מעלתה באופן זה. לכאו', היה לו לומר שלא היו לה עבירות, ולא לומר שהיתה כבת כ.
נראה ששני הקושיות יכולים להיות מתורצים בתירוץ אחד. נראה שהדרך שלא עברה עבירה היא שראתה את עצמה כבת כ, כמי שפשוט אי אפשר לעשות עבירה, כמי שעליה עבירה לא חל. כיון שכן, ממילא לא עברכה. לכן, גם כן, מזכיר שהיתה כבת כ', לא רק מפני שכן היתה, אלא מפני שלכן היתה כן.
רואים מזה שאם אדם חושב על עצמו שלא יכול לחטוא, ושחטא ממש לא שייך לו, לא יחטא, ולא יהיה חטא שייך לו.
אומר גמ' סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טוב, כמו יוסף.
ד
כשהפסוק מדבר על אליעזר עבד אברהם מתחילה קורא לו עבד של אברהם. אבל אחר כך משנה, וקורא לו "איש." צריך ביאור למה שינה קרא.
צריכים לראות איפה שינוי זה קורה - מתי משנה הפסוק מלקרותו עבד ומתחיל לקרוא לו איש. הוא קורה מיד אחר שרבקה דבר לו וקרא לו אדוני.
נראה שההסבר הוא שכיון שאחר חשב עליו לאדון ואיש חשוב, הוא שינה, שגם הוא חשב על עצמו לאיש חשוב. ממילא היה איש חשוב, ולכן תורה קרא לו בלשון איש, ולא בלשון עבד, שלא היה לשון זה הגון לו עוד.
רואים מזה שאם אדם חושב על עצמו שלא יכול לחטוא, ושחטא ממש לא שייך לו, לא יחטא, ולא יהיה חטא שייך לו.
אומר גמ' סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טובים כמו יוסף.
תולדות
א
הפסוקים מדברים באהבת יצחק על עשו. וקשה למה היה יצחק אוהב את עשו; אטו לא היה יודע שהיה יעקב איש תם יותר מעשו?
נראה שלא, באמת, החשיב את עשו יותר. אלא ראה שעשו היה צריך סיוע, ואז ניסה לחשוב עליו להיות איש טוב ואיש חשוב. ומה היה היסוד בזה, שכשעשו יראה איך התנהג יצחק אביו עמו, ישנה את עצמו להיות איש ראוי לחשיבות שיצחק נהג עמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
עשו רצה להרוג את יעקב.  לכאורה זה צריך ביאור, שרצה להרוג אותו על שנטל את הבכורה. אז, ממה נפשך, קשה. אם חשב שהבכורה לא יעשה כלום, למה רצה להרוג אותו? ואם סבר שישמור עליו ויחזק אותו, איך חשב שיוכל להרוג אותו?
נראה שבאמת עשו, שהיה רשע גמור, לא האמין בבכורה כלל. אלא, ידע שהרבה אנשים האמינו בו, ותמיד יחשבו על יעקב להיות מי שמוזמן להצלחה. אז, יעקב יחשב כן על עצמו, ואז בוודאי יצליח. לכן, רצה להרוג אותו מיד, קודם שזה ייעשה.
רואים מעשו הרשע יסוד גדול, והוא שאיך שאתה חושב על חברך - זהו מה שהוא יחשב על עצמו, וזהו מה שהוא יהיה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ויצא
א
כשיעקב היה רועה לצאן של לבן לשכר הכבשים שהיו בצבעים שונות ונקודות מוזרות, הוא נתן לפני הכבשים מקלות מקופלות כדי שיולדו באופן כעין המקלות. אבל צריך ביאור איך זה פועל על מה שיולידו.
נראה שהכוונה הוא שכשנתן יעקב אותם מקלות שם, הכירו שהיה חושב עליהם לכשבים עם יחס לנקודים או כדומה. וכיון שחשב עליהם כך, הולידו נקודים, כמו שהיה יעקב חושב עליהם.
ואם לבהמה כך, על אחת כמה וכמה לאדם; אם אדם חושב על חבירו להיות טוב ולהיות צדיק, ממילא נעשה כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
אומר אברהם בפרשת וירא שהוא עפר ואפר. מחמת זה, אומר ירושלמי, זכה ל"והיה זרעך כעפר הארץ” האמור ליעקב בפרשה זו. צריכים לבאר מהו יסוד של מדה כנגד מדה בזה. הדעת נותנת שאינו רק דמיון מילה, אלא יש סיבה יסודי שיהיה כן.
נראה לפרש שאברהם לא רק אמר כן על עצמו, אלא כן היה חושב על עצמו. כיון שחשב כן על עצמו, במדרגה אחת, כן היה. לכן, ממילא היה בניו כעפר ואפר.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
מצינו שרחל גנבה את התרפים מאת אביה לבן. לכאורה, צריכים לבאר איך אפשר שאחד מן האמהות, ואשה של איש החסד, היא אשה שתגנוב ושתשקר.
נראה שיש להעיר על רש"י שמבאר שלבן הלך כמה פעמים לאהל רחל כיון שהכיר שהיתה רגיל להיות גונבת. נראה שהענין הוא כך: לבן חשב על רחל להיות גונבת. אז, אף שהיתה כל כך קדושה וטהורה, היתה גונבת, וכוח של אותו עבירה היה גבורה יתירה עליה. אז, גנבה את התרפים, ואז שקרה עליו.
רואים מכאן שכשאדם חושב על חברו להיות חוטא, הוא ממש עושה אותו חוטא. זה יסוד שצריכים לחשוב עליו תמיד ותדיר.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ד
ה' הזהיר ללבן שלא ידבר עם יעקב לא טוב ולא רע. מובן למה לא ידבר עמו לרע, אבל קשה למה לא ידבר עמו לטוב. כמובן, מחוסר הדנים בשאלה זו, ואנחנו נזקקים לדון בו.
נראה שלבן, שהיה רשע, היה לו דרהר רע על יעקב. כל זמן שהיה מדבר עם יעקב, היה מראה ליעקב אותו דרהר שלו. אבל ה' לא רצה שיראה לו כך כיון שכשיעקב מבין שיש מי שחושב עליו להיות איש רע, אף הוא יחשב כן על עצמו, ואף הוא יהיה כן. אז, ה' הזהיר את לבן שלא לדבר עמו כלל.
רואים מזה שאף צדיק כיעקב יכול להיות מושפע ממה שאחרים חושבים עליו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ה
קשה איך היה יעקב יכול לגלל האבן מעל הבאר אם כרגיל היה צריך כל הרועים לעבודה זו. יעקב לא היה איש חזק; בפרט בזמן הזה שהיה למד תורה לארבע עשרה שנה לפני ביאתו לחרן, ותורה מתשת כוחו של אדם. גם לא היה יכול להילחם עם עשו או עם אליפז.
נראה שצריך לבאר שלא היה קשה לגלות את הבאר, וכל איש תש היה יכול לעשות אותו. אבל, מנהג של הרועים היו שכולם היו עושים אותו ביחד. כיון שכן, כולם חשבו על עצמם שלא יכול לגלות בלי חברו. לכן, לא היו יכולים לעשות בלי חבריהם. רק יעקב, שלא חשב על עצמו כן, היה לו היכולת לגלות את הבאר.
רואים מכאן יסוד: אדם שחושב על עצמו באופן גרוע ממש מתיש את כוחו. אז, צריך לשמור מאד מה חושבים על עצמינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
וישלח
א
יעקב נאבק עם המלאך כל הלילה, וכבש אותו. אחר כך, קרא לשם של אותו המקום ”פניאל“ כיון שראה ה‛ פנים אל פנים וינצל נפשו. יש להעיר שלכאורה עיקר של מה שקרה שם היה שאף שהיה קשה לו, נתנצל נפשו. אם כן, היה לו לקרוא לו ”נצל“ או כדומה, ולא על שם שראה ה‛ פנים אל פנים.
נראה שיש לדון למה אומר לשון ”פנים אל פנים,“ ולא לשון ”פנים אל ה‛,“ שלכאורה, אין פני ה‛ בו. יש לבאר שאין הענין רק שהוא קרוב לה‛, אלא שמכיר מה שה‛ מדרהר בו. זהו פנים אל פנים - פנים של אדם קרוב לפנים וראיית ה‛, ויכול להכיר בו.
על פי זה, נראה לבאר שמה שהיה יכול יעקב ללחם עם מלאך היה מפני שהיה יכול להכיר את עצמו לאיש חשוב. היה יכול להכיר את עצמו כך כיון שראה ה‛ פנים אל פנים - ולכן ”וינצל נפשי.“
על כן, קרא לאותו מקום פניאל, שזה היה הסיבה להצלתו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
כשיעקב שמע שהיה עשו בא, שלח מתנות לו כדי שעשו לא יזיק אותו. צריך ביאור מה היה חושב יעקב, ואיך דבר כזה יפייס את עשו.
יותר קשה מזה הוא מה שקרה באמת שיעקב היה נכון, ועשו בא עליו ברחמנות. צריך ביאור איך זה קרה.
נראה שהביאור הוא כך: יעקב הראה לעשו שהוא חושב עליו לאח אוהב וריע. ממילא, גם עשו חשב על עצמו לאח, ואח לא שונא את אחיו. לכן, בא ליעקב ברחמנות.
רואים שאף רשע יכול לשנות על ידי מה שחושבים עליו. זה כח גדול, וצריכים להשתמש עמו תמיד לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
וישב
א
אומר קרא שכשירד יוסף למצרים, ירד עם עגלות שהיו בהם בשמים ודברים שיש להם ריח טוב. אבל קשה מה לנו שהיו שם בשמים. גם קשה מה לו ליוסף שהיו עמו בשמים - הרי הוא הולך למקום קשה של מצרים, ולקראת חיים קשה של עבד - ועכשיו מריח בשמים. לכאורה, אין זה מנחם גדול לו.
יש לומר שמה שעשה בשמים הוא שהיה יכול יוסף להכיר שה‛ היה עמו. אף שלא היה ה‛ עושה שלא הלך למצרים, על כל פנים היה עוזר לו קצת והיה מראה לו שהוא נוסע עמו בכל הדרך שחיים שלו הולך.
נראה שזה היה חשוב ונצרך שכיון שהיה יוסף יכול להכיר שה‛ היה עמו, היה יכול להכיר שהוא אדם חשוב בעצמו. השבטים כבר דנו עליו וחייבו אותו מיתה, ועכשיו הוא משתלח למקום טומאה של מצרים וקשה איך יהיה יכול לחיות חיים של רוחניות שם. אבל כיון שהכיר שה‛ היה עמו, אז היה יכול לראות את עצמו כמי שהוא נאהב של ה‛. וכיון שהיה מכיר את עצמו כך, ממילא היתה ישיבתו במצרים ישיבה אחרת - היתה ישיבה של בן יעקב במצרים, ולא רק ישיבת עבד במצרים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
כשיוסף ספר חלומותיו לאחיו, אמרו לו ”המלך תמלוך עלינו אם משל תמשול בנו.“ שמעתי שיש מקשים למה כופל ”המלך תמלוך,“ ו”משל תמשול.“
נראה לבאר שאמרו ליוסף, ”אם אתה מולך - וחושב על עצמך למלך - אז מלוך עלינו.“ זה אומר שהגידו לו שכדי להיות מלך, נצרך שיחשוב על עצמו למלך.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
נראה שלכן אחר שבאו אחים למצרים, הודו לו למלוך עליהם. הכירו שכבר חשב על עצמו לאדם חשוב ולמלך, שבזה ניצול מעבירה, ואז היה ראוי למלוך עליהם, כמו שאמרו הם בעצמם שנים רבות קודם לכן: "המלך תמלוך עלינו."
ג
פסוק אומר, "וישב יעקב…" ובאר רש"י: "בקש יעקב לישב בשלווה…" אבל ה' לא הרשה לו לישב בשלווה. וקשה למה לא היה טוב שיהיה לו קצת חופש, ושישב בשלווה קצת. מה רע עם שלווה קצת?
נראה שההסבר הוא שאם אדם לא יושב בשלווה, חושב עליו להיות צריך טורח וחושב: אני איש שחייב לטרוח. וכיון שכן, ממילא יש לו יותר כח לטרוח, ואף לטרחות אחרות, כמו טרחת תורה. לכן נראה שרצה ה' שצדיקים ישבו בצער כדי שיחשבו על עצמם להיות בני אדם שצריכים לטרוח.
רואים מזה שמה שאדם חושב על עצמו משנה אותו.
אומר גמ' סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טוב, כמו יוסף.
ד
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יש להוסיף שלא מצאנו הרבה בני אדם שנקראים בשם ”הצדיק.“ אבל, יוסף היה נקרא כן והיה ”יוסף הצדיק.“ נראה שההסבר לזה תלוי בביאור שכתבנו. הרי השם הוא סימן למה שחושבים בני אדם על דבר. כשאדם רואה תפוח, חושב ”תפוח,“ ולכן הוא השם שלו.
יוסף נקרא על שם ”צדיק“ כיון שמה שהיו בני אדם חושבים על צדיק כל כך ראוי לו, שזה היה מה שהציל אותו מעבירה. ומה שעשה אותו ליוסף הוא מה שגורם אותו להיות ראוי לשם שלו להיות נחתם על החושן הקדוש.
מקץ
א
קרא אומר שראה פרעה בחלומותיו פרות שהיו רעות מראה, והיו אוכלות את הטובות, וזה היה פלא. לכאורה, לשון "רעות מראה" קשה, שרק צריך לומר שהיו רעים.
נראה שאותו פסוק אומר שהיו רעות מראה - לעצמם, שהיו רעות לתוך מראה שהיו רואים על עצמם.
הפלא היה שיאכלו את הגדולים אף שחשבו על עצמם להיות חלושים. כיון שראה פרעה את זה, ידע שדבר כזה אי אפשר, הוא כפיל ההולך לתוך נקובת מחט, וצריך להיות סימן מן השמים.
רואים מזה יסוד: מה שאדם חושב על עצמו הוא חשוב מאד. לא היו פרות, באופן רגיל, אפשר לאכול פרות אחרות כיון שראו על עצמם מראה רע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאז יחשבו על עצמם טוב, ואז יהיו טוב.
ב
האחים אמרו שהיו יראים שיוסף ייקח אותם לעבדים וגם ייקח את החמורים שלהם. לכאורה, קשה מאד; הרי חשש של עבדים הוא יותר גדול מאד מחשש של חמורים. אחרי שכבר הזכירו אותו חשש הגדול, אין צורך להזכיר חשש הקטן של לקיחת החמורים ולמה אמרו החששות בסדר הזה?
נראה לבאר שלא חשו אחי יוסף שיהיו עבדים, שהיו חזקים מאד. אבל, חשו שיחשבו עליהם לעבדים, יחשבו עליהם לרע, וזה יזיק אותם באופן רוחני.
אז, אמרו שני חששות - חשש רוחני, שיחשבו עליהם לרע, וחשש גשמי, שייקחו את החמורים שלהם.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טוב, כמו יוסף.
ויגש
א
אחר שגילה יוסף לאחיו מי הוא, שאל אם "העוד אבי חי." וקשה, שהרי ידע שהיה חי, כיון שאמרו לו אחיו שהיה חי כמה פעמים כשדברו.
יש לדקדק למה אמר "אבי," ולא "אבינו." הרי, לא היה רק אב של יוסף, אלא היה אב של כל האחים וכל השבטים כולם. אז, מוזר שרק דיבר על אביו, ולא על אב של כולם.
נראה שלא היה שואל אם היה חי - בוודאי היה חי. אלא היה שואל אם היה עדיין כמו שזכר אותו, וכמו שחשב עליו. מה שאדם חושב על חברו משנה אותו. אז, חש יוסף שכיון שלא היה בפני אביו לחשוב עליו ולדרהר אותו לו, שינה אביו. אז, שאל אם עוד אבי - האב שעשיתי והאב שדרהרתי, עודנו חי.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
קשה איך לא הכירו אחי יוסף את יוסף. לכאורה, פשוט הוא שצדיק כזה יכול להיות ניכר. אז, קשה איך לא הכירו אותו מחמת צדקתו.
נראה לבאר שכיון שהאחים חשבו אותו למצרי, ולא לצדיק, באותו שעה ובאותו רגע, לא היה כל כך צדיק. וזהו הטעם שלא היו יכולים להכיר אותו.
רואים מזה יסוד חשוב. מה שבני אדם חושבים עליך, ואף עם סיבה מוטעה לגמרי, משנה אותך, ועושה אותך כן. לכן צריך להקפיד איך חושבים על אחרים שיהיו צדיקים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
לפני שיוסף גילה מי הוא, שלח את כל הנכרים לחוץ. אך קשה למה שילח אותם, ומה לנו אם יראו גילוי יוסף לבניו.
נראה שהכיר יוסף שאם הנכרים יראו את זה, יחשבו רע על האחים שמכרו את יוסף. וזה יעשה רע לאחים, שמה שאדם חושב על חברו גורם שחברו יחשוב כן על עצמו. אז, לא רצה שיראו את הגילוי ויכירו מה קרה ויחשבו על אחיו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ויחי
א
אמרו חז"ל (תענית ה:) ש"יעקב אבינו לא מת." אבל קשה לומר שיעקב ממש לא מת, שהרי הפסוק אומר שקברו לו. אז, צריך לומר שמת. ואם כן, גמרא זה צריך ביאור כשאומר שיעקב לא מת.
נראה שהיה ליעקב הבטה מיוחדת על בני ישראל, והיה לו כוח לדרהר בני ישראל. מפני זה, אנו נקראים בני ישראל, ולא בני אברהם או בני יצחק. היה יעקב יכול לדרהר אותנו, ואותו דרהר שהיה חושב עלינו היה מה שעשה אותנו לעם של תורה ועם של ה’.
וזהו מה שאמרו חז"ל שיעקב אבינו לא מת. גופו מת, אבל אותו הבטה שהיה לו על בני ישראל עדיין חי וקיים, שמחמת מה שהוא דרהר על בני ישראל, בני ישראל, אף היום, מדרהרים כן על עצמם. אז, הגמרא יכול לומר באמת שיעקב לא מת.
רואים במקום אחר אותו כוח מיוחד של הבטה שהיה ליעקב אבינו:
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
חז"ל אומרים שיעקב אבינו לא מת. יש לפרש מהו כוונה שיעקב אבינו לא מת. כמו כן, נפרש מה כוונת המימרא של חז"ל שצדיקים במיתתם חיים ורשעים בחייהם מתים.
נראה שזה תלוי בביאור חיים ומוות. החי הוא מי שמשנה, שלא לעולם הוא אותו דבר. מה שרשע נחשב מת הוא שחושב על עצמו שאי אפשר לשנות, וכיון שהוא רשע, לעולם יהיה רשע. אבל, צדיק תמיד חושב על שינוי, ששינוי אפשר. אז, אף שהוא מת, הוא עוד משנה, שכיון שחשב כן על הרבה בני אדם, הם חוזרים בתשובה, ונותנים לו זכויות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יש להוסיף שצריך ביאור מה ראה יעקב ביוסף. הרי יעקב לא ידע איך יהיה יוסף, שלא ראה אותו כבר לזמן רב. נראה שהא גופא - זה בעצמו הוא הנקודה. נראה שיוסף לא ראה כלום. חשב לעצמו פתאום: ”זה - כלום - הוא מה שאבא חושב עלי! אבי מכיר שאני יכול לשנות. אני לא חייב להיות רשע רק מפני שהייתי רע עד שגרמתי לעצמי שאהיה ניתן לעבד במצרים.“ וכיון שכן, לא עבר.
שמות
א
אמר קרא שקם מלך חדש על מצרים "אשר לא ידע את יוסף." חולקים חז”ל אם היה מלך חדש ממש או לא. הגמרא מפרש שאילו לא היה מלך חדש ממש, ידע את יוסף, אבל עשה את עצמו כאילו לא ידע את יוסף. צריכים לבאר מה בכלל עשה את עצמו כאילו לא ידע את יוסף.
נראה שלא רק עשה כאילו לא זכר אותו. אלא, עשה את עצמו כאילו לא היה מדורהר על ידי יוסף. הדרך שאדם מדרהר את חברו עושה את חברו, ומה שאדם חושב על אחר עושה שאחר חושב על עצמו, וממילא כן נעשה אותו אחר.
אז, פרעה היה יכול לעשות את עצמו כאילו לא ידע את יוסף, מפני שעשה את עצמו שלא באופן שהיה יוסף מדרהר אותו.
מזה רואים יסוד חשוב: הדרך שאדם מדרהר על חברו משנה איך חברו חושב על עצמו וזה משנה מי הוא אותו אחר. אבל גם רואים יסוד אחר: כח של היצר הרע הוא כל כך גדול שאף יכול לעשות שכופר באותו דרהר.
אז, צריכים להיות כל כך זהירים לחשוב טוב על חבירים שלנו, ולשמר על עצמינו, שכשאחרים חושבים טוב עלינו, וכשאנו חושבים טוב על עצמנו, שלא נניח את היצר הרע, חס ושלום, לבוא אלינו ולקחת מאתנו אותו טוב שהושפע עלינו מחמת אותו דרהר ואותו מחשבה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
צריכים לבאר למה לא היה שעיבוד מצרים כשהיו שבטים עדיין בחיים. לכאורה, אין סיבה שזה ימנע את המצריים מלשעבד את בני ישראל.
נראה שהביאור הוא שלהם היה פרעה מאד טוב, והם הכירו בטובת בני מצרים. אז, חשבו על מצריים להיות אנשים טובים. לכן, כל זמן שהיו בחיים, וחשבו על המצריים ככה, לא היו המצריים יכולים להיות רעים ולשעבד את בניהם.
רואים מזה יסוד שהוא מאד חשוב: שאף רשעים כמו מצריים יכולים להיות טוב אם יש מי שחושב עליהם טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
וארא
א
גמרא (פסחים נג:) אומר שחנניה מישאל ועזריה נשאו קל וחומר מן הצפרדעים שהפילו את עצמם לאש, אף שלא היו מצווים. צריך לבאר איך היה לצפרדעים הכח להפיל את עצמם לאש בלי שום ציווי; איך היו יכולים לחזק את עצמם להרוג את עצמם כשלא היו מחויבים על זה.
מהרש"א שם מבאר שיש יותר מעלה על פי מה שהיו צפרדעים. הצפרדע הוא דבר שחי במים ואש הוא הפוך של מים. אז, יהיה קשה לו ביותר להפיל את עצמו באש שהוא הפוך של מה שמחיה אותו. אבל בהמה וחיה אחר, שחי ביבשה, לא היה כל כך קשה לו, שאין אש הפוך של חייו.
לכאורה, המהרש"א הוא קשה להבין. מה שהוא קשה בהפלה לאש אינו מה שהוא הפוך של מה שמחיה אלא הוא מה שממית. לכאורה, לכל בהמה האש ממית, ולכן קשה מהו הייתור גבי הצפרדעים.
נראה שצריך לומר שהסיבה שהיו יכולים לזרוק את עצמם לתוך האש הוא שכיון שידעו שה’ רצה שיהיו בתוך האש, היו מדרהרים את עצמם להיות בתוך האש. כיון שכן, ממילא היה קל לזרוק את עצמם בתוך האש, שכבר היו נדרהרים כן.
זה יבאר גם כן המהרש"א. המעלה של צפרדעים היה מפני שיותר קשה להם לדרהר את עצמם להיות בתוך האש, כיון שהיה האש הפוך של מקום חיותם. זה היה מעלה יותר גדולה בצפרדעים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
כשמשה מדבר אל פרעה, ה' אמר לו שיגיד לו את דברי ה’. אבל, לא קורא אותו, ”ה’ אלקי השמים“ או כדומה, אלא ”ה’ אלקי העברים.“ יש לדון למה היה קורא לו באותו תואר.
נראה שחלק מן התכלית של הדיבור עם פרעה היה לתת חיזוק לבני ישראל העבדים. לכן אמר להם "אתם עם של ה’." כשאומר כן, יחשבו על עצמם להיות עם ה’, ולהיות חשובים, ויהיו באמת כן.
רואים מזה שמאד חשוב לחשוב על עצמינו להיות טובים וחשובים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
בא
א
קרא אומר שבני ישראל אכלו מצה עם קרבן הפסח בהיותם במצרים. וזה קשה, שמצה הוא לחם שאוכלים לשמח על יציאת מצרים וחירות שלנו. אם כן, איך אכלו אותו כשהיו במצרים.
שמעתי פשט נפלא: בני ישראל כבר דרהרו על עצמם להיות בני חורים. מפני זה גופא היו נעשים בני חורים, שכיון שדרהרו כן על עצמם, וממילא כן נעשה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
ה' מחייב לבני ישראל לקדש כל בכור לה’. לכאורה קשה, שקדושתו לה’ הוא במה שעובד. אם יש ששים ריבוא בני ישראל, יש הרבה והרבה בכורים ואז לא היו עובדים כל כך. בשביל עבודה קטנה זו, איך נוכל לקרוא להם מקודשים לה’.
נראה שצריכים לבאר את דעת כהן. כדי שכהן יוכל לכוון כוונה הראויה על עבודתו, צריך לחשוב שהוא מקודש לה’ - הוא חפצא ששייך אך ורק לה’. רק אז יכול לעבוד כראוי.
אז, ה' אמר שצריכים לקדש כל בכור, שבאמת, בכור הוא קודש לה’.
רואים מזה יסוד. כדי שנוכל לעבוד לה’ לגמרי - שהרי רמב"ם אומר שכל אחד יכול להיות ככהן שמקודש לה’- צריכים ממש לקדש עצמינו לה’, ולא די לומר, "לפרקים אני לומד" או דבר אחר כזה. הענין של מחשבה זה על עצמו הוא שרק אם אדם חושב על עצמו כן, יכול לעבוד את השם באמת, שמחשבה על עצמו משנה אותו.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
בשלח
א
תורה מבאר שלא היה הים נקרע עד שהתחילו בני ישראל לבוא במים. וקשה למה צריכים לזה, ומה עשה ביאת בני ישראל במים.
נראה לבאר שהענין היה שהיו בני ישראל צריכים לדרהר את המים כאילו כבר נקרע. וכיון שכן, ממילא יהיה נקרע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יש להוסיף שדורשים שים ראה ארונו של יוסף ואז נקרע. וקשה, מה ראה מארונו של יוסף. נראה שהכיר מארונו של יוסף מושג זה של חשיבות של הדרהר. וכיון שכן, הכיר שמוכרח הוא לקרוע על פי דרהר של בני ישראל.
ב
כשבני ישראל היו צועקים בים, משה אמר להם, ”אל תיראו, התיצבו וראו את ישועת ה’.“ וקשה, שלכאורה משה היה נותן ציווים לבני ישראל כשאמר להם שלא ליראות וכדומה. ואז קשה מה אמר להם לראות את ישועת ה’. איזה ציווי נמסר בדברים האלו.
נראה שמשה היה מסביר להם איך לגרום את הישועה. אם יראו את הישועה - דהיינו, שיחשבו שהוא כבר בא - אז יהיה ישועה. מה שאדם חושב יש בו כוח גדול. אם אדם חושב על עצמו שהוא ראוי לישועה, ואדם חושב על משה שיגרום את הישועה, וכהנה וכהנה, יהיה נכון, ויבוא הישועה.
רואים מכאן חשיבות של מחשבה על חברים ועל עצמינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יתרו
א
אחד מן עשרת הדברות הוא שלא לגנוב את הנפש. כל מה שהוא בתוך עשרת הדברות הוא או דבר שהוא מיסודי יהדות, כמו עבודה זרה, או דבר שהוא מיסוד היותינו לעם, כמו רציחה (שאי אפשר להיות עם שכל אחד רוצח מי שירצה). אך קשה למה גניבת נפש הוא אחד מן עשרת הדברות, שלא נראה שהוא דבר כל כך חשוב ודבר כל כך יסודי כמו שאר הדברות. ולכן היה לו להיות מצוה, אבל לא להיות חלק מן עשרת הדברות החשובות.
נראה שאין האיסור רק במה שעושה חבירו הישראל להיות עבד; אלא, באמת, האיסור הוא במה שרואה כל אחד ואחד וחושב אם יוכל לגנוב אותו. זה גורם שחושב על כל אחד ואחד להיות עבד. וכיון שחושב על כל אחד להיות עבד, אותו אדם קצת מורגש, ואף הוא מתחיל להיות קצת כמו עבד. זהו סיבה ויסוד של איסור גניבת נפש.
לכן, זה צריך להיות מתוך עשרת הדברות, שהוא דבר חמור מאד, ושהוא דבר ששייך להזיק בו כל כך כמה בני אדם. ורואים יסוד זה מיוסף:
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו הוא חשוב מאד. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
ב
חז“ל אומרים שכשה’ נתן את התורה לבני ישראל, כפה עליהם את ההר כגיגית, ואמר להם שחייבים לקבל את התורה, ואם לא יקבלו אותו, שם תהא קבורה שלהם. לכאורה, ענין של הר כגיגית היה שהוא דבר גדול, ותחתיו היו נקברים. אבל, קשה למה נקט גיגית. היה לו לנקוט דבר יותר רגיל, כמו אבן או כדומה וכנראה שאין סיבה שיאמר כן בגיגית.
נראה שההסבר אינו שיתן אותו על גביהם וימית אותם ויקבר אותם. אלא שיתן אותם בתוך חלל שלו כדי שבכל צד הם יהיו מכוסים בגיגית. מה היתה הכוונה בזה?
בדרך כלל, אדם רוצה להיות טוב. אז, יש לשאול למה רוב בני אדם אינם טובים כמו שירצו. ההסבר הוא שבני אדם חושבים על חבריהם להיות רעים. מחשבה זו גורמת שחבריהם חושבים על עצמם להיות רעים, וממילא נעשים רעים. אז, בגלל מחשבות של כל אחד על חברו, כל העולם חוטאים.
זה היה כוונת ה’ בנתינת גיגית. נתן אותו על בני ישראל, ואמר להם שרק באופן כזה אתם יכולים להיות טובים. ואיך אדם מבדיל את עצמו מבני אדם רעים שיחשבו עליו מחשבה שיזיק אותו, הוא על ידי התורה. התורה מבדיל בין הרשעים ובין הצדיקים, ואז אמר להם ה’: כדי להיות לעולם שרוי באופן כזה, שאתם יכולים להיות טוב בלי מחשבה מחברים שלכם, צריכים לקבל את התורה. ואם לא תקבלו את התורה, אמר ה’, שם תהא - תהיה בין העמים - והוא קבורתכם, שיגרום לכם מיתה וגיהנם.
רואים מכאן יסוד נפלא. רואים מזה שאף שאדם רוצה להיות טוב, מה שאחרים חושבים עליו ממש משנה אותו, ועושה שהוא מאד קשה לו להיות טוב. אז, מאד חשוב על כל אחד ממנו לחשוב רק טוב על חברים שלנו, ומאד חשוב לכל אחד ממנו שלא לדבר עם מי שלא יחשוב טוב עלינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
ידוע שהיו שני לוחות - אחת של מצוות בין אדם לחבירו ואחת של מצוות בין אדם למקום. לכאורה קשה למה מצות כיבוד אב ואם היתה על הלוח של מצוות בין אדם למקום, שהוא לכאורה מצווה שבין אדם לחבירו.
נראה להסביר שחלק מן הסיבה לכיבוד אב ואם הוא בין אדם למקום, ולא בין אדם לחבירו, והסיבה היא ככה: כשאדם מכבד את אביו ואת אמו, מתחיל ההורים לחשוב עליו להיות טוב, ולהיות ירא ה’, ואיש תם. וכיון שאב ואם חושבים על בניהם תמיד, ומראים אותו מחשבה, הבן יכיר מאד בכוונה זו. ובשביל כל מה שאדם חושב על חברו משנה איך חברו חושב על עצמו, וכל מה שאדם חושב על עצמו משנה באופן מאד חשוב מי הוא, כשיכיר בן אדם שהורים שלו חשובים עליו לטוב, יהיה יותר טוב. אז, נמצא שכיבוד אב ואם משפר אדם, ועושה שהוא יותר עליל לעשות מצוות. נמצא שיש ענין של בין אדם למקום בכיבוד אב ואם.
מצאנו שמחשבת אדם על עצמו - ומחשבת אדם על חבירו - הוא קובעת חשובה בענין מי יהיה אותו האדם. ולכן צריכים לשמור על המחשבות שחושבים על עצמינו ועל חברינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ד
רש"י מבאר שכשבני ישראל באו להר סיני, היו כאיש אחד בלב אחד. צריך ביאור מהו כוונת ”כאיש אחד בלב אחד,“ וגם למה נזכר כאן. משמע שהוא נצרך כדי לקבל את התורה; אבל צריך ביאור למה הוא כל כך חשוב עד שצריכים אותו כדי לקבל את התורה.
נראה שיש לציין לגמרא בכתובות. הגמרא שם דורש שמילת שוחד נחלק ל"שהוא חד", והוא שנעשה הנותן והמקבל אחד. וכיון שאין אדם רואה חובה לעצמו, יהיה הדין בטעות, שלא יכול לחייב את הנותן.
בביאור ”שהוא חד,“ רש"י כתב שהם בלב אחד. נראה שרש"י, כשאומר גבי קבלת התורה שהיו כאיש אחד בלב אחד, הולך לשיטתו, וסובר ש"בלב אחד" הוא אותו אחד של שוחד, דהיינו שאין אחד רואה חוב לעצמו.
אז, נראה לומר שכדי לקבל את התורה צריכים שכל אחד לא רואה חוב בחברו, שאם רואה חוב בחברו, יחשוב על חברו לרע, וחברו יחשוב על עצמו לרע, ויהיה רע. לא יכול תורה לקיים בזה, וזה הטעם שצריכים שיהיו כאיש אחד בלב אחד.
רואים מזה כמה חשוב הוא לחשוב רע על חברו, שעל זה כל התורה עומדת, ובלי זה אי אפשר לקבלת התורה באופן גמורה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
משפטים
א
קשה למה עבד עברי הוא הדבר ראשון שבפרשת משפטים. פרשת משפטים כולל כמה דינים יסודיים, ואז קשה למה מתחילים בזה.
עוד קשה מי יקנה עבד עברי. נותן הרבה ממון כדי שיקנה עבד שהוא גנב. צריך לומר שחושב שהוא צדיק גדול, שכל יהודי צדיק גדול, כמו שאמר הגאון האדמו"ר מניקולזבערג. יוצא מזה, לכאורה, שכל ענין של עבד עברי הוא שיהיה משעובד לזמן זה למי שרואה אותו לצדיק. וכיון שהוא משעובד למי שחושב עליו כן, אף הוא יחשוב על עצמו כן, ואף הוא יהיה כן ויעשה תשובה.
לומדים מעבד עברי יסוד חשוב - יסוד שהוא כל כך חשוב שאז צריך להתחיל פרשת משפטים היסודי בו - שמה שאדם חושב על חברו הוא דבר חשוב וגדול.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
קשה למה פרשת שקלים הרבה פעמים נקרה בפרשת משפטים, ולא בפרשת שמדברים בענייני תרומה. הרי לכאורה אינו נוגע לפרשת משפטים כלל.
שקלים הם כפרה למכירת יוסף. השבטים מכרו את יוסף כיון שחשבו שהיה רשע. הם לא הכירו שהיה צדיק, כיון שראו אותו לרע. זה היה רעה גדולה - ואולי מחמת זה כמעט נעשה רשע. אבל, יעקב לא עשה כן: הוא שמר את הדבר, שמר את בנו, וחשב עליו לצדיק.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
לעיל בארנו למה פרשת משפטים מתחיל ביסוד זה. אז, נמצא שיסוד זה הוא שייך מאד לפרשה זו. אז, באמת, מה הוא מקומו יותר מכאן.
ג
כששור הורג את האדם, הדין הוא שהורגים את השור. צריכים להסביר למה השור צריך להמית. אותו שור לא בוחר, ואינו רשע ואז קשה למה מת באותו הריגה.
נראה שקשה איך יהיה שאדם לא שומר את שורו כראוי. הרי, שור הוא בהמה חזקה, וידוע שקל הוא לו להרוג בני אדם. אז, איך אפשר שמי שהוא יפשע על שמירתו ולא ישמור אותו כראוי.
אלא צריך לומר שחושב ככה: אני ראוי לשבת בחירות, ואני ראוי להיות בעל בחירה. וגם לבהמה שלי ראוי שיהיה בחירה ויהיה חירות. איזה רע יש בחופש קצת לשור? למה אני יכול להיות אדון על השור שלי? למה אני יותר טוב ממנו? וכיון שחושב כך, לא שמר את השור כראוי.
לכן, אנחנו סוקלים את השור, להראות לו: הרי השור מת והוא לא בחר למות. זה מראה שהוא חלוק ממך, שלא צריך שום בחירה כדי שנהרוג אותו. אז, מתחיל לחשוב על עצמו שאינו כבהמה, ויחשוב שיש חילוק גדול בינו לבין בהמה, וראוי ונכון הוא שחופש של בהמות שלו יתלו בו, שהוא חשוב. וכיון שכן, ישמור את שווריו האחרים כראוי.
נמצא שמה שאדם חושב על עצמו להיות חלוק מבהמה יעשה שינוי גדול בו, ויתחיל לשמור כראוי, ולקיים מצוות בוראו כראוי. רואים מכאן שאיך שאדם חושב על עצמו הוא מאד חשוב, וממש משנה את מי הוא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ד
הפסוק אומר שאם עבד רוצה להישאר עבר לאחר זמן עבדות, יכול להיות נרצע, ובזה נשאר עבד. וזה קשה, שאין עבד אחר נעשה עבד על ידי זה, ומה נשתנה נרצע שברציעתו נעשה עבד.
עוד קשה למה אדם ירצה להישאר כעבד. למה יסכים להיות עבד כשיכול להיות בן חורין?
צריך לומר שהוא מפני שחושב על עצמו כבר להיות עבד, ומפני זה חושב שראוי לו להישאר בעבדותו. אדם כזה הוא, באמת, עבד אמיתי. לכן, בו לא קשה שיהיה עבד ברציעה, אף שהוא לא עושה עבד בדרך כלל - שהוא, כבר, עבד בפנים.
רואים מכאן שמה שאדם חושב על עצמו משנה מי הוא, ואף לענין נפקא מינא בדין. ולכן, צריכים אנו לשמור על עצמינו רק לחשוב דברים טובים על עצמינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
תרומה
א
על הארון היו שני כרובים. חז"ל מפרשים שהיו פני הכרובים כפני תינוקות. גם מפרש גמרא שהכרובים היו דוגמאות לאהבת ה’ את בני ישראל. צריך לבאר למה ילדים הם דוגמאות טובות לזה.
נראה שהענין הוא שהיה ה’ מראה לבני ישראל למה אהב אותם, והראה כן על ידי נערים. נערים הם קטנים שלעולם משנים. אין חושבים דבר קבוע על עצמם כבר, ולכן, יכולים להיות כל דבר. מה שאדם חושב על עצמו הוא הקובע מי הוא; אם אין אדם ממעט את עצמו, כמו שקטן לא ממעט את עצמו, יוכל להיות כל דבר טוב. אז, אמר ה’ שאוהב בני ישראל מפני יכולתם שלא למעט את עצמם על ידי מחשבה על עצמם, כמו שאומר קרא, "נער ישראל ואהבו."
לכן צוה ה' לעשות כרובים עם פני ילדים - שהוצרך ה’ להראות את זה לישראל, כדי שיבינו שהם כנער, והם יבינו לחשוב רק טוב על עצמם, ולא למעט את עצמם ולחשוב רע על עצמם.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
מה ראה יעקב ביוסף? רק זכר אותו כשהיה נער, קודם שהיה לו זקן. אז, ראה אותו לנער. כיון שהכיר כן יוסף, וראה את עצמו כן, אף הוא היה יכול לשנות אתה דרהר של עצמו על עצמו, והיה יכול למנוע אותו מחטא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
קשה למה היה ארון רק מצופה זהב. לכאורה, היה הכלי הכי קדוש והיה לו להיות זהב בעצמו.
נראה שבא לבאר איך אדם יכול להיות קדוש. לפעמים, אדם מכיר שתוכו עץ - תוכו לא זהב. אבל, הארון מראה לנו שאם אתה יכול להראות לעצמך שאתה זהב, ואתה יכול להראות לחברים שלך שאתה זהב - דהיינו, מצופה מבית ומחוץ - אז, גם אתה יכול להיות זהב. מפני שיחשבו חברים עליו לזהב, והוא יחשוב על עצמו לזהב, הוא יהיה זהב, ויהיה קדוש.
נמצא שמה שאדם חושב על חברו ומה שאדם חושב על עצמו הוא מאד חשוב.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
תצוה
א
הפסוק אומר שזכה אהרן ללבוש את החשן כיון שראה את משה כשנבחר להיות המנהיג של כלל ישראל ושמח בלבו. צריכים לבאר היחס בין שני עניינים אלו.
לכאורה, קשה מאד הוא לשמוח על שמחה של חבירו. הדרך היותר קל נראה שהוא רק לחשוב על עצמו כאילו הוא חבירו. אז, בשום דרגא נעשה מיוחס לחבירו, וממילא נתייחס אל חבירו והשמחה הוא שלו.
נראה, שרק מי שנוהג כן יכול ללבוש אורים ותומים. כדי להכיר בתשובה מאורים ותומים, צריך להבין שאלת השואל ממש. לכן, היה צריך לראות את עצמו כאילו היה השואל. אז, היה צריך להיות מי שמכיר ביסוד חשוב זה, והוא שאיך שרואה את עצמו עושה מה שהוא עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
הכהנים היו צריכים לעבוד בבגדים מיוחדים. אם עבדו בלי אותם בגדים, העבודה היה פסולה, והם נתחייבים מיתה. צריכים לבאר מה כל כך חשוב בבגדים אלו עד שכל כך צריך מאד ללבוש אותם.
נראה שההסבר הוא שצריך כהן להכיר בשעת עבודה שהוא חשוב והוא קדוש. כדי שיחשוב כן, נותנים לו בגדים חלוקים, שהם יגידו לו תמיד - אתה חלוק; אתה לא כאיש רגיל, ואתה קדוש!
רואים מזה שמה שאדם חושב על עצמו הוא מאד חשוב, וממש יכול לקדש אותו בדרגה שמנשא קרבן שמקריב.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
בתוך חושן היה אורים ותומים. נותנים אותו ממש בתוך החושן, שחלק מן החושן הוא לפניו וחלק מן החושן היה לאחריו, והיה כפול על האורים ותומים. צריכים להסביר מה זה מלמד לנו.
נראה שההסבר הוא ככה: אדם תמיד רוצה להיות טוב, וקשה להבין למה לא יכול להיות טוב לעולם. נראה שהביאור הוא שיש הרבה דרהרים שבאים עליו מחוץ, וזה מבלבל אותו, שזה חושב עליו כך, וזה חושב עליו כך. אז, התורה מלמד לנו שאם אדם רוצה להיות טוב, צריך להסתיר את עצמו מן החוץ, כדי שלא יפגע מחמת מחשבות אחרים עליו.
רואים מזה שמה שאחרים חושבים על אדם קובע מה יהיה האדם.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ד
כהן גדול היה לובש ציץ, והיה הציץ אומר ”קדוש לה’.“ יש לדון מה היה הענין של הציץ.
נראה שהוא שכהן גדול צריך להיות איש הכי קדוש שבישראל, וצריך לעבוד בקדושה נפלאה. לכן, יש לו ציץ, שכשכהן רואה ציץ שעליו כתיב "קדוש לה'", הוא חושב על ”קודש לה'.“ זה, ממילא, עושה שמדרהרים על כהן גדול להיות ”קדוש לה’.“ אז, כהן גדול נעשה יותר קודש לה’, שאף הוא מתחיל לחשוב כן על עצמו.
רואים מזה שאף כהן גדול, שנמנה מפני קדושתו, צריך מחשבה מאחרים כדי לקדש אותו. וגם רואים כמה חשוב הוא מחשבה שלנו על אחרים, שגורם שיחשבו על עצמם, ויהיו כמו שחושבים.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
כי תשא
א
צריך ביאור איך עבדו בני ישראל את העגל, שמיד אחר קבלת התורה חטאו חטא גדול כזה. בכלל לא היה מובן אף לנו, שבוודאי לא יותר קל לנו שלא לעבוד יצר הרע. ואם תאמר שעכשו נשחט יצר של עבודה זרה, יש לומר שבוודאי לא יותר קל עלינו. אז, צריך ביאור איך לא עמדו בו אבותינו.
גם צריכים לבאר איך יהיה שכשראו שמשה לא ירד, למה זה יעשה שיעבדו את העגל. נראה שהביאור הוא שחששו שמשה לא יתן להם את התורה, ויעכב אותו בשביל עצמו. אז, בדעתם, משה חשב עליהם להיות בני אדם שלא קבלו את התורה, ולא יקיימו את התורה. לכן, כן נעשו, ואז לא קבלו ולא קיימו את התורה.
רואים מכאן יסוד חשוב: כל מה שאדם חושב על חברו, ואף אם לא חשוב כן באמת, אלא חברו חושב שחושב כן עליו, נעשה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
ה’ אומר למשה שלא יכול לטעון בעד בני ישראל אחר העגל. הטעם לזה הוא שרק יש לו כוח כיון שהוא מלך והוא מנהיג את בני ישראל. אבל, כשבני ישראל כלים, אין לו כוח ואין לו שום חוזק. אבל קשה, שה’ ליבא בעי, ומה לו אם משה מנהיג או לא. לכאורה, חשיבות של משה בא ממה שהיה עבד ה’ וממה שהיה צדיק וירא שמים.
נראה שצריך לבאר שהיה לו יכולת לעלות ביראת ה’ במה שהיה מנהיג. היה מנהיג של בני אדם שהיו יראי שמים. כולם חשבו עליו - אתה תביא אותנו אל הטוב, ואתה תביא אותנו ליחס חזק לה’. זה גורם שהוא חשב על עצמו - אני מטרתי להביא בני ישראל לה’, ולהתקרב לה’.
אז, ה’ אמר שכיון שבני ישראל לא טובים, ולא חושבים שהוא עושה להם טוב, ששונאים את מה שעושה להם, כיון שלא טובים הם, ממילא הוא לא חושב על עצמו שמטרתו ככה. אז, לא היה לו אותו הכוח להגן בעד עם ישראל.
רואים מזה יסוד חשוב, והוא שמה שאדם חושב על עצמו - שבא ממה שאחרים חושבים עליו - משנה מי הוא, ויכול לעשות אותו יותר טוב, עד כדי שרק מחמת זה יהיה יכול לדבר עם ה’ ולווכח עם ה’, בדרגה של משה רבינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ויקהל
א
כתיב, ”ויעשו כל חכם לב.“ וזה קשה, שלא תלוי חכמה בלב, אלא במוח, כפי מה שידוע מגדולי חכמי האומות של זמנינו.
נראה לבאר שאכן, חכמה תלויה בלב. אף שחכמה יושב במוח, חכמה תלויה בלב, שמי שמדרהר את עצמו להיות חכם הוא חכם, ומי שמדרהר את עצמו לטיפש הוא טיפש. אדם מדרהר בתוך לבו, ולכן צריך מי שהוא חכם לב.
רואים מזה יסוד חשוב, והוא שמה שאדם חושב על עצמו הוא הגורם למה שהוא. זה יסוד נורא ואיום.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר שנשיאים הביאו את אבני מילואים. ידוע קושיית העולם, למה נקראו האבנים אבני מילואים. נראה לבאר את זה בצירוף ביאור למה הנשיאים בדווקא הביאו אותם.
ההסבר הוא שנקרא אבני מילואים כיון שלא רק היו נאים, אלא מילאו את מקום של הזהב. ובזה עשו שהזהב היה נראה יותר טוב.
לומדים מזה שהדבר הכי חשוב שאדם יכול לעשות הוא לגרום שאחרים יראו בטוב על אדם. הסיבה שזה כל כך חשוב הוא שמחשבות בני אדם על אדם הם מאד חשובים. הדרך שבני אדם חושבים על אחד משנה איך הוא חושב על עצמו, וזה משנה מה עושה. לכן, נקראו האבנים אבני מילואים, להורות חשיבות של עשיית ראיות טובות על חברנו.
לכן, נשיאים בדווקא הביאו אותם. הם היו המנהיגים של השבטים. מנהיג הוא מי שצריך לכוון את כל בני אדם שהוא מנהיג אל האמת, אל בני אדם הכי טובים שיכולים להיות. אז, לימוד זה היה מאד חשוב בעיניהם, שזהו הדרך להנהיג את השבט.
רואים מזה יסוד חשוב. רואים שצריכים לחשוב תמיד על אחרים לטוב. אם נחשוב עליהם לטוב, יהיו טובים, שיחשבו על עצמיהם לטוב, וממילא יעשו רק טוב ולא רע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
פקודי
א
פסוק אומר שמשה הקים את המשכן. ביארו חז"ל שאחרים נסו להעמיד את הקרשים, ולא היו יכולים. אבל משה היה יכול להעמיד אותם. צריכים לברר למה היה משה יכול להעמיד את הקרשים במקום שלא היו אחרים יכולים להעמיד אותם.
גמ' אומר שתורה מתשת כוחו של אדם. לכאורה, כיון שמשה היה לומד תורה מאד, היה לו להיות החלוש מכל. ואז קשה איך היה משה הכי גיבור, והאחד שהיה יכול להעמיד את הקרשים.
נראה לבאר שמשה היה מנהיג של בני ישראל. המנהיג צריך להבין שהדרך לעשות שבני אדם ימשכו אחריו הוא להיות חושב על עצמו למנהיג. אז, ממילא הוא יהיה המנהיג - יינתן לו אותם "קארקטירישטיק" שגורם שיהיה המנהיג שלהם.
לכן, כיון שהכיר בזה, היה חושב על עצמו להיות גיבור די להעמיד הקרשים. וכיון שחשב כן על עצמו, היה בו כוח ראוי והיה יכול להעמיד אותם. אבל, רק משה, שהיה מנהיג, הכיר בזה.
רואים יסוד חשוב. מה שאדם חושב על עצמו נותן לו כוח ויכולת להיות אותו דבר.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר שכסה ענן את המשכן, ולא היה משה יכול להכניס לשם. אבל קשה להבין את זה, שלא קשה בכלל ללכת לתוך הענין. ואז, למה לא היה משה יכול לבוא לתוך אהל מועד.
צריכים להבין איך אדם יכול להיות איש מושלם כמשה רבינו. הרי קשה הוא להיות ירא ה’ תמיד ורק לעשות מצוות תמיד. ולכן, צריכים לבאר איך השיג משה כן.
נראה שהביאור הוא שאדם צריך להבחין מי הוא - הוא איש חשוב שה’ אוהב ומחשיב. ואם חושב כן על עצמו, יכול להיות כמשה רבינו.
אז, נראה שהביאור על שאין יכולים לראות בתוך ענין הוא שמשה לא היה יכול לראות מה שסבר ה’ עליו. לכן, ממילא, לא היה יכול לדבר אל ה’, שלא היה ראוי אז.
רואים מזה יסוד חשוב. אף משה רבינו לא היה יכול להיות טוב כמו שהיה צריך בלי מחשבה על עצמו לטוב, ולא היה יכול לחשוב על עצמו לטוב כיון שלא היה מכיר באחרים שחושב עליו לטוב. כמה נצרך, אז, הוא לחשוב עלינו ועל חברינו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ויקרא
א
כתיב בקרא, "במקום אשר ישחט את העולה תשחט את החטאת." חז"ל פרשו שטעם לזה הוא כדי שלא יבינו בני אדם שמביא קרבן חטאת ולא קרבן עולה. אך קשה למה חוששים על הבושה של עבריין זה; אילו היה חושש לעצמו, לא היה חוטא, ולמה נחוש שאחרים יכירו שמביא חטאת.
נראה שחוששים שכיון שרואים אחרים אותו להיות חוטא, אף הוא בעצמו יחשב כן על עצמו. ובשביל זה, לא חוזר ממעשיו. וכיון שעיקר של קרבן הוא התשובה שמעורר, לא היה צורך לקרבן חטאת אילו היה במקום בפני עצמו. (אבל, בעבודה זרה, מסתמא ישוב אף בלי זה כיון שעבירה שלו היתה כל כך גדולה.)
רואים יסוד חשוב: מה שאדם חושב על חברו ממש משנה את חברו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ב
הפסוקים מבארים קרבן מנחות. כשאדם מביא מנחה, אומר קרא שמבלל אותו. מבאר גמרא שאין בילה מעכב, אבל אף שאין בילה מעכב, צריך להיות ראוי לבילה: כל הראוי לבילה, אין בילה מעכבת בו, וכל שאינו ראוי לבילה, בילה מעכבת בו.
העיר הגאון הרב הראש ישיבה שליט"א שמשמע שמה שמעכב אינו רק שאינו אפשר ליבלל, אלא הבילה עצמה. וקשה אז למה לא מעכב הבילה כשראוי לבילה.
נראה, שהפשט הוא שצריך בילה - בילה לעולם מעכב. אבל, כיון שהוא ראוי לבילה, יכולים אנו לחשוב עליו - והוא עצמו יכול לחשוב על עצמו - שהוא נבלל. אז, כיון שהוא ראוי לבילה, יש בו בילה ממילא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
ג
כשהפסוקים מתארים הציור של שבועת העדות, הוא אומר, "אדם כי יחטא ושמע קול אלה…." וזה קשה, שלא חטא ושוב שמע קול אלה וכדומה, אלא בזה גופא חטא. אז, סדר המילים שבפסוק הוא מוזר מאד.
נראה שהביאור הוא שבאמת חטא ושוב שמע קול אלה וחטא עוד; הפסוק מסביר שהדרך שחטא הוא שחטא פעם אחת, ושוב יחטא עוד. ולמה יהיה כן? נראה שהדרך לבאר כן הוא על ידי עוד קושיה.
נכון הוא שחטא עוד פעם, אבל למה הוא הוזכר כאן? הרי כאן מדברים על חטא השני שלו, ולמה בא חטא הראשון לכלל?
אלא, ההסבר צריך להיות שמדברים על מי שחטא ולא יכול לשכוח את זה. כיון שהוא חטא, הוא תמיד חושב על עצמו להיות איש החוטא. על איש כזה אומר פסוק שמפני זה כיון שחטא יחטא עוד. כיון שהוא חושב על עצמו לחוטא, יחטא עוד, שזהו מה שחוטא עושה - הוא חוטא עוד ועוד.
רואים מזה כמה חשוב הוא לשמור לחשוב על עצמינו רק לטוב ולא לרע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
צו
א
אם אדם מחשב מחשבת שלא לשמו או שלא לזמנו על בשר קרבן בשעת זריקה, הרי אותו קרבן נעשה פיגול. צריך לבאר למה נפסל פיגול. לא עשה בו שום פסול, אלא רק חשב עליו. אז, קשה למה נפסל.
נראה לבאר שכיון שחשב עליו פסול, יש בו מקצת מאותו פסול. זה מפני היסוד שחדשנו כמה וכמה פעמים, שמה שאדם מחשב על דבר עושה מה שהוא אותו דבר.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
פסוק אומר, “זאת התורה לעולה….” וצריכים לבאר מילים מיותרים אלו, שכנראה אין בהם שום תכלית.
נראה שהביאור הוא שהדרך לקיים כל התורה מיוסד על מוסר שלומדים מעולה. הרי, יודעים שבעולה, צריך לחשוב על עצמו כאילו הוא הנקרב. הענין הוא שמה שקורה לקרבן הוא שהולך כל כולו לה’. אף מה שלא נראה כל כך שהולך לה’, כמו מה שנאכל בקרבן שממנו הולך לכהנים, הוא הולך לה’, שכהנים משולחן גבוה זכים בו.
והמביא קרבן צריך לחשוב גם על עצמו כן: כל מה שיעשה, אף מה שלא נראה שהוא לצורך ה’ כמו אכילה ושתיה, צריך להיות לצורך ה.’ וכיון שחושב על עצמו כן - שהוא רק חי לה’, ושצריך לכוון את מעשיו לה’ - כיון שיראה את עצמו כקרבן, יוכל לקיים את כל התורה כולה, ולשמש את ה’ כראוי.
רואים מזה יסוד חשוב בענין עבודת ה’. הדרך להיות עבד ראוי לה’ הוא לחשוב על עצמו כמו קרבן לה’, שכל מעשיו מוכרחים להיות לה’.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
שמיני
א
בפרשה זו, מתו נדב ואביהוא. צריכים לבאר איך זה קרה לבני אהרן, ולמה מתו באופן שמתו. גם צריכים לבאר למה נסמך מה כשר לאכול לפרשת מיתת בני אהרן. וגם צריכים לבאר למה לא הוזכר בהמות טהורות בפרשת שמיני, ורק בפרשת ראה.
נראה שמתו בני אהרן כיון שחשבו על עצמם להיות קדושים יותר ממה שהם ראויים. מה שאדם חושב על עצמו משנה את עצמו. אז, נתנו בעצמם אותו קדושה. אבל לא היו יכולים לסבול אותו קדושה, ובשביל זה מתו. לכן, נשרפו נשמתם ולא עורם, שהרי לא היתה סיבת מיתתם גשמי, שבא מיחסם הגדולה עם הרוחני, ועם הקדושה היתירה שחשבו על עצמם.
ונראה שלכן נכתב פרשיות אכילה כאן. לא בא לאסור לאכול, אלא בא להתיר את השאר. התורה אומרת לנו שלא לחשוב על עצמינו להיות כל כך קדושים וטהורים עד שלא נוכל לאכול שום אחד מאלו, שזה רע: אם יחשוב כן על עצמו, יעשה את עצמו קדוש כזה, ואם אינו ראוי לאותו קדושה, ימות. אלא, רק מאלו לא יאכל.
לכן לא מנה בהמות כשרות. בבהמות, אין כל כך טהורים. אז, לא מונה אותם, שלא מחדש כל כך. אבל בעופות וכדומה, בא לומר שכל שאר עופות כשרים. אז, מחדש הרבה בענין מה שלא לחשוב עליו, שיש הרבה שלא ימנע את עצמו מלאכול.
מזה רואים יסוד חשוב: מה שאדם חושב על עצמו משנה את עצמו. צריך לחוש שמה שיחשוב על עצמו לא יהיה דבר שהוא רע לו, אף אם הוא דבר קדוש, אם אינו יכול לישא אותו דבר.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק מזכיר שחזיר טמא, אף שיש בו סימן אחד. וקשה, שכבר אמר שצריך שני סימנים, ואין שום דיני טהרה בגמל, וכדומה, אף שיש בו סימן אחד. אז, קשה מהו ההוא אמינא שלא יהיה דין חזיר שווה לשאר בהמות.
נראה שהביאור מיוסד על מה שאמרו חכמינו שחזיר יש לו רגלים כבהמה כשרה. וכיון שכן, מראה את עצמו כבהמה כשרה.
ידוע שהדרך שחושבים על דבר קובע מהו הדבר הזה, כמו שנבאר. אז, היה הוא אמינא לומר שכיון שכולם חושבים על חזיר להיות כשר, שכן נראה, יהיה קצת כשר.
רואים מזה יסוד חשוב: הדרך שחושבים על דבר משנה את הדבר. וכל שכן הוא גבי אדם. אם חושבים עליו להיות איש כשר, כן יהיה, ואם חושבים עליו להיות איש טמא, יהיה כן. אם לא כן, לא היינו צריכים פסוק מיוחד כאן. זה מוסר מאד חשוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
תזריע
א
אומר קרא שצריך מצורע להכריז, ”טמא טמא.“ צריך ביאור למה הצריכה תורה שיכריז את זה. איך זה עושה דבר טוב למצורע.
נראה שצריכים להבין יסוד של צרעת. צרעת הוא בא על לשון הרע. אז, צריכים לבאר יסוד של עבירה גדולה גבורה מופלאת איומה נוראה טמאה ומשוקצת זו. נראה שיסודו הוא שאדם חושב על עצמו שהוא יותר טוב מאחרים. אז, אף שהם יהיו בצער כשהוא מדבר אליהם, הרי מה איכפת לו אם אחר יהיה שרוי בצער.
התיקון לחטא גדול גבור מופלא זה הוא שיחשוב על עצמו להיות רע ומשוקץ וטמא. אבל איך יעשה כן. הלא טבע האדם הוא שחושב טוב על עצמו.
לעשות כן, צריך לסמוך על יסוד שכתבנו. צריך לשמוע אל עצתינו. אם אחרים שומעים שהוא טמא, אז יחשבו עליו להיות טמא - ולא רק טמא, אלא גרוע ומשוקץ. וכיון שהם חושבים כן על עצמו, אף הוא יחשוב כן על עצמו. זה יעשה שהוא יהיה בדעתו לאיש שאינו כל כך מופלא על חבריו, וזה יעשה שהוא עניו.
נמצא שסומך על יסוד שבארנו, והוא שמה שאדם חושב על חברו עושה מה שחברו חושב על עצמו. זה יכול לעשות מי שהוא חברו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
פסוק אומר, "אדם כי יהיה בעור בשרו…." לשון זה מוזר מאד. היה לו לומר, "כי יהיה בעור אדם…," ולא "אדם כי יהיה בעור בשרו."
נראה שהביאור הוא שיכולים לקרוא שהאדם הוא הנגע - כי יהיה האדם בעצמו נגע בעור בשרו.
בא הפסוק לבאר למה צרעת בא לאדם. איך אפשר שאדם יעשה כל עבירות אלו ויגרום צרעת לעצמו. לזה, אומר שהוא רק מפני שחושב על עצמו לנגע. חושב שהוא רק דבר המטמא, ואינו דבר טוב. לכן, לא עושה טוב.
רואים מזה כמה חשוב הוא שלא לחשוב על עצמינו על עצמינו לרע, שזה גורם שנעשה עבירות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
מצורע
א
מצורע נטהר על ידי כמה דברים: על ידי ארז אזוב ושני תולעת. יש כמה מפלפלים שמצפצפים בענין האזוב והארז. אנו לא באנו לצפצף, אלא לדון בעמקה של תורה, ואמיתה של הפשט. אז, נדון בסייעתא דשמיא בשני תולעת; צריך ביאור מהו ענין של השני תולעת.
נראה לבאר שמצאנו שתולעת שני - שהוא אותו דבר של שני תולעת - הוא אחד מן הדברים ששמשו בו במשכן ובבגדי כהונה. נראה שהיסוד הוא שבגדי כהונה הוא דברים שעושים שאדם יקרב אל קונו. אבל לשון הרע, שגורם צרעת, אינו כן, אלא עושה שאדם ירחק ממנו.
אבל, מצורע משמש בו, אף שעשה מעשה רע. נראה שהוא מפני שכיון שעוסק בדבר שמיחס אותו אל קונו, ממילא הוא חושב כן על עצמו, וחושב שאף הוא ייחס לקונו. וזה משנה אותו, ועושה לו יחס לקונו.
נמצא יסוד: אדם נעשה מה שחושב על עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
כל עסק מצורע נעשים על ידי כהן: צריך שכהן יראה הצרעת, וצריך שכהן יעשה עבודה כדי לטהר אותו. אבל צריך ביאור למה זה כן, ולמה צריך כהן.
נראה לבאר על פי דיוק אחר. תמיד קורא לאיש המיטהר ולכהן המטהר. מילים אלו הם מאד קרובים, וזה מבלבל את המוח. וקשה למה לא רק נקרא לו המצורע, ולא יהיה קשה להבין.
נראה שההסבר הוא שהדרך שמצורע יטהר הוא שיראה מעשי כהן אחד, איך שהוא פוסק ודואג עליו, וכמה טוב הוא. שוב יכיר שאף הוא יכול להיות כן - הוא מאד קרוב להיות כהן, והוא דומה לו. כיון שהוא חושב כן על עצמו, יכול להיות נטהר.
לכן, כל העבודה צריך להיות עם כהן, ולכן מדמה אותם בתשמיש מילים דומים.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
אחרי מות
א
כתיב, ”בחוקותיהם לא תלכו.“ צריך ביאור למה הוא כל כך רע ללכת בחוקות הגויים.
נראה שהרע אינו ההליכה בחוקות שלהם. אלא, הרע הוא מה שקורה מחמת זה. כשהולך בחוקות הגויים, הרי הוא חושב על עצמו כגוי. זה גורם שהוא כמעט כגוי, והוא נהפך לגוי, על פי הכלל הידוע שמה שחשוב אדם על עצמו משנה מי הוא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק מזכיר שאם צריכים כהן גדול חדש, או מושחים כהן גדול או ממלאים את ידי כהן גדול אחר על ידי לבישת בגדי כהן גדול. צריך ביאור איך לבישת הבגדים עושה אותו כהן גדול.
נראה שהענין הוא על פי מה שכתב חכם אחד, והוא ש"בגדים עושה את האדם; בני אדם ערומים לא עושים כלום." הביאור הוא שכיון שלובש בגדי כהן גדול, יכול לחשוב על עצמו ככהן גדול. וכיון שיכול לחשוב על עצמו כן, יכול להיות כן; כיון שעומד להיות ככה"ג, נתקדש ונעשה כה"ג. אז, הדרך שחושב על עצמו הביא כל קדושה זו.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
קדושים
א
אומר קרא, "ואהבת לרעך כמוך." צריך לבאר מה בכלל מצווה זה. נראה לבאר שאין המצווה רק לאהוב את חברך כעצמך; אין זה שייך, שאין אדם יכול לאהוב את אחר כעצמו ממש. אלא נראה שהדרך לקרוא פסוק זה הוא שאומר שצריך לאהוב את חברך - ואיך עושה כן? כמוך! תחשב עליו כמו שאתה חושב על עצמך. כמו שאדם חושב על עצמו ומכסה פשעיו, כך תחשב על חברו. ואיזה אהבה יש בזה? יש אהבה גדולה בזה, שכשאדם חושב עליו לטוב, יחשב חברו על עצמו יותר לטוב. כיון שחושב על עצמו לטוב, יהיה יותר טוב.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו הוא חשוב מאד. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
ב
הפסוק אומר שלא לעשות אונאת דברים לגר, וממשיך לומר שהוא מפני ש"גרים הייתם בארץ מצרים." הפשטות הוא שטוען שאינו ראוי לך להלעיג על גר, כיון שאתה אינו יותר טוב ממנו. אבל, זה קשה מאד, שה' בחר בנו, וה' הוציא אותנו, וטהר אותנו, ונתן לנו את התורה. ה' לא עשה כן לאותו גר. אז, קשה מהו המשך של הפסוקים.
נראה לבאר על פי מה שכתבו חז"ל בביאור מה יאמר לגוי לאונאת דברים. לא רק אומר לו, "אתה כושי," אלא, מבארים חז"ל, אומר לו, "אתה לא ראוי לעשות מצוות, שכבר עשית הרבה עבירות." מה הבעיה בזה? נבאר לקמן.
הרי כשיוסף היה בבית פוטיפר, כמעט עבר עבירה. רק היה ניצול כיון שראה דמות דיוקנו של אביו. העולם חושבים שראה דמות של אביו. אבל זה לא נכון. הפשט אינו כן, אלא הפשט הוא שראה את דמות דיוקנו שלו - של אביו; ראה תמונה של יוסף בעיני אביו, שראה איך אביו חשב עליו. כיון שהכיר שאבא שלו הכיר אותו לצדיק, לא היה יכול לחטוא.
אם אדם אומר לגר שהוא עבר הרבה עבירות, ואינו ראוי להיות גר, לא יהיה ראוי להיות גר, ויחטא עוד. לכן, הוא רע מאד לומר לו כן.
נראה שלזה מכוון כשאומר הפסוק שהיינו גרים בארץ מצרים. אנחנו היינו חלוקים מהם, לא היינו מעורבים בהם. ואיך? מפני מה שקרה ליוסף, שאנחנו חשבנו על עצמינו להיות עם חלוק מהם.
אז, פסוק אומר שלא לדבר כן לגרים, כי אתם יודעים כמה חשוב הוא לחשוב על עצמך ועל אחרים רק לטוב ולא לרע.
לומדים מזה יסוד גדול, והוא כמה חשוב הוא לחשוב על חברך ועל עצמך לטוב תמיד.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש עוד קושיה, והוא שחז"ל דרשו ממה שכתיב בפרשה שלנו ש"לא תפנו אל האלילים" שאסור להסתכל בדמות אדם. אז, קשה איך יוסף הסתכל בדמות יעקב.
יש לבאר שלא ראה, באמת, דמות - דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
ג
הפסוק אומר: "קדושים תהיו." כידוע, חולקים הרמב"ן והרש"י בביאור זה, אבל לשניהם יש קושיה פשוטה. הקושיה הוא למה לא אמר הציווי מה לעשות, ולמה רק אמר שתהיו קדושים. אילו הציווי אומר שלא להיות מנובל, היה לו לפסוק לומר: "אל תהיה מנובל ברשות התורה."
נראה שהביאור הוא שדברים אלו שמצווה הפסוק הם קשים מאד להשיג. לכן, הפסוק מורה לנו איך לעשות אותם, ובאמת, נותן ציווי של מה לעשות.
איך נשיג גדלות וקדושה הנזכרת בפסוק? קדושים תהיו! תחשבו על עצמכם כאילו אתם קדושים. על ידי זה, אדם יהיה קדוש, כיון שמדרהר אותו להיות חשוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
אמור
א
במקלל את ה’, רש"י כתב שכשהפסוק אומר שהמקלל היה "בתוך בני ישראל," מלמד שנתגייר. אבל רמב"ן הקשה על רש"י שאמו היתה בת ישראל, ואביו היה גוי, ואז, היה ישראל כשר ולא צריך להתגייר. יש מתרצים שאולי קודם מתן תורה לא היה הדין כן. חזקוני פירש זה שהטעם שבן של ישראלית וגוי הולך אחר אמו ולא אחר אביו, כמו שרגיל, הוא מפני שהפקיר ה’ את זרע של גויים. אבל זה קרה רק בשעת מתן תורה. אז, במקלל הולכים אחר אביו, ודינו כגוי. הרמב"ן חולק, שסובר שהיה דין יהודי כבר לאבות. מביא ראיה מגמרא בקידושין שלא לומד דין גויים מעשו, כיון שהיה ישראל מומר. גם יש אומרים שלא ר"ל שממש נתגייר, אלא שבחר ללכת בדרך היהודים ולהיות יהודי.
ראשונים הקשו למה מזכיר מעשה זה כיון שהוא בזיון לה’. מתרצים שני תירוצים. האחד, שלשון הקרא מראה שחשב על שם ה’ ואז קלל אותו. מזה לומדים שכשאנו מברכים, צריכים לחשוב על שם ה’ קודם שמברכים. גם מתרצים שהיה אפשר לאדם להקשות איך פרשה כזה קורה. אז, בארו שקרה.
למה היה אותו בן גוי מקלל. מבארים שהוא מפני שהוא היה פסול ופגום, ולכן היה יכול לקרות שיקב ויקלל את שם ה’. אבל, אין הכי נמי, לשאר בני אדם, קשה להבין.
אבל קשה, שהרי הוא חשב על עצמו ליהודי, כמו שכתבנו לעיל, שהוא נתגייר, לפי פשט שני שכתבנו. אז, קשה איך יכול להיות שדבר רע בא מפגימתו כיון שלא חשב עליו כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יכולים לומר שהמקלל לא חשב על עצמו די כישראל גמור. זה גורם שכשאדם אחר מזכיר אותו, אומר שהיה בן אשה ישראלית, אבל גם אומר שהוא בן איש מצרי. וזה היה רק אם עדיין חשב על עצמו כזה. לכן היה גר, והיה כבני ישראל, אבל עדיין היה בן איש מצרי בדעתו.
יודעים שיש יסוד חשוב, שמה שאדם חושב על עצמו מהפך על עצמו. אבל, צריכים לדעת שזה רק מתקיים אם אדם חושב כן על עצמו ממש, בלי שום נטייה לרע. כמו שלא היה יכול לעשות אותו ישראל כשר בלי פגם על ידי מחשבה שלא חשב כראוי, שהיה נוטה להיות בן איש מצרי. כך אנו לא יכולים לכוון כן בלי מחשבה טובה ממש.
ב
הפסוק מונה כמה מומים שעושים שאדם לא יכול לעבוד בבית המקדש. קשה להבין איך מום יעשה שאדם לא כשר להקריב קרבן לה’. אטו מפני שבני אדם לא חושבים עליו לטוב - שחושבים על דברים מאוסים כשרואים אותו - זה סיבה שלא יוכל לעבוד?!
צריכים לומר שאכן זה סיבה שלא לעבוד. למה? כי איך שאדם חושבים על אדם - ודברים מאוסים שחושבים כשרואים אותו - משנים את האדם, שגורמים שאף הוא לא יחשוב טוב על עצמו.
רואים מזה כמה חשוב הוא לחשוב טוב על עצמינו תמיד.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
בהר
א
בכל זמן שהפסוק מזכיר אדם שנעשה מך, הוא אומר ”כי ימוך עמך.“ לשון זה מוזר, וקשה למה אומר שמך "עמך," ולא רק שנעשה מך.
נראה שקרא מסביר איך יכול להיות שאדם יהיה מך. מסתמא, כל אדם יכול לקנות ולמכור ולעבוד קרקע, וקשה למה יהיה מך.
נראה שההסבר הוא כך: מה שאדם חושב על חבירו גורם מה שחבירו חושב על עצמו. ומה שחבירו חושב על עצמו משנה אותו. אז, הדרך שאדם נעשה מך הוא שחושבים אחרים עליו שלא יכול להצליח בממון, ומוכרח להיות מך. אז, חושב על עצמו כן, ואז נעשה מך.
לכן, אומר "עמך,“ שאומר שנעשה מך מחמתך, שדרהרת עליו שיהיה מך.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
פרשת בהר מתחיל במעמד הר סיני, וממשיך לבאר דין של שנה שביעית. יש שמקשים למה סמכה שמיטה להר סיני.
נראה שהביאור תלוי בהבנה איך אדם יכול לשמור את שנת השמיטה. הרי, לא פשוט שלא לעבוד לשנה שלימה. אז, איך בני אדם מתגברים על עצמם לשבות בכל אותו השנה.
הביאור הוא שלא חושבים "האם אני אעשה מלאכה או לא?" אלא, יודעים מי הם - הם עבדי ה’. אז, אין ברירה, שכיון שה’ אמר שלא לעבוד, זהו - לא עובדים.
נמצא שיסוד של מצוות שמיטה, המוסר שלומדים ממנו, הוא שהדרך לשמור את התורה הוא לחשוב על עצמו להיות מי ששומר את התורה.
נראה שיסוד זה הוא יסוד מאד חשוב בקיום כל התורה כולה. לכן סמך אותו להר סיני, לומר שהדרך לקיים כל המצוות שניתנו על הר סיני הוא לחשוב על עצמינו כמקיימי המצוות.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
בחוקתי
א
כתיב בקרא, ”אם בחוקתי תלכו.“ מבאר רש"י שהכוונה בזה הוא ש"תהיו עמלים בתורה." לכאורה, לשון רש"י הוא פלאי פלאים. לא מובן כלל מהו ביאורו. צפצפו בזה הרבה, ולא העלו בידם כלום. צריך לבאר למה רש"י - עומק דברי רש"י אומר "שתיהו עמלים" ולא "שתעמלו בתורה."
נראה שהביאור ברש"י אינו שצריכים שיעמלו בתורה, אלא שצריכים לחשוב על עצמינו כעמלים בתורה. כיון שאנו נדרהר את עצמינו לעמלים בתורה, ממילא כן נהיה, ונעסוק ונעמול בתורה.
רואים יסוד חשוב: כל מה שאדם חושב על עצמו עושה מי שהוא ותנועותיו והנהגותיו. אז, אם אדם חושב על עצמו להיות עמל בתורה, ממילא כן יהיה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
אחד מן ההבטחות שיבואו לבני ישראל אם ישמרו בקול ה’ וילכו בחוקותיו הוא שחרב לא יעבור בארצם. גמ’ מבאר שאף חרב של שלום לא יעבור בארץ שלהם. צריך ביאור למה זה ברכה, ולמה רוצים שחרב לא יעבור בארץ שלנו.
נראה שהביאור הוא שכל מי שעובר בארץ שלנו, אף אם לא בא להרוג אותנו, יראה בנו, ויש לחוש שלא יחשוב עלינו לטוב, אלא יחשוב שאנו רעים. מחשבה כזה יגרום שגם אנחנו נחשוב בעצמינו שאנו רעים. מחשבה כזה הוא דבר רע מאד, כי איך שאדם חושב על עצמו קובע מי הוא, ומה יעשה.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב. גם רואים שאיך שחברים שלנו חושבים עלינו משנה איך שאנו חושבים על עצמינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
במדבר
א
אומר ה’ למשה, ”שאו את ראש….“ אבל קשה, שהרי לא נשא רק את ראש כל בני ישראל, אלא נשא את כל הגוף שלהם.
נראה שצריך לבאר למה מנה אותם כלל. למה לנו לדעת כמה בני אדם היו, שהרי לא צריכים לדעת כן למלחמה, שהרי ה’ יודע, וה’ אמר שיצלח.
נראה שה’ רצה להראות כל אחד שהוא חשוב, לא רק אומרים שיש כמעט מנין זה, אלא מונים כל אחד להראות שהוא יחיד ומיוחד וחשוב.
לכן, נקרא כל אחד ראש - שכל אחד ראש, וכל אחד חשוב.
למה רוצים להחשיב את כל אחד? כיון שכשמחשבים את אחד, הוא מחשב את עצמו. וכשהוא מחשב את עצמו, הוא נעשה חשוב. אז, רצה ה’ לעשות כן. אז, על ידי גלגל החוזר הזה, באמת, כל בן ישראל הוא ראש, וכל בן ישראל הוא צדיק גדול.
רואים יסוד חשוב: מה שאדם חושב על חברו עושה חברו, ואם חושב עליו טוב, יעשה אותו טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
המנין של כמעט כל השבטים נגמר במאה, וכולם גומרים בעשר. צריך ביאור איך זה יכול להיות, ואיך לא היה אף באחד מהם שלא כזה. הביאור הוא שה’ עשה כן בדווקא. אבל, צריך לבאר למה רצה ה’ בזה.
נראה שהביאור הוא שכל אחד היה יכול לחשוב על עצמו שהוא חשוב ונצרך. בלי הוא, לא יהיה מנין שלם. הוא שינה את התשעים ותשע למאה, וזה דבר גדול.
והטעם שה’ רצה בזה הוא כיון שהוא דבר חשוב לחשוב על עצמו לטוב, זה עושה שאדם יעשה טוב.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ג
הפסוק מונה את הבכורים, ונגמר עם מאתים שבעים ושלש. קשה למה לא רק אומר את העשר הקרוב לזה, ולמנות באומד כאן (ראונ"ד בלע"ז).
נראה שהביאור הוא שבא לומר שכל אחד ואחד חשוב, ומנה את כולם.
רואים מזה יסוד חשוב: הוא נצרך מאד לחשוב על עצמינו לטוב, כיון שזה עושה אותנו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
נשא
א
אומר קרא בברכת כהנים ש"ישא ה’ פניו אליך וישם לך שלום." צריכים לבאר למה נתינת פניו של ה’ בנו גורם שלום.
נראה לבאר שאדם נפעל כפי דרהר שניתן עליו. אז, אם אדם חושב עליו להיות טוב, ממילא אותו אדם נעשה טוב.
נראה שנשיאת פנים של ה’ הוא שה’ נותן פניו בנו וחושב בנו. כיון שה’ אוהב אותנו, חושב עלינו להיות טוב. אז, ממילא נעשים טוב. כיון שאנו נעשים טוב, בהכרח יהיה שלום.
רואים יסוד זה, שמה שאדם נחשב בעיני חברו עושה מה שהוא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
פסוק אומר, "כי תשטה." גמרא מבאר שאין אדם חוטא אלא אם כן נכנס בו רוח שטות. צריך ביאור מה אנו יכולים לקחת מזה במוסר. הרי, כשאדם חוטא, איך עוזר לו לדעת שמה שרוצה לעשות הוא מפני שיש בו רוח שטות. הרי יודע שיש בו רוח שטות, אבל עדיין רוצה כן. להיפך, יחשוב שאולי זה לא כל כך רע כיון שלא הוא עושה אותו, אלא רוח שטות עושה כן.
במדרש אומר לשון קצת שונה, שהחוטא "יצא מדעתו." נראה שזה קצת שונה מהבנה שכתבנו, ועל פי זה נוכל לפרש את הגמרא.
נראה שאדם בדרך כלל חושב על עצמו להיות אדם טוב. אז, אם הוא חוטא, צריך לומר שיצא מדעתו - שיצא מדעת על עצמו. ורק בגלל זה חטא.
כמו כן הוא הפירוש של הבבלי. רק חוטא אם נעשה שוטה - שחושב על עצמו כשוטה ורשע.
מזה יכולים ללמוד הדרך להרחיק מעבירה. אם אדם תמיד חושב על עצמו לצדיק, ותמיד חושב על עצמו לטוב, לא יחטא.
רואים מזה יסוד בענין חשיבות מחשבה על עצמו לטוב: אם אדם תמיד יחשוב על עצמו לטוב, ולא יהיה בו רוח שטות לעולם, ולא ייצא אף פעם מדעתו, אז, רואים מכאן, לא יחטא. רואים שזה מאד חשוב לחשוב על עצמינו תדיר במחשבה ועין טובה כזה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
בהעלותך
א
בפרשה זה, מצאנו טענה מוזרת מאד. חייבה תורה את בני ישראל להביא קרבן פסח. טענו הטמאים לה’ "למה נגרע" - רצו להקריב קרבן פסח, והקשו לה’ למה יגרעו מלהביא אותו קרבן. לכאורה, טענה שלהם אינה מובנת. יגרעו כיון שהם טמאים, וקשה איך יטענו שאף הם יוכלו להביא אותם.
נראה שתחילה צריכים לחדש יסוד: כל מה שאדם חושב על עצמו משנה את עצמו. אם אדם חושב על עצמו שהוא טוב, הוא טוב. אם הוא חושב על עצמו שהוא רע, הוא רע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
אז, נראה לפרש שלא היו טוענים שיוכלו להביא, אבל היו מקשים שהיו מדרהרים על עצמם למקריבים של קרבן פסח. אז הקשו איך אפשר שלא יהיו באמת מקריבים של קרבן פסח, שהרי כן מדרהרים.
לזה ענה ה’ שבהכרח יש תשלומים, ובהכרח יש יום אחר להיות בו מקריב פסח, שהוא פסח שני.
ב
אומר תורה שאהרן ומרים היו טוענים על משה, והטענה הניח שהיה נביא כשאר נביאים. קרא אומר שה’ השיב ש"פה אל פה" דבר עם משה. חז"ל מבארים שמשה היה מדבר עם ה’ ורואה באספקלריא המאירה, אבל נביאים אחרים היו מדברים באספקלריא שאינה מאירה.
רש"י מפרש, וכן הוא הפשטות, שפשוטו של מקרא לעולם כרש"י, שכן ראה את ה’. אספקלריא המאירה הוא הדרגא שבו היה לו ראיית ה’. אבל, קשה לפרש את זה.
מפרשים במסכת כלים כתבו שאספקלריא הוא מראה שבו אדם יכול לראות את עצמו, והוא בלע"ז מירר. (כעין, "מירר מירר און די וואל, הוז די פיירסט אב דם אאל.")
נראה לפרש שאספקלריא הוא באמת מירר. המירר של משה היה מאיר יותר מאחרים, והיה יכול לראות את עצמו בדרך בהיר מאד. וכיון שהיה רואה את עצמו, ויהיה רואה שהיה חשוב, ממילא היה יותר חשוב, והיה נביא יותר גדול, והיה נבואתו יותר טובה.
זה היה החילוק הגדול בין משה לשאר נביאים. שאר נביאים לא היו יכולים לראות את עצמם כל כך כמשה ולא הבינו חשיבותם. ולכן הנביאות שלהם לא היתה כשל משה.
רואים חשיבות של יסוד זה במה שנביאות משה הוא אחד משלש עשרה עיקרים. צריך ביאור למה יהיה כל כך חשוב עד שהוא אחד מיג’ עיקרים. לכאורה, מוכרחים אנו לומר שעיקר של העיקר אינו מה שמשה היה עדיף, אלא מה שחשיבות שאדם רואה בעצמו הוא עושה את עצמו חשוב. אז, יסוד זה הוא יסוד חשוב ונצרך להאמין בו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
ג
הפסוק מזכיר שה' צוה למשה ואהרן לעשות תנופה על הלויים. כנראה, זה דבר מוזר (ובאמת, זה היה קצת מטענות קרח). הרי, תנופה היא על קרבנות, ולא על בני אדם. אז, קשה למה היה מניף את הלווים אם לא היה מקריב אותם לקרבן.
נראה לבאר שהענין הוא שכל לוי חייב לחשוב על עצמו לקרבן. ולכן עשו בו מעשי קרבן - כדי שיחשוב על עצמו שגם הוא קרבן.
לא קל להיות לוי. צריך לעבוד בעבודה קשה, ותמיד יש יראה ופחד שמא ימות. איך יכול אדם לזרז את עצמו ולעבוד בעבודה הקשה הזו. הפתרון הוא שיזכור את תנופתו. ה' צוה שיניפו את הלויים, ואז נמצא שה' חשב עליו כקרבן. כיון שיכיר שה' חשב עליו כן, אף הוא יחשוב על עצמו כן. וכיון שכן, קצת ייעשה כן, וכמו קרבן, יהיה קיים רק לרצון הבורא יתברך, ויכוף את רצון עצמו לרצון ה'.
רואים מזה יסוד חשוב. איך שאדם חושב על עצמו ממש משנה את הכוחות שלו. מה שמאד קשה ללוי לעשות נעשה אפשר רק על ידי שחושב על עצמו להיות קרבן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
שלח
א
אמרו המרגלים על הנפילים שהיו בארץ ישראל, "ונהי בעינינו כחגבים, וכן היינו בעיניהם." קשה איך ידעו מה היו בעיניהם. תמוה למה לא בארו חז”ל את זה. אבל, ברוך ה’, שמעתי משום גדול הדור אחד[fn:1] שתחילת הקרא מפרש סוף הקרא. כיון שהיו בעיניהם כחגבים, חשבו שכן היו בעיני מרגלים. מה שאדם חושב על עצמו חשוב הוא, שגורם איך יחשב על דברים אחרים וגם, על פיהם, איך ינהג.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
ב
ה' אומר למשה שיהרוג את כל בני ישראל ח"ו מפני עון המרגלים ויעשה את משה לעם גדול. הרי, כל עונשים של ה' הם מדה כנגד מדה. צריך לפרש באיזה אופן יהיה עונש זה מדה כנגד מדה.
נראה לפרש שכל בני ישראל חשבו על עצמם להיות בני אדם שלא חשובים כלום. הרי, חשבו, אינם כדאי שה' ינצח את יושבי ארץ כנען להם. אבל משה לא חשב כן. הוא ידע שהיה חשוב, והוא השאיר את אמונתו בעצמו.
לכן, ה' אמר שכל מי שלא חושב על עצמו להיות חשוב לא יהיה כלל, ומשה שידע שהוא חשוב, כיון שהוא חלק מן בני ישראל, יישאר, בעצמו, חשוב.
רואים מזה יסוד חשוב. אם אדם חושב על עצמו להיות חשוב, כן הוא, שהוא באמת חשוב, שמחשבתו יגרום את מעשים שלו. גם ההיפך נכון, ואם אדם חושב על עצמו שאינו חשוב, לא יהיה קל לו להיות, באמת, חשוב, כיון שחושב שאינו כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
קרח
א
אומר קרא שאחר מיתת קרח ומאתים וחמישים אנשיו, נטלו את המחתות מן החוטאים, ועשו אותם ציפוי למזבח. צריך לבאר מה הועילו בזה, ולמה ייקחו דבר שהיה חלק מחטא ויתנו אותם על מזבח.
נראה לפרש שרגיל אדם לראות את חברו ולחשוב שהוא חוטא והוא מושחת. אבל, זה רע מאד, שמה שחושב אדם על חברו משנה את חברו, ויעשה שחברו יחשב על עצמו להיות רע, וממילא ייעשה חברו רע. אז, צריך לחשוב עליו לטוב.
מחתות על המזבח נעשו מיר“ר. אז, הגדת המחתות היה לראות את עצמך בחברך. אילו היית כן, מסתמא, היית מוצא עליל לטובתך. אז, אף אתה תמצא עליל לחברך, כדי לחשוב עליו לטוב, וכדי שאף הוא יחשבו על עצמו לטוב, ואף הוא יהיה טוב.
רואים יסוד מזה: אם אדם חושב על חברו לרע, יהיה חברו רע, ואז צריך לחשוב עליו רק לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפרשה הזה מספר איך הקטורת הציל את בני ישראל מן המגיפה. צריכים לחפש איך אפשר שלקטורת יש כוח כזה.
נראה להסביר על פי מה שאמרו חז"ל שקטורת מכפרת על לשון הרע.
נראה לבאר שכל בני אדם הם, בעיקר, טוב. אבל, כיון שבני אדם, לפעמים, חושבים על אחרים לרע, אותם אחרים מתחילים לחשוב על עצמם לרע, וממילא הם נעשים רע. אבל, כל זה בא על ידי לשון הרע, שבלי לשון הרע, הכל יחשבו שהכל חושבים עליו לטוב.
ממילא מה שעשה קטורת הוא ששמר אותם מאיסור של לשון הרע. כיון שיבוא כפרה עליו, ממילא אין שטן מקטרג ומשטין בו. אז, כיון שאין לשון הרע, כולם עומדים להיות צדיקים גמורים, שאין סיבה להם לעבור על שום איסור ולהיות רשעים כמו שאמרנו. לכן, מבואר למה קטורת מצלת מן המגיפה.
רואים מזה יסוד חשוב. מה שבני אדם חושבים על אחד אחד לטוב או לרע משנה מי הוא אותו אחד, אם הוא טוב או רע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד: הכל תלוי באיך אדם חושב על עצמו. חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר, כיוסף.
חקת
א
כל בני ישראל אבלו את אהרן לשלשים יום. קשה למה היו כל כך אבלים במיתת אהרן. לא מצאנו אחר שהיה לו אבילות כל כך כזה.
מצאנו את התשובה בדברי חז"ל שאמרו שהיה אהרן אוהב את הכל, ומכבד את הכל. כיון שהיה מכבד את אדם, היה חושב לעצמו: ”אכן אני חשוב שאהרן מכבד אותי. אז, איך אחטא?“
רואים מכאן שיכול אדם למנוע את אחרים מחטא אם חושב עליו שלא יחטא, ומראה לו שהוא איש חשוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
מצאנו שהלביש משה את אלעזר לפני מיתת אהרן. נמצא שיש ענין בהלבשת כהן גדול החדש, ואינו רק שכיון שצריך לעבוד ממילא צריך ללבוש את הבגדים. באמת, גם יכולים לקדש אותו על ידי לבישת בגדים. צריך ביאור מה עושה לבישת בגדים.
נראה לבאר שאם לובש בגדי כהן גדול, חושבים עליו להיות כהן גדול. וכיון שחושבים עליו כן, הוא חושב על עצמו כן - ואז הוא נעשה כן.
רואים מזה יסוד חשוב. מה שחושבים על אדם גורם שהוא יהיה כן, שגורם שהוא עצמו יחשוב כן על עצמו, וממילא יהיה כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
בלק
א
כשקוראים פרשה זה, חייבים אנחנו להקשות איך היה שבלעם, שזכה לנבואה עצומה, היה איש כל כך רע, ואיך חטא נגד ה’ כל כך. נראה שיש לבאר על פי קושיא אחרת. הפסוק קורא לבלעם "שתום עין,” שהיה סומא בעין אחד. וקשה למה אומר לנו זה; מה לנו ביכולתו לראות.
נראה שלא אומר שהיה ממש סומא, אלא סומא בראיית פערספעקטיב שלו. היה ראייתו על עצמו סמוי, שלא היה רואת את עצמו לטוב - וזהו מה שגרם שהיה כל כך רע. אף אם אדם מדבר לשכינה, הוא רק יכול להיות צדיק אם יכול לראות בעצמו טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
ב
בלעם הלך למקום שיכול לראות את בני ישראל כדי לקלל אותם. צריך לבאר למה רצה את זה, ולמה זה, בדווקא, יתן כח לקללה שלו חס ושלום.
נראה לבאר שיש דרך קל להזיק לאדם בלי אף נגיעה. אדם חושב על עצמו איך שבני אדם חושבים עליו. והדרך שאדם חושב על עצמו משנה אותו. אז, אם אחרים חושבים עליו לרע, ואז הוא יחשוב על עצמו לרע, יהיה רע.
נמצא לומר שבלעם רצה לקלל את בני ישראל, וחלק מן הקללה יהיה שיחשוב עליהם לרע. אז, אף הם יחשבו על עצמם לרע, ואז יהיו רשעים, ויהיה קל לקללה שלו לחול.
אבל, טובה גדולה עשה ה', ושמר אותנו מזה, ועשה שלא קרה מחשבה של בלעם, ולא היפך אותנו לרע ח"ו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
פינחס
א
יהושע נתמנה להיות מנהיג חדש של ישראל. צריך לבאר למה היה יהושע המנהיג, ולא אחר. למשל, כלב היה יכול להיות המנהיג. כלב היה יכול להתגבר על עצת מרגלים בפני עצמו, ולא הוצרך לסיוע של משה. אז, צריך לפרש איזה מדה היתה לו ליהושע שעשה שהיה יותר ראוי להיות מנהיג על בני ישראל.
ראשון, כדי להבין מה עושה שהיה מנהיג טוב, צריכים לבאר מהו מנהיג טוב. צריכים לבאר איזה הוא המדה שיבחר בו המנהיג כדי להיות יותר טוב. לעשות כן, נבדוק במשה.
משה לא היה יכול להיכנס לארץ ישראל כיון שהכה את הסלע ולא דבר לו. אך קשה למה זה יעכב אותו מלהיות מביא את בני ישראל לארץ. לכאורה, אינו עבירה כל כך גדולה.
נראה לבאר שלא היה העונש מחמת שהכה את הסלע, אלא היה העונש מחמת שקרא לבני ישראל "מורים." כיון שלא האמין בבני ישראל, ממילא לא היה יכול להיות מנהיג של בני ישראל, ולא היה יכול להביא אותם אל הארץ הטובה.
לא היה חי כיון שלא היה מביא את בני ישראל לארץ, כמו שאמרו חז"ל, שכל גדולתו של משה רק בא בשביל בני ישראל. כיון שלא היה עוד מנהיג של בני ישראל, לא היה חשוב די לבוא אל א"י.
אז, רואים שמדה חשובה של מנהיג טוב הוא שרואה את עדרו בטוב, וחושב ומדרהר עליהם לטוב. מדה זה הוא חשוב כיון שמה שאדם חושב על אחרים גורם מה שאחרים חושבים על עצמם. מה שחושבים על עצמם גורם מה הם. אז, מנהיג שעושה כן יכול להפוך את כל עדרו לטוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יהושע בא מיוסף, ולכן היה מכיר במדה זה. אז, ידע משה שהיה יכול לבטוח שיהיה יהושע מנהיג טוב, מנהיג שמכיר בצורך למדה זה ושנוהג באותה מדה.
ב
מצאנו שבכל שבט, מנין בני אדם היה או לסופו מאה או לסופו חמישים. צריך לומר שה' עשה את זה בדווקא. קשה למה יעשה את זה.
נראה שהוא כדי לומר לכל אחד ואחד שבלי הוא, לא רק חסר אחד, אלא מנין החמישים לא שלם. אז, כל אחד יכיר כמה חשוב הוא.
אם הוא יחשוב על עצמו להיות חשוב, הוא באמת יהיה חשוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ג
כשבני ישראל נמנים בפרשה זו, נמצא שיש קרוב לששים ריבוא בני ישראל. קשה למה לא רק אמר שהיו ששים ריבוא, ולמה אמר כמה היו בדיוק.
נראה שהוא לומר לכל אחד ואחד שהוא חשוב, שה' לא רק מונה אלפים, אלא מונה כל יחיד ויחיד. כיון שהיחיד יכיר כמה ה' אוהב אותו, יבין לחשוב על עצמו לטוב. ממילא, יהיה טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
מטות
א
קרא אומר שאם אשה נודרת ואב מיפר הנדר, ה’ יסלח לה. גמ’ מפרש שהציור הוא שאשה לא מכרת שאביה הפירה נדריה. מכוונת לעבור, אבל נמצא שלא עברה, ועדיין צריכה כפרה.
צריך לבאר למה צריכה כפרה, כיון שלא עברה על שום איסור.
נראה לבאר שחושבת שהיא עשתה איסור. אז, תחשב על עצמה לבעלת איסור. זה יעשה שהיא, באמת, בעלת איסור, ותעבור עוד איסורים. אז, מה שעשתה הוא רע, וצריכה סליחה.
רואים מכאן יסוד חשוב: מה שאדם חושב על עצמו עושה מי הוא. אז, צריכים לחוש מה חושבים על עצמינו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
מן הפסוק יוצא שכלים של גויים צריכים להיטבל במקווה קודם שישתמשו בהם בני ישראל. אבל צריך ביאור למה.
נראה לציין למה שאמר אדם כשנתקלל - אטו אני וחמור שלי נאכל מאבוס אחד. רואים מזה שאם שני דברים אוכלים מכלי אחד, יש דמיון ביניהם.
אז, הביאור הוא שה' צווה את בני ישראל כן כיון שאם לא יעשו כן, יחשוב על עצמם להיות שווה לגויים. אם יהודי יחשוב שאינו נבחר ואינו חשוב, לא יהיה צדיק כל כך. כדי להיות צדיק, צריך לחשוב על עצמו לצדיק. לכן, חילק ה' בין בני ישראל לבין אומות העולם, וצווה שכלי אומות העולם צריכים טבילה.
רואים מזה יסוד חשוב: איך שאדם חושב על עצמו ממש משנה וממש קובע מי הוא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
מסעי
א
קרא אומר שצריך לתת שלש ערי מקלט בארץ ישראל ושלש בעבר הירדן. מקשה גמרא למה ניתן מנין שווה לעבר הירדן, כיון שלא היו כל כך כמה בני אדם שם. הגמרא מבאר שהפסוק משמע שהיו כמה רוחצים שם. מקשים העולם מה לנו שהם רוצחים, כיון שבאים לערי מקלט מחמת הריגה בשוגג, ולא במזיד.
נראה שאין מה שהיו רוצחים הסיבה שהוצרכו לכמה ערי מקלט, אלא הוא סימן. צריך לבאר איך יקרה שהיו הורגים זה את זה. צריך לומר שהוא מפני שכמה בני אדם חשבו על עצמו להיות הורגים. אבל, זה גופא צריך ביאור. מה יעשה שחושב כן על עצמו. לכאורה, הוא שכבר הרג, ואף בשוגג. אז, ממה שהורגים זה את זה, רואים שהיו הורגים בשוגג.
מזה, לומדים יסוד חשוב, והוא שמה שאדם חושב על עצמו משנה את עצמו, עד שמביא אותו להיות אפשר להרוג את חברו. זה אפשר לרע, וכל שכן, גם אפשר לטוב, שמדה טובה מרובה ממדת פורענות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק מזכיר כל מסעות של בני ישראל. אך קשה למה צריך להזכיר את כולם. הרי, לכתחילה, היה יותר טוב שלא ילכו בהם, שכל זמן שהיו במדבר היה עונש להם.
נראה לבאר שבזה ה' הראה לבני ישראל את החשיבות שלהם. בפרט כיון שהיה בזה עונש, ה' הראה להם שהוא עדיין מחשיב אותם. רק מונים כל הילוך של סאלאבריט"י, של אדם חשוב מאד. ה' הראה לבני ישראל שהם חשובים לו מאד.
רואים מזה דבר חשוב. הפסוק האריך בלשון שלו כדי להראות לבני ישראל שה' חושב שהם חשובים. אם אדם מכיר שחושבים עליו שהוא חשוב, גם הוא יחשוב על עצמו כן - ויהיה כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
דברים
א
קרא אומר שאסור לדיין להכיר פנים, וגדול יהי כקטן. לכורה, אין קרא זה רק אומר שלא לכבד את הגדול יותר מן הקטן, ולפסוק כמותו כיון שהוא גדול. לא - לא צריך קרא לומר כן. אלא קרא אומר שלא לחשוב על אחד שהוא גדול ולא לחשבו על בעל דין אחר שהוא קטן.
הסיבה שלא יכול לעשות כן הוא שמה שאדם חושב על חברו עושה מה שחברו חושב על עצמו. זה עושה שינוי גודל בחברו. אז, אם תחשוב על אדם שהוא קטן, יהיה קטן, ואיך יוכל, אז, לנצח בדין. אז, צריך שלא תכיר פנים.
רואים יסוד חשוב, והוא שמחשבת אדם על חברו עושה את חברו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
בפרשה זו, משה הוכיח את בני ישראל. רש"י מבאר שבדווקא עשה כן לפני מיתתו, כמו שעשה יעקב אבינו. צריכים לבאר למה יותר טוב להוכיח קודם מיתה.
נראה שבכל תוכחה יש חשש גדול. בדרך כלל, תוכחה מראה שהוא חושב על אחר להיות חוטא - שאומר לו שעשה חטא. כיון שכן, בוודאי יש לחוש שאותו אדם יחשוב על עצמו להיות חוטא. וכיון שחושב על עצמו כן, יש לחוש שיהיה כן.
אז, יותר טוב לתת תוכחה מיד קודם מיתה. אחרי מיתה, אינו בעולם עוד לחשוב על אותו האיש לחוטא ולכן לא יהיה חוטא.
רואים מזה שצריכים להיות מאד נזהרים שלא לגלות לבני אדם שחושבים עליהם לרע. אם הם רואים מאתנו שאנחנו חושבים עליהם לרע, גם הם יחשבו כן על עצמם, וממילא יהיו כן.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ואתחנן
א
כתיב בקרא, ”צו את יהושע וחזקהו ואמצהו.“ צריך לבאר מהו החיזוק והאומץ הזה. לכאורה, אינו רק שאומר לו שחושב שיצליח, שהרי ידע שחושב שיצליח, שהרי ה’ חושב שיצליח, שה’ מנה אותו. אז, צריך ביאור מה עושה.
אחר זה כתיב, ”כי הוא יעבור לפני העם הזה והוא ינחל אותם את הארץ אשר תראה.“ צריך ביאור למה אמר שהוא הארץ אשר תראה; היה לו לקרוא לו ארץ כנען או ארץ ישראל כמו בכל מקום אחר בתורה.
נראה לבאר שלא רק אומר שיחזק אותו, אלא שידרהר אותו להיות חזק. זה יעשה שהוא חזק, וזה יעשה שהוא אמץ. רק על ידי זה, יכול לחשוב על עצמו להיות חזק, ורק על ידי זה יהיה חזק.
נראה שזהו כוונת ”הארץ אשר תראה.“ מבאר שצריך לחשוב שכיון שהוא יעשה מה שאתה חושב - הוא יכנס את העם אל הארץ אשר אתה תראה אותו – הוא באמת מביא אותם לשם.
רואים מזה יסוד חשוב. אף אדם חשוב כיהושע הוצרך שאחד יחשוב שהוא ראוי למה שיעשה. אם אין משה מאמין בו, ואם אין משה חשוב עליו לטוב, לא היה יכול להביא את העם. אז, רואים כח של דרהר על אחרים. אותו דרהר נותן לו כח, נותן לו חוזק, ונותן לו אומץ לעשות מה שצריך לעשות. לפעמים, הוצרך לאותו כח, שאף יהושע לא היה יכול להביא את העם בלי דרהר של משה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר שחייבים אנו לזכור כי עבדים היינו במצרים, וה' הוציא אותנו מזה. קשה למה צריכים לזכור את זה.
נראה שהענין הוא שלפעמים קשה לעשות המצוות. אז, אנחנו חייבים לחשוב על עצמינו מי אנחנו. אנחנו עבדים - ועבדים לא בוחרים.
הביאור הוא שאיך שאדם חושב על עצמו, כך הוא. אם אדם חושב על עצמו להיות עבד, באמת, יהיה עבד, ויהיה, מזה, עבד לה' יתברך.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
עקב
א
קרא אומר, ”מה ה’ אלקיך שואל מעמך כי אם ליראה….“ הגמרא מקשה למה זה נחשב דבר קטן. מתרץ שלמשה היה דבר קטן. אך צריך לבאר איך אנחנו יכולים להשיג את זה.
גם צריך ביאור למה הגמרא ממשיך לבאר מה עשה ה’ לנו. לכאורה, דברים אלו נוגעים רק לאהבת ה’. אבל הגמרא לא רק דן באהבת ה’, אלא אף ביראת ה’ והליכה בדרכיו וכדומה. איך דברים אלו עוזרים להשיג ליראת ה’.
נראה לבאר שהדרך להשיג ליראת ה’ הוא לחשוב על עצמינו להיות עבד ה’ ולהיות טפל לה’. ממילא, יהיה לו יראת ה’, שממילא יהיה עבד ה’, שהדרך שאדם חשוב על עצמו מעורר אותו, ומשנה אותו.
אז, מזכיר מה שה’ גרם לנו להיות מי אנחנו. אז, אנו רק טפלים לו. כיון שאדם יחשוב כן על עצמו, כן יהיה. אז, באמת, דבר קטן הוא, שכיון שחושב על עצמו כן, קל ליראות מה’.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפרשה מתחיל במילים "והיה עקב תשמעון." בלבלו המפרשים לדעת מהו הפירוש של "עקב," ולמה נקט אותה המילה בדווקא.
נראה לבאר שרצה לתת משל איך יחשוב אדם על מצוות. אדם לא רק יחשוב שמצוות הם דברים שהוא עושה. אלא, הם דברים שהם תחת עקביו - הוא עומד עליהם, והם מגביהים אותו למעלה למעלה, וגם נותנים לו כח לקחת עוד פסיעה ועוד פסיעה.
הביאור בזה הוא שאחרי שאדם עושה מצוה, מתחיל לחשוב על עצמו להיות מקיים של המצוות. כיון שחושב על עצמו כן, באמת נעשה כן.
רואים מזה יסוד חשוב. איך שאדם חושב על עצמו הוא המכריע מי הוא - מחשבתו קובעת מי הוא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ראה
א
קרא אומר, ”בנים אתם לה’ אלקיכם… לא תשימו קרחה בין עיניכם למת.“ צריך לבאר שייכות של שני עניינים אלו זה לזה.
נראה שיש לבאר אותו בדרך דרש. אפשר לומר שאין ”לא תשימו קרחה בין עיניכם“ רק אומר שלא לקרח את ראשינו. אלא אומר שלא לראות בך ובאחרים קרחה, שהם קרחים מן המצוות ורעים.
זה דבר חשוב, שמה שאדם חושב על חברו יגרום מה שחשוב חברו על עצמו. זה יגרום דברים בחברו. אז, צריך לשמור שלא לחשוב על חברו לקרחה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אוסר מסירת הבן למולך. מנהג שטות היה לעובדי עבודה זרה שהיו נותנים את בנים למולך, והיו מוליכים את הבן שלהם קרוב לאש.
צריכים לבאר איך זה יכול לקרות בעם הקדוש. אנו רואים בעינינו שבני ישראל אוהבים את הבנים שלהם, ומוסרים את נפשם וגופם בעדם תמיד. אז, קשה איך יימצא מי שממית את בנו כדי למסור אותו לעבודה זרה.
נראה לבאר על פי המשך הפסוקים, שמספר איך בני ישראל יגורו קרוב לגויים. הרי, זהו הדרך שאפשר להיות שיהודי יבוא להמית את בניו. אם אדם יושב תמיד קרוב לגויים, ומכיר איך שגויים חושבים עליו להיות רשע (שהגויים חושבים שלהיות רשע זהו נכון), יהיה רשע. ואז, אף הוא יחשב על עצמו שהוא באמת רשע, שהוא לא מקפיד על מצוות ושהוא לא אוהב את בניו כל כך, וממילא מוסרם למולך.
רואים מזה יסוד חשוב. הדרך שאחרים חושבים עלינו הוא דבר מאד חשוב, והוא דבר שמשנה איך אנחנו חושבים על עצמינו. זה מהפך מי אנחנו, שהדרך שאנו חושבים על עצמינו גורם מי נהיה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ג
מסית הוא אחד מן העבירות הכי חמורות שבתורה. ממיתים את המסית, ולא נוהגים עמו ברחמנות כלל. צריכים לחפש טעם למה עבירה זו היא כל כך חמורה.
אפשר לבאר בדרך זה: הרי, אדם נחשב מסית אף אם אפילו אדם אחד לא עשה עבירה על פיו. בדרך כלל, אם אדם ניסה לעשות עבירה, ולא עשה אותו, אינו חייב כלום, וכל שכן שלא יתחייב מיתה. אז, צריכים לבאר מה עשה מסית עד שממיתים אותו בלי שום רחמנות.
נראה שהביאור הוא שעשה דבר חשוב מאד, ויצאה ממנו תוצאה חשובה מאד. וזה שהוא הראה לחבירו שרצה להסית אותו שהוא חושב עליו להיות מי שיעבוד עבודה זרה. הראה לו שלא חושב עליו להיות תמיד שתמיד מבקש עבודת ה', אלא חושב עליו להיות מי שיעבוד עבודה זרה.
מצאנו, שהדרך שאדם חושב על חברו גורם שחבר שלו יחשוב על עצמו כן. זה יגרום שבאמת יהיה כן. אז, נמצא שמסית באמת גרם שחברו יהיה רשע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
שופטים
א
כשזקנים עוסקים בעגלה ערופה, חייבים לומר, "ידינו לו שפכו את הדם הזה." וקשה מהו ההוה אמינא שהזקנים הרגוהו.
באר האלטר מקאלם שהענין הוא שאילו היו מלווים אותו ונותנים לו מזון וצידה לדרך, היה רואה בעצמו שהוא אדם חשוב כיון שזקני העיר כבדוהו כל כך. וכיון שהיה רואה על עצמו חשיבות זה, לא היה נהרג - היה בורח או היה רודף את רודפיו. מפני שלא חשבוהו למכובד וחשוב, לא היה יכול לחשוב כן על עצמו להציל עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
ב
הפסוק נותן דין של ישראל שעובד עבודה זרה. צריכים לבאר איך דבר כזה  יהיה, איך יהודי שעמד בהר סיני וראה את הקולות ואת הברקים יבוא לעבוד עבודה זרה.
גם קשה לשון הפסוק, שאומר ש"יומת המת." וזה קשה, שאינו כבר מת, שאם היה כבר מת, למה צריכים שימות.
נראה לבאר שהתורה קורא אותו מת כיון שמדברים במי שחושב על עצמו להיות מת. הוא חושב שאינו אדם חשוב, אינו צדיק. וכיון שכן, לא יהיה צדיק, ולא יהיה טוב. זהו הדרך שאדם מבני ישראל יבוא לעבוד עבודה זרה.
לומדים מה יסוד חשוב. הדרך שאדם חושב על עצמו ממש משנה מי הוא; הוא מה שחושב על עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
כי תצא
א
קרא אומר שכי יהיה לאיש בן סורר ומורה, שלא שומע לאביו ואמו, ועושה עבירות קלות בקטנותו, בית דין ממיתים אותו. גמרא מבאר שממיתים אותו על שם סופו, שסופו ללסטם את הבריות ולהרוג את בני אדם.
צריך לבאר למה כל כך פשוט לנו שיהרוג את אחרים. הרי טעה ועשה עבירה כשהיה קטן, שהיה רק קצת אחר בר מצווה שלו. מחמת זה, מניחים שיהרג כשיגדל?!
נראה לבאר שאין מעשיו הראשונים סימן, שהוא איש ההורג, אלא סיבה. כיון שעבר כבר, והוא עבריין, הרי חשוב על עצמו שהוא עבריין. כיון שחושב כן על עצמו, כן יהיה, ועוד יגדל עוונותיו.
נראה שזהו הביאור של מה שאמרו חז"ל, "כך היא דרכה של יצר הרע: היום אומר לו עשה כך… עד שעובד ע"ז." וקשה איך הולך מעבירות קלות לעבודה זרה.
אפשר לומר שהביאור הוא כמה שכתבנו. כיון שאדם עובר עבירה קלה, חושב על עצמו להיות עבריין. זה גורם שהוא באמת עבריין, ועובר עבירות יותר ויותר גדולות, עד שעובד עבודה זרה.
רואים מכאן כח של מחשבת אדם על עצמו, שיכולים לעשות שהוא רע. אז, מזה נראה כוחם לטוב, כיון שגדולה מדה טובה ממדה רעה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר שה' לא שמע אל בלעם, אלא הפך את הקללה לברכה כי אהב ה' אותנו. וזה קשה, שלמה הפסוק צריך לומר "כי אהבך ה' אלקיך"? לכאורה, לא מכוון לבאר למה הפך ה' את הברכה לקללה, שפשוט שה' אוהב אותנו, שאנחנו בנים בכורים שלו.
אלא נראה שהפירוש של "כי" זה הוא "אלא." ה' לא אבה לבלעם לקלל, ואף הפך את הקללה לברכה, כי אם - מה שעשה כדי שלא יהיה קללה - אהב ה' אותנו. מה הפירוש בזה?
הראה ה' לנו את אהבתו לו. הרי, כשאדם חושב על עצמו לטוב, כן יהיה; אדם שחושב על עצמו לצדיק יהיה צדיק. אז, אחרי שה' הראה לנו שהאו אוהב אותנו, חשבנו על עצמינו להיות בני אדם שה' אוהב. אז, ממילא אין אנחנו בכלל קללה. אי אפשר לקלל אדם כה; אדם כזה הוא בעצם ברוך.
מזה לומדים יסוד חשוב. מה שאדם חושב על עצמו ממש משנה אותו, ומהפך אותו להיות כמו שחושב, ואף נגד כוח חזק כקללת בלעם.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
כי תבא
א
אומר קרא שקללות של תוכחה באים "תחת אשר לא עבדת את ה’ אלקיך בשמחה ובטוב לבב.” קשה, איך ייענשו עונש חמורה כזה על עבירה קלה כזה - עשו את המצוות, אבל רק לא עשו אותם בשמחה.
רב משה פיינשטין שאל שאלה עצומה: ידוע שבאו כמה יהודים לאמריקא ומסרו נפשם בעד שבת ובעד יהדותם. אבל למעשה, לא היו בניהם לבסוף יהודים דתיים, אלא התנכרו מיד. צריכים לשאול איך זה קרה.
באר רב משה שזה קרה כיון שהיו אביהם שמסרו נפשם כל כך אומרים, "איז שבער צו זיין א איד," ולא, "איז גשמק צו זיין א איד." כיון ששמעו שלא היה שמחה ביהדות, הבנים נתנכרו.
על פי זה, יש לומר שאם אדם לא עובד את ה’ בשמחה, עומד עבודתו להיבטל. וכיון שכן, בני ישראל נענשים על זה.
הרי, רואים שכיון שהוא חושב על עצמו להיות בצער, להיות במצב רע, ייהפך, ולא יישאר באותו מצב. אף שיודע שצריך לעשות מצווה, מחשבתו על עצמו - שמוטל בצער - יגרום לו ולבניו צער מספיק עד שלא יקיימו את המצוות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. צריך לבאר איך ראה אותו אביו. נראה לבאר על פי המשך של הגמרא. גמרא ממשיך לומר שאמר לו אותו דמות שאם יחטא, יהיה שמו מחוי מן החושן. קשה, לכאורה, מה לו בזה; אין מצווה להיות החושן. גם לא מסתבר שיוסף הצדיק ירצה בכבוד כזה. אז, נראה שהענין היה שדמותו שהראהו יעקב היה של איש חשק למצוות, איש שהיה שמח במצוות, איש שרצה במצוות לא כיון שצריך, ולא כדי ליטול שכר או כבוד, אלא אך ורק מפני שהם מצוות. כיון שהכיר יוסף שאביו חשב עליו לאיש כזה, אף הוא היה יכול לחשוב על עצמו לאיש כזה, והיה יכול לעמוד כנגד יצרו ושלא לחטוא.
ב
הפסוק אומר שבני ישראל מקבלים את כל הרעות המנויים בתוכחה כיון שלא עבדו את ה' בשמחה ובטוב לב. צריך לבאר מהו טובת הלב, ואיך הוא משונה מן שמחה.
נראה לבאר שטובת לב הוא שחושב בלבבו על עצמו להיות טוב. הוא מאמין בעצמו, והוא יודע שהוא טוב וצדיק.
הרי מה שחושב אדם על עצמו, בין לטוב ובין לרע הוא נכון. אם חושב על עצמו לצדיק, יהיה צדיק, ואם חושב על עצמו לרשע, יהיה רשע. הפורעניות באים כיון שלא חשבו על עצמם להיות טובים, והרי לא היה עבודת ה' שלהם עומד להישאר במקום שלו.
רואים מזה יסוד חשוב. אדם יכול לעבו ולעבוד לה', אבל לא יישאר אם לא גם חושב על עצמו לטוב. מה שאדם חושב על עצמו, אז, הוא דבר מאד חשוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
נצבים
א
גמרא דורש מ"ולא אתכם לבדכם" שמשה אומר לבני ישראל ש"אין אני משביע אותכם על דעתכם, אלא על דעת המקום ועל דעתי." הפשטות הוא שכשהשביע את בני ישראל, נתן תרגום למילים, ולא בא התרגום מבני ישראל הנשבעים. אבל נראה שיש לומר פשט יותר עמוק על פי דרך דרוש.
לכאורה, בני ישראל היו יכולים להיות תמהים איך יוכלו לקיים את כל המצוות, כל המצוות שכבר קבלו, וכל המצוות שיקבלו בביאתם לארץ, עם ערבות שיתחייבו. אז, אמר להם ה’ שלא רק תעשה כפי מה שאתה חושב שיכולים לעשות, אלא תעשה כפי דעתי וכפי דעת משה. ה’ ומשה היו מנהיגים בני ישראל, והם חשבו על בני ישראל לטוב, שזהו מה שמנהיג צריך לעשות.
נראה לומר שכיון שה’ ומשה חושבים עליכם, בני ישראל, לטוב, תוכל, ולא תהיה פלא איך תקיים. זה מפני שמה שמשה וה’ חושב עליהם ישנה מה הם חושבים על עצמם, וזה יתן להם הכח לקיים כל מצוות אלו.
אז, אומר משה שה’ ואני חושבים עליכם להיות יכולים, ואז, אכן, אתם יכולים.
רואים מכאן יסוד חשוב. אף אם אדם חושב שדבר אינו אפשר כלל לו לעשות, אינו כן, שאפשר שאם חושב על עצמו שיכול, יהיה יכול לעשות אותו. ואיך יבוא לחשוב על עצמו כן? אם מכיר שחברו חושב עליו, אף הוא יחשוב כן. אז, צריכים אנו לחוש לחשוב על חברים שלנו לטוב, שעל ידי זה, הם יעלו מאד מאד.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
כתיב, "אתם נצבים היום כולכם." רש"י מביא מדרש שאומר שהיו יראים מחמת התוכחה והקללות ששמעו בפרשת כי תבוא. אז, משה הגיד להם שעדיין חיים. צריך ביאור מה הגיד להם, ואיזה נחמה יש בזה. לא אפשר לומר שאומרים שה' לא באמת יעשה כמו שהבטיח בקללתו. אז, צריך ביאור מה היה כוונת משה.
נראה שנתן להם עצה איך שלא לחטוא, והוא שיחשבו שהם כולם נצבים לפני ה'. אם יחשבו כן על עצמכם, יהיו כמעט לפני ה'. זה אומר שאם חושבים שהם קדושים שה' אוהב, יהיו קדושים, ולא יוכלו כלל לחטא, ובזה יהיו ניצולים מקללות של עבירות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
וילך
א
כתיב בפסוק, "ואתה כתבו לכם את השירה הזאת…."[fn:2] תמוה הוא למה שינה מלשון יחיד (אתה) וללשון רבים (לכם). יש להסביר שכל אחד ואחד צריך לכתוב. לכן, אומר לשון יחיד. אבל אחר זה אומר לשון רבים כיון שבכתיבת התורה, ובאמת, בכל קיום התורה, אפשר שרק על ידי מה שבני אדם אחרים חושבים עליו להיות איש שמקיים מצוות. אם חברו חושב עליו לטוב, ורבו חושב עליו לטוב, ואשתו חושב עליו לטוב, אז - ורק אז - יכול לקיים מצוות. לכן, אומר כאן לשון רבים - מקיים מצווה רק מפני שהוא מורכב ממחשבת כמה בני אדם עליו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק מזכיר שמשה לימד לבני ישראל  את כל דברי הספר תורה עד תומם. בפשטות, זה רצה לומר שלימד להם כל דבר תורה עד תום כל דבר תורה, עד סוף דבר תורה. אבל, קשה, שאז רק יאמר שלימד להם את כל דברי תורה.
נראה לבאר ש"תומם" לא קאי על דברי ספר תורה, אלא קאי על בני ישראל. משה לימד להם עד שנעשו תמים ושלמים על ידו. אבל, עדיין צריך ביאור איך זה יקרה, ואיך על ידי לימוד של התורה ייעשה אדם תמים.
נראה שהביאור הוא שכשאדם לומד, לא רק בא למוח שלו דינים של תורה, ולא רק קיים מצווה ללמוד תורה. אלא, הוא נעשה אדם הלומד תורה. הוא יכול לחשוב על עצמו באופן אחר עכשיו, הוא יכול לחשוב על עצמו להיות אדם טוב, להיות אדם שלומד תורה.
רואים מזה יסוד חשוב, והוא שאיך שאדם חושב על עצמו משנה מי הוא. אז, מי שלומד תורה נעשה תמים, כיון שחושב על עצמו להיות לומד התורה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
האזינו
א
קרא אומר, "כי דור תהפוכות המה," וזה מזכיר גנותם של ישראל. גמרא אומר מעשה בקרא זה. היה איש ששמו כידור. מחמת שמו, הכיר בו רבי מאיר שלא היה איש טוב, שהיה רבי מאיר מדקדק בשמות, והבין ששם כידור הוא דומה לקרא שאומר זה על בני ישראל כשאינם מהוגנים.
כמו כן, אומר גמ’ שהשם גורם, ושם קובע מי הוא האדם. צריך לבאר איך זה קורה, ואיך יש כח לשם לשנות את האדם.
נראה שהביאור הוא כך: מהו שם? שם הוא מה שהכל קוראים לאדם. אם הכל קוראים לאדם דבר שמזכיר עליו שם של רשע, כן יחשבו עליו כן קצת. כל זמן שעובר עבירה, יחשבו, כשקוראים לו כידור - אכן, כידור הוא. כיון שהוא שומע שהם קוראים לו כן, וכיון שהוא מכיר שהם חושבים עליו קצת כן, אף הוא יחשוב על עצמו כן. אחר שהוא מכיר על עצמו כן, ייהפך להיות רשע כשמו.
נראה שלכן לא קוראים אדם בשם רשעים, כמו שדורש גמ’ מ"שם רשעים ירקב." כל זמן שיקראו לו בשם זה, יחשבו בו, והוא יחשב בעצמו, דמיון לאותו רשע. לכן, יידמה לאותו רשע, ולכן אף הוא יהיה רע.
רואים מכאן יסוד חשוב: אדם יכול להיות איש כשאר כל אנשים, אבל מחמת מחשבות אחרים עליו, ומחמת זה, מחשבות שלו על עצמו, נהפך להיות רשע. אז, צריכים לשמור על עצמנו לחשוב רק טוב על אחרים.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר, "כי לא דבר ריק הוא מכם." מזה דורש הירושלמי שאם תורה דבר ריק הוא, מכם הוא. הפשטות הוא שמפני שאתם לא לומדים אותו יפה, אתם מוצאים אותו להיות דבר רק.
אבל, אין זה משל טוב. הרי, דבר ריק אינו ריק דבר שלא מוציאים ממנו טעם, אלא דבר שאי אפשר להוציא ממנו טעם. היה לו לדמות אותו יותר לדבר מכוסה, ולא לדבר רק.
נראה לבאר ש"מכם" לא רצה לומר שאתם לא לומדים אותו יפה, אלא שאתם חושבים על עצמכם להיות מי שלא יכול ללמוד, ומי שלא שייך לתלמוד תורה. אז, המשל הוא טוב. אם אתם חושבים על עצמכם כן, אין מה לעשות כלל, וממש רק הוא, ואי אפשר להוציא ממנו שום טעם.
לומדים מזה דבר חשוב. איך שאדם יחשוב על עצמו משנה מי הוא, עד כדי שלא יוכל להנות מן התורה אם חושב על עצמו לכך.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
וזאת הברכה
א
בברכת משה, מדמה משה שבטים לבהמות וכדומה. כמו כן מצאנו ביעקב אבינו בפרשת ויחי. צריך ביאור מהו הפשט בדמיונות אלו.
נראה להתחיל ביסוד. הדרך שאדם חושב את חברו הוא שעושה את חברו למה שהוא. אז, אם מדרהר שהוא חכם, יהיה חכם. אם מדרהר שהוא גבור, יהיה גבור.
אז, נראה שמשה ויעקב נתנו דרהר שלהם על שבטים אלו, ודרהר אותם, בענינים מיוחדים, כבהמות. אז, יבואו להם קרקטרסטיקים טובים של אותם בהמות.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
הפסוק אומר שעלה משה אל ההר לראות את כל ארץ ישראל. הגמרא בסוטה דורש שעלה את כל הפסיעות בפסיעה אחת. קשה איך עשה כן, ואיך זה קרה.
נראה לבאר שכיון שמשה רצה כל כך לכנס לארץ, חשב על עצמו להיות כבר בן ארץ ישראל, וחשב על עצמו להיות כבר על ההר. כיון שכן, היה כמעט כבר עולה, והיה קל לו מאד לעלות. לא באמת עלה בפסיעה אחת, אלא היה כמו פסיעה אחת לו, כיון שהיה כבר עומד לזה, שכבר חשב על עצמו לכך.
רואים מזה יסוד חשוב. איך שאדם חושב על עצמו משנה מי הוא. אם חושב על עצמו להיות כבר בגדר מקיים מצצוה, אז זהו מי שהוא, הוא מקיים המצווה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ראש חדש
בני ישראל מיוחסים ללבנה שבה מונים חדשים ולה נמשלים. צריך לדון באיזה אופן נמשלו בני ישראל ללבנה. נראה שהוא שאין ללבנה אור של עצמו, אלא הוא נעשה מאיר מחמת אור של אחרים.
נראה שלבני ישראל יש מדה חשובה. כיון שאדם אחר חושב דבר על ישראל, אף אותו ישראל נעשה כן. הוא נשתנה מחמת מה שחשב חבירו - הוא מאיר מחמת מה שחבירו מאיר עליו.
בזה, דומים בני ישראל ללבנה.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
שלש רגלים
ירושלמי אומר מעשה שאירע בענין קרא של "לא יחמד איש את ארצך" כשעולים לרגל. המעשה היה שהיו גויים שרצו קרקע של יהודי אחד. כיון שעלו לירושלים, באו אותם גויים כדי ליטול אותו קרקע מהם, אבל ראו דמות של מלאכים בו ולא לקחו אותו.
נראה לפרש שלא חששו שהיו אנשים שם, ולא ראו מלאכים.
אלא, ראו דמותם של עצמם של המלאכים - ראו מה שמלאכים חשבו עליהם. מלאכים היו קדושים וטהורים, ומסתמא חשבו עליהם להיות טובים. כיון שכן, גם הם נהפכו כן, ולא היו יכולים להיות חוטאים.
רואים מכאן יסוד חשוב. מה שאדם חושב על חברו, ואיך שרואה אותו, ממש משנה מי הוא חברו, ומונע אותו מחטא.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
אלול
יש ספרים שאומרים ש"אלול" הוא ראשי תיבות ל"אנה לידו ושמתי לך (מקום)." זה קשה להבין, שפסוק זה מדבר במי שממית את חבר שלו בשוגג, ואיזה שייכות יש בין פסוק זה לעבודת אלול.
נראה לבאר שתשובה היא דבר קשה. הרי, אחרי שאדם חוטא, לא רק חטא, אלא שינה מי הוא - עכשיו הוא אדם שחטא. אם חושב על עצמו כן תמיד - "אני אדם שחטא; אני רשע"- לא אפשר לשוב. אלא, צריך לחשוב "אנה לידו," שרק קרה לו עבירה, ולא שהוא בעל עבירה. על ידי זה "שמתי לך מקום," שה' נתן לנו תשובה.
לומדים מזה יסוד חשוב. איך שאדם חושב על עצמו הוא דבר מאד חשוב בשאר מעשים שלו, שהוא נעשה מה שחושב על עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו - שלא היה לו לחטוא.
ראש השנה
צריך ביאור מהו ענין הסימני מילתא בראש השנה, ואיך דברים אלו משפיעים לשנות גזר דין שלנו. נראה שכדי לתרץ לזה, נקשה קושיא אחרת, והוא למה טובלים את התפוח בדבש, ולא רק נותנים דבש על התפוח (או שנוכל לבחור איזה לעשות, או זה או זה). לכאורה, הענין הוא רק שיהיה מתוק, ולזה, זה וזה יהני. אז, קשה למה צריכים לתת תפוח לתוך הדבש.
נראה שהביאור הוא שצריך לראות את עצמינו כאותם הסימנים. לכן, צריכים לאכול את הסימנים; כדי שייעשו, ממש, חלק ממנו, שאוכל נעשה חלק מן הגוף שאוכל אותו. על ידי זה, השם של הסימנים ישפיע על מי שאוכל אותם.
הרי, כשאדם טובל את התפוח בדבש, אותו תפוח יורד ונופל (לתוך הדבש), אבל שוב מוציא דבר מתוק ועולה ועלה. (שוב - וזה יותר טוב - נותנים עליו ברכה.) כמו כן אנו: לפעמים, אדם נופל בגשמיות וברוחניות; וצריך לדעת שלא נופלים, אלא יש יד השי"ת שמפיל אותנו, והסיבה שעושה כן הוא להפיל אותנו לתוך מתיקות.
גמרא סוטה מבאר שיוסף ניצול על ידי ראיית דמות דיוקנו של אביו שבא לו. נראה שלא ראה דמות דיוקנו של אביו, אלא ראה דמות דיוקנו שלו, של אביו. ראה איך אביו חשב עליו, וממילא לא חטא. יוסף חשב שבוודאי הוא בעל חטא, והוא רע, ובוודאי יעבור; הרי נפל כל כך מארץ ישראל, מבית יעקב אבינו, למצרים, למקום הכי גדול של טומאה בעולם. אבל, אביו ראה שהיה יד שגרם כל דברים אלו, כמו שבארנו, כדי לתת לו ולכל בני ישראל מתיקות. ועל ידי זה הטוב, כיון על יוסף להיות צדיק. אז, כיון שהכיר שאביו חושב שהוא צדיק, ושיד ה' הפיל אותו, גם הוא היה יכול לחשוב על עצמו לצדיק, וכיון שחשב כן על עצמו נעשה צדיק, ולא חטא.
אנחנו רואים מזה, אז, יסוד חשוב. והוא שאף אם רעים גדולים באים על אדם, צריך להכיר שזה לא מפני שהוא רע - לא! לעולם אל תחשוב כן! אלא אדם צריך תמיד לחשוב על עצמו לצדיק, שרק כך יוכל להיות צדיק אמיתי.
* סוכות:
מצאנו שתי מצוות של החג. מצווה ראשונה היא ארבע מינים, ומצווה השנית היא מצווה לשבת בסוכה. לכאו', צריכים להבין איזה יחס בין שני מצוות אלו, ולמה שניהם ניתנו בחג הסוכות.
נראה לבאר שניהם על פי יסוד שמצאנו בסיפור של יוסף הצדיק. יסוד זה קל להבין, אבל, אף שהוא קל להבין, הוא גם קשה להבין.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
הביאור הוא שאדם צריך לשנות את עצמו בשני דרכים, שצריך לשפר את עצמו כשהוא מדרהר על עצמו, וצריך לשפר את עצמו כשאחרים מדרהרים על עצמו. הראשון אומר שצריך לשנות איך חושב על עצמו, והשני אומר שצריך לשנות איך הוא מדרהר על עצמו נגד מחשבות חברו.
לכן, יש לו שני מצוות. מצווה ראשונה היא לשבת בסוכה. שם, הוא יושב בפני עצמו, ואינו עם המון העם, אלא הכל יושבים בסוכה שלעצמו. אז, יש לו רק מחשבה על עצמו. בזה, מקיים ענין ראשון.
מצווה שנית היא מצוות ארבע מינים. הם דברים שבגלוי. הם סימן לדבר שני שצריך, שצריך לשפר את עצמו כשהוא עם אחרים, וצריך לעמוד, לפעמים, נגד הדרהרים שלהם.
פסח
בהגדה, אומרים, ”ארמי עובד אבי.[fn:3]“ צריך לבאר למה מזכירים את זה בליל הסדר, שבו דנים ביציאת מצרים. לכאורה, מה שעשה לבן לאבותינו אינו נוגע לזה.
נראה שצריך לבאר פירוש של ”ארמי עובד אבי.“ אפשר לומר שהביאור הוא שחשב עליו לעבד. כיון שחשב עליו לעבד, מפני זה ממש נעשו בניו עבדים לפרעה במצרים. לכן, קרא זה נוגע ממש למילתא דיומא, ונוגע לסדר.
רואים מכאן יסוד חשוב. מה שאדם נחשב בעיני חבירו משנה מי הוא. אז, אם חברו חושב עליו כעבד, כך יתקיים לו. צריכים להחשיב יסוד זה, ולחשוב על חברינו רק לדברים טובים, ולא לעבד או שום דב רע.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
* שבועות
א
רות אמרה לנעמי שכל מקום שנעמי תלך, גם היא, רות, תלך. חז"ל בארו את זה בהרבה פנים. אחד מהם הוא שנעמי אמרה לרות שאסור ליהודים ללכת לטיאטראות. קשה למה תאמר כן לרות; היא מסברת לה מהו יהודי, וככה אומרת לה?!
הביאור הוא שמה שכונה לומר הוא שאין יהדות רק מנין מצוות שצריכים לעשות. אלא, יהדות הוא דרך החיים, הוא כל מה שאדם עושה.
ולמה זה כל כך חשוב? למה זה מה שצריכים לומר לגר? כי הדרך להתנהג בכל וכל כמו שאומרת התורה הוא לאדם לחשוב על עצמו ליהודי ולעבד ה’. איך אדם עושה כן? רק אם כל חיים שלו יהיו של ה’. רק זה גורם שאדם יחשוב על עצמו להיות עבד של ה’ ושומע בדרכיו.
רואים מזה יסוד חשוב, והוא שמה שחשוב אדם על עצמו משנה מי הוא אותו האדם. לכן, כל אחד ממנו צריכים לחשוב על עצמינו אך ורק לטוב, כדי שנהיה, כמו שאנו חושבים על עצמינו, רק טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ב
רב יוסף אומר ששמח בשבועות, ואמר שאי לאו אותו היום, כמה יוסף יהיה בשוק. לכן, חייב אדם לשמוח בשבועות, וכולי עלמא מודו שצריכים "לכם," ולא מספיק ב"לה'."
צריכים להבין מימרא הידוע של רב יוסף, ומהו הכוונה של "בלי האי יומא, כמה יוסף איכא בשוקא."
נראה שיש הבנה פשוטה לזה – היא עמוקה, וגם היא פשוטה. ההבנה היא שכל זמן שאדם הולך בין אנשים, הוא עצמו נעשה להרבה בני אדם. כל אדם רואה אותו בהשקפה ודרהר מיוחדת.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
אז, כל זמן שאדם הולך ברחוב, כל אדם מדרהר בו, וחושב עליו. אז, הוא נעשה לכמה בני אדם. לכן, אומר רב יוסף שיהיו כמה יוסי בשוק – לא שיהיו כמה בני אדם שנקראים יוסף, אלא שהוא עצמו יהיה כמה יוסף, על ידי דרהרים של בני אדם.
אבל, על ידי התורה, נעשה ליוסף אחד. הרי, התורה היא דבר המתאחדת לכל מעשה וכל מחשבה של אדם. אז, כל מקום שהולך, הוא רב יוסף – הוא הלומד תורה. אז, על ידי התורה, נעשה אחד, ואינו כמה יוסף שבשוק.
ספירה
מתו כל תלמידים של רבי עקיבא בימי הספירה, ונעשה העולם שמם. גמרא מפרש שזה קרה כיון שלא נהגו כבוד זה בזה. צריך ביאור למה זה הסיבה לעונש חמור כמיתה.
נראה לבאר שהפשט ב"לא נהגו כבוד זה בזה" הוא לא רק שלא כבדו זה את זה, אלא שגם לא חשבו על חבריהם כתלמידי חכמים וכמקיימי מסורת התורה. ממילא, לא יוכלו חבריהם להיות כן. אז, מחמת זה, הוצרכו למות, שבבני אדם כזה, לא יכולה תורה להתקיים.
נראה על פי זה לבאר מה קרה לתלמידי חכמים אחרים שבאותו זמן, כמו ר' אלעזר בן עזריה ור' יוסי הגלילי, ולמה היה העולם שמם כשמתו תלמידי ר' עקיבא. לא היו ת"ח באותו זמן, שאף שהיו לפני כן ולאחר כן ת“ח, הרי תלמידי ר“ע דרהרו עליהם שלא היו כל כך חשובים. אז, נעשה העולם שמם.
רואים יסוד חשוב: מה שאדם חושב על אחר ממש נותן שם לאותו אחר, כיון שהוא מה שחושב על עצמו, וזה עושה אותו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
חנוכה
א
קשה מאד איך החשמונאים היו יכולים לנצח נגד היוונים. הרי היוונים היו חיל גדול וחזק, והחשמונאים היו בני תורה חלושים. אז, קשה איך היו יכולים להילחם ולנצח.
נראה שהביאור הוא שחשבו על עצמם להיות מנצחים. ידעו שה' צריך לנצח להם, וזהו. לא היו צריכים יותר מזה, שכיון שחשבו על עצמם להיות המנצחים, ממילא היו בהם כח להיות מנצחים.
נראה שזהו הביאור של מה שאומרים ב"על הניסים." אומרים שה' נתן "גיבורים ביד חלשים." לכאורה, זה קשה מאד, ש"איזהו גיבור, הכובש את יצרו," ולא ראינו מעולם יווני שכבש את יצרו. אלא, נראה שרצה לומר שנתן מחשבה, נתן דרהר, של גיבור ביד חלש. עשה ה' שהחלשים חשבו על עצמם להיות גיבורים.
ואם תאמר הרי גם אומר, "טמאים ביד טהורים," ואיך אפשר לומר שה' עשה שיחשבו על עצמם לטמאים, נראה לפרש בדרך זה: קשה איך נקרא לגויים בשם טמאים. להיפך, גויים לא מקבלים טומאה, ולא נעשים זבים, ורק בני ישראל יכולים להיות טמאים. אלא נראה שצריכים גם לעיין למה בני ישראל מקבלים טומאה ואין גויים מקבלים טומאה. אפשר לומר שהוא מפני שלבני ישראל יש קדושה. מה שסותר אותו קדושה, אז, גורם טומאה. אבל לגוי, כמו לבהמה, אין קדושה כזה, ואז אין יכולת לטומאה. לכן, אף זה אומר שה' נתן להם אותו דרהר - ה' עשה שחשבו על עצמם להיות אנשים קדושים, עד כדי כך שטומאה שייך בהם.
כמו כן הוא ב"רשעים ביד צדיקים." ה' עשה שהחשמונאים חשבו על עצמם להיות אנשים שהם כל כך קדושים שכל מעשה שלהם לרע יכול לגרום רשעה.
רואים מזה שאם אדם חושב על עצמו להיות מאד חשוב, זה ממש משנה אותו.
אומר גמ' סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טוב, כמו יוסף.
ב
לכאורה, קשה למה היו בני ישראל צריכים למצוא שמן טהור כשחזרו לבית המקדש אחר הניצוח על היוונים. הרי טומאה הותרה בציבור, ואז היו יכולים אף להדליק שמן טמא, שזה גם כן היה כשר להם.
נראה שהטובה בזה היה שה' נתן לנו לעשות יותר ממה שהיינו חייבים לעשות. מה הטוב בזה? הטוב בזה הוא שכיון שה' גילה לנו נס בענין זה, אנחנו חושבים על עצמינו להיות אנשים שרוצים לעשות יותר, להיות אנשים שמתאווים לעבוד ה' ביותר. זה, באמת, מעלה גדולה, שמה שאדם חושב על עצמו מהפך אותו, ומשנה אותו להיות כן.
על פי זה, נראה לבאר למה יש שמנה ימים של חנוכה. נראה שאולי באמת היה ראוי שיהיו שבעה ימים. אבל, כיון שיסוד של נס חנוכה היה שה' עשה שאנחנו נרצה לעשות קצת יותר לה', ממילא הדרך לזכור חנוכה הוא לעשות קצת יותר לה', ולהוסיף יום אחד לה'.
רואים מזה שמה שאדם חושב על עצמו משנה אותו. אם חושב על עצמו לטוב, ממש נעשה איש יותר טוב. זה דבר שכדאי לזכור.
אומר גמ' סוטה שבא יוסף לבית פוטיפר לחוטא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך אביו שלו ראה אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים טוב, שאם יראו שאנחנו חושבים עליהם טוב, אף הם יחשבו על עצמם טוב, ויהיו טוב, כיוסף.
פורים
א
יודעים שכל אדם צריך לשתות ולשכר בפורים עד שלא מכיר בין ארור המן לברוך מרדכי. צריכים לבאר מהו ענין זה, ולמה רצו חכמים שתקנו מצווה זה נשכר עד כדי זה.
נראה לבאר שענין יום של פורים הוא שהוא יום של התחדשות. באותו יום, קיימו וקבלו היהודים את התורה ונתחדשו על ידי זה. לכן, פורים יש לו כח סגולי להתחלות חדשות, וזהו עיצומו של אותו היום. מפני זה הוא לפני אביב, שהוא זמן חידוש של העולם.
כיון שכן, אומרים ברוך אף על המן. מדרהרים אותו בדרהר חלוק עד שאומרים עליו שהוא ברוך, וזה סמל לשינוי. דרהר קובע מהו אדם - מה שבני אדם מדרהרים על בני אדם משנה מי הוא - וכיון שכן, כיון שאומרים ומדרהרים דבר חלוק על המן, ממילא הוא נשתנה. אז, זה סמל לשינוי של כל אדם שיש לו כח זה בפורים ועל כן תקנו חכמים מצות שכרות בפורים.
נראה שזה גם מבאר ענין ונהפוך הוא. והוא, שפורים הוא יום של התחדשות האדם, שאדם יכול להפוך את עצמו, ויכול לשנות אף את מידותיו.
גם מבאר ענין של מנהג ללבוש בגדים שונים בפורים. זה גם כן סמל של כח היום לשנות את עצמו.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
נמצא שני חידושים מזה: רואים שיש כח סגולי מיוחד ליום פורים לשנות ולחדש את עצמו. וגם רואים כח של דרהר, שדרהר משנה מי הוא אדם, עד שדרהר על המן לטוב הוא עושה שהמן טוב.
ב
גמרא (מגילה ז:) אומר שקם רבה שחטיה לרבי זירא במשתה פורים. קשה איך תלמיד חכם ישחוט תלמיד חכם אחר. נראה לי שני פשטים אמיתייים.
פשט ראשון הוא שלא ממש שחטו, אלא אמר לו פשט מנכפל במאה. כמובן, זה דומה כאילו שחטו.
פשט שני הוא שהיה רבי זירא אומר פשטים מנכפל במאה. כמובן, רצה רבה לשחטו.
סוף ספר
בסוף כל ספר אומר, "חזק חזק ונתחזק." צריך ביאור מהו כוונה של מילים אלו, ולמה אומרים אותם במקום זה.
נראה שהביאור הוא שאחרי גמר כל ספר, שהוא דבר גדול וקשה, שואלים איך סיימנו את כל ספר הזה, ואיך נוכל להתחיל ספר אחר.
לזה, משיבים שחבר אחד אומר "חזק," וחבר אחר אומר, "חזק" עד שממילא הוא נתחזק. הביאור בזה הוא שאם כל אחד ואחד אומר לך שאתה חזק ואתה יכול, אף שנראה קשה מאד, ממילא אף אתה תחשוב על עצמך כן, ותתחזק ותוכל.
רואים יסוד גדול מזה בכוח של מחשבות שלנו על האדם. רואים שיכולים לתת לו כוח לחשוב על עצמו לטוב ולהיות טוב.
אומר גמרא סוטה שכשבא יוסף לבית פוטיפר לחטוא באשת פוטיפר, בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
הערות
- עיין בגמ’ גיטין נז:, שאומר מעשה של ארוס וארוסה שלא חטאו, ומזכיר שבחם על יוסף, שהיה יותר קשה להם לעמוד בניסיונם. עיין במהרם שי"ף שם, שמקשה שיש עוד סיבה למה לא חטא יוסף - והוא שבא ליוסף דמות דיוקנו של אביו, אבל לא בא לאותו ארוס דמות דיוקנו של יעקב אבינו.
נראה לבאר שלא קרה שום נס ליוסף, ולא בא לו דמות של אביו, אלא בא לו במוחו דמות דיוקנו של עצמו, של אביו, שראה ודרהר על עצמו כמו שאביו ראה אותו. כיון שראה שאביו חשב עליו לאיש טוב שלא היה יכול לחטוא, הוא לא חטא.
אז, אין דבר שעשה שהוא יותר קל ליוסף, שמסתמא אף אותו ארוס היה לו מי שחשב עליו לטובה - והראיה הגדולה היא שלמעשה היה ניצול מעבירה. אז, היה שווה ליוסף בזה, ואף הוא ראה דמות דיוקנו של אחד.
- עיין בגמ’ ברכות, שאומר שצריך אדם לכוון את רגליו כמלאך בשעת התפילה. קשה, למה ידמה את עצמו למלאך. נראה שהביאור הוא שאם יחשוב על עצמו כמלאך, יהיה קצת כמלאך, וזה, כמובן, טוב בשעת תפלה.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו ולא חטא. צריכים אנו לבאר למה לא חטא - מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
* Footnotes
[fn:1] עיין בגמרא פסחים (סוף פרק שלישי).
[fn:2] דברים ל"א/י"ט. עיין שם
[fn:3] עיין שם
