1. בראשית
כתיב שה’ ברא את האדם בצלם אלהים ובדמות דיוקנו. צריך לבאר איך אדם יכול להיות בדמות דיוקנו של ה’ כיון שאין לה’ דמות. נראה לבאר ש"דמות דיוקנו של ה’" אינו אומר "הדמות שיש לה’,” שאין דמות לה’. אלא רצה לומר דמות דיוקנו של אותו איש של ה’, והוא שכמו שנראה ה’ לו, כן הוא האדם. מי שחושב על ה’, מי שמרגיש ה’, להיות אדון כל ולהיות אלהים ממש, הרי הוא דומה לו, ומקיים מה שאמרו חז"ל לדמות לה’, וקונה מדות אלו. להפך, אם אדם חושב על ה’ להיות מי שאינו חנון, אף הוא לא יהיה כן. אז, נמצא שמה שאדם חושב על ה’ יש לו כוח לפעול עליו.
אומר גמרא סוטה שבא יוסף לבית פוטיפר לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן דרשה דומה של "דמות דיוקנו.”
נראה לבאר הסיבה שמהות האדם תלוי בחושבו על ה’ שהוא שאם אדם חושב על ה’ להיות מי שאינו חנון, מדה כנגד מידה, לא יתן ה’ אותו מידה. אז, ה’ נוהג עמו, כמו שאמר גבי יוסף, כאילו אינו חנון, ועושה אותו דומה לה’ שאינו חנון. זה מפני שכשחושב על אדם, נעשה כך.
1. נח
** א
נח עסק בבניין התיבה לזמן רב, למאה ועשרים שנה. חז"ל מבארים לנו שרצה ה’ שיעסוק לכל כך זמן כיון שאז יראו אותו בני אדם. ישאלו לו מה עושה, ויגידו להם שיהיה מבול, ושצריכים לשוב. קשה; אחרי מאה שנה, לכאורה, ידעו כבר מה עושה, ואז לא יועיל בנינו.
נראה לבאר שלא היה רק כדי שיאמר להם שיהיה מבול, אלא כדיש יראו שיש מי שעדיין מנסה להשיב אותם. נמצא שהיה חושב עליהם לבני אדם שיכולים לשוב. כיון שכן, יוכלו לחשוב על עצמם לבני אדם שיכולים לעשות רצון ה’. אז, עדיין היה תקווה שישובו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
** ב
אמרו חז"ל שנוח היה מקטני אמונה. קשה להאמין איך מי שבנה תיבה למאה ועשרים שנה היה מקטני אמונה. גם קשה לומר שמי שטרח ה’ בעדו להצילו מן המבול אף לא האמין בה’.
שמעתי מאדם חשוב שהיה נוח מקטני אמונה בעצמו. לא חשב על עצמו להיות כל כך צדיק, ולא חשב על עצמו להיות יכול להציל את כל דורו.
נראה שזה מבאר דבר שהוא פלא גדול. קשה איך לא עשה אף אחד תשובה בימי נוח. נוח היה איש חשוב, והיה טורח ליותר ממאה שנה להציל בני אדם- איך אפשר שלא הצליח אף באדם אחד?
נראה שלא הצליח כיון שלא חשב על עצמו להיות אדם חשוב ואדם שיכול להצליח.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. לך לך
אברהם לחם עם ארבעה מלכים והיה יכול לכבוש אותם. מבאר גמרא בתענית (כא) שהיה לו עפר מיוחד ש,כשנזרק, היה נהפך לרמחים. קשה איך היה אברהם יכול לבטוח על נס כזה וללחום שלא בדרך הטבע.
נראה לבאר שהיה אברהם חושב על עצמו להיות מי שה’ עמו, ומי שה’ לוחם בעדו. כיון שכן, היה בוודאי נוצח, וממש לא היה לו יכולת שלא לנצח. אז, לא היה סומך על הנס, אלא היה פשוט לו שה’ יעזור בעדו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. וירא
** א
קשה איך היה יצחק יכול להסכים להיות עצמו נעקד; מי ימסור נפש כך על ציווי שלא היה נודע לו כלל?
נראה שהענין הוא שכיון שאמר לו אביו שהוא לקרבן, וכיון שהוא ראה אותו למי שהוא ראוי להיות קרבן, היה יכול לראות את עצמו לקרבן, היה יכול לראות את עצמו למי שראוי להיות קרבן
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
** ב
כשהגר נגרשה מבית אברהם הלכה במדבר, וכמעט מתה מחסרון מים. בא לו מלאך, וגילה את עינה וראתה את המים. הגר היתה במצב רע. אדונה, שהיתה הראביצין והמורה שלה, גירשה מביתה, והיתה במדבר. כמה פעמים, כשאדם במצב רע, כיון שחושב על עצמו לולא כלום, רגיל שלא לחשוב ששום טוב יכול לבוא לו. לכן, לא היתה הגר יכולה לראות המים. כשבא מלאך, גילה את עינה- גילה לה מה היתה באמת, ומיד ראתה את המים.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. חיי שרה
** א
אומר רש"י שרבקה באת ליצחק "והנה היא שרה.” קשה, שלא היתה שרה. יש פשטים דחוקים, אבל עושים שדברי רש"י הקדוש אינם מכוונים. אז, צריך ביאור איך יאמר תורה שהיא שרה.
נראה שהענין הוא שכשקוראים אנו בשמות לדברים, הם רק שמות שבני אדם מכנים. אז, אם כל בני אדם מכנים לה שם שרה, הרי היא שרה. נראה שכל בני הבית חשבו עלה להיות שרה, ולהיות אשה חשובה הראויה להיות אם של בני ישראל.
נראה שזה יבאר איך אשה שגדלה בפני רשעים כבתואל ולבן היתה יכולה להיות אם של בני ישראל. מפני שבני אדם חשבו עלה לאם, היתה יכולה להיות אם.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
** ב
אומר קרא שנפלה רבקה מגמלה. קשה מה קרה לה ליפול. נראה שהענין הוא שראתה יצחק, וראתה חשיבותו, ולא הכיר בחשבותה להיות נשואה לאיש כזה, ולכן נפלה. רואים מזה שאף שאחרים חושבים על אדם להיות חשוב, צריך אדם לחשוב על זה ולעשות שאף הוא חושב על עצמו כן.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
אף שיוסף היה כבר נחשב להיות חשוב, רואים שחז"ל דברו בגדולתו. לכאורה, צריך לומר שעשה דבר חשוב- ואותו דבר חשוב הוא שהיה יכול להוציא את הכוח ממה שחשבו עליו אחרים, ולעשות שאף הוא יחשוב על עצמו לטוב.
1. תולדות
קשה למה היה יצחק אוהב את עשו; אטו לא היה יודע שהיה יעקב איש תם יותר מעשו.
נראה שלא, באמת, החשיב את עשו יותר, אלא רצה שעשו היה צריך סיוע, ואז ניסה לחשוב עליו להיות איש טוב ואיש חשוב.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. ויצא
נתן יעקב לפני הכבשים מקלות כדי שיולדו כעין המקלות. צריך ביאור איך זה פועל על מה שיולידו.
נראה שהכוונה הוא שכשנתן יעקב אותם מקלות שם, הכירו שהיה חושב עליהם לכשבים עם יחס לנקודים או כדומה. כיון שחשב עליהם כך, הולידו נקודים, כמו שהיה יעקב חושב עליהם.
אם לבהמה כך, לאדם על אחת כמה וכמה. כיון שאדם חושב על חבירו להיות טוב ולהיות צדיק, ממילא נעשה כן.אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. וישלח
יעקב לחם עם המלאך כל הלילה, וכבש אותו. אחר כך, קרא לשם של אותו המקום ”פנואל“ כיון שראה ה‛ פנים אל פנים וינצל נפשו. יש להעיר שלכאורה, עיקר של מה שקרה שם היה שאף שהיה קשה לו, נתנצל נפשו. אם כן, היה לו לקרוא לו ”נצל“ או כדומה, ולא על שם שראה ה‛ פנים אל פנים.
נראה שיש לדון למה אומר לשון ”פנים אל פנים,“ ולא לשון ”פנים אל ה‛,“ שלכאורה, אין פני ה‛ בו. נראה שיש לבאר שאין הענין רק שהוא קרוב לה‛, אלא שמכיר מה שה‛ מדרהר בו. זהו פנים אל פנים- פנים של אדם קרוב לפנים וראיית ה‛, ויכול להכיר בו.
על פי זה, נראה לבאר שמה שהיה יכול יעקב ללחם עם מלאך היה מפני שהיה יכול להכיר את עצמו לאיש חשוב. היה יכול להכיר את עצמו כך כיון שראה ה‛ פנים אל פנים- ולכן ”וינצל נפשי.“
על כן, קרא לאותו מקום פניאל, שזה היה הסיבה להצלתו.אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. וישב
** א
אומר קרא שכשירד יוסף למצרים, ירד עם עגלות שהיו בהם בשמים. קשה מה לנו שהיו שם בשמים. גם קשה מה לו ליוסף שהיו עמו בשמים- הרי הוא הולך למקום קשה של מצרים, ולחיים קשה של עבד- ועכשיו מריח בשמים. לכאורה, אין זה מנחם גדול לו.
יש לומר שמה שעשה בשמים הוא שעשה שהיה יכול יוסף להכיר שה‛ היה עמו. אף שלא היה ה‛ עושה שלא הלך למצרים, על כל פנים, היה עוזר לו קצת, והיה מראה לו שהוא עמו.
נראה שמה שזה היה חשוב ונצרך. כיון שהיה יוסף יכול להכיר שה‛ היה עמו, היה יכול להכיר שהוא אדם חשוב. האחים כבר דנו עליו וחייבו אותו מיתה, ועכשיו הוא משתלח למקום טומאה של מצרים. איך יהיה יכול לחיות חיים של רוחניות שם.
כיון שהכיר שה‛ היה עמו, אז היה יכול לראות את עצמו כמי שהוא נאהב של ה‛. כיון שהיה מכיר את עצמו כך, ממילא היה ישיבתו במצרים ישיבה אחרת- היה ישיבה של בן יעקב במצרים, ולא רק ישיבת עבד במצרים.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
** ב
יוסף חלם חלומות, ואמר אותם לאחיו. אמרו לו, ”המלך תמלך עלינו אם משל תמשל בנו.“ שמעתי שיש מקשים למה כופל ”המלך תמלוך,“ ולמה כופל, ”המשל תמשל.“
נראה לבאר שאמרו ליוסף, ”אם אתה מולך- חושב על עצמך למלך- אז מלך עלינו.“ זה אומר שהגידו לו שכדי להיות מלך, נצרך שיחשוב על עצמו למלך. אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
נראה שלכן אחר שבאו אחים למצרים, הודו לו למלוך עליהם. הכירו שכבר חשב על עצמו לאדם חשוב ולמלך, שבזה ניצול מעבירה, ואז היה ראוי למלוך עליהם, כמו שאמר, ”המלך תמלך עלינו.“
** ג
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. מקץ
קרא אומר שראה פרעה בחלומותיו פרות שהיו רעות מראה, והיו אוכלות את הטובות, וזה היה פלא. לכאורה, לשון "רעות מראה" קשה, שרק צריך לומר שהיו רעים.
נראה שאותו פסוק אומר שהיו רעות מראה- לעצמם, שהיו רעות לתוך מראה שהיו רואים על עצמם.
הפלא היה שיאכלו את הגדולים אף שחשבו על עצמם להיות חלושים. כיון שראה פרעה את זה, ידע שדבר כזה אי אפשר, הוא כפיל ההולך לתוך נקובת מחט, וצריך להיות סימן מן השמים.
רואים מזה יסוד: מה שאדם חושב על עצמו הוא חשוב מאד. לא היו פרות, באופן רגיל, אפשר לאכול פרות אחרות כיון שראו על עצמם מראה רע.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. ויחי
אמרו חז"ל (תענית) ש"יעקב אבינו לא מת.” קשה לומר שיעקב ממש לא מת, שהרי הפסוק אומר שקברו לו. אז, צריך לומר שמת. אם כן, צריך ביאור מה אומר גמרא זה כשאומר שיעקב לא מת.
נראה שהיה ליעקב הבטה מיוחדת על בני ישראל. היה לו כוח לדרהר בני ישראל. מפני זה, אנו נקראים בני ישראל, ולא בני אברהם או בני יצחק. היה יעקב יכול לדרהר אותנו, ואותו דרהר שהיה חושב עלינו היה מה שעשה אותנו לעם של תורה ועם של ה’.
וזהו מה שאמרו חז"ל שיעקב אבינו לא מת. גופו מת, אבל אותו הבטה שהיה לו על בני ישראל עדיין חי וקיים, שמחמת מה שהוא דרהר על בני ישראל, בני ישראל, אף היום, מדרהרים כן על עצמם. אז, לא מת.
רואים במקום אחר אותו כוח מיוחד של הבטה שהיה לעיקב אבינו:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. וארא
גמרא (פסחים) אומר שחנניה מישאל ועזריה נשאו קל וחומר מן הצפרדעים שהפילו את עצמם לאש, אף שלא היו מצווים. צריך לבאר איך היה להם הכוח להפיל את עצמם לאש בלי שום ציווי; איך היו יכולים לחזק את עצמם להרוג על עצמם כשלא היו מחוייבים על זה.
מהרש"א שם מבאר שיש יותר מעלה על פי מה שהיו צפרדעים. צפרדע הוא דבר שחי בימים ובמים. אש הוא הפוך של מים. אז, היה קשה לו ביותר להפיל את עצמו באש, שהוא הפוך של מה שמחיה אותו. אבל, בהמה וחיה אחר, שחי ביבשה, לא היה כל כך קשה לו, שאין אש הפוך של חייו.
לכאורה, המהרש"א הוא קשה להבין. מה שהוא קשה בהפלה לאש אינו מה שהוא הפוך של מה שמחיה אלא הוא מה שממית. לכאורה, לכל בהמה האש ממית. אז, קשה מהו הייתור גבי צפרדעים.
נראה שצריך לומר שהסיבה שהיו יכולים לזרוק את עצמם לתוך האש הוא שכיון שידעו שה’ רצה שיהיו בתוך האש, היו מדרהרים את עצמם להיות בתוך האש. כיון שכן, ממילא היה קל לזרוק את עצמם בתוך האש, שכבר היו נדרהרים כן.
זה יבאר גם כן המהרש"א. המעלה של צפרדעים היה מפני שיותר קשה להם לדרהר את עצמם להיות בתוך האש, כיון שהיה האש הפוך של מקום חיותם. אז, היה מעלה יותר גדולה בצפרדעים.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. בא
קרא אומר שבני ישראל אכלו מצה בהיותם במצרים. קשה, שמצה הוא לחם שאוכלים לשמח על יציאת מצרים וחירות שלנו. אם כן, קשה איך אכלו אותו כשהיו במצרים.
שמעתי פשט נפלא: בני ישראל כבר דרהרו על עצמם להיות בני חורים. מפני זה גופא היו נעשים בני חורים, שכיון שדרהרו כן על עצמם, ממילא כן נעשה.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
1. בשלח
תורה מבאר שלא היה הים נקרע עד שהתחילו בני ישראל לבוא במים. קשה למה צריכים לזה, ומה עשה ביאת בני ישראל במים.
נראה לבאר שהענין היה שהיו בני ישראל צריכים לדרהר את המים כאילו כבר נקרע. כיון שכן, ממילא היה נקרע.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
יש להוסיף שדורשים שים ראה ארונו של יוסף ואז נקרע. קשה מה ראה מארונו של יוסף. נראה שהכיר מארונו של יוסף מושג זה של חשיבות של דרהר. כיון שכן, הכיר שמוכרח הוא לקרוע על פי דרהר של בני ישראל.
1. יתרו
אחד מן עשרת הדברות הוא שלא לגנוב את הנפש. כל מה שהוא בתוך עשרת הדברות הוא או דבר שהוא מיסודי יהדות, כמו עבודה זרה, או דבר שהוא מיסוד היותינו לעם, כמו רציחה (שאי אפשר להיות עם שכל אחד רוצח מי שירצה). קשה למה גניהת נפש אחד מן עשרת הדברות.
נראה שאין האיסור רק במה שעושה אחד לעבד; האיסור הוא במה שרואה כל אחד ואחד וחושב אם יוכל לגנוב אותו. זה עושה שחושב על כל אחד ואחד להיות עבד. כיון שחושב על כל אחד להיות עבד, אותו אדם קצת מורגש, ואף הוא מתחיל להיות קצת כמו עבד.
אז, צריך להיות מתוך עשרת הדברות, שהוא דבר חמור מאד, ושהוא דבר ששייך להזיק בו כל כך כמה בני אדם.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו הוא חשוב מאד. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
1. תרומה
יודעים שעל הארון היו כרובים. גמרא מפרש שכרובים היו ציורים של קטנים, והיו מחבקים זה את זה להראות חיבת ה’ לישראל. צריך לבאר למה במקום הכי קדוש ובהראת אהבת ה’, נקט קטנים.
נראה לבאר שקטן הוא מי שמגדיל, הוא מי שלא רק די לא להשאר במצבו, אלא רוצה ומנסה להיות יותר גדול, וכמעט בעל כרחו נשתנה ומגדיל. ועוד, שאין קטן מי שהיה לפני שנה. אם היה, לפני שנה, צועק בכל זמן, אולי אחר שנה, יהיה כבר יותר כגדול, ולא יצעוק כלל. כך אומר הכתוב כשאומר "נער ישראל ואהבו.” ישראל הם לעולם גודלים, ולא ממעטים את עצמם מפני מה שחטאו לפני שנה. לכן, הכרובים הם קטנים.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
יש לדון מה ראה אביו ביוסף שגרם שלא היה יוסף חוטא. נראה לבאר שידע יעקב את יוסף רק כשהיה נער (עד שהיה בן שבעה עשר). אז, נראה שראה יוסף מה שחשב עליו אביו לנער, להיות אדם שהוא לעולם משתנה, ולעולם גודל. כיון שראה זה, היה יכול להציל את עצמו מחטא.
1. ויקרא
הפסוקים מבארים קרבן מנחות. כשאדם מביא מנחה, אומר קרא שמבלל אותו. מבאר גמרא שאין בילה מעכב, אבל אף שאין בילה מעכב, צריך להיות ראוי לבילה: כל הראוי לבילה, אין בילה מעכבת בו, וכל שאינו ראוי לבילה, בילה מעכבת בו.
העיר הגאון הרב הראש ישיבה שליט"א שמשמע שמה שמעכב אינו רק שאינו אפשר ליבלל, אלא הבילה עצמה. קשה, אז, ל"ל מעכב הבילה כשראוי לבילה.
נראה שהפשט הוא שצריך בילה- בילה לעולם מעכב. אבל, כיון שהוא ראוי לבילה, יכולים אנו לחשוב עליו- והוא עצמו יכול לחשוב על עצמו- שהוא נבלל. אז, כיון שהוא ראוי לבילה, יש בו בילה ממילא.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
1. קדושים
אומר קרא, “ואהבת לרעך כמותך.” צריך לבאר מה בכלל מצווה זה. נראה לבאר שאין המצווה רק לאהוב את חברך כעצמך; אין זה שייך, שאין אדם יכול לאהוב את אחר כעצמו ממש. אלא נראה שהדרך לקרא קרא זה הוא שאומר שצריך לאהוב את חברך- ואיך עושה כן? כמותך! תחשב עליו כמו שאתה חושב על חברך. כמו שאדם חושב על עצמו ומכסה פשעיו, כך תחשב על חברך. ואיזה אהבה יש בזה? יש אהבה גדולה בזה, שכשאדם חושב עליו לטוב, יחשב חברו על עצמו יותר לטוב. כיון שחושב על עצמו לטוב, יהיה יותר טוב.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו הוא חשוב מאד. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
1. שלח
אמרו מרגלים, “ונהי בעינינו כחגבים, וכן היינו בעיניהם.” קשה איך ידעו מה היו בעיני בני ארץ כנען. שמעתי משום גדול הדור אחד[fn:1] שתחלת הקרא מפרש סוף הקרא. כיון שהיו בעיניהם כחגבים, חשבו שכן היו בעיני מרגלים. מה שאדם חושב על עצמו חשוב הוא, שגורם איך יחשב על דברים אחרים ו,על פיהם, איך ינהג.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
1. בלק
כשקוראים פרשה זה, חייבים אנחנו להקשות איך היה שבלעם, שזכה לנבואה עצומה, היה איש כל כך רע, ואיך חטא נגד ה’ כל כך. נראה שיש לבאר על לפי קושיא אחרת. הפסוק קורא לבלעם "שתום עין,” שהיה סומא בעין אחד. קשה למה אומר לנו זה; מה לנו ביכולתו לראות.
נראה שלא אומר שהיה ממש סומא, אלא סומא בראיית פרספקטיב שלו, שהיה ראייתו על עצמו סמוי, שלא היה רואת את עצמו לטוב- וזהו מה שגרם שהיה כל כך רע. אף אם אדם מדבר לשכינה, הוא רק יכול להיות צדיק אם יכול לראות בעצמו טוב.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
1. שופטים
כשזקנים עוסקים בעגלה ערופה, חייבים לומר, “ידינו לו שפכו את הדם הזה.” קשה מהו ההוה אמינא שהזקנים הרגוהו.
באר האלטר מקאלם שהענין הוא שאילו היו מלווים אותו ונותנים לו מזון וצידה לדרך, היה רואה בעצמו שהוא אדם חשוב כיון שזקני העיר כבדוהו כל כך. כיון שהיה רואה על עצמו חשויבות זה, לא היה נהרג- היה בורח או היה רודף את רודפיו. כיון שלא חשבוהו למכובד וחשוב, לא היה יכול לחשוב כן על עצמו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
1. כי תבא
אומר קרא שקללות של תוכחה באים "תחת אשר לא עבדת את ה’ אלקיך בשמחה ובטוב לבב.” קשה איך ייענשו עונש חמורה כזה על עבירה קלה כזה- עשו את המצוות, אבל רק לא עשו אותם בשמחה.
רב משה פיינשטין שאל שאלה עצומה: ידוע שבאו כמה יהודים לאמריקא ומסרו נפשם בעד שבת ובעד יהדותם. למעשה, לא היו בניהם לבסוף יהודים דתיים, אלא התנכרו מיד. צריכים לשאול איך זה קרה.
באר רב משה שקרה כיון שהיו אביהם שמסרו נפשם כל כך אומרים, “איז שבער צו זיין א איד,” ולא, “איז גשמק צו זיין א איד.” כיון שמעו שלא היה שמחה ביהדות, הבנים נתנכרו.
על פי זה, יש לומר שאם אדם לא עובד את ה’ בשמחה, עומד עבודתו להיבטל. כיון שכן, בני ישראל נענשים על זה.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. צריך לבאר איך ראה אותו אביו. נראה לבאר על פי המשך של הגמרא. גמרא ממשיך לומר שאמר לו אותו דמות שאם יחטא, יהיה שמו מחוי מן החושן. קשה, לכאורה, מה לו בזה; אין מצווה להיות החושן. גם לא מסתבר שיוסף הצדיק ירצה בכבוד כזה. אז, נראה שהענין היה שדמותו שהראהו יעקב היה של איש חשק למצוות, איש שהיה שמח במצוות, איש שרצה במצוות לא כיון שצריך, ולא כדי ליטול שכר או כבוד, אלא אך ורק מפני שהם מצוות. כיון שהכיר יוסף שאביו חשב עליו לאיש כזה, אף הוא היה יכול לחשוב על עצמו לאיש כזה, והיה יכול לעמוד כנגד יצרו ושלא לחטוא.
1. וילך
כתיב בפסוק, ,ואתה כתבו לכם את השירה הזאת….” תמוה הוא למש שינה מלשון יחיד (אתה) וללשון רבים (לכם). יש להסביר שכל אחד ואחד צריך לכתוב. לכן, אומר לשון יחיד. אומר לשון רבים כיון שבכתיבת התורה, ובאמת, בכל קיום התורה, אפשר שרק על ידי מה שבני אדם אחרים חושבים עליו להיות איש שמקיים מצוות. אם חברו חושב עליו לטוב, ורבו חושב עליו לטוב, ואשתו חושב עליו לטוב, אז- ורק אז- יכול לקיים מצוות. לכן, אומר כאן לשון רבים- מקיים מצווה רק מפני שהוא מורכב ממחשבת כמה בני אדם עליו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
1. פורים
יודעים שכל אדם צריך לשתות ולשכר עד שלא מכיר בין ארור המן לברוך מרדכי. צריכים לבאר מהו ענין זה, ולמה ירצו חכמים שתקנו מצווה זה שלא ידע בין ארור המן.
נראה לבאר שענין יום של פורים הוא שהוא יום של התחדשות. באותו יום, קימו וקבלו היהודים את התורה ונתחדשו. פורים יש לו כוח סגולי להתחלות חדשות, וזהו עצומו של אותו היום. לכן הוא לפני אביב, שהוא חידוש של העולם.
כיון שכן, אומרים ברוך אף על המן. מדרהרים אותו בדרהר חלוק עד שאומרים עליו שהוא ברוך, וזה סמל לשינוי. דרהר קובע מהו אדם- מה שבני אדם מדרהרים על בני אדם משנה מי הוא- וכיון שכן, כיון שאומרים ומדרהרים דבר חלוק על המן, ממילא הוא נשתנה. אז, זה סמל לשינוי של כל אדם שיש לו כוח לו בפורים.
נראה שזה גם מבאר ענין ונהפך הוא, והוא שפורים הוא יום של התחדשות האדם, שאדם יכול להפוך את עצמו, ויכול לשנות את מדתו.
גם מבאר ענין של מנהג ללבוש בגדים שונים בפורים. זה גם כן סמל של כוח היום לשנות את עצמו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
נמצא שני חידושים מזה: רואים שיש כוח סגולי מיוחד ליום פורים לשנות ולחדש את עצמו. גם רואים כוח של דרהר, שדרהר משנה מי הוא אדם, עד שדרהר על המן לטוב היה עושה שהמן טוב.
גמרא (מגילה) אומר שקם רבה שחטיה לרב זירא במשתה פורים. קשה איך תלמיד חכם ישחוט תלמיד חכם אחר. נראה לי שני פשטים אמיתייים.
פשט ראשון הוא שלא ממש שחטו, אלא אמר לו פשט מנכפל במאה. כמובן, זה דומה כאילו שחטו.
פשט שני הוא שהיה רב זירא אומר פשטים מנכפל במאה. כמובן, רצה רבה לשחטו.
ויקהל- נדיב לב
תרומה- כרובים
ספירה- ר’ ויליג
ראה אהרן הטוב בכל
יונתן של leader (חטא משה, ויקח רומח, אליהו)- יהושע היה מיוסף
במקום אשר ישחט את העולה
אספקלריה המאירה
שלש רגלים- דיוקנן (ירושלמי)
פשט של מרדכי גרווס
* Footnotes
[fn:1] עיין בגמרא פסחים (סוף פרק שלישי).
