* ב.
** יש לדון
אם פסול חטאת ופסח שלא לשמם שווה. גם יש לדון אם הוא שווה למה שגורם שאין שאר קרבנות עולים לבעליהם (ואף שם, יש לדון אם כל אותם קרבנות שווים). ונכתב, אולי, קצת צדדים.
יש לדון למה לא יעלו.:
1. אפשר שכיון שכהן, שהוא חשוב לענין אותו קרבן כיון שהוא המקריב אותו, חשב עליו להיות קרבן אחר, נעשה קצת אותו קרבן אחר. אפשר שלא עולה כיון שהוא אותו קרבן אחר (דהיינו, שמה שהוא קרבן אחר עושה שאינו קרבן זה),ואפשר שנפסל כיון שאינו קרבן זה (דהיינו, שאין לא שם גדול של אותו קרבן, אבל גם אין לו שם גדול של קרבן זה) ואפשר שנפסל כיון שהוא שני קרבנות (רצה לומר, שמה שיש סתירה בשמו פוסלו. כיון שיש קצת פסול, אינו יכול לרצות כל כך. גם אפשר שכיון ששינה ממה שהיה כשקדשו בעל (או ממה שרצה בעל), אינו כל כך מיוחס לו. ויש לדון, שאם היה מרצה בלי זה, אין זה חליוק חשוב, לכאורה, שלא מונע ריצויו. ואולי ימנענו קצת.
2. גם בזה יש לדון אם הבעיא הוא שדעת זה רע או שיש צורך לדעת בעת הקרבה. זה שייך לגמרא דסתמא לשמה. ותחשב.
3. אפשר שכדי לכפר צריך דעת כהן שיעשה תכלית הקרבן. כיון שחושב עליו להיות קרבן אחר, אין אותו דעת.
לכאורה, התנא שתולה אותו בלמה מחשב משמע כצד שני, שאז יש לומר שיש שני שמות, ולהיות לו אלו הוא רע. לשני, קשה. נראה שיש לומר שכפרת אלו חלוק, אבל כפרת שאר קרבנות שווה, ואז במחשבה על זה, מכפר על זה. ותחשב.
נראה שאף יש לדון אם יש בעיה בריצוי (שאינו מרצה כל כך או שמרצה באופן חלוק) או בעיה בכפרה (שריצוי גורם כפרה. אולי כאן, אי אפשר לגרום כפרה. ותחשב. ועיין לקמן.). ועיין בשיח שי על רש"י כאן.
** למעלה מהם -
נראה שיש לבאר במחלקותם כזה:
נראה שיש לדון אם יש ריצוי חלוק מחטאת לעולה או שיש אותו ריצוי, אלא שכיון שה’ ברצון, יכולים לשאול דבר ממנו. מה ששואלים- מה שאותו ריצוי גורם- הוא חלוק. אולי זה ביאור אותו מחלקת. שמעון סובר שכיון שיש בכלל ריצוי מה שלמעלה ריצוי של מה שלמטה, אין בעיא לחשוב עליו. חכמים החולקים אומרי שיכול להיות שמחשבה על שלמעלה פוסל כיון שריצוי חלוק. (אינו מוכרח כלל כמובן.)
** לישני כל הני -
יש לדון איך נבאר סברה זה לצד שלישי שבראשון. לשאר צדדים, מובן הוא, שאומר שמוסיף לעשות יותר שם לקרבן אחר. לזה, קשה, שכבר יש סתירה בשמו. אולי אם חלק משמו שסותר חלק אחר הוא יותר חשוב (הוא חלק יותר גדול מן השם), יש יותר בעיה. יש לדון, שאז מה שנסתר אינו כל כך חשוב. ותחשב.
נראה שגם יש לדון מהו צד שני של גמרא, ולמה לא נאמר כצד זה. אפשר שלא חולק, ורק אומר שיש עוד טעמם מקרא, והוא יותר פשוט (כיון שהוא מקרא, ואין צורך לדון בסברותינו). יש לדון, אז, למה צריך קרא. אולי כמו שמה שנלמד מקל וחומר נכתב בפירוש, כך מה שנלמד מסברה נכתה. ויש לדון. גם אפשר שחולק על הסברה. אולי סובר כצד שלישי שבראשון. נראה שגם אפשר שאומר שאף שרבה את פסולו, וגורם ביותר שלא יכפר, אין זה הבעיה, או מפני שכבר אינו מכפר כלל, אולי, או מפני שכבר חייב להביא שני, ואז, בין כך ובין כך יכפר. ותחשב.
* ב:
** הא סתמא -
יש לדון בדיוק זה (עיין לקמן שנדחה, אבל אנו דנים רק בהוה אמינא ללמוד ממנו), שמשמעות מילים ממש הוא שנזבחו, אבל לא לשמן. אם כן, אולי כולל סתמא. נראה שאז צריך לומר שלא נזבחו לשמן (יש לדון למה דרך זה יותר נכון- ולהיפך, הוא קצת vague, שכולל ציור שלא נזבחו כלל.). אלא צריך לומר שנזבחו לשם דבר שאינו שמם.
** לשם זובח -
מעניין שבעל נקרא זובח, שאינו צריך להיות שוחט. אולי לעולם נשחט לו (מי ששוחט הוא שלוחו, כיון שיכול זר, ואז יכול לעשות לשוחטו), והוא כמו מה שכהן זוכה בהקרבת קרבנו, שאף ישראל זוכה במה שיכול לעשות. ותחשב.
** רמי -
יש לדון בזה, שיש לדון למה לא נאמר שחלוקים החלותים, וחלות זה צריך דעת וזה אינו צריך דעת (ויש רק בעיה כיון שיש חושב לדבר שאינו נכון). ותחשב. ובאמת, צריך ביאור מהו מצד לשהשוותם; צריך לומר שלא מניח שפסולו הוא כיון שלא יכול לכפר כיון שלא חישב עליהם, שהרי אם כן, פשוט לחלק אולי סבר שפסולם הוא רק מפני שאדם חשב עליהם שלא לשמן. אולי סבר שמה שלא אמר שחשב לשמם הוא קצת הוכחה שאינו כן, ושחשב עליהם שלא לשמם. ויש לדון. ותחשב.
** שלא לשם אישות -
עדיין קשה, שהוא רק סתמה. נראה שני דרכים ליישב את זה:
1. אפשר שאף אם אין צריכים דעת בפירוש לספיסיפיק שלו, צריך דעת לג’נרל. תחשב על זה, למה זה יהיה.
2. אפשר שאומר שנכתב לשם דבר אחר, והוא שלנכתב ללמד. לשון גמרא (“לא איכתוב לשם כריתות כלל") לא משמע כן. וצריך ביאור למה לא נאמר כן. ותחשב.
* ג.
** דילמא שאני התם דאינתיק -
לא הבנתי כלל מהו ההוה אמינא להביא ראיה, שכיון שהוא לשם אשה אחרת, הוא ממש שלא לשמה, ואינו סתמה. ונראה שסבר שלא לשמה יהיה שכתבו וחשב שלא לגרש אשה זה. כאן, בא אותו מחשבה רק מדיוק (אגרש זה, ואז ממילה… ). ויש לדון, שלכאורה, אף בזבח כן הוא, שלכאורה (וכן אמרש"י במשנה) מכוון בעולה לשלמים, ולא שלא יהיה עולה. ותחשב. ונראה שאולי לא רק כיוון שיעשה כפרת עולה, אלא כיוון שיהיה עולה, ועולה הוא, בהכרח, לא שלמים. כאן, אם היה חפץ מיוחד של גט של זה וחפץ אחר של גט של זה, אז היה דומה, ויש לומר שכיון ששני החפתים בשמם חלוקים, אינו לשמה. אבל אינו כן, ואז אולי יש צד שהוא נחשב לשמה. ותחשב.
גם יש להעיר שמה שלא חשב שיהיה לזה דווקא הוא, לכאורה, קשה לצדדים שכתבנו. צריך לומר שמה שמכוון שלא יהיה לו אותו הרצאה או אותו שם הוא הבעיא (ולא, למשל, שמה שחושב שיהיה לו שם אחר נותנו אותו שם, וממילא נשתנה שמו. ואוליעדיין יכול לומר שאין לו שם זה כיון שחשב שלא יהיה לו). ותחשב.
נראה שאולי יש עוד צד, והוא שאולי פסול חלוק ביניהם, ובאשה בא ממה שלא חשב לאשה (תחשב מהו הפסול), ובזבחים בא ממה שחשב לדבר אחר. רק דן אם מחשבה של סתם נחשב לאותו דבר הפסול (מדלא חשב לדבר שמכשיר, כמה שכתבנו לעיל.). ותחשב.
** אינתיק לאחר -
יש לדון אם זה אותו פסול של שלא לשמה (או שמשנה שם או שכיון שחושב שלא יהני לזה, לא מהני) או פסול אחר. כמובן, ייתלה במהו הפסול (שאפשר שפסול זה (אינתיק) הוא או שיש לו שם של גט של פלוני, ואפשר שגמרא מחדש עכשיו שבזה נחשב שכיוון שלא לזה. ותחשב.)
יש להעיר שממה שגמרא שוב מקשה ומתרץ ששאני כיון שאינתיק לההיא (ולא לההוא) משמע שאינו אומר שממה שהוא כבר לזה (ואז אי אפשר להיות אף לזה) נחשב שכיוון שלא יצא בו, שאז פשוט שאין לחלק בין אינתיק לההוא לאינתיק לההיא. יש לדון או שביאור התשובה משנה במסקנא או שאין הכי נמי, ושניהם אותו תירוץ, והוא כמו שמצינו בכמה מקומות שיקשה גמרא דבר, אף שכבר אמר מה שיתרץ אותו. ותו"ת.
** שאין ברירה -
לכאורה, צריך ביאור מה זה אומר, שאין ברירה רק עושה שאין סיבה לחול כיון שלא אמר על דבר ספיסיפיק (שרק אמרו על דבר שיש בו קרק’ של אחר כך). אם כן, שווה הוא לסתמא. נראה שמשמע כמה שמפרש רש"י בברירה (וכן אומר כאן בפירוש בביאור זה), והוא שאם אין ברירה, הוא מפני שחוששים שכיוון לחלות אחד, ואולי מה שלו כיוון אינו החלות הנכון.
עדיין צריכים לבאר למה אין אומרים מה שאומרים בברירה אף בסתם. אפשר שסתם משמע שלא חושב עליו כלום (ויש לדון, שלכאורה, אין זה כל כך מצוי. ויש לדון.) גם יש לומר שצריך להיות שאומר מה איזה שחשב עליו. אז, אם אומר דבר שיכול לפרש להיות חפץ מיוחד, כמו בברירה, יש בעיה, אבל אי לא, אינו אומר חפץ.
* ג:
** מינו -
מעניין שנוכל לדמות פסול מחשבת של קרבן למחיצת כלי שטף. נראה שדן אם יש יכולת לחפץ להיות לו שני שמות כיון ששני מינים חלוקיים הם. נראה, אז, שבשוחט לחולין, בא לו שם חולין קצת, אבל זה לא מונע שם חטאתו, שחטות אולי מפרשו על דרך אחר של חולין, שחולין הוא מי בעליו, וחטאת הוא איזה הרצאה יכול לעשות (ואף שאין חולין עושה שום הרצאה, אולי אין זה עיקר שמו). גםם במחיצה שבכלי כן, שמקום מה שבתוכו יש לו שם על פי מחיצה ועל פי הכלי. ותחשב.
** קרא -
קשה ללרבנן למה כאן צריכים קרא וכאן לא צריכים.
** צריך ביאור מהו ההוה אמינא
של גמרא להקשות מ"תוכו
; הא פשוט הוא שאין קל וחומר מוציא מקרא. ואולי רצה לומר שעל כל פנים עושה קרא לאו דווקא (שאין קרא מוכרח להיות נגד קל וחומר). ויש לדון.
* ד.
** שכן… בפסח -
יש לדון למה שחיטה פוסל באלו בפסח, אם הוא מדין שחיטת קדשים (ששחיטה חשובה מפני שהוא זמן חשוב להקרבתו לקרבן) או שחיטת פסח (שהוא זמן חשוב לאכילת פסח). משמע מגמרא זה כראשון. יש לדחות שאולי הוא מסופק, אבל אין ללמוד ממנו מחמת הספק. ותחשב. ונראה שעל פי זה נוכל לפרש למה אין אומרים שזה יוכיח לומר שאף שאין שחיטה אסור בזרים, כל זה אכנים, והוא שאפשר שאינו יותר קל לפסול קרבן על ידי מחשבת שחיטה. ותחשב.
** נפסלת -
עיין בב"ח. נראה שתלוי במה שיש לחקור אם על ידי מחשבה פוסל שחיטה או פוסל כל הזבח. וצירך לחשוב.
** קרויה -
יש לדון מהו הלימוד:
1. אפשר שדורש ממה שנקרא שלמים שהוא מין שלמים. והוא שמחשבה על שלמים מהני כיון שחשב על כל מה שצירך לחשוב לתודה. (יש שני דרכים לבאר את זה:
  1. אפשר שאומר שתודה בכלל שלמים. אז, כשב על כל עניני תודה כשחשב על שלמים. זה מחודש, שנאכל לזמן יותר מועט, ואז מסתבר לומר שיש לו יותר קדושה. יש לדון, שנאכל קודם כדי שיפרסם נס.
  2. אפשר שאומר ששלמים בכלל תודה, דהיינו שאין בתודה מה שיש בשלמים. אולי זה גורם שלא יפסל. ותחשב.
2. אפשר שדורש שהוא כעין שלמים לדין, והוא לדין זה, שיכול לחשוב לשלמים.
3. אפשר שאומר שמילת שלמים כולל שניהם. כיון שכן, כשחושב לשם "שלמים,” הוה כסתמא, שלא חושב, בהכרח, שלא על תודה, שאולי "שלמים" שעליו חושב הוא תודה. ותחשב.
* ד:
** כלל ופרט -
קשה, שאי אפשר שבא לרבות רק שחיטה, שכבר אמר שחיטה. ואולי בא למעט זריקה (שמשמע שיש מקור לו). ויש לדון למה לא ימחק שניהם. ואולי סובר שיש שום דרשה מקרא של זריקה.
** שקולין -
נראה שיש שני צדדים (ואולי זהו שני הלשונות), והוא שיש לדון אם הענין הוא שמרבים הכי דומה, ואף ששנים אלו דומים באופן חלוק, שניהם הכי דומים, או שהוא שספק הוא איזה לרבות, ולא היה עושה כן תורה אם לא שרצה לרבות שניהם (שבכל ספק בדרשה מחמירים. ועוד שאין להקל, שאז היה לו לומר רק שחיטה, ולא כופו"כ). ותחשב.
** יש עמו דמים -
לכאורה, זה מוכיח שחלות שעושה הוא חלות שטוען יותר, שאף טוען יותר מקרבן אחד. גם היה צד לומר שכיון שקרבן הוא בכלל של קרבנות אחרים (הוקרב עמהם), יש יותר בעיה כשנשנה (רצה לומר, שיש לו כמה שמות (ואף שכלם של אותו בעל. ויל"ד.), ואז, יש יותר בעיה בהוספת שם רע לו. ותחשב.
** לייפסלו -
קצת קשה למה נחשב כן. לכאורה, כיון שהוא דבר שבקדשים, ולא נשנה, ההוה אמינא יהיה שהוא רק דין לכתחילה (ואף יכפר). ותחשב.
שוב ראיתי בתוספות. יש להעיר שאף אי מעכב, צריך מקור שלא רק מעכב כפרה, אלא פוסל. (ויש לדון מה נניח אם אומר שני קראי.)
* ה.
** רמי ריש לקיש -
צריך ביאור למה היה עושה כן.
** זהו -
יש לדון מי אמר כן. ועיין ביבמות שאמר עליו ר"י לר"ל שהיה דורש טוב. ותחשב (ועיין שם שדחהו).
* ה:
** אם היא יולדה -
משמע שפשוט לגמרא שאי אפשר לו לכפר על מת. יש לדון אם זה מפני שהוא מת או מפני שאינו שלו עדיין. עיין רש"י בחולין (כה:) שאומר שהוא עדיין בחזקת אב. (עיין לקמן (ט:) שאומר גמרא ש"אין כפרה למתים.”
** בכל סוגיא זה
(אם קנו יורשים), יש לציין לגמרא ב"ב שאומר שפשוט שאין ירושת בכור כיון שאינו שלו. (ודע שרש"י שם אומר קרא דבכור. משמע שביורש סתם אינו כן.)
* ו.
** מקיבעא -
כתבתי בגלגל שלישי על זה. עיין שם.
נראה שגם אפשר להיות שהוא שכשאדם מביא קרבן, מרצה את ה’, וזה הוא שה’ הוא בנחת לו. זה עושה שה’ יכפר את עוונתיו. זה בקופיא. גם עושה שסיבה אחר לה’ לכפר לו לא נמנע. זהו בקיבעא. חטאת יש לו או שני או אף שני. לשון קבוע בחטאת הוא שריצויו קבוע לכפרה, שעושה אותו יותר ממה שעושה דבר אחר, אבל גבי עולה, לא בפרט מכפר, אלא שה’ נחית לו, וזה עושה כמה תוצאות. ותחשב. נראה שלשון צף הוא, אולי, מפני שכדי לדבר לצוף, צריך להיות מקום לדבר אחר עמו, והוא מפני שאם אין מקום, אז, היו כותלים מעמידים אותו, ולא היה נקרא צף. אף כאן, החלות אינו מיוחד לכפרה. ותחשב.
נראה שגם יש צד חלוק ממה שכתבנו, והוא שאולי קאי על העבירה (זה לא נראה כן מרש"י). והוא, שאינו מכפר על העבירה עצמה, אלא על מה שצף עליו, והוא שאינו מתגדל לגרום יותר עבירות או כדומה.
** כאילו לא… מאי לאו -
צריך ביאור, אז, לשון "כאילו… ." נראה, אולי, שר"ל שכיפר, אבל כאילו לא כיפר, שאז יש לו עוון אחר, וצריך עוד כפרה.
* ז.
** עשה -
משמע שזה בכל זמן. אם כן, צריך לומר שמניחים שעבר אף אחר יום הכיפורים, ואף שאין מניחים אשם תלוי אז.
** מקל וחומר -
קשה, שאם כן, יכפרו אף מקבעא. גם כן קשה, שלא מכפרת על חייבי כריתות אלא אם כן מפרש לזה. אם כן, כן יהיה בחייבי כרת. ואולי אין הכי נמי, מחדש שיכול אדם להקדוש ולהקריב על עשה.
* ז:
** הואיל וגלי -
קשה, שלא אומר כן גמרא לעיל.
** הוא -
מעניין איך מה שכתב כן בפסח מגלה זה. ותחשב.
* ט.
** לחם -
קשה, שיש נפקא מינא גם כן לזמן אכילה. אולי כיון שזה כדי שיגלה הנס, פשוט שאין צורך כאן לעשות כן.
** לרבות -
לא הבנתי, אז, למה צריך דיון שלפני זה במה נקרב. ותחשב.
* י.
** מה -
אם כן, נוכל ללמוד רק זריקה.
** בשוחט על מנת לזרוק
נראה שיש לדון מהו הפסול:
1. אפשר שהוא פסול ככל שחיטה (והוא, באמת, או פסול בשחיטה או פסול בקרבן). יש לדון אם הפסול הוא שעומד לזריקה פסולה (זה פוסלו או מפני מה שפוסל אותו זריקה או מפני שאותו זריקה פסולה) או מפני שחישב עליו לאותו זריקה (שמי שהוא חשוב חשב עליו להיות ראוי לזה).
2. אפשר שהוא פסול בזריקה (שנחשב עליו כבר לרע). זה לא נראה, שלומדים ממנו דין חולין לעבודה זרה, והרי שם אין זריקה לפסול. ותחשב.
** קצת קשה
למה לא אומר גמרא קל וחומר ממחשבה לזריקה למחשבה לשחיטה. ותו"ת.
** בא על חטא -
יש לדון אם זה סימן (שמראה שהוא קרבן חשוב) או סיבה (שכדי לבא על חטא, צריך יותר). ולא נראה שהוא שני, שהרי דן בפסולו, ולא במה שלא מרצה. נראה שני מהלכים לדחות את זה:
1. אפשר שכדי להכשר, צריך להיות לו קצת מריצויו.
2. אפשר שהענין הוא שצריך לעשות קצת ריצוי. יש יותר שינוי מריצוי כפרה לריצוי שיכול לעשות בפסול זה, ואז אינו יכול לעשותו. אז, הוא פסול.
** דמה למעלה -
יש לדון מה לנו בזה. אולי רק אומר חילוק, ואין ידוע איזה יותר חמור, אבל אומר שכיון שאין יודעים, אי אפשר ללמוד. ויש לדון. גם אפשר שמעלה יותר קדוש, והסימן לזה הוא מה שמערכה שם הוא. ויש לדון, שאולי כולו קדוש באופן שווה, אבל אי אפשר לעשות מערכה על מה שאינו flat. (ודע שבאמת, יכול לעשות מערכה על גב סובב.)
* י:
** אשם שאינו כליל -
יש לדון למה אין אומרים כן בפסול שלא לשמו. ותחשב.
לטעמיך- רצה לומר שהמקשן סבר שיוכל למצא תשובה לכל אחד למה אינו בעיא. אומר שלטעמיך קשה, שיש כמה, ואז צריך לומר שאינו דווקא.
* יא:
** דמה -
יש לדון למה צריך קרא לזה, ולמה היה לנו לפוסלו. ותחשב.
** שלמים -
היה אפשר לומר ששאני שם שכל מעלה, אף שהיא קטנה, שייך, שהרי מוכרח אחד מהם לקדם. ותו"ת.
* יא:
** הוה אמינא -
יש לדון, שאם יש סברה לומר כן בר"י, מהיכי תיתי שלא לומר כן בב"ב. צריך לומר שאפשר, אבל למסקנא, אינו כל כך מסתבר, אבל אין זה כל כך פשוט, וצריך ברייתא לאומרו. ותחשב.
* יב:
** בידים -
תחשב מה לנו בזה. ובאמת, צריך לחשוב על כל סוגיה זה.
* יג.
** לשמן ושלא לשמן -
יש לדון מהו הפסול:
1. אותו עבודה שעליו חשב נפסל.
2. כולו נפסל כיון שיש במקצתו מחשבה שפוסל.
3. כולו נפסל, שאומרים שכל מחשבה מגלה על חבירו, ומניחים שהיה לו שני דעות. כיון שהיה לו דעת שפוסל, פסול. ותחשב.
** ישן -
יש לדון איך נדחה את זה:
1. אפשר שכיון שהוא הדרך (אף שיש שנקדשים אותו היום), אין פסול. והוא שיש לדון מהו בעית דחייה:
  1. אפשר שהוא שהיה לו שם פסול, ואף שסיבתו יצא, לא יצא אותו שם. אם כן, מה שהוא הדרך לא מעלה ולא מוריד.
  2. אפשר שהוא שמה שהיה פסול הוא גופא פסול (הוא קצת בזיון לו).
2. נראה שאולי לצד שני, יש לומר שאינו בזיון ופסול לו להיות שהיה לו אותו פסול, שהרי כן הדרך. (עדיין יש לדון למה אין אומרים שזה מכשיר את הכל כיון שרגיל להיות אותו פסול (דהיינו, שאולי אין בין פסול זה לפסולים אחרים בענין שיחלק, ואז נאמר כן לעולם. ואולי כן סובר החולק, ואומרו בכל שהוא למפרע. ויש לדון.)
3. אפשר שסבר שהוא דומה לבידו, שעומד ליפסק.
4. אפשר שהוא דומה לבידו, שאין צורך לכח אחר לרפאותו, שהוא יעורר את עצמו.
5. אפשר שהוא נחשב בידו, כיון שהוא מעורר את עצמו, ואז הוא העושה שיתעורר, וזה בידו. יש לדון למה לא נאמר כן:
  1. אולי אינו מחליט לעלות. ויש לדון, שלעולם בא לו דעה, ומוחו חושב מה לעשות ועושהו. ואולי כיון שהוא יותר subconscious, אינו נחשב בידו.
  2. אולי אף שמחליק כיון שמוכרח שלא לעשותו עד לאחר זמן, אינו מהני.
  3. אולי אינו מעורר כיון שמוחו אומר שרוצה בזה, אלא הוא דבר physical, כמו שלפעמים הוא חולה, ושוב נעשה ברי.
  4. אולי אומרים שה’ עיררו, ולא עצמו.
* יג.
** לחדודי -
לכאורה, רואים כמה פעמים שאמוראים אחרונים (כמו רב אשי) יחלק על אמוראים ראשונים (כמו ר"ה). יש לדון למה לא היה יכול לומר כן כאן. יש לומר שהיה יכול, אבל ידע שהיה כן. גם יש לומר שבכל מקום, לא חולקים, אלא (אם שייך), אמרוהו לחדד תלמידיהם. ויש לדון, אז, למה רק כאן אומרו גמרא בפירוש. ותחשב.
* יג:
** רבי שמעון -
קשה, שכל עבודה זה אי אפשר להבטל. וצריך לומר שכיון שהוא בכלל הולכה, יש לו דינו.
* יד.
** אין מחשבה מועלת כלל -
לכאורה, מועלת אם מוליך ברגל. אפשר שהוא מפני שלא ברגל.
* יד:
** והא שחיטה -
רצה לומר ואז אין הכרח מה סוברים רבנן. ויש לדון, שיש ברייתא, ואולי אף שאפשר שאינו תלוי באם יכול, מסתבר שייתלה, ואז יותר נראה לומר שברייתא רבנן, ולא ר"ש. ותחשב.
** מראות -
שם, אין זר פוסל, אלא שלא עושה כלום. משמע, אולי, שכן הוא גבי שחיטה, שאינו פוסל, אלא שאי אפשר להשחט שני פעמים, ולא נשכט כראוי, ואז פסול.
** הא עומד דומיא דיושב -
קשה, שאין צריכים הולכה (כמה שאמר ר"ש- ואף רבנן לא חולקים, לכאורה, על נקודה זה). ובאמת, היה לו להקשות איך פוסל כיון שהוא לא מוליך ברגל- ויוכיח מזה שנחשב הולכה. ואולי רצה לומר שפוסל כיון שמה שעושה הוא נחשב הולכה גבי מי שכשר (וזהו מה שאומר, “הא עומד… "). ודחוק. ועיין לקמן בגמרא ("אפשר לתקנה") שמרשי שם נראה שפסול הוא אם לא הוליך. צריך ביאור למה.
** מאי קמ"ל -
קשה, שפשוט שקא משמע לן שיש לעשות כן. ואם תאמר שגמרא שואל למה לעשות כן (וזה ק"ק, שלא משמע כן), זה קשה בין כך ובין כך. אולי סובר שעושים כן לגלות שיש הולכה ביד. גם יש לומר שאם רק מוליכים ביד, יותר קל הוא, ולכן עושים כן, אבל אם צריכים לנייד, אינו יותר קל, ואז קשה למה יעשו כן. ותחשב על זה.
* טו.
** נשפך -
היה אפשר לומר שלקח ממה שהלך לחיצון. ותו"ת.
** לבראי -
אינו כל כך קשה, שאם נפל עם פיו לחוץ, רק ישפוף לבראי, לכאורה.
** חטאת -
לא הבנתי למה חלוק מכל שאר זריקה. ותחשב.
* טו:
** שאם עבד -
יש לדון אם זה מוכיח שיש קדושה או, יותר מזה, מוכיח שום יחס לעבודה, שאומרים שרק עובד אוכל. זה מראה, אז, שהוא בפרשת עבודה (לכאורה, רצה לומר שהוא קצת ראוי עבודה).
* טז.
** טמא -
מעניין, שאף שאין בהמה מקבל טומאה מחיים, אם לאחר מיתה מקבל, אינו נקרב (שהמת, ולא הכי הוא הנקרב). אז, יש בו מעין של דין של בעל מום, והיה לנו לומר צד השווה. ויש לדון.
(ועיין ברש"י, שמשמע שהענין הוא דמיונו לכהן. ותחשב.)
** מוזהר -
יש כאן- ובכמה מקומות- שלש דינים:
1. איסור
2. סיבת איסור
3. חילול
צריך לדון מה גורם מה, ומהו היחס (ואם יש יחס) בין כלם.
** אונן -
נראה שיש לדון אם אונן  פסול מחמת אנינותו או מחמת שאינו מצווה (כיון שהוא אונן. ודע שהיה אפשר לומר שזה מפני שאינו יכול לעשות ס”ט, ואז אין סיבה שלא לומר כצד ראשון). אולי כדי לעשות שקרבן נקרב כראוי, צריך להיות מצווה להקריבו. (אפשר שהוא כמו מה שכדי להוציא אחר, צריך להיות שהוא עצמו חייב, וחיוב כהן להקריב קרבן (אם נניח, כמו שצריכים על אותו צד, שחייב להקריב קרבן) מהני כמו עריבות. ויש לדון. ואולי תלוי באם כהני שלוחי דידן. גם יש לומר שחלק מן ההרצאה הוא שה’ נתן חוק, ומקיים אותו. כהן זה לא מקיים חוק שאמר תורה, שלא אמר לו תורה לעבוד.
* טז:
** זר יוכיח -
כמובן, אז, אי אפשר ללמוד זר ממנו.
** אין לו תקנה -
יש לדון אם זה סימן או סיבה. נראה שהוא סיבה, שמשמע לקמן שפסול בגדי כהונה הוא אותו פסול של זר (“אין בגדיהם עליהם, אין כהונתם עליהם"). אם כן, מצינו שפסול זה יתקן. אם כן, בטל הסימן. (ואולי עדיין יש סימן ממה שלפעמים אי אפשר לבטלו. ויש לדון.) אז, נראה לומר שהוא סיבה.
** לא תותר -
לא הבנתי איך ילמד שלא תותר לכהן גדול בקרבן יחיד, שהרי קרא אומר שמותר. ואולי רצה לומר שנוקים את זה מן ההכרח לקרבן צבור.
** צריך לדון למה
אינו אומר בכל אלו פירכות של "מה לטמא שמטמא" או כדומה. ואולי זהו מסקנת גמרא. ותחשב. ושוב ראיתי בתוס’. (ושוב ראיתי שרש"י משמע כמה שכתבנו.)
* יז.
** קלישא -
קשה, אז, למה אינו לומד ממנו בפני עצמו. ואולי יותר קשה לפרוך על צד השווה. ועיין בחולין (קיג?) בזה, שאיני יודע אם הוא נכון.
** אלא -
לשונו משמע שר"ל שיכול לפרוך לכל צד, ומה שלא פירש קרא, אף שהוכיח רבא שהיה צריך לפרש, הוא הוכחה לזה. יש לדון, שאולי יש הוכחה רק למקצתם. גם מרש"י לא משמע כן. אם כן, לשון "לפרוך" מוזר, שרצה לומר שיש ללמוד כזה וזה…
* יח:
** אלא בגדים שנאמר… -
רצה לומר, אז רואים שאינם נלמדים מ"בד,” וכיון שאינם חד דרשה, יש לחלק ביניהם לומר שיש מהם שהם רק לכתחילה, אף שיש מהם שהם מעכבים.
* יט.
** דגמי מסי -
לכאורה, ק"ק למה לא אומר שמילתא אגב אורחה קמ"ל שמותר ללבוש גמי אף שמסי. אולי כן רצה לומר (כן משמע מרש"י כאן), אבל אינו נראה כן. אולי זה פשוט וכבר ידוע מכמה משניות בסוף עירובין.
** דרך לבישה בכך -
רצה לומר, ואז כיון שאומר שילבש אותו, מוכח ש"על בשרו" כולל את זה.
* יט:
** וי"ו אאופתי -
יש לדון למה, אם ידע כן, אמרו. יש לומר שאמרו לחדד לו. ודחוק.
** ובניו -
קשה, שבאותו זמן, לא מת עדיין בני אהרן, והיה צריך להיות ראוי לשש. ותחשב. אפשר לדחוק לומר שאין מניחים שני בנים כיון שהיו לו שני בנים, אלא שאולי לא צריך להיות ראוי לכל בניו; מניחים שנים רק מפני שמיעוט רבים שנים. ותחשב. (גם יש לומר שלא יודעים על איזה זמן קאי (לא נראה, שלכאורה, יש לנו לדעת שקאי על זמן כתיבתה, שהוא קודם מיתתם), ו"תפסת מועט תפסת.” ויש לדון.)
* כ.
** לא מוסיף -
עיין בקידושין (כה.) שאינו כן שם. (ועיין בהליכות עולם (או אחר מן הכוללים כללים, אולי), אגב, במה שמבאר שם). ועיין ברש"י (איך מפרשו כאן). ואולי מפרשו כן מחמת קושייתינו.
* כ:
** אסוחי -
משמע שענין הפסקים אלו אינם שמפסיקים, אלא שיגרמו שמסיח דעתו. ותחשב. יש לדון אם היסח הדעת רצה לומר שלא  חושב על ידיו לשמרם או שלא חושב על עבודה. ותחשב. ודע שאם רצה לומר כראשון, צריך לדון ממה צריך לשמרם (שגמרא דן על כמעט כל דבר שיכול להיות שפוסלם. ועוד שכמה מן הדברים שדם עליהם הוכחנו שרק דן אם גורם שמיסח דעתו.)
(ועיין ברש"י ד"ה או דילמא, שנראה שמפרש שם כל זה. ועדיין צריך ביאור (מהו טינוף, ואם הוא רק דבר שממש מטפם, קשה למה זה בעיה. ותחשב.))
** אגב, נראה בביאור
מה שאין אומרים שיש חציצה במה שידיו מחוברים לזרועיו, ובמה שאין חציצה בפנים, הוא שאינו צריך שיהיה נוגע למים בכולו, אלא שלא יהיה נוגע לכלום חוץ למים (ואף לא לאוויר). אז, כיון שמגע פנים לא נקרא מגע (לענין טומאה, בחולין, פרק רביעי), ואין חיבור נחשב מגע, אינו נוגע לכלום חוץ למי מקווה. ותחשב.
* כב:
** מה טמא מת -
יש לדון למה לא פרכינן מה לשרץ שמטמא בכעדשה. אולי אין זה דין בטמא שרץ, אלא בטומאתו. קשה למה לא פרכינן מה לטמא שרץ שנטמא מדבר שאינו צריך שיעור. אולי כל זה אכניס. ותחשב.
* כג.
** ומה במקום -
קשה למה לא אומרים על זה דיו, שהחומרא שמזכיר אין בו אותו דין של הדין שלומד (חושב אני שעל כגון זה אומרים דיו. ועיין בריש פרק ראשון של קידושין.) ותחשב. ואולי מחלקת אמוראים אלו הוא.
* כד.
** רצפה -
לא הבנתי מהיכי תיתי שצריך קדושה זה כדי להכשיר קרבן (שאולי נתקדשה רק להכשיר קדשים הבאים שם). כן, באמת, היה נראה, שהרי לא היה נקדש במדבר, ועדיין היה כשר. יש לדון, שאולי מה שהיה לפלנים מעננים מהני. גם יש לומר שמקדש חלוק ממשכן. ודחוק.
** רבה זוטי -
יש להעיר ששמו הראשון מתורגם "גדול" ושם השני שלו מתורגם "קטן.”
* כד:
** בכיהונן -
לא הבנתי, שאם כבר יודעים שיש צורך לכהנים, נדע דין זה, ואם לא, נצרך זה ללמד שצריך כהן. ותחשב.
** בברייתא -
עיין בראש עירובין שאומר אביי כן שם גם כן.
* כה.
** שלא יהא קרבנו מהודר -
משמע שדין יד ימין הוא מחמת בזיון. ואולי זה רק הוה אמינא.
* כו:
** מום -
יש לדון אם זה מפני פסול מום או מפני שאינו כבשחיטה. לשון דרשה משמע כשני. יש להעיר שבין כך ובין כך אינו כבשעת שחיטה ואינו תמים, שיש בו מום של שחיטה (עיין בגמרא חולין שאומר שזה מום). אפשר שכיון שנצרך כדי להקריב אותו קרבן בעבודה זה, אינו בעיה, שאין בו בזיון. ויש לדון (שעדיין אינו דומה).
גם נראה שיש לדון אם פסול בעל מום הוא שדם נחשב "בא מבעל מום," ואז זה פוסל קבלה הולכה וזריקה, או שהוא שמעשה של קבלה נעשה עם בעל מום, ואז זה פוסל קבלה.
** בן שנה -
נמצא שפסול של שניו אינו מפני שמגדל (רצה לומר שאין שני שנים רצה לומר מי שגדל שני שנים), שזה כבר מת. ותו"ת.
* כו:
** דחוי -
נראה שהענין הוא שאם לא נעשה, אינו פסול, אלא שאינו כשר עדיין (לכאורה, החילוק יהיה אם יש רע או רק אין טוב). אם נעשה כן, היה פסול. אז, הקרבן כבר היה לו שם דיחוי, ואי אפשר להכשר. עיין ברש"י שאומר שדם נדחה. זה, לכאורה, אינו כמש"כ. ותחשב.
* כז.
** אי הכי -
זה קשה בין כך ובין כך, שמשנה אומר שאינו פיגול אבל הוא פסול.
* כז:
** מקצת -
נראה שצריך להזכיר שניהם כיון שהיה צד לומר שאם חושב כן על כולו, אינו כשר כלל, ואין בו חיוב כרת. ותו"ת.
* כח.
** אמר ליה -
מוזר שאומר לשון אף זה, אף שבקושיה לא הזכיר שום אדם השואל לו. ותו"ת.
* כט.
** יהיה -
עיין במקום אחר (תמורה?) שדורשים מ"יהיה" שלא יהיה ביטול. הענין שם הוא שלא ישנה שמו על ידי ביטול. אם כן, צריך לומר שכשדברים מצטרפים, לא משנים שמם. יש לדון:
1. אפשר שאין הכי נמי, יש משמעות כזה נגדו, אבל יש גם כן משמעות כמותו כמו שכ’ רש"י, וזה השני יותר חזק.
2. אפשר שאף שמשנה שמו, רק נשתנה לדבר הכולל שניהם, ולא לשם שניהם.
** מאחר נדרו -
יש לדון למה נניח כן, שרק כתיב פעם אחת, ולא יהיה מעכב. ויש לדון אם נחשב חולין או לא, שעיקר האיסור הוא שלא לשהות נדר, וזה אף בנזיר.
** מאחר -
ואם תאמר למה יהיה צד שלא מהני; לא בא בעבירה, שאין העבירה הקרבתו לאחר זמן, אלא שהויו. נראה שאולי איסור הוא רק סימן, ואסור מפני (על כל פנים, בהוה אמינא) שלאחר זמן, אין קרבנן כל כך טוב. עיין בראש השנה, שכתבנו כעין זה שם. ותו"ת.
* כט:
** דבר שדרכו -
יש לדון למה:
1. אולי אין מעשה שלו כל כך נחשב אכילה, ונמצא שלא חישב על אכילה.
2. אולי לא מניחים שבאמת יעשה כן, שמוזר הוא. לא נראה, שאם כן, יהיה הדין כן אף אם חישב לאכילת מזבח (ולא רק להקטרה). ואולי דין הקרבה באינו ראוי חלוק מאכילה באינו ראוי. ואולי מסתבר כן, שלכאורה, כדי להיות הקטרה צריך לעשות ס"ט, אבל אין גדר כזה באכילה, לכאורה. ותחשב.
* ל:
** לא תיחול -
קשה למה לא רק אומר שכולי עלמא מודים אם אמר, “… תמורת עולה ושלמים.” אולי זה יותר פשוט. ותחשב.
* לא:
** מאי קמ"ל -
קשה, שדילמא קא משמע לן כדיוק גמרא לעיל.
* לב.
** גזירה שמא יגעו -
קשה, בין כך ובין כך יהיו פסולים מדרבנן, שמדרבנן אי אפשר להם ליכנס. ויש לדון. ותחשב.
* לב:
** מטונך -
עיין במה שמבאר רש"י. צריך ביאור איך מביא ראיה להיפך; לכאורה, אין זה ראיה. ותחשב.
** הואיל… דחויה -
זה מראה מקום. ותחשב.
* לד.
** בהמה אין -
קשה איך ממעטים חיה מזה, חיה בכלל בהמה. ואולי שאני הכא שמונה את הבהמות שמקריב, ואז אולי מפני זה מפרשים ש"בהמה" כאן רצה לומר בהמה דווקא. ותו"ת. קצת מעניין, אז, איך יודעים ללמד למקומות אחרים שבהמה כולל אף חיה, ולא נאמר ש,כמו כאן, הוא דווקא. ותחשב.
* לד:
** דחזו לקדושינהו -
ואם תאמר אף טמא חזי להיטהר. ויש לומר שצריך יותר שהוי או יותר מעשה. ותחשב.
* לה.
** מדו -
עיין לעיל, שיש אומרים שיכול לקצרו על ידי אבנט.
** איצטבי -
קשה למה אין בעיה שמוסיף על הבנין. ותו"ת.
* לז:
** הרי כאן -
קשה למה לא דורשים שלש לבית שמאי, שאי היה רוצה לומר שנים, היה אומר חמש, שאי היה רוצה לומר אחד, היה אומר כב"ה. אפשר שחולק על ב"ה במה לדרוש כשיש ארבע. גם אפשר שאינו יותר טוב לומר ארבע מחמש. שאף שיש בו מנין יותר גדול, אינו מיותר (יש לדון, שאין צורך לוי"ו. ויש לדון, שאולי כן דרך התורה כמה פעמים, שהוא חלק מן הנקודה. ותחשב.), ואז לא נדרוש כן.
* מא.
** בפירוש -
יש לדון מה אומר:
1. כתיבה שני פעמים הוא כמו שכתוב בפירוש.
2. כתיבת פעם שני מלמד ללמד דין זה, שלא היה צורך לו כי אם ללמדו. ותו"ת.
3. מג.
4. מנחת כהן משיח- לכאורה, זה נכלל במנחת כהן. נראה שכיון שהם שני מיני מנחות, אף שלענין זה שווים, מפרידם. ותו”ת.
5. מג:
6. עליו- מגמרא זה נמצא שמזבח לא רק עושה שאין בעית טומאה; עושה שאינו טמא. ויש לדחות ולדחוק.
* מד.
** שני ימים -
אפשר שהענין בזה הוא שיש לו מתירים יותר, שיותר מתירים אותו, שהוא מותר ליותר זמן.
* מה:
** מסתבר -
קצת קשה למה לא אמר שמקישים לחומרא. קצת משמע שאין אומרים כן בגזרה שוה. דע שזה מחלקת ראשונים (עיין בתוס’ בריש בבא קמא. ועיין בהליכות עולם ונושאי כליו).
* מז.
** איזהו מקומן-
יש לדון אם הענין הוא מקום החפץ או מקום המעשה. יש לדון מה נחשב מקום המעשה (אין למעשה מקום, אלא לחפצים). אולי הוא מקום של חפתי מעשה, אבל הענין הוא שזה נחשב מקום מעשה, וחשוב הוא כיון ששם קרה מעשה, ולא כיון שחפצים היו שם. ותו”ת.
יש להעיר שיש לדון אם מה שאומר “ודמן... “ שמבאר מקום זריקה נכלל בתשובה ל”איזהו מקומן.” לשון משנה אולי משמע שאינו, שאומר, “שחיטתן... וקבלת דמן...” ולא אומר “וזריקתן... “ אלא, “ודמן טעון.”  אפשר שהוא שחד (לכאורה, תחילת משנה) הוא מקום המעשה, ושני הוא מקום החפץ. ותחשב.
* מח.
** היקש עדיף -
לכאורה, היה מצי לומר שדין שלא לפלוג יותר טוב בחד. ותו"ת.
* נח:
** רבי יוסי -
לכאורה, אין הוכחה שמשנה זה אומר שצריך לינטל משם. נראה שאולי בלי זה, לא היה לו לייחד מקום להוצאתו.
** דגמרן -
יש לדון למה אינו אומר שצריך לעשות כן מפני שאין מעבירים על המצוות. ותחשב. ואולי זה לא אומר שצריך לעשות אותו באופן הכי מהר, אלא שלא לעבור, ואפשר, אולי, ליקח הרחוקים באופן שלא יעבור ממש. ונראה שאולי זה החילוק בין זה לזריזים מקדמים למצוות.
** רבי יהודה -
אם כן, היה אפשר לומר שהוא שום תנא, וסבר כרבי יוסי. ותחשב. ותו"ת.
* נט.
** מכלים ואפילו -
יש לציין למקום אחר (מזבח מקדש, אבל לא כמו מזבח הזהב) אומר גמרא שאין מזבח כלי. נראה שאולי כאן לאו דווקא, או ששם רק רצה לומר שלא נמשח. ותו"ת.
* נט:
** אל ארבעת רבעיו -
יש להעיר שהוא עד אמצע הצד, ומוזר לקרוא אותו רבוע שלו, שהוא המקום היחידי  שיהיה שווה לאם לא היה מרובע (אלא עגול).
* ס.
** שלש אמות -
יש לדון מה קרה כשמשה עבד (שהיה גבוה עשר אמות). ונראה שאולי לכן אומר, “שלא יראה כהן…“
* סא:
** אביי -
פשוט לציין לגמרא ב"מ (אלו מציעות, גבי הכרזת אבידה), שאומר אביי כעין זה. ותו"ת.
* סב:
** פורח אמה -
אם היה שם יסוד, קשה איך היה אויר קרקע ביניהם, כמו שאמר גמרא לעיל. ותחשב. ואולי לא היה כל הכבש אותו אורך (היה חסר בחלק ממנו).
* סד:
** נותנים לו יין -
ואם תאמר איך נותנים לו כיון שהוא על גב מזבח. צריך לומר שעלו ופנו לשמאל. אם כן, קשה מאי אהני. אולי חוץ ממה שאין ללכת לשמאל, יש ענין של הליכה לימין. גם יש לומר שכיון שאין המביא עובד, אין בעיה. ותחשב. ונראה שאולי יש לחקור אם הליכה כן הוא טוב בפני עצמו או שהוא עושה שמה שמקריב הוא יותר טוב. אף לשני, עדיין יכול להיות אף אם אין הוא המקריב, שהרי הקרבה זה נכשר על ידי מעשיו. ותחשב. גם יכול להיות לראשון שהוא רק במקריב, שאולי רק בדברים חשובים יש צורך ללכת בימין. ותחשב.
** פנה… היה מולק -
יש לדון למה שינה לשונות, ולא אמר, “מלק… " או להיפך. ותו"ת.
* סה:
** מעשה -
קשה למה לא אומרים שמקומו מחלק.
** מחתך בשר -
משמע מזה שר"א רק מכשיר. לשונו משמע שאומר שיש לו לעשות כן (ועיין לקמן בגמרא שאומר שלא צריך להבדיל. כן, לכאורה, מוכרח ממה שאומר קרא ש”לא יבדיל.” ויש לומר שמכשיר אם לא מפריש.). (יש להעיר שלכאורה, אם רק מכשיר, לא רק מכשיר, אלא אוסר, שהרי יבטל ממיצוי.)
** משום ר"א בן שמוע -
מעניין שיאמר דברי רבי אלעזר ברבי שמעון, כיון שהיה חבר רבי שמעון, ור"א היה בן של רבי שמעון. ויש לדון.
* סו.
** אלא מעתה -
לכאורה, לא מוכיח מזה כרבנן, שאז עוד קשה, שבוודאי לא אומר שאין לכסותו, אלא מוכיח מזה שרק בא להכשיר אם לא מפריש. גם יש לומר שמוכיח כרבנן, והוא שלרבנן אין צורך לתורה לבאר מה שהוא חלוק מכאן כיון שכל כך פשוט מן הקרא שהוא חלוק, שלמה לא יכסה, אבל לר"א, אינו כל כך פשוט, והיה לו לבאר. ויש לדון.
** אלא מעתה ולא -
קשה למה לא מקשים כן בכל לאו (שנאמר לרבי אליעזר שכל לאו אינו מעכב. ותחשב.)
** עלויה -
קשה, לכאורה, למי שמחייב אף אם היה למזיק רשות לעשות מה שעשה לגרום ההיזק (עיין בב"ק ל ובמק"א.) אם נאמר שרק מקשה על רבי אלעזר, יכולים לומר שכן סובר. עדיין מעניין שלא אומר שמחדש קרא נגד זה, אלא שאומר דבר אחר כשאומר ולא יכסנו.
* סז.
** מכי מלק… אפסלא -
יש לציין למה שכתבנו בכעין זה בבבא קמא, שמבואר שלפעמים (כמו לענין טריפה ובעל מום) שאין אומרים שמה שקורה בתחילת מעשה פוסל מה שקורה (היתר אכילה או היתר הקרבה) בסוף המעשה. לאידך גיסא, מצינו מקומות (כמו כאן, וכמו שחיטה עם כוונה לעבוד עבודה זרה (שם בבבא קמא ובחולין גבי ישנו לשחיטה מתחילה ועד סוף)) שאינם כן, ושמה שגורם בתחילה משנה מה יקרה בסוף. ותחשב על זה.
** יש להעיר שאם אין
לשחיטה אלא לבסוף, אז, לכאורה, מה שנחשב שעושה מעשה חטאת אחר סימן אחד, אף שלא הגיע לגמר שחיטת עולה הוא רק מפני שעשה אותה חטאת כבר. קשה, שאם כן, הוא גלגל החוזר. ויש לומר שלא צריך אלא שמעשה שעשה נראה (והוא עשייה השווה) כמעשה חטאת.. ותו"ת.
* סז:
** מחצה -
מוזר למה לא אמר, “חטאת… " שיפרש יותר. אפשר שאמר כן כדי שיוכל לומר לשון השווה בשניהם. ודחוק, כמובן.
** רבי יהושע -
מעניין שצריך להוכיח שהוא רבי יהושע כדי להקשות, שלעיל, לא רצה לומר שסתם משנה אינו כרבי יהושע, כיון שרבי אליעזר שמותי. ותחשב.
* סח.
** סכין -
יש לדון למה אין אומרים שהוא קל וחומר, שלעיל מבואר שיותר טוב לעשותו בכלי (שמנסה ללמדו בקל וחומר). ותחשב.
* סח:
** לא היה פסולו -
יש לדון מה בסכין. יש לומר ששם אינו מליקה כלל, ולא מליקה פסולה. וצריך ביאור. ותחשב.
** סכין -
קצת מעניין שלומדים מאברים ופדרים ואין לומדים מבהמה. צריך לומר שכיון שיש במינו, יותר יש ללמוד. ותו"ת.לת
* סט.
** כלי שרת -
יש לדון אם רצה לומר שאז אינו אותו מנחה (ואז, אולי, רק שם מהני קמיצת ישראל), או שאז מעשה קמיצה חלוק (מה שעושה חלוק, כיון שאין קידוש כלי). גם יש לדון אם זה סיבה או סימן. ותחשב.
** דנים -
זה מעניין, שלכאורה, אינו מלמד, אלא מדמה לטריפה. ותחשב.
* סט:
** קל וחומר -
יש לדון, שלכאורה, אינו, למסקנת גמרא, קל וחומר. אפשר שרק רצה לומר שבהכרח אין רבי יהודה נכון. גם יש לומר שצריך קל וחומר כיון שבלי זה נדרוש קרא רק לשחיטה. ויש לדון, שמשמע שמשיב לרבי יהודה לבאר דבריו, ואם כן, היה לו לומר עיקר מקורו (ותחשב). יש להעיר שלפעמים יאמר משנה דבר שאינו כל כך דווקא (עיין בר"ה ולקמן בזבחים).
עיין ברש"י שאומר על ר"מ שהוא מקל וחומר. מוזר שאומר כן כיון שמשנה מפרשו, ועוד שמשנה לכאורה אינו דווקא. ותחשב. משמע שבא לומר שהוא דווקא. וצריך ביאור.
** אי -
היה אפשר לומר שמוכיח שטרפה אינה חיה, ולכן מטמא. ותו"ת.
** דחידוש הוא -
מעניין למה צריך נקודה זה, שהיה אפשר לומר שמטמא בהיותו בבית הבליעה, ואולי לא צריך לאכלו. וצריך לעיין מהו לשון הקרא.
* ע:
** ימותו -
מעניין שממיתים קדשים (שלכאורה, אסור. ויש לדון, שאולי כיון שלא עומדים להקריב, אינו אסור. ויש לדון, שעדיין אסור להטיל מום.). ותחשב.
* עד:
** סמיכה -
יש לדון אם מקשה שלא נקריב לבטל אותו מצווה או שכיון שאינו ראוי לסמיכה (יש לדון, כיון שהוא רק מחמת ספק), ייפסל. ותחשב.
* עט:
** לא הבנתי כל כך
למה קדשה לרבי זירא, שיש לומר שאף שחולקים עד אם גוזרים, כולי עלמא מודו שאם ממש מצוי, אין לגזור. ויש לדון.
* פ.
** אין בילה -
יש לדון מה סובר אותו שיטה:
1. הפשטות הוא שסובר שאין מניחים שיש חלק מזה ומזה במה שנטל.
2. אפשר שסובר שלא נבלל כלל, וכולו במקום הראשון, ואז בוודאי אינו בכל מקום (ואין לדעת, לכאורה, מאיזה מקום נטל). לכאורה, הסיבה שלא נניח שיצא ממקומו הוא שכבר הוחזק שם, ולא יודעים שיצא, ואין ספק מוציא מידי וודאי. ויש לדון.
3. צד זה נראה יותר מוזר, אבל לשון, “אין בילה" משמע כן (שלא נבלל כלל). ויש לדחות"ק.
עיין ברש"י שאומר, בביאור מי שאומר שיש בילה, שסובר ש"יש בילה, וסמכינן… " נראה, לכאורה, שמפרש שצריך לסבור כשני הנקודות- שיש בילה (ולא כב’), ושסומכים עליו (ולא כא’). (אם זה נכון, נמצא שמשתמש במילים של גמרא בב’, ומשמע שכן מבאר מי שסובר שאין בילה. יש לדחות שרש"י רק אומר ש"יש בלה, דהיינו.. “ ותו"ת. ועיין לקמן ברש"י שרק אומר, “אלמא סמכינן אבילה…"
שוב ראיתי ברש"י ד"ה מאי קסבר, שלכאורה, מוכרח כצד ראשון. ותו"ת.
גם מעניין מה שאומר רש"י שמניחים שנתערב בכולו. היה אפשר לומר שרק מניחים שנתערב באותו מקום שממנו נונטלו (והוא שאולי מניחים לקולא), אבל אין מניחים שהוא במקום אחר (אלא שהיינו מקילים לומר כן). ויש לדון. ותחשב.
* פא.
** אלא אמר רבא -
קשה שלא אמר שום אמורא שאין בילה חוץ מרב אשי, והרי רב אשי חי אחר רבא (יש לציין למגרא קידושין שאומר שנולד רב אשי ביום שמת רבא. אם כן, ק"ק למה מתרץ כן רבא. אולי בא לבאר מה שהיה צד למקשה שסובר רבי אליעזר שאין בילה. ודחוק. ואולי זה רבא אחר או רב אשי אחר. ודחוק, כמובן. ועיין באלו מציאות (כח) ובמקומות אחרים שדנים במה שמצינו שרבינא ורבא דנים בדבר, ואומרים שיש שני רבינא. לכאורה, מכאן היה יותר נראה לומר שיש שני רבא. ותו"ת.
* פב.
** לדבריו -
נראה, אז, שזהו ביאור לשונו, והוא שאומר שאם לא ישב וירבה לכעין זה, אינו נכון, ואף אם סובר שזה ריבוי, יש לו דבר אחר לדרוש לזה ממנו. ויש לדון. ותו"ת.
* פב:
** בא זה… אמר ליה אביי -
אביי הוא המקשה כן גם כן בקידושין. ויש להעיר שיש לחלק לומר שיותר רע שם, ששם לכאורה, בגרות אינו סותר קנין שאינו, ואז אין לו אותו דין. כאן, אפשר לומר שהוא עושה רע, והוא פוסל, אלא שאין נפקא מינא, שהוא כבר פסול. אולי, אז, יש לומר (ואין צורך, שאינו בעיה לומר שלא ידע אמורא אחד קשיא שהקשה על אמורא אחר (שכאן הוא רבא, ושם הוא רבה. ועיין במסורת הש”ס שאומר לגרוס כאן רבה. אם כן, לכאורה, יותר קשה. ואולי הא גופא; אמר שניהם במקום אחר, ואמר גמרא אותם בשני מקומות (עיין רשב"ם פסחים[fn:1]). באותו זמן אחד, הקשה אביי שני קושיותיו. גם יש לומר שרבה לא סבר כקושיית אביי, ולא חש לו, ולכן חזר לומר אותו שיטה. ותו"ת.) שזה בא שני, ולכן רבא הניח שאף שהקשה אביי על כעין זה, לא היה מקשה על זה. ויש לדון, שאביי מבאר דבריו, שאומר שצריך להיות שהוא רק קל וחומר. ואז, היה לו ללמוד. ויש לדון אם אביי אמר כולו, או אולי גמרא ביארו. ותחשב.
* פג.
** קדשה -
לשון זה מעניין. לכאורה, הוה אמינא שיש כמה פסולים שאינם בעיה בקדושה, שדיינו שקדושתם שווה, אלא שיש רע. ויש לדון, שאולי זה פוגם קדושה. גם יש ומר שכיון שהוא כל כך קדוש, הוא טוב שיקריב (או שהוא יותר רע אם לא נקרה. ותחשב.).
* פג:
** לאו ממילא -
מסתמא, החולק יסבור שלא היינו דורשים כן אם לאו שכבר היה לנו קרא אחר, שהיינו אומרים שקרא זה רק בא לגלות את הדין של עולה. ותחשב. ויש לדון איך ילמדו מעולה (ואם כן, אין צורך למיעוט, שלכאורה, אין ריבוי).
* פד.
** סד"א הואיל -
לשונו מוזר (שכופל מה שאומר); לכאורה, רצה לומר כיון שמקריב לאחר זמן, סד"א שאינו חלק מן הזבח. ותו"ת.
** אם עלה -
לעוללם אומר, “אם עלה.. “ והוא לשון מיותר, שמלשון ירידה, פשוט שעלה, שאי אפשר לרדת ממקום שלא עלה לו. ותו"ת. ואולי הוה אמינא שר"ל שיורד מקדושתו או כעין זה. ותח’. גם נראה שאולי אף שאינו נצרך כן מדברים בני אדם, והוא מסתמא מפני שיותר קל להבין, שאין צריך השומע לדייק כן מעצמו. נראה שיש לזה שני מעלות:
1. אינו צריך להטריח את עמנו.
2. אפשר שיגיע לו ההבנה בדרך כלל לאחר זמן. אז, אולי לא יבין שאר דבריו, שהיה עוד חושב על מה שאמר ללפני כן.
ותו"ת. (ויש להעיר שלכאורה, אין אלו שייכים כל כך לגמרא. יש לדון, שלכאורה, ראשון לא שייך, שטוב לטרוח על גמרא. אולי אין זה נכון, שאין ענין טירחא על גמרא על כעין זה, אלא על ההבנה, ולא על ביאור הלשון. ויש לדון, שאולי זה מעורר זה. ותחשב. על שני, נראה שאין כל כך בעיה, שכלאורה, יש בעיה רק כשממשיך המדבר, שאז מפסיד מה שאומר, אבל גמרא נקרא. ויש לדון, שמתחילה לא היה נקרא, אלא נאמר. ודע שאף אם אינו נוגע, יש לומר שאוותו לשון נעשה נורמל כיון שכן מדברים, ואולי לכן השתמשו בו. ויש לדון. ויש להעיר שעל כל פנים היום, יש שינויים, בדרך כלל, בין לשון הנכתב ללשון הנדבר[fn:2]. ותו"ת.)
* פד:
** תנא אזאת… -
ואם תאמר הרי למעשה לא אומר כן. ויש לומר שרק אומר סימן כדי לזכור. לא משמע כן. גם יש לומר שאומר למה נבחרו אלו למעט. ותחשב.
** שהרי לן -
ואם תאמר נאמר שהרי לן באימורים כשר לכתחילה (ורשי לא מפרש כן). ויש לומר שאינו כשר אחר עמוד השחר, והוא העושה לינה.
* פה:
** נקבה -
קשה, שלכאורה, זה יהיה פשוט, שהרי יש בו מום. גם קשה, שלכאורה, אינו כמום שקדם, אלא הוא מום שקדם. ונראה שאולי אינו כל כך רע כיון שהוא כשר בדברים אחרים (זה סימן או סיבה), ועוד שהוא דבר מצוי, ואז אינו כל כך רע ומאוס. עיין ברש"י שאומר עליו ש"אין לך מום גדול כזה.” עיין במה שכתבנו על כעין זה בחולין (ל.) ובמקום אחר. נמצא, אז, שאינו כל כך פשוט. אפשר לתרץ קושיא שני שאולי אף אינו נחשב מום. לשון רש"י בוודאי לא משמע כן. ואולי רצה לומר לא שאין דבר מום יותר משזה מום אלא שאין מום יותר גדול משזה גדול לענין פשול. אם כן, אולי מה שהערנו ממה שכתבנו בחולין אינו כל כך קשה. ועדיין דחוק, שבדרך כלל, אין אותו לשון אומר כן.
** מה ת"ל ועשית -
קשה, שכבר דרש מזה (או לומר שצריך אוויר או שאם אין כזית נשאר, אין זורקים, ונאמר שממעט מדין זה שאר חלקי בהמה. וצ"ב.
* פו:
** כל הלילה -
קשה, שלבסוף לכאורה לא מוצא מקור לדין של משנה. ונראה אולי שכשחוזר מדרשה הוא רק על מה שרק חצי לילה להרמה, אלא דורש סתירה לומר שחצי הוא לשניהם, וחצי הוא רק לזה. ודחוק עדיין.
* פט.
** כאלה -
מעניין שאומר לשון כאלה, ולא כזה, שלכאורה, קאי על הסדר. אפשר לומר שאומר ששאר יהיו כעין אלו- הקרק’ של הסדר. לשון רש"י לא משמע כל כך כזה. ויש לדון.
** ועל היסוד -
עיין במה שמבאר רש"י. קשה שלעיל למד מקרא שכל שהוא על מזבח העולה טעון יסוד. נראה שכיון שהכתיב יותר בפירוש יותר יש לו חומרא. כמו כן מצינו בתוס’ שלנו (קדושין טו:), אלא שיש להעיר שאולי הוא כן רק בקדשים, שמציינו שמקורות אינם כל כך חזקים לו, כמו היקש והיקש. ועיין במה שכתבנו בזה בשיח שי זבחים (גלגל שלישי). ותו"ת.
* פט:
** להודיעך -
לכאורה, אז, צריך לומר שכשאומר רב יוחנן את טעמו, רק אומר שאף לטעמו של ריש לקיש, כאן יודה לו. ותו"ת. ויש לדון, שאולי רצה לומר שכשר כיון שסוף של חלק ממנו לצאת. ויש לדון. אולי אגב, יש לדון מה לנו שסופו לצאת, אם הוא סיבה (וצריך ביאור למה) או סימן (וצריך ביאור מה מוכיח, שאין לומר שמוכיח שאינו קדוש, שזה לכאורה, כבר ידוע מדין מעילה. ואולי מגלה שקדושתו מאד מעט ממה שאף אינו גורם לכל כך קדושה. ויש לדון.) ותחשב. (ואולי מהות הסברה יבאר אם מה שבשר יצא ילמד על האימורים. ותחשב.
שוב ריאתי ברש"י על זה.
** בציבור -
יש לדון אם הענין הוא שיכול לעשות דבר היותר חשוב (הוא הקרבה לציבור) או שיכול לעשות יותר דברים (יכול להתקרב ליחיד או לציבור).
* צ.
** דמכפת -
נמצא שלכאורה, מה שאומר משנה על חטאת (מכפרת) ועל מנחת נדבה (בא על חטא) שווה. אם כן, קשה למה לא אמר אותו לשון. ותחשב. אפשר לומר שבא על חטא משמע שיש להביא את זה כשחטא, וזה רק אומר שיש שום כפרה קלה. מכפר משמע דרגא יותר גדולה של חזקה. אז:
1. אפשר שאין מנחה ממש מכפר, אלא רק "בא על חטא.”
2. אפשר שאומר במנחה שבא על חטא כיון שמנחת נדבה אינו אף בא על חטא. אבל בקרבן, שעולב מכפר מקופיא, אינו אפשר לחלק ביניהם לומר שזה בא על החטא, ששניהם באים על חטא, ואז צריך לומר שמכפר, שרק חטאת מכפר מקבעא. ותו"ת.
עיין לקמן בגמרא שמבאר לשון כאן של באה על חטא. יש לדון אם אומר כמו שכתבנו או רק שאומר לשון זה כדי לכלל יותר מנחות. על כל פנים, עדיין צריך מה שכתבנו לבאר לצד האחר (ולמה אין מביאים ראיה מזה). ותחשב. ויש להעיר שאם אינו אומר מה שכתבנו, אלא אומר לשון זה לכלול שני טעמיהם, ,לכאורה, קצת מוזר, שאין לכאורה איחוד טעמם, שאין טעמם שווים כלל, ואז כשאומר לשון זה, אינו אומר טעם, אלא אומר דבר שבזה גורם חד טעם ובזה גורם טעם אחר. לשון משנה משמע שאומר טעם. ותחשב.
** דמכפרת -
יש להוסיף שאין כל כך סימן ממה שאין לו שמן ולבונה, שיש לו סיבה שיהיה לו שמן ולבונה, אלא שנדחה, כמו שאומר בתחילת מסכת סוטה. כן היה נראה לומר, אבל לכאורה, אינו נכון, שאין הקרבן בעצם טוען שמן ולבונה, ומה שיש לו שמן ולבונה בלי סברת גמרא שם הוא רק מפני שלא יהיה חוטא נשכר. (ועיין שם. והוא גמרא קשה, שלכאורה, אם אין שום סיבה חוץ מזה, זה לא יהיה סיבה, שאז אינו נהנה כלום, שנתחייב בקרבן, ולא נפטר משמן ולבונה, אלא שאין סיבה לו. ותו"ת. אז, צריך לומר שיש סיבה לו, ואז אומר שאין רוצים שיפטר ממנו. קשה למה זה לא יהני בפני עצמו (מה היה פוטר אותו ממנו). אפשר שיש סיבה לו, והיה נדחה כיון שלא יהיה מנחת חוטא טוב, אלא שלא יהיה חוטא נשכר, ואז על זה מחדש גמרא שאף זה ידחה. ודחוק. אם כן, יש לומר כמה שכתבנו כאן, שיש סיבה להיות לו שמן ולבונה. ותו"ת.)
** מכפרת -
יש לדון אם אומר שלכן הקרבן יותר חשוב או שיש יותר צורך באותו תכלית (באמת, הענין יהיה איזה תוצאה יהיה לו יותר סיבה להיעשות מיד- ולא רק איזה יהיה לו יותר סיבה להיעשות כלל. ותו"ת.)
* צ:
** לחטת -
היה אפשר לומר שדורש שאין א, ואז אינו ראשון (שאלף הוא האות הראשונה).
** איבעיא להו -
צריך ביאור למה שואל כן כאן, ולא על משנה שלפני כן. ותח’. ואולי הוא מפני שרצה לשהות לו
כדי שיהיה יותר קל להביא ראיה ממנו.
* צא.
** אלא מותר -
אם כן, יש לשאול מהו, אם הוא זה או זה. ויש לומר שאין נפק"מ ביניהם. ויל"ד למה שאני אם יכול להקריב שמן לנדבה. וצריך ביאור, אז. ועיין בקהתי.
** אטו ראש חדש -
אם לא ידע אותו סברה, אז, יחשב ששל שבת יש לו מעלה כיון שיש עליו שם שבת, ואם כן, צריך ביאור למה יחשב ששל ראש חדש מקודש. צריך לומר שחושב רק על של שבת שמהני לשניהם. וצריך ביאור למה. ותחשב.
* צב:
** זו שאלה -
אפשר לומר שר"ל שעיקר שאלתך (רצה לומר, הלומדות) הוא עדיין שאלה, אלא שהדין הוא…, והוא מפני שממה נפשך הוא. עיין לקמן, שלכאורה, אינו אפשר לפרשו כן. ואולי כן היה דרך רבי לדבר (עיין במסורת הש"ס כאן).
* צג.
** כמונח -
ואם תאמר אם כן מה מעליותא של מת. ויש לומר שלא רק עולה, אלא אף בוקע. גם יש לומר שסובר שאין שום מעליותר (חוץ משבע ימים ואהל.)
* צז:
** רבא -
נמצא, לכאורה, שלא סובר שצריך להיות בעידנא. ועיין בשבת, שהאומר שצריך להיות כן הוא רב אשי, ואולי לכן צריך לחלוק כאן. ותחשב.
** עשה -
כמו כן אומר ביום טוב, ומשמע שהגדרתו של עשה חלוק.
** והתם עולה -
לכאורה, זה מוכיח שהיה- או שהיה על כל פנים צד שהיה- ישראל, שאין גוי מביא אלא עולה. ויש לדון, שאולי כיון שה’ חייבו חלוק. ותחשב.
* צח:
** מנא הני מילי -
ק"ק, שמשנה מביא קרא.
* צט.
** אלא מאי… -
יש לדון איך יודעים לדרוש אותו כן, ולא כקושיית גמרא.
** ש"מ -
לא הבנתי הראייה, שלא מצינו שם שמרבה אותו תורה לחילוק אף שאינו עובד, שהרי כאן עובד. ותו"ת. אפשר שזה רק מהני למה שאינו יכול להביא אותו, שרק על זה רואים שאף שאינו יכול (כיון שהוא בעל מום) אינו מפסידו מלאכול. ותו"ת.
** ומי איכא -
לכאורה, היה אפשר לו להקשות כן לעיל על מה שאומר ששומר את עצמו ממת בלחוד.
* קא.
** לא שמעתי -
יש שמבארים (שייך לגמרא בחגיגה ושבת אם יותר טוב לשכח או שלא ללמוד) שהיה יכול לזכות בדין לומר שלא שמע, ואז מוכרח שלא נאמר, ואז היה אהרן חושב שהוא נכון. לא משמע כן כל כך לשון גמרא, שלא אומר שהיה אומר ששמע נגד זה, אלא שלא שמע כן, והרי הוא נלמד מקל וחומר, ואם כן, נניח כן. נראה שיש לתרץ על פי מה שאומר ירושלמי (פאה פרק ב הלכה ד) ש"אף מה שתלמיד ותיק עתיד להורות לפני רבו כבר נאמר למשה בסיני.” אם כן, לכאורה, כבר ידע משה כל קל וחומר, אם לא שמע זה, נמצא שאינו נכון (ואז כשאומר שלא שמע, לא רצה לומר שלא אמר כן ה’ למשה כשאמר לו מה לעשות בחינוך, אלא שלא אמר לו כן בסיני). זה מניח שידע ממש כל קל וחומר. יש שמפרשים שרק רצה לומר שהיה לו כל מדות וכדומה, עד שהיה כל מה שיחדש אותו דרשה[fn:3]. אם כן, מש"כ אינו נכון.
** טומאה -
באמת, אפשר לומר כן, לכאורה, בביאור הקרא לשני צדדים, אלא נראה שרצה יותר צד זה לאומרו, שאז נמצא שמובן יותר למה לא פירש קרא מה אירע לו, והוא שהוא המשך של מה שאמר קודם. ודחוק. ותחשב על זה.
* קא:
** כהן גדול וחולק -
לשון כפול זה מעניין. נראה לבאר על פי יסוד ששמעתי מרש"ש שליטא בשיעוריו על הוריות. באר שיש שני חלקי דין כהן וכהן גדול, והוא קדושה שלענין מקדש (שמביא קרבנות), ולענין שאר דינים (שיכול לאכול תרומה, ולא מטמא). עיין שם שהוכיחו משיטת רבינו תם שיש דיני כהנים רק כשיש עליו בגדים, ואף שבוודאי בלי בגדים אסור לבעול גרושה. ועיין שם. על כל פנים, יש לומר ששנים אלו הם לשני ענינים אלו. ויש לדון איזה הוא איזה.
* קב.
** אהרן הלוי -
אז, נראה שאין זה ממנין של פעמים שנקרא כהנים בשם לויים. ויש לדון למה לא אומרים כן לתרץ קושייתו. ותו"ת.
** אלא תם -
יש לדון למה:
1. הפשטות הוא שמי שהיה ראוי הוא עדיין יותר ראוי. לכאורה, הסיבה לזה הוא שאין שמו הפסול כל כך[fn:4], אלא הוא קצת הכשר.
2. כמו כן, יש לומר שנמשך דין של שמו הכשר, אף שלא נמשל הכשרות (כמו שמצינו בכמה דינים. שמעתי מרש"ש שליטא שלכן נאסרו עריות לאחר מיתה.).
3. גם אפשר שכהן יש לו זכות אף בדבר שאינו בעולם, אלא יבא לעולם (ויש לדון אם יכול להיות כן). אם כן, כל זמן שהוא ראוי כלל, מקבל אותו.
4. לפי זה, צריך לומר שדן בזכותו. נראה שהיה אפשר לדון אם גמרא אם ההוה אמינא של גמרא הוא לאכילה או לחילוק. גם יש לדון אם המסקנא הוא לשניהם או רק לאכילה. לצד זה, צריך לומר שדן רק בחילוק. הדרך לדחות זה יהיה לומר שיש תלייה ביניהם. ותחשב.
** עובר -
נראה שכאן יש בזה שני ענינים:
1. אינו כל כך פסול, כיון שעומד להיות כשר.
2. יש יותר צורך בנתינת קדשים לו, יאכל אותם כשהוא תם. וזה לא יקיים אלא אם כן עובר מיד.[fn:5]
* קב:
** כי טמא -
לכאורה, הענין הוא שחלק ממה שיכול לאכול הוא שיש לו יותר חסרון אם לא אוכל, שלא יאכל לעולם, אבל זה יאכל. ודע שמעניין שהיינו לומדים כן מטמא, שטמא הוא פסול חלוק, ולמה נניח שהוא חילוק של יכולתו להכשר שאוסרו. ואין זה קשה, שרק פירכא הוא, ואומר שאין ללמוד, מפני שיש חילוק זה. וקשה, שאם כן, אין להביא ראיה מטומאה. ותחשב.
גם יש לדון מה אם אדם טמא, ולא יכול להיטהר, שמגמרא זה משמע- אם לא שנאמר לא פלוג- שיהיה יכול לאכול. (ואולי זה רק בהוה אמינא זה.) זה, לכאורה, בא אם טמא מת בזמן שאין פרה אדומה. ויש לדון, שראוי להיות נטהר, אלא יש בעיה היותר פרקטיקל (אותו טומאה במצב אחר יכול להיטהר). ויש לדון. גם נמצא, אולי בציורי נזיר טמא (עיין בנזיר. וחושב אני שלמסקנא לא נמצא שם.).
** וטמא בשעת -
משמע שאינו דין באכילה (עיין בהגה"ה 6). ויש לדון, שאולי בשעת זריקה, כיון שהיה עומד לאכלו בטוב, כבר זכה בו. כיון שזכה בו, לא מפסידו כיון שהוא טמא, ולא יכול לאכלו. ויש לדון.
** לעולם -
כיון שעובר דווקא, מעניין שאין צריכים קרא לקבוע (שאולי קרא מגלה שאין קרא אומר דין קבוע, אלא רק עובר).[fn:6]
* קד.
** בדיעבד -
אין, לכאורה, ראיה מזה, שאין זה אומר שמותר כיון שיש צורך. ותו"ת.
* קד:
** בית הדשנים -
לשון זה מעניין, שלכאורה היה לו לומר, “בתי הדשן.”
** יש לדון אם
ענין של לפני זריקה הוא שאז היה לו כשרות או שמה שגורם כשרות כבר בא, ולא יוצא, ורק יש פסול אחר עליו, או שאז היה כבר עומד לאותו דין. ותחשב.
** מקום אחד -
משמע כרבי יוחנן. ויש לדון, שאולי רק רצה לומר שום מקום אחד, אבל לא קבוע. ודחוק. גם יש לומר שקבעו גזברים מקום לו, אף שלא היה צורך. ויש לדון למה יעשו כן. גם יש לציין לגירסת גמרא ביומא (ב.). אם רצה לומר הבית, אז בוודאי חולק, אלא אם כן לומר שאז בירה של משנה רצה לומר הראשון, ואז אומר רק כריש לקיש. ותו"ת.
** פשטנה -
משמע שלא סובר כדיחוי גמרא. יש לדחות:
1. רצה לומר שפשט מזה וששוב הקשה.
אולי פשט לא רצה לומר שפשט בלי דיחוי אלא הביא ראיה. ויש לדון.
** יוצא -
לשון של "ביציאתו" אז הוא קצת מוזר. ויש לדון. ויש לומר שלא רצה לומר בדרך לצאת, אלא במה שהוציאו, והוא שהוציאו יותר מן הצריך. ויש לדון שמשמע מגמרא שקאי על זה ועל טמא, ואין לפרש כן לטמא. ותחשב.
** יציאה -
יש לדון אם שאל בזה מפני שהוא שאלה הדומה לשאלה שלפניו או מפני שמביא ראיה מאותו משנה. גם אפשר להיות שניהם. ותו"ת.
* קה.
** הן עצמן -
מעניין למה לא אומר,”אבל הנוגע בהם…,” שכן, לכאורה, רצה לומר (וכן מפרש רש"י).
** הא כדאיתא -
אם כן, נמצא שאין שום תנא שסובר שיש, באמת, אותו מניןי. ואולי רצה לומר שבזה סבר כר"מ ובזה כרבנן. אם כן, מה שגמרא, מתחילת, לא רוצה להניח כן הוא, לכאורה, רק מפני שלא מסתבר שחד תנא יחלק לומר לפעמים כר"מ ולפעמים כרבנן. לא נראה כן, שאז מה לנו שרישא וסיפא רבי מאיר. ואולי רק רצה לומר שראינו שסובר כמותו בשני מקומות. לא נראה, שהיה צריך לסבור כאחד מהם, ואם כן, מוכרח הקושיא. ויש לדון, שאולי היה יכול להיות מסופק. וכל זה דחוק. ואולי כל זה רק בהוה אמינא.
* קו.
** אביי -
כ"נ, שמשמע שדורשים משני קראי, ואין צריך לתנא שני לחלוק על תנא ראשון מפני דרשה שדורש. אם כן, לא נניח יותר מחד מחלקת.
** אביי -
יש לציין לכלל ש"תנא בתרא לטפויי" (ב"ב צג:).
* קו:
** ומה במקום -
יש לדון מה סובר:
1. אולי אין צריכים אזהרה מפורשת, אלא די שיילמד מקל וחומר. לשון גמרא לא משמע כן.
2. במקום אחר, דנינו אם תורה הוא האזהרה או שתורה אומר מה קרה, ואומר שהיה אזהרה. על השני, יש לדון אם תורה הוא ממש מה שאמר ה’ או שמבאר מה אמר (רצה לומר, שהוא מעשה שמגלה מה קרה). לשני, יש לומר שמגלה שאמר אזהרה על זה, שה’ אמר לבני ישראל שלא לעשות כן. אז, לומר מקל וחומר שכן קרה, ושכן אמר לו ה’.
** קל וחומר -
קשה למה לא פורכים שכאן כתוב בפירוש, וכאן לא כתוב. ובאמת, יש לדון למה אין זה פירכא בכל קל וחומר. וחושב אני שדברנו בזה במקום אחר. ותחשב.
** אם כן -
היה אפשר לומר שדבר שהיה אפשר ללמוד בקל וחומר טרח וכתב אותו קרא. ואין לומר ששאני כאן שיכול ללמוד ממנו (רצה לומר, שדורשים אם יש לדרוש. אז, יש לומר שכאן יש לדרוש שלא לעשות קל וחומר כזה. אז, לא נניח שבא רק כיון שטרח וכתב לו, אלא אולי היה לו צורך לבא.), שהרי אין אומרים כן בלימוד שאין מזהירים מן הדין מדין אחותו (אלא צריך קרא אחר ביבמות). ותחשב.
וצריך ביאור, באמת, למה אי אפשר לומר כמש"כ. ותחשב.
** אתא לקמיה -
לכאורה, מה שקורה כאן הוא שהלך רבינא לפני רבא אחר שהלך לרב אשי. קשה, שחי ר"א אחר רבא, כמו שאומר גמרא בקידושין. וצריך לומר שאחד משניהם (רבא או רב אשי) יש לו אחר עם אותו שם. ותחשב. עוד קשה, אז, למה אומר תוס’ שיש שני רבינא (שמצינו שמדבר עם רבא), ולא שיש שני רבא, שזה היה מתרץ אף לכאן. וצריך ביאור.
** מה להלן לא ענש -
מעניין למה לא אמר מה… הזהיר. ותחשב.
* קז.
** מתקיף -
לכאורה, רק על צד זה קשה, שאז עושה שניהם שני פרשיות, אלא שמרבה שניהם לאותו דין. ותחשב.
* קז:
** שחיטה -
מעניין שמחשיבים את זה למקום מעשה, שלכאורה, אין מקום למעשה, אלא מה שנקא מקום מעשה הוא מקום של חפץ של מעשה או של שינוי שעשה מעשה. לכאורה, אז, אומר שיש שינוי היותר גדול בצוואר, אף שלכאורה, יש גם כן שינוי חשוב בשאר בהמה, שנעשה מת. ודע שלכאורה, חד חפץ הוא, ואז צריך להיות כמקום שינוי, ולא כמקום חפץ. ויש לדון שאולי כיון ששינוי נעשה לצוואר, כולו בתר צוואר גריר, וזה נחשב מקום החפץ. ותחשב.
** קדשה לשעתה -
לכאורה, לשון זה אומר שאו קידשה לעולם או רק לזמן שהיה עומד. יש לדון, שלכאורה, אז, שניהם אומרים שקדשו לעתיד לבא, ורק דנים לאיזה עתיד. ונראה שאולי אפשר לבאר באופן אחר, והוא שכשחלות ממשיך, יש שני יכולתות; אפשר שסיבה ראשונה הוא סיבה לחלות שבכל זמן ואפשר שסיבה ראשונה גורם חלות ראשון, ואחר כך מה שהיה כבר אותו חלות בלי הפסק חשוב ביניהם עושה שאותו חלות חל עוד. אולי דנים בזה כאן, וסיבה שקדוש לשעתה אומר שחל לשעת סיבה, ואחר כך חל מהמת סיבה אחרת. אולי אז כיון שהופסק, ואינו מיד לאחריו (שביניהם יש חורבן), לא קדוש. סיבה שקדוש לעתיד לבא הוא שסיבה לקדושתה היה הגורם קדושה לעולם, ואז, כמו שיכול לגרום לדבר שבא כמה שנים לאחריו, אולי יכול לחול אף על לאחר חורבן. ותו"ת.
** נימא -
יש להעיר שבין כך ובין כך הוא מחלקת תנאים (עיין בערכין). ואולי רצה לומר שכיון שהוא מחלקת ר"א ור"י היה לנו לפסוק כר"י, ואז לא היה להם לחלוק בזה. ותחשב.
** חיבורי עולים -
יש לדון אם רצה לומר שכולול נחשב חד דבר (לכוארה, זהו הנקרא מגילה) או שכיוףן שהוא מחובר לו, יש לו אותו קדושה המכשירו. ויש לדון אם יש חילוק בין צדדים אלו. עיין במה שאומר לקמן גבי מלח. יש לדון אם זה אומר שיש לו כבר יותר קדושה, שהרי יש בו צורך, או שהוא יותר חלק אחד ממנו. אולי זה תלוי על צדדים אלו. ותחשב.
* קח.
** מלח -
יש להעיר שאין צריכים להחזיר אותו מלח. לכאורה, אז, אין זה עושה אותם כל כך דבר אחד יותר. ותחשב.
** שכן -
יש לדון אם זה מחמת טומאת בשר או מחמת דין במקוה[fn:7]. יש לדון אם יכול להיקרא חומרא לצד שני.
* קח:
** ויבן -
מזה נמצא שלכאורה, הקרבה שאסור בחוץ שייך להקרבה שהוא כשר בשעת במות. ותחשב.
* קיא.
** נמצא… במדבר -
לכאורה, אין הוכחה מה סובר ר"ע, שאולי כן הוא בשניהם, וקרא מחדש במה קטנה ובמה גדולה, ואומר הכי מחודש.  ואולי רק רצה לומר שאפשר לומר כן. ולא נראה כן ממה שמשמע שתולהו על זה בראש העמוד (“בקרבו… פליגי").
* קיג.
** ושניהם מקרא אחד -
חושב אני שכבר הערנו את זה, אבל ראוי להעיר אותו עוד, והוא שמצינו כמה מקומות שבו אומר רבי יוחנן ששניהם דורשים חד קרא, וכאן אומר כן רב נחמן בר יצחק כן על רבי יוחנן. ותו"ת. (ודע שמצינו משנה בתרומות שאומר כן על שני תנאים.)
* קיג:
** שקצים ורמשים -
יש לדון למה לא נחוש לבשר מתים. ויש לומר שהיו נקברים קודם שיכולים לבא (ודע שאם כן צריך להיות שהיה זמן רב קודם שבאו). אם כן, זה מבאר מה שהערנו על רש"י ד"ה מהבלא (ועדיין צריך ביאור למה נקט צד זה).
* קיד.
** אידחו -
ק"ק למה לא אמר שהוה אמינא שיודה כיון שהם מאוסים, כמו שאמר לעיל (או להיפך).
** וקסבר ולדות -
מעניין שאומרים שנחשב ראוי לפתח, אף שלא קדוש עדיין. ותחשב.
* קטז.
** ובקש -
ק"ק למה לא אומר, “ונותנה.”
* קטז:
** בת י -
אם כן, בת י שנים היתה בקריעת ים סוף; נמצא שהיתה זונה כל כך מפורסמת כבר מאז.
** יהא מחול -
משמע שהוא אסור לגוי להיות זונה. ואולי היתה נשואה. ואולי זנה עם ערוותה.
* קיח:
** שאינו שלו -
קצת משמע שהבעיה באשת איש הוא שאינו שלו, וכמו גזל. ויש לדון. ואולי אשתו של גוי חלוק משל ישראל. גם יש לומר שיוסף היה גוי, ולגוי חלוק.
* Footnotes
[fn:1] אומר שמצינו כמה פעמים ששאל רבי את רבי ישמעאל ברבי יוסי כשחלה. דן אם חלה שני פעמים, אוא שכלם קרו בבת אחת, וגמרא אמרם בכמה מקומות. חפשתי לו במהירות אחר כן, ולא הייתי ייכול למצוא אותו. ותחשב. ועיין.
[fn:2] נראה שכן הוא לרב בני אדם, אבל יש להעיר שיש בני אדם שלא יודעים לכתוב, שכותבים כשהם מדברים, אבל זה בדרך כלל נחשב מוזר ומוטעה. יש בני אדם מועטים שמדברים כמו כתיבה, אבל אין אלו הרוב (ונחשבים קצת מוזרים, אבל לא מוטעים).
[fn:3] אגב, יש להעיר שזה דומה למה שאומר בשבועות, שידיעת בית רב מצרף, והוא שלפעמים ידיעות דברים שכשמצרף את כלם ביחד יאמר אותו מסקנא נחשב כידיעת אותו מסקנא. כאן הוא דומה, שאף שלא ידע משה אותו קל וחומר, ידע דיני קל וחומר, וידע דיני תורה. ותו"ת.
[fn:4] נראה שיש בזה שני ענינים:שמו יש בו יותר דבר שהוא כשר.שמו יותר דומה למה שהוא כשר, ואז, “יש במינו שהוא כשר.”
[fn:5] ואגב זה, נראה שיש לדון אם מה שיש הוה אמינא שלא יחלק הוא דין בחלוקה או באכילה, והוא שיש לדון אם מה שאל חולק הוא תוצאה ממה שאין אכילתו, אולי, כל כך טוב, או לא, והוא יותר דיירקטלי ממה שהוא בעל מום. ותחשב.
[fn:6] ויש לדון אם היינו דורשים כן, שלחד צד, לכאורה (ויש לדון) הוא היותר מסתבר, ואין בו כל כך חידוש, אבל לאידך גיסא, משנה יותר ממה שהנחנו בקרא, ואולי, אז, אין להניח כן בלי דרשה. ותחשב.
[fn:7] עיין בגליון הש"י בשבת (פרק ראשון) שדנינו בזה.
