** ב. למה לי -
עיין במה שאומר שרק מקשה שיש דרך יותר קצר לומר זה. לולי רש"י, היה אפשר לומר שאין לשון "אלא" נכון, שאומר שיש שיור בכשרות קרבן, והרי אין שיור בו, שלכל כשר. אז, צריך לומר שכשר לא רק אומר שהוא קרבן כשר, אלא אומר שיש לו כל דיני שאר קרבנות, ועל זה אומר מיעוט. נראה שאולי מה שלא אמר כן רש"י משמע שחושב שיש בעיה בכשרותו, ואין הבעיה ביכולתו לכפר אלא ביכולתו לרצות.
ודע שכל זה הניח ש"כשר" אומר שריצה לה’. אולי אין זה נכון, ו"כשר" משמע שעשה כל מה שזבח עושה, והיה כולל בו כפרה. ותחשב.
** ב: ונדבה -
וכיון שרחמנא קרייה- זה מעניין, שלכאורה, היה לו לומר "כיון שהוא נדבה… " משמע שיודע שקרא לאו דווקא, ואינו ממש נדבה, אלא דורשים שיש לו דיני נדבה ממה שכן קוראו קרא. ותחשב.
** תוכו -
אבל… בתוף תנור- נראה שזה מפני שאז אין שם של "בתוך כלי חיצון נסתר," שרק נסתר כיון שמקומו הוא כלי פנימי, וזה אין מקומו כלי חיתון, שיוצא ממנו. ותחשב.
** ואפילו -
לשונו (שם) משמע כמה שפירשנו בזה. ותחשב. עוד.
** ג. אם הציל -
אז, אף רבנן אומרים כן, אלא שחולקים אם יש קל וחומר. אם כן, יכול להקשות אף מרבנן.
** חולין לא כש"כ - .
לא הבנתי, שרק אומר שאין זה קל וחומר שרק מינו פוטר. ותחשב. גם צריך ביאור מהו קושיית גמרא, שאין שני הקל וחומרים שווים. אין לומר שדן אי קל וחומר יש לו תוצאות בזה, שלמה לא יהיה לו. נראה שאולי ידע המקשה מסקנת גמרא, וסבר שהדיון הוא אם קל וחומר עוקרת קרא. קשה, שיש לנו כבר הוכחה שאינו עוקר (גבי קידוש שני שעירי יום הכיפורים). ואולי חושב שזה תלוי במחלקת. ותחשב
** ד. תודה קרוייה -
חטאת- אין זה דמיון כל כך טוב, ששינוי של שם לא דומה לשל כאן.
** ה: מאן -
מעניין שדורש מלשון רצון שמכפר. משמע שאין הרצאה חוץ מכפרה. זה מעניין; לולי זה, הוה אמינא שיש מצוה לרצות את ה’, ואינו גורם כלום חוץ מקיום מצווה.
** ו. כאילו -
עיין איך מפרשו. אם כן,- קשה למה שונהו, שכבר שנהו. לולי רש"י, היה אפשר לומר שר"ל שכיפר, אבל לא כל כך, שכיפר ולא כיפר. לזה, לשון "כאילו" קשה.
** ו: קרבנות -
עיין שבועות, שלכאורה, אינו כל כך דומה לזה (ששם מתנה איזה קדושה נותן). ותחשב.
** אלא שחיסך -
יש להעיר שהיה לו לומר שהוא מלשון חס על ממון (אבל רש"י אומר שכסך מעוונתיהם). ועיין בתהילים שאומירם "חשך עבדך," ואז אולי (שאולי יכולים להחליף השי"ן והסמ"ך) רואים שאומר לשמור. ותחשב.
** ז. ודילמא -
לא קיימא לן- מעניין שיש ראיה כלל, אז.
** תודה -
לכאורה, רצה לומר ששחטה למין תודה אחרת (כן נראה מרש"י לקמן). קשה, אז, למה צריך לומר שלאחר יש גם כן תודה, אלא שהוא מין חלוק… שהוא מבלבל. ותחשב.
** ז: עולה -
עיין במש"כ תוס’. קשה, שגמרא לעיל אמרה שאף עולה כן. נראה שיש שני דרכים לדחות את זה:
1. אפשר שסבר שזה רק קאי על יורשים בלחוד.
2. אפשר שסבר שגמרא שבריש עמוד מובן רק אם עולה מכפר יותר. אז, צריך לומר שיש שני דרגות בקופיא. ותחשב.
** ח. ה"ג בס"א -
צריך ביאור,  איך מפרש. ותחשב.
** כלל ופרט -
מעניין שאומרים כן אף בלי צורך (שיש דרך אחר לפרשו). ונראה שמוכרח כן, שאומרים כן אף שיש דרך אחר לפרשו לעולם (שהוא מיעוט ורבוי).
** ט: מעשיה -
עיין במה שכתב. משמע שהוא ריעותא במחשבה. היה אפשר לומר שיש יותר סיבה להכשירו (שיש כבר מעשיה שמוכיחים).
** י. שכן -
שהרי תורה נתנה מחיצה- צריך ביאור מהיכי תיתי שאין מחיצה רק לחטאת (שאז, אין הוכחה ממה שנתנה תורה מחיצה, שדילמא לא לחלק לעולה נתן).
** י: שכן -
כגון- יש לדון איזה זמן אחר יש שנכנס דמיו שם (שהיה לו לרש"י לומר "ביום הכיפורים,” ולא "כגון ביום הכיפורים.” ותו"ת.
** יג. ובכלי -
עיין במקור שמביא. עיין לקמן, שדורש מכאן שלא ילבש בגדי כהן גדול (אבל דורש חסרון בגדים מקרא אחר).
** מחשבת פיגול -
צריך ביאור למה אומר דווקא חוץ לזמנו, ולא כל פיגול (אף חוץ למקומו).
** טו. והחזירו -
עיין בלשונו של “כהן שעליו…” יש לדון אם רצה לומר שעליו מטלת כיון שהוא כהן. לא משמע כן, שזה פשוט. אלא נראה שר”ל כהן שקבל זכות וחוב לעשות קרבן זה על ידי פייס או משמר או כדומה.
** אי תניא -
משמע שמודה. עיין ברש"י אחר (שבת?) שאומר שם אמורא אחד לשון זה, ואומר רש"י שלא מודה.
** טו: קרבו -
משמע שפשוט לרש"י שאם היה הוקרב בטומאה, היה מחמת שדוחהו (רצה לומר שעושה ס”ט די, אף שהוא טמא), ולא שהוא שאני, ואין טומאה רע לו.
** טז: שכן הותר -
במה- עיין במה שאומר. יש לדון מה אומר. אולי רצה לומר שאינו באותו כלל. לא כן משמע לשונו. יותר משמע שאומר שאינו דחוי שם, אלא הותר. כן היה רמ”ש חושב לומר ב”הותר מכללו,” אבל שוב אמר נגד זה מגמרא חולין (קיג?) שאומר שחלב הותר מכללו אצל טריפה. שם, לכאורה, אין מה לדחותו.
** יט. דלילה… -
צריך ביאור מהו סברה זה שאומר רש"י (ומשמע כן מגמרא) שמחמת חביבות מצווה, נחשב חלק מגופו.
** לא תיבעי לך -
עיין במה שבאר. לולי רש"י, היה אפשר לומר שהוא שכיון שלפעמים חוצצים, לא נחשבים כל כך חלק מבשרו, ואז לעולם יחוצו. ותחשב.
** כג: עיין במה שבפרש"י
בדרשה של "לעמוד לשרת,” שהוא שבחירתם פעל רק לעמידה. לולי רש"י, היה אפשר לומר שדורש שקידש אותם לדבר שהוא בשירות. כיון שידועים שקידש אותם לעבודה, רואים שעבודה הוא דבר שבעמידה. ותחשב.
** כח: אדרבה -
היה אפשר לומר שאומר גמרא שמסתבר שסמכו כיון שהוא היותר דומה, ואז מסתבר שמיעטו, אבל מרש"י נראה שאומר שיותר מסתבר שמיעטו כיון שהוא דומה, שאז יותר צריך מיעוט. צריך ביאור, שלכאורה, בלי מיעוט, הוה אמינא שעל שניהם קאי, ובין כך הוא נצרך. ותחשב.
** כט: דלאו בר -
משמע שאין שלמים מכפר על חטא. עיין ברש"י בערכין (כא? גבי מי שממשכנים).
** לב: שמא ירבה -
לשונו מוזר; משמע שגוזרים כדי שלא יענש. אפשר שהוא רק סימן לחומר עבירה. דחוק.
** לד: הואיל ומרצה -
משמע שזריקה פסולה אינו זריקה. נראה, אולי, שר”ל שאין פסולו שעושה רע, אלא שאינו עושה את הטוב שצריך, שאין לו שום תוצאה. נראה שאפשר שמרצה לפיגולו רצה לומר שיש לו תוצאה- תוצאה רעה. (לא משמע כן לשון ריצוי, שמשמע שממלא רצון ה’. ותו”ת.)
** לה: וכשרין -
ק"ק איך נאמר שסומא נחשב מחוסר אבר; משמע מגמרא קידושין (גבי קטע עין מסומא) שאינו מחוסר עד שהוא מוציאו. אולי שניהם מחוסרים, וחד חסר יותר. ודחוק. אולי אדם חלוק מעוף.
** לו: ישפך -
שפיכה אחת- לא רצה לומר שלשון שפיכה משמע אחת- היה אפשר לומר שכן הפשט, אבל רש"י לא אומר כן, כמבואר מהמשיכו- אלא רצה לומר שמשמע מעשה שפיכה אחד.
** לז. תרי -
עיקר… טפל- לשון אותו ברייתא לא משמע כן. ותו"ת.
** מה: שכן הותר -
הותרו מכללם- לעולם צריך ביאור איך לפרשו, שהיה אפשר לומר כאן שהותר קודם שני ימים. ותחשב.
** מו: חד מהאי -
היה אפשר לומר שהיו רק שני חולקים; חד מזוג זה וחד מזוג זה. ותו”ת.
** מח. דנקא -
עיין בסוף מנחות שזה פחות שהנחשת, שלא מניחים שיתנדבו בפחות.
** נח: כל -
למה להו לשוויה כללא- קצ"ב למה לא אמר שמקשה שהוא פשוט. ותחשב.
** סב. שכל -
נראה שגם אפשר לומר- ואולי כן אומר רש"י- שדורש מה"ה הידיעה, והוא שאומר שלענין זה, יש רק מזבח אחד, שאין מה שמשנה מזה נחשב משכן כלל.
** סב:
בני קטורה- יש להעיר שלא נחשבים אף בני אברהם, דכתיב, “כי ביצחק יקרא לך זרע.”
** סג: לג’ דברים -
אינו עולה- יש לדון מה כוונתו בזה:
1. אולי אגב מה שמזכיר עלייה למזבח מעורר שיש מאלו שאין להם שום עלייה למזבח.
2. אולי מעורר שאלו אין להם שום עלייה, ואז ממילא, מקיפים, כמו בשאר קרבנות, ולא כשאר הנעשים שם, שכיון שאינו על גב מזבח, אין לחוש לעשן. אין נראה כן, שלא באר עדיין סיבה זה.
3. אולי אומר שכיון שאינו על גב מזבח, אלא רק הולך למקום שצריך לילך על קרקע, אין דין שכל פינות צריכים להיות לימין. יש לדון אם זה נכון. ועיין ביומא שכשדנים איך בא כהן גדול, לכאורה, לא מחשבים מה שצריך לפנות לימין. ויש לדון.
** סט. אין קידוש -
דלא דמי הך קמיצה- לשונו משמע שמחלק בין מעשה למעשה, ולא בין חפץ לחפץ. ועיין במה שכתבנו בשיח שי על גמרא. ותחשב. ויש לדחות"ק שרק אומר כן כיון שלמעשה הלימוד יהיה ממעשה למעשה, ואז אומר שאין ללמוד מעשה ממעשה, ואולי זה מפני שהם על חפצים אחרים. ותו"ת.
** מה טריפה -
היה אפשר לומר שאומר, “מה טריפה אסור…." יש לדון למה לא יפרש רש"י כן.
** מדבר שלא -
צריך ביאור מה אומר. וצ’ לציין למה שאומר כאן שיט"מ.
** אלא ת"ל -
אפשר להיות אף כרבי יהודה, כמו שאומר גמרא לקמן. ויש לומר ששם דורש מטריפה שניה, ואם כן, אין צריך כל הוכחה זה, אלא מה שכבר אמרו בפירוש. ויש לדון, שאי הוה רק אחד, לא היינו דורשים כן, אולי . ויש לדון. עדיין מלשונו לא משמע שאומר כן. קם קשה, שלכאורה, רש"י, ולא גמרא, הוא האומר אותו הוכחה לדרוש. ותחשב.
** סט: מדין קל וחומר -
עיין במה שפירש. עיין במקום אחר (רש"י תענית כ.) שאומר שכל שלש עשרה מדות הם הלכות למשה מסיני לדרוש אותם. ודע שאפשר שאין רש"י בתענית רש"י, וגם אפשר שאין רש"י כאן רש"י (שיש כתב יד כאן). גם עיין ברש"י (יבמות צ:), שלכאורה הוא רש"י, שאומר כרש"י בתענית. אז, צריך לומר לכאורה שאינו קשה כיון שזה אינו רש"י.
דע שלולי רש"י, היה לנו לומר שאומר או משל של קל וחומר (לבאר מהו) או שאומר הגדרת קל וחומר. עיין ברשב"ם (בבא בתרא קיא.) שכתב (עיין שם) כפשט ראשון שכתבנו. כן, לכאורה, נראה (ולא כרש"י, ואולי אף לא כפשט שני שכתבנו, אלא ששם יש לדחות), שהרי אומר כן אף בגזרה שווה. שם בוודאי נלמד מהלכה למשה מסיני שיש לדרוש אותם, שאותם מילים נאמרו מסיני לדרוש, שאין אדם דן גזירה שווה מעצמו. ועוד ששם לא מביא מקור, אלא ציור. (הדרך לומר שמגדיר הוא שמגדיר על ידי אותו משל שם. וע"ש.)
גם יש להעיר על רש"י שאומר שההו"א הוא שאין התורה ניתן להידרש כן; ומביא מקור לדרוש כן שאינו, לכאורה, דורש מתורה. יש לדון, לכאורה, למה אינו פשוט מסברה לדרוש קל וחומר:
1. עיין בשיח שי במקום אחר (כריתות?) שהוכחנו שאולי יש חלק מאיסור שאינו סיבות רעות או מה שה’ ציווהו (גילה שכן רוצה), אלא מה שאמר לנו כן בפירוש (ויש לציין לתוס’ שלנו בקידושין טז. שאומר כעין זה). ותחשב. אם כן, יש לומר שאולי כיון שדבר שנלמד מקל וחומר לא נכתב בפירוש, לא יהיה בכלל דיני תורה.
2. יש לומר שאין יודעים לעולם סיבות דיני תורה, ואז אי אפשר לדון בכעין זה מדעתינו.
3. יש לומר שלעולם (או, על כל פנים, בכמה קו"ח) יש פירכא במה שאין לשני ס"ר של ראשון, ואף שיש לו ס"ר חלוקות.
לכאורה, מכלם, רק 3 נוהג גבי אותו קל וחומר שאומר תורה. ותחשב.
** אם -
בחזקת חיה- מעניין למה לא אומר שהוא אז חיה, ולא רק בחזקת כן. וצריך ביאור.
** עא: ירעו -
יש לדון מה אומר. אפשר שאומר שרק דוחה רק רעה של זלזול, ולא שנים. יותר משמע שרק דוחה שלו, ולא של אחר, והוא, לכאורה, שאינו רק דוחהו, אלא שכיון שזהו טובת הקדש, אינו כל כך זלזול. אם יש טובה להקדש באופן יותר דיירקט, הזלזול פחות. נראה שאולי לכן רק בקרבן עצמו מותר. ותחשב.
** עד: ואי בעית אימא -
נראה כפשטו השני ממה שלא הביא שיטת רבי אליעזר. משמע שהוא דבר שכבר הובא וכבר ידוע לגמרא. אם כן, צריך לומר כפשט שני. ותו"ת.
** פ. מי יימר -
רוב שניהם- לא רצה לומר רוב של כל אחד ואחד, אלא רב של שניהם ביחד, שאין, לכאורה, צורך לומר רוב של כל אחד. ותחשב.
** פב. אלא ה"ק -
לא הבנתי, שכיון שצריך חטאת לזה, אין צורך להביא מה שכבר אמר חטאת. יש לומר שלולי זה, לא הייינו יודעים מקור לדבר אחר, שאינו נלמד מחטאת, ולא שהיינו אומרים שחטאת ממעט. ותו"ת.
** פט. מין זבח -
מעניין שזבחים נקראים ונגדרים על שם שחיטתם, אף שלכאורה, היה נראה לומר שזריקה הוא עבודה היותר חשובה, כיון שהוא המכפר (והוא עבודה). ותחשב. כמו כן, היה אפשר לומר שמה שהוא מין בהמה קובע, כיון שזהו קרק’ חשוב, לכאורה, של החפץ.
** צג.
רבי אליעזר- ואם תאמר אם כן, איך מצינו לעולם שיחלקו רבה ואביי, שנאמר שלעולם חזר בו. ואולי אין הכי נמי, לעולם חזר בו (חוץ ממקומות שמצינו שמביאים ראיה לדבריהם). גם יש לומר ששאני הכא שמקשה עליו ודוחה מה שאומר. ותחשב.
** צו: והא לא תניא הכי -
עיין במה שפירש; וזה מעניין, שחושב אני שרגילים בני אדם לפרש שאומר שתניא לא כזה (ואף שפשוט שאין פשטות המילים אומר אלא כמה שאומר רשי, כן רגילים בני אדם לדבר, כמו שכשאדם שנא דבר, אומרים שלא אוהבים אותו. ותחשב. ויש להעיר שברב מקומות, מוציאם שגמרא אחר כך יביא ברייתא שחולק. אפשר ששם פירושו הוא שלא מצינו ברייתא כן, והרי יש ברייתא נגדו. גם יש לומר שמן הקנטקס"ט כאן (שדנים אם יפשוט אותו כברייתא) יודעים שהוא חלוק. ותחשב.
** קא. וחכמים -
עיין במה שפירש. גם היה אפשר לומר שר"ל שחכמים עשו חיזוק יותר, ואז מקל וחומר כיון שעשו אותו על דאורייתא, עשו אותו על דבריהם. ויש לדון, שאין סיבה לגמרא להניח שהוא קל וחומר, שאולי רק סובר שהם שווים. ממה שאומר גמרא שהוא יותר, אז, נראה דלא כמש"כ, אלא כמש"כ רש"י. גם יש להעיר שלרשי מה שאומר גמרא הוא יותר דיירקט לגמרא, שלא אומר מה שיכול להוכיח ממנו לביאור גמרא, אלא אומר ביאור גמרא. ותו"ת.
** קא: שעיר נחשון -
עיין במה שמביא מתורת כהנים. גמרא הוא בשבת גם כן; מעניין שמביאו מתו"כ ולא מגמרא. ויש לדון, שתו"כ קדם.  ואולי הוא מפני שגמרא רק מביא תו"כ.
** שני דרשות -
גם היה אפשר לומר שדרש על הנשארות למה לא נשרפו אם היו הנשרפים נשרפים (למה חילק).
** לא בזרה -
יש לדון אם כשאומר שיכול לעבוד, בא לבאר למה יכול לעבוד (שמזכיר זה שם) או למה אוכל. ותחשב.
** קב: כלפי לייא -
משמע יותר- לשון זה (“משמע") מעניין, שר"ל כאן שהוא מסתבר יותר. ותו"ת.
** קד: ושוין -
ואם תאמר נמצא גם כן אם מכוון ל"אכילת" אש. ויש לומר שמעשה שצריך להיעשות לו אינו של אכילה (שם זה לא עיקרי). ויש לדון אם זה נכון ואם זה מהני. ותו"ת.
** מהו -
מפרש נפקא מינא או כדי לומר למה שייך לכאן או כדי לפרש שאין זה תלוי על שאלת גמרא בחולין (ע) בזה. צריך לפרש כן כיון ששם פשט וכאן לא פושט, ואוד שלא יודע לפשוט השאלה או לדעת שאין ההוה אמינא בשאלה מסתבר משם. ויש לדון, שהם אמוראים חלוקים. ותחשב.
** קח: אכל בהמה -
מה שאומר שהוא אחד מעניין, שהיה אפשר לומר שר"ל שכיון שאין מקרבים רק חלק ממנו לחייב, נמצא שלא חייב כלום. ודע שצריך ביאור לרש"י למה שייך דין של העלאת אבר לאם נחשב אחד או לא. היה אפשר לומר שלעולם נחשב די אחד ודי שנים, ואז היה יכול לחייב שנים, ויכול לחייב אחד, אם צריך לזה כדי לחייב. ודחוק. גם יש לומר שכיון שזה צריך לזה, יותר מיוחסים זה לזה, ואז יותר נעשים אחד. ויש לדון.
** גובהה -
כדי שיהיה נוח- נראה שאולי זה פו"ן, שאומר שנוח עשה דבר כדי שדבר יהיה יותר נוח. ותו"ת.
** קיב: משיזהיבו -
עיין בחולין במה שמפרש רבא בביאור הדרשות, ועיין במה שאומר רש"י כאן. ותחשב.
** קיג: מהבלא מתו -
עיין במה שאמר שקברום. ק"ק למה לא אמר שפינו אותם מתי מבול. ועיין במה שנכתב בס"ד על גמרא בד"ה שקצים ורמשים.
