* *ב.*
:PROPERTIES:
:CUSTOM_ID: ב.
:END:
*לשכת האבן*- במקום אחר דנינו למה נקרא שמה לשכת האבן, ולא נקרא אחר כלי
אחר מן הכלים שהיה שם. ויש להעיר שכיון שנקרא לשכת האבן, מעניין שאבן אינו
הנמנה ראשון או אחרון. לכאו', יש יותר סיבה לנקוט אחד מהם (כמו שאומר גמ'
גיטין פב:, וכעין גמ' בתחילת נדרים ונזיר). אז, היה לו לכ' אבן ראשון או
אחרון.
*כי היכי*- גמ' לעולם מפרש שנתנו בו חומרים אלו כדי שלא יזלזלו בה. יש
להעיר שלכאו', יש תוצאה אחת מאלו, והוא שיותר קשה לטמא אותה, ואף אם
מזלזלים בו מעט, אולי לא יטמא.
*היכירא*- לכאו', ר"ל שמחמת זה בני אדם יכירו שהוא יושב שם לצורך הפרה;
(ויכירו, אז, איזה מעשים צריכים פרה) וצריכים שבני אדם יכירו כיון שכל
צורכו הוא כדי שיכירו בני אדם בחומר טומאת כהן העושה פרה האדומה.
*מפרישים*- בכל כעין זה, יש לדון אם הענין הוא שצריך להיות שם או שלא טוב
שיהיה במקום אחר. ותו"ת.
*אימא כולא*- ר"ל, אינו מיותר.
* *ב:*
:PROPERTIES:
:CUSTOM_ID: ב
:END:
*צווה דיוה"כ*- קשה למה יאמר ה' גז"ש כזה; לא יאמר גז"ש כלל. אולי יותר קל
לזכור שאין לדרוש ג"ש לפרה אחר שיודעים שדורשים ג"ש לזה.
*מי איכא דבר*- יש להעיר שלפניהם אין קדושה, אבל לפני יום זה, יש קדושה.
*צווה דיוה"כ*- לכל אלו, נמצא "לכפר" לא נצרך. ויש לדון אם מיותר הוא. גי"ל
שצריך אותו לבאר איך לדרוש צווה. ותו"ת.
*מי ידעינן*- לכאו', היה אפשר להקשות כן לעיל. אולי כבר היה לו קושיה אחרת.
גם אפשר שסברה אינו מכריע כל כך בדרשת ג"ש כמו בדרשות אחרות, שג"ש ניתנו
בסיני. הסיבה, אולי, שצריכים סברה בדרשה הוא שכך ניתן, שה' אמר דבר שקשה
להבין ואומר שלנו לדרוש אותו מסברה שלנו. אבל, אם ה' אמר בהלכה למשה מסיני
איך לדרוש, אין הוכחה שמה שאומר צריך להיות מכוון לסברה שלנו. ויל"ד.
*אי חג*- היהי אפשר לומר שכל סיבות אלו שוות.
*לא ידעינן*- ואם תאמר איך זה עושה שדורשים יום הכיפורים, שאיזה סיבה יש
להעדיף אותו, ויהיה בכלל הספק.
*מי איכא מידי*- קשה שאין הכי נמי, ונדרוש מזה שכל סוכות בעי פרישה.
*דבר הקבוע*- יש להעיר שהיה אפשר לומר שאין ימי מילואים תלוי בזמן באופן
שיום הכיפורים קבוע בזמן, והוא שלכאו'ה קרבנות של ימי המילואים תלוי בחנוכת
המזכן, וזה תלוי בזמן, אבל הוא עצמו לא תלוי בזמן. נראה שאינו קשה, שגמרא
לא אמר שהוא תלוי בזמן, אלא שהוא קבוע בזמן, וזה בוודאי אמת.
*פעם אחת*- יש לדון בזה, שהיו שבעת ימי מילואים. צ"ל שהיו המשך אחד (לכאו',
ר"ל שכל אחד עשה טוב עם חבירו). גי"ל שהיה רק שבעת ימי הפרשה אחד.
*פתח בו הכתוב*- מעניין שזה מעלה, שלכאו', לא פתח בו הכתוב ראשון מחמת
טובתו, אלא מחמת שקורה ראשון. ואם תאמר זה גופא חשיבות, אין הכי נמי, אבל
אז קשה ל"ל אמר גמרא אותו חשיבות.;
* *ג.*
:PROPERTIES:
:CUSTOM_ID: ג.
:END:
*תשלומים דראשון*- צריך ביאור, שהיה נראה לומר שיש שני דברים: הוא יום טוב,
ויש בו, אז, פז"ר קשב, והוא גם יכול להיות עושה בו דין תשלומים. אז, קשה
למה צריך להיות עיקר הרגל בעי פרישה, שאין זה רק טפל שלו. ותחשב.
* *ג:*
:PROPERTIES:
:CUSTOM_ID: ג
:END:
*למה לי*- קשה, שאולי הוא לחדש שרצה ה' משלו. אולי לא היה כתיב קרא מיותר
לחדש כן.
*מתניתין ר"י*- אז, צריך ביאור מהי"ת שיש תנא אחר חוץ ממנו.
*תחלה*- יש לדון מהי"ת שלא רק עושים כן ביום הכיפורים הראשון. אולי לא
מצאנו חילוק אחר בין יה"כ ראשון לשאר יה"כ. שו"ר שגמ' לקמן דן בכעין זה
(ד.).
* *ד:*
:PROPERTIES:
:CUSTOM_ID: ד
:END:
*מעכב*- ואם תאמר היה לו להקשות שמה שהיה היה, ואין נפקא מינא. ונראה שיש
נפקא מינא לענין דרשה.
* *ה.*
:PROPERTIES:
:CUSTOM_ID: ה.
:END:
*אשר ימשח אותו*- צריך ביאור למה חילוק זה צריך קרא, אבל מה שלא צריך הפרשה
קודם שנעשה כה"ג לא צריך קרא. אולי יש שום קרא שלא מביא גמרא (כיון שכבר
הביא ראיה לדין).
*יום אחד... שבעה*- יש להעיר שהדין כן אף אם אין מושחים אותו כלל, וכל שכן
אם לא עושים אותו לשבעת ימים. ותחשב.
* *ו.*
:PROPERTIES:
:CUSTOM_ID: ו.
:END:
*אטו ברשיעי*- אפשר שמקשה שאם ברשיעי עסקינן, למה דנים בדינם, שלא ישמעו
לנו. וצריך לראות אם במקומות אחרים שאומר כעין זה אפשר לפרש כן.
*כר"ע*- לכאו', בוודאי אפשר להיות שתהיה נדה בשעת ביאה. אז, קשה ל"ל נחוש
לזה. (ר"ל, משמע מגמרא שרק חוששים שלא יוכל לעבוד, ולא שיהיה פסול ולא יהיה
ידוע.) אולי כיון שיכול לסמוך אז ולעבוד אינו רע, אף שבאמת אשתו היתה נדה.
זה מחודש.
נראה שאפשר שזה רק אינו חשש מצוי, ולא נחוש לו אם לא שנצרף עמו (ואולי אף
לא צריך אותו חשש לצירוף כלל) חשש שמא תראה אחר כן ונצטרך להניח שהוא טמא
(ולא יוכל לעבוד). ותחשב.
* *ו:*
:PROPERTIES:
:CUSTOM_ID: ו
:END:
*הותרה*- עיין לקמן, שאומר שלא אפשר לומר שהוא הותרה בקרבן זה. (ואולי זה
לא קאי למס' שהוא מח' תנאי; שם, באמת, חוזר בפירוש.)
* *ז.*
:PROPERTIES:
:CUSTOM_ID: ז.
:END:
*שלו*- באלו שהם קצת דוחים, קצת צריך ביאור, שלכאורה, מקורם הוא משאר
קרבנות ציבור. אז, קשה, שאין דינים שווה; אז, קשה איך נלמדים. ותחשב.
*למה לי לרצויי*- היה אפשר לומר שאף אם הותרה, ואין אותו ס"ר, זה רק עושה
שאין ס"ר לאיסור, אבל עדיין פסול הוא. נראה שסובר שאותו סיבה רעה ואותו
סיבת הפסול הם שווים (או שזה גורם זה וכדו').
*עם העומר*- מעניין שנחשב זמנו קבוע. לכאורה (אבל לא מוכרח), מה שצריך
להיות בפסח אינו מפני שזמנו אז, אלא מפני שהוקרב קרבן העומר אז. נמצא שמה
שתלה בדבר אחר, ולכן זמנו קבוע, נחשב לזה זמנו קבוע.
* *ח.*
:PROPERTIES:
:CUSTOM_ID: ח.
:END:
*נשבר הציץ מנא ליה*- ואם תאמר ידע אותו ממה שצריך להיות על מצח אהרן. אולי
יש הו"א שיש טוב שבא כשהוא על מצחו, אף שנשבר. לא נראה כן, שנראה שפשוט
לר"ש שאין זה נקרא ראוי למצח. ותו"ת. יותר נראה שצריך שני קראי, שאילו היה
רק קרא אחד, היינו אומרים שהוא לכדרבי שמעון.
* *ח:*
:PROPERTIES:
:CUSTOM_ID: ח
:END:
*אלא בקביעא*- משמע, לכאורה, שלא משנים קביעות החודש כדי שלא יחסר עוד יום,
ואף שקדשו על פי ראייה.
* *ט:*
:PROPERTIES:
:CUSTOM_ID: ט
:END:
*בירה*- יש שאומרים שהחזיר ה' בירה כיון שהיו צריכים לו. לכאורה, גמרא זה
משמע נגד זה, שאם כן, אינו ראיה שהם יותר גדולים ממנו.
* *י.*
:PROPERTIES:
:CUSTOM_ID: י.
:END:
*גזירת מלך*- לכאורה, בין כך ובין כך הוא גזירת מלך, אלא דן אם הוא גזירת
מלך בלי טעם. אם כן, מש"א גמ' זה ק"ק, שנמצא שאינו גז"מ. אולי ר"ל שאף היה
קל לת' שהוא גזירת מלך. ותחשב. גם יש לומר שגזר כן ה' בלי טעם, ולבסוף נמצא
שהיו אף בונים ראויים ליפול.
* *י:*
:PROPERTIES:
:CUSTOM_ID: י
:END:
*דילמא אתי*- קצ"ב, שמצאנו כמה זמנים שרבנן גזרו על המעשר.
* *יא.*
:PROPERTIES:
:CUSTOM_ID: יא.
:END:
*חזוק*- לכאו', נמצא ששער שלא נעשה להליכה (אף אם מהלכים בו) פטור ממזוזה.
אולי זה היה רק דיחוי, אבל תשובתו האמיתי היה השני. דחוק.
* *יא:*
:PROPERTIES:
:CUSTOM_ID: יא
:END:
*מהו דתימא*- עיין בקידושין, שאומר הו"א אחר.
*ביתך ולא ביתה*- לכאו', ר"ל "ביתךָ," ולא ביתָך." ותחשב על זה.
*דרך ביאתך*- נראה שאולי לא רק דורש המילה, שזה, לכאורה, לא מפרש דיוק של
ביתך ולא ביתה. אלא, נראה שאולי איש הולך באופן חלוק מאשה (ולכן מדוייקת
לומר שכי הולך איניש, עקר...), וחייב לתת מזוזה של דרך ביאת איש.
* *יב.*
:PROPERTIES:
:CUSTOM_ID: יב.
:END:
*לבלעו*- יש לדון אם ר"ל שהיה מצטער על רצונו לבלוע או שהיה מצטער ומתפלל
כדי לבלעו. ותו"ת.
* *יב:*
:PROPERTIES:
:CUSTOM_ID: יב
:END:
*בהנך דשווים*- בין כך ובין כך, צריך להיות שלא מדבר על הכל, שלא מזכיר
חילוק עבודות.
* *יג.*
:PROPERTIES:
:CUSTOM_ID: יג.
:END:
*צרה מחיים*- יש לדון אם הקמ"ל הוא שלא חוששים שיחשב כה"ג כך או שאינו בעיה
כשחושב כן. יש להעיר שכבר יש כמה בני אדם שרוצים במיתתו (כל הרוצחים).
*שני* *בתים*- צריך ביאור למה כל כך פשוט שנחשב שני בתים, שהיה אפשר לומר
ששניהם בית אחד, שהוא בית שלו. ותחשב. ונראה ש"בית" ר"ל אשה, ולא שבית ר"ל
דבר אחר, ויודעים שכוונתו לאשה, ואז בוודאי שני נשים הם שני בתים. ותו"ת.
*אחת מכם*- גם יש לחוש שחברה תמות.
*כריתות*- קשה, שזה יכול לבוא לידי כריתות, שיכול להיות שחבירה תמות ראשון.
* *יג:*
:PROPERTIES:
:CUSTOM_ID: יג
:END:
*ולאדך*- היה אפשר לומר לאחד שהיא מגו' ע"מ שמתה קודם גמר יום הכיפורים
ולאחר לומר שהיא מגו' ע"מ שיכנס לבית הכנסת.
*קדים איהו*- לכאו', לא צריך לקדם, שמהני כל זמן שהולך לשם, ואף אחר מיתתו,
שחל למפרע. ותחשב.
* *טו:*
:PROPERTIES:
:CUSTOM_ID: טו
:END:
*ניתיב*- נראה שהסיבה שיותר טוב לתת חטאת קודם הוא כמה שאומר גמרא זבחים
שלעולם חטאת קודמת לעולה.
*יט.*
*לבהדי פניא*- כמו שפירש אביי לעיל לבאר את המשנה לפי רבי עקיבא. שו”ר
שרש"י מעורר כן.
*מטרחינן*- אבל ביום הכיפורים עצמו לא מטרחינן אותו, כמו שכ' בגמ' זבחים
(קרוב לדף כ).
*יט:*
*על דעת ב”ד*- נ' שר"ל שכשאומר “שליח ב”ד,” ר"ל שבשבועה זה, אתה שליח בית
דין, שאתה שנבע על דעתם. לשון שליחות ע”ז קצת מעניין.
*שחשדוהו צדוקי*- לכאו', בוכה על זה מחמת מה שאומר גמ' שכל מי שנחשד יש לו
מקצת מאותו עוון.
*אר”ז*- במשנה שלנו, לא כ' “רבי.”
*בקש להתנמנ*- משמע שהיה ער רק ליל יוה”כ. עיין לעיל (מה היה אוכל) ובשיח
שי על משניות שם (השלמות) שבארנו שצריך להיות שלא רוצים שישן לילה לפני יום
הכיפורים. אולי עדיין ישן קצת באותם דברים. גי”ל שרוצים שיישן אותו לילה,
ורק לא רוצים שיישן בליל יוה”כ, ואכילת הרבה גורם שאוכל אף לאחר זמן. עיין
שם. גי”ל שלא רוצים שיישן, אבל אם ישן, אף שאין לו לישן, צ”ל שמוכרח ממש
לשינה. אז, לא מקפידים עליו. אבל, ביוה"כ, מקפידים עליו.
*והא האידנא*- לכאו', אומר זה לסיבה למה היה לו למשיח לבוא. צריך ביאור למה
יבוא מחמת זה. ותחשב.
*כא.*
*עד שישנה*- יש לדון מה אומר:
- דמו רק בראשו אם עושה כן שני פעמים.
- צריך לשהות לא רק לקריאה אחת, אלא לשני קריאות.
*לא יארע קרי*- גמ' מבאר אשה שהיתה כל בניה כהנים גדולים. אם לא אירע קרי,
צ”ל שמתו כולם, ובא כה”ג אחר. אולי יכול כה”ג לresign. ותחשב. גם אפשר שהיה
פסול אחר. גי”ל שכל אלו אולי הם רק בבית ראשון, אבל מעשה זה היה בשני.
ותחשב. גי”ל שלא מתו קודם זמנם, אלא היא האריכה שנים. ותחשב.
*תרתי*- לכאו', ר"ל שצ' לגורסם במשנה, שאל”ה נ' שעדיין קשה.
*כא:*
*קביעי*- צריך להגדיר, שאף מה שעשן לא הלך ממקומו היה קבוע, לכאורה. ותחשב.
* *כב.*
:PROPERTIES:
:CUSTOM_ID: כב.
:END:
*בראשונה*- לכאורה, זה אגב משנה שלעיל. מענין שניתן בתחילת פרק חדש.
*מרובים*- לכאו', רק צריכים שנים. נמצא, אז, ששנים נקראים מרובים. (אולי אם
היו שנים, מסתמא היה אחד מוותר לחברו.)
*בד"א*- צריך ביאור למה תלוי בד"א, ולא במי מגיע לראש מזבח. אולי אף אם לא
זכה, כיון שהוא שם, יתרום. אז, רוצים שיבחנו קודם לכן.
*לא מסיימא*- לכאו', ר"ל שקשה לראות מי קדם לשם. ותו"ת.
* *כב:*
:PROPERTIES:
:CUSTOM_ID: כב
:END:
*אשר לא ימוד*- אינו, אז, כל כך דומה לחול, שנמדד על ידי חרס.
*וכתיב אשר*- זה רק קשה אם מניחים שהוא הבטחה ולא לאו. נ' שזהו אחד מת'
גמ'. ויל"ד, שאולי אומר שמנינו הוא דבר שאי אפשר להימנות ע"י אדם.
*מאי רבותא*- צריך באיורמה ר"ל.
*נפש אחת*- משמע מזה שמביאים עגלה ערופה על גוי, ושהריגת גוי הוא אסור.
באמת, שאול טעה בזה, אבל לא מסתבר לומר שטעה כל כך. ותחשב.
*הא אפרעו מיניה*- קשה, שלא היה מגופו. אבל דע שאף של שאול לא היה בגופו.
ותו"ת.
* *כג.*
:PROPERTIES:
:CUSTOM_ID: כג.
:END:
*דנקיט ליה בליביה*- משמע שאין בזה איסור נקימה.
ואם תאמר הרי זה דומה לנטירה אבל לא לנקימה. אולי אומר שכשיש סיבה אחר
שאינו נותן לו, יכול לשמוח על מה שלא ננתן לו מחמת זה. ותו"ת.
* *כו:*
:PROPERTIES:
:CUSTOM_ID: כו
:END:
*אבל בקרבן יחיד*- משמע שזה אף בישראל. ויש לדון, שדין זה נאמר בדרך כלל
בכהנים.
* *כח:*
:PROPERTIES:
:CUSTOM_ID: כח
:END:
*בא בימים*- צריך ביאור איך רואים מכאן שישב בישיבה. ויש לומר שר"ל שזקן
וממילא ישב בישיבה. ותחשב.
*תורותי*- נמצא שדין דרבנן נמצא תורה שבעל פה.
*כט:*
*לילה*- צריך ביאור למה אין להקשות שלילה יפסל בכל ציור, ואף אם נתנו
בזמנו. אז, צריך ביאור איך תירוץ שני מהני. ותחשב.
*ל.*
*כה"ג*- קשה, שכה"ג נכנס לעבודה. וי"ל שחולק על משנה שלנו, וסובר שרק טובל
אם עושה עבודה.
*ל:*
*כל אדם לא דיישי*- א"כ, חול' על משנה שלנו, ואומרים שאין כל אדם צריך
טבילה.
*לא מצורעים*- אם כן, לכאו', לא סובר שנקרא לשכת מצורעים.
*לא.*
*שמה ביאה*- ואם תאמר עדיין יש להסתפק לפי רבי יהודה. ויש לומר שלר"י, הוא
גזירה אטו איסור ביאה, ואז תלוי בשאלה בזבחים אם נחשב ביאה לענין איסור
ביאת טמא. ותו"ת.
*לב.*
*שכל הפרשה*- קשה, שגמ' אומר שאין אומרים "אין מוקדם ומאוחר בתורה" אלא
בשני ענינים.
*לב:*
*לא ר"ח*- היה אפשר לומר שמודים זל"ז ורבי סובר שאינו הל"מ שצריך עשר
קידושין, אלא רק שצ' חמש טבילות.
*לג:*
*דרעא*- צריך ביאור, שלכאו', יש סיבה אחרת, והוא ש"כל זמן שהם בין
עיניך...." אולי לא סובר כאותו דרשה. אבל, דע שמחודש הוא לומר שמה שבא לידו
ראשון הוא סיבה לחייב בשל יד קודם, שהיה נראה יותר לומר שתלוי מתי בא
לתפילין של יד, שאז יכול לקיים מצווה. אולי מניח ששני תפילין שלו הם במקום
אחד. כיון שיותר קל לו להביא ידו אל ידו (מסתמא כן הוא), אפשר לקיים מצוות
יותר מהרה אם נותן של יד קודם. מעניין שזה נחשב מעבירים על המצוות. ותחשב.
*לד:*
*ואמר אביי*- צ"ב ל"ל רק הקשה שבעל המשנה הוא רבי יהודה.
*וצריכי*- סברות אלו צריכים ביאור. לכאו', אומר שחובה אולי צריך להיות יותר
נאה כיון שיש יותר צורך בו. הראיה לזה הוא שהצריך ה' אותו. צריך ביאור למה
נדבה צריך להיות נאה. אפשר שהוא העושה יותר, והא שלא חייבו ה' הוא מפני שרק
עושה יותר כיון שהוא עושה אותו מדעתו. (ואם תאמר הרי גדול מצווה ועושה. ויש
לדון אם זה עושה שהקרבן אינו יותר טוב; אולי עדיין הקרבן יותר טוב, אבל
בכלל המצווה אינו יותר טוב, שקיום ציווי ותר טוב. ותחשב. גם יש לחלק בין
מצווה לקרבן (ואז אף בסיבה, ולא בציווי, אולי יש חילוק.)) גם אולי כל קרבן
רע אם לא עושה הרצאה חשובה (יש לדון למה), ואז אולי צריך שיהיה נאה כדי
לעשות אותו הרצאה חשובה. ותחשב.
* *מא:*
:PROPERTIES:
:CUSTOM_ID: מא
:END:
*דבעי חלוקה*- אם כן, רק יהיה השיעור כדי חלוקה. נ' שמקשה ששניהם צ' שיעור
כזה, וצריך לומר שיש שיעור שלא מוגדר כך. וקשה לל"א שצריך שיעור כדי קשירה.
ותחשב.
* *מב.*
:PROPERTIES:
:CUSTOM_ID: מב.
:END:
*בדק הבית*- ר"ל, אין דבר שהוא עבודה, ואז אין סיבה לחשוב שאין הקרא קאי על
זה. כן נראה מרש"י, וכן פשוט לפרש בגמ'.
*רב*- צ"ב איך אמר על דבר שר"ז, תלמיד של ר"י תלמידו, אמר.
*למעוטי*- צ"ב מהי"ת שממעט כלום.
* *מב:*
:PROPERTIES:
:CUSTOM_ID: מב
:END:
*כה"ג*- צ"ב למה יותר פשוט שהחילוק לדורות הוא לקולא. להיפך, בדר"כ דורשים
לחומרא.
* *מד.*
:PROPERTIES:
:CUSTOM_ID: מד.
:END:
* כפרתו קודמת לכרפת ביתו*- צריך ביאור מה מכפר רק לו. עיין בגר"א.*
:PROPERTIES:
:CUSTOM_ID: כפרתו-קודמת-לכרפת-ביתו--צריך-ביאור-מה-מכפר-רק-לו.-עיין-בגרא.
:END:
* *מד:*
:PROPERTIES:
:CUSTOM_ID: מד
:END:
*חולשא*- לכאו', הוא לשני טעמים:
- הוא עובד כל עבודות היום.
- לא אוכל.
*משום חולשא*- צריך ביאור למה בכל יום שופך, ולא רק נוטל באחד. אולי היה
מזיק אותו אחד אם היה חותה בכל זמן. ותו"ת.
*שם פרישה אחת*- לא הבנתי ל"ל ת' שאף זה בכלל "אינו בשעת הק',” שזה פשוט
לת'.
*מכולה עזרה נמי*- ואם תאמר נביא ראיה ממה שלומ' מג"ש. אולי הו"א שתק' רבנן
כן כנגד ג"ש. זה מחו'. אולי ג"ש להיכל וגוז' אטו היכל בשניהם. כ"נ, שנ'
שאין גמ' מצדד שדין עצמו הוא דאו'.
* *מה.*
:PROPERTIES:
:CUSTOM_ID: מה.
:END:
*משום כבודו*- עיין ברש"י על המשנה שלא ממש אומר כן. עיין שם, שלכאו' חושב
שאומר כן, וצריך, אז, ליישב (ולא נוכל לומר שלא גורס כן). ותו"ת.
* *מו.*
:PROPERTIES:
:CUSTOM_ID: מו.
:END:
*סופו*- יש לדון למה:
1. הוא רק סופו.
2. הוא רק של ע"ש.
*נראה שהחילוק* בין של ע"ש לבין שבת הוא ששל שבת נתקדש ממה שהוא בשבת, כמו
שאומר גמ' בסוף זבחים (גבי תדיר ומקודש).
* *מו:*
:PROPERTIES:
:CUSTOM_ID: מו
:END:
*בר מדחיא*- ואם תאמר הרי גם אינו בטומאה, שהרי אינו טמא אז. ואם תתרץ
שאילו היה טמא, היה דוחה, הרי אילו היה שבת, היה דוחה. ויל"ד, שאולי אז
הקרבן היה משנה, כמו שכתבנו. (גם יש לומר ששינוי בין שבת לחול הוא יותר
גדול, ועל זה אי אפשר לומר ראוי.)
*סופו נמי דחי*- לכאו', ר"ל שגם הותר.
*דחוייה*- נמצא שיש שני דינים מפסוק אחד, ודין אחד הותרה ודין אחד דחוייה.
* *מז.*
:PROPERTIES:
:CUSTOM_ID: מז.
:END:
*קורות בית*- אם הייתי בעל מוסר, הייתי טעון שזה גופא הוא הסיבה למה היתה
חלוקה משאר בני אדם, והוא שהאמינה שזה סיבה לדבר כזה. ותחשב.
*שבעה בנים*- מסתמא, היו צדיקים, שאם לא כן אינו כל כך זכות לאמהם. (ויש
לדון, שאולי היו ע"ה שהיו כה"ג, ולא סתם ע"ה. אבל לא נראה כן, שהפרישו
מבגדי ע"ה, ועוד שאינו טוב לע"ה להיות כה"ג, שעובר על יותר.) אז, מעניין
שלא מונה אותם בטובים. אולי היו בבית ראשון.
*כופה שלש אצבעות וקומץ*- יל"ד אם כופה בתוך הכלי או בחוץ ומכניס כך.
* *מז:*
:PROPERTIES:
:CUSTOM_ID: מז
:END:
*פשט... ספק*- מעניין שיכול לומר שפשט אותו לספק. ותו"ת.
*אי הכי*- אל, אם באמת יש לחוש. יש להעיר שכבר אמר לעיל שצריך לחוש.
*נמי לכתחילה*- משמע שתקנת עצים אינו לכתחילה. אולי ר"ל שאף אם הלכה כר"א,
טוב לחוש לרבנן. דחוק, שמשמע שר"ל לשיטת ר"א, והרי ר"א לא חש לרבנן, לכאו'.
* *נ:*
:PROPERTIES:
:CUSTOM_ID: נ
:END:
*בקופיה*- עיין במה שפרש"י. היה נראה שאולי כפרת המתכפרים שווה, ורק דן למה
מתכפרים, אם הוא מפני קנין לבהמה או מפני דבר אחר. אז, מניח שמה שאומר
שמתכפרים הם הבעלים הוא רק סימן לקנין שלהם, שיש להם קנין שעושה שהם
הבעלים, ואינו מחמת שהם מתכפרים. ותו"ת.
כן נראה מרש"י, אבל מגמ' לקמן (נא:) נראה שצריך לומר שיש קנין למתכפרים.
ותחשב. (ויש לדון, שאולי רק ר"ל שבהכרח חידש תורה דבר, והוא אולי שלא צריך
קנין או שמכפר בקבעא, והקנה תורה. לא משמע כן שם.)
* *נא.*
:PROPERTIES:
:CUSTOM_ID: נא.
:END:
*שם תמורה אחת*- לכאו', ר"ל שקדושה של כל תמורה שווה. ותחשב. וע' ברש"י,
שמשמע שאינו כל כך לומדיש.
* *נב:*
:PROPERTIES:
:CUSTOM_ID: נב
:END:
*משנגנז*- ואם תאמר ל"ל רק הביא משנה לקמן. וי"ל שזה לא אומר מתי נגנז.
* *נג.*
:PROPERTIES:
:CUSTOM_ID: נג.
:END:
*שלא תתחיל*- לא הבנתי כל כך למה הוא יותר טוב אם מתחיל מבחוץ ומכניס ידיו
בפנים.
*חד*- לכל אחד מאלו, צריך לפרש ל"ל יצטרך קרא למה שאומר חברו.
* *נג:*
:PROPERTIES:
:CUSTOM_ID: נג
:END:
*שהרי שנינו*- משמע (אבל לא מוכרח) שאמרו לו את המשנה. אם כן, נמצא שמשנה
זה היתה כבר ידועה בימי בית המקדש.
*מימינו*- עיין ברש"י. נמצא שסובר שזה סימן, ולא סיבה. וצריך ביאור למה אין
נקודה זה שייך אף בקרא שני. אולי זה יכול להיות סיבה. ותחשב.
