* ג:
:PROPERTIES:
:CUSTOM_ID: ג
:END:
*תחלה במקום*- חלוק לבן- ואם תאמר ל"ל מזכיר שהיה משה זר. וי"ל שלאותם ימים
(ואולי אף אחר כן; עיין בסוף זבחים) היה משה נחשב כהן. ויש לדון, שלאותם
ימים, נאמר שהיה חלוק לבן נחשב בגדי כהונה, שהרי כשר היה, מה שאין כן אילו
היה כהן לובשו, שלא היה כשר. אלא, צריך לומר שממה שלא כשר בדר"כ, צ"ל שאינו
כל כך טוב. אז, נוכל לומר ג"כ במשה שכיון שלא בא מכהן, אינו כל כך כשר.
נראה שאולי בכהנים ראשונים, לא היו יחוסם עושים אותם כהנים. אז, ממילא לא
היה חילוק בין משה לאהרן וכודמה. ויש לדון, שעדיין נוכל לומר שלא היה כהן
כל כך, והראיה יהיה שלא הוליד כהנים. ויש לדון, שאולי זה רק מפני שלא הוליד
כלל אחר שנעשה כהן (וכמו מה קרה לפנחס). ותחשב. גי"ל שאינו כהן כל כך כיון
שלו לא נעשה שבעת ימי מילואים. ותו"ת.
* ד:
:PROPERTIES:
:CUSTOM_ID: ד
:END:
*במקום גילה*- עיין במה שפירש. עיין בגמרא ברכות, שמדרשה שאמר שם מקרא זה,
לא נראה שזה קאי על מתן תורה. לולי רש"י, היה אפשר לומר שאין הכי נמי,
ודרשה זה רק הובא אגב.
נראה שרש"י סובר שכולל כל מקום גילה, ואז כולל נתינת התורה, וכולל תפלה
(שם). רש"י רק מבאר מהו המקום גילה כאן, ולמה הוא שייך.
*שהוא בבל יאמר*- עיין במה שמפרש בדרשה. לולי זה, היה נראה לומר שדורש ממה
שאומר שה' צווה אותו לאמר. ויש לדון, שאולי היה אפשר לדחות שה' הוצרך לומר
כן כדי שיהיה ציווי. ואם תאמר הרי זה קשה אף לרש"י. אלא, צריך לומר שכבר
פשוט שצווה אותו לומר לבני ישראל.
* ה.
:PROPERTIES:
:CUSTOM_ID: ה.
:END:
*כאילו לא כפר*- מן המובחר- קשה, שאינו כאילו לא כפר מן המובחר, אלא לא
כיפר. אולי אין זה נכון, אלא מה שפגם אינו בכפרת הקרבן, אלא בדבר אחר. יש
לדון, אז, למה מעלה עליו הכתוב כאילו לא כפר. ותחשב.
* ז:
:PROPERTIES:
:CUSTOM_ID: ז
:END:
*הותרה*- מרשי יוצא שמביא ראיה רק מלשון היתר, ולא מדין של המשנה. אם כן,
מעניין ל"ל אומרים שנקרא כן כיון שהוא מותר, ולא מפני מה שמכונה בשם
"הותרה." צ"ל שמניח שאף משנה שמע לשון זה, ולא היה לו לומר לשון היתר כי אם
כשר"ל הותרה ממש. ותחשב.
* יב.
:PROPERTIES:
:CUSTOM_ID: יב.
:END:
*דכרכים-* מחודש שכיון שנעשה להרבה בני אדם הרי הוא שלהם. ותו"ת.
גם מעניין שיש חילוק בין אם בעליו ניכרים לאם בעליו אינם נכירים. ותו"ת.
* טו.
:PROPERTIES:
:CUSTOM_ID: טו.
:END:
*רישא וסיפא*- נראה שאף שמצאנו כן לפעמים אף שאינו באותו משנה, צריך לומר
ששם יש חד משנה אף שהם מוחלקים בגמ'. כאן, הם מאד רחוקים יותר משאר מקומות.
ותו"ת.
*יח:*
*באיוב*- מעניין שאלו נחשבים מושכים את הלב, שעכשיו לא נחשבים כן.
*יט.*
*שלוחי*- כדתנן- שם רק תנן שיכול להקריב קרבנות שאינו שליח עליו. (עיין שם
ובר”ן.)
*יט:*
*מחוטמו*- ע' במש”כ. קשה איך לא נכנס רגלו ראשון.
*ולא בתפלה*- גמ' בברכות לומד את זה מחנה.
*ולא בתפלה*- משמע מזה שלשון דיבור משמע דיבור בקול. לכאו', ההל' הוא
שיתפלל ע”י דיבור, ולא מח'. (אולי שאילתות חולק על זה.) ותו"ת.
אם כן, ייצא שאיסור דברים בטלים הוא רק בקול רם, אבל מותר ללחש אותם.
ותחשב.
*כ.*
*וברגלים*- עיין שם, שחלקו אם יש שלש או ארבע משמרות בלילה.
*כ:*
*לא היה אמורא*- עיין ברשי בתחילת מגילה (לשנותה ביום), ועיין בגמ' פסחים
(מים שלנו).
* *כב.*
:PROPERTIES:
:CUSTOM_ID: כב.
:END:
*ואם היו*- כולם- צריך ביאור למה כולם יצביעו, ולא רק אותם שנים. באמת, קצת
צריך לבאר למה בכל זמן מי שבא קודם יזכה, שהוא קצת רנדום[fn:1]. ותחשב.
*הצביעו*- צריך ביאור למה אחד נוטל מצנפת שלו, ומה לנו ממי התחלנו. ותחשב.
* *כב:*
:PROPERTIES:
:CUSTOM_ID: כב
:END:
*בבזק*- שברי- קיל"ד איך ידעו שלא שברו יותר אחר כן.
* כו:
:PROPERTIES:
:CUSTOM_ID: כו
:END:
*אתרוגיהם*- מעניין שלא רק דייק ממה שהיו שם אתרוגים. ותו"ת.
*לא.*
*מהו*- יושיט ידו לפנים- צ"ב, שאז יש ביאה במקצת. לולי רש"י, היה נראה שרק
מושיט סכין בפנים. ותחשב.
*לא:*
*רבנן*- היה אפשר לומר שהם חביריו. יל"ד מהי"ת לרש"י שהיו תלמידיו.
*לב.*
*מאי טעמא*- מעמש שהדיון הוא למה הדין הוא כן, ולא המקור. אז, אומר שהסדר
הוא כך כדי שיהיו מנין טבילות וקידושין אלו.
היה אפשר שרק שואל מהו המקור. אבל, לשון שאלת גמ' משמע כמה שאומר רש"י.
אבל, קצת מעניין שישאל למה, שהרי לא שואל למה על שאר עבודות. ותחשב.
*לג.*
*אביי מסדר*- של כל יום- יש ממנו שאינו בכל יום, אלא רק בשבת ויו"ט. ותחשב.
אולי ר"ל שמזכיר כל דבר שנצרך בשום יום.
*משמיה*- עיין במה שפרש. צריך ביאור איך למד אותו מכולם. ראשון, צריך לדון
אם למד כולו מכולם או מקצת מכל אחד. אם נאמר כשני, צ"ל שלא היו כ"כ כמה
תלמידים. (עיין בעירובין, שהיו שיעורים שהיו קטנים מאד.) אם אמר כראשון,
צ"ב למה צריך לכולם, ולא רק לאחד מהם. ותחשב.
*לה.*
*תנא מניינא*- עיין במה שכ'. לולי מש"פ, היה נראה לי שמקשה מה לנו מהו
המנין. אז, אף אילו לא היינו יכולים לעמוד עליו, מה צורך לנו לעמוד עליו.
ותחשב.
*מד.*
*לשון הרע*- סתם לשון הרע- אף שמה שכפר לו לא היה בחשאי, אלא ברבים.
*מו.*
*מאי אינו*- והראשון נראה- איני מבין חי'; אולי ראשון סובר שלא נקטר בשבת.
קשה, שמשניות דנים בהק' למזבח.
*נא:*
*שולחנות*- עיין במה שאומר רש"י. צריך ביאור למה הולך בין שולחן למזבח,
שבין כך ובין כך, יהיה מול המזבח, ורק יהיה חילוק מאיזה צד יוצא לשם.
*נב.*
*ורבי יוסי*- עיין במה שפרש"י. לולי רש"י, היה נ' לומר שענין הליכה שלא
להדיא הוא שטוב לאדם להראות הרחק בינו לה'. רבי יוסי אומר שכיון שמוסיף
שליח שלא נצרך, נמצא שהוסיף כבר הרחק.
[fn:1] יש בוודאי מושג כזה במילי דעלמא, אבל צריך ביאור למה. ותו"ת.
