** א. הא עם שעורים -
עיין במה שכתב. נמצא שההו"א ידע שהוא מין חיטין. מעניין, שגמרא לקמן מקשה ל"ל אסור זונים עם חיטין. משמע, לכאורה, שלא ידע שהוא מאותו מין. אם כן, יותר היה לו לומר שמדייק כן ממה שאומר חיטין כלל, ולא רק אמר שמותר עם הכל. אז, צריך לומר שרק מותר עם חיטין, ואף שאין כל כך סיבה לחלק. ותחשב.
** להביא -
מעניין שמהני מה שמביאים ממקום למקום, אף שאין זריעתו חשוב בכל מקום. ותחשב.
** פירש -
יש שני חידושים מקרא זה:
1. לא רק נוהג בצמר ופשתין, אלא האיסור הוא לתת צמר ופשתים יחד.
2. לומדים מכאן לכל דבר.
לכאורה, הראשון כבר נלמד מפשטות הקרא, ומה שאומר פני משה שיש ריבוי הוא ללמד השני. ותו"ת.
** א: רבא בשם רב -
מעניין למצוא רבא בשם רב. חושב אני שיש מי (חושב אני שהוא רשב"ם בסוף פסחים) שאומר שלא לעולם כשאומרים "בשם" או "משום" ר"ל שאמר ממנו (ורק אמר משמע כן), אלא ששמע מזה…, וכמו שאומר גמרא בנדרים (וע"ש באיזה נוסח משתמש שם).[fn:1]
גם אפשר שאין סתם רבא של ירושלמי שווה לסתם רבא של בבלי, אלא הוא רבא אחר. אז, שייך שראה רב ואמר דבר משמו.
** מחלפא -
צריך ביאור מהו הקושיה, שנאמר שכשרב אומר שכולם זוגות זוגות, לא ר"ל כמו שאמר ר"י, אלא ר"ל שמשנה זה זוגות. אם כן, אין סתירה עוד.
משמע שגמרא סובר שאין זה מסתבר. קשה, שהיה הוה אמינא בר"י, ולא דחה גמרא אותו. לכאורה, צריך לומר שכיון שר"י אמר אותו סתם, ולא כוון לזה, לא מסתבר שרב יאמר אותו סתם, ויכוון לדבר אחר (שהאחרון לא היה לו לומר לשון דומה בסתם).
** ב. אף -
לא הבנתי כל כך הראיה מזה, שאולי המשנה בזוגות, וזה הוסיף להיות שלא בזוגות. עיין בפני משה. מה שהקשינו קשה עליו, אבל לולי פני משה, היה נראה לומר שכיון שאומר משנה כמה דינים, היה צריך לפרש על מה מוסיף זה. אז, צריך לומר שמשנה אומר רק דין אחד, והוא שכל אלו מותרים עם כל אלו. ותחשב.
** ב: בתחום -
ר"ל ולטעמיך, נסמוך לו מכאן. ֝(ואז, יש סתירה, ועוד שאז אין קושייתך טוב.) אז, צריך לומר כמו שדוחה גמרא.
** זרגון -
בדיבור זה, לא מוסיף כלום. אולי מבאר מהו הגירסא. גי"ל שמבאר איך לקרוא אותו. אם כן, צריך לומר שהוא הנותן את ה".”ים וכדומה, ולא רק המדפיסים.
** אר"י
- חששא דכלאים- יש לדון אם ר"ל כן בדרך כלל (שגדר של כלאים של תורה הוא מראית עין, כיון שיש שום יחס בסיבתו למראית עין (עדיין צריך ביאור)), או רק באלו, שאומר שאינם כלאים מדאורייתא, אבל הם מראית עין, שנראים ככלאים.
** ג. תמן -
יש להעיר שה"הכא" ו"שם" משנה, שבעופות מחליף. ותו"ת.
** מצודה -
נראה שמזכיר לשון מצודה כיון שדן בדגים.
** אמר ר"י
- צריך ביאור למה צריך לדון בהנהגה כלל, ול"ל אומר רק שהוא מקריב אותם עד שיש איסור. ותחשב.
** ד. שהוא עתיד למתקא -
לכאורה, ר"ל שכשאומרים שלא מרכיב, רק ר"ל לענין אחד שבהרכבה, אבל עדיין עושה ענין אחר.
** שקמה
- לא ידעתי עד כאן ששקמה הוא תאנה של יער.
** ד: אתיא -
מעניין שאומר שהוא דבר שאינו מתכוון על המוקצה. לכאורה, המוקצה הוא פסיק רישא. אולי לא סבר כמסקנת אביי אלא כהוה אמינא שלו, וסובר שאף פסיק רישא.
** אתיא -
טלטול מן הצד- כיון שכבר יש היתר זה, צריך ביאור למה צריך היתר של רבי שמעון. אם כן, קשה למה צריך להיות כרבי שמעון.
** ניטלים -
לכאורה, מביא ראיה מן המשנה. ק"ק, שמשנה הוא כשעליו מגולים, ובזה אף חכמים מתירים. ותחשב.
** ה. שני מינים -
לכאורה, אין חילוק בין חורבה לבקעה. אם כן, ק"ק למה מחלקם.
** מודה ר"ל -
יש לדון למה מחלקם. נראה שהוא מפני שהם לשני סיבות. ואם תאמר אם כן למה כולל שנים ראשונים. ויש לומר שסיבתם שווה.
** פתר -
צריך ביאור מה אומר. לא הבנתי כל זה, אבל היה נראה לומר שחייב אם זרע אף קצת בתוך קרחת של ששה על ששה, אלא אם הרחיק די (שהוא, לפי ר"י טפח), אבל אין הכל טוב כזה. ותחשב על זה. וצריך ביאור.
** פתר -
דמהני- לכאורה, הת’ הוא שאינם זרעים כיון שהם בחור אחד; אז, אין גדר מפסיק, שאצ"ל כ"כ קרוב. ותחשב.
** ו: ר"א בשם ר"י -
מניח שקושיית גמרא הוא אף על מיעוט איסור. יש לדון בזה, שחייב לבער איסור, וממילא נעשה בטל. ויש לדון, שאולי היה לו לברר ההיתר ממנו, ושוב לזרוק את האיסור. על כל פנים, לולי פני משה, היה אפשר לומר שגמרא רק מקשה על הציור של הוספת היתר. ותחשב.
** מכיון שהתחיל -
לכאורה, רק אומר דינו, ולא מבאר כלום בזה. ותו"ת.
** רוב סאה -
אפשר שהענין הוא שכיון שאין החטים (ר"ל הכי גדול) רובו, נחשב הוא כלאים בשאר, והרי הוא גדול מרובע. ותחשב.[fn:2]
** טז: במחלקת -
יש להעיר שמפני משה נראה ששם חולקים מהו הדין לזרוע בין שני שורות של אותו מין, כמה צריכים להרחיק את המין משורה של אותו המין. כאן, אינו כן, אלא דנים כמה צריך להרחיק מין ממין אחר. לכאורה, אין הוכחה שהם תלויים.
צריך לומר שמניח שענין הרחק מין מעצמו הוא שאם נחשב שניהם כאחד, אז נמצא שמין האחר נזרע בתוך אותו המין, ויהיה כלאים. לאותו סיבה אסור לזרוע מין אחר באותו הרחק, שהוא נחשב אחד עם מין זה, וזה אסור. עדיין קצת קשה מהו הציור שם, שאם בצלים הם בתוך שמנה, אז יהיה אסור כמו כאן, ואם לא, אז, מה לנו בדלועים שבאידך גיסא, שנמצא שלא שינו את הדין כלל. ותחשב.
** יז. שהורעת כוחו -
יש לדון, שלכל אחד יש מעלה, שזה יש לו כוח בשמנה, ואז לא יצטרך כל כך אורך, אבל לאידך גיסא רק יש לו שמונה. ותחשב.
** שנים עשרה -
צריך ביאור איך לפעמים דורשים שצריך להיות מרובע, ואיך לפעמים הדרשה נשתנה ללמד המנין. ותחשב.
** ר’ ינאי -
לא הבנתי כל זה כל כך.
** מותר הוא לעשות -
ק"ק, שלכאורה, היו עלין קודם שטלטל אותם. אם כן, לכאורה, נאמר שכיון שנאסר, נשאר באיסור, כמו שהקשה גמרא לעיל. ויש לדון, שאף שם אי אפשר לזרוע אותם ממש בבת אחת, שאי אפשר לצמצם (אם לא שמוקימים אותו כרבי יוסי הגלילי). אם כן, צריך לומר שאינו צריך להיות שלא נאסר כלל. ויש לדון למה. נראה שהוא שמה שהיה אסור לזמן קטן עושה שאין איסורה קובע את שמה להיות כלאים כל כך. יותר מזה, כל זה מראית עין, ואז תלוי במחשבות בני אדם. לא כל כך כמה בי אדם ראו אותו, ומי שראה לא חושב כל כך עליו, ולכן לא נאסר מחמת זה.
** צריך ביאור
כמה צריך לרחק העלין. לכאורה, אם עומקה טפח, לטפח יהיה גידולין קרובים. ויש לדון, שאולי אינו רק hole, אלא הוא יותר דומה לditch, ויש מקום בצדדיו לפשוט את השורות. אז, הם הולכים לדרכים חלוקים מיד. ותחשב.
** עמוקה טפח -
לא הבנתי למה עומק טפח דווקא. אולי אם לא נאמר כמש"כ בדיבור לעיל, יש לומר שאם קרובים ליותר מטפח, נאסרים. ותחשב.
** יז: שמנה -
צריך ביאור מה אומר, שלכאורה, היה לו לומר, כמו בשאר, שיש שמנה בין דלועים לדלועים.
** יח: יחידים -
קשה, שעדיין הראה רבי יוסי שלפעמים מחמירים כאן מכרם. אם כן, לא קשה קושיית רבנן עליו. ותחשב.
** בא וראה
- בגמ’ שלנו, כתוב רבי מאיר ראשון.
** תלתא ביניים -
אחד הוא השורה עצמו, וזה לא מונה, שאינו שבע. אז, יש שני בינים של שבע, ואלו מצטרפים ליד’, ויש בין אחר שאינו גדול די להיות מתיר. ותחשב.
** אם נטלו שני שורות
, לכאורה, לא נשתייר כדי כרם. אם כן, צריך ביאור למה צריך קרחת. ותחשב.
** שני כרמים -
לכאורה, זה קרחת הכרם לרבנן, וצריך ביאור. נראה שיש חילוק בין שני כרמים לאמצע של כרם אחד. צריך ביאור מהו ההפרש. ותחשב.
** יט: אמר’ יונה -
צריך ביאור מה לנו אם הכרמים אינם זה כנגד זה, שלכאורה, הענין הוא כמו שבאר פני משה על המשנה, שחלק בטל לזה…. אם כן, עדיין יבטל. ותחשב.
** שיהא מוקף -
נראה שאם אין מוקף, מצדד גמרא שיהיה כקרחת (כיון שגדר יותר חשוב, ויכול דבר לבטל לו). לא נראה שיש צד שיהיה מותר אף בפחות, שלכאורה, מה שאין זורעים בתוך ד"א של גדר הוא בעיה במציאות, ומה שצריך ד"א לכאורה נכון בכל זמן, ואף בלי גדר, שהבעיה הוא שלא יבטל לכרם. ותחשב.
** ח אמות -
לא הבנתי את זה כל כך. יש קולא במה שזה רק צריך הרחק ח"א, וזה צריך יב"א, אבל אין זה נמנע אם הוא פחות מח"א. אם כן, קשה למה אין שניהם אסורים בפחות מח"א. קצת משמע שהוא מפני שנמצא שמקום האיסור הוא, על הכל, יותר קטן. צריך ביאור מה לנו בזה, שהרי זה רק מפני שמקומו יותר קטן. ותחשב.
** כ: אם יש ג’ טפחים -
קצת יש לדון מהיכי תיתי שאסור לזרוע בתוך גדר, של"ל יפסיק חצי גדר. ותחשב.
** והעומד רבה -
נמצא, לכאורה, שהיה יותר טוב אם לא היה אותו כותל של פרוץ מרובה, שאז לא נראה כסומך עליו. ויש לדון, שאולי אז נראה שלא סומך על כלום, ובוודאי אסור. ויש לדון.
** כנגד עומד
(ציור שני)- צריך ביאור מהו החידוש, שכבר יש כותל. אפשר שהו"א שנ’ כסומך על פסים פסולים אלו.
** שאין הפיאה -
ואם תאמר אם כן למה צריך פאה כלל, שהרי הוא כבר נחשב פתח. וקל לתרץ שיש נפק"מ לפרוץ מרובה על העומד. ותחשב.
** כא. כמין דוקרן -
לכאורה, ר"ל שכיון שהוא קצר בתחתונו, לא עומד החבל. צריך ביאור, אז, איך עומד למעלה. גם צריך ביאור איך עומדים השלש. ותחשב.
גם קצת צריך ביאור ל"ל אומר משנה תיקון אחר, והוא לתת באמצע במה שאינו כמין דוקרן. ויש לומר שרצה לבאר ציור זה בדווקא. ויש לדון למה. אפשר לבאר היתר שיהני לכמעט כל הציורים. גם יש לומר שציור זה רגיל. יש לדון למה יעשו כן בני אדם, שיש לעשות כן רק אם מכניס כל מה שדוקר לקרקע (שמה שהוא קצר עושה שקל להכניסו). אפשר שדרכם להכניס לקרקע, אבל רק כשצריך, ויש לו, כיון שלפעמים צריך, אבל עכשיו לא צריך. דחוק.
** סוף סכך -
אילו סוף סכך מציל, קשה למאי נפק"מ צריך שלש דפנות, שמוכרח שיהיו דפנות סביב כולו. נראה שפשוט לגמרא שלא בכל אופן יורד פי תקרה. וצריך לחשוב מתי עומד.
** אין תימר
- נראה שאולי הוא מפני שכל פתח יש לו דבר על גב פתחו. ותחשב.
** כל אילין
- צריך ביאור למה אין כל זה נוגע למשא ומתן. ותחשב.
** מד’ עד עשר…
- עיין בפני משה על כל הסוגיה, שנראה שלו אין חילוק בברייתא בין יותר מארבע לפחות מארבע. אם כן, צריך ביאור למה חילק אותם. ותחשב.
** כא: לפיכך הזורע -
לכאורה, ר"ל שכיון שחולקים במה נחשב כרם לענין מה אוסר דבר אחר, כך יחלקו לענין נפק"מ אחר, והוא מה ייאסר. קצת מעניין שמניח שכל הכרם נאסר; מי הכריח גמרא לזה, שהיה אפשר לומר שרק החלק מן הכרם שהוא קרוב נקדש. ותחשב.
** שורה של חמש
- מניח שחמש גפנים דווקא. עיין בפני משה לעיל שכתב (כן אני חושב) שסתם שורה הוא של חמש, וגמרא נוקט זה מחמת שכן אורח ארעא. ותחשב.
** כב: כמה דתימר -
יש לדון איך נדע ממילא. ותחשב.
** שאלו
- לא הבנתי החילוק בין ההלכה לראב"י. אולי ר"ל שלהלכה צריך שישתיירו שלש.
** כג. שלש שורות -
לא הבנתי מה אומר.
** כד. לא הבנתי כל סוגיה זה כל כך. עיין במה
שבאר איך חולקים אותו לנו על נו. צריך ביאור, שאז עדיין חסר הקרנים. ותו"ת.
** כד: זה פי’ הק’ -
צ"ב עדיין למה, אילו היינו מצרפים אחד, היה ט שורות, ולא שמנה.
** כה. עיין במה
שבאר פ"מ לר"ש. צריך ביאור למה אינו, אז, ספק. נראה שממה שאין יכולים להכיר שאין אלו עיקר, גופא נקרא כרן. ותחשב.
* Footnotes
[fn:1] ופשוט שלא מסתבר שראה רבא את רב, שהרי רב יהודה היה תלמיד של רב, וחי לאחר רב, שרשב"ם כ’ בבבא בתרא שאחר מיתת רב, הלך ר"י לשמואל, והרי רבא נולד ביום שמת רב יהודה.
[fn:2] כאן, כתבתי בתוך נוט"ס שלי.
