** ב. לקנסיה -
לשון זה מעניין, שלכאורה, קנס הוא דבר שעשו רבנן שלא כדין על מי שעושה דבר שלא כהוגן כדי שלא יעשה כן. כאן, לכאורה, אין זה שייך לכאן, שכאן לא עשה דבר שאינו נכון. לא מסתבר לומר שקנסו אותו כיון שעשה דבר שאולי יהיה נחלף במה שיחייב אותו בבכור, ואז יבוא שלא לתת, שכיון שקנסו, נמצא גלגל החוזר, שאז לא ייעשה רע. ויש לדון. אז, היה נראה לומר יותר שקנס זה הוא דבר המונע אותו מלחטוא. אם כן, נמצא מין קנס חלוק משאר קנסות.
** ג. מילתא דלא שכיחא -
מזה רואים, לכאורה, ש“מילתא דלא שכיחא“ אינו רק סיבה שלא לגזור, אלא אף סיבה שלא לגזור כל כך. זה, לכאורה, אומר שיש לדון למה לא קנסו על מילתא שלא שכיח:
1. לא היה כל כך סיבה.
2. לא עלה על דעת רבנן.[fn:1]
זה מבואר נגד צד ראשון.
ותחשב עוד.
ודע שכאן יש לדחות לומר שאולי היו שני גזירות, וזה היה רק בכלל גזירה אחד, ואז נמצא שדינו הוא יותר קל. ותחשב.
** כל -
היה אפשר לומר שהוא מפני ש“אין ריבוי אחר ריבוי אלא למעט.“ וכמדומני, ראינו כמה וכמה מקומות שיכול גמרא לבאר כן. נראה שהוא דחוק, שלא משמע כן כל כך. גם יש לומר שדחוק כיון שאם כן, לא יכתוב שום אחד משניהם. ותחשב.
** אמר רבי יהושע -
ב"ח גורס רבי יוחנן, ולכאורה הוא נכון, שבדרך כלל רבי יוחנן הוא האומר כן. ויש לציין למה שהערנו שרבי יוחנן אומר כן בדרך כלל, ופעם אחת יש אמורא חלוק שאומר כן- על מחלקת של רבי יוחנן ואחר. ותו"ת.
** ג: מום קבוע -
לכאורה, שני דברים אלו לא תלויים על הדדי, שהראשון מבאר כמה צריך לתת לגוי, ושני מבאר מה נחשב מום. ותחשב.
** ולויים -
יש לדון למה אין הדין עכשיו כמו שהיה במדבר, שהרי של לוי לא יכול לפטור עוד (ר"ל, אי אפשר לתת ללוי עוד). נראה שמשמע שמה שעשו בימי מדבר הוא חלות חלוק ממה שעושים עכשיו, ומה שעושים עכשיו מבאר תורה שהוא רק בכוהן.
** ד. בפטר רחם -
לכאורה, אינו רק בזה, שהוא בבן של לוי. ותחשב. ויש לדון, שאולי אין זה מדין שנולד מלוי, אלא מדין שהוא לוי, ולוי פוטר את עצמו, כמו במדבר[fn:2]. ותחשב.
** הלויים -
לכאורה, גם זה מבאר בת לוי, שגם אשה לויה. ויש לדון אם היא בכלל קרא זה. ויש לבאר עפמש"כ לעיל, והוא שאולי דן במי שהוא לוי, ולא מי שאביו לוי. ותחשב.
** ד: לדורות -
יש לדון ביחס בין שני מיני פדיון שמצאנו- פדיון של מדבר ופדיון של היום. לכאורה, יש דיון כללי שיש לדון, והוא שיש לדון אם הם שווה או לא, דהיינו אם הוא עושה דבר שמסלק את הקדושה באופן שווה. או לא. אם נאמר שאינו באופן שווה, אין אין יחס ביניהם. אם נאמר שהוא שווה, לכאורה, יש יותר סברה לומר שיש יחס ביניהם. יש להעיר שמצאנו שני חילוקים ביניהם:
1. זה בכהן ולוי, וזה רק בכהן. אינו יודע איך לבאר את זה.
2. זה בבהמה שכבר יש לכהן, וזה בבהמה שנותן.
3. על זה, יש לדחות:
  1. אולי מה שצריך לעשות הוא לעשות דבר קודש. כשמקדיש שה, רק עושה את השלה קדוש. צריך לתת את השה מפני שהוא אותו קדושה.
  2. אולי מה שצריך לעשות הוא לעשות שה לכהן. במדבר, עשה כהן, ואז עשה שה לכהן. כאן, נתן שה לכהן, ואז עשה שה לכהן.
** ה: בכל דבר -
צריך ביאור למה נחשוב כן, שלמה נחשוב שצריך שום פדיון.
** ו. מאי לאו אפילו -
לכאורה, מדייק כן ממה שאומר כן בלשון סתם. ותחשב.
** חמור -
יש לדון אם הענין הוא שאז יש יותר סיבה לחיוב בכור, או שהוא אז יותר דומה לפרה. ותחשב. ויש להעיר שזה, לכאורה, אומר שיש יחס בין שני דיני בכור, של בהמה טמא ושל בהמה טהור. ותחשב.
** ו: ואין טמא -
לכאורה, מטמא טמא הנולד מן הטהור כיון שיש כלל שדבר ממעט מה שדומה לו.
** ארץ -
לכאורה, יש להביא יותר ראיה ממה שאומר גבי ברכת יהודה ”לבין שניך מחלב,“ שמשמע ששתה את החלב. ותחשב.
** החלב -
היה אפשר לומר שכיון שהיה מלחמה, היה פקוח נפש, שהיו צריכים מזון.
** דבש -
ואם תאמר נלמד מכאן שדבש מותר. וי"ל שלא מדבר בדבש של דבורים, אלא של תמרים.
** ז. ואיכא דמקשי -
לכאורה, ר"ל שמביאים את זה לראיה שהוא ר"ש. ק"ק למה צריכים ראיה זה, שלכאורה, ראיה הראשון הוא יותר פשוט. ואולי אין הכי נמי, והיה אותו קושיה קשה להם, ואז דנו בו, ואגבו הביאו ראיה ממנו.[fn:3]
גם נראה שיש לדחות הראיה הראשונה, שאולי ”סימן אחד“ הוא גופא שנולד מן הטהור. ותחשב.
** ז: שם לווי -
עיין ברש"י סוכה ו. בענין מה נחשב דבש. וצר"ב.
** שם לווי -
צריך ביאור מה לנו בזה, שלא אומר ”דבש“ בתורה. ונראה שאולי הענין הוא שרק דבר אחד יכול להתרבות להיתר, ואותו דבר הוא דבש. כל מה שהוא בכלל דבר, שאין לו שם לווי, אז יש לו אותו היתר.
** ח. בריה דרב -
בכל זמן שעושה כן, יש לדון ל"ל אומר רק ”בן ר"כ.“ אולי לא היה נקרא על שם אביו, אלא מזכיר גמרא שהיה אביו ר"כ. ותחשב.
** ששה חדשים -
לכאורה, אין זה בסדר.
** ח: הכא -
לכאורה, משמע שהעולם הוא ככדור. ויש לדון, שאולי רק אומר להם שכמו שאי אפשר להם לדעת אם הוא נכון, אי אפשר לו לדעת איפה הוא אמצע שלו.
** י: ואיתימא ר"א -
נראה שהחליף אותם כיון שאומר גמרא ביבמות שהיה ר"א מדבר סתם, והכל יודעים שבא מר"י. אז, היה קל להחליף איזה אמר כן. ותחשב. ויל"ד, שלאידך גיסא, אולי היה ידוע אם אמר דבר שלא מר"י, ואז אולי היה לו להיות ידוע. ואולי הצד שהוא ר"א הוא שהיה ר"א בשם ר"י.
** יב. נתנו לכהן -
ק"ק ל"ל, שאף שאינו שה, לכאורה, הוא שווית של בכור. ואולי צריך להיות חפץ אחר בשווית של בכור, כדי שייפדה עליו קדושת בכור. ותחשב.
יש לדון אם הבעיה הוא שהוא אותו חפץ שבא לו קדושה זה מן הרחם או שהוא בכור חמור. הנפק"מ יהיה אם יכול אדם לפדות פטר חמור על פטר חמור אחר שדמו שווה, ולתת אותו לכהן. ותחשב.
** איסור חל -
זה מעניין. ותחשב. יש שאומרים שהמציאות של האיסור הוא שם, אבל לא האיסור עצמו. איני יודע מה זה אומר, אבל זה, לכאורה, נגד מש"א כאן.
** יג. אמרו -
בפשטות, זה רק אומר שעכשיו מצוות חליצה קודם. לשון ”אמרו“ קצת מוזר, ואולי רק אומר שאז פסקו רבנן כן. א"כ, הוא קצת מיותר. גם יש לומר שר"ל שאמרו שהוא קודם מן התורה, אף שאינו נכון, כדי שיעשו כן בני אדם. כמו"כ מצאנו בכ"מ שאדם יאמר פסק בשם רבנן כדי שישמעו לו. ותחשב.
** קדושת הגוף -
יש לדון למה זה יקדים:
1. מפני שהוא יותר קדוש.
2. מפני שיש בו ביותר ענין של המסכתא (קדושת בכור).
** דזוטר -
לכאורה, ר"ל שהוא רק פרק אחד (כן נראה מרש"י בתחלת המסכתא). ק"ק למה זה עושה שמקדימים את דבריו).
** ישראל מישראל -
יש להעיר שאין קנין גוף שיש לישראל על ישראל אחר כל כך חזק כקנין שיש על גוף של עכו"ם. ותחשב.[fn:4]
** מיד -
סתם גמרא זה כר"ל בקנין משיכה (עיין לקמן שגמרא ידון בר"י). אולי משמע שכן הלכה.
** קל וחומר -
ואם תאמר הרי הקל וחומר נדחה. וצריך ביאור. ועיין בתוס‛ חיצוניות שבשט"מ. ותחשב.
** יד: בעל מום -
לכאורה, עדיין אין סיבה לומר שהקרא שמביא לעיל לא קאי על זה, ששניהם נלמדים מקראי אחרים. ותו"ת.
** טו: דלא אלימי -
לשון זה מעניין, שלכאורה, אין בו שום קדושה, ואינו נאסר מחמת קדושתו, אלא מחמת גזרה. רק לא התירו גזירתם לפדיון. ותחשב.
** יח. ואפילו בידי אדם -
עדיין יכול להיות שר"א חולק על ריה"ג וחולק על רבנן, ואז אולי יש שיטה שמחלק.
** כ. ר"ע מביא
לשון של ר"י בתוך משנה. נראה שכשאמר רבי יהושע לומר לו, שלח ר"ע.
** רובא דתלי -
זה מעניין. יש להעיר שלשון גמרא משמע שהחילוק הוא מפני שיש בו מעשה. מרש"י נראה שהענין הוא שאולי המעשה לא קרה, ואז נמצא שאינו כל כך מוכרח לקרות. ויש להעיר שאז יש שני ספקות (יש כעין ס"ס שלא קרה), שאולי לא קרה מעשה, ואף אם קרה, אולי לא נתעברה. ותחשב.
** כ: שלש -
יש לומר שרצה שלוש כיון שצריך שיהיו לה שלוש בנות.
** כא: שמואל -
קשה, אז, למה מחלק משנה. ותחשב. ואולי אין דינו שווה. ותחשב מה יהיה החילוק.
** כג. טומאה סרוחה -
קשה, שלא אמר גמרא כן, אלא אמר שבטל ברוב.
** כג: קשיא -
אולי מוכרח שר‛ ירמיה ס"ל כבר פדא.
** כה. דבר שא"מ -
קשה למה אינו פס"ר.
** הלכה -
יש לדון ל"ל אמר שהלכה כזה בפירוש.
** כה. ומדרב -
צריך ביאור מהיכי תיתי. ואולי ממה שרב לא פירש שאינו סובר בכולו כר"י, משמע שסובר כמותו בכל דבר. א"כ, צ"ל שסובר ר"י כמותו, בכל פרט.
* Footnotes
[fn:1] לכאורה, קצת מוזר לומר שרבנן לא חשבו על זה, אבל יותר נראה לומר שהענין הוא שרבנן עשו דין על כלל, וכלל כולל, אולי, מה שרגיל להיות, שזה עיקר של מה שנשמע מן הכלל, שבדרך כלל, זהו מה שנוגע משם. ותו"ת.
[fn:2] ויש לדון, שאם כן, אין נפק"מ מדיון על אהרן.
[fn:3] או מפני שכיון שעסקו בו, נמצא שהיה יותר פשוט, או מפני שיותר קל לזכור השמעתתא כיון שכולו כאחד (כולו כלול בתוך דיון אחד).
[fn:4] ואולי, להיפך, הוא, אז, כל שכן שיוכל לקנות כך. ותחשב.
