** ב. מייתי -
יש לדון מה אומר:
1. יכול לקיים מצווה שבלי זה לא היה מקיים.
2. יש ס"ר אם לא מקיים שבת כשהוא של גוי, אלא שאין גוי מצווה ע"ז. ותחשב.
** ב: אלמא -
עיין בביאור ענין מכירה שלמה. לולי רש"י, היה אפשר לומר שדן בביאור דין רבנן, שדן אם סיבתם הוא מפני שאינו כל כך מכירת בהמה או כעין זה, והרי זה מכירה ביותר. עיין בגמרא שם שמבאר סיבת דין רבנן, ועל פי זה נראה לפרש כרש"י. ותו"ת.
** מסייע -
קונסים- לא אומר שמסייע לו למנין, כיון שאולי המנין אינו דווקא (כמו שיאמר גמרא לקמן).
** ט: לימא קסברי -
כחד- זה מעניין. אולי רק ר"ל שכיון ששניהם בכורות, יותר פשוט לגמרא שהם מין ומינו ושאז לא חוצץ. ותחשב.
** יז. אלא -
עיין במה שבאר שהיה לו לומר. לולי רש"י, היה אפשר לומר שהיה לו לומר, ”לעולם,“ שכיון שלא מנה ת"ק דורות, לא היה לו למנות דורות, אלא לומר את הדין.
** יז: בידי אדם -
צריך יבאור למה מניחים שעגלה ערופה כן, שלכאורה, לא מכוון רוצה לזה.
** חוט של סיקרא -
יל"ד מה רוצה שיעשו אילו א"א לצמצם. ואולי היו להם לרחק מן האמצע; אם כן, אין החוט שייך, ולכן מקשה.
** כ. ת"ל -
זה מעניין. וצריך לחשוב ולצרף את זה למש"א רש"י שפרט מפרש כלל.
לולי רש"י, היה נראה לומר שהחילוק הוא אם יהיה לנו הוה אמינא לומר שבכלל ופרט, לא היה צד לחשוב שכן פירוש הכלל אילו לא היה פרט. אולי זהו כוונת רש"י. ותחשב.
