** גמרא תענית גמ’ ר"ה רש"י תוס’ תוס’ רבי מאירי
אומר שחולקים ר"א ור"י אם מזכירים ג"ג ביום ראשון או אחרון של סוכות. שואל גמ’ אם מקורו של ר"א הוא לולב או נה"מ. יחסו לנה"מ הוא מש"א
שמנסכים מפני שזהו זמן דין מים. יחסו ללולב אינו כ"כ פשוט.
מפרש שהוא מפני שא"א להם בלי מים (ו
מוסיף שגדל על המים). גמ’ אומר נפק"מ בהתחלה בערב או יום ראשון.
לא גרס כן, ומוסיף נפק"מ אחר (אם נה"מ הוא ביום ראשון). קשה למה שואל בסגויתינו. גם קשה למה פשוט שאם היה נה"מ ביום ראשון שהיינו לומדים ממנו. ת’
שיותר היה לנו לנקוט נה"מ כיון שיש יותר מקור שמרצה על מים. כן מביא
מרש"י[fn:1].
** רש"י לח"מ רי"ד בעל הצרורות ראב"ד
מפרש שנה"מ היה בלילה כיון שממלאים את הכלי בלילה.
דן בזה[fn:2]. כ"כ
. צ"ב למה הכשר זה עושה זמן הזכרה (כמו שלא היינו לומדים מאיגוד לולב, שיכול להיות בלילה). י"ל שכיון שרואים הלכות בשאיבת מים זה (תקיעות ושמחה) הוא יותר מהכשר מצווה.
מביא
שכ’ שבמילוי מים מקדשים מים. עדיין אין קה"ג אז, אלא קה"פ. ק"פ דומה להז’ גשמים בפה.
** רש"י ראשונים גמ’ יומא בעל הצרורות גבורת ארי
מביא גירסה אומר שאומר שיכולים לנסך בלילה, דכ’, “מנחתם…"- בלילה. דנים
אם זה אמת. אותו קרא נאמר על נסוך יין קרבנות.
אומר שמנסכים מים עם תמיד.
מק’ שקרא זה רק בנסכים הבאים בפנ"ע; אבל נה"מ הובא עם תמיד. עו"מק’ שאין מביאים נסכים קודם הקרבן.
מת’ שאין נה"מ שייך לתמיד; ומדמה לערבה. העיר’ ששניהם נלמדים מהל”מ[fn:3] (אלא שיש ד”א באותו הל’ שאינו שייך לד”א). עפ"ז גם באר שאינו הוק’ אחר סוכות, ואף שנסכים הוק’ אף עשרה ימים אחר הקרבן. בקדשים, הלילה הולך אחר היום. קשה, אז, איך מקריבים בליל סוכות כיון שהוא ליל יד. מת’ גב"א שהוא דין יו"ט כמו ערבה. משמע שאינו אף קדשים. העיר’ שזר שמנסך חייב. קשה, שחייב רק על עבודה. צריך להגדיר.
** ריטב"א גמרא יומא ת"י סוכה ראב"ד רמב"ן. רש"י גמרא רש"י מהרש"ל רי"ע רש"י
יסוד זה כבר נאמר, לכאורה, ב
.
מונה כל הקטרות לפסול אחד של זר. מחלק נסכי מים ויין לשנים. הק’
.[fn:4] ריטב"א ת’ שנה"י הכשר זבח, ונה"מ חובת היום. ב
, מביא קשיא מ
[fn:5], ומביא תשובה זה בשם
מביא הכשר לילה למקור. לא מז’ שאינו קדשים.
בסוכה אומר שתמיד של סוכות טעון שני נסכים.[fn:6]
כ’ שרק שיר קרבן אולי דוחה שבת .
פ’ שהוא שעת נה"י ומים לתמיד.
מוחק את זה, ו
גורסו. לכאורה, לשיטתו, מובן שרש"י יאמר כן.
גם כ’, “חליל… לשמחה של בית השואבה.” ריטב"א אומר שהוא לניסוך המים. ממה שרש"י היה צריך לפרש כן לדוגמה של שיר שאינו לקרבן, משמע שסברש של ניסוף המים הוא לקרבן.
** תענית ר"נ
חולקים ב
במקור לנה"מ. מביא דרשות קראי. שוב מביא שהוא הל"מ.
לומד אותו ממש"כ, “הסך נסך" בפרשת תמיד. משמע כרש"י. אף שאר דרשות משמעים כן, שקאי על נסכי תמיד שמזכיר בפרשת סכות. אם הוא הל"מ, יש לדון. יש להעיר שרש"י אומר מש"א ברבי יוחנן שאמר הל"מ.
** גמרא מעילה ירושלמי סוכה רש"י פירוש קדמון כ’ רמב"ם פה"מ תו"י
כ’ שר"א סובר ש"מנסך מי חג בחג בחוץ חייב" כיון שסובר כר"ע שדורש מ"ונסכיה" לרבות נסוך מים. אין צד מפורש שהוא מדרבנן.
גם דן בזה, ולא מזכיר צד שהוא דרבנן. אז, כאן בא למעט צד שהוא הל"מ, ולא שהוא מדרבנן.[fn:7]
ו
שר"ע סובר שנלמד מן התורה, ואז מחייב כרת.
ב
כ’ כרש"י לומר שכיון שהוא הל"מ, הל’ אינו כר"ע, שלהלכה, הל"מ הוא.
מקשה למה זה רק אם נלמד מן התורה.
** בע"מ ריטב"א יש
כ’ שהעברת ד"א ברה"ר, שהוא הל"מ, הוא חלק מהוצאה (שד"א הוא רשות אדם).
כ’ שאין עונשים על דבר שאינו מפורש. אז, צ"ל שהוא חלק מהוצאה.[fn:8] אז,
שכ’ שלכן ר"א צ"ל כר"ע. העיר’ שלכאורה, אין הל"מ אוסר, אלא עושה שהוא קרבן, ובכלל איסורי תורה. א"כ, הוא כהעברה.[fn:9]
אם נאמר שהל"מ עושה שאינו הקרבה, פשוט למה אין איסור הקרבת חוץ; ואז הגמרא מבואר. ועדיין זה לא נראה לרש"י לשיטתו.
** תוס’
כ’ כרש"י, אבל הוסיף שצריך היקש ממים. אז, מבואר למה צ"ל כר"ע, ולא שהוא הל"מ. יש לדון אם נאמר, בלי זה, שאינו הקרבה, אף אם היה בקרא. גם יש לדון מהו קמ"ל של הקרא.
** ראשונים תוס’ מ"ק רמב"ם ריטב"א שיטה מאירי הל"מ תוס’
יש
שמשמעים שלמסקנא, אין חולקים. אולי אחר חידוש ההל"מ, מוכיחים שהדרשות הם אסמכתות.
ב
כ’ כן.
ג"כ משמע כן, שכ’ "הל"מ, ויש לזה רמזים….” אולי רק אומרים שר"י סבר שהדרשות הם אסמכתות. גמ’ מעילה לא משמע כן.
כ’ שר"ע חולק על עשר נטיעות. משמע שלא חולק בנה"מ.
במ"ק מסיק שחול’.
בתענית כ’ שקרא אומר שהוא מיום שני, אבל הל"מ מוסיף שהוא בכל יום. צריך קרא להוכיח מה אומר הל"מ. כן משמע מרש"י
שכ’ ש
מגלה שהוא שבע ימים. עדיין למה לא יאמר הל"מ שהוא כל שבעה.
יומא מביא גמ’ שדן אם קרא אומר שמק’ נסכי יין עם תמיד של שחר או של ערב. הק’ תוס’ שזה נלמד מזה. כ’ שמה שנלמד מקרא יותר חשוב, ומקדים אין אין יין די. אז, יש לומר שלזה צריך קרא. אם לכו"ע הוא ביום ראשון ג"כ, קשה למה גמרא אומר שללומדים מקרא שהוא בימים אחרים סוברים שמזכירים גשמים אז. עפמש"כ, י"ל שמה שנכ’ הוא יותר חשוב. העיר’ שלשון גמרא הוא "דכי רמיזא בקרא…,” ולא "שבשני מנסכים.”
** ירולשמי פנ"מ
כ’ שמשנה כר"ע שאמר נה"מ דב"ת.
פ’ שקאי עמש"א משנה שיעור ג’ לוגים.[fn:10] העיר’ שגמ’ תענית אומר שנה"מ כל שבעה אינו כר"ע. אז, משנה סותר א"ע. אולי צ"ל בבלי וירושלמי. מאירי מבאר את הירושלמי בטוב, אבל הוא נגד הבבלי. אז, י"ל שגמרא אומר כן לפני שחידש הל"מ (ע"ש). אם כן, אצ"ל שח’ על ירושלמי.
גם כ’ שם ששאל אם יכלוים להקדים נה"מ לפני קרבן או בלילה או לאחר יו"ט. לכאורה, שלשתם מיוסדים באם הוא חובת יום או נסכי זבח. שאל לר"י, שסובר שהוא הל"מ. ר"י דורש כאן מ"ונסכיה" לומר שיקדים ויעשה בלילה ולא יביא אחר חג. קשה איך לומד כן מקרא.
** ירושלמי יש
[fn:11] דורש קרא בשמואל שאומר "מי ישקני מים" לומר שנסך מים בסוכות בבמה.
שמעוררים שאין תמיד בבמה; נמצא שיש נסוך בלי תמיד.
** תוספתא מנחות חסדי דוד ריטב"א
כ’ ש"מי החג חייבים עליהם משום פיגול נותר וטמא.” יש משנים הגירסא, אבל כל הדפוסים של תוס’ שמצאנו גורס כך. חל’ ב
אם יש פגול בנסכי יין.
כ’ שתוס’ זה כר,מ שסובר שיש פגול בנסכי יין. ל
ק’ מה מתיר של מים. אפשר שריטב"א יאמר שחול’ אם הוא חובת זבח (שחול’ אם הוא הל"מ).
** גמ’ יומא משנה גמ’ הוריות מנחות רמב"ם ראבד ריטב"א רמב"ן
כ’ ש"אין מנסכים מים בחג אלא בתש"ש[fn:12].” מביא ראיה מ
כאן, שמז’ כה"ג צדוקי, ורגמוהו באתרוגים.[fn:13] מק’ תוס’ מגמרא בתענית שהז’. כמו"כ יש להק’ למה יהיה עם תמיד אם הוא חובת היום. ת’ שחייב בשל שחר, ואם רוצה, מביא בלילה.[fn:14] אפשר שהוא חיוב היום, אבל אם מביא תמיד חייב בנסכיו.
כ’ ששה"ל קודמים לשני כבשם, שדבר שבא בחובת יום בא קודם דבר הבא מחמת לחם. חול’ ב
אם לחם מעכב כבשים.
פוסק שמעכב, ו
חולק. כשרמב"ם מביא אותו גמרא, לא חולק. ק’. י"ל שכבשים באים בפ"ע לחובת יום, אבל כשמביאים ביחד, הוא רק מפני הלחם. אם כן, אף כאן, יש לומר כן בנסכי מים.
מביא מ
שאף שאין תפילין של יד ושל ראש מעכבים זע"ז, הם מצווה אחת, ולכן א"א לדבר ביניהם. זה אותו מושג שבארנו.
על פי זה, יש לבאר איך יש פגול; כשבא עם התמיד, הוא חובת קרבן, והוא נתפגל. גם יש לבאר תוס’; יש חובת זבח, וחובת היום.
** מש"ח
עדיין צריך מקור לומר שיש שני קיומים כאן. בתפילין יש דרשות שמראים דין זה, אבל כאן עדיין צריך מקור. אולי גופא המקור הוא גופא קושיית תוס’.
כ’ על שאלת ירושלמי (בהקדים נסכים לזבח). משיב שם מדרשת "נסכיה.” מבאר שדרשת "נסכיה" הוא שאף שלכת’ מצווה עם התמיד, שקרא קאי על תמיד, מתיחס אל היום. משנה הדרשה ל"נסכיהם.” אומר שלשון רבים אומר שהם מינים חלוקים, שזה חובת זבח, וזה חובת יום. לכאו’, אומר שממילת "ונסכיה,” יש לו יחס עם תמיד. אם כן, אולי אומר מושג זה שכ’.
** רש"י תוי"ט
מביאים נסכי מים משל שלש לוגים. יל"ד אם הוא מפני ששווה הוא לשל זבח או הוא רק היקש. אם הוא רק לוג אחד, כ’
שהיה חלק מן ההלכה. עיין ב
.
** קה"י רמב"ם ראשונים גמ’ תענית רש"י קינה
ממה שרוצה משנה שיהיו שני הנסכים כלים בבת אחת, משמע שנה"מ חובת הזבח.
במנחות הק’ איך עושים שניהם בב"א, כיון שאין עושים מצוות חבילות. אם שניהם חובת זבח, אין בעיה, שהם מצווה אחת. אבל
פוסק כמשנה זה, אף שסבר שהוא חובת היום. דנו
אם הוא אף בשני בנ"א העושים מצווה; אבל הק’ שרמב"ם אומר שהוא אף שם. מביא
אמר שכשמנסכים מים בחג, אומר תהום ש"קול שני רעים" שומע.
פ’ ששני רעים הם נה"מ ונה"י. משמע שיש רצוי על מים אף מנה"י. כיון שתכלית שני המצוות שווה, אולי אין איסור לעשות מצוות חבילות.
כ’ על מה ש"ארץ טמאה באים להם גשם, אבל בנ"י צריכים נה"י.” משמע שיין ג"כ מרצה. לפמש"כ בתוס’, י"ל שכוע"מ שכאן הוא חובת זבח.
יש שני פשטים מהו "ערה של מים….” י"א שנסך של יין בשל מים או להפך. יש אומרים שנתן מים עם יין בשל יים או להפך.
** ר’ תוי"ט רא"ם הורוויץ
בראיית גמרא יומא, הק’
שאנשי ירושלים היו נוטלים לולב כל היום. ת’
שכיון שלא היה זמן תפלה, לא היו נוטלים אותם שם. צריך ביאור מה אומר.
כ’ שיש מעלה רק אם לא נתנו בקרקע. אז, יש לומר שמסתמא כבר נתנוהו בקרקע.
** תורא"ש
בארנו לעיל שדן גמרא באיזה תמיד נ’ בו נסכים, ונפק"מ שאומר תוס’.
כ’ שיש נפק"מ באיזה זמן הוא נה"מ, שנל’ מאותו קרא. נמצא שחולקים מתי מביאים נה"מ.
** על"נ גמ’ קידושין ירושלמי רש"י
מביא
שפסק ר"ז דבר בדין גרים, ורגמוהו באתרוגים. שם א"א לומר שבא להודיע שהיה שחר.
כ’ שמת אותו כה"ג, ולכן א"א להיות אותו שעבד עבודת יוה"כ, ששניהם מתו מיד. הק’ על"נ איך מת מאתרוגים. גם קשה איך פגמו מזבח.
כ’ שאף זרקו אבנים. מפני זה מדייקים ממה שאמר שזרקו אתרוגים.
** משנה גמ‛ רש"י שט“מ רמב"ם מהר“י קרקס כס“מ ספרי רלב“ג רש"י
אומר ש“שני ספלים של כסף היה שם [על גב מזבח]….“ פשטות הוא שנסכים הולכים לספלים, ומזה לשיתים. לכאו‛, לא הולך למערכה.
זבחים אומר: שמואל אומר שהמנדב יין (בפנ“ע) מביא ומזלף ע“ג אש. ר“ע אומר שנותן אותו לספלים. אם מביא עם קרבן, לא מזלף ע“ג אשים.
שם כ‛ ש“הסך נסך“ משמע שצ“ל בספלים.
כ‛ פשט אחר. מקור שמואל מ“אשה,“ ור“ע דורש משם, כ‛ רש"י ושט“מ, שמכפר כמו אשה.רע“א שאין מנסכים ע“ג אשים כיון שמכבה אש מזבח; שמואל חול‛ כיון שדבר שא“מ מותר.
פוסק שדשא“מ מותר, ופוסק כר“ע.
כ‛ שרמב"ם סובר שהוא פס“ר. ק‛, שגמ‛ לא אומר כן.
כ‛ שמש“א גמ‛ שר“ע סובר כן מפני שסובר שדשא“מ אסור הוא ל“ד, והוא אף מחמת שר“ע קיבל כן. ק‛ שגמ‛ לא אומר כן.
דרש מ“נסך“ כר“ע, ואולי זה כוונת כס“מ. העיר‛ ששם הוא מקור שלא יהיה על האש, אבל לא שיהיה בספלים.
מחדש דרשה אחר (”בקדש“).
כ‛ נג“ז, שכ‛ ש“בקדש“ אומר שהוא על המזבח.
** רמב"ם ראב“ד רדב“ז מהר“י קרקב וכס“מ מהר“י ק‛
פוסק שנסכים נק‛  על יסוד.
חול‛, וכ‛ שנתן בספלים של משנתינו.
כ‛ שכוונת רמב"ם כראב“ד, ואומר שנותן על קרן שיש לו יסוד, והוא הספלים. מוכיח כן ממה שמגביה ידו (ורק צ‛ להגביה לקרן).
כ‛ שמשנתינו רק בסוכות, שמנסכים עם מים. דוחה שגמ‛ אומר לר“ע שנסכים בספלים. ת‛ כס“מ שרק רצה לומר שאינו על אש. רמב"ם בביאור ניסוך בחג כ‛ שהוא בספלים; משמע כת‛ זה.
כ‛ שמספלים יוצא ליסוד, וסומך ע“מ שאומר בנסכי סוכות. מוזר שיסמוך על מה שאומר במקום שאינו עיקר.
** פה“מ
באמת,
כ‛ במנדב יין שמנסך בשני נקבים על יסוד, כמו בכל נסכים. זה נגד רדב“ז ונגד מהרי“ק. צ“ל ככס“מ. צ“ב מהיכי תיתי לחלק. אם לרמב“ם נתינה בספלים פסול, צ“ל שחז“ל קבלו כן מהל“מ. אם לא, אז, יש לומר שידעו חז“ל שהוא יותר טוב כך, אבל יכולים להוסיף סברות מדעתנו, כמו שמחת חג. מוזר שגמרא לא אומר ”מנה“מ.“
** תוס‛ מנחות תורא“ש ריטב“א
מק‛ מ
שהיו שני שלחנות באולם- אחד של כסף ואחד של זהב. נתנו על כסף בביאה וזהב ביציאה; צ“ל של זהב כיון שמעלים בקדש ולא מורידים. מק‛ ששאבו מים בצלוחית זהב; ק‛ איך נתנו בספלי כסף. ק"ק למה מק‛ מת“ק, ולא מר“י. מ
ו
הוא שת‛ של תוס‛, שספלים חלק ממזבח, הוא פשוט לפי ר"י, שמזבח היה אדמה. (אולי סבר שחולק, באמת, אם ספלים צ“ל חלק ממזבח.) רואים מתוס‛ שאינו קשה אם לא מנסכים ע“ג מזבח. אולי כשר כיון ששופך ובא לשם.
** ריטב“א ראב“ד תוס‛ הרא“ש
בת‛ ראשון של תוס‛, צריך ביאור.
כ‛ ש“ולפיכך אין לחוש בה להורדה.“ משמע שמוריד, אבל אין זה בעיה. לכאורה, אומר שאין מים קדוש, ואז אינו מעלה בקודש.
כ‛ שקדשו בפה בהעלאה. לכאו‛, אז, יש קדושת פה על מים. יל"ד אם לזה ת‛ של ריטב“א קיים. מצאנו דברים שאין בהם ק‛ הגוף שיש בהם ”מעלים…,“ אבל אולי רק מדרבנן.
כ‛ ”לא מקרי הורדה,“ שמשמע שכיון שהכלי חול, אינו הורדה, שבא לקדושה.
** ריטב“א מאירי תוס‛ גמ‛
בת‛ שני של תוס‛, צ“ב.
כ‛ שמזבח מקודש ומעולה. אז, נחשב העלאה. נמצא שריטב“א כ‛ כמה שמשמע מרא“ש לעיל (אבל אולי עדיין היה יותר פשוט לו לומר כמש“כ לעיל). כ“כ
.
מביא ראיה מבזיכי לבונה. מעניין, ששאר ראשונים לא הצריכו ראיה. יש
זבחים שמשמע שכל“ש מק‛ יותר ממזבח, ויש נפק“מ מזה. צ“ל שלענין קידוש פסולים הוא כך, אבל כיון שנקרב ע“ג מזבח, יותר קדוש.
** ריטב“א ערל“נ אחרונים רמב“ם
מדייק מרש"י שאינו חלק ממזבח. מבאר שהגביהו ספלים, ונסכו את היין. תוס‛ כ‛ שהוא חלק ממזבח רק כיון שנקבע. אם כן, קשה איך רש"י יבאר. ע‛ ב
שפקפק בזה. יש
שדייקו מ
כרש"י (”ספלים היו שם“).
העיר‛ שמשנה לא מז‛ מקור לספלים. אם נאמר שיש הל"מ שמודיע כן, לשון תוס‛ ק"ק, שמק‛ למה עשו כן, והרי עשו כן כיון שהיה הל"מ כך. אולי היה לו להק‛ ללמוד מזה, אבל לשונו לא אומר כן. משמע שסבר בק‛ שאין מקור לספלים אלו, אלא הנהיגו אותם כן.
אם ספלים היו חלק מן המשכן, צריך להיות שקבלו מה‛ (”הכל בכ'“). א"כ, בזה ידחה לשון קושייתו (אבל יישאר קושיה אחר שבארנו). א"כ, יש הרחק גדול בין קושייתו לתירוצו. לשונו סתום אם אומר כן.
** רלב"ג
לת‛ לק‛ תוס‛ על רש"י, הביא ר‛ תוס‛ בע“ב. מק‛ שם למה רש"י מניח שמים הולך ע"ג מזבח מספלים לשיתים. י"ל שרש"י בחומש פירש ש“בקדש“ שאומר קרא מכוון למזבח. א"כ, כיון שסובר שאין ספלים חלק מן מזבח, צ"ל שהולך ע"ג מזבח. לת‛ תוס‛, אין זה בעיה, שכבר הולך במזבח כשהוא בספלים. לא חידש שהוא חלק מזבח כדי לתרץ לזה; ואולי הוא מפני שבקושייתו סבר כרש"י. סתימתו (שלא מז‛ נקודה זה, שספלים היו חלק ממזבח, אף שלא היה כל כך פשוט לו) לא משמע כן. אולי סובר ש“בקדש“ לא אומר שצ"ל על מזבח;
דורש מאותו קרא שאצ"ל ע"ג מזבח.
העיר‛ שבשולחנות, מניח על גב שני כלים; מביא ממקום לא חשוב שהיה מונח שם למקום חשוב שהיה מונח שם. אולי כיון שבשפיכה לספלים אין המעשה של כלי ראשון שווה לשל כלי שני, אין בעיה. כמו"כ י"ל שאין בעיה של הורדה אלא במקום שעליו מונח; כאן, רק הולך דרך הספל.
מה שיש ענין לשני המצוות להיות כלים בבת אחת משמע יחס ביניהם. על"ע שבארנו שאולי כשעושים אותם ביחד, יש להם יחס. גם י"ל שכיון ששניהם מרצים על מים בסוכות, יש להם יחס.
** רמב"ם כס"מ מהר"י קורקוס
מביא שמנסכים מים בשעת נסוך המים של תמיד של שחר.
מבאר שמה שהוא של שחר הוא גמ‛ בפירוש. עמש"א שהוא עם נסכים, מביא דיוק מתוספתא שאומר שהוא עם אברים, שהיו עם נסכים.
מק‛ ל"ל למד ממשנה שלנו.
** ר"י לוניל מאירי תורי"ד מקדש דוד גמ‛ (
באר
שספל של מים היה ראשון שמגיע, ויין שני. מוסיף שאין עיכוב בסדר עבודה הזה. לכאו‛, בפרט ראשון לא מז‛ איזה נעשה ראשון, אבל לכאורה, כן הוא הדין (אולי מחמת אין מעבירים על המצוות).
ו
חול‛ כיון שתדיר קודם. אז, מהפך את הסדר.
כ‛ ברמב"ם שמקודש קודם (ומים שהוא של יום הוא מקודש). כ‛ שאולי לכן א"א לאחד לקדם, ש
מסופק אם תדיר או מקודש קדים. העיר‛ שקשה איך לעשותו בזמן אחד. גם מז‛ שאולי אין נה"י קודם כיון שהוא תדיר, שאולי נה"מ חל קודם, אם יכול לנסך בלילה. אולי זה יבאר רי"ל; או שכיון שהוא מקודש, קודם מים.
היה אפשר לבאר ברמב"ם ש"עם" לא אומר שהם בזמן אחד.) אז, א"צ שהם בזמן אחד (שאז צריך לעשות בשמאל). אפשר שכללי קדימה אינם במעשה אלא בקיום, שהוא ירידה לשיתין. אולי, אז, עשו שיהיו כלים בבת אחת. אולי זהו מה שמבאר מקדש דוד. כששאר ראשונים דנים ב"תדיר" כאן, דנים במעשה. אפשר שהוא בשניהם. ק"ק, שאם הוא ספק, נצטרך לחוש אף במעשה לרמב"ם.
** מהר"י קרקס רמב"ם אחד
מעורר שפשוט שאם שינה את הסדר, כשר, שבכל פרק כל התדיר לא מעכב. לכן, באר,
לא מפרש כן. לאלו ראשונים, החידוש הוא שאין סדר עבודה מעכב. כ’
פשט אחר ל"ל כ’ רמב"ם כשאר ראשונים. ק"ק למה מז’ ר"י רק בסוף משנה (ולא גבי דין ג’ לוגים). כ’ שיש שני סיבות שלא לומר ביטול ברוב (ואז יוצא): שיעורם שווה, ואין עולים מבטלים זה את זה. ר"י סובר שעולים מבטלים, וגם סובר שיש רוב. אז, חולק על דין זה. מביאו בסוף כיון שנמצא חולק עליו. חשבון זה אפשר רק לרמב"ם.
** גמ‛ ספרי מנ"ח קרית ספר כ רמב"ם לח"מ ר"ג
רמב"ם מפ‛ שהח‛ הוא שאם המים הוא בתוך היין (לא בתוך ספלו, אלא בו), ולהיפך, יצא. ק‛, שיין מזוג פסול לנסכים.
ו
אומ‛ כן, ואין חולק. אין לומר שנתן אותו ליין כשהיה בתוך הספל, שאין המצווה נתקיים בנתינה בספל, שצריך ללכת לשיתין, ואז הוא כבר מזוג, ועוד שאומר כן גם על יין שנתן בתוך מים, ששם נעשה מזוג מתחילת נתינתו.
ו
‛ שרק יצא נה"מ. דוחק גדול הוא.
, כשמונה יינות פסולים למזבח, לא מונה מזוג. ג"כ שאיסור י"נ הוא רק בכשר על מזבח. כ‛ שהוא במזוג.
כ‛ שמוכח שצריך לומר שחולק על גמ‛ וספרי. באר שכשמק‛ גמ‛ שם ”עלויי עלייה,“ מק‛ אף לפסול נסכים. כ"כ
. א"כ, פשוט שאין ק‛ על הרמב"ם ק‛.
** פנים מאירות קרן אורה
מק‛ כל נוש"כ על יין, אבל, לכאו‛, ק‛ אף על מים.
כ‛ שמברכים על יין מזוג כיין- כולו יין, ולא רק רובע שלו.
כ‛ שנזיר חייב על רביעית יין מזוג, אף שיש בו מים. כיון שהוא יין, ק‛ איך יוצא נה"מ.
יש יותר ביין, אולי, מ“יין עם מים.“ יש, גם, דרך לעשות אותו. מפני"ז, מזיגתו לא עושה שאינו יין; אף שלא בא מענבים, דרכו עושה שהוא יין. מים אינו כן, אלא מים הוא חפץ מיוחד. א"כ, אולי יכול להיות מים ויין
** קרית ספר
כ‛ שפסול מזוג לנסכים הוא רק מחמת שחסר שיערו. עפ"ז, מת‛ לרמב"ם כאן. הק‛ ר‛ שאם י"מ הוא יין, קשה למה אין שיעור. גם הק‛ למה ספרי דורש מקרא. אולי קרא מגלה ש“יין“ של נסכים הוא ”יוצא מענבים.“
** גמ’ מנחות ר"ג רש"י תוס
כ’ שרק לבנה קרב כולו למזבח. מק’ מנסכים, ומת’ שלשיתין אזלי.
פ’ ש"לא נק’ ע"ג מזבח ממש.” העיר’ ש
סובר שהולך על מזבח קודם.
’ סובר שהולך על ספלים, שהם חלק ממזבח. צ"ל ש"כולו על מזבח" ר"ל שנשאר עליו. (א"כ, “ממש" שאומר ר"ג קאי על "נקרב.”)
** רש"י רי"ד תוס’ ר"ח רי"ד רשב"ם ר"ג רמ"ה תוס’ ריטב"א רבינו יונה רש"ש גמ’ זבחים שיט"מ רמב"ם רמב"ם
ו
כ’ ש"מנה"מ" קאי על מה שתוקעים ומריעים כשמנסך.
ו
כ’ פשט חאר; שואל מהי"ת שבא ממי שלוח, ות’ שלומד מ"ממעיני הישועה.” נמצא שמי שלוח ל"ד, ורק צ’ מעין.
מביא ירושלמי שדורש שמביא ממי שלוח לעשות פומבי, להוציא מלבן של צדוקים. לכן, לא מפ’ כתוס’.
כ’ ש"מים מכונסים פסולים לניסוך המים.” כ"כ
,
, ו
. רש"י ורי"ד יח’ ע"ז. תוס’, לכאורה, צריך מקור כיון שסובר שמעכב. מתוס’ משמע שפשטו חלוק מפשט רש"י. ק"ק למה א"א לומר שגמ’ דן בשניהם.
כ’ ש"אכולא קאי.” כ"כ
בב"ב. העיר’ שראשונים לומדים שמעכב מן הגמרא. לא לומדים ממשנה מפני שיש לדחות כירושלמי. ריטב"א מוסיף שזה מקור לנה"מ. (העיר’ שכבר יש לנו מקורות.) העיר’ שלכאורה, שמחה לא מעכב. הק’ ר’ איך נלמוד מדברי נביאים. ת’ שצ"ל שהוא הל"מ (כמוש אומר גמ’ גבי ערל שעובד).
מעורר שגמ’ כ’ שאשם נשפך, ממלאים מן הכיור.
כ’ מח’ תנאים אם צ"ל מי מעין. להל’, א"צ. כן מק’
בב"ב. י"ל שמשנה שלנו אינו כאותו תנא. א"כ יש סת"ם כר"י.
לא פוסק כן. א"כ, רמב"ם יסבור שאין מי מעין מעכב, וילמד גמ’ זה כרש"י. ר"י פרלאו מביא
שכ’ ש"אף שבכל המצוות היה מצווה לשמוח, בחג השמחות היה שמחה יתירה בבהמ"ק, דכ’, ‘ושמחתם…’.” מז’ משניות בשמחת בית השואבה. לא מז’ רמב"ם לשון "שמחת בית השואבה." בנה"מ, לא מז’ שמחה. מדייק שסובר שאין שמחה שייך לשאיבה. מבאר שנק’ שמחת בית השואבה כיון שבאותו מקום התחיל השמחה. מדייק כרמב"ם ממה שקורא גמ’ לשמחה זה "שמחה יתירה,” שמשמע שמוסיף על שמחת יו"ט, ואינו חלוק ממנו. אז, ק’ לומר שדוש קרא זה לומר שמחה גבי שאיבה. צ"ל שרמב"ם לומד מצוה לכת’ מדברי קבלה למעיין. קרא אומר שנסך דווד מים לניסוך המים (לירושלמי). שם, כ’ "באר,” וקרי "בור.” אולי קרי וכתיב מרמז לדין זה לכת’. קרא זה נשנה בדה"י, ולא כ’ שם "באר.”
העיר’ שק"ק למה היה של מים הושחר מחמת שנתערבו, שלא היה מצוי, לכאורה.
** אבני נזר יש תוס’ גמ’ עונג יו"ט חתם סופר רי"א
דן
אם מזבח כשר עם נעשה ממלח.
שטוען שמגמ’ זה רואים שהוא פסול. דחה שלא הוכשר כיון שלא בטלו למזבח, שאסור לבנות ביו"ט. מוכיח שהיה יו"ט ממה שלא תקנו אותו. מניח שאסור לבנות ביו"ט.
בשבת כ’ שיכול לבנות אף בית ביו"ט (מתוך שהותרה בנין בגיבון) אלא שהוא עובדין דחול. אין שבות במקדש בדר”כ, ואז היה להם לבנות מזבח.
בשבועות כ’ שאין בנין בית המק’ דוחה יו"ט. פי
ששם כבר היה מזבח, ולא היה צורך. א"כ, כאן, לא היה בעיה.
כ’ שיש איסור מכה בפטיש. אז, תוס’ מתיר רק בבנין אהל, שאין בו גמר של מכה בפטיש. נוגע כל זה לשאלה של
בסוכה שנפל ביו"ט. מתיר אותו, אבל אחרים חולקים.
** רש"י
כ’ שנבראו שיתין מששת ימי בראשית לקבל נסכים.
** רש"י
(נג) כ’ לת’ ק’ תוס’, נגד רש"י כאן, שאולי נתמלאו עפר.
ק"ק למה רש"י צ’ ראיה שיש מח’ אם שיתין ירד לתהום, שפשוט שלא יקחו כהנים אם בא לתהום. אפשר שחלק בין נסכי סוכות (“תהום אל תהום קורא) לשאר השנה, כמו רמב"ם (לעיל).
** רש"י מהר"ם
כ’ שלא צ’ קרא ללמד שמוציאים, שאל"ה, יסתם.	 לכאו’ השריפה מצווה. שוב מוסיף שאף אפשר ללמוד מזה מצווה להוציאה.
כ’ שרש"י רק מבאר שמקשן רק הק’ על שריפה, אבל תרצן ת’ על שניהם. אז, אין גמ’ משנה, אלא מפ’ שא"א להק’ על הוצאה. לא מפורש גדרי דין זה. לכאו’, אין שבעים שנה דווקא, אלא הוא כל זמן שנתמלא. לא מפרש כמה צריך להוציא משם. אם הוא מצווה, ק"ק ל"ל פ’. ק"ק למה צ’ מצווה.
לכאו’, ממה שאין מעילה, רואים שא"צ להגיע לתהום. אף שנבראו לכך, לא מעכב שירד לתהום. אף לצ"ל אויר שראוי להנחה. יש לדחות שחטפו מספלים; דחוק. גם משמע שאם קלטו לפני שבא לשיתין, לא קיי"מ. כן משמע אף ממשנה, שאומר, “ירדו לשיתין אין מועלים בהם.”
העיר’ שק"ק ל"ל אומ’ שאף רבנן סוברים שצ’ לשרוף אם קלט.
** רש"י תוס’
מפרש ששרפתם במקום קדוש מוכיח שהוא קדוש, וזה מוכיח שיש בו קדושה שהיה לו. אז, מועלים. יש לדון אם מק’ ידע שאין מעילה אם נעשית מצוותו. דחוק לומר שלא ידע. אם ידע, י"ל שהק’ שגזה"כ יאמר שמועלים או שלא נעשית מצוותו. מרש"י, משמע כראשון.
מעילה כ’ כצד שני.
** ריטב”א רש"י
ת’ של גמ’ יאמר או שאין קדושה די למעילה, או שכבר נעשית מצוותו.
כ’ כראשון.
לא משמע כן, שכ’, “וניסוכו עיקר מצוותו.” מה שמביא זה משמע כצד שני. לכאורה, מצווה השניה (שאינו העיקר) הוא מצוות שריפה. א"כ, צ"ל שסבר כתוס’ בביאור ק’ גמ’. לא משמע כן כ"כ.
** רש"י ור"ג[fn:15] תו"י
משמע שא"צ לשרוף בק’, אלא אם תשרוף, תשרף בק’. אז, נעשית מצווותו. גמ’ כ’ שאם סך משמן שעל ראש כה"ג, מועל.
מק’ שנעשית מצוותו, ויש מת’ שעדיין עושה מצווה. לכאו’, הוא כבר כה"ג, קודם שנתיבש. אז, לכאו’, זה נגד רש"י. י"ל שאף שלא מעכב, הוא חלק ממשיחה. גם י"ל שכיון שאין המצווה לשרוף מצד החפץ, לא נאמר שנעשית מצווה. הענין הוא שמצוות נסכים הוא להסך, ולא לשרוף.
חול’ ביומא במעילה באברי שעיר משתלח. גמ’ ג"כ אומ’ שבהגיע למדבר, נעשית מצוותה, ואז מתחילים עבודה שלאחריו. ק’, אז, למה לא חול’ לאחר שהגיע למדבר. צ"ל שכיון שיש מצווה להמיתו, לא נגמר מצווה. א"כ, כבר נעשה עיקר מצווה, כמו במשיחת כה"ג.
** תוס’
במעילה כ’ שלא נחשב נעשית מצוותה עד שנשרף. לכאורה, לא צריך לשרוף את כולה. אם כן, קשה איך נאמר שיש מצווה לשרוף אותו, שלא צריך לשרוף אותו חלק.
גם שם מביא גירסא שגמ’ מת’ שדין שריפה הוא מדרבנן.
** גמ’ רש"י קרן אורה גמ’ רשב"ם רמב"ן רבינו יונה ריטב"א תו"כ זרע אברהם ריטב"א גמ’ אחרונים יש ראשונים
במעילה מת’ שאיקלט לראב"צ.
מפ’ שנשרף רק מפני שנתק’ בשיתין.
מק’ שם. קשה מהי"ת שקרקע שיתין קדוש, ושמקדש.
ב"ב כ’ תנא שאומ’ שמק’ בור ונתמלא, אין מועלים במה שבא לו.
מפ’ של"מ קנין חצר להק’.
כ’ שאף אם קונה, אין מועלים.
פ’ ש"מעילה ליכא, כיון שלא בא מק’ פה.” מדמה אותו לשיטה שסובר שאין גדולי הק’ ק’.
פ’ שכ’ מעילה בק’ פה. החול’ סובר שנח’ כק’ פה כיון שק’ בא מק’ פה.
כ’, “יכול אם הק’ בור ואח"כ נתמלא מים מועלים ת"ל מק’ השם.” יש שכ’ שהרבה דרשות בתו"כ הם אסמכתות. אם אין זה אס’, קשה. אולי רק באו להגדיר אותו גזה"כ.
מק’ איך רש"י אומר שרצפה מק’, שאינו ק"פ. יל"ד אם אף רשב"ם מודה לרמב"ן, ורק אומר טעם יסודי, או חולק. אם חולק, כבר מצאנו חולקים על רמב"ן, וקל לומר שכן סובר רש"י. ת’ שמק’ מה שכבר היה ק’, ואז ק’ בא מק"פ. אף שנכון שלא מק’ חולין, הרי כבר הלך ק’, ואז לא תלוי במה שיש בו ק"פ. בביאור רמב"ן, אפשר שהוא ממון הק’, ולא ק’ הק’. אין פועל אוכל בשדה הק’. מק’
שיעבור על מעילה, וא"צ קרא. באריטב"א שאפשר להק’ לממונו. א"כ, הוא רק ממון הק’, ולא ק’. נמצא שיכו"ל רק נק’ להק’, ולא קדוש, ותלוי בדעת מק’. גם רואים שאין מעילה תלוי בממון הק’, אלא בק’. אז, י"ל כן בב"ב. לשון ריטב"א בביאור רמב"ן לא משמע כן, שכ’ שבמאי דק’ ממילא ליכא מעילה. הול"ל שאינו ק’. אז, לא נ’ שמכוון לומ’ כן. אז, א"א לת’ שרצפה מק’, ולא רק נותן קנין.
כ’ שמועלים בבכור. מק’
שאין ק"פ על בכור.
שכ’ שכשמק’ בפה (כמו שחייב לעשות), בא ק"פ. חי’ לומ’ כן; ב
לא משמע כן. אם לא נאמר כן, צריך לומר שקדושה שבא בפה חלוק מק’ דממילא. יכול להיות דברים אחרים שעושים אותו קדושה. אז, י"ל כן גכ"כ.
** ספרי ראב"ד אחרונים
לרבנן, מוכח שירידתו לשיתין שעושה מצוותו אינו ירידה לתהום, שנעשה מצוותה אם נקלט. מגמ’ סוכה, אפשר לומר שראב"צ חולק. אין סיבה לעשות מח’ חדש. כן מוכרח מגמ’ מעילה.
דורש מ"הסך נסך" שבקדש יבלעו.
על ספרי[fn:16] כ’ שר"ל שנבלע בשיתין.
כ’ שר"ל כראב"צ. משמע שלראב"צ צריך לבוא לקרקע, וחולק על רבנן בזה, דלא כגמ’ מעילה.
** משכנת יעקב ראשונים גמ’ מאירי רש"י
לכאו’, גמ’ משמע שצריך לבוא לשיתין לק’.
כ’ שמה שמקילים לאכול חדש תלוי במח’ תנאים באם הק’ נסכים במדבר. שם, מק’ איך הק’ במדבר כיון שלא היו שיתין שם. נמצא שמשנה שלנו הוא סת"מ במעילה שאומר שלא הק’ במדבר. (על פי זה, מקל לחדש בחו"ל.) היה אפשר לדחות שירדה לשיתין רק אומר שיצאה ממזבח. אם מצווה אינו נסוך לשיתין, קשה למה צריך לצאת ממזבח כלל.
כ’ שבשה"מ, נעש"מ רק כשנתיבש.
כ’ שהיו פוקקים את השיתין כדי שיהיה יין נשאר ע"ג מזבח.
כ’ שזה רק מנהג.
בזבחים כ’ שנדרש מלשון נסך שכר. משמע שעדיין מקיי"מ עד שיוצא.
** גמ’ רש"י
בזבחים אומר שיטה שבבית שני גדלו מזבח להוסיף שיתין.
מפ’ שבב"ר היה כמין בור כרוי אצל מזבח לירד נסכים לתוכו. בב"ש, גדלו את המזבח עד שהיה הבור בתוך המזבח. גמ’ מפ’ שמעיקרא סברו שצ"ל אטום, ובב"ש סברו שצ"ל שתיה כאכילה. הק’ ר’ איך ב"ש חל’ על ב"ר. מגמ’ ורש"י יוצא שצ"ל נבלע במזבח. ק’, שלכאו’, נבלע בשיתין. נמצא שחול’ ב"ש וב"ר בספרי. לכאו’, זה רק לראב"צ, שצ"ל נבלע במזבח. לעיל, הערנו שאולי שיתין אינו כ"כ נצ’; א"כ, לא כ"כ ק’ שיח’.
** פסקתא ירושלמי רש"י פסקתא מגיה רמב"ם מאירי רמ"ש רמב"ם
ר"ל דורש שפקקו שיתין כדי שיהיה יין נ’. לכאו’, זה ק’ על חול’ על רש"י; רש"י פ’ שהלכו מספלים לגב לנקבים. לכאו’, תוס’ מפ’ שלא פקקו שיתין, אלא ספלים. כ"כ ב
וב
.
בזבחים כ’ שבנסכי חובה כוע"מ שלא נותן ע"ג מערכה, ושם מבאר שפוקקים יין שע"ג מזבח. שם, משמע שהוא דין דאו’. ע"ש.
כ’ שדין זה אמרי לערב.
כ’ שצ"ל לעכב, ושכ"כ פסקתא רבתי.
לא מז’ דין זה.
כ’ שהוא מנהג; אולי רמב"ם סובר כן, אבל עדיין הול"ל. לשון ר"ל, “היו פוקקים… לקיים מש"א…,” משמע כן.
כ’ שר"נ דורש זה, ודורש מזה ג"כ נה"מ. א"כ, דין זה רק בסוכות, לשמחת בית השואבה.
משמט כמה ממשניות של שמחת בה"ש (שסובר שיכול לשמוח בכל אופן שרוצה). משמע שאינו דרשה ממש.
** ספרי רבינו הלל חסדי דווד
כ’, “ובקדש יבלעו.” על"ע. לכאו’, זה צ"ל כראב"ע, שאין הליכתו עד התהום חלק מן המז’.
כ’ ש"בקדש יבלעו" אומר שפקקו שיתין, כדי שלא ילך יין לתהום. אז, זהו דין פוקקים. לכאו’, מניח כרבנן. מעניין שרש"י כ’ שנברא שיתין לזה, והרי אף לא יורד כלל לשיתין. כן מק’
. אפשר שיבלע למעלה לא ר"ל שלא יורד, אלא שישהה ע"ג מזבח. זה טוב עמש"כ שעושה קצת מצווה כששוהה שם.
** גמ’ על"נ כ"ס גמ’ ראשונים יש ראבי"ה רמ"ש
ק’ למה ר"פ מז’ שמגרונו שבע. אולי הוא מח’ דין של רבא. ק’ למה מז’ רבא זה.
יומא כ’ שרבא סבר שחמרא מפקח; קצת יין עושה אדם חכם. אז, רבא נתן עצה כדי ללמוד יותר.
כ"כ. גם י"ל שנוגע לדין כוס של ברכה שאומ’ אח"כ. חל’ אמוראים אם אכילה הוא הנאת גרונו או מעיו (יש נפ"מ אם מקיא ואוכל).
כ’ שכוע"מ שבמשקה הנאת גרונו עיקר. אז, גמ’ נוגע להל’. העיר’ שגמ’ כאן דן בשביעה ושמחה, ולא מה נח’ שתיה.
בפסחים כ’ שהמק’ צ’ לטעום כמלא לוגמיו לצאת.
מק’ שמלא לוגמיו יותר מרביעית. כוס של ברכה לא צ"ל אלא רביעית.
שמחלקים בין מלא לוג’ וכמלא לוג’.
מביא מאביו שדייק מלשון טעם לומר שצריך להיות מביא בשני לוגמיו עד שטועם מלוגמיו. זה פחות משתיית מל"ג. לומד משיטת רבא כאן, שמפ’ שרבא אומר שצ’ לסבב על כל פיו. א"כ, יש נפק"מ. (
מביא גי’ שכ’, “בזמן שמנסכים מים…..” כ"נ קצת ממה שבבלי וירושלמי אומרים אותו כאן.)
צ"ב למה גמ’ כאן שייכים. עיין בעל"נ.
“תחלה לגרים" מעניין; עיין ברמב"ן בפרשת אמור ופרשת דרכים.
** רש"י גר"א דניאל
פ’ ש"צדקה שבו" ר"ל שטורח, שנותן לבו ודעתו לטובתו של עני.
כ’ בסוף פ’ על רות וכ’ שצדקה לעכו"ם צדקה, אבל לא חסד. חסד גדול מצדקה, שכ’ ב
"חטאך (שוגג) בצדקה פרוק.” “עוותיך (מזיד) [בחסד נתכפרים].” פ’ בחסד שאינו תלוי אלא בעני, ולא בבעה"ב, והוא כמה היה העני צריך אותו ממון. (לא אומר אותו בפ’ על גמ’ זה; ע"ש.)
** רש"י גמ’ ר"י גקטליא
בביאור "שמא כל הבא לקפוץ קופץ,”
כ’ שלא ממציאים לכל אדם לתת צדקה לאנשים מהוגנים, אלא צ’ לטרוח. לגר"א, קל לומ’ שלא לעולם יבוא לו עני שהוא רעב הרבה. כ"כ גר"א בפ’ (אבל לא בפ’ על גמ’).
ב"ק מז’ שהתפלל ירמיה שה’ יביא לבנ"א אנשים שאינם מהוגנים לצדקה. חול’ אם אינם עניים, אם אינם צדיקים, אם הם רשעים. ק’, שה’ מצרף מח’ למעשה.
מביא גמ’ שחול’ אם יש שכ"מ בהאי עלמא. כוע"מ שעיקר שכר לעוה"ב. כ’ שיש מצוות שמביאים טוב, ולא מטעם שכר. מפ’ שלכן מצוות צדקה גורם שתפלתו נשמעת וכדומה. גם מביא מה שהביאו חדשים בלחוד לקטרת, כיון שמעשרת. העיר’ שממה שלא מקבלים כולם עושר, אף שכולם באו לפייס, רואים שא"א שה’ מצרף למעשה לסגולת מצוות. א"כ, לזה רצה שלא יביא ה’ לאנשים מהוגנים (שלא רצה שיהיו נצולים מחרון אף, והרי צדקה מציל מחרון אף מסגולה).
** רמב"ם ריקנטי
גמ’ דורש בענין תורה של חסד. יש שני דרכים כאן.
כ’ שחסד ר"ל דבר בלי גבולים, בדר"כ לטוב (כמו בעריות). לכאו’, לשון ראשון אומר שתורה לשמה הוא בלי גבול שיושב ולומד תדיר, כמו שאמ’ חז"ל על תורה, שצ’ ללמוד לעולם. לשון שני אומר שמטיב.
כ’ על לא עם הארץ חסיד שאדם עושה חסד לה’ ע"י לימוד, ואין דרך אחר לחסד לה’, שהלומד תורה לשמה עוזר לה’. אז, שני הלשונות אומרים שחסד ר"ל גמילות חסדים, ורק חולקים עם מי עושה.
** ראב"ד
הק’ ל"ל ימלאו ביום וינסכו בלילה, שפסול לינה רק ביום שבא. מזה מוכיח
שאין מנסכים בלילה. על"ע שראשונים חול’. צ"ל שיש מעלה לנסך ביום, וזה יותר טוב מנסוך מכל"ש. העיר’ שמזה יוצא חי’, שיש פ’ לינה, אף שלא נכנס לזמן פ’ (שהרי כשר בלילה).
לכאו’, רק כשהיה יו"ט בשבת לא נסכו מכל"ש, אבל בחול, נסכו מכל"ש.
** רש"י במעילה
כ’ שאף שלא מועלים על מים בכד, מועלים על מים בצלוחי ת (כל"ש).
** תוס’ מכתב תורה מקדש דוד רא"ז זרע אברהם ר"ן ראב"ד
במנחות כ’ שרק דבר שיש בו קה"ג יש בו מעילה. כל"ש רק מק’ קה"ג לדבר שכבר ק’. אז, ק’, שאם כבר ק’ אותו, יהיה בו מעילה. אם לא, ק’ איך כל"ש מק’. כ’
[fn:17] שמדעת מקדש חולין. גי"ל שנותן ק’ דמים (ולכן מועלים אחר שניתן בכ"ש).
מק’ על תוס’ מגמ’ כאן שכ’ שיפ’ בלינה. ק’, שלא מק’ לחולין קה"ג. מה שלא מק’ ממשנה במעילה משמע כמה שכתבנו לת’ (אבל לא כמכ"ת, שאז אף קושייתו לא ק’). ת’
שקדשו אותו כשנתנו לכל"ש. משנה ורש"י במעילה לא משמעים כן, שמשמעים שהחי’ הוא באיזה כלי הוא, ולא מתי מק’ אותו.
ת’ שלא יכולים להק’ הפקר בפה, אלא לזכות בו להפקר. לכן, אין מעילה (כרמב"ן). לזה, צ"ל שק’ כל"ש (כיון שצ’ מעשה נתינה) יש בו מעילה לרמב"ן. (על"ע שהיה צד שדבר שאין בו ק’ פה אינו קדוש, אלא נק’ להק’. א"כ, מחו’ לומר שכלי יק’.) הק’ מ
שכ’ כרמב"ן, וכ’ שכשזוכה להק’, מועלים.
כ’ שק’ מים בפה. אז, א"א לומר כת’ זה.
** רש"י
משמע שאי היה שיעור למעלה, כולו, ולא רק בריבוי, חולין.
** שט"מ רא"ש קרן אורה
מביא מ
שאף אם כל"ש מק’ שלמ"ד, אם חשב שלא לק’, לא ק’. אז, ק’ ל"ל כוונו כן כאן. אולי חשו שישכחו.
חלק על רא"ש, ואז לו לא ק’.
** רש"י
ל
, שמקשן סבר שיש פ’ לינה, ורק סבר שאין ק’ כל"ש, ק’ למה יתן לכל"ש. אפ’ שמק’ שמשנה מש’ שא"א להתשמש בכל"ש. גי"ל שמק’ סבר שכבוד הוא או שבזיון הוא להביא מים מכלי לכלי. ק’ מה יעשו במים שלא ק’, שאם נתנו הכשר בכלי אחר, מה הרוויחו (לת’ שני). י"ל שנתנו היתר לכלי אחר.
** תוס’ ריטב"א
מק’ למה אין פסול יוצא כיון שנתק’ במילוי שהוא בחוץ. צ’ שרק מק’ בעזרה. הק’ ל"ל ימלא בכ"ש; רק ישאר בחוץ. ת’ שבזיון הוא לזמן ארוך. מתוס’ משמע שבזיון הוא למים; מעניין, שלא קדוש. ע’ ב
, שאולי משמע[fn:18] שהוא בזיון לכלי. (עיין לעיל, שכ’ שאולי הענין הוא כבוד למים). ג"ת שאין רווח בכ"ש בחוץ. ק’  ממש"כ לעיל, שאף אם לא ק’ יש רווח.
** תוס’ משנה תוס’
כ’ שמכוער להשהתם "כל כך.”
אומר שמקרות גבר, מלאו מים. מק’
שעדיין לילה הוא, ויפסל בלינה. ת’ ששהו בתקיעות וכדו’ ליכנס עד יום. ממעט מזה כשאומ’, “כל כך.”
** תוס’ גמ’ מנחות שט"מ גמ’ זבחים רש"י תוס’ תוס’ ר"ש[fn:19] ראב"ד
אמר שאם לא יק’ קה"ג לא ירוויח. ק’, שמקשן הק’ שנק’ בכל"ש, אף שידע שאין פ’ לינה כיון שלא ק’. צ"ל, אז, שיש מעלה בכל"ש. גם יש להעיר שלעיל כ’ צד שהמעלה הוא של"צ להחליף כלים; מתוס’ פשוט שא"א לומר כן. צ"ל שכשהלי בחוץ, לא כ"כ ק’ לק’. אז, אין מעלה. העיר’ שדיון זה, אם מה שלא מק’ בחוץ הוא מח’ שינוי בכלי או בהק’, אולי תלוי בגמ’ בפ’. גמ’ שם אומ’ שלחמי תודה מק’ בשחיטת תודה. חול’ ר"י ור"ל אם קדש לחם תודה שהיו בחוץ או לא. לר", גמ’ מפ’ שהו"א שלא חל כמו כ"ש. תוס’ שם מפ’ שר"ל שלא מק’ כל"ש בחוץ. לכאו’, אין דמיון אם נאמר שהוא בעיה בכלי, אלא שהוא בעיה בהק’. נ’ שהמס’ הוא כתוס’ כאן.
לא מז’ "מידי דהוה אכל"ש.” (אבל
מוסיף כן.) משמע שהיה פשוט לו כמס’ של תו’ס.
על משנה שכל"ש רק מק’ בקדש (עזרה) מביא ששמואל אומר שרק מק’ בפנים.
מפ’ שר"ל בעזרה, כמו במשנה.
מק’ למה משנה הלשון. לכאו’, עו"ק למה אומרו, שכבר ידוע המשנה. אפשר לומר שני הלכות- אחד מפני שלא יכול להיות נקדש ואחד מדין כל"ש. אפשר שיש נפק"מ. עדיין ק’ תוס’ ק"ק.
כ’ ש"אין כל"ש מק’ בחוץ עד שיקדש… כדאמר שמואל.” ק’ ל"ל מביא משנה, אלא שמואל.
(תו"כ) כ’ שגמ’ זבחים כ’ שמק’ ליפסל. גמ’ לא אומר כן, אבל שט"מ כ’ לג’ כן.
על תו"כ[fn:20] כ’ שכן מוכרח ממה שלא ממלאים מכל"ש בחוץ. מק’ תוס’, רואים נגד ראב"ד. נ’ שתוס’ סובר ששמואל מח’ שלא ק’ לפ’. זה יבאר למה הביא תוס’ שמואל, ול"ל ק’ לו מה מוסיף שמואל. (תוס’ בזבחים יש לו ביאורים אחרים בשמואל, ואולי ראב"ד סבר כאחד מהם.)
** מצפה איתן לח"מ רמב"ם רי"ד משנה רמב"ם ראב"ד ח"ח תוס’ רש"י
תוס’ לעיל הק’ איך מלאו מקה"ג. ק’ לראב"ד.
מביא
שכ’ ש
סובר שק"ג הוא ביום. א"כ, אינו ק’. ק’ שראב"ד (גדולי מפ’ של מאירי) בתענית אומר שמז’ גבורה בלילה כיון שמ’ק בלילה, ומוכיח מממה שמלאים בלילה. צ"ל שהיה בלילה. י"ל שסובר שלעלום לא ממלאים בכ"ש. לשון מאירי, שכ’ שלא מנסכים ומק’ בלילה (אלא ק’ פה) אולי קצת משמע כן, שלא מק’ בכל"ש. א"כ, צ’ לפ’ שכשמשנה אומר, “אלא שהיו…,” החילוק הוא אם מניחה בלשכה, שבחול לא צריך לשהות.[fn:21] אז, י"ל כן למש"א תו’ס לענין מעלים בק’.
כ’ שאין נה"מ בלילה. אז, כ’ שמילאו בלילה והביאו לעזרה מקרות הגבר. א"כ, ק’ ל"ל פסלו בלינה. צ"ל כראב"ד שממלאים בכלי חול.
במעילה כ’ שאין מועלים במים שבכד. נתנם בצלוחית, מועלים. מניח שכבר יודעים שאינו בכל"ש. זה יותר טוב אם הוא כן אף בחול. העיר’ שיכולים להק’ לראב"ד ל"ל יפ’ ביוצא כיון שנתק’ בחוץ. עוצ"ל שלא ממלאים בכ"ש.
כ’ באימורים שיצאו בשעת זריקה ושוב נכנסו שכשרים.
חולק.
כ’ שרמב"ם סובר שאין פסול יוצא במה שלא היה בפנים.
חול’, שמק’ למה אין פ’ יוצא, ות’ שלא מק’ בחוץ.
בזבחים ג"כ משמע כן. אז, יש לדחות שראב"ד כרמב"ם. ראב"ד חול’ שם על רמב"ם, ואז א"א לומר כן. יל"ד, שלא קל להבין הרמב"ם, ואז אולי לא פ’ כן ברמב"ם.
הקריבהו נא לפחתך ר"ל התקריב אותו למלך שלך. פחת הוא לשון מלך (מלשון pasha.)
** ר"י ענגיל
(מסתמא בלקח טוב) דן למה אין פסול דיחוי במגולה שנתן במסננת.
** רש"י תוס’ חסדי דוד מהר"י קורקוס חשק שלמה תוס’
כ’ שהפסול הוא שפחות משיעורו, שחלק ממנו ארס.
כ’ שזה א"א במס’.
כ’ שרש"י סובר שגמ’ מת’ רק לר"נ.
כ’ שני טעמים. לכאו’, אומר כזה.
מעורר שלשון פסולים לא משמע מרש"י, שאין פסול, אלא אין בו כשיעור (אגב, זה יבאר למה אין דיחוי). אז, תוס’ סובר שדחוק לומר כן, והיינו אומרים כן רק מדוחק, ואז חוזר למס’. כ"ז משמע שמקשה לא ידע דין "הקריבהו.” אפשר שסבר שאין "הקריבהו" כשאין ארס שם. אז, כן סבר מקשה. אז, מרש"י משמע שלא היינו אומרים "הקריבהו" אלא מתוך הדחק, היפך של מש"א חש"ש.
ביומא כ’ שאף שיש פ’ בע"מ ביין, אין פ’ כך במים. יל"ד אם סובר שאין מום או אין איסור הקדש. לצד שני, אולי הוא מפני שאין נה"מ הק’ ק’. דחוק, שזר ח"מ. אולי הוא עבודה, אבל אין החפץ קרבן. לא נ’ כן מרש"י, שרש"י סובר שהוא נסכי קרבן, כמו נסכי יין. עכ"פ, אפשר שלא אומרים הקריבהו כיון שאינו קרבן. אבל, לשיטת רש"י, ק’. אפשר שרש"י סובר שהק’ הוא רק אם יש בעיה בבהמה, ולא בדבר אחר שמעורב בו. אפשר שק’ גמ’ לר"נ הוא שמזה מורה שאינו חלק מן המים.
** רש"י ראבי"ה טור רי"ץ גיאת
בזבחים (עד:) כ’ על בהמה שהוח’ ספק טרפות ונמצא שאינו טרפה שאינו הקרבהו. י"ל כעי"ז כאן, שהיה בה בעיה. להל’ לא חוש’ לגילוי. א"כ, בזה"ז יכשר לקידוש. כ"כ
.
[fn:22] חלק בשם
. נ’ שפסל כיון שלא שמרו, שמה שלא שמר הוא החסרון.
** ריטב"א ש"ע ר"י תוס’ ספר מנהגות מאירי ספר חסידים גמ’ שאלתות רשב"א גר"א
כ’ שמכאן שלא מדלקים בו בבית הכנסת. ק’ מה ר"ל, “מכאן,”שיש כמה גמ’ שאומ’ דין הק’. אפשר שר"ל שאם הוא נכון במים לנסכים, צ"ל שאינו רק לקרבנות. ק"ק ל"ל דן בנרות שבת וכדומה.
כ’ מ
שנרות מגלח אין מדליקים בבה"כ כיון שמאוסים. כמ"כ עכבר שנמצא בשמן פסול להדליק בו בבה"כ משום הקריבהו.
בב"ב דן במקבל צדקה מגוי. מק’ק מגמ’ ערכין שדן במקבל שרגא מגוי. ת’ שהוא כעין קרבן, וגוי מביא קרבן. בשו"ת רשבש, שאל בעכבר שנפל לנר של בה"כ, שדנו בו.
מר"א מלוניל כ’ שמצא שאף שקרבנו בטלו, נרות לא בטלו. שם אומר שנהגו שלא להנות מנרות בה"כ, שהוא כהקדש.
כ’ כמו"כ.
כ’ שלא יקח אדם נר לפני הארון לבקש מעותיו או למנות מעותיו. אז, מובן למה ריטב"א אומר כן רק על נרות בית הכנסת.
ב"ב משמע שיש איסור בק’. אז, אינו רק בקדשים.
משמע שקידוש שייך לראוי למזבח, ואז הוא דין קדשים קצת.
פסל בשמים להבדלה מחמת זה. צ"ב למה נחשב מצווה כלל, שאינו ברכת מצווה. אולי הוא מפני שתקנו חז"ל עם הבדלה.
הביא גמ’ שפוסל ביין. לכאו’, הוא להוכיח שאינו רק בקדשים.
** ר"ח ירושלמי רא"ש גר"א גמ’ תוס’ רע"א ריטב"א נתיבות טהרת הקדש
מביא
שפוסל כיון שלא ראוי לישראל לשתות. ק"ק ל"ל לומד בבלי מזה. לכאו’, בבלי כר"נ, ואז מותר. גי"ל ת’ אחרים. יל"ד אם מים מגולים אסורים, שלא התירו בית דין, אבל מותר היום.
כ’ שאולי סתם יינם מותר היום שלא נוהגים גויים כן, כמו יין מגולים. דוחה שניסוך היה דבר שבמנין, אבל גילוי לא נאסר אלא מח’ סכנה. משמע שאינו אסור, אלא אמרו שהיה סכנה. ודע שיש שמשמעים שהוא אסור.
ג"כ משמע שהיה גזירה, אבל אומר לשון ש"לא נאסר לגמרי.” יש לדון אם ר"ל שלא נאסר בכל ציור, או שלא נאסר לגמרי.
בתמורה דורש לפ’ טריפה, ומק’ ל"ל נל’ ממשקה ישראל. כ’ שהו"א שכיון שהיה לו שעת הכשר, לא פסול. א"כ, אף יין כן. אז, יל"ד אם קמ"ל הוא שפ’ משק"י הוא אם יש פסול או רק יש פסול של רובע ונרבע וכדומה שם. חלקו ראשונים בזה.
כ’ ש"מסקינן דאין לחלק.”
מציין לתוס’ אחר שכ’ שאין משק"י אלא אם לא היה לו שעת הכשר. כ"כ
שם. גי"ל על פי
שכ’ שאין שינוי בחפץ באסור דרבנן (אלא הוא איסור גברא). מ"מ אסורים מדרבנן. אולי "משקה ישראל" הוא רק אם יש בעיה בחפץ. דנים למה אין איסור משקה ישראל ביוה"כ. יל"ד בדין משק"י.
דן אם פ’ לישראל סיבה או סימן (שס"ר יאסור למזבח כמו שאסר להדיוט). תולה אותו במח’ ר"ט וריב"נ (מנחות סט). אולי כיון שאסור מח’ סכנה, פשוט שאין ס"ר זה שייך למקדש. אז, לצד שהוא סימן, לא ייאסר. העיר’ שלצד זה, יל"ד אם נאמר אותו בדינים דרבנן, שסיבתם חלוק מדיני תורה.
* Footnotes
[fn:1] רש"י כאן לא אומר כן; משמע שאין רש"י של כאן רש"י.
[fn:2] תלוי במהו קריאת הגבר.
[fn:3] יש לציין לרש"י (סוכה לד.) שאומר: “אלו שלשה נשאלו בבית המדרש מנין להם מן התורה והשיבו שהלכה למשה מסיני הם ושמע השומע וגרסם כסדר ששמעם.” ואולי מביא ראיה ממה שאמרו אותם ביחד בבית מדרש. עדיין יש לדון, שבודאי לא בא ממש בחד זמן, שהרי מה הצד שיבואו כולם בזמן אחת. ותו"ת.
[fn:4] ת’ שאינם חד כיון שאחד הוא בכל יום, ואחד הוא ביום אחד.
[fn:5] מביא אותו מרב אב בית דין, אבל הוא קושיית ראב"ד.
[fn:6] אין להקשות מרש"י בתענית על זה, שרש"י בתענית אינו רש"י, אבל רש"י בסוכות הוא רש"י.
[fn:7] יש אחרונים שכ’ שהוא מדרבנן בדעת רמב"ן (אבל השיגו עליו בזה).
[fn:8] מבארים את זה לפשט ל"אין עונשים מן הדין.”
[fn:9] אמר’ שמעניין למה סובר בע"מ שהוא הוצאה ולא "לא תעשה כל מלאכה.” אולי אין זה איסור תורה, אלא הוא שלא לעשות כל אחד מן האבות, וקיצר לומר "לא תעשה….” הראיה לזה יהיה חילוק מלאכות. כ"כ תוס’ רי"ד.
[fn:10] רש"י בזבחים, וגמרא מעילה, משמעים כן.
[fn:11] סנהדרין (ה-ו)
[fn:12] עיין שם, שבא למעט תשבה"ע.
[fn:13] אומר שהיו אתרוגים להודיע שהיה בשחרית.
[fn:14] אמר’ שבכ"מ צריך לשנות קצת לשונות תוס’ בתענית.
[fn:15] באמת, הוא רבינו אליקים, אבל נקרא לו ר"ג כיון שרב שלום כ’ כן כיון שכן כ’ בדף.
[fn:16] רב שלום אמר שהיה bet  כל פרוטה שיש לו שאינו ראב"ד.
[fn:17] הוא מכתבים מראגיצוב"ר וגדולים אחרים.
[fn:18] יש טעות בגי’, אבל אולי הדרך לתקן אותו טעות משמע הכי.
[fn:19] אינו ר"ש, אבל נקרא ר"ש.
[fn:20] הוא ראב"ד.
[fn:21] אמר’ שהוא דחוק, אבל לאחר שתאמר כן, מגדיל עליך, אבל אינו כל כך קשה.
[fn:22] בן בן בנו של ראבי"ה
[fn:23] אולי הוא מפני שבא קודם, שהרי מתחיל בערב. אז, רואים כבר שאותו לילה הוא זמן מים. ונראה שזה לא יהני לתוס’, שהרי תוס’ אומר ששניהם יתחילו בפעם אחת, שהרי הוא בצד שרק זה נפק"מ. ויל"ד.באמת, יש לדון למה לא יהיה נפק"מ זה לתוס’. אולי הוא מפני שאף לולב היה לו להיות, מצד דיני מים, בלילה, אלא שאינו בכל לילות, אלא ביום. גם יש לומר שסבר שאין חלק מנה"מ בלילה.
[fn:24] נראה לבאר שאינו רק ששניהם בפה, אלא ששניהם רק גורמים, שזה גורם חשוב להקרבה, והזכרה גורם לשאלה.
[fn:25] יש לדחות שמקריב נסכי יו"ט (שהוא חלוק, מפני מש"כ גמרא יבמות בדיון תדיר או מקודש). ויש לדון מהי"ת שצריך נסכי חג.
[fn:26] יש לדון למה אינו חולין בעזרה אז. ואולי נדחה.
[fn:27] עיין בקרבן העדה, שכ' שיש צד שהוא מדרבנן.
[fn:28] אין זה מוכרח, שאולי הוא כמה שכ' גבורת ארי. יש לדון, אז, אם צריכים כל זה. ונראה שמקשה מהיכי תיתי שלא סבר שהל"מ אף על זה. ויש לדון, שלמה יהיה, שלא מסתבר להיות. עדיין ק"ק מהיכי תיתי שזה ההל"מ.
[fn:29] אין זה בעיה, שר"ל "אם היה בקרא בלי הוכחה זה.”
[fn:30] יש לומר שהוא שר"א סובר כר"ע, שמצאנו שסובר שהל"מ אומר שהוא חייב.
[fn:31] קשה לר"ע, שהיה דורש שהוא מיום ששי, למה א"א שהל"מ הוא מיום חמישי.
[fn:32] היה אפשר לומר שכ’ כדי להקש.
[fn:33] יש לדון ל"ל אומרים שאז יביא לאחר הקרבן (אף ימים אחר כן) כיון שהוא אף קודם זבח. אולי צריך להיות עם הזבח להיות חובת קרבן. יש לדון אם יצטרך כן, שהרי אין חובת זבח צריך לבוא עם זבח, ואז אין ביאה עם הזבח חשוב. ויל"ד.
[fn:34] היה אפשר לומר שהוא דומה לשל יין במה שיש שני נקודות בו (שיש שני מיני יין, של זבח ושל יום). ויש לדון, שרק מדמה אותו לתמיד. ויש לדון. עיין בקרבן העדה שקצת משמע כן.
[fn:35] לכאורה, היה אפשר לומר יותר פשוט שלכן צריך קרא וג"ש. יש דייק ממה שלא אומרים כן. ותחשב.
[fn:36] על פי רש"י זה יש לבאר גם מה שהביאו שניהם ביחד. מסתמא, כך היה כוונת רבי.
[fn:37] גמרא שם בפירוש לא אומר כן.
[fn:38] יש לדון למה יזרקו אתרוגים אם יש אבנים. ואולי לא היה כל אחד יכול למצוא. גם יש לומר שהיו בני אדם שלא רצו להמית אותו או לפגום את המזבח.
[fn:39] יש להעיר שלרבי יהודה, מושחרים מחמת יין, אף שלרמב“ם, נותנים עליו יין רק לשמנה ימים בשנה. ותו"ת.
[fn:40] אפשר לומר שלר“י אין טוב בעשיית אותם של זהב, שבין כך ובין כך, כיון שאומר שמחלידים, אינם נאים. ויש לדון אם סובר שאף זהב היה מחליד, או אולי רק סיד. ותו"ת.
[fn:41] היה נראה לומר פירוש אחר. בדרך כלל, ”מעלים בקודש“ מיירי בקדושת חפץ, ואומר שיש להעלותו, ולא למעטו. אם כן, נראה שאף כאן יש לתת את החפץ במצב של קדושה יתירה, והוא שנותן אותו בכלי היותר קדוש. כלי של זהב, כיון ש והא של זהב, יותר קדוש מכלי של כסף. אם כן, כמובן זה רק אם כלי הראשון הוא קדוש.
[fn:42] אם כן, לכאורה, נאמר כן אף ברצפה, שהיה מקודש (אולי) כמזבח. אם כן, קשה איך מגביהים מן הרצפה לתוך כי שרת. יש לדון, שרק הוקדש להקרבה, אבל לא לזריקה. גם יש לומר ששאני הכא שצריך כך כדי לכפר.
[fn:43] לא הבנתי הדיוק, שלכאורה, כן הוא לשון המשנה, ואם לא נאמר שכן סובר משנה, לא נאמר שכן סובר רמב"ם. אולי היה לו לרמב“ם לפרש יותר משהיה לו למשנה לפרש. עיין שם (מרכבת המשנה) שאומר שהמשנה משמע כן. שם גם מדייק ממה שכשדן במקדש לא מזכיר הספלים. גם מזכיר שבבית שני, היה שום מי שרצה לתת על מזבח ספלים. א"כ, יש עוד סיבה שא"א להיות חלק מן המזבח.
[fn:44] נראה ליישב על פי זה הסתירה שברמב“ם, והוא שאולי הוא צריך לתת נסכים לתוך ספלים, ומן הספלים ליסוד. זה יותר קל אם אין הספלים מחוברים למזבח. ותו"ת.
[fn:45] יש להעיר שלרמב"ם לא הניחו אותם לזמן. אולי זה לא יהני אם הוא חלק מן המזבח.
[fn:46] אפשר שהענין הוא רק שאז יש יחס. נראה שגם יש לומר שרוצה לעשות אותם ביחד כדי לעשות שהם מצווה כך.
[fn:47] יש לתרץ פשוט שרמב"ם סובר שהוא מצוות היום, ורק אם מביא אותם ביחד, יש מצווה שיהיו כלים בבת אחת.
[fn:48] אולי יש לת‛ ע"פ רש"י שאומר שנסוך יין הוא חלוק כיון שמרצה על מים. יל"ד שגם כולל מה שבדר"כ עושה.
[fn:49] היה אפשר לומר שר"י נוגע לזה כיון שיכול לערב רק לפי רבנן, שלפי ר"י פשוט לדעת איזה הוא איזה (שאחד יותר גדול מחברו). ויש לדון, שלעולם אפשר לראות. ויל"ד.
[fn:50] ק"ק למה אינו פשוט כיון שהיתר מצטרף לאיסור. וע"ש שהוא מח‛.
[fn:51] לכאורה, היה אפשר לומר שלכן תוקעים ומריעים. אולי א"צ כיון שכבר עשה מן השלוח. ויש לדון, אז, למה עושים במי שלוח אחר שעתיד לתקוע. אולי לא עושה פומבי כ"כ טוב.
[fn:52] צריך ביאור למה יעכב, שלא שינה עליו הקרא לעכב, ועוד שהוא מנביאים. רבי שוב העיר השני.
[fn:53] אולי לכן לא רצה תוס’ ללמוד שניהם מאותו קרא.
[fn:54] גם יש לומר שאף שלא היו צריכים למלאותו ממי מעין, כן עשו. יש לדון למה יעשו כן.
[fn:55] אולי צריך לומר שסובר כריטב"א.
[fn:56] אפשר לומר שהוא לשיטתו.
[fn:57] לכאורה, ראיית אבני נזר יאמר שהיה שבת (קודם גזרה על ארבע מינים).
[fn:58] יש להעיר שלאבני מלואים ק"ק למה מז’ מלח, שלחולקים יש לומר שהוא ללמד שלכן אינו מהני, אבל לאבני מלואים היה מוכרח שלא יהני, שמוכרח שלא לבנות.
[fn:59] אין זה קשה, שיש לומר שבא ממילא עם חיוב לשרוף.
[fn:60] יש להעיר שאף לא בא לשיתין, אלא לנקב שבמזבח.
[fn:61] אין זה כל כך קשה; אם כן משנה אמאן תרמייה. שוב ת’ רבי כן. היה אפשר לומר שאם כן, היה לו לחייב להוציא, כמו בר"א. כמו כן, היה אפשר לומר שק’ גמ’ הוא שלא נעשית מצוותו, שצ’ להוציא. לא נ’ כן לרש"י, שיש אותו הוכחה.
[fn:62] ק"ק ל"ל נל’ ממה שצ’ להוציאו, כמו שאומר תוס’. יש לדון מהו בכלל "מצוותו.”
[fn:63] קצת יש לדון למה א"א שזה מצווה חדשה שיש לו לעשות. אולי אינו נחשב מצווה, שאינו עושה טוב של הקרבת קרבן או כדומה.
[fn:64] איני מבין, שאפשר שהאו כמו מנחה, שנוטלים ממנו קומץ.
[fn:65] אם לא ידע שאיקלט, קשה איך באר שיטת רבנן.
[fn:66] אולי מקדש כיון שרצפה מתקדשת, כמו שאומר גמרא בזבחים. גמ’ מצדד גם אם מה שתחת רצפה קדוש.
[fn:67] אולי מש"כ רש"י שקרקע שית מקדשתם לא ר"ל קרקע ממש, אלא מעשה שלו, ולא כלה עד שהולך לקרקע. אם כן, כיון שמק’ ע"י מעשיו, אולי מועלים בו.
[fn:68] צריך ביאור למה דן גמ’ באיקלט, ולא נטל מעל גב מזבח. משמע שצריך לרדת קצת לשיתין.
[fn:69] ר’ פ’ שלא יהיה חלל תחתיו. היה נ’ לומר שלא יהיה חלל בתוכו. העיר’ שלכאורה בבית ראשון היה נקב שביסוד.
[fn:70] נראה שלכן היה גמ’ במעילה נחית לומר שאיקלט רק לפי רבנן, שכן צריך לעשות.
[fn:71] היה אפשר לומר שנמצא אם מקיא (ובלי זה, אין יכול לברך ברביעית. למעשה גמ’ לא משמע כן, שמז’ כמה ציורים של רביעית). אמרתי את זה לרבי וצחק, ואמר שלא לעשות כן אחר שאנשא.
[fn:72] יש לדון איך כל זה שייך למחשבה טובה שה’ מצטרף למעשה. שוב דן ר’ בזה. נ’ שקל לת’ שלא מכוון למהוגנים לעולם (על כל פנים, לא למהוגנים כל כך). דחוק.
[fn:73] יש להעיר שלמד"א ששכר מצוות יש בעולם הזה, קשה ל"ל מוכיח ממה שיש בני אדם שממיתים, אף שהיה כל אדם רוצה לכבר אמו כדי שלא ימות (והרי זה צדיק גמור). ותחשב.
[fn:74] קשה, אז, למה אין פסול לינה מחמת שמילאוהו מקרות הגבר. שוב הק’ ר’ כן.
[fn:75] יש להעיר שאין זה ממש אוקימתא, שהרי משנה אומר שהוא כן בכל זמן שהוא בכד, ואף שזה לא קורה בכל יום. ותחשב. אז, כמעט מזכיר שהוא רק בשבת, ולא בחול.
[fn:76] לכאורה, הוא מפני שהוא בדיו לתקנו. גם אפשר שכיון שיכול לסלק אותו, לא פסול. זה תלוי במהו הפסול בהוה אמינא.
[fn:77] אגב, יל"ד ל"ל יבטל הארס.
[fn:78] היה אפשר לומר שהפסול הוא שנחש שתה הימנו, שזה מאוס. אפשר שזה יבאר רי"ץ גיאת, שאולי בהמה אחר שתה הימנו.
[fn:79] אז, עדיין קשה למה לומד "מכאן.” גם ק"ק ל"ל ילמד, אז, מב"ב.
[fn:80] אפשר שירושלמי סובר כר"נ וסובר שיש בעיה מחמת דיחוי.
[fn:81] אפשר לומר שמותר לשתות המים, אלא רק לא הארס. זה אף ית’ לק’ למה מותר בזה"ז. שוב אמר’ את הרא"ש, וכעין זה יוצא מרא"ש. באמת, צריך ביאור למה יאסרו אותו. אולי החמירו על דין שמירה לנפשותיכם. גם היה אפשר לומר שהאיסור הוא על מים שיש בו ארס נחש, ואז ממילא לא נוהג עדיין.
[fn:82] ק"ק ל"ל יהיה אסור, אז, מח’ סכנה. צר"ל שהחמירו על דין תורה.
