** העיר תוספתא מדרש
’ שההו"א שלא יכול כה"ג לפרוע ראש סוטה מוזר .כ’
שהיו מגרילים מי היה צ’ לגלות ראשה, ואף אם נפל על כה"ג, היה צריך. (וכן
אומר שהיה ה’ אומר קו"ח ממה שמלך עוסק בסוטה שאף כה"ג יעסוק.) נמצא שהוא קצת בזיון, ואז יש צד שלא יכול כהן גדול לעסוק בה.
** רש"י רש"י ר"ן ר"י לוניל רמב"ם רב נתן בר’ מאיר ספר מאורות רמ"ה העיר’
יש לדון למה כה"ג יפרם למטה; הא אינו מקיים בזה קריעה. לשון
(“הלכך מותר בכה"ג") משמע שאינו חיוב.
(כת"י) במ"ק (כו:) כ’ שאינו מצות קריעה, ורק עגמת נפש (כמו מה שקורעים בגדי קטן). נמצא שיש ענין בקריעה זה.
במ"ק (שאינו ר"ן) כ’ שכיון שאינו חייב באבילות, הוא רק זכר לכבוד אביו. זה דומה למש"כ רש"י.
כ’ כמו"כ.
כ’ (אבל- ז- כו) ש"כה"ג חייב בכל דיני אבילות, אלא שאסור לו לקרוע בגדיו למעלה…..” זה נגד ר"ן ורי"ל. גם כ’, “אבל חייב לקרוע על מתו. הקורע [שלא במקומו] לא יצא, אלא כה"ג שקורע למטה.” משמע שמקיים בזה קריעה. גם משמע כן מרבו של רמב"ן (
).
(חבר רמב"ן) כתב בשמו על גמ’ שאומר שלפעמים הכל צריכים לקרוע שכיון שמצינו שקריעה למטה נקרא קריעה לכה"ג, מהני אף לזה. לכאורה, משמע כרמב"ם. לרש"י, שהוא רק היכר, בודאי אין ראיה. לרי"ל, אין הוכחה, שאינו דין קריעה.
(סנהדרין יט) כ’ שכה"ג חייב בכפיית מטה. משמע שיש לו דיני אבלות (אבל אולי עדיין אין לו דין קריעה).
שכן נ’ מלשון "לא פורם כדרך שבני אדם קורעים,” ולא פטור.
** סה"ח מנ"ח רמב"ם תו"כ בגמרא תו"כ חסדי דוד העיר’
כ’
שאין כה"ג רשאי לקרוע על מת שימות לו. כ’
שמשמע ששלא על מת יכול לקרוע, ומק’ למקור. מביא ש
משמע שהוא אף אם אינו על מת. מביא רמב"ם אחר שמשמע כסה"ח. מביא אח"כ רמב"ם  שאומר שכה"ג מצורע קורע כיון שעשה דוחה לאו. משמע שיש איסור אף אם אינו על מת. באמת, נדרש כן ב
(ולכא’, הובא
כשאומר במ"ק (יד:) ש"והצרוע" מרבה כה"ג. יש מפרשים שמרבה אותו לפריעה.) בפירוש.
כ’ בשיטת ר’ ישמעאל שלא פורע כדרך שבני אדם פורעים על מתם. משמע שהוא רק על מתו.
כ’ שאולי מרבה אף מתו. לשון סה"ח לא משמע שבא לרבות, ואז לכאורה, עדיין קשה. סה"ח כ’ שכמו שקריעה למת צ"ל טפח, צ"ל כן לכה"ג לעבור.
שמה שגמרא משווה דין מת לכה"ג משמע שהוא רק קריעה על מתו. אפשר שכיון שלשון תורה בכה"ג ובמת (שנל’ מאזהרת קרא לאהרן ובניו) שוה (פריעה ופרימה). אם כן, אולי יש ללמוד זה מזה.
** רש"י טורי אבן זכר יצחק העיר’ תו"כ אונקלוס. העיר אב"א רבי ר"ש אורבך
(נדה לז) כ’ שאשה שהיא מצורעת וזבה משלחת קרבנות. הק’
שמצורע לא משלח קרבן.
(מג, מד) כ’ שמצינו כמה הל’ אבלות במצורע (כמו פריעה ופרימה; תשמיש המטה; כיסוי ראש). מצורעת מותרת באלו. משמע שאין לה אבלות של מצורע. אם נאמר שדין שילוח קרבנות הוא דין אבלות (שאין אונן, ואולי אף אבל משלח קרבנות), נוכל לת’ לרש"י.
שגמרא (מ"ק יד:) שואל אם מצורע ינהג צרעתו ברגל. מוזר מה ששאל זה; כל טומאה נוהג ברגל. משמע שהוא מחמת דיני אבלות.
כ’ ש"יטה ראשו [מצורע] כאבל.” כמו"כ אומר
’ שמעניין שואמר כן רק בדין שפם.
כ’ שטעם דין פריעה הוא כעין אבל. שאל
ל
שגמרא אומר שטומאת מצורע חמור כיון שיש בו פרו"פ. משמע שהוא מדין טומאתו. ת’ שאבלות מחמת טומאתו.
עפ"ז, פשוט שצריך קרא לרבות כה"ג מצורע לקריעה.
** רמב"ם רמב"ן
כש
מביא דין קריעת כה"ג, כמעט סותר א"ע. בספר המצות, דן אם פריעת כ"ה בשעת עבודה ושל כה"ג שלא בשעת עבודה, וכ’ שכ"ה מוזהר אף על קריעות שאינם מחמת אבילה, אבל כה"ג מוזהר רק לקרוע בדרך אבילות. גם כ’ לשון שאיסור קריעת כה"ג "על מתו שמת לו.”
גם כן כ’ לשון כזה בתרגומו של רמב"ם. נמצא שאף שסותר את עצמו בכמה פרטים, מבואר הוא לסברו כסה"ח.
** מנ"ח
כ’ לת’ לסה"ח שאסור לכה"ג רק אם יש "קצת מצוה לקרוע.” אז, צריך קרא למצורע, וכיון שנתמעט, הוא רק בסה"ח. לשון רמב"ם (“על מתו" ו”אבלות”) לא משמע כן.
צריכים לדון מה יהיה המקור למה שאומרים ראשונים שאין לכה"ג דין אבילות. אפשר שנלמד ממה שאסור לקרוע. זה יהני (אבל לא יהיה מוכרח) רק אם נאמר כביאור ראשון שבסה"ח (שאז, נאסר מכל קריעות של אבילות, ולא נאסר מכל קריעות של מצוה).
** תורא"ש ראב"ד רא"ש משנה למלך רש"י רש"י על הדף שם
חזרנו לזכר יצחק. הבאנו גמרא מ"ק (יד:) שדן אם מצורע נוהג צרעתו ברג. מה שיש הוה אמינא לגמרא שלא ינהג משמע שיש בו אבלות, שהותר ברגל. גם יש הוכחה ממה שגמרא בא מיד לאחר גמרא שאומר שאין אבלות ברגל. כ"כ ראשונים.
כ’ כן
, “אבלות צרעתו ברגל….” כ"כ
עצמו, “חלות אבלות של צרעת…." כ"כ
.
במ"ק (רש"י אמיתי) כ’ על שאלת אותו גמרא שדן לענין כיבוס בגדים ובשאלת שלום. אלו הם איסורי אבלות.
(שאינו רש"י) אינו כל כך משמע כן. גמרא מביא ראיה מכהן גדול (שכל יום לו כרגל, ונוהג צרעת).[fn:1]
** תוהרא"ש רי"ד ר’ רש"י
על הנחת זכר יצחק שמצורע אינו משלח קרבנות מחמת אבלות, כן כתב
בפירוש. כ"כ
.הק’
ש
(שניהם) אומר שאין מצורע משלח מפני טומאתו (וכן אומר על ט"מ). אם כן, א"א לומר כזכר יצחק (שבא לת’ לרש"י).
** רמב"ם ר"י הנגיד כס"מ טו"א
על מש"א זכ"י שאין אבלות לאשה, העיר’ שדורשים קרא לפו"פ ועוד קרא להתיר תשמיש. אפשר שאין תה"מ אסור מחמת אבלות (וקרא מגלה שהוא דין אבלות).
סותר א"ע ביד החזקה וסה"מ. ביה"ח כ’ שאין מצורעת מכסה ראשה. בסה"מ כ’ שמכסה.
(בן בן בנו) דן בזה. לכאורה, המקור לפטור אותה יהיה שהוא דין אבלות, ושאין לה דין אבלות.
כ’ מקור אחר (שממעטים פו"פ בגמ’ ממקור שיש בו כיסוי). ע’
במגילה שדן בזה.
** מאירי ריטב"א ריד רש"י מאירי רי"ד ריטב"א
חזרנו לגמרא מ"ק. כ’
שכה"ג כרגל כיון ש"אין אבלות חלה עליו כלל.” גמרא מביא ראיה שכה"ג כרגל ממה שעובד באנינות. מק’
ו
שאין כה"ג אונן אוכל קרבן. קשיא זה מניח שאונן אוכל ברגל.
זבחים (ק:) ו
בפסחים חול’ ע"ז. ת’
שלענין הק’ כרגל הוא.
ת’ שכוונת גמרא להביא ראיה מפו"פ. (לא קל להבין שזה מת’; נאמר שאנינות קדשים חלוק כיון שהוא נוהג אף לאחר קבורה.) מזה רואים שאין אבלות לכה"ג- ושרואים זה מאיסור פו"פ. צ"ל כמש"כ ע"פ זכ"י. רמב"ם סבר שיש אבלות לכה"ג. קשה, אז, איך נאמר שכה"ג כרגל.
** גמרא
בזבחים אומר שאנינות הותר מכללו אצל כה"ג. הק’ רבי שאינו מקיל בו כיון שאינו אונן כלל. (כ"נ ממה שלא מביא ראיה מכ"ה בי"ט.) א"כ, אינו כגמ’ מ"ק. אז, י"ל שהוא מח’ הסוגיות. העיר’ שרמב"ם פוסק כגמרא במ"ק. משמע שיש לו ראיה מזה.
* Footnotes
[fn:1] העיר’ שזה משמע שכה"ג שנצטרע עדיין כה"ג. מס’ גמרא (הוריות) הוא שאסור באלמנה; משמע שהוא כה"ג. עדיין ק"ק, שרבא הוא המביא ראיה כאן, ורבא היה מסופק בזה בהוריות. אפשר שאי אפשר לפשוט משם, שהיה אפשר לומר שאומר שאינו כה"ג. (קשה איך מביא ראיה) מרש"י בהוריות נראה שאין צד שהוא כה"ג, וקשה. רד"ל בפרקי דר"א (לא חושב שחולק על רא"ש בביאור אותו גמרא) נוגע בזה. (אפשר לומר שבטל דין כה"ג מחמת אבילות)
[fn:2] אולי זה שייך למצורע חשוב כמת. זה אולי גם יכול לבאר למה הוא חומרא בטומאה (שאולי לכן טמא). לא נראה, שלכאורה, הוא כמת מחמת דינים אלו. גם אולי יש לומר (וצריך ביאור למה) שהאיסור הוא קריעה שעל מת.
[fn:3] לכאורה, יש לבאר, אז, לשון תו"כ על פי זה.
[fn:4] לכאורה, לא מצינו שממעט דין כיסוי שפם.
[fn:5] גם יש לציין לשקלא וטריא של גמרא בכריתות (ח:).
[fn:6] לכאורה, רצה לומר שיש לו דיני רגל (לכאורה, קדושה יתירה) במה שבא מקדושה שבא לעבודה, ולא בקדושה אחרת. כמו כן אמר’ במק"א.
[fn:7] יש לומר שאנינות חלוק.
[fn:8] נראה שיש לת’ כרי"ד.
