משנה אומר למעט בשמחה באב. לכן, אומר ר"פ שלא לעשות דין עמהם. חולקים אם הוא עד טו באב (שאחריו הוא חדש אחריו הוא חדש אחר), או כל האב. גמרא אומר שממעטים מבנין של שמחה כשלא נענו (בתעניות). גמרא מבאר שזהו בית חתונה לבנו. כ’ ירושלמי אומר שרק בנין שמחה מותר, אבל אם ביתו נופל, מתקנו. אז, אומר ר”ן שבנין שמחה הוא מה שאין לו הכרח. זה אינו כפשוטיו, שגמרא מבאר שהוא חתנות. רא”ש חולק על זה, ואמר שירושלמי דן בתיקון בית חתנות. שו”ע כ’ שהוא “בנין עם ציור,” והוא לשון רמב”ם. מוסיף שאם היה כותלו נוטה ליפול, אף שאם הוא של שמחה, יכול לתקנו. ק’, שלרא”ש, מותר אף בשל חתנות, ולר”ן, כבר כל בנין אסור, ואין רואים הדין אם בית חתנות נוטה ליפול. אפשר שסבר שאין לחלק בין בית לבית חתנות. גם אפשר שסובר שהוא רק בבית שהוא קצת של שמחה כזה. תוס’ במגילה כ’ שמיעוט משא ומתן הוא בשמחה, אבל שאר בנינים שרי. משמע נגד ר”ן. תוס’, באמת, רק דן במו”מ בעיקר, אלא שאגב זה אומר דין בנין. תוס’ יבמות אומר שבנין הוא של שמחה, ויש מפרשים שמו”מ נמי איירי בשל שמחה, כמו צרכי שמחה. רואים, אז, מה סובר תוס’ להיות שמחה (חתנות). תוס’ חולק על צד זה (של מו”מ). העיר’ שגמרא מגילה משמע כתוס’, שאומר שנטע רבי בפורים כיון ששל שמחה מותר, כמו שבתענית אסור רק בשל שמחה. לר”ן היה מותר אא”כ היה הכרחי. לא נראה. ריטב”א כ’, באמת, בפירוש, שדינא הוא שיהיה מותר כיון שהוא יום שמחה. זה אינו לר”ן. ואולי לר”ן צ”ל שיש מושג של חילוק בין שמחה לשאר דבר.[fn:1]
דנים מהו “ממעטים.” תוס’ אומר שלא יהיו עושים כלל, שהיה לו לפרש השיעור. ק’, שתוס’ אמר שרק בשל שמחה אסור. פשוט לתרץ שצריכים למעט כל משא של שחמה, וצריך למעטו לגמרי. תוס’ ביבמות כ’ שקאי על כל מו”מ, ורק ריבוי אסור, ויכולים לעשות מעט. דן בשני שאלות ביחד כיון שהם שייכים זה לזה, שמגדירים מה יכול לעשות. ב”י מביא בני בודן שלא עושים שום מו”מ כלל. כ’ שאין להם על מי שישמחו, ששני התוס’ נגד זה[fn:2]. היה אפשר לומר שבזה סוברים כזה, ובזה כזה. יש”ש אומר שבכל זמן שיש מח’ בין תוס’ במס’ יותר קטן ויותר גדול, הל’ כשל גדול, שהוא מר”א מטוך. גם מבאר שהתירו רק כדי פרנסתו. (כ’ שלכן לא מקילים על זה.) כן נוטה משנ”ב. העיר’ שתוס’ לא משמע כן, וכ’ שימעט יותר מבשאר ימים. רא”ש מציין שהוא כדי שיהיו נראים כמתאבלים. זה שיעור חלוק. (עיין במהרי ברונא.)
תוס’ ביבמות כ’ על מיעוט של אב שבתענית מוקי רק בבנין של שמחה. שם ב[] כ’ שהוא בירושלמי (שאין גמרא כזה). על משנה זה (שאינו לעולם ראיה) אומר שהוא בבנין של שמחה.[fn:3] יש ראשונים שאומרים כן מסברתם. אולי, אז, תוס’ מכוון לומר פ”ק דתענית (שהוא מקור של איסור תענית זה). העיר’ שממה שלא פירש כלל כאן משמע שהוא שווה לדין תענית. טור מביא יש אומרים שכיון שאוסר סתם, אוסר כל בנין, כמו מו”מ. קשה איך יישמע כן מ”ממעטים בשמחה.”  ריבב”ן ור”י מלוניל (אף שלא היה שום שייכות בין אנשים אלו) כותבים שמיעוט שמחה קאי על נשואים. מה שלא אומר כפשטות גמרא הוא לכאורה כי”א זה. (ויש שאומרים שכל דין מו”מ וכדו’ באב הוא רק מנהג, ולא דין כדין משנתינו כלל.) יש לדון אם מיעוט זה אוסר או שממעט. רימ”ל מבאר שממעטים בשמחת חופה (ולא שלא נושאים).
שו”ע כ’, “[א] משנכנס אב ממעטים בשמחה, וכל בר ישראל שיש לו דין... [ב] מר”ח עד תענית ממעטים במשא ומתן... “ מעניין שרק בסעיף ב אומר כלל. אולי לכן כ’ מג”א שבראשון הוא כל החדש. מביא מר”י שכן משמע מגמרא. חת”ם כ’ שהוא דומה לאדר[fn:4]. ק”נ כ’ שגמרא משמע נגד מג”א, שדין של “כל בר ישראל” נאמר מפני מיעוט שמחה. כיון שמיעוט הוא עד תענית (שכן אומר שו”ע על מיעוט מו”מ), כן הוא סעיף א. אם נאמר כי”א, אין להניח שמיעוט בשמחה הוא רק עד תענית, שרק דין בנין הוא כן. העיר’ שרי”ל כ’ שממעטים בנשואים כל אב. אז, זה טוב למג”א.
* Footnotes
[fn:1] יש להוסיף שהיה אפשר לומר שמבאר ר"ן את ציור גמרא לומר שנקט ציור שבו אסור אף אם נופל. אם כן, זה נגד מש"א בש"ע.
[fn:2] אפשר שזה לשיטתם, והוא שאי אפשר לומר שהשיעור הוא כדי פרנסה, שהרי האו רק בשל שמחה. אם כן, אי אפשר להיות שיעור, אז, צריך להיות על הכל. נמצא שלתוס’ ביבמות, אין לומר כתוס’ שבמגילה. אז, אין מי כאותו מנהג.
[fn:3] מעניין שיש להביא ראיה משיטת ירושלמי, שחלק במה שהוא שמחה.
[fn:4] עיין ברשי בתענית שכ’ שמרבים כיון שהפ ימי גאולה של פורים ופסח. משמע שממשיך אף אחר אדר.
