* ב.
** א.	יש לדון
בקדושת בכור. אפשר שקדושה יש לבכור ואפשר שקדושה יש לאם. הפשט הפשוט הוא, לכאורה, שקדושה יש לבכור. זה אומר שמה שהאם הוליד אותו ראשון הוא, לאיזה סיבה, גורם לקדושה לו. נראה שגם יש אפשרות אחר, והוא שכל נקבה (ואולי אף זכר) של חמור קדוש בקדושה מיוחדת שעושה שמה שיוצא ממנו ראשון קדוש. ותחשב.
יש להעיר שפטור אף אם רק אם של גוי, ולא בהמה עצמה. אם כן, משמע שחלק מן הקדושה בא מצד שני שכתבנו. אבל, לאידך גיסא, אף אם האם של ישראל לא חייב. ויש לדון, שאולי כיון שאין גוי חייב להקריב, אותו קדושה נמנע. ותחשב. לולי זה, משמע ששניהם סיבות לקדושה. ותחשב.
גם אפשר לדחות בקל שתורה קידש בהמה על ידי לידה מבהמת ישראל. יש לדון איך נראה את זה מן הקרא. אבל, כמו כן קשה איך נראה מה שיש שני סיבות לקדושה מן הקרא.
שוב ראיתי שתוס’ מביא קרא שדורשים ממנו למעט אמו של גוי.
** ב.	בישראל -
יש לדון אם הבעיה של קנין גוי הוא מה שהוא גוי או מה שאינו מחוייב. כמו כן, יש לדון אם קנין של גוי עושה שאין סיבה די או שיש מניעה.
** ג	משום דקא מייתי -
יש לדון אם זה שכר לטוב שעשה או כדי לגרום שיעשה אותו טוב.
** ד	דקא מייתי -
מעניין שיש טובה בהקרבה לקדושה. לכאורה, זה משמע שיש טובה במה שבהמה שומר שבת. ויש לדון, שאולי רק יש טובה במה שיש לו מצווה אחר לעשות, שיש לו להשבית אף בהמה זה. ותחשב.
** ה	לאו שבור הוא -
רצה לומר, אינו כשבור בדין.
** ו	ונותן חצי דמיו -
וא”ת כיון שאין עליו קדושת הגוף של בכור, מהיכי תיתי שיהיה עליו שום קדושה. נראה שיש סיבה לקדושה. קדושה זה חל על מה שיש עליו סיבה, והוא חצי גופו. אותו קדושה נעשה קדושת דמים כיון שאין חצי גופו דבר שיכולים להקריב. מצאנו כעין זה בציור של רבי יוחנן גבי קונה שותף המקדיש (דיחוי).
* ב:
** ז	הנותן לו בקבלה... בהמה -
לא הבנתי זה כל כך. לכאורה, לא נותן כאן, אלא רק נותן בקבלה. אם כן, צריך ביאור למה יהיה איסור על בהמה. אם נאמר שאף כאן יש חשש של מלאכת שבת, אז יהיה פשוט שאסור למכור כאן. אולי גופא דן אם אסור למכור כך. וצריך לחשוב. (וחושב אני שדן גמרא לקמן בזה, ואז לא קשה לומר שדן גמרא כאן בזה.)
** ח	לפטם -
לא הבנתי מה זה עושה. מגמרא משמע שזהו מה שעושה שיש לקנס על בהמה. קשה, שקונסים על בהמה כיון שיש חשש שיעבד בו בשבת. אם כן, מה לנו אם נוטל גויט רווח של ולדות או של פטום. ותחשב.
** ט	מיגו -
כיון שהגענו לזה, מתורץ קושיית תוס’ לעיל, שתוס’ (ד”ה ונותן) הקשה איך אומר גמרא שנותן עשר בדמיו, וגם אומר שנותן דמיו לכהן, שכיון שקנה, יתן לכהן את הוולד עצמו. נראה שעכשיו יש לומר שעל האם קנסו לקנות עד עשר בדמיו, כיון שבו היה העבירה, ועל הוולד קנסו לתת דמיו לכהן, במגו. ויש לדון אם עושים מגו כך, שאין דיניהם שווים.
ודע שאינו קשה ל"ל ת’ כן תוס’, שתוס’ קאי בהוה אמינא של גמרא.
** י	דלא פסקא מיניה -
קצת צריך ביאור מה לנו במה שפסק ממנו, שהרי הבעיה הוא אחד, והוא אם שובת או כדומה או לא. לכאורה, דינים אלו לא שייכים באם עדיין פסק ממנו. יש לדון,שאולי שייכים בזה. קשה, אז, למה יש שום איסור כאן. אולי אין הכי נמי, הוא רק מחמת גזירה. לכאורה, היה לו לבאר את זה יותר טוב, ולא רק לומר שלא פסק, אלא לומר שעדיין יש לו דיני בהמת ישראל.
** יא	דלא פסקא מיניה -
עדיין יש לדון למה אין בעיה במה שמפקיע את העובר. עיין ברשי שמפרש הוא מפני שהעובר נברא של גוי. וא”ת נאמר כן בכל עובר שמוכר. ויש לומר שהיה כן, אלא שזה נראה כמכירת שלם. גם יש לומר שכבר בא לעולם בבהמה של ישראל. ויש לדון, שלא בא לעולם די לקנות (למקצת שיטות בבבא בתרא)
עדיין צריך ביאור מה לנו במה שלא היה של ישראל לעולם. אולי הרע אינו רק שדבר אינו קדוש, אלא הוא הורדה מקדושה. לכאורה, הענין הוא שכמו שמעשה קנין, שעושה קצת יחס, גורם יותר יחס, מה שעושה קצת קדושה, גורם קצת קדושה, ומה שמפחית קדושה, גורם שיפחת מאד. אם כן, אולי לא רוצים שיפחת קדושה, ולא שרוצים שיהיה לזה קדושה. ויש לדון. ותחשב.
** יב	והוא הדין -
אם כן, קשה למה צריך מכירת עובר במשנה, שכבר רואים משאר ציורים שלא קונסים אותו, אף אם עבר על איסרור זה. אם כן, צריך להיות עוד צריכותא שהאו צריכותא האמיתי שלא פירש. ותחשב.
** יג	המקבל -
לא הבנתי למה חייב חציו, שהרי אין קנס כאן, וקרא פוטר אותם. ותחשב. (זה קושיה על גמרא לפני כן).
** יד	לא ישמע -
צריך לומר שאין זה בכלל איסור לגויים, שאי לאו הכי, היה כבר לפני עוור. ויש לדון, שאולי אומר כן כדי לחייב אף אם יותרו מצוות לבני נוח.
* ג.
** טו	שמע מינא -
היה אפשר לדחות אותו, אבל אין צורך, שלא מביאים ראיה מאותו דיקא, לכאורה.
** טז	המוכר עבדו -
יש לדון מהו הראיה:
1. ממה שאינם שווים, צריך לומר שאחד אינו דווקא.
2. צריך לומר ששל עבד אינו דווקא, שלא מסתבר שנקנס אותו כל כך.
3. על כל פנים, יש להעיר שלכאורה מניח גמרא שממה שאחד אינו דווקא, גם חברו לא דווקא. אולי רק ר"ל שאין סיבה להניח שחברו דווקא, ואז יש לדון בו רק מסברה שלנו.
גם יש לומר שאילו היה אחד דווקא, ואחד לאו דווקא, היה לו להיות אותו אחד אגב חברו (אף שלא רצה לשנות מה שהוא דווקא, ירצה לשנות אגב). ותחשב. אז, צריך לומר שאין אחד מהם דווקא, ולא רצה לשנות דבר אגב מה שבין כך ובין כך אינו דווקא.
** יז	מילתא דלא שכיחא -
עיין במה שהערנו בגלגלים אחרים שמעניין, שבדרך כלל, רק מצאנו שלא גוזרים על דבר שלא שכיח, ולא שמקילים עליו. היה אפשר לומר שאינו כל כך לא שכיח, ואז זה רק די לעשות שאין כל כך סיבה לגזור, ואז גוזרים מועט. כמו כן, יש לומר שיש שני סיבות, ואחד הותר על ידי מה שהוא לא שכיח. ויש לדון, שזה מניח שאין כל סיבה יכולה להיות הותר על ידי מה שלא שכיח. ותחשב.
** יח	רבי יהושע -
עיין בב”ח. כן נראה לשני טעמים:
1. לא מצאנו רבי יהושע שיבאר מחלקת של רבנן ורבי יהודה. אי אפשר להיות ר”י התנא, שהרי חי קודם רבי יהודה, ועוד שלא יבאר מחלקת, בדרך כלל, בגמרא. אי אפשר להיות רבי יהושע האמורא, שלא מצאנו שום אמורא עם אותו שם. ויש לדון, שאולי כאן נתחדש.
2. דרכו של דבר הוא שרבי יוחנן אומר ששניהם מקרא אחד דרשו, כמו בתחילת עירובין ובכ”מ.
3. יט	מקצת בכור- יש לדון אם ר"ל בכור שאינו כל כך “בכור,” אלא הוא רק במקצת בכור, והוא שמה שנקנה חציו לגוי עושה שאינו כל כך בכור; או שר”ל שאין חיוב לתת לכוהן מקצת בכור, והרי כאן, רק נותן חציו, שהרי יש לו רק חציו.
4. כ	בכור מקצת- יש לדון אם ר"ל שבכור היה משמע ללמד אותו דין, או שבכור לא היה משמע כלום, ואז הדין שהייתי אומר הוא כך. ותחשב.
5. כא	מקצת... כוליה- ואם תאמר יהיה משמע עד שאיכא רובו, שאיך נדע לדרוש יותר מזה. יש לומר שתירוץ זה לא סובר שיש סברה לחלק בין כובו למקצתו. גם יש לומר שלשון כולו משמע כולו, ולא רובו.
6. כמו כן יש להקשות גם על רבי יהודה; מהיכי תיתי שאין כל מרבה רובו. אפשר שפשוט לגמרא שרוב ומקצת שווים (או שפשוט לרבי יהודה שרוב וכולו שווים). גם אפשר  שכל משמע כל ציור. אם כן, לכאורה, אף משמע ציור שיש רק מיעוט. יש לדון, שאולי אז נאמר שפשוט מן הסברה שאינו כן, שבטל לשל העכו”ם או כדומה.
7. כב	היה אפשר לומר צד שבכור אומר כולו בכור, ובכור שני הוא ריבוי אחר ריבוי. אז, ממעט. כמו כן יש לומר להיפך. אין להקשות שנאמר שמרבה רובו, שזה קשה בין כך ובין כך.[fn:1] נראה שאולי הענין הוא שאין בכור ריבוי, אלא שמשמעות קרא לא ממעט או לא מרבה ציור זה. אם כן, אלוי אין דורשים אותו בריבוי וריבוי או מיעוט ומיעוט.[fn:2] ותחשב.[fn:3]
8. כג	כמה תהא- לכאורה, זה נוגע למש”כ לעיל גבי מיעוט. ויש לדון איך מחשיבים מיעוט. ועיין בגמרא זה.
9. כד	שקל- צריך ביאור מהו סברה זה. רש"י מפרש שהוא: “דאי נמי הוה בכור בעל מום, היה ניתן לכהן.” קשה, שיש לחלק, ששם כל בכור הוא לכהן, אבל כאן, חלק ממנו אינו לכהן. אף אם נאמר שזה רק עושה שאז אין חלק של גוי חשוב לענין כוהן, שלא יכול לעשות שישנה דינו לענין כוהן, קשה ל"ל נאמר כן אף בנבלה, שאף נותנים נבלה לכהן, שהרי נותנים לו נפל. צריך ביאור. אולי הענין הוא שצריך יחס לגוי על כולו. אותו יחס יכול להיות שמשנה אותו במה שמחיה אותו וגם יכול להיות שמשנה אותו במה שגורם שאינו ניתן לכוהן. הראשון חשוב כיון שהאו שינוי גדול, והשני חשוב כיון שהוא שינוי נוגע. אם כן, אולי כאן מקשה גמרא שאין אחד מיחסים אלו, אבל בנבלה (או טריפה) יש לו אותו יחס. דחוק.
10. ונראה שר”ה סובר ששינוי שנעשה על ידי מום חשוב, שהרי אף שעדיין ניתן לכוהן, משנה דין כוהן עליו, שעכשיו כהן שוחטו ואוכלו, ולא מקריבו.
11. ג:
12. כה	אין במינו קדוש- לכאורה, משמע שפסול מום אינו רק שהוא מוזר (ואז הוא מאוס), שאז מה לנו מאיזה מין הוא. אלא נראה שהענין הוא שכיון שהוא מוזר, אינו כל כך מאותו מין. תורה אמר דין זה על, למשל, פר, אבל פר שנראה כך אינו בכלל פר. אם כן, אולי אם הוא ממין שחייב בכורה, אומר שאף אם נחשב שהוא במקצת ממין שה, עדיין יהיה בו אותם דינים. כמו כן, יש לומר שממה שהוא על מין של עז ועל מין של שה, מסתבר שהוא אף על מין חדש זה של שניהם. ותחשב.
13. יש לדון אם המסקנא הוא שמום הוא מחמת שהאו מוזר ואז מאוס, או שאינו נחשב מאותו מין של עז, אלא ממין חדש של שניהם, או (לדחות צד שלישי) שאין יכולים ללמוד לחיוב של אותו המין. ותחשב.
14. גם צריכים לבאר מה שיש ממומים שאינם כן[fn:4], כמו שרוע אולי אלו הם כעין המסקנא. ותחשב. גם אפשר ששם מחדש תורה שקרק’ של היות עין אחד גדול מחברו הוא דבר שאינו בשום מין, ואז אינו ממין שחייב בכורה. אבל, בשאר דברים, אין מה שפיו אינו כמו עינו או כדומה אחד קרק’ חשוב עד שנאמר שאינו בכל מין. כן, לכאורה, מסתבר, שנראה שזה קרק’ יותר חשוב. ותחשב.
15. נראה שיש עוד מהלך, והוא שהוא מוזר, אבל אולי אינו כל כך מוזר אם הוא ממין שדומה לו.[fn:5] מה ששניהם דומים בחיוב בכור הוא דמיון (ואולי סימן לעוד דמיון). ותחשב.
16. כו	עינו- מגמרא מבואר (וכן כתב רש"י בפירוש) שמניח שר”ל  או זה או זה. היה אפשר לומר שצריך שניהם, שזה קטן מאד, וזה גדול מאד. נראה שאולי סובר גמרא שכיון שעינו כבריה שפטור מבכורה, לא יצטרל עוד שעינו אחד גדולה. ותחשב. כמו כן, יש לומר לשא מסתבר שצריך שיהו חלוקים בגודל כל כך.
17. כז	תרוויהו- יש לדון מהו תירוצו. אולי מתרץ שאינו מוזר, שבהמה כחוש או בריא כן. לא נראה כן מלשון גמרא. אלא, נראה שגמרא מתרץ שכיון שזה לא בא מדבר מוזר, אינו פוסל אותו. ויש לדון, שצריך ומר שמה שהוא בריא הוא מוזר, שהרי לא רוב שוורים שיש להם עינים כן. ויש לדון, שאולי אין לכל בריא עינים גדולים כזה. ותחשב.
18. יש להעיר שפשט זה מטעים טוב עם מש”כ שאין מום שהוא מוזר ואז מאוס, שהרי אף זה מוזר, אלא שהוא ממין אחר, אבל זה אינו ממין אחר, אלא הוא ממין שה כחושה, שהוא מין שה, כיון שהוא מצוי, והוא נראה, לפעמים, כך. ותחשב.
19. ד.
20. כח	בהמתם- יש לדון מה הופקעו בזה:
21. אולי הפקיעו בכורות של בני ישראל. כן היה נראה, שכאן מה שמפקיעים הם בכורות של כוהנים. דע שאם כן, לכאורה, צריך לומר שנתוסף קדושה כקדושת בכור על בהמות של לוייים. לכאורה, זה יעשה נפק”מ כמו קדושת בכור. מחודש שהיה כן במדבר. גם קשה למה היה צריך לעשות כן, שלמה יהפך ה’ כל בהמתם של לויים לבכורות.
22. אולי הפקיעו בהמת בכורים. יש לדון מה הפקיעו. ויש לומר שמה שהיו של קדושים עשו שהם קדושים. אם כן, שני הפקעות אלו נעשים ביחד, שכיון שהקדיש כוהנים, ממילא הוקדשו בהמתם. היה צריך שני ההפקעות כיון שהיה קדושה יוצא משני דברים. ותחשב. הקושיה על זה הוא איך לומדים מזה שמפקיעים קדושת בכורה, שאין זה אותו קדושה שהפקיעו במדבר. ותו"ת.
23. לשון הקרא משמע כצד שני, שאומר שיקחו בהמת לויים תחת בהמתם, שלכוארה קאי על בכור.
24. שוב ראיתי שגמרא לקמן (“שה אחד של לוי פטר כמה חמורים” משמע כצד ראשון. נראה שגמרא מניח שלא היו עליהם קדושת בכור, אלא היה כעין מה שיש בשה. קשה למה לא הצריכו לתת שה, שבדרך כלל, כן צריך לעשות. ותחשב. עדיין, זה אפשר רק בפטר חמור (אבל למעשה דין זה נכון רק בפטר חמור).
25. כט	אם פטרו- יש להעיר שפטרו במה שהיו נתקדשים, ולא במה שהיו קדושים. ויש לדון, שאולי בלידתו נתקדש הכהן, ואז בזה פוטר. ותחשב.
26. ל	בהמה טמאה מנא לן- עיין ברשי ד”ה אלא. יש להעיר שאז היה לגמרא להקשות בהמה טהורה מנא לן שלא פטור, שזהו הדין היוצא מקרא זה. צריך לומר שכיון שהלימוד הדייקרט מקרא זה הוא פטור בהמה טהורה, כך שואל גמרא. אם כן, לכאורה, צריך לומר ששואל ידע תשובה. ונראה שאולי אין גמרא שואל, אלא מפרש שכל זה בתוך המשנה. אם כן, משנה כאילו שואל ומשיב כך. אם כן, פשוט שידע השואל את התשובה.
27. גם יש לומר שהכיר שאין דורשים קל וחומר בכל, אלא באדם. לא ידע למה, אבל כיון שהוא כן, הקשה על בכור בהמה טמאה. ותו"ת.
28. לא	בכור פחות מבן חדש- לכאורה, גמרא מקשה שבמדבר יהיו בכורים של לויים שהיו פחות מחדש חייבים בבכורה. קשה ל"ל אומר שכשמגיעים לגיל החיוב, שהוא שלשים יום, יפטרו את עצמם. ותחשב.
29. לב	שה- קשה למה אין זה קשה לשניהם, שנאמר שמה שנלמד מאדם הוא שכשיש לו מין הפוטר, פופטר, ולא צריך לתת עוד. ותחשב.
30. לג	בפטר- לכאורה ר"ל שתלה המצווה בפטר רחם, ואז אם לווים פטורים, צריך לומר שאף אלו פטורים.  קשה, שאם כן יפטרו במדבר. ויש לומר שרק תלה אותם לענין מה שהוא יותר קל, והוא לפטור את עצמם. וקצת קשה, שלכאורה אם נוכל לומר קל וחומר, צריך לומר שכוח זה כלול בתוך כוח זה (או בתוך סיבתו או כדומה). אם כן, קשה איך נאמר שאותו קדושה של שניהם היה שווה, שהרי לא היה אותו קדושה לבני לויות. ויש לומר שיש לו מעין של אותו קדושה, כיון שסיבתו קצת הוא רק מקצת הסיבה, והוא שלוי יש לו שני סיבות של קדושה, והוא שאמו היה כך ואביו היה כך, וזה יש לו רק אחד, אבל אותו אחד הוא שפוטר. קשה, שאי אפשר לומר כן, שהרי לווים שאינם בני לויות פטורים. אולי צריך לומר שקרא חדש שאותו קדושה אף בא מן הרחם, אף שיכול להיות בא אף מן האב. ודחוק. ותחשב.
31. אפשר שאין הכי נמי, זה היה קשה, אלא שהוקשו כל הלווים זל”ז. אם כן, סומך על המסקנא. ויש לדון למה הקשה מאהרן, ולא מכאן.
32. צריך ביאור למה לא אומר שאהרן יכול לפטור כיון שהיה בן לויה. אולי לא היתה יוכבד לויה, שלא נתקדש כבר לוי. כיון שהגענו לזה, נראה שאולי יש לבן לויה קדושה די להפקיע קדושה של אחרים, אלא שלא היה בן לויה אז, שלא היה לויה שהיתה מולדת כבר. ותחשב. אין זה משנה כלום, לכאורה, אבל אולי הוא נכון. ותחשב על זה.
33. לד	בפטר- לכאורה, זה תירץ לקושיה שניה ושלישית, אבל לא לראשון.
34. לה	קשה לי (וחושב אני שמצאתי את זה במקום אחר) למה צריך קל וחומר, ולמה לא רק אומרים מה מצינו, שאין לוי שבמקדש צריך פדיה, שפדה אותו קדושת לויה. ותחשב אולי יותר טוב לעשות קל וחומר מלעשות מה מצינו.
35. ד:
36. לו	בהוויתם- יש להעיר שזה, לכאורה, רק יאמר שאותם לויים ישארו בקדושתם, שישארו בהוויתם. קשה איך יודעים שלויים אחרים שנולדים יש להם אותו קדושה. ותחשב. אולי א”צ קרא על אותו דור, שלמה לא ישאר בהם אותו קדושה, ואז צריך לומר שקאי על דור שלאחר כן. ותחשב.
37. לז	מעניין שהיו פוטרים בכור בהמה על ידי היות שה ללויים, אבל לא פטרו בכור אדם על ידי היות לו חמש סלעים. ותחשב.
38. לח	בהמתם- לא הבנתי למה גמרא מניח ש”בהמתם” הוא רבים, שהוא אותו לשון של לויים, אלא שבאותו מילה נאמר גם כן של מי. וצריך ביאור.
39. לט	מה אדם- קשה, שאינו באותו דבר לדורות כאן, שלדורות צריך נתינת השה, דלא ככאן. ואם תדחה שלעולם צריך חידוש של שה ללוי. לדורות, מה שקורה הוא שלוי קונה שה, וכאן מה שקורה הוא שנעשה לוי. ותחשב. לא נראה, שלא די לפטור במה שקונה שה, שאי לאו הכי, יפטור בכל זמן שקונה לוי זה. אז, צריך לומר שצריך לתת לו שה.
40. גם קשה, שלדורות צריך נתינה לכוהנים, ולא ללויים. ותחשב. צריך לומר שרק לומדים הדמיון לענין החפץ שבו פודים. צריך ביאור למה.
41. לכאורה, צריך ומר שרק לומדים אותו למה שיכולים, והוא שיודעים דין דורות, וגם יודעים שהיה בהמת לויים שפטרו במדבר, ואז רק לומדים דין שה, וזהו.
42. מ	פקעה- קשה, אז, למה היה צריך לפדות בכורות בלווים, שפקעה קדושתם. אולי יהיו קדושות בביאה לארץ ישראל, ועכשיו לא יהיו קדוש, ומחמת זה צריך פדיון.
43. מא	דקדוש- נמצא שחולקים אם, אילו במדבר לא קדשי, היה קדושה גם נפקע. קצת צריך ביאור מה חושב המקשה, שפשוט שאין ללמוד זה מזה, שיותר קל לעשות שדבר לא יחול מלעשות שיפקע (ולכן אומר גמרא ,מה מכורה כבר...”). נראה שאולי חולקים אם קדושה כזה הוא דבר שצריך סיבה תמידית או לא. זה אומר שיש לדון מהו בכורה, אם הוא שנולד קודם או שהוא יותר מבוגר (ויש לדון איך נחשב את זה, לענין מי שנולד בכט אדר א...). על כל פנים, נראה שאם הוא ראשון, יש סיבה רק כשנולד (אין זה מוכרח, שיש לומר שמה שהיה נולד קודם מקדשו). אם נאמר כצד שני, לכאורה, יש סיבה תמידית.
44. מב	מכאן ואילך- ואם תאמר עדיין יק’ מבכורות מצרים. פשוט לומר שכבר הקריבו את כולם (שלמה לא יביאו את כולם ביום ראשון). רש"י קצת משמע כן.
45. מג	ומינה- קצת קשה, ששאר דברים שבמשנה הק’ אח”כ. יש לומר שמניח שצ”ל שלשון זה בכולם הוא אגב בכורות. ותו"ת.
46. מד	חובות בבמה- יש לדון אם זה דין בהקרבה, שכל המעשים חלוקים כשנעשים לבמה, או במזבח, שחלק ממה שקורה, חוץ מתוצאת המעשה, הוא מה שהיות דם על המזבח מקדש (או כמו זה), אבל כאן אין אותו חפץ לקדש. ותחשב.
47. מה	במצרים- לכאורה, היה גם אפשר להקשות מבכניסתם לארץ, ששם בוודאי קדשו. אפשר שכיון שהוא כל כך פשוט, לא קשה שתנא יאמר עליו לשון זה, שפשוט לומר שקדשו. דחוק. יותר היה נראה לומר שרק הקשה מן הראשון שהיה קשה לו.
48. ה.
49. מו	תיובתא- וא”ת הרי אותו תיובתא רק היה בהוה אמינא, ויש לומר שלא היה לו כלל, כמו שצריך לומר שהיה לנו אף שלא קרה. ויש לומר שאין הכי נמי, ורצה לומר שלא רק לא יותר טוב ממה שאנו גורסים, אלא הוא יותר גרוע. ותחשב. גי”ל שתיובתא ר"ל הקושיה איך יפרש הקראי.
50. מז	קמ”ל חייב- מצאנו לשונות כעין זה בכמה מקומות. יש לדון אם רצה לומר שמודיע לנו שצריך לומר בלשון רבו, או שאמר כן כיון שצריך לומר בלשון רבו. ואם תאמר ל"ל יהני שני. ויש לומר שאין הכי נמי, אבל אולי מוסיף יותר. גם יש לומר שלא היה ראשון בפני עצמו סיבה ללמד אותו כן, שזה מבלבל לבני אדם, אלא רק ללמוד כן לעצמך, שכבר ידוע לך, ולא תבלבל. ויש לדון. במקום אחר, היה לנו ראיות מה אומר גמרא, אבל אינני זוכר. עיין ברשב”ם בב”ב (קרוב לדף קל:).
51. מח	בלשון רבו- ואם תאמר באיזה לשון אמרו. ויש לומר שחולקים בזה. אם כן, לכאורה, מסתבר שלשון שני קשה, שמי יברא כן מלבו. ויש לדון. גם יש לומר שחולקים אם יש ללמד בלשון רבו. גם יש לומר שזה לימד בלשון רבו להראות שיש לומר בלשון רבו, וזה רק אמר בלשון רבו, ולא גילה שיש לומר בלשון רבו (שלא היה רוצה להראותד ין זה). אם כן, אולי אינו מחלקת כלל.[fn:6] גם יש לומר שאמר אותו שני פעמים, ופעם אחת אמר לשון זה, ופעם אחר אמר לשון אחרת.
52. אם כן, לכאורה, כיון ששמעו לשון ראשון, יאמרו כן, שהוא לשון יותר טוב, ואף הוא בא מרבם. ויש לדון אם מאמינים שאמר כן רבם. גם יש לדון אם יש לומר הלשון שאמר רבו, או הלשון ששמע. ותו"ת.
53. ה:
54. מט	רפידים שמה- ואם תאמר ל"ל נאמר כן. ויש לומר שמוזר הוא שהיה לו שם שראוי לידרש עליה. אז, מסתבר יותר שיש לו שם כזה בדווקא, וקראו לו כן כדי לדרוש זה. ותו"ת. גם יש לומר שלא מסתבר שהיה מקומות במדבר שהיו להם שמות, שהרי מדבר היה, ומי דר בו לתת לול שם. אז, מסתבר שבני ישראל נתנו בו שמות, ואז שפיר יש לומר שלכן נתנו בו אותו שם. ותו"ת.
55. נ	לענין אכילה- יש לדון מהו הפסול לענין בכור. אפשר שהוא מפני שהוא נחשב קצת מין אחר. אז, פטור מן הבכור. אם כן, דין של כשרות מחודש, שמחדש שעדיין נחשב די מאותו מין להיאכל (או שלא צריך להיות ממין כשר, אלא לבוא מן הכשר). גם אפשר שהפסול הוא מחמת שאינו נראה כשאר מינו (או שאינו נראה כאמו). ותחשב. אפשר שהוה אמינא שזה אוסר אכילתו, או אפשר שהוה אמינא שאין זה הסיבה שאין לו דיני בכור. ותחשב.
56. ואם תאמר לצד ראשון, למה פטור אם השני הוא ממין שחייב. ויש לומר שהוא חצי ממין זה, שמזה אמו, וחצי ממין זה. חיובם חלוק, ואז אין סיבה שלמה לחייב. ויש להוסיף צד שאולי חיוב של מי שיש לו עז הוא לתת עז, ושל מי שיש לו רחל הוא לתת רחל (ולא רק צריך להיות עז או רחל, אלא אותו עז ואותו רחל). כאן, לא יכול, שאין זה עז, אלא חצי עז, ואין זה רחל, אלא חצי רחל. אם כן, אי אפשר לקיים חיובו, וממילא פטור. ויש לדון, שהיה אפשר לומר שחיוב עז, כיון שבא מחצי עז, מחייב אותו לשלוח חצי עז; וכן חיוב רחל. ותחשב.
57. נא	פטר פטר קנסיב- היה אפשר לומר שמשנה אומר שבשני מקומות אלו אין פטר חמור, אבל לא אומר כלום על דין בכורה של פרה. ותחשב. שוב ראיתי שכוונתי בזה לתוס’.
58. ו.
59. נב	בבכורה- יש לדון מה לנו במה שהוא חייב בכורה. עיין לעיל, שכתבנו שני צדדים למה יש פסול. אפשר שהוא מפני שהוא קצת מימן האחר. אז, יש לומר שאף שהאו קצת ממין אחר, עדיין יש מקצת סיבה. גם אפשר שהפסול יהיה שאינו דומה לאמו[fn:7]. אם כן, הענין בזה הוא שאינו כל כך חלוק, שהוא רק נראה כמין שאינו כל כך חלוק ממינו. ותחשב.
60. קשה לומר צד הראשון גבי מה שאומר גמרא גבי סוס. צריך לומר שכיון שהוא דומה לו, יותר מסתבר שיש לו קצת סיבה לקדושה. ודחוק.[fn:8]
61. נג	קרנים- לעיל, באר גמרא הדמיון על פי מה ששניהם טמאים. כאן, תולה אותו במה שגופם דומה. אולי זה מפני שלעיל היה דן אם מצרף לדין מקצת סימנים, אבל כאן מבאר איך יהיה חייב אף בלי מקצת סימנים. לא היה נראה שזה מחלק. ותחשב.
62. ו:
63. נד	גמל טמא הוא- קשה ל"ל נדייק להיפך, לומר שרק גמל, שיוצא מן הטמא ונראה טמא אסור, אבל היוצא מן הטמא, ולא נראה טמא, לא אסור. אפשר שאם כן, אין חידוש. זה אומר שכבר היה נראה לדרוש "ממעלי גרה" כן.
64. נה	ממעלי- יש לדון למה צריכים קרא זה למסקנא. לכאורה, כבר לומדים היתר של טמא הבא מן הטהור מ"הוא" שנאמר גבי גמל. אז, צריך לומר שצריכים קרא זה לאסור טהור הבא מן הטמא. זה פשוט, אבל טוב לבאר אותו.
65. נו	אימא הבא ממעלה- לכאורה, צריך לבאר מהו סברה החיצונה. מקושיה זה, רואים שיש סברה חיצונה שטמא שבא מטהור יהיה מותר. מדרשה ראשונה של גמרא, רואים שיש סברה חיצונה שטהור שיוצא מן הטמא מותר. אם כן, לכאורה, זהו הסברה חיצונה, ששניהם אסורים. ותחשב.
66. נז	למילקי על בישוליה- קשה, שהרי דורשים מקראי שחייבים אף על אכילה. אולי רבי שמעון לא סובר כן. וצריך לעיין.
67. נח	כל היכא- ר"ל שיותר מסתבר לדרוש משלא לדרוש, שאז לא כפל כל כך כמה דברים, ועוד שאז כפל מחמת יותר. ותחשב.
68. ז.
69. נט	אישתני מגמל- יש לדון מהו הצד שלא לומר כן. אפשר שהוא שכיון שרובו כעין גמל, עדיין הוא נחשב גמל. (ויש להוסיף שאפשר שחלק ממה שנקרא גמל הוא שאינו יכול להיקרות שום מין אחר.)
70. ודע שצריך ביאור מהו הצד שלא נקרא אותו גמל מחמת זה, שהרי גבי בכורו שור אומרים שראשו ורובו מהני. צריך לומר שמיירי כאן בבהמה שאין ראשו רובו כגמל. אם כן, צריך ביאור מהו הצד שנקרא גמל. ותחשב על זה. יש לדחות שאולי מה שנקרא בכור שור הוא רק מפני שאף אמו שור, ואז מהני רק לשור ולא לעשות שהוא גמל. ותו"ת.
71. ס	אם זה בכלל גמל, צריך ביאור למה צריך קרא לאוסרו, שהרי אומר תורה שגמל לא כשר. צריך לומר שקרא אומר שגמל אסור. לא נצרך, ואז צריך לומר שקאי על זה, וגם קורא לו גמל. אז, מחדש שהוא גמל. ותחשב.
72. סא	מי מיעברא- צריך ביאור ל"ל נדייק כמש"א גמרא בלשון ראשון, שלכאורה הוא דיוק יותר פשוט, שהוא מדין הברייתא עצמו. ותחשב.
73. סב	זה וזה גורם- זה מעניין, שלכאורה, כאן לא תלוי במה נחשב גורם שלו, אלא במינו. צריך לומר שפשוט לגמרא שבזה תלוי מינו (במה גרמו). ותחשב.
74. סג	ואמר ר"י- ממה שעדיין נחשב אסור, ולא פושטים מזה תירוץ שלנו, צריך לומר שמה שיכול להוליד מן הטהור, כמו טהור, לא נחשב סימן אחד שדומה לאמו. אולי מפני שאין אמו מוליד (ואז הוא רק דומה לאביו), ואולי הוא מפני שלא נראה.
75. סד	זה וזה גורם- יש לדון למה אין כל וולד זה וזה גורם, כיון שאף ה’ גורם. אולי אין הכי נמי, כן הוא. אולי הוא מפני שטמא הוא רוב. גי"ל שה’ שותף רק בבנ"א. גי"ל שכיון שה’ בכל מקום עושה כן, אינו נחשב שותף. איני מביין אותו צד אחרון כל כך, אבל מצאנו כמו כן. ותחשב.
76. ז:
77. סה	דלא שתו- יש לדון אם זה סיבה שלא ישאל (שלא נוגע) או שלא מסופק. לשני, לכאורה, יהיה סיבה שאינו אסור, יש לדון אם לא נאסר מחמת שינוי בחפץ או במעשה.
78. סו	שם לווי- קצת צריך ביאור למה זה סיבה לאסור. לכאורה, לא ידועים למה דבר מותר, שהרי בא מגוף של דבורה. לכאורה, על סיבה להתיר יהיה תלוי איך זה מתיר אותו. אפשר שיש לו עוד יחס לדבר האסור, והוא שנקרא על שמו. לא משמע כן כל כך, שאם כן, אין הענין שיש לו שם לווי, אלא שנקרא שם השרץ באותו שם לווי. ותחשב.
79. יש לדון מהיכי תיתי לרבות דבש צירעים, שלכאורה, כ’ בקרא שדבר שרק שרץ עצמו אסור. אם כן, יהיה דבש של כל מותר. וצריך ביאור.
80. סז	רחמה צר- כמו שאומר גמרא בב"ב (שאמר כן ה’ לאיוב).
81. סח	טעמא דחזיניה- ואם תאמר מהי”ת שלא רק אומר משנה עיקר הדין- עיקר הדין הוא שאם אכל, מותר.  לא מזכיר דין אחר, והוא איך נדע. אולי כיון שהוא כל כך נוגע, היה צריך לבאר איך יודעים.; משמע שהוא כסברה חיצונה. אז, צריך לומר שזה סב”ח. ותחשב עוד.
82. סט	האי אשרץ- ואם תאמר למה נניח שזה הלך וזה אחר; הרי לא אומרים כן ביוני שובך בביצה. ותחשב. ונראה ששאני כאן שדרך דג הוא לאכול מה שבלע ולעשות אותו לרעי, ודרכו גם להשריץ. אז, מסתבר כאן שכן קרה.
83. ע	כמו שבלע- לשון זה מוזר, שלכאורה, עדיין הדיוק מן המשנה עומד במקומו, ומיירי כשרואים שבלע. זה רק הוכחה שבלע זה. ותחשב.
84. עיין בתוספות שכ’ שאחר ר”א לא צריכים לראות. נראה שר”א מבאר שלפי מש”א, ההוכחה מסתבר להיות כל כך חזק עד שצריך לומר שלא צריכים לראות שבלע. ותחשב, שלכאורה, אין זה מוכרח.
85. ח.
86. עא	שכינה עמהם- יש להעיר שלא דבר ה’ עם דג עד כמה שנים אחר בריאה. אולי לא הבינו למה הוא משונה עד אז, ואולי ידעו שעתיד הקב”ה לדבר עמו. גי”ל שלא עשה כן עד אחר שדבר עמו ה’.
87. ויש להעיר שהיה אפשר לומר שמה שמינו נגרר אחריו הוא שהיה הראשון (כמו גבי אדם רנחש), שכיון שכולם באים ממי שמשמש כך, או ממי שדבר עמו ה’, כן עושים. בדג אינו כן, שרק אחד מכל המין היה מדבר עם ה’, ועכשיו כולם משמשים כן. ותחשב.
88. עב	לעשרים- איני יודע אם אלו מזמן ביאה או מזמן שנקלט שכבת זרע והתחיל לעשות עובר. אולי אינו זמן אחד (שהרי יש לו שלש ימים לפלוט גבי אדם). ותחשב.
89. עג	אילן תבואה- לשון זה כרבי יהודה, שקורא לחיטים בשם אילן (שאומר שהיה עץ הדעת). ותחשב. שוב ראיתי שרש"י כאן מעורר כן.
90. עד	על אחת ז- קצת יש לדון מהיכי תיתי שהוא תלוי בפרופורשי”ן, ולא תלוי רק ביותר זמן. אז, אולי אמר שהוא שנה עם שש שבעי שנה. ותחשב.
91. ח:
92. עה	אם כלב חיה, קשה ל"ל אומרים שעיבורו גדול כגודל עיבור חמור מכלב. ויש לומר שלא מניחים שהוא מנין שאינו כל כך איבי”ן. דחוק, שחתול הוא כן, שאינו איבי”ן. ותחשב. אפשר שאין הכי נמי, אולי הוא כן, אבל גמרא לא דק. מוזר שיהיה כן, שלא רק אומר מנין, ולא דק בו, אלא מבאר מהו הדרשה, וצריך לומר שאף בו לא דק. ותחשב.
93. עו	מכל- לכאורה, הענין הוא שמה שהוא הכי גדול כולל כולם, שעיבורו הוא גם כימי בהמה זה על חיה זה וגם כבהמה זו על חיה זו וכדומה וכדומה. ותחשב. יש לדון מה סובר החולק. אפשר שלא דורש כל (ואולי זה מפני שכתיב “מ” לפניו, שקצת ממעט). גם אפשר שסובר שאינו ככל, שהוא יותר מכל. זה כעין דיון של גמרא בפרק שני של זבחים אם יתר כנטול או לא.
94. עז	אחד משבעה- לכאורה, מנין זה קצת לאו דווקא, שאי לאו הכי ששנים עשר חדש הוא פחות מזה, ואף אם כולם מלאים. אז, לכאורה, צריך לומר או שלא דק או שלא מניח שהוא מנין שאינו איבי”ן. אם כן, קל לומר כמו שכתבנו ב”עה.”
95. עח	רישא- עיין בגמרא בפרק ראשון של ערכין לביאור מה היה הדין אילו היה כן.
* Footnotes
[fn:1] יש לדון, שתירוץ ראשון שכתבנו יתרץ לשניהם, אבל תירוץ שני שכתבנו לא יתרץ לקושיה על צד זה, אבל יתרץ לקושיה על צד שאומר גמרא. אולי, באמת, זה ראיה שהוא תירוץ נכון.
[fn:2] כמו כן מצאנו בכמה מקומות. הדוגמא הגדולה לזה הוא סוגיה של מוציא מיד מוציא גבי דמי חטאת ביומא. ותחשב.
[fn:3] יש להעיר שהנחתי שחולקים בפירוש בכור, ואז חולקים גם בפירוש כל. היה אפשר לומר שלא חולקים בפירוש כל, אלא חולקים אם, אז, הוה מיעוט אחר מיעוט (או ריבוי אחר ריבוי) או לא, שרק אומר גמרא שבא אותו קרא לומר דין זה. אבל, סתימותו לא משמע כן, אלא משמעש רק מלד אותו, ואינו מיעוט אחר מיעוט או כדומה. ותחשב.
[fn:4] ר"ל, אינו כהוה אמינא
[fn:5] יש לדון אם זה נכון, שואלי הוא שווה במה שהוא מוזר. ותחשב.
[fn:6] בפשט זה, צריך לעיין לעיל באות מז.
[fn:7] לא בארנו מהו הפסול בזה. אפשר שהוא כעין מום. גם אפשר שאז לא מיוחס כל כך לאמו, ואז לא בא לו קדושה של בכורה.
[fn:8] בפרט כיון שיש לנו קצת סיבה למה חייבים חמורים בלחוד, ואינו שייך לטומאה וטהרה. ותחשב.
