* ב.
** א	מייתי לה -
לא ליקנסיה- קשה, אז, ל"ל אמר גמרא שיש סיבה אחרת שלא לקנס, והוא שאין סיבה לקנס כלל, שמה עשה שלא כדין. אולי יש גזירת קנין אטו גזירת מכירה. דחוק, שלא מצאנו במקום אחר גזירה כזה. ויש לדון, שאולי הא גופא הוא הסיבה שלא מצאנו גזירה כזה (שמביא אותו לקדושה).
לולי רש"י, היה נראה לומר  שאומר גמרא שהוה אמינא שבאמת יתחייב, אבל כיון שהביא אותו לקדושה, לא חייב, שפטר אותו הקרא. אולי רש"י סובר שלא מסתבר שיפטור ה’ אותו ממצוה כיון שעשה דבר טוב. גם יש לומר שאינו דבר טוב להיפטר ממצוה; להיפך, מצווה גוררת מצווה ושכר מצווה מצווה. (עדיין היה אפשר לומר שהיה לו להיות חייב מדרבנן, שנראה כאילו היה לו להתחייב מדאורייתא, ואז רבנן פטרו אותו מחמת שהביא אותו לקדושה).
** ב	או דילמא -
אל אתי לאחלופי- לכאורה, היה אפשר לומר שכיון שאינו מוזר, יש לומר עליו לא פלוג. עיין ברשי בגיטין (טז:) שמשמע שסובר שזהו לא פלוג (אם באו להכשיר זה יכשירו זה). אם כן, כן אומר רש"י. לא פלוג הוא רק הכלל שאומר שגזירה כזה (השוואת ציורים) הוא דבר שנצרך כדי שלא יעברו בני אדם. ותו"ת.
** ג	תוד”ה הלוקח -
שניהם במוכר- יש לדון איך היה שונה שניהם בלוקח או במוכר, שבאחד לא היה העובר של ישראל. לכאורה, היה לו לשנות עדיין הנפקא מינא שיצא מהיותו קדוש. אף שגוי לא יחייב להביאו, אז, עדיין יהיה קודש, ויצא מזה נפקא מינא. ויש לדון מהיכי תיית שאין גוי חייב להביאו, שאולי הוא קצת של כוהן, והוא כעין גזילה. ותחשב על זה. עיין בשי”ח ש”י על גמרא שהנחנו שאינו בר חיוב, אבל ראוי לציין לכאן.
** ד	והמשתתף -
מדאיצטריך בישראל- משמע שבא בישראל רק לדין זה, ולא לדין אחר שבמשנה. לכאורה, דינים אחרים נלמדים מקראי שהביא תוס’ בדיבור שלעיל.
** ה	לקדושת בכורה -
וא”ת הרי הוא עצמה לא הביא לקדושת בכורה, שהוא עצמה לא הובא, אלא בנה. אולי משמע שיש קדושה באם שגורם אותו הבאה. צריך לומר לא רק שיש אותו קדושה, אלא שרוצים באותו קדושה. ויש לדון, שאולי כיון שהגענו שבא מקדוש שלה משתמשים במילים של “מביא אותו לקדושה.”
** ו	נקבה -
משמע שהוא מפני שרוצים שיעשה כן, ולא מפני שעשה מצווה, שהרי, בזכר פטור, אף שלא עשה מצווה. ויש לדון, שאולי מה שעשה דבר מפני צד הפספק שיהיה טוב הוא סיבה די לפטור אותו. ודע שכיון שאומרים שהאו טוב מפני שעשה אותו מפני אותו צד ספק, אם לא כיוון לשם מצווה, יהיה פשוט שלא לומר כן. ויש לדון אם זה בעיה. על כל פנים, יש לדחות שעשה מעשה שה’ רצה שיעשה, וזהו מצווה שלו.
** ז	ומכל שכן - ח	לאפוקי מדרבי יהודה -
ר"ל כיון שכבר אומרים שחד מתרי ותלת טעמי, עוד לא קשה למה לא נקט מה שהעיר תוס’ לעי
לכאורה, ההבנה הוא שאומר שצריכים להביא זה כדי להראות חידוש, שיש לחלק בין זה לשאר ציורים. ההוכחה שיש לחלק הוא שיש תנא שמחלק. תוס’ מעורר שהיה אפשר לומר שיש לחלק מסברה (כיון שכאן אף רבנן מודים שיש לחלק, אלא שיש עוד קרא), אלא שרצה להביא סמך לזה ממה שיש תנא שמחלק.
** ט	משום טיבותא -
קצת צריך ביאור בזה, שמדאורייתא, צריך לתת השותפות. קשה מה פוטר אותו מזה. אולי עשו רבנן אינו זוכה כזוכה, ונתנו רבנן לכהן והחזירו לזה כיון שנותן דמיו לכוהן. ויש לדון, שלא כל תנא אומר שעשו רבנן אינו זוכה כזוכה. גם יש לומר שהפקיעו רבנן קנין של כוהן כיון שזה נותן לו דמיו. צריך לומר שיש לכוהן רק קנין לחייב לתת לו, שאי לאו הכי, לא יוכלו רבנן להפקיע אותו, לכאורה.
גם יש לומר שיכול כוהן למחל על מתנת כהונה שלו, ולבטל אותו לטובה אחרת. ותחשב.
** י	ונותן -
לשון כל תוס’ זה מוזר, וצריך לעיין בהגהות וציונים (במה שמביאים משיטה מקובצת).
* ב:
** יא	בהמה לעוברה -
לא נתעברה- לכאורה, יכול אדם למכור אותו לעוברה אף אחר שמעוברת, אלא שרשי אומר שלא צריך להיות שכבר מעוברת, כמו שצריך להיות כדי למכור עובר. ויש לדון, שאולי כיון שבהמה מתעברת, כבר קנה הבעל, ולא יכול למכור עוד אלא עובר עצמו, ולא אותו קנין שיגרום קנין עובר. ותחשב.
ועיין לקמן ברשי (ונבאר אותו בשיח שי בע”ה) שלכאורה היה רש"י צריך לומר זה.
** יב	שמא יתחייב- עוד מייתי ר”ת ראיה -
יש לדון איך מביא ראיה מזה, שרק סובר שמותר לקבל שבועה מהם כיון שצריך, אבל לא לכתחילה לעשות שותפות כיון שיצטרך לקבל שבועה. אולי ר"ל שצריך לומר שזה היה שום מקום הצורך לעשות עמהם שותפות.
ויש להעיר שהיה קל לדחות על פי תוד”ה אסור לאדם לומר שחלק על אבוה דשמואל. כמו כן, היה אפשר לדחות כל ראיות של אותו תוס’ על פי שיטת רבינו תם, שואלי שם היה מקום הצורך. יש לדון למה לא הביא תוס’ אותם לראיה לרבינו תם, ולמה הביא זה במקומם לראיה. ותחשב.
** יג שיתוף -
לכאורה, זה אומר ששיתוף מותר להם, שאי לאו הכי, יהיה איסור של לפני עוור. ויש לדון, שאולי אין זה עבודה זרה, שאין איסור לשבוע על שם עבודה זרה. עיין בשיח שי על גמרא כאן שהוכחנו כן ממה שצריך איסור זה כלל. ותו"ת.
** יד	שלש סעודות -
יש שיטה לאור זרוע שחיוב שלש סעודות הוא רק אם אדם רעב, ומטעם עונג שבת. אם כן, אפשר שיש חיוב לשל סעודות, והוא כמו שאמר אור זרוע, אבל אז נמצא שאין צריך שלש דווקא. אבל, כיון שדרשה מן הקרא אומר שלש, יש ענין לאכול שלש. על זה היו דנים אותם אמוראים שם בשבת. ותחשב.
אין הוכחה שאין זה כוונת תוס’. לולי זה, כמובן, תוס’ אומר שכל אותו דרשה אינו חיוב לגמרי, אלא רק מצווה. מסתמא, אז, אינו מצווה דאורייתא, אלא דרבנן, שאם הוא נשמע ממש מן הקרא, לכאורה יהיה חיוב. ותחשב.
ודע שמעניין שנותנים אותו מזון לעניים, אף שאינו חיוב ממש. ותחשב.
** טו	דעיקר -
עיין במה שפירש. לשון עיקר, אז, קשה. אפשר לומר שרשי סובר שגמרא מבאר למה לא נשנה איסור זה, והוא מפני שאינו עיקר איסור מכירה, ולהוכחה שאין המשנה מזכיר כל איסור, הביא עוד איסור שלא הזכיר. לא צריך להוכיח ש”עיקר איסרו” ומה שאומר תוס’ הם כוח שווים, שזה פשוט לו; רק צריך להוכיח שכשיש דבר שיש לו אותו כוח, לא שנה אותו במשנה. אם כן, יכולים לומר כרש”י. ותחשב.
* ג.
** טז	כל בכור -
בישראל- משמע כצד שכתבנו שלא בא רק למעט נתינת חציו, שאי לאו הכי, מה לנו שחציו הוא של עכו”ם, ואומר בישראל; לכאורה, כבר פשוט שאין גוי חייב בזה, אלא רק אומר שמה שנולד ברשות גוי פטור. ותחשב. ויש לדחות שהיה צד לחייב גוי מטעם גזילה, כמו שכתבנו לעיל. ותחשב.
** יז	נבילה -
כוליה- לכאורה, לא ר"ל כוליה, אלא ר"ל חציו, שבא לבאר הציור שיש מחלקת רבי יהודה ורבנן של שותפות. ויש לדון, שאולי שותפות הוא מה שיש לשניהם יחס לכולו, ואז צריך יחס לכולו. זה עושה, אולי יחס של חצי בעלות לכל אחד, אבל רש"י מבאר הענין הראשון, והאו שמיוחס לכולו, ואומר שזה כן, כיון שכולו חי מחמתו. ודע שלא מוכרח לומר כן, שיש לומר שיש לו קנין חציו על כל הבהמה כיון שמיוחס לחלק חשוב ממנו. ותחשב.
** יח	שגר -
לשון אחר- לכאורה, לשון זה יפרש שהדיוק הוא ממה שאומר לשון שגר ולא לידה, שמשמע שמה שקרה לא היה לידה, שהרי לא נולד שום וולד, אלא נפל. ותחשב. (ויש לדון, שעדיין יכול לשון לידה להיאמר עליו, שהרי יש בו טומאת לידה.. ותחשב.)
** יט	שגר -
לשון אחר- ללשון זה, לכאורה לא גורסים “שגר בהמה שגר בבהמה,” אלא “שגר בבמה,” שמזה בלחוד בא הראיה. ותחשב.
** כ	ורבי יהודה -
בקושיית תוס’, נראה שיש להוכיח שסבר תוס’ ש”כוליה משמע” דן במשמעות הקרא- מהו משמעות של מילה סתם- ולא במה מסתבר. (עיין בשי”ח ש”י שדיננו בזה.) אם היה אומר שאין גמרא דן במשמעות, אלא מהו סברה חיצונה, אז קל לומר ששם אין הסברה חיצונה שווה לסברה חיצונה של כאן. ותחשב.
ודע שלא נראה שתוס’ מת’ כמה שכתבנו כאן, אלא נראה שתירוצו הוא שמשמעות של מילים חלוקים הוא חלוק, ואין מחלקת אחד אם  מילים משמע כל או מקצת.
** כא	בישראל -
צריך ביאור מהו אותו משמעות.
** כב	רב חסדא -
תוס’ מוכיח שגי’ של שם נכון, שמסתבר שעולה גמרא לרבות כמה צריך גוי לקנות. יש לדון למה כל כך פשוט שיעשה כן גמרא כאן. ויש להעיר שכמו שאפשר לשנות הגירסא כאן, כך אפשר לשנות הסדר כאן. אולי לא היה טועה בזה כמו שהיה טועה בשיטתם. יש לדון. יותר מזה, יש לומר שאז צריך שני שינויים, ולא אחד כמו אם היינו משנים כמו שאומר תוס’.
** כג	שכל אחד -
לכאורה, קצת מוכח כן (ולא רק שכזה יצא הסדר במקרה) שבדרך כלל מקימים מי שחי מוקדם. אם כן, קשה למה מקדמים רבא. צריך לומר שהוא כדי לסדר כך. ותחשב.
** כד	בא דר”ה -
נמצא שתוס’ אומר מה שרשי אמר בפירוש. אולי כתבו כן למי שלא ראה מה שפירש רש"י. גם אפשר שהיה לו רש"י חלוק מרשי שלנו, וברשי שלו לא פירש כן רש"י. ותחשב. ודע שמצאנו כעין זה בכמה מקומות.
* ג:
** כה	מילתא -
נראה שרש"י מפרש שחוששים שלא ידע אחר לקנות כמו רמב”ר. אז, לא היה לו להקנות לגוי, אלא לנהוג עמו בקדושה, שאחר יבין שהקנה לגוי כדי שלא יתקל, ויקנה, אבל לא יקנה בדיבור, ויחשוב שקנה. ותחשב.
היה אפשר לומר גם כן שחוששים שאחר יחשב שלשא קנה לגוי, ואז יבוא שלא לקנות לגוי, וזה רע, שהיה לו לקנות לגוי, שחוששים שמא יתקל מחמת הקדשים שיש ברשות שלו. ותחשב. אולי לשון גמרא לא משמע כן.
** כו	אלא לאו -
היה נראה לתרץ לקושיית תוס’ שאין הכי נמי, גמרא מקשה מזה לרבי יוחנן, ורבי יוחנן צריך תירוץ גמרא, והוא שאפשר לומר שני צדדים במשנה, ורבי יוחנן בא לבאר איזה הוא הנכון. ותחשב. אולי סובר תוס’ שיאן לשון גמרא משמע כן.
שוב הבנתי שאין תוס’ מקשה מהוכחת גמרא, שקל לתרץ כמה שכתבנו. תוס’ מקשה מדיוק מן אותו משנה, איך ידחה אותו רבי יוחננן למעשה. ויש לדון, שלשונו קצת לא משמע כן. ותחשב.
** כח	הפקעה דאם -
נראה שהענין הוא שאז לא היה קדוש לעולם. אם כן, יכול לתת אוזן כשהוא עובר. אולי יש לו קצת קדושה אז  (אף שצריך בית רחם לקדשו ביציאתו, לכאורה), אולי נותנים אוזן אם אף קודם שנתעברה.
** כט	כדפרישית -
אין זה כל כך קשה, שאולי אין הכי נמי, יש תקנה בזה, אבל נקט מה שאומר גמרא בפירוש. ותחשב. וצריך לעיין שם באותו גמרא, שאינו כל כך ברור לי לדון בו.
** ל	היה לנו לתקן -
יש לדון, שלמעשה לא תקנו כן חכמים, ואולי כיון שלמעשה לא תקנו כן, אף שהיו מתקנים כן, לא מותר לעשות כן. ויש לדון.
** לא	יש להעיר
שכל מה שאומר תוס’ מתו’ על פי פשט שכתבנו בביאור גמרא נגד רש"י. יש לדון, שאולי רק דן בצד ראשון של גמרא. ויש לדון ל"ל תירץ, אז, שסוברים אנו כצד שני. ויש לדון, שאולי קשה לו למה נפסוק כאותו צד,, ולמה לא נחמיר מספק. ותחשב.
** לב	דבר שלא בא לעולם -
וא”ת הרי גמרא דן ליעל במוכר עובר. ויש לומר שזה רק לפי השיטה שיכול אדם להקנות דבר שלא בא לעולם. ותחשב.
* ד.
** לג	אלא אמר רבא -
מדאיצטריך- קשה מהיכי תיתי שאינו להיפך, שפוטרים הכל מקל וחומר, אלא שאדם לא נפטר, ולומדים ממנו פטר חמור, ולכן צריך ההיקש. לכאורה, הדרך שכתבנו יהיהי חומרא, שיגרום פטור על רק מין אחד. ויש לדון, שאולי יותר מצוי. גם יש לומר שההיקש יותר פשוט אם נאמר כדרך  שאומר גמרא, שאז לומדים מה שהוא מסתבר להיות הדין בזה לזה. ותחשב.
גם יש לומר שמסתבר שיהיה הקל וחומר נכון ברוב מקומות.
** לד	לויה -
לא נמנו נקבות- קשה, שלכאורה היה לו לומר שלא נמנו בני לויות, אלא בני לווים. ותחשב.
** לה	הוקשו -
נראה שסובר שזה מתרץ קושיה ראשון כיון שאז כל הלויים הוקשו זה לזה. ויש לדון ל"ל אומרים שהוקשו זה לזה לומר שכל שיש לו שה פוטר. זה אומר שיש לדון מה בכלל מהו הדרשה, ומה בכלל במי הדרשה. ותחשב על זה.
** לה	והא -
מלקדש- לכאורה, ר"ל מלתת שה, שאין אדם עשוה דבר לקדש פטר חמור, לכאורה. ותחשב. אולי “לקדש” רק ר"ל לנהג עמו קדושה.
** לו	מה שיכול לנהוג עכשיו -
קשה, שעכשיו פוטר אף בלי שום שה, כמו שמקשה ומתרץ בגמרא. אולי אין הכי נמי, אבל למעשה זה יכול לנהוג היום, אף שיש דין אחר שכבר יעשה כן. שוב הבנתי שאין כוונתו לומר שאם יש ללוי שה אחד פוטר הרבה חמורים שלו, שעל זה יש להקשות כמה שכתבנו. אלא, צריך לומר שאין זה שהשה פוטר אותו, אלא שאין כוהן חייב כלל, שאין סיבת החיוב. אלא, לומד ממה שיראל יכול לפטור כמה חמורים עם שה אחד. ותחשב.
** לה	לשון -
עיין לעיל, שכיוונו לזה.
** לו	שאין קדושת השה של לויים -
צריך ביאור מהו סברה זה, שעדיין נעשה קל וחומר ממה שקדושת לויים פטר של אחרים. ותחשב.
* ד:
** לח	ופודה בו פעמים הרבה -
אם קונה- וא”ת הרי במדבר לא הוצרכו לקנות מן הלווים. ויש לומר שזה מפני שבמדבר, לאיזה סיבה, לא היו צריכים נתינה. מה שצריך לקנות אותו הוא דין בנתינה.
** לט	ופודה בו -
קצת צריך ביאור ל"ל יאמר כרש”י. אפשר לומר כמה צדדים פשוטים:
1. אפשר שסובר שמשנה לא אומר כן. עדיין נצטרך לדון ל"ל אומר כן משנה. אולי הוא רק בגלל שרוצה לדבר בספק, ואז אמר דין זה בספק אגב שאר דינים.
2. אולי סובר שדין של רש"י אינו נכון.
3. אולי סובר שדין של רש"י פשוט, עד שלא צריך לימוד זה  (ר"ל, אין זה הטעם לדינו של רש"י, אלא פשוט הוא כן, אף בלי טעם זה).
4. אולי סובר שדין של רש"י פשוט, ויותר מסתבר לגמרא או לברייתא לומר דין שיותר מחודש.
5. מבאר תוס’ ראשון, אז, זה בוודאי אפשר.
6. על שני, לא נראה כן, שרק אומר כן על ציור שלא כבר נתן. גם יש להעיר שלכאורה דין של רש"י יהיה למד מדין של מדבר, שלמה לא, שהרי זה מוכיח, לכאורה, שיכול בהמה אחת לפטור כמה שיין. ותחשב. גם בציור תוס’ הוא כן, לכאורה, שהרי שם נותן כמה קדושות עליו. ותחשב.
7. על שלישי, נראה שאולי הצד לזה יהיה שכיון שבא לכהן, אין השה קדוש עוד, שנתינתה לכהן עושה שלא קדוש. ויש לדון, שמוזר שנתינה לכהן יעשה כן. אולי רק קדוש כל זמן שצריך לאותו קדושה, שה’ קדשו כדי שיינתן לכהן. זה מעניין, שמעניין שלא ישאר אותו קדושה, ומעניין שה’ יעשה כן, שהיה לו רק לגזור שילך לכהן, וזהו הוא. ויש לדון.
8. גם יש לומר שסובר שנתינת כהן לישראל מוריד אותו מקדושתו. ויש לדון, שהיה קדוש לפני שנתן לכהן (כמו שמוכיח תוס’, לכאורה, מדין ספק). אם כן, יודעים שאין קנין של זר עושה שאינו קדוש. ותחשב.
9. אפשר שצריך להסיר הקדושה כדי שלא יחזור לו לאחר שנותן ללוי. יש לדון אם יש לו אותו כוח. ותחשב. גם יש לומר שמה שנתמעט בקדושה, שבא לישראל, ממעט הקדושה ממילא. ותחשב.
10. על רביעי, אולי צריך לומר שכאן הוא יותר פשוט כיון שיש נתינה חלוקה לכל אחד ואחד. צריך ביאור מה לנו בזה, שלכאורה החידוש הוא שאחד פודה בו כמה קדושות, ולכאורה נתינה הוא רק תוצאה של קדושה.[fn:1]
11. מ	מעיקרא- במצרים- נמצא שהיה קדושת בכורות במצרים, אבל לא במדבר. זה מעניין, שהיה נראה לומר שמה שהק’ רק בא”י הוא שמה שהיו בני ישראל על אדמתם גורם חיוב זה. (ואם תאמר הרי נתחייבו אף אחר שיצאו. ויש לומר שמה שהיו בארצם יכול לגרום אותו חיוב, ולא רק מה שהם עכשיו בארצם. גם יש לומר שכיון שכחל החיוב, לא פקע. זה מעניין, שחל על בהמה חלוקה, ועל איש חלוק, שחייב אף מי שלא חי לא הוא ולא בהמתו בזמן שהיו בני ישראל בארץ ישראל. וצריך לומר שממשיך כיון שהוא חל כבר על אותו עם. זה מעניין. ואם תאמר הרי שאר חיובים אינם כן. ויש לומר שאין הכי נמי, זה חלוק משאר חיובים.) על כל פנים, לא נראה כן כיון שבהמות שבאו ממצרים לא היו חייבים.
12. אפשר לומר שבני ישראל חייבים אם הם במקום הכי טוב להם. קודם יציאה ממצרים, או קודם קבלת התורה, לא היה כל כך טוב שיהיו בני ישראל בארץ ישראל; רק אחר שנתקדשו היה כן. עדיין צריך ביאור למה אינו כמצב שלאחר יציאת בני ישראל מארץ ישראל. יש לומר שאי אפשר לומר שכבר חל חיוב על העם, או שהיו כבר במקום שיחייב אותם, ששינה העם. ותו"ת.
13. מא	לא קדשו (תוס’)- ואם תאמר אולי היה אותם בהמות טהורות שיצאו ממצרים. ויש לומר שכבר הקריבו את כולם למזבח. ואם תאמר ומה בבעלי מומים. ויש לומר שמסתמא כבר נתנו את כולם לכוהנים. ותו”ת.
14. ה.
15. מב	ואפכיתו- משמע שלא היה זה קורה אלא לתלתיד. אפשר לדחות שהיה קורה למי שלא היה תלמיד, אבל יותר טוב שיקרה לתלמיד, ואז היה בא לתלמידו, ולא לר”א. יש לדון מה נחשב תלמיד של ר”ל.
16. מג	ואפכיתו- יש לציין לגמ’ יומא שאמר שלא היה מדבר ר”ל לר”א כיון שאל היה מחשיב לו כל כך. עיין בשיח שי בברכות (גלגל חמישי) שחדש שלא היה ר”א כל כך נחשב (ויש לדון, שהרי היה נקרא מרא דא”י), שהרי ר”י לא רצה ללמוד עמו, וריש לקיש לא דבר עמו, ור”י אמר לו שלא לבכות על תורה, שאחד המרבה ואחד הממעיט.... ותחשב על זה.
17. מד	מעניין שלא היה ר”א נחשב תלמיד של ר”ל, שיודעים (עיין בגמרא בסוף ב”ק) שהיה ר”ל חוזר על מש”א ר”י לשאר התלמידים. אולי לא היה ר”א תלמיד אז.
18. ומנה- היה אפשר לומר שקאי לפי השיטה שכתובה דרבנן.
19. ה:
20. מה	לגמרי ילפינן מהדדי- לא הבנתי מה לנו בזה, שהרי אף חמור לא יודעים שיפטור אם נשתנה לדבר שיש בו אותו חיוב, שאין דבר אחר שיש בו אותו חיוב. ויש לומר שיודעים שיפטור אם נשתנה לדבר שיש בו קדושת הגוף. ויש לדון, באמת, איך יודעים לדרוש כן, שאין קרא מיותר לזה. וצריך ביאור. גם מעניין שנגדור אותו כך, ולא נגדור אותו על פי מה שיש לו קדושה שווה. ותחשב. ואולי בכלל קדושת הגוף יש קדושת דמים. ותחשב.
21. גם מעניין שדורש ממה שחמור פטור, אף אם נראה כמה שיש לו קדושת הגוף, שהרי משנה לא אומר כן (עיין בתוד”ה ומה הן ובש”מ וגליון). ואפשר לומר שתוס’ סבר שפטור בכל ציור בפטר חמור, שלא יכול להיות בהמה שיש לו אותו חיוב, ומה שיש לו קדושת הגוף לא משנה מידי. אז, יש רק ציור אחד, וקרא פוטר. כיון שיודעים שפטור בכל ציור בפטר חמור, דורשים ממנו לפטור בכל ציור בפטר פרה. ותחשב על זה.
22. מו	יש לנו לדרוש מן הראשון- גם היה אפשר לומר שהוא כעין “הי מינייהו אפקית,” שאילו היינו דורשים רק שנים, קשה איך נדע איזה שנים נדרוש ממנו, שיש שני מילים מניותרים של “בכור,” ואחד נצרך. אם כן, לא נדע איזה נצרך.
23. מתוס’ משמע שהראשון יהיה ה”בכור” שאינו מיותר. לכאורה, זה מפני שבשעת כתיבתו, לא נדע שקאי על בכור אילו לא נכתב. אז, נצרך. גי”ל שאף לאחר מכן, לא נוכל להבין שקאי על בכור ממש”כ בכור אחר כך. אז, בוודאי הוא מיותר. ותחשב על זה.
24. ו.
25. מז	ניחא ליישב- יש לדון למה ניחא ליישב לזה, שהרי מוכרח שאינו כאותו מאן דאמר. אם כן, קשה למה רוצה ליישב כמותו.
26. מח	וגמל נשנה מפני שסועה- מעניין, שהיה אפשר לומר שכיון שאם יש לדרוש דורשים, נדרש כרבי שמעון. ויש לדון, שאולי אם לא מסתבר לדרוש, שהדין מחודש, אז אין דורשים. ויש לציין לגמרא סוטה (ג.) במחלקת רבי ישמעאל ורבי עקיבא. אבל, לאידך גיסא, עיין בקושיית תוס’ שם.[fn:2]
27. מט	דומיא דמורה- ואם תאמר הרי הוקש. ויש לומר שהוקש לא שווה לזה שמשמע שהוא דומה. יש לדון אם דומה ר"ל שהוא דומה בחשיבות או שמה שצריך לעשות הוא דומה. ותחשב.
28. יש לדון למה כל כך פשוט שדרשה מ"את" אומר שהוא דומה, יותר מהיקש. ותחשב.
29. ו:
30. נ	ולא כתיב הטמא- אין זה מוכיח, לכאורה, ממה דורשים מה, אלא איזה הוא הדרשה שהיינו דורשים אילו רק כ’ טמאה, שאפשר שכיון שכ’ שניהם, יותר מסתבר שנדרוש זה מן הה"א המיותר. ויש לדון. גם יש לדון אם זה יאמר שנדרש מן הה"א, שאולי כשאומרים שנדרש ממנו, רצה לומר שבלתי זה, לא היה ידוע, אבל כיון שכתיב זה, ידוע. ותחשב על זה.
31. נא	דקים ליה- עדיין צריך ביאור, שאם אינו ציר ממש שם, אלא קצת פחות, היה אפשר להקל בדרבנן ולהחמיר בדאורייתא. אולי זה חלק מת’ של תוס’, והוא שקים ליה שכעין זה, אילו היה אסור בדאורייתא, היו רבנן גוזרים עליו. יש לדון מהיכי תיתי (שלכאורה, זה היה ק’ תוס’). ויש לומר שיש סברה שדבר מצוי כזה, אם הוא אסור בדאו’, יגזרו בו רבנן. ותחשב. וצריך ביאור.
32. ז.
33. נב	ופליג- יש לדון מה אומר תוס’. קצת ממשע שמקשה למה נניח שהוא רק חצי שיטתו, ואומר שהוא מפני שכן צריך לומר למסקנת גמרא. ויש לדון, שלכאורה אין זה כל כך דחוק, שהרי כבר מצאנו מחלקת על נקודה זה. אז, אין בוראים עכשיו שיטה חדשה שנאמר שדחוק הוא לעשות כן, אלא מצדדים שלא סוברים כרבי שמעון במחלקת אחר. ותו"ת.
34. נג	שאור- יש לציין לר"ן בסוף נדרים שכ’ שסתם חכמים שחולקים על רבי אליעזר הוא רבי יהושע.
35. ז:
36. נד	והני נמי- צריך ביאור מה מפרש רש"י, שאם כן, כן יהיה אף במי רגלים של סוס. אולי אין הכי נמי, והשואל לא הכיר כלל בצד זה. ותחשב. מלשון רש"י (“דדמו לחלב") קצת משמע שדורשים שצריך להיות ממין של דבר טמא לאכול, כמו חלבו, שאסור לאכול. אז, יש לומרש רק זה, שנעכר, נחשב להיות ממין טמא.
37. נה	ואסירן- פירש שהאיסור יהיה אבר מן החי. זה בוודאי נראה מן הגמרא, אבל קצת קשה, שבדר”כ, אבר צריך להיות בתוכו עצם (כן הוא למקצת דינים בחולין). אולי צריך לומר שאינו כאן לדין זה. גי”ל שאינו בכלל איסור אבר מן החי, אלא בשר מן החי. לא נראה כן מרש”י. יש לדון אם נקראים שני איסורים חלוקים (שאולי רק מצאנו נפק”מ לענין טומאה, ולא לענין איסור). ותחשב.
38. נו	עור הבא- יש לדון אם מכוון להביא ראיה לדין פירשא או להוכיח שזה פירשא. אם נאמר כצד שני, צריך לומר שזהו עור הבא כנגד פנים. לא משמע כל כך מרש"י, שרש"י כ׳ שהוא שליא. אולי דן ממה בא שליא.
39. ועיין בתוד”ה עור הבא ובהגהות וציונים (מהרש”א וש”מ). שו”ר שכ’ כן בפירוש לקמן.
40. נז	מאי לאו- יש לדון מה זה אומר ש”בא משניהם.” אפשר שרק ר"ל שיכול לבוא מזה ואפשר לבוא מזה. אז, הוא ספק, וספק טומאה טהור. לא נראה, ראשון מלשונו, ועוד שלא בכל מקום ספק טומאה טהור. אז, משמע שהוא חלק משניהם, ורק צריך להיות חלק מאחד מהם להיות נחשב חי. אין זה כל כך קשה, שהרי היו אחד  (אולי) עד כאן, ואז קל להיות דבר שהוא חלק משניהם. עדיין צריך לומר שיש חילוק בין זה לשאר אבריה, שלא נראה שהם טהורים אם הוא חי. לכאורה, החילוק הוא שזה מחובר לוולד (אולי מחובר לו עכשיו, ואולי רק היה מחובר לפני זמן).
41. נח	יש להעיר על תוס׳ שלא משמע כן מלשון ברייתא. נראה שמפרש קאי על אחד, אבל מרבה כל ציורים של אותו אחד, ואף אם אחר מת. ותחשב. נראה שרש"י דחה ראייתו, וסבר שלא משמע כן הלשון,ולכן לא צדד ר”ח לןומר כן. ותו"ת.
42. ח.
43. נט	אם מבהמה- ואם תאמר אם כן, למה לא אומר גמרא, “אם מחיה... מבהמה.” ויש לומר שמניחים שחיה ר"ל פחותח שבחיות. קשה, אז, איך היה אפשר לו רק לומר חיב להשמיע כן. ותחשב.
44. ס	באילן תות- כיון שגדל על אילן ועל עץ, ק"ק ל"ל אומר בורא פרי העץ. אולי הקרקע נחשב יותר סיבה מן העץ. קשה מה זה שייך לאם גזעו מחליף או לא. אולי צריך יחס לפרי, לא רק במה שעשה אותו, אלא שעומד לעשות דבר שדומה לו. זה אי אפשר אם אין גזעו מחליף. דחוק מאד.
45. סא	מניחים בכל סוגיה זה (בין בתוס’ כאן, בין ברשי שגם הוא תולה זה במה היה עץ הדעת) שעץ ואילן הוא דבר שווה. ותחשב על זה.
46. ח:
47. סב	לכמה מיעבר- עיין במה שפירש רש"י. מעניין, ששאר הבהמות שדנו בהם לפני כן דן בעיבור שלהם. יש לדון, שאולי כן כוון רש"י, ולא רק כמה זמן שוהה במעיו כיון שכבר נגמר. ועיין בגמרא שמבואר שהוא שבעה ימים משעת ביאה.
* Footnotes
[fn:1] בכל זה, אני מניח שמה שקורה הוא שיש קדושה, שהרי מהני בפני עצמו, ושוב חייב לתת. ותחשב. לא צריך לומר ששניהם מיוחסים, שאפשר לומר שיש שני דברים חלוקים, וסיבה שייתן הוא מפני שה’ רצה בטובת כוהן. אם כן, ק"ק למה צריך לתת את המקודשת לו. ותו"ת.
[fn:2] באמת, קצת תמיהה הוא ל"ל מביא שם גמרא שלנו לראיה, שלא היה צריך לדמות כמו שאומר שם. ותו"ת.
