** גמ גמ’
’ (פא:) כ’ שחול’ ב"ש וב"ה בלן עם אשתו שגרש בפונדקי.
מפ’ שחול’ באם מניחים שאדם עושה ביאתו ביאת זנות. להל’, אא"ע ביאתו ב"ז.
** ריב"ש
(ו) כ’ מעשה באשה מאראנו שרצתה לישא לאחד, אבל אנוס אחד (מאראנו) כפה אותה לישא לו. נתעברה, והוא יצא ממנה, ושאלה אם צ’ גט. כ’ שק’ שעשה ע"י גוי אינו ק’, שרק נתן כומר טבעות לאיש ואשה, ואי"ז ק’. יש חשש בביאה, שאא"ע ביאתו ב"ז.
** גאונים רמב"ם
כ’ שצ’ עדים, וצ’ שבעל יראה עדים, שרק אז יכוון לק’ בביאה. מביא שיטת
שכ’ שבכ"ז אאעבב"ז.
חלק וכ’ שאא"ע רק אם כבר יש לו שייכות לה.
אעפ"כ, כיון שרואים שרצה בעל להיות נשוי לה, יש להניח שכוון לק’. דחה שלא כוונו לק’, אלא לק’ של גוי.
גם היה אפשר לומר שצ’ גט מדין "בעולת בעל" לב"נ. דחה שזה רק אם ב"נ בא על אשת ב"נ, והוא חשש מדרבנן. כיון שהוא רק מדרבנן, רק גזרו על גוי.
** ראב"ד
כ’ שרק כשיש חז’ כשרות, מניחים שאא"ע, אבל כאן, אין חז"ק. כיון שהיה מאראנו, ויצא ממנה, ועוד שבא על נדה, רואים שלא היה איש טוב.[fn:1]
כיון שאין עדים שאומרים שבא עליה, אף שידוע שנשא אותה, אין קידושין.
לכן, מתיר אותה.
** רא"ש קרב"נ רמב"ם מג"מ רש"ל ראב"ד
סובר כרמב"ם.
מק’ שרא"ש כ’ שנושא שפחה מניחים ששחרר אותה. רא"ש מביא ראיה לשיטתו ממה שגמ’ אומר שנותן שט"ק לשפחה שחררה, ש"לא עביד איסורא.”
לא סותר א"ע, אלא כ’ שמיש בא על שפחה לא שחרר אותה.
דוחה ששם קדשה בשטר. אז, גלה שרוצה לק’. צ"ל ששחרר. לכאו’, לת’ לסתירה לרא"ש, י"ל שאיסור ביאת שפחה יותר חמור.
כ’ שקודם מ"ת, אדם היה משנה עם אשה, וזה נקראת קדשה וזונה. משנתנה תורה, נאסרה קדשה. א"כ, רמב"ם סובר שאיסור פנוי ושפחה שווים, ששניהם דאו’.
חול’ שאיסור קדשה הוא רק אם מפקרת עצמה לכמה אנשים. רא"ש, לכאו’, סובר כראב"ד. אם כן, חול’ לשיטתם. בציור של רמב"ם, אז, י"ל שלא היה עדים, ובין כך ובין כך היה ביאת זנות. אז, צריך לומר שלא קפיד על איסורים, ולא נניח ששחרר אותה. רא"ש, שסובר שלא אסור לזנות, סובר שיש ראיה, שאין רואים כלום ממה שזנתה.
** ר"מ רב האנקין
חולקים להל’ גם במי שנשא אשה גבי הריפורמי"ם.
ו
כ’ שכוונה לק’ הוא רק כוונה להיות איש ואשה. ק’ מריב"ש. ר"מ כ’ שריב"ש מיירי בשלא ידעו שצ’ קידושין. אז, לא כוון לכלום כשבעל. כמוכ"כ שמק’ ע"ד חוקות גויים, ולא כוונו לק’ דאו’, ויש חילוקים גדולים, והוה קידושין לזמן. זה כעין סברת ריב"ש. הק’ רב האנקין שזה מתנה עמש"כ בתורה. גם דוחה סברה ראשונה.
כ’ שאף שהוא כוון לשם ק’, היא לא כוונה לשם ק’. מדייק ממה שהז’ כל המעשה שלא היתה רוצה להיות נשאת. היא רק רצה לישא כדת תורה, אבל הוא רק רצה לישא כמו קידושין של ר"מ. כיון שלא כוונו לדבר אחד, לא יכול קידושין לחול. אז, צריך ריב"ש לדון מה היה כוונתו.
נמצא, לכאורה, נפק"מ לדינא.
* Footnotes
[fn:1] יש לדון בזה, שגם נוכיח מזה שלא רצה להינשא לה. אולי אין הכי נמי. ותחשב.
