** משנה
כ’ שאם כ’ גט על יד עבד או קרן פרה, כשר אם נתן עבד או פרה. מדייק גמ’ שא"א לכרות יד או קרן. אסור לחבל בעבד, אבל קשה ל"ל כורת קרן פרה. ת’ שא"כ מחוסר קציצה ונתינה, ולומ’ מקרא שפסול.
קשה למה מחוסר קציצה, שלא צ’ לקוץ, שיכול לתת עבד.
** רמב"ן רב האי גאון פנ"י תורת [fn:4]גיטין
מביא
שמיירי כשכוון לקוץ אותו בשעת כתיבה. אז, בשעת כתיבה, היה חסר מהש היה רוצה לתת.[fn:1] אם מקנה לה הקרן, ולא הפרה, יש ראשונים שאומרים שאין הגט כשר. אם כן, הקציצה מוכרח.[fn:2]
כ’ שאינו בעיה בכתיבה, אלא שצריך להיות שחפץ לא נשתנה בין כ’ לנתינה.[fn:3]
כ’ שאף אם חתך אחר נתינה, פסול. צריך לומר שגט בשעת נתינה הוא עומד לנתינה, ולא לקוץ אחר כן.
** רשב"ם יש ר"ן אבי עזרי ר"ד פאברסקי
כ’ שקציצה ר"ל עוקר דבר מגידולו.
שכ’ שכל קציצה כן. אפשר לבאר ברשב"ם שצריך מעשה חשוב.
מבאר שתורה רק ממעט מה שא"א לתת בלי אותו קציצה. בעל חי דומה למחובר.
כ’ שתלוי כמה הגט נשנה. אם קוצץ מקרקע, הוא שינוי חשוב כיון שמכשיר. בבעל חי, חשוב הוא מטעם אחר. לא משמע כן מלשונו.
כ’ שמח’ רשב"ם וחול’ הוא למה נח’ שינוי, אם הוא מפני ששינה אותו מחי למת או מפני שנשתנה שמו ממה שהיה מחובר לו למה שהוא עכשיו.
** גמ’ קרבן נתנאל גרש ירכים תורת גיטין
כ’ שאם כ’ על חרס של עציץ נקוב, כשר. רש"י כ’ שאינו מחוסר קציצה, שלא חוששים שישבר חרס. משמע כחול’ על רשב"ם.[fn:5] ק’ שרש"י אומר לקמן ש"הוא קציצה במחובר.” קשה.
כ’ שרש"י כרשב"ם, אלא ששבירת החרס הוא גז’ אגב חתיכה ממחובר.
כ’ שבטל למה שהוא מחובר.
כ’ שרמב"ן כ’ שאם כ’ על דבר ששיורו חשוב, א"צ דעת, שפשוט שלא יתן כולו. אולי רש"י סבר כן. חרס הוא שיורו ניכר.[fn:6] במחובר, צריך לתלוש אותו. אז, צריך קציצה מזה.
* Footnotes
[fn:1] ק"ק ל"ל אומר שמה שנתן אי אפשר לתת בלי קציצה.
[fn:2] אין צריך זה, שהיה אפשר להוקים אוות ברוצה לתת כשאינו מחובר.
[fn:3] דרשת קרא לא נראה כן.
[fn:4] לא נראה כן, שהרי כשאומרים שמחוסר, דורשים מקרא שאומר מה שצריך כדי לגרש, ולא מה שעושה.
[fn:5] היה אפשר לחלק בין מחובר לקרקע למחובר לדבר אחר. עדיין אין זה כל כך נשמע מהגדרה שאמר רד"פ. ראיה שיביא משה הוא מוכיח נגד זה. לא אפשר שהרי החרס כן גם כן.
[fn:6] אז, אין צריך שרש"י אומר שלא חוששים שיעשה כן, אלא שממילא אם היה עושה כן, לא היה בעיה. אולי אין הכי נמי.
