ר"א סובר שיכול אדם לגרש את אשתו חוץ מאיש מיוחד. אם נושא אחד, יכול לישא אותו איש אחר כן. מקשה איך מצאנו שזה אוסר וזה מתיר. מק' גמ' מהפרת בעל. מת' שנודרת על דעת בעל נודרת, אבל אין איש מתיר.
** קובץ הערות
משמע שזה תנאי. אם כן, יעקור למפרע, כיון שע"מ חל למפרע. גמ' אומר שבעל מהני מכאן ולהבא.
כ' שהוא נדר לזמן. מק' שאז לא יהני בנזירות, שאינו פחות משלשים יום. י"ל שכ' בתורה, ומניחים שתורה אומר אף זה, ומסתמא הוא מפני לא פלוג. גם ק' למה תורה כ' שצ' לשון הפרה וכדומה.
** תוס'
מק' בנדה למה צ' שתורה יפרש שבעל מפיר. ת' שצ' לדין קיום. גם ת' שנודרת על דעתו כיון שהוא יכול להפר.
** ר"ן ק"ש
מביא שי"א שיכול אדם לנדור על דעת חברו, ודוחה שגזה"כ הוא, אבל תורה זכה לבעל מחמת זה. אז, חולק על תוס', ואומר שהוא רק באישתה. קשה, אז, איך מתרץ גמ' בזה לקידושין דרבנן.
מבאר שגה"כ חל על אישות דרבנן, והוא כל מי שסובר שאיש זה אישתה.[fn:1]
** ברכת אברהם
לר"ן, קשה למה אין מאמר של ר"פ דרישת טעם הקרא. ת'
שלומדים מטעם קרא כדי להוסיף, כמו במ"מ, ורק לא יכולים למעט.
** ברכת אברהם
לר"ן, קשה מהו תירוץ גמרא בגיטין.[fn:2]
ת' שכוחו בא מכוחה, ולכן מהני רק אם לדעתו נעשה.
* Footnotes
[fn:1] אף זה צריך פירוש, שלכאורה, לא חושב שהוא אישתה, אלא נודר על דעתו כיון שנותן לו מזון. ותחשב.
[fn:2] אין זה כל כך קשה, שיש סיבה שתורה יזכה לו, והוא שנודרת על דעתו.
