** משנה רש"י תוס’
(כד) כ’ שאשה עצמה מביאה את גטה ובלבד שהיא אומרת ב"נ. מק’ גמ’ שכבר קבלה גט. גמ’ כ’ שהיא שליח לקבלה עד שבאתה שם. מק’ שלא חזרה שליחות אצל בעל.
מפרש שצ"ל שליח עד שתחזור לבעל. כאן, כבר נעשה בעל מעשה.
כ’ שכבר נעשה שליח לעצמה.
יש להביא קצת ראיה שיש מושג כעין מש"כ תוס’ מגמ’ (סג) גבי שליח שנעשה שליח להולכה וקבלה. אפשר שרש"י סובר ששני הפסולים (אם נעשה שליח או בעל מעשה) הם פסול אחד, והוא שהוא אחר בתוך הציור כשהוא כבר שליח להולכה. צריך ביאור, עדיין, ל"ל באר רש"י כתוס’ גבי אשה.
לזה, אפשר שרש"י ותוס’ לא חולקים בדין, אלא רק נוקטים פסול חלוק בדף כד. עיין בלשון תוס’ סג, שמשמע שיש בעיה אם נעשה שליח אף לענין שום דבר אחר.[fn:1] גם ממה שאומר, “קונ’ לא פ’ כן" בכד, לא משמע כן.
אפשר שרש"י פי’ שיש פסול אחד של בע"ד, ופסול בסג הוא מחמת ששלוחו כמותו. גם בזה, היה אפשר לומר שתוס’ לא חולק, אלא שיש שני הבעיות שכ’ לעיל.
יש להעיר שלכאורה, יש בעיה בכל שליח להולכה, כיון שהוא שליח, וגם הוא בעל מעשה (של מוליך).
יש לדון למה תוס’ יחלוק על רש"י. אולי הוא מוכיח כן ממה שאומר גמרא לקמן, שמת’ שאומרת שעושה אחר לקבל גט. אם כן, היא בעל מעשה שם גם כן. אפשר לחלק ששם יש אחר שעושה שליחות לה.[fn:2]
בביאור למה פסול אם היא שליח לשני בני אדם, אפשר שהולכה וקבלה סותרים זא"ז, אי אפשר להיות שליח לשניהם. אם כן, הוא רק בשליח לקבלה והולכה, אבל תוס’ בסג משמע שהוא אף בשליח לשני דברים שאינם שייכים זל"ז. באמת, היה אפשר להק’ ממשנה שאומ’ שיכול שליח להיות שליח לשני בני אדם. אז, צריך לומר שתוס’ לא פוסל כל שליח לשני דברים.[fn:3]
גם אפשר שתוס’ לא סובר כרש"י מחמת סברה שלו, והוא שכיון שדין זה הוא מחודש, לא נניח שהוא במקום אחר ממקום שמצאנו אותו. כיון שאפשר שהוא רק בשליחות, שאפשר כצד שכ’ לעיל, לא נלמד לומר כרש"י.
** אבני מלואים תוס’
כ’ שרש"י לא פ’ כתוס’ מח’ ק’ רשב"א, והוא שגמ’ מניח בפשטות שיש בעיה, אבל בסג מסופק. אז, יש לומר שרש"י סובר שכאן בבע"מ, וכאן בשליח. הסברה לומר שהוא רק בבעל מעשה הוא אולי שאולי צריך שני דברים שעושה שהם חשובים, אבל לא לשליח ושליח, אלא לבעל מעשה (אולי מסופק אם שליח כבעל מעשה או אם צריך בעל מעשה). אפשר שמסופק אם ענין בעל מעשה הוא אם עושה החלות או שלו הוא החלות.
יבאר כרשב"א שכ’ שמה שגמ’ מסופק הוא אם צ"ל חוזר בשעת מינוי או בסוף.
** ריטב"א
כ’ (ומביא גי’ אחרת לסמך לזה) שהבעיה הוא שבטל שליחותו, ואז לא נותנו. לכאורה, הוא מפני שאמר לשון, “עד דמטית….” ק"ק שההוה אמינא לפני זה בגמרא יש בו בעיה של טלי גטך, ואז צריך לומר שהיה אותו קושיה שני פעמים, ושינה לשון ת’. גם ק’ מהו הת’. גם ק’, מהו הבעיה בסג. לכאורה, צריך לומר שמה שנעשה שליח או בעל מעשה מנתק שליחותו, ואז לא בא מן השליח, שבטל שלחותו.[fn:4] (עדיין ק’ ראשונה ק"ק).
* Footnotes
[fn:1] לא נראה שהוא נכון בזה, שנראה שאין זה הדין.
[fn:2] יש לדון, שכאן כ’, על כל פנים בתוס’, שהיא שליח לעצמה. ויש לדון, שאולי רש"י אינו מודה לזה. באמת, לא הבנתי מה אומר שהיא שליח לעצמה, שאין לזה כל כך הבנה.
[fn:3] יש לדון, שאולי צריך להיות שני דברים חלוקים.
[fn:4] כיון שהגענו לזה, היה נראה לומר שלא חולק ריטב"א על שאר ראשונים, שהם מבארים למה אין שליחות, וריטב"א מבאר למה צריך שליחות.
