** גמרא
אומר שאילו לא אמר ר"י שקנין פירות כקנין הגוף, לא מצא ידיו ורגליו בבית מדרש, שאומר שאין ברירה, ואחים שחלקו לקוחות. אם אינו כקנין הגוף, אין מי שיביא ביכורים חוץ מחד בן חד מימות יהושע בן נון, שלא יכולים להודות לה' על הארץ שנתן לנו.
** תוס' גמ'
הק'
ש
פוסק כר"ל, שקנין פירות לאו כקנין הגוף, ושאחים שחלקו לקוחות הם. ת' שהל' כר"ל רק בכותב נכסיו לבניו, שאבא לגבי ברא מוחל[fn:1], אבל לא בירושה. מז' שרבא אומר שקרא ומתניתא מסייע לר"ל, והוא מי שפוסק שאחים שחלקו לקוחות הם. מבאר שאולי אף שמצא קרא ומתניתא כר"ל, לא פסק כן, או שאף שהם לקוחות, לא מחזירים זל"ז ביובל, כיון שיורשים.
יש להק' על ת' ראשון של תוס', שנ' שגמ' משמע שאומר שקנין פירות לאו כקנין הגוף בבעל בנכסי אשתו.
** רמב"ם
פסק שקנין פירות לאו כקנין הגוף דמי בכל דין. גם פסק שאחרים שחלקו לקוחות הם ומחזירים זל"ז ביובל. אז, ק' גמ' עדיין קשה עליו.
** לח"ם
פ' שאף שמחזירים, מניחים שנותנים קנין פירות לאחיו כדי לקיים מצוות ביכורים. מקורו הוא מפסק של גמ' כשני הדינים שאמר רבא. לכאורה, כוונתו לומר שרבא סובר כן, ורבא חולק על מש"א גמ' שלא היה יכול ר"י למצוא ידיו ורגליו בבית מדרש. פסק כרבא.
** רש"י תוס'
חלקו
ו
בביאור "אחים שחלקן לקוחות." רש"י מבאר שהם שותפים בכל הירושה. אז, בוודאי כל אחד נוטל חלק של חבירו במקצת, שבכל דבר יש לכל אחד שיעור. תוס' כ' שלא יודעים איזה חלק הוא למי, אבל לא שותפים הם בכל חלק וחלק, אלא היה חלק לזה וחלק לזה. אז, לקוחות הם ספק לקוחות. מח' ספק דאו' לחומרא, מחזירים[fn:2] ומביאים וקוראים. לכאורה, צריך לומר שאומר כן ברבא, שאל"ה קשה איך נפרש מה שאומר שלא נמצא ידינו ורגלינו בב"מ.
** גמ' רשב"ם תוס'
אומר שאין קוראים מקרא ביכורים מספק, שנראה כשקר או שמא לא יפריש תו"מ. י"ל שסובר שלא יקרא מח' חיוב מעשרות, וכאן, שחייב להביא בוודאי, אין בעיה. חלקו
ו
אם יש מצוות ביכורים בוודאי כשיש קנין פירות או לא. שאג"א מניח כרשב"ם.[fn:3]
לכאו', תוס' לא אומר כן כשיטתו בב"ב. גי"ל שאולי סבר כטעם אחר של גמ' שם. גי"ל שלא נחשב מצא ידיו ורגליו בבית מדרש כיון שא"א לקיים מצוותו בתורת וודאי.[fn:4]
** רמב"ם
כ' שישראל וגוי שקנו דבר, טבל וחולין מעורבים בכל קלח. א"כ, נמצא כרשי, ולא כתוס'. וק'.
** טור סמ"ג
כ' שכ' נכסיו לבנו או לאחר, קנין פירות לאו כקנין הגוף. צריך לומר נגד ת' ראשון של תוס'.
שהלכה ביבמות כר"ל שהמוכר שדהו לפירות…, אף ששם לא אמר כן בפירוש, אלא אמר רק באב שנתן לבנו.
* Footnotes
[fn:1] יש לדון, שאין כל כך כמה נפק"מ לקנין הגוף.
[fn:2] יש לדון ל"ל אומרים שמוציא מחברו עליו הראיה.
[fn:3] העיר אחד שם שאם כן נוכל לומר שגמרא שלנו לא תירץ כן כיון שסבר שהבעיה הוא שנראה כשקר.
[fn:4] לא נראה כן, שלכאורה מה שאי אפשר להיות כן הוא שלא רוצים שתורה יאמר דין לבטלה. ותחשב. אולי רק אם ספק דאורייתא לחומרא מדאורייתא יש לומר כן. ק"ק שרמבם סובר שהוא מדרבנן.
