** משנה משנה ראשונים רש"י רי"ף
אומר שזכין ש"ש לשחרר עבד.
לקמן אומר שאם מזכה ש"ש לעבד, ומת קודם שבא ליד עבד, לא ניתן לעבד לאח"מ. משמע שחל רק כשבא לידו.
כ' שלא גו', "תן," והוא שנתן לשליח לזכות, אלא "תנו," שאמר לתת לשליח, ואז לא זיכה.
(וכ"כ
) כ' שזכה עד שא"א לחזור, אבל לא חל עד שבא לידו. לא חל לאח"מ, כיון ששל יורשים הוא. ק':
1. רש"י במק"א כ' שחל מיד כשזכה.
2. קשה ל"ל נאמר זכים כאן כמו בכ"מ.
3. רא"ש מקשה ל"ל יכול לחזור, כיון שלא קנה א"ע להיות משוחרר.
4. קצות מעורר שרשי שכ' שא"א לשחרר כיון שאינו שלו, ולא רק כ' שאין שליחות. (מזה מוכיח שסובר כרמבם שיש שליחות לאח"מ.) קשה, שרש"י כ' במק"א ששליחות בטל לאח"מ.
5. גמ' כ' ששולח ממון לבע"ח לא יכול לחזור, אבל חייב באחריות. נמצא שיכו"ל שלא יכול לחזור בו, אף שעדיין שלו הוא. רא"ש דוחה שזה מפני שחוב הוא שיהיה ממון לבע"ח, שאז אחריותו עליו. עדיין קשה ל"ל יכול לח' בו.
** פנ"י
כ' לת' לשני: קנין ש"ש חוב לעבד, שמס' נשוי לשפחה, ויבעל באיסור כיון שלא שמע[fn:1]. דחוק לומר אוקמתא כזה.
** אחרונים ר"א רמב"ם ר"א
מדיי' שרא"ש מק' כיון שזכייה מטע"ש. לכאו', אם אין זמט"ש, ק' איך מקיים, "ונתן בידה."[fn:2]
מביא
בשליח להבאה (שיחול גט כשבא ליד עבד). כ' ששליח קונה גט, ומביא לה. אבל, נתינת בעל רק צ"ל לקנין, אבל לא לידה. אז, נתקיים מה שצ' בעל לעשות; רק חסר נתינה בידה, וכשנעשה, חל.[fn:3] כמו"כ י"ל כאן. זה ית' ראשון (שם שליח הוא), ושני (צ' קיום בידה), שלישי (יש קנין, וא"א לחזור מאותו קנין), ורביעי (לא צ' עוד שליחות). ראית רי"ף צ"ב, שאין קונה שם.
מפ' שנתינת ממון לא לעולם מהני לחוב, אלא צריך לשלם לחוב. חוב הוא לבע"ח להיות משתלם עכשיו, ואז לא חל הקנין מתורת חוב, שלא נדחה החוב שלא לרצונו ע"י זכים.[fn:4]
** רש"י רש"י
כ' בפ' שזכייה מטע"ש.
בקידושין קצת משמע שיש לו צד שזכייה האינו מטע"ש. אולי סובר ששניהם אפשרים להיות, וכ' לפעמים וכזה ולפעמים כזה. אז, יש ליישב הסתירה ברש"י.
* Footnotes
[fn:1] מחודש, שזה אונס.
[fn:2] לא כל כך פשוט שזה יהיה מתורץ אם הוא שליח. גם יש לדון למה כל כך פשוט לומר כן, שנראה שיש צד לומר שהקנין הוא נתינת ביד מי שעושה מעשה קנין. ותחשב.
[fn:3] דורש את הקרא להיות אומר שני דברים: ונתן- שבעל יתן, ובידה- שיימצא בידה. כמובן, צ"ב למה.
[fn:4] צריך ביאור מה אומר, שלכאורה, לא ניתן לו קנין אחר חוץ מתשלומים. גם עדיין צריך ביאור מהו הראיה; דחיית רא"ש מובן, אבל לא כ"ז.
