** קצות אחרונים קה"י רש"י מגיה
דן בגדרי באים כאחד. יוצא מדבריו שממה שחל גט בע"כ, רואים שא"צ קנין הגט, אלא נתינתו. לכן, מפ’ שכ’ גט על א"ה.
מק’ מפסול נייר שלי. מק’ גם מלשון רש"י שם. אז, מפ’ שנתינה גורם קנין.
כ’ שהבעיה שם הוא שקנין בעל מעכב, ואינו כריתות.
(עה) לא משמע כן, ש"לא יהב לה ולא מידי, ורחמנא אמר ונתן בידה.” לא משמע כקה"י.
כ’ שצ’ נתינה שראויה לקנין.[fn:1] זה גדר מוזר לנתינה.
** גמ’ תוס’ שאנץ
יש סיבות לחשוב שצ’ קנין הגט.
דן בזכייה לקטנים.
מק’ ש[אם אין קונות מדאו’, ]ק’ איך נתג’. ת’ שדע"מ מהני מדאו’. לכאו’, צ"ל שאשה צ’ שום דעת, שמק’ ממה שאינה בר דעת.[fn:2]
** רש"י גמ’
בכתובות כ’ שאין קנין יד פחות מג"ט. חול’ תוס’, כיון שכ’ יד בגט. משמע שיש קנין בגט.
ג"כ בכ"מ לשונות של קנין.[fn:3] כמו"כ, גמ’ שמק’ בתחלת הזורק ש"מה שקנתה אשה קנה בעלה" קשה לקצות. כמו"כ גמ’ מנסה להביא ראיה מזה לענין כליו של לוקח ברשות מוכר. (לכאו’, חצר מהני בע"כ ג"כ, ואז צ"ל שרק צ’ נתינה. עוד, נל’ מיד.) אז, נ’ שקונה גט.[fn:4]
** שט"מ
מבאר רש"י בכתובות, וכ’ שא"א ללמוד מגט. יש שכ’ שסובר שהוא נתינה. ק’ ממש"כ. באמת, עו"ק לל"א שאין לומ’ ממון מאיסור. באמת, עיין ברש"י בב"מ גבי חצר מתורת שליחות; וצריך ביאור איך כל זה שייך לזה. לא נראה שכן אומר שט"מ, שכ’ שיש לו ראיות, אבל לא יפ’. אם ר"ל זה, הוא כמעט מפורש. ותו"ת.
* Footnotes
[fn:1] קשה איך זה מתרץ לשום אחד מן הקושיות. צריך לבאר מהו בגדר "ראוי.”
[fn:2] לא נראה לומר שמי שאינה בר דעת לא יכולה להיות לה קנין, שהרי רבנן עושים לה קנין. יש לדון, שאולי כל אלו לא קונים מדאו’. ותחשב.
[fn:3] הביא תוס’ רי"ד, אבל נראה לי שאותו לשון שהביא לא קאי על קנין גט, אלא על קנין אשה. וצריך לעיין.
[fn:4] לכאורה, היה קל לומר שנתינה ר"ל כל סיבות קנין חוץ מדעת אשה. אולי זהו מה שאומר ראוי. ודע שזה יתרץ למה אין בעיה בדבר שאסור בהנאה, שלכאורה הבעיה הוא רק שלא נעשה כל כך שלה, אבל יש עדיין סיבות. יש לדון, שאולי זה אף עושה שאין לו כוח לתת. ותחשב.
