** גמ רש"י חידושי הרי"ם
’ גיטין דן בפרוזבול. שמיטה משמט חוב- אחר שמיטה, אין גובים. כיון שבני אדם לא לוו, תקנו פרוזבול כדי שלא יהיה משמט, ואף אם שמיטה דאו’.
פ’ "שאתם [בית דין] נוגשים, ולא אני, ויש כוח בידם [של הפקר בית דין הפקר].” נמצא שמפרש שנגישת בית דין אינו בכלל נגישת לא יגוש. צריכים לבאר למה צריך, אז, הפקר ב"ד הפקר, שכבר באר שאין איסור לא יגוש.
שת’ שיש שני דינים: איסור לגוש, ודין השמטה. רש"י מבאר הראשון כשאומר שאינו בכלל לא יגוש, והשני כשאומר שהפקר ב"ד הפקר. צריך ביאור למה יהיה לא יגוש כלל, שלכאורה עושים חוב חדש. צריך לומר שלא עושים חוב חדש, אלא מניחים את הישן. אפשר שלבית דין יש אותו כוח לעשות שלא נשמט. אפשר שאולי ב"ד רק לא יכולים ללכת נגד תורה אם נראה שהוא נגד התורה; כאן, נראה כעשיית חוב חדש. עדיין צריך ביאור ל"ל יעשו חוב חדש, אז.
** רש"י
בכתובות לא משמע כן, שכ’ שהוא לא נוגש כלום, אלא בית דין תובע, והפקרם הפקר.
** תוס’ ראשונים ריטב"א
צריך לבאר מה קורה כשאדם מוסר שטרותיו לבית דין. לכאורה, הוא הרשאה.
כ’ שהרשאה מהני בתורת שליחות. א"כ, עדיין יהיה לא יגוש כאן. לכאורה, צריך לומר, לרש"י, כ
אחרים, שאומרים שמקנה את החוב. קשה, אז, למה אין איסור לא יגוש לבית דין. אפשר שאסור רק על מי שהלוה, ולא על מי שקנה ממנו.
כ’ בפ’ נג"ז. אז, י"ל שב"ד יכולים לתבוע מדין הפקר ב"ד הפקר- שמגו שיכולים לעשות שהחוב שלהם ואז יהיה להם הכח לגוש, יש להם כבר הכוח לגוש. רש"י אומר, אז, שעל הגשה כזה אין איסור. עשיית פרוזבול הוא שאלת בית דין לתבוע לו, אבל לא עושה, אז, שום חלות.[fn:1]
** גמ’
יש לדון למה, עדיין, אין השמטת כספים. אפשר שמשמט רק במקום לא יגוש. כן נראה מ
בגיטין שאומ’ שאין שביעית משמט חוב ש"לא קרינן ביה לא יגוש.” יש לחלק ששם החוב הוא חוב ששאין עליו לא יגוש, אבל כאן, ההגשה הוא הגשה שאין עליו האיסור. לכאורה, יש להוכיח כן, שיש איסור על אחד שתובע, ואם נחשיב שאין עליו איסור, נמצא שמשמט לענין אחד ולא לענין אחר. במילים אחרים, כל חוב הוא כך, אלא שבדרך כלל, לא שייך מה שאין איסור לאחר, שהרי אין לו כוח.
** גמ’ ראשונים רש"י רש"י
כ’ ש"המחזיר חוב צריך לומר משמט אני. אם אמר לו אף על פי כן, יקבל הימנו. אמר רבה ותלי ליה עד דאמר הכי [אף על פי כן].”
מבארים שיכול לשהות עד שישלם.
מפרש שיכול לכוף אותו בידים לשלם הממון. קשה איך יכול לכוף אותו כיון שנשמט החוב.
מבאר שאין כאן משום לא יגוש, שלא בב"ד תובע לו, ולאו משום חוב. אם אין חוב, כמובן קשה איך יכול לכוף אותו.
** יראים
יש שמבארים על פי
שכ’ שאין השמטת כספים, אלא איסור לא יגוש וחיוב למחול את החוב. עדיין קשה לבאר כן ברש"י, שהרי מחל על החוב.
אפשר לומר שסובר רש"י כעין יראים, והוא שלא מוחל החוב, אלא עושה אותו חוב שאין בו חיוב לשלם (כמו שאומר גמרא בכ"מ). אולי מפני זה יכול לכוף אותו.[fn:2]
אז, יש לומר שכשנוטל עם כוח בית דין, לא צריך לומר דיברו שמשמט כך. אם כן, יכול ליטול בכוח בית דין.
** רש"י
מק’ איך חז"ל יוכלו לשמט שמיטה, ומפרש רש"י שאז חז"ל עשו שהוא גזלן. לכאורה, זה אי אפשר אם סובר כיראים. אז, אפשר לבאר שיש הפקעת מלך שאין חיוב.[fn:3][fn:4]
* Footnotes
[fn:1] יש לדון, אז, למה צריך לכתוב שום פרוזבול ולעשות שום דבר. ותו"ת. אולי לא רצו לבטל מצוות שמיטה בזה.
[fn:2] עדיין צריך ביאור למה יכול לכוף אותו; רק יכול לקחת את הממון בלי מעשה קנין. אם רק תפס הממון, אינו קשה, אבל מרש"י משמע שלא כך קרה. אז, יהיה מותר, לכאורה, רק מחמת עביד איניש דינא לנפשיה. אם כן, כאן שאינו לנפשיה, צריך ביאור.
[fn:3] עדיין, לכאורה, אי אפשר לומר לפי צד זה, שעדיין אינו גזלן, אלא רק עובר על איסור של לא יגוש.
[fn:4] צריך ביאור איך נגדיר חיוב זה, שאם הוא חיוב כל זמן שיש לא יגוש, יהיה כן כאן גם כן. אולי הוא רק כשאדם מגיש. ותחשב. מעניין, שאם כן, יהיה חיוב אלא אם כן עובר על איסור של לא יגוש. אם כן, יהיה הלווה חייב לשלם מפני עצמו, וזה בוודאי אינו נכון. אם נאמר שעדיין אין חיוב, צריך ביאור מה הועילו בתקנה של פרוסבול.
