** משנה לז:
כ’ שאם נשבה עבד ונפדה, אם נפדה לשם עבדות ישתעבד, ואם הוא לשם בן חורין, יצא. רבא מפרש שלאחר יאוש הוא, ואילו לשם עבדות ישתעבד לרבו שני, ולשם בן חורין, יצא. מק’ גמ’ ששבאי עצמו לא קונה, ואיך יקנה לרבו שני. מת’ גמ’, ומביא ראיה, שקונה למעש"י.
** רש"י רש"י פ"י
דנים מהו קנין שבאי.
משמע שהוא קנין של יאוש לגזלן. קשה, שאין קרקע נגזל, ועבדים הוקשו לקרקעות. (
בסוכה כ’ שבקרקע צריך ש"ר, והרי כאן אין ש"ר).
כ’ שר"ל הפקר, שכיון שעדיין ברשותו, יכול להפקיר. (מבאר שכיון שמיאש, מסתמא מפקיר.) (אין להק’ מ"וישב ממנו שבי" שמזכיר, שרש"י בחקת כ’ שקאי על שפחה. עיין בדברות משה, שכ’ שמסתמא לא ייאשו על שפחות, ואז אומר פשט אחר.)
** ר"ן אחרונים
כ’ שקונה בכיבוש. לא נח’ כיבוש עד שעת יאוש. ק’ למה אין כל גזלן נח’ כובש.
כ’ שכבוש הוא כשא"א לתבוע בב"ד.[fn:1]
** רשב"א
שקונה בכיבוש מלחמה, וצ"ל אחר יאוש, אבל אז היה חוזר לבעל ראשון, אף שכבוש כבר קנה. אז, כיון שמשוחרר, אינו עוד כיבוש.[fn:2] ואם תאמר איך מפקיע יאוש קנינו, כיון שאין קרקע נגזל. י"ל שכיון שנכבש יוצא מרשותו, ואז יאוש מועיל.
** רמ"ה
כ’ שאין קנין; הוא רק דינא דמלכותא דינא. ק"ק למה צ’ יאוש.[fn:3] א"כ, ק"ק למה צ’ מקורות אלו. אולי אילו לא היה אפשר לקנות, לא היה דינא דמלכותא דינא מהני. עדיין קשה שאר קושיות גמ’. בדר"כ דינא דמלכותא דינא הוא שמלך יכול לכוף לנו, שעבדי מלך אנו. רמ"ה דן בשני ציורים: ציור שמלך התיר, וציור שכבשו במלחמה. אין דינא דמלכותא דינא שייך כאן כל כך, אלא הוא שיש למלך רשות לקחת כשהוא כובש. אז, גמרא צריך ראיה לזה.
** ב"ח
כ’ שכשדורשים "וישב ממנו שבי" חוזר מקנין מעש"י (ולכן לא קשה מה שרק קונים מעש"י ואיך נטהרו[fn:4]).
* Footnotes
[fn:1] יש לציין לגמ’ בהניזקין גבי שלש גזרות.
[fn:2] מעניין שיכול קנין להיות חוזר ונער כך.
[fn:3] אולי כן הוא דין מלכות.
[fn:4] ויש לדון, שאולי רק ישראל קונה במעש"י; הענין הוא רק להראות שקונה בחזקה.
