** גמ’ רש"י מהרש"א תוס’ רע"א רי"ף ר’ הוטנר רא"ש
כ’
שאשה יכולה להיות שליח לקבלה, שיכולה לקבל, וכן איש להולכה. שואל אם יכולים להפך. מסיק שיכולים להפך.
מפ’ שמה שיכול משלח לעשות, יכול שליח לעשות.
הק’ שלשון גמ’ (“איתא בנפשיה") משמע שמה שיכול להיות שליח הוא מפני כוח שיש לשליח. (ע’ ב
, שכ’ פשט אחר; ע"ז לא ק’.)
ת’ שרש"י ר"ל ששאלת גמ’ היה אם צ"ל בענין קבלת גט או גירושין. גמ’ מת’ כצד שני.[fn:1]
רק כ’ דינים, ומביא מקור (אב מקבל, ואשה מלכת לעצמה). לא מבאר. רע"א מבאר למה צ’ כל אלו. ק"ק מהו מקור שיכול ב"ח לקבל לעבד. י"ל שאדם יכול לגזול ולמכור[fn:2][fn:3][fn:4]. צ"ל שאינו בפרשה עד שנמכר. לרי"ף, גמ’ מביא מה שמולכת לעצמה למקור. א"כ, שקו"ט ק"ק, ששואל ומשיב ממשנה.[fn:5]
אומר שאם אמר לאשה לקבל גט לעצמה, טל"ג הוא. ק’ ל"ל הק’ מ"ונתן בידה.”[fn:6] מהני גבי עבד, שאין טל"ג, ואין "ונתן בידה" (שאין "ונתן בידה" גבי אשה). א"כ, אין ב"ח צ"ל שליח.[fn:7] לת’ לק’ ראשונה, אמר שיכולה קטנה לקבל קדושין לעצמה.
פ’ שיכול קטן להיות שליח לטובתה. אז, איתא נפשיה כיון שהיא שליח שלו בזה, ואז רואים שיכול אב לקבל גט, שמקבל מכוחו.[fn:8]
* Footnotes
[fn:1] לא הבנתי איך מפרש מה שאומר רש"י. גם לא ראיתי לשון רש"י, ואז אולי אין זה קשה.
[fn:2] יש לדון, שאסור לגזול. אחר כך, אמר כעין זה. גם נראה שהוא מפני שגזלה עושה שהוא עבד, וזה משנה דבר בו. זה נחשב, אז, זמן של נתינת כוח. ותחשב מה זה אומר.
[fn:3] יש לדון, שזה גט שחרור של עבד עברי, ולא של עבד כנעני. אם כן, עדיין יהיה קשה איך יודעים שיכול בע"ח לקבל לכנעני.
[fn:4] יש להעיר שדין זה לא נוהג עוד בזמנינו.
[fn:5] איני ידוע למה הוא קשה, שמצאנו שקו"ט כזה בכ"מ, ששואל ומשיב ממשנה אחרת. יש לדון, שאולי רק מת’ מברייתא.
[fn:6] יש לדון, שאולי הוא אותו בעיה.
[fn:7] קשה, שעדיין יכול לזכות לו, ואז יכול להיות שליח לקבלה. אז, יהיה קשה.
[fn:8] לא הבנתי, שאם כן, נותן טעם, ואינו רק מקור; ואיני יודע מה אומר רי"ף ממש.
