* נב.
** תנאי -
עיין בביאור רש"י. יוצא שיש תלייה בין תנאי לטעות. יש לדון אם מה שתנאי עושה הוא שכל שכנגד התנאי נחשב טעות (זה לא מסתבר, שאם כן הרבה דיני תנאי קשים להבין) או שמה שעושה טעות הוא שיש אומדנא, שהוא תנאי. ותחשב.
* נו.
** כבר אכלה -
קושיית הגמ' לא מובן לי. רק יודעים שאומר שכיון שכבר אכלה אוכלת אם הסיבה שלא אכל היא מדרבנן. אבל, אם הוא מדאו', אולי לא תאכל.
* נז:
** חופה -
לא כל כך פשוט מסברה שאין חופה לבת שלש שנים. היה אפשר לצדד שיש חופה, שמה שחופה עושה, אולי, הוא שהיא עומדת לביאה, לא רק עכשיו, אלא אף אחרי כן. אז, אולי עושה שהיא עומדת לביאה שלאחר כמה שנים, כשהיא כבר גדלה. אבל, ביאה עכשיו לא חשוב, כיון שלא עושה ביאה שלאחר כמה שנים, ולא עושה שהיא עומדת לביאה שלאחר כמה שנים. ותחשב.
* נט.
** דומיא דגרושה -
עיין ברש"י. צריך ביאור למה לא לומדים גרושה, שהוא סתם, מאלמנה, שיש בה דרשה.
* עב.
** האי המול ימול -
בפשטות, כיון שדרבנן הוא, צריך ביאור למה הביאור קרא. אפשר לומר שטענו לו שאפשר שמחמת שכחה יבראו דין, אבל לא מסתבר שיבראו דין ואסמכתא. אולי אם נאמר כריטב"א (בר"ה) שהתורה מגדת לרבנן לגזור יותר מובן למה מביאים פסוק, שיש, באמת, דרשה ממנו. אבל, דע שכל ריטב"א זו צריך ביאור, שמצאנו כמה גמ' שאומרים שכיון שקרא רק אסמכתא, צריך להיות דבר אחר לדרוש ממנו. אז, רואים שאין התורה מגדת לנו כלום באותה הפסוק. אז, בין כך ובין כך, צריך לדון איך אומר הריטב"א שהתורה נותן לנו דין באסמכתא. ותחשב.
ודע שאפשר לפרש ששקלא וטריא של הגמ' הוא אם מסתבר להביא ראיה מן האסמכתא או לא. (ודע שאין מס' של גמ' זו כל כך פשוט, שאולי יש שיטה לקמן שהוא מדאו'.)
** נשיו -
מוזר איך נשיו יהיה אמו, בפרט כיון שנשיו הוא לשון רבים, ואין אדם שיש לו יותר מאם אחד. יש לדון, שיכול להיות לו אם ואם אב.
** מוליד -
ההו"א משמע שהוא מאכיל, ולא שהוא היחס שבין אביו לאמו, ושאביו מאכיל. (אין זה יוצא מן הסברה, שנראה שבין כך ובין כך אין הסברה כל כך פשוטה, ובין כך ובין כך אנו יכולים לברוא ביאור לסברה, אלא הוא יוצא מן הלשון. אז, יש לדון בו, שאולי הלשון הוא רק מפני שזהו מה שקורה בדרך הפשוט, שמחמת שהוא שם, אמו אוכלת. ותחשב.)
** רשי הא צריך -
רשי מפרש שקושיית הגמ' הוא שלהיפך יש ראיה שהוא מדרבנן, ולא רק שאין ראיה מזה שהוא מדאו'. אין זה מוכרח מן הגמ'. (יוצא מרשי, לכאו', שלשון צריך משמע שהוא מדרבנן, ולא יותר חמור מזה. יש לדון, שאולי זה רק בדבר כזה שיש להסתפק בו.)
** רשי עת רצון -
עיין במה שכ' רשי גבי כינור דוד. יש להעיר שגמ' לא אומר שרק בחצות היה, בהמשך הדורות, רוח זו, אלא שהיה תמיד בחצות לילה. אם כן, נמצא שלא תמיד קם דוד בחצות לילה, אלא כמה פעמים, מסתמא, קם קודם חצות לילה. (אין לומר שחזר לשינתו, שלא היה אפשר לו לדעת איזה נגינה של חצות הוא. ותו"ת.) יותר מזה, לכאו' כל רוח היה מנשב אותו, ולא רק צפונית. יש לדון, שאולי היה בקצת תיבה. אף בלי זה, יש לומר שהיה לו מנגינה קצת שונה כשבא רוח צפונית מכשבא שאר רוחות. ותחשב.
* עב:
** רשי ראיתי לבן -
יוצא מרש"י זה שר"א היה תלמיד של רבי יוחנן. כן יוצא גם מגמ' לקמן. ויש להעיר (וזה יותר קשה על הגמ' לקמן) שהיה חולק עליו בכמה וכמה מקומות. כנראה, לא חש לחלוק על רבו. (עיין בירושלמי בברכות שמבואר שהיה בבלי. אולי מפני זה חלק הרבה על רבי יוחנן, שהיה דרכו כל כך שונה מדרך רבי יוחנן רבו. ותחשב.)
* עג.
** אסור לבער -
אין דין איסור לבער בטומאה כל כך פשוט לי. הרי, שורפים קדשים שנטמאו, ונמצא שמבער אותם. אולי רצה לומר שאין מבערים אותם באופן הנאה כשהם טמאים. צריך לעיין, שמס' זה משנה מפורשת.
* עד:
** חללה לאו -
בפשטות, רצה לומר שמה שנעשה חלל או חללה מנתק את היחס לאהרן הכהן. נראה שיש דרך אחר לבאר אותו, והוא על פי מה שיש לחקור למה אין חלל וחללה אוכלים תרומה, אם הוא מפני שאין סיבה (אין קדושה או אולי אף אין סיבה לקדושה) או שיש מניעה (יש מניעה מלהיות קדושה או יש קדושה ויש מניעה על אכילה). אפשר לומר זה לשני צדדים. אפשר לומר שגמ' סובר שנחשב זרעו של אהרן – דהיינו שבא קדושה (או סיבה לקדושה) ממנו, אלא שיש מניעה – ודוחה שאינו זרע אהרן, ולא בא לו קדושה (או סיבה לקדושה). גם אפשר לומר שסובר גמ' שהוא זרע אהרן שלא אוכל בתרומה, כיון שאין לו קדושה (או סיבה לקדושה), ואומר גמ' שאין חילול בא מזרעו של אהרן, והוא שמצד היותו זרע של אהרן יכול לאכלו, שאין זה מעט משאר זרעיו של אהרן, אלא יש בעיה אחרת, והוא מה שיש מניעה. (אבל, זה חידוש בקריאת מילים אלו, שאז נמצא ש"אין חללה" רצה לומר "אין חילולים.")
** חללה -
צריך ביאור למה רק מדבר בחללה, ולא בחלל. (באמת, היה נראה ותר לנקוט חלל, כיון שהוא איש, כמו שכתוב בפסוק. אף שצריך להיות גם בנקבות, כמו שרואים ממיעוט חזה ושוק, היה לו לנקוט דבר שיותר נכנס ללשון הפסוק.) נראה שיותר פשוט שאין חלל (שנתחלל מילדתו) זרע של אהרן. ותחשב.
** ותו -
רצה לומר, אינו כל כך פשוט לדרוש את הפסוק לענין זה, שהרי יש כמה דינים שצריכים ללמוד. איך שנלמד אותם הדינים יהיה שייך לאיך שנלמד דין זה. ותחשב.
** רשי הדס - ס
מעניין שינקט סמ"ך לא
ור לאונן. יש שני בעיות. הראשון הוא שאין אסור אף מתחיל בסמ"ך, והשני הוא שאין דבר העיקרי מילת איסור, אלא אונן, לכאו' ותחשב. מסתבר שרוצה סיצן שמגיד דבר (ש"הדס טב" יש לו כוונה), אבל עדיין אינו סימן טוב.
* עה.
** ולהך תנא -
קצת קשה איך מפרש "שווה בזרעו של אהרן" שדרש גמ' לעיל. ותחשב.
** דלא הותר -
מעניין, שאין זה שווה לשאר "הותר מכללו," שכאן אין טומאה זו הותר מכללו, אלא הוא מתיר טומאות אחרות. (עיין בנדה, שחולקים אם דם שונה הוא שיוצא מיולדת. לפי אותה הצד, אינו מתיר שום טומאה. אולי בזה חולקים התנאים, אבל לא נראה כן, שהיה לו לתלות אותו בפירוש.) אם הייתי למדן, הייתי אומר שאולי אפשר לתלות טומאת יולדת בטומאת דם, לומר שהם טומאה אחת. ותחשב.
* עה:
** פצוע ולא הפצוע -
לא פשוט מהו פירוש מילים אלו. כעת, נראה לי שאולי בלשון תמיהה אמר, והוא שמקשה איך הפסוק מתאים עם זה, שמה שלא אומר "הפצוע" משמע שכן הוא הדין לכל פצוע. אבל, ירא אני מלומר שדברים נאמרים בלשון תמיה אם אין לי סיבה לחשוב כן (ואולי מה שאין לי פשט טוב אם אני לא אומר טוב הוא סיבה מספיקה), שיכולים אנו לעשות את עצמינו כופרים אם נחדש ששמע ישראל נאמר בלשון תמיה. ותו"ת. אבל, זה מתאים עם מה שמיד אחריו מביא בריי' שאומר מקור אחר.
** ממזר -
קצת קשה למה מחשיב אותו בידי אדם, שגם ה' שותף בילד הנולד, וה' אף לא מוסר את המפתחות להריון לשום שליח.
** לשבושי -
לשון זה מעניין; מצאנו כמה פעמים שאומר אמורא דבר כדי לתת מבחן לאמורא אחר. אבל, לשון זה – שאמר אותו כדי לשבש אותו – הוא מעניין. ותחשב. ועיין ברש"י, שנראה שמפרש שהוא רק רצה להבחין אותו.
** רשי שפייה -
מרשי משמע שממש שף את אותו הבשר. לולי רש"י, היה אפשר לומר שרצה לומר שהחשיב את הבשר כאילו שף אותו, ואמר שכיון שיש מה שצריך, אלא שרק ניתוסף עוד בשר עליו, אינו פצוע דכא. ותחשב. לא נראה כן, שיש סיבה שאותו בשר מיותר יפסול, כמו שמפרש הגמ'.
* עו.
** היכי עבדינן -
מחודש לי שיכולים לגרום לו לראות שכבת זרע כדי לבדוק אותו. אף אם לא קיים פו"ר, וצריך בדיקה זו כדי לראות אם יכול לישא, לא ידחה אותו עשה שלא בעידנא את האיסור החמור של הוצאת ש"ז לבטלה. אולי יש לחדש שלא נחשב לבטלה, כיון שהוא לבדוק אותו, וכיון שהוא גורם (מחמת היתר שלו לבוא על אשה) שישא אשה ויוליד בנים. (אין להקשות ממה שספק הוא, שנראה שכל ש"ז ספק הוא, שלא וודאי הוא שאשה תהיה הרה ממנו. אבל, אין כל ענין ש"ז לבטלה פשוט לי, שמותר לאדם לבעול את אשתו איילונית.) מעניין גם מה שלא חושש למחשבתו הרעה, אלא משמע שאומר שזה לא יועיל לעשות שמזריע. ותחשב. (ודע שעל כל פנים על הראשון של הגמ', יש לומר שזה לא יעשה תאווה, ולא יורה כחץ. אולי כיון שזה לא מוליד לא נחשב ש"ז לבטלה. אבל, עדיין היה לו להקשות על מה שאומר אביי.) אולי – וזה עונה לשני דברים – יותר רוצה הגמ' להקשות על מה שאומר אביי שלא קורה מלומר שיש איסור עמו. ותחשב.
* עו:
** מנימין -
צריך לעיין מתי זה קרה. הרי, יודעים שכל תלמידי רבי עקיבא מתו, ורק אחר כך לימד לחמשה תלמידים שלו מזקני דרום (והיה ר"י אחד מהם). אולי רבי יהודה למד ממנו כמה פעמים (כעין זה מצאנו ברבי מאיר, בעירובין ובסוטה, אבל לא יודעים שאחד מהם היה קודם מיתת התלמידים), ואולי היה לו עוד תלמידים אחרי אותם החמש. (אפשר שזה היה קודם מיתת תלמידי רבי עקיבא, ולא היה רבי יהודה תלמיד של רבי עקיבא, אלא רק היה חבר של תלמיד אחד של רבי עקיבא.)
** אלא מלבוא -
אין הקושיה זו נראה חזקה, שהרי לא אומר שאסורים לבוא על נדה. אלא, צריך לומר שסמך על מה שתמיד יש איסור. יש לדון, שאולי שאני כאן שיש הו"א (וקצת צריך ביאור למה) להתיר נתינה להם, ואז היה לו להזכיר אותו, ולא לסמוך על האיסור. ותחשב.
** תנינא -
יש לדון אם אמר לשון זה; אם אמר כן, נמצא שכבר היו להם משניות. (כעין זה אומרים שעיקר פרק איזהו מקומם נאמר כבר בימי משה, ולכן אומר "קלעים." אבל, בילדותי העירתי שיש מחלקתים שרמוזים בו, והעיר ר"ק שיש דינים דרבנן בתוכו.) מן הסברה, נראה שהיה להם משניות.
** מיד... שאל -
מעניין שהיה צריך לשאול, שכנראה בא לידו פסק. נראה שהיה רוצה לראות שאין שום פוסק שיתיר לדוד, שאם יש צד להקל לו, יחוש שימלוך, שאולי יקל כאותו הפוסק.
** מום זר -
יש לדון אם הענין הוא שאין לדייק ממנו, שבכוונה אחרת נאמר "ממזר," או שרואים שהוא נכון גם באשה, שגם בה יש מום זר, ורואים שזה עיקר הענין של ממזר.
** מפרץ -
יש להעיר שידע שאול שלא לעולם ימלוך הוא וזרעו, שלא מיהודה בא. אלא, מפרשים הראשונים בגמ' בתענית, אם לא חטא, היה נעשה נעשה קצת מלך. אז, היה אפשר לומר שהיה לו לחוש יותר אם בא מזרח, שיהיה קצת מלך, מאם בא מפרץ. ויש לדון, שאולי אם בא מפרץ, ימלוך עכשיו, וזה יעשה ששאול עצמו לא מולך. ותחשב ותבין.
** הנך -
נמצא שהצד שהלכו לעלמא אינו רק מפני סנחרב, אלא הוא אף מפני מה שקרה בים סוף.
** אם הלכה -
לכאו', לא רצה לומר הל"מ, שאז אין צריכים קו"ח, אלא רצה לומר שלמד הלכה מרבותיו. אבל, קשה, שאז כיון שלא נראה להם הקו"ח, יחלקו גם על רבותיו. צריך לומר שלא היה קושייתם מוכרח (עיין בגמ', שתלוי במח', ואז אינו מוכרח). ותחשב.
* עח.
** תני ראשונה -
נמצא שרצה לומר שישא לה אפילו ראשונה, שלא חושש שזה יגרום פסול לב"ב, שהולך בתר האב, ולא בתר האם. ותו"ת.
* עח:
** חוצץ -
מעניין שיכולים לומר (ולצדד) שאף שיש חציצה בכולו נחשב שטבל. ותחשב.
** אין הדבר תלוי אלא בי -
מעניין שאמר כן, שהרי לא היה תלוי בו, אלא בשאול. נראה שכיון שהיה מלך, לא היה מי שיכול לתקן חוץ ממנו, ולכן אמר שלא תלוי אלא בו. גי"ל שראה שלא היה דבר שקל להבחין, ורק הוא (צדיק הדור או מלך הדור) היה יכול להבחין מה הוא.
** דון מינה -
צריך לעיין מתי אומרים מח' זו, שלפעמים (כמו כאן) אפשר לומר שלומדים דין שלא נמצא (שלומדים גם פסול נשים, וזה דין שלא נמצא). ותחשב.
** גבעונים -
נמצא שהיו חוטבי עצים אז. צריך לומר שהיה גזירת יהושע קיים. אף שהיה רק בזמן שמקדש קיים, צריך לומר שהיה משכן בכלל מקדש. ותחשב.
* עט.
** מוטב שתעקר -
צריך לעיין מתי אומרים כן. נראה שאומרים כן כאן כיון שהראה ה' שרצה להם לתקן את זה, כיון שלא יעניש ה' את בני ישראל בלא דרך לתקן את עצמם (יש לדון בזה), ואין דרך לתקן חוץ מזה. אבל, אז צריך לדון מה חושב השואל. וצריך לעיין בזה.
* עט:
** חלק מזבח -
נמצא שאין "הפקר בית דין הפקר" פועל על מה שהוא של מקדש.
** והא לאו בר הכי -
לכאו', אינו ממעט את המעשה שלו ממעשה קיום שם (כיון שלא מוליד), שאם כן, כל סריס יהיה בכלל זה. לאיזה סיבה, אינו נתמעט מחמת זה, אלא יש מיעוט אחר. תחשב על זה.
* פ.
** רשי ממעי -
עיין במה שפרש"י. אפשר לומר שאמר שעכשיו הבין הלשון "ממעי," שהוא מחמת האם שהוא ניזוק, ואז שפיק הוא "ממעי אמו." (אין הלשון "ממעי" צריך לומר כן, שזהו לשון הרגיל להשתמש בו, ואז נראה ש"לא ידענא" לא רצה לומר שתמיד היה מפליא בעיניו מה היתה כוונתה, אלא רצה לומר שעכשיו רואה שלא הבין פי' האמיתי של הדברים שלה. אולי יש קצת סמך לזה ממה שלא שאל לה. אבל, לאידך גיסא, יש לדון מהי"ת שכיוונה לזה. ותחשב.)
* פ:
** ואינו ניכר -
יש לדון אם רצה לומר שקולו כאשה, ולא ניכר בין איש כזה לאשה, או שרצה לומר שקולו הוא מין קול שלא נודע אם הוא של זכר או נקבה (הוא בין קול נקבה לקול זכר, ולא פשוט לבני אדם אם הוא קול איש או אשה). ותחשב.
** כמאן כר”ה -
נמצא שהיה מיקל עם ר"נ נגד שיטתו. נראה שזהו קושיית הגמ' (נראה ש"כמאן" הוא קושיה). קצת קשה למה היה צריך לבדוק בר"נ, שהיה נראה שר"נ יבחין אם הוא עצמו סריס, ולא ישא אשה אם אסורה לו.
* פא.
** בזמן חזה ושוק -
יש לדון למה לא אמר "תרומה דאו'," ונאמר שהוא בזמן תרומה דאו'. נראה שנחשוב אז שהוא תרומה דאו' עצמו. רק מבחינים כאן מפני ששינה בלשונו, ולא אמר דבר הרגיל לומר אם היה כוונה שלו לחלק בין איסור דאו' לאיסור דרבנן. ותחשב.
** מי סברת -
לכאו', חולקים ברבי מאיר. אז, קשה למה לא אומר שזה כשיטת רבנן. ותחשב. כמו כן, קשה למה לא אומר שזה כמי שמיקל ואומר שהוא דרבנן (ע' בגמ' לקמן). ותחשב.
** דבר שיש לו מתירין -
חולקים ראשונים בענין דבר שיש לו מתירים. רשי סובר שהוא שכיון שאפשר לאכול אותו בהתיר, יאכל אותו בהיתר, ור"ן אומר שאז אין כל כך סיבה שיבטל, שהם יותר דומים. הרי, אם נאמר כר"ן, מובן הו"א של רב אשי, שיש בו ענין של היתר, וגם מובן המס', שצריך להיות שיהיה מותר לגמרי, ולא מותר למקצת בני אדם, אף שהוא עכשיו (אף שלא נראה שלשון הגמ' אומר כן). ותחשב. אבל, לרש"י צריך ביאור. (עיין ברב אלחנן על ביצה, שאומר שבעיקר ר"ן סובר כרש"י.) הרי, נמצא שמה שאומר רב אשי הוא שכיון שיכול להנות ממנו על ידי מכירה לכהן, יש לו דין של דבר שיש לו מתירים. הרי, זהו הפשט, וכן פי' רשי את ההיתר לעיל. אז, קשה איך נדחה. צריך לומר שלשון ר"א (דבר שיש לו מתירים) לא משמע כמה שאומר רש"י, וסובר שיש בזה הפסד, אלא שנאסר בלא פלוג מדבר שיש לו מתירים, כיון שיש בו היתר. לזה, דוחה גמ' שלא דומים, שההיתר שיש כאן הוא מאד שונה. ותחשב.
** ולר"ל מאי שנא -
לא הבנתי את הקושיה כל כך; עיין ברש"י שמנסה לבאר, אבל איני רואה את ההוכחה.
* פג.
** מדשבקיה -
הייתי חושב שכיון שאומר דבר עם רבי שמעון במקום אחד, נראה שזהו העיקר, שיש לומר שכיון ששמע מרבי שמעון חזר בו. תחשב על זה, שבין כך ובין כך, יש חולק עליו, ויש לומר שלו חזר. נראה שפשוט לגמ' שאם יש חזרה, הבריי', שבדר"כ מאוחר, הוא השני. (יש לדון אם נכון שבריי' מאוחר.) רק דן אם חזר בו או אם חולק על המשנה במה אומר. כיון שאינו עם רבי שמעון, מניח גמ' שחזר בו, ולא שחולקים מה אמר. ותחשב.
* פג:
** אחוה -
צריך להוסיף אותו למנין אחים ת"ח שלנו.
* פה.
** לאחר מיתה -
אין זה כל כך פשוט, שיש לומר שחלק ממה שלא רוצה להתגרש ממנו הוא שיודעת שתקבל מזונות לאחר מיתתו.
* פה:
** סוטה -
עיין בקו' תוס' בכתובות בתחילת פרק שלישי (למה לא נקט ציור זה). נראה שהלך כסדר גמ' שלנו, ובגמ' שלנו נקט סדר זה, לבאר שיש קושיה למי שעושה חלל מעשה. אבל, שם, אין לו אותו הקושיה, ולכן מסיק בזה. אבל, עדיין יש קושיה, נראה לי, לתוס' מגמ' בקידושין ממקור שרבי עקיבא מודה שם. ותחשב.
* פו.
** מיתה -
לכאו', למסקנא, אין מקור לחיוב מיתה בטבל שהפריש ממנו רק תרומה ומעשר ראשון.
* פו:
** נקראים כהנים -
צריך לעיין בשאר מקומות, אבל יש להעיר שכאן מכוון לכהנים בכלל לויים, שמודה שאף לויים מקבלים מעשר.
** בימי טומאתם -
צריך לומר שמחמת לא פלוג נתנו אותו לכל כהן שירצה, שהרי ראב"ע היה עשיר מופלג, כמו שאומר גמ' בשבת וביצה. מס', עשו כן מפני שקשה להבחין תמיד איזה כהן עשיר ואיזה כהן עני.
** מת ולה -
מעניין שבן שני חשיב מבן ראשון, שהייתי אומר שלשני בעלים שלה, יש לה יחס, והוא שיש בן ממנו. ותחשב.
* פז.
** כוליה ובת -
צריך ביאור לרבי עקיבא, אז, למה אומר בו וי"ו, שנצטרך לדרוש בו שני דברים. ותחשב.
** מה לי -
קצת קשה, שדוחה את הקו"ח, ושוב מביא קרא נגדו. ותחשב.
** רשי תרומה -
עיין במה שמבאר בקדשים. אולי זהו המקור לשיריים של רבי.
* פח.
** והא תרי -
קשה, שאולי תרי נאמן, ואחד נאמן, אלא שאדם יותר נאמן על עצמו.
** בלא חתימת -
צריך ביאור למה לא מגלחים אותו. אולי זה ראיה שאסור לגלח. אפשר לומר שהוא כשלא רוצה לגלח, לאיזה סיבה, ואין כוח ביד בית דין לכפות לו לגלח כדי לבדוק אותו. יש לדון בזה, שבכ"מ נוכל להוכיח ממה שלא רוצה להתגלח. גם אפשר שמה שגדל זקן, אף אם מגלח אותו, משנה את מראתו.
* פח:
** אחד מעדיה -
לכאו', יכול להיות כל מי שאומר שברי לו (כמו שאמרנו באשה עצמה).
* פט:
** וכי בית דין מתנין -
קצת קשה למה לא אומרים שאין בית דין מתנין, וכאן משתמשים בכוח שלהם של הפקר בית דין הפקר, שמפקירים אותו רגע לפני שעשה אותו תרומה. אפשר לומר שאין להם כוח להפקיר למפרע (לעשות שדבר הפקר על פי מה שיקרה לאחר זמן).
* צ:
** כולהו נמי -
כמובן, לא רצה לומר שעכשיו כולם שב ואל תעשה, אלא רצה לומר שעכשיו מכיר שאין להקשות, כיון שב ואל תעשה.
** איבה -
משמע שאינו בחילוף שום דבר, שהרי כאן לא נותן לה שום דבר.
* צא:
** ואשינויי -
מה שאומר שאותם שינויים דחוקים מבאר למה מביא כל כך הרבה ברייתות להקשות מהם, אף שמובן שתי' ראשון יספיק לכולם. הביאור הוא שמקשה שלא רק צריכים לעשות בריי' אחד דחוק, אלא הרבה בריי' דחוקים. ותחשב.
* צב.
** ליתא -
לא מפרשים למה נקט בריי' נגד משנה.
** ראשון ואחרון -
קשה, שאף אם מת בינתיים, אף שזה נכון, אין בזה חידוש, שפשוט הוא שהראשון ממזר ושהשני אינו ממזר. יש לדון, שנראה שאין דין זה פשוט בכלל. דין בן שני פשוט, אבל צריך לעיין בדין ראשון. יש לדון אם אמר לו מתי מת, ורואים שהראשון ממזר או לא. לצד שני, נמצא שיש חידוש מזה, והוא שאף שיודעים שעכשיו מת הבעל, מניחים שמת אחרי הביאה שהוליד בן זה, ושהבן ממזר. ותחשב.
** לימא אין ממזר מחיי"ל -
קשה, שאולי רוצים להורות שאף שיש לומר שאין ביבמה תפיסת קידושין (כמו שאומר רב לקמן), ויש לומר שאז הבן ממזר (עיין בתוס' בכתובות בפרק שלישי), אינו כן, והבן כשר. ותחשב.
** חיי"ל דשאר -
ק"ק, שעדיין היה לו לומר שאין ממזר מחיי"ל שאינם שאר. אולי מובן למה רק נקט ציור אחד, שהוא יותר קצר מלומר כל זה. ותחשב.
* צג:
** בחלמא -
צריך לעיין בגמ' בסוף ברכות, שמשמע שאם נפל לפיו פסוק הרע קודם פסוק הטוב, סימן רע הוא. הרי, כיון שנפל לפיו שהוא סימן רע, קשה, שהוא סימן רע. אפשר לומר שה' נתן אות זה לך כיון שכיוון לטוב, ואת הוא ששנית, וחשבת לרע. ותחשב.
* צד:
** אשוגג -
קשה למה לא חילק לומר שאין סיבה לקנוס, שלא נאמנת (ע' בתחילת הפרק).
* צו:
** הכל יודעים -
מעניין לומר כן, כיון שמצאנו כמה פעמים שרב אלעזר חולק על רבי יוחנן. צריך לומר שאם היה חולק עליו, אמר בפירוש שזה לא אליבא דרבי יוחנן, אלא חולק עליו.
** דובבות -
משקו"ט של גמ' נמצא שזה קורה אף אם לא מזכיר אותו בשמו, אלא שבני אדם מכירים שעליו מדובר. יש לדון מה יקרה אם אדם אומר "הריטב"א" לבני אדם שלא יודעים מי כתב את הריטב"א, או כעין זה. ותחשב.
* צז.
** אי כחוש -
יש לדון אם אמר כן אם באו לו אחרי שנעשו סריס, ואומר שאם עושים כן ומיד באים להם שערות, רואים שאינם סריס, או שהיה עושה כן לפני שעשו סריס, קודם שבא להם סימנים. ותחשב.
* צז:
** מאי טעמא -
נמצא שלא רק דן בטעם של דין המשנה, אלא אף דן בדין של המשנה (אם אוסר או פוטר). לשון הגמ' לא משמע כזה, כמובן, אלא משמע שבעיקר דן בטעם של המשנה. פשוט לגמ' שזה רק פוטר אותם מחליצה, אבל זה יכול להיות מחמת פטור ויכול להיות מחמת איסור, ובזה – הטעם – דן הגמרא. ותחשב.
** רשי בתר -
זונה- עיין בגמ' לקמן שאומר שאין זה הטעם שאין יחס מן האב, אלא הוא מפני שה' הפקיר את זרע של גויים, ואז אין יחס בין אב לבנים שלו (וממילא, אין יחס לבנים להדדי). ותחשב.
* צח.
** הרי אשה -
לכאו', לא אמר את זה בפניו. אז, כיון שאמר שאף היא ראתה, לא ישקר, שיכולים אנו לשאול לה, ואם אינו אמת, לא תגיד לנו. ותחשב.
** מעשה אחרינא -
קצת קשה איך זה ראיה, שאולי שיקר. מסתבר שלא ידוע לבני אדם שזה עשוה אותו יותר נאמן, ואין טעם שיוסיף את זה אם לא מפני שבאמת נאמרו ביחד. ותחשב.
* צח:
** דילמא מתרמיא -
יוצא שעושים דבר שיכול להיות שיבוא לדבר מאד טוב, ולא דבר שמבטיח לנו קצת טוב.
* ק:
** נתפסה -
מעניין שצריך קרא למור שאין חלות קידושין בטעות.
** טעות -
נמצא שאינו נחשב זנות, אף שלמפרע, לא היה קידושין. (יש אותו חידוש במיאון, אלא שיש לומר ששם תקנת רבנן הוא שלא יהיה בה דין זנות כדי שישאו קטנות.) ותחשב. כנראה, זנות תלוי בכוונה או בדבר אחר חוץ מנישואין ממש. ותחשב.
* קא.
** רשי בבת אחת -
עיין בציור שנותן רשי. לכאו', היה אפשר לומר שיש ציור אחר, והוא שיכה זה ומיד אחר כך זה, או שמכה את שניהם בזמן אחד בשני ידים. אפשר שרשי היה יכול לומר ציורים אלו, אבל נראה אולי לחדש שרשי אומר שצריך להיות מעשה אחד. במילים אחרים, יש לדון מה צירך כדי להתחייב. אפשר לומר שצריך שההתראה הוא על מה שיחייב. אז, רק צריך שיהיה, בתוך כדי דיבור (שזהו שעה של ההתראה), מה שמחייב אותו. אבל, אפשר שרשי סובר שהתראה הוא על מעשה פרטי, אלא שמעשה פרטי זה צריך להיות בתוך כדי דיבור, ואותו מעשה פרטי צריך להיות דבר שבוודאי יחייב אותו. ותחשב.
* קא:
** מפיקנא -
צריך לחשוב על זה, שהיה אפשר לומר שמכוח בית דין, יוציאו ממןו, שיודעים שזה נכון, כיון שרשב"י אמר כן, והוא נאמן. ותחשב.
* קב.
** חולצים במנעל -
משמע שמה שלא חולצים במנעל לא נחשב מנהג. יש לדון אם זה כלל שתמיד מה שלא עושים דבר לא נחשב מנהג, או שזה רק כשאין הכרח מזה, כמו כאן, שיכול להיות שרק רוצים לעשות אותו בסנדל. הנפקא מינא יהיה אם לא משתמשים בעירוב, שפשוט שאם היה מותר, היו מוציאים. ותחשב.
** רוב העקב לא -
קשה, שאולי מכוון לומר שאם שמט רגלו מרוב הרגל, שאינו רוב עקב (שעשתה כל החלק שלא היה עקב) החליצה פסולה. ותחשב. אפשר לומר שאם אותו חלק היה נחשב חלק מן החליצה, היה לה ליבמה לעשות רוב שלו. ותחשב.
** גילוי כרעא -
ק"ק למה נחשוב שגילוי כרעא מספיק, שהרי הפסוק אומר שצריך חליצה. צריך לומר שדן איזה חלק ממעשה חליצה הוא קרק' חשוב. ותחשב.
** חליצה בעינן -
נמצא בין שני שאלות של הגמ' שיש שני דברים שמסופקים אם צריכים – חליצה וגילוי כרעא. לכאו', בין הכל, יוצא שיש ארבע צדדים. אפשר לומר שצריך שניהם, אפשר לומר שצריך רק גילוי כרעא, אפשר לומר שצריך רק חליצה, ואפשר לומר שרק צריך אחד מהם. יש לדון איזה מהם נכנסים לצדדי הגמ'. ותחשב.
* קב:
** תוס' ומי איכא -
עיין בקושייתו. צריך לעיין בזה, שהרי כל סוגיות שבקדשים לא נוגעים להלכה. אבל, אולי צריך להיות שיהיו נוגעים להלכה בביאת משיח, ולא שכמעט תמיד לא יהיו נוגעים. ותחשב.
** לא יטייל אדם -
לכאו', אף תירוץ של אביי יתרץ סתירה זו. אז, לא מביא ראיה לרבא, אלא מביא ראיה שצריך להיות חילוק. ותחשב.
** באנפילא -
צריך לעיין מה עושה דבר אנפילא ולא מנעל או סנדל. אולי הוא אם יש לו סו"ל למטה.
* קג.
** לא עשה רגליו -
משמע שזה מותר, ולא נחשב בגד אשה. ודע שקשה למה היה עושה כן – אטו היה בא לפני המלך ערום. ותחשב.
* קג:
** רשי רעה היא -
עיין ברש"י. קצת קשה, שלא נראה שהגמ' מפרש כן, שהגמרא מבאר מה היה הרעה. ותחשב.
** רשי שמא -
יש לדון אם הבעיא הוא שאמר מילת "אלהים" על ע"ז או שהתורה רק אומר פאראפרי"ז של מה שאמר, אבל באמת אמר שם של עבודה זרה. ותחשב.
** שמא -
יש לדון אם הבעיא הוא לשמוע שם של עבודה זרה או שכיון שלהם היה מדבר, נמצא שגרמו לו לומר שם של עבודה זרה.
** סנדל המסוליים -
מעניין שלא נחשב נעלו הראוי לו.
** ראוי -
אולי זה מדין "כל שראוי לבילה, אין בילה מעכבת."
** דיעבד -
נמצא שאף שדורשים קרא לרבות אותו, עדיין אינו כשר לכתחילה. צריך ביאור מהו המקור לזה, שכבר דורשים מיעוט אחר מ"נעלו." אולי דין דרבנן הוא. יש לדון למה גזרו בו רבנן. אולי הוא גזירה מחמת מה שאינו ראוי לו. ותחשב.
** והבא -
כנראה, מניח הגמ' שכיון שעומד ליכתת, אינו נחשב עוד בית, ולא רק שאין לו שיעור. ויש לדון, שאולי זה מפני שלבית יש שיעור, כמו שאומר גמ' בתחילת סוכה.
** רשי חליצתה -
בגד- משמע שנעל נחשב בגד. יש לדון, שאולי רצה לומר שכמו שבגד נחשב עוד בגד, כך נעל נחשב עוד נעל.
* קד.
** מי קפיד -
יש לדון אם כוונת הגמ' לומר שהגדרה של "להילוך" הוא אם קפיד אם הולכים בו, או שכיון שלא קפדינן אם הולכים בו, מסתמא לפעמים הולך בו, ולכן הוא להילוך.
** כגמר -
אם נאמר (ע' בר"ן בר"ה שאומר כן) שענין של סוף הדין הוא שנגרר אחרי תחילת הדין, צריך לומר שיש תחילה לחליצה. אולי הוא נתינת עצה, ואולי הוא מיתת יבם (או כל המשך זמן זיקה).
** דיחידאה -
עדיין, הוא כמעשה, ומעשה רב.
* קד:
** מעשה באיש -
הגדרת "מעשה באיש" מעניין, שלא כל כך פשוט לי שאין רקיקה נחשב מעשה לו. (יש להעיר שגמ' משנה מלשון הפסוק (שהוא מעשה לאיש) ללשון אחר (מעשה באיש).)
** תחלוץ -
איני רואה במה דין שלה שונה משאר דינים שנזכרו במשנה (שכל "חליצה פסולה" פוסל אותה מייבום), ואז קשה למה לא שונה את הדינים ביחד.
* קה:
** רשי עיניו למטה -
עיין במה שפרש"י. נמצא, אז, שבני חו"ל יתפללו בעיניו לפניהם, ולא למטה. יש להעיר שבני א"י יכולים להסתכל בכל חלק מא"י שירצו. יל"ד, שאולי צריכים להסתכל בחלק הכי קרוב להם, שהוא מה שתחת רגליהם.
** רשי נצטרע -
נמצא שצרעת הוא עוד עונש של לשון הרע, אף בימים שאין נוהג כל דינים של צרעת.
** ועדים רואים -
משמע שכשאומרים שצריך שני דיינים, ממש צריכים להיות עמהם במחיצתם. צריך להגדיר את זה. יש להעיר שלכאו' היה יותר קל לומר שמדובר בשלש שלא כשרים להיות דיינים. (אולי לא יכולים לקרוא (ויש לדון אם יהיו עדים כשרים, שלא יודעים שנעשה בכשרות), או אולי הם גרים.)
* קו.
** בכך אתה כונסה -
נראה שאפשר לומר שמה שאין בעיה של טעות כאן הוא מפני שמכוון לכנוס. הרי, אם כונס, זה יהיה מפני (או זה יגרום) קיום שם. אולי חליצה גם עושה מקצת קיום שם, ואז אולי הם דומים מספיק. אם כן, אולי אם מכוון על ידי זה לזכות בגורל, לא יהיה חל.
** בת חמוה -
יש לדון למה לא רק אומר "אחות אשתו."
** יהיב -
צריך ביאור למה היה מותר לכל אמוראים אלו להמית כל כך כמה בני אדם על ידי קללות ועינים, כמו שרואים בכל הש"ס. עיין בראש בנזיר, שמשמע שלא הכירו שזה היה ממית. אבל, מוזר שלא יבינו את זה.
* קז.
** לא פלוג -
מעניין לקרוא לזה "לא פלוג." לכאו', לא תקנו רבנן מיאון באותו ציור. אז, אינו כשאר "לא פלוג"ים, ששם רבנן גזרו אף על דבר מפני ה"לא פלוג." כאן, רבנן לא גזרו על דבר מפני "לא פלוג." ותחשב. (ויש לדון, שאולי זה גזירה שנית, או שנחשב הוספת גזירה, במה שתקנו שנמשך הנישואין, ואין המיאון מבטל אותו.)
** יש תנאי -
אם כן, גם בכל נישואין של טעות נגזור. אולי אה"נ גוזרים.
** בעל כרחה -
אז, אינו כרבי שאומר שמאמר נעשה בעל כרחה.
* קז:
** דרחמנא רמייה -
מעניין שאומר שה' רמא לפניו, ולא שבא מחמת מעשה של אחיו. ותחשב.
* קח.
** רשי אתי -
אבל, אין לחוש שיכתב לה גט, שלכאו' אין זה כל כך רע, שגם זה יהני. אבל, יהיה נפקא מינא אם ישא מי שאסור לו מחמת זה. אבל, זה רק איסור דרבנן, וזה חשש רחוק.
** אין לך מיאון -
דנים בסגנון של "אין לך גדול מזה" אם רצה לומר שזה נראה שהוא הכי גדול או שאף שזה לא נראה כל כך גדול, הרי דינו שווה לשאר ציורים, ואין השאר גדולים ממנו. כמובן, מה שאומר כאן "אף" ואומר שאין גדול מזה משמע כצד שני. ותחשב. אינו ממש מוכרח (תמיד אין דבר מוכרח), אבל הוא מסתבר (ולפעמים, צריכים אנו להיות שבעים בדבר המסתבר).
** מאי לאו דהוה -
קשה למה נחשוב כן. אפשר שהוא מלשון "כלתיה." אבל, אז צריך לומר שאותו הלשון בא מאיזה מקור ידוע, ולא שאומר כן הגמ' כשמביא את הראיה. יותר נראה לומר שהוא על פי מה שאמר גמ' לעיל 0בסוף פרק מצוות חליצה), שזה היה עונש לאבדן. אולי רק נחשב עונש גדול אם היו כבר נשואות. ותחשב.
* קח:
** ריב"י -
מעניין למצוא מחלקת בין ריב"י ורב. גם מעניין למצוא רב במה שקורא גמ' "תנאי."
* קט:
** ואזלי ועבדי -
יש לדון למה זה לא מיוחס לו. אפשר שהוא מדבר במי שסובר שאין צורך לעשות. אז, כיון שהוא לא מלמד להם כדי לעשות, לא מיוחס לאותה התוצאה. גם אפשר שמדובר במי שרק קשה לו לקיים. אבל, כיון שהוא עצמו לא מקיים, לא יכול ליחס לקיום שלהם. צריך לחשוב למה זה כן. ותחשב.
* קי:
** ניחא -
מעניין לי שיש ענין של "ניחא" כאן. הייתי אומר שלא תלוי במה ניחא לו, אלא רק תלוי איזה יחס יותר חזק. ותחשב.
* קיא:
** אפילו בן יום אחד -
מענייו שלא לומדים מזה שאף שנאסרה, יכולה לייבם (שאין כל כך מקור לכלל זה, אלא נלמד ממה שכל דרכי התורה נועם). לכאו', הכלל שיוצא, למסקנא, הוא שכל שנאסרה מחמת דבר שעומד לשנות וליעשות היתר, מותר לה לאחר זמן. אולי זה מפני שאין זה כל כך נגד כללי נועם. הרי, יודעת שצריכה לייבם, ולא צריכה לחכות עד עולם על ספק. ותחשב.
[אגב, אזכיר כאן מה שמעניין שאומר גמ' בנזיר שלא חיו בנים לר"ה בימי רב אדא בר אהבה. עדיין, חי רבה בנו של רב הונא, והיה חבר של רב חסדא ודורו, כמו שרואים בביצה. אבל, ע' לקמן (קכב.) שהיה ראב"א בימי רב יוסף. מעניין.]
* קיב.
** הון -
אולי זה קצר ל"הונא."
** טמאה -
נראה שלא היתה נאמנת לבעלה לעשות איסור, אלא שהבעל היה חייב מחמת איסור שלה. למס', לא חייבו לבעל מחמת איסור שלה. קשה, שיש לה איסור בוודאי, שהרי שויא לנפשה חד"א. ויש לומר שחייב לגרש, אבל לא לתת כתובה. דחוק. צריך לעיין לאיזה דברים מאמינים לה בזה. גם יש לומר שכיון שלא חושבים שהיא באמת חושבת כן, אינו נכון שיש לה שוי"א. עיין לקמן בגמ', שנראה שיש לנו עוד ראיה לזה.
** יבם -
קשה מה נעשה שם, שאין מי שיכול להפר את הנדר שלה לענין יבם. ותחשב.
* קיד.
** דאיסור סקילה -
עיין לקמן שרבא אומר שלא מחלקים בין איסור כרת לאיסור לאו לענין גזירה. יש לדון אם רבא יודה כאן כיון שיש חיוב סקילה. (אפשר לומר שאינו תלוי בכלל בחומר האיסור, אלא שיש קצת חשש סכנה כאן, שאולי יבוא להתחייב מיתה. לא נראה כן, שהרי מסתמא לא יתחייב מיתה, שצריך לקבל התראה ועונוש.)[fn:1]
* קיד:
** מותנא -
יש לדון אם זה נוהג בדווקא במותנא או שלאיזה סיבה אומרים כן במותנא, ולכן חושבים עליו בני אדם כן. ותחשב. (באמת, אולי אינו נכון בכלל, אלא שבני אדם אומרים כן. אבל, יש גמרות שמקשה ממה שאומר בני אדם (בנוגע אם לשמוע לאשה).)
* קטו.
** כשירדתי -
לכאו', לא רצה לומר שיצא מא"י כדי לעבר שנה, שזה אסור. רק היה יכול לעבר בחו"ל כיון שהיה הגדול, והיה בחו"ל. אולי היה אסור בארץ לעבר שנה, או אולי ירד ממקום אחר (ולא מא"י). גם יש לומר שלא היה יכול למצוא ת"ח לעבר עמו בא"י. ותחשב.
* קטו:
** מי חיישינן -
קשה איך "יצחק ריש גלותא" יכול להיות. אולי זה היה שם, כעין מה שמצאנו בשבת בפרק רבי אליעזר דמילא או בפסחים).[fn:2]
* קיז.
** שאם תנשאי -
מעניין, שאם באמת לא מותר לה להינשא, נמצא שלא נשאת, אלא בזנות נבעלה. אז, מעניין שסומכים על ההיתר לומר שנכנס בכלל זה לענין חיוב ממון. ותחשב.
* קיח.
** תמות נפשי -
משמע שאם היתה עושה כן, לא היה אסור לה. יש לדון, ששוי"א. אפשר לומר שהקמ"ל הוא שעדיין אסור, כיון ששוי"א. אבל, עיין לעיל, שהיה לנו סיבה לחשוב שלא אומרים ששוי"א כיון שנראה לנו שהיא משקרת. ותחשב.
* קיט:
** רישא חזקה -
לכאו', זה פשוט. צריך ביאור למה אין שאר האמוראים מתרצים כן. ותחשב.
** הכרזה -
בילדותי הקשיתי למה לא רק אוסרים אותה תמיד לכהנים. ותחשב.
* קכ.
** לדבריהם -
קשה למה נחשב כן. נראה שאין זה סברה כל כך חזקה. לא רוצים שר"א באמת יחשוב כן, ויותר קל לומר שרק הקשה שאף אם רבנן לא מסכימים לו, אולי יסכימו לסברה זו. ק"ק, שאם נראה לנו שר"א לא יסכים לו, לא נראה שיקשה לרבנן שיסכימו לו. ותחשב.
* קכ:
** מלובנת -
מעניין, שלכאו' אין החום עושה שום דבר, שחידוד קודם לליבון, כמו שאומר גמ' בחולין גבי סכין. אולי זה רק בבית השחיטה שהצדדים נפתחים, אבל אולי אין שאר חלקי בהמה כן.
** איהו קריב -
נמצא שכשדבר אחר קירב מיתה, אין חיוב גלות, אף שגרם שבוודאי ימות. ה מעניין ומחודש. לכאו', זה מפני שמיתה שלמעשה קרה לא בא מחמתו, אלא אף מחמת דבר אחר. מיתה שהיה בא מחמתו הוא שונה. ותחשב.
* קכא.
** ארבע רוחות -
לכאו', יצטרך לראות ארבע רוחות ביחד. ויש לדון, שאולי מניחים שיראה אותו גם קצת אחרי שיצא מן הים, ואז רק צריך להיות מסבב ורואה את כולם בזמן קצר. ותחשב.
* קכב.
** החזיקו -
יש לדון אם הודה להם אחרי שהחזיקו או שהחזקו כיון שהוא חזר בו. ותחשב.
** נומית -
מעניין שלשון מוזר זה בא פעמיים בתוך דף אחד. אולי שני משניות אלו נכתבו על ידי תנא אחד שאמר לשון כזה. ותחשב.
* Footnotes
[fn:1] אגב, עיין בקושיית תוס' בכתובת למה אין הרבה בני אדם מתים מפני שעברו על מה שמחייב אותם בד' מיתות, כיון שה' מעניש אותם. צריך לומר שתוס' מניח שלא צריכים התראה. אולי אם גלוי לה' שהיו עושים אותו בקבלת התראה, ימית אותם, ולא צריך קבלת התראה ממש. גם אפשר שפוסק כרבי יוסי, שהתראה היא רק סימן, ויש שלא צריכים התראה. ותחשב.
[fn:2] אגב, יש להעיר שאולי אין שם הפרק "רבי אליעזר דמילה," אלא שם הפרק הוא "רבי אליעזר" והוא הפרק דמילה. "דמילה" לא קאי על "רבי אליעזר," אולי, אלא על "פרק." ותחשב.
