ט.- נראה שאפשר שסברת "הואיל ואישתרי . . . " הוא דומה לסברת “כיון שהותר [לחצי שבת] הותר.” זה יבאר למה צריך להיות שכבר חל ההיתר. לשון גמרא לא משמע כן. ותחשב.
כד.- הזכיר לי א.ד.ר. שיש מקשים למה לא דחה גמרא את הצד שרק בכור מייבם ממה שצריכים קרא למעט קטן. אם בכור הוא, אחיו צריך להיות קטן, ואז אינו מקודש מדאורייתא. אפשר שהיה אפשר להקשות מזה. נראה לי לתרץ על פי גמרא (-----)[fn:1] שאומר שיכול להיות שנולד ראשון נעשה גדול שני אם נולד בסוף אדר ראשון ואחיו נולד בראש אדר שני ושנה שלש עשר שלהם הוא שנה פשוטה. אם כן, יש לומר כן כאן. (אמר לי תירוץ בשם הגר"א שאם בכור בן תשע חדשים ושני בן שבע חדשים (מאשה אחרת), נמצא.)
- עיין בגמרא גבי רב נחמן ורבה רב אבוה (סריס). יש להעיר שנמצא שלא נשא, אף כשהיה עשרים, ואף שהיה לו לעצמותיו לתפח. ואולי לא היה יכול למצוא אשה. גם יש להעיר שלא נשא בת רבה, שיודעים שנשא בת ריש גלותא. ואולי נשא שני נשים (זה אחר זה או בבת אחת). ואפשר שזה היה אשתו השניה. גם אפשר שלא היה בעיה כיון שאולי היה סריס.
- עיין בתחילת מצוות חליצה. יש לדון למה צריך להיות בית דין שקול; לכאורה, צריך לזה רק מפני שצריך להכירע. יש לומר על פי מש"א תוס’ (כן אני חושב) שצריך שיהיו שם ושיהיו יודעים קריאה כדי שלא יצטרכו לצאת ולשאול על קריאה. אם כן, אולי צריך להיות שלא יחלקו איך לקראות.
גם יש לומר שאין הסיבה שווה לסיבה של בית דין רגיל. אלא כיון שנלמד מקרא של "זקנים" לומדים דיני בית דין. ויש לדון.
- עונשם של עריות- במקום אחר הערנו שמעניין שאומר שעונשם של מדות יותר קשים משל עריות, שהרי לא דן בעונש, אלא ביכולת לעשות תשובה. יש לציין לגמרא שבת (סח.) שאומר כגון זה (שקשה עונש של שבת, כיון שבא על יותר). ותחשב.
- רש"י כ’ שרבי אליעזר ורבי יהושע היו רבותיו של רבי מאיר (בסוגיא של אין איסור חל על איסור). אף שהיה רבי מאיר תלמיד של ר"ע, שהיה תלמיד של רבי אליעזר, נראה שאין זה קשה. יש לציין לגמ’ ברכות (כח.) בענין נשיא, ששם אומר שאותו תלמיד ששאל לרבי אליעזר ורבי יהושע היה רבי שמעון. רבי שמעון גם כן היה תלמיד של רבי עקיבא. עדיין יש לדון, שרק ידועים ששאל שאלה אחת לר"י ור"א, אבל אולי לא היו רבותיו. ותו"ת.
* Footnotes
[fn:1] גמרא ערכין הוא גבי בהמה. שמעתי מאת י.מ. וו. שאינו כל כך פשוט גבי בהמה.
