* ב.
** אור לילה ־
צריך ביאור איך אפשר ש"אור" יאמר לילה. הרי, אין אור בלילה, ויש אור רק ביום. נראה ש"אור" לא רצה לומר "ליי"ט," אלא רצה לומר "פיי"ר" (שהוא אור עם שורוק, ולא חולם). קורא לילה אור כיון שבלילה צריך יותר אור. ותחשב.
** לחשיכא ־
זה משמע שיש דבר שהוא חושך, ואינו רק העדר אור. אבל, אם רצה לומר שאמר כן לממלאך הממונה עליו, יש לומר שיש מלאך שממונה שלא יבוא אור, ולו דיבר. ותחשב.
** כוכבי אור ־
נמצא אז ־ וזה מעניין ־ שאומר מילה מיותרת בקרא כדי ללמד לנו דין בנדרים, אף שבדרך כלל נדרים הולכים אחרי לשון בני אדם. ותחשב. אפשר שהאו כעין "להגדיל תורה ולהאדיר," שמשמיע לנוו יותר תורה, ואף שבדר"כ לא נוגע לדין, כיון שלפעמים נוגע נחשב תורה, וממילא יש הרבה יותר קיומי תורה, שיש עוד תורה ללמוד. ויש לדון אם צריך זה, שלמעשה צריך מקור מה יעשו במקום שאין משמעות למילת "אור."
** מי כתב ־
לכאו', יש שני דרכים לפרש מה שאומר כאן גמרא:
+ אפשר לומר שגמרא אומר שאילו היה כתוב כן, היה מוכרח ש"אור" רצה לומר יום. אבל, כיון שלא כתוב כן, יכולים לדחות.
+ אפשר לומר שגמרא אומר שאילו היה כתוב כן, היה אפשר לפרש שאומר ש"אור" רצה לומר יום. אבל, כיון שלא אומר כן, בין כך ובין כך צריכים לחדש פירוש לזה.
עיין ברש"י, שמפרש בכל אלו כצד שני. ויש להעיר שלקמן יהיו ראיות שמוכרחים לומר בהם כצד ראשון.
** הא קמ"ל ־
רש"י כ' שלכל כוכבים יש אור. לכאו', סובר שלא היה ממעט שאר כוכבים רק כדי להודיע לנו דין נדרים.
* ב:
** שעות דרבנן ־
אם הייתי לומדיש, הייתי טוען שהמחלקת העיקרי ביניהם הוא אם רבנן קבעו איסור על כל היום משעת איסור דרבנן, ובזה הוסיפו על איסור דאו', או שרק אסרו שעה. צריך ביאור למה יעשו את הראשון. נראה שהביאור יהיה שעשו כעין דאו', שאסר חצי יום. ותחשב.
** אורה ־
מעניין שגמרא מחלק בין "אור ליום" ו"אורה," ולא מחלק בין "אור ליום" ל"אור." ותו"ת.
** ת"ש ־
וא"ת אחרי שהוכיח אותו גמרא, למה מרבה להביא עוד ועוד ראיות. ויש לומר שהוא מפני שהיה אפשר לדחות, אם רק מאצנו אחד או שני ראיות, שלפעמים אור ר"ל יום ולפעמים ר"ל לילה. גי"ל שהיה אפשר לדחות שיש תנא שאומר אותו ליום ויש תנא שאומר אותו ללילה. ותחשב.
** אף בעולם הזה ־
עיין במה שכ' רש"י. יש להעיר שזה קרה אחרי מותו, והוא לא נהנה ממנו.
* ג.
** רכבת ־
עיין בקושיית רש"י ובתירוץ שלו. חוץ ממה שצריך לדון איך מורה לנו כן, צריך ביאור למה לא לומדים כן ממה שבשאר מקומות אומר "טמאה," ולא "אשר איננה טהורה." ותחשב.
* ג:
** הרגוהו ־
צריך ביאור למה הרגו אותו. יש לומר שהבינו שאם לא היו הורגים אותו, היה הורג את ריב"ב שהטעה אותו. אבל, עיין ברש"י, שמשמע נגד זה, שמשמע שמתחילה היה ריב"ב רוצה להרוג אותו. ותחשב.
** שעורים ־
נמצא שכשאומר דבר רע, צריך לומר עמו דבר טוב, ולא מספיק אם רק אומר דבר שממנו יכולים לדייק רע, ולא אמר רע. יש לדון, שאולי נחשב כאומר רע בפי' כיון שאמר להם דבר שלא נוגע. ותחשב.
* ד.
** אייבו קיים ־
רש"י מפרש ש"אייבו" היה שם של אביו של רב. (חושב אני שיש מחלקת ראשונים בזה, אבל כן סובר רש"י.) אם כן, נמצא שרב קרא לאביו ולאמו בשמות שלהם. אולי יש להקל קצת כיון שלא היו עוד בחיים. גם אפשר להקל כיון שרבי חייא שאל להם בשמותם, והוא רק השיב כשמותם. ותחשב. אבל, לא נראה כן, שהוא אמר שם אמא ראשון. אולי אמא שונה, שמה היה לו לומר ־ ששמה אמא. אבל, באייבו יש לדחות שחזר למה שאמר רבי חייא. ותחשב.
** דכתיב ביום השמיני־
מרש"י יוצא שזה הוכחה שאין צורך להקדים קודם תחילת היום. יש לדון איזה ראיה יש מן המשנה, ששם מדבר במילה, וזה אי אפשר בלילה. לולי רש"י, היה אפשר לדחוק בלשון גמרא שמכוון להביא ראיה שיש ענין להקדים. אבל, אז היה לו להביא ראיה קודם תירוץ הגמרא.
** הלכך ־
כשאומר אביי, "הלכך תלמיד חכם...," יש לדון על מה קאי. לכאו', היה נראה לומר שהוא הולך על הדין, שצריך להיות בלילה. אבל, קשה, שאז היה לו לומר כן על המשנה, ולא על הגמרא. אלא, משמע שהוא הולך על הגמרא שנותן טעם לזה, ומפרש שכיון שיש טעם טוב לזה, וכיון שרואים שהוא חיוב בלילה, דין שלו נכון. גם יש לפרש שלמד מן הטעם שהוא חיוב לבדוק בלילה, ולא רק אומר המשנה שיכול לבדוק בלילה. אבל, לא נראה כן, שמקושיית גמרא נראה שהניח כן כבר במשנה.
** והולך ־
רש"י כ' שעשה כן כדי ללמד לתלמידים. קשה, שאולי עשה כן כיון שזהו ההלכה. אולי לא היה אומר לשמש שלו מיד כל מה שצריך לעשות, אלא היה אומר לו להביא מנעליו עמו, ואח"כ יאמר לו שילבש אותם.
** אור הנר ־
עיין ברש"י שבאר לימוד מקרא לזה. קשה, שדין דרבנן הוא, ומסתמא הפסוק אסמכתא. אולי רש"י מפרש שהפסוק מלמד לנו דין דאו', והוא שמדאו', אם לא בטל, צריך לבדוק, ומפרש לנו איזה מין בדיקה מהני. אם כן, רש"י הולך לשיטתו למה שכ' בתענית (אם רש"י בתענית הוא רש"י) שגזירה שוות שבגמרות כזה הם ג"ש ממש. ותחשב.
** בדיקת חמץ ־
עיין ברש"י על המשנה שבאר שצריך לבדוק מחמת איסור בל יראה ובל ימצא. עיין שם בתוס' שחולק על זה. יש להעיר שאפשר לומר שרש"י רק מפרש כהו"א של הגמרא, שהוא שצריך לבדוק מדאו'. אז, רש"י אומר שצריך לבדוק כדי שלא יעבור על בל יראה ובל ימצא. אבל, אולי אחרי שבאר גמרא שלא צריך בדיקה לסלק את עצמו מאיסור בל יראה ובל ימצא, אפשר שרש"י סובר שיש טעם אחר בבדיקה, ואולי יסכים לתוס'.
** בחזקת בדוק ־
נמצא שאף שהחיוב הוא על המשכיר, אם אינו בודק, השוכר חייב, שאם לא כן, אין נפקא מינא אם הוא בחזקת בדוק. ויש לדון, שיש לומר שיש נפקא מינא למי שקונה בית, שאולי הוא חייב אף אם קונה אותו בארבע עשר.
* ה:
** רבי עקיבא ־
רש"י משמע שהמקור לזה הוא מה שקרא לו אב. יש להעיר שגם יש מקור לזה ממה שלא אמר שעשה ידחה אותו. ותו"ת.
*  ו.
** אף על גב דמצי מסלק ליה ־
לכאו', זה קשה מן הבריי'. צריך לעיין בזה.
** לא ימצא ־
כיון שמסיק שדורש כן מ"לא ימצא," ולא מ"בתיכם," נמצא שהקרא שהביא בבריי' הוא דוקא (רצה לומר, הביא החלק הנכון שבו).
*  ו:
** מוקדם ומאוחר ־
נראה שהענין הוא שהתורה לא רק אומרת מה קורה. אלא, הוא כמו אדם שחושב מה קרה לו ומה למד בימים שעברו, שלא יאמר דברים כסדרם, שאין זה הסדר שחשוב לו. ותחשב.
** משה ־
יש להעיר שזה בפסח שני. אם נאמר שדין זה בכל י"ט, אין זה כל כך קשה. אבל, אם נאמר שהוא רק בפסח, צריך לומר שהוא רק בפסח ופסח שני, ומסתמא הוא מפני דין פסח או מצה או מרור, או מפני כולם. ותחשב.
** אינו חשוב ־
יש לדון אם זה רצה לומר שאינו שלו או שאינו חמץ. מראיית גמרא, נראה כראשון.
* ז.
** עיסה ־
נמצא מגמרא זה שיכול אדם לבטל דבר שאינו חמץ. (יש לדון אם צריכים מה שממילא יהיה חמץ.) זה מעניין; היה אפשר לומר שענין ביטול הוא שבאמת לא שווה כלום, אבל לא רק תלוי במה הוא שייך, אלא גם תלוי במה שהבעל מחשיב עליו, וענין ביטול הוא לגלות שהוא מודה על האמת שלא שווה כלום. יש לדון אם נוכל לומר כן כאן, שכאן אינו חמץ, אבל ממילא יהיה חמץ. ותחשב.
** בחיטי ־
עיין ברש"י שמפרש שכל המקדש על דעת רבנן מקדש. קשה למה צריך זה, שהרי רבנן הפקירו אותו, ואינו שלו. (באמת, כן יש להקשות על מה שמקשה גמרא ־ הניחא מי שמקדש בכסף ־ שאם זה היה הדבר היחיד שבכלל זה, לא היינו צריכים כלל. אבל, שם לא כל כך קשה, שהרי ידע שכיוון לומר שרבנן יכולים לבטל את הכל, ורק דן איך זה יכול להיות. יש לדון, שאולי גמרא לא משמע כן.)
נראה שאפשר לפרש שהענין אינו רק שאין אפשרות ביד חכמים, שאין להם הכוח, אלא הענין הוא שלא רוצה תורה שדברים ישנו ממה שיהיו לולי רבנן. אז, צריך כוח זה על הקידושין, כיון שבזה מסלקים קידושין. לא צריכים כזה לשאר דיני ממון, שהם בכלל הפקר בית דין הפקר. אבל, צריכים כן לקדושין. קושיית גמרא שהבאנו הוא שאף שלא משנים מה שלא יכולים לשנות, אין להם כוח, שרק יש להם כוח להפקיר.
תחשב על פשט זה, שהוא מעניין. אבל, דע שעדיין לא מובן לי למה יהיה כן. ותחשב.
* ז:
** לאו איהו ־
צריך לחשוב בזה, שלכאו' יש מצווה למול. אם רצה לומר שאפשר בשליח, כן הוא בפסח וכדומה ג"כ. אז, צריך לעיין.
** דילמא מקלקלי ־
צריך ביאור למה למעשה לא חוששים לכך. אולי מניחים שלא יקרה, או אולי המצווה היא רק לנסות. ותחשב.
* ח:
** דרכן ליזוק ־
קשה למה אין זה נחשב היזק מצוי, שאז אין שמירה למי שעושה מצווה. (באמת, על כל סוגיה זו יש להקשות כן.) צריך להגדיר מה נחשב היזק מצוי.
** פירות גינוסר ־
נמצא שבהוספת כוונה שלא לשם שמים נעשה שאינו כל כך לשמה, אף שאותו כוונה לשמה נשאר בשלימות שלו (שלכאו' מה שיש שם פירות גינוסר אינו סיבה שלא יהיה כוונה לשמים כמו שהוא בלי פירות גינוסר.)
** שתי שורות ־
לכאו', זה מחלקת במציאות ־ מה עושה השמשים. ותחשב.
* ט:
** כהן ־
יש להעיר ששם היה בשר, ואז למי שדוחה שבשר שאני (שבוודאי אוכלים בשר) אין ראיה מכאן.
** תשע ־
לכאו', כבר יש סיבה להקל כיון שיש ספק ספיקא, שאולי לא נטל את החמץ, ואף אם נטל, אולי אכל אותו. אולי זה מדובר כשרואים שלא אכל אותו. יש לדון איך נודע כן; אולי לא היה זמן לו לאכול אותו עד שראה אותו בלי החמץ. ותחשב.
** טומאת מת ־
אגב, צריך לעיין מתי נגנזה מי חטאת. יודעים שאף בזמן הגמרא נהגו טהרה. לכאו', זה אי אפשר אם לא היה להם מי חטאת, שכל מי שקרובו מת חייב לטמא לו, ולא נטהר עוד. ותחשב.
