* ב.
** מופלא -
משמע שהם גדולים אם מביאים שערות. קשה, שעדיין צריכים שנים.
** מופלא
- מעניין שקוראים לו כן, שאולי אינו יודע להפלות. אין זה הערה, שאז אינו חל, ורק דנים במי שיודע להפלות. לכן, נקרא מופלא, שאחר לא צריך לדעת, כיון שהוא גדול. ותו"ת.
** כל בעלי
- יש לדון למה ינקט חמשה, ולא שלש או מנין יותר פחות. עיין בגיטין (םו:) שגם שם נקט חמשה.
* ג:
** שלא יהא דבר -
מרש"י (וכן מגמרא) משמע שאין בעיה בהפסק אלא במה שאינו תחת בגדיו. לא יכול ללבוש עוד בגד עליו כיון שזה יהיה ריבוי בגדים.
** ראש -
יש לדון למה אין ציץ מפסיק ברצועות שלו. צריך לומר שהיו כולם למטה מן התפילין. ותו"ת.
* ד.
** ה"נ דכל -
ר"ל, ואז יהיה הדין כל כך פשוט שאף לא צריכים משנה לו. ותו"ת. קצת דחוק, כמובן, לומר שלא נצטרך משנה. ותו"ת.
* ד:
** תפסת מועט -
מעיין שלא יכולים לומר המוציא מחבירו עליו הראיה. אולי אין הקדש נחשב המוציא, שאולי ממונו בא מיד לרשותם, ש"כל היכא דאיתא בבי גזא דרחמנא הוא.” ותחשב. גם יש לומר שאין לו דינים כממונות. ותחשב.
** ראש -
לכאורה, הענין הוא שזה קונה הראש, וזה קונה שאר הגוף. כיון שכל אחד הוא סיבה לחיות שלו, שלא היה חי בלי מה שקונה זה, אז מחמת זה יש לו דיני בעל על חציו. יש להעיר שנמצא דבר מעניין, שכיון שזה קונה שאר גוף, יכול לתת לב לזה, וריאה לזה. אם כן, לכל אחד יש דבר שגורם חיותו, ואז צריכים לשמן בין שלשתם. אם כן, יכול למעט חלק חברו. ויש לדון, שאולי כיון שחברו כבר זכה בחציו, לא אפשר זה למכור. ותחשב על זה.
* ה.
** טעי -
נמצא ש,על כל פנים בהוה אמינא, גמרא סובר שרבנן חוששים לטעות. היה אפשר לומר שאף חוששים שמא אדם יאמר כן להפליג בדברים, ולא לעשות חלות. נמצא שמניח שאין אדם עושה כך. (עיין במה שאומר רש"י לבאר המסקנא. אינו מוכרח כן, שיש לומר שמסיק שאף בזה בני אדם טועים.)
** דמי ראשי -
יותר מזה- משמע ש”אין... יותר מזה” ר"ל שהוא הכי גדול, שלכאורה כן הוא כאן באיש.
* ו.
** דבר מסויים -
אז, היה אפשר לומר שזה בדבר מסויים וזה בדבר שאינו מסויים. אולי סתימות לא משמע כן.
* ז.
** כשעמד -
קשה ל"ל מוקמים אותו כרבי יוסי. ותחשב. ושוב ראיתי ברש”י.
** עובר… פשיטא -
משמע שאם רוצה בעל, אין איסור בהריגת עובר, שאי לאו הכי, קשה למה לא נאמר שזהו החידוש. אולי רק פשוט מפני שפשוט שאף הוא חלק ממה שחייב מיתה, שהוא חלק ממנה. אולי כיון שאותו חלק יחיה לאחר זמן, אסור לחתוך אותו חלק. כמו כן, יש לומר שאסור לחתוך אבר שלא לצורך, ולכן אסור להרוג עובר. ותחשב. ויש לדון.
שוב הבנתי שאינו כן, ושענין של גמרא הוא שפסקו מיתה עלה, ואותו חיוב נופל אף על העובר, כיון שהוא חלק ממנה. אז, אף שיש איסור בהריגתה, כאן חייבים להרוג אותה.
ויש לדון מהו הדין אם נולד, שלכאורה, פסקו מיתה עלה. צריך לומר שיש שינוי שקורה כשנולד שגורם שלא ממיתים אותה. כמ"כ י"ל שמה שחייב מיתה היא אשה, ורק כשהיא חלק ממנה, חייב מיתה. ותחשב אם שנים אלו חלוקים.
צריך ביאור, אז, מהו ההוה אמינא שלא נהרוג אותו כיון שהוא ממון בעל- הרי אנו חייבים להורגו. אין לומר שאיסור היזק ידחה זה, שאיסור הריגה לא דוחה זה. נראה כמה שחדשתי במקום אחר, והוא שלא דוחה הריגת בית דין איסור להרוג, אלא שחלק מן העונש הוא שלא זכאי עוד לחיות. (ואם תאמר אם כן יהיה מותר לאחר להרוג אותו. ויש לומר שהאיסור רק נחלש. גם יש לומר שזה רק הו"א כאן, ואינו המסקנא. גי"ל שרק הותר לגבי בית דין. מעניין שיכול להיות הותר רק לגבי חד. ותחשב.)
** שבת -
אם כן, שלפעמים חי העובר יותר, יש לומר שכך קרה כשעובר פרכס אחר מיתת אמו, ולא צריך לומר שהוא כזנב הלטאה. ותחשב.
* ט:
* בעיבור שנה- היה אפשר לומר שעולא חושש שירננו בתר יום אחד, אם לא אפשר לומר שכיון ש"לא ראינו אינו ראיה,” יתלו שראו רבנן, אבל הם לא ראו. ותו"ת.י:
** בקייטא -
צריך ביאור למה חוששים שיכירו שאין ימים שקובעים לר"ח ימי מולד רק בראש השנה (שיהיו צריכים לשמור על זה כל השנה). ותחשב.
** דל ירחא -
שיתא…- לא הבנתי מה כוונת רש"י לומר כן, אבל לכאורה החשבון הוא כן: יום הנף הוא יום אחד קודם אור עיבורו, שאור עיבורו הוא שלשים ואחד בחדש. זה שלש ימים לתחלת שבוע. יום הנף הוא יום טז, שהוא שני ימים לתחלת שבוע. אם כן, אם עושים חדש אחד לפני כן מלא, אז עושים עוד חסר, שכן יכולים לעשות, כיון שבין כך ובין כך, יהיה מוטעה חצי יום. אם אותו חסר הוא בין ניסן לר"ה, אז יקדים ר"ה יום אחד- מאור עיבורו ליום הנף.
** לא קא חשיב -
ק"ק למה קחשיב שנה מעוברת.
** צריך ביאור למה לא
עושים יותר משמנה, כמו אם בשנה שלפניה עשה שמנה להיפך. וצריך לומר שרק מיירי בשני שלאחר שנה כתיקונה. וצריך באור.
** תמה -
לכאורה, לא היה הקובע את החדשים, שאילו קבע אותם, קשה למה קבע כיון שחשב שייצא ממנו רע. אולי היה שום סיבה לדחות אותו רע.
* י.
** ועיבור שנה -
קשה, שרק יכולים לעשות שנה שלפניה כן אם לפניהו היה מעובר (או שהוא היה מעובר, אלא שצריך שנעשה שהוא רק יום אחד מן המולד). אם כן, קשה. וצריך ביאור.
* י:
** קריעת ים סוף -
משמע שההלל הוא מחמת הנס, ולא מחמת החג. ויש לדון ל"ל יבוא מחמת החג.
** שני כלים -
שאבוב היה בזמן בית ראשון, ולא נשאר עד שני (ולכן לא מזכיר אומני אלכסנדריא).
* יא.
** גוזמא -
אף אם אינו גוזמא ממש (או שניהם גוזמא), נ’ שרק ר"ל שיותר נ’ כגוזמא.
** מעלים -
ואם תאמר רק מעלים מחמת זה, ואז הוא גלגל החוזר. יש לומר שאומר שלא חולקים בדין, אלא חולקים מה נהגו. ואם תאמר אם כן מאי נפק"מ. לזה אומר שיש נפק"מ למשיאים ממנו. גי"ל שדנים אם קבעו רבנן שיהיה כן כדי שיהיה עוד סימן. כמו"כ יש לומר שחולקים אם קבעו רבנן כן כיון שחשו שבית דין יטעו.
** לעולם קסבר -
לכאורה, ר"ל, “אלא לעולם קסבר….”
** לויים נתונים -
כל אלו הם רק מקור לשיר שלווים עושים; שיר אחר הוא רק לבסם קול לויים, לכאורה (ולכן א"צ לויים).
** קצת צריך
ביאור למה רש"י מפרש כמה מן ה"מהכא"ים שאומר גמרא.
** אין אדם שר
- לולי רש"י, היה אפשר לומר ששירה מביא אדם לידי שמחה וטוב לבב, ואז כיון ששרים, עובדים את ה’ בשמחה וטוב לבב.
ואגב, יש לדון מה אם לוי לא היה שמח. אולי לא היה יכול לעבוד. ויש לדון, שאולי זה רק מפרש מין עבודה, שהוא בדרך כלל בא מאדם שיש בו שמחה.
** תחת אשר לא -
אם כן, לא אורמ כמו שנוהגים בני אדם לדרוש, שצריך לעשות מצוות בשמחה, אלא רק קאי על מצוות שירה (ואף שם, נראה שהשמחה לא נצרך למצווה, אלא הוא פרט לבאר מהו המצווה). ודע שזה משמע שבשאר מצוות אינו צריך לעבוד בשמחה, שאין ללמוד תביעה של קרא זה על מה שלא נעשו בשמחה.
* יא:
** אזהרה -
גמרא זה משמע שגוזרים יותר על איסור מיתה מעל איסור אזהרה. צריך ביאור, שאומר רבה ביבמות נגד זה. ותחשב. אפשר שאזהרה ר"ל דבר שהוא מדברנן. לשון דחוק. אם כן, לא קשה עוד קושיית רש"י (שאין מקור לזה).
** ריב"ג -
רש"י רק גורס יב"ג.
** אף הם -
משמע ששיר לקרבן, ולא רק לשנות בית המקדש (שמשנה הקול שבו). כן נראה ממה שהוא רק בזמן הקרבת קרבנות.
** נפיק מיניה חורבא -
היה אפשר גם כן לומר ששאלת גמרא היה רק אם חייב או לא.
* יב:
** משמרתו של יהויריב -
היה אפשר לדחות, אולי, שהיה זמן שהיה לו להיות משמרתו. יל"ד.3		/’	//’
* יג:
** אלא בשעה -
לכאורה, ר"ל שהעבודה היחידי שהיה יכול להיות נכנס לו ולהשתתף לו היה השיר, וממילא רק עשה כן בזמן שהיו משוררים. לשון המשנה עדיין קצת מוזר.
** כדי ליתן -
לכאורה, ר"ל שכל ההיתר להם להיות משוררים הוא שנותנים תבל בנעימה. אז, רק מותרים אם שרים; אם לא משררים, אז אין היתר להם ליכנס. ונראה שאפשר שאם באים ומשוררים, אינו רק נדחה, אלא הותרה, שהבעיה הוא שיש קצת בזיון במה שמי שאינו חשוב עושה כן, אבל אם לאותו דבר שהוא עושה הוא הכי טוב, אז לענין אותו דבר, הרי הוא חשוב. ויש לדון.
** כנגד מי -
לא הבנתי את זה כל כך. לכאורה, אינו אומר שצריך כל אלו דברים, שאם כן, אינו כנגד אלו, אלא מפני אלו. ותחשב.
** ובניו -
לכאורה, מניחים שבניו היו קטנים. אין הוכחה לזה. יש להעיר שלעיל מנה בניו. גם יש להעיר יותר מזה ששם משמע שלא היו שרים, אלא היו בכלים. אין קטן משורר בכלים. ותחשב. גם ק"ק, אז, איך לא עולים למנין. ותחשב.
* יד.
** כמה נאה -
ואם תאמר הרי רק אומר שיש כותי שהוא הכי נאה. זה בהכרח נכון. ויש לומר שאף אומר עליו שדמיו יותר מערכין. ותו"ת.
** יש להעיר שיוצא
מגמרא זה שיוצא מזה שיותר קל להזכיר שם מכוער על ישראל מלהזכיר שם נאה על כנעני. ותחשב על זה. ונראה שאין זה מוזר, שמה שאין להזכיר זה על ישראל הוא מחמת שהוא יעצב בזה. אז, אם לא מזכיר על ישראל פרטי, אין בעיה. מה שאין להזכיר כן על כנעני הוא מפני שמהותו כנעני סותר קצת נאותו, ואז אין להזכיר אותו. ויש לדון, שהרי יכול להזכיר אותו אם לא מכוון לקלס את הגוי. ותחשב. ואפשר שזסה רק מפני שאומר כן להודות לה’, ונדחה אז. ותחשב על זה.
** כמה כנעני -
יש להעיר שהיה אפשר לומר על אותו אומה של גויים, שהרי יכולים לקלס גר תושב, לכאורה, שהרי מותר לתת מתנת חנם לגר תושב, וצריך לומר שאינו בכלל אותו איסור. ותחשב על זה. אולי לא רוצה לחלק בתוך אומה אחת. ותחשב.
** עין יפה -
דבר מעניין הוא שיכול אדם לשנות איך מקדיש אותו באופן שישנה מה קורה בפדיונו. ותחשב.
** פודה וחוזר -
ואם תאמר אם כן, למה צריך קרא. אולי הוה אמינא שכולו נפדה כן, ולא רק הקרקע. אז, הקמ"ל הוא ממש היפך של מה שהניח גמרא. ותחשב.
* ב:
** הכל חייבים בראיה -
ואם תאמר ל"ל אומר שהוא לרבות את הקטן. ויש לומר שקטן נאמר באותו משנה בפירוש (עיין שם). ועדיין יש לדון באחרים שיבואו לקמן בגמרא. וצריך לעיין שם.
* ג:
** נהי דאישתרי -
יש לדון אם זה אומר שאז שלא בעידן עבודה חייבים או אז לעולם חייבים. (וגם היה אפשר לומר שכהנים בא לחייב בעידן עבודה, ורק שם היה הו"א, כמו גבי מגילה.)
* ד.
** לכל ערכין -
יש להעיר שכל זה בהוה אמינא הוא. אז, אין הכי נמי, לזה בא. צריך לומר שמקשה שכל כך פשוט הוא שזה בא עד שאין הוה אמינא לזה. אולי מקשה שכיון שנשמע ממשנה אותו דין, לא צריכים דין זה (ר"ל, אולי משם הוא שכל כך פשוט הוא).
** טומטום -
יל"ד מהיכי תיתי לא. אולי היה לו לשנותו במשנה.
* ד:
** ואלא קרא למה לי -
מעניין שהוא כל כך פשוט שחייב שום ערך"ש הרי לא אמר ערך של שום אדם. אז, יהי כאומר ערך כלי, ויהיה פטור לגמרי.
** איכא דאמרי -
בפשטות, אומר שאיכא דאמרי שבא הקרא ללמד שהוא בהשג יד. ויש לדייק בלשונו, שבצד זה לא אומר ש"לומר שנידון," אלא "נידון." אולי לצד זה לא דורשים כן מאותו קרא, אלא צד זה גרס שר"נ רק אמר דין זה. אולי דורשים, אבל לא אמר ר"נ כדי לבאר מה דורשים. גם אפשר שדורשים קרא לדבר אחר (וצריך ביאור ל"ל מבאר גמרא), וזה הוא הדין מסברה. ותחשב.
* ה.
** זכר -
משמע שאם אינו חזי לעולה, לא הקדיש. ויש לדון, שרק מסיק כן אם הוא רק אבר של מה שאינו ראוי. ותחשב.
* ו.
** אין מקבלים -
היה אפשר לומר ששניהם בסוף, ואחד בדבר מסויים ואחד בדבר שאינו מסויים. ויש לדון, שאולי לשון מקבלים משמעש קאי על הכל. גם היה אפשר לומר שאחד רבי מאיר ואחד רבי יהודה, ושניהם בסוף. ותחשב.
** תניא כוותיה -
אין זה כל כך ראיה, שאינו מפרש איזה מין צדקה הוא, ואז אפשר לומר שהוא רק כשאמר "עלי." נראה שמדייק ממה שנשנה סתם. יש לדון, שנדייק מלשון נדר שמיירי בצדקה שדומה לנדר, והוא שאמר הרי עלי, ולא הרי זו. אולי ר"ל שבהנחת רבא, שיש יותר סיבה לאסור הרי עלי מהרי זו, משנה זה משמע כמה שמסיק ששניהם נכונים. ותחשב.
* י:
** והרי יציאת מצרים -
ידוע שיש כתבו שהלל של פסח הוא מדין מועד, ולא מדין נס. לכאורה, גמרא זה משמע שהוא מדין נס. ותו"ת.
* יד:
** ומפקים -
קשה, שאין גזירה שווה למחצה, ואז היו צריכים לדרוש כרבי אליעזר. נראה שכיון שיש “מכסת” ללמד, פשוט שחלוק הוא בחד דבר. מחלקתם עם רבי אליעזר יהיה, אז, באיזה דבר אחד.
** האומר בפיו -
באמת, מה שאומר בפיו הוא יותר רע, שהרי הוא אומר שזינתה. עדיין, אומר שיש רע שבא מפיו שהוא רע מן המעשה. קושיית גמרא, א"ז הוא קשה להבין, שאף אם הוא מה שתמות, הרי זה בא מפיו. ויש לומר שאין הכי נמי, אלא שאז אין לו להזכיר אותו, שזה רק מוכיח על דיבור שיש לו אותו כוח. רוב דיבור אין בו אותו כוח כלל. אז, אילו היה מחמת זה, לא היה מלמד לנו כלום. ותחשב.
* טו.
** על זה -
מעניין שיכולים לדרוש כן, שהרי דורשים אותו בקרא שאומר, “זה עשר פעמים.” אז, הקרא עצמו משמע שבא על העשר פעמים, ולא רק על זה.
* טו:
** זאת תהיה תורתו -
לכאורה, הדרשה הוא על מילת “מצורע,” שאומר “מוציא שם רע.” אז, “תורת” שדורש אינו שייך. ותחשב.
** כרבי יוסי סבירא -
נראה שאולי אינו מחלקת, אלא ר"ל שהוא ציור כמו הציור שבו התיר רבי יוסי. עיין בגמרא נדרים (ט:) כעין זה.
* טז.
** אהנו -
עיין במה שכתב. ק"ק ל"ל יכולים לומר שזה מציל על השנים אחרים (שגמרא אמר לעיל שהורג שלש). נראה שמי שמדברים עליו לא יוצל, שלא הוזק באופן רוחני מחמת רוע עבירה. עדיין יש לדון ל"ל תירץ שזה למדבר לשון הרע וזה למקבל.
* טז:
** מנין לרואה -
ואם תאמר למה ברייתא דורש שני קראי ביחד. ויש לומר שהוא מפני שהם בתוך פסוק אחד.
** ענוה -
ואם תאמר למה צווה תורה להוכיח, שבכל זמן יפטור את עצמו מחמת ענווה. ויש לומר שמחייב אם אין סיבתו לפטור א”ע ענווה. צריך לומר שמה שלא מוכיח אותו אינו מוכרח להיות ענווה, אף שהוא שלא לשמה. ותחשב על זה.
** שלא לשמה -
מעניין למה פשוט לגמרא כך, שהרי למצוות הוכחה יש מצווה לשמה. ותחשב.
** הכאה דדביתהו -
יש לדון אם ר"ל שאשת אדון הכה אותו או שאכסנאי הכה את אשתו. נראה כצד ראשון, שלא מסתבר שיקיים את אשתו כך.
** קיבל עולמו -
שאל לי אחד שר”י אומר שעונשים שלא שם לבו עליהם לא מכפרים. א”כ, שאל אם כאן צריך לשים לבו. היה נראה לומר שלא צריך, שהענין כאן הוא שאם לא באו עולמו, בא הרבה טוב לו, וקבל עולמו. ותו"ת.
* יז:
** אלא הוא למה לי -
היה אפשר לומר שדורשים “הוא” לדבר אחר, ואז לא דורשים אותו לומר שצריך להיות עני מתחילתו עד סופו. צ”ל שגמ’ סובר שהיה יותר מסתבר לדרוש שצ”ל עני מתחילה ועד סוף.
** רבי שמעון -
נראה שהוא לשיטתו, שסובר שצריך כפרה (נדרים י.).
* יח:
** עד יום -
ר"ל, אילו ר"ל עד ולא עד בכלל, היה פשוט שדן בתחילת היום, שלא כולל אותו. רק אם כולל היום, אז יש לדון כמה מן היום כולל. ותחשב על זה.
** בן שנתו -
יש לדון איך יודעים שהוא כן בכל קרבנות. אולי בכל קרבן אומר כן. וצריך לעיין.
* יט.
** עומדי מהו -
נראה שהדיון הוא אם שיטת רבי עקיבא בא ממה שמוסיף מילים או אף ממה ששינה מילים. (אבל, לולי זה, יש לומר שדן אם זה מילה משונה, או שדן מהו המשמעות מילה זה. ודע שיש לדון אם דיון גמרא הוא רק לפי ר"ע, רק לפי החולקים, או לכולי עלמא.)
* יט:
** רחבי -
לא הבנתי חילוק בין שני הצדדים. אולי יש אורך סתם ורוחב סתם, ודן מאיזה שינה. גי"ל שארוך לעולם גדול מאורך, כמו גבי חצר. ותו"ת.
** אומדנא -
קשה, שלעיל (צריך למצוא איפה ולעיין שם) אמר שהולכים אחר שעת נתינה, ואז קשה מה לנוו באומדנא אחר. ואין לומר שמסתמא לא שינה, שמקשה מציור שמת.
* כ.
** ערכי עלי -
דבר קצוב- ואם תאמר אינו מפני זה, אלא מפני שחייב כשעה שמעריך, ואז היה חי. ונראה שרש"י בא לבאר למה חייב כשעה שהעריך, והוא מפני שלא צריך אומדנא, שהוא דבר קצוב.
** מאי ניהו שעמד -
נראה שזה קשה רק למי שמוקים רישא רק בשעמד בדין, שאי לאו הכי, נוכל לומר שכפילות חלק זה של המשנה מוכיח שרישא איננו כשעומד בדין, אלא מלווה הכתובה בתורה ככתובה בשטר (או שיתומים חייבים אף במלווה על פה).
* כ:
** נתצו
- נחשד- מעננין שריש משמע שתלוי במה שנחשד, ולא במה שעבר. ותו"ת.
* כא.
** כיון שמעל -
עיין במה שבאר בלשון מעילה. יש להעיר שאומרים לשון מעילה אף כשלא יצא (כמו בהמת קדשים). היה יותר נראה לומר שמשנה דבר בחפץ, וזהו מה שגורם שנעשה חולין.
** יקריב אותו -
נראה שהלימוד הוא פשוט: הוא עשה, ובית דין כופים על כל עשה. אם כן, אין זה מלמד שכפייה עד שיאמר רוצה אני מהני, אלא מלמד שצריך לכפות. אילו לא היה אפשר לכפות, לא היה מלמד לנו שאפשר. אבל, יודע גמרא מסברה שכפייה כזה מהני. ותחשב.
** קמ"ל זימנים -
קצת משמע שפשוט לגמרא שצריך דעתו, אלא שסבר שהיה פשוט שרצה. (אולי, אז, לא צריך לשאול לו, או אולי אף אם לא רוצה, בטל דעתו.) אפשר לדחות שר"ל שקא משמע לן כן, וצריך להשמיע כן מפני ש…. כמו כן אולי מצאנו בתחילת גמרא נדה (גבי אין הלכה כהלכה שבמשנה).
* כא:
** דאירצי בשעת הפרשה -
יש לדון מה זה אומר:
1. לא צריך דעת בפירוש בשעת כפרה, שכבר גילה דעתו בשעת הפרשה. אם כן, אם יודעים שחזר בו, לא יהני.
2. לא צריך דעת בשעת כפרה, שמה שצריך שדעת יעשה כבר קרה כשהיה דעת בשעת הפרשה.
** יש לדון
אם שמואל סובר שצריך בשעת הפרשה אף אם ידוע שיש לו בשעת כפרה. (אולי רק חולק לומר שדעת בשעת כפרה מהני.)
** יש לדון
אם צריך דעת שלו כדי שקרבן ירצה או כדי שקרבן ירצה עליו. ותחשב.
** שום היתומים -
הלשון שאומר מעניין, שאין שום שלהם לאותו זמן, אלא אחר ששמים, מכריזים לאותו זמן, ושוב מוכרים.
* כב.
** כרבי מאיר -
צריך ביאור למה שאל אם ידע מה אמר רבי מאיר, וידע שאינו זה. אולי אינו מקשה, אלא גמרא חוזר ומשיב לזה.
** כיון דמשכא -
גם היה אפשר לומר שהוא  מפני שיש יותר ימים של שני וחמישי (שהם יום שהכל נכנסים, כמו שמצאנו בתחילת מגילה), ואז יותר בני אדם ישמעו.
** על מנת ליתן -
ק"ק ל"ל היה אפשר להוקים כרבי נתן, ודן למי נותן הממון, אם לבעל חוב או לכתובה, אבל עדיין הוא מחמת כתובה, וצריך לתת אותו כדי שלא ימשכו לתת מזונות.
** אלא כיון -
גי"ל שאם לא היה הדין כן, לא יזדקקו, והיתומים יהיו חסרים.
** יתמי -
אין זה סיבה, אלא זה היה דרך שלו לומר שצריכים לשלם- עד כדי כך שאם לא משלמים, ימותו.
** פריעת בעל חוב -
נראה שמה שר"ל הוא שמה שבית דין חייבים לעסק בפריעת בעל חוב אינו מדין השגחת בית דין על ממון, אלא הוא מדין השגחת בית דין על מצוות. אין השגחה זה מחייב אותם לחייב ליתומים.
** והלכתא כר"ה -
צריך ביאור למה רק מזכיר נפק"מ זה.
* כב:
** שובר -
צריך ביאור למה חשש זה חלוק מחשש שמא נתן לה ממון (ואי אפשר לומר שהוא דבר שווה במילים אחרים, שהרי רהבדר"י מקשה עליו). נראה ששובר הוא ששילם בבית דין. רהבדר"י טען שלא חוששים שעשה כן, אולי שהיינו יודעים ואולי שלא היה מחוצף לטעון עוד. אבל רהדבר"י רק חושש שמא נתן לה ממון בין שניהם. כמובן, אין חשש זה נוגע בכל ציור, שאדם נותן לאשתו כך, אבל לא נותן לכל אדם כך.
* כג.
** על דעת רבים -
עיין במה שכתבנו בחברותא קטן גיטין (א.ל.י.), שרש"י זה לא משמע כמה שכתבנו שם. צריך ביאור למה לא יכול לשאול על נדר כזה.
** הן דברי -
אין זה מוכיח שהוא אותו מחלקת, שיכול להיות שאומר שאף בזה חלקו בית שמאי ובית הלל.
** אטו -
ק"ק, שלכאורה, אם בית דין עושה שצריך לידור הנאה, אסור לעושת כן לכתחילה. נראה שבמקומות מיוחדים, כמו כאן, מותר. אבל, עדיין בית דין יעשו שצירך לידור הנאה, מחמת לא פלוג (שתקנו חכמים שצריך לידור הנאה).
** בתר עניא -
יש לדון אם זה אומר שנעשה יותר עני או שנשאר עני. ותו"ת.
* כג:
** יוסיף עוד דינר -
צריך ביאור למה צריך להוסיף דינר. ותחשב.
** איהו הוא -
צריך ביאור, שבשניהם, אדם בחר לעשות דבר. אם כן, צריך ביאור למה במצב אחד אומר שהוא הפסיד את עצמו, ובמצב אחד שומר אותו.
** רבי אליעזר -
צריך לבאר יסוד מחלקת זה (מהו החילוק בין כלים אלו לשאר כלים).
* כד:
** משנת -
אם כן, לכאורה, חולקים ב"עד ועד בכלל.” גם יש לומר שרבה סובר ששנת היובל ר"ל שנה שלאחר יובל. כמובן, קשה לומר כן. גמרא לקמן אומר שרב סובר כרבי. אז, לכאורה, הדיון יהיה אם חולקים אליבא דרבי או אם חולקים אם הלכה כרבי (או אם משנה כרבי) או לא. שו"ר ברש"י ד"ה ואנא.
ושו"ר שבפירוש בגמ’ אומר שחולקים מה אומר רבי.
** אי כרבי -
לכאורה, מגמרא יוצא שמתחילים הגרעון משנת יובל, כיון שיכול לפדות בגירוע במה שהוקדש אז. ותחשב ותבין.
** אלא לרב מאי אחר שנה -
צריך ביאור, שכבר הוקים רב משנה כרבנן, ולא כשיטתו.
* כה.
** משום דאין מחשבים -
ואם תאמר הרי זה אותו הדין. ונראה שדין ראשון אומר עצה טובה, והוא שלא לפדות אז, שיש לו לשהות עד שנה מלאה, ומפרש שהוא מפני דין זה. ותחשב. גם יש לומר שמרמז לדרשה, ואז באמת מזכיר סיבה, והוא שדרשה הוא מדיוק מ"שנים,” למעט חדשים.
* כו.
** דבר שמתנה -
לכאורה, משמע שר"ל שלומדים איך ניתן דבר זה מאיך ניתן דבר זה, שהרי שני הדברים חלוקים, במה שהם מתנה לכהנים. יש להעיר שהיה אפשר לומר שלא לומדים, אז, מפני דמיון הדברים, אלא מפני דמיון הנתינה (שעל הנתינה, באמת, לומדים). ותחשב.
** אגב,
נראה שהדיון של אם הולכים בתר שעת פדיון או לא הוא אם מה שצריך סכום מיוחד הוא כדי לשנות הקדשו (קדושתו חלוק, עד שזה יכול לעשותו חולין) או שזה יכול לפדות רק דבר מיוחד.
* כו:
** או לא -
גם היה לומר שיש צד שרק חוזר להקדש, ולא יוצא לכהנים, והוא כאילו לא הוקדש. ותחשב.
* כז.
** שאין היובל -
לכאורה, כן הוא הדין לכל דבר שאין לו פדיון קצוב. נראה שנקט שדה כיון שהיה כבר מבאר דינים של שדה.
** מצות גאולה באדון -
ואם תאמר אולי זה רק מפני שטפי ופריק או מפני שנותן חומש. ויש לומר שאין הכי נמי, אבל עדיין היה לו להזכיר אותו, שהרי הוא הציווי. (ר"ל, יש לעשות כן כדי לקיים הציוי, ולא רק לקיים הציווי הכללי של גזברי הקדש לטרוח בעד הקדש לקחת יותר ממון).
ודע שקצת קשה למה צריך קרא זה, שכמו שמשנה זה אומר, היה צריך לעשות אותו בין כך ובין כך. יש לומר שאין הכי נמי, ואינו מיותר, אלא מבאר שאם לא יעשה זה, שהוא היותר טוב…. גם יש לומר שמחמת זה יש מצווה על אדון לפדות אותו בדמים יקרים. ותחשב. אם כן, במשנה, בית דין צריכים לבוא לו ראשון מפני מצווה שלו, ולא שלהם. ותו"ת.
* כז:
** גברא בחריקין -
עיין בע"א, שאמר גמרא שמצווה בבעלים. אז, היה אפשר לומר שלכן לא יכול לומר שבא גברא במקומו. נראה שצריך לומר:
1. אולי זה רק סיבה לשאול לו ראשון (למשל, אולי יתן יותר).
2. אולי זה לא "מעכב.” ר"ל, לא כופים אותו לקנות מחמת זה, אלא לתת סכום שבו יקנה את השדה שלו.
** ולא דק -
מחודש לומר שלא דק לפרש מה שהוא גורם את הדין.
** שמגיע -
שמניח שאומר מנין מלא, ואז לא יגיע לשלשים ואחד בלי הוספת דינר.
* כח.
** יותר מחומש -
לכאורה, אין זה ממש קל וחומר:
1. לכאורה, זה תקנת חז"ל.
2. רק נדע מקל וחומר שאי אפשר לתת את כולו, אבל עדיין יכול לתת יותר מחומש.
והיה אפשר לפרש (לולי רש"י) שכוונת גמרא הוא שראב"ע לא סובר שתקנו כן, אלא שמקל וחומר הוא כבר, ור"א סובר שתקנו כן. דחוק, שאז צריך לומר שדאורייתא ר"ל דאו’ ממש. אז, נראה שצ"ל כרש"י.
** קל וחומר -
נמצא שיותר טוב לתת חרם מלתת צדקה.
* כט.
** למאי דאפכיתו -
נראה שיש שני דרכים לפרש את זה:
1. רב אומר שלמה שהיו חבריו מהפכים, הרי הלכה כריב"ב.
2. רב אמר שהלכה כרבנן. גמרא אומר שהלכה כריב"ב, ומכוון לריב"ב שלו, שהוא הפך ותני בתוך משנה. (מצאנו שגמ’ עושה כן לפעמים, כמו בב"ב בפרק חזקת הבתים, שרב אומר שדבר הוא כמה שאמר רב יוסף.)
* כט:
** קרקושי -
צריך ביאור מהיכי תיתי שאף זה אסור, שאולי רק מכירה אסורה, ולא רק אומר תורה שלא צריך למכור, אלא שאסור למכור. וצריך ביאור.
** וחדא לא -
אי שמיט- צריך ביאור מתי חוזר, שרש"י מניח שיש לו זמן לאכול. לכאורה, מסתבר שרק חוזר כשמקנה אותו לו. ויש לדון, אז, מה עושה שצריך להקנות לו. וצריך לחשוב.
** וחדא
- אגב, לכאורה, דין זה מוכיח שקנין אגב לא בא מחמת סיבת הקנין על הקרקע, אלא חלות הקנין על הקרקע. ויש לדון, שאולי אם הסיבה נדחה, אז אף הסיבה על המטלטלים נדחה. ותחשב.
* ל.
** מאי בינייהו -
צריך ביאור מהיכי תיתי שרבי דן כלל בזל קרקע עצמו, ולא רק בנמכר לסכום אחר, ומהי"ת שרדבר"י דן כלל בשל רבי. ותחשב.
* ל:
** כי ימוך -
הייתי בבית הכנסת והיו דנים אם טעה בעל קורא בזה. לסוף, הסיק אחד שלא צריכים לחזור ולא יעני עוד. הערתי שבטח שיעני עוד, שכרב עבר ושנה, ולבסוף ימכור עוד, כמו שגמרא זה מפרש.
** לקולא -
יש לדון למה זה נקרא קולא וזה נקרא חומרא, שכ"א הוא חומרא לאחד וקולא לאחד. ותחשב.
** אלא נתרבה -
ודורש איזה הוא איזה מאותם קראי שם. ותו"ת.
** כסיני -
מעניין, שהוא עצמו היה המכונה סיני.
* לא.
** צד אחד -
צריך לחשוב על מחלקת זה, ולדון אם הוא כשהחזיר הריבית או לא. ותחשב.
* לא:
** דאמר ליה -
לא ממש אומר כן לו, שהרי הוא בהמה.
* לב.
** נתינה בע"כ -
לא הבנתי כל כך הצד שיהיה נתינה, שלכאורה צריך קנין המעות (על כל פנים כאן), והרי אין קנין בלי דעת לקנות. ותחשב. יש לדון איזה מן ההנחות יידחו.
** וכי איצטריך -
צריך ביאור מהו ההוה אמינא להביא ראיה מכאן, שלכאורה, פשוט לדחות כמו שדוחה גמרא, שהתקין כל מה שהיה צריך.
* לב:
** תרי ירושלים -
מעניין, אז, לרבא, שמשנה לא יפרש, אף שמפרש שאר המקומות. אולי ידוע שלא יכול להיות ירושלים הקדוש, שלא שייך דין זה גבי אותו עיר, כמו שאומר גמרא.
** מה -
צריך ביאור למה צריכים שני הקישים ללמוד כל אלו. ותו"ת.
* לג:
** איני יודע -
עיין במש"כ. גם היה מצי לומר שההכרח הוא ממה שבתים בתוך חומות יש להם דין אחר.
* לד.
** קדושיו לאו -
צריך ביאור, שזה רק יותר סימן שיהיה לו כאן, ואם כן, רק אומר שההוה אמינא הוא יותר טוב. לכאורה, צ"ב מה קשה בזה.
