** גמרא דן (ב, ג) מהו משמעות "אור." אומר ? ראיות שבקר ר"ל אור:
* ? ראיות מקראי:
"הבקר אור"
* ראיה:
כתיב, "הבקר אור…." ר"ל, הבקרו- שהוא אור-… . אז, צריך לומר שאור ר"ל בקר.
* דחייה:
"הבקר אור" ר"ל שהבקר האיר. אז, לא מפרש מילת "אור."
* ראיה:
כתיב, "וכאור בקר יזרח שמש." ר"ל שכאור, שהוא בקר…
* דחייה
ולא מדמה לאור, אלא מדמה לשעה שבו מאיר בוקר (מתחיל בוקר להאיר).
* ראיה
כתיב, "ויקרא אלהים לאור יום." אז, צריך לומר שאור ר"ל יום.[fn:1]
* דחייה
ר"ל שלזמן שמאיר ובא קראו יום, אבל לא ל"אור" עצמו.
* קושיה
הרי אף כ'', "ולחשך קרא לילה," ושם אי אפשר לפרש, כמו"כ, שמחשיך ובא קרא לילה, שעד צאת הכוכבים יום.
* דחייה
אור לא ר"ל זמן, אלא ר"ל אור ממש. ה' קרא לו וצווה אותו על יום.
* ראיה
כ', "לאור יקום רוצח… ובלילה יהי כגנב." צריך לומר שאור הוא הפוך לילה.
* דחייה
התם הכי קאמר אי פשיטא לך מילתא כנהורא דאנפשות קאתי רוצח הוא וניתן להצילו בנפשו ואי מספקא לך מילתא כליליא יהי בעיניך כגנב ולא ניתן להצילו בנפשו
* ראיה
כ', "הללוהו כל כוכבי אור." צריך לומר שאור לילה.
* דחייה
ר"ל, הללוהו כל כוכבים המאירים .
* קושיה
זה משמע שרק כוכבים המאירים מהללים את ה', אבל קרא אחר אומר שכל צבאיו מהללים.
* דחייה
לא אומר מאירים למעט כוכבים, אלא לגלות שכוכבים מאירים (שאורים נקרא אור).[fn:2]
* ראיה
מיתיבי {איוב ג-ט} יחשכו כוכבי נשפו יקו לאור ואין ואל יראה בעפעפי שחר מדקאמר יקו לאור ואין אלמא אור יממא הוא
* דחייה
התם מילט הוא דקא לייט ליה איוב למזליה אמר יהא רעוא דליצפיה הך גברא לנהורא ולא לישכחיה
* ראיה
מיתיבי {תהילים קלט-יא} ואומר אך חשך ישופני ולילה אור בעדני אלמא אור יממא הוא
* דחייה
התם הכי קאמר דוד אני אמרתי אך חשך ישופני לעוה''ב שהוא דומה ליום עכשיו העולם הזה שהוא דומה ללילה אור בעדני
* ראיה
מיתיבי ר' יהודה אומר בודקין אור (לארבעה) עשר ובארבעה עשר שחרית ובשעת הביעור מדקאמר רבי יהודה בודקין אור ארבעה עשר ובארבעה עשר שחרית אלמא אור אורתא הוא ש''מ
* ראיה
מיתיבי מאימתי ארבעה עשר אסור בעשיית מלאכה ר' אליעזר בן יעקב אומר משעת האור רבי יהודה אומר משעת הנץ החמה אמר ליה ר''א בן יעקב לרבי יהודה וכי היכן מצינו יום שמקצתו אסור בעשיית מלאכה ומקצתו מותר בעשיית מלאכה אמר ליה הוא עצמו יוכיח שמקצתו מותר באכילת חמץ ומקצתו אסור באכילת חמץ מדקאמר רבי יהודה משעת הנץ החמה אלמא אור דקאמר ר''א בן יעקב אורתא הוא
* דחייה
לא מאי אור עמוד השחר
* קושיה
אי הכי דקאמר ליה היכן מצינו יום שמקצתו מותר בעשיית מלאכה ומקצתו אסור בעשיית מלאכה נימא איהו לנפשיה הא איכא לילה דקא שרי ר''א בן יעקב
* תירוץ
ה''ק בשלמא לדידי אשכחנא דקא פלגי רבנן בין יממא לליליא (דתנן) גבי תענית צבור עד מתי אוכל ושותה עד שיעלה עמוד השחר דברי ר' אליעזר בן יעקב ר' שמעון אומר עד קרות הגבר אלא לדידך היכא אשכחנא יממא גופיה דפלגי ביה רבנן אמר ליה הוא עצמו יוכיח שמקצתו מותר באכילת חמץ ומקצתו אסור באכילת חמץ שפיר קאמר ליה ר' יהודה לר''א הכי קאמר ליה רבי אליעזר אמינא לך אנא מלאכה דרבנן ואת אמרת לי חמץ דאורייתא דעד הכא אסר רחמנא ועד הכא שרא רחמנא ואידך שעות דרבנן ואידך הרחקה הוא דעבוד רבנן לדאורייתא
* ראיה
מיתיבי אין משיאין משואות אלא על החדש שנראה בזמנו לקדשו ואימתי משיאין משואות לאור עבורו אלמא אור אורתא הוא ש''מ
* ראיה
מיתיבי היה עומד כל הלילה ומקריב על המזבח לאורה טעון קידוש ידים ורגלים דברי רבי
* דחייה
אורה שאני:
* ראיה
מיתיבי מר זוטרא המפלת אור לשמונים ואחד בית שמאי פוטרין מקרבן ובית הלל מחייבים אמרו (להן) בית הלל לבית שמאי מאי שנא אור שמנים ואחד מיום שמנים ואחד אם שיוה לו לטומאה לא ישוה לו לקרבן מדקאמר ב''ה לב''ש מאי שנא אור שמונים ואחד מיום שמונים ואחד שמע מינה אור אורתא הוא שמע מינה
* ראיה
מיתיבי יכול יהא נאכל אור לשלישי ודין הוא זבחים נאכלים ליום אחד ושלמים נאכלים לשני ימים מה להלן לילה אחר היום אף כאן לילה אחר היום ת''ל {ויקרא יט-ו} ביום זבחכם יאכל וממחרת והנותר עד יום בעוד יום הוא נאכל ואינו נאכל לאור שלישי יכול ישרף מיד ודין הוא זבחים נאכלין ליום ולילה אחד ושלמים נאכלין לשני ימים ולילה אחד מה להלן תיכף לאכילה שריפה אף כאן תיכף לאכילה שריפה תלמוד לומר {ויקרא ז-יז} והנותר מבשר הזבח ביום השלישי באש ישרף ביום אתה (שורף) ואי אתה שורפו בלילה מדקאמר יהא נאכל אור לשלישי אלמא אור אורתא הוא שמע מינה
* ראיה
תא שמע אור של יום הכפורים מתפלל שבע ומתודה שחרית מתפלל שבע ומתודה במוסף מתפלל שבע ומתודה במנחה מתפלל שבע ומתודה בערבית מתפלל מעין שמונה עשר ר' חנינא בן גמליאל אומר משום אבותיו מתפלל שמונה עשר שלימות מפני שצריך לומר הבדלה בחונן הדעת אלמא אור אורתא הוא שמע מינה
* ראיה
תא שמע דתני דבי שמואל לילי ארבעה עשר בודקין את החמץ לאור הנר אלמא אור אורתא
* Footnotes
[fn:1] דע שיש מאלו שמשמעים שאור הוא בקר, ויש מאלו שמשמעים שאור הוא יום. צריך לפרש איזה הוא. אולי רק מקשה, ולא בא לבאר מהו אור.
[fn:2] יש נפקא מינא למי שנודר מן האור.
