גמרא מזכיר ששאל ר"ס לר"א מהו הדין במי שיודע בקביעת החדש שבא לבבל. אמר לו שצריך לנהוג כבני בבל, אבל רק ביישוב.
תחילה, נדון בשיטת אביי. לאביי, יש רק דין ראשון. אז, לכאורה, צריך לומר שמה שהיה נוהג איסור היה כדי שלא לגרום מחלקת. יודעים שלאביי הדין הוא שבני ארץ ישראל חלוקים מבני בבל. בני בבל לא יכולים להקל אף בצנעה, אבל בני ארץ ישראל יכולים. כן, לכאורה, נמצא מגמרא לעיל, שאביי פירש שהיה מותר כיון שהיה מבני ארץ ישראל, אף שהיה עושה בצנעא. אם כן, לכאורה, לפי אביי, יוצא הדין כאן כמו המסקנא שם, אם נניח שאלו שידעו את קביעות הירח היו מא"י.
יש להעיר שנמצא לאביי שחוששים מחמת מחלקת אף בצנעה. אולי חוששים שמא יימצא. ותחשב. גם יש לומר שחוששים שמה שהדין הוא כן יגרום מחלקת.
עכשיו, נדון לפי רבא. לרבא, יש שני דברים שיכולים לדון בהם. לרבא, מה שמותר במדבר יהיה אולי מפני שהוא מבני א"י או אולי מפני שדעתו לחזור. מה שאסור ביישוב היה אפשר לדון אם הוא מפני שגורם מחלקת, ואולי מפני סיבה אחרת. גמרא אומר בפירוש שחוששים מחמת המחלקת. נמצא שאין חשש מחמת סיבה אחרת. אולי זה מפני שבדרך כלל, אין סיבה אחרת, או הוא מפני שאותו סיבה לא ינהוג כלל. אולי לא ינהוג כיון שהוא מבני א"י, ואולי לא ינהוג אם דעתו לחזור, ואולי לא ינהוג כיון שכאן לא תלוי במנהג, אלא בידיעה (ואף מייסדי מנהג בבל היו נוהגים כן בא"י[fn:1]). ותחשב.
* Footnotes
[fn:1] לכאורה, זה תלוי במחלקת רבי יהודה ורבנן בפירות שביעית (אם נאמר כר"ש בדר"א). אם אינו כרשבדר"א, אז אינו כשום שיטה. ותחשב.
