1. סדר ימי פסח
  1. קודם שלושים יום לפני פסח[fn:1]:
* (לפני טו אדר)
    1. כל מקום וכל זמן:
      1. בדיקת חמץ:
** יוצא מביתו לא יחזור בפסח חוזר בפסח רבא ואביי (ו.)
אם אדם
(לא יהיה בביתו מן אחר שלושים יום עד שיבוא פסח), אם
, לא חייב לבדוק. אם
, חולקים
אם חייבים לבדוק או לא.
  1. שלושים יום[fn:2] לפני פסח:
* (מטו באדר[fn:3] סוף הפסח)
    1. כל מקום וכל זמן:
      1. בדיקת חמץ:
** יוצא מביתו
אם אדם
:
1. אם אין דעתו לחזור בפסח:
  1. רבא: תלוי במחלקת רבנן ורשב"ג, שרבנן מחייבים ורשב"ג פוטר.
  2. אביי: פטור.
2. אם דעתו לחזור בפסח:
  1. רבא: חייב לבדוק.
  2. אביי: תלוי במחלקת רבנן ורשב"ג, שרבנן מחייבים ורשב"ג פוטר. (ו.)
      1. שאלה בדיני פסח:
** רבנן ורשב"ג שואלים בהלכות פסח שמשה מזהיר את בנ"י על פסח שני ביום הקרבת פסח (ו:)
חולקים
אם כבר
או רק שואלים שני שבועות לפני הפסח. מקור של תנא קמא הוא
, שהוא חדש קודם. רשב"ג דוחה שהזהיר אז כיון שעסק בדיני פסח.
  1. שני שבועות[fn:4] קודם פסח:
    1. כל מקום וכל זמן:
      1. בדיקת חמץ:
** יוצא מביתו
אם אדם
:
1. אם אין דעתו לחזור בפסח:
  1. רבא: חייב
  2. אביי: פטור.
** דעתו לחזור (ו.)
אם
בפסח: חייב.
      1. שאלה בדיני פסח:
** שואלים בהלכות פסח שני
רשב"ג מודה ש
. גמרא מביא
מקורות[fn:5] שמתחילים אז, ומסיקים במקור אחד:
1. כתיב, “החדש הזה לכם… דברו.” היה עומד בר"ח, ומזהיר על פסח (שהוא אחר שני שבועות). דוחה גמ’ מהי"ת שהיה ר"ח.
2. כתיב, “וידבר ה’ אל משה במדבר… בחדש הראשון… ויעשו בנ"י את הפסח.” דורשים מג"ש (“מדבר" מ"במדבר באחד לחדש…") שהיה מר"ח. הזהיר על הלכות פסח, אז, שני שבועות קודם. (ו:)
  1. ארבע ימים קודם פסח:
* (י ניסן)
    1. בפסח מצרים:
      1. לקיחת בהמה:
** לוקחים בהמה ארבע ימים
לפסח ומבקרים אותו ל
עד שחיטתו.
  1. ערב פסח:
* (יד ניסן)
    1. בזמן שאין בית המקדש קיים:
      1. בדיקת חמץ:
** גזרו רבנן (ד:) מקום שהיה נותן שם חמץ (ב.) (ב.) לברך בלשון עתיד (ז:) יבטל את חמץ (ו:)
לבדוק כל
’ בלילה של ערב פסח.
חלקו ראשונים
אם הוא כדי שלא לעבור אל "לא תראה" ו"לא תמצא" או מחשש שמא ימצא ויאכל חמץ. קודם שיבדוק, יברך. כיון שמברך קודם בדיקה, צ’
; כוע"מ שיכו"ל, "לבער," וחול’ אם יכו"ל, "על ביעור."
אחר שבדק,
שלו, כדי שלא יראה חמץ נאה בפסח וישהה אותו (שלא יכול לבטלו אז, כיון שאינו שלו), ויעבור על בל יראה ובל ימצא. מבטל אז, שכיון שהוא עוסק בו, יזכור.
        1. במה בודקים:
** שלש
מצאנו
דרגות של דברים המאירים לענין בדיקה:
1. יש דברים שבודקים בהם לכתחילה. זה כולל נר. נר הוא הכי טוב לבדוק בו. (ד.) גמ’ מוצא סמך לזה מכמה ג"ש שמצטרפים לומר כן. (ח.)
2. יש דברים שהם כשרים לבדיקה. זה כולל אור החמה שבא ממעלה. גמרא לא מבאר דין אור לבנה מלמעלה.
3. יש דברים שהם פסולים לבדיקה. זה כולל אור חמה שבא לצדדים (ר"ל, לצדי הארובה), וכולל אור לבנה. לכאורה, אלו פסולים כיון שלא חזקים אורם.
** אבוקה ארבע
גם פסול אור
. אף שאורה יותר חזק מאור נר, יש
טעמים לפסול אותו:
  1. לא יכול להכניסו לחורות וסדקים.
  2. אורו לאחריו.
  3. בני אדם מפחדים שילהב דברים, ואז לא בודקים יפה בו.
  4. אש שלו דולג ומרקד. (ח.)
        1. מה בודקים:
** מקום שהוא קונה ח. משכיר מקום (ד.)
בודקים כל
אם מסתבר שנתן שם חמץ. (עיין
) אם
, המשתמש בו בתחילת יד’ צריך לבדוק אותו.[fn:6]
        1. זמן בדיקה:
** לילה שני
חייב אדם לבדוק ב
. יש
טעמים לזה:
1. בנ”א מצויים בביתם אז, וקל לחייבם.
2. קל לבדוק לאור הנר (שהוא מובחר). (ד.)
** (י:) (י:)
(יש צד בגמ’ לומר שרבי יהודה דורש מ"השבתה,” שנאמר שלש פעמים שצריך לבדוק בערב, בבקר, ובשעת ביעור. דוחה גמ’ מברייתא.
.) אם לא בדק בלילה, יבדוק ביום. ר"י אומר שלא יבדוק אחר זמן איסור (עיין לקמן לזמן איסור), שחוששים שיאכל. חכמים מתירים; כיון שמאבדו, לא יאכל. אז, יבדקו עד פסח.[fn:7]
        1. עוד:
** לא חוששים אביי ורבא (ט:)
אם בדק ביג’,
שחולדה הביא לו פת ממקום שלא נבדק. אם בדק ביד’, חול’
אם חוששים (שמתוך שנתמעט הפת, מצניעים) או לא (שלא יבין חולדה).
גמ’ שם מבאר דין חששות אחרים.
      1. איסור אכילה[fn:8]:
** אסור לאכול (קז:) קודם מנחה שני
סעודה (אבל מותר לאכול דברים שלא סועדים (כגון ירקות ובני מעים) ודברים שעושים שהוא רעב (כמו יין)
) חצי שעה
. גמרא מבאר
סיבות (ועל זה תלוי זמנו).
1. אולי הוא כדי שישתמש בפסח. א"כ, מתחיל קודם זמן הק’ פסח, ואז מתחיל בחצות. (אז, “מנחה" הוא מנחה גדולה.) א"כ, אולי לא נוהג בזמן שאין בית המקדש קיים.
2. אולי הוא כדי שיאכל מצה ופסח לתאבון, ולא אכילה גסה. א"כ מתחיל בסוף שעה תשיעית, שהוא חצי שעה לפני מנחה קטנה. כן מסקנת גמרא. (קז:)
** רבי יהודה ורבי יוסי שמואל (ק.)
אם התחיל לאכול בהיתר, חולקים
אם צריך להפסיק לקידוש או לא (חול’ אמוראים אם הלכה כר”י או כר”י). אף ר"י מודה שטוב (ופוסק
שצריך) לפרוס מפה ולקדש.
      1. איסור חמץ:
** חצות שלש
אסור להיות לו ולאכול חמץ מ
מדאורייתא[fn:9]. יש
מקורות לזה:
1. כתיב, “אך ביום הראשון תשביתו שאור מבתיכם.” דורשים שזה יד’:
  1. אביי דורש כן ממה שכתיב, “שבעת ימים לא ימצא.” א"כ, א"א לבערו אז, שצ’ שכבר לא נמצא. אז, צ"ל שמכוון ליום יד’.
  2. דבי ר’ ישמעאל אומר ש"ה" מיותר של "הראשון" אומר שמכוון ליד’.
  3. רבי עקיבא מוכיח שראשון הוא יד’, שסובר שביעור חמץ צ"ל בשריפה, ואין שריפה ביו"ט.
2. רבא ורבי ישמעאל דורשים אותו מ"לא תשחט על חמץ דם זבחי,” שאומר שלא להיות לו חמץ בזמן שחיטת ק"פ, שמתחיל בחצות. (ה.)
3. רבי יהודה לומר אותו מאחד מן השלש פסוקים ("לא תאכל עליו," "כל מחמצת," ו"לא יאכל חמץ") שאוסרים אכילת חמץ. רבי שמעון חולק.[fn:10] (כח:)
** (כח.)
אם עובר, לא חייב כרת, אלא רק עובר בלאו.
** גזרו רבנן שלש
, והקדימו זמן האיסור[fn:11]. יש
שיטות בזה:
1. רבי מאיר סובר שאסור לאכול ולהנות מתחילת שעה ששית (הוסיפו שעה). גמרא מבאר:
  1. למה אסור אז:
    1. חוששים שמא יטעו בני אדם.
  2. ל"ל אסור קודם:
    1. אביי: לא טועים בני אדם שני שעות.
    2. רבא: לא טועים בני אדם בין חצות ליותר משעה אחת, כיון שחמה משנה צדי רקיע. (ואם תאמר אם כן אף לא יטעו שעה. גמ’ מת’ שבתחלת ששית, שמש קרוב לאמצע רקיע.)
2. רבי יהודה סובר שאסור לאכול מתחילת שעה חמישית (הוסיפו שני שעות). גמרא מפרש:
  1. למה אסור אז:
    1. אביי: חוששים שמא יטעו בני אדם.
    2. רבא- יש כמה מהלכים:
      1. חוששים שמא יטעו בני אדם. כן אומר אביי אליבא דרבא.
      2. חושש שמא יטעו בשעה ששית. נותנים עוד שעה (חמישית) כדי שילקטו עצים, כיון שמצוותו בשריפה. כן אומר רבא. דוחה גמ’ שבזמן ביעור, לא צריך לשרוף חמץ.
      3. חוששים לטעות של יום מעונן. כן אומר רבא.
  2. ל"ל אסור קודם:
    1. אביי: לא טעי אינשי כל כך.
    2. רבא- תלוי בכל צד:
      1. צד ראשון- לא טעי אינשי כל כך.
      2. צד שני- רק צריך שעה לעצים, ולא טעי אינשי יותר משעה.
      3. צד שלישי- זמן רביעי הוא זמן סעודה לכל, ואז מכירים בו בנ"א.
** משעה ששית
ר"י מודה לר"מ שאיסור הנאה מתחיל
.[fn:12]
1. רבן גמליאל סובר כר"י, אבל מתיר אכילת תרומה עד תחילת שעה ששית, כדי למנוע משריפת תרומה. (יב:)
** רב פוסק (יג.)
כרבי יהודה.
נמצא שכוע"מ שלא צריך לבער אותו עד תחילת שעה ששית, וחולקים מה מותר קודם לכן.
      1. ביעור חמץ:
** לבער חמץ
אחר שעת איסור הנאה (עיין לעיל), חייב אדם
שלו, שכ', "תשביתו שאור."
** שלש
חולקים איך יבער אותו. נראה שיש
שיטות:
1. רבנן סוברים שיכול לבער אותו בכל אופן שירצה. (כא.) מבאר דין של שני מיני ביעור:
  1. מפולת- זה מהני. רשב"ג אומר[fn:13] שצריך להעמיק שלש טפחים.[fn:14]
  2. פירוד והשלכה לים. חולקים רבה ורב יוסף בזה. אם עושה שניהם, בוודאי מועיל. אם נותן חיטין לשאר נהרות (לא ים המלח), שלא נמאסים ואינו מלוח, כולי עלמא מודו שצריך לפרד. אם נותן לחם לים המלח, כולי עלמא מודו שלא צריך פירוד, שנמאס והמים מלוח. אם נותן חיטין לים המלח או לחם לשאר נהרות, חולקים ר"י ורבה; רב יוסף אומר שצריך פירוד אא"כ נמאס, ורבה אומר שצריך פירוד אלא אם כן המים מלוחים. (כח.)
2. רבי יהודה סובר שקודם לזמן ביעור, צריך לבער אותו ע"י שריפה. בזמן ביעור, יכול לבער אותו בכל אופן שירצה. (כא.)
3. רבי עקיבא סובר שבכ"ז, צריך לבער אותו ע"י שריפה.[fn:15] (ד:)
המקור שביעור הוא רק על ידי שריפה הוא:
1. דורשים קל וחומר מנותר שלא נאסר ב"לא ימצא" ו"לא יראה,” ועדיין נשרף. דוחה גמרא שמה שנשרף הוא קולא, שאם לא יכול לשורפו (בזמן שהיה יכול לשורפו, שהוא כל שלשים יום קודם פסח, אם יוצא, כשאינו זמן ביעור), לא יהיה מבוער.ד
2. ורשים מה מצאנו מנותר, שאסור באכילה, והנאה, וענוש כרת, והוא נשרף. דוחה גמרא מחלב של שור הנסקל, שאסור באכילה, והנאה, וענוש כרת.
3. דורשים מה מצאנו מנותר, שאסור להותיר, והוא נבער. דוחה לשיטת ר"י, שסובר שאשם תלוי וחטאת העוף שבא על הספק נקבר ולא נשרף. (כז, כז:)
לא מבאר מוקר לחלק בין זמן ביעור לזמן אחר (לר"י).
** ביטול (מט.)
יכול אדם לבער על ידי
[fn:16], אבל חייב לבער אותו מן העולם מדרבנן (וזהו חיוב בדיקה). פטור אם הוא טורח גדול.[fn:17]
      1. איסור מלאכה:
** שני
מצאנו
שיטות תנאים:
1. רבי יהודה[fn:18] אומר שמחלקת הוא:
  1. בית שמאי אומרים שאסור לעשות מלאכה בע"פ מצאת הכוכבים.
  2. בית הלל אומרים שאסור לעשות מלאכה בע"פ מהנץ החמה.[fn:19]
2. רבי מאיר אומר שאסור לעשות מלאכה מחצות היום. (נה.)
** (נ.)
יש שנהגו שלא לעשות מלאכה מעלות עד חצות. אם אדם בא ממקום שנוהגים כן, או הולך למקום שנוהגים כן, בדר"כ צריך להחמיר.
    1. זמן שבית המקדש קיים[fn:20]:
מוסיפים על דינים של אין בית המקדש קיים:
יום זה היה יום הקרבת קרבן פסח. נבאר, אז, דיני פסח כאן:
      1. הקרבת קרבן פסח:
        1. זמן הקרבה:
תחילת זמן הקרבה נדון בגמרא זבחים:
1. רבי אושעיא  לפי בן בתירה- כשרה מתחילת היום. דורש ש"בין הערבים" אומר שכשר כל זמן שהוא בין ערב של יד לערב של טו.
2. מסקנת גמ’ לפי ב"ב; רבנן- כשרה מחצות היום (שהוא בין הערבים).[fn:21] (זבחים יא:, יב.)
** אחר תמיד ( א אביי ב. רבא ) (נט.)
מקריבים קרבן פסח
אף שבדרך כלל, לא מביאים קרבן אחר תמיד (גמרא מביא שני מקורות לזה, ומסיק באחד:
.
לומד ממה שאומר גבי תמיד ש"ש, "והקטיר עליה,” שממעט הקטרה על חברתה. גמ’ דוחה שרק נל’ שלא להק’ שלמים אחר תמיד.
דורש ממש"כ, “… השלמים עליה" שאומר "השלם עליה.”)
, כיון שבפסח כתיב "בין הערבים" ו"בערב,” ובתמיד רק כתיב "בין הערבים.”[fn:22]
. זמן הקרבת תמיד בערב פסח[fn:23] הוא מחלקת.
1. ערב פסח בחול:נשחט בשבעה ומחצה.
2. ערב פסח בשבת:
  1. תנא קמא, רבי ישמעאל (אביי), ר"ע (רבא): נשחט בשבעה ומחצה.
  2. רבי עקיבא לפי אביי: נשחט אותו בשש ומחצה, שאין נדרים ונדבות בשבת.
  3. רבי ישמעאל לפי רבא: נשחט אותו בשמנה ומחצה, כדי שלא יסריח קודם צלייתו.
3. ערב פסח בע"ש: נשחט בשש ומחצה (מקדימים שעה כיון שצריך לצלות אותו קודם שבת). (נח)
        1. סדר הקרבה:
** (סד.) (סד:) אביי ורבא (סד:) (סד:) (סד:) (סד:) (קכא.) ר"י (סה) (סד.) (סד:)
אחד קונה בהמה. אחרים מונים על אותו בהמה (עיין לקמן בדיני מנייה.) מביאים אותו לבית המקדש. לא סומכים עליו (קרבן פסח לא טעון סמיכה). הקריבו את הקרבן בשלש כתות של עשר (שכ’, “קהל,” “עדת,” ו”ישראל,” ואפשר שצריכים שלש עדות חלוקות)
. אחד מן הכתות צריך להיות בו שלשים (שאפשר ששלש העדות הנזכרות צ"ל ביחד).
בא כת ראשונה עד שננעלו דלתי היכל (חולקים
אם ננעלו בפני עצמם (שסמכו על הנס) או כהנים נעלו אותם כשהיה מלא (שלא סמכו על הנס).
תקעו כהנים והריעו ותקעו. שחט (אף זר, שזר כשר לשחוט).
היו שני שורות של כהנים (עומדים על איצטבאות מפני שהיה עזרה מלאה דם, והיו צ’ שבגדיהם יהיו עד רגלם, ויהיו נקיים) עם מזרקות (לשורה אחת היה של כסף ולשורה אחת היה של זהב; לא היו מערבים כדי לנאותו.[fn:24]
קבלו כהנים, ונתנו מזה לזה. דן גמ’ (זבחים יד) אם הוליכו ע"י הילוך רגל או יד (דן אם הלוך יד נח’ הילוך). עשו כן (בכ"כ כמה כהנים) כיון ש"ברב עם הדרת מלך.”[fn:25]
זרקו כהנים את דמו (חלקו תנאים בזבחים אם שופך שפיכה אחת או זורק שני זריקות. אם שינה את אופן זריקתו, פסול
). נשאר מאד דם על הרצפה כיון שפקקו את העזרה (
סבר שהוא כדי שיקח מן הקרקע (שכבר מקובל), ויזרוק, לכפר על מי שנשפך דמו (שאין מין מבטל מינו). רבנן סוברים[fn:26] שהוא שילכלכו בגדי כהנים בדם קדשים כשמוליכים עצים). לר"י, זרקו אותו כוס שלקחו מן הקרקע.
. כל זמן זה, לויים קוראים הלל וכופלים.
מפשיטים[fn:27] על ווי ברזל, ועל קנים שנתנו על כתפיהם.
דיני מנייה:
        1. מנין:
        2. מי צריך למנות:
** (פז.) שלש
כדי לאכול ק"פ, צריך להיות מנוי עליו.
בדר"כ, צריך דעת בפירוש לזה. יש
יוצאים מהכלל:
1. מונים על קטן בלי דעת שלו. (פח.) (ע’ בגמ’ נדרים (לו.) שמבאר שאינו צריך למנות כלל.[fn:28])
2. מונים על העבד ושפחה כנעניים בלי דעתם. (פח.)
3. מונים על אשה. צריך דעת, אבל מן הסתם יש דעת. זה רק אחר רגל ראשון, באשה שאינה רדופה לחזור לאביה. (פז.)
        1. כמה צריכים למנות:
** רבי יוסי רבי יהודה (צא.)
חולקים
ו
מתי צריכים למנות עוד בני אדם. רבי יהודה אומר שצריכים למנות אם רק אחד נמנה, שכ’, “לא תוכל לזבח את הפסח באחד.” (רבי יוסי דורש מזה שאין מקריבים ק"פ על במת יחיד.) רבי יוסי סובר שצ’ למנות אם אינם יכולים לאכול הפסח[fn:29] (אז, אחד שיכול הוא כמאה שיכולים, ומאה שלא יכולים הם כאחד שלא יכולם), כיון שכ’, “איש לפי אכלו.”
        1. מתי מונים עליו:
** (פט.)
מונים עליו כל זמן שלא נשחט, ומושכים ממנו כ"ז שלא נשחט (לרבנן) או שלא נזרק (לרבי שמעון)
אם אדם מנוי על פסח, לא יכול להיות נמנה על עוד פסח; במינוי על שני, לא נמנה על ראשון.[fn:30]
        1. ממון של מנין:
כתיב, “אם ימעט מהיות משה.” מזה דורשים: החייהו משה. חולקים בזה:
1. חד מרבה ור"ז אליבא דרבנן: דורשים להחיות (להכשיר) את השה. אז, רק קונים עצים לצלייה.
2. חד מרבה ור"ז אליבא דרבי, אידך אליבא דרבנן: דורשים להחיות (להכשיר) את השה. אף קונה מצה ומרור, כיון ששה נאכל "על מצות ומרורים.”
3. אידך לרבי: דורשים להחיות הבעל משה. אז, קונה כל מה שרוצה.
יש שני טעמים לדינים אלו:
1. משיירים בקדושת ממון (וכשקונה פסח, אינו קודש). (כן הו"א דאביי.)
2. משיירים בקדושת פסח (עד שכולם נמנו עליו והקריבו אותו, לא קדוש). (כן מסיק רב אושעיא.)
** (צ.)
יש נפ"מ אם יש לאדם כוח לתת פסח לקנות דבר (כמו מה שכ’ משנה שנעשה אתנן), שרק לשני אפשר.
        1. אין עושים חבורה שהוא:
1. כולו גרים, שמא מתוך דקדוקם שלא כהל’ יפסלו אותו. (צא:)
2. נשים ועבדים[fn:31] (מחמת זנות)  (צא.)
3. עבדים וקטנים (מח’ משכ"ז). (צא.)
4. כולו אוננים (שמא יטמא, ולא יהיה קרבנו נאכל).(צא.)
5. כולו מפקחים את הגל (ספק טומאה), שמא טמא הוא, וקרבנו נפסל.(צא.)
6. כולם בני אדם שהבטיחו אותם לצאת מבית האסורים[fn:32] (צא.)
7. חבורה שסומכים על חולה לאכילה (שמא לא יוכל לאכול). (צא.)
8. חבורה שסומכים על זקן לאכילה (מטעם חולה).(צא.)
9. חבורה שכולה נשים (או עבדים, שדינם שווה, שכל חיובי עבדים נלמדים מאשה בג”ש). זה מחלקת (עיין לקמן). (צא:)
** (צא.)
אבל, כל אלו מצרפים למנין (וצריכים למנות[fn:33]).
        1. מה מביאים:
** (צו.)
מביאים "שה תמים זכר בן שנה מן הכבשים או מן העזים.” כתיב כן גבי פסח מצרים  (שמות, יב, ה), ולומ’ ממנו כיון שהוקשו עבודות של החדש (“ועבדת… בחדש הזה").
        1. מי מביא:
הכל חייבים בפסח. יש ארבע יוצאים מן הכלל[fn:34]:
1. מי שאינו בר דעת (חרש, שוטה, וקטן). לא מצווה בשום מצווה.
2. אשה (ועבד). יש באשה שלש שיטות:
  1. רבי יוסי- חייבים לעשות בראשון (שכ’, “במכסת נפשות") ושני (שכ’, “ונכרתה הנפש") ועושים בפני עצמם.
  2. רבי יהודה- חייבים לעשות בראשון (שכ’, “במכסת") ועושות בפנ"ע, ובשני רשות הוא ואין עושים בפנ"ע (לא חייבים, כיון ש כ’, “חטאו ישא האיש,” אבל עדיין רשות הוא ומצרפים, כיון שכ’, “ככל חוקות הפסח").
  3. רבי שמעון- רשות הוא בראשון (שכ’, “איש,” וכתיב, “במכסת נפשות.”), ומצרפים, ולא עושים בשני, שכ’, “חטאו ישא האיש.”
3. מי שהיה בדרך רחוקה. חולקים מהו. יש שני צדדים:
  1. רבי עקיבא אומר שהוא "מן המודיעים לחוץ.” גמרא נותן שני הגדרות לזה:
    1. עולא אמר שהוא כל שלא יכול ליכנס בשעת שחיטה אם יוצא בתחילת זמן שחיטה. זה הליכה של חצי יום. חולקים כמה מיל הוא:
      1. עולא אומר שהוא חמש עשרה מיל.
      2. מברייתא יוצא שהוא שש עשרה מיל.
    2. רב יהודה אומר שהוא כל שלא יכול ליכנס בשעת אכילה אם יוצא בתחילת זמן שחיטה. חלקו מהו סוף זמן אכילה, אם הוא חצות (ראב"ע) או בוקר (ר"ע). לראב"ע, זה תשע שעות, ולר"ע, זה תשע עשרה שעות. אם נניח שהולך ביום כבלילה[fn:35], זה יהיה שלשים או ארבעים מיל.
  2. יש תנא שסובר שר"א סובר שהוא כל מי שהוא חוץ מירושלים. דורש ג"ש ("ריחוק מקום") ממעשר.
  3. יש תנא שסובר שר"א סובר שהוא כל מי שהוא חוץ מן העזרה. לומד כן[fn:36] ממה שנקוד על ה’ של דרך רחוקה.. (צב:, צג)[fn:37]
4. אונס. זה כולל:
  1. טמא. אין טמא יכול להקריב קרבן פסח. יש ארבע יוצאים מן הכלל:
    1. מי שרק צריך הערב שמש.
    2. מי שרק צריך הקרבת קרבן.
    3. טמא שרץ. חולקים בזה רב ועולא. רב סובר שלא מביא, כיון שכ’, “ולא יכלו… ביום ההוא,” שמשמע שביום אח"כ היו יכולים, שהיו ט"ש. אז, משמע שלא יכולים להקריב. עולא חולק. (צ:)
    4. מי שנטמא טומאת מת (ודן גמ’ אם הוא אף בשרץ) תהום (בעת טומאתו, לא היה שום אדם יודע שנטמא). זה הל"מ. (פ:, פא)
  2. מי שלא יכול לאכול קרבם פסח. חולקים רבי נתן ורבנן אם צריך רק שיהיה איש שראוי לאכול ק"פ או שיהיה ק"פ נאכל. יש נפק"מ אם נפסל הבשר. (עח:)
  3. מי שיש לו אונס אחר שמעכב אותו מלהקריב קרבן פסח.
        1. איסור אכילה:
** (מא:)
אף שקרבן פסח נקרב, אסור לאכול אותו עד שתחשך. זה נלמד מ"ואכלו אותו בלילה הזה." אז, הוא איסור עשה. לרבי יהודה, שדור שאיסוא לאו מ"לאמר," אף יש בו לאו.
      1. פסולי קרבן פסח
יש כמה דברים שיפסלו קרבן פסח. נחלק אותם לשלש חלקים:
1. פסולי בעלים. מנינו את אלו בפטורים מן הקרבן (לעיל).
2. פסולי עבודה.
  1. יש בו פסולים שנוגעים בכל קרבן (כמו אם לא זרק, או אם זר או יושב או טמא וכדומה עשה אחד מן העבודות שפסולים בו).
  2. אם חשב עליו באחד מארבע העבודות (שחיטה, קבלה, הולכה, זריקה) לשם קרבן אחר[fn:38], פסול הוא. זה הנקרא שינוי קודש. (פסולו נדרש בזבחים.) חול’ אם פסול אם לא כוון לעקור, אלא טעה.(עב.)  אף אם גם חשב עליו לשם פסח, עדיין פסול הוא. אם באותו עבודה, חשב לשמו ושלא לשמו, חולקים רבי מאיר ורבי יוסי אם כשר, כיון שתופסים לשון ראשון, או פסול, שתופסים כל מה שאמר. (נט:)
  3. אם חשב עליו למי שאינו מנוי עליו, פסול. יש שני פסולים כאן:
    1. אם חשב שיכפר בו מי שאינו נמנה עליו, פסול הוא, שכ’, “עליו.”; זה נקרא שינוי בעלים. (פסולו נדרש בזבחים.)[fn:39] פסול זה אינו אם חושב שיכפר בו פסול, ש"עליו" דומיה דידיה. חולקים אם יש פסול זה בחושב לערל (שחייב לתקן א"ע). (סב.)
    2. אם חשב שיאכלו רק בנ"א שאינם נמנים עליו[fn:40], פסול הוא, שכ’, “מכסת.” פסול זה הוא רק בשחיטה. יש שני מקורות לזה:
      1. נסמך קרא זה לקרא של שחיטה.
      2. מילת "מכסת" גם משמע שחיטה.
אינו פסול אם חשב עליו לשם מנויים ולשם אינם מנויים, שנלמד מהיקש מערל[fn:41].[fn:42]
  1. אם חשב שיאכלו בני אדם שאינם יכולים לאכול, שנל’ מאינם מנויים מהיקש (“לפי אכלו תכוסו”).. יש שני מינים, והם שווים.
      1. אסור לאכול.
      2. לא יכו לאכול.
** (סב:)
אינו פסול אם חשב עליו לשם ראויים ולשם אינם ראויים. גמ’
מביא שני מקורות, ומסיק באחד:
      1. כ’, “כל ערל,” לומר שצ"ל כולו ערלה. דוחה גמ’ שאולי ר"ל שכל מקצת ערלה פוסלת.[fn:43]
      2. כ’, “זאת" למעט מקצת ערלות.
1. בזבחים (כב:) מבאר שיש שחולקים על זה. עדיין לא יעשה כן לכת’, אבל בדיעבד מותר.
2. פסולי בהמה. יש בזה שלש:
  1. הוא בעל מום. (זה כולל מום קבוע ומום עובר.)
  2. היא נקבה.
  3. אינו בן שנה.[fn:44] (כל אלו מפורשים בקרא)
      1. קרבן חגיגה:
חייבים להקריב קרבן חגיגה בערב פסח. חלקו למה מביאים אותו:
1. יש אומרים שחיוב הוא. אז, כמו שלפעמים חייבים להביא עולה, כך עכשיו חייבים להביא שלמי חגיגה. אז, מקריבים אותו בכל שנה, ואף אם יש הרבה פסח לכל אדם, ואף אם הוא שבת, ואם אם נקרב בטומאה.[fn:45] דורש כן מ"וזבחת פסח לה'… צאן ובקר," שאומר להקריב עוד קרבן עם הפסח, והוא שלמים שבא אף מבקר וצאן. (ע:) (כן סובר יהודה בן דורתאי.)
2. צריך לאכול קרבן פסח על השובע (הוא חשיבות לו) (ע.), ולכן מקריבים קרבן חגיגה לאכול תחילה. לכן, אינו נצרך, ואין מקריבים אותו אם כבר יש לו פסח לשבע, או בשבת וטומאה. (דוחים "בקר וצאן" לומר שמלמד שמותר פסח בא לשלמים.)
גם חולקים אם יש לו דיני קרבן פסח  (בא משה זכר בן שנה ונאכל צלי ללילה אחת למנוייו[fn:46]). בן תימא סובר שיש לו דיני ק"פ, שמקיש לפסח ("זבח חג הפסח"), וחכמים סוברים שאין לו דיני ק"פ. (על"ע, שדרשה של יהודה בן דורתאי מוכיח שסובר כרבנן.)
      1. שחיטת זבח עם חמץ:
** (רש"י סג:) (סג:, סד.) (סג:)
כתיב, "לא תשחט על חמץ דם זבחי."[fn:47] אסור לעבוד (אסור לשחוט (שכתיב בקרא), לזרוק (שכ', "דם"
). חולקים תנאים במקטיר (תלוי באם הוקש לשחיטה)[fn:48].
) קרבן פסח כשיש לעובד (כן משמע קרא) או לאחד מן המנויים (שהוקש לאיסור להלין) חמץ. חולקים רבי יוחנן וריש לקיש אם עובר אם אינו עמו בעזרה או לא (שכ', "על").
חיוב זה הוא על שלש מיני קרבנות:
1. פסח ביד'.
2. תמיד ביד'. כן סובר ר"י (מסתמא חכמים חולקים), כיון שכ', "זבחי," שמרבה זבח שמיוחד לה', שהוא עולת תמיד.[fn:49]
3. כל קרבנות בפסח. כן סובר רבי שמעון (רבי יהודה בוודאי חולק עליו[fn:50], ומסתמא אף רבנן חולקים עליו), כיון שכתיב, "זבחי" שני פעמים. נותנים "י" של שניהם על אחד לעשות לשון רבים. סתירת קרא מחלק, אז, בין פסח לערב פסח. (סד.)
    1. במצרים[fn:51]:
      1. חילוקים:
הקריבו בני ישראל קרבן פסח ביד' בניסן בשנה שיצאו ממצרים.[fn:52] זה נקרא פסח מצרים. בזמן שבית המקדש קיים, מקריבים קרבן פסח אחר. זה נקרא פסח לדורות. הכלל הוא כך: ברוב דינים, פסח מצרים ופסח דורות שווים, שכ', "ועבדת את העבודה הזאת בחדש הזה," שאומר שכל עבודות של אותו חדש שווה.[fn:53] אבל , היו שלש חילוקים בין ק"פ של בית המקדש לק"פ של מצרים:
1. במצרים, הוצרכו לקנות שה מעשר לחדש. (זה כ' בפירוש.)
** (צו.)
לדורות, לא צריכים לקנות שה בזמן מיוחד. (זה נל' מ"הזה.")
1. במצרים, זריקת הדם היה כך: טבלו אגודת אזוב בדם ונתנו אותו על מזוזה, טבלו עוד ונתנו על משקף, וטבלו עוד ונתנו על משקף אחר[fn:54]. (קרא עם פרש"י)
** (צו.)
לדורות, זריקת הדם היה כך: כהן שופך שפיכה אחת על המזבח והיסוד.[fn:55] (לא מבאר גמ' מקור לחילוק.)
1. במצרים, אכלו בחפזון. (איני ידוע כל כך מהו דין זה, ומה עשו. אולי ר"ל שלבשו בגדים שיהיו לובשים אם היו רוצים לצאת מיד.) (זה כ' בפירוש.)
** (צו.)
לדורות, לא צריכים לאכול בחפזון. (זה נל' מ"אותו.")
היה חילוק אחד בין שאר דיני פסח מצרים לפסח לדורות:
1. במצרים, איסור חמץ[fn:56] נהג רק ליום ראשון. (זה נל' מ"היום.")
** (צו:)
לדורות, נוהג שבעה ימים. (זה נכ' בפ'.)
  1. פסח:
* טו' ניסן עד כא' ניסן
    1. בזמן שאין בית המקדש קיים:
      1. איסורים:
יש ארבע איסורים שנוהגים:
1. איסור אכילת חמץ. זה כתוב בפירוש בתורה. אסור לאכול כל חמץ (בין אם הוא שלו, בין אם אינו שלו; בין אם הוא במקום שלו, בין אם הוא בכל מקום).
2. איסור הנאת חמץ. אסור להנות מכל חמץ (בין אם הוא שלו, בין אם אינו שלו; בין אם הוא במקום שלו, בין אם הוא בכל מקום). חולקים בזה:
  1. רבי יהודה ורבי שמעון סוברים שיש איסור הנאה. גמרא (כא- כד) מביא שבע מקורות לזה:
    1. אומר קרא "חמץ לא יאכל.” לשון "יאכל" משמע שלא יביא להנאה המביא לידי אכילה. (כא:)
מי שלא דורש מזה סובר שאין קרא משמע איסור הנאה.
    1. מזהיר קרא שלא לאכול נבלה. מתיר אותו לינתן ולימכר. ממה שצ’ קרא להתיר הנאות אלו, לומדים שד"א שנאסר באכילה נאסר בהנאה. (כא:)
מי שלא דורש מזה סובר שאין הקרא מתיר לינתן ולמכור לגר ולינתן ולמכור לגוי. חולקים רבי מאיר ורבי יהודה בזה. כתיב, “לגר אשר בשעריך תתננה ואכלה או מכור לנכרי." חולקים רבי מאיר ורבי יהודה; רבי מאיר קורא מה שנאמר באמצע (תתננה ואכלה או מכור) עם גר ועם נכרי. אז, מתיר למכור ולתת לגר ולמכור ולתת לגוי. רבי יהודה דורש מ"או" שנאמר באמצע שלא לקרא כן. מי שלא דורש כן סובר כרבי יהודה. אז, קרא זה לא נצרך להתיר הנאה, אלא לאסור הנאות מיוחדות.
    1. מזהיר קרא שלא לאכול טרפה. כתיב, “לכלב תשליכון אותו.” “אותו" ממעט שאר דברים שאסר תורה באכילה. (כב.)
מי שלא דורש זה סובר שצריך קרא לאסור הנאת חולין שנשחטו בעזרה, אף שלא נאסרו כבר באכילה. אז, נצטרך שני מקורות, וצריכים לחפש למקור אחר.
    1. כתיב, “כל חטאת אשר יובא מדמה… לא תאכל באש תשרף.” "באש תשרף" מיותר, ודורשים אותו (ב"אם אינו ענין") לאסור הנאת איסור אכילה. (ואם תאמר אם כן גם יצטרך שריפה. וי"ל שנתמעט מ"בקדש באש תשרף,” שאומר שרק שורפים פסולי קדש.)
דוחה גמרא את זה, שכבר דורשים "באש תשרף" לומר שפסולי קדשי קדשים ופסולי אמורי קדשים קלים נשרפים. אז, אין קרא לדרוש איסור הנאה, ואין קרא לדרוש שאין צריכים לשרוף.
    1. כתיב, “ואם יותר… לא יאכל.” כיון שכבר כתיב, “ושרפת את הנותר באש,” דורשים מקרא זה (באם אינו ענין) לאסור הנאת איסורי אכילה. (ואם תאמר אם כן גם יצטרך שריפה. וי"ל שנתמעט ממש"א, “ושרפת את הנותר.”)
דוחה גמ’ ש"לא יאכל" כבר נדרש לתת לאו על כל קדשים שנפסל.
    1. דורשים קרא שנאמר ב4. דורשים ממה שאמר, “ולא תאכל" באם אינו ענין, כיון שכבר נאמר, “באש תשרף.”
דוחה גמרא שצריך כדי לייחד לאו לאותו איסור. בלי קרא זה, לא היה איסור אלא מ"לא יאכל"  (קרא של 5), והוא לאו שבכללות, ואז אין לוקים עליו.
    1. כתיב, “והבשר אשר יגע בכל טמא לא יאכל באש תשרף.” דורשים כפילות הלשון באא"ע לומר שמה שנאסר באכילה אסור בהנאה. לא צריך לכתוב לאו כיון שכבר הוקש למעשר, ובמעשר כתיב לאו כבר איסור אכילה. ואם תאמר אולי כתיב לתת לאו שני. ויש לומר שלא מניחים שקראי נאמרים לחדש עוד לאו אם יש דבר אחר לדרוש מהם. (כד.)
  1. רבי יוסי הגלילי סובר שאין איסור הנאה.
1. איסור ראיית חמץ. זה כתיב בפירוש.
2. איסור מציאת חמץ. זה כתיב בפירוש. שנים אלו הם שווים (לומ’ ג"ש בין 3 ל4), והם: אסור להיות לו חמץ שלו (או של גוי כשקיבל אחריות, שכ’, “לא ימצא,” ולא כתיב בו "לך" (ה:)[fn:57]) בכל מקום (שכ’, “בכל גבולך" (ה:)) שלו[fn:58] (ה:), אא"כ השכירו.(ו.) (אם ביטל את החמץ, אינו עוד שלו, ואינו עובר. (ו:)
אם מצא אדם חמץ בביתו בפסח, אז:
1. ביום טוב: כופה עליו כלי.
2. בחול המועד:
  1. אם הוא שלו: יבער אותו.
  2. אם הוא של עכו"ם: נותן בינו לבין שאר מקומו מחיצה ארבע אמות.[fn:59]
  3. אם הוא של הקדש: לא צריך לעשות כלום, שבנ"א כבר נמנעים מהקדש.[fn:60] (ו.)
        1. מהו חמץ:
** (מג.) (מו.)
חמץ הוא כל דבר שנתחמץ (בין מעצמו, בין מד”א, שכ’, “כי… אוכל מחמצת
). חימוץ הוא הנקרא כשבצק מסדק. חולקים רבי מאיר ורבי יהודה מתי זה קורה (עיין לקמן). אם לא נראה סדקים, אז אחר שהיית הילוך מיל"אז רואים אם  נראים סדקים בבצק שנעשה באותו זמן. אם אין בצק אחר, מניחים שנתחמץ אחר כדי הילוך מיל.
יש שני מיני חמץ:
1. חמץ. זה בצק שנתחמץ.
2. שאור. זה בצק שנתחמץ ביותר עד שאינו ראוי לאכילה, אלא להחמיץ בציקות אחרות.
          1. מחלקת רבי מאיר ורבי יהודה:
חלקו רבי מאיר ור"י מתי דבר נעשה חמץ. תחילה, צריכים לבאר שגמרא אומר שני לשונות:
1. שיאור[fn:61], שלא נתחמץ כל כך.
2. חמץ.
שאור הוא מין חמץ נוקשה. (ע"ל שנדון בחמץ נוקשה)
יש שלש ציורים:
1. בצק נעשה לח (הכסיף פניו)- כוע"מ שהוא שיאור.
2. יש שני סדקים ארוכים (קרני חגבים)- ר"י אומר שהוא שיאור (שיש רק שני סדקים), ור"מ אומר שהוא חמץ (שהתחתון נסדק מאד).
3. יש הרבה סדקים (נתערב סדק בסדק)- כוע"מ שחמץ הוא.
          1. שלש סוגי חמץ:
יש שלשה סוגי חמץ:
1. יש חמץ רגיל. הוא בצק שנתחמץ ונשאר ראוי לאכילה.[fn:62]
2. יש חמץ נוקשה. זהו בצק שנתחמץ ולא נעשה ראוי לאכילה[fn:63]. חלקו תנאים אם יש איסור בעשייתו ובאכילתו. ר"מ אוסר אותו בפירוש. רב נחמן סובר שר"א אוסר אותו (כיון שאוסר סוג שלישי בפירוש)[fn:64]. לא מבאר גמ’ מקור לזה. (מג.)
3. יש תערובת של חמץ[fn:65]. חלקו תאנים אם יש איסור בעשייתו ואכילתו. ר"א אוסר אותו בפ’. ר"י סובר שר"מ אוסר אותו (כיון שאוסר סוג שני בפירוש). מקור שלו הוא מ"כל" של "כל מחמצת.”[fn:66] (אין כרת כיון שאין מקור; באותו קרא, לא כ’ כרת.)
          1. זמנים שחוששים שדבר נתחמץ:
יש כמה ציורים שבו חוששים שדבר נתחמץ, חוץ משלש סימני חמץ שנזכרו לעיל:
1. יש מהם שהם אסורים לעשות לכתחילה:
  1. חוששים לחיטים, אף שקלויים כבר, שנתן במים. חוששים שלא נאפו טוב. (לט:) בדיעבד, מותר.
  2. אין עושים סריקים המצויירים בפסח כיון ששוהים אדם בהם. גמרא מזכיר על זה שלש דברים:
    1. זה אף למי שעושה בדפוס (ולא שוהה), שאל"ה יתמהו בנ"א על שרק של זה מותר.
    2. ר"צ מחדש שרק של נחתום אסור, ששוהה עליו. יש אומ’ שאמר שרק של נחתום מותר, שרובם יש להם דפוס.[fn:67] ויש לדון אם חולקים עליו.
    3. ר"י מחדש שמותר אם נעשה כרקיק (אינו גבוה). יש לדון באיזה ציור דן (אם הוא בציור שמודים שמותר, או אם הוא מתיר בכעין זה כל הציורים). ויש לדון אם חולקים עליו. (לז.)
בדיעבד, מותר.
1. יש מהם שאסורים לעשות ואוסרים:
  1. אין לותתים (שורים שעורים[fn:68] במים)[fn:69]. (לו., מ.) אם לתת ונתבקעו[fn:70], אסורים. חולקים אם יכולים להתירם ע"י נתנתם בחומץ. להלכה, לא מתיר. (מ.)
  2. לא תלוש אשה בחמה, שהחום יחמיץ. (מב.)
  3. לא תלוש אשה במים חמים[fn:71], שהחום יחמיץ. (מב.)[fn:72]
2. יש מהם שלא פשוט דין בדיעבד:
  1. אין נותנים שני חיטים ברותחים ביחד, שמשא ישב אחד בסדק חברו, ולא יבא מים רותחים מארבע צדדיו.[fn:73] (מ.) לא מבאר דין בדיעבד.
  2. אשה תעסוק בפת בכ"ז עד שנתבשל. (מב.) לא מבאר דין בדיעיבד.
  3. אין לשין בפושרים[fn:74]. (לו.) לא מבאר גמרא דין בדיעבד.
  4. אין לשים עיסה ביין ושמן. אם לש[fn:75] עיסה ביין ושמן, ר"ג סובר שצריך לשרוף מיד[fn:76]. חכמים מתירים לאוכלה[fn:77]. (לו.)
3. יש מהם שנדחים:
  1. חריכת שני קליות, שמא יצא מים מאחד לחברו. גמרא דוחה זה בשני דרכים. אביי אומר שחוששים לזה רק אם לא יוצא ונופל, אלא נשאר שם. רבא אומר שלא דוחים לזה, שמי פירות הוא, ולא מחמיץ[fn:78].[fn:79] (מ.) לא מבאר דין בדיעבד.
  2. ב"ה וב"ש חלקו אם מותר לאפות פת עבה (מפ’ שהוא פת שיותר מטפח) בפסח. גמרא (לז.) חושב שחולקים אם חוששים שיחמיץ. גמרא לא מבאר דין בדיעבד.
אבל, דוחה גמ’ (שא"כ נחוש אף לפחות מכך)[fn:80], ואז מבאר שהמחלקת שם הוא אם יכול לאפות הרבה פת ביום טוב או לא, שהוא טירחא.
          1. מה אינו נעשה חמץ:
לא כל דבר נעשה חמץ. יש חמש יוצאים מן הכלל:
1. דבר שאינו ממינים מיוחדים[fn:81]. לא כל מין נעשה חמץ, אלא רק חמש מינים שנקראים דגן (חטה, כוסמין,שעורה, שיפון, שיבולת שועל). ריב"ב מוסיף שני מינים (אורז, ודוחן) (לה.), אבל אין הלכה כמותו. (קיד:)
2. בצק שנעשה במי פירות, ולא במים.(לה:)  רש"י מבאר שנעשה חמץ נוקשה. גמרא מבאר דינו לקמן.
3. דבר שכבר אפוי או חלוט. (לט:) כמו"כ דבר שניתן בחומץ. חולקים אם זה רק אם נתן בחומץ בעין או אף בחומץ בתערובת. עולא גוזר על שניהם. (מ.)
4. דבר שיש עליו דלף (אם נופל דלף על אותו מקום ולא פסק, לא מחמיץ).(לט:)
5. גמרא אומר (בציור שאין כל כך עצה אחר) שיטיל בצק לצוננים, כדי שלא יחמיץ.(מו:)
          1. חמץ של מי:
כבר בארנו דין בל יראה ובל ימצא (שהוא של קונה, או דבר שהוא אחראי עליו).
** (כט.)
דין אסור אכילה ואיסור הנאה הוא כך: אסור מדאורייתא לאכול ולהנות מחמץ של ישראל. חולקים בחמץ של גוי. ראב"י סובר שדורשים ג"ש מראיה להתיר של גוי.[fn:82] אסור מדרבנן לאכול (אבל מותר להנות) מחמץ של גוי. רבא חולק. למס’, ראב”י חוזר בו, ואומר שאסור באכילה והנאה מה"ת.
נראה שכל דינים שלא בארנו הם שווים בין ארבע איסורים אלו.[fn:83]
        1. שיעור חמץ:
איסור אכילת[fn:84] חמץ הוא כזית. זה נוהג לשני מיני חמץ. דורשים א"ז ממה שקרא אחד מזכיר שני מינים, שאומר לנו ששיעורם שווה.[fn:85]
** .תמשוך.
שיעור שאור בבל יראה ובל ימצא הוא כזית. חלקו ב"ש וב"ה לשיעור חמץ
** (ביצה ז:)
        1. מי:
כל בר דעת מצווה על אכילת חמץ. יש שנים שהם חידושים:
1. אשה. הו"א ללמוד ממצה לפטור (שהו"א לפטור מצה, כיון שהוא מעשהז"ג). חייב כיון שכ’, “כל.” (מג:)
2. עבד. כל חיובים שלו נלמדים מאשה, ואז דיון של אשה נוגע אף בו.
כ"ז שווה לכל האיסורים.
        1. זמן איסור:
** (ה.)
אסור[fn:86] לאכול חמץ שבעה ימים (כ"כ בפירוש) ולילות (שהוקש למצה, ובו כ’, “בערב"). אסור להיות לו שבעה ימים (כ"כ בפירוש) ולילות (שהוקש לחמץ)[fn:87].
        1. עונש:
1. אם אדם אוכל שיעור חמץ של סוג ראשון, חייב כרת. (כ"כ קרא.) אם אדם אוכל של סוג שני ושלישי, רק חייב מלקות. (מב.) אם אדם נהנה מחמץ עובר בלאו. אם אדם יש לו חמץ, עובר בלאו שאין בו מעשה.
      1. חיובים:
יש שלש חיובים של אכילה (כל חיובים אלו הם רק בלילה ראשונה. כמו"כ, ק"פ הוא רק בלילה ראשונה):
1. מצה.
2. מרור.
3. יין.
        1. מצה:
** (מג:) (קכ.)
חייב כל בר דעת (ואפילו נשים ועבדים, שהוקש לחמץ
) לאכול כזית (שכ’ בו אכילה) מצה בליל פסח. בזמן בית המקדש, היה אדם חייב מדאורייתא. בזמן שאין בית המקדש קיים, בוודאי חייב; חולקים רבא וראב"י
אם חייב מדאו’ או מדרבנן.
** (קיט:)
חולקים אם אוכלים אחריו. רב, ולשון אחד בשמואל, אומר שיכול לאכול; לשון אחר בשמואל אומר שאסור לאכול.
** (קטו.)
צריך לברך עליו ברכת הנהנים וגם ברכת המצווה. חולקים ר"ה ור"ח אם מברך בה"נ, אוכל, מברך בה"מ, ואוכל; או שמברך בה"נ ובה"מ ואוכל.
          1. מהו:
מצה הוא לחם שלא החמיץ. יש תשעה ציורים שאינם כשרים:
1. לחם שלא בא מדבר שיכול להחמיץ. רק חמש מינים (או שבע מינים) שמנינו לעיל מחמיצים. זה נלמד ממה שהוקש לחמץ. (לה.)
2. דבר שהוא חשוב. זה נתמעט מ"לחם עוני."[fn:88] גמרא נונן שלש ציורים:
  1. חלוט.(לו:)
  2. אשישה.(לו:)
  3. מצה שנילושה ביין ושמן. (לו.) (אם נותן רק מעט, עדיין כשר. (לח:))
3. דבר האסור. רש"י מפרש שהוא מפני שהוא מצוה הבא בעבירה.(לה:)
4. לחם שאינו של האוכל. נלמד מהיקש מחלה. (לח:)
5. מעשר שני. יש שני סיבות לומר שלא יוצאים במ"ש:
  1. רבי יוסי הגלילי דורש את זה ממה שנקרא לחם עוני, שממעט מה שלא נאכל באוני. (לו.)
  2. לרבי מאיר, שממון הקדש הוא, לא יוצאים בו, שנלמד בג"ש שצ"ל של האוכל. (לח.)
** (לו.) (לו:) (לח.)
רבי עקיבא סובר שיוצא; מרבה אותו מ"מצות" (ולא סובר כר"מ שהוא ממון הקדש).
אף שר"ע דורש שצ"ל נאכל בכל מקום, מרבה מע"ש מ"מצה" כיון שנאכל בכל גבול ע"י פדיון, אם נטמא.
דן גמ’, אז, בחלת מעשר, שלא נאכל בטומאה, וחלת מעשר שלקוח, שלא נאכל בטומאה, ולא נפדה.
1. ביכורים. יש שני דרשות לזה:
  1. דורשים מ"לחם עוני" למעט מה שלא נאכל באוני. מקישים בכורים למעשר ללמד שלא נאכל באנינות.
  2. "בכל מושבותיכם" מגלה שרק יוצאים חיוב מצה במצה שנאכל בכל מקום. אין בכורים אכל אלא בירושלים. (ואם תאמר נדרש מ"לכם עוני" לפי ריה"ג, שהוקש למעשר ללמד שלא נאכל באוני. י"ל שחול’ תנאים אם מקישים, שר"ש אומר שהוקש לתרומה, ומלמד שמותר לאכול באוני. ואם תאמר עדיין צ’ שמחה, שכ’, “ושמחת.” ויש לומר שלא צ’ שמחה; רק צ’ שיהיה זמן של שמחה, שהוא בין עצרת עד החג.(לו:)
  3. הוקשה מצה למרור לומר שצריך להיות שאינו ביכורים, כמו גבי מרור. דוחה גמ’ שאם כן, צריכים ללמוד גם כן שאין במינו בכורים, כמו מרור. (לו:)
2. מצה שאינו לחם. (זה נוגע לדינים אחרים, כמו חיוב חלה, ולחמי תודה.) יש כמה מינים:
  1. מצה נא. ר"ל, מצה שכשפורסים אותו, חיטים נמשכים ממנו. (לז.)
  2. מה שנאפה בחמה. (לז.)
  3. מה שנעשה באילפס. דורשים מ"לחמכם תנור" שאין לחם אלא מה שנאפה בתנור. חולקים ר"י ור"ל בזה, שר"י מכשיר ור"ל פוסל. ר"ל רק פוסל אם מדביק ושוב מרתיח, שאינו דומה לתנור. (לז:)
אולי חולקים תנאים אם יוצאים בו אם חוזר ואופה אותו בתנור. הצד לצאת הוא שנאפה בתנור. הצד שלא לצאת הוא לדרוש מ"לחמכם בתנור אחד" לומר שלחם צ"ל נאפה במקום אחד.
** (לז:)
גמרא
מסיק שכל אופן שמבשל באילפס (כשמדביק ולבסוף מרתיח) נחשב מעשה אילפס ופסול.
  1. מעיסה וחלטה. זהו דבר שנתבשל עם מים רותחים. חולקים בזה תנאים; יש שלש שיטות: לעולם פטורות, פטורות אם נתבשלים באילפס (גמרא משמע שמניח שאם כן כל שנאפה באילפס פטורים), חייבים. (לז:)
1. דבר שלא נאכל לכל שבעה.(לח:)
2. דבר שלא נשמר לשם מצה:
** (לח.) (מ.)
כתיב, "ושמרתם את המצות," ואז צריך לשמור את המצה מצה, לשם מצה[fn:89]
, משעת תחילת עסקו, או משעת תחילת עסקו במים[fn:90].
          1. זמנו:
** (קכ.)
לא חייב אדם לאכול מצה בכל ימי הפסח, שיצא יום שביעי מן הכלל להיפטר (שכ’, "ששת ימים תאכל מצות…”), ומלמד שכל הכלל פטור.
חייב ביום ראשון, מפני שני חיובים:
1. "על מצות ומרומים." זה מחייב כל אדם לאכול מצה עם פסח שלו. חולקים הלל ורבנן מהו "עם קרבן פסח." יוצא שלש שיטות:
  1. הלל סובר שצריך לאכול אותם ביחד, שקרא אומר שצריך לאכול ק"פ על מצה ומרור.
  2. רבנן (א) סוברים[fn:91] שיכול לצאת אף אם אוכל אותם בפנ"ע, שכ’, “יאכלוהו" (בלשון יחיד). אז, רק צריך לאכול בזמן אכילת ק"פ.
  3. רבנן (ב) סוברים שצריכים לאכול כ"א בפ"ע, שאל"ה חלק ממה שאוכל יבטל חלק אחר, ונמצא שרק אכל מין הכי גדול. (קטו.)
** (קכ.) (צו.)
חיוב זה הוא רק בזמן שיש ק"פ
, אבל אף למי לערל (שכ’, “בו") ומומר "שכ’, “בו").
1. חייב אדם לאכול מצה בלילה ראשון של פסח, שכ’, “בערב תאכלו מצות.” חולקים מי מרבה קרא זה:
  1. רבא דורש לחייב אכילת מצה בזמן שאין ק"פ. (קכ.)
  2. ראב"י דורש לחייב אכילת מצה למי שנאנס ולא הביא ק"פ. (קכ.)[fn:92]
זמנו של חיוב "על מצות ומרורים" הוא, לכאורה, שווה לזמן אכילת ק"פ. לכאו', "בערב תאכלו מצות" הוא כל הלילה.
          1. איך אוכל:
** (לה.) (קטו:) (קטו:)
אדם יוצא כשנותן מצה (שאינו כבר נמוח במים
)
בתוך פיו (ולא בתוך דבר בתוך פיו
), ואף אם לא טועם אותו (כמו אם בולע אותו)
, ואוכלו.
** (קטז.)
יאכל מצה פרוסה, כיון שנקרא "לחם עוני.”[fn:93]
          1. צריך להסב לשמאלו כשאוכלו. לא יסב על גבו (רש"י כ’ שזה מפני סכנה. לבוש כ’[fn:94] שהוא מפני שאינו דרך חירות.) ולא יסב לימינו (רש"י כ’ שהוא כדי לאכול בימינו. רשב"ם כ’ שהוא מפני הסכנה.[fn:95]) ולא על פניו (כ"כ ש”ע, אבל לא גמ’, ומסתמא הוא מפני שאינו דרך חירות.). (קח.)
1. הכל חייבים להסב חוץ מ:
2. אשה אצל בעלה (חוץ מאשה חשובה). (קח.)
3. תלמיד אצל רבו (המלמדו תורה). רבה חייב ור"י פטר. (קח.)
        1. מרור:
** (קכ.)
כל אדם[fn:96] חייב לאכול כזית מרור. חיובו נלמד מ"על מצות ומרורים יאכלוהו.” אז, בזמן שאין ק"פ, רק חייב מדרבנן.
נותן לתוך חרוסת
          1. מהו:
** (לט.)
משנה מזכיר חמש מינים (חזרת, עולשין, תמכא, חרחבינא, ומרור).גמרא
מוסיף:
1. תני בר קפרא מוסיף חרחלין, ומוצאי מרור. (יש לדון אם חולק, או רק הוא שם אחר. גי"ל שלא מזכיר מרור כיון שהוא פשוט לו. מה שמוסיף אולי חולק, ואולי משנה לא מזכיר הכל.)
2. רבי יהודה מוסיף עולשי שדה. (יש לדון אם זה בכלל עולשין של משנה שלנו.)
3. רבי מאיר מוסיף עסווס וטורא ומר ירואר.
4. רבי יוסי אומר שעסווס וטורא הם דבר אחד, ומר וירואר הם דבר אחד. (מרבי יוסי יוצא שלכאורה, מה שאמר רבי מאיר, "ומר ירואר" היה אומר, “ומר וירואר.” ויש שני גי’ כאן ברבי יוסי. וע"ש.)
5. תנא דבי שמואל מוסיף חרגינים והרדופנים.
6. רבי יהודה מוסיף חזרת יולין וחזרת גלין. (אף שהיה ר"י כבר אומר דבר אחר, אולי שני תנאים הוא אליבא דר"י. גם יש לומר שמרבה כולם. ותחשב.)
7. רב אילעא בשם ר"א מוסיף ערקבלים.
8. רבי יהודה מוסיף כל שיש לו שרף (כשחותכו, יוצא משקה לבנה כחלב).
9. רבי יוחנן בן ברוקה מוסיף כל שפניו מכסיפים (אינו ירק מאד).
10. אחרים מוסיפים כל ירק מר שיש לו שרף ופניו מכשיפים. (רבי יוחנן משמע שאומר שכל מי שמונה שמות סובר כן. אם כן, לכאורה, צריך לומר שלא חולקים, ורק מונים ציורים.) רב הונא פוסק כן.
          1. איך אוכל:
דינו הוא כמצה, חוץ משני מקומות שלא יצא במרור:
1. אם לא טעם אותו. (קטו:)
2. אם אכל אותו עם חיוב דאו’ (שאז בטל). (קטו.)
** (קח.)
יש דבר שצ’ במצה, ולא צריך כאן, והוא הסבה (כיון שלא מז’ חרות, אלא צער).
          1. טבילה בחרוסת:
** (קטו:)
צריך לטבול (חלקו אם צריך לשקע כולו או רק לטבול קצת[fn:97]
) את המרור בחרוסת. יש שלש טעמים:
1. להסיר התולעות. (קטו:)
2. להזכיר הלבנים שהיו בנ"א עושים. לכן, צ"ל עב. (קטז.)
3. להזכיר תפוחים (“תחת התפוח עוררתיך"). לכן, צ”ל לבן. (קטז.)
          1. זמנו:
זמנו הוא, לכאורה, שווה לזמן מצוות קרבן פסח.
        1. יין:
** (צט:) (קח:) (קח:) (קח:)
חייב כל בן דעת (ואף עני
ואף נשים, כיון שהם היו באותו הנס
וחולקים רבנן ור"י אם יש לחנך לקטנים בזה
) לשתות רוב של ארבע כוסות של יין, בכ"א רביעית
.
מצאנו שני סיבות למה צריך ארבע כוסות:
1. כנגד ארבע לשונות של גאולה. (רש"י צט:)
2. צריך שלש כנגד שלש "כוס"ות שנאמר ב"וכוס פרעה…."[fn:98], ואחד לברכת המזון.
          1. מה:
** (קח:) (קח:)
היין ששותה יכול להיות חי ויכו"ל מזוג, אבל טוב שיהיו מזוגים.
רבי יהודה אומר שצ"ל בו טעם ומראה יין (שצ"ל אדום).
          1. אופן שתיה:
** (קח.) (קח.)
צריך להסב בשני כוסות. גמ'
מסופק אם צ' בשנים ראשונים (ששם מתחיל חירות), או אחרונים (שאז כבר משוחררים), ואז פוסק להסב בכולם.
** (קיז:)
שותים ראשון לקידוש, שני לברכת מגיד, שלישי לברכת המזון, ורביעי לברכת הלל. כיון שצריך ארבע כוסות, תקנו לתת כל אחד על מצווה.
          1. סכנה:
ואם תאמר הרי בא לידי סכנת זוגות (והרי כל אדם צריך לחוש קצת). ויש לומר:
1. כיון שהוא ליל שימורים, אין לחוש. (אם כן, מסתמא צריכים בני חו"ל להקפיד.)
2. כוס של ברכה לא מצרף לרעה (רק לטובה מצרף).
3. לא מצטרפים כיון שכ"א מצווה באנפי נפשיה (יש להם צורכים חלוקים).
        1. סיפור יציאת מצרים:
** (קטז.) (קטז:)
חייב אדם לספר מעשה יציאת מצרים (לכל מי שעמו, ואם אין אחר עמו, אף לעצמו[fn:99]), מתחילת גנות (חולקים אם זה מכוון לעבודה זרה של אבותינו או מעבדות אבותינו) ומסיימים בשבח (כנגדו, חולקים אם זה מכוון לקרבות שלנו לה' או לשחרור שלנו), ואומר דרשות של "ארמי אובד אבי."
מזכיר מצה, ומגביהו, ומבאר אותו, וכן במרור. עושה כן לפסח, אבל לא מגביה תבשיל מן השני תבשילים שצ"ל שם, שהוא רק זכר לפסח, ואינו פסח (ועוד שנ' כאוכל קדשים בחוץ).
כדי שהבנים ישמעו, עושים ארבע דברים:
1. עושים דברים כדי שישאלו:
  1. חולקים אם היה קערה (עם מצה מרור ושני תבשילים) לכל אחד או רק לאומר הגדה. מעבירים את הקערה מלפני מי שאומר את ההגדה. (קטו:)
  2. מטבלים שני פעמים. (חולק ר"ל על זה, ואומר  שמטבלים שני פמעים כיון שמצוות צ' כוונה.) (קיד:)
2. אם לא שואלים מעצמם, שואלים להם חמש שאלות (יש תנאים שאומרים שיש רק ארבע (ע.)).
3. נותנים להם קליות ואגוזים. (קט.)
4. מכינים מבעוד יום, כדי להתחיל מוקדם. (קט.)
    1. בזמן שבית המקדש קיים:
מוסיף על דינים שבארנו דיני קרבן פסח:
      1. אכילת קרבן פסח:
** (רש"י ע.) (קיט:)
כל שהיה חייב להקריב קרבן[fn:100] פסח חייבים לאכול כזית צלי[fn:101] מקרבן פסח על השבע (כיון שמראה חשיבות
) שנמנה עליו. שמואל ור"י אומרים שלא יאכל אדם אחר קרבן פסח (כדי שטעמו יתקיים בפיו). רב מתיר.
        1. מה:
חולקים רבא ורבה במה מקיים מצוות אכילה:
רבה:
1. תנא קמא- כל שנאכל בשור הגדול ע"י בישול רגיל נאכל בגדי הרך.
2. יש אומרים- סובר כת"ק, אלא שמוסיף אף ראשי כנפים וסחסוחים.[fn:102]
רבא- כל שנאכל בשור הגדול על ידי שליקה, נאכל בגדי הרך (ואף ע"י בישול). זה כולל ראשי כנפים וסחסחים.
** (פד.)
חולקים רבי יוחנן ור"ל אם אוכלים  גידים הרכים שסופם להקשות או לא. ר"י חזר לומר כר"ל.[fn:103]
** (פג:)
רב אמר שכל הגידים נאכלים חוץ מגידי צוואר[fn:104].
        1. זמן:
חולקים רבי עקיבא וראב"ע עד מתי אוכלים ק"פ מדאורייתא. מזכיר גמרא שלש מהלכים, לכאורה, בביאור המחלקת:
1. רבי אליעזר סובר שנל' מ"בלילה הזה" בג"ש ממכת בכורות. רבי עקיבה סבר שמ"חפזון" נלמד שנאכל עד שעת חפזון, דהיינו בוקר.
נמצא מגמרא ארבעה קראי:
1. בלילה.
2. הזה.
3. חפזון.
4. בקר.
לראב"ע, ראשון לג"ש, שני לג"ש (אותו ג"ש), שלישי לא נדרש, ורביעי נדרש לגלות שקרבן פסח נאכל רק לילה אחרת (אינו כשאר קדשים קלים שנאכל לשלש עונות).
לר"ע, ראשון נדרש למעט אכילה ביום שלאחריו, שני נדרש למעט אכילה בלילה שלאחריו, שלישי נדרש לסוף זמן אכילה, ורביעי לא נדרש.
1. כ', "בערב כבוא השמש מועד צאתך ממצרים." בערב, זובחים, ובבא השמש אוכלים. חולקים ראב"ע אם "מועד צאתך, אומר זמן שריפה או זמן סוף אכילה.
2. כולי עלמא דורשים מ"חפזון." ראב"ע סובר שמכוון לחפזון של מצרים במכה, ור"ע סובר שמכון לחפזון דבנ"י ביציאה. שאר דרשות שב1 יהיו, אז, כמה שכתבנו שם לר"ע.[fn:105]
** (ברכות ב.)
מדרבנן, כולי עלמא מודים שלא נאכל אחר חצות, שאם נאכל אחר חצות, חוששים שלא יאכל קודם עלות השחר.
        1. הלל:
** (צה:)
כשאוכל אדם את קרבן הפסח, צריך לומר הלל, שכ', "השיר יהיה לכם…."
      1. איסורי קרבן פסח:
        1. אכילת כשאינו צלי:
יש שלש איסורים:
1. יש איסור לאו לאכול ק"פ שלא נצלה. רבא ולשון ראשון של אביי אומר שלוקים ע"ז. לשון שני של אביי פוטר, שאינו מיוחד כלאו של חתימה, שממנו נל' מכות. (מא:). צלי כולל צלייה על גב אש ועל גב גחלים (חולקים אמוראים אם זה רק בגחלים של עץ או אף בשל מתכת[fn:106]). לא כולל צלייה על תנור שגרף, מח' כפל "צלי אש." (עה.)
2. יש איסור לאו לאכול ק"פ נא. מ"נא ומבושל" דורשים שרק אסור אם בישל קצת[fn:107] (מא.)
3. יש איסור לאו לאכול ק"פ מבושל, בין במים בין בשאר משקים (רבנן דורשים אותו מקו"ח, שמים לא מפיג טעמו, ורבי דורש אותו מ"בשל מבושל." נמצא שיחלקו אם יהיה פטור אם מבשל ברוטב שלו או יהיה חייב.) אם צלאו ובשלו, חולקים. יש דורשים מ"בשל מבושל" לחייבו[fn:108]. יש דורשים מ"נא ומבושל" לפטור אותו. אם בשל וצלה, חייב. (מא.) אין סיכת ק"פ נחשב בישול. (מ:)
אם אכל עובר על שני או שלישי:
1. רבא- לוקה שנים, מחמת לאו ראשון והוא.
2. אביי- לוקה אחת, מחמת הוא. (מא:)
** (מא:)
חולקים רבי ורבנן אם חייב אף מבע"י (כיון שכ', "ובשל מבושל[fn:109]) או פטור (כיון שכ', "כי אם צלי אש").
** (עה.)
מפני איסורים אלו, יש דרך מיוחד לצלות. צריך לצלות בשפוד של רמון, או בשפוד של מתכת שלא נוגע בתוכו[fn:110]
(ולר"י, אף אם נוגע בתוכו). שאר עצים פסולים מאחד משלש טעמים:
1. יש שיש להם שורות, ומבין השורות יוצא מים. אותו מים חם (כיון שהשפוד על האש), ומבשל את הפסח. דקל פסול מחמת זה. פסול זה לא נוגע ברמון.
2. יש שיש להם מוח. אותו מוח גורם שהשפוד מבשל את קרבן הפסח. תאנה פסול מחמת זה. פסול זה לא נוגע ברמון.
3. יש שאינם חלקים. כדי לעשות שהם חלקים, צריך לחתוך החלק שאינו חלק. אז, יצא מים משם, ואז נמצא שלא צולה ק"פ. רוב אילנות פסולים מחמת זה. ברמון אין לו פסול זה, באחד משני אופנים:
  1. חלק שאינו חלק הוא קטן, ולא צריך לחתכו.
  2. קטני רמון אין להם אותו חלק שאינו חלק. אז, לא צריך לחתוך.
** (עד.)
חולקים רבי יהודה ורבנן אם צולים על מתכת (ולא מביא חום לתוכו) או לא (שמביא חום למה שבתוכו, ונמצא שאינו צלי אש).
** (עד.)
רבי יוסי הגלילי סובר שנצלה עם מעיו בתוכו[fn:111]. ר"ע סבר שאז מעיו מבשלים אותו, ואז נותנים אותם למעלה מראשו.
        1. נותר:
** (פד.)
אסור להותיר קרבן פסח (ולא לוקים עליו, כיון שאין בו מעשה וניתק לעשה
) אחר זמנו (באנו לעיל מהו זמנו).
** (פג.) (קכ:) (פג:)
בשר (כל מה שנאכל) שנותר, וכן מה ששמשו
, טמא (כדי שלא יעצלו כהנים)
, וצריך לשרפו בבקר שני (שכופל לכ' בקר, או שכ', "עולת שבת בשבתו," שממעט עולת חול ביו"ט[fn:112], או שכ', "הוא לבדו," או מפני שאסור לשרוף ביו"ט, שהוא איסור לאו ועשה
).
בדר"כ, שורפים בחצרותיהם מעצי עצמם (לא יקחו עצי הקדש, שמא יטלו יותר מן הנצרך). יש שני יוצאים מן הכלל:
1. ציקנים (צרי עין) שורפים לפני בירה[fn:113] בעצי הקדש (לא עצי עצמם, שגורם שבנ"א יחשדו שנוטלים עצי הקדש הנשארים אחר ששורף). (פא:)
2. אכסנאי. חולקים אם זה רק אם כבר החזיק בדרך או לא. (פב.)
(אסור לאכול נותר, כמו שאסור לאכול כל קרבן פסול וכמו שאסור לכל מי שאסור לאכול קרבן לאכול קרבן פסח.)
        1. שבירת עצם:
** (פד)
אסור לשבור עצם של פסח טמא. דורשים למעט- רבנן דורשים מ"בו," למעט פסול, ורבי דורש מסמיכתו לאכילה למעט מה שאינו ראוי לאכילה. גמרא
ממשיך מזה לבאר דין של כמה ציורים:
** (פד)
דן גמרא
בכמה ציורים למצוא נפקא מינא:
1. שבירת עצם של פסח הבא בטומאה. רבי ירמיה אומר שרבי יחייב ורבנן יפטרו. חול’ יאמרו שכוע"מ שפטור. (לכאורה, סובר שרבי דורש שני הקראי, ורק מקיל עוד על ידי קרא שני. יל"ד מהי"ת.)
2. שבירת עצם של קרבן שנפסל אחר שהיה לו שעת הכושר. רב יוסף אומר שרבי יפטור, שלא נאכל ורבנן יחייבו, שהיה כשר. חול’ יאמרו שכוע"מ שפטור, כיון שעכשיו פסול.
3. שובר עצם של פסח לפני ליל טו. רבי פוטר, שלא נאכל ורבנן מחייבים כיון שכשר הוא. חול’ יאמרו שכוע"מ שחייב, כיון שיהיה ראוי לאכילה.
4. שובר עצם שיצא מקצתו. צריך לקלוף בשר ולחתוך את העצם. מה שלא יצא, אז, אינו ראוי לאכילה, אבל הוא כשר. אז, רבי יפטור ורבנן יחייבו. חול’ יאמרו שכוע"מ שפטור, כיון שאותו אבר פסול.
5. שבירת עצם בנא. רבי פוטר, שלא נאכל, ורבנן מחייבים, שכשר. חול’ יאמרו שכוע"מ שחייב, שנאכל אם צולה אותו.
6. שבירת אליה, שאינו נאכל, אלא הולך לגבוה. רבי פוטר, שלא נאכל, ורבנן מחייבם, שכשר הוא. חול’ יאמרו שכוע"מ שפטור, כיון שלא נאכל כלל. (צריך ביאור מהי"ת לרבנן שפטור אם לא נאכל כלל.)
7. שבירת עצם שאין עליו כזית בשר. רבי פוטר כיון שלא נאכל ורבנן מחייבים כיון שחייב. חול’ יאמרו שכוע"מ שפטור כיון שאין עליו שיעור אכילה.
8. שבירת עצם שאין עליו כזית במקום שבירה אלא במקום אחר. רבי יפטור, שאין אותו מקום ראוי לאכילה, ורבנן יחייבו כיון שכשר. לא מפ’ גמ’ מה יאמר חול’.
        1. אכילה בשני מקומות/ אכילה בשני חבורות:
כתיב שני פסוקים: "בבית אחד יאכל," ו"על הבתים…." אחד אומר לנו שמותר לאכול קרבן פסח במקומות הרבה ואחד אומר לנו שאסור. חולקים רבי יהודה ורבי שמעון בזה:
** (פו)
רבי יהודה (וכן הלכה) סבר שיש אם למסורת, ודורשים שראשון אומר שבבית אחד יאוכל, ולא יאוכל אדם משני חבורות. רבי שמעון סובר שיש אם למקרא, ודורשים שראשון אומר שבבית אחד ייאכל, ולא מחלקים חבורה לשני מקומות.
** (פו:)
דן גמ' אם עשיית מחיצה וסילוק מחיצה נחשבים עשיית שני מקומות.
** (קכ:)
אם ישנו כל החבורה, נחשבים חבורה אחרת (ולר"י לא יאכל). אם נתנמנמו ("נים ולא נים…") מקצתם, לא נחשבים חבורה אחת. אם ישנו כולם, חולק רבי יוסי ורבנן אם נחשבים חבורה אחרת או לא. הלכה כרבי יוסי.[fn:114]
        1. הוצאה:
** (פה:)
אסור להוציא (לעקור ולהניח) את קרבן הפסח חוץ מן הבית שבו נאכל.
  1. אחר פסח:
* מכב' ניסן והלאה.
    1. בכל מקום וכל זמן:
      1. חמץ שעבר עליו הפסח:
חולקים רבי יהודה ורבי שמעון אם חמץ שעבר עליו הפסח אסור בהנאה (דורש אחד מן השלש פסוקים שאוסרים אכילת חמץ) או מותר אף באכילה.
** (כט.)
לעיל, הזכרנו שיטה שהוקש אכילת חמץ לבל יראה, ולכן של גוי מותר. לא גזרו רבנן על של גוי שעבר עליו הפסח, אף שגזרו באכילת חמצם בפסח.
  1. פסח שני:
* טו' אייר
אם אדם לא הקריב קרבן פסח, צריך להקריב קרבן פסח שני.
** (צה.)
מצאנו חמש חילוקים בין פסח לפסח שני (והכלל הוא שיש לפסח ראשון כל דינים של גוף הפסח, ולא שאר דינים). הכלל כאן הוא כך: כתיב בפסח שני לעשות "ככל חוקות הפסח." אבל, אינו ממש; דורשים (חולקים אם הוא ממקרא מיותר לשבירת עצם או מ"יעשו אותו"
) שרק דומה לו במצוות שבגופו. יש כלל ויש פרט בכל מין מצווה (עשה, לאו הניתק לעשה, ולאו) להורות שיש למעט אחד מכל מין. אז, מזה דורשים שלש חילקוים:
1. פרט של העשה ממעט עשה של השבתת חמץ בפסח שני.[fn:115]
2. פרט של לאו הניתק לעשה (לאו שאין בו מלקות) ממעט בל יראה ובל ימצא בפסח שני.
3. פרט של לאו ממעט איסור לשחוט על חמץ.
** (צה)
יש עוד מיעוט, והוא שלא צריכים הלל באכילת קרבן פסח. בפסח ראשון, צריכים הלל באכילתו. חילוק זה נלמד ממה שמלמד הלל מלמד רק ב"ליל חג."
יש שני חילוקים שהם מחלקת:
1. פסח צריך לינה (צריך שישאר בירושלים בלילה ראשונה של פסח, אחר הקרבת פסח). חולקים אם פסח שני צריך לינה. (צה:)
2. פסח נקרב בטומאה (אם רוב ציבור טומאה). חולקים אם פסח שני נקרב בטומאה. (צה:)
* Footnotes
[fn:1] יש לדון אם זה ימים לפני הפסח או לפני יום הקרבת הפסח. לשון גמרא (קודם הפסח…) משמע שהוא שלושים יום קודם חג הפסח. יש לדחות דיוק הלשון, וגם יש לדחות שזה רק בזמנינו שאין לנו קרבן פסח. (ויש לדון, שאולי היה לנו לחוש שיחזר בית המקדש ונקריה קרבן פסח.)
[fn:2] באמת השיעור הוא חדש, שהרי נלמד הוא מהכרזה על פסח שני ביום הקרבת פסח. לכאורה, לא מוכרח להיות שלושים יום, שתלוי בקביעות החדש. אולי ידוע לגמרא שהיה, באותו שנה, שלשים יום. ותחשב.
[fn:3] כן נראה לנו פשטות השיעור, שלומד ממה שהזהיר על פסח שני שלושים יום קודם לו, שהיה ביום הקרבת פסח. אם מצאנו שהזהיר על יום יד ביום יד, אז יזהיר על פסח, שהוא טו, ביום טו. אבל, חושב אני שפוסקים לא אמרו שיעור זה. יש לומר שני פשטים למה לא יהיה כן:אולי אותו שנה היתה חדש מליאה, ועכשיו היא חסרה. יש לדון במציאות זה.אולי צריך לדרוש שלשים יום קודם הקרבת הפסח, ולא קודם יום פסח.
[fn:4] שני שבועות כוללים אותו היום שבו עומדים, אבל לא כולל יום פסח (שהרי נלמד משאלה בראש חדש). יש לדון אם הוא מפני ששני שבועות ר"ל שלמים בסופם או מפני שצריך שני ימים עד יום הקרבת הפסח.
[fn:5] מקורות אלו מוכיחים שני דברים:מוכיחים שצריך לשאול אז.מוכיחים שלא צריך לשאול קודם לכן, שהרי רק אז מתחילים לדון בהלכות פסח. לא נראה שגמרא מנסה להביא ראיה זה, לשני טעמים:לא אומר אותו כשאומר למה לא לומד רשב"ג מקרא של חכמים.לא שואל איך חכמים ידחו אותו.צריך ביאור למה אינו ראיה. נראה שני צדדים:אולי אין הכרח שיהיה ציווי בשעת שאלה (אלא רק שאלה בשעת שאלה, ואם ה’ רוצה לחדש ציווי, יכול לחדש בכל זמן שרוצה). אבל, אם יש ציווי, מוכרח שהוא זמן שאלה.אולי אף שכתיב שה’ אמר כן בראש השנה, אף אמר כן קודם לכן, ורק חדש לומר אותו שני שבועות קודם. נמצא שה’ אמר להם חדש קודם ושני שבועות קודם באותו שנה.
[fn:6] גמרא לא מבאר דין מי שקנה בתוך יד’, אם גם שם הדין הוא שמי שקנה אותו בתחילת יד’ צריך לבדוק.
[fn:7] איני יודע למה לא יבדוק אחר שתחשך. נראה שאז אומרים שאין מעלה לבדיקה (ויש רע, שאולי ימצא), שאם לא מוצא לעולם, הרי לא ימצא, ולא בא רע, שלא אכל חמץ מחמת שלא בדק, ואם מוצא, מה טוב היה בא מבדיקה, שהיה מוצא אז. אבל, אם בדק לפני כן, בדק בזמן שלא אפשר לחייב כרת.
[fn:8] עיין בגמרא (קז:) וברשב"ם שלא כל כך פשוט שנוגע בזמן שאין בית המקדש קיים. אבל, כתבנו אותו כאן מחמת מסקנה של גמרא.
[fn:9] יש מן המקורות שנביא שמשמעים שהאיסור הוא להיות לו, אבל לא לאכול. גמרא לקמן (כח:) יאמר שיש איסור לאכול ולהנות, וכמו כן יאמר משניות. לכאורה, תלוי במקור, שאם לומדים מ"לא תאכל עליו…,” (וכן דורש גמרא לאותו שיטה לקמן (כח:)), אז אסור באכילה והנאה, ואם דורשים מ"תשביתו,” יהיה אסור בקיום. אז, אפשר שיש שדורשים יותר מאחד מן הדרשות האלו.
[fn:10] יודעים שמתיר באכילה והנאה אז. אולי עדיין אוסר להיות לו. אז, אפשר שדורש קרא ראשון או שני.
[fn:11] זה בוודאי לאיסור אכילה והנאה. לא מבאר איסור להיות לו. יודעים שהוא מותר עד שעה ששית, אבל לא יודעים שהוא אסור, אז, שאולי "שורפים" רק ר"ל שהוא איסור הנאה, ואין נהנים ממנו.
[fn:12] יש לדון למה. אולי הוא מפני שאינו איסור כרת.
[fn:13] ויש לדון אם חכמים חולקים עליו.
[fn:14] השיעור הוא שלא יחפש כלב אחריו. יש לדון אם הוא כדי שלא יחפש כלב אחריו או לסיבה אחרת.
[fn:15] נראה שכן סובר, שהרי מוכיח שקרא שאומר להשבית לא קאי על יו"ט ממה שצריך לשרוף, אף שאותו השבתה של יו"ט יהיה השבתה בזמנו (ועדיין אפשר להשבית בביעור קודם שבת). אז, צריך לומר שחולק על רבי יהדוה.
[fn:16] כן אומר גמרא, אבל נראה שזה רק לפי רבנן, אבל לא לפי רבי עקיבא, שאינו שריפה. אז, הוא ככל אופן שמוציא אותו מרשותו.
[fn:17] עיין שם, שמבאר ציורים.
[fn:18] לא קל לראות מן הגמרא מי סובר מה. כן כתבנו שיטות אלו, אבל לא מוכרח כן.
[fn:19] עיין בדף ב:, שכ' שם שראב"י סובר שמתחיל משעת האור. שם, דן אם ר"ל מעלות השחר או מצאת הכוכבים. לכאורה, למסקנת גמרא שם שאור ר"ל לילה, צריך לומר שהוא כצאת הכוכבים (אם לא שנאמר שלפעמים אומר כן ולפעמים אומר בקר). על כל פנים, אם כן, מסתמא סובר שכן אומר ב"ה, שלכאו', לא פוסק כב"ש. אם כן, יש עוד שיטה.
[fn:20] עיין בסוף זבחים, שצריך שיהיה במת ציבור, שעל במת יחיד לא מקריבים פסח, כיון שאינו נידר ונידב. היה זמן אחד שהביאו אותו בלי מזבח ציבור, וזה היה במצרים, שכל אחד הקריב פסח מצרים בפ"ע, ונתנו את דמו על מזוזות ומשקוף, ולא הקריבו אימורים.
[fn:21] לכאורה, כמו מנחה, צריכים לשהות חצי שעה מפני הספק. אז, רק כשר משש שעות וחצי. (נח.)
[fn:22] יש לדון, שהרי בתמיד כתיב "השלם עליה.”
[fn:23] אינו כן ביום רגיל, שאז נשחט בשמונה ומחצה. גמרא (נח.) מביא שני דרשות לזה, ומסיק באחד. (א. דורשים מ"בין הערבים" שחולקים הערב לשני עירובים. דוחה גמרא שאם כן יהיה זמנו קבוע כן בכל יום. ב. מאחרים אותו כיון שאי אפשר להקריב נדרים ונדבות אח"כ.)יש אומרים שיש תנא שסובר שבשבת מקדימים אותו שעה, שאין מקריבים נדרים ונדבות. החולקים סוברים שהובא בשמונה ומחצה כמו בחו"ל.
[fn:24] גמרא גם מצדד שהוא כדי שלא יורידו בקדושה ויקבל כסף ויחזיר זהב, אבל דוחה כיון שבי"כ ובי"כ אולי יוריד אם נוטל מפסח של מאתים ומחזרי של מנה. ק"ק ל"ל אומרים שיתקן ככל יכולתו.
[fn:25] צריך ביאור למה עשו כן במצווה זה יותר מבשאר מצוות. ותחשב.
[fn:26] צ"ב ל"ל יסברו כר"י, שאף שסוברים שמין מבטל את מינו, סוברים שאין עולים מבטלים זה את זה. אולי לא מניחים שנפל דם או לא מניחים שנתקבל מה שעל הקרקע.
[fn:27] יש לדון אם עדיין קוראים הלל כשמפשיטים.
[fn:28] יש להעיר שגמרא אומר דין זה גבי בנו ובתו. לפי מה שאומר אותו גמרא, לכאורה, כן יהיה בכל קטן. אולי הוא דין דרבנן. כן משמע מאותו גמ’ בנדרים.
[fn:29] יש לדון מה סובר רבי יהודה אם יש מאה ולא יכולים לאכול את הפסח. לכאורה, יהיה צריך למנות עוד כדי שלא יהיה נותר. אבל, אם הוא כל כך פשוט, קשה למה צריך קרא לרבי יוסי. נראה שעיקר חידוש של הקרא, לרבי יוסי, הוא להוציא מרבי יהודה, ולומר שכל שיכול לאכול מונים עליו. ותחשב.
[fn:30] נראה שכן יוצא מפח:
[fn:31] יש לדון אם אוסר כל חבורה שיש בו נשים ועבדים או רק חבורה שהוא כולו נשים ועבדים.
[fn:32] גמרא (צא.) מעורר שזה רק בשל גויים (אבל בשל בנ"י, יודעים שישחררו אותו), ורק אם הוא חות מירושלים (אבל בירושלים, יאכל, שיביאו לו).
[fn:33] אין לי ראיה לזה חוץ ממן הסברה.
[fn:34] יש מאלו שאין יכולים להקריב, ויש מהם שהם רק פטורים (אשה ועבד לר"ש).
[fn:35] וכן נראה, שהרי גמרא מניח שהולך בין שקיעה לצאת ובין עלות לנץ כמו שהולך ביום.
[fn:36] גמרא רק אומר שלכן נקוד, אבל לא אומר שזהו מקורו.
[fn:37] אולי היה לזה להיות בכלל אונס, אבל אינו ממש אונס, כיון שקל הוא לחזור. ותחשב.
[fn:38] אם עשה עבודה אחת ע"מ לעשות עבודה אחרת לשם קרבן אחר, חולקים ריש לקיש ורבי יוחנן בתחילת זבחים ואמצע חולין.
[fn:39] איני יודע מהו הדין אם חשב למנויים ואינם מנויים. אין זה דיון גמרא (ס.), ששם דן במחלקת רבי מאיר ורבי יוסי. אותו מחלקת שייך רק (עיין בר"ן בנדרים כו) אם שני דיבורים שלו סותרים זא"ז. אז, צריך לומר שגמ’ דן כשחושב שהוא רק למנויים וגם חושב שהוא רק לאינו מנויים. כאן, דנים אם חשב לשם שניהם.
[fn:40] באלו, יש לדון אם הוא פסול בעלים או פסול מחשבה. לשון המשנה (שחיטה על מי שאינו מנוי…) משמע שהוא פסול מחשבה. אבל, מפשטות הסברה, היה נראה לומר שהוא פסול הבעלים, שהבעל צריך להיות מנוי עליו וכדומה. ותחשב.
[fn:41] אין גמרא אומר מקור לזה בפירוש, אבל אומר שיש היקש (סא.), ולא מזכיר מקור אחר לדין זה.
[fn:42] עיין בגמ’ (סא:) כשמזכיר מחלקת רבה ור"ח שכתבנו גבי שינוי בעלים. יש להעיר שממה שמביא אותו מקרא של פסול כשמחשב שאחרים יאכל, ואומר שמה שמשנה הוא שחושב לזריקה, היה יותר נראה לומר שהוא בחושב שיחשב באותו עבודה לאכול בו פסולים. אבל, גמרא משמע שלא אומר כן, שאומר, “על מנת שיכרפו בזריקה….” אז, נראה שאין לצדד כן, אף שהיה המקור משמע כן.
[fn:43] לכאורה, גמרא משנה הסברה חיצונה. גי"ל שהו"א שבא קרא לומר כסברה חיצונה. עיין במקום אחר שחדשנו שאולי כמו שטרח וכ’ קרא דבר שנלמד מקל וחומר, גם טרח וכ’ דבר שנודע מסברה.
[fn:44] בן שנה ר"ל שהוא בתוך שנתו הראשון. אותו שנה אינו למנין עולם, אלא מיום ליום, שכתיב גבי קרבנות "שנתו.”
[fn:45] לא כל כך פשוט למה מניח כן גמרא, שהיה אפשר לומר שהוא חיוב, אבל לא לומדים כל דינים אלו מפסח. ויש לדון אם מוכרח שיש מי שסובר כן, שבוודאי יש שיטה שסובר שחיוב הוא (כן אומר יהודה בן דורתאי), אבל אולי סובר שנלמדו דינים אלו, אבל עדיין הוא לאותו סיבה שאומרים חכמים. לא נראה כן, שמסתמא אם יש חיוב בכל אופנים אלו, צריך לומר שאינו לטעם של רבנן.
[fn:46] גמרא אף חוקר אם אולי יש עליו איסור שבירת עצם.
[fn:47] צריך ביאור איך דורשים מזה לפי רבא (ה.) שדורש מזה איסור חמץ בע"פ בזמן שחיטה. ותו"ת.
[fn:48] גמרא מסיק (סד.) שתלוי באם הוקש לשחיטה או לא. יש להעיר שגמרא אמר לעיל שיחייב כיוןן שהוא בכלל לינה. לכאורה, זה טענה טובה, וצריך ביאור איך דוחה את זה, ולמה הוצרך לדחות את זה אף לתנא שסובר שעובר. אפשר שההיקש שאומר ר"ל סמוכים שמקיש לינה. ויש לדון, שאז היה לנו לחייב כל אדם (עיין בגמ' סג:). אולי צריך לומר שכוונת גמרא לומר שלא מדייק ממה שלא אומר "זבחך," וגם לא דורש ההיקש. אם כן, נמצא שאף אם יש לאחד מבני המנויים, לא יעבור עליו. זה חידוש בדין.
[fn:49] יש לדון איך יודע שלא לרובת כל עולה. אולי תפסינן מעט.
[fn:50] שכבר דורש קרא שלו לאסור תמיד.
[fn:51] זה כולל כמה זמנים, אבל כיון שבארנו עיקרי דינים של קרבן פסח של דורות בזמן זה, נבאר אף דין של קרבן של מצרים.
[fn:52] גם הקריבו אחר כך במדבר. מסתמא, זה כבר היה כפסח דורות.
[fn:53] אינו כל כך ברור לי איך משמע כן. ותחשב.
[fn:54] יש לדון אם זה היה מדין זריקה (כשאר קרבנות) או מדין אחר (לכאורה, שמירת בתיהם). באמת, צריך ביאור אם קרבן פסח של מצרים היה, באמת, קרבן.
[fn:55] יש תנא שחולק בזבחים, ואומר שכהן זורק אותו אל מזבח.
[fn:56] יש לדון על איזה מן הארבע מצוות של חמץ קאי.
[fn:57] גמרא שם דורש שאסור אף מגוי שכבשתו (הוא תחת ידך) והוא בחצירו, שכ’ אותו קרא סתם. יש בגמ’ שני דרכים לבאר קטע זה (שהרי הוא הפוך מן הסברה):יש שמבארים שלומד המקום שבו מותר, אם אינו מקבל אחריות.יש שמבארים שמהפכים, ולומד דין נכרי שלא כבשו ושלא שרוי אצלו (אומר שניהם בשני הדינים. יש לדון איזה דווקא, וכאיזה דומה מי ששרוי ולא כשבתו.).נמצא חידוש דין לכל צד. יש לדון אם צד האחר יודה לאותו דין.
[fn:58] איני יודע הדין אם שכרו. ממה שמותר אם שכר לגוי, נראה שאם הוא שכרו, יהיה אסור.
[fn:59] נראה שהוא מפני מה שכתבנו שאם הוא במקום מיוחד, ומשכיר אותו מקום לגוי שאז אינו אסור. אז, אולי כאן מכוון להשכיר. יש לדון, שעדיין צריך מעשה קנין. ותחשב. שוב נראה לי שאינו כן, שנראה שזה מחמת החשש שמא יאכל, ולא מחמת איסור לא יראה, שהרי אינו שלו, ולא יעבור. אבל, צריך לומר שלרשי גדרי איסור בל יראה תלויים במתי מסתבר לגזור, שמשמע שהאיסור הוא גזירה שמא יאכל (כמה שכתבנו בשיח שי), ואז צריך לומר שזה עושה שלא יאכל. אז, אולי י"ל כמש"כ.
[fn:60] יש לדון, עדיין, אם צריך, על כל פנים, לכפות עליו כלי. אם לא צריך, אז, מסתמא דין שלו יהיה חלוק אף ביום טוב.
[fn:61] זהו דבר שלא נתחמץ כל כך, ואז, לכאורה, אינו דבר שווה ל"שאור" של תורה.
[fn:62] יש לדון אם צריך שלא עשה חימוצו שאינו רואי לאכילה או שצריך שהוא ראוי לאכילה. ותחשב.
[fn:63] מצאנו שלש ציורים:חמץ שאינו אוכל.חמץ שלא נתחמץ כל צרכו. (אולי זה שווה ל1, שאולי הענין הוא שכיון שאל נתחמץ כל צרכו, אינו אוכל. לא נראה כן במציאות.)דבר שנתחמץ במי פירות. אם אין 2 שווה ל1, יש לומר שזה שווה ל2. אבל, זה מוסיף דבר, שזה לא היה אפשר להיות חמץ ממש. ותחשב.
[fn:64] גמ’ שם מביא ראיה שמשמע נגד ר"נ, אלא שר"א רק אוסר תערובת.
[fn:65] ואם תאמר הרי חמץ לא בטל. אם כן, יהיה פשוט, וגם יהיה חיוב כרת. גמרא (מג) מפרש שהחידוש הוא שהיתר מצטרף לאיסור.
[fn:66] ואם תאמר אם כן יתחייב כרת, שאף כ’, “כי כל אוכל מחמצת ונכרתה.” י"ל ששם דורשים מ"כל" לרבות עוד אדם שאוכל (שבזה דן הקרא), לומר שנשים מצוות על איסור חמץ. (ולא נפטור אותם מחמת ההיקש למצה, שהוא מצות עשה שהזמן גרמא).
[fn:67] ואין לחוש להעיר ב1, לכאורה, כיון שידוע שיש להם דפוס. ויש לדון, שאפשר לומר שחולק על 1.
[fn:68] חולקים אם זה אף בחיטין: יש ארבע שיטות:אסור ללתות חיטין. כן אמר רבא בהוה אמינא ראשון.בעל נפש לא ילתות חיטין, אבל אינו אסור. כן אמר רבה.מותר ללתות. כן אומר רב נחמן וכן אומר רבא בהוה אמינא שני שלו.מצווה ללתות. כן מסיק רבא. מביא ראיה, אבל לא מבאר למה מצווה. (מ.)
[fn:69] חוששים לזה אף במנחות כיון שאינו במקום זריזים. לא חוששים לזה במנחת העומר; שם הוא לציבור, ואז נעשה על פי בית דין.
[fn:70] חולקים אם צ"ל נתבקעים ממש, או שרק נשתנים עד שיתבקעו אם נותנם על פי חבית.
[fn:71] צריך ביאור, שגמרא (לט:) משמע שיותר קשה להחמיץ דבר חם.
[fn:72] גמרא שואל אם עברה על שנים אלו (יש לדון אם השאלה הוא אף על השלישי (אשה עוסקת כל זמן…)). (באמת, מגמרא לא מוכרח שאף שואל על ראשו (לישה בחמה)ן, שרק שואל מהו הדין אם עברה ולשה. מסתבר שקאי על שני, שהיה הכי קרוב לו. עדיין, לכאורה, סתימות שלו משמע שהוא קאי על הכל.) רש"י מבאר שמסיק שקונסים, ואסור בדיעבד.
[fn:73] כמובן, מניח גמרא שאם לא בא המים מכל רוחותיו, יחמיץ.
[fn:74] רק חוששים לזה גבי חמץ, ולא גבי מנחות, שבמקום זריזים עושים מנחות.
[fn:75] גמרא מבאר שכוע"מ שאין בעיה אם רק מקטף (נותן על פניה). חכמים אומרים שלעולם אין חילוק בין לישה לקטיפה.
[fn:76] ואם תאמר הרי אין מי פירות מחמיצים. נראה לבאר על פי מה שנכתוב בשם רש"י לקמן שעדיין חמץ נוקשה הוא.
[fn:77] אם שומר שלא נתחמץ (לא נתסקע, ולא שהה זמן שבו נעשה חמץ קודם בישול).
[fn:78] אבל, עדיין יהיה חמץ נוקשה.
[fn:79] לכאורה, אביי יאמר שאינו מי חיטין, אלא מים שבלועים בחיטים. ותחשב.
[fn:80] היה אפשר לגמרא לומר כן, ולומר שעבה ר"ל אף פחות מטפחה.
[fn:81] נמצא שחמץ אסור מכל מין, ולא רק מחמשת המינים- אלא שרק קורה בחמשת המינים. כן נראה ממקורו בגמ’ (לה.).
[fn:82] צריך ביאור, ששם דורש מ"לך,” ולכאורה ממעט אף של ישראל. שמעתי שגר"א כתב שעובר על של ישראל. צריך ביאור איך דורש.
[fn:83] עדיין יש לדון בחמץ נוקשה ותערובת, שהיה לנו רק קרא אחד לרבות אותו, ואז אולי רק לאותו איסור אכילה מרבה אותו. ויש להעיר שגמרא אומר שצריך לשרוף שאור, שהוא חמץ נוקשה. יש לדון מהו המקור, אבל לא ידענו המקור לאיסור שלו כלל. ותחשב.
[fn:84] ומסתמא אף להנאה הוא כן.
[fn:85] לכאורה, יודעים שאותו שיעור הוא כזית כיון שכן מסתבר, שרוב שיעורי אכילה הם כך. זה רק בא לומר שלא נדרוש נגד זה מדרשה כעין מה שדורשים גבי בל ימצא. אם כן, אין זה לפי ב"ש וב"ה, שרק ב"ש היה אומר שהוא חלוק גבי בל ימצא.
[fn:86] עיין לעיל (ערב פסח) שהתחילו תחלת איסורים אלו.
[fn:87] גמרא לא מבאר דין הנאה, אבל מסתמא דינו הוא כאכילה, שנלמד ממנו באופן אחד.
[fn:88] אבל עדיין לא צריך פת קיבר, כיון שכתיב "מצה" לרבות אף פת נקי.
[fn:89] כן סובר רבה (ודורש אותו מ"ושמרתם את המצות"). רב יוסף חולק על הפשט שאומר רבה על פי זה, אבל מסתמא מודה לדין, שגמרא מביא ברייתא שאומר כרבה.
[fn:90] צריך לעיין בהלשמות (יט) על שי"ח ש"י על משניות פסחים.
[fn:91] כן מפרש רב אשי, אבל רבי יוחנן לא מפרש שיש שיטה כזה.
[fn:92] רבא סובר שזה כבר נלמד מערל ומומר, שנדרש לעיל ממה שכתיב, בכל אחד, “בו.”
[fn:93] יש לדון אם זה מעכב. לכאורה, היה לו לעכב, שנדרש מקרא; אבל לא כתבו אותו פוסקים לעיכוב. אולי הוא רק אסמכתא.
[fn:94] ונראה כן ג"כ מרשב"ם שכ’ שסכנה שאומר גמרא קאי על ימין. ויש לדחות שסבר שקאי על שניהם. לא משמע כן.
[fn:95] יש נפק"מ, כידוע, לאטר.
[fn:96] נראה שחיוב נשים בזה (וכן, באמת, בחיוב מצה של "על מצות") תלוי בחיובם בקרבן פסח.
[fn:97] יש להעיר שמחלקת זה בא בגמרא מחמת טעם ראשון שמזכיר גמרא. רבי אלעזר בר"צ סובר כטעם שני או שלישי. יש לדון אם אף סובר כטעם ראשון. אם לא סובר כן, יש לדון מה צריך. ותחשב.
[fn:98] צריך ביאור למה קרא זה שייך כלל.
[fn:99] צריך לדון אם יכול לקיים מצוותו בסיפור לעצמו אם יש לו אחר עמו. כמו כן, יש לדון אם מקיים כשאומר לאשתו, אם יש לו בן. גם יש לדון אם צריך לאיש אחד או לכל אחד שהוא שם. ותחשב.
[fn:100] אין מקור ידוע לי לזה, אבל כן נראה לי.
[fn:101] אסור לאכול אותו באופן אחר, אבל עדיין יש לדון אם מעכב את מצוות אכילת קרבן פסח. אולי הוא מצווה הבאה בעבירה.
[fn:102] יש לדון אם סובר כרבא או לא, שאולי רבא, כיון שצריך לבאר שזה מטעים עם רישא, עושה כלל שכולל אלו מלשון המשנה. אולי לרבה, אין יש אומרים עושה שום כלל, ורק מרבה אלו, ולא יותר.
[fn:103] מגמרא קצת משמע שזהו אותו מחלקת של רבא ורבה. וצריך לעיין.
[fn:104] צריך לבאר איך זה מטעים עם רבי יוחנן ור"ל.
[fn:105] יש לדון בכל אלו אם הוא מקור או תוצאה ממקור.
[fn:106] תשובת רב אמי בוודאי מחלק ביניהם. תירוץ רבינא עושה שלא צריך לחלק. הנחנו למעלה שלא מחלק, אבל יש לדון.
[fn:107] לא נותן שיעור בהיר.
[fn:108] מסתמא, רבי לא יכול לדרוש כן, שכבר דרש מזה לבישול במשקים שאינו מים.
[fn:109] ודורשים ממנו שני דרשות לפי רבי, אחד מפני שכפל לשלונו, ואחד מפני ששינה לשונו.
[fn:110] ר"ל, השפוד נתקטן באמצע שלו. אבל, מה שנוגע בפסח (מה שהוא בצד השפוד) עדיין צריך להיות רמון.
[fn:111] יש לדון אם צריך להיות כן או רק יכול להיות כן. לשון גמרא משמע שצריך להיות כן, אבל צריך ביאור למה.
[fn:112] אם כן, אם שבת מכין ליו"ט, מותר ישרוף של שבת בפסח.
[fn:113] בביאור בירה, עיין ברשי כאן. אבל, עיין בשי"ח ש"י כאן.
[fn:114] לא מבאר משנה את הדין אם נתמנמו כל החבורה, לפי רבנן. נראה שיסברו שלא נחשבים שני חבורות, שהרי רק אומרים שנחשב כשני חבורות אם ישנו כולם. אין לדקדק ממה שלא התיר בציור זה, שאולי רצו לחדש שציור שמותר אף אם ישנו. ותו"ת.
[fn:115] יש להעיר שכל אלו ממעטים איסור להיות לו חמץ. יש לדון באיסור לאכול חמץ. נראה שאין זה פרט בקרבן פסח, ואז לא צריך למעט אותו. אז, נמצא שיש עוד סוג של חילוקים, והוא מה שאינו פרט בקרבן פסח. ותחשב. אם כן, צריכים להניח שהשבתת שאור הוא פרט בפסח שני. זה מחודש.
