- גמרא מביא מימרת רבי יוחנן שיכול אדם לדרוך ענבים טמאים פחות פחות מכביצה. סובר שלא נטמאו משקין, אלא ע"י נגיעתם בפרי אחר יציאתם. כיון שהפרי פחות מכביצה, לא מטמא[fn:1]. צריך להיות פחות מכביצה, אף שחשבון זה יתיר יותר מכך, כיון שיחסר ע"י סחיטה, מגזירה אגב יותר מכביצה. מוכיח כ"ז ממשנה שמטהר מה שדרך טמא מת.
ר"ח חולק, וסובר שמשקים בתוך פרי טמאים. דוחה המשנה (שמטהר מה שדרך ט"מ) לומר ששם לא הוכשר. הוכשרו רק אחר שחסרים מכביצה בסחיטה.
עדיין אף ר"י מודה שלא יכולים להניח תרומה טמאה כדי לדרכו, שחוששים לתקלה. כן לומדים מברייתא מפורשת שאומר שאין דבר לעשות עם תרומת תותים טמאים. רק לא חיישינן לקלקול אם יכול לעשות שהוא מאוס, כמו שמן ופת. אם לא עושה כן, אסור. (חולקים אם חיטין מותר, שיכול לעשות שהם מאוסים, אבל צריך לשלק אותם קודם, וחולקים אם יש חשש בשליקה.)
- מקשה רבה בר מתנה על משנה שאומר ששתילי תרומות שנטמאו ושתלן טהורים מלטמא ואסורים מלאכול. מקשה למה אסורים. מתרץ שאסורים לזרים. מקשה שכבר יודעים איסור גידולי תרומה, אף אם אין זרעו כלה, ואיסור גדולי גדולים אם לא כלה, והתיר גדולי גדולים אם כלה. אז, אומר שאסור לכהנים, שנפסל בהיסח הדעת. מבאר שזה אפשר רק אם הוא פסול הגוף, ולא חשש טומאה. חולקים ר"י ור"ל בזה (שרק ר"ל אמר שהוא פסול גוף). מתרץ שאסורים לכהנים כיון שעשו מעלה שאין זריעה מטהר לאכילת קדשים, אם זורע אחר שכבר נעשה קשדים. מזכיר כמה עוד מעלות[fn:2]:
1. לא יכולים לדרוך, אף בציור שבדרך כלל לא יטמא, אם דורך אחר שכבר הקדיש. גמ’ מבאר שציור זה הוא:
  1. אם הוא פחות מכזית.
  2. אם נטמא פרי בשני, שאז לא יטמא משקין.[fn:3]
2. צריך לקדש מי חטאת בכלי שבו לקח מים, ולא לתת לכלי אחר, אף שיכול מדאו’ (שנ’, “ונתן").
3. מחוסר כפורים אינו יכול לאכול קודש עד שמביא קרבן, אף שכבר העריב שמשו.
4. לבונה ועצים נטמאים.
* Footnotes
[fn:1] הפשטות הוא שלא מטמא, אבל רש"י כ’ צד כאן שאף לא נטמא.
[fn:2] ודן גמרא אם מעלות אלו הם אף בקדושת פה. פשוט שהם בקדושת פה כשאי אפשר להיות יותר מכך (כגון גבי תרומה), אבל דן כשיהיה יותר מכך, כמו מנחות.
[fn:3] גמרא אומר שני תירוצים אלו. יש לדון מה אחד סובר על חברו. ותחשב.
