רבי אלעזר אומר מימרא: רבי יוסי בן יועזר היה מטהר משקים שבבית המקדש. יש שני דיונים כאן:
1. דנים איזה משקים טיהר. רב סובר שטיהר משקה בית מטבחיא (כן גורס שאמר), שהוא מה שמשתמשים בו לבהמה. זה כולל דמו ומים. מוכיח גמרא שכן סובר שמואל. לוי סובר שטיהר משקה בית מדבחיא (כן גורס), שהוא מה שמשתמשים בו למזבח (כמו יין).
2. דנים איזה טומאה טיהר. היסוד הוא (בכמעט כל הצדדים) שרק טיהר מה שטמא מדרבנן. אז, חולקים מה טיהר. רב אמר שטיהר משקים מלהיות טמאים וגם מלהיות מטמא אחרים. שמואל אומר שמטהר משקים מלהיות מטמא אחרים, אבל לא טיהר אותם מלהיות טמאים. מוכיח גמרא שכן סובר לוי.
3. דנים איזה חפץ טיהר. היסוד הוא כאן גם כן שרק טיהר מה שהוא טמא רק מדרבנן. רבי אליעזר אומר שטיהר כל משקין. (רב ושמואל היו דנים בתוך שיטה זה לעיל. לרבי שמעון, פשוט שאף לא נטמא.) רבי שמעון אומר שרק טיהרו רביעית מים שמחובר לקרקע. מים כזה נחשב מקווה מדאורייתא, ואז מטמא רק מדרבנן.[fn:1]
4. מצאנו, אז, שלש יכולות:
  1. משקה בית מטבחיא יכול להיות נטמא אבל לא מטמא.
  2. משקה בית מטבחיא לא יכול להיות נטמא ומטמא.
  3. משקה בית מטבחיא יכול להיות נטמא אבל לא מטמא.
* Footnotes
[fn:1] רב פפא מצדד שאף אם הוא טמא מדאורייתא, בבית המקדש, הלכה למשה מסיני מטהר אותו. גמרא דוחה את זה כיון שר"א גופא לומד מדין של רבי יוסי בן יועזר שאין משקים טמאים או מטמאים מדאורייתא.
