** ארבע
[fn:1]יש
ציורים בענין תערובת חמץ:
1. חמץ במינו בזמנו[fn:2].
2. חמץ שלא במינו בזמנו.
3. חמץ במינו שלא בזמנו[fn:3].
4. חמץ שלא במינו שלא בזמנו.
** חמץ במינו בזמנו:
רב ושמואל סוברים שאסור בכל שהוא. זה מפני שרב סובר שכל מין במינו אסור במשהו.[fn:4]
רבי יוחנן וריש לקיש סוברים שאוסר בנותן טעם.
רבא פוסק כרב כאן.
** חמץ שלא במינו בזמנו:
רב סובר שאסור בכל שהוא, שגזר מחמת במינו בזמנו (כיון שהוא איסור כרת).
שמואל סובר שאסור בנותן טעם, שלא גזר מחמת במינו בזמנו.
רבי יוחנן וריש לקיש סוברים שאסור בנותן טעם, שאין דבר שאוסר במה שהוא (ואז פשוט שאין לגזור).
רבא פוסק כרב כאן.
** חמץ במינו שלא בזמנו:
דין זה תלוי במחלקת רבי יהודה ורבי שמעון (שחולקים אם אסור או מותר לאכול חמץ שעבר עליו הפסח). אם יש איסור בחמץ כזה, אז דינו שווה לדין חמץ במינו בזמנו. אם אין איסור בחמץ כזה, אז פשוט שתערובת שלו מותר[fn:5].
רב פוסק כרבי יהודה, ושמואל ורבי יוחנן פוסקים כרבי שמעון.
רבא פוסק כרבי שמעון (כרבי יונן ושמואל) כאן.
** חמץ שלא במינו שלא בזמנו:
דין זה תלוי במחלקת רבי יהודה ורבי שמעון. לפי רבי יהודה, אסור בנותן טעם (שאין גוזרים אגב מינו שלא בזמנו, כיון שאינו איסור כרת[fn:6]). לפי רבי שמעון, מותר.
רבא פוסק כר"ש (כרבי יוחנן ושמואל) כאן.
כיון שרב סובר שאסור במשהו לאחר זמנו בין במינו, סובר שאסור לשהות כלי חרס שבלע חמץ לאחר פסח. לא מותר לשהות כדי לעשות בו במינו, כיון שלא בטל. לא מותר לשהות כדי לעשות שלא במינו, שגוזרים שאם ישהה יבוא לעשות במינו.
לא יכולים לגרום שיפלוט מה שבלע, שכלי חרס לא פולט. (חולקים בגמ’ אם אף לא פולט אם מסיק בפנים. אף אם נאמר שאז פולט, לא מתירים לו לשהות, שחוששים שיחוס על כליו (כדי שלא ישבר), ולא יסיק מבפנים.)
אין הלכה כזה לשני טעמים:
1. רבא כבר פסק כרבי שמעון. אז, אף במינו לא אסור תערובת חמץ לאחר פסח.
2. להלכה, נותן טעם לפגם מותר. קדירה אחר יומו נותן טעם לפגם.
להתיר שאר כלים, מזכיר גמרא הכלל ש"כבלעו כך פלטו.” (גם מביא שיטה אחר שטוען ליבון לסכין. לא מבאר מה סובר; לכאורה, לא סובר שכבלעו כך פלטו, שלכאורה, לא בלע על האור ממש (ויש לדון).)
* Footnotes
[fn:1] יש להקדים שגמרא אומר שמדאורייתא הכל בטל ברוב. איני יודע אם זה אף במין במינו.
[fn:2] ר"ל, בתוך פסח.
[fn:3] ר"ל, חמץ שעבר עליו הפסח.
[fn:4] חולקים רבי יהודה ורבנן בזה בזבחים.
[fn:5] ואם תאמר למה יהיה מותר, שהרי רבא אמר שר"ש קנס חמץ שעבר עליו הפסח. גמרא אומר שזה רק כשהחמץ בעין, אבל לא כשהוא בתערובת. (קצת יש לדון אם הענין הוא שלא קונסים כשעבר על הפסח בתערובת, או שלא קונסים תערובת של חמץ שעבר עליו הפסח. יש נפק"מ אם היה בעינו בפסח. רש"י כ’ כצד שני.)
[fn:6] כמובן, יש להעיר שגמ’ יבמות אומר שגוזרים על איסור לאו בשווה לאיסור כרת.
