בתערובת, יש שלש דרכים לאסור:
1. אכילת כזית בכדי אכילת פרס. זה נוהג בכל איסורים, ונלמד מהלכה לשמה מסיני.
2. היתר מצטרף לאיסור. כן הוא הדין באיסור חמץ לאוסרים תערובת (ר"א, ואולי אף ר"מ), שכ’, “כל מחמצת,” וכן הוא הדין באיסורי נזיר, שכ’, “משרת." חולקים אם הוא כן לר"א אף בהקטרת שאור, שכ’, “כל שאור לא תקטירו.” כן הוא הדין בחטאת לכולי עלמא.
3. דין ראשון ושלישי יהיו רק לר"א. דין שני הוא רק לר"ע.
4. לא לומדים מזה לשאר דינים. לרבנן לא לומדים, שנוהג רק בחטאת, שהוא קדשים. לר"ע לא לומדים, שהוא שני כ’ הבאים כאחד, שלא צ’ איסור בחטאת.[fn:1]
5. אף כשאיסור והיתר מצטרפים, מצטרפים רק בבת אחת. יש דברים אחרים (כמו איסורי נזיר) שאף מצטרפים זה אחר זה (דכ’, “מחרצנים עד זג").
6. טעם כעיקר. חולקים תנאים מהו המקור לזה:
  1. רבנן דורשים את זה מ"משרת,” ומלמדים לכל איסורי תורה.
  2. ר"ע לומד את זה מ:
    1. בשר בחלב. גמ’ דוחה שחידוש הוא, שלא נאסר בשרייה, אלא בבישטל.
    2. גיעולי נכרים. גמ’ דוחה שחידוש הוא, שאוסר נ"ט לפגם. ר"ע דוחה שנאסרו אלו שהיו בני יומם, ונ"ט לשבח. רבנן דוחים שבהכרח נתנו טעם לפגם.[fn:2]
7. לומדים מכאן לכל התורה.
* Footnotes
[fn:1] גמרא מפרש שמחמת זה הוא שני כ’ הבאים כאחד. אין צ’ כן, אלא היה יכול להיות שהוא כן מחמת חמץ ונזיר או כדומה, אלא שאין לנו הכרח שסובר כר"א. ותחשב.
[fn:2] אגב, קצת צריך ביאור שבסוף ע"ז משמע שמי שאוסר נ"ט לפגם לומד מזה לאסור. לכאורה, צריך לומר שרבנן לא אומרים כן, שהרי אם כן אין חידוש בו, שכל התורה כן. ויש לדון ל"ל אומרים שכן סובר ר"ע. ותו"ת. אולי רוצים שיהיה כהלכה (שמותר).
