מצאנו כמה דברים שחוששים שנחמצו:
1. אם לש[fn:1] עיסה ביין ושמן, ר"ג סובר שצריך לשרוף מיד. חכמים חולקים. (לו.)
2. אין לשין בפושרים[fn:2]. (לו.) לא מבאר גמרא דין בדיעבד.
3. אין לותתים (שורים שעורים[fn:3] במים)[fn:4]. (לו., מ.) אם לתת ונתבקעו[fn:5], אסורים. חולקים אם יכולים להתירם ע"י נתנתם בחומץ. להלכה, לא מתיר. (מ.)
4. ב"ה וב"ש חלקו אם מותר לאפות פת עבה (מפ’ שהוא פת שיותר מטפח) בפסח. גמרא (לז.) חושב שחולקים אם חוששים שיחמיץ. גמרא לא מבאר דין בדיעבד.
5. אבל, דוחה גמ’ (שא"כ נחוש אף לפחות מכך)[fn:6], ואז מבאר שהמחלקת שם הוא אם יכול לאפות הרבה פת ביום טוב או לא, שהוא טירחא.
6. אין עושים סריקים המצויירים בפסח כיון ששוהים אדם בהם. גמרא מזכיר על זה שלש דברים:
  1. זה אף למי שעושה בדפוס (ולא שוהה), שאל"ה יתמהו בנ"א על שרק של זה מותר.
  2. ר"צ מחדש שרק של נחתום אסור, ששוהה עליו. יש אומ’ שאמר שרק של נחתום מותר, שרובם יש להם דפוס.[fn:7] ויש לדון אם חולקים עליו.
  3. ר"י מחדש שמותר אם נעשה כרקיק (אינו גבוה). יש לדון באיזה ציור דן (אם הוא בציור שמודים שמותר, או אם הוא מתיר בכעין זה כל הציורים). ויש לדון אם חולקים עליו. (לז.)
7. בדיעבד, מותר.
8. חוששים לחיטים, אף שקלויים כבר, שנתן במים. חוששים שלא נאפו טוב. (לט:) בדיעבד, מותר
9. אין נותנים שני חיטים ברותחים ביחד, שמשא ישב אחד בסדק חברו, ולא יבא מים רותחים מארבע צדדיו.[fn:8] (מ.) לא מבאר דין בדיעבד.
10. חריכת שני קליות, שמא יצא מים מאחד לחברו. גמרא דוחה זה בשני דרכים. אביי אומר שחוששים לזה רק אם לא יוצא ונופל, אלא נשאר שם. רבא אומר שלא דוחים לזה, שמי פירות הוא, ולא מחמיץ.[fn:9] (מ.) לא מבאר דין בדיעבד.
11. לא תלוש אשה בחמה, שהחום יחמיץ. (מב.)
12. לא תלוש אשה במים חמים[fn:10], שהחום יחמיץ. (מב.)[fn:11]
13. אשה תעסוק בפת בכ"ז עד שנתבשל. (מב.)
* Footnotes
[fn:1] גמרא מבאר שכוע"מ שאין בעיה אם רק מקטף (נותן על פניה). חכמים אומרים שלעולם אין חילוק בין לישה לקטיפה.
[fn:2] רק חוששים לזה גבי חמץ, ולא גבי מנחות, שבמקום זריזים עושים מנחות.
[fn:3] חולקים אם זה אף בחיטין: יש ארבע שיטות:אסור ללתות חיטין. כן אמר רבא בהוה אמינא ראשון.בעל נפש לא ילתות חיטין, אבל אינו אסור. כן אמר רבה.מותר ללתות. כן אומר רב נחמן וכן אומר רבא בהוה אמינא שני שלו.מצווה ללתות. כן מסיק רבא. מביא ראיה, אבל לא מבאר למה מצווה. (מ.)
[fn:4] חוששים לזה אף במנחות כיון שאינו במקום זריזים. לא חוששים לזה במנחת העומר; שם הוא לציבור, ואז נעשה על פי בית דין.
[fn:5] חולקים אם צ"ל נתבקעים ממש, או שרק נשתנים עד שיתבקעו אם נותנם על פי חבית.
[fn:6] היה אפשר לגמרא לומר כן, ולומר שעבה ר"ל אף פחות מטפחה.
[fn:7] ואין לחוש להעיר ב1, לכאורה, כיון שידוע שיש להם דפוס. ויש לדון, שאפשר לומר שחולק על 1.
[fn:8] כמובן, מניח גמרא שאם לא בא המים מכל רוחותיו, יחמיץ.
[fn:9] לכאורה, אביי יאמר שאינו מי חיטין, אלא מים שבלועים בחיטים. ותחשב.
[fn:10] צריך ביאור, שגמרא (לט:) משמע שיותר קשה להחמיץ דבר חם.
[fn:11] גמרא שואל אם עברה על שנים אלו (יש לדון אם השאלה הוא אף על השלישי). (באמת, מגמרא לא מוכרח שאף שואל על ראשון, שרק שואל מהו הדין אם עברה ולשה. מסתבר שקאי על שני, שהיה הכי קרוב לו. עדיין, לכאורה, סתימות שלו משמע שהוא קאי על הכל.) רש"י מבאר שמסיק שקונסים, ואסור בדיעבד.
