1. הקדמה:
** (ויקרא, כג)
יש שש ימים שנקראים יום טוב (א' טו' וכב' תשרי, טו' וכא' ניסן, וו' סיון). בכולם, יש איסור לאו שאוסר לעשות מלאכה
.
1. איסורים דאו':
** (לו:)
איסור זה יש לו גדרים דומים לאיסור מלאכה של שבת
,[fn:1] ואסור לעשות כל שלשים ותשע מלאכות. אבל, מצאנו שני חילוקים:
1. אוכל נפש:
** (שמות יב[fn:2], לו:)
אוכל נפש מותר בי”ט. בי"ט, מותר לעשות מלאכה לצורך אוכל נפש, אף שבשבת אסור
.
** (כח:)
חולקים רבי יהודה ורבנן איזה סיבה לאכילה נחשב אוכל נפש. רבנן אומרים שהוא רק אוכל נפש (שכ’, הוא”), ורבי יהודה אומר שכולל מכשירי אוכל נפש (שכ’, “לכם”)
.[fn:3]
יש הרבה יוצאים מן הכלל; יש ארבע יוצאים מדאו’, ויש ? יוצאים מדרבנן:
1. יוצאים מן הכלל מדאו’:
2. כדי שדבר יהיה מותר, צריך להיות בשביל אוכל נפש של אותו היום[fn:4]. יש יוצא אחד מכלל זה:
  1. רב חסדא אומר שמותר אם הוא בשביל אוכל נפש של שבת[fn:5]. רבה חולק על זה.
3. כדי שדבר יהיה מותר, צ"ל בשביל אוכל נפש של ישראל, כיון שכ’ "לכם" (לא.). זה ממעט שלש דברים:
  1. אם הוא בשביל אוכל נפש של גוי, אסור[fn:6] (לא).
  2. אם הוא בשביל אוכל נפש של בהמה אסור. חולקים אם זה רק בבהמה שמזונותיו עליך או בכל בהמה (לא:).
  3. אם הוא לה’, אף שבא מזה אוכל נפש (כ:), אסור, כיון שהאוכל רק זוכה משלחן גבוה[fn:7] (כא.).
יש יוצא אחד מזה:
    1. קרבן שלמים. יש שני מיני קרבן שלמים:
      1. שלמי חגיגה. זה מותר, כיון שכ’, "וחגותם… לה’" (יט.).
      2. שלמי נדבה. חולקים תנאים אם, לפי בית הלל, יכול להקריב כל שלמים[fn:8]. מצאנו שלש סיבות להתיר:
        1. לא ממעטים מ"לכם" כיון שכבר מעט העושה לבהמה ולגוי (כ:).
        2. מרבים מ"לה’" (יט.).
        3. מרבים מקל וחומר- שבת שאסור כל שחיטה להדיוט, יש בו היתר מיוחד לתמידים; בי"ט, שמותר כל שחיטה להדיוט, כל שכן שיהיה מותר כל שחיטה לה’[fn:9][fn:10] (כ:).
        4. מרבים מסברה- לא ראוי שתהיה שולחנך מלא ושולחן רבך ריקן (כ:).
** (כא.) (כא.)
מותר לעשות מלאכה של אוכ"נ של לישראל, אף אם נמצא שנכרי נהנה
. מותר לעשות מלאכות בשביל גוי וישראל כשכל חתיכה אפשר לישראל[fn:11]
.
1. כדי שדבר יהיה מותר, צ"ל שלא היה אפשר לעשות אותו קודם י"ט. דורשים כן כיון שכ’, “הוא.”[fn:12][fn:13]
2. הכנה. רבה סובר שמדאו’ אסור להכין משבת לי"ט, שכ’, “והכינו…,” ומה שמוכן, ואפילו בלי מעשה, אסור לאכול.[fn:14] הרבה אמוראים חולקים על רבה בזה[fn:15] (ג.).
    1. יוצאים מן הכלל מדרבנן[fn:16]:
3. מוקצה. אם דבר לא מוכן בבין השמשות, אסור לטלטל אותו ולאכול אותו בי"ט.[fn:17] רבי יהודה סובר שיש מוקצה (ורק מה שמוכן מביה"ש מותר לטלטל בי"ט) ורבי שמעון סובר שאין מוקצה (ורק דבר שהוא מאד נדחה אסור לטלטל בי"ט). יש מין אחר של מוקצה שנקרא נולד, שהוא כשהחפץ לא היה בעולם ביה"ש. דינו שווה לדין מוקצה (והוא תלוי בחמ’ ר"י ור"ש)[fn:18] (ב.).
4. יש להוסיף שמוקצה הוא איסור חמור, ומצאנו בו גזירות (י.), וגם מצאנו מחלקת (כד.) אם ספקו מותר (בע"ה, ע’ לקמן, כשנדון על ספק איסורי י”ט).
5. ביצה שנולדה בי"ט. אם נולדה ביצה בי"ט, חולקים בית שמאי ובית הלל אם מותר או אסור לאכול אותו. יש שמפרשים שאיסור לאכול אותו הוא גזירה (אולי מחמת פירות הנושרים, שהוא גזי’ שמע יעלה ויתלוש, ואולי מחמת מי פירות, שהוא גזי’ מחמת סחיטה). אף שרק גזי’ הוא, דוחה אוכ"נ, ולא מותר לאכול את הביצה בי"ט (ב).
6. ליתר ביאור, ע’ בסיכום שלנו על ענין זה.
7. נראה כעושה מלאכה. אם מלאכת אכ"נ נראה כמלאכה, אסור לעשות אותו בי"ט. מצאנו ? ציורים כזה:
  1. לפעמים, אסור להוליך סולם, אף לצורך אכ"נ. תמיד אסור להוליך סולם של עלייה. יש אומרים שתמיד מותר להוליך סולם של שובך, וי"א שרק מותר ברה"י, וי"א שתמיד אסור (ט).
  2. אסור לשלוח דבר לחברו בשלשה בנ"א, שנ’ שמכוון למכור אותו בשוק (יד:).[fn:19][fn:20]
8. אסור לטבול כלי בי"ט.[fn:21]
9. הולכת מתנות. יש סיבה לאסור הרמת תרומה ומתנות, כיון שמתקן את האוכלים. אבל, אם לא היה אפשר קודם י"ט, מותר. אבל, יש אוסרים להוליך מתנות לכהן, גזי’ שמא ירים מתנות שלא מותר להרים. חולקים אם אסור להוליך תרו"מ ומתנות שהיה אפשר להוליך מבע"י, או רק תרו"מ, או שכולם מותר. (לכאו’, כל דינים אלו הוא גם אם יש אכ"נ לכהן שמוליך אותם לו.) (יב:)
10. לעשות מלאכה שיש בו טורח. חולקים[fn:22] אם מותר לעשות מלאכת אכ"נ אם יש בו טורח (כב:).
11. לבשל לשבת בלי ע"ת. אם י"ט חל להיות לפני שבת, מותר מדאו’ לבשל לשבת (או מפני שאומרים הואיל או מפני שהוא לשבת), אבל אסרו חכמים לבשל אם לא שם עירוב תבשילים. חולקים אם זה כדי שיזכור לבשל לשבת או כדי שילמד שהכנה אסור בי"ט. (?) (לע’ בסיכום דיני ע"ת?)
12. אסור לקבל מה שגוי הביא בכווונה לו בעבירת מלאכה, שמא ישאל לגוי (כד:).
13. אם מלאכה עושה רעש, אינו כבוד יו"ט, ואסור לעשות אותו, אף לצורך י"ט (כה:). אבל, רק מצאנו איסור זה אם יש אופן להביא את האוכל בהיתר.
14. ראיית מומים. חולקים רבי יהודה ורבי שמעון אם מותר או אסור לראות מומים של בכור (להתיר אותו באכילה). אם ראה, חולקים ר"י ור"ש אם מותר לאכול מאותו הבכור או אסור. סיבת איסור זה הוא שנ’ כמתקן (כו).[fn:23]
15. אסור לנהוג כמנהג חול. לכן, אסור לשקול (וי"א שאף אסור להשתמש במשקולת), ולקנות דבר בהז’ כמה עולה, ולמדוד (אולי רק אם מזכיר שרוצה לכוון המדה, או אולי אף בכלי שעשוי למדה, או אולי אף בכלי שיהיה עומד למדה אחר שכלי מדה נשבר[fn:24]).
יש שני היתירים שיוצאים מאוכל נפש:
  1. מתוך שהותרה לצורך, הותרה נמי שלא לצורך. בית הלל אומר שכל מלאכה שרגיל[fn:25] שנעשה לצורך אוכל נפש מותר בי"ט, ואף שלא לצורך אוכ"נ. אבל, צריך להיות לצורך הנאה השווה בכל. בית שמאי סוברים שאין היתר זה קיים.
  2. הואיל. רבה אומר שאף אם לא עושה את המלאכה בשביל אוכל נפש, אבל ראוי הוא לאוכל נפש של היום אילו דבר רגיל קורה, מותר. (אז, למשל, מותר לבשל, אף שאינו רוצה לאכול, שאולי יבוא אורח.) רב חסדא אומר שאין היתר זה קיים.[fn:26]
1. איסור מלאכה בשבת הוא איסור לאו שיש בו כרת ומיתה. איסור מלאכה בי"ט הוא איסור לאו. חולקים אמוראים אם גם יש בו איסור עשה.
איסורים דרבנן:
** (לו:)
גם באיסורים דרבנן, יום טוב הוא כמעט שווה לשבת
. אבל, מצאנו חילוקים:
1. רב נחמן סובר (ב.) שדבר שלא הוכן מעי"ט אסור לטלטל בי"ט, ודבר שלא הוכן מערב שבת מותר לטלטל בי"ט. הסיבה לזה הוא שכיון שיום טוב הוא יותר קל[fn:27], בני אדם מזלזלים בו, ויותר צריכים גזי’ מוקצה.[fn:28]
2. משילים (?)
3. טבילה (?)
* Footnotes
[fn:1] איני יודע מהו המקור לזה. לכאו', הוא מפני שמצאנו לשון של איסור מלאכה בשניהם, ואז מניחים שה"מלאכה" שנאסר בשניהם הוא שווה. (אני לא מחדש שהוא גזרה שווה, שאין לי מסורה לזה, אבל אני מחדש שרואים פירוש מילת "מלאכה.")
[fn:2] עיין שם, ששם רק אומר קולא זו על פסח. נראה שזה מקור שנוהג בכל ימים טובים, כיון שהוא דבר היוצא מן הכלל ללמד, שמלמד על כל הכלל.
[fn:3] לא כל כך קל להגדיר מהו החילוק. בפרט, יש להעיר שאין הרבה ראיות, שנוכל לומר שכל משנה הוא שיטת רבי יהודה. נראה שיש שלש דרכים להגדיר אותו. אפשר שרק סיבה אחרונה מותר לפי רבנן. גם אפשר שרק שינוי בחפץ הנאכל מותר לפי רבנן. לשנים אלו, נמצא שהרבה פעמים, הבערה אסור. גם אפשר שרק דבר שעכשיו רק יש לו טוב בנוגע לאכילה (למעט, למשל, עשיית סכין, שגם עושה טוב במה שיש לו סכין לעולם) נחשב אוכל נפש. אז, לכאו’, הבערה יהיה מותר.
[fn:4] איני יודע מהו המקור לזה מקרא, אבל נמצא בכ"מ במשניות ובגמ’.
[fn:5] יש לדון אם צריך להיות שבת הבאה (או אולי שבת שהוא למחר) או אולי יכול להיות כל שבת.
[fn:6] לא נראה שיש חולק בזה. אבל, יש לדון. גמ’ מביא בריי’ שבו חולקים רבי ישמעאל ורבי עקיבא אם למעט מ"לכם" בהמה או גוי. אז, אפשר לומר שכמו שחולקים אם לצרכי בהמה נתרבה, גם חולקים אם לצרכי גוי נתרבה. אבל, עיין שם, שקאי על מעשה שבו בשל אדם דבר לגוי, אלא שהיה גם ראוי לכלבים. כדי לאסור, צריך לאסור שניהם, ואז צריך לומר שאחד משני התנאים אסר את שניהם. ויש לדון, שאולי יש תנא אחר (בית הלל בבריי’ לעיל מזה) שאוסר שניהם, ויש, אז, שלש שיטות. ותחשב.
[fn:7] וא"ת עדיין אוכל נפש, אף שבא משולחן גבוה. נראה שההסבר הוא שבעיקר הוא לה’, כיון שאכילתו הוא לצורך שולחן גבוה. (צריך להגדיר את זה, שלא נאמר שמי שאוכל כדי להיות פולי"ט אינו בכלל אכ"נ. ותחשב.)
[fn:8] אם יכול להקריב קרבן שלמים, אין כלל זה קיים עוד.
[fn:9] ואם תאמר נאמר על זה דיו, שרק יגלה לנו היתר תמיד ומוספים, כמו בשבת. וי"ל שזה לפי השיטה שלא אומרים דיו (כיון שכאן לא מלמד שום דבר אם נאמר דיו). גם יש לומר שמגדירים את הדברים ככה- בשבת, יותר ממה שמותר להדיוט מותר. אז, בוודאי מה שמותר להדיוט יהיה מותר בי"ט. אז, אינו מלמד דברים הפרטיים, אלא מלמד הכלל, ובזה לא נראה שיש דיו. ותחשב על זה.
[fn:10] גמ’ גם מביא קל וחומר מאבא שאול, אבל כמעט אותו דבר הוא, רק עם משל אחרת.
[fn:11] ואם תאמר הרי זה סותר את הראשון, שנמצא שעושה יותר ממה שצריך. נראה שלעיל הוא רק אם ברר חלק הגוי, ואז עושה מה שאינו ראוי לישראל. ותחשב.
[fn:12] זהו המקור לדין זה גבי מכשירי אוכל נפש (כח:). יודע אני שדין זה נוהג לפי רבנן, אבל איני יודע מהו המקור לו. אז, הנחתי שרבנן מודים לרבי יהודה, וסוברים ש"הוא" ממעט את שניהם. ותחשב. (ויש לדון אם זה אפשר להיות, שאולי "הוא" רק משמע מיעוט של מכשירים, אלא שרבי יהודה מוקים אותו למכשירים שאפשר מלפני י"ט.)
[fn:13] יש להוסיף שלא צריך להיות שממש לא היה אפשר לעושת אותו קודם י"ט. אם, למשל, לא ידע מה רצה קודם י"ט, ולכן לא עשה אותו קודם י"ט, אף שהיה יכול לחשוב קודם י"ט מה ירצה, אינו נחשב אפשר לעשות אותו קודם י"ט. (כן אומרים בית הלל (יד.), אבל אפשר לומר שבית שמאי חולק על זה.)
[fn:14] לא יודעים המקור שאם הכין אותו אסור לאכול. אולי בלי זה לא נחשב שהוא לצורך י"ט. דחוק, שיהיה אסור לאכול אותו לעולם, שאז לצורך חול הוא. יותר נראה שדורשים לשון הקרא, והוא שבשבת וי"ט רק אוכלים מה שמכינים, שאומר שמכינים מה שאוכלים. ותחשב על זה.
[fn:15] שם, רק חולקים על הכנה דרבה, שהוא על דבר ממילא. אבל, לכאו’, אז, חולקים על פי’ הפסוק, ואינו מדאו’. כיון שכן, אין סיבה לחשוב שהוא אסור באכילה בכלל. ותחשב.
[fn:16] יש כמה מאלו שהם רק הנחות, אבל יכולים להיות מכשירים ואליבא דרבנן או שאפשר מבעוד יום.
[fn:17] כן נראה מגמ’ (כד:), שנראה שיש איסור של הנאה שמוסיף על איסור לטלטל.
[fn:18] עיין שם, שזהו שיטת רב נחמן. אבל, אף שמצאנו חולקים עליו בביאור המשנה, לא מצאנו חולק עליו בדין זה, ומסתבר לומר שאין חולק. ותחשב.
[fn:19] כן פי’ רשי. אבל, יש לעיר שרשי גם מזכיר מה שאוושא מילתא. אבל, במקום אחר שמזכירים אוושא מילתא (כה), לא משמע שרשי מפרש כן. אולי צריכים לצרף שניהם, ולומר שלא חוששים שנראה כעושה מלאכה ולכן יקילו בני אדם לעשות מלאכה, אלא שזילזול יו"ט הוא להראות שהוא עושה מלאכה. ותחשב. אז, אולי יש לומר כן בשנים אלו.
[fn:20] סתימות גמ’ משמע שזה גם גבי אוכלים, וגם אם הם לצורכי אכילת י"ט.
[fn:21] יש לדון אם זה אף אם יש צורך בו לי"ט.?
[fn:22] הייתי אומר שכך הוא פי’ המח’, שדחוק לומר שיש שלא מחשבים אותו להיות טירחא, וגמ’ לא מזכיר שיעור. אז, היה נראה לומר שחולקים על כל שיעור, שבית הלל תמיד אומר שהוא מותר. (לב"ש, יש שיעור, אבל אין הלכה כבית שמאי.) אבל, ע’ לקמן (בתחילת פרק משילים) שמצאנו איסורי טורח. ויש לדון אם שם יש צורך לאותו היום בכלל או לא. אם אין צורך, קל לבאר שאוסרים טורח אם אינו לצורך אוכ"נ.
[fn:23] קצת קשה למה הוא יותר חמור מנטילת מתנות כהונה.
[fn:24] כן אומר גמ’. לא מזכיר באלו מה הוא דעתו, אם מכוון למצוא מדה, ואם הוא משנה כלל. ותחשב.
[fn:25] כן אומר המאירי; בלי זה לא פשוט מהו ההגדרה, ולא פשוט שיש הגדרה, אלא אולי מספיק שיש אפשרות שמשתמשים בו לצורך אוכל נפש.
[fn:26] ואם תאמר כיון שיש כבר היתר של "מתוך,” למה צריכים היתר של "הואיל.” ויש לומר שהוא כשאינו לצורך הנאה השווה בכל.
[fn:27] לעיל, הזכרנו שתי קולות; יש לדון מה הסיבה לרפיון זה- הראשון, השני, או שניהם.
[fn:28] מוקצה הוא גזי’ משום הוצאה, שאם אדם לא מטלטל דבר, לא יוציא אותו. (?)
