** (ב.)
חולקים בית שמאי ובית הלל בביצה שנולדה ביום טוב.
מצאנו ארבע שיטות בביאור המחלקת. בכל אחד, מסביר גמ', יש איזה בעיה שהכריח לאחרים שלא לפרש כן.
הארבע הם:
1. רב נחמן סובר שכאן מדברים על ביצה מוקצה. יש שני מיני עופות, יש עוף שעומד לשחיטה ויש עוף שעומד לגדל ביצים. אם בא ביצה ממין ראשון, כולי עלמא מודו שמותר לאכול אותו, שאם שלו היתה מוכנת מבע"י, שעומדת לאכילה, והוא אוכל כמו אם שלו, ואז גם הוא מוכן. אבל, אם בא הביצה ממין שני, חולקים ב"ה וב"ש. בית הלל סוברים שיש מוקצה (שאסור להשתמש בשבת במה שלא מוכן מבע"י, גזי' שמא יוציא אותו), ובכלל זה יש נולד (שמה שלא בא לעולם הוא, בהכרח, מוקצה), ובית שמאי סוברים שאין מוקצה, ואין נולד. (אף שמצאנו ששיטות של ב"ה וב"ש הפוכים בשבת, יש לחלק ששבת יותר חמור. אז, לחד גיסא, יותר ראוי לגזור שם, אבל לאידך גיסא, א"צ גזירה כ"כ, כי בנ"א כבר נזהרים.) (ב)
** (ג.)
הבעיה בזה הוא שאם כן יחלקו בשני מחלוקתים- אם יש מוקצה ואם יש נולד (שלא פשוט שיהיו תלויים זה בזה). אז, היה לב"ש ולב"ה לחלוק על התרנגולת ועל הביצים.
1. רבה סובר שהחשש כאן הוא הכנה. ממש"כ, "והכינו את אשר הביאו" דורשים שיש רק מין אחד של הכנה שמותרת- הכנת חול לשבת (זה כולל הכנת חול לשבת, הכנת חול ליו"ט, והכנת יו"ט לחול). אבל כל שאר הכנות (חוץ מהכנה מחול לחול, שמסברה פשוט להתיר) הם אסורות. כיון שביצה נולדה יום אחרי גמירתו, נמצא שיום שלפני יו"ט מכין ליו"ט. אז, אם יום שלפני יו"ט שבת הוא, נמצא ששבת הכינה ליו"ט. אז, גזרו רבנן על ביצים אלו בכל יו"ט. בית שמאי, לכאו', סובר שאין איסור הכנה או שאין הכנה קורה ביום שלפניו. (היה אפשר לומר שלא גוזר, אבל לשונו משמע שמתיר בכל ציור. ויש לדון, שלפי צד זה, אולי לא מתיר כשהתרנגולת מוקצה.) (ב:)
** (ג.)
הבעיה בזה הוא שמניח שאסור להנות ממה שמוכן מיו"ט לשבת^. האמוראים שלא מפרשים כן לא מודים לדין זה.
1. רב יוסף סובר שהחשש הוא שאם יאכל ביצה שיוצא מעוף, יאכל פרי שנופל מעץ. אם יאכל את הפרי, יעלה ויתלוש. (ואם תאמר, הרי גזי' לגזי' הוא, וכ',  "משמרת למשמרתי," ואז רק גוז' גזי', ולא גזי' לגזי'. וי"ל שכולא חדא גזי'. כן אומר הגמ', אבל לא כ"כ פשוט מהו התי'.) בית שמאי יסבור שאינו כל כך דומה, ואז אין סיבה לגזור, או שאין אומרים כאן ש"כולא חדא גזי'." (ב:, ג.)
** (ג.)
הבעיה בזה הוא שסובר שביצה דומים לפירות, אף שביצה בלועה, ופירות לא בלועים.
1. ר' יצחק ורבי יוחנן סובר שהחשש הוא שאם יאכל ביצה שיוצא מעוף, ישתה משקים שיוצאים מפרי. אם יאכל את המשקים, יסחט פרי. . (ואם תאמר, הרי גזי' לגזי' הוא, וכ',  "משמרת למשמרתי," ואז רק גוז' גזי', ולא גזי' לגזי'. וי"ל שכולא חדא גזי'. כן אומר הגמ', אבל לא כ"כ פשוט מהו התי'. בית שמאי אולי לא מדמים אותם או סוברים שלא אומרים כאן ש"כולא חדא גזי'" או סוברים שמשקים היוצאים מפירות שלא עומדים לסחיטה מותרים. (ג.)
** (ג.)
הבעיה בזה הוא שאינו כל כך דומה למשקים, כיון שמשקים עומדים לשתייה, וביצים עומדות לאכילה.
עכשיו, נבאר את הדינים שלו:
1. תרנגולת העומדת לגדל ביצים:
  1. הו"א של גמ’- אסור, כיון שנולד הוא.
  2. רב נחמן[fn:1]- זה תלוי במחלקת אם יש מוקצה או אין מוקצה ביום טוב. רב נחמן מחדש שאולי אין מחלקת של מוקצה ביו"ט ומח’ של מוקצה בשבת תלויים זה בזה. שבת יותר חמור, ואז יש יותר סיבה לגזור, אבל בנ"א כבר נזהרים.
רב נחמן מפרש שזהו המחלקת בין ב"ה וב"ש, שכאן ב"ה מחמיר וב"ש מיקל. שאר השיטות לא מגידים לנו מה חושבים על זה. אף אם סוברים שאין בעיית מוקצה, יהיה בעיה שיש לנו בתרנגול שעומד לאכילה, כמו שנבאר לקמן, בע"ה.[fn:2]
1. תרנגולת העומד לאכילה:
  1. בית שמאי, בית הלל (לפי רב נחמן)- מותר.
  2. בית הלל (לפי רבה, רב יוסף, ורב יצחק)- אסור.
בכל זמן שהוא אסור, יש לדון בכמה דברים:
1. דין ספק שלו:
  1. לפי רב נחמן, זה ייתלה במחלקת תנאים בזה (כד.).
  2. לפי רבה, ייאסר, כיון שספק דאו’ לחומרא. (ג:)
  3. לפי רב יוסף, מחלקת הוא. סתם גמ’ אומר שהוא מותר, כיון שספק דרבנן לקולא (ג:), אבל רב אשי אומר שהוא אסור, כיון שהוא דבר שיש לו מתירים. (ג:)
2. דין תערובת שלו. יש שני סיבות שלא ייבטל"
  1. ביצים הם דבר חשובים. בזה, מצאנו מחלקת תנאים.
  2. ביצה זו היא דבר שיש לו מתירים. נראה שיש מחלקת אמוראים אם זה עושה שאין ביטול אם האיסור הוא רק דרבנן[fn:3]. אז, נמצא שלרבה בוודאי אין ביטול, ולשאר הצדדים, אולי יש ביטול. אם יש ביטול, יהיה ביטול ברוב, כדין דאו’ של ביטול.[fn:4]
3. שחט ומצא בה ביצים. זה לא פשוט לי. יש בריי’ שמתיר את זה. גמ’ מסביר למה זה מותר לפי רבה (לא נגמרו מאתמול, כיון שלא יצאו[fn:5], ואז אין טעם הגזי’ שייך בהם. לא גוזרים מח’ ציור שיצאו כיון שמילתא דלא שכיחא הוא). לא מבאר לפי שאר השיטות. לפי רב נחמן, לכאו’ אין חילוק בין זה לשאר ביצים, כמו שאין חילוק בין זה לעוף, ואז צריך לומר שב"ש הוא. לפי ר"י ור"י, אולי צריך לומר שב"ש הוא, או אולי יש לומר שלא דומה לפירות ומשקים כיון שלא יצא ממנו, אלא נטל אותו מתוך העוף.[fn:6] (ב:)
4. אם כבר יצא בה רוב לפני יום טוב וחזר לתוכה, רבי יוחנן מתיר. גמ’ דן אם רב סובר כר"י או חולק על ר"י. (ז.)
5. לפעמים, לא פשוט שמותר לאכול אותו גם ביום אחרי שנולד. זה נמצא כשיום שלאחריו הוא גם יום קדוש. מצאנו ארבע ציורים כזה:
  1. שני יו"ט של גליות. חולקים רב ורב אסי. רב אומר שמותר, כיון ששני יו"ט הם רק מנהג מחמת חשש שנסתפק איזה יום הוא הנכון. לכן, מתירים ביום שני ממ"נ. ר"א אוסר שחושש שהם קדושה אחת. (ד:)
  2. שני יו"ט של ר"ה. אם נולד בראשון, רבי יהודה מתיר בשני, כמו בי"ט שני של גליות, ורבנן מחמירים. גמ’ מבאר שיש יותר סיבה להחמיר, כיון שאסרו אותו מפני שגזרו לקיים שני י"ט לפעמים אף בלי ספק. בטלו את הגזי’ של שני י"ט בלי ספק, אבל דן אם גמ’ אם זה מבטל גזי’ לאסור ביצה ביום שני או לא מבטל (או מפני שלא בטל אותו בפי’ או מפני שחשו שיחזר להיות שני י"ט בלי ספק). (ה)
  3. שבת ויו"ט. יכול להיות שתי סיבות לאסור. יכול להיות אסור מפני שלשני הימים יש קדושה אחת (כיון שלשניהם יש קדושה, והם קרובים זה לזה, לאיזה סיבה נעשה קדושתם אחת, ומה שנאסר ליום ראשון נאסר ליום שני) ויכול להיות אסור מפני הכנה של רבה (שהוכן ביום ראשון כשנולד אז). רב אוסר מחמת טעם שני. רבי יוחנן מתיר. הלכה כרב. (ד)
  4. יו"ט ושבת. לא מחלק גמ’ בין ציור זה לציור של שבת ויו"ט, ואז נ’ שדינו שווה.[fn:7]
6. אפרוח שנולד בי"ט:
  1. לפי ראב"י, אסור עד שפותח את עיניו, מטעם כשרות.[fn:8]
  2. לפי רבנן, מותר מטעם כשרות כשנולד, אבל חולקים אם נאסר משום י"ט.[fn:9] שמואל מתיר, כיון שמתיר א"ע בשחיטה, אבל רב אוסר. (ו)
* Footnotes
[fn:1] אף שיש חולקים על רב נחמן בגמ’, לא מוכרח שחולקים על נקודה זו, אלא, להיפך, משמע מגמ' (ג.) שמודים לנקודה זו.
[fn:2] לא פשוט שבאמת יש לו אותו הבעיה. אפשר לומר, לפי רב יוסף ורב יצחק, ששם אינו דומה כל כך לציור שגוזרים ממנו, ואז אולי אין גוזרים.
[fn:3] זה לא כל כך פשוט לי. יש שני סוגיות בזה. בסוגיה ראשונה (ג:, ד.) נראה שגמ’ מניח שלא יבטל. אבל, לקמן בסוגיה שנית (ד:) נראה שיש חולק שאומר שלא בטל.
[fn:4] יש לדון בזה, שאולי כיון שהוא דבר שיש לו מתירים, מחמירים בו קצת.
[fn:5] עיין בתוס’.
[fn:6] יש לדון, שלכאו’ זה יהיה סיבה להחמיר. אבל, זה צריך הגדרה, כמובן, שהרבה הרבה פעמים אדם נוטל דבר מתוך דבר אחר בשבת, כמו אם נוטל את הטלית שלו מן השקית שלה.
[fn:7] צריך ביאור, שאין איסור הכנה מיו"ט לשבת. אז, קשה איך רב יאסור. אולי אוסר בלי עירוב תבשילין. גם יש לומר שע"ת לא יהני לזה כיון שהוא כל כך חלוק מתבשיל. וצריך לחשוב.
[fn:8] איני יודע מתי זה קורה; גמ' משמע שהוא מאוחר יותר מיום, ואז דיון זה לא נוגע. עדיין אולי נוגע בשני י"ט. כמו כן, יש לצדד שפתיחת עיניו הוא הכנה.
[fn:9] לכאו', אם נאסר יהיה אסור מחמת הכנה. צריך לחשוב אם שאר הגזי' קיימות כאן.
