* יב:
** ומתבייש -
יש לדון אם ר"ל שאחר מבייש אותו בו או שהוא, כשחושב עליו, נרגש בבושת. ותו"ת.
* יט.
** פסוק אחד -
יש לדון מהו הדיון:
1. מצווה בחצי קריאה.
2. מה צריך לקרוא (שכבר חלקו בזה).
בין כך ובין כך, קשה ל"ל"א שמשנה ראשון סובר שצריך לומר כולו ושני סובר שרק קורא זה, שכבר חלקו. ויש לומר שלשון אפילו משמע שלא מקיימים מצוותם בכך.
* כ.
** כי קאקי -
אולי ר"ל שנ' כאנשים זקנים- ומי מתאוו לאנשים זקנים. (עיין בגיטין עג.)
* כא.
** אלא יקצר -
קשה, דילמא הא לא התחיל, יחשב.
* כא:
** ובמשנה תורה דריש - ובמשנה תורה מנא לן -
קשה, שזה רק אם מופנה או מוכח, כמו שאומר ביבמות (ד.).
כיון שבר"י דנים, צריך רק ברייתא זו. ותו"ת.
* כג.
יש לומר שדנים אם נניח שלא היה ראוי לעמוד נקביו או שרק לא רצה.
** כשאין יכול לעמוד -
נראה ששינוי לשון זה הוא מפני שלשון ברייתא ולשון אמוראים חלוק. ותו"ת.
** שמור נקביך -
כמובן, עיין ביבמות (קג.).
** להשתין מים -
נמצא שדין ד"א ה"ה רק אם מכוון לפנות שם.
** עלה לראש הגג -
ואם תאמר איך ידעו. ואולי אמר לפני מיתתו. גם יש לומר שזונה הודה.
* כג:
** לא ישתין -
לכאורה, דן גמרא בזה לעיל (ע"א).
** ולאביי -
זה רק בבגד מת. יש שני ציורים שם, חד שבו כולי עלמא מודו לאביי וחד שכולי עלמא מודו לרבא. נראה לח’ למה נדחה לזה. ועיין שם בגמרא ותחשב.
* כד.
** והיכא מנח -
כמובן, צריך ביאור איך זה אינו אכתי קשה מברייתא. ואולי ר"ל שנדע שברייתא אינו נכון, כיון שסברה כל כך טוב הוא.
** אייתי לי תפילין -
קשה מהיכי תיתי שהוא יום טבילה, דילמא בא לחדש דין לישן בפני עצמו, שמשמע מגמרא שיש חידוש בו. ותחשב.
* כד:
** אם אמרה -
הפשטות הוא שר"ל שאף אם בוודאי אמרו ר"י, ואז אי אפשר לומר שאין גדול כרבי יוחנן אומר כן, לא היה מאמין. גם יש לבאר על פי גמרא פסחים (נא:). ויל"ד.
** אר"י היה מהלך -
חושב אני שלא מצוי שיהיה ר"ה אומר דבר בשם ר"י. ונראה שלכן צ"ל שאם אמר ר"י בפיו…, ואף שאין לדון אם באמת אמרו ככיון שנראה כל כך מוזר. ויש לדון שלא כל כך מוזר שיאמר רבב"ח דבר בשם ר"ל.
* כה.
** בספקן לא גזור -
ואם תאמר תדייק שענין ספק דרבנן לקולא הוא שרק גזרו על וודאי. יש לדחות שצריך אף זה.
** אמר רבא -
יש להעיר שמחלקת אמימר ומ"ז בא אחר זה, שהיו אחריו.
