* יט.
** למימר הכי -
כמו"כ הוא ב"הרבה חטאתי."
* יט:
** בבית הפרס -
ליקרייהו- משמע שאכתי עובר, אלא שמחלוץ משמע שרבנן אמרו דבר, וצריך לשמוע לרבנן מחמת איסור לבזות רבנן, שבזיון הוא להם שלא יהיו דבריהם נשמעים. ודע שאם נשיא גזר, יהיה נכנס למחלקת אם יכול למחול על כבודו.
יותר היה נראה שרל שאל גזרו, ואז אינו בכלל יקרייהו כלל. באמת, צריך ביאור למה יגזרו וימחלו, ולא רק שלא יזגרו.
** לקראת מלכי -
ראב"צ- כתבתי לציין לזה בשי"ח ש"י (רביעי).
* כ.
** רבי יוחנן -
שופריה- לכאורה, העיקר הוא ההמשך, שדן בשופריה של רבי יוחנן.
* כא.
** ולואי -
בה"ג- כתב לשון יחיד. עיין במקום אחר שכ' לשון רבים.
** תוד"ה ההוא בדברי תורה -
לכאורה, הוה מצי להקשות ממשנה קמא, ממה בא, אי לא מקרא. צריך ביאור מהו התירוץ. יש לדון אם אסמכתא יהני לזה. אולי יותר מסתבר לריטב"א שיהני. ויש לדון לשניהם.
לולי תוס’, יש לומר שכ’, "והגית בו" (כוונתי לדרשת גמרא מנחות צט:). נראה שנוכל לומר ש"בשבתך" קאי על לימוד רק לרבי יוסי, שלרבנן, אינו רק בשבת ובקום, שלעולם הוא. נראה, אז, שתנאי הוא, ואין קושיית תוס’ וקושיה שלנו קשים.
* כג.
** שלא תצא -
לכאורה, אומר כאן שני סיבות. ויש לדון אם צריך שניהם. אולי שני הוא רק סימן. ויש לדון.
* כג:
** גליון הש"ס -
עיין בגר"א. ודע שאז לשון ד,יפיל" ק"ק. ואלי הו"ל לומר יפלו (כמו ברש"י לעיל).
** מהלך עשרה -
דאי לאו הכי, אין חילוק בין י פעם ד או ד פעם י. ויש לדון, שהיה אפשר שיש נפק"מ מתי יכול או מתי צריך להפסיק.
* כד.
** תוד"ה והתניא -
אולי שאני כאן דגם כ’ בניו.
* כד:
** למטה -
איני יודע מהו כוונת רש"י, שמשמע שאין חילוק בין למעלה ולמטה אלא אם מוציא קול או לא.
** ואומר -
יכול להפסיק- גם הומ"ל שנצרך, ואז אינו הפסק (כמו, “הבא מלח").
* כה.
** כל הנשמה -
גם יש לומר שהוא הפה שממנו יוצא נשימה כשהוא מתהלל.
