** דף ח ע”א מס -
לימוד זה לא קל להבין. אף שהמס שנזכר בתוך הפסוק הזה מדבר על מס של חולין, לא נראה מזה שלשון מס הוא לשון של חולין. הרי, כוונת המילה לא בא על מה שהוא חולין, אלא על מה שהוא מעות שצריכים לשלם למלך. מה שהוא חולין אינו פרט גדול בחשבון השם של המס.
** דף ט ע”א בגזל -
לא נוכל לראות מזה שבעריות מדבר הכתוב, שרק נוכל לראות שאינו בלאו שניתק לעשה ולאופן לבטל אותו, כמו גזל. נראה שאולי מתחילה רוב לאווים לא הולכים בכלל זה, כי כלל זה הוא רק מה שנאסר מחמת תוצאתו (שהמעשה בטל מיד). ויש לדון.
** למי שהיה מתוקן -
יש לדון למה מוכרח שמדברים על מי שהיה מתוקן בכל, שאפשר לומר שקוראים לו מעוות על שם שהיה שמתוקן במה שלא היה עובר על חטא זה. אז, אם מי שלא הוליד ממזר מוליד ממזר, נקרא מעוות, כיון שעיוות את תקנתו בענין הולדת ממזרים.
** שכן אינו חלוק -
קצת תמוה מה שלא נקט לסיבה מה שיום שביעי יותר קרוב ליום עיקרי (יום ראשון) משיום שמיני קרוב לו. גם ק”ק מה שלא אמר חילוק ממה ששבעה ימים הם רק שבעה ימים, וריבוי שמונה ימים יהיה שמונה ימים. ותחשב על זה. אולי חדא מתרי ותלת טעמי נקט. (אבל, היה נראה לו לבחור את טעמים שלנו, שהם נראים יותר עיקרים.)
** דף ט ע”ב אשר לא עבדו -
לא רצה לומר שנחשב כאילו לא עבד את ה’ כלל, שאומר שהוא צדיק גמור (ואגב, רואים מזה שיכול אדם להיקרא צדיק גמור אף אם חסר מצווה (אולי מפני שהולכים בתר רוב); ויש לדון, שאולי מדברים כשנאנס), אלא אומר שלא עבד את ה’ עבודה זו. מה שמחדש הוא שאף אותו פעם אחת של לימוד ממאה למאה ואחד חשוב עד כדי שנקרא עבודה לה’.
** עניות -
זה לא אומר שתמיד טוב לישראל להיות עני; זה רק אומר שטוב שה’ יתן לנו עוני. אולי זה מכוון לומר שיתן ה’ לנו עוני מתחילה, כי טוב לנו לעשר את עצמו באמצע חיים שלנו, ושלא להוולד עם עושר. ותחשב על זה.
** דף י ע”א לבר מדשמואל -
בהכרח, יש דיחוי למקור של שמואל, שהרי תנא אמר שאין לו מקור. יש לדון, שכמו שחלק שמואל על כל תנאי הברייתא, יחלוק גם על המשנה. יש לחלק, שכאן חולק על סתם משנה.
** דאמר שמואל -
אז, קשה, שהרי שמואל לא סובר שהמקרא הזה מוציא מידי דרשה שלו. אז, לפי שמואל, לא נכון שמקור שלו הוא הכי טוב.
** טבא חדא -
יש להעיר שכאן כל תנא חולק על כל שאר התנאים. אז, אין דבר אחד שמחדש שמואל (חוץ ממקור זה), אבל לא מחלק מה ששאר התנאים טועים.
** כל נדיב לב -
עיין בפרש”י. נראה שדורש כן ממה שאומר “נדיב לב” על שעת הבאה. לולי רש”י, היה אפשר לפרש שמ”נדיב לב” דורשים שסיבת החיוב אינו (רק) דיבור, אלא מחשבה שלו. כיון שכן, אולי מסתבר שיוכל לשאול עליו, שזה מבטל כוח דעת ורצון שלו לחלות. ותחשב.
** אשת כהן -
ע’ ברש”י, שכ’ שדורשים מ”היא.” גם אפשר לומר שדורשים ממה שנאמר לכלל בפני עצמה. לא נאמר שאם איש בא על אשה שלא באונס..., אלא כ’ שאם איש בא על אשה, ואין הציור אונס.... זה משמע שלא תמיד צריכים מה שאינו אונס. ותחשב על זה.
** דף י ע”ב מלאכת מחשבת -
לכאו’, קושיית הגמ’ היה שאין לו אף שערה, ואין לו שום מקור. אז, מבאר שיש לו מקור ממה שצריך מלאכת מחשבת (וש לזה קצת מקור מן הקרא, כמו שמפרש”י), ואחרי זה מעורר שעדיין לא נכתב כלל זה בפי’ בקרא.
לקמן, לא מכוון לומר כן, אלא מכוון לומר למה נחשב רק שערה, ולא יותר.
** אלא מעתה -
קשה, שנקשה כן גם למסקנת הגמ’, שאטו רק חלב של חגיגה אסור ללון, ולא חלב של שאר קרבנות.
** דף יא ע”א לכדרבי -
לכאו’, זה נכון גם לשאר מקורות של אותו הדין (כולם מובאים בתחילת פרק החובל בבבא קמא).
** מיכתב -
אם ממש כתוב, לא היה אומר לנו לשון של “יש להם על מה שיסמכו,” שאינם סומכים, אלא הם שם. יותר מזה, לא יצטרך משנה להגיד כן לנו.
** מים שכל גופו -
יש לדון אם אומר שאין דרשה זו כל כך פשוטה, ואין השיעור כל כך פשוט (שמי אומר שרבנן נכונים, ועוד שלא נדע בלי רבנן).
** אמה -
לכאו’, זה שיעור של איש. מעניין שנקרא “מי נדה,” ועדיין משערים אותו על שיעור איש, ולא אשה. אולי שיעור אינו שסתם איש יכול לבוא, אלא שסתם אדם יכול לבוא, וסתם אדם הוא איש. יש לדון.
** דף יא ע”ב גופי תורה -
יש לדון אם רצה לומר שדינים שיש להם סמוכים ודינים שאין להם סמוכים שניהם הם דינים שהם עיקרי התורה, או אם רצה לומר שכתיבת דינים שיש להם סמוכים וכתיבת דינים שאין להם סמוכים שניהם נכתבים באופן שהם עיקרים. ותחשב על זה.
** דף יב ע”א הסתכל -
אז, מה שאומר ה’ שהמליך אחרי שבאו אותו הדור הוא קשה להבין. הרי, ידע כבר שיהיו רשעים. (תמיד לא קל להבין איך ה’ לא יודע דבר. אבל, כאן יש סתירה מפורשת.) כמו כן, קשה לומר שה’ עושה דבר שהוא תוצאה של בחירתם קודם שיבחרו. (באמת, זה לא נראה כל כך קשה לי, שהם בוודאי יבחרו דבר אחר- רצה לומר, נודע לה’ מה שיבחרו- אבל עדיין הם יבחרו אותו. ותחשב.)
אולי ידע שיש צד גדול שיהיו רע (כך ברא אותם), ולכן חשש שלא יהיה האור שם. אבל, לא ידע שבוודאי יבחרו ברע. לכן, ברא אותם, ויכול להיות שהמליך על מה שברא אותם. אבל, לשון גמ’ (”ראה שמעשיהם מקולקלים”) לא משמע כן.
** נתלו -
היה אפשר לומר שאין זה מח’, אלא קודם שתלה אותו ה’, היה יותר קרוב, והיה קל לראות ממקום למקום.
** דור המבול -
קצת צריך ביאור למה גנז אותו הרבה זמן לפני כן.
** גער -
יש להעיר שיש חכמי האומות בזמנינו שטוענים שהעולם תמיד מתגדל ומתקטן ומתגדל ומתקטן. אולי זה כוונת הגמ’. אבל, דע שעכשיו הוא מתגדל, והיה צריך לומר שהיה עוד גערה מה’.
** כב שנה -
איני יודע איזה שנים היו. הרי, יודעים שלמד לעשרים וארבע שנים, ושוב חזר עם הרבה תלמידים. יש לדון אם היה לפני כן (ואז היה רוב של אותם השנים) או אחרי כן (אחרי שכבר היו לו הרבה תלמידים).
** דף יב ע”ב אוי להם -
צריך להיות פירוש לאגדתא זו, שקשה למה אומר לשון זה (”אוי להם”), שמה לנו על מה עומד העולם. צריך לומר שמכוון לעמידה רוחני וכדו’. ותחשב.
** עולם הזה -
נמצא שעולם הזה דומה ללילה, וגם גהנם דומה ללילה. אז, הכל דומה ללילה חוץ מעולם הבא.
** דומה ליום -
אולי לכן יום בא אחרי לילה, כי חיים בעולם הזה קודם שחיים בעולם הבא. ותו”ת.
** רוחות -
עיין במשפרש”י. כמובן, זה דבר מאד מעניין.
** דף יג ע”א אין מוסרים -
קשה למה לא אומר אותו משום מש”א בסנהדרין שעובר משום “מורשה קהלת יעקב.”
** נח נפשיה דרבי יוחנן -
יש שסוברים שרבי יוחנן חי זמן ארוך. לפי זה, צריך לומר שרבי אלעזר חי יותר זמן. עדיין, בפעם ראשונה, אמר שלא היה זקן מספיק. לכאו’, רק גר בסוף חיי ר”י. אבל, קשה, שאם נדקדק באל מי דיבר ר”א, לא משמע כן כל כך. וצריך לעיין.
** סבי דפומ’ -
עיין בסנהדרין (יז:), שאומר שסבי דפומפדיתא הוא רב יהודה. הרי, רב יהודה היה קודם רב יוסף (רב יהודה היה תלמיד של רב ושמואל, ורב יוסף היה רק תלמיד של תלמיד של רב ושמואל), ואז כל סיפור זה מוזר.
** מאי חשמל -
העיר א.ל.ל.ל.ל.ל.ל.ל. שגמ’ מספר סיפור של ילד שמת כיון שהבין בחשמןל, ואומר שאל צריכים לחוש לזה, כיון שרוב בני אדם לא יבינו אותו. מיד, מתחיל לדון מהו חשמל.
** דף יג ע”ב תחת נבוכדנצר -
ע’ בגמ’ בפסחים שדן למה גלו לבבל. יש להק’ למה לא תי’ שהגלו לבבל כדי שיגלו למלך שכבש את כל העולם. נראה שהוא מפני מה שאמר גמ’ זה, שכל מי שהיה כובש את היהודים היה מלך על כל העולם כולו. ותו”ת.
** אותם שמכסות -
לכאו’, אין מקור שיש שמכסות רגלים, אבל נראה שיש דבר חסר שם, ומסתמא, אז, יש כנפים כזה, והם החסרים.
** דוסאי -
עיין בברכות (מט.), יומא (כב.), ב”ק (יג.), סנהדרין (נב.), זבחים (קטז:), ומנחות (נב.), ששמו נכתב “דוסתאי.” עיין בתמורה (ח.) ששמו נכתב “דוסאי.” אולי שני אנשים שונים הם.
** מן הצפון -
עיין במה שפרש”י. קצת קשה, אז, למה קורא לא”י “מערבא,” ולא “דרומא.”
** דף יד ע"א ופליגא -
איני מבין מהיכי תיתי שיש מחלקת, שאפשר לומר שזה וזה עושה מלאכים.
** שר חמישים -
נוכל לפרש שזהו פירוש של "שר חמישים" כשאמר כן גמ' לעיל.
** חומשים -
יש לדון אם רצה לומר שיודע פשט הפשוט של הפסוקים או שיודע טוב איך לדרוש. (גם אפשר שצריכים לדעת את שניהם.)
** דף יד ע"ב חיישינן לשמואל -
נמצא עוד לשון חשש לקולא. עיין בשבת שמצאנו כעין זה, גם בנוגע שמואל. אולי זה היה לשון של שמואל, שהיה אומר לשון חשש אף על קולא. ותחשב.
** דף טו ע"א חוץ מאחר -
אפשר לפרש שלא רק נתן לו כוח למחק כל זכות שהיה לו אלא גם העתידים. לכן, לא היה אפשר לו להיות צדיק. (כמובן, כל זה קשה להבין, איך אפשר להיות שאדם יאבד זכויות שלו.)
** כנגד -
לכאו', רצה לומר שהוא דומה לו, אבל הוא יותר קטן.
** יש לו שני חלקים -
קשה להבין את זה; זה משמע כמה שאומרים הנוצרים שיש לאדם חובה מעוון הראשון. אולי רוצה לומר שיש לו יצר הרע, שיביא אותו לגהנם ויש לו יצר הטוב, שיביא אותו לגן עדן. ותחשב על זה.
** דף טו ע"ב דעסק באו' -
נמצא שמי שעסק בתורה, אף אם עבר על עבירות, לא נכנס לגהנם. (צריך לציין בגמ' בסוף המסכתא, שאולי הוא שייך לזה.)
** כי קא נח נפשיה דר"י -
יש להעיר שיש אומרים שרבי יוחנן חי זמן ארוך מאד (יש אומרים שחי ארבע מאות שנה). אז, הוא היה הכי גרוע להכניס את אחר לגן עדן, שהיה צריך לחכות הרבה זמן. (אולי מפני זה חי לזמן רב.)
** קלני -
צריך ביאור למה מצטער, שגמ' אומר שזה טוב לעולם. אולי רבי מאיר חולק על זה. גם יש לומר שה' בוכה על מה שבא לידי כך, שרוצה שלא יצטרך להצטער.
** גדול -
עיין ברש"י, שמשמע שהחשש הוא רק שילמד ממעשיו, ולא שמחמת מעשיו יש דבר רע בתורתו (או שזה גרם את מעשיו הרעים) שנחוש שילמד.
** דף טז ע"א יוסי בן יועזר -
יש להעיר שמח' ראשון שהיה נמצא בדין דרבנן, ואינו דבר שנשכח ממה שלימד לנו משה. (כן יוצא לפי מה שיסבור גמ' לקמן.)
** לא נחלקו -
יש לדון אם רצה לומר שהודו לשיטה אחת או שלא נחלקו על זה, שלא דבדרו עליו קודם שמנחם יצא.
** דף טז ע"ב אבא אלעזר -
יש לדון מה רצה לומר:
1. שמו היה "אלעזר," וקראו לו אבא מחמת כבוד, ולא היה אבא של אלעזר.
2. שמו היה "אבא אלעזר," ולא רק "אלעזר." "אבא" היה שמו, ולא אומר כמו "רבי."
** דף יז ע"א תפסת מרובה -
יש לדון למה לא נאמר שנקיש לחומרא. ויש לדון מהו החומרא כאן. אפשר להיות שאין חומרא (שלכל צד יש חומרא וקולא). גם אפשר שהחומרא הוא לחייב אותו בתשלומים עוד יום. אז, צריך לומר שכלל זה (תפסת מועט) דוחה כלל של היקש לחומרא.
** ואין סומכים -
עיין במה שפרש"י. יש להעיר שאז יש מחלקת על דין דאו' (אלא שלא מכריח מחלקת במה יעשה אלא בדין דרבנן), וגמ' משמע שהמחלקת הוא רק בדין דרבנן. ותחשב.
** דף יט ע"א גוד אסיק -
אין זה גוד אסיק רגיל, שאז לא יצטרך להיות על ראשו, אלא כל מקום למעלה מן המים. אולי כן רצה לומר, אבל דחוק. יותר נראה שגם צריך חיבור זה אל המים.
** דף יט ע"ב מאיר -
עיין ברשי. יש לציין למקומות רבות שמצאנו שכשבריי' מביא שם אחד של תנא משמע ששאר תנאים חולקים. יש לדון למה לא יהיה כן כאן. ותחשב.
** דף כב ע"א סל -
נראה שהסיבה שאין בזה אף לא פלוג הוא שכאן אינו נקב, ואינו פתח, אלא כאן אין שום דבר שמפסיק באותו צד. לא מסתבר בכלל שאדם יעשה כלי כזה אם אין הנקב גדול, שאז אין אויר בכלי.
** כמאן מקבלינן -
נמצא, לכאו', שהורגים אדם על פי עדות שכשר רק משום איבה. אולי לא מכשירים אותם אלא לדיני ממון, ומוצאים דרך לפסול עדות שלהם (שיש הרבה כזה בדיני מיתה).
** דף כו ע"א חברים -
מעניין שמפרשים את זה לומר חברים ממש. הרי, כשמברכים את החדש אומרים לשון כזה, אף שלכאו' לא מאמינים כל מי שהוא בתוך בית הכנסת.
