* ב:
** לשון ראשון -
רש"י מפרש שלשון ראשון שלו מקשה על הגובה. יש להעיר שאז לתי' שני נשאר קושיה על רבי יהודה.
גם יש להעיר שללשון שני, לא פשוט מהו הקושיה על רבי יהודה, שהוא סובר שיכול להיות פתח של עשרים רוחב. ונראה שאינו קשה עליו, וכשאומר ששניהם ילמדו אותו מכאן, הקושיה היא שרבנן ילמדו אותו מכאן. גם רבי יהודה ילמד מכאן במציאות, שלמה יחלק על רבנן, אבל אין בזה קושיה.
* ג.
** נעשים -
לכאו', יש לחלק, שיש לומר שרואים למטה כשל ברזל, שלמעשה הם מחוברים לדבר שמחזיק אותם, שהוא למעלה, אבל לא נוכל לומר שנראה שצילתו מרובה מחמתו, שציל של דבר אחר הוא שמרובה מחמה, ואין זה צל שלהם. ותחשב.
* ג:
** ולמטה -
רצה לומר, צריכים לקרוא "משפת עשרים, וכן למטה, הוא צריך להיות בשפת עשרה.”
* ד.
** אמת כלאים לאפוקי -
נראה שרבא מפרש שכשאומר "אמת כלאים," בא לאפוקי אמות שלא נוגעות להלכה. במילים אחרים, רצה לומר אמות שאנו נוהגים, כמו אמות כלאים, הם בשל שש, אבל יש אמות שלא נוהגות, כמו אמות שהיו בבית המקדש, שהם בני חמש. ותחשב.
אבל, עיין ברש"י לשא כל כך משמע כן, אלא משמע שבא לחדש דין בשל כלאים, דהיינו שלא יהיו אמות קטנים של שש, ואגב גם חידש שיהיו של שש. מה שהוסיף שיהיו של שש בוודאי בא למעט אמות אחרות, והאמות אחרות הם מקצת אמות של בית המקדש.
** מחיצה -
עיין במה שפי' רש"י (והוא מגמ' לקמן ומגמ' בסוכה). קצת קשה למה אין עשרה טפחים של מחיצה בכלל שיעורים. ותחשב.
* ד:
** רובו -
רש"י פי' שזה רובו של שער. לפי רש"י, צריך לומר שהגדר הוא שכדי להיות מחיצה, צריך להיות רובו של אותו חלק מן הגוף שיש בו חציצה. ותחשב. ויש לדון, שאולי זה בדווקא בשער, שהוא נמנה בפסוק בפני עצמו, כמו שדרש גמרא לעיל. אבל, לא נראה שיהיה יותר חמור ממה שבא רק מדרשה. ויש לדון, שאינו יותר חמור, אלא יותר דבר בפני עצמו, וממילא הוא יותר חמור. ותחשב.
* ה.
** היכר של מטה -
צריך ביאור מהו הצד שישוו, שהם היכירים בדרכים מאד שונים, שמה שלמעלה הוא ההיכר, ומה שלמטה הוא מקום שבו צריך לעמוד כדי שיהיה מה שלמעלה היכר. נראה שרצה לומר שלא פשוט מה יהיה השיעור, ואז אפשר לומר שנקטו שיעור של ההיכר עצמו, כיון שזה בא רק לעשות את ההיכר להיכר. ותחשב.
** ברוחק -
עיין בציור רש"י. כן מבואר מן הגמרא לקמן. אבל, אז צריך ביאור איך זה נוגע לגמרא שדן בו בענין מחלקת אביי בגודל המבוי, שזה רק יהיה נוגע אילו היה נכנס לתוך המבוי במשך ארבע אמות. ותחשב. צריך לומר שכיון שהגיע לשיעור חשוב, דהיינו שיעור מבוי, הוא שסובר גמרא שמסתבר שלא יהיה לחי עוד. ודחוק.
* ה:
** מאי אמרת -
יש להעיר שמצדד בזה שלא דק. אם כן, עדיין נחוש שלא דק, ובאמת הוא גדול משמונה. אז, אולי אין רובו, והוא יותר מארבע אמות. נראה שאיה"נ, ועדיין יש בו ספק דרבנן להקל. (זה מבאר למה צריך לסמוך על ספק דרבנן להקל, אחרי שמזכיר ספק ספיקא.)
* ו.
** לא עבדי -
יש להעיר שכנראה עושים פתח לחצר בקרן זוית, כמו שהוכיח גמרא לעיל לשיטה שמבוי משכו בארבע טפחים. ותחשב.
** מטפי ביה -
צריך ביאור למה לא יכול להיות שזה בצד זה ומשך יותר ממנו.
* ז.
** כעין מחלקת בית שמאי ובית הלל -
צריך ביאור מה זה אומר ומה הוסיף.
* ח:
** אלכסון אינו היכר -
יש לדון אם רצה לומר שאינו היכר למה שיוצא או שאינו היכר בכלל. הנפקא מינא פשוט - אם, כשעשה אותו באלכסון - רק אסור שלא כנגד הקצר, או גם אסור כנגד הקצר, כמבוי שאין בו לחי.
** אין בו עשר -
יש לדון מה יהיה אם יש עשר כנגד שפה חיצונה של העודף, אבל אין עשר כנגד אמצע העודף, אם יכול לעשות אותו באלכסון שפונה לשם, ולהתיר עד שם. ותחשב.
* ט.
** חבוט ולבוד -
יש לדון למה רק נאמר אחד:
1. לא יכולים לצרף קולות.
2. בציור כזה לא נאמר לבוד (או לא נאמר חבוט, או לא נאמר אחד מהם[fn:1]). יש לדון למה:
1. שלבוד צריך להיות אל דבר - רצה לומר, לחבר אותו אל דבר. כאן, אם נשתמש בלבוד, עדיין הוא רחוק, שגם צריך חבוט.
2. שלבוד צריך להיות לצורך - צריך להיות גורם היתר. כאן, אינו גורם היתר, שעוד צריכים חבוט. ויש לדון, שגורם שיכולים להתיר על ידי חבוט.
** מסתבר מילתיה -
יש לדון אם חולקים מה כיוון רבי יוחנן, או שחולקים אם מה שאמר רבי יוחנן נכון. באמת, יש לדון אם יש הוכחה מרבי יוחנן, שיש לדון אם נאמר "תנא לברא" - לומר שאינו נכון - על בריי' שסובר שקצת ממנו נכון וקצת ממנו לא נכון. אפשר שבזה חולקים אביי ורבא (או אפשר שמודים שיכול להיות שיאמר כן, אלא שחולקים אם אמת כן), ואפשר שכולי עלמא מודים מה אמר רבי יוחנן, וחולקים עליו.
** משיכה -
עדיין יש לדון מה יהיה הדין אם שפתה חוץ משלש, ואז אין זה נוגע. אלא, הובא אגב מה שאומר גמרא שצריך להיות שהוא בתוך המבוי. אומר שזה בוודאי אינו אפשר, אלא נאמר לבוד. אבל, עדיין יהיה נפקא מינא אם צריך להיות שלש טפחים מן החיצון או מלפנים של המבוי. ויש לדון, שיש לומר שכל ענין לבוד הוא רק להביא אותו אל דבר אחר, והוא להביא אותו אל המבוי. אבל, אם צריך להיות בתוך המבוי (שיש מחיצה מפנימי שלו), לא נאמר בו לבוד כלל. ותחשב.
* ט:
** נראה מבפנים... -
נראה שזה יהיה נוגע לדיון הגמרא לעיל בהיכר מבחוץ או היכר מבפנים (לענין משמש תחת הקורה).
** קטנה וגדולה -
איני מבין את זה כל כך, שחשבתי שרק אומרים לבוד בפחות משלש, ולא בשלש. אם כן, נוקים אותו בבמצומצם ביניהם. נראה שעשר הוא גודל הפתח, ואז, כשנצרף רוחב המחיצות, יהיה פחות משלש ביניהם, ונאמר לבוד. ותו"ת.
** ארבע אמות -
מניח גמרא שצריך להיות שזה גודל מבוי, ולא שאז אינו עוד לחי, וכיון שבטל מלהיות לחי, והוא שיעור מבוי, נעשה מבוי. ותחשב.
* י:
** לא אטרחיה -
לשון זה קצת מוזר. לכאו', הייתי אומר שלא אמר את זה כיון שאין מעליותא בזה, הוא יותר טורח. לשון גמרא משמע שיש מעלה בזה, אלא שרבנן לא הצריכו לו לעשות אותו. על פי גמרא לקמן, נראה שיש מעליותא בזה (וגמרא כיוון לזה), והוא שאין פתח קטן שבני אדם יכנסו בו (שהפתח קטן הוא קטן מאד). ותחשב.
** עסלא -
יש להעיר שמעניין שלא אומרים שאויר של כל צד מבטל אותו, שלכאו', כשהוא מאהיל, מדבר כשיש אויר בכל צד. צריך לומר שלא מחשבים את האויר אם אין האויר חלק מ"מקום אחד" עמו. צריך להגדיר אותו, אבל נראה שזה נקודה חשובה.
* יא.
** לדברי הכל -
לכאו', זה רק מהני לפי רבי מאיר. לשון הגמרא משמע שמה שיש מחלקת היא גופא פירכא לכולי עלמא, ואף לרבנן. זה מעניין מאד.
** רב-
יש לדון אם רב מחמיר ברוחב ובגובה או לא. ותחשב.
* יא:
** יש ברגליה -
צריך להגדיר מה נחשב גג. ותו"ת.
** ארבע מחיצות הלכה למשה מסיני -
רש"י מפרש שארבע מחיצות יהיה הל"מ. יש לדון בזה, שהיה אפשר לומר שלומדים ממה שהיה במשכן, וחולקים מסברה מה היה קרק' החשוב שבמשכן. ותחשב.
** אגב -
אגב, יש להעיר על גמרא לעיל ברחב ארבע בפתח רחב שמונה, שיש לומר שהצד שלא מצומצם אינו ממש ספק, ורק מקילים עליו כיון שיש כעין ספק ספיקא. זה נקודה חשובה לענין הסוגיה, ונראה שהיא גם חשובה לסוגיות אחרות, שאם לא כן, נוכל להקל על כל דין דרבנן כשמצמצם, כמו אם פתחו ממש י. ותחשב.
* יב.
** לחי -
תירוץ הגמרא צריך ביאור, שהרי רק מזכיר שכיון שהיה לו רק לחי אחד, צריך להוסיף לחי אחר. צריך לומר שכיון שהיה דן בלחיים, הזכיר רק לחי. ותחשב.
** ארבעה -
גמרא נקט כאן לפרש שיעור למטה של מקום הצריך לחי כיון שדן בהו"א שלא צריך כלום. אז, אגב זה, דן איפה לא צריך כלום. ותו"ת.
** תלויה -
קשה, שלכאו' אין זה קולא של מים, אלא כל מחיצה תלויה מהני, אלא שיש בקיעת גדיים תחתיו. הרי, אין בקיעת דגים נחשב בקיעה, ולכן מקילים בו במחיצה תלוייה. (כן נראה מגמ' בפרק הזורק ובכ"מ.) אם כן, קשה איך נלמד ממנו לשאר קולות. ותחשב.
** שתי פסים -
יש לדון מה הענין, אם הוא שיהיו שתי פסים, ולא רק אחד, או שיהיו פסים סביב הדלת. (איני חושב שיהיה נפקא מינא בין הצדדים; אני רק שואל לדון בשאלה עצמה.)
** ארבעה -
וא"ת אולי צריך שניהם, ארבע ורוב. ויש לומר שהיה לו להזכיר כן. גם יש לומר שכיון שיש רוב הכותל, לא מסתבר שצריך להיות ארבע.
** שבע -
וא"ת למה ידון בזה. ויש לומר שלא רצה לומר שדן בשבעה, אלא שדן עד שבעה, והוא שהיה פשוט לו שארבע מהני, אבל בא לחדש שלפעמים לא צריך ארבע, והוא אם נותן בשני צדדים או אם נותן רוב. ותו"ת.
* יב:
** חצר -
נראה שחצר יותר חמורה כיון שהצד החסר הוא הצד היותר גדול (או, כשהם שווים, על כל פנים אינו הצד הקטן). ותחשב. (אף שיכול להיות שהצד פחות מצד מבוי, כיון שהוא צד גדול לו, יותר חשוב.)
** מחיצה -
נמצא שגדר מחיצה דאו' כולל לחי של מבוי, אף שבדר"כ מחיצה צריך להיות הרבה יותר מזה. (נראה, אז, שגם זה בהל"מ של החידושים של מחיצות.)
** קורה -
כיון שאינו רשות היחיד, נמצא שקורה מתרת כרמלית. ותחשב.
* יג.
** קשיא -
כיון שהם חולקים, יש לדון אם עדיין נניח ששמש ר"ע ושוב ר"י ושוב ר"ע. ותו"ת.
** לא אמרה -
מעניין שיאמר דבר כזה לחזק את התלמידים, כיון שאומר הלכה שאינה נכונה. אין לומר שיבינו שאינו נכון, שאז לא יחזק אותם. (ויש לדון, שאולי אף שיודעים שאינו נכון, יש מזה חיזוק.) נראה שלא חש לזה כיון שבין כך ובין כך אינו נוגע שהוא דיון מה סובר בית שמאי, ופשוט שאין הלכה כבית שמאי.[fn:2] וא"ת יבינו גם זה. ויש לומר שזה לא פשוט שיבינו, ואין בעיה כשלא יבינו, שלא קרה שיש הלכה תלוייה בפסק זה.
** יכול למחוק -
עדיין איני מבין למה צריך להיות שיכול למחוק אותו, שרק רואים שאם מוחק אותו למי סוטה, כשר, אבל לא שצריך להיות ראוי לכך.
* יג:
** מפני מה לא קבעו -
קשה, שמתחיל ואומר שכלפי ה' היה ברור שהיה החכם הגדול, אבל אז ממשיך לשאול למה לא קבעו רבנן של זמנו הלכה כמותו. ותחשב. היה אפשר לומר שמקשה איך הרשה ה' לחכמים לקבוע הלכה נגדו, כיון שהכיר שהיה הכי גדול, אבל אז צריך ביאור מהו התשובה. ותחשב.
** לא היא -
יש לדון אם רצה לומר שאין זה קו"ח נכון, והם דרשו קו"ח יותר טובים, או שרצה לומר שלמעשה אינו נכון, ומפרש למה אין הדין כאותו קו"ח שהיו דורשים.
** על סוף -
יש לדון אם נכונים ר"ל שהם סברו כן או ר"ל נכונים.
** אחוריו -
צריך ביאור מה קרה עם כל התלמידים שהיו לפניו. צריך לומר שצריך יותר מלימוד לפניו או לאחריו, אלא שבאותם דברים אחרים שצריכים - כמו לימוד ותפילה - רבי היה שווה לחבריו.
* יד.
** מלבין -
יש לדון אם אומר שצריך הוספת טינא לקורה או שזה נחשב שיכול להעמיד, כיון שעם הוספה, שיעשה אילו רוצה לבנות בו, יכול להעמיד. ותחשב.
** קורה אין כאן -
יש לדון למה לא, שרואים שיש דבר שמעמיד את הוילון. נראה שלא רואים שהוא בהכשר קורה, שאולי הוא קטן מאד. גם יש לומר שקורה משום היכר, וחלק מן ההיכר הוא שלא נראה כמחיצה, אלא הוא דבר קטן שניתן שם. ודע שיש לדון, אז, אם יש שיעור לקורה (למשל, לא יכול להיות ג"ט בגובה). ותחשב.
** עקמימותו -
לכאו', אינו פשוט בכלל, שלעיל אמר גמ' שאם מקצת הקורה למעלה מכ', כשר הוא (הוא מחלקת שם). זהו כשבכל רוחב הקורה, יש למטה מכ', אבל יש מן הגובה שהוא למעלה מכ'. אז, הו"א שכמו שכשר שם, כך כשר כאן, שהו"א שההכשר שם הוא מפני שהמקום הולך אחרי אפילו מקצת ממנו, וכיון שיש לו מקום של "למטה מכ'" (אף שמסתמא גם יש לו מקום של למעלה מכ'), כשר. ותחשב.
** מנלן -
וא"ת צא ובדוק שכך הוא. ויש לדון. אפשר ששואל מהי"ת מן התורה שיכולים לסמוך שהוא שלש, ולא לצמצם לומר שהוא פי"י. (גם יש לדון אם אולי סובר שהוא "חלק מן התורה" כיון שהוא במשנה. אז, סובר שצריך מקור שהוא "חלק מן התורה," והוא שימצא אותו בקרא. זה נקודה טובה, אבל איני מבין אותו כל כך, ולא פשוט לי מה נחשב חלק מן התורה. עיין בשבת, בדיון אם יש ללמוד הלכות סכנה (הלכות בית הכסא) יותר או פחות מתורה עצמו. ותחשב.
** משהו -
וא"ת למה לא אמר שבאמת אינו ממש שלש, אלא שרסנן קבעו לו שלש, ולא דקו. צריך לומר או שרבנן לא יעשו כן, או שלא מביא מקור למציאות, אלא לדין, או שכיון שמפורש בתורה שאינו ממש שלש, רבנן לא יעשו כן. ותחשב.
* יד:
** רבי יוסי -
לעיל, הוזכר שיטתו בחצר, וכאן הוזכר במבוי. מעניין שגמרא משמע שסובר שהם שווים. ותחשב.
* טו.
** לחי העומד מאיליו -
צריך ביאור למה לא דן גמרא בזה בקטנה שנפרצה לגדולה לעיל. יש לומר ששם מניח כאביי, כיון שידע שהלכה כמותו. (ויש לדון, שאולי משם ייצא חולק על אביי, ואז אולי לא נפסוק כמותו. ותחשב.)
* טז.
** פחות משלש -
אבאר שקלא וטריא של הגמרא.
הגמרא מקשה שכיון שבין שלש ובין פחות שלש נפסלים בשלש, כיון שפרוץ כעומד פסול, היה לו לומר שעד (וכולל) שלש דינו שווה, והוא שפסול בשלש, ולא שעד (ולא כולל) שלש פסול בשלש. דוחה גמרא שפסול שלש שונה מפסול כשהוא פחות משלש, שפסול פחות משלש הוא מה שגדי נכנס לשם. צריך ביאור, שבשני המקומות צריכים כן. נראה שהענין הוא שיש שני הגדרות על מה שצריכים כדי לפסול - שיהיה יותר מלבוד, ושיהיה כעומד. בפחות משלש, הפרט האחרון לבוא הוא מה שהוא יותר מלבוד. בשלש, אינו כן, אלא באים בבת אחת. ותחשב.
* טז:
** רשב"ג -
הענין הוא שכיון שרשב"ג אומר שיש לבוד עד ארבע טפחים, רואים שלא מחשיב ארבע טפחים (כמובן, יש לדון אם הוא סימן או סיבה). כיון שכן, רק לו מסתבר לחלק בין ארבע טפחים לפחות ממנו.
** מחיצה תלויה -
עיין לעיל, שדנינו בזה. רואים מכאן שענין מחיצה תלויה היא אף אם אין גדי מעביר תחתיו. צריך לעיין בסוגיה זו, שלא בהיר לי.
* יז:
** מיצר -
יש לדון במיצר במחנה, אם נקבר ברחוב. אם נקבר, יש עוד תשובה למה זה לא כלול בתקנת יהושע. (אולי ממה שלא מתרץ כן, יש ראיה שאינו נקבר ברחוב.)
** יש מלח -
יש לדון אם רצה לומר שיש מין מלח, והוא מלח סדומית, ויש לו מדה זו, או שרצה לומר שיש קורטים של מלח במלח סדומית שעושים כן.  ותחשב.
* יח:
** דמות -
לשון גמרא משמע שכל אלו דברים שמונים יש להם דמות של אדם ולא צלם של אדם.
** דיו לעולם -
נראה שזה קצת פו"ן, שאומר "דיו" לעולם לקיים בשני שמות, אחרי שדרש ש"דיו" רצה לומר שנים. (אף שכמובן אין המילים נאמרים שווה, עדיין יש להם אותם תיבות[fn:3], וגם שנשמעים דומים. ותו"ת.)
* כ.
** כאן הודעך -
גמרא שואל למה צריך שני המימרות. באמת, לא פשוט לי למה צריך מימרא זה בכלל. צריך לומר שבא לומר שהוא סובר כמותו. אבל, מוזר לומר כן, כיון שגמ' הגיה לו הו"א שגופא אומר שלא סובר כן. לא קל להבין למה יאמר לשון שאולי אומר שהוא סובר כן ואולי אומר שהוא לא סובר כן. ותחשב.
* כ:
** וכן בגת -
עיין בפי' רש"י על זה. יש להעיר שזה רק פירוש רבא שם בשבת. אבל, אביי נותן פי' אחר שם. יוצא מזה מחלקת לדין, וכיון שהלכה כרבא, בחר רש"י לפרש כרבא.
* כא.
** מים דחזי -
עיין בפרש"י בזה. צריך לחשוב על זה, שכיון שאין אדם שותה את המים, היא סברה מוזרת.
** מתיבתא -
צריך ביאור, שאין מי שיכול להקל בזה ולשתות את המים אלא בהמות, ומי מביא את הבהמות שלו למתיבתא. ותחשב. (באמת, היה אפשר להקשות כן בעולי רגלים, אבל אפשר לומר שמביאים מבהמותם לקרבנות.)
** בורגנים -
רצה לומר, ממשיכים את העיר ככל משך הבורגנים, אם הם מתחילים בתוך שבעים אמה לעיר.
** חנוותא -
אלו חזקים יותר מבורגנים, ואז הם מתירים בבבל. גם יש לומר שאף אם אינם חזקים, הם חשובים יותר, ואז עדיין מתירים. ותחשב.
* כב.
** קרפף -
מעניין שגמרא רק מצדד לאסור מחמת גזירת קרפף יותר מבית סאתיים, ולא מפני שהיא מחיצה חלושה, ואז לא מתרת ביותר מבית סאתים.
* כב:
** תל -
צריך ביאור למה לא חלק ששם המחיצות הם יותר טובות (שהם סובבות את כולו).
* כה.
** מודה לי -
יש לדון למה מודה לו שם. כנראה הענין הוא שיש איזה הוספה בדירה בין מחיצות, ולא על גב המחיצות ש"רואים" בתל. ותחשב.
* כה.
** אורזילא -
יש לדון אם תמיד מיקל ואומר שפי תקרה יורד וסותם אף אם אין פה או שאומר שכיון שיש קצת פי תקרה, או כיון שהוא תחת תקרה, נחשב מקום בפני עצמו, ולא מצטרף לבית סאתיים.
* כו.
** הושיב -
לא לומדים את זה ממה שבא לו, שיותר היה קל לומר שבא לו כדי לבקר חולה. אלא, ידע גמרא שבא והושיב בית מדרש אצל מיטתו.
* כו:
** בית הקברות -
וא"ת הרי מותר לישראל בתרומה, וגם כאן יהיה מותר לכהן, כיון שאפשר לישראל. ויש לומר שרק אומרים כן בפסול מזון. אבל, כאן הוא פסול מקום, והבעיה הוא שמקום שאי אפשר לכהן ללכת לשם אי אפשר להיות נחשב מקום מושבו. אבל, בפסול מזון, אין זה בעיה, אלא יש בעיה רק במה שמושך אותו לשם. כן יוצא מרש"י. ותו"ת.
* כז:
** מאן דמתרגם לי -
יש להקשות על זה שני קושיות פשוטות:
קושיה ראשונה היא למה זה כל כך קשה לו, שיכולים לומר, כמו שמצאנו בכמה מקומות, שמילתא דאתיא בקל וחומר טרח וכתב ליה קרא.
קושיה שנית היא למה הקשה על בן בג בג, שלכאו' היה לו לומר שכל מי שיכול לפרש לו את הפסוק יזכה בזה, שהרי הפסוק נראה מיותר. זה קל לדחות, שיש לומר שיש דרך אחר לפרש את הפסוק, ויש דרשה אחרת לדרוש ממנו. צריך לעיין.
נראה שיכולים לתרץ זה בעקב זה, לומר שלולי בן בג בג הייתי אומר שמילה זו באה לדרשת בן בג בג, ואין צורך, שמילתא דאתיא בקל וחומר טרח וכתב ליה קרא. אבל, רבי יוחנן סבר שמילים של בן בג בג לא משמע שסבר כן (אולי ממה שהביא את הדרשה או אולי ממה שלא אמר עליו שמילתא דאתירא בדרשה טרח וכתב ליה קרא). אז, הקשה על בן בג בג, ולא רצה לטרח שמילתא דאתיא בדרשה טרח וכתב ליה קרא, ולכן הקשה רק על בן בג בג, שאחרים יכולים לתרץ שמילתא דאתיא מדרשה טרח וכתביה קרא.
* כח.
** מרובי בנים -
לכאו', אי אפשר לומר שמסרס, שאם מסרס יהיה אסור לכל, כמו שמבואר בגמרא שבת (קיא.). אלא, צריך לומר שרק ממעט בנים. אם כן, מעניין שגמרא אומר שלא ראוי לחשוכי בנים, שהרי בוודאי אין איסור בדבר, אלא שמי שרוצה בנים לא ירצה לאכול אותם. צריך לחדש אחד משני דברים:
אולי אף שאין בהם איסור, כיון שבני אדם כמותו לא רוצה בו, לא יכולים לערב בו.
אולי אף שאין בו איסור מסרס, יש בו ביטול מצוות פו"ר. אז, אסור לו לאכול אותם.
* כח:
** ואקבל בהו אגרא -
מעניין שאומר שיעשה אותו כדי לקבל שכר, שלכאו' הוא כ"עובד את הרב על מנת לקבל פרס." (כמו כן, עיין בגמ' בברכות (כו.) שכשדן בחילוק שני מיני תפילה, לא דן בחילוק כמה טוב הוא, אלא בחילוק כמה שכר מגיע לו.) ותחשב. אפשר לפרש שהמשנה לא אומרת שלא תעבד כדי לקבל פרס, שהיה לו לומר כן, אלא שלא תהיה כעבד שעובד כדי לקבל פרס, והוא שעבד כזה לא עובד כל כך טוב (יש לדון אם זה נכון). אז, אומר שצריך להבין כמה טוב אנחנו צריכים לעבוד ולעבוד ככה. אבל, עדיין מוזר שיאמר שהוא עושה את זה שלא לשמו. ותחשב.
* כט:
** ופוסל את המקווה -
עיין ברש"י, שמשמע שרק פוסל אותו מדין מים שאובים. אם כן, רק פוסל אותו כשהוא שאובים, והחידוש הוא שעדיין נחשב מים. (זה מבאר מה שמחלק גמ' שזה לא נקרא מים צבועים. קשה, שזה יותר צד לפסול, כיון שאינו בכלל מים. נראה שאין פסול של דבר אחר בשלש לוגים, שפסול זה רק במים שאובים. החידוש הוא שזה בכלל מים שאובים. אז, מה שלא נקרא "מים" עושה שלא פשוט לפסול מחמת זה. ותחשב.)
** מיקרי -
כמובן, כמו בכמה מקומות, יש לדון אם זה סימן או סיבה.
* ל.
** באומר כל הזן עלי -
קשה, שהמשנה לא אמר כן. אולי משנים את לשון המשנה. אילו היינו גורסים "כאילו...," אז היה אפשר לפרש שבא לומר ששאני נודר, ששם מזון רצה לומר "כל הזן." אבל, אז נראה שעיקר התירוץ חסר מן הספר. ותחשב על זה.
** אימא מזונא -
קשה, שזה פשוט, שרק חמשת המינים מזונא. אפשר לומר שזה אחרי שניתותבו רב ושמואל. עדיין, פשוט, שאינו מחמשת המינים, וגם אינו אורז. אולי צריכים לחלק בין "מזונא" ל"מזון." דחוק.
** שבועה שלא אוכל -
הייתי אומר שההגדרה היא שרק לא יכול לערב בו אם הוא בעיה בחפץ. אבל, אז צריך לומר ששאר איסורים הם איסורי חפצא, ולא איסורי גברא, והר"ן בנדרים כ' שרק נדרים איסורי חפצא. ותחשב. נראה שאפשר שזה הולך כתנא שאומר שכיון שמותר לחברו, גם לו יכול לערב. (אגב, יש לדון אם זה מפני שראוי לחבירו או מפני שחבירו יכול לערב בו.) אבל, אם הוא איסור חפץ לו, אז לא יכול לערב בו, שהחפץ לא יכול להיות מזונות לו, מחמת דין החפץ עצמו, ולא מחמת דין שלו. אז, לא יכול לערב בו, אף אם אחרים יכולים לערב בו ולאכול אותו. (אולי זה מפני שהוא פסול גדול או אולי הוא מפני שאצלו החפץ שונה (רצה לומר, יש קרק' שהוא מאד יותר חשוב אצלו, עד ששם לו חלוק מלאחרים) מלבני אדם אחרים, ואז לא נכון שיכולים לערב בו ולאכול אותו, שאצלם הוא דבר אחר.
* ל:
** שמערבים לגדול -
וא"ת למי מותר אז. ויש לומר לקטן. וא"ת תמיד מותר לקטן. ויש לומר שבדר"כ יש איסור חינוך עליו או שאסור להאכיל בידים. גם יש לומר שכאן מותר למסוכן. וא"ת צמיד מותר למסוכן. ויש לומר שכאן יותר מצוי שיהיה מסוכן על זה. גם יש לדון אם נאמר שנחשב מותר לו (שתלוי אם צריך להיות הותר, ואם הותר. ותחשב.)
** כדי מזונו -
נמצא שאף שאומרים שנותנים מדה שווה לכל אדם, זה אינו ממש לכל אדם. הענין יהיה שלמי שלא שונה בקרק' כל כך גדול, נותנים מדה שווה. אבל, מי שכל כך שונה, אינו באותו כלל של שאר בני אדם, וממילא אין לו מדה שווה להם. ותחשב.
* לא.
** אסור לקנות בית -
מהמשך הגמרא נראה שהבעיה אינה שקונה דירה שם אלא ששומר את מזונו, ושיש לו הנאה מזה. אבל, לא נראה שיש בעיה לקנות דירה שם, שלא נהנה מן בית הקברות אז. ותחשב. ושי לדון, שאולי הענין יכול להיות שאם ידור שם, ממילא יהנה מדברים של המת. אז, אין דירה שם. אבל, מהמשך הגמרא לא נראה כן.
** בפשוטי -
רש"י כ' שהוא אב הטומאה. נמצא שרש"י סובר שלא אומרים שחרב הרי הוא כחלל בכלי שנטמא מן המת באהל, שאם לא כן, יהיה אבי אבות הטומאה.
** לדבר הרשות -
עדיין, לכאו' יהיה מותר רק אם מערב לדבר רשות. יש להעיר שגם למי שאומר שמערבים רק לדבר מצווה, לכאו' אם מערב לדבר מצווה ולדבר רשות (שיהיה מותר), לא יכול לתת אותו בבית הקברות, שנמצא שנהנה. ותחשב.
** כיון דקנה -
קשה, שרוצה שיהיה נשמר עד שקנה.
** אכיל -
קשה למה זה עושה שלא יחול. לכאו', זה עושה שיהיה אסור, אבל בין אם חל בין אם לא חל, ירצה שישמור אותו. נראה שאם לא חל עירוב שלו, לא מסתבר שיבוא כאן לאכול את המזון. דחוק, שצריך לומר שמותר לו לבוא לכאן, שאל"כ, אין עירוב שלו מהני. ותחשב.
** מיגו דאי בעי -
צריך לחשוב מהו סברה זו. בוודאי אינו מפני שיש דרך לתקן, כיון שגם יכול לתקן מעשר שני שלא נפדה. (ודע שצריך ביאור למה לא יכול לערב במעשר שני, שהרי פדיון שלו הוא רק אסור מדרבנן. אולי צריך לומר שהולך כשיטת רבנן, ולא כשיטת רבי, שסוברים שלא הותרו שבות בבין השמשות.)
* לא:
** כהלכתן -
אולי זה מלמד שיש הלכות בפדיונם, ושלא יכול לפדות במה שרוצה, או אולי זה מלמד שאותם הלכות מעכבות. ותחשב.
* לב.
** כולי יומא -
וא"ת מה אם שלח אדם לעשות עירוב בחצי היום. אפשר שאיה"נ לא יכול לסמוך עליו, אבל לא נראה כן. יותר נראה לדחות. אפשר שרצה לומר שיגמור אותו קודם סוף היום, מאימתי שמתחיל (והענין הוא שסוף היום נראה כ"גמר" לו, ואז יגמור קודם זה) או שרצה לומר שיגמור קודם סוף הזמן. (לצד אחרון, יש לדון אם נניח שיעשה כן באותו היום אם יש לו עוד ימים לעשות אותו.)
** בין השמשות-
יש להעיר שמעניין שדנים מה יכול בבין השמשות, שבביה"ש הוא אינו שם, ואז לא יכול לאכול אותו. ותחשב.
* לב:
** אלא דנתכוון -
רש"י הוכיח מכאן שצריך להיות כרבי. יש לדון למה לא הוכיח גמרא מכאן.
** והא קא משתמש -
לכאו', בין כך ובין כך זה קשה.
** משתמש -
נמצא שכיון שנוטל אדם דבר מן האילן, נחשב משתמש בו. גם יש לומר שכיון שהוא מקום של העירוב שלו, זה עצמו נחשב תשמיש בו. דחוק.
* לג.
** עליו -
לכאו', מניח גמרא שיש דבר שהוא למעלה מעשרה טפחים גם בתוך ארבע אמות שלו. היה אפשר לו לתרץ שאין כזה דבר. ותחשב.
* לג:
** הכא לא הדרן -
עיין ברש"י שפי' שרצה לומר שלא אומרים שני דברים - שחוקקים להשלים ושגוד אחית. לולי רש"י, היה אפשר לומר שאף המחיצות שעושים הם מחיצות שונות (תחשב האיך), שלא נאמר עליהם שיורדים.
* לד:
** פשיטא -
יותר מזה, יש להקשות שכיון שהוא ברה"י, היותר נמוך יותר פשוט שהוא רשות היחיד, ויותר פשוט שיהני. אז, לשון "אפילו" קשה. עיין בלשון רש"י, שאולי מכוון לפרש כן. אבל, אין הכרח.
** גזירה -
וא"ת זה עצמו דרבנן, ולא יהיה גזירה בבין השמשות. ויש לומר שזה גזירה שלא לערב בו, ולא שזה גזירה של שבת. אז, ממילא הוא חל, שחל אף אם אינו שבת. גם יש לומר שאינו גזירה על עירוב, אלא על השתמשות, וזה גזירה היותר חמורה מסתם שבות, שיש בו חשש ממש של עבירת מלאכה. לשון רש"י משמע כשני.
** עוזרדים -
רש"י פי 'שהם קשים. אז, זה סותר מש"א לעיל שיש גזי' שמא יקטם כיון שהוא רך. ותחשב.
** ואם בשדה -
רש"י שמפרש שיש שלש שיטות בזה רצה לומר שכן חושב גמרא בקושייתו. אבל, למס' יפרש גמרא נגד זה. ותו"ת.
* לה.
** רעדה מחמת כחו -
אולי הענין הוא שכיון שהולך כל כך מעט, לא נחשב שמסיט אותו.
** אלא לצורך -
מעניין שלא דוחים שתשמישתו הוא לחתוך, אלא אומרים שתשמיש שלו הוא לחתוך מאכלים, בדווקא.
** חמר גמל -
וא"ת למה חמירים כיון שהוא מדרבנן. וי"ל שסוברים שמדאו' הוא ע"ת. גם יש לומר שאם היינו מקילים מספק, היינו מקיל על שניהם, וזה סותר א"ע. אלא, מחמירים על שניהם, שטוב יותר לסתור להחמיר מלסתור להקל. החולק סובר שכיון שיודע מה שרוצה - רוצה עירוב - בוחרים את זה להקל בו.
** ארבע אמות -
זה מחודש, שעדיין אסור לו ללכת לשם ולהביאו. אבל, עדיין מהני, כיון שיכול ללכת ולהיות העירוב במקום שלו. ותחשב.
* לה:
** דאורייתא -
עיין לעיל, שדנינו בקושיית הגמרא. יש לדון למה לא רצתה גמרא לתרץ כמו שכתבנו. (ודע שמצאנו דינים ככלל שכתבנו, כמו אם נפל דבר איסור אולי לזה ואולי לזה, שאף בדרבנן, אם אין רוב באחד מהם, מחמירים בשניהם.)
** כתים -
נראה שהענין הוא שעושה שאין עוד חזקה, כיון שיש עדים שאומרים שנשתנה. ותחשב. (במילים אחרים, אין העדים דוחים את החזקה, שאין להם כוח, כיון שיש עדים נגדם. אלא, הם מתירים את החזקה, ואין אומרים שיש חזקה שלא הולכים אחריו, אלא אין עוד חזקה. ותחשב.)
* לו.
** סוף היום -
יש לדון בזה, שאולי ביה"ש חל, בין אם הוא סוף היום בין אם הוא תחילת היום, והאיסור מושך כל בין השמשות, כמו שאמר גמרא לעיל. ותחשב.
** סעודה הראויה -
אם כן, לכאו' לא יוכל לערב ביה"כ לשבת, שאין שום סעודה שהיא ראויה לבעוד יום. (ויש להעיר שגמ' דן בעירוב ביה"כ. זה לא קשה אם חל בסוף היום. ותו"ת.)
* לז.
** התנו -
כמובן, קשה להבין תירוץ זה ש"תנאי" שמזכיר רש"י נראה שהוא שווה ממש לברירה, שמתנה שאיזה שיברור כהן יהיה שלה. אולי יש חילוק כשיש ברירה בין שני בני אדם, שאז יש ברירה (והביאור יהיה שאין ברירה כיון שאדם מניח שיהיה זה או זה, ואז כבר מפרש את דעתו; כיון שהוא דן עם אחר, לא מניח דברים). דחוק.
* לז:
** רמונים -
מעניין שגמרא אומר שלא ניכרים שיריים; הייתי אומר שניכרים שיריים, אלא שלא ידוע אם חל. אבל, מכיר איזה הם אפשרים להיות שיריים לנגד אלו שאפשרים להיות תרומה. כנראה, כיון שלא יכול לומר - "אלו שיריים," לא נקרא שניכרים שיריים, אף שאין השאלה "איזה," אלא "האם יש שיריים."
* לט.
** ר"ח הזה -
לכאו', כן אמר ראש השנה הזה, אלא משנה מזכיר ראש חדש להוסיף חידוש, שהיה גם מזכיר ר"ח בר"ה.
** אותו פת -
אין זה כל כך ברור לי. כנראה, אם מערב באותו פת, אף שהוא במקום אחר, יותר מסתבר לגמרא שלא יצטרך לומר שהפת הוא לעירוב, ורק אז לא נחשב הכנה. ותחשב.
** חול' על ר" -
יכול להיות שני דרכים לבאר החולקים על ר"י:
1. יכול להיות שלא חוששים שנעשה שני ימים טובים ככה. במילים אחרים, כשחדשו רבנן לחוש לשני ימים טובים, חשו מפני שאולי זה י"ט ואולי זה י"ט, ולא נדע. אבל, לא תקנו מפני החשש שאולי שניהם י"ט, שזה לא מצוי.
2. יכול להיות שסוברים שאף בכעין ציור של רבי יוסי נחשב שני ימים טובים. המשך הגמרא מוכרח כצד זה.
** ושרו -
ק"ק, אז, מהו ה"וכן" של רבי יוסי, שלא אמר דין כזה לעיל.
** ושרו -
עיין ברש"י, שכ' (וזה מעניין) שדוחקים בלשון דברי רבי יוסי, שכיון שידוע שנימוקו עמו, לא רוצים שהוא יאמר דבר שלא מסתבר. ותחשב.
* מ:
** אקרא -
קשה, שגם חובה לומר על קרא, כשאוכל אותו. אפשר לדחות שרצה לומר שכיון שאנו אומר אותו על קרא, אני מביא קרא, ואז אין לי ספק (כמו שנוהגים היום ביום שני של ר"ה). אבל, לשון הגמ', וכן לשון רש"י, לא משמע כן. אז, צריך ביאור.
** יה"כ... -
גמרא פוסק שיוה"כ צריך שהחיינו וגם פסק שמברכים אף על כוס. יש להעיר שהשני מוכרח, כמו שהוכיח לעיל. אז, לא צריך גמ' לומר אותו. (אין זה כל כך קשה; יש לומר שאמר אותו כדי שיהיה יותר בהיר.) נראה שהיה אפשר לדחות (וק"ק למה לא דחה כן לעיל) שרק ביה"כ, שאי אפשר לומר על הכוס, התירו לומר שלא על הכוס.
** ראש חדש -
אם הוא מפני שכולל אותו בשאר התפילות, אם כן גם חול המועד יהיה כן. (אין זה קשה; אין לי הוכחה שאין דינו שווה דין ר"ח, אלא זה רק הערה שנמצא שדינם שווים.)
* מא:
** מעבירים -
יש לדון מה זה אומר. אולי רצה לומר שמפני זה עושה דברים שהוא לא רוצה ושה' לא רוצה.
* מב.
** כמאן -
וא"ת למה צריך להיות כאחד מהם, ולמה אי אפשר שיהיה לו שיטת עצמו. עיין ברש"י, שמסביר שיש תלייה, ואי אפשר לסבור קצת כזה וקצת כזה. ותחשב.
** מהלך בה -
עיין ברש"י. גם היה אפשר לומר שהוא שהמחיצות היו שם בתחילת שבת, אבל מהמשך גמרא נראה נגד זה.
* מב:
** מאי בינייהו -
גם, כמובן, יש בינייהו אם עמד (או, באמת, אם לא הולך כל כך מהר, שלשיטה אחרונה שברש"י, צריך להיות הולך מהר מאד). צריך ביאור למה לא אמר כן גמרא.
* מג.
** אליהו -
נמצא שאליהו המלאך מקיים (ויש לדון אם מצווה עדיין) מצוות, וששדים לא מקיימים (ויש לדון אם מצווים) מצוות. ותו"ת. (אבל, לאידך גיסא, יודעים שיש דברים ששדים מקפידים עליהם, כמו שאומר גמרא במגילה וכ"מ, שלא אומרים שם ה' על שקר.)
* מד.
** שני אמות -
יש לדון אם רצה לומר ששני האמות לא הגיעו לו, והיה צריך ללכת שני אמות להם או שהשני אמות לא הגיעו אל העיר, והיה צריך ללכת אל העיר. נראה שחידוש לומר האחרון, שאין זה בתוך ארבע אמות שלו., ולכאו' אדם רק קונה ארבע אמות אחד (שאם לא כן, יהיה מותר לאדם לחזור לתוך התחום בפחות פחות מארבע אמות. ויש לדון, שיש לומר שרק כשיש לגזור שילך ברגיל ויעבור אוסרים את זה), אבל מרש"י משמע כאותו צד. ותחשב.
* מד:
** הבלעה -
לפי צד ראשון של רש"י, שרק יהיה לו תחום אחד, קשה איך נאמר הבלעה, שנמצא גלגל החוזר, שניתן לו תחום של מקום שבא לו, ואז ניתן לו תחום שלו, כיון שיש הבלעה, ואז, כיון שיש לו רק תחום אחד, רק ניתן לו תחום שלו, ולא תחום של מקום שהוא שם, ואז לא יכול ללכת לתוך תחום שלו, וגם שאין הבלעה. נראה שעד שבא לתוך תחום שלו, ניתן לו תחום של מקום שהלך לשם. כיון שבא לתוך שלו, נמצא שהוא עוד יכול לזכות באותו תחום, ולא נאמר שיש הפסק, ממה שיצא משם, שתמיד היה מותר ללכת לתוך תחום שלו (אף שלא היה בתוך תחום שלו), ואז חוזרים לו תחומו הראשון. ותחשב.
** מערה -
גמרא זה היה קשה לי בכל זמן שלמדתי אותו, אבל בפעם הזה הבנתי אותו בטוב. הענין הוא כך: כיון שהוא שרוי בתוך המערה, יש לו רשני מקומות שביתה, אחד בכל פתח. אז, יש לו אלפים אמה מפתח שבמזרח ואלפים אמה מפתח מערבית. אבל, יהיה תלוי באיזה פתח יוצא, שרק כשיוצא מפתח מזרח יש לו את האלפים מפתח מזרח, ורק כשיוצא מפתח מערב יש לו  האלפים מפתח מערב. אבל, אם נאמר הבלעה, כיון שבתוך האלפים שניתן לו כשיוצא מפתח מערב יש ג"כ תחום אחר לו, מצרפים אותם, ושניהם שייכים לו, באיזה פתח שיצא ממנו. ותחשב.
איני מבין למה צריך להיות שהוא רחב ארבעת אלפים בתוך המערה, אבל צריך להיות שהוא רחב פחות מארבע אלפים בתוך המערה, כיון שבלא"ה אין תחום של פתח זה מובלע בתחום של פתח זה.
* מה.
** נהרדעא -
יש לדון אם רצה לומר שכשאמר בבל רצה לומר נהרדעא (שאומר שלפעמים נהרדעא נקרא "בבל"), והוא הסמוך לספר, או שמחדש שבבל יש דין של סמוך לספר (אולי מחדש שאותו דין נוגע שם או אולי מחדש המציאות), ומפרש גמרא איזה עיר בבבל הוא הקרוב לספר.
* מה:
** כלי הפקר -
צריך ביאור למה כלי הפקר, כיון שלא קונה שביתה, מותר בכל מקום, ואדם, כיון שלא קונה שביתה, אסור חוץ מאלפיים אמה. נרה שאולי גם כלי היה אסור, אלא שכיון שאין לו שביתה, בטל שביתתו לשביתת אדם. ותחשב. ודע שצריך ביאור למה לא יצא מאותו מקום, שאם הוא מקומו, יהיה לו אלפיים אמה, ואם אינו מקומו, לא יהיה שום איסור. נראה שמתרגמים ש"לא ילך ממקומו" לומר ששישאר במקומו. דחוק. גם דחוק כיון ש,כמו שהוכחנו, אין זה מקומו, ובכל מקום יהיה אסור. נראה שצריך לומר שאם הוא מכוון לשבות שם, מקום שחוצה לו נקרא מקומו, ואם לא מכוון, אין האלפים אמות נקרא מקומו, אלא רק איפה שהוא. כיון שכן, שניהם שובתים, ולשניהם יש מקום שביתה. אם כן, קשה למה של כלי בטל, ודווקא כשלא כיוון לקנות שביתה. נראה שצריך לומר שאינו כל כך מקום שלו. יש לדון אם זה שייך למה שאין אלפיים אמה, אם הענין הוא שכיון שאינו כל כך מקומו לא בא לו אלפיים אמה (ואז אולי אצ"ל כמו שכתבנו) או ששניהם נכונים, אבל לא תלויים זה בזה. ותחשב.
* מו.
** בשעת הדחק -
רש"י פי' שהוא שעת הדחק כיון שהיתה שנת בצורת, וכבר טמאה טהרות. משמע שמה שכבר טמאה טהרות לא יהיה, בפני עצמו, שעת הדחק. גם משמע שמה שהוא בושה לו לחזור ולומר שטעה לא נחשב שעת הדחק. ותחשב.
** עירובין דרבנן -
קשה, שאולי כשאמר שהלכה כמיקל בעירובין, דומה להלכה כמיקל באבל, ואיך מניח שהוא רק מפני שעירובין דרבנן. אולי מניח רבנן שאין סיבה שנפסוק כמיקל, חוץ ממה שהוא מדרבנן. אבל, צריך לעיין למה פוסקים כמיקל באבל. (אולי הוא מפני שדיני אבל קשים לאדם, והם טורח גדול. ויש לדון.)
* מז.
** מיתיבי -
נראה שהטעם שמביא את כל הציורים הוא מפני שדחוק לומר שכולם יוצאים מן הכלל, שאין טעם שיש לו הרבה יוצאים מן הכלל. (גם יש לדון אם הכלל הוא שהלכה תמיד כרבי יוסי, למשל, מפני שרבי יוסי חכם, או שנמצא שזה קורה. אם נאמר כראשון, יותר קשה שיהיו כל כך הרבה יוצאים מן הכלל. אבל, דע שאף אם בא לומר כלל, ממילא ייצא מזה סיבה, שמסתמא הלכה תמיד כרבי יוסי כיון שהוא חכם.)
** בגזירותיו -
קשה למה לא אומר שבא לומר שהסתם הוא כיחידאה או לומר שאין הלכה כסתם יחידאה.
* מז:
** שלא מן הכל -
עיין ברש"י שמפרש שרצה לומר שיש רב שהוא יותר טוב לכולם. לולי רש"י, היה נראה שהלשון משמע שיש רב שמתאים יותר לזה ורב אחר שמתאים יותר לזו.
** בבריי' -
עיין ברש"י. עיין לעיל, שדנינו אם בא לומר סיבה או רק כלל. לשני, יש לומר שאולי רק אמר הכלל במשניות, ולא בבריי'.
* מח.
** ננס -
יש להעיר שאם נאמר שעוג היה בן י' אמרה באמותיו, היה משונים אמותיו. אז, יש לדון איך נשער לו. יש לדון אם רצה לומר שנשער אותו באמה הראוי לגוף שלו או אם נשער אותו באמה רגיללה. גם יש לדון אם זה רק אם גופו קטן כפי אמותיו, אמותיו קטנים כפי גופו, או שניהם. ותחשב.
** אי הוה -
איני יודע מה זה רצה לומר. אולי רצה לומר שאי אפשר ללמוד בקיאות אם  תעיין כל כך. אבל, מרש"י לא משמע כן. צריך ביאור מה אומר לפי רש"י. ותו"ת.
** גליא -
צריך ביאור איך מגלה את דעתו, שאולי מה שלא מערב עמו האו מפני שעשה את חברו שליח. ותחשב.
** שמואל -
עיין בהוכחת רש"י. מניח רש"י שכשאומריםש הוא "לשיטתו" רצה לומר שהוא מתאים רק לשיטתו, ולא לשיטת החולק עליו. אין זה מוכרח, שהיה אפשר לפרש שהוא מתאים לשיטתו, ולא למה שהיה אפשר לומר בהו"א. ותחשב.
* נ:
** לא אמר כלום -
עיין במה שבאר גמרא לפי שמואל. איני יודע למה אין זה חמר גמל לפי שמואל, שאולי אמר בתוך אלפיים ואולי אמר חוץ ממנו. צריך לומר שאמר על דבר אחד, והוא על כולו, וזה עושה חלות על כולו, וממילא עירובו באיזה ארבע שלא נודע. אבל, כדי לחול על כל הארבע, צריך להיות שכולם ראויים לעירוב. כאן, אין כולם ראויים לעירוב, שיש מהם חוץ מאלפיים.
* נג.
** רב ושמואל -
רשי באר שמביא כל מקומות אלו שחולקים במשמעות מילים. יש להוסיף על זה (ונראה שגם כוונת רש"י כן) שמביא כל מקומות אלו שבהם חולקים רב ושמואל במשמעות מילים.
** וימת -
קצת קשה למה לא דוחה שהטעם שלא אומר "וימת" הוא שלא מת, אלא מלך אחר מלך בלי מיתתו. נראה שזה לא קירה, שאם הוא היה חי, היה מולך (ואם אחר נטל ממנו את המלכות, בוודאי היה ממית אותו).
** גלי -
עיין ברש"י שבאר איך מצאנו שהיה דוד מלמד תורה. יש להעיר ששם היה, לכאו', פוסק על שאלות בני ישראל. מעניין שזה בכלל מלמד הלכה, שמטרתו שם לא היה ללמד תורה, אלא לפסוק, דהיינו שלא היה כדי שידעו בני אדם את התורה אלא כדי שיעשו בני אדם כתורה (וגם שלא יקפיד אם מיד, אחרי שעת המעשה, ישכחו). ותו"ת.
* נג:
** גנבים -
קצת קשה, שאינם גנבים כמותו, שהוא תלה על מה שכבר היה דרך שם, אבל צריך לומר שהם לא תלו (שהם היו הראשונים, שעשו את הדרך). צריך לומר שלא כוונה לכך, אלא רצה לומר - אולי היו גנבים, כמו שאתה גנב, ומה שאתה גנב אינו הסיבה לחשוב שהם גנבים (רצה לומר, לא מסלק המניעה שאין להניח על רבים שהם גנבים, אלא אין כזה הנחה).
יש להעיר שיוצא מגמ' זה שלא מניחים על רבים[fn:4] שאינם גנבים, אלא שעדיין צריכים לחוש שהם עושים רע.
** שלא תרבה -
ואם תאמר עכשיו היא מרבה עמה דברים. ויש לומר שכאטן היו דברים של צורך. (יש לדון אם זה דחויה או הותרה.) גם יש לומר שגופא היתה מדברת עמה על הצורך להרחיק עם נשים, ובדברים כזה אין לחוש לקורבה עם נשים. גם יש לומר שמותר לה להאריך לדבר עמו, ורק לא מותר לו להאריך לדבר עמה.
* נד.
** רמ"ח אברים -
נראה שזהו הטעם שבני אדם נוהגים לעשות שוקו"ל כשהם לומדים, שאז לומדים ברמ"ח אברים.[fn:5]
* נד:
** ימין -
יש לדון מהו חשיבות ימין, שנראה שיש שני דרכים לבאר אותו:
אפשר שהוא מפני שהיה לימין של משה (שהיה החשוב).
אפשר שיש כאן שורה של בני אדם, והוא בימין השורה.
תחשב בזה, שנראה שהם שונים.
* נה.
** ארוכה -
צריך ביאור מתי נחשב ארוכה, שלא מרבעים, ומתי נחשב בית יוצא. ותחשב.
* נה:
** בהמה -
לכאו', הבים ממזרים, ולא בהמות.
* נו.
** ירק -
כמובן, עיין בשבת (קמ.).
** חצי ימיו -
יש לדון אם רצה לומר שבחצי ימיו נעשה כבר זקן או שבחצי ימים שבנ"א נעשה זקן, הוא כבר נעשה זקן. (לדוגמא, אם בני אדם חיים שבעים שנה, ונעשים זקנים כשהם בן ששים שנה, לצד ראשון, הוא ייעשה זקן בן שלשים וחמש שנה, ולצד שני הוא ייעשה זקן כשהוא בן שלושים שנה.)
* נז:
** קשת -
גמרא מפרש למה לא אומרים בו מליוה. לא הבנתי למה לא ממלאים אותו בחלק העיר (גובה של הקשת). נראה שצריך לומר שרק יכולים למלאות ולראות את העיר השלישי במקום אחר אם לעשות כן מביאים את העיר השלימה. אבל, לא מחצים את העיר כדי לעשות כן. (ואם תאמר אם העיר השלישי גדולה מן ההפרש שבין שני העיירות, לא נביא אותו לשם. אולי אין הכי נמי. גם יש לומר שיכולים להביא אותו, ויהיה על גבי שני העיירות, ועדיין יותר. אבל, בקשת, בהבאת העיר, יסולק שני העיירים עצמם, שכולו עיר אחד. ותו"ת.)
* נח.
** לשון אחר -
שני הלשונות ברש"י חולקים (ונראה שרק חולקים בביאור, אבל יש לדון) אם הענין הוא כשמודדים לצפון, ויש הר שיוצא עד יותר מאלפיים אמה לצפון, אם אוסר ללכת יותר מאלפיים לצפון כדי למדוד או שאוסר ללכת לצד ההר, ליותר מאלפיים אמה למזרח, כדי למדוד. ותו"ת.
** כותל -
יש לדון אם החידוש הוא שאין מודדים כלל מגובהו (משא"כ אם יכול ללכת שם, שישים חלב כנגד לבו, שיתגדל קצת מרחבו מחמת גבהו) או שלא מודדים רוחב גובה הכותל. ותו"ת.
** מבליע-
מצאנו הרבה דברים בגמ' זה - יש מבליע, ויש מודד, ויש מקדר, ויש אומר. נראה שיש, בין הכל, כמה דברים, וצריך לדון מהו מה בכל הלשונות. לפעמים מודדים גם את הירידה, לפעמים מודדים את הירידה, אבל בקידור, שממעט אותו, לפעמים מודדים רק את הרוחב, ולפעמים לא מודדים את הרוחב של דבר שעולה ויורד.
* נט.
** אלכסון -
צריך ביאור איך יכולים להקל לומר שאולי אחד שכח למדוד כאלכסון, שיצטרך לבדוק אם הוא באלכסון או לא. נראה שלפעמים קשה לבדוק, ואז הוא ספק. ותחשב.
* ס.
** זמורתך -
אז, מצאנו לשון זה שלא מאביי לרבה על שפסק כתנא שאין עליו חולק.
* ס:
** כארבע אמות -
לכאו', אז, עדיין ממעט את תחומו ארבע אמות (ואינו כמי שאינו שם כלל). אז, מי שהניח את עירובו אמה חוץ מן העיר הפסיד חמש אמות. ותו"ת.
* סא:
** מהרו -
קשה למה צריך להיות מבעו"י, שמותר גם קודם שחזר הצדוקי וביטל את ביטול רשות שלו.
* סב.
** לא שמה דירה -
יש לדון למה לא יהיה שמה דירה, שלכאו' ענין דירה הוא שכיון ששיך להמון בני אדם, נראה כרשות הרבים.
** אוסרים זע"ז -
צריך ביאור מה מוסיף כשאומר שצ"ל "אוסרים זה על זה," שלכאו' יהיה אסור גם אם עירבו, שכל ענין שנים הוא שיהיה מצוי שיגורו עם גוי.
* סב:
** דיר -
קשה למה לא אומר שנחשב כדיר כשאין שם יהודי (שלא גזרו). וא"ת אז מה נפקא מינא, שאין שם יהודי. ויש לומר שיש נ"מ אם לא גר שם, אבל רוצה לטלטל שם.
** לא שמה דירה -
משמע שאילו היתה שמה דירה, היה גוזר בגוי. ותחשב. ודע שיש לדון אם מה שלא גזר בו הוא שלא גוזרים גזירה על גזירה או שלא שייך טעם האיסור כיון שאינו שם. (יש לדון אם לא שייך טעם איסור, שיש לומר שזה כעין קנס, כדי שלא יגור עמו כלל. ותחשב.)
** מגילת תענית -
עיין ברש"י, שזה מעניין.
ודע שכיון שכתוב, ק"ק למה ביעתא בכתחא הוא יותר מסתבר שיורה בו, ששאני מג"ת שכל אחד יכול לעיין בה. ותחשב. יש לדון בזה, שאולי לא ידעו לקרוא.
** ר"ח -
נמצא שהיה ר"ח תלמיד של ר"ה.
* סג.
** תלמיד חבר -
עיין בהגדרת רש"י. נמצא שבעיר של תלמיד חבר אחר, לא יכול לפסוק. קשה, שכמעט כל ת"ח יהיה תלמיד חבר של כל ת"ח אחר. אם כן, אין מי שיכול להורות. יש לומר שרק לא יכול לפסוק אם האחר הוא רב העיר, שאז רק רב העיר יכול לפסוק. ותחשב.
** לשאול -
רש"י פי' מיתה, ולכאו' זה מוכרח, ממה שלמד מיהושע. אבל, בדר"כ שאול ר"ל גהנום. יש לדון למה אמר כן כאן, כיון שרצה לומר מיתה.
** תילתא -
עיין ברש"י. קשה, שגם אינו בשליש גידול שלו, אם נברא מספר יצירה. צריך לומר שנעשה כעין בשליש גידול שלו. אם כן, נוכל לומר שגם נעשה כעין שלישי לבטן. ותחשב.
** סבר מר הכי -
מעניין שהיה רב אשי קורא לרבינא מר. ותו"ת.
** ולטעמיך -
קשה מה משיב. נראה שרצה לומר שהיה גר שם, ולא שפסק שם. וא"ת מה לנו שהיה גר שם - גם יש להקשות מה לנו בשמו, ואז צריך לומר שהוא כדי שלא נאמר שמשל הוא.
** משל -
עיין בב"ב (קרוב לטז) כעין זה.
** ולאפרושי -
מעניין שמביא ראיה מרבינא לפני רב אשי, שהיה תלמיד חבר שלו, ולא רק תלמיד שלו.
* סג:
** פו"ר -
מובן שהוא מדה כנגד מדה, שבטל בני אדם מלהיות להם בן. (גי"ל כן בצד ראשון, שביטל את הרב מלהוציא את תורתו בעולם, שהוא צאצאי תורתו. ותו"ת.)
** פו"ר-
קשה איך היו יכולים לקיים פו"ר, שהיו צרים על עיר. ותו"ת.
* סז.
** כרבנן -
יש לדון למה לא יכול לבטל רשות לבני חצירו, וכיון שהם כבר עירבו, ונמצא שהוא רשות שלהם, לא יאסרו על בני החיצון. ותחשב.
* סז:
** מותבינן -
יש לבאר את זה על פי מה שטענו אחרונים שאין רע באי' דרבנן אלא מה שהלך נגד רבנן, והרי כיון שלא ידע שהוא אסור, אף אם לא דן בו כל צרכו, לא נחשב רע.
* סח.
** לא אמר זיל אחים -
קשה, שאף זה אין בו מעשה, שרק דיבר לו. ויש לומר שרצה לומר שמה שנקט אף לומר דבר שאין בו מעשה גדול מראה שיש חילוק בין יש בו מעשה לאין בו מעשה, וכש"כ שיש חילוק בין ממש שי בו מעשה לדיבור.
** ב"ש -
יש לדון למה תלה בב"ש (שבדר"כ לא סותמים כמותו) וב"ה, ולא בר"י ור"מ (ביין כותים).
* סח:
** רבי יהודה -
ואם תאמר רבי יהודה שווה לת"ק. ויש לומר שבא ללמד שיטת רבן גמליאל.
* סט.
** מומר וגילוי -
יש לפרש שטעו בין "מומר וגילוי" ל"מומר בגילוי" כיון שוי"ו דומה לבי"ב רפויה. אבל, זה רק אם וי"ו אומר כמו וו"י באנגלית, ולא אם אומר כמו דאב"ל י"ו באנגלית. אבל, בי"כ ובי"כ לא נראה לומר כן, שהבי"ת תהיה דגושה, שהיא בראש מילה, ובוודאי לא יהיה דומה לוי"ו.
* סט:
** מומר לע"ז -
ואם תאמר למה הוא לא יביא קרבן. יש כמה תשובות:
- אף אם מביא, חושבים שלא יחזור.
- לא רוצים שיחזור, שלא זוכה לכך, כיון שרשע גדול הוא. דחוק.
- עונשים אותו שלא יוכל לחזור. (זה שונה מצד שלעיל.)
- קרבנו כל כך רע עד שלא מקריבים אותו, אף שמביא אותו לידי תשובה.
** ואין נוטלים -
יש לדון מהו הבעיה אם שנים נוטלים רשות ונותן אחד לחבירו:
- נשאר לשניהם הרשות.
- לא ניתן כל הרשות לשני, ואז אין לו כל הרשות.
תחשוב על זה, שיש חילוק ביניהם.
* ע:
** או דילמא -
מעניין שאין לו אף צד אחד שלא צריך להיות ראוי לערב. מעניין אז שאומרים - ושכל כך פשוט - שיכולת לבטל רשות תלוי ביכולת לערב.
** עירב ... הואיל והות' -
יש לדון אם זה דין בשבת או דין בעירוב. ותחשב.
* עב.
** נהגו -
קשה איך נאמר כן כאן, שרבי מאיר מחמיר. שו"ר שתוס' דן בזה.
* עה.
** תרי זמני -
יש לפרש שאומר אותו פעמיים - לגמ' כאן ולגמ' בחולין (יט).
** חוכא -
ועוד, שכאן ממ"נ הוא.
* עו.
** ארבע על ארבע -
יש להעיר שזה קטן מגודל אדם (שהוא טפח על טפח). צריך לומר או שנחשב פתח כיון שיכול אדם להקטין את עצמו או שנחשב פתח כיון שיכול לשים חפצים מכאן לכאן מחמתו. יש להעיר שלשני מעניין שצריך להיות בתוך עשרה. ותחשב.
* עז:
** פורחות -
מן הגמרא יוצא ככה: אם הם פורחות, אז, הם קשים לעלות בהם. אז, מצאנו מחלקת אם צריך להיות שיש פחות משלש ביניהם. אבל, אם הם כמדרגה, וקל לעלות בהם, לא צריך להיות פחות משלש ביניהם. כן נראה לי, וצריך לעיין.
* עח:
** איסור שבת -
נראה שהענין הוא שהקרק' של יש בו איסור יותר חשוב כיון שבאים להתיר בו איסור שבת על ידי עירוב, ואז מה שיש בו איסור שבת קרק' חשוב. גי"ל שאומרים שלכל מי שרוצה לערב בזה, לא ילכו מזה לזה, שיודעים שמקפידים על הלכות שבת. אז, אין אדם יכול לסמוך על זה לעירוב. ותחשב.
* עט.
** דקאים -
וא"ת כיון שאסור להוליך אותו, ורק מותר לעמוד לפניו, למה אמר שאסור בידים, ולא אמר שאסור להוליך אותו. נראה שלעמוד לפניו הוא דרך להוליך אותו, ואז לא הזכיר הולכה שלו כיון שזה תלוי איך עושה כן.
** מבטל
מגמרא זה משמע שיכול לבטל באמצע שבת (עיין לעיל, שדן גמ' בזה). עיין לקמן, שמדיחוי גמ', ראיה זו יידחה.
* פא. -
** בכל ... פת -
איני מבין איך "בכל" יכול להיות משמע פת, שמוציא ממנו מקצת דברים שאינם פת, שמשמע ששאר דברים שאינם פת כשרים. ותחשב.
* פא:
** למימרא דפליגי -
קשה, שפשוט שחולקים, שהרי משנה זה נאמר כאן, בענין עירובי חצירות. ותחשב.
* פב.
** אומנות אחר -
עיין בביאור הפסול, לפי רש"י. לכאו', הענין הוא שכיון שמה שעושים בשביל פרנסה קל, לא מכירים בצער בני אדם בממון. כמו"כ, יש לומר שרק עושים כן אם כבר יש להם הרבה כסף, ואז לא מכירים בצער בניא דם. אבל, קשה למה לא פוסלים שאר בני אדם שעושים דבר קל, כמו מי שלומד בכולל, או אדם עשיר. ותחשב.
* צד:
** פי תקרה ... ארבע ־
מעניין שהבעיה הוא לתת לארבע, ולא שצריך שכבר יש מקצת רוחות ממשיות. ותו"ת. יש לדון, לפי זה, מה יקרה בעגול. ותחשב.
* צה.
** פטור ־
יש להעיר שלכאו' לא רק פטור, אלא שאסור הוא. אפשר שנקט תחילת הדין, שאסור כיון שפטור הוא. אבל, עיין בתחילת יבמות שלא משמע שנאמר כן.
* צו.
** צריך דעת ־
נראה שמה שצריך דעת יותר לעבור הוא אולי מפני שעיקר התוצאה הוא הטוב שלו, ולא הרע שלו, ואז יותר קל לעשות אותו, ועוד שסתם דעת אדם לעשות טוב ולא לעשות רע. ותחשב.
* צו:
** עולה לרגל ־
היה אפשר לחלק ששם מתיר כיון שאין שום רע בזה, מה שאין כן בשאר הציורים. ותחשב.
** חדשים ־
צריך ביאור למה חדשים נראים יותר כקמיעה. אולי לא לובשים קמיעה כל כך. גם אפשר שלא לובשים אותו כדרך תפילין, ואז לא נעשה ישן. ותחשב.
* צז.
** מכמה בני אדם ־
נמצא שלא עושים חזקה לומר שלקח אותם ממומחה אחד, שיש בזה שני הנחות.
* צז:
** כספר תורה ־
יש להעיר שכדי לבאר את המשנה, צריך לומר שהיה יותר דומה למגילה מלספר תורה.
* צח:
** חורין ־
גם יש לפרש שאז לא נופל, שהוא רחב.
* צט.
** הא אם הוציא ־
נראה שהטעם שמניח שאז חייב הוא ממה שגזר מחמתו. ותחשב.
* צט:
** גת ־
יש לדון אם זה מדין או רק גזירה, לפי רבא.
** ויצרף ־
מעניין שנעשה רה"י, כיון שהוא למטה מי'.
** בור ־
צריך ביאור, שנופל לתוך רה"ר, מיד כשנופל מן מחיצות הגג. תו"ת, ותמצא שמש"כ נכון.
* ק.
** מטפס ועולה ־
נראה שמה שמזכיר עולה בדר"כ ראשון הוא אגב גמרא זה. ותחשב.
** עביד מצווה ־
לרש"י, הנידון הוא שעוד משתמש באילן. גי"ל שהוא משום עונג שבת. אבל, אין בו מצווה, כיון שאין עונג בירידה עצמו, אלא במה שהוא תחתיו. ותחשב.
** רבה ור"ש ־
עיין במה שפירש"י, שנמצא שיוצא מכאן שני מחלקתים שלא תלויים זה בזה, כנראה, והם דבר היוצא מן האסור ודבר שהוא לגבי צד אחד למעלה משלש.
* ק:
** תובעת ־
נראה שהמעלה הוא שהוא לא כופה אותה כלל, עד כדי שהיא תובעת ממנו.
**  דרך ארץ ־
מעניין שלומדים דרך ארץ מהם, כיון שד"א שלהם הוא לשקר בפיוס שלהם.
* קג:
** בשיניו אין ־
עיין ברש"י שמבאר למה רבי אליעזר מודה שאין איסור דאו' בשל חבירו, ומפרש שהוא מפני שאין חברו עושה אותו שפיר. מעניין, שהייתי אומר שהוא מפני שזה משונה. אף שכשהוא עושה אותו שלא בכלי, אינו משונה, כשאחר עושה אותו על ידי דבר חוץ מכלי, משונה הוא. אבל, מרש"י משמע שפטור כיון שלא נעשה שפיר.
אולי רצה לומר שאין הפטור בכלל משום שינוי, אלא מפני שלא נעשה התוצאה כל כך. גם אפשר לפרש שרצה לומר שרק נחשב משונה אם התוצאה משונה. יש שני דרכים לומר זה ־ דרך ראשון הוא לומר שמה שמשונה צריך להיות התוצאה, ודרך שני הוא לומר שמה שמשונה צריך לשנות את התוצאה (שרק אז הוא חשובה). ותחשב.
** חבירו ־
יש להעיר שלכאו' יש חידוש בזה במה שמותר לחברו לעשות כן, אף שהוא שבות, כדי שהוא (רצה לומר, לא העובר) יקיים מצווה. ותו"ת.
** רבנן ־
גמרא מסיק שזה כרבי אליעזר, ולא כרבנן. צריך לעיין בזה, וברש"י כאן, שלא הבנתי איזה ראיה מביא. איני מבין למה מניח שרק אם נאמר כרבי אליעזר נוכל לחדש שממעטים באיסור ככל הצורך. לכאו', יכולים לומר כן גם לרבנן. ואם לא נרצה לומר כן, אלא נאמר שכיון ששבות מותר בדרבנן, לא צריך למעט בעבירה, נאמר כן גם כן לפי רבי אליעזר. ותחשב.
* קד.
** לחולה ־
משקלא וטריא של הגמרא משמע שאין איסור לשמוע לשיר כדי לישון, ואף למי שאינו חולה. אבל, זה קשה על הרבה ראשונים שאסרו את זה, אחרי החורבן.
* קד:
** ולא נביאים ־
וא"ת אמר שנביאים הותרו. ויש לומר שרצה לומר שלא מתורת נביאות שלהם, ולא מתורת מה שהביא אותם לנביאות (גדלותם בתורה), אמרו כן, אלא הם זכרו את מנהג האבות, ולכן התירו.
** בור הקר ־
צריך ביאור איזה איסור נוסף יש בו שמותר רק בי"ט.

* Footnotes
[fn:5] זה נשמע טוב, אבל, באמת, לא פשוט, שלא פשוט איך נאמר שהלימוד הוא ברמ"ח איברים, שאף שהוא משתמש ברמ"ח אברים כשלומד, אין ההשתמשות הלימוד, ואינו מוסיף כלום ללימוד. אלא, צריך לומר שהשוקו"ל עצמו עושה שהלימוד יותר טוב. אם כן, כבר מצאנו סיבה אחרת לשוקו"ל, ואין צריכים לסמוך על גמרא זה. יש להעיר שהוא כן גם בקול, לכאורה (אם לא שנאמר ששאני קול שהוא אומר דבר תורה עצמו), ושגמרא לא נותן טעם היחידי למה צריך לומר דברי תורה בקול, אלא מוסיף חומר לאמירת דברי תורה. ותחשב.
[fn:4] אבל, יש לדון כמה בני אדם יש בכלל "רבים" זה, שאיני יודע כמה בני אדם צריכים כדי לעשות שדבר ניכר לדרך. ותו"ת.
[fn:3] אבל, יש להעיר שגמרא לא היתה כתובה. אז, מה שהיה להם אותם תיבות אולי אינו כל כך חשוב. ותחשב.
[fn:2] צריך לומר שהיה פשוט לכל התלמידים שאין הל' כבית שמאי, ושלא היו טועים מחמת "הלכה" שאמר לחשוב שכיון שפוסק כשיטה שמפרש שיטת בית שמאי, הלכה כבית שמאשי.
[fn:1] נראה שצריך שלא נאמר אף אחד מהם, שאל"כ, נאמר את שיכולים לומר בפנ"ע ראשון.
