ב.
** מאימתי -
גמרא יבאר שמתחיל משנה בשאלה כזה כיון שהוא ממשיך מן הקרא. יש לדון, עדיין, למה נקט התנא לומר דרך שימשיך ממשנה, ולא רק לבאר את הדין. נראה שני צדדים עיקרים:
1. לא נקט להמשיך מקרא, אלא נעשה כן ממילא. זה אומר כך: המשכה מקרא, לכאורה, רצה לומר שכבר היה הקרא ידוע, ולמי שהיה ידוע, פשוט שמשנה זה ממשיך ממנו, שמבאר אותו ומוסיף עליו. אולי כל הדברים אלו הם כן, שלכאורה, ידוע אותו מצווה. אם כן, אולי בהכרח היה קאי על הקרא.
ויש לדון בזה, שאולי כדי שיהיה קאי עליו, צריך אף להיות ראפארינ"ס אותו. לכאורה, מה שזה אומר הוא שלפעמים אין כל הדברים שכתבנו לעיל נכון, וצריך דבר להזכיר אותם. אם כן, אולי כן כאן, ואז אם לא היה שואל כך, כדי להזכיר, לא היה קאי עליו.
ויש להעיר שלכאורה יש כמה דינים שהם דאורייתא שהם במשניות, ושם לא קאי עליו, שלא אומר שאלה. צריך לדון למה (וצריך לדון כן, באמת, בכל הצדדים).
1. נקט להמשיך מקרא, וזה היה יותר טוב. יש לדון למה זה יותר טוב:
  1. אולי רצה להיות קאי על קרא. יש לדון למה ירצה כן. אולי הוא כדי להראות שהוא מדאורייתא.
  2. אולי רצה לומר שאלה. יש לדון למה ירצה כן. אולי בני אדם שומעים יותר אם שואל.
** וכל הנאכלים ליום אחד -
יש להעיר שיש, לכאורה, ארבע דברים שקרים בזמן שקרבן בכשרות, והם:
1. יש מצווה לאכול קדשים.
2. יש סיבת המצווה לאכול קדשים.
3. אין איסור לאכול הקדשים.
4. אין סיבת האיסור לאכול קדשים.[fn:1]
אז, מזה יוצא שמותר ומצווה לאכול אותו.
אחר זמן נותר אינו כן, אלא נעשה אסור לאכול אותו. יש לדון מה קורה אז. יודעים שראשון אינו שם, שאינו מקיים מצווה, שאסור הוא. לא יודעים אם שני הוא שם. יודעים ששלישי אינו שם, שהוא אסור. יודעים שרביעי שם, שיש סיבה, לכאורה, לגרום את האיסור.
עדיין יש לדון מה גורם מה, שאפשר שיש שינוי ב4, שגורם שינויים אלו, או שינוי ב2, או שינוי בדבר אחר לגמרי. ותחשב. גם אפשר שאין כל השינויים באים מיסוד אחד, אלא שאז אין להוכיח יותר משינוי אחד (שאין צריך אלא ביטול סיבת מצווה, שאז נוכל לומר שהיה לעולם סיבה לעבירה, ולא נצטרך להניח שני שינויים).
** כדי להרחיק -
יש לדון אם ר"ל כדי שלא יאכל איסור נותר, או כדי שיקיימו מצוות אכילת קדשים. עיין ברש"י, שכ’ השני. לשון "עבירה" משמע כן.
יש להעיר שבקריאת שמע, החשש הוא לביטול מצוות עשה. נראה שאולי לכן רבן גמליאל לא גוזר גבי שמע. אולי זהו הביאור במה שאומר כאן, שאולי היה מבאר שיטתו, לומר שרק גוזר על העבירה. לא נראה כן, שלא היה מי שיקשה, שאף אם בניו היו מקשים מכוח מה שרבנן סוברים (כפי מה שבאר) כמותו, אלא שגזרו, אף אילו לא היו רבנן סוברים כן, היו מקשים כן. ותחשב. ויש לדון, שאולי רק מקשים כן כדי שיש שיטה שאומר כסברתם, ואז הקשו שיש להם לפסוק כן. זה אומר שלא הקשו כן כדי לפלפל אלא כדי לפסוק, ואז היה צריך שיש שיטה שסובר כן. ותחשב.
נראה שאפשר שאין חיוב לאכול קדשים, והוא רק מצווה קיומית. אם כן, מובן ל"ל גזרו כדי שיקיים אותו מצווה.
** מאי שנא דתני ערבית -
יש לדון ל"ל ישנה של ערבית כן. אולי הוא מפני שבסדר היום, שמתחיל משיאיר היום או משיקום אדם. יש לדון למה זה קובע סדר, אבל נראה שכן מדרהרים בני אדם.
** מ"ש -
יש לציין לברייתא (ד:) שאומר ש"אם רגיל לשנות, שונה, וקורא קריאת שמע.” נמצא שדרך אדם ללמוד קודם קריאת שמע של ערבית. אם כן, אולי מסתבר שנקדים של קריאת שמע, שזהו מה שיבוא לו ראשון.
יש לדון, שגמרא רק אומר שאז שונה, אבל לא אומר שרק אז לומד. ותחשב.
ב:
** וטהר יומא -
עיין במה שפרש רש"י שר"ל שיום נסתלק ונפנה. יש להעיר שיכולים לדון ביחס בין טומאה וטהרה:
1. אפשר שטומאה הוא דבר, וטהרה הוא העדר טומאה.
2. אפשר שטהרה הוא דבר, וטומאה הוא העדר טהרה.
3. אפשר שטהרה דבר וטומאה דבר.[fn:2]
לשון קרא, שמדמה טהרה למה שיום נפנה[fn:3], משמע כצד ראשון.[fn:4]
באמת, יש להעיר שלשון פנייה קצת משמע שיום נפנה ללילה. זה אומר שיום הוא דבר, ולילה הוא העדרו. ויש לדון, שאולי יש לומר כצד שלישי. ועיין במה שנכתוב על רש"י בס"ד.
ודע שאפשר לדחות כל זה לומר שקרא נאמר רק מפני דרהר של בני אדם, והוא שאולי בני אדם מדרהרים שטומאה יוצא. ותחשב.
(יש לבאר שכל לימוד זה הוא ממה שמילה של טהרה שנאמר גבי טהרה הוא שווה למילה זה שאומר גמרא. אפשר שיש למילה יותר ממשמעות אחד; גם אפשר שיש לו משמעות ויי"ג, ומשמע שינוי, או כדומה.)
** מברייתא -
יש לדון למה לא מביא ראיה ממשנה שלנו. לא יודעים איזה ברייתא מציין, ואז יש לומר שברייתא אומר כן בפירוש על קרא זה. אולי, אז, רצה להביא אותו ברייתא, ולא על דין קריאת שמע.
ויש להעיר שאף שלא ידעו הוכחה של רבה בר רב שילא, צריך לומר שהבינו אותו אחר הברייתא, שאם לאו הכי, הברייתא יהיה קשה להם. ויש לדון, שאולי סברו שהוא הלכה למשה מסיני בפירוש המקרא, או הוכחה אחרת.
** עני וכהן חד שיעורא -
אם כן, צריך ביאור למה נקט שיעור של עני, ולא אמר צאת. הניחא בכוהן יש לומר שמלמד לנו דין של זמן אכילת כוהן, אבל בעני אי אפשר לומר כן. אולי גמרא חוזר מזה, וסובר שצריך להיות תירוץ אחר. יש לדון מהו אותו תירוץ. גם יש לומר שזה סימן ידוע, ואז אינו קשה למה נקט אותו ולא זמן; גמרא הקשה רק גבי אכילת זמן כהנים, שאינו סימן ידוע, שלא מצוי. כמו כן, יש לומר שאינו סימן כלל, שהניחא גבי עני, עושה כן מפני שרוצה לעשות כן, ויכולים לראות מזה זמן, אבל גבי כוהן הוא עצמו צריך לשאל מתי מותר, ואז אינו סימן כלל, שהכל הולך לצאת הכוכבים. ותחשב.
** ואינהו -
לכאורה, אין זה רק צד, אלא אין סיבה לחשוב שאינו כן, שאין סיבה לחשוב שתלו אותו בימים דווקא. ותחשב.
** עני ובני אדם -
יש לדון מה רוצה בזה. לכאורה, לא עושה אז שאין כל כך מחלקת, שבין כך ובין כך יש שני שיטות. אולי עושה שיותר שיטות סוברים כמשנה. משנה הוא מסתבר (לכן רבי נתנו במשנה), ולכן מסתבר שיותר יסברו כן, ולא שיחלקו.
ג.
** וסימן לדבר -
יש לדון אם זה סימן למשמרות או סימן לשאגת ה’. על הצד שהוא בין המשמרות ובאמצע אחד, צריך ביאור למה הוא סימן. צריך לומר ששנים הם סימן למה שהיה גמרא מבאר, שהוא שינוי משמרות. ויש לדון, שאולי רק ר"ל שהוא סימן לענין דבר לענין המשמרות.
יש להעיר שיש לדון במה הוא סימן- ר"ל, שיש לדון אם הוא סימן רק במה שהוא באותו זמן, או אם הוא סימן במה שזה בא מזה או שזה בא ממה שגורם זה או כדומה. ותו"ת.
נראה ששני דיונים אלו יכולים להיות נוגעים זה לזה.
** למאן דגני -
עיין בשי"ח ש"י בגלגלים אחרים שביארנו למה אין אומרים אף שהוא זמן לפניו, ונפק"מ למי שיושב בתוך בית אפל. נראה שגם יש לומר שהוא מפני שזמן של לילה ארוך, ומסמא יוכל לשהות עד שיודע בברור שהוא לילה. אבל, זמן של יום (בפרט אם אומרים כרבי אליעזר[fn:5], ולא כרבי יהושע) אינו אלא מעלות עד הנץ החמה. אז, יותר צריך סימן. ותחשב על זה.
** שהמתפלל בדרך -
לכאורה, ר"ל אם הוא ירא שמא יפסקו בו עוברי דרכים. משמע שלכל מי שמתפלל בדרך יש חשש זה. זה- שיש חשש זה לכל הולך דרך- אינו נלמד מאליהו.
** שמנהמת ואומרת -
יש לדון אם מנהמת, ואחר כך אומרת, או שמנהמת, ובניהומו אומרת, או שבדרך כלל מנהמת, אבל עכשיו אומרת….
ג:
** במקומם -
נראה שיש לדון למה שנים אינם ניזוקים:
1. אולי אין מזיקים מזיקים את שנים.
2. אולי אין היזק של מזיקים שולט בשנים.
3. אולי אין מזיקים באים לשנים.
אם הענין הוא ראשון או שני, הענין הוא שיש לו יותר כוח במקומו. אם הוא שני, נראה שאולי מזיקים באים לבני אדם, אבל לא לשנים, אבל כאן, מקומו הוא, ומסתמא כבר הוא שם, ולא מהני כוח שנים לעשות שייצא.
** תיכונה -
הקשה לי א.כ. מהיכי תיתי שיש שלש; רק יודעים שיש מנין או"ד, ולא איבי"ן. נראה שלאיזה סיבה שאומרים ש"מיעוט רבים שנים,” ואז כשאומר קרא לשון רבים, דורשים שר"ל שנים, כך אומרים כן שהוא שלש. אולי הוא שייך לכלל של "תםסת מועט,” אבל לא הבנתי אותו כלל כל כך, שלא הבנתי אותו סברה שאומר רש"י.
** אחת מן התיכונה שבתיכונות -
לשון זה מוזר. לכאורה, ר"ל שיש שנים תיכונות, וזה היה אחד מהם. אם כן, היה לו לומר, “אחד מן התיכונות.” צריך ביאור.
** אשמורות -
מניחים ש"אשמורות" שווים ל"משמרות.” שוב ראיתי שכבר הניח כן לפני כן, שמשנה אמר "אשמורות.”
** כרבי יהושע -
משמע שתנא החולק על רבי יהושע חולק על מציאות זה. ויש לדון, שאולי אל כיוון לומר כשיטת רבי יהושע, אלא ר"ל שהוא מפני המציאות שגילה רבי יהושע. גם יש לומר שלא היה קורא לעצמו חסיד על מה שקדם לקרוא קריאת שמע, שכך היה חייב לעשות מצד הדין. אז, רק יכולים לומר שהיה משבח את עצמו בקדמת אשמורות לר"י.
אם כן, יש לדון איך יש כאן משמרות, שכדי לקרוא קריאת שמע קודם סוף זמנו, צריך לקום קודם אותו זמן. אז, הוא קצת חסר משני משמרות. אולי רובו ככולו (על כל פנים, ברוב כל כך גדול כזה).
** שית דליליא -
מעניין שזה נחשב אשמורות, שהיה אפשר לומר שאשמרות הם דברים ממשים, ולא רק חלקים שהם ארבע או שלש שעות. אם כן, אין זה שני משמרות. יש לדון, שאולי רק ר"ל זמן של שני משמרות. קצת נראה, שרק בא לשבח חסידותו, ואיך מה שהוא משמר ממש יגרום שהוא יותר צדיק.
** משמר ופלגא -
יש לדון אם ר"ל שהקדים לחלק ממנו או שכולו נקרא על שם אותו חצי. לאותו צד, אולי יש לציין למחלקת בגמרא חולין[fn:6] אם חצי כרוב. יש להעיר שאותו מחלקת הוא רק הוה אמינא. עיין שם.
** וכל שכן מילי דעלמא -
יש לדון מהו הכל שכן. אולי ר"ל שכל שכן שיכולים לומר דבר במילי דעלמא בשם המת. יש לדון, שדבר של תורה בשמו עושה ששפתותיו נעים, ודברי חול לא עושים כך.
גם יש לומר שקאי על איסור דיברו, ואומר שאם דבר שהוא מצווה אסר תורה, בוודאי אסר דבר רשות. אם כן, צריך לומר שיש סיבה אחת לכולם. אז, צריך לבאר מהו יסוד איסור זה. אולי הוא רק קלות ראש קרוב למת, שיש לו להראות עצבון. ותחשב.
גם אפשר שיש לועג לרש על כל דבר של שמחה וקלות ראש, שהם משמחים, והמת מקנא על מה שהוא שמח, והמת לא יכול לשמח.ויש לדון, שלכאורה (ואין זה מוכרח) שמחה שאינה של מצווה הוא רק טובת הגוף, ולא טובת נשמה. אז, אחר מיתת הגוף, אולי אין שמחה שאינו מצווה, שאין גוף, אלא רק נשמה. ויש לדון, שאולי, כמו שאף שהוא מת, נוכל לומר שנשמתו קצת מתיחסת לגופו, אולי יכולים לומר שגופו קצת חי ויכולים להרגיש. ותחשב.
** לא עבר עלי -
קצת קשה למה יזכיר חצות, שלא עבר עליו שום חלק מן הלילה. אפשר שחצות הוא הזמן שרוב בני אדם ישנים, שיש שמאחרים לשכב עד אז, ויש שמקדמים לקום מיד אחריו, אבל אז רוב בני אדם ישנים. ויש לדון.[fn:7]
** דוד היה יודע -
אם נאמר שדוד קם בנשף, ורק לא ישן כלל בחצות, אולי לא קשה, שאולי לא קם בחצות, ואז לא היה צריך לדעת זמנו, אלא היה כבר קם אז, וזה היה נכון על כל צד של חצות שבעולם. אז, היה יכול לומר שלא בא לו חצות שהיה ישן בו. ותחשב.
עיין במה שנכתב בס"ד בד"ה משה רבינו, שלא משמע כן. ותו"ת.
** משה רבינו לא היה יודע -
יש לדון למה היה משה אומר כחצות, שידע שיקרה בחצות, שהרי ה’ אמר כן, ואם כן, לא היה לו להזכיר מה שלא היה יודע. וצריך ביאור.
ד.
** משה בדאי -
מעניין שתולה בעצמו, ולא בה’. אולי הוא לשון כבוד.
מעניין שהיה יותר טוב אם יודה שלא ידע, שלכאורה היה אפשר לומר שגם זה מבזה את שם שמים. ותו"ת.
** למוד לשונך -
נמצא שזה מפני שחוששים שבני אדם יטעו, ולא מפני שחוששים שאם אדם לא ישיב, “איני יודע,” לפעמים הוא יטעה. ותחשב.
** אני נמלך -
צריך ביאור, אז, איזה טובה היה במה שעשה כן. אולי פסק כן, ורק אחריו שאל לאיש בשת, לדעת אם יפה הורה או אם יחזר. אז, יכולים לדעת יותר מוקדם. ותחשב.
** שמא יגרום -
ר"ל, שמא, אף שעכשיו הוא חסיד, לא יהיה חסיד לאחר זמן. ויש לדון, שאם ר"ל כן, קשה למה צריך לומר שחושש שמא יגרום החטא, שיש גם חשש אחר, והוא שמא לא יהיה חסיד לאחר זמן. אולי הדרך הוא שמי שהוא חסיד נמשך להיות חסיד, אלא אם כן חוטא. ותחשב. גם יש לומר שהיותו חסיד לפני זמן, בלי חטא, יזכה לו בטובה. ותחשב.
ד:
** ואי כרבן גמליאל -
צריך ביאור למה דן גמרא בזה, שהרי משנה מבאר שיטת רבנן. אולי דן אם מוכרח לומר כמו שמבאר רבן גמליאל בשיטת רבנן. קשה, שלא משמע כן מלשון גמרא, אלא משמע שדן מה סובר רבנן.
כמו כן, צריך ביאור ל"ל מביא ראיה ממשנה עצמו. זה, אולי, אינו כל כך קשה, שברייתא, אולי, מבאר יותר טוב ממשנה. ותחשב.
** אם רגיל לקרוא -
משמע שחלק ממה שרוצים זה אינו רק כדי שלא יבטל מקריאת שמע, אלא אף מפני שזה יגרום שילמוד יותר תורה. ותחשב.
** וכל העובר -
יש לדון מה מכוון לומר בזה:
1. אחר שהזכיר דין דרבנן, מזכיר, אגב, כמה צריך לעשות אותו הדין- “כל העובר….” עדיין יש לדון אם אומר סימן או סיבה. ותו"ת.
2. מבאר למה החמירו כל כך, והוא שכל שעובר על דין דרבנן חייב מיתה. לא נראה כן, שלא החמירו על דין דרבנן, אלא על דין דאורייתא של זמן ק"ש. חושב אני שיש כסף משנה שאומר שזמן ק"ש הוא רק דרבנן. ותו"ת.
** תפלות באמצע -
יש להעיר שמשמע שצריך להתפלל קודם קריאת שמע. לכאורה, כן הוא לביאור שני במחלקתם, אבל לא לביאור ראשון. ותו"ת. אולי יש סיבה אחרת שצריכים להתפלל קודם קריאת שמע (מעלים בקדושה, או סיבה אחרת).
** גאולה מאורתא -
יש לדון מה סובר רבי יוחנן:
1. אפשר שסובר שהיה תוצאה שבא רק ממה שקרה בלילה בלחוד. זה אומר שלא היה גאולה רק יציאה ממצרים, אלא היה דבר אחר שנקרא גאולה, וזה כבר קרה בלילה. ויש לדון מהו אותו דבר. אולי הוא גאולה רוחני (שאז קיימו מצווה, והיו רואיים לגאולה).
2. אולי סברו שהיו עומדים לגאולה בלילה, ורק נמנעו כיון שרצה ה’ להוציא אותם בתוך היום.
3. אולי סובר שגאולה לא רק כולל התוצאה של גאולה, אלא מה שנתן ה’ בידינו יכולת לגרום את הגאולה. אז, זה שייך אף ללילה, שאז עשינו אותם מעשים שגרמו גאולה.
** מאורתא -
יש לדון מה לנו בזה:
1. כיון שאין לילה זמן של גאולה, אין להזכיר גאולה בלילה. יש לדון למה.
2. יש רק להזכיר גאולה של לילה בלילה ושל יום ביום. יש לדון למה. כיון שכן, כיון שאין גאולה בלילה, אין מה להזכיר אז.
** קרא -
ק"ק, שדין תפלה הוא, לכאורה, מדרבנן. ותחשב.
** אר"א אר"א -
צריך ביאור למה זה כאן. ותחשב.
ה.
** ואם תלמיד חכם -
יש לדון אם ר"ל שאז מסתמא כבר אומר דבר (והחידוש הוא שאותו דבר מהני) או שאז אינו צריך לומר דבר.
לכאורה, יש להביא ראיה לצד שני (שתלמיד חכם חלוק), שאי לאו הכי, למה יהיה תלמיד חכם חלקו באמירת קרא של רחמים. ויש לדון, שאולי יש שני ענינים, וראשון נוגע רק לאחד.[fn:8]
** אף תלמיד חכם -
יש לדון אם אביי חולק או מפרש.
** כולם נתנו -
עיין כעין זה בירושלמי פאה.
** ואין עוף -
מעניין, שהרי הקרא אומר שהתעיף ואיננו.
** אפילו תינוקות -
קשה, שקרא משמע שצריך לקיים מצוות גם כן, אבל ריש לקיש אמר שיכולים ללמוד תורה בלחוד. נראה שסומך על גמרא בפרק בית שמאי (יבמות) שאומר שאין למי שלומד ולא עושה אף שכר לימוד. ויש לדון, ששם הוא רק צד אחד.
** נתן להם תורה -
קשה, שזה מפני שנתן לנו תורה, ולא מכר לנו, ואז אין אונס ממון. מעניין שבכל זה קורא עליו מקח. אולי משמע שיש מכירה כאן, שרצה ה’ שנקיים את המצוות. ותחשב.
** אפילו תינוקות -
יש לדון אם ר"ל שאז אין צורך במה שאומר ריש לקיש כן, או שמקשה שאז אין צורך באמירת קרא כן, וצריך לומר שקרא אומר דבר אחר. לכאורה, לא משיב מה הקרא אומר, ואז צריך להיות כצד ראשון. יש לדון ל"ל יקשה השני.
ה:
** בחסד ואמת -
יש לדון אם צריך כולם או רק אחד מהם. נראה שתלוי, אולי, במחלקת רבי יאשיה ורבי יונתן בבבא מציעא ובכ"מ אם צריך יחדיו. ויש לדון, עדיין במה שנדרש מ"עוון,” שאין בו וא"ו החיבור כמו שאר. ותחשב.
** בנים -
יש להעיר שלכאורה פשוט שאין מיתת בנים יסורים של אהבה, שמבטלים תלמוד תורה לאבילות. צריך לומר שלימוד תורה של אבילות הוא בכלל תלמוד תורה. חושב אני שזה דיון בפוסקים.
** חביבים -
נראה ששאל לו אם יש בהם ביטול תורה וכדומה.
** לוקים ר"י לנפשיה -
לכאורה, מקשה כן כיון שכבר מצאנו שיכול להקים את החולים. יש לדון מהיכי תיתי שמעשה ראשון קדם למעשה שני, שאולי מעשה שני קדם, ובאותו זמן לא היה לו עדיין אותם כוחות.
אפשר שמה שמעשה ראשון הובא ראשון מוכיח שקרה ראשון.
** דלא אפשת -
יש לציין לגמרא ב"מ (בתוך "פ"יים) שאומר שלא היה ר"י אוהב ללמוד עם ר"א.[fn:9]
** דינא בלא דינא -
קשה, שאולי היו יסורים של אהבה. אולי גרמו לו ביטול תורה. גם יש לבאר על פי מש"כ בשיח שי על רש"י ד"ה דהוו.
** בתר גנבא -
קשה, שאדם דן דין לנפשיה. אולי היה אפשר לבוא לבית דין. אף זה מחלקת. גם יש לומר שלכתחילה אין לאדם לדון דין לנפשו.
ו.
** במקום רנה -
יש לדון אם מה שטוב הוא שהוא מקום רנה או שהוא מקום המיוחד לתפלה. גם אפשר שהוא מפני מה שידרוש גמרא לאחר זה (שה’ מצוי שם).
** רנה -
לכאורה, יש מזה מקור למה שמשוררים בתוך תפלה. ויש לדון, שאולי אינו טוב, אלא נעשה. עיין בד"ה במקום רנה (דיבור שלפני זה).
אפשר שרנה הוא מה שמשוררים חזנים, שזה כולי עלמא מודים לעשות. יש לדון שידוע שאין זה לעולם רנה.
יש להעיר שהיה אפשר לומר שנקרא רנה כיון שהוא משבח ה’, אבל אין בו רינה ושירה ממש. נקרא על שם שירה כיון שהוא דומה לשירת מלכים. כמו כן, יש לומר שאין שירה למלאכים, אלא שכיון שכ"פ משבחים על ידי שירה[fn:10].
עיין ברש"י שלא נראה כצד זה, שכ’, “ששם אומרים הצבור שירות… בנעמת קול ערב.”
** מי משתבח -
לא הבנתי כל זה, שמשמע ששואל אם ה’ מתפאר בכבוד של בני ישראל. אומר שנתכבד, ומביא מימרא שכיון שבנ"י שבחו לה’, הוא השביח להם. לא רואים מזה, לכאורה שמתפאר במה שבני ישראל הם גוי אחד. ותחשב.
ו:
** משאיל בו -
לכאורה, ר"ל שואל בו. יש לדון ל"ל אומר שואל בו.
** אבל למיעל -
קשה למה צריך לומר כן, שהרי אומר בפירוש שהוא ביוצא מבית המדרש. יש לומר שהוה אמינא שיש חידוש יותר ביוצא. לכאורה, הצד שיהיה אסור בשניהם הוא שאינו כבוד, שהוא מראה קלות ראש, שלא הולך בכבוד, והוא קרוב לבית הכנסת. אולי זה יותר רע כשבא לבית הכנסת מכשיוצא ממנה.
גם יש לומר שתלוי במה שחלקו פוסקים אם מותר לפסוע פסיעה גסה לצאת מבית הכנסת כדי להכניס בו לאחר זמן יותר מוקדם. נראה שאביי מתיר זה, ואומר שאסור רק לצאת מהר כדי לצאת, ולא לצאת מהר כדי לבוא.
יש לדון מהו הבעיה בפסיעה גסה. אולי הוא שמראה שלא אוהב את בית הכנסת. לכאורה, זה בעיה של מראית עין או בזיון בית הכנסת. גם יש לומר שלא טוב לעשות דבר שהוא בא ממחשבה רעה, כמו רצון לצאת מבית הכנסת. יש לדון למה זה רע. אולי זה מחזיק אותו מחשבה. גם יש לומר שהוא טוב להיות קרוב לבית הכנסת, ואז לא יצא במהירות.
ודע שיש לומר עוד צד, והוא שאין הבעיה שהוא מהר (כך הנחנו עד כאן), אלא שפוסע פסיעה גסה. אולי פסיעה כזה אינו דרך כבוד. יש לדון למה. אולי הוא מראה את הערוה קצת. ודחוק.
** אלא במנחה -
יש להעיר שלא התפלל קודם לכן. אז, לכאורה היה לו לומר, “שהיה אליהו נענה במנחה.”
** אף… שחרית -
יש לדון על מי מוסיף.
** לעולם יהא זהיר -
יש לדון מהו "זהירות" זה. לכאורה, חיוב הוא להתפלל; אז, בוודאי צריך להיות זהיר. אפשר שאומר שיזהר שלא יהיה נאנס. גם יש לומר שיקפיד על דברים שעושים אותו תפלה יותר טוב.
** ואם נתן ולא החזיר -
לכאורה, לשונו משמע שעדיין רק קאי על מי שרגיל לומר לו שלום (ומסתמא זה רגיל לענות), שאז יכול זה להניח שחברו יענה לו.[fn:11]
** מחליין -
משמע שלשון חילול שבת נאמר אף על דבר שהוא רק מדברי כתובים (כגון זה שנלמד בשבת מ"ודבר דבר…").
ז.
** ניים -
יש לדון ל"ל עשה כן לבלעם.
** יכול לכוון -
ואם תאמר אינו קשה; רק יראו סימן של אביי. ויש לומר שאותו סימן גופא ידוע ממנו. למעשה, אחר שידוע אינו יחיד עוד. ויש לדון אם זה קשה על לשון גמרא, אבל לכאורה, קשה למה היה בלק משכירו. אולי לא הגיד עד קרוב למיתתו. גם יש לומר ששאר בני אדם ישנים אז. יש לדון מה סבר, אז, ריב"ל. גם יש להעיר איך הוכיח ממה שקרה לו שלא טוב לצדיק לענש, שאין שום אדם יכול לכוון. אולי כך היה הקמ"ל, וצריך לומר, אז, שאינו רק לצדיק; נראה שאולי "צדיק" בא לרבות אף צדיק.
גם אפשר שחולק ריב"ל על גמ’ שלעיל בנקודה זה (סובר שלא היה מיוחד לבלעם, ויכולים אחרים להבין על ידי ניסה זה). אם כן, שני קושיות אלו (מה היה הוה אמינא שלו, ואיך למד) מתורצים. ותחשב.
** בהנך תלת -
עיין לקמן במה שאומר רבי מאיר. ואם תאמר הרי לא קמים עד שלש שעות, ואם כן, איך אפשר להיות בתוך שלש שעות. ויש לומר שתלוי בטיי"מ זונ"ז. ותו"ת. גם יש לומר על פי רש"י (ג:) שאמר שקמים בתחילת שעה שלישית. עדיין יש לדון ל"ל אמר שהוא בתוך אותו שעה, שאי אפשר להיות קודם לזה. אפשר שמונה שלש שעות מזמן שקמים מלכים.
ועיין בחידושים מגלגלים הקודמים, שכתבנו תירוצים אחרים לזה.
** גמור -
לכאורה, משמע שגמור ר"ל בלי שום חטא, ולא רק שעל רוב הוא צדיק. עיין ביומא ובמקום אחר, שדיננו בזה.
ז:
** הפעם אודה -
יש לדון מהו הדרשה. אולי אין דורשים מזה שהיתה ראשונה, אלא שרואים כאן שהודה, ולא רואים כן קודם. גם יש לומר שמדייק מלשון הפעם, שממעט שאר פעמים לפני כן. ויש לדון, שאולי זה רק היה זמן ראשון לה, אבל אחרים הודו. אז, נראה כפשט ראשון. ותחשב.
** ובחללו -
עיין בתחלת פרק יש נוחלים שמשמע שלא מחמת זה בא בכורה ליוסף.
** לא אקנא ביה -
לכאורה, צריך לומר שכבר ידע באותו זמן שיהיה יוסף הבכור, שאי לאו הכי, למה היה לו להקנות בו אז.
** שמא גרים -
משמע שהשם הוא סיבה, ולא רק סימן.
ח.
** עדיפא מכולהו -
לכאורה, ר"ל שהוא הפירוש הכי טוב. גם היה אפשר לומר שהוא הדבר הכי טוב בתפלה, אבל אולי אינו פירוש הקרא. (לא נראה כן, שלכאורה, קרא אומר לאיזה דבר צריך תפלה. אולי הוא הכי טוב, אבל לא צריך תפלה כל כך.)
** עדיפא -
יש לדון אם לשון זה אומר שהוא הכי טוב מכולם, או שהוא יותר טוב משאר. ותו"ת.
** נהנה מיגיעו -
כמובן, צריך לבאר מה טובה של נהנה מיגיעו, עד שהוא יותר גודל מירא שמים.
ח:
** צנועים בד"א -
ואם תאמר הרי לא צנועים די, שאי לאו הכי איך ידע. ויש לומר שלמד ממה שלא ראה כלום. גם יש לומר שאמרו לו פרסיים כן. ויש לדון אם זה גופא בעיה בצניעות. אולי שמע מפרסי שצווה לאחר איך לנהוג בצניעות.
** והא דקרי -
אז, זה נגד מה שהניח גמרא (ב:) שקריאת שמע תלוי ביום ולילה. גם הוא מניח שלאחר שעלה עמוד השחר עדיין נקרא לילה. אולי יש לתרץ שניהם לומר שיש שני ציני יום ולילה, וזה הוא יום שמתחיל מהנץ, ועל זה אין קריאת שמע תלוי. (ויש לדון, שאז היה לו לומר שאף שהוא לילה, איו לילה של גמ’ לעיל, אבל לא אומר כן. אלוי זה ושכיבה וקימה הם דבר אחד. ותחשב.)
** איכא אנשי -
לכאורה, אז, יש סתירה בדברי רשב"י. אולי אחד משמו ואחד משם רבו. ותחשב.
** מחמת אונסו -
יש לדון אם יש לכבד אותו מחמת שהיהלפני זמן  בו תורה, או מפני שעכשיו היה בו תורה לולי האונס.
** הזהרו -
יש לדון אם אומר שיכבדו אותו או שלא יבוזו אותו. ותו"ת.  עיין ברש"י שכ’, “הזהרו… לכבדו.”
ט.
** דאיכא אנשי דגנו -
אם רק איכא אנשי דגנו, צריך לומר דאיכא שלא גנו, אלא קמים. אם כן, קשה למה רק יכולים לקרוא של לילה, ולא של יום. ואם תתרץ שיכול לקרוא אף של יום, אקשה לך למה צריך לומר שניהם ביום כך, באחד קודם הנץ ואחר אחר הנץ, ולא אמר שיכול שניהם להיות באותו זמן ממש. ותחשב.
אולי כיון שמשוה אותו לילה לענין זה, לא יכול להשוות אותו יום לענין זה. ויש לדון בזה, שלא משווה אותו יום או לילה, אלא זמן שכיבה וקימה, ואין זה סותר את זה, לכאורה. ותחשב. על כל פנים, אם היינו אומרים כן, היה מבאר למה אין סתירה בדברי ר"ש. ותחשב.
** עד שיעלה -
ק"ק למה מקשה שלא תני פסח, שיש הרבה עוד דברים שלא שנה. ויש לומר שעל אותם דברים לא גזרו רבנן. קשה, שמהיכי תיתי שכאן גזרו. ותחשב.
** מה כאן עד חצות -
לכאורה, כאן אינו עד חצות, אלא בחצות. ותחשב. שוב הבנתי שאינו כן, שעשה אותו רק בחצות. אם כן, היה עד חצות. עדיין יש לדון, אז, איך יודעים שאל נתחיל רק בחצות. זה יש לומר שאי אפשר לאכול אותו, אז. אז, רק יכולים לעשות אחד- או אכילה עד חצות או אכילה מחצות. יש לדון, עדיין, מהיכי תיתי לנקוט אכילה עד חצות, ולא אכילה מחצות.
** לא נגאלו אלא בערב -
יש לציין לגמרא לעיל (ד:) שחלקו בו, לחד צד, ר"י וריב"ל אם היה גאולה בלילה. גמרא זה משמע כר"י שם.
** יש להעיר שממה שאין
זמן שאסור לאכול אותו זמן שראוי להישרף, רואים, לכאורה, שאין הכרח לתלות זה על זה, ואין מה שעושה שאסור לאכול עושה שנשרף. לא נראה לומר שרק יש מניעה עד הבוקר, שהרי יש מניעה אף אחר כן, עד בקר שני. אולי רק דן במניעה אחת. יש לדון למה יעשה כן.
ט:
** בעל כרחם דישראל -
יש לדון מי השאיל אותם בעל כורחם. אפשר שה’ עשה כן, כמו שדרש גמרא לעיל. גם אפשר שמצרים עשה כן, שלא רצו שיהיו בני ישראל וה’ שונאים אותם. כמו כן, יש לומר שהכירו בחשיבות בני ישראל, ורצו להתייחס להם. ותחשב.
** לתפילין -
לא הבנתי את זה כל כך, שאם אינו מצווה שהזמן גרמא, אז זמנו מתחיל בכל זמן. אם הוא מצווה שהזמן גרמא, אז זמנו הוא ביום, ויום הוא אחר עלות השכר. אז, קשה ל"ל אומר שזהו זמנו. אולי זהו זמנו של אחרים. קשה, שהיה לו לאחרים לפרש.
נראה יותר שאין צריכים לומר שזמנו ביום דווקא. אבל, גזרו רבנן שלא ילבש אותו בלילה, שמא יישן בהם.[fn:12] זמן קימה הוא הזמן שמותר ללבוש תפילין, אז. אז, זמנו הוא זמן קריאת שמע, אלא שיש סיבה אחרת לאחר קריאת שמע (לסמוך לתפלה). ותחשב.
י.
** פתח באשרי -
קשה איך יודעים שזהו מן החביבים. אולי "דכתיב…" הוא חלק מן המימרא, ואז אמר שזה אחד מן החביבים.
** שפיל -
נראה שר"ל שאם מתפלל שיתמו חוטאים, אז קשה מה אומר בזה, שהוא כופל את מה שאמר. אז, צריך לומר שאומר שיתמו חטאים, ולא חוטאים, ואז ממילא לא יהיו רשעים. אף שפשוט שלא יהיו רשעים, עדיין הוא דבר חלוק ממה שאמר שיתמו חטאים. ותחשב.
גם יש לומר שלא פשוט שלא יהיו רשעים, שצריך להתפלל שלא רק ימנעו מלחטוא, אלא ישובו על מה שכבר חטאו. ותחשב.
** יסורים -
כמובן, יש לדון ל"ל עשה ההיפך.
י:
** אפילו בעל החלומות -
ה"אפילו" מעניין, שכל חלום יש בו קצת שאינו אמת. צריך לומר שאי אפשר להוציא מעט ולומר שיחיה, שכל החלום אמר שימות. ותחשב.
** החייה את בנה -
יש לחלק, ששם היה בנה יחידי, אבל כאן, היו אחרים לשלמה. ותחשב.
** על אחת כו"כ -
יש לדון אם הענין הוא שעשה יותר, או שעשה אותו לבית המקדש לה’, ולא רק לצדיק.
** בזכות -
קשה, שלכאורה, יותר טוב להיות בזכות אחרים, שאז אין מנכים מזכותו. ויש לדון, שאולי שני הזכויות גורמים לו טוב, ומה לו איזה זכות נתמעט. עדיין צריך ביאור מה לו אם בא לזכותו.
ויש לומר שהטובה הוא שאומר ה’ שבא בזכותו, וזה כבוד לו. כיון שהגענו לזה, יש לומר שלא ממעט זכותו, ולא בא מזכותו, אבל ה’ אומר שבא מזכותו. ותחשב.
** כשמואל -
יש לחלק, ששמואל היה שופט של כל ישראל, ולא רצה להיות לו הטייה בדין.
יא.
** בשעת שכיבה -
קשה איך רואים כלל זמן לפי בית שמאי. ותחשב.
** אתה מטה -
אינו ממש דומה למשל, שבמשל, ספר מה שאמרו לו שהוא נאה. כאן, אינו כן, שלא גילה ר"א שרצה שישב ר"י. נראה שכיון שישב ר"א, גילה שסבר שטוב להקפיד כבית שמאי, ואז גילה שטוב לעשות כן לכל, וגם לר"י. אז, דומה למשל.
זה מניח שעשה כן לקיים דברי בית שמאי, ולא רק היית רוצה להיות מוטה. ותחשב.
** כדאי היית -
פלא הוא, שאולי חייב מיתה מפני שסכן בעצמו. לעשות שאינו כל כך קשה, יש להעיר שאי אפשר שהיה מסכן בעצמו כל כך, שהרי לא היה ראוי לעשות כבית שמאי ולסכן את עצמו, שלכאורה, אף בית שמאי יודו שאינו דוחה פקוח נפש[fn:13].
היה נראה לומר, וזה יתרץ שני הקושיות, שלא אומר שכיוון לסכן את עצמו, אלא שקרא כבית שמאי, ומה שנגרם מזה היה שהיה מסתכן מפני הליסטים. אם כן, פשוט שאין מה לחייב אותו עליו, שאל כוון לסכן את עצמו.
עדיין קצת קשה, שאם כן, קשה למה מזכיר אותו רבי טרפון כלל. אולי מזכיר שחושב שזה היה סימן שלא טוב לעשות כבית שמאי, וחכמים אומרים שלא רק שלחו לו סיןמ, אלא זה היה קצת עונש שלו, שהיה ראוי להיות הומת, אלא שניצול בזכות. ותחשב.
ודע שאם היה לו לעשות כבית שמאי, ואף במקום סכנה, אפשר שאינו כל כך קשה ל"ל אומרים שנענש כיון שנתן את עצמו במקום סכנה, שאפשר שכך הוא כוונת גמרא כשאומר שעל כעין זה חייב מיתה, שכעין זה אינו רק עשייה כבית שמאי, שלמה לא יעשה כן[fn:14], אלא כעין זה ר"ל באופן שחב לעצמו ועובר על דבר לעשות כבית שמאי, שמה שעשה אותו כדי לעשות מצוה מן המובחר להחמיר כבית שמאי לא מציל אותו מן העבירה. אם כן, הוא ממש דומה למשנה שלנו. ותחשב.
** רב יוסף -
קשה איך יבאר מעשה של רבי ישמעאל ורבי אלעזר בן עזריה. אולי סבר שלא קרה או לא קרה כן. גם יש לומר ש"ועוד" ר"ל איהו היה בית הלל מודה, אבל באמת, לא מודים. גם יש לומר שרב יוסף לא אמר מה שאמר אלא בציורים שעובר על דבר מחמת זה (עיין לעיל, שכתבנו צד כעין זה).
יא:
** מעליא -
מעניין שחושך אינו לשון מעליא.
** למקרא צריך -
רש"י מפרש שדיון של גמרא זה קאי אף לפני אהבה רבה (כשפוטר). יש לדון אם אף קאי לאחר אהבה רבה (לחייב). לכאורה, לא אפשר לומר שקאי לאחריו גם כן, שאם כן, אין חילוק בין לפניו ללאחריו. ויש לדון, שאולי רש"י אומר כן רק על גמרא. ותחשב.
** מקרא -
יש לדון למה יברך יותר על מקרא:
1. אולי יש בו יותר טוב בלימוד אותו. אם כן, אולי יותר יש לברך ה’ עליו.
2. אולי הוא מפני שיותר בא מה’, שאין בו מה שבני אדם מחדשים. אם כן, יותר יש לברך לה’ עליו.
** ספרא דבי רב -
קשה, שזה מדרש (כמו שאמר רש"י בפירוש). אולי רב היה שונה גמרא עליו. קשה, שעדיין לומד עמו מדרש, ויהיה חייב מחמת זה. אולי אם רק לומד זה כדי לדון בו ולהגיע אל גמרא, לא יחייב. חוץ מאותו חידוש, קשה לומר שלא היה לומד אותו רב אלא להיכי תמצא לומר גמרא.
אבל, דע שלכאורה כן קשה על כל גמרא, שיש בו משנה. אולי מיירי בשהמשנה כבר ידוע, ועכשיו דנים רק בגמרא. גם יש לומר שמשנה גם שייך לדיון במאמרות של אמוראים. ותחשב.
** לימרינהו -
כמובן, קשה איך יכול לחדש לומר ברכה שהוא אולי לבטלה כיון שיש כל כך צורך לברכת התורה. ותחשב.
** הילכך -
צריך ביאור מהו ה"הילכך.” בשלמא אם היה אומר שהוא מעולה כיון שצריך כל כך לברך על תורה, יש לומר שאז חשו לומר ברכה שהוא בוודאי טובה. אבל, עיין ברש"י שלא משמע כן, אלא שנראה שאומר שברכה הוא טוב כיון שיש בו הודאה ותורה וכדומה.[fn:15] אם כן, צריך ביאור איך זה גורם שיברך שני ברכות. ותחשב.
** היינו… מעכבות -
קשה, שבין כך ובין כך יש להקשות אולי אמר השני לאחר זמן כשיש לו פנאי. אולי אין יותר פנאי לאחר זמן מעכשיו. גם יש לומר שכיון שאפשר רק לומר אחד, פשוט שיש קיום באותו אחד, ואז לא רואים הדין כשאומר אחד ויש יכולת לומר שניהם. דחוק לומר כן. גם לא נראה כן ממסקנת (ר"ל, דחיית) גמרא. ותו"ת.
יב.
** בתר עיקר ברכה -
יש לדון מהו הפסול:
1. עיקר ברכה לא יכול להיות קאי על המאכל.
2. מחשבה של ברכה לא קאי על חתימה. אז, דן אם צריך מחשבה של עיקר ברכה או של חתימה.
היה אפשר לומר צד אחר, והוא שהפסול יהיה ששינה מן תחילת ברכה לסוף ברכה. לא נראה כן, שלשון "בתר עיקר ברכה או בתר חתימה" לא משמע כן.
על צד ראשון, קל להבין למה אין בעיה אם יכול לצאת בשני הברכות, שאז שניהם קאי על המאכל ופוטרים אותו.
על צד שני, יותר קשה, שעדיין לא היה לו מחשבה נכונה. אולי מחשבה שהיה לו הוא דומה די, שכולל זה.[fn:16]
שייך לזה, יש לדון אם עיקר ברכה ר"ל שם ה’ או ר"ל מחשבתו. ותו"ת.
נראה שהיה אפשר לומר צד (וצריך לדון איך לבאר לשון גמרא לזה) שהפסול יהיה שהברכה דחוייה, שהיה כבר עומד להיות ברכה לדבר שאינו מהני, ואז נדחה מהיות ברכה טובה. אם כן, פשוט שאם יכול לקיים באותו ברכה שהיה כבר עומד לומר שאין בעיה. ותו"ת.
** מפני תרעומות -
צריך ביאור מה טוענים, שלכאורה קשה להביא ראיה מעצמינו לומר שאנו  טועים, שבהכרח אנו סוברים שאין אנו טועים. ויש לומר שמביאים ראיה מרבותינו שתקנו לעשות כן. ותו"ת.
** לא יצא ידי חובתו -
לכאורה, מחדש חובה, ואומר שלא קיים אותה. לשונו, אז, קצת מוזר. אפשר שידוע שיש חובה להזכיר טובת ה’, אלא מלמד שיש חובה לאומרו ביום ובלילה.
** כשהוא כורע -
לשון זה מוזר; לכאורה, היה לו לומר, “כורע….” אולי אינו חיוב ממש לכרוע, ואומר שאם רוצה לכרוע, כך יכרע. עדיין לשון "כש" לא משמע כן, שהיה לו לומר, אז, “אם….” ותחשב.
יב:
** קבעוה -
יש שיטה בגמרא (עיין לקמן) שאומר שחייב אדם לקרוא קריאת שמע מדאורייתא. יש לדון קצת בשיטה זה. ראשון, יש לדון מהו המקור לקרוא קריאת שמע בכל יום. אולי הוא "ודברת בם.” אם כן, צריך לומר שאין מילים אלו קאי על תלמוד תורה (כמו שאומר גמרא מנחות לאסור דיבור בדברים בטלים). שוב ראיתי שכן יאמר אותו גמ’ לקמן.
גם יש לדון מה צריך לקרוא מן התורה, ומהו המקור לזה. מה שגמרא כאן נוגע לדיון זה הוא כך: אומר שרצו לקבוע אותו. יש לדון אם היו עושים אותו חיוב דרבנן לומר אותו עם שאר קריאת שמע, או היו עושים אותו חיוב דאורייתא. אם היו עושים אותו חיוב דרבנן, אז רואים שרבנן קבעו חיובים דרבנם עם חיוב דאו’ של ק"ש; אז, קל לומר כן אף בפרשיות אחרות.[fn:17] אם נאמר כצד שני, לכאורה, צריכים לומר שמסרה לחכמים לקבוע מה יהיה בכלל החיוב דאורייתא. ותחשב.
** מצוות ציצית -
מעניין מה שרוצים להזכיר מצוות ציצית. שאר דברים הם, לכאורה, דברים חשובים ועיקרים[fn:18], אבל ציצית לכאורה אינו כן. יש לומר שאין הכי נמי, אבל יש קצת טוב בהזכרתו, ואז מוסיפים אותו למעלה. גם יש לומר שהוא עיקרי, כיון שהוא כנגד תרי"ג מצוות, או כיון שהוא דומה לרקיע…, ואז מזכיר כסא הכבוד. ותחשב.
** הרי אני כבן -
צריך ביאור מה לנו בזה. אילו היה ממש בן שבעים, ואמר שאף בהמשך הזמן, לא היה זוכה שיקיימו את דבריו, אז אולי היה מובן, שהיה יותר נראה להיות מקובל לזמן ארוך, שניסה ליותר זמן. כיון שרק אומר כמש"פ רש"י, קשה מה לנו בהיותו כבן שבעים שנה. אולי ר"ל שאף שהיה כל כך חשוב, שנס כזה נעשה לו כדי שיהיה ראש ישיבה, לא שמעו לו לאמור יציאת מצרים בלילות.
** עד שדרשה -
יש לדון מה סובר ראב"ע, ומהו מקורו. אם מקורו הוא מקרא זה, קשה מה שינה כשאמר כן בן זומא. אם מקורו הוא ממקום אחר, קשה למה שמח במה שקבלו דברי בן זומא. נוכל לתרץ לצד ראשון ולצד שני.
לצד ראשון, יש לומר שדרשו אותו דבר, אבל האמינו בן זומא יותר כשדרש, שידעו שמסתמא הוא נכון, שהרי היה דרשן טוב (כמו שמבואר בסוף סוטה).
לצד שני, יש לומר ששמח במה שעשו בדין, אף שלא דרשו אותו מקרא הנכון. ותו"ת.
** נתכפר -
אם נתכפר, קשה למה היה צריך למות, וקשה למה לא היה המלוכה הולך לבניו, שזה היה עונש לעבירה, אבל עכשיו לא צריך אותו עונש. באמת, קשה בכל זמן שעשה אדם עבירה ונענש ושב, שאז נמצא שבטל העבירה למפרע, ואז נענש בחנם. יש לדון שאולי לא בטל העבירה למפרע, אלא מכאן ולהבא. עדיין נמצא שאף שעונש היה על עבירה לא היה נצרך. ותחשב.
אולי מניחים שלא היה עושה תשובה אם לא שהיה כבר קצת נתכפר מחמת העונש. ויש לדון מהיכי תיתי להניח כן ולענש אותו. ותחשב. אפשר שהוא ספק ספיקא, ששמא לא ישוב, ואף אם ישוב, מי יאמר שהיה שב. ויש לדון למה לא רק עושים ספק אחד, והוא אם שב בלי עונש. ותחשב.
יג.
** משכחת -
אם נשכח, אז קשה למה מזכירים אותו עוד. אולי לא נשכח לגמרי, אלא ר"ל שנשכח קצת, שאינו כל כך חשוב. דחוק. גם יש לומר שאינו עוד פלא שעשה ה’, ולא יאמרו אותו להראות גדלות ה’, שיש ראיות יותר גדולות, אבל עדיין צריכים להודות לה’ עליו, שהרי עשה לנו טוב בו. אולי קריאת שמע הוא הודאת טוב לה’ על מה שעשה לנו, ואז עדיין צריכים להזכיר אותו. היה אפשר לומר שזהו יסוד המחלקת בין ראב"ע ורבנן.
דע שהנחה זה, שקריאת שמע הוא מחמת הודאה לא פשוט. ר.ש.ש. לא אמר כן.
** נחש -
משמע שנחש יותר קשה מארי. זה מעניין. אולי הוא מפני שנחש אוכל אף בלי הנאה (תענית ח.), ואז אי אפשר לצדד שכבר אכל ואז לא ימית אותו.
גם אפשר שזוכר אותו יותר מפני שהוא אחרון, ולא מפני שהוא יותר גדול. לכאורה, אינו כן בנמשל (של גוג ומגוג נגד יציאת מצרים).
** יהיה שמך -
קצת צריך ביאור איך עובר על זה במה שקורא לו דבר אחר, שעדיין זה שמו. אולי פירוש של שם הוא מה שבני אדם קוראים לו, ואז לא משנה את שמו. ותחשב.
** בפרקים שואל -
יש לדון אם זה נדחה או הותר. הצד שנדחה הוא שיש כאן הפסק, שהרי מדבר בתוך קריאה שלו, אבל צריך לעשות כן מפני הכבוד וכדומה. הצד שדחוי הוא שחלק מההפסק הוא היסח הדעת. לא מגלה היסח הדעת בזה, שלא צריך להיות חושב עליו כל כך, ולא חושב על דבר אחר, כדי להשיב להם, שהרי מוכרח להשיב. ויש לדון, שזה מניח שההפסק הוא שמה שהכיר להשיב טעון היסח הדעת. אם כן, לכאורה, ההשבה הוא רק סימן, וקשה למה יאסר. יש לומר שיש הפסק במה שעושה שנראה שהפסיק בהיסח הדעת. גם יש להעיר שהיה אפשר לומר שיש היסח הדעת שיוצא מהשבה עצמו. לכאורה, ממשנה יוצא שזה אינו כן.
כמו כן יש לדון, כמובן, בחילוק בין השבה לשאלה. ותו"ת.
** ואחר כך עול מצוות -
יש לדון למה רוצים זה:
1. אפשר שקבלת עול מלכות הוא יותר נצרך. אז, טוב לקבל אותו ראושן. ויש לדון אם הוא יותר חשוב ונצרך.
2. כמו כן, יש לומר שמקדימים את היותר חשוב, לא כדי לעשות אותו ראשון, אלא מפני שהוא יותר חשוב, ודבר חשוב קודם (כמו, למשל, גבי מקודש שקודם. ויש לדון, שאולי בכל זמן שחשוב קודם הוא כדי שימשכו תוצאות שלו לזמן ארוך. ויש לדון בזה.)
3. .אפשר שקבלת מצוות הוא יותר טוב אם מקבל אותם מחמת מלכות, שאי לאו הכי, לא מודה שיעשה אותם מפני ה’, אלא לסיבה אחרת. אין זה קבלה טובה. ותחשב.
** נפקא ליה מדברים -
מעניין שפשוט לגמרא שאי אפשר ללמוד שניהם מחד קרא, שהיה אפשר לומר שקרא אומר שצריך להיות כצורה שאומרת תורה בדווקא, והרי צורה זה יש בו שני קרק’, שהוא באותו סדר והוא באותו לשון.
** מצוות צריכות -
יש לדון למה צריכות כוונה. נכ’ כאן קצת צדדים. אפשר שצריך כן כדי להחשיב את התוצאות של טובת מצווה. ותחשב. גם יש לומר שצריך כן כדי לעשות לו שם של מצווה, והוא שנעשה לו שם זה מפני שהוא חושב עליו לכך. גם יש לומר שחלק ממה שרצה ה’ הוא שיהיה אדם חושב על המצוות כדי לקיים אותם, שאז מכיר שעושה אותו לה’. ותחשב על זה.
** האלה -
יש לדון מהיכי תיתי שמוציא מה שלאחריו, ולא מה שלפניו. אולי מסתבר שמה שלפניו צריך כוונה יותר ממה שלאחריו, שהוא עיקרי האמונה.
יג:
** כי היכי -
משמע שמצווה ללמד את בנו הוא בעיקר הכשר מצווה, כדי שיוכל בנו ללמוד לאחר זמן. היה אפשר לומר שגמרא או קרא רק אומר שיעור כאן, והוא שצריך לשנות לבן עד שהוא יכול לדבר בם וללמוד בפני עצמו. ותו"ת.
** צריכה כוונה -
חושב אני שבשיחתא דשי הוכחנו שירושלמי סובר שדיונים אלו של כוונה הם על כוונה לצאת, ולא על כוונה לפירוש המילים. עיין שם.
** דרו עבדיה -
יש להעיר שבדרך כלל, היו לת"ח שמשים, ולא עבדים. מצאנו עבד אחר שהוא מפורסם, והוא טבי עבדו של רבן גמליאל. נראה שרק העשירים או החשובים היו להם עבדים. רבן גמליאל היה נשיא, ור"נ היה חתן של נשיא (או ריש גלותא).
** אמר ליה ר"י -
לכאורה, זה ר"י אחר מן הסתם, או רבא אחר מן הסתם, שהרי רב יוסף היה רבו של רבא ואביי, שהיה חברו של רבה.
** דבעל בשר -
כמו שמאריך בבבא מציעא.
** חסורי מחסרא… ואין צריך לומר -
לכאורה, הלשון משמע שאין זה דבר שווה לזו אין צריך לומר זו קתני, שהרי אומר מילים אחרים. ויש לדון.
אם נאמר שהוא חלוק, אז יש לדון מהו החילוק:
1. אולי החילוק הוא שחסורי מחסרא אומר שגמרא משנה גירסא שבמשנה, ואומר שהיה המשנה אומר מילים אלו.
2. אולי זו ואצ"ל זו אמר שראשון שמע זה, ואמרו, ואחר כך אמר זה, שהיה מחודשד יותר, והשאיר את הראשון. כאן, אומר שתנא ידע שניהם. יש לדון למה נתרץ גמ’ זה כאן וזה כאן. לראשון, יש לומר שהיה קצת ידוע להיות גירסא כזה. אבל, לשני, צריך ביאור. ותחשב.
יד.
** ופגע בו -
אין צריך זה, שלכאורה זה כבר נאמר ב"מפני הכבוד…,” וכדומה. ותחשב.
** פרסומי ניסא -
לכאורה, לא צריך שהוא עדיף, אלא שהוא פירכא. נראה שר"ל שכך: פירסום הנס הוא הסיבה למצוות קריאת מגילה, לכאורה. יש מצווה וס"ט אף לקריאת שמע, כמו שיש לכל מצווה. מה שיש לזה סיבה חלוקה מזה לא עושה פירכא, שאם כן בטלת כל קל וחומר[fn:19]. אז, כדי לפרוך, צריך שסיבה של מצוה זה עדיף, ויותר גדול. ותו"ת.
** גומר בהם -
יש לדון אם מה שלא גומר את ההלל הוא סימן או סיבה.
** פוסק ואין בכך כלום -
לכאורה, שאל לו אם יש לו דינים של קריאת שמע או אם הוא יותר חמור. לא שאל לו אם הוא יותר קל או לא. יש לדון מהו התשובה:
1. מותר להקל כדיני ק"ש. אסור להקל יותר מכאן.
2. מותר להקל כדיני ק"ש. אף מותר להקל יותר מכאן, אבל רק ענה על השאלה.
3. מותר להקל בכל.
לכאורה, קאי על ימים שאדם גומר את ההלל, שבלי זה, אין פירסום הנס. אז, אולי ייצא שחולק על שיטה שיבוא.
** ימים שהיחיד -
לכאורה, ר"ל ימים שהם מדאורייתא. כיון שהם מדאורייתא, גדר שלהם שווה לשל דין קריאת שמע. קשה, שבכלל עשרים ואחד יום (כמו שמזכיר כאן רש"י) הוא ימים שיש בו הלל מחמת פירסום הנס. אם כן, צריך לומר שבתוך מאמרו יש שני חידושים, והוא שדרבנן מח’ פה"נ הוא ג"כ כדין דאורייתא.
** ולא פסיק -
ואם תאמר הרי על כל פנים יהיה ככל אדם. ויש לומר שצריך לומר שהדין שאומר שיכול לסוק אף באמצע הוא רק לכבוד, ולא לכל אדם. גם יש לומר שלא צריך אדם לשאול בשלום מי שאינו מכובד (אלא אם כן רגיל הוא להקדים לו שלום, כמו שאמר גמרא לעיל). אז, משיב גמרא שמה שלא שאל לו אינו מפני שלא יכול, אלא מפני שלא רצה, ולא היה חייב. ותחשב.
** הנאה קבל -
לצד זה, יהיה אסור להנות כלל מן המאכל. אם כן, יהיו עוד נפק"מ. יל"ד, שאולי אסר כל הנאות שבאים במעשה אכילה. ותחשב.
** במה -
אם כן, חוץ מחידוש של משנה שיכולים להפסיק, לפעמים, יש עוד חידוש שיכולים לשאול כלל, כיון שלא התפלל. והיה אפשר לדחות שלא יכול, ומשנה דן במי שכבר התפלל, ולא סמך גאולה לתפלה, או שקאי על תפלת ערבית. ותחשב.
שוב ראיתי במה שיאמר גמרא. קיל"ד ל"ל אמר כמש"כ.
** בר אישאן -
יש לדון אם זה תנא דבי ר"א דלעיל.
** הכי אמר ר"ח -
לכאורה, אל אביו, ומזכירו סתם.
** דאמר -
מוזר שמזכיר במה. נראה שהוא מפני שר"י אומר שני דברים במשנה.
** פגעו -
יש לדון מהו החילוק. אולי אם פגע בו, אין כל כך כבוד במה ששואל בשלומו. אז, אינו אסור. גם יש לומר שאז יאבד אם לא ישאל, שיצטרך ללכת לו. אבל אם בין כך ובין כך הולך, לא יפסיד. נראה שיש קצת נפק"מ, והוא אם הוא לפני תפלה יותר קרוב לבית של זה, ואז קל יותר לשאול עכשיו. ותחשב.[fn:20]
יד:
** חוזר ואומר אמת -
יש לדון אם זה כשמפסיק או כשלא מפסיק. לכאורה, אינו כשמפסיק בין אמת לויציב, שלא היינו דנים בזה כלל. ותחשב.
** וכיון דאתחלינן -
קשה, שאולי בני מערבא התחילו רק מפני שסברו שלא צריכים לגמור אותו. ויש לומר שאין רע בגמירתו, אלא רק אומר שאין חיוב לגמרו. ותחשב. עדיין יש לדון, שאולי רק סברו שיש חיוב בהתחלתו כך מפני שאין זה מחייב אותו לגמרו. ויש לדון..
** דהא אמר -
יש לדון למה בזה פוסק כבני מערבא, ובזה כר"כ.
** שנים -
קשה, לכאורה, לראשונים שאומרים שעוסק במצווה פטור מן המצווה, אף אם אפשר לקיים שניהם. אף אם אי אפשר, מעניין שכאן לא פטור, שהרי כאן אי אפשר לקיים שניהם, אלא אפשר לשניהם להיות מקויים. ותחשב.
** שליחא -
ואם תאמר אם כן מאי קמ"ל. ויש לומר שקמ"ל שיש לקרוא אף בלי תפילין, אם בלי זה יפסיד זמנו. יש לדון מהו ההוה אמינא שלא יעשה כן:
1. אולי אין לעשות כן כיון שהוא כמעיד עדות שקר, ואז טוב שלא לעשות כן מלעשות כן, שאף שאולי מקיים כלום.[fn:21]
2. אפשר שהוה אמינא שאין מקיים כלום, ואין צורך לעשות אותו.
3. אפשר שמקיים יותר אם קורא לאחר זמנו. טוב לשהות עד לאחר זמנו לקרוא עם תפילין. ואם תאמר ל"ל יקרא שני הפעמים. ויש לומר שכיון שכבר יצא, אי אפשר לצאת עוד.[fn:22]
יש לדון אם המסקנא הוא שזה יותר טוב, שיכול לקיים שני פעמים[fn:23], או שלא ידע אם השליח יבוא כלל, ואז נקט וודאי ולא שהה למה שאולי לא יבוא (ואז יצטרך להיות לאחר זמן בלי תפילין). ותחשב.
טו.
** את מזבחך ה’ -
לכאורה, לא רואים מזה אלא שהוא כסובב מזבח. יש לדון מה זה, ואיך מפרשים את זה להיות שנים אלו. אולי רק ר"ל שעשה דבר עם מזבח; אם כן, צריך ביאור איך יודעים שניהם.
** בעידן צלותא -
כיון שקאי על מהדר אחר מים לקריאת שמע, צריך ביאור מה שייך זמן תפלה. אז, היה יותר נראה לשנות שאומר זמן ק"ש (או לומר כב"ח).
נראה שאפשר לומר כך. אפשר להיות שני טעמים ל"ל יחפש למים:
1. אולי הוא טורח לו. לשון גמרא שלייט עליו קשה.
2. חוששים שמא לא יקרא בזמנו, שיאחר.
נראה שמחדש שאף שהוא בעידן צלותא, שלא התפלל כבר, אלא הוא נוטל ידים בין כך ובין כך. אז, אין סיבה ראשונה שייך. אומר גמרא שאף בלי זה היה לייט עליו. ותו"ת.
** מיל הוא דאינו -
לכאורה, פחות ממיל מטריח מאד יותר ממיל, כיון שאף צריך לחזור. ותחשב. אולי כיון שיכול לשהות בינתיים אינו כן. ותחשב.
** ולא השמיע -
יש לדון אם זה דין בקריאה או בשמיעה. (זה אומר שיש שני דברים כאן- קריאה ושמיעה. יש לדון אם צריך רק קריאה, ושמיעה (או יכולת להישמע) מהני לקריאה, או שצריך שמיעה, ומה שבא מקריאתו מהני שמיעה (זהו מה שצריך לשמוע), או שצריך שניהם.) ותו"ת.
** כוחו של רבי יוסי -
קשה ל"ל אומר כוחו של רבי יהודה כיון שכוח של היתר עדיף. ותחשב על זה. ושוב ראיתי תוס’.
** דיעבד -
אם רבי יהודה סובר שצריך להשמיע לאזניו לכתחילה, קצת צריך ביאור מה יהיה המקור. לכאורה, יש מקור לומר שמעכב, כמו שמבאר גמרא בר"י, ויש מקור, אז, לומר שהוא לכתחילה בדרבנן, והוא שתקנו רבנן כעין דאורייתא (שבדבר שצריך לומר דאורייתא אף צריך לשמוע). אם לרבי יהודה לכתחילה ישמע, צריך ביאור מה יהיה המקור לזה. אולי דורש את קרא של רבי יוסי, אבל רק דורש אותו לדין לכתחילה. זה מעניין, שבדרך כלל, שלא בענין קרבנות, לא צריכים כפלות קרא לעכב. שו"ר שתוס’ קצת מרמז לקושיה כזה  בד"ה להודיעך, אבל לא מפרש.
נראה שאפשר שדורש "על לבבך" ודורש "שמע" לומר שצריך לשמוע לכתחילה, אבל לא מעכב. ותו"ת.
** תורם לכתחילה -
היה אפשר לחלק, לכאורה, בין דין דרבנן לדין דאורייתא. ותחשב. ונראה שאין הכי נמי, וגמרא מנסה להוכיח שאי אפשר לנו להביא ראיה מדין ברכת המזון שרבי יהודה פוסל לכתחילה, שאם כן, צריך לומר שמניחים שאין בין לכתחילה גבי דאורייתא וגבי דרבנן, והרי אם כן, יש לנו ברייתא שלא יכולים לתרץ. ותו"ת.
טו:
** מכלל דרישא -
ק"ק, שלכאורה, משמע, להיפך, שרק על קטן חולק רבי יהודה. אם כן, משמע שמודה לשאר המשנה. וצריך ביאור.
** מכאן תשובה -
הוא ממה שקרא סומכם לומר שמה רחם מכניס ומוציא…, ולא ממה שעושה קל וחומר לומר שמוציא בקולי קולות. ותו"ת.
** בטלים ממלאכתם -
ואם תאמר עדיין למה חלוק משמ"ע. וי"ל שצ’ ליותר זמן, או סוג אחר של כוונה. ותחשב.
טז:
** ובמקום -
נמצא שהיו שלש ידיעות שצ’ לדעת כדי להבין מה שעשה ר"ג:
1. אנינות לילה דרבנן.
2. לא גזרו רבנן על איסטניס.
3. היה ר"ג איסטניס.
יש לדון מה לא ידעו תלמידיו. לכאורה, אם נאמר כ3, טוב, שאז נמצא שלא טעו בדין. עדיין קשה ל"ל דנו אותו לכף זכות. אולי דנו אותו, אבל לא ידעו אם יש היתר אחר, ואז שאלו. ותחשב.
** דלא ידעינן
[
- משמע שתלוי במה שלא יודעים, ולא במה שאין כולנו באים מאחד. אם כן, אין זה נוגע לכהן ולוי. ותחשב.]
** ותרבה גבולינו -
לשון זה בא מתפילת עתניאל בן קנז (תמורה טז.).
** אין קוראים אבות -
יש לדון איך לקרוא זה. אפשר שהוא לשון רבים, ואומר ששלש אלו הם האבות, ולא השאר. לא נראה כן, שמה שהיה אחר נקרא הוא אב, ולא אבות. אז, יש לומר שהוא מפני שהאחרים היו אבות, והוא שהאחרים שהיו נקראים כן הם רבים, ועליהם יכולים לומר אבות. גם יש לומר שיש שורוק בוי"ו, והוא שם דבר (כעין עבדות), ואין קוראים של של אבות לאחד. עדיין יש לדון ל"ל אמר שאין קוראים שם אב. ויש לדון אם זה יותר טוב. ותחשב.
יז.
** איני כדאי -
צריך ביאור מה אומר, שהרי לא היה נברא כבר, ואז פשוט שלא היה כדאי. ואולי אין הכי נמי, פשוט הוא, אלא היה כופל אותו לעצמו. גם יש לומר שמה שהיה אחרי שנוצר לא עשה שהיה כדאי להינצר עד שלא היה נצור. אין הלשון משמע כן כל כך. גם יש לומר שנצירה לא ר"ל נצירת נשמה, אלא נצירת גוף. אם כן, היה בעולם קודם שנוצר. גי"ל  שהיה אפשר להיות כדאי להיות נצור, לא מחמת עצמו, אלא מחמת אחר (שאחר היה זכאי שזה יהיה נברא). ותחשב.
** כאילו לא נוצרתי -
יש לדון אם ר"ל שהוא עדיין לא חשוב כמו שלא היה חשוב קודם שלא נברא, או ר"ל שעדיין לא ראוי להיות נוצר. אם נאמר כדרך שני, יהיה קשה על צד אחד שכתבנו לעיל, וצריך לומר שהחידוש הוא שאף שכבר נוצר, לא ראוי להיות נשאר באותו מצב. ותו"ת.
** ואפילו נכרי
[
- לא ר"ל שהקדים לכל אדם, אלא ר"ל למי שחשב שיקדם לו שלום היה מקדים. אז, לא הקדימו אדם מעולם.
** בשוק -
ענין בשוק קצת צריך ביאור. ויש לומר שר"ל שאף שיש קצת בזיון לגלות שאוהב גוי, עשה כן. ותחשב.]
** ובמצותיך -
לשון זה מעניין, שלכאורה, לא רודפים בדבר, אלא רודפים את דבר. ותחשב. ואולי תרדף לא ר"ל שנפשי תרדף, אלא ה’ ירדוף נפשי, ואומר בלשון שני (ר"ל אתה) שתרדף נפשי במצוות, שתביא אותם לידי. דחוק, שהיה לו לומר את נפשי. גם, אז, לשון נפש שנקט הוא קצת מוזר.
** חלבו -
משמע שהחלב מתכפר, אף שלא מעכב. גם מעניין שלא מזכיר בשר, שהרי מקראי משמע שיש קצת כפרה באכילת הבשר.
יז:
** אין פרץ -
צריך ביאור למה מזכיר של דוד ראשון, שלא היה קודם. לכאורה, מה שגמרא מניח אותו קודם ה וא שלשון "פרץ" משמע דוד שהיה מבני פרץ. אבל, צריך ביאור למה היו מזכירים אותו קודם.[fn:24]
אפשר שאחיתופל יותר רע לחבורה מדואג, שדואג היה מנסה לעשות לטובת חבורה, אלא שהיה חוטא ועושה רע לאחרים, וממילא היה רע לחבורה, אבל אחיתופל כוון לעשות רע לחבורה של דוד ותחשב.
ויש לדון, שזה מניח שהיו מברכים את הסיעה שיהיה סיעה וחבורה טובה בהיותם חבורה, ולא שברך שכל אחד יהיה צדיק. ותו"ת.
והיה אפשר לומר שהזכירו ראשון מי שהוא יותר קרוב להם בזמן, והרי אחיתופל חי אחרון, ואז הוזכר ראשון. אי אפשר, שהרי מזכיר גחזי אחרון. ותו"ת.
** מערב שבת -
ק"ק, שמשמע שלא קיים מצוות שבת, שלא אכל סעודות לחם, ולא אכל שום דבר לכבוד שבת. אולי היה ממש אנוס. גי"ל שהיה די לו בכך, אבל אכל יותר לכבוד שבת. דחוק.
** לא תחליף -
עיין ברש"י עירובין צט (וכ’ כעין זה, אני חושב, בכ"מ). לכאורה, מגמרא זה משמע שאומר להחליף, שהרי גמרא משיב לו שלא להחליף. אפשר שכן כוונת רש"י, והוא שהחליף רבי יהודה שיטתו אם נאמר כן, ומסתמא לא החליף, ואז צריכים לשנות הגירסא. ותו"ת.
** אמרי אינשי -
נמצא שיש שני דברים ששייכים:
1. אם מכירים בני אדם שמה שעושה הוא חלוק משאר בני אדם.
2. אם מכירים שהחילוק הוא כדי לעשות מצווה.
אם יש שניהם (מכירים, ומכירים שהוא מחמת מצווה), אז יש יוהרא. בקריאת שמע, בדרך כלל, אין ראשון. במלאכה, בדרך כלל אין שני. אז, אם אין כל כך ראשון, רשב"ג מחמיר ורבנן מקילים. אם אין כל כך שני, רשב"ג מיקל ורבנן מחמירים. עדיין צריך לבאר למה יחלקו כך. ותחשב.
** שלא תהא סיעתינו
[
- צריך ביאור למה צריך לומר שלש דברים אלו.
** כמה בטלני -
ק"ק למה צריך שניהם. עיין בפסחים שמבאר שחד הוא. לכאורה, מה שיש כמה בטלנים הוא סיבה שיכולים בני אדם להניח שמלאכה אין לו, שבלי זה, היה קשה להניח כן. ותו"ת.]
יח.
** לפניו -
יש לדון למה מניח גמרא שיצטרך להיות בפניו, ומה יהיה הסברה לזה. כמו כן יש להקשות לרב פפא למסקנא. אולי יותר טרוד עליו אם הוא בפניו. ותחשב. גם יש לומר שלא סובר שסיבה של דין של משנה שלנו הוא מחמת פטור טירדא, אלא מחמת לועג לרש. אז, הוא רק אם הוא בפניו. עדיין צריך ביאור למה יהיה, אז, רק במתו. ויש לומר שאין הכי נמי, בצד זה לא הניח כבר שמתו דווקא. דחוק, אבל לכאורה כן מוכרח, שאי לאו הכי, צריך ביאור איך יתרץ אותו קושיה, שאי אפשר לומר כמש"א גמרא, שהרי כאן אי אפשר לחלק בין שומר למה שעושה כאן במשנה, שהרי אף במשנה צריך להיות בפניו ממש. ויש לדון, שאולי משנה הוא כשהוא בפניו, ואף אם לא שומר אותו. ויש לדון, שלכאורה ממילא יישמר. ותחשב.
** ואקברה
[
- צריך ביאור למה צריך שני קראי.]
** משמר -
ואם תאמר הרי זה פשוט, שהרי הוא עוסק במצווה. אם כן, לא צריך להביא ברייתא להקשות ממנו. ויש לומר שאין הכי נמי, אלא שהקשה מברייתא שאומר כן בפירוש. ותחשב. יותר נראה לתרץ על פי מש"כ ראשונים שלא לעולם עוסק במצווה פטור מן המצווה, שצריך להיות עסוק במצווה (למקצת ראשונים) או שלא יוכל לקיים מצווה אחרת (לראשונים אחרים). חידוש הוא שהוא כן כאן. יש לדון, שחידוש הוא לראשון, בוודאי, לומר שזה נחשב עסק. לשני, צריך ביאור, שלכאורה כל אחד יכול להשאר אם יכול לעשות מצווה אחרת או לא. ויש לדון.
יח:
** המת מעיקרא -
היה אפשר לומר שהוא מפני שהוא עומד למות. ויש לדון, שכיון שמהפכים בזכותו, אולי לא עומד.
** בני ר"ח -
עיין בגליון שמביא מרש"י בע"ז. יש להעיר שגמ’ שם בע"ז מוכרח שהיה חזקיה בנו. בכמה מקומות אחרים רואים שהיו בניו יהודה וחזקיה. ותו"ת.
** ולא ידע -
קשה, שאם ידע, למה ישאל. וצ"ל שדיבור ראשון נאמר בנחת, ולא היה שאלה.
** בואי ונשוט -
צריך ביאור למה חשבה שעכשיו תרצה. אולי אחר ששמעה ששמעה חברתה דבר כל כך טוב כזה, אף היא תרצה. ויש לדון למה תרצה ללכת, ולא רק לשמוע מחברתה.
** כל הזורע -
קצת צריך ביאור למה רצו לדעת דברים כעין זה. אולי חשבו שישמעו דברים שיותר נוגעים להם. ויש לדון מה נוגע להם.
** שכיב -
עדיין יש ראיה ששומעים מקצת דברים מן הפרגוד. נראה שזה רק גזירות, אבל לא מאורעות.
** דלמא דומא -
יש לדון ל"ל אמר שאולי שמע מאחורי הפרגוד, שלכאורה זה גזרה מאת ה’.
** דלעגל -
קשה, שלא היה ידוע כבר למטה, ואז צריך לומר שהכריזו. ויש לדון, שלכאורה, כבר היה סיבה לו למטה (לא מוכרח כן, שאולי לא מת מחולי, אלא אחר הורגו או כדומה), וידע בו קודם שאר בני אדם. גם יש לומר שכבר היה ידוע למטה, אבל לא משמע כן, שאם כן, כבר ידע שמואל כן, והיה לו לדעת שלכן בכה אביו.
** חשיבי -
אז, מסתבר מה שמזכיר שני הדברים ביחד, שהכירו בשניהם ביחד, שממה שהכריזו על מיתתו ידע שניהם.
** חשיבי -
היה אפשר לומר שהיה דומא מכריז. אולי מסתבר לגמרא שזה רק יום אחד קודם או כדומה, אבל כאן חי לזמן. שנים אלו הם הנחות שצריכים מקור. ותחשב. שוב הבנתי שלכן מבאר רש"י שהראיה הוא ממה שהוא חשוב. ותחשב.
יט.
** לאחזוקי -
משמע שצריכים להחזיק טובה למי שעושה טובה, אף שלא שינה שום דבר, שהרי כבר ידעו לפני כן כמו שידעו לאחר כן. אפשר שלא צריך, אלא מסתמא צדיקים כאלו יחזיקו טובה. עדיין, נראה שהוא חידוש שיש ענין בזה.
** שאני -
לשון זה משמע שהם יודעים והם מקפידים, שאי לאו זה, לא היה לומר שהוא שאני, אלא היה לו לומר שלא בא זה מחמת שהקפיד, אלא מחמת שהיה פגם בכבוד תורה ותלמיד חכם. אז, קשה מהו תירוץ של גמרא. אולי עשה ה’ שידע כדי שיענש ת"ח אותו. ויש לדון למה אין ה’ מעניש אותו. אולי אין בזה די לענשו, אבל יש בו קצת רע. ותחשב. כשת"ח שומע ומקפיד, יש רע די. ותחשב.
** עד דמהדר -
יש לדון מהו "הני מילי.” הפשטות יהיה לומר שקאי על מה שמניחים שעשה תשובה. קשה, שגם נניח שהחזיר אותו. ויש לומר שאז מצוי לומר שלא שב, שקל לדעת אם החזיר אותו או לא. גם אפשר שהני מילי קאי על מה שמשמע שאחר תשובה, אין רע (שמחמת זה, אין לטעון אחריו). ותחשב.
** פסוק אחד -
יש לדון מהו הדיון:
1. אם יש טוב בעשיית קצת מצווה. ויש לדון אם זה שווה בכל המצוות. אפשר שיודעים סיבות למצוות, לפעמים, ויודעים בהם, אז, שמסתבר שה’ רוצה לקיים כל מה שיכולים. ק"ש הוא לקבוע דברים בלבנו, ומסתמא יש ענין לקבוע מקצת הענינים. ותחשב.
2. מה צריכים לקרוא. ק"ק, שכבר חלקו בזה, ויש לומר שברייתא ומשנה חולקים בזה. (ואם תאמר אם כן, בין כך ובין כך קשה, שנאמר שבזה חולקים. ויש לומר שלולי צד זה, יש לומר שלא משמע הלשון כן, שכיון שאומר, “אפילו…,” משמע שאין זה כקריאת שמע שרגילים לקרוא.
** כ. פנימה -
לכאורה, הענין הוא שאז מסתמא האבל רואה אותם, ואז מתסמא בא לו נחמה. אז, הם מקיימים מצווה. אם כן, היה לו לומר "נראה,” שזהו הענין. צריך לומר שלא יכולים העומדים לדעת אם הם נראים, כי אם אם הם רואים, ולכן בזה תולה התנא. ויש לדון, שיכול להיות נפק"מ, ובאופן שיכולים לעשות חשבון, כמו אם מכירים שיש דבר בין ראשם ולא, אבל לא בין שאר גופם לו. ותחשב.
** צריך ביאור בשיטת
רבי יהודה. יש לדון אם הוא סימן או סיבה. אם הוא סיבה, אז, לכאורה הוא שמסתמא אם בא לנחם, מנחם, ואם לא בא לנחם, לא מנחם. אם הוא סיבה, אז לכאורה, הוא שצריך מצווה לשמה (עיין לקמן). גם יש לומר שחלק מהנחמה הוא ממה שבאו אלו למצווה, לכבד מת או לעזור לו.
כל זה קצת תלוי על איזה כוונה צריך, אם הוא לקיים מצווה או להנות לאבל. לשון גמרא קצת משמע כצד שני, אבל יש לדון. יש להעיר שאם נאמר שסיבת המצווה הוא לכבוד המת, ולא לאבל, או שבזה מנחם, אז לא יהיה אפשר לומר מקצת מן הצדדים שכתבנו לעיל. גם יש להעיר שאפשר שאין הגמרא אומר שהוא לשם אָבֵל, אלא אֵבֶל. אז, אולי בא על מת. ותחשב.
** אין חולקים כבוד לרב -
מלשונו, משמע שהחידוש הוא שאף תלמיד חכם צריך לעשות כן. אם כן, ק"ק ל"ל אמר כן בתוך מאמר שלו (היה לו לומר, “תלמיד חכם שמצא…"). אולי הוה אמינא שת"ח בלחוד צריך להוציא אותו. וצריך ביאור למה. אולי חוששים שאחר יכיר שת"ח לובש כלאים, ואז יחשוב שמותר ללבוש כלאים. דחוק.
** אבל -
לכאורה, מימרא שאמר רב היה רק שאין כבוד תלמוד חכם דוחה איסור שבתורה. אולי כבוד של אבלות (אולי הוא כבוד אבל ואולי הוא כבוד מת) אינו ככבוד תלמיד חכם, ואולי הוא דוחה. צריך ביאור. אולי מסתבר לגמרא שכבוד תלמיד חכם הוא יותר גדול. ותחשב.
** כב. מקבלים טומאה -
יש להעיר שזה לשון מוזר, שלכאורה, היה נראה לומר שאילו היה אסור, אינו מפני שמטמא את התורה, אלא שהוא עושה דבר של קדושה כשהוא טמא. כמו כן, פשוט שאין אדם מטמא בית המקדש כשנכנס בו טמא. אבל, עדיין אסור. אולי צריך לומר ששם מטמא אותו, והוא שלא מטמא אותו די להיות איסור להשתמש בו וכדו’, אבל יש לו קצת טומאה. ותו"ת.
** כאש -
להיפך, אש מטהר, כמו שאומר גמ’ שה’ טבל באש כשקבר את משה.
** כו. מלוא עיניו -
יל"ד אם הוא מלוא עיניו ממש או השיעור שבדרך כלל יכול לראות. לכאו’, הראשון נכון, שלכאו’, יכול לראות לעולם אם אין מפסיק. ויל"ד, שאולי הוא השיעור שבדר"כ דבר מפסיק. גם נראה שלא יכול לראות לעולם דברים שבעולם, שהעולם הוא עגול. ויל"ד, שעדיין רואה שמים. יותר נ’ שאחר הרחק גדול, מה שרואה לא רואה טוב, שהוא קטן, ושיעור ראיה הוא עד שיראה עדיין קצת גדול.
עיין במה שכתבנו גבי מתפלל וראה שור. ותו"ת.
** כו: תפלת מוספים -
היה קל לדחות שאותו תפלה תקנו אותו רבנן. אז, היה אפשר לומר שהיה תפלה אחת שתקנו רבנן, ותקנו אותו על פי קרבן, והיו שלש תפלות שתקנו אבות, והם תקנו לשום זמן שרצו.
נראה שרק מכוון להביא ראיה ליחס בין קרבנות לתפלה. זה אומר שבין כך ובין כך מוכרח לשיטה זה שמתקנים תפלות על פי קרבן. כיון שכן, לא קשה לומר שאף תקנו רבנן זמן תפלות על פי קרבנות. ותחשב.
** יש להעיר
שכיון שתקנו תפלת מוסף על פי קרבנות, היו מתקנים, לכאורה, שאר תפלות על פי קרבנות. אם כן, כשריב”ח אומר שתקנו על פי אבות, צריך לומר שרק ר"ל שזה גרם התקנה, ואף שאף בלי זה, לא היה תקנה. ויש לדון, שאולי קרבנות נתקנו (או נתקנו באותם זמנים) רק מחמת זה. גם יש לומר שהיו רבנן מתקנים רק תפלה אחת כנגד קרבנות. זה אומר אולי שטורח שנתרבה מארבע תפלות יותר מן הרווח שנתרבה. אולי זה מפני שטורח נתגדל מכפי ארבעתים. גם יכול להיות שיש קצת מן טובת התפלות שהם אחד. אז, אין טובת התפלה ארבעתים. ותחשב.
** צריך ביאור
למה מקשה לפי ריב”ח, ולא מקשה על ריב”ל. יש לתרץ על פי תירוץ קושייה אחרת, והוא שקשה למה הקשה כלל, שכבר הוא מחלקת תנאים. אז, איך מקשה מברייתא. נראה שהתשוב הוה שלא מקשה אלא מפני שיודע שיש תירוץ ובא לבאר שיכול ריב”ח לסבור כשני הברייתות. אבל, לריב”ל אי אפשר (ידע גמרא ש”כנגד קרבנות תקנום” לא ר"ל שרק תקנו הזמן מחמת זה), ולכן לא דן גמרא מה יתרץ. גם יש לומר שהיה דן בשיטת ריב”ל, אבל הכיר שאף הוא יאמר כעין זה לתרץ לשיטתו. אז, נמצא שלא חולקים, כמו ששני הברייתות לא חולקים. אז, נמצא שלמסקנא אין מחלקת בגמרא זה. גם יש לומר שלריב”ל אין משנה ראשונה כל כך קשה, שיש לומר שרק אומר לנו שתקן כן לבני ביתו, אבל לא לכל ישראל (או שתקן אותו לכל ישראל, אבל אין אנו מצווים, כיון שעברנו את הר סיני, ונעשו גרים). ותחשב. אם כן, רק קשה על ריב”ח. נראה שזה גם יבאר, אולי, ל"ל רק תירץ שתנאי הוא, שלא היה לנו לעשות תנאי על פי ברייתא ראשון, שרק משמע כריב”ח, אבל בוודאי לא מוכרח כמותו. ותו"ת.
** עד ארבע שעות -
לשון זה מעניין, שלכאורה, אילו היה אומר עד שעה רביעי, אז היה אומר עד סוף אותו שעה, או עד תחלת אותו שעה. אבל, כיון שאומר עד ארבע שעות, לכאורה, ר"ל שכשר לארבע שעות. אז, לשון “עד” מוזר. ותחשב. לכאורה, צריך לומר שר"ל עד שעברו ארבע שעות. אם כן, שאלת גמרא, אם הוא עד ועד בכלל או עד ולא עד בכלל, מוזר, שיש רק דרך אחד לפרש (ואין לומר שדן אם יכול לומר אותו בתוך הארבע, שפשוט שאפשר לומר אותו בתוך הארבע, שאי לא יתפלל אז, מתי יתפלל). אולי דן אם שלש שעות וקצת מן הרביעי נחשב ארבע שעות, ואם אומרים שזה היה כוונת תנא שכשר עד שנגמר ארבע שעות. דחוק. אם כן, זה חלוק משאר “עד ולא עד בכלל”ים שבש”ס.
ועיין בתוס’ ד”ה איבעיא להו. נראה שעל פי מש”כ אולי יכולים לתרץ קושייתו, שיש לומר שזה רק דן גבי עד ולא עד בכלל, ולא לגבי דיון זה. נראה שאולי אין הכרח שתוס’ לא אומר כמה שבארנו, שאולי תוס’ רק סובר שגמרא שם הוא לענין כל דיון שיכולים לדון על שיעור, ולא רק על “עד ולא עד בכלל.” ותחשב.
יש להעיר שלפי מה שבארנו, מוזר שמביא ראיה מסיפא של משנה, ששם הדיון הוא בעד ועד בכלל, והוא חלוק מכאן. אז, צריך לומר שהם עדיין דומים. ותחשב על זה.
כז.
** ותנן בבחירתא -
יש לדון אם זה הענין הוא מה שתנן בעדיות או שזה סימן. זה אומר שאפשר שהענין הוא שהלכה כמותו כיון שהעיד כן ריב”ב. מה שאומר שהוא בעדיות הוא שעדיות הוא, כמו שמשמע משמו, עדיות מתנאים. הצד האחר הוא שמה שתנן בעדיות הוא גופא הסימן שהלכה כמותו, שמה שנתן אותו שם רבי הראה שהלכה כמותו. יש לדון למה יעשה כן. אולי הלכה כרוב דברים שבעדיות. יש לדון בזה. ותחשב.
גם יש לומר שאין מה שהוא עדיות בפני עצמו ראיה, אלא שידוע שהלכה כאותם משניות. כיון שהוא שם, צריך לומר שהלכה כמותו. לא משמע כל כך מן הגמרא, שאז רק הביא חצי ההכרח, ואין חצי האחר דבר שיכולים אדם לדעת רק מסברה (ויש לדחות, שאולי כיון שלשון בחירתא משמע כן, כמו שאומר רש"י, הרי אומר כן גמרא, שאומר שהוא במסכתא שהלכה כמותו בכל מקום), אבל מרש"י נראה כצד זה. ותחשב. (אפשר לדחות שכשרשי אומר, “אותם עדיות” לא בא למעט שאר עדות, לומר שאין הלכה לעולם כעדות, אלא שכאן יודעים שהלכה כמותו, אלא שכוונתו לומר שאין כל עדות טוב, שלא דקדקו לעולם אחריו, אבל מסתמא באותו יום, שהיו שם הרבה ת”ח, עסקו ודקדקו בה. אם כן, כמעט אומר כצד ראשון. ותחשב.
** ממאנים -
נראה שיש כמה חידושים בזה:
1. מיאון שלה מתיר ייבום. עיין בגמרא יבמות, שמפרש את זה.
2. מיאון שעשו בית דין שתמאן נחשב מיאון.
3. יותר טוב שתמאן, אף שעושים כל הביאות כאילו הם ביאות זנות.
4. בית דין צריכים למאן.
ויש לדון על איזה מן החידושים האלו חלק החולק.
** על יין בן -
יש לדון אם חידש פסול קודם לכן, או חדש כשרות אז. לשונו משמע שחדש כשרות.
** וחם השמש -
לכאורה, הביאור הוא כך: בהוה אמינא, היינו אומרים ש"וחם השמש" אומר שהשמש מחמם את כל העולם. אז, הוא בשש שעות. כיון שמצאנו לשון חלוק בשש שעות, מוכיח גמרא שאינו כן. אז, צריך לומר שהלשון משמע שרק מקום השמש חם, ואז הוא ארבע שעות.
** ארבע שעות -
צריך ביאור למה פשוט לגמרא שהוא בשעה רביעית, ולא בסוף ארבע שעות.השני דרכים הוא:
1. מוכיח כן מן הלשון. זה אומר ש"שעה רביעי" משמע כן. כמו כן, יש לומר ש"שעה ששי" משמע שהוא תחילת אותו שעה (אולי בזה יש משמעות יתירה, ממה שלא אמר חצות), ושעה רביעי צריך להיות תחילת אותו שעה, דומיא דשעה ששי.
2. מוכיח כן מן המקרה. זה אומר שיודע גמרא מתי מקום חמה חם ומקום צל צונן, והוא בתחילת ארבע שעות. כמו כן, יש לומר שידע מתי הכל חם, והוא בתחילת שש שעות.
** בבקר -
נמצא, אז, שיש שני לימודים:
1. מה שלשון זה משמע הזמן ששמש חם וצל צונן.
2. מה שכופל בבקר בבקר.
יש לדון למה צריכים שניהם. אז, לכאורה, היה לו לגמרא לומר ששאני הכא שאומר ראשון, ולא לתרץ שני כלל. ותחשב.
ויש להעיר שלכאורה, כשאמר בהוה אמינא שהוא שש שעות, קשה, שהרי כתיב בבקר. אז, צריך לומר שהוא מפני משמעות הלשון. ויש לדון, שאולי בקר בא לגרע שעה לרבנן או להוסיף שעה לרבי יהודה. נראה שאולי לכן סבר בהוה אמינא שהוא שש שעות (אולי אין הלשון יותר משמע שש שעות מארבע שעות.)
** הכא מאי -
יש לדון למה מזכיר מה שבמקום אחר, יודעים שההלכה כר"י:
1. אולי מפרש ל"ל שואל שם. (ויש לדון למה צריך כך, שאף אילו היה שואל במקום אחר, עדיין היה לו לשאול שם. ויש לדון, שאולי רבו יניח שכמו ששואל כאן, אף כוונתו לשאול שם (ק"ק, שמלשונו יכולים להוכיח נגד זה), ואז ישיב לו יותר ממה שצריך. עדיין יש לדון למה צריך לבאר הסיבה.)
2. אולי מפרש הסיבה שנפסוק כרבי יהודה. זה אומר כך: באמת, שאלתו קשה, שפשוט להניח שהלכה כרבנן, כיון שהלכה כרבים. כל צד שלו לפסוק כרבי יהודה הוא שהלכה כמותו ברישא. אז, צריך לומר שיש תלייה בין שני הדינים. ויש לדון.
3. אולי סבר, להיפך, שידוע שהלכה כרבי יהודה ברישא. אילו לא הזכיר למה הלכה כן, היה אפשר לומר טעם שיהיה שווה בשני שיטות רבי יהודה (למשל, צריכים לגרוס במשנה שלנו, “דברי רבי מאיר"). אז, מבאר שהלכה שם הוא כרבי יהודה, אבל כאן, אין אותו סיבה קיים, ואז יש לשאול כמי ההלכה.
** אדרבא מדר"ה -
לכאורה, ר"ל שראינו שהיו רוצים להתפלל, אבל לא התפללו, שאי לאו הכי, אינו ראיה נגד רבי יהודה. ויש להעיר שמצאנו לפעמים שאמוראים ירצו לעשות כדברי רבם רק להראות דברי רבם (עיין בסוף פסחים). אם כן, יש לומר שהיה רב הונא עושה כן אי לאו שלא סובר כרב.
** של שבת בע"ש -
כמובן, צריך ביאור למה גמרא מניח שכיון שזמן מנחה הוא עד פלג המנחה שיכול להתפלל ערבית אז. ויש לומר שערבית, בעצם, יהיה בכל היום, שהוא כנגד הקרבת אימורים, וזה היה כל היום. מה שאינו בכל היום הוא אולי מפני שתפלה אז יהיה יותר מיוחס לשאר קרבן (שהוא חוב), או שלא הקריבו בדרך כלל אימורים עד הלילה, שהיו עוסקים בקרבנות עצמם (אבל לא נראה כן מגמרא בפסחים (“חביבה מצווה בשעתה")). אז, משעה שלא מביאים קרבנות עוד, שהוא סוף זמן מנחה, בכל זמן שהוא, לכאורה, מאז נעשה זמן ערבית. ותו"ת.
** אחוריה רביה -
מניח שכשאומר שלא פסק לצלותיה, הוא שרצה לפסוע שלש פסיעות אחר תפלתו, ולא פסע, כיון שאז היה מפסיק תפלת ר"י. יש לדון איך רואה כן בלשון, שאולי היה ר"י מתפלל במקום אחר, ורצה רב להלך לפניו ולא הלך. אבל, אולי לא היה אחורי של רב. נראה שאז לא היה בתוך עדות זה, שעדות זה הוא על מה שקרה באותו תפלה של רב. ויש לדון, שהיה אפשר לומר שהוא על מה שקרה באותו לילה, או בתפילות של כל הרבנים של אותו לילה.
כז:
** והאומר דבר שלא שמע -
אין כל כך ראיה מר"א, שלכאורה רוב תנאים חולקים על זה (שלא מצאנו מי שנוהג כן אלא ר"א, ולהיפך, גמרא מדגיש מה שלא אמר אלא מה ששמע מרבו). אז, היה אפשר לומר שכל משנתו הולך לשיטתו.[fn:25]
** והחולק על ישיבתו של רבו -
איני יודע מהו זה. אולי ר"ל שחולק על מסקנא שהעלה רבו בישיבתו. לא נראה כן, שהרי אף לא יאמר דבר שלא אמר רבו. אולי ר"ל שאומר שישיבה (בית מדרש) של רבו אינו טוב.
** נכנס להזיע -
אם כםם0ן, קשה מה מגיד לנו עדות זה. אולי מגיד לנו מתי נגזר. יש לדון מה לנו בזה. גם יש לומר שאולי מי שאמר כן סבר שכבר נגזר. דחוק.
** דלא מטרחינן -
הענין הוא שכדי להתפלל של מוצאי שבת, צריכים לכוון שהוא של מוצאי שבת (זה מעניין, שבזמן שלא היו מבדילים בתפלה, קשה מה עשו. ואולי אין הכי נמי, היו צריכים לשבות עד סוף היום ממש). מקשה שהרי לא כוונו.
ואם תאמר אם מחמת טעות לא חל הבדלתם, קשה מה לנו בטורח שלהם. ויש לומר שמחמת טורח קבלו. ר"ל, טעות לא עושה שאין קבלתם קבלה אלא אם כן לא היו מקבלים אילו נודע הטעות. כאן, אילו נודע הטעות (ועדיין באו להתפלל, שצריכים לעשות לדעת מה יהיה מחשבתם בשינוי זה בלחוד), היו מקבלים, כדי שלא להצטרך לטרוח. ויש לדון, שזה מניח שאין טורח של כל אחד מן ציבור שווה לטורח של אחד שמתפלל בפני עצמו. אולי זה נכון, אבל אילו היינו אומרים כפשטות הגמרא, הענין יהיה שבין הכל יש יותר טורח. אבל, זה אי אפשר בצד שכתבנו, שלמה שכתבנו, לכל אחד יהיה שייך רק טורח שלו. ותחשב.
גם אפשר לומר (וכן נראה מרש"י) שלא חל שום הבדלה, אלא חדשו חז"ל שתפלה כזה יהני, כדי שלא להטריח את הציבור.
** טעותא הואי -
יש לדון מה ר"ל:
1. חשב שהוא מאוחר ביום. אז, קבל שבת. לא היה מקבל שבת אילו ידע שהוא עדיין מוקדם ביום, ואז מאבד זמן רב של חול.
2. חשב שהוא כבר שבת. אז, לא כיוון לקבל שבת, שחשב שכבר בא. לא נראה כל כך כצד זה, שלכאורה יש מצוות תוספת שבת, ואז היה לו לקבל שבת לפני שבת, ומוזר לומר שלא קבל.
ועיין לעיל במה שכתבנו בד"ה דלא מטרחינן. לכאורה, מה שכתבנו שם לבאר הוא רק לפי צד ראשון כאן, שלשני, הרי לא קבלו, ואף אם אלא חשבו לקבל מחמת טעות, עדיין יש בעיה במה שלא קבלו. ותחשב.
** צלי של -
לכאורה, שני דברים נעשים כאן:
1. התפלל.
2. קבל שבת.
יש לדון ביחס בין שני הענינים. היה אפשר לומר שכיון שהתפלל, נעשה שבת. יש לדון למה, שהוא רק זמן ערבית, ואז התפלל ערבית. אולי צריך לקבל כדי להתפלל, שצריך להתפלל תפלת שבת. צריך ביאור למה צריך להתפלל תפלת שבת, שכיון שחול הוא, יתפלל תפלת חול. אולי שבת צריך ארבע תפלות. יש לדון למה. כמו כן, נהיה צריך לומר שחול צריך ארבע תפלות, שהרי צריך לקבל של מוצאי שבת (כמו שמצאנו גבי טועים). אם כן, כל זמן שמתפלל כרבי יהודה, יצטרך לקבל יום שיבא (אם לא שנאמר שכל שבוע צריך שמנה עשרה תפלות). ותחשב.
ונראה שאין הכי נמי, היה אפשר להתפלל תפלה של יום המוקדם, ולקיים מצוות ערבית. רב וציבור וכדומה התפללו תפלה של יום שיבוא. לכן, צריכים שיחול קבלת אותו יום, ולכן, נראה, חל קבלת אותו היום. ותחשב. אז, ממילא לא צריך כן ביום רגיל. ותו"ת.
** צלי של -
יש להעיר, והוא פשוט, שיש כאן שני חידושים:
1. יכול אדם להתפלל ערבית ביום (כרבי יהודה).
2. יכול אדם להתפלל תפלת שבת בחול.
** אלא של מוצאי -
יש לדון אם יש שינוי בזה, או שרק מבאר מה קרה (כמו שאומר שאר טעויות)[fn:26].
גמרא שואל אם יכול לקדש על הכוס, ושוב שואל אם יכול להבדיל על הכוס. יש לדון אם זה חילוק בין הבדלה לקידוש או חילוק בין שבת למוצאי שבת. לכאורה, השני יהיה נוגע כאן. בשניהם, יש לדון איזה הוא היותר מחודש; על צד אחד, אולי שבת יותר מחודש, שעושה קדושה, ואולי זה קשה, אבל לאידך צד, אולי של מוצאי שבת יותר קשה, שטוב שיהיה קדושה שם, ואז אולי יותר קשה לסלקו מלהביאו. ותחשב.
** רשות -
ואם תאמר למה מזכיר אותו משנה שלנו, שהרי משנה דן בזמנו. ויש לומר ש"אין לו קבע" כבר ר"ל שזמנו אינו קבוע, ורק מזכיר בלשון זה לומר שהוא רשות. ויש לדון איך יודעים שגם ר"ל שאין לו זמן קבוע. אולי הוא גופא מפני שהוא במשנה זה. גי"ל שהוא מפני שלא אומר שהוא רשות.
גם אפשר שמה שהוא רשות שייך לזמנו, שמשנה מפרש שאין לו זמן של שאר תפלות. משנה דן בזמן חיוב. אז, בשאר אומר זמן חיוב שלהם, ובזה אומר שאין זמן, שאין חיוב כלל. יש זמן מצווה, אבל משנה רק דן בזמן חיוב. כמובן, צריך לבאר אז ל"ל דן בזמן מצווה. ויל"ד אם זה קשה.
** הלכה כדברי האומר -
נמצא שאביי פוסק נגד סתם משנה זה. אז, צריך לומר שסובר שאין הלכה כסתם משנה. אולי אביי חולק על הדיוק שייק גמרא לעיל. (יש לדון איך מבאר אותו לשון. גם יש לדון ל"ל אומר שחולק כשמבאר גמרא אתו דיוק, ולמה לא שם מבאר איך לומד הדיוק.) גם יש לדחות ששאני דיוק מסתם משנה מן סתם משנה עצמו. ותחשב.
גם יש לומר שבדרך כלל, הלכה כסתם משנה, אבל כאן בוודאי אין הלכה כמותו, שהרי רבי יהושע, לבסוף, אמר כרבן גמליאל. דחוק לומר כן, שלכאורה, היה מתוך הדחק. ויש לדון, שאולי כיון שקבעו כן, קבעו. ויש לדון אם קבעו, שהרי הפסיקו למתורגמן.
** והלא ר"י אמר -
לקמן, יאמר גמרא שאותו תלמיד רשב"י. מצאנו בו, אז, אותו מדה שהיה אומר כל דבר, שאף שגורם רע (כמו בשבת לג).
כח.
** אפילו שעה אחת -
רק מביא ראיה שהיה שם, אבל לא שלא מנע עצמו אפילו שעה אחת.
** הואיל והכי הוה -
לכאורה, ה"הכי" הוא שהיה כל כך רע לרבי יהושע עד שהיו צריכים להעביר לרבן גמליאל. אז, הכיר שהיה מצער לר"י יותר מדי, ואז היה שואל סליחה מאתו.
** אלא לדרוש ר"ג -
ואם תאמר הרי אף זה ירידה. ויש לומר שכיון שהיה עדיין נשיא לא נחשב ירידה. לא נראה כן, שלא היה נשיא שדרש כל כך. אז, אולי הוא הורדה, אבל טוב להוריד קצת מלהוריד הרבה. נראה שאם כן, צריכים לגורס כאן שנתנו לר"א תרי שהתות, ולא תלת, שהיה להם למעט בהורדת ר"א.
** ולא היא -
זה מעניין, שהרי החזירו ר"ג לנשיאות. לכאורה, אז, חזר שומא הפתח (ויש לדון, שאולי היה ראב"ע עושה שלא יבוא כלל). אם כן, לכאורה, חלופ זה לנחמו גרם שהרע שעשה נמשך עוד ועוד. ותחשב.
ויש לדון, שאולי הכיר שהחלום היה לנחמו, אבל ידע שהוא אינו כל כך רע, שהרי ה’ נחמו עליו. זה קצת גלגל החוזר. ותחשב.
** צערא -
צריך ביאור למה משנה הלשון מתברא. ותחשב.
** דריב"ל -
יש להעיר שיש ראשונים שכתבו שהיה ריב"ל תלמיד של רבי יוחנן. אם היה רבי יוחנן עדיין לומד מאחר (מרבי נתן), מעניין לומר שהיה אפשר שרבי יהושע בן לוי כבר אמר מימרא. ויש לדון.
כח:
** ואשמח בהם -
עיין ברש"י שמבאר שר"ל שלא יטעו ואשמח בטעותם, ואז גם אני אעבור. כמו כן הוא "וישמחו בי חבירי.”
עיין בגמ’ מגילה (כח.) שרנבה"ק האריך ימים כיון שלא נתכבד בקלון חבירו.
** אני משכים -
ר"ל, צריך אני להודות לה’, כיון שתורה רק גרם טוב, שגרם עולם הבא, ולא גרם צער, שבין כך ובין כך הייתי צריך לצער.
** כבוד חברכם -
נראה שלכן נמנה כאן, שהוא שייך ל"וישמחו בי חברי.”
** אם שגורה -
יש לדון למה יהיה שגורה, כיון שכשאינו שגורה, אומר מעין יח, ולא יח. אולי יש עדיין ענין לומר כל יח, ואז ישגר יח’ בפיו.
** כנגד מי -
מצאנו בגמ’ בכ"מ (כמו במגילה גבי סדר ברכות שמ"ע בימים מוחדים) ששואל כנגד מי הם, ולא כנגד מה. צריך ביאור למה. אולי הוא רק שבדרך כלל, בני אדם יותר חשובים מדברים אחרים. אז, יותר מסתבר שייתקן על בני אדם מעל דברים אחרים. דחוק.
** כנגד מי תקנוה -
נראה שהוא מחודש יותר שגמרא כאן שואל מי, אף שיודע בשאר הברכות שאינו כנגד מי אלא כנגד מה. ותו"ת.
** מעין שמנה עשרה -
יש לדון למה יכול להתפלל כן, אם הוא מפני שאומר החלקים הנצרכים של שמנה עשרה או הוא שמציין לכל שמנה עשרה. יש להעיר שאם נאמר כשני, אז מעניין שכל אדם יכול להתפלל מעין שמנה עשרה, שאז מה שלו מציין אינו כל כך חשוב ואינו כל כך ידוע, שהרי אין מי שצריך להתפלל כן. ותו"ת.
כט.
** דאתחיל -
ועוד שהוא עסוק כדי לזכור אותו.
** הוא ינאי -
מניח שהיה ינאי תחילה. היה אפשר לומר שהיה ינאי אחר שנסרך. כמו כן, לרבא לא מוכרח שהיה לעולם צדיק; יש לומר שהיה רשע, ורק לא נודע כמו ינאי. אולי "צדיק מעיקרו" הוא חלק ממילים של רבא.
** לייט עלה אביי -
יש לדון אם זה מפני שסובר כרב או מפני שסובר כרבן גמליאל (או שעל כל פנים, יותר טוב לעשות כן).
** שהתחיל -
יש לדון למה:
1. אולי הוא מפני שגילה שרצה לאומרו, שאי לאו הכי, למה לו להתחיל אותו. (ולא מסתבר שנעשה מין באמצע הברכה).
2. יש ראיה שאינו מין (ולא מסתבר ששינה באמצע ברכה) כיון שכבר אמר מקצת תפלה נגד מינים.
** ונימרה -
לכאורה, הקושיה הוא שאינו רע אם שוכח, שיכול לחזור ולומר אותו בשומע תפלה.
כט:
** שאינו יכול -
לכאורה, זה סימן, והוא שנוהג וחושב על תפילה באופן שעכשיו לא יכול לחדש דבר.
** מעניין שגמרא
אומר שמתפלל תפלה קרצה זה כשהוא במקום סכנה, שתפלות אלו הם, בעיקר, על בנ"י וכדומה, ולא על מצבו. אולי מתוך כך מכיר מצב של בני ישראל וצורכם לתפלה. גם יש לומר שכיון שמזכיר דברי ציבור, וה’ יענה אמן, שלא מואס ציבור, יותר נוח שה’ יענה אף לו. כמו"כ י"ל שכולל את עצמו עם ציבור (כמו שיאמר אביי לקמן) לומר שלכולם יארע רק טוב. ותחשב.
** תוליכנו -
לכאורה, הציבור כאן הוא כל מי שהולך (ומסתמא בשעה שהוא הולך, יש אחרים שהולכים). גם יש לומר שהוא כולל אף ההולכים אחר כך.
** לייטי -
עיין במה שבאר רש"י. יש להעיר שמשמע שיש רע אם נאנס אז. יש לדון בזה, שהרי נמצא שבשעה שעבר, היה נאנס. באמת, אף לפני כן, היה מכוון לטוב, ולא היה פושע. זה יש לדון, שאולי היה לו להבין שאולי יאנס, ואז נחשב פושע.
זה ק"ק על ר"ן שכ’ שאם נאנס אז, נחשב אונס. באמת, אף קשה גמרא לעיל שאומר שנקרא פושע.
נראה שצריך לומר שנחשב אונס, אבל עדיין אינו טוב. ר"ל שהוא כמו שוגג, שלא היה לו לטעות כך, אבל קצת יותר דומה לאונס.
ודע שלולי רש"י היה אפשר לדחות (וכמו כן יש לדחות הא דר"י  גבי תפילת מוספים) שחוששים שיהיה פושע באותו שעה ואז יפסיד זמנו. ותחשב.
** לא תרווח -
לכאורה, אינו נכון שבזה לא יחטא, שאף צריך שלא לכעוס. לא היה יכול לומר שאם תרווח תחטא, אולי, שלכאורה רק אולי יחטא, אבל לא בהכרח יחטא. ותחשב. עדיין יש לדון ל"ל אמר, “לא תרווח ולא תכעס ולא תחטי.”
אפשר לומר שיש בעיה רק אם הוא רגזן והוא שתוי, והוא שהבעיה אולי הוא כך: אדם יכעס. הוא ירא שמים, ואז לא יעשה כלום, וימחל בעיקר לחברו ככל יכלתו. אחר שהוא שתוי, אז יקפיד על חברו מחמת כעסו שלפני כן, ואז ילך ויחטא נגדו. אז, אם אינו רגזן או אם אינו שותה, אין בעיה. ותחשב.
** המלך -
עיין במה שבאר רש"י. אינו ממש נוטל רשות, אלא אולי שואל רשות. אף זה אינו ממש, שלא שואל רשות, אלא שואל לעזרה. ותחשב.
ל.
** לישתף נפשיה -
יש לכתוב שלש צדדים פשוטים למה יותר טוב להתפלל בעד ציבור:
1. מה שמתפלל בעד חבירו הוא מצווה. כיון שמקיים מצוה זה, זכאי הוא, וה’ שומע לתפלה זה. (ואולי אינו רק מה שהוא מקיים מצווה, אלא שמקיים מצווה בזה, ואז ה’ רוצה להקשיב לתפלה כזה, שיש לו נחת רוח ממנו, ומביאתו יותר לפניו.)
2. יש לציבור זכות, וה’ לא מואס בהם. אז, אם אדם מתפלל להם, ה’ יענה. יש לדון בזה, שמה שאומר שה’ מכפר לציבור קצת קשה להבין, שצריך לדון מה עושה אותם ציבור. לכאורה, מה שעושה אותם ציבור אינו מה שזה מתפלל עליהם ביחד, אלא דבר אחר. אז, זה לא יהני.
גם לא מסתבר שמחמת הזכאים שבהם ה’ ישמע יותר לתפלה, שגם ימאס יותר מפני הרשעים. ושי לדון, שאולי אין ה’ מואס בתפלת רשעים כל כך כמו ששומע בתפלת צדיקים. ותחשב.
1. אולי הוא מפני שאז נחשב יותר תפלת ציבור, שכל אדם מתפלל אותו דבר. אז, אולי כולם מצרפים לציבור שמתפללים כן. כשציבור מתפלל דבר, ה’ שומע יותר. ותחשב על זה.
** מהיות טוב -
לכאורה, אילו לא היה חבורה שלו שוהה, לא היה שוהה. לכאורה, זה מפני שמפסיד במה שאינו בחבורה. אז, כאן אף בלי "מהיות טוב" יש לו להפסיק כדי שיהיה עם חבורתו.
ויש לדון, שאולי זה רק דבר קצת טוב, שיעשה שילך ולא יעמוד, אבל לא יעשה שיעמוד ולשהות.
גם יש לומר שאמר שאז אף הוא יאמר תפלת הדרך באותו זמן שצריך לשהות, ולא יעשה דבר אחר ויברך על הדרך.
** עומד -
איני יודע אם ר"ל מופסק, שלא הולך, או שעומד, שאינו על גב סוסו, אלא עומד. בין כך ובין כך, לא יכול ללכת כשהוא עושה כן, ואז שניהם שייכים בגמרא זה.
** מה בין -
ממה ששואל כן, וממה שנשנים יחד במשנה[fn:27], משמע שיש שום קשר בין שני דברים אלו. יש לדון מה הוא, שלכאורה, הביננו הוא דרך להתפלל שמונה עשרה, וזה תפלה מיוחדת שנאמר במקום סכנה. אולי הם תפלות חיוב שאינם שמונה עשרה. צריך ביאור.
** תפלה קצרה -
משנה מזכיר מין אחד של תפלה קצרה. בברייתא חולקים מה אומר באותו תפלה קצרה, ואליהו מזכיר עוד תפלה קצרה. יש לדון, בכל זמן שגמרא דן בתפלה קצרה, על איזה מהם קאי. (באמת, יש לדון אם של אליהו גם חולק על משנה שלנו, כמו שאר תנאים של ברייתא, שלכאורה חולקים.)
** כנגד א"י -
לא הבנתי ל"ל יכוון את לבו כנגד בית קדשי הקדשים.
נבאר ראשון ענין זה. לכאורה, אין הענין שה’ הוא יותר שם, שגמרא דן בזה במקום אחר (בבא בתרא) ומסיק שיתפלל למערב (וצריך לעיין אם אפשר שזה ר"ל לא”י), אם לא ששכינה הוא בכל מקום. אלא, נראה שהענין הוא שכשפונה אל מקום, יש לו קצת יחס לאותו מקום; אם יש לאותו מקום קדושה, נמצא שמיוחס למקום קדוש. זה מהנה לתפלה שלו. באופן יותר דרושי, יש לומר שהוא עושה סמל שמחכה לה’, שהרי הוא מביט לקדושה. ותחשב.
על כל פנים, נראה שהענין הוא ששם של כל ארץ ישראל הוא א"י, ולא ירושלים וכדומה, שא"י הוא השם הכי חזק שלו (ויש לדון למה). אבל, כשאדם כבר בא"י, אין שם של א"י כל כך חזק, שהרי כל מקום שילך יהיה א"י (תחשב על סברה זה). אז, נותנים, לנגדו, שם של ירושלים. אז, יש חילוק לאיזה צד הוא מביט. וצריך ביאור.
גם אפשר שהענין הוא רק שחוץ מא"י מסתמא הוא קשה ביותר לכוון יותר מלא"י. ותחשב. וצריך להגדיר, כמובן.
** מי שאינו יכול -
לכאורה, סדר הברייתא מוזר, שהיה לו לבאר מה שצריך לפנות אל רוח מיוחד, ושוב לבאר דין מי שלא יכול לכוון אל הרוחות.
** מקום אחד -
לכאורה, הוא א"י, אבל לא ירושלים וכדומה, שאין בני חו"ל מכוונים לאותו רוח. ותו"ת.
** טריחא לי -
מעניין שלא אמר שהוא טריחא להם (לבני הישיבה). נראה שאולי ר"ל שלו נחשב טורח להם. ותחשב.
** אמר’ חייא בר רב -
בדרך כלל, הובא ל"חייא בר רב.” עיין בגיטין, שבפרק שני (גבי זמן כתובה) הובא לרב חייא בר רב. אולי היו שני אנשים חלוקים. יש להעיר שיש הוכחות ששניהם היו בני רב (ר"ל, אבא אריכא).
ל:
** יתיב ר"ח קרא קמיה -
איני יודע כל כך לפרש לשון זה. אולי שמו היה כן, אולי על שם שהיה בקי בקראי. גם יש לומר שהיה יושב וקורא לפניו. אולי קרא מימרא זה שהיה יושב וקאמר. ותחשב.
** אף על גב -
לכאורה, ר"ל שאף התפללו מוסף שם, ואף שהיה ציבור. זה, לכאורה, הסיבה שהובא כאן.
גם אפשר לומר שרק הובא אגב דין מתפלל ביחיד במקום חבר עיר, שדן איך יהיה אדם עושה כן, שהרי צריך להתפלל עם ציבור. ויש לדון.
** רש"י
כ’ ששיטת ר"י הוא שחזן פוטר כל בני אדם. ויש לדון, אז, למה בני אדם שהם בציבור מתפללים. אפשר שכיון שרק פוטר אחר שמברך, יכולים להתפלל קודם תפלת חזן (ואף בני אדם שאינם מן הציבור), ואף שיכולים לשהות ולא יצטרכו להתפלל.
גם יש לומר שלא היה ש"ץ מוציא הכל בלי תפילתם, שתפילתו מיוחס לכולם, ונעשה תפלת ציבור, וזה רק מפני שהם התפללו אותו דבר. ותחשב. (כמו כן, יש לומר שיחס שלהם להדדי, שעושה אותם ציבור, לא נעשה אא"כ כבר התפללו ביחד.)
** כדי שיכוונו את לבם -
זה מעניין. לכאורה, הייתי אומר שהמשנה מתחיל בדיון ב"מתוך כובד ראש,” ואז ימשיך לדון בחסידים שהקפידו כל כך בכובד ראש. אז, היה לו לומר, "כדי שיכבדו ראש.” לא אומר כן, אלא אומר, "כדי שיכוונו את לבם….” אז, נראה שיש לומר שני דרכים:
1. אולי שניהם אחד. זה אומר שאולי "כדי שיבדו ראש" ו"כדי שיכוונו את לבם לשמים" הם שווים. יש שני דרכים לומר זה:
  1. הענין הוא שיכבד ראש, אבל אם אדם מכוון את לבו לשמים, ממילא יכבד ראש.
  2. הענין הוא שיכוון את לבו לשמים, והסיבה שצירך לכבד ראש הוא כדי שיכוון.
  3. אפשר שהם ממש שווים, והם רק מילים חלוקים לאותו דבר. נראה שמה שאמר מילים חלוקים הוא שאחד (כוונת לב) הוא דרגה יותר גדולה של חברו (כובד ראש).
עדיין יש לדון למה לא אמר דבר אחד (מסתמא, היה לו לומר מה שהוא הענין). נראה שלשני, יש לומר שבחסידים אומר התועלת, שכן בא לבאר, אבל כשאומר מה צריכים לעשות, אומר הדרך שבו עושים, שהרי בא לבאר איזה מעשים מוטלים עלינו לעשות.
1. אולי אין הכי נמי, לא עשו כן לאותו סיבה. שנים אלו הם ביחד רק מפני שהם תקנות לתפלה: כדי שיהיה לאדם תפלה טובה, צריך אדם לכבד ראש, וטוב לשהות שעה אחת. כמו כן, יש לומר שהם שני דברים שצריך בשעת תפלה: צריך אדם לכוון את לבו וצריך להיות לו כובד ראש. ותחשב.
** במקום גילה -
איני מבין כל כך מהו דין זה. לכאורה, מרש"י יוצא שדרשה למשנה בא מ"עבדו את ה’ ביראה.” אז, לכאורה, זה צריך להיות דין אחר. לכאורה, מגמרא מיד אחר זה, יוצא הוא שבכל זמן שאדם יש לו גילה, יהיה לו אף רעדה. קשה, שאם כן, לא צריך לפרש כן, שזהו, לכאורה, פשטות הקרא. ותחשב.
** אנא תפילין -
יש לציין למה שאמרו חז"ל שמי שלובש טלית ותפילין… בוודאי לא יחטא. אז, יש לומר שהענין הוא שאם אדם יש לו גילה ביותר, אולי יחטא. כאן, לא היה לו אותו חשש.
עיין ברש"י. יותר משמע שהענין הוא שמי שהוא שמח ביותר נראה שאין עליו עול מצוות. ויש לדון, שאולי הענין הוא שכיון שהוא מראה עליו עדות קונו, לא יחטא. ותחשב על זה.
** הוה מציין -
קשה, שכבר נלמד מהכון.
לא.
** כסא דמוקרא -
עיין בתוס’ שכ’ שמכאן נהגנו לשבור זכוכית. יש להעיר שקרו שני מעשים שהיה צריך לשבור כוס. לכאורה, צריך לומר שאחר ראשון לא נהגו, שהרי היה מהני בפעם שני לשבור כוס, ואז צריך לומר שלא רק נהגו כן. אז, לכאורה, מנהג שלנו בא אחר שנשבר שני פעמים. נראה שאולי בפעם שני שברו עוד כוס, או שברו כוס יותר טוב (אולי לכן מבאר כמה היה טוב). ותחשב.
** אז ימלא -
יש לדון איך מדייקים מזה, שאולי קרא רק אומר שאז ימלא שחוק פינו, שלא נותן היתר לזה, אלא אומר שכן יקרה. אולי זה פשוט (שהרי זמן ביאת משיח הוא, ואיך לא יקרה כן). גם יש לומר שמדייק ממילת "אז,” שמשמע שממעט זמן אחר (אולי מפני שהוא מיותר).
** מימיו -
יש לדון מהו משמעות מילת "מימיו.” הייתי סבור שוהא שמתחילת ימיו לא עשה כן. אבל, מגמרא זה, צריך לומר שלא כזה, שהרי אומר שמימיו לא עשה כן מכי היה ר"י מלמד אותו. אולי יש לומר שר"ל כמו שכתבנו, ולבאר שר"ל שהיה מקפיד כן מימיו עד שפסק מלהיות ת"ח, ושוב מכי למדו עוד מר"י. זה הולך למה שאמר תוס’ בב"מ שהיה ת"ח ושוב רשע ושוב ת"ח.
** דין -
יש לדון במה חלוק דין מהלכה. אולי דין הוא דבר שפסוק למעשה, והלכה הוא דבר שרק חושב עליו. גם יש לומר שדין הוא דין ממון, והלכה הוא הלכת איסור.
** וכל ארץ שלא גזר -
לכאורה, מן הקרא רק לומדים שרק אם גזר ליישוב היה בו יישוב, שאומר על אותו מקום שלא גזר שישב ולא ישב. אבל, אין לומדים שבהכרח כל מה שלא ישב הוא מפני שלא גזר.
** משבא לגולה -
היה אפשר להביא הקרא שאומר דווד. אולי יש לדחות שדוד על שם עתיד אמר כן (כמו שמצאנו בסוף פסחים).
** ויחשבהה -
היה אפשר לומר שהבעיה אינו במה שהתפללה שכרה, אלא במה שהיתה שכורה. נמצא שפשוט לגמרא שזה אינו כל כך רע.
** נגד ירושלים -
עיין לעיל, שאמר שצריך להתפלל לא"י (ולפעמים לירושלים, ולפעמים למקדש…), והביא קרא אחר. ותו"ת.
לא:
** דבר שאינו הגון -
ואם תאמר הרי יש בזה חיוב דאורייתא, שכ’, “הוכח תוכיח….” עיין בתוס’. גם נראה לי שהוה אמינא שקרא נותן היתר, שלא תאמר שאונאת דברים הוא, אלא מותר הוא. ותחשב.
** דברה תורה -
יש להעיר שכאן יותר קל לומר כן, שהרי דיברה תורה כן בתוך דיבור אדם. ותחשב.
** לבטלה -
צריך ביאור ל"ל אמר שרחם שלה היה לבטלה. (ויש להעיר שהיה אפשר לומר שיש צורך לדדים, שעכשיו אם תרצה להיות אומנת, תוכל.)
לב.
** נתמוטטו -
ואם תאמר אף בלי קרא, פשוט הוא, שהרי יש לה’ כל כוח. ויש לומר שהיו בני ישראל שעבדו עבודה זרה וכפרו בה’ נמנעים, שהרי הודו שאין לה’ אותו כוח. (כמובן, יש לדון אם אותו הודאה ישנה את דינם כיון שאינו נכון.) אז, אומר שאף ה’ הודה, ולא יכול, אז, לתבוע מהם. ויש לדון ל"ל יודה ה’ לעולם בשעת דין, כיון שהוא נכון.
כסא של שלש רגלים- צריך ביאור, שמהיכי תיתי שכלה זכות אבות; רק לא היה יכול להציל בני ישראל, אבל בוודאי יצורף עם זכותו. אם כן, אינו כסא של רגל אחת, אלא של ארבע רגלים.
** מה אני אומר -
לכאורה, הוא פיגיוריטי"ב, שהרי הם ימותו. אולי ר"ל, מה אומר להם אחר שאמות.
** סלחתי כדבריך -
רגילים העולם לומר (וכן כ’ חזקוני שם בפירוש שם; ויש מקורות אחרים) שאמר כן על העגל. מגמרא זה לא נראה כן, שאומר שה’ אמר כן להשיב למה שאמר משה, ומה שאמר משה בוודאי היה בחטא מרגלים.
** לב: אלא בתפלה -
היה אפשר לדחות שתפילה אינו יותר טוב, אבל מסוגל הוא לענות יותר בו, כיון שהוא דיבור לה’. אולי "גדולה" לא ר"ל הדבר הכי טוב, אלא ר"ל הכי גדול לענין השבת ה’ לו. דחוק, שהוא קצת חסר מן הספר.
בממונו- משמע שעיקר טובת צדקה הוא בצערו, שאי לאו הכי, יש פירכא חזקה, והוא שבצדקה הוא מחיה אחר.
** ואתפלל אל ה’ -
צריך ביאור, שרק רואים שה’ השיב על אותו תפלה. אולי שממע שכן היה בשאר פעמים ממה שאומר, “גם בפעם.” עדיין קשה, שרק שומעים שה’ השיב למשה, ורק שומעים שה’ השיב פעם אחר, אבל אולי חוץ מזה, לא משיב.
** הא דמאריך -
נראה שסבר בתחילה שענין עיון הוא רק שאולי לא יעשה, ואז לא יעיין או שאז אולי יעצב כשמעיין. אז, מקשה שבוודאי יענה. אז, דוחה שעינוי הוא גופא עושה שלא נענה. נראה שרעת עיון הוא מה שחושב שהוא מכריח את ה’.
תורה ומעשים טובים- כיון שקאי על קרא של שמירה ועשיית תורה, לכאורה, מעשים טובים ר"ל קיום מצוות.
** מעשה סיני -
ואם תאמר כבר אמר שלא ישכח. ויש לומר שרק יזכור פרט אחד של בני ישראל, אבל לא זה. גם יש לומר ששינו דבר כשהתפללו שה’ ישכח, וכיון שגרמו שהוא שכחן, אף ישכח את זה. ויש לדון, שאם כן, יצטרכו לחזור ולשאול אם שוכח את העגל. ותחשב.
** המתפלל צריך -
משמע שהוא חיוב ממש.
** עד שסיים -
יש לדון מה סבר לתת את נפשו בקידוש ה’:
1. אולי סבר שהוא יהרג ואל יעבור. מסתמא המקור לזה יהיה מסברה (או מן הסברה שאמר, או ממה שתפלה הוא גופא גורם לו לחיות. לא נראה כצד שני, שמסתמא אם אדם נאנס ולא התפלל, עדיין יחיה.)
2. אולי ידע שיוכל להציל את עצמו על ידי טענתו. יש לדון, שצריך להניח שיוכל לטעון ושיקבל טענתו.
3. סבר שמותר לגרום מיתה לעצמו על קידוש ה’.
** לג. ראה שוורים -
שצריך להרחיק מלוא עיניו.
** מעידים עליו שמת -
יש לדון ל"ל נקשה מזה על המשנה. צריך לומר שלא קשה לגמרא שמשנה יאמר שצריך למסור את נפשו. עיין לעיל.
** דתני -
יש לדון אם בא להוכיח מה שצריך להרחיק או שיעור שצריך להרחיק (שיעור ראייה, כמו שהערנו לעיל).
מתוך שהיא חול- אם כן, לכאורה, אם שכח בברכת הדעת, יאמר בשאר ברכות חול. ויש לדון, שאולי צריך להיות בתחילת חול, כמו שעושה תחילת חול. ויש לדון, שזה סתום בגמרא.
** וקבעוה -
כיון שהיום צריכים כוס, כמו שאומר גמרא, צריך לומר שחזרו והעשירו, אבל עדיין לא בטלו אותו מתפילה.
** שאינה צריכה -
מעניין שאינה לבטלה.
** לד
.
** עד דמכוון -
נראה שמקשה שאולי רק נראה שלא כוון, ואז לא יהיה נראה ככופר. מתרץ שלא נראה כן, שלא נוהגים בני אדם (כיון שאינם כופרים) לעשות כן, כיון שמראה חברותא כלפי שמיא. אם כן בזמנינו, לכאורה, יהיה מותר.[fn:28]
** תבשיל שאין בו מלח -
נראה שהדמיון הוא כך: תבשיל בלא מלח נותן כל טעמו, ולא רוצה שאחר יתן טעם. מפני זה, אינו טוב. כך זה, שרוצה לעשות את הכל בעצמו, ולא לתת כבוד לאחר, הרי "טעמו" רע. ותו"ת.
** חוזר לאתה חונן -
צריך ביאור ל"ל ימשוך על הסדר. צריך לומר שאם סדר הוא, הוא מפני שהוא קצת כעין ברכה אחת.
** ברכה אחת -
לכאורה, אף לר"ש מוכרח לומר כעין זה, שכן הוא הדין בראשונות ואחרונות. אולי מוקים אותו באמצעיות.
** לד: מקובלני -
לכאורה, ר"ל שכך שמעתי. מעניין שהוא קצת פון, שדן בתפלה מקובלת.
** מטורף -
נמצא, לכאורה, שהוא רק לשלחו, שאם לא כן, יש לומר שהוא רע לו, ואז אין לדעת. ויש לדון, שאולי הוא רק סימן בנוגע התפלה.
לא יתפלל- לכאורה, כ"ז לכתחילה (אם יש לו מקום שיש בו חלונות), אף שאומר לשון זה.
** לה
.
** אשכחן אחריו -
מקל וחומר שאומר גמרא, מבוא שלא רק ר"ל שמצאנו אחד, אלא שמצאנו לאחריו דווקא. ואם תאמר מהיכי תיתי שיודע את זה, ואז יכול ללמוד ממנו. נראה שרש"י (ד"ה אשכחן) מכוון לתרץ שיותר מסתבר שיש לו איזה שנוהג מדאורייתא. יש להעיר ששניהם נוהגים מדאורייתא, שנלמד מקל וחומר. אלא, מסתבר שיהיה הדין שנכתב בפירוש בתורה. ותחשב.
** חוץ מן -
יש לדון למה משנה את הברכה:
1. אולי הוא מפני שלא נחשב עוד פירות האילן; כיון שהוא כל כך חשוב, לא נשאר זה לחלק חשוב משמו.
2. אולי הוא מפני שיש ברכה יותר טוב לומר. הוא יותר טוב מפני שמזכיר חלק חשוב ומשובח משמו.
לכאורה, יכול להיות נפק"מ באם בירך על פירות האילן, שעל שני בוודאי יהני, ועל ראשון יש לדון. אפשר לדחות שאף לשני, אולי צריך לברך עוד, שיש לו יכולת לומר ברכה יותר טובה. ותחשב על זה.
** שנהנה -
לכאורה, ר"ל שאוכל.
** חייב בעוללות -
צריך ביאור למה חושב גמרא שזה סיבה לחייב אותו בברכה. אולי הוא סימן, שממה שצוותה תורה לתת לעניים, צריך לומר שהוא דבר נצרך. ויש לדון, שזה מניח שתורה אומר לתת דבר נצרך לעניים; היה אפשר לומר להיפך, שה’ לא יפסיד ממך דבר נצרך לתת לעניים. נראה שהוא דבר נצרך למי שאין לו דבר אחר. זה אומר שהוא דבר שטוב להיות כשאין דבר אחר. מחמת טובה זה, צריך אדם לברך לה’ עליו (ואף אם אינו עני). וצריך ביאור.
אלו לא יהנו לבאר צד מזבח, אם לא שנאמר שיש דגש לאדם לתת מה שהוא צריך לה’. אפשר לומר כעין זה שיש דגש לתת דבר חשוב, ומאכל חשוב נתחשב מחמת שבני אדם צריכים אותו.
גם אפשר לומר שאין הענין רק שכיון שהוא יותר טוב, צריך לברך ולהודות לה’ עליו, אלא אף שכשמברך שם ה’, עושה ששם ה’ נקרא על לחם. לכאורה, זה רק אומר שבני אדם חושבים על ה’ בנוגע לחם. יש יותר סיבה לעשות כן בדבר החשוב. ותחשב.
** מקדשי… לה
’- נמצא שקנין מאת ה’ הוא מה שעושה שיש בהקדש מעילה. עדיין יש לדון אם מה שעושה כן הוא הקנין עצמו או דבר שהקנין גורם.
לה:
** אלא חמרא -
לשון אלא קצת מוזר, שלכאורה לא חוזר ממה שאמר, שעדיין סעיד, ולכן יש לו ברכה מיוחדת. עיין ברש"י שנראה שבא לבאר אותו.
יבוא אליהו- צריך ביאור מה אמר בזה, שלכאורה השיב לשאלתו, שאמר שאינו קביעות מחמת שלא נהגו כן. לכאורה, משמע שיש סיבה אחרת שלא יהיה קביעות סעודה, אורמ שלזה לא ידע (או לא שייך) וצריכים לשהות עד ביאת אליהו.
** סעודה -
יש לדון מהו החשיבות:
1. רק מברכים שלש ברכות אחר סעודה. ויש לדון, אז, למה מברך אחר לחם כשלא קבע סעודתו. אולי בטלה דעת שלו, ונחשב סעודה.
2. רק מברכים על דבר חשוב, חשוב במה שקובעים סעודה עליו בדרך כלל.
לכאורה, שאלת רנב"י רק שייך על הראשון. לכאורה, אין תשובת רבא כשני, ואז מסתבר לומר כראשון. יש לדחות שלא ר"ל שעכשיו קובע, אלא שהוא לעולם קובע, ושואל אם זה חשוב די, כיון שלו יש לו אותו חשיבות. ותחשב.
** סעודה -
צריך ביאור מה נחשב קביעות סעודה. אולי קצת סימן הוא שכששואלים אדם מה עושה, אומר שהוא אוכל, ולא אומר שהוא עושה דבר אחר. ותחשב.
** לו
.
** הנאה -
יש לדון אם ר"ל שהוא הנאה של רפואה או שממילא יש אף הנאה של אכילה. לא נראה כשני, שאם כן, מי שאוכל אותו בפני עצמו יהיה חייב, שיש לו אותו הנאה. ותחשב.
עיין ברש"י שכ’ בפירוש כצד ראשון. אם כן, לכאורה, אף אם לא צריך לרפואה יברך כן. אולי אז יבטל דעתו.
** לו: ולוקח -
צריך ביאור איך ידע שלא לקט מעצמו (ולכן לא אכל אביונות).
** שומר לפרי -
נראה שיש לומר ארבע סיבות למה נאסר:
1. אותו סיבה לאסור פרי גם אוסר שומר הפרי (ומה שהחפץ שהוא שומר יש לו אותו סיבה לא שייך לסיבתו).
2. מחמת יחסו לפרי, סיבת הפרי בא אל שומר הפרי.
3. מחמת יחסו לפרי, דין פרי בא אל שומר הפרי.
4. יש סיבה אחרת לאסור שומר הפרי.
** ערלה -
מניח גמרא שכיון שקרא מלמד שחייב בערלה, צריך לומר שהוא פרי. היה אפשר לומר שקרא רק מרבה אותו לערלה, כמו שמרבה שומר. כן קצת משמע ממה שצריכים קרא. צריך לדחות שצריך קרא לגלות שהוא פרי.
** ללמדך… חסר -
צריך ביאור מה אומר, שלכאורה, אין קרא ראשון אומר כן. אולי צריך לומר שמגלה שאף דבר מוזר כעין פלפל, שעץ יש בו טעם פריו, נמצא בא"י, קשה, שלא אומר כן קרא, אלא רק אומר שיש עליו ערלה. אולי מניח שהוא בחו"ל רק מדברי סופרים, או שתורה לא יאמר דבר שרק נוגע להל"מ. צריך ביאור למה לא.
** לז. דתניא ריב"נ -
עיין שם, שמבואר שהנידון הוא אם מחמיץ או לא. אם כן, לכאורה צריך לומר שמה נחשב דגן, ומה נחשב פת הוא מה שיכול להחמיץ.
** כמעשה קדירה -
אם אינו מברך אותם ברכות, צריך ביאור למה מדמה אותו למעשה קדרה, ולא לדבר אחר, שהרי כל דבר הוא כן.
** ריב"נ -
אז, יש לומר שברייתא שאומר שמברך עליו כעל מעשה קדירה הוא גם כן ריב"נ. נראה שאי אפשר מפני מה שמקשה גמרא לקמן, שאם כן יהיה ברכתו כברכת הפת.
** ולא כלום -
מעניין שקורא לברכת בורא נפשות "ולא כלום.” אולי הוא שייך למה שאין הברכה מדבר כלל על מה שאכל, אלא הוא ברכה כללי.
היה נראה לפרש על פי מה שכתבנו לעיל, והוא שברכה עושה שני דברים:
1. מודה לה’ על מה שנתן לו.
2. הוא מיחס שם ה’ על הפרי (חושבים בני אדם על ה’ עם הפרי).
אולי צריך לברך מחמת ראשון, אבל לא רוצים ליחס שם ה’ לאורז, שאינו כל כך חשוב, והוא קצת גנאי. (וצריך ביאור, שיכול לברך ברכה ראשונה. אולי יכול ליחס אותו לאורז למי שרעב, שלו חשוב. ותחשב.) אז, צריך לברך, אבל לברך ברכה שלא נוגע למה שאוכל. ותחשב.
נראה שאולי לכן, גם כן, מברכים, אחר שהולכים לבית הכסא, ברכת אשר יצר, אף שלא כל כך נוגע למה שצריך לברך ה’. (ויש לדון, אבל יש שהקשו כן.) הענין הוא שצריך להודות לה’, והדרך להודות לה’ הוא לשבח אותו, אבל אין להזכיר שם ה’ על מה שעשה, ואז נותן לו ברכה כללי. אבל, עדיין צריך לבאר מתי נוקטים ברכה זה ומתי ברכה זה.[fn:29]
** לז: ותני גבי אורז -
יש לדון ל"ל משנים דין פרוסות. נראה שאז צריך לשנות כל חילוק הבבות, וזה שינוי יותר גדול.
** אמר רבא -
אז, צריך לפרש באיזה דן גמרא לעיל.
** מלחם גדול -
צריך ביאור, שלכאורה, צריכים לכתות את כל המנחה. לולי רש"י, היה אפשר לומר שכיון שדן בפסח, לא דן עוד במנחות. וצריך לעיין במקורו.
** כדקתני -
לא הבנתי, שרש"י מפרש שחייב כיון שמעשיה מוכיחים כוונתו. אז, קשה איך נקרא לחם שעשה לכותח. אולי ר"ל שעשה אותו באופן שהיה מגלה מחשבתו, אלא שגילה דבר שאינו מחשבתו. אז, אולי חייב מחמת מראית עין או שבטל דעתו. דחוק.
** לח. ואדם יוצא -
נמצא שסובר שהוא פת, וחולק. יש לדון מה סובר מר זוטרא, שיש לומר שרק בירך עליו המוציא כיון שקבע עליו סעודה (וכמו פת הבא בכיסנים). ויש לדון אם יש לשאר מיני פת גרועים דין זה של קביעות סעודה או לא. אף אם אין להם דין זה, אולי רק חלק מ"ז עכ"כ שנתן להם אותו דין, אבל לא עכ"כ שסבר שהוא פת ממש.
נראה שלא היה פת ממש ממה שהיה צריך להזכיר שקבע סעודתו.
היה אפשר לדחות (אבל זה מחודש) שלחם עני לא רק ממעט לחם עשיר, אלא מרבה מיני לחם שלא יקראו לחם כי אם לנגד עני. אולי מחמת זה מרבה מין זה של לחם.
** זיעה -
ר"ל, אינו חלק חשוב ממנו. אז, יחסו לפרי האילן אינו כל כך חזק (אף שפרי האילן גרם אותו). ותחשב.
** חשילתא -
לכאורה, מה שלא באר לו רבינא כוונתו הוא שלא לבייש את רבא (כיון שלא ידע). מעניין, אז, שרבא גילה שלא היה יודע (שאי לאו הכי, למה יזכיר מה הוא).
** לרפואה קא מכוון -
לא הבנתי, שאמר לעיל שרק מותר כיון שכיוון לאכילה.
** המוציא לחם -
קשה למה מברך כן, שהוא כיין ושמן שגמרו בידי אדם.
** טעם מצה -
קשה, שגמרא בפרק אחרון של פסחים אומר שאין צריכים טעם מצה. אולי זה רק לפי רבי מאיר.
** דילמא בורא -
ואם תאמר אם כן מהו עדותו. י שלומר שהו"א שלא חשוב די עד שצריך ברכה אחרונה. גם יש לומר שהו"א שהוא פחות משיעורו.
** לט. אגור -
עיין במה שפירש. יש להעיר שזה מחלקת בפסחים (לג).
* תנאי- לכאו’, רואים שהיו תלמידי ב"ק נחשבים תנאים. יש לדחות שלא מסתבר שכל אחד יפסוק על פי דעתו. אז, צ"ל שהיה לכל אחד בריי’. דחוק.
** והאי דפרמינהו -
יש לדון מה ר"ל:
1. ואינו כן אם מפרים אותו כל כך עד שנשתנה טעמו.
2. כן הוא אם מפרים אותו כל כך עד שנשתנה טעמו.
3. כבר לעיל אמר שאין חילוק, ומבאר שאין חילוק בינו אלא שעושה כן כדי לשנות טעמו. צריך ביאור ממה מוציא. ותו"ת.
** לט: מברך על הפורסה -
יש לדון אם צריך או צריך רק אם יותר גדול.
** שמניח פרוסה -
עיין בפסחים (פרק ערבי פסחים) שאומר גמרא כעין זה, ועיין שם מה שמפרש רש"י, שאינו נראה מן הלשון כאן.
** מ. טול ברוך -
יש להעיר שאינו נוגע לאכילתו, והרי הברכה היה על אכילתו.
** ונתתי עשב -
לכאורה, אז, לא צריך לתת להם מזון, אלא שיאכלו, שלכאורה, לא נותנים להם עשב. ויש לדון, שאולי צריכים לגרום אכילתם, והוא שצריך להוליך אותם. אבל, מסברה לא נראה שמי שכבר אכלו בהמות שלו אין לו תקנה.
** ביום -
יש לדון אם השעה שאכל (או תחילה, או סוף, או שום חלק) או היום שמצער הוא יום או לילה. ותו"ת.
** מ: כל המשנה -
יש לציין לגיטין, שבו ר"מ אומר, “כל המשנה ממטבע…" לענין דבר אחר.
** אלא בפה"א -
צריך ביאור, שהרי נקרא עץ:
יש להעיר שיש שני ראיות:
1. ראיה מקרא.
2. ראיה מברייתא.
לראשון, יש להשיב:
1. לשון תורה חלוק מלשון ברכות.
2. נקרא עץ הדעת, שזה גופא מראה שאינו ממש עץ, אבל לא נקרא עץ סתם.
לשני, יש להשיב:
1. לשון משניות חלוק מלשון ברכות שתקנו.
2. נקט אותו לשון אגב שאר התנאים.
3. אילן אינו שווה עץ
** ואלו נאמרים -
צריך ביאור איך נלמד מברכת המזון, שיש לחלק בין ברכה לפניו לברכה שלאחריו. ואם תאמר הרי נלמד ממנו. נראה שכיון שיש מקור לשאר ברכות, אותו חיוב יהיה על ברכה שלפניו.
** מא. בשאין -
יש לדון מי מהם מעמיד שיטתו בשאין ברכות שווים.
** יש לדון אם
יסוד של שיטת ר"י הוא שברכה על מה שהוא חביב לו הוא יותר טוב או שאין מטריחים אותו לאחר מה שחביב לו. יש נפק"מ אם הוא יותר חביב לו, ולכן רוצה לאכלו אחרון. ותו"ת.
** מא: מדרבנן -
עיין בגליון. עיין בירושלמי בתחילת פאה. עיין ברש"י ערכין (יח:). ודע שכאן אינו כל כך הוכחה, שאפשר לומר שלא אומר שהשיעורים הם דרבנן, אלא אולי הדרשה הוא מדרבנן. לא אפשר לומר כן לפי שיטת ריטב"א באסמכתא. אף לרמב"ם לא נראה כן, שלא צריך לומר יותר מ"אסמכתא" אז, שזה אומר הכל. ותו"ת.
** מב. דקבע -
לכאורה, אז, כשרק שמע "צ"ים, לא יכול לדעת שטעו.
** נראה שמה שברכת
עיקר פוטר טפל שלו, ומה שסעודה פוטר כל מה שנאכל עמו, הוא מפני שברכה על פת אומר ברכה לה’ על פת בכל אופן שנאכל. אז, כל מה שנאכל עמו, ונכלל ב"כל אופן שנאכל,” נפטר. אבל, אם אין דרכו להיות נאכל עם פת (או אם אינו מהנה את הפת כלל), אז לא נכלל באותו ברכה.
כמו כן, יש לומר שבאכילת פת, אדם חושב על מה בא עם הפת, ובמח’ על זה מודה לה’. אז, נמצא שנתן לה’ טוב בברכה בחילוף טוב של כל הסעודה, שעליו היה חושב. ותחשב. (ונכלל בדעתו להיות נחשב טוב אחת, כיון שהוא חלק מיונט אחת.) ותחשב.[fn:30]
** מג. רמא להו -
ואם תאמר ל"ל רק אמר להם הדין. וי"ל שרצה להביא ראיה. גי"ל שלא ידע במה היו עוסקים, וה’ נתן שמועה זה בפיו. עדיין יש לדון למה ה’ נתן את כולו בפיו, ולא רק מה שהיה צריך. ותחשב.
גם יש לבאר על פי מה שאומר תוס’ בתחילת חולין, והוא ש"ההוא סבא" הוא אליהו הנביא. כיון שאין הלכה בא ממנו, שאינו בא מן השמים, היה צריך להביא ראיה. אז, הביא הסתירה. ותחשב.
ויש לדון, שאולי הוא גילוי מילתא, שרק אומר המ שאמר חכם אחר ליישב. וצריך להגדיר, שאז אף יכול לגלות מה סובר תנא או מה סובר משה רבינו או מה סובר ה’.
** מגו דמהניא -
היה אפשר לומר (ולא נראה שאומר כן) שצריך פת רק כדי לעשות שהקביעות הוא קבוע, אבל אז מהני אף ליין. לא נראה שגמרא אומר כן. ויל"ד.
** מג. בר מיניה -
יש להעיר שר"י הוא הסובר בסוף כתובות שאסור ללכת לגור בא"י.
** ואמאי -
לכאורה, כווונתו להקשות למה הוא ברך כיון שיש גדול ממנו, שאי לאו הכי, יתרץ שמה שהוא מברך על המוגמר הוא מפני שברך כבר לכולם. קשה, אז, מהו תירוץ גמרא, שנאמר שאז קשה למה הוא נטל ידיו תחילה. וצ"ב.
נראה שאולי אין כבוד בזה, ואינו כל כך רע להקדים מי שאינו גדול, אף שיגרום כבדו. ותחשב.
** מג: זכינו -
נמצא שבברכתו לא רק מברך על הנאה שלו, אלא על כל הנאה שבא מן החפץ. (אולי הענין הוא מש"כ לעיל, שאף נותן שם ה’ עליו, וטוב יותר לתת שם ה’ על דבר יותר טוב.)
** אכריע -
כאן, לא ר"ל שהוא אומר שיטה שהוא באמצע, אלא ר"ל שהוא פוסק. רם כן, לכאורה, כאן ר"י אינו פוסק כר"ג מחמת הכלל של הלכה כדברי מכריע.
ויש לדון, שצריך ביאור אם יש הסבר אחר בשיטת בית שמאי, אבל אולי יש, ואולי נוהג לד"א, ואז נמצא שר"ג באמצע.
** עתידים בחורי -
נראה שנקט בחורי ישראל כיון ש"גנאי הוא לת"ח להיות מבושם.” (באמת, היה אפשר לפרש שהטוב שיבוא אינו ריחם, אלא שלא יהיה מצוי עבירה, עד שאינו גנאי עוד להם לצאת לשוק מבושם.
** בבגדו -
קשה, אז, מהו הבעיה לתת אותו בראש השמש, שזהו גופו. אולי חוששים שיפול משם לבגדו. דחוק, שקשה למה נותן עצה לתת בכותל, ולא לתת ולשמור שלא יפול על בגדיו.
** ולא היא -
יש לדון אם אומר שאין הלכה כן או שלא אמר רבא כן. עיין ברש"י. כמו כן, יש לדון אם ר"פ לא סבר שהלכה כן, אלא טעה ולא ידע שיש חולק, או שסבר כן, אלא שרצה לתלות דבריו בגדול.
** מד. אינה סעודה -
יש לדון אם ר"ל שאינו כל כך טוב, או ממש אומר כן לדין, וכל סעודת שבת צ"ל בו שרף.
** מד: ששה -
מונה שבעה; עיין בגר"א, שלא גורס דבש.
** מה. אכל דמאי -
לכאורה, כל אלו הם אף לענין ברכה עצמו. א"כ, ק"ק למה רק אומר דינם לענין ברכת זימון, ולא לענין ברכת המזון עצמו.
** דקבעו להו -
יש לדון אם זה סימן או סיבה. אף אם סיבה הוא, יש לדון אם ברכה בשעת חיוב יותר טוב, או שחוששים שכיון שאינו חיוב לא יברכו. לזה, יש לדון, שנאמר בשאותו ציור יהיה עליהם חובה. (אולי כיון שבד"כ אינו חובה חוששים שישכחו.)
** חייבים לזמן -
יש לדון אם יש לכל אחד חיוב, אלא עשיית אחד פוטר את כולם, או יש חיוב לכל אחד לשמור שיהיה זימון.
יכול אחד לצאת (אם יש ארבע). אולי שם חיובו חלוק, אבל אם נניח שהוא שווה, לצד ראשון, נצטרך לחדש שמהני הזימון לו, אף שכבר יצא.
** מה: איכא דעות -
צריך ביאור מה מכוון להוכיח.
** מעיקרא -
ר"ל, בא לחדש שצריכים לקרוא אחריו כדי לזמן בחיוב. (וצריך לדון בזה, שלכאורה, אילו בחרו שלא לקרוא אחריו, כיון שיכולים לזמן בפני עצמם, יצטרכו לזמן בפני עצמם. אם כן, אף הוא חיוב. אז, צריך ביאור למה צריכים לקרוא אחריו.)
** מו. בעל הבית בוצע -
לכאורה, לא סובר כמותו בזה, שנתן לאורח לברך. אולי רק ר"ל שסבר כסיפא שלו, או רק היה קשה לגמרא טעותו השני. (הדיון כאן הוא אם השיב לכל שאלתו או לא.)
** בעל הבית בוצע -
נמצא טעם לבעל הבית לבצע ולאורח לברך. לא אומר טעם שיהיה באותו איש, אבל צריך להיות שום טעם. יש לדון אם חלוקים מה דוחה מה או שחולקים באחד (או יותר) אם יש בו שום טעם.
** שנים ושלשה -
מניח שאף לר"ש, ברכת זימון הוא רק ברכה אחת.
** מו: אף הטוב והמטיב -
ר"ל, ואז צריך לומר שר"ע סבר שלא אומרים אותו.
** אף הטוב -
הוה מצי לומר שחולקים אם הוא דאורייתא או לא.
** ושני לו למעלה[fn:31] -
צריך ביאור למה. אולי והא כדי שרק יחוי ולא צריך לדבר.
** שני למעלה[fn:32] -
צריך ביאור למה לא נותנים שני באמצע.
** מז. טועה -
אם כן, רוב ומיעוט הוא סימן, ומה שהוא תלוי בו הוא הארכה יותר מדי. ויש לדחות ששיעור של "יותר מדי" הוא "אחר רוב.” ותחשב.
** כל המאריך -
זה נגד מש"א גמ’ ש"כל העונה אמן….” ואולי צריך להאריך, אבל לא יותר מדי. כמובן, צריך להגדיר.
** ואמר ר"ה -
לכאו’, ר"ל שאף אם תמצא ברייתא אחר…, זה רק ב"ש. אז, זה מצרף לראיה לדין זה. ותו"ת.
** מז: אינו מגדל -
יש לדון אם הוא כן אף אם הוא עצמו לא למד, או אולי יותר קל לו ללמד לבניו (שקל להם ללמוד, ועוד שלא מטריח א"ע) ממנו.
** אפילו קרא -
יל"ד אם זה קאי עליו או על בנו. ותו"ת. המשך גמ’ נ’ כצד ראשון, אבל לא מוכרח. ותו"ת.
** עבד… קטן -
צריך ביאור מהיכי תיתי, שמה שאין דבר שבקדושה פחות משנים נלמד מקרא, ואותו קרא אומר עשר גדולים מבני ישראל. ותחשב.
** עם הארץ דרבנן -
שמעתי בני אדם אומרים, “עם הארץ דאורייתא.” לכאורה, הם חושבים שהם בונים ומגדלים על מה שנאמר כאן, אבל אינו בכלל שייך. ותו"ת.
** מבדרי -
מוזר שיהיה מחלקת בזה, שלכאורה, מציאות הוא, והיו להם לבדוק. נראה שחולקים למי צריך להיות נראים כעשר. לכאורה, יש שני ציורים:
1. אדם רואה אותם ולא מכוון למנות כלל. נראה שאז אם הם יותר מפוזרים, נראים כעשר, שנראים כיותר.
2. אדם רואה אתם ומונה אותם. יותר קשה לו להוכיח שאין עשר כשהם מכונפים, שלא רואה את כולם חלוק מחבריהם, מאם הם מפוזרים. ותו"ת.
** מח. ככל הני -
יש לדון אם זה כולל מאמרים בענין עשר, שהרי רק דן בזימון, והיה אפשר לומר, אז, שרק משיב על הנוגעים לזימון. אבל, אולי דיוני דברים שבקדושה נשארים במקומם.
** רבא ואביי -
במק"א הערנו שרבא היה, לפי רש"י, יותר מעשרים שנה קטן מאביי, שהרי מת אחריו, ולא חי אלא ארבעים שנה (ואביי חי לששים). צ"ל שאין זה רבא סתם כן (וכן גורס בה"ג).
** מח: כשהוא רעב -
קשה, אז, למה לא צריך ארבע או שלש ברכות לפניו.
** כי הוא יברך -
זה רק ברכת המצווה (כמו שמבאר רש"י) אבל לא ברכת הנהנים.
** מט. בור -
מעניין שקורא אותו בור, אחר שיש תנא שאומר לברך כן. אולי לא שמע אותו תנא, אלא ידע שיש מקום לטעות. גי"ל שהוא רק בור אם מחליף שנים אלו.
גם יש לומר שבדרך כלל, סימן טוב הוא שהוא בור. לא מסתבר שאמר כן מפני שחשב כאותו תנא, שאין הלכה כמותו. אז, יהיה שני כללים:
1. בורים.
2. מי שאינו בור, אבל לא יודע שאין הלכה כאותו תנא.
כת ראשון יותר גדול מכת שני. ותחשב.
גם יש לומר שיש חילקו בין אם אומר רק אחד לאם אומר שנים, וברייתא רק דן באומר אחד.[fn:33]
** מט: אי בעי לא אכיל -
לכאורה, כיון שאכל, צריך לברך. אז, נראה שאין הענין שאף אם נחשב שאינו ברכה, טוב. אלא, נראה שהענין הוא שאין לאותו ברכה כל כך יחס ליום- שלא מוכרח- ולכן אין כל כך צורך להזכיר אותו בו. אז, לא מעכב. ותחשב.
כמו כן יש לומר שבהכרח אין חיוב להזכיר יעלה ויבוא, שלא צריך לאכול. אין ברכה כה יותר רע מאילו לא אכל, וכמו ששם לא חייבו, אף כאן לא יחייב אותו. ותו"ת.
** נברך -
יש להעיר שלומדים צורך לשלשה מ"הבו לה’….” לכאורה, אז אומר לשון כעין "ברכו,” ופירוש הקרא הוא שנאמר לשנים. ותו"ת.
** נ. ש"מ נברך עדיף -
ק"ק, שלכאורה, רק רואים שאין ברכו עדיף, אבל עדיין אפשר שהם שווים. שו"ר בתוס’. יש להעיר שכשאומר כן גבי "ברכו עדיף,” לא ר"ל כן.
** מאי קמ"ל -
לכאורה, יש חידוש אחר מן המשנה, והוא שאף שיש ארבע, ואז יכול לצאת אחד, וישאר זימון, עדיין אסור לצאת, שכל אחד צריך להיות חלק מן הזימון (או שכל אחד צריך לגרום את הזימון).
** עדיף -
היה אפשר לדחות שברכו עדיף, אבל לא די לחייב אותו.
** ועוד -
קשה, שאם אף ר"ע מודה לזה, איך יהיה המנהג נחשב כר"י. נ’ שהקשה לו ממ"נ, ואמר שאם תאמר שמודה ר"ע לר"י, אז תעשה כשניהם, ואם לא מודה, נמצא שמנהג כר"י.
** נ: פרח זימון -
קשה למה אינו כן אם שלש חלקו. אולי יותר קל להחזירם להיות שלש.
** פרח -
צריך ביאור מהו הצד לחייב יותר מכל זמן שכבר זמנו. אולי רק בא להוכיח שאי אפשר לזמן עוד לרשות. צריך ביאור איך רואים כן מטומאה. ותחשב.
** נא. עד דחלפי -
צריך ביאור איך יודע.
** נא: אנן נעבד -
קצ"ב למה, שלכאורה, הוא ספק דרבנן ויהיה לקולא.
** הכי אר"י -
לשיטתו הוא, שאמר לעיל ש"אנו אין לנו אלא ארבע.”
** יושב ומברך -
יש לדון אם זה רק בכוס של ברכה או בכל ברכה. לצד שני, יש לדון אם הוא בברכת הנהנים או בכל ברכה.
** נא: שהיין גורם -
לא הבנתי למה נאמר שגורם לקדושה שתאמר יותר מן היום. אולי לא מכוון לומר סיבה, אלא מבאר למה מה שאמר בית שמאי (“שהיום גורם ליין") אינו נכון. (ויש לדון, שזה לכאורה לא אומר שיום גורם לקידוש, אלא שגורם ליין. ואולי בית הלל דוחים שלא שייך מה גורם יין, אלא מה גורם קידוש, שבו עוסקים, והרי בקידוש שניהם שווים.) אם כן, מובן למה בית הלל צריך לומר שני.
** נב. אין משגיחים בבת קול -
נמצא שר"י, שהיה מב"ה, סובר שאין הלכה בהכרח כב"ה, ור"א, שהיה מב"ש, סובר שהל’ לעולם כב"ה, שהוא החול’ על ר"י לסמוך על בת קול.
** עיולי -
לכאורה, רק ר"ל שיש סיבה לאחר יציאת היום, אבל לא נותן עוד סיבה להקדים תחילת היום, שאם כן, אף בית הלל יצטרך שלש סיבות. על פי מש"כ בד"ה שהיין ואלי י"ל, שאולי גמ’ רק צ’ כיון שסיבה ראשונה של ב"ה אינו סיבה, אלא הוא דיחוי של סיבה אחד של ב"ש.
** נב: איפכא -
אינו ממש איפכא, אלא הוא חלוק. ותו"ת.
** מותר להשתמש -
א"כ, יהיה מקולי ב"ש. וי"ל שנשאל על דבר שבו היה חומרא. ותו"ת.
** מאור -
אז, צ"ב למה שינה שני דברים במשנה.
** שלא שבת -
לכאו’, לא נעבר על ציווי ה’, שגוי עשה אותו. צ"ל שעבר על סיבת האיסור. נמצא שיש ס"ר במה שעשה עכו"ם, ואין במה שעשה קטן. וי"ל שיש אף במה שעשה קטן, אבל אין מעשה קטן נח’ מלאכת שבת, כיון שצ"ל מלאכת מח’ (או שצ"ל לו מחשבה או שצ"ל חשוב). ותח’. אז, שבת חלוק.
** נג. רוב -
היה אפשר לומר שנקט רוב, ולא מחצה על מחצה, כיון שלא מצוי שיהיה מחצה זה ומחצה זה. ותו"ת.
** מחצה -
צ"ב למה מברכים, שהוא ספק ברכות. אולי קיים ענין הברכה אף אם עבר בה עבירה, ורק גם עשה דבר רע, שהוציא ש"ש על דבר רע. ותו"ת.
** תנא סיפא -
לכאו’, אומר כן כיון שיותר קל לעשות שסיפא הוא אגב רישא. כמו"כ משמע מגמ’ בזבחים. ויל"ד למה לא אומר גמ’ כן בכ"מ שאומר "ליכא למשמע מינא.”
** לאורה -
מברכים כיון שאז נברא אור. אז, צריך ביאור למה צריך להיות שהודלק לאורה. אולי מה שחשוב באור, והסיבה שמברכים, הוא יכולתו לתת אור לראות. כ"נ מלשון הברכה. יל"ד למה רק מברכים ע"ז, שיש ד"א שעושים אש שהם חשובים. אולי היו כבר חמי טבריא וכדו’. עדיין דחוק.
** אדם חשוב -
צריך לדון בכ"ז מהו הדין אם מדליק לשני סיבות.
** בטול -
צ"ב למה יש יותר ביטול אם מברך אחד לכולם.
** אם רוב עובדי -
לכאו’, מניח שהם לעבודה זרה. אז, הוא כר"א. לכאו’, לכן הוא חוטא.
** נג: מיתיבי -
לכאו’, היה לו להקשות ממה שצריך להיות נאותים לאורו (לאיזה נפק"מ נאמר).
** מרובה -
לא משמע שזהו זמן עיכול. אז, צ"ב למה חלוק.
** זוהמאי -
מעניין שאומר דבר בענין זוהמא.
** נד. מארצינו -
יש לדון מה אומר אם אינו בא"י.
** על הגשמים -
קצת צריך ביאור למה אין זה בכלל בשורות טובות. אולי מחדש גדר של טוב, והוא שכל גשמים כן. (יותר נ’ לומר שסתם גשמים כן, שהרי אין גשמים לעולם טובים.) גי"ל שמחדש שאף שעכישו אינו טוב, הוא דבר שהוא בדר"כ טוב, ואז מברכים עליו.
** ושמע קול צווחה -
יש לנו ק’ ע"ז מגמ’ ב"מ גבי מדידה. ותו"ת.
** בכל מדה -
לזה מביא הקרא.
** נד:
- למה רק מצורעים.
** ולא ידעו -
לכאורה, צ"ל שחזרו ההרים, שאל"ה קשה איך לא הכירו. כ"נ ג"כ ממה שהכירו מצורעים. ויל"ד, שאולי הכירו כיון שזב למעלה מן ההרים.[fn:34]
** ולא ידעו -
נמצא שמה שקרה כאן לא היה שינוי יותר גדול ממה שהיה קורה בכל פעם, אבל כאן היה יותר נצרך. אז, רק עליו מברכים. זה מעניין.
** אמן -
נמצא שעניית אמן על מי שלא מחוייב ברכה מהני. אולי מחוייב ברכת הודאה על הצלת חברו. עדיין מעניין, שאינו אותו ברכה. ותחשב.
** חיה -
עיין ביומא (כא"ח) שקורא ליולדת חיה.
** מאריך -
יל"ד ל"ל מזכיר דל"ת של ק"ש.
** נה. שנה טובה -
כמובן, כיון שכבר יש זה, לא צריך עוד. ותו"ת.
** ואברכה -
לכאורה, רק רואים שלא זוכה לברכה.
** ושובע -
ואם תאמר הרי זה בכלל רעב. וי"ל שאף שהם הפוכים, מכריז על כל אחד כשבא. גי"ל שיכול להיות דבר באמצע.
** נה: שלא יבהילוך -
היה אפשר לתלות החילוק בזה, לומר שהברכה אינו שלא יראה חלום רע אלא שיראה ולא יבהל אותו. ותו"ת.
** ספק נדה -
ואם תאמר גם נדה וודאית כן. וי"ל שהברכה הוא שלא יבוא נסיון לידך, ולא שלא תוכל לבוא עליה.
** יטיבנו -
נמצא שעדיין צריך הטבה, אף ש"חלמא דלא…." לכאו', הענין הוא שהוא כמו אגרת שלא נקרא, שלפעמים כיון שלא נקרא לא נעשה הדבר, שצריך ידיעתו, ולפעמים נעשה אף שלא נקרא. ותו"ת.
** שבע זימנים -
יש לדון אם אומר מילים "שבע זימנים" או אם אומר אותו שבע פעמים. ויש לדון איזה מילים אומר שבע פעמים, אם קאי על לפניו או לאחריו. ותו"ת.
** יהונתן ימות -
שם לא כ' פדיון. אולי בהמשך הקרא כ'. גם אולי ישועה שווה לפדיון.
** ואי לא -
עיין ברשי בשבת שדן אם ר"ל ואי לא אפשר או ואי לא מהני. לכאו', מצוי שאינו אפשר, שאין לו כהן שמברך. לא מצוי שידע שלא מהני, שאז כבר בא החלום הרע. ויש לדון, שאולי יש כמה חלקים בחלום, או שחלום אומר שיש רע שימשוך. ותו"ת.
** מזרעא דיוסף -
לפני זמן רב, שאל לי ש.א.ל. למה חולקים בזה, ואיזה נפקא מינא יש איזה הוא המקור. אין זה כל כך קשה, ומצאנו כעי"ז כמה פעמים, והוא שחולקים בפירוש התורה.
אבל, נראה שכאן יש נפקא מינא, והוא מה יאמר כאן. (זה מניח שמקור שמזכיר גמ' הוא חלק ממה שצריך לומר, ולא שגמ' רק מז' זה להסביר מה שצריך לומר.)
** אר"ע -
משאר רבנים הנז', לא נראה שזה הוא ר"ע התנא. (ואגב, יש להעיר שזה הרבה בני אדם.)
** והוא דמפשר -
שאי לאו הכי, לא היה שום מעליותא במה שעשה יוסף. כמו כן, כן מוכרח מום שאי לאו הכי אפשר לאדם לעשות שום דבר שירצה על ידי הפשרת חלום.ש
** אלא מהרהורי -
יש לדון אם ר"ל שאז ממילא אי אפשר שחלום מוכיח על העתיד או שרק אומר שהקנטקס"ט של מה שאומר החלום צריך להיות דבר מצוי. ותו"ת.
** וכולם -
זה יותר מחודש, שמחדש שכל הפתרים נתקיימים, ולא רק שהראשון נתן לו ביאור, וזהו.
** נו. את אמרת -
עיין בנדרים שכן קרה.
** בדיינא דמלכא -
עיין בחגיגה, שכן קרה. ויש לדון, ששם נותן סיבה אחרת לו.
** פטר חמור -
לכאו', משמע שאומר שכן היה, ולא שכן יהיה. אם כן, מעניין איך בזה ילך אחר הפתרון, שצריך ללכת אחריו למפרע.
** אשתך שכבא -
לכאו', כבר אמר כן. לכאו', צ"ל קאי על אשה אחרת. אם כן, בין הכל (אם לא נניח שיש אשה שנכפלה), נמצא שנשא רבא ארבע נשים.
** אפדנא דאביי -
נראה שאולי לכן סבר שלא היה לו לאביי לעשות מעשה בעצמו, שכבר היה קצת סמין שימות. וא"צ לזה.
** בדדך -
קצת צריך ביאור איך לא הבין שהיה טוב אחר שנתן ממון ורע קודם שנתן ממון. ותחשב.
נ' שאולי ב"ה עצמו חשש שיבין, והיו בין אלו כמה חלומות שפתר לטוב קצת או לרעה קצת, ורק לא הזכיר אותם גמ'. ותחשב.
ויותר צ"ב למה פתר לרע אם לא נתנו לו שכר, אם לא רצה שיבינו לתת שכר. כמו כן, צריך ביאור למה נתן רבא שכר, אם לא כדי להטיב את חלומות שלו.
** נו: הא דרכבו הוא לתורא -
אז, נמצא שיש שש דברים שנאמרו בשור. ותו"ת. (אולי זה נחשב דבר שנאמר בו, ולא דבר שנאמר בשור. וצריך לבאר.)
** נז: עתידים -
לכאו’, סובר שמקבלים גרים בימות משיח. עיין בגמ’ יבמות (סוף פרק שני).
** בשעת אפיך -
ואם תאמר למה זה שייך לחולה. ונראה שמכוון למה שאומר גמ' שחולה לא צריך מזון, שהחולה שלו זן אותו. אז, כיון שאוכל לחם, צריך לומר שלא חולה עוד. ותו"ת.
** רובה עובדי כוכבים -
צריך ביאור, שאף להם אסור לעבוד ע"ז. אולי אף סומך על מה שאינו ממש עבודה זרה, אלא מנהג אבותיהם. גי"ל שזה אחר ביטול שבע מצוות לבני נוח.
** לאבותינו -
קצ"ב, שלא היה דניאל אבותינו. אולי היה אבותינו, שבמשך הימים, מסתמא כל אחד בא ממנו. גם יש לומר שזה היה טוב לכל בני ישראל שמחמת זה היה דניאל יכול להושיע לבני ישראל.
** נח. נתן בו עיניו -
מעניין שהיה יכול לעשות כן, אף שהיה סומא.
** לשמשני -
עיין ביבמות שאומר שהכל לא נברא אלא לשמש לת"ח.
** בר קטלא הוא -
צריך ביאור איך השיב. ואולי כך היו דיני מדינה (או שכך פשוט על פי שכל).
** כחלינהו -
לומר לו שאף סומא יודע יותר ממנו, ואז אין צורך לעיניו.
** נח: שובר חצי גופו -
לא ר"ל ששובר את גופו בחציו, שאם כן שיטת רבי יוחנן לא מובן.
** שובר -
משמע שהוא האנחה עצמו, ולא מה שגורם אנחה, שאי לאו הכי, מוכרח לעשות כן. ויש לדון, שאולי יכול לשנות מה שחושב, ואז לא יאנח.
** נט. וליהדר -
קשה ל"ל מהדר של זה לזו ושל זו לזה.
** תחת השמש -
מעניין שנחשבים הכוכבים תחת השמש.
** ברקא -
נ' שהוא אותו לשון שאומ' גמ' ביומא "ברקאי."
** ופליגי -
יש לדון במה חולקים. אולי מה שאומר שמברכים עליו חולק עליו, שלא נמצא עוד. ויש לדון, שאולי אומר הלכתא למשיחתא. ויש לדון, שבכ"מ גמ’ מק’ מזה. גי"ל שמק’ על מה שפ’ שוהא טהרו, שאם זהו טהרו, הרי נמצא, ואינו רק לפני חורבן בית המקדש.
** נט: מאיהי דקירא -
היה נראה לומר שאולי אין חולקים במציאות, אלא שמשם שינו את המקום, וזה גרם שינויים במקומות אחרים. דנים אם נחשב אותו שינוי שינוי הבא ע"י אדם או לא. ותחשב.
** אימא האל -
ק"ק ל"ל לימא כל ההודאות.
** אית ליה -
ק"ק ל"ל יאמר אותו כשיש לו קרקע שלו. אינו מפני שכבר ברך שהחיינו, שלא יברך כן על כל ירידת גשם, אלא רק בפעם שקונה. ותחשב. אולי זה כולל כל טוב שבא לו מחמתו. יש לדון, אז, אם בירך ושוב נתן שותפות לאחר, אם מברך על גשם.
** ס. כח דהתירא -
אין זה כל כך מובן למה שפרש"י בביצה, שהרי כאן, היה יותר ק לומר שלא צריך לברך. ותו"ת.
** בבת אחת -
ואם תאמר אי אפשר לצמצם. וי"ל שמסתבר שאפשר לדברים לצמצם, אלא שלא נדע שהוא מצומצם, אף שנראה מצומצם. גי"ל שלא צריך להיות ממש מצומצם, כיון ששני המקרות לא נעשים ברגע אחד, אלא נמשכים, ויכולים להיות קרים באותו זמן של המשך האחר. ותחשב.
** ס: כי מנח -
נמצא שאין זה כמנהג רא"ש. אולי סובר כאשכנזים שלא מסדרים ברכות כך, ומסתמא סוברים שאינו אומר אותם על הסדר. גי"ל שסובר שסדר זה שייך רק אם עושה הליכות בוקר שלו כך, וגמ’ נקט אותו כיון שכן היו עושים. ותו"ת.
** כל דעביד -
אולי זה בא משיטת רבו נחום איש גם זו (שבועות).
** סא. והא קא חזינן -
לכאו’, יודעים שיש להם יצר הטוב כיון שלא מנגחים בכל הזמן.
** והא קא -
נמצא שיש יצר הרע ויצר הטוב לבהמות.
** פורענות דמבול -
יש לדון ל"ל בכלל, “בקללה מתחילים.”
** למאי דקאמר ר"נ -
מה שאמרו סתם משמע שרנב"י הוא סתם ר"נ.
** שני כליות -
כמובן, צריך ביאור מה קורה לאדם שיש בו רק אחד.
** סא: צדיקים יצר הטוב -
לכאו’, זה קצת פשוט.
** בכל נפשך -
לכאו’, זה לא חולק על דרשה שלעיל.
** במקום שאין שם גדר -
יל"ד ל"ל נתמעט מרואה. ויש לומר שהוא גדר נמוך, ויכול לראות על גבו.
** סב. רואים שהיה
ר"י מדבר עם ב"ע. צ"ב, אז, איך היה העולם שמם אחר מיתת תלמידי ר"ע. אולי היה ב"ע ת"ח רק אחר זה.
** אוכל בה -
צ’ לציין לגמ’ בנדרים (“למה אתה מאכלני את צואתך") שמשמע שהיה אוכל עם היד שהיה מקנח בו.
** שמתעטש -
אם צ’ להרחיק כך מאחרי גדר, צ"ב איך ב"כ שלנו מותרים.
** סג: להבחין -
נ’ שלכן זכה ר"א, שגמ’ ביומא אומר שלא היה ר"ל אוהבו. ויל"ד, שמשמע מגמ’ שהיה רואה והיה מרא דארץ ישראל בימי ר"ל. אולי איה"נ, אבל לא היה כן בתחילת ימיו.
* Footnotes
[fn:1] אין זה מוכרח, שאפשר שיש סיבת האיסור, אלא שנדחה כיון שיש יותר סיבה למצווה.
[fn:2] על צד זה, יש לדון אם כשאדם נטמא, רק נתרבה זה על זה, או שהוא סיבה לשניהם, או סיבה באחד גורם שינוי בשאר. ותחשב. על הצד שבא ממילא, יש לדון אם סילוק זה הוא הסיבה, או מה שאינו שם הוא הסיבה. גם יש לומר שיש לעולם סיבה, אלא שנמנע מן הטומאה.
[fn:3] ר"ל, ללשון פנייה, שהוא עזיבה.
[fn:4] גם אפשר לומר כצד שלישי, ולומר שסילוק זה ממילא גורם זה, ומטהר גורם סילוק הטומאה.
[fn:5] והוא התנא של המשנה
[fn:6] בענין שחיטת מחצה; כן אני חושב.
[fn:7] כוונתנו הוא שכל מי שרוצה לישון ליותר מחצי הלילה, ואף רבים מן הישנים לפחות מזה, ישנו בחצות.
[fn:8] ר"ל, מי שיביא ראיה יניח שקרא של רחמים הוא טוב, אבל לא טוב די. אז, מהני רק לתלמיד חכם. הדוחה יאמר שלימודו עושה דבר חלוק, ולאותו דבר חלוק היה חברו העם הארץ צריך קריאת שמע.
[fn:9] יש לציין גם כן לגמרא יבמות (פרק הערל) שהיה ר"י מתפלא כשאמר ר"א דרשה נאה מאד. היה אפשר לומר שלא היה ר"י מחשיב ר"א כל כך.
[fn:10] ובאמת, צריך ביאור למה. היה אפשר לומר שהוא מפני שמלאכים עושים כן, אבל כמובן, אי אפשר לומר כן בצד זה.
[fn:11] ר"ל, אין רואים יותר מזה מכאן. עדיין אין לדייק למעט, שהרי אפשר שמה שנקט מי שרגיל לומר לו שום הוא שאז יקדים לו שלום, אבל לאחר אין ענין כל כך להקדים שלום.
[fn:12] יש לדון אם גזרו כן רבנן (צריך לחפש), שהרי שינה הוא רק גזרה להפחה, ואז, זה גזרה לגזרה.
[fn:13] אלא אם כן נאמר שהוא בכלל אבוזריא של עבודה זרה כיון שיש בו קבלת עול מלכות שמים.
[fn:14] ויש לדון, שיש אמוראים שסוברים שלא יצא. ואולי אף הם בציור כזה. באמת, כל שיטתם צריך ביאור, שלכאורה לומדים ממה שבית שמאי פוסלים שיטת בית הלל כשבית שמאי מחמירים. ותחשב.
[fn:15] לא משמע שקאי על תורה.
[fn:16] באמת, יש לדון אם מחשבה ר"ל מחשבה על איזה ברכה או מחשבה על איזה מין אוכל הוא אוכל (שחושב עליו להיות מין של "שהכל"). ותחשב.
[fn:17] אבל, צריך לדון אם סיבה שלמעשה לא חייבו חכמים לומר פרשת בלק יפטור אף אלו, שאולי אף אלו טורח ציבור. יש לדון, שאולי יש יותר סיבה לומר אותם, או שאינם כל כך גדולים או קשים, או שלא מוסיף על כל כך, שבלי זה, היו רק שני פרשיות.
[fn:18] ויש לדון, שעבירה לכאורה אינו כל כך עיקרי. אולי הוא מצווה גדולה.
[fn:19] ובאמת, אפשר שלכן צריך הלכה למשה מסיני (רש"י כ’ שכל היג’ מדות הם הל"מ) לדרוש קל וחומר, שלעלם יש פירכא זה. ויש לדון, שבדרך כלל, י"ל כ"ז אכניס.
[fn:20] דע שזה יכול לעשות שהוא דחוי או הותר, שיכול להיות שלא הטריח אותוה
[fn:21] או שמחמת זה לא מקיים. ותחשב.
[fn:22] עדיין יש לדון ל"ל יכול לעשות כמו שעושים בני אדם ויתנה. ואולי כן עשה, והעדות רק אומר שהיה לו צד כך. דחוק, שלא משמע כן.
[fn:23] יש להעיר שכאן אינו כשאר ציורים, שלא רק, אולי, אין הקיום כל כך טוב, אלא אף יש רע שנברא בקריאה זה. ותות
[fn:24] שוב ראיתי בתוס’ שלא פרש ההוכחה כמש"כ.
[fn:25] אגב, ואם תאמר כיון שר"א לעולם אומר דברים בשם רבו, קשה ל"ל אומר בכל זמן שר"א אומר משום…. ויש לומר כמו שאומר גמרא ביבמות, שהוא שכיון שידוע שכל מה שאמר בא מרבו, לא היה צריך להזכיר כן. שם, הוא כשיש רב אחד שממנו אומר הכל. אולי כן הוא ברבי אליעזר. ותחשב.גם, כמובן, צריך להגדיר מה בכלל מה ששמע מרבו, שהיה אפשר לומר שלא שמע ממנו בפירוש, אבל שמע שדרש קרא זה באופן זה, והבין לדרוש אחר באופן דומה…, ואז אינו ממש בשם רבו. אז, אין לו לומר בשם רבו. ותחשב.
[fn:26] ויש לדון, שאולי רק אמר שאר טעויות אגב זה, אבל לא היה מזכיר כל זה כלל אם אין שום שינוי. מה שמזכיר שאר טעויות הוא אולי אגב זה, או אולי כדי להוכיח שהוא נכון, והוא שזוכר כל כך טוב עד שאף זוכר טעויות אלו.
[fn:27] אלא שיש לדחות ששואל כן כיון שנשנים יחד במשנה.
[fn:28] אלא שהיום בני אדם לא חוזרים לכוון, כיון שמסתמא לא יכוונו. ויש לדון, שזה מסתבר בש"ע, שאז אומר ברכות, אבל כאן לא אומר שום ברכות, ולמה לא יחזור. ויש לדון, שנצטרך לחזור עוד ועוד ועוד.
[fn:29] עיין בהוספות שכתבתי שענין ברכת הודאה (ברכת נהנהים) הוא שה’ נתן לו הנאה, ואז אף הוא צריך "לתת" לה’ דבר שה’ "רוצה.” אותו דבר הוא ברכה, וצריך לברך את ה’. וצריך לחשוב למה יותר טוב להזכיר מה שאוכל. אולי, אז, בטוח שאין הברכה פחותה מהנאה שלו.
[fn:30] זה הולך למש"כ לעיל בביאור ענין ברכת נהנים.
[fn:31] קאי על ציור שיש רק שנים.
[fn:32] קאי על ציור שיש שלש.
[fn:33] אבל שוב ראיתי שרש"י מבאר שיוצא אם אמר אחד, ורק ר"ל שיכול לחתום בכל מה שרוצה. אולי, אז, ברייתא לעיל מדבר במי שסובר שצירך לחתום באחד, או שבוחר לחתום במושיע.
[fn:34] קצת תלוי ג"כ באם נשאר כן כשהיו מצורעים הולכים אחריו.
