* ב.
* כדי
*ויתחייב כרת*- יש להעיר שגמרא אומר ביבמות (קרוב לדף קיד, וקרוב לדף פח)
שלא גזרו יותר על איסור כרת מעל איסור לאו. אם כן, קשה למה יאמר כן רש"י
כאן.[fn:1]
* ב:
* אדכי
*השמש*- יש להעיר שהיה יותר נראה לומר שמה שנפנה אינו השמש, אלא היום,
שנשתנה להיות לילה. מצאנו שיום, לפעמים, יאמר שמש, כרש"י.
היה אפשר לומר שהוכחה של רש"י הוא שסובר שלשון פנייה לא יכול להיאמר על
יום, אלא על שמש. עיין בשי"ח שי על גמרא.
* מברייתא
*עיין* במה שנכ' בע"ה בשי"ח ש"י על גמרא (ד"ה מברייתא). זה אי אפשר לרש"י
זה. אז, לרש"י עדיין צריך ביאור. צריך לומר שנקט ברייתא כיון שהוא אומר צאת
יותר בפירוש.
ויש לדון, שאף אם זמן משנה לא היה צאת, לכאורה, לא היה דבר אחר שיכול
להיות. עדיין צריך לומר שאין זה בפירוש די.
* ג.
* ואשה
*והשוכבים יחד*- משמע שהכל מתעוררים אז, אלא ששנים שישנים זה עם זה מדברים
זה עם זה. על זה, נראה שפשוט להעיר שני הערות:
1. קצת קשה למה נקט גמרא אשה ואיש, ולא רק אמר שהוא זמן שבני אדם מתעוררים.
2. קצת קשה למה לעולם יצטרך אדם סימן זה, שאם הוא נתעורר, אז הגיע אותו
זמן. ויש לדון, שאולי דנים במי שלא ישן. גם יש לומר שלא יכולים לפשוט כן
על פי איש אחד, אלא צריכים לראות שקרה כן להרבה בני אדם.[fn:2]
אפשר לתרץ ראשון לומר שלא כל זמן שאדם מתעורר הוא מדבר עם חברו, ורק אחר
זמן מסויים.
לולי רש"י, היה אפשר לומר שאינו הזמן שרוב בני אדם מתעוררים, אלא שבאותו
זמן מחצה בני אדם מתעוררים, ואז אחד מן השנים יתעורר, ויעורר השני. אין זה
מתרץ כל הקושיות, שהשני עדיין קשה. ותחשב.
* תפלה קצרה
*הביננו*- עיין לקמן, שחולקים בזה רב ושמואל (כן אני חושב).
* ושמר
והמתין- גם היה אפשר לומר שהיה שומר לו ממש, ממזיקים, וכדי שלא יפול (כיון
שהיה לו כוחות כך, שהיה אליהו), ומחשד, שיראו בני אדם שני בני אדם.
ויש להעיר שיש גורסים בגמרא "והמתין.” אם כן, אולי מוכרח כמה שכתבנו, ולא
כמו שאומר רש"י, שלרש"י, נמצא שכופל את עצמו.
* ג:
* בחדתי
*שנפלה מחדש*- גם היה אפשר לומר שלא נפלה מחדש, אלא שהיה נבנה מחדש. אז,
נראה שהוא חזק, ואף שחלק ממנו נפל. צריך ביאור למה מה שנפלה מחדש עושה ששאר
יותר חזק. נראה שאחר שנפל, יש עוד סיבות שמתחדשות וגורמים לו ליפול (הכל
הולכים בה, עשבים צומחים וגדילים לתוכה, רוח נכנס, וכדומה). אז, יותר זמן
יעשה שסיבות אלו יפילו אותו יותר.
*ור' נתן*
*בתחלת שעה שלישית*- נמצא שרש"י סובר שזמן שלש שעות ר"ל עד תחילת שעה
שלישית. יש בזה נפק"מ להלכה, כמובן; וחושב אני שאין בני אדם מקפידים כרש"י.
נראה שהוכחה של רש"י בא ממה שאומר שקדמו עיניו משמורות, אף שהיה לפני שש
שעות של לילה, ושלש של יום. אם כן, היה יותר משני אשמרות. צריך לומר ששעה
שלישית ר"ל בתחילת אותו שעה. ויש לדון, שהיה קל לתרץ שיש בכלל זה אשמורות,
אלא שהוא יותר. נראה שהיה קשה לרש"י ל"ל יזכיר את היתר.
אגב, נראה שאולי בזה חולקים שני השיטות בגמרא. אם כן, אולי אין כל כך
נפק"מ, אולי, ממה שמפרש רש"י כאן, שאולי אין הלכה כאותו מד"א (וצריך
לעיין).
* נשף
*קפץ ועלה*- מה שאומר מילה זה על יום ועל לילה משמע שיום ולילה שניהם הם
דברים, ולא שאחד הוא מה שאינו השני. עיין בשיח שי על גמרא (ב:) שדנינו בזה.
אפשר שזה היה דיון של גמרא שלנו כאן.
ודע שיש לדון אם יש דבר הנקרא "יום,” והוא זמן מיוחד, או שהוא רק זמן שיש
בו מאורעות מיוחדים. ותחשב.
* ונמלכים
*כדי שיתפללו*- עיין לקמן, שרש"י מבאר שהיו שואלים לאורים ותומים אם
יצליחו. כיון שכבר ידעו שיצליחו (שלא היו לוחמים, לכאורה, אם ידעו שלא
יצליחו), למה הוצרכו לתפילות. יש לומר שלפעמים לא ענה, או שענה שתלוי
בתפלות. גם יש לומר שמה שענה היה נרשם ע"י אותם תפלות, שתפלות עשו שינחצו,
ואז יאמר כן אורים ותומים. ותו"ת.
* ד:
* זה הסומך
*אוהבו*- משמע שאין הענין שעושה תפלה יותר טוב, אלא שרע לומר ק"ש ולא לומר
אחריו תפלה. יש להעיר שמדאו', אדם אומר ק"ש, ולא מתפלל. ותחשב.
אגב, לכאורה, גם הוא יותר טוב לתפלה, שהרי הוא כדופק על דלת של ה', ומסתמא
זה טוב לתפלה. משמע שאין ענין זה די לחייבו (או על כל פנים אינו כל כך סיבה
גדולה כסיבה שמזכיר ירושלמי). ותו"ת.
אפשר לדחות שכל שמ"ע יש בו ממילא הקשת דלת, שהרי הוא מתפלל לה'. ותו"ת.
* ה.
* ואם תלמיד חכם
*לחזור*- צריך ביאור למה נקט זה, ול"ל נקט ללמוד. נראה שרש"י סבר שחידוש של
גמרא הוא שדיו בלימודו, ולא שלא צריך ללמוד קודם (עיין בשיח שי על גמרא
כאן). סובר שצריך ללמוד ממש קודם שהולך לשכב. אף תלמיד חכם לא לומד ממש אז,
אלא שבמוחו חוזר על מה שלמד. רש"י אומר שעל לימוד זה קאי גמרא. ותחשב.
* זה מקרא
*שמצוה*- משמע שסובר שדרשה של פסוק זה אומר שה' נתן להם מצווה ללמוד כל
אלו. אם כן, נמצא שיש מצווה מיוחד לכל אלו, ואינו רק מצווה אחד ללמוד הכל.
ויש לדון, שאולי רק מזכיר שכולם הם בכלל חיוב ללמוד.
על כל פנים, יש להעיר שלא משמע שנתן למשה אלו בהר סיני. ותחשב. על פי זה,
יכולים להשיב למה שהערנו שקשה על מה שאומר רש"י שגזרה שווה צריך מסורה כיון
שנלמד מסיני, שכאן משמע שהכל נלמד. לרש"י כאן, לא קשה, שרק נאמר מסיני שיש
מצווה ללמוד כל אלו, אבל לא אומר שכולם ניתנים. ותחשב.
לשון גמרא "מלמד שכולם נתנו" לא משמע כן כל כך, וצריך לומר שאומר שמצוותם
ניתן. (ואל תתמה איך מצווה ניתן קודם הספרים עצמם, שיש לומר שה' צווה
שכשיהיה להם אותם ספרים, ילדמו אותם.)
* התעיף
*אם תכפל*- לא ידעתי מהו לשון "תכפל" כאן.
* אשרי
*לבוא*- מעניין, שמגמרא היה נראה לומר שרק לא מעכב אותו מללמוד, ולא שגורם
לו ללמוד. ויש לדון, שאולי "לבוא" רק ר"ל שלא יעכב.
* ה:
* ביר
*לעגמת נפש*- לולי רש"י, היה אפשר לומר שהוא לנחם בני אדם כמו ר"א. אפשר
לדחוק שרש"י ר"ל שהוא לבטל עגמת נפש של אחרים. ותחשב.
*וגברא רבא*- קשה, שבוודאי חטא ש"אין צדיק בארץ אשר לא יחטא,” והרי רש"י
לעיל פירש שיסורים של אהבה לא באו על חטא. אולי מסתמא עשה תשובה. יש לדון,
שלמעשה אף משה היה צריך עונש. אולי מה שקרה למשה לא היה עונש, אלא שלא היה
יכול לבוא מפני חטאו לסיבה אחרת. יש לדון מהיכי תיתי, אז, שזה היה עונש.
ותחשב. ואפשר ששל משה היה של אהבה. קשה, שלא היה רוצה ה' לתת לו מתחילה.
ויש לדון, שאולי היה כל כך קדוש שלא היה צריך לו, אבל לאחר כן היה צריך לו.
לולי רש"י, היה אפשר לומר שהוא כמחוצף כיון שהיה מראה שעבר ונענש (כמו
שאומר גמרא "חציף עלי מאן דמפרסם חטאיה"). ותחשב. ויש לדון, שמצורע קורא
"טמא טמא.”
*דהוו*- משמע שיש כפרת עוונת ביסורים של אהבה, אף שלעיל משמע שלא באו מחמת
עבירות. אולי ר"ל שעבירות לא היו מביאים עונשים כיון שהם כל כך קטנים, אבל
למעשה מתכפר ומביא אותו יותר קרוב לה' אם באו. ותחשב. אולי זה מיישב שני
הדיבורים.
* סמוך למטתי
*לעסוק בתורה*- נמצא שאין ללמוד קודם תפלה. יש לדון, שהרי קבעו בתפלה לימוד
תורה (כמו קרבנות וכדומה), שבפשטות הם כדי שילמוד תורה בכל יום. אם כן, היו
להם לקובעם אחר שמונה עשרה. אולי אין להניח שבני אדם יאמרו אותם אם הם אחר
שמ"ע, שיצאו כבר מבית הכנסת לעבודתם, שלפעמים תפלה הוא מאוחר. יש לדון,
שהיום אין אומרים אותם, ולא הועילו כל כך בתקנתם. ויש לדון.
גם אפשר שאולי יש לחלק בין לימוד תורה לעסק בתורה, שאולי עסק הוא עיון
בתורה.
באמת, קצת צריך לבאר למה הוא דבר טוב לסמוך את זה לקומו. אולי חושש שמא
יטרד וישכח להתפלל. אם כן, החילוק שכתבנו מובן. גם, לכאורה, כיון שהוא חלק
מן התפלה אין לחוש כל כך שלא יתפלל.
* צפון
*או למזרח*- איני יודע אם רש"י מסופק או שאומר שיש שום מחלקת בזה (איני
יודע, שאני רק זוכר גמרא בבבא בתרא שדן אם הוא במערב או בכל העולם) או
שלפעמים הוא כאן ולפעמים כאן. ותחשב.
* ו.
* למצוותי
*לגמול חסד*- לכאורה רש"י מפרש שקאי על זה כיון שהוא גמילת חסד לחברו. אם
כן, לכאורה כן הוא לכל גמילת חסד. ויש לדון, שאולי קאי על זה, כיון שזה חסד
שבא מהמתנה. ויש לדון, שכלאורה יש הרבה כזה.
* קדמה
*כל העשרה*- משמע שעדיין צריך שמקצתם באים. יש לדון מהיכי תיתי.
גם יש להעיר שאם כרש"י, צריך לומר שלא התחילו כבר ללמוד, שאי לאו הכי, פשוט
שכבר בא שכינה. ותו"ת.
* ו:
* ואין עונה
*לענות דבר שבקדושה*- אז, לכאורה, “אין איש קראתי" ר"ל שאין איש קורא דבר
שבקדושה. זה אומר שדברים שבקדושה, בדרך כלל, יש להם שני חלקים, והם האמירה
והענייה, כמו קדיש, ואמן יהא שמיה רבא. כשאין עשר, בטל האמירה ובטל הענייה.
ויש להעיר שאם זה כן, קצת קשה למה רש"י אומר כן רק על עניית דבר שבקדושה.
אולי לא יודעים שקאי על דבר שבקדושה עד שמיירי בענייה, שאין עונים על דברים
חוץ מדברים שבקדושה. ויש לדון, שעונים על ברכות וכדומה. ויש לומר שאין הדרך
להתפלל בקול, עד שיוכלו לענות אמן, אלא אם כן יש ש"ץ ובעשרה.
*שיעור*- לשון זה מעניין, שלכאורה ה' עצב כיון שאין עונה, ולא כיון שאין
שיעור שיענה. אם נאמרש רש"י לא סובר כמה שכתנו בדיבור שלעיל (ד"ה לענות),
יש לומר שהבעיה אינו מה שאין ענייה, אלא מה שאין אמירה. ותחשב.
גם יש לומר שיש קצת בזיון למקום שאין עשר בני אדם באים שם לתפלה. אז, לא
תלוי באמירת דבר שבקדושה כלל. ותחשב.
* אחורי
*מזרח*- איני יודע למה רש"י מזכיר זה, שלכאורה לא נוגע למה שאומר גמרא.
* ח.
* לעת מצא
*מצוי לו*- גם היה אפשר לומר שר"ל שלא יהיה קשה לו לפנות, אלא שלשון מצא של
קרא לא משמע כן. ותו"ת.
* ח:
* משום קלקול
*ימאס*- גם יש לומר שיאסור את המאכל, שיהיה מעורב עמו דמו, ואולי לא יהיה
בו כדי ביטול. אפשר שקל למצוא הדם ולסלקו. קשה, אז, מה מאוס יש בו. אולי
ידעו בני אדם שהיה בו דמו. גם יש לומר שלא יזכר להסירו. אם כן, עדיין קשה
ל"ל אומר משום איסור.
* אסור
*שבמזרח*- עוד מזכיר רש"י היות הפתח במזרח (כמו שהזכיר לעיל ו:). צריך
ביאור למה זה נוגע לו. ותחשב.
* ט.
* או דילמא
*היכי דאינס*- לכאורה, יהיה נפק"מ אף אם לא איתנס, שיש נפק"מ באם הוא מזיד
גם כן. ויש לדון, שאלוי גזרו רבנן שלא יקרא אז, כדי להראות לבני אדם שזמנו
קודם לכן. לא נראה. ותחשב.
על פי זה, היה אפשר לבאר גירסא שאומר גמרא "מותרים,” שלא רק בא להפקיע מצד
שאיו מקיים מצווה, אלא מצד שנראה כמקיים מצווה (או מקיים מצווה דאורייתא),
ואז גזרו רבנן שלא יקרא. ותחשב.
* ט:
* בין
*לא עלה עליה יפה*- משמע שעלה עליה קצת. אם כן, אינו רק קשה מפני שצריך
לחלק בין שני חתיכות שאינם כל כך גדולים, ואז אין כל כך לראות, אלא הוא קשה
כיון שצריך לחלק בין מקום שהוא נצבע יפה למקום שלא נצבע יפה.
* יא.
* אלמה
*כמו למה*- נראה שאולי הוא נוטריקון של "אז למה.” ויש לדון.
* לאחד
*משל שלך*- זה לשון מוזר; לכאורה, ר"ל שמה שאומר לך הוא משל שלך- משל
לציורך- והוא שדומה.... דחוק קצת בלשונו. ותחשב. אולי משל רק ר"ל דבר שכנגד
דבר אחר, ואז משל ונמשל שניהם נקראים משל. ותחשב.
גם נראה שאין "שלך" אומר שלך הרגיל (ר"ל, דבר שהוא נקנה לך), אלא נקרא עם
דומה, והוא המשל שהוא לך דומה, ר"ל, שלך הוא דומה אותו משל.... אם כן, המשך
דברי רש"י אינם כל כך טובים. ותחשב.
* יא:
* אף לגמרא
*שהיא עיקר*- אם כן, לשון "אף" קצת קשה, וצריך לומר שהוא שאף מה שאומרים
אחרים שאינו צריך לברך..., ולא אף מה שאינו כל כך מסתבר לברך עליו צריך
לברך. ותחשב.
* וברכת
*לא יצא*- קשה, אז, למה קראו אז. אולי קראו כן אחר הזמן. א"כ, קשה למה קראו
כלל אז. גם יש לומר שיש קצת קיום קודם זמנו. זה מחודש. יש לציין לכסף משנה
שאומר שזמנו הוא רק דרבנן (כן שמעתי). גם יש לומר שהוא רק זכר למצווה. ויש
לדון, שבכל שאר ימות השנה מקיימים המצווה, ואז לכאורה לא צריכים סימן.
גם קצת מוזר שאין להם פנאי לאומרו לאחר זמן בבקר. אולי הוא מפני שצריך
כוונה, ואין להם פנאי לכוון. ותחשב.
* יב:
* בחיר ה'
*בת קול אמר*- צריך ביאור מהו ההוכחה, שאולי זה רק אומר מלך, והם קראו לו
מלך כיון שהיה מלך. ותחשב. אולי אז היו לו לקרוא לו רק מלך; שם זה הוא שם
של כבוד.
* כבן
*אותו יום*- צריך ביאור מהיכי תיתי שהיה באותו יום, ולא ביום אחר, שהיה
אפשר לומר ששנים אחר זה, שהיה עדיין כבן שבעים, אמר שלא זכה עד שדרשה בן
זומה באותו שנה. ותחשב על זה.
* יג.
* שמע מינא
*מתכוון לשם מצות*- משמע שלא צריך כוונה למצוה מיוחדת, אלא כוונה למצוות,
דהיינו לקיים דעת ה'. ויש לדון, שאולי אומר רש"י לשון זה רק מפני שקאי על
"מצוות צריכות כוונה.” ותחשב.
שוב ראיתי שבעוז והדר, גורסים "מצווה.” זה יכול להיות, נראה לי, כשני
הצדדים, שיכול להיות שצריך לכוון למשצוה סתם או לאותו מצווה. ותחשב.
* יד.
* מהו שיפסיק
*לשאלת שלום*- משמע שרק שואל לענין שאלה, ולא לענין השבה. יש לדון מהי"ת.
ויש לדון, שאולי כל זה נקרא שאלה, שאו שאול לאחר או משיב לשאלת אחר. ותחשב.
גי"ל שמשיב בשאלת שלום (ר"ל, אחד שואל, “איך אתה,” והוא משיב, “איך אתה,”
או כעין זה).
* מהו שיטעום
*לדעת אם צ'*- משמע שבלי זה, לא יכול לטעום. ק"ק ל"ל, שלכאורה סברות גמ'
עדיין שייכים. אולי מה שעושה שאינו נחשב מעשה אכילה הוא שאל עושה אותו כדי
לאכול אותו אלא כדי לדעת אם התבשיל טוב. צריך לבאר. גם יש לומר שלא היה צד
לאסור בלי זה, שחלק מן הצד לאסור הוא שגורם הנאת אכילה, שיאכל, לאחר זמן,
התבשיל. צריך להגדיר ולבאר.
* יד:
* ומתני
*לעסוק*- עיין בב"ח.
* טו.
* תוד"ה להודיעך
*אין כאן שום חידוש*- צריך ביאור, שלכאורה, אין חידוש ברבי יוסי, שאם דורש,
פשוט שמעכב. ויש לומר שלא כל כך פשוט שכל קרא יעכב. זה מחודש. גם יש לומר
שהוה אמינא שלא דורש קרא, ויש סיבה דרבנן שסובר שלא יעשה כן לכתחילה. זה גם
כן מחודש.
אבל, מה שהוא יותר קשה מזה הוא שאותו הוה אמינא שמוציאים ממנו לרבי יוסי
היינו צריכים להוציא ממנו לרבי יהודה. אז, תירוץ של תוס' קשה מאד, שאומר
שהוה אמינא שהיינו צריכים להוציא ממנו לרבי יהודה אינו מובן, ואף שמוציאים
מאותו הוה אמינא לרבי יוסי.
ואפשר שאין הכי נמי, וכיון שגמרא אומר דבר פשוט, תוס' אומר שאין גמרא צריך
לבאר כוח התירא, שרק אומר אותו חידוש כיון שהוא יותר מחודש, אבל כאן, שניהם
פשוטים. ותחשב.
* תרתי
*ש"מ נמי*- וכן, לכאורה, להיפך. נמצא ש"שמע" משמע שלא צריך כלום אלא לשמוע.
אז, כל לשון מהני, אלא שישמע. כמו כן, יש לומר ששמע אומר שצריך להשמוע
ולהבין. אז, צריך לומר שצריך לשמוע, וגם צריך לומר שיכול להיות בשפה חוץ
מלה"ק, שאי לאו הכי, לא היה צריך להבין. ותו"ת.
* טז.
* מעין
*יא*- צריך ביאור, אז, איך מגיע ליח', שיא' עם ג' וג' הוא רק יז'.
* טז:
* ותביט
*עיין במה* שפירש. גם יש לומר שאמר שאף שתביט, עדיין תרחם. ויש לדון, שאז
היה לו להתפלל שלא יביט. אולי זה היה יותר קשה לקרות. ותחשב.
* אבות
*לישראל*- משמע שבא למעט עבד, שהרי גמרא ממשיך לומר שיכולים לקרוא כן
לעבדים חשובים. יש לדון למה היה מותר לקרוא כן לעבד, ולא לישראל. יש לומר
שבעבד, כבר ידוע שלא חשוב, ואז אין שם כזה עושה שנראה כל כך חשוב. ויש
לדון, שזה מניח שמה שאינו נקרא כן הוא שנראה יותר חשוב לו, ומביא לו חשיבות
יותר מן הראוי, ולא שאותו מילה לא ראוי לו, כיון שהוא מילה של חשיבות. נראה
שאולי אם נאמר כאותו צד, יש לומר שמילה של חשיבות תלוי בעל מי נאמר, ואינו
מילה של חשיבות אם נאמר על אבד. ויש לדון.
ועדיין קשה על רש"י, שאם מניח שבעבדים אפשר, וכך הוא גמרא לקמן, צריך לומר
שלא רק מיירי במה שחושבים עליהם להיות אבות, שהם מיסדים לאומה שלנו, אלא
שקוראים להם בשם אבא. קשה, שמצאנו כמה בני אדם, כמו אבא שאול, ואבא יוסי,
ורב, שנקראו בשם אבא. אולי סבר שכך היו שמם.
גם נראה שאפשר לומר שמה שאומר רש"י אינו שלא עושים כן למי שהוא ישראל, אלא
שמה שאין קוראים להם אינו שם אבא, אלא שם אבא לישראל, דהיינו אב של אומה.
דחוק קצת בלשונו. ותחשב.
כן נראה מוכרח ממה שממשיך רש"י לומר, “כן היו רגילין... אבא פלוני....”
ואולי זה בגוי. ותחשב על זה.
* יז.
[*ושמא*
*גם היה* אפשר לפרש ששמא תאמר ששלי יותר טוב משלו, אינו כן, ששנינו לומדים
כפי יכולתינו.
* ערום
*בכל מיני ערמה*- גי"ל כלשון "ערום" ורצה לומר פשוט ובלי תחבולות.
* הועשה
ואם תאמר כיון שכ' ראשון למה צ' שני. ויש לומר שר"ל שהוא שלא לקיים. וק',
אז, למה ילמד שכמובן, לא רוצה בשכר. אז, צריך לומר שלומד לקנטר.
ודחוק.[fn:3]
* ובלבד
*מנחות*- קצ"ב למה מזכיר כן. ויש לומר שמדיון בו נראה שאינו כל כך פשוט,
ואף שיש משנה בפירוש. אז, צריך לפרש שאין משנה כל כך בפירוש בו, אלא בדבר
אחר.]
* יז:
* שבחא
*אלול*- משמע שהיו לומדים הלכות החג שלושים יום קודם, ולא רק של פסח. ויש
לדון ל"ל עשו כן בעצרת. ויש לומר שני דרכים. אולי אין חיוב בשאר חגים כמו
בפסח, אלא שעשו אותו אף בלי חיוב, כיון שרצו שידעו ההלכות. גי"ל שיש חיוב,
אבל רק לא באו כולם אל רב אשי בשבועות. גי"ל שיש חיוב רק בחג ופסח כיון שיש
להם כמה וכמה דינים.
* מי שמתו
*חתן*- יש להעיר שכאן טרוד בדבר שיכול לעשות, אבל בחתן אינו לעולם כן. אם
כן, לא ממש דומים. (עיין בכתובות כשדן בדין חתן, שכוונתינו כאן הוא לומר
שגמרא שלנו כאביי, וכאן יהני אף לרבא.)
אם פטורים אלו הם באים מחמת טירדתו כמו חתן, אז לכאורה אף חתן לא יצטרך
לברך. אולי אין הכי נמי. גם יש לומר שטירדא רק פוטר מדבר שקשה לעשות מחמת
הטירדא. לא קשה לחתן לברך, אבל קשה לאונן לברך.
* יח.
* רב אשי
*ומתניתין נמי*- לא צריך לומר נקודה זה, שהיה אפשר לומר שמשנה מיירי במת
שלו, כשהוא מוטל לפניו. נראה שאי אפשר לומר כן, שהרי חוזר להקשות ממשמר מת
שאינו שלו. אם משנתינו בשאינו מוטל עליו, אז זה משנתינו. ויש לדון מהו בכלל
"אינו מתו,” אם הוא רק שלא עליו מוטל לקוברו או שאינו קורבו (שאולי צריך
קורבה יותר חזק לחייבו לקבור מלעשות שהוא מתו). ותחשב.
* יח:
* ונחת
*לעסוק*- קשה, שצריך טבילה רק מתקנת עזרה.
* חזייה
*חבירו*- משמע שהיה חברו, ולא רבו. היה אפשר לומר שר"ל שהיה חברו של אבי
שמואל (וכן קצת נראה, שהרי חולקים לפעמים, ועוד שגמרא בשבת אומר שהיה רבו
של שמואל (עם אביו של שמואל)). ועיין בלשון שהובא בגליון.
* יט.
* למימר הכי
*לא נפרעת*- גם היה אפשר לומר שר"ל חטאנו הרבה, שהוא כמו אמירת "כסדום
דימינו,” שעושה שה' עושה דין על פי מה שחטאנו. ותחשב.
* יט:
* מחמת עצמם
*מחמת כבוד*- מלשון רש"י משמע שמתנחמים מחמת הכבוד, שרואים שאדם מכבדים את
המת[fn:4]. היה אפשר לומר שמדברים להם או שרואים שרוצים לדבר להם, וזה גורם
נחמה. ותחשב על זה. באמת, יש לדון למה כל אלו גורמים נחמה, שלכאורה, הוא
עצב כיון שקרובו אינו כאן, שהוא מת, ואז לא יהני אלו. נראה שראשון מהני אם
נאמר שהוא עצב כיון שאז לא היה קרובו לעשות עוד מצוות. אז, מכבדים אותו
ואומרים שכבר היה טוב. אם כן, לכאורה, ברשעים, טוב שלא יבואו, ויגידו לו
שהיה רשע כל כך שטוב לו למות, כמו שאומר גמרא בסנהדרין. לצד שאנו כתבנו,
לכאורה, הוא שעצב כיון שאבד קרובו שאהב אותו, ואז מראים אותו שאנו אוהבים
אותו. (ודע שאם באו לומר לו דברים, אז פשוט שאפשר נחמה בזה, שיכולים לומר
כל דבר שינחם אותו. מה שהוא מחודש בצד זה הוא שהם פטורים אף שלא אמרו כלום,
שממשנה משמע שלא צריך לומר כלום, אלא להיות שם. ויש לדון, שאולי מה שהם
בשורה מוכיח שאומרים כלום. ותחשב.)
* כז.
* אין ממאנים
*שהרי קטנה אינה בת דעת*- גם היה אפשר לומר שהוא מפני שלא קדש אותה, שמה
נתן לה. משמע שנותן דמי קידושין לה, ולא לאמה ואחיה. ויש לדון, שאולי
הקידושין קרו בביאה. ויש לדון, שלכאורה, לא יכוון לביאת קידושין, שכבר קדש
בדמים. ואם תאמר שר"ל שאילו היה יכול לקדש יותר מעל פי הדמים שנתן לאמה
ואחיה, היה מקדש בביאה, אף זה לא נראה, שלא היה מקדש בביאה, אלא היה נותן
לה ממון. אז, עדיין הוא מפני שלא נתן לה ממון. נראה שנקט זה כיון שלכן לא
נתן לה ממון. ותו"ת.
* שממאנים
*להצריכה מיאון*- משמע שמה שחדשו רבנן הוא שצריכה מיאון. ק"ק, שיש שיטות
ביבמות שבנשואיה לאחר, נחשב מיאון. אז, אין חילקו, לכאורה, הין מה שעושה
אילו צריכה מיאון למה שהיתה עושה אילו לא היתה צריכה. ותחשב. ויש לדון,
שאולי עשו שאסור לה לזנות, ולא שאסור לה לישא אחר. ויש לדון, שכבר אסור
לזנות, כיון שהיא פנוי הבא על הפנויה. ותחשב.
גם צריך ביאור ל"ל אומר שיש עוד חידוש שחדשו רבנן, והוא שאין איסור של פנוי
הבא על הפנויה בזה. ואם תאמר איך למעשה עשו כן, שהרי איסרו דאורייתא הוא.
ראשון, יש להעיר שלא פשוט שהוא איסור דאורייתא, אלא דנו בזה ראשונים. אם
נאמרש הוא מדרבנן, לא קשה איך בטלו דין דרבנן (אלא שיש לדון בכל זמן
שמשתמשים ב”הם אמרו והם אמרו” ב”גדול בחכמה ומנין”). אם הוא דאורייתא, צריך
לומר שכיון שנתייחד לו כך, ממילא אין איסור פנוי הבא על הפנויה. זה אפשר אף
אם הוא מדרבנן, ונראה שכן כוונת רש"י כאן (שנמצא שרבנן רק עשו דין אחד).
עדיין קושייתינו הראשונה קשה. ותחשב.
ודע שקצת צריך לדון לזה על מה שאומרים שכל הביאות נעשים, כמו שכתב רש"י,
כזנות, אם ממאנת. ותחשב.
* ולא פסיקה לצלותיה
*ולישב במקומו*- יש להעיר שאילו מה שהיה רוצה הוא לשבת, היה אפשר שלא פסקו
כיון שלא היה יכול לשבת, שכסאו, אולי, היה קרוב לר"י, ואין לשבת קרוב
למתפלל. אולי ידע שלא קרה כן (ומי שהעיד דקדק). גם י"ל שהיה לו לזוז את
כסאו. גם יש לומר שאז לא היה לו להדגיש מה שלא פסק לר"י, אלא מה שלא ישב.
אף אם עשה כן על ידי מה שלא פסק לר"י, זהו קרק' שלא נצרך.
* כז:
* אחורי רבו
*יוהרא*- היה אפשר לומר שהבעיה הוא כעין מתפלל לפני צילום של אדם גדול,
שהוא שנראה שמתפלל לרבו. אולי כיון שפני רבו אינם עליו, לא נראה כן.
* כנגד רבו
*ומראה כאילו*- עיין במה שפרש. יש להעיר שהיה אפשר לומר שהבעיה בזה הוא
שמזלזל את רבו, שמראה שרבו שווה לו. נראה שאין רש"י אומר כן, שברשי ד"ה
אחורי רבו אומר שהוא נמי יוהרא הוא. לכאורה, רש"י מוסיף על רש"י זה, ואומר
שהוא יוהרא. אז, צריך לומר שהוא שיהיר, שמראה שהוא חשוב כרבו. ותחשב.
כמו כן, יש לומר שיש יוהרא במה שמראה שחושב שרבו לא כל כך חשוב, והוא שחושב
שהוא חשוב די לדעת מי חשוב ומי לא חשוב. אז, נמצא שמזלזל ברבו, אבל אין זה
בעיה, שאין בני אדם מאמינים לו, אבל מראה שיכול לדעת גדלו, וזהו היוהרא.
* מעבירים לך
*מן הנשיאות בשביל אחר*- יש לדון למה רש"י מזכיר "בשביל אחר.” לכאורה, פשוט
הוא, שלא היו עושים שאין נשיא כלל, וגם לא נצרך, שאם העבירו אותו שלא בשביל
אחר, בוודאי יהיה בזיון. אפשר שהיה קשה לרש"י קושיה ראשונה שבארנו, ואז
מבאר שאף אם מעבירים לאחר, היה רע, ולכן היתה לה טענה, ולא היתה יראה רק
שמא יעבירו אותו ולא יתנו לאחר. ותחשב.
גם יש לומר ש"אחר" בא למעט מרבן גמליאל שהיה הנשיא מקודם. אולי זה לא היה
כל כך רע. ותחשב על זה.
* כח.
* יח' דרי
*שורות של זקנה*- במקום אחר הערנו שמרשי קצת משמע שר"ל רינקל"ס, ולא זקן
לבן. ויש לדון, שכמעט מוכרח הוא שגמרא אומר זקן לבן (וצריך לומר שאפשר לומר
לשון שורות על זקן, כמו שאומר גמרא). ותחשב.
* קא חלשא
*שמא יענש*- מעניין שאומר רש"י שחשש לעונש, ולא חשש שעשה עבירה בכך. ותחשב.
*שנתוספו*- ק"ק, שלכאורה, ידע שיבואו תלמידים, אלא חשב שאינו טוב להם לבוא.
אם כן, היה לו לרש"י לבאר שראה שטוב בא מביאתם (למשל, ראה שלמדו, ולא רק
בטלו תורה). נראה שרש"י מפרש שמה שראה הוא שכל כך כמה באו, ולא היה רק אחד
או שנים. אז, היה שווה הרע שלהם. ותחשב.
* מתפלל של מנחה
*פושע גם עליה*- לא נראה לפרש שהענין הוא שיותר טוב להיות פושע על חד דבר
מעל שנים, שהרי גמרא אומר סיבה אחר להקדים מנחה, והוא שמנחה תדירה. אז,
נראה שאם היה עושה כן, לא היה פושע עוד על מוסף, ואז אינו מעלה. נראה שרש"י
רק בא לבאר שמה שמקדימים התדיר הוא כדי שלא יפשע על התדיר. ר"ל, חוששים שלא
יעשה האחרון, ויותר נצרך לו לעשות התדיר.
נמצא, אז, ששני מיני "תדיר ושאינו תדיר תדיר קודם"- שקודם, ושנעשה אם רק
אחד יכול להיעשות- הם אחד, שהוא מחמת שני שהראשון נכון. ותחשב.
עדיין לשון רש"י "גם עליה" משמע כצד ראשון שדחינו. ותחשב.
* ל.
* עד כמה
*לשון ראשון*- צריך ביאור למה לא יתפלל אחר שהרחיק פרסה, שעדיין יש לו
להתפלל לשלומו. אולי שייך למה שגמרא קורא לו שאלת רשות, והרי הוא כבר גילה
שילך בלי רשות.
נראה שאולי הענין הוא שאדם לא רק מתפלל לה', אלא מראה לה' שהוא מפחד לצאת
בלי שמירה מאת ה'. אז, מראה לה' כמה ה' גדול ממנו, וזה כבוד לה'. לכן צריך
להתפלל, ולכן אם כבר הלך, וגילה שלא סובר שצריך שמירה מאת ה', אין חיוב
להתפלל.
*לשון שני*- צריך לחשוב על זה. באמת, צריך לחשוב בדרך כלל לבאר מהו מיוחד
בהליכה שבו אדם צריך לשאול רשות. לכאורה, הוא מפני שהוא דבר שצריך יותר
שמירה מאת ה', שהרי מסוכן הוא. אז, יש לומר שלכן לא צריך בדרך קטן כזה.
עדיין צריך ביאור למה רק מתפללים על דבר שיותר צריך עזרה. לכאורה, הענין
הוא שאז התפלה הוא יותר נשמע. לפי מה שפרשנו בדיבור שלפני זה, יש להוסיף
הסבר, והוא שאם אדם מראה שלא צריך שמירת ה' בזה, הוא יותר רע. ויש לדון,
שלאידך גיסא, אם מראה שצריך שמירת ה' בדברים יותר קטנים, הוא יותר טוב.
ותחשב.
* ל.
* מיושב
*לא רצה לצאת*- לכאורה, ר"ל שלא רצה לעמוד, שאם עמד יחייבו לעמוד לו. משמע
שכן הוא הדין, שבעמידתו יהיו חייבים לעמוד לו.
* בהדי
*כדי לכוון*- משמע שרש"י סובר שהבעיה בתפלה כזה הוא שלא יכול לכוון. יש
לדון אם זהו הבעיה אם כל תפלה כשאינו עומד (ולכן צריך לעמוד בתפלת שמונה
עשרה) או לא (אולי צריך לעמוד מפני שהוא כעומד לפני מלך), ורק כאן הוא
הבעיה (מחמת שהוא יושב לפני ציבור, לא יכול לכוון). וצריך ביאור, אז, למה
מזכיר בעיה של כוונה, ולא בעיה של מה שהוא יושב. ויש לומר שהוא מפני שהיה
גמרא דן באותו בעיה לעיל. זה מניח שהוא יכול לעמוד כשמהלך, אלא לא מפסיק.
גם יש לומר שאין צורך לעמוד אם אי אפשר . ר"ל, אין סיבה לעמוד אז, שהרי אין
צורך לעמידה לכבד, אלא מה שלא מכבד כשאפשר הוא בזיון. אם מהלך, אינו אפשר.
גם יש לומר שלא יעכב, ורק מעכב מחמת חסרון כוונה.
יש להעיר שלכאורה רב אשי, שסובר שצריך לכפול תפלה, סובר שיותר טוב שלא
לסמוך גאולה לתפלה, שהרי סובר שלא מקיים אם יושב. ויש לדון, שנראה שמקיים
שום דבר, שלא התפלל קודם כן, כדי לסמוך גאולה לתפלה. אז, צריך לומר שמקיים
כלום, אלא שרצה להתפלל עוד לקיים מצוות עמידה.
וצריך ביאור למה לא יתפלל לפני כן, ושוב יתפלל אז. צריך לומר שאחר שכבר
התפלל, אי אפשר לתקן. צריך ביאור, אז, איך מהני לו להתפלל מעומד אחר שהתפלל
מיושב. ותחשב.
היה אפשר לומר שרק מקשה ל"ל עושה כאבוה דשמואל שרק לא סמך גאולה לתפלה. אם
כן, לא צ"ל שמתפלל קודם זמן קריאת שמע, שיש לומר שכן מקיים כשמתפלל אחריו.
ותחשב.
* ל:
*חדש שעבר*- עיין במה שכתב. גם יש לומר שהוא מפני שאז מוכרח שיום שני הוא
ראש חדש, ומוכרח כבר מערב. באופן כזה, אין בית דין אף צריכים לקדש (למקצת
תנאים). אז, יש לומר שמה שקורה במקום בית דין לקדשו כבר קורה בלילה, שאולי
רק לבית דין אין כוח בלילה.
לא נראה כן, שאז אין רואים נגד זה מטעם של רב.
* לא.
* במוץ שלה
*אכילת בהמה עראי*-משנה זה רק מוכיח שהוא מותר, אבל לא שהוא עראי. באמת, יש
לדון מהו "עראי,” ויש לדון למה מותר כשהוא עראי. אולי הוא מה שאינו מהנה
אותו כל כך, או הוא מה שאינו כל כך חשוב (ויהיה כמה קרק' בזה, ויהיה בכללו
מה שלא מהנה אותו כל כך). ותחשב עוד.
* לד.
*מפני הטירוף*- קשה לל"א שלא לענות לברכת מצווה. משמע שלא התחיל יברכך. דנו
פוסקים בזה. יש לדון, שאולי אין הוה אמינא שיענה, שיטרף אותו, ואינו כל כך
חשוב.
*לא ישא*- אימת ציבור- לכאורה, ר"ל שיש לעולם זה, ומצרף למה שצריך לשנות
משמונה עשרה. וצריך ביאור.
* לה:
* מזיק
*לגופיה*- גם היה אפשר לומר שהוא רק מזיק לאוכל, שזהו התוצאה הכי חשובה,
שמה שהוא אוכל אותו לא חשוב, שאינו טוב לו, ולא נהנה.
* לז:
* מנא אמינא
*דאפרורים*- לכאורה, בא רש"י לתרץ לקושיה פשוטה. קל להקשות איך רואים שאם
פחות מכזית הוא לא מברכים עליו המוציא לחם מן הארץ, שאולי יש סיבה אחרת למה
צריך להיות יותר מכזית. (באמת, לא מסתבר שזה סיבה שלא להיות פחות מכזית.)
אז, רש"י מפרש שגמרא אומר המקור שכזית חשוב, ועליו מברכים המוציא לחם מן
הארץ. אבל, דין פחות מכזית יודע מסברה או ממקור אחר.
* שהחיינו
*אם לא הביא*- לכאורה, אז, גמרא משמע שלא היו כוהנים מקריבים כל כך. אולי
הוא מפני שכ"א רק הקריב בבית אב שלו, וזה רק פעם אחת בשנה. יש לדון מהו
השיעור של ברכת שהחיינו, שהרי מסתבר שהביא בפחות משנה, שבית אב שלו נמשך
לזמן (ועוד שעבד ביו"ט).
* לח:
* שלקות
*חשוב*- נמצא שהיה ר"נ יותר חשוב מר"ח.
* לט:
* אבל לא חצי
*יותר*- יש לדון מהיכי תיתי, שהיה אפשר לפרש שחול' בששווה.
* מא:
* פת
*אורז*- מרש"י משמע שדין של פה"ב בכסנים הוא כאורז. אם כן, קשה למה אומר
שיש רק דבר אחד, שהרי יש יותר. אולי כולם בכלל אחד. וצריך לדון מהו אותו
כלל.
לולי רש"י, יש לומר שאוכלים פחות מכשיעור. אז, אינו כאורז. כן הוא אף בכל
דבר שנאכל פחות משיעורו, וזהו הדרך שבו אומר כן.
* מד:
* קודם ארבע
*שהגוף ריקן*- יש לדון אם זה קאי על גוף האוכל או גוף המדבר עמו. לצד
ראשון, יש לדון אם צ"ל דבר בגוף בשעת אכילה או בשעת דיבור. ותחשב.
* מה.
* שאני התם
*גאוה*- יותר היה נראה לומר שהבעיה הוא גניבה, שלא יודע שרוצה שיאכל משלהם.
אז, לא יכול לאכול. נראה שאולי פשוט שיכול לאכול, שכל אדם נותן לשמש שלו
לאכול; החידוש הוא רק שרוצים שיאכל עמהם. יש לדון אם החידוש הוא שיכול
לאכול עמהם או שאם אכל עמהם מצטרף (שאולי כיון שאין לו לאכול שם, אף אם אכל
שם, אינו מכלל שלהם).
* מח.
* ואיהו
*ר"ז*- לא גור' כן בגמ' שלנו. ע"ש.
* עד שיאכל
*אבוה*- צריך באיור, אז, למה יכול לפטור אביו אם אביו אכל מדרבנן.
*ינאי וחבריו*- יש לדחות ש"עד שאכל כזית" נאמר על רבים שלא שבעו. לומד מזה
שהיה צריך לשבוע כאן. ותו"ת.
*לגרמיה*- לכאורה, אינו ממש לגרמיה, שר"ג יודה לו. ויש לדון, שאולי יש
חילוק בין חיוב שבא מחמת שתיית יין לחיוב שבא מחמת פת; ואולי חיוב של אחד
לא יכול לפטור את חברו. לא נראה כן.
* נד.
* כל חותמי
*ברוך חונן*- ק"ק ל"ל מפ' שאמרו בא"י מן... חונן, ולא ברוך חונן....
* ואומר
*עיין* במה שאומר. עיין במה שכתבנו בחבורה על זה.
[fn:1] באמת, יש להעיר שנראה מדף פח שהוא מחלקת שם, שהוא סתירה בדברי מי
שאומר כן. על כל פנים, קשה לומר כן, שהרי כאן אומרים כן אף על קריאת
שמע. ויש לדון, שרש"י אומר שרק קאי על אכילת קדשים, ולא על קריאת
שמע. עיין במה שפרשתי בגלגל חמישי בשיח שי על גמרא.
[fn:2] ויש לדון, שגמרא מוקים שזה כשהוא ישן בבית אפל. אם כן, לכאורה, אין
כל כך בני אדם שם. ויש לדון. באמת, היה אפשר לומר שכוונת גמרא הוא
שיפשט על מה שמתעורר שם, שרק זה יכול לדעת בכל זמן. עדיין יש לדון
למה אמר הסימן כך. ותחשב.
[fn:3] חושב אני שבאתי לפרש כפל הלשון, שאמר שהוא אינו לשכר, ולא היה צריך
לומר יותר. ואם נאמר שיש דבר רע בדווקא בלקנטר, אז, קשה ל"ל רק כ'
זה. ותו"ת.
[fn:4] יש לדון, שאפשר שהוא שמראים שהם מכבדים את האבל. גי"ל מה שרוצים
לנחם אותו הוא מחמת שהוא מכובד. דחוק.
