* ב.
** תחילת
יש לדון אם נקרא כן כיון שאינו בסופו (כמו סמיכה) או מפני שהוא תחילת הקדש חפץ הנתקדש. (ועיין ברש"י, שנראה שהוא נוגע לזה).
* ב:
** לשון זכר
אין זה המיעוט, שאין מיעוט, אלא שאין ריבוי. עדיין מעניין מה שלא מזכיר מה שהיה ביותר נראה להיות הריבוי (מה שבכל לאו אשה מצווה, ולא זה, שכל התורה בלשון זכר נכתב. ותחשב.
* ג:
** שקר דומיא דשוא
יש לדון למה כל כך פשוט ששוא לשעבר, שלכאורה הוא אף להבא, כמו אם אומר שלא יישן. ותחשב.
** אבל מילקא
זה מעניין, שלכאורה, יהיה אסור לעשות דבר שיגרום מלקות לו. ותחשב.
* ד.
** של זו זו
מחודש שזה מהני אף שלא פירש איזה חלק ממנו הוא מעשר (ובוודאי לא עשה כולו מעשר, שהרי פירש אחריו עליו). ותו"ת.
* ד:
** דבדיבורו
אפשר לחלק שבתמורה, הבעיה הוא קדושת בהמה שניה, ועשה אותו חלות על ידי דיבורו, אבל כאן, הבעיה הוא מה שבאותו זמן לא נטל תרומה, וזה לא עשה דיירקטלי על ידי דיבורו. ויש לדון, שאולי זה לא מעלה ולא מוריד או אין זה נכון (ורעת איסור זה או זה חלוק ממה שהנחנו).
** עבר אמימרא
אפשר לומר, אז, שחולקים אם לוקים מחמת איסור או סיבת איסור. יש לדחות שרבא אומר שיש ס"א, אבל אינו חלותו, ושאביי סובר שלוקים מחמת איסור, אבל האיסור הוא לעשות שיחול (שעל זה יש סיבה). ויש לדון.
גם נראה אולי לציין למחלקת גמרא גבי קן צפור (ברכות) אם מה שאין מזכירים הוא שלא להטיל קנאה או כיון שכל דיני ה’ הם רק גזרות מלך. נראה שנקודה זה, שרק גזירות הם, שנוי, אולי, במחלקת זה. ויש לדון.
* ד:
** משום ר"י
מקור זה רק אומר שהוא לאו, ולא שיש בו מלקות. סמך על מסקנת גמרא שאין בו מלקות. ותחשב.
* ה.
** אונס
צריך להגדיר מה נחשב מהני ולא מהני, שכאן לא עשה מעשה, לכאורה, עם שום סיבה שיעשה שלא יצטרך לישא אותה עוד, שרק נתן קט, וכמו שהיה חייב לישא אותה מיד אחר שאנסה- דהיינו, קודם שהיתה נשויה לו- כן יחייב כאן (יש לדחות- אולי יש שום יחס שבא על ידי ביאה, למשל, וזה המזקיקיו, אבל כאן שגירשה, אין יחס זה). ותחשב.
** נשיאת חטא למה
לרבא, זה צריך ביאור, שיש נשיאות חטא כיון שעבר על מימרת רחמנא. אולי לשון נשיאות חטא משמע ס"ר (זה מניח שלרבא אין ס”ר. ויש לדון.). ויש לדון.
* ה:
** תצא זו
קשה, שלקמן מבואר שאומר שלשון שאומר שזה יקדש, ולא שזה יצא מקדושתו. יש לומר שהוה אמינא שאף בלי זה, יוצא מקדושתו, שכבר נתן קדושתו לאחר. גם יש לומר שהוה אמינא שחלות שעליו דבר תורה הוא נתינת קדושה מזה לזה, וסילוקו מזה, ואז הוה אמינא שאומר לשון שאומר שמסלקו מזה לזה. ותו"ת. ויש לדון.
** לא יחלל
מניח גמרא שום שייכות בין דין מי ממזר ובמה אין קדושין תופסים. ויש לדון מהו.
* ו:
** התם מעניינא
לולי רבא, היה אפשר לומר שחד הוא מיעוט אחר מיעוט (ואולי כן רצה לומר, אבל לא נראה כן).
* ז:
** אין לוקים על לאו
מנין לאווים לאביי יהיה נוגע לגמרא בפסחים שיש בו שני לשונות אם אביי סובר שיש רק מלקות אחת או אין שום מלקות מלאו שבכללות.
** היה אפשר
לומר לאביי שאפיק כד ועייל תמורה, כקושיית גמרא לעיל.
** רבי יוחנן
היה רבו של רבי יהושע (על כל פנים בדיני עירובין), ואז מוזר שהיה דן עם רבי עקיבה, תלמיד של רבי יהושע.
* ח.
** לית ליה
לא הבנתי, שאולי אינו כהן, וצריך ליתן אותו לכהן ראשון.
** בן דוסאי
בדרך כלל, הוא בן דוסתאי. ואולי יש ילגרוס כן כאן.
* ח:
** דמיברי
יש לציין לגמרא בבא בתרא (קכו:) שאומר שרוק של בכור מרפאץ
** דמיברי
קשה ששל שלישי הוא הכי טוב. ואולי אין הכי נמי; זה רק היה טוב, אבל לא הכי טוב.גם יש לומר שטובים באופנים אחרים (זה מרפא). ויש לדון. ואם אין שלישי רצה לומר לבטן, יותר טוב, שאז אינו משבח במה שהוא גריעותו. ותו"ת.
* ט.
** מי דרע
נראה שזה הגדרה של "גילוי מילתא בעלמא.” ונראה להוסיף קצת ביאור לומר שמה שאין קל וחומר נחשב נכתב בפירוש הוא שהוא קצת מחודש, וצריך הלכה למשה מסיני לומר שדורשים קל וחומר. מה שהוא מחודש הוא שלכש יש פירכא, אולי, במה שאינו חבירו. למשל, אי אפשר ללמוד מצרעת לשבת, שלצרעת, ולא לשבת, יש ס"ר של צרעת. אז, כאן, שאינן כן, שזה נכלל בזה, אין חידוש. אז, הוה כנכתב בפירוש. ותו"ת.
ודע שיש לדון אם חולק רבא על יסודו של אביי או רק סובר שאינו כן כאן.
* י.
** כגון דשוו
יש לדון, שאז שלוחם מקדיש, והוא כמו אם הם הק’. ואולי רצה לומר שאחר יקדיש בלי מינוי. ויש לדון.
* יא:
** נראין
נמצא שיכול לומר כן, אף שד"נראין" שני אינו אומר כן. חושב אני שגמרא פסחים גבי ר"י ור"א באם אין בשר לא משמע כן.
* יב.
** ראוי
עיין בע"ז, שיש צד שאין לעדה שינוי. יש לדון אם אז יהיה נחשב ראוי.
* יג:
** ואת תימצא
נמצא שהוא "אם תמצא" ב"אם תמצא.”
* יד.
** בבהמה
נראה שנקט זה מפני שאין עוף בציבור כלל. ותו"ת.
** שלמים
גם היה אפשר לומר שיש שבא בזכר ויש שבא בנקבה. ותו"ת.
** וכל הקרב
צריך ביאור מה זה שרק נקרב בלילה.
* יד:
** כשורף
צריך ביאור למה משנה מלשון רבים ללשון יחיד. ועיין בגירסת רש"י.
** דילמא
לכאורה, דילמא לאו דווקא, שצריך לומר כן כדי לתרץ לקושיית גמרא. וע’ במקום אחר שדנינו בזה.
* טו:
** אין צבור
נראה שבאר על פי מה שאומר ר"א שהוא שבעליו הוא "ציבור,” וכל מי שנולד נכנס לאותו כלל. עדיין, היה יכול לומר שמת, שאולי אם אין נשאר מי שהיה בציבור ראושון, נאמר שנשתנה הציבור.
** מיעוט
נמצא שהיו רבים יותר משבעים. אינו כל כך מוזר, שאלו שזכרו א"י היו הרוצים לחזור לו.
** יוסף בן יועזר
במקום אחר, נקרא יוסי בן יועזר.
* טז.
** דופי של סמיכה
קשה, שכבר אמר ששכחו כמה הלכות וחלקו בהם. ותו"ת. ואולי זה הראשון שנתוסף על שלש מאות ששכחו בימי משה.
** נשתכחו
העיר ש.ל. שקשה מה בין ספקות לשכחות. ותחשב.
יהודה אחי שמעון- לכאורה, רצה לומר שהיה יהודה בן יעקב. יש לדון למה אמרו על שם אחיו (ולמה אמרו על שם שמעון יותר מאח אחר). צריך ביאור, אז, יחסו לקנז.
* יז.
** גבי קדשים לא לקי
לכאורה, רצה לומר שאם עושה בו דבר האסור בקדשים, לא לקי.
** אלא אימא
אם כן, ממש משנה את כל המימרה. וצ"ב.
* יז:
** אימא זכר
נראה שמקשה שלא נדע מה מרבה מה. אז, מקשה איך יש לברייתא צד שנכתב רק חד ונלמד חבירו ממנו; בהכרח נדע רק הכי פשוט. גם יש לומר שרק מקשה על מה שדורש גמרא באופן אחת, ואומר שאין הכרח לזה. אולי אף חושב שיותר מסתבר לאידך גיסא, שהרי רק לנקבה יש ולד.
* יח:
** תני ר"ח
מעניין שר"ח, שהיה תלמיד (חבר) של רבי, יביא ברייתא לסייע לריב"ל שהיה תלמיד של רבי יוחנן שהיה תלמיד של רבי. גם מוזר למה לא רק יאמר כן, שהוא תנא. ויש לדון, שאולי ברייתא יותר קודם. ועיין לקמן (כ?) שרש"י גורס כאן שהיה רב חנינא, ולא רב חייא. אם כן, כמובן, אין קושיה.
(ועיין לקמן, שבאמת, כן גורס גמרא שם.)
** עד כאן
אז, הוא לשיטתו בביאור משנה לכולי עלמא ולרעייה לעיל.
* יט:
** מחוסר זמן
לולי זה, היה אפשר לומר, לכאורה, שפסול מחוסר זמן בכל זבחים ופסול אשם קודם זמנונ הוא שווה. מכאן נראה שאינו כן. ותחשב.
* כא.
** בבלאי
כן אומר גמרא בכמה פעמים (ממולאי, פומפדיתא…) ותו"ת.
* כג.
** מאי לאו
יש להעיר שאז בוודאי יסבר רבי שכיש ספק, ועל ידי זה ממעט זמן אכילת קרבן, אינו בעיה (כרבי שמעון).
* כד.
** דאלימי
אין הוכחה שלכן לא פודה בכור, אלא שאין הוכחה שיש לו אותו קדושה, שאולי אינו אלים, שלא רואים שיכול לתפוס פדיונו.
* כד:
** עולה
קשה מה מבנה על ידי זה. אפשר שלא רוצה להנות לכהנים. גם אפשר שכבר נדר.
** מפקעא מקדושה
היה אפשר לחלק לומר שאינו אסור כיון שמפקיע אותו מקדושה, אלא מפני שמפקיע אותו מכהן.
** מקדושה
קשה, ששלמים למעלה מבכור (עיין פרק קמא דזבחים). וצריך ביאור.
* כה:
** המשחרר
בכל סוגיה זה, צריך לזכור, לכאורה, שמביא גמרא ברייתות כר"י לעיל 0ומפרש שם מהו הצד לחלוק עליו. ועיין שם.)
** המשחרר
צריך ביאור מהו דינו. לכאורה, יהיה שלו יום אחד ושל רבו יום אחד. אם כן, קשה מהיכי תיתי שיום ראשון שלו. יש לדון. אם לא נאמר כן, אז צריך לומר שכיון שהוא חצי לעצמו, יש לו חצי יד. יש לדון, שכל מה שקנה, קנה רבו, ואז יקנה חציו, ומיד אחר כך, יקנה הרב חצי מזה, ושוב עוד חצי… ותו"ת. גם קשה, שאם כותב לו כולו, יקנה כולו, ואם כתב חציו, יקנה רק חצי זה. ותו"ת.
** כולי עלמא
עיין בגי’ שלנו. לכאורה, צריך לומר, “כו"ע אם שיירו אינו משוייר,” שאי לאו הכי, לא יאמרו שהוא בן חורין. ותחשב.
* כו.
** מדהוה
ק"ק למה לא אומר, “מדהוה ליה לומר, “לא תחול זה אלא אם כן… "” ונראה שלא אומר שיאמר כן כיון שהוא יותר מובן, אלא מפני שהוא יותר קצר. נראה שלכן יש יותר חידוש ב"לא תחול… " ולכן עליו אומר שלא נחלקו. ותו"ת.
** לא נחלקו
נראה שאולי ר"מ לשיטתו, שלא חושש שבני אדם לא יודעם הלכה (בשיטת אין אדם מוציא דבריו לבטלה).
* כו:
** צריך לבאר החילוק
בין חליפין וחילול.
** דשמואל
לכאורה, לא מחדש כלום בסטא"ף זה. ותו"ת.
* כט:
** ולא זונה
נראה שממעט את זה כיון שהוא יותר חלוק משאר מיני אתנן. ותו"ת.
* ל:
** את בשרו
מעניין שלא דורשים "את" לרבות פרש, אלא לעור. אפשר שהוא יותר טפל לבשר כיון ששומרו וכדומה.
* לא:
** והרי
קשה למה לא הקשה מקרבן ציבור. גם קשה למה לעיל לא הקשה מקרבן ציבור.
** דלא חלק
קשה, אז, למה לא מניחים שעשה שניהם לשלמים למזבח.
* לג.
** דתנא דבי לוי… וכן תני לוי במתניתיה
יש לדון בחילוק שנים אלו.
