יש לדון אם מחלקת רבי יהודה ורבי מאיר מיוסד על איזה פסוק משמע להם או איזה פסוק משמע יותר (ולומדים מחד שלא לדרוש אידך) או בסברה (ומזה רואים איזה לנקוט לדרוש).
ולא תשאו עליו חטא- צירך ביאור למה רבא אומר שזה הכרח, שלרבא, נחשב חטא כבר כיון שיש ציווי. אפשר שהוא מיותר, שפשוט שיש איסור. ויש לדון, שצריך ביאור איך הלשון יהיה משמע שחל. ואולי רצה לומר שיש ס"ר.
תיובתא דאביי (פאה)- משמע שהוא אותו חיוב שחוזר עליו, ולא חיוב חדש. כן נראה מגמרא ב"ק שמוכיח מכאן שאין שינוי קונה. ואולי כן הוא דיחוי שם (אלא שאביי שם מסיק דלא כאותו דיחוי).
לחיים- אפשר שאומר לשון קראף ורפשר שהוא לשון טוב של מיתה. לא נראה כשני, שגמרא אומר לשון מיתה כ"פ.
רב אחא- רצה לומר, רק מחמת זה יפסוק.
מעניינא דקרא- היה אפשר לומר שאחד הוא מיעוט אחר מיעוט או ריבוי אחר ריבוי.
מאי משמע- גם בנדרים מצינו שהיה רבי שואל לבר קפרא פירוש מילים. מעניין.
תם חי- ק"ק, אז, למה אמר חי כלל. ואולי הוא להודיע באיזה זמן הוא.
רישא- גם יש לומר שרישא בזה"ז…
רבא אומר שענש כיון שעבר על מימרא דרחמנא, אף שלא עשה סיבה רעה. ואם תאמר אם כן, למה נאסר (הוא קצת ראנדו"ם). אמר א.י.ש. שאילו לא נאסר, היה חל. אז, ה’ אסרו. יש לדון, שזה מניח שלא היה דרך אחר לעשות כן.
במקום אחר כתבנו צד שאולי קדושת דמים ר"ל שדבר הוא של ה’, אבל קדושת הגוף ר"ל שהדבר קדוש. צריך לחשוב מה זה אומר. העיר לי ש.ז.מ. שלשון של אדם כשמקדיש הוא שהוא קדוש, ומוזר לומר שהוא רק עושה חלות ממוני. נראה שקל לומר שמה שהוא של ה’ הוא גופא קדושה[fn:1]. וצריך לחושב.
* Footnotes
[fn:1] איני יודע מהו קדושה, אבל לכאורה, הוא דבר כעין "יחס אל ה’,” או כדומה. אם כן, מה שנקנה להקדש או לה’ הוא קדוש, לכאורה. ותחשב.
