* ב:
** אבל
מעניין שסובר שצריך לומר מהו מסכתא זה, שלכאורה, כבר ידוע הוא שהוא תמורה. ותו"ת.
* ג:
** משום
התראת ספק
מעניין שתולהו בשכחתו, שלכאורה, זה רק לריב"י שאומר שהתראה הוא רק להבחין. ותחשב. ויל"ד.
** יש להעיר
שמעניין שנחשב שבועת שקר שאין בו מעשה, שהרי אם הוא כשבועת ביטוי, מע שעושה הוא שעושה מעשה להיות רע. אם כן, אולי נאמר שעבר במעשה. ויש לדוןן, שבא אחרון מה שאינו מעשה. וק’, שידמה לאם עשה תנאי אחרון. ותחשב.
** לפייס
הואיל- זה מעניין. ותחשב.
** לקיים
היה אפשר לומר שאף זה אסור (לוקה), ורק מחדש שחל. אפשר שלשון קרא משמע שהוא מותר.
* ד.
** לא תקלל
יש להעיר שקרא משמע שהבעיה הוא מה שמקללו, וקרא משמע שהוא מה שמשתמש בשם ה’ לשוא. רש"י כאן משמע שבא לדון בזה, אבל צ"ב מה אומר. ותחשב.
** מפני
יש להעיר שלפעמים "שמות" שאומר הם שמות לאותו דבר, ולפעמים הם שמות לחלקים חלוקים שבו. ותו"ת.
* ד:
** מה טעם
ואי
לשון זה מעניין, שבודאי יהיה נותר עד אז כיון שכבר נותר. נראה שצריך לומר שה"אי" קאי על היותו נותר עד ראשון, וזהו הספק בהיותו ספק עד בקר שני.
* ה:
** ה"ג
אבל בכור ומעשר- יש להעיר שאף שטובת בכור הוא לכהן, לכאורה רוצה תורה בטובתו של כהן (לכן ציווה שלו יהיה בכור). ותו"ת.
** בכל
משמע שביטול הוא שינוי שם. יש לדחות שגורם שינוי שם (כיון שמשנה דינו).
* ו.
** מחזיר
קני
משמע שרק קונה ביום, אבל לא בלילה. לכאורה, יהיה לזה נפק"מ גדולות (לענין איבודו, ושמיטה). ותחשב.
* ז.
** מתקיף
משמע שכל דיון זה הוא רק סימן למה מכוון. ק"ק למה לא פירש כן לענין "יש במינו.”
* ז:
** לא אמור
נמצא שיכול להיות לאו אף שרק נרמז, ולא כתוב בפירוש. אם תורה הוא דיבור ה’ (חקרנו על זה במקום אחר), ולא רק קיצור של ה’ של דיבור ה’, זה יותר מעניין. ודע שזה רק מעיר על הצד שלא אמר ה’ יותר, ולא שכולו נאמר.
* ח:
** היינו
עיין במה שמפרש אותו בעיה. עיין איך מפרשו בזבחים.
* יא:
** באומר
קשה למה לא רק אומר שיכול אדם לקנותו ולומר, “הרי זה עולה,” ויזכה במצווה.
* יב:
** ביאת מים
זה מעניין. ותחשב.
* יג.
** לרבות
לשון שוגג על כעין זה (וכן מוצאים בנדרים) מעניין.
* יג:
** אין
אין זה לשון ש"ס
יש להעיר שיש כמה שבתמורה שיש לו לשון מוזר, אבל זה בדרך כלל ב"לשון אחר"ים. ועיין לקמן, שאומר גבי תיבעי כן. ואולי לשון זה אינו אף לשון ירושלמי.
* יד:
** כשורפי
דע שצריך להיות שהרע אינו שאין תורה נשאר, שאם כן, בודאי יכתב, אלא שיש בזיון בשריפתה. ותחשב.
* טו.
** עשר
לכאורה, זה מוכיח שמלך דוד רק ממיתת שאול, ולא ממשיחותו:
1. רק אז נוכל לומר שמלך שמואל לשלש עשר שנים, ולומר כן אף ששאול מלך לבדו שנה, והוא מפני שמניחים שאותו שנה הוא אותם חדשים, והרי אינם אף כרב שנה. ותו"ת.
2. רק אז נוכל להגיע לכל ימי שמואל, שהרי מנכים ימי עיבורו, ונשאר שלש חדשים יתירים. צריך להוציאם בד ירחים של מלכות שאול בפני עצמו. ותחשב.
* טו:
** לקול
יש לדון אם הראיה הוא ממה שנשמע כל כך בכייה או ממה שתולהו ב"עם" ולא רק במיעוט מבם.
* טז:
** ארבעה
לחומרה
קשה איך זה חומרה כיון שממית בהמה שאולי צריך לפדות. ועיין לקמן, שנראה שצריך לרעות אותו קודם. ותחפש. ותו"ת.
* יט:
** תימכר
מעניין שקורא זה מום. ותחשב.
* כ.
** קדשי
דדין
שמעתי מגר"ק שאין קדושת דמים של כל ק"ד שווה. נראה שזה כוונת רש"י כאן, לומר שיש לו כין של בדק הבית.
* כה.
** דברי הרב
לא מפרש שהוא מחמת איסור, שמגמרא לעיל מבואר, לכאורה (גבי שלמים), שאין איסור. (והיה אפשר לדחות שאותו גמרא דן בדין בדיעבד, אבל עיין רש"י שם שלא פירש כן.)
נראה שמה שמה שעושה ה’ דוחה מה שעושה הבעל הוא:
1. אפשר שהוא מפני  שדעת ה’ יותר חזק, ואז יש יותר כוח (מחמת אותו יתרון שבדעתו).
2. אפשר שהוא מפני שה’ הוא הבעל עליו ביותר, ואז יש עליו יותר כוח.
3. אפשר שהוא מפני שכמו שיש חילוק בין ישראל לגוי לענין קנין, כך יש חילוק בין ה’ לנו. ותו"ת.
גם יש להעיר שאומר גמרא סברה בלשון זה גבי עשיית שליח לדבר עבירה. שם, אומרים אחרונים שלש צדדים בביאור הבעיה:
1. יש אומרים שהאו מפני שלא מניחים שסומך דעת משלח. אם כן, סברות אינם שוות, ומוזר שישתמש באותו לשון.
2. יש אומרים שהוא מפני שלא עושה כן שליח למשלח, שאין אדם חוטא ולא לו. אם כן, אין הסברות דומות.
3. לש אומרים שהוא שה’ לא מניח לו לעשות לשיח כיון שהוא לדבר עבירה. אם כן, יכול להיות דומה, אם נאמר שהק מונע סיבתו, ולא שעושה שאינו יכול לעשות סיבה. נראה שצריך ביאור למה אי אפשר. היה אפשר לומר שה’ רק חידש שליחות לטוב. אם כן, צריך לומר שאי אפשר לעשות שליח, ולא שה’ מונע. וצריך ביאור.
גם צריך לדון בענין מתנה על מה שכתב בתורה בכל סוגיה זה.
[אגב, צריך ביאור למה רש"י מביא לשון ירושלמי כל כך בתמורה.]
* לא.
** ל"א
יש לדון, שהניחא בביצה, לא גודל, אבל אפרוח גודל, ובזה דן.
* לב.
** חרמי
חרמים
זה מחלקת. ואולי כוונת רש"י הוא לומר שיכול להיות אף לפי שיטה שחרמים סתם….
* לג:
** חולין
לכאורה, עדיין אפרו מותר (שאומר שהוא כן גבי כל נשרפים. ויש לדון.) אם כן, קשה איך יוכלו רבנן לתקן כן. אולי זה גזירה דאורייתא. ותחשב.
* לד.
** ליבטל
עיין במה שאומר בכלאים. זה מעניין, שהיה אפשר לומר שכיון שאותו מין בטל, אין שני מינים. נראה שאף בביטול, אין שמו בטל, אלא שניתוסף לו שם של אותו מין אחר באופן חשוב, ואז נשנה, אבל כאן, כל כלאים הוא דבר עם שני השמות. ותחשב. ויש לדון.
