** פרק ראשון א-א א. ודאי -
לכאורה, היה נראה לומר, וכן נראה שיבואר לקמן שחולקים רשב"ל ורבי יוחנן בטעם זה. רבי יוחנן סובר שאלו בדרך כלל הם רוב, ואז לא צריכים להפריש מעשר. ריש לקיש סובר שהטעם הוא שאלו אין חשובים. חשובים די עד שלא מפקירים אותם, אבל מפרישים מהם. אז, לריש לקיש, זה מהני רק בדמאי.
כן נראה ממה שחולקים בפירוש משמרים. לא משמע כן ממה שתולה גמרא על מחלקתם; ועיין לקמן.
** מתני’ מסייעא -
לכאורה, לא מסייע לו בשיטתו, אלא בתשובתו. גם יש לומר שלא היה נראה לומר כריש לקיש אלא מפני קושיה זה. כיון שנדחה, יש סיוע לרבי יוחנן. יש לדון, שלא נאמר שמשנה מסייע לו, אלא דבר אחר מסייע לו, ומשנה מסלק הבעיה. ויש לדון.
** א: מחלקת -
לא הבנתי זה כל כך. לכאורה, מח’ ר"י ור"ל הוא כשיש וודאי עם ספק אחד- ספק שהם מהפקר. יש גם, לכאורה, ספק שבא מגוי, אבל אין סיבה לחשוב שצריך ספק זה. יודעים שרבי יוחנן אומר שספק הפקר הוא רוב. יש לדון אם אף ריש לקיש אומר כן. אם נניח שאומר כן, נמצא שחולקים בדין וודאי אינו מעושר עם ספק אחד של רוב. כאן, יש וודאי עם שני ספקות שאולי הם רוב. צריך ביאור למה מניח שדין שנים אלו שווים. אולי לא ר"ל שהוא אותו מחלקת של ריש לקיש ורבי יוחנן, אלא מחלקת אחר. כמובן, זה דחוק. וצריך לחשוב על כל זה.
** העלין -
לכאורה, הענין הוא שהעלין גורמים שלא באים להם כל כך שמש, ואז הם רעים. גם יש ומר שזה רק סימן, ולא סיבה, וכמו שהוא מוזר בזה, כך הוא מוזר בדברים אחרים שעושה אותו רע. זה אומר, שאולי יותר מצוי שפרי רע יהיה לו כמה דברים מוזרים (כן אני חושב), ולכן פרי שהוא כל כך מוזר, עד שהוא תחת האלה, יהיה רע. ותו"ת.
** שבציפורין -
שם היה רבי יוסי דר.
** והוא משמר מפני -
לכאורה, יש לדייק ממה שזרע אותם שרוצה אותם, ולא מפקיר אותם. אם כן, צריך לומר שיש טובים על האילן. א"כ, קשה ל"ל אומר ששומר מחמת הטובים. ויש לומר שדרך טובים לבוא מוקדם או מאוחר לאלו. גם יש לומר שטובים באים בשנה אחר, ולאלו זרע אותו. גם יש לומר שחשב שיהיה טוב, אבל אינו טוב, ולא רוצה בו. ותו"ת.
** תני -
מעניין שמביאים מימרא בלשון תני. אולי הוא לשון ירושלמי. ויש להעיר שלולי פני משה, היה אפשר לומר שחלק מזה ברייתא, והשאר הוא מימרא שמביא מחלקת רבי יוחנן וריש לקיש.
** צווח
- עיין במה שמבאר. אם כן, לכאורה, לא לומד ממה שצווח, אלא ממה שהושיב בעל הבית שומר עליהם. נראה שצווחתו הוא הראיה שעליהם שומר, ולא על דבר אחר. אז, רואים שבעל הבית מקפיד, שמצווחת שומר, רואים שבעל הבית הושיב שומר. ותו"ת.
** ב. רבי יוסי-
כל העולם כולו…- צריך ביאור, שרק צריכים להוכיח אם הוא הפקר, ואז כיון שיודעים שהוא באותו מקום, ל"ל נביא ראיה מזה לראות אם הוא הפקר. וי"ל שאף אם לא כוון אלא לקנות אותו, בטלה דעתו. ביטול דעת הוא יותר קשה אם נאמר שצריך דעת להפקיר, ולא רק לקנות. ותחשב. (אם בט"ד ר"ל שלא באמת חושב כן (או שמשקר, או שטועה במה רוצה), אז אינו קשה.)
** חרצנים -
צריך ביאור איך מבארים את זה בתוך דיבור שלו. ויש לדון, שאולי משנים את הגירסא.
** ב: א-ב רבי אימי -
לקמן, קורא לו פני משה וגמרא "רבי אמי.” נראה שזה רבי אמי, ונמצא שיש בשמו יו"ד. אז, אין העולם אומרים את שמו בדרך נכון.
ויש לדון אם הוא אותו רב אימי.
** ומאבדים -
עיין בשני פשטים שלו. רמב"ם יסבור שרק בציור שלו יכול לאבדו כיון שהוא יותר קשה להעלותו. גם יש לומר שכיון שאינו עוד ברשותו, לא חייב עליו. ותו"ת.
** ג. א-ג מחפים -
עיין במה שמביא פני משה מגמ’ מכות. יש להעיר ששם לא כל כך פשוט בגמ’. ותו"ת.
** אפילו ביעי -
זה נראה כדבר שהיה עשו עושה (אלא שלר"י היה סיבה טובה).
** איתאכלית -
מצאנו מזה שאף על דרבנן, נוהג הכלל ש"בהמתם של צדיקים…,” וגם לומדים מזה שאין אותו כלל שייך היום. ותו"ת.
** מתקנא הוה –
אם היה כל כך פשוט לו, קצת צריך למה שאל כלל.
** דרפב"י -
יל"ד ל"ל מחל’ ששם היה איסור דאו’. אולי גמ’ יודע שהיה מדרבנן.
** ד. גניי -
ק"ק, שבמעשה שמזכיר בבבלי חולין, עשה רפב"י שאף טייעא יעבור. אולי כאן היה דרך אחר. גם יש לומר שחולקים.
** מעניין שהיה
רפב"י בזמן רבי, שהיה רפב"י חמיו של ר"ש, שהיה רבו של רבי.
** פטל
- עיין במש"פ. נראה, אולי, שזהו הסיבה שנקרא פטל (הוא דבר שנותנים בתוך מים לעשות אותו למשקה טוב, כמו קול אייד) נקרא כן.
** חסיד -
בבלי, יש כלל של מי הוא חסיד אחד, והוא ר"י אחד. מעשה זה הובא בבבלי להיות מעשה בנחמיה חופר שיחים. לכאורה, או צריך לומר שאין אותו כלל בירושלמי, או ששנים היו איש אחד, או שחולקים מה קרה, או שהיו שני מעשים, שאז יש לומר שזה ר"י. ותו"ת.
ודע שכאן גם חלוק בענין אחר, שכאן הלכו לרפב"י. אולי, אז, גם היה ר"י, שהיה חסיד סתם.
** ד: הלך דרך כזיב -
אין זה כל כך מבואר. עיין בגרח”ק במה שפירש. אף בזה, יש לדון, שהיה אפשר לדחות שלא הולך מכזיב לחו”ל, אלא אם כן בא מארץ ישראל. ותחשב.
** רבי יוחנן -
לכאורה, לא מפרש כלל, שרק אומר שלא גזרו, ולא מפרש למה. אולי לא יודע, אלא אומר שיודע שאינו לטעם פשוט כרבי הושעיא. דחוק, שאומר כן קודם שאמר ר”ה טעמיה. אף אם היה יודע טעמו של ר”ה, היה לגמרא להזכיר אותו אחר שיטת רבי הושעיא, שקאי עליו. ותחשב.
גם יש לומר שר”ל שרבנן לא גזרו כיון שלא רצו לגזור על הכל, כדי שיהיה חלוק מוודאי. ויש לדון, שכבר יש כמה חילוקים. ותחשב.
** ה. מפני אחד -
שמא יש אחד- זה מעניין, שהיה נראה לומר שוודאי יש אחד, אלא שמא זה הוא. ותו”ת.
** ה: מברכים עליו -
מצווה הבאה בעבירה- עיין בב"ק שאומר שהוא משום דכתיב, “בוצע ברך נאץ ה’.” אולי קרא זה מגלה שלא לברך עליו כיון שהוא מצווה הבאה עליה. ותחשב.
** ערום -
חידוש של זה הוא שאינו צריך לברך. ק"ק ל"ל אומר כן. אולי זה גם מחדש שלשאר ברכות צריך להילבש. ותחשב.
** מקום אחד -
עיין בפני משה, שמבואר שחולקים אם יכול להפריש שניהם במקום אחד.
** מקום אחד -
מעניין שחוששים לזה, שלכאורה, קל לזכור מאיזה מקום הפריש.
** קבוע -
לא הבנתי כל זה כל כך. לכאורה, כבר מפריש בקביעתו. אם כן, קשה למה יהיה רק יכול לקבוע ולא להפריש. זה יש לומר שאף שאין חילוק ממש, כיון שאלו דינים דרבן, יש חילוק (למשל, תלוי במה נראה לבני אדם). עדיין צריך ביאור למה דן פני משה בהפרשה אחר כך. גם צריך ביאור, אז, מהו הצד שיכול להפריש אותו מקום. ותחשב.
** ו. עולא -
לא הבנתי את זה כל כך. לכאורה, אחר שמפריש מעשר שני, ושוב פודה אותו, לא חוזר להיות טבל כמו שאומר פני משה, שהרי חילל אותו. לכאורה, צריך לומר שהוא עדיין טבל, שלא הפריש הכל ממנו (ומסתמא, כיון שהוא מעשר שני, אינו חייב להפריש). צריך ביאור. על כל פנים, לכאורה, זה אפשר רק אם נאמר שלא הפריש מעשר ראשון, אבל פני משה כ’ שכבר הפריש. וצריך ביאור.
גם צריך ביאור איך מפריש ת"מ כיון שאין זה מעשר ראשון. ותחשב.
גם לא הבנתי תירוץ של רב מנא כלל. וצריך לחשוב.
** ז. פרק שני ב-א אבל הלוקח מן הישראל
(כגי’ פ"מ)- לא הבנתי למה הוא וודאי, שעדיין אולי הפריש ממנו. ונ’ שר"ל כשבוודאי לא הפריש ממנו, וכאן רק דן בחשש שהוא בא מגוי או מחו"ל, ולא היה חייב. בוודאי כן הוא החשש בגוי, אבל מוזר שנקרא דמאי מחמת זה. ותחשב.
** אותו הגר הוכיח -
קשה, אז, מה עושה עם אותו מעשה. אולי אומר שלא קרה, או שלא היה זה הטעם.
** ז: נקלווסים -
לכאורה, אותו תשובה נכון בכל, שרק אומר שתלוי באם בא מישראל או לא. צריך לבאר מה היה הסברה לחלק (למה היה השואל שואל רק גבי נקלווסים).
** לא הבנתי
איך ברייתא של ר"א הוא כר"א יותר מכר"י, ואיך ברייתא של ר"י הוא יותר כמותו מכר"א.
לכאורה, יש שלש דינים שבאים במשנה זה. יש דין של רוב עכו"ם, ובו כולי עלמא מודו, ויש דין של רוב בני ישראל, ובו כולי עלמא מודו, ויש דין א"י (אם רוב עכו"ם או ישראל), ובזה יש מחלקת.
לכאורה, ברייתות אלו לא מוכיחים כלום על דיון שלישי (שהוא דיון של גמרא). ותחשב.
** צריך ביאור
איך נאמר שמפני שחושש למיעוט יהיה ודאי; לכאורה, כל דמאי, אז, יהיה וודאי כמו זה. ותחשב. אולי וודאי הוא אף יותר מזה, עד שאין מיעוט חשוב נשאר. ותחשב.
** ח. בעי -
פני משה מפרש שזה שאלה עם תשובה בצדה. היה אפשר לומר שאין זה שאלה ותשובה, אלא מימרא, כמו שמצאנו בירושלמי ש"בעי" יכול להיות "אמר.” (חושב אני שכן מצאנו בחרדים בתחילת ברכות.)
** הפירות לא הילכו -
לכאורה, ר"ל שאין הוכחה די בזה.
** על כותים -
עיין בפירוש פני משה. נמצא שבפעם ראשון, אומר נגד כותים, ובפעם שני אומר עם הכותים. כמובן, זה מוזר.
אולי אינו כל כך קשה, שאולי אמרו לשון זה אגב זה. ותחשב.
** ח: פלן -
חז’ היתר- לאו ממש הוחזק, שהרי אינו מותר אלא דמאי. ויש לומר שר"ל שהיה מוחזק כן לכל חוץ מדמאי, אבל בדמאי, שחששו אף לחששות קצת רחוקות, כמו כל חשש דמאי[fn:1], חששו לזה. ותחשב.
** ט. חד מקום -
נראה שכך אומר גמרא. שאל לו אחד על פירות של מקומו, אם מניחים שהם מא"י או לא, וענה לו שלא היה ארץ ישראל עושה כל כך כמה פירות. מקשה גמרא למה לא היה ארץ ישראל יכול לעשות כל כך כמה פירות, וענה שרק אמר שאין אותו מקום אחד שבא"י יכול לעשות אותו, ואז מוכרח שלא ללכת אחר הקרוב. אז, הולכים בתר רוב, ומניחים שבא מחו"ל.
מה שהולכים בתר קרוב לכאורה, הוא, כמו שבארנו, בפירות שלא היינו חוששים שבאים מא"י בלי זה. צריך להגדיר קצת, שלכאורה, אם יש רוב מחו"ל, נאמר שברוב וקרוב הולכים אחר רוב. אז, צריך לומר שאינו ממש רוב מחו"ל, אלא ספק די עד שלא נחוש. ותחשב.
** נצרפיה -
זה מעניין, שר"י אמורא. גם מעניין שר"י צריך זה, ולא רק אומר שהל’ כראב"ש כיון שמסתבר. אולי גמ’ מפ’ ל"ל נאמר שמדין של ר"י עצמו נאמר שלא נפסק כר"י כאן.
** עתיד -
ואם תאמר לכאורה, ר"ל שכבר הלך שם, שאם לא הלך שם כבר, פשוט שלא נסר. נראה שר"ל שביציאתו, היה עומד ללכת שם, שזה היה דרכו, אבל לא יודעים שהלך לשם. לכאורה, יש אותו הדין, אלא רק מזכיר מה מצוי.
** מה את בעי
- עיין במש"כ. קשה, עדיין, ל"ל יהיה הדין כרבי במחלקת זה. אולי בזה יודעים שיש רבים שלא סוברים כרבי. היה לו לפני משה להזכיר את זה. ותחשב על זה.
** ב-ב המקבל עליו -
לא הבנתי כל כך מהו הדיון בזה, שאם דנים אם נאמן לענין לאכול אצלו, אז, לכאורה, צריכים רק לדון בזה, וכן אם דנים בנפק"מ לענין דבר שמוכר, צריכים לדון רק בזה. צריך לומר שכשאומרים שיודעים שמקפיד בזה, לא יודעים בברירות, ואז אם לא מקפיד בדבר אחר (כמו מה שאומר במשנה), מוכיחים שלא באמת מקפיד בזה, אף אם כבר קבל על עצמו, או כדומה. ותו"ת.
** חבריהם -
אין חברים אלו (שאוכלים אצליהם) חברים. המבין יבין.
באמת, איני יודע למה נקראו חברים (ר"ל, מי שלא חשוד) בשם חבר.
** בק’ גמ’
על רבי יוסי, צריך לדון מה הניח במחלקת רבי יהודה וחכמים, שאם חולקים בציור שלא קיבל, לא רואים שרבנן חולקים על רבי יוסי, ואם חולקים בשאכל פעם אחת, אז פשוט שר"י כרבי יוסי.
אפשר שהניח שחולקים בשניהם, אבל קשה מהו הסיבה להניח כן, ואיך רואים ממשנה יותר ממחלקת אחת.
** ר"ח ר’ ייסא -
יש לדון אם ר’ ייסא הוא אותו אדם של ר’ יוסי, ואז הוא לשיטתו, או שהוא אדם אחר.
** ואם תאמר
מה לי שמקבל מתחילה, כיון שאומרים שהוא חשוד. צריך לומר שאף שחושדים אותו, לא נחשד לגמרי. אז, אינו כל כך חשוד כמי שלא קבל כלל.
** ט: ר"ז… כגון אני -
עיין לעיל, שמזכיר מעשה בו שהיה נמצא שאינו טוב בו.
** לוקחים ממנו
- לערב- ואם תאמר ל"ל אומר שנותנת לו דבר שאינו מעושר. ויש לומר שבעלה עושה את המזון, או על כל פנים בודק את המזון, לדעת שהוא מתוקן, ואז היא רק מוספת מזון, וחוששים שאותו הוספה שמערבת אינו מתוקן.
** התנה על לבו -
אם מתנה כך על מה קאי מעשר שלו, לכאורה, הוא ברירה. ותו"ת.
** ב-ג אבל אינו נאמן -
יש לדון למה אין לו מה לי לשקר.
** י. אפילו ע"ה -
לא הבנתי כל כך במה הוא ע"ה.
** כר"ל -
לכאורה, מוכיח מכאן שאין כל ת"ח מקפיד, וממילא צריך לקבל.
** ב-ד יא. מסייע לר"ל -
ק"ק ל"ל מביא משנה ה, שלכאורה מסייע לזה.
** פרק שלישי ג-א יב. הפועל מפריש -
קשה, ששם מיירי בפועל שלא מאמין לבעל הבית. אז, צריך הפועל להפריש. כאן, אולי מיירי בבעל הבית שנאמן. ותו"ת.
** מן האבוס -
נראה שהחילוק הוא שאם נותן לו מזון עם שאר פועלים, היה צריך להפריש מכולו, ובעל הבית יפסד יותר. יש לדון, שיפריש על קצת ויתנה בלבו, כמו לעיל.
** בישראל
- מעניין שכיון שהוא מקפיד לעצמו, אסור לאכול טבל. ותו"ת.
** יב: אפי’ תגדרנו -
עיין במה שמבאר תירוץ גמרא. היה נראה לומר שהתירוץ הוא שעושה שפעם זה לא אוכל איסור. לא אומר כן, אלא אומר שאפשר שיפריש לעולם. באמת גמרא משמע כמה שאמר פ"מ. זה משמעש אין טוב במה שפעם אחת לא עובר. ותו"ת.
ויש לדון, שאולי אף היה אפשר לומר אותו תירוץ שכתבנו, אלא אומר עוד טוב שבא. ודחוק, שמה שכתבנו הוא פשוט ביותר. ותו"ת.
** נתנו
- לכאורה, ר"ל שאין לחם דבר הנקנה, ורק נותנים דבר הנקנה בדמי שביעית, ולא שביעית עצמו. ויש לדון קצת למה, שהם נותנים שביעית עצמו למי שיתן להם ממון לו, שהרי יש להם ממון שביעית.
** שנייא היא -
זה מעניין. לכאורה, אומר שנופל בגסה. לא מניחים שהוא מפקיר אותו- אף שהוא עצמו הפיל אותו- כיון שהוא גסה. מסתמא, מניחים שיחזור לו. כיון שאחד לקחו בדקה דקה, אז מניחים שהוא מקפיר אותו. זה מעניין. לכאורה, הוא מפני שלא ילך לאותו איש כדי לקבל מדה דקה.
** קצת צריך
ביאור למה מי שמפקיר פטור, שהרי מוציא אותו מתחת ידו, כמו במוכר. צריך לומר שהוא מפני שלא בא מתחת ידו ליד אחר, ואז אינו כל כך גורם של אכילתו באיסור. ותחשב.
** שהמבקיר -
עיין בפני משה. מבאר שיוצא להיות הפקר כשמגיע לידי הקונה, ואז קונה. זה מעניין; הוה אמינא שהקונה קונה אותו ממנו. לכאורה, כן מוכרח משיטת רבי יוסי עצמו, שבזה אוסר לנודר לתת לנדור. ותחשב.
** חזקיה אמר
- שורה- עיין במש"כ. יש להעיר שבדפ"ו, נכתב כך:
בלאה דמפקיר מפקיר בלאה בלאה בלאה בלאה בלאה הפקר בלאה בלאה….”
אם כן, אפשר, אבל לא כל כך מסתבר שבא משורה שלמעלה, ששם כ’ מפקיר, ולא הפקר, ועוד שאינו ממש על גבו. ותח’.
** לא
- יצרן- לא הבנתי מה אומר כאן. עיין במפרשים אחרים, שאומרים פשטים אחרים.
** ג-ב יג: ציבור -
כיון שכן, צריך ביאור למה צריך להחזיר לו דמי מעשרו (ר"ל, ליקח אותו שעשר). לכאורה, דמי תשעה מעושרים שווים לדמי עשרה שאינם מעושרים, שמי שקונה מעשר. ותחשב. ויש לדון, שאולי ע"ה קונים. גם יש לומר שיש נפק"מ בטובת הנאה. עדיין, אז, רק צריך לשלם אותם דמים, ואינם שווים, לכאורה, לדמי הפרי.
** ג-ג כהנא אמר -
לא הבנתי מה מוסיף על המשנה, שלכאורה אומר כן בפירוש.
** יד. גידורו -
לא הבנתי כל כך מה מילה זה אומר.
** ג-ד סדקית -
לא הבנתי החילוק.
** טו: טעם -
צריך ביאור למה שאלו לטעם. נראה שלא הניח שיפסוק כן באותו מחלקת תנאים. ותו"ת.
** כפירותיו -
קשה איך נאמר שהוא כפירותיו שחייבים ודאי, שאולי לא החליף אותם. ותחשב.
** טז. מודה ר"ש -
לכאורה, זה אומר שר"ש ורבנן לא חולקים כאן, שהרי זה וזה מודים שמפרישים דמאי, שלרבנן רק ספק הוא. יש נפק"מ אם נוטל ממון שבט בשאר ציורים של מעשר מעכו"ם. ותחשב. עיין בגרח"ק, שלא פ’ כן, אבל נראה שצריך פני משה לומר כן, כפי מה שפירש במשנה. אולי רק פירש כהוה אמינא.
** טז: ג-ו רבי יוסי -
לא הבנתי חילוק זה, שצריך ביאור ל"ל יהיה חבר מוציא מתחת ידו כאן. אולי ר"ל שלא רוצים להרגילו להוציא מתחת ידו. דחוק.
לולי זה, היה אפשר לומר שרשב"ג סובר שלא מכוונת לגזול, ואז אינו נחשבת רמאי.
** רבי יוסי -
אם סובר שלא מורה היתר, לכאורה, נחוש שכל אחד יחליף, ולא רק חמותה. ותחשב. אולי חמותה תעשה כן כיון שאף אם ימצאו מה שעשתה יאמרו שרק הורה היתר. ותו"ת.
** ג-ו אירוסין -
עיין בפני משה שמבאר השאלה. יש להעיר שלכאורה,  יש עוד סיבה שאין דין זה נוהג בארוסה, והוא שאז לא תחליף כיון שאל בא המזון לבתה, שאין הבעל חייב במזונות שלה. צריך ביאור למה אין זה נכון. ותו"ת.
** יז. מפני שאימת שבת -
קשה ל"ל יכול לת’ כמש"א לעיל, שהוא מפני אותו אחד מאלף. ותחשב.
** יום טוב שהוא סמוך -
צריך ביאור למה ייתלה בהיותו קדושה אחת או לא, שלכאורה, יש כאן כבוד שבת ויום טוב, ויש כאן מה שלא משקר, ואין זמן אחר להרים. בענין שני י"ט של גליות, היה אפשר לומר שתולה אותו באם יכול להתנות על כלכלה (כמבואר בערובין וביצה), אלא שזה אי אפשר בשבת ויום טוב.
** בשבת
- ק"ק, שאולי לא הדירו עד לאחר זמן.
** שאלו
- לא הבנתי פשט שני שאומר.
** יז: ברם הכא -
לא הבנתי למה בתרומת מעשר אי אפשר לשאול לו בדרך כבוד.
** יח. שאסור לחבר -
לכאורה, ר"ל שאסור לו לאכול בסעודה שאין בו שם לעולם, ואף בלי חשש מעשרות. כן נראה ממה שמציינים לגמרא פסחים. לולי זה, היה אפשר להסתפק.
** רבי אליעזר -
לא הבנתי למה אין אומרים כן אף במעשר עצמו, שאף טבלו במיתה. אז, מה שחוששים למעשר ראשון יאמר שחוששים שמעשר עני גם כן.
** הא שני צריך -
צריך ביאור למה צריכים משנה זה לומר כן; נלמד ממה שאין משנה שאומר שנאמן. ויש לדון.
** ראשון שיש לרבו -
קשה, ששני נאכל לבעל.
** יח: טוענו -
ר"ל, שטוען טענה שאינו טענה (יש לציין לשיעור של רב שמעי).
** מי שקרא שם
- לא הבנתי למה מדגיש פני משה מה שישראל מפריש אותו.
** יט. ואני נותן מעות -
יש לדון מאיזה ציור בא למעט:
1. אם שלוחו משלם, ולא מחזיר מעות לשלוחו.
2. אם נותן כבר מעות לשליח, ואז לא ישלם לו.
לצד 1, הענין הוא שכיון שבא ממון שולח, יזהר שליח לעשות כרצון שולח.
לצד 3, הענין הוא שיותר קשה לעשות נגד רצון משלח, שלא רק יכול להניח לו ולצאת, אלא צריך אף לקבל ממנו דבר.
** אינם נאמנים -
יש לדון למה זה חלוק מרישא של המשנה. נראה שהפשטות הוא שהחילוק הוא רק כמה צריך תקנה, שבראשון צריך תקנה, כיון שה וא אורח, ובסיפא לא צריך כל כך. גם אפשר לומר שיש לחוש יותר לגומלים כששני חמרים הם, שלכאורה מצב כזה, שאדם זה גורם שזה נאמן, קורה בכ"פ, שרוב אין מכירים אותם, אבל בשני בעלי בתים, אין זה קורה כל כך, ואז מסתמא לא כבר קבעו להיות גומלים זה לזה.
** תקנת אורח -
לא הבנתי למה צריך תקנה, ולא רק יכול לעשר.
** יט: שלא בפניו -
מפני משה משמע שיש הוכחה ממה שאל אמר בפניו. זה לא נראה כל כך, שאולי רק היה ירא ממנו. אלא, לכאורה, הענין הוא שאין ראיה אלא אם כן אומר בפניו. ותחשב.
** כא. מפריש על דבר שאינו שלו... -
לא הבנתי שקלא וטריא של גמרא כאן כל כך. לכאורה, גמרא מקשה כאן שאי אפשר לישראל להפריש את תרומת מעשר, כיון שאין המעשר שלו. (באמת, זה לכאורה תלוי במחלקת תנאים בגיטין אם ניטל באומד ומחשבה כתרומה). צריך ביאור, אז, מהו המשך גמרא אחר כן. ותחשב.
** תניי בית דין -
יש לדון איך בית דין עשו תנאי כזה, ואם יהני כוח של הפקר בית דין היה הפקר. ותחשב.
** פוחת או מוסיף -
קשה, שלכאורה, עכשיו יש סכום מעשר שצריך לתת על פי התורה, ואי אפשר שלעולם יהיה פוחת או מוסיף יותר מדי. ותחשב.
** כא: העוקץ -
לא הבנתי כל זה כל כך מדברי המפרשים, אבל נראה שלולי דבריהם הפירוש הפשוט יהיה שגמרא אומר שאם מפריש עשר כשהיה לו להפריש תשע, מה שקורה הוא שמעשר שיש בו נתפשט על כולם, עד שיש לכולם דרגא שווה של מעשר. אז, הפרשת אחד על שאר הוא הפרשת תרומת מעשר מעלייא. כשאחד גדול מן שאר, יש בעיות:
1. נמצא שאז צריך להתפשט המעשר על מעשר אחר שיש לו עד שיהיה כולם שווים, ואף שאותו דבר שיתפשט עליו לא היה מאותו מעשר של דבר גדול זה.
2. נמצא שחלק מעשר שעל דבר גדול היהי שווה רק על פי פרופורשיי”ן, אבל לא יהיה שווה ממש.
3. אז, נמצא שגמרא רק אומר שאותו מעשר נתפשט על כולם. ותחשב על כל זה.
4. כב.
5. מנפול- אולי מילה זה יש לו יחס עם מילה שבאנגלית של “מונופולי.” ויש לדון, שלא רואים לאיש זה מונופולי.
6. רבי מאיר אומר- עיין בפני משה שמבאר למה אין זה קשה על משנה שלעיל. יש להעיר שקל לבאר מה שאומר רבי מאיר, והו א שרבי מאיר חושש לדפוסים אחרים כיון שמסתמא אופים אחרים יעשו דפוסים אחרים, שאין כל אחד ואחד עושה דבר שווה. לא חושש שאופה אחד יעשה דפוסים הרבה מחיטים חלוקים, שלמה יהיה כן, ולמה ישנה מה עושה.
7. רבי יהודה אומר- יש לדון אם סובר שנחתום עושה כמה דפוסים, ואז אין הוכחה שמשנה מנחתום לנחתום, או שסובר שאין פלטר קונה משני נחתומים, ואז צירך לומר שאותו נחתום עושה כמה דפוסים. ותחשב ותבין.
8. טפוס אחד- ר”ל, שואל אם צריך מה שיודעים שאחד קנה מיותר מאחד בלחוד, או בצירוף מה שיש לו כמה דפוסים. כמובן, יש גם נפק”מ, אף אם יש לו כמה דפוסים, אם יכול להפריש מדפוס זה על זה.
9. כמה דתימא- לכאורה, אין צד שנניח, אז, שיכולים להפריש משל פלטר זה על של פלטר אחר, שנחוש לשאר, כמו שחוששים למנפול אחד[fn:2], אלא דן אם מניחים שאותו אחד מיותר קנה כולו מאחד או מכולם. לכאורה, הצד להניח שקנה מכולם הוא שלא מסתבר שאחד עשה כפל של שאר. ותחשב ותבין.
10. הלוקח מן העני- לא הבנתי דין משנה זה, שאין עני צריך להפריש דמאי. ועיין לעיל, שהיה מבואר שיש מקומות שצריך עני להפריש מדמאי.
11. כב:
12. לא הבנתי למה יש כל כך נפק”מ בבלילתם ושוב הפרשתם, שלמה אדם ירצה לעשות כן. אולי אין הכי נמי, אלא משנה דן אם יכול, ואף שאין מרוויח כל כך. וצריך לחשוב.
13. מתניתין פליגא על רבי יוחנן- לכאורה, כל שכן שפליגא על רבי יוסי. שוב ראיתי שכן כתב גרח”ק.
14. אחד מחמשים- מפרשים מבארים שצריך לחלק הכל לחמישים, דלמא מתרמי.... לא הבנתי ל”ל אומרים שנחלק אחד לחמישים, ונסמוך שמא מתרמי....
15. הדא דתימר- קאי על הרישא (מתי מהני כשהוא באותו חבית).
16. רבי ירמיה בעי- לא הבנתי כל כך למה יהיה חלוק. היה אפשר לומר שהחילוק הוא שכאן נראים חלוקים. לא נראה כן, שפני משה מפרש שלא ממש נראה חלוק, אלא זה רק עלילה שאומר כדי לשאול לו. אולי אם משיב לפי תומו, חוששים שישקר. תחשב למה, שבדרך כלל, להיפך הוא. אולי חוששים שזה דבר שיעשה שישקר, שלא רוצה שבני אדם ידעו ששינה מקום שממנו קנה. צריך ביאור למה. ותחשב. אולי אז בני אדם לא יקנו ממנו, אף אם אוהבים מה שמוכר, שאולי לא ימכור אותו עוד. ויש לדון, שאף יבואו יותר בני אדם שלא אוהבים מה שמוכר, שעדיין יש צד שיאהבו מה שימכר לאחר זמן. ויש לדון, שאולי טוב להיות וודאי לחצי הבני אדם מלהיות ספק לכולם.
17. אם מעשרים הם- צריך ביאור איך נדע זה באופן שלא יהיה הדין פשוט. יש לומר שאמר לנו, ואז אין יודעים אם מעשרים, שזה לא ידע לנו, אבל יודעים שהוא יודע. ותחשב.
18. כג.
19. עיין במה שכ’ פנ"מ שיהיה דשיל"מ. מעניין, שלרש"י, ענין דבר שיש לו מתירים הוא שלא נסמך על ביטול בלי צורך. אם כן, אם אין תקנה, היה נמצא שמותר לו לאכול אותו. ותו"ת. (אולי אף פנ"מ אומר כן, ולא מכוון לומר שלא יבטל, אלא שכיון ש"אין לו תקנה,” יבטל.)
20. כג:
21. תרי כל לקבל- משמע שהראיה לפני כן היה ממה שזה תרי וזה אחד. אבל קשה, שלשון גמרא היה משמע שהראיה היה ממה שר"ש ור"מ הלכה כר"ש. אולי כוונת גמרא הוא שכללים אלו הם רק במחלקת של יחיד, אבל כל תרי מקבל כל תרי. מוזר למה זה יהיה. נראה אפשר שאף אם אין הלכה כזה, או אין הלכה כזה, יהיה הלכה כשניהם, שאין הלכה ככל אחד כיון שהוא עליל לטעות מיוחד, אבל חברו עליל לטעות אחרת; אז, מה ששניהם חושבים כן מוכיח שאין שום טעות אחד.
22. כד.
23. ג הם- בגירסא שלנו, רק מונה שנים. לכאורה, סומך על מה שנאמר לעיל (לוקח מן הגוי). היה אפשר לומר ש"ג הם" ר"ל ששלש בני אדם אלו נהגו כן, אלא שאז לא מיירי בציור שלנו כלל, וזה לא נראה. ותחשב. עיין בגי’ של פני משה.
24. זה- הטבל בטל- אולי סובר שכיון שצריך מעשה לתקן אותו, אינו דבר שיש לו מתירים. גם אפשר שסובר שאין לו תקנה, שאי אפשר לו לקנות טבל, ואז הוא דבר שאין לו מתירים.
25. אר"ז- אין הכהן צריך… דמים- לכאורה, הענין הוא שבכל זמן שהוא תרומה שצריך לתת דמים, אף אם לא מדברים בענין דמים, צריך כהן לתת דמים, שמניחים שעל דעת כן עשו. כאן, שלא צריך לתת תרומה, לא מניחים כן. מה שמניחים כן בדרך כלל הוא אולי מפני שהכל נותנים זה בשביל מעות, ולא בחנם, ועוד שמסתמא כהן יודה, שמוכרח שדמי אותו חתיכה הם מועטים, שלא יכול למכור למי שאינו כהן. כאן, אינו כן, שאינו תרומה. ועוד, שאין להוכיח שמוכר אותו, שאולי כמו שנותן אותו לכהן, בלי צורך, אף לא רוצה ליטול דמיו, בלי צורך.
26. כד:
27. מספק- לכאורה, צד שני בא לחלק לומר שספק דאו’ לחומרא רק מדרבנן, ובזה חולקים. ויש לדון, שאולי אומר שהוא כספק דבריהם, שלא עשו ברנן כל דינים של דרבנן עליהם, אלא נהגו עמו כספק.
28. כה.
29. במאמינו- נמצא- מחודש- שלא צריך שליחות לזה, אלא אחר יכול לעשות כן כיון שאל מקפיד.
30. כה.
31. החוכר- אי אפשר לתרומה שתעקר- צריך ביאור מה זה אומר.
32. כה:
33. תפשה מדת הדין- לא הבנתי, אז, למה חוכר לישראל אינו צריך לשלם. אולי רוצים שיותר בני אדם יחכרו להם, ואז מסייעים לחוכר.
34. רבנן- גמרא מוכיח שרבנן סברי שתפשה…. לא הבנתי הראיה, שאולי רבי מאיר ורבנן שחולקים באם חייב אף במעשר לא חולקים מהו מדת הדין, אלא חולקים באם יש קנס. ותחשב.
35. קנסו חכמים- מבאר שחכירה יותר טוב לשניהם. ואם תאמר למה יש שום מי שעושה קבלנות. ויש לומר שאף שרוב בני אדם אוהבים חכירות, יש שאוהבים קבלנות, שמצבם חלוק או דעתם חלוק. ותחשב.
36. ואם תאמר איך אפשר שחכירה טוב לשניהם. ויש לומר שבעל הבית רוצה במה שבוודאי לא יפחות מאותו המנין, ואף שעל פי הרוב, נחסר, ואריס, שבין כך ובין כך היה תלוי בכמה יש בשדה, רוצה בדרך זה שבדרך כלל ישכר. אם כן, נמצא שמה שרוצה אריס הוא, באמת, שיתן לו בעל הבית שכר, ולא שיקבל ולא שיחכור. נראה שבעל הבית עושה כן כדי שיעבד יותר טוב, שאז יהיה תלוי במה שהוא עושה בתוך אותו שדה.
37. כו.
38. שלך אסור- לא הבנתי סיוע זה בבית הגרנות. בדרך כלל, מסייע בבית הגרנות הוא כהן שנותן דבר כדי שיקבל תרומה.הבעיה הוא, לפי רש"י, שאז נראה שלא נוטל התרומה בתורת מתנה, אלא בתורת שכר. כאן, אינו כן, אלא נותן הכהן את התרומה בחילוף דבר אחר. ותחשב.
39. גם צריך ביאור למה אין מסייע בבית הגרנות כשהמעשר שלו, שאז לכאורה בא לו מפני שהוא מסייע בעל הבית, והוא אריס שלו. ותחשב.
40. עיין בתוך נייר שכתבתי על זה.
41. מתניתא פליגא על ר"י- קשה, שכבר כתבנו שמשמע מפני משה שחולקים רק בכהן (שלכן גורס לעיל כוהן במתניתא). אם כן, קשה ל"ל אומר שמשנה זה מיירי בישראל.
42. באמת, עיין לקמן בגמרא (בשאלה דר"ז) שמשמע שרק חלקו בכהן לישראל. וצריך ביאור.
43. ברוצה- חידוש הוא שיכול לחלק לשני כוהנים.
44. ברוצה- מעניין שזה מתיר סיוע זה. שמעתי שרדב"ז כ’ שאז לא נראה ככוהן המסייע. ותחשב.
45. לא אגיבון- מקרא- עיין בפני משה, שמשמע שדנים בכוהן שלוקח בכור מישראל (ממה שכ’ שאומר ש"יתננו לי"). אם כן, צריך ביאור ל"ל אומרים שקרא אומר שאין עיכוב מכוח ישראל, אבל אולי יש עוד עכבות, כמו איסור על הכהן. תחשב. אולי אילו היה איסור סיוע, היה אסור לשניהם.
46. כיון שנראה שפני משה סובר שדן בכוהן הלוקח מישראל הבכור, קשה מה מקשה גמרא שצריך לומר, אז, שחולקים בישראל מישראל. קשה, שיש לומר שחלקו בישראל מכהן, שמגמרא לעיל משמע שיש חילוק. ותחשב.
47. המקדש- נראים כעין שני מחלוקתים שמניח בתוךך מחלקת זה, והוא אם יש איסור של מראית עין כאן, ואם הטובת הנאה ממון. אז, צריך ביאור באיזה חולקים. אולי כיון שהוא אסור, אינו ממון. ותחשב.
48. כהן אחר- עיין גרח"ק. צריך ביאור, שלכאורה ההיתר כאן הוא שלא נוטל תרומה של זה, אלא שהוא נוטל חלק קרקע, ונוטל תרומה לכל החיטין, ונותן לעצמו. אם כן, לא נוטל כלום בחילוף תרומה. אם כן, אף לחברו מותר. אולי אז יש מראית עין. לכאורה, מה שאין כל כך מראית עין לראשון הוא שהיה כבר שלו. צריך ביאור.
49. אלא- לשון זה מוזר, שלכאורה עושה חלות חלוק כאן, ואין זה אופן אחר. אפשר שמוכר לו הכל, ומחזיר לו ומשייר.
50. מעניין שיכול אדם לשייר לעצמו דבר שאין בו ממש ודבר שלא בא לעולם. משמע שאין הבעיה בהיות קנין עליו. ותחשב.
51. כז.
52. והאיך אפשר- משמע שק’ גמ’ הוא איך עושים מעשה קנין עליו. עיין בפני משה שלא משמע כן. צריך ביאור מה מקשה לפי פני משה. אולי מקשה מה יכול להשתמש בו. קשה, שלכאורה קצת פשוט הוא. שוב ראיתי ברש"ס שאומר שקונה בקין אגב, וכן אני חשבתי לומר כן.
53. צריך ביאור מהו ראיית גמרא מכאן, שהרי זה רק אומר שיכול לעשות מעשה קנין או כדומה. קשה מה מוכיח מזה. ותחשב.
54. אסור- נמצא שאסור לישראל להתנות ליתן כן לכוהן. צריך ביאור איך נבאר כל הגמרות לעיל לפי זה. ותחשב.
55. ירושלמי- לכאורה, אין השדה בירושלים, שאי לאו הכי, בין כך ובין כך הוא עולה. אולי כיון שנגמר שדה, אינו עולה עוד. ותחשב.
56. כח.
57. שוין- לכאורה, כל גמרא זה קשה לפירוש רמב"ם שהובא בפני משה. ותחשב.
58. פליגא על רבי יוחנן- לכאורה, המשמעות שהוא רק חומרה מדרבנן בא מלשון רבי יוחנן (חומרין), אף שהיה אפשר לומר שרק ר"ל שמחמיר. ותחשב.
59. פליגא- לא הבנתי זה כל כך, שמקושיה זה, ומתירוץ גמרא, יוצא שמה שהוא חומרא אינו רק החיבור, שאף בלי זה היה אסור למכור, מחמת אותם שלא הוכשרו, אלא ההכשר עצמו. אם כן, קשה איך מחלקת של אותו הכשר תלוי במחלקת של קטן וגדול עולה עמו או גדול וקטן עולה עמו, שאותו מחלקת תלוי בחיבור. ותחשב.
60. דרבי מאיר- ק"ק מהיכי תיתי שדנים במוכר במדה גסה, ולא במדה דקה (ואף לרבנן).
61. ומתקן דמאי- קשה, שאולי מתקן וודאי (שמשנה לא אומר דמאי).
62. כח:
63. דמאי- לכאורה הוא דמאי כיון שאולי כבר הפריש על חלקו.
64. דמאי- יש לדון למה מפריש על חצי, שאולי החליף כולו. ותחשב.
65. שכל קלח- לא הבנתי למה נחלק, שעל כל אלו גם כן יכולים, לכאורה, לומר ברירה.
66. צלם- דנראה כמחליף- מעניין, שכיון שהוא ספק, היה נראה לומר שאסור לא מפני שנראה כן, אלא מפני הספק. אולי סובר, וזה יהיה חידוש גדול, שאיסור ספק אינו מחמת הספק, אלא מחמת שנראה כוודאי. ותחשב.
67. גם יש לומר שכאן אין כל כך צד שהוא אסור, והיה מותר אילו לא היה נראה כוודאי. ותחשב.
68. כט.
69. אם החליף- לכאורה, הענין הוא שאז קנה לעצמו, והוא חבר, ואז לא עשר לו המוכר. ויש לדון איך יודע מוכר שהחליף אותו. אולי מיירי בציור שאמר לו. אם כן, לא צריך ממש להחליף לו, אלא רק לומר שהחליף לו.
70. מן השוק- צריך ביאור למה צריכים לתלות בז"ה ולא לתלות שהשולח עישר אותם. ותחשב.
71. מעניין שפני משה קורא לפה שאסר מגו. ותו"ת. ודע שגמרא עצמו מחלק בכתובות ביניהם; צריך לומר עדיין יסודם שווה, אלא שהפה שאסור הוא יותר חזק. ותחשב.
72. כט:
73. המזמין- לא הבנתי איך יכול להפריש על של חברו, כיון שאינו שלו. אולי הוא כעין שליח לחברו, כיון שמסתמא היה רוצה חברו בו, כיון שהוא חוב. ותחשב.
74. אפשר שמפריש מה שהו א שלו לאחר זמן. אם כן, עושה שהחלות חל בשבת. עיין לקמן בגמרא שיבאר מתי חל ההפרשה.
75. המזמין- לכאורה, זה ברירה. ויש לדון, שאולי הוא מה שהוא במערב עכשיו, ולא מה שיהיה שם לאחר זמן. קשה, אז, איך יודע שלא אוכל ת"מ. ותחשב.
76. היה החנווני חרש- פועל- ואם תאמר אם כן איך איסור, שהוא חרש. ויש לומר שהוא כמאכיל בידים. גם יש לומר שהוא אסור כיון שבא לו הנאה, ולא כיון שמאכיל.
77. למען תלמד- ק"ק איך יתיר קרא, כיון שאינו אלא שבות, אם אסור.
78. מורה- קשה למה בא לו זה על שקיים דין זה, שהוא שבות. ותחשב. ושוב ראיתי בפני משה שמניח שכאן היה שעת הדחק, ולכן היה יכול להתיר, אבל בדרך כלל, יש איסור. ותחשב.
79. ל.
80. צריך שיהיה זכור- לכאורה, הוא מפני דין של ר"ע גבי אשה שחושבת שלא הפיר לה בעלה. אם כן, עדיין קשה למה צריך ללחשו בפיו.
81. למפרע טבל- קשה ל"ל אומר שעכשיו יש תרומה, והתרומה הוא מה שהוא על גב חולין כשמשאר. ותחשב. גם קשה ל"ל עושה שהוא תרומה מיד אחר מגביהו, שלא צריך להניח דבר מוקצה שהוא בידו. אולי יהיה אסור ליטול אותו כיון שייעשה מוקצה. גי"ל שטבל גם כן מוקצה, לולי מה שיהיה חולין ואז מותר, אבל כיון שחלק מזה לא יהיה מותר, נשאר מוקצה.
82. מבכר לכשאשתה- צריך ביאור מה זה אומר ואיך זה מתרץ כל קושיות הגמרא.
83. ולא נמצא- תולה במה שהוא למטה ולמעלה. צריך ביאור למה תלוי בזה. היה נראה לתלות במה שהוא רבים, אבל זה אינו אפשר כאן, שאם כן יאמר שישאר רוב חולין. ותחשב.
84. שמא תבקע- קשה, שכאן לא קבע מה שישאר בשוליים לעולם, שמסתמא יוציא אותו עם הארץ. אז, צריך לומר שהרים מה שנשאר שם באחרון. אם כן, אפשר אף אם נתבקע הכוס. אם כן, קשה מהו החשש. ותחשב על זה.
85. ל:
86. עשו שאינו מאמין- לא הבנתי אותו דין כל כך. הציור הוא שכב נתן לעני ולוי, ועכשיו רוצה לסמוך על זה לאכול השאר. צריך ביאור, שהרי כבר הפריש, ומה לנו אם נאבד. יש לומר שרק אמר לו ליקח אותו, אבל לא קח כבר. קשה, שאפילו נשרפו פירות, מהני, כמו שאומר גמרא. אולי לא ברר סאה, אלא אמר לו לברר לעצמו. אז, לא חל עד שמברר.
87. גם יש לומר שלא נתן תרומה כבר, ולא רוצה, אז, שיחול קודם שנותן תרומה. ותחשב על זה.
88. בעל הבית- צריך ביאור מהו הדמיון. לכאורה, הוא רק מה שבשניהם יש אדם שאינו מאמין לחברו. קשה, שכל דאמי הוא כן, לכאורה. ותחשב.
89. רבי יוסי- עיין בגיטין (כה:) ובכמה מקומות בבבלי, שמבואר שגם רבי יהודה נשנה במשנה זה.
90. ומיחל- עיין ברש"י בגיטין, שכ’ שמחלל ושותה. נראה שכיון שכבר סומכים על ברירה, סבר פני משה שלא צריך זה. עיין במה שבארנו בחברותא קטן על זה; אולי מחמת זה חלק פני משה (עיין שם).
91. טעמא דר"י- לא הבנתי טעם זה (למה שייך נתינתו בכלי אחר). שוב ראיתי שאחר כן גמרא מפרש שר"ל שאין ברירה. צריך ביאור איך זה מטעים עם מה שמפרש פני משה כאן. קצת מנסה לבאר כן בפני משה לקמן, אבל לא הבנתי מה שאומר.
92. דרבי שמעון- לא הבנתי איך יודעים שכן סובר רבי שמעון, שאולי רק חושש לבקיעת הנוד. אולי רק ר"ל שיכול לסבור כן.
93. לא.
94. תמן- הנבתי החילוק (הוא שכאן החשש הוא שהכל אסור, אף מה שהיה בזמן שהיה קיים, אבל כאן החשש הוא למה שיהיה בזמן שאינו קיים), אבל לא הבנתי המחלק כאן, שהרי לכאורה בשניהם יש חשש שווה לאיסור. מפני משה משמע שבאחד יש חזקת תרומה. צריך ביאור, שלכאורה מה שצריך הוא חזקה שהוא קיים, וזה יש בשניהם. ותחשב.
95. לב:
96. מודים חכמים- לכאורה, משמע שאם אמר זה ואחר כך זה, שחל הראשון, רק ראשון חל, אבל אם אמר שיחולו שניהם בבת אחת, שניהם חלים. קשה, ש"כל שאינו בזה אחר זה, אינו בבת אחת.” אולי אין ירושלמי מודה לכלל זה.
97. מפני שקבע- היה אפשר להקשות את זה מיד כשמוקים משנה כרבי מאיר. ותו"ת. לא אפשר לומר שהניח שמשנה אינו בתוך כדי דיבור, שאם כן, אין להוכיח מזה כלום לענין מחלקת רבי מאיר ורבנן. ותחשב.
98. לג.
99. נוטל- אין בו איסור לזרים- קשה מה לנו בזה, שהרי מטבל, ואז יהיה עדיין אסור. וצריך ביאור.
100. אם לשם מאתים- צריך ביאור מה אומר. אולי מה שאומר הוא שצריך להפריש כל הששים. לכאורה, אין זה נכון, שאין צורך להפריש כל הששים. אפשר שאומר שצריך להשלים כשמפריש הי"א. קשה, שזה פשוט, ועוד שלשונו לא משמע כן. וצריך ביאור, אז, מה אומר.
101. גם צריך ביאור איך מפריש כל העשר מכאן. לכאורה, צריך להפריש עוד חצי מן המאתים. אם כן, ירבה בתרומת מעשה, ולכאורה יהיה מקולקל. צריך ביאור. אולי מתנה.
102. ואם לשם אלף- צריך ביאור מהו סברה זה, שאולי כוון לתת רק מעשר ראשון מחברו. צריך לומר שלא מניחים כן. ותחשב על זה.
103. על כל תאנה ותאנה- צריך ביאור קצצ מה שכל כך לא דק, ומחלק הכל עד שיש פראקשינים. ותחשב. וצריך לומר שאינו קשה לגמרא להיות לא מדקדק כך.
104. עדיין צריך ביאור ל"ל מונים בתוך מעשר של הכא (עיין בפני משה) מעשר שני. וצריך ביאור.
105. משנה- ביאור המשנה כן הוא לפני משה (וכן כ’ רמב"ם) הוא כך: מניחים שהמאה שנוטל הוא מאה שהם הכי אסורים. אז, רק היה צריך ליטול אותם מאה, וזה די. (צריך ביאור למה מניחים זה.) אבל, אם כן, היה לנו לחוש שיהיה מי שסובר שנטל את ביותר קלים. אז, נוטל עוד אחד. ממה שלקמן צריך ליטול עשר, נראה שמה שזה מהני הוא שהיו בני אדם מבינים קצת אם נראה להם שחוששים לתרו"מ, ואז נוטלים עוד עשר, ומזה ידעו שהמאה ועשר או מאה ואחד הוא של איסור. ותחשב על זה.
106. עדיין לא הבנתי למה נוטל רק אחד יותר אם נתערבו מאה של מעשר עם מאה של טבל. ותחשב.
107. גם לא הבנתי ל"ל אומר פני משה שמניחים שתשעים ראשון שנוטל הם מעשר, שאמר לעיל שמניחים שמה שנטל הוא מעשר, כיון שיש בו יותר איסור. ותחשב.
108. לג:
109. לכפול- זה מחודש, שהרי כאן, באר מה יקרה על שני הצדדים, דלא כתנאי כפול בדרך כלל, אבל רק לא באר מתי לא יחול זה (אלא רק אמרו כשאמר שדבר אחר חל). ותחשב.
110. רבי אליעזר בן ערך- צריך לומר שנפל עד שיהיה ביטול. זה רק אם נפל מאה מטבל לתוך חולין או כדומה, אבל לא בציור שנפל מאה של מעשר לתוך מאה של חולין. ותחשב.
111. כדעתיה- אינו כל כך כדעתיה; הענין הוא רק שכאן זה אומר שצריך לברר איזה מקום נעשה תרומה, וכאן אמר שצריך לומר לשון שהוא קל להבין כשעשה מעשר או תרומת מעשר. צריך ביאור.
112. עולה- צריך ביאור איך מפריש לתוכו ת"מ, שמבטל איסור לכתחילה (וקשה למה לא יכולים להפריש לעולם לתוך תערובת, שאז לא צריך לתת כלום לכהן).
113. כיני מתניתא- לא הבנתי כל זה לפי מש"כ לבאר את המשנה, שקל לומר שבמשנה נוטל אחד כדיש שיכיר. וצריך ביאור.
114. ואינו יודע- צריך ביאור למה לא חוששים איזה אחד מן השורה. ותחשב.
115. ויטול שנים- עדיין יש לדון ל"ל אומר משנה  ציור שלא עשה כבר חצי מעשר. ותחשב. גם צריך ביאור מהי"ת שלא נוטל שנים (שיש לדון ממשנה).
116. אלא כן אנן- צריך ביאור מהו הצד שיצטרפו לרביעית. אולי הם נחשבים אחד, מפני הספק, והרי לא צריך לאכול כל כך איסור, אלא חפץ איסור שהוא אותו גודל. צריך לחשוב למה. אולי הוא כדי להחזיב את החפץ (ולא שכשאוכל יותר ממילא עושה יותר רע).
* Footnotes
[fn:1] ואגב, קצת צריך ביאור למה חששו כיון שהרוב מעשרים. ויש לומר שכיון שמאכל כל כך מצוי, כמעט מוכרח אדם לעבור.
[fn:2] אלא אם כן נאמר שתקנו חכמים זה אגב זה, שלא רצו שיהיה נראה כשני דינים שסותרים זה את זה. ודע שאם היינו אומרים כן, צריך ביאור למה יעשו כן, ולא להיפך. ותו”ת.
