* יד:
** ולא קבלו מינייהו -
ק'; הא קל לתרץ שאף לשלמה לא קבלו. ויש לומר שכיון שהיה מלך, היו מוכרחים לקבלו. כיון שקיבלוהו בראשונה, אין לומר שפסקו מלעשותו, אף שקבלו רק מדחק. אפשר שזה מפני שכיון שקבלוהו, נעשה הדין, והיו חייבים בו, או שכיון שקבלוהו, לא היה כל כך קשה להם עוד.
עוד יש לומר שלא מסתבר שיתקנו רבנן אחר שלא היו יכולים לקיימו שני פעמים. ויש לדון, שאולי ידעו- ואמת היה- שיכול אותו פעם.
עוד יש לומר כמו כן שלא מסתבר לתקן אם כבר לא היו יכולים, אף פעם אחת, אלא אם כן היה סיבה שמוכיח להם שאותו פעם יהיו יכולים לקיימו. אם כן, לא מסתבר שלא יקיים בפעם שניה.
גם יש לומר שאם לא קבלוהו, לא היה קרא מקלסו. ויש לדון, שמחשבה טובה מצרף ה’ למעשה.
גם יש לומר שכיון שאמר אותו עם עירובין, משמע שכמו שקבלו את זה גם קבלו את זה (מצאנו כעין זה בתחילת מועד קטן). ויש לדון, שלא יודעים שקבלו עירובין ממנו, שאולי לא קבלו, ורבנן אחרים תקנו.
ותלוי בתי' אלו הוא מה שיש לדון אם תי' גמ' דווקא, או שגם יכול לומר ששלמה תקן ולא שמעו לו, ושמאי והלל תקנו על הקדשים, ותלמידיהם הוסיפו תקנה לתרומה.
** ולא קבלו -
מושג זה, שכיולים בני אדם שלא לקבל גזירה, הוא מעניין. אולי רצה לומר שנעשה גזירה שאין רוב הצבור יכול לעמוד בו. ויש לדון, אז, אם מש"כ בדבור הקודם נכון (שכיון שהיו מלך, היו כפופים…), שאולי עדיין לא היה כוח בידו לגזור כן. ויש לדון אם ענין מה שאין רב ציבור יכול לעמוד הוא סימן לטירחא (ואז, יהא כן כאן) או שכיון שלמעשה לא יעשו כן בני אדם, אינו דין (יש לדון למה), שאז לא שייך כאן.
* טו.
** שחייב אדם לומר -
עיין במקום אחר (ברכות לג:) שמקלס אדם על זה. משמע שאינו חיוב גמור.
** שתיק ליה הלל לשמאי -
ק’ למה לא נאמר שאף אלו היו במח’, ולא נמנו כיון שהשוו. ואולי שתיקה ה"ה חלוק. ודחוק. ותחשב.
* טו:
** אאוירא ולא כלום -
אין זה מוכרח, שיכול להיות שגזרו על שניהם לתלות, אלא שמסתבר לגמרא שהיו מחל’. ועיין גמרא לקמן. ואולי ה"ה אגב גמרא לקמן. ויש לדון.
** מעמיד -
לכאורה, רצה לומר סיבה אחרונה (שהרי, כולו מעמידו). גם יש לומר שמתכת חשוב כאן, שמחשיב את הכל, ועושהו כלי, ואינם מחשיבים אותו, שחשוב כיון שמתכת הוא, ואז הוה עיקר. ותחשב.[fn:1] גם יש לומר- ונראה שזה נכון- שאינו רק כמעמיד, אלא אולי אף כמעמיד כיון שהוא חלק חשוב ממנו, ואז יש לו כוח לקבל טומאה. ותו"ת.
** יש שכ'
שיוסי הוא כינוי ליוסף. יש לדון למה לא מצאנו כינויים אחרים. (ויש לדון, שיש רבא ורבה. ויש לדון אם נקראו כן בימיהם או רק אחרי חייהם. כמו כן, יש לדון אם רק מדפיסים כתבו כן. אבל, יל"ד בזה גם ברבי יוסי, אלא שצד אחרון לא כל כך מסתבר שם.) הראה שאםשר שרב פפי הוא כינוי לרב פפא (ואז היו שני רב פפא באותו דור). ודע שיש הרבה שמות שלא ידועים לנו כל כך, ואז לא יודעים אם הם השם או כינוי.
** בביאור
מתי היו באושה וכדומה, ע' ברשי בר"ה (לא:).
* טז.
** יש להם תקנה -
יש לדון אם כלי חרס אין להם טהרה במקוה כיון שאין מקוה פועל בהם או כיון שטומאה שבהם חלוק.
** תרומה וקדשים -
קשה; יש כבר הכירא בדין שבירה. אולי זה לא מצוי. גם יש לומר שזה קודם. ותחשב. ועיין בתוס’. וצריך ביאור מה רצה לומר (מה לנו בהיכר דאורייתא). ואולי רצה לומר שלא יכשבו בני אדם שזה דרבנן, אלא יחשבו ששניהם שווים, ולא גזרו לסיבה אחרת (אבל בדין תורה, יותר קשה לומר שיש סיבה אחר שיחלק או שידעו דיניו וסבריו, וידעו שהיה לו להיות בכעין זה).
* טז:
** נמנו ורבו -
קשה, שאמר לעיל שהודו והשוו. ואולי רצה לומר כיון שנמנו, הודו והשוו. אולי זה חלוק משאר. ל"נ כן.
** במקומה -
משמע שדנים אי אכתי חול’. יש לדון, שאולי מח’ במקו’ רצה לומר שלא נפסק. יש לדון, שלעולם הלכה בכית הלל. יש לדון, שאולי ב"ל כר’ יהושע, ולא היה בת קול מילתא. (אגב, נראה שמה שמצינו שרבי יהושע יודה לבית שמאי (חגיגה כב.) הוא לשיטתו,) שסובר שלא היה בת קול קובע. עוד יש לומר ששאני בכא שאין רב לב"ה (יל”ד אי ס”ל כן). ועיין ברש"י.
** בכדי טהרתו -
כיון שהגענו לזה, יש לומר כן אף לשיטה אחרת, אלא שרק חשו למת:
1. יכול לטמא יותר, ויש יותר צד לרע.
2. יותר רע. יש לדון אם הנחה זה- שמה שהוא מטמא יותר, טומאתו יותר רע- הוא נכון.
* יז.
** והיה קשה לישראל -
למה.
** הנכנס -
נראה שהוא מן הדין הנזכר בראש סנהדרין שכיון שידוע דין לדיין, לא יכול לסלק את עצמו. ויש לדון אם הוא כן כאן גם כן.
** אם תקניטני -
נראה שר"ל שסובר שאין צורך לגזור זה אטו זה, שידוע חילוק, אב אם אתה עושה שבני אדם לא יבינו חילוק, ויביאו ראיה בזה שהוא טהור, אז אצטרך לגזור עליו. ותחשב.
* יז:
** איכא הא דראב"א -
כיון שהגענו לזה, יש לומר שבזה חולקים רבי מאיר ורבי יוסי. ותו"ת.
** כדי שישורו -
צריך לחשוב על דעת עשיית כלי אדם מח’.
* יח:
** שריק -
א. מסתמא, לא יגלה.
ב. גילה שלא יגלה.
ותחשב.
** בש"א -
יש לדון מה נ’ רע:
א. מכירה.
ב. היותו ביד גוי (אלא שאין חוששים כ"כ קודם יו"ט).
עיין ברש"י ד"ה לא ישכור.
* יט.
** ואינו שובת -
צריך לפרש. (וחושב אני שאולי במקום אחר פירשתי).
** ואם התחילו -
א. מלפני שלש.
ב. לאחר שלש, בדיעבד, אף שהתחיל באיסור.
* כ.
** דגבי האור -
יש לדון למה לא דנים ברבנן, שסוברים מה שחולק על זה. אולי ידע הראיה, וידע שמר"א בא.
** תנא ר"ח לסייועא -
לכאורה, שמואל היה אחריו. ויש לדון. אם כן, מעניין שנחשב לסייעו (עיין רש"י ב"ב מה). ואולי רצה לומר שהובא בבית מדרש לסייע לו
* כ:
** פתילות נמי -
מעניין, שאין פתילה עצמו ממנו.
** דדובשא -
לכאורה, זה נצרך לדין זבת.
* כא.
** לכל נחותי ימא -
מצינו ששאל כ"פ לנחותי ימא, ומצינו שהיה מהלך קרוב לים כשבא רב (שבת קיח).
** גזירה לגזירה -
קשה, שאביי הוא השואל, והוא סובר (לעיל) שבשבת גוזרים.
** דבוץ -
הוה מצי לומר שר"ל לשמחת בית השואבה. ויל"ד.
* כא:
** לאמנועי -
יש לדון אם זה דוחה דין או רק ראיה.
* כב.
** יש בו -
עיין בתו"ת (וישב).
** דתניא -
הו"מ להז’ את זה לעיל.
** וכי נר -
הק’ לי אחד שאומרים "הנרות הללו קדש הם.”:
1. אולי קדש רק רצה לומר מופרש (מצינו כן במק"א), והוא שמופרש למצווה.
2. רצה לומר אסור בהנאה (מצינו כמו כן בכ"מ בקדושין).
3. רבנן נתנו בו קדושה. יש לדון אם יכולים.
4. אולי- ודחוק, וצריך לחשוב- ריב"ל חולק על רב יוסף.
* כג.
** ומדליקה -
ק"ק למה צריך להדליקו עוד, שהרי אף חרש וכדומה כשר. ויש לומר שאל"ה נ’ כלהנאתו.
** והיכן צוונו -
נמצא שלשון ברכה קצת לאו דווקא. מעניין, אז, מה שגמרא מדייק ממנו.
* כג:
** לישתרי אלמה… -
צריך ביאור למה.
* כד.
** דתני רב אושיעא -
משמע שלשון "דתמי ר"א” רצה לומר שכן סבר (דאי לאו הכי, אינו ר"א, אלא שום ברייתא). ויש לדון (אולי כיון שסתמו, צ"ל שסובר כן).
** רב הונא… -
עיין בב"ק קיח. (אותם חולקים כעין זה).
** יש אונדרליין
תחת אינו צריך.
* כד:
** בארבע -
עיין זבחים צא.
** דאתיא בקל וחומר -
ק"ק למה לא אומרים שכאן- משא"כ בצרעת- יכול לקיים שניהם.
* כה:
** חובה -
ק"ק, הא אמר מפני כבו"ש. וי"ל שנרות ה"ה משום כבו"ש.. צ"ל שזה מיוחס לטעם של שלו"ב. ודע שהיה אפשר לומר שרבנן ורבי יוסי חולקים בזה.) גם יש לומר שמה יצא הוא משום כבו"ש. שו"ר ברש"י.
** בית המרחץ -
מעניין שחד דבר הנזכר חוב, וחד רשות.
* Footnotes
[fn:1] רצה לומר, יחס שבין כלי למתכת, חלוק משבין מתכת לכלי, שמתכת עושה כלי חשוב, שעושהו כלי, אבל כלי לא מחשיב מתכת כל כך, שבין כך ובין כך היה חשוב, כיון שהו מתכת. אולי זה עושה שמתכת הוא דבר חשוב שבכלי.
