* טו:
** זכוכית -
דבר המקפיד עליו- סימן/ סיבה.
* טז:
** ודקא -
קשיא, יטמא אף מתוכו. עוד קשה, שיטמא רק על ידי אויר, ולא נגיעה. יש לומר שאין אפשרות לאויר, ואף נוגע טמא בכ"ח. ויש לדון.
** עיין ברש"י
שדן בגילוי שמשמע שלא תלוי במחשבה (ואז, זה רק סימן, ואם היינו יודעים מחשבתו, הייינו הולכים אחריו), אלא בגלוי.
** רב אשי
- זה, לכאורה, אומר שכ"ח לא מקבל יותר, ואין זה סיבה שאין מקוה. ויש לדון, אולי שאני זה שרק נגזר.
* יח.
** אין נותנים קורה -
א. לא ברא משקה כל כך (כבר נברא)
ב. לא שינה חפץ כל כך (רצה לומר, פרי).
ותחשב.
** מידי גבי הדיי -
משמע שברייתא של רב חייא ורבי אושיעא אינו חד ברייתא, אלא שני סדרי ברייתא חלוקים.
* כ.
** בן דרוסאי -
לסטים- עיין ב"מ (בביאור רש"י בביאור מהו אונס). משמע מכאן שלשון יחיד הוא לסטים, ולא לסטם (ויש לדון)[fn:1] (ואולי מה שאין לו לשון רבים חלוק מלשון יחיד הוא שלא יכול לקראותו ליסטימים כיון שזה היה נראה מוזר).
ויש להעיר שמצינו שרש"י אומר "בעלים" במקום בעל, ואז, אולי לפעמים אומר לשון רבים ליחיד.
* כ:
** במה -
לולי רש"י, הוה מצי לומר שקאי על שמן ופתילה, אבל מרש"י נראה שקאי על פתילה בדווקא, ושוב אחר כן מביא משנה דין שמן. ל"נ כן מלשון משנה.
** עץ בעלמא -
ועוד שאם היה מכוון לעץ, היה אומר רק עץ, ולא מפרש איזה מין, שכולם יהיו שווים לזה.
* כא.
** בשמן קיק -
קשה; הרי זה מחלקת לקמן. ונראה שזה קאי על משנה, ומפרש כשיטה ראשונה. ואכתי ק"ק, שלא מפרש שאר.
* כו.
** מה -
בטבלו- משמע שהוא כבר תרומה (דנו בזה אחרונים). ואולי זה שייך למתנות שלא הורמו כמי שהורמו (אולי חולקים בנקודה זה).
* Footnotes
[fn:1] שוב ראיתי ביאסטר"ו שהם שווים, והוא ליסטים עם צירי תחת הטי"ת. אז, לפעמים נכתב יו"ד, ולפעמים לא נכתב.
