* סח.
** רב נחמן -
מראיה שהביא רב ששת, לכאורה, רואים שאין המחלקת אם אהנו מעשיו לפני כן או לא, אלא אם צריך להיות שאהנו מעשיו.
* עב.
** דלא אכלי -
יש לדון אם אומר שלא דקדק בו, וזה משל, או אומר שלא אכל די, ולכן לא היה מדקדק. יש להעיר על צד שני שהיה ר"נ חתן של ריש גלותא, והיה מוזר אם לא אכל כראוי. ותחשב.
* סט:
** כי האי סתמא -
ואם תאמר הרי היה אפשר להקשות כעין זה על כל מחלקת שבש"ס. נראה שאין זה קשה, ששם יש מי שסובר ככל שיטה, ואז יכול להכריע, אבל כאן, הוא ספק, שדן אם חזר מזה או מזה. אז, אולי אינו אפשר לברר. לא הבנתי כל כך איך מחלק, אבל כתבתי החילוק.
* ע.
** סתם יחידאה -
ק"ק, שגמ’ אומר שלא משגחינן בסתם במשנה ומח’ בברייתא. נראה שזה חלוק, שזה אומר שהוא יחיד, ואז לא מסתבר שרבי פסק כמותו, באמת.
** אפלגא -
היה אפשר לומר יותר קל מזה, שלכאורה, שליש ר"ל ממה שיכול להוציא, ואז יש לו שייכות לכל. ותחשב. שאולי לא ר"ל כן.
* עא:
** אשארא -
יש לדון, אז, למה מנה זה כלל, שאין בו חידוש. אולי מחדש שאף לרבי מאיר הוא שחיטה כשרה. קשה, שלכאורה, אין זה נשמע מן המשנה. ותו"ת.
* עב:
** בפנים -
כמובן, צריך לבאר מה נחשב פורתא, שלכאורה, כל פורתא יכול להיחלק. אולי תלוי במה יכול אדם לעשות בזמן אחד. ותחשב.
* עג.
** בגזלנותא -
לא הבנתי, שממה שבאים לבית דין להעיד, רואים שהם סוברים שהם כשרים. אולי צריך לומר בפירוש. יש לדון, שאף בשאר זוממים, לא אומרים כל כך בפירוש שהיו שם, אלא שראו. ויש לדון, שאולי ההזמה אינו על מה שהיו שם, אלא על מה שראו. קשה, שלכאורה, צריכים לומר עמנו הייתם, ולא רק שראינו שאתם לא ראיתם. אז, אולי עדיין צריך לומר שאנו ראינו יותר משמעו שהיו שם. גם יש לומר שלא נאמנים, מפני שאולי הם פסולים. זה אומר שלא רוצים שעד כשר יהיה משקר, ואז מניחים שאלו פסולים, ולכן משקרים. אי אפשר לומר כן בע"ז, אף שאפשר שנניח שהוא ע"ז, ואז הוא נפסל, מניחים שפסל את עצמו בעדות זה. ותחשב.
יש לדון ל"ל מניחים, אז, על כל ע"ז שפסול שגנב חפץ או כדומה. יש לומר שאין להניח כן על זה יותר מעל זה, שאין עדים על אחד מהם לזה.
* עד:
** עינו ושינו -
אם כבר נשתחרר בשינו
או, אם קדם, בעינו,
צריך ביאור פטורו
על הזקת חברו.
אם מניחים שצריכים שטר,
אז, לא נעשה בן חורין כבר.
אז, מתורץ הקושיה,
אבל זה רק לפי אותה שיטה.
אם נאמר לא, אז נראה,
צריך לומר שהוא חד מעשה,
שביחד נעשים זה עם זה.
** אביי -
יש לדון מאי קא משמע לן-
לצד שני, נראה מובן
שיכול לדון שני צדדים:
אם נחשב שני מעשים
או על מעשה אחד, שני חיובים.
לצד ראשון, יש לדין
אם נעשה קצת בן חורין
לכן נתחייב תשלומין.
או אולי על כל שמזיק
חייב לעבדו הניזיק
אלא אם כן, יכול לשחרר,
וזה כבר נעשה בהזק האחר.
** בפלוגגתא -
דברי רש"י תמוהים היו,
שאביי ורבא אחרון חיו.
אז, קשה למה הם הנדון,
שחלקו בו ר"א ור"י במח’ הראשון.
שמעתי ממקור נאמנה[fn:1]
שחי ר"י ארבע מאות שנה.
יודעים שבסוף ימיו.
לפני שהתפללו עליו חבריו.
למד עם ר"א ולא אהב
ללמוד עמו כמו בכל חייו.[fn:2]
אז, אולי לא היו ראשון,
ולכן אינם הנדון.
במקום אחר
חשבנו לבאר
על פי מה שרש"י זה אומר
שבפלוגתא לעולם אומר
שיבוא פלוגתא אחר
שתלוי במה שכבר באר.
ולא שמה שכבר הובא
תלוי הוא בפלוגתא הבא.
נראה אולי שאין זה
הביאור, למעשה,
שאולי רצה לומר ש
אין כל וכל ציור דומה,
אלא לעולם אומרים
חלקו רבני אחרונים
במחלקת של ראשונים.[fn:3]
* עה.
** אליבא דרב… תנאי -
יש להעיר שכבר נדחה
שיטת רב על פי משנה
שאינו טוב לפי שיטה
שעדים שנייים פוטר גברא.
אז, צריך לומר כבר שהוא
תנאי, ואז נראה גם זו
יכול להיות תנאי, too.
משמע שרב לא מסכים
לראיה שלעיל מביאים.
יש לדון איך דוחים
לשיטתו בבאו עדים.
** שכבר אין ל (רש"י) -
היה לו להזמין
מנין של תשע מתפללים.
אולי זה גורם שיחרור,
ולכן אף הוא איסור.
* עה:
** חייב עצמו -
כיון שכבר אמר חילוק זה, היה אפשר לומר שאין רב ושמואל חולקים. אם חולקים, היה אפשר לדון איפה חולקים. על פי זה, אולי אין הדיוק מן המשנה עוד קשה על רב.
** מכרו לגבוה -
נראה שכל דיון זה שייך למה הוא הקדש, אם יש בו קנין לה’ או אם אין בו, ואם יש בו יותר מזה או לא. ותחשב.
* עו:
** כל העומד -
קשה, שעדיין בשעת שחיטה צריך עוד, כמו קבלה והולכה. ותחשב. אולי כיון שנעשו בטוב, אין בעיה. לא נראה, שלכאורה, נשפך דם ר"ל שלא נתקבל.
* עח.
** נדמה -
צריך ביאור איך מניחים איזה דרשה אומר מה. ותו"ת.
* עח:
** מצוה מן המובחר -
משמע שיש על כל פנים צד שמעלה של שור אינו רק שחסר יותר כדי לקיים מצווה. ותחשב.
* עט:
** זה השווה -
יש להעיר שאין זה
נכון שהוא לא השווה.
אפשר שהוא רק מקפיד
שרק יראנו היחיד.
ה’ הוא הרואה תמיד
ומפניהו לא יחליד.
אז, רק יקח כשלא נראה
לבני אדם שרואה.
אבל אם היה לו אפשר
להיות ראיית ה’ נעצר,
ורק להיות נראה לבר
נש, אז היה זה דבר
שהיה רוצה לעשות
ונמצא שאינם שוות.
* פ:
** לא במהרה -
עיין ברש"י. לכאורה, ר"ל שצריך להרבות בתפלה עליו. גם יש לומר שאם אינו כל כך ברורו שתפלתו נענה, לא יתפלל עליו, שקשה ליענות. ותחשב.
* פא:
** אפילו טל -
נראה שהוא מפני שהיה בבל מקום שהיה מלא מים.
* פב.
** והא (רש"י) -
נמצא שרש"י אומר שרבי יוחנן ורבי יהושע בן לוי הם אמוראים (אף שריב"ל בא במשנה האחרון).
ריב"ל היה אמורא,
אף שנזכר במשנה,
במשנה האחרונה.
** מכניס -
אז נמצא
ששמחה
גוררת לה
האהבה.
* פב:
** אהל הטומאה -
מה שלא רוצים אוהל טומאה הוא אולי מפני שיש הרבה טהרות או הרבה אוכלי טהרות. לא רוצים שלא יאכלו או שיאכלו בטומאה.
* פג.
** רש"י לשון סורסי -
עיין בסוטה שהבאנו מאחד שאולי ר"ל שהוא לשון שנתקטן, כמו לשון תלמוד ירושלמי. אין הכרח לזה, שאולי ר"ל שאין הלשון עושה פרי, שאינו טוב לעמוד. ותחשב.
** שתסתלק -
ר"ל, שלא יבוא. ואולי ר"ל שלא רק לא יבוא, אלא אף יסתלק, אם מת אחד. ותחשב.
* פג:
** מכה מכה -
צריך לבאר בכל סוגיה זה מהו הסברה החיצונה, ומה מיותר וכדומה.
** נהורא -
נראה שהחולק סובר שלא רק עשה שהוא סומא, אלא אף נתן מום בו, ועשה שעינו מוזר ורע. אז, אולי עין גדול חלוק מעין קטן. ותח’.
* פד.
** מלקות -
יש להעיר שמלקות במקום מיתה, ואז אולי אינו כל כך דומה.
** אי מיית -
לכאורה, החידוש שאומר כאן הוא שלא חוששים לאותו בעיה לומר שאין עונשים כך. יש לדון, שבמכות אין עונש אחר שאפשר. גם קשה, שאין המשנה שמביא כל כך מוכיח זה.
אם כן, צריך ביאור מה מכוון לחדש כאן. ותחשב.
* פד:
** אין מועד -
עיין במה שבאר. לא הבנתי ל"ל מביאים לבית דין, שאף שאין נפק"מ לתשלומים, יש נפק"מ גדול לעשייתו מועד.
אולי הוא מפני שאין עשייתו מועד גורם ביטול חסרון כיס וכדומה, ואז אי אפשר לעשות שליחות שלהם.
* פז.
** מכל מצוות -
לכאורה, עדיין חייב בקרבנות, שהרי הוא היקש מהיקש. ויש לדון, שאולי כיון שאותו קרא גם קאי לענין דינים אחרים, דורשים.
* פח.
** קטן… ישנו במילה -
יש לדון, שאף שיש חיוב על אחרים למול אותו, ואף שיש צורך שיהיה נמול, לכאורה, כיון שקטן הוא, אין חיוב על עצמו למול את עצמו. משמע שכן הוא אף בעבד, ורבו חייב עליו, אבל הוא לא חייב על עצמו. כן מסתבר, שרק חייב כאשה.
** אין לו חייס -
מעניין שמשתמשים בזה בקל וחומר כיון שלכאורה, אין זה סיבת פסולו, אלא רק דבר שמודיע הדרשה. ותחשב.
** פסולה (רש"י) -
לאו בר עונשים- דנים אם יכול להיות יש בו הזמה כיון שנפסל. אם נאמר שיכול, אז צריכים לומר לרש"י שאין קטן נפסל, שפסולו עונש. ותחשב.
** קל וחומר -
יש לדון, שאולי מילתא דאתיא בקל וחומר כתב קרא. ועוד, שיש לומר שרק כתבו אגב, כמו שאומר גמרא להפך למסקנא. ותחשב על זה.
* צ.
** לא עשו -
עיין במש"כ רש"י בענין שותפים, שכ’ ש"יש לזה חלק בכולו ליטול חצי.” יש לדון אם כולו ר"ל כל החפץ (תחשב, אז, מה זה אומר), או ר"ל כל הקנינים- קנין גוף וקנין פרות.
* צ:
** והא עדים -
יש לדון למה מוסיף גמרא שאומר כן. אולי הוא מפני שאמר עוד "הא,” וצריך לבאר על מה אמר אותו. גם אפשר שהוא מפני שזה דבר שצריך להיאמר כדי שיחייב אותו. ותו"ת.
** ראו בלילה -
אם ראו ביום, כשרים. יש לדון אם הוא מפני שפוסקים על פי ראייתם, ואין זה עדות, או מפני שבזמן שנעשים עדים, היו גם כן דיינים, שאינם יותר ראויים מזה לזה. אז, אי אפשר לשם אחד לדחות את חברו, שאיזה ידחה את איזה. ותחשב, בפרט על השני.
ואם תאמר לצד ראשון, יפסוק על פי ראייתו לאחר זמן. ויש לומר שאינו אפשר, שאז לא פוסק על פי ראייתו, אלא על פי זכרונו. ויש לדון, שאז נאמר שבעדים, פסוק על פי זכרון שמיעתו, ונאמר אותו הוכחה לפסוק, שלא יהיה זכרון שמיעה גדול מזכרון ראיה. וצריך לחשוב על כל זה.
** חוזר ובונה -
קשה, שאולי אז אין ממיתים אותו.
* צב.
** נענה תחלה -
ק"ק, שלכאורה שרה לא נענה תחילה. אולי ר"ל שה’ מחתים אותו דין ראשון, אף שלא קורה מעשה של ה’ עד לאחר זמן.
עדיין לא רואים מכאן שהוא תחילה.
* צד.
** איכפל תנאי רש"י -
נתקבצו- צריך ביאור מה אומר בזה.
* צז.
** רבה בריה -
גורסים בצד רבא. לכאורה, הוא מפני שכן כתוב בב"מ, ועוד שמצאנו שהיה לו בן שהיה שמו רבא, והוא רבא סתם. יש לדון, שאולי אף היה לו בין ששמו רבה. חושב אני ששמעתי שרבא ורבה הם אותו שם, אלא כינויים אחרים. אם כן, לא מסתבר שהיו לו זה וזה. ויש לדון, שאולי הוא כמו בני ר"ח (ויש להעיר שאולי שם חד מת קודם לידת זה. כאן, יותר קל לומר לרש"י שאחד מת[fn:4], כיון שהיו בני עלי, ולא חיו לזמן, ורק רבא, שלמד הרבה, חי לארבעים שנה). גם היה אפשר לומר שרבה בן ריב"ח הוא רבא סתם, שהוא אותו שם, כמש"כ, וקראו לו בדרך כלל רבא סתם, אבל אף קראו לו רבה בן של ריב"ח. ותחשב.
הביאור לזה יכול להיות שהיה לו להיקרא רבה, אלא שרצו ששמו יהיה חלוק משל רבה.
* צח:
** דאם כן (רש"י) -
משמע שחיובו מחמת מזיק. זה מעניין, שלכאורה, הוא רק גרמא, שרק הביאו לבית דין, ובית דין עשו את האיסור. גם יש להעיר שלכאורה, רק לא עיכב בית דין מליקח אותו, ולא הביא אותו לבית דין. יש לדון, שאולי מייירי בציור שהביא.
לולי רש"י, היה אפשר לומר שחייב מפני שהוא שומר, ולא שמר כראוי. ותחשב על זה.
* צט:
** טרפיה -
ר"ל, אמר שהוא נבילה. ודע שאף היום אומרים בני אדם לשון טרפות על מה שהוא נבלה.
* קא.
** קוף -
משמע שאין נפק"מ אם אדם נתנו שם. יש לדון ל"ל, שנוקים אותו באדם אחר, ואז יש נפק"מ מי חייב. ויש לדון, שאולי רק לא מצוי.
* קז:
** ואלו הן -
לשון זה מוזר, שהיה לו לומר רק שכל השומרים..., שהרי לכולם נותן דין זה. ותחשב.
* קט:
** רב אהרן -
שם זה לא מצוי בתנאים ואמוראים (אבל מצוי מאד בזמנינו).
** מנין -
לא הבנתי לשון הברייתא, שלכאורה לא מסיק. אולי מש”א ג”ש הוא המסקנא. לא נראה כן, שהיה גמרא מנסה לומר תירוץ אחר קודם לכן. וצריך ביאור.
** טמא -
אם לעיל למד מתרומה, קשה מה מקשה על זה, שיכול, לכאורה, לקבל תרומה בטומאה (ורק לא לאכול).
* קי:
** מתנה -
יש להעיר שאף אומרים כן על דבר שזוכה בו משולחן גבוה. זה חשוב באמירה לנו מה הוא דיון של גמרא כאן, ומהו הצד שהוא מתנה. ותו"ת.
** בלא חליצה -
יש לדון, שאף שיצא רע זה, גם היה טוב בנשואים שלה לבעלה (ולא נראה שזהו תירוץ של הגמרא). צריך לומר שפשוט לגמרא שאין זה די לעשות שתרצה. ותחשב.
* קיא:
** אלא אמר רבא -
עיין בביאור רש"י. לזה, רבא רק מפרש ל"ל שונה כרבי. אם כן, לשון "אלא" לא נראה, שלא משנה הפשט. באמת, רש"י נ’ שלא גורס אלא.
** והא מתני -
כמובן, צריך ביאור איך ייצא לנו שאין המשנה כמו שפרש רבי, כיון שכתב רבי את המשנה. אולי רק לקחו מתנאים אחרים. גי"ל שלומד מר"א שלא אמר כן רבי. מרש"י לא נראה כצד שני.
* קיג:
** יחזיר -
עדיין יש לדון מהיכי תיתי שיכול להשמתש עמו, שאולי רק אין מצווה להחזיר אותו, אבל אסור לקנות אותו, שהוא גזל. ויש לומר שכיון שיודע כן, מסתמא מיאש. גם יש לומר שמפני זה, אינו גזל, שמסתמא לא יבוא לידו עוד, ולא חסר כלום בזה. גי"ל שכל אבידה היה יכול לקנות (כיון שאינו ברשות בעל) לולי מצוות השבה, אלא שמצוות השבה עושה שהוא עדיין מיוחס לזה (או שעומד לחזור לו או מפני שהוא גורם מצווה עליו). ותחשב.
** תרי גווני גזלן -
נמצא שסובר רבה שלסטים מזוין גזלן, והוא כשיטתו נגד רב יוסף גבי שומר אבידה. ותחשב.
** לכאורה, מה
שלא יהני יאוש בגנב או שלא יהני בגזלן הוא שאינו כל כך רחוק מרשותו, שקל לו להחזירו לו בדין.
* קיד:
** הא לאו כבוד -
קשה ל"ל דוחים שמריירי בדייאש בפירוש. יש לומר שסתמותו לא משמע כן. גם יש לומר שרק מביא ראיה לפי רבה, ולא עולא. זה מעניין.
** קנין דרבנן -
יש לדון למה. אולי הוא מפני שאינו שולט עליהם כל כך. יש לדון אם זה יבטל קנין. גם יש לומר שבדרך כלל, לא עשה מעשה קנין רגיל עליהם.
** שאני… קנין דרבנן הוא -
ועוד שבעלים מרדפים.
** בשבויה הקילו -
היה אפשר לומר שזה בכלל עדות אשה.
* קטו.
** לבישותא -
לכן נקרא "חנן בישא.”
** כשעקל -
לא הבנתי, שהוקים משנה ראשונה בשעקל…, ושם אף לא חל. אולי זה אף אפשר להציל. ותחשב.
* קטז.
** כי אפקרה אדעתא דאריא -
לכאורה, אי אפשר להפקיר רק שאחד יזכה בו (שזה כהפקר לעניים; אבל דע שאולי זה חל אבל לא פוטר ממעשר), אלא ר"ל שהפקיר על תנאי שארי יאכל אותו, והרי כהפקר בטעות. ותחשב.
* קטז:
** גלי דעתיה -
רש"י מפרש שגלי דעתיה גורם גילוי דעת של בעל, ששותק. גם יש להעיר שלכאורה צריך גילוי דעת שלו לסיבה אחרת, והוא שכיון שאפשר לאחר להציל, אולי זה סובר שאי אפשר לו לקנות, ולא מכוון לקנות כלל. אז, צריך הוכחה שהוא מכוון.
** אחוי ההוא -
לכאורה, שני התירוצים שווים הם, והוא שהראה את זה לעכו"ם, וקצת צריך ביאור מה לנו אם שאל לו על שדותיו. ותחשב.
* קיז.
** היכא דלא אוקמיה -
משמע שנחשב כבר נאבד, שכבר עומד להיות הוזק.לכאורה, כאן אינו כל כך עומד כמו בציור של עיל (של זורק דבר ואחר מזיקו). ותחשב.
* קיז:
** מחמת הגזלן -
אין לומר שגזלן חלוק (באמת, אין סיבה לחלק, שלא חייב במכת מדינה), כיון שאין גזלן על קרקע.
** שלא יהא ממונו -
מצאנו לשון כזה גם בדרשה של קריאת שמע (“בכל מאדך").
** שטפה נהר -
עיין ברש"י. לא הבנתי כל כך מה מכוון לומר. משמע שאין הנהר גודל עד ששוטף, אלא נכנס תחת קרקע השדה. צריך ביאור, אז, למה דן במגביה שפתו. וצריך ביאור.
* קיח.
** פרה רבוצה -
עיין במה שפרש"י. מעניין שיש קנין אגב כאן. לכאורה, אין קנין על הקרקע. אז, צריך לומר או שקנין אגב נעשה אגב סיבת הקנין, ולא אגב הקנין עצמו. גם יש לומר שיחס של גניבה גם כן יכול לעשות אגב. ותחשב.
** הגוזל את חברו -
משמע שאין שוויותו שווה כשהוא במדבר. ותחשב. יש לציין לגמרא לעיל (צח) גבי זורק מטבע לים, שאל אומרים שפחת מכספו, לכאורה.
** אי בעינא -
לא הבנתי כל כך ההוה אמינא, שהרי אמר בפירוש. ותחשב.
** בבא לצאת -
מזה משמע שכשיש לאדם ספק גזל, יש לתת לקיים ידי שמים. זה מעניין.
* קיח:
** במה שתולה
גמרא במה שיכיר בעל הבית, נראה להעיר שאולי זהו הסיבה שנסמך זה למשיב מדעת. ותו"ת.
* קיט.
** כשהם יושבים -
צריך ביאור למה זה מתיר אותו. אולי כיון שהוא כל כך בפרהסיא, לא היה גוזל. גם יש לומר שזה מוכיח שיש לו הרבה למכור, ולא היה יכול לגזול כל כך. כיון שיודעים שקנה קצת משלו, מניחים שכולו משלו. גם יש לומר שטרח כל כך למכור, ולא יעשה כן לגזל. ותחשב.
** בעלים דהשתא -
מעניין שנחשב גזלן בעליו. אולי ר"ל לאחר יאוש.
** דבר מועט -
עיין תענית כא.
** שהרג נוב -
קיל"ד איך יודעים שזה לא היה עונש למה שהרג נוב עיר הכהנים. ממעשה שגרם שיהרגו בניו (עיין ביבמות) משמע שהיה מפני שגזל מגבעונים.
* קיט:
** באלימי -
עיין ברש"י. גם היה אפשר לומר שיטול את הכל, ועושים יותר מן הגדול, שכיון שהוא יותר אלים, צריך יותר כדי להדקו. ותחשב.
* Footnotes
[fn:1] רב שלום שפיץ.
[fn:2] יש להעיר שמצאנו בע"ז שהיה ר"א בימי רבי יהודה בן בנו של רבי. אם כן, לכאורה, צריך לומר שאף הוא חי לזמן מאוחר. אם כן, צריך ביאור איך רש"י יודע שזה היה בסוף שנותיו, ולא בתחילה. ותו"ת. על כל פנים, הוכחנו שאפשר לרש"י לומר כן. ותו"ת.
[fn:3] במילים אחרים, כיון שזה טוב, נראה שאולי רש"י אומר כאן שבפלוגתא ר"ל שמה שהוזכר שני הוא בפלוגתא של מה שהוזכר ראשון. גם היה אפשר לומר שר"ל שמה שחלקו בו אמוראים אחרונים הוא בפלוגתא של אמוראים ראשונים. גם אפשר לומר צד שאומרים שראשונים חלקו במחלקת של אחרונים, אלא שאין זה כל כך מסתבר. באמת, יש עוד צדדים, שאולי אומרים שאמוראים שאינם כל כך ידועים, אולי בדרך כלל או אולי במחלקת זה, חולקים במחלקת של הידועים.נראה עוד צד, והוא שאומרים שמי שאינו כל כך ידוע (או שהאמורא אינו כל כך ידוע, אוא שאותו מחלקת אינו כל כך ידוע) במי שהוא יותר ידוע. ותחשב.עיין בשי”ח ש”י על גיטין (גלגל רביעי), ששהם הערנו הערה חשובה.
[fn:4] ויש לדון, שאולי זה גם אומר שרב יוסף בר חמא לא חי לזמן רב, כדי להיות לו שני בנים שיהיו חלוקים בגילם כל כך. ויש לדון, שאולי היה מבית עלי רק מאמו. קצת תלוי, לכאורה, באם היה רבא כוהן. עיין בראש השנה וחולין, שדן רש"י בזה. ותו"ת.
