א.
** חמשה
- רבי יהודה- לכאו’, השש הוא ארבע שהכל מודים בו, וקטן שלא הגיע לעונת נדרים, וקטן שהגיע לעונת נדרים. יש לדון למה כל כך פשוט הוא לפני משה שרבי יהודה חלק אותם לשנים. לכאו’, הוא מפני שצריך דבר למעט. ויש לדון למה יכולים למעט מזה ולהניח שהם שנים.
צריך ביאור, עדיין, ל"ל אומר שממעט רבי יהודה מן המשנה עצמו, שאומר שתרומתו אינו תרומה. ותחשב.
** החרש
- מה שאומר שנלמד ממה שצריך דעת, ולא מ”איש” קצת קשה, שיש מקומות שממעטים כל מי שאינו בר דעת, והוא מ”איש,” כמו גבי שליחות. אינו קשה למה כתוב קרא זה, שיש נפקא מינא, כמו שאומר גמרא לקמן, אבל קשה למה אומר גמרא כן. ותחשב.
** קשייתה
- צריך ביאור למה לא נחשב כתוב בו מחשבה, כיון שכ’ בו, “וכתב לה.” ודע שפני משה קצת מבולבל כאן בביאורו- אם צריך מחשבה או שליחות. ותחשב.
ב:
** דלא כר"י -
צריך ביאור ל"ל רק הביא משנה שאומר כן בפירוש.
** מכאן ולהבא -
לכאו’, הצד שיחול מכאן ולהבא הוא שרק חל על ידי אב, ולא על ידי בן, וההפרשה של אב הוא מה שהסכים לבנו. אם כן, לכאו’, אין עוד ראיה לשיטת רבי יהודה.
יפות- עיין בבבלי בפרק שני בב"מ. לכאו’, מוכרח נגד זה, שאם נאמר כמה שמפרש גמרא’ שם, אי אפשר להביא ראיה. נ’ שגמרא כאן סובר כאביי, ובזה מתרץ קושיית רבא.
ו:
** מהו שיקרא -
לכאו’, גמ’ לא משיב לזה, אלא מזכיר שאלה אחר בנוגע קריאת שמע שהיה שאול לאליהו זכור לטוב. ודע שאפשר לקרוא גמ’ שאומר ששאל את זה לאלהיו הנביא, והשיב לו הנביא שאם אדם קורא הוא זכור לטוב. (אולי זה אומר שאין חיוב עליו ממש, והוא פטור, אלא שהוא עדיין טוב, או אולי השיב שלהיפך הוא יותר טוב לקרוא שתוי משאינו שתוי, שאז בענין אחד קצת צליל דעתו יותר.)
גם אפשר שגמ’ עכשיו משנה לומר שלא כך שאל ר"ז לר"א, אלא כך שאל. (כן קצת נראה, שאי לאו הכי, לא השיב כל כך לקושיית גמ’, שהיה ששאלתו היה פשוט. ותו"ת.)
אבל, אז, צריך ביאור מהו תשובתו. אולי הניח שכמו שאפשר לברך כשהוא שתוי גם יכול לקרוא קריאת שמע כשהוא שתךוי. ודע שיש חילוק פשוט, והוא שק"ש צריך כוונה, אבל ברכת המזון לא צריך כוונה. ותחשב.
** ואפי’ מדוממדם
- עיין במה שבאר בתשובת הגמרא. נראה שיש על זה שלש הערות:
1. מניח ששבעיה זה ר"ל שתייה. זה מחלקת תנאים בפרק שביעי של ברכות, ובפסחים (זהו המח’ בין ר"י ור"מ בשיעור ברכת המזון).
2. לא פשוט שזהו דין דאו’, שהרי דיון שם הוא בשיעור ברכת המזון, אם הוא כזית או כביצה, וזה, בוודאי, והא שיעור דרבנן.
אולי אין זה כל כך קשה, שאין הכי ננמי, דרשה דרבנן הוא, ולא מביאים מקור מכאן, אלא מביאים ראיה ממה שיכולים רבנן לומר שרק מברך כשהוא שתוי.
1. זה מניח ששתייה של אותו קרא ר"ל שתיית יין, ולא שתיית מים. אולי מסתבר כן כיון שאין שתיית מים, אולי, מצוי. ותו"ת.
** מה תרומה -
שאל לי א.י.כ. בגיטין איך לומדים דין אומד מתרומה לת"מ, שאין דין אומד גבי תרומה, שאין מאמדים שום דבר. נראה שאין לומדים מה שיכול לאמד, אלא לומדים מה שצריך להיות במחשבה, ולא במנין, ואז ממילא יוצא שצריך לאמדו.
לכאו', חשבון זה נכון, אבל צריך ביאור, אז, למה מזכיר שני הדינים בשני מילים . ותחשב.
ז.
** הנכתשים -
לכאו', כיון שהם כבר נכתשים, אין כל כך גזל השבט, שעומד שמן לבוא מהם. המציאות לא כל כך פשוט לי מהו הציור שדך וכתש אותם, ועומד השמן לצאת ולא כבר יצא. ותו"ת.
** תמן -
לכאו', פשוט שסובר שזה במשנה אחר. אם כן, חילוק משניות שלו אינו כשלו, אלא הוא כמו שנמצא בפני משה של דפ"ו, ולא של עוז והדר.
** מפני גדר חטאת -
נראה שרצה לומר שרוצים שיהיה טהור כשעושה השאר, וחוששים שיהיה טמא טיעשה אותו בטומאה, ויגע בו לטמא אותו. אז, גוזרים שצריך להפריש עוד תרומה. אז, יהיה טהור כשנוגע בו. אם כן, אף בנכתשים על נכתשים יהיה אותו גזירה.
ודע שזה צריך להניח שלא חוששים בשמן על שמן, אף ששם אפשר שיעסוק בו עוד בטומאה. כמו כן, יש לדון ל"ל גזרו על זיתים סתם. ויש לומר שהיה לנו לגזור, אבל לא יהני, כיון שבין כך ובין כך יפריש אותו קודם שהוכשר. ותחשב.
ויותר נראה (וזה לא יתרץ כל הקושיות) שרק גזרו שאין תרומתו תרומה כשלא היה לו לעשות כן מתחילה, שהוא מדבר שנגמר על דבר שלא נגמר. כן נראה מפני משה על המשנה, שאי לאו הכי, למה יזכיר אותו. ויש לדון, שאולי מזכיר ההו"א של גמ'.
ז
** יש כמה
דברים בסוגיה זה לא הבנתי כל כך. לא הבנתי כל כך ראיית גמ’ שגדר מי חטאת חמור יותר, ולא הבנתי כל כך דיחוי גמ’ לשיטת רבי יוסי.
ט:
** מהו שיתרום -
קצת צריך ביאור שחוששים שעושה מה שלא מהני. ראשון, לכאו’, חושב שיחול שאיזה אופן שמהני. ויש לדון אם זה נחשב ברירה. שני, אולי יודע את ההלכה. ותחשב.
** הכסיל -
יש לדון מהו המשל בזה (למה הביא קרא זה). אולי ר"ל שאין תרומה יכול להיות תרומה על שני דברים (וקצת קשה, שאין זה הנקודה שחידש להם, אלא חידש שחוששים שיעשה כן), כמו שאין אדם יכול להיות כבר חלק מעצמו ואף מזונו. ויש לדון, שלכאו’, מה שהוא הכסיל בזה אינו מפני שלא מהני, שמהני, ונותן לעצמו מזון, ואף מחסר החלק בו שצריך לאכול, אלא הוא מפני שהחסרון יותר גדול מן הרווח. אז, קשה.
אולי רק אומר שאף יש כסיל שאוכל את בשרו, ואז לא קשה לצייר ככסיל שחושב שתרומה נעשה תרומה על שני טבלים. אז, חוששים שלא חל. דחוק.
י.
** שאין בפיו כביצה -
הענין הוא כך:
צריך אדם להפריש מטהור על הטמא, אבל לא יכול לעשות שהטבל נטמא, שאז יהיה תרומתו טמאה. אבל, צריכים להיות מוקפים.
אילו היו יבשים, היה קל, שהיה יכול ליגע אותם, שלא יטמאו זא"ז.[fn:1]
אבל, כיון שהוא לח, זה יטמא את זה, כיון שמשקים מטמאים משקים.[fn:2]
אז, אומר תקנה, והוא שצריך לעשות שבפיו, אין ביצה. אז, אין ביצה נוגע, ואינו נטמא. (אם פחות מכביצה לא נטמא, רק צ’ שאחד פחות מכביצה. אם לא מטמא, אז צ’ שהמטמא הוא פחות מכביצה.)
צריך ביאור עדיין:
1. קשה ל"ל רק מקנח אותו ומיבש אותו. אולי זה יותר קשה.
2. קשה למה מהני מה שאין בפיו כביצה, שיצטרף עם מה שאינו בפיו, שלכאו’, נוגע בו. והמציאות צ"ב.
י:
** בטומאת טב"י -
עיין במה שפ’. יש להעיר שאילו נעשה תרומה, היה טמא, ולא היה שלום. אז, הוא גלגל החוזר. אולי לא מניחים שיעשה גלגל החוזר.
** טבולי
- אם יעריב- לכאו’, רצה לומר "כשיעריב…" ויש לדון, שאולי ר"ל שאם יעריב שמשו קודם שיתנו כל התרומות.
יד:
** אם -
מחודש לי שנחשב הכוהן המוציא, שהרי מוציאים ממון ממנו. שו"ר גמ’ לקמן. עדיין צריך ביאור, שהרי גמ’ לקמן לומד ממה שמקילים לענין דימוע. גבי דימוע, ספק דרבנן הוא (שמדאו’, הכל בטלים ברוב). אז, צריך ביאור מהו הדמיון.
טו.
** ראב"ש -
נ’ שגדול ר"ל בשנים, אבל לא בחכמה, כמו שאומ’ בבלי גיטין (נט.). אולי חולק ירושלמי על זה.
** אם תרם -
יש לדון למה אין הפרש טעות, שלא היה מפריש אילו ידע שהיה חברו מפריש. יש להעיר שזה ציור מעניין, שכל אחד הו א כן, וכיון ששל כל אחד חל, של חברו היה חל. ותחשב. ויש לדון, שה"אילו הוה ידע" הוא קצת חלוק, שבזה הוא ידיעתו על מה קרה ובזה הוא ידיעתו או על מה יקרה. גם יש להעיר שאולי כיון שחד קרה ראשון, וזה היה של טעות, ממילא מה שיבוא יחול. ראשון לא היה עושה אם ידע שחברו יעשה המעשה שהיה חל בלתי דין טעות. ויש לדון אם עדיין לא היה עושה. ותחשב.
טז.
** היה הבור קטן -
מניח שכל זה הוא כשעושים פועלים שתי וערב, שכן עושים פועלים. אז, משמע שרק אם יש חשש גדולה של טומאה, יכולים לתרום לפני כן. וצריך ביאור מהו ענין בור קטן, ולמה יותר עליל ליטמא.
** תיפתר
- לכאו’, ר"ל שכיון ששינה, וגילה שלא רוצה כיון ששינה, הרי שליחותו בטל. ותחשב.
טז:
** כאן וכאן -
לכאו’, אין כל כך חילוק בין אלו, שעיקר התירוץ הוא שווה. החילוק הוא אולי מה נקרא מצוי או כמה מצוי הוא.
יז.
** רשב"ג -
עיין במה שכ’. צריך ביאור, שהרי לעיל אמר שמחלק ונותן צד צפוני. אז, צריך לומר שהחילוק הולך ממזרח למערב. כמו כן כאן אומר שנותן צד צפוני. אז, ג"כ צ"ל החילוק ממזרח למערב. אבל, קשה, שאומר על אחד שהוא לארכו ועל אחד שהוא לרחבו. צריך ביאור איך זה שייך. ותחשב.
מן מה- לכאו’, זה צריך להיות כשיטת אביי ב"כל מה דאמר רחמנא לא תעביד, אם עביד מהני.” אפשר שסובר כרבא, ורק אומר שלא ילקה, שכיון שאין מעשה ואין חלות, הוא כלאו שאין בו מעשה, ולא ילקה. (וצל"ע שם בתמורה.)
** יז: שהק’ בשבלין -
צ"ב ל"ל יעבור, שהופרש תרומה לאחר זמן. אולי ר"ל שלא מאוחר תרומה, שניתן מיד בשעת חיובו. לא נ’ כן מפני משה.
** מאן דמר -
צ"ב איך רואים מכאן אותו דמיון. ותו"ת.
** יח. רבי אבוהו -
לכאו’, זה רבי אבהו. אם כן, נמצא ששמו הוא רבי אבוהו. אם כן, מצאנו שרב אמי הוא רב אימי, ורבי אבהו הוא רבי אבוהו.
** יח: טבל -
צ"ב למה מניחים כן. אולי ר"ל שאם מפריש מעצמו, הוא הפרשה אחת ארוכה, וממילא לא נתקן כלל.
** כא. השליח -
הענין הוא אם נתנם ביחד או לא. ויש לדון, ששליח לא נתן שום דבר, אלא אמר. ותחשב.
** כא: כן ר"א -
יש לדון אם רואה כן ממשנה (קצת יש לדון בזה, שלא אומר כן בפירוש במשנה) או רק אומר שכן הוא, ואומר שסובר כבית שמאי.
** כב. רבי יוסי -
כולו מן החולין- לכאו’, זה קצת פשוט; צריך ביאור מהו הצד שלא לומר כן.
** מנין -
מבואר שזה רק אסמכתא, והדין דרבנן.
** כב: לא מסתברא -
עיין בפני משה. ויש לדון למה חוששים לאיבוד אחד; משמע שאז חוזר וניעור. אולי לא בטל כל כך עד שלא יחזור כיון שיש יכולת זה.
** כג. כולן נעשה -
עיין בסו"ד. צריך ביאור; היה נראה לומר שאין סיבה להוכיח שמה שנפל הוא של תרומה. אם כן, צריך ביאור למה אומר שהוא עד שלא נשאר רוב, שהרי אף ר"ל מודה לזה, כפי מה שבאר. וצריך ביאור.
** רא"א פורחות -
נמצא שסובר שלא צריך להיות בכלל הספק כדי שיצטרפו לבטל. אם כן, מח’ של לבנות ושחרות הוא רק אם הם דומים די לצרף. ותחשב על זה.
** כז: בטל מגעה -
עיין במה שבאר. ודע שיש בזה חידוש, שהיה אפשר לומר שביטול עושה שאין חפץ של איסור או טומאה נחשב שם[fn:3] או נחשב של איסור ושל טומאה. אבל, מגמ’ זה לא נראה כן.
ויש לדון, שהיה אפשר לומר שאין הענין שדיני ביטול רק עושים ספק שיכולים לסמוך עליו, ואין ספק גבי משא, אלא אולי הנעין הוא שאחד מן הדברים שגורמים ביטול הוא מה שיש ספק, אבל לענין טומאת משא, אין ספק, ולכן אין ביטל. אבל, אילו היה ספק, היה בטל, ולא היינו רק סומכים שאין רע, אלא היה נעשה שאין רע. ותחשב ותבין.
** כח. לא מצינו -
עיין במה שפירש. אז, פירש שאמרו להם המימרא הזה בלי תמיהה. אם כן, לא היו צריכים לומר יותר מ“ב“ש הודו לב“ה.“ נראה שאמרו כן מפני שכן שמעו את המאמר (ולא על שאלה זה שמעו). גם יש לומר שאמרו כן להוסיף עוד מאמר..
אבל, לולי פני משה, היה אפשר לומר בקל שאומר כן בתמיהה, והוא שאומר שלא מצינו דבר אחר שמודה בית שמאי לבית הלל, ורק מצאנו שבית הלל יודו לבית שמאי, וזה יאמר לנו שאף כאן כן הוא, שבית הלל הודו לבית שמאי.[fn:4]
לזה, גמ’ מביא ראיות נגד זה אחר כך, ולא מביא ראיות לו. ותו"ת.
** שמע לה… קלוח -
במשנה זה, צריך לפרש מהו ה“קילוח“ שנטמא, שאין אם אין קילוח חיבור, נאמר שרק מה שנגע ממש נטמא, והרי מה שנגע בהכרח הוא מעט מעט. ויש לדון, שאולי כל הקילוח נחשב מחובר, ורק לא מחובר למה שבכלים. וצריך לבאר קצת למה נחשב חיבור לקילוח יותר מלמה שהוא בכלים. אולי הוא מפני הדמיון, שלא רק עומד ללכת אל אותו מקום שזה עומד ללכת, אלא הוא הולך, כמותו. ותחשב.
** אינה מדמעת -
מניח שמשנה ר"ל כמו שפי’ פני משה על המשנה, והוא שצריך שחולין יהיה כנגד אותו חלק של תרומה, אבל לא מצטרף עם החולין שנפל. ויש לדון מהיכי תיתי לפרש את המשנה כן.
אבל, דע שאף מה שאומר ר“י לא משמע שמצטרף עם החולין, שאז לא צריך חולין שני. ויש לדון, שאולי אין חולין ראשונים מבטלים את התרומה עד שהוא מצטרף עם דבר אחר, ונעשה תערובת אחרת. ויש לדון למה יהיה כן. ותו"ת.
** כח: ברם -
עיין במנינים שאומר לביטול. משמע שסובר שכדי לבטל ברוב, צריך שהוא כפול. ותחשב.
** לא: תפלוגתא -
היה אפשר לחלק לומר ששם אכל באיסור, ואז צריך להוציא מתחת ידו, אבל כאן אכל אחר מחילה.
** מהו כדון -
עיין בביאור פ"מ את הדרשה. ודע שהיה אפשר ללמוד מכאן שנתינת הקודש מהני לכל חומש, ושקרא מדבר בכל ציור, אבל גמ’ לא חושב שזה כל כך פשוט, ואז דורש שהוא מדבר רק בציור שיש רק חיוב מחמת תרומה. ותחשב.
** לב: תמן -
לא הבנתי כל כך למה אינו מסויים. גם לא הבנתי דין הוספת חומש על חומש, שלכאו’, אין זה נוגע לחוב ראשון, שהוא חיוב חדש על שכפר בחומש, ואז לא יעשה שאינו מסויים. ותחשב.
** לג. עיקר סעודה -
שקלא וטריא זה הוא קצת קשה להבין. לפני משה, נראה שמקשה מה בינייהו, ואיזה נפק"מ יש, ומתרץ בחילוק לומדי זה, ולא נותן נפק"מ. אולי משיב שאין הכי נמי, אין נפק"מ, אבל יש חילוק לומדי, וזה די. גם יש לומר שזה יש לו נפק"מ בדינים אחרים, אף שאין לו נפק"מ זה. ותחשב.
** לד. אית חל מימר -
לא הבנתי קושיה זה, שמצאנו ציור לכל אלו שבמשנה לומר שאין חייבים בתרומה. אז, צריך ביאור מה מקשה כאן. ותחשב.
** חילפא
- קשה, שאף אם נעשה לקט אחר שנופל, לא הוקבע לתרו“מ, שאל ראה פני הבית, ולא אידגן. אז, עדיין הוא חלוק ממעשר שני וכדומה.
** אכל חלה -
ר“ע- משמע שלר“א פשוט הוא שיכול. קשה למה, שלכאו’, גרוע הוא. אולי ר“א סובר שצריך להיות יפה, ואז בוודאי לא יהני, אבל ר“ע סובר שרק צריך להיות מאותו המין. אם כן, מצאנו נחומרא לר“א. לא נראה כן, אלא נראה שאומר שאף שואלים את זה לר“ע.
** אין משלמים מפירות חו“ל -
לא מפ’ גמ’ למה, אבל מסתמא הוא מפני שאין תרומה יכול לחול עליהם, שלא היו חייבים בתרומה לעולם (על כל פנים, מדאורייתא), אף שהם ממין של תרומה.
* Footnotes
[fn:1] איני יודע למה זה כל כך פשוט, שחושב אני שאוכל מטמא אוכל מדרבנן. אולי אין זה נכון.
[fn:2] כן נראה לי, אבל איני יודע אם זה נכון, שאין זה ממש משקין, אלא הוא רק דבר לח. אולי הוא מפני שיאלו היה יבש, היה פשוט שלא יצרף, ואז לא יצטרך לחוש לגודל פיו. גי"ל שיבש ר"ל שלא הוכשר.
[fn:3] נראה שלא אפשר לומר שלא נחשב שם כבר מגמ’ לעיל, שאומר שיכול להיות שלענין אחד בטל, ולענין אחר אינו בטל.
[fn:4] לשון תמיהה שכתבתי אינו כל כך דווקא. ותו"ת.
