** פרק מבוי שהוא גבוה
* ב.
** אף על פי -
מעניין מה שרק מזכיר רחבו ולא גובהו בזה. ואולי זה רק נוהג ברחבו. ויש לדון למה. ויש להעיר שאולי לחד צד בביאור שיטות אלו, אין גדר גבהותו ורחבותו מפני אותו סיבה. אולי, אז, פשוט לחלק.
** אשכחן -
ואם תאמר עדיין מהיכי תיתי שזה נאמר אף משקדש (שלא כל שנאמר במשכן אינו אמת במקדש). ותחשב..
* ב:
** פתח סתמא -
יש לדון למה אין אומרים כן גבי פתח אהל מועד. אפשר שעיקר תירוץ גמרא אינו שהוא נקרא פתח שער החצר, אלא שנקרא פתח שער, וסתם פתח של שער חלוק מפתח סתם. ותחשב.
** אי בעית אימא -
יש לדון במה חוזר מתירוץ ראשון:
א. אפשר שסבר שאין פתח שער חלוק מפתח.
ב. אפשר שסבר שהדרך לקרוא את הקרא הוא "פתח [של] שער החצר,” ולא "פתח שער [של] חצר.” ועל"ע.
** משפת מזבח -
צריך ביאור למה ימנה משם. אפשר שהוא מפני שיש צורך בכיסוי עליו (עיין בזבחים (נט:)), ואז גובהה שעליו חשוב. ותחשב.
** דמלכים -
נמצא שרבנן לומדים משם של תורה ורבי יהודה לומד משם בני אדם. אפשר שיסוד מחלקתם הוא איזה שם יותר חשוב. (ויש להעיר- ויש לדון אם שייך- שר"י דורש לשון הדיוט (בב"מ קד.). ותו"ת.
** לצניעות -
יש לדון עדיין כיון שהיו לו דלתות איך יודעים שנקרא פתח בלי דלתות. ואולי גמרא רוצה לומר שדלתות הם סיבה שיהא דבר נחשב סתום או כדומה, אכל לא שיחשב "פתח.” ותחשב.
** ולילפו מפתח שער -
יש לדון מה רוצה ללמוד:
א. לעולם יכול להיות רהב עשרים (ואף אם גובהו יותר מגובה שער החצר, שלא שייך גובה לרוחב).
ב. אם גובהו כגובה פתח שער החצר, יהא יכול להיות רחב כמותו. משנה שאומר דינו סתם משמע שהוא בכל מצב, ואף אם אינו גבוה אלא כשער. ותו"ת.
* ג.
** הניחא -
יש להעיר שהיה אפשר לומר שיש הוה אמינא שההיכר שצריך חלוק בין שניהם. ותו"ת.
** כיון דלישיבה -
יש להעיר שאז נמצא למסקנה לרבנן שני שיעורים, שבסוכה השיעור הוא יותר חמור, שצריך להיות דבר שנראה יותר, שאף שיושב והוא רחוק ממנו עשרים לא מהני. אפשר שאין הכי נמי, שיעורם חלוק. (אז, מה שהקשינו בד"ה הניחא יותר קשה.) גם יש לומר שסוברים רבנן שאין מניחים שמי שיושב רואה יותר או שצריך להיות היכר לכל ובכל ציוא רגיל, ואף למי שלא יושב. ותחשב.
** והא סוכה -
מעניין שאין דוחים שבין כך ובין כך שיעורם חלוק. משמע ששווה הוא. (עיין בד"ה כיון דלישיבה לעיל.)
** לקבל אריח -
היה אפשר לדחות שקאי ברחב ארבע.
** סימנא -
קצת קשה למה לא נקט סוכה לסימן כיון שאין בא בעיא דאמלתרא. אפשר שלא היה כל כך ידוע כגובה היכל. גם יש לומר שנקט היכל כיון שאף דומה לו ברוחב.
* ג:
** אמת סוכה -
מביאו כאן או מפני שאף הוא דן ב(דמיון ב)סוכה ומבוי או מפני שאף הוא דן באיך ישער (כמו "חלל מבוי תנן").
** מבוי -
צריך ביאור למה מחמיר בו, שדרבנן הוא.
* ד.
** דאורייתא -
משמע שלא קורא להלכה למשה מסיני דאורייתא. ע’ במק"א שדנינו בזה.
* ד:
** ארץ -
מעניין שכל ארץ כן. ויש מושג שתורה יותר נוהגת (מסתמא, הוא שיש יותר סיבות) בא"י. אולי כן ר"ל. ותו"ת.
** אסמכינהו -
יש להעיר שלכאורה אי אפשר לפרש את זה כאסמכתה כל ריטב"א (עיין ר"ה טו?), ומוכרח כרמב"ם. ואולי כאן יודה ריטב"א, שהרי מדאורייתא הוא. ותחשב.
** לרובו -
צריך לחשוב למה לולי הלכה הוה אמינא שאינו חוצץ. ויש לדון אם הלכה מלמד החומרא, הקולא (ואיזו) או שניהם (שכיון שמלמד אחד, מסברה היינו אומרים שאף לחברו יש אותו דין, ומלמד הלכה שאינו כן.). ולשון גמרא אולי משמע שמלמד את כלם.
** לבוד -
יש להעיר שזה שייך לכמה דברים חוץ ממחיצות, ומעניין שקראו באותו שם. ותו"ת.
** אי נמי משום -
יש לדון מהו ההוה אמינא לומר שנגזור גזירה לגזירה. בדרך כלל, נאמר שהוהו אמינא ש"כולו חד גזירה,” אבל הכא לשון גמרא לא משמע כן. ויל"ד. ותחשב.
* ה.
** פתח -
קצת קשה למה לא נוכל לומר שיש פתח שבא לתוך משך שהוא פחות משיעור גובהה מבויץ ןאולי זה לא מהני. ותחשב.
** מתיר בפירצה -
לא הבנתי כל כך, שאף אי יש פס ד’, יהיו מבני הד’ שישתמשו בפתח שאיין בו לחי (שיותר קרובים לו). וצריך לחשוב על כל זה
** לחי הבולט -
יש לדון מה היה ההוה אמינא להביא ראיה מכאן. ותחשב.
** קל וחומר -
חושב אני- ושוב מצאתי מקור לקמן (טו:)- שדין עמוד מרובה הוא הלכה למשה מסיני. אם כן, יש לדון אם נלמד מקל וחומר. ותחשב.
* ח.
** בדר"י -
יש לדון מה אומר. אפשר שרק אומר שיש שני ציורים, והם שני ציורי רב יוסף. לא משמע כן מן הלשון. אפשר שחולקים באחד מדינים שאמר. יש לדון באיזה חולקים. ותחשב. גם יש לדון מה מוסיף בהבאת ר"י, שלכאורה לא מבאר את המחלקת, אלא רק מבאר מהו הציור. נראה שהיה פשוט לגמרא שיכול להיות מחלקת באותו ציור, ורק מפרש שהוא אותו ציור. ותו"ת. (יש להעיר שאם נניח כן, אלי זה יבאר למה הביא ר"י ולא הגדרה אחרת של הציור, כמו רבה, והוא ששם לא סבר שצריך להגדירו כדי להבין את המחלקת. ותו"ת.)
* ח:
** דכהני -
יש לדון אי ר"ל שהיו בה בני אדם בשם כהנא או שהיו כמה כוהנים. (יש להעיר שלא היה רבא כהן (תוס’ ר”ה יח. ובכ”מ), ואין זה, אז, אינו מעדיף אותו צד.
** כהני -
זה לשון רבים. משמע שסבר שהיו שני בהני, וצ"ל, אז, כלשון ראשון. ותחשב.
** אלא אמר רבא -
לא הבנתי איך זה מהני, שאכתי יש יותר מחד פתח, והוא עוקם. ותחשב.
* ט.
** בר רבא -
יש לדון אם זה בן של רבא סתם. יהא מוזר שיביא ראיה לשיטתו נגד רבא ממימרת בן רבא (וילד), ובפרט שלא הזכיר אותו בלשון "בנך.” ויש לדון, שאולי שינה גמרא את הלשון, ולעולם אמר "בנך.”
** למה לו לשנותו -
לכאורה ר"ל שלא יסבור שהוא ברייתא מתורצת, שאומר דבר שסובר להיות מוטעה. יש לדון בזה, שאפשר לדעת שברייתא נכונה ולחלוק (שלכאורה היה תנא). ואולי ר"ל שלא היה מלמדו אם סבר שאין הדין כן. ויש לדון. ותו"ת. (כן נראה קצת מלשון "למה ליה למתניה." אם כוונתו היה שחשב שהוא מוטעה, היה לו לומר לו רק שאין לו טעם לשנותו, אלא שלא היה לו לשנותו, שביטול תורה הוא, שאינו ברייתא (ויל"ד). אם רק אין הלכה כן, יש לומר שר,ל שאין נפק"מ לשנותו ולומר שאין כן הלכה.)
(שוב ראיתי שכן משמע מתוד"ה אי לא סבר, שבודאי לא יסבור ר"י שאות שיטה לא מתורצת רק מפני שחולק עליו, שיכול לחולוק וחולק בכ,מ. ויש לדון. ותחשב.)
** ולימא לבוד -
אי לחי משום היכר, יהא מוזר שמהני לבוד כמו כאן. ואולי לא פלוג יהא. ותו"ת
* ט:
** מי לא שמיע -
ק”ק למה כל כך פשוט שראהו (עיין בשבת (סא.)). ואולי שאני הכא שהוא שהוא ברייתא של ר"ח (וכיון שהיה תלמיד רבע והיה חשוב היו ברייתותיו ידועים). (וע’ במה שנכתב בזה בס"ד על רש"י.(ד”ה מי לא שמיע).)
** צריך ביאור למה מניח
גמרא שיש לבוד כיון שאינו פחות משלש טפחים אלא שלש טפחים בדיוק. ותחשב.
* י.
** ועד כמה -
יש להעיר שלרב בריש המסכתא אין ספק בזה. ותו"ת.
** נועץ קנה -
יש לדון למה לא אומרים שכיון שאי אפשר לצמצם, עדיין נשאר פירצה עשר. ויש לדון.
* יא.
** א"ל -
גמרא מניח שזה שיטת רב. יש לדון אם רב הוא האומר כן או שחייא אמר כן ורב שמע ושתק (ומשתיקתו ראיה). ותו"ת.
** נלמד -
יש לחלק שבהא דרב, צורות הפתח הם יותר מעשר, שהוא יותר מרחב פתח. אולי לכן אינם צורות הפתח טובים. ותו"ת.
* יא:
** ריב"נ -
נמצא שהיה קדמון. וע’ בסוף גיטין. וע’ בקדושין (לט).
** אשכחינהו -
בפשטות, אמרו שלא אמר כלום. אם כן, אין מה ללמוד ממעשה זה, וקשה למה הוא בגמרא. ואולי אמר שלא הצריך כלום בצורת הפתח. ותו"ת.
* יב.
** אמר"נ -
עיין בראיית רע"א. ויותר קשה כיון שמשמע כן גם כן מרש"י ותו"ת.
* יג.
** גמרא -
בדרך כלל, אין זה "גמרא.” (עיין בקידושין (ל.).
** בשלמא שימוש -
יש לדון אם זה עומד למסקנא.
** מאי בינייהו -
לכאורה, הענין הוא אי יכול להשתמש בו לסוטה, עליו קאי "ומחק.”
* יג:
** ולא ר"מ -
יש לצייין לגמרא יומא (פג:), שר"מ הוא הדורש שמות.
** בן ערך -
יש לציין לגמרא שבת (קמז:). נראה שלכן לא היה לומד לבנו שום אומנות חוץ מתורה (שידע כמה רע הוא שלא ללמוד לזמן).
** ולא היא -
ישלדון אם אומר שאין זה קל וחומר כל כך חדק (והיו דנים בקל וחומרים יותר טובים) או שאומר שלמעשה אינו הדין . . . .
** הלכה כמותינו -
זה כמסקנת גמרא ביבמות שעשו.
** יפשפש -
מוזר, שהיה לו לומר שלא יחטא, ולא שיפשפש כשיחטא. ותו"ת.
** עגולה -
יש להעיר שלכאורה יש רק מעט שהוא רחב כהלכתו. אז, לשני טעמים אי אפשר להעמיד. ותו"ת.
* יד.
** הא תו -
צריך ביאור למסקנא למה אינו שונה רק את זה.
** מנא -
ואם תאמר שמא בדקו חז"ל וידעו. ואולי שואל מהיכי תיתי שנדון בשלש, ולא בπ. ותו"ת.
** והאיכא משהו -
לא הבנתי, שבין כך ובין כך לא דק. ואולי מקשה שנצטרך להניח לכל עגול קצת פחות משלש. ותו"ת.
** רואים -
יש להעיר שזה לכאורה מילה מוזרת למושג זה. ותו"ת.
* יד:
** מחיצה שהגדיים -
יש להעיר שלרבא אינו מחמת מחיצה אלא מחמת היכר.
* טו.
** צריך לחשוב מה לנו
בכוונתו. אפשר שהעניין הוא ששם המקום יותר הוא "בין המחיצות" כיון שמה שנעשה ביניהם גרם לעשיית מחיצות. ותחשב. גם אפשר שרה"י אינו מקום מוקף מחיצות עשר על ארבע על ארבע, אלא מקום שהוא עשר על ארבע על ארבע, ומחיצות מצטרפים עם מה שבתוכם. (נראה שזה יישב מה שמצינו שני מיני רה"י:
א. עמוד של עשר על ארבע על ארבע.
ב. מה שיש לו מחיצות של עשר על ארבע על ארבע.)
אם כן, אולי צריך יחס זה לעשות אותו לאותו חפץ (וכיון שאינם חד חפץ, אין חפץ אחד שהוא עשר על ארבע על ארבע.)
* טז:
** לא דמי פסולא -
לא הבנתי את זה, שפסולם שווה, אלא שיש לאחד יותר צד- שלא מקויים- להיות מותר. ותו"ת.
* טז:
** מחיצה תלויה -
לא הבנתי, שרש"י כתב שזה רק כשתלהו יותר משלש טפחים, וכאן הוא למטה משלש. ותחשב.
* יז.
** שבת גורמת -
במה שיש הרבה דברים תלויים בביאת שבת, יש לדון למה. אפשר שהוא זמן חשוב לענין שבת, שהוא תחילתו, ואז מה שקורה אז חשוב, ונותן שם לכל השבת. גם אפשר שכיון שכבר מעשה אסור או מותר, והיה לו אותו שם, קשה לשנותו. ותחשב.
* יח:
** מתקיף לה -
מקשים מזה על שיטת רש"י בסתם ר"נ. אפשר שמקשה ק’ על מה שאמר עצמו. אפשר שזהו החילוק בין מתקיף לה ומתקיף ליה (אם הקשה להאומר). ויש לדון.
* יט.
** המוציא -
עיין בברכות שחולקים בזה.
* כ.
** דהדרן -
קצת קשה למה לא מחלקים בזה גופא. ותו"ת.
* כא:
** פעמים -
יש להעיר שהיה ניתן פעמים פעמים, שניתן כמה מצוות קודם מתן תורה. ותחשב.
** אין קץ -
קשה, שעדיין יש להקשות למה נבחרו מה שיש בתורה.
** למה לא נכתבו -
יש להעיר שאי אין באיסורי דרבנן אלא ענין לשמוע לרבנן, קשה למה יכתבם. צ"ל, אז, שיש בו יותר ענין. וכן משמע מכמה מקומות בכל גמרא זה. ותו"ת. (ודע שצריך לפרש מה כאן קאי על מדרבנן ומה על תורה שבעל פה).
** בני אם חכם -
יש לציין לגמרא ברכות (ד.). ותו"ת.
* כב:
** לרבנן -
לא הבנתי תלייה זה כל כך, שלכאורה רק חולקים רבנן ורבי יהודה באיזה מחיצות הם חשובים, ומודים בדין הילוך רבים, שהוא שמבטלים כל מחיצות שאינם חשובים. אם כן, לשניהם, יהא רק נדון אחד הוא, והוא אי אלו מחיצות חשובות. ותו"ת.
* כג.
** אילימא -
נמצא- ונמצא כן בכמה מקומות- אילימא שעומד למסקנא. ותו"ת.
* כה.
** רבא -
אי גורסים רבא, צריך לציין למחלוקתו עם אביי בענין פי תקרה.
* כה:
** אורזילא -
צריך לחשוב מה לנו בזה.
* כו.
** איתיביה רבינא -
משמע שרבינא ראה רבא. מעניין, שהיה תלמיד רב אשי, שנולד כשמת רבא. ואולי הוא רבינא אחר (שמעתי שכן כתב תוס’). לא נראה מוכרח, שרק היה תלמיד חבר של רב אשי, ופרש"י שהוא שלמד ממנו דבר אחד, ואז אפשר להיות שהיה גדול ממנו. לא נראה מרש"י שהיה רבא אחר (שלכאורה היו ר"פ ורהבדר"י תלמידי רבא סתם), ותחשב.
* כו:
** פשיטא -
יש לדון, שהיה אפשר שחולקים כשאמרו (וכשאלת גמרא לקמן).
** בית הקברות -
יש לדון למה חלוק מנזיר. ונראה שלא רק אסור לו לאכול, אלא לשבות שם, ואי אפשר ליחשב כאילו שובת שם.
* כז.
** ר’ יוחנן -
ואם תאמר למה לא אמרו על זה, שאז אין צריך לשנות בו "חוץ.” ואולי כך קרה, ששאלו עליו כשלמד זה או כדומה. ותחשב.
** טהור -
שמעתי שיש אומרים שעדיין יש לו טומאת ולד, ורק נתמעט מתורת אב. אם כן, הקנטרס"ט כאן צריך ביאור, שטומאת שניהם שווה. ותחשב.
* כז:
** בהבלעה -
עיין במה שפירש רש"י. אם כן, אינו צריך להיות, לכאורה, חלק מאותו חפץ. ותחשב. ולולי רש"י היה אפשר לומר שענין הבלעה הוא שחד חפץ הוא, וכיון שיש בו שמן, אותו חפץ ראוי למעשר. ותו"ת. ואולי רש"י ר"ל כעין זה ששם החפץ הוא שמן באופן מיוחד (שיש לו יין על גביו), ולכגון זה מוסיף דמים. ותחשב
** עור -
קצת צריך ביאור למה אי אפשר ללמדו מקנקן, שאף, הוא, לכאורה, לשמור. ואולי יש חילוק כיון שלא ניתן שם לשמור (שלא ניתן עורו שם לדעת).
* כח:
** דקטלא -
יש לדון, שאולי יש דבר מהיזמי שמגדליהו. ותו"ת.
** כוותיך מסתבר -
כמובן, צריך ביאור, אז, למה לא אמר כן. (ועיין בדיבור הבא.)
** ולא היא -
יש לדון אי גמרא אומר כן או ששמואל אומר כן (ורק אמר שהיה, בהשקפה ראשונה, מסתבר לומר כר"י). נראה שמה שאומר "ואף על גב" משמע כצד ראשון. ותו"ת.
* כט:
** דלא אישתי -
יש לדון למה לא אומרים, אז, שיכול לערב כיון שיכול לשתות שכר ולבא שם.
** מפני שהשעה -
יש לדון אם זה קאי על מה שהתפללו עליו או על מה שחי. על שני, קשה למה לא יתפללו לו אף בלי זה. על ראשון קשה- ויש לדון- איך ידעו.
** אבל הכא -
לא הבנתי את זה כל כך; לכאומרה רק ר"ל ששותים יותר יין משכר. ותחשב.
* ל.
** אימא מזונא -
יש לדון מה רבותא בזה, רק חמש מינים הם מזונות. ואולי אלו הם מזונות בשיעור רגיל, אבל שיעור גדול ברוב מאכלים יזון.
** רישא -
קצת קשה למה לא אומרים להיפך. ותו"ת.
* ל:
** בטל דעתו -
לשון ביטול דעת מעניין. אם הוא שמניחים שמוטעה הוא או שמשקר, לכאורה לא יהני. צריך לומר שרק ר"ל שלא כל כך חשוב לסקיי"ל כיון שכל כך מוזר הוא.
* לא.
** מצוה -
קשה, שאומר גמרא ציורים שרץ מגוים, ושם בודאי יש הנאה. ותו"ת.
* לב.
** חבר אחר -
לכאורה, שניהם יכולים להיות כן. ותחשב.
* לב:
** עיבורה -
כל דין זה מעניין. וצריך לחשוב.
* לג.
** דהדר -
היה מצי לומר שהוא משופע, כזה:
** פחות משלשה -
נמצא שלבוד לא רק מחבר, אלא עושהו חלק מן הקרקע. ותחשב.
* לג:
** שאמי כלכלה -
לא הבנתי למה אין בזה איתור של הבאתו לתוך רשות הרבים. ותחשב.
* לה:
** אי הכי -
היה אפשר להקשות משיטת ר"מ גופא, שאומר שיש ספק. ושו"ר בתוס’.
* לו.
** כיצד אמר ר"י -
לאו דוקא הוא לחד צד, שלחד צד לא אמרו ר"י אלא אבטולמוס. ותו"ת.
* לז:
** לדידך -
יש לדון למה לא נניח בברייתא כפשטותו. ותו"ת.
** אם ירדו -
רש"י אומר שענין ברירה הוא שחוששים שלא ממש תולהו, שכבר קובע בדעתו מה יקרה. אז, אין בין זה לברירה. אם הבעיא בברירה תלוי במה שמגדרו בקרק’ שלא קרו עדיין, אז מובן. ואולי אם כבר קרו, אין מחשבתו מהני, שכבר יש משמעות אחרת למיליו. ותחשב. (ושוב ראיתי בתוס’. אם כן, בזה ברירה יפסול (וצריך לומר הפוך מה שכתבנו כאן.)
* לח:
** אלא הא דתנן -
צריך ביאור למה אין זה קשה ממה נפשך (שאי אפשר לו לקנותו מבעוד יום, שהוא אסור לו לאכול).
* לט.
** עצה טובה -
לכאורה, פשוט לעשות כן, ורק ר"ל שאומרו על דרך שהוא שכי טוב (שיש בו עצה הכי טובה).
** רבי דוסא -
נמצא שמה שתפלה זה רק נאמר ביום טוב אינו שרק אז ראוי לשאול להחליץ, אלא שיש ענין להחליץ (או יכולת) רק אז. ותו"ת.
** אי אתם-
לא הבנתי את זה כל כך, שעדיין יש אחד מן הימים שהוא חול. אולי ר"ל שאין גזירתו בא ממה שאפשר שהוא יום טוב. צריך לדון, אז, ממה בא, שרבי יוסיף משמע מגמרא, חולק על רבנן, וסיבתם אינו סיבה לדין רבי יוסי. ותחשב.
* לט:
** אם אתמול -
יש להעיר שאם היום קודש, כבר היטל תרומה אתמול, ואין צורך להתנות. מצינו בכמה מקומות (והרשמנו כמה מהם) כמו כן.
* מ.
** מאן דאכל סבר -
שניהם סברו כן, אלא שסבר מי שאכלו שזה שייך כאן. ותו"ת.
** והא -
אף שאכתי מה שאומר הוא נגד שיטת ר"ש, ממה שהשיב לו ר"ש, רואים שהיה רבה אומר כחולקים על ר"ש. גם אפשר שלצד זה, לא הובא על יום אחר. ותו"ת.
* מ:
** כשהוא מעונה -
יש לדון למה:
** א.
אולי הבעיא הוא שאז למקצת שבת (ואולי זה חלק חשוב כיון שהוא תחילתו, ולכמה דברים קובע).
** ב.
אולי אינו כבוד שבת להיות רעב. ותחשב.
** ג.
אולי הוא כמו אבלות בשבת (כיון שהוא תוצאה גדולה של אבלות).
* מא.
** לא זהיה -
ואף שאז אין סיבה להתירו לו, אולי מותר כדי ללמד דין (או שמותר מחמת לא פלוג).
** בדורו -
יש לדון אם ר"ל שר’ יהושע נצח על ריב"נ או שלאיזה סיבה (אולי כבדו ר’ יוסי) התחילו העם לנהוג שלא כר"ג. גם יש לומר שרק הקפיד ר’ יוחנן לאותו דור. ויש לדון.
** ערב -
דיוק זה צריך ביאור, שדלמא קושטא אומר. ותו"ת.
* מא:
** מצוה לגרשה -
משמע שאם אחד גורם רע לעצמו, אין זה מעלה לו לגיהינום. (ואולי שאני הכא שהוא עבירה (ויש לדון אי יש בו עבירה. ולא נראה שיהא בו עבירה). יש לדון מה לנו בזה. אולי, אז, אומרים שגרמו בעצמו, ולא שה’ גרם שיכריח לגרמו. ותו”ת.)
** לדעת -
יש לדון מהו החילוק:
א. אפשר שקנס הוא. סתימות גמרא לא משמע כן (יש לדון). גם, אז, קשה מדין פירות (צריך ביאור מה לנו במה שהם אנוסים- אין זה נוגע לסיבה לקנוס. ואלי ל"פ הוא).
ב. אולי הענין הוא שצריך להיות מקומו בתוך התחום. אם אדם יצא, מדעת חזר ממה שהיה נקבע למקומו, ואז נתבטל מהיות מקומו. זה רק מבאר יציאה  מדעת, אבל לא הכנסה לדעת.
ג. אולי אם יצא מדעת, מקומו יותר ננעשה מקום אחר כיון שבחר להיות באותו מקום (זה קצת חלוק מ2). אפשר שכשחוזר, בוחר להיות בקרקע שבין חוץ לתחום ותחום. ותחשב עוד.
ד. אפזר שהיתר תחום הוא שיש לו מאה אמה שבו יכול לילך. כיון שהלך באמות אחרות, יהא לו יותא מזה. אי אפשר לו לשנות אמותיו, שלא קבלם. ותחשב. ויל"ד בדין פירות.
* מג.
** יוסף שידא -
יש לציין לגמרא גיטין ומכות שכתבנו שמשמע שיש להם שכר ועונש. ואולי יש רק כגוי.
** צריך ביאור למה מניח
גמרא שכל זמן שאדם הולך משמים יש בעיא של תחום. אולי מניח שכמו שיש תחום לצדדיו, יש גם כן ממעלה למטה. ותו"ת. לא משמע כן, שלא מודדים גבהוץ הרים. ותחשב.
** חנניא -
מצינו חנניא אחי ר"י וחנניא בו אחי ר"י. יש לדון אם חולקים מי הוא או אם היו שניהם. ותחשב.
* מג:
** שלא לטרוח -
יש שמקשים שטוב יותר שיבא משיח ויטרחו בני ישראל. ונראה שקל לומר שאם היה לו לבא בשבת, יביאהו ה’ בערב שבת. ויש לדון, שאז תלוי בידיעת ה’ על מעשי בני אדם (שאיך ידע אם ראוי להא בשבת). ותו"ת.
* מד:
** שלא מדעת -
לא הבנתי, שאכתי כיון שמתירו, יהא נחשב עושה מחיצה ואסור. ותחשב. ואולי כיון שלא יודעים למה הם שם, עומד ליבטל, שעומדים ללכת למקום אחר. ותח’.
שוב ראיתי ברש"י. יש להעיר שמשמע מגמרא שהיה מקשה אף מבהמה. ואולי חזר מזה.
* מה:
** קשיין אהדדי -
היה אפשר להקשות, לכאורה, אף לפני הסתירה. ותו"ת.
** דלמא הנך -
יש לדון למה נחוש לזה, ובפרט בדרבנן. ואלי הוא מפני שיש לו התיר. ונראה שבזה דן שני צדדי גמרא כאן (שבזה חולקים בביצה).
* מו:
** ומנא תימרא -
יש להעיר שאין שינוי זה שייך כלל, לכאורה, שהוא משונה לסיבה חלוקה. וש לדון, אז, מה מוכיח. אפשר שרק מוכיח שלא עושים שניהם דומים כדי לעשותם דומים (ללא פלוג).
** רבי יעקב -
יש להעיר שמצינו (על כל פנים לרשב"ם) שרבי חייא דן באלו כללים. משמע (עיין בצדי צדדים) שהיו כבר ידועים (ונשכחים, שהיה מסופק בהם) בימיו. יש גם כן להעיר שיש לגמרא כתובות צד שמת ר"ח קודם רבי. אם כן, צריך לומר שנעשו כללים אלו בכיי רבי, אף שאחד מהם על רבי.
** למאי הלכתא -
משמע שלא דנים מה נאמר, אלא מהו הדין שנלמד ממה שנאמר. (ועיין בשי"ח ש"י על רש"י ד"ה כלשון זה.)
** אף אני לומד -
יש לדון מה אומר:
א. אף אני יש לי עוד דין. מז ה, לומד, או גמרא לומד עוד דין.
ב. אף אני יכול עוד דין על דרך שלמד גמרא (קל וחומר).
** מנא ליה -
נראה שיש לדון מהו "הלכה כ…”:
א. אולי הכלל הוא סיבה מיוחדת (הוא הכי חכם). זה גורם שלעולם הלכה כמותו.
ב. אולי אומר שלמעשה נמצא שלעולם הלכה כמותו.
נראה שאולי מקשה הניח כצד שני. אז, יותר קשה הוא אי יש חד שאינו ככלל. מתרץ אולי סבר (עיין במה שנכתב, בס"ד על רש"י ד"ה היכא דאיתמר) כצד ראשון (אז, אינו כל כך קשה, שאכתי סיבה זה קיימת, אלא שלפעמים נדחה). ותחשב ותבין.
* מז.
** ומאן פליג עליה -
יש להעיר שאף רבי יוסי חולק, והיה לנו לקבוע הלכה כמותו, ובפרט כיון שכאן הוא המכריע. ותו"ת.
** מכלל דיחידאה -
היה אפשר לומר שזה גופא מגלה לנו. ועוד שאולי צריך לגלות שאף שסתם (במקום מחלקת) שיטת ר"מ, אין הלכה כמותו.
** מכללא -
יש להעיר שבדרך כלל לא מצינו לשון כזה במימרא אלא במעשה (עיין רש"י ב"ב קל:).
* מז:
** יוסף הכהן -
אולי זהו ר’ יוסי הכהן הנזכר באבות (ב-ח). לא נראה כן, שלמד מריב"ז, שהיה נשיא, ומסתמא היה בא"י. ואולי היו זמנים חלוקים, ולפני זמן היה בחו"ל. גם יש לומר שלמד מיותר מרב אחד.
** לא יזיזם -
משמע שאין להם ד"א. אולי זהו מפני שרק לאדם יש ד"א, שרק לו נחשב מקומו. אבל בהמשך גמרא משמע שיש לו ד"א; וצריך לומר שכולו נקרא ד"א שלו.
* מח.
** מחייך עליה -
יש לציין לגמרא סנהדרין (סופ"ק) שאומר ש"מחכו עליה במערבא" הוא ריב"ח. יש לדון למה לא כותב אותו לשון כאן (אלא כותב שמו).
** מחיצה תלויה -
צריך לחשוב איך למעשה מתיר. ותחשב.
** שמנה על שמנה -
לכאורה, הוא קצת יותר מזה, שיש, באמצע, מקומו.
* מח:
** גליא אדעתא -
לא הבנתי כל כך, שאולי לא עירבו כיון שאין צורך לערב. ותחשב.
* מט.
** דוחים -
איני יודע אם רק מחשיבים כאילו משתמש עמו (תחשב) או שאומרים שצריך לצאת משם או כדומה. לשון "כופין" משמע שעושים כעין השני. ותחשב.
** ארבע -
מעניין שאומר ארבע אמות לקנין שביתה, ולא שהוא יקנה בחד מקום, וממילא יהיו סמוך לו ד"א הנחשב כעצמו. ותו"ת.
(שוב ראיתי שמתחיל אלפים אמה מחוץ מדל"ת אמותיו. יש לדון, אז, למה אין אומרים שיש לו שמנה אמות, ארבע לכל צד. ואולי הוא כתנא החולק. ודחוק.)
** שמואל -
יש להעיר ששמואל סובר שאין ברירה. לרש,י,זה מפני שאף שאומר שיחול על פי מה שיקרה, אבל באמת, מכוון לדבר ברור. אולי, אז, זה קצת לשיטתו. ותחשב. יש להעיר שאי אפשר שהוא ממש תלוי בברירה, שאם כן, כבר הוא מחלקת תנאים, ולא נביא ראיות מברייתות.
* נא.
** אלפים -
צריך ביאור למה שוהה עד כאן לשאול כן.
** חשכה לו -
מה שיש לגמרא צד שלא לומר כתירוץ שני (אף שלכאורה נראה פשוט) הוא שלא מסתבר שמי שחשך עליו לא יהא רץ להגיע לביתו.
** פרק כיצד מעברים
* נג.
** חד אמר -
יש  שור כעין זה בסוטה. יש לדון למה לא הובאו כאן. ותח’.
** יב תלמידים -
יש לדון אם זה כולל ר"י או לא.
* נג:
** לסטים כמותך -
אינן כמותו ממש, שבאו עליו לפני שהיה נראה כשל רבים.
* נד.
** רבא בר -
מנשרים (שאומר שהיה רבא סתם) וממה שטעם במזיגה (ע’ שבת ריש פרק המוציא יין. ויש לדכות שיותר מחד איש מזג כן. יש לדון אז איך הכירו. ושו"ר ברש"י בביאור הא דמזיגה. אם כן, אין כל כך ראיה.ותחשב.) משמע שרבא זה הוא סתם רבא. (וצדיך ביאור למה לא נקרא רבא סתם כאן.)
* נד:
** תנו לו -
מקשים למה לא אמר שלכן ארך ימיו (בסוף מגילה). ואולי זה קרה אחר שכבר היה זקן, ואז כבר האריך ימים קודם לכן.
* נה:
** יושבי -
יש לדון למה אין מונים את זה בחשובים כמת (בנדרים).
* נו.
** מזקינים -
היה אפשר לתרץ על פי זה מה שהיה ברזילי זקן לפני שניו (שבת קנב.).
* נז.
** במח
’ רבי מאיר ורבנן, נראה שאפשר לבאר שיש לדון בענין תחומין. אפשר שאדם רק הולך במקומו, אלא שמה שקרוב לעיר נחשב מקום עיר (ומקום יושביה) (מסתמא מפני שמיוחסים לו ביחס שבדרך כלל עושה שעומד ללכת שם ולהשתמש שם) או שיכול אדם ללכת תחום חוץ ממקומו (ורק צריך להיות קרוב למקומו) נראה שרבנן סוברים כצד שני, ואז מחלקים לומר שקרפיף מהני רק לצרף שני דברים להיות אחד, וזה רק בשני עיירות, ר"מ סבר כראשון, ואז, שניהם כן, ואין לחלק. ולא מוכרח. ותחשב. (הפשטות הוא ששיטת רבנן הוא שצריך להיות דחיק תשמישו.)
** מקיר -
אם תחומין אינו מדאורייתא, צ"ל שקרא זה אסמכתא.
** מנא הני מילי -
יש לדון אם קאי על רבנן, רבי מאיר או שניהם.
* נח.
** חוט -
לכאו’, נצטרך לפרש אורך החוט. ותו"ת.
צריך לסכם כל גמ’ זה. יש לדון למה מצינו שמדדו יפה אם יותר קשה ללכת, וגם אם אינו כל כך קשה, כמו אי לא מתלקט כל כך. גם צ"ב איך לבאר גמ’ דחוט, שאומר רש"י שרק אז (שאין חוט יורד) מדדים, ושוב אומר שביותר מאלפים מדדים. מרש"י נראה שהחילוק הוא אי מבליעים אם יכול (ולא נ’ כן מרש"י בע"א).
* נט.
** עיר של -
כל עיר מתחיל להיות עיר קטן. אז, צריך לפרש מה נחשב עיר גדולה שנעשה קטנה. ותו"ת.
* ס.
** גמרא -
נ’ שאולי ר"י לשיטתו שהיה סיני ולא דקדק כל כך.
* סא.
** כלבא -
יש לציין לגמ’ בכורות במעשה דר’ יהושע.
** פרק הדר
* סג.
** מצוה להביא מן ההדיוט -
לכאו’, לא תירץ קושיא זו.
** נביא -
קשה, מה לנו שידע; בהכרח ידע, שכל שאמר עליו כן ימות, שקללת חכם בא. יש לדון אם זה בכלל קללה. גם אפשר שהיא גופא, והיתה שואלת איך ידע, שלא היה אומר כן אם לא ידע, שאז יגרום מיתתו. לא נראה כן, שמגמרא נראה שרק שאלה אחר שמת. ותו"ת.
** בלא ולד -
לכאו’, ולד משמע כל מי שנולד, ואף בת. ועיין במגילה (יד:). וצריך ביאור.
** מביא רעב -
יש להעיר שמצינו בהרבה מקומות "מכירי כהונה,” שלכאו’ הוא זה. יש להעיר שבבבא בתרא היה יכול להביא ציור אחר. כיון שזה אסור, צריך ביאור למה הביאו.
* סג:
** פרו ורבו -
אם כן, עונשו מדה כנגד מגה, כמובן. גם יש להעיר שבאותו שעה כבר היה יהושוע יותר מבן ארבעים, ומוזר מה שלא היו לו בנין עדיין. ואולי מפני זה מתו בניו. ותח’.
** מיד -
עיין רש"י מגילה (ג.) שמיד לאו דוקא, לכאו’, ואולי ר"ל ביכולתו הראשון.
** דלא שכיחא -
אם כן בזה יודה ר"מ. ואולי לא שכיח באותו דרגה של ציור מחלוקת.
** תמיד -
צריך ביאור מהו המקור שהיה הדבר אחר תמיד. ועיין ברש"י.
** גמירי -
מוזר שמלאך לא הוכיחםח על פרו ורבו, ולא נענש על ת"ת. ותו"ת.
* סה.
** אמר אביי -
עיין יבמות קו. ברש"י. ויש לדחות. ותחשב. (ועיין קדושין לא:.)
** מגן -
צריך ביאור למה קוראו מגן. ואולי זה בפרט באותו ברכה. וצריך ביאור למה.
* סו.
** ואי אתא -
לא הבנתי למה אין אומרים שרק יכול לשכור, ולא לערב.
** חד חצר -
יש לדון למה:
א. אין כל כך צורף. אז, עניו זה לפנים מזה הוא שיש אז צארך.
ב. אי אפשרבטל להם, שאינם כל כך חד. אולי מה שזה אוסר זה הוא יחס ביניהם. ותחשב.
* סז.
** מעניין
מה שמצינו ששני בקיאים- רב יוסף (עיין בסוף הוריות) ורב ששת- היו סומים. ואולי יש שום יחס. ותחשב.
* סז:
** מאן דלא ידע -
יש לציין לגמ’ חולין (קלז:).
** והדר -
אפשר לבארו על פי שיטה שאין איסור מדרבנן אם חלא מכוון לרעה. ותחשב. ויש לדון.
* סח.
** חישב -
מעניין מה שתלאו במה שחישב ולא במה שעשה. נראה שיש לדון מהא ענין בריבה, אי חל:
א. מניחים שממש חשב ל"אותו שאברר.”
ב. מניחים שהיה חושב קצת על אותו אחד שברר.
נראה שיש נפקא מינא כאן. לראשון, לכאו’ יתלה דעתו במה יעשה (או ירצה בעת עשייה), ולא במה יחשב. לשני, אולי, מה שחשב ראשון הוא סימן טוב למה שהיה חושב, ואז, אם יש ברירה, בתריה אזלינן. ותחשב. ויש נפקא מינא מזה.
* סח:
** "
ר
א- צריך לבאר שייכות כל זה, אם הדיון הוא רק אי יהא כחוכא ואטלולא.
** שוגג -
מצינו בכמה מקומות שקונס ר"מ בזה. כן אני זוכר.
** חסורי -
ואם תאמר איך ידע שהיה חולק על ר"ג. ויש לומר שלא היה נזקק להביא מעשה אם אין חולק. גם אפשר שלומד כן מן הברייתא. ואכתי יש לדון מהיכי תיתי שמשנה מביא חולק.
** כחוכא -
יש לדון מה נעשה כחוכא:
א. אולי דין ביטול רשות, שממה שיוחזר הרשות, יניחו שלא ממש נתנו.
ב. אולי דין עירוב, שיראו שכל כך קל (או שיכול על ידי דבר מוזר מפני א) להתיר תשמיש.
* סט:
** בפרהסיא -
יש לבאר למה יתלה בזה,והוא  שכל ענין זה הוא כדי שלא ילמד מהם ישראל. אז, רק מי שמפרסם ילמד לישראל אחר.
* עא.
** כלך -
צריך לחשוב על זה.
* עא:
** הא קמ"ל -
בכל כעין זה, יש לדן אם ר"ל שמשמיענו הכלל אי שמפני הכלל צריך להשמיענו הדין. לשונו משמע כראשון. (שוב ראיתי רש"י ב"ב (קל:). ועיין בשי"ח ש"י שם. שוב ראיתי במהרש”א נדה (ז:). ע”ש. ויש ליישב על פי מש,כ רש”י כאן (ושו”ר שיש אחרונים (מובאים שם בעוז והדר) שכתבו כן.))
** אין ברירה -
משמע שאי אין ברירה, אין כל אחד קונה חלק. זה קשה למה שפירש רש"י שאם אין ברירה הוא שלא כיוון לברירה אלא לחפץ מיוחד, שאז יקנה אותו חפץ. כעין זה יש להקשות למה לא קנה חד עירוב (בביצה. עיין שם) מספק. (ועוד קשה למה שכתבנו בשי"ח ש"י (ביצה- גלגל שלישי- לז:).)
* עב:
** אמרנ" בר יצחק -
מה שמשנה שמו ומה שאומר כן על מימרא שהביא עצמו משמע שאין רנ"ב יצחק סתם ר"נ.
* עג.
** סומכים על שולחנו -
משמע שהיה דרך תלמידים לסמוך על שלחם רבם. יש להקשות קצת מגמרא הוריות (סוף י.).
* עג:
** מני -
אין צריכים ראיה זה, שסתם משנה ר"מ. יש לדון למה אומרים כן.
* עד.
** ולאו מר הוא -
היה אפשר לדחות שקאי על משנה אחר שהובא כשדן בו לעיל (שמבואר שם שרק צריך חד ציור של זה). ותחשב ותבין.
** קבלה -
צריך ביאור מהו מצד שהודה, שמוכרח שיש דרך ליישב סתירה, שרק הקשה לו שלא סובר כמה שאמר. לא הבנתי איך זה ישנה מה סובר, שבודאי סבר כן, שאומרו. ותחשב ותבין.
* עה.
** הוה אמינא -
מעניין שנחשב כן, שאין שום תנא הסובר כן.
** היינו -
אפשר שהפשט בזה הוא ששכח עם שאר לימודו.
* עה:
** בית שער דיחיד -
צריך ביאור, אז, למה לא יחלקו בזה. ואולי הוה אמינא שחולקים בדין בית שער, שלא רואה שמודה בשאר בית שער. ויש לדון אם כאן יודעים שהודה או שרק מוקי כן גמרא. גם יש להוכיח כן באותו ציור ממה שלא הראו כח היתירא וחלקו בבית שער סתם.
** פרק חלון
* עו.
** הא קא מ"ל -
לכאורה, אין משמעות לזה, אלא שהוא משנה יתירה. כן משמע גם כן מרש"י; וקל לדחות (שרק מבאר למה צריכים לימוד). ותו"ת.
* עו:
** רבי יוחנן סבר -
יש להעיר ששם אותו מחלקת הוא בשיטת ר"י. אז, צריך לומר שהחולק שם לא גורס מימרא זה. ותו"ת.
** מן הצד -
יש לדון למה זה ישנה. וצריך לחשוב בדרך כלל מה ענין שבית כמאן דמלי. ותחשב.
** רשויות -
לכאורה, הענין הוא שאיסורי חצר הם דרבנן. אפשר, אז, שלא ר"ל רשויות, אלא הוצאות (שהמעשים הם האסורים), כמו שאמר רבא בתחילת שבת.
* עח.
** זה שלא כנגד -
יש לדון למה לא. תחילה, יש לדון מה עושה מיעוט זה:
א. אפשר שעושה שאינו עשר, והוא מפני שמודדים מביי"ס של הכותל. אף שאכתי קשה הוא, כיון שאין לו כותל להבדיל, נחשבים אחד. אז, אולי, אם הם כבגד זה, ביי"ס של העליון הוא על הקרקע ממש.
ב. אפשר שעושה שהוא נוח לבא מחצר לחברו, ואז נחשבים כחד. אולי, אז, אם שניהם זה כנגד זה, הענגי"ל עושה שהוא קשה לעלות מראשון לשני, שהוא דיירקטל"י עליו. כן נראה מרש"י. (ויש להעיר שיש דרך אחרת, והוא שממש צריך לקבוע סולם, ומה שאמר שצריך שאינם זה כנגד זה הוא רק סימן לזה. ותח’.)
נראה שאולי יש נפקא מינא- ויש לדון מהו הדין לצד ראשון- אי תחתון הוא כנגד ראשון, אבל הוא אף יותר רחב ממנו. ותחשב.
** מידי דהוה -
לא הבנתי, שלא מבאר כלום, ורק מוכיח, והרי כבר ידע רב שדין זה אמת. ותח’.
* עח:
** איסור שבת -
יש לדון מה לנו בזה. ואולי מה שיכול להיות פתח אף שאסור לעלות אינו (רק) שיכול לעלות באיסור, אלא שזה גורם שלמי שאינו מקפיד על איסורי אשירה זה פתח ויהא סיבה להתיר לו בשבת. מה שיתיר לו גורם שאף יתיר לאחרים. אי אפשר לומר כן באיסור שבת, שבדרך כלל, מי שלא נוהג באיסור של עליית האילן לא יקפיד על מה שמתיר לו לערב. אז, או מפני שלא יערב או מפני שלא ישנהלו אם עירב, היתירו לא חשוב להתיר לאחרים על גבו. (ואלי זה יתלה אי עובר על אשירה נחשב מומר לע"ז, שאז נחשב מומר לכל.)
** שאיסור ד"א -
יש להעיר שיש אף איסור שבת, שהוא אילן.
** הנאה -
יש, לכאורה, שני פרטים בזה, והם שאולי אי אפשר לעשותו עירוב כיון שבזה נהנה ממה שיש ש ם אשירה, ושאולי לא נחשב פתח כיון שאסור ללכת על ידי אשירה זה, ואז, אי אפשר לכנס בפתח זה.
** יש לדון
למה צריך שיהא בו פתח כדי לערב שנים. נראה לבאר שענין עירוב הוא שנעשה כל החצר כמקום אחד, וכולם דרים באותו מקום. יש לדון אם צריך שיהא ראוי לבא בקל כדי לחשבו דר שם או כדי לחשבו חד מקום. ודע שלצד קמא, אפשר שאין צריכים לומר שהוא חד מקום, אלא הוא כמה מקומות, וכולם דרים או קונים אותו. ותחשב.
** חריץ -
יש להעיר שכאן יש דבר המפסיק, אבל קל הוא לקצוף עליו. מעניין שאכתי אינן מערבים אחד. שוב ראיתי ברש"י, והעניין הוא. גם מעניין למה מה שהוא הפסק (ר"ל מקום חשוב ביניהם) מהני.אולי ייותר מובן על פי הצד שכתבנו שאין הבעיא היותם נחשבים לחד אלא היותו נחשב שדר בו, שאולי שם אין הבעיא דאינו מקומו, ולא דר בו בפועל, אלא מה שקשה לו ללכת שם בפועל. ותחשב על זה. גם יש להעיר שלכאורה אם אינו רחב עשר, יש אותו קשות. יש לדון, שאז מה יקרה אם לא פוסע בטוב אינו כל כך רע (וריס"ק זה הוא חלק ממה שעושהו קשה). ואולי צריך להיות שניהם- מפסיק וקשה. ותחשב. יש להביא קצת סמך לצד שאין צריך רשות להפסיק, והוא שאף שיש מה שמפריש על הקרקע, אין מה שהוא ביניהם באוויר. ויש לדון, שאולי רה"י עולה. גם יש לומר שחילוק בקרקע די (צריך לבאר זה. ונראה שהוא שהפסק הוא, אולי ששני הדברים חלוקים כיון שהם בצדדים אחרים של דבר חשוב. אולי מה שקרקעית שני חצרות הם כן מהני לעשות שני החצרות חלוקים ונחלקים.)
** כותל -
יש לדון מה מוכיח מזה:
א. אולי מניח שמה שצריך מחיצה, צריך לביטול חלריץ, ואש כיון שרואים שזה די למחיצה, בוודאי הוא די לביטול.
ב. אולי מניח שמחיצה צריך דבר שביטל. אז, רואים שלא ביטל זה. אם כן, יבטל חריץ.
* עט.
** מתבן -
עיין במה שמבאר רש"י. דע שאז צ"ל שדנים במחיצה שלא נתמעט כבר.
* עט:
** צריך לטעום -
יש לדון למה:
א. אפשר שברכת קידוש יותר חשוב אם הוא סמוך לברכה חשובה. ברכה שמתרת יין הוא חשובה.
ב. אפשר שברכת קידוש יותר חשוב אם בוא "על" יין, והוא שמיוחס לחפץ חשוב של יין, ואז צריך לשתות עמו יין. ותחשב, של אהבנתי את זה כל כך.
ונראה שאפשר שיש קצת יותר, והוא שכיון שהדין הוא שצריך כך, נמצא שחיובו לומר קידוש גרם לו לברך ולשתות יין. אולי זה הוא המחשיבו. ותחשב.
** לחיה -
ואם תאמר אם יש בה סכנה, פשוט, ואי לא. למה תהא חלוקה מחולה. ויש לומר שסבר שמחדש שחיה יש בה סכנה. ותחשב. גם אפשר שיש מדרגות חלוקות של חולה שאין בו כסנה. ודע שיש לומר, אולי, שני טעמים לבטל שבת לחולה שאין בו סכנה:
א. יש לו צער. אולי לא צווה תורה לשמור שבת באופן שיגרום כל כך צער.
ב. אולי יש לחוש שאם לא נעשה אותו מלאכה לו, יהיה חולה שיש בו סכנה, ונחלל עליו את השבת. אולי,אז, כיון שאין רווח (כל כך, שהרי אולי לא יעשה חולה שיש בו סכנה, ועוד שאולי כיון שעובר מלאכה, קדושת שבת נדחה (עיין בשבת), ואז אולי יש ענין לחכות.), נחלל את השבת מיד. ודע שאפשר שזה תלוי באי שבת הותרה או דחוייה (שאם הוא הותרה, יש בוודאי סיבה לחכות, שאז אינו מחלל שבת).
אפשר שגבי חיה יש שניהם וגבי אחר יש רק ראשון. גם אפשר שיש אחד (איזה מהם) יותר בחיה. ותחשב.
צריך לבאר קצת מה נשתנה בין הוה אמינא ומסקנא. מסתמא, שניהם דנים במה סובר סבי. אפשר שלמסקנה, אינו דווקא. מוזר שינקט ציור שהוא הכי פשוט כיון שהוא נכון אף כשהוא יותר מחודש. אפשר שנקט הציור הכי מצוי. גם יש לומר שבתירוץ אינו הכי פשוט. אולי משנים מפני מה מחללים (ותחשב למה לא יהיו שני הענינים שכתבנו נכונים). גם אפשר שמשנים את המציאות. זה, כמובן, צריך ביאור, אם לא שנאמר שלא ידע גמרא את המציאות, ורק הניח דבר כיון שסבר שהוא דוקא (וצריך ביאור למה סבר כן. ואולי הוא מפני שאמר ציור ולא אמר הכלל), ושוב מחדש שאינו דוקא. ותחשב.
* פ.
** התם -
גם יש לחלק, אולי, בין כשחולק לכשלא ידוע. ותו"ת.
** דלא אסר -
לא הבנתי, שאז יש סתירה אם כשאוסר, צריך אשתו. ואולי לעולם אינו צריך ורק נקט עשיית אשתו לרווחא דמילתא, אבל אין שינוי בין אם היא עושה או אם לא עושה.
* פ:
** מצד -
צריך ביאור מה זה אומר.
** זאת אומרת -
אחר דחיית גמרא, כמובן, צריך לבאר "זאת אומרת.” ותו"ת.
** רבי יהודה -
מעניין איך מגלה לנו שיעור סעודה, שלא אומר שמה שצריך הוא שיעור סעודה. ואולי ממה שאמר נוכל למעט שאר צדדים שיהיו לנו. ותו"ת. ועיין בראש ברכות כעין זה.
* פא.
** מאן שמעת -
צריך ביאור למה לא אומר שהוא האחר שנמנה ברש"י (שיש שנים). וצריך לומר שכל צד יאמר שהאחר אי אפשר לסבור כן ממש. ותחשב למה.)
* פא:
** במה דברים -
עיין לעיל שמבואר שרבנן חולקים על זה. יש לדון בזה לשיטה (עיין פרק שלישי? של סנהדרין) שבכל "במה דברים . . . “ רק מפרש. ואולי שאני כאן כיון שיש הוכחה. ועדיין מוזר מה שישתמש ר"י עם אותם מילים. ותחשב. שוב ראיתי בגמרא. (ואם תאמר למה לא תירץ כמש"כ, שאומר כן גמרא גבי כללי פסק לעיל. ואולי הוא מפני קושיתינו השני.
* פב:
** כיון שעירבו -
יש לדון מי עירב קודם. ואולי זה המשנה בין הוה אמינא של גמרא למסקנא. גם יש לומר שלעולם היא מערבת קודם, ודן אם מה שמחה לפני שידעה נחשב מחייה. ותחשב.
* פה.
** רבי עקיבא -
יש להעיר ששנים אלו (רבי ורבי עקיבא) היו עשירים (עיין נדרים (נ) וגיטין (נט))
* פז:
** לאנשי טבריה -
יש להעיר שיש מאלו שהתיר בדרך כלל, אלא שפסק כן להם, ויש מאלו שהתיר רק להם. ותו"ת.
* פח:
** ומאי -
היה אפשר לומר שסבר שתירוץ שאמר לבאר לרבה דחוק. ותחשב.
** פרק כל גגות
* צא.
** בשלמא עירב -
הוה מצי לדחות שבלי אמירה זה הוה מותר כשעירבו. ותחשב.
* צב.
** מפני מה -
עדיין צריך ביאור למה לא גזר שם כמו שגוזר כאן. ואולי חלוק כיון שיש חד שעירב על אותו מבוי. ותחשב.
* צג.
** שלח ביד -
לא רוצה לומר ששלחו בידו ממש, שאסור היה לכתוב תורה (עיין בתמורה (יד, אולי) כעין זה. ואולי יש לדחות שחשש שישכח.) אלא רק ר"ל ששלחו עמו, כמו "על יד . . . .”
** עבודת כרם - .
יש לציין למאירי ריש בבא בתרא שמשמע נגד זה.
** טעמא -
צריך לבאר למה אי אפשר לומר כעין זה כאן. ותחשב.
** שדייה -
יש לדון מה יגרום שישדה לזה או לזה.
** אם מותרים -
מצינו שר"י אומר כן ומחמיר (כן מצינו בשבת גבי מי מלח. חושב אני שכן מצינו במקום אחר. ותחשב.
* צד:
** והא -
לא הבנתי למה אין זה בעשר. ותחשב. גם לא הבנתי למה צ"ל בשני צדדים. שוב הבנתי שהענין הוא שאז צריך למלאות ארבע, וזה אי אפשר. זה מעניין, שכיון שנתמלאו שלש, איין בעיא. ושו"ה שכן הוא אף בסוכה. ותחשב.
* צה:
** ממאי דר"מ -
קצת קשה למה לא אמר שידע כיון שהוא סתם משנה. משמע שלא כל כך פשוט שכל סתם משנה אליבא דרבי מאיר הוא.
* צו.
** אות -
ואם תאמר לעולם יש אות, שהרי יש מילה. שמעתי, ואיני יודע מהו המקור לזה, שצריך שני אותיות. נראה שהמקור מן התורה לזה הוא מה שצווה תורה שבת וימים טובים, אף שבוודאי צריך להיות כבר מימות חול מהול. ויש לדון. על כל פנים, אם זה נכון, יש לדון למה ידחו שבת ויום טוב (רצה לומר, אם הם חד יום) למול בן; הא אין צורך אז שימול. יש לומר שיש מצוה למול, ויש אות רק במה שהוא נמול. ותחשב. גם יש לומר ששבת ויום טוב אות אחד ושווה הוא. (כן נראה לפי מה שמפרש רשי כאן, שהרי לכאורה, קיומם שווה.)
* צו:
** וכי אדם -
יש לחלק בין איסור שבת לשאר איסורים, לכאורה, שאיסור שבת חמור בדרך כלל. ויש לדון.
** וכי אדם -
וקשה, שהיא גופה- אם לא מסתבר שעשה כן אחר, למה נחוש. והיה נראה לומר שאומר, “אם תאמר שכעין זה נחשב לא מסתבר, אז ציור שבמשנה אינו מסתבר. אלא, צריך לומר שאין להביא הוכחה ממה שטרח בה.” ועיין בלשון רשי, שלא משמע כל כך כמה שכתבנו. ותחשב.
* צז.
** זאת אומרת -
לכאורה, רק אומר שהוא מחלקת.
** ואי לאו -
עיין ברשי. הנקודה היא שבאמת היה יותר טוב אם שהה עד שקיעת החמה, שאז לא ידחה שבת, אלא שיש טירחא בזה. כאן, אי לא שלא יציל את כלם, יהא טורח, ואז חייב לשהות, שלא מפסיד על ידי זה.
* צז.
** אוושא -
יש לדון אם זה מפני שנשמע ביותר או מפני שיש יותר שעוסקים בחילול.
* צט.
** מחשבתו -
זה מעניין, שלכאורה, לא נתנו שם ברצון, אלא שמוכרח ללכת שם. ואולי נחשב ברצון כיון ששתה. (ואם פי אמה הוא מקומו, אולי כיון שעקרו מגופו לשם נחשב שנתנו שם והחשיבו.) ותחשב.
** אמר ר"ל -
נראה שהביא זה לא רק מפני שדן ברק וכיח אלא מפני שהוא מימרא שאומר אחד וכולל שניהם (כמו שהניח גמרא על משניות שלעיל).
* צט:
** שלש -
מעניין שמותר כשהוא בתוך שלש; נמצא שנעשה חלק מן הארץ (שאי רק נחשב מחובר לו, הרי הוא אילן המחובר לו, ועדיין אסור). מעניין, שאין אומרים כן לעולם (למשל, גבי סוכה, לא פוסלים שום סכך מחמת זה. ויש לדון. אולי רק כאן, שדברים בטלים לקרקע כיון שהוא חשוב (לכן מצינו בכ"מ דין מיוחד למחובר לקקע).).
* ק.
** וכן אניגרא -
לא הבנתי כל כך דמיון שני הדינים. וצריך לחשוב.
* ק:
** יבש -
מעניין שנחשב ככבר תלוש. אולי הוא מפני שעומד ליתלש, ואולי הוא מפני שלא בא לו שום דבר מן הקרקע. ותחשב.
** והאידנא -
לשון זה מעניין; היה לו לומר, “וכיון דקיי"ל כרבי שמעון…. “ ותחשב.
** ייחוד -
קשה, שלכאורה, אין זה מדאורייתא.
** מגדלת -
משמע שאף מאז היו אנשים מקצרים את שערם ונשים היו מגדלות.
* קא:
** כרמלית -
יש לדון, אז, אם למעשה חולקים רבנן על דין רשות הרבים (עיין גמרא לעיל) ומהיכי תיתי.
* קב:
** מחזירים -
נראה שהחילוק ביניהם (למה חד יותר נח מחבירו) הוא מה שהתחתון כשחסר עושהו ישר ומכוון למקומו מפני גרביטי, אבל עליון שחסר יעשהו עקום.[fn:1]
** רבי אליעזר -
קשה, שגמרא בשבת אומר שלא אמרו בכל מכשירי מצווה.
* קג.
** רבי אליעזר -
אז, היה אפשר לתרץ על פי זה לעיל.
** בני חבורה -
לכאורה, רצה לומר שמי שעוסק בקדשים זרוז. מוזר, שיהא יותר סיבה להיות זרוז ממה שאי לא, דילמא יעבר. ויש לדון.
* קד:
** שרץ עצמו -
צריך לחשוב מה יהא הסיבה לזה, ואיך דבר כזה יהא.
* Footnotes
[fn:1] יש להוסיף צורה לבארו קצת:
