** פרק מבוי שהוא גבוה
* ב.
** מבוי -
צריך לדון עד מתי נחשב כותל כותלו (ולא אומרים שכיון שלאחר שלש מיל יש כותל נחשב רה"י). ותחשב.
** מבוי -
היכירא- זה מחלקת בגמרא.
** תני פסולה -
צריך ביאור מה אומר. משמע שכדי לומר שדבר פסול, צריך להיות שכבר אמר שיעורו, ורק אחר כך יאמר שאם לא עשה כן פסול. (יש לדון למה. אולי סבר, ואף זה צריך לבאר, שבעיקר יאמר התורה מה לעשות, ולא מה פסול, אלא שכיון שאמר מה לעשות, יאמר בו פרט שאם לא עשה כן פסול) יש להקשות שאם סומך על שיעור שכבר אמר, אין צורך להלכה, שכבר יודעים השיעור. צריך לומר שיש צד שלא יעכב. ותחשב. גם אפשר שלא אמר השיעור באופן כל כך בהיר. ותחשב.
** פסיק -
עיין בנה שפירש. היה אפשר לפרש שחשש שישכח קודם הדין (ואז לא יושאר בידו כלום, ואף לא פסק פסולה) כמו שמצינו בתחלת נדרים.
** קדושה אחת -
רש"י אומר שרק מכוון לדמיון בדין. היה אפשר לומר שיש יותר שעושהו אחד (אולי סיבת קדושתם הוא שווה). ותחשב.
** אהל מועד -
משמע שבא להוכיח מזה מה היה אהל מועד. וקשה איך יאמר שהיה כלים אלו בהיכל. ואולי יש שום קרא שאומר כן. ואפשר שלא בא להוכיחו מקרא אלא אף ממשנה, ויש משניות שאומרים ששם היו. ותחשב.
* ד.
** לרבא -
צריך ביאור איך ידע שהוא מצומצם. ותחשב.
** מיסב -
שהוא שוהה יותר- יש לדון על מה קאי (מיסב או לא מיסב). ותו"ת.
** בקרן זוית -
זה, לכאורה, אינו נכון, שאין הפתח שם אלא 3.16227766, ולא 4. ותו"ת. ואולי מה שהוא על ד של מבוי מהני. שו"ר בתוס’.
* ה.
** מאן דאמר אכבע -
עיין בביאורו. לא הבנתי כל כך אז למה יכול להיות חלק ממנו למטה מקורה, שאז אין מקום חשוב במקום הנצרך. ויש לדון (ואוי אין תחת קורה.) אולי כיון שהוא תחת קורה מחשב (כן משמע מרש"י לבאר מאן דמצריך חד.) לא נראה, שאז קשה למה צריך ארבע. ותחשב.
** נקטינן -
עיין במה שפירש. מוזר, שבדרך כלל, הוה אמינא שבר קבלה מרב ומנהג מאב. ותו"ת.
* ז.
** מכל מקום -
עיין בשני הגירסאות. נראה שאי גורס לא. אומר "מכל מקום" על הקושיא ותירוצים, ואי לא גורס לא, אומרו על תירוצים השונים. ותו"ת.
* ט.
** ובלבד שלא יחליפו -
עיין במה שכתב. גם יש לומר שהבעיא הוא שמראית עין יש בו. ותחשב.
* ט:
** מי לא שמיע -
נראה שאפשר שמה שכתב "ברייתא דר"ח,” ולא רק "ברייתא" הוא לכוון למה שכתבנו בשי"ח ש"י על גמרא (ד"ה מי לא שמיע).
** ונימא -
כלבוד- יש להעיר שלבוד זה מעניין, שעושה שיש לו מחיצה, ולא שמחוברים. ותחשב. אולי כן כוונת רש"י כאן. ותחשב. ותו"ת. (ועיין לקמן שאומר רש"י שלבוד הוא (ולא רק כלבוד).) (ועיין לקמן שכותב כן רש"י בטז:. ותחשב. גם יש להעיר גמרא אומר כן גבי מה שהוא לכאורה לבוד ממש (עט:))
* י:
** אין הכי נמי -
יש לדון מה יותר טוב בו. ואולי רק ר"ל שהוא יותר טוב לשנות כיון שיש בו חידוש זה. ודחוק, שאינו יותר טוב, שטרחה הוא. ותו"ת.
* יא.
** פיתחי שימאי -
עיין במה שציין. לכאו’, שם לא פירש כן רש"י. ותו"ת.
* יא:
** הא דרביה -
בתרייתא- עיין בנוסח אחר. לא הבנתי מה אומר.
* יג:
** שמקדימים -
לשון " דבריהם" לא משמע כן (אבל המעשה משמע כן).
* טו.
** יע"ל -
נמצא שאומרים כן אף אי יש חולק אחר. ותו"ת.
* יז:
** ובלבד -
עיין לקמן בגמרא שמשמע שהוא ממש. ואולי סבר רש"י שמשמע ממשנה שקאי שיעורו, וגמרא רק מדייק ממה שצריך לשיעור זה. ותו"ת.
* יט.
** רבקה -
אם כן, צריך ביאור למה צריך לשנותו.
* כד:
** פום נהרא -
בא רש"י לומר שלא תפרש לומר שהוא פה של נהר (וצריך ביאור מהו הכרחו). ונראה שאולי לכן נקרא אותו העיר באותו שם (שכמבואר כאן, היה קרוב לנהר). ותו"ת.
** לחי -
עיין במה שכתב. גם היה אפשר לומר שיותר קל לנעוץ לחי מלנעוץ צורת הפתח. ותו"ת.
* כז:
** עור -
עיין במה שפירש למה נחשב יותר גופו. גם יש לומר שהוא מפני שאינו רוצה לגזזו כמו צמר. ותחשב ותבין. ויש לדון, שזה דומה לרש"י, שרק אומר שמהנה את הבהמה. ותחשב.
** גידולי -
היה אפשר לומר על פי אותו גמרא חולין שיביא גמרא לקמן (גבי עוף) שאומר שבהמה נברא מיבשה. ותו"ת.
* לג.
** מקום פטור -
בטל- לשון זה מעניין, ובפרט כיון שאינו נעשה כשום אחד מהם. ותו"ת.
* לג:
** אלא -
קלוטה- משמע שכל זה רק לתנא שאומר קלוטה כמי שהונחה דמיא. ותח’.
* לו:
** בא -
על ידי עירוב- היה אפשר לומר שדרים באמצע.
** ליתא -
היו שניהם- אף בלי זה, הרי תנא שילך למקום שרבו שם, אף שיש בזה ברירה. ותו"ת.
* מ:
** מי בדלת -
עיין שם, שמבואר שאין זה אם טעה. וצריך ביאור.
* מא:
** מי שהוציאוהו- תוס’ -
עיין במש,כ. משמע שפירש שהכחשת פמליא נכלל ב"עובר על רוח המקום.), וצריך לבאר מהו העברה זה. ותח’.
* מב.
** הקיפוהה -
לכאו’, אינו צריך להיות לדירה, שיש לומר שארוך יותר באלפים, ורק כולל סאתחם. נ’ שזה דחוק, כיון שיהא כל כך מעט ברוחב. ותו"ת.
* מב:
** ארבע -
עיין בפשטו הראשון. לא הבנתי, שלכאורה אם לא קנה מקום, לא ילך כלל. וצריך לומר שמניח שאין ענין תחום שאין להלך אלא במקומו, אלא שלא יצא ממקומו. ותו"ת.
* מג:
** אליבא -
עיין במה שקורא לר"א רבו של ר"מ.
(חושב אני שכ’ כן רש"י במק"א).
מעניין, שבפשטות רק היה רב רבו. ואולי לזה מכוון.
* מה.
** והם לא באו -
יש לדון למה אומרים שמסר נפשו, שהרי הובטח שינצח. ותחשב. ולולי רש"י הוה אמינא שהיה שבת, ומסתמא שאל לשמואל (או ידע מעצמו אותו דין), וגמרא רק מפרש אגב מה שאל לאורים ותומים (ואלי הוא שלא תאמר שהיה הוראת שעה על פי ה’. יש לדון אם הכרח גמרא דוחה זה. ותו”ת.). ותחשב.
** והושעת -
רצה לומר "אלמא שאל אי יצלח,” שבזה היה גמרא דן. ותחשב ותבין.
* מה:
** יש להם -
ענין מה שאומר רש"י הוא שאין נפקא מינא, ואז רק מקשה מן הלשון.
* מו:
** כלשון הזה -
משמע שמחלוקת זה תלוי בלשון שנאמר מימרא. עיין במה שכתבנו על גמרא ד"ה למאי.
** בשיורי -
רש"י רק נותן חד ציור וחד דין; וצריך להיות יותר מזה, שאי לאו הכי, לכאורה לא היה אומרו לכלל. ותו"ת.
** ולא אמרו -
שם מבואר שר" ל שהעיקר הוא שיתוף ורק מחמת שיתוף פטור. אם כן, אולי אף של חצירות עיקר, אלא שלפעמים אין צורך בהם. ותח’.
** היכא דאיתמר -
עיין במה שכתב. קצת משמע שבא לבאר כצד שני שכתבנו על גמרא (ד"ה מנא ליה), שלא רק אמר שעדיין יש סיבה לפסוק כמותו (ויש לדון, שאולי אף אי זהו חידוש הכלל, צריך להיות טוב בלשון הכלל), אלא שהרי הוא כאילו אמר כלל, “כשלא נאמר הלכה, הלכה כר"י . . . .“
* מז.
** בהמה -
מעניין שיש מושג כזה בבהמה. ואולי הוא רק כדי שלא יוקרב לקרבן לע"ז. ולא משמע כן לשונו.
** רב -
מניח שהני כללי היו בימי ר"מ. ולולי רש"י, הייתי אומר שלשון "ליתא" משמע יותר ממה שיש עליהם חולק. ותו"ת.
* מז:
** חפצי הנכרי -
מעניין למה לא נחשבים נכרים קונים שביתה, שרק אין להם איסור לצאת משביתה- והרי אף בהמוות אין להם איסור. ואולי ר"ל שאין שביתתם שייך, שאין אדם מוציאם. ויש לדון, ששייך לחפצם. ותחשב עוד.
* מח.
** של קודש -
אמתו של משה- לא היה אמתו ממש (עיין רש"י בכורות מד.).
* מט:
** כר"ש -
מבאר כר"ש של רב כיון שעל פסק של רב קאי. ותו"ת.
** שאני -
לולי רש"י היה אפשר לפרש שהוא מפני שיכול לקרוא לחלק מעשר ושוב לחלק אחר (אם, בין שניהם, אינם יותר מן השיעור. וי שלדון אם דין זה אמת. המשך גמרא אינו כל כך טוב, אבל אפשר, לצד זה שכתבנו.
* נא.
** נימוקו -
עיין בגיטי (כן חושב אני. ואולי הוא במקום אחר)ן במה שפירש. ותחשב.
** פרק כיצד מעברים
* נג.
** או גשרים -
ע’ במה שהוא בנפשות. אפשר שלכן נקרא נפש (ואולי כן ר"ל).
** דוד -
זה מבאר יותר טוב לצד ראשון שכתב רש"י לעיל.
* נו.
** תומי וכרתי -
יש לציין לגמ’ שבת (קמ:) שאומר שרע לאכול ירקות (וסתימותו משמע שקאי על ירקות סתם). אז, הוה לו להביאו לראיה. אולי סבר שמדלא מביאו גמרא משמע שנחית גמרא לומר שחולקים (כיון שהוא רק מימרת אמוראים). עדיין מוזר למה אין רש"י מביא ראיה מזה (שיותר מסתבר שלא חולקים משחולקים).
* נז.
** לשון אחר -
הלכך- זה, לכאו’, לשני הלשונות.
* נז:
** כנגד לבו -
גם הוה מצי לומר שהחידוש הוא שאף ששניהם אוחזים אותו בחד מקום צריך להיות לבו, שצריך לאחזו בחוזק (שאי לאו הכי לא ימשך חבל כל כך), ויותר קל לעשות כן כנגד לבו.
** הא -
סתמא- נראה שר"ל שלא רק הוה חוזר לדברי ר"מ, אלא שסתם הוא, וממילא ר"מ הוא.
* נח.
** ובלבד -
ללשון ראשון נמצא שכל יתרונו של הר הוא לתחום (שמנכה מיציאה מתחום). נמצא שיוכל לילך יותר שם מבשאר מקומות.
* נח:
** שומעים -
ע’ במשנה, שלכאו’ אומר טעם אחר (שרק מדרבנן הוא).
* נט:
** דפנימית -
לא הבנתי למה נחשב מדת סדום, שרוצה לצאת, ויש לו צורך.
* ס.
** ואסור -
צריך לפרש "ניחא,” שמסתמא רוצה באותו מקום יותר משלא לזוז.
** פרק הדר
* סג.
** תלמיד חבר -
יש לציין לגמ’ גיטין (נט.) שמשמע שהיה ר"א הגדול בתורה.
** ואי בעית -
יש לדון על איזה מהם (או על שניהם) קאי מופלג. ויש לדון איך נדע שהוא יותר מחד.
** בפניו -
נמצא שלא גרס ככת"י המובא בעוז והדר.
** לשאול -
לא אמר שר"ל לגיהנום, שלכאו’ לא הלך יהושוע לגיהנום (ועל כל פנים אין מקור שילך לגיהנום).
* סד:
** שינה -
או זה- כן מוכרח, לכאו’, מקושיית גמרא מר"ג.
* סז:
** לא שכיח -
עיין במה שכתב. צריך לחשוב אם לא שכיח שיהיו שניהם למה אין שניהם מותרים, ולמה צריך טעם גמרא. וצריך לומר שאינו כל כך לא שכיח או שאין מה שעושהו לא שכיח קרק’ כל כך חשוב. ותחשב. ולולי רש"י הוה מצי לומר שגזרא על היותר מצוי. ותחשב. ואולי כן רצה לומר.
* סח.
** אין -
רש" לשיטתו שסבר שאם אין ברירה, יש סיבה לו לחול על אחד, אלא שאין ידוע איזה אחד. ותו"ת.
* סט:
** עד דהוי -
עיין במה שכתב. לולי רש"י היה אפשר לומר שכיון שהודה בעבודה זרה, אין סיבה לו לקיים שאר התורה, שלא מאמין במי שציווה אותם. ולא נראה, שיכול להיות שמאמין בה’ ובאחר, ואז מאמין בתורה.
* עב.
** אין משתתפין -
יש לדון איך שייך צד של "נהגו" כאן, שמחמיר, ואז בודאי לא נאמר להם לעצור. ואולי רק ר"ל שאין הלכה כן, אלא שאגב- ואין מזה נפקא מינא- כן נהגו. גם יש לומר שנהגו ר"ל שנהגו כן מחמת עצמם, ולא מחמת שום הוראה (כן נראה הלשון), ומפני זה יש לו. אולי ר"ל שכן הוא כאן (ואכתי אין בו נפקא מינא).
** וב"ה -
פירש כמסקנת גמ’. ועיין שם.
* עו.
** לא מינכרא -
זה מראה מקום.
* עז.
** מעלים -
מעניין שיכול ליבטל לשני רשויות. לכאורה, ענין ביטול הוא שנעשה חלק של דבר אחר, ונוטל שמו. קשה, אז, שכיון שיש לו שם רה"ר, יהא אסור לרה"י. ואולי מה שיש לו שם רה"י מתיר את זה. ותחשב.
** ורב -
יש להעיר שאם ידוע הוא ממשנה, קשה למה אמרו ר"ד. ואולי רק משמיע לנו דין היוצא מן המשנה.
* עט.
** תבן -
יודעים אנו- תלאו במה שעומד לשאר שם (או שלא עומד לינטל). לולי רש"י, אפשר לומר שאין הענין למה עומד, אלא כוונת הנותנו שם. ותחשב. (ובכל זמן שכוונה משנה דין, יש לדון בצדדים אלו, והם אי עושהו עומד או שמחשבתו עושה לו שם.)
* עט:
** סבי -
שם אומר שהוא ר"י ור"ע. אולי היה ר"ע עיקר תלמידו (י.מ.ו.). ודחוק.
* פ.
** רב תנא הוא -
עדיין חולק הוא על סתם משנה, ומשמע שלא סובר שהלכה כסתם משנה.
* פ:
** כל שהוא - -
ר"י פליג
אם משנה רק דן בנתמטמט (עיין בגמרא), לא חולק ר"י.
* פא.
** חלתה -
עיין ברש"י שבין דיבור זה ודיבור של נחתום, אומר שני סיבות חלוקות. ואולי משנה בין הוה אמינא למסקנה של גמרא. ותו"ת.
* פב.
** -
פסולין
יש להעיר שיש מחלקת בזה שם בסנהדרין (ובאמת, שייך הוא לדיון מתי ר,י חולק.
* פב:
** ושניהם -
צריך ביאור למה לא מזכיר מה שיכול לאכול יותר כיון שיש לו נפש יתירה. ותחשב.
* פז:
** אין חורין -
עיין במה שכתב. משמע שהוא שכיון שרק מדרבנן הוא, לא רצו להחמיר כל כך. גם היה אפשר לומר שחור נעשה חלק מאותו רשות כיון שמשתמשים באותו רשות משתמשים בו. אולי אין משתמשים בכרמלית כל כך, ואז אין מה לעשות חור לחלק ממנו. ותחשב. יש לדון, שאולי אף שאין סברת חור שייך, אם היו גוזרים, לא היה מפני שהוא שווה לכרמלית, אלא כדי שיהיו לכרמלית חורים כמו שיש לשאר רשויות.
** פרק כל גגות
* פט:
** דבי -
עיין במה שכתב. משמע שלשון זה רק אומר שהיה לו ברייתא. יש להעיר שחושב אני שיש צקוצות שאומרים ר"י לשיטתו עם תדר"י. אפשר ששאני תנא, שיש אפשרות שתני הברייתא.
* צ.
** התם -
נראה ששני מחלקיות אלו לשיטתם, שסבר רב שדירה שלמטה חשוב (ואז מחלק ואז עושה אותם מחיצות של דירה) ושמואל סובר שאינו חשוב (ואז לא מחלק ולא עושה אותם מחיצות של דירה).
* צד:
** כפי
הבנתי, נראה שרש"י מפרש בשמואל שהוא שוה לרב, אלא שאין קירוי באלכסון אלא שאינו שם (שניטל עד ארבע). לא הבנתי, אז, למה לא פירש גם כן בחצר שהוא עשר, שאם לא יהני פי תקרה, אז יאסר.
* צה.
** דאורייתא -
הוצרך לבאר כן מפני שמצינו כמה מקומות (במקום אחר כתבנו כמה) שדאורייתא משמע שאינו הלכה למשה מסיני.
* צו.
** מי שצריכים -
עיין במה שאומר, שמשמע שהאות הוא שכיון שבנני ישראל מקיימים את השבת, יש סימן למה שמחזיקים בכל התורה. ותו"ת.
* צו:
** כיפי -
נראה שרשי סובר שפשט השני יותר נכון כיון שדרך נזמים לתלות (ואז יש לומר "תלא ביה"), ולא דרך מרגליות בפני עצמם. ותו"ת.
* צט.
** וכן בגת -
עיין שם, שחולקים בו רבא ואביי. רשי מבאר מה אומר רבא.
* ק:
** עטופה -
קשה למה לא אמר שחייבת לכסות את שערה. אולי רצה לנקוט מה שהוא אף בבתולות.
** עבר -
משמע שישיבה באילן מחשב מעשה (שלכאורה, זהו החילוק כאן). העיר לי א.ר. אפשר שהענין הוא מה שמשתמש בו (נותן לו הנאה או משנהו) אולי יש לפרש רש"י ברכות ( יט) גבי כלאים כמו כן.
* קב.
** מותר לנטותה -
גם יש לומר שאולי חלוק פתח (כזה) מגג. יש לדון למה . ואולי גג מציל ביותר. ויש לדון. גם יש לומר שכיון שרק פתח הוא, רק מוסיף על הכותל, והוה כהוספת אהל.
* קב:
** בשיפועה -
קשה למה לרשי אין אומרים לבוד לעשותו אהל. אולי הם כל כך מרוחקים זה מזה שאין בעיא.
** בשיפועה -
עיין במקום אחר (שבת, ריש פרק עשרים) שאומר רשי (כן אני חושב) שאין מטה כזה עשוייה לשכוב בה. אם כן, אין קשיא כאן. ותו”ת.
** אם בתחילה -
אומר כאן שני דברים כאן. יש לדון איזה מהם העיקר (ואולי צריך שניהם). ותחשב.
** פלוגתא -
חולקים אף לענין דברים אחרים (שם בשבת).
* קג.
** ואביי -
מבואר מזה ש”זריז” כאן רק ר”ל שיודע ההלכות. יש לדחות שרק כולל זה.
