* ב:
** שלא עשו מעשה -
משמע שמי שלא עושה מעשה יותר קל ממי שעושה מעשה. מה שלא מקבל עונש אינו מוכרח כן, שהיה אפשר לומר שהוא מפני שבחילוף מעשה בא לו עונש של מעשה, ובחילוף מה שאינו מעשה, לא נכון שיבוא לו עונש כזה. ותחשב.
* ד.
** לא עלתה -
עיין ברש"י. הביאור אינו שזה מפסיק, שאז לא צריך להיות שראשו ורובו שם, אלא שבא ראשו ורובו למים שאובים. (עדיין לא צריך להיות שכולו במקום אחד, כמו שאומר רש"י, אלא שרובו שם.) אבל, נראה לי שאין זה מוכרח, שכדי להפסיק, צריך רובו, אם לא מקפיד עליו. לא נראה שיקפיד עליו כאן, ואז צריך רוב כדי להיות חציצה. ותחשב. (וא"ת למה לא יהיה חציצה. ויש לומר שבטל למים עד כדי שלא יהיה חציצה, אף אם לא בטל לו עד כדי שלא ייחשב מים שאובים. ותחשב.)
[אגב, דיברתי עם א.מ.ו. בענין לאו הבא מכלל עשה. מזה יצא הערה טובה שלומדים את זה מתנאי, אבל החידוש שמצאנו בתנאי אינו שווה לחידוש שמצאנו בשאר מקומות שאומרים אותו כן. תחשב על זה. גם יצא לנו ביאור של הסיבה שלא אומרים כן, והוא שאז ההן שבא מן המילים שלו לא בא רק מן המילים, אלא גם מידיעה. למשל, אם אומר שאינו חולין, יודעים שהוא הקדש לא רק מפני מה שאמר, אלא גם מפני שיודעים שאין מה שאינו חולין חוץ מהקדש. גם יכול להיות מפני שלא דיבר עליו בפירוש לומר מה הוא, אלא לומר מה אינו. ותחשב.]
* ה:
** הדר חזייה -
כמובן, יש לציין לגמרא ביבמות, שגם רבי יוחנן כעס על רבי אלעזר על שלא אמר דבר משמו. שם, דחה שכולי עלמא יודעים שכל מה שאמר ר"א בא מר"י. כמובן, לא ידע ר"ל כן. אולי רק לא ידע ר"ל כן כשאמר לו חידוש בדיבור זה לזה, ולא אמר אותו בשיעור. ותחשב.
** אין… עד -
משמע שהחידוש הוא שלא נהרגים קודם. אבל, ממשיך לדבר בחידוש שלא נהרגים אם גורמים שייהרג. ותחשב.
** רבי יהודה -
צריך לעיין מה היה הו"א לתלות זה בזה. כמובן, סובר שדנים אם דוחים עדות מפני שלא מסתבר לנו. אבל, עיין בשבועות שמסיק גמ’ שדוחים לפעמים. עיין שם.
** לאו קל וחומר -
וא"ת הרי אומר "נפש.” ויש לומר שהו"א שזה רק בא לומר ציור שלא הרגו לו, כדי שירבה גם ציור זה. אבל, לא ממעט ציורים אחרים מלהיות נלמד ממנו.
** למחר -
מעניין שאומר לשון זה (שמקרב מיתתו) על עצמו (אף שאומר אותו בלשון חבר, ולא על עצמו).
** עד זומם -
מעניין שקורא לו כן, כיון שעד משמע שנים. אולי כיון שאומר "זומם" בלשון יחיד, אינו בעיה. גם אפשר שהולך לשיטתו, שלא דורש כן, ואז לא יודע ש"עד שקר העד" הולך על שני העדים.
