* ב.
** כיצד -
בגמ' מפרש- עיין בגמ', שמקשה שני קושיות. כנראה, יש קושיה פשוטה כאן שמכריח לרש"י לבאר שגמ' יסביר את המשנה. נראה שהוא קושיה ראשונה של גמ', שקושיה שנית של גמ' תלוי במשנה לקמן. אז, לא צריך רש"י לבאר משנה למי שמקשה קושיה זו, שסתם קורא לא ידע משנה שיבוא. ותחשב.
** תנא התם קאי -
לכאו', קושיית הגמ' הוא שכיון שלא עושים בהם "כאשר זמם," אי אפשר לקרא להם עדים זוממים. אז, צריך ביאור מהו תי' של הגמ'. (אולי צריך לומר שקושיה של הגמ' הוא שמילים של "עדים זוממים" משמעים כן (או בצירוף ביאור הפשוט של מילת "זוממים" או מפני שכן הוא ציור הרגיל) כיון שזה המשנה ראשונה- שצריך להיות ההקדמה- של המסכתא.) אולי יכול להשתמש באותו מילה כיון שהוא המשך של משנה אחר שאומר מילה זו כשדן בעדים שהם קצת זוממים (שמקיים מה שזממו לעשות לבעל).
** חוץ מזוממי -
עיין בלשון רש"י בביאור הדין, שמשמע שבא להם מיתה שזממו על הבועל. אז, אם לא ימיתו את הבועל (למשל, היה קטן או כבר מת), יקבלו מה שזממו על האשה. ויש לדון, שאולי זה מגלה שרק בא לו מה שזמם על אח, ואם לא זממו כלום, לא בא להם כלום. ותחשב.
** קל וחומר -
יש לדון אם עונש של עדים זוממים בא ממה ששקרו והטעו את בית דין או ממה שעשו שהוא עומד לקרות רע. ממה שלא פורכים ממה ששקרו לבית דין, צריך לומר שזה בכלל לא סיבה, ואז צריך לומר שמצדד עכשיו כצד שני. ותחשב. כן נראה גם ממה שנותנים לו כאשר זמם. ויש לדון בזה, שיש לומר ששקר על דבר יותר חשוב הוא יותר חמור, וטוען עונש יותר חמור.
** כאשר זמם -
ואם תאמר ניתן דין ב"ג וב"ח לו ולא לזרעו, שבין כך ובין כך לא מקויים דין כאש"ז, ועל כל פנים נקיים אותו במקצת. צריך לומר שאין סיבה (מספקת), כיון שבין כך ובין כך לא מקויים כאש"ז.
* ב:
** משום רבי עקיבא אמרו -
יש להעיר שזה חלוק משאר ה"דברים." שאר הדברים הם דברים שלא עושים לזוממים. אבל, כאן, הוא מצב שאין עונשים להם מה שבדרך כלל עושים להם. במילים אחרים, נגיד ככה. נכון הוא שכולם הם ציורים שאין עושים "כאשר זמם."[fn:1] אבל, באחד, אף שניזום באופן הראוי, אין נותנים עליו דין של כאשר זמם, והבעיה הוא בעונש שניתן לו. אבל, בשני לא ניזם כראוי, ובזה הוא הבעיה. ותחשב.
** בגנתבו -
גם ממעטים מכאן מכירה בכפלותו. לכאו', שניהם דרשה אחת, שגנבתו דווקא. (ודע שיש לדון אם יכולים לומר, אז, שדורשים מן הייתור. נראה שלא קשה לומר כן, שנראה שאולי יש ייתור, וזה אומר לנו דבר. אולי מסתבר בביאור הקרא שמה שאומר לנו הוא שהמילה דווקא. ותחשב.)
** רמז -
ואם תאמר עדיין מהיכי תיתי מלקות בשני הציורים. נראה שני צדדים. אפשר שלא דורשים מן הייתור- לא דורשים מן הקרא שצריך להיות מצב כזה- אלא קרא מלמד שבכל מקום ש"הקצדיקו את הצדיק..." יש סיבה למלקות, אלא שלפעמים כבר יש עונש אחרת. גם אפשר לומר שייתור הוא, ואין חילוק בין שניהם, ואם יש מלקות בזה, יש מלקות בזה גם כן, והוא אותו חידוש. (כמו כן, נוכל לומר שלא יודעים איזה ללמוד, ואז לומדים שניהם. ותחשב.)
* ג.
** העדנו והוזמנו -
ואם תאמר למה אין זה חוזר ומגיד. ויש לומר שאין הכי נמי, לא נאמן נגד עדותו, אבל נאמן שהוזם. יש לדון. (יש להוסיף שאם אין הודאת בע"ד נאמנות, אלא התחייבות, אינו כל כך קשה.) גם יש לומר שהוא כעין פה שאסר, שלא יודעים שהעיד כלל חוץ מדיבור שלו. גם יש לומר שכיון שכבר הוזם, לפי שיטתו, כבר נדחה דיבור שלו.
** רבי עקיבא -
אם מודה בקנס ובאו עדים פטור, היה אפשר להוקים אותו כשאחד הודה ושוב באו עדים.
** משלשים -
עיין בפשט שני של רש"י. ויש לדון למה נוקט שלש, ולא שנים (שהוא סתם ציור של עדים). נראה שיש חידוש בשלש, שהוה אמינא שכיון שרק צריכים שנים, אחרי שהעידו שנים, כבר נגמר העבירה, ואז ישלמו השנים הראשונים בלבדם. מחדשים שאף השלישי חייב לשלם, כיון שהיה חלק מן העבירה.
** מעידים אנו -
יש לדון מה יקרה אם נמצא שמתה ביום שלאחריו, למה לא אומרים (שלכאו' לא מחייבים להם את כולו) שכיון שנמצא שהיו מפסידים את כולו, חייבים את כולו. נראה שיש שני מהלכים. הראשון הוא ששמים בשעת החיוב, ושמים על פי מה שנודע אז. השני הוא שמה שמחייב אותם הוא מחשבתם (כן משמע לשון הפסוק של "כאשר זמם," והם לא ידעו שתמות. ואגב, בשניהם, יש לדון מה יקרה אם ידוע שקרובה היא למיתה. לכאו', אז ישלמו יותר.)
* ג:
** דלא עביד איניש -
יש לדון למה כותבים שטר, אם הוא כדי לזכור ולהזכיר את החוב או מפני שלא מאמין את הלווה. לכאו', גמ' שלנו מוכיח שהוא (על כל פנים, שלפעמים הוא) מחמת טעם ראשון, שהרי לשני אין חילוק בהמשך זמן החוב. ויש לדון, שאולי חושש שעדיו יומתו (ויל"ד, שבין כך ובין כך יטעון שפרוע הוא), או שאולי לא ישקר מיד אחרי שהיטיב לו חברו ללוות לו. ותחשב.
** לא תיתב -
מעניין שאומר לשון זה, שמשמע שקושיה גדולה היא, אף שהיה פשוט לומר שכך שיערו רבנן.
** שלשים יום -
כמובן, משמע שלמד"א (תחי' ר"ה) שיום אחד בשנה חשוב שנה, יהיה סתם הלוואה ליום אחד. ותחשב.
* ד.
** לא תני חסר קורטוב -
צריך באיור, אז, למה אין מים עם חלב פוסל את המקווה. לכאו', אין סיבה שהחלב יבטל את המים, שיש יותר מים מחלב. ותחשב. אולי יש יותר חשיבות לחלב ממים. (תחשב למה.)
** לא תני -
יש להעיר שעדיין, לכאו', צריך לומר שרב הוא כרבי יוחנן בן נורי, אלא שדינו הוא כרבנן. ממה שלא אמר חלב, אלא רק אמר יין, משמע שסובר שאינו כן בחלב, והוא כרבי יוחנן בן נורי. ויש לדון, שיש לומר שאמר את הדין שוהא נכון לדברי הכל. ותחשב.
** לרב פפא -
וא"ת לרב פפא, איך רב מתרץ הא דרבי חייא. וי"ל שסובר שרבי חייא חולק על רבי יוחנן בן נורי ורבנן, שגם הוא (רבי חייא) תנא.[fn:2] גם אפשר שר"ח תני "חסר קורטוב," ורב היה נחית לחלוק על רבי חייא בגירסת המשנה.
** וכן -
נמצא שחשש זה יותר גדול מספק. זה נראה מוזר לי.
** חיישינן -
וא"ת למה צריכים שלש לוגים, שאף פחות מזה יהיה חציצה, ולא יועיל לו טבילתו. צריך לומר שנחשבים אחד (עיין בפרק ראשון של שבת, שמים על מים היינו הנחתו, שממה שמביא גמ' ביין ושמן משמע שהוא מפני שנעשים אחד. אף שכאן יש חילוק בענין הכשר מקווה, ממה שלא חילק שם, משמע שאין חילוק. אבל, צריך לומר, אז, שאף שנעשים אחד, אינו מבטל אותו לענין לפסול אותו.), עד כדי שיכול לטבול בו, אם אינו כשיעור הראוי לפסול. יותר מכך, צריך לומר (מהמשך הגמ') שכן הוא ביין, שגם הוא בטל לגבי מקווה להיחשב אחד (וכן נראה גם מגמ' בשבת). ותחשב על זה.
** לרבא -
קפיד נמי- משמע שתולה בשניהם. יש לדון מהיכי תיתי מדברי רבי יוחנן או מדברי רב לזה. גם יש להעיר שאם כן לא חולקים על ציורים שמביא בריי', אלא על ציורים אחרים. זה קצת מוזר. ותו"ת.
** וחכ"א -
צריך לחשוב על כל זה. רבנן סוברים שיש רק מקור לעונש אחד. אז, קשה למה רבנן צריכים מה שאין לוקים ומשלמים.
* ד:
** גמר מעדים זוממים -
יש לדון למה לא לומדים מעדים זוממים שמקבלים "כאשר זמם." אולי שם לא קוראים לדין שלהם "מלקות," אלא "כאשר זמם." ויש לדון. ע' בפרק שלישי של כתובות, שלא משמע כן.
** עדים זוממים -
ניתרי בהו אימת- עיין שם, שהוכחה זו נדחה. (באמת, לא נאמר בכלל להוכחה לזה, אלא לדבר אחר (שלא מקבלים מלקות), ובין כך ובין כך נדחה.)
* ה.
** ואפי' -
נמצא שרצו לגרום היות חיוב מיתה ליום (לפני כן), ועדיין לא חייבים. אולי זה מפני שאין נפק"מ לאותו יום של חיוב מיתה, שכבר עבר, או שאינם גומרים אלא דין עכשיו.
** בחד גנב... בתרי -
יש שמשנים את הגי'; לכאו', אין שום חילוק גדול, אלא גמ' רק רוצה לשנות קרק' אחד. דנים איזה קרק' נשנה (אם הכל קרה ביחד או באיזה יום קרה גניבה וטביחה). ותו"ת.
* ה:
** מאי דהוה -
נראה שרבי אבהו סובר שחידוש הוא שעדיין לא הורגים את השאר. הרואים יחשבו, אז, שבית דין טעו, ולא רוצים את זה. אולי פשוט שלא הורגים את הנפש לעשות שבית דין נראים כאמיתיים. יותר מכך, אחרי שנהרוג מאה כתי עדים, לא נראים כאומרים אמת.
** כת אחת -
יש לדון מהו החילוק בין הכת האחת לשאר כתים:
1. כת אחת בא קודם שהעידו עדים המזימים.
2. כת אחת הוא רק שני עדים.
יש נפקא מינא גדול, באם כבר באו יותר מכת אחת כשהעידו המזימים. (יש להעיר שלפי צד שני, לכאו' ההבנה הוא שלא מסתבר שהרבה בני אדם היו עם כת המזימים. אם כן, לא תלוי בכמה כתים יש, אלא בכמה עדים יש. אז, כשאומר גמ' שרק הורגים כת אחת, מכוון לומר שרק הורגים שני עדים. אבל, יכול להיות שמזימים כת אחת, אבל יש בו שלש עדים, ולכן אין הורגים אותם. ויש להעיר שאם כן, המשך המשניות, אולי, הוא טוב מאד, שרבי יהודה אומר שרק הורגים את כת אחת, ומבאר משנה שלאחרו שיוצא שאף הם לא תמיד הורגים.)
** חזייה לרבי אלעזר -
ואם תאמר איך לא חש לעשות חן לפני רבו. אין קושיה זו שובר הרים, אבל יש להעיר שלא היה קל לרבי יוחנן לראות, כמו שאומר גמ' בסוף ב"ק ובתענית (ויש להוסיף שלכן לא חש ללכת למקום טבילה).
** כרבי יהודה -
איני מבין בכלל למה נתלה את שניהם זה בזה. ותחשב. אולי הענין הוא שאשה כבר הודה שהיו עמה כתים הרבה, ואז לא מסתבר שעמה היו עוד עדים, וכאילו הודה שאין עדים אלו כשרים. דחוק.
** קל וחומר -
ואם תאמר הרי כבר כתיב "אחיו." ויש לומר שכיון שיש קל וחומר, מסתבר שזה ריבוי לאותו ציור, ולא מיעוט לשאר ציורים.
** ומה שנים -
קצת צריך ביאור איך רבי עקיבא דורש את שני דינים אלו מפסוק אחד. להוסיף על הקושיה, יש להעיר שבכמה מקומות, מניח גמ' שיש מחלקת בדין של רבי עקיבא. לכאו', זה מפני ששאר התנאים דורשים דבר אחר, ואין דורשים שני דברים מקרא זה. אבל, אם רבי עקיבא דורש שני דינים מכאן, קשה מהי"ת שגם הם לא עושים כן. ותחשב. אולי צריך לומר שהוא מפני שתנא מזכיר אותו בשם רבי עקיבא, או מפני שמזכיר את שמם עם דרשה אחר, ולא זה, שהיה להם להזכיר שגם דורשים את זה. יש לדון, שזה לא כל כך שייך למסכתא זו, ולא כל כך קשה למה לא הזכירו אותו. אז, נ' כצד ראשון (שהז' בשם ר"ע). ותחשב.)
** בריבי -
כמובן, במקומות אחרים, רש"י אומר שרצה לומר גדול בדורו. זה מקום מן המקומות שמוכיחים שכשדבר בא הרבה פעמים בש"ס, לא חש לפרש רש"י לומר שני הפירושים שלו בכל מקום, אלא לפעמים אומר כזה ולפעמים אומר כזה. ותחשב על זה.
** אראה -
גמ' הפכו- גם אפשר שריב"ט הפך אותו לטובה.
** על אחת -
עיין בפרק אחרון, ש"רש"י" שם עושה חשבון כמה גדול מדה טובה. יש להעיר שיש לדון למה טוב בא לבני בנים. אולי הוא כיון שזה טוב לאב (שרוצה בטובת זרעו) או אולי יש איזה ירושת זכות. לראשון, יש לומר שבן יותר גדול בזה מבן בן וכדומה, שאדם אוהב את בנו יותר (כיון שהוא בנו, וכיון שיודע אותו). אז, ארבע דורות אינו אחד מחמש מאה מאלפיים דורות. ותחשב על זה.
* ו.
** הרוג יציל -
לכאו', הענין הוא שתורה אומר שלפעמים מתים, ואז צ"ל שלא מציל, ואז צריך לומר שכל הדרשה מוטעה, שאין חילוק. ותחשב.
** יקום דבר -
ע' במש"פ. יש לדון, אז, אם זה כולל הרוג, שאינו עושי הדבר. ותחשב. אולי הוא נתמעט, כמו שנתמעט עושי הדבר. ותחשב.
** הלכה כרבי יוסי -
לכאו', הסיבה לפסוק כרבי הוא שהל' כרבי מחבירו. (יש להעיר שיש דיון- בעיקר גבי הל' כרבי עקיבא מחבירו- אם זה כולל רבו. יש לדון אם רבי יוסי נחשב רבו של רבי. היה באותו דור של רבותיו של רבי, אבל לא נראה שמצאנו שרבי למד ממנו, אלא רק מצאנו שלמד מרבי מאיר ומרבי שמעון. (יש להעיר שאולי היה זמן שלא היו רבי מאיר ורבי שמעון שם. איני יודע, אבל יש להעיר שרבי מאיר נפטר קודם שנפטר רבי יהודה ורבי יוסי, כמו שאומר גמ' בקידושין, וגם היה צריך לנוס (בע"ז, במעשה של ר"ח בן תרדיון), וגם הוציאו אותו מן הישיבה (בסוף הוריות). רבי שמעון היה צריך לצאת כשהיה במערה (בגמ' בשבת[fn:3]). אז, היה זמן גדול שכל אחד לא היה שם. אולי לכן למד משניהם, שלמד מזה כשזה לא היה שם. ותחשב.)) גם יודעים שרבי היה יותר גדול מרבי יוסי (שגמ' אומר שהיה ריב"י ממלא מקום אביו, ורש"י פי' שהוא שהיה גדול כאחיו, והיה כפוף לפני רבי). אבל, לאידך גיסא, היה מודה לרבי יוסי (עיין שם, באותו גמ' שהבאנו משם, ששם רבי מודה לדברי הזקן רבי יוסי). כנראה- ויש לומר את זה לשני הצדדים- יש חילוק כשממש מודה לכשלא ממש מודה. (ויש לדון מה גורם שלפעמים מודה ולפעמים לא מודה. ותחשב על זה. אולי לא ידעו על החולק כאן.)
* Footnotes
[fn:1] אגב, זה לא כל כך מדוייק, שהיה אפשר לדון אם פטור קנס הוא שמניחים שעשה אותו אבל פטור או שלא מאמינים שעשה אותו.
[fn:2] באמת, יש לדון אם רבי חייא אומר כן או מביא בריי'. לשון גמ' לעיל משמע שמביא בריי'. אז, בוודאי אינו קשה. (קצת מוזר שמשנה של רבי יוחנן בן נורי לא מביא אותו שיטה, אבל אינו כ"כ קשה.)
[fn:3] אני כותב מילים אלו בל"ג בעומר, שהוא הזמן הראוי לכתוב אותו, כמובן.
