* חיוב קריאת שמע:
:PROPERTIES:
:CUSTOM_ID: חיוב-קריאת-שמע
:END:
חייב אדם לקרוא קריאת שמע פעמיים ביום -- פעם אחת בשחרית ופעם אחת בערבית.
כיון שמדברים על חיוב לקרוא קריאת שמע, לכאו' צריכים להבין מה הוא "קריאת
שמע.” בפשטות, יש בקריאת שמע שלש פרשיות. הראשון הוא פרשת "שמע,” השני הוא
פרשת "והיה אם שמוע,” והשלישי הוא פרשת "ויאמר.”
** אם החיוב הוא מדאו' או מדרבנן:
:PROPERTIES:
:CUSTOM_ID: אם-החיוב-הוא-מדאו-או-מדרבנן
:END:
מצאנו מחלקת אמוראים בחיוב זה. רב יהודה סובר שחיוב לומר קריאת שמע הוא
חיוב דרבנן. רב אלעזר סובר שחיוב לומר קריאת שמע הוא חיוב דאורייתא. רב
יוסף מקשה על שיטת רב יהודה ממה שנאמר, “ובשכבך ובקומך,” ואביי משיב לשיטת
רב יהודה שזה נאמר בדברי תורה[fn:1].[fn:2][fn:3]
*** ביאור לימוד מ"בשכבך ובקומך":
:PROPERTIES:
:CUSTOM_ID: ביאור-לימוד-מבשכבך-ובקומך
:END:
קצת יש לדון איפה רואים מ"בשכבך ובקומך" שחייב אדם לקרוא קריאת שמע
מדאורייתא. נראה שיש שני דרכים פשוטים. דרך הראשון הוא שלא מכוון לאותו קטע
של הפסוק, אלא מכוון לכל הפסוק. הפסוק אומר, “ושננתם לבניך ודברת בם בשבתך
בביתך ובלכתך בדרך ובשכבך ובקומך.” אולי מ"ודברת בם" דורשים שאדם צריך לדבר
בדברים אלו, שהוא קריאת שמע. אבל, אז קצת קשה למה הקשה מ"ובשכך
ובקומך.”[fn:4] דרך השני הוא לומר שמכוון לאותו קטע של הפסוק. אפשר ש"ודברת
בם" מדבר בדברי תורה, אבל לא מסתבר שדברי תורה הם "בשכבך ובקומך.”[fn:5]
אז, צריך לומר ש"בשכבך ובקומך" הולך על דבר אחר, ומצווה דבר אחר, והוא
קריאת שמע. כיון שהגענו לזה, יש לומר כצד ראשון, ולומר שמביא "בשכבך
ובקומך" כיון שזה מוכיח שהפסוק מדבר על קריאת שמע, ולא על דברי תורה.
ותחשב.
*** פירוש המחלקת אם ק"ש מדאו' או מדרבנן:
:PROPERTIES:
:CUSTOM_ID: פירוש-המחלקת-אם-קש-מדאו-או-מדרבנן
:END:
הפירוש הפשוט של המחלקת הוא שרב יהודה סובר שאין שום חלק מקריאת שמע שיש לו
חיוב דאורייתא. רב אלעזר סובר שיש חלק מקריאת שמע שיש לו חיוב מדאו'. עיין
לקמן בגמ', שידון איזה חלקים מקריאת שמע צריך אדם לומר. לפי מה שכתבנו,
הדיון יהיה ברב אלעזר. (קצת קשה, שהרי חולקים תנאים בזה. צריך לומר שלפי רב
יהודה, חולקים מה תקנו חכמים לומר.) אבל, אינו מוכרח כן, שיש לומר שחולקים
רב אלעזר ורב יהודה במי שכבר אמר חלק (ויש לדון איזה חלק) מקריאת שמע, אם
השאר הוא מדאו' או מדרבנן.[fn:6]
** מקורות:
:PROPERTIES:
:CUSTOM_ID: מקורות
:END:
כיון שהחיוב הוא לומר שלש פרשיות שונות, בהשקפה ראשונה לא נאמר שיש חיוב
אחד לומר "קריאת שמע,” אלא שיש שלש חיובים -- חיוב לומר פרשה ראשונה, חיוב
לומר פרשה שנית, וחיוב לומר פרשה שלישית.[fn:7] אז, נצטרך לדון למקור לכל
אחד ואחד. נחלק את קריאת שמע לשני חלקים -- פרשה ראשונה ושניה ופרשה
שלישית.
** מהו החיוב:
:PROPERTIES:
:CUSTOM_ID: מהו-החיוב
:END:
קודם שנראה את השיטות, צריכים לבאר שלא רק צריכים לדון על מה חל החיוב, אלא
גם מהו החיוב, ואיזה מין אמירה צריכים. נראה שיכול להיות חמש דרכי דיבור --
צריך לדבר אותו בפה עד שמשמיע אותו לאזנים, צריך לדבר אותו בפה עד שמוציא
קול, צריך לדבר אותו בפה, צריך לומר אותו במחשבה, צריך לחשוב על הענינים
שלו. כשנדון לקמן, צריכים לחשוב על ענייינים אלו.
*** ביאור בפרשה ראשונה ושניה:
:PROPERTIES:
:CUSTOM_ID: ביאור-בפרשה-ראשונה-ושניה
:END:
*** כמה צריך לומר:
:PROPERTIES:
:CUSTOM_ID: כמה-צריך-לומר
:END:
מצאנו שלש שיטות מפורשות בבמה צריך לומר. רבי אומר שצריך לומר פסוק ראשון
של קריאת שמע. רבי יאשיה אומר שצירך לומר פרק ראשון של קריאת שמע. אבל,
פרשה שניה צריך להיות במחשבה. אז, לכאו', פרשה שניה צריכה להיות במין דיבור
הרביעי או החמישי. (אבל, יש לדחות שמחשבה רק אומר שאם בוחר לומר אותו, צירך
לכוון בו, שבזיון הוא לומר אותו בלי כוונה.) רבי זוטרא אומר שצריך לומר שני
פרקים ראשונים של קריאת שמע. לכאו', כיון שמה שגמ' אומר שלא נחשב דיבור הוא
מין דיבור רביעי או חמישי, צריך להיות שכשאומר שצריך דיבור הוא צד אחד ממין
שלישי ולמעלה או ממין רביעי ולמעלה.
נראה לי שיש עוד שיטות. נראה שרבי אליעזר (ואפשר שגם רבי יאשיה סובר כן)
סובר שרק צריך לקרוא עד פסוק רביעית. עיין שם בגמרא, שיש להסתפק אם צריך
לקרוא את כל הפסוק הרביעית או רק עד מילת "האלה.” (צד שני קשה להבין, שזה
אמצע דיבור. אפשר להיות שיקרא עד סוף הדיבור, ואולי זה קודם גמר הפסוק,
ונראה שיהיה אחרי "על לבבך.”)
*** המקורות:
:PROPERTIES:
:CUSTOM_ID: המקורות
:END:
**** מקור של רבי:
:PROPERTIES:
:CUSTOM_ID: מקור-של-רבי
:END:
איני יודע מהו המקור של רבי. נראה שיש ארבע דרכים. דרך ראשון הוא שכשאומר,
“והיו הדברים האלה... ודברת בם" יודעים שמכוון לפסוק ראשון. השני הוא
שכשאומר, “בשכבך ובקומך" יודעים שמכוון לפסוק ראשון. (אולי זה מפני שרק
מסתבר שצריך לומר זה, או אולי לא דורש ש"האלה" ממעט, וזה המקום הכי מסתבר
לו לחלק.) השלישי הוא שלשון הפסוק של "שמע ישראל" משמע שצריך כל אחד לומר
אותו ולהשמיע אותו[fn:8], שאם אין חיוב לומר אותו, איך ישמעו לו כל בני
ישראל. דרך הרביעי הוא שזה רק חיוב מדרבנן. אולי כיון שהוא עיקר האמונה,
קבעו לו רבנן חיוב.
**** מקור לרבי יאשיה:
:PROPERTIES:
:CUSTOM_ID: מקור-לרבי-יאשיה
:END:
מקור לשיטת רבי יאשיה הוא שבפרק ראשון אומר, “ודברת בם.” זה מלמד לנו
שצריכים לקרוא את הפרשה; ההנחה של הגמ' הוא שכשהפסוק אומר לדבר "בם,” מכוון
לכל הפרשה. אבל, לא דורשים כן מ"לדבר בם" של פרשה שנית, שמניחים שזה הולך
על דברי תורה. (וא"ת מה נשתנה פרשה שנית מפרשה ראשונה. מן הגמרא משמע שיוצא
מן החילוק בין לשון "ודברת בם" ללשון "לדבר בם." גם יש לומר שפרשה ראשונה
מדבר באהבת ה' ועיקרי אמונה, ומסתבר שיצטרך לומר כן. אבל, לא מסתבר שיצטרך
לומר פרשה שנית. יש להצטרף עם זה שאולי מסתבר שיש חיוב ללמוד. יותר מסתבר
לדרוש כן מפרשה שנית, כיון שלא כל כך מסתבר שיתחייב לקרוא אותו. ותחשב.)
המקור שצריך מחשבה על פרשה שנית הוא שאומר, “על לבבך.” כנראה, אף ש"לדבר
בם" הולך על דברי תורה, “על לבבך" הולך על הפרשה. מסתבר שהוא מפני שכיון
שדורש ש"ודברת בם" הולך על דברי תורה, לא צריך לומר שיכוון, שפשוט שענין של
לימוד תורה הוא לימוד, ובוודאי צריך כוונה כשלומד. אז, צריך לומר שהולך על
אותה הפרשה. (יותר קל לבאר לפי צד שני שהבאנו למטה בביאור הצד שהולך על
דברי תורה.)
**** מקור לרבי זוטרא:
:PROPERTIES:
:CUSTOM_ID: מקור-לרבי-זוטרא
:END:
מקור לשיטת רבי זוטרא הוא שאומר “ודברת בם" בפרשה ראשונה, ואומר "לדבר בם"
בפרשה שנית. הראשון אומר שצריך לקרוא פרשה ראשונה, והשנית אומר שצריך לקרוא
פרשה שנית.[fn:9]
**** מקור לרבי אליעזר:
:PROPERTIES:
:CUSTOM_ID: מקור-לרבי-אליעזר
:END:
מקור לשיטת רבי אליעזר הוא שאומר, “ודברת בם,” ואומר, “הדברים האלה.” זה
ממעט דברים אחרים; מה שממעט הוא המילים משם עד הסוף.
*** דאו' או דרבנן:
:PROPERTIES:
:CUSTOM_ID: דאו-או-דרבנן
:END:
יש משיטות אלו שהם בוודאי מזכירים את הדין דאורייתא. אז, לא יודעים אם רבנן
הוסיפו על זה חיוב. ותחשב. יודעים שרבי היה נוהג לומר רק פסוק ראשון בזמן
קריאת שמע. חולקים אמוראים אם היה אומר את השאר (יש לדון מהו בכלל השאר)
אחרי כן. אבל, זה היה מפני שהיה מוסר שיעור לרבים, ואז היה דחוף. ותחשב.
נמצא שלפי שיטה אחת, רבי סובר שיש שתי דרגות של חיוב. יש לדון אם אחד מדאו'
ואחד מדרבנן, או שניהם מדאו' (ויש לדון מהו המקור לחלק) או שניהם מדרבנן
(ואז אולי חלקו רבנן בין דין היותר נצרך לדין אחר).
** איזה מין דיבור צריכים:
:PROPERTIES:
:CUSTOM_ID: איזה-מין-דיבור-צריכים
:END:
חולקים אמוראים אם הרהור כדיבור או לא. צריכים לדון מהו הירהור, שנראה
שיכול להיות כצד שלישית ולמטה. כדי להיות טוב עם צד אחד שכתבנו לעיל, צריך
להיות כצד שלישי או אולי כרביעי. גם אפשר שדיבור של רבי יאשיה לא שווה
לדיבור של שאר שיטות.
רבי יוסי ורבי סוברים שצריך מין ראשון של דיבור, כיון שכתיב, “שמע.” אבל,
רבי יהודה ורבי מאיר חולקים, וסוברים ש"שמע" רק אומר שיכול לקרוא בכל לשון.
הלכה כרבי מאיר ורבי יהודה. אבל, לכתחילה, צריך לעשות כמין ראשון. (איני
יודע מהו המקור לזה, שלא יכול להיות "שמע,” שדורשים מזה כבר דבר אחר, כמו
שבארנו, ועוד שאז יעכב. דין זה נוהג בכל המצוות, כמו שאומר הגמ' שם, ואיני
יודע המקור לו גם במקומות אחרים.) אז, יוצא שהדיבור שצריך אינו מין ראשון.
** פרשה שלישית:
:PROPERTIES:
:CUSTOM_ID: פרשה-שלישית
:END:
יש עוד חיוב, והוא להזכיר יציאת מצרים. כדי לעשות כן, קורא אדם פרשה שלישית
של קריאת שמע. גמרא מבאר שמפני ששה דברים קבעו פרשה שלישית בקריאת שמע:
מפני שיש בה מצוות ציצית, מפני שיש בה יציאת מצרים, ממפני שיש בה עול
מצוות, מפני שיש בה דעת מינים, מפני שיש בה הרהור עבירה, ומפני שיש בה
הרהור עבודה זרה.[fn:10] (יש לדון אם דברים אלו הם סיבה שיאמר אותו, או שהם
סיבה לומר אותו עם קריאת שמע, וזה הסיבה שצריך לומר אותו (אגב קריאת שמע).)
לכאו', רואים מזה שפרשה שלישית הוא חיוב דרבנן. מדאו', רק חייב להזכיר
יציאת מצרים, ורבנן קבעו לומר אותו בתוך פרשה שלישית של קריאת שמע. אבל, לא
מוכרח כן, שיש לומר שיש חיוב לומר פרשה שלישית של קריאת שמע, ורק אין חיוב
לומר אותו לפרשה שלישית של קריאת שמע, אלא יכול לומר אותו בפני עצמו. רבנן
קבעו לומר אותו עם קריאת שמע. (אז, דברים אלו צריכים להיות סיבות לייחס
אותו לקריאת שמע.אבל, איני יודע מקור שיאמר אותו בפני עצמו, ואז לא נראה
כצד זה. (שוב נראה לי שאפשר שהוא מפני המקור לחיוב זכירת יצ"מ. הפסוק אומר
"למען תזכור." כיון שלא אומר לזכור, אלא "למען תזכור," אולי משמע שמדבר על
מעשה פרטי, ואז אפשר שמסתבר שהוא פרשה שלישית של קריאת שמע. אפשר להוסיף
שאולי לפי זה גם אפשר לומר שגמ' מנסה לבאר למה היה נראה לרבנן שזהו הדבר
הפרטי שלו מכוון התורה. אבל, אין הלשון משמע כן.) כן נראה ממה שלא תמיד
צריך לומר אותו, כמו שנבאר בע"ה.
*** פרשה שלישית בלילה:
:PROPERTIES:
:CUSTOM_ID: פרשה-שלישית-בלילה
:END:
גמרא אומר שבלילה לא צריך לומר פרשה שלישית של קריאת שמע. חולקים מה יאמר.
אמוראי בבל אומר שלא צריך לומר אותו כלל. אמוראי א"י אומר שצריך
לומר[fn:11] פרשה שלישית של קריאת שמע באופן אחר; יאמר "ויאמר... דבר אל
בני ישראל אני ה' אלקיכם אמת.”[fn:12]
*** הזכרת יציאת מצרים בלילה:
:PROPERTIES:
:CUSTOM_ID: הזכרת-יציאת-מצרים-בלילה
:END:
כמו שהזכרנו בהגדה, חולקים תנאים אם צריך אדם להזכיר יציאת מצרים בלילות או
לא צריך להזכיר. מן הגמרא יוצא שאף אם צריך להזכיר יציאת מצרים בלילות, לא
צריך לומר פרשה שלישית, ששם מקשה איך יזכיר יציאת מצרים כיון שלא צריך לומר
פרשה שלישית. (אפשר לדחות שמדבר בחיוב דרבנן להזכיר יציאת מצרים, שאולי
רבנן מודים שצריך להזכיר אותו מדרבנן. לא משמע כן מקושיית הגמרא בפשיטות,
ולא משמע שרבנן סוברים שיש חיוב דרבנן להזכיר יציאת מצרים, ממה שאומר
ראב"ע, “לא זכיתי שתיאמר יציאת מצרים בלילות.”) הסיבה שלא צריך לומר פרשה
שלישית הוא שאין מצוות ציצית נוהגת בלילות. (אף שיש עוד ארבע דברים שנוהג,
צריך לומר שאין אלו עושים, בפני עצמם, חיוב לומר פרשה שלישית של קריאת
שמע.)
*** דיני פרשה שלישית:
:PROPERTIES:
:CUSTOM_ID: דיני-פרשה-שלישית
:END:
יש להעיר שיש הרבה דינים שנוהגים בהזכרת יציאת מצרים, כמו הזמן שלו, שהם
שווים לפרשה ראשונה. אולי זה נוהג מדדרבנן, אבל אם נאמר שנוהג מדאו' אין
המקור להם פשוט. ותחשב. אפשר שרק נוהגים בו מדרבנן.
** כולם חיוב אחד:
:PROPERTIES:
:CUSTOM_ID: כולם-חיוב-אחד
:END:
יש סיבה לחשוב שיש יחס בין חלקי קריאת שמע. אסור להפסיק בין החלקים, ומזה
משמע שיש יחס ביניהם. (אבל, אפשר לדחות שעיקר הסיבה שאין להפסיק הוא שאז
מפסיק בין קריאת שמע לברכות קריאת שמע, ולא מפני שמפסיק בין חלקי קריאת
שמע. ותחשב.) אולי זה רק מפני שרבנן קבעו לומר אותם זה אתל זה, כיון שהם
דומים. אבל, גם אפשר לומר שהם בעצם אחד, ואז אפשר לומר שהמקור לומר "דברים
האלה" הולך על כולם. וא"ת אם כן יאמר אותם גם בלילה. ויש לומר שקריאת שמע
בלילה לא כולל פרשה שלישית, שהוא רק בכלל אם הוא שייך. ותחשב. אבל, המקורות
שהבאנו לעיל לא משמע כן. אבל, יש הרבה שיטות, ואז אפשר להיות כן.
* שאלת הראשונים:
:PROPERTIES:
:CUSTOM_ID: שאלת-הראשונים
:END:
כמו שבארנו, יש חיוב לקרוא קריאת שמע בערב, בזמן שכיבה, כמו שאומר הפסוק,
"בשכבך." המשנה מבארת תחילת אותו הזמן- הוא צאת הכוכבים. רש"י ותוס' מבארים
איך המנהג שנהגו בימיהם מתאים עם דין הנשנה במשנה.
** המנהג בימי הראשונים:
:PROPERTIES:
:CUSTOM_ID: המנהג-בימי-הראשונים
:END:
נהגו להתפלל ערבית קודם צאת הכוכבים. נמצא שברכו ברכות קריאת שמע, ואמרו
קריאת שמע, ואף התפללו, קודם זמן צאת הכוכבים. כשהלכו לישון, אמרו פרק
ראשון של קריאת שמע על המטה, ולא ברכו עליו ברכות קריאת שמע.
** הירושלמי:
:PROPERTIES:
:CUSTOM_ID: הירושלמי
:END:
ירושלמי מביא את הדין של המשנה, ומקשה למה אנו קוראים את קריאת שמע[fn:13]
בבית הכנסת (כיון שהוא קודם זמן שלה). משיב שהוא כדי לעמוד בתפילה מתוך
דברי תורה.
יש להעיר שאז, לכאו', היה אפשר לקרוא איזה חלק מן התורה שרוצה. אלא, לאיזה
סיבה, תקנו (או נהגו) לקרוא קריאת שמע. אולי הוא כדי להזכיר לבני אדם לקרוא
לאחר זמן, או אולי הוא מפני שככה עושים בזמן שמקיים את המצווה (אם מתפלל
מאוחר). (יש להעיר שקצת מעניין שלא חששו לבני אדם שיחשבו שכבר יצאו.)
** שיטת רש"י:
:PROPERTIES:
:CUSTOM_ID: שיטת-רשי
:END:
*** איך יוצאים:
:PROPERTIES:
:CUSTOM_ID: איך-יוצאים
:END:
רש"י אומר שלא יוצאים בקריאת שמע שאומרים בערבית כיון שהוא קודם הזמן (שהוא
קודם צאת הכוכבים). אלא, יוצאים בקריאת שמע שעל המטה, שהוא אחרי צאת
הכוכבים.
*** למה קוראים קריאת שמע בתפילת ערבית:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-בתפילת-ערבית
:END:
רש”י מפרש על פי ירושלמי שקוראים אותו בבית הכנסת בתפילת ערבית כדי לעמוד
בתפלה מתוך דברי תורה. אז, יש סיבה לקרוא קריאת שמע אף שלא יוצא בזה חיוב
קריאת שמע.
*** למה קוראים קריאת שמע שעל המטה:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-שעל-המטה
:END:
רש”י מפרש שקוראים אותו בקריאת שמע שעל המטה לשתי סיבות.
ראשון, יש חיוב לקרוא את קריאת שמע שעל המטה מחמת מה שאומר הגמ' לקמן (ד:,
ה.). שם, אומר שמצווה[fn:14] לקרוא קריאת שמע שעל המטה. (עיין שם בגמ', שגם
מדבר בשמירה שבאה מאותו קריאת שמע. יש לדון אם זה סיבת המצווה או שיש סיבה
אחרת.) אבל, גמ' מפרש שאין זה תמיד מצווה, ותלמיד חכם רק צריך לומר פסוק של
רחמים.
שני, יש חיוב לקרוא קריאת שמע של ערבית (שקריאת שמע שקרא בתפילת ערבית היה
מוקדם).
** קושיות תוס':
:PROPERTIES:
:CUSTOM_ID: קושיות-תוס
:END:
תוס' מקשה ארבע קושיות על שיטת רש"י.[fn:15]
*** קושיא ראשונה:
:PROPERTIES:
:CUSTOM_ID: קושיא-ראשונה
:END:
מקשה תוס' שסמוך למטה רק נהגו לקרוא פרשה ראשונה. הרי, חיוב לקרוא קריאת
שמע הוא לקרוא שלש פרשיות של קריאת שמע, ולא יכולים לצאת בפרשה ראשונה.
רש"י מזכיר נקודה זו, ולא משיב עליו; כנראה, רש”י לא סובר שזה קשה[fn:16].
יש לדון למה יוצא בו:
1. אין חיוב לקרוא שאר הפרשיות. לכאו', קשה לומר כן, שהפסוק אומר בפירוש
לקרוא פרשה שנית "בשכבך," וגם המשנה אומר שהוא נוהג בלילה. אבל, צריך
לע' בגמ' לקמן, שמצדד שאולי יש חיוב לקרוא רק ראשון.
2. יצא כבר בקריאת שאר הפרשיות. יש שני צדדים בזה:
   1. יצא כיון שקרא אותם. הביאור יהיה ששאר הפרשיות לא חייבות להיות אחרי
צאת הכוכבים. לא פשוט למה נחשוב כן; נראה שהביאור יכול להיות שזמנו
לילה רק מן הסברה (שבפרשה רק כתיב שצריך להיות בזמן שכיבה), שכיון
שזמנו נאמר שהוא זמן שכיבה, מסתבר שכוונת התורה לתלות אותה בלילה.
אולי זה רק מסתבר בפרשה ראשונה, ולא בפרשה שנית. צריך ביאור למה יהיה
כן.
   2. יצא כיון שקרא אותם, וקרא פרשה ראשונה אחרי צאת הכוכבים. הביאור יהיה
שכיון שכולם מיוחסים ללילה -- שקרא את הראשון אז, וכולם מיוחסים
לראשון -- יוצא מצוות קריאת שמע
(יש להעיר שלכאו', יש הפסק ביניהם מחמת זה. כמו כן, יש לדון אם ייפסל כיון
שאינו כסדר.)
יש להעיר שלפי צד זה אין קושיית הירושלמי מובן כל כך, שהרי קורא קריאת שמע
אז כיון שיוצא בשנים מן הפרשיות. אפשר שמקשה למה לא רק דולג אותו, ויקרא
השנית והשלישית עם הראשונה. גם אפשר שמקשה למה קורא את הראשונה אז. ותחשב.
עיין בלשון רש”י שמשמע כצד ראשון, שאומר ש"בקריאת פרשה ראשונה... יצא."
לכאו', נאמר שכל צדדים אלו מחודשים, ושכולם צריכים ביאור -- מהיכי תיתי
לרש"י שיכולים לצאת בזה. אבל, כשנחשוב, נבין שאין זה כל כך קשה, שרש"י יאמר
שהמקור שלו הוא הירושלמי. (יש לדון מהיכי תיתי שבזמן הירושלמי רק קראו פרשה
ראשונה אחרי התפילה.) לא קשה מהו המקור של הירושלמי כיון שאמוראים הם,
ויכולים לחדש דינים כזה.
*** קושיה שנית:
:PROPERTIES:
:CUSTOM_ID: קושיה-שנית
:END:
מקשה תוס' שצריך לברך ברכות קריאת שמע. לכאו', יש בזה שני קושיות (ונראה
שתוס' לא המשיך לבאר את הקושיה כדי לכלול את שתי הקושיות):
1. נוהגים לקרוא אותו בתפילת ערבית עם ברכות. אם לא יוצא בזה מצוות קריאת
שמע, קשה איך יברך עליו.
2. לא נוהגים לברך עליו כשקורא עליו על המטה. אם יוצאים בזה מצוות קריאת
שמע, קשה איך לא יברך עליו.
נבאר איך לתרץ את שניהם.
נבאר איך לתרץ את הראשון:
1. אפשר שרש"י סובר שיכולים לברך עליו אף אם לא מקיים בו מצוות קריאת שמע.
(לכאו', יש לדון אם ברכות קריאת שמע הם ברכות מצווה או סוג אחר של ברכה.
מה שכתבנו יותר קל לצד שני. נראה שאפשר גם לצד ראשון, ונאמר שמקיים מעין
של המצווה. (מסתבר לומר כן, שמס' שטעם של המצווה הוא לזכור יסודות של
האמונה. אף שמצווה הוא בפרט לזכור אותם בזמנים פרטיים, גם מקיים מקצת
אותו הענין כשמזכיר אותו בשאר מנים, מפני שטוב לזכור אותו אז, ומפני
שגורם קצת זכירה באותם זמנים פרטיים.)
לכאו', יש הוכחה לזה ממה שיכולים לברך ברכות קריאת שמע אם קורא אותו אחרי
שלש שעות. (גמ' לקמן אומר שכשאומר המשנה שאם מאחר לקרוא אותו מפסיד את
הברכות.) אבל, אולי יש לחלק בין קודם זמנו ללאחר זמנו. ותחשב. (אפשר שיש
חילוק כמה אפשר לקיים אותו, ואפשר שיש חילוק בין אם מקיים בו איזה ענין
תשלומים. יותר מזה, שם זהו הקיום, ואין קיום אחר. אבל, כאן, יש קיום אחר.
ויש לדון, שבשעה שמברך אין קיום אחר.)
בפשטות, יכולים לברך עליו בלי יציאת המצווה כיון שיש קצת קיום. אבל, אפשר
לומר שבלי שום קיום יכולים לברך עליו. אולי כיון שקבעו רבנן לברך באמצע
תפילת ערבית, כיון שנהגו לקרוא קריאת שמע של חובה אז, המצווה הוא תמיד לברך
אז, אף בלי צורך. יש לדון למה לא נאמר שמחמת זה צריך להתפלל לאחר צאת
הכוכבים, כדי שלא יהיה ברכתו לבטלה. ויש לדון. ותחשב.
2. [@2] אפשר שרש"י סובר שיש קיום. עיין לעיל, שבארנו שני צדדים בזה (שאולי
מקיים בזה מצוות קריאת פרשה שנית ושלשית[fn:17]).
נבאר איך לתרץ את השני:
1. אולי בברכות שלפני כן יוצא. זה יותר קל לומר אם נאמר שכבר קיים מצווה
(או מקצת מצווה). אבל, אולי אף בלי זה, אולי כיון שברך עם קריאת שמע שלא
יוצא בו, ייחס את הברכות לקריאת שמע. ותחשב על זה.
2. אולי לא צריך ברכות. יכול להיות שלש סיבות לזה:
   1. כיון שכבר קרא אותו (וכבר קיים מקצת המצווה).
   2. כיון שקורא אותו על המטה. (אולי אפשר לומר שגזי' הוא שמא יחשוב
שהברכה הוא מחמת המצווה של קריאת שמע שעל המטה, ואז יברך עליו אף אם
כבר קרא קריאת שמע.) נראה שיש שני דרכים לומר צד זה:
      1. כיון שהוא על המטה.
      2. כיון שאינו באמצע תפילה. (אולי אפשר לחדש שעיקר ענין של הברכות הם
לעשות גשר בין קריאת שמע לתפלה. וא"ת א"כ למה יברך לפני ק"ש. ויש
לדון, שבכ"מ צריך הכנה לגשר, דהיינו שצריך הקדמה לדבר כדי להכשיר
אותו להיות שייך לדבר אחר. ותחשב.
   3. כיון שרק קורא פרשה ראשונה.
וא"ת מהיכי תיתי שלא מברכים עליו כשקראו אותו על המטה. באמת, יש שני קושיות
כאן. קושיה ראשונה היא עלי -- למה אני מניח שזהו המציאות, ומניח שכך מקשה
תוס'. נראה שמה שאומר רש"י -- שיוצאים בקריאת שמע שעל המטה -- יהיה פשוט
ביותר אם נאמר שמברכים עליו. קושיה השנית הוא על רש"י ותוס' -- למה מניחים
שלא מברכים על קריאת שמע שעל המטה. זה לא קשה בכלל, שרש"י ותוס' דנים במנהג
שהיה בימיהם, וכך היה נהוג בימיהם -- לא ברכו על קריאת שמע שעל המטה.
*** קושיה שלישית:
:PROPERTIES:
:CUSTOM_ID: קושיה-שלישית
:END:
מקשה תוס' שהגמ' אומר שקריאת שמע שעל המטה הוא רק בשביל המזיקים. המקור לזה
הוא שאם תלמיד חכם הוא, לא צריך לקרוא קריאת שמע.
אגב, יש להעיר שלא פשוט שהוא רק בשביל המזיקים. נכון הוא שגמ' יאמר שהוא
מציל מן המזיקין, אבל לא מוכרח שזה הסיבה שקוראים אותו. אבל, תוס' לא צריך
נקודה זו כדי להקשות; מה שהוא הסיבה, אינה יכולה להיות חיוב קריאת שמע של
ערבית, שהרי אינה מחייבת את תלמידי חכמים. ותחשב.
לכאו', יש דרך פשוט לדחות את קושיית תוס'. אולי הגמ' רק מסביר מה צריך
לקרוא לקריאת שמע שעל המטה. אבל, אם הוא גם קורא אותו לסיבה אחרת, שצריך
לקיים בו את קריאת שמע שבערבית, אז צריך לקרוא את שלש הפרשיות. אז, לא קשה
לתרץ את קושיית תוס'.
לכאו', תוס' סבר שלא מסתבר לפרש את הגמ' כן. הרי, יודעים שבזמן הגמרא היו
מתפללים קודם צאת הכוכבים. יודעים כן מן הירושלמי שהזכרנו לעיל. כיון שהוא
כן, לא היה לו לגמ' להזכיר מה צריך לומר בקריאת שמע שעל המטה, כיון שנהגו
לקיים את קריאת שמע של ערבית אז. ויש לדון.
רש”י יאמר שאף שבדר"כ אדם יוצא ק"ש של ערבית אז, לא קשה שידבר על חיוב ק"ש
שעל המטה בלחוד, אף שלא מקיים אותו בפנ"ע. ותחשב. גם אפשר שרש”י יאמר שאולי
לא נהגו בבבל כן. בא"י נוהגים כן -- זהו מה שרואים מן הירושלמי -- אבל בבבל
אולי לא נהגו כן. ותחשב. (יש להעיר שבבריי' שמביא גמ' (ד:)משמע שהיו סומכים
גאולה לתפילה. כמו כן, ממה שחלקו רבי יוחנן וריב"ל בסמיכת גאולה לתפילה,
משמע שזה נוהג. אז, צריך לומר שלא תמיד היו נוהגים כמנהג הראשונים.)
*** קושיה רביעית:
:PROPERTIES:
:CUSTOM_ID: קושיה-רביעית
:END:
חולקים אמוראים אם תפילות באמצע קריאות שמע או תמיד אחרי קריאת שמע. במילים
אחרים, חולקים אם להתפלל תפילת שמונה עשרה של ערבית אחרי קריאת שמע של
ערבית או קודם קריאת שמע של ערבית. תוס' מניח שהלכה כרבי יוחנן, שאומר
שמתפללים אחרי קריאת שמע. (לכאו', המקור לזה הוא שכן נוהגים כשמתפלל אחרי
צאת הכוכבים. גם יכול להיות כיון שגמ' לקמן (ד:) יאמר שבריי' שמובא שם
מסייע לו.[fn:18])
הרי, לפי רש”י נמצא שמתפלל תפילת שמונה עשרה של ערבית לפני קריאת שמע, שהרי
לא יוצאים בק"ש שאומרים לפני שמונה עשרה. אז, קשה, שלהל' צריך להתפלל אחרי
קריאת שמע. (יש להעיר שזה לא קשה על מנהג שלנו בלבד; יודעים מגמ' לקמן
(שיביא תוס') שיכולים להתפלל קודם צאת הכוכבים, וצריך להיות אופן שבו יכול
לקיים ענין של תפילה אחרי קריאת שמע. אבל, עיין לקמן בתוס', שייצא תי'
לזה.)
אפשר לומר שכיון שקורא את קריאת שמע, אף שלא מקיים בזה את מצוותו, יכול
להתפלל אחריו[fn:19]. אבל, לא נראה כן מן הירושלמי, ששואל למה קוראים קריאת
שמע, ואומר שהוא לבוא לתפילה מתוך דברי תורה, ולא שהוא כדי להתפלל אחרי
קריאת שמע. (דחוק מאד לומר שמכוון לומר שהוא כדי להתפלל אחרי קריאת שמע.)
אפשר לומר שרש”י סובר שירושלמי סובר שמתפללים לפני קריאת שמע, ולכן צריך
למצוא סיבה. אבל, לנו, שפוסקים להתפלל אחרי קריאת שמע, לא קשה קושיית
הירושלמי, והסיבה שאומרים קריאת שמע הוא כדי שנתפלל אחר מכן. לא נראה כן
מכמה טעמים. דבר ראשון, אז רש”י עושה ירושלמי נגד הלכה בלי שום מקור. דבר
שני, הרי בריי' הוא בירושלמי, ולא מסתבר לעשות אותו נגד אמורא שכמותו
פוסקים, שלא נפסוק כמותו כיון שחולק על בריי'. דבר שלישי, הרי רש”י מביא את
הירושלמי, ומשמע שמפרש לדין כן, ואז צריך לומר שלא סובר לתלות אותו על
מחלקת אמוראים שלעיל.
אפשר לומר שחיוב להתפלל רק אחרי קריאת שמע לא מחייב אדם להטריח ולשהות את
תפלתו.[fn:20] רק אם הוא נמצא בשעה שיכול לומר קריאת שמע ותפלה, ודן איזה
מהם יקדם, חייב הוא להקדים את קריאת שמע. אבל, לא חייב להתפלל בזמן שיוכל
להקדים את ק"ש לתפלה. ותחשב.
** שיטת רבינו תם:
:PROPERTIES:
:CUSTOM_ID: שיטת-רבינו-תם
:END:
*** איך יוצאים:
:PROPERTIES:
:CUSTOM_ID: איך-יוצאים-1
:END:
רבינו תם אומר שיוצאים בקריאת שמע שקוראים בתפילת ערבית, אף שקוראים אותו
קודם צאת הכוכבים.
[fn:21]חולקים רבי יהודה ורבנן בזמן של תפילת המנחה. רבנן אומרים שהוא עד
הערב (לכאו', זה עד צאת הכוכבים), ורבי יהודה אומר שהוא עד פלג המנחה (גמ'
מבאר שהוא זמן שנשאר ליום שעה ורבע).
תוס' מניח שלפי רבי יהודה גם יכולים לקרוא קריאת שמע אז.[fn:22] לכאו',
צריך לומר שמחלקת בין רבי יהודה ורבנן אינו רק לענין זמן של תפילת מנחה,
אלא זמן לילה, ושזמן קריאת שמע תלוי בזמן לילה (עיין לעיל, שכתבנו צדדים
בזה). (אפשר לומר שדין של רבי יהודה הוא שזמן מנחה הוא עד הלילה, ושפלג
המנחה הוא לילה, או שזמנו הוא עד פלג המנחה, אבל מס' היינו ממשיכים אותו
לכל שאר היום, עד הלילה. לא נראה כצד שני, שלא ממשיכים זמן של שאר התפילות.
ותחשב. גם אפשר לומר שזה לא סימן, אלא סיבה. כיון שבא לו כבר דינים של לילה
(ונאמר שמה שלא יכול להתפלל בו תפילת מנחה הוא דין של לילה, כיון שהוא נוהג
כל הלילה גם כן), בא לו עד דינים של לילה. זה מחודש, שדין מנחה הוא רק דין
דרבנן. ותחשב. אבל, אפשר לתלות אותו בהקרבת קרבן תמיד או בקיום תפילת מנחה
(שלכאו' היה קיום כיון שיצחק תיקן אותו). ותחשב.) נראה שיש עוד צד (ואולי
זה יבאר ענינים אחרים), והוא שזמן שכיבה אינו זמן שבני אדם שוכבים, אלא
שבדרך שהעולם נעשה, יש זמן של שינה. לכל זמן ועת, ולילה היא עת של שינה.
(יש גמרא שמשמע כן; צריך לעיין.) אז, יש לומר שכיון שחולקים מהו לילה,
ממילא חולקים מהו זמן שכיבה, כיון שלילה הוא זמן שכיבה -- לילה הוא זמן
שראוי לשכוב בו. ותחשב.[fn:23]
צריכים לדון לענין איזה דברים נחשב לילה. יש דברים שתולה תורה בביאת שמש,
כמו טבול יום, ולא מסתבר שהם תלויים בפלג המנחה, שלא נראה שזה ייקרא ביאת
שמש. גם לענין פלג עצמו, צריך לדון בשעות היום של צאה"כ או שקיעה, ולא
בשעות של יום שגומר בפלג המנחה. אז, לא פשוט לאיזה דבדרים מחשיבים את פלג
המנחה להיות גמר היום. ותחשב.
יש להעיר שאם כן רבי יהודה חולק על משנה שלנו. אף שמשנה שלנו אולי (עיין
בתחילת ג.) סתם משנה, יהיה סתם ואח"כ מחלקת, ולא צריכים לפסוק כסתם. אז,
יכולים לנהוג כרבי יהודה.
מעניין שחידוש גדול זה -- שקריאת שמע תלוי בסוף זמן מנחה -- לא מוזכר
בתוס'; פשוט שמניח כן, אבל קשה שלא יאמר אותו בפירוש, ולא יסביר למה ומהיכי
תיתי לו. ותחשב.
*** למה קוראים קריאת שמע בתפילת ערבית:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-בתפילת-ערבית-1
:END:
רבינו תם מפרש שקוראים קריאת שמע בתפילה ערבית כדי לצאת בו מצוות קריאת שמע
של ערבית.
*** למה קוראים קריאת שמע שעל המטה:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-שעל-המטה-1
:END:
תוס' מפרש שקוראים קריאת שמע שעל המטה לסיבה אחת, והוא לקיים מה שאומר גמ'
לקמן שיש ענין לקרוא קריאת שמע שעל המטה. (לעיל, באר תוס' שהוא כדי לשמור
מן המזיקים.) אבל, אין חיוב קריאת שמע של לילה גורם לו לקרוא על המטה.
** קושיית תוס':
:PROPERTIES:
:CUSTOM_ID: קושיית-תוס
:END:
מקשה תוס' שגם נוהגים להתפלל תפילת המנחה אחרי פלג המנחה. נמצא שלא פוסקים
כרבי יהודה, אלא כרבנן.
*** תי' תוס':
:PROPERTIES:
:CUSTOM_ID: תי-תוס
:END:
תוס' מת' שבזה נוהגים כרבנן. לפעמים נוהגים כרבנן, ולפעמים נוהגים כרבי
יהודה. מסביר שזה לא כל כך קשה, שגמ' אומר שכיון שלא פסק הל' לא כרבנן ולא
כרבי יהודה, אדם יכול לעשות כאיזה מהם שירצה. אז, יכולים לנהוג לענין מנחה
כרבנן ולענין ערבית כרבי יהודה.[fn:24]
*** דיחוי תי' תוס':
:PROPERTIES:
:CUSTOM_ID: דיחוי-תי-תוס
:END:
תוס' דוחה שאף שלא נקבע הל' כרבי יהודה או כרבנן, ואז כל אדם יכול לבחור
כאיזה שירצה לפסוק כמותו, לא מותר לבחור לפסוק באופן שסותר את עצמו. (נראה
שיש שני דרכים לבאר את זה. דרך הראשון הוא שלא מותר לעשות דבר שכל תנא
שבעולם (וכל סברה שבעולם) יאמר שעבר על מצווה דרבנן להתפלל. דרך השני הוא
שכיון שפסק כרבנן, לא מותר לפסוק עוד כרבי יהודה, שכבר קבע הלכה כעצמו.
לשניהם, נראה שיש לדון כמה קרובים צריכים להיות שני הדברים, ובכמה זמן נביט
כאחד. ותחשב. מסתבר שלראשון יהיה כל ימיו. לשני, לא נראה זמן פשוט, אלא
נראה שיש לדון.)
כנראה, רבינו תם יסבור שאינו בעיה לסתור את עצמו בפסק זו. יש לדון אם תמיד
אין בעיה לסתור את עצמו או שהוא מפני שכאן מדובר בדינים שונים (מנחה
וערבית) או שמדובר בזמנים קצת שונים. ותחשב.[fn:25]
** שיטת ר"י:
:PROPERTIES:
:CUSTOM_ID: שיטת-רי
:END:
*** איך יוצאים:
:PROPERTIES:
:CUSTOM_ID: איך-יוצאים-2
:END:
ר"י אומר שיוצאים בקריאת שמע שאומרים בערבית. וא"ת איך יוצאים בו (ואיך
מתפללים ערבית) כיון שהוא קודם צאת הכוכבים. באר ר"י שסוברים כשיטות שמצאנו
בגמ' שאומרים שיכולים לקרוא קריאת שמע קודם צאת הכוכבים. מניח שכמו שאומרים
כן לענין ק"ש, גם יאמרו כן לענין תפילת ערבית. (זה לא צריך להיות משמיע לנו
דבר יסודי, כמו שראינו בדברי רבינו תם, שיש לומר שכיון שתפלה דרבנן, קבעו
רבנן אותו על זמן קריאת שמע של לילה, כיון שבדר"כ נאמר עמו. וא"ת הרי לא
עשו כן בק"ש של שחר. ויש לומר שלא ממעטים זמן תפילה בזה, אלא רק מוסיפים
עליו; הוא קולא מחז"ל. ותחשב.)
קצת קשה למה לא פוסקים כמשנה שלנו. עיין לקמן (ג.) שידון גמ' אם המשנה שלנו
סתם משנה או לא. יש לומר שאף שלא נזכר חולק זה, נזכר שיטת רבי יהודה, ואולי
ר"י יסבור כרבינו תם, ויאמר שבהכרח חולק רבי יהודה. אז, אינו סתם משנה.
רואים מזה, אז, שסתם משנה שנזכר אחריו שיטה אחת לא נחשב סתם משנה בכלל, ואף
לא למעט משאר השיטות. ותחשב על זה.[fn:26]
*** למה קוראים קריאת שמע בתפילת ערבית:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-בתפילת-ערבית-2
:END:
לפי ר"י, קוראים את קריאת שמע בתפילת ערבית כדי לצאת בו מצוות קריאת שמע של
ערבית.
*** למה קוראים קריאת שמע שעל המטה:
:PROPERTIES:
:CUSTOM_ID: למה-קוראים-קריאת-שמע-שעל-המטה-2
:END:
לפי ר"י, קוראים את ק"ש שעל המטה רק לקיים מה שאומר גמ' לקמן -- שצריך
לקרוא קריאת שמע שעל המטה. תוס' לעיל אמר שזה כדי לשמור מן המזיקים. אבל,
אין צורך לקרוא כדי לקיים מצוות ק"ש של ערבית, שכבר קיים אותו כשקרא בתפילת
ערבית.
** ראיית תוס'[fn:27] לשיטת ר"ת ור"י:
:PROPERTIES:
:CUSTOM_ID: ראיית-תוס-לשיטת-רת-ורי
:END:
תוס' מביא ראיה שמקיים את מצוות ק"ש של ערבית ממה שמצאנו אמוראים שהתפללו
של ערבית של שבת קודם שבת. הרי, אומר תוס', מס' גם קראו קריאת שמע אז. צריך
לומר שיכולים לקיים במצוות קריאת שמע אם קורא קודם זמנו.
איני מבין ראיה זו. יודעים שיש שקוראים קריאת שמע קודם צאת הכוכבים, כיון
שכן היה המנהג בימי הראשונים, כמו שאומרים רש”י ותוס'. אז, קשה מה מביא
משם; אולי אותם אמוראים קיימו את מצוותם בקריאת שמע שעל המטה. אולי צריך
לומר שכוונת תוס' הוא שלא מסתבר כן, שהיה לו לגמ' לפרש איך יצאו קריאת שמע
(ולמה אמרו קריאת שמע בתפילה). וא"ת הרי ירושלמי לא מפרש איך יצאו קריאת
שמע. (אולי רק היה לו לבבלי לפרש למה אמרו קריאת שמע.) צריך לומר שיש לחלק
בין בבלי לירו' או בין בריי' לגמ'. ותחשב.
** קושיית תוס' על ר"ת ועל ר"י:
:PROPERTIES:
:CUSTOM_ID: קושיית-תוס-על-רת-ועל-רי
:END:
לעיל, הבאנו ירושלמי הנוגע לזה. ירו' מקשה למה קוראים קריאת שמע בבית
הכנסת, כיון שהוא קודם זמן קריאת שמע. הרי, לתוס' הקושיה לא מובן, שקוראים
אותו אחרי זמן קריאת שמע.
** תי' תוס':
:PROPERTIES:
:CUSTOM_ID: תי-תוס-1
:END:
תוס' תי' שלא מדובר בקריאת שמע שאנו נוהגים לקרוא היום, שהוא מיד קודם
קריאת שמע. אלא, קודם שהתחילו בברכות ק"ש, קראו קריאת שמע. כיון שהתפללו
אותו קודם שקראו ק"ש השני, היה קודם זמן ק"ש, ואז מקשה הגמ' שהיה קודם זמן
קריאת שמע.
יש להקשות על ביאור של תוס'.
ראשון, קשה למה יק' ירושלמי שהוא קודם זמן קריאת שמע. יותר מזה, יש פלא
גדול במה שקורא פעמיים. היה לו להקשות שאם קורא כיון שיוצא בו, למה יקרא
אתו פעמיים. (יש בזה שתי קושיות. קושיה ראשונה היא למה לא נקט הקושיה היותר
טובה. קושיה שנית היא למה קושיית ירו' קשה בכלל. לזה, צריך לומר שקריאת שמע
ראשונה, ולא השנית, היתה לפני תחילת זמן קריאת שמע של לילה.)
שני, קשה על תי' של ירו', שהרי קורא אותו כדי לצאת בו. אז, קשה למה קורא
אותו פעם אחרת קודם שקורא אותו לפי תפילה. צריך לומר שכיון שהוא קריאת שמע,
ובו מקיים מצוות קריאת שמע, לא מקיים בו ענין לעמוד לתפילה מתוך דברי
תורה.[fn:28] (אולי זה מתאים עם מה שמקשה תוס' שרק קורא כדי להרחיק את
המזיקים. אולי אפשר לקרוא שתוס' מקשה שכיון שגם קורא לסיבה אחרת, לא יכול
לקיים את שניהם. אז, שניהם הולכים עם דרך אחד.) גם אפשר לומר שסובר שקריאת
שמע נאמר אחרי תפילה, כרבי יהושע בן לוי. גם יש לומר שכיון שקריאת שמע נאמר
עם תפילה כדי לסמוך גאולה לתפילה, קצת נחשב כחלק מן התפילה, וצריך קריאת
שמע בהקדמה לו. ותחשב על זה.
שלישי, ק' כיון שירושלמי קאי על המשנה. הרי, לפי תוס' לא פוסקים כתנא של
המשנה. אז, היה לו להשיב שאין פוסקים כתנא של המשנה. אם מניח שפוסקים
כמותו, יהיה קשה גם על קריאת שמע השני שקורא. ותחשב.
וצריך לחשוב על זה יותר.
** שני דינים:
:PROPERTIES:
:CUSTOM_ID: שני-דינים
:END:
תוס' מבאר שני דינים שיוצאים מן הדיון שדן.
*** דין ראשון:
:PROPERTIES:
:CUSTOM_ID: דין-ראשון
:END:
דין ראשון הוא שמי שקורא קריאת שמע לא יברך. לכאו', מלשון תוס' נראה שמכוון
לומר שזה מפני שבאר שלא יוצא בו, אלא יצא בקריאת שמע שאמר בתפילת ערבית. יש
להעיר שזה היה אחד מן ההוכחות שלו (אולי; לא מוכרח כן) לשיטתו. אז, אי אפשר
שרק יודע אותו אחרי שמוכיח כשיטתו. ותחשב. אפשר שכן היה נראה לו קודם
שיוכיח כשיטתו, אבל עכשיו ברור הוא לו[fn:29]. גם אפשר -- אבל דחוק לומר --
שזה יוצא מן הידון, ולא משיטתו. ועיין במה שנכ' בע"ה בדין שני שלו.
*** דין שני:
:PROPERTIES:
:CUSTOM_ID: דין-שני
:END:
דין שני של תוס' הוא שאין אדם קורא בקריאת שמע שעל המטה אלא פרשה ראשונה.
על זה בוודאי קשה מה שהקשינו על דין ראשון, שזה אחד מן ההוכחות לשיטתו.
צריך לומר כאחד מן השני דיחויים שכתבנו. ותחשב.
גם יש להעיר שקצת מעניין שתוס' אומר לנו דין זה, כיון שאין שיטה שחולקת על
זה. תוס' יאמר שלפי מה שאומר רש”י היה לו לחלוק על זה, אבל למעשה לא חולק
(כיון שהוא חולק בנקודה אחרת, ואומר שיכול לקיים אף שרק קורא פרשה אחת).
אז, מעניין שתוס' יאמר שיוצא מזה דין; הרי, אין חולק עליו. אין זה כל כך
קשה.
[fn:1]  יש לדון אם סובר שנאמר על דברי תורה בכלל או שנאמר על קריאת שמע,
ומחייב לומר אותו מדין לימוד תורה, ולא מדין קריאת שמע. (לדין שני,
המילים שחייב לומר הוא קריאת שמע, אבל אינו מפני שיש חיוב לקרוא
קריאת שמע, אלא מפני שיש חיוב ללמוד תורה, וזה בכלל תורה. אבל, אינו
צריך להיות קריאת שמע, אלא יכול להיות כל לימוד תורה.)
[fn:2] באמת, זה לא כל כך פשוט.אולי מזה נאמר שיש חיוב ללמוד תורה בשעת
שכיבה ובשעת קימה. עיין בגמ' במנחות (צט) שכן משמע, אולי, מן הגמרא.
אבל, לא נוהגים כן בני אדם. אולי לא פוסקים כרב יהודה.
[fn:3] יש הרבה דינים של קריאת שמע שנלמדו מן הפסוק של "בשכבך ובקומך.” כמו
כן, דין עוסק במצווה פטור מן המצווה נלמד מ"בלכתך בדרך.” (אין לומר
שלומדים מלימוד תורה, שללימוד תורה יש כללים שונים בענין עוסק
במצווה פטור מן המצווה.) קצת קשה מה יהיה המקור לכל זה, לפי רב
יהודה.
[fn:4] נראה שיש יישוב לזה. (דבר ראשון, צריך להעיר שאין זה קושיה נוראה,
שמצאנו, לפעמים, שיביא קטע של פסוק שלא מדוייק. אבל, בדר"כ, מביא
התחילה כשהיה לו להביא את הסוף; כאן, מביא את הסוף כשהיה לו להביא
את התחילה.) כמו שנבאר, לכאו', נצטרך מקור לכל אחד מן הפרשיות. מקור
לפרשה ראשונה, אולי, הוא "ודברת בם... בשכבך ובקומך,” ומקור לפרשה
שניה הוא "לדבר בם... בשכבך ובקומך.” רצה להביא פסוק אחד ששווה
לשניהם, ואז אמר "הפסוק שיש בו "בשכבך ובקומך,” שזה שווה בשניהם,
ולכן הביא אותו קטע.
[fn:5] יש לדון למה לא מסתבר. אולי לא מסתבר ללמוד קודם שהולך לישון, שזה
אינו זמן טוב ללמוד, ואולי לא מסתבר שבדווקא ירצה תורה שילמוד אז,
ואולי לא מסתבר שיהיה חיוב ללמוד אז, כיון שיש חיוב ללמוד כל הזמן.
[fn:6]  הבנתי שגם יכול להיות שחולקים אם החיוב לומר אותו, ולא רק לחשוב
אותו, הוא מדאו' או מדרבנן. אם כן, צריך לומר שהמקור שמביא רב יוסף
הוא "ודברת בם," ולא "בשכבך."
[fn:7]  בכל זמן שדנים בכמה חיובים, צריך להבין מהו הדיון. אפשר שהדיון הוא
אם היה נקבע להיות חיוב אחד או כמה חיובים (תחשב אם זה אומר כלום)
או אם עושה טוב אחד או כמה טובים, ואפשר שהדיון הוא היחס בין
החיובים (כמה זה מהנה לזה).
[fn:8]  יש להוסיף שרבי סובר שצריך להשמיע לאזנו, ודורש כן מ"שמע," כמו
שנבאר לקמן. אז, אולי הולך לשיטתו, ואומר שזה המקור שצריך לומר
קריאת שמע. במילים אחרים, אולי יכולים לומר שמה שרבי דורש כן מ"שמע"
הוא המקור לשתי שיטות שלו (מה שצריך לומר "שמע," אף שלא דורש
מ"ודברת בם," ומה שצריך להשמיע לאזנו). ותחשב.
[fn:9]  לא ממש מוכרח שסובר שצריך לקרוא את כל הפרשה, שאולי רק צריך לקרוא
עד אותו פסוק שבפרשה. אבל, הסתימות בוודאי לא משמע כן.
[fn:10] לא פשוט אם "דעת מינים" ו"הרהור עבודה זרה" הם דברים שונים. גמרא
אומר שיש בו חמשה דברים, ומונה ששה. אפשר להיות שמשנה הדברים חוץ
מיציאת מצרים, שזה עיקר החיוב. גם עיין בגר"א, שמשנה את הגי' לומר
"ששה.” אבל, אם לא נדחה כן, נוכל לומר שדעת מינים והרהור עבודה זרה
שווים. עיין בגמ', שרק מביא מקור להרהור עבודה זרה, ועליו אומר "זו
מינות.” אבל, איני מבין איך לקרוא את הגמרא אז, אם לא שנשנה אותו
בגי', ונוציא "דעת מינות" משם. מסברה, היה נראה שהם אחד, אם לא
שנאמר שהראשון הוא ללמוד אותו, והשני הוא לחשוב שהוא נכון. ותחשב
על זה.
[fn:11] לא פשוט לי שבאמת צריך לומר כן, ואולי החידוש הוא רק שיכול לומר כן
(עיין שם בגמרא, שבוודאי חידוש הוא שיכול לומר כן). אבל, לא נראה
כן, שאם אין מעלה לומר כן, למה להם לומר שיכול לומר כן. אבל, אפשר
שיש מעלה, ולא חיוב. אפשר שהמעלה, ואולי אף החיוב, בא ממה שכן צריך
לומר בשחר. ותחשב.
[fn:12]  זהו לשון הגמרא, אבל לא קל להבין, שהרי לא מזכיר בה יציאת מצרים.
מהמשך הגמרא יוצא שצריך להזכיר יציאת מצרים. אפשר לפרש שאינו
דווקא, ומכוון לכלול חלק שיש בו יציאת מצרים. דחוק. גם אפשר
שקושיית הגמרא הוא גם לבני א"י. אז, רק חולקים לומר שצריך להזכיר
פרשה שלישית, אבל לא צריך להזכיר אותו בענין זכירת יציאת מצרים.
ותחשב.
[fn:13]  באמת, הלשון שאומר הוא ש"מתפללים קריאת שמע." קצת מעניין שייחשב
תפילה, שאין בו שבח הודאה או בקשה, אלא הוא, לכאו', זכירה על עיקרי
האמונה. ותחשב. (אפשר לומר שהאו קורא אותו כן כיון שמהני לתפילה.
וא"ת הרי רק ידע כן במסקנא. אפשר לומר שאין הכי נמי, והגמ', שידע
מה יהיה המס', קרא אותו כן על שם המס'. כמו כן, יש לומר שקבלו
שאותו הלשון מתאים לו, ולא הבינו למה עד המסקנא. כמו כן, יש לומר
שידעו מעולם שמהני לתפילה, אלא שלא ידעו שיוכל להעלות את התפלה אם
לא מקיים בו קריאת שמע. ותחשב.
[fn:14]  יש לדון אם לשון זה משמע שהוא רק רשות. מצאנו מקומות שגמ' אומר
שדבר הוא "למצווה," כשמכוון לומר שהוא לא מעכב. אבל, אולי הוא רק
מצווה, ולא חיוב, אם כבר קרא אותו. (פשוט שאם לא קרא אותו יש חיוב
לקרוא אותו מחמת מצוות קריאת שמע, אבל אולי אז יש גם חיוב מחמת
קריאת שמע שעל המטה; במילים אחרים, אולי ק"ש שעל המטה הוא רק רשות
כיון שכבר קיים מקצת ענינו בקריאת שמע של ערבית.)
[fn:15]  אגב, אזכיר כאן שהיה נראה שלא היה רש”י של תוס' שווה לרש”י שלנו.
אחד מן הקושיות שהקשה תוס' על רש"י מפורש בדברי רש"י (לא מפורש בו
התשובה, אלא מפורש בו שרש"י מכיר את הקושיה, ולא חושב שקשה; היה לו
לתוס' להזכיר את זה), והירושלמי מפורש בדברי רש"י, ואף על פי כן,
מביא אותו תוס' כאילו הוא מצא אותו.
[fn:16]  יש להעיר שיש לדון אם, לפי רש"י, חייב לקרוא פרשה ראשונה או חייב
לקרוא פרשה אחת. זה יהיה נוגע לכל דיון זה.
[fn:17]  שוב נראה לי שאולי גם מקיים את מצוות קריאת פרשה ראשונה. נראה
שאולי צריך לקרוא לאחר כן רק כדי לייחס אותו ללילה, אבל כיון
שמיוחס ללילה, לא רק יוצא בקריאה ראשונה בפרשה שניה ושלשית, אלא גם
בפרשה ראשונה. נמצא שאפשר ליחס על ידי קריאת פרשה ראשונה אף שלא
יוצא בו. ותחשב.
[fn:18]  עיין בתוס' שאומר: "ואנן קיי"ל כר"י דאמר לקמן איזהו בן
עוה"ב...." היה אפשר לקרוא שכשאומר "דאמר לקמן..." בא לומר המקור
שהל' כרבי יוחנן. אבל, לא משמע כן, שהרי רבי יוחנן הוא האומר כן.
אז, אין להביא ראיה מזה. אפשר לומר שכיון שאמר אותו בלשון חזק זה,
מסתבר שהלכה כמותו. אבל, יותר נראה לומר שתוס' לא מביא מקור שלו,
אלא מביא המימרא שכמותו הלכה. אז, כאילו אמר שקיי"ל כרבי יוחנן
דאמר שצריך לקרוא אותו קודם תפילה. ותחשב.
[fn:19]  זה יותר קל אם נאמר שיש קיום בקריאת שמע שקורא לפני זמנו. (עיין
לעיל שכתבנו הרבה צדדים בזה; אולי יש רק מקצת קיום, או אולי יש
יותר בזה.)
[fn:20]  נראה שיש שני דרכים לומר כן. דרך הראשון -- הוא הדרך שרמזנו למעלה
-- הוא שכיון שהוא טורח לשהות להתפלל, לא חייב לעשות כן ולקיים
הלכה זו. דרך שני הוא שזה לא דין בתפילה אלא דין בקריאת שמע. (יש
לדון בזה.) אז, כיון שלא הגיע כבר זמן של קריאת שמע, לא חייב לשמור
שיהיה קודם התפלה, ויכול להתפלל. מושג זה, שקודם זמן של דבר לא
צריך לשמור על קיום שלו, לא כל כך קל להבין, אבל נמצא בכמה מקומות.
ותחשב על זה.
[fn:21]  הנחתי שגם זה מדברי רבינו תם. עיין בתוס', שלא מוכרח כן, ואולי
הוא רק בא לבאר שיטת רבינו תם שאדם יוצא בק"ש שבתפילת ערבית.
[fn:22]  תוס' גם מניח שיכולים לקרוא קריאת שמע אז. אבל, יותר מזה, רואים
שתוס' מניח שאף שלא לפי רבי יהודה יכולים להתפלל תפילת ערבית אז,
שהרי לא מוכיח ממה שמתפללים אז שהלכה כרבי יהודה. לא מוכרח כן
מרש"י, שאולי רש”י סובר שהל' כרבי יהודה, ולא אומר כרבינו תם כיון
שסובר שאף רבי יהודה לא יאמר שיקרא קריאת שמע אז.
שוב ראיתי שתוס' יאמר לקמן שרק לפי רבי יהודה יכולים להתפלל תפילת
ערבית אחרי פלג המנחה. אז, שקלא וטריא של תוס' צריך קצת ביאור.
[fn:23]  גם אפשר לומר שכיון שעיקר דרך לומר קריאת שמע הוא עם תפילה, נתנו
לו זמן שווה. עיין לקמן, שנביא צד כזה. אבל, יש להעיר שתפיה
מדרבנן. צריך לומר שעדיין יש ענין בו מדאו', ושבזה דן. ותחשב.
[fn:24]  עיין בלשון תוס', שקצת משמע שמה שמחדש בתי' הוא שזה לא קשה לפי
רבנן. אבל, לכאו', זה פשוט, וצריך לומר שמחדש מה שכתבנו.
[fn:25]  נראה שיש דיון יסודי ששיך לזה, והוא שיש לדון מהו כוונת הגמ'
כשאומר ש"דעביד כמר עביד," אם הוא שכיון שלא נאמר הלכה כזה או כזה,
ספק הוא, ויכולים להקל, או שאז אדם יכול לעיין בו ולפסוק לעצמו.
לשני, מובן שלא יכול להיות סתירה. יש להעיר שקשה איך יאמר תוס'
כראשון ולא כשני. הרי, כאן מדובר בקריאת שמע, וקריאת שמע מדאו'.
אז, אם נאמר שהוא ספק, נצטרך להחמיר עליו. אם סומכים על רבי יהודה
כיון שאין פסק, צריך לומר שאינו ספק, אלא שיכול כל אדם לקבוע הכה.
ותחשב. (כדי לדחות את זה, צריכים לחדש עוד פשט, והוא שאין לו דין
ספק, אלא הוא כאילו דין פסק, והוא שכל זמן שאדם סומך על שיטה, עושה
הישר והטוב. הרי, אם סומך על רבי יהודה, נמצא שהוא סומך על שיטה,
וכשהוא סומך על רבנן, נמצא שהוא סומך על שיטה. ותחשב.)
[fn:26]  לכאו', צריך לומר שאין ענין של סתם משנה שכיון שרק אמר דבר אחד,
צריך לומר שהוא נכון, אלא שכיון שרק אמר דבר אחד, ולא צריך לעיין
בו יותר כפי מה שרואים מן המשנה, צריך לומר שהל' כן. אבל, כיון
שמזכיר שיש מח', צריך לעיין בו, וימצא עוד שיטת. ותחשב. מה שלא
יהיה סתם משנה אם מזכיר שהוא דברי רבי אליעזר, ומה שנחלק, אולי,
בין זה לסתם שנזכר בו שיטה אחת, הוא שכיון שמזכיר את השם, מורה שיש
שיטות החולקות, ואז מעורר שצריך לעיין בהם. אבל, אם רק מזכיר שני
שיטות, יודעים מה הם השיטות החולקים, ולא נדע לעיין בשיטות אחרות.
ותו"ת.
[fn:27]  כמובן -- ובאמת, תוס' כמעט אומר כן בפי' -- הקושיות שמקשה תוס' על
רש”י הם ג"כ ראיות לזה. אבל, אנחנו כתבנו אותו כמו שמצאנו בתוס'.
[fn:28]  יש לדון בזה, שגמ' לקמן משמע שהקורא קריאת שמע כקורא בתורה,
ומקיים בזה ענין של לימוד תורה, שאם לא כן יהיה יותר טוב לקרוא שלא
בזמנו מלקרוא בזמנו, ולא נכון לומר שלא מפסיד כקורא בתורה, אלא הוא
נתרווח. יש לדון. יש לעיין במה שמגילה דוחה תלמוד תורה, ולא נחשב
תל' תורה (יש לדון בזה, שיש לומר שהוא רק מפני שלא נניח שכל בנ"א
דם שהיו לומדים יבואו לשמוע מגילה), ובירושלמי שמדבר בקיום ברכת
התורה בברכת אהבת עולם (אהבה רבה), רק אם לומד אחריו, ובדיון אם
קריאת שמע מהני לזה. ותחשב.
[fn:29]  קצת נראה כן ממה שצריך להביא הרבה הוכחות. קצת משמע שאין זו הוכחה
ברורה; קל לומר שהוא מפני שאולי רק נדע שהוא כן אם לא יוצא בו, אבל
אולי אם יוצא בו, אולי יברך עליו, ואולי יקרא כל שלש הפרשיות.
