* הקדמה:
:PROPERTIES:
:CUSTOM_ID: הקדמה
:END:
בסוכות, חייבים לשבת בבית מיוחדת שנקרא "סוכה." רש"י מפרש בסוכה שנקרא כן על שם הסיכוך. אז, נדבר בפסול בסיכוך. נדבר בכמה מינים הפסולים בסכך, ונבאר מה קורה אם אחד מן הפסולים נמצאים בסוכה שלו.
* פסולים:
:PROPERTIES:
:CUSTOM_ID: פסולים
:END:
** סכך פסול:
:PROPERTIES:
:CUSTOM_ID: סכך-פסול
:END:
מן התורה, סכך צריך להיות גדל מן הקרקע, צריך להיות שלא מקבל טומאה, וצריך להיות שאינו מחובר לקרקע.
גמרא נותן ארבע מקורות לזה:
1. הפסוק אומר שיושבים בסוכות לזכרון לענני הכבוד. הרי, ענן הוא דבר שגדל מן הארץ (כמו שנאמר "ואד יעלה מן הארץ"; לכאו', הביאור הוא שענן נעשה ממים, והמים הוא בארץ), ואינו מחובר לארץ, ואינו מקבל טומאה. סכך, שהוא עיקר הסוכה, צריך להיות דומה לענני הכבוד.
דוחה גמ' שחולקים תנאים בטעם של מצוות סוכה. הרי, הפסוק אומר שהוא לזיכרון לסוכות שבו הושיב ה' את בני ישראל. חולקים ר"א ור"ע אם כוונת הפסוק לענני הכבוד או לסוכות ממש. מקור זה רק אפשר לפי ר"א שאומר שהכוונה היא לענני הכבוד.
2. [@2] הפסוק אומר "חג הסוכות,” ומקיש את הסוכה לחגיגה. חגיגה היא בהמה, ואז גדלה מן הארץ (כיון שאוכלת דברים הגדים בארץ), אינה מחוברת לארץ, ואינה מקבלת טומאה.
רש"י מעורר שלפי זה, מרבים גם בהמות, ואז יכולים לסכך בעורות. אבל, רש"י אומר, זה רק לפי הצד הזה. כשחוזר גמ' מן הצד הזה, גם חוזר מן אותו הדין. נראה שאין זה ממש מוכרח. תחילה, יש להעיר שלא נכון שאין חגיגה מקבל טומאה, שהרי חגיגה הוא בשר, ומקבל טומאה. אז, צריך לומר שלא מדובר בבהמה שחוטה, אלא בבהמה חיה. אז, נראה שאפשר לומר שרק בהמה חיה נחשב, לפי פשט זה, להיות גדל מן הארץ. הביאור יהיה שכיון שהבהמה נשתנה כל כך מחיותה למיתתה, אומרים שהבהמה המתה לא באה מן הקרקע, אלא באה מן הבהמה. ותחשב. אז, נראה שנוכל לומר שזה רק מגלה לנו שיכולים לתת בעל חי ממש על סוכה, ואכן אולי יכולים. ותחשב.
גם מעניין שלא נאמר כן לפי פשט ראשון. היה נראה שאם נאמר כן בבהמה, גם נאמר כן בענן. נראה שענן שונה, שהוא עצמו מן המים שהיה בארץ, ואינו רק אוכל המים.
דוחה גמ' שאם כן יוכל לסכך בבעלי חיים (שכמו שרש"י אומר, מרבים בהמות), ויודעים שאי אפשר לסכך בהם.
וא"ת אם זה אפשר לומר לצד ראשון, ל"ל הקשה שם. וי"ל שהיה לו קושיה יותר טובה. לא נראה כן, שרק דוחה לפי שיטה אחת שם. ותחשב. וי"ל שלא דחה כן כדי שיוכל להביא הו"א זה.
3. [@3] הפסוק אומר שהסוכה תיעשה "מגרנך....” מזה דורשים שסכך צריך להיות דבר הבא מן הגורן ומן היקב, שהוא הפסולת. הוא דבר שלא מקבל טומאה, ואינו מחובר, ובא מן הארץ. דוחה גמ' שאולי מדובר על גורן ויקב עצמו, והם מקבלים טומאה, אבל מסיק שכיון שאומר "מגורנך" לא מדבר בגורן ויקב עצמם.
4. הפסוק בנחמיה מספר איך שהלכו בני ישראל והביאו ירקות שונות. מבאר גמ' שהביאו ירקות לסכך. הרי, רואים שסכך הוא דבר שאינו מחובר לקרקע, ואינו מקבל טומאה, ושגדל מן הקרקע, כאותו סכך שמצאנו שם.
** סוכה תחת דבר אחר:
:PROPERTIES:
:CUSTOM_ID: סוכה-תחת-דבר-אחר
:END:
כיון שכתיב, "בסוכת," בלי וי"ו בסוף, דורשים שסוכה שתחת דבר אחר פסולה.
*** תחת בית:
:PROPERTIES:
:CUSTOM_ID: תחת-בית
:END:
אם הסוכה תחת בית, פסול, משני טעמים. טעם ראשון הוא שיושב בסוכה תחת סכך פסול, וטעם שני הוא שבדרך כלל לא משנה דירתו מדירה רגילה שלו. (ערוך השולחן מוסיף טעם שני.)
יש לדון למה פסול:
1. כיון שאין הסכך נחשב סכך כל כך. יש לדון למה:
   1. כיון שבלי הוא, עדיין יהיה צל.
   2. כיון שאינו המסכך, שכבר ניצול החמה קודם שהגיע לו.
   3. כיון שאין הסכך חשוב, שלא מסכך (אינו נצרך). (זה שונה מלעיל; לעיל, הבעיה הוא בצל, וכאן הבעיה הוא עם הסכך.)
   4. כיון שאין הסכך עומד לישאר שם כלל, שאינו עושה דבר חשוב.
2. כיון שיש סכך פסול:
   1. הוא יושב בצל של סכך פסול.
   2. אילו לא היה סכך כשר, היה סכך פסול צל עליו.
*** תחת אילן:
:PROPERTIES:
:CUSTOM_ID: תחת-אילן
:END:
**** הפסול:
:PROPERTIES:
:CUSTOM_ID: הפסול
:END:
אם צל האילן מרובה מחמה של האילן וקדמה אילן לסכך, פסול. אם קדמה סכך לאילן, חולקים גאונים וראשונים אם כשר או פסול. לכאו', הטעם להכשיר הוא לומר שעיקר הסיכוך הוא מה שהיה קבוע כאן ראשון. הביאור הוא שתמיד כשיש שני סיבות לדבר אחד, יכולים לומר שסיבה אחד היא העיקרית, והשני עומד נגדו, למלא את מקומו, אם צריך. לפי הגאונים, מה שבא ראשון הוא הסיבה העיקרית, והשני הוא העומד נגדו.
נראה שזה מצוי לקרות. אם רוח מוליך אילן על סוכה, יש לסתפק אם יכולים לשבת תחת האילן בשעה שהרוח מוליך אותו שם (שאולי אומרים שהוא עומד לחזור למקומו). אבל, לפי גאונים בוודאי כשר, שהסכך קדם לאילן. אפשר שכאן כו"ע יודו לסברת הגאונים, ויאמרו שכיון שהסכך קבוע, ואין האילן קבוע, הסכך היא עוקר האהל.
אם האילן חמתה מרובה מצילתה, חולקים אם לפעמים יפסל. רש"י ותוס' אומרים שתמיד כשר. אבל, ראב"ן ראבי"ה ור"ן סוברים שהאילן פוסל מה שלמטה ממנו, ואז, כדי להיות כשר, צריך להיות שצל הסוכה מרובה מחמתה, ומחמתה.
קשה למה רש"י ותוס' לא סוברים כר"ן. הרי, האילן הוא סכך פסול, ומה שהוא תחתיו יפסול. אין לומר שאין האילן כל כך פסול (כמו שנבאר לקמן), ואז אינו פוסל מה שתחתיו, שאם כן אף אם צילתה מרובה מחמתה לא יפסול. אפשר לומר שלפי רש"י, מה שיש בו חמה יותר מצל לא נחשב סיכוך. (כמו כן, יש לומר שאין מקום שתחתיו נקרא על שמו כל כך, כיון שלא מסכך עליו.) אז, אינו תחת סכך פסול. (על פי זה, נראה לבאר שסכך שחמתה מרובה מצילתה אינו פסול רק מפני שאין מספיק סכך, אלא שאין שום סכך, שאין הסכך גורם סיכוך לסוכה.) גם אפשר שכיון שרק סיכוך של הסוכה יש בו יותר צל מחמה, הוא הסיכוך העיקרי, כמו שמצאנו לשיטת גאונים אם קדמה סיכוך הסכך. גם אפשר שסובר שהסכך מבטל את האילן, כיון שביחד הם סכך, אף שהם רחוקים זה מזה.
יש להעיר שבציור כזה, יש שלשה חלקים -- יש צל הסכך, יש צל הסכך שהוא תחת האילן, ויש חמה. יכול להיות שלשה דינים. יכול להיות שצל הסכך צריך לבטל שנים הפסולים, אפשר שיצטרך לבטל כל אחד בפני עצמו (אבל לא בצירוף), ואפשר שיצטרף עם אחד לבטל את אחד מן הפסולים, ואחר כך יבטל את האחד שהצטרף עמו (אולי בפני עצמו או אולי באחר שנתבטל). הסיבה שנאמר הראשון הוא שיש דמיון בין שני הפסולים, במה שהם פסולים. אבל, לא נראה שזה יספיק, שנראה לקמן שאין סכך פסול מצטרף עם אוויר. אבל, אפשר לומר שכאן, יצטרפו כיון ששניהם הם מקומות שסכך הכשר לא עושה צל. (שם, סכך הכשר וסכך הפסול הם אחד. אבל, כאן, הם מופרשים, ויכולים לומר שסכך הכשר לא עושה צל.) הסיבה שנאמר השני הוא שכל אחד הוא מין בפני עצמו. הסיבה שנאמר השלישי הוא שיש דמיונות בין הכשר עם הפסול. למשל, דומה לחלק האמצעי במה שיש בהם צל. כמו כן, דומה במה שהוא תחת סכך הכשר (אף אם אותו סכך לא נותן הצל, שכבר דבר אחר נתן צל). הוא דומה לחלק שתחת החמה במה שאינו תחת סכך פסול.
כשרש"י ור"ן חולקים, איני יודע במה חולקים, ומי סובר מה. לעיל, בארנו צדדים שיעשה שרש"י סובר שתמיד כשר, ואין צריכים שום ביטול. אבל, לא צריך להיות כן.
יש להעיר שלפי רש"י אם צל האילן יותר מחמתו, אף אם אין בו סיכוך כמו הסכך, משמע שעדיין פסול. לפי מקצת הצדדים שכתבנו, לא כל כך פשוט למה זה יהיה.
יש להקשות מה זה מוסיף על דין בית. נראה שאפשר שמוסיף אף ציורי פסול של חמה מרובה מצל, כמו שנראה לקמן. גם אפשר שמוסיף שאף פסול זה של מחובר לקרקע, עושה פסול של בית, אף שקל לתקן אותו.
**** ההכשר:
:PROPERTIES:
:CUSTOM_ID: ההכשר
:END:
גמרא אומר שיכול להכשיר על ידי חבטה, אם רוב הסכך כשר. לר"ן, זה ר"ל שאם אילן חמתה מרובה מצילתה, וצל הסוכה שאינה תחת האילן לא יותר מחמתה, יכול להכשיר. לפי רש"י, זה ר"ל שאם אילן וסוכה הם חמתם מרובים מצילתם, יכולים להכשיר על ידי צירוף הבאה מחבטה.
חולקים ראשונים מהו חבטה. מצאנו שלש שיטות.
רש"י כתב שחבטה רצה לומר שמשפיל ומערב את ענפי האילן עם הסכך. (רמ"א כ' שצריך להיות שאין האילן ניכר. מהמשך הרמ"א נראה שאין זה דווקא; ערוך השולחן כ' שר"ל שאינו ניכר להיות דבר בפני עצמו, אלא נראה כחלק של סכך הסוכה, אף שיכול לכוון איזה עדיין אילן.)
רש"י מעורר שביטול זה הוא ביטול ברוב, שמדאו' מבטלים ברוב. קשה, שמדרבנן צריך ששים נגדו לבטל אותו. אז, גם כאן נצטרך לששים. אפשר לומר שאין ששים נוגע לכאן, שששים הוא השיעור של נותן טעם. כאן, לא אוכל כלום, ואין טעם שייך. אז, הולכים אחרי השיעור מדאו'. אבל, יש לדון בזה, שנכון שהשיעור של טעם נוהג רק בדברי אכילה, אבל יש דברים אחרים שאולי נוגעים בציור שיושב תחתיו, כמו מה שנותן צל. ותחשב. גם אפשר שהוא מפני שנחשב מין במינו בדבר יבש. אז, הביטול צריך רוב גם מדרבנן. מה שנחשב מין במינו יכול להיות מפני שהוא גם מין הכשר לסכך או מפני שבמה עושה -- בנתינת צל -- הוא שווה. גם אפשר שגזרו רק באיסור, ולא בקיום מצווה. הביאור יהיה אולי שיותר רע אם נמצא שעובר, או שכ"ז שנותן טעם, אוכל מעט מן האיסור, וזה רע. אבל, באיסור, בוודאי לא עושה דבר רע. גם אפשר שיש שני ביטולים כאן -- יש ביטול צל בצל, ויש ביטול חפץ בחפץ. אולי מפני זה, יותר נחשב בטל, ולא צריך ששים נגדו לבטל. (וא"ת ל"ל אומרים כן בכל ביטול. וי"ל ששם אין הטעם חשוב כמו שהצל חשוב כאן.) גם יש לומר שכיון שהם בגדרים שונים -- זה צלו יותר מחמתו, וזה חמתו יותר מצלו -- יכול להיות ביטול ברוב. אולי הענין הוא שאז אין לחוש שלא יהיה רוב, כיון שההבדל גדול. גם יש לומר שאינו רק רוב נגד מיעוט, אלא הוא דבר חשוב בגד שונה נגד דבר אחר. לפי מה שנביא בשם עה"ש לקמן, בע"ה, נראה שאולי יש עוד ביאור.
עה"ש מקשה למה לא אומרים שאין מבטלים איסור לכתחילה. אפשר לומר שאינו דבר של איסור, אלא של מצווה. כיון שאינו חיוב גמור, כיון שיכול לשבת בסוכה אחרת, אין איסור של ביטול לכתחילה. כמו כן, יש לומר שכיון שבאותו רגע לא צריך לשבת בתוך סוכה, אינו נחשב דבר חיוב. מעניין שלא רק אומר שמצווה שונה מעבירה בזה. גם תי' שזה נכלל בהל"מ של שיעור שלו, וכיון שיש היתר עליו בהל"מ, לא גזרו בו איסור. גם באר שבאמת לא צריכים שום ביטול כאן. אלא, כיון שרוב הסכך כשר, זהו סכך כשר. אבל, כדי לומר כן, צריך להיות יחדות ביניהם, ומה שאחד מחובר לאילן עושה שאין יחדות זה. הביטול מביא אותו היחדות. על פי זה, גם יש לבאר למה מהני ביטול של רוב, שהרי אינו מבטל שם איסור או שם פסול.
הרמב"ם והרי"ף כתבו שחבטה רצה לומר שיחתוך אותו מן האילן. רש"י מקשה שאז אינו סכך פסול, ולמה יצטרך רוב של סכך הכשר. משיבים שכיון שכתיב, "תעשה," צריך הסוכה להיות בא על ידי עשייה, ולא שייעשה בפני עצמו. אם גמר הסוכה באה מחתיכת האילן, כיון שאין זה מעשה לסוכה, נחשב שהסוכה באה מן העשוי. לכן, צריך לנענע את הענפים. אבל, אם יש רוב של סכך כשר, לא צריך לנענע.
לפי הרמב"ם, יש לדון למה כשר אחרי שחבט. הפשטות הוא שהוא מפני ביטול ברוב. אבל, אפשר לומר צד אחר; אפשר לומר שהעשייה האחרון קרה לסוכה, שהעשייה היתה הביטול.
יש לדון למה רמב"ם לא סובר כרש"י. אפשר לומר שסובר שלא נחשב תערובת, כיון שאחד מחובר לאילן, וניכר לגמרי. גם אפשר שסובר שאין אומרים בו ביטול בכלל, מפני מה שיש להקשות על רש"י, ואז מתיר מטעם אחרת. לזה, צריך לומר כטעם השני שכתבנו ברמב"ם.
בעל המאור כתב שלשון חבטה דומה ללשון חבטת ערבות, ומבאר שר"ל שחובט את העלים ממנו, שמראה שלא מקפיד על סיכוך של האהל. לכאו', הביאור הוא שכיון שמראה שלא מקפיד על סיכוך שלו, בסכך נעשה סיכוך העיקרי. וא"ת כיון שלא נשאר עלים, אין בו סיכוך, ולמה צריך גילוי זה. יש לומר שצריך כדי לבטל סיכוך האילן עצמו. יש לדון בזה, שרק גילה שלא רוצה עלים, ולא שלא רוצה כל האילן. צ"ל שכיון שנוטל ממנו את העלים, מראה שלא רוצה את כל הסיכוך שלו כלל. גם קצת מחודש, שבדר"כ אין האילן עצמו גדול כ"כ. גי"ל שלא צריך ליטול את כל העלים, אלא כיון שהתחיל, אין העלים (ואולי אף האילן) נחשב סיכוך, שגילה שלא רוצה.
בעה"מ בוודאי הולך כר"ן, ולא כרש"י, שלפי רש"י, צריך צירוף של האילן כדי לעשות שיש יותר צל מחמה.
בביאור למה לא סובר כרש"י, יש לומר שני הצדדים שכתבנו ברמב"ם. בביאור למה לא סובר כרמב"ם, אפשר לומר שסובר כרש"י (שאם חתך אותם, לא צריך ביטול, הורי הם סכך כשר מיד), ואפשר שסבר שאין אומרים ביטול כלל (או שאין זה נחשב עשייה).
אבל, גמ' משמע שלא יכולים להכשיר על ידי חבטה אם האילן צילתה מרובה מחמתה. יש לדון למה לא. לפי רש"י עצמו לא קשה, שמדובר בסוכה שהיא חמה מרובה מצל, ואז בוודאי אין בו רוב. (אולי, באמת, יש מכאן הוכחה לרש"י.) לר"ן, אפשר שאז גוזרים שרוב לא מספיק לבטל, וצריך יותר. גם אפשר ששם גוזרים אטו ציור שלא חבט אותם, כיון שהוא יותר דומה הציורים, שבין כך ובין כך, נותן יותר צל מחמה.
*** תחת סוכה:
:PROPERTIES:
:CUSTOM_ID: תחת-סוכה
:END:
כדי שסוכה עליונה יפסול את סוכה התחתונה, צריכה להיות גבוה. חולקים כמה גובה צריך, אם הוא טפח, כאהל הטומאה, ארבע טפחים, כמקום חשוב (וזה קשה להבין, שזה שיעור של רוחב מקום חשוב), או עשרה טפחים, כהכשר סוכה. גם צריך להיות ראוי לדיורים. גמ' מבאר שזה רצה לומר שצריך להיות ראוי להניח שם כרים וכסתות. לכאו', ר"ל שצ"ל שהוא חזק עד שיכול לקבל אותם. לכאו', גם צריך להיות ראוי לקבל את הדיורים (אבל, אין זה מוכרח). חולקים תנאים אם צריך להיות ראוי לקבל אותם ברווח או גם בדוחק. עה"ש ביאר שמחלקת זה בין רבי יהודה ורבנן הולך לשיטת מחלקת רבי יהודה ורבנן באם סוכה נחשבת דירת עראי או דירת קבע. לרבנן, נחשבת דירת עראי, ואז פוסל אם יש בו דירה ע"י הדחק. לרבי יהודה, נחשבת דירה קבועה, ואז רק פוסק אם יש בה דירה שלא ע"י הדחק. עה"ש כ' שגם צריך להיות בו רוחב הראוי לסוכה. לכאו', זה יהיה תלוי במחלקת האמוראים שכתבנו, שלשיטה ראשונה רק יצטרך להיות אהל לטומאה, שהוא טפח על טפח על טפח, ולשיטה שנית, רק צריך להיות מקום חשוב, שהוא ארבע על ארבע על ארבע.
נראה שיש לדון למה פסול. אפשר שהוא מפני שהוא סכך תחת סכך (אולי הענין הוא שאין אחד מהם עושה סיכוך, כיון שבלי הוא, עדיין יהיה סיכוך), ואפשר שהוא מפני שהוא סכך תחת סוכה, ואפשר שהוא מפני שהוא תחת סכך שאינו של אותו סוכה, ואפשר שהוא מפני שיושב בתוך שתי סוכות (סוכה תחתונה, וסוכה גדולה שכוללת את שתיהן). מה שצריך העליון להיות סוכה מובן לכל הצדדים. לראשון, הוא מפני שאם אינם שייכים לסוכות שונות, מצטרפים ונחשבים אחד. לשני, הוא מפני שרק כשר אם הוא סכך תחת סכך (אולי מפני ששניהם כשרים, ואולי מפני ששניהם מצטרפים), ורק פסול אם הוא תחת סוכה. לשלישי, הוא מפני מש"כ בראשון, ולרביעי, לכאו' הביאור יהיה שכולו נחשב סוכה אחד (והתחתונה אינה סוכה בפני עצמה), כיון שהעליון אינה סוכה בפני עצמה.
אם החתחון או העליון יש להם יותר חמה מצל, אינו פסול. לצד ראשון, זה קשה על שיטת ר"ן לעיל (גבי אילן על סוכה). יש לומר שכיון ששניהם כשרים, מצטרפים. כמו כן יהיה לצד שלישי. לצד שני ולצד רביעי, יש לומר שיש רק סוכה אחת.
חולקים ראשונים אם שניהם חמתם מרובה מצילתם, אם מצטרפים עד כדי להכשיר את התחתון. גמרא משמע שלא מכשיר, שציור של הכשר התתון שמזכיר יש בו צילתו מרובה מחמתו. אפשר לומר שר"ל שסוכה תחתונה יש בו זה, מפני צירוף העליון והתחתון. לא נראה כן, שגם מזכיר ציור שבתחתונה, חמתה מרובה מצילתה, ובעליונה, צילתה מרובה מחמתה.
*** תחת דבר פסול:
:PROPERTIES:
:CUSTOM_ID: תחת-דבר-פסול
:END:
משנה אומר שסוכה שפרס עליה סדין מפני החמה או תחתיה מפני הנשר או קינוף (שנותן לנוי על מטתו) פסול. על זה אומר רב חסדא שאם רק נתן עליה לנאותה, כשרה. רש"י כ' שכיון שאינו להגן, לא נחשב סכך. אולי רוצה לומר שאז אינו משמש בו כבגד, ואין השם שלו "בגד," שהוא פסול. אז, הוא כשר לסכך. גם אפשר שר"ל שכיון שלא משמש בו כסכך, בטל הוא לסכך. וא"ת ל"ל מבטל את הסכך. י"ל שמה שסכך עושה יותר חשוב. גי"ל שאין אדם דר בלי סכך, ולא מנאה אותו אם לא דר שם. אז, מה שסכך עושה יותר בסיסי, שגורם לשניהם. יש להעיר שדין זה נכון אף אם זה מסכך, כל זמן שלא ניתן שם לסכך.
אם ניתן שם לנוי, והוא ארבע טפחים רחוק מן הסכך, חולקים אם הוא כשר או פסול. הצד לפסול הוא שכיון שהוא רחוק מן הסכך, לא בטל לו. יש לדון אם המכשיר סובר שעדיין בטל לסכך או שבטל לסוכה.
וא"ת ל"ל כשר כשישן תחת נקליטין, שזה נעשה לנוי. י"ל שזה נעשה לסיכוך ולנוי. גי"ל שזה לא קרוב לסכך, ואינו על כל הסוכה, ולא יכול להיות בטל לו, ואינו מותר. נראה שאפשר לומר ששם הוא מאד רחוק מן הסוכה, עד שעושה דבר לעצמו, עד שאולי שם יש פסול אחר. כאן, לכאו' הפסול הוא מפני שיש סכך פסול. אבל, אולי שם הפסול הוא שאינו יושב בסוכה, שיש הפסק בינו לסוכה.
גאונים כתבו שאם ניתן הסכך קודם שנותן עליו סדין, הוא כשר. לכאו', זה מפני שעיקר האהל הוא מה שנותן ראשון, כמו שהזכרנו לעיל. עה"ש כ' שאפשר שנאמר כן כאן, אף אם לא נאמר כן באילן, כיון שהוא כבר קצת בטל לסכך. אולי זה מפני שהוא להציל (אפשר שהכוונה הוא שהוא להציל מה שבא מן הסכך, ואולי הוא מפני שיש לו אותו הצורך), ואולי זה מפני שהוא יותר קרוב.
* אם יש בו פסול:
:PROPERTIES:
:CUSTOM_ID: אם-יש-בו-פסול
:END:
** אם יש בו סכך פסול:
:PROPERTIES:
:CUSTOM_ID: אם-יש-בו-סכך-פסול
:END:
אם הפסול הוא באמצע, חולקים אמוראים אם פוסל בארבע אמות או בארבעה טפחים. להלכה, פוסל בארבעה טפחים, כיון שזה מקום חשוב. זה רק פוסל את הסכך הפסול. אבל, יכול לשבת בשאר הסוכה, אם יש בו הכשר. כדי למצוא הכשר, מצרפים את כל הסוכה עד מקום הפסול. אם אין הפסול הולך על פני כולו, מצרפים גם שאר הסוכה, אחרי מקום הפסול. (יש לדון כמה רוחב צריך להיות מסכך כשר.)
אם הפסול הוא בצד, יש הכשר של דופן עקומה, שרואים המחיצה כאילו כופף עד הסכך. רש"י מפרש שרואים שסכך הפסול הוא המשך של המחיצה. גם מביא פי' שרואים שמחיצה הולך תחת סכך הפסול, ודוחה ממה שלא אומרים דופן עקומה אם יש רק אויר שם. יש לדחות שרק אומרים אותו אם אין סתירה למחיצה במה שאין שום דבר שם.
חולקים ראשונים אם אומרים דופן עקומה כשאין המחיצה מגיע לסכך. וא"ת הרי אין אומרים ד"ע כשאין סכך פסול, אלא אויר. עה"ש תי' ששם מה שהוא אויר הוא יותר חשוב, כיון שהוא מקום שיותר צריך להיות דבר. גם יש לומר שיש מחצה, כיון שגוד אסיק.
אין לשבת תחת מה שהוכשר על ידי דופן עקומה, שאותו מקום תחת דופן, ולא תחת סכך. נמצא שהחיוב הוא לשבת תחת הסכך, ולא בתוך הסוכה.
אם רוב הסוכה פסול, כולו פסול.
כל זה בסוכה גדולה. אבל, בסוכה קטנה (שהוא רק שבע על שבע טפחים), פוסל את הכל בשלשה טפחים. עה"ש מבאר שהוא מפני שלא מסתבר לפסול בארבע טפחים, שכבר אין רוב (יש לדון בזה, שיש רוב אם יש רק ארבע על ארבע שפסול). אני הייתי אומר שפסול כיון שעושה שאין שיעור הכשר סוכה במקום אחד. (וא"ת יכול להיות שלש מן הצד וארבע מן הצד. וי"ל שאי אפשר לצמצם. יש לדון, שבדר"כ לא אומרים כן לפסול שיעורים.) אבל, אז לפעמים ינהג גם בסוכה שהוא תשע על תשע.
** אם יש בו אויר:
:PROPERTIES:
:CUSTOM_ID: אם-יש-בו-אויר
:END:
אויר כל שהוא פוסל. אבל, יש הלכה של לבוד, ונמצא שאין אויר כל שהוא עד שיש אויר שלש טפחים, שמחמת לבוד ממלאים אותו. ערוך השולחן כתב שמה שאויר יכול לפסול בפחות ממקום חשוב כיון שהוא ניכר. יש לדון אם זה מחשיב אותו המקום או שזה עושה שהוא יותר מובדל, ואין כשרות שאר הסכך מכשיר אותו.
אויר זה פוסל את כל הסוכה. אבל, לא תמיד פוסל את כל הסוכה, אלא רק פוסל אותו באופנים שבארנו בסכך פסול.
אויר פוסל בין מן הצד בין באמצע. יש אמוראים שסוברים שלא אומרים לבוד באמצע (איני יודע למה; אולי הוא מפני שכיון שהוא כנגד רוחב שני דברים, לא פשוט איזה דבר להמשיך. גם אפשר שלבוד רק מכשיר לומר בו דופן עקומה.), ואז פסול במה שהוא. צריך לשער, שתמיד יש קצת אויר בסוכה. עיין לקמן, שעה"ש ידבר בזה.
אין לשבת תחת האויר, שאף שאומרים לבוד, לא נחשב סכך כשר. (איני מבין למה. אולי צריך לומר שאף כשממלאים אותו, לא ממלאים אותו בסכך כשר. יש לדון למה לא, שהייתי אומר שההכשר הוא מפני שממשיכים מה שקרוב לו.) עה"ש מבאר שזה רק אם הולך על פני כל הסוכה, או על פני ראשו ורובו של מי שישן. (לא משמע מדבריו שהוא אם הולך על פני ראשו ורובו כשישן או אוכל, אלא שזהו השיעור.) איני יודע למה משער בישן, ולא באוכל.
אבל, אם הוא בסוכה קטנה (שהוא רק שבע על שבע טפחים), עה"ש כ' שיכול לשבת תחת האויר. איני יודע למה זה. אפשר שהוא מפני שבלי זה, כמעט פוסל את כל הסוכה, ולא רצו להחמיר כל כך בו. גם אפשר שהוא מפני שכיון שהוא כל כך קטן, שמו של מקצת יותר הולך על השאר, ואז שם של סכך כשר הולך גם על האויר יותר.
** צירוף:
:PROPERTIES:
:CUSTOM_ID: צירוף
:END:
אין אויר ופסול מצטרפים. מעניין שלא אומרים שאויר מוסך את הפסול. מסופק רא"ש אם אויר מפסיק בין שני טפחים טשני טפחים של פסול, ומכשיר את הסוכה. מבאר עה"ש שבוודאי לא ממשיך את הפסול, אף שסביב לו רק פסול, כיון שאין אומרים לבוד להחמיר. (יש לדון, שהייתי אומר שהספק הוא אם בשני צדדים שי גם סכך כשר.)
