כבר כתבתי בגלגל זה על נייר.
* סו:
** אם טמאי -
צריך ביאור למה פשוט ללמוד דין זבים; נפרוך מה לזבים שיש להם דין משכב או כדומה.
* סז.
** ואיזה זה -
לכאורה, אין הוכחה איזה זה, אלא מניחים שהוא פסח. לכאורה, היה אפשר לומר שהוא תמיד הבא בטומאה, ונלמד פסח מתמיד. ותחשב.
** עמו -
צריך ביאור איך שימש משה כיון שלכאורה היה טמא מעצמות יוסף. אולי הביאם באופן שלא יטמא. גם אפשר שכמו שהיה מותר לו אף שהיה זר (יש לדון, שאף שלא היה מזרע אהרן, אולי ה’ שינהו, ועשהו כהן, אלא שעל זה גן כן אולי יש לומר כמה שכתבנו. ותחשב.), אף היה מותר בטומאה.
* סז:
** כחתימת -
קשה, ששיעורו קטן (ומצינו כעין זה בכ"מ, כמו גבי מת נגד שרץ).
* סח.
** אם כן -
קשה למה לא אומר שכשיכולים לדרוש, דורשים.
* סח:
** כתוב אחד -
אינו ממש אחד, שהרי דורשים שנים, אלא רצה לומר שמקורים שווה.
** פורים -
מוזר, שזה לא מועד.
** מר בריה -
משמע שמותר אף בשבת, אף שלא לתענית חלום. ותחשב.
* סט.
** בשחיטה -
יש להעיר שלכאורה לא מת בשחיטה, ומוזר מה שלא בא קללת חכם, שאף על בא חנם.
* ע:
** מאי טעמא -
קשה למה לא אמר כגמ’ לעיל.
** אבל קופיץ -
יש לדון, שאפשר שכבר יודע חבורתו. ונראה שכיון שיש בני אדם שלא יודעים, לא נוכל להניח שכבר הטבילו.
** אבין -
מזה רואים, לכאורה, ששמו היה אבין, ולא רבין. אולי היה נקרא בשניהם או היה רבין קצר לרב אבין.
* עא.
** מה ראית -
אם כן, יהא ראיה להיפך.
** כסות -
יש לדון למה אין בזה בעיה שנעשו שלא בזמן שמחה.
* עב.
** אר"מ -
קשה למה מניח גמרא שצריך להיות לשיטת עצמו, שרק מפרש שיטת ר"א ור"י. יש לדון.
* עב:
** מפני שהוציא -
קצת קשה, שלכאורה, כבר יצא. וחושב אני שדן גמרא בזה.
* עג.
** עבודה -
אם כן, קצת מעניין מה שהיו אמוראים (חולין) שלא רצו לקבל מתנות כהונה. יש לדון אם אף תרומה לא רצו (שאולי יש כן רק לתרומה. לא נראה כן ממקורו).
** כי אזלת -
לא מדבר באמירתו. אולי לא הלך, והשיב כן בעצמו לאביו. ותחשב.
** שמוציאו -
מעניין שזה תיקון, שכבר התיר ה’ את שבע מצוות. יש לדון מתי התירם.
* עה.
** תשרף -
היה נראה לומר שהוא פרט וכלל (ולכן צריך לפרט להקדימו). אם כן, כשמקשה "התם נמי… ," אומר שיהא כלל ופרט וכלל, ונרבה קצת דברים.
* עו.
** נאכל מחמת -
לשונו משמע שלא רק רצה לומר שאינו קשה לאכלו, אלא שמלח עשה אותו קל לאכול, והוא שהיה המלח מהנה אותו.
** מאן חכים -
ואם תאמר רבא עצמו אמר מימרה שמתירו. אולי רק אמר כן אחר כך. מוזר, שלא אמרו משמו. אולי אף על עצמו חשב להיות חכם.
* עז:
** מילתא -
היה אפשר לומר אז שלכן יודע שלא בא רק לזה.
=SUM(B3:H3)
** דלא כרבי יהושע -
נראה, אולי, שזה קשה לגמרא מפני שמשנה שבא אחריו נסתם להיפך (עיין תוס’ בבא בתרא קכב בכעיין זה). ותח’. (ועיין לקמן, שרש"י על אותו משנה משמע שאינו דווקא ר"י, אלא תנא רק חש לרבי יהושע. נראה שעדיין יהא כמזכיר מחלקת, ויהא בעיא אם נסתם שלא כמותוU+002e
* עח:
** דאי ממשכי -
נראה שהוא על פי "כל הראוי לבילה… ”
* עט:
** ראב"מ -
מעניין, שאינו יחיד שמכריע, אלא כל הציבור. וצריך לומר שר"ל שאין חילוק יחיד גורם הכרע.
** לפי שאין -
קשה למה אין זה סיבה אם הוא מחצה ומחצה.
* פב:
** אבל נטמא -
לא הבנתי, שאם אין הל"מ עליו, אז, אף בלי פירכא לא היה נלמד (שאין לומדים מהלכה), ואי נכתב, אז, אין צריכים קרא. אולי הלכה אומר דבר שהוא vague, כמו, “כל פסול חשוב,” או כעין זה. ותחשב.
* פה.
** לא תעשה -
צריך ביאור למה זה מכריח שאין לאו; עובר בחצי שיעור.
* פה:
** שבת -
יש לדון למה צריך לימוד משבת. לכאורה, אין קרא שמרבה אותו בשבת, אלא ידוע הוא, לכאורה, ממה שזה ביאור של מילת "הוצאה.” (ואין לומר שהוא הלכה למשה מסיני, שאז אי אפשר ללמד ממנו.) אם כן, נאמר כן כאן גם כן. נראה שני דרכים:
1. אפשר שאין הכי נמי, נלמד כאן ממשמעות לשון יציאה, וגמרא רק מביא סמך שכן הוא המשמעות מדיני שבת.
2. אפשר שיש סיבה בשבת שלא שייך כאן, ואי אפשר ללמדו, ולא לומדו במה מצינו או כדומה, אלא מילת הוצאה הוא לימוד ממש שמקישם ומדמה אותם.
ועיין ברשי, שמשמע שדורש מכאן למעט שנים שעשוהו. יש לדון, ששם שפיר קרה יציאה (ועוד שאם כן, קושיית גמרא קשה אף בהוה אמינא). ותחשב. אולי לתרץ שנים אלו, יש לומר שרש"י סןבר שמקור של שנים שעשוהו גם כן נצרך למעט חצי מלאכה (דהיינו, שמלמד שאסרה תורה מעשה שלם)ץ ותחשב ותבין.
** נקנור -
הק’ לי א.מ.ו. שבוודאי יהיה מקום הבדל, ויכול לתת את ידיו שם (למשל, היה אפשר ליתן את ידיו בשערים). אולי אף אי נתקדשו שערים, אינם כשרים לדם. ויל"ד למה לא. ותחשב. (ונראה שאולי יש לדון למה יהיו קדושים, אם הוא מפני שהם חלק מעזרה כמו שדרום עזרה חלק ממנו או אם הוא מפני שמשמשים את העזרה. אם נאמר כשני, אולי אין קדושתו כקדושת שאר העזרה, ואולי אינו כשר לטהרת מצורע. ותו"ת. כמו כ ן נראה שאפשר שקדוש כיון שהוא “חד מקום” עם העזרה. נראה שאולי כן משמע- ויש לדחות בקל- מדמין לתפלה, ששם דן מה נחשב חד מקום. היה אפשר לדחות שזה רק סימן למה נתקדש. ותו"ת.)
** וכן לתפלה -
לכאורה, הוא דומה לשערי עזרה, שאין סברה של מצורעים. קצת מוזר למה לא פירש מהו הדין כאן קודם שאומר ששייך במקומות אחרים כיון שצריך לדעת לאיזה דין נדמה. ותו"ת.
* פו.
** חמורה -
יש לדון מה רצה לומר:
1. אולי זה מגלה שזה חמור יותר לכנס בו. יש לדון, שלכאורה, סיבת החילוק אינו בחומרתם, אלא במה שצריכים.
2. אולי זה סיבה למה יותר חמור לכנס לזה מלזה, שזה "נתחלל" יותר. ויש לדון.
3. אולי הוא חמור במה שאין נכנסים כל כך, ולא אומר דין, ור"ל שהוא חמור במה שחילולו לא קורה כל כך.
* פו:
** כריסי רחבה -
יש לציין לגמרא יבמות (קה) שאומר שם שהיה ריב"י גדול.
* פז:
** שמתוקה -
נראה שהוא על שם מה שאומר גמרא (תענית ה:) גבי רחב, והוא שאף היא כן, שהאומר שמה (בפיו) היה מתוק, שהיה נהנה עד שהיה (עכ"פ, גבי רחב) נעשה בעל קרי.
** לא היה לך -
קשה, שקרא אומר בפירוש ש"לא כן עבדי משה [שהיה חלוק ולכן היה צריך לפרוש מן האשה, מפני ש]פה אל פה אדבר בו." אם כן, בוודאי לא היה לו ללמוד ממשה.
** שמים וארץ -
מעניין שמחשיבו קנין אחד.
* פז.
** במקום -
נמצא שאין הרישא כסיפא, שרישא הוא כשלא אמר כלום, וסיפא הוא כשפירש. ואולי על פי דין, הוא כמה שרגיל, שכיון שצריך לאמר, מסתבר שאמרה. ותחשב.
* פז:
** מפני ששיגרן -
רצה לומר כדי לשגרם…
* פח.
** אשתו -
חושב אני שיש ברייתא כעין זה בעירובין.
** פורחות -
יש לציין לגמרא שאומר כעין זה על ר"ח בן תרדיון. ותחשב. (ונראה שאולי לא ראה ממש אותיות פורחות, אלא שאמר שהבין דמיון ללוחות. ותו"ת.)
** עולא -
קשה, אז, על מה שאמר שאלו היו סיבה למה שנשלחים לבבל. אפשר שר"ל שבא להם יותר זכויות כיון שהוא כל כך קשה לעסוק בתורה. גם אפשר שאמר כן קודם שבא לבבל, ושוב חוזר בו. קשה, שמשמע שלא ידע כמה זולים היו קודם שבא לבבל. אולי אמר בין לקיחתו לאותו לילה. גם יש לומר שידע שהיו בזול, אבל לא ישע כמה היו בזול.
** ועסקי -
צריך ביאור מהו התמיהה; אולי לא קנו. יש לומר שלא היו רעים אם לא היה צורך לעסוק בתורה (שאז צריך גוף נקי). זה לא נראה. יותר נראה שממה שהיה יכול למכרם כלל, רואים שלא היה כל כך מזון טוב בבבל. ותחשב.
* פח:
** מלך -
יש לציין למעשה שחלקו על אי גדי או עז יותר טוב. ותחשב.
** לכו ושאולו -
זה מעניין, שרואים ש"הכל כפוף לאשתו" ואף מלך. לאידך גיסא, עיין בשיח שי על רש"י על זה.
** חייבין -
יש להעיר שכל אחד יכול לאכול, שיש רק ספק, ומותר מדאו’ (אולי). ותחשב. ויש לדון למה אין הולכים בתר רב. ותחשב.
** לא הבנתי
למה אי אפשר להם להתנות לפסח שני. ותחשב.
** וריחשה -
מעניין שאין חוששים שהוא רק כפירכוס של זנב הלטאה שמת. ואולי אין דרכו להתחיל לפרכסה כשנותן מים עליו, ורק דרכו לחיות. ותו"ת.
** קמי שמיא -
צריך לדון מה סברה זה; הרי יש מה שמונע אכילתו, והוא מה שאינו יודע. מה לנו, אז, שיש אחר- שמים- שיודע. כיון שהוא לא יודע, נשאר הבעיה. ודע שבני אדם מדרהרים כזה (הוא מה שאומרים כמה פעמים: "בעצם, there’s no problem; it’s only a technical problem” וצריך לחשוב מה זה אומר.
* פט.
** כדי לזרזן -
אין זה עיקר התירוץ; התירוץ הוא שלא היה התנאי דווקא. אם כן, קשה למה אמרו. על זה משיב שהיה רק לזרז. ותו"ת.
** מאי קמ"ל -
רצה לומר מאי קמ"ל לעולם. ויש גורסים כן בפירוש.
* פט:
** מאה -
לכאורה, אין זה נכון, שהרי רבינא רק אכל כפול של ר"פ.
** איתיביה בני חבורה -
מוזר שיקשה לו מדיון מסיפא ולא מרישא. ונראה שרק ציין לאותו ברייתא, ולא ידע ר"פ סיפא של הברייתא. עדיין קשה למה יקשה מכל הקודמים, ולא מברייתא זה.
* צ:
** מדרבנן -
לא הבנתי למה לא אמר ש"חוששיים" שאומר רק עושה שאינו עומד לזה, ומחוסר יותר מטבול יום. אז, אינו ראוי בשעת שחיטה. ותחשב. אולי רק מדייק מלשון "חוששים," שאולי הוא לשון שנאמר בדרך כלל עם דיני דרבנן. ותחשב.
** קמ"ל כדר"ש -
לכאורה, משמע שלא ידע הא דר"ש לפני כן (רצה לומר שאילו היה ידוע לא היה חידוש). יש לדון, שעדיין יש מה שאינו בידו. משמע שאין ענין של מה שאינו בידו אלא שאינו כל כך likely ליעשות. כאן, שהוא likely, אין מעלה במה שהוא בידו. זה מעניין. ותחשב.
* צא.
** אפשר -
אם כן, לא רק שאז דין משנה נכון, אלא שאף לא יצטרך שיבטיחו אותו. ואולי רק ספק הוא אם יאכיל אותו, ואז כאן רק מצטרף לספק ספיקא. ותחשב.
** בית פאגי -
זה, לכאורה, מוכיח מהו. חושב אני ששמעתי שחולקים ראשונים בזה. ועיין במנחות.
** חבורה -
צריך ביאור למה נחלק בין חבורת נשים לאשה אחת. ותו"ת.
* צא:
** אלא אימא -
קצת קשה, שמצינו כמה פעמים שגמרא יאמר ש"ארישא קאי,” ולמה צריך כאן להפך את הסדר. ויש לדון. ואולי לא ממש מהפכו, אלא אומר שכן רצה לומר, ואם כן שניהם שווים.
* צב.
** העמידו -
צריך לבאר מהו החילוק.
* צג.
** לא מתקן -
יש לדון איך זה יהיה, שלכאורה, תשלומיו רצה לומר שאמה שהיה צורך לו לעשות ביום פסח עכשיו נעשה בפסח שני. אם כן, אין סיבה לכרת, שקיים מצוותו. ויש לומר שלא קיימו כל כך. גם נראה שיש לומר שיש ס"ר וס"ט בפסח (כשלא קיימו, בטל ס"ט ועשה ס"ר), ותשלומים רק עושה ס"ט. זה אומר שיש יותר משאר עשיים, ששם יש איסור ביטול רק מפני ס"ר הבאים ממה שלא עשה ס"ט. אם כן, צריך לדון מה בין זה ללאו. ואולי אין חילוק חוץ מלשון ציוויו (ואולי זה חשוב). ותחשב.
** מעניין שאין
פסח נחשב עשה הניתק לעשה ונפטר מחמת זה. אולי היה נחשב כן, אלא שבפירוש אמרה תורה שחייב. ויל"ד, שאולי הוה אמינא שזה רק כשביטל עשה. אם כן, לא יצטרך קרא לרחב"ע. ותחשב. וצריך לחשוב אם יהיה עשה חלוק מלאו.)
* צג:
אמר ליה ר"י- יש לדון למי אמרו:
1. אולי אמר לר"ע, והיה מקשה לו. לא משמע כן, שהיה ר"ע רבי, ולא היה מקשה עליו בלשון זה, לכאורה. ויש לדון, שאולי לשונו דומה ללשון שאומר גמרא קידושין שיאמר כשטועה (“כך כתוב… ").
2. אולי אומר לר"א, לסמך לו. יש לדון מי אמר מימרא זה:
  1. רבי אליעזר. אם כן, צד זה לא נראה, שהיה רב של רבו של רבי יוסי, ולא רק מסתמא אינו כבוד להביא סמך לו, אלא לכאורה, לא דבר עמו, שמת קודם אף רבי יהושע
  2. רבי אלעזר. זה נראה, שהיה , עמו, תלמיד רבי עקיבא.
ראיתי במשניות שכתוב "רבי אליעזר.” אז, ק"ק. (ועיין לקמן בגמרא (צד:) שלכאורה, מבואר שהוא רבי אליעזר.)
** לטהור -
נראה שהענין הוא שאף ששניהם גורמים אותו בעיה, גורמו בפסולים אחרים. ותחשב.
* צד.
** סומכא דרקיעא -
יש לדון מה זה. אם העולם אינו כדור, אולי חשבו שבסוף יום, ירד חמה לסוף קרקע ולן שם.[fn:1] יש לדון, שעדיין בסוף ים, ייראה קצת. ואולי סובר שיש הרים בין חמה לנו. ועדוון קשה למה לא ישרף אותו חלק קרקע. ואולי שרפו. גם קשה איך חוזר למזרח. ואולי סברו שנס הוא. (אין לתרץ שחווזר ומגלגל תחתיו, שאם כן, אינו עובי שמים, אלא אף ארץ). גם אפשר לומר שבלילה לא הולך למטה, אלא למעלה (עיין גמרא לקמן). אם כן, מה שסובב הוא הרקיע, ודנים בעביו. ויש לדון, שלא נראה כן כלל בעינינו.
אם העולם הוא ככדור, אז יותר צריך ביאור. נראה שאז, יש לומר שהוא עובי הגלגל. נקרא עובי רקיע רק כיון שאף אותו מקום נחשב רקיע (שרוקע על הדרים על אותו חלק (וזה אי אפשר לומר אם אינו גלגל)). אז, רצה לומר שהוא רקיע של עובי קרקע. ודחוק.
** ואין יכול -
קשה איך חייב, שנאנס. ואולי רצה לומר שחייב לשלוח מי שיכול. ותחשב.
** תדע שחמה -
לא הבנתי, שאינו אותו שעה בכל העולם. ותחשב. ויש לדון מה בכלל יישוב. (ועיין ברשי ד”ה תחת כוכב).
* צד:
** נראים -
קצת קשה, אז, למה לא אומרים כמותם. ואולי רצה לומר שנראה כמותם מסברה, אבל יש לנו מקור מתורה. ויל"ד.
** ב
ית פאגי- זה, לכאורה, מוכיח מהו. חושב אני ששמעתי שחולקים ראשונים בזה. ועיין במנחות.
חבורה- צריך ביאור למה נחלק בין חבורת נשים לאשה אחת. ותו"ת.
בן בנו- עיין רש"י. כמו כן מצינו בסוטה יג.
* צו.
** זה -
קצת קשה למה לא דורשו למעט פסח שני או כמו כן. ותחשב. שו"ר ברשי.
* צו:
** חצות -
יש לדון למה לא נאמר שהוא הוכשר ליקרב אם היה שם בעת שחיטה. ואולי יש מה שקורה בשעת חצות. לא נראה, שאף זה היה בעולם אז. אולי רק קורה אם עומד ליקרב. ותחשב.
* צז.
** תיובתא -
ואין לומר שהוא אסמכתא, שאין דרשה אחרת.
** תיובתא דרבא -
יש לדון למה אין זה אחד מן היע"ל קג"ם. ואולי אביי לא חלק מסברה, ורק מפני הברייתא שידע. אם כן, בכל זמן שהוא כן, אין בהכרח הלכה כרבא. זה מחודש. נראה שאולי יהיה כלל זה קיים אם ידע רבא את הברייתא, ולא סבר שהוא ראיה, שאז יש חילוק דעות. ותחשב.
* צט:
** מאי
איריא- יש לציין לגמרא לעיל (לו) שאמר שאומר פסח במקום יום טוב כיון ששם הוה קאי. אולי רק ברייתות, ולא משניות, יעשו כן.
** חיובא דמצה -
ואם תאמר יש חיוב אף בשבת. ויש לומר שאינו מדאורייתא. עדיין קשה, שיש חיוב בסוכות. ואולי אין צריכים כל כך שובע לזה. ויש לדון.
* קה.
** כך קובעת -
משמע שאיסור טעימה הוא מפני קביעותו. משמע שהרע של אכילה קודם קידוש הוא שאוכל אז סעודת שבת. ותחשב. ויש להעיר שאומר גמרא שנחשב סעודת שבת. הנחנו על פי לשון זה שהענין הוא שאינו רק סתם סעודה, אלא הוא סעודת שבת. מדמיון למעשר יותר נראה שרק אומר שנעשה סעודה, וממילה הוא סעודת שבת. אם כן, אולי הענין הוא שצריך לזה, שאין הפסק חוץ מאכילה חשובה, דהיינו סעודה. ועדיין לשון סעודת שבת מוזר.
** דאי -
לכאורה, זה מוכיח ש"דאי" אינו מפני שלא רוצה לומר ציור שיש בו איסור, שכאן יכול להיות שנאנס. אלא הוא שלא רצה לומר ציור שאינו כל כך מצוי. ויש לדון, שאולי לא רצה לומר ציור שיש בו איסור, אף אם נעשה באונס. ויל"ד.
* קז:
** ירקי -
יש לציין לגמרא שבת (קמ) על ירקי.
** נירו -
ואם תאמר מה לנו שמצער; כיון שאינו משביע, אף שאין צער יהיה מותר. ואולי היה לנו לגזור לא פלוג אלא אם כן יש לו צער (או שיש טוב אחר, כמו שמגרר גריר). נראה שזה הוכחת רבא שיין גריר, ולא רק שלא משביע.
* קח.
** משום פסחא -
זה, לכאורה, מוכיח שנוהג אף בזמן הזה. אם כן, רשב"ם שכתב לעיל צד נגד זה קשה. ואולי גמרא רצה לכלל זה באחד מן ההנחות שצריך להניח. ודחוק, שלא מזכירו.
** כשהוא מיסב יצא -
משמע שהסיבה מעכב. ותחשב. ואולי אומר שקיים מצוות הסיבה, ומחדש שיש מצווה לו.
* קי.
** לצאת -
ואם תאמר אם כן, היה לנו לתרץ כן לשתיית פסח. ויש לומר שיש לחוש שיצא או שיצא לבית הכסא או כדומה. גם יש לדון שנחוש לאדם חשוב.
** חד מצווה -
קצת צריך לחשוב מה עושהו חד מצווה. ותחשב. ונראה שהוא שמה שמראה חירות ומקיים סיבה הוא מה שיש ארבעתם.
** ארבע -
צריך ביאור למה לא חשש לכשפים.
** ארבע -
קשה, שבין כך ובין כך אין חשש, כיון שהם אורחים (כמבואר לקמן).
** דבר אחר -
קשה, נפשוט ממעשה של בעל ראשון שהוזק שזה הדבר אחר. אולי לא דן בכשפים בזה, אלא במזיקים. גם יש לומר ששאני אותו איש כיון שקפד כל כך.
* קיב.
** ואי לא -
עיין ברשי בשבת שדן מהו "ואי לא.” לכאורה, כאן צריך להיות כצד שהוא שאינו אפשר לו, שלכאורה, לא יוכל לדעת אם מהני או לא. ותחשב. (ולכאורה, אין זה קשה, שיכול להיות כזה כאן וכזה כאן.)
** שברירי -
נראה שזה מקור ל"נ נח נחמ נחמן… ," והוא שעל ידי שממעט אותיות מרחיקו, ואז על ידי ריבוי אותיות יביאו. (וקצת מסתבר כן, שהוא הולך ונתמעט עד שאינו שם, וכמו כן, נתגדל עד שכולו שם.)
* קיב:
** אל תבריח -
ואם תאמר אסור הוא כיון דדינא דמלכותא… ויש לומר כעין מה שאומר גמרא בסוף בבא קמא.
** מעין פתוח -
משמע שיש אותו סיבה לדם בשניהם. ותו"ת.
* קיד.
** קקלי -
ק"ק, שגמ’ בשבת (קמ) אומר שאין לאכול ירקות. ואולי אומר שאף ירקות, כיון שאינם כל כך רע כבשר, הם כן. ודחוק.
* קטז.
** אי הכי מאי -
עיין בגירסת משנתינו, שהוא כצד שני כאן. מוזר, ותחשב.
** אפשר -
קשה, שאז יאמר שכבר אמרוהו במצרים כששחטו שם את פסחיהם. ואולי לאותו סיבה שאין אומרים אותו בשאר מצוות, לא אמרוהו, ואולי נשנה אחר יציאת מצרים.
** פסל -
יש לדון, שהרי היה לו פסל אף בירדן (“הללו עובדי עבודה זרה… "). ואולי לא היו רבים מבני ישראל עובדים אותו. לא משמע כן לשון "הללו עובדי… " כל כך.
* קיז:
** כל חד וחד -
יש לדון למה אין במה שעושה בעיה של עשיית מצוות חבילות חבילות. ותחשב.
** דרך חירות -
לשון זה, לכאורה, מיותר. ונראה שכיון שאומר שאינו נצרך מחמת ברכת המזון, אומר מחמת מה חייב. ותו"ת.
* קיח.
** קשין -
מוזר, אז, מה שחווה, שהיתה החוטא, נענש במה שהוא יותר קל מעונש אדם. ואולי רק רצה לומר שקשים כן לה’, אבל לא לאיש או אשה. לא משמע כן מקראי שמביא.
** רב נמחן בר יצחק אמר -
עיין לעיל, שחלקו תנאים בזה.
** אינו מקפח שכר -
משמע שיש למלאכים שכר. ועיין במקום אחר שהיה לנו ראיה (מגמרא בגיטין דאשמדאי) שיש לשדים שכר.
* קיח:
** כסבור אינו מקבל -
יש לדון אם אומר שכן סובר משיח או שכן סוברים מצרים. אם כן סוברים משיח, ק"ק איך לא ידע גמרא זה. אם כן סוברים מצרים, יש לדון למה מביאים אותו. ויש לדון.
* קיט:
** במותו -
עיין בספר התמונה (הובא בילקוט ראובני, והוא מיוחס לחבי נחוניא בן הקנה ור"י כהן גדול) שאומר שהיה משה נקבר במערת מכפלה (ממלאכים).
** שעתידה -
משמע, לכאורה, שיש ס"ר, שאי לאו הכי, קשה מה לנו בזה.
** שמואל -
לכאורה, לא חולק על ר"י. ויל"ד, שאולי רק אומר שאסור לאכול דבר חשוב.
* קכ.
** אומרים צד
שמרור הוא רק דין במרור. דין מומר לא משמע כן. ותחשב.
* Footnotes
[fn:1] כעין זה:
