* סז.
** אלא לעולם -
לחומרא- מעניין מה שמחשיבו לחומרא. עיין ביבמות (ח.) כעין זה.
** נתקו -
עונש אחר- משמע כמה שכותב במקום אחר (עיין בשיח שי במקום אחר (סוף חולין?) שדן בזה), שאומר שזה, ולא דבר אחר עונשו.
* עא.
** הכי קשיא ליה -
משמע שאין הפשט שדן גמרא מה הקשה, אלא שידוע שהקשה, וכיון שהיה קשה לו לטעם אחר, הקשה מה שאינו קשה. צריך ביאור.
* עג.
** ר"א -
כל צדדיו- כמו כן היה ר"א משווה ביבמות קח. מעניין.
* עד.
** רבי ישמעאל -
קשה אך צד שני יפרש גמרא בברכות. אם יפרשנו כצד ראשון, קצת קשה (ויש לדון) למה לא מפרש כן כאן.
* עה:
** אמר לך -
משמע שכלל זה קיים אף אי יש עוד חולקים עם רבא ואביי. ותחשב. וזה מראה מקום.
** בין -
אירע- ואם תומר למה לא יכפר אחריו אם לובשו אחריו. ויש לומר שאין הכי נמי, יכפר, אלא שכבר דחוייה. יש לדון שבידו להכשירו.
* עח:
** הורצה -
לכאורה, יש גם כן נפקא מינא שיקריב אימורים.
* פ.
** רב הונא -
צריך ביאור מה לנו בזה; הרי עדיין אינם רב. נראה שענין רב הוא שיהא עיקר קרבן פסח בראשון. אם רק טמאים הקריבו אז, אינו העיקר. יש לדון, שיודעים שיש ס"ר שנעשו אז, אבל לא יודעים שיש פחות ס"ט. ויש לדון. ואולי יודע גמרא שאין כל כך ס"ט או שס"ר ממעט ס"ט. ותחשב.
* פא:
** נטמא -
בירה- שם מחלקת הוא.
* פה:
** אינה מפסק -
נראה שהסברה הוא שאין מחיצה חשוב לענין תפלה כיון שתפלה תלוי בראיית ה’. אז, מה שיש מחיצה ביניהם אינו הפסק, שמשהו בעלמא יש ביניהם. ודע שיש לדון, שכל מצווה הוא לעשות נחת רוח לה’, ואז נאמר כן על הכל. ואולי זה יותר דיירקט (המעשה כולל בו מה שהדברים לה’)ץ ותחשב.
* פו:
** תלמוד לומר -
אינקלוס- קשה איך החולק יבאר את אונקלוס; אטו יאמר שלא היה נכון. ותחשב.
* פח.
** יש ברירה -
זה מחודש, שלולי רש"י, הייתי אומר שברירה רצה לומר שהיה לו דעת בחפץ מיוחד, ונתברר שזהו אותו חפץ. מרש"י לא משמע כן, שמשמע שנתגלה שאילו ידע היה רוצה. צריך לפרש איך מה שאומר רש"י שאין ברירה הוא שמניחים שחשב על חפץ מיוחד (שהניח שיהיה נברר) הוא קנטרס"ט. (יש כמה דיבורים של רש"י שאומרים כן (במקום אחר בשיח שי הבאנו זה. יש רש"י שאומר כן על ע"ב.) ואולי רצה לומר שמניחים שלא רק שינה הבירור, אלא אף שינה דבר בדעתו, ומה שרצה כן עכשיו אינו גילוי שכן היה רוצה לפני זמן. ויש לדון, שלא משמע לשונו כן כל כך. ותחשב.[fn:1]
שוב חשבתי יותר על אותו גמרא, ואינו ברור לי כלל. ראשון, יש לדון בדעת מי דנים. לכאורה, אין לקטן דעת, ולא צריך דעת להימנות. אז, לכאורה, דנים בדעת אפיטרופוס. לכאורה, כל אחד חושב ששוחט עליו, אבל רק אם הוא ירצה בו. אז, הוא יותר כעין תנאי (כמו שאומר גמרא גיטין (כה:)). על כל פנים, אולי רש"י אומר שתלוי במה שהיה רוצה אילו הודיעו אותו רק מפני שלא יודע אז כלל ששחטו אותו, ואז אינו רוצה כלום עכשיו. אז, תלוי רק במה היה רוצה אם אמרו לו. ותחשב. ועיין בחבורה שכתבתי בזה. וצריך ביאור,שחשבתי על נקודה זה, ולכאורה, יש בו ממש. ותחשב עוד.
עדיין אין כל זה כל כך ברור לי, שלכאורה, לא יהיה תלוי במה שרוצה אז, אלא במה שירצה לאחר זמן. ותחשב.
ודע שעדיין מוזר להניח שלא ידע קטן שיש שני אפוטרפסים לו (ויש לדון, שאולי מניח שלא ישחטו שניהם עליו, שלמה צריכים לכך. ויש לדון.). אז, קצת משמע שיש יותר ב”אילו הודיעוהו,” שבין כך ובין כך, פשט שכתבנו צריך קצת עזרה. ותחשב. אז, לכאורה, נראה שתולה רש"י במה שהיה רוצה התינוק אילו ידע שהיה רוצה לאחר זמן. קשה למה יהיה תלוי בזה. נראה שאולי רש"י סובר שמה שאין ברירה הוא מפני שחוששים שחשב על מה יקרה, ולא היה נכון. אפשר שאומרים שמה שחשב לא מהני, שהוא טעות, שאילו ידע מה יקרה, כך היה חושב. אז, אותו כך נחשב דעתו, ועל אותו דבר חל החלות. מרש"י זה היה נראה כן. ותחשב.
** מלכה -
משמע שאילו אשתו של אדם אינה בקיאה וחכמה, אין צורך לשאלה על הכל…  (ועיין במש"כ בשיח שי).
* פט.
** מהוויתה -
יש לדון מהו דרשה זה אולי רצה לומר שצריך להיות שמה שמהווה אותו- דהיינו, דמו, שנקרא נפשו, הוא בעולם. יש לדון, שאף לאחר זריקה הוא בעולם. על כל פנים רש"י בוודאי לא אומר כן. יש לדון מה אומר רש"י. אולי רצה לומר שיש לו כל זמן שיש צורך לשה להיות בעולם. יש לדון, שיש מצוות אכילה. צ"ל שכיון שלא מעכב, לא דן בו. גם יש לומר שהוא נחשב עדיין שם כיון שעושה תוצאות. ויל"ד.
* פט:
** לאטריחינן -
משמע שעיקר התירוץ הוא שאין מה להוכיח שמחלו. לולי רש"י, היה מצי לומר שר"ל שמינוהו שמש, ואז הוה כהתנו (אף שלא התנו ממש, על כל פנים גילו דעת שכן רצה). ואולי לשון גמרא לא משמע כן כל כך.
** אפשר -
מעניין איך מפרשו. ותחשב.
* צא.
** בית האסורים -
שמעתי שיש אומרים שהיה כח לבית דין או למלך לענש על ידי בית איסורים או כדומה, ואף אי לא נמצא חייב, שקשה לחייב על פי דיני בית דין. רש"י זה, שלא מזכיר ציור זה (שלכאורה, היה מצוי), משמע שאינו כן. אם כן, מעניין איך יוכלו לחיות, כיון שהיה כל כך קשה לחייב בני אדם. ויל"ד. (ואפשר שסבר רש"י שהיו בית איסורים כזה, והיו של מלך, ולא היה מלך לעולם ירא שמים, ואז, אין להאמינו. ויל"ד, שלא מביא ממה שבית דין נאמנים, אלא ממה שבני ישראל נאמנים. אולי לאו דווקא. דחוק.)
* צג:
** בשעת אכילה -
לר"א- רצה לומר ראב"ע (ובדרך כלל, נקרא על שם אביו).
** תחת כוכב -
לא הבנתי הראיה מזה, שאולי אינו תחת עוד כוכבים. ותחשב. ונראה שעולם רצה לומר לא רק Earth, אלא עולם ממש, ויישוב רצה לומר Earth (זה אינו מוכרח, שיכול להיות שהוא רק מקום שבו יש יישוב).
** בין עגלה -
קשה, אם כן, למה לא אומר יותר ספסיפיק. ואולי אינו לעולם בחד מקום.
* צד.
** וכן בין -
לולי רשי, היה אפשר לומר שקושיית גמרא מכאן הוא שרואים שעובי רקיע גדול מאד. ויש לדון מהו עוביו . (ועיין בשיח שי).
** וכן -
עיין במש"כ במקום ארץ. עיין במקום אחר שחשבנו, אז, גודל ארץ (נמצא שהוא כמו 4.15 מיליון מייל. זה, לכאורה, אינו נכון.)
* צה:
** לא תשחט -
הוה אמינא- יש לדון אם זה מפני שיש סיבה יותר חזק או שיש סיבה חלוקה. ותחשב. (נראה שהוא חלוקה, ממה שיש איסור חמץ אף אי אין קרבן פסח. ואולי הק’ פסח רק מרבה אותם סיבות עצמם. ותחשב.)
** אפשר -
קשה, שיש הרבה מצוות שעושים בלי הלל (ואולי היה צריך אם אינו כבל זמן. זה אומר שהלל הוא דבר שאינו כל כך חשוב אם נאמר לעולם. אז, אף אי יש סיבה לאמרו על כל מצווה, אי אפשר לאמרו אלא על מצווה שנעשה לזמן בהכרח. ויש לדון.) ודע שלולי רש"י, היה אפשר לומר שלא רצה לומר שפשוט להודות ולהלל כיון שהוא מצווה, אלא מפני שהוא זכרון לנס. ותחשב.
* צח.
** ושמע -
ותמיהה- לא הבנתי למה אין לחלק שזה נפסל ממה שהיה נתקדש לו, וזה רק לא היה נצרך. ותחשב.
* צח:
** אם -
אסור- לשון זה מעניין, שלכאורה, רק פסול הוא (ויש, באמת, איסור לפסול קרבן, אבל זה רק תוצאה שלא שייך כל כך לכאן). ותחשב.
* ק.
** אלא פורס מפה (רשבם) -
על מאכל- יש לדון אם זה חולק על רש"י, שאומר שהוא על השלחן. ותחשב.
* קב.
** להודיעך -
עיין רש"י ריש ביצה שמבאר למה כח של היתר עדיף. נראה שחולק רשב"ם על זה, שאם סובר כן, אז פשוט לומר ששיטת רבי יהודה הוא החידוש, שספק ברכות להקל. צריך ביאור למה, אז, כוח היתר עדיף. ותחשב.
* קג:
** לא עקר -
ריבוי לשון שלא לצורך- כתב לשון כזה בב"ב. ודע שזה עצמו ריבוי לשון. ותו"ת.
* קה:
** ומי אמרינן (רשבם) -
רצה לומר, שהניחא שיש מקור לאמרו בדרך כלל, אבל אין מקור לאומרו בציור זה. ויש לדון למה נחלק.
* קו.
** קידושא רבא -
גם היה אפשר לומר שנקרא כן בלשון סגי נהור.
* קז.
** אדור -
הפרה- לכאורה, רצה לומר היתר, שהפרה הוא לשון של הפרת בעל. זה לא שייך כאן.
** שמעת
(רשבם)- יש לדון למה זה פשוט, שאולי הוה אמינא שהוא ברכה לבטלה.
* קח.
** ארבע -
קשה, שלעיל אמר שהם כנגד ארבע לשונות של גאולה.
** בין שלשי
(רשב"ם)- ירושלמי- נמצא שהיה רגיל להשתכר בשלש כוסות (ואולי רק רצה לומר שמי שמשתכר בארבע לכאורה ישתכר בשלש). ועיין לקמן שאומר שהיה רבא משקה תלמידיו ארבע. ואולי היו בתוך סעודה.
שוב הבנתי שמרשבם (קיז) משמע שלא מניח שנשתכרו על שלש כוסות, אלא ששתו בסעודה.
** אשה -
נשי- משמע שהוא מפני שהיא אשה, ולא מפני שכפופה לבעלה. לא משמע כן מגמרא.
* קח:
** שאף הן -
עיין ברשי מגילה, שלא אומר כן. וצריך ביאור.
** אמתא
(תוס’)- עיין במה שגריס. נראה שהבעיא הוא שלא נכנס באותו רוחב. עיין בגמרא סוכה שאומר דלא כזה. גם קשה למה לא אומרים שאף אי נכנס, יהיה כל כך קרוב לכותל עד שלא יגע מים.
ודע שבאמת היה יכול לגמרא להקשות (וזה ק’ על גמרא) קושיא זה על אדם, שהוא אמה על אמה. וצריך ביאור מה יתרץ. ותחשב.
** של פרקים
(רשב"ם)- זה מוכרח נגד תוד"ה אמתא, שהרי משמע שגמרא לא ידע בלי מאמר זה אף על רגליו.
* קי:
** לחוש -
עיין במה שכתב למה אמרום. גם יש לומר שמה שלא מזכירם כיון שמפחד מהם הוא קפידה עליו. ויש לדון.
* קיא.
** דרכא אחרינא -
יש לדון ממה למה (שלא יודעים מאיפה או לאן הולך השד).
* קיא:
** צלה של לבנה -
עיין במה שפירש. ואם תאמר אם כן הוא אף כשאין לבנה כלל. ואולי אין הכי נמי, ורק מרבה שאף כאן, שיש קצת אור, יש לחוש. גם יש לומר שאז, יש יותר מקום לשדים. אז אין כל כך חשש שיבא למקום אחד או שלא יקפידו כל כך אם בא, שיש להם מקום לצאת. ותו"ת.
* קיב.
** ואם -
היה אפשר לומר שלא רצה להגיד את זה, שאם יגלה כן, לא יהא מהני כל כך.
** ארבע -
לכאורה, קשה למה נחשב כממזר, שיכול איש לישא אשה אחרת. ותחשב.
* קיב:
** ולא תגנו -
יש לדון אם היו יהודים שעברו על זה או שהיו גויים, ואומר שלא לנהוג כגויים לגבי זה (ונקט הני גויים כיון שהיו מצויים שם (ויש להעיר שכן בוודאי עושה ב”אל תנסוב גיורתא” ודע שזה נלמד מיותרו. ואולי היה ארמאי. ותחשב. ויל"ד.) (ודע שאף לראשון קשה למה לא לנקט גויים. ואולי אין עושים כל כך ס"ר.)
* קיג.
** בר מחמרא
(רשב"ם)- יש לדון, שיכול ליחרט אם רואה שלא נעשה רע. ואולי יש לתלות שכלי לוקח חלוק משלו.
** מסתמא לאו ברשיעי -
יש לדון למה לא.
** צווה כנען
(רשב"ם)- נראה שכן מוכרח מן היש אומרים שמביא, שלא אומר דבר שציווה, אלא דבר שבו רגילים.
* קיד.
** מטבל -
לא הבנתי, שיחייב לטבל ממש, מחמת שרף של הירק.
* קטז:
** שלש -
שלא פירשו טעמם- זה מעניין. ותחשב. ונראה שמדייק כן ממה שאומר אחריו טעמיהם. ולולי זה, היה אפשר לומר שמבאר למה הם כל כך חשובים עד שמעכבים.
** כן -
וראיה- יש לדון מהיכי תיתי שם שאין חולקים.
* Footnotes
[fn:1] . שוב דברתי עם ר.מ.ש. בזה. אמר לי שאכן, קשה הוא, ואפשר שרק אומר סימן למה היה בדעתו. דחוק הוא, שלכאורה, אין צורך לסימן. (גם דחוק לשונו שנתברר כן, שלעולם אם היינו אומרים כן על שום דבר, אף אם היינו טועים, היה רוצה אותו, וזה יהיה סימן טוב לדעתו. ותו"ת. שוב הבנתי שלכאורה זה קשה בדרך כלל. וצריך ביאור. ותחשב.)
