יש ארבע דינים במשנה:
א. עד אחד נאמן לומר שלא שותה.
ב. עד אחד אומר שלא שותה וע”א אומר ששותה, ר”ח גרס שותה (אבל רק אם בא בבת אחת), ועולא גרס לא שותה.
ג. עד אחד אומר שלא שותה, ושני עדים אומרים ששותה, שותה.
ד. שני עדים אומרים שלא שותה, וע”א אומר ששותה, לא שותה.
חולקים בביאור הדין:
רבי חייא סובר שעד אחד נאמן חוץ מבשני זמנים:
א. אם שני עדים מכחישים אותו.
ב. אם עד אחד מכחיש אותו קודם שנתקבל עדותו.
עולא סובר שעד אחד נאמן חוץ מבזמן אחד:
א. אם שני עדים מכחישים אותו.
ר”נ אומר שבפסולי עדות, הולכים בתר רוב. יש שני לשונות בר”נ; החילוק הוא אם הולכים בתר רוב כשיש שני פסולים נגד אחד כשר או לא הולכים בתר רוב אלא אם כן עד האחד היה גם כן פסול.
נבאר את המשנה לפי ר”ח, לפי צד ראשון:
א. דין זה לא נשתנה; אם יש רק עד אחד, ואף עד פסול, נאמן לומר שלא שותה.
ב. דין זה לא נשתנה, אלא אומר שאם יש עד נגד עד, אם עד שני בא בב”א, שותה. נמצא שבספק, שותה. לא מבאר משנה דין עד אחד כשר נגד עד אחד פסול.
ג. דין זה קשה, שלא צריך שנים, אלא אחד. אז, מפרש גמ’ שמחדש שכשיש שני עדים פסולים נגד העד אחד, שותה. אז, מחדש שני דברים. אולי מחדש שאף שני עדים פסולים נאמנים נגד ע”א כשר, שאין ע”א פסול נגד עד כשר[fn:1]. גם מחדש ששני העדים נאמנים אף בזה אחר זה.[fn:2]
ד. דין זה לא נשתנה; אם שני עדים אומרים שלא שותה, ובב”א ע”א אומר ששותה, לא שותה. דין זה חלוק מאילו היה רק ע”א שאומר שלא תשתה. (יש קצת חידוש שניתוסף, והוא ששני עדים נאמנים אף אם הם פסולים.)
נבאר את המשנה לפי ר"ח, לפי צד שני:
א, ב, וד לא ישתנו. אז, רק נדון בג:
ג. דין זה קשה, שלא צריך שנים, אלא אחד. אז, מפרש גמ’ שמחדש שכשיש שני עדים פסולים נגד העד אחד, שותה. לכאו’, צריך לדון נגד איזה עד אחד הוא. אם נגד עד אחד כשר הוא, אז יש לומר שני החדושים שבארנו לעיל. אם נגד עד אחד פסול הוא, אז אי אפשר לומר שרק שני עדים נאמנים, שעד אחד פסול יהיה כע”א כשר נגד ע”א כשר, ותשתה. גמ’ אומר שהוא בע"א פסול. אז, רש"י מפרש שצריך להיות שהחידוש הוא שאף לאחר זמן שותה.
יש לדון ל"ל יהיה דין זה בשני עדים פסולים נגד ע”א כשר בב”א. לכאו’, נוכל לומר אחד משני צדדים. אולי הוא מפני שאין שני העדים נאמנים, ולא תשתה. קשה ל"ל שכשהוא ע”א נגד ע”א שותה. אז, רואים שבספק שותה. אז, צריך לומר שהוא מפני שאף בע”א שותה, אף שאותו ע”א פסול. נמצא שבע”א פסול נגד ע”א כשר, הולכים אחר הע”א פסול כשאומר לשתות. (ויש לדחות שלא אומרים ציור זה כיון שכבר באר דין ספק.)
נבאר את המשנה לפי עולא, לצד ראשון:
א. דין זה לא נשתנה; אם יש רק עד אחד, ואף עד פסול, נאמן לומר שלא שותה.
ב. דין זה לא נשתנה, אלא שגורס שבע”א נגד עד אחד, לא שותה, שעד ראשון נאמן.
ג. דין זה לא נשתנה, ואומר שאם יש יש ע”א שאומר שלא תשתה, ושני עדים שאומרים שתשתה, שותה. אילו היה רק עד אחד, לא היתה שותה. (למס’, מחדש יותר מזה; מחדש שאף אם שני פסולים אומרים שתשתה, תשתה.)
ד. דין זה קשה, שלא צריך ששנים אומרים שלא תשתה, אלא אף אם אחד אומר שלא תשתה, לא תשתה. אז, מפרש גמ’ שמחדש שאם שני עדים פוסלים אומרים לה שלא לשתות, לא שותה. אבל, אילו היה עד אחד כזה, נגד עד אחר כשר, לא היתה שותה.
נבאר את המשנה לפי עולא, לצד שני:
א,ב, וג לא משתנים כל כך. ד ישתנה ואז נדון בו:
אם שני עדים אומרים שלא תשתה ואחד אומר שתשתה לא שותה. קשה, שאף אם אחד אומר שלא תשתה, לא תשתה. אז, מחדש שאף בפסולים, כשהוא נגד עד פסול, לא שותה. אבל, אם הוא נגד עד כשר, תשתה. נמצא שהוא ספק, והדין בספק הוא שתשתה, כמו שבארנו בר”ח[fn:3]. (היה אפשר לומר שגמ’ מפרש שמשנה הוא אף בספק, ואומר שתשתה, ואין חילוק בין לשון ראשון לשני אלא בדין, אבל לא בפ’ המשנה.)
* Footnotes
[fn:1] יש לדון אם דין זה נכון.
[fn:2] לכאו’, קשה לומר כן, שאז לא צריכים לומר שמבאר דין עדים פסולים, שיכולים לומר שהוא שני עדים כשרים, ומחדש שנאמנים נגד ע”א, אף שבאו אחריו.ודע שאין צורך לחדש השני, שהראשון הוא חידוש שיוצא מכאן.
[fn:3] בר”ח היה יותר פשוט, שהרי כך הוא הציור של ב”א לפי ר”ח, ורח”א ששותה.
