* ב.
** רש"י עד סוף –
ובקריאת פ"ר שאדם קורא – יש לדון מהו חידושו:
א. כדי לקיימו, אין צריך שלש פרשיות, אלא די ב:
אא. פרשה אחת.
בב. פרשה ראשונה.
ב. אפשר שהחידוש הוא שיוצא אף אם מכוון לקריאת שמע דמטה, שאינו מכוון לקיום המצווה, והוא מפני שטובותיה דומה.
** רש"י מצוותן –
עיין במה שפרש"י. יש לדון ביחס בין זמן מצוותן וזמן אכילתן:
א. אולי שניהם סימנים ליסוד אחד, והוא שלאחר שום זמן, נעשה "רע,” וממילא שרעותו גורם שאינו כל כך קדוש, וגם גורם שאסור לאכול.
ב. אולי מצוותו גורם לאיסור שלו, והוא שבדר"כ אסור לאכול בשר של קדשים, אלא שבאכילת קרבן עושה ס"ט (ואולי אף מצטרף להרצאת קרבן), ואז מותר. לאחר יום, אינו זמן מצווה, ועם ביטול המצווה, בא איסור.
ג. אולי איסורו גורם שאין מצווה, שנעשה כעין מהב"ע. ותחשב.
קצת צריך ביאור למה הוצרך רש"י לבאר שכוונתו לזמן אכילה. ותחשב.
** לתני דשחרית –
יש לדון למה. ותחשב. מסתמא, בא מכוח משנה דלקמן. עיין בתוס’.
** להרחיק –
יש לדון מהו ההרחקה:
א. יבוא לפשע, ולאכלו אף לאחר בקר.
ב. יבוא לפשע ולא לאכלו כלל.
נראה כשני, שאי כראשון, הגזרה של שם אינו כל כך שייך לכאן. ויש לדון אם זה בעיה. עיין ברש"י שכ’ כצד ראשון. גם יש להעיר שרק נודע הדין, ומה שהביא אותו כאן מעניין, שאין מקור שהוא כשני, ולא כראשון. ותחשב.
** מילתא אגב אורחיה –
רצה לומר, יודעים שזמן כהנים הוא או בצאת או בהבאת קרבן, מדנחשב זמן קריאת שמע של לילה, צריך להיות הראשון.
** מילתא –
וא"ת דילמא בכהן שאינו מחוסר כיפורים אנו דנים. ויש לומר שאם כן אין חידוש, והוא פשוט.
** מילתא –
כיון שהגענו לזה, יש לומר שלכן הקדים משנה זו, שמראה כמה דינים.
** ממאי –
היה אפשר לומר שאי לאו הכי, אין צריכים לקרא. אולי יש לדחות שיש צד שיאכל בבקר, שהוא בזמן שעומד ליטהר על ידי הקרבת קרבן. עיין ברש"י נגד ת’ שכ’. על פי זה (הצד שצידדנו, שהוא נגד רש"י), נראה לבאר שדיוק גמ’ מ"וטהר" לא (אין זה מוכרח כלל) רצה לומר כמו שאומר רש"י, אלא שיאמר "ויטהר,” שהרי טהרת קרבנות בעתיד הוא לבוא (על פי זה, גם כן, נראה שאלוי אפשר לתרץ ק’ תוד"ה א"כ).)
* ב:
** דילמא ביאת -
קשה, אם כן, מה לנו באמרו שצריך ביאת אור, שיכ’ רק שצ’ הק’ קרבן. ותחשב. באמת, אף למס’ קשה למה צריך שני לשונות. אולי לכן מביא מה שאומרים בני אדם, לבאר את זה.
** עני וכהן –
ואם תאמר אם כן למה לא תני כהן ללמד מילתא אגב אורחיה. יש לומר שרק משניות עושים זה. באמת, יש לחקור מי עשה כן, אם היה רבנים השונים לתלמידים או שהם רק נקטו דוגמא, ורבי, בסידור כל המשניות באופן שיהיה קל להבין ולזכור, נקט ציור שיגלו עוד דינים. עוד יש לומר שאז יכול לתלות סוף זמנו בו.
* ג.
** אמצעתא –
קצת צריך ביאור סימן לשינוי משמרות למ"ל. נראה שני צדדים:
א. אולי מפני שיש שום ענינים בשמים. אז, הוא זמן טוב לדברים, ולכן טוב שידע. ק"ק מאמצעית שבאמצעית. אולי גם זה טוב לדעת, ויש ענין לומר שם תפלות. גי"ל שיש נ"מ לק"ש ואכילת קרבנות. אז, אין חשיבות שלו מה שוהא אמצע של אמצע, אלא מה שהוא אמצע (חצות).
ב. אולי ר"ל שדבר שבשמים, ושינוי שבשמים, גורם אותם דברים כאן. אולי זה גופא מלמד שעושים א (שטוב להתפלל אז).
** למאן דגני –
וא"ת אם כן נאמר כן אף במשמרה ראשונה, בתחילתו. נראה שאינו מצוי שבני אדם יהיו בבית אפל ביום, מה שאין כן בלילה, שרוצים שינה, ואז מצוי הוא.
** למאן דגני –
עיין במש"כ תוס’. לכאו’, היה אפשר לומר שמ"כ גמ’ ל"ד הוא, וכיוון לכל שאר מצוות שזמנן ביום. יש לדון, שאולי רק ק"ש הוא, שזמנו קצר, שיש צדדים שקרא עד הנץ.
** סימן לדבר –
יש לדון למה הוא סימן, אם למשמרות, אם למה שה’ ישאג. עיין לעיל ד"ה אמצעתא. ודע שמוכרח שסימן הוא למשמרות, שאי לאו הכי, אין קושיית הגמ’ קשה.
** מאי קסבר –
לכאו’, שאלה זו לא שייך לקושיית גמ’. אז, קשה למה מביא אותו כאן. אפשר שכיוון בזה לרמז לבריי’ שמז’ תשובה לשניהם. אז, צריך לומר שהמק’ ידע תי’ הגמ’. עוד יש לומר שיש אפשרות לסמנים בעולם רק אם נאמר שיש שלש משרות. אולי רק אז נקבע על פי שאגת ה’.
** אמצעתא –
קשה – סימנים הם, ואז נחזי אנן באיזה זמן באים. הפשטות הוא שיש בכ"א שני דרגות, שמתחיל בזמן אחד וממשיך לזמן אחר. ותחשב.
* ג:
** הוה להו שתי משמרות –
לכאו’, לא רצה לומר משמרות ממש, אלא זמן משמרות, שאי לאו הכי, נמצצא שאין משמרת התכונה אלא חד מן התכונות. עוד, שא"כ נמצא כמה התחלות ותחילות (ר"ל שחד מתחיל מארבע שעות, וחד מתחיל מחצות.)
* ד.
** לאיתעררי –
ר"ז לשיטתו לעיל שסבר שעד כאן היה מתנמנם. ויש לדון, שאולי היה אפשר לומר שהוצרך לעררו מלימוד שלו.
* ד:
** מפני מה לא נאמר –
הפשטות הוא שזה בא אגב הדיון על א"ב של אשרי. אפשר לבאר שבא לתרץ מה שיכול להקשות, ווהא שאין א"ב באשרי, שאין בו נ’. מת’ שיש לזה סיבה (א. קושיה היה שאין בו א"ב, ות’ שיש בו א"ב הטובים. ב. קושיה היה שמה שאין נ’ סימן הוא שאין בו א"ב, שלא הקפיד כ"כ ליתן בו א"ב. ת’ שיש בו, ולסיבה אחרת לא ניתן בו נ’.), ועוד שנ’ מרומז. עוד יש לומר שבא לת’ ק’ גמ’ על ר"א, ואמר שזה יותר טוב מ"אשרי תמימי,” שאין לזה נ’.
** רש"י שלש פעמים –
עיין במש"כ. ופשוט שאינו ר"ל בשלש תפילות (אם לא שלא התפלל כמונו), אלא רצה לומר שכנגד שלש הוא (לכאו’, הוא שכמו שטוב להתפלל שלש פעמים, כך טוב לומר זה שלש פעמים). לולי רש"י, הפשטות הוא שיש שלש זמנים הטוב לו ביותר (רצה לומר, מקומות שבתפילה שאנו אומרים אותו). נראה שסבר רש"י שאין הקנטקסט כל כך חשוב לענין עשיית ענין זו (שאי לאו הכי, היה לו לגמ’ להז’). ואז צריך לומר שיש עוד טעם במנין הזה. ותחשב.
** רש"י אפילו הכי –
יש לדון למה:
א. כיון שרומז לנפילה, כ’ סמיכה.
ב. רצה לרמוז לנ’, אבל לא רצה לאמרו בפירוש.
* ה.
** רש"י זה גמ’ –
עיין במש"כ רשי בקידושין (ל.) ד"ה גמ’, והוא דסברות וטעמי סתימותיהן של משניות, ולתרץם במה שסותרות זו את זו. לכאו’, סתירה היא. יש לומרש סבר רש"י שלא ניתנה משנה בלשונו מסיני, אלא רק דינים וביאורים. לכן, לא היה צורך ועניין לתרץ סתומים וסתירות.
** כל המחלה –
צריך ביאור, שזה בשומע כל מצוות ה’.
** רש"י ושמח –
עיין במש"F. ונראה לבאר יותר על פי מימרת רבא (קידושין לב:) ד"תורה דיליה.” אז, מה שמשבחו ואומר שלא לעזוב אותו עושה חפצו יותר רחוק ממנו.
** אלו אלו –
לכאו’, לא רצה לומר שאם רק אחד מהם ביטול נעשה של אהבה, שא"כ צ’ "ומתורתך" לומר שזה מין אחר של יסורים של אהבה. אז, נראה שבכל (אולי אינו כ"כ רע לדחות) הוא יסורים של אהבה.
** רשי ביד -
עיין במש"כ רשי שג"ר כר"י לא יבא לו יסורים. גם יש לומר שג"ר כר"י לא יראה לבנ"א את ענשיו. ותחשב.
** והא אמר רבי יוחנן –
קשה, שהיה לו להק’ ממימרת "תנא קמא דר"י.”
** בתר גנבתא –
צריך ביאור מאי קאמר. אולי הענין הוא שאז א"א לגנב לקיים ח"ה. אולי אף יש ענין שאסור לחטוף את תשלומיו (והוא שהממון משעובד לו, אבל אינו כ"כ שלו).
* ו.
** יכולה לעמוד –
לכאו’, רצה לומר שאז יהא פחד מהם עד שא"א לעמוד. עוד יש לומר שרואה ר"ל מרגיש (ועדיין מרגישים קצת, כמו שאומר רבא), והענין הוא שיהיו מכבדים עליו ודוחפים אותו. עיין במה שאמר בר קפרא "אילו היה נותן בו דבש, אין אדם יכול לעמוד מפני ריחה.”
** ויראו ממך –
יש לדון אם זה סיבה (נותנים לנו עז במה שגורמים שיראו אחרים ממנו) או סימן (נותנים לנו קדושה גדולה, עד שגויים יראים ממנו (א. מזלם מרגיש בגודל הקדושה. ב. כמו שבהמה ירא מאדם כיון שנברא להנאתו, כך הוא בגוי לבן ישראל, אלא שזה רק בבן ישראל כתקונו. ע"י תפילין, נעשה קצת כזה.)
יש לדון למה נקרא עזו גבי ה’:
א. בד"כ נותן עוז (ר"ל לעיקר לובשיו).
ב. נותן עז, כביכול, לה’. זה אומר כצד שהוא סימן, ואומר שנותן לה’ קדושה, כמו שיש כסא שנותן לה’ יותר רחמים. ותחשב.
** ומי קא משתבח –
צריך ביאור מהו תי’ גמ’ לזה. ותחשב.
* ו:
** ולא מצא בה עשרה –
רצה לומר, לא מצא בה עשרה באים, שהרי, בכל זמן מקדים את העשרה. עוד יש לומר שיש שני דברים שמעוררים שיאת שכינה: א. מה שיבוא עשרה. ב. זמן תפילה. זה מדובר בסיבה שנית לביאה ה’. גם נראה לבאר שנותן הגדרה בכמה זמן שוהה להם. לצד ראשון שכ’, יש לומר שאם כוונתם לבוא התעורר את ה’ לבוא, ושוב נמנע ושהה, כעין מישרגיל לילך ולא הלך, אז נענש. ותחשב. על פי זה, צריך לקרוא "ולא מצא עשרה מיד, כועס.” אף שאין לשון "הוא" כל כך טוב לזה, נמצא דרשה יותר טוב, שאין הוכחה מקרא שכועס מיד, אבל לשון "קראתי ואין עונה" משמע שצ:ל שם בעת שיכולים לשמוע סוף קריאתו ולענות, שהוא מיד. ותחשב.
* ז.
** אין מרצים –
לשון זה מוזר שמגמ’ ומקרא שמביא מוכרח שקאי "כעס" על ה’, אבל הלשון מורה שקאי על ה"אדם.” אולי ר"י בשם ר"י לשיטתו, שסובר שה’ מתפלל, וכן היה ה’ אומר למשה, שצ’ לשהות כדי שה’ יתפלל, שעכשיו א"א , שבחרון אף  הוא. ותחשב.
** צדיק גמור –
אז, “בין צדיק" הוא קרק’ (שמצאנו כ"פ לשון "בר ענוותנא" או כדומה).
** זכה לקלסטר –
כיון שלא ראה פני ה’, נותן לו ג"כ פנים שא"א לאחרים לראות, במדה כנגד מדה.
* ז:
** שמא גרים –
משמע שהשם הוא לא רק סימן, אלא אף קצת סיבה, והוא שמהות של אדם נשתנה קצת עם שמו, וממילא מה שיעשה לו נשתנה. ותחשב.
** ממל’ גוג ומגוג –
יש לדון מה ר"ל:
א. תרבות רע בבית יותר רע למקבל תרבית ממל’ גוג ומגוג הוא לבר מלחמה. צריך לומר שדוד ניבא ע"ש עתיד, שבני אדם ילחמו.
ב. תרבות רע בבית יותר רע ממה שגוג ומגוג רע לכל העולם.
ג. תרבות רע בבית יותר רע לה’ ממל’ גוג ומגוג לה’. צריך לומר שנקרא "צרי" על שם שהם רע לה’. עוד יש לומר שמה שהיו צרו גורמים שהם רע לה’.
** ר"ש בן אבישלום –
נראה אולי שעל שם מה שקילס אבשלום היה נקרא כן (ואולי שינו את השם קצת כדי שלא ייקרא על שם רשע).
* ח.
** דמיא כחיזרא –
עיין בסוטה שבביאור פדגרא, הק’ איך ידע, ות’ שהיה חש ביה או שסוד ה’ ליראיו או שגמרו מרבו (ורבו ידע מאחד משאר הצדדים). כאן, ג"כ אפשר להק’ כן, וצ"ל שלמד מסוד ה’ ליראיו.
** עדיף
:
א. יותר צער יש אם לא יהא יכול לפנות.
ב. צער של זה תדיר, ואז הוא יותר רע.
ג. יותר יכול לעשות טוב ע"י תפילה. (א. הטוב שאפשר הוא יותר טוב. ב. הטוב שהאפשר יותר קל לעשות על ידי תפילה).
* ח:
** סכנה –
שני צדדים אלו אולי תלויים בדיון גמ’ בשבת (קט.).
* י.
** וכל קרבי –
רצה לומר, שדורשים מזה שרואים גדלות ה’ ממה שיש בני קרבים.
** צורה בתוך –
רצה לומר אדם בתוך העלם שצר. עדו יש לומר אדם בתוך אדם אחר. על פי זה, יש לומר שכוונת הדרשה הוא שרואים גדלות ה’ במה שאף בקרבים – בתוך צורה – נותן צורה.
** ברכו ה’ –
בסוף שלש פסוקים, מסיים עם ברכ"נ.
** אל ימנע עצמו מן הרחמים –
לשונו משמע שמחדש שא"צ אף להתחנן לרחים, אלא שיש אפשרות שרחמים עומד לבוא, ואל ימנע את עצמו ממנו ביאור וכפירה ברחמים. ויש לדון, שאולירק רצה לומר שתמיד תפילה מהני, כמו שחזקיהו התפלל. (הענין הוא שיאוש עושה שלא יבוא שכיון שמיאש, חסר רצון לו. אז, צריך שלא ליאש, שאפשר שסיבה לגזרה היה רצון האדם.)
* י:
** שגנז ספר רפואות –
מסתבר שכוונתו היה לא רק על הזכות, אלא אף  שלא יאמרו בני אדם שטעה בזה, שהרי מפני זה מת. וא"ת ומה בכך. ויש לומר שיבקשו למצוא אותו. עוד יש לומר שיבקשו עוד סגולות כזה. עוד יש לומר שאין טוב לחשוב על דבר של מצוה לרע (שפרט בתורה היא). עוד יש לומר שכיון שהחזיק בכוח רחמים, הוחזק לו כוחו.
צריך ביאור קצת מה יחס בין קריבת גאולה לתפלה ורפואה, וכן איך רואים אותו מלשון "טוב.” אם נאמר כמש"כ תוס’, שהוא שהיה כותיקין, אולי זה דבר שרק ה’ מכיר בו (וא"ת איך הכיר אח של ר’ אלעא. ויש לומר שקצת מיכרים בו. עוד יש לומר שלא הכיר בו, אלא ברוחניות שבו ובמעלות תפלתו. גם אפשר שנקרא טוב כמו "לעולם יצא בכי טוב.” אולי נראה שמי שמיחס גאולה לתפלה מגלה שמתפלל גם על גאולות, והוא הצלות גדולות. מי שאינו עושה כן מגלה שרק מתפלל לצרכיו, והוא שחושב שאינו כדאי לטרוח את ה’. אבל, הסומך מבין ששניהם קל לה’. לכן, במצב שהוצרך גאולה, יותר ראוי שיענה, כיון שכבר גילה שסובר שקל לה’.
** ספר רפואות –
א"ת הרי בזה עשה שבנ"א ימותו. ויש לומר שאם היה ידוע לו שרצה ה’ שבני אדם ימותו, אז אין רע במה שאינו מציל אותם (בפרט שהם גורמים ג"כ במה שאינם מתפללים). על פי זה, יש ליישב לשון "והטוב בעיניך,” והוא שאף שבנ"א חושבים שטוב הוא להציל בנ"א, וכן הוא ברוב מקומות, הבין והכיר חזקיה שטוב תלוי בעיני ה’, ולפעמים אין רצון ה’ שיציל בני אדם.
** הואיל –
ואם תאמר איך לא הדו, שהרי מח’ הוא אם אומרים הואיל ו"משום דס"ל כרבה, מאן דסבירה ליה כר,ח משתיק ליה.” ויש לחלק בין "הואילים.” ויש לומר שהק’ לו איך היה מעביר מבנ"א ספר רפואות, שהרי על ידו היו ודאי מרופאים. תי’ שהואיל ויכולים להתפלל, ונח’ ככבר ברסויים, וא"כ הם הם שפשעו, ואז הק’ לו לשיטתו.
** רש"י ניסן בניסן -
עיין במה שכ’ רש"י. קשה, אם כן, מהו הדרשה, שהרי רק "זה" ניסן, שנמצא שראשון לא היה ניסן. יותר נראה, אולי, שפשוט מכיון שכבר נקבע חודש להיות דבר אחד, אין ביכולת לשנותו להיות דבר אחר. אבל, אולי הענין הוא שחושב גמ’ שעברו לניסן, ועשו שני ניסנים. כן נראה קצת מלשון עברו ניסן בניסן, שממע שאת ניסן, וא את אדם, עברו. אין לומר שקאי על מה שהיתה החודש, ולא על מה שנעשה החדש. ותחשב. נראה, אז, שצ"ל שפסח היה בשני, דאל"כ מאי אהני. ויש להק’ למה הוא כן באדר:
א. אולי יש שום חשיבות לבתרא.
ב. אולי ישענין בימי אדר, שבהם יכולים להכין לפורים. אז, רוצים שיהיה יותר ימי אדם לפני פורים.
ג. אולי רוצים לסמוך גאולות ושמחות פורים ופסח.
בפסח, יש לומר כראשון, יש לומר כשני, וכשלישי יש לדון, שאולי יש ענין בקרבתו לשבועות (אלא שיש לדון אם שבועות ישנה את מקומו), ולפ"ש, אבל עי"ז מגרע קרבו לפורים.
** רש"י יטה –
רצה לומר, כיון שעל גבי איסור.
* יא.
** טרדת מצווה –
יש לדון מה קאמר:
א. רק בטורד טרדת מצוה נפטר, שבכל שאר טרדות, צריך לבער את הטרדה מלבו. וא"ת יעשה כן אף במצווה (ר"ל שפשוט שהדרך לבערו מלבו אינו ע"י איבור סיבות היאוש, שהרי באבל ובספינה זה א"א). ויש לומר שטירדא עושה שיעשה את המצווה יותר טוב. עוד יש לומר כצד שני.
ב. רק במקיים קצת מצווה פטור. טרוד טרדת מצווה הוא קצת מזה. לזה, לשון הדרשה יותר טוב, אבל לשון רש"י ד"ה טריד טרדא ק"ק.)
* יב.
** מפני תרעומות המינים –
וא"ת אם כן יבטלו ג"כ בבית המקדש. ויש כמה תי’:
א. יש צורך גדול בביה"מ, ולכן אין כדאי לבטלו.
ב. אין מינים יודעים מה שקוראים בבית המקדש.
ג. מה שבגבולים אין קוראים מוכיח להם שאין עשרת הדברות עיקר. קצת מעניין, שהרי בגבולים אין הוכחה נגד זה, אלא אין הוכחה לזה. ותחשב.
לפי זה, מעונין מה שבטלו תקנותיו בסורה, שהרי שאר גבולים מוכרח נגד זה. ויש לדון. אולי חששו ששאר מקומות ינהגו כן, ועוד שאולי כיון שבטלוהו, ל"פ עשו. (כן קצת נראה מלשון "כבר בטלו" שמשמע שאין הענין בעיה עכשיו או במקום זה, אלא מה שהיה או יש יכולת להיות בעיה, ולכן בטלוהו.  עוד יש לומר שדבר טוב הוא שכל בני ישראל שבגבולים יקבלו מלכו"ש באופן שווה. ויש לדון. ותח’.
** כבר בטלו –
ק"ק למה אין , אף בלי זה, ענין של טרח ציבור, כמו בברכת בלק ובלעם. צריך לומר שיש בזה יותר סיבה (או שיותר קל לומר).
** רש"י תרעומות –
עיין במש"כ. כ’ שמה שלא כ’ רק כמדאומרים כן, יח’ שזה עיקר הוא משום שא"כ קשה איך אומרים שום פרשה מק"ש (ויש לדחות קצת שבשלש אלה יש יותר ענין וצורך). לרש"י, הענין קצת תמוה, שאם מאמינים את התורה, בהכרח יאמינו כל המצוות, ואם לא מהיכי תיתי שזה או שרק זה ניתן מאת דיבור ה’. אולי האמינו איזה ספר היסטוראי.
** פתח אדעתא –
יש לדון במה דן:
א. אולי דן אם מצטרפים, והוא אולי אם מח’ תחילת הברכה אינו דומה לסוף או למחשבת סוף הברכה, היחס בין תחלתו וסופו קלוש. ויש לדון בזה, שנמצא מכאן שפשוט לגמ’ שכשממעט (רצה לומר, בא מדבר גדול, לדבר קטן) אותו שינוי, וכשמרבה דן גמ’, וע’ בפסחים (פו:), ובמה שכ’ שם. זה מעניין.
ב. אולי דן ביחס בין תחילת ברכה לאוכל.
ג. דן מה "קובע" מח’ הברכה, אם הוא תחלתו או סופו. כמו"כ, יש לומר שדן אם ראשו קובע או לא (ר"ל, ששניהם נח’ דעתו). גם יש לומר שדן אם יש בעיה כשיש בו שני כוונות. ותחשב עוד.
** מאן דאכל תמרא –
ממה שאמר חידושו במשנה זה, נ’ (ופשוט לדחות) שאינו יוצא, אלא על כל פנים דומים, ואז בכעין זה, שמשנה מחשבתו, יוצא.
** ה’ זוקף כפופים –
משמע שמה שכופף (לפני ה’) הוא כדי שיזקוף בשם. ויש לדחות שרק אומר טעם על שני.
** רש"י כשהוא –
לשון "כשהוא,” ולא "כשכורע" קצת מוזר. נראה שהוא שאינו אומר לזקף בכל שם ושם, ואז אומר שכשכורע וזוקף, אז כורע וזוקף בזמנים אלו.
** רש"י כל מי –
עיין במש"פ. עוד אפשר לפרש שקאי רק על לשון "אמת ואמונה" במקום "אמת ויציב.” עוד יש לפרש שאומר שיש חיוב שמקיים בברכות אלו חוץ מענין ברכת ק"ש. יש להעיר שלמש"כ רש"י, ק"ק למה א"א לומר אמת ואמונה ביום.
* יב:
** עמו במחיצתו –
כמה שאמר בחגיגה (קרוב לדף ל) ששמואל לקח עמו משה להעיד שקיים כל התורה כולה.
** ומפני מה –
קצת קשה למה לא אמר שלא קבעוהו מפני שחזר לקללה. אולי עתיד לחזור לברכה. ועוד, שאולי אף על פי כן, מראה אהבת ה’ לבנ"י, ומה שנתקלקלו, בנ"י הם דקלקלו.
** כבן שבעים שנה –
צריך ביאור מה לנו בזה. אולי ר"ל הריני גדול שכשהייתי צעיר הייתי ראש ישיבה. עוד יש לומר שחשש שלא יתנו לו authority כיון שאין זקנו לבן. אז, אמר שאף שנחלף ללבן, לא שמעו עד שדרשו בן זומא.
* יג.
** צרות אחרונות –
לכאו’, רצה לומר שתשועה מצרות אחרונות….
** משחכים –
רצה לומר, משכחים קצת, שהרי אומר שצריך להזכיר אף על הראשונות.
** שנאמר ולא יקרא –
יש לדון מה ר"ל:
א. קרא זה אומר שלא יקראנו בשם אחר משמו (שהוא שם אברם).
ב. ע’ במה שכ’ בב"ק שיש מושג ששם שבנ"א קורים יש לו שום חשיבות. לכן, יש לומר שהקרא ממש מזהיר מעשיית לו שם "אברם.” בפרט כאן, שכבר יש חישות לשם ארבם, י"ל כן. ועוד שאינו כ"כ נשנה משם "אברהם.” וע’ במש"כ (פסחים פו:)” וברכות יב:) ד"ה פתח.
ועיין בב"ק שבארנו שיש שלשה מיני שמות:
א. שם שמים, שהוא שם אמיתי שכולל כל הקרק’ וחשיבותם.
ב.שם שמי שמיוחס ושייך לחפץ קורא אותו.
ג. שם שהעולם קורא.
על פי השני, בארנו שאפשר שאין שה"ש שינוי ממילא (וזה ית’ סוגית טלה ונעשה עיל), וע’ בצדדים שם.
** פרק שני:
- רש"י ד"ה מדברים –
עיין במ"כ. ויש לדון (שלכאו’, אם הוא noun וadjective ולא phrase, היה לו למחוק שני הההין.
** – בין ויאמר -
יש לדון אם רצה לומר שלא יפסיק כלל (שצריך לדבקו לשמע, וכיון שאינו ממש מדובר, צריך לדבקו יותר באמירה) או שלא יפסיק פסקת בין הפרקים, אלא כאמצע הפרק. ותחשב.
** – כדי שיקבל –
יש לדון אם ר"ל שצורך זה בא לפני זה, שקודם קבלת מצוות, צריך לקבל עול מלכות שמים, או שר"ל שזה יותר חשוב, ואז בא תחילה. ותחשב.
* יג:
** – על לבבך בעמידה –
עיין בדף יא. במעשה דר"א ור"י. וצריך ביאור.
* יד.
** – אין מבשרין –
בפשטות, רצה לומר שממילא לא יהיה רעות. עוד יש לפרש על פי מח' בהוריות (עיין בדף יב., ובמה שבאר רש"י שם ד"ה איתרע מזליה).
* טו.
** – ולא השמיע –
עיין בגמ' שמבואר שאין זה רק גדר בכמה צריך להגביה את הקול שלו, שהרי שייך לחרש, אלא צריך לשמוע. (א. שייחס לו באמירה ובשמיע. 2. צריך שאמירתו יעשה תוצאה של שמיעה לעצמו.)
** – הא דידיה –
היה מצי לחלק בין דאו' לדרבנן.
* טו:
** – מכלל דרישא –
אכתי היה אפשר לומר שבזה סובר כמותו, ובזה חולק. ממה שרוצים שלא לומר כן, נראה שיש קצת תלייב בין שיטות תנאים (שמיוסדים על דרכים שונים בלימוד). וזה מבאר למה רגילים אנו להביא רק כמו עשר מכמה וכמה תנאים, והוא שאנן דרכן נקטינן. ויש לדחות בפשטות לומר שמסתבר שתלמידיו הפסוק כמותו, בכ"מ הוה פוסק כמותו. ודוק, שמי יימר שלא היה מי שאינו תל', כמו ר"ע וכדומה.
** – קטן שהגיע –
יש לדון אם זה סימן או סיבה.
** – רש"י ולא דקדק –
אמשנה קאי.
** רש"י ברה דבת –
יש לדון אם כוונתו הוא שלא נקרא בשמו כיון ששמו רע (איסור), כיון שבא על אמו בדעת, כיון שהיה גוי, או כיון שאין לו יחס.
* טז:
** – רש"י אבות – לישראל –
צריך ביאור מהו כוונתו. אפשר שכוונתו היא שאין לקרוא לאדם "אבא פלוני." וא"ת רק על עבדיהם נאמר. ויש לומר להיפך, שרק לעבדיהם ניתר, שאין חשש כלל שימלכו (ושנראה שרוצה לדמותם לאברהם יצחק ויעקב), אלא שרק בכשרים הותרו. וקשה מכמה בני אדם כמו אבא אריכתא ואבא שאול (אם לא שנאמר שכן היה שם שלהם. אבל, עיין ברש"י שלא מבאר כן.
** – דלא ידעינן –
יש בזה שני ענינים: אינו ידוע אם זה אב שלו. ב. אינו אב של כל בנ"י.
- דלא ידעינן –
אין זה סברה אלא על לאחר יעקב, אבל לפני אברהם פשוט הוא (א. לא היו רק אבותינו, אלא אף של אחרים. ב. לא היו כשרים וצדיקים כל כך.)
** – קמסיים –
צריך ביאור למה לא אמרו לחלק מתפילתו, ולמה לא נח' חלק ממנו.
* יז.
** רש"י בפמליא –
עיין במש"פ. נראה שהיה קלרש"י מה לנו בשלום פמליא של מעלה. תי' שמעורר על של מטה. אז, הק' למה לן להתפלל על שנים. אז, תי' שמעורר על מלחמות דאומות ופמליא של מטה ר"ל תורה. לולי רש"י ויש לת' שר"ל שלא יחלקו בשמים ויצטרכו לחד ממנו (כמו רבה, בב"מ). עוד יש לומר על פי מש"כ בדרך ה', שיש סיבות שלמעלה למטה, ויש להוסיף, ומתפלל על שניהם.
* יז:
** – אינו אוכל.
עיין במש"כ רש"י. ויש לדון למה:נראה כמלעיגו על מה שהוא חי. ב. נראה שמלעיגו ומרמז לחיותו שעושה שיכול לקיים מצוות. 3. נראה שמלעיגו ומרמז לברכת אוכלים.
** – ואינו מברך-
משמע שיכול לברך אם רוצה. (ואולי תלוי במחלקת רשב"ג ורבנן. ויש להעיר שכאן אולי יש ענין הז' ש"ש אם אינו חייב / מקיים כברכתו. ויש לדון אם שם היה מברך על ק"ש.)
* יח.
** – רב אשי –
רצה לומר מוטל לפניו דמתניתין ל"ד, ולא ר"ל לפניו ממש.
** – רש"י שנית-
עיין במה שכ'. לכאו', היה אפשר לומר שר"ל לא למדת משנה (שלשון שינוי נאמר עליו. וכן מצינו במילת "משנה," וכן במילת "תנו [שנו] רבנן." לזה שלשת ר"ל כעין מש"כ גמ' קדושין, והוא לימוד גמ' (אני מכוון לגמ' שכ' לחייב אדם לשלש את ימיו). והוא שדברים אלו או נמצא בהם דרשה זו, או יחדרו את השכל עד שיבין.
* יח:
** – רש"י שני רוחות –
עיין במש"כ. וא"ת מהי"ת שהיו ילדות. אולי ממה שהיה אמא של אחת קיים (היתה בגיל שתהא במח' עם אשת מי שעדיין זורע) מזה רק נ' שהיה אחת ילדה. ממה שהיו חבירות, משמע ששתיהן היו תינוקות.
** מחצלת –
וב לכאו', רצה לומר שאין זה דרך כבוד לבוא לפני פרגוד. גי"ל שלא רצתה שאחרים יראו אותה ככה.
* יט.
- אבל בממונא –
לכאו', זה יכול להיות סיבה או סימן.
* יט:
** – במקום שיש ח"ה –
צריך ביאור מהו ח"ה בזה: יח' בנ"א שעושה עבירה. ב. עושה נגד רצון ה'. (אין לומר שעושה ס"ר, שאין לשון חילול מורה כן.) אם נאמר כצד ראשון, צריך לומר שידעו בני אדם שכלאים הוא, ושלא ידעו שנדחה. לשני, צריך לומר שלא נדחה. אז, הענין הוא, לכאו', שאין לאווים נדחים מפני כבוד הבריות. וקשה, שמשמע שמקרא רואים שכיון שכבוד הבריות והרב יהא נגד חה"ש, אין לכבד. וקשה, שהרי אם היה דיחוי, אין צוואה, ויש רק ס"ר, ואז אין חה"ש. ואין לשונו נראה שבא לומר שלא הותרה. ותחשב. וכן מוכרח מרש"י לקמן.
** – וליגמר מיניה –
קצת קשה למה לא תי' שמקרא ד"אין עצה..." לומדים שלא ללמוד ממנו.
** – כבוד רב –
מגמ' משמע שיש שום דמיון בין כה"ר וכב"ה (ושעכ"פ כבוד הבריות נכלל בכה"ר).
** – כל מילי –
יש לדחות שאז לא דוחה לאו שבתורה, שהרי לא סר. ונראה אולי שבא רש"י לת' זה במה שכ' בד"ה כל מילי. ועיין שם.
* כ.
** – שוא"ת –
יש להעיר שגם דחיית כה"ב יהיה בשוא"ת.
** – עולי עין –
במקום אחר דנתי אם אין עין נופל עליהם או אם נופל אינו מזיק. לשון שלט משמע שאינו מזיק להם. ויש להעיר שלשון מסולק, וכן דמיון למים, משמע להיפך, אם לא שצריך לדחות שר"ל שמסולק ומכוסה מרעות ומכות העין. ותחשב.
** – תוס' שב –
עיין במש"כ תוס'. וצריך ביאור מאי קאמר, שבכל עשה הדוחה לאו נאמר ששוא"ת הוא. וצריך ביאור.
* כ:
** – כמ"ע –
יש לדון מה ר"ל: בא קרא לומר שיש לו דיני מ"ע שהז"ג. ב. יש שני מצוות וענינים:של יום. בב. של לילה. לכן, כל אחד הוא מ"ע שהזמן גרמא.
** – רש"י או דרבנן –
עיין במה שכ' רש"י. ותמוה, שכבר כ' גמ' לעיל צד שיפטרו (ואולי זה סיבה שיפטרו מדין דרבנן (שלא ירצו רבנן שיראה כחייבים במ"ע, שמא יבואו לברך. ואז, צריך לומר שרק על ברכת המזון דרבנן קאי. ותחשב.
** – כדאשכחן –
צריך ביאור מה רצה לומר, שאם רק נותן סיבה לתקנ"ע, כמש"כ רש"י, צריך ביאור למה כ' כאן ואיך תי' את הקושיה. ואם ר"ל כתוס', נמצא ששומע לדברי חבירו כדי לידעם ולהבינם, נח' שומע כעונה. זה, לכאו', תמוה.
** לא יתחיל –
קשה, שדילמא צריך להרהרנו.
** דלית ביה מלכ"ש –
יש לדון מה ר"ל: אם בני אדם מקבלים מלכות שמים, צריך לקבל מלכ"ש עמהם. ב. אם בנ"א מקבלים מלכ"ש, צריך אדם להתעורר ולקיים מצווה. נפקא מינא הוא אם יש תי' אחר לקושיית גמ' ב"ונגרוס פרקא אחרינא."
** בדבר שהציבור –
לכאו', הענין הוא שטוב שיהיו הכל עוסקים בדבר אחד (שיש טוב ביחוד כל הציבור). עוד יש לומר שכיון שכולם לומדים בציבור, יתעורר גם הוא ללמוד בציבור. ממילא, אז, צ' ק"ש.
- על המזון
צריך ביאור איזה אחרים יש (שהניחא בק"ש הנחתי שעם אחרים הוא). ולכאו', צריך לומר שבמקום שצבור יהיו עוסקים במצווה, לא יהיה מונע את עצמו. ותו"ת. ואולי צריך לאו' בזימון. עוד יש לומר ש"אלא ק"ש" חוזר לא רק על מלכות שמים אלא על תי' ראשון. אכתי קשה, אז, מה מקיים. ותחשב.
** שאין לפניו –
רצה לומר שלא כ' שם בפי' (עיין בתוס' קי' טו ובגמ' בב"מ).
** אינו חוזר –
לכאו', רצה לומר שא"צ לחזור, שלא חסר בחזרתו. עוד יש לומר שלא יזר מיד, שאז מפסיק בין ק"ש לחיוב אמת ויציב. לפי זה, צריך לומר או שקיום ק"ש מהני לאמו"י או שאמו"י מהני לק"ש, ולא שק"ש – רצה לומר עיקר מילותיו – מהני לאמו"י. ותו"ת.
** יציאת מצרים –
וא"ת אם כן לכפול ק"ש לקיים כן. ויש לומר שבי"כ ובי"כ צריך לומר אמו"י, ואז אין לכפל ק"ש. וקשה, שכבר כ' שאם כופל ק"ש, אינו אומר אמו"י (שאז יהיה מסופק, שרק אי לא אמר ק"ש בס"ר יכול לומר אמו"י וכבר אמר יצ"מ.) וצריך לומר שאומרו, אלא שאינו כל כך טוב.
** היה עומד –
קשה למה הל' כזה, כיון שהל' כרבי יוחנן. אולי ת"ח ותוספת תפילה עושים טובות אחרות, ולכן צריך לחשוב על מה מתפלל. וא"ת אם כן בספק לא יתפלל ת"ת. ויש לומר שת"ת מקיים ת"ח, אבל אין ת"ח מקיים ת"ת. ויש לדון. עוד יש לומר שאף שאין ת"ת כל כך מקיים ת"ח, טוב לעשות במקום ספק, שבלי הוא, לא יקיים כלום. עוד יש לומר שיכול להתנות. (באמת, אינו מוכרח שר"י חולק על ר"א, אבל נ' כן מלשון.) עוד יש לומר שסבר ר"י שיש שום סיבה שאין להתפלל ש"פ (א. דילמא לא יכון. ב. דילמא יעשה תפלתו קבע.) אז, רק במצב ספק, מתירים לו. כאן, אין כל כך סיבה להתיר לו. על פי זה, יש לחקור אם חולק על ר"י סובר שא"ח כיון שאין טוב בתפילה ש"פ, או כיון שיש רע זה בו. ותחשב. שוב ראיתי מגמ' לקמן י"ל שר' יוחנן דן בציור שמחדש דבר.
** רש"י ולואי-
עיין במש"כ. נראה שמוכרח שלא לתרץ כמש"כ בסוף דיבור הקודם (א"י אם כוונתי לשלי או שלו. אם הוא שלי, הוא ד"ה היה עומד) (שאל"ה אין חולקים). ולרש"י, יש לומר פשוט שסבר שאיה"נ חול', ורק במצב ספק, שיש ספק ספיקא, שדילמא לא התפלל כבר, ואף אם התפלל, דילמא הלכה כרבי יוחנן, וצריך לחזור.
* כא:
** כמאן דלא צלי –
יש לחקור בענין תפילת צבור:
א.כל אחד מתפלל את תפלתו, ויש יותר צד שה' יענה את בקשה שלהם:
אא.  מיוחס הוא לשאר בני אדם, ואז נעשה כאדם שיש בו טובותם.
אב. מיוחס הוא לשאר בני אדם, ואם תפלתם נענה, שלו נמשך עמהם.
ב. תפילת ציבור חלוק מתפל"י; תפילת ציבור מיוחס לכל הציבור, והוה כמי שכל תפילה ותפילה התפלל בחד תפילה מציבור.
נראה, אולי, שכיון כוונת "כמאן דלא צלי." יש לדון אם הקמ"ל אומר כצד קמא או שאף על פי כן, כיון שכבר קיים עיקר המצווה, אינו מתפלל עוד. ודע שג"כ אפשר שרק ר"ל שמקיים יותר, שיותר נענה. אז, יכול להיות אף לצד ראשון.
** וכן אמר –
יש לדון מהו ה"וכן": כמו שיטה זו שבארנו שסובר שאין יחיד אומר קדושה, כך מצאנו שיטה אחרת. ב. מדצ' קרא, מוכרח שיש מה לדון, ואז, זה "וכן" לתליית המח'. עיין במסורת הש"ס.
** מתפלל עמהם-
יש לדון מה עושה אם לא זה: מת' בציבור אחר; ודן אם מותר להת' כאן. ב. מת' ביחיד. לצד ראשון, נקטו כאן כיון שהוא דין השייך לנכנס לציבור ואינו יודע אם יתפלל. לצד שני, גם כן יש לומר שנקטו כן כיוון שדן בכמה יותר טוב ציבור מיחיד.
** וכי מפני –
יש לחלק שכאן מפרש מה שלא מפורש, וכאן מפרש את המפורש (שסתם מיתות לחזק), ואין כ"כ סיבה לומר שמפרש. ואולי מדייק מלשון: "וכי מפני שסמכו," שאולי משמע שסבר כשאין כוח בסמוכים.
** השתא זב –
יש לדון למה יפטר:
א. גזרו רבנן רק אם יעלה לו טבילה. כאן, לא יעלה לו, שיש לו טומאה אחרת.
ב. גזרו רבנן רק על מי שמצבו מוכיח שבע"ק הוא. כאן, שיש לו סב"א לטומאתו, אין מצבו מוכיח.
לצד שני, חיוב משמשת וראתה אינו מוכרח להיות מפני שכבר נתחייבה, ולא הופקע, אלא מפני שיש תוצאה של טומאתה "שלא חל" חצי טומאת נדה (רצה לומר, שחצי טומאתה מחמת נדה, וחצי מחמת בע"ק). ויש לדון. ותחשב על כל זה.
** אגב
יש להעיר שמגמ' שקורא טומאה למ"מ ולבשת כלאים שוא"ת, צריך לומר שאין ענין שוא"ת שאין מטריחים אותו, אלא שהוא שמעשה שלו הוא סיבה שבטל, והוא שגבי כלאים, לבישתו הוא סיבה לאיסורו, ומעשה הוא (א. מעשה ראשון של לבישה. ב. מעשה של לבישה של כל שעה ושעה), משא"כ גבי טומאת מת וק"פ, שביטול ק"פ בא ממה שאינו מקריב אותו.
** ובועלו –
עיין במש"כ רש"י. משמע שנעשה בועל נדה בשעה שנעשה צע"ק, ולא לפני כן (בשעת העראה). ואולי רוצה לתפוס בזה דברי הכל (כ"נ מהמשך דבריו).
** טב מה אש אינו מקבל –
טב לא רק זה, אלא אף "מטהר" קצת, שבו טבל ה'.
** טב מציע גמ' –
טב ממה שזה חלוק ממשנה (רצה לומר מהצעת משנה), משמע שגמ' הוא יותר מטעמי ועייני משנה (ושיש בו מה שכבר אמרו גאונים על המשנה או להיפך.) ותחשב עיין בקי' (ל.).
** רש"י אתבר –
יש לדון מה ר"ל:
א. שבר את כדו, להודיע שאינו נצרך, או כיון שאינו נצרך.
ב. שבר את כדו על ידי אמרו שאינו שייך. רצה לומר, שגרם שלא יהיה לו זכר. פשטות הוא כשני. שוב ראיתי שכן מוכח מגמ' לקמן.
* כב:
** לא האי –
רצה לומר שטבל במקווה (שאינו מסתבר למימר שלא ראה קרי מימיו), ולאח"ז לא ראה.
* כג:
** אמר רבא –
בתחיה דר"נ – משמע שר"נ הקדים לרבא (בשנים). עיין לעיל שכ' רש"י שרנב"י – שסבר רש"י שהוא ר"נ – הוא בתרא לנגד רבא.
* כד:
** לא צייתנא –
יש לדון מה רצה לומר: אין אני מאמין שאמרו. אף אם אמרו, אינו נכון. ב. אף אם הייתי שומעו מפיו בלשון יותר מובן, אכתי לא הייתי מסכים לו.ג. אף אם היה כאן, והייתי מפלפל עמו, לא היה יכול לת' לי. ד. יש לפרש על פי גמ' בפסחים (נא:).
** עומד –
רצה לומר שאז יותר הוקבע מקומו, ויותר מיוחס למקומו. ושי לדון אם הבעיה בא שמריח ורואה רע או שמקומו רע.
* כה.
** אבל לתפילה –
יש לדון אם זה צורך תפילה. רצה לומר, אולי הסיבה לדין זה הוא שכיון שמראה א"ע כעומד לפני ה' (או כיון שבאמת מתפלל ועומד לפני ה'), צריך להתנהג כראוי לפני ה', ואיל"ה, נח' פגם בכבוד ש"ש. גם אפשר שזה עושה שתפלתו רע, שמיוחס לרע, ושמגלה שאינו חושב שעומד לפני מלך, או שאין אותו מלך צריך כבוד, או שאולי מפני זה לא יהא בא לפני המלך, ועל כל פנים, לא לרצון שמנובל לפני המלך יהא. ותו"ת. תקן הלשון.
** וכי גזרו –
באמת, כמעט כל גזירות כזה, שספק דרבנן לקולא. ואולי הו"א כאן שעושהו כצואה. ודחוק.
** מהא ליכא –
קשה, שנימא אלא נבלעו אינו דומה לישנו. ונראה שאכתי אז צ"ב למה כ' ישנו אם לא לדייק כן. ואז, צריך לומר שחלק אחד ממנו ל"ד הוא.
* כה:
** כליין –
יש לדון מה לנו בזה:
א. יש קצת קדושה לכליין כיון שקובע לו ועושה לו.
ב. אין מקומו מדורהר להיות "בכליין," שזה גלוי ופשוט, אלא הוא מקום כליין. (כן מדרהרין, אלא שקצ"ב, שמדרהרים כן רק מפני שמקומו האמיתי – בתיך בכלי – פשוט ביותר.)
ג. אולי יותר הוה כלי מקומו, שלא רק שם, אלא קבוע שם, ותח'.
ד. אולי יחס בינו לבין כליו עשאו כחד יונט.
* כו.
** ק"ש וק"ש –
לשון זה ק"ק, שמלשון ק"ש וק"ש (ולא כ' כמו גבי תפילה), ונראה שצריך לדלג שניהם. וצריך ביאור למה. ויש לדון ביחס בין חד ק"ש לחברו:
א.עושה טובה אחת (רצה לומר, שיש שני זמנים שבהם חייב לומר ק"ש, ובהם ק"ש עושה דבר אחד). חייב אדם לעשות אותו דבר טוב ש"פ ביום/ ח"פ בתקופה.
ב. שניהם ביחד עושות חד דבר טוב. יש לדון אם כל חלק עושה דבר טוב בפ"ע.
ג. שתיהם עושים דברים טובים חלוקים. אז, אולי כצד שני יש לומר שכשביטל רק חד, לא ביטל חיובו לגמרי. ותחשב. עוד יש לומר ש"חד מצוה הם," וכן כוונת "של שחר... וערב" והוא שהמבטל אותו מצוה ע"י ביטול מחד פרט, אין לו יכולת לתקן.
** אבות תקנום –
יש לדון מה רצה לומר:
א. אבות קבעו שמשפחתם יתפללו אותו תפילה. אנן בתר קבלתיהם קיימים. צריך לומר שלא קבלו כל כך לייב אותנו, שמחוייבים רק מדרבנן, אלא שהדין מדרבנן הוא לעשות כמו שתקנו.
ב. אבות התפללו אותם ראשון.
ג. אולי אבות הם הרבנן שחייבו אותנו בהם.
מה שנותן לזמנים אלו כוח הוא שבהם התפללו האבות. לפירוש זה מובן יותר מה שזה קונטראס"ט לצד אחר של הגמרא.
יש לדון מהו ענין כנגד התמידים:
א. התמידים הם סימן שזה זמן טוב.
ב. מראה לה' שרוצים אנו להק' תמידים.
ג. מזכיר לה' את התמיד.
לצד שלישי, א"א לאבות לקתן על התמידים, שאין סיבה בזה עדיין. ויש לדון, שאולי מזכיר מה שיבוא.
** רש"י אבות תקנום –
עיין במה שכ'. ונראה כוונתו כצד שני דלעיל.
** דאלת"ה –
אינו כל כך קשה, שיש לומר שיש תפילות כזה ויש תפילות כזה.
** עד ועד בכלל –
קצת צריך ביאור, שהרי, אם היה אומר עד שעה רביעי, היה יכול לשאול כן, אבל עכשיו, רצה לומר עד שיגיע זמן ארבע שעות, ורק יש לשאול אם ר"ל התחלת או סוף ארבע שעות. ותחשב.
* כז.
** פלג ראשונה –
ובריי' דלעיל עד ולא עד בכלל אמר. ותו"ת. ודחו"ק.
** רש"י בבחירתא –
יש לדון אם הוא סימן או סיבה. ותו"ת.
** רש"י לא פסקיה –
משמע שהבעיה הוא עשיית הפסק בינו לכותל. קצת צריך ביאור, שהרי אין אדם מפסיק בדר"כ בין המתפלל לכותל. (אולי אין רש"י סובר כן, ששמעתי מר.מ.ג.א. ששו"ע לא סובר כן.) (צריך לומר, למש"כ, שלא ממש לפניו הוא, שאם כן, מאי אהני במה שלא עבר. ואז, צריך לומר שתפילה לאחורי רבו היה פשוט לגמ' שהוא אף בצדדים, ושאין לחלק, מדלא תי' כן. (ואולי מדמרבה כנגדו הוכח לגמ' כן, ויש לדחות בקל.) ותו"ת.)
* כז:
** רשות –
קצ"ב איך זה שייך למתניתין. ותחשב. ואולי בא מסיבה אחת של זמנה.
** רשות –
קשה, אז, שלא הז' זמנו. אולי מה שהוא רשות מראה שלא קדקדו בזמנו כל כך. עוד יש לומר אולי כמה שכ' בדבור הקודם.
** ורבי יהושע עומד –
צריך ביאור מה רצה ר"ג שיעשה. אולי סבר שהיה לו לומר לו לשאול לר"ג. עוד יש לומר שהיה לו ללמוד כדרך ר"ג, ואז היה אומר שחיוב הוא. ודחוק. אולי המעשה היה שכבר דברו בה מקודם, ונמצא שר"י פסק נגדו. ותחשב. (יש להעיר שאף אם שיטת ר"ג נודע לר"י, צריך לומר שלא נודע לתלמיד, ששאל אותו. ויש לדון, שאולי ידוע המחלקת ביניהם, והתלמיד שאל איך לנהוג למעשה. ותחשב.)
** תלמיד –
כ' שרשב"י הוא. ונראה שכך היה מידתו, לומר אמת בכל עת, כמו שמצאנו בשבת (לג, במעשה דמערה). אולי זה כיוון באמרו "אילו אני חי והוא מת," שהוא שאיני חושב שלא יאמר עלי עדות כל זמן שהוא חי. וחדוק.
** חדא שבתא –
צריך ביאור למה אין זה הורדה. עוד צריך ביאור, שהרי פשוט שמורידים לצורך, שהרי העבירו את רבן גמליאל. אולי לא היה כל כך צורך בין נתינת רובו לנתינת כולו, לר"ג, אבל היה בו מאד הורדה בקדושה. ותו"ת.
* כח.
** פושע –
רצה לומר, אם הזיד ופשע עד לאחר שבע שעות (או עד זמן מאוחר), ושוב שגג, נקרא פושע, שלא היה לו לאחר אותו.
** רש"י מתפלל –
עיין במה שכ'. וצריך ביאור:
א. צריך ביאור למה יהיה נקרא פושע, שהרי לטעם נכון אחרו. עוד קשה, שכ' עיל – וכן, לכאו', מוכרח מסברה – שאין רע אא"כ ביטל אותו, ואם כן יקדים למנחה מחשש שמא יבטלו. לזה, יש לדחות שליאדך גיסא, יש חשש שמא יבטל מוסיף. וצריך ביאור.
ב. למה צריך לזה, שיש לומר שתדיר קודם, ככל תדיר קודם. משמע קצת שזה רק כשיש ענין הטוב לו בקדמותו, והוא מה שלא יהיה פושע עליו. וצריך ביאור. עיין ברש"י גבי מוסיף, שכ', "הואיל ואיחר," ומשמע שהוא ש"הואיל וכבר איחר, וכבר פשע...," ואז צריך ביאור למה צריך טעם דתדיר. גם צריך ביאור, שאם יתפללנו, לא יהיה עליו פושע. וצ"ב.
* כח:
** לאנוחי –
רצה לומר, שישמע שר"T היה חלוש. עוד יש לומר שיבין שתלמידיו רוצים בכבודו. ותחשב.
** רנבה"ק –
אין משנה זו כל כך שייך לעני הפרק.
** שני דרכים –
צריך ביאור בחילוק בין זה ודבר ראשון שאמר. אולי ראשון היה שה' יחזיר אותו לעוה"ז או יענשנו בעונש אחר, או רק שיכעס בו. ותחשב.
** ר"ת –
פשוט לומר שהוא לשיטתו, שתקנ' ברכות ע"פ חוליות שדרה שהם שייכים להשתחואות ואז לתפילה.
* כט.
** צדיק מעיקרו –
נראה, אולי, לבאר על פי זה מה שבע"ת עומדים במקום שאף צדיקים אינם עומדים, והוא שבעלי תשובות לא רק עושים מצוות, אלא אף שומר ע"ע שלא יסריח, מה שאין כן צדיק, שנשמר משמים. ותחשב ותבין. אולי, אז, חולקים רבא ואביי במח' ר"י ור"א בזה. וכן יש לומר להיפך, לומר שמה שה' שומר אותו הוא סימן שהוא היותר גדול. ותחשב.
** ונימא –
צריך לומר שזה בסוף סלותא, ולא יבוא לטרד.
* כט:
** רגיל לומר תחנונים –
רצה לומר שאז לא נחשב כגומר תפילתו, שהיחס בין זמנו לתפלתו אכתי שייך לו. ותו"ת. (רצה לומר, אכתי נחשב בתוך תפילה, שאכתי יש רצון וצורך להרצאת תפילה, כדי שיבקש יותר. ותחשב.)
** צרכי עמך -
לכאו', תפילה זו אינו שייכת לגדודי חיה. וצריך ביאור.
** לא'-
צריך ביאור ל"ל לקה"ק. ויש לומר שאינם יכולים ליחס לו (ר"ל, מקומם גורם שאין תפילתם נשמעת כל כך, ואינם ראויים או אינם נהנים מקה"ק. ותחשב. ועוד שעושה כאילו תפילתו בא ממקום שפונה לו, וזה א"א בעומד בח"ל ופונה לקה"ק, שחלוקו רב. ותחשב.
* ל:
** שאמר משום –
מזה נראה שלא רצה לומר "מפני שאמר משום...," שהרי מח' הוא (ויש לדחות שס"ל שהל' כמותו, שיודע שכן אמר.... ודחוק). אלא, רצה לומר, "במה שאמר משום...." וכן מוכח מ"אין הל'.... ותו"ת.
** רש"י קמסהיד -
עיין במה שכ' רש"י. עוד יש לומר שקאי על רבי ינאי, ואומר שהיה מכוון כראוי. עיין בחולין (ז.) ששם לכאו' מוכרח כמש"פ רש"י כאן. ותו"ת.
** פרק אין עומדים
* ל:
** דילמא -
צריך ביאור מהו המשך גמ’, שלכאו’, שואל גמ’ למקור- והוא, לכאו’, למקור לדין כובד ראש- ומביא קרא מחנה, ולכאו’ מניח שכובד ראש ומרות נפש הם דומים/שוים, ואז מק’- וצריך ביאור מה מקשה, שלכאו’ ק’ הוא שדלמא לא הוצרכה להיות כן, אלא היתה כן .אם כן קשה מה לנו שהיתה מרת נפש[fn:1]. נראה לי שני דרכים:
א. סובר גמ’ שמרת נפש רק ר"ל "סיריא"ס," והוא כובד ראש, ודחה גמ’ שיודעים שהיתה מרת נפש, ואז היה נראה יותר לומר שר"ל מרת נפש ממש. ודחוק.
ב. אולי מנא הני מילי רק ר"ל מהיכי תיתי שאפשר בכובד ראש, ואין צריכים שמחה של מצוה. מביא ראיה מחנה. דוחה שדילמא שאני חנה שהיתה מרת נפש מאד, ואז היתה אנוסה. ותו"ת.
* לא.
** שכן בנביאים -
צ"ב מהו הדמיון, ששם הוא שבח ותחנונים (ונ’ שמשמע שום יחס בין שבח להלכה, מלשון "וכן,” אם לא שנאמר שקאי על מה שצריך מחשבה מיוחדת.)
** וזמנין -
לכאו’, הוה מצי ללמוד מ"ערב ובקר . .  . .“ יש לדחות שאולי זה ר"ל תמיד או שיש שני תפלות לזמן (ויש להעיר שבדרך כלל, אומרים שתפסת מועט תפסת) ועוד שזה אותו קרא שמהיא מיד לאחר כך ותו"ת.
** ישמיע -
ק’, שכבר באר לפני זה שאז נראה כקטני אמונה. ואולי זה רק מפני שלא נקבע כן (ר"ל שיש דברים שעושים כעין שמדברים למלך, כמו משתחווים (ולא רק מדמים כן במחשבתנו).
* לא:
** על אחת -
ר"ל שאז טוב שלא יהא לי בן, שהייתי מת בעת לידה.
* לב.
** דבר זה תלוי בי -
בדרך שחוק קצת, יש להקשות כמה קושיות:
א.מהא "מיד ניתוש משה"- הא לא נחרבו בני ישראל אכתי (ויש לומר ש"עומד לישרף כשרוף." גם יש לומר שכבר חטאו, ולא היה ראוי להם גדולה.)
ב. איך נתחזק, שהרי עדיין היו בני ישראל עומדים ליחרב.
(ג. מהו "אין הדבר תלוי אלא בי.”)
נ’ שחשב שמפני שכל דברי ה’ על תנאי חטא היו נאמרים, גם עשיית בני ישראל לעמו כן הוה, וסבר שה’ היה טוען שכיון שחטאו בטל התנאי, וממילא בטל כח משה. כיון שצו את משה לשהות, הכיר שלא עשאו על תנאי, ויכול לזכות את העם והתפלל. גם נ’ שחשב שה’ היה מתיר יחס בינו לבין בני ישראל, וממילא לא יהיו תפילותיו נשמעים, שלא היה מנהיג של אומת ה’. כיון שאמר מה שאמר למשה, הכיר שרצת להשמידם ממש (רק לזה יצטרך זמן (שמסתמא רצת לעשותו באופן קצת טבעי). גם נ’ כן מלדון השמדה שאמר ה’), הכיר ש"אין הדבר תלוי אלא בי,” שמצינו צדדים ששם שנותן בעל קובע, וחשב משה שמח’ ה’ על בני ישראל קובע לשני טעמים:
א. הוא שם אמת (יש שלש שמות לכל דבר:
א. שם אמת. הוא שם שכולל קרק’ החשובים.
ב. שם עולם. הוא מה שקוראים אותו בני אדם.
ג. שם בעל. הוא מה שקוראו בעל.)
ב. ה’ הוא בעל של ישראל.
הכיר ששם בני ישראל תלוי בו, ולכן לא היה ה’ יכול לעשות שלא יהיו עמו, שהוא מנהיגם, ואז חשב עליהם להיות עם ה’.כיון שכן, חזר לו כחו וחשיבותו להתפלל בעדם. (ואפשר שהיה כח לשניהם, ומחשבת משה דוחה מחשבת ה’. אז, הוה כעין גיטו וידו, שאולי מחשבתו יותר חשוב (ונ’ שזה אפשר אולי אף בלי נקודה שב( )) רק מפני שהיה חשוב מפני שהנהיג בני ישראל.
** אחד -
ק’ למה לא יהיו עדיין מיוחסים לאברהם יצחק ויעקב.
** אמרתי -
הו"ל להקשות מ"ארבה.” ותחשב.
* לג.
** אלא מעתה -
היה לו להקשות כן קודם, ולאחר מימרת ר"א הראשון.
* לה.
** חוץ מן היין –
וא"ת ומה בכל משקין. ויש לומר שזה כבר אינו מיוחס לעצו. אבל, משמע שיין אכתי מיוחס הוא, וזה לכאו' הוא שבדר"כ נזרע על כך, ואז עומד להיות יין.
** פת –
צריך ביאור ומה בדבר שהוא "מזונות." (ובפרט שאינו פשוט ללמוד זה מזה, שהפת יותר חשוב, ועוד שאולי מיני מזונות ברכתם חלוק מפני שזנים ולא מפני חשיבותם.
** לאחריו –
ואף שיש יותר סברה שיהיה בלפניו, דוחמה למשנ"כ בקרא מרבינן, וכבר נכ' לאחריו בב"מ. וקשה, שדילמא רק כ' לאחריו כדי שנלמד ממנו לפניו דלחם (רצה לומר, שצריך לבאר מה לנו שכ' לאחריו, שאם נותן חשיבות לאחריו, אז אין ללמוד מקל וחומר, ואם הוא לומר שגזה"כ הוא, ק' שמהיכי תיתי שלזה בא.) ויותר נראה שלא ק', ורצה לומר שמקל וחומר לומדים כן בלחים, ואז מסתבר שבא קרא לדמותו ללחם (רצה לומר, אף שחי' לומר שמברך לפניו, וחי' לומר שמברך לאחריו, כיון שיודעים שמברך לפניו, יותר מסתבר שגם כן מברך לאחריו, שלא מצאנו אוכל שיש בו רק ברכה לפניו. ותחשב.
** כשהוא שבע –
יש לדון מהו קל וחומר זה:
א. מה ללאחריו, שאינו מכיר כל כך כמה טוב היה, שקשה לו לחשוב על כמה רעב היה, צריך לברך, לפניו, שחושב בו על כמה רעב הוא, וקל לו לדמות כמה טוב יהיה אותו מאכל, לא כש"כ, שיש יותר רצון, ושמכיר יותר בחסד ה'.
ב. מה שלאחריו, שיותר קשה לברכה לחול על אכילת חפץ, כמו שמצאנו גבי עשיית מצווה (צריך לחשוב למה זה כן. ותחשב. אולי הענין הוא שבלפניו עומד להיות עכשיו. ותחשב.) לפניו, שיותר קל לכש"כ.
ג. כשהוא שבע, שיש רק חד סיבה, והוא הודאה, מברך, ואז כשהוא רעב, שמודה ושואל רשות, לא כל שכן.
** שכן חייב –
א. אז, רואים שיותר כלל שק' יחול עליו.
ב. אז, יותר חשוב הוא (ואז אכילתו יותר חשוב). ותחשב.
** השמים –
אי אפשר להיות מקור, שהרי יש לומר שעל קמה קאי. ומה שנתן לבנ"א הוא או לאחר ברכה או בשאר מינו. ויש לדון, שאולי צד זה סובר שענין ברכה אינו שצ' שאלת רשות, שא"כ אולי אין כל כך סברה לחלק שכולם של ה' הם, אלא הענין הוא שצריך להודות. אבל, עיין ברש"י.
** מעל –
עיין בכ"מ, שחקרנו בהקדש, אם הוא שיש (שנותן) קדושה בחפץ או שנותן את החפץ לה'. מה שלומד דמיון למעילה ממה שזה של ה' נראה שענין מעילה הוא השני (אפשר שהראשון ג"כ אמת, אלא שאין עבירה על זה מעילה). יש לדחות שר,ל שעבר על קדושה הבאה מאותו היחס. יש לדחות, אז, עוד שאולי אין מעילה תלוייה אלא בק' שנותן בו, אלא שקדושה הבא מיחחסו לה' הוא מעין קדושה שנותן בו.
אמרתי את כל זה לחבר, ושאל אותי למה לא הבאתי ראיה ג"כ מ"נהנה מן קדשי שמים." בארתי לו שזה רק מגלה שבנהנה מקדשי שמים יש אותו רע, ולא שזה מעילה. למשל, כ' במק"א שאולי מח' רבי ורבנן תלוי בזה, שבדר"כ אין איסור ממון תלוי במיתה, אלא בלאו, ואז, אולי בא מקדושתו, לרבי, ומגניבתו לרבנן. אז, אכתי אפשר שסובר רבי שיש רע דרבנן, אלא שלא זה אסרה תורה וענשה עליו תורה. ותחשב.
ויש להעיר שכ' גמ' בכתובות: "אמר ר"י אמר שמואל הל' כרבנן. פשיטא יחיד ורבים הוא. מהו דתימא הל' כרבי מחבו ואפילו מחבירו. קמ"ל." יש לחקור אם הקמ"ל הוא ששם אין הל' כרבי או שהל' כרבי מחבירו ולא מחבירוי.. אם נאמר כראשון, יש לומר ששמואל דכאן לשיטתו, שסבר כרבי, ושמואל ובריי' שניהם נתכותו לדבר אחד, שלא שבריי' קרא אותו מעילה ושמואל קרא אותו נהנה מקדשים.
* לה:
** זן –
יש לדון מה לנו בזה:
א. מקבל יותר הנאה ממנו.
ב. יותר חשוב הוא, ויותר ראוי הוא לקבל ברכה.
אף לשני, יש לומר שחשיבותו צ"ל שייך (רצה לומר, מה שזן מחשיב רק אם המברך או רוב בני אדם אוכלו ליזון.
** זן –
יש לדחות שכיון שלא נאכל לזון אלא לרפואה, מה שזן אינו מחשבתו. ויש לדון, שאולי אם הזה חשוב, היה מברך באכילתו אף שלא כדרך. ויש לדון.
** יין ישמח -
יש לדחות שעל יין רב קאי (ואולי שרק זה משמח). עוד יש לומר שלא נאמר בו אלא "ישמח" שהוא בכל, בין מועט בין רב, ולא מה שזן, שאינו בהרבה.
** הואיל וסוף –
עיין בבכורות בדין ראש עגל הרך שעתיד להתקשות, ששם פסקינן שעומד להקשות נחשב קשה.
** אפ"ה הל' –
יש לדון אם הוא שלא חזר בו שמואל, ורק אמר שסברת ר"י היה מסתבר או שחזר בו לר"י, ואף על פי כן, הלכה כשיטתו, או שחזר מחזרותו. אם נאמר כשלישי, מעניין איך ששמואל ור' יוחנן שניהם אמרו שדבר לקשות אינו כקשה ושניהם חזרו בהן. ואפשר שמחד טעם הוא.
** ונימא הלכה –
קשה, שלא נימא כלל, שכבר יודעים שהל' כמיקל. יש לדחות שאולי הו"א שזה אינו ביחיד ורבים.
[אגב ברש"י בסוף עירובין, שכ' על קשר שאינו של קיימא "במדינא גזור," וקשה, שלכאו', פלא הוא, שגמ' דן במקדש. נראה שרצה לבאר שלא תימא שר"ש מחדש חילוק זה, שיותר קל לגזירת עניבה כיון שאינו מביא לידי קשירה, אלא אף רבנן סוברים כן במדינה, ואז אומר על גזירת קשר שהוא גזירה מוסכמת במדינה. ותחשב.]
* לו:
** והאמר רבא –
היה מצי להק' סתירה (שאף רבא אמר כן על זנגבילא).
* לז.
** עד מתי אתה מכניס –
וא"ת מאי היה לו לעשות. ויש לומר שהיה לו לסרב. מרש"י, לא מוכרח כן. ג"כ ק"ק למה נתן לו ר"ג לברך. אולי ר"ל "מחלקת" לא כוון למח' ר"ג ורבנן, אלא מחלקת שיהיה בינו לרבין ר"ג. וצריך ביאור קצת מה תירץ לזה. ותחשב.
* לז:
** בדין פחוץ מכזית –
פשוט שאין הענין שאז לא נח' יותר קל ליבטל להיות חלק מדרב אחר, שהרי במנות אין דבר אחר לבטל, אז צריך לומר שהוא דקטן הוא עושהו שאינו כל כך חשוב, וחשבותו הוא חלק מסיבת ברכתו (ואפשר שהענין הוא שחשיבותו בא ממה שראוי לעודה, פחות מכזית לא ראוי לסעודה מחמת קטנותו, ואז צריך לומר ככר שלם/ גדול בעת אכילה (וא"ת הרי בלעיסה ראשונה יתקטן, ואולי רק צריך בשעת ברכה. עוד יש לומר שר"ל אכילתו הוא חד מעשה ממשיך, ונעשה הכל אכילה על ככר כזית.)
** והוא –
לכאו', ג"כ הוה ליה לגמ' להק' למה אמר שיעור, שרק אחרי כן כשיש חשש שיתבטל כמו אם יש כמה פירורים. ותחשב.
* לח.
** ל"א –
צריך ביאור מאי בינייהו. על כל פנים, צריך לבאר שיש כמה סברות לומר כאן (ואולי חלקים בהם):
א. ביטל דעתו (שרוב אכילת זה לאכילה הוא). מענין שזה יתיר גזרה, שכלאו' אכתי נשאר החשש.
ב. דעתו לאכילה (שיש, בוודאי, שום דעת כזה) מתיר:
בא. עושה ל"מאכל," ולא ל"רפואה," ואז אינו בכלל הגזירה.
בב. אולי אינו נעשה ל"מאכל," אלא ל"רפואה שיש בו הנאת אוכל," ואין זה דומה לסמנים. ותחשב.
* לח:
** היה אשמעינן טעמא –
וא"ת דילמא לא כרבנן הוה סובר. ויש לומר שיודע שהל' כרבנן (ואם היה חושב שלא כזה, כל שכן שרואים שאינו אדם גדול), וידעו שאל ידע שידעו כן.
** רש"י הלכה –
עיין במש"כ רש"י. ויותר נראה לבאר שההל' הוא שיוצא בברכת המוציא, שמה שכן הוא תרגום "המוציא" הוא מאד דומה ל"טעם הקרא," שהרי בהכרח לפרש קרא כמש"כ קודם אם נפרש "המוציא" כן, ואינו מראה, באמת, שום ענין אחר בפי' קרא, חוץ מזה. ואם לא נאמר שיש שני טובות בביאור קרא ובביאור מילה עברית, צריך לומר כמש"כ. ואולי לכך כיוון רש"י. ותחשב.
* לט.
** רש"י אגור –
עיין בפסחים, שזה שנויה במח'.
** ונימא כתנאי -
מענין מה שבר קפרא ותלמידו קרויים תנאי.
** תוך תוך –
עיין במש"כ בפסחים. ומש"כ לא יתכן כאן כי אם בדוחק.
* לט:
** ר"י אומר מן-
אפשר לפרש שחול' במה שחקרנו בכ"מ בענין הקדש, שיש ג"כ לחקור כאן, הואו אם נותנו לכהן, ו"קנין תרומה" דכהן נותן בו איסורים לגזרים, או שנותן בו "קדושת תרומה," וזה עושה שום יחס בינו לכהן. רבנן סוברים כצד קמא, ואז, מה שיותר טוב לכהן, רצה לומר שענין הוא בעלות כהן, ואז רוצים שיהיה בעל על דבר היותר טוב לו, שבבעלות, הנאת הבעל הוא דבר חשוב, צריך ליתון לו, מה שאין כן לר"י, שסובר שהענין הוא נתינת קדושה בחפץ, ואז מסתבר שנותן קדושה בהכי ראוי לקדושה, והוא היותר חשוב ויפה. ויש לדון. ותחשב.
* מ.
** הביאו –
יש להעיר על שינוי לשון, ששינה מלשון "הבא," שהוא לשון יחיד, ללשון "הביאו," שהוא לשון רבים. נראה שהענין הוא שיש בזה דבר חידוש, והוא שיכול לומר לשני בנ"א ליקח, כיון שחושש שזה לא ישמע לא/ לא ימצא (ועוד שיזרז את כל אחד). אז, אמר שאף זה אינו הפסק (וכן רב, לאידך גיסא, אומר חידוש).
** דאמר ר"י אמר רב –
אל תאמר שמחדש שסובר כן, וממילא פשוט מה שאינו הפסק, שהרי רב מוכרח לסבור כן, ואף על פי כן, סובר שהוא הפסק, אלא הענין הוא שזה אומר שצורך הוא, ואכתי צורך שאינו כל כך מיוחס ללחם הוא (שהוא: א. אין לו תוצאה גופנית על הלחם. ב. אינו משנה את הלחם (רצה לומר, שמלח נעשה חד בלחם. רק חלקתי בין זה למלא, אבל טול ברוך, לכאו', יותר פשוט שאינו צורך אכילה, אלא אכילה עצמו. ותחשב.)
** ונתתי -
יש לדון מהו הראיה:
א. מקרא רואים שבא אכילת אדם לאחר אכילת בהמה (רצה לומר, מה שמק' בקרא הוא סימן שמקדים לו בדין).
ב. קרא אומר שממש נותן (או, על כל פנים, היה יכול ליתן) קודם לבהמות, שאם היה נותן קודם לבני אדם, יהנו בזה, שלא יכולים לאכול.
ג. עלינו לנהוג כה', שנתן תחילה לבהמות, ושוב לבני אדם. זה, נמצא שצריך אדם ליתן מזון תחילה לבהמות שלו ושוב לעבדים שלו. ותו"ת.
** תן לו מעין –
יש לדון מהו הענין:
א. יש חיוב לומר כן. רק בשמ"ע יכול לומר כן, שס"ט של שמ"ע מעלה אותו.
ב. יש חיוב לומר כן. רק בשמ"ע יכול לומר כן, שאז מראה יותר שתפילה היא (רצה לומר, מגלה בקשתו בתפילה).
ג. אולי זה עושה שתפילה שלו עושה יותר. יש לדון מה עושה כן:
גא. דעתו הנגלה עי"ז.
גב. אמירת דבר זה.
ותחשב על כל זה.
** קרקע –
צריך ביאור מהו הענין, שהרי, פשוט שנח' קרקע, שראוי לזריעה (וכמו"כ כו"ע מודו שיכול לברך "בורא פרי העץ" על קרקע שאין בו זרע). אפשר שהענין הוא שצריך קרקע ראוי לזריעה. אבל, קשה, שאף לר"י, פשוט שאינו כן. אולי הענין הוא מח' אם קרקע רצה לומר קרקע הראוי לזריעה או לא. וקשה, שהרי אם כן בכל אילן יאמרו רבנן שלא יקרא (וזה, באמת, צ"ב). אולי הענין הוא שצריך מקור הפרי הזה קיים, והרי כאן שבטל האילן, אינו קיים. אם כן, לכאו' מוכר אותו חלק נתבטל מקריאה. יש לדחות שרק צריך דומה למקור פרי זה. ודחוק. ותחשב.
** תוס' יבש -
עיין במש"כ תוס'. נמצא, אז, שכולי עלמא מודו לר"י, בעיקר, וכשאמר "ר"י הוא," רצה לומר "משנה דר"י...." קשה, אז, תוד"ה רבי יהודה, הפוסק כר"י מכוח סתם משנה.
** רבי יהודה –
מוכרח, אז, שר"י סובר שבמיני דשאים, אם אמר, "על האדמה," יוצא. ויש לדחות שאין הכי נמי, ר"י יחלוק (וצריך לומר, אז, שקפידא זו הוא רק בברכה והענין אינו שאינו מיוחס לקרקע, אלא שצ"ל בלשון ספיסיפיק), וכרבנן מוק', כמש"כ לעיל בד"ה יבש.
* מ:
** תנינא –
וא"ת הרי הברכה שלפניו יש יותר סיבה. ויש לומר שאם מדרבנן הוא, פשוט שלא יחמירו יותר. אם דאו' הוא, נלמד בקו"ח ונאמר דיו.
* מא.
** רש"י ופליגא –
לא בא הכתוב –
יש להעיר שלכאו' פשוט שלא בא הכתוב לומר אלא שבח א"י (כן מוכח מפשטות הפסוק), אלא הענין הוא שהחשיבות של א"י בא ממה שיש אלו שהם חשובים בטעמן. אז, מסתבר שיהיו מן המינים היותר חשובים, אבל, במה שיש שיעורים הבאים מהם, אינו כן, שאינו מסתבר שזה יהיה יותר חשוב. מזה (אבל צריך ביאור למה), שיש מצוות שהם יותר גדולים ומצוות, ויש פירות היותר עיקרים לשיעור, וזה יהיה חלק מחשיבותם.)
** אינו טעון לאחריו –
יש להעיר שכלאו' טעון לאחריו, אלא שיוצא בברכת המזון. ותחשב.
* מב.
** אסור –
וא"ת כייון דסח, ל"ל לברך בהמ"ז (עיין ברש"י, שכ' שצריך בהמ"ז). ויש לומר שאכתי נשאר קצת רושם הברכה, ואין כ"כ סיבה לברכה. ודחוק. ותחשב. ואפשר שהענין הוא שאכילה אחרת (ואולי רק אכילה אחרת חשובה, או שיכול ליחס עליו בהמ"ז) יפסוק. ותחשב. (רצה לומר, ולא ייחס ברכת המזון לאכילה ראשונה).
* מג.
** והא לא קא –
נראה להעיר שאפשר שהחפץ יותר מיוחס להנאת טעם מהנאת ריח, שלהנאת אכילה צריך לעשות מעשה על או מעשה המשנה את החפץ, משא"כ לריחו. ותחשב. ועל דרך יותר סוינטיפיק, אולי הענין הוא שמה שגורם לריח הוא חתיכות קטנות מאד הבאים מן החפץ, אבל לא החפץ עצמו, משא"כ הטעם, שבא מן החפץ עצמו. ותחשב.
** יש להעיר
שהיה משמע מגמ' דלעיל שצריך ברכה כדי להניח מדבר הנקנה לה'. יש להעיר שיותר קשה לקנות ריח מלקנות טעם (רצה לומר, מלקנות חפץ הטעם). ותחשב. ויש לבאר שלכאו' קנין על חפץ עושה, כמובן, קנין על כל זכויותיו, והוא שכל זכויות בחפץ לבעל החפץ הוא (וצריך לחשוב.). וא"ת, אז למה מותר להריח בחפץ של אחר:
א. לא ניתנה תורה למלאכי השרת.
ב. אפשר שכל ענין של קנין על הזכויות הוא שנטולן זכות מאחר מראה בעלות (רצה לומר, לא שהם דברים המיוחדים לבעל, שזה גופא אנו מבארים, אלא שהם דברים שרגילים לבעל). אם כן, מסתבר שריח, שקשה שלא להריח, אינו דבר המראה בעלות. ויש לדון, שיש חפצים שאינם כן.
ג. אפשר לומר כעין שני, אלא שיחס שבא ע"י תשמשתו לא בא מהראת בעלות, אלא ממה שמתשמש בחפץ. ריח אינו שימוש חשוב, כמו שבארנו.
ד. אולי הענין הוא שיכול בעל לשמור על חפתיו, שלא יהיו נשתנים. אינו כן בריח, שלא יהיה נשתנה על ידי הרחת אחר.
ה. אפשר שקנין על זכויות בא מיחס לחפץ. מסתבר, אז, מה שיש יותר קנין על השתמשות היותר מיוחס לחפץ. לכן, יש לדון כאן, שכאן, אפשר שיש שני בעיות:
א. הבעיה הרגיל של התשמשות בחפץ שאינו שלו.
ב. הבעיה של השתמשות בחפץ הקדוש. ר"ל, שחפץ של ה' יש בו קדושה, מחמת יחסו לה', וכשמתיר ה', מתיר קצת קדושה ממנו, עד שהוא ראוי לאדם (או שמעלה את האדם. ר"ל, כוונתינו הוא שאף שקדוש הוא, נעשה ראוי לקדושה זו או שקנין ה' בא ממה שאי אפשר לבריה לקנות חפץ הזה מפני קדושתו, שאז רק יכול להתחייחס לה', וממילא נעשה של ה'. לזה, צריך לומר שיחס של ה' בא מפני קדושה. וא"ת הרי כ' לעיל שמשמע שבא איסור מפני היחס לה'. וצריך לומר שאין קדושה ראשונה גורם לאיסור, שאינו כ"כ חזק. ותחשב. ונמצא, אז, שיכול לעשות שא"א לו ליחס לו, אבל לא לעשות איסור עליו. ותחשב.)
אז, צריך לדון אם זה יתיר אף הנאת ריח מה'.:
א. לזה, יתכן ששני הבעיות יהיו קיימים כיון שאפשר להתיר על ידי ברכה.
ב. לכאו', זה רק יתיר בעיה ראשונה, ולא שניה, שאכתי נהנה מקדוש הוא, ואף שאינו מראה בו בעלות (אם לא שנדחה לומר שאף מעילה אינו הנאה אלא הראת בעלות).
ג. גם זה כשני (אם לא שנדחה שאין בעיה של הנאת דבר קדוש, אלא לקיחת דבר של קדוש).
ד. לכאו', גם בזה יהיה בעיה שני, שאכתי נהנה הוא בקדש (ואין לומר שהענין הוא שלא לשנות ולאפקט את הקדש, שהרי אסור אף בלי זה, לכאו'. ותחשב.)
ה. לזה, אם נאמר שגדר שני הדברים שווים, מסתבר שיתיר את הבעיה (רצה לומר, שמזה מסתבר שלא היה כל כך רע, אבל יש לדון אם יקל כ"כ שיהיה מותר. ותו"ת.)
וא"ת יודעים דין הקדש בזה, שהרי אינו אסור להריח מהקדש. ויש לומר שאינו כל כך קדוש. ועוד, שאינו מריח כ"כ במח'. ועוד, שבדר"כ אינו דבר הטעון ברכה (רצה לומר, שאין ריחו כ"כ נוטף וטוב). ועוי"ל ששאני שם שהתירו כיון שא"א לתקנו. ותו"ת.
[אגב, בדרשת "חצר חדשה," שחדשנו בה דברים, יש לדון מהו הדרשה:
א. בתוכו גזרו. נראה שאז הענין הוא שמסתבר שעליו היה הגזי' שאל"ה למה ומה לנו שהיה בתוכו.
ב. עליו גזרו.
ג. עוד יש לומר שחדשוה, שנתנו בו יותר קודשה, לאסור אותו ביותר.]
[אגב, אכתב הערות מדפים הקודמים משנה הקודמת:
* יא.
** רש"י ד"ה אמר להם הממונה –
צריך ביאור למה הוצרך רש"י לפרש כן.
* יב.
** רש"י נחת-
הוה מצי לפרש שהוא מלשון relax.
** שיחלה –
יש לדון אם זה לשון צער מאד או תפילה מאד.
* כח:
** כנגד מי –
לשון "מי" קצת צריך ביאור (בין בשאלה, בין בתשובה).
* כט.
** גומרה –
וא"ת הא א"א ששמואל היה מין, שהיה מנסה לגמור את הברכה. ויש לומר שהיה משקר בזה.
** בחונן הדעת –
חקרתי אם מכוון להיננו או לאמירתו בברכה. (מוכרח שהוא הראשון, שלשני צריך ביאור מהו התי' לשאלה (שמז' בברכה באמצע). ואז, צריך לומר שכשאמר את כולם, לא יבוא לטעות (שלא מצוי שישכח ברכה שלמה).
* לב.
** עכשיו מה אני אומר –
זה פיגיוריטי"ב, שהרי יכלו, ואין מה לומר (אולי ה' היה ממיתם ברעב במדבר).
* לג.
** מעידים עליו שמת –
יש לדון אם זה קשיא למתניתין או שנתרץ שצריך למסור נפש, שצריך רחמים כדי לחיות.
** דתני –
יש לדון אם מביא ראיה למה שמרחיק או למה שצריך להרחיק משעת ראייה.
** חזרו –
צריך לומר שחזרו אח"כ והעשירו, שהרי קבעוהו אף על כוס. ותחשב.
* לג:
** הכל בידי שמים –
וא"ת מה בצינים פחים (כמו שאמר גמ' בכתובות). ויש לומר שזה קרק' של אדם, וזה בדברים הנעשים לו.]
* מג:
** קבעא –
וא"ת איך קבע. ויש לומר שהיה קבוע בזמן אחר, ולא הלך אז חד יום, ואז הלך לאח"כ בלילה, שידעו בני אדם שבא מחמת קביעות הראשון. עוד יש לומר דעי"ז שקבע לילך ביום, ואז כשראוהו יבינו שהיה חוזר מזה. ודחוק. ועוד יש לומר שהיה קבוע לילך עם כמה בני אדם.
* מה.
** עד כמה מזמנים –
זה שיעור ברכת המזון, ואז יש לשאול למה דן משנה בזה רק בזימון. נראה שבא לגלות רבותא, שלשני התנאים, חידוש וחומרא הוא שמברכים ברכת המזון בפחות מכדי שביעה. אז, אומר שלא רק מברכים ברכת המזון אז, אלא גם מזמנים.
** רש"י עד כמה –
עיין בלשון רש"י, "כמה ואכל עמהם...." נראה שבא רש"י לתרץ מה שהקשינו לעיל. נראה שמתרץ שיש בזה רבותא שאף אם כל שאר סעודתו היה בעצמו, כיון שאכל כזית או כביצה עם שנים, חייבים בזימון.  ותחשב. וקצת קשה למה לא פירש רש"י כמו שכתבנו. אולי רק מוסיף רבותא על רבותא (אבל, צריך לומר, אז, שידע רש"י דין זה ממקור אחר או מסברתו, שאי אפשר להוכיח כן מן המשנה, אז,).
** יש לדון בזימון מהו הענין:
א. יש שני טובות:
אא. שאלת זימון, והוא "הב לן ונבריך."
אב. עניית זימון, והוא מה שעונים השאר.
הראשון נזכה לחד והשני נזכה לשאר.
ב. אולי טובת ניזון נזכים לכולם. מסתמא, טובת זימון הוא שיש שום formal invitation לברכה. הדרך שזה נעשה מוכרח להיות על ידי שאלה וענייה. ותו"ת.
ג. אפשר לחקור גם אם טובת זימון הוא:
גא. טובה בפני עצמה. יש לדון למה סמוך לברכת המזון:
גאא.רצו שיהיו סמוכים זה לזה כדי שיזכרו בני אדם, שזה דומה לזה.
גאב. ברכת המזון עושה זימון יותר טוב.
גאג. זימון עושה ברכת המזון יותר טוב.
גב. אולי זימון עושה ברכת המזון יותר טוב (ורק זה עושה).
גג. אולי זימון מיחסם זה לזה, ועושה, אז, שברכת המזון, המיוחס לזימון, מיוחס לכולם, כמו ציבור. כצד זה, יש לחקור:
גגא. עושה דבר אחד טוב (כמש"כ,), וזה עושה יחס.
גגב. מה שמזמנים (inviting) יחד עושה יחס (ואינו עושה דבר אחר). ותחשב.
** בגמרא
דן אם צריך שלש או לא. נראה שאפשר לתלות (ראשות כל, צריך לבאר שיכול לחלק את הצדדים שלעיל לשני עיקרי צדדים, והוא אם צריכים שלש כדי לעשות טובת זימון או כדי שיהיה שאלה ותשובה.
אולי אם צריך כדי שיעלה לטוב, אולי מסתבר שצריך שלש ולא שנים. אבל, אם הענין הוא שצריך שאלה ותשובה, אולי מסתבר ששנים יהני (ושלש עולי יעשו כן יותר טוב שאז יהיה רבים העונים ועוד שאז יהיה מזמן ומדבר אחד לרבים.
גם יש לומר כעין זה והוא שאולי אין כ"כ חילוק בין שנים לשלש. אז, אם דבר אחד עולה לשנים, ואחד לאחד, כמו צד ראשון, היהי בעיה בשנים, אבל אם כולו עולה לכולם, מסתבר שעולה בשנים. ותחשב.
אפשר לתלות בזה הדרשות:
אפשר שדרשת ר"א, שאומר שיהיו הם מרוממימם, אומר שכולו עולה לכולם, ור"א חולק על זה, וסובר שהעונה והשואל עושים טובות שונות.
נראה שתלוי אף בזה מח' עד היכן ברכת זימון:
אם הענין הוא שום דבר טוב שעושה, אז אפשר שקאי על כל הברכה. אם הענין הוא ליחסם לברכות אחרות, וכצד שני שבשלישי, אז פשוט שלא קאי על ברכת הזן. ותחשב.
ותחשב ג"כ על מש"כ בביאור לשון "עליו," שאולי הוא שייך לזה.
** עליו –
צריך לבאר מהו "עליו":
א. על האוכל (רצה לומר, האדם).
ב. על המאכל.
ג. על מעשה אכילה.
יש להעיר שיש ציורים שהבעיה הוא בזה ולא בזה. ותחשב.
* מה:
** רש"י דמקבע -
עיין בלשון רש"י. היה אפשר לומר שסימן הוא, שלמה יחייבו שלש, אם לא שיותר טובהוא משנים.
** תשעה נראים כעשרה –
יש לדון מהו כוונתו:
א. אם היה אדם רואה תשע והיה רואה עשר, היה קשה להבחין ביניהם, אבל אם היה רואה שנים והיה רואה שלש, היה קל להבין ביניהים.
ב. אם היה אדם רואה תשע, היה קשה להבחין שתשע הוא, ולא עשר הוא, אבל אם היה רואה שנים, היה יכול להבחין ששנים הוא, ולא שלש.
החילוק הוא שבשני אין הענין דמיון בין עשר לתשע לשל בין שלש ושנים, אלא מה שיותר קל למנות שנים מיד, ולא למנות תשע מיד.
וקצת יש לדון מה לנו במה שקשה לדעת שאינו עשר:
א. כיון שיש לו קצת קרק' של עשר, אולי מסתבר שיהיה לו קצת דינים של עשר. (כמו כן יש לומר שענין של עשרה הוא שהוא מכובד. כיון שזה נראה כעשר, ממילא יש בו קצת מן הכבוד.)
ב. אין חוששים שיראו ויבואו לטעות. (יש לדון מה יהיה הטעות).
לשני, מוכרח שהענין הוא כצד שני שבארנו, לכאו'. לראשון, יותר טוב לומר כצד ראשון,אבל יש לדון.
** רב פפא –
צריך ביאור, שהרי כשהפסיק, אחר נפסק עמו, ואז צער זה בא במקום זה, ולא נהנה. יש בזה שני שאלות:
א. למה היה זה יכול לברך, שהרי היה חד הרצה לברך, וחד שרצה לשא לברך, ור"ם, שלא רצה לברך, אבל מחל על קפידותו.
לזה, יש לומר שר"פ מחל והכריע לברך בברכת עצמו. דחו"ק. עוי"ל כמה שנבאר בע"ה לשני.
ב. איך היה ר"פ נהנה. לזה, צריך לומר שלכאו' היה צער זה גדול מצער זה. ותחשב. (אולי זה תלוי במקרה או אולי הוא כן בדרך כלל).
* מה:
** רש"י וליקומו -
דסבר...  דרבנן-
לא בא להפקיע מהא דר"א, שהרי אם ר"א סובר שדאו' הוא, אז צריך ביאור למה חס שיזלזלו בני אדם (ואם הוא מפני שפועלים יוצאות, אז אין ראיה שאביי חולק). וועוד, שאם כן, אין לו לומר אמן אלא על הטוב והמיטיב. אלא, בא להפקיע מצד בעמוד לקמן.
** רב אשי –
יש לדון למאי חש:
א. רצה שלא יצאו פועלים ויזלזלו. מגמ' נראה שזה הלכה מוכרחת (מה שפועלים יוצאים), ואז לא נראה שחולק על זה. אז, לא נראה כצד זה.
ב. רצה שלא יזלזלו הפועלים בזה, כשאינם עובדים, מפני שיצאו לפניו.
ג. רצה שלא יזלזלו בני אדם אחרים כיון שדרבנן הוא.
ד. רצה שלא יזלזלו בני אדם אחרים כיון שרואים פועלים יוצאים.
(עיין בתוד"ה רב אשי, שמוכרח כצד שלישי, שכ' שכיון שאין פועלים, אף אביי יודה. ואם כשלש צדדים אחרים, אז אין סיבה לומר אותו בלחש, שאין מי שיזלזל. אז, צריך לומר ששלש הוא הבעיה. אפשר שהאחרים הם ג"כ בעיות. ותחשב.
* מו.
** רש"י קטינא –
עיין ברש"י. ונראה לפרש שהיה ר"ז מצער עצמו על כל דבר, והיה מתענה עכ"כ שנעשה חול', ועל זה היה ר' אבהו מתפלל, ואז אמר שם ירפא זה המחליא את עצמו (ולכן קרא אותו בשם קטינא (ונראה שכיון למה שהיה skinny, ולא בעל בשר) וששוקיו היו נכווים), יעשה סעודה וינהיג א"ע בבקשות בשמחה בלי עינוי. נראה שלכן כשבא לשמחה זו, ר"ז אמר, "... ר"ה מבבל...," והוא שאמר, "הייתי צריך לעשות כן לשכח תורת בבל, אבל אם לא תרצה כן, אנהג עמך כאמוראי בבל."
** כי הא דאמר רבי יוחנן –
צריך לומר שלא ידע את כל מימרא זה, שאם כן, לא היה טועה בהא דרבי יוחנן קמא. (ואפשר שר"ל שידע חצי מימרא זו, או שידע דין זה, ולא ממימרא זו. ותחשב. ויש לדחות שהיה הוזכר מזה כשאמר ר"ז שיטת ר"י בביצוע.). לכאו', ג"כ צריך לומר שכשר"ז אמר בשם רבי יוחנן לבצע בעה"ב, רק ידע חצי מימרא זה, או שלא כיוון למימרא זה. יש לדחות לפי מה שכתבנו ד"ה קטינא.
** ונכסינו –
מעניין מה שברכה חוזר על עצמו. ונראה לבאר על פי מש"כ גמ' שיכלל אדם חולה עם חולי ישראל, והוא שיש ענין של "מגו דזכה זה, זכי חבירו" בתפילה (ואפשר שכמו שזה נוהג בנתפלל גם נוהג במתפלל, ושזה חד מן ענין ציבור. עיין לעיל מש"כ בזה וכעין זה.) אז, נראה שני דרכים:
א. בעצמו יתפלל היותר כוונה, ויותר מסתבר שיענה, ואז גם כן יענה על בעל הבית.
ב. כיון שתפילתו על בעה"ב בא מהכרת הטוב, יש יותר צד שיענה (תח'), ואז טוב שיתפלל ג"כ על עצמו.
** אי סברת מדרבנן –
וא"ת אכתי סמוך לחברתה היא. ויש לומר שהענין הוא שכיון שחלוקים הם, שזה דרבנן, וזה דאו', א"א לברכה זו לייחס לזו. עיין ברש"י ד"ה ויש. ונראה אולי שהיה ק' לו איך ברכת אמת ואמונה ייחס לברכה שלפניו, וצריך לומר שק"ש ממשיך אותו. אז, רואים שאין מה שזה מדרבנן וזה מדאו' סיבה שא"א לייחס. אז, דחה ותירץ שסיבה אחרת יש, והוא שיכולים לייחס, שאין ק"ש מפסיק. (אלא שרש"י לקמן בי"כ ובי"כ אומר סיבה אחרת מה לנו אם דרבנן הוא, והוא שסימן הוא שעל דרבים אחרים באים, ואז א"א לזה ליחס לזה.)
* מו:
** מתניתא ידענא –
וא"ת אם כן למה הק' על פרסיים במה ששני למעלה מראשון. ויש לומר שהקשה רק על מה שנהגו כשיש רק שנים, שמוכרח לדבר עם שני. דחוק. יותר נראה שהיה זה קושיא לכולי עלמא, ואז הקשה על מנהג פרסיים, שהיו בקיאים, ואולי הם יוכלו להשיב לו. ת' שני מוכרח בהא דמים ראשונים.
* מז.
** ולא בידים מזוהמות –
יש לדון אם סבר בריי' זו כפרסיים או כבריי' דלעיל. אם נאמר שסבר כבריי', אז מוכרח שקאי על יותר מחמש. על פי זה, נראה שאם נאמר שכל שבבריי' זו דומה להדדי, נראה שכל בריי' זה אומר שלא רק א"צ לכבד לגדול, אלא שאין לכבדו (ושהענין אינו שאין כבוד בקדמו, אלא שיש סיבה אחרת למה לא הוקדם).
ודע שיש לומר פשט אחר בריי', והוא שיש בנ"א הנכבדים מפני גדלתם בתורה ובמצוות, ויש בני אדם הנכבדים מחמת עשרם. אין לכבד במים אחרונים את מין השני, כיון שגורם לכבודו בדבר ברכה. (וצריך לחשוב על דררכים וגשרים.) יש להעיר שלפי זה, צריך לומר שאין מכבדים רצה לומר אין מקדימים, וקרא אותו מכבדים, שבדרך כלל, זהו כבוד, אבל באמת, כיבוד יש. ותחשב. גם יש להעיר שמגמ' לקמן מוכח נגד זה.
** הכי נמי –
לשונו משמע שמק' מהל' ידוע; לכאו', הוה ליה להק' ממעשה דרבין ואביי.
** כיון דאי בעי-
לכאו', זה סימן שאינו עבירה כ"כ רע. ותחשב. (עוד יש, אולי, מושג שאם דבר הוא בידו, וראוי ליעשות, יכול ליעשות אף בלי עשיית אותו דבר שמכשיר אותו.)
* מז:
** ומה ראית –
לכאו', צ"ל עכ"פ שום סברה לצד האחר, דאל"כ פשוט מאד יהא. ונראה שמה שפוטר התרומה הוא מה שכבר מעשר הוא, שרק טבל, ולא מעשר חייב בתרומה. אז, אולי לאחר חיובו במעשר, נעשה יותר "מעשר," ונפטר מנתינת תרומה. ויש לדון אם הקא משמע לן הוא שאז חייב אף שמעשר הוא, או שלא חל עליו שם מעשר אז. ותחשב.
** דלא כחלי –
ואז, החידוש הוא שיש דינים המעכבים.
** לגרמיה –
משמע שאף ר"ג, הסובר שמברך שלש על כוס, סבר שאי אפשר להוציא אחרים שאכלו דגן, שאם לא כן, יש מי שסובר כמותו. ותחשב.
** מצוה הבאה –
משמע שאף שנדחה, נעשנה מהב"ע. שקה למה א"א כן בכל עשה דוחה לאו. עוד צריך ביאור מהו תי' גמ'. אפשר שהענין הוא שדחויה היא, ולא זה צריך להיות שיש ס"ט. גם כן י"ל שכיון שאין ה' ממאס בציבור, אין בעית מהב"ע (ואף אם בדר"כ אין מהב"ע עושה ס"ט. ויש לדון, שאינו נ' כן מלשון תי' גמ'.) גם יש לומר שכיון שמיד חטא, וציבוא עשה מצווה, אין כל כך יחס בין מצווה לעבירה.)
** רש"י עד שיאכל –
עיין במה שכ'. הניח ש"עד שיאכל" קאי על הא דינאי . היה מצי לומר שכוונת גמ' הוא שאי אפשר להוציא שום חייב בהמ"ז אא"כ אכל כזית, שאז על כל פנים, מוציא חייב מדרבנן. ותחשב.
* מח.
** שבע מהו –
הנחא שאל על שמונה, שיש הו"מ שכמו עבד הוא, שכיון שתשע כ"כ קרוב לעשר, חז' לצורך, אבל צ"ב מהו ההו"א ששמונה, ולא שבע, מהני. ותחשב.
** שמש –
יש לדון מה רצה לומר:
א. אם שמש אוכל, אז נמצא בן חבורה זו שרואה בני חבורה זו (רצה לומר, ששמש אוכל עם שניהם). וא"ת אם כן מאי רבותא. ויש לומר שהו"א ש(כיון ש)אין שמשמ כל כך מבני חבורה (ועוד, שמקומו לא קבוע, ואז מקומו לא יהיה כל כך חשוב), ולא יהני לזה.
ב. אולי אף אם אין שמש אוכל, מה ששמש של זה משמש לזה, מחבר אותם.
** תוס' שמש מצרפן -
עיין במש"כ תוס', שהק' א"כ למה אוקמוה מתניתין בבית אחד. מה שהק' כן רק כאן משמע שמק' רק מדין שמש, ולא מדין ראייה (וצריך ביאור למה לא יק' מזה. יש לדחוק שרק על זה כ' כן ירושלמי, ואז רק כאן נקט להק'. עוד יש לומר שלא יהיה דין זה נוהג בראיה, ורק בשמש (עיין בהג' לקמן). עדו אפשר שבראיה פשוט, שמה לי ראיה בחד בית, מה לי ראיה דשני בתים. ויש לדון. אבל, בשמש (הוא שצ"ל חד שמש) כדי לייחד אותם, והו"א שאם יש הפסק בית (רצה לומר, שיוצא ונכנס), לא נקרא חד שמוש. (ויש לדון מהו הקמ"ל.) מזה, משמע שסבר תוס' שהיה לו למשנה לרבות בדין שמש, ואף שלא אמר דין שמש. נראה מזה שסבר שכשאומר גמ', "תני עלה" (או אף "תנא") כוונתו אינו רק שיש בריי' באותו ענין, ותנא אמר כן אגב משנה כדי שיזכר, אלא שתנא ידע שכן סבר תנא של המשנה (או שזה היה בגירסאות שונות של משניות (שרבי לא כ' את כל המשנה). ותחשב.)
* מח:
** משה תקן –
לפני"ז, צריך לומר שכ"א אמר בלשונו הודאה לה'. (אף לאח"ז, אמרו כן למד"א שחלק ברכת זימון היה. ותחשב.)
* נ:
** אזמון בהדייהו –
יש לדון מה לנו בזה:
א. אפשר שכיון שענה לזימון, יחס לברכותם, ואז אף ברכת המזון שלו נח' כמזומן (או שאף שלא בירך עדיין, יצא מצוות זימון). אפשר שאף יותר מחבורה זו רואים, שבן חבורה זו מקומו קרוב ממש, ואף משמש.
ב. אולי הענין הוא שמי שאוכל חייב לזמן עם חברותו. אם יצא, ביטל את זה, ויתחייב לחזור אא"כ אם מצא חבורה אחרת לצרף. כאן, בטל סיבה לחזור, שכבר זמנו. יש להק' שאכתי נמצא שביטול חיובו אם לא ימצא אחרת. עוצ"ב למה צ' שיזמנו עלייהו (ויש לדחוק שרק ר"ל שיזמנו). עוד צריך ביאור אם לא נאמר כראשון למה מותר לשהות לברך. לזה, יש לומר שטרחא גדולה היא. ותחשב על כל זה.
* נא.
** הואיל ואידחי –
תחשב על סברה זו. (ופשטותו הוא שלא נקבע זמנו להיות לאחר אכילה, ואז אין יכולת לברך אז, ולא נראה כן כ"כ מלשון.) עיין במה שכ' מסורת הש"ס. מעניין מה שיפרש רש"י כן, שפשוט שרבינא לא הבין כן, ובדרך כלל, לא יפרש רש"י כמס' גמרא בתחילה אם אמורא אחר לא חשב שכן ר"ל. ותחשב.
[אגב – יחזור – אפשר שר"י גרס תשובה זו על שאלת גמרא למה פולט, ואומר שברכה לברטלה היא אם לא פלטן. וצריך ביאור, שאינו לבטלה, לכאו', שהרי, אפשר בסילוק, שאם לא כן, איך אפשר במידי דממאיס. יש לדחות שרק כאן, ש[?] יכול לפלוט לא פלט, נחשב ברכה לבטלה. עיין ברש"י שלא משמע כן.]
** מיושן –
אז, הכש"כ קצת מוזר, שבשאר יין, אינו כן. (וצריך לומר, לכאו', שמה שהוא טוב ללב כש"כ שטוב לבני מעיים, אלא שיש דבר ביין חדש [שעושהו] רע ללב ורע למעיים.)
** רש"י אימתי –
קצת צריך ביאור למה רק כאן כ' כן רש"י.
[חי' – היה מצי למימר שלזה יין חי טוב לרבנן. עיין ברש"י ד"ה חי. ויש לדון אם כן הוא זה. מן הלשון לא נראה כן, אבל יש לדחות שנקט לפרש רק שם שיש מקור מפורש. ותחשב.]
* נב.
** שותהו –
לשון שותהו לא שממע לגמ' טעימה או מפני שרק קצת הוא או מפני שביד הוא. ותחשב.
** תרי תנאי –
קשה, אז, נאמר שיש עוד תנא בשיטת בית הלל, ושזה הוא. ונראה שכיון שחול' בזה, מסתבר שהוה יודעים ביה. ותחשב.
** בידיה –
וא"ת אם כן אף לב"ה יעשה כן. ואפשר שלב"ה אף זה [פסלא]. עוד יש לומר שב"ה גוזר דילמא יבוא לטעמו בשתיה.
* נב:
** נראה שחוששים
לטומאת אוכלים יותר מטומאת ידים, שחשש טומאת ידים הוא רק שאז יפסל את מאכלו, שהם שלישי, ובטומאת מאכל, חוששים שייעשה שני. ותחשב.
* נג.
** א"ה נכרי מנכרי –
היה אפשר להק' כן אף אם נעשה כולו חדש. ותחשב.
** מחצה -
ואם תאמר יהיה ספק ברכה להקל. ויש לומר שיש לצרף עמו צד שהודלק לאחר שבת. אבל, יש להעיר שעדיין רק נעשה ספיק ספיקא, וזה מניח שיכולים לברך על ספיק ספיקא. דניפ פוסקים בזה.
** אור שלא שבת -
יש לדון אם הענין הוא כעין מצווה הבאה בעבירה או שמרמז לבריאת אור שבא מחמת ולאחר השבתת שבת. (בא מחמת השבתת שבת כיון ששבת הוא השבתת ה’ מבריאת העולם, ואחרי ששבת ה’, התחיל ה’ לברוא את העולם, והוא להוציא דברים חדשים מדברים הברואים. ותחשב.) כאן, אז, אש זה נגד, ולא דומה, לאש הנברא, ואז אי אפשר לברך עליו. נפקא מינא יהיה אולי אם נעשה אש ממלאכה שמותר בשבת. אבל, יש לדון, שיש להתיר ולאסור לשני הצדדים. בצד ראשון, יש לדון אם מצווה הבאה בעבירה כאן תלוי בציווי או בס"ר. בצד שני, יש לדון אם צריך להיות דומה במה ששבת או במה שעשה כרצון ה’ של שבת. ותחשב. (לא נראה כצד אחרון שזכרנו, שאין זה רק בשבת, שבכל ימי בראשית ה’ עשה כרצונו. ותחשב.)
** רש"י בנכרי שהדליק -
משמע שהענין הוא גזירת נכרי שהדליק במ"ש לנכרי שהדליק בשבת. קשה, אז, מה לי נכרי מנכרי. נראה, אז, שגזירה לקוחה מזה שלא שבת על ידי נר אחר לשלא על ידי נר אחר. לצד ראשון, צריך לדחות שצריך שני פקטורים. ותחשב. אף לצד שני, ממה שבישראל שרי, מוכרח שיש יותר מחד פקטור. ותחשב.
** לגמור -
גם כן מיעוט גויים. ותחשב אם יש אולי הגדרת צירופי מיעוטים, שכאן אחד הוא (שאינו לריח). ותחשב.
* נג:
** מ"ט יונה -
לכאו’, שואל למה נקט יונה, ולא למה מצא יונה, שפשוט שמצא יונה כיון שאמר שמחפש ליונה. וא"ת מהו התשובה. ויש לדון אם התשובה היא שחשב שבזה אולי ייעשה לו נס, כיון שהוא דומה למצוות ובני ישראל, או שהתשובה הוא שרצה לומר דבר שהוא נכון על פי דרך משל, וכיון שחזר למצווה, ומצוות משולות לכנפי יונה, נמצא שחזר לכנפי יונה. ותחשב.
** בכנפות… מצוות -
צריך לבאר היחס ביניהם. אולי הוא רק מה שהוא משונה. עיין ברש"י בשבת (מט), שמשמע שהדמיון הוא מה שיש לו דבר שהוא מבטיח עליו, שהוא עושה את כל שמירתו. ותחשב.
** צמא -
יש לדון אם זה סימן או סיבה. ועיין לקמן.
** צמא –
נראה שני צדדים בביאור למה אי אפשר לברך לאחר עיכול:
א. רק מברך כשנהנה.
ב. רק מברך כשמיוחס לאוכל או להנאה שהיה לפני כן:
בא. על ידי תוצאות שלו (דהיינו מה שאינו רעב). קצת קשה, שמה שחי יהיה תוצאה. ויש לדון, שהיה חי בלי מזון זה. ותחשב.
בב. אם אין "זמן חשוב" מפסיק. זמן חשוב הוא זמן של אכילה עד שרעב הוא.
אם נאמר כב-א, אז מסתבר שהא דר"ל הוא סיבה. ותחשב. אפשר שגופא בזה חולקים ר"ל ורבי יוחנן. ותחשב.
** רבי זוהמאי -
מסתבר שמחמת זה נקרא רבי זוהמאי. ותחשב.
* נד:
** ממיך -
הענין כאן, לכאו’, אינו שהיה משפיל, אלא שהיה מביא זה לזה. לכאו’, צריך לומר שכן עשה כאן, שאם לא כן, היו מכירים כבר בזה. יש לדון, שאולי הכירו, ולא ידעו למה שינה. גם אפשר ששינה, ולא הכירו בזה. ותחשב.
** את והב –
הם ראו מפני שהם היו בסוף.
** קמצי -
לכאו’, היה בזה כמה ניסים:
א. באו קמצי.
ב. היו יכולים לעשות נקב באבן.
ג. היו יכולים לנקוב נקב כל כך גדול ורחב.
ד. משכו שיניה.
* נה.
** שלשה צריכים רחמים -
יש לדון מה רצה לומר:
א. בדברים אלו, יש יותר צורך לרחמים, שיש חילוק גדול בין טוב לרע.
ב. דברים אלו לא נעשים טוב אלא על ידי רחמים. עיין בפסוקים שמביא. כן נראה מרש"י.
** וי"א -
לכאו’, מניח גמ’ שאף החולק לא יסבור שטוב הוא לו.
** רש"י כאגרתא -
עוד יש לומר להיפך, ששם הוא, אף שלא נקרא, כאגרתו שבוודאי נכ’, ובוודאי אם כתב לו לומר שיקטלנו, יקטל, ואף שלא קראו. שוב ראיתי שגמ’ לקמן מוכרח כרש"י.
* נט.
** אשתך שכיבא -
כבר אמר כן. צריך לומר או שנשנה קודם שמתה אשתו או שהיו לו שתי נשים. לצד שני, יכולים לבאר למה אמר שרגז על בת ר"ח, ולא על אשתו, ששנים היו שמתו. אבל, לולי זה יכולים לפרש שאמר בלשון זה כיון שרגז כיון שהיתה בת ר"ח, ולא (רק) כיון שהיתה אשתו.
** מלכא הוית -
משמע שהיו שתי מדרגות - ראש מתיבתא, ועליו מלכא, שאם לא כן, קשה שכבר נתנבא לו כן. יש לדחות שנשנה קודם שקרה.
* נז.
** ר"ש -
משמע שאף סגי נהור רואה בחלום. וקשה, אם כן, מה שאמר רב יוסף, “אף לדידי…,” וכמו שפרש"י שם. אולי שאני ר"ש שהיה רואה (איני יודע ברב יוסף). עוד יש לומר שזה נאמר לפני שנסתמא. ותחשב.
* נז:
** ספר מלכים -
נמצא שיש ארבע, אף שאמר שימנה שלש.
** הרואה מגילת אסתר -
ריבוי לשון הרואה, ומה שכבר מנה שלש, משמע שאינו חלק מכתובים. אולי זה כמד"א שלא קידש.
** תשמיש -
לכאו’, ר"ל לאיש, שלאשה יש מה שנכנס בה (א. אבר. ב. זרע.) ויש לומר שמה שנכנס אינו מה שנהנה. רצה לומר, שנהנה מנגיעה, ולא מאכילה, וכדומה. ותחשב.
* נח.
** [בשבילי -
רצה לומר, כמו שהוא עצמו אמר על ה’. לכאו’, מש"א "לי נעשה" א"צ, שהניחא בבית, יש לומר שלעצמו ולבניו נעשה, ולא לאורח. אבל, למי ה’ יברא עולם אם לא לבני אדם. ויש לומר שסבר שאולי לא נברא אלא לכל בני אדם, ולא בשביל יחיד. גם יש לומר שרק בשביל ת"ח נעשה. אם כן, צריך לומר שחשב את עצמו שלא להיות ת"ח או שהיה מלמד כן לאחרים. ותחשב.
** למימרא -
וזה רע או שבא חושבים שהיה שונא ע"כ, או שיודע ששיקר.]
** גבורה -
רצה לומר יד גדול יש בו גבורה (שהוא כוח וחזק).
* נח:
** שוברת חצי גופו -
יש לדון מה זה אומר:
1. נשבר גופו לחצי (רצה לומר, שובר במתנים, עד שגופו נשבר בחציו).
2. ניטל ממנו חצי כוחו.
3. חצי מן אברים שלו נשבו.
כמובן, הוא רק לשון של הטשת כוח, אבל השאלה היא מה כוונה של המילים. (אבל, לא מוכרח שיש, באמת, כוונה כל כך למילים. ותחשב.)
** ואמר ר"י -
לכאו’, זה חלק מן הנחמה, והוא ש"אף שאמר ר"י… אף אמר רבי יוחנן שעתיד להחזיר אותם.” עוד יש לומר שכשם שדרש נכון בזה, ומה שדרש קרה, כך מה שידרוש בזה יקרה.
** כששין -
לא ממש, שאם לא כן, קשה מש"א אין ששים רבוא בבבל. ראיתי שהקשיתי שהרי ברכה זו נאמר על מה שדעת כולם חלוקים, ואז זה אי אפשר באחד. ויש לומר פשוט שחישבות של זה אינו רק מה שהם שונים, אלא שברא ה’ כל כך כמה מיני דעות עד שלכל אחד יכול להיות כוח, ויכולים להיות כולם שונים. אם כן, יש לומר שר"ל שהוא כלל כוחות כולם, והיה בו ששים רבוא כוחות. ותחשב.
** ברוך דיין -
נראה שהפשט הוא שבמעי אמו, אינו דין עליו. ויש לדון, שיכול להיות דין על אמו.
** רש"י ר"ה -
עוד יש לומר שמפ’ מהו כוכב דשביט.
* נט.
** רש"י וליהדר -
וקשה שנהדר מעייש. ויש לומר שלא היה רוצה בזה. עוד יש לומר שאז נעשה על ידי חולותו תיקום, והיה כמו מילוי מחוליא. ותחשב.
** אין הבור מתמלא -
צריך ביאור למה לא. (אין לפרש שמקשה שניטל ממנה ונחזיר אותו לעצמו, או שניתן לעייש, שזה פשוט. ותחשב. אין לומר ש"אין בור" רצה לומר שדבר הניטל מדבר אחר אי אפשר להחזיר לו, שלעתיד לבוא, יחזרו כוכבי עייש ויתקנו. ותחשב. אולי ה’ יעשה חדשים אז.)
[והיינו גוחא – שקול עושה וויברישי"נים. אבל, שו"ר שמגמ’ מוכרח שבא מן הדמעות הנופלות.
** ופליגא -
יש לדון מהו המחלקת:
1. מה שאמר שהוא "בטיהרא" רואים שנעשה.
2. אמר עליו הל’, ומשמע שנוגע הוא, ולא שבטל.
* נט:
** תקופתה -
דנים אם מברך אם כסהו ענין. לכאו’, הצד שלא לברך הוא שאז אין החמה נראה, וצריך לראות שחזר, ולא רק לדעת. ויש להעיר שרק רואה אותו כשהוא חזר, ולא רואה שהוא חזר, שאין בראייתו ידיעה שמשם נברא. ותחשב. גם אפשר לומר שהוא שאז אין שמים כברייתו, שנברא בלי עננים. אבל, אז נמצא שגם עננים שאינם נגד השמש יפסלו. ויש לדון, שאולי צריך להיות השמש כבריאתו, ואולי זה גם כולל עננים שלפניו, אבל לא שכל השמים צריך להיות כבריאתו. גם יש לומר שכשאומר שבטיהרא נברא, מכוון רק לעננים שלפני השמש.
* ס.
** קנה וחזר וקנה-
קשה, שדילמא זה יותר צד שיברך, שבעת קנייה, לא היה לו חפץ כמותו. ותחשב.
** דאי שמע -
צריך ביאור מה רע יש בזה; דילמא רק אין טוב. ותחשב. אולי הניח גמרא שרק צריך ראיה שדנים על שם תחילתו, ולא על שם סופו לחיוב ברכת הטוב והמיטב. ותחשב.
** רש"י בד"ת –
או שיטעה.
* ס:
** רוקע הארץ -
יש להעיר שכבר היה נהנה מזה במטתו, שאם לא רקיעת הארץ, היה מטתו על המים, ומסתמא זה רע לו. ויש לדון, שאולי היה יכול לפלו"ט. לזה, צריך לומר שמש"א כיון שעמד, זה צריך להיות על גבי הקרקע ממש, שאם עמד על עצים וכדומה, יש לומר שגם זה יהיה פלו"ט.
** ציצית -
[זה חלוק, שבה"מ הוא.] ויש לומר שברכת המצוות הוא רק ברכת שבח או הודאה כברכת השחר, אלא שהוא על מצווה. וצריך לומר שכדי לעשות ברכה כזה על מצווה, יש דינים פרטיים, המיוחדים למה שקוראים ברכת המצווה. גם יש לומר שרק כולל כל הדברים שאומר בשחר, אף ממיני ברכות שונים. יש לדון, שלא מזכיר כל הברכות שבתפילה.
** נט"י -
תפיליו יפסקו, וצריך להתירם קצת קודם לכן.
* סא.
** וייצר -
ואם תאמר דילמא רק רע יש לו. ואולי לא כ’ אף ויצר. ודחוק. ועיין בקראי.
** ויבן -
צריך ביאור מהו התירוץ:
1. חוזר הקרא על בנינה דמעיקרא לחדש שכן נבראת.
2. אולי רצה לומר שלאחר שנפרדה, הוסיף ה’ לה כן. וקשה, אז, איך תוליד לפני זה. ויש לומר שלפני זה לא היתה יולדת כעין עכשיו. ותחשב.
* סא:
** כשם שדרו-
[זה קצת נשמע כמו אבולושי"ן.] עוד יש לומר שרצה לומר במגדל בבל. עוד יש לומר על פי מש"א גמרא שלכל בים יש כנגדו ביבשה, ומבאר בגמרא בכורות שיכול להוליד ממנה, ואז אומר שמסתמא לך היו אבות ביבשה, ולא היו אבות בים. ותחשב.
* סב.
** את עיילת -
ואם עיילת, נמצא שאינו צנוע. ותו"ת.
** כותב -
צריך ביאור מה לנו בזה, ובפרט שלא היה דרכם לכתוב אלא תורה שבכ’. ותחשב. ויש לדון.
* סב:
** של כבוד -
קצת קשה, שמשמע ששאר בתי כסאות לא היו כן. אולי רצה לומר שכבודו היה שנמצא נעול וידע שיש בו אדם, ואין צריך האיש בתוכו להכות להראות שהוא שם, אבל אם יכול לענות, פשוט שאין כבוד במה שא"צ לענות. ודחוק. ואולי ת"ח צריך לנהוג את עצמו בדרך מכובד, וזהו הראיה.
* סג:
** חנניא -
אפשר שזה סמך למה שקוראים בן אחר זקנו.
** זוכה להבחין… דתנן -
צריך ביאור מאי קאמר. אולי רצה לומר שימצא סוגיות המועלים לו ללמדם.
* Footnotes
[fn:1] איני מבין כל כך מה כוונתי בזה, שלא השבתי כל כך על קושיה זה. ותו"ת
