** פרק כל כנויי
* ב.
** כל כנויי -
יש להעיר שלריש לקיש (שסבר שכינויים הם רק לשון אומות) קשה למה לא אמר, “נדרים חלין בכל לשון. “ (יש לדון אם זה ק’ ר”ן. קצת נ’ שרק מק’ למה נז’ הני, אבל לא מק’ על לשון “כינוי.” וזה דחוק, שמק’ קודם תירוצו שנביא לתרץ לקושייתינו.) נראה פשוט לתרץ על פי מה שכ’ ר”ן ש”קמ”ל . . . אע”פ שאינם מעיקר לשונם . . . .” יותר קשה, לכאו’, לר’ יוחנן, שסבר שכינויי שם לשונות שנעשו לצרך אמירת שבועות ונדרין. אם כן, פשוט, לכאו’, שמהני. ואולי היו ידועים לשונות לבני אדם והיא נקראים “כנויים.” לא היה כל כך פשוט מה היו. אז, אמר משנה שהם כשרים (ויש בזה חידוש, שלא היה ידוע שתקנוהו רבנן). וא”ת איך ידע ר”י. וי”ל שידע כן מסברה כיון שאמר משנה אותו דין. ויל”ד. גם י”ל שהיה לו מסורה (שלא היה ידועה לרב בני אדם.) ותו”ת.
* ב:
** מאי שנא -
יש לדון מה רוצה:
א. יאמר כלם בשניהם- יש לדון, שכיון שכבר אמרם, לא צריך לאמרם עוד. ויל”ד.
ב. יאמרם בשני ולא בראישון. צ”ב למה; לכאו’, מסתבר להיפך, שבזמן ראישון שהיה לתנא סיבה לכ’, יכתוב. יש להעיר שיש כעי”ז בשבועות. וע”ש. (ואפשר שאי היה תני כלם בשני, לא היה צ’ להז’ נדרים (שכבר אמרו לפני רק מס’ אחת), ואז לא יצטרק לאמר כל כך. יש להעיר שזה לא נוגע בשבועות.)
** וחסורי -
לכאו’, ר”ל חסורי (הוא”ו צ”ב.).
** חסורי -
מתרץ ק’ בתרא קודם. מעניין, שתי’ כאן הוא לומר שיש להשיב על השני קודם.
** דסליק מיניה -
צ’ לחלק בין זה למשנה באבות (ה-ז). חושב אני שבמק”א דנינו בזה.
** אוושא -
נ’ שחוששין שישכח. אם יאמר ראישון ראשון, לא חוששין:
א. אין כל כך בין דבר וביאורו. דחוק, שהחילוק קטן.
ב. יש לאדם בדעתו מנין של מה שאמור בהקדמה, ואת זה זוכר. אם, אין חשש שישכח (כמו אי לא אוושא), אין צורך לפרש כאותו מנין, שבין כך ובין כך לא ישכח. כיון שאוושא, וחוששין שישכח, צ’ לפרש כאותו מנין כדי שלא ישכח.
* ג.
** מפרש -
יש לפרש, אולי, שמקדימו שאינו כל כך פשוט, שאינו בפירוש בקרא, ואז צריך לפרשו, ולכן רק בפירושו מקדימו.
* ג:
** כגון דאמר -
לא הבנתי, שלמש”פ ר”ן, יהא כאומר “אהא נזיר בשעה שאוכל לדעת . . . ,“ שהוא מיד, ואז יחול מיד.
* ד.
** חידוש -
לכאו’, רק ר”ל פירכא. אם כן, לשונו מוזר.
* ד:
** רישא -
לכאו’, זה קשה בין כך ובין כך.
* ה.
** כגון דפריש -
גם הומ”ל שפרש כמה שאמר שמואל (אלא שלכאו’ אינו כל כך פשוט).
* ו.
** דדלמא -
יש לדון אם ר"ל שצריכים להחמיר או שכן מניחין שכיוון. נ’ כשני ש"פירושיהם להקל,” כמה שאומר לקמן. וצריך ביאור למה מניחים שיותר משמע כן.
* ו:
** מי אמרינן -
משמע שדן במשמעות לשון, ולא באם יש יד. וצ"ב.
* ז.
** לכאו’
, הו"מ לרבינא לדון בהזמנה לאביי לאיסורי הנאה.
* ח:
** אי אפשר -
צריך מה שאינו אפשר שאין בו, ולא מה שאפשר שיש בו בטלה, שאי לאו הכי נאמר שיש סםק ספיקא, שאולי היה הנידוי שקר, ואולי היו שניהם אמת. (וצריך לומר שאין צד ששניהם שקר.)
א"ר- זה כמה בני אדם!
* ט:
** אמרתי לו -
לכאו’, “לו" רצה לומר היצר, ולא הבבואה. ויש לדון שהוא המתגאה, ולא יצרו. ותחשב ותבין.
** חולין לעזרה -
מעניין שדעתשל לאחר זמן מהני כלל. ואולי ר"ל שנעשה כטעות.
** כל אשמות -
נראה שלא הקשה מחטאת כיון שבא רק על שוגג. (ועוד שיש חטאת יולדת ש(אולי)  לא בא על חטא.
שקוקואל- כבר שאל כן. ועיין בב"ח.
** קרינשא -
צריך ביאור למה דומה. ואולי דומה ל"קרבן.” ודחוק, שהיה מפרש הדומים ללשון שבועה (א. לשון שבועה. ב. עושים שבועה.)
* יב.
** של עולה -
מעניין שמניח שאף בו לא ננתק נדרו ונתחדש איסור אחרת. ותחשב.
** דשמואל -
עיין בפירוש ר"ן. אם למסקנא זהו החידוש, היה אפשר לו לומר שלא אמר "יום ראשון" אלא "יום שמת." ותחשב ותבין.
* יב:
** דאפרשינהו -
מעניין שנחשב חלה. שאינו אפוי.
* יג:
** יאסר פי -
יש לדון איך נאמר שפיו הוא החפץ שאוסר על עצמו. (עיין לקמן שיש נדר שבו הוא החפץ (איני ברור בזה, אלא שכן אני זוכר). וצריך ביאור.
* יד.
** ממילא נסבא -
נמצא שלשון זה שוה ללשון שאמר לעיל (איידי קתני).
* יד:
** תורה -
צריך לחשוב על כל גמרא זה.
* טו.
** כי לא מזדהר -
צריך ביאור למה.
** דאי -
ואינו בעיא דתני דאי, שאומר ציור שיחייב, ובהכרח עובר.
** והתניא -
זה דין חלוק. ועיין במש"כ בשי"ח ש"י (גלגל רביעי) על ר"ן.
* טו:
** הנאת -
צריך לחשוב על כל זה (מה לנו מה אסר).
* טז:
** לאו ליהנות -
העיר ש.ל. שיש הנאי ממש (כמש"כ ר"ן גבי ביאה). וצריך ביאור.
* יז:
** תאנים -
צריך ביאור למה לא דן בזמן (שהוא הנידון גבי נזירות).
ונשאל- לא הבנתי למה אינו פשוט לומר שיחול שני כיון שנעקר ראשון, ונמצא שלא היה נשבע. ותו"ת.
* יח.
** לא ינקה -
צריך ביאור, שאכתי יש חומר לנדרים.
* יח:
** סתם -
יש לדון אם זה מחמת ספק או מפני שמניחים שאומרים בני אדם נדרים שיחולו.
לא מעייל- נמצא מעניין שאם מק’ בהמה וחיה, יהא קדוש, שאינו שרוי בספק, אבל אי מקדיש בהמה ושוב חיה, לא יהא קדוש, שעל כל אחד שרוי בספק.
* יט:
** ראב"צ -
היה אפשר לומר שהוא ר"י, כדלעיל.
* כ.
** שסופך -
יש לדון למה צריך זה, ולמה לא די מה שאולי יעבור על איסורי נדרים. (זה יותר קשה, אולי, לשיטת רבה (יבמות (פב.)).
* כ:
** עושה אדם -
יש לדון אם אומר שמותר (כן נראה מדרשה שלו), ומניח שלא יבא לו רע כיון שמותר או שאומר שאין צורך ליזהר. ותחשב.
** משל -
צריך ביאור מה מגלה.
* כב.
** כל מיני -
מעניין מה שיש כמה מיני גהינום. גם נראה שזהו מקור ל"All h-ll broke loose” ויש לדון.
* כב:
** רב נחמן -
אולי היה יותר ירא ממנו (ולקמן, אולי רק היה עושה כן כיון שהיו כמה רבנן) כיון שהיה חתן נשיא.
** אדעתא -
מעניין שהיה צדיק עד שחש להא דר"נ, ואכתי נדר. ואולי יש לתרץ על פי מש"כ בדיבור הקודם.
* כג.
** הוה לה -
אולי מפני מעשה זה שנאה, ולכן נשא אחרת ביבמות (ומת).
* כד.
** כלום אמרת -
לא הבנתי למה מניחים כן ולא חוששים שאמר כן לא מפני שרצה שיכבד אלא שירווח. אולי אף על פי כן, יכול לטעון שרק רצה שבקשותיו ימלאו. ויש לדון.
** כלב -
נראה שבקט כלב מפני שאף בשבת מותר ליתן לו מזונות ושדרך בני אדם ליתן לו מזונות (שבת קנה:) ושאמר תורה ליתן להם נבילה.
* כד:
** הלכה -
לכאורה, פשוט שיהא כן, שמשנת ראב"י קב ונקי. ואולי סבר גמרא שזה רק נגד יחידים.
* כו.
** יש לדון במחלקת
רבא ורבה למה יותר חשוב אם ישנה:
א. אולי ר"ל שיותר הוה נדרו בטעות, שלא היה אותר אותם מילים כל אם ידע.
ב. אולי ר"ל שהותר חלק חשוב, חשוב במה שהיה משנה את כל הנדר. ותחשב.
** ולנערה -
משמע מר"ן שהענין הוא שלא כיוון לאונס. אם כן, קשה מה שייך קרא. ותחשב.
* כח.
** כח דב"ש -
צריך ביאור למה לא משמיענו כח היתר. (ויש לדון אם כלל ד"כחא דהיתירא עדיף" הוא רק במשנה ולא בברייתא.)
* כח:
** להכי קנדר -
יש להעיר שאם חוזב שלא יחול, אין סיבה לנדור. ויש לדון, שאולי רוצה שבני אדם יחשבו שנדר. יש לדון, שאף הם ידעו חשבון גמרא. גם יש לדון למה ירצה שיחשבו כן, שרק רשע נודר.
** בהא דנעשה קדוש
צריך לחשוב. וצל"ח על כל סוגיא זה.
* ל.
** וחד תני -
יש לדון מה סובר מי שתני כן על רישא לגבי סיפא. אפשר שמודה, ורק מיקל יותר ברישא. גם אפשר שחולק. יש לדון, שאז קשה מהו החידוש; כבר אמר שלא נחשבים יורדי ים. אולי הוה אמינא שלא נחשבים יורדי ים ולא נחשבים יושבי יבשה. גם יש לדון למה נאמר כן כיון שאומר על יושבי ים בפירוש, ולא מחלק. ותחשב.
* ל:
** שחורי -
משמע שלא לבשו לעולם ירמלכ"א.
** שחורי -
יש לדון למה רק דן בקרח ולא במי שיש לו שער אדום או כדומה.
* לא:
** בזבינא -
בכל סוגיא זה יש להעיר שממה שקנאו פשוט שהוא רוצה אותו יותר. אז, צריך לומר שנהנה. יש לדון, שאולי שווים לו, ועשה חסד לחברו. ודחוק. ואולי זה טעות (אז, רצונו לא חשוב או שמה שנחשב הנאה אינו מה שעשה רצונו, אלא זה סימן שאותו חפץ יביא לו הנאה. כאן, לא יביא לו, שמוטעה הוא). גם יש לומר שאף שרוצה אותו יותר, אינו נחשב נהנה, שאולי תלוי ברצון סתם בני אדם.
** זבינא מיצעא -
יש להעיר שאם כן, אין אחד מהם נהנה, ואז נקשה שיהא מותר בשני ציורי משנה. ותחשב.
** משה הצדיק -
בדרך כלל לא נקרא כן. ואולי הוא מפני שאז לא היה רבינו עדיין, אלא רק הצדיק. אם כן, נראה מכאן שבני אדם נקראים על שם מה שהיו אז, ולא על שם מה שלבסוף נקראים. עיין לקמן שקוראו משה רבינו.
** לא נקרא שלם -
יש להעיר שלכאורה זה רק מפני שהיה האחרון. ויש לדון. ואולי מה שבחר בו ה’ להיות המשלים הוא המוכיח. ויש לדון.
** כל זכויות -
אם לא קיים תורה, יש לדון איזה זכויות היו. ואולי היו לו מידות טובות או קיים שבע מצות של בני נח או עשה מצוה בלי ציווי. יש להעיר שיש לגמרא צד שאין שימור ממצווה אם אינו מצווה (סוטה, גבי נשים בלימוד תורה).
* לב.
** שנתעסק -
אכתי הוא מפני ששהה, אלא לא שהה כל כך. ותו"ת.
** ולא שיירו
- עיין במה שפירש ר"ן. אם כן, אולי מזה רואים שהיו שנים, שאי לאו בכי, איך ישייר רק אמצעיתו. ואולי היה כזה :	    (זה ראש מה שבלעו, והקו הוא כנגד מזה) עד שרק אמצעיתו לא נבלע. ותו"ת.
** אין לך מי -
יש לדון מהו כוונת זה (שמשה, לכאורה עסק כן). ותחשב.
** ופליגא -
יש להעיר שיש על שני לשונות שאמר על מילה חולק (שיש מימרא שתלמוד תורה כבגד כולם). אפשר לתלותו בשני אופנים:
א. אפשר שחד נאמר על תורה וחד על מילה, ודנים איזהו איזה.
ב. אפשר ששניהם נאמר על היותר חשוב, ודנים איזה הוא החשוב. לזה, אולי יותר מובן מה שלא מזכיר מה שעל ראשון יש חולק (שנכלל בהזכרתו על השני).
** שמא יש בי דבר מגונה -
באמת, היה בו דבר מגונה, שהיה לו ערלה, ואז יש לדון מה היה דן. ואולי דן אי היה דבר שהיה לו לתקן. גם יש לומר שציווה ה’ מצוות ברית מילה רק מפני שעל ידי זה נעשה ברית. ותחשב. גם יש לומר שמחדש שלא היו ס"ר, אלא שלא עשה ס"ט.
** אין מזל -
יש לדון אי היה ישראל, ואין לו מזל, או שהיו בניו ישראל, ואז יוכלו להיות אף בלי מזל. נראה כראשון, שאם הוא  לא היה ישראל, לכאורה אף יצחק לא היה, ואז היה הוא צריך מזל. ותו"ת.
** מפני שהפריז -
יש לציין לגמרא סנהדרין שאמר ה’ שלא טענו אבות אחר מדותיו.
* לב:
** ויתור -
יש לדון מהו הצד להתירה:
א. לא נחשב הנאה, שכולי עלמא מתירין אותו, ואז צריך לומר שאינו כל כך חשוב. (יש לדון, שאולי רק אינו מזיק.)
ב. לא נחשב ממנו כל כך , שכל אדם היה נותן כן. יש לדון מה לנו בזה (ואולי יחסו לנתינה חלוק כיון שלא היה צ"ל הבעל אותו כדי שיתן. ויש לדון.)
** מחזיר -
יש לדון למה לא אומרים שיהא לו יותר ממון מחמת שלא הוצרך לקנות אותו חפץ, ואז נהנה (כמו שאמר גבי כלי שדרכו לשכור).
* לה.
** מה שיש,
אולי, מעילה ופדיון בקונמות משמע שיש בהם קדושה. ותחשב. מה שהוא רק כשנאסר על כולי עלמא הוא אולי שיסיבה שיאסר. זה מעשה על ידי קדושה אם אפשר. אם צריך ליאסר רק לחד, אינו אפשר. ותחשב.
* לו.
** על בישרא קאי -
יש להעיר שבמקום אחר אומר שהוא ברירה.
* לז.
** אי בקטן -
יש להעיר שיכול, אולי (עיין סנהדרין) , לקטן להיות לו בנים, אלא שיהיו קטנים מאד, ואז לא יתרץ משנה.
* לז:
** בנות -
יש להעיר שאין ללמד לבנות תורה. ואולי זה נשנה קודם שתקנו שלא ללמד.
** ואמרי לה -
נראה שמחלקת דלעיל תלוי ב"אמרי לה" זה. ותו"ת.
* לח.
** לא העשיר -
לכאורה (ואין זה קשה), היו כייבין להעשירו אף בלי זה כיון שהיה ראש ישיבה (עיין רש"י הוריות וכ"מ). ואולי היה מוחל על זה. ויש לדון אם יכול אדם למחול.
* לט:
** אם בריאה -
מניח גמרא שידע כן משה (שאולי יודעים כן
** לכבודי -
יש להעיר שגמרא מבאר למה יש צורך שיאירו. ואולי זה שייך אף להא דמשה. וצריך לעיין שם. ותחשב.
** א"ל אביי -
צריך לבאר מהו קושיא זה, שזה רק אומר שבלי מימרא מפורשת, לא ידוע מהו שכרו. ותחשב.
** דבי רבי -
אכתי אפרש ליטול ממנו עד שאין לו יותר מן הראשון שבא (והרי אין הראשון חולה). זה מניח שנוטל משמע שנוטל לעצמו. ויש לדון.
* מ.
** זן -
נראה שאולי זה המקור למה שאמרו חז"ל שחמות של חולה זן אותו. ותו"ת.
** ומי -
יש לדון, שיכול רופא לרפאותו. ואין לומר שזה רק כיון שה’ מתירו או כדומה, שיש לומר כן אף באש. ותחשב. ואולי ר"ל שאינו כל כך דיירקט.
* מט.
** זכר -
אם סובר שאינו תלוי בלשון בני אדם, יש לדון למה רק זכר הוא. ואולי רק ר"ל שלא מוכיח את הכל, כלא מוכיח מה שיש לתלות בלשון תורה.
** כותח -
אולי לכן הצריכו לכל כך כותח לחולים (שבת קמה:)
* מט:
** דלא כבבלאי -
יש לדון אם יהא כן אף לבבלאי.
** ביהודאי -
היה אפשר לו לומר "בנו" שאף צדוקי ישראל, ואז לשונו קצת מוזר. ויש לדון.
* נ.
** פורתא דתיבנא -
יש לציין למעשה שנכ’ ממאר"ק טויי"ן שאומר מעשה כמו כן.
** רשיעא -
יש לציין למה שמתו כיון שלא נהגו כבוד זה בזה. יש להעיר שרואים כאן מדתם של אי-נהגת כבוד.
* נא:
** דשליק
(וכדומה)- היה אפשר לומר שדן בשני צדדי רן. ותו"ת.
** קטנים -
היה אפש ר לומר שהוא קל וחומר, שרק צריך לומר שקטנים, שאינם צריכים כל כך, מתו, גדולים לא כל שחם. ויש לדון אם זה נכון.
* נב.
** זה -
בכל זמן שאדם נודר, לכאורה, אוסר אותם חפצים. אם כן, צריך ביאור למה אומרים זה רק אם אמר "חפץ זה.” אף יש לדון- ואולי שני הענינים שייכים זה לזה- איך אדם אוסר את עצמו על חפץ שאינו בעולם, אם אי אפשר לו לשנות את החפץ. ויש לדון. ותחשב.
* נב:
** מר כי אתריה -
יש לדון למה כופל את זה. אפשר שאומר שמשנה ראשון הוא כאתריה ומשנה שני הוא כאתריה. דחוק. גם אפשר שאף מבאר את רבנן. יש לדון, שאין קושיא עליהם (עיין ברן).
** עדשים -
יש להעיר שזה הציור האחרון במשנה שמביא מחלקת זה; מוזר מה שלא נקט ראשון. ותח’.
** איידי -
קשה למה לא נאמר כהוה אמינא של קושיה שללפני זה, והוא שיותר פשוט שהוא מותר. גם יש לומא שיש יותר צד לאסור כיוצא בו, ואז לא מותר. יש לדון.
* נג:
** גוש -
יש להעיר שגוש עצמו גזרה, וזה רק חשש לו, וכל זה רק מפני איסור להיות טמא, שהוא עצמו לכאורה אינו איסור דאו’ (במקום אחר כ’ על איסור ליטמא, אבל שכחתי).
* נד:
** שפיר אמר נחמני -
יש להעיר שלפי רשי, היה אביי יותר מעשרים שני גדול מרבא. אם כן, מעניין שרבא יקרא לו בשם זה. ויש לדון. ואולי גורס רבה.
** רבן שמעון -
יש להעיר שבמשנה אומר שהיו חכמים דנים בזה. אם נאמר שלא רק רצה לומר שדנו בבית מדרש אחר כך כאילו דנו בו ר"ע וחביריו, נוכל לומר שבעל המחלקת דן עם ר"ע. יש להעיר שהיה ר"ע יותר חבר של ר"ג. ויש לדון, שמת ר"ג קודם ר"א, שעצמו מת קודם ר’ יהושע. מאז, היה, לכאורה, בנו נשיא, ואז כבר נגדל, לכאורה, מאז, ואז בוודאי היה ר"ע קיים. ויש לדון.
* נה:
** גידולי -
מניח גמרא שאין לחלק בין גידולי קרקע לגידולו מן הארץ (ויש שני חילוקים ביניהם, כמובן).
* נו.
** כולי שתא -
לשון זה מעניין, שלא תלוי בימי שנה. ותו"ת.
* נו:
** למה לי שיפת -
מעניין למה לא אמר שאי אפשר לשפם, שהם מכוסים. אי אפשר שדן בשיפויים ללפני כן, שאין זה גמרו, ולא יקבל טומאה אז. ותו"ת.
* נו:
** בתחומה -
יש לדון למה יהא הוה אמינא לזה, שהיה צריך ריבוי לעיבור. צריך לומר שכיון שנתרבה עיבור, יש הוה אמינא לרבות תחום.
* נט.
** מאי מצוה -
לרשי, שענין דבר שיש לו מתירים הוא שאין צורך לסמוך על ביטול, קשה מה לנו בזה. ותו"ת.
* סא.
** ולא שנת -
יש להעיר שאין צד שהוא רק שנה ראשון, אלא רק שהוא אף שנה ראשון. ויש לדחות שאין זה מפני שהוא חלק ממה שבא לפניו, אלא שיהא חמישים כיון שהוא אחר ארבעים ותשע, ואף אם אינו חלק ממנו (יש לדון), אבל לא יהיה ראשון אם אינו חלק ממנו, שהרי לא התחיל אותו מנין. ויש לדון.
* סב.
** מכל מעשה של ר"ט
נמצא שחשוהו אף שידעו שר"ט הוא. גם מבואר שאף על פי כן, כיבדוהו. זה מעניין.
** רב -
יש לדון למה צריך זה, שהרי אף בלי זה, היה אפשר להשיג בלי זה, ואינו לפני עוור. אפשר שלא דן ממש בלפני עור, אלא באיסור לסייע. לא משמע כן מסתימות רן. גם אפשר שלא היה אפשר להם להשיג בדרך אחר. דחוק. עיין במש"כ השי"ח ש"י (רן) לתרץ את זה.
* סג:
** הא דפשיטא -
לשון פשיטא מעניין; משמע שלא רק צריך לדעת, אלא להיות שהוא פשוט לו. ועיין בלשון שאומר לcontrast, שהוא "לא ידע.”
** עד שיהא צום -
היה אפשר לומר ששם יותר פשוט, שאם נאמר ש"עד" רצה לומר עד תחילתו, קשה, שבין כן ובין כך אי אפשר לאכול בשר אז.
* סד.
** כיון דאיחפיץ -
יש לדון אם רצה לומר שפשוט הוא שאז לא חש לכבודם, ואז לא יועיל אם ישקר, או שאז אף עכשיו יחציף. ויש לדון.
** יש לדון
אם לאביי יחוש מפני שחושש לעשות רע (אם יאמר שלא רצה, יבזה אותם או יהא נגד כבוד שמים יותר) או מפני שאז יראו בני אדם שעבר בכוונה. ותו"ת. מסתבר כשני, שלראשון נצטרך להניח שישקר לזה. ותו"ת. ויש לדון. (ודע שאפשר לצרף.)
** נצים -
אז, יש לדון למה חולק ר"א. אפשר לסבר שלא משמע שהיו כבר עניים (אולי מפני שלא הזכירו קרא). גם אפשר שסבר שלא היה דתן ואבירם. אם כן, נמצא חידוש ש,חושב אני, לא ידוע.
** נצים ונצבים -
צריך לביאור מה זה משנה; כמו שלא מצינו שאמר שמת קודם, ואז מניחים שרק מת אחר כן, נאמר כן על עשירות. ואם לא, אין צורך להשיב כן על זה. אולי מניחים שהיה משה יודע בשעת נדרו אם כבר מתו. דחוק מאד, שלא ידע אחר זמן כשמתו.
** כי מתו -
יש להתמיה איך סבר רן שיודעים שנעשו עניים רק מפני שרק זה יגרום טוב למשה, שהרי אינו ידוע שהוא עניות בדווקא, שיש דברים אחרים שיהיו נחשבים כמת, ואם נאמר שקרו לדתן ואבירם, נוכל לומר שהם כמת. יש לדון, שאולי מסברה, אין דבר אחר שיש צד לגמרא שיהא חשוב כמת.
** כי מתו -
כיון שהיו, נמצא שהיו יהודים שהיו עשירים, אף שהיו כולם עבדים. זה מוזר. גם נמצא שהיו כמתים אם היו עניים, אף שה’ היה מזמין להם ממון (כמו דגים, כמו שמזכיר רשי על החומש (כן אני חושב)). ויש לדון.
* סה:
** רב נחמן ברבי יצחק -
יש לדון אם הוא אדם חלוק מרנב"י.
* סו.
** צריך ביאור למה אי אפשר
להתיר כל נדר כיון שירצה שבשום פעם ורגע אחת יוכל לעבור (שמסתמא יהא חד זמן שירצה לאכול אותו דבר), ויבטל מקצתו, ואז כולו. ותו"ת. וצ"ב.
** כבוד עצמו -
זה, לכאורה, פשוט, שהרי לא ישקר לזה. ותו"ת.
** שני זיתים -
יש לדון מה יהא הדין אם אוסר כל זיתים.
** מקלש -
אולי דיון זה שייך למה הוא שuתפות. יש להעיר ששותפות בזה אי אפרש ליברר. ותו"ת.
* סט:
** דאמר רבה -
מוזר, אז, למה לא פשט רבה מדידיה. ואולי ר"ל שרבה לאחר כן פשטו, ומביאים ראיה לזה. ותו"ת.
* ע.
** על ואני -
נראה שיש לדון למה הוה קיום:
1. רוצה בו כדי ששלו יחול. אז, רק רוצה בו לשעה.
2. לא היה עושה כן בעצמו אם לא חשב שהוא טוב. זה לא נראה, שאולי רק לו טוב. גם קשה, אז, מה אם כבר היה נזיר; אטו אי אפשר להפר.
אם כן, קשה למה יקיים יותר משעה אחת. אולי צד זה סובר שאם לא אומר שרק שעה אחת מקיים, מקיים את כולו (לא משמע לשונו כן), שלא מסתבר כל כך לחלק (ועוד שלא מסתבר שיאמר דבר שמשע- אף קצת- שרוצה בו אם, באמת, רק רוצה בו לזמן).
* עב.
** נסיב -
יש להעיר שיותר קל לנקוט סיפא אגב רישא (עיין זבחים (צא:). עיין תוס’ כריתות (יב:). יש להעיר שמוזר מה שלא מביא תוס’ אותו גמרא. יש לומר שרק הוה אמינא שם, ואפשר שהוא נדחה.) נראה שהטעם הוא שיהא מבלבל כשרק סיפא נקרא (שנקרא ראשון). ותו"ת.
* עב:
** אורחיה -
לכאורה, זה תירוץ אחר. ויש דלון. וצריך לחשוב.
** מטרידנא -
מוזר ליטרד עד שלא יוכל או שישכח לאומרו.
* עג.
** אותה -
צריך לומר שקאי על נשים (כן משמע לשון נקבות), שיכול להפר יותר מחד נדר בחד זמן (כמו במתניתין).
** לא מן השם -
מעניין לדרוש כעין זה, שיש בדרשה יותר מאם משמע; יש לדון גם כן כמה מסתבר הוא. ותו"ת.
** בית דין -
לא הבנתי כל כך כל זה, שלמה נחלק בין לפני שנים עשר חדש ללאחריו, שבשניהם הוא נקנה, לכאורה, ובשניהם יש חשש סמפון וכדומה. ותחשב.
* עה.
** מיחל חלים -
ביני וא.מ.וו. יצא שקשה איך יחולו ויבטלו; יבטל חלות ראשון כמו שיבטל חלות שני. עיין במקום אחר שדנינו בזה (חושב אני שהוא בחרב אל הבדים- ווינטר זמן).
לא יפר- אין מקור נגד זה בהקמה. אז, קשה למה לא נלמד הקמה מהפרה (שיש בו מקור מקל וחומר) לומר שיכול. אפשר שכל כך מוכרח מסברה שאינו כן שחזק מן הקל וחומר. דחוק.
* עז.
** אישתיק -
יש לציין לגמרא חולין עה:.
* עז:
** דחטאת -
מעניין שנחשב חטא, אף שלמפרע בטל. ותו"ת.
* עח.
** בניו -
נראה שאולי בא לרבות קרובים.
* עט.
** ר"מ אומר -
לכאורה, מוכרח, אז, שענין שהיית יום אינו שאי לא מחה עד כה, בוודאי נחית לו, והוה קיום (ויש לדון, שיכול, אולי, לשאל על שתיקה), שהרי כאן אין הוכחה שרצה בו. ותחשב.
** הנאת רחיצה עלי -
אין צורך שתתלה בדבר כמו רחיצה; יכול לאוקמיה כשתולה בדבר שאי אפשר לעמוד בו, כמו שלא לאכול, ואז בוודאי הוה נדר. אולי אז לא היה מזכיר התנאי. ויש לדון, שעדיין לא חל (וזה, לכאורה, ענין התנאי. ועיין ברן. (אגב, יש לדון, שצריך לומר שמתנה שיחול כשיעבור, ולא אם יעבור.)
* פא.
** מפני מה אין מצויים -
בימינו, מצוי הוא. באמת, גם בעיניהם היה מצוי, שראינו כמה וכמה בני אמוראים ותנאים שהיו תלמידי חכמים. ותחשב.
** רב ששת -
קצת ironic, שהוא בן של רב אידי, שהיה תלמיד חכם.
** ומפני מה -
לשונו (שיש וא"ו) משמע שאומר contrast, והוא שמבני עניים תצא, אבל לא מבני תלמידי חכמים. קשה, שאין זה חילוף זה. אולי עניים רצה לומר עניים בתורה. גם יש לומר שרק מונה מי שרגיל לצאת מהם תורה ומי שלא רגיל, אבל שאר בני אדם הם באמצע. ותחשב.
** משום דקרו -
יש לדון אם זה טעם חלוק. ותחשב.
** ירושה -
יש לדון מהו הבעיא בזה:
1. לא ילמדו מי שאינו בן תלמיד חכם.
2. לא יחשיבו בני תלמידי חכמים, שיחשבו שלא זכו מחמת שלמדו אלא מחמת שירשו.
** רב אדא בר אהבה -
חושב אני שזה המקום היחידי שמוצאים שיחלוק בפירוש. ויש לעיין.
* פא:
** לא מצינו שועל שמת -
העיר ש.ל. שאפשר שזה מן המשלות של שועלים (עיין סוכה כח.).
* פב.
** כל נדרים -
צריך ביאור מה מימרא זה, שלא מחדש שכל נדרים הם נדרי עינוי נפש (כן פשוט, ששוט שאינם, ועוד שלא מפרש כן רן), ואין חידוש לומר שמפירים כן נדרי עינוי נפש. ותחשב. ואולי רצה לומר שכל מה שנראה כעינוי נפש יש בו עינוי נפש. ודחוק.
* פד.
** דמוכחא -
ואף שיכול להיות שאומרת, “אם אתגרש… " כיון שלא עומדת ליגרש, ואף אין בידה ליגרש, לא מניחים שתאמר כן. ותחשב.
* פה:
** הואיל ואדם אוסר -
צריך ביאור מהו דמיון זה; הרי בנדר עושה איסור על החפץ, ואז פשוט שיהיה יותר צורך שיהיה לו החפץ משיהיה לו הגברא. וצריך ביאור.
** הואיל -
נמצא שאין נדרים כהקדש. אז, צריך לומר שלא רק נותן קדושה בהם. ואולי יש דרגות של נתינת קדושה. גם יש לומר שבהקדש לא רק נותן קדושה (אלא נותנו לה’), וזהו הבעיה.
** יקדשו -
ואם תאמר אם כן משנה את עצמו והוא שבועה. נראה שכאן משנה את עצמו, וזה גורם שינוי בחפץ, וזה גורם דין בחפץ. בשבועה, גורם שינוי בעצמו שעושה את הדין. ותחשב.
* פו:
** כי קדושת -
לשון גמרא משמע נגד ר"ת (עיין ברן).
* פח.
** רצה -
יש לדון למה אי אפשר ליתן לאשתו (שהרי, מותר ליתן חפץ לאחר ואחר נותן לחתן):
1. אפשר ששאני הכא שמוכרח לבא לבעל (או שאז נחשב גורם שבא לבעל או שאז נתינה לאשה נחשב הנאה לאיש)
2. אפשר שאין אשה קונה ואז קונה בעל, אלא מעשה אשה קנין לבעל. אז, נתן לחתנו.
* צ:
** בדיק לן רבא -
משמע שהיה רב פפא תלמיד רבא (כמו שכתב רשי עירובין (כו.)).
* צא:
** פשיטא -
יש לדון אם מקשה למה צריך גמרא לומר את הדין או למה צריך להביא קרא או למה צריך לומר כן קרא. ותחשב.
