** פרק כל כנויי
* ב.
** כל כינויי: נדרי הקדש -
יש לדון בדמיון זה לנדרי איסור. אולי רק יש להם שם דומה. יותר נראה שזה מגלה דמיון יותר יסודי, והוא מה ששניהם משנין חפץ. (וע’ (צריך לציין), שיש צד שכל נדרים עושים שום קדושה.)
** מס’ זו -
יש להעיר שאף שמס’ זה לא דן בנדרי הק’, אפשר שמשנה זו דן בו, שמזכיר כמה דינים. ויש לדון איך ייאמר. נצטרך לומר שהוא בכלל “נדרים.” דחוק שיכלל שני דינים (ותלוי במה מיוחסים שני הדינים).
** כתבתי -
העיר ש.ל. שנראה שכ’ הקדמתו אחר שכ’ פי’. (ואולי לא כ’ כל זה או כל זה בזמן אחד.)
** חרמים -
לא הבנתי את זה כ”כ, שלכאו’, אין בין נדר לחרם כזה. ואולי חלקם רק מפני לשונם.
** הסכמתם -
יש לדון, שזה רק הסכמת רבנן, ולא הסכמת אומה. ותח’. ואולי ר”ל שעשו רבנן שיאמרו כן, ואז, נעשה לשון אומה. וא”ת מה בראישון שאמר כן. ואינו ק’, שאולי אין צריך מה ששאר בני אדם אומרים כן, אלא מה שמבינין, ושלא נראה להם לשון מוזר, ומה שהיו משמשין באותו לשון אם היה להם צורך. ויש להעיר שאולי לשון ר”ן של “הסכמת רבנן” לא משמע כן כל כך. ואולי לא דן במי אומרין אותו, שלא במי תיקנו (וחידוש שזה נודע).
אינם גמורים- צריך ביאור מה לנו בזה. ואולי הוא לשיטתו (כפי מש”כ לעיל ד”ה הסכמתם) שיש ענין במי קבע את הלשון. ואכתי צ”ב למה יש חשיבות מי קבעו. ונ’ שהוא שדרך לשון לשנות. אם דבר נקבע, אז לא ישנה כל כך (נראה שני סיבות לזה. ראישון, נראה שאז יותר בני אדם ישתמשו בו ליותר זמן (ותח’.). גם יותר נראה שאז לעולם יהא מי לסמוך עליו, ש”נכון” הוא.), ויש לו יותר מיינינ”ג שלא עומד לשנות. (כיון שהגענו לזה, י”ל שכיון שטעות הוא, דרכו ליבטל.) זמן קיומו שייך מפני שענין לשון הוא דבר שבני אדם מבינים ואומרים. מה שכני אדם שלעתיד מבינין ואומרין, אז, אולי יהא שייך.
** ושבועות: עדות -
יש להעיר שמניח דמיון בין שבועת עדות לשבועת איסור, אף שלכאו’ בשבועת עדות לא “אוסר עצמו על חפץ” כמו בשבועה. ונראה אולי שהיא גופא, שכיון שאינם דומין בלומדות, צריך להיות שדמיון שמם בא ממה שלשונם דותה (וכעי”ז). אז, יש יותר מקום להק’ כמה שאמר.
** המוציא -
נ’ שקושייתו בא מלשון שמדמה שמיעת שבועה לאמירתו, שמניח שדוקא הוא. ותח’.
האומר:
** אי נמי -
לכאו’, אלו הם חד פשט למה יד הוא, ורק דן מה היה יכול לומר.
* ב:
** איידי: לשון
ר”ן משמע (וכן נראה מוכרח ממה שאומר בסוף ש”עיקר לשון נדר.” יש לדחות, אולי, שיש חילוק לומדי שתלוי בלשון שאומר.) שביאור גמ’ זו אינו לומדיש, ורק ר”ל שלשון זה משמע שאוסר חפץ עליו, ולשון זה משמע איפכא. צ”ב, אז, מהו עיקר החילוק ביניהם. יש להעיר שלקמן כ’ ר”ן שנדר איסור חפץ, ושבועה איסור גברא. משמע שיש איסור יסודי (וצריך ביאור, אז, למה לא פי’ כן כאן (אולי סבר שאינו כן בחרמין), ומהו מקורו.)
** משמע -
יש לדון מהו הראיה:
א. פשטות הוא שסבר שדיון גמ’ כאן הוא על לשונם. אז, מבאר שלשונם חלוק.
ב.אולי ר”ל שגמ’ מבאר שיש חילוק יסודי השייך ללשוונם. אז, מסתבר שלשונם מעכב.
** לאו בדוקא -
יש לציין לראישונים בקידושין (סא).
אם יכול לומר נדר בלשון שבועה ולהיפך, צ”ב מתי נעשה נדר ומתי נעשה שבועה. אולי תלוי בדעתו. אמר ש.ל. שאולי סתמו כעיקר לשון, ואם לא רוצה כן, צריך לפרש.
* ג.
** אלא לאו דוקא -
הוה מצי לפרש שלא נקטו לשום סיבה, אלא מפני שלא דק.
לעשות- אפשר שיהא קרא האומר שכינויי דרבנן הם דאו’, והוא שאי ירצו רבנן (או שיעשו כן) יתקנו מדאו’.
* ד.
** הואיל וכך -
יש להעיר שכאן לא רק מוסיף מלקות, אלא מגלה עוד דבר רע, אלא שכבר יש רעה אחר בו. ותו”ת. (ואולי כל הוספץ מלקות כן.)
** והרי חטאת יולדת -
יש להעיר שגמ’ שם אומר: “שאלו תלמידיו את רבי שמעון בן יוחי מפני מה אמרה תורה יולדת מביאה קרבן אמר להן בשעה שכורעת לילד קופצת ונשבעת שלא תזקק לבעלה לפיכך אמרה תורה תביא קרבן.” אז, קשה לומר כמש”א ר”ן.
* ד:
** קשריא -
מצוה- מ’ שהיה קשה לו שאי רק ר”ל שחשוב כיון שמתיר, הרי אף בנזיר מתיר (יש לדון, שאינו נצרך, שיכול לגלח על קרבן אחר.), ואז אומר שהענין הוא שצ”ל שהוא היתר הנצרך, והוא היתר של מצוה.
* ה:
** מה נזירות -
ע’ במנ שבאר. אפשר שמח’ זה תלוי במקור יד (אם נל’ מנזירות שיש לו דין הפלאה או מנדרים שאין לו אותו דין (ויש להעיר שמגמ’ סנהדרין (כה.) משמע שיש אותו דין בכל.)
* ו:
** דאמר לה -
הוה מצי לאוקמיה כשקדשה בדבר שמהנה את שניהם, כגון שרקד לפניהם.
* ז.
** ולענין הל
’- יש יד- יש לדון אם רק יש יד להחמיר (ואז, צריכה גט משני) או שיש יד כיון שבדר"כ הוא חומרה. יל"ד למה נאמר כשני.
** מנודה -
יש לדון אי ר"ל שחכך ביצמו לגלות צער או שחכך את ראשו כדרך בני אדם שמחשבים.
** ולענין הלכה -
דלית דחש- יש להעיר שהו"מ לומר שזה רק מפני שסבר שמח’ הוא חלוק, ובזה אין סברת ר"ע מסתבר. וי"ל שלשונו משמע שדן במה נוהגים, ואז לא יתלה במה הוא המחלקת.
* ח.
** וכי עייל -
יש לדון אם שני מנודים יכולים לקרב זה אל זה. אם יכולים, יש לדחות שזהו הנפקא מינא של דיון של גמ’ של תשמיש מי שמנודה. ותו"ת.
** הא קמ"ל -
יש לציין לתוס’ קדושין שלנו (טו:).
* ח:
** שמתא -
כגון אנא- יש לציין לסוף סוטה שאומר ר"נ כן שם. אולי משמע שהוא אותו ר"נ (ועיין בחבורה שכתבתי שם).
** שמתא -
אי צריך להיות סמוך הוה מצי לומר שלכן לא התיר רבינא לאשתו בפני עצמו, שלכאו’ לא היה סמוך.
** בעל -
מכנפי- יש להעיר שלשון גמרא של "כי מכנפים. . . “ משמע שקאי על היתר שלא בפני רב.
* ט.
** מתני
’- רשעים בזה- עוד יש לומר שדרך רשעים בדרך כלל לנדור.
** מתניתין -
יש לציין לרש"י פסחים (ח:) ור"ה (ד.) בנותן פרוטה. שייך הוא למה שכתבנו בדיבור הקודם. ותחשב.
** מתניתין -
מסתברא- כן אומר גמרא, לכאורא. אולי רק ר"ל שאומר גמרא שמסתבר. . . .
** כנדבותם -
זה מעניין. ולא הבנתי, אז, למה אינו אף לנדר. (ובאמת הערה על גמרא הוא.)
** כנדבותם -
משום הכי- יש לדון מהו היחס בין זה לרצונו. אפשר שרק סימן הוא (שרוצה בו כל כך שכבר בחר) או שהוא סיבה (שלא יטרח כל כך, שלא חייב באחריותו). נראה שיש אולי עוד צד של סובה, והיא אולי שאין לו רצון כל כך כחשוב בקרבן עדיין, שאין קרבן, ואז אי אפשר שיהא לו רצון בחפץ הקרבן. ותחשב.
* ט:
** פחז -
יש להעיר שדורשים מילה זה בשבת לומר, לכמה שיטות שם, שלא גבר יצר הרע, שהציל את עצמו מיניה. ותחשב ותבין.
* י.
** כולם -
נראה להעיר שאביי אומר כמה "כולם . . . " בש"ס. נראה שהוא מפני שלא דק כל כך בביאור מה נחשב אותו שיטה. גם נראה להעיר שאולי מה שלא דק כל כך הוא קצת לשיטתו, שמצינו בכמה מקומות שרבא ידחה פשטו של אביי מפני שלא דק (ובפרט מפני חסרון "לא"). נראה שאביי לא דק כל כך בפשטיו כיון שלא דק כל כך בביאוריו (ואז לא הניח שאחרים ידקדקו כל כך). ותחשב יותר.
** משום -
לכאורה רק רצה לומר שעשה חטא אחר (אף שאינו שוה כלל לחטא קמא. ואולי (חלק מ)איסור ליטמא הוא שאז צריך גילוח וכדומה וסותר, ואז מצער את עצמו יותר. ותחשב.
* י:
** לא משתעי -
צריך לחשוב על הסברה בזה. ויהא כמה שמתבנו לעיל (עיין שם, והוא על הר"ן הראשון).
** לחולין -
יש להעיר שלא מצינו דכי גבי איסור הבא מנדר (ולהיפך, מצינו בתורה שאומרו גבי איסורים אחרים). ונראה שר"ן סובר שפירושו שוה ל"אסור," ואז כולל כל מיני איסור. ותחשב.
** הק
’ לי ש.ל. למה מביא ר"ן שיש אומרים פשט ושאינו נכון אם לא יאמר הפשט. ונראה שאומר שאם תראה מה אומרים, דע שלא נכון הוא (ואם לא תראה, אז יותר טוב). ותו"ת.
** יא: בעיקרו -
זה מעניין.
* יג:
** באומר -
זה מראה מקום.
** באומר -
זה לשיטתו ש"באומר" ר"ל שנעשה כאומר, שאי לאו הכי לא היה לו לעשות אוקימתא, והיה אומר אמת. ותחשב ותבין.
* יד.
** הלכך לענין הלכה -
מה שאומר "קדושה" מעניין. אולי לאו דוקא הוא, ורק רצה לומר שיש לחפץ מה שיאסרו. ודחוק.
* יד:
** ה"ג -
שעל ידי- מעניין שזה עושהו דבר הנודר.
* טו.
** רבינא -
צריך ביאור מה מביא ממה שיש תנא אחר המשתמש בלשון זה על דרבנן; פשוט שנוכל לעשות כן, שזהו אסמכתא (אולי ר"ן לא סבר כרמב"ם, אלא כריטב"א.) ותחשב.
* טז.
** ותו -
לקמן אומר "ותו אמר.” יש לדון למה משנה. ותחשב.
* טז:
** על -
מעניין שדין שבועת שוה עושה שנחשב שיש קצת שבועה, שלכאו’, חלוק הוא. ותחשב.
* יח.
** הלכך -
זה מעניין. ותחשב על כל זה.
* יח:
** לא הקדיש -
אמרינן- משמע שהוא מפני שאפשר שלא נכלל בתוך לשונו. לשון גמרא משמע שהענין הוא שכיון שיש אותו ספק, בוודאי לא כיוון לו.
* יט.
** מאי איכא -
יש לומר דהכי פריך- צריך ביאור למה ייתלו שניהם אהדדי. נראה שיש לכקור מהו קושיית גמרא "מאי קמדמית":
א. אפשר שמקשה שאין טעם ר"א שייך שם, שאין תנאי בעליו שייך, שלא הוא הקדישו.
ב. אולי ר"ל שלכן הוא יותר חמור. יש לדון למה לא נאמר כראשון.
אם נאמר כשני, נוכל לתרץ.
** מאי איכא -
הוה מצי לומר שר’ אלעזר ור"א אינם חד (ששני הוא רבי אליעזר). אולי, אז, גמרא רק מניח (ודחוק) שכיון שהוא תנא דרישא, סובר כסיפא. ותחשב ותבין.
* יט:
** אי תניא -
עיין במה שכתב. ויש לציין לרש"י במקום אחר שלא כתב כן. ואולי חלוק כאן שסמך על מה שלא תני. ותחשב.הא מכירים- אם יכול לומר ששניהם להחמיר כמה שאמר, צריך ביאור למה לא אמרו. ותחשב.
* כ.
** ולענין הלכה -
יש להעיר שיש משנה לקמן בסתם נזירות שסאתר זה, ויש מחלקת כאן. אם כן, יהא סתם ואחר כך מחלקת ואחר כך סתם. יש לדן מה יהא הדין. יש להעיר שהובא מחלקת ר"ט לאחר כן. אם כן, יהאסתם  ומח’ וסתם ומח’. ואם נאמר שראב"צ הוא, יהא מח’ וסתם נחסר מח’ אחרון. ותחשב על זה.
** הואיל -
ע’ במעשה שמביא. אם נזיר צריך להיות נשיר רק לזמן מועט של נזיר, יהא נדר נצרך רק לשעה. אם כן, צריך ביאור למה לא היה אפשר לו.
* כ:
** אונס-
יש לדון למה, אז, אין כוללים אחרים (עיין בציורים, שיש שדומים). ואולי הוא רק מפני שאין דרך קל לכוללם, שאין להם אות שווה.
* כב.
** ההוא -
זה שיטה מחודשת.
* כב:
** אמר’ -
יש להעיר שיש שני מיני "אין נזקקין,” כמו שאמר לעיל. שיש שאין ליזקק ויש שאין חיוב ליזקק. ותחשב.
* כג.
** כל -
עיין במה שכתב לבאר למה אינו נולד. יש להעיר שאז מעניין למה לא חשב עליו בעת נדרו.
* כג:
** ולענין -
צ’ לחשוב על הא דהדירו חבירו.
* כד.
** יתר -
היה אפשר לומר שחידושו הוא לדחות סברת צד ראשון.
* כד:
** ולענין הלכה -
יש להעיר שזה יתלה אי הלכה כמותו בברייתא (עיין בר"ן לעיל).
* כה.
** למקח -
יש להעיר שלירושלמי, אין קושיא ד"כל נחש . . .”
** למקח -
מילתא רבא- יש להעיר שמקשה למה מדמה אותו כלל ומביא ראיה ממה שכשמדמה אחר מזכיר גדול. ותו”ת.
* כה:
** מתני’ -
שוגג- צריך לחשוב על זה.
** היכי דמי -
ולא הבין- מצינו בהרבה פעמים שלא חולקים מה כיוון אלא מה אמר.
* כז:
** עיין במה שכתב
שנחשב הודאה. אם הודאה הוא מחמת נאמנות, צריך ביאור איך מתנה עליו. אם מחמת מתנה הוא, הוה אסמכתא. ותחשב.
* כט.
** וכי -
קונם פרטי- לא הבנתי כל כך מה לנו בזה. ותחשב. ויש להעיר ששם לא אסרה אלא הנאתה, ואז יש לומר שאינו אותו חפץ, ולא נפקע, אלא רק לא חל. ויש לדון, שאין הנאה בעולם, ולא נאסר, ואז צריך לומר שהיא הנאסרת.
** אלא על אשתו -
לא הבנתי, שאינו חל זה אלא על הנטיעות. ותחשב.
** אמר ליה -
צריך לדון מהו קדושת הגוף וקדושת דמים. יש להעיר שכאן משמע שמשווה קדושת הגוף לקנין הגוף. הוא, לכאורה, שלו היחס, ולא רק דיני בעלות נגרמים לו. אם כן, חילוק בין ק"ד וקה"ג יהא אי של הקדש הוא או רק שיש להקדש דיני בעל (שמקבלים הנאתו).
* כט:
** אמר ר"פ -
עיין במה שכתב שלא נחשב שפקע. נראה שיש לדון אם קדשי קדשים (וכדומה) הם קדושה חלוקה מקדשים קלים או רק מוסיפים קדושה. משמכ מכאן כצד שני. ותחשב. ותו"ת.
* ל.
** ואשה -
לא הבנתי כל כך, שאכתי חלות אפשר לו לחול לאחר זמן. אז, יהא כקדושה, ויהא עושה סיבה לעולם. ותחשב.
** מאוכלי -
יש להעיר שלכאורה אין כותים תלמידי חכמים. צריך לומר שאף על פי כן, תקן עזרא לכולי עלמא.
* לא.
** שאיני -
לא יהא שוה ממש, ששם יהא שבועת שוא, שאי אפשר, ואז לוקה. יש לדון מה יקרה כאן. ותחשב.
* לא:
** בזבינא -
יש להעיר שאכתי נהנה מיניה, שיש לו אותו חפץ שיביא לו הנאה, והוא ממנו. אולי מה שיכול להשיגו מאחר עושה שאינו כל כך ממנו. ותחשב.
** מתנינין -
עיין במה שכ’. זה מראה מקום. ונראה לבאר על ידי זה (כ’ כן במק"א) שלכן מקשה גמרא מבריי’ אף שכבר אמר תירוץ שקל לתרץ בו אותו בריי’, והוא שרק רוצה לבאר אותו ברייתא, כדי שכשתלמדנו לא יהא קשה לך. ותחשב.
* לב:
** השטן -
יש להעיר שיום הכיפורים הוא מימי לבנה, ולא חלה. ואולי עושה אברי"ג עם שנים מעוברים (ואז, יש שנה שיש בו יותר משס"ד ימי שטן).
* לה.
** למעול נותן -
יש לדון למה יהא הנודר מועל. יש לומר שגרם ס"ר. לא נהירא, שאף מנבל כן. גם יש לומר שנדר עושה שחפץ עושה ס"ר לעצמו. ותחשב.
** אמר ליה -
צריך לחשוב למה זה נכון.
* לה:
** ומלמדו -
יש להעיר שאי נהנה ממנו כיון שהוא מעשה טובה, יהא אסור כיון שיש בו הנאה.
** חוץ -
צריך לומר שסברה שאומר לא די בפני עצמו. גם יש לומר שמקור של ר"י מגלה שאינו לכפרה.
** שלוחי -
יש לדון למה אין נמה שגורם לו כפרה הנאה.
** משמשות -
איכא למימר. יש להעיר שמוכרח שאומר כן שם ביבמות.
* לו.
** אלא -
על ידי מעשה- יש להעיר שפיגולו נעשה רק על ידי דיבור, אלא שאומרו כששוחטו. ואולי זה חלק ממה שמפלגו.
** הריני -
ר"ל שאי אפשר שממש אומר כן כששוחטו, שאם כן הם כבר בירושלים. (ואולי ידע שיצאו ויבואו.) כיון שכן, קשה מהיכי תיתי שכבר שחטו.
** הכא -
צריך לפרש כל זה.
* לז.
** שכר בטלן -
יש לדון למה אין אומרים, אז, איסור מחמת זה. ואולי מיירי בדלא בטל או שנטל. גם יש לומר שיכול למצא אחר שלא היה בטל, ואז לא נהנה. יש לדון, שמה שיכול ליקח ממון מעיד שאין כל כך אחרים כמותו.
** בקטן -
כמובן, אין קושיא זה קשה לרמב"ם (שיש איסור לנודר).
** חוץ -
צריך ל ומר שהסוברים שר"ע ושלמה היו חכמים מיניה חולקים על זה, שלכאורה לא ידעו את ה’ באמיתו.
* לח:
** לזןו -
יש להעיר שעל אשה, צריך להיות כדי חיה, שעל יותר מזה איין לו חיוב, ואין חידוש. ואולי יש לו חיוב על קצת יותר מכדי חייה ממש.
** המדיר -
לולי רש"י היה אפשר לומר שהוא הותרה, ולא דחוייה. יש לציין לגמרא עירובין סה.. ותו"ת.
* מ.
** אין -
זה מראה מקום.
** אין -
יש לדון למה יותר קל להתפלל לו שימות:
א. אין בו כל כך הנאה. תחשב מה לי בזה. יש לומר שנגזר רע על אותו אדם, ולא נשתנה כל כך בזה.
ב. אינו משנה כל כך, שעומד למות. אפשר ששניהם שווים. ותחשב.
** בתרייתא -
היה אפשר לומר שחוששים שיתפלל שימות.
* מ:
** ולענין -
וחכ"א- אין לנו גירסא זה, לכאורה.
* מב:
** כי פליגי -
יש להעיר שהיה מלמד לנו נגד רב.
* מג.
** אר"י -
יש להקשות למה מזכיר שניהם (למה צריך ששניהם נדרו).
* מד.
** רישא -
כזכי מהפקר- כמובן תריך לבאר את זה. ותחשב.
* מד:
** ופרכינן -
יש להעיר שלכאורה, תלוי לא בהיותו הפקר, אלא ביכולת כל אדם לקחתו (שאז יש לכהן חלק בו), ואז זה יהא כן.
* מה:
** השותפין -
צריך לחשוב על כל זה.
** כמה סתמות -
יש להעיר שאין עודף לכמה סתמות מחד (עיין ביבמות).
* מו.
** אי אמרת -
יש להעיר שדרך הרמב"ם לפסוק לפעמים כירושלמי.
* מח:
** אמרי’ -
לא הבנתי סברה זה. ותחשב.
אמרי’- צריך לחשוב למה בא שאר לבן האחר. ותחשב.
* נ.
** אילא -
יש להעיר שלא עשה מה שצריך לעשות כאן, כמובן.
* נ:
** כי היכי -
לולי ר"ן, יש לומר שרוצים לבלעו.
* נא:
** הנודר… מותר -
בגמרא שלנו אומר שהוא אסור. יש לדון למה. אפשר שסתם טרית טרוף כל כך עד שיש בו  ציר של אותו דג (וגם נותנים בו מורייס), ואז אלו נאסרו. ויש לדון.
* נג.
** כוסס חיים -
היה אפשר לומר סברה להיפך, שאי אפשר לעשות לחם מחיטה אחת, אבל אפשר לכוס רק חיטה אחת. ויש לדון.
** ולענין הלכה -
יש להעיר שכאן מצינו תנא קמא סתם (שלכאורה, בדרך כלל נעשה רב מפני שהוא נסתם קודם המחלקת) חולק על רבים. הדין, אולי, ייתלה על מה שהבאנו לחקור ביבמות, והוא אי סתם ואחר כך מחלקת מגלה לנו שרבים אמר דין ראשון (שאז כאן יהא רבים החולקים על רבים. ויש לדון, שאולי יגלה לנו שרבים יותר אמרו הסתם) או שנחשב דין ראשון כרבים, והוא שהיו בטוחים שהלכה כן כמו ברבים ויחיד. ותו"ת.
* נד.
** והא מן -
צריך לבאר בכל סוגיא זה ש, על כל פנים לפי הבנת רן, יש שני ענינים כאן, והם כמה דבר נשמע מהמילה ואם יכול אדם להבין רצון לדבר אחר מן המילה. אפשר שאף אי לא נשמע כלל, יכול אדם להבין רצון- אולי מי שרוצה זה גם ירצה זה. נמצא לפי רן שההגדרה הוא שאם יש רק שני, אינו אסור. אם יש עמו קצת מראשון, אסרו, אבל אל חייב (יש לדון למה יאסר ולא יחייב. ואולי ר"ל שהוא מדרבנן.). אם יש ראשון לגמרי (ואפילו אם אין שני. כן אני חושב שאומר לקמן, ואולי אינו נכון בזה.), אז חייב. ויש לחזור על זה.
** אמר עולא -
מייתר לישניה- היה אפשר לומר שזה הוא המחלקת ר"ע ורבנן, וחולקים אם לומדים מלשון שמוסיף, ואז יהא ר"ע לשיטתו (עומקא ורומא, בב"ב), אלא שגמרא ביאר ראיתו וראית רבנן.
** באומר -
בעו בישול טובא- מהמשכו, נמצא שלא רצה לומר שצריכים בישול רב, אלא שמאד צריכים בישול. ויש לדון, שאולי אומר שצריכים בישול רב, אבל אומר כן מפני שזה בינן למה שמאר צריכים בישול (אבל אמר את הסימן כי אולי חשב שזה הנשמע מלשון מתבשל. ויש לדון.)
* נד:
** ואמר -
קרי ליה הכי- יש לדון מהו "הכי"- אביי או נחמני. ותו"ת.
** אף על גב -
יש להעיר שעדיין יהא כרבים (ויש לדון, שכאן החולק הוא הסתם). ויש להעיר שהמשכו של רן מוזר, שאומר זה לטעם, ושוב ממשיך לומר שאולי אינו סתם והלכה כמותו לטעם אחר. ותו"ת.
גם יש להעיר שהלככה כרשב"ג בכל משנה חוץ משלש. צריך למור שזה רק אי נזכר. נמצא שסתמו רבי ועל ידי זה גילה (ואולי כדי לגלות, שיש לדון אי ידע רבי (ואולי מפני שישדע רבי יש שום כלל) כללו של רבי יוחנן שהלכה כרבן שמעון.
** בדכיבין -
צריך ביאור למה כן הוא, שאף שאפשר שעדיין יהיו מכאיבים ליה, אינו מוכרח, ואז יאסור דגים כיון שאין הכרח שאין צריכים איסור. ותו"ת. ואולי ר"ל שאין הוכחה שאוסרם, שאולי מניח שאין צורך. ויש לדון.
* נה.
** הכל -
דברי יחיד- ועוד שהוא בדברי יכיד שעליו חולקים.
יש להעיר שאולי משמע מרן שמה שהוא דברי יחיד הוא סיבה להניח שיש חולק. עיין ברשבא ב"ב (קל).
* נה:
** ועל -
דברייתא- לכאורה, משנה הוא. אולי קורא למשנה בלשון "ברייתא.” מוזר הוא. גם אפשר שסובר שגמרא מביא ברייתא כדי שלא נדחה לומר שאף שמביא ברייתא שאומר שכן ברכתם, חולק על המשנה בגדר מהו שהכל. אז, מניח שמה שמביא הוא רישא של אותו ברייתא.
** תוס’ -
הלכך אנו- צריך ביאורלמה צריך תוס’ כדי לומר כן. ותו"ת.
גם יש לדון אם זה מפני שלשון תורה נעשה לשון בני אדם, שרק אומרים מה קוראים שמות בעברי מפני שכן אומר תורה, ולא מפני שכן אומרים בני אדם, או מפני ש יש שני סיבות לשם, וכיון שאין סיבה של קריאה, צריך ליתן לו שם על פי מה הוא שם שבתורה, ולא מפני שכיון שאין מדברים בו בני אדם, כך מפרשים אותו רב בני אדם. ותו"ת. אולי לצד שני מביא שיש ענין שם מלשון תורה, אף אי לא מבינים אותו בני אדם כן (שאין לו שום הבנה). ראיתו הוא ממה שיש שיטה שזהו הקובע, ולא מסתבר שחולקים כל כך שהחולק לא מחשיבו כלל.
* נו.
** כולה -
מהיכי תיפוק- אם זהו הקושיא, יש לדון איך מתרצו גמרא. ותו"ת.
* נו:
** מנלן דעיבורא -
היה אפשר לומר שלא דן בע’ אמה אלא בריבוע של העיר (חושב אני שגם הוא נקרא בשם עיבור).
** ילך לביתו -
לולי רן, היה נראה לומר שלא צריך להסגיר ממש, אלא שאומר שצריך הסגר.
* נז.
** העלה בידו -
על פי זה, נראה שיש לבאר יותר מה שאומר גמרא ב"ק לר"ע, “ולא העלית בידך… ,” שהוא פון, שהוא לשון של אמירה, דהיינו שאין לו מה לומר, ועוד שהוא נגד לשון העלה נגד הליכה בסוף מים.
* נט.
** והקדש -
גם יש לומר שיש מצווה כיון שנותן להקדש ממון, שצריך יותר משום חפץ.
יש להעיר שאינו קאי ע ל כרחך לפדייה, שיש שיכול להשתמש בו בבנין. יש לדון, שאולי אז אי אפשר לפדותו, כמו שאי אפשר אם כבר נבנה ממנו. ויש לדון.
* ס.
** שנה זו -
ר"ח תשרי- הוצרך לכתוב כן כדי לבאר על איזה ראש השנה דנים.
* סא.
** אסור בה -
פשיטא- יש לדון למה הוא כל כך פשוט, שיש צד שנודר כפי שנה רגילה. ויש לדון.
* סב:
** והלך -
לצד ראשון, יותר מבואר למה נלמד מ"והלך," שהוא בהליכת מלך. לצד ראשון, יותר צריך ביאור.
** רב עצים -
יש להעיר שאם כן, אין צריכים מה שהוא רב, אלא מה שהוא ספק.
נראה שיש להעיר במה שספק מותר, שאיסור לפני עור הוא לגרום שעושה רע. אפשר שאז אם בליהו לא היה עושה הרע, אסור אף לגרום ספק. אם היה כבר יכול, אסור רק אם גורם וודאי. ותו"ת. נראה שאולי זה יבאר מה שהקשה השי"ח ש"י (גמרא).
* סד.
** רסי אליעזר -
לשון אחר- היה אפשר לומר ששנים אלו הם שווים, ושלכן נקרא כן. (ועיין שם, שדן בבת כהן שזינתה, שאי אפשר שאביה עשה כן, שאינו בת כהן, ואינו בת בכלל. אז, אולי אי אפשר שלמד ממנה. ויש לדון, שעדיין אפשר שזנה עם אשת איש או כדומה. ותו"ת.)
** אמרו -
יש לדון אם רצה לומר שסתם בני אדם לא מקפידים כל כך לומר שלא חשו למצוה או שמי שאמר נדר- שהוא רשע- לא יקפיד לומר כן (או שלא יבייש כל כך (או שלא מחשיב אותו או שבין כך ובין כך ידוע לקצת רשע) או שלא יאמינו לו לומר שהקפיד). (גם יש להעיר שלא רק דנים במי שנדר, אלא במי שעכשיו הוא משקר לחכם. ותו"ת.)
** ירושלמי -
לכאורה, זה פלא, שאף כבוד אב ואם ככבוד שמים (כן אומר בבלי בקידושין, ואף ירושלמי עצמו בפאה). אז, צריך לומר- וכן היה נראה מסברה- שלא ישקרו בני אדם לומר שחשו, שהוא ככבוד אביו, ואין בני אדם מחשיבים אותו. ותו"ת. וצריך ביאור.
* סד:
** ירושלמי -
מצוי- צריך לדון מה לנו אם הוא מצוי.
* סה.
** היכא -
יש להעיר שידוע מה שאומר רשי גבי פרעה (הוא גמרא סוטה לו:). נראה שלא אמר שישאל על שבועתו כיון שאי אפשר כמו שכתב רן כאן. ותו"ת. יש להעיר שגמרא אומר שישאל על שבועתו; אז הוא קשה על רן. אולי צריך לומר- ואולי כן אומר רשי זה- שגמרא לאו דווקא, ואינו ממש שואל, אלא עובר.
* סה:
** שמא יעני -
עיין בגמרא שלנו שאומר "שהוא עני." כן משמע, שאי לאו הכי יהא נולד. יש לדון, שאולי אסור כיון שיש לחוש שיעני. ויש לדון.
* סז.
** קיים ליכי -
דומה- גם יש לומר, ואולי כן אומר, שאין זה קל וחומר, שיש בכלל ראשון שני, והוא אותו דין עם יותר סיבה שיהא הדין כן. ותו"ת.
* סח.
** ורבה -
בא לומר שלא מקשה איך דוחה אותו ברייתא של תדר"י, שלא דוחהו. יש לדון איך דוחהו, למעשה. ותו"ת.
* סט.
** שמע - -
לא שיפיר
ואם תאמר כל הפר הוא רק שאומר שאינו רוצה בו, ואז מה לנו מה מיפר. יש לדון. ואולי אין הכי נמי, ורק דן למה צריך להפר עוד. ותו"ת.
** בעי רבה -
דלא גרע- קצת יש לדון למה אי אפשר לשאול על השתיקה (או מהיכי תיתי לרן שאי אפשר. אולי אפשר ורק אומר שיצטרך לשאול אף עליו, ולא רק על הפר.
** ואת"ל -
יש לדון בחילוק הפר והקם ובדמיון לנדר. ותו"ת.
* סט:
** בעי רבה -
צריך ביאור למה פשוט שהפרה חל אי לא מתנה שצריך לחול אחר הקם, שהרי אם הקם חל, לא יחול הפר, ואז לא יחול הקם, ואז יחול הפר, ואז יחול הפר… ויש לדון. אולי ר"ל שלשונו משמע שרוצה יותר בהפר, ואז זהו החל.
* עא.
** מנא -
מחודש הוא שמה ששמע אב בעיא לבעל; ברי באו לא שמע. יש לדון אם הוא בעיא להפרת בעל או ליכולתו לצרף עם הפרת אב. גם יש לדון למה יש לו יום מזמן שמיעה. הפשטות הוא שיש לו אותו זכות, והתורה מגדיר כמה זכות יש לו. גם יש לומר שאם לא עושה עד אותו זמן, מסתמא רוצה בו. כל אלו, לא יבארו מה שיהא בעיא בבעל. וצריך לחשוב.
** אביה -
כרעא- כמובן, צריך ביאור מה זה אומר. אפשר שנעשה על דעת מי שיזון אותה, והרי נשתנה מי שיזון אותה. אז, נכלל לאותה סיבה של בעל ראשון. ותחשב. ויש לדון.
* עא:
** ואהדרה -
שכיח- יש לדון אם זה השכיח, שהרי כבר גירשה, ולא רצה בה. ותו"ת.
* עב.
** ולענין -
שמואל- יש לדון, שאולי לא קבל לשנות כן, אלא קיבל שכך הוא הדין.
* עג:
** ואיכא -
יש לדון למה יחול הפרה כשנודר על דעת אחר כיון שאינו תנאי (שאינו למפרע). צריך לומר שהוא כאומר, “ … עד שלא ירצה זה.” יש לדון. גם יש לומר שגמרא לא יודע הבנה לו, ורק מגדיר חידוש תורה של הפרה.
* עד.
** שומרת -
אין זה המסקנא, לכאורה, אלא חד צד שבו. ותו"ת.
** שאין לאחרים רשות -
יש לדון אם זה סיבה או סימן. אם הוא סימן, יש לציין לסברת רשבם בבא בתרא (קלה (גבי אי קדם וזבן, שמוכיח שאינו קנין)).
* עד:
** אמר -
דקדושי- משמע, ויש לדחות, שהוא קדושין ממש, ואין חילוק ביניהן חוץ ממאיזה מצב התחיל.
** האומר -
עיין איך מפרש כאן. יש להעיר שמצינו בכ"מ שלא ר"ל כן כאן, אלא אומר בעכשיו, כמו מכאן ולהבא. אז, ק"ק למה לא פירש כן רן.
* עה.
** ולענין -
יש להעיר שהיה ר"י רבו של ר"ע. גם יש להעיר שר"י הוא המכריע. ותחשב.
** אי אמרת -
יש להעיר שאם חל למפרע, לכאורה, אי אפשר שיהא אב מבטל מחצה, שכל שניטל מחצה ביטל כולה. ואולי זה רק בביטול חכם. ותחשב.
* עו:
** להקל -
לאו דווקא- צריך ביאור למה לא שייך כאן חומרא וקולא. ותחשב.
* עז:
** ורב -
יש לציין לשיטת הרן בתחילת דין בלילה, שהוא מחמת שכולו המשכו. ויש לדון אם זה שייך לכאן. ותחשב.
** תניא -
עתיד- יש לדון אם אומר שגמרא אומר לשון עבר, אף שדן בציור של אחד שאמר לשון עתיד או שדן במי שאמר לשון עבר, וכיוון לחלות לעתיד, ואף על פי כן, חל. (עיין ברשבם בבא בתרא מג.)
** ובעל -
אמר אין כאן- נראה שיכול כיון שעושה שאין כאן נדר.
* עח.
** אמראב"י -
ופשיטא- יש לדון מה אומר:
1. אינם נכללים כיון שהוא פשוט שהם פסולים.
2. אינם נכללים לשום טעם; ומביא ראיה לזה ממה שפשוט שאינם כשרים.
3. נכללים, ואין בעיא בגברא, אלא שלא עושים מעשה הנכונה, שלא "מתירים.” ותחשב.
* פא.
** ירושה -
עיין במה שפירש. לא משמע כן לשון גמרא; אומר "שלא יאמרו… ," ולא "שאומרים ירושה… ." משמע שעושה ה’ שיותר קשה להם להיות תלמידי חכמים כדי שלא להראות שהוא ירושה. יש לדון למה יש צד שיהיה ירושה:
1. אולי חושש ה’ שבני אדם יחשבו כן כיון שיש הרבה שררות וכדומה שהם כן.
2. אולי יש יותר צד שמהם יצא תורה (שגדילים במקום תורה), ואז, יראו בני אדם שרב תלמידי חכמים הם בני תלמידי חכמים, ויחשבו שהוא ירושה. אם כן, אולי ה’ רק עשה שהוא שווה, וגמרא רק אומר שלא מצוי כמו שהיה מסתבר להיות מצוי. ויש לדון (ש"מהם תצא תורה" אולי לא משמע כן. ואולי אין הכי נמי, הם יותר מבני תלמידי חכמים, אבל אין בני תלמידי חכמים פחות מרב בני אדם.)
** ולענין -
מעניין שלא נחשב דברי רבי יוסי סתם. נראה- ושוב ראיתי שכן אמר בפירוש- שכיון שמשמיע שרבי יוסי אומרו אינו סתם, ואף שלא נכתב שמו במשנה. ותחשב.
* פא:
** קונם -
איכא פלוגתא- לשון "פלוגתא" בדרך כלל משמע מחלקת. עיין ברשי קידושין (ג?, גבי דרך) שאומר כרן כאן.
** דבר -
מוחל- יש להעיר- ובאמת, הוא הערה על אותו גמרא- שלשון מוחל בענין זה הוא מעניין מאד. ותחשב.
** משום -
מכאן- יש להעיר שגמרא בפסחים מפרש דין זה להיות דבר חלוק מאד ממה שאומר כאן רן.  ותחשב. ואולי מכאן הוא ממה שעושה גמרא כלל ממנו כרבן גמליאל, ואומר שכולו הולך בתר חד שיטה, ושיטה זה, אומר רן, כולל דין של ר"י הכהן. ויש לדון.
* פג.
** אמר ליה אביי - -
ולא אין נזירות
מעניין, שאף בחזרת גמרא לא אומר אותו לשון.
** אמר ליה -
יש לדון אם נדרה לששים יום ומיפר אחר שלשים, שכבר היתה נזירה לימי נזירות סתם, אבל לא לימים שנדרה. ותחשב. ודע שיש לי צד שאין זה מחמת מה שהוא חציו, וזה רק סימן לדבר (ואולי לכן לא אמרו גמרא), והסיבה הוא שצריך קרבנות כדי לעשות שאינה נזירה, ואף שרק נזרה לזמן. אולי אם יש הפרה לעשות כן, אין צורך. ויש לדון.
* פג:
** רבא אמר -
ר"מ בר שניאור- יש לדון מה הדין אם יכולה ללקוט אבל לא לקטה עדיין, שמתחילת דבריו משמע שיפיר ומסופם משמע שיפר. ותחשב.
* פד.
** ואני -
אפילו בא לעיר- מעניין למה נקט ביאתו לעיר, ולא סוף יב חודש שלו. ותחשב. ואולי זה נקרא ביאתו.
* פד:
** קסבר -
תליא- אם כן, לא יהא לבעל טובת הנאה בזרוע לחיים וקיבה לפי הצד שלא טובל, וחושב אני שלא משמע כן גמרות בחולין. ויש לדון.
** קסבר -
ובעיני- יש להעיר שמשמע מכאן- על כל פנים לצד זה- שאין טבל אל עירוב תרומה ומעשר (כן משמע גם כן לקמן ד"ה מה לי הורמו).
גם יש להעיר שלמה שכתב, קשה למה לא יכול כהן לאכול טבל. ואולי צד זה סובר שיכול. ותחשב.
* פה:
** שאני -
מכאן משמע שאין חילוק בין מה שלא בא לעולם למה שאינו ברשותו. גם נראה כן ממה שגמרא יבמות (על כל פנים לרשי) אומר שדין אחד בא ממסורה מדין אחר (שרשי מפרש שם אומר שחד למדו מחבירו). עיין שם (צב?).
** והא משתעבדים -
זה מעניין.
* פו.
** אמר’ -
מעניין שיקשה ממנו.
* פו:
** דאמר רבא -
לרבינו תם, אז, יתורץ קושיית רבינו יונה על גמרא בבא בתרא (קכה.), שאז יכול להפקיע על ידי הקדש. עיין שם, שרן אומר כרבינו יונה (על כל פנים, בהנחה זה של איך מפקיע), ואז אף הוא צריך לחלוק על ר"ת.
* פז.
** והל’ -
איתקש- יש לדון, שיש צד שזה דין דרבנן, או שהוא מפני חומרתו בעיני בני אדם.
לא חמירי- יש לדון, שרואים שהיו מגרשים בכדי (כן ענין גט מקושר).
ולא ניחא- יש לדון, שאולי, כמו בקונמות, שינו משמעות לשון (שמשמע, “אם לא אחזור בתוך כדי דיבור.”)
** יש להעיר
שיוצא מזה שני פשטים יסודיים בדין תוך כדי דיבור. ותחשב.
* פז:
** רבי מאיר -
אסמכתא- לכאורה, זה כמו שסובר רמבם באתמכתא.
* צ:
** בראשונה -
יש לדון בענין נסתחפה שדהו, מהו. אינו, לכאורה, מי שינה, שלכאורה, אשה שינתה ביותר, שהיא אנוסה, ורב בני אדם אינם כן.
** השמים -
כמה דשמים- יש להעיר שגמרא חגיגה אומר שהם קרובים. אולי חולק ירושלמי.
** נותנת -
מקום אחר- אם תאמר אם כן אף תלך. יש לומר שחוששת שבעלה ימצא אותה (מה שאין כן אם היא מגורשת ממנו, שמה לו, אז, מקומה). גם יש לומר שחוששת לאיסור חמור של אשת איש. גם יש לומר שחוששת שאם ימצא איסורה, יהיו בניה ממזרים.
** ואיכא -
צריך ביאור איך התירו רבנן בתרומה, אז, כיון שמבטלים בקום ועשה. ותחשב.
