* ג.
** הכא אשה -
לכאורה, הכוונה הוא שכיון שיש כל כך כמה חילוקי דינים, מבינים כבר שאין זה כשאר קיום שטרות. לכאורה, יש לדון למה צריך כל כך כמה חילוקים:
1. אפשר שהוא מפני שאם יש רק חילוק אחד, בני אדם לא יבינו שהם כל כך חלוקים. אז, עדיין ילמדו מזה לזה.
2. אפשר שאם יש רק חילוקים קטנים, לא ידעו בני אדם שאותם חילוקים הם חילוקים, ואז אף בהם נלמד זה מזה. ותו”ת.
* ד.
** דקיימא לן הל’ כוותיה -
יש להעיר שמשנה זה הוא רק סתם ואחר כך מחלקת. אם כן, מעניין שרוצים להוקים שסתם ואחר כך מחלקת הוא כרבי אלעזר, שבין כך ובין כך, אין מכריעים כמותו. משמע כשיטת תוס’ שסתם ואחכ"מ הוא כרבים נגד יחיד.
יש לדון אם מביא ראיה ממה שהם פסקו כן שמסתמא אף רבי פסק או נטה כן, אוא שמביא ראיה ממה שהבינו לפסוק כן (שמסתמא זה היה מקורו). ותחשב.
* ד:
** רבה אית ליה -
ואם תאמר עדיין נקשה; אם צריך לשמה, קשה למה צריך להיות מהגמניא להגמניא, ולא רק מכל מקום לכל מקום. נראה שלא קאי על חו"ל, אלא על א"י.
* ה.
** אלמה תניא -
ואם תאמר ל"ל מק’ ממה שכאן לא אומרים לא פלוג. וי"ל שלא אומרים כן על מה שלא שכיח, אלא על מה שאין לו סיבת התקנה (אבל שכיח הוא).
** בעא מיניה שמואל מר"ה -
זה מעניין; יש לציין לב"ק (פ), שמבואר שהיה שם תלמיד של רב שהיה גדול משמואל. ותחשב. ויש להעיר שגמרא (מגילה) אומר שהיה רב אסי כפוף לרב הונא. אם כן, מסתבר שהיה רב הונא גדול משמואל.
* ה:
** אין רבי מאיר לטעמיה -
יש לדון בסיבה לשיטת רבי מאיר. אפשר שסובר שיש לרבנן כוח לעשות בני אדם ממזרים, או לעשות שאין הגט טוב. אם כן, קשה למה לא מוקים משנה של האשה רבה כמותו שם (זה רק קשה לצד ראשון). גם אפשר שיכולים רבנן לבטל גט כיון שכתיב בו כדת משה וישראל. גם אפשר שכל זה רק מדרבנן. יש להעיר שאם הוא מדרבנן, אין קושיית גמרא כל כך חזק, שכיון שרבנן אמרו שגט זה פסול (זה עושה לכולי עלמא), למה קשה שעשו מחמת זה איסור על הבנים. וש לדון, שאולי חושב גמרא שכיון שהוא רק חשש רחוק מדרבנן, לא היה להם להחמיר כל כך. ודחוק.
** בפלוגתא -
עיין במה שאומר. משמע שבפלוגתא ר"ל מה שחלקו בו אחרונים חלקו בו ראשונים. עיין בב”ק (פרק מרובה), ובמה שכ’ שם בגלגל רביעי. מכאן משמע, אבל לכאורה לא מוכרח, שתולים ראשונים בשל אחרונים. ותחשב.
* ו:
** דאסכים מריה -
עיין במה שפירש. נראה שהאו מה שהודיעו לו מה שהקדוש ברוך הוא למד. לולי זה, היה אפשר לומר שהוא מה שהיה אליהו מדבר עמו. גם אפשר שהוא מה שהקדוש ברוך הוא היה לומד תורתו. ותחשב.
* ז:
** המביא גט בספינה -
לא הבנתי הציור כל כך. פשוט שהיותו בספינה לא יהני, שכל שליח הוא בארץ ישראל לזמן קודם שנותן לו. צריך לומר, לכאורה, שבעל מוסר לו בספינה. אז, צריך ביאור בציור של עציץ. אולי הוא עציץ גדול מאד. גם אפשר שמה שצריך אינו מקום של שליח או מקום של בעל, אלא מקום הגט, והגט יכול להיות בעציץ.
** נקוב -
קשה, שספינה לא נקוב, והיה לו לדמות אותו לעציץ שאינו נקוב.
* ח.
** העשויה -
עיין במה שפירש. לולי דבריו, היה נראה מלשון גמרא שאין הענין מה שהוא בורח בכל שעה, אלא מה שהוא עומד לברוח, בכל שעה. ותחשב.
* ח:
** נכסיו לא קוניים -
על כל סוגיה זה, יש להעיר ששמעתי מג.ר.ק. בביאור קצות הידוע בענין גטו וידו באים כאחד שהבעיה באותו חלות במקום שצריך קנין הוא שקנין קורה אחר מעשה הקנין, ואז אין דבר יכול לחול בבת אחת, שכבר נגמר הסיבה. עיין במרגנליא, שכבר בארנו דעתינו בענין זה. על כל פנים, אם נאמר כן, ואף נאמר שצריך שעבד יקנה את עצמו, ולא רק ישוחרר, כדי לקנות, ואף נאמר שקנין עבד האו כקנין שטר (שאולי מפני שהוא קונה את עצמו יכול להיות חלוק), אז לכאורה יהיה סיבה אחר, חוץ ממה שמפרש רש"י שאומר גמרא, למה לא קונה, והוא מפני שאין סיבת קנין בזמן שיכול לקנות. לכאורה, אין זה אפשר בגמרא. וצריך לחשוב.
** משום יישוב -
לגרש- משמע שאין מצווה אם לא מגרש גויים. באמת, אפשר לדון אם רש"י אומר שאין מצווה אם מגרש ישראל, או שאין מצווה אם אין מגרש גויים. על כל פנים, משמע שטובת המצווה הוא שארץ ישראל ירבה בו ישראל, ולא שיהיה בארץ הקדושה. ותחשב ותבין.
* ט:
** יחזור -
עיין בלשונו. משמע שאף שאין חבין לאדם שלא בפניו, אם עושה שליח, אז חבים לו. היה אפשר לומר שלעולם אין חבים לו, אבל אם עשה שליח, אז יודעים שאין זה חוב לו, ואז יכולים לעשות כן. משמע מרש”י כאן שני חידושים:
1. חבים לאדם אם עשה אותו שליח.
2. אין מינוי שליח מגלה שאינו חוב.
3. י:
4. עד כותי- מעניין שמניחים ש”עד” ר"ל אחד, אף שגמרא (תחלת סוטה) דורש שסתם “עד” אומר שנים.
5. חסורי- כדי שלא תאמר שהוא מעשה לסתור.
6. יא.
7. בשמות מוהבקים- נמצא שהיו שמות שהיו שווים בין בני ישראל לגויים, אבל גם היו שמות שהיו רק לגויים. זה מעניין.
8. ודע שיש לדון אם היו שמות אלו שמות שרק גויים היו קוראים לבניהם, או שהיו בני אדם ידועים בשמות אלו, וקרה שאותם בני אדם היו גויים. ותו”ת.
9. יב:
10. הקדש גופא- מעניין שצריך מה שהקדש גופא רוצה בכך, ומה שאין הממון הקדש. ותחשב.
11. סמא חריפא- לא הבנתי זה כל כך. לכאורה, ר"ל שאם צריך לצער עבד, כדי לתת שבת יותר לאדון (ר"ל, כדי שיוכל לעבוד יותר לאדון), עושים כן, ואין צריכים לתת חלק מממון של שבת לעבד, אף שהוא נתן מצערו לשבת. ותחשב.
12. טו.
13. תקברם- לכאורה, אי אפשר לומר שלא היה לו דחייה, אלא אמר שאסור להביא ראיה מהם, שלמעשה, איך נדחה הדין כיון שלא רוצים להזכיר אותם בבית דין. אולי אומר שכיון שהיו רעים קנסו אותם. גם יש לומר שכיון שלא דנו בראיה מהם, לא היו חכמים של דור לפני כן יכולים לדון במה קרה, ולדון אם יש ראיה. אז, אפשר שהיה שום דחייה. דחוק.
14. כה:
15. ולכי מיית- עיין במה שכתב רש"י. זה מעניין. היה נראה לומר שסובר שדיון של ברירה תלוי באם אומרים שדבר נחשב די מוכרח לקרות לפני כן. נראה שאם תלה בדבר שאינו בידי אדם, אז פשוט לו שנחשב שיעשה. אם תלוי בידי אדם, אינו כן, שיכול אדם לבחור שלא לעשות כן. הצד שלא לומר כן הוא שכיון שבחר זה, מסתמא היה כבר סיבה שמסתבר שיבחר כן.[fn:1]
16. כח.
17. איפליג- מעניין שרש”י מחדש שיעור לזה. לכאורה, מקורו הוא מה שכמה דברים הולכים בתר עשר שנים. ויש לדון, שלא הכל עושים כן. ותחשב.
18. ל.
19. מי יהיב- מעניין שגמרא אומר מזה שאין אונס בגט, שלכאורה כאן אומר שהיה לו לעשות יותר, ואז אינו, באמת, אונס, אבל אילו היה אונס, לא היה הדין כך. ויש לדון (שאולי אומר שאל יצעק אלי, שיש לו יותר לעשות, ואף שאין מה שיש לו יותר לעשות משנה הדין). ותחשב.
20. לד.
21. לבטולי גט- לכאורה, פשוט שאי אפשר לו לבטל גט, שאין שליח לו לבטל. אולי יכול להטל נתינה (עיין מאירי לעיל). ויש לדון, שאולי נתינה כבר קרה. באמת, צריך לדון בכל זמן שחל גט אחר זמן מתי נחשב נתינה מן הבעל.
22. כנחמן- ק”ק למה קוראים לו נחמן, ולא רבי נחמן. אולי הוא אגב נחמני (שלא נקרא רבי נחמני).
23. לה.
24. דאישתרשי- קשה, שלא נשתרש כלל, שאף שהלחם יותר גדול, אין זה טוב לה, שאין יותר בתוך הלחם. אולי מכרה הלכם לדמי לחם רגיל.
25. לו:
26. רבא אמר- הו”מ לומר שמתרץ לק’ שניה, אלא שלכאורה מה שאומר יתרץ לשניהם. ותחשב.
27. לח:
28. גזברים מאי- רש"י מפרש למה לא מניחים שמכוון להקדישו לדמיו, אבל לא מפרש למה לא מוקמינן המשנה במקדיש לדמיו.
29. לט.
30. הא מני- להקדש- משמע ששיטה זה הוא רק שאין אדם מוציא דבריו לבטלה להקדש, אבל לדבר אחר אולי מוציא. גם אפשר לומר שרש”י רק אומר שלא חולקים לענין דבר שאינו הקדש, ושם כולי עלמא מודו לרבי מאיר. צריך ביאור למה זה יהיה.
לט:
31. כליו של מקנה- מתנת שכיב מרע- לכאורה, מתנת שכיב מרע לא יהני, שהוא לאחר מיתה. ותחשב.
32. רב אשי- לכאורה, אין זה רב אשי סתם, שלא היה תלמיד של רבי. ותו”ת.
* Footnotes
[fn:1] כמובן, כל זה קשה לבאר, שלא הבנתי איך בחירה אפשר בדרך כלל, שלכאורה לכל יש סיבה, ואז הכל כבר מוכרח לקרות. ותחשב.
