* ב:
** כשרים ועלו -
לכאורה, יש בזה שני חידושים:
1. אין דין שאינו עולה לבעלים נוהג במנחה.
2. אין פסול מנחת חוטא וכדו’ נוהג במנחה.
(שוב ראיתי שרש"י מרמז זה).)
* ג.
** ומיעבר -
נראה שסבר בהוה אמינא שהענין הוא שממעשיו רואים שלא חושב כן באמת, שאילו היה חושב כן, לא היה שוחטו שם. במסקנא מחדש שהענין הוא שמוכרח שמחשבתואינו נכון. גם יש לומר שדוחה שאולי לא עושה כן כיון שלא, באמת, מחשב עליו לקדשי קדשים, אלא מפני שטעה בדין.
** מיעבר -
כיון שהגענו לזה, לכאורה, יש לומר כן גם כן בעוף. ושו"ר ברש"י לקמן. ועיין במה שאומר, שלכאורה מוכיח כצד שני שכתבנו לעיל בד"ה ומיעבר.
* ג:
** תורה אחת -
קשה, שרק רואים מזה שכל חטאות שוות, ואז אין שינוי קדש, אבל עדיין אולי יש שינוי בעלים (שאין כל בני אדם חלוקים). אם כן, היה אפשר לו לומר כרבה. ואפשר שיסוד של שינוי בעלים הוא שינוי קודש (ולא שעושה שאינו כל כך מיוחס למי שצריך כפרה ממנו), שמנחה של זה חלוק ממנחה של זה, ולכן יש פסול. כיון שיש קרא שנותן לכל מנחות תורה אחת, נמצא שאינם חלוקים. ויש לדון.
* ד.
** שמיעת קול -
צירך ביאור, שנאמר שיותר טוב ללמוד מחטאת כיון שכבר למד ממנו דין. ואולי אותו דין נוהג גם בשמיעת קול, ולא יודעים מאיזה נלמד.
* ה.
** ואי מחוס"ז לבו ביום -
נראה שר"ל שמה שיעכב הוא רק שיהיה ראוי לבדר זה, ולא סדר זה, שכן הוא בכל דבר שאינו כפול. אז, כיון שיהיה יכול להקרבו היום, אחר שעושה מתנה חלוקה, אם זה נחשב שאינו מחוסר זמנו, הוא ראוי, ואז הוא כשר. ותו"ת.
** ממשקה ישראל -
יש לדון אם זה סיבה או סימן. אם הוא סיבה, לכאורה, יהיה שחלק מקרבן הוא שאדם מחסר את עצמו כדי ליתן לה’. כאן, לא מחסר כל כך. אם הוא סימן, לכאורה, הוא סימן שאותו חפץ רע. נראה שאולי יש עוד צד. אפשר שאיסור אכילה הוא בעצם איסור להנות באופן חשוב, אלא שרק אכילה הוא אותו הנאה. נראה שאולי תוצאה של קרבן הוא חשוב עכ"כ שנכלל באותו איסור. ותחשב. לא נראה כאותו צד, שאם כן מה לי מחוסר זמן לבו ביום; עדיין, לכאורה, אסור לאכלו. ואולי אין הכי נמי, אסור, ורק דן אם הוא כשר או לא. אומר שהוא כשר כיון שיותר באותו יום. יש לדון למה זה יפסול כלל. נראה שני מהלכים:
1. לא מהני כדי שלא יהיה לבני ישראל הנאה, ולא יעברו. זה א"א לומר כאן.
2. לא מהני מפני שביאתו עבירה או רע. כאן, צריך לומר שאינו כל כך רע.
נראה שאולי יש עוד צד, והוא שאולי מה שהוא רע לדבר (אכילה) עושהו רע ומאוס. ותחשב. אם כן, אולי ענין בו ביום הוא שכיון ששם זה עומד ליבטל, אינו עליו כל כך. ותחשב.
* ה:
** אלא מכללא -
היה אפשר לומר שנאמר מכלל זה.
** להתיר -
קשה, שאולי רק מניחים שיתיר לאו במנחת העומר, שרואים שבדרך כלל מתיר חדש, אבל בטריפה, קשה למה נניח שמתיר אותו איסור. ותחשב.
- ק"ק למה לא אומר שנלמד מכל קרבנות, שהם אסורים, שהם מעילה, אבל הם מותרים לגבוה. ואולי כיון שפסולם וקדושם באים בבת אחת, אינו בעיה. ותחשב למה לא. ותו"ת.
* ו:
** לר"ש -
מעניין מה שמניחים שאם זה ר"ש, גם זה רבי שמעון. נראה שגמרא מניח שכל תנא, אף אם אינו רבי שמעון יכתוב מה שאין רבי שמעון חולק עליו בזה. אז, היה לו לאותו תנא לכתוב ההודאה. מדלא כתבו, צריך לומר שכבר משמע כן מדבריו (כן מסיק גמרא, אבל היה אפשר לומר שמסיק שאינו כן, ושרבי שמעון לא מודה.)
** שלא יהא חוטא נשכר -
צירך לדון בזה, שלכאורה, אינו נשכר בזה, אלא שאין סיבה לחיוב. ויש לדון, שיש לדון למה לא חייב שהרי שאר קרבנות חייבים. אם זה מפני חטאו, אז, אולי יש לבאר. ויש לדון, שלולי חטאו, לא היה חייב כלום. ואולי אם החטא עושה מניעה, נוכל לומר שעושה חטא דבר רע לו- מחייבו- ודבר טוב לו- פוטרו- והשני הוא "חוטא נשכר.” וצריך ביאור.
** כולהו משמע -
לשון זה משמע שהנדון הוא אם משמע כולם או לא. אז, מניח שהוא כרבי שמעון ורק דן מה אומר. לולי זה- ולכאורה, כן ר"ל- הייתי מפרש שאומר שזה די לומר לנו שהוא כן אף לרבי שמעון. ותחשב.
** רב -
כמו שעושה גמרא כאן עושה גם כן ביבמות פח: (אומר שני לשונות ברב שהם הפוכים, ובאים רק לדחות האחר).
* ז:
** ומהלכתא -
משמע שהיה אפשר ללמוד ממנו. ק"ק, אז, למה צריך קרא של וטבל. ואולי טרח וכתבו. גם יש לומר שאמר בעיה אחד עם לימוד, ויש עוד בעיות. ותחשב.
* ח.
** בלא… מנחת חוטא -
יש לדון למה לא למד כולם מזה. ואולי הוא יותר רע אם רק חסר אחד. ותחשב למה. ואולי אז אין השמן טוב, שאינו עושה מה שצריך לעשות, כיון שאין עמו לבונה. אם כן, אולי, אין להביאו, שיש עליו מה שאינו קדוש (אינו עושה מה שצריך לעשות). ותחשב.
* ח:
** ליבש שבו -
ואם תאמר אטו לר"ח אין אדם מביא שום מנחה מפני היבש שבו. ויש לומר שסובר שכולו נחשב מנחה.
** יש להעיר
שלכאורה, יש ראיה רק ללשון ראשון של שמואל.
* ט.
** בביאור קביעות כלי
נראה לכתוב שני צדדים:
1. אפשר שהענין הוא שאין שני החלקים מצטרפים כיון שיש חילוק ביניהם במה שזה (הישן) חלק ממה שהיה עמו ואין החדש חלק ממנו.
2. אפשר שהענין הוא שאי אפשר להיות שלם עם זה, שכבר הוא שלם, שהוא כבר מנחה, ולא סולת. זה אומר שסלת וסלת מצטרף למנחה, אבל זה כבר נצטרף עמו, והוא מנחה כבר,ולא סולת (לכאורה, הענין הוא שאז אי אפשר לצרפם מפני אותו חילוק ביניהם). וצריך ביאור.
** איתא… חציצה -
יש לדון מהו המסקנא:
1. אינו חוצץ. יש לדון למה. ואולי הוא שהם מין אחד, ששניהם עושים חד דבר.
אין צורך שיתנו על הבשר, אלא על הדם, ואז ממילא, אין חציצה, שאין דבר שהוא בין דם לשמן.
* ט:
** קידוש -
לא ידעתי כל כך על איזה יד דנים, אם הוא על יד שבו נותנים או על יד שמגביה את הכלי שבו נותנים. ותחשב. ועיין במה שאומר שלר"ש יכול בשמאל כיון שאם בא לעובדה בכלי, עובדה בשמאל. היה אפשר לדון מה זה אומר, אם אומר שעובד עבודת כלי, דהיינו נתינתה בו, בשמאל, או שנותנו משם בשמאלו. לכאורה, צריך לומר שהוא האחרון, שאם דן בנתינה בו, מהו "אם בא לעובדה… " שהרי צריך לצד זה. ויש לדון, שאולי אומר כשעובדה… . על כל פנים, לכאורה, תלוי על זה יהיה מהו קידוש כלי. ותחשב.
* י.
** חד לפסול צדי צדדים -
שמעתי מר.מ.ש. שיש לדון למה נחשב מנעל של חליצה "מעל" רגלו. אמר שאפשר שהוא מפני שחלק חשוב (חלק ממה שמעמידו על רגלו) הוא עליו. גם אמר שאולי הוא מפני שעל בסמוך משמע. יש להעיר שלכאורה, זה רק ירבה מה שהוא על צדדים, ולומר שכיון שרובו או חלק חושב הוא עליו או על צדדיו, נקרא "מעל.”
** אמר רבא -
ק"ק למה לא אמר שרק אחד נצרך, וכפלו מפני הא דתדבר"י, שכל דבר שכפלו…
** אמר רבא -
קשה למה לא רק משנה דרשת שנים אלו, ובשאר יורה כמה שאמר גמרא לעיל. ואם תאמר אם כן, כבר יש לנו דרשה לקמיצה, ואין צריכים עוד קרא, קשה, שבין כך ובין כך יש שני קראי לקמיצה. ויש לדון, אולי, שאולי כעין זה יותר קשה לומר שהם לאו דווקא וקאי על קידוש קומץ.
** אבל מלח -
יש לציין לגמרא ששואל מה הדין אם משלים לכזית, שתלוי באם נחשב אותו חפץ של הנקרב. אולי זה שייך לזה.
* י:
** ר"ש -
ק"ק, שכבר דרש זה. ואולי אינו בעיה לדרוש אותו לשני דינים. ותחשב.
* יא.
** היכי דמי -
לכאורה, ממה ששאל כן, רואים שידע התשובה, שבלי זה, פשוט שכולל כל הציורים.
** להשוות -
יש לדון מה אומר:
1. כדקמצי אינשי רק אומר ש,כמו בני אדם, משתמש עם כל אצבעותיו. עושה כן מפני שמשווה אותו בזרתו.
2. אולי אומר שקוצץ כדקמצי אינשי, אלא שאחריו משווה אותו.
* יא:
** את לא משמע -
מעניין, שהיה תלמיד של ר"ע שהיה דורש "את"ים.
** הקומץ -
בכל כעין זה, יש לדון למה לא היה יכול לומר, “אף למנחה יש דין פיגול,” ונדע שהוא אותו דין של קרבן. ויש לדון, שאולי יש כמה חידושים (כמו מי מצטרף או כדומה). ולא נראה. גם יש לומר שיש שהיו לומדים זה קודם זה. אז, רבי כתב שניהם במילואיהם. גם יש לומר שלכם תנאים כתבו שניהם (שהיה תנא שהתחיל מעיקר מקומו, והיה תנא שלאיזה סיבה התחיל ממנחות), ורבי כתב שני הברייתות למשנה. יש לדון למה רבי נקט שנים אלו, שלכאורה, אף היה ברייתא אחר מאת התנא שתנא אותם בזבחים שיאמר מנחות בלשון קל. ויש לדון.
** בביאור הרצאת פסול
, נראה שאולי יש שני תוצאות של זריקה, והם הרצאה והיתר. אפשר שזה לא בא מזה וזה לא תלוי בזה. אם כן, יש לומר שמה שפיגול יש לו הראשון (שמרצה), אבל לא השני (שלא מתיר).
* יג:
** דלאו מינא דמחנה -
יש לדון אם ההוה אמינא הוא שאין לבונה שני מתירים (כיון שהוא מין אחד) או שאף שהוא שני מתירים, הוה אמינא שיכול זה ללפגל לזה כיון שהם חד מין. ותחשב.
** ירך -
ואם תאמר לא אותו ירך יאסר, אלא רק אותו כזית. אפשר שחשב על "כזית מאותו אבר.” מעניין שזה אוסר כל האבר, שלא חשב על כולו. אפשר שכל האבר נחשב אחד בדרך כלל או שכאן דן בשעדיין מחובר לאבר (ואז אין ללמוד מטמאה, שכאן היה טמא כולו).
* טו.
** הלחם מפוגל -
לכאורה, הענין בזה הוא שמחשבה בתודה פוסל תודה, ואותו פסול גם פוסל לחם. גם יש לומר שהם אחד, אבל אין לחם חלק כל כך חשוב מתודה, שאינו מתירו ואינו מחובר לו כלל, אבל תודה הוא חלק חשוב מלחם, שהוא מתירו. אז, רק במחשב על תודה נאסר לחם, ולא להיפך.
** התם הוא -
היה אפשר לומר שהוה אמינא שהתם הוא שפגל בלחם, שלחם נקרא תודה (כהוה אמינא של גמרא).
* טו:
** הבא -
ק"ק, שלכאורה, דחה קל וחומר זה בתחילת מכות. ותחשב.
* טז:
** הא כמ"ד -
אז, לכאורה, יש תנא הסובר שיש מד. מעניין שלא מצינו (ושלא מביא גמרא) ברייתא כזה. ויש לומר שמביא ברייתות אלו רק כדי לבארם, וכבר פשוט הוא איך לבאר אותו ברייתא.
* יח:
** מאי הוי -
עדיין יש להקשות על ר"ז (או מקשה), שהיה לו לת’ שכי אינם נבללים, מעכב, ומשנה רק אמר שכי אינם נבללים ביד כהן, לא מעכב. ותחשב.
* כב.
** כדרך שמביא נסכים -
ק"ק למה לא מדמה ללבונה, כמו לעיל. ונראה שעצים לא כל כך דומים ללמונה כלנסכים (ומלח יותר דומה ללבונה, שהוא בכל אחד).
* כג.
** בתר בטל -
נראה שאולי מה שלא יהיה תלוי באם יכול בטל לשנות שמו הוא שאולי מה שאין ביטול קורה אינו רק שאין לשנות שם של חפץ, אלא שכיון ששינה שמו, נמצא שיש בו סתירה, שיש בו שם זה, אבל היה בו שם אחר, ואי אפשר לאותו דבר אחר לשנות לדבר זה. (ויש לדון, שאולי בטל גם לענין שמו שהיה, ואין מחשבים בשמו שהיה כמו שאין מחשבים בשמו שיש לו עכשיו.) אז, אם יכול לשנות, אין בעיה זה, ואולי אז יותר קל לבטל. אז, אולי אף שנחשב מין במינו, יבטל. ויש לדון.
* כג:
** אילימא רבנן -
היה אפשר לומר שאין כאן רוב.
* כד.
** שבע לו טומאה -
תחשב על מושג זה. ונראה לי לומר צד שאולי כשדבר טמא נוגע בדבר טהור ומטמאו, אין הביאור שנותן מטומאתו עליו או שעושהו כמותו. אלא הענין הוא שטומאה הותא"בתירה"- ולכן מי שהיה חי ועכשיו מת, שהיה לו שם חשוב של חי, ועכשיו יש לו שם של מת, שאינו חשוב כלל, טמא, שיש בו אותו סתירה. ותחשב. אולי, אז, הנוגע בדבר טהור עושה אותו סתירה, ואז הוא טמא. אינו כל כך טמא כמה שנגע בו, שיאן זה סתירה כל כך. ממילא, אז, כל טומאה פחותה שיגע בו יעשה טומאה יותר פחות. אם נאמר כן, אולי יש להבין שכיון שהוא כבר טמא, אין סתירה, ואין סיבה לטמא. ותחשב.
** ונגע -
אפשר שתלוי במה שיש לדון אם כששני דברים נעשים דבר אחד, מה שזה טמא כשזה נטמא הוא שמעשה נגיעה על כולו או שכיון שזה טמא, זה טמא. ודע שצריך ביאור איך נאמר שכיון שזה טמא זה טמא, שהרי כאן הם אחד, וזה טמא, ואין זה טמא. ואולי כיון שטומאתו שייך ללשמו בפני עצמו (שאז קרה), אין להיעשות אחד לנגדו. ודחוק.
* כה.
** עוון המקדישים -
היה אפשר לדון אם בעיה של שמאל הוא שאינו מכובד לחפץ או שאין לשמאל של כהן כל כך קדושה (ואולי זה מפני שאינו מכובד). על כל פנים, לשון שהוא חטא מחטאים אולי משמע כצד שני. ויש לדון, עדיין, שלמעשה הוא קרק’ שהוא בעיקר בכהן. ותחשב.
* כו:
** יש קומץ -
לכאורה, רק צריכים אחד כדי לומר שיש פעמי פעמים.
** אי בעי -
אבל אין לומר ש"על" בסמוך, שרש"י כ’ שבודאי אינו אומר תחתיו. ותו"ת.
* כז.
** על ממש -
משמע שיש יותר משמעות של "על" לעל גבו. ואולי גמרא רק רצה לומר שהוא על גבו והדרך לאומרו הוא "על ממש,” אף שאין על משמע כן. ודחוק.
* כח.
** הא והא רבנן -
היה אפשר לומר שהוא דברי הכל.
** בא זהב -
צריך ביאור למה אי אפשר לעושת אותו דרשה למקשה.
* כט:
** שני טעויות -
אולי זה שייך למחלקת מתי יש חזקה (או שזה עושה שזה מנין חשוב, או שזה גורם שנניח שיש עוד בעיות שאי אפשר לראות. ותחשב.)
* ל:
** כל מקום -
מעניין שאומר לשון זה אף שנאמר רק על מקום אחד (או שני מקומות). ויש לדון, באמת, למה גמרא לא מניח שנאמר על כל מקום.
** לימא -
משמע שממה שאין אדם אומר דבר רואים שחולק. וזה מעניין.
* לא.
** אין רב -
או שלא סבר כמה שאומר גמרא בסוטה שרובם מעשרים או שסבר שהמצב נשתנה.
** פשיטא -
היה אפשר לומר שאינו כל כך פשוט, שלא היה הפוסק אלא השואל.
* לד.
** כדי שיפגע -
צריך ביאור למה יותר טוב שיפגע בו תחילה כשבא ולא כשיוצא. ויש לומר שמסתמא ביתו מקום קדושה, ואז אין צורך לבא לו מיד כשיוצא, שיוצא מבית קדושה.
** יהודה ברה -
מזה נראה כמש"א רש"י בכ"מ (ודלא כמש"א במקומות אחרים) שאינו שם אלא אומר "החשוב.”
* לז.
** אדהכי -
עדיין היה שאלת פלימי דבר שלא מצוי, שגמרא מניח שימות קודם שלשים יום.
* לז:
** שאני הכא -
לכאורה, עיקר חסר מן הספר, שהעיקר הוא שעכשיו חי, ואף שימות, אולי, לאחר זמן. ותחשב.
** אך -
צריך ביאור שאם ימות לפני ל’, למה נדון בו, שרק חייב אז, ואם כבר מת, פשוט שלא חייב.
* לח.
** וראיתם אותו -
יש לדון מה ראה בזה, שלכאורה, אי אפשר לומר שמרבה מלשון רבים, שהרי אין הקרא אומר אותו לשון רבים אלא על מי רואה, ולא על מה רואה. לשונו משמע יותר שלומד ממה שכוללם באחד לומר שהם נצרכים. ותחשב איך מגלה כן.
* לט.
** כדי שיכרוך -
לשון זה מוזר, שהיה לו לומר שהוא כריכת חוט שלש פעמים, ולא מקום כדי כך. ותחשב.
** מעלין -
זה מעניין, שבהכרח מורידים כשעושה בתכלת. יש לדון למה לא לעולם עושים בלבן. אולי הוא כדי להעולות. ותחשב.
* מ:
** מעשה לא הוי -
זה מעניין. צריך לחשוב על זה.
* מג:
** האי אשר תכסה -
יש לדון מהיכי תיתי שאין מרבים כסות סומא מזה. ואולי כיון ש"וראיתם אותו" אינו דווקא, אין למעט כסות סומא.
** ור"ש -
קשה, שכבר דרשו. ואולי מדרשה זה עצמו נלמד.
* מה:
** ובן ננס גמרא -
ק"ק, שבן ננס אומר מקורו במשנה. ואין להשיב שבא לבאר למה דורש כן ולא כר"ע, שהרי גמרא מבאר גם את זה. ואולי צריך מה שאומר משנה בצירוף כל מה שאומר גמרא. ודחוק.
* מו.
** זיקה -
לכאורה, הענין הוא שמרצה באופן חלוק כשבא עם לחם (או שצריך לכך כדי שיכפר על לחם או שאין צורך להרצאה רגילה כיון שיש עמו לחם), וכיון שנמצא שאין לחם, אין זה טוב. ותחשב.
* מח.
** רבי יהושע -
כאן אינו חוטא כדי לזכות ה’, אלא כדי לזכות הכהן (שיהיה יכול לו לאכול החולין, ולא כדי שיעשה מצוה). בדיון גמרא על כבשים, לכאורה ה’ זוכה שהם כשרים. משמע שסבר שעדיין הם שווים. ויש לדון, שאולי אף בכבשים, הוא לטובת כהנים, שנאכל אז. ותחשב.
* מח:
** שלטומאה -
ואם תאמר הרי כבשים לפסול עומדים. וזה תלוי בעל מה מחשב שלא לשמה,שללשון ראשון שברשי, לא מחשב על אותם כבשים שיפסלו. גם יש לומר שאינו עומד לאותו פסול, ואז יש עדיין יתרון.
** דלטומאה -
לכאורה, הענין הוא שאין יתרון בהצלתו, שבין כך ובין כך ייפסל (וחילוק של זמן נפילה לא שווה כלום. אולי מה שלא שווים הוא שהבעיה בטומאה הוא שאינו ראוי לאכול. בנפילתם, בי"כ ובי"כ אינו ראוי. ויש לדון, שאין איסור לעשות אותו א"ר כגון זה (כמו אם נועלו בבית).) גם יש לומר שאולי אין איסור לטמא תרומה בא מפני שיש דבר רע בתרומה טמאה, אלא בא מפני שרע להוריד תרומה מקדושתו (יציאת קדושה מדבר הוא רע). ותחשב. אם כן, לכאורה, אין חילוק מתי קורה; אם היה הבעיה מצבו אחר שנטמא, אז יש לשהות ביאת אותו מצב כדי שיהיה במצב שאינו רע ליותר זמן (ואף בזה, אם נאמר שישרפנו מיד, ויהיה באותו מצב לזמן שוה, יהיה בעיה רק אם נאמר שהוא טוב להיות תרומה במצבו של טהרה, שאז מחסר טוב), אבל אם הבעיה הוא יציאת קדושה, אין טוב לשהות אותו בעיה, שהוא שווה בין אם קורה עכשיו ובין אם קורה אחר כן. ותחשב.
* מט.
** לטעמיה -
לכאורה, יש לומר כן לכל הצדדים שם, שכלם נותנים טעם שיתקיים כאן בביאור שיטת ר"ש. ותחשב.
** מחנכים -
יש לדון למה צריכים חינוך:
1. משנה את המזבח. אם אין מזבח כבר נשנה, אי אפשר לקרבן לרצות.
2. קרבן ראשון משנה את מזבח. אם תמיד של בין הערבים עושה כן, לא יכול לרצות גם כן, שרק יכול לעשות אחד.
3. אולי רק רצה לומר שיכול להיות ראשון, אבל אם שאר הם ראשון, אינו טוב (יש לדון למה. ואולי קרבן ראשון כדורון שמרצה ה’ שיקבל שאר קרבנות.). אם כן, הוא דין בקרבנות, ולא במזבח, וכשאומר שמכשיר את המזבח, רק אומר שמפני זה, יש להביא קרבנות עליו.
(במילים יותר קצרים, דנים אנו אם הוא דבר הנעשה למזבח או לקרבן. גם דנים אנו אם צריך ראשון כדי לחנך או שאף אחר יכול לחנך, אלא שאז לא יהיה אותו אחר מהני.)
** יש לדון
אם ראשון אין צריך חינוך או שרק הובא לחינוך (ומה שלא מכפר ומרצה חוץ ממה שעושה חינוך אינו בעיה. ותחשב.)
* נ:
** מיחזא -
אפשר שחולקים אם צריך להיות עומד או רק ראוי. ותחשב.
** תעשה -
יש לדון אם זה מגלה שהותרה (ואף שיכול לעשותו מע"ש, יכול לעשותו בשבת) או שאי אפשר לעשותו מערב שבת. גם יש צד שאומר שאם בא שבת, ולא עשה אותו, צריך לעשות אותו, אבל כיון שאפשר לעשות בע"ש, צריך לעשות אותו אז (וכל דין זה בדיעבד). יש להעיר שאחד מן המקורות אומר שצריך לעשותו באותו יום. אם נניח שיהיו שווים (שהרי, אומר כולם ביחד), אז נצטרך לומר כצד שני שכתבנו.
* נב.
** דאי -
נמצא שאומרים דאי אף אם אינו עבירה. יש להעיר שכאן הוא, על כל פנים, דבר רע. ותחשב.
* נג.
** אדיר -
שאלתי את רשש שליטא על זה, שמשמע מכאן שהיו המצרים האדירים, אבל בגמרא ב"ק, אומרים חכמים לר"ע, “צללת במים אדירים…,” שלכאורה אומר שאותו אדירים נאמר על המים. הראה לי מדרש שוחר טוב שמביא מקומות שקאי על מים ומקומות שקאי על מצריים, ולא הביא זה כלל. אמר שאולי סבר שקאי על שניהם, ואז אינו ראיה לשום צד. אם כן, קשה למה לא הביאו לראיה לשני הצדדים (או לא לשום צד כאן). ותו"ת.
* נג:
** זו -
חלקו אם "זו" רצה לומר "אשר" או "זה.” גמרא שמביאו עם "זה,” וכן מן הדיבור שעושה ממנו, מוכרח לומר שר"ל "זה.” ותו"ת.
* נד:
** יש דיחוי -
נראה לי עוד צד בדיחוי, והוא שאולי מה שעושה איסור אינו דבר שקרה לו, אלא מה שקרה לו עשה איסור, ומה שהיה אסור (או שהיה עושה ס"ר) עושה שיעשה עוד ס"ר (כמובן, זה לא יהיה שייך, לכאורה, בכל איסור. ותחשב.) ויש לומר כן בכמה דיחויים (כמו בקדשים, שיש לומר שקדושה בטלה).
** תיובתא -
כיון שלא מתרץ לזה, יש לשנות את המחלקת למה שהניח גמרא לפני כן שהיה ולעמוד על אותו תיובתא. ויש לדון, שלכאורה, יש לגמרא דרך לדחות זה, שאי לאו הכי, לא היה צורך להביא עוד ראיות (ויש לדון, שלפעמים אומר גמרא שדילמא יהיה תיובתא מזה ומזה. ולא משמע לשון כאן כן), ואז אפשר שהוא כן רק על תיובתא זה, ולא על תיובתא שלעיל. ותחשב.
* נו.
** מעיקרא -
אינו הראשון, אלא מעט קודם לזה.
* נז:
** אין -
לשון זה (אין נמשחו) מוזר; בדר"כ, על כעין זה אומרים "לא נמשחו.”
** קצ"ב איך ידע .
גמרא להקשות שהוא מדת יבש, שאולי מיירי כשלא גבל בקטבליא, אלא בכלי רגיל. ותחשב
* ס.
** ריבוי -
ק"ק, שנחשב ריבוי אחר ריבוי רק מפני שמניחים שהדין בשמן הוא הדין בלבונה. ק"ק, אז, למה למסקנא למה לא מניחים כן (ולומדים ממיעוט זה). ותחשב.
* ס:
** מצוייה -
יש לדון אם ממש אומר שמצוייה טפי או שרק אומר שמה שהוא תדיר (קבוע לבא יותר) מהני. נראה שאולי תלוי באם מעלת תדיר ומעלת מצוי שווה. וצריך לעיין בדיון רבא ור’ הונה בר יהודה (זבחים צא.).
* סא:
** שהתנופה -
יש להעיר שתנופה הוא אף בבעלים (כמו שאמר לעיל, “כיצד מניח…).
* סד.
** צורך גבוה -
היה לו לחלק כאן כמו שאמר לעיל (ואולי כן אומר במילים אחרים).
** זיל -
כל זה מעניין, שלכאורה, לא עבר על ציווי ה’, שהיה ה’ מצווהו. צריך לומר שאין צריכים לעשות נגד ציווי ה’ לחייב.
לכאורה, זה עדיין לא דומה למה שאומר ר"ע בסוף נזיר וראש חגיגה באשה שלא יודעת בהפרה שצריכה  סליחה, ששם אין, לכאורה, ס"ר.
צריך ביאור, אז, למה אינו מביא קרבן על אונס (שאין לחלק לומר שצריך להיות תביעה עליו, שאין תביעה כאן). ויש לומר ששם אינו כל כך מעשיו. במקום אחר (צדי צדדים על ב"ק) דנינו בזה.
גם יש לומר שכוונה לעשות נגד ה’, לכאורה, בצירוף מה שעושה ס"ר, מחייבו.
גם יש לומר שכיון שאזלינן בתר מחשבותיו, מעשה זה רע, ויש ציווי עליו. נמצא שציווי תלוי בכוונתו. לכאורה, מה שמעשה יותר רע על פי מחשבתו הוא שבמחשבתו מחשיב חלקים מיוחדים של מעשה, וכשחושב לעבירה, מחשיב הס"ר. ותחשב. (ואולי הוא לא רק שרוצה יותר באותו חלק, אלא שרק ידע בו, ורק גילה שום רצון לו. ויש לדון אם לא ידע שדבר אחר הוא מצוה (לא ידע שה’ צווהו). ואולי שאני התם, שרצה באותו מעשה; מה שאין כן כאן, שלא ידע אף באותו מעשה.
ודע שאין לומר שחייב כאן כיון שהיה יכול לעשותו בלי צידה, שהרי אז אף אם אזלינן אחר מעשיו יחייב.
ונראה שיש לציין לדיון בפסחים בבע"כ ומכוון. ותחשב.
** כי מטא עומר -
צריך לדון מתי קרה מעשה זה:
1. קודם מעשה של תמיד. אם כן, קשה למה לא אמרו להם להביא. ואולי אף הם לא ידעו איפה למצא. גם יש לומר שרצו לקיים מצות קצירה בפני עצמם.
2. אחר מעשה של תמיד. צריך לומר, אז, שמה שקרה עם התמיד לא חרב ירושלים.
יש לדון איך יצאו ליקח את העומר. לצד ראשון, אולי (ע"ש) אפשר לומר שלא יצאו, אלא אמר להם להביא. גם ק"ק איך ידע שהיה שם חיטים אם לא היה יכול לצאת.
ונראה שאם נניח כצד שני נוכל לומר פשט כזה (לא לתרץ ק’ שלנו לעיל, אלא בענין אחר):
נראה שקשה למה מביא כל מעשה של תמיד, שאינו שייך לגמרא שלנו. ויש לדון. גם, אולי, קשה איך לא היה אלם הזה יכול לרמז בטוב לחבריו. נראה לבאר שהיה יכול לרמז בכחמת יוונית, אבל גזרו עליו, ואז לא היה יכול לרמוז. לכן, היה צריך לעשות רמז מוזר כזה, ואז הצריכו למרדכי בלשן. צריך להביא הא דתמיד לבאר כל זה. (ויש לדון, שרק אומר קללה על מי שמלמד חכמה יוונית, ולא מי שמשתמש בו. גם יודעים שהותר לצורך (כמו לקרובים למלך).
* סה:
** אם משה -
היה אפשר להקשות, אז, למה לא עשה כן בראש השנה.
** משה -
נמצא שלכאורה היו כופרים לומר שלא בא תורה מן השמים, אלא ממשה.
* סו.
** מלמד שישראל -
לשון זה מוזר (למה לא אמר, “מלמד שמהבהבים…").
* סז.
** יהא רעווא -
ק"ק, שלא בשמים היא. ויש לומר שרק אי אפשר לפסוק עליו, אבל עדיין ידע לדעת האמת. ויש לדון בזה, כמובן.
* סח:
** לא נאסרו -
זה מעניין. ויש לציין למה שגמרא (כ"מ, ולמשל, חולין קיג) אומר שחלב הותר מכללה אצל חיה. ויש לומר שאולי הוא שם שאותו מין (חלב) נאסר. ויש לדון מה נחשב מין (שהיה אפשר לומר כמו כן כאן).
* סח:
** שלא כסדרן -
יש לדון מהו הצד שיתיר:
1. מתיר שלא כסדרו.
2. אין צריך עומר כלל להתיר למזבח. (לכאורה, עדיין צריכים להמתין עד העומר כדי להסיר "משקה ישראל,” אבל אם כן (שעושים דברים חלוקים לגמרי), לכאורה לא יעכב סדר.)
* עא:
** סבר לה -
היה אפשר לומר כן בר"ש, אלא שר"ל שסובר כר"ע רבו. ותחשב.
** יש לדון
אם קצירה עושה טוב לקבן או הוא רק מצוה. גם יש לצרף שניהם, ולומר שקיום מצוה עושה טוב לקרבן. ותחשב על זה.
** ורבי -
ואם תאמר הלא מצינו מחלקתים ביניהם. ואולי כיון שיודעים שדן בזה ר"ע, לא מסתבר. ולא נראה, שבוודאי נמצא מח’ כעין זה בש"ס. ותחשב.
* עב.
** קצירכם -
מעניין איך נמעט מזה של מצוה, שהרי אין עומר ראשית קצירות של רשות, שאינו של רשות. ואולי ראשית יכול להיפרש "לפני,” ולא "ראשון.” ודחוק.
* עב:
** ר"פ -
צריך ביאור למה אומרו בכל מקום. גם צריך לומר למה אומר, “בכל מקום,” אם, בין כך ובין כך, יאמרנו בכל מקום. לכאורה, לא אמרו ר"פ בכל מקום, אלא גמרא אומרו בכל מקום (ועדיין צריך ביאור למה). ויש לדון אם הוא בעיה. ותחשב.
** צריך ביאור
איך ידע שכשנקמץ לעולם הוא של כהן, שהיה אפשר לומר שהוא של ישראל. נראה שלא חושב כן כיון שהוא קדשי קדשים.
* עג.
** מנחת העומר -
לכאורה, אומר הוה אמינא חלוקה ממה שאמר גמרא לעיל, אלא ששניהם מצטרפים (ששניהם דוחים מקור אחד).
** קמ"ל -
בכל אלו, יש לדון אם משנה מה עושה הקרבן או רק אם יכול ניתן לכהנים.
* עג:
** שלמי -
מעניין שמחשבתו על קרבן יכול לעשות כן. ואולי רצה לומר שכשאומר "שלמים,” יודעים אנו שכוונתו לומר עולה. ויש לדון אם יש לו דינים אחרים של שלמים. ותחשב.
* עד.
** אלא אמר רבא… תדירה -
תימה, שרבא הוא האומר בזבחים (צא) שאין מצוי ותדיר שווים. וצ"ל שהוא כל כך מצוי עד שנקרא תדיר (ע”ש). גם יש לומר שדומים די לומר זה (ורק תדיר הוא דרגה יותר גבוה, כמבואר שם).
* עה.
** אמר רבא -
יש להעיר שרבא אומר כעין זה אף בחולין (בבני יונה ותורים).
* עה:
** פתות -
יש לדון למה לא אומרים שכפל עליו קרא לעכב לשני פתים, ולא אומר שצריך ארבע. ותחשב.
* עו:
** היה מנופה -
צריך ביאור באיזה צירו קאי- אם כבר הגיעה לעשרון, פשוט שאינו מניפו יותר, שצריך עשרון (ואולי אומר שאז צריך ליקח יותר. עדיין הוא נגד משנה שלעיל). אם הוא ליותר מעשרון, אז, נגד משנה שלעיל הוא, שנמצא שלא יצטרך שלש סאים. ויש לומר שמשנה שלעיל אומר השיעור שמסתמא יגיע לזה. גם יש לומר שמשנה שלעיל חולק על זה. ותחשב.
* עז.
** תגרא -
לכאורה, אז, ייתלה בשיעור הרווחה. אז, צריך לבאר למה כך הוא שיעור הרווחה (אלא שבין כך ובין כך צריך לבאר כן).
* עז:
** שלא יטול -
יש לדון למה לא:
1. אולי לא נחשב אחד מעשר ממנו, שהרי אינו שווה לשאר (אולי הוא יותר או פחות, או שאינו כנגדו). ויש לדון, שגמרא לא היה יכול ללמוד מכאן שאינו להפריש כל מה שרוצה.
2. אולי לא נחשב שמפריש ממנו, שאינם חד כלל. ותחשב.
** חדש… א"י -
יש להעיר שלכאורה, אלו רק אחד, והוא שצריך להיות דבר שיש עליו איסור חדש, ולזה צריך שני קרק’ אלו. ותחשב.
** קצת קשה
למה לא אומר גמרא בכל דיון זה מה שלומדים לחומרא בדרך כלל. ותחשב.
** פרוס -
יש לדון אם הענין הוא שבעיה הוא לתרומה להיות פרוס או שבעיה הוא למנחה להיות פרוס. ואולי יש נפק"מ אם כבר נפרס, אם יכול ליתן אותו לכהן. ותחשב.
* עח.
** מעניין שגמרא
קורא לג"ש היקש.
* עט:
** אין לב ב"ד -
עיין ברש"י שמבואר שבהוה אמינא סובר גמרא שלא יחול תנאי. יש לדון למה לא. ולכאורה, היה יותר נראה לומר שסבר שלא מתנים בפועל. ותחשב.
* פא.
** ואידך -
לכאורה, אין צריכים שלשה, שיש להתנות שאם ראשון הוא תודה, מפריש אחריות, ואם לא, מפריש תודה. ותחשב.
* פב.
** שכן אינו טעון -
יש לדון מה שמניח שזה יהיה סיבה לאסור להביא אותו ממעשר. יש לדון, שהיה אפשר לומר שכיון שאינו כל כך קודש, יותר היה נראה להתיר הבאתו אף ממעשר. ויש לדון. וצריך לומר שמניח שיש סברה (ואולי שני הסברות אפשרות) שיותר קל להביא ממעשר לדבר יותר קדוש. אם כן, יותר נראה להביא בו דבר שיש בו זריקה. ותחשב.
* פג.
** ודנים -
צריך לומר שאף שרבי עקיבה, שלא דורש אפשר משאי אפשר, דורש ממקור של ברייתא זה, לא סובר ככל הברייתא. ויש לדון בזה, שאולי רק סובר כן כשנלמד מהיקש, ולא כשנלמד ממה מצינו. (עיין בשיח שי (נדה- גלגל רביעי) שבארנו את זה.)
* פד.
** אבל בארץ -
משמע שדין ארץ ודין חדש אינו חד דין. זה נגד מה שכתבנו לעיל. ותו"ת. ויש לדון, שגמרא תולה אותו בהיתר חדש בחו"ל.
** אלמא -
לא הבנתי ראיה זה.
* פה.
** עד שמעלה -
יש לדון מה זה אומר:
1. בודק כן ועל ידי זה עולה כל עפרה.
2. בודק כן עד שיודע שעלה כל עפרה.
* פה:
** שמן זית -
חושב אני שאומר גמרא בהוריות שהרגיל בשמן זית חכם.
* פו.
** בעי רבה -
עיין לעיל, ששם שאל רבא את זה שני פעמים. עיין לקמן, שרבי יוחנן שואל את זה.
* צב.
** שעירי -
מעניין שאומר לשון רבים בזה, אף שלא אומרו בקרבן אחר. (עיין במשנה שלא אומר לשון רבים.)
* צב:
** אם אסמכתא
הוא שתורה מגלה לרבנן לדרוש (כמו שאמר הריטב”א) צריך ביאור איך דורשים דבר אחר ממנו, ולמה גמרא מניח שמוכרחים לדרוש דבר אחר ממנו.
* צג:
** גופיה -
עיין בצדי צדדים על בבא בתרא, שהיה לנו צד שיחס של שאר ובשר אחד הוא יחס של קנין. ממה שאומר גמרא כאן שאינו כן בעבד (אם נניח ש”כגופו” ו”בשר אחד” הוא דבר שווה) משמע נגד מש”כ.
** זה בנה -
בדרך כלל, אומרים שזה בונה אב שכל מקום שלא מפרש, הוא הפוך ממקום שמפרש (ממה שצריך לפרש). ותחשב. ואולי זה רק אם היה סברה חיצונה לפרש כך, ואין צריכים פירוש שאומר תורה. ותחשב.
* צד:
** קנה -
הקושיא הוא כזה: כשהוא כשפינה, אינו רק triangular prism לבי צד עליון, אלא אף מקצר בכל צד, כספינה. אם כן, הוא דומה לbowl שהוא oval כשנראה מעליו. אז, מעליו, היה נראה כfootball. ממילא, יש רק מקום לקנה אחד.
מתרץ גמרא שהיה שם בצק, ואז על כל צד הקצר של הfootball, במשיך בצק כדי לשבת עליו קנה.
כן משמע מלשון פירושי ראשונים, אבל אם כן, צורתם מוזר, שצרים ציור מן הside, אבל רק של אמצע. ואולי אף כשנעשה יותר קרוב בצדדים, אינו ממש נוגע, ואז הוא קרוב לfootball, אבל אינו כמותו ממשע. נמצא שמעליו, יותר נראה כמו [fn:1]goatee. ותו"ת.
* צח.
** שש -
לכאורה, אין סיבה לחשוב שהוא דווקא שמנה וארבע, אלא הוה אמינא שיכול לעשות אף זה. ותחשב.
* צט:
** דבר אחד-
נראה לדייק, אולי, מלשון "דבר אחד,” שהיה אפשר לומר רק "דבר.” אולי הענין הוא שאם שכח דבר, מסתמא אנוס הוא, שמי יזכור את הכל, אבל אם שכח רק דבר אחד, וזכר את השאר, לכאורה, היה יכול בלי כל כך טורח לזכור אף אותו דבר. אם כן, עובר על הלאו.
** פן תשכח את הדברים -
מעניין שיש לאו על כל אחד כיון שאומר "הדברים.” ואולי לכן מדגיש שהוא אף על דבר אחד.
** יכול אפילו -
קשה, שאינו עובר על שום איסור כשהוא אונס. ויש לומר שאומר שאין אף סיבה רעה של עבירה (שאין ס"ר של עבירה מה שלא יודע תורה, אלא מה שביזה אותו ושכחו). מעניין שתורה יאמר לנו מתי יש ס"ר, אף שאין, בי"כ ובי"כ, ציווי. גם יש לומר שמרבה דבר שאינו אונס ממש, אלא קרוב לאונס. כן, אולי, נראה מן הקנטרס"ט שאומר גמרא, שהוא רק במסיר אותם מלבו. ותחשב.
** מחצה -
נראה שיש לדון אם קדש הקדשים הוא מקום יותר קדוש שבבית, או שהוא יותר קדוש רק מפני שהוא מקום הארון (ואף אם אין ארון שם, הוא מקומו, שראוי להיות שם). נראה שאולי בזה חולקים כאן, והוא שמי שאמר מחצה סובר שקדושת ק"ק בא ממקומו, והוא שהוא בית חלוק, אבל החולק סובר שבא ממה שארון שם, ועדיין כולו חד בית. ותחשב.
** מכאן -
גם היה אפשר ללמוד ממה ששופר באמצע כשמצות היום בו וחצוצרות באמצע כשמצות היום בו (בר"ה). ותחשב.
** דמדלי -
קשה, שאם כן, הוא יותר מעשרים אמה, ונמצא שאינו רק בחצי הבית. ואולי רק אומר זה על של שלמה, אבל לא על של משה.
** חמשה מימין -
לכאורה, זה אינו למאן דאמר מצפון לדרום, שלאותו מאן דאמר, ארבע לזה וארבע לזה, וכנגד עוד ארבע. ותו"ת.
** בפרהסיא -
משמע שאם אינו בפרהסיה יכולים לבזות אותו. ויש לדון, שאולי רק בפרהסיה יש הוה אמינא לבזותו כיון שבני אדם ילמד מאותו בזיון.
** ונשמה -
עיין בביאור רש"י בזה. מעניין שנקרא זה יצירת נשמה. אולי כשאומר נשמה, כוונתו לומר חיות. ודחוק. ותחשב.
** בבליים -
נראה שלא רק היה דעתם יפה, אלא שהיו חשוקים המצוה (כמו שאומר גמרא ביומא גבי שעיר המשתלח. )
** לא ימוש -
לכאורה, חלק על רבי יוסי.
* קא:
** שאתה יכול להאכיל -
יש לדון למה יש לו טומאת אוכלים:
1. יכול לבוא לאחד הנאת אכילה, שיכול ישראל ליתן לגוי לאכול. יש להעיר שאף כל דבר יכול לבוא לידי הנאת אכילה, שיכול לגוי לקח אותו ולאכול, אלא שכיון שאי אפשר לישראל ליהנות ממנו, לא יוכל לתת אותו לגוי. (ואם תאמר, הרי יכול גוי לגזול אותו ממנו. ויש לומר שזה לא מצוי. גם יש לומר שאסור לו לגזול. וזה תלוי מתי הותרו שבע מצות).
2. יכול לבוא לישראל (או לבעל) הנאה של אכילה- אלא שאומר שהנאה של תודה שנותן או ממון שנותן מחמת אכילה מיוחס לאכילה עד שנקרא הנאת אכילה.
אולי לשון גמרא של "יכול להאכיל" משמע שהנקודה הוא מה שמאכיל אותו, והוא כצד שני. ופשוט לדחות שרק אומר ההגדרה שיימצא למעשה. ותחשב.
* קו.
** כי קא מסתפקא -
יש לדון אם כל אחד מאלו סיבה שלא להסתפק או שמפני כולם אין ספק (ואחד שיש כזה ויש כזה). ותחשב.
* קז:
** שאין לך -
ואם תאמר אם כן אף כשפירש. ויש לומר שממה שהוצרך לפרש פשוט שיותר מדבר אחד הובא בסלע. ואם תאמר אם כן למה יביא רק כבש. ויש לומר שרק רצה לומר שבדרך כלל לא נמצא דבר אחר בסלע, ואין צריכים לחוש לו אלא אם כן יש לנו הוכחה שנמצא. גם יש לומר שאומר שאין לך דבר שרוצה ה’ שיבוא בסלע אלא כבש (ששאר דברים רוצה ה’ שיביא אחר ממינו). אם פירש, פשוט שהתנדב דבר אף שה’ רצה שיביא גדול ממינו. ותחשב.
[אגב, מעניין ששור בן סלע גרוע מכבש בן סלע, אף ששניהם שווים. צריך לומר שהוא מפני שבני אדם חושבים, “רע” כשרואים אותו שור (מפני שמדמים אותו לשוורים אחרים, אבל חושבי,ם "טוב" כשרואים אותו כבש. ותחשב על זה.]
* קח.
** כזעירי -
יש להעיר על זה:
1. דנים מה יעשה סתם משנה. רבי סתם משניות (על כל פנים, לפי רש"י בביצה ובכ"מ). אם כן, אף שרבי לא פסק לעולם כעצמו (ולכאורה, הוא ממה שמצינו שיש אמוראים שאומרים לפעמים שאין לעשות כשיטתם), אינו מוזר שיסתום כעצמו. ותחשב.
2. משנה זה נסתם חלק ממנו כרבי. אם כן, הוא כעין סתם ואחר כך מחלקת. ותחשב.
* קט.
** אי סגיא -
לא הבנתי למה יכול להיאו בבית המקדש, שלכאורה לא יכול להביאו בבית חניו, ונמצא שלא חל נזירותו. ותחשב.
* קט:
** שב ועומד -
מעניין, שלכאורה, אף שוגג צריך תשובה, שהרי שוגג מביא קרבן חטאת. ותחשב. ואולי לא רצה לומר שנחשב כבר שב, אלא אומר שעומד לשוב (ולא היה לו לומר, “ושב”). ויש לדון בזה.
* קי.
** כאילו -
קשה, שכבר אמר שאינו צריך. ויש לומר שאינו צריך כיון שכאילו מביא (ורבא רק משנה ביאור איך דורשים). יש לדון, עדיין, למה צריכים שני דרשות.
* נב.
** רבי שמעון -
יש לדון למה גמרא רק דן ברבי שמעון, ולא ברבי יהודה, שלכאו' כמו שיש סתירה בשיטת רבי שמעון, כך יש סתירה בשיטת רבי יהודה. ותו"ת.
** דאי -
מעניין שקורא לזה "דאי," אף שלא בא על ידי איסור.
** האי נמי -
יש להעיר שהם צחקו על הראיה שלו, ולא אומר כאן שהראיה שלו היה טוב. ותו"ת.
** שמן -
נראה שדרך הפשוט להבין את זה הוא שחולקים אם שניהם הם שני קרבנות או קרבן אחד.
* נב:
** דאי הוה -
יש להעיר שזה מין אחר של דאי, שזה דין דיעבד, ולא שהשיעור שאומר נוגע רק אם קרה דבר. במילים אחרים, השיעור שאומר אינו דיעבד, הדין דיעבד. ותחשב.
* Footnotes
[fn:1] כמובן, אם יש לך שאלה על מציאות מושג זה, יש לשאול לא.י.ש.
