* ד:
** אשם מצורע -
לא רק מכשירו לבא למחנה; אף מכשירו לאכול קדשים. צריך ביאור למה רק מזכיר את זה.
* ו:
** זר -
יש לדון איך נלמד מבכורות, שאז היה להם קדושה. ותו"ת. גם יש להעיר שמרשי משמע שאין זר מביא בבמה. עיין לעיל, שחושב אני שאינו כן.
* י.
** … מאמצע הכלי
(בתוך רש"י)- לא רצה לומר שיעשנו מאמצע ולא מאותו מד, שלכאורה, יכול ליקח אותו אף מצד האחר. לכאורה, רצה לומר מחציו ברוחב, שהרי כשמסלק לבונה, נמצא שהוא נמוך ממה שהיה. ותו"ת.
* יא.
** זה אמה -
ק"ק למה לא אמר מה שיש לאמה נפק"מ בכמה וכמה דינים, ולא רק בבנין בית המקדש.
** מלח -
לכאורה, רצה לומר לא זו אף זו. ואולי מבאר ענינו (שידע רק זה, ושוב נתחדש לו…)
** מן הצד -
לא הבנתי, שעדיין חוצץ בין סלת לסל.
* יא:
** לשון אחר -
לזה, לכאורה, דין של משנה הוא רק כשהוא לבונתה. היה אפשר לומר, אז, שזה היה הכרח של רב לעיל (ובאמת, ק"ק לצד זה למה לא אומר כן גמרא).
* יב.
** כל הקומץ -
דבטלה דעתו- דנינו בזה בשיח שי בזבחים, והערנו שלפעמים חושב על אותו מעשה, ותלוי רק מה קורא אותו. אם כן, ק"ק מה לנו בביטול דעתו. ותחשב.
* יד:
** שאין -
אם נפסל- גם היה אפשר לומר שלא נפסל חציו השני, אלא שצריכים לנהוג עמו כחצי הראשון. ותו"ת. ודע שבכל ציורים אלו, יש לדון למה לא עושים להיפך, וגוררים הפסול בתר הכשר. ותו"ת.
* יח.
** עד אחד -
גם אפשר לומר שר"ל שהיה הכי חביב לו.
* כא.
** נותנת טעם כבינה -
כמובן, זה לשון מעניין.
* כא:
** אינו חוטא -
מביא חולין- ועוד שאולי גורם שצריך לבער את המנחה (שהוא של כהן).
* כה.
** אמר קרא -
מפני כבוד ציבור- זה מעניין. ויש לדון איזה כבוד יש בזה. ונראה שאין כבוד בהיותו כשר, אלא יש כבוד בנתינת התירים מיוחדים לצבור. ותחשב.
* כז.
** דעושים -
יש לציין לגמרא קידושין שאומר שמצות, ולא עבירות, עושה פירות. ועיין שם. (אולי לכן יש אותו משל.) ותחשב.
* כט.
** שאין גויל -
עיין במה שביאור. גם יש לומר שמשמעות זה ממשנה הוא שמעכב שיהיה כתב אחד אחד ממש, ולא חלק מדבר אחר (שאינו מוקף גויל).
* לג.
** אם יעבור -
ק"ק, שמגמרא בסוף הוריות נראה שכיון שהיה נשיא, אין עמידתם תלוי באם הוא לפניהם אלא באם נכנס לשם. ואולי רצה לומר שאם הוא לפניהם, יראו שבא. ודחוק.
* נ.
** ולא פי’ טעם -
צריך ביאור למה לא אומר שטעם הוא מפני גזרה שווה של גמרא לעיל.
* ס.
** כל שאין לו קמיצה -
להתיר- כ’ כן מפני שיש אומרים שכעין אלו יש להם קמיצה, אלא שאף שיריים על מזבח. וע’ לקמן.
* סח.
** אר"י -
לא אמרו לריב"ז כיון שהיה רבו של רבו של רבו. גם, לר"י רבי יוחנן (אמורא) אם אמרו לריב"ז, היה מבאר לו שלא חלקו.
* סח:
** בשיטת -
עיין בקושייתו. ונראה שכיון שיש מחלקת בעלמא בעד ודע בכלל, יש שיטה שיאמר כר"י ור"ל כאן (שאומר ר"י כמותם בביאור הקרא, אלא שחולקים ב"עד ועד בכלל”).
* עב:
** אלא -
יש לדון מה לנו איזה קדם (ואם שבת יידחה לפניו או לאחריו). ויש לומר ששבת נשתנה כשנדחית, ואותו שינוי נמשך עד סוף אותו השבת (ובאותו זמן, כיון שכבר נשתנית, אין כל כך בעיה בעוד שינוי).
** אבל מנחת חוטא -
צריך ביאור למה אומר כל זה(חילוק כהן וישראל) כאן ולא במנחה אחרת. ותחשב.
* עה:
** אבל מקפלה -
מש"א שהוא מחצה כיון ששיעורה מחצה הוא יותר טוב לפירוש אחרון שכ’ בביאור, “כזית…."
* עו.
** ועצם -
משמע שאין בנין אב ומה מצינו שווה. צריך ביאור מהו החילוק (שיש בנין אב עם שני כתובים, אבל יש בנין אב עם כתוב אחד).
* עח:
** נא -
עיין במה שפרש"י בביאור ק’ גמרא. יש להעיר שאף גבי פסח אין נא משמע שלא בישלו כלל. אם כן, היה אפשר לומר שגמרא סובר שאותו מילה לא משמע כן כלל, ואז שואל איך להגדירו.
** עיין במה
שאומר רש"י שהענין הוא שעומד לפרוך. גם היה אפשר לומר שאומר גמרא שלא יהיה כשר כיון שאינו חשוב, כמו מה שפרוס אינו חשוב. ותו"ת
* עט.
** חול"ז -
עיין בחילוק שאומר רש"י. גם היה אפשר לומר שחול"ז מרצה לפיגולו יותר (שהרי חייב כרת).
** עיקר -
עיין במש"פ שהוא התחילה (וכן, לכאורה, נראה מגמרא). מעניין שעיקר ישמיע כן. ויש להעיר שכן הוא במילת, “מעיקרא.”
* פד:
** רבי יוחנן -
משמע שיש לסמוך על חלום. לולי רש"י, היה אפשר לומר שראה שיאמר דבר טוב, אבל לא ראה מהו. ויש לומר שאינו בעיה של "לא בשמים" כיון שזה רק נתן לו הרעיון, ואחר כך חשב עליו, והבין שהיה נכון.
* פה.
** תבן -
עיין במש"א רש"י. גם היה אפשר לומר שאמר משה שהביא שם, ששם החשיבו אותו, וידעו שהוא מה’, כמו שיביא פירות למקום של פירות, כדי שיבינו שהם פירות טובים.
* פו:
** מנורה -
צריך ביאור מה לנו שהיה מזבח באמצע, שהיה נמוך, ולא היה מפסיק האור. ואולי רצה לומר שלא יהה שלחן כל כך קרוב למנורה (והיה השלחן צריך אור יותר ממזבח. ויש לדון.)
* פז.
** והוו -
צריך ביאור מה רואה על עתיד, שגמרא משמע שדן במה קרה לפני זמן (אומר, “מעיקרא").
* צד:
** כמין -
עיין במה שפירש למה נחשב רוקד. גם היה אפשר לומר שנקרא כן כיון שדבר שהוא על ים מד מצד לצד, כאילו הוא רוקד. ותו"ת.
* צו:
** פרקדא -
עיין במה שבאר רש"י. אם כן, נמצא שהיו כל החלות slanted לפנים. וק"ק למה לא אומר גמרא שהיה כולו בחוץ (שהיה מחובר לחוץ של השלחן). ותו"ת.
* צט:
** אשר -
עיין בביאור רש"י כאן בדרשה. עיין בשבת, שלא מפרש כן.
** זהו יסודה -
חושב אני שרגילים בני אדם לפרש את זה (או, מה שאומרים כעין זה, ש"ביטולה זהו קיומה") לומר שביטולה גורם לקיומה, שכיון שמבטל אותה, יכול לקיים אותה יותר. ותח’. מרש"י זה נראה שהענין הוא שבא לו שכר שווה. על זה.
יש להעיר שלכאורה, מה שאומר בענין שכר הוא רק סימן. ועיין ברש"י בתחילת פרק שני של קידושין, שלכאורה אומר כעין זה.
יש להעיר שמה שיש לו שכר שווה לכאורה לא רצה לומר שיש לו שכר כאילו יש לו תורה (רצה לומר, שכר של מהו שהיו בני ישראל זכאים אם בא להם לוחות. ותו"ת.) וגם יש להעיר שאין ראיה שהוא טוב כאילו יסדו, שאולי רק רע למומר לעשותו (שקל וחומר של משה נכון), ואם כן, נמצא שטוב לשברו. כן משמע, באמת, מגמרא ביבמות, שאומר שזה אחד מן הפעמים שדרש משה דבר והסכים ה’ לו. ותו"ת.
** על פתח -
לולי רש"י, היה אפשר לומר שהיו נותנים של כסף שם כדי שלא להפסיד ממון של בני ישראל, ולא היה עדיין צורך לאחד שהוא יותר טוב. לא נראה כן, שלכאורה, לעולם זהב הוא יותר טוב. ותחשב.
* קא:
** הואיל -
עיין בגמרא שאומר כן (בנזיר ופסחים) ששם לא מסיק גמרא כן. וצריך לומר שרש"י סובר שרק לא מסיק שזה הסיבה שנחשב חידוש, שיש לחלק בין זה לבישול לומר שיש סיבה פשוטה למה זה יהיה מותר וזה יהיה אסור, אבל עדיין נחשב בשר בחלב די. ותחשב.
גם יש להעיר שמרש"י נמצא שאין הענין שהיה לאותו חפץ עצמו הכשר, שמי אומר שהיה שורה אותו קודם בישולו, אלא אומר שבמינו יש הכשר. ותחשב. ויש לדחות שמפני שנתבשל די לעשותו אסור היה כן. ותחשב.
* קו.
** רבנן -
קומץ בדעתו- גם אומר כן לקמן, אלא שרוצה להביא מה שכבר בא, שמסתמא הלומד גמרא זה כבר ראה אותו גמרא. ותחשב.
ודע שיש לדון למה גמרא מעורר כן לקמן אבל לא כאן. ותחשב.
