* ב:
** רש"י דמינכרא-
יש לדון למה רש"י בחר לבאר כאן שכל דיברו של קדשים רצה לומר אמירה. נראה שרש"י סובר שיש בעיה במה שניכר שאינו אמת כיון שהוא ניכר לשאר בני אדם, והוא ששומעים המחשבה, ורואים שאינו נכון. גם אפשר שרש"י סובר שרק אז נוכל לומר שניכר שאינו נכון, שלו תמיד ניכר שאינו נכון. ויש לדון.
באמת, צריך ביאור איך כל סוגיה זו הולכת עם המחלקת בפסחים ובמק"א אם עקירה בטעות שמה עקירה. אם לא שמה עקירה, צריך לומר שמדובר במי שחשוב שיכול לעשות מנחה למין מנחה אחרת על ידי מחשבה, אבל סובר שעדיין יעשה כמעשי מנחה שהיה. ותחשב.
* ג.
** מיצוי –
נמצא שמה שלפני כן לא נעשה מעשה לא עושה שניכר שמשקר. נראה שמוכרחים לומר כעין זה, שהרי בוודאי קידוש שלו לא מוכיח. ויש לדון, שיש לומר שצריך להיות מעשה החושב. ותחשב. אבל, יש להעיר שלא צריך להיות שאותו כהן שחושב הוא הוא שבחר שלא להזות, שיכול להיות שכהן אחר נתן לו ואמר שזה חטאת וימצה. (אפשרלהיות, באמת, אז שבזה מדבר גמרא. אבל, סתימותו לא משמע כן.)
* ט:
** מנחה לגבי דם -
יש לדון מה רצה לומר:
1. מנחה נחשבת כמו יבש לגבי מה שדרכו בו. אז, כמו שמקדש מנחה, מסתבר שגם יכול לקדש יבש ממש. יש לדון בזה, שיש לומר שרק מה שקצת לח מקדש, כיון שהוא קצת דומה למה שדרכו בו.
2. כשאומר שמקדש יבש, כיוון למנחה. קרא אותו יבש כיון שלגבי דם נחשב יבש.
** רש"י נכנסים להיכל -
מעניין שרש"י מבאר שההו"א הוא לפסול אותו אחרי שיצא לשם. לכאו’, אז אין זה בזיון (שיהיה כשר שם). אלא, צריך לומר שההו"א הוא שאין לאכול שם (שהוא קצת בזיון). נראה שרש"י מניח שאחרי שאין לאכול שם, גם ייפסל בביאתו שם.
* ט:
** שמאלית אחרת -
קשה איך נדרוש מכאן מיעוט אחר מיעוט, שהראשון אינו מיעוט, אלא הוא נצרך לגופיה. נמצא שגם על דבר שנצרך לגופיה (דהיינו, שאומר הדין שהוא משמע ביותר ובפשיטות) אומרים כלל של מיעוט אחר מיעוט.
גם עיין ברש"י, שמשמע שממיעוט אחרי מיעוט זה היינו מרבים יד ימין של כהן. קצת קשה, שהפסוק לא מדבר ביד הכהן, אלא ביד המצורע. אם כן, היה נראה לומר שמיעוט אחר מיעוט זה ירבה יד ימין של מצורע. ותחשב.
* י.
** צדי צדדים -
לא כל כך פשוט לי מהו צדי צדדים. עיין ברש"י. נראה שרש"י סובר שצריך להיות על גב היד, איפה שיש צפורן. גם יכול להיות בצד זה. אבל, לא יכול להיות בפנים, שהוא הסמוך לכף ופס היד, שהוא המקום שיש בו פינגארפרינ"ט. אחוריים נקרא צידי צדדים כיון שהוא הצד של הצד. ותחשב. (במילים אחרים, הוא 180 דג’, ואז הוא 90 דג’ של 90 דג’. אז, הוא צדי צדדים.)
** נשנית הכל -
וא"ת למה כופל את כל הפרשה בשביל דבר אחד שמחדש. ויש לומר שהוא כדי שהלומד פרשה אחת יוכל ללמוד רק אותה פרשה, ולא יצטרך ללמוד פרשה אחרת עמה. נמצא שבריבוי דברים ממעט מה שכל אחד צריך ללמד כדי לדעת סוגיה. ותחשב.
** לעולם -
עיין ברש"י שפי’ למה לא נצרך הולכה להרצאה. לכאו’, היה לו לומר שלא נצרך כיון שהקטרה עצמו לא נצרך להרצאה, שהדם הוא מרצה, ולא האימורים.
* יא.
** הנחה -
גמרא התחיל בדיבור על קומץ ועכשיו מדבר על קידוש קומץ. נראה שיש לדון אם קידוש קומץ הוא חלק מדין קומץ או לא. אף אם אינו חלק מדין קומץ, גם אפשר שאיפה ששם את הקומץ (בתוך כלי או לא) הוא חלק מדין קומץ. ותחשב.
** פליג בבריי’ -
עיין ברש"י שפי’ למה לא הקשה מקומץ. נמצא ש,על כל פנים כאן, המקשה לא ידע את התשובה למה שהקשה. אבל, אפשר לדחות שתמיד ידע את התשובה, אבל הקשה מה שצריך להקשות כדי להביא תשובה שבלי הקושיה לא היה מובא. אבל, קושייה אחרת תביא תשובת קומץ, ולא צריך להקשות קושיה זו על קומץ. ותחשב.
** מלח -
וא"ת למה לא רק פי’ רש"י שהוא לא זו אף זו. צריך לומר שאכן רש"י מפרש כן, ורש"י לא אומר מילים של הגמרא – לא זו אף זו – אלא מבאר ענין של לא זו אף זו. מלשון רש"י, נראה שבא לפרש כמו שמשמע מן הגמרא ביבמות (לג), שהוא שרבי שמע דין מתנא, ושוב שמע דין יותר מחודש, והוסיף על המשנה שכבר שנה מן התנא הראשון. מפני כבוד התנא, או מפני שכבר ידוע, לא הסיר את המשנה הראשונה, אלא הוסיף עליו.
** קמיצה -
לא פשוט לי בכלל איך קומצים. צריך לעיין בגמרא זה, לראות איך קומצים. נראה שצריך להיות ששוקע את כל ידו במנחה, ושוב קומץ בראשי אצבעות, שמביא ראשי אצבעות אל פס ידו. ותחשב.
** מאי איריה -
הלשון משמע שההוכחה היא ממה שנקט לשון זה, ולא נקט לשון יותר טוב של "הותר מן השמן.” יש להעיר שלשון שנקט יותר קצר, ואז מובן למה נקט אותו. אלא, היה לו לגמ’ להוכיח ממה שמשמעות הלשון של "שמנה" הוא כמו שפי’ הגמרא. נראה שאותה משמעות לא מהני בפני עצמה, שהיא רק משמעות קטנה. אבל, כיון שיש קצת משמעות כן, לא היה לו לנקוט אותו לשון בלי סיבה טובה. ממה שאין סיבה אחרת לנקוט אותו, צריך לומר שמה שלא חש לאותה משמעות הוא מפני שהמשמעות נכונה, כמו שדייק הגמרא. ותחשב.
* יא:
** אשר על המנחה -
רבי מאיר כבר דרש את זה, לומר שצריך להיות שווה למה שהיתה כשהיא על המנחה, ודרשת ר"י ור"ש ממנו לא שייכים לו. ותו"ת.
** רבי מאיר-
כמובן, יש לדון אם שיטת רבי היא שצריך קומץ של לבונה בסוף, כמו שצריך בתחילה, או שצריך להיות שווה בסוף לתחילה. ותחשב.
* יב.
** פסול דגוף -
אין כל ענין זה כל כך פשוט לי. לכאו’, הפסול כאן הוא על הנשאר, והפסול הוא מחמת דבר אחר, שהוא החלק שלא נשאר עוד. נראה שחושבים על כל המנחה כאחד. אז, המנחה נשתנה בשינוי הניכר שיש בו רושם, והוא שחסר. ותחשב.
* יג:
** הכא קא שקיל-
יש להעיר שלכאו’ זה סיבה לפסול יותר, שהוא יותר נעשה על ידי כהן. צריך לומר שההו"א הוא שדמיון לדם זבח הוא סיבה, ולא סימן. צריך ביאור.
** מחשבה -
ואם תאמר בוודאי יש מעלה במחשבה, במה שהוא מחייב כרת. ויש לומר שזה מעלה במה קורה אם חל, אבל אין מעלה לו שיחול. ותחשב.
* יד:
** שאין ציבור חלוק -
יש לדון מהו הפסול:
1. הפסול הוא מה שחצי ממנו פסול.
2. יחסו לו הביא לו את אותו הפסול.
3. פסול בא לכולו, ולא רק למקצתו. ותחשב.
תחשב על אלו, שכולם שונים, וכולם צדדים טובים.
כמו כן יש לדון בצדדים אלו בתודה ולחמה וכדו’.
* טו.
** לימוד ערוך -
לכאו’, זה רצה לומר שהלכה למשה מסיני הוא (שאם לא כן, עדיין צריך קרא).
** גלל -
יש לדון מהו החילוק:
1. תודה עושה עיקר הטוב.
2. לחם רק מעלה את התודה.
3. יש צורך לתודה בלי לחם, ותודה עושה הצורך ללחם.
** הוזקקו -
קצת קשה למה לא אומר שהו"א שרק בתודה פוסל את הלחם, כיון שהלחם נקרא תודה, כמו שסבר ההו"א של הגמרא.
** המפגל -
נראה שהענין כאן ובכלאים הוא שיש שני דברים לדון על דברים אלו – כדבר אחד או כשני דברים. הפיגול (או הכלאים) פוסלים רק כדבר אחד (רצה לומר, משניהם יש פסול). אבל, על שניהם כדבר אחד אין פסול, שרק אחד מהם פסול ואסור. אבל, בשניהם כשני דברים (שעל זה יש פסול ואיסור) אין פוסל ואוסר. אז, נמצא שמה שפסל אין בו פסול ומה שבא לפסול יש בו פסול. ותחשב.
* טו:
** כולו בלחם -
הקל וחומר צריך ביאור, שיותר יש צד לפסול תודה כיון שחלק מן המחשבה היא על תודה. ותחשב.
** חברו -
מעניין שאין אף צד שמחשבתו שבמוחו (לא מחשבתו שאמר) יפרש את מחשבתו שאמר. כנראה אף לענין זה אומרים שדברים שבלב אינם דברים. ותחשב.
* יז:
** רש"י בשיטת רבי אליעזר -
רש"י מפרש שר"א פוסל מדרבנן. עיין לקמן בגמרא, שההו"א (ואולי תנא אחד) לא סבר כן. נראה שרש"י מבאר לפי המסקנא כיון שיוצא מזה ביאור נאה במשנה. כיון שרש"י עכשיו מבאר את המשנה, מבאר אותו על פי המסקנא. ותחשב.
** אכילה -
קצת קשה למה לא דורשים מלשון אכילה שרק חייב אם חשב על לשון אכילה, ולא שאף חייב אם חשב על לשון אכילה.
** אכילה -
ואם תאמר למה צריך קרא זה, שכיון שנקרא אכילה, חייב עליו, כמו אם חשב על אכילת כלב. ויש לומר שזה גופא יודעים מכאן, שמזה דורשים שכל שנקרא אכילה יש בו פיגול, ולא רק אכילת אדם. גם יש לומר שנקרא אכילת אש, כיון שהאש אוכל אותו. כאן, לא חושב על אכילת אש, אלא על אכילת המזבח. ותחשב על זה.
* יח.
** לאחד -
עיין בשני פירושים שמביא רש"י. גם יש לומר שאהב אותו לאחד, והוא שאהב אותו (ויש לדון אם מדבר על התלמיד לרבו או על הרב לתלמיד) באהבה שלא אהב שום אחר, והיה כאחד בעיניו. ותו"ת.
* יח:
** ראוי לבילה -
נראה שאפשר שענין של ראוי לבילה הוא שבעיקר בילה מעכבת, אלא שכמו שאומרים שכל העומד לזריקה כזרוק, כך, בכל הראוי לבילה, אומרים שהוא נחשב כבלול. אם כן, רק במה שלא עומד לבילה יש עיכוב כשלא בפועל נבלל. ותחשב. (על פי זה, נראה לבאר מה שכ' רש"י שלא חולקים רבי אליעזר בן יעקב ורבנן אלא במחלקת קטנה, והוא שרבנן סוברים שבששים, כיון שקשה לבלל אותו, אף שאפשר לבלל, לא עומד כל כך לבילה, ואז לא יכולים לומר עליו ש"כל העומד לבילה כבלול." ותחשב.)
* כ.
** כלי אחד -
איני מבין, אז, למה שאר קרבנות צריכים מלח, שאין שום דבר שהם צריכים שבא בכלי אחד עמהם. (איני מבין לשון גמרא כל כך; נראה שאולי בא ליישב למה עצים מהני לכך, אבל לא הבנתי מה שאומר.)
* כא:
** אכילה -
יש לדון למה אכילה יותר פשוט:
א. יש בו מצווה באכילתו:
אא. מלח הוא לצורך מצווה.
אב. מלח נאכל עם אכילת מצווה.
ב. יש בו קדושה יותר מן העור.
* כב.
** קא משמע לן -
יש להעיר שלשון המשנה משמע שקא משמע לן שאינו כן, אלא יש להם חלק בלשכה. יש להעיר שההו"א נכונה, ובעצם אין להם חלק בלשכה, אלא שתקנו שיהיו יולכים למלוח במלח של ציבור.
** הדיוט -
איני מבין את זה כל כך. לכאו', הענין הוא שכיון שהוקנו להדיוט, השתמש בהם הדיוט. אבל, קשה,שגם בית המקדש קונה אותם מהדיוט, כמו דוד מארנונה. אז, נראה שרצה לומר שכיון שהיה צריך לקנות מיוחדים לכך, וצריכים להיות חדשים, זה מאד קשה לכל יחיד להשיג, ולא מסתבר שבזה חייב אותו ה'. דחוק.
** לשון יחיד -
עיין ברש"י. נראה שאפשר לומר שאומר לשון יחיד כיון שדן בתערובת, ולא במנחה. אבל, לשון רש"י לא משמע כן, אלא שמשמע שדן במנחה. איני יודע אם הוא מנחה המעורב או מנחה שמעורב בו, וגם איני יודע למה ידון רק באחד. ותחשב.
* כג.
** מין במינו -
צריך ביאור למה זה שייך כאן, שלכאו' רבי יהודה פסל אותו כיון שריבה בשמנה או חסר בשמנה. ותחשב.
** סלק -
וא"ת למה צריך שבזה יש יותר שמן ובזה יש פחות שמן, כמו שאמר רבי יהודה במשנה. ויש לומר שאם לא כן, היו שניהם מין אחד - מנחה. כיון שאינם שווים בסולת, אינם נחשבים מין אחד. לא נראה כן, שאז אינו בכלל מין במינו. אלא, צריך לומר שאז הסולת במיותר בזה אינו ממין האחר, ואז השמן המיותר בזו אינו ממין האחר. ותחשב.
** נבלה בשחוטה -
נראה שאפשר לפרש שענין המחלקת הוא בלומדות של ביטול, למה דבר מועט בטל בדבר גדול. נראה שיש שני דרכים לפרש אותו:
1. צד הראשון הוא ששם של הגדול חל על כל החפץ, ומסיר את שם של הקטן ממנו. אז, לכולו יש שם של הגדול.
2. צד השני הוא ששם של הקטן לא חשוב, כיון שלרוב החפץ אינו השם (רצה לומר, נותן שם רק למועט של החפץ). לכן, הוא בטל מן המועט.
לראשון, ייתלה באם שם של הגדול סותר את שם של הקטן או אם יכול להית נאמר עליו, ולראשון תלוי באם שם של המועט סותר את שם של הרוב או אם יכול להיות נאמר עליו. ותחשב.
* כג:
** רבי חייא -
איני מבין מקור שיטת רבי יהודה, לפי רבי חייא, שזה לא יהיה מין במינו, שהרי אין דם הפר יכול להיות נעשה דם השעיר, ואין דם השעיר נעשה דם הפר. אולי שם שניהם יכולים להיעשות דבר אחד, ששניהם יכולים להיעשות קדשים פסולים. מחודש שזה יהני, שלא נראה שאם רק אחד נעשה כשני יגרע מזה. ותחשב.
** טבל בשל שיריים -
צריך ביאור למה גמרא מניח שהטבל ייבטל לתוך השיריים, שלכאו' יש יותר טבל, שלא ניטל ממנו קומץ. אפשר לומר שחוששים שמקצת מעורב במקצת, עד שבמקום אחד יש רוב של שיריים. אבל, אז יהיה קשה לשניהם, ששניהם הם המבטלים והבטלים.
** טפל נעשה שיריים -
ואם תאמר אין כולו נעשה שיריים. עיין לקמן, שגמרא מבאר יותר, ואומר שכיון שכל חלק ממנו ראוי להיות שיריים, נחשב שיכול להיות נעשה שווה לו. ותחשב.
* כד.
** שבע לה טומאה -
נראה לומר שני צדדים פשוטים בזה:
1. כיון שכבר יש לו שם טמא, לא חל עליו עוד שם טמא.
2. טומאה בא מירידה, שהיה במצב של קדושה וירד. אז, אי אפשר לדבר טמא להיות נטמא, שכבר פיחת בקדושתו.
** אחד -
מרש"י יוצא שמה שעושה לשני דברים אחד הוא שהם בכלי אחד, ונוגעים בתוך אויר הכלי. ותו"ת.
* כד:
** תחתון -
אינו ברור לי למה אין בראשון גם מגע מדרס. צריך לומר שמצמצמים לומר שהראשון נעשה מדרס קודם שהשני נעשה מדרס, שהיה קצת זמן - זמן קטן ממש - משעה שישב עד שעה שנשען (שכאילו נפל עליו), והרי נפל על הראשון קודם שנפל על השני. [fn:1] אבל, אז לכאו' יוצא שנגע שני בראשון ונעשה מדרס קודם שהוא עצמו נעשה מדרס, שהוא נעשה מגע מדרס כשראשון נעשה מדרס. אם כן, מה שאומר שהוא בבת אחת אינו דווקא, שהוא, כמו לעיל, שטומאה חמורה חלה על טומאה קלה. אז, הנחות הגמרא צריך ביאור.
** רב אשי-
רש"י כ' בביאור רב אשי שאין לעמוד על סופו. לכאו', זה ייתלה בברירה. [fn:2]
** מיוחד לישיבה -
יש לדון אם יושב על דבר שאינו מיוחד לישיבה שהוא על דבר המיוחד לישיבה, שתלוי באם זה דין במעשה ישיבה או דין בחפץ. ותחשב. (ככה שאלה לי אשתי י.ח.ח..)
* כה.
** דחיתיו -
לכאו', משמע שרצה לומר שטומאה בציבור נדחה וששמאל של יה"כ לא נדחה, אלא הותרה. יותר מזה, משמע שמה שמצוותו בכך מורה שהותרה (שלכאו' מזה מוכיח גמ' שהותרה). עיין בתוס' ביבמות (ג). ותחשב.
* כז.
** מעכבים זה את זה -
יש לדון למה יעכבו (ולא צריך להיות שווה לכל דברים אלו):
1. הטוב בא מהיות כולם, ולא מהיות מקצתם.
2. כל אחד עושה קצת טוב. אז, צריכים כולם לקיים את המצווה.
3. אחד משנה את השני, ורק על ידי שניהם, אז, בא טוב.
4. מה שלא מקיים את כל הטוב שיכול לקיים עושה שלא טוב לצאת בו.
** באה זהב -
צריך ביאור למה לא דורשים להיפך, ש"באה מקשה...." אולי ככר נאמר יותר על זהב. ותחשב.
* כח:
** גביעים מעכבים זה את זה -
רצה לומר, גביעים מעכבים את המנורה. הלשון משמע שזה עושה שאין לו שום גביעים, וזהו הפסול. ותחשב.
** אף של עץ -
עיין ברש"י, שמשמע שהוא מפני שבפועל עשו ממנו חשמונאים. לולי רש"י, הייתי אומר שאינו מפני שעשו ממנו, אלא מפני שכשר לעשות ממנו. ותחשב.
* כט.
** שלחן אש -
לפי זה, אפשר להיות ש"ששלחן הטהור" מלמד לנו שהראה לו ממקום הטהור, שכמו ששמים הראה לו מנורה, כך הראה לו השלחן. (לפי זה, אולי לא נטמא או אולי לא צריך מקור שנטמא.)
* כט:
** תילים-
הקשה לי אבי מגמ' בברכות שמשמע שה' הראה את כל התורה למשה רבינו. עיין שם, שדנינו בגדר נתינה, שאולי לא ממש למד את כולו. (גם עיין שם, שלא אומר שהראה לו את כל התורה, אלא אומר דברים פרטיים שהראה לו. אבל, עיין במגילה כעין אותו גמרא בברכות, ואולי שם משמע יותר שהראה לו כה"ת כולה.) תירצתי לו שזה היה קודם שהראה ה' למשה את התורה.
עיין בלשון רש"י - "ועדיין לא קיבלה" - שלא פשוט מה מכוון לומר. על פי הדרך שכתבנו, נראה שהיה קשה לו שרבי עקיבא יודע יותר משיידע. כיון שאמר דבר בשמו שהוא עוד לא קיבל, הבין שה' ילמד לו שאר התורה, ואז לא היה דואג עוד. ותחשב.
* ל.
** בדמע -
רצה לומר, היה בוכה כשכתב אותו, ואז לא דיבר אותו כשכתב אותו. אבל, הכתיבה עצמה היתה בדיו, ולא בדמע.
** כאילו כתב -
יש לדון אם הוא גם כן כאילו קבל אותו, או שאולי זה רק אם כתב אותו ממש, ולא רק אם הוא כאילו כתב אותו.
** למשפחות'-
יש להעיר ששלנו הם גדולים מזה. ותחשב.
* ל:
** אפכיה -
יש לדון מי היפך - אם רצה לומר שהם היפכו, והיהי קל להם לומר ההלכ' מלומר שהפכו ושפסקו או שהיו תנאים שהפכו אותו. עיין בגי' רש"י, שמוכרח כשני.
** לימא -
קשה, שאולי לא אמר כיון שכבר אמר, שכבר אמר שהלכה כמותו תמיד. (עיין בעירובין (קרוב למד) שמקשה כעין זה.)
** תולה -
איני מבין כל כך מהו שיטת רבי יהודה; צריך לעיין.
* לא.
** אין רוב -
עיין במה שפרש"י. אילו ספק דאו' היה דאו', היה אפשר לפרש שאז ספק, כשאינו רוב, הוא חיוב דאו'. אז, נמצא שפוטר חיוב דאו' בחיוב דרבנן. ותחשב.
* לב.
** האידנא -
יש להעיר שכדי להוכיח שיטת רב, לא מספיק להוכיח מה שנוהגים "האידנא," שצריכים להוכיח מה שנוהגים בימי רב, שרב יפסוק מחמת אותו המנהג. ותו"ת.
* לב:
** מגרס -
מה שהיו מגרס גריסי בהם משמע שנהגו במו שיש נוהגים עכשיו לומר פרשיות התפילין בתפילת שחרית, שאז ממילא יהיו מגרס גריסי באותם פרשיות.
* לד:	
** לטפטפת-
קשה איך רואה מכאן ארבע, שרק כתיב, "טוטפות" שלש פעמים. אפשר שדורש לשון רבים, אבל קשה שאז יהיו שש. נראה שלא דורשים לשון רבים, כיון שהוא חסר, אבל כל אחד שצריך לגופו מלמד שנים, שהרי הוא לשון רבים (אף אם כתוב בלשון יחיד). אז, דורשים שצריכים ארבע. ותחשב.
** מתוך -
רש"י מפרש למה יש יותר קדושה בשל ראש מבשל יד. יש לדון אם רש"י אומר סימן או סיבה. (רש"י אומר שני דברים; בכל אחד, יש לדון אם הוא סימן או סיבה. לא צריכים להיות שווים.) ותחשב.
** מורידים -
מעניין שאומרים כן, שהרי כשמשתמשים בו ליד, כבר שינה אותו, ונתן עליו עור, כמו שמפרש גמרא.
* לה.
** אמגוזא -
לא הבנתי כל כך מה גמרא אומר. נראה שרצה לומר שאולי אין הפסול מפני שאינו מרובע, אלא מפני שארכו יתר על רחבו. אבל, מה שאין לו קרנים אולי לא פוסל. אבל, רש"י לא משמע כן.  ותחשב.
** פני טבלא -
איני מבין מה אומר.
** כנגד -
וא"ת הרי בשלש בוודאי יש זה כנגד זה. אם כן, קשה למה אומר שבשלש פסול, שבכה"ג, גם שלש פסול. אפשר לומר שאיה"נ, ושלש רצה לומר שנים כשהם זה כנגד זה, ונקט שלש, מפני שבזה בוודאי יש זה כנגד זה. גם יש לומר שכשיש שלש, צריך לתקן כל השלש קודם שיתכשר. גם יש לומר שכשיש שלש, פסול אף בעתיקי, ולא רק בחדתי. ותחשב.
* לה:
** פוק חזי -
מעניין שאומר לשון זה, שהרי, כל ענין תקנה זו הוא שלא נראה כל כך. אז, קצת מוזר לומר לראות אם בני אדם עושים אותו. ותחשב.
* לו.
** לא סח -
ידוע שיש מחלקת ראשונים בזה. יש שפירשו שרצה לומר שאם סח מברך שנים בין הכל - אחד על של יד ואחד על של ראש, ויש שפירשו שאם סח, מברך שנים על של ראש שנים. לשון הגמרא נראה שמשמע כצד שני, שלראשון היה לו לומר - הא בדסח. נראה שהצד לדחות הוא שאביי ורבא לא אמרו תירוץ לקושיה זו, אלא אמרו הדין, והגמ' מתרץ על פי הדין שאמרו. אבל, עדיין יש לדון, שהיה לו לומר, "כדאמרי רבא ואביי...." ותחשב.
* לו:
** קל וחומר -
כמובן, אין זה קל וחומר ממש, שקל לדחות מה לציץ שרק כהן יכול להניח אותו, מה שאין כן בתפילין. ויש לדון, שאולי יש לומר שההגדרה הוא שרק יכול ללבוש אותם אם עושה בהם עבודתם או שראוי לעשות בהם עבודתם. גם תפילין כן, שרק אם ראוי לעשות בהם עבודתם, דהיינו שיקיים את הטוב של לבישתם, מותר להניח אותם. ותחשב.
* לז.
** החורם -
עיין ברש"י. מעניין שכינו לו שם מחמת מומו.
** רב אשי-
קצת קשה מהיכי תיתי לרב אשי שיש בזה מחלקת (רצה לומר, מהיכי תיתי לו לחדש שרבי יוסי דורש דרשה אחרת). נראה שמדייק ממה שמביא מיד אחריו תנא הדורש, שמשמע שרק התנא, ולא הוא, דורש. יש לדון, שהיה נראה לומר שמביא אותו מפני שלרבי יוסי מוכרח שצריך עוד מקור, ולא מצאנו שאמר, ואז מביא שיטה שצ"ל שסובר כמותו.
** שולט בשני ידיו -
יש לדון אם ההו"א הוא שילבש בכל יד שרוצה או שלא ילבש, שאין לו יד שמאל. לשני, אולי המס' הוא שכל ידיו כשרים (ומזכיר אחד מן הכשרים). ותחשב.
** תרי רישי -
נמצא שכיון שהיו בב"א, פשוט ששניהם קדושים, ופשוט שיכול להיות שני בכורים. עיין בבכורות, שחשבתי שהגמ' משמע נגד זה, שיש דרשה ששניהם קדושים, לפי רבי יוסי הגלילי, ומזה דורש שאפשר לצמצם (ואגב, קשה שאולי זה בשני ראשים, ואולי לא מצוי, ולא יכ' בו תורה דרשה). אבל, גמ' אומר שאולי אין דרשה זו נוהגת בחמור. בוודאי עדיין יכול לצמצם, שזה מציאות (ועוד שמצאנו שזה נוגע בכה"ת כולה), ואז צריך לומר שמה שמשנה הוא מה ששניהם קדושים. אז, יש לדון מהי"ת שבאדם שניהם יהיו קדושים לרבנן, שלא דורשים מקרא של רבי יוסי הגלילי. ותחשב. צריך לע"ש.
* לז:
** יד -
יש לדון למה לא דורשים מדין גידם, שממה שיכול ללבוש תפילין, צריך לומר שאין היד ממש. ותחשב.
** בעלת ה-
עיין ברש"י. ק"ק למה מניח שהמחלקת הוא אם לא חייב או צריך חמש, שהיה יכול לומר שחולקים אם צריך ארבע או צריך חמש. ותחשב.
* לח:
** אלימי -
גמרא מסיק שאלימי לא צריך להיות ראויים לעניבה, אלא רק צריכים להיות ראויים לעניבה אילו היו קטנים. יש לדון מהו השיעור של קטנים - מתי לא אומרים שאילו היה יותר קטן היה ראוי לעניבה. נראה שאין שיעור, ושיעור עניבה רק תלוי במהו יכולת של בני אדם (שאף בחוט קטן מאד, יש שיעור שבו לא יכולים בני אדם לענב. ותחשב.
** מידי צבעא -
פשטות ביאור הגמרא הוא שכהוא צבוע תכלת, עדיין מה שיש בו מצוות לבן הוא הקודם, שמצוות לבן תמיד קודם. מה שהוא אותו צבע של הבגד אינו מה שגורם שיקדים, אלא מה שמקיים בו מצוות לבן גורם בו שיקדים. אבל, עיין ברש"י, שמשמע שלבן רצה לומר לבן ממש, וכיון שהוא סתםמ צבע של בגד, והוא הצבע של רוב, הוא הקודם. צריך לעיין בזה.
* לט.
** קשר עליון -
וא"ת פשוט שצריך קשר זה, שצריך גדיל, ובלי קשר זה, אין מה שמקיים גדיל. עיין ברש"י, שמתרץ שיכול להיות שלפעמים נשאר יום או יומיים בלי קשר. (נמצא מרש"י שאף שעומד ליבטל, כיון שלא בטל כבר, כשר הוא.) כמו כן, היה אפשר לומר שאולי נתן בו קלי"פ או כדומה. יש להעיר שבזה היה אפשר לדחות ראיית הגמרא לעיל שצריך יותר מקשר עליון.
** לא יפחות -
עיין ברש"י שבאר למה יהיה שם רמז לשבעה רקיעים. יש לדון מה הדין אם אין לו תכלת, כמו בימינו, אם אולי אין עוד ענין של רקיעות, או שנאמר שכך הוקבע מצוות ציצית, או שנאמר שאף שאין לנו תכלת, יש לנו זכר תכלת, וכשמביטים בציצית, צריך לזכור את התכלת שהיה שם.
** לא יפחות -
עיין ברש"י. אני מבין למה ישים בה שבעה, שהוא כנגד רקיעות, ומבין למה ישים בה שלש עשר, שהוא כנגד רקיעות ואוירים. אבל, לכאו', קשה למה יכול לשים כל מנין שביניהם, שאינו כנגד שום דבר, ולמה הוא גרוע מארבע עשרה או מששה. (ששה אולי גרוע כיון שהוא לא כולל רקיעות. אבל, קשה למה הוא גרוע מארבע עשר. ותחשב.)
** מעלים בקודש -
זה מעניין, שכבר ירד בקדושה, שהתחיל בתכלת. מעניין שיש ענין להעלות עוד בקדושה כדי שלא נרד בקדושה מתחילה לסוף. ותחשב.[fn:3]
* בית שמאי פוטרים -
עיין ברש"י. צריך ביאור למה מניח שבית שמאי סובר שחיוב מנא הוא.[fn:4]
* מא.
** כל שכן קמאי -
כ"כ רש"י. זה מעניין, שהיה נראה לומר שהענין הוא שמבטל לקמאי. אז,  אולי רק בתראי כשרים, ולא קמאי.
* מב.
** על הקרן -
איני מבין כל כך מה זה אומר, ומה נחשב נתינה על הקרן. אולי רצה לומר שאם הנקב שווה לצד מטה ולצד הצד, אז הוא פסול, אלא צריך להיות משוך לאחד מן הצדדים. ותחשב.
** דסתר -
עיין ברש"י, שנותן שני פירושים איך נתמעט משלש. יש להעיר שהיה אפשר לחלק ביניהם, לומר שרק אם נסתר הבגד כשר, שהנקב והציצית נשארו בהמקום שלהם, וכיון שאותו מקום היה כשר, נשאר בכשרותו, אבל אם נסתבר הנקב, אולי לא כשר, שאותו מקום גם מתחילה לא היה כשר. 
* מב:
** ספר תורה -
צריך ביאור למה לא מברכים על ספר תורה, כיון שבגמר כתיבתו מקיימים מצות "ועתה כתבו לכם," לכתוב ספר תורה. ותחשב. (אם נחלק לומר ששם מסברה יודעים שעיקר המצווה הוא כדי שיהיה לו ספר תורה או שירבו ספרי תורה בעולם, ואינו מפני מעשה הכתיבה, צריך לומר שלא נאמר כן במילה, ועיקר המצווה הוא המעשה, ולא התוצאה.)
** חובת הגברא -
צריך לעיין מהו המצווה, שהפסוק משמע שהמצווה הוא לשים ציצית. אם כן, אם הוא חובת גברא, הייתי אומר שרצה לומר שכל זמן שאדם לובש בגד של ארבע קרנות, צריך לשים עליו ציצית, אם אינו כבר שם. אז, מעניין שיש קיום מצווה, ולא רק שאין ביטול, כשכבר יש בו ציצית. צריך לומר שהמצווה היא שיהיו עליו ציצית, דהיי' שה' ציווה עליו לשמור שיהיו עליו ציצית בבגד כזה. ותחשב, שהוא לא שומר, אלא כבר היו שם. צריך ביאור.
* מג.
** זה על זה נאמרו -
מעניין שגמרא אומר שכיון ששני הבדיקות נאמרו זה על זה, מניחים שיכולים להקל. קשה, שהוא רק הוכיח שזה נאמר על זה, אבל אולי נאמר זה על זה להחמיר, לומר שרק אם הצליח בשני הבדיקות היא כשרה. נראה שכיון שכל אחד אמר רק אחד, מוכח שכל אחד מהני בפני עצמו, שאם לא כן, לא יאמר דבר שיטעה בני אדם לחשוב שיכולים לסמוך על בדיקה אחת. ותחשב.
** משום זונה -
מעניין שחוששים לרעת זונה, כיון שהיא כבר זונה היא, ולא מקפדת על איסור זנות.
** משום זונה -
מעניין שחוששים רק משום זונה, ולא חוששים שאשה ישא אותו.
** משום זונה -
קשה, שהוא בא עליה, ותכיר שהוא ערל. אולי כיון שמסכימה, נבעלת לו, אף כשמכרת שהוא גוי.
** כהנים -
וא"ת רק כה"ג לובש כלאים. ויש לומרש סובר שאבנטו של כ"ה שווה לשל כה"ג בכל ימות השנה. גי"ל ש"כהנים" כאן ר"ל כהן גדול. גי"ל שכל כהן ראוי להיות כהן גדול.
** כסות יום -
צריך ביאור למה לא בירך כשלבש כסות לילה במקום כסות יום.
* מג:
** תכסה בה -
יש לדון למה לא אומר שמשמע ה', כיון שאומר "בה," שיכול להיות "בה'."
** בור -
קשה איך מברך לה' על זה, שהכל בידי שמים חוץ מיראת שמים. אולי בור לא בר רק ממה שאין לו  יראת שמים, אלא גם ממה שהוא טיפש. ותחשב.
ודע שק"ק למה לא מברכים שלא עשאני שוטה וכדומה.
* מד.
** חלזון זה -
נראה שיש שני דרכים לקרוא את זה:
- "חלזון זה - גופו דומה לים...." לפי זה, נמצא שיש כמה מיני חלזון, ומפרשים מין חלזון הראוי לתכלת.
- "חלזון - זה גופו...." לפי זה, לא רק אומרים קרק' של חלזון, אלא אומרים מהו החלזון. לפי זה, צריך לומר שסימנים אלו הם סימנים מובהקים, שמפרשים לנו מהו החלזון. ותו"ת.
** שלושים יום -
יש שני דרכים לפרש את זה:
- רק חייב אחרי שלושים יום, אף אם שוכר אותו ליותר זמן.
- רק חייב אם שוכר אותו לשלושים יום. אבל, אז חייב מיד.
** ציצית קל -
רש"י מפרש שהוא קל כיון שהוא מצות עשה. משמע שקיום מצוות עשה קל מקיום מצוות לאו, ולא רק שעונש לאו חמור מעונש עשה. (דין עשה דוחה לאו לא משמע כן, אבל דע שאוין אותו כלל קל להבין, על פי מה שאומר גמרא ביבמות שלאו יותר חמור ממנו.) לולי רש"י, הומ"ל שהוא קל כיון שלא טורח בו כלל, שהוא שווה כמה פרוטות.
** הוציאה -
רש"י כ' שהיה נס. אולי היה נס שהלכו וטפחו אותו או היה נס שזה החזיר אותו לתשובה. נראה ג"כ שאולי נס כאן לא רצה לומר כמו נס של קריעת ים סוף, אלא רצה לומר נס כמו סימן, והוא שהכירה שזה סימן ליראת ה'.
* מד:
** אכילה -
יש לדון מהו הענין:
- טוב לסמוך אכילה לאכילה.
- טוב שלא לשנות ממה שעושה.
תחשב אם אלו שווים או לא.
* מח.
** ממילא -
נמצא שאין איסור בהבאת חולין לעזרה כזה (לעשות שקדשים שבעזרה נעשים חולין). (חושב אני שיש גמרא בזבחים שסותר את זה. נראה שאולי תלוי באם איסור הבאת חולין לעזרה הוא מדאו' או מדרבנן. גם יש להעיר שזה רק בהו"א. ותחשב.[fn:5])
** רבי -
יש להעיר שרק לפי אביי יכול לפדות.
** שנים מארבע -
איני מבין למה צריך פדיון, שרק הקדיש שנים מהם. ותחשב.
* נב.
** רבי שמעון ־
צריך ביאור למה גמרא רק דן בסתירה בשיטת רבי שמעון, ולא בסתירה בשיטת רבי שמעון.
** דאי ־
מעניין שקוראים לזה "דאי," אף שאין בו איסור, אלא שצריך דבר לקרות כדי שהדין יהיה נוגע.
** האי נמי ־
יש להעיר שהם צחקו על הראיה, והוא אומר עכשיו שהדין, ולא הראיה, צודק.
** לוגים ־
נראה שמחלקת ר"י ורבנן תלוי באם נחשבים שני החלקים כקרבן אחד או כשני קרבנות. ותו"ת.
* נב:
** דאי הוה ־
יש להעיר שהוא מין אחר של דאי, שהוא רק דין בדיעבד. במילים אחרים, הדין הוא מה שקורה בציור של קומץ. כאן, אומר ציור של קומץ שקורה רק אחר שקרה דאי. ותו"ת.
* נג.
** חובה ־
לכאו', עדיין היה אפשר לומר שנקרא חובה רק במה שהוא לאו. נראה שרצה לומר שיש לנו לאו אחר לו, ויודעים בקדשים שמצרפים שני לאווים לעשות עיכוב.
* נג:
** עב ־
איני מבין איך יכול להית שבהוספת מעט מים, נעשה שהוא יותר קטן מאילו לא הוסיף בה מים. צריך לומר שהמים מביא את הקמח יותר קרוב זה לזה. ותחשב.
* נד:
** מרבה במעשרות ־
צריך לומר שחזר ממה שסבר שחולקים בדיחוי באיסורים, שאם לא כן, אין ראיה זו נוגעת.
* נו.
** שהוא קדשי קדשים ־
משמע שקדשי קדשים הוא דין בפני עצמו, ואינו רק דבר שכולל דיני קדשי קדשים, שהרי כאן דן בדין אחד של קדשי קדשים (מקום שחיטתו). ויש לדון, שיש לומר בקל שכולל כל שאר הדינים כאן. ותו"ת.
* נו:
** מום בבעל מום ־
יש לדון אם אינו חייב כיון שלא גורם פסול או כיון שלא הטיל מום בדבר שכל כך קדוש. ותחשב.
* נז:
** אמרו דבר אחד ־
מגמרא זה יוצא שכשאומר ששני תנאים אמרו דבר אחד, רצה לומר שהם ממש אמרו דבר אחד, ולא שאמרו דבר דומה. ויש לדון, שאולי יש לחלק בין כששני תנאים אמרו דבר, אלא שאחד מוסיף על החידוש, לכאן, שאחד מחדש דבר שאינו הולך עם אותו חידוש, אלא הוא דין אחר. ותו"ת. גם יש לדחות שרק כאן כשכבר כלל ב"אמרו דבר אחד" תנאים שממש אומרים דבר אחד, לא יאמר עמו עוד "אמרו דבר אחד" שבו לא ממש אומרים דבר אחד (ונקט לומר את האחד שבו אומרים דבר אחד ממש).


* Footnotes
[fn:5] יש להעיר שמדברי רש"י מבואר שכל זה הו"א, ושלמס' זה בוודאי נגד רבי. היה אפשר לומר שרק בריי' אחרונה נגד רבי. וא"ת הרי מבריי' אחרונה, שרק מתיר בחוץ, רואים שאסור בפנים, ואין מקור שרבי יחלוק על זה. ויש לומר שרק אומר שיעשה בחוץ כיון שיכול. אבל, אם לא יכול, אולי יהיה מותר בפנים. 
[fn:4] אפשר לטעון שיש יחס בין מחלקת אם דוחה תכלת את איסור כלאים ואם חיוב מנא הוא או חיוב גברא. אולי פשוט שכלאים הוא חיוב גברא. (כן נראה, שאין מי שאוסר שיהיה לו בגד של כלאים.) אז, אולי לא מסתבר שחיוב מנא של ציצית ידחה את חיוב גברא של כלאים. (יש לומר את זה בשני דרכים. דרך ראשון הוא שכיון שטוב שלהם שונה, לא אפשר שטוב של זה ידחה את טוב של זה. יכולים לומר צד זה רק על הצד שהוא הותרה קצת. ותחשב. יותר נראה לומר כצד שני, שהוא שאז אפשר לקיים שניהם, שמקיים אותו במצווה כשלא לובש את המנא.) אבל, כל זה צריך ביאור, שהרי לקמן בגמ' מצאנו סוברים שציצית חיוב מנא. אם כן, צריכים לומר שסוברים שאין עשה של ציצית דוחה לאו של כלאים, וזה לא נראה, שזה רק שיטת בית שמאי, וגמ' בכ"מ מניח נגד זה. אז, צריך ביאור. ותחשב. 
[fn:3] אפשר לבאר שאין התכלת ירידה, שהתכלת הוא נצרך. אז, ייחשב ירידה רק אם יעשה אותו בלי צורך, והוא שימשך בו. אבל, קשה, שאז היה יכול ג"כ לאחר התכלת עד הסוף, ומגמרא משמע שלא יכול לעשות כן. ותו"ת. 
[fn:2] וגם, אין כל הענין כל כך מובן לי. לכאו', זה תלוי במה תולים אותו - אם הענין הוא שתולים אותו בדעת כהן ומסופקים מהו, או שתולים אותו בדעת כהן ואומר שכהן חושב סתם לאיזה שיהיה. לראשון, לכאו' נשאל לכהן. אולי כהן לא נמצא. אבל, לא משמע כן מרש"י. ותחשב. אם נאמר כשני, לכאו', אינו כברירה, שאין שום דבר שייתלה בו, שכהן חושב סתם, והוא שחושב שיהיה רק אחד, ולא מפרש איזה אחד. מחודש שחל על אף אחד שם. ותחשב.
[fn:1] יש לדון בזה, שהרי רק אחרי שנפל, ולא כשנופל, ממש נשען עליו, שכשהוא עדיין נופל, הוא נופל, ואין גופו נשען על שום דבר. אז, מחודש שייחשב משכב אז. ותחשב.
