* פרק חמש עשרה נשים
* ב.
** דנים
למה צרת ערוה פטורה מייבום:
א.יחס לערוה אוסרתה. זה רק במקום מצוה:
א.תורה מחדש (ותח’ למה) שהיחס שאוסרה אינו רק מה שהיא היתה נשואה לאיש עם ערוה, אלא מה שהיתה נשואה לאח עם ערוה.
ב. אז, יחס יותר חזק, שעושה יותר דינים (יחס ייבום עושה שחד אשה פוטרת חברתה. אף שאין זה שייך כאן, מה שהוא בדרך כלל שייך מחשיב את היחס.).
ג. אולי מצטרפת איסור צרת ערוה עם איסור אשת אח, ונאסרת. זה מניח- ויש לדון- שייבום לא מתיר אלא דוחה איסור אשת אח (יש להזכיר מה שאז קשה למה חייבי עשה  יש להם ייבום).
ב. אין לה ייבום. כיון שכן, אשת אח היא. יש לדון למה אין ייבום:
א. אולי יש ייבום רק בבית שיכול ליבם לכל מי שרוצה.
ב. אולי יש ייבום רק אי אין לחד מהם איסור ערוה.
ג. אולי יחסה למי שאין לה ייבום עושה שאין לה ייבום.
וכל אלו לא מבוארים.
* ג.
** עיקר איסור -
לכאו’, מזה מוכרח שייבום בערוה נדחה, ולא רק “הותר,” דא”כ, אין איסורה שייך. וי”ל שלא דן בסיבה לדין, אלא במקורו, שנלמד על מה דכ’ בפרשת עריות.
** אבל מחלץ -
ק’, שכל שעולה לייבום . . . . אולי לא ידע כן גמ’ אכתי (שרק לקמן מחדשו).
* ג:
** חמורות -
זה לשון קצת מוזר, שמה של יכול לישא אח אינו מחמת שחמורין הן, אלא שבמציאות לעולם יהיו עריות אף לאח. ואלי רק ר”ל שיש לו חומרא זו בדין.
** ותו -
בדרך כלל, אומר לשון זה כשמקשה עוד קושיא. כאן, לכאו’ אי אפשר לומר שכוונתו הוא שאין מקור לו, ואז אינו נכון, שכנר הניח בק’ ראישונה שהוא נכון ושיש מקור לו, דאי לאו הכי, רק ק’ אחת היא, שאין לחל’ בין לאווין. ויל”ד. ותח’.
* ה.
** ישנו בשאלה -
הקשה לי א.ד.ר ששאלה עוקר, ואז, לא חל. אז, כל נדר עומד לעולם, אלא שיש שחשבנו שהוא נדר שאינם נדרים. ראשון, יש להעיר שהיה יכול לומר שיש בו הפרה (ויש לדון אם זה יהא פירכה אף באנשים.), לצד שאינו עוקרו. גם יש לומר שאין פירכא זו סיבה אלא סימן, והוא שנה שיכול חכם לעקרו הוא אולי רק מפני שום חלישות שכבר יש לו. ותח’.
* ה:
** גדיל -
לא הבנתי את זה, שאולי עושים שני גדילים על ידי ארבע חוטים. ותחשב.
* ו.
** לכדתניא -
וא”ת מה לתנא הדורשו. וי”ל שחולק על בריי’ ראישונה (יל”ד מה דורש מאותו קרא ולמה לא דן גמ’ בזה), ואז יש לו רק חד מקור.
* ו:
** לעולם -
וא”ת נדרש להיפך. וי”ל שלחומרא מקישין.
* ז.
** קבורת מת מצוה -
גמרא זה מעניין, שממה שהניח לפני כן שאינו דוחה משמע שהיה שום מקור. אם כן, צריך ביאור מה מקשה כאן. ואולי דן גמרא אי מקור הוא טוב. אם כן, גמרא לא מזכיר עיקר הדיון.
* ז:
** ואי לא -
נראה שאין זה חלק מן הקושיה, שלכאורה לא שייך לו. ותחשב.
* ח.
** הוקשו -
יש להעיר שאף שלא פורכים על היקשים, צריך לדון מתי נחשב דין אחר, שלכאורה כאן היה אפשר לומר שאינו אותו דין, שכאן הותר בלי איסור אחר וכאן יותר בשני איסורים. ותחשב.
* ט.
** טז -
ק"ק למה לא חשב שרבי סתמו כן כיון שסבר כר"י. יש לומר שסבר שכיון שיחיד הוא, לא יסבור כן. גם יש לומר על פי רא"ש (הוריות יב:. ועיין שם.)
* י.
** והכי קאמר ליה -
אז, צריך להיות שסבר שנאמר בכל שאר שבמשנה.
** דמתניתין -
אולי הוה מצי לדחות שבכל אחד מנה מה שיעשה הכי גדול במנינו.
* י:
** וקדשה -
צריך ביאור למה צריך זה.
** וחזר -
לשון "וחזר" מוזר. משמע שחליצה עושה דבר הדומה לקידושין.
** צריך ביאור
למה מניח גמרא שעשה כאן דוחהו מכרת ולא מוסיף עשה. ואולי רק מוסיפים עשה כשיש צורך, כמו לדחות עשה. כאן, כבר יש כרת, ואז דוחה עשה.
* יא:
** אין מקרא -
יש לדון למה לא:
1. אולי יש כלל שתורה נקרא ונדרש על פי דרך הפשוט ועל פי דרך הנדרש.
2. אולי דורש ממה שנכתב שם (כמו גמרא לעיל גבי "מוכח").
מחזיר- הו"מ לומר שהוא סוטה או כעין זה.
** דלא אלים -
נראה שיש שכוונתו כן:
יש פירכא לקל וחומר, והוא שלאסור לה יש מצוה. דוחה גמרא שאכתי יש ללמוד מן הקל וחומר, שיש רק סיבה להתיר, אבל עדיין רואים מן הקל וחומר שיש איסור. אז,דן אם דוחה אותו איסור הנלמד מקל וחומר את המצוה.
* יב:
** שכבר ילדו -
הו"מ לומר שרצה לומר "שכבר ילדו, והרי הם חיים.”
* יג.
** נשואים הראישונים -
נראה לי שני צדדים בזה:
1. יש לדון איזה יחס של אשה לאיש גורם ייבום:
2. יחסם בשעת מיתה.
3. יחסם בכל זמן (בצירוף יחס שבשעת מיתה, שהרי אם מגרשה, אין ייבום. ויש לדון.)
אולי צד זה הוא צד שני, והענין הוא שאז האיסור הוא חלק מיחס של ייבום, ואז הוא יותר חשוב, ואז נאסר.
1. אולי ייבום הוא כעין זכות שמקבל בעת נשואים. כיון שאז לא קבלה, בטל. ותו"ת.
* טז:
** אין זקנה -
נראה שהוא מפני שהיה ה’ חי לעולם. זקנה הוא החילוק בין גיל שהיה לגיל שהוא. כיון שבה’ לעולם גילו ∞, ואז לא מעשה זקן.
* יז:
** בנשואין -
יש להעיר שאפשר שהיתה נשואה יותר משני פעמים ואפשר שצרתה היתה נשואה שני פעמים. גם אפשר שכבר נפלה צרה (ע’ בלשון רש"י, שמשמע שבא ליישב לזה. וצ"ב מה אומר. ונ’ שר”ל שדנים באלו השייכים לציור זה.)
** בנשואים -
יש לדון למה לא אומר שהיא שניה בנפילה, שנפלה שני פעמים. ותו"ת.
** מלוט -
ואם תאמר הרי גמרא לעיל (ח.) מיעט מתי מיבמים באומר שדורשים לחומרא. ונראה שכאן שלא יהיה איסור, כיון שהיה לוט בן אחיו, לא היינו ממעטים. ויש לדון, שהיה אברהם אחי אביו, וזה מוסיף עוד איסור. ותחשב. משמע שאין אומרים כלל זה בג"ש; ודנים בזה. ואולי רק היה לו תירוץ אחר. וקשה, שלמסקנא, צריך קרא לזה. ותחשב.
** מעריות -
לכאו’, הו"מ לומר כגמ’ לעיל שדורשים לחומרה. ודע שדנים אם זה אף בגזרה שוה.
** חידוש -
צריך ביאור, שק’ גמ’ לכאו’ לא היה רק שלא נצרך אלא שלא מוסיף.
* יח.
** הכי קאמר -
יש לציין לגמ’ שבת (קלח.).
** הא מני -
היה אפשר לומר שהוא רבן גמליאל, ואז לא היה צריך לדון אם יכול לסבור שאין זיקה.
** אדמייבם חד -
לא הבנתי זה כל כך, שהניחא לא ייבם אחד ראשון, שהרי צריך מי שיחלוץ לשני, ואולי ימות אחיו. אבל, עדיין קשה למה לא ייבם שני, שראשון כבר חלוץ. ותחשב.
* יח:
** אחיו… אחותה -
יכול לשמש באותו לשון (שנותן pronoun על אח של יבם זה ועל אחות של ש"י זה) כיון שמיירי על שומרת יבם (ואז יכול ליתן לה pronoun), ושומרת יבם רצה לומר מי ששומרת ליבם, ואז דיבר על יבם, ונותן לו pronoun. ותו"ת. וזה פשוט.
** בבא דרישא למאן -
ואם תאמר אולי תני לה לר"ש, כדי שלא יחלוק עליו, ונראה שהוא מודה. ויש לומר שאם כן, היה לו לשתוק, שלא היינו חושבים שחולק בו אם לא היה משנה להודיע כן.
* יט.
** ולא שני -
אם כן, יש עוד אפשרות למצוא אח שלא היה בעולם.
** מתיב רב אושעיא -
לכאורה, צריך להיות רב אושיעא שני, שרב אושעיא אחר אמר מימרא זה. צריך להיות שיש שני ר"א. ושו"ר בתוס’ כאן (ובגירסתו). ותו"ת.
* כ.
** שדי היתירא -
קצת צריך ביאור למה איסור אשת אח נחשב היתר. ונראה אולי שיכול להיות שכשהיא מתייבמת, אין סיבה לאיסור ייבום, והוא שאינה צריכה חליצה אז, שיש קיום השם, מה שאין כן באשת אח שלא היה בעולמו, שאף כשהיא נשואה, ואף שיש עוד איסור, יש עדיין סיבה לאיסור אשת אח הראשון. ותו"ת.
** קדש עצמך -
צריך לבאר מה שינה. ואולי משתמש במילת קדוש לומר מופרש. לא נראה כן, שאז עדיין היה לו לומר שנקרא קדוש, אלא במשמעות אחר. ואולי קדוש- כלומר טוב- הוא שם שניתן לאדם, אבל קדוש- כלומר הופרש- אינו שם הניתן לאדם, בדרך כלל. ותחשב על זה.
גם יש לומר שיכול להיות שמקדש את עצמו, כיון שעושה את עצמו יותר קדוש, אבל לא שאז נקרא קדוש, שבלי זה היה רשע. ותו"ת.
* כ:
** כל התורה כולה -
יש לדון מהו הקושיה:
1. אם כן, לא יהא שום עשה דוחה לאו, והרי יודעים מקרא ומשנה שדוחה. כן משמע לשון גמרא.
2. אם כן, עשה יש לו עוד עשה, וידחה, ולא נתרווח גמרא כלל. עיין בתוס’ שכ’ שאין זה נכון בדין. ותחשב למה.
** עשה ולא תעשה -
עדיין צריך לבאר למה לא יעשו ייבום לכתחילה במשנה שהביא לקושייה לעיל,ששם אם בעלו קנו. ותו"ת.
** אלא מעתה -
יש לדון בקושיות אלו, שיש מהם שהם דברים שהתיר תורה בפירוש (ואומרים אחרונים שלא אסרו רבנן דבר המפורש להיתר בתורה). ואולי תורה לא התיר אותם אלא ברמז, שאמר לעשות אותו, וממילא שהוא מותר. ודחוק.
** כל מקום -
העיר א.ד.ר. שזה לכאורה מוכיח שמש"א ר"ל הוא חיוב, ולא רק שכן טוב לעשות. כן נראה ע"פ סברה.
* כא.
** סימן -
נ’ שהוא שמוסיף ציור על ידי הוספת דור.[fn:1]
** קשה עונשן -
צריך ביאור למה זה בכלל עונש, שהוא רק אפשרות בתשובה. ואולי רצה לומר שהוא יותר קשה כיון שיותר יבוא. גם יש לומר שבעריות, יתן לו ה’ זמן, שאולי ישוב. ויש לדון למה יותר רע אם קורה מיד. על כל פנים, במיתה מובן למה הוא יותר רע (ויש לדון אם עונש של מדות הוא דבר כזה שהוא הולך ונענש, ואז הוא רע להתחיל יותר קדים).
** משל -
נראה שהענין הוא שאין אדם יכול לשמור מקום אלא אם כן עומד חוצה לו. אם עומד שם, מסתמא ימצא שאף שומר על קצת מן האדמה שחוצה לו. נמצא שצריך לשמור מה שאינו צריך להישמר כדי לשמור מה שצריך להישמר.
* כא:
** אמר פפא -
’
יש לציין לגמ’ ב,ק שבאר שם ר"פ על ידי משל עם רפב"א, כמו כאן.
** דבי אמא רבא -
לכאורה, לא רצה לומר שאז יש צורך בכל אחד, שאז אינו גזירה לגזירה (ויש לדחות שכשאמר לעיל שכולו גזירה לגזירה, רק אמר שאין זה שמדברים עליו גזירה לגזירה, שכמה דברים בגזירות אלו, אף שנראים כגזירה לגזירה, אינם כן. ודחוק.) אלא רצה לומר שאז הם בכלל אחד, ובחד גזירה שאסר את זה, אסר את זה. ותחשב.
** בחד קידושין -
קשה מה לנו בזה, שעדיין יש לגזור עליה אטו מי שיש עליה חד קידושין, כיון שהיא ערוה דאורייתא. לא נראה לומר שאומר שכיון שהוא רק מחמת קידושין אינו ערווה חמורה, שאם כן, היה לו לדמות קידושין של העריות, ולא של השניות. אולי אומר שהחילוק בין אחד לשנים יותר גדול מן החילוק בין אפס לאחד לענין מה נחשב באותו כלל אחד. לא נראה כן; באמת, היה נראה היפך. גם יש לומר- עיין לעיל שדנינו בזה- שאולי דרשה של קשות ורכות משמע שיש לשניות ס"ר, אלא שאינם קשים עד שאסרם תורה. אם כן, אולי יש לומר שאומר שכיון שהם כל כך מרוחקים, אין ס"ר. ויש לדון, שגמרא כאן שדן בגזירה לגזירה משמע שהם גזירות, ולא שיש שום רע בהם. ותחשב.
** איבעיא להו -
ואם תאמר אם כן, קשה למה משנה אמר בדווקא אשת אחיו של האם מן האב. ויש לומר שמרבה שאף זה רק שניה ולא ערוה. ותחשב.
* כב.
** לכתחילה -
כיון שהבעיה הוא שנראה שמורידים קדושתם, קשה למה אין אומרים כן אף במשפחת אב, שנראים כבני משפחה. גם קשה למה אומרים כן בעדות כלל, שאין גוי כשר לעדות. ותחשב. וצ"ל שהוא לסיבה אחרת (אולי גזירה מחמת ישראל). ויש לדון אם קושייתינו עדיין קשה.
** מבני יעקב -
או"ת היו בני אחות אשה. ואולי כיון שלא היה איסור לא היו פסולים. ותח’. לכאורה, צריך לומר כן, שאי לאו הכי, כל אחד מבני ישראל יהיה ממזר. ויש לדון, שאולי נעשו כגרים[fn:2] שנולדים בחדש במתן תורה. ויש לדון, שעדיין יש לנו זכות אבות, שנחשבים אבות אבותינו.
** מבני יעקב -
יש לדון מהו הצד ללומר שלא מקיים:
1. על ידי ייבום, לא יהא המת כל כך מיוחס לבניו, שהוא פסול, ובנים (על ידי ייבום) יהיו כשרים.
2. אין בנין פסולים כל כך טובים לקיים בהם קיום שם.
3. אין את כשר כל כך מיוחס לאחיו הפסול.
נראה שיש נפקא מינא באי יש הו"א זה אף אי שניהם פסולים.
ויש להעיר שממסקנת גמ’ (מטעמו), נ’ כאחד משנים ראשונות.
* כב:
** ונשיא -
קרא זה נאמר על איסור קללת אדם מישראל. צריך ביאור למה מניח שהוא אף באיסור זה.
** וחייב על מכתו -
הוה מצי לתרת שהוא פסול כיון שאביו ממזר, ואז לא עבר אביו כלל. אולי אם הוא ואביו פסולים, אין חידוש במה שנחשב כאביו.
** וריב"י -
לא הבנתי למה לא אומר שקרא אוסר בת אשת אחיו אף אם אינה אחותו. ויש לומר שאומר "אחותך היא.” אם צריך אותו קרא לזה, קשה איך דורשים ממנו לעיל. ותחשב.
* כג.
** לימא קסבר -
ע’ בקידושין שאומר הפיכו. ואולי רק מדייק ממה שהוא מיותר שרק מכריח שמוסיף שום דין, ולא מכריח מהא. ותו"ת.
** מאן תנא -
בקדושין מביא עוד מקורות. וצריך ביאור.
** יש דין
שלא תופס קידושין ושאין בנם מיוחסים לאב. יש לדון אם אין יחס בין דינים אלו, יש להם סיבה אחת, או חד (יש לדון איזה) סיבה לאידך. ותח’.
* כג:
** דיקא נמי -
ק"ק איך אביי ידחה את זה. שוב ראיתי בתירוץ תוס’. לא הבנתי שאם אין מזה שום בעיא לאביי, לא ייחשב דיקא. ואולי ר"ל שאינו כל כך קשה, שלא מקשה מן הלשון, אלא שלאביי הוה ליה לומר לשון יותר טוב. אולי סבר שזה אינו קושיא כל כך חזקה. דחוק.
** דיקא נמי -
לכאורה, רצה לומר שדיקא כאותו תירוץ, אבל אין זה בעיה לאביי, שאולי אמר אותו ציור אף שלא היה צריך להיות באותו ציור. ויש לדון למה לא יאמר דבר שיגלה עוד חידוש. ודע שאם הוא מדוייק נגד אביי, נמצא שמדוייק נגד הלכה, שהלכה כאביי.
** דווקא -
רצה לומר, מחדש שחוששים לספק על איסור זה, אף שהוא איסור דרבנן, כיון שאפשר לסלק את עצמו מן הספק להפך את הסדר (ואף שבזה משהה, אולי, מצווה).
* כד.
** כי איכא בכור -
נראה שהוא על דרך "כל הראוי לבילה . . . “
** מית קטן -
לא הבנתי למה אי אפשר שמת אמצעי (ולמה מניח גמרא שיש שני אחים).
** מה בכור -
לא הבנתי מהו התירוץ. ותח’. אולי ר"ל שיודעים שמה שמחשיב את הבכור לזה הוק מה שהוא הכי גדול. דחוק (בפרט בלשון.)
* כד:
** נטען -
יש לדון מהו הבעיא אם יאמרו שאמת היה הקול הראשון. אפשר שיגרם שיאמרו לשון הרע או שיוציאו שם רע. גפ אפשר שהוא אותו בעיא של מראית עין. ותח’.
** הא גיורת -
יש לדון מהו ההוכחה לזה:
א. אפשר שכיון שאמר שלא יכנס, ולא שאינה יהודי, משמע שנעשה גר. יש לדון:
א. אולי רק דן באיסור לישא אותה. ויש לדון.
ב. אולי ממה שלא נשא אותה נוכל לדייק שנתגיירה לשמה.
ב. אולי ממה שנשנה עם שאר דיני משנה, שהם רק בנשואים, נראה שרק יש נפק"מ גני היתר לישא אותה. ודחוק.
** רבי -
נראה שעדיין סומך על מה שאמר לעיל לבאר למה פירש רב כן. גם אפשר שמניחים שרבנן חולקים על רבי (יש לדון), ורוצה להוקים משנה כרבים.
** רבי -
אז, מחלקת רב ור"ש הוא תנאי. אפשר שחול’ בדעת רבנן אי רק צריך יותר ממכוער או שממש צריכים עדות.
* כה.
** רשע -
לכאו’, חלים בבת אחת. אי ענין רשע הוא שלא נאמין רשע, אז נאמין אותו כאן, שההוכחה שאדם אומר אמת הוא שלא מסתבר שאדם כשר ישקר. יש אותו הוכחה כאן. (ודחוק לומר שמה שהוא רשע הוא סיבה להניח שמשקר, ולא רק סילוק סיבה לומר שאומר אמת.) אם הענין הוא שאי אפשר לפסוק על פי רשע, אז פשוט שכאן יש בעיא, שאם נפסוק כן, לא יהא לשום טעם חוץ ממה שכן אמר רשע זה.
ולא היא- יש לדון אם זה אותו חילוק שאמר לעיל (“הכא בעל התם בועל"). אם אינו, יש לדון מהו אותו חילוק שאמר לעיל. ותחשב.
* כה:
** ליסטים -
משמע שלשון יחיד של ליסטים הוא ליסטים. (ע’ ברש"י שבת כ. יעיין בשי"ח ש"י שם.) ואולי רצה לומר ליסטֵים. ויש לדון אם היינו אומרים, אז, יו"ד. ותחשב.
* כו:
** צריך לחזר -
נמצא שאיסור של אחות חלוצתו הוא רק אם יש זיקה.
* כז:
** ומודה ר"ג -
קצת צריך לבאר את זה, שלא הבנתי למה מניח גמרא שאם אחד קטן מחבירו, לא יחול חבירו. משמע שאחד מבטל חבירו. אם כן, אם שווים הם, אחד יבטל חבירו, ולא יחול שום אחד מהם. ותחשב.
* כח.
** גזירה שמא ימות -
קשה למה לא אומר אף צד שיש זיקה. ויש לומר שזה יהיה בעיה בציור של רבי יוחנן עצמו. רק בזה אין לגזור בציור של ר"י. ותו"ת.
* כח:
** הא תו ל"ל -
קשה למה לא אומר כצריכותא שאומר גמרא מיד לעיל.
** ואשה -
יש לדון אם אז מוכרח שסבר שיש זיקה. יש לדון, שאולי אף אי יש זיקה, לא יעשה שאר דינים שאומר גמרא בזיקה. גם יש לומר שאין זה מפני שיש זיקה, אלא מסיבה אחרת (למשל, אי אפשר לחייב לייבום, שעל איזה יחייב). ותחשב.
* כט:
** יעשה מאמר -
לכאורה, זה מהני רק אם הבעיה הוא זיקה, אבל אם הבעיה הוא ביטול מצוות יבמים, אף בזה מבטל. ותחשב.
* ל.
** עיקר -
יש לדון מה לנו בזה. ואולי יש לומר שצריך שהבית אינו של ייבום (שחלק של בית אסור בייבום), ואז עיקר הבית חשוב. לא בארתי צד זה, וצריך לחשוב עליה.
* לא.
חליצה נמי- צריך ביאור ל"ל אומרים שמאמר אינו דאו’.
* לב.
** מיתלא תלי -
מעניין שלא פקע איסור אשת אח כיון שלא היה עושה היתר לייבוום, אף שעכשיו אין דבר שהיה מונע אותו חל כבר. ואין זה קשה, אלא מעניין.
** נראה שאולי
ענין אין איסור חל על איסור הוא שאם כבר היא אסורה, אין לה שם של איסור שני כיון שלא חשוב, שלא משנה כלום. אם משנה דבר, אז, הוא חשוב. גם יש לומר שאף אם לא חשוב, שלא משנה כלום לענין אותו איסור שבו אנו דנים, מגו שנאסר בענין זה, גם נאסר כאן, אף שאין בו שם.
מה שיש לו עדיין שם של איסור ראשון הוא אולי מפני ששם זה כבר היה חל, ואז בני אדם עדיין חושבים עליו. גם אפשר שהוא מפני שבני אדם מדרהרים את זה לסיבה לדינים, כיון שהוא קודם. גם אפשר שאין שום אחד שם די, אלא שכיון שכבר חל האיסור מחמת זה, אין צריכים שם.
* לב:
** לקברו -
נמצא שאף שאין איסור חל על איסור, זה רק לענין עונשים. ותו"ת. ודע שאפשר שזה רק לר"י, ולא לר"ש (וגמרא לקמן ידון לפי ר"ש).
** יש מעלה
של מוסיף במה שהוא לענין דין זה. יש מעלה של כלל במה שהוא שם לענין זה. ותו"ת.
** יש שכ’
שדין שבע לה טומאה בא ממה שאין איסור חל על איסור. הק’ לי א.י.ש. שקשה למה לא אומרים שמיתלא תלי. יש לומר שרק אומ’ כן גבי איסורין כיון שנמשך הסיבה. אולי אינו כן בטומאה, והוא רק טמא אחר זמן מפני שהיה טמא.
שאלתי שר.מ.ש. הק’ בשם חז"א ל"ל אומרים כן במצורע שנעשה בע"ק בתחילת המסכתא. ויש לומר שהוא מוסיף לענין איסור לבוא בית המקדש.
* לג:
** בת אחת -
יש לדון למה זה כל כך פשוט להיות קל וחומר. ותחשב.
** מידי ברשיעי -
לכאורה, ר"ל שלא מצוי שיהיה כן, וקשה למה תנא ידבר באותו ציור. כמו כן, יש לומר שדאי לא קתני, ואז לא היה לו לשנות כן. אפשר ששני נקודות אלו שווים.
ויש להעיר שאולי יוצא מגמ’ לקמן שבין כך ובין כך זה ציור מוזר. יש לדון, אז, אם היה כל כך קשה להוסיף שהיו רשיעי.
* לד.
** עיין איך
רש"י מבאר למה קידושין רק חלים כשהם בני שלש עשרה. מעניין שיכולים לעשות שליח לפני כן. צריך ביאור. ותחשב.
** קשה למה
צריך שופעות, שרק נאמר שהם נדות מלפני זמן, ועכשיו נעשו בני מצוות. וצריך ביאור.
* לה:
** איידי… יוציא -
יש לדון למה, אז, לא אמר "לא צריך להוציא,” שאז יכול לומר שני הדינים, שבאחד לומר שצריך להוציא, ובאחד אומר שלא צריך להוציא. צריך לומר שהוא יותר ארוך לומר שצריך להוציא. עדיין קשה ל"ל אומר שלא יוציא. יש לומר שאף זה משמע שצריך שלא יוציא. עדיין קצת מעניין שלא נקט זה כדי להיות יותר אגבו. צריך לומר שנקט לשון שהוא יותר אגבו, אבל עדיין רצה לומר לשון קטן. ותחשב.
** בחליצה -
צריך ביאור איך לבאר כן במקורות שלהם.
* לו.
** ואם תאמר רוב -
קשה;חוששים לזה או לא. אם חוששים, אז לא צריך בבא זה. אם לא חוששים, אז קשה למה מז’. אולי צריך צירוף. קשה, שלא משמע שסברה שניה צ’ צירוף, שאינו חשש, אלא וודאי. גם יש לומר שר"ל שאם תסבור כר"מ, יש ראשון. אף אם לא, יש שני. ותו"ת.
יש לדון ל"ל רק אמר השני. אין זה קשה, שלמעשה רק אמר השני. ויש לדון מה משנה בג’ ומה לא משנה.
** ולא תנן -
יש להעיר שלמקצת לשונות לעיל, אומר ר"ל שמשנה מדוייק כמותו. אולי לא סובר כאותם לשונות, ואולי סבר שהיה לו למשנה לשנות אותו יותר בפירוש. ותחשב.
יש לדון, שלכאורה, אף זה לא כל כך בפירוש. ותחשב.
* לו:
** דבר אחד -
אין להקשות שר"מ אמר שלא יחזיר, ורבי אליעזר לא אמר כן, שרבי מאיר צריך לומר כן כיון שמיירי במגרש בזמן שאסור לו, אבל רבי אליעזר מיירי במגרש בזמן שמותר לו. אז, פשוט שלפי ר"א אי אפשר לקיימה, שהשתא מכורה כבר…, כמו שאומר גמ’ בערכין.
* Footnotes
[fn:1] זה בא לעורר, ולכאורה, הוא נקודה טובה, שאין זה סימן, אלא אומר מה מוסיף במילים אחרים שאינם, לכאורה, יותר נזכרים. אלא נראה לומר שהם יותר נזכרים כיון שאומר דמיון בין מה קורה (הוספת ציור) למהו הציור (הוספת דור).
[fn:2] יש שני סיבות לזה:נעשו יהודים מהיות בני נוח.מתו ובאו עוד לחיים (ויש דנים אם ר"ז היה כהן אחר שרבה שחטו).
