* פרק חמש עשרה נשים
* ג.
** וליתני -
עיקר מצוה- תח’ מה ר”ל. לכאו’, הוא רק שכיון שיש מצוה לעשות כן, כן בדר”כ נעשה, ואז יותר נוגע פטורו. ותח’.
** אבא שאול -
קרוב בעיני- יש לדון מהו פי’ לשון זה:
א. בעיני, נ’ צד חזק שהוא ממזר.
ב. בעיני, נ’ כדבר הדומה לממזר.
* ד.
** לסקילה -
משמע מרש”י שאי הוה קולא היינו יכולים לדרוש. משמע, אז, שיותר קל לדרוש חומרא מלדרוש קולא. תח’. ונ’ שזה אי אפשר כאן, שלכאו’, דחיית לאו הוא קולא (כן נ’ מגמ’ לקמן ד”לחומ’ דורשין”), ואז, לא נצטרך מה שדורש במשנה תורה, אלא מה שדורש לקולא. ואפשר שרק מבאר רש”י מה שאומר ר”י, והוא שא”כ, החמרת עליו שלא כדין.
* ה.
** שאין -
ע’ במש"כ. מעניין שלאו אשה ולאו איש נחשב חד, שיש בהם מכשה חלוד. ותו"ת.
* ה:
** כולה -
לא מבאר רש"י למה לא אומרים שכולו בא לדין שוע טווי ונוז.
* ו.
** וכי תימא -
משמע שאף לאו של שבת נחשב "חילול שבת.” ואולי לאחר קרא אינו כן. ודחוק.
* ו:
** לחלק -
עיין ברש"י מכות (כא:).
* ט:
** והאמר -
וחזר שמעון ואנס- לכאו’, אין צריך שחאנס, שיכול לישא.
* יב:
** ואפילו לר"י -
ע’ איך מפרש שיטתו. גמ’ בנדה לא מפרשו כן.
* יז.
** ולא מתייבמת -
נראה לי שלש מהלכים בזה:
1. קונה קצת מדרבנן (שעשו לו קצת קנין כדי לאסור)
2. אסרו רבנן כאילו קנה קצת. לשונו לא משמע כן.
3. יש קצת קנין מדאו’, ומפני זה גזרו רבנן.
* יז:
** לימא הלכה -
צריך ביאור למה מניח רש"י שהוא ריב"ב, ולא האומרים שבעל יפר. ותחשב. ואולי כיון שאפשר לאוקמיה לזה במאמר, לא הביאו. קשה, שלקמן, יביאו. ותחשב.
* כ.
** תפסי -
לאו קיחה- ק"ק שמגמרא מבואר שאף בחייבי לאווים, אם עשה ייבום, לא חל (ובאמת, קצת יש לדון למה. ונראה שגמרא רק אומר שלא חל מתורת ייבום, אבל אולי אם כיוון לקנין ביאה, חל). אז, בוודיא אין קיחה. ואולי רצה לומר שאי אפשר לומר שלא יחפוץ לקחת, שמה שחושב עליו כשחושב אם ייבם או לא אינו נשואים וקיחה לה, שהרי אין זה אפשרות. ותחשב.
* כ:
** אם בעלו - מדייקים כן -
מניח שהראיה משם. אם כן, אין ראיה נגד צד אחר שאמר שהוא מדרבנן. אפשר שמדייק- ומצינו גמרות
ממה שמביא ביאה שניה, שמשמע שכבר היה דן בה.
** תיובתא -
לקמן מסיק שאינו תיובתא לר"ל. צ"ב. ותו"ת
* כא.
** הא פסיקא -
גם הוה מצי לומר שאין היתר אשת חמיו פסיקא, שמצוי שהיא חמותו.
** כלתו -
יש לדון למה כלת בנו יש בו ערווה בדורותיו. יש לומר שכלתו יותר דומה לכלת בנו מלכלת בתו כיון שהוא ובנו זכרים. גם יש לומר שבכלת בנו, יש, מסתמא, באותו ציור לו כלה. ותחשב.
* כב:
** השתא מיהת -
משמע שמה שאומר גמרא שלא יכול לתקן הוא אומר שחטאו לעולם נזכר (לכאורה, זה אומר שלעולם הוא מחלל שם שמים בזה). ותחשב. ועיין בשיח שי בחגיגה, וצרף שניהם.
* כד.
** ואי למ"ד -
קשה למה צריך לסמוך על "נאסרה" לומר כן, ולא רק לומר שהוא איסור חמור יותר משל כאן, ולכן גזרו אף אחר כן )כמו שמשמע גמרא). ועיין גמרא לקמן שנראה כרש"י. בביאור נאסרה זה, נראה שאף שמדאורייתא יכול, כיון שיודעים שאי אפשר לו (מפני שצריך לשמוע לרבנן), אינו "נועם." ק"ק למה לא אומרים כן אף אם הוא במדינת הים, ולא יוכל עד לאחר זמן. ותחשב.
* כה.
** המביא גט -
ע’ בטעמו שאמר. ודע שחולקים בזה שם, ויותר היה לו לרש"י לומר טעם השני שם, שכולי עלמא סוברים כן. וע"ש.
* כו.
** גירושין -
עיין בתוס’. עיין ברש"י, שלכאורה, מבואר שחולק. ויש לדון למה זה יאסר אשה. ויש לומר שרע לגרש אשה, ואז אין לישא אשה כדי לגרש אותה. ויש להעיר שזה מוכיח שאין רעת גירושין רק מה שאינה נשואה, שכאן, גם אם נחוש לזה, לא תנשא, שלא ישא אותה שום איש. ותו"ת. אז, לא מרווחים בחשש זה.
** מיתה -
יש להעיר שלכאורה, אין זה קשה אלא על מת (ורש"י מזכיר הרגוהו לאו דווקא או לצד השני) לפי צד אחד בגמרא, שאומר שממיתה ממעיה (ע"י ביאה). ותו"ת.
* כז.
** יגמור -
יש לדון אם כשאומר "כל שכן" רק בא לבאר דין או אולי בא לבאר שאז ברות דוקא, שיותר טוב לחלוץ לשני הצרות, ואין צריך לומר שהוא צרות דעלמא.
* ל.
** ראשונה -
כיון שיש שני משמעויות כאן, היה גמרא מסופק בזה בתחילת הפרק. ותו"ת.
* ל:
** ספק קרוב -
עיין במה שבאר. עיין שם בגיטין (עח) שלא משמע כן.
* לא.
** מפולת -
נביאים- ק"ק, שאף אי היו נביאים, לא היו יכולים לסמוך על מה שיודעים בנבואה שלהם. משמע שיכולים לסמוך על ידיעת שבאים מנבואה, ורק לא יכולים לסמוך על הלכות.
* לד.
** ורבי מאיר -
מרבותיו- משמע שהיו ר"א ור"י רבותיו. מעניין, שלכאורה היה תלמידו של ר"ע, שהיה תל’ של ר"א ור"י. אולי הוא לאו דווקא.
* לה:
** דלא סגי -
ע’ במש"כ שא"א לחלוץ לה כיון שכבר בא עליה. יש לדון מה אומר בזה, שלמה יעשה מה שבא עליה באופן שלא היה ייבום לעשות שלא יוכל לחלוץ לה.
* לו.
** דכל -
לא אמר שיכול לבועלה כדי שלא יהיו חייבי לאווים קשים (ויש להעיר שהיה לגמ’ צד שנחשבים שלא עולים לייבום, ומשם גופא דרש). ותחשב.
