** קט: כאילו בנה -
עיין ברש"י. נמצא שיש איסור בעשיית במה. אולי הוא אסור רק מפני שגורם איסור (שיבוא הוא או אחר להקריב עליה). אולי אף נדר כן, שאסור שאולי יעבור. עיין בנדרים, שיש גמ’ שמשמעים שאסור מפני שמצער את עצמו, ויש שמשמע שהוא שמא יעבור. וצלע"ש.
גם מעניין שנחשב שני איסורים, אם הראשון אסור רק במה שגורם לשני. ויש לדון, שאולי ראשון אסור מפני שגורם לכמה איסורים כמו שני, שיביא עליו זמנים הרבה. ותו"ת.
** רש"י לישנא אחרינא -
רק משנה ביאור הלשון, ולא ביאור הבעיה.
** בלילות -
מניח גמרא שזה מפני שהיה דן. ותו"ת.
שוב ראיתי מש"כ רש"י.
** אין לו תורה -
יש לציין לגמרא חגיגה שדן בו בשכר אחר מפני תורתו. אולי שם אינו שכר, אלא דבר אחר (שתורה מגין עליו לסיבה אחרת). ותחשב.
** קי. תינח דקדיש -
עיין במש"כ. ק"ק, אז, למה צ’ גמ’ להביא הא דכל דמקדש על דעת רבנן מקדש, שלכאורה, פשוט שרבנן יכולים לבטל, שכבר פשוט שהפקר ב"ד הפקר, ולא משתמשים בתנאי שמתנים. אם נאמר שרש"י רק אומר זה לסימן, אין קושיה שניה קשה. ותו"ת.
** פב: כרבי יוסי -
אז, אין להוכיח ממשנה לעיל, שיש לומר שסובר שהוא דרבנן, ואינו ר"י.
** דלא נשקל -
אם כן, צריך לומר שכאן הוא עדיין מחצה. יש לומר שאולי מה שיש אותו ספק מניח גמרא שהוא כמחצה. אם כן, דן גמרא אם הוא שווה למחצה על מחצה או הוא יותר טוב. אפשר גם שדן אם מה שאף אם לא לשם נפל, אין כולו אסור עושה שהוא קצת בטל, ואז הוא יותר טוב. ותחשב. גם יש לומר שדן כמה צד יש שמוציא אותו מים שנתן.
** פג. מדשבקיה -
צריך ביאור מהו ההוכחה מזה.
** אין אדם אוסר -
אולי הענין הוא שאין מה שעושה נעשה כל כך שם של החפץ. גם יש לומר שלא מיוחס כל כך לחפץ, כיון שמי שקונה חפץ יכול לסלקו. ותחשב.
** פב: רש"י רבי יוחנן -
מניח שגמ’ חושב שלאו דווקא "שאני אומר.” עיין לעיל, שכ’ שאולי גמרא רק חשב שלא מהני יותר מציור של מקווה.
** פד: מכלל דהוא פסול לקהל -
ואם תאמר היה לו להקשות אטו יש מי שאינו כשר לכהונה. ויש לומר שאין, יש מי, שדיחוי זה אומר שאין כשרות נושאים פסולים.
** עונשים -
לכאורה, אם כן, לא מצווה על לאו שאין בו מלקות, כמו לאו שאין בו מעשה. נראה שאולי עדיין מצווה על לאו הניתק לעשה, על פי מה שאומר רש"י בכ"מ, שהעשה הוא עונש של הלאו.
** פה. רש"י בני בירי -
היה אפשר לומר שהיו אחים, והיה שם אביהם בירי.
** פו. ואכלתם -
נראה לי שאמרה משנה בלשון הקרא.
** אלא גזירה משום -
לכן, כ’ בת כהן, לחדש גזירה זו. ולצד א, גופא כתב כן למעט מצד שני.
** פז. פרט להפרת נדרים -
לכאורה, היה לו לגמרא לדחות שאין זה לחם. יש לדון, שאף חזה ושוק אינו לחם. ויש לומר שעדיין הוא יותר קרוב, שהוא מאכל. יש לדון אם זה מהני, שאולי כיון שקרא כבר לאו דווקא, אינו קשה לומר שהוא דבר שהוא יותר רחוק.
** מי עדיפא לה מיניה -
יש לדון אם ר"ל שכיון שהוא גופא נתרבה משם, איך יהיה עדיף. ע"ש, שאיני יודע אם מרבה אותו מאותו קרא. גי"ל שמק’ שכיון שהוא רק נדרש, ולא נכתב, איך יהיה חמור ממה שנכ’ יותר בפירוש. ותחשב.
** ולד מן הראשון כולד -
קצת צריך ביאור, שיש חילוק פשוט (אינו קולא וחומרא, אלא חלוק), שבשניהם אין ולד מן הראשון כולד מן השני, אלא הוא כולד מן הראשון, אלא שבאחד ולד מן הראשון גורם אותו דין, ובאחר אין ולד מן הראשון גורם אותו דין. אולי צריך לומר שאינו כן, אלא ולד מן הראשון ממש כולד מן השני. צריך ביאור למה יעשה כן.
** פז: רש"י סריקא -
יש להעיר שאילן סרק הוא אילן שלא יכול להוליד, אבל אשה ריקא הוא אשה שאין בה וולד.
** ולא בהפרת -
לשון, “ולא זכאי בהפרת…,” וכן מה שנכלל עם מעשה ידים וכדומה משמע שהוא זכות בה. מעניין, שגמרא אומר שהוא רק דבר שקורה ממילא כיון שנודרת על דעתו.
באמת, צריך ביאור ל"ל אומרים שכאן נודרת על דעתו. נראה שהוא מפני שלא נותן לה מזונות. אם כן, של לפני זמן נתבטלים. ויש לדון, שאולי אלו היו תלויים עליו בטעות. ותו"ת.
** פח. לאו משום דאישתיק -
קשה, שאולי אינו מפני שהוא מודה, אלא מפני שהוא רק נאמן נגדם כשהוא טוען, אבל כאן לא טוען. ותחשב.
** צ: רש"י בטלו -
עיין שם, שחולקים למה בטלו. נראה שרש"י מזכיר זה כיון שכן פוסקים. נראה שגם יש לפסוק כן כיון שמבואר בראשונים שם שכולי עלמא מודו לחשש וביטול זה. ותו"ת.
** צא. תרומה דרבנן -
יש לדון מהו הדין במעשר דרבנן.
** רנב"י -
יש להעיר שרש"י סובר שר"נ הוא רנב"י. אבל, גם סובר שר"נ ור"ה חול’ בשיטת רבי מאיר. אם כן, קשה איך בעל מימרה זה יאמר שר"ה כר"מ, שהוא נגד שיטתו. אולי סובר שיש שני סתם ר"נ. עיין בקידושין (קרוב לדף ל) במסורת הש"ס. גם יש לומר שרק ר"ל שר"ה סובר שהוא כר"ה. אולי לכן פ’ רש"י שזה קבל מזה…, ולא שסובר זה כזה. ותו"ת.
בכל זה, עיין בחבורה שכתבתי על זה.
** רבי אליעזר -
מעניין שמניחים אותו כאן בשלשלת הקבלה, שלכאורה, רבי מאיר היה תלמיד של רבי עקבה. ותחשב על זה.
** משום דאיהי -
אם נאמן מחמת שמאמינים עד אחד, אם כן, אין פסול אשה לבעלה ובועלה מחמת שאינו אונס. גם קשה איך נאמר שאל צריך בדיקתה, שהרי לכן קונסים אותה. אולי צריך לומר שעדיין צריך לו קצת, אבל לא כל כך. דחוק.
** צה. תנהו ענין לשריפה -
אולי יש לציין למש"כ גמ’ סוטה שיש אש בבית כשיש זנות בבית.[fn:1]
** צח. אשה ושבעה בניה -
לא הבנתי איזה ראיה יש מזה, שרק מביא ראיה שנשא, ולא שהיה נכון לו לישא או שאמר כן שום תלמיד חכם.
** ואי בעית -
דניכרים- כיון שכבר סומכים על ניכרים דברי אמת לומר שנאמרים יחד, קשה ל"ל נאמר שמיירי בניכרים שהיה אומר האמת. אולי בזה אף שניכרים לא נאמן, כיון שבני אדם אחרים שלא מכירים באותו נאמנות יוציאו לעז עליו. דחוק.
לולי רש"י, היה נראה לומר שר"ל שלא היה מוסיף פרט זה אילו לא היה אמת. זה מראה שהוא מכוון לומר אמת, ולא בורא את זה מלבו.
** צט: לשון ראשון קשה -
יש לדון, שמספקים אם יכול להביא. נראה שכיון שהוא ספק, בוודאי אי אפשר להביא, כמו אם היה חלוש וזקן אי אפשר להביא. ותחשב.
** ואין מוציאים -
לפשט ראשון של רש"י, מעניין שמניחים שהם המוחזקים עליו, שלכאורה הכהנים מקריבים אותו, ואז הם מוחזקים עליו. ותחשב.
** השתא בהמתם -
תוס’ כ’ שזה רק באכילה. יש לדון איזה אכילה יש כאן. אולי רבו שחררו, ועדיין רצה לאכול תרומה.
** ק. דמחייב -
יש לדון אם הענין הוא שטוב לתת לו זמן לעשות מצוות, שיעשה יותר מצוות, או שאז רואים (או שמפני זה) שהוא יותר חשוב. ויש לדון בזמן ראשון, שהיה אפשר לומר שאף אשה תעשה מצוות בכל אותו זמן, אלא שלא יהיו כל כך כמה מצוות חלוקות. ותחשב.
** ק: טעות -
היה אפשר לומר שמיירי בקידושי חוץ, אלא שיש תנאים שסוברים שאין זה מהני. ותו"ת.
** קיג. רב מלכיו -
נראה שזה הזמן המיוחד שהובא רב מלכיו שלא הובא ב"שפחה שפוד….” יש פעם אחר שלא הובא בו כל המימרה של שפחה…, והוא בע"ז (לד), אבל זה הובא בתוך המימרה של "שפחה….”
** קיג: כיון דעתים -
צריך ביאור אז איך משנה יכול לומר חרש שנשא אשה יכול לגרש אותה, שאולי בתחילה לא היה שוטה ועכשיו הוא שוטה. ותו"ת.
** לדבריהם -
ר"ל שחשב שיותר קל לחלק על מה שאמר שאשה צריכה דעת מלחלק מלומר שאיש צריך דעת, אם נאמר שאשה לא צריכה דעת. ותחשב.
** קיד: שב שנים -
צריך לומר שזה היה דבר שנוהג, או שהיה ידוע, רק גבי דבר.
** קטז. קפיצה -
עיין במה שבאר רש"י. מוזר שחוששים לזה.
** קטז: ההיא דאתא -
ק"ק ל"ל רק אמרו לה שלא לבוא לבית דין של ר"י. אולי לא היה אחר קרוב לה.
** משום דאיהי -
ר"ל שכאן מאותו מעשה למדו יסוד. בציור של רחב"ע, לא למדו שום יסוד, אלא גזרו מפני שרע קרה במעשה כזה.[fn:2]
** מספר כתובה -
יש לדון אם זה סימן שכשחז"ל תקנו כתובה תקנו כן, או שכל מי שכותב כן מקבל כן. לכאורה, הראשון נראה, שרבנן תקנו שיכתב כן.
** קיז. הואיל דלא -
עיין במה שפרש"י. גם היה אפשר לומר שלא יודעת אם גט יהני לה, ואז שואלת לה אחרון, שלא יודעת אם רוצה אותה. ותחשב.
** קיז: לא בעלה -
צריך לומר שפלגינן, ורק חוששים לזה לענין חמותה.
** אף על גב דאסור -
נמצא שרב שמנגיד לא אסר אותו, אלא כבר היה אסור. יש לציין לתוס’ גיטין (לג:) שכ’ שאין איסור בקידושי ביאה.
** קיט: רובא דאיתא קמן -
קצת צריך ביאור, שאם רבי מאיר חולק על זה, נמצא שאף חולק בדין סנהדרין. לכאורה, זה עושה נפק"מ גדולה מאד, ולא נשמע, לכאורה, בכל הש"ס. אולי מה שנשמע שיטת ר"מ בדרך כלל ברוב די. ותחשב.
גם יש לומר שדין רוב חלוק מדין בית דין, שדין בית דין הוא שאף שאינו נחשב שכל בית דין אומרים כן, כן הפסק, אבל אולי אין ללמוד מזה דין הרוב, שלא יכולים להניח כלום על כל אחד ואחד. ותחשב.
** סנהדרין -
בלי זה, לכאורה, לא היינו יכולים ללכת אחר רוב, אלא היינו צריכים לדון עד שכולם מודים. צריך ביאור, אז, איך נמית, שלא ממיתים אם כולם מודים. אולי נמצא רק אם לא מחייבים מחד טעם. ותחשב. גם יש לומר שצריך לשהות עד שמי שלא מודה הוא רק מיעוט מן המיעוט.
** רש"י רבי מאיר חייש -
לא מביא הא דחליצה, אף שזהו מה שמביא רש"י במק"א כיון שפשוט שגמ’ לא ידע אותו כבר עד שמקשה ממנו. ותחשב.
** קיט: סמוך -
לכאורה, זה שווה לפשט ראשון שאמר גמרא. ותו"ת.
** מצריכה כרוז -
צריך ביאור ל"ל רק אומרים שתהא אסורה לישא לכהן אחר כן. אולי עושים מה שיותר טוב לה, ויותר טוב להחמיר עד שבא צרה מלחלוץ לה ולאסרה לכהן. דחוק.
** קכא. קירב מיתתו רש"י -
פרכס יותר מדי- משמע שמה שפרכס כלל אינו סיבה לפטור אותו. לכאורה, הוא מפני (וצריך לחשוב למה זה עושה כן) שפשוט שיפרכס. ותחשב.
** צמית -
נראה ששניהם שייכים זה לזה, שעושה שעור יותר קטן. זה ממילא מגדיל את המכה, וגם צמית העור, ועושה אותו עדיין ניכר. ותו"ת.
** לאחר שלשה ימים -
לכאורה, פשוט שלא יחיה כך לעולם. צריך ביאור אחר כמה זמן מתיר ר"מ.
** כמה גדולים -
מעניין שר"ע אמר כן, שכבר ידע שכן קרה לעצמו. אולי זה קרה אחר זה. ותו"ת.
** קכא: מת בנו -
לכאורה, זה אומר שלא היה רחב"ד נכון. צריך ביאור. ותחשב.
** קכב. תלתא רגלי -
ואם תאמר איך הלך אביי לקברו כיון שהיה כהן (כמבואר בחולין ובכ"מ). ויש לומר שרק הלך קרוב לו, ולא שם עצמו.
** סתמא -
נמצא שאם יודעים מברייתא שסת"מ הוא ב"ש לא פוס’ כמותו. צ"ב ל"ל.
** סתמא -
ק"ק למה לא אומ’ את זה בשאר מקומות שדנים בשיטת ב"ש וגמ’ מק’ מה לנו לדון בהם (למשל, עיין בשבת פרק יט).
** החזיקו -
לא הבנתי, שהחזיקו, לכאורה, היה רק לענין ע"א, שהרי ר"ע החזיק אותו. ותחשב.
* Footnotes
[fn:1] ואם תאמר אי אפשר לומר שאש מכוון לאיסור זה על זה, שאומר כן אף על זנותו. ויש לומר שזה מפני שגמ’ גם אומר שזנותו גורם זנותה, וממילה תאסר.
[fn:2] לכאורה, באמת, הענין הוא שעל ידי זה יזכרו אותו מעשה, ויראו כמה רע הוא, ואז יקפידו.
