פרק א
משנה א
1. זה- אחד נעשה זומם-
עיין שם. לכאו', ציור של הגמ' לא באמת עושה כן כאן, שהוא מיוסד על הודאתו, ולא מצאנו חיוב חוץ מחיוב ממון שבא על הודאה. (ויש להעיר שיש לדון- וזה נוגע בפרק אלו נערות- אם אומרים שעונש של עדים זוממים הוא תמיד "כאשר זמם," אלא שזה משתנה, או שהוא כל מה שזממו. אז, כשחייבים ממון, יש לדון אם חייבים כאשר זמם, והוא ממון, או חייבים ממון. לא פשוט שיש חילוק, ותחשב. אף אם יש חילוק בלומדות, לא פשוט שיחלק לזה. אבל, כוונה שלנו הוא רק לומר שאולי אם נאמר שבכל זמן חיוב שלהם שווה- הוא כאשר זמם- אין לחלק בין ממון לשאר עונשים. אבל, אז היה נראה לומר שלא יכול להודות באף אחד מהם, ואז רק נוכיח נגד צד זה.) אבל, עדיין נראה שנמצא בציור אחר כזה, והוא כשהודה אחד, ושוב באו עדים. (יש לדון אם דין של מודה בקנס הוא גם בקנס של עונש, ולא של ממון.) כמו כן, נמצא אם אחד כבר מת.[fn:1]
1. כתובתה- מה שצריך הבעל לתת-
גמ' לא מזכיר את זה, אבל לכאו' הוא רק מאתים מזה, שכמו שלא יודע על מה שצריך להחזיר, כך לא יודע שכ' לה יותר ממאתים. ותחשב.
* Footnotes
[fn:1] אבל, יש להעיר שלא פשוט אם, באמת, יש חידוש בזה (ויצטרך משנה להשמיע לנו). נראה שאולי מה שגמ' לא נוקט אותו ציור משמע שאין בו חידוש, והוא שנראה מן הגמ' שכל ההו"א לפטור אותו בא ממה שפוטרים את חברו. אבל, אם חברו מת, או שחברו יש לו פטור מסויים שידוע למה לא שייך לו, אולי אינו בעיה לחייב אחד מהם ולפטור את השני. ותחשב. כמו כן, יש לומר שיש חידוש רק בממון, כיון שרק משלם לפי חלקו, ואם רק אחד ישלם, לא נעשה כאשר זמם. יותר מזה, יש לומר שכל החידוש הוא שרק משלם לפי חלקו, ולא משלם כולו אם רק הוא משלם. אבל, לשון גמ' בביאור ההו"א לא אומר כן.
