** יב. מאי אהני ליה -
יש להקשות, אז, איך יודעים איזה למעט ואיזה לרבות. ונראה שהוא דבשמנה הם אולי יותר חשוב בענין שמו של שה. וצריך ביאור איך יודעים באיזה נחלק (שאף שיודעים מה יותר מסתבר ממה, לא יודעים כמה מסתבר צריך להיות). ותחשב.
** יג. זוטרן -
צריך ביאור אם ר"ל שזוטרן מילי במשניות או בקראי (ואז הוא כעין דבר שנלמד מדרשה). איני יודע אם, במציאות, אין לו כל כך כמה קראי.
** בדיניהם -
אולי דין ר"ל ההלכה שלהם או שדין ר"ל קל וחומר, ור"ל ההלכה שנלמד מדין (קל וחומר) שלהם.
** יג: אף עובד כוכבים -
זה מעניין, שהרי גיפא לימוד של הקרא הו"א שהוא שאינן דומים, ואז לא נלמד כזה. ותחשב.
** יד: אף תמורתו בעל מום -
וצ"ב שאולי הוא מדלא נקיש לענין קידוש בע"מ לא נקיש להרבה. ואולי מקשים ג, כ לקדושה, והוא שאי אירע מם בקרבן עכשיו (שק‛ הוא) נקרב.[fn:1]
** יז. ניחזי אנן -
יש לדון אם הביא לו השאלה, וזהו מה שאמר, או אולי לא הביא לו את השאלה כלל (והיה מתרץ מדעתו).
** יז: הכל בכתב -
ובענין שיעור כמו אמה, יש לדון אם יש שיעור בעצם אלא שאי אפשר לנו לבוא לזה בצמצום, או אולי השיעור בעצמו יש בו range. ותו"ת.
ויש לדון ל"ל שאל מהם. גם יש לדון איך יתרץ, שמשמע ש“הכל מכתב“ שייך לתירוץ. ויל"ד איך שייך.
** יח. ההוא דבריא -
יש לדון אם הוא סימן או סיבה. וכן יש לדון בצד שהוא סימן הוא הסיבה ליציאה ראשון או שמה שגרם שהוא בריא גם גרם שיוצא ראשון. ותו"ת.
** יח: דלא תשתכח -
מעניין שחוששים לזה, שאין זה, לכאורה, כל כך מצוי.
** קא משמע לן -
ועוד שחידוש בר"מ שא"א כסברת רבי יוסי.
** כ. מחוורתא -
עדיין אפשר שאומר כן (ואפשר שר"מ אומר כן) רק בררובא דליתא קמן.
** כג. אנן -
משמע שלא היה לו על רח“ס כלל. אז, נ‛ שלכל אחד היה ציור אחד קשה. ואינו מוכרח.
** כד: דבר שא"מ -
צריך ביאור למה אינו מלאכה שא"צ לגופה.
* Footnotes
[fn:1] דבר ראשון שכ‛ הבנתי- והוא שדנתי למה לא לומדים מזה שא"א לקדשו כל כך. דבר שני שכ‛ צריך ביאור.
