פרק ראשון[fn:1]
משנה א[fn:2]
[fn:3][fn:4][fn:5][fn:6]א.
הַלּוֹקֵחַ עֻבַּר חֲמוֹרוֹ שֶׁל נָכְרִי[fn:7], וְהַמּוֹכֵר לוֹ[fn:8][fn:9] אַף עַל פִּי שֶׁאֵינוֹ רַשַּׁאי[fn:10][fn:11], וְהַמִּשְׁתַּתֵּף לוֹ[fn:12][fn:13], וְהַמְקַבֵּל מִמֶּנּוּ[fn:14][fn:15][fn:16], וְהַנּוֹתֵן לוֹ בְקַבָּלָה[fn:17][fn:18][fn:19], פָּטוּר מִן הַבְּכוֹרָה, שֶׁנֶּאֱמַר (במדבר ג), בְּיִשְׂרָאֵל[fn:20] , אֲבָל לֹא בַאֲחֵרִים[fn:21].
ב.
כֹּהֲנִים וּלְוִיִּם[fn:22] פְּטוּרִין[fn:23][fn:24] מִקַּל וָחֹמֶר, אִם פָּטְרוּ שֶׁל יִשְׂרָאֵל בַּמִּדְבָּר, דִּין הוּא שֶׁיִּפְטְרוּ שֶׁל עַצְמָן[fn:25]:[fn:26]
משנה ב[fn:27]
א.
פָּרָה שֶׁיָּלְדָה כְּמִין חֲמוֹר[fn:28], וַחֲמוֹר שֶׁיָּלְדָה כְּמִין סוּס[fn:29][fn:30] , פָּטוּר מִן הַבְּכוֹרָה, שֶׁנֶּאֱמַר פֶּטֶר חֲמוֹר פֶּטֶר חֲמוֹר[fn:31], שְׁנֵי פְעָמִים[fn:32], עַד שֶׁיְּהֵא הַיּוֹלֵד חֲמוֹר וְהַנּוֹלָד חֲמוֹר.
ב
וּמָה הֵם בַּאֲכִילָה[fn:33] בְּהֵמָה טְהוֹרָה שֶׁיָּלְדָה כְּמִין בְּהֵמָה טְמֵאָה, מֻתָּר בַּאֲכִילָה[fn:34]. וּטְמֵאָה שֶׁיָּלְדָה כְּמִין בְּהֵמָה טְהוֹרָה, אָסוּר בַּאֲכִילָה[fn:35], [fn:36]שֶׁהַיּוֹצֵא מֵהַ[fn:37]טָּמֵא[fn:38][fn:39], טָמֵא. וְהַיּוֹצֵא מִן הַטָּהוֹר, טָהוֹר. דָּג טָמֵא שֶׁבָּלַע דָּג טָהוֹר, מֻתָּר בַּאֲכִילָה[fn:40]. וְטָהוֹר שֶׁבָּלַע דָּג טָמֵא, אָסוּר בַּאֲכִילָה, לְפִי שֶׁאֵינוֹ גִדּוּלָיו[fn:41]:[fn:42]
משנה ג[fn:43]
חֲמוֹר שֶׁלֹּא בִכְּרָה, וְיָלְדָה שְׁנֵי זְכָרִים, נוֹתֵן טָלֶה אֶחָד לַכֹּהֵן[fn:44][fn:45][fn:46]. זָכָר וּנְקֵבָה, מַפְרִישׁ טָלֶה אֶחָד לְעַצְמוֹ[fn:47]. שְׁתֵּי חֲמוֹרִים שֶׁלֹּא בִכְּרוּ, וְיָלְדוּ שְׁנֵי זְכָרִים, נוֹתֵן שְׁנֵי טְלָיִים לַכֹּהֵן. זָכָר וּנְקֵבָה, אוֹ שְׁנֵי זְכָרִים וּנְקֵבָה, נוֹתֵן טָלֶה אֶחָד לַכֹּהֵן[fn:48]. שְׁתֵּי נְקֵבוֹת וְזָכָר אוֹ שְׁנֵי זְכָרִים וּשְׁתֵּי נְקֵבוֹת, אֵין כָּאן לַכֹּהֵן כְּלוּם[fn:49].[fn:50]
משנה ד[fn:51]
א
אַחַת בִּכְּרָה וְאַחַת שֶׁלֹּא בִכְּרָה וְיָלְדוּ שְׁנֵי זְכָרִים, נוֹתֵן טָלֶה אֶחָד לַכֹּהֵן. זָכָר וּנְקֵבָה, מַפְרִישׁ טָלֶה אֶחָד לְעַצְמוֹ. שֶׁנֶּאֱמַר[fn:52] (שמות לד), וּפֶטֶר חֲמוֹר תִּפְדֶּה בְשֶׂה,[fn:53]
ב
[שה שנותן לכהן יכול להיות] מִן הַכְּבָשִׂים וּמִן הָעִזִּים . זָכָר וּנְקֵבָה, גָּדוֹל וְקָטָן, תָּמִים וּבַעַל מוּם[fn:54]. וּפוֹדֶה בוֹ פְּעָמִים  הַרְבֵּה[fn:55]. נִכְנָס לַדִּיר לְהִתְעַשֵּׂר[fn:56][fn:57] . וְאִם מֵת, נֶהֱנִים בּוֹ[fn:58].[fn:59]
משנה ה[fn:60]
א
אֵין פּוֹדִים לֹא בָעֵגֶל[fn:61], וְלֹא בַחַיָּה[fn:62], [fn:63]וְלֹא בַשְּׁחוּטָה[fn:64], וְלֹא בַטְּרֵפָה, וְלֹא בַכִּלְאַים[fn:65]. וְלֹא בַכּוֹי[fn:66].[fn:67] רַבִּי אֶלְעָזָר מַתִּיר בַּכִּלְאַיִם מִפְּנֵי שֶׁהוּא שֶׂה[fn:68], וְאוֹסֵר בַּכּוֹי מִפְּנֵי שֶׁהוּא סָפֵק.
ב
נְתָנוֹ[fn:69] לַכֹּהֵן[fn:70], אֵין הַכֹּהֵן רַשַּׁאי לְקַיְּמוֹ[fn:71] עַד שֶׁיַּפְרִישׁ שֶׂה תַחְתָּיו[fn:72]:[fn:73]
משנה ו[fn:74]
הַמַּפְרִישׁ פִּדְיוֹן פֶּטֶר חֲמוֹר וּמֵת , רַבִּי אֱלִיעֶזֶר אוֹמֵר, חַיָּבִין בְּאַחֲרָיוּתוֹ[fn:75] , כַּחֲמֵשׁ סְלָעִים שֶׁל בֵּן[fn:76].  וַחֲכָמִים אוֹמְרִים , אֵין חַיָּבִין בְּאַחֲרָיוּתוֹ, כְּפִדְיוֹן מַעֲשֵׂר שֵׁנִי[fn:77]. הֵעִיד רַבִּי יְהוֹשֻׁעַ וְרַבִּי צָדוֹק עַל פִּדְיוֹן פֶּטֶר חֲמוֹר שֶׁמֵּת, שֶׁאֵין כָּאן לַכֹּהֵן כְּלוּם. מֵת פֶּטֶר חֲמוֹר, רַבִּי אֱלִיעֶזֶר אוֹמֵר, יִקָּבֵר[fn:78], וּמֻתָּר בַּהֲנָאָתוֹ שֶׁל טָלֶה. וַחֲכָמִים אוֹמְרִים, אֵינוֹ צָרִיךְ לְהִקָּבֵר, וְהַטָּלֶה לַכֹּהֵן[fn:79]:[fn:80]
משנה ז[fn:81]
לֹא רָצָה לִפְדּוֹתוֹ[fn:82], עוֹרְפוֹ בְקוֹפִיץ מֵאַחֲרָיו[fn:83] וְקוֹבְרוֹ[fn:84][fn:85]. מִצְוַת פְּדִיָּה קוֹדֶמֶת לְמִצְוַת עֲרִיפָה[fn:86], שֶׁנֶּאֱמַר (שמות יג), וְאִם לֹא תִפְדֶּה וַעֲרַפְתּוֹ. [fn:87][fn:88]מִצְוַת יְעִידָה[fn:89]  קוֹדֶמֶת לְמִצְוַת פְּדִיָּה[fn:90] , שֶׁנֶּאֱמַר (שם כא), אֲשֶׁר לֹא יְעָדָהּ וְהֶפְדָּהּ. [fn:91]מִצְוַת יִבּוּם קוֹדֶמֶת לְמִצְוַת חֲלִיצָה, בָּרִאשׁוֹנָה, שֶׁהָיוּ מִתְכַּוְּנִין לְשֵׁם מִצְוָה. וְעַכְשָׁיו שֶׁאֵין מִתְכַּוְּנִין לְשֵׁם מִצְוָה, אָמְרוּ מִצְוַת חֲלִיצָה קוֹדֶמֶת לְמִצְוַת יִבּוּם[fn:92][fn:93]. [fn:94]מִצְוַת גְּאֻלָּה[fn:95] בָּאָדוֹן הוּא קוֹדֵם לְכָל אָדָם , שֶׁנֶּאֱמַר (ויקרא כז), וְאִם לֹא יִגָּאֵל וְנִמְכַּר בְּעֶרְכֶּךְ[fn:96]:[fn:97]
פרק שני[fn:98]
משנה א[fn:99]
[fn:100][fn:101]א.
הַלּוֹקֵחַ עֻבַּר פָּרָתוֹ שֶׁל נָכְרִי, וְהַמּוֹכֵר לוֹ אַף עַל פִּי שֶׁאֵינוֹ רַשַּׁאי, הַמִּשְׁתַּתֵּף לוֹ, וְהַמְקַבֵּל מִמֶּנּוּ, וְהַנּוֹתֵן לוֹ בְקַבָּלָה, פָּטוּר מִן הַבְּכוֹרָה, שֶׁנֶּאֱמַר (במדבר ג), בְּיִשְׂרָאֵל, אֲבָל לֹא בַאֲחֵרִים.
ב.
כֹּהֲנִים[fn:102] וּלְוִיִּם חַיָּבִין. לֹא נִפְטְרוּ מִבְּכוֹר בְּהֵמָה טְהוֹרָה, (וְלֹא נִפְטְרוּ) אֶלָּא מִפִּדְיוֹן הַבֵּן וּמִפֶּטֶר חֲמוֹר[fn:103]:
משנה ב[fn:104]
כָּל הַקֳּדָשִׁים שֶׁקָּדַם מוּם קָבוּעַ לְהֶקְדֵּשָׁן[fn:105], וְנִפְדּוּ, חַיָּבִים בַּבְּכוֹרָה[fn:106] וּבַמַּתָּנוֹת[fn:107], וְיוֹצְאִין לְחֻלִּין[fn:108] לִגָּזֵז וּלְהֵעָבֵד[fn:109], וּוְלָדָן[fn:110] וַחֲלָבָן[fn:111] מֻתָּר לְאַחַר פִּדְיוֹנָן, וְהַשּׁוֹחֲטָן בַּחוּץ[fn:112] פָּטוּר[fn:113], וְאֵין עוֹשִׂים תְּמוּרָה[fn:114], וְאִם מֵתוּ[fn:115] יִפָּדוּ[fn:116], חוּץ[fn:117] מִן הַבְּכוֹר[fn:118] וּמִן הַמַּעֲשֵׂר[fn:119]:[fn:120]
ג
כֹּל שֶׁקָּדַם הֶקְדֵּשָׁן אֶת מוּמָן, אוֹ מוּם עוֹבֵר לְהֶקְדֵּשָׁן, וּלְאַחַר מִכָּאן נוֹלָד לָהֶם מוּם קָבוּעַ (וְנִפְדּוּ), פְּטוּרִין מִן הַבְּכוֹרָה וּמִן הַמַּתָּנוֹת, וְאֵינָן יוֹצְאִין לְחֻלִּין לִגָּזֵז וּלְהֵעָבֵד, וּוְלָדָן וַחֲלָבָן אָסוּר לְאַחַר פִּדְיוֹנָן , וְהַשּׁוֹחֲטָן בַּחוּץ חַיָּב , וְעוֹשִׂין תְּמוּרָה , וְאִם מֵתוּ יִקָּבֵרוּ:
ד
הַמְקַבֵּל צֹאן בַּרְזֶל  מִן הַנָּכְרִי, וְלָדוֹת פְּטוּרִין , וּוַלְדֵי וְלָדוֹת חַיָּבִין. הֶעֱמִיד וְלָדוֹת תַּחַת אִמּוֹתֵיהֶם, וַלְדֵי וְלָדוֹת פְטוּרִין, וּוַלדי וַלְדֵי וְלָדוֹת חַיָּבִין. רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, אֲפִלּוּ עַד עֲשָׂרָה דוֹרוֹת , פְּטוּרִין, שֶׁאַחֲרָיוּתָן לַנָּכְרִי :
ה
רָחֵל שֶׁיָּלְדָה כְּמִין עֵז, וְעֵז שֶׁיָּלְדָה כְּמִין רָחֵל , פָּטוּר מִן הַבְּכוֹרָה. וְאִם יֵשׁ בּוֹ מִקְצָת סִימָנִין , חַיָּב:
ו
רָחֵל שֶׁלֹּא בִכְּרָה וְיָלְדָה שְׁנֵי זְכָרִים וְיָצְאוּ שְׁנֵי רָאשֵׁיהֶן  כְּאֶחָד, רַבִּי יוֹסֵי הַגְּלִילִי אוֹמֵר, שְׁנֵיהֶן לַכֹּהֵן. שֶׁנֶּאֱמַר (שמות יג), הַזְּכָרִים לַה'. וַחֲכָמִים אוֹמְרִים, אִי אֶפְשָׁר , אֶלָּא אֶחָד לוֹ וְאֶחָד לַכֹּהֵן . רַבִּי טַרְפוֹן אוֹמֵר, הַכֹּהֵן בּוֹרֵר לוֹ אֶת הַיָפֶה. רַבִּי עֲקִיבָא אוֹמֵר, מְשַׁמְּנִים בֵּינֵיהֶן, וְהַשֵּׁנִי יִרְעֶה עַד שֶׁיִּסְתָּאֵב. וְחַיָּב בַּמַּתָּנוֹת רַבִּי יוֹסֵי פּוֹטֵר. מֵת אֶחָד מֵהֶן, רַבִּי טַרְפוֹן אוֹמֵר, יַחֲלוֹקוּ. רַבִּי עֲקִיבָא אוֹמֵר, הַמּוֹצִיא מֵחֲבֵרוֹ עָלָיו הָרְאָיָה. זָכָר וּנְקֵבָה, אֵין כָּאן לַכֹּהֵן כְּלוּם:
ז
שְׁתֵּי רְחֵלוֹת שֶׁלֹּא בִכְּרוּ, וְיָלְדוּ שְׁנֵי זְכָרִים, נוֹתֵן שְׁנֵיהֶם לַכֹּהֵן. זָכָר וּנְקֵבָה, הַזָּכָר לַכֹּהֵן. שְׁנֵי זְכָרִים וּנְקֵבָה, אֶחָד לוֹ וְאֶחָד לַכֹּהֵן. רַבִּי טַרְפוֹן אוֹמֵר, הַכֹּהֵן בּוֹרֵר לוֹ אֶת הַיָּפֶה . רַבִּי עֲקִיבָא אוֹמֵר, מְשַׁמְּנִים בֵּינֵיהֶן , וְהַשֵּׁנִי יִרְעֶה עַד שֶׁיִּסְתָּאֵב. וְחַיָּב בַּמַּתָּנוֹת . רַבִּי יוֹסֵי פּוֹטֵר . מֵת אֶחָד מֵהֶן, רַבִּי טַרְפוֹן אוֹמֵר, יַחֲלוֹקוּ  . רַבִּי עֲקִיבָא אוֹמֵר, הַמּוֹצִיא מֵחֲבֵרוֹ עָלָיו הָרְאָיָה. שְׁתֵּי נְקֵבוֹת וְזָכָר, אוֹ שְׁנֵי זְכָרִים וּשְׁתֵּי נְקֵבוֹת, אֵין כָּאן לַכֹּהֵן כְּלוּם :
ח
אַחַת בִּכְּרָה וְאַחַת שֶׁלֹּא בִכְּרָה וְיָלְדוּ שְׁנֵי זְכָרִים, אֶחָד לוֹ וְאֶחָד לַכֹּהֵן . רַבִּי טַרְפוֹן אוֹמֵר, הַכֹּהֵן בּוֹרֵר לוֹ אֶת הַיָּפֶה . רַבִּי עֲקִיבָא אוֹמֵר, מְשַׁמְּנִין בֵּינֵיהֶן, וְהַשֵּׁנִי יִרְעֶה עַד שֶׁיִּסְתָּאֵב. וְחַיָּב בַּמַּתָּנוֹת . רַבִּי יוֹסֵי פּוֹטֵר , שֶׁהָיָה רַבִּי יוֹסֵי אוֹמֵר, כֹּל שֶׁחֲלִיפָיו בְּיַד כֹּהֵן, פָּטוּר מִן הַמַתָּנוֹת. רַבִּי מֵאִיר מְחַיֵּב . מֵת אֶחָד מֵהֶן, רַבִּי טַרְפוֹן אוֹמֵר, יַחֲלוֹקוּ. רַבִּי עֲקִיבָא אוֹמֵר, הַמּוֹצִיא מֵחֲבֵרוֹ עָלָיו הָרְאָיָה. זָכָר וּנְקֵבָה, אֵין כָּאן לַכֹּהֵן כְּלוּם:
ט
יוֹצֵא דֹּפֶן וְהַבָּא אַחֲרָיו , רַבִּי טַרְפוֹן אוֹמִר, שְׁנֵיהֶם יִרְעוּ עַד שֶׁיִּסְתָּאֲבוּ וְיֵאָכְלוּ בְמוּמָן לַבְּעָלִים . רַבִּי עֲקִיבָא אוֹמֵר, שְׁנֵיהֶן אֵינָן בְּכוֹר, הָרִאשׁוֹן מִשּׁוּם שֶׁאֵינוֹ פֶטֶר רֶחֶם, וְהַשֵּׁנִי מִשּׁוּם שֶׁקִּדְּמוֹ אַחֵר  :
פרק שלישי
א
הַלּוֹקֵחַ בְּהֵמָה מִן הַנָּכְרִי וְאֵין יָדוּעַ אִם בִּכְּרָה וְאִם לֹא בִכְּרָה, רַבִּי יִשְׁמָעֵאל אוֹמֵר, עֵז בַּת שְׁנָתָהּ  וַדַּאי לַכֹּהֵן, מִכָּאן וְאֵילָךְ סָפֵק. רָחֵל בַּת שְׁתַּיִם וַדַּאי לַכֹּהֵן, מִכָּאן וְאֵילָךְ סָפֵק. פָּרָה וַחֲמוֹר בְּנוֹת שָׁלשׁ וַדַּאי לַכֹּהֵן, מִכָּאן וְאֵילָךְ סָפֵק . אָמַר לוֹ רַבִּי עֲקִיבָא, אִלּוּ בַּוָּלָד בִּלְבַד בְּהֵמָה נִפְטֶרֶת, הָיָה כִדְבָרֶיךָ, אֶלָּא אָמְרוּ, סִימַן הַוָּלָד בִּבְהֵמָה דַקָּה , טִנוּף. וּבְגַסָּה, שִׁלְיָא. וּבְאִשָּׁה, שְׁפִיר וְשִׁלְיָא. זֶה הַכְּלָל, כֹּל שֶׁיָדוּעַ שֶׁבִּכְּרָה, אֵין כָּאן לַכֹּהֵן כְּלוּם. וְכֹל שֶׁלֹּא בִכְּרָה, הֲרֵי זֶה לַכֹּהֵן. אִם סָפֵק, יֵאָכֵל בְּמוּמוֹ לַבְּעָלִים. רַבִּי אֱלִיעֶזֶר בֶּן יַעֲקֹב אוֹמֵר, בְּהֵמָה גַסָּה שֶׁשָּׁפְעָה חֲרָרַת דָּם, הֲרֵי זוֹ תִקָּבֵר , וְנִפְטְרָה מִן הַבְּכוֹרָה:
ב
רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, הַלּוֹקֵחַ בְּהֵמָה מְנִיקָה  מִן הַנָּכְרִי, אֵינוֹ חוֹשֵׁשׁ שֶׁמָּא בְנָהּ שֶׁל אַחֶרֶת הָיָה. נִכְנַס לְתוֹךְ עֶדְרוֹ וְרָאָה אֶת הַמַּבְכִּירוֹת מְנִיקוֹת וְאֶת שֶׁאֵינָן מַבְכִּירוֹת מְנִיקוֹת, אֵינוֹ חוֹשֵׁשׁ שֶׁמָּא בְנָהּ שֶׁל זוֹ בָּא לוֹ אֵצֶל זוֹ, אוֹ שֶׁמָּא בְנָהּ שֶׁל זוֹ בָּא לוֹ אֵצֶל זוֹ :
ג
רַבִּי יוֹסֵי בֶּן מְשֻׁלָּם אוֹמֵר, הַשּׁוֹחֵט אֶת הַבְּכוֹר, עוֹשֶׂה מָקוֹם בְּקוֹפִיץ  מִכָּאן וּמִכָּאן וְתוֹלֵשׁ הַשֵּׂעָר, וּבִלְבַד שֶׁלֹּא יְזִיזֶנּוּ מִמְּקוֹמוֹ. וְכֵן הַתּוֹלֵשׁ אֶת הַשֵּׂעָר לִרְאוֹת מְקוֹם הַמּוּם  :
ד
שְׂעַר בְּכוֹר בַּעַל מוּם שֶׁנָּשַׁר וְהִנִּיחוֹ בַחַלּוֹן וְאַחַר כָּךְ שְׁחָטוֹ, עֲקַבְיָא בֶּן מַהֲלַלְאֵל מַתִּיר , וַחֲכָמִים אוֹסְרִין , דִּבְרֵי רַבִּי יְהוּדָה. אָמַר רַבִּי יוֹסֵי, לֹא בָזֶה הִתִּיר עֲקַבְיָא , אֶלָּא בִשְׂעַר בְּכוֹר בַּעַל מוּם שֶׁנָּשַׁר וְהִנִּיחוֹ בַּחַלּוֹן וְאַחַר כָּךְ מֵת, בָּזֶה עֲקַבְיָא בֶּן מַהֲלַלְאֵל מַתִּיר, וַחֲכָמִים אוֹסְרִין. הַצֶּמֶר הַמְדֻבְלָל בַּבְּכוֹר , אֶת שֶׁהוּא נִרְאֶה מִן הַגִּזָּה  , מֻתָּר. וְאֶת שֶׁאֵינוֹ נִרְאֶה מִן הַגִּזָּה, אָסוּר :
פרק רביעי
א
עַד כַּמָּה יִשְׂרָאֵל חַיָּבִים לְהִטַּפֵּל בַּבְּכוֹר. בִּבְהֵמָה דַקָּה, עַד שְׁלשִׁים יוֹם. וּבַגַּסָּה, חֲמִשִּׁים יוֹם . רַבִּי יוֹסֵי אוֹמֵר, בַּדַּקָּה שְׁלשָׁה חֳדָשִׁים. אָמַר לוֹ הַכֹּהֵן בְּתוֹךְ זְמַן זֶה תְּנֵהוּ לִי, הֲרֵי זֶה לֹא יִתְּנוֹ לוֹ . אִם הָיָה בַעַל מוּם, אָמַר לוֹ תֶּן לִי שֶׁאוֹכְלֶנּוּ, מֻתָּר . וּבִשְׁעַת הַמִּקְדָּשׁ, אִם הָיָה תָמִים, אָמַר לוֹ תֶּן לִי שֶׁאַקְרִיבֶנּוּ, מֻתָּר. הַבְּכוֹר נֶאֱכָל שָׁנָה בְשָׁנָה בֵּין תָּמִים בֵּין בַּעַל מוּם , שֶׁנֶּאֱמַר (דברים טו), לִפְנֵי ה' אֱלֹהֶיךָ תֹאכְלֶנּוּ שָׁנָה בְשָׁנָה   :
ב
נוֹלַד לוֹ מוּם בְּתוֹךְ שְׁנָתוֹ, מֻתָּר לְקַיְּמוֹ כָּל שְׁנֵים עָשָׂר חֹדֶשׁ . לְאַחַר שְׁנָתוֹ , אֵינוֹ רַשַּׁאי לְקַיְּמוֹ אֶלָּא עַד שְׁלשִׁים יוֹם :
ג
הַשּׁוֹחֵט הַבְּכוֹר  וּמַרְאֶה אֶת מוּמוֹ, רַבִּי יְהוּדָה מַתִּיר. רַבִּי מֵאִיר אוֹמֵר, הוֹאִיל וְהוּא נִשְׁחַט שֶׁלֹּא עַל פִּי מֻמְחֶה, אָסוּר :
ד
מִי שֶׁאֵינוֹ מֻמְחֶה  וְרָאָה אֶת הַבְּכוֹר וְנִשְׁחַט עַל פִּיו, הֲרֵי זֶה יִקָּבֵר , וִישַׁלֵּם מִבֵּיתוֹ . דָּן אֶת הַדִּין, זִכָּה אֶת הַחַיָּב וְחִיֵּב אֶת הַזַּכַּאי, טִמֵּא אֶת הַטָהוֹר וְטִהֵר אֶת הַטָּמֵא, מַה שֶּׁעָשָׂה עָשׂוּי  וִישַׁלֵּם מִבֵּיתוֹ  . וְאִם הָיָה מֻמְחֶה לְבֵית דִּין, פָּטוּר מִלְּשַׁלֵּם . מַעֲשֶׂה בְפָרָה שֶׁנִּטְּלָה הָאֵם שֶׁלָּהּ, וְהֶאֱכִילָהּ רַבִּי טַרְפוֹן לַכְּלָבִים, וּבָא מַעֲשֶׂה לִפְנֵי חֲכָמִים וְהִתִּירוּהָ. אָמַר תוֹדוֹס הָרוֹפֵא, אֵין פָּרָה וַחֲזִירָה יוֹצְאָה מֵאֲלֶכְּסַנְדְּרִיָּא עַד שֶׁהֵם חוֹתְכִין אֶת הָאֵם שֶׁלָּהּ, בִּשְׁבִיל שֶׁלֹּא תֵלֵד . אָמַר רַבִּי טַרְפוֹן, הָלְכָה חֲמוֹרְךָ טַרְפוֹן. אָמַר לוֹ רַבִּי עֲקִיבָא, רַבִּי טַרְפוֹן, פָּטוּר אַתָּה, שֶׁאַתָּה מֻמְחֶה לְבֵית דִּין, וְכָל הַמֻּמְחֶה לְבֵית דִּין פָּטוּר מִלְּשַׁלֵּם :
ה
הַנּוֹטֵל שְׂכָרוֹ לִהְיוֹת רוֹאֶה בְכוֹרוֹת, אֵין שׁוֹחֲטִין עַל פִּיו , אֶלָּא אִם כֵּן הָיָה מֻמְחֶה כְּאִילָא בְיַבְנֶה  , שֶׁהִתִּירוּ לוֹ חֲכָמִים לִהְיוֹת נוֹטֵל אַרְבָּעָה אִסָּרוֹת בִּבְהֵמָה דַקָּה, וְשִׁשָּׁה בַּגַּסָּה , בֵּין תָּמִים בֵּין בַּעַל מוּם :
ו
הַנּוֹטֵל שְׂכָרוֹ לָדוּן , דִּינָיו בְּטֵלִים. לְהָעִיד , עֵדוּתָיו בְּטֵלִין. לְהַזּוֹת וּלְקַדֵּשׁ, מֵימָיו מֵי מְעָרָה וְאֶפְרוֹ אֵפֶר מִקְלֶה. אִם הָיָה כֹהֵן וְטִמְּאָהוּ מִתְּרוּמָתוֹ , מַאֲכִילוֹ וּמַשְׁקוֹ וְסָכוֹ. וְאִם הָיָה זָקֵן, מַרְכִּיבוֹ עַל הַחֲמוֹר. וְנוֹתֵן לוֹ שְׂכָרוֹ כַּפּוֹעֵל:
ז
הֶחָשׁוּד עַל הַבְּכוֹרוֹת , אֵין לוֹקְחִין מִמֶּנּוּ בְּשַׂר צְבָאִים  וְלֹא עוֹרוֹת שֶׁאֵינָן עֲבוּדִין . רַבִּי אֱלִיעֶזֶר אוֹמֵר, לוֹקְחִים מִמֶּנּוּ עוֹרוֹת שֶׁל נְקֵבָה  , וְאֵין לוֹקְחִין מִמֶּנּוּ צֶמֶר מְלֻּבָּן וְצוֹאִי , אֲבָל לוֹקְחִין מִמֶּנּוּ טָווּי וּבְגָדִים :
ח
הֶחָשׁוּד עַל הַשְׁבִיעִית  אֵין לוֹקְחִין מִמֶּנּוּ פִשְׁתָּן וַאֲפִלּוּ סֶרֶק, אֲבָל לוֹקְחִין מִמֶּנּוּי טָווּי  וְאָרִיג :
ט
הֶחָשׁוּד לִהְיוֹת מוֹכֵר תְּרוּמָה לְשֵׁם חֻלִּין , אֵין לוֹקְחִין מִמֶּנּוּ אֲפִלּוּ מַיִם אוֹ מֶלַח , דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי שִׁמְעוֹן אוֹמֵר, כּל שֶׁיֵּשׁ בּוֹ זִקַּת תְּרוּמוֹת וּמַעַשְׂרוֹת , אֵין לוֹקְחִין מִמֶּנּוּ:
י
הֶחָשׁוּד עַל הַשְּׁבִיעִית, אֵינוֹ חָשׁוּד עַל הַמַּעַשְׂרוֹת. הֶחָשׁוּד עַל הַמַּעַשְׂרוֹת , אֵינוֹ חָשׁוּד עַל הַשְּׁבִיעִית  . הֶחָשׁוּד עַל זֶה וְעַל זֶה, חָשׁוּד עַל הַטָּהֳרוֹת . וְיֵשׁ שֶׁהוּא חָשׁוּד עַל הַטָּהֳרוֹת, וְאֵינוֹ חָשׁוּד לֹא עַל זֶה וְלֹא עַל זֶה. זֶה הַכְּלָל, כָּל הֶחָשׁוּד עַל הַדָּבָר, לֹא דָנוֹ וְלֹא מְעִידוֹ :
פרק חמישי
א
כָּל פְּסוּלֵי הַמֻּקְדָּשִׁין (הֲנָאָתָן לַהֶקְדֵּשׁ), נִמְכָּרִין בָּאִטְלִיז (וְנִשְׁחָטִין בָּאִטְלִיז) וְנִשְׁקָלִין בְּלִטְרָא, חוּץ מִן הַבְּכוֹר וּמִן הַמַּעֲשֵׂר  , שֶׁהֲנָיָתָן לַבְּעָלִים . פְּסוּלֵי הַמֻּקְדָּשִׁין הֲנָיָתָן לַהֶקְדֵּשׁ . וְשׁוֹקְלִין מָנֶה כְנֶגֶד מָנֶה בַּבְּכוֹר :
ב
בֵית שַׁמַּאי אוֹמְרִים, לֹא יִמָּנָה  יִשְׂרָאֵל עִם הַכֹּהֵן עַל הַבְּכוֹר. בֵּית הִלֵּל מַתִּירִין, וַאֲפִלּוּ נָכְרִי.  בְּכוֹר שֶׁאֲחָזוֹ דָם , אֲפִלּוּ הוּא מֵת, אֵין מַקִּיזִין לוֹ דָם, דִּבְרֵי רַבִּי יְהוּדָה . וַחֲכָמִים אוֹמְרִים, יַקִּיז, וּבִלְבַד שֶׁלֹּא יַעֲשֶׂה בוֹ מוּם  . וְאִם עָשָׂה בוֹ מוּם, הֲרֵי זֶה לֹא יִשָּׁחֵט עָלָיו . רַבִּי שִׁמְעוֹן אוֹמֵר יַקִּיז, אַף עַל פִּי שֶׁהוּא עוֹשֶׂה בוֹ מוּם :
ג
הַצּוֹרֵם בְּאֹזֶן  הַבְּכוֹר, הֲרֵי זֶה לֹא יִשָּׁחֵט עוֹלָמִית , דִּבְרֵי רַבִּי אֱלִיעֶזֶר. וַחֲכָמִים אוֹמְרִים, כְּשֶׁיִּוָּלֵד לוֹ מוּם אַחֵר , יִשָּׁחֵט עָלָיו . מַעֲשֶׂה בְזָכָר שֶׁל רְחֵלִים זָקֵן וּשְׂעָרוֹ מְדֻלְדָּל,  רָאָהוּ קַסְדּוֹר אֶחָד , אָמַר, מַה טִּיבוֹ שֶׁל זֶה. אָמְרוּ לוֹ, בְּכוֹר הוּא וְאֵינוֹ נִשְׁחָט אֶלָּא אִם כֵּן הָיָה בּוֹ מוּם. נָטַל פִּגְיוֹן וְצָרַם בְּאָזְנוֹ, וּבָא מַעֲשֶׂה לִפְנֵי חֲכָמִים וְהִתִּירוּהוּ. רָאָה שֶׁהִתִּירוּ, וְהָלַךְ וְצָרַם בְּאָזְנֵי בְכוֹרוֹת אֲחֵרִים, וְאָסָרוּ . פַּעַם אַחַת הָיוּ תִינוֹקוֹת מְשַׂחֲקִין  בַּשָּׂדֶה וְקָשְׁרוּ זַנְבוֹת טְלָאִים זֶה לָזֶה, וְנִפְסְקָה זְנָבוֹ שֶׁל אֶחָד מֵהֶם וַהֲרֵי הוּא בְכוֹר, וּבָא מַעֲשֶׂה לִפְנֵי חֲכָמִים וְהִתִּירוּהוּ. רָאוּ שֶׁהִתִּירוּ, וְהָלְכוּ וְקָשְׁרוּ זַנְבוֹת בְּכוֹרוֹת אֲחֵרִים, וְאָסָרוּ. זֶה הַכְּלָל, כֹּל שֶׁהוּא לְדַעְתּוֹ, אָסוּר. וְשֶׁלֹּא לְדַעְתּוֹ, מֻתָּר:
ד
הָיָה בְכוֹר רוֹדְפוֹ, וּבְעָטוֹ וְעָשָׂה בוֹ מוּם , הֲרֵי זֶה יִשְׁחוֹט עָלָיו. כָּל הַמּוּמִין הָרְאוּיִין לָבוֹא בִידֵי אָדָם, רוֹעִים יִשְׂרָאֵל נֶאֱמָנִים , וְרוֹעִים כֹּהֲנִים אֵינָן נֶאֱמָנִים . רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, נֶאֱמָן הוּא עַל שֶׁל חֲבֵרוֹ וְאֵינוֹ נֶאֱמָן עַל שֶׁל עַצְמוֹ. רַבִּי מֵאִיר אוֹמֵר, הֶחָשׁוּד עַל דָּבָר, לֹא דָנוֹ וְלֹא מְעִידוֹ:
ה
נֶאֱמָן הַכֹּהֵן לוֹמַר הֶרְאֵיתִי בְּכוֹר זֶה וּבַעַל מוּם הוּא . הַכּל נֶאֱמָנִים עַל מוּמֵי הַמַּעֲשֵׂר  . בְּכוֹר שֶׁנִּסְמֵית עֵינוֹ, שֶׁנִּקְטְעָה יָדוֹ, שֶׁנִּשְׁבְּרָה רַגְלוֹ , הֲרֵי זֶה יִשָּׁחֵט עַל פִּי שְׁלשָׁה בְנֵי הַכְּנֶסֶת  , רַבִּי יוֹסֵי אוֹמֵר, אֲפִלּוּ יֵשׁ שָׁם עֶשְׂרִים וּשְׁלשָׁה, לֹא יִשָּׁחֵט אֶלָּא עַל פִּי מֻמְחֶה :
ו
הַשּׁוֹחֵט אֶת הַבְּכוֹר (וּמְכָרוֹ) וְנוֹדַע שֶׁלֹּא הֶּרְאָהוּ, מַה שֶּׁאָכְלוּ אָכְלוּ וְהוּא  יַחֲזִיר לָהֶם אֶת הַדָּמִים . וּמַה שֶׁלֹּא אָכְלוּ, הַבָּשָׂר יִקָּבֵר וְהוּא יַחֲזִיר לָהֶם אֶת הַדָּמִים. וְכֵן הַשּׁוֹחֵט אֶת הַפָּרָה וּמְכָרָהּ וְנוֹדַע שֶׁהִיא טְרֵפָה, מַה שֶׁאָכְלוּ אָכְלוּ וְיַחֲזִיר לָהֶם אֶת הַדָּמִים. וּמַה שֶּׁלֹּא אָכְלוּ, הֵן יַחֲזִירוּ לוֹ אֶת הַבָּשָׂר וְהוּא יַחֲזִיר לָהֶם אֶת הַדָּמִים. מְכָרוּהוּ לַנָּכְרִים אוֹ הִטִּילוּהוּ לַכְּלָבִים, יְשַׁלְּמוּ לוֹ דְמֵי הַטְּרֵפָה :
פרק ששי
א
עַל אֵלּוּ מוּמִין שׁוֹחֲטִין  אֶת הַבְּכוֹר , נִפְגְּמָה אָזְנוֹ מִן הַסְּחוּס, אֲבָל לֹא מִן הָעוֹר, נִסְדְּקָה אַף עַל פִּי שֶׁלֹּא חָסְרָה, נִקְּבָה מְלֹא כַרְשִׁינָה, אוֹ שֶׁיָּבָשָׁה. אֵיזוֹ הִיא יְבֵשָׁה, כֹּל שֶׁתִּנָּקֵב וְאֵינָהּ מוֹצִיאָה טִפַּת דָּם. רַבִּי יוֹסֵי בֶּן מְשֻׁלָּם אוֹמֵר, יְבֵשָׁה, שֶׁתְּהֵא נִפְרָכֶת:
ב
רִיס שֶׁל עַיִן שֶׁנִּקַּב, שֶׁנִּפְגַּם, שֶׁנִּסְדַּק, הֲרֵי בְעֵינָיו דַּק, תְּבַלּוּל, חִלָּזוֹן נָחָשׁ, וְעֵנָב. וְאֵיזֶהוּ תְּבַלּוּל, לָבָן הַפוֹסֵק בַּסִּירָא וְנִכְנָס בַּשָּׁחוֹר. בַּשָּׁחוֹר וְנִכְנָס בַּלָּבָן, אֵינוֹ מוּם, שֶׁאֵין מוּמִים בַּלָּבָן:
ג
חֲוַרְוָד וְהַמַּיִם הַקְּבוּעִים. אֵיזֶהוּ חֲוַרְוָד הַקָּבוּעַ, כֹּל שֶׁשָּׁהָה שְׁמוֹנִים יוֹם. רַבִּי חֲנִינָא בֶּן אַנְטִיגְנוֹס אוֹמֵר, בּוֹדְקִין אוֹתוֹ שְׁלשָׁה פְעָמִים בְּתוֹךְ שְׁמוֹנִים יוֹם. וְאֵלּוּ הֵם מַיִם הַקְּבוּעִים, אָכַל לַח וְיָבֵשׁ שֶׁל גְּשָׁמִים, לַח וְיָבֵשׁ שֶׁל שְׁלָחִים. אָכַל הַיָּבֵשׁ וְאַחַר כָּךְ אָכַל הַלַּח, אֵינוֹ מוּם, עַד שֶׁיֹּאכַל הַיָּבֵשׁ אַחַר הַלַּח:
ד
חָטְמוֹ שֶׁנִּקַּב, שֶׁנִּפְגַּם, שֶׁנִּסְדַּק, שְׂפָתוֹ שֶׁנִּקְּבָה, שֶׁנִּפְגְּמָה, שֶׁנִּסְדְּקָה, חִטָּיו הַחִיצוֹנוֹת שֶׁנִּפְגְּמוּ אוֹ שֶׁנִּגְמְמוּ, וְהַפְנִימִיּוֹת שֶׁנֶּעֱקָרוּ. רַבִּי חֲנִינָא בֶּן אַנְטִיגְנוֹס אוֹמֵר, אֵין בּוֹדְקִין מִן הַמַּתְאִימוֹת וְלִפְנִים, אַף לֹא אֶת הַמַתְאִימוֹת:
ה
נִפְגַּם הַזּוֹבָן, אוֹ עֶרְיָה שֶׁל נְקֵבָּה בַּמֻּקְדָּשִׁים, נִפְגַּם הַזָּנָב מִן הָעֶצֶם, אֲבָל לֹא מִן הַפֶּרֶק, אוֹ שֶׁהָיָה רֹאשׁ הַזָּנָב מַפְצִיל עֶצֶם, אוֹ שֶׁיֵּשׁ (בָּשָׂר) בֵּין חֻלְיָא לְחֻלְיָא מְלֹא אֶצְבַּע:
ו
אֵין לוֹ בֵיצִים, (אוֹ) אֵין לוֹ אֶלָּא בֵּיצָה אֶחָת. רַבִּי יִשְׁמָעֵאל אוֹמֵר, אִם יֵשׁ לוֹ שְׁנֵי כִיסִין, יֵשׁ לוֹ שְׁתֵּי בֵיצִים. אֵין לוֹ אֶלָּא כִיס אֶחָד, אֵין לוֹ אֶלָּא בֵיצָה אֶחָת. רַבִּי עֲקִיבָא אוֹמֵר, מוֹשִׁיבוֹ עַל עַכּוּזוֹ וּמְמַעֵךְ, אִם יֵשׁ שָׁם בֵּיצָה, סוֹפָהּ לָצֵאת. מַעֲשֶׂה שֶׁמִּעֵךְ וְלֹא יָצָאת, וְנִשְׁחַט וְנִמְצֵאת דְּבוּקָה בַּכְּסָלִים, וְהִתִּיר רַבִּי עֲקִיבָא וְאָסַר רַבִּי יוֹחָנָן בֶּן נוּרִי:
ז
בַּעַל חָמֵשׁ רַגְלַיִם, אוֹ שֶׁאֵין לוֹ אֶלָּא שָׁלשׁ, וְשֶׁרַגְלָיו קְלוּטוֹת כְּשֶׁל חֲמוֹר, וְהַשָּׁחוּל, וְהַכָּסוּל. אֵיזֶהוּ שָׁחוּל, שֶׁנִּשְׁמְטָה יְרֵכוֹ. וְכָסוּל, שֶׁאַחַת מִיַּרְכוֹתָיו גְּבוֹהָה:
ח
נִשְׁבַּר עֶצֶם יָדוֹ, וְעֶצֶם רַגְלוֹ, אַף עַל פִּי שֶׁאֵינוֹ נִכָּר. מוּמִין אֵלּוּ מָנָה אִילָא בְיַבְנֶה, וְהוֹדוּ לוֹ חֲכָמִים. וְעוֹד שְׁלשָׁה הוֹסִיף. אָמְרוּ לוֹ, לֹא שָׁמַעְנוּ אֶת אֵלּוּ. אֵת שֶׁגַּלְגַּל עֵינוֹ עָגוֹל כְּשֶׁל אָדָם, וּפִיו דּוֹמֶה לְשֶׁל חֲזִיר, וְשֶׁנִּטַּל רֹב הַמְדַבֵּר שֶׁל לְשׁוֹנוֹ. וּבֵית דִּין שֶׁל אַחֲרֵיהֶן אָמְרוּ, הֲרֵי אֵלּוּ מוּמִין:
ט
מַעֲשֶׂה שֶׁהַלְּחִי הַתַּחְתּוֹן עוֹדֵף עַל הָעֶלְיוֹן, וְשָׁלַח רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל לַחֲכָמִים וְאָמְרוּ, הֲרֵי זֶה מוּם. אֹזֶן הַגְּדִי שֶׁהָיְתָה כְפוּלָה, אָמְרוּ חֲכָמִים, בִּזְמַן שֶׁהִיא עֶצֶם אֶחָד, מוּם. וְאִם אֵינָהּ עֶצֶם אֶחָד, אֵינָהּ מוּם. רַבִּי חֲנַנְיָא בֶן גַּמְלִיאֵל אוֹמֵר, זְנַב הַגְּדִי שֶׁהִיא דוֹמָה לְשֶׁל חֲזִיר, וְשֶׁאֵין בָּהּ שָׁלשׁ חֻלְיוֹת, הֲרֵי זֶה מוּם:
י
רַבִּי חֲנִינָא בֶּן אַנְטִיגְנוֹס אוֹמֵר, אֶת שֶׁיַּבֶּלֶת בְּעֵינוֹ, וְשֶׁנִּפְגַּם עֶצֶם יָדוֹ, וְעֶצֶם רַגְלוֹ, וְשֶׁנִּפְסַק עַצְמוֹ שֶׁבְּפִיו. עֵינוֹ אַחַת גְּדוֹלָה וְאַחַת קְטַנָּה, אָזְנוֹ אַחַת גְּדוֹלָה וְאַחַת קְטַנָּה, בְּמַרְאֶה אֲבָל לֹא בְמִדָּה. רַבִּי יְהוּדָה אוֹמֵר, אַחַת מִבֵּיצָיו גְּדוֹלָה כִּשְׁתַּיִם בַּחֲבֶרְתָּהּ, וְלֹא הוֹדוּ לוֹ חֲכָמִים:
יא
זְנַב הָעֶגֶל שֶׁאֵינָהּ מַגַּעַת לָעַרְקוֹב, אָמְרוּ חֲכָמִים, כָּל מַרְבִּית הָעֲגָלִים כֵּן, כָּל זְמַן שֶׁהֵן מַגְדִּילִין הֵם נִמְתָּחוֹת. לְאֵיזֶה עַרְקוֹב אָמְרוּ, רַבִּי חֲנִינָא בֶּן אַנְטִיגְנוֹס אוֹמֵר, לָעַרְקוֹב שֶׁבְּאֶמְצַע הַיָּרֵךְ. עַל אֵלּוּ  מוּמִין שׁוֹחֲטִין אֶת הַבְּכוֹר, וּפְסוּלֵי הַמֻּקְדָּשִׁין נִפְדִּין עֲלֵיהֶן:
יב
אֵלּוּ שֶׁאֵין שׁוֹחֲטִין עֲלֵיהֶן  לֹא בַמִּקְדָּשׁ וְלֹא בַמְּדִינָה, חֲוַרְוָד וְהַמַּיִם שֶׁאֵינָם קְבוּעִין, וְחִטָּיו הַפְּנִימִיּוֹת שֶׁנִּפְגְּמוּ, (אֲבָל לֹא) שֶׁנֶּעֶקְרוּ, וּבַעַל גָּרָב, וּבַעַל יַבֶּלֶת, וּבַעַל חֲזָזִית, וְזָקֵן, וְחוֹלֶה, וּמְזֻהָם, וְשֶׁנֶּעֶבְדָה בוֹ עֲבֵרָה, וְשֶׁהֵמִית אֶת הָאָדָם (עַל פִּי עֵד אֶחָד אוֹ עַל פִּי הַבְּעָלִים) , וְטֻמְטוּם, וְאַנְדְּרוֹגִינוֹס, לֹא בַמִּקְדָּשׁ וְלֹא בַמְּדִינָה . רַבִּי יִשְׁמָעֵאל אוֹמֵר, אֵין מוּם גָּדוֹל מִזֶּה  . וַחֲכָמִים אוֹמְרִים, אֵינוֹ בְכוֹר, אֶלָּא נִגְזָז וְנֶעֱבָד :
פרק שביעי
א
מוּמִין אֵלּוּ, בֵּין קְבוּעִין בֵּין עוֹבְרִין, פּוֹסְלִין בָּאָדָם. יוֹתֵר עֲלֵיהֶן  בָּאָדָם , הַכִּילוֹן, וְהַלַּפְתָּן, הַמַּקָּבָן, וְשֶׁרֹאשׁוֹ שָׁקוּעַ, וּשְׁקִיפָס. וּבַעֲלֵי הַחֲטוֹטֶרֶת, רַבִּי יְהוּדָה מַכְשִׁיר, וַחֲכָמִים פּוֹסְלִין:
ב
הַקֵּרֵחַ, פָּסוּל. אֵיזֶהוּ קֵרֵחַ, כֹּל שֶׁאֵין לוֹ שִׁטָּה שֶׁל שֵׂעָר מַקֶּפֶת מֵאֹזֶן לְאֹזֶן. וְאִם יֵשׁ לוֹ, הֲרֵי זֶה כָּשֵׁר. אֵין לוֹ גְבִּינִים, אֵין לוֹ אֶלָּא גְבִין אֶחָד, הוּא גִבֵּן הָאָמוּר בַּתּוֹרָה. רַבִּי דוֹסָא אוֹמֵר, כֹּל שֶׁגְּבִּינָיו שׁוֹכְבִין. רַבִּי חֲנִינָא בֶן אַנְטִיגְנוֹס אוֹמֵר, כֹּל שֶׁיֵּשׁ לוֹ שְׁנֵי גַבִּים וּשְׁתֵּי שִׁדְרָאוֹת:
ג
הֶחָרוּם, פָּסוּל. אֵיזֶהוּ חָרוּם, הַכּוֹחֵל שְׁתֵּי עֵינָיו כְּאֶחָת. שְׁתֵּי עֵינָיו לְמַעְלָה, וּשְׁתֵּי עֵינָיו לְמַטָּה, עֵינוֹ אַחַת לְמַעְלָה, וְעֵינוֹ אַחַת לְמַטָּה, רוֹאֶה אֶת הַחֶדֶר וְאֶת הָעֲלִיָּה כְּאֶחָת, סָכֵי שֶׁמֶשׁ, זוּגְדוֹס, וְהַצִּירָן. וְשֶׁנָּשְׁרוּ רִיסֵי עֵינָיו, פָּסוּל, מִפְּנֵי מַרְאִית הָעָיִן:
ד
עֵינָיו גְּדוֹלוֹת כְּשֶׁל עֵגֶל, אוֹ קְטַנּוֹת כְּשֶׁל אַוָּז, גּוּפוֹ גָּדוֹל מֵאֵבָרָיו אוֹ קָטָן מֵאֵבָרָיו, חָטְמוֹ גָּדוֹל מֵאֵבָרָיו אוֹ קָטָן מֵאֵבָרָיו, הַצִּמֵּם, וְהַצִּמֵּעַ. אֵיזֶה הוּא צִמֵּעַ, שֶׁאָזְנָיו קְטַנּוֹת. וְהַצִּמֵּם, שֶׁאָזְנָיו דּוֹמוֹת לִסְפוֹג:
ה
שְׂפָתוֹ הָעֶלְיוֹנָה עוֹדֶפֶת עַל הַתַּחְתּוֹנָה, וְהַתַּחְתּוֹנָה עוֹדֶפֶת עַל הָעֶלְיוֹנָה, הֲרֵי זֶה מוּם. וְשֶׁנִּטְּלוּ שִׁנָּיו, פָּסוּל, מִפְּנֵי מַרְאִית הָעָיִן. דַּדָּיו שׁוֹכְבִים כְּשֶׁל אִשָּׁה, כְּרֵסוֹ צָבָה, טַבּוּרוֹ יוֹצֵא, נִכְפֶּה אֲפִלּוּ אַחַת לְיָמִים, רוּחַ קַצְרִית בָּאָה עָלָיו, הַמְאֻשְׁכָּן, וּבַעַל גֶּבֶר. אֵין לוֹ בֵיצִים, אוֹ אֵין לוֹ אֶלָּא בֵיצָה אַחַת, זֶהוּ מְרוֹחַ אָשֶׁךְ הָאָמוּר בַּתּוֹרָה. רַבִּי יִשְׁמָעֵאל אוֹמֵר, כּל שֶׁנִּמְרְחוּ אֲשָׁכָיו. רַבִּי עֲקִיבָא אוֹמֵר, כּל שֶׁרוּחַ בַּאֲשָׁכָיו. רַבִּי חֲנִינָא בֶּן אַנְטִיגְנוֹס אוֹמֵר, כֹּל שֶׁמַּרְאָיו חֲשׁוּכִין:
ו
הַמַּקִּישׁ בְּקַרְסֻלָּיו, וּבְאַרְכּוּבוֹתָיו, וּבַעַל פִּיקָה, וְהָעִקֵּל. אֵיזֶהוּ עִקֵּל, כֹּל שֶׁמַּקִּיף פַּרְסוֹתָיו וְאֵין אַרְכּוּבוֹתָיו נוֹשְׁקוֹת זוֹ לָזוֹ. פִּיקָה יוֹצְאָה מִגּוּדָלוֹ, עֲקֵבוֹ יוֹצֵא לַאֲחוֹרָיו, פַּרְסָתוֹ רְחָבָה כְּשֶׁל אַוָּז. אֶצְבְּעוֹתָיו מֻרְכָּבוֹת זוֹ עַל זוֹ, אוֹ קְלוּטוֹת (לְמַעְלָה) עַד הַפֶּרֶק, כָּשֵׁר. לְמַטָּה מִן הַפֶּרֶק וַחֲתָכָהּ, כָּשֵׁר. הָיְתָה בוֹ יְתֶרֶת וַחֲתָכָהּ, אִם יֵשׁ בָּהּ עֶצֶם, פָּסוּל. וְאִם לָאו, כָּשֵׁר. יָתֵר בְּיָדָיו וּבְרַגְלָיו שֵׁשׁ וָשֵׁשׁ עֶשְׂרִים וְאַרְבַּע, רַבִּי יְהוּדָה מַכְשִׁיר, וַחֲכָמִים פּוֹסְלִים. הַשּׁוֹלֵט בִּשְׁתֵּי יָדָיו, רַבִּי פּוֹסֵל, וַחֲכָמִים מַכְשִׁירִים. הַכּוּשִׁי, וְהַגִּיחוֹר, וְהַלַּבְקָן, וְהַקִּפֵּחַ, וְהַנַּנָּס, וְהַחֵרֵשׁ, וְהַשּׁוֹטֶה, וְהַשִּׁכּוֹר, וּבַעֲלֵי נְגָעִים טְהוֹרִין, פְּסוּלִין בָּאָדָם, וּכְשֵׁרִין בַּבְּהֵמָה. רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, שׁוֹטָה בַבְּהֵמָה אֵינָהּ מִן הַמֻּבְחָר, רַבִּי אֱלִיעֶזֶר אוֹמֵר, אַף בַּעֲלֵי דִלְדּוּלִין, פְּסוּלִין בָּאָדָם , וּכְשֵׁרִין בַּבְּהֵמָה:
ז
אֵלּוּ כְּשֵׁרִין בָּאָדָם, וּפְסוּלִין בַּבְּהֵמָה, אוֹתוֹ וְאֶת בְּנוֹ , וּטְרֵפָה, וְיוֹצֵא דֹפֶן, (וְשֶׁנֶּעֶבְדָה בָהֶן עֲבֵרָה, וְשֶׁהֵמִית אֶת הָאָדָם ).  הַנּוֹשֵׂא נָשִׁים בַּעֲבֵרָה , פָּסוּל, עַד שֶׁיַּדִּיר הֲנָיָה. הַמִּטַּמֵּא לַמֵּתִים , פָּסוּל, עַד שֶׁיְּקַבֵּל עָלָיו שֶׁלֹּא יְהֵא מִטַּמֵּא לַמֵּתִים:
פרק שמיני
א
יֵשׁ בְּכוֹר לַנַּחֲלָה וְאֵינוֹ בְכוֹר לַכֹּהֵן, בְּכוֹר לַכֹּהֵן וְאֵינוֹ בְכוֹר לַנַּחֲלָה, בְּכוֹר לַנַּחֲלָה וְלַכֹּהֵן, יֵשׁ שֶׁאֵינוֹ בְכוֹר לֹא לַנַּחֲלָה וְלֹא לַכֹּהֵן . אֵיזֶהוּ בְּכוֹר לַנַּחֲלָה וְאֵינוֹ בְכוֹר לַכֹּהֵן , הַבָּא אַחַר הַנְּפָלִים  שֶׁיָּצָא רֹאשׁוֹ חַי   , וּבֶן תִּשְׁעָה  שֶׁיָּצָא רֹאשׁוֹ מֵת , וְהַמַּפֶּלֶת כְּמִין בְּהֵמָה חַיָּה וָעוֹף  , דִּבְרֵי רַבִּי מֵאִיר. וַחֲכָמִים אוֹמְרִים, עַד שֶׁיְּהֵא בוֹ מִצּוּרַת  הָאָדָם . הַמַּפֶּלֶת סַנְדָּל , אוֹ שִׁלְיָא  , וּשְׁפִיר מְרֻקָּם , וְהַיּוֹצֵא מְחֻתָּךְ ,  הַבָּא אַחֲרֵיהֶן, בְּכוֹר לַנַּחֲלָה וְאֵינוֹ בְכוֹר לַכֹּהֵן. מִי שֶׁלֹּא הָיוּ לוֹ בָנִים וְנָשָׂא אִשָּׁה שֶׁכְּבָר יָלְדָה , עוֹדָהּ שִׁפְחָה  וְנִשְׁתַּחְרְרָה, עוֹדָהּ נָכְרִית וְנִתְגַּיְּרָה, מִשֶּׁבָּאת לְיִשְׁרָאֵל יָלְדָה, בְּכוֹר לַנַּחֲלָה  וְאֵינוֹ בְכוֹר לַכֹּהֵן . רַבִּי יוֹסֵי הַגְּלִילִי אוֹמֵר, בְּכוֹר לַנַּחֲלָה וְלַכֹּהֵן, שֶׁנֶּאֱמַר (שמות יג), פֶּטֶר כָּל רֶחֶם בִּבְנֵי יִשְׂרָאֵל, עַד שֶׁיִּפְטְרוּ רֶחֶם מִיִּשְׂרָאֵל. מִי שֶׁהָיוּ לוֹ בָנִים וְנָשָׂא אִשָּׁה שֶׁלֹא יָלְדָה, נִתְגַּיְּרָה מְעֻבֶּרֶת, נִשְׁתַּחְרְרָה מְעֻבֶּרֶת, יָלְדָה הִיא וְכֹהֶנֶת , הִיא וּלְוִיָּה, הִיא וְאִשָּׁה שֶׁכְּבָר יָלְדָה , וְכֵן מִי שֶׁלֹּא שָׁהֲתָה אַחַר בַּעְלָהּ שְׁלשָׁה חֳדָשִׁים וְנִשֵּׂאת וְיָלְדָה, וְאֵין יָדוּעַ אִם בֶּן תִּשְׁעָה לָרִאשׁוֹן, אוֹ בֶן שִׁבְעָה לָאַחֲרוֹן, בְּכוֹר לַכֹּהֵן  וְאֵינוֹ בְכוֹר לַנַּחֲלָה . אֵיזֶהוּ בְּכוֹר לַנַּחֲלָה וְלַכֹּהֵן, הַמַּפֶּלֶת שְׁפִיר מָלֵא דָם, מָלֵא מַיִם, מָלֵא גְנִינִים, הַמַּפֶּלֶת כְּמִין דָּגִים וַחֲגָבִים שְׁקָצִים וּרְמָשִׂים, הַמַּפֶּלֶת יוֹם אַרְבָּעִים, הַבָּא אַחֲרֵיהֶן, בְּכוֹר לַנַּחֲלָה וְלַכֹּהֵן:
ב
יוֹצֵא דֹפֶן וְהַבָּא אַחֲרָיו , שְׁנֵיהֶם אֵינָן בְּכוֹר לֹא לַנַּחֲלָה וְלֹא לַכֹּהֵן . רַבִּי שִׁמְעוֹן אוֹמֵר , הָרִאשׁוֹן לַנַּחֲלָה , וְהַשֵּׁנִי לְחָמֵשׁ סְלָעִים :
ג
מִי שֶׁלֹּא בִכְּרָה אִשְׁתּוֹ וְיָלְדָה שְׁנֵי זְכָרִים , נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן . מֵת אֶחָד מֵהֶן בְּתוֹךְ שְׁלשִׁים יוֹם, הָאָב פָּטוּר . מֵת הָאָב וְהַבָּנִים קַיָּמִים, רַבִּי מֵאִיר אוֹמֵר, אִם נָתְנוּ עַד שֶׁלֹּא חָלְקוּ , נָתָנוּ . וְאִם לָאו, פְּטוּרִין. רַבִּי יְהוּדָה אוֹמֵר נִתְחַיְּבוּ נְכָסִים . זָכָר וּנְקֵבָה, אֵין כָּאן לַכֹּהֵן כְּלוּם:
ד
שְׁתֵּי נָשִׁים שֶׁלֹּא בִכְּרוּ וְיָלְדוּ שְׁנֵי זְכָרִים, נוֹתֵן עֶשֶׂר סְלָעִים לַכֹּהֵן. מֵת אֶחָד מֵהֶן בְּתוֹךְ שְׁלשִׁים יוֹם , אִם לְכֹהֵן אֶחָד נָתַן, יַחֲזִיר לוֹ חָמֵשׁ סְלָעִים. אִם לִשְׁנֵי כֹהֲנִים נָתַן, אֵינוֹ יָכוֹל לְהוֹצִיא מִיָּדָם. זָכָר וּנְקֵבָה אוֹ שְׁנֵי זְכָרִים וּנְקֵבָה, נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן. שְׁתֵּי נְקֵבוֹת וְזָכָר אוֹ שְׁנֵי זְכָרִים וּשְׁתֵּי נְקֵבוֹת, אֵין כָּאן לַכֹּהֵן כְּלוּם. אַחַת בִּכְּרָה וְאַחַת שֶׁלֹּא בִכְּרָה וְיָלְדוּ שְׁנֵי זְכָרִים. נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן. מֵת אֶחָד מֵהֶן בְּתוֹךְ שְׁלשִׁים יוֹם, הָאָב  פָּטוּר. מֵת הָאָב וְהַבָּנִים קַיָּמִין, רַבִּי מֵאיר אוֹמֵר, אִם נָתְנוּ עַד שֶׁלֹּא חָלְקוּ, נָתָנוּ. וְאִם לָאו, פְּטוּרִין. רַבִּי יְהוּדָה אוֹמֵר, נִתְחַיְּבוּ נְכָסִים. זָכָר וּנְקֵבָה, אֵין כָּאן לַכֹּהֵן כְּלוּם :
ה
שְׁתֵּי נָשִׁים שֶׁל שְׁנֵי אֲנָשִׁים שֶׁלֹּא בִכְּרוּ וְיָלְדוּ שְׁנֵי זְכָרִים, זֶה נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן, וְזֶה נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן. מֵת אֶחָד מֵהֶן בְּתוֹךְ שְׁלשִׁים יוֹם, אִם לְכֹהֵן אֶחָד נָתְנוּ, יַחֲזִיר לָהֶן חָמֵשׁ סְלָעִים . אִם לִשְׁנֵי כֹהֲנִים נָתְנוּ, אֵינָן יְכוֹלִין לְהוֹצִיא מִיָּדָם. זָכָר וּנְקֵבָה, הָאָבוֹת פְּטוּרִין, וְהַבֵּן חַיָּב לִפְדּוֹת אֶת עַצְמוֹ. שְׁתֵּי נְקֵבוֹת וְזָכָר אוֹ שְׁנֵי זְכָרִים וּשְׁתֵּי נְקֵבוֹת, אֵין כָּאן לַכֹּהֵן כְּלוּם :
ו
אַחַת בִּכְּרָה וְאַחַת שֶׁלֹּא בִכְּרָה שֶׁל שְׁנֵי אֲנָשִׁים, וְיָלְדוּ שְׁנֵי זְכָרִים, זֶה שֶׁלֹּא בִכְּרָה אִשְׁתּוֹ, נוֹתֵן חָמֵשׁ סְלָעִים לַכֹּהֵן. זָכָר וּנְקֵבָה, אֵין כָּאן לַכֹּהֵן כְּלוּם . מֵת הַבֵּן בְּתוֹךְ שְׁלשִׁים יוֹם, אַף עַל פִּי שֶׁנָּתַן לַכֹּהֵן, יַחֲזִיר (לוֹ חָמֵשׁ סְלָעִים). לְאַחַר שְׁלשִׁים יוֹם, אַף עַל פִּי שֶׁלֹּא נָתַן, יִתֵּן . מֵת בְּיוֹם שְׁלשִׁים, כְּיוֹם שֶׁלְּפָנָיו  . רַבִּי עֲקִיבָא אוֹמֵר, אִם נָתַן, לֹא יִטּוֹל. וְאִם לֹא נָתַן, לֹא יִתֵּן . מֵת הָאָב בְּתוֹךְ שְׁלשִׁים יוֹם, בְּחֶזְקַת שֶׁלֹּא נִפְדָּה , עַד שֶׁיָּבִיא רְאָיָה שֶׁנִּפְדָּה. לְאַחַר שְׁלשִׁים יוֹם, בְּחֶזִקַת שֶׁנִּפְדָּה, עַד (שֶׁיָּבִיא רְאָיָה)  שֶׁלֹּא נִפְדָּה. הוּא לִפָּדוֹת וּבְנוֹ לִפָּדוֹת, הוּא  קוֹדֵם אֶת בְּנוֹ . רַבִּי יְהוּדָה אוֹמֵר, בְּנוֹ קוֹדְמוֹ, שֶׁמִּצְוָתוֹ עַל אָבִיו, וּמִצְוַת בְּנוֹ עָלָיו :
ז
חָמֵשׁ סְלָעִים שֶׁל בֵּן, בְּמָנֶה  צוֹרִי  .   שְׁלשִׁים שֶׁל עֶבֶד, וַחֲמִשִּׁים שֶׁל אוֹנֵס וְשֶׁל מְפַתֶּה, וּמֵאָה שֶׁל מוֹצִיא שֵׁם רָע, כֻּלָּם בְּשֶׁקֶל הַקֹּדֶשׁ , בְּמָנֶה צוֹרִי . וְכֻלָּן נִפְדִּין  בְּכֶסֶף, וּבְשָׁוֶה כֶסֶף, חוּץ מִן הַשְּׁקָלִים :
ח
אֵין פּוֹדִין  לֹא בַעֲבָדִים , וְלֹא בִשְׁטָרוֹת , וְלֹא בְקַרְקָעוֹת , וְלֹא בְהֶקְדֵּשׁוֹת . כָּתַב לַכֹּהֵן שֶׁהוּא חַיָּב לוֹ חָמֵשׁ סְלָעִים , חַיָּב לִתֵּן לוֹ וּבְנוֹ אֵינוֹ פָדוּי , לְפִיכָךְ אִם רָצָה הַכֹּהֵן לִתֵּן לוֹ מַתָּנָה, רַשַּׁאי . הַמַּפְרִישׁ פִּדְיוֹן בְּנוֹ וְאָבַד, חַיָּב בְּאַחֲרָיוּתוֹ , שֶׁנֶּאֱמַר (במדבר יח), יִהְיֶה לָּךְ וּפָדֹה תִפְדֶּה :
ט
הַבְּכוֹר נוֹטֵל פִּי שְׁנַיִם בְּנִכְסֵי הָאָב, וְאֵינוֹ נוֹטֵל פִּי שְׁנַיִם בְּנִכְסֵי הָאֵם . וְאֵינוֹ נוֹטֵל פִּי שְׁנַיִם בַּשֶּׁבַח , וְלֹא בָרָאוּי  כְּבַמֻּחְזָק. וְלֹא הָאִשָּׁה בִּכְתֻבָּתָהּ, וְלֹא הַבָּנוֹת בִּמְזוֹנוֹתֵיהֶן , וְלֹא הַיָּבָם . וְכֻלָּן אֵין נוֹטְלִין בַּשֶּׁבַח, וְלֹא בָרָאוּי כְּבַמֻּחְזָק :
י
אֵלּוּ שֶׁאֵינָן חוֹזְרִין  בַּיּוֹבֵל, הַבְּכוֹרָה , וְהַיּוֹרֵשׁ אֶת אִשְׁתּוֹ , וְהַמְיַבֵּם אֶת אֵשֶׁת אָחִיו , וְהַמַּתָּנָה , דִּבְרֵי רַבִּי מֵאִיר. וַחֲכָמִים אוֹמְרִים, מַתָּנָה כְּמֶכֶר  . רַבִּי אֱלִיעֶזֶר  אוֹמֵר, כֻּלָּן חוֹזְרִין בַּיּוֹבֵל . רַבִּי יוֹחָנָן בֶּן בְּרוֹקָא אוֹמֵר, הַיּוֹרֵשׁ אֶת אִשְׁתּוֹ, יַחֲזִיר לִבְנֵי מִשְׁפָּחָה וִינַכֶּה לָהֶם מִן הַדָּמִים  :
פרק תשיעי
א
מַעְשַׂר בְּהֵמָה נוֹהֵג בָּאָרֶץ וּבְחוּצָה לָאָרֶץ, בִּפְנֵי הַבַּיִת וְשֶׁלֹּא בִפְּנֵי הַבַּיִת, בַּחֻלִּין אֲבָל לֹא בַמֻּקְדָּשִׁין . וְנוֹהֵג בַּבָּקָר וּבַצֹּאן , וְאֵינָן מִתְעַשְּׂרִים מִזֶּה עַל זֶה . בַּכְּבָשִׂים וּבָעִזִּים , וּמִתְעַשְּׂרִין מִזֶּה עַל זֶּה. בֶּחָדָשׁ , וּבַיָּשָׁן , וְאֵינָן מִתְעַשְּׂרִין מִזֶּה עַל זֶּה . שֶׁהָיָה בַּדִּין, מָה אִם הֶחָדָשׁ וְהַיָּשָׁן שֶׁאֵינָן כִּלְאַיִם זֶה בָזֶה, אֵין מִתְעַשְּׂרִין מִזֶּה עַל זֶה. הַכְּבָשִׂים וְהָעִזִּים שֶׁהֵם כִּלְאַיִם זֶה בָזֶה, אֵינוֹ דִין שֶׁלֹּא יִתְעַשְּׂרוּ מִזֶּה עַל זֶה, תַּלְמוּד לוֹמַר (ויקרא כז), וָצֹאן, מִשְׁמָע כָּל צֹאן, אֶחָד:
ב
מַעְשַׂר בְּהֵמָה מִצְטָרֵף כִּמְלֹא רֶגֶל בְּהֵמָה רוֹעָה . וְכַמָּה הִיא רֶגֶל בְּהֵמָה רוֹעָה, שִׁשָּׁה עָשָׂר מִיל  . הָיָה בֵּין אֵלּוּ לְאֵלּוּ שְׁלשִׁים וּשְׁנַיִם מִיל , אֵינָן מִצְטָרְפִין. הָיָה לוֹ בָאֶמְצָע, מֵבִיא וּמְעַשְּׂרָן בָּאֶמְצָע . רַבִּי מֵאִיר אוֹמֵר, הַיַּרְדֵּן מַפְסִיק לְמַעְשַׂר בְּהֵמָה :
ג
הַלָּקוּחַ אוֹ שֶׁנִּתַּן לוֹ מַתָּנָה, פָּטוּר מִמַּעְשַׂר בְּהֵמָה . הָאַחִים הַשֻּׁתָּפִין שֶׁחַיָּבִין בַּקָּ לְבּוֹן , פְּטוּרִין מִמַּעְשַׂר בְּהֵמָה . וְשֶׁחַיָּבִין בְּמַעְשַׂר בְּהֵמָה, פְּטוּרִין מִן הַקָּלְבּוֹן . קָנוּ מִתְּפוּסַת הַבַּיִת, חַיָּבִין. וְאִם לָאו, פְּטוּרִין. חָלְקוּ וְחָזְרוּ וְנִשְׁתַּתְּפוּ, חַיָּבִּין בַּקָּלְבּוֹן וּפְטוּרִין מִמַּעְשַׂר בְּהֵמָה  :
ד
הַכֹּל  נִכְנָס לַדִּיר לְהִתְעַשֵּׂר, חוּץ מִן הַכִּלְאַיִם , וְהַטְּרֵפָה , וְיוֹצֵא דֹפֶן, וּמְחֻסַּר זְמָן, וְיָתוֹם. אֵיזֶהוּ יָתוֹם, כּל שֶׁמֵּתָה אִמּוֹ אוֹ שֶׁנִּשְׁחָטָה . רַבִּי יְהוֹשֻׁעַ אוֹמֵר, אֲפִלּוּ נִשְׁחֲטָה אִמּוֹ וְהַשֶּׁלַח  קַיָּם , אֵין זֶה יָתוֹם :
ה
שָׁלשׁ גְּרָנוֹת  לְמַעְשַׂר בְּהֵמָה, בִּפְרוֹס  הַפֶּסַח , בִּפְרוֹס  הָעֲצֶרֶת, בִּפְרוֹס הֶחָג , דִּבְרֵי רַבִּי עֲקִיבָא. בֶּן עַזַּאי אוֹמֵר, בְּעֶשְׂרִים וְתִשְׁעָה בַּאֲדָר , בְּאֶחָד בְּסִיוָן , בְּעֶשְׂרִים וְתִשְׁעָה בְאָב . רַבִּי אֱלִיעֶזֶר וְרַבִּי שִׁמְעוֹן אוֹמְרִים, בְּאֶחָד בְּנִיסָן , בְּאֶחָד בְּסִיוָן, בְּעֶשְׂרִים וְתִשְׁעָה בֶאֱלוּל . וְלָמָּה אָמְרוּ בְּעֶשְׂרִים וְתִשְׁעָה בֶאֱלוּל וְלֹא אָמְרוּ בְּאֶחָד בְּתִשְׁרֵי, מִפְּנֵי שֶׁהוּא יוֹם טוֹב, וְאִי אֶפְשָׁר לְעַשֵּׂר בְּיוֹם טוֹב , לְפִיכָךְ הִקְדִּימוּהוּ בְּעֶשְׂרִים וְתִשְׁעָה בֶאֱלוּל . רַבִּי מֵאִיר אוֹמֵר, בְּאֶחָד בֶּאֱלוּל רֹאשׁ הַשָּׁנָה  לְמַעְשַׂר בְּהֵמָה. בֶּן עַזַּאי אוֹמֵר, הָאֱלוּלִיִּין מִתְעַשְּׂרִין בִּפְנֵי עַצְמָן :
ו
כָּל הַנּוֹלָדִים מֵאֶחָד בְּתִשְׁרֵי עַד עֶשְׂרִים וְתִשְׁעָה בֶּאֱלוּל, הֲרֵי אֵלּוּ מִצְטָרְפִין . חֲמִשָּׁה לִפְנֵי רֹאשׁ הַשָּׁנָה וַחֲמִשָּׁה לְאַחַר רֹאשׁ הַשָּׁנָה, אֵינָן מִצְטָרְפִין. חֲמִשָּׁה לִפְנֵי הַגֹּרֶן וַחֲמִשָּׁה לְאַחַר הַגֹּרֶן, הֲרֵי אֵלּוּ מִצְטָרְפִין. אִם כֵּן לָמָּה נֶאֱמַר שָׁלשׁ גְּרָנוֹת לְמַעְשַׂר בְּהֵמָה, שֶׁעַד שֶׁלֹּא הִגִּיעַ הַגֹּרֶן, מֻתָּר לִמְכּוֹר וְלִשְׁחוֹט. הִגִּיעַ הַגֹּרֶן, לֹא יִשְׁחוֹט. וְאִם שָׁחַט, פָּטוּר:
ז
כֵּיצַד מְעַשְּׂרָן, כּוֹנְסָן לַדִּיר וְעוֹשֶׂה לָהֶן פֶּתַח קָטָן כְּדֵי שֶׁלֹּא יִהְיוּ שְׁנַיִם יְכוֹלִין לָצֵאת כְּאַחַת, וּמוֹנֶה בַשֵּׁבֶט, אֶחָד, שְׁנַיִם, שְׁלשָׁה, אַרְבָּעָה, חֲמִשָּׁה, שִׁשָּׁה, שִׁבְעָה, שְׁמוֹנָה, תִּשְׁעָה, וְהַיוֹצֵא עֲשִׂירִי סוֹקְרוֹ בְסִקְרָא וְאוֹמֵר הֲרֵי זֶה מַעֲשֵׂר. לֹא סְקָרוֹ בְסִקְרָא וְלֹא מְנָאָם בַּשֵּׁבֶט, אוֹ שֶׁמְּנָאָם רְבוּצִים, אוֹ עוֹמְדִים, הֲרֵי אֵלּוּ מְעֻשָּׂרִים  , הָיָה לוֹ מֵאָה וְנָטַל עֲשָׂרָה , עֲשָׂרָה וְנָטַל אֶחָד, אֵין זֶה מַעֲשֵׂר . רַבִּי יוֹסֵי בְּרַבִּי יְהוּדָה אוֹמֵר, הֲרֵי זֶה מַעֲשֵׂר , קָפַץ (אֶחָד) מִן הַמְּנוּיִין לְתוֹכָן , הֲרֵי אֵלּוּ פְטוּרִין . מִן הַמְעֻשָּׂרִים לְתוֹכָן , כֻּלָּן יִרְעוּ עַד שֶׁיִּסְתָּאֲבוּ, וְיֵאָכְלוּ בְמוּמָן לַבְּעָלִים:
ח
יָצְאוּ שְׁנַיִם כְּאֶחָד, מוֹנֶה אוֹתָן שְׁנַיִם שְׁנָיִם . מְנָאָן אֶחָד, תְּשִׁיעִי וַעֲשִׂירִי מְקֻלְקָלִין  . יָצְאוּ תְּשִׁיעִי וַעֲשִׂירִי כְּאַחַת, תְּשִׁיעִי וַעֲשִׂירִי מְקֻלְקָלִין  . קָרָא לַתְּשִׁיעִי עֲשִׂירִי  וְלָעֲשִׂירִי תְּשִׁיעִי וּלְאַחַד עָשָׂר עֲשִׂירִי , שְׁלָשְׁתָּן מְקֻדָּשִׁין . הַתְּשִׁיעִי נֶאֱכָל בְּמוּמוֹ , וְהָעֲשִׂירִי מַעֲשֵׂר   , וְאַחַד עָשָׂר קָרֵב שְׁלָמִים וְעוֹשֶׂה תְמוּרָה, דִּבְרֵי רַבִּי מֵאִיר. אָמַר רַבִּי יְהוּדָה, וְכִי יֵשׁ תְּמוּרָה  עוֹשָׂה תְמוּרָה. אָמְרוּ מִשּׁוּם רַבִּי מֵאִיר , אִלּוּ הָיָה תְמוּרָה, לֹא הָיָה קָרֵב .  קָרָא לַתְּשִׁיעִי עֲשִׂירִי וְלָעֲשִׂירִי עֲשִׂירִי וּלְאַחַד עָשָׂר עֲשִׂירִי, אֵין אַחַד עָשָׂר מְקֻדָּשׁ. זֶה הַכְּלָל, כֹּל שֶׁלֹּא נֶעֱקַר שֵׁם עֲשִׂירִי מִמֶּנּוּ, אֵין אַחַד עָשָׂר מְקֻדָּשׁ:
* הוספות:
** א.
כן אומר גמ’ (יג.). אבל, איני מבין כל כך למה מה שיש לו קדושת הגוף הוא סיבה להקדים אותו. אפשר לומר שטוב לתת כבוד למה שהוא יותר קדוש, ולדבר בו תחילה. גם יש לומר שכיון שמדברים על בכור, מה שהאו יותר בכור בא ראשון. כיון שיש לו קדושת הגוף, הוא יותר בכור, שמה שעושה אותו בכור הוא חלק יותר חשוב ממנו. גם אפשר שאין הענין שיבוא ראשון, אלא שיסמוך לזבחים ומנחות, כיון שהם דנים בדברים שיש להם קדושה. אבל, יש לדון, שביניהם כבר יש חולין, ומי שקורא את השם של חולין יכול להבחין בקל שלא מדבר על קדשים. גם אפשר שקושייתו הוא למה לא סומכים בכור בהמה טמאה לבכור אדם, שלשניהם אין קדושת הגוף. לשון הגמ’ בוודאי לא משמע כן, וגם לא תי’ לקושיה זו לבסוף, שיכתוב בכור בהמה טמאה, ושוב אדם, ושוב בכור בהמה טהורה, או יכתוב בכור אדם, בכור בהמה טמאה, ושוב בכור בהמה טהורה.
** ב.
כן אומר גמ’ (יג.). איני מבין למה יותר טוב לשים הדבר היותר קטן בתחילה. אפשר שתנא לא רצה לסדר הענין היותר ארוך, ואז עשה פרוקראסטינישי"ן. דחוק לומר כן על תנא; גם יש לדון למה לא היפך את הסדר אחרי שכתב אותו. (אולי חשש שיהיה בעיה לסתם משניות; צריך לע’ אם יהיה בעיה.) אפשר שחש שירצה הקורא להתחיל עם דבר קל. יש לדון למה ירצה. נראה שאולי חושש מללמוד דבר גדול (יש לדון איך יידע), ואז לומד דבר קטן. כיון שכבר נכנס קצת לסוגיה, ימשיך ללמוד גם דבר יותר ארוך. ותחשב עוד.
** ג.
גמ’ אומר (יג.) שהוא "איידי דחביבא ליה כדר"ח[fn:121].”[fn:122] יש לדון אם הכוונה הוא לומר שהוא חביב כיון שיש עליו הפשט של רבי חנינא, והוא שפשט טוב הוא, או שהוא חביב מחמת אותו טעם שגילה ר"ח, והוא הכרת הטוב. לפשט ראשון, יש לדון אם פשט של ר"ח הוא טוב כיון שהוא מאד מסתבר או כיון שמגלה כמה חשוב הוא הכרת הטוב. לפשט שני, הביאור יהיה שרואים שמצווה חשובה היא זו, שהרי בא מפני הכרת הטוב של ה’. (אבל, איני יודע שמצווה שבא מחמת הכרת הטוב של ה’ הוא יותר חשוב ממצווה שבא לאיזה סיבה אחרת.)
שוב ראיתי שגר"ק פי’ שכוונת הגמ’ הוא מפני שיש בו חידוש.
** ד.
גמ’ מפרש שהוא מפני שסייעו את בני ישראל כשיצאו ממצרים. לכאו,’ הוא סוג של הכרת הטוב, שהוא טוב לבהמות לעשות כן להם (כמו שמצאנו בפרות בהר הכרמל)[fn:123]. גם אפשר שמה שעשו דבר טוב קדש אותם, עד שהם ראויים לקדושה כזה.
** ה.
מענין שגמ’ רק מצדד לקנוס כיון שהוציא את הבכור מקדושה. הייתי אומר סיבה יותר פשוטה לקנוס, והוא מה שכתוב בפי’ במשנה, שאסור לעשות כן.[fn:124] נראה שגמ’ מניח שאילו היו קונסים אותו על שעבר על זה, לא היה הקנס נוגע לבכור, אלא היה על האם. (אבל, ע’ בגמ’, שמצדד שכיון שקונסים על האם קונסים על הבכור.)
וע’ ברע"ב, שכ’ איסור של מכירת כל בהמה לגוי. יש להעיר שגמ’ לא אומר כן.
** ו.
גמ’ מבאר שגבי בכור בהמה טהורה, חייב לקנות את כולו ולתת אותו לכהן. (אף אם הוא כפי עשר מדמיו, חייב.) חלק מזה קנס דרבנן (כן אומר גמ’ בפי’), ואיני יודע כמה ממנו הוא דין דאו’. על כל פנים, יש לדון אם זה ישנה דין של חמור. ותחשב.
** ז.
איני יודע מי ההורים שלו. יכול להיות שלש יכולות- שניהם טהורים, האב טהור והאם טמאה, והאב טמא והאם טמאה. אפשר להיות שרבנן ור"ש לא סוברים שטמא וטהור מולידים, ואז אין זה נוגע. אבל, אם נוגע, נראה שצריך לומר שחולקים בכולם, שהרי בזה מצאנו דיון של רבי אליעזר ורבי יהושע (ז.), וגמ’ מוכיח שסוברים כרבי שמעון. ויש לדון, שאולי כיון שגם מדברים בציור שאב ואם טוהרים, ועדיין צריכים סימנים, מוכח שאינו כרבנן. אבל, אולי שאר דינים הם כרבנן. וצריך לחשוב.
** ח.
כן נראה לי, אבל זה לא ברור. יש שתי הערות. הערה ראשונה הוא שגמ’ לא מבאר דין של אם טהורה ואב טמא כלל. הנחתי שהוא שווה לדין אם טמאה ואב טהור, שכן נ’ מלשון הגמ’, אבל איני יודע. גם יש להעיר שלצד אחד בגמ’, הטמא שמוליד צריך להיות קלוט (שאין טמא אחר מוליד מטהור). יש לדון אם יהיה מותר אם הוא טמא ממש (לפי התנאים שסוברים שמוליד). ותחשב. גם איני יודע דין של דומה בראשו ורובו אם רק הורה אחד הוא טהור.
** ט.
אין כל זה כל כך פשוט. גמ’ שואל מהו הדין של מי רגלים של חמור. מבאר למה רק שואל למי רגלים של חמור- לשון אחד אומר שהוא כיון שרק הוא נשתנה מגוף בהמה טמאה, ואז רק בו יש צד לאסור, ולשון אחר אומר שהוא כיון שרק הוא נשתה, אבל מ"ר של בהמות אחרים אינו נשתה או נאכל. (ללשון שני, יש לדון אם אותו שאלה יתקיים בהם, אלא שלא נוגע, או לא יתקיים. היה נראה לומר שלא יתקיים, שאם היה קיים, היה לו לשאול אותו במ"ר סתם, ויהיה נוגע שם, כיון שזה כולל מ"ר של חמורים. אולי רצה לבאר מתי יהיה שייך. דחוק.) גמ’ תי’ שכיון שמשנה אומר "מן הטמא,” רואים שאוסר כל חלק מן הטמא, אף שלא בא מגוף שלו. יש לדון אם זה חוזר ואוסר גם של סוסים (ונגד הו"א של השואל) או אינו אוסר אותם, אלא רק של חמורים. ותחשב על זה.
** י.
איני מבין דרשה זו כל כך. עיין ברש"י, שיש לו שני לשונות. גם איני מבין כל כך למה מה שאין לו שם לווי עושה שיותר מסתבר להתיר אותו מלהתיר שאר מיני דבש. ותחשב.
** יא.
גמ’ מדייק (ו:) מלשון "מן הטמא.” לא כל כך פשוט לי מהו הדרשה, אבל כן דורש. ע’ במשניות, ששם כ’, “מהטמא.” אפשר להיות שחולקים שני האמוראים בגמ’. (באמת, כן נ’ קצת, שאם לא שחול’ בגי’ של המשנה, למה יביא ראיה מתנא אחר החולק; יביא ראיה מן המשנה. צריך לומר שאין גי’ של המשנה כל כך ברור, והיה לנו להוכיח את הגי’ על פי בריי’ האחר. יש לדון, שאולי אין הדיוק כל כך מוכחרח- ובאמת, אינו כל כך מוכרח.) ותחשב על זה.
** יב.
גמ’ מדייק שצריכים שראינו שבלע אותו. לכאו’, הדיוק הוא ממה שאמר שבלע, ולא שמצאנו אותו במעיו. דוחה הגמ’ הצד שצ’ ראייה שבלע, ופי’ שצ’ שנמצא בדרך הריעי או כדו’. אבל, יש לדון אם עדיין צ"ל שראה אותו בולע. לא ברור למה יצטרך שראה אותו בולע, אבל הדיוק, לכאו’, נשאר. ותחשב.
** יג.
אין הלומדות של הדןי הזה כל כך פשוט לי. אני הייתי אומר שהחידוש הוא שכמו שיש חיוב לתת שה של הפדיון לכהן, כך יש חיוב לתת שה המתה לכהן. אבל, נראה שלא סובר כן גמ’ (כיון ש"שה" משמע חיה). אלא, מסביר גמ’, כיון שהפריש אותו, ברשות כהן עומד. קצת צריך ביאור- איזה כהן, שהרי אין אחד שלו בדווקא צריך לתת. אולי מניחים שיש כהן בדעתו, ולו נעשה. גם אפשר שנעשה של כל הכהנים, שיש לכולם זכייה בו להיות שבא לאחד מהם. ותחשב.
** יד.
עיין בגמ’ ביומא. נראה שאפשר להיות שמי שדורש אותו ממה ש"שה" לא מכוון לשה שחוטה סובר שלא יכולים לדרוש אותו מקרבן פסח, שאף שלא מביאים לעזרה שה שחוטה, מקריבים שה שחוטה על המזבח, ואז לא נוכל לומר שהוא פסול לקרבן פסח. ויש לדון, שקרא מדבר על מה מביאים לעזרה לשחוט. ותחשב.
** טו.
צריך לע’ בגמ’ בזה, שזה לא פשוט. צריך לעיין באיזה מין  מדברים כאן. בהשקפה ראשונה, היה נראה לומר שהוא מין שני, שהרי כן סובר רבי אליעזר בחולין (עט). אבל, אם כן קשה למה רבנן צריכים לדון בו כלל, שהוא כבר כלאים. דחוק לומר שהוא רק אגב שר"א מדבר בו. אז, אולי כל אחד מדבר על מין שלו. אבל, מוזר שיש לנו, במשנה אחד, מילה אחת שמשמע שני דברים. ותחשב.
בנוגע בירור דין, גם זה לא פשוט. לכאו’, יהיה פשוט על צד הראשון שכוי לא כשר[fn:125], שאינו שה. ויש לדון, שאולי על הצד שהוא בהמה, הוא שה. אבל, גם מין שני לא יהיה פשוט לר"א, כיון שלא סובר שמקצת שה נחשב שה. (צריך לע’ בחולין, שלא עיינתי בו כלל, ואולי אין זה נכון.) ותחשב על זה.
וע’ ברש"י, שפי’ שכוי הוא מין ראשון.
גר"ק אמר שאם הוא ספק אם חיה אם בהמה הוא, שניהם פוסלים כיון שהוא חיה, ואינה שה. אם הוא כלאים, ת"ק אוסר כיון שהוא כלאים, ור"א פוסל כיון שמסופק אם חוששים לזרע האב (ומיירי בצבי הבא על התייש).
** טז.
הזכיר גר"ק: “ מק’ תוס’ שאף לר"ש נצטרך הפרשה כדי לגרום שלא יחייב לערפו. ת’ שכיון שא"צ ליתן לכהן את השה, אינו חייב בהפרשה. לכאורה, כוונתו למר (ודנו (ע’ ר"ש בשערי יושר) מהו הפשט בזה) שתלוי מצות הפרשה במצות נתינה לכהן. המקור לומר כן צריך ביאור. מתוס’ נמצא שמה שא"צ ליתן לכהן הוא דין ודאי (שאל"ה, נאמר שמספק צריך לקיים מצות עריפה. זה שייך לסוגית תקפו כהן. יש (רי”ט אלגאזי) שאומר שעל מצות עריפה אומרים המוציא מחבירו עליו הראיה. מחודש לומר כן, אבל מחדש שעיקר הדין הוא שצריך להפסיד חמורו, וצריכים להוציאו ממנו. על פי זה, מת’ ק’ תוס’.)”
** יז.
אם כן, היה נראה לומר שבספק, ר"א סובר שצריך לתת לכהן, לוא רק להפריש. אבל, בבריי’ אומר נגד זה. דנו בזה אחרונים. חמדת שלמה פי’ שעשו שאינו זוכה כזוכה. יש להעיר שאז לקוח הוא (ור"א יחלוק על אותו דין שבמשנה). רי"ט אלגאזי פי’ שרק צריך נתינה לכהן לפדות כשיש חיוב ממוני לתת לכהן.
** יח.
וא"ת למה אין בזה מחלקת רבא ואביי ב"אם עביד מהני.” בתמורה מפרש שכאן כתיב, “ולנדר לא ירצה,” שמשמע שרק ריצוי אין בו, אבל קדושה יש בו.
** יט.
ע’ בגמ’. גמ’ מדייק שרק מותר אחרי שנפדו, ואומר שמזה יכולים לסייע לרבי אלעזר, שגם אומר כן. היה אפשר לדייק שממה שצריך להביא סיוע לרבי אלעזר, אינו דבר מוסכם, ואינו כל כך פשוט. יש לדון בזה, שאפשר לטעון שרק אינו פשוט, אבל לבסוף הוא מוסכם. ותחשב.
יש להוסיף שאם יש מי שחולק על רבי אלעזר, יצטרך לפרש את המשנה. זה לא נראה כל כך קשה, כי המשנה לא מאד משמע כרבי אלעזר. נוכל לומר שקטע זה של משנה לא מדבר בציור של לאחר שנפדו.יש להעיר שאז האמצע שונה מן התחילה ומן הסוף של המשנה. ויש להעיר שאולי משנה קצת משמע כן, שמזכיר הפדיון רק בתחילה ובסוף, ולא בזה.
היה אפשר לדחות לומר שההוכחה אינו ממה שאומר על רישא או סיפא שהוא לאחר פדיון (ואז נניח שקאי גם על זה או נלמד שכל ציורי המשנה דומים), אלא הוא ממילים "יוצאים לחולין.” כן נראה מרש"י על המשנה. אבל, לשון גמ’ כשמדייק לא משמע כן.
** כ.
נראה שעדיין יהיו לו דינים של משנה הבאה. נראה שדינים של משנה זה באים כיון שלא יכול להקדיש אותם. הרי, גילתה תורה שיכול להקדיש אלו. אבל, לכאו’ (ולא מוכרח), דינים האחרים באים מפני שלא יכול להיקרב, והרי גם בכור ומעשר לא נקרבים.
* Footnotes
[fn:1] פרק ראשון
[fn:2] משנה א
[fn:3] מסכתא זה דן בעיקר בדיני בכור. יש שלש מינים של בכור- בכור בהמה טמאה, בכור אדם, ובכור בהמה טהורה. ידון בדינים של בכור, וכיון שנוגע לדיני בכור, ידון במומים. גם ידון במעשר, כיון שהרבה דינים נלמדו מזה לזה.
[fn:4] פרק זה יבאר דין של בכור בהמה טמאה. אז, נקדים עם עיקרי דינים שלו: נולד לישראל (אני משתמש עם מילה זו למעט גוי ולמעט כהן ולוי) בכור בהמה טמאה. חלקו תנאים אם מותר להנות מן הבכור. יש חיוב להפריש שה לתת לכהן (או לתת פדיונו לכהן (ט:)) או לערוף אותו. (יותר טוב לתת שה.) אחרי שנותן שה, כוע"מ שמותר בהנאה. אחרי שעורף אותו, גמ’ מצדד שכוע"מ שאסור בהנאה.בכור בהמה טמאה רק נוהג בחמור. חולקים אם המקור לזה הוא כפילות שני המילים "פטר חמור" או כלל ופרט של "כל מקנך תזכור… חמור.” (ו.) גמ’ נותן סיבה לזה, והוא שה’ מכיר טוב לחמורים, כיון שסייעו את בנ"י כשיצאו ממצרים. (ה:)
[fn:5] גמ’ מבאר שהיה לו להתחיל עם דינים של בכור בהמה טהורה, כיון שיש לו קדושת הגוף. (ע’ בהוספות אות א) אבל, הקדים את זה לשני סיבות:אין הרבה משניות לדון בבכור בהמה טמאה. אז, היה יותר קל לתנא להתחיל בו. (ע’ בהוספות אות ב.)הוא מראה הכרת הטוב של ה’, ולכן היה חביב על התנא. (ע’ בהוספות אות ג.) הדרך שמראה אותו הכרת הטוב הוא על פי פשט שאומר ר’ חנינא לבאר למה חמור לבדו יש לו דינים של בכור בהמה טמאה. מפרש שהוא להכרת הטוב (ע’ בהוספות אות ד.) על מה שנשאו את שלל מצרים לבני ישראל.
[fn:6] משנה זה יבאר פטור של קנין גוי. כיון שגוי קונה אותו (שכ’, “כל בכור בישראל") או את האם (שכ’, “כל מקנך תזכר”), אין עליו דיני בכור. חולקים תנאים ואמוראים כמה צריך גוי לקנות. בתחילה, נבאר כמה צריך לקנות בו, ואח"ז, נבאר כמה צריך לקנות באם.רבי יהודה סובר שכדי שיהיה פטור, צריך שגוי יקנה את כולו (ב., ג.). דורש כן ממש"כ, “כל בכור.” סובר "כל" מלמד שרק צריכים כל שהוא כדי לחייב בבכור. (ג.)רבנן סוברים שכדי שיהיה פטור, רק צריך שגוי יקנה חלק חשוב, שדורשים מ"כל בכור" שצריך להיות שכל הבכור הוא לישראל (ג.). גמ’ מניח שלא צ’ כל הבכור, אלא כולו בלי חסרון חלק חשוב. חולקים מה נחשב חלק חשוב:ר"ח לפי ר"פ ורבא לפי ר"פ אומרים שרק חלק שצריך כדי לחיות מהני. חולקים מה צריך כדי לחיות:ר"ח לפי ר"פ אומר שהוא מה שעושה אותו לנבילה.רבא לפי ר"פ אומר שהוא מה שעושה אותו לטריפה.ר"ה ור"י (וכ"ע, לפי רבנן קמיה דר"פ) אומרים שכל חלק שעושה מום, אילו ניטל, מהני.זהו דין קנין הבכור. דין קנין האם שווה, חוץ מחילוק אחד, והוא שלפי רבנן קמיה דר"פ, כו"ע (אולי חוץ מר"י) אומרים שצריכים חלק שצריך כדי לחיות. (ג)
[fn:7] אז, הבכור של ישראל, אבל כיון שהאם של גוי, אין הישראל חייב בבכורה.
[fn:8] עובר, ונשאר החמור של ישראל. (כן יוצא מגמ’ ב..)
[fn:9] מצדד גמ’ (ב) שרבי יהודה חולק על דין זה, וסובר שכיון שמכר באיסור, חייב בבכורה.
[fn:10] גמ’ מבאר (ב.) שבציור זה, יש הו"א לחייב אותו בדיני בכור מחמת קנס, כיון שהוציא את הבכור מקודושה. (עיין בהוספות אות ה.)
[fn:11] אז, האם של ישראל, אבל הכור של גוי. לכן, אין חיוב בכורה.
[fn:12] לכאו’, רצה לומר שמשתתפים באם (ואז גם בבנים), שאם לא כן, שווה הוא לדיני קבלה. (אז, נמצא שגם בזה רבי יהודה חולק.)
[fn:13] רבי יהודה חולק על דין זה, ומחייב אף כשיש שותפות לגוי (ב.). לכאו’, המקור לזה הוא "כל,” שכל קנין (ואף קנין שיש לו כשיש שותף אחר) מספיק לחייב אותו בבכור. רבי יהודה סובר שחצי דמיו קדוש. בבהמה, זה עושה קדושת הדמים על חציו. צריך ביאור מה יקרה בחמור.
[fn:14] הבהמה הוא של גוי, והבנים הם של ישראל.
[fn:15] רבי יהודה חולק על דין זה, כמו שחולק בדין שותפות. (ב.).
[fn:16] גמ’ מפרש (ב.) שאין בזה חי’ מוסיף על משתתף, אבל רצה לשנות נותן בקבלה (מח’ חידוש שנבאר), ולכן שנה זה. (לא מבאר ל"ל רק תנא זה במקום שיתוף עם גוי.
[fn:17] הבהמה של ישראל, והבנים של גוי.
[fn:18] רבי יהודה חולק על דין זה, כמו שחולק בדין שותפות. (ב.). (עיין בהוספות אות ו.)
[fn:19] גמ’ מבאר (ב.) שיש בזה חידוש, שהו"א שכיון שהאם של ישראל, נראה כציור שמתחייב בבכור, ואז יתחייב מדרבנן.
[fn:20] באמת, קרא זה הוא מקור לפטור בכור של גוי. משנה גם מבאר פטור של אם של גוי. זה נלמד מ"כל מקנך.”
[fn:21] רצה לומר: שנאמר, “ישראל" שמשמע- אבל לא באחרים.
[fn:22] פטורים כשקונים את הבכור. גמ’ לא מבאר דין של כהנים ולויים שקונים את האם. (היה נראה לומר שאין מקור לומר שפוטר. אבל, יל"ד, שאולי מסתבר שדבר שיש לו כוח לפטור מכבורה יפטור כל זמן שהוא על האם.)
[fn:23] לא פשוט כמה צריכים לקנות בו כדי לפטור את הבהמה, אם צריכים לקנות את כולו או מספיק שיהיו שותפים.
[fn:24] נראה שזה רק אם נולד ברשות שלו. אבל, אם נולד ברשות ישראל (ונתחייב בבכור), אף שניתן לכהן, אינו פטור מבכור. (חיוב הפרשה הוא על בעל השה, ולא על מי שנולד לו.) (יב.)
[fn:25] חולקים מהו הלימוד:אביי פי’ שבמדבר, לויים פטרו בכורות, ובהמות לויים פטרו בכור בהמות בנ"י. כמו שפטרו בהמות שלהם את הבכורים, יפטרו את עצמם. דוחה רבא מלשון המשנה, וכן שאז יטפרו גם בכור בהמה טהורה שלהם (ואין זה הדין).רבא פי’ שבמדבר, לויים פטרו בכורות, ורואים מזה שבכור אדם של לוי פטור. כיון שהוקשו לבכור בהמה טמאה (“אך פדה תפדה…"), גם ב"ב טמאה של לוי פטור.יש מיני לויים שלא פטרו בכורות במדבר, והם נתרבו מ"הלויים,” שמקיש כל לויים זל"ז.פוטרים בכורים של דורות כיון שכ’, “והיו.”  (ד)
[fn:26] דינים היוצאים מן המשנה:אם של גוי- אם של גוי- בכור פטור.נשתתפו בו בחלק חשוב-רבנן- פטור.רבי יהודה- חייב.בכור של גוי-בכור של גוי- פטור.נשתתפו בו בחלק חשוב-רבנן- פטור.רבי יהודה- חייב.בכור של כהן ולוי- פטור.
[fn:27] משנה ב
[fn:28] גמ’ (ו.) מעורר שאם יש בו מקצת סימנים הדומים לאם, נתחייב בבכור בהמה טהורה. ר"ש חול’, ופוטר עד שידמה לאמו בראשו ורובו. (ו:) (נ’ שמשנה הפוטר הוא או כשאין סימנים או רק פוטר מבכור בהמה טמאה.)
[fn:29] גמ’ מפרש (ו.) שיש בזה חידוש, שסוסים וחמורים הם דומים זה לזה, ואז הו"א שאין הבן כ"כ חלוק מן האם, ויתחייב.
[fn:30] דן גמ’ אם נתחייב הנולד בבכור אם יש לו מקצת סימנים הדומים לאם. (ו.)
[fn:31] נמצא שתנא שלנו דורש מ"פטר חמור" שנכפל. גמ’ מביא חולק (רבי יוסי הגלילי) שלומד כן מ"בכור" שנכפל בכל מין בהמה (שור, כשב, ועז), ולומד ב"ב טמאה מב"ב טהורה.
[fn:32] יש להעיר שלשון המשנה כפול, שכבר הזכיר שכופל "פטר חמור.”
[fn:33] באר"ק- הו"א שכמו שפרה שהוליד חמור, אין הולד פר לקדושת בכור, כך אינו פר לאכילה.
[fn:34] חולקים בזה רבנן ורבי שמעון. רבנן מתירים את זה כיון שכ’, “גמל הוא,” שממעט זה. רבי שמעון אוסר, כיון שכפל מילת "גמל.” (ו:) (עיין בהוספות אות ז.)אבל, אם הבהמה דומה לטהור, מותר. גמ’ מסופק כמה דומה צריך להיות. אם ראשו ורובו דומה, בוודאי מותר. אם רק דומה במקצת סימנים, ר"א ור"י מתירים, אבל גמ’ מסופק אם ר"ש מודה. אף ר"א ור"י לא מתירים בכל מקום שם. ר"י רק מתיר כשאב ואם שלו טהורים (שכ’, “אך את זה לא תאכלו,” שמשמע שיש מה שיאכל"), אבל לא בציור אחר (שכ’, “כבשים”), אבל ר"א מתיר בכל מקום (כיון שכפל "שה"). (ע’ בהוספות אות ח.) (ז.)
[fn:35] גמ’ דורש את זה ממש"כ, “את זה לא תאכלו ממפריסי…,” שאומר לנו שיש דבר עם סימני טהרה שנאסר, והוא דבר טהור שנולד מדבר טמא. (ו.)
[fn:36] עכשיו, משנה מסכם את הדין לכלל. גמ’ מפרש (ו.) שאין כלל זה מוסיף חידוש, אלא הוא דרך לזכור את הדין של המשנה. (וע’ לקמן בביאור שלנו, שיש חידוש שיוצא מכלל זה, לפי מקצת אמוראים.)
[fn:37] נ’ שגמ’ גורס "מן הטמא" ומדייק מזה להכריע שאין יוצא מכלל זה, חוץ מדבש דבורים (עיין לקמן למטה). (עיין בהוספות אות יא.)
[fn:38] זה כולל הנולדים מהם, וגם כולל מה שמוציא מגוף שלו. דורשים כן ממש"כ, “הטמאים.” מרבים חלב (צריך עוד קרא כיון שיש בו חי’ כיון שבא מדם (לשיטת אחת) וכיון שהוא מותר אף שבהמה עוד בחיים) או מ"גמל" יתירה או מ"את הגמל.” (ו:)
[fn:39] חולקים אם יש יוצא אחד מכלל זה, והוא דבר שלא נשתנה הרבה מחמת בהמה הטמאה. (ז:) (ע’ בהוספות אות ט.) אם אין זה יוצא מן הכלל, יש יוצא אחר מן הכלל, והוא דבש, כיון שכ’, “אך את זה תאכלו מכל שרץ העוף,” שמרבה דבר אחד שנאכל, והוא דבש דבורים (שאין לו שם לווי). (ז:) (ע’ בהוספות אות י.)
[fn:40] גמ’ מבאר מה צריכים כדי שנדע שבלע אותו, ולא השריץ בתוכו (בכל כעין זה, יש לדון מי חולק על מי):ראינו שבלע אותו. דוחה גמ’ שאולי בלע אחרת, וזה השריץ.מצא אותו דרך הריעי. (עיין בהוספות אות יב.)מצאו דרך בית הבליעה. מצאו עם צורה נגמרת.רב אשי אומר שכיון שמצאנו אותו, מותר, כיון שרוב דגים משריצים את מינם (באמת, ר"ל שרוב שבדג אינם נשרצים). שאר השיטות חול’ על ר"א, ומדיי’ כן מלשון משנה, שאומר "שבלע" אותו, שמשמע שבוודאי בלע אותו. (ז:)
[fn:41] אין זה כ"כ מחודש (אלא שאולי מחדש מתי מניחים שבלע אותו), ורק אומר שלא נשתנה דין שלו ע"י בליעה, לא לקולא, ולא לחומרא.
[fn:42] דינים היוצאים מן המשנה:בכור נדמה (בין אם דומה לפר בין אם דומה לסוס)-לא דומה לאמו- לא קדוש.דומה במקצת סימנים- רבנן- קדוש.רבי שמעון- לא קדוש.דומה בראשו ורובו- קדוש.בהמה טמאה שמוליד טהורה- טמא.בהמה טהורה שמוליד טמאה-רבנן- מותר.רבי שמעון- דומה לאמו במקצת סימנים:רבי אליעזר- מותר.רבי יהושע- מותר רק אם אביו ואמו טהורים.אולי רבי שמעון- אסור.דומה לאמו בראשו ורובו- מותר.דג טמא שנבלע- אסור.דג טהור שנבלע- מותר. חולקים איך נדע שנבלע:נמצא אותו בבית הרעי.נמצא אותו בבית הבליעה.הוא גדול.תמיד נדע, שהרי אינו מין אחר (מין טהור) הוא.
[fn:43] משנה ג
[fn:44] ידוע שנולד בכור אחד. לא משנה איזה הוא הבכור, שבין כך ובין כך צריך לתת שה אחד לכהן. אז, כן עושה.
[fn:45] וא"ת הרי אין בכור נוגע בכל הרחם. וי"ל שמקצת רחם מקדש. גי"ל שאין מין מפסיק במינו, ואין הפסק בינו לכל הרחם. (ט:)
[fn:46] נמצא שמניח תנא שבוודאי יש בכור אחד. הרי, מצאנו שיטה שחולק על זה, שרבי יוסי הגלילי סובר שיש בכור אחד בוודאי, ויש בכור ספק (אם לא רואים מתי יצאו (יל”ד אם חוששים שנולדו בב”א); אם רואים שיצאו בב”א, יהיו שני בכורות וודאים), שסובר שאפשר לצמצם. חולקים אמוראים אם יאמר כן גם כאן או יתמעט מ"הזכרים,” אבל מסיק שיאמר כן גם כאן. (ט.)
[fn:47] אז, ספק הוא אם חייב בבכורה. כיון שהבכור אסור בהנאה, אם רוצה להתיר אותו בהנאה, צריך להפריש. אבל, כיון שהפריש, הותר בהנאה, אלא שיש לו חיוב ממוני לתת אותו לכהן. כיון שספק הוא, מוציא מחברו עליו הראיה, ולא צריך לתת אותו לכהן.זה מניח שהבכור אסור בהנאה. (איני יודע למה מניח כן, שי"ל שיש חיוב להפריש, אבל כן אומר גמ’.) חולקים בזה רבי יהודה (שאוסר, שהרי צריך פדייה בשה בדווקא) ורבי שמעון (שמתיר, שהרי פדיון שלו מותר בהנאה, או מפני שכ’, “בכור צאנך,” שממעט בכור בהמה טמאה).. (ט:) (עיין בהוספות אות טז.)
[fn:48] אם ילדו שני זכרים, נ’ שצריך להפריש שה אחד מספק, בהוספה לשה שנותן לכהן. ויל"ד, שאולי יש ס"ס, שאולי אחד הוליד זכר וזכר ואחד הוליד נקבה, ואולי אחד הוליד זכר ואחד הוליד נקבה וזכר. ויל"ד.
[fn:49] צריך להפריש אחד (או שנים) מספק. (רש"י ט.) בפשטות, הרמב"ם סובר שלא צריך להפריש כלל, כיון שיש הרבה צדדים כאן. (העיר"ק שרבות הצדדים לא מרבה צדדי פטור. הרבה תורה נכ’ ע"ז.)
[fn:50] דינים היוצאים מן המשנה:אם ידוע שזכר נולד, צריך לתת שה לכהן.אם לא ידוע-רבי יהודה- אסור בהנאה עד שמפריש שה, ואז צריך להפריש שה. אבל, לא נותנו לכהן.רבי שמעון- מותר בהנאה; לא צריך לעשות כלום
[fn:51] משנה ד
[fn:52] רש"י מפרש (ט.) שחוזר על מה שאמר במשנה שלפני כן שפודים בשה, ואומר שהמקור לזה הוא שקרא אומר כן בפירוש. (זה יותר מסתבר אם יהיו משנה אחת, כמו שהם בגמ’.)
[fn:53] רצה לומר, ושה זה יכול להיות מן הכבשים….
[fn:54] מרבה כל אלו מ"תפדה" שנכפל. (יב.)
[fn:55] יש אחרונים שמדייקים מרש"י שזה רק אחרי שנתן אותו לכהן. אבל, אם לא נתן אותו לכהן, יש בו חלות שמונע אותו מלפדות בו עוד. נמצא שמשנה מלפני זה הוא כשלא נתן לכהן, וקטע שלאחר זה הוא כשלא נתן לכהן, וקטע זה רק כשנתן כבר לכהן.
[fn:56] אין בהמה הלקוחה נכנס לדיר להתעשר. אז, רק נמצא שנכנס אם לא ניתן לכהן. זה נמצא כשהוא רק ספק פדיון פט"ח. גמ’ מוסיף שגם נמצא אם נפל לו פט"ח מאחי אמו כהן שנפלו לו מאחי אמו ישראל, שאז מפריש לעצמו. (יא.)
[fn:57] החידוש הוא שממע"ה הוא דין וודאי, ואז נתעשר, ולא נתמעט מ"עשירי וודאי.”
[fn:58] גמ’ מפרש (יא:) שהחי’ הוא שאם הפריש כדי לתת לכהן (בשה וודאי) ומת השה קודם שיתן אותו לכהן, נותן את השה המתה לכהן, שזכה בו מזמן הפרשה. (ע’ בהוספות אות יג.) לכאו’, ההו"א הוא או שעד שנותן לכהן יש איסור הנאה, או אם מת קודם נ’ לכהן, יש איסור לכהן.
[fn:59] דינים היוצאים מן המשנה (יש דינים שיוצאים ממשנה זה שנבאר בע"ה במשנה הבאה):אם יש לאודם וודאי בכור- מפריש שה ונותן אותו לכהן.ספק בכור- רבי יהודה- מפריש שה, להתיר בכור שלו בהנאה. אבל, לא צ’ לתת אותו לכהן. (רבי אליעזר?)רבי שמעון- לא צ’ לעשות כלום.
[fn:60] משנה ה
[fn:61] שכ’, “שה,” ואין זה שה.
[fn:62] כמו צבי ויחמור. ג"ז נתמעט ממה שאינו שה.
[fn:63] שני דברים הראשונים היו מינים חלוקים; שלש אחר זה הם שה במצב אחר, ואחד אחר זה הוא מין חלוק.
[fn:64] חלקו מהו המקור לזה. י"א שאין שה שחוטה נקרא שה (יומא מט:), ויש שדורשים אותו ממקור שנביא לקמן. (ע’ בהוספות אות יד.)
[fn:65] שלש אלו נלמדים מג"ש (“שה") מקרבן פסח, ששם לא יכול להקריב שחוטה, טרפה, או כלאים. (יב.)
[fn:66] חולקים מהו כוי, אם הוא מין בפנ"ע (ואז, מסופקים אם הוא בהמה או חיה) או הוא נולד מצבי ותייש (בין צבי ותיישה, בין תייש וצבייה). (עיין בהוספות אות טו.)
[fn:67] מסופק גמ’ אם פודים בנדמה. חולקים אם פודים בבן פקועה. לא פודים בפסולי המוק’, שהוקשו לצבי ואיל. לא פודיםוודאי בבהמת שביעית, שנח’ סחורה. (וא"ת אין שביעית בבהמה. וי"ל שנמצא אם קנה אותו בדמי שביעית.) (יב)
[fn:68] לכאו’, מרבה אותו מ"תפדה.”
[fn:69] נתן את בכור החמור.
[fn:70] יש ראשונים שכ’ (וכן משמע לשון המשנה) שלכת’ לא יתן לכהן (כיון שחוש’ שכהן לא יפדה אותו).
[fn:71] אף שכהן פטור מבכור בהמה טמאה, חייב אם נולד של ישראל.
[fn:72] גמ’ מבאר שבא לחדש שצ’ שיפדה לפני ישראל, שאינו נאמן על פט"ח. (יב:)
[fn:73] דינים היוצאים מן המשנה:במה פודים:דבר שאינו שה- לא. אבל, יכול לתת פדיון שלו לכהן, אבל לא הוא עצמו.שה- יש כמה קרק’ שפוסלים-שחוטה.טרפה.כלאים. בזה, רבי אליעזר חולק מוכשיר.נדמה. בזה מסופק גמ’.בן פקועה- בזה חולקים.פסולי המוקדשים.בהמת שביעית-בכור ספק- כשר.בכור ודאי- פסול.אלו לא פוסלים-נקבה וזכר.גדול וקטן.כבר פדה בו.בעל מום.
[fn:74] משנה ו
[fn:75] לכאו’, אז, רבי אליעזר סובר שפדיון חל רק כשנותן את השה לכהן. (ע’ בסוספות אות יז.)
[fn:76] גמ’ מבאר (יב:) שדורש ממש"כ "אך פדה תפדה…" להקיש שניהם זה לזה.
[fn:77] איני יודע מהו מקור של רבנן, שלעיל (לפי רבא), דרשו אותו היקש של רבי אליעזר.
[fn:78] כל זמן שאומרים שדבר נקבר, כוונתו לומר שאסור בהנאה, ולכן חייב לקבור אותו.
[fn:79] חולקים עוד לשיטתם, אם פדיון חל כשהפריש או כשנותן.
[fn:80] דינים היוצאים מן המשנה:אם שה שהפריש מת-דין שה-ר"א- לא קדוש.רבנן- קדוש. (כן נ"ל על פי טעם מח’.)דין בכור-ר"א יפרוש אחרת.רבנן- לא צ’ להפריש.אם בכור מת אחרי שהפריש שה-דין שה-רבנן- של כהן.ר"א- של בעל.דין בכור-רבנן- חול.ר"א- קדוש (אסור בהנאה, ונקבר).
[fn:81] משנה ז
[fn:82] לא כל כך פשוט מתי חל החיוב לערוף. גמ’ מצדד (יג.) שהוא אחרי שלושים יום, אבל דוחה את זה. אולי הוא מיד כשיכול לפדות (שהוא למס’ גמ’ שלשים יום, ואז יהיה כהו"א שהז’, ומטעם אחר). אולי הוא בכל זמן שבחר שלא לפדות כלל.
[fn:83] נראה שמקום עריפה הוא אחורי הראש. (ע’ בחולין יט:)
[fn:84] לעיל, הבאנו מחלקת תנאים אם הבכור מותר או אסור בהנאה. אם אסור מחיים, אסור גם לאחר עריפה. אם מותר מחיים, דן גמ’ אם אסור לאח"מ (יש אמוראים שסוברים שאסור). (ט:, י)
[fn:85] דורשים כן מג"ש מעגלה ערופה, שאסור בהנאה. מגמ’ יוצא (י:) שאפשר שצ’ קרא זה רק לר"ש, אפשר שצ’ קרא זה רק לר"י, ואפשר (כ”נ) שצ’ קרא זה לשניהם.
[fn:86] משמע שיש איזה קיום בעריפה. כ"כ רמב"ם, אבל ראב"ד חולק (ומפ’ שכעין עונש הוא).
[fn:87] ממשיך משנה לבאר דברים אחרים שבהם יש שני מצוות, ואחד יותר טוב מחבירו.
[fn:88] אם אדם קונה אמה העבריה, יכול ליעד אותה, והוא לישא אותה (או לתת אותה לאשה לבנו). אם לא עושה כן, משפחה פודה אותה (או יוצאת בגדלותה).
[fn:89] דנים אם מצוות יעידה שלו קודם לשל בנו, אבל משנה לא דן בהקדמה זו.
[fn:90] גם בפדיון דנו אם מצווה הוא. באמת, לא קל להבין איך מצווה ייחשב, שנפדה בע"כ. ראשונים מבארים שיקבל ברצון (אף שאפשר בע"כ) ויסייע.
[fn:91] אם אחיו מאביו מת, אדם חייב לבוא על אחת מן הנשים של המת או להחלץ מאחד מהם.
[fn:92] דנו ראשונים אם יש איסור מדאו’ לבוא עליה או מדרבנן.
[fn:93] זהו שיטת אבא שאול, וחכמים חלוקים עליו. אם עושה ייבום כשורה וחליצה כשורה, כולי עלמא מודו שייבום יותר טוב מחליצה. אבל, חולקים אבא שאול ורבנן במייבם שלא לשם מצווה, שאב"ש אוסר ורבנן מתירים. אז, כיון שחוששים בזה"ז שכן יעשו, אב"ש סובר שיותר טוב לחלוץ. (יבמות לט:) (גמ’ לא מפרש מקור של אבא שאול ורבנן.)חלקו ראשונים אם הל’ כאב"ש (כ"פ רמ"א מספק) או כראשונים (כ”פ ש”ע).
[fn:94] אם אדם מקדיש דבר, הוא יכול לפדות אותו, וגם כל אדם אחר יכול לפדות. משנה זה אומר שיותר טוב שהוא יפדה. (יש לדון אם זה גם כשאינו משלם חומש יותר, כמו אם אחר רוצה לשלם אותו מנין. שם, על כל פנים, אין חיוב; זה מפורש בערכין. גר"ק אומר שהוא רק מפני הוספת חומש.)
[fn:95] יש מצווה לגאול, לכאו’, רק אם אי אפשר להשתמש בדבר של הקדש בפ"ע.
[fn:96] רש"י כ’ שהוא במתפיס בהמה טמאה. לכאו’, זה לאו דווקא.
[fn:97] דינים היוצאים מן המשנה:לפעמים, מוטל על אדם אחד משני דברים לעשות, ולפעמים אחד יותר טוב:מצווה לפדות או לערוף בכור; פדייה קודם.מצווה על יבם לייבם או לחלוץ; ייבום קודם. (אבל, אם לא מכוון לשם מצווה, חול’ רבנן ואב"ש אם מותר לייבם.)מצווה על אדון ליעד או לחכות עד פדייה; יעוד קודם.שדה שנקדש נפדה מבעל או מאחר; בעל קודם.
[fn:98] פרק שני
[fn:99] משנה א
[fn:100] פרק זו מבאר את דין בכור בהמה טהורה. בכור בהמה טהורה נוהג בכל בהמה (ולא חיה) טהורה. זה כולל שור, כבש, ועז. הבכור הוא קדוש משעת לידה. צריך לתת אותו לכהן. אם תם הוא, מקריב אותו לקרבן בכור, ונאכל לכהן. אם בעל מום הוא, שוחט אותו ואוכל אותו בכ"מ.
[fn:101] דין בכור בהמה טהורה שווה לדין בכור בהמה טמאה בקנין גוי (בין בקנין בכור בין בקנין האם) שהמקור מדבר על שניהם.
[fn:102] לכאו’, כהן לא צריך לתת לכהן אחר. אבל, בבכור שלו יש דיני קדושה (אסור לשחוט אותו אלא במום או לקרבן).
[fn:103] יוצא מגמ’ (ד.) שאין פטור כיון שאין מקור שיש פטור. (וע"ש, שזה רק אפשר לפי מקור של רבא, אבל למקור של אביי, גמ’ לא מבאר.)
[fn:104] משנה ב
[fn:105] יש להעיר שנמצא, אז, שקדש בעל מום. אסור לעשות כן, אבל אם עושה כן, חל. (עיין בהוספות אות יח.)
[fn:106] אבל, לפני שנפדו, לא חייבים בבכורה, שאף קדושת דמים שיש לבהמה בעל מום דוחה קדושת בכור. (יד.)
[fn:107] לפני שנפדו, לא חייבים במתנות, כיון שיש להם קדושת דמים. (יד.)
[fn:108] רצה לומר, מותר לגוז אותו ולעבוד בו.
[fn:109] גמ’ מבאר (יד.) שזה רק אחרי פדיון. אבל, לפני פדיון, אסור. (עיין בהוספות אות יט.)
[fn:110] יש שלש מיני ולד:נתעבר לפני פדיון ונולד לפני פדיון- אינם חולין. אם יש להם מום, נפדים, ככל קרבן שיש לו מום. אף אם אין בהם מום, נפדים, שלא אפשר שיהיה הטפל (הולד) חמור מן העיקר (האם). נתעבר לפני פדיון ונולד לאחר פדיון- הם חולין.נתעבר לאחר פדיון ונולד לאחר פדיון- הם חולין. (יד)
[fn:111] חלב של קדשים אסור. אבל, כיון שנפדה, חלבו מותר.
[fn:112] רש"י (יד.) פי’ שזה אף קודם פדיון שלהם.
[fn:113] יש בזה שני גירסאות שמובאים בגמ’. יש שגורסים שהוא פטור, ומפרש שפוטר על חיוב שחוטי חוץ, כיון שאינו ראוי להקרבה. יש שגורסים שהוא חייב, ומפרש שמחייב על שחיטתו בבמה, שאף שם לא כשר במום, כיון שכ’, “לא תזבח לה’ אלקיך….” (יד:)
[fn:114] גמ’ מפרש (טו:) שבין לפני פדיון שלהם בין לאחר פדיון שלהם אין עושים תמורה.
[fn:115] קודם פדיון.
[fn:116] יכול להיות שתי בעיות בפדיון בהמה מתה:צריך העמדה והערכה. פסוק אומר, כשמבאר איך לפדות, שהכהן יעמיד אותו ויעריך אותו. כיון שאי אפשר להעמיד מת (שלא יכול לעמוד), אולי אין בו פדיון. בזה, צריכים לחלק קדשים לשני מינים:קדשי בדק הבית- רבי שמעון- א"צ, שכ’, “אותו.” בי לוי- צריך, שבהעמדה והערכה כ’, “בין טוב ובין רע,” שמרבה ציור שאין מום פוסל בו.רבנן- צריך, שכ’, “בין טוב ובין רע.”קדשי מזבח-רבי שמעון- צריך, שכ’, "אם בהמה אשר יקריבו…," אבל, אם קדם מום שלו להקדש שלו, לא צ’, שכ’ "אותו.” (צ"ל שמשמע מיעוט שני דברים.)בי לוי- צריך, שכ’, “אם בהמה אשר יקריבו….”רבנן- רבי יוחנן- צריך. אבל, אם קדם מום שלו להקדש שלו, לא צ’, שכ’, “אותו.” ריש לקיש- א"צ, שכ’, “אותו.” (יד:)יש שדרשו מ"ואכלת" למעט ציור שלא יהיה בהמה מותרת באכילה. כיון שמת, אם לא שחט אותו, לא מותר לאכילה. יש שחולקים על זה. מח’ זה נקרא "פודים להאכיל לכלבים או אין פודים,” כיון שסתם תשמיש של מה שאסור באכילה הוא להאכיל לכלבים.יוצא שכדי להיות שפודה אותו מת, כיון שהוא קדשי מזבח, צריך להיות כשיטת רבנן או רבי שמעון, וצריך להיות או ששחט או כמי שאומר שפודים להאכיל לכלבים.
[fn:117] לכאו’, זה ממעט אותו מכל דינים אלו, ודין שלו יהיה כקדם הקדש למום שלו
[fn:118] רש"י מפ’ שהמקור לזה הוא מה שקדושתו בא מרחם. (יד.)
[fn:119] רש"י מפ’ שהמקור לזה הוא שכ’, “בין טוב בין רע.” (יד.) (עיין בהוספות אות כ.)
[fn:120] דינים היוצאים מן המשנה:קדשים שקדם מום קבוע להקדשם:בכור- תראה משנה לקמן.מעשר- תראה משנה לקמן.שאר קדשים- יש שינוי דינים ב? דברים:מתנות. אדם חייב לתת לכהן חלק (זרוע, לחיים, וקיבה) של בהמה. לא חייב לתת לו של בהמת קדשים. בבהמה כזה, הדין הוא:קודם פדיון- פטור, כיון שיש בו קדושת דמים.אחר פדיון- חייב.בכורה. בכור של בהמה קדוש. אין בכור של קדשים קדוש. בבהמה כזה, הדין הוא:קודם פדיון- פטור, כיון שיש בו קדושת דמים.אחר פדיון- חייב.גיזה. אסור לגוז בהמה של קדשים. בבהמה כזה, הדין הוא:קודם פדיון- אסור.אחר פדיון- מותר.עבודה- אסור לעבוד בבהמת קדשים. בבהמה כזה, הדין הוא:קודם פדיון- אסור.אחר פדיון- מותר.ולד- ולד של קדשים קדוש. בבהמה כזה:נתעבר קודם פדיון-נולד קודם פדיון- קדוש הוא, אבל נפדה בלי מום.נולד אחרי פדיון- חולין הוא.נתעבר אחרי פדיון- חולין הוא.חלב. חלב של בהמת קדשים אסור. בבהמה כזה, הדין הוא:לפני פדיון- אסור.לאחר פדיון- מותר.שחיטה בחוץ. אסור לשחוט קדשים בחוץ. בבהמה כזה, הדין הוא:קודם פדיון- מותר, שלא ראוי למזבח.אחרי פדיון- מותר, שלא ראוי למזבח.תמורה. בדר"כ, אם אדם ממיר בהמה, תמורה קודש וקרב. בבהמה כזה, הדין הוא:קודם פדיון- לא ממירים, שכ’, “רע בטוב.”אחרי פדיון- לא ממירים.פדיון. פודים אותו, ואף אם כבר מת.
[fn:121] אגב, יש להעיר שמעניין שנקרא על שם ר"ח, שהוא שאל לר"א, ור"א חידש את הדין. היה נראה לבאר, אולי, פשט אחר בביאור שאומר גמ’ (יג.), והוא שיש עליו קושיה טובה, ולכן רצה להתחיל בו. (לכאו’, הענין הוא שבני אדם מרגישים מתיקות קושיה יותר משמרגישים מתיקות של דינים.) אולי לכן רשי רק מביא את השאלה, ולא התשובה. אבל, יש לדון, שריש ממשיך לומר, “וכו’.”
[fn:122] עיין שם, שתי’ הראשון הוא שכך גזר תורה. אולי לתי’ זה מכוון גמ’, שהוא נאה, שמראה שאנו עושים דברים מפני שכך גזרה תורה. אבל, יש לדון, שכיון שיש תי’ שני, אינו מראה כן.
[fn:123] יש להעיר שהבהמות לא בחרו, אבל עדיין נותן להם טוב בשביל זה.
[fn:124] באמת, יש לדון, לפי ביאור גמ’, למה משנה אומר קטע זה, ומהו ה"אף על פי.” הייתי אומר שמחמת זה היה נראה לקנוס, אבל גמ’ לא אומר כן. נראה שהוא שעשה כן אף שאסור. כיון שמזכירים העשייה, מזכירים דין שנוגע בו. ותחשב.
[fn:125] רוצים שיהיה על כל פנים ספק לפי ר"א, ולא שיהיה פסול לגמרי. אנחנו מקשים כאן שיהיה פשוט שאינו כשר. ותו"ת.
