- פרק א, הקדמה למשנה א, להיות קרבן אחר-
באמת, אומר זה לענין קרבן חטאת, שפסול שלא לשמו. יש לדון אם זה גם כן לענין דין לשמה שלא עולה. (מגמ' (ג.) נראה שנוגע בו.)
- פרק א, הקדמה למשנה א, לחלל קדשים-
לא ברור לי מהו הדרשה כאן. אולי דורשים את הקרא כאילו אומר כך: צריכים שלא לחלל את קדשי ה'. איך נחלל אותו? [על ידי הקדשים] אשר ירימו לה'. וצריך לחשוב.
- פרק א, הקדמה למשנה א, בעל קרבן-
כוונתי בזה הוא לומר שיש פסול אם חושב על מי שאינו בעל להיות הבעל. אבל, אין פסול כשלא חושב על מי שהוא בעל להיות הבעל. (יש לדון אם זה רק מפני שסתמא לשמו עומד, כמו שאומר גמ', או שאולי לפעמים זה לא יהני, ואולי אם חשב לשם אחד מן הבעלים, ולא לשם חברו, יותר גרוע מסתמא, אבל עדיין לא נפסל.)
למדתי את זה ממה שאומר גמ' (ד.) ששינוי בעלים לא נוהג בקרבן ציבור. רש"י מפרש שוהא מפני ש"הכל בעליו." אז, אף שיכול לחשוב רק על מקצת מבעליו, כיון שלא יכול לחשוב על מי שאינו בעליו, לא אפשר לפסול.
- פרק א, הקדמה למשנה א, מין קרבן זה-
כן אומר גמ' (ג:). אבל, כשאומר אותו גמ', אומר אותו לענין פסול חטאת, ולא לענין שאר קרבנות. אז, יש להסתפק אם אותו הדין נכון גם במק"א. עיין בתוס' בסוף ד., שמדבריו שם מוכרח שהוא אף לשאר קרבנות. (ויש לדחוק שרל שיש גרעון לשינוי בעלים במה שאי אשפר להיות מעכב גבי קרבנות ציבור.)
- פרק א, הקדמה למשנה א, ולא עולה-
** (תמשיך שם)
הנחנו שיש שני דינים כאן- איסור לעשות כן לכתחילה, ומה שלא עולה לבעלים. עיין בשי"ח ש"י בתחילת גלגל חמישי, שכל זה אינו כל כך פשוט. גמ' משמע שיש שני דינים, אבל אין כל כך מקור.
- פרק א, הקדמה למשנה א, במח' של"ש-
גמ' מבאר שאם אותו מחשבה פוסלת, נלמד מפיגול, שהוא מחשבה בעבודה על מנת לעשות דבר אחר (אכילה או הקטרה) שלא בזמנו). צריך ביאור ל"ל לומד משינו בעלים, שבו חושב לזרוק לאחר. אולי יש לחלק בחילוק לומדי. אולי שם, הפסול הוא שחושב עכשיו שהוא קרבן שיכפר לאחר, אבל פסול פיגול לא בא משם של זבח מחמת עבודה שיקרה, אלא מחמת שחושב על מחשבה שיקרה. הסיבה לזה הוא מפני שקרבן זה לא נשתנה מחמת מה שיהיה, אבל גבי שינוי בעלים, שמו נשתנה אם יכפר לאחר. אולי כמו כן לא יכולים לומר ששמו נשתנה מחמת שינוי קודש. ותחשב.
אבל, עיין לקמן בגמ' שאחר כך תולה אותו בקראי.
- פרק א, משנה א, נקראים זבחים-
גם היה אפשר לפרש שנקראים זבחים מפני שהם בהמות, ובהמות טעונות סמיכה. יש על זה שני קושיות:
1. אף עוף צריך שחיטה. ויש לדחות בשני אופנים:
  1. אולי לא צריך שחיטה מדאורייתא. עיין בחולין (כז) שחולקים תנאים בזה.
  2. אולי אף שצריך שחיטה, אין שחיטה שלו נקרא זביחה, שנשחט באופן חלוק מבהמות, שרק צריך חתיכת סימן אחד.
2. בהמה לא צריך שחיטה. אף שצריך שחיטה כדי לאכול אותו, לא צריך אותו לכל הנאה. לא כל כך מסתבר לומר שנקרא כן על שם מה שצריך כדי לאכול אותו, כיון שאין זה השתמשות של קרבן, שלא נאכל, אלא נקרב. (ויש לדון אם יש דמיון בין אכילת אדם להקרבה על מזבח.)
אבל, לא נראה כן; אלא נראה שהפשטות הוא כמו שכתבנו על המשנה.
- פרק א, משנה ג, מחמת גזירה-
עיין שם ביומא (או קרוב לשם), ועיין ברשי שמבאר שהוא גזירה. ויש לדון, אז, למה נוגע גבי זמן תפלת מנחה, כיון שאין גוזרים גזירה לגזירה. יש לומר שהוא גזי' דאו'. אולי רבנן תקנו את דינם כעין דאו'. גם יש לומר שלא תקנו רבנן שתפלה יהיה לו זמן של הקרבת קרבנות, אלא שיהיה כעין הקרבת הקרבנות. כיון שלמעשה היה הקרבן נקרב אז, אף צריך להתפלל. ותחשב.
- פרק א, משנה ג, ביחד-
אינו כל כך פשוט לי מהו כוונה של זה. גמ' אומר ש"בחד שיטתא הוה קיימי." היה נראה לומר בפשטות שכדי שבית דין יכריע דין, רק צריכים רוב (או קצת יותר). אבל, כאן, לא היה רק רוב, אלא כולם אמרו כן. (רק גבי חיוב מיתה לא הולכים אחר הכרעת כולם.) אבל, מרשי לא נראה כן, שרש"י אומר,  "בישיבה אחת היו יושבים וכולם היו כאיש אחד." אינו משמע שאומר כמו שפרשנו, אבל לא כל כך קל לדעת מה אומר, ומהו המעלה בקרק' שאומר. אולי כוונתו לומר שכולם פסקו כן לאותו סיבה, ולא לסיבות שונות. דחוק. (ראיתי שיש שמוסיפים לשון אחר ברשי שאולי מכוון לומר כמו שכתבנו.)
ועיין לקמן בהוספה בד"ה ת"ח שאולי על פי זה ייצא סיבה ל"ל פירש רש"י כמו שכתבנו.
- פרק א, משנה ג, ת"ח-
לא נראה לפרש שכוונת "שבעים ושנים זקן" הוא סנהדרין הגדול, שלא היה בו שבעים ושנים, אלא שבעים ואחרד או שבעים. אז, צריך לומר שזקן ר"ל ת"ח. ותחשב.
אם כן, לכאו', היו יותר משבעים ושנים זקנים, ורק אומר ששבעים ושנים מהם פסקו כן. אולי לכן לא פירש רש"י כמו שכתבנו לעיל (עיין לעיל בד"ה ביחד), שאין לומר רוב כיון שאין סכום המנין שבעים ושנים.
עדיין, יש לדון מי נכנס לכלל זקן, וכמה גדול צריך להיות. לכאו', באותו היום היו הרבה לומדים שם, כמו שמבאר אותו גמ' בברכות, ואז אינו כל כך גדול ששבעים ושנים מהם יאמרו דבר אחד. אז, קצת צריך לפרש מי נחשב זקן. (אולי צריך לציין לגמ' בקידושין שדן בעמידה לזקן.)
- פרק ב, משנה א, לשאר פסולים-
אינו לכל הפסולים ממש. עיין בארטסקרול על גמ' על משנה זה שדן בזה.
- פרק ב, משנה א, שלש קראי-
לא מבאר איך יודעים דין זה בשאר פסולים. אולי לא נוהגים כולם, אלא רק נוהג בדברים שמעכבים.
- פרק ב, משנה א, ממקום-
אומר גמ' כן בכיור, אבל מס' הוא נכון אף בכלי שרת.
- פרק ב, משנה א, ואף אם נאנס-
כן אומר רש"י, אבל ר"ת חולק. (עיין בתוס' כב:)
- פרק ב, משנה א, בגשתם-
בתחילה, גמ' רק אומר מקור מקרא. אבל, אחר כך, אומר אביי פסט שסומך על היותו דין דרבנן, ורבא חולק על אותו פשט. אז, לכאו' נראה שגמ' ראשון שאומר מקור מקרא הוא שיטת רבא, ואביי, לקמן, חולק על המקור.
- פרק ב, משנה א, מומר-
צריך לפרש מה נחשב בכלל מומר, כמו שדן גמ' בתחילת חולין.
- פרק ב, משנה א, מין אדם-
יש לדון אם החידוש הוא שלא נחשב מין במינו או שמין במינו חוצץ. ותחשב.
- פרק ב, משנה א, זה נדרש-
מגמ' מבואר שדורשים אותו לומר, "דם מהפר." אומר שקסבר שגורעים ומוסיפים ודורשים, שצריך לגרוע את המ"ם ממילה אחת ולתת אותו על מילה אחרת. משמע מגמ' שאין הכל דורשים כך, אלא יש תנאים שסוברים כן ודורשים כן, ויש תנאים שלא דורשים כן, אלא חולקים על דין של משה שלנו.
- פרק ב, משנה א, אף לוי-
לא מפרש גמ' מהו המקור לזה, שלכאו', לא יכולים ללמוד משיריים, שלא נדע שמקום זה הוא פסול לתת שם שיריים. (באמת, פשוט שפסול הוא כיון שאין בו נקב, אבל לא פוסלים שאר חלקי המזבח מחמת זה, וצריך לומר שסוברים שאין ללמוד מזה, שהשאר כשר לתת בנקב שבו, אלא שאין נקב. ותחשב.)
באמת, כל הלימוד צריך ביאור, שנלמד משם שצריך לתת אותם לתוך היסוד. ותחשב.
- פרק ב, משנה א, על המזבח-
לכאו', אז, רק דורשים שיכפר אם נתן על גב המזבח. לכן, אז, נמצא שדין של ניתן בפנים של חוץ ודין ניתן על גבי הכבש אינו כן. נמצא שלשמואל יש ציורים במנין זה שיש להם דינים חלוקים, ולריש לקיש, יש ציורים שיש בהם מחשבות שפוס' ויש שאין בהם אותם מח'. זה דחוק. עיין בתוס' (כו:).
- פרק ב, משנה א, לא יכול לתת דם עוד (ראשון)-
לכאו', זה אומר שאחר שאדם קיים מצווה, לא יכול לקיים אותו עוד, ולכן לא יכול לתת אותו. ויש לדון אם הוא מפני שלא קיים ציווי או מפני שלא קיים אף סיבות טובות. ותו"ת. גם היה אפשר לומר שמה שעושה שלא נקרב עוד אינו מה שקיים המצווה, אלא שזה משנה את הדם. צריך ביאור למה יעשה כן. ותחשב.
- פרק ב משנה ב, לא חייב כרת-
חושב אני שעובר בלאו, ואז מסתמא לוקה, אבל איני יודע.
פרק ב, משנה ג, בדבר שמעכב-
איני יודע מהו הדרשה, שלכאו', כל הקרא נצרך לגופו או נדרש לקמן (כט.). וצריך לחשוב ולעיין שם.
- פרק ב, משנה ה, רבי יוחנן-
עיין במה שנבאר. יש לדון אם רבי יוחנן סובר שרבי יהודה לא סובר שתופסים לשון ראשון, או שלא סובר שלשון ראשון סותר לשון שני, ולא סותר שרבי יהודה סובר שתופסים לשון ראשון כשאינו סותר אותו. לכאו', כיון שסובר כן, אין סיבה לומר שרבי יהודה סובר שתופסים לשון ראשון כלל. אז, הנידון הוא רק אם יש לנו ראיה שרבי יהודה לא סובר שתופסים לשון ראשון, לפי רבי יוחנן, או לא. ותחשב.
- פרק ג, משנה א, לומד את זה-
זה מבאר את הלימוד לזר. לכאו', כיון שלא צריכים כהן, לא צריכים שאר דברים גם כן. (יש לדון אם אין מקור שצריכים או שיש סברה (ממה שלא צריכים כהן) שגם לא צ' זה).
- פרק ג, משנה א, אם עושה כן כשר-
אף שגמ' לא תירץ כן, אלא תי' תירוץ שני, נראה שזה נכון. לא יתרץ קושיה שבא גמ' לתרץ- והוא שגמ' קאי על מה שאומר שכשם שאין סמיכה…, ושם בוודאי בא לדון בהיתר שלו. (אבל, עדיין יש לדון אם מה שכתבנו נכון, שלכאו', גמ' לומד, אז, ממה שלא מותר שלא יהני, שהרי לומד שחיטה מסמיכה, אבל לא לומד אותו ממה שמהני גבי שחיטה, אלא ממה שמותר. ותחשב.) ויש לדון אם הוא מצווה הבאה בעבירה. וצריך לחשוב על כל זה.
- פרק ג, משנה א, ששוחט צ"ל בתוך העזרה-
לא כל כל ברור לי מהו שיטת שמעון התימני. גמ' אומר שסובר שידי שוחט צ"ל לפנים מן הבהמה. לא ר"ל שלכן צ"ל ידיו בתוך העזרה, כיון שגמ' גם אומר שסובר (על כל פנים, סובר אותו מד"א שמוקים לסבור כשמעון התימני) שביאה במקצת לא שמה ביאה. אולי ר"ל שידיו צ"ל יותר קרוב לתוך עזרה (לכאו', ר"ל יותר קרוב להיכל) מן הבהמה. ממילא, נמצא שצריך שכל גופו יהיה בפנים, שא"א שגופו יהיה חוץ מעזרה, וידיו יהיו לפנים מן הבהמה, וישחוט. אבל, אף שלשון גמ' משמע כן, דחוק לומר שידרוש כן מקרא, שנראה מגמ' שדרשתו הוא רק שצריך שהשוחט יהיה לפנים ה', שהשוחט צריך להיות בעזרה. וצריך ביאור.
- פרק ג, משנה א, מקום הראוי לסמוך-
גמ' אומר כן לגבי דין צפון. לא כל כך פשוט הוא אם זה רק בקדשי קדשים או אף בשאר קרבנות, ולא רק לענין צפון.
- פרק ג, משנה א, סתם-
גמ’ מדייק מלשון קבלה. לא מבאר מה מדייק ממנו (מה מוזר בו שמגיד דין), אבל נראה שהוא מה שלא אמר אותו סתם, שזה מטעים טוב עם מה שגמ’ בתחילה ממעט ממנו זריקה, ושוב ממעט ממנו שחיטה. אילו היה רק שלא אמר זריקה, אז, אין דיוק השני מוציא מידי ראשון כמו שאומר גמ’, אלא שניהם יכולים להיות אמת. אולי יותר קל לומר קבלה כדי להוציא מידי שחיטה, אבל צריך ביאור למה. ותחשב.
- פרק ג, משנה א, להיות שיריים-
בזבחים, אומר שהוא דחוי. היה אפשר לפרש שהוא מפני שנעשה בדם פסול, והוא זריקה שלא כדין, אלא שמגמ’ מעילה (וכן מסברה) לא נראה כן. בגמ’ מעילה, אומר בפי’ שהוא ש“פסול עושה שיריים.“ ודע שנמצא, אז, שאומר לשון דיחוי לומר שיריים, אף שדבר שנדחה חלוק משיריים, ודיניהם חלוקים. צריך לומר שכיון שהוא נדחה מלכפר, יכול לקרוא לו כן.
- פרק ג, משנה א, שנית-
יש להעיר שהוא קצת יותר מזה. צריך לומר שלא רק לא צריך להשמיע דין, אלא שהיה יכול לומר אותו סתם, אף שעל ידי זה, קצת משמע שהדין נוהג בכ“מ- אף שאינו נוהג בכ“מ, שלא נוהג בשחיטה. צריך לומר שכיון שכבר באר דין שחיטה, לא חש למה שדין שנאמר סתם משמע, בלי ידיעה אחרת, שנוהג בכל מקום. ותחשב.
- פרק ג, משנה א, לשאר עבודות-
רש"י כאן מפרש שרק נקט עבודה ראשונה. עדיין לא מפרש ל"ל רק אמר אותו סתם (אם זה היה הקושיה, כמו שבארנו לעיל). ועיין במעילה, שקצת משמע שהוא לאו דווקא כאן, אבל במק“א (שם) הוא דווקא, ונקט אותו כאן אגב שם. אבל, עיין בגמ’ שם, שמתחיל כאילו יאמר כן, אבל לא מסיים כל כך כן. וצריך לעיין בראשונים שם, ובמה שכתבנו בשי“ח ש"י.
- פרק ג, משנה ב, אף שהפסיק-
אין דין זה כל כך ברור לי. עיין בגמ’ שם, שלא מכוון להוכיח ממה שיכול פסול לתת אותו לכהן. משמע שאף יכול פסול להוליך אותו קצת, אף אם הולכה שלא ברגל נחשבת הולכה. קשה, אז, למה לא נפסל בקצת הולכה מן הפסול, אבל נפסל בקצת הולכה שאינו ברגל.
אז, נראה שצריך לומר שגמ’ כאן מניח שהולכה לצד חוץ ממזבח אינו נחשבת הולכה (שאם נעשה בזר, אינו פסול), ולכן יכול לתת אותו לכהן, ולא נחשבת הולכה.
- פרק ג, משנה ב, שבטמא-
עיין לקמן (לד:).
- פרק ג, משנה ב, הקדמה, נדחה-
קצת צריך לבאר, לפי צד ראשון, מה נחשב נדחה. לכאו’, אין אומרים שהכל נדחה קודם שייצא הדם. אז, קשה למה זה חלוק משאר דברים שלא יצאו דם. אולי זה מפני שזה צריך עוד מעשה. יש להוסיף שאולי ענין של דיחוי הוא שקצת בזיון הוא להקדש שדבר יכפר כיון שהיה פסול. אז, צריך שהיה לו פסול יותר או פסול חלוק משאר דברים. אם לכל דבר יש פסול זה, אין בזיון בזה. ותחשב.
- פרק ג, משנה ג, אצל כל אדם-
יש לדון בזה, שאם הוא מפני שהוא דבר שאסור לעשות (שהרי יש דברים שנחשבים שאינם ראויים לאכילה, כיון שהם דברים אסורים), כל פיגול יהיה כן. לכאו’, נראה מזה שלא צריכים מחשבה שהוא מסבתר שיעשה, ויכול להיות מחשבה שבטלה, כדי להיות פיגול. ותחשב.
- פרק ג, משנה ד, לא חשובים די-
לכאו’, יש מאלו שהם בשר ממש. צריך לומר שכיון שעכשיו הם במצב שלא עומדים לאכילה, לא חשובים, אף שהיו עומדים, והם אותו מין של מה שהוא פיגול. ותחשב.
- פרק ג, משנה ג, האוכל או הקרבן-
כן מסתבר לי, אבל אין לי מקור לזה. רש"י אומר שהוא בטומאת הגוף; קצת משמע שאינו כן בטומאת בשר, אבל לא נראה כן מסברה.
- פרק ד, משנה א, ומעשר-
לכאו’, לא צריכים קרא למעשר, שהרבה דינים שלו כבר נלמדים בג“ש מבכור, וכבר למדנו שבכור צריך נתינת דם למזבח. ותחשב.
- פרק ד, משנה א, נלמד מחטאת-
לכאו’, לא יכול ללמדו מחטאת במ“מ, שהרי יש לחטאת קולות, שאין כולו נקרב לגבוה. אלא, נראה שנלמד מהיקש (”זאת תורת…“). ותחשב.
- פרק ד, משנה א, הקדמה, לא נחשבות-
גמ’ מפרש אלו בחטאת, אבל מסתמא (בפרט אם נלמדים מחטאת) דיניהם שווים.
- פרק ד, משנה ב, שיטת רבי מאיר-
יש לדון אם היה אפשר לומר שהולך לצד ראשון של רבי מאיר, אבל לרבנן, ולא לרבי מאיר. יש לדון אם מוכרח מן המשנה (עיין בלשונו) שחשב על הראשון לפיגול, שאולי אפשר לומר שרק חולקים אם פיגל בחצי מתיר, אבל אם חשב בראשון, כולי עלמא מודים שפיגל, כיון שרבנן סוברים שמניחים את הפיגול בכל המתיר. ותחשב.
- פרק ד, משנה ג, אם אוכל דברים אלו-
עיין לקמן, שנבאר שנלמד משלמים. קצת יש לדון מהיכי תיתי שאותו לימוד קאי על מה אוכל, ולא על מה חושב. באמת, היה מסתבר לומר שקאי על שניהם. ותחשב. וצריך לעיין בלשון הקרא, שאולי ממנו יבואר איך לדרוש. ותו"ת.
- פרק ד, משנה ג, שהוא דבר הניתר-
לכאו’, גמ’ מניח ששלמים שאומר קרא מכוון לבשר, שהוא דבר שיש לו מתירים. לולי זה, היה אפשר לדחות את הדרשה, לומר ש“שלמים“ כולל את הדם, ואז חייב אף על דבר המתיר.
- פרק ד, משנה ג, ולא דבר הניתר-
יש לדון בזה, שלכאו’, לא יכול להקריב קודם תמיד של שחר, שצריך להיות הראשון. (אולי זה רק לענין הקטרתו, ולא לענין מתן דם.) אול לא נחשב מתיר שלו, שלא משנה אותו, אלא משנה דבר אחר (מסתמא, המזבח), וזה עושה שמותר להקריב אותו. ותחשב. לא כל כך פשוט לומר שמשנה דם דבר שבאימורים, וזהו המתיר אותם להיות נקרבים. ותחשב.
- פרק ד, משנה ג, גבי שלמים-
כן הוא המקור שאומר גמ’ (כח:, מד.). אבל, יש, לכאו’, מקור אחר, והוא מדברי עולא (מג.), שלומד ממה שקובע דבר בפיגול שהוא עצמו אינו נחשב בר פיגול. אז, נוכל ללמוד ממנו שאין בו כרת, כיון שאינו פיגול. נראה שיש לדחות שלמס’ גמ’ עולא מיירי אחר שמשל בו אור. צריך לימוד משלמים לגלות פטור מפיגול קודם שמשלה בו אור. ותו"ת.
- פרק ד, משנה ג, שמרבה כל זבח-
ואם תאמר למה צריכים, אז, קראי המקדימים. כופו“כ לא קשה, שיש לומר שאינו מיותר. כן נראה, שגמ’ לעיל (כח:) דרש המילים של הכלל ופרט וכלל. נמצא שדורשים אף כופו“כ שאינו מיותר ככופו“כ. בשאר המילים, קצ“ב. אוליט אף הם לא מיותרים, אלא יש מהם משמעות. דחוק, שנראים מיותרים. אולי אילו רק היה קרא שאומר זבח, או כדומה, הייינו רק מרבים מה שדומה לשלמים ביותר. ותחשב.
- פרק ד, משנה ג, שמרבה כל זבח-
קצת צריך ביאור למה לא לומדים מ“זאת התורה לעולה…,“ שמקיש כל הקרבנות זה לזה. אולי כיון שהוא דבר שנוגע לאכילה, אי אפשר ללמוד מאוכל למה שאינו אוכל. מה שיכול לאכול ליותר זמן, אולי, הוא נחשב אוכל. מה שאי אפשר ללמוד מאוכל יהיה שלומדים את הדין, אבל הדין הוא שאכילת אותו אוכל עושה אותו דין, אבל זה אינו כן, שאינו אוכל. ותו"ת.
גם אפשר לומר שאין זה דין של הקרבן, אלא דין של האוכל, ואז לא לומדים מן ההיקש. זה אומר שאולי ההיקש לא מגלה דמיון בין הקרבנות אלא בדין. דחוק למה צריך לעשות כן, ודחוק שלא יוכל ללמד כן. ותחשב.
- פרק ד, משנה ה, קדושת הגוף-
לכאו’, אז, ממעט שני דברים:
1. דבר שקדוש קדושת דמים לבדק הבית.
2. דבר שקדוש קדושת דמים למזבח.
גמ’ רק מזכיר הראשון. חושב אני ששמעתי מגר“ק (בשיעור בוקר; ואולי אף היה על משנה זה) שלפעמים אומר ”בדק הבית“ כשרוצה לומר ”קדושת דמים,“ כיון שכל קדושת בדק הבית הוא רק דמים. (ויש להעיר שמעניין שמניח כן, שיש דברים שקדושים לבדק הבית, ומשתמשים בהם, כמו אבנים לבנות. אולי זה לא מצוי או אולי אף אז אין קדושת הגוף, אלא קדושת דמים. אם כן, צריך לומר שקדושת דמים אינו רק קדושה במה שרק עומד לדמים להקדש.)
- פרק ד, משנה ה, חוץ מן הדם-
עיין במה שבארנו בדרשות הפסוקים. לא מוכרח שהדרשה הוא לענין מעילה, ולומדים ממנו "אם אינו ענין" לשאר הדינים. אפשר לומר שכיון שכבר יש מקור למעילה, יכולים ללמוד דברים אחרים מן הפסוקים. צריך לעיין אם יכולםי להיות מקור להם. נדון בכל פסוק בפני עצמו.
פסוק ראשון אומר שהדם הוא שלכם. קל לבאר איך שדרשה זו אומרת שאין מעילה, שנוכל לומר שמעילה בא ממה שהוא של הקדש, ולא שלכם. לבאר שאין בו איסור נותר וטמא, יש לבאר בשני אופנים. אולי איסור זה ג"כ מיוסד במה שהוא של הקדש (שאז הוא קדוש, ואז נאסר). גם אפשר שמה שנאסר עושה שאינו כל כך שלכם, שאין לך כל הזכויות בו, שיש דברים שנאסרים.
פסוק שני אומר שהדם הוא רק לכפרה ולא למעילה. לכאו', קל לדרוש כל דבר משם, שכווונה של דרשה זו היא רק שמזכיר תוצאה אחת של הדם- כפרה- וזה ממעט תוצאה אחרת של דם- עבירה. אז, יכול למעט עבירת כל עבירה שמסתבר למעט משם (אבל רק אחד, כיון שנדרש מן הייתור).
פסוק שלישי אומר שדם הוא שווה לפני ולאחר כפרה. אפשר לומר שלא מסתבר שיהיה איסור טומאה לפני הקרבה, כיון שנלמד מפסוק נגד זה לעיל, ולא מס' כן בנותר כיון שנל' מטומאה. אבל, לא נראה כן כל כך, שיכולים לומר שקרא מחדש נגד זה בדם (מה שאין כן במעילה, שהוא שני כתובים הבאים כאחד). גם לא כל כך משמע שגמ' חושב כן, שהרי לא רק אומר את זה לענין מעילה, אלא דן אם מהני למעילה. (אבל, זה יש לדחות. אולי גמ' מכיר שכולם דרשות, ואז דן מה נעשים עם שלש אחרות, אבל גם מכיר שהובאו לדרשות על מעילה. אז, צריך לומר שיש שלש דרשות וחלקו אמוראים איזה מהם ממעט מעילה. כן נראה, באמת, מקריאת הגמ'. אז, רק דן איך מד"א שממעט מעילה מכאן דורש את זה. אבל, אולי לא פשוט ששאר השיטות דורשים את זה לענין מעילה. באמת, אז יוצא קושיה לשאר שיטות, אם מוכרחים ללמוד את זה למעילה. צריך לומר ששאר השיטות רק הביאו דרשה שהיה אפשר ללמד דין מעילה, אם לא שכבר היה מקור אחר. לכאו', עשו כן כיון שאין מקור זה כל כך פשוט.)
- פרק ד, משנה ה, אין חייבים עליה משום טומאה-
עיין במה שכתבנו בענין פסול שלהם. צריך לע' אם זה בטומאת הגוף, בטומאת בשר, או בשניהם- ומהיכי תיתי.
- פרק ד, משנה ו, לשם זבח-
עיין במקור שהבאנו. כן אומר גמרא כאן, אבל עיין בתחילת המסכתא, שהביא קרא אחר. צריך ביאור. נראה שאותו שהביא לעיל הוא המקור האמיתי, וכאן רק אומר רמז שיש לו בקרא (יש קרא שמשמע שמלמד לנו אותו דין). אבל, יש לדון למה אינו יכול להיות מקור.
- פרק ד, משנה ו, לשם ניחוח-
איני יודע איך זה שונה מכוונה לה’. אולי זה מחייב לו שיכוון שהריח יהיה ניחוח לה’. גמ’ לא משמע כן, שהיה לו לבאר את זה.
