* פרק ראשון- הכל שוחטין
* ב.
הכל- כל היכי- צריך ביאור למה אמר כן,שלכאורה, אינו שייך לכאן. אולי כוונתו לומר שכל זה מרבה דין ושגמרא יודע שירבה דין כיון שכל "כל" עושה כן, ושתמצא כן (שכלם נדרשים) בערכין. ותו"ת
הכל שוחטין- עיין בדיחוי שכתב. אין לדחות אותו פשט לומר שאם כן, אינו צריך לומר "הכל שוחטין,” שאולי בלי זה לא היה משמע שהוא לכתחילה, ועוד שכן דרך משניות, כמו שמבאר רש"י לקמן (ואגב, על זה יש להקשות למה הוא דרך משניות. ויש לדון. ואולי הוא רק מפני שרב משניות הם לכתחילה. ותחשב.)
* ב:
וכל הכל- כוונת גמרא הוא כן: גמרא הקשה מתחילת משנה לסופו. כיון שאין הכרח שזה לכתחילה וזה בדיעבד, אי אפשר שמקשה מכח סתירה. אלא, חשב, גמרא, מקשה שמיותר הוא. אם כן, צריך להיות שמניח גמרא ששניהם אומרים לכתחילה. מקשה גמרא מהיכי תיתי. אז, מסיק גמרא שמקשה ממה נפשך. ותו"ת.
תרתי דיעבד- כבר פירש ששם הוא הדרך, ורק בא לפרש מהו החילוק שעושהו דרך התנא שם ולא כאן. ותו"ת.
כקדש- יש לדון אם מי שאוכל על טהרת קדש נודר שרק יאכל דבר שאילו היה קדש היה טהור (כן משמע מלשון אכילה שבדרך כלל נאמר בו) או שינהג עם החפץ כאילו הוא קודש, ולא יטמאנו. לשון רש"י משמע כשני. ותחשב.
* ג.
קשיא- וצריך לדחוק לומר שקאי על קטן אף שלשונו לא משמע כן. ותו"ת.
התם מי קתני- צריך באור למה לרבא תני כן (שלא מפרש כן, ורק מביא מקור אחר לדברי רבא. ותחשב.)
* ג:
בודק לסכין- יש להעיר שיכול ליתן לו אותו בהמה ובהמה כשרה ולראות ולומר לו לאכול בהמה ששחט, שלא יאכלו אם אינו כשר. ודע שמעניין שלא מניחים שהוא מוזהר על לפני עור, שעל זה אינו מומר (זה תלוי במה שחוקרים אם הוא חלק מכל מצוה או מצוה בפני עצמה), ועל זה, לכאורה, אין צורך ואין תאווה. צריך לומר שבושתו הוא סיבה לו לשקר (שאף הוא מודה שהוא רע לאכול דבר אסור, ולכן, בדרך כלל, מונע מהם, ואז יהא נתבייש אם ידעו אחרים שאכל.) יש לדון, שכבר ידוע שהוא מומר. על כל פנים, אולי על פי זה נוכל לבאר שיאכל משלו, שיהא נתבייש, ולא יוכל לבדקו. ותו"ת.
הכא- כהרף עין שוהה- כמובן, אי אפשר לשהות כהרף עין. יש מזה כמה הערות:
1. מוזר למה רש"י נקט שהייה. זה לא קשה, שאולי אומר חידוש, שאף לזה יש לחוש, ואף שצריך קצת יותר זמן. יש לדון אי יש לזה נפקא מינא, שבין כך ובין כך, יש לחוש שדרס.
2. מוזר למה ינקוט "כהרף עין” כיון שאינו צריך להיות כל כך  מהר. צריך לומר שאינו דווקא, אלא רווחא דמילתא הוא. וצריך ביאור.
3. כיון שנקט שהייה, מוזר למה נקט כהרף עין.
4. כיון שנקט בהרף עין , מוזר שנקט שהייה.
ותחשב ותבין, שכל אלו ענינים חלוקים.
התם עיקר- לכאורה, ר"ל שאז שניהם עיקר, ואז יש בעיא למה נאמר שני פעמים, שאי אפשר לומר שחד רק נאמר אגב. יש להעיר שלא דוחה היותו אגב לומר שאינו אגב, אלא לומר שהוא עיקר. משמע שאין הבעיא שאין פתח לו, שאולי יש פתח אגב, אלא שיש בעיא לכפול דבר כשהוא, בשני הפעמים, עיקר. ותחשב.
* ד.
כיון דאחזוק- עדיין יש לדון מהו הדין לר"ש אם הוא כתוב ולא החזיקו. ויש לדון.
* ד:
ישראל מעליא- משמע שאין מומר ישראל מעליא. ונראה אולי שאין "ישראל מעליא" אומר שהוא כל כך ישראל, ולא חסר שם ישראל ממנו, אלא שהוא ישראל שהוא מעליא, והוא "a good Jew.” יש לדון בזה, שאם כן, קשה למה מזכיר "ישראל.” ואולי הוא מפני שפסול זה רק בישראל בקרבנות, ואז אמר שהוא ישראל- שהוא לפעמים שייך- שהוא טוב. ודחוק.
ויש להעיר שאי אפשר לומר, לכאורה, שאין למומר בעיא אלא שהוא קצת גוי, וזה הוא הסיבה לכל דיניו, שאם כן, צריך ביאור למה יפסל מהבאת קרבן. יש לדון, שיש לומר שיכול קרבנו לעשות טוב, כיון שהוא ישראל, בעיקר, אבל אינו זכאי באותו טוב, כיון שהוא גוי. ותו"ת.
מומר לערלות- אם כן, מוזר למה נקט ערל בדווקא; היה לו לומר "מומר" או "מומר לדבר אחד.”
כיון דדש- לכאורה, זה אומר סיבה שלא יוכל להיות שום מומר לתאבון (שאף אם מתחיל כן, לבסוף יהא כהיתר לו). גם יש לומר שחושב להרחיק, אבל כיון שלא שווה לו כל כך, ממילא לא יוכל לעולם להרחיק מן האיסור, ויטרוף.
כיון דדש ביה- מה שנקט טעם זה (דדש ביה), ולא מה שגילה שלא שווה לו (אלא אם כן נאמר שזה סימן. ואין לשונו משמע כן.) הוא שיש להקשות גבי מומר לעבודה זרה שעבודה זרה שקול ככל המצות, שכיון שכופר בה, אינו מאמין, בהכרח, בשאר מצות (ויש לדון, שאולי מאמין בה’, אבל אף באחר). אז, קשה למה חלוק ממומר לאותו דבר. צריך לומר- וכן אומר גמרא כאן- שהחילוק הוא שמומר כבר עבר, וזה סיבה שיעבור עוד, והוא יותר ממי שרק לא מאמין בו. ותו"ת.
ודילמא גברי- לא הבנתי מהו ההוה אמינא לזה; בוודאי כיון שהיו יראים מעיזבל לא יהיו עובדים בבית מלך. ואולי סבר גמרא שהיה להם שום שמירה כיון שהיו אנשי המלך, ואז לא חשו לה. (ויש להעיר שהיה עובדיה מאנשי המלך. וצריך ביאור בזה.)
מפני- שאם כן מצינו דמים- ואם תאמר אף בלי זה, אף שאסור להנות, שאסור להחליפו, אפשר, ואז יהא לו דמים. ודע שכל איסור הנאה כן, שיכול, אם רוצה, לאכלו. וצריך ביאור קצת בדרך כלל למה לא נחשב בזה דמים. ותו"ת.
* ה.
והעורבים- אולי יש לציין לגמרא (?) שאומר שאין דבר טמא בא משמים. ויש לדון.
שמייהו עורבים- לכאורה, ר"ל שהיה שמם אורב, ואז נקראו עורבים. ותחשב. וכן הוא שם הנזכר בגמרא שמביא.
שמייהו- אם כן, "ה" הידיעה  מוזר.
* ה:
מעם הארץ- יש להעיר שאפשר שצריך קרא למעט מומר לאותו דבר.
לכפרה- יש לדון אם הוא שזה שלא זכאי בכפרה (מצינו כמו כן במכות) או שכדי שיכפר צריך יותר כח, ואין למומר כח זה.
למימרא- יש לדון אם ר"ל שאין צריך לאומרו, שהוא דין פשוט (כן נראה מן הלשון), או שאין צריך לתקן כן (כן נראה הסברה).
רנב"י- מעניין שרנב"י ראה את ר’ יוחנן, שמשמע שהיה קצת קדמון[fn:1]. זה שייך לדיון של מי הוא ר"נ סתם. (ועיין בגירסת שיט"מ כאן).
לא מקבלי- משמע שכלל זה ש"אין הקב"ה מביא תקלה" אמור (גם) על מה שחושבים להיות תקלה, ולא (רק) על מה שהוא תקלה ממש. ותו"ת.
צדיקים עצמן- יש להעיר שיש מאלו שאינם איסורי אכילה, כמו דמאי, אלא שמעשה שגורם האיסור הוא אכילה, אבל אותו רע ממש (הפסד לווים, או עבירה על ציווי רבנן) יכול להיעשות באופן חלוק. ותו"ת.
ואית דגרס- יש לדון אם זה קאי על תחלתו, ואומר גירסא חלוקה מתחילתו, או על סופו, והוא שמבאר פשט, ושוב דן מה גורסים (ויש להעיר שבדרך כלל, דרך רש"י לבאר את הגירסה תחילה. ויל"ד.) לראשון, יש לדון מה חילוק יש בין גירסא ראשונה לת"כ. נראה (וכן נראה מד"ה) שגורב "שב" עם צירי תחת השי"ן. ויש לדון, שאין זה,לכאורה, נכון מכללי דקדוק. ואולי ארמית הוא.)
שוב ראיתי שאומר לשון "נמי" ("אית דגרס… והוא נמי"), שמשמע שהיה גירסא אחרת לפני כן שהיה לול אותו משמעות. ותו"ת.
אימא נקבל- גם יש לומר שהוא מפני שיש לו כל כך צורך או שהוא מפני שאין כל כך סיבה שלא לקבלו (שאולי רק בדורון יש בעיא ויש בזיון לה’). ותחשב.
שוב הבנתי שיש להעיר שלרשי לשון "חוב" מוזר, ואינו העיקר, שהעיקר הוא מה שבא מעבירה.
* ו:
בר בי רב- יש לדון מהיכי תיתי שדן בבר בי רב (מפרש רש"י בכ"מ שבי רב הוא בית מדרש, ואז, לכאורה, בר בי רב הוא תלמיד חכם). אפשר שמוקים משנה בזה. גם קשה למה מניח שתורה היתר; הרי ע"ה שונאים ת"ח (עיין בפסחים סופ”ג). גם אפשר לומר שיודעים שביני אדם מכבדים ת"ח, וחוששים שלא יבאור בני אדם אם ידוע שאינם מכבדים ת"ח. ויש לדו. ואולי אין כל ע"ה שונא ת”ח. אכתי מוזר למה נחוש. אפשר שבי רב רק ר"ל בית גדול, וכן חושבת על פונדק שלה. זה אף יתרץ קושיה ראשונה. ויש לדון.
שמא- צריך ביאור למה יש חשש רק כיון שאינו מעושר; הרי אף גזול הוא, שלא הניח עם הארתל לה לאכול. ואולי נקט זה כיון שלעולם הוא חשש, ואף אי נותן רשות.
אפשר- יש לומר שלא היו עובדים אותו עד כאן.
נותנת- יש לדון מה לנו שחבירתה נותנת לה; כמו שלא תיטול מעצמה, לא תיטול כשחבירה נותנת לה. ויש לדון אם זה נכון במציאות.
* ז.
מקום- מחודש הוא שיכולים להניח לעבודה זרה כדי להניח לו מקום. ותחשב.
לאו אדעתיה- יש לדון אם זה ראיה שהוא סבר כן או שהוא נכון, שאם לא כן, נמצא שבא לו תקלה. עיין לעיל שהוכחנו שיש מושג של תקלה במה שסובר להיות אסור; אולי רק בזה יש אותו מושג. ודע שבמציאות לא נראה לומר כצד שני, שמסתמא שני שיטות החולקים לעולם נהגו כשיטתם, ואף על פי כן, אין לעולם נוהגים כשיטה המיקל לומר שלא היה ה’ מניחו לעשות איסור. ותחשב.
חזי מאן- עיין בברכות שכתבנו צד אחר ממה שכתב רש"י בביאור לשון זה. כאן, לכאורה, מוכרח כמו שפירש רש"י שם, ואז נראה שאף שם ר"ל כמו שאומר רש"י.
כמשה- לכאורה, הוא ואנשיו היו כמשה ושש מאות אלף, ולא הוא לבדו. ואולי מביא ראיה ממה שהיה קורע רק לו, שרצה לשוב מיד אחר שעבר. גם יש להעיר שאולי שאני הכא שהיה בדרך לעשות מצוה. ואולי אף משה היה בדרך לקבל תורה. יש לדון, זלא היה הליכתם לים כל כך נצרך לזה (אלא היה נצרך כדי שלא יהרגום מצרים, אבל אינו דיירק”ט). ויש לדון.
מכאן- גם יש לומר ש"כאן" הוא מה שלפעמים יניחו מקום, ואז מה שלא עשו לעולם שום דבר אינו ראיה כל כך שלא לעשותו.
* ז:
חבטינהו- יש להעיר שאפשר שלא אכל אז כמה שחשבו, והא שרצה שיהא יותר טוב, ומה שעשה כדי שלא יהא תקלה הוא מה שלא אכל לאחר כך. ותו"ת.
רמו ליה- כיון שלא היה מקבל הנאה,צריך לומר שקנה אותם. אם כן, אפשר שמה שלא אכלם היה כדי לשא יארע לו רע. על פי מש"כ תוס’ שזה רק באיסורי אכילה, יש לומר שאי אפשר שהוא מפני איסורו, שלא היה איסור אכילה. ותו"ת. ואולי לא היו מקנים אותו לו, ורק שילם להם ממון ליתן אותו לפני בהמתו. ותחשב.
תקלה- כמובן, צריך לפרש איך יש תקלה כשבהמה עושהו. ויש לומר שאף שפשוט שאין ציווי בבהמה, אפשר שיש ס"ר (שהרי כאן, בוודאי יעבור מי שנתן לו. ותו"ת.
שמע רבי- עיין בגמרא שבת (לג:) שהיה ר"פ כתנו של ר"ש. ר"ש היה חבר ר"מ ותלמיד ר"ע והיה תלמיד בזמן ר"ג ור’ יהושע. רבי היה תלמיד של ר"מ. מעניין קצת, אז, שרבי ראה את ר"פ.
מלאך המות- יש להעיר שלכאורה לא היה איסור במה שהיה קונה אותם, שהרי לא שינה דבר בין זמן שקנה אותם ללפני כן, שאין דרך שהיו נשמרים. ותחשב. קשה, אז למה יש בו לפני עור. וצריך לומר שכיון שהוא הבעל,יש לו איסור. ותחשב.
בל תשחית- קשה למה לא אמר שבל תשחית אחרים שיזיק יותר רע.
בל תשחית- מעניין שמתירים עבירה על ידי זה (ומי יאמר שיכול אדם להנות מעבודה זרה כיון שבלי זה, יש בל תשחית. גם מי יאמר שיכול לקיים חמץ על פסח מפני זה. ותחשב.
במיתתם- יש לדון למה גדול, שרק חי לזמן. ואולי לא היה יכול לגרום אף זה בבן בילד שהחיה כשהיה חי. ויש לדון, שאולי זה מפני שלא כיוון לזה.
בגודל- יש לציין לגמרא שבת (פרק ר"ע) שאומר מעשה על רבא שיש בו היזק של אצבעותיו. אולי מכוון לגודלו, וכמו כאן. ודחוק.
ולפני- משמע שהיה יכול למכור לגוי בלי זה, אף שלכאורה לא ישמרנו יותר טוב. גם יש להעיר שמשמע שאין לגוי מצוה לשמור את חפצו. יש להעיר שעדיין חייב הוא על נזק. ואפשר שהוא רק מפני שוויתר ה’ את נכסיהם.
ודילמא- ולא היה יכול לו להחיות באופן אחר, שכיון שהיה מת, לא היה יכול לעשות יותר מנגיעה. ויש לדון, שהיה לו לה’ לגרום שיחיה אחר בחייו כדי שלא יצטרך לעשות כן על ידי נגיעה. ותחשב.
* ח.
והאיכא- מעניין שיהא כוויה של צדדים שכבר נשחטו (על כל פנים, אותו חלק מהם כבר נשחטו) בעיא. ואולי על ידי אותו נגיעה על הצדדים יהא כל הסימן נכווה. ותחשב.
חידודה- לכאורה, יש שני דיונים השייכים כאן:
א. אם חידוד של תחתונו של סכין בא קודם ליבונו. יש לדון למה הוא כל כך פשוט, שחודודו יבא קודם, שאמר רבא שיכול לשחוט לאט לאט (ועוד, שבהכרח יוליך ויביא).
ב. אם ליבונו של צדדים (שאולי רק לצדדים שהם גדולים חוששים) באים קודם שיהא צדדים נופלים ממנו. לא משמע כן מלשון קושייתו (“והאיכא צדדים,” שפשוט שיש צדדים, שעל זה היה גמרא גופא דן).
חבטה קדם אתי- יש להעיר שיש בזה שני הדיונים שהזכרנו לעיל. לכאורה, אחד מהם פשוטף ודן רק על השני- אותו דן בו בסכין. ותו"ת. דיחויי גמרא של חידוד משמע, לכאורה (ויל"ד) שדן בראשון.
מקלקל- מעניין, אז, למה אין לאיסור הנאה דמים, שהרי יכול לעשות בו מה שלא נחשב בעיני אחרים לטוב, והרי רב בני אדם רוצים בשום דבר כזה. ויש לדון.
* ח:
והלכתא- צריך ביאו למה צריך כן, שזהו הכלל בכל מחלקותם (שרבינא הוא המיקל, ושהלכה כמותו).
היכירא- עיין במה שכתב. לולי רש"י היה אפשר לומר שהוא שכיון שצריך שנים, בכל זמן יחשב, “האם זה הנכון?” מפני שיהיו שנים לפניו.
גם יש לדון לרש"י אם יש חיוב לעשות היכר (לא משמע כן מדבריו) או רק שמניחים שכיון שצריך שנים, יעשה היכר (או שיכיר כמה צריך להרחיק או כדי שלא להצטרך לקנות סכין אחר, אם שכח איזה הוא איזה). ויש לדון.
* י.
מפני שדרכן- משמע קצת (ויש לדון) שעושה רב על ידי מה שיש יותר כללים שיגרום דין זה מכללים שיגרום דין אחר. מעניין שזה יעשה רב.
* י:
ודילמא- קצת קשה למה לא אמר מתחילה שהוא בציור שאחר עומד ואומר לו אם שינה או לא.
עד אחד- עיין במה שאמר ביבמות; והוא, לכאורה, קיצור של מה שאמר כאן. ותו"ת.
ודע שיש לדון אם רש"י אומר שיש מקור שהוא נאמן (כן נראה מלשונו) או שלומד ממה שמקומות אחרים צריכים מקור לצורך עדות ואין לזה מקור (אולי כן משמע סוף לשונו).
אחזקתיה- יש לדון מה אומר:
1. אפשר שר"ל שזה רק לראות נגע, אבל לא לראות שלא נשתנה.
2. אפשר שר"ל שזה רק אומר שנגע שרק נראה בזה אינו נחשב נראה, אבל כאן, נראה לטומאה, ורק צריך שלא ישנה, ובודאי יכול לדעת שלא ישנה על ידי זה.
* יא.
דכתיב- יש להעיר שיש, לכאורה, שני דינים חלוקים הנלמדים מזה:
1. שיש ללכת אחרי רבים בדין.
2. שיש להניח שדבר הוא מן הרבים.
לכאורה, אין סיבה שווה לדינים אלו. ותחשב.
ליתא קמן- אפשר שמה שלא יכול להילמד הוא שצריך לדעת קודם שיש רב במציאות, ורק אז, נוכל לדון ברב. אז,יש שני סט"פים. ויש לדון אם פשוט הוא שצריך להוכיח שיש רב בעולם. ותחשב.
קטן- מעניין שחוששים לזה כיון שהוא רק קטן, ולא עובר על כלום, שאינו מצווה. לכאורה דומה למה שאין ליתן לו דבר אסור מחיים. ותו"ת.
* יא:
מאי נפקא מינא- לא הבנתי למה לא אומר שיש בעיא במה שאז אין שניהם שווים. ותחשב.
משום איבוד- אם כן הוא, ולא היינו הולכים בתר רב, לא היינו הורגים אותו. אם כן, צריך ביאור איזה איבוד נשמה יש. ואולי ר" שכיון שעשה דבר גל גך רע, ואיבד נשמה, ננסה להרגו (או שכדי לאבד נשמתו, נבדק). לא נראה כן, שמנסים להצילו.
ברבי- לא ידעינן- לא רק אמר שלא הוזכר שמו, אלא שלא ידעינן מי הוא. אולי לעולם מזכירים שם האומר דבר, להביא גאולה לעולם. גם אפשר שאם הוא כל כך חשוב עד שנקרא בריבי, היה לנו להזכיר שמו.
היכא דאפשר- ר"ל שבכל אלו הקיל תורה כיון שהיה כל כך טירחא בחומרא. גם יש לומר שרב קצת קובע מציאות, קובע שם למציאות על פי מה שבני אדם יאמרו עליו. אולי אין שם זה כל כך חשוב אם אפשר להשיג שם אחר על ידי בדיקה.
דחייש- יש להעיר שר"מ רק חושש למיעוט המצוי, ובכמה מאלו, אין המיעוט מצוי כלל. ותו"ת.
* יב.
פסח- יש לדחות ששם אין ספק מוציא מידי וודאי, ואז יקיים מצות אכילתו. (ועוד שעשה דוחה לאו.) ויש לדון אי יש מצוה כלל אם אינו כשר.
פסח וקדשים- מונה אותם בשנים כיון שלכאורה יש מצות חלוקות באכילתם, שבפסח יש אף מצות אכילת פסח. ותחשב.
* יב:
תורם שלא מדעת- מה אתם- יש לדון למה צריך זה, שלכאורה אם אינו מדעתכם, אינו שלוחכם. ויש לדון.
* יב:
הכי קאמר- לא סברה דידיה ולא רואה אני- לכאורה אלו שווים, ואולי רק מבארו. ותו"ת.
וכולם- לכאורה, אין צורך להביא קטע זה, שיש לדייק ממה שצריך טעם של קלקול. ומצינו בכ"מ שרוצה גמרא להביא משנה שאומר דבר בפירוש.
דתנן- היה אפשר לומר שלא ידעו מפני שכן תנן אלא שהבינו מסברתו. אפשר שלא אומר כן מפני שבין כך ובין כך היה אפשר להקשות איך לא ידע משנה. ויש לדון למה לא הקשה אותו קושיה (כיון שאין לתרצו כמש"כ). ותחשב.
מפני שיש להם מעשה- מעניין שתלוי מעשה של עשיית כלי במחשבה כלל (עיין ברש"י).
מעשה- יש לדון למה זה מהני:
1. אפשר שמה שמראה מחשבתו עושהו יותר חשוב.
2. אפשר שאין מחשבת קטן חשוב כיון שהוא כל כך קשה להבין. אם מראהו, אין לנו אותו בעיא. ולא נראה, שלכאורה, אף אי אומר מהו מחשבתו, אין לו מחשבה. ויש לדון.
* יג.
מקום הוא- יש לדון אם דן מה משמע מעשה זה או איזה משמעות צריך שיהא לו. ותו"ת.
קתני- לכאורה, ר"ל שהכי אמר ר’ יוחנן.
הא דמין- יש לדון למה מין הוא יותר חידוש לומר ששחיטתו נבלה, שישראל הוא. ותחשב.
טבלים- וא"ת אף סתם ע"ה כן. ויש לומר שנאמר רק אגב שאר. גם יש לומר שהוא אף קודם גזירת דמאי. גם יש לומר שאין לו היתירים של דמאי. גם יש לומר שהוא וודאי (ויכול להפריש עליו עם טבל מדאורייתא).
תנינא- וש"מ- יש לדון אם הוא רק על בבא זה או אף על כל הברייתא. נראה כשני, שאי לאו הכי, קשה מהו החידוש, שכבר נודע מן המשנה. ויש להעיר שמצינו, לכאורה (ויל"ד), שמובא תנינא להא שלא מוסיף. ואולי עדיין יש להביא ראיה שאי לאו הכי אין רש"י מוסיף כלום.
* יג:
מין- זה האדוק- מעניין מה שאומר כן מתחילה, ובסופו אומר כן ומוסיף קצת. ותחשב.
* יד.
ומיחל- מעניין מה שטוב שלא לסמוך על ברירה.
ומיחל- ואם תאמר אם אין ברירה, טבל הוא בין כך ובין כך. ויש לומר שרש"י לשיטתו, שסבר (עיין ברש"י ד"ה אוסרין, וכן הוא שיטת רש"י בכ"מ) שבוודאי יש תרומה, ורק חוששים שאינו מה שנשאר, ותחשב.
* יד:
מעין מלאכתן- יש לדון איזה מלאכה חשב שיש לו שאינו מעין ממנו, שאם מלאכתו אכילה, פשוט שהוא מעין ממנו, שהוא הוא, ואם אינו אכילה, פשוט שמוקצה הוא, אף בלי זה, שאין לו תשמיש המותר. שוב ראיתי שלא ידע גמרא עדיין דין מוקצה לאיסור.
לאכילה עומד- יש לדון למה, שהרי אסור הוא. ויש לדון. ותחשב.
* טו:
כגון שקצץ- אם כן, אין בישולו שייך, ששינוי של הקציצה הוא מה שאוסרו.
ור"ח- מעניין שרבי יסתום משנה כר"ח תלמידו (אלא שבדר"כ מוזר שיסתום שלא כשיטתו. ואולי אין זה כל כך קשה, שלפעמים אומר תנא או אמורא שאף שחושב שדבר נכון, אין לפסוק כן. אולי, אז, כן עושה רבי כשסותם. מוזר שיעשה כן לנגד ר"ח שהיה תלמידו.
* טז.
המשתחווה- ואם תאמר שיכול אסרו על ידי מעשה. וי שלומר שזה מעשה חלוש (עיין בסנהדרין, שיש צד שלא לוקה. עיין בשי"ח ש"י, שבאר שהוא מפני שלא היה שום אינטרקשי"ן חשובה בינו לבין החפץ. ותחשב.
* טז:
ה’ דברים- מנקבא- גם בו יש לומר שחוששים שיאכל סימנים ויהא בו סכנה. ויש לומר שאם כן, הוא שווה לחתיכת בשר.
* יז.
הותר- יש לדון למה אין אומרים הכלל שלעולם לחומרא מקשינן. אפשר שלא מסתבר לר"ע שבריו של ר"י. ויש לדון.
יש לדון גם כן אם כלל זה בכל מין דרשה (דנים בהל"ע ויב"ש ובדומה אם הוא אף בגזרה שווה). גם יש לדון אם נאמר כן כאן, שאין נפקא מינא, ולא נאמר על דין. אפשר שצלוי במה שיש לחקור (עיין בחבורת שי"ח ש"י) אם זה כלל בלי טעם או שמיוסד על טעם של ספק לחומרא. ותחשב.
נראה שיש לדון לר"ע אי לא היה ס"ר או שלא היו מצווים. אפשר שזהו השקלא וטריא של גמרא כשדן אם נחירה נקרא שחיטה. ויש לדון (שאפשר שאף בהוה אמינא סבר שלא היה ס"ר, אלא שעדיין חלוק מעשיהם, ויהיה להם שם אחר, ואפשר שרף במסקנה סבר שיש ס"ר, ושמילת שחיטה רק אומר המתה באופן שמתיר בשר).
גם יש לציין לדיון גמרא במה שהביאו עמהם. נראה שאם רק לא מצווה להם, יהיו מצווים כשבאו לארץ (שלא יכלו לאכול ממה שנחרו בא"י), ויהא אסור. יש צד שמותר רק אי לא היה ס"ר, ואם הוא לא היה מפני שינוי בבני ישראל אלא מחמת שינוי באותו בשר. יש לדון אם הדיון של גמרא הוא גופא בצדדים אלו או אם הוא מחמת שינוי בבנ"י או שינוי בבשר.
לאחר מכאן- אם כן, לכאורה, אף יש לדן במה שהיה נשאר מאותו שלל, ולא רק מבשר שהכניסו לארץ. כן נראה, שלא מסתבר שעדיין היה להם מאותו בשר לאחר שבע בנים. ויש לדון בזה, שאפשר שאין שני השאלות שוות, שאולי זה היה דין בבנ"י וזה היה דין במאכל. אולי כן מסתבר, שהותר כל מאכל. ותחשב.
אפילו כותלי חזיר- אם כן, צריך ביאור למה שהו לעומר (עיין גמרא קידושין לח.). ואולי זה היה רק בבשר. ודחוק. אף לתירוץ שני, יש לדון אם היה שום שלל של חדש.
* יז:
בריה דרבא- לשון "יתבי קמיה" משמע שהיו תלמידיו. אם כן, צריך לומר שהיה תלמיד ר"א גדול ממנו, שנולד ר"א כשמת רבא, ומסתמא (ויש לדחות) בן רבא נולד קודם לכן.
שלש פגימות- צריך ביאור למה לא מזכיר פגימת מזבח.
והוא- מגל קציר- צריך ביאור למה אי אפשר לומר ששם רק מטהרו ואולי אף כאן לבית הלל יעשה כן. ותו"ת.
* יח.
מחוברת- מעניין מה שיש פסול זה אף במחובר לבע"ח, אף שרבי רק אמרו במחובר לקרקע. לולי רש"י היה אפשר לומר שכוונתו הוא רק שקל לפסול שחיטתו אם הוא עדיין מחובר, ואז אינו כשר. ותו"ת.
* יט:
עורף- אם עורף רוצה לומר אחרית הראש, אז מה שרגילים כמה בני אדם לתרגם מילות "עם קשה עורף" ל"stiff-necked people” אינו נכון. ודע שבפשטות יותר מסתבר לומר שהוא "stiff-necked people,” שהרי לכל אדם יש עורף קשה, ור"ל שיש להם מול עורף קשה, ואז לא נוטים ממה שרואים. וצריך ביאור.
* כ:
התם כדי- מניח גמרא שלא קשה לקיים מצות הבדלה, אף שכבר מת. לכאורה, זה מפני שענין מליקה הוא אופן להמיתו. ויש לדון. ותחשב.
ההוא- אחרי המחמיר- יש להעיר שמניח שזה של דברי תורה, והרי זה גופא מחלקת. ותחשב.
* כא.
זקנה שאני- יש לדון למה לא אמר שבעל בשר שאני.
זקנה- יש לדון מהו הדין בעוף זקן, שלכאורה, יהא כמו עלי. ותחשב.
הותזו- משמע שכשמפרכסת לאחר מיתה, נחשב כבר מת. עיין בגמרא לקמן. אפשר שזה רק כאן שהתיז ראשם. כן נראה, דאי לאו הכי, אין צורך לדון מהו ההתזה.
כזנב- בפשטות, דן אם הוא סימן של חיות או לא. (וצריך לבאר מהו חיות.) אפשר שנחשב חיות כיון ששרב חיים עושים כן (ועדיין צריכים להגדיר מהו חיות שעושה חיים). אם כן, דמיון זה אומר שלא רק חיים עושים כן, ואם כן, אין סיבה לקראותו חי.
* כב:
אימא- ואם תאמר למה לא אומרים אף בזה "לא לשתמיט.” ונראה שני דרכים:
1. אפשר שסבר שאין צורך, שאין מה שמשמע מיעוט.
2. אפשר שסבר שאמרו, והוא שתורים לא רק יכול להשמיע כל תורים, אלא שכן משמע.
דומיא- יש לדון איך ידע לדרוש כן, ולא לדרוש שיהיה דמיון במה ששניהם כשרים בקטנים. ותו"ת.
לא לשתמיט- יש לדון למה, שכבר הדין נשמע. ואולי יעשה כן כדי שלא להיות מבלבל כלל.
* כד:
לכשיטיל- כל שהוא- יש להעיר שזה מחלקת בנדה. יש לדון אם עושה נפקא מינא לכאן, שאולי מה שיוצא עם מי רגליו גדול מאותו שיעור. ותחשב. וע"ש.
חמין- עיין לעיל שאומר שהיה ר"ח רופא. אולי אף זה צירף לעשות שהיה בריא.
התורה העידה- צריך ביאור מה הכרח זה ולמה הוא רק בדין מה שמטמא. ותחשב. עיין ברש"י לקמן, שמשמע שנלמד מדכתיב תוכו. יש לדון אם זה מחמת ייתור (עיין לקמן שם שאומר שהוא לגופיה). ותחשב.
* כה.
דחק- נראה שמה שזה למעשה לא מטמא הוא או שעומד מאד לו לשנותו, ולא נחשב נגמר כלל או ששינוי שישנהו יותר חשוב, שישנה מה תשמישו. זה יותר חושב או בדרך כלל לענין שם כלי או לענין טומאה. ותחשב.
* כה:
התמד- יש לדון למה לא אמר זה בלשון שאר המשניות (שהיה יכול לומר "בזמן שניקח בכסף מעשר, פוסל את המקוה.”).
* כו:
ולית הלכתא- כר"ד- יש לדון למה אומר כן כאן. משמע קצת שיש שום יחס בין שני הפסקים; וצריך לחשוב מהו. ותחשב.
* פרק שני- השוחט
* כז:
שנבראת- הוה אפשר לומר שכמו שברא ה’ את אדם מאדמה, כך עשה לבהמות (ולדגים, עשה כן ממים). יש שני הוכחות נגד זה:
1. אם כן, מוזר מה שהיה אדם נקרא על שם שבא מן האדמה; כל הבהמות באו משם.
2. לא משמע כן ממה שאומר גמרא לקמן (ס.) שנבראו כל בהמות בקומתן. ותחשב.
איתקש- יש לדון איזה דינים אחרים נלמדים מכאן לעשות אותו כלל. ותו"ת.
* כח.
מאן תנא- היה אפשר לומר שהוא אותו תנא של רקק. ותו"ת.
* כח:
אימא- אז, “בשחיטה" רצה לומר "בשעת שחיטה.”
הכי- מניח שהוא הלכה למשה. ויש לדון. עיין בעירובין שחולקים בכעין זה. אולי מביא לשון משם.
חלקו- מניח גמרא שמחלקת זה שייך בכל מקום. יש לעיין למה זה יהא ולמה לא יהא כן במחלקת כעין זה שבעירובין.
חכים- לא הבנתי מהו ראיתו, שהרי שם שדר ליה שמואל ולא ידע להשיב, ועשה כן שמואל לגלות שהיה הוא (שמואל) יותר חכם ממנו (רבי יוחנן).
שחט- היה אפשר לדחות שבכבר שחט וושט.
* כט.
לדם- צריך לחשוב על זה, שבין כך ובין כך יוצא דם. ותו"ת.
ואי אשמעינן- וא"ת למה לא אמר "ואי אשמעינן רק חד, הוה אמינא שהוא חולין.” ויש לומר שמן המשנה משמע על מה קאי. ונראה שלכן מפרש גמרא לאחר כן מהו המשמעות. (ועדיין מחודש הוא שמשמעות כזה יכול לגרום חידוש דין, ולא רק יבאר לנו אחר כן מהו מה. ותו"ת.
* כט:
מצוה למרק- יש לדון אם יש ענין במריטה זה חוץ מברב עם. אם יש ענין, מעניין שמזכיר זה (ויל"ד). אם אין ענין, מעניין שיש בזה "ברב עם.” ויש לדון.
* ל.
אי אמרת- מניח גמרא שכיון שיש פסול בתחילת שחיטה, יפסל. יש לדון למה. אפשר שלצד זה כל שחיטתו הוא חד מעשה ממשיך. ותחשב, כמובן. גם אפשר שרק אומר לנו קרא שכשר כשיש שחיטה מתחילה ועד סוף, ואין לנו מקור להכשירו כשיש רק כעין זה. יש לדון, שאולי הוא מה שתריך עקירה. ותחשב. ויש לדון אם נלמד מקרא.
בכל זה הנחנו שפסול שלא לשמה עושה רק שאין שחיטה. גם אפשר שהוא פסול, ועושה דבר רע, וכיון שהוא בזמן שחיטה, ואף אי אינו בזמן כל שחיטה, יפסול. ותחשב.
נהי דאידחי- יש לדון, אז, למה צריכים שיהיה חייב להביא קרבן פסח שני; עומד הוא לדמי פסח של שנה הבאה. ותחשב.
עיין ברש"י שכתב ש"אין לך מום גדול מזה.” כתב עמק ----- (מובא בהג’ על רי"ף ביבמות) שלשון זה לא אומר שהוא הכי גדול, אלא קטן הוא, והא לחדש שאף שיש צד לומר שהשאר גדולים ממנו, אינו כן, ואין גדול מזה. יש להעיר שרש"י אומרו על זה; ולכאורה, מום גדול הוא (ויש לדון, שאינו כל כך ניכר).
שמא יטרפו- במקום אחר כתבנו שמרש"י (לב.) משמע שמה שאין תחילת שחיטה עושה טרפה הוא שכולו מעשה שחיטה. מעניין בציור ששני בני אדם שוחטים, שנצטרך לומר ששניהם הם מעשה שחיטה, ואולי אף ששניהם הם חד מעשה שחיטה. וע"ש.
* לא.
אבל הכא- אלא רבא דייק- עדיין קשה למה מקשה למה הוצרך רבא להשמיענו כן שני פעמים; וקשה למה, לרבא, צריך לומר הדין שני פעמים. ותו"ת.
אמר רבא- נראה שלכן סובר שמסתבר לסתום משנה כמותו.
* לב.
אותה- הענין הוא ש"אותה" משמע שהוא מיוחד. אז, צריך שיהא כלל שבו הוא מיוחד. הוה אמינא שכללו הוא קדשים הנשחטים, והוא המיוחד בזה. ותו"ת.
מאי כדי- יש לדון מה היה צד האחר של השואל. אולי חשב שהוא זמן מתחילת השחיטה או זמן לגמור שחיטה זה. יש לדון למה יהא משנה על פי מה שכבר שחט. ותו"ת.
לא הוה בדיחנא- יש לציין לסוף המסכתא שאומר דין שאמר ר"ח, ולא הבין רב כראוי. ותו"ת.
תיקו- יש לכתוב כמה מהלכים למה אין כל בהמה נעשה טרפה (או בעל מום) בכל שחיטה:
1. אפשר שמשמע מרש"י שכיון שהוא באותו מעשה של שחיטה, אין אותו תוצאה נחשב נעשה עד סוף מעשה. זה רק כאן, נראה ממקומות אחרים, כיון שהוא סותר תוצאה חשובה של מעשה (היתר בשר). מצינו משוג כעין זה לרש"י ב"מה לי קטלא. . . “ בפרק מרובה. ותחשב. ועיין בצדי צדדים.
2. אפשר שכשעושה כן בתוך מעשה שחיטה, אין פסול טריפה. זה לא באר כל כך, ורק אמר הגדרה.
3. ודע שצריך לדון בזה לצד שאין לשחיטה אלא לבסוף. ותו"ת.
4. אפשר- וזה אפשר ל2- שענין טריפה (ולא יתרץ בזה בעל מום, לכאורה) הוא שאז אין כל כך שחיטה (ולכן, אולי לא כל כך פשוט לגמרא ששחיטה מתירה. ויש לדון.), שאין שחיטה גורם היחידי של מיתתו, שיש גם כן טריפותו. כן משמע ממה שיש צד לתלות דין טרפות על דין שחיטה (גבי דגים). אז, פשוט שאם נעשה טרפה מחמת שחיטה אינו בעיא, שכולו מחמת שחיטה. ותו"ת.
5. אמר לי א.מ.ו. שאפשר שאם יש לשחיטה מתחילה ועד סוף, תחילה בפני עצמו יהני (עיין לעיל שדנינו אי סוף בפני עצמו יהני), אלא שרק נקרא תחילתו שחיטה אם גומרה. ותחשב.
שהייה- יש לדון אם פסול הוא או שרק גורם שלא  ייחסו שני חלקי שחיטה זה לזה.
* לב:
כאן ששחט- יש לדון מה לנו בזה.
ומשנה- לא שכחוה- לכאורה, זה הסיבה שלא עקרוהו. ותחשב על לשונו.
משנה- ממשנתם- יש להעיר שמשנה זה נעשה מוטעה קודם קודם כתיבת משנה, ואף על פי כן, לא זז. מעניין, שכמו שלא כלל משניות שלא היו נראים לו (ונעשו ברייתות), כך שלא יכלל זה. ואולי רצה לאומרו מפני דין טרפות זבו, וןלא רצה לשנותו מפני שבני אדם זכרוהו באופן אחד. ותחשב.
* משנה- סתם- זה מעניין. ותחשב.
לג.
כיון דאיכא- רצה לומר, לכאורה, שלישראל יש קרק’ חשוב של אותו מצב- שנשנחט (והוא חשוב לו כיון שנצרך כדי להתירו)- שיש לו יחס (או שגורמו או שבדרך כלל, כשהוא שם, אף מיתה שם) עם מיתה. לגוי, אין אותו קרק’ כל כך חשוב. יש להעיר שקצת קשה למה לא נאמר כן בנחירה לגוי כיון שקבלו עליהם שלא למכור בשר המת (עיין לקמן). ואולי כיון שרק במכירה הוא (ורק קיבלו) אינו כל כך חשוב. ותחשב.
* לד.
בשר- יש לדון אם אז אי אפשר (שאומר עליו שינהג בו ניהוג שירחיקו מאיסור- אבל אין ניהוג כזה) או לא מסתבר שיעשה כן.
דקתני- לולי רש"י, היה אפשר לומר שעושה כן כדי להרגיל את עצמו בשמירה זה. יש לדון אם, אז, יש צד שיעשנו בבשר, שלמעשה, מרגיל את עצמו בשמירה. אבל רש"י אומר שחושש לחילוף. ותחשב. דע שגם היה אפשר לומר פשט אחר, והוא שיש לדון למה אין איסורי טומאה של תרומה וכדו’ שייך גבי חולין, אם יש שום ס"ר או לא (אם יש, יש לדון אם הם רק פחותים או שמחמת שיש בו כל כך טורח, הותרו). אם יש, אפשר שלכן יקפיד אדם על טהרת חולין. לא משמע כן מגמרא זה, שאם כן, יעשה כן אף בבשר. ותחשב.
* לה:
שמא תשב- יש להעיר שלעיל דן גמרא על משנה ראשונה למה אמר לשון עתיד כיון שר"ל חשש על שעבר. אולי לשון גמרא הוא לדבר כן אבל לא לשון גמרא. ויש לדון.
* לו.
שהיה ר"ש- לכאורה, זה מוכיח שענין הליכה בתר רבים בפסק הוא שיש יותר צד שהם נכונים כיון ששניהןם חשבו עליו, שכאן לא חשבו שניהם על אותו סברה. ואפשר שכן הוא, וכאן יש יותר צד שהוא נכון כיון שיש שני תלמידי חכמים שסוברים סברה שיעשנו נכון (ואם נניח שיש לכל תלמיד חכם פראבאביליט"י שווה להיות נכון, יש לו יותר פראבאביליטי אם סומך על שניהם, אף אי חולקים. ותו"ת.) יש להעיר שרבים בדרך כלל יש גם כן הוכחה נגד יכיד ממה שלא אמר כן רבים. אולי אינו כן כאן, שאולי ר"ש מודה לרבי, ורק סבר שאין דיני שחיטה שייך כאו. ותו"ת.
מאחר- לשון זה מעניין; היה לו לומר "נסמוך על הרבים,” ולשון "מאחר. . . “ משמע שרק עושים כן כיו וש יש לנו ספק, ולא נדע מה לעשות. ותחשב. ולכאורה, אין לנו ספק, שהלכה כרבי מחבירו. ותחשב.
* לז.
מסוכנת- אין הכרח להקשות כן, שהיה אפשר לפרש שמשנה אומר שאלו סימנים שאינו ממש מסוכן, ולא שעדיין חי. ותחשב.
שאת החיה- מוזר מה שלכאורה לא יודעים פירוש מילים שבתורה (ובדרך כלל אין צריכים לדון בזה).
* לז:
אי אמרת שריא- קשה, שאף אמר שלא חשב ביום וגרם קרי בלילה. ואולי ר"ל שכיון שזה איסור, צריך להיות שום רבותא בו, ויש רק זה. ויש לדון בהא דבשר פגול. ועיין לקמן שדן גמרא בדין זה, שתלוי בציור, ואם כן, היה אפשר לאוקמיה בציור שיש לו היתר (כל זה רק אי אסרו חכם, והוא חושב להתירו. אבל אולי כאן דן במה שמתיר חכם, והחידוש הוא שחשש לספק. אם כן, בוודאי הוא מותר.). גם, לכאורה, יש היתר למתנותיה.
מתנותיה- הוא כהן- אף בלי זה, אולי אין איסור (עיין לקמן שדן בזה, שר"י אוסרו. ולא פוסק כמותו. ועיין בתוס’ שם.)
* לח.
אי ממתניתין- יש לדון על מי היה מקשה:
1. על רב. אם כן, יש להעיר שצריך להיות שפשוט לומר כפירוש שמואל רב, שאי לאו הכי, אינו מלמד כלום.
2. על שמואל. והוא ששמואל מבאר רב, ומקשה גמ’ עליו שאין צורך לביאורו, שכל מאמרו פשוט, ולמה לו לשנותו ולבארו. אם כן, אפשר שמחדש דבר שלא נשמע מרב, ורק אומרו על רב כיון שיותר נשמע עליו. גם אפשר שמקשה למה מפרש רב כן, שאם הוא נכון, אין בו חידוש, ובוודאי יש בו חידוש.
משמו- יש לדון משם מי אמר.
הוצאת נפש- עיין לעיל שדנינו למה צריך להיות מפרכס. אי אפשר שהוא שלא יהא מסוכנת מפני מש"כ שם (אם לא שנפרש שיש שני מיני מסוכן, ויש אסור (צריך ביאור מהיכי תיתי. שוב אפשר שאולי נלמד מחשש של יחזקאל. ויש לדון, שאולי חשש שכבר מת. ואולי היה מכיר את זה בקל, ורק חשש שהוא מסוכן עד שעומד למות.) כשעומד למות. ודחוק.) אפשר שהוא שמגלה שחי הוא. א, זה קשה, שאם כן מהו "רק הוצאת נפש הוא"; אם כן , בוודאי היה לו נפש, ואז היה חי. ותחשב. אפשר אולי שהוא שצריך להיות חי בשחיטה (כן נראה, אגב, שבזה דן כיון שאומר לשון של "כל היכי תיחי ותיזיל".), והוצאת נפש הוא בין חיים למיתה. הוכחנו במקום אחר שיש כזה מדיון גמרא ב"ב מתי חל מתנת שכ"מ. ועיין שם. גם יש להוכיחו ממה שאמרו חז"ל שמתו בכורי מצרים בחצות. יש לדון, אז, אם בזמן שהיה שמש באמצע רקיע היו חיים או כבר מתים (noun), שלשון חז"ל משמע שהיו מתים (פועל) אז, משמע שיש מה שהוא בין מיתה לחיים. חושב אני שהיה לנו עוד ראיות לזה. ותחשב.
אבוה- אם היו מכירים את הבן, מעניין שקראו אותו על שפ אביו. ואולי היו אחרים עם שמו. גם יש לומר שהתחילו בני אדם שידעו אביו לקראותו כן, עד שכל בני אדם קראו כן, ואף מי שידע אותו יותר מי ממה שידע אביו. ותו"ת.
* לח:
סוף לידה- צריך לחשוב על ענין זה, שאולי קפדה תורה על דבר חלוק כאן מכאן. ועיין לקמן. ויש לדון.
סוף לידה- יש לדון אם הדמיון הוא בפירוש קראי (בשניהם אומר שבאותו עת צריך להיות חי, ודיון בשניהם הוא מתי הוא אותו עת) או בדין (אולי אם יכול להיות חי למקצתו, יהא מחמת שום לומדות שכיון שהוא חי למקצתו, כאילו חי לכולו. אם כן, אולי זה שייך בשווה לשניהם). ותחשב.
* לט.
בשלמא- רביה- מצינו מקור לזה בגמרא בתחילת פרק אין עומדים (לא.).
בשלמא- מעניין שיחלוק מסברה (ושיהא נשנה למחלקת) קודם שילמד משניות (ובפרט כיון שאמר גמרא שבתחילה ילמד אדם ושוב יחשב עליו). ותחשב.
לשון אחר- אכתי יש להקשות על לשון ראשון שלו איך לא ידע משנה. ואולי מודה ללשון קמא במה שהיה, מתחילה, חולק בלי ידיעת גמרא (כמובן, זה מפני שהיה אותו מעשה של פרק שביעי של ב"מ, ואז לא ידע כל כך כשהתחיל ללמוד. ואולי אז לא היה לו כל כך זמן ללמוד.), ורק דן מה גרם לו לחזור בו כאן. ותו"ת.
* לט:
ואי לא- מעות- לא הבנתי איך מתרץ את זה. ותחשב.
טייעי- וכן דרכן- יש לדון מה אומר בזה:
1. אפשר שאומר שכן עשו לשום רק מפני שכן נהגו (ר"ל לשום סיבה שנתחדש לפני זמן, ולא ידעו על מה), ולא לעבודה זרה בייחוד.
2. אפשר שמבאר רש"י שכן הוא דרכם אף בזמנו. יש לדון למה אומר כן. ותח’. ואולי אמר "אל תתמיה על זה, שכן עושים היום, ואין מתמיהים עליו,” שכן דרך בני אדם, שכשאומרים דבר אחר שלא מובן, לא מתמיהים על דבר ראשון ששמע שלא היה מובן (מסתמא לכן נותנים ראשי הישיבות כל כך כמה שיעורים).
* מא.
כיון דקניא ליה לכפרה- יש לדון אם אומר שיש קנין שגורם שהקרבת בהמה מכפר לו, וזה עושהו קצת שלו, או שמה שמכפר לו (ואז, לו בא הנאת אותו בהמה) עושהו שלו. יש להעיר שלצד קמא, אפשר שבמסקנא, לא רק אין קנין זה די, אלא אולי משנה גמרא למה מכפר (שאינו מחמת קנין כזה). ותו"ת.
בישראל- שותפות- יש לדון, שלצד זה, מניחים שלא ממש עובדו, אלא מכוון לצער את חבירו. אם כן, אף אם יש לו חלק, נניח שלזה מכוון, ולא נאסור את הנעבד. ותחשב. (ואפשר שסבר רש"י שרק מניחים כן מפני שדחוק לומר שעובד את עב"ז שלו שלא מהונו. ותו"ת.)
* מא:
מידע ידיעה- עיין ברש"י טעם האיסור. אם כן, מובן מה שתלוי על מה שבני אדם חושבים.
* פרק שלישי- אלו טרפות
* מב.
ובשר- יש בזה שני קושיות:
1. פשוט הוא, ואינו צריך לאומרו.
2. אינו רמז, אלא אומרו בפירוש.
* מג.
מעשה ניסים- עיין במה שפרש"י שהיה קשה לשטן שלא להרגו. כיון שהיה מחייהו על פי נס, נמצא שמה שקשה לא היה עשיית דברים שיצערו ולא ימותו, שאף אם בדרך כלל ימותו, את איוב לא ימותו. ואולי היה קל לו לגרום ניסים אלו. אמר לי א.ד.ר. שאולי היה בצער כיון שרצה להרגו. לא נראה, שמגמרא משמע שרצה שיכפור בה’ ושלא יהיה טוב כאברהם. ותו"ת.
יש להעיר שמשל לעבד קצת מוזר לפי זה, ששם מצער למצוא דרך לשוברה בלי ביטלו יינה. ותו"ת.
אלא ניסא שאני- לכאורה, לשונו משמע שבא להוכיח שנס שאני. זה, לכאורה, פשוט, שאיך יוכיח שום דבר כיון שאינו רגיל. אלא, מוכיח שזה היה נס. אם כן, לשונו מוזר. ותו"ת.
הלכה כסתם- מרש"י יוצא שאי הלכה כסתם משנה, לא יהא סיבה לעדף חד (ואף שחד בתרא, שהרי רש"י סבר שאין סדר כי אם לסתם ומחלקת, שבו דקדקו. ק"ק למה לא ידקדקו כאן), אבל אי אין הלכה כסתם, נפסוק כסתם, אלא שאפשר להיות סיבה לפסוק יותר כחד.
מאי שנא- היה אפשר לו לומרש שאני הכא שיש לו חזקת כשרות, שרב בהמות אינם טרפות, והרי נשחט כראוי. (אגב, מבואר לעיל שאין ספק טריפה נחשב ספק בשחיטה (ח?), אם כן, משמע נגד מה שכתבנו שטריפה פוסל שחיטה.
מאי שנא- נמצא שיש שיטה שדין ספק דאו’ לחומרא הוא רק שכשיש חזקת איסור או שכבר קבוע איסורו. זה נראה מחודש.
* מד.
כאן קודם- מוזר לרבי יהושע למה יהא בת קול כיון שאין נפקא מינא ממנו. ותו"ת.
בתורא- יש לדון מה אומר:
1. כי קאמר רב בתורה [הוא] משעיר יותר [משאר מינו]. מוזר למה ידון בזה.
2. כי קאמר רב בתורא, ש[בדרך כלל] משעיר יותר [משאר מיני בהמה].
סתם שמעתתא- זה מעניין. ודע שצריכים לפרש, אז, מהו החילוק בין מה שנאמר משם ר"י ומה שנאמר סתם, ולמה כאן נקט זה וכאן נקט זה. אולי היו אמוראים חלוקים אומרים דברים חלוקים. ותחשב.
* מד:
והא כתיב- קשה, שלעיל הניח גמרא שאין אלו איסורים. ואולי סבר שהיה לו להקפיד על אלו.
זה הרואה- לולי רש"י היה אפשר לפרש שהוא שיש לו חכמה לראות. נראה שרש"י לא מפרש כן כיון שמפרש קרא בזה וכיון שאם לא כן, לכאורה, שווה (ויש לדון) לשימוש תלמיד חכם, שאיך יפסוק בלי זה.
* מה.
אתייקרי- כמובן, צריך ביאור למה אין אומרים כן בכל מתנה, שכל מתנה הוא רק לטובת הנותן, שאי לאו הכי לא יתן אותו. ואפשר שיש להגדיר- ועדיין צריך לבאר- שאם הטובה לא בא ממה שמקבל את המתנה, אין לקבלו. ותו"ת.
נקבים- אם אין בהם חסרון, צריך ביאור איך יצטרפו. ותו"ת.
* מה:
מוחו- צריך ביאור מהו הדיון; אם מודה, אין מחלקת. (ואפשר- ודחוק- שיש צד שהוא כמו שאמר גבי ב"ה וב"ש גבי נטילה, שכל אחד אמר חד ולא חולקים.)
שמינה- יש לדון, אז, איך נבדוק שמן. ותו"ת.
* מט.
או על ידי- לולי רש"י, היה אפשר לומר שאין סמנים בפני עצמם עושים כלום. ותו"ת.
אווזא- יש לדון אם ר"ל שכן ראויים ליקח סמנים או שבזה נלקחים. ועיין ברש"י.
* מט:
ואת אמרת- לשון זה משמע שלא היה תלמיד של רבא. זה שייך לדיון מי היה ר"נ סתם.
* נ.
ולדידן- יש לדון, ששניהם תלוי בחד דבר, ואיין סיבה יותר להקל בסתימתו. ותו”ת. וצ"ב.
אמר- גם יש לומר שלא רצו לכתוב שמו, שלא היה איש ידוע. ויש לדון.
* נא:
ואיני יודע- יש לדון למה לומר שום דבר כלל. ואולי אומר שלא קל לפרשו, וזה שייך למי שרוצה לפרשו או כדומה. גם אפשר שממעטו למקום צר. ותו"ת.
מהו דתימא- צריך ביאור למה זה יותר מחודש. ותו"ת.
איסתמכא- יש לדון מה אומר. אפשר שאומר ששמע פשט, אבל אינו יודע אם הוא נכון. גם יש לומר ששמע שהוא אותו שם, ולא ידע איזה חפץ יש לו אותו שם. גם יש לומר שר"ל ששמע שבני אדם משתמשים עם אוות מילה, ומסתמא, סבר, הוא אותו איסתמכא של משנה, אבל לא ידע על מה מכוונים אותם בני אדם (וצריך לומר שנעשה אי אפשר לשאול להם). ותו"ת.
* נא.
מפטיר- יש לדון מהיכי תיתי שלא רק הפטירם.  ותו"ת.
* נב:
כי איתשיל- יש לדון אם זה סיבה או סימן. יש לדון למה יהא סימן. אולי הוא מוכיח שהוא הנפקא מינא הכי מצוי או הכי נצרך לדעת (אולי לתוצאות שאינם להלכה).
אורחא- לכאורה, לא משמע כן כלל מר"י. ותו"ת.
רב כהנא- כעין זה רואים בתחילת פרק עשרים של שבת.
חמשה- מניח גמרא שאי היה עליה דם, נתן עליו ארס. היה אפשר שרק עשה לו מכה (scratch) מבלי לתת בו ארס. ותו"ת.
בריבי- בדרך כלל לא אומר כן. אולי שאני הכא שהוא בריבי בפני עצמו, ואינו מזכיר עמו שם. ויש לדון.
* נד:
חביבה- לולי רש"י היה אפשר לומר שאומר שהוא חביב לפני ה’. ודע שלרש"י צריך ביאור מה דוחה גמרא, שעדיין צריכים לכבדו, ואף אם הוא לטעם של גמרא. אפשר שרק מבאר ההו"א. ואפשר שר"ל שצריך לכבדו בדברים אחרים (ולומד מכאן). גם אפשר שרש"י מודה למש"כ, ורק מבאר במהו הנפק"מ, והוא לכבדו בכל דרך שיכול. ותו"ת. גם קשה למה שאומר רש"י למה אומר "חביבה,” ולא "צריך אדם לחבב.” ותו"ת. (מה שכתבנו בסוף זה יתרץ לזה.)
* נו:
הורו- ק"ק למה אין צד שאומר שהורו על טלפחת להיתר ובזפק הורו כרבי להיתר. ותחשב.
* נז.
חזקיה- מכאן רואים שאינו בעיא לומר שלא ידעו חז"ל את המציאות. אפשר ששמר ה’ שלא יטעו מחמת זה (ושלח מי שיגיד לו את המציאות), שבהמותם של צדיקים . . . כל שכן. ויש לדון.
* נז:
אהימנותא- גם יש לומר שידע לא מרוח הקודש אלא מפני שהיה יכול לדבר עם חיות.
* נח.
בשיחלא- עוד קשה שלכאורה אז אין זה הסיבה, שאסור כיון שנטרפה עם אמו, ולא כיון שנגמר באיסור. ואולי אינו כן. ויש לדון, שאב היה סיבה לתחילתו, ולא נתמעט היותו סיבה משיחלא בתרא. ותו"ת.
רבי אליעזר- לשיטתו הוא בפסחים ובכ"מ.
* סב:
כל שנשתמה שמו- משמע שהענין הוא שיש מיעוט לעולם ממה שלא מזכיר אותו מין (שהזכרת מין כללי לא נחשב הזכרה עליו), אבל אין מיעוט למה שהיה כן שמו אז. לולי זה, היה אפשר לומר שפשוט שלא ממעטו, זאנשי אותו דור לא ידעו, בהכרח, למעטו, ואם כן, צריך לומר שהוא בכלל אותו דין. אולי נוכל לומר ש"נשתנה שמו, נתחדשה הלכה.” זה, לכאורה, אפשר רק אם שינוי שמו הוא סיבה, ולא סימן, שאם הוא סימן, לא ישנה. (ונראה שאפשר שחלק ממה שעושה מצוה טוב הוא שמה שאמר ה’- ולא רק מה שכיוון ה’- ומה שעשה הם שווים. כאן, הרי יש שם חלוק למה שעשה).ותו"ת.
גם יש לדון למה לא אפשר לתורה למעט מה שלא היה לו שם עדיין; מצינו (כתובות) שיש דברים שנקראים על שם עתיד. יש לומר שאף על פי כן, כן היו שמם, אלא שנקראו על שם עתיד. כאן, לא היה זה שמם. אפשר גם כן שאין הענין כאן שאי אפשר לומר שמו האחר, ואז אינו מיעוט, שזהו מה שנקרא, אלא שאין רואים מיעוט כיון שאף זה שאמר תורה היה, אז, שמו. ותו"ת.
* סג.
יפה כח הבן- ר"ל בת.
* סג:
רואה נבלה- נראה שזה רבותא כיון שארף ישראל גבוה, ואין כל כך "bird’s eye view.” לאידך גיסא, כיון שהיה באויר, גבהות א"י עושה שהוא קרוב יותר לו.[fn:2]
* סד:
בת שירה- יש להעיר שאמרו מעי בני ישראל שירה על הים (כתובות?).
* סו.
בי רב- עיין בר"ג ב"ב (קכד) שגורס "ספרי דרב," שמשמע שמרב נשנו, ולא בבי רב (בית מדרש). ועיין שם, שגם כן גורס דבי רב. ותו"ת.
* סז:
בהמה בשחיטה- מעניין שיהא חלק מבהמה על כדי כך שצריך שחיטה, אבל לא עד כדי כך ששחיטת בהמה מהני. ותו"ת.
לויתן- אין להביא ראיה ממה שיעשה ה’ סעודה ממנו לצדיקים, שהרי מצות בטלים לעתיד לבא.
* סט:
לטעמיה- צריך ביאור למה ייתלה ביציאת רובו; למה לא נאמר שכיון שכשיצתה כולו, נמצא שיצא רובו בלידה, הוא קדוש למפרע. ותחשב.
* ע.
למפרע- ואם תאמר איך יכול לזרוק, שיצקרך לחוש שיקדש. אפשר שרק נעשה קדוש אי יש בכור לקדש. כאן, אין בכור, וכמו שאילו לא ילדה אלא יצא דרך רחם לא היה קדוש, אף כאן לא יהא קדוש. ותו"ת.
* עג.
ידות- יש לדון בזה, זאם נחשבים כבר נחתכים, יש חלק מן הסורפ"ס שלא טבל, והוא מקום חיתוחו. ותחשב. אפשר שכמו שאומרין שאין צריחים לטבל ידות כיון שהוא כאילו אינו שם, אומרים שהוא כאילו נכנס שם מים. יש לחלק, שעל ראשון, יש לומר שהענין אינו שמחשיבים אותו כאילו אינו שם, אלא שהדין הוא שצריך טבילה רק על חלקים חשובים של כלים, וכיון שזה עומד ליזרק אינו חלק חשוב. ותו"ת. אבל זה לא יהני לעשות שנגע מים במקום חתך. אפשר שאין יד הכלי חציצה, שהיינו רבותיה. יש לדון, שאינו צריך להכניסו כלל, ואז, אינו רק חציצה, אלא לא הכניס כלל. ותו"ת.
* עה.
דגים- יש לדון מה לנו בשחיטה, שזה לכאורה לא שייך לדין טרפות. משמע שיש שום קשר בין איסור נבלה לאיסור טריפה. אפשר שהקשר הוא שכיון שאיין חייו גדול, האופן שנוטלו לא שייך. אם כן, אולי אף פגם בו אינו בעיא. ותו"ת.
* עו.
טעון- יש לדון בזה, שלכאורה מה שסומך על שחיטה לא עושה שהוא אחד מאבריה. אפשר שיש לו שני שמות, ואם על שם אחד יותר, מותר הוא. וצריך ביאור. וצריך לחשוב.
אין לו- זה, לכאורה, מוכיח שאין ענין שהייה שאז נעשה טריפה בחתיכת סימן ראשון. ודע שאם כן, הוא פסול מעניין, שלכאורה, אינו כל כך קרק’ של מעשה שחיטה, כמו דרסה או כדומה. וותחשב ותבין.
גדולה מזה- משמע שגדדול מזה הוא שהוא הכי גדול. יש לדון, שאולי אין זה הכי גדול (אלא קטן) מפני מה שכתבנו לעיל בד"ה אין לו).
יש להעיר שאם אין לשחיטה אלא לבסוף, מה שקרה לסימן ראשון שלו, אולי לא נחשב שחיטה (יש לדון, שלאם, נחשב שחיטה). יש לדון אם זה יגרום שאין לו שחיטה עוד. ותחשב.
* עז.
דרבא- יש להעיר שזה רבא סתם. מוזר שלא מזכירו בשמו ושלא ידע אביי להביאו לפניו כיון שהיו לומדים ביחד אף לפני זמן (יש מעשה בברכות בהם וברבה) (יש לדון . ועיין בגירסת רש"י שם.). ויש לדחות.
* עט.
אותו- מוזר שיהא אותו אומר רק נקבה. צריך ביאור למה לא אמר אותה.
* עט.
אין מרביעין- יש להעיר שיש שיטה (ר"י בע"ז) שאין שבור מקבל זכר. אפשר שיש חילוק בין גידם לשבור.
* פ.
מוזר שיחלקו מהו כוי; צריך לבאר איפה נזכר שיחלקו מהו; ידונו בשני מיני חיות וזהו. וצריך ביאור. ואולי אחד מרבם אמר כן. אפשר שרק משתמשים במילה בתרגום חלוק. דחוק. אמר א.ר. שאפשר שהיה מין ידוע שלא ידע איך בא. מוזר שלא יראנו נולד ושלא יוכלו לבדוק (יש לדון, שהוא כלאים. אכתי, יש מיני היתר לעשות כלאים (עיין בגמרא בבא מציעא).
* פא.
נתקו לעשה- יש לדון מה לנו בזה; אין לומר שהעשה מכפר או כדומה, שהרי אחר שעבר על לאו, אי אפשר לקיים עשה זה. ותחשב.
התראת- מאדם חריף- יש לדון אי ר"ל ששבשו מה שאמר אותו חריף או שאף שאמר דבר זה שהוא משובש, אל תבזהו, שהוא בדרך כלל חריף ומפולפל.
ואזדא- יש להעיר שלמש"כ בדיבור שלעיל, אינו התראת ספק.
* פא:
כיון דכי- משמע שהענין הוא שכיון שפטור בזה, אגבו פטור בזו. יש לדון למה אין אומרים אגב לאידך גיסא (לפעמים, גמרא מקשה כן). אפשר, גם כן, שרק אומר סימן. ויש לדון מהו. לא משמע לשונו כן כל כך.
* פג.
בא- נמצא שהשיטה הידועה הזה אשר ממנו מדייקים שיטתו לענין לאו שאין בו מעשה יכול להיות שאינו נכון.
ומודה- אם ר"י לא חולק (חולקים אם בלשון זה חולק או מפרש), נמצא שאומר מודה, אף שאין חולק. אפשר שאני הכא שאומר "מודה.” ותו"ת.
יכול אף זה כן- זה מעניין, שיכול להיוות שאין זה בקדשים. ואולי אינו לאותו שיטה.
* פג:
בעפר- עיין במה שפירש, והוא שאי יש עפר עליו ותחתיו, נמצא שהוא בדם. לולי רש"י, היה אפשר לומר שמרמז לנתינתו על גב קרקע, שאז נבלע בתוכו, ונמצא שהוא בעפר. ותו"ת.
* פד.
וליפריקינהו- לכאורה, לא צריך לפדותו ממש, אלא כיון שיכול, נחשב שחיטה ראוייה. ויש לדון.
ונסיב- בכ"פ כשאומר כן, לא סובר כן רבי (עיין בגמרא תחילת שבואות, וסוף הוריות (וברא"ש בשני המקומות). ותו"ת.
ליטרא ירק- עיין בגמ’ שבת (קמ?) שאומר שלא יאכל שום אדם (ואף עני) ירק.
אמר"י- יש להעיר שהיה בעל בשר (כן אני חוזב, אבל שכחתי מקורי לזה).
לווים- לא ר"ל הוא עצמו, שהיה חתן נשיא (וכן משמע מלשון רש"י (“עלינו ללות . . . “)).
* פד:
רוצה לאבדן- לכאורה, היה לו להקדים את זה, שהוא היותר שייך לדיון גמרא לעיל. ותו"ת.
אישתומא- נמצא מרש"י (ובאמת מגמ’) ש"אשתומם שעה חדא" לא אומר שלא היה יודע איך לתרץ, והיה חושב, אלא שהיה מתמיה על הקושיא (blown away). ויש לדון, שאולי הוא הוא. ותחשב.
שהן- יש לדון מה אומר. אולי אומר שזה טוב, שכיון שיעשה כן להם, אף ה’ יתן לו יותר ממה שראוי לו מדה כנגד מדה, ואז אין לחוש לאבדת ממונו.
* פד.
ראה רבי- יש לדון למה צריך לשנותם בלשון רבים; הרי דברי ר"מ הם כבר סתם ואחר כך מחלקת, והוא דינו כרבים. יש לתרץ:
1. אפשר שלא היה רבי הסותם, אלא הוא כתב את המשניות ועל פי שאם קביעות סתמם. אם כן, לא היה יכול לעשות כן על ידי סתימתו. מוזר שיניחו אותו מנין לו לעשות כן. ואולי לא הניחו, ועשאו כיון שהיה ברור לו שהיה נכון.
2. אפשר שלא ידע שיקבלו בני אדם את הסתמים.
3. אפשר שלא כתבום בסדר (אף שסדרו בסדר), ואמרו ברב קודם. משנה לא זזה ממקומה.
4. ותחשב עוד.
אטו- לר"ש אינו נוהג, אבל זה גלגל החוזר.
* פו.
די לו- משמע שהוא שלא נתן לו ה’. לשון די לו לא משמע כן.
היה מחייב- זה לא מבאר יותר. וצריך ביאור. ותחשב.
* פו:
שמע מינא- לולי רש"י, היה אפשר לומר שממה שששלחו רק זה, צריך לומר שהיה, בפעם אחת, רק זה. צריך לומר שהוא ראישון. לא משמע כן כל כך מגמרא. אפשר ששלחו כלכ ך מאוחר בחייו שלא מסתבר כן.
* פז.
צדוקי- נראה יותר ככופר מצדוקי. ואולי יש מהם שהיו כופרים.
* פח.
הכשר- לכאורה, מצוה עצמה היא. ותחשב.
* צ:
שכן- לכאורה, רצה לומר שהוא איסור שנתוסף על אחרים. גם אפשר שהוא סיבה אחרת; ותחשב.
גוזמא- יש לדון איזה חלק ממנו הוא הגוזמא. ותחשב. ועיין ברש"י. ויש לדון.
* צא.
מבואר מגמרא זה שלא היו יעקב ומלאך אבוקים ונגע בו, אלא שעשה כן ללו בדרך בהפתאה. לשון קרא (“כי לא יכול לו") לא משמע כן כלל, ולא מדרהרים בני אדם כן.
* צא:
קפצה- מוזר שקפץ ושוב מהר לבא שמש; לא יקפוץ כל כך, ולא נצטרך נס שאני.
* צב:
בשר המת- רואים כאן, וכן ראינו בכמה מקומות ממסכתא זז, שיש מושג שיש בנחירה מעין של שחיטה. ותו"ת.
בשר- יש להעיר שבשר אדם הוא בפרהסיא, שלכאורה, קל להכיר שהוא בשר אדם (ויש לדון). לכאורה, אינו כן גבי בשר בהמה שמתה. ותו"ת.
חתובה- מוזר שזה ממה שקבלו, שביאתם הוא כבר נאסר משבע מצות. אפשר שכבר הותרו (כגמ’ ריש ע"ז). גם אפשר שקבלוהו עוד (רצה לומר שקבלו לשמור חיובם). גם אפשר שהיו כותבים בתובה (לפני כן) ועושים נשואים בלי ביאה. לא משמע כן מרש"י.
מדרבנן- לשון ברייתא לא משמע כן. וצריך לומר שאינו בעיא שאומר דבר שהוא נכון רק מדאורייתא.
* צג.
טבחא- יש לדון אם זה כל כך שייך. ותו"ת.
* צד:
** .
והא- מחזיק לנו- משמע שהבעיא אינו מה שסובר שהוא מכובד לחנם או כעין זה, אלא מה שמחזיק טובה. ותו"ת
* צה.
איתחזק- אחרים- משמע שמה שקבוע שם איסור אינו סיבה בפני עצמו לאסור; הוא רק סיבה להניח שיש יותר איסורים שם. מעניין, שלכאורה, יהא  חילוק אשם תלוי אף אי יודע בברור שיש רק אחד שם.
* צה:
היכי אכל- יודעים שאכל כיון שאמר גמרא (פסחים) שהיה אוהב לאכול גוזלות.
סימנא- לכאורה, זה מניח שסימנים דאורייתא.
דרביה- יש לדון איך ידע, שמשמע שאף שלא היה ר"י מכירו, הוא היה מכיר ר"י. אולי ראה מה ששלח לרב חברו או מה ששלח לו באותו אגרת ראשונה.
לא ידע- ואם תאמר הרי היה שמואל בא"י (היה רופא של רבי). אולי אז לא היה עדיין רבו של ר"י (או שלאחר כן גדל ר"י הרבה).
* צו.
האיך- יש לדון, שדילמא היה סימן מתיר גם זה, אלא שבדרך כלל לא נמצא. ואולי לא ר"ל שהוא ראיה יותר גדולה, אלא שהוא יותר יוספא"ל.
* צו:
ורבנן- מעניין מה שאי אפשר לומר שכמו שמה שהוא בריה מחשיבו לאסרו, גם עושה שנקרא אכילה. ואולי רק מקשה שהוא מיותר. ולא נראה כן.
כבשר- כרוב- יש לדון למה לא אמר "אף שהוא עצמו לא נותן טעם כבשר, ולא משערין בגיד,” שלכאורה, זה מחודש די לטעון שהוא מהלכהן. ותו"ת.
כבשר- הלכה למשה- קשה, שבגמרא אומר ששיעורים אלו הם מדרבנן, שמדאורייתא בטל ברב.
* צט:
דלא כהאי תנא- לא הבנתי מהיכי תיתי שאינו כמותו, שכמו שמחשבים אותו ליתן טעם כבשר, אף שאינו נותן אותו טעם, כך נשער כן אף שאין לו שום טעם. ותחשב.
* ק:
שכן- יש לדחות את הדיוק (ולכן הוא רק דיוק, ואינו ראיה) שמביא ראיה שנוהג כיון שגבי גויים נוהג באותם בהמות. ויש לדון מה יסברו רבנן שזה ידחה מה שאמרו. אפשר שסברו שאין לנו מקור שנוהג בבהמות טמאות (שכמו שאינו בשיני בהמה, שאינו אותו חפץ שאסר תורה, כך לא יהא כאן, שלא ראינו שחידשו בבהמה טמאה, שרק על מה שצריך אזהרה דן), ועל זה אמר"י שיש לנו מקור מדין בני נח. יש להעיר שבא ממה שקרה עם יעקב- והרי הוא היה בהמה טמאה. ותו"ת.
* קא:
קביעא- יש לדון מהו סברה זה. ותו"ת. אולי ר"ל ששם שבת בא לפני שם יום הכיפורים כיון שבכר מיימות בראשית היה לו שם זה. מוזר, שלא היה שפם להיות לו שם זה. ותחשב.
* קב.
ואמרי לה- זה כמה וכמה שמות ביחד.
* קב:
חישב- צריך לחשוב מה לנו בזה. ותחשב.
* קג:
שמעתי צד מאחרונים (קדמונים, אני חושב) שמה שצריך לאכול כשיעור כדי לחייב (או, אולי לקיים מצות. ויש לדון על איזה נאמר, שכאן נוכיח רק על שיעור לחייב) הוא מפני שאם אינו עושה כן, הוה שינוי. מגמרא זה לא משמע כן, שלהיפך, מוזר יותר אם יאכל שיעור מאם לא יאכל שיעור. ותו"ת.
הקיאו. . . נהנה- הוא לשיטתו, אז, עם מחלקותו עם רשב"ל.
אם אי אפשר לחלקו, צריך ביאור על מה נאמר שיעור של כדי אכילת פרס. ואולי חד במצות וחד באיסורים.	כל- פליגי- לכאורה, רצה לומר לא רק שחולקים בדין, אלא שחולקים בביאור המשנה. ותו"ת.
* קד.
שמע מינא- מעניין שבא להוכיח את שיטתו כיון שלא חלק עליו שום אמורא אכתי (שרב אשי נולד כשמת רבא, ורב יוסף מת קודם רבא, שמלך קודם לו). אולי רק מוכיח נגד אותו צד. עיין בלשון רשי, שאולי (ויש לדחות בקל) לא משמע כן כל כך. ותו"ת.
* קה.
חלא בר חמרא- לכאורה, לא ר"ל שההוא חלא ואביו חמרא, שאז אינו צריך לומר "לנגד אבי,” אלא רק שהוא כחלא בר חמרא. ואולי מבאר המשל. גם יש לומר שמה שבא חלא מחמרא אינו חלק מן המשל. ודחוק.
מצוה- כיון שהוא חיוב מדרבנן, קשה איך נקרא אותו רק מצוה ולא חוב.
* קה:
על סיפא- קשה, אז, למה אמר "צונן" ולא "חמין.” אולי קורא כל מה שאינו יד סולדת בו צונן. ודחוק. אולי על כל פנים קוראו כן לנגד מה שהוא יד סולדת בו. גם אפשר שאין שום דבר קצר לומר לדבר שאינו יד סולדת בו. ותו"ת.
תותי מרזיבא- זה מעשה מעניין. גם, אגב, משמע שיש חיובים לשדים.
* קי:
אחוינא- יש לדון מה ר"ל בזה:
1. אפשר שרצה לומר ששם היו כלם חכמים, ואף עליהם חכם, והיה יכול להראות כן.
2. אפשר לבאר על פי גמרא בכורות (ט.), אלא ששם רק אומר שהוא יותר חצוף, וכאן אנו אומרים שהוא יותר חכם. ותו"ת.
חריף- זה מילה מעניין, שרק הודיע שידע הלכות. ותו"ת.
* קיא:
צנון- יש לדון אם זה חלק ממה שאומר אביי עליו "הלכתא,” או מה שאומר בלי זה או מה שאומר גמרא.
* קטז.
אמינא דרש- עיין בשבת (קל.) שאומר, “אמינא דילמא דורש.”
* קיח:
תחלת- יש לציין לגמרא (לעיל) שדימהו לגמר כלי.
* קכא:
לכלל מתה- זה אומר שיש משהו בין חיות למיתה. עיין לעיל ובמקום אחר שכתבנו כן. וצריך ביאור מה זה ביניהם. (נראה לבאר אולי על פי מה שאומר גמרא ערכין, שמלאך המוות ממית על ידי טפת מר ששורף. אולי אותו חילוק זמן הוא כשיש בו מר, אבל לא שרפו, שאז עומד מאד למות.)
* קכב:
יכול אפילו כולם- לכאורה, ר"ל, “יכול כלם" או "יכול שפילו שאר.” מה שאומר הוא לשון מוזר.
ותנא- לכאורה, לא ר"ל ששונה כן במשנה, שאז אינו צריך להיות תנא, אלא ר"ל שאומר שכן הוא הדין. וצריך ביאור.
* קכו:
שחציו- היה אפשר לומר שלא נולד כן ולא נברא כן, אלא ר"ל שרץ מת שנתעכל מציו. ותו"ת. לא נראה כן, שאם כן, פשוט הוא.
* קל:
חולין- מעניין שיש בעיא בזה כיון שיש בזה צורך להכניסו. עיין ברשי שמשמע שההגדרה הוא שכיון שאין לו צורך להקדש, אינו מותר.
עני היה- אם כן שרק רוצים לחייב ממדת חסידות, אז חולקים על ר"א בשני נקודות, ומוזר מה שרק מזכירים אחד. ותו"ת. ואולי אותו אחד יכול לבאר שני הנקודות. ותו"ת.
* קלג.
בדיק- רבא כהן- הוא לשיטתו, לכאורה, בר"ה (יח.). ותוס’ חולק לשיטתו.
* קלו:
ששייריה ניכרים- עיין במה שכתבנו על זה בשיחתא דש"י (פאה-פ"א ה"א). ותו"ת.
* קלז.
דברי בריבי- נמוקו- משמע שזה אומר שהיה הגדול. יש לדון שגמרא עירובין (יג?) משמע שהיה ר"מ הכי גדול שבדור (ושניהן היו תלמידי ר"ע). גם משמע ממק"א (שוב ראיתי שהוא רשי עירובין יד:) שרק ר"ל שלעולם היה מביא טעם, ולא שהיה כל כך גדול. ויש לדון. ואולי בריבי רק אומר שהיה יכול לעשות דבריו נשמעים.
* קלז:
לשון תורה- צריך ביאור קצת למה יהא כן. ואולי לשון רבנן רק ר"ל לשון בני אדם של אותו זמן.
לשון תורה לחוד- עיין בגמרא קידושין (ע) שמשמע שאינו בעיא להשתמש בלשון תורה (אלא ששם אינו בענין לימוד משניות; אולי הענין הוא שעושהו יותר קל לזכור.)
אבא אריכא- לא משמע, אז, כמה שאומר רשי בכ"מ שאבא הוא לשון כבוד. אפשר שאינו כל כך כבוד. ויש לדון.
דכירנא- יש לדון למה לא אמר אותו לשון שאמר לריש לקיש (נד.).
* קלט.
מעיקרא איחייב- צריך ביאור שלא ניסה ליקח קן, ואז לא חייב עדיין. ותחשב.
בדק הבית- לא הבנתי מה מהני דיון של איך הקדישו. ותחשב.
* קמא.
לרב כהנא- נמצא שהיה ר"כ שהיה אחרון, שדבר עם בן בן רבא, והרי מצינו ר"כ תלמיד רב ורב רב. אולי צ"ל שלש. ותחשב. ואולי הוא רבא אחר.
* קמא:
לומר שאין לוקין- יש להעיר שאמר גמרא לעיל שיש חולקים על משנה זה לומר שלא אמרו רבי יהודה.
* Footnotes
[fn:1] יש להעיר שיש שכתבו שר"י האריך ימים כל ימי אמוראים. אם כן, אינו תימא שראהו רנב"י.
[fn:2] תראה ש1 יותר קרוב להר מקריבות 2  לבקעה.
