- צריך ביאור למה אין כל בהמה שחוטה נעשה טריפה. נראה שיש להעיר שבעיה של בהמה טריפה הוא שמיתתו לא היה לו סיבה טובה. זה אומר  שכשם שאסור לאכול נבילה כיון שלא הומת כראוי, כך אסור לאכול טריפה כיון שלא הומת כראוי, שחלק חשוב מחיותו כבר היה יוצא לפני שחיטה.[fn:1] אם כן, מובן למה כשנעשה טריפה על ידי שחיטה, אינו טריפה.
הקשיא שהיה לנו על זה הוא שאם כן, איך יש לגמרא צד שיש טרפות בדגים. אפשר שאין הכי נמי, בזה תלוי פשט שלנו. יותר נראה לומר שלא הותר כל מיני מיתה גבי דגים, ואף שמיני מיתה שבדרך כלל עושים בהמה נבלה לא עושים דג נבלה, יש דרכים אחרים של מוות שאוסרים אותו, וזה מיתת טרפה.
לא נראה שזה נכון, שיש שני דרכים לקרוא לסיבות מיתה. אפשר לקרוא להם על שם הדברים הפיזיקאליים שאינם טובים (כמו, נחתך סימניו…), או על ידי הסיבה לזה. אם נאמר כצד שני, אז נדון בסיבה שעשה אותו טריפה. כיון שאילו היה נהרג כך מותר, פשוט שאי נטרפה כך, מותר. אז, צריכים לומר כצד ראשון. קשה, שאז נאמר שכשאדם ממית אותו, נעשה טריפה שעה אחת קודם שמת, שמה לנו שזה נעשה על ידי דבר שמתיר אותו להיאכל; הלא כל דבר כן הוא. ותחשב.
* Footnotes
[fn:1] זה מבאר למה מצאנו בכ"מ שטריפה ונבלה נאמרו ביחד.
