* ב:
** כל מה שעשיתם -
משמע שאין שכר לגויים במה שעשו שלא לשמה. (יש להעיר שלימוד של "מתוך שלא לשמה בא לשמה" בא מגויים. הרי, גמ' בהוריות מוכיח שמצוה שלא לשמה הוא טוב ממה שגורם מצוה לשמה. יש לדון אם זה סימן (לא יהיה לו כוח לגרום כן אם אינו טוב) או סיבה (שיש לו שכר במה שעשה דבר שיגרום לו מצווה לשמה)[fn:1]. נראה שאם נאמר שהוא סיבה, נוכל לומר שיש כוח במצוות גוי שלא לשמה כמו שיש כוח במצוות ישראל שלא לשמה. אבל, אותו כוח הוא תמיד רק למצוות ישראל, ולא למצוות גוי. הרי, באותו ציור, גרם מצוות רות וכדו', והיא היתה בת ישראל. אבל, כאן לא נתגיירו, ואז לא גרם מצווה.[fn:2]) כמובן, צריך לציין לגמ' בתחילת ראש השנה ופסחים גבי נותן סלע כדי לרפא את בניו. (עיין שם במפרשים, שקצת משמע נגד גמ' זה שהוא רק רע כיון שתולה אותו בתנאי (ויטען על ה' אם לא נתקיים), אבל לא מפני שלא עושה אותו לשמה.)
גם אפשר שיש ענין במצוות שלא לשמה, אבל הם כוונו לעשות כנגד התורה. לא משמע כן מלשון הגמ'. יותר נראה לדחות- אם נדחה- שה' טען שלא נכון שעשו אותו לשמה, וכיון שכן אין להם שכר מספיק. יש להם שכר, שעשו דבר טוב, אבל דבר כזה לא פוטר אותם מעונש שלהם.
גם נראה לומר שלא טענו שיש להם זכות מחמת זה,  שזה בוודאי לא יספיק להם. נראה שה' בא בטענה שהם, כששעיבדו את בני ישראל והחריבו את בית המקדש, בטלו תלמוד תורה. אז, הם טענו שגם קיימו תלמוד תורה. אולי זה הוכיח שלא כוונו, באמת, לבטל את התורה כשהחריבו את בית המקדש או אולי זה מגלה ששבו בתשובה. אז, ה' טוען שאינו כן, כיון שלא עשו אותו לשמה, ואז אינו מוכיח על כלום. על פי זה, נוכל לבאר מה שיש להקשות על מה שאומר גמ' לבאר למה פרסיים טענו כן אחרי שלא עזר לרומיים, שיש להקשות מה לנו בסתירת בית המקדש, שזה לא היה טענת ה'. אז, יש לבאר שכל הטענה של ה' היה על זה, וחשבו שה' טוען שאחרי שהחריבו את בית המקדש[fn:3], צריך לומר שלא עשו את זה לצורך התורה, ואז פרסיים, אולי, לא ידונו לכף חובה כן. ותחשב על זה.
** יגיד זאת -
ואם תאמר איך יגידו זאת, כיון שאסור לגוי ללמוד תורה. אולי רצה לומר קיום התורה. עדיין יש לדון, שהתיר ה' את שבע המצוות, ואז אין תורה להם להתקיים. אז, נראה שרצה לומר: מי בכם כיוון לגרום "זאת"- כוון לגרום תורה- כמו שהם טענו, שעשו הכל כדי שילמדו.
** חוטא נשכר -
יש לדון למה לא יהיה חוטא נשכר. צד אחד פשוט הוא שאז יעברו יותר. ואם תאמר איף זה נודע כאן, שהרי לא נשאר להם מצוות לעבור עליהם. יש לומר שלא התיר ה' את כולם בבת אחת, אלא אחד אחד עברו והתיר ה' להם[fn:4]. גם יש לומר שחוששים שמחמת זה בני ישראל יעברו. גם יש לומר שכאן אין טעם של "אין חוטא נשכר." יש לדייק מן הלשון, שאומר כאן, "אם כן מצאנו חוטא נשכר." לא אומר ש"אין חוטא נשכר," אלא שאם כן מצינו כן. אז, אולי מקשה שבמק"א אומר שאין חוטא נשכר. הרי, כאן מצאנו שחוטא נשכר. ותחשב. וצריך לעיין, שלפעמים אומר לשון זה ולפעמים אומר לשון זה, וצריך לדון בכל אחד. ותחשב.
** ויעידו -
אין גוי כשר לעדות. אולי הוא כעין הודאת בעל דין. יש לדון בזה. גם לא כל כך פשוט שיש הודאת בעל דין לגויים.
* ג:
** תקופת תמוז -
צריך לע' בפרק קמא של סנהדרין (בסוגיות של עיבור השנה), שדן מתי יכול להיות התקופה.
** שתים עשרה -
לא צריך לחדש זה. אולי הו"א שיום של ה' שונה. יש לדון, שאין זה יום של ה' (שהרי יום של ה' הוא אלף שנים, כמו שאומר הפסוק, ולא מדבר על זה, שהרי מזכיר דברים שקרים בכל יום ויום), אלא יום שלנו. הרי, ידוע אורך של יוום שלנו.
** כיון שרואה -
לשונו משמע שבכל יום ויום, תמיד ה' רואה שנתחייב העולם כלייה, על פי מידת דין. יש לדון, שאולי רצה לומר שאם רואה ה' כן, יושב על כסא רחמים.
** ומן המצוות -
דנים אם לגרוס אותו או לא. אם לא גורסים אותו, אז הוא מיוסד הוא על מה שאמרו אין מים אלא תורה. אם גורסים אותו, צריך לומר או שכשאומרים ש"מים" מכוון לתורה, לא רק מכוונים לומר שלתורה מכוון, אלא שלקיום תורה גם מכוון. (צריך לע' במקום שאומרים חז"ל כן.) גם אפשר שאין המשל כל כך מדוקדק, אלא הדמיון הוא רק במה ששניהם סומכים על דבר לחיותם. (ואם תאמר אם כן נאמר שאדם, כשמוציאים אותו מאקסיגי"ן מיד מת. ויש לומר שלא היה אומר כן, כיון שזה פשוט. גם יש לומר שצריך להיות דבר שמאד קל להוציא אותו משם, ולא קל להוציא אדם מן האוקסיגי"ן. ותחשב.)
** אין גהנם אלא -
הוא כאותו לשון שבו משתמשים הרבה פעמים כשאומרים "כל האומר... אינו אלא טועה," ורצה לומר שגהנים הוא שמוציא חמה מנרתיקה. ותחשב.
** עולם הבא -
מעניין, שדגים מתים כשחמה בא עליהם. לא כל בן אדם מת כשחמה בא עליו, שצדיקים מתרפאים בו. אולי רצה לומר שדומים לדגים שכל מי שנשרף על ידי חמה מת. אבל, זה קצת פשוט. (אולי בעיקר בא לחדש שיש שריפה על ידי חמה בבני אדם, וזה קורה לעולם הבא.) ותחשב על זה.
** הכל בידי שמים -
עיין בדברי רש"י, שמשמע שרצה לומר שכל דברים רעים שקורים לאדם באים בגזירת ה' חוץ מזה. יש לדון למה לא מפרש שכל דבר שקורה לאדם הוא בגזירת ה'. ותחשב. (אולי רש"י רצה לומר שאף דברים רעים שבאים לאדם הם כן. צריך ביאור מהו הרבותא בזה. ותחשב.)
* ד.
** מצרפן לחשבון גדול -
צריך לחשוב מהו החידוש. לכאו', פשוט שכל מצווה מצטרף. אולי רצה לומר שאין ה' נותן שכר קצת קצת, אלא כולו ביחד. ותחשב.
* ה.
** עמה -
אז, לכאו', דורש ש"עמה" קאי על העבירה, ולא על אשת פוטיפר. אז, נמצא שהפסוק משנה באמצע, שאומר, "לשכב אצלה"- אצל אשת פוטיפר- "להיות עמה"- עם העבירה. אפשר לבאר ש"עמה" הוא עם האשה, ומה שהוא עמה מרמז שהיה עם העבירה גם כן. צריך לבאר את זה.
** לשמחת עונה -
נמצא שהיה מותר להיות בועל אף שאין שום צד שיוליד, אף שאסור לסריס לבעול. זה לא קשה, שהרי אין איסור לסריס מלידה או לאיסטניס לבעול.
** אלמלא -
אז, נמצא שסובר (בצד זה) שנשמות שלנו לא היו בסיני, שבאותו זמן לא היו ראויים להיות ולדים. יש לדון, שאולי היו שם לסיבה אחרת. (אף שלא יולדו, אולי רצה ה' שיהיו שם.)
** לשמחת -
איני מבין כל כך מהו הראיה. אולי סובר שאין צד שיש היתר בלי יכולת לבנים. קשה, כמו שבארנו לעיל. גם אפשר שסובר שזה חיוב (עי' בגמ' בביצה, שמבאר שצריך זה גם לעשות היתר), וסובר שלא יהיה חיוב אם אין בנים. אז, דוחה שיש חיוב כדי לגרום שמחה. ותחשב.
* ה:
** להקרבה -
רצה לומר, מחפש בהמה שאין בו פסול. כיון שלא קל למצוא אותו, מתחיל שלשה ימים קודם. לפעמים, מצליח מהר, ומוצא בהמה ראויה ביום ראשון של חיפוש שלו. אז, נמצא שיקנה בהמה כמה ימים קודם יום האיד.
** שואלים -
משמע שזה תלוי בזמן שבו צריכים לחפש לפסח. (כן נראה ממה שמביאים ראיה מפסח שני. הרי, אין הרבה דינים שנוהגים בפסח שני חוץ מזה. ויש לדון, שיש דינים שנוהגים (כמו איך לאכול ואיך למנות).) יש להעיר שלא בדקו לפסח מצרים שלשים יום קודם (כמו שאומר גמ' בפסחים). אולי שם ה' הצליח בעדם למצוא קרוב לזמן הפסח. גם יש לומר ששם היו הרבה טלאים (שהיו המצרים עובדים אותם), ולא היה קשה למצוא אותם.
** מנין למחוסר -
זה מביא מקור לפסול. לכאו', זה חוזר למה שבאר שצריכים שלוש ימים. לא מבאר מה שאמר שלא צריכים שלשים יום, כיון שאז היה לו להביא מקור שאין פסול בעלי מום. (הדרך לדחות הוא שאומר שאין לפסול בעלי מום, שהרי המקור לפסול מחוסר אבר אינו מלימוד מקרבן ישראל, שאז נאמר שכל דיני בהמת ישראל נוהגים בו, אלא הוא מקור אחר, כמו שמבאר ר"א.)
* ו.
** חדא יומא -
איני מבין את זה כל כך. לכאו', קושיית גמ' הוא שכיון שכולל אותו בשלש הימים, היה לו לכלול שלש הימים כשמבאר אורך שלו. (איני יודע ההכרח לזה בכלל.) אז, צריך ביאור מהו תי' של גמ'. אומר שכולם נחשבים כיום אחד, אבל איני רואה איך זה מתרץ את הקושיה. ותחשב.
** תמים -
ענו ושפל רוח- צריך ביאור מהו החילוק בין אלו.
** צדיק -
עיין במה שפרש"י. לא נראה שמכוון לומר שזהו ביאור מילת "צדיק" בדרך כלל, אלא שכאן המבול בא על חמס, ואז ביאור "צדיק" הוא מי שאין בו חמס. במילים אחרים, "צדיק" רצה לומר "איניסנ"ט," כמו "והצדיקו את הצדיק," ואז תלוי איפה כתוב לדעת ממה הוא איניסנ"ט.
* ו:
** לא יושיט -
עיין ברש"י, שמשמע שזה אסור אף אם הנזיר לא בוודאי ישתה. יש לדון למה לא אומרים שספק דאו' הוא. אולי רש"י סובר שזה בכלל אותו הלאו, או רק מבאר מה הוא אסור, אף אם אינו בכלל הלאו. ותחשב. יותר מזה, יש לומר שהוא אסור בוודאי לעשות מה שאולי יגרום אותו, ואף אם לא גורם. אולי זה גזירה (יש לדון למה זה שאני מספק איסור, שכל גזי' יהיה בו ספק. צריך לומר שהוא יותר מצוי שיקרה. ותחשב.), או אולי יש דבר רע בעצם בזה (אולי הוא מה שאינו טוב לאדם לתת לו עצה רעה כזה). ותחשב.
** בדבר שאינו מתקיים -
צריך ביאור למה מה שפרע לו כבר נחשב, לפי רבא, דבר המתקיים. ותחשב על זה.
* ז.
** מחלקת ואח"כ סתם -
צריך ביאור למה פשוט לגמ' שזה נכון. הרי, דין שהלכה כסתם משנה הוא מחלקת; אז, קשה למה לא נאמר שמחדש זה. משמע שאף החולק על זה סובר שנוטים כסתם משנה (אולי כוחו כרבים), ואז אף לו אין בו חידוש.
** גבי הלכתא פסיקתא -
יש לדון מה בא זה לתרץ:
1. אולי בא לומר שפשוט לפסוק כמותו כיון שהוא סתם משנה, אלא כיון שהוא נאמר במקום הכללים.
2. אולי בא לומר שפשוט לפזוק כמותו כיון שהוא מחלקת ואחר כך סתם, ויודעים זה כיון שנאמר במקום הכללים. ותחשב על זה.
בביאור מה לנו במקום הכללים (רק ביאור מה הוא, ולא ביאור כל הענין), יש לדון אם הוא שנאמר במקום דבר שנאמר לכלל או הוא מה שנאמר אגב, ונאמר בלי צורך.
** בחכמה ובמנין -
איני רואה איך רב אחד יותר גדול מרב אחר במנין. לכאו', לא מדבר בשני רבנים אלא בשני מקורות (שני בתי דינים). גם אפשר שנמצא ברב אחד שמביא דבר משני רבותיו.
** אחר המחמיר -
לכאו', נמצא שסובר שבספק בדין, מחמירים אף בדרבנן. יש נפקא מינא גדול בזה. (צריך לחשוב אם נוכל לחלק בין ספק בדין למחלקת כשלא יודעים איך לפסוק.[fn:5])
** נותן לו -
עיין במה שכ' רש"י לבאר את זה (וע' בגמ' ב"ק שכ' כן בפירוש). נמצא, לכאו', שאדם יכול להיות גנב ומשנה בבת אחת. יש לדון, שאולי כשנוטל אותו על מנת לתת בו אותו דיו, כבר גנב אותו. ויש לדון, שלא מוכרח שיטלטל אותו, שאולי ישים אותו במקום אחד, ושוב יתן עליו דיו, ולא מטלטל אותו ממקום שקבע בדעתו לשנות אותו. (אולי עדיין צריך להיות שהוא, בענין אחד, ברשות שלו.) ותחשב על זה.
** מחלקת
- קמו רבנן- משמע שסתם משנה תלוי במה ש"קמו רבנן." עיין ברשי בתחילת ביצה שאומר בפי' כנגד זה. ותחשב.
** אין סדר
- עיין במה שפרש"י. משמע שהבעיה הוא רק שלא יודעים מה קדם. לכאו', מחמת זה יהיה בעיה אחרת, והוא שכיון שרבי ידע שלא נדע, לא יקבע את הסתם אחר המחלקת, ולא יקבע סתם בכלל אם גם קבע מחלקת, כיון שאין שינוי בזה. (לא כל כך קשה לומר שרבי מכוון לומר כן, אלא שאומר את הדבר הראשון שצריכים לדעת כדי לומר כן.) נראה שאולי רבי לא קבע דברים אלו (סתם, ומה קודם למה) כדי להודיע לנו דברים, אלא קבע אותם מפני שכן סבר. כשסבר שדבר נכון, אמר אותו סתם, כדי שעכשיו ילמדו ממנו. לא אמר אותו בסדר ראשון או אחרון, אלא אומר אותו אימתי שסובר כן. ותחשב.
* ז:
** איהו מדקא מפליג -
עיין בגמ' חולין (פרק שני) ששם אומר שאם שני תנאים אומרים דבר אחד, אף אם אינו מטעם אחד, עד כיד שיש נפקא מינא בדין, מצרפים אותם להיות רבים. נראה שרק מצרפים אותם להיות יותר טובים מאחד. אבל, עדיין גרועים הם מן השנים. כיון שהיו שנים כנגדו (אולי), לא מהני סיוע זה.
** ויצא יצחק -
עיין בברכות (כו:), שגמ' מהפך את זה. אולי יכול להיות משמע רק דבר אחד כיון שהוא נאמר בשני המקומות. איללו רק נאמר באחד מהם, אולי היה אפשר לומר פי' אחר. אבל, כיון שנאמר בשניהם, לא אפשר לומר פי' אחר. ותחשב.
** מוכרים -
מילתא דלא שכיחא- עיין ברשי בגיטין (טז:) בזה.
* ח.
** חכמים אומרים -
לכאו', רבנן דרושים שנני המקראות. אז, צריך לומר תפלה קודם ואחר בקשת צרכיו.
** רב גובריה -
נראה שהוא כמש"א גמ' במגילה (יח), ש"מי ימלל... מי שראוי...." קצת מעניין, שהכל צריכים לשבח. צריך לומר שעדיין תשבחה שלו יותר טוב.
** אם בא לומר -
לשון זה (וכן לשון, "אף על פי שאמרו") קצת משמע שלא לכתחילה הוא לומר בקשת ברכה בסוף הברכה. ותחשב.
** מנהגו -
צריך ביאור למה הסיק שמנהגו של עולם הוא, ולא הסיק שהועיל תפלה שלו. (אם הייתי בעל מוסר, הייתי אומר שזהו דרך רשע, שכשרשע צריך לה' הוא מתפלל לו ומחנן אליו. אבל, כשלא צריך לה', לא רק שלא זוכר אותו, אלא אומר שמעולם לא היה צריך לו, ומבאר איך קרה לו תשועה גדולה בדרך אחר.)
** משעבדיו -
יש לדון אם החידוש הוא שלא מניחים שעובדים או שאף שרואים שעובדים, לא מניחים שבאמת מכוונים לעבור, אלא כך צריכים לעשות לכסף שלהם.[fn:6]
** משעת קריאה -
כמובן, אינו משעת קריאה, אלא משעה שעונים "הן," או משעה שבאים או משעה שאוכלים את שלהם.
* ח:
** אמור לנו -
עיין ברשב"ם בפסחים על זה. יש להעיר שלא פשוט שיש שנים ושלשה דברים כאן (שאולי כולו נחשב דבר אחד). אז, קשה, ששאל לו לדברים, והשיב לו דבר. אולי לא היה לו דבר אחר לומר. דחוק. יותר משמע כצד אחד של הרשב"ם שם, והוא שאמר דברים אחרים, וגמ' רק מביא מקצת ממה שאמר במקום אחד. ותחשב.
** רבי יהודה בן בבא -
אגב, עי' במדרש על עשרה הרוגי מלכות (הובא באוצר מדרשים), שלכאו' משמע נגד זה.
** שני ערים -
לכאו', הענין הוא שנתן את מקום הסמיכה בין שני המקומות, כדי שלא ידעו איזה להחריב. ואם תאמר יחריבו שניהם. לכן שמו אותו בין שני עיירות גדולות, שלא ירצו (מחמת הטורח ומחמת שירגזו הרבה בני אדם) לחרוב שניהם מספק.
** רוצחים -
יש לדון למה רק נקט רוצחים, שגם הרבו מזנים, כמו שאומר גמ' בסוטה. נראה שזה היה רק קצת לפני החורבן, אבל אחרי ארבעים שנה. אולי גופא נתרבה כיון שלא היה עוד בית המקדש.
** לא לחייבו -
עיין במה שאומר רש"י. קצת קשה, שתוס' כ' (וכן נ' מהרבה גמרות) שנחש מכיש אותו או כדומה. אז, צריך לומר שהוא חייב מיתה, אלא בית דין לא יכולים להמית אותו. אז, הייתי מפרש שהוא כדי שלא יחייבו בית דין להמית אותו או לא יחייבו עונש אם לא ממיתים את כולם. ותחשב על זה.
** ממקום למקום -
רצה לומר, אף שלא נגלה למקום אחד, אלא למקום שבו יושב נשיא, ואז בכל נשיא, נצטרך ללכת למקום אחר, עדיין ראוי לנו לגלות.
** בחנות -
איני יודע למה ישבו בחנות, ולא בבית מדרש.
** דיני -
בשם רבי- עיין ברשי בתענית שאומר שגם מי שנקרא רב נקרא כן מפני שסמכו לו. עדיין, אומר רש"י שכדי לסמוך, קראו לו "רבי," ולא "רב" (אם לא נאמר שזה לאו דווקא, ויכול להיות או זה או זה). צריך לחלק בין מה שקראו לו בני אדם למה שקרא לו כדי לסמוך אותו.[fn:7]
* י:
** חסא -
קשה, שהיה בן שהמליך. אולי מת או אולי היה סריס או אולי לא היה נולד כבר. (גם אפשר שממנו זנה, ובן שהמליך בא מזה. לא כל כך מסתבר שיהרוג אותה על שזנתה עמו. אולי היה ידוע שזינתה, אבל לא עם מי (שרק ראו אותה מעוברת.[fn:8])
** רמז -
צריך ביאור למה לא דברו על זה כשהיו ביחד. צריך לומר שאף שם חששו. גם אפשר שלא היה להם הרבה זמן, ולא רצו לבטל מזמן תורה שלהם.
** ערלתיה -
לכאו', זה לא גייר אותו, אלא רק עשה שלא היה ערל (אף שבאמת כל גוי נקרא ערל). אולי סובר כמד"א שמילה בלא טבילה מהני. גם יש לומר שגם טבל, ורק לא אמר כן. דחוק.
** לר"ע -
צריך באיור איך קנו. אולי עשו מעשה קנין קודם שמת. גם אפשר שהוא כעין הודאה, וזה מועיל, אולי, אף בבני נוח (אם לא נתגייר). גם יש לומר שהיה כדין שכ"מ. (אם היה כבן נוח, צריך לדון אם דין זה ינהג אצלו).
** בכמה שנים -
קשה למה לא הזכיר שיש הרבה שלא קונים את העולם שלהם כלל. נראה שלא טוב להזכיר חוטאים, שאנו מקווים שאין שום בני אדם כזה, ולא רוצים להזכיר את הרשעים שהם כזה. ותחשב.
* יא:
** בראשו -
איני יודע בראש מי נותנים את זה. אולי נותנים אותו בראש החגר, כיון שהוא כנגד יעקב, ורבי ישמעאל היה יהודי, ואולי נותנים אותו בראש השלם, כיון שהוא כנגד עשו שהוא חזק, והרי רבי ישמעאל היה יפה מאד.
** לילך לשם -
איני מבין את זה כל כך. לכאו', תמיד יש מקום בדרך שבו אי אפשר ללכת אלא לאותו מקום. צריך לומר שלפעמים דרך ממקום א למקום ג הולך ממש בתוך מקום ב. דחוק. גם יש לומר שכיון שנכנס לעיר, יכולים להבחין אם הולך לבית עבודה זרה או לא, שאם הוא לא הולך לאותו צד של העיר, מבנים שלא הולך ל עבודה זרה. ותחשב. המציאות צריך מחשבה.
** דפיזא -
עיין במה שכ' רש"י. מן השם, היה נראה לומר שהוא מה שקוראים באנגלית "טופא"ז." בביאור טופא"ז, וכמה מצוי הוא, עיין למטה[fn:9].
* יב:
** פרצופות -
איני יודע למה זה פשוט לגמ'; הרי, כאן אינו מראה שמשתחווה לו, אלא מראה שמנשק לו. אין נישוק תמיד נחשב עבודה. אולי צריך לומר שמדברים כשנחשב עבודה, שאי לאו הכי, לא ייאסר. אז, כיון שעבודה הוא, פשוט הוא. יש לדון בזה, שהיה נראה שאף אם אינו עבודה, מראה שמקבל אותו עליו לאלוה. ותחשב.
* יג.
** מה יעשה -
לכאו', יותר רע להיות מהנה, כמו שאמר לעיל (שאמר "כל שכן"). אבל, יותר טוב שלא ללכת בכלל, ולכן אוסר ללכת. ותחשב.
* יד:
** אמר רב -
חשודים- צריך ביאור מהיכי תיתי שבזה תלוי. אולי באמת אין שום גוי חשוד על זה עד כדי שיהיה איסור ממש, אבל יש מקומות שהחמירו מחמת חשש קטן שיש בו.
* טו.
** סמוך לשקיעת החמה -
מעניין שחוששים לזה, שהרי אסור למכור בשבת. אז, צריך לומר שחוששים שהוא מוכר סמוך לשקיעת החמה, ואף עושה נסיון (שהוא קודם מכירה) אחרי שקיעת החמה. ותחשב.
** איני יודע
למה יהיה לפני עוור גבי בהמה, שלכאו' יכול גוי למצוא בהמה. אולי לא אפשר למצוא אותו ברגע זה. גם יש לומר שביאה עם בהמה שונה הוא איסור שונה קצת, ונמצא שאין איסור זה אפשר אלא בסייעתו.
** אימור -
עיין ברש"י. מעניין שאומרים שבהמה טמאה לא עומד לשחיטה, לגוי. הרי, גויים אוכלים הרבה חזיר.
** שכירות -
רק מוכיח כן על שכירות, אבל חוזר ומניח אותו על שאלה. אפשר לחלק לומר שבשאלה, שכל הנאה שלו בלי שום תשלומים, יותר קונה אותו. ויש לדון, שאולי מסתבר לגמ' שגם גבי שכירות יש לו אותו קנין, אלא ששילם בעדו. ותחשב.
* טו:
** אין אדם מצווה -
איני מבין כל כך מהו החילוק, שאף כאן יש איסור, ובשניהם הדיון הוא רק אם עובר על אותו האיסור. ותחשב על זה.
היה יותר נראה לחלק (ואולי יש לפרש שכן מכוון גמ' לומר) שכל לפני עוור הוא איסור התלוי בספק (שאולי יחזק את עצמו ולא יעבור), ואז נמצא שיש כאן ספק ספיקא, שאולי יחזק את עצמו, ואולי לא קנה אותו לזה כלל. אבל, לא נראה שגמ' אומר כן. ותחשב למה אינו נכון.)
** נקבות אצל -
איני יודע את המציאות כל כך, אבל איני רואה איזה איסור יכולה אשה לעשות עם הנקבה (שאף הסילול שתוכל לעשות אינו, לכאו', נאסר). אולי העמדת הבהמה גזי' אגב שאר הציורים, או שאולי תעשה דבר שהוא אסור מחמת גזירה מחמת זכר על נקבה.
** דזימנים -
יש לדון אם רוצים שהוא ייהרג ולא יהרוג (ותחשב למה רוצים זה) או שחושבים שאם אין לו כלי זיין, לא ייהרג, שלא יבוא להרוג.
* טז.
** ה"נ -
השקלא וטריא לא פשוט, שלכאו' דחה את האיסור, וממשיך ל"איכא דאמרי." נראה שצריך לומר ש"הכי נמי" הוא ביאור של החולק. אז, היה לו לומר לפניו, "ואידך."
* טז:
** סתם ארי -
כמובן, זה מזכיר לנו מח' כעין זה גבי שביל של רבים בב"ב.
** וחיה גסה -
אם לא נאמר כרב אשי (ונאמר שאין סתם ארי שבור) צריך להיות גם מלאכה שעושים באריים. (נראה שהדיון הוא אם צריך להיות דבר שרגיל לעשות או דבר שאפשר לעשות.)
** הואיל -
היה נראה לבאר על פי מה שכתבנו בנכפל במאה שאולי אין זה סתם שוחד, אלא שכיון שהכיר שר"א סבר שהוא נאמן, הוא חשב על עצמו להיות כן, וממילא עשה את עצמו כן, ודקדק שלא לפסוק בטעות. הכיר בטעות שלו, ולכן לא הרג אותו.
* יז.
** רבי -
יש לדון אם ייחשב נסמך מחמת זה. אם נאמר שנחשב נסמך, נמצא, לכאו', שיש דרכים שונים לסמוך חוץ משסמוך אחר יקרא לו "רבי," שמספיק גם אם ה' קורא לו כן. ותחשב.
** ואיכא -
יש לדון אם רש"י בא לסכם את הגמ' או להביא גי' אחרת. לצד שני, נמצא שאף אחד מגי' של רש"י אינו כגמ' שלנו, שגמ' שלנו מביא שני הגי' בשני לשונות. זה התחדש לי מושג שאולי כל "לשון אחר" או אולי כל "איכא דאמרי" שבש"ס אינו, באמת, בגמ', אלא הם לשונות חולקים של סבוראים גאונים או אולי, לפעמים, אף ראשונים שראו המדפיסים. ותחשב. אין שום הכרח לזה.
* יז:
** מדהא -
קשה למה לא אמר כן על כל הטענות שלהם. ותחשב. אולי רק שנים אלו בא מאותו אדם אחד.
** עבדך -
צריך ביאור, שאין זה דין יהדות,אלא להיפך אסור הוא (באמת, מח' ר"ע ור"י הוא, שר"ע אוסר ור"י מתיר). ותחשב על זה.
* יח.
** להתלמד -
עיין במה שכ' רש"י. קשה למה לא אמר כרש"י כמה שאומר גמ', "אלא מאי טעמא אענש משום הוגה את השם בפרהסיא." צריך לומר שלא גרס אותו בתוך הגמ'.
** מעות של פורים -
עיין ברש"י. נראה שבכוונה כ' לשון שאינו כל כך מבורר כיון שאפשר להיות כשני צדדים שלעיל. ותחשב.
** דשתנא -
עיין במה שפרש"י. כך אמר גמ' בכתובות. היה נראה לומר שגמ' שאל על זה בדווקא כיון שידע שצריך להיות קיצור לדבר כיון שהוא בלשון פרסי (לבני בבל), והיה גם בלשון רבי מאיר. ותחשב. נראה שרש"י, אז, מפרש אותו כאן, כיון שחוץ מזה רק רואים אותו בגמ', ובא לבאר איך יהיה גם בלשון של רבי מאיר. ויש לדון.
* יח:
** זונה -
עיין ברשי שפי' שהיה נראה כאשה. צריך לומר שאין בזה בעיה של "לא תלבש" כיון שהיה מלאך. ותחשב. גם אפשר שהיה פקוח נפש. לולי רש"י, היה אפשר לומר שנראה כזונה איש, והיה מראה שהיה אותו אדם שכרך בעל תאוות. ע' בלשון גמ' ("כרכתיה"), שלא משמע כן, שנראה שהוא לשון נקבה.
** אלך -
היה אפשר לפרש, אבל לא משמע כן מן הלשון, שטוען שאולי זה הדרך הכי טוב לשמור שלא ילך למקומות האסורים, שכיון שהוא ישן, לא יעשה כלום.
* יט.
** דור הפלגה -
יש להעיר שלא היה אברהם ראוי להיות נקרא אברהם כיון שנולד, שלא היו הרבה אומות, אלא רק אחד (שהיה קודם ההפלגה). ותחשב. יש לדון, שרק יודעים שכולם גרו ביחד ודברו לשון אחד. אבל, אולי לא היו נחשבים אומה אחת. צריך לדון מה עושה בנ"א לאומה אחת.
** בתחילה -
כמובן, יש לציין לדברי הגמ' (נראה שגם שם הוא רבא) בקידושין על מחילת ת"ח על כבוד שלו. (שו"ר שמסורת הש"ס מביא אותו.)
** חבילות -
בפשטות, רצה לומר שמבקש הרבה קודם שחוזר עליו. אבל, היה אפשר לומר שלא מדבר גמ' על זה (רק לקמן ידבר על זה), אלא מדבר על מי שקובע לעשות סכום בזמן (כמו שאומר גמ' בסנהדרין לפי צד אחד).
** רבא -
אם גורסים "רבא," נמצא שהיה רבא בזמן ר"ח. צריך לע' בגמ' בסוף מ"ק, שחושב אני שחי ר"ח זמן רב. אז, אולי אין זה כל כך קשה.
* יט:
** מכוש -
גם היה אפשר לומר שרצה לומר ששכרו חוץ מאותו מכוש מותר.
* כ.
** לא תתן להם חן -
רצה לומר, לא תאמר דבר טוב עליהם. אולי נתינת חן רצה לומר אטריביו"ט חן להם. גם אפשר לומר שאם יגיד כן לאחרים, יהיה חן להם בעיני אחרים. יותר מזה, אם יגיד כן לו, ישמע, ויחשוב כן על עצמו, וממילא כן יהיה, כמו שיודעים מן הספר נכפל במאה. (ודע שצריך לדון בפני מי אסור לומר כן. ותחשב.)
** נאה -
ואם תאמר איך ידע. וי"ל שהסתכלות יותר גדול מראייה. אבל, אז, קשה, שאולי רק ראו. יותר נראה שתלוי במה שישמע מאחרים. ותחשב.
* כ:
** כמלאך המוות -
זה דבר מעניין ומוזר.
** צבע -
ממה שלא אומרים שצ' כדי למעט בגדי איש, משמע שלא היו נוהגים אנשים ללבוש בגדי צבע גם בימיהם. יש לדון, שאולי פשוט שלא מדברים על בגד אשה. ויש לדון, שהו"א שאסור לנשים לראות או הו"א שאסור גם לאנשים שיבוא להם תאוות זכר. דחוק.
** תח"מ -
קשה, שגמ' אמר לעיל שאפילו הקטנים שבכם יכולים להחיות מתים. צריך לומר שה"כם" כולל רק חשובים כזה. יותר מזה, נראה שאולי הקיסר טעה.
* כא.
** חובת הדר -
תחשב מה לנו בזה, שבין כך ובין כך יש מצווה שלא נעשה. ותחשב על זה.
** תרתי -
יש לדון למה גוזרים כאן אף שלא מוסיפים גזירה מחמת חיוב כרת, כמו שאומר גמ' ביבמות. יש לדון, שזה הוא מחלקת שם, לכאו' (שיש הרבה גמ' שאומרים נגד זה).
* כב:
** לוקחים -
ואם תאמר למה לא הקשה מן המשנה לעיל. וי"ל ששם קל לתרץ כמו שאמר רש"י ש"נהגו" רצה לומר "מקום שחוששים משום ביאה על הבהמה, שחשודים על כך." (אגב, קצת צריך ביאור איך נדע שחשודים על זה. כנראה, היו מקומות שלא רק עשו את זה, אלא היה ידוע שעשו את זה.) גמ' לא רצה לת' את זה כאן, כיון שאוסר סתם ומתיר סתם. ויש לדון, שלעיל תי' כן. ותחשב.
** בבשר -
ואם תאמר למה חוששים לזה; ימכרו לבני ישראל (שלא מכירים בהם). ויש לומר שחוששים שלא לא ירצו (או לא יכלו) למכור. גם יש לומר שחוששים שישראל יכירו בהכחשת בשר. ק"ק, אז, למה לא אומרים כן ברועה. נראה שיכירו בזה ברועה, אבל לא יכירו למה, ולכן לא ידעו שרועה גרם את זה. גם יש לומר שלא מכיר אותו כיון שרועה מחזיר אותו בכל יום. אין כל כך שיוני ביום אחד, ואז בין הכל לא מכיר את שינוי הגדול. אבל, הלוקח רק רואה אותו פעם אחת. אם בעל אותו הרבה פעמים (או אולי אף אם בעל אותו פעם אחת, ושהה), יכחיש הרבה, ויבחין הלוקח בכחישות. ויש לדון למה לא חוששים שבעל אותו פעם אחת ומכר אותו מיד אחריו.
** דידעי -
ואם תאמר הרי אנו יודעים, שהרי תיקנו דינים אלו. ויש לומר שגויים לא יודעים שאנו יודעים. גם יש לומר שאנו לא יודעים בוודאי על שום אחד, אבל הם יודעים על אחד ואחד, מי חשוד ומי לא חשוד. (צריך לומר, לפי זה, שמה שחוששים לכך אינו שלא יקנו מהם מחמת זה, שדינים שלנו כבר שלא לקנות מהם. ותחשב.)
** אלמנא -
יש לדון אם זה מפני החשש או מפני מראית עין. (עיין ברשי, שמשמע כראשון.) לא צריכיםן להיות שניהם שווים. יש להעיר שאם הוא רק מראית עין, כלב יהיה מותר אם לא שדי לה אומצא, שאז רואים שאל הולך אחריה, ובוודאי לא נבעלת לו. ויש לדון, שאולי לא תמיד הוא מסרח אחריה. גם יש לומר שיש מראית עין כיון שחוששים שהיא מכוונת להיבעל לו לאחר זמן.
** בר בי רב -
יש לדון למה נקט בר בי רב:
1. אולי אורחא דמילתא נקט, שסתם בני אדם גרים בבית שלהם. רק בר בי רב, שצריך לגור במקום אחר כדי ללמוד בישיבה שם, אף שהוא קרוב מן המשפחה ומן הבית שלו, יגור בבית אלמנה.
2. אולי בא לומר שאף בבר בי רב, שמסתמא יוכל לעמוד נגד יצרו (ובוודאי היא תחשוב כן, ולא תתחל בו), יש לחוש.
3. אולי רק בבר בי רב יש איסור, שרק בו היא נסמכת לומר שלא יגיד שהוא בועל אותה (שרק הוא צנוע).
כמו כן, יש לומר שרק בו לא יחושו בני אדם (היא חושבת) שבא עליה. (יש לדון אם זה האמת, ואז צירך לומר שאין הבעיה מראית עין, או לא. אף אם לא, יש לדון אם נוכל לומר שהיא לא תיבעל לו, כיון שחושבת שהכל יחשבו כן, ולכן רוצה להיות יכולה לומר באמת שלא נבעלה.)
** נשי חבריהן -
קשה למה נקט נשי חבריהן, ולא נשים שלהם. אולי אשה שלו תביא לשם בהמה, והיא לא תימצא שם, ויבעל את הבהמה. יש לומר שיחוש שאשתו תחזור ולא תרצה לראות שהוא מזנה עליה עם בהמה.
* כג.
** דשאני -
לכאו', נמצא שיש חילוק בין חשש שצריכים ללאו של לפני עוור לחשש שצריכים לפסול נרבע. (יש לדון אם הוא שהחשש שצריכים שונה או הוא שהחסרון שיש שונה, וממילא כאן החשש שצריכים שונה.) קצת צריך ביאור איך מביא ראיה מדין אשה, שלכאו' דין דיעבד הוא שונה מאד (יש בו איסור שונה, ויש בו חסרון שונה).
** תדע -
זה לא מוכיח שתמיד אין חילוק בין בד\יעבד ללכתחילה בכעין זה, אבל מוכיח שאין להביא מדין זה ראיה, שבאותו הדין אין חילוק.
* כד:
** יתרו -
יש לדון למה לא אומרים שעל ידי תגר ישראל היה, שמכר אותו לישראל, וישראל מכר אותו לקרבן.
** מישראל -
לעיל, מצאנו שיכול ישראל לקנות ממנו, ועכשיו מוצאים שיכול לקנות מישראל. אז, נמצא שרק צריכים שיד ישראל יהיה בו בשעה אחת (קודם הקדש).
** יתרו -
ואם תאמר אולי לקח אותם אחרי שנתגייר. ויש לומר שמשמע שלקח אותם עמו כשבא למשה. קשה, אז, איך אמר שקנה אותו מישראל. צריך לומר שראו אותו אחרי יציאת מצרים, או שלפני יצ"מ, היה ישראל יכול למכור ליתרו. היה נראה לומר שמשה קבל ממנו, כשגר עמו, ומכר לו (או נתן לו) כשיצא ממנו לחזור למצרים.
** גר תושב -
נמצא שמחדש שגם גר תושב מהני. יש לודן למה לא תי' כן ביואב. אולי לא היה גר תושב כבר (שצ' יותר משמאמין בה', אלא צריך קבלה בפני בית דין, אולי).
** שירה -
אולי לא ממש אמרו שירה, אלא הוא כעין מה שאמרו חז"ל בפרק שירה.
** ישרו ואמרו -
ק"ק  מהיכי תיתי לדרוש שניהם (ישר ושירה). אולי מסתבר לו לדרוש ישר, ואין ענין במה שהוא ישר אם לא גם אמרו שירה לו.
* כה.
** ספר הישר -
מסתמא לשון זה הוא המקור למה שנקרא לנוצרים בשם "The Good Book."
** מלא גויים -
צריך ביאור למה נקרא כן. נראה שהוא אות שבהכרח היה נראה לכל האומות.
** אבני ברד -
היה מין אחר למשה, אבל לא היה מין זה. גם יש לומר שלא היה באותו זמן למשה.
** גבי ישראל -
ק"ק למה מניח שיותר פשוט שנאסר לגוי, שהו"א שרק חוששים גבי ישראל שמא תתרצה להבעל להם. אבל, אולי לא חוששים שתתרצה להיבעל לגוי.
* כה:
** אשה כלי זיינה -
יש להעיר שאם כן, אף שאין איסור לולי מה שמזכיר המשנה, היה איסור ידוע לנו אף בלי מה שמזכיר לנו משנה. אם לא היינו יודעים את דין המשנה, אלא היינו חושבים שאשה לא תיבעל, יהיה איסור לאשה להתייחד משום נפשות. יש לדון, שאולי הו"א שלא יאנס את האשה, והיא לא תתרצה לו, אבל הגוי חושש שאולי תתרצה לו, ולכן לא הורג אותה.
* כו.
** מפני שמילדת -
יש לדון מה לנו בזה. משמע שיש איסור בהגרמת עבודה זרה על ידי זה. ואם תאמר אם כן נאמר שיהיה אסור להוליד כל בן, שמסתמא יעשה עבירות. וי"ל שבישראל מסתבר שיעשה הרבה יותר מצוות מעבירות. יותר מזה, נראה שאולי ע"ז שאני, שמצאנו איסור בהגרמתו ("לא יישמע"). כן נראה, שלכאו אחר תיילד, ואז אינו לפני עוור. יש לדון, שאולי רק נאסר מדרבנן, כשאר מסייע לדבר עבירה.
* כו:
** כרות -
אז, נמצא שגויים רוצים בזה, ושאנו צריכים לחוש לזה.
** כרות -
אז, היה אפשר לומר שרבי מאיר מתיר כן בסריס. יש לדון אם אסור לגרום עבירה זו של סירוס (ע' בגמ' בב"מ אם גויים מצווים עליו), שהוא אסור גם אחר סירוס, או שאז גורם שאין בנ"י ושמבטל מצוות פו"ר, שאז לא יתקיים כאן. בין כך ובין כך, אם גוי ידוע שהוא סריס, לא יהיה בעיה.
אבל, נראה שלא רצה לתרץ כן, כיון שבדרך כלל מילה נעשה על תינוק, ולא ידוע כבר אם הוא סריס.
* כז.
** לשם הר גריזים -
צריך לחשוב מהו האיסור בזה. אולי מכוונים ממש לשם ההר עצמו, וזה ע"ז. צריך לומר שדהם מכוונים לזה, אבל עובדי ע"ז לא מכוונים לשם ע"ז שלהם (מסתמא מפני שאין בחוק שלהם למול).
** והתנן -
ואם תאמר איך לומדים משם; הרי זה תלוי בלשון בני אדם. וי"ל שאם תעיין שם, תראה שנלמד מקרא, ואינו תלוי בלשון בני אדם, אלא בלשון תורה.
** והתנן -
קצת קשה, שיודעים שיש דיני ערלים שנוהגים בישראל שהוא ערל ממש (כמו איסור לאכול קרבן פסח). נראה שכיון שהוא כבר אסור לגוי, כשממעט ערל, צריך לומר שמכוון למי שהוא באמת ערל (ואף שהוא ישראל). אבל, בדרך כלל, אין זה פירוש של המילה. ותחשב.
** אתחלה -
קצת צריך ביאור מה לנו בהתחלה שלו, שלא היתה יכולה לקיים את המצווה, ואז אינו אף התחלה במצוה. (יש בזה שני קושיות. יש לדון למה זה לא פסל את המצווה. ויש לומר שישנו... רק בסוף. גם יש לומר שכיון שלמעשה אין שם ערלה, רק יש מצווה לסלק את המצוה האחרון שנשאר. גם צריך ביאור למה זה יציל את משה אם אינה מילה כשרה. ויש לומר שעושה שיותר קל למשה למול.
* כז:
** טהור -
מעניין, שהיה טהור בטעות.
** טהור -
מעניין שמשווה "טהור" ו"מותר." לכאו', הייתי אומר שטהור מדבר על מה שהוא בעצם, ומותר כולל גם דבר שיש בו קולא מפני הצורך (כמו זה, באמת).
** דתניא -
באמת, יש מי שתמיד אוסר, אבל יודעים מה היתה שיטה של רבי יהושע, ואז ידועים מה היתה כוונתו.
** שיולי -
עיין במה שפרש"י. לולי רש"י, היה יותר נראה לומר שסובר שלא בטוח מה לעשות, ושואל להרבה מומחים. אז, בין הכל לא יועלי, וגם יראה שהוא שקרן ורוצה להמית אותו.
* כח:
** לכ"ע שרי -
אולי זה כעין שוי"א חתיכה דאיסורא.
* כט:
** גופיה מנלן -
נמצא שלומדים דבר מדבר מדבר....
** שהיה מתחלתו -
עיין במה שפרש"י. לולי רש"י, יש לומר שרצה לומר שהוא רק בחומץ שבא מיין, ולא במין אחר של חומץ. (באמת, היום בארה"ב, רק קוראים שם "ויניג"ר" למה שעשוי מסיד"ר של תפוחים. בבריטני"א המצוי ביותר הוא ויניג"ר שנעשה מחיטים וכדומים. אבל, באורופא יותר מצוי חומץ שבא מיין.
** חרס -
עיינתי בספרי פנגיו"ן למצוא מקור אחר לזה, אבל ל אמצאתי (חוץ מבגמ' זה).
* לא.
** שריקא וחתימא -
איני מבין כל כך מה שצריך. נראה שצריך שיחתופ אותו, ושוב להפך כלי עליו, ולשרוק את הכלי שם. ויש לדון, שלא מדבר על חתימתו עד אחרי שמדבר על הכלי, ואז קצת משמע, נגד זה, שהחתימה הוא דבר שעושה על הכלי. ותחשב.
** פיו למטה -
יש לדון אם יודע גוי כן קודם שפותח את החותם הראשון. אם יודע כן, טוב, אבל קצת מחודש שיוכל לדעת כן. אם לא יודע כן, קצת מחודש שמהני, שבדרך כלל, צריך להיות שלא רוצה להתיר פעמיים ולחתום פעמיים. כאן, לא מבין כן עד שכבר התיר. אז, רק צריך להתיר עוד פעם (אבל, עדיין, אותו פעם אחת אינו פעם ראשונה, אלא הוא כבר אחרי פעם אחת).
** אלא שם -
ומלמדים- יש לדון מה רצה לומר. אולי רצה לומר שכולם יודעים, כמו שראיתי, מפני שהרבה למדו מן ת"ח, ולמדו זה לזה. אילו רק למדו מן הת"ח, לא מסתבר שכל אחד מהם יידע, אבל כיון שלימדו זה את זה, מסתבר. גם אפשר שרצה לומר שכולם יודעים, כמו שראיתי, ולכן מלמדים לי, כמו שקרה לי. ותו"ת.
** וחכמים -
עיין בלשון רש"י. קצת מוזר מה שמדבר עליו בלשון דיעבד (אומר שהוא אסור לכתחילה לעשות כן, אבל אם עושה כן לא נאסר בהנאה), ולא אומר שהוא אסור באכילה ולא בהנאה. ותחשב.
** קפיד -
ואם תאמר למה יקפדו על הסתומות יותר. אפשר לומר שחושבים שכבר ייאסרו הפתוחות, שלא יודעים מה קרה לו, שאולי גוי לקח מן היין ממש. אבל, חושב, רק הסתומות יכול גוי לאסור. ותחשב.
* לא:
** בעיר -
לא מבאר למה יש לחלק. נראה שלא רואים אותו בני אדם בדרך, ואז לא חושש שייאסרו.
* לב.
** דרדורין -
עיין ברשי. נמצא שלא שייך בכלל, לכאו', למה שפי' רש"י בדורדייא, אף שהמילים הם כמעט שוות.
** בעיניה -
לכאו', אז, בשל אדריינוס, נחשב בעינו מפני שראוי לעשות בעינו ממנו. גם יש לומר שכאן האיור הוא העיקר, והחרס הוא רק להוליך את האיסור. ותחשב.
** אב"א -
קצת קשה למה לא רק אמר שפעמיים הגיד כן, ופעם אחת הודו לו ופעם אחת לא הודו לו. אולי לא מסתבר שישנה. יש לדון למה, שאולי אמר לפלני חכמים שונים, שכך צריך לומר לתי' גמ' ש"גודא" ו"גודע" שאני. ויש לדון, שאולי יותר קל לומר שהחכמים חלוקים אם נאמר שהאומר שונה. גם אפשר לומר ששם מה שמשנה אינו למי נאמר, אלא מי נאמר. ויש לדון, שיל"ד אם "הודו" רצה לומר שהודו שכן קרה או שזה הדין. לשני, לא מסתבר לחלק על פי מי שאמר אותו. ותחשב.
** אבל בנו -
צריך ביאור איך מבאר לשון רבים. ע' בב"ב שבן יחיד, לפעמים, נקרא בלשון רבים. יותר נראה שמשנים את הגי' (או לעשות "בניו של רבן גמליאל," או "הודה לו." אבל, יש לדון למה לא מבאר גמ' את זה בפירוש.
* לב:
** מאי נפקא -
נראה שהיה מקשה לו ככה: אם אתה חושב שלא חולקים, תקשה למה אמרתי את זה. מן הלשון שלך, אני רואה שאתה שואל בדרך שאלה אם חו'. אז, לך אני מקשה מה לנו בזה, שבין כך ובין כך, יודעים מהו ההלכה. יש לדון.
** שמטמא -
יש להעיר שאין קרא זה בתורה, אלא הוא בתהילים. אז, לא פשוט שדורשים את דרשה זה לכל דינים שלו, ולא פשוט שייאסר. ותחשב ותעיין.
** חזרה -
ואם תאמר למה נאסר; אף אם לאחר זמן ילך לעבוד, לא ייאסר עכשיו. אולי רצה לומא שייאסר לאחר זמן, ביום איד. דחוק, שאז גם גוי ייאסר. ויש לדון, שאולי לא מדברים במי שהוא כעובד של ע"ז זה. מחודש. אז. שנאסר בהליכה. וגע שאפשר שכאן מדברים בחג ארוך, שהולכים וחוזרים והולכים וחוזרים.
* לג.
** ציר ומורייס -
עיןן במה שבאר רש"י. לולי זה, היה אפשר לומר שלא מתיר לכל דבר, אלא הוא עצמו מותר להעמיד שם. לכאו, ההסבר יהיה שהטעם שלו כל כך חזק עד שלא מקבל אעם של יין כל כך.
* לה:
** איבו -
השם של אב של רב היה "אייבו." אבל, לא נראה ששווה לאיש זה, שאיש זה לא הקפיד על איסור זה, ואב של רב היה תלמיד חכם, ועוד שרנב"י דבר על איש זה, אף שחי הרבה שנים אחרי רב.
* לו.
** לודאה -
לא הבנתי את התירוץ.
* לו:
** זנות -
יש לדון אם אסרו כל זנות או אסרו זנות של בת ישראל עם גוי. תמר היתה בת ישראל (כיון שהיתה במשפחת יעקב), ומסתמא הבועל היה גוי.
** צער גדול -
כמובן, קצת קשה למה היה כן, שהרב כבר ידע את התשובה כשתלמיד שאל לו, כיון שהוא כבר שאל לרב שלו. ותחשב. אולי שכח אותו או אולי לא רצה להגיד לו.
* לז:
** והא הל' -
עיין בגמ' בתחילת נדה, שלא נכון שתמיד מקילים בו. שם, יש ציור שחולקים בו רבי שמעון ורבנן. אז, יש לומר שהוא הקיל כרבי שמעון.
* לח.
** ריש אוניה -
כעין זה, עיין בכתובות (ה).
** מעשה שהיה -
צריך ביאור, עדיין, מהו החידוש. נראה שמחדש שאין רוב חגבים שנראים ככשרים (כשהם חרוכים) כשרים.
** קרובה -
יש להעיר שאינו רק ממהר אותו, אלא הוא הסיבה לבישול שלו, שוהא מתבשל כיון שהוא שם, והוא שם מחמתו (אף שבלי הוא, היה במקום אחר שיבשל). מה שבא לו אותו קרק' מיוחד, שהוא כאן ולא שם, הוא חשוב במיוחד, כיון שזה ממהר את הבישול.
* לט.
** קשרי מוכס -
עיין במה שפרש"י. יש להעיר שאז טוב שיהיה לו קשרי מוכס, שאם אין קשרים, יגבהו ממנו פעמיים. נראה שמחמת זה לא יגבה בלי קשרים, ואז לא טוב היות לו קשרים.
** קשרי מוכס -
משמע שגמ' לומד מזה שאשה הולכת אחרי הבעל. מעניין מן האגדה גבי אשת קרח ואשת און בן פלת.
[אגב, הק' לי. א.י.ש. למה לא אומרים שעבירות צ' כוונה. אין זה כל כך קשה, שלא מסתבר שצריך, שמי יכוון. לא קשה איך אפשר לחלק; איני יודע למה מצוות צ' כוונה, אבל לא נ' שיהיה קשה.]
* לט:
** ר"י בן גמליאל -
נמצא שמביא דבר בשם אחיו. (אין זה מוכרח.)
** וכי קאי -
מסתמא, זה לא יהני לפי אביי שאין נכנס ויוצא מהני. ותחשב.
* מ.
** ובדגים -
צריך ביאור מה מקשה מכאן, שזה אומר לנו איך לבדוק, אבל כיון שבודקים, יודעים שיש מינים שהם כשרים, ויודעים איך נראים, ואז רק צריכים לבדוק את הראשים. ואם תאמר למה לא הזכירה תורה את הראשים. ויש לומר שלא קל לתורה לבאר דבר כזה. גם יש לומר שיש הרבה מיני דגים. נראה שצריך לומר שמקשה גמ' למה בודקים בראשים, ולא בסנפיר וקשקשת.
** קראי -
נמצא שקורא לאמוראים חשובים בשם קראי. (יש להעיר שבתוך זה רואים שאינם כקראי, שלא צריכים שלש פסוקים.) נראה שאולי רצה לומר "בני אדם שהם בקיאים אפילו בקראי," או "... שהם בקיאים בדרשת קראי."
* מ:
** יין תפוחים -
אז, נמצא שאם אשאל איפה בא אפ"ל סייד"ר בגמ', התשובה הוא בע"ז (מ:).
** ומצאו -
עיין בב"מ שמזכיר יסורים של רבי. אולי זה אותו דבר, וכך ריפא אותו ה'.
** עומדים -
רצה לומר, לא תימר שכיון שכל זה גזירה, גם על זה נגזור, אלא רק על מה שדומה לנעבד, או מה שראוי להיות נעבד, גורסים.
* מא.
** מחלקת בשל -
אז, יש לומר שחול' רבי מאיר ורבנן אם גוזרים זה מחמת זה.
** כדור -
מלשון הגמ', נראה לפרש שמחשיב את עצמו ככדור (כמו שאומרים בצפור), והוא שכדור הוא דבר שיכולים לזרוק גבוה.
** עטרה -
יש לדון אם הוא לובש את העטרה או אוחז בו.
** צואה -
צריך ביאור למה ישימו שם צואה אם אינו לכבוד. אולי לפעמים עשו כןל זה כדי לגנותו. גי"ל שהיו חייבים לעשות לו צלם, אבל שנאו אותו, ואז עשו לו ככה.
* מא:
** בסיסן -
יש לדון אם רצה לומר שמחוברים לשם או לא. אם מחוברים, רואה אני איך אפשר להיות שהרגל הוא שבר, שאולי היה מחובר, ונשבר משם. אבל, יש יותר קשה, שלא בדרך כלל מחובר לבסיס, וצריך לומר שרק עשו יד. ותחשב.
** מסתמא -
יש להעיר שמשמע שלא חולקים אם צריכים מעשה ביטול, אלא אם יבטל בלבו מחמת זה. גם יש להעיר אם ביאור מילת "מסתמא" הוא שמחמת הסתימות מניחים שהוא מבטל או מחמת הסתימות מבטל אותו. תריך לבאר את השני, אבל נראה שיש בו ממש. ותחשב.
* מא:
** ספק מוציא -
יש לדון למה לא רק אומר שהוא ספק, וספק דאו' לחומרא. ותחשב.
* מב:
** מפלח -
צריך ביאור למה לא דוחים שאסור לפלוח להם, אבל לא מניחים שלהם מפלח. נראה שמדייק שלהם מפלח ממה שנקט אותם לדוגמא.
** צורת חמה -
עיין במה שפרש רש"י. צריך יבאור מהיכי תיתי, שאולי אין מקום אחד שעובדים לכל צורה.
* מג.
** יוסף -
מעניין, שאמר "אדם," ונמצא שצ"ל אדם פרטי.
** הלכה כרשב"א -
משמע שחולקים; לשון של רשב"א לא משמע כן בכלל.
** מאיסורא -
צריך ביאור מה רצה לומר. נראה שרצה לומר שעדיין רוצה את הקנין, כיון שטוב לקנות את האלוה כיון שהוא עוד נעבד. ותחשב.
** לבנות -
לשון שלו משמע שהיה מצייר הרבה ציורים של לבנה (כמו קרסנ"ט, מלא, וכדומה). לולי זה, היה נראה שיהיה לו דמות אחת, והיה יודע לכסות מקצת ממנו, עד שמראה צורות שונות.
* מג:
** כל הפרצופים -
קשה למה לא מפרשים את זה כמש"א לעיל. אולי ידועים שזה מדבר בעשייה.
* מד.
** עשה לך שרף -
משה לא היה חי עוד. אלא, של יורשיו היה. צריך ביאור של איזה יורש היה. תחילה, נראה שצריכים לדון מהו כוונת גמ' כשאומר תי' זה. אולי הוא לומר שלא, באמת, היה עבודה זרה. קשה איך לא היה עבודה זרה, ואז מפרש שהוא מפני ששל אחר היה. אז, באמת, היה אפשר לומר ששל הפקר היה, ונעשה של איזה אדם אחד שזכה בו. אבל, אין זה נכון, שלא קרה כן, ולא היה הפקר"א אל היה של משה רבינו (ויורשים שלו), ולכן אמר כן. גם אפשר שגמ' מוכיח את התשובה, שמוכיח שלא היה נאסר מחמת עבודה זרה, שאין אדם אוסר מה שאינו שלו. לפי צד שני, צריך לומר שידע שלא היו יורשים של משה מן העובדים אותו. יש לדון בזה, שהיו הרבה יורשים. ויש לדון כמה יורשים צריכים לעבוד אותו כדי לאסור אותו. (אולי שייך לזה גמ' בביצה (גבי עירובי תחומים) וגם בכ"מ (בנוגע שיטת רבי יוחנן המובא בב"ק (ע) ובמק"א) שדן בברירה בירושה. ותחשב. גם נוגע לזה מה שנכתב בע"ה בדיבור הבא.)
** שלך -
משמע שזה רק מפני שנעשה משלו. אבל, אם היה של ציבור, שפיר יכולים לאסור אותו. זה מעניין, שלא כולם עבדו לו. יש לדון כמה בני אדם צריכים כדי לאסור. יש לדון, באמת, למה לא יכול אדם לאסור דבר שאינו שלו. יש לדון אם הוא מפני שלבעל יש זכות שאין אדם יכול לשנות את חפצו או מפני שאין סיבה לשינוי חפץ אם אינו הבעל של החפץ. ותחשב. גם יש לדון כמה בעל הוא כאן (כיוןש הוא רק חלק מן הציבור), וכמה בעל צריך להיות. (גם יש לדון אם מה שאין שאר בעלים עובדים אותו רק עושה שאין כל כך סיבה לאסור אלא עושה גם סיבה להקל. זה תלוי במה אוסר עבודה זרה, אם הוא מה שנעבד או מה שבעל נותן לו שם, שחושב עליו לאלוה. אם נאמר כשני, יש לומר ששם בא מבעל אחד, אבל יש שם לאידך גיסא (שאינו אלוה) מבעל שני.) ותשחב על כל זה. (גם שייך לזה ענין קנין של ציבור.)
** כתותי לא היה צריך -
יש לדון למה לא צריך לכתות אותו מדין המבואר בסנהדרין, כשדבר גורם לאדם לחטוא. אולי גם זה לא נוהג בדבר של חבר שלו. ותחשב. (גם אפשר שאין גנות בזה; עיין שם.)
** ומועלים
- עיין במה שפי' רש"י. יש להעיר שלפעמים אומר שלא נהנים ולא מועלים ולפעמים אומר שמועלים, כעין כאן. החילוק הוא שכאן יש מעילה מדרבנן, ושם אין מעילה מדרבנן, אלא איסור להנות. (לכאו', החילוק הוא אם צריך להחזיר את הדמים.) אז, יש לדון למה לא הזכיר רש"י שיש מעילה מדרבנן, ולא רק איסור שלא להנות. ותחשב.
** ואין אדם -
עיין ברשי שתולה אותו במה שלו מוקצה. יש לדון אם הענין הוא איך שחושבים עליו (מהו הצורך שלו) או מה עומד להיות (שכיון שאינם בעלים שלו, לא עומד להיעשות בו כמה שרוצים). גם אפשר שהענין הוא שהוקצה, אבל אותו הקצאה לא משנה, כיון שלא נעשה על ידי בעל. לא משמע כן מלשון רש"י.
** שלך -
ואם תאמר אז איך חזקיה היה יכול לכתות אותו, שאינו שלו. ויש לומר שממ"נ- אם היו היורשים בני תורה, רצו בזה, ואם לא, עבדו אותו, ונעשה עבודה זרה. דחוק. יותר נראה שכיון שהיה מלך היה לו כוח זה. ויש לדון מהיכי תיתי למלך כוח זה.
** מטיל לים -
יש לדון אם רבנן חולקים גם על זה. לכאו', חולקים, שאומרים שצריך להטיל אותו לים המלח. משמע שאף בזה חוששים שיהנה ממנו. אבל, קשה אז מה שאומר רש"י שאין איסור כיון שאומר "ויזר על פני המים." אולי שם שאני כיון שלא נתן אותו למקום גדול של מים, אלא למקום קטן הכנוס. (צריך ביאור איך רואים את זה מן הקרא). יותר מזה, לא רק שהוא כנוס, ויכול לשמור אותו, אלא שתו אותו מיד. ויש לדון אם שתו את כולו. ותחשב על זה. גם אפשר להיות שגם רבנן מתירים זה, אלא שנתינה לים המלח יותר קל (על כל פנים, לתנא שכ' את שיטתם). רק חולקים, בעיקר, בנתינה לתוך האויר.
** וישרפם וישאם -
משמע שרוצה שיאמר שניהם. יש לדון למה לא רוצה שיאמר רק "וישאם" בשניהם או "וישרפם" בשניהם. ותחשב.
** דכתיב ויקח את עטרת -
לא צריך עוד ראיה; כבר הביא ראיה. נראה שזה יותר מפורש, שלא צריך לסמוך על מה ששינה את המילה.
** אבן שואבת -
איני מבין את זה כל כך. לכאו', אבן שואבת הוא מאגנ"ט. אבל, צריך ביאור איזה דבר היה למעלה ממנו. אולי רק לבש אותו במקום שהיה מתכת עליו. גם יש לומר שהיה לו חלק שהיה למעלה ממנו, והיה מתכת. וא"ת אם כן מאי אהני, שבין כך ובין כך הוא נושא אותו. נראה שעל ידי מאגנ"טים, יכול לשים את האבנים באמצע ממש, עד שאינו נשען לא למעלה ולא למטה. ותחשב. וע' בתוס'. יש להעיר שאז לא צריך אבן שואבת, שמספיק לתת שם הו"ק.
** ראויה -
יש לדון מה רצה לומר; לכאו', היה משבח דוד, ואומר שהצדקות שלו או היופי שלו היה ראוי לכך. שוב ראיתי שרש"י פי' שר"ל שהיה כגודל ראשו, וזה היה חשוב שהיה סימן. (אגב, יש לדון מהיכי תיתי להם שהיה סימן, שבדקו את בני דוד בו.)
* מד:
** פרוקלוס -
עיין במה שכ' רש"י. יש לדון אם רצה לומר שהיה מין, ושהיה גוי, או שרצה לומר שזה לא היה השם שללו, אלא שזה היה מין אחד של גויים. אז, כאיו אמר, "נוצרי שאל...." ותחשב.
גם יש להעיר על כעין זה ב"בן פילוסוף." מוזר לומר שזה ממש היה שם. אולי נקרא שמו אחרי הלימוד, אבל גם זה מוזר. אפשר לומר שהיה בן פילוסוף, שהיה עסוק בפילוסופי. גם אפשר שזה מין ע"ז שהיה, שהיה מין פרוקלוס, שבא מן הפילוסופים.
** את אלוהיהם -
יש לדון אם זה מוכיח שאין עובדים לאותו אלוה או שאף אם עובדים לו, אם לא נוהגים עמו בכבוד, לא נאסר.
- צריך ביאור מה חשב אותו גוי. צריך לומר שסבר שהמרחץ היה כעין הקרבה לאותו עבודה זרה. צריך לומר, אז, שאם עושים לו בית או כבוד אחר כזה, אף שהוא מחובר לקרקע, נאסר בהנאה. גם יש לומרש סבר שיש יותר כבוד לו ביותר בני אדם רוחצים, ואז אסור לרחוץ שם. הפסוק שהביא משמע יותר כצד ראשון. שוב ראיתי בגמ' שידון בזה.
** תנא כשיצא -
עיין בלשון המשנה. לכאו', צריך לומר שמשנה לשון של המשנה. אם כן, צריך לומר שלשון זה- "תנא..."- משנה את הלשון. יש לדון אם תמיד עושה אותו דבר; על כל פנים, רואים שיכול להיות שאומר לנו לשנות את הגירסא.
** זו אין עבודתה -
אז, מה שזה עבודה של אפ' במרחץ לא מספיק. ותחשב.
** אני לא מבין
את ההו"א שיהיה מותר לומר דברי תורה בלשון חול. כנראה, יש סברה לומר שכיון שלא אומר אותם בלשון הקודש, אינם כל כך קדושים. אולי סובר שצריך צירוף של דברי תורה ולשון הקודש. נראה יותר לבאר על פי מה שכתוב בכ"מ שיש כוונה בעצם למילים שבלשון הקודש, ולא למילים בלשון אחר. (תחשב מהו הכוונה של זה.) אם כן, בלשון הקודש הרי הוא אומר דברים של דברי תורה, וזה אסור. אבל, במקום אחר, אינו אומר דברים של דברי תורה, אלא אומר דברים, וממילא באים הבנה של דברי תורה לתוך מוח של חברו. ותחשב. אפשר גם לדון מהו הצד לאסור לשון הקודש. בפשטות, הוא שיש קדושה ללשון הקודש (ולכן נקרא לשון הקודש). אבל, על פי מה שכתבנו, יש לומר שכל דיבור הוא חשוב וקדוש (שלכן נקרא אדם אדם), אלא שאין דיבור אלא לשון הקודש. לשון הקודש הוא מילים עם כוונה, וזהו דיבור, אבל שאר שפות הם רק הסכמת אנשים, והרי גם לבהמות יש קצת הסכמות. ותחשב על זה, שכמובן עדיין יש חילוק בו בין בני אדם לבהמות.
** וכי בא בגולה -
אין זה קושיה על התירוץ, אלא למה צריכים לאותו תי'. אז, באמת, הוא קושיה על כל התירוצים (אבל נקט הראשון, כיון שהיה ראשון).
** כטובת אחרים -
לכאו', הענין הוא שמהנה להם. אז, מעניין שמה שהוא בא קודם מתיר אותו להנות להם. ותחשב.
** כטובת -
אז, הבעיה הוא שמהנה לעבודה זרה. (יש לדון אם הוא שבני אדם רואים שבא לע"ז הנאה, כיון שחשובים שמקבל הנאה, או שמפני זה אחרים יעבדו את העבודה זרה. ותחשב.) יש להעיר שלכאו' אין זה נוגע לקרא שהביא פרוקלוס. אז, מה שקרה הוא שהק' מן הקרא, ור"ג לא השיב לזה, שפשוט לו שאין בזה בעיה, אבל אמר שיש בעיה אחרת, והשיב לו. לכאו', צריך לומר שהשיב בזה גם לבעיה של פרוקלוס. ויש לדון.
** להרהר -
כיון שאסור להרהר, צריך ביאור מהו החילוק בין לשון הקודש ללשון חול, שאין אדם מהרהר בלשון, אלא מהרהר מחשבות. יש לדון אם זה נכון. גם יש לומר שיש הרהור בלשון (בוודאי יש), ורק זה אסר. ותחשב על זה.
** כטובת -
יש לדון אם החשיב את האליל בעיניהם או החשיב את בית הכסא לעיניהם (וזה גרם הנאה לעבודה זרה). ותחשב על זה.
** ואני אומר -
נראה שאולי חולקים אם אותו משנה ("רק בה...") אומרש עשה כולם (שאולי אז משמע שהיה המשך זמן) או שעשה אחד מהם (שאז יש לומר שהיה רק לפי שעה). ויש לדון בזה.
** רבה בר עולא -
איני מבין מה בין זה לשל אביי. ותחשב. נראה שהוא דייק מלשון אמירה, שמשמע שבזה בלחוד אסור (יש לדון למה סובר כן), ועל זה מקשה. לעיל, הקשה שאף אם נעשה לו, אינו אסור. צריך ביאור למה לא אמר כאותו ממשנה לקמן. גם צריך ביאור למה לא תי' כאן כדלעיל, שכאן הוא מהנה לה.
** נוי -
נראה שמניח שהרחיצה לו נוי, ולא המרחץ. ויש לדון אם הרחיצה עצמו נוי, או שטוב להיות לו מרחץ חשוב, והוא יותר חשוב אם הרבה בני אדם רוחצים בו.
* מה.
** צפוי -
אם הייתי למדן, הייתי דן אם ההרים אינם ע"ז או שהם ע"ז המותרים. הייתי מוכיח מדין ציפוי כצד שני, אבל הייתי דוחה שאולי מה שייחד אותם לצורך עבודה זרה- אף שמה שהוא בדעתו להיות עבודה זרה אינו, באמת, עבודה זרה, מספיק לעשות איסור. ותחשב. (אינו בעיה לעשות כאן חידושים, שהרי מבארים קרא, ולא מחדשים מסברה.)
עיין ברשי שמביא ראיה חזקה שלא נחשב עבודה זרה. ויש לדון, שגם בדין זה יש לומר שלא אוסר. ותחשב. אבל, הקושיה שם, אז, צריך ביאור. ותחשב. ושי לדון איך אותו גמ' ידע.
** הם מותרים -
עיין ברשי. יש לדון למה מדבר בהנאה מן ההר אחרי שתלש אותו, ולא כשהוא מחובר. היה נראה לומר שיש יותר חידוש כשהוא מחובר, שאחרי שתלש אותו, שינה אותו באופן גדול ממה שהיה כשעבד אותו.
** תפיסת -
אז, נמצא שאף שאין חילוק בדרשה, כיון שיש חילוק בסברה, מחלקים.
** ציפוי הר כהר -
צריך ביאור איך רואים מחלוקת זו בתוך דבריהם.
** כהר -
עיין ברש"י שפי’ שהוא מפני ביטול להר. (כן נראה, באמת, מן לשון גמ’.) היה אפשר לומר שהוא שאין איסור על ציפוי הר, ולא מפני שבטל להר. (נראה שיהיה נפקא מינא אם עובד לציפוי; אולי רש"י סובר שבזה דנים.) נראה שאם לא נדחה כמו שכתבנו בביאור רש"י, יהיה מוכרח לומר כמונו ולא כרש"י, שהרי אם יש לו מקור, צריך לומר שלא בטל, ואם אין לו מקור, יאמר שאינו אסור, כיון שאין ההר ע"ז. ותחשב. אולי לכן לא דורש את המקור. עדיין יש לדון למה אותו סברה מספיק לעשות שלא נדרש, אבל סברה שלנו לא מספיקה. ותחשב.
** ציפוי -
יש לדון מה בכלל תלושים. עיין בלשון רש"י, שמשמע שהוא דבר המחובר. גם אפשר שהוא דבר גבוה וגם אפשר שהוא דבר שאין עיקר צורך שלו לנאות את ההר. ותחשב על זה.
** נראה ששני
שיטת בגמ’ הולכים ככלל שתנא בתרא לטפויי, אבל חולקים אם בא לטפויי על החידוש או על החומרא. ותחשב. גם יש לומר שחולקים על מה בא לטפויי, על החידוש להקל (ואז מיקל יותר) או להחמיר (ואז מיקל יותר). ותחשב.
* מה:
** ולבסוף -
יש לדון מה לנו במה שבתחילה עבדו. אולי מה שעשה אותו על דעת ע"ז עושה אותו ע"ז, ואולי מה שנטע אותו על דעת ע"ז נחשב עבודה לו, וזה עשה אותו ע"ז.
** תלמוד לומר -
אם נלמד ממה שכ’, “ואשריהם,” קשה מהיכי תיתי לרבות גם מה שנטעו ולבסוף עבדו. אולי לא מסתבר לחלק. גם אפשר שכיון שלא דורשים "ולא אילנות…,” אין מקור למעט. (יש לדון למה לא לעשות פשרה בין שני הפסוקים. עיין בתחילת פרק אלו נערות, שגם שם יוצא (ע"פ מש"כ תוס’) שלא עושים פשרה בין שני הפסוקים. ותחשב.
שוב ראיתי שלא אומר כן. לא קשה לדחות מה שכתבתי ראשון, אבל מעניין לדחות צד שני שכתבנו. נמצא שסובר גמ’ שנעשה פשרה (שלכאו’ כן הוא) בין שני המקראות- ובהכרח.
** כל מקום שאתה מוצא -
אז, יש לדון מהיכי תיתי למעט הר. ותחשב.
** עיקרו -
נמצא שאף שעבד לעיקר שלו, לא נאסר. רק נאסר מה שמוציא לאחר העבודה. (בזה, כמובן, הוא שונה מעבודה זרה של עץ ואבן, שנאסר אף שלא גדל כלל.)
עיין ברש"י, שאולי משמע שעיקר לא נאסר כיון שהוא בארץ. רק השאר, שאינו כל כך בארץ, יכול להיות נאסר. אין הסברה נראה כל כך.
** אילו לא נאמר -
נמצא שכשאומר "אילו לא נאמר" לא רצה לומר שבלי פסוק שני, פסוק ראשון שמביא הוא המקור, אלא רצה לומר שפסוק שמביא הוא פסוק שעושה פסוק שני למקור (ואילו לא נאמר, לא היה פסוק שני מקור). צריך לחפש במקומות אחרים שאומר כן.
** שצריך לשרש אחריה -
יש לדון אם זה מפני שהשרשים הם אותו אילן או מפני שמה שייצא מן השרשים יהיה אותו אילן. (נראה שיש לומר סברה לכל צד, ששרשים היו ממש חלק מן האילן, אבל הם מאד שונים, שהם רק שרשים, ולא אילן.)
* מו.
** אמר לו ר"ע -
נמצא שלבסוף ר"ע יסבור כרבנן. קשה, שבמשנה לא משמע כן. שו"ר בתוס’.
** היו קוראים -
יש לדון אם חוב לתת לו שם גנאי או היתר לתת לו שם גנאי או שניהם (או שיש חוב שלא לומר שמו או שם טוב, והיתר אף לומר שם רע.)
** יכול לא לשבח -
קשה, שזה כבר נשמע מ"לא יישמע על פיך.” נראה שהו"א שזה רק שלא יישמע דרך כבוד. למשל, לא יגרום שאדם ישבע על שמו. הרי, זה כבוד לשמו (שאין אדם נשבע בשם מה שאינו חשוב). אבל, אולי אם אומר "ישו הנוצרי הוא ממזר,” אז אין בזה שום כבוד, ואולי היה מותר לומר כן עם שם עבודה זרה. ויש לדון אם אחרי דרשה זו רואים ש"לא יישמע" אוסר כל מיני אמירתו, ואף שלא בדרך כבוד, ואף בדרך גנאי, או לא רואים כן. ותחשב. גם אולי יש לדייק ממה שאומר לקמן, “היו קוראים….” לשון כזה משמע שלא מדברים על שם האמיתי שלו. (אולי כמו שיש לנו שם מפורש של ה’, אבל לא אומרים אותו, אלא אומר "השם,” דך יש לגויים דבר כזה, לפעמים.) אולי יש איסור של "לא יישמע" בשם האמיתי שלו. גם אפשר שזה רק עשה שמוסיף על הלאו. אבל, לא נראה כן, שלכאו’ נוכל להוכיח שאינו רק עשה שמוסיף על לאו, אלא בא לאסור דבר אחר, כמו שלא רוצים לאו שמוסיף על לאו, אלא דורשים ממנו דבר אחר. יש לדון, שאולי יותר מסתבר להוסיף עשה על לאו (שמוסיף יותר). ותחשב.
** הן אסורים -
לכאו’, זה קצת לאו דווקא, שכמו שמבואר מן הגמרא לעיל, לא כולם אסורים. (אגב, יש ללמוד מזה שאין העיקר מעלה את הנזרע לאיסורים. עיין בנדרים, שדן גמ’ בזה. אולי מדברים בשייתר עליו האסור; צריך לע’ שם, שנראה שר"ן סובר שאף בזה דנים. אבל, אולי יש לחלק בין ע"ז לשאר דברים. שוב נראה לי שאולי כוונת גמ’ הוא שכשהיה רק עיקר היה מותר, וכשהיה צריך גידוע, אסור. אבל, לשון שלו לא משמע כן.)
** ורבנן -
יש לדון אם רוצה כן כדי שיהיה לפי רבנן או כדי שיהיה לכולי עלמא. לשון גמ’ משמע כצד ראשון; יש לדון, שאולי רצה לומר "אף לרבנן,” שפשוט שעדיין יכול להיות כרבי יוסי.
** בעלי חיים -
יש לדון מהו ענין של בעלי חיים. אלוי הוא שאין תפיסת אדם על כל הסוג, שאין אדם עשוה שום חי (יש לדון, שעושים בן. יש לדון אם נחשבים עושים, שהם שותפים עם ה’ בזה), אבל יש תפיסת אדם על סוג של אבן, שלפעמים אדם נוטל אותו מן ההר.
** לא נשתנו -
יש לדון שבהמה נונלדה ונתגדלה. צריך ביאור מתי תחילת בריאת בהמה; לא אומרים שהאבן נברא כשנפל (שאז נעשה בריה חדשה), אלא נברא קודם לכן (מתי שההר נברא).
אפשר שגבי בהמה כל השינוי שבא היה עומד לבוא, ולכן לא נחשב שינוי כל כך.
** לא נשתנו מבריאתם -
יש לדון מה לנו בזה. תפיסת ידי אדם הוא דבר שמובן לי, שכיון שבני אדם עשו מה שהוא, מחשבת בני אדם ומעשי בני אדם יותר חשובים עליה לקבוע לה שם. אבל, מה שנשתנה לא שייך בכלל. (אף שבצד השווה פורכים כל דהו, נראה שצריך להיות שום הבנה, שאם לא נפרוך ש"הר" ו"בהמה" יש להם מילה אחת, אבל "אבן שנדלדלה" יש לה שנים מילים, או דבר מוזר כזה.) נראה שאולי כיון שנשתנה, מקרים יותר חשובים לה לקבוע שם, שהם כבר קבעו לה שם. ותחשב. גם יש לומר ששם שיש לה לא כל כך חזק, שגם יש לה שם של קודם לכן. אז, מה שעושה יותר חשוב לו. ותחשב.
** בעל מום… יבש -
יש לדון איך יודעים דינים אלו. ותחשב.
** ומאילן -
ע’ ברש"י, שכ’ שצריך מעשה כדי לאסור, ולא מספיק אם רק משתחווה לה. איני יודע מה המקור לזה.
** לא תתיא -
יש לדון אם זה כלל בעבודה זרה, שלא דורשים צד השווה להקל, או דין מיוחד כאן. לצד ראשון, צריך לדון אם דורשים דרשות אחרות (ונראה שכל צד השווה קלוש, שאולי צד חמור נפרוך, וקל לדחות אותו). גם יש לדון, לצד ראשון, אם זה רק בדברים שנאסרים מחמת עבודה זרה או גם בשאר דיני עבודה זרה. ותחשב.
** בני ר"ח -
רש"י זה צריך להיות מוקדם (בתחילת הסוגיה).
** ביצה -
קצת קשה למה לא נאמר שלא נשתנה מבריאתו. צריך לומר שכיון שעדיין צריך צד השווה, אסור. אז, זה מלמד לנו דרשת הקרא של "שקץ תשקצנו.”
** הוי מעשה -
לכאו’, לא דן כמה הוא מעשה, אלא כמה שינה את הביצה. כמו כן בסנהדרין, כשחולקים אם השתחוואה הוא מעשה, על כעין זה דנים (אם נחשב מעשה לע"ז, כיון שלא שינה אותו).
** זקף -
איני יודע כל כך מהו זקיפת ביצה. אולי הוא שהגביה אותו לקמום גבוה (שהיה יושב על הקרקע וכדומה, ונתן אותו על סטנדר). אבל, יותר נראה שנתן אותו במקום שיכול לעמוד בזקיפה, ולא לשכוב. (יש צד ארוך וצד נמוך בביצה. בדרך כלל, יושב על צד הארוך. נותן אותו במקום שיושב על צד הרחב.)
** אי למאן דאמר -
נמצא ש"מיד" אינו מיד אחרי שמכין אותם, שמספיק מה שהם כבר גמורים, אלא הוא מיד אחרי שהם גמורים ודעתו להשתחוות להם. גם אפשר שצריך הכנה, אבל אין צורך שאותו הכנה יהיה מעשה.
** וכגון -
משמע שמה שאין אדם אוסר מה שאינו שלו הוא מפני שיש מניעה מחמת הבעל. אם כן, לכאו’, יכול לאסור הפקר. יש לדון, שאולי יש מניעה מחמת שאר בני אדם שיכולים לזכות בו. גם אפשר לומר שכאן בעל נותן אותו זכות לכל אדם. יש לדון למה יעשה כן. אולי כיון שגילה שרוצה בעבדות שלו, הרי רוצה שיעבדו אותו. יש לדון, שלא רוצה שייאסר. אולי כיון שהסכים שיעשו את האיסרו, אותו איסור יכול לאסור, שהוא איסור ברשות בעל. ותחשב.
עיין בלשון רש"י (ובאמת הוא לשון של גמ’ לקמן (נג:)), ש"שליחות" של ישראל הוא עושה. קצת משמע שצריך כוח של ישראל, ולא רק שישראל לא ימנע אותו. כמובן, אינו שליחות ממש, שאין גוי נעשה שליח, ואין שליח לדבר עבירה. וצריך לחשוב כמה דווקא הוא הלשון.
** דמנכרא -
יש לדון אם צריך להיות ניכר לנו (שצריך שנאמין שעשה כן כדי שייעבד) או שצריך להיות ניכר לגוי. ותחשב.
** דמנכרא -
יש לדון איזה מחשבה צריכה, מחשבה שייעבד או מחשבה לעבוד אותו. היה נראה שאף הראשון יהני.
** תיקו -
נראה שבדרך כלל אומר "תיקו" כשאין מה לדון בו (אולי מפני שאין מה לדון בו או אולי שאם יש מה לדון בו, אף שנדחה כל הראיה, אפשר להיות שנחיה את הדיון עוד, אבל אם אין מה לדון בו, יותר קשה להחיות את הדיון). הרי, כאן יש דמיון לדון בו. אולי פשוט שאינם ממש דומים, ופשוט שאין ללמוד משם, ורק דן אם אותו הדין נוהג. ותחשב. גם אפשר שתלוי באם נאמר את המאמר ושואלים אם זה דומה או אם אומרים את השאלה ושוב דנים במאמר. (זה רק מבני לפי צד ראשון שכתבנו בביאור מה לנו שאין מה לדון, והוא שהוא רק אם יש מה לדון או אין מה לדון, ולא מה שזה גורם שנוכל להחיות אותו).
* מו:
** מה אתנן -
לכאו’, רק ראינו איסור להקריב אותו (שאין מקור לומר ש"לא תביא" אומר יותר מזה). אז, רק משיב לשאלה ראשונה, ולא לשאלה שנית. שוב נראה לי מסוף הגמ’ שחושב לדרוש (אף שלא אומר כן בפירוש) מ"בית ה’ אלקיך" שאינו עושה כן לבית. (לקמן, זה גם מוכיח לו שמדברים במחובר, כיון שאין עושים בית מן התלוש. צריך ביאור למה לא, שנמצא אם תלש אבן ונתן אותו לאתנן.) יש להעיר שאף אחרי דיחוי שלו שלחומרא פרכינן, מצאנו תנאים שדורשים מ"בית ה’,” ואז עדיין רק שאלה ראשונה נפשטה.
שוב ראיתי שרש"י פי’ ש"בית" רצה לומר שהיא מביאה בית. לכאו’, אז זה מראה שני הדרשות. ותחשב.
** פרכינן -
היה אפשר לומר שלחומרא ולקולא לחומרא דרשינן או דנינן. נראה שלשון פרכינן רצה לומר שדוחים את הקל וחומר שהולך לקולא (אולי על פי מה שבארנו במקום אחר שלכל קל וחומר יש פירכא, במה שהדין ייצא מן הקל וחומר, ואז אינו כל כך חזק), כדי ללכת לחומרא. יש לדון למה אומר אותו כן.
אבל, עיין במה שפרש"י.
** פרכינן -
עיין בגמ’ בזבחים שמרבה גמ’ קו"ח, ושם מסיק שלא דורשים אף אחד מהם. עיין שם.
** משום שבות -
קצת צריך ביאור, שאין זה קל וחומר ממש, שהרי אחד מהם דין דרבנן. אלא, לכאו’, זה רק סימן, שאם רבנן העמידו את דבריהם, לעשות שאין חיוב פסח דוחה אותו, בוודאי אינו דוחה איסור דאו’. אולי משמע כמה שכ’ מקצת ראשונים שיש איסור קל מדאו’ בשבות.
** ר"ע -
מעניין שמחשיב מש"א ר"ע להיות קולא, שלא רק פוטר, אלא אף אוסר. ותחשב. (וא"ת אז רבי אליעזר מיקל. לא נראה כן, שכאן יש לשניהם חומרא זה על זה, ואולי גופא בזה חולקים- איזה נחשב החומרא.)
** יש להעיר
שהיה נראה שיש סברה לומר שלומדים דבר שבא ראשון בתורה בלי קל וחומר- שאז אין לו כבר קל וחומר- ואחר כך, כיון שנקבע דינו, לומדים קל וחומר ממנו. ותחשב.
** פרה -
יש להעיר שזה לא מצוי בכלל. ראשון, פרה אדומה לא מצוי. שני, אם היה פוסל, נמצא שהוא מאבד הרבה לתת לה מעט. (לא כל כך קשה לומר שהיא לא אומרת כן מפני שרוצה את הפרה, אלא רוצה שיוכיח לה את אהבתה לו. ויש לדון, שבדרך כלל זונה היא זונה, ולא אוהבים את זונה, אלא באים על זונה.)
** או אין -
דהא הנאה- אני מבין למה זה אוסר לעשות את החיטין, שנמצא שנהנה, אבל איני מבין למה זה יאסור את החיטין. אפשר לומר שהוא כדי שלא יקבל הנאה, אבל אז קשה למה אין כל איסור הנאה אוסר את החילוף שלו, ולמה רק עבדה זרה ושביעית (קצת) אוסרים את החילוף. ותחשב.
** זה וזה -
עיין בר"ן (נראה שהוא לקמן; הוא בביאור רש"י גבי ילדה שסבכה בזקנה) שפי שזה וזה גורם הוא משום ביטול. חוץ מן הקושיה הפשוטה שאין בן רוב, אלא הוא מחצה על מחצה, יותר קשה כאן, שהייתי אומר שאם היא גרמת יותר מן האב, שהיא גם מתעברת עמו. ויש לדון.)
* מז.
** דשא -
יש לדון אם רצה לומר שהחילוק כאן הוא יותר קטן או רצה לומר שהחילוק הוא יותר עומד לקרות (ולכן הוא יותר קטן).
** איכא דאמרי -
יש לדון אם דיחוי הגמ’ הוא על שני הצדדים או לא (שגמירי שגמ’ השיב דבר, ולא ידוע אםן הוא מימרא של רבא או חילוק זה).
** דשא -
קצת צריך ביאור, שאינו כן במציאות. עובר לא נראה כבהמה רגילה, ולא יכול לחיות בפני עצמה. אפשר לומר שזהו החילוק היחידי שאינו עומד לבוא. אף שכמובן עומד לצאת, יש בזה מעשה של יציאתו, ואינו רק גידול שלו. אז, אומר שהוא בהמה- עומד להיות בהמה- והחילוק היחידי בינו לשאר בהמות (שיכול להיחשב חילוק) הוא מה שיש דלת לפניו. ברי, אין זה מחלק.
** לר"י -
לכאו’, אף לר"י יש לאסור, שהיה משמע לעיל שרק אסר מה שגדל אחר כך. אולי צריך לדחות מש"כ לעיל כמו שדחינו שם.
** לר"י -
צריך ביאור למה לא דן בזה לעיל. צריך לומר שחיטים לא נעשים אשירה. כדי להיות אשירה, צריך להיות אילן, ולא זרע וירק.
** לולב -
יש לציין למה שכתבנו במקום אחר שאולי יש בלולב כעין קדשים. אולי לכן שואל בלולב בדווקא; אבל, אולי לענין שאר מצוות פשוט שאין בעיה. יש לדון.
** אין דיחוי -
יש להעיר שדיחוי של דם הוא, לכאו’, שאין עוד סיבה למצווה. (אין זה מוכרח, אבל כן היה נראה.) דיחוי זה הוא שפסול למצווה. אבל, מניח שהם שווים, שמה שאין בו סיבה של המצווה פסול למצווה.
** מצווה -
יש לדון מה יהיה החילוק בין מצווה לקרבנות. אפשר להיות כמה מאוס הוא (שאולי יש דברים שהם מאוסים להיות קרבנות ולא מאוסים לשאר מצוות), ואפשר להיות כמה מיאוס פוסל בו (שאולי יותר קל לפסול דבר מקרבן מחמת ממיאוס מלפסול ממצווה).
** דיחוי -
במקום אחר דנינו למה דבר נדחה. אפשר שהוא מפני שמה שהיה נפסל עושה פסול עכשיו (שיש מיאוס במה שהיה פסול או במה שהיה מאוס) ואפשר שמה שיש לו שם פסול נמשך, ולא נפקע בביטול הסיבה לאותו שם. אם נאמר כצד ראשון, נמצא ששאלה זו מאד דומה לשאלה אחרת לענין מצוות, והוא כמה מיאוס פוסל למצוות. (אבל, כמו שכתבנו, אולי שאלה לעיל לא היה כמה מיאוס פוסל אלא אם יש מיאוס.)
** לכאו’
, ממה שלא צריך לכסות אותו עוד אחרי שנתגלה אחרי שכסה אותו, רואים שחיוב שלו הוא לכסות, ולא לגרוטם שהוא מכוסה. ותחשב. (ויש לדון, שאולי אם עשה מעשה שהוא תמיד סיבה, אלא שיש מניעה, מהני.) מסתבר, אז, לומר שמה שרוצה ה’ הוא המעשה, ולא התוצאה. אם כן, מעניין שלא חייב לגלות ולכסות אם כסהו הרוח. ותחשב על זה.
** לרב פפא -
יש לדון למה צריך ר"פ, שרק מבאר מה שאמר אחרים. אולי אין הכי נמי, ורק נקט זה ודן עליו כיון שאמר אותו בפירוש. גם יש לומר שלולי זה, נוכל לחלק בין מיני דחייה, כמו שכתבנו לעיל. (יש לדון אם נוכל לפשוט מר"פ, שהיה בתרא.)
שוב ראיתי שבשאלת "מפשט פשיטא" יש שלא גורסים רב פפא (עיין בהגהות מהר"ב רנשבורג).
** מיפשט פשיטא -
נמצא שסובר שלשון "זאת אומרת" יכול להיות משמע ספק. ויש לדון, שיש לומר שר"פ רק אומר שאותו מימרא הולך עם השיטה הזאת, אבל אולי לא הולך עמו כיון שסובר כן תמיד, אלא רק חושש לו. ותחשב.
** תכלת -
נראה שהיה אשפר לומר שהיה מסכם את שני השאלות בתוך שאלה זו, שיכולים לפרש אותו כזה וכזה.
** ציצית -
קשה, אז, למה נקט תכלת יותר משאר גוונים.
** היינו -
נמצא שלא מחלק בין לולב לשאר מצוות, נגד מה שצדדנו לעיל. יש לדון אם זה סיבה לומר שאין בו ענין קרבן, שהיה לו לומר שיש לחלק מחמת זה.
** ספוקי -
חושב אני שיש דיבור מן הרב מבריסק שאומר שאין אומרים ספק דאו’ לחומרא ללבוש "תכלת" כיון שאין אומרים כן אלא אם כן יודעים שלבסוף קיים את המצווה. הרי, גמ’ זה יהיה נגד שיטתו. (אולי בזה גופא דן גמ’, שרק מחדשים כן על הצד שספוקי מספקא.) צריך לע’, שאולי רק אומר אותו כשאולי נשאר בחיוב שלו. כאן, בוודאי לא נשאר בחיוב, שאולי אין סיבת החיוב מתחילה ואולי קיים את חיובו.
** מי מאיס כלפי גבוה -
עיין ברש"י לקמן, שנראה שרש"י גורס, “מי מאוס ככלפי גבוה.”
** חלילים -
עיין ברש"י; יש לדון למה נותן את ה" באמצע המילה, ולא מיד לפני האות האחרונה (כמו שעושה בדרך כלל).
** אחרנייתא -
יש לדון אם רצה לומר שכשאמר את כל שאלות הגמ’, לא אמר אותם על מקום שששאל אותם, אלא אמר אותם על זה, כדי לשאול, אגבם, שאלות אחרות, או שרצה לומר שהביא שאלה זו לבית המדרש כדי לשאול אחרת עמו (ואולי זה כעין מש"א גמ’ שהביא סתירה לבה"מ כיון דאיכא ליה למימרא אחריתי).
** חלילים -
יש לדון אם נוכל לדחות שאין החליל עושה את הקול, אלא אויר שו עושה את הקול (אלא שלא היה עושה את הקול בלי החליל). תחשב על זה.
** ספל -
איני יודע למה זה יוכח לנו, שאולי יותר מסתבר שיעבוד למעיין משיעבוד ספל. כמו כן, יש יותר בבואה בספל (כיון שהמים לא הולכים) משיש במעיין (כיון שהמים הולכים).
** לדברונא -
לכאו’, רצה לומר שמכוון לעבוד לכל הנהר. (יש לדון אם בדעתו לעבוד לכל המים שבנהר או לעבוד את הנהר.) צריך ביאור למה לא רק אמר כן (שרצה לעבוד את הנהר), ולמה אומר שמכוון להילוך של הנהר.
** של רבים -
יש לדון אם זה מפני שיש בעלים אחרים או מפני שהבעל הוא "רבים,” והוא אינו רבים, אלא הוא אחד מן הרבים. יהיה נפקא מינא באם יכול אדם לאסור את של שותפים, אם הוא אחד מן השותפים (אלא שאולי אף שם הבעל הוא "שותפים,” ולא כל יחיד). עיין לעיל, שדנינו בכעין זה גבי נחש הנחושת.
** אסור לבנותו -
עיין ברש"י שכ’ שזה כשעובדים את הבית. אז, הבעיה הוא שעושה עבודה זרה. אבל, אם רק היה עבודה זרה בבית, משמע שאין איסור. קצת קשה למה לא אוסרים כיון שהוא מהנה לעבודה זרה. (עיין בגמ’ לעיל (פ"ק) שדן אם מותר להנות לעבודה זרה.
ועיין ברש"י בשבת שלא משמע כן, אלא כ’ שהוא סמוך לבית ע"ז, ושהבעיה הוא שמהנה לעבודה זרה.
** ארבע אמות -
לכאו’, רצה לומר שבאותו הרחק, לא נניח שיעבדו לו עוד, ולא נחשב שהוא בונה עבודה זרה להם. ותחשב.
* מז:
** אבניו -
לפי רש"י כאן, נמצא שמדברים בטומאת ע"ז. לפי רש"י בשבת, צריך לומר או שמדברים בע"ז, ולא בציור של תחילת המשנה או שמדברים בבית של עבודה זרה, ושאף בו יש מחלקת. עיין בגמ’ שם (בפרק ר"ע), שלא משמע כן.
** שרץ… -
קשה, שאף תקרובת ע"ז מטמא כמת. אולי זה לא הולך כרבי יהודה בן בתירה, אלא סובר שתק’ ע"ז לא מטמא כמת. גם אפשר להחמיר יותר בתק’ ע"ז מבעבודה זרה עצמו. הרי, מעשה של הקרבה הוא, לכאו’, נעשה יותר לתקרובת משנעשה לעבודה זרה (שנעשה לצורכו, אבל כיון שבאמת לא נהנה ממנו, קשה לומר שנעשה לו. כמו שכתבנו בכמה מקומות כשאומרים שמעשה קרה לדבר, אומרים שאותו דבר יש בו שינוי חשוב (יכול להיות חשוב מפני רצונו או מפני דבר אחר) מחמת המעשה.)
** שלשה בתים -
ההמשך הוא שדן במי שגר קרוב לבית ע"ז, ועכשיו דן בבית ע"ז. היה נראה לומר שמזכיר שלשתם לומר שלכולם (עד שהוציא את הע"ז) יש להם דין הנזכר במשנה לעיל. וע’ ברש"י שכ’, “לענין ביטול….” מעניין שלא פי’ שלש שלש בדין שלפני זה. ויש לדון, שאולי לענין דין שלפני זה, אין חילוק ביניהם, ולא היה מזכיר אותם לשלש. ותחשב על זה. (אולי זה הוכיח לרש"י שלא לפ’ כן או אולי מודה רש"י שכן כוונת המשנה, ורק בא לפרש כוונת המשנה כשאומר שהם שלש, דהיינו שהם שונים זה מזה.) מועיין בגמ’, שלפי רב, לכאו’ מוכח כרש"י. (יש לדחות שרצה לומר שהם חלוקים, כיון שהם חלוקים לאותו דין, אף שלא דנים עכשיו באותו הדין.)
** צניעותא -
לכאו’, זה מוכיח לנו שצניעות מורה שגם צריכים צניעות מן גויים. ויש לדון, שאולי יש יבנ"י, כמו שנראה מתוס’ ד"ה אבניו ועציו.
** צניעותא -
יש לדון למה לא פותח אותו לגויים לפנות שם. אולי אף גויים צריכים (או רוצים) צניעות. גם אפשר שלא יבואו לפנות באמצע אדמה של אחר. גם אפשר שלא רוצה שיכנסו לתוך קרקע שלו.
** רווחי -
צריך ביאור קצת: יותר טוב או יותר רע להם להיות שם כותל. אם יותר טוב הוא, לא יבנה, ואם יותר רע הוא, יבנה. אולי מסופקים. יותר משמע מזה שאסור להנות, אף אם בזה גם כן מזיק. אז, אף שבין כל הדברים יהיה יותר טוב להם שיהיה כותל או שלא יהיה שם כותל, זה וזה ייאסרו. גם אשפר שגמ’ מקשה ששניהם שווים, ששניהם נותנים הנאה (ואין סיבה לחשוב שזה יותר טוב מזה). אז, שניהם יהיו מותרים, שלא מוסיף טובה. יש לדון בזה, שהרי בנו את הכותל פעם ראשונה, ואז כנראה רצו את הכותל. יש לדון בזה; יכול להיות שהיה כותל מלפני כן, ולא רצו לסתור אותו (שלא קל לסתור כותל). ותחשב.
יש להוסיף שאם הבעיה הוא שכיון שמהנה לעבודה זרה גורם לאחרים לעבוד, אפשר לומר שעכשיו אין כותל. כל מה שיעשה- בנין או הנחה כמו שהוא יגרום לאחרים לעבוד. ויש לדון בזה, שהנחה כמו שהוא לא גורם לשום דבר, אלא נמשך כמו שהוא. ותחשב. (כמו כן, לא חייב לסתור את הכותל מתחילה.)
** ואף על פי -
קסבר- יש להעיר שיכול להיות איזה תנא שנרצה, שלא פי’ אם הוא של ישראל או של גוי. (אפשר לומר שמה שלא הזכיר בו ביטול משמע ששל ישראל הוא. אבל, רש"י לא פי’ כן על המשנה.) יש להעיר שרש"י על המשנה משמע שיכול להיות זה או זה. זה רק מפני שיכול להיות כאיזה תנא מן התנאים, אבל יוצא שלפי רב, לכל תנא רק יכול להיות אחד מהם.
** יש לדון
למה עבודה זרה ייאסר מיד, אם הוא מפני שעומד לעבודה או מפני שמעשה של עשייתו לעבודה הוא גופא עבודה. לא נראה כצד ראשון, שהרי לא צריך להיות שמי שעשה אותו מאמין בו בכלל. יש לדון, שאולי עדיין אותו מעשה אוסר, אף שאינו כעבודה, אלא הוא דבר אחר (הוא עשיית עבודה זרה). ותחשב. כמובן, זה קצת תלוי באיזה מין מעשה צריכים; עיין לעיל, שדנינו בזה.
** והוא שסייד -
יש לדון מה מתיר, אם מתיר את הסיד עצמו או מתיר הבית. לפי צד ראשון, יש לדון למה יהיה מותר. אולי צריך להיות שבטל לבית, אבל רק עד כדי להתיר אותו, ולא עד כדי שנוכל לומר שהוא שינה את הבית ואסר אותו. צריך ביאור.
** ותיתסר כולה -
יש להעיר שאפשר לומר שאם עשה כן בתוך גופו, אז, הגרו"ב הוא מה שצייר בו. אז, אף אם נוטל יותר, הרי הוא נשאר שם. יש לדון, שאולי צריך למלאות אותו; לא קל לעשות כן באבן. אז, יותר נראה שנוטל יותר מן האבן, עד שאינו רואה צורה. ותחשב על מהש כתבנו; כל ענין זה (מה נחשב הצורה אז) הוא קצת מבלבל. ותחשב.
כמו כן, אולי מה שרושם בו הוא מה שלמטה (מה שלאחורי) הגרו"ב. אז, אולי צריך לקלף אף את זה.
* מח.
** מה שהחליף -
צריך ביאור למה ייאסר, שהרי זה וזה גורם בו (או בטל לאילן עצמו), כמו גבי ילדה שסבכה בזקנה. אולי אין ביטול בע"ז (כמו שמשמע מגמ’ בזבחים). צריך לע’ בזה. גם אפשר שאוסר את כל האילן, אבל רק כל זמן שההוספה נמצתא שם.
** איזה... ר"ש -
לשון המשנה שמובא בגמרא הוא קצת מבולבל. לכאו', מה שרצה לומר הוא, "איזהו אשרה שנחלקו בה רבי שמעון וחכמים כל שיש תחתיה, שרבי שמעון אומר שאשרה הוא רק כל שעובדים," שלשון גמ' כמו שהוא משמע שחולקים רבי שמעון ורבנן במה חולקים רבי שמעון ורבנן.
יש להעיר שבכל כעין זה, יש לדון אם גמ' משנה את הלשון או לא. אם הלשון שנקט הגמרא גופא אינו דווקא, נראה שיותר מסתבר לומר שאינו משנה את הלשון, שאם היה משנה את הלשון, היה לו לומר את הלשון הנכון.
ויש להעיר שבין ללשון שאומר גמ' ובין ללשון שאומר משנה, מוזר שידון במה שחולקים קודם שמזכיר שחולקים.
יש לדון שגמ' מוסיף לשון כזה, אבל לא פשוט שמוסיף אותו בגירסת המשנה. ותחשב.
** כל שעובדים -
קצת מוזר שאומר, "כל שעובדים," שמשמע שבא לרבות; אבל, לכאו', הוא בא למעט מה שלא עובדים (אלא עובדים תחתיו). אז, היה לו לומר,  "רק מה שעובדים." נראה שצריך לומר לשון זה כדי לרבות שני מיני אשרה הנזכרים לעיל. (ויש להעיר שאז לא נודע כבר, "שתים לדברי הכל...."
** אפילו אמרי -
לשון כזה משמע שהם תקרובת, ולא עבודה זרה עצמו. אז, נראה שיש לדון מה כוונת שמואל, אם בא לרבות כשרק אמר שהם תקרובת, או שיש עמו סימן אחר (ומסתמא, אז, הסימן האחר הוא של רב).
* מח:
** אי אפשר דליכא -
אבל אם היה אפשר, לא היה נטמא מספק, כיון שברשות הרבים הוא, וכיון שטומאה דרבנן הוא, וספק דרבנן לקולא. (ויש לדון מה היה קורה אילו היה רוב לטמא אותו.)
** מישרא שרי -
היה אפשר לדון למה מותר אם אין דרך אחרת, אם הוא מפני שהוא יותר צריך לו (רבנן לא גרמו שלא ילך שם ע"י טומאה כיון שצריך לו) או מפני שאז הוא יותר של רבים (ויותר קשה לשנות אותו בטומאה). היה אפשר לומר שמה שלא צריך לרוץ משמע כצד שני, שלראשון, לא צריך לו, שיכול לרוץ. נראה שקל לדחות שאין בעיה בהשארתו שם, אלא בהליכתו לשם, שבזה נטמא. אז, אין סיבה לרוץ. ויש לדון; עיין לקמן, בע"ה. ויש להעיר שלפי שני, לא צריך שאין דרך עצמו לאותו הולך, אלא שאין דרך אחר לרבים. אז, אם, לדוגמא, יש שלש עיירות- יש צפת, ויש טבריה, ויש ירושלים, וכדי ללכת מטבריה לירושלים, צריך לעבור שם, אף אם לא הולך לירושלים, אלא לצפת, יהיה מותר לו לעבור שם. ותחשב.
** ועבר תחתיה -
דרבנן- נמצא שרש"י אומר שהטומאה דרבנן. יש לדון למה לא אומרים שהוא מדאו'; באמת, לא קל לדעת מתי דינים הנלמדים מנ"ך הם מגאו', ואומרים שהקרא רק עושה גילוי לדין דאו', ומתי הם מדברי קבלה, ומתי הם מדרבנן. ותחשב.
ויש לדון למה רבנן גזרו עליהם. נראה שני מהלכים. אולי רצו שבני אדם לא יבואו קרוב לתקרובות עבודה זרה, שמא יהנה מהם או שמא הוא יביא. גם אפשר שרצו שעבודה זרה ותקרובת שלה יהיה מאוס בעיני בני אדם.
** חשוב -
יש לדון מה לנו במריצה, ולמה זה יותר טוב לאדם חשוב. צד ראשון הוא שאז אינו שם לזמן ארוך, ולא מצוי שיראו אותו. אז, נמצא שאינו יותר טוב ללכת לשם בריצה, אלא הכל בא מחשש ראיית בני אדם. גם אפשר שיש מעלה בריצה. תלוי במה שדנינו לעיל- למה גזרו טומאה- אבל אפשר לומר שרע להיות קרוב לעבודה זרה ותקרובות שלה, שמא יהנה מהם, או שמא הוא ירצה להביא. אז, יותר טוב לרוץ מללכת. (אז, קושיית דמרא הוא רק שאין צורך ואין חיוב לרוץ, אף שעדיין יש מעלה.)
** מכלל -
נמצא שפשוט לו הדין. אז, קצת קשה איך יאמר לקמן שזהו החידוש של המשנה. אפשר לומר שאין המקשה הגמ'. אלא, היה דיון בזה בבית מדרש, ויש שני לשונות איך דנו. אבל, לא פשוט לגמ' דין זה; רק היה פשוט למקשה. אבל, אז יוצא דרך אחר במשנה (אלא שכולי עלמא מודו שבאותו בית מדרש שאנו סומכים עליו לא אמרו כן). ותחשב. יותר נראה לומר שאף שלבני הגמרא היה פשוט, עדיין יהיה במשנה. נמצא שמשנה מחדש מה שהיה נודע לתל"ח, אבל לא לשאר עמי הארץ. זה מסתבר מאד. (יש להוסיף שאולי לא פשוט לבני הגמרא מסברה, אלא אולי מבריי' אחרת.)
** צל -
עיין בביאור רש"י. לכאו', כוונתו לומר שבבקר ובערב, רואים שני צילות בתוך צל. אחד נמשך כגובה הדבר, והוא עמוק, ואחד נמשך יותר, והוא דק. אין זה נכון בכלל במציאות. נראה שאולי רצה לומר שבאותם זמנים ביום שהצל הוא יותר ארוך, הצל הוא גם יותר דק. יש לדון אם שניהם ממש תלויים זה בזה או במקרה קרים ביחד; אולי תלוי ברפרקשי"ן של האויר כשהוא בצד העולם, שהוא שונה ממה שהוא כשהוא למעלה באמצע הרקיע. ותחשב על זה.
* מח:
** בימות הגשמים -
יש לדון אם הרע של הצל הוא שמונע את החמה או את הגשם. (אולי הוא שניהם.)
** מה שמשביח -
יש לחלק, שכאן (לא יודע המציאות) אפשר שמחת הטוב והרע, יש אותו דבר. שם, יש טוב אחר (אבל, בין הכל, יש אותו טוב). ותו"ת.
** מפני שהוא פרי -
איני מבין למה זה אסור, שלא נהנה ממנו, שהרי כל הנאה שיבוא ממנו בא ממנו וממקום אחר. יותר מזה, מוכרח שאין זה נחשב הנאה ממנו, שאם היה נחשב הנאה ממנו, אף מה שנגרם בזה וזה ייאסר, כדי שלא יהנה ממנו (רצה לומר, אם לא כן, נמצא שזריעתו מהנה אותו). ויש לדון, שיש לומר שמדברים בציור שהוא לא זרע אותו. אבל, אולי אם הוא זרע אותו, ייאסר.
** בעלים -
יש להעיר ששם יש שני דברים- העלים והצל- וזה טוב וזה רע. אינו כן בעור, ששם נוגע לשני דברים שונים, אבל בא מדבר אחד. ותחשב.
** שאר איסורים -
זה טוב לרש"י שסובר, לכאו', שזה וזה גורם הוא מדין ביטול. (רש"י כאן כ' שדין של ילדה שסבכה בזקנה הוא מדין זה וזה גורם. מגמ' בסוטה משמע שהוא מחמת ביטול. ר"ן באר שרש"י סובר שזה וזה גורם הוא מחמת ביטול. קצת צריך ביאור, שאין בו רוב, ויהיה מחצה ומחצה.) הרי, מצאנו חילוק כזה בין עבודה זרה לשאר איסורים בביטול (בזבחים).
יש להעיר שרש"י קצת סותר את עצמו, שבסוטה משמע שהוא ביטול ממש. נראה לבאר, אולי, שרש"י כאן הולך כתי' ראשון של הגמ', והוא שרבי יוסי מחלק בין עבודה זרה לשאר איסורים. אבל, אולי למסקנא של הגמ' אינו כן (שלא מצאנו מי שמחלק). אולי רש"י בסוטה מבאר לפי המסקנא של הגמ' כאן. ותחשב.
** דרבנן אדרבנן -
אין לומר שרבנן רק דוחים את דברי רבי יוסי לשיטתו של רבי יוסי, שרבנן מתחילים ואומרים שצריך לזרוק אותו לים המלח.
** בנביה -
יש להעיר שלא רק דברים שונים מזיקים ומהנים, אלא לכאו' עושים כן בזמנים שונים. כשיש צל, אין נבייה, וכשיש נבייה, אין צל (שהנבייה בא מן העלים, שהם הצל). ויש לדון, שאולי לפעמים יש מקצת עלים. כמו כן, יש קצת צל שבא מן האילן עצמו.
** רבנן -
צריך ביאור למה פשוט לגמרא שלפי רבנן העלים אסורים. הייתי אומר שיש רק עבודה זרה אחת, והוא האילן. אף שלא נתבטל באיבוד העלים, אולי העלים אינם עוד חלק מן העבודה זרה. ויש לדון, שאולי לא מדברים על הנאה שבאה מן העלים, אלא הנאה שבא מן האילן, שנותן את העלים. (בכל הנאה, צריכים לפרש מהו ההנאה, ומה רק נחשב מכשיר להנאה.) זה גם יבאר דברים אחרים שדנינו בהם לעיל. (ודע שיש לדון מהו ה"אילן" שנותן אתהעלים, אם הוא העלים כשהם מחוברים (והוא שהיותם שם טוב, שזה גורם שירדו) או הוא האילן, שמה שמוסר את העלים לרוח גורם לו הנאה. ותחשב.
** רשי סובר
, כמו שכתבנו, שזה וזה גורם הוא מדין ביטול. קשה איך נאמר כן, שאינו רוב. נראה שאולי אותו גורם של היתר מצרף עם ה'- שהוא הגורם לכל דבר- ואז יש רוב. במילים אחרים, כל דבר הוא היתר ואיסור גורם, וזה לא מתיר, שצריך רוב כדי להתיר. דבר רק מותר אם הוא היתר והיתר ואיסור גורם. תמיד יש סיבה שהוא של היתר, כיון שתמיד יש ה'.
** דרבנן -
אם הייתי למדן, הייתי דן בכמה דברים כאן. ראשון, הייתי דן אם עלים נחשבים עבודה זרה או שהאילן נחשב עבודה זרה, והם נחשבים חלק מן האילן. עוד הייתי דן למה עלים אוסרים, אם נאמר שהם חלק מן האילן, אם נאמר שהם חלק מן האילן ואז אילן מהנה או שהם חלק מן האילן ואז הם עבודה זרה, והם מהנים. ותחשב על כל זה. גם יש לדון אם עלים נחשבים דבר שיכולים לבוא על ידי אדם, שרק בא בגרמא (על ידי זורע) על ידי אדם. ותחשב.
** מודה רבי יוסי -
לשון זה מעניין, שלא מצאנו חולק.
** מודה רבי -
יש להעיר שהיה אשפר לחלק בין ערלה לאיסורי הנאה. היה אפשר לומר שכיון שצריכים לו, נמצא שהוא מהנה. אז, אסור להנות ממנו. אבל, לערלה צריכים יותר מזה, שאין האילן אסור בהנאה. צריך שהוא נחשב פרי של האילן. כיון שזה רק אחד מן הגורמים, אולי לא נחשב כן. ותחשב.
** שני ליה -
נראה שאולי המקור לחלק ייהה מ"שקץ תשקצנו" שלעיל אמר שהוא (אולי) מקור שלא ללכת עם כללים רגילים.
** מאי לאו -
רש"י באר שההיתר גבי פרה הוא מה שאכל לפני זה (ולכאו', גם אחר זה). קצת קשה למה לא אומרים שהוא מה שהוא גרם לעצמו, שהרי הוא אכל, שהוא עשה אותו מעשה. ותחשב על זה. עיין בתוס', שכ' שצריך להיות גורם בדרך דומה.
** אחר אחרון -
אף אם לא היה הטעם כאביי, היה מספיק, שרק צריכים למצוא תנא שמיקל בזה וזה גורם.
** הלכה כרבי יוסי -
נמצא שמניחים שכיוון לשיטה האמיתית של רבי יוסי, ולא למה שאומר במשנה (מה שסובר לפי שיטת רבנן).
** בזבל -
עיין בציור שנותן רש"י. גם נמצא אם אדם עבד את הזבל, אבל לא מסתבר לרש"י שאדם יעבוד לו. ויש לדון, שלא כל כך מסתבר שאדם יקריב אותו לפני עבודה זרה. יש לדון, שמצאנו פעור. יותר מזה, אולי הקרבה שלו הוא לזבל שדה. אז, מובן למה זבל יהיה התקרובת. ותחשב.
* מט:
** נטל ממנה -
קשה  למה אסור, שיש בזה ביטול ע"ז. אולי מדברים בשל ישראל. גם יש לומר שאף זה דרך גדול שלו, שדרך גידול שלו הוא שדברים נופפלים ממנו. צריך להגדיר. אולי, אף אם אינו ממש דרך גידול שלו, רגיל הוא, וטוב לו, שזה מזמר אותו. ותחשב.
** חבית -
אם לא אומר כן לענין חבית, נמצא שפוסק שזה וזה גורם אסור. יש לדון אם זה רק לענין עבודה זרה או לכל דבר (כיון שלא מצאנו, למס', תנא שמחלק).
** שלא לצרכה -
משמע שאף לא צריך כוונה לבטל אותו. אם עדיין מחשב אותו לאלהות, אבל רוצה, לאיזה סיבה, לשפות אותו, נמצא שביטל אותו. יש לדון למה זה יהיה. לכאו', אפשר שסובר שאין הע"ז מקפיד על זה (יש לדון, שאולי אין זה מסתבר), ולכן, כיון שרוצה לשפות, למה לא ישפה. ותחשב.
ועיין ברשי שקצת משמע שנטל אותו לשרוף. אולי אף אם לא מוכרח שלא ירשה ע"ז שיטול חלק ממנו, אולי עדיין מוכרח שלא ירשה לשרוף חלק ממנו.
** לצרכה -
רש"י באר צורך אחר, אבל יכול להיות לכל דבר שיביא נחת רוח לע"ז. לכאו', אם חושב שע"ז רוצה שישפה אותו, יהיה אסור.
** מה ששייך
להרבה דיונים שלנו הוא מה שיש לדון אם ענין ביטול הוא שמגלה גוי שאינו אלוה או שמשנה אותו גוי, עד שלא מיוחס לעבדות שלו. ותחשב.
** שפאיה -
יש לדון למה יאסו. אולי הוא מפני שהיו חלק מן העבודה זרה. גם אפשר הם כעין תקרובת של עבודה זרה, שסילוק שלהם עשה הנאה לעבודה זרה. יהיה נפקא מינא- אם יכול לבטל אותם.
** כל קיסם -
יש לדון מהו ההו"א. אולי הוא שביטול העיקר מהני, ואולי הוא שביטול קיסם אחד מהני (כיון שהו"א שכולם שווים).
** שברי שברים -
יש לדון איפה נמצא שברי שברים דרך גדילתם. אולי נמצא בעלים, שרגיל שאחרי נפילתם הם מתייבשים ונשברים. ויש לדון אם זה כדרך גדילתו, שאף שמסתבר שכן יקרה, אינו מוכרח ולא קורה ממילא. (יש לדון אם נוכל לומר שנפילת עלים קורה ממילא; לכאו', צריך רוח לזה. יש לדון אם זה נכון במציאות. ראיתי באינקרט"א שרק נופל על ידי רוח.)
** עובדים לשברים -
מעניין שמניח שרבנן צריכים לסבור כן, שכאן אינם שברים, שלא נשבר, אלא חתיכות. ותו"ת. אף כשחוזר גמ' מזה לקמן, לא משמע שהוא מפני זה, אלא משמע שהוא מפני שזה עושה שהיינו אורחיה. ותחשב על זה. נראה שהביאור הוא שהעבודה זרה רוצה שיהיה בחתיכה אחת כמו שרוצה שיהיה כולו במקום אחד. אז, אין לחלק. (קצת צריך ביאור למה לא אומרים שעבודה זרה רוצה שלא יקרה אורחיה. ויש לדון שאין לנו שום הוכחה על מה שע"ז רוצה, אלא שלא מסתבר שרוצה להיות שבור. תחשב למה מניחים כן, אבל מסתבר לי להניח כן. אז, אומר גמ' שאם אורחיה להיות ככה, אין להניח שלא רוצה כן ע"ז.
** דאיכא למימר -
הכוונה הוא כך (כן מורה הלשון והסברה): תמיד נניח שבא מן הע"ז. הרי, רוב האבנים שבאותו מקום שם הם (יש לדון בזה), והוא גם הכי קרוב (גם בזה יש לדון). אף בלי זה, על כל פנים יהיה כספק (גם זה לא מוכרח, שאולי יש רוב נגד זה), וספק דאו' לחומרא. אז, צריכים הוכחה כדי להתיר. גמ' מפרש שאם נראים עמו, אין הוכחה שלא בא ממנו. אבל, אם לא נראים עמו, יש הוכחה שלא בא ממנו. אילו היה בא ממנו, היה יותר קרוב. (צריך לומר שלא חושבים שאדם הוציא אותו. אולי זה לא מסתבר או לא מסתבר שזה קרה בלי ביטול (שאם אדם הוציא אותם, מסתבר שבטל את העבודה זרה.)
** ואפילו למ"ד -
אין צורך לזה לביאור המשנה, אבל לא רוצה שהמשנה יהיה מוכיח שעובדים לשברים.
* נ.
** מרוחקות -
עיין בב"ח. לשון "כלומר" כאן קצת מעניין, שרש"י נותן שיעור, ולא נותן מילים אחרים למה שאמר גמ'.
** בצד ארבע -
נראה מרש"י שעכשיו סובר גמ' ש"נראים עמו" רצה לומר שהוא בתוך אמה וחצי אמה. (אגב, צריך ביאור איך נותן רש"י שיעור כזה. נראה שהוא תלוי בגודל האבנים וגובה האבנים.) רבי ישמעאל בא לחדש שלפעמים, אף שלא נראה עמו, אסור. (יש לדון למה לא אומרים רבנן, "שלא נראים עמו...."
אפשר לפרש (ואולי רש"י סובר כן) שרבנן באים לאסור מה שנראה שנפל ממנו, אף שוהא קצת רחוק. עדיין, יודה לזה רבי ישמעאל, לכאו'.
** בצד ארבע -
רש"י פי' שהוא תוך ארבע אמות. אולי עכשיו משנה אותו הגמ', אבל מסתבר לרש"י שלא משנה אותו כל כך. גם אפשר שהוא בצד הפנימי של ארבע אמות.
** רבנן -
מלשון גמ' משמע שחולקים אם עושים מרק' קטן בצד גדול. אז, נמצא שחולקים גם אם נמצא כעין מקר' קטן קרוב לגדול. אבל, שם נראה שרבנן יאסרו כיון שיניחו שזה מרקוליס.
יש להעיר שיש לדון אם, לפי ר"י, הם ע"ז אחד או שני ע"ז. אולי יהיה נפקא מינא לענין ביטול.
** עושים -
מחודש קצת שנניח שזה מרקוליס קטן, שלא נראה שיש הרבה סימנים מוכיחים כאן. (יש להעיר שאולי אף שני אבנים יכולים להיות מרק' קטן (שאף עיקר מרקוליס רק יש לו שנים על הארץ). אבל, אולי אין הוכחה שזהו מרק', שלא מוזר למצוא שני אבנים, זה בצד זה. לכן, לא אסור. (ואם תאמר יהיה ספק דאו'. ויש לומר שאין התעוררות ספק. יש לדון, שהרי הוא קרוב למרק'. גם אפשר שיש חזקת היתר, שלא נברא כחלק מן עבודה זרה.)
** מרקוליס -
אולי סטונהנ"ג היה שייך למרקוליס.
** מרקוליס -
ראיתי שבסנסינו כתבו שהוא מורקיור"י, שהיה אליל שהל הרומיים (היה כמו הרמי"ז של היוונים). בדקתי באינקרט"א ובבריטאניק"א ובכתבי פנגווי"ן מרומי, ולא מצאתי שום רמז לאבנים למרקיור"י.
** בעיקר מרקוליס -
היה אפשר לתרץ שזה רק שיטת רבנן, אבל רבי ישמעאל סובר שגם יכול להיות שלש אבנים, זה בצד זה.
** אפילו בצורתא -
אפשר לפרש שהיה תמיד לומד, ולא היה מסתכל (שאולי זה לשון של ראיה חזקה) בשום דבר, ואף לא בזוזים (שהיו דברים נצרכים).
** אין לה בטילה -
יש לדון מהו הצד שיש לו ביטול (איך יבטל אותו), אם הוא על ידי ביטול התקרובת או על ידי ביטול הע"ז.
** בי ינאי -
קצת צריך ביאור למה נותן כל הקדמה זו.
** זבחי מתים -
אם כן, לכאו', דין זה דרבנן (שדורשים טומאה מן הקרא מדרבנן). ויש לדון, שאולי אין כל הדרשות שווים.
** טירחא שרי -
סבר המקשן, לכאו', אם כך הקשה, שתמיד יש סיבת איסור, אלא שכיון שיש איבוד בזה, הותר. אז, למה לי לחלק בין שני האיסורים, ששניהם הם לאווים. אם מתירים זה מחמת ההפסד, גם נתיר את זה.
** שעובדים אותה במקל -
נמצא שאף העבודות שחייבים עליהם אף כשלא עבודתם צריך להיות בחפץ של עבודתם. (יש לדון אם חייב עדיין בבהמה, כעין פנים.)
** משתברת -
הלשון שממע שהקרק' של זריקת משקין שצריכים הוא שמקצתו נשאר על הכותל ומקצתו נופל. אבל, הקרק' החשוב בזה, משמע, הוא שנתחלק, ולא מה שנשאר במקום שזרק. אז, לכאו' אם זרק מקל, והמקל נשבר (אולי צריכים גם מה שהיה מוכרח לשבור בכעין זה), היה חייב. ויש לדון, שאולי הלשון אינו כל כך דווקא.
** דרב גידל -
נראה שיש שני דרכים לקרוא לגמרא זה:
1. מאי קשיא ליה- דרב גידל?! הרי, בעינן...
2. מאי קשיא ליה, שהרי הא דרב גידל צריך...
* Footnotes
[fn:1] צד זה מחודש. לכאו', זה אומר שאין טוב במה שעשה חוץ ממה שעשה גורם למצווה אחרת. נמצא שטוב של המצווה לא בא כשעשה אותה שלא לשמה. (לכאו', יש מצוות שלא מסתבר לומר כן.) הדרך לדחות הוא לומר שאין אותו טוב גורם שכר או מיוחס למי שעושה אותו שלא לשמה. אבל, מה שגורם שיעשה מצווה הוא מיוחס (והוא גורם שכר) למי שעושה אותו שלא לשמה. ותחשב.
[fn:2] זה מחודש. מסתמא, היו שהתגיירו, ומי יאמר שאינו מחמת זה. יותר מזה, אף אם בפועל נמצא שלא גרם אותו טוב, הרי עשה דברד עם סיבה לאותו טוב. צריך לומר שזה לא מספיק.
[fn:3] שוב הבנתי שנקודה זו נכונה אף בלי זה, שיכול לומר שממה שבטלו תורה בזה, צריך לומר שלא קפדו עליו, אף אם לא נאמר שטענת ה' מתחילה היתה על בית המקדש. ותחשב על זה. אבל, עדיין לפשט זה יש לומר דבר אחר שהוא יותר קל, והוא שיש לומר שחשבו שאף שלא הועיל לבני רומי, זה היה מפני שהטענה מתחילה היתה יותר גדולה, ולכן קצת ששבו קצת שעשו מצוות לא עזר להם. ותחשב.
[fn:4] אולי ה' התיר אותם מצוה ומצוה, ואולי ה' התיר אותם אומה ואומה.
[fn:5] נראה שאולי יותר מסתבר לומר שהמחמיר ברור בדבריו, ואז מסתבר לפסוק כמותו. כמו שאומר גמ' בכתובות (ו) שאין אדם מיקל אלא אם כן ברור לו, בדרבנן נאמר להיפך, כיון שספק בדין הוא לקולא. אז, יש סיבה לחשוב שמי שמחמיר, אף שספק דרבנן לקולא, הוא צודק. (יש לדון לזה, שלא כל פעם שאמר אדם שלא יודע ההלכה נחשב ספק שבו נוכל להקל בדין דרבנן.) ואם תאמר אם כן נקל בדין דאו'. צריך לומר שאף שיש קצת הוכחה להקל, לא מספיק להקל בדין דאו'.
[fn:6] צד שני הוא כעין דיון בעבודה זרה לאהבה וליראה.
[fn:7] גם היה אפשר לומר שבמקומות שונים יש שמות שונים. בא"י, "רבי" היה שם של ת"ח, ואז זה היה סמיכה. בבבל, אולי "רב" היה השם של ת"ח, ולכן ככה סמכו שם. ותחשב.
[fn:8] לא כל כך משמע שהיה ידוע לבני אדם, כיון שהיה צריך לשלוח לרבי בסתר. יש לדון, שאולי עשה כן כדי שרבי יכיר לשלוח לו בסתר. לא נראה כן, שלא שלח לו בסתר לעיל. (צריך ביאור לךמה לא. נראה שלא הכיר לעשות כן עד שרבי עשה כן לו.) נראה שידע שבני אדם יכירו אם לא הורג אותה.
[fn:9] ראיתי בבריטאניק"א שכתב:“The finest British Topaz is found in the Central Highlands, especially at Ben a Buird, Scot. The famous topaz rock of the Schneckenstein, in Germany, yields pale yellow crystals that were formerly cut for jewelry.Fine topaz occurs at several localities in the Urals and in Siberia, Russia, and beautiful crystals come from Takayama and Tanokamiyama in Japan. Brazil is a famous locality, the well-known sherry-yellow crystals coming from Ouro Preto, Minas Gerais, where they occur in a kaolinitic matrix. In the United States fine topaz has been worked near Pikes Peak, Colo., and in San Diego county, Calif. Common topaz occurs in coarse crystals at many localities. Natural red topaz [is very rare].”אבל, שם גם כותבים דבר מעניין, שמשמע לנו שאין זה טופא"ז. כותבים:"It is believed that the topaz of modern mineralogists was unknown to the ancients and that the stone called topazos was the mineral chrysolite or peridot. The “topaz” in the Old Testament also may have been chrysolite."בביאור דברים אלו כתבו:“Peridot- also called precious olivine gem-quality, transparent green olivine in the forsterite–fayalite series (q.v.). Gem-quality olivine has been valued for centuries; the deposit on Jazīrat Zabarjad (Saint John’s Island), Egypt, in the Red Sea that is mentioned by Pliny in his Natural History (AD 70) still produces fine gems. Very large crystals are found in the Mogok district of Myanmar (Burma); peridots from the United States are seldom larger than two carats. Yellow-green peridot has been called chrysolite (Greek: “golden stone”); this term, used for various unrelated minerals, has become less common for the gemstone. Peridot is generally faceted with a step cut.”גם ראיתי באנצקליפדי"א יודיאק"א, והם כתבו על "פטדא שהוא:"According to  the commentators, a green stone, and generally identified in  the versions as the green-yellow topaz. According to Pliny, however, what was known as the topaz in antiquity was not identical with the modern stone called topaz, but with the modern chrysolite or peridot belonging to the olivine group. This mineral is usually green in color and is used as a gem. The identification of topaz or chrysolite with pitdah is rejected by N. Shalem who proposed plasma, a green variety of cryptocrystalline quartz. Pitdah is also mentioned in Job 28:19 as pitdah of Ethiopia, which is used as a symbol of the value of wisdom. This is apparently a reference to pitdah imported from Ethiopia."עיינתי בזה, ומצאתי אותו בפליני (חלק ו, פרק לב). שם כ':CHAP. 32. (8.)—TOPAZOS: TWO VARIETIES OF IT.Topazos3111 is a stone that is still held in very high estimation for its green tints: indeed, when it was first discovered, it was preferred to every other kind of precious stone. It so happened that some Troglodytic pirates, suffering from tempest and hunger, having landed upon an island off the coast of Arabia known as Cytis,3112 when digging there for roots and grass, discovered this precious stone: such, at least, is the opinion 427expressed by Archelaüs. Juba says that there is an island in the Red Sea called “Topazos,”3113 at a distance of three hundred stadia from the main land; that it is surrounded by fogs, and is often sought by navigators in consequence; and that, owing to this, it received its present name,3114 the word “topazin” meaning “to seek,” in the language of the Troglodytæ. He states also, that Philon, the king’s præfect, was the first to bring these stones from this island; that, on his presenting them to Queen Berenice, the mother of the second Ptolemæus, she was wonderfully pleased with them; and that, at a later period, a statue, four cubits in height, was made of this stone,3115 in honour of Arsinoë, the wife of Ptolemæus Philadelphus, it being consecrated in the temple known as the “Golden Temple.”The most recent writers say that this stone is found also in the vicinity of Alabastrum, a city of Thebais, and they distinguish two varieties of it, the prasoïdes3116 and the chrysopteron;3117 which last is similar to chrysoprasus,3118 all the shades of it tending, more or less, to resemble the colouring principle of the leek. Topazos is the largest of all the precious stones, and is the only one among those of high value that yields to the action of the file, the rest being polished by the aid of stone of Naxos.3119 It admits, too, of being worn by use..”על זה כתב ההערה:“3111Under this name Pliny evidently speaks of the stone known to us as Chrysolite, and possibly of green agate as well. Our Topaz cannot be easily recognized in this Chapter, at all events.3112See B. vi. c. 34.3113See B. vi. c. 34.3114Τοπάζω in Greek, signifies “to conjecture.”3115It was agate, most probably.3116“Leek-green.” Ajasson and Desfontaines think that this must have been either Oriental Chrysolite or Oriental Peridote.3117Some would identify this with Oriental topaz or yellow corundum, a variety of the Sapphire; while others would see in it the genuine Topaz; and others, again, think it synonymous with the Chrysoprase. The name “chrysopteron” means “golden-wing.”3118“Leek-green and gold.” An apple or leek-green Chalcedony, coloured by nickel. See Chapters 20, 34, and 73, of this Book.3119See B. xxxvi. c. 10..”גם, עיין שם (פרק מב), שכ':"CHAP. 42.—CHRYSOLITHOS: SEVEN VARIETIES OF IT.Æthiopia, which produces hyacinthos, produces chrysolithos3174 435also, a transparent stone with a refulgence like that of gold. The stones of India are the most highly esteemed, as also those found among the Tibareni,3175 provided these last are not of a mottled hue. The worst in quality are those of Arabia, the colour of them being turbid and mottled, and their brilliancy interrupted by cloudy spots: even too, when they happen to be limpid, they have all the appearance of being full, as it were, of a peculiar dust. The best stones are those which, when placed by the side of gold, impart to it a sort of whitish hue, and so give it the appearance of silver. When this is the case, they are set in a bezel that is open on either side; but when the stone is of inferior quality, a ground of aurichalcum3176 is placed beneath.”ועל זה כתב ההערה:“Generally supposed to be the Oriental topaz, yellow Sapphire or yellow Corundum. We have already seen, in Chapter 32, that the “Topazos” of the ancients was in all probability the modern Chrysolite.”
