* ח:
** דעתו לוודאי -
למה א"א כמו שאמרנו גבי עצים, שכיון שמוכן לזה, מוכן לזה.
** זיל טרח וכסי -
צריך ביאור מהו תירוץ זה. ואולי רצה לומר שלא היו אומ’ כן ביו"ט בלי צורך שיש צד לגזור. ויש לדון, שאדם עושה כל פרכו בעפר. (טירחא?)
** אסור לכסותו -
זה נגד רמי, ואולי יש לומר שמזה נדייק שספק חיה ובהמה חיה, ואף לענין חלב. וצ"ב למה זה יהא.
- מה איסור יש ואולי הוא טירחא או שמשמשו בלי צורך. ודחוק שיש צורך, שחייב ע"ז.
* ט.
** חלת חוצה -
מניח שאבוה דשמואל קאי בחלה דחו"ל (ששם דר).
** ור"ש אוסרין -
נמצא שרב סובר נגד סתם משנה.
* ט:
** ממאי -
הרי ר"ח ידע כיון שתני לה. י"ל שלא כ’ הבריי’. או שר"י ממש אמרו על ר"ש (הזמנין לא נ’).
* י.
** לית להו ברירה -
אם כן, נאמר שהכל מוכן, שאדם מכוון שרוצה להשתמש עם דבר אם ירצה אז.
* י:
** הואיל ועשויין לדדות -
ק’ למה לא דחה (לשני) ששאני גוזלות שאינן מקושרים.
** בשני כיסים -
הדמיונים מעניינים, שהרי בכיסו, יש סיבה חלוק שאם נטל זה ייטול זה מן הסיבה שיש בגזלות. ותחשב. ואולי הענין הוא שמניחים שמה שקרה לזה קרה לזה.
* יב.
** משום אוכל בשר בחלב -
צריך ביאור למה אין בזה משום הנאה.
* יב:
** הבערה ובשול -
אוי"ל שנקרא המשנה כן שבעיקר נלקה על הני (ודחוק) או שמז’ בישול שאי אין הבערה יהא בישול.
* יג.
** טבלא -
אי"ז ת’ אחר, שאכתי נקשה שתמצא בדגן, ולא קטנית.
* טו:
** שמחת יום טוב מצוה -
יש לציין לגמרא שבת שאומר לשון כזה גבי תפלה, אף שהוא מצווה. אולי הוא מפני שהוא רק מצווה מדבריהם.
** שניהם מקרא אחד -
הוא שני מקראות, אבל רצה לומר מקור שווה.
* טז.
** מצא אחרת -
1. אוכל מה שקנה לכבוד שבת.
2. אוכל כדי שלא ימצא השחתת אוכלים, ואז יוכל לקנות יותר. ותו"ת.
רש"י
* טז:
** למעלה… למטה -
יש לדון מה היה ההוה אמינא.
* כ.
** על תכף -
צריך ביאור איך ידחה ב"ש את הצה"ש.
** עולת תציד מצויין בתמיד
(ואף שאין תמיד צריך סמיכה).
ואולי בזה תלוי מחלקת אם ללמוד מבניא.[fn:1]
* כא:
** הני סופלי -
לא הבנתי, שזה, לכאורה, רק איסור לעשות מלאכה בשבילם, ולא ליתן להם מאכל. ואולי צריך לומר שאוסר אף את זה. ואינו נ’ כן מכמה גמרא דכאן.
* כג.
** מוליד ריחא -
ואם תאמר מה בגחלים. ויש לומר שאין הכי נמי שם יש גם כן בעיה זו, אלא שיש בעיה יותר גדול. עוד יש לומר ששאני שם שגחלים אינם חשובים ואז אין רע כשהם קולטים ריח. ויש לומר כן גם כן באוויר שקלט ריח. ובאוויר גם כן יש לומר שכבר היה אפשר להריחו קצת באוויר קודם כן, ואז נראה רק כמוסיף, ולא מוליד. ותחשב.
עיין ברש"י. ויש לדון.
** רב נחמן לחודיה -
יש לדון אם ממעט אף "רבא.”
** ראב"ע מודה לו -
לכאורה, היה מצי למימר שלולי שיטת רבי אלעזר בן עזריה, היה סתם בתרא נגד רבי שמעון. ואם תאמר הרי סתם שלאחריו כר"י. ויש לומר שכולם חד משנה (שזה המשך שיות רבנן. כ"נ ממה שממשיך לבאר ענין רחים).
* כד.
** מה שנחשב צד:
1. אין לו מקום לילך.
2. עומד להיות נצוד כשיבא אדם.
עיין בתירץ גמרא "לכלובן."
* כו:
** שזה מן המוכן -
וק’, שאכתי פסקם מתירו ומתקנו.
** פשיטא צריכא למימא -
למה צריך שניהם.
* כז.
** בקנסא -
על זה כתבתי אונדרליי"ן. נראה שהוא מעניין, שקורא אותו קנס, אבל גם קצת משמע שהוא מפני שמתשתנים. ותחשב על זה. ועיין בריש בכורות שקורא לשון קנס לדבר שנראה שהוא גזירה.
* כז:
** שיולי קמשייל -
וק’; שלכאורה, סוף דין הוה שעת פסקו, ושעת ההיתר. ועיין רן בראש השנה שכ’ שהא דתחלת דין ביום וסוף דין בלילה הוא שכולו נגרר בתר תחלתו.
** דאמר מודה -
צריך ביאור למה יודה. אולי רצה לומר שנשתנה ממה שהיה שנחשב כנולד. אם כן, יתלה במחלקת בשיטת ר"ש בנולד. ותחשב.
** שפיר -
אם כן, נמצא סת"מ כר"ש. ובאמן, כן נמי למסקנא.
** דלי עיניה -
אולי היה כרבי יוחנן (עיין בסוף בבא קמא). ודע שלא חי אלא מ’ שנה[fn:2], ואז לא היה זקן כל כך.
* כח.
** אפילו לשמרו -
נראה שני ח’:
1. אינו מכוון לשקול.
2. אינו שווה (שמה לו להשוותו). (וי"ל שאי לא משווהו, יגיע לו עכברים.)
** בשר במים -
נראה שצ"ל אומן כדי לדעת רישי"ו בין הוואליו"ם לוויי"ט.
** חושב אני שמצאתי
שמה שאין בכור נמכר באיטליז פירכא. זה ק’, שאינו חומרא, אלא בא ממה שממונו לבעל. ותחשב. ונראה אולי כצד שחומרות באי הם סיבה, ולא סימן . חושב אני שמצאתי תוס’ קידושין (ריש) שנ’ כן. וצריך ביאור.
* כח:
** צריך ביאור
למה מניחים שלעצמו שוחט.
* כט:
** מבי נשא -
מכאן נראה שיכול לפרשו אב או חמיו. ועיין בשבת (פרק ב"מ בדין הרגיל בנר).[fn:3]
** צ"ל שלא
נחשב מרקד מחמת צרור זה שלא נפל.
* לב.
** ואליבא דרבי נחמיה -
ק’, אם כן, נוק’ למשניות כן.
* לב:
** משום כבודו -
למה א"א כת’ קמא (שגזר רק כשיש אהל). וכ"ז צ"ב שלכאורה, חזר בו, הוה ליה לחז’ זה.
* לג.
** אפילו ר"ש -
רצה לומר, שס"ל כאבוה, אלא שמוסיף נקודה. ואפשר שה"לימא" הוא קושיה למה שנה תנאים. ואכתי ק"ק למה לא עשה הראשון ראב"ש. וזה לא כל כך קשה, שיש לומר שנקט רבי שמעון, שהוא עיקר באומר כן. ותו"ת.
* לד.
** שצריך לבדקן -
תחשב, שלכאורה, אין זה שצריך למדק, אלא שיש חשש שיפקא. ותחשב. ועיין ברש"י. ונראה שאינו קשה.
** משום לבון רעפים נגעו בה -
נמצא ש"חייב" על זה, ואינו רק גזירה.
* לה.
** והלא מוחזרים… אלא -
רצה לומר, שבקל יכול לבטל הכנתו.
* לה:
** דאיכא ביטול -
אורחים?
מקיים מצוות עונ"ש. ועיין ברש"י. וצריך ביאור.
** מאן -
יש לדון אם גור’ כן במשנה או שיש ברייתא אחרת האומר לשון זה בבאיי’. זה שייך ל134.[fn:4]
* לו:
** מקדישים -
משמע שערכין מצווה, ולא רק שגורם שיתן ושנתינה מצווה. ותו"ת.
* לז.
** אבל אטלטול לא-
משמע שאותו איסור הוא משום מוקצה (ולא משום טרחא). ועיין שם, שלא נראה כן. ואולי כל טלטול שאינו לצורך הוא מעין מוקצה (שלא הותר לכבוד שבת). ותחשב.
* לז:
** או לרועה ש"מ -
רצה לומר, שיש יכולת ליתן לבנו (ויש לדחות ששני ציורין הם, וציור ד"רועה" הוא בשאין בן.).
* לח.
** אם רק
בחד מקום הניח, נוכל לומר שמתנה הוא, ולא עושה ברירה.
* לח:
** אע"פ שאין להם… -
כתבתי את זה באונדרליי"ן.
* לט.
** דבר שיש -
יש לומר כן אף בגזל, שיכול לשנותו.
** ומותר בשלהבתו -
יש עוד נפקא מינא כמובן, והוא גזל. ואולי אין שלהבת שהוא שווה פרוטה.. ויש לדון.
** שלהות
:
1. לא חשוב.
2. בטל לאוויר.
* Footnotes
[fn:1] איני ידוע מה כתבתי כאן ועל מה קאי. גם איני יודע מהו מילה אחרונה הזאת.
[fn:2] לרש"י בראש השנה (יח), אבל לא לגירסת תוס’ (ולפשט אחר שברשי).
[fn:3] כג:
[fn:4] איני יודע מה זה. ונראה שבשיח שי (גלגל שלישי) כתבתי מניינים על ביצה. שוב ראיתי שכן הוא.
