* י.
** דלמא אתי לאמלוכי -
עיין בפירוש רשי. משמע שחשש זה לא יעשה שאינו מוכן.
** לית להו ברירה -
דלמא- לשיטתו.
** לית -
עוד מעניין, שאי חוזר, נמצא שאינו מוכן.
** אף משיומת -
וב"ה סברי- קשה, שמי יימר שהו"ל שום דעת לפני כן. ויש לדון. ואולי רק דם אי דנים עמידה על פי מה שקורה[fn:1]. ויש לדון, שאם כן, זה נוגע לכמה וכמה דברים.
גם צריך ביאור למה לא מטהרים כלם כיון שמוציא מחד.
* י:
** על רש"י ד"ה לימא מתניתין רבי
, כתבתי אונדרליי"ן. זה אומר לחשוב עליו.
* יב.
** אלא מדלא -
כיון דהותרה- עוד יש לומר שיש יותר מיגו על דבר שיש בו צורך.
* יב:
** גזרה שוה -
ואולי ה"נ כמש"כ במק"א שענין גזרה שוה הוא שיש מושג שוה (מילה עם מושג שוה).
* יד:
** מי איכא מאן דשרי -
יש לומר שיש לו תשמיש, שיכול להשתמש בו על ידי ברור.
* טו:
** רב אשי -
לכבוד- זה מעניין.
* טז.
** צירך להודיע -
אביו ואמו שהוא אוהבם- יש לדון אם הענין הוא שצריך לדעת שיש שאוהבים אותם או שזה אוהב אותם.
** ב"ש היא -
על "לא דחיא סמיכה דידהו" כתבתי אונדרליי"ן.
* טז:
** דאית ביה כזית -
יש לציין לגמרא ב”ב (גבי מתנת שכיב מרע) כעין זה.
* כא.
** כהנים -
לשם גבוה- צריך ביאור, שלכאורה, ענין אכילה הוא שזה שמחת יום טוב, ולכאורה, יהא כן כאן. ואולי רצה לומר שלכן עיקר תכלית ה"ה הקרבתו, ולא אכילתו (שאין שחיטתה יכול להיות כדי שישמח ועוד שאין השחיטה אלא שירצה וזה מעיקר נעשה על ידי הקטרתו).
* כב:
** בזריזין -
ועוד יש לומר שכל כהנים זריזים היו.
* כד.
** חייב -
דרך חלונות- אם כן, נאמר ביבר בלי חלונות.
* כו:
** חכמים -
צריך ביאור למה נניח שחול’.
* כז.
** אנא מסתברא -
משמע ש"הלכה כרב" אינו כן. ותחשב.
** אלא -
כל זה מראה מקום.
** ומינה -
ואין דבריו של אחד במקום שנים- זה לשון מעניין, שעדיין הלכה כיחיד המסתבר. וחושב אני שאומר לשון כמו כן גבי בית הלל ובית שמאי, ושם הוא ממש כסתם משנה.
* כט.
** ואתא רבי יהודה -
משמע שאלו ה"ה שנים דברים חלוקים. וצריך ביאור אי צירך שניהם (משמע מרש"י שצריך).
** מברורי מדות -
קשה, הלא היה מקפיד על ברורי מדות. ואולי מפני מעשה זה בקפיד. עוד יש לומר שצריך להפך בירור ומיצוי, והוא לשיטתם. ודחוק.
** בתוספתא -
זה אונדרליינ"ד. נראה שחשבתי שהוא מראה מקום.
* כט:
** וכן המוליך -
דגנאי י"ט- כתבתי על זה אונדרליי"ן.
* ל.
** נפרוס -
נגזר מחמת סחיטה.
* לה:
** מאן דתני -
ק"ק למה לא פירש שידע ברייתא שתנא כן.
* לז.
** דאית ליה -
לבית הלל- נראה שמפרש את זה מפני שיש צד שמשנה בית שמאי היא. ועוד דכתיב "בנים.”
** משום מקח -
רשות הקדש- קצת משמע כצד שהקדש הרי הוא נתינה, ולא רק שנותן בו קדושה. ויש לדון, שאולי לאחר כן, יוצא מרשותו, וזהו הבעיה.
** אטו טלטול -
לבטל…- למה צריך; הוה גזירה שאין רב צבור. אולי רק מבאר למעשה למ"ל.
- או אם היה שם בתחילת שבת.
* לט.
** רב ששת -
והלך בשליחותו- נמצא מוכח שאין הפקר שהכל שותפין. ועוד נראה כן מדין נדרים. והוה מצי לומר- ואין נראה כן מרש"י- שזהו גופא המחלקת (מהו הפקר).
* Footnotes
[fn:1] ועיין במקום אחר (גיטין?) שהוכחנו שכן סבר רש"י). שוב שמעתי מר"ג שפיץ שכן סבר ברש"י.
