** פרק חמש עשרה נשים ב.
וצרות צרותיהם- הק’ לי אחד שלכאו’, אין הנשים פוטרות צרות צרותיהם, אלא צרות פוטרות צרותיהם. תורץ לי שאה”נ, והדרך לקרא את המשנה הוא, “. . . פוטרות צרותיהם, וצרות, צרותיהם.” (ויש לדון אם נכון הוא, שדלמא נפטרו כיון שמיוחסים לערוה. ויל”ד למה נצטרך לזה, ולמה לא יפטרו מחמת אשת אח. ויש לדון, דאולי ייבום התיר את זה, ונשאר רק איסור צרת ערוה. ותח’.)
צרות- חשבתי על פשט לבאר צרת ערוה. צריך להקדים בכמה הקדמות והנחות:
א. איסור אשת אח אינו מחמת יחסו לה, אלא שיש לאח (אול אב שניהם) זכות לעשות שלא ישא אשתו (שמיוחס לו) את אשת בנו (שגם כן מיוחס לו). מניחין שכן ירצה (מסתמא מפני שיש שום רע בו). (וצ”ל שיש זכות זו לאב אף לאחר מיתתו.)
ב.כשיש  יותר טוב מייבום (קיו”ש), ירצה בו, ואז יותר.
ג.אם היא ערוה לו מטעם אחר, לא יבנה בית טוב. אז, לא רוצה בו אב.
ד. רוצה יותר שלא ישא האסור משישא המותר.
ה. רק יכול להתיר או לאסור כלם.
אז, ממילא, כשחד אשה ערוה, כל צרותיה יאסרו.
** ג:
ליתנינהו- לכאו’, זה גם כן קשה על סתם הגמ’, שלא רוצה למעט (כ”נ. ויש לדחות בקל.) אלא שנים. א”כ, קשה למה לא נ’ שאר במשנה. ואולי לא רצה למעטן מפני שהן פשוט, ולא מפני שסוברין שאין הדין כן.
במשנה תורה- ק”ק מה בין מ”ת ושאר קראי, שאי מוכח או מופנה, לעולם נדרש, ואי לא, אף במ”ת לא נדרש. (לא משמע שחוזר בו גמ’.) אולי רק ר”ל ששם נמצא כן בדר”כ (אז, נצטרך להניח שבמכשף וכדו’ אינו מוכח או מופנה. ולאידך צדדין, צ’ להמיח שהוא מופנה או מוכח, דאל”ה, מהי”ת לתלותו זמ”ת.) . גם י”ל שבייתור, לא נדרש, בדר”כ, סמוכין, אלא דרשה אחרת, אבל במ”ת (וצ”ב למה) דורשין סמוכין.
** ד.
לסקילה- אף שכיון שאינו סובר שיש לדרוש כן, נקט כן לרבותא. (נראה שכוונתי הוא שסבר שאין לדרוש את זה, ואף אם לא היה להחמיר, שלהפך, יותר קל לדרוש להחמיר (ויש לדון, שאולי אינו כן גבי מיתוות, שהוא חומרה שלא להמית אותו, אולי), אלא ר"ל כמה רע הוא אם נטעה לדרוש.)
** ד:
[ותיתי… טעמא]- ועוד שאם כן, נכתב בגד גבי שניהם, ולמה שינה את הלשון.
** ה.
וקסבר האי תנא- והחולק סבר כתדר"י או כצד דמופנה או נגד ר"י.
ללאו שאינו שווה- קצת מעניין מה שנחשב שאינו שווה בכל, שלצד אחר, שכן פסק רמב"ם, בעצם שייך לנשים, אלא שאין זקנם זקן. ואולי כיון שלמעשה אינו גבי כולי עלמא, יותר קל. (וכל זה על לאו סתם שיש בו ג"כ.)
- יש לדון אם ר"ל זקנו אינו שווה (אותו איסור) או שאמירה שלו גבי כהן אינו שווה בכל. ותו"ת. ראשון נ"ל.
שאני כהנים- ואם היה רק זה, הוה אמינא בישראל מיירי.
לא דחי קמ"ל- אין לפ’ שכיון שהח’ תורה להם, צ’ להח’ בעשה נגד לאו, שא"כ יהא כן בכל לאו ועשה לענין כהן (יש לדחות שכן ר"ל גמ’) ועוד שמי יאמר שכן הוא חומרא. אלא הוא שלאו כהן הבאים לשמור ק’ כהונה הם חמירי.
ישנו בשאלה- קשה, אם כן יצטרך לשאול כדי שיקיים שניהם.
שכן ישנו- יש לדון:
1. מגו
2. זה מראה חלשות הלאו.
** ה:
ואכתי- כ’ על זה אונדורליי"ן.
אלא כולה- קשה מה היה אם היה ר"ל שוע טווי. ואולי אם כן, לא היה נקט לשון כזה, אלא לשון יותר טוב (ואולי הוא יותר טוב במה שלא אף משמע זה).
ישנן לפני הדבור- צריך ביאור למעשה למד"א החולק. חושב אני שר’ שטיין דן בזה.
** ו.
האמורה- וצריך לומר שהברייתא אינו נכון.
** ו:
לא משבת- דרשה זו צריך ביאור. עיין ברש"י. ויותר נראה לי שר"ל שסיבת שמירת שבת הוא יראת ה’, ולא רק כדי שיהיה יום של מנוחה. אבל צריך ביאור מהיכי תיתי. ולכאורה, זהו מש"א גמ’ שאם היה לשם עבודת יום שבת, היה צריך יראה ממנו. ודחוק. ותחשב.
ותיהוי נמי רבי יוסי- ועוד שנק ‘ כמו בראש ד..
** ז.
רציחה דוחה אותה- ק"ק שאינו דוחה מה שיוצא עבודה.
** יב.
- תפשוט מדרב יוסף, ואיך ידע ששנה רבי זה, אי לאו שמחז’ גורשה א"א.
- רב יוסף היה אחר רבי יוחנן.
-מסורה.
- לשון (פסולה, ולא מחז"ג).
** יב:
אחת זו ואחת זו- יש לדון אם זה בכל ציור או רק כן (וצב"ל).
** יג.
משום צער לידה חיישינן- ועוד שכיון שיש ראיה ברורה שיש לה סימנים, מוכרח שאם אין נראה צריך לחוש שנשרו.
** יג:
בסוגיה דעשו, יש להעיר מסוגיה ברכות (לכאורה, כוונתי היה לגמ’ גבי ר"ט שקרא ק"ש כב"ש).
פנימית- יש לדון מהי"ת שפנימית בכלל קרא זה.
כל תיבה- כל הוא לאו דווקא.
התם הרואה- לכאורה, הו"ל חזרה.
[ק"ק ל"ל מביא שום מח’. וי"ל שמדייק מלשון "מתירים" שקרה.]
