** פרק חמש עשרה נשים ב.
תוד”ה חמש- ע’ בתירוצו. בפשטות, הוא שאי הוה כתיב, “ח”ע עריות,” לא הוה יודעין למעט הא דרב ורב אסי. ע’ בתי’ שני של תו”י. לכאו’ תי’ שוש לתירוץ תוס’. קשה, שלכאו’ בא להוסיף על תוס’, ולא לכפול את דבריו. אז, חשבתי לומר שתירוץ תוס’ אינה כמה שכתבנו, אלא שסבר שאם הוה כותב “ח”ע עריות” הוה ממעטין הא דרב ור”א ושאר ציורים הנצרכים למעט ממילת “עריות,” ואם כן, ישאר חד מנימא מופני. יותר רצה לכתוב מנין מלכתוב לשון עריות. ודחוק. ותו”ת.
שוב נראה לי תירוץ אחר. יש לחקור מהו הדיוק ממנינא:
א. מדכתב לשון מנין יתירה, צ”ל שמכוון למעט ציור מדין משנתינו.
ב. אי הוה כ’ חד מניינא, הו”א כא’. כיון שכ’ שנים, חד לפני המנין וחד לאחריו, זה סותם את המנין לומר שרק לאלו יש דין זה, ולא לאחרים. ממעט, אז, את הכל, אלא שצ”ל שנים, שנתמעטו דאי לאו הכי, די בחד מיעוט. (יל”ד קצת, אז, בתירוץ רב ר”א.)
אפשר שתוס’ סבר כראישון ותו”י סבר כשני. (וכן משמע מלשונם.)
לכאו’, מוכרחמגמ’ שרב ור”א סברו כראישון, שהרי אינו ממעט כל דבר, דאינו ממעט דיניהן. אז, לא הביא תו”י אלא למעט דרב ודר”א, שזהו עיקר המיעוט (כן משמע מגמ’.) לחול’ על רב ור”א, וכל הצד להביא ממאנת ומח”ג הוא רק כדי לת’ לרב ולר”א; אבל לתו”י, כיון שאינו כרב ור”א ממ”נ, לא רצה להביא אותו מיעוט. (רב ור”א יחלקו לסבור כראישוון רק מפני דחקם.)
** ב:
תו”י אות א- ע’ במה שכתב. בפשטות היה נראה שהא דאינו חוזר בו על מה שהיה מקפיד אי היה יודע שימות הוא שאי היה יודע שלא תגדיל תחתיו, וממה נפשך, לא תלד לו, לא היה מקפיד. אבל בתו”י כ’ שלא יקפיד לזמן מועט. וקשה, שיכול לישא אותה כמו עשר שנים ותשאר קטנה. לאיד”ג, יכול לינשא לה כשהיא גדולה, ולמות מיד. וצ”ע.
