* ב.
** דקא מפקא -
יש לדון מהו יציאתו מן הקדושה:
1. בכור קדוש מרחם. אבל, זה לא נקדש.
2. בכור גורם נתינה לכהן. אבל, זה לא גורם אותו נתינה.
יש להקריב שאם נאמר שהוא שני, אם נקנס אותו, נמצא שאין סיבה לקנס. (עדיין יש לומר שיש סיבה לחייב אותו כדי שיקדש, אבל לשון קנס לא משמע כן כל כך, אלא משמע שהוא כיון שעשה דבר רע. ותחשב. אבל, ע' לקמן בגמ', בקנס שלא יחלף, שאף שם, אם נתחייב, אין סיבה לקנס, וצריך לומר שכוונתו לומר גזירה. ותחשב.)
* ב:
** מרביעים עליה -
לכאו', ממ"נ יאסרו רבנן כאן, שאם אוסרים מחמת שיוליד וולדות, הרי כאן מוליד וולדות לגוי, ואם אוסר מפני שנראה כמוכר לו בהמה, הרי גם כאן נראה כן. אפשר לומר שחשש של חילוף שאומרים רבנן אינו שוווה לחשש חילוף שאומר גמ' בתוך שאלתו, שהראשון הוא שילפו הדינים, והשני הוא שיראו אותו בחצר גוי, ויחשבו שאינה שבורה. ותחשב. גם אפש ר שאין הבעיה שגורם וולדות לגוי, אלא הבעיה הוא שהוא שלו, ויש לו תכלית. ותחשב.
** אבוה דשמואל -
קשה, שלא יהיה אסור להיות שותף עמו, אלא יהיה אסור להשביע אותו. משמע שיש איסור להכניס את עצמו לציור שמצוי שיעבור[fn:1]. (נראה שאולי הוא איסור לפני עוור על עצמו.) גם אפשר שהוא גזי' מדרבנן, שחוששים שיעשה שישבע. אבל, המילים לא משמעים כן. ותחשב. (גם אפשר שסובר שכיון שצריך את הממון, מותר לעשות שישבע. אבל, אסור לעשות שיצטרך את הממון. ותחשב.)
** דעיקר מכירה היא -
רצה לומר, "דעיקר היא מכירה." נתן מילת "היא" אחרי מכירה, ולא לפניו, שכן הוא הדרך בכמה מקומות (כמו שאומרים "אחד הוא אלקינו," שמכוון לומר שאלקינו אחד. ויל"ד.[fn:2])
* ג.
** מסייעיא -
אם הם דווקא, המנין מסייעא לו. אם לא, הסיוע הוא רק לומר שיש קנס שצריך לקנות אותו בחזרה.
* ג:
** רחל שילדה -
יש לדון אם המום הוא מה שהוא משונה משאר מינו או מה שהוא משונה מהוריו. (אולי יהיה נפקא מינא במשונה בן משונה.)
** איש איש -
אפשר שהדרשה הוא מכפל לשון "איש." נראה שמפרשים שאומר, "איש שהוא איש מזרע אהרן." ייתור אומר לנו שביאור "איש מזרע אהרן" הוא "סתם איש מזרע אהרן." ותחשב.
** ה"נ מסתברא -
אז, לא רק אינו פשוט, אלא יש קושיה עליו. ותו"ת.
** בריותא -
יש לדון אם הכוונה הוא שכיון שזהו סיבתו אינו בעיה (ויש לדון למה לא) או שכיון שזהו סיבתו, קל להחזיר אותו לטוב, ולכן אין זה מום. (ויש לדון, שעל כל פנים יהיה מום עובר. אולי זה נחשב בידו. ויש לדון, שאינו בידו לעשות כן מיד.)
** וחזי -
מעניין שחוששים לכך, שהרי לא היה נוהג בו מנהג חולין.
* ד.
** כדריב"ל -
יש לדון מהי"ת שזה אחד מן המקומות. אולי היה קבלה ממשה ככה.
* ו:
** אין נפשה -
נראה שהוא לשון דם, כמו ש"דמו בנפשו," וכמו "נוטל נפש" (עיין בתוס' בתחילת כתובות).
** אילימא... בשר בחלב -
ק"ק ל"ל לומדים מ"ולכן שיניך מחלב." אולי היה מותר לו, כיון שלא היה ניתן התורה כבר. לא נראה כן, שמגמ' משמע שאיסורו יהיה אבר מן החי, והרי אף בני נוח מצווים על עליו.
** הנאה -
קשה, שיש שלש פסוקים, ואחד מהם מיותר.
* ז:
** מנלן -
הפשטות הוא ששואל מהיכי תיתי חשש שהשריץ. יש להעיר שלכאו' מביא ראיה ממשנה למשנה. ראיתי בהגו"צ שבעוז והדר שיש שלא גורסים מילה זו.
** ריעי -
ואם תאמר אם כן למה צריכים שראה שאכל אותו. אולי אין הכי נמי, לא צריך כן, וכשאומר שבלע אותו, כוונתו שיודע בוודאי, וזה דרך אחר לדעת בוודאי. יש לדון, שהיה נראה יותר לומר שמדייק ממה שלא רק אמר שמצא אותו בתוכו. אז, היה לו לדייק גם ממה שלא אומר שמצא אותו בתוך בית הרעי שלו.
** עטלף -
יש רק שלש מיני חיות שהם ככה, והם המונוטרי"מים, שנמצאים רק באסטרלי"א (וטאזמני"א ונ"ו גינ"י, שהם קרובים לשם), והם כוללים הדו"ק ביל"ד פלאטיפו"ס (שלא נודע לחכמי הטבע עד קרוב לזמנינו, ומתחילה חשבו שהוא הוק"ס) ושני מיני האקידני"אים. שניהם יש להם גם חלב (אבל אין להם דדים, אלא יש להם מיל"ק פאט"ש).[fn:3]
אם כן, יש לנו ראיה שתורה ידעה על מינים אלו (ויש לדון אם המילה של התורה מכוון לכך או רק של הגמ').
* ח.
** תאנה -
ע' בב"ב ובכ"מ שתאנות באים בזמנים שונים. ותחשב.
** הואיל ודברה -
יש לדון אם דג נשתנה אחרי שדבר לו ה', או שהיה כן על שם העתיד.
* ח:
** לסנדליה -
כמובן, עיין בגמ' בשבת וביצה גבי סנדל המסומר.
* ט.
** דלא כר"י -
נראה שאולי הענין הוא שלענין בכור בהמה טהורה, התורה אמרה שאם נראה שבאים בזמן שווים, נסמוך על ראייה שלנו, אבל כאן, לא נסמוך על ראייה שלנו. ותחשב.
* ט:
** מקצת רחם -
מעניין שדנים במקצת רחם, ולא במה שרק נוגע במקצת הוולד.
** מין במינו -
נראה שאולי הענין הוא שכיון שרק אחד קדוש, מין בשאינו מינו הוא בהו"א. כמובן, זה גה"ח, אבל אולי זה מספיק. ותחשב. לכן, אין זה קשה לר"י. ותחשב.
* יא:
** ממורחים -
נמצא שאף שהוא כהורם, עדיין צריך להרים אותו כדי לעשות אותו לחולין.
* יב.
** מאי אהני -
צריך לחשוב לפרש מה הכלל שמגלה לנו מה לרבות ומה למעט.
** נדמה מיבעי -
ואם תאמר למה הם שייכים זה לזה. נראה שהבעיה בשניהם הוא חילוק ביניהם לשאר המין או להורותיהם. כלאים הוא שינוי בקרק' יותר חשוב מקרק' של שינוי שבנדמה.
* יג.
** קדושת הגוף -
צריך ביאור למה זה סיבה להקדים אותו. גם צירך לחשוב אם הענין הוא שיש לו יותר קדושה או שהוא יותר "בכור." ותחשב.
** כדר"ח -
יש לדון אם חביב לו מפני שבא להכרת הטוב או מפני שיש לו פשט נאה, והוא ר"ח. ותו"ת.
** גופיה -
היה אפשר לומר שהוא  מפני שאם קונה גופו, קונה חפצו, ואם יכול לקנות חפצו על ידי היפוך זה על ידי כסף, בוודאי יכול לקנות אותו על ידי כסף. אבל, אז אין לימוד מקונה ישראל (קל וחומר השני) מהני, שאינו קונה את חפציו.
** ישראל יוכיח -
קשה, ששם לא קונה גופו, ואיך יכול להיות מוכיח. (אבל, עדיין מוכיח את הקל וחומר השני.)
* יג:
** משיכה -
מעניין שנחשב שמשיכה הוא דבר שמהני מדאו'. כסף מסתבר, שהוא פיי"ר, אבל משיכה מחודש. ותחשב על זה.
* טז:
** הא דקביל -
משנה שם מותר כשקבל משני טעמים. ראשון, אינו הלוואה. ושני, אף אילו היה הלוואה, מותר, כיון שיש אפשרות לשכר ויש אפשרות להפסד. ותחשב.
** ולדות -
אם, באמת, תופס את הוולדות שלו, קשה למה לא פטור גם ולד ולדות, שהרי האם הוא קצת של הגוי[fn:4]. נראה שחיוב ולדי ולדות הוא רק אם הולד הוא האב, אבל אם הוא האם, נכון הוא שיפטרו מחמת זה. ותחשב.
* יז.
** אף בכור שור -
איני יודע למה דרשה זו כל כך פשוטה, אחרי שחולקים מהו המקור לזה. נמצא שעל כל דרשה יש חולק, ואז קל לומר שיש מי שלא דורש שניהם. ויש לומר שכל הצד שלא לדרוש ממקור הוא רק שיש בכור אחר יותר טוב ממנו. צל"ע לעיל. ותחשב.
** זיל בתר אימיה -
נמצא שהצד לפסול אותו הוא שאינו דומה לאם של אמו. היה אפשר לומר שהצד לפסול אותו הוא שבא מפסול, שבא מנדמה. ותחשב.
** מה פשתן -
כנראה, מושג של נדמה לא נמצא גבי פשתן.[fn:5]
* יז:
** בידי אדם מאי -
יש להעיר שלכאו' לא מצאנו מקור לו. אז, צריך לומר שיהיה נודע בלי מקור.
** הכל בכתב -
נראה שהו"א של גמ' היה להביא ראיה ממה שה' צווה כן, שכשם שסמך ה' עליו שם, כך יסמוך עליו במקום אחר. אז, לזה דוחה שרק כאן ה' רצה כן- ה' רצה דבר הקרוב לאמתים וחצי לארון- אבל במק"א, אין לנו סיבה לחשוב כן. ותחשב מה שינה בין הו"א למס'.
** זימנים -
אף בלי חוט, יהיה אותו בעיה. ותחשב. ונראה שמה שהיה שם חוט הראה לגמ' שלא חייבים להרחיק מחשש שמא לא יכול לצמצם, אלא הוא כדי שיוכל לסמוך לחוט, ולזרוק בכל העליון או בכל התחתון.
* יח.
** ההיא דבריא -
יש לדון אם כיון שיצא ראשון, נעשה יותר בריא, או שיצא ראשון כיון שהיה יותר בריא.
** המוציא -
לכאו', היה אפשר לתרץ שסובר רבי עקיבא כסומכוס; כנראה, גמ' סבר שלא מסתבר לומר שסבר כסומכוס נגד רבנן.
* יט.
** כלל הצריך -
לא כל כך פשוט לי למה זה הל"מ, שלכאו' פשוט הוא שאם כלל צריך לפרט שפרט מפרש אותו. ותחשב. אולי הו"א שהוא גם בכלל כלל ופרט וכלל וכדו'. דחוק.
** סימן -
לכאו', הכוונה הוא שכשמטנף, זה סימן שהיה בו וולד שיצא עם הטינוף. כיון שהי הולד שיצא, אין הבא אחריו בכור. אף שלא יכול להיות שיהיה לה וולד כבר, רק לא יכול להיות ולד קיים, אבל יכול להיות ולד שיוצא בטינוף. ותחשב.
** דחייש -
יש לדון אם, למסקנת הגמ', רבי מאיר סובר כן ברובא דאיתא קמן.
** רובא דאיתא -
לכאו', החילוק הוא שהוא רוב יותר טוב כיון שמה שהוא רוב בא מסטט', לוא מג"ס. ויש לדון בזה. גם אפשר שמה שידוע שדבר הוא שם עושה שהוא יותר חשוב, וכיון שיש יותר היתר מאיסור, זה יותר מחזיק את ההיתר משמחזיק את האיסור (אף שהפרופרשי"ן נשאר שווה).
* כ.
** דלא תלי -
זה מראה מקום. צריך לחשוב למה זה כן, שהייתי אומר שיסוד של רוב הוא שמסתבר כן. אז, בין אם תלוי במעשה בין אם לא תלוי במעשה, יהיה רוב. לכאו', יש שני דרכים לתרץ לזה. דרך הראשון הוא לומר שאין רוב תלוי (רק) בכמה מסתבר הוא, אלא גם בדבר אחר. דרך שני יהיה שרוב תלוי בכמה מסתבר הוא אבל יש דבר שמוציא מידי רוב, והוא מה שתלוי במעשה. (ויש לדון, שזה לכאו' חזקה (שאומר שדברים לא קרים), והרי רוב דוחה חזקה. ותחשב על זה.
** חוששים -
קשה, שיש נפקא מינא בהבאתו לקרבן (שאולי הוא חולין בעזרה). אם עבירה זו רק דרבנן, יש לומר שבזה לא חושש למיעוט, שאף ספק יהיה מותר. ותחשב.
* כא:
** העברה -
יש להעיר שכולי עלמא דורשים דינים מכאן. אז, צריך ביאור למה כאן לא אומרים שאין גזירה שווה למחצה.
** לקבל -
יש לדון מה היה ההו"א:
1. סבר שפי' של המימרא הוא שמה שפולט בתוך שלשים יום אינו נחשב טינוף.
2. סבר שכמו שלא מקבל זכר עד שלושים יום, כך טינוף אינו אלא לאחר שלשים יום. וא"ת למה ייתלו זה בזה. וי"ל שהסיבה שלא מקבל זכר הוא שמכין את גוף שלו. הרי, אולי קצת מסתבר שזמן הכנה וזמן שנשאר בתוכו הוא שווה. אז, מכין יום ליום. כיון שצריך שלשים יום להכין למה שוהא קצת וולד- ולא ירצה להיבעל אם אינו עשוה קצת ולד- נמצא שרק עושה קצת ולד אחרי שלשים יום. ותחשב. כמובן, לא קשה להבין למה נדחה, שיש הרבה הנחות שאינם מוכרחים.
* כב.
** נגעו -
לשון זה מעניין, שלכאו' אין זה ביטול דרבנן, אלא דאו'. (אגב, צריך ביאור למה ביטול ברוב מהני כאן, שבדרך כלל זה מהני דאו', אבל דרבנן עדיין גזרו. נראה שאין כל כך צורך לגזור בטומאה, כיון שאין איסור כל כך מיוחס לטומאה כמו שהוא לדבר אסור. ותחשב. יותר מזה, רבנן לא רוצים לגזור על טומאה, כמו שאומר גמ' בתחילת ביצה[fn:6].)
** לטעמיה -
יש לדון מהו טעמו:
1. אולי טעמו הוא שזהו הסיבה שאינה טמאה.
2. אולי טעמו הוא שיש ביטול ברוב בטומאה.
** נגעו בה -
זה קצת פו"ן, שלא מטמא במגע.[fn:7]
** ביטול ברוב -
אז, לכאו' יש חיוב אחר לקבור אותו, והוא שאסור בהנאה (שלזה לא נראה שנאמר ביטול ברוב).
* כג.
** כביצה במקום אחד -
איני מבין מה לנו בזה, שאם מצא מין את מינו וניעור, נמצא שאכל תרומה טמאה (שמשנה אמר שכבר נטמאה), וזה אסור גם בפחות מכביצה, ששיעורו בכזית, כשאר אכילות.
** אבטלינהו -
יש להעיר שלכאו' זה אסור, שאסור לבטל איסור לכתחילה. אז, ק"ק שנגזור כדי להציל אותו.
** אלא לרבי יוחנן -
ועוד שרבי יוחנן אמר בפי' שהוא מפני ביטול ברוב, ולא מפני שהוא טומאה סרוחה.
* כד.
** אדר"י קאי -
קצת צריך ביאור למה לא רק אמר, "... שאין לו מח' במשנה." אולי יש מקו' אחרים שנוגע לדעת אם מח' שבבריי' הוא בכלל מילת "מחלקת." (אולי הוא נוגע להל' כסת"מ.) ותחשב.
** הו"א מינה -
אז, היה אפשר לומר שבזה הוא הספק.
* כו.
** בבחי' -
נמצא שאף שלא נסתם הל', אלא רק נסתם מהו המחלקת, כיון שתנן בבחי' כן, הל' כן.
** ובמאי -
א"צ זה לומר שרבי יהודה הוא. אולי אומר כן כדי לבאר שקושיות שהקשנו על הצד שאינו רבי יהודה אינם קשים על הצד שרבי יהודה הוא. גם אפשר שאגב שבא להוכיח כמי המשנה בא לבאר את המשנה.
* כו:
** שלשה חדשים -
מגמ' לקמן יוצא שרק חולק בדקה, ולא מאריך בגסה כנגד מה שמאריך בדקה.
* כז.
** כהן קטן -
צריך ביאור למה לא טובלים גדולםי ואוכלים היום חלה של חו"ל.
* כח.
** ישלם -
לכאו', גרמי הוא (אם לא נטל ונתן ביד).
* כח:
** קנסא -
נמצא שאומר מילת קנס לגזי'. כמו כן משמע מגמ' לעיל (ב.).
** לאכחושי -
נמצא עוד הוכחה עם חוזק לדחותת עדים (כמו בכתובת בתחילת פרק שני). אבל, יש לדון אם אומר שמוכיחים שמשקרים או שספק הוא, שהוא כאנ"ס, וכשני עדים נגד שני עדים.
** ואם היה מומחה לב"ד -
צריך לחשוב על זה; לכאו', הוא גרם אותו היזק. אף אם היה אנוס, הרי חייב על אונס, ככל אדם המזיק. אז, צריך לחשוב מה לנו בזה.
* כט:
** חייק -
יש לדון למה לא רק אוסרים כשאומר שעכברים אכלו אותו.
** דמערבי -
וא"ת הרי זה פשוט, שהרי נתערב בו שמן. אולי הו"א שכיוןש הוא רק דרבנן (כיון שיש ביטול ברוב) יהיה מותר. ותחשב. (ואם תאמר למה הוא חלוק משאר תרומה דרבנן, שמשמע מן המשנה שהוא אסור. וי"ל שאין האיסור בעינו, כיון שהוא בטל.) גם אפשר שבא לומר, "קרבי דבים, דמערבי," והוא שמחדש שמעורבים בהם הרבה פעמים, ואז צריך לחוש לשמן. ותחשב.
* לא.
** רבי מאיר -
צריך לע' בקידושין, ששם רבי יהודה ורבי מאיר הם האומרים שתמיד בני ישראל נקראו בנים.
** מומא בכולא עדרא -
נמצא שלא חושש למה שלא יכול להביא קרבן מעדרו. וצל"ע בגמ' בב"ק (צח) כעין זה. (ואם תאמר שאני הכא שכל עדרו הוא. וי"ל שיכול להחליף אחד לאחר לאחד שאין בו מום, כיון שלאחד אין בעיה אם יש בו מום. ותחשב.
** הלוקח לולב -
נראה שזה צריך להיות לפי מי שמתיר מתנה על מה שכ' בתורה, שלרבי מאיר נאמר בזה שהוא אונאה, שכן יהיה בדר"כ.
** הכא מוכחא -
אבל בשל קטן, לא חוששים לזה. אולי זה נדחה או אולי הותר קצת, שעדיין יחשבו בנ"א שרק בשל קטן מותר.
** מנא אמינא -
תחילת זה מוסכם לכל.
* לב.
** דהא מעשר נמי -
צריך ביאור כוונת גמ' בזה. אולי אומר שכיון שהוא אז ג"ש מג"ש, אין חשש לימוד מלימוד בקדשים (כמו שאומר גמ' בזבחים (נ.)).
* לג.
** זר -
ממה שר"ע לא רק לומד מזה, משמע שאין גוי אוכל בק"ק. כמו כן נראה מגמ' בתחי' פסחים (גבי גוי שהרגו ע"פ מש"א ר"י מנציבים), אבל שם יש לדחות שהרגו אותו מחמת גזל, שהיה נמנה בטעות. צריך ביאור מהיכי תיתי שאסור לו לאכול. ותחשב. אולי רק לא מצאנו היתר למי שאינו מבנ"י.
* לג:
** יטהר -
נמצא שנגע הוא בתוך ימי משתה, אלא שלא מטמאים אותו. (איני יודע אם מראה לכהן או לא. אם אינו מראה, זה מאד מחודש.)
* לה.
** קסדור -
ואם תאמר למה עשה כן אם לא להתיר אותו. ויש לומר שהיה כל כך אוגל"י שרצה שיהיה יותר אוגל"י. דחוק. גם אפשר שסבר שכיון שיטיל בו מום לא יותר עולמית, שלא ייעשה בעל מום ממילא בחיו. מוזר שיחשוב כן, וגם מוזר שאחר זה יעשה הרבה מומים לטובת בני ישראל. גם אפשר שחשב שזה לא מתיר אותו אלא בשחיטה, אבל לא בהנאה. ותחשב.
* לו:
** ליהודה -
נמצא שקרא לרב יהודה "יהודה." (אם נאמר שלא נסמך, זה יותר קל, אבל ע' ברשי בתענית שאומר שכל מי שנקרא רב, ואף לא רבי, נסמך. אז, צריך לומר שהיה חבר שלו, ולכן לא קרא אותו רבי. ותחשב.)
** אפי' כלישנא קמא -
לשון זה קצת מוזר, שלא נראה שהם תלויים בכלל. ותחשב.
** האי הוא דחציף -
ואם תאמר אף זה רק חציף כיון שהיה לו סיבה לחשוב שלא יכיר. וי"ל שבדרך כלל יהי האותו סיבה לחשוב כן כיון שלא יראה לו. יש רק חשש שיראה אותו לאחר זמן, והרי היה אותו חשש כאן (שמסתמא ירפא עינו). גי"ל שזה גופא הוא הסיבה שלא חוששים באחרים. דחוק. גי"ל שבזמן שהטיל מום לא ידע שיקרה דרך לו להטעות אותו, אלא נתן מום, ולאיזה סיבה חכה קצת, ושוב בא לו האפשרות להטעות. ותחשב.
** רבי יוסי -
יש לדון למה אין מביאים את זה בביצה להוכיח שהיתר בכור הוא חלות ואסור בי"ט, שאם אינו חלות, קשה למה צריך מומחה כאן. אולי צריך אותו כדי שידון אם מניחים שכהן לא נתן בו מום.
** ריב"ל -
נמצאש שרי"נ אמר בשם ריב"ל, ור"ל אמר (במק"א) בשם רי"נ. אז, לא מסתבר שריב"ל היה תלמיד של רב (כמו שכ' רש"י, וכ"כ מקצת שיטות המובאות בסדר הדורות) כיון שהיה ר"י בזמן ר"ל. יותר נראה שהיה רבו. אבל, דע שיש שסוברים שיש שני רי"נ יש להעיר שנראה שגופא תלוי בשני לשונות אלו.
* לז.
** רשב"ג -
קשה, שלכאו' אסור לערב אותו. וי"ל שיש לו שוויות, כיון שיכול להשהותו עד שמתערב. ותחשב.
* לז:
** מום עובר -
יש לדון מהו ההו"א:
1. בפשטות, ההו"א הוא שאף שחוזר להיות כשר, יכול לפדות אותו כל זמן שלא כשר.
2. אפשר לפרש שההו"א הוא שלא יחזור להיות כשר, כיון שנדחה על ידי מומו (אף שחוזר עומד לחזור). ואם תאמר אם כן איך מוכיח מן הפסוק נגד זה, שהדרשה מיוסדת על מה שיחזור להכשירו. וי"ל שפסוק גם מוכיח שיש דבר שחוזר להכשר, שאם לא כן, על מה מדבר כשאוסר פדיון דבר שיחזיר להכשר שלו. אז, לומדים מזה גם שחוזר להכשרו.
** איבעית אימא -
ואם תאמר למה לא נאמר כצד ראשון. אפשר לומר שלא נדרוש משם מומים עוברים אם לא שכבר מסתבר, כיון שכבר דורשים שהוא שונה גבי דיני בכור. גם אפשר לומר שלא נוכל ללמוד מדין פדיון, שאחרי פדיון לא נשאר לו דיני קדשים הרבה. אבל, בכור שיש בו מום נשאר לו קדושת בכור. (אם הייתי ישיביש, הייתי מוסיף שאולי לא חסר קדושה אלא חסר כשרות. במילים אחרים, קדושת בכור הוא קדושה שגורם הקרבת כשאפשר או אכילה כשאין הקרבה. מה שאין בו מום נצרך כדי לעשות שהוא כשר להקרבה. ותחשב על זה.
** פסח -
פסח הוא מה שלא יכול ללכת על רגליו. יש להעיר שזה יכול לקרות לזמן ולחזור. אז, צריך ביאור איך נמעט מום עובר מזה. אפשר לומר שמוכרח שפסח זה קבוע, כיון שצריך למעט דבר. גם אפשר שכיון שאילו רק כ' פרט זה, ולא כ' ריבוי אחרת, לא נרבה פסח עובר, כיון שאין מקור לומר שפסח זה עובר הוא. אז, דורשים כן ממנו. גם אפשר שמילת פסח (או מילת פסח סתם) משמע פסח קבוע, אף שמה שעושה אותו פסח יכול לקרות רק לזמן.
** בידי שמים -
משמע שדבר שהוא בידי אדם יותר מסתבר להיות מום. יש לדון למה; הייתי אומר שמה שלעולם היה בעל מום יותר נחשב בעל מום. נראה שבעל מום אינו רק בהמה שיש עמו בעיה, שכל בהמה יש בו בעיה במה שלא יכול לעוף. אז, פשוט שצריך בעיה שלא נמצא ברוב בהמות. אז, אולי הוא מום ביותר אם אותם "בהמות" כולל אותו, מלפני זמן. ותו"ת.
** פגימה -
איני יודע למה אין סדק כבר כולל פגימה.
** כרשענה -
צריך בעאור למה שואל בדווקא גבי כרשינה, ולא גבי עדשים.
** העומדת -
יש לדון איך נדע אם הוא כשיעור אם הוא כשיעור ראשון. נראה שאפשר להכניס ולהוציא, אבל לא קל, כמו שמשמע מגמ' בסוכה (אולי על ידי זה נטרץ סתירת הגמרות אם צריך יותר הרחב כדי להכניס). גם אפשר שיכול לתת כרשינה קרוב לו ולראות. גם אפשר שכולי עלמא מודים שצריך להיות ראוי להכניס, ורק לא לצאת. גם אפשר שאם עושים נקב בו, אינו ראוי להכניס (שצריך נקב יותר גדול כדי לכוון הכנתו לנקב), ואז ניקב דבר אחר בכרשינה קרוב לו, ונבדוק.
** כיוצא בה -
יש לדון אם כוונתו לומר שנוכל להוכיח משם או שרק הזכיר לו דבר תורה, ואז אמר לו מהו.
** כראש -
זה מטבע גדול מאד. צריך ביאור מי יעשה מטבע כל כך גדול, ולמה לא יעשו יותר קטן.
* לח.
** חזקיה אבי עקש -
בדרך כלל, בני אדם לא נקראים על שם בנים שלהם אלא על שם אביהם. (לכאו', זה מפני שתמיד היה לו אב, ולא תמיד היה לו הבן.) אולי עקש היה יותר ידוע מאב שלו. גם יש לומר שלא רוצה להזכיר שם אביו (כמו רב מרי בר רחל).
** מקולי -
לא קשה לומר שנשאל לדין טריפה, ושם בית שמאי לחומרא.
* לח:
** אבל מורה -
לשון זה קצת מעניין, שכמו שיבאר גמ' זה רק אם היה שונה מתחילה כן.
** סירא -
כיון שהסירא הוא חלק מן העין, והוא גבול, נראה שאולי בן סירא נקרא כן כיון שהיה מאד טוב לראות (רצה לומר, היה גם קצת רואה דברי חכמה). ותחשב. וצריך לע' שם, שאולי מסביר.
** חלב -
נראה שיכול להיות שני צדדים לומר שאינו בעיה בחלב[fn:8]:
1. אולי הוספה על חשך העין הוא רע.
2. אולי אין אומרים שיש הוספה על חשך, אלא שהחשך הוא גדול עם חסרון גדול.[fn:9]
** קבועים -
מצאנו, אז, שני הגדרות: צריך לבדוק בשמונים יום, וצריך לבדוק על ידי אכילת מאכלים. יש לדון בשייכותם זה לזה. אולי צריך שניהם, או אולי זהו הדרך לבדוק בשמונים יום.
* לט.
** למפרע -
צריך ביאור למה לא יהיה למפרע, שלכאו' הייתי אומר שזה גילוי עליו. אין לומר שחוששים שנשתנה, שאז נאמר שחזר. אולי זה מוקמים אותו על חזקזת תמות שהיה לו.
** פסחים -
אולי נקט אותו קרא כיון ש"פסחים" דומה לשמו של "פנחס." גם אפשר לומר שנקט זה כיון ש"פסח" הוא המום שנאמר בקרא.
** חוטם -
איני יודע כל כך מה נקרא "חוטם."[fn:10]
** קודם שחיטה -
אז, רק רצה לומר שאין מום אחרי שחיטה (או קבלה). אז, קשה למה לא רק אומר כן.
* לט:
** קודם זריקה מי שרי -
קשה, שמוכרח שלא לדרוש משם, שאם היינו דורשים משם, לא היינו צריכים קרא לפסול מום שבא קודם קבלה. אולי בלי זה, היינו רק ברים הויה אחת, שהוא קבלה. ויש לדון, שלא אומרים שרק מרבים הויה אחת שהוא הולכה. גם אפשר שלא היינו מרבים אותו דין כלל, כיון שאינו כל כך מסתבר. רק אחרי שמצאנו כן בקבלה, הוא מסתבר. אולי הסיבה שאינו מסתבר הוא שכבר יש בו מום, שנשחט. (מה שהוא מת יהיה מום, ומה שיש מכה גדול בצוואר שלו יהיה מום.
** נפגם ולא ניטל -
מעניין, אז, שאין אומרים שמום זה עובר, כיון שבידו לתקן אותו על ידי נטילת כיס. (אין אני יודע דין של מום שיכול להכשיר.)
* מ.
** השתא אין לו -
איני יודע למה כל כך פשוט לגמ' לדרוש ככה, שאולי יהיה כמו ניטל כיס, שאינו מום, ורק נפגם מום. אולי מסתבר לגמ' שזה רק מפני שמוליד אותם מחדש, ואם כבר הם שם, אינו מוליד אותם מחדש (אולי מפני שאין מקום או אולי מפני שהגוף לא מבין בצורך). אז, אולי אם נולד בלי אותו דבר, אין זה סברה, שאולי לא אפשר שיחזיר אותם. ותחשב.
** כל יתיר -
אפשר לפרש שפסול חלסר הוא שיש רגל בלי כוח. אם יש שלש רגלים, יש אחד שחסר בכוח (שהכח נחלק ביניהם). גם אפשר שיש חסרון כוח כיון שהשנים אין להם כל כך כוח, שמקצת כוח ניתן לשלישי.) אבל, כל זה לא נראה כל כך במציאות, שבדרך כלל, אם יש עוד רגל, אין כוח כלל לרגל הנוסף.
** מאי תנא -
איני מבין את הקושיה כל כך. לכאו', שנה את זה כיון שהוא שונה את המומים. אולי מקשה למה הזכיר סיפור, ולא רק הזכיר את הדין. אז, תי' שבא לומר שלא רק אילא סובר כן, אלא זה לכולי עלמא.
* מ:
** עצם אחד... אין בו עצם -
צריך ביאור מה הדין עם יש בו שני עצמות. עיין בגירסת רש"י.
** עצם -
באמת, אין עצם בתוך האוזן, אלא הוא קארטילי"ג. (יש עצם קרוב לו, וממולא מין מים, אבל זה רק מה שנקרא האוזן הפנימי, ובפשטות גמ' לא מדבר על זה, שאין אני רואה איך יכול להיות שנים מזה.)
** שיער -
קשה למה לא אומרים על זה, "מכדי קרא סתמא...."
** עינו אחת -
יש לדון מה רוצה לומר:
1. עינו אחת גדול ועינו אחת קטן.
2. שני ציורים יש- עינו אחת גדול ועינו אחת רגיל, ועינו אחת קטן ועינו אחת רגיל.
* מב.
** סמי מיכן -
יש להעיר שאם ממעט גם טומטום, צריך לומר לא רק שיכולים למעט טומטום, אלא שיכולים למעט טןמטום כמו שיכולים למעט אנדרוגינוס, ששניהם נתמעטים מפסוק אחד. ויש לדון, שאולי יש משמעות לפסוק שממעט אותם, וזה ממעט שניהם. ותחשב.
* מב:
** יחיד -
מעניין שנאמר כן נגד שיטה שנאמר בשם "רבנן."
* מג.
** גרב גרב -
ואם תאמר למה צריך שני גזרות שוות. אולי הוא רק אחד, והוא על שני המילים. ואם תאמר למה לא אמר אותו על מילה אחת. אולי יש מקום אחר שהיינו מניחים לו הלימוד אילו רק היה אחד. צריך לע' איזה מקום הוא. (כעין זה מצאנו בתחלת פרק ר"א דמילה, אבל שם יש צורך להרבה מילים בג"ש, שאל"ה יש דברים אחרים שיהיו בג"ש.)
** לאפנויי -
עיין לעיל, שדרש ממנו.
** מצוות -
מעניין שזה שייך לדין בכור שלו.
** בכור מבכור -
מעניין שיש הו"א לדרוש זה מזה, שמה שעושה אדם הוא מאד חלוק ממה שעושה בהמה. ותחשב.
** קדושתו מרובה -
קשה למה לא לומדים ממין אחר של קדשים שאין בהם קדושה מרובה. וע' בזבחים שמבאר מה יותר חמור ממה; אף אחד לא פחות מבכור, ורק מעשר שווה לו. אולי גם מעשה לא נודע, אלא מבכור. צריך לע' לקמן.
* מג:
** לאפוקי מהא -
יש לדון למה צריכים לומר כן, שהלכ' כבר כסתם משנה. ותחשב.
** מדרש -
גם היה אפשר לומר שהבריי' הוא שיטת רבי חב"א. ותחשב.
* מד.
** באמה -
קצת צריך ביאור מה היה ההו"א שנשער אותו באמה של משה. אולי כיון שה' מינה אותם על הבנין (ק"ק, שלכאו' מנה את בצלאל), מסתבר שבו נשער.
** כריסו צבה -
איני יודע מה בכלל זה, אבל ראוי להעיר שכהן בעל בשר כשר, כמו שאומר ביומא גבי קמיצה.
* מד:
** אין לו ביצים -
קשה למה לא נקשה כמו שהק' לעיל, שאם אומר "יש לו אחת," למה צריך לומר "אין לו שנים." אולי גם בזה הפי' הוא כמו שתי' הגמ' לעיל, ולכן לא צריך לדון בו. ותחשב.
* מה.
** זונה אחת -
משמע שלומדים מן הגויים. עיין בנדה (מה.) שלכאו' זה מחלקת בין צדדי הגמ'. אפשר שהיתה זונה ישראלית.
** שלקו -
יש לדון אם הם שלקו או הם בדקו אחרי שהושלקה.
* מה:
** אתחלא -
לשון התחלה קצת מוזר. נראה שלא דנים אם כחוש או חזק הוא, אלא כולי עלמא מודו שהוא חזק. אבל, יכול להיות שהוא חזק כיון שהשתמש בו. אז, דנים אם זה מפני שהיה בריאות יתירה או כחישות יתירה. (גם יש לומר, כעין זה, שכל אחד קצת כחוש, שלא השתמש בו אלא חמישים אחוז. אבל, צריך ביאור למה משתמש ככה, וכמו שכתבנו בביאור ראשון.
* מז.
** גר שנתגייר -
הראה לי מ.וו. שחולקים אחרונים אם כף הדמיון הוא ממש. גמ' זה משמע שהוא ממש. (אולי הוא רק ממש לענין דין, אבל אולי אינו באותו דרגה.) אפשר לומר שהיה "גר שנתגייר..." מאמר ידוע, ואז ר"ל היה אומר, "שהרי ידוע שגר...," ובאמת חלוקים אם כף הדמיון דווקא הוא או לא. דחוק.
** לטעמייהו -
מעניין שאומר כן, כיון שיאמר לקמן שאין הכרח לתלות זה על זה.
** הא וודאי -
אינו וודאי, אלא הוא כן רק לפי רבי יוחנן. אפשר לומר שרצה לומר שזה בוודאי יכול להיות רבי יוסי. אבל, לא משמע כן. יותר נראה לומר שרצה לומר שכיון שלא הזכיר "גר שנתגייר," צריך לומר שוהא כשיטת רבי יוסי, שאינו מחמת זה (על כל פנים לא מסברה) אלא הוא דרשה. (ויש לדון, שגם לא הזכיר הדרשה.)
** זרה -
זה קורה קודם הלידה וקודם גמר הביאה (שעושה ולד), שהרי קורה גם בהעראה.
** אתינא מכוח -
צריך לחשוב על זה; משמע שחיוב הבן רק בא מחיוב האב. ותחשב. ויש לדון, שרק צריך לקיים חיוב אחד (חיוב בן או חיוב אב). אולי זה עושה שכאילו כבר קיים חיוב האב, ואין צורך, אז, בחיוב הבן.
* מח:
** לשני כהנים -
בכעין זה יש לדון אם כל כהן נטל בשביל בן מיוחד (ויש לדון איך קובעים מי נטל למי), אלא שספק הוא, או לא. יש לדון מהו הצד שלא. ותחשב על זה.
** שני זכרים -
יש לדון למה לא מזכיר כאן הו"א של רבי טרפון שתלוי איזה יותר חזק. אולי גבי בנ אדם אינו כן (יש לדון למה), ואולי כשהגיעו למשניות אלו, כבר חזר בו ר"ט. ותחשב.
* מט.
** הכל מודים -
לא הכל מודים, אלא פשוט מהו ההלכה שצריכים לנהוג. ותו"ת.
** מעלמא -
לכאו', זה מחלקת יסודי, והוא אם לומדים משני כ' הבאים כאחד לדבר שהוא באותו כלל[fn:11] של אחד מהם.
* מט:
** בדינא -
מעניין שזה נחשב איסורי, ולא דין.
* נב:
** לאתויי נכסי -
נראה שאולי הדרך שמרבה אינו רק שכופל הכלל, אלא שיכול לקרוא שמרבה ראוי שהוא כמוחזק. וצריך לע' בלשונו.
** לתת לו -
נמצא שלא מניח שהוא ירושה.
** ירושת הבעל -
נמצא שאילו היה דרבנן (כמו שיאמר לקמן), יעשו אותור בנן כמתנה (או שדין דרבנן יעשה מתנה). זה לא כל כך פשוט. ותחשב.
** נחלה -
מסתמא נקט לשון זה כיון שהסוגיה מדברת על נחלה.
** נחלה -
מעניין שמשבח אותו על ידיעתו כשלא ידע את המאמר שהוא נגד מה שאמר.
** אגב, יש
שאומרים שלעתיד לבוא לא יהיו כהנים כהנים, אלא לוויים. לא נראה כן מגמ' תענית שמדבר על כהנים שלא ישתו יין בזה"ז.
* נד:
** העשירי -
נראה שרצה לומר שצריך להיות שיש שנים, שרק אז יכול להיות עשירי נקרא "העשירי," שצריך להפריש אותו מעשירי אחר. ותחשב. נראה לי שמצאנו כעין זה בתחילת יבמות.
** קים להו -
לכאו' אי אפשר שקים להו כן מן הל"מ או כדו', שאז היה להם לדעת את הדין ממה שהשמיע כן תורה. יש לדחות שתורה משמיע לנו מציאויות שאין בהם צורך. דחוק. אלא, יותר נראה שחכמים השעירו מדעתם, וסומכים על זה. גם אפשר שלא ידעו את הדין בדיוק, שהיה יכול להיות שצירוף תלוי בחצי השיעור. גם אולי הו"א שנוגע לדין אחר. וצל"ע.
** אם היה באמצע -
ואם תאמר הרי זה משמיע חידוש להחמיר (שמחייב אותם במעשר). ונראה שנקט זה כיון שהוא יותר גלוי, שבלי זה, יש סתירה, ואז מוכרח שכוונתו כך.
* נה.
** עברי הירדן... ואצ"ל -
אם נאמר שהוא מפסיק כיון שהוא גבול, אז קשה למה אמר אותו, כיון ש"אין צריך לומר...." אולי הוא רק גבול השבטים, אבל אני לא חושב כן.
** גבול אחד -
לשון זה מוזר; לא רצה לומר שכולו גבול אחד, אלא שהגבול כולל את כולו להיות אחד. ותחשב.
** לשון בני אדם -
אגב, כל זמן שדנים בלשון בניא דם, צריך לע' אם הכוונה הו אשכשאומרים כן חושביםע ל אותו דבר או כשרואים את הדבר, חושבים על אותו מילה. יכלו להיות שזה מחלקת בין רבי עקיבא לרבנן. ותחשב.
** זכרותא -
נראה שקורא אותו כן כי האב רק שם (בהכרח) בתחילה, אבל אינו שם (בהכרח) בסוף, שלא צריכים אותו אז. גם זה הוא רק שם בתחילת המים, ולא נצרך בסופו. ותחשב.
** מי פרת -
קשה למה לא אומר שאמר, "מים מפרת," כמו שאמר לעיל גבי מערת פמייס לאסור.
** כבד -
אז, אינו רק העושה אותו, אלא הוא עצמו נעשה ממנו. אולי כיון שדם מטמא ככה, כל שכן שמה שעושה אותו מטמא ככה. יש לדון, שלא אומרים שמערת פמייס יכשיר מאותו כל שכן. ויש לדון, שאולי לא האבנים גורמים את המים לבוא, אלא יש שם מים, וזה הבורא שמים יבוא. אז, באמת מכשיר.
* נו.
** בנך -
קשה למה לא גם אומרים שבנך לא בא כיון שהקדיש אותו במעשר. ותחשב.
* נו:
** כהן הבא עליה -
זה רק אם היא זונה על ידי איסורים שפרט ביבמות, אבל לא רק מופקרת לזנות. איני יודע אם זה נכון גם בדין אתנן.
* נז.
** חלקו בהמה -
ואם תאמר לכאו' יש גם חידוש להיפך. אולי אין הכי נמי, ורק נקט אחד. גם יש לומר שלא פשוט לחלק בהמות, שיש חילוקים בין בהמה לבהמה. אז, רק אם כבר חלקו בהמות יש לומר שנחשב שחלקו את הכל.
** לטעמיה -
כמו לעיל, אמר "לטעמיה" כשיאמר שלא מוכרחים לתלות אותם זה בזה.
** יש ברירה... -
יש שמביאים ראיה מקושיית סתם גמ' בתמורה לומר כשכן הל'. כיון שק' זו גם נמצא כאן, יש לומר שסמך על ביאור של גמ' שלנו כאן. ויש לדון.
** משהוא -
יש לדון אם חסר משהו (שאז מוכרח שאינם אחד נגד אחד).
** רבי ישמעאל -
אין זה חולק, לכאו', אלא מוסיף לומר שזה הוא גם במשנה שלנו, כיון שהוסיף דרשה זאת. ותחשב.
* נח.
** כמה פרס -
צריך ביאור למה לא רק אמר השיעור או הימים.
** פחות -
לכאו', כאן הוא חצי חודש. צריך ביאור למה אומר, "פחות...," שהוא בדיוק ככה.
* נח:
** ממ"נ -
צריך ביאור מה יקרה אם שלש מאלו, שנים מאלו, וחמש מאלו יוצאים, שאז אין מעשר שלו מעשר. צריך לומר שאין הכי נמי, ונעשה ספק מעשר.
** לקוח -
אם נותן את אמם שם, לא יצאו הכל, ועוד שיבחין בין לקוח ושאר, שלקוח לא יהיה לו אם שם. ותו"ת.
** שאינה עוברת -
צריך ביאור, שרוב טריפות עוברות. אולי סובר שטריפה מתה, ואז עומד שלא תוכל לעבור. גם אפשר שיש טריפות שלא עוברות, ומס' שהסיבה להוציא אותם הם שהם טריפות, ואז נלמד לשאר טריפות. צריך ביאור. גם אפשר שמיעוט אותם הוא מיותר, שכבר פסולים כיון שלא יכולים לעבור. אז, צריך לומר שממעט אותם מחמת טריפותם. דחוק. (וצריך לע' אם קרא זה מיותר בכלל, שאולי הוא אומר שצריכים שיעברו שם, ואז אי אפשר לומר כשום צד שכתבנו חוץ מן הראשון, אולי.)
** בדיר -
אז, אינו ביציאתו שנקדש. צריך ביאור מהו המקדש אותו. ותחשב.
* נט:
** אלא אמר רבא -
רצה לומר, אלא רבא מסברה שלו דרש. צריך ביאור למה לא אומר שהבריי' שיביא לסמך לרבא הוא המקור של רבא.
** דיקא -
מעניין לקרוא לזה דיקא, שהיה נראה שהוא הוכחה גמורה. נראה שאולי הו"א שכולל שניהם. ותחשב.
* ס:
** וכל -
אפשר ש"וכל" מרבה אותם, ואפשר שדורשים לשים "וכל" על "עשירי," לרבות מינים אחרים של "עשירי"ים.
** מעורבים -
משמע שאינו ספק, אלא ממש מעורבים. קצ"ב, שאי אפשר לצמצם. אבל, ע' לקמן בגמ' (אפיק רישיה) שמשמע שספק הוא.
** חד עישורא -
קשה, שאם אין לו שני עישורים, למה הוא מונה יא'. אולי צריך להיות לו יותר משני עישורים כדי שיצטרך למנות את המעשרים.
* Footnotes
[fn:1] אבל, יש להעיר שיש ספק ספיקא, שאולי לא יצטרך להשביע, ואף אם צריך, אולי לא ישביע אותו, כיון שהוא אסור. ויש לדון בזה, שאולי אינם שקולים, ואולי נחשבים אותו שאלה. ותחשב.
[fn:2] יש לדון, שבדרך כלל מצאנו זה כשאומר את הסבג'קט אחרי המילה. ותחשב.
[fn:3] ראיתי באינקרט"א ככה:The monotremes make up by far the smallest subclass of mammals, with just three species, found in Australia, Tasmania, and New Guinea. One of these is the duck-billed platypus, and the remaining two are the echidnas, or spiny anteaters. The reproductive and excretory systems of monotremes share a single body opening, but a much more striking feature of these mammals is that they lay eggs, a characteristic unique from all other mammals. The female duck-billed platypus normally lays two or three eggs and incubates them in a waterside burrow. Echidnas usually lay a single egg, which the mother incubates in a pouch formed by two folds of skin on her abdomen. When monotreme eggs hatch, the young feed on milk, lapping it up from a special milk patch on the mother's underside.
[fn:4] הנחתי שפטור זה הוא גם בבהמה טהורה. מצאנו אותו בפי' בגמ' לעיל גבי בכור בהמה טמאה. אבל, לעיל בגמ' למד דינים של זה לזה (לענין נדמה). וצריך להגדיר.
[fn:5] זה לא כל כך פשוט. בבריטאניק"א, ראיתי שיש חילוק בין הנזרעים לגרעינים לנזרעים לפשתן (אבל, אולי זה רק תלוי באיך זומר אותם או כדומה). אבל, גם ראיתי שיש חילוק בין גוון פרחים. אולי זה לא חשוב די לעשות שלא נ' כמותו, או אולי אין דבר אחר שהוא נ' כמותו. ראיתי באינקרטא שיש מינים שונים של פשתן, ואז יש שנראים חלוקים, אבל אולי אינם כל כך חלוקים, או אינם בכלל פשתן. גם ראיתי שם שיש שיש להם יותר או פחות גרעינםי.
[fn:6] אגב, שמעתי מגר"ק שאמר "ביצה," ולא "ביעא."
[fn:7] ואם תאמר גם לא מטמא במשא. זה נכון, אבל ע' ברש"י, שרק מזכיר מגע. אולי רש"י הוא הבא לעשות פו"ן, אבל יש להעיר שמגמ' לקמן יוצא שאינו כל כך פשוט שלא מטמא במשא. אבל, לפי רבי יוחנן, כיון שבטל, לא יטמא במשא.
[fn:8] לא פשוט שכן סובר רבי מאיר. אולי סובר רבי מאיר שיכול להיות מום בחלב העין, אבל רק לא חסרון, אלא בלילה.
[fn:9] עיין בפדף.
[fn:10] עיין בפדף.
[fn:11] יש לדון אם הענין הוא הדמיון שיש כבר בציור או שאם נלמד זה מזה, יגלה שהם שווים בלומדות. ותחשב.
