* ב.
** הלוקח -
עיין שם בגמ', שאומר שני טעמים. רש"י רק אומר אחד מן השנים. (לכאו', הסיבה שלא אומר השני הוא מפני שהוא מיוסד על מאמר אחר, ורש"י לא רצה להביא אותו מאמר.)
** הלוקח -
וכל אינך- אין זה נכון, שיש פרקים לקמן שלא דנים לא בזה ולא בזה. אול רצה לומר שבן הפרקים שדנים בבכורות, כל שאר הפרקים ידונו בבכור בהמה טהורה.
** הלוקח -
עיין לקמן בגמ', שמסביר שהסיבה להקדים בכור בהמה טהורה הוא שקדושת הגוף יש לו. כמו שנבאר לקמן, לא פשוט למה זה סיבה. כיון שכן, מעניין שרש"י רוצה להעיר כך על המשנה, שבדרך כלל, רש"י רק מפרש כשיש קושיה פשוטה להעיר על המשנה.
* ז:
** דבש -
שאין כוורת- גם היה לו לומר שכיון שאמר אותו סתם, מוכרח שהוא דבש דבורים, כמו שאומר גמ' לעיל (שאין לו שם לווי). ויש לומר שדבש גם יכול להיות משמע כל מין דבש. ותחשב על זה.
* ח.
** כלב -
נ' יום- זה מעניין.
* יב.
** לא בחיה -
בא רש"י לפרש מה כוונת חיה, שהיה אפשר לפרש שצריך להמית את השה, ואז היה קשה, שאומר שלא יכול להיות חיה ולא יכול להיות שחוטה (ואולי אף הו"א שצ"ל נבילה). גם אפשר שקשה לרש"י שצריך להיות שה, ופשוט שאין חיה שה, ולכן נקט חיות הדומות לשה, עד שהו"א שנקראים שה. (זה תלוי, לכאו', במהו הצבי.)
* יז:
** הכל בכתב -
מעניין איך רש"י מביא את הפסוק, ומבאר אותו, ואחר זה מבאר שלא לגרוס אותו כאן בכלל.
* יח.
** שומן יהא ביניהם -
עיין בביאור רש"י. לולי רש"י, היה יותר נראה לומר שהכוונה הוא שמה שמה שיש ביניהם- דהיינו, מה שיש לזה מינוס מה שיש לזה- הוא השומן, שיש לזה בהמה ויש לזה בהמה, והחילוק ביניהם הוא כמה שמן הוא היותר טוב. ותחשב.
* יח:
** כל שחליפיו -
לא נ' שרש"י גרס כמונו בגמ'.
** שמניח -
ע' במה שפרש,"י. גם היה אפשר לומר שחולקים באותו ציור, שמדחמים ציור זה שלנו לאותו ציור. דחוק.
* כב.
** כפרדה -
נראה שאולי הסיבה שכורעת יותר משאר בהמות הוא מפני שמי רגלים שלו חלוק (כמו שאומר גמ' לעיל), שהוא יותר עב. ותחשב. (גם אפשר שלכן הוא חלוק, שכורעת יותר.)
* כז.
** רבה -
עיין שם (בר"ה ויבמות) שיש שני גי' בגמ' זו שמוזכרים ברש"י.
** נדה -
ל"א- לא הבנתי את החי'.
* לב.
** חלים על הכל -
יש לדון למה הזכיר שגם חלים על מה שאינו בהמה. אולי מה שבכור חל רק על בהמה הוא כמו מה שרק חל על בכור, והוא שזה חלק מסיבת קדושתו. קשה למה זה יחלק. ותחשב.
* לז.
** אבל לא מן העור -
עיין במה שפי' רש"י. זה מיוסד על מה שאומר גמ' שמום צריך להיות דבר שלא חוזר לבריאתו. אבל, יש להעיר שיש קרק' אחר שצריך, והוא מה שיהיה מום. גמ' לא מפרש מהו מום, ולא כל כך פשוט מהו. אולי הוא כל שינוי, אבל לא מסתבר כן. אולי צריך להיות שינוי שאינו לטוב, או שינוי שהוא לרע (ויש לדון אם פגימה באוזן הוא, באמת, לרע). ותחשב. על כל פנים, הכוונה שלנו הוא שלא מוכרח כפי' רש"י כאן, ואפשר שהסיבה שלא נחשב מום אינו מפני שחוזר אלא מפני קרק' אחר שקובע מה בכלל מום.
* לח.
** כחזקיה -
עיין ברשי. לכאו', הכוונה הוא שאף שלא היה קל להבין (ויש לגמ' כמה לשונות), עדיין מניחים כמותו. יותר מזה, יש להעיר שחזקיה אינו איש ידוע, ועדיין סמכו על עדות זה. יותר מזה, אולי חזקיה לא היה לו ייחוס טוב (עיין לעיל), ועדיין סמכו עליו.
** כי היכי -
עדיין נגזור על תוכו.
* לט.
** תורא ברא -
עיין בלשון רש"י. הענין הוא שבפנים קרוב לפה, יש עור, כמו כל עור האדם, ושוב אנג"ל, ואחרי זה עור מיוחד של שפה. כשדנים בפגימה, דנים בפגימה באותו אנג"ל.
* לט:
** הצורם -
איני יודע למה צריך להיות פר של כהן משיח, שלכאו' יוכל להיות כל פר שמביא. אולי אותו קרא נאמר בפר כהן משיח. (ויש לדון מהיכי תיתי ללמוד ממנו. אולי אין הכי נמי, אין לומדים. אבל, אז היה לנו לומר, "כאן בפר כהן משיח....)
** או שראש -
עיין ברשי. נראה שכוונתו לומר שבדרך כלל, אם רק קצת ממנו מגולה, כיון שיש בשר בשני הצדדים, מעלה ארוכה. אבל, כאן, בהכרח יש רק בשר בצד אחד (שהוא הסוף), ואז לא יעלה ארוכה.
* מ:
** אינה מום -
ולא דמי- י שלדון למה לא אומרים שכל יתר כחסר.
* מד:
** אחת לימים -
עיין ברשי. לכאו', רש"י מזכיר שני דברים- זמנו קבוע, ואין זמנו מצוי. מעעניין שרש"י רואה שני דברים אלו כאן.
* מה:
** כמותך -
יש לדון אם רצה לומר שכמותך ירבו ממזזרים, ואז יתמעטו, או שרצה לומר שאתה בוודאי ממזר, וכמוך ירבו בין מין שלך. ידע שהוא ממזר כיון שמסתבר שלכן נתן ה' אות זה. (יש להעיר שלצד ראשון, צריך לומר שאין זה אות עכשיו. אז, כדי שיועיל, צריך שייעשה אות. צריך לומר שאחרי שנראה יחס בין שני הדברים, ייעשה סימן. ותחשב.)
* נג:
** וצאן -
מין אחד- כיון שמצדד גמ' לדרוש כן גם לענין חדש וישן, משמע שהבעיה הוא שהם קצת מינים חלוקים. יש לדון, שאולי רק משמע שיכולים לעשר מזה על זה, ורש"י מבאר למה זה יהיה כן. דחוק.
* נה.
** תרגמה -
גם היה אפשר לומר שמשנה את הגי' לומר תשע. אולי לשון תרגמה לא משמע כן, אבל יש לדון למה לא ישנה את הגי'. (באמת, יש לדון אם צ' לשנות את הגי' לומר שהוא ציור אחר.)
** מדן -
שם מקום- שאינו מכוון לדן ממש, שאם תסתכל בציור, תבין שדן לא קרוב לירדן.
* נו.
** רבי יוחנן -
יש לדון אם זה רק אומר שיאמר דבר טוב או שיאמר דבר טוב לסיוע לרבי יוחנן. (אני חושב ששני פעמים שמצאנו אותו בבכורות אומר דבר לסיוע לרבי יוחנן.)
* נו:
** האחים -
עיין בירושלמי שקלים שמביא הרבה סיבות לדין קלבון.
** קנו -
גם אפשר ש"קנו" רצה לומר שקנו כשמחוסר זמנו.
* נח:
** ונוטל -
הרי זה מעשר- עיין שם, שמחלקת הוא.
** ספק מנין הראוי -
עיין במה שכ' רש"י. לכאו', הענין הוא שיש צד שמסתבר לקרות שלא יעשה שאלול יהיו בכלל מנין. ותחשב על זה.
* ס.
** וכי יש תמורה -
היה נראה שהדרשה הוא שדורשים מ"תמורתו" שרק תמורת הקרבן, ולא תמורת התמורה נקרב. אבל, לשון גמ' בביאור הדרשה לא משמע כן, אלא משמע שהוא שרק קרבן ותמורה מקריבים, ולא תמורת תמורה.
** רגלא -
רש"י מזכיר מה שיגיד טוב להרבה בני אדם השומעים. גם מונע מרע מכולם, שהיה נראה רע אם לא היה יכול להשיב.
