* ב.
** שבא על חטא -
אינו ר”ל שיש לו אפקט- שמכפר- לחטא, שאף לעולה יש אפקט זה. אלא ר”ל שסיבת ביאתו הוא כפרת חטא. גם יש לומר שדומים במה ששניהם מכפרים מקבעט (ועיין בגמרא לקמן).
* ב:
** מעלייתא -
יש לדון מה רצה לומר:
1. היו שני מעלות בשיעורו:
  1. היה סתירה גשמק.
  2. מה שסתר היה בעצמו דבר גשמק.
2. היה סתירה טובה כיון שלא היה אפשר לדחות אחד מן הדברים הסותרים, ששניהם היו טובים.
3. אולי קרא את הדברים בשם זה מחמת הסתירה שבא מהם (כמו מה שאומרים בני אדם שרמב”ם זה גשמק, והוא מפני שיש עליו גר”ח גשמק. ותו”ת).
[כאן נכתב זה:
1. ניחוח/ שם:
  1. מביא מפני שכן צווה
  2. מביא מפני שכן נותן רוח לה’/ רוצה ליתן רוח לה’.
2. עומד לשמו:
  1. להקרבה לשמם (יש לדון לרבי יוסי אם יהיה עומד).
  2. להקרבה של חטאת (או של אותו קרבן). כן נראה מאותו של גט.
3. קשה בהא דגט, שאף אם יהיה עומד, שניהם נשיו, ושניהם יעמדו שווה, ואז א”א להביא ראיה.
* ג.
** דאין ברירה -
רצה לומר שגבי סתם, “מפרשים” את דעתו כיון שאין דעת בפועל; אבל כאן, יש דעת בפועל, ואי אפשר לפרשו אלא על ידי ברירה. ותחשב. ועיין ברשי (שהוא לשיטתו בביאור למה לא נאמר שיש ברירה).
* ג:
** תירוץ גמרא
:
1. כיון שמקרא, אין מק’ מסברה.
2. תוכו קרא?
3. ענין ק’ לעיל הוא שאין סברה זו נכון, והוה ליה לומר סברה כקרא, ואז אין מקור.[fn:1]
* ד.
** הולכה לא -
ואין ללמוד משחיטה וקבלה כמש”כ; מזריקה וקבלה שאינם בזרים; מזריקה ושחיטה שאין חייבין בחוץ. פשוט שא”א ללמוד מהולכה ואחת מהני. אבל ק”ק למה אי אפשר מהולכה ושנים.
** ובשר -
למס’, צ”ל שדורשים רק אחד (וכן בהא דר”א) ואו שאין זה ייתור או שתורה יעשה שני ייתורים לגלות לנו דין אחד (וצ”ב). ותעכ”ז.
* ד:
** קבלה והולכה לא -
אם כן, לכאורה, לא נצרך קרא זה, שיש לעיל (וכן אי הוה כלל ופרט, אלא ששם יש לדחות שזה ממעט זריקה ואומר שלא לדרוש כר”א) ואז מוכרח שאין זה כלל (או שנאמר גבי הא דר”א אם אינו ענין. וע’ לקמן.)
** לישנא אחרינא -
צריך לחשוב בכלל זה, ובחילוק הלשונות. ותחשב.
* ה:
** באין בנדר -
צריך ביאור למה זה יהיה סיבה שלא ירצה. ואולי יש לומר שחיוב הבא על ידי עצמו יותר חמור מהבא על ידי תורה. ותחשב. (ועיין בצדי צדדים פרק יש נוחלים שעל פי סברה כין זה בארנו למה יחס של אישות יותר חזק משאר קרובים, והוא שהוא עשה אותו, ובא על ידי מעשיו.)
** מיעט רחמנא -
לא הבנתי למה רוצה למצוא חילוק; כבר מצא קרא שממעט אשם.
* ו.
** מקופיא -
צ”ב מה אומר. אולי רצה לומר שיש כפרה במה שעושה מצוה, אבל לא במה שקרבן מביא. ויש לומר כמה סברות כמו זה.
** אעשה -
בפשטות, רצה לומר שכמו שמצינו יותר מכפר בענין זה, כך יותר מכפר בענין אחר. ויש אולי לפרשו באופן חידוש שר”ל שאין שום דין כן בחטאת, אלא שחטאת צריך להיות הופרש על חטא, ויכול לכפר רק על אותו חטא. אז, ממילא אי אפשר לכפר על חטא שלאחר הפרשה. אבל לעולה, אין בעיה זו.
** לאחר -
באמת, בבת אחת הוא, אלא ששחיטה הוא סיבה לביטול.
* ז.
** אבל עשה -
הצד לומר שמכפר מוכרח דלא כרבא לעיל, אלא כר”ה.
** לשום שלמים -
צריך ביאור למה נקט שלמים (ואף אם תאמר שנקטו כיון שמין שלמים הוא, צריך ביאור למה לא נקט אותו לעיל).
* ז:
** לשמו:
א. אינו חושב על הטוב.
ב. חושב על שקר.
כאן, צריך לומר שאין זה באופן חשוב.
** אלא ש”מ -
ק”ק, שבחטאת א”א כן.
** מנלן -
י”ל שאם לא כן, למה צריך מקור אחר. נראה שכן מק’, ”הוא ל”ל.” ושו”ר בגמרא לקמן.
** לעכב -
אם כן, נמצא שצ’ קרא זה למעט אשם. וקשה, שעדיין יש קרא בחטאת למעט.
* ח.
** בשנוי בעלים -
לא הבנתי, שהרי כתיב חטאתו גבי זריקה של שינוי קדש.
** חטאת חטאתו -
אם כן קשה למה צריך חטאת חטאתו של זריקה  (ויש לומר שאל"ה, לא הוה דורשים כן. ודחו"ק).
* ח:
** ובשאר -
ואף ששלמים הוא, שאינו נפסל בשלא לשמה, אלא שכיון שיש לו יחס לקרבן פסח, נמשך להיות דומה לכן, וכיון שאין זה זמנו, פסול. (נראה שגם יש לומר ששמו שלמים, אז, וכיון שהוא כבר קצת פסח, כשחושב עליו, נשתנה שמו לפסח, וזה גופא הבעיה, שאף שאר קדשים יש להם פסול שלא לשמה- דהיינו, שיש בעיה ממה שיש לו שני שמות, אבל לא כל כך, אבל בדרגה כזה, שיש לול אותו שם אחר באופן חזק, אולי יש להם. ותו"ת.
** לזבח -
ק"ק שנדרוש שזה (הא דיכול לחשוב לשלמים) רק בשחיטה שכשר בזר. צריך לומר שאין לשון קרא משמע כל כך כזה.
* ט.
** למאי נפקא מינא
:
- אין צריך נפק"מ; חלוקים הם.
- אולי דן למה דנים בו.
- אולי אינו נעשה אחד מאלו קרבנות, אלא יש לו מעשה שלו. אם כן, אין חילוק חוץ מנפק"מ.
1. less דומה to מעשר/ בכור or תמורה
- their קדושה is done differently
1. מעשר is קק"ל weak, כמו פסח. Should be מעשר when לשם שלמים.[fn:2]
* ט:
** דחזי -
משמע שלאחר פסח שני, אף אי לא עבר שנתי, הוה כעבר. ולולי זה, הוה אמינא שיש הוה אמינא שלא להקריבו לשלמים, שמיוחס מאד לפסח, שהרי לזה הוקדש, והוא בהמה כשרה לפסח (אלא שאינו זמן פסח).
* י.
** חטאת תוכיח -
קשה אם כן נלמד כמה קרבנות אחרים גם כן. עוד ק’ שלא אמר כן ר"א, אלא אמר שהוא מפני שבא על חטא, ולמסקנא, אין צ’ זה.
* י:
** חד מתרי -
אם כן, אינו צריך לומר, לכאורה, כרבי ישמעאל.
** ודמו -
ק; נימא חטאת יוכיח.
** באשם שיש לו קצבה -
קשה, שנלמד מזה אף דין לשמה (ונ’ שלזה אי אפשר ללמוד מחטאת עוף. ובאמת, יש לדון מהו הדין גבי עוף).
** ר"א… כחטאת כאשם -
קשה, אם כן, למה צריך צד השווה.
* יא.
** שהיא כליל -
מניח גמרא שהיותר קדוש יותר אפשר לפסול. וזה מסתבר, שצריך יותר קדושה, ואז פגימה כל שהוא יפסל אותו. אבל, יש לחלק כאן שפסולו בלפני ולפנים בא ממה שהדם אינו שייך ללפני ולפנים, שאינו נזרק שם. אבל, אולי עולה, שקדשה שלו רב, אף שאינו ניתן לפני ולפנים, יותר שייך ללפני ולפנים מקדושתו מחטאת שאינו קדוש כל כך (בהא דאינו כליל).
** שכן אינה מכפרת -
רצה לומר, מכפרת על לאווים, שהרי עולה מכפר על עשיים (ואולי לא מכפר כמו חטאת, כמו שאמר גמרא שרק מקיבעא מכפר).
** דרב אבין היא -
ק"ק שנלמד מאותו ק"ו.
** דמה ולא בשרה -
יש לדון מהו ההוה אמינא לרבות בשרה (שלכאורה, דמה יותר קדוש שניתן על מזבח (ואולי לאימורים מכוון. ועדיין אולי יש לחלק.))
** בזמנו -
משמע שהודה לזה ר"א ואם כן קשה, שנאמר שחולק על יוסף בלשם פסח בשאר ימות. ואולי רצה לומר כאן ששחט לשם "פסח בשאר ימות…" (ואינו נ’ מחשבון גמרא כזה), שהוה שלמים. ותע"ז.
** מנחת נדבה -
הרי זה פשוט, לכאורה (ולמס’, אין זה המקור).
** פסח בשאר ימות
:
1. אינו מחשבה שייכת (תחשב מה זה. אולי הוא דומה למה שאמר גמרא בתחילת מנחות (שיטת ר"ש גבי מנחות)).
2. אולי ענין פסול הוא שנעשה קצת כאותו קרבן. אז, אולי פוסל יוסף כיון שפסח יש בו כמה עניני שאר קרבנן. לכן, זה רק ביד, שנעשה פסח. ותחשב.
* יא:
** אינו דין שתהא פסולה -
קשה מהיכי תיתי דלא כזה.
** אמר שמעון בן עזאי -
צריך ביאור למה אומרו כאן, ולא במשנה שלעיל.
** אמר"א אמר"א -
לכאורה, מוכרח שיודע כן משום ברייתא או מקבלה, שאי לאו הכי, מוכרח שנוכל ללמדו מסברה. וזה אומר שאין סברה לומר שפסולה אף שאין זה זמן פסח. ואם כן, קשה למה אין המחלקת אם יכול להקריב קרבן פסח אז. (ויש לדחות שכשאומר הו"א בר"י, רק הו"א שאפשר להמון עם שיקראו ר"ל, ולא דבר שהיה אפשר על פי אמת).[fn:3]
** ותניא מערב -
צריך ביאור למה צריכים להביא ברייתא זה, שלכאורה תירוץ גמרא שכבר נאמר בפירוש שמערב מתחיל. (ואם לא תאמר כן, אלא תאמר שהראיה הוא רק ממה שצריך לשנו "מערב עד בקר,” אם כן קשה איך יודעים ששיעור זה מערב ממש. אלא צריך לומר דערב ממש, ואז א"צ אותו ברייתא)
** את הכבש אחד תעשה -
או שמדיש חד בבקר, האחר צריך להיות בין הערבים, או שממה שמה שהוא בבוקר הוא רק בחצי היום(עיין בברכות שדן מהו זמנו ממש. על כל פנים, אינו בכל היום. ותו"ת.), אף הא דבין הערבים הוא רק בחצי (אחרון) של יום.
* יב.
** אין מחוסר זמן -
יש לדון אם אומר זה לכולי עלמא או רק לבן בתירה שמחשב מסוף היום לתחלתו.
* יג.
** לחדד -
או לכאות אם יקשו צד כרת או לראות אם יקשו מאשם.
** שכן ישנן -
(דמיו קצוב)
** ליתי תודה -
(בא מזכר ונקבה)
* יד.
** חוץ למקומו מנלן -
ואם תאמר נלמד משלמים בקל וחומר, שבמקום ששלא לשמו אינו פוסל, חוץ למקומו פוסל, קל וחומר המקום ששלא לשמו פוסל שחוץ למקומו יפסול. ויש לומר כמה חילוקים, כמו הנפה וחיוב כרת גבי חול"ז.
** מפתח אולם ולפנים -
הניח שאף שהוא עבודה שאי אפשר לבטלה, רק במקום שאי אפשר לבטלו עושה פיגול.
* טו.
** אפשר לתקונה -
או שכיון שהגיע למזבח, נחשב הוקרב, ואי אפשר לקרבו יותר, או שהקרבה הוא רק דבר המביאו להיות יותר קרוב למזבח ממה שהיה בכל עת.  יש כמובן נפקא מינא אם לא הקריבו כל צרכו עדיין. ותחשב.
גם אולי דן אם הקרבה של זר פוסלו או שצריך הקרבה של כשר, וכיון שיש כבר זה, אין בעיה אם יש עוד הקרבה על ידי זר.
** בהולכה רבתי -
לא הבנתי איך שייכים זה לזה, שעדיין יש לומר כמש"כ לעיל, שרבי שמעון סבר שכיון שיש זמנים שא"צ הולכה, אינו פוסל כלל. ויש לומר שרוצים שלא יחלקו בכל כך. לעיל, לא היה דבר שיחלקו בה חוץ מזה. ותו"ת.
** דפסולה בה מחשבה -
לא הבנתי, שבין כך ובין כך, לכאורה, זה יהיה קשה.
* טז.
** בקל וחומר (שני) -
ואז, צריך לומר שכשמסיק לעיל שנלמד זר מיושב וחד מהנך, אי אפשר שאותו אחד הוא אונן, שאם כן, כמובן, הוא מקור לעצמו. ותו"ת. לכאורה, ההוה אמינא ללמוד מאונן לא ידע או לא סבר כאותו מקור.
* טז:
** מפני אנינות נשרפה -
לא הבנתי למה אין זה מקור לחילולו. ושוב ראיתי ברש"י. עיין במה שאומר רש"י. לכאורה, רצה לומר שאומר שאולי הם הקריבוהו באיסור; ומוכיח שאסור ממה שיש שום נפקא מינא מי הביאו. עדיין מוזר למה ישאל משה על זה; אין נפקא מינא אחר שנעשה, ולכאורה, הוא לשון הרע. ויש לדון. אפשר לומר- ואולי כן כוונת רש"י- שאמר לו משה, “שמא הקריבו אותו בנך, ואתה סובר שאז נתחלל…" ותחשב.
** טמא יוכיח -
ואז, לכאורה, לא צריכים זר. אם כן, יש לומר שמי שדרש זר מזה (עיין לעיל) ידע מסקנא זה).
* יז.
** סוף סוף -
לא הבנתי למה אין אומרים כן גבי חד מחד.
* יח.
** אבל ייתור לא -
לכאורה, מדלא הקשה אם כן למה צריך קרא זה, שדלא כדלעיל יש בעיה זה בשניהם, ואז צריך שני קראי.
* יח:
** אחד זה ואחד זה פסולין - .
נמצא שהכשר מרושל הוא רק על ידי אבנט. וצריך ביאור מציאות זה
ואולי הוא שכיון שהוא puffy, אינו כל כך ארוך, וכשחוגר באבנט, מאריך אותו. ותו"ת. ושוב ראיתי בגמרא. ונראה שלכך כיוון באמר שעדיין ק’ על רב.
** שסילקן על ידי אבנט -
נמצא אם כן שאפשר ש"אחד זה ואחד זה" אפשר להיות לא רק מרושלים ומסולקים, אלא אף אולי יש לפרש שר"ל מסולקים בין באבנט בין בלי אבנט. ותחשב.
** ואידך האי אשר -
ועוד יש לומר שכאן הוא ייתור שאפקט את שאר הקרנות, שאו מרחק אותם, או משנה את הangle.
* כ.
** ולא בסוף עבודה -
לכאורה, היה אפשר לומר שראה דבריו מקרות גבר.
** לא פסלה לינה -
אולי היה אפשר לומר כמש"א בפשט שני שגזרו רבנן רק אם אינו עבודה של אותו יום.
* כב.
** אי הכי כלי חול -
לא הבנתי קושיא זה, שלמה נאמר שהקרא מרבה יותר מהכי מסתבר. ותחשב.
* כג.
** דיו
* כג:
** מכדי יושב כזר -
יש לדון אם רצה לומר שפוסל כמו זר, ולכן מסתמא שאר דיניו כדין זר או שר"ל שקרא דלעכב מסתמא קאי על קרא דאיסור שאומר שכזר הוא, ואז מסתמא הקמ"ל הוא שממש כזר לעבודה הוא (ולא שלאיסור ולפסול כזר, אבל לעונש, אינו כזר).
* כד.
** לדברי הכל אין מלמדים -
ק"ק, שבפשטות, אין לומדים מזה, אלא מדמיונו לזב (כן כתבתי, אבל נראה לי שאולי כוונתי היה לכתוב זר). (ונראה כצד ראשון שכתבנו לעיל, ואז הגמרא אומר שאין צריך שני קראי לומר שיש חיוב מיתה; נדע כן ממה שדומה לזב. ואם כן, ק"ק למה צריך תרי קראי (חד יהני) וצריך לומר שבלי חד קרא, לא הוה ידעינן לדמותו לזר).
** דאין דעתו לחברה -
בפשטות, רצה לומר אם דעתו לחברו כלל, נחשב כחבור.
אבל אין זה נראה, שבודאי מתקנים בית המקדש. ואולי יש לומר שמכוון לתקנו לאלתר. גם יש לומר שר"ל שדעתו בעמידתו עליו הוא לחברו קצת. ותו"ת.
* כד:
** במקרא… קמפלגי -
אם כן, נמצא שמה שאמר יד לאו דווקא הוא, והוה אפשר לומר אצבע. אפשר שלא רצה להיות מבלבל, שהרי נראה כמש"כ אצבע[fn:4]. ותו"ת.
** בדבר המעכב -
גם יש לומר שהוא רק בדבר שאי אפשר לבטל.
** ר"ש תרתי בעי -
לכאורה, הוה מצי להקשות כדלעיל מקמיצה.
** למה לי בכיהונם -
עדיין אינו מיושב לשון, “כל מקום שכ’ אצבע וכהונה,” שהרי אין "כהונה" נכון.
* כה.
** וקסבר גורעים -
ואם תאמר מה ראייה יש; דילמא שאני הכא שהוצרך לזה, כמש"כ גמרא. ויש לומר שהחידוש הוא שאין דורשים אותו כאות יתירה, אלא כך.
** והא בשיריים- אי אפשר שמקשה פשוט, שאם חייב לשפוך את כל הדם, לכאורה, חייה לקבלו (שחידוש גדול הוא לומר שצריכים שיריים, אבל אותם שיירים לא צריכים להיות להם קבלה). אלא נראה שמקשה שכיון שבשיריים כתיב, צריך להיות לאו דווקא. ועל זה תירץ גמרא שכיון שאין רוצים שיהיו לאו דווקא, אומרים, “אם אינו…."
* כו.
** פר שהיה כבר -
יש לדון אם הפסול הוא משום בעל מום- וקצת לא משמע כן מגמרא כאן- או משום שחלוק באופן חשוב ממה ששחט.
- כמובן, יש לדון למה אין אומרים ששחיטה עצמו הוא מום.
** הכניס… כאילו רובו -
עיין במה שפירש רש"י. ואין לפרש שר"ל שנחשב בדרום ופסול, שהרי אין פסול דרום, אלא הפסול הוא מה שאינו בצפון, לכאורה. ולכן, אף אי רק בדרום, פסול. ועוד נראה כן מהא דקק"ל.
* כז:
** כדברי האומר לא יאספנו -
ואז אפשר ששני הברייתות הם בציור אחד, וזה ר"י וזה ר"ש.
* כח:
** ולמעוטי נותר מכרת -
לכאורה, יש לומר שמסתמא קאי בנותר וממעט חוץ ממקומו, שחוץ למקומו הוא מה שאינו כל כך מפורש בקרא.
** דגמר עון עון -
לכאורה, היה אפשר לומר שהפשטות קודם. וחושב אני שיש דיון בזה בגמרא קידושין (ורשי ותוס’ שם) בבא זה וגלה על זה. ועיין שם. ותחשב.
* כט:
** לא יחשב מאי עביד ליה -
עדיין אינו מבאר מה היה דורש בו אם היה קאי בנותר, ואולי אף שם לדרוש שחייב כרת רק כשלא חשב שום מחשבות רעות.
* ל.
** שני שמות כאחד -
אין להקשות שהרי יכול לעשות דבר תמורת עולה ותמורת שלמים למשל באמירת לחצות כספק דלקמן, ואז אפשר לאומרם בבת אחת, שאין זה אומר שיש שום סברת מאי הוה ליה לעשות, אלא שמתוך שאי אפשר לומר שניהם בבת אחת, הבנת שניהם זה עם זה הרי הוא שניהם בבת אחת. כיון שאין דרך קל לומר שניהם בבת אחת, כן הואר  ההבנה. ותו"ת.
** בהא וודאי -
עיין לקמן (ע"ב) שמוכרח שעל שניהם קאי.
** הרי שחיטה… ופליגי -
יש לחלק טובא שרבי מאיר סבר שעולה לא יחול שנתפשט. ועכשיו, יש לגמרא הוא אמינא שלא נתפשט כיון שאומר לחצות. אבל ר"י סבר שכיון שחשב על זמן, נתחייב, שכבר נפסל בפסול זמן. זה בודאי נכון, שהרי "חציו" זמן, ואין צריך שום התפשטות. וצ"ב. ותחשב.
* לא:
** בשני בני אדם מצטרף -
ק"ק שיש לדחות שר"ל אכילה והקטרה של מזבח.
** הקטרה ביותר מכדי -
ועוד לכאורה יש לדחות שאין הא דיותר מכדא"פ דווקא, אלא הדווקא הוא כל אחד בזמנו.ויש לדון אי הוה מצרף וצ’ כדי אכילת פרס, אם היה זה שמשהה יותר בקודש מעכב או לא, שאולי אין זה פסול בקדש[fn:5]. ותחשב על זה.
* לב.
** מתני איפכא -
אם כן, משנתינו קשה. ולכאורה, סבר שחולקים.
* לג.
** בטמאים נמי משכחת לה -
יש לומר שאכתי מדרבנן אינו נמצא (וכמו שחיטה לפי משנתינו).
* לה.
** דאמר אין דם מבטל דם -
צריך אש ראשון, שבלי זה, לא יהיה מין במינו. ותו"ת.
* לה:
** אלא איידי דבעי -
ק"ק אם כן למה צריך הא דרישא (רצה לומר, נכתוב רק בסיפא).
** דכמאן דקדם -
צריך ביאור למה לא אמר שקדם מומה את הקדשה.
* לו.
** בעינן מקום -
צריך ביאור למה אין זה בניתנים בפנים שנתן בפנים.
* לו:
** זרק ומיחזי -
או רצה לומר שחלק ממחשבתו הוא התירתה או שהוא אסור שאפשר להתירו.
** וחייבים עליו כרת -
יש בזה שני חידושים:
1. אינו חצי מכפר. (ויש לדון בדין חצי מכפר:
  1. צריך לחשוב בעשיית מלאכה חשובה. חצי מכפר אינו חשוב.
  2. צריך שמחמת הפיגול הקרבן יהיה מחוסר עבודה (שאם לאו זה, לא הרע כל כך שלא עשה אותו משלם למחוסר עבודה).
  3. לכאורה, מגמרא שלנו נראה כצד ראשון, שאי לצד שני, אינו מחוסר עבודה, שעדיין יש שני. ויש לדחות שעדיין נדחה שאר הדם מכפרה, ואי אפשר לכפר. ויש לדון אם נדחה אם נתפגל. ויש לדון איך יודעים שהאחרים אינם מתכפרים. ויש לומר שסברה הוא (ועוד יש לומר שכן נלמד מלשון שפיכה, שמשמע שכולו נשפך, ולא זריקה).
2. אינו "פסול אחר בו.”
* לז.
** רבי אומר -
ואם תאמר עדיין קשה לתנא של ברייתא. ויש לומר שאינו מוכרח שהברייתא נכונה, ורק רצה להביא דין, ולרווחא נקט ברייתא שאומר כן (ובפרט, כיון שמביא קרא). עוד יש לומר שדרך ברייתא לנקוט קראי שנרים שלומדים ממנו, אף אם , באמת, אין לומדים ממנו (וכמו שמצינו, “מקמי גזרה שווה").
** דם זבחיך… כריה"ג -
נמצא אם כן לר"י שצריך לשלשה דברים:
1. שרק צריך מתנה אחת (ואולי חולק)
2. שפיכה מכפרת
3. שפסח ומעשר צריך מתן דמים. ועיין בגמרא.
* לז:
** גמר עברה עברה -
ק"ק למה א"א ללמוד דין דמן מזה. וי"ל שמעשר לאו דווקא. (וכיון שנלמד פסח מעשר נלמד ממילא).
** כבית הלל -
אם כן, נמצא שרבי עקיבה כבית שמאי[fn:6]. ולכאורה, סבר שלא חלה. וכיון שהגעתי ללח. ראיתי שיש תנא הסובר שאי אפשר ללמדו מחטאת. ואולי כן סבר רבי עקיבה.
** כפרה בכדי לא מכפרא -
קשה; נימא כלם לעיכובא. ויש לומר שאז א"צ קרא (ויש לדון, שלא שנה עליו לעכב. ואולי סברה זה של גמרא יאמר שמעכב. ודחוק.). וק’ נימא שנים לעיכובא או שלש (ובפרט לשיטות שסובים שכלל של "לחומרא מקשינן" שייך בכל לימודין. ויש לדון אם יכולים לומר שתפסת מועט תפסת (זה, לכאורה, יותר שייך אם לא נניח שהכל מעכב בלי קרא). ותחשב.
יש לדון מה לבית הלל אם היה נכתב רק חד.
* לח.
** ארבעים ותרין -
יש לחלק ששם הוא קרא אחת, ואין לומר על קרא אחד מסורת ומקרא, אלא יש לחלק שיש מן הקראי כזה,ויש כזה.
** וטמאה -
קשה למה לא אמר כן לראיה אם לדרוש מקרא או מסורת. וחושב אני שבמקום אחר מקשה כמו כן. ותחשב.
** אלא למטה -
צריך ביאור למה לא אמר שלש למטה ואחת למעלה. שו"ר בגמרא. צריך ביאור בהוה אמינא.
* לט:
** מצוה ידועה -
וזה חידוש, שהוה אמינא שדומה לפר כהן משיח (האמור בעליונה).
* מ.
** מתן ארבע נמי לא -
צריך ביאור למה אין הוה אמינא זה בשבע.
** מתקיף לה רב פפא -
אם כן, לר"י נמצא רישא ר"ש וסיפא ר"י. לר"ש צריך כדי ליתן שני מתנות.
* מא:
** ואי טעמא דרבי מאיר -
יש לדחות שכולי לעמא מודו שבתר ראשון אזלינן, וברייתא דלעיל בשלא כיוון פיגול על ראשון, וחולקים בחצי מתיר לחוד.
** תנא נמי סיפא -
לכאורה, רצה לומר תנא נמי סיפא חוץ למקומו, שהרי תני פסול מפני שכן הוא הדין.
* מג:
** קומץ דמיפרת -
וזה גם כן מבאר למה נקט קומץ בדווקא.
* מד.
** נאכלים לשני ימים ולילה אחד -
צריך לבאר למה זה סיבה שיהיה לו דין פיגול. נראה שהוא סיבה להקל ולומר שקצת מרצה. יש לדון מה יהיה אם שאר קרבנות לא יפלגו:
1. ירצה לפיגולם, אלא שלא יתחייב כרת (שרק שלמים המתפגלים חייבים כרת).
2. לא ירצה לפיגולם[fn:7].
מש"כ נ’ לשני.
עיין במש"כ, “שהן טעונים סמיכה" ונראה שיש לפרוך בשני ענינים שלעיל (לקולא ולחומרא). ותו"ת.
** לא נהנים ולא מועלים -
לא הבנתי כל כך למה אי אפשר שלרבנן הזאה מתירו.
* מד:
** על המזבח החיצון -
אינו רצה לומר כר"ש שלעיל, שאם כן, אין לשון, “מאי קרא"נכון, שאינו קרי על הדין דלעיל. אלא נראה שר"ל שבשלמים מעשיו ומח’ בחוץ, ולכן בכל מ’ מעשים ומח’ במקום אחד.
** הלכה כרבי -
צריך ביאור מי חולק. ואולי כמו שיכול לומר הלכה בלי צורך (שהוא הלכה למשיחא), יכול לומר הלכה בלי חולק (כמו שאומר רבה, נגד אביי.) יש לדון, שאביי כאן הוא האומר שיכול לומר הלכה למשיחא, אף שאין צורך. ויש לדון, שאף הוא לא מודה שיאמר לשון הלכה, והרי ר"נ אומר אותו לשון. ותו"ת.
* מו:
** כמחלקת בזו כך מחלקת בזו -
על פי זה, יש לומר שלזה צריך קרא שלישי (ואם כן, צ"ב מקור לפנימי).
* מח:
** ה"נ מדורות לא גמרינן -
י"ל שהוה אמינא שהקמ"ל דקרא הוא שלומדים.
** הבאה מכוח עולה… -
ואי אפשר ללמוד ממה שלימוד עיכוב בחטאת בא מעולה, ושאי אפשר ללומדו אי לאו שיש דין זה בעולה, שיש לומר ש"אם אינו ענין" תני.
** ואילו איהו חיילא -
לכאורה, אף כאן יש לומר שזה מפני שאינו קדוש כל כך, ואין קדושה סותר מן המום כל כך.
* מט:
** מהו שילמד בג"ש -
אינו ראיה לאי היקש יותר חזק או לא, שאם הוה היקש יותר חזק, יש לומר שכאן יותר מסתבר שיהא לו כוח קלוש, ואז אי אפשר ללמוד באופן חזק, אבל אולי אפשר באופן יותר קל כמו גזרה שווה או שלעולם באופן יותר חזק נ’ שילמד, אבל הורע כוח היקש דבא מהיקש ואינו כל כך חזק כיון שמכפלים היקש. ואם היקש יותר קל, יש לומר שיש צד שגזרה שווה ילמד שיותר חזק או של עוללם היותר קל ילמד והיקש כיון שכבו הוקש דין זה לא יתריע לימוד בעוד היקוש. ותחשב. וזה נראה.
* נ.
** אשם… ותיתי מהנך -
ואם תאמר מהו לטעמיך; הא אין תלויים אהדדי כלל. ויש לומר שקאי על צד השווה, שאם נלמד היה נחשב נלמד נלמד מעולה (וחטאת רק מגלה שזה לימוד טוב). ועיין באחרונים שדנו בזה[fn:8]. ואז, מוכרח שאי אפשר ללמדו מצד השווה. ואז, מוכרח שאי אפשר ללמדו מחטאת. ותח’.
* נב:
** ואליבא דר"י -
לכאורה, אז כמו שיש ברייתא לסייע לר"פ, יש תנא שמסייע למד אחר. ותו"ת.
* נג.
** המימנת שבימין -
או רצה לומר היותר לימין כשכפיו למעלה (ואינו חושב גודל שאינו יחד עם שאר אצבעותיו) או רצה לומר האצבע שיותר רגיל בו, כמו שרגיל יותר בימין (כמו כן אומר גמרא כמה פעמים כשמביא דרשת רבא של המיומנת שבירך). ותחשב.
* נד:
** ועל דבר זה נתקנא -
לכאורה, הענין הוא שאם לא היה מעלת שניהם, לא מהני. קשה, שאם גמירי כן, מוכרחים כן. גם קשה, שאם דורשים כן, אין צריכים ועוד לקרא. ויש לומר שמוכיח לדרוש כן. גם יש לומר שקרא לא מבאר מקומו, ורק יש רצה לומר שיש מעלה בדמיון לקרא (וזה סימה, ולא סימן). וצריך ביאור. גם אפשר שקרא לא היה חלק מחשבונם, וגמרא אומר אותו. צריך ביאור, שאם כן, גמרא חולק על דוד ושמואל.
(יש לומר שרק היה מעלה במה שלא יתפלגו טובא, אבל אין זה מוכח. ותו"ת. ועיין לשון רש"י ש"אינן בעינן….”)
* נה.
** לזכרי כהונה -
צ"ב ל"ל נל’ מדין קק"ד. ויל"ד.
* נה:
** אמר רב אשי -
מעניין שהיו אמוראי א"י שהיו יודעים באחרונים כמו רב אשי. משמע שאולי היו שני רב אשיים. (ועיין במקום אחר (זבחים, לכאורה), שדנינו בזה בשיח שי.)
* נו.
** תני נמי אין חייבים -
וק"ק אם כן הא דר"נ מוכרח שחולק על זה (ואם אין זה בעיה מה לנו לחלק אכילה לשחיטה).
* נז.
** וחזה ושוק של תודה -
לכוארה, היה אפשר להקשות כן גם כן לעיל, שגם זה קדשים קלים.
* סה.
** כהן ומלק -
לכאורה, אפשר לו לומר שהוה אמינא שכשר בין כך ובין כך, וצריך קרא לרבות שצריך כהן, ולא כשר בכלי. ומשמע שהיה פשוט שרק אחד כשר. ואם כן, קשה למה כלי נחשב לחומרא. (ובפ’ הוא שאין בהמה כשר בגוף של כהן.) ועוד יש לומר שאין הכי נמי; אין מקור שיש רק אחד, אלא שלמעשה, אם לא היה לנו שום מקור, היינו דורשים אותו קל וחומר (ואף בלי קל וחומר, צריך קרא כדמפרש).
* סה:
** לא מעכב -
יש לדון אם רצה לומר שצריך שלא למצה. (ולכאורה, כן מוכרח, שהרי יש חילוק אחר בדין- זה אין הבדלתו מעכב.)
* סו.
** ולא יכסנו -
ק"ק, שיש לחלק טובא, שאין זה אפשר להיות צווי, לכאורה.
* סח:
** שמאל -
ואף שדין זה במשנה, נראה שבא לומר, “אף ש…" ועיין ביד בקידושין במק’ במלוה. גם יש לומר שהיה רב כולל את הדינים לסכם אותם. ותחשב.
* סט.
** לאתויי שחיטת קדשים -
ק"ק שתני בהדיא. ואין לומר שתני והדר מפרש, שכאן מפרש קודם.
* עד.
** וספק ספיקא -
לכאורה, יותר מחודש כאן, שיש רוב גם כן נגד הספק.
** ומשלשה למקום אחד -
לא הבנתי, שאם מתיר בס"ס, איך אוסר השלשה לפני יציאתה, שלכאורה, כבר יש ס"ס. ותחשב.
* עד:
** מעת לעת -
ק’ נבדק בזה ונשהה.
* עה:
** מה שקנו לו -
מעניין מה שמניח גמרא שזה חלק מן הקנין.
* עו.
** איערובי מערב -
ק’ אכתי על אותו פורתא יש תקנה. ויש לומר שמשנה על אותו פורתא לא מיירי.
* עז.
** נרבע -
לא הבנתי למה אי אפשר לחשבם עצים. ואולי לכולי עלמא מאוס.
* עח:
** יין לבן -
מעניין שזה נחשב מין במינו.
* פ.
** אלא כשהוא בעצמו -
נראה שגמרא בהוה אמינא חשב שבל תגרע (וכעין זה) הוא כשמגרע בדווקא. ולמסקנא, סובר שכאן כיון שאין דעתו אינו גירוע על זה, אלא על אחר, אינו עובר. ותחשב.
** אחד אחד לא -
וכן מדוקדק ממה שאמר כוס בכוסות, ולא כוס בכוס.
** דאיתעביד ביה -
צריך ביאור למה זה יותר צד להביא את האחרים (נאמר להיפך, שכיון שאינו טועים בכפרה, אין כל כך צורך להביאו). ויש לומר שכיון שכבר נתכפר, קנאו מזבח יותר, ויותר חייב לבעלותו. גם יש לומר שאינו עושה כל כך, ואז אינו כל כך רע אם הוא פסול. ותחשב.
** שני הזאות -
עיין בתוס’. וצריך ביאור, שלכאורה, אף אי יכולים לתלות היוצא בפסול, אכתי צריך להזות עוד שנים, ויצתטרך שלשה.
** אין צריכה שיעור -
צריך לבאר מהו החילוק.
* פ:
** לשם שיריים -
צריך ביאור איזה חידוש יש בזה.
** לשם שיריים -
ק"ק, שהרי הם שיריים שלאחר זריקה.
* פא.
** בנתערב באחת -
ק"ק למה א"א שנתערב ארבע בארבע, ולר"א, שאין בילה, נמצא כולו על מזבח, ולר"י בילה. ואולי אם כן, היה טוען רבי אליעזר לרבי יהושע כן (שאין בילה).
** מקום שיריים -
היה אפשר לומר שזה רבי אליעזר (ואולי אם כן, לא היינו צריכים קרא).
* פא:
** אפילו למ"ד -
עוד הוה אפשר לומר דלמא קמ"ל שלהלכה אינם מעכבים. (או שקמ"ל שהל’ כר"ש או ר"י. וזה אולי אין לומר, שאינו מסתבר שידחוק כדי שההל’ או כזה או כזה.)
* פב:
** אמר רבא -
נראה לי שני דרכים לפרש את הדרשה:
1. מדמנה קודש ופנים לחוד, משמע שחלוקים הם לענין כמה דרשות, והוא שאם חישב על זה, הכנסה לאחר לא יפסל אותו.
2. מדכתיב שניהם, ואי אפשר להעמידה חוץ מבא זה וגילה על זה, מוכרח שהוא בציור אפשרי, ואז מגלה לנו קראי שבהכנסה להיכל לא נפסל אם חישב לקדש.
נראה שיש נפקא מינא בין אלו אם ימצא פשט אחר בדרשה (שלשני, ולא לראשון, יהיה קשה.)
** כל היכא -
לפי צד זה, כל שקלא וטריא של גמרא שלעיל קשה. ולפי הצד האחר, יש לומר כפשט ראשון, ולומר שנצרך לציור כזה.
* פד.
** [- מצינו בק’
ששניהם דורשים
- אין סברה חיצונה בקדשים.]
* פז.
** לשלחן -
ק’; בעזרה היא, ואיך יהיה לינה.
* פח.
** בקניא -
לא הבנתי כל כך מציאות אם עדיין בראש מזבח איך יזה למטה.
* פח:
** שאין עניות -
יש לדון על מה זה קאי. [שוב כתבתי: צריך ביאור מה היתה כוונתי בזה, שיש דבר אחד שמותר שיש לחלוק עליו לאוסרו. ונראה שאולי חולקים מה טעם. ויש לדון מהו הטעם בלי זה. שוב הבנתי, שלכאורה, כוונתי לא לדון על מה אמרו יש אומרים, אלא על מה נאמר על אותו טעם. ותו"ת.]
** על קול הרע -
ק"ק, שיש עוד דברים התלויים בקול, כמו מגדף.
** ויכפר על קול -
וז, יש לומר שמה שמוצאי קול הוא כנגד מראות נגעים, ואז מה שהביא לעיל אולי אינו רק סימן, אלא הוא ממש לשיטתם. ותו"ת.
** מקטרת -
מעניין שלא נקרא קרבן.
** ויתן… ויכפר -
יש להעיר ששם אינו על לשון הרע.
- יש לדון אם "קול פעמונים" מבאר מהו הקול (קשה, שהוה ליה לומר כן לעיל) או שאומר שהקול, ולא הבגד, הוא מה שמכפר. ודע שיש לדון אם הוא בדרך כלל היות החפת או מצות או טוב של לבישתו. אולי שיך לזה גמרא יוצר גבי ציץ כשאינו על מצח אברון )(ז:).
* פט.
** דילמא תמידים -
אפשר שר"ל שאינו רק מפני שיותר תדירים, אלא מפני שהם תמיד בכל זמן (שמה שקורב ביום נחשב כבכל היום, כשיטת רבי יוסי במנחות. ותחשב.
** שהוא בא -
ק"ק למה שינה מלשונו שאמר גבי חטאת. ועיין בגמרא לקמן (ובשיח שי).
* פט:
** צריך ביאור
למה אין אומרים בזה אין מעבירים על המצוות. צריך לומר שהוה אמינא שנדחה מחמת זה.
** בחטאת הלווים -
צריך ביאור אם הענין הוא שיש שם חטאת למה צריך למור רק בשל לוויים. ואולי רצה לומר, “אף בקרבן לויים.”
* צא.
** שאינו תדיר -
זה חידוש, שנעשה יותר, אלא שאינו נעשה ביותר ימים.
* צב.
** ושקיבלו -
מעניין מה שמפרש מה נחשב פסולו בקדש כאן, כיון שכאן אין חילוק, ומה לנו מה נחשב מה. זה מניח שכל פסולים בכלל כל אלו, והיה אפשר לדון, ולומר שרולי יש סוג יוצר כשרים מזה, ותחשב מבו. אולי מבאר שאלו אינם בכל אותו סוג (ואולי זה עושה שאין שום סוג כזה).
** תשחט -
צריך ביאור למה למסקנא צריך קרא זה.
* צב:
** יאכלנו -
צריך ביאור למה לא אומר כתירוץ גמרא שלעיל. ויש לומר שהא דנאכל יותר חשוב שעיקר קרא בנאכלים. וזה נגד רבא.
* צג:
** ואיבעיא -
לכאורה, הגורס וי"ו גורסו כיון שכל השקלא וטריא נצרך למה שאומר גמרא כאן. יש להעיר שלא לעולם אומר וי"ו בכעין זה, שיש לציין למה שהעיר לי א.מ.ו. שבב"ב (יש נוחלים) במחלקת רבה ורב נחמן לשיטת תוס’ קאי גמרא על מסקנא, ולא אומר וי"ו (הוא בקכד: או קרוב לו).
** כתב רחמנא וטבל -
יש לדון מה היינו דורשים, אז, מ"הדם.” י"ל שצריך שיעור, אבל א"צ לעשות כן.
* צה.
** משלש על שלש -
זה חידוש, שהוה אמינא שכיון שיותר על ג על ג הוא, כולו טמא. יש להעיר שאין צריכים ליגע ביותר משלש על שלש כדי לטמא. ותחשב. ואפשר שכמו שיש חילוק, אולי, בין מגע להכנסה לענין ביאה בבית המקדש, אולי יש חילוק אף לזה. ותו"ת.
* צז:
** יכול נגע -
צריך ביאור מה הוא זה.
** ולידחי -
צירך ביאור למה לא אומר כן בכל פסול. (ולולי ק’ גמרא, הייתי אומר שעשה בטל.)
ועיין במה שכתבנו על תוס’ כאן. נראה שאם נאמר כן, פשוט למה הוא רק בתערובת. ועיין שם. ותחשב. וקושיא זה סמך לומר כמו שכתבנו שם.
** אלא… גופא -
ק"ק למה לא מק’ כן גבי נאכל לזכרי כהונה.
* צט:
** שהרי אמרו -
אם כן, אין רואים שאוכל, שהוא רק אנינות דרבנן.
** דברי ר"י -
אז, היה אפשר לומר שזה רבי יהודה וזה רבי שמעון.
** ותנא שלמים -
ק’; שהניחא פסח יש לומר שהוא חלוק לאכילה כיון שיש עוד מצוה לאכלו, אבל קשה למה נחלק בשליחות קרבן. ואולי הוא מפני שפסח הוא כל כך חשוב, ויש בו כרת. גם אפשר שמה שאינו נאכל הוא חלק ממה שאין שולחים אותו. ותחשב.
** פסח כדי נסבא -
נמצא שאומר כדי נסבא דבר שאינו נכון. עיין בקידושין (ה:). וש לדון אם שם הבעיה הוא שאינו נכון או שיש בו סתירה. מגמרא כאן, נראה כצד שני. עיין ברש"י שם (בקנטרס"ט שאומר) שקצת משמע כראשון. וצ"ב.
* ק.
** מילת זכריו -
משמע שאם לא מל מחמת אונס, עדיין לא יכול לאכול. אם כן, דיון של גמרא בהערל לענין ערל קודם זמנו יהיה שייך כאן. יש לדון, שאולי אין כאן אונס, שהיה לו לעשותו קודם (ומיירי באותו ציור שיכול לעשותו קודם). יש לדון, שדנים בכעין זה בתפלת תשלומים אם נחשב אונס. ויש לדון, שאולי אין מה שנחשב אונס שווה לכל. ותחשב.
* קא:
** לימא -
הוה ליה להקשות עוד מה יתרץ לזה.
* קב.
** דאהרן ובניו -
ק"ק איך היה ה’ כשר לו, אז. ותחשב. ונראה שאי אפשר שיהיה דבר באהרן שיכשיר שלא יהיה בה’.
* קג.
** עולת אשה -
שהוה אמינא ש"עולת איש" דווקא, ולא "עולת אשה.” ויש שלש דרכים לפרש את זה:
1. כיון שהביא קרא שאפשר לטעות בענין זה מפני דקדוק לשונו, מבאר שלא לטעות.
2. אחר שהביא שהקרא שאפשר לטעות ממנו ממש דוקא, ואז יותר יש לטעות, מבאר שלא לטעות.
3. מבאר גמרא שאיש דווקא, וממעט שום דווקא, ומבאר גמרא שבא למעט זה ולא זה (ונמצא שדין אשה סיבה לדין עולה פסולה).[fn:9]
4. לא נראה כן, שממעטים צבור וגר. ויש לומר שתנא שלנו חולק.
5. ועיין בגמרא, שנראה כמש"כ.
** ה"נ -
נמצא, לכאורה, אם כן, שני מיעוטים.
* קה.
** אלא רבי אליעזר -
מקרא זה רק מוכיחים שצ’ חזרה כדי לטמא. וצריך ביאור, אז, מהו ראיית גמרא מזה. ואין לומר שר"ל שהקרא אומר שבחזרה נטמא, שבפשטות, זה אומר אחר שנשרף. וחותר הבנתי פירוש תוס’.
* קו:
- אין עונשים ומזהירים מן הדין.
* קטז.
** על הפשט
הראשון בטמאים, צריך לומר שכשנקט שנים ממין טמאים, רצה לומר מין שלא היו בו אלא טמאים.
** תנאי (שלמים)
וק’ שקרא הביא.
* קיח.
** ליבעי קידוש -
יש לדון אם רצה לומר רק או אף.
* קכ:
** מה לעוף -
ק"ק, שיש לעוף יוצא.
* Footnotes
[fn:1] איני מבין כל כך מה כתבתי. ותחשב.
[fn:2] איני יודע מה אומר כמה מזה. צריך לחזור עליו.
[fn:3] איני מבין כלל מה זה אומר.
[fn:4] כן כתבתי, אבל נראה שכוונתי היה לומר כאן יד. ותו"ת.
[fn:5] כוונתי בזה היה לדון, לפי הצד שמצטרפים הקטרה ואכילה ולפי הצד שאין צריכים להקטרה כדי אכילת פרס, מה שיעור לצירוף, שאולי יוכל להיות יותר מכדי אכילת פרס. ותחשב.
[fn:6] יש לציין לרש"י ביבמות (חושב אני שהוא שם או בב"מ, והוא גבי משנה שבו אומר ר"ע, “בזה אני כמוחזק" בבבא בתרא) אומר שרבי עקיבה היה תלמיד של בית שמאי. ועיין שם.
[fn:7] נראה שדנתי כאן אם ירצו לפיגולם או לא ירצו כלל. לכאורה, יש גם כן צד שירצו, ולא יהיה שום פסול.
[fn:8] שייך הוא למתי אומרים דיו בצד השווה (שייך לב"ק וקידושין). ועיין במרגנליא, שחושב אני שדנינו בזה. ועיין שם.
[fn:9] נראה שכוונתי בזה הוא לומר שהענין הוא שדין זה שייך לדין אחר שאמור כאן, ששייך לדין שלומד כיון שאין לומדים למעט אותו. ותו"ת. ואיני יודע אם כן כוונתי, שאז לא אבין מה שכתבתי בשורה שלאחריו. ותחשב.
