* ב.
** הנשחטין -
בי”ד- זה מחודש, שהוה אמינא שכיון שמכוון לפסח, מה לנו זמנו.
* ט.
** למילקא -
מה עשה רע; לא החליף, אלא הביא בק’ כזה?[fn:1]
** למאי -
לכאורה, תוס’ זה ותוד"ה אי נמי סותרים זה את זה (תירוץ סמיכה מהני  לשחיטה).
* י.
** השתא מיהת -
אכתי להוה סימן
- אין מגלים מזה לזה
- אינו סימן
* יא.
** אם כן -
ק"ק, שלכאורה, הוא חומרת פסח שעליו חושב. ותחשב.
* יא:
** צריך לומר ראב"ע
(בהגהות שבתחתית הדף)- ואין לומר ביום שהושיב ר"א לבית המדרש אחר חרמו, שהרי לא התירו החרם עד לאחר מיתה.
* יד.
** חוץ -
ועוד שאולי אין מה שיש כרת דרגא יתירה דפסולו אלא ענין אחר. ואם כן, אף בלי דיו, אי אפשר ללמדו, שמאיזה דין נראה שהוא "חמור.”
* טז.
** אונן -
דפסול- נראה שבא לומר שלא שואל מחמת מה שלומד ממנו מקל וחומר, שאם כן, היה לו להביא בעל מום קודם. ויש לדון. והיה אפשר לומר שלא בא אגב קל וחומר, אלא להוכיח על קל וחומר, כמו שכתבנו בשיח שי על גמרא, והוא שממה שנלמד מזר, אי אפשר שהוא המלמד לזה. אז, גמרא מבאר קל וחומר שלעיל.
על כל פנים, מה שמביא קטע של משנה לפניו משמע כמו שאומר רש"י.
* כד:
** (המעכב כפרה) -
מרש"י משמע שהוא מדמיון למצורע. ונראה שיש ב‘ דרכים לבאר את זה:
1. אין דנים גזרה שווה בכל מקום שנאמר מילה זה, אלא צריך שהשני מקומות יהיו שווים. ואולי זה ממש חלק מן הגזרה שווה הוא אותו מילה באותו קנטקס"ט, שהוא חלוק מבקנטקס"ט אחר.
2. כל דין מצורע הוא דין עיכוב, ואז ממילא הוא אסור. צריך לחדש או שדין הנכ’ הוא העיכוב ורק לומדים ממה שכתוב או שדין הוא העיכוב וסיבת האיסור הוא שאסור לעכבו (ולא שרע לעשות כן), ואז אי אפשר ללמדו לדבר שאינו מעכב. ותחשב.
* לו.
** תרי קראי -
צריך ביאור איזה לא נכתב:
אם לא נכתב הא דתודה, הוה אמינא שדין זה רק בפסח, שמחשבה פוסלת. ויש לדחות שאין מחשבה שייכת לכאן. אם לא נכתב הא דפסח, אולי הוה אמינא שכמו דפסח נשתנה לשלמים אם אינו בזמנו, כך נעשה כשאין זמן אכילתו נכון. ותחשב.
* לו:
** אמר רבא תדע -
מחשבת הינוח- לא הבנתי מה אומר, שמחשבתו עדיין לזרוק לאחר זמן.  ואולי זהו דחוי גמרא (אבל פשוטו הוא שדחייתו הוא שלא נשתנה מחשבתו כלל, ולכן אין כוח בראשון לפסול את השני או שבטל הראשון בביאת שני. ותו"ת.)
* מה.
** הלכה קאמינא -
צריך ביאור לרש"י מהו החילוק.
* נד.
** מלבן
- וכל אחת ארוכה- צריך להיות קצת יותר מזה, שצריך להיות שמה שבתוכן כן, ואז אם הלב’ אמות הם זה:          , אז, יהיה צירך להיות כזה:            ורק נוגעים בקרנות. רק אז היה אפשר להיות נקרא לב אמות אף על החיצון, אבל היה יותר קל, לכאורה, לעשות רחב יותר בחוץ, שאז יותר קל לחברו. ותו"ת.
* נה.
** קדשין קלים -
היה אפשר לומר שאינו אומר בזה דין, אלא שאין קדושתם כל כך גדול. ותו"ת. גם ק"ק לל באר כן רש"י על לעיל (קק"ד). ותחשב.
* נה:
** וחד להכשיר צדדים -
לולי רש"י, היה נראה לומר שמכשיר צדדים חוץ מצפון. יש לדון לרש"י איך אלו ידועים. אי אפשר להיות ממה שלא פי’, שאם כן, נלמד צפון מזה. (ואינו קשה למה שכתבנו, שלמש"כ, אומר שנאמר קרא לצפון, ולא לצדדים. ויש לדון, שא"כ מ"מ הוא, ולא קו"ח. ותחשב.)
* נו.
** מדרבנן -
לא מזכיר מה שאין איסור דאורייתא כיון שאין בו כל כך נפקא מינא ועוד שגמרא רק דן בעונש (קרבן וחיוב). ותח’.
* נז.
** אין מלמדים -
עיין בקדושין לד:. וצריך ביאור. (שו"ר שבהל"ע כ’ לתרץ שנלמודד טף, והוה כנכתב, ואז נלמד נשים בקל וחומר.) ואולי חלוק כאן כיון שכבר לימד דין זריקה.
ודע שזה מעניין, שלכאורה, יסוד שני כתובים הבאים כאחד הוא שמדצריך שניהם מוכרח שאין לומר דין מאחד. אבל כשיש גזרה שוה, לא הוה ילפינן הכל ממנו, ואין הקרא מגלה דלא כזה. ותע"ז.) וראיתי ביבין שמועה והליכות עולם, שדנים בזה.
* נז:
** כי התם -
צריך ביאור מה אומר ב"כי התם" אז, שלכאורה, הוא הוכחה אחרת, ועכ”פ, לגמרא שלנו, יש לומר שהוא אופן מוזר של ביאור הדין.
* סב.
** אמר רב יוסף -
משמע שהיה לשלמה לא הבינו. בפשטות, היה אפשר לומר שהבין לדרשו, אלא שלא הוצרך לזה, ולכן אוקמיה על פשיטותיה. ועיין ברש"י לקמן שכ’, “עד ששים אמה ראוי לו.”
הוה מוסיף לפ’ רבי יהודה.
* סח.
** בקצת נוסחאות
(ב[] בצד)- זה רק אפשר לר"י, ולא לרב.
* עד:
** לשון אחר…
שנים שנים- לא הבנתי שמיירי בשחד נפל, ואם כן, למכור תרי תרי, וצריך שלא יהא ק, שאם כן, לאחר נפילה, יהיה ד’ ולא חר נפילה שינית יהיה ג.
* פג.
** ודאי חד מקום -
עיין ברש"י. ועוד יש לפרש שכאן שעדיין עוסק בעבודתם, יחסים לעבודה שבפנים, וכשרים.
* פח.
** ליבש -
יש לדון איך שמן מקדשם. (ואולי רצה לומר שמחוברים בו.)
* צה:
** ואחד שעירה -
עוד יש לומר שקל  שזה ראיה שעיקר הוא אי הוה בלוע.
* צז:
** ניתי עשה
- מתחילת תוס’, נראה שאף לאחר זמנו יש אותו עשה ויש ס"ט, אלא שיש אף ס"ר. יש לדון אם זה משנה במסקנא, שאולי אינו אומר כן אלא מחמת שגמרא אומר כן (ויש לדון אם נניח שהוא דומה לפסול אחר שעליו אומר תוס’ שיש מצוה באכילתו). יש להעיר שבמשנה בברכות אומר, “כל הנאכלים ליום אחד, מצוותם עד שיעלה עמוד השחר.” משמע שהמצווה כלה אז. אולי רצה לומר שלמעשה אין חיוב כיון שאסור. ודחוק.
שוב הבנתי שלכאורה, הוא רק כאן שהוא תערובת, ואז יש בו ממה שיש בו מצוה. נמצא, אז, שבאכילת אותו חפץ יש מצווה. ויש לדון, שנחוש שיהיה לו חלק שיש בו רק מן האיסור (ויש לדון אם בציור זה, זה אפשר), ואז לא יהיה דוחה בעידנא (כמו שמצריך אב אשי בשבת). ותחשב על זה.
* ק:
** רבא אמר -
לכאורה, אינו מוכרח שרק על זה קאי.
* Footnotes
[fn:1] איני יודע מה אני מקשה, שלכאורה, שחטיה לשם תמורה לא רק רצה לומר שאמר שהוא תמורה, ולא המירו (למשל, לא אמר של מה (ויל"ד)), אלא שהמירו. אם כן, שפיר לקי. ויש לדון.
