* גיטין
* סז:
** בודקים -
עיין לשון רש"י. משמע שבודקים אותו לדעת אם הוא בדעתו או לא. הק’ א.ל.י. שצריך ביאור למה נניח שאינו בדעתו. אולי רצה לומר שאין דעתו מיושבת כיון שהוא עצב על מה שנעשה אלם. גם יש לומר שאולי כמו שנעשה אלם נעשה גם כן קצת שוטה (שחולי שגורם זה אולי יגרום זה). ויש לדון. גם יש לומר שרק לא מניחים כן באדם רגיל כיון שלא אמר לנו דבר. ויש לדון, שנניח כן מפני שהוא חזקתו.
** בודקים
- גם היה אפשר לומר שבודקים אותו לדעת אם מחשב לומר, “כן" כשעושה זה, שאולי רק שיי"ק.
** מיפף -
ק"ק, שביבמות אומר שלא לעשות כן מחמת שקר.
** שימשא -
יש לדון אם רצה לומר שהחולי היה לזמן מרובה או החום שגרמו היה לזמן מרובה. ותחשב.
** בעל חמש -
אין זה כל כך ראיה, שיש לומר ששחטו אותו בהמה, ולקחו ממנו רגל.
** שלש רגלים -
לכאורה, היו יכולים לומר שהיה כן. ולפעמים (אם הוא רגל הקצוץ, או אם קצוץ מארכובה), זה יעשנו טריפה, ואז לא היו יכולים לומר כן.
** שלש -
לכאורה, היה מי שאמר כן לו, שהיה סגי נהור, כמו שאומר לקמן.
* סח:
** כסא דכספא -
נראה שלמדו מיוסף.
** צריך ביאור
למה נתנו מחתלץ, שבין כך ובין כך לא היה רואה. אולי הוא כדי שלא יראה שמשו. ויש לדון, שהבין ר"ח. ואולי לא חשב שר"ח יבין (שהרי, רק ר"ח, ולא השמש הבין. ואולי אף ר"ח לא הבין, אלא באקראי ראה שכרו בור). היה אפשר לומר שנתנוהו שם כדי שיהיה סיבה לומר לו לילך שם, והוא שיאמרו לו ללכת על מחצלת. לא נראה, שלא ידע שהיה מחצלת עד שאמר לו שמשו. ויש לדון, שאולי אמר לו שמשו שיש רק מחצלת, ולא דבר אחר לירא ממנו.
** מה היא -
ראש- קשה, שאשמדאי המלך, והשיג את אלו להשיג לאשמדאי, ואז בהכרח אינם אשמדאי. ואולי ראש ומלך חלוק, ש,למשל, אלו היו הכי חזקים ואשמדאי היה המלך. ויש לדון.
** שידתא -
לכאורה, אומרים כן במקום שידתים (ולא רק זה, שקרא אומר שני דברים).
** יש לדון
למה מביא כל מעשה זה של אשמדאי. אולי הוא רק אגב הא דברורות. ותחשב.
** כי צחי -
צירך ביאור איך לא היה יכול למצוא שום מים במקום אחר.
** לאבני -
מסרטים- יש לדון למה יש בזה שום חסרון. ותחשב.
** כי חזיתיה -
קשה למה לא חוששים שיאבד שכרו (כמו גבי רויא).
** אמר ליה בניהו -
יש לדון למה שהה עד עכשיו. ואולי גמרא אומר מעשה זה שלא כסדר. יש לדון למה יעשה כן. ותחשב.
** סיפי -
ממני וא.ל.י. יצא שלכאורה, אומר לשון רבים כיון שצריך ליתן על כל צד כדי שכשיכנס וכשיצא יהיה באותו צד שכואב לו.
** תלת -
איני יודע אם רצה לומר שהוא באותו צד של גופו (והוא עומד), ונקט ראשו כיון שזהו הענין (מה שהוא כנגד ראשו הוא מה הסיבה שמרפא), או שאולי הוא רק כנגד ראשו (שהוא שוכב). ותחשב.
* סט.
** שברירי -
ק"ק למה לא אומר כמו שאומר גמרא פסחים (“שברירי ברירי…")
** מריאה -
יש להעיר שגמרא חולין ויבמות אומר שאין קרום שבריאה מהני. צריך לומר שיכול להיות דבר אחר שירפא את ריאתו.
** ליתבינהו -
אפשר שזה רק מפני שהוא קשור לכלב, וקשה לו לילך, ואז צריכים להביא לו.
** הב לי -
זה מוכיח שאין חיוויא אומר שהוא חי. ואולי אומר שהוא חיה (ולא בהמה). גם ראיתי שגמרא נדה (יט:) אומר צד שחי בא לאפוקי כחוש. אם כן, יש לומר כן כאן גם כן (שהוא בהמה בריא). וכן נראה מחולין (מז.). ותו"ת.
** לוי -
נמצא שהיו בני אדם באותו זמן עם אותו שם, אף שרק מצינו אותו פעם אחת בגמרא.
* סט:
** כי בשיל גווזא -
נראה שהוא מפני שאין כולו בתוכו (שמגיס בו), ואז נתבשל יותר לאט.
** אהלא
- צריך ביאור מה אומר שהוא תולעת שני, שזה לכאורה, בא מתולעת, ואז יהיה אסור לאכול.
** ואי לא -
מזה משמע שלא אומר שאי לא יכול, אלא אי לא מהני, שאותם חפצים נצרכים לזה. ויש לומר שאין לו תנור. ונראה שיש לדון אם צ"ל תנור בדווקא או אף כופח וכירה. אולי אם צ,ל תנור דווקא מתסבר שאין לו תנור.
** אי אית -
יש לדון אם אומר שידוע הרפואה או שמסתמא ישתה (שכל בני אדם אוהבים לשתות) ולא היה חולק (או שהיה נתרפא ממילא). לשון שלא היה שואל לך, ולא שלא היה חולה, משמע כצד ראשון. ויש לדון.
* ע.
** בישרא שמינא -
אם אין לו זמן לצוות לביתו, לכאורה, אין לו זמן לעשות בשר שמן. אם כן, לכאורה, צריך לומר שכבר יש לו. עוד, לכאורה, מעניין שבזמן אכילתו לא יכול לצוות לביתו.ף ואולי הוא כל כך חלש אז שרק יכול לאכול, ולא לצוות. ודחוק.
** תמרי -
לכאורה, רצה לומר שהוה אמינא שכיון שהוא טוב באופנים אלו, גם טוב באופן זה. גם יש לומר שהבעיה הוא שכיון שמלא הוא, אם יכעוס, יבקע (כמה שאומר גמרא לקמן). אז, יש לומר שהוה אמינא שכיון שאין אלו מפקנים, אין לחוש לזה כל כך כמו בשאר מאכלים. ויש לדון, שאולי אותו פינוק רק שייך לאיזה מאכל רוצה לאכול, ולא לכעס על דברים אחרים. ותחשב.
** ועייל -
יש לדון אם כל המשך זה אומר מה לעשות אחר שתייה או שאומר שהוא בתר אכילה ובתר זה….
** עד דמתסי -
יש לדון אם זה ממעט זמנו, מרבה זמנו, או עושה שניהם.
** יש להעיר
שלפעמים אומר רש"י ש"בונא" הוא מלא יד, ולפעמים אומר שהוא אגרוף. לכאורה, אלו שווים, אבל מוזר למה שינה לשונו. ויש לדון.
** בונא חמרא -
וא"ת איך יש מלא יד של יין כיון שהוא לח. ויש לומר שכך שיערו כוס. גם יש לומר שידו למעלה עד שיש לו בית קיבול. לשון אגרוף לא משמע כן. אמר א.ל.י. שאולי הוא מדה, ואומר שהוא אותו שיעור שאם היה יבש היה ממלא ידו.
** סומקא -
נראה שיש לציין לגמרא פסחים שאומר שיין אדום יותר טוב כיון שכתיב, “אל תרע יין כי יתאדם.”
** בנים ויתקים
- נראה שמה שרש"י צ"ל שהוא רק מאותו ביאה הוא מפני שהיה אפשר לדייק מלשון רבים שהוא כל בניו. ויש לדון, למעשה, למה אמר אותו לשון רבים.
** כל שקייני -
יש לדון אם רצה לומר שיש מהם שקבוע לו ג ימים… או שבכלם עושה שיעור אחד מאלו עד שנתרפא. ותחשב.
** מכחישים -
לכאורה, היה לו לאמר גם כן הקזה, שלכאורה, לכן הוו בניו ויתקים. ויש לדון. ואולי כיון שאין מקור מקרא, לא מזכירו.
** קרובים למיתה -
יש לדון מה זה:
1. אולי אומר שיותר עומדים למות מלחיות.
2. אולי אומר שמצבם יותר דומה למי שמת ללמי שחי.
* ע:
** שחט בו שנים -
צריך ביאור מהו הראיה לזה:
1. לכאורה, פשוט שיש לו דעת. יש לדון, שאולי הענין הוא שאי אפשר לכוון כיון שעומד למות. דוחה גמרא או שמכוון די או שאינו מי שאינו יכול לכוון, אלא שצערו דוחה אותו מכך, ואז אינו שוטה (זה מחדש ששוטה אינו רק מי שאינו יכול לחשב, אלא מי שיש לו דבר ספיסיפיק הגורם בעיה זה).
2. לכאורה, אם כן, אף לריש לקיש יפסול, שכן היה מתחילת מינוי שלחות. ויש לדון, שאולי אף חולקים לענין מינוי שלחות.
3. לכאורה, יודה ר"ל, שכאן אין רפואה.
וצירך ביאור.
** פרחס -
ואם תאמר למה לא אומרים כן בבהמה (שאם פרכס אחר שחיטה, יהיה נבלה). ויש לומר ששאני בהמה שלא בחר לפרכס, ונחשב כולו חלק ממעשה שחיטה (כמו מה שלא מביא דם למוחו). גם יש לומר שכיון שנשחט נחשב מת (כמו לענין אבר מן החי).
** אלא מעתה -
מקשה על מימרא שניה, ולא על תירוץ של גמרא.
* עא.
** אלא בפירי -
עיין בתוס’. ויש לומר שזה לא מצוי, והיה לו לדעת שרק בודקים אותו. ויש לדון, שאולי אז היה לנו לומר כן בכסות חמה. ותחשב. (ודע שמוזר מה שלא יודע שבודקים אותו, שאומר לנו לכתוב גט, ומיד שואלים אותו אם רוצה פרי.)
** כתב -
לכאורה, זה רק מכתב, שאם לאו הכי, היה לו לומר כמו שאמר משנה. גם נראה כן ממה שמשנה לא אמר דין של רב.
** אישתקל -
לכאורה, הוא אלף של תחילת מילה ראשונה, למד של סוף מילה ראשונה, ומם של תחילת מילה שניה.
** עדות
- עיין במה שאומר רש"י ששטר אין בו בעית עדות מכתב כיון שהוא אורחיה. זה מעניין; וצריך לחשוב על זה.
** ירושת
- צריך ביאור מה אומר, שאי אפשר להעביר נחלה מבכור. ויש לומר שר"ל שנותן לשאר בנים. ויש לדון, שלא ישווה בכור, אז, לכל הבנים. גם יש לדון למה לא אומר שהשווה בנים לו (שכך עשה). גם יש לומר שאולי סבר רש"י שיכול לסלק חלק פשיטות של בכור. זה דיון בראשונים ואחרונים.
** ירושת
- צריך ביאור למה לא אמר אח, וכריב"ב. אין לומר שלא ס"ל כוותיה, שלכאורה, דין בכור גם כן מיוסד על שיטתו.
צריך ביאור למה לא אמר רש"י (וזה יבאר למה נקט בכור, אולי) שהוא לענין דין יכיר (להכיר בכור, שיש אומרים שאי אפשר להכיר בן כיון שרק נאמן עליו כיון שהוא בנו, ורק יודעים שהוא בנו כיון שהוא נאמן עליו. ותו"ת.).
** תנאי -
יש לדון למה מניח שרשב"ג חולק.
** דידיה -
יש לדון אם רצה לומר הודאה או מתנה.
** כשם -
יש לדון למה לא אומר שיש נפק"מ לצד ביבמות שחרש עתים חלים עתים שוטה.
** שאני עדות -
כיון שמחדש גמרא שתנאי, אפשר שר"ש מכשירו לעדות, ואין דורשים שעדות צריך להיות מכתב. גם אפשר, אז, שכן אומר אותו ברייתא שמונה כל הדברים שבו נאמן. ותו"ת.
* עא:
** דחזינא -
נראה שר"ל שהיה אמינא כר"א ביבמות שלפעמים חריף ושזה אחד מהני זמנים. קמ"ל או שאין הל’ כר"א או שאין לסמוך שזה אחד מאותם זמנים. ותחשב. (וכל גמרא זה נ’ שצ"ל נגד ר"א, ואז, נראה כצד ראשון.)
* עב.
** ולא מיבעיא היכא דאמר -
צריך ביאור מהו תירוץ זה, שהרי למעשה לא אומר, “תנו,” והאיך נאמר "לא זו אף זו" אם לא נאמר הזו השני. ותחשב.
* עב:
** ולדברי ר"י -
עיין במה שמשמע שחלק מן החידוש הוא שכן אמר ר"י. יש לדון, שכבר אומרים כן ממה שהביא גמרא לעיל.
** ר"י מאי היא
- נראה שידע שלא שאל מהו ברייתא שממנו יודעים שיטתו, שהרי לא אומר כןא שיטתו שמביא גמרא. גם יודעים כן מפני שגמרא כבר הביא שיטתו (או על כל פנים, דברים שמביאים שיטתו), ואז לא היה צריך להביא אותו ברייתא. ותחשב.
* עג.
** דהלך -
גם היה אפשר לומר שקמ"ל שאף אם הלך על משענתו לא אומרים שעמד עד שהגט ייבטל.
* עג:
** רבי יהודה -
ואם תאמר מהו ציור של רישא של משנה. יש לומר שהוא אותו ציור, ורבי יוסי הוא. גם יש לומר שהוא רבי יהודה, וחוששים לאותו שעה. יש לדון, שאם כן, נמצא שגט וקידושין חלים בבת אחת. ויש לדון. גם קשה שרש"י אומר לקמן שיש נפק"מ להצריכה גט שני; לכאורה, הוה ליה לומר שצריכה ייבום או חליצה.
** נתנו
- אחר בעילה- צריך ביאור למה צריך להיות אחר בעילה. נראה שרש"י מניח שלא נראה כאתנן אם נתן לה קודם.
** חוששים
- יש לציין לגמרא שבת שאומר שמואל (כן אני חושב) קולא בלשון חוששים.
** כרבי יהודה
- סתים- לשון זה מעניין, שלכאורה, יש צורך להוכחה זה ברבי, שאין יודעים מה סובר כיון שכתב כל השיטות במשנה, אבל לכאורה, לת"ק יש הוכחה, שאמר כן, ואז סובר כן. ותחשב. ואולי רצה לומר שלא היה רבי סותמו, וגמרא אומר שאי אפשר להיות כרבי. לא משמע כן מגמרא או מרש"י. ותחשב.
* עד.
** ומטמא לה -
לכאורה, לשיטת רבי עקיבה (תחילת סוטה) שחייב לטמא לה, יש עוד נפק"מ.
** בעילתה תלוייה -
עיין במש"א רש"י. מעניין שעדיין אין צריכים אשם תלוי, שאשם תלוי הוא להגן עד חטאת, וכאן, עד שנראה אם מת, צריך אותו הגנה. ותחשב.
** לרחוקה -
ואם תאמר בוודאי רוצה כיון שנותן. ויש לומר שרק רוצה מעות.
** כסוף -
א"צ זה, שכבר אמר סיבה למה אי אפשר לומר מח’ בקידושין. אפשר שרוצה שר"י יאמר דינו בקידושין, ור"ה יאמר דינו בגרושין. ותחשב.
* עד:
** והתניא -
רש"י מניח שמביא את זה לראיה שרק בזה חולקים. היה אפשר לומר שידע דיחוי של גמרא, והוא רק ראיה שבזה חולקים. ותחשב.
** עד כאן -
קצת צריך ביאור למה מניח גמרא שנתינת חפץ, ולא דמיה, מצער, אבל קבלת מה שאמר, ולא חילופו, אינו הרווחה. ויש לומר שאולי בדרך כלל הוא הרווחה, אלא שכאן נמצא שהיה מים בחילוף מים, ולא היה הורווחה.
** לשכה -
צריך ביאור למה צריך לזה, שכיון שסותר את כותלו, יכנס ויתן לו. ויש לומר שלא היה חובש את עצמו באותו בית אלא בבית אחר.
** לצעוריה -
קצת צריך ביאור למה זה לא סותר מה שאמר גמרא לעיל שכיון שהוא מרחיק אותה, רוצה לשהותה. ותחשב. ואולי זה רק היה הוה אמינא.
* עה.
** מכלל -
איסורא- צריך ביאור למה צריך לזה; היה אפשר לומר שאין צורך לתקנה. ויש לומר שבא לבאר למה אין לא פלוג עליו.
** תנאי קודם -
זה, לכאורה, נגד רמב"ם שאומר שזה אומר שצריך להתנות קודם שעושה מעשה.
** תנאי -
עיין ברש"י שמבאר למה היה לו לנקוט זה. היה אפשר לומר שלשון יותר משמע שזה היה בעיה, שאין לדחות לומר שאמרו כתיקונו, אלא שרצה תנא לקצר בלשונו. נראה שכמו כן הוא מעלת הא דראב"א, ששם אי אפשר לומר שהלשון לאו דווקא כלל, שהוא מעיקר התנאי.
** מכדי
- אצ"ל ר"מ, שכולי עלמא לומדים משם (כמבואר בקידושין, ולקמן ברש"י), ובאמת, מזה מקשה לפי רש"י.
* עה:
** לא מקדים -
מעניין שזה אף אם דבר שבא לפניו אינו חלק מן התנאי. ותו"ת.
** דמקל -
נראה ששיטתו העיקרי הוא שמסתבר שאיש יגרש את אשתו. אז, יותר מסתבר שכלל כמה דברים כאלו בתנאו.
* עו.
** ר"מ -
מעניין שר"מ אומר דינו של תנאי כפול בענין שאינו כפול (רק אומר דין של מקרה אחד), אף שסובר שמכלל לאו אי אתה שומע הן; וחכמים אומרים אותו באופן כפול, אף שסוברים שמכלל לאו אתה שומע הן. ונראה שמסתבר האו, שרבי מאיר היה מדבר לרבנן, שסברו להבין מלאו, ורבנן דברו לר"מ, שלא היה מבין מלאו. ותחשב.
** וכל שני כתובים -
צריך ביאור, שכאן לכאורה כתב לשון כפול כיון שצריך המתנה לכפלו, ולא ללמד שצריך לכפלו. ויש לדון, שאולי היה אפשר לומר אותו בלשון שאינו כפול, ונבין שהוא רק פאריפריי"ז. ותחשב.
** ואין אחד -
יש לדון, שאין עדים נגד מה שאומר ראשון. וצריך לומר שהענין הוא שזה סותר למה שאמר זה, ואז אין מעידים ביחד על שום דבר. וצריך לחשוב, שלא הבנתי כל הענין כל כך.
** אנטיפרס
- סמוכים- אם כן, היה אפשר לגמרא להקשות איך יהיה זה בגליל וזה ביהודה, שסמוכים הם (ואי אפשר לומר שהגבול משפע ביניהם) וזה יותר קרוב לגליל. ותחשב.
* עו:
** תניא כוותיה -
לכאורה, אין זה מוכיח כמה שאמר, שיש לומר שרק אומר אותו דין. ואולי גמרא רק הביאו להוכיח שכן הוא הדין. גם יש לומר שידע שקאי על המשנה. גם יש לומר שכיון שלשונו כל כך קרוב ללשון המשנה, מסתבר שעליו קאי.
** נאמנת -
מעניין, שלכאורה, אין זה רק עושה שיודעים שלא יערר, שאומרים כן אף על ציור שמת. אם כן, צריך ביאור למה זה עושה נאמנות, שלכאורה, אין לו כוח של כלום, שאין הודאה לאיסורים.
** לאחר יב -
צריך ביאור למה רק אז יהיה מותר, שהרי אם חל אז, הוא לאחר מיתה.
** איה"נ
- ע’ במש"כ שהיה באותו מנין. עיין תוס’ בראש חולין שאומר שכל "סבא" הוא אליהו. אם כן, מחודש שהיה יכול להיות במנין:
1. מחודש שהיה יכול לפסוק.
2. מחודש שלא היה בעיה של "לא תענה על ריב,” שלא היו יכולים לחלוק עליו. ותחשב.
* טז.
** אינו חיבור -
יש לדון מה היה הדין אם היה חיבור:
1. היה זה מטמא את זה. אז, אם אחד ראשון, יעשה את חברו שני.
2. היה שניהם נעשים חפץ אחד, וכיון שזה ראשון, אף זה ראשון. יש לדון למה לא נאמר שאם זה טהור, אף זה טהור. ותחשב.
יש להעיר שבמקווה לכאורה צריכים לא רק שנוגעים אלא שנעשים אחד. אז, מה שמדמה דיניהם משמע כצד  שני. ותחשב.
** חיבור -
כמאן דעביד- צריך לחשוב למה זה יעשה שהוא כאילו נעשו ביחד. ונראה שהוא מפני שרישומו של הראשון עדיין שם כשנעשה השני. ותחשב.
לולי רש"י, היה אפשר לומר שמה שיועיל הוא שבעת אחד יהיה כל ידו במים, שכבר יש מים על חצי השי. ויש לדון, שאינו ניצוק בחד זמן. ויש לדון, שנוגע במים שהיה ניצוק עליו. ותחשב.
** לענין
- גוד אחית- אם כן, לכאורה צריך להיות על גב המים, ולא שיוצא ממנו. ויש לדון, שאולי הולך דרך גופו. לולי זה, היה אפשר לומר שהוא שכל גופו מחבר אותו. וקשה למה שייך לדין חיבור אם הוא מחמת גוד אחית. אפשר שאומר שדין של משנה הוא רק שכשהוא טופח על מנת להטפיח, נחשב עדיין מים, ומצרפים אותו דרך גוד אחית. רק אם הוא לא מטפיח, לא נחשב כבר מים. גם יש לומר שאומר שכמו שהקיל ר"י במקווה בזה, אף הקיל בקולא אחרת (כמו כן מצינו בכ"מ).
** לענין
- עבמש"כ למה א"א ללמוד ממנו. גם י"ל ששואלים לרבנן.
** טמא
- ושוב גזרו- נמצא שיכולים רבנן לגזור גזירה לגזירה (אם "בלא הא…"), אף אם אינו בחד זמן.
** וחציו
- ט קבים- היה אפשר לומר שכיון שהוא רק חציו, צריך רק חצי של זה. ויש לדון.
** מתחת
- משמע שצריך שניהם: ששנים אדוקים בו וששניהם שלוחים.
* טז:
** כשר -
זה מ"מ, שמגלה שלא פלוג הוא מחמת גזירה (ואולי החולק על דין זה וסובר כלשון שני יחלוק אף על זה).
** במאי קמפלגי -
רש"י מבאר שרק שואל לרבי יהודה, שכבר יודע שרבי יוחנן אמר כרבנן. אף שכבר יודע שיש צד שרבי יוחנן אמר כרבי יהודה, ואז ידוע שיש סברה לומר כן, כל זה בדיבור של רשב"י, ובתוך הלשון שני. בזה, אין לשון ראשון, כמובן. ותו"ת.
* יז.
** חבריא -
עיין בריש בשבת (גבי המכבה מפני נכרים) שאומר שהיו מכבים נרות מחשש פרסיים. ק"ק, שמכאן משמע שלא היה סכנה בו, אלא שפרסיים היו מכבים את הנר. ואולי לפעמים כיבו רק את הנר, ולפעמים, אף הרגו אותו. ותחשב.
עיין שם במסורת הש"ז שהביא גמרא זה. יש לדון אם מביאו ללסמך למש"א שהיו פרסאים עושים כן, או לראייה או שבא להקשות כמה שפירשנו. ותו"ת.
** מקמי -
וצריך לומר שבאותו זמן כבר היו יכולים לקבל גזירת ארמיים, אלא שבאו פרסיים, שהיו קובים (או שהיו יותר אכזרים, לענש יותר).
** והא זמנים -
צריך ביאור למה לא הקשה כן מתחילה (קודם שהקשה מן המשנה). ויש לדון.
* יז:
** זנות לא שכיחא -
גם יש לומר שלא שכיח שהיו בית דין הורגים (גמרא מכות), ואז אין לחוש.
** מאי אהני -
ואם תאמר אהני שנאסר לכתחילה לכתוב. ויש לומר שמי שעושה כן מכוון להטעות בית דין ולטרוף פירות, ומסתמא לא יקפיד על זה. עדיין צריך ביאור למה אין מה שאין לכתוב לכתחילה (ולא רק מה שאין לישא לכתחילה) עושה שלא ימצא מי שיכתוב לו.
** איפכא -
אינו ק’ על ר"י, שרק אומר כר"ש.
* יח.
** מה הועלו -
יש לדון, שהועילו שלא יהרגו אותה אם זנה לפני כן (ויותר טוב מאם לא התקינו).
** קלא
- לכאורה, ק"ק למה צריך להביא ראיה, שספק נפשות להקל. ונראה שמיירי בתוך הזמן שלא מסתבר שהיו באים ממדינת הים.
** אלא לאחר שלש -
היה אפשר לדחות שאולי תנאים אלו סוברים שתלוי בזמן ביאה, ולא בזמן גירושין כלל.
** הלכתא -
וא"ת הרי הלכה כרב נגד שמואל. ויש לומר ששאני הכא שרב אשי וכדומה סוברים כשמואל. גם יש לומר ששאני הכא שכבר יש תנא שסובר כשמואל. ותו"ת.
** תניא כוותיה -
מביא מחלקתזה כאן כיון שהוא מחלקת רב ושמואל שבו יש תנא ככל אחד מהם.
** נכתב -
יש להעיר שאם הוא מעשה בית דין, חייב משעת נשואים, ולא משעת כתיבת כתובה. אם כן, צריך לכתוב אותו זמן.
** רבי חייא -
מעניין שבדרך כלל מצאנו שהיה נקרא חייא בר רב. שמעתי שאולי כיון שנשא אשה היה נקרא "רבי.” אם כן, מובן למה כאן היה נקרא רבי. ותו"ת.
** באותו ענין -
יש לדון מה לנו בזה:
1. מרש"י נראה שהענין הוא שהקול יוצא על חתימתו, שכיון שעומד הוא לחתום (לא רואים שום דבר שמעכב אותו מלחתום) יודעים באותו חיוב; מה שאין כן אם שהו בינתיים, שמה ששהו בינתיים, אף שלא היו צריכים לשהות עושה שבני אדם חוששים שלא יחתמו אותו. ותחשב.
2. לולי זה, היה נראה לומר שכיון שעומד לחתום (רצה לומר, שהתחיל אותו פרוס"ס, ולא דחייה בידים, שלא היה אפשר לעשות אותו עדיין), נחשב שכבר עשה אותו.
3. אולי כיון שאין הפסק בתוכו, כולו נגרר בתר תחילתו.
* יח:
** נמצא אחד -
בסנהדרין- חושב אני שבדרך כלל מביאים את זה ממכות.
** אמרי לה כשר -
יש לדון למה מניח שחשב על שום אדם. ואולי הוא כמו שאומר רש"י גבי אין ברירה, והוא שמניחים שחושב על דבר שיהיה היותר מצוי. ויש לדון איזה פקטורים עושה אדם עד, שלכאורה, לא מעלה ולא מוריד לו מי הוא העד. ותחשב. ויש לדון אם כולם כשרים, איזה אומרים שהוא העד. ותחשב.
* יט.
** בשעת הדחק -
קשה למה לא רק כתבו בו אז שהזמן אינו נכון ושהוא זמן אחר. ואולי אם כן חוששים לרמאי, וימחק או כדומה. ותחשב.
* בבא בתרא
* צב.
** איתמר -
לקמן פריך- לולי זה (ואולי כן רצה לומר), הוה אמינא שהביא אותו כאן מפני שלקמן, על ידי אותו קושיה, יפרש משנתינו. ותו"ת.
** יכול לומר
- יש לדון אם רצה לומר טענה טובה או חזקה (וסובר שחזקה עושה כוח הטענה). ועיין בלשונות שאומר לקמן.
** לשחיטה
- צריך ביאור מה אומר, שלא אומר שיש הוכחה ממה שלא אמר, שעדיין צריך ממע"ה. וצריך לומר שהוא הוחכה די לעשות שהוא ספק.
** הכי גרסינן -
יש לחלק ששם לכולי עלמא כן הוא זרעוני גינה, ואז הוא חלק ממשמעותו. כאן, אינו כן לכולי עלמא. ותו"ת.
** ומשני
- יש לדון ל"ל אומרים שקונה לעמים לאכול, אבל אינו טבח (למה צריכים מה שהוא טבח). יש לומר שלא היה דרך לבני אדם ליקח, אלא לטבח ליקח. לא נראה כן מגמרא שדן בחתן וכלה שלוקחים אם ובן. גם יש לומר שלא קונה אדם די עד שנסתפק. ותו"ת.
** וליחזי -
שהוא מאותם- לא הבנתי:
1. כאן, מדמים סיבה לדבר (מה קורא) לדבר עצמו (למה זבן ממש). ויש להעיר שאף כאן נאמר כן, שאי לרדיא זבן אותו פעם, בודאי לא לנכסתא זבן אז.
2. מה לנו באותו חילוק.
כמובן, פשוט שיהיו השנים תלויים זה בזה. ותו"ת.
* צב:
** רוב נשים -
היה נראה לומר שהוא רוב כיון שכל שנישאת אלמנה נישאת כבר. אז, כיון שיש שלא נושאים לפעם שני, בודאי יש יותר בתולות. ויש לדון, שיכול להיות אשה נישאת בנשואים של אלמנות כמה פעמים. ותו"ת.
** סהדי שקרי -
מעניין שמניחים כן, ולא שהיה לה הנמיא, אף שהיתה אלמנה. אולי גם ראיה זה של הנמיא יותר חזק מהנחתינו שאין העדים שקרנים. יש לומר שיש קול רק מחמת ההנמיא (שבלי זה, לא היה ידוע לבני אדם שהיא בתולה).
** יש לדון למה
בכל ראיות גמרא מניחים שיש "טענה טובה,” כמה שאמר רש"י. אם טענה טובה רק רצה לומר כוח הטענה מחמת שהוא מוחזק, אינו קשה.
** ורובא
- דשוורים- קצת צריך ביאור מה לנו בזה, שאולי רוב כך רק מפני שרוב בני אדם אינם כאדם זה שהוא טבח ועובד אדמה. אם כן, קשה איך נלמד מהם להוכיח עליו. ואולי מה שרוב בני אדם בוחרים להיות רק טבחים או להיפך יגלה כמה הוא טובח או עובד. ותו"ת.
** לא אזלינן
- אם יש לו שום טענה- עיין לעיל, שרש"י אמר ש"אזלינן בתר טענה טובה.) ותחשב.
** האשה שנתארמלה
- אבדתי- קשה למה נאמנת, שאולי כבר קיבלה כתובתה. ואולי יש עדים שמעידים שלא גבתה. ואין לומר שבעל מודה, שאם כן יהיה מגו.
** בהנמיא
- קלתא… כלתא- אולי נקט שני לשונות אלו לפו"ן.
** כתובתה מנה
- מעניין שלא הזכיר ה"טענה טובה" שהזכיר לעיל.
** כי איכא
- דאין כאן קול- משמע שידיעת שני עדים כבר נחשב קול. ויש לומר שאין מוכיחים שאין קול אלא ממה שלא באו להעיד. אם היו עדים מעידים שהיתה בתולה, ולא רק שיצאה בהנמיא, לא היה סיבה להם להעיד, ולא היו באים. ותו"ת. ויש לדון, שאולי כולם שמעו קול, אבל לא ידעו די להעיד. ויש לדון, שאולי יכולים להעיד על קול ששמעו.
** ליסטים
- ליהרג- יש לדון אם קאי על האדון (שעבד יהרג אותו) או על העבד (שמלך יהרג אותו). אם נאמר כצד ראשון, צריך לומר שרש"י ד"ה הרי שלך רק קאי על מוכתב למלכות.
** ליסטים -
עיין ביבמות (כה.) שזה לשון ללסטים אחד).
* צג.
** דרובא הכי -
קשה, שלכאורה, רוב זה עושה שכן חושב לוקח, ואז אין חזקה וכדומה סותר את הרוב. ואולי אף רוב הוא שכן חושב. דחוק, ולא נראה כן. ותחשב.
** ושמואל אמר לך -
משמע שחזקה עדיף מרוב. אף שהלכה כשמואל, אין הלכה כן. צריך לומר שמניחי שתנאי הוא (ואולי מפני שבין כך ובין כך צריך להיות תנאי).
** בעיתותא -
קשה למה לא חייב בהפלה מחמת בעיתותא, שהרי גמרא בקידושין רק אומר שהוא פטור בבעלי דעת כיון ש"הוא מבעת את עצמו.”
* צג:
** אמרו לו -
סאה אחד- רצה לומר, בין כולם, שאם לא כן, היו שני מיני רוב שווים. מעניין שאין להוכיח מלראות כמה אדם זה לקח.
** תנא קמא -
גם אפשר להיות תנא של משנתינו.
** רשב"ג -
זה מעניין, שיש אומרים הוא. בדרך כלל, יש אומרים הוא רבי נתן; והוא רבי נתן מפני מעשה שאירע ברבן שמעון בן גמליאל (עיין בסוף הוריות). אז, זה קצת ironic.
** הוצאה
- דקנסא- לכאורה, אם קונסים על זה, צריך לומר שמניחים שפשע. יש לדון איך היה לו לדעת.
** דמי -
רצה לומר, לא מסתבר שרבי פסק כן, שלמה יפסוק כתנא שהוא יחיד.
לשון רש"י של "סתם" מוזר, שזה כלל אחר- כלל שהלכה כרשב"ג במשנה.
* צד.
** פחות מרובע -
יש לדון אם יכול להיות שניהם או רק אחד מהם. אם יכול להיות שניהם, יש לדון מהו השיעור אם הוא רק אחד מהם. אם הוא רק אחד מהם, יש לדון מה נחשב קטנית- אם כולו כן, או אם רק מקצתו כן. ותו"ת.
** נותן
- כל זה מעניין, שלכאורה, הזיק את הגדיש, שעשה שאינו שווה כל כך, ועשה כן במעשה לגדיש (שהוציא ממנו דבר). ותחשב. גם צריך ביאור למה אומר שאינו ניכר. גם יש להעיר שיש שם אחר להיזק שאינו ניכר, והוא היזק שאינו ניכר, ולא גרמי. ותו"ת.
** וזה בכה
- אם כן, ידע כבר את החילוק, וקצת קשה למה חשב ללמוד זה מזה.
** כל סאה
- בהשרשה- קשה ל"ל אמר שהוא אף אחר השרשה, ויש נפק"מ לקיום כלאים. ואולי שיעור זה הוא רק לענין לאסור את האוכלים. גם יש לומר שסבר שרבנן חולקים על ר"י גופא מפני שסוברים שאין איסור לקיים כלאים. אז, רצה לבאר אף להם.
* צד:
** ומנה -
גם יש לומר ששם הוא רק ספק. ותו"ת.
* צה.
** כל יתר מכאן -
עיין ברש"י, שמפרש שרק רצה לומר שלא מוחלים. לשון גמרא לא משמע כן כל כך.
** ואמאי -
צריך ביאור למה מקשה על ביטול מקח, ששם כל המקח הוא טעות (עיין בשיח שי ב”ב ולעיל, שהוכחנו שכן סובר רשב”ם), ופשוט שחוזר.
* צה:
** מרתף -
חומץ…- לא הבנתי מה לנו שחומץ נתחזק בזמן, ולמה זה עושה שהיה לו לומר שרוצה מרתף של חומץ. ותחשב.
* צו:
** והלכה כוותיה דשמואל -
יש לדון אם פוסק כמותו בכל, או אם אומר שבשכר מיהת, הלכה כשמואל, ועשה ר"י טוב, אבל ביין, אינו ידוע שהלכה כרב.
** תרין ופלגא -
ואם תאמר מה קרה, אז, שהחצי. ויש לומר שנבלע בשמרים הוא (במקום יין שיצא).
** ואחרים
- קפי- לא הבנתי מה לנו בזה.
* צז.
** אבל יותר -
לא הבנתי למה סובר שרבנן לא מחמירים כלל מחמת מעשר כיון שרואים שלא מחמירים בכל ציור מחמת מעשר. ותחשב.
** ביותר -
יש לדייק מזה אף לקצת יותר. נראה שזה יהיה מחלקת אחרים ורבנן רק לצד שלא חולקים בשלש ושלש כיון שאין רגלים לדבר, אבל לא לצד שלא נוכל להניח שניתוסף די לעשותו יין. (עיין ברש"י לעיל.)
** להודיעך כוחו
- בא לבאר למה אין מראין חידוש להיתר, כמו שדרך גמרא לעשות. נראה שמיוסד הוא על מה שאמר רש"י בתחילת ביצה שאותו כלל מפני שכל היתר יותר מחודש, שאי אפשר להיות מסופק ולפסוק כן.[fn:1] אז, אומר כאן שכאן יש חידוש ביותר במחמיר.
** מעשר… -
יש סימן לכל סוגיה זה, והוא ששווה אותו דרגא שהוא אסור לדרגא שמטמא.
** מעשר -
היה אפשר לתרץ שכאן הוא במעשר ראשון, וכאן הוא במעשר שני (כמו שאומר רש"י, וכמו שאומר גמרא ביבמות על קושיה כעין זה). ותחשב.
** של מעשר
- ק"ק מה לנו שהוא מותר לזרים, שעדיין יכול להיות נפק"מ בציור שתמדו קודם שנתן ללוי. צריך לומר שלא מניח כן רש"י כיון שזה לא מצוי.
** אנן אפילו לכתחילה -
צריך ביאור למה מניחים כן (הוא כעין דיו).
** בפרה
- מעניין שנעשים כולם אחד, ולא אומרים שכיון שאינם בכלי אחד לצרף אותם, לא נעשים אחד. ואולי הוא מפני שאין דרך אחר לדון מה ראשון, ומה שני, שטיפה שניה לא יוצא ממקום שיצא ראשון, ואז אף הוא שני, ולא נדע מהו טיפה השניה מאותו שמר. ותחשב.
** קמא -
ע’ במה שכתב. גם יש לומרש מקשה שאז אין נפק"מ עוד בין מים לתמד. ותחשב. ואולי כן אומר, ולא שאז נעשה יין.
** דאמר רבא -
לכאורה, לא מובן אלא אם כן גורסים כמו רש"י כאן, שזה קושיה בפני עצמה, ולא מוכיח קושיית גמרא הראשון[fn:2]. ותחשב.
** הלסטון-
נראה שהצד שיהיה קשה מן מן הגת הוא שאינו עומד כל כך אולי להיעשות יותר חזק. ותחשב.
* יט:
** ב‛ וג‛ -
יש לדון, שצריך להניח שני הנחות, שצריכים להניח שבא אותו מזוזה לשם, ושנאבד אותו גט. אם כן, הוא כעין ספק ספיקא. ותחשב.
** שינה -
קשה, אולי יש בעיה שם רק כיון שכתב שם שאינו נכון. ויש לומר שלשון ”שינה,“ ולא ”כתב שם שאינו נכון“ משמע שכבר יש שם שיש לו לכתוב. ויש לדון, שאולי יש לו לכתוב אותו רק כדי שיהיה לה ראיה, אבל אינו מעכב. ותחשב.
** איסורי הנאה -
יש לדון למה אין שוויות לאסורי הנאה:
1. אולי הוא מפני שאי אפשר לקחת הנאה ממנו. ויש לדון, שיכול לראות אותו או כדומה.
2. אולי הוא מפני שאי אפשר לקחת ממון למכירתו. זה מחדש שאף שנותן הנאה, ואף שהיו בני אדם נותנים ממון, אין לו שוויות.
** משמיה -
לכאורה, בפעם ראשון חשבו שרבנן חלקו. בפעם שני, לא חשבו כן. יש לדון ל"ל. אולי הוא מפני מה שאמר. יותר מזה יש לומר שרק חשבו כן מפני שאמר רק שם רבי, שמשמע (עיין ראשונים בב“ב (קל)) שחולקים רבנן. ותחשב.
** משמיה -
יש לדון איך הטעה אותם, ששמעו הראשון. ויש לומר שחשבו ששמע שטעה. גם יש לומר שאמר כן במקום אחרת או לבני אדם אחרים.
** יש להעיר
שאי אפשר שהחילוק בין תוכות לירכות הוא שאם הוא בולט אינו נקרא כתב, שבציץ כשאר. אולי הענין הוא שצריך לכותבו, והוא שצריך לעשות דבר להאותיות. ויש לדון, שלא אומר כן גבי ציץ. אולי לשון ”מכתב“ משמע דבר שנכתב. ותחשב.
** ויש לדון
למה אותיות יותר נחשבים אותיות ממה שבין אותיות, שלכאורה, שניהם מוכיחים מה שמכוון לומר בשווה. ותחשב.
** כנופי -
יש לדון למה לא רואים אם גדל או לא. נראה שלא דנים מה קורה, אלא אם נחשב כתב, שאף שגידל הנכתב, אין צריך כך, שאף שקע. ותחשב.
** אלמא -
היה אפשר לומר שמה שקבלו בני אדם הוא הסיבה. דחוק. ותחשב.
* כ:
** הא בעינא -
ק"ק למה רש"י מבאר כאן (שהיה לו לבאר בזמן ראשון שהביא גמרא ראיה מזה).
** והשאר -
לכאורה, הציור הוא שגט נכתב על חלק מן הנייר, ושאר הנייר אין לו עליו כלום.
** בין תיבה -
גמרא לא מתרץ לזה, כיון שאין כל התיבות בחד שורה, ואז יהיה כולו מחובר. ותו"ת.
** הגודרות -
יש לדון ל"ל נקראים ”צאנות,“ שהרי זה אף אם אין גדרות של צאן, אלא רק אחד. נראה שאולי רוצה לשנות המילה לעשות שהוא חלוק מן הnoun, אבל כיון שעשיית verb הוא נתינת חולם, היה "צאנות“ שווה, ולא כ“גודרות,“ שמתחלה היה בו חיריק.
* כא.
** לא קנה
- אמור רבנן- לשון זה מעניין ומיותר. אולי רק ר"ל ”פירשו רבנן בדרשה של התורה.“ ויש לדון, אז, למה הזכירו כלל. ותו"ת.  משמע שהוא רק מדרבנן, וקרא אסמכתא. אולי זה יבאר למה רש"י יאמר פשט בדרשת הקרא שאינו כל כך טוב.
* כא:
** מי שאינו -
יש לדון, שהיה אפשר לתת אותו על הפרה. באמת, יש לדון מה נחשב מחוסר, שפשוט שאם אחר שכתב גט נתן עליו smiley face, לא נאמר שהיה הגט חסר כך. ותחשב. וצריך לומר שכיון שזה שינה איך נותן אותו הוא חשוב. ויש לדון, שלא שינה אותו כל כך.
** על מנת -
ואם תאמר נלמד תנאי מכאן. ויש לומר שאילו לא ידעינן דיני תנאים, היינו אומרים שאר ציורים שאין בהם כריתות, כמו אם הוא עדיין אדוק בגט. ותחשב.
* כב:
** והא לאו -
לכאורה, מניח שהוו כרבי אליעזר. אפשר שהמשיב (רב הונא) הוא השואל.
* כג.
** והוא שהיה גדול -
לכאורה, זה מוכיח (וכן נראה מגמרא בתחילת חולין) שיכול קטן לחשוב, אבל צריך דבר גדול להוכיח מה חושב.
גם יש לומר שגדול מלמד לקטן מה לעשות כשעושה אותו. אולי, אז, מחשבת הגדול די. לא נראה כן, שאם כן בוודאי יהיה די בגוי. יש לדחות שגוי עושה אותו לסיבה אחרת, מה שאין כן קטן, שעושה אותו בלי צורך, שלא יכול לכוון.
** עובד כוכבים -
יש לדון איך יודעים שזה בכל ציור, ואף בישראל עומד על גביו.
** לאו מילתא -
ואז נמצא שמתורץ קושייתו הראשון, שאז אין צריך לומר עוד שמשנה הוא בשעומד על גביו, ואז אין צריכים לומר שמהני אם עומד על גביו, שמשנה שלנו הוא כרבי מאיר. יש להעיר שאם כן, נמצא שלרב נחמן אין עמידה על גביו מבני כלל. זה מעניין. יש לדון אם זה בכל דבר או רק בגט, כמו שמצאנו חומרות בגט (כמו גבי תוך כדי דיבור). ותחשב.
** רבי אליעזר היא -
עדיין היה אפשר לומר שרבי אליעזר סובר כרבי מאיר. ואם תאמר כיון שלא צריכים לחתופ, למה יעכב הכוונה. ויש לומר שהוא כמו מזוייף מתוכו (אם העדים הם פסולים). ויש לדון אם זה דין דאורייתא או לא.
וקל לדחות שדין כתיבה לשמה קאי על אותו דבר שעליו קאי "וכתב לה,” שאומר שצריך כתיבה. אז, צריך לומר שדין לשמה קאי על דבר שצריך כתיבה. אז, לר"א אי אפשר לומר שקאי על חתימה. ותו"ת.
** דלאו בני דעה
- איש- ואם תאמר זה ממעט קטן, אבל לא ממעט שאר ציורים. אולי מבינים למה קטן נתמעט. גם יש לציין לגמ’ נזיר (כן אני חושב) שממעט אונס מ"איש" כיון שלא חושב כך. אם כן, אולי יש לומר כן ג"כ כאן. ותחשב.
* כג:
** המשחרר חצי עבדו -
אם כן, לכאורה, צריך לומר שאינו כל כך ברשותו כיון שאבר אחד הושחר, ולכן יכולה לקבל את גט שחרור של אותו אבר. אם כן, אחר שהושחר אבר אחד, יכולה לקבל את הגט לכל עבד של רבה. ותחשב.
ויש לדון אם אף נאמר שאז יכולה לקנות דבר לעצמה. אולי רשותה אינה של בעל לענין שטר שחרור, אבל הוא של בעל לענין לקנות. ותחשב. החילוק יהיה כמה צריך לכל חלות או כוונת בעל. ותו"ת.
** ואם לחשך -
לשון זה מוזר. אולי אומר אותו לשון כיון שאין הק’ נכ’ בברייתא, והרי הוא כאילו אדם לחשו.
** בחוץ לארץ -
יש להעיר שיש עוד יכולת, והוא שאולי רק נאמנת בא"י, וצריך שתאמר בפני נכתב, שאז יש נאמנות ביותר. ותחשב.
* כד.
** סוף סוף -
יש לדון מהו הבעיה:
1. אז, אין נתינה, שנתינה קרה לפני זמן רב. יש לדון אם זה בעיה.
2. מתגרשת מיד, ואין זמן לה לומר. יש לדון, שזה מניח שלעולם צריך לומר מיד, קודם נתינת גט, ולא בתוכ"ד אחריו. אולי זה מפני שדין תוכ"ד אינו בגט. ויש לדון, שזה רק דין דרבנן.
לשון רש"י כאן משמע כשני.
** לא חזרה -
לא הבנתי את זה כל כך, שבכל שליחות, השליחות כלה בשעת החלות. אולי ר"ל שבשעת חלות, היא צריכה להיות האשה, ולא השליח. צריך ביאור ל"ל יכולה להיות שניהם. גם צריך ביאור למה אינו כמו שהוא בכל ציור כאן, שהרי בכל זמן, יש שליח עד שעת חלות, ולאחר כן, כשאינו עושה החלות עוד, אינו שליח. אף כאן, הוא ממש כן. ותחשב.
** ומשוי בי דינא -
יש לדון אם זה אומר שבית דין נעשה שליח (ואין צריך מינוי שלו, כיון שמסתמא בני אדם רוצים שבית דין יעשו כן), או שבית דין עושים שליח. יש לדון למה יש להם כוח. אולי מניחים שהוא מאמין להם למנות לו.
ויש לדון למה מניחים כל זה, שחוב הוא לו. ואולי הוא מפני שמנסה לשלוח גט. וכ"ז צ"ב.
** חצרה הבאה -
אינו כל כך דומה, שכאן אין החצר השליח של הבעל.
** וכי מטית… שליח לקבלה -
לכאורה, ר"ל שתקבל אותו, ולא שתהיה שליח, אלא שתהיה עצמה, שהיא האשה שמקבלת. צריך ביאור ל"ל אומר כן גמרא. צריך ביאור מה אומר לה להיות שליח לעצמה, שאינו מובן לי כל כך מה זה אומר. ותחשב.
* סב:
** טעמא דלא שויתה -
ק"ק איך רואים במשנה שלא עשאה שליח, שאולי מיירי בציור שעשו שניהם שליח, וכיון שהוא רק עשה שליח להולכה, יכול לחזור. אולי אם כן, היה לו לזכור אותו במשנה. לא נראה כן, ששונה אותו סתם, וכולל כל ציור. אולי הוא מחמת היקישו ל"האומר התקבל,” ששם צריך לומר שלא עשה אותו לשליח.
** להביא את גטה -
רש"י מפרש שהראיה הוא מלשון "להביא.” לולי זה, היה אפשר לומר לשיטת רש"י (ב.) שרק שליח להולכה צריך לומר כן, שמוכרח שהם שלוחים לקבלה. ותו"ת.[fn:3]
** איפכא מאי
- צריך ביאור מהו סברה זה שאומר רש"י. לכאורה, הסברה לדין זה ראוי להיות שאין בעל בתורת קבלת גט, ואז לא יכול להיות שליח לו.
* סג.
** אי אפשי אתא -
ק"ק, שלכאורה, דין זה פשוט, שהרי לא יהיה שליח לקבלה אחר שאמר הבעל שלא רוצה בזה, ויהיה שליח להולכה, אחר שאמר הבעל שכן רוצה, והוא הוליך את הגט. ותו"ת.
** מאן ת"ק -
ואם תאמר אם כן למה לי לשנות ת"ק. ויש לומר שמתחילה היה המשנה בלי רבי, ומי ששנה משנה זה העתיקו כן[fn:4], אלא שהוסיף עליו קצת להודיע מי אמר את המשנה. גם יש לומר שאז נחשב סתם כרבי. ויש לדון אם זה יהיה סתם, שמפרש שהוא שיטתו לאחר זמן. ויש לדון, נראה לי, למה יש מעלה לסתם ואחר כך מחלקת:
1. מפני שבזמן אחד היה סתם. אם כן, יש מעלה אף כאן.
2. מפני שיש עדיין סימן ממה שלא אמר מי אומר אותו מימרא. זה אומר שיש סימן שכולי עלמא אומרים כן ממה שאומר כן, ולא מפרש מי אומר כן, שמשמע שכולי עלמא אומרים כן, אלא שסימן זה איתרע כיון שאומר שלא כולי עלמא אומרים כן. אולי מה שאומר סימן שאיתרע, ולא לא אמר סימן, הוא המגלה כן. זה לא שייך כאן, שאין סימן כלל כאן.
3. ויש להעיר שאם זה נכון, אם סותם משנה, ושוב מביא, לא רק חולק, אלא מחלקת, שיש בו שני השיטות, לא יהיה סתם ואחר כך מחלקת עוד. ותו"ת.
* סג:
** מאן שמעת -
קשה ל"ל אומרים שהוא רבי, ושאני אם אמר השליח שאמרה אשה לקבל לה. ותחשב.
** גט מחיים -
לכאורה, ר"ל שהיו שני ציורים. גם יש לומר שהיה ציור אחד, ועל אותו ציור אמר שאם רוצה לגרש, צריך גט, ואם לא, תצטרך חליצה. שוב ראיתי שרש"י משמע כשני.
** ספק -
קצת יש לדון מי נחשב המוחזק (למה). ותו"ת.
** נפאתה
- יש לדון מהיכי תיתי שאין זה שמו. אולי מה שהוא לשון נקבה (נפאתה, ולא נפאת או נפאתא) משמע כן. ויש לדון, ששמחה הוא שם של איש.
** עשו עדים -
יש לדון מהו הנפק"מ. אולי הוא שחזקה שליח עושה שליחותם שייך לא מבטיח אלא עשיית גט אחד. גם אפשר שצריך אדם לקבל שליחות כיון שמקבל. ותחשב.
גם יש אולי עוד נפק"מ באם צריך עוד מינוי. ותחשב.
לכאורה, מה שיהיה זה מהני לשליחות הוא שקבל טירחא מסויימת. ויש לדון, שאם האשה רחקה א"ע, אטו לא שליח עוד. ויש לדון.
* סד.
** מי קא נפיק -
מרש"י משמע שנאמן מחמת מגו. קשה, שגמרא אומר שנאמן כיון שהאמינו בעל. צריך ביאור איך נבאר ששנים אלו אומרים דברים שווים.
** לדידה -
לכן כ’ רש"י שצריך להיות שהם בעיר אחד.
** שטרות -
לכאורה, יש שני ראיות:
1. קורא להם שם חלוק. אז, צריך להיות חלוקים.
2. א"א ששניהם שטרות, שלא יזכיר שטרות שני זמנים.
** שעת הגזרה -
לכאו’, עדיין א"צ לראות הקריעה, אלא הקבלה. אז, הקריעה לא שייך כלל למשנה.
** והיא אומרת -
נמצא שאף אם אין מעורר, יש צד שלא נאמנת. צריך ביאור למה. היה אפשר לומר (אבל המשך גמרא לא נראה כן) שהיא טוענת שלא נתן לשליח, אלא לי. ותו"ת.
** קמאי דידי -
ק"ק איך תהיה לה מגו מחמת זה, שלא היתה מעיזה פניה לומר זה. גם צריך ביאור למה אין בזה עזות פנים. ותחשב.
* סד:
** דבר אחר מחמת גיטה -
לכאורה, המעלה בזה הוא שיכולה להבחין שיש צורך לשמירת דבר, ויכולה לשמור דבר.
** אינה מתגרשת
- עיין בדרשה. יש לדון אם הדרשה הוא ממה שמילת שלוח משמע שלוח בלי חזרה, או שקרא משמע שאין עוד אחר שלוח, שלא חוזרת. יש לדון, שמה היה לו לומר. אולי הוה ליה לומר שאם תחזור, ישלחה עוד. צר"ב שלא צ’ ליתן עוד גט, לכאורה, ואז אינו דין, ולמה צריך לבארו.
** דא ודא
- תקנות- היה נראה אולי לגרוס "תנקות.” שו"ר בע"ה שבכת"י גורס כמה שכתבנו.
** וורדאן
- היה אפשר לומר שהיה דומה לוורד, כמו שאומר גמ’ בשבת ובכ"מ.
* סה.
** אית לה -
ק"ק למה א"א שיש לזה עיקר מן התורה בהוצאה.
** מערימים -
צריך ביאור איך זה שייך לזכייה לאחרים. חושב אני שתוס’ דן בזה.
** נדריהם -
מה שמניחים דמיון בין הקדש ונדרים בכ"מ הוא, לכאורה, מפני ששניהם הם שינוי על החפץ מחמת דיבור אדם, שעושה איסורים. ויש לדון.
** בנכסי אביו -
יש לדון במה שנתון לו (שאולי אינו כל כך רע לאבד, שזכתה בלי טירחא וחסרון). יש לדון אם נכסי אביו דווקא או רק אורחא דמילתא. חושב אני שגמרא דן בזה, אבל אולי רק דן באם יכולים לתת קרקע.
** גט לידה -
צריך לומר שמניחים שהוא עושה אותו שליח להולכה (עיין בתחילת הפרק). היה אפשר לומר ש"עד שיגיע גט לידה" ר"ל עד שיעשה שליח להולכה. דחוק.
** איהו דמדעתיה -
לכאורה, ר"ל שכיון שיכול לתת גט לה בכל מקום, אין סיבה שתעשה שליח רק למקום מיוחד, שאם לא יקבל שליח אותו, ימצא דרך אחר לתת אותו לו בכל מקום, ואז אין טוב בא על ידי עשיית שליח.
אבל, יש טוב בנתינת מראה מקום. אף שאין הכרח שהוא באותו מקום, שהרי יכול לתת בכל מקום שירצה, חושבת שמסתמא הוא שם. ותו"ת.
* סה:
** גיטא לא הוי עד -
צריך ביאור איך חל שם, שאז בא מיד שליח. אף אם השליח הוא אף שליח להולכה, נמצא שלא חזר שליחות אצל הבעל. לכאורה, יש אותו שאלה לכל תנאי למד"א שרק חל לאחר זמן. צריך לומר שמעשה גירושין נעשים מיד, ואז בעל עושה אותו. אלא, אותו מעשה לא עושה גירושין עד לאחר זמן. ותו"ת.
** בשל חברו -
ואם תאמר אם מניחים שאין המערב מקפיד, למה יהיה חברו מקפיד. אפשר שמניחים שהמערב יאכל את הפרי. אז, אם שניהם שלו, לא יקפיד כל כך. אם של חברו הוא, יקפיד חברו, שלא רוצה שחברו המערב יקח זה, אלא זה. ותו"ת.
** הא והא
- מקפיד- לכאורה, אין צריך לזה, שרק צריך שחברו מקפיד, ולא שהמערב מקפיד, שאף אם לא היה מקפיד, לכאורה אי אפשר לו לערב בפרות של חברו בלי רשות חברו. ותחשב.
** פטרוה -
לא הבנתי הדקדוק כל כך כאן, אבל לכאורה, יוצא שאמירתו בלשון ארמי יותר חזק מבלשון עברי. היה נראה לומר שלשון ארמי אינו רגיל, ואז הוא יותר חזק (שבדרך כלל, משנה אדם דבר ועושה אותו יותר חזק על ידי אותו שינוי. ויש לדון.). ותחשב. זה אינו בא"י, מסתמא שאין יכולים לשנות לארמי, שאין שום אחד מדבר בלשון ארמי שם.
קצת מעניין מה שרש"י אומר שאלו הם לשון ארמי, שאף ראינו לשונות כזה בתורה. אולי זה לשון ארמי בתורה. יותר היה נראה לומר שאלו הם שני לשונות, ומה שאמר בלשון שהוא כולל אף ארמי מחזק אותו. אולי הא גופא הוא מה שמחזק אותו, שאמר אותו באופן שהכל יכול להבין אותו. ותו"ת.
** לא הבנתי למה
אומרים שכשהדגיש, כוונתו לומר לשון גירושין.
** התירוה
- עיין במש"א רש"י . יש להעיר שחולקים תנאים בנדרים אם יכול שליח לבטל נדרים שלה. לכאוהר, לא יעשה לזה שליחא ם אין שליח מהני. ויש לדון, שאולי טועה. גם יש לומר שרש"י רק אומר כן לפי השיטות שסוברים שיכול. ואם תאמר למה לא רק אומר התרת חגור, שזה לכולי עלמא. ויש לומר שזה מוזר להניח שאומר לשליח, ואז לכאורה, לא אומר כן, אם יכולים להניח שאומר להתיר נדרים. ותחשב.
** אף על פי
- מבאר רש"י למה אין הכרח נגד זה ממה שלא אמר כן. לא מבאר למה נחשוב שהוא כן. יש לומר שמוזר לעולם לרצות רק כתיבה, ולא נתינה. גם יש לומר שלו בדווקא מוזר, כיון שהוא עומד למות. ותו"ת. צריך לומר שאותו סברה לא דוחה מה שלא אמר כן (לולי מש"כ רש"י). ותו"ת.
* סו.
** רש"י כ’ -
וכן נ’ מגמ’- שדין יוצא ליהרג הוא כשכיב מרע. קשה, שאין חשש שמא יטרוף דעתו, וימות מח’ שלא נותן מתנה, שאינו חולה. ויש לומר שאף מי שבריא מת כיון שאי אפשר לתת מתנה. גם יש לומר שהוא לא פלוג. ותחשב.
** כתבו אף על גב -
מעניין, שהרי כאן, אף שלא אמר "תנו,” אמר "הבו,” וזה, לכאורה, כמעט שווה ל"תנו.” צריך לומר שאין משמעות שלו ממש שווה.[fn:5]
** לאחר מיתה מי איכא -
ואם תאמר הא גופא הוא הקושיה. ונראה שרק מדמים זה לזה לענין לשונות- מתי מניחים שכוון בדעתו רק לסיבה מיוחדת, ויכול לחזור, ומה כוון בתוך דעתו, וכדומה. כיון שהבעיה כאן לא הוא בעיה בתוך כוונתו, אלא הוא בעיה ביכולת חלות כזה לחול, אין זה בעיה בדמיון שעושה. ותחשב.
** מחמרא -
ק"ק ל"ל אומרים שלא מניחים שהוציא דברים לבטלה, ואז צריך לומר שלא כוון לכך. לכאורה, צריך לומר שסבר שאותו לשון כל כך לא משמע כשאר הצדדים עד שאף שאין אדם מוציא דבריו לבטלה, אין לחדש שכאן כוון לומר שום דבר.
** כדי לייפות -
עיין במה שפירש רש"י. לולי רש"י, היה אפשר לומר שהוא לייפות כוח של היורש. באמת, לשון גמרא לא משמע כן כל כך, שאומר "לייפות את כוחו,” והרי לא דבר כבר על יורש, אלא רק על לוקח. עדיין צריך ביאור ל"ל ייפה כוח היורש בזה, שלכאורה, הוא המוחזק. ותחשב.
** בבואה דבבואה -
רש"י מפרש שהוא צל דצל, ומפרש במק"א שצל דצל הוא מקום שצל ארוך מן החפץ, ומחמת זה, הוא שם יותר קל. לא הבנתי המציאות בזה כל כך, אבל יש להעיר שלזה לכאורה צריך להיות שהאור בא מן הצד. אם כן, קצת קשה להבין איך יקרה כך בבור. ותחשב.
** בשעת הסכנה -
נמצא שאין הגמרא מתרץ, אלא אומר שיודעים שכן הוא, ואף שיש חשש, יותר בעיה אם לא כותבים.
** צרה -
ק"ק מה רוצה צרה לעשות, שהרי צרתה אונס. אולי לא יודעת אותו דין. גי"ל שמיירי בנשואה לכהן.
** אם מדעתו -
יש להעיר שלכאורה, כאן אין כל כך טירוד, כמו שאמר רש"י לעיל, שהרי כאן ידע שימות ורצה למות. ותחשב.
** חסורי מחסרא -
בכ"פ שעושה כעין זה, אומר שהוא חסורי מחסרא, והוא באמת מחלקת…. כאן, לא עושה כן. אולי רק עושה כן כשכבר שמענו מחלקת. ותחשב.
** ברא שלוחא במקום אבא -
לכאורה, אין זה שייך לשאר גמרא כאן כל כך.
** לאחר מיתה -
משמע שיש גט לאחר מיתה, אלא שייבום בא קודם (ואינו יכול להתיר ייבום, או מפני שהוא יחס אחר, או שאינו יחס לו). אם כן, נמצא שאם אין ייבום, כמו אם יש בנים, תהיה גרושה, ותהיה אסורה לכהנים. זה מעניין.
** במקצת
- יש להעיר שלכאורה הראיה הוא להיפך, שממה שלא נשאר לו כלום, צריך לומר שמצווה מחמת מיתה, אבל אין ראיה להיפוך, שאולי משאר ליורשים.
** אידמו
- לכאורה, כן מוכח ממעשה דאשמדאי.
** אידמו
- עיין ב"ב עג:.
* סו:
** מפני שעשאן בית דין -
לא הבנתי כל כך למה ומהיכי תיתי שבית דין עושים אחר שליח.
** מבי רב -
יש להעיר שבדרך כלל, בי רב ר"ל בית מדרש. לפעמים, יכול להיות משמע בית מדרשו של רב. (עיין בפרק יש נוחלין גבי ספרי דבי רב, שיש שכ’ שרב סידר אותו.) כאן, לכאורה, אל ר"ל בית מדרשו של רב, שלכאורה, לא היו שואלים לשמואל, שהיו שואלים לרב. ויש לדון, שאולי לפעמים רב לא ידע, ורצה לשאול לשמואל. גם יש לומר שהיה בית מדרשו, אבל אחר מיתתו. ותחשב.
* סז.
** ר"ש ברבי -
לפעמים רש"י מפרש שברבי הוא לשון חשיבות, אבל כאן ר"ל בן רבי.
** אמר שמואל אמר רבי -
מעניין ששמואל אמר דברים בשם רבי.
** אלמלא ראיתו -
אבל, אף על פי כן, רק פסק כמותו במקצת.
** חכם לכשירצה -
לכאורה, בא למעט מאותו גמרא בקידושין שבו טעה רבי יהודה באשה בעזררה כיון שהיה כועס על תלמידי רבי מאיר.
** יש לדון בסדר
אלו, שאינו בבסדר דורות.
** תרומת -
אולי אומר שמה שיודע הוא טוב מטוב של ר"ע, שר"ע שנה לו טוב שבמשניות שלו, והוא שכח הרע ממה שלמד. יותר נראה לומר שהוא שונה הטוב ממה שקבל, ששכח הרע, ולא מלמד הרע ממה שזכר. לכאורה, צד שני נראה יותר כיון שהנדון כאן הוא מה שמשנה להם, ולא מה שיודע.
** קופת רוכלים -
צריך ביאור מהו החילוק בין זה לחנות מצויינת.
** מעשה -
יעידו- אף שגמרא לא אמר כן, הוצרך רש"י לפרש כן, כיון שתורה האמין שני עדים. וצריך ביאור קצת מה בין זה לעדות או בין זה למעשה. וצריך לחשוב.
* סז:
** אמרי לה להאי גיסא -
שטורח- יש לדון מה אומר:
1. אולי מכוון לומר שגילה שטורח עליו למנות. קשה, שעדיין כבר גילה שרוצה שיהיו כעין כולכם. אז, קשה למה לא נעשה כן. אולי אם אדם לא רוצה כן עד שיאמר מנין כולם, בוודאי לא רוצה די. יש לדון.
2. אולי מכוון לומר שגילה שטורח לו שכולם יהיו נצרכים לאותו גט. לשונו לא כל כך טוב (שלשון טירחא קצת מוזר לזה).
3. מנין- עיין במה שפירש שהוא א’, ב’, ג’.... היה אפשר לומר שאמר, “אתם העשר....” נראה שזה אי אפשר מציור שמנה מקצתם, שצריכים לומר שחזר בעמצע. ותחשב.
4. כד:
5. ספר כריתות- וא”ת הרי דורשים ספר כריתות לדבר אחר. גם קשה למסקנא למה צריכים זה, שכבר נדרש שצריך להיות לשם איש ולשם אשה. נראה שכל זה בהוה אמינא, שהוה אמינא לדרוש זה ולא לדרוש מה שדורשים במקום אחר, אבל לאחר שכתיב לה ווכתב, לא צריך קרא זה, ודורשים לדברים אחרים.
6. פוסלים- אם היה בעלה- פסולה מכל כוהן, ולאחר מיתת בעלה, לא תוכל לישא כהן. נראה שרש”י כתב זה כדי לחדש שאסורה אף לבעלה, ואף שנראה שיש מוכיח, שממה שעדיין נשואה לו, צריך לומר שאינה מגורשת. ויש לדון, שאולי נראה שהחזיר אותה. אפשר שזהו הקמ”ל. גם אפשר שהקמ”ל הוא שהוא לא פלוג. גם אפשר (וכן נראה ממה שרש”י מבאר שזה נלמד מקרא) שאינו גזירה כלל, אלא יש קצת מחלות הגט.
7. ופוסלת- דשם חליצה- יש לדון מה רצה לומר. היה אפשר לומר שתלוי באם מילת “חליצה” יכול להאמר. זה קשה, שאף יכול להאמר על קטן ואנפילא. אז, אולי הענין הוא אם יכול מילת “חליצת מנעל” להאמר. קשה, שאף על קטן, לפי רש”י, יכול להאמר. אז, יהיה קשה לומר הגדרה מסתברה בזה.
8. מרש”י לקמן, באמת, יותר נראה לומר שתלוי באם הוא דבר שנכתב בפירוש, שאז פשוט וידוע לבני אדם, או נלמד מגזרה שווה. יש להעיר שאף שמה שאין אנפילא נעל לא נלמד מגזרה שווה, צריכים קרא אחר להוכיח מה נחשב נעל.
9. כה.
10. קטן- נראה שרש”י מפרש שקטן ר"ל שקטן עשה חליצה. היה אפשר לומר שאומר שחלץ נעל קטן.
11. אמר רב אסי- חושב אני שרב אסי סובר (בביצה) שיש ברירה להקל על דינים דרבנן. אם כן, אולי הוא קצת לשיטתו כאן.
12. לה לשמה- קצת צריך ביאור למה נניח שצריך להיות יותר לשמה מציור סתם, שאינו מיותר או כדומה.
13. זכה בחלקו- במקום אחר הערנו שלכאורה לשון “ראוי...” משמע שלענין בירה הוא שכבר יש לו עומד לאותו קרק’ לפני זמן. יש לדון, שאולי רק רצה לומר שהוא כבר נמנה בשעת שחיטה. לא נראה כן מן הלשון. ותחשב.
14. אי אמרת בשלמא- הראיה הוא ממהש אחרים נמנים. צריך ביאור קצת איך אחרים נמנים כלל, שלא מנה אותם. אולי מפרש שמשנה אומר שדבר טוב הוא למנות, אחר כך, שאר בניו, ואז מקשה איך ימנה. ותחשב.
15. תולה בדעת עצמו- לכאורה, הוא רק תולה בדעת עצמו לבעל, אבל לא לסופר. צריך לומר שרק צריכים דעת בעל, שהוא המשלח, ולא דעת סופר, שהוא השליח. ותחשב.
16. אמר אביי- עיין במה שכתב. נראה , אולי, שהענין הוא כך: רש"י מפרש שמה שאין ברירה הוא שמניחים שכבר הניח שאחד יקרה. אם כן, אולי זה רק בשתלוי בדעת עצמו, שיותר קל לו לדעת מה יקרה. ותחשב.
17. מאן דאית- לכאורה, ר"ל שאין לחלק ביניהם (ולא רק שקרה שתנא שסובר כך גם סובר כך, שאז אין סיבה לנו שלא נחלק ביניהם).[fn:6]
18. מבין הכותים- חשודים- לכאורה, חשודים מפני שלא מקפידים על לפני עור.
19. תשעה מעשר שני- מרש"י מבואר שלא סומך על ברירה לזה. כן, לכאורה, מבואר ממה שמחל אותו. אם כן, לא אומר "שאפריש,” אלא מציין מקום (אפשר שיהני אף אם אומר לשון ברירה, אלא שכיון שמחלל אותו אין צריכים לאותו לשון).
20. כה:
21. ומיחל- אפשר לתקן- קשה, שלכאורה עושה כן מחמת חשש שאין ברירה. קשה, שעל הצד שאין ברירה, הכל טבל בין כך ובין כך, ומה לנו בחילול מעשר. ויש לומר שרש"י לשיטתו, שסובר שברירה בוודאי עושה החלות, אבל תולה אותו במה שחושב שיהיה. אז, יש מזה שהוא מעשר ותרומה, ואינו מה שיפריש לאחר זמן. אם כן, יש בזה ספק איסור. אם ממעט ספק איסור, יותר טוב. אז, נהנה על פי חומרה זה.
22. ולכי- היה ראוי למות- לכאורה, אף זה מוכיח שרש"י סובר ש"יש ברירה" רצה לומר שמניחים שזה היה ראוי לכך מתחילה, ולא רק שדבריו משמע מה שיהיה כן, ולא מה שחושב עליו עכשיו. ותחשב.
23. תנאי- לכאורה, ר"ל שבתנאי אדם חושב שיחול, שאי לאו הכי, לא היה עושה החלות, אבל בברירה אין להוכיח שיודע על מה יהיה חל. וקשה, שאז לא יהיה תנאי תלוי, שחשב שיחול, ואז לעולם יחול. אולי זה אינו קשה, שזה חידוש התורה, שאומר שיכול לעשות שאף כשחושב שיחול, יכול לעשות דבר שעושה שלא יחול. ותחשב על זה.
24. ורש"י מפרש שכל זה רק כשהתנאי בדיו, שרק בכעין זה יכול להיות ברור לו שיקרה. יש לדון, שיכול להיות חושב שדבר יקרה, אף אם אינו בידו. ויש לדון, שאולי צריך להיות ברור יותר ממה שיכול להיות אם אינו בידו. ותחשב.
25. הריני- בביאה- לכאורה, נקט ביאה כיון שצריך כן כדי לומר שתהיה מקודשת אף שהתנה, שאין אדם עושה בעילתו ביאת זנות.
26. אף על פי- אף שלא רצה האב- ולכאורה, אמר מילים אלו לחנם. ק"ק; אולי צריך לומר שרצה שיחשבו בני אדם או אשה שהוא תולה אותו.
27. אע"פ- ביאת זנות- יש להעיר שבין כך ובין כך אין לקדש בביאה (עיין בקידושין שרב מנגיד…), אבל עיין בתוס’ לג: (גיטין) שאומר שאין זה מחמת איסור. אז, עדיין יכולים להניח שלא עבר על שום איסור.
28. כו.
29. שמא יבקע- עיין במקומות אחרים (כמו סוף מעילה) שלא מסיק כן במחלקתם.
30. הכותב- נסתפקתי אם אף צריך להניח מקום של "מגרש את אשתו…,” שלכאורה, אין זה שם האיש או אשה או כדומה, אבל לכאורה, הוא נצרך. ותחשב.
31. שטרות אטו גיטין- לכאורה, ר"ל לענין טופס, אבל אולי לענין תורף פסל. עיין ברש"י שכ’ שפסל.
32. כו:
33. קטטה- יש להעיר שלכאורה כבר היה קצת קטטה קודם לכן, שאי לאו הכי, לא יכתוב סופר גט. אז, צריך לומר שאף על פי כן, יכנס יותר קטטה, ושאף על פי כן, לא רוצים באותו קטטה.
34. ויש לדון, שאולי לא היה קטטה לפני כן, וכתב סופר גט לאלו, אלא שחשש שיהיו אחרים עם אותו שם, שכ’ שם שהיה מצוי.
35. קפסיק- יש לדון אם היה ברייתא שאמר שקאי על המשנה, או שאמר לשון משנה והוסיף זה. ותו"ת.
36. גטה קודם- אם כן, לא פסול אא"כ כ’ זמן מוטעה, אבל בלי זמן כשר. אם כן, קשה למה לא יכ’ אדם שטר בלי גט. אולי אין הכי נמי, יכול, ומשנה רק אומר שלא יכול לכ’ הזמן. ירצה לכ’ הזמן כדי שאף נשואים ישתמשו בה.
37. לא שנא- המגרש- לכאורה, ר"ל שצריך להיות שלא נכ’ זמן שקרה קודם גירושין שלאחר נשואין. אפשר שאף אי לא נשא, יש חשש שבא עליה באריסות.
38. כז.
39. שיירות- לכאורה, שיירות אינם מאותו העיר. אז, אומר שיש שני חששות- שבא ממי שהוחזק באותו עיר, ושבא משיירות.
40. לא יחזיר- ואם תאמר ל"ל יחזיר לבעל. ויש לומר שדילמא נתן כבר לאשה, ודמי הנייר שלה. ותחשב.
41. איכא דאמרי- יש לדון אם דנו בפירוש דיבור שלו, או שחולקים מה אמר.
42. דמזבני- בשוק- ואם תאמר א"כ למה ייחד כיתנא. וי"ל שכאן היו מוכרים בשוק, שהיה מקום קטן שמוכרים זה…, וזה נמצא במקום קטן של פשתן. גי"ל שהיה שוק של פשתן. כמו"כ מצאנו שהיה שוק של ציקי קדרה לרבי יוסי. ותחשב.
43. לא לזה ולא לזה- קשה, שגמרא שם אומר שיש שני יכולות שגובה. אחד הוא אם סוברים שנותנים שובר, ואחד הוא אם לא כותבים כתובה.
44. לראשון, קשה למה יש לו את הגט, שהיה לנו לתת לו שובר. אולי נותנים זה במקום שובר. ואם תאמר איך יתנו לו; במה תשא. י"ל שאם מודה בה, יכולים לתת אותו לשובר.
45. לשני, קשה, שלכאורה, א"צ נתינת גט לו, שהיא נאמנת. וי"ל שאיה"נ, אבל לדעת בוודאי שלא תגבה עוד, כן תקנו. קשה, עדיין, כמו שהקשנו על צד ראשון. ותחשב.
46. כז:
47. איכא דאמרי והוא- יש לדון אם חולקים אם חלק בפירוש, או שחולקים אם יש לדייק שחולק.
48. רבה לא אמר כר"ז- לכאורה, רבה לא שאל כן, אלא תירץ. ויש לדון. עיין ברש"י, שנראה שקצת מעורר זה.
49. מתניתין אלימא ליה- אולי זה מפני שהוא יותר ידוע (ואז אינו צריך לחדש ולבאר דבר קודם שיקשה), ואולי זה מפני שבוודאי הוא נכון, שאין לומר שמשנה אינו נכון כמו שיש לומר בברייתא. כמו"כ י"ל שמח’ אלו מסתמא בא השאלה אל מוחו גבי משנה ולא גבי ברייתא. אז, שם שאלו.
50. לאלתר- עיין במה שבאר רש"י. ויש לדון, שנראה שעדיין יש חידוש, שהוה אמינא שצריך שני עדים לעשות שגט נאמן, ולא די בבעל בלחוד. ותחשב.
51. על גט אחד- ואם תאמר איך יודעים שהוא של זה. עיין ברש"י. היה אפשר לומר לולי זה שלא מניחים שיתן גט שלא בא ממנו. ותחשב. ויש לדון, שזהו החשש שלא לשמה בפרק ראשון, לכאורה. ותחשב.
52. מספקא- עיין ברש"י. מרש"י משמע שגמרא אומר מימרא, והוא שממשיך לומר שכיון שמסופק, צריך להיות כן. לולי רש"י, היה אפשר לומר שמקשה גמרא שרק כאן אומרו, ואז נוכיח שיטתו, וגמרא אומר שאולי מסופק הוא, ואז אין להוכיח. מצאנו שקו"ט כזה בכ"מ. ותחשב.
53. ודווקא- מזו- משמע שאומרים לשון זה אף כשאינו הכי טוב. עיין במקומות אחרים שהבאנו משמעותים חלוקים בזה. אחרונים דנים קצת בזה.
54. דרבנן- ואם תאמר הרי בגט יכולים לתקן לבטל קידושין. ויש לומר שזה רק לרשב"ג, ולא לרבי. לא נראה כן, על כל פנים לתוס’. יותר נראה לומר שלא רוצים, בדרך כלל, לעשות כן, כיון שעושה ביאה באיסור. כמו"כ, יש לומר שאז סיבת התקנה לא כל כך מסתבר בגט. ויש להעיר שמרשי לא משמע כצד שני. אף לא משמע כל כך כצד ראשון, אבל אינו כל כך קשה.
55. כדי שיהא- נמצא שלא משיב לשאלת גמרא של "כיצד,” אלא אומר דבר אחר. רש"י מעורר זה, באמת, אבל יש להוסיף שהוא קצת יותר קשה, כיון שיכול להשיב על שאלת גמרא, לומר שהשיעור הוא כדי שלא יהיה אדם בא כלל. אפשר שסובר שאין שיעור כזה, שיכול אדם לבוא כהרף עין. לא נראה כן, שלכאורה, נונכל לדון ממה שלא ראינו אותו קרוב לכאן לפני כהרף עין. ותחשב. ואולי יכול אדם לזרוק את הגט. ותחשב.
56. שהה- לא מפרש שיעור שהייה. אולי הוא כדי השתחוייה.[fn:7]
57. כדי לכתוב- יש לתמוה קצת על שיעורים אלו שהם- כמו שבאמת רש"י מעורר- קצת ראנדו"ם.
58. יש אומרים- קשה, שמזכיר ר"נ וי"א, והרי הם אחד. אולי נאמרו בשני זמנים בחייו. גי"ל שאף שהיה ר"נ שהיה יש אומרים, אין זה סתם רבי נתן. אין כל זה פשוט לי, אבל יודע אני שמצאנו ר"נ שהיה חבר רבי. מסתמא, אין זה יש אומרים. אז, אולי זה ר"נ סתם, וזה ר"נ אחר. ותחשב. ונראה שלא קשה ממה שגמ’ בהוריות קורא ליש אומרים בשם ר"נ סתם, שהרי היה ר"נ סתם קודם מעשה זה, ורק אחר מעשה זה שינו את שמו, וממילא נעשה ר"נ אחר ר"נ סתם. ותחשב.
59. אירכס- שליח- ק"ק מהי"ת שהיה שליח, שלכאורה, יכול אף לבעל לאבדו. אולי בעל לא יחוש כל כך אם מאבדו למצוא אותו, שרק יכתב אחרת. גי"ל שבעל יהיה נאמן לומר בטביעות עין שהוא שלו, כיון שיכול לכתוב עוד אחר. ויש לדון, שאולי לא רוצה לטרוח כן.
60. טביעות עינא- שום סימן- לכאורה, בא לבאר מהו החילוק בין טביעות עין לסימן, שאם אין סימן, איך יכיר אותו. אז, אומר שאין סימן, אלא יש הכרה, שיש, לכאורה, קצת דברים, שכל אחד אינו סימן, אבל על הכל, הוא מכיר. ותחשב. ויותר היה נראה לומר שיש סימן, אבל לא זוכר אותו אלא כשרואה אותו. ותחשב.
61. לצורבא- קצת משמע שמחמת שני טעמים אלו צריך להיות צורבא מרבנן לחוד, ולא רק מחמת שרק הוא לא משקר. ותחשב.
62. מצאו קשור- ומכיר- או יש לו סימן. ואולי זה בכלל "מכיר.”
63. כח.
64. ומשני- היה אפשר לומר לא רק שנהפוך זה בזה וזה בזה, אלא אף יש אחרים להפוך גם כן. ותו"ת.
65. כיון דאיפליג- יש לדון מהי"ת לו שיעור זה. אולי סבר שהכל יש לו עשר שנה (שיש מן השאר, כמו חמישים וששים שהם כן, לכאורה). גי"ל שנתן חצי לגבורות וחצי לכיון דאיפלג. ותחשב.
66. שהרי אסרה- לא הבנתי את זה כל כך.
67. כט.
68. בזיון דבעל- ק"ק, אז, למה יכולים שלש לעשות שליח. צריך לומר שיכולים לעשות שליח, אף שבעל לא רוצה בזה.
69. כאן שנה רבי- ק"ק ל"ל אמר שזה אף מקור שאין שומר מוסר לשמור, שהרי כאן, לכאורה, לא יכול להשמתמש עמו. וצריך לומר, לכאורה, שכדי לדחות לשיטה שלא מוסר לשליח, צריך לומר שכאן מיירי בציור שהתיר לו להשתמש עמו. ויש לדון ל"ל רק ישלח לשליח אחר ויאמר לו שלא ישתמש עמו. ותחשב.
70. זו אפילו תנוקות- חושב אני שמצאנו גמרא (גבי מחלקת רבי יוחנן וריש לקיש, כשריש לקיש חזר בו מחמת משנה) שמבואר שלפעמים לא ידע ר"ל משניות. נראה שזה מפני שלא התחיל בחסידות, אלא היה מתחיל ללמוד מאת ר"י. אז, לפעמים לא ידע כל משנה. נראה שאף זה כן, שמצאנו בכ"מ שאומר רבי יוחנן לר"ל לשון זה (עיין בברכות ה.). אולי ממש לא ידע ר"ל שזה דבר פשוט וידוע, והיה צריך ר"י לומר לו. לשון "כי פליגי" לא משמע כן כל כך, שמשמע שממש חולקים. ויש לדון, שלא מוכרח שיודה ר"ל למש"א ר"י שני, שאולי רק הכיר שהוא פשוט. ויש לדון, שלכאורה כוונת ר"י הוא לומר שפשוט שאין זה חידוש של המשנה, ואז צריך לומר שמשנה בא לחדש כרבי יוחנן.
71. זה אפילו- מקניטו- לשון זה מעניין, שלכאורה האיסור הוא גניבה, ולכאורה, הקנטתו לא שייך לגניבה.
72. כט:
73. שליח בית דין אני- היה אפשר לו לומר שאמר לפניו בפני ב"ד שבפניו נכ’ ונח’, אבל זה יותר קל לומר (וגם יכולים לומר אותו בכל זמן, ואף שליח שני יכול לומר אותו לשון). עדיין יש לדון ל"ל חוששים לבית דין טועים[fn:8] (שלא יצרכו שיאמר ב"נ). ותחשב.
74. שליח דשליח משוי- יש לדון ל"ל ישוה שליח.
75. הא לא- משמע שלא שאל לאביו. מצאנו בכ"מ שכשאומרים לאדם לשאול, לא שואל, אלא משיב. נראה שכוונתם היה לשאול לו, ואמרו לשאול לאחר מחמת כבוד. כמ"כ, י"ל שאמרו לו לשאול כדי שלא יכירו שמכוון לשאול להם, ואז ישיבו[fn:9]. ותו"ת.
76. שליח שלא ניתן לגירושין- יש לדון למה זה בעיה, שלכאורה אף שלא נתן לו כוח לגירושין, נתן לו כוח לעשות שליח, ואז ל"ל יוכל לעשות שליח לעשות כך. ותחשב.
77. סמוכי- יש לדון אם היו סמוכים ממש או רק ר"ל חשובים. שמם (אומר "רבי") משמעים שהיו סמוכים. אם כן
78. לכאורה, צריך לומר שבאו מא"י.
79. ולא את- נראה שהצד שלא עשה אותו שליח הוא שאין צורך לעשות שהוא יש לו אותו כוח, שאין טוב בא ממנו. אולי החולק סובר שעשה אותו דילמא יכיר בו או כדומה, ואולי החולק סובר שכיון שנחית לו, אף שאין טוב בו ולא רוצה בו, ממילא יש בו אותו כוח.
80. נאמנת- ואם תאמר אין דבר שבערוה פחות משנים. ויש לומר שזה רק בחששות. זה אינו חשש כלל עד שיערער. אינו יכול לערער כיון שאמר זה. נראה שקצת מחודש שזה עושה שאין ערעורו ערעור. ותחשב.
81. הא ודאי- נראה שאולי חוזר על גמרא שלעיל שאמר מה שלא לשאול (אם עושה שליח…), שרבא אומר שאלו אין לשאול, אבל זה יש לשאול.
82. ואזל- לא ימסור דברים- צריך ביאור, שלכאורה אם טועה באמירה לו, צריך לומר ששכח. אם כן, יטעה אף הוא בנתינה. אז, אין פסול זה שייך למסירה לעוד שליח. ותחשב.
83. ואזל- אורחא- מעניין שזה נחשב אורחא דמילתא, שלכאורה עושים כן כדי שתצטרך לתת את החפץ. צריך לומר שבני אדם רגילים לעשות כן.
84. עושה כמה- עיין במה שבאר למה זה א"א בחו"ל. ק"ק למה בחו"ל א"א לומר שקיבל ממי שלפניו אמרו…. ויש לומר שלא נאמן אותו אחר אלא בפני שלש; אז, ממילא, צריך בית דין.
85. קפחינהו- עיין במה שבאר רש"י. קשה מגמרא בבבא מציעא שואל רבי, “יש בן לאותו ת"ח שהיה מקפח את בניו.” משמע שר"ל שימותו. כן פירש רש"י בשבת (פרק ראשון) בפירוש, וכ’ שר"ל לקצר. אולי קצרים הם אם מתים הם, שלא עומדים (או שמסריחים). גי"ל שמקצר ימיהם. עדיין צריך לבאר לשון "מלמטה" (שרש"י כ’ כאן שקיפוח ר"ל מיעוט מלמטה).
86. ל.
87. בפניו- צריך ביאור למה צריך להיות בפניו.
88. מי יהיב לה- לשון זה מוזר. לכאורה, על פי מה שיבאר גמרא לקמן, הטענה הוא שאין אונס בגיטין, והרי לא בא. אם כן, צריך ביאור מה אומר כאן, שמשמע שמכוון לומר שאילו היה אונס גמור, היה אונס בגיטין, אבל אין זה אונס גמור. ותחשב. אפשר שר"ל שאין לך תקנה אלא אם כן תתן תרקבא דדינרא. צריך ביאור איך נבאר את זה בתוך לשון גמרא, ואז לא נראה שכן פירושו. וצר"ב.
89. פסקיה מברא- רש"י מפרש שמברא ר"ל מעבר. אם כן, לכאורה "פסקיה מברא" ר"ל שהיה המעבר נפסק, ולא שהמעבר הפסיק אותו. לא נראה כן, שלשון "פסקיה" משמע שקאי עליו, ולא על המעבר. אולי כשאומר שמעבר פסקו, ר"ל שמה שלא היה מעבר פסקו. דחוק.
90. פייסא- לכאורה, אין זה אותו פיוס שאמר לעיל (כט:), שאז היה בטל הגט מעצמו, ולא עשה תנאי שום דבר. נראה שיש שני דרכים לבאר כאן:
91. אין פיוס זה פיוס של לעיל (של ביאה), אלא של דברים.
92. יש נפק"מ, שכאן עושה שחל מיד, ואז לא היה פיוס מבטל את הגט.
נראה שרש"י אומר שניהם, שאומר "עכשיו" (אבל עיין בשני הגירסאות), אבל גם אומר שפיוס ר"ל בדברים. נראה שרש"י ראשון בא לת’ להערה שלנו כאן, ושני לא קאי על פיוס (ולת’ הערה שלנו), אלא מבאר מה אומר שהוא פייס אותה, והיא לא נתפייסת, שלכאורה, אילו פיוס ר"ל ביאה (וכן סובר רש"י, שהרי צריך לתרץ הערה שלנו על ידי צד שני שכ’ לעיל), קשה איך פייס אותה והיא לא נתפייסה. אז, אומר שכאן פיוס ר"ל בדברים. ותו"ת.
** להיות -
ואם תאמר למה יעשה כן, שאז לא פורע כל כך מהר, שמאבד תרומה, שהיו שווים כחולין לו, שיכול לאכול אותם, ולא פורע כל כך בתרומה, שלא נמכר להרבה ממון. שוב הבנתי שפשוט שאינם כל כך טובים אף לכהן, שיכול הוא לקנות תרומה, ואז לא מהני כלום אם יקבל אותם ויתן ממון אחר, שאז הוא כקונה אותם. זה פשוט, ותו"ת, ורק כתבתי אותו כיון שחושב אני שטעיתי בנקודה זה בשיחתא דשי על דמאי.
** ליטול רשות -
ואם תאמר כיון שאין חוב זה עליהם למה יסכימו. וי"ל שבלי זה, לא ילווה ממון, והרי אף הם נהנים מאותו הלוואה, שהם יורשים.
** אינו צריך -
אין צורך להטיל חוב זה על כל כהונה, שיכולים להטיל רק על כהן אחד, ולעשות שעושה כן לו. ותו"ת. [fn:10]
* לא:
** של מוצאי החג של תקופה -
עיין במה שבאר רש"י. צריך ביאור, שמגמרא סנהדרין (יג.) מבואר שצריך להיות תקופה בתוך החג. אפשר שזה רק בזמן שמעברים את השנה כפי הצורך, אבל אולי בשנים אלו קורה כן. קשה, שלכאורה בזמן הברייתא עדיין קדשו כפי הצורך. ותחשב. אולי כאן ר"ל מוצאי חג ראשון. גם יש לומר שר"ל מוצאי של חג שקרה בתקופה חדשה (וצריך לומר שלא ר"ל שמקצתו בתוך תקופה חדשה, שכל חג צריך להיות כן, אלא ר"ל שמקצת חשוב של חג כן).
** פרוס -
איני יודע כל כך מה זה. חושב אני שיש רש"י בשום מקום שמבאר מהו. ראיתי בסונסינו שכתבו שהוא קצת מוקדם.
** מכאן ואילך -
צריך ביאור מה אומר, “מכאן ואילך,” שהזכיר שלש זמנים. אם קאי על כולם, פשוט שאינו כן, שאם כן, כולל כל זמנים. אולי מודים שפוסק בשום זמן (אולי התחלת שנה או כדומה). גי"ל שרק קאי על אחד. יש לדון על איזה אחד קאי. גם צריך ביאור, אז, למה צריך מה שבא אחריו. אולי אומר השעה שפוסקים. ותחשב על כל זה.
** תלמים -
צריך ביאור מה זה אומר. נראה שיש לחקור אם עושה כן ברוח שהולך או לא. זה אומר שכשחורשים בשור, עושה תלמים במקום שהולך, שאם תלך מזרח מערב כשהולך צפון דרום, תפגע בכמה וכמה תלמים. אז, היה נראה לומר שכן הוא כאן, שהרוח בא ממזרח למערב, וכשתלך מצפון לדרום, תפגע בכמה צלמים. יש לדון איזה מין רוח משנה יעשה כן, שרק יגע במקצת מקומות. ויש לדון. גם יש לומר שעושה תלמים באופן שהפוך לו. אז, אם תלך מזרח מערב כמותו, תפגע בתלמים. קשה, שכל רוח עושה כן, והם נקראים waves. נראה שר"ל שהוא כל כך חזק עד שעושה כמה, ועד שאחד נשבר, כבר יש הרבה אחרים. אז, נראה כתלמים. ותחשב על זה.
** אלמלא כן -
יש לדון מה נצרך. נראה שהוא רוח צפוני עם רוח דרומית. ותחשב.
** מעיינו -
יש לדון ל"ל אומרים עובר שהוא במעיה. ויש לומר שזה כבר נדרש. אם כן, משמע שכולם מודים כלכל הדרשות. כן, באמת, משמע מן הגמרא. ותחשב. לולי מה שאומר גמרא כאן, היה נראה לומר שקאי על שכבת זרע כיון שהוא אחד מן המעיינים של איש שמטמא בזבה. ותחשב.
** שדיא -
בסנסינו אומר שאולי ר"ל רוח מזרחי או שד נקבה. צריך ביאור ל"ל אומר מילה רגיל לראשון, וצריך ביאור מה אומר שני. ותחשב.
** כשמשקיט -
סנסינו אומר שר"ל שה’ משקיט אותו רוח. ותו"ת.
* לב.
** אמר רבה בא אבוה -
יש לדון מה משנה לשון זה (שיש לדון אם רק אומר שרבה בא רבוה אמר בשם ר"ש). לא נראה שיאמר בשם ר"ש, שהיה ר"ש חבר של ר"נ, ורב"א היה רבו של ר"נ (וגם אולי היה חמיו. עיין ביבמות בסוגיית סריס). ותחשב.
** בטל -
חושב אני שבטל קצת משמע דבר שהיה טוב ושוב נעשה שאינו טוב. נראה שזה יכול להתקיים כאן אם התנה עליו, שהיה עמוד לו לחול, אבל שוב לא נתקיים התאי, ולא חל. ותחשב.
* לג.
** כל דמקדש -
עיין ברש"י פסחים (ז.) בביאור ההוה אמינא של רבינא. לשון "כל דמקדש…" קצת מוזר, אבל יש להעיר שאפשר ש"הפקיעו קדושין" לא ר"ל שהפקיעו הקידושין עצמם, אלא מעות הקידושין. על כל פנים, יש להעיר שרש"י כאן לא משמע כלל כרש"י בפסחים, שמבאר המסקנא, אז, בהוה אמינא. ותחשב.
* לג:
** הכי נמי -
עיין במה שכתב. גם היה אפשר לומר שר"ל שאילו היה המשנה כן, שפיר היה ראיה משם. כעין זה מצאנו גבי אומר לשליח שיעשה כמה שאמרה אשה, בתחילת פרק האומר (וכן בבבא מציעא). ותו"ת.
* לד.
** משום דפנוי -
ר"ל, שהיו מכים אותו אילו לא נתן אמתלא לביטולו. מילה זה גם כן נאמר ביבמות, בתחלת פרק האשה רבה. לא ידעתי מקורו (למה אומר הכאה). אולי בא ממילת "דופן,” והיו דרכם בהכאה בדרך כלל, או בהכאה זה, להכות על דופן. דחוק.
** אטו התם לבטולי גט -
נראה שני מהלכים בזה. אפשר שאמר שאף שהיה רוצה בביטול גט, לא כיוון לבטל אותו, שהרי חשב שכבר בטל מחמת שלא קיים תנאו. יש להעיר שמעניין שרבא לא מחשיב דעת בכוח, אלא רק דעת בפועל. הרי, רבא הוא המתיר יאוש שלא מדעת.[fn:11] מהלך השני הוא שרק רואים שרצה בקיום התנאי, אבל לא בביטול הגט. יש לדון למה ירצה בזה ולא בזה, שאין נפק"מ, לכאורה. אולי לא רוצה לחזור על דבריו. גם יש לומר שרוצה לגרש עוד בגט או בשליח זה. דחוק.
* לד:
** מפני תיקון העולם -
צריך ביאור מה טוענים. אם בא מבעל, הרי בא מבעל. אם לא בא מבעל, אלא מזוייף הוא, צריך ביאור למה כתב שם שאינו נכון. אלא, צריך לומר שהוא נכון ויש לו שני שמות.
אפשר שחוששים שהיה לה עוד בעל, והוא נתן לה גט זה. ויש לדון, שאולי אפשר להוכיח על פי זמן הגט. ותו"ת.
** והוא דאתחזק -
לשונו משמע שצריך לכתוב "וכל שום,” ולא לכתוב כל שום. יש להעיר שאם צריך לכתוב כל שום, קשה, שהרי מהו המיעוט של לא איתחזק, שלא יכול לכתוב שם שלא יודע. אפשר לומר שאומר שלא צריך לטרוח למצוא אותו, וגם אפשר שלא מעכב בדיעבד.
** מגורשת -
כל שמותיו שהחזיק עצמו בהם- ואם תאמר הרי רש"י אומר שלא כותבים שמות כלל, אלא "כל שום.” ויש לומר שרש"י מודה שאם כותב כל השמות מהני. אז, אומר שאף שידוע שהוא איש שיש לו כמה שמות, לא מניחים שיש לו יותר שמות ממה שהוחזקו, ולא צריכים לכתוב, “כל שום.”
** בשבועה
- כן הוא אף במודה במקצת, שלכאורה יש אותו דין ששיך. ותחשב.
** שתהא
- מיני מזונות- ראשונים כתבו שצריך להיות דבר שיכולה לקיים. אם כן, צריך לומר שמיני מזונות אפשר לקיים. ותחשב. וצריך לעיין בגמרא שמבאר מהו (בנדרים ובמק"א הוא).
** העדים חותמים
- היה לו לבאר את זה לעיל.
* לה.
** של אותה אשה -
נמצא שאף שאמר בלשון סגי נהור, לא הועיל, ועדיין בא עלה כללה. זה מעניין.
* לה:
** זימנים דגייז -
ואם תאמר הרי אם לא אומר, בהכרח מגייז. ויש לומר שאז ידע החכם שצריך לשאול, שידע שלא אמר כל מה שקרה.
ויש לדון, שאם מניחים שחכם ישאל, אז קשה למה חוששים לעבירה. ותחשב. אולי אין הכי נמי, חולק, וכשאומר שחוששים לעבירה, כולל כל מה שצירך חכם לדעת.
** מילתא דאיסורא -
יש דברים אחרים, כמו אם כבר עבר על נדרו, שבו לא יתיר לא נדרו. יש לדון ל"ל מזכיר אותם, כיון שהם יותר בפירוש בגמרא (בנדרים).
** נושא נשים -
יש לדון אם זה בכל אסורות או רק באיסורי כהונה. הסיבה שיהיה רק באיסורי כהונה יהיה אולי מפני שהם יותר חמורים או ממדה כנגד מדה (שכיון שהוא בועט בכיהונו, פסול).
** משום איסורא -
זה חשש מעניין, שצריכים להניח אדם שירא מן הנדר אבל לא מן העבירה.
** נודר
- הנאה- יש לדון למה צריך לאסור הנאה, שיכול רק לאסור ביאה. אולי צריך לאסור הנאה לגדר (שלא יבעול אותה).
* לו.
** דמדרינן על דעת -
אולי ר"ל שעושה חלות חלוק מנדר, אלא עושה שאחרים נודרים לו. אז, אין הפרה ואין שאלה, שאין אחרים שואלים, והוא לא יכול לשאול על חלות של היתר לאחרים לנדור לו, אלא על חלות של נדר שאמר.
** לר"א -
ר"ל, מצאנו תנא שסובר שאינו חיוב. לא מבאר למה אין הקרא חיוב, אבל יודעים שיכול להיות שאינו חיוב, שמצאנו תנא שסובר כן.
** כדתניא
- עיין במה שהביא מאותו גמרא בכתובות. היה אפשר לומר, לכאורה, שנוכל להוכיח משום שטר אחר שלא לטובתו, שלכאורה רק מניחים שאולי זייף כיון שהוא לטובתו. אולי צריכים לדעת שאינו פסול. ויש לדון. גם יש לומר שאולי חוששים שהיה עד אחד על אותו שטר אחר. אםכ ן, צריך לומר שזוכרים מי היו העדים על אותו שטר אחר, ואינו הוא, ולא רק שהוא מקויים. ותו"ת.
** בדיסקי -
וידעו שהוא שלו כיון שהיו נכתבים בתשובה, שהיה אדם משלח לו, והוא היה משיב. ותחשב. (ועיין ברש"י, שאינו רק שו"ת.)
** בזמן הזה
- מנו יובלות- משמע שאין יובל נוהג מדרבנן. יש לדון למה הוא חלוק משביעית.
** רש"י
מביא דרשה מירושלמי מאותו קרא של רבי. אם כן, קשה איך נאמר שהלל סבר כרבי וכירושלמי.
** שמוט -
נראה שדרש מכפל לשונות שמיטה.
* לו:
** ומי איכא -
ואם תאמר הרי יש איסור בקו"ע של גניבה. וי"ל שכיון שהלואה הוא, אינו גניבה, אלא שרק יש לו חיוב להחזיר. מה שקורא לו רש"י גזלן הוא שמצאנו בב"ק שלפעמים נקרא אדם גזלן אם לא משיב מה שצריך להשיב. ותו"ת.
** בבי דינא דסורא -
צריך ביאור מהו ההוה אמינא להביא ראיה מכאן, שלכאורה, זה רק אומר שרק מבטלים בבתי דינים מיוחדים. איך רואים מכאן שרק תקן לדורו. נראה שמניח שהצד שהיה מתקן לדרי עלמא הוא שהיה מתקן לכל אחד, ולא היה מחלק בין אם מסתבר לתקן שם או לא. אז, אף כך לא יחלק. וצריך ביאור.
** עלובה כלה -
ואם תאמר אולי ר"ל שלא עושה לרצון אחרים אלא לרצונה, שעשתה נבלה זאת. אז, עדיין יכול להיות משמע ניחותא, כמו שמפרש רש"י אותו. נראה שאולי היה לנו לומר שהיא חצופה, שהרי הוא חצופה, וזה יותר רע מניחותא. ותחשב.
** שמחים ביסורים -
יש לדון אם זה ר"ל כל יסורים, יסורים שמכפרים, או יסורים של אהבה.
** עושים
- מעניין שלא ממעט עשייה מיראת הרוממות. משמע שזה טוב כאהבה.
** שזינתה
- ממדבר סיני- יש להעיר שהיה אפשר שלא היו עדיין בהר סיני, שרק אומר שנסעו ממדבר סיני. אולי היה לו להזכיר אותו אילו יצאו מהר סיני. גם יש לומר שנחשבים כמו מקום אחד. כמו שלא עברו, מסתמא, במקום שקבלו תורה ממש, ועדיין הוא קרוב די להיות נחשב חצופה, אף אם היו קצת יותר רחוקים, יהיה קרוב די להיקרות כן. ותחשב.
* לז.
** בוטי -
לכאורה, זה אינו במילת פרוסבול. אפשר שנקט מילה של עשירים שגם התחיל באופן שווה למילת עניים כדי לכלל עניים. ותחשב.
** מקום לתנור -
לכאורה, יכול להיות אף פחות, שיכול להיות כל שהוא.
** מאי כל שהוא -
לכאורה, צריך לומר שהמשיב שאל, שגמרא בב"ב משמע שמסתבר שכל כל שהוא הוא ממש (והרי כאן, לכאורה, אומר שהוא ממש). לכאורה, צריך לומר רק מפני שמצאנו כל שהוא שאינו ממש. ויש לדון, שאולי מפני שמצאנו במקצת מקומות שלא מסתבר להיות כל שהוא, מצדד כאן. ותחשב.
** לא צריכת -
לכאורה, ר"ל שמסר בדיבור, ולא הוצרך לכתיבה. יש לדון אם זה כמה שהיה רוצה ר"נ, או שהיה ר"נ רוצה שאף בלי דעת, הכל יהיה מסור לבית דין.
** צריך ביאור
ל"ל צריך להיות לו הקרקע בשעת הלוואה, שלכאורה הרגיל הוא שילווה כשיש לו קרקע אז. ותו"ת.
** אלא על הקרקע
- קטינא- יש להעיר שזה רק אם חוזר ופודה הקרקע עוד ועוד. לכאורה, אין לו לסמוך שיעשה כן, ואז אינו רגיל.
** לתנור -
צריך ביאור מה לנו במה שהם מטלטלים.
** דמנח אסיכי
- ואם תאמר הרי עדיין משתמש במקום שעליו עומדים סיכי. ויש לומר שיש דברים אחרים עליו שהם לצורך המשאיל, ואז אינו שאול לו. ותחשב.
** קריביה
- יש לדון מהיכי תיתי (ואולי הלשון משמע כן), ומה לו בזה.
** וכי מפני שאנו מדמים -
לכאורה, כאן מוכרח כמה שאמר רש"י לעיל (יט.), ולא כמו שמצדדים שם לבאר את הרמב"ם (שסובר שמחלק בין גט לשבת).[fn:12]
שמעתי שאף ר.ש.ח.ל. הביא ראיה זה.
** ולך תהיה צדקה -
לכאורה, ר"ל שממה שנחשב לו צדקה, צריך לומר ששלו הוא, שאי לאו הכי, הרי חייב להחזיר אותו. ואם תאמר היה לו להוכיח ממה שמותר לו שלא להחזיר אותו ביום, ואם אינו שלו, הרי הוא גזל. ויש לומר שה’ התיר לו ליקח אותו, ואינו נחשב גזל אם לוקח, אף שאינו שלו. ואם תאמר הרי אז יש לומר שנחשב צדקה, אף אם אינו שלו, שהרי יש לו היתר לקחת. ויש לומר שכיון שלא התיר ה’ אלא לאותו זמן, כשאינו באותו זמן, אין צדקה במה שמשיבו, שאינו חלוק מחפץ אחר, ולא נדחים זכויותיו. אבל, אם קונה אותו, מסתמא קונה לכל זמן (שלא מצאנו קנינים שחוזרים וחלים וחוזרים ופקעים…). אם כן, כשחוזר אותו, הולך נגד זכויותיו. אף שחייב לעשות כן, יש צדקה במה שעושה נגד זכות שלו. ותחשב.
* לז:
** זה דבר -
יש לדון איזה חלק ממנו הוא החידוש:
1. צריך להשיב לו דבר.
2. מותר לקחת אחר שהשיב לו דבר.
ודע שאפשר לומר שמגלה אחד, וכיון שגילה אותו אחד, השני חידוש. ותו"ת.
** דאמר ליה הכי -
יש להעיר שאז צריך ביאור למה אומר, “משמט אני,” שמן הלשון שאמר, פשוט שכבר ידע חברו שהוא נשמט. ותחשב.
** דאמר ליה -
צריך ביאור למה יחשוב אביי שקשה רק לרבה, שהוא רק קאי על הברייתא, ואומר שמה שאומר בברייתא מותר לכפותו לומר. ותחשב.
** דאמר ליה -
קשה, שהוא תליוהו ונתן, ולא חל.
** דהוא אבא -
אולי מניומי היה שם אביו, ומרתא היה שם אמו (או להיפך). אבל, דע שמצאנו אמוראים שיש להם יותר משני שמות.
** ר"י אמר ר"נ -
לא מצאנו, בדר"כ שיאמר ר"י דבר בשם ר"נ, שהיה ר"י תלמיד של רב, ור"נ היה בתוך אותו דור (ואולי קצת אחרי) ר"י. ותו"ת. ויש שאין גורסים כן כאן.
** תנן וכן -
אולי לולי רב אין זה ראיה, שאפשר שר"ל כשאינו טוען כן, ומחדש שלא טוענים לו כן. אבל, נראה שהתנאי שמביא אחר כך מכריח מחלקת תנאי לכולי עלמא.
** מעשה ידיו -
יש לדון אם ר"ל קנין פירות או קנין גוף של שאר נכסים, ורק לא נשתנה גוף עבד להיות מין אדם אחר. ותו"ת.
** צריך ביאור
למה פשוט לגמרא שעבד נמכר לגוי בלי דיני עבד עברי, כיון שנלמד ממנו.
** מפיל עצמו -
לכאורה, לא מהני כל כך, שמסתמא אם היה פודה אותו לשם בן חורים, יפדה אותו וישחרר אותו. ויש לדון.
* לח.
** כל מקום ששנה -
אגב, יש להעיר שיש לדון אם זה סיבה (שרשב"ג אדם חשוב) או כלל (רק אומר שקרה כן). מה שאינו כן בברייתות ומה שאינו כן אם לא נשנה בשמו משמע דלא כראשון. אבל, השני קשה, שאיך אירע כן. אז, נראה שהוא סיבה, אבל הוא קצת חלוק, אלא שרבי רק אמר בשם רשב"ג מה שהוא מסתבר לו מאד, לכבד את אביו. אז, הלכה כמותו, כמו סתם משנה. נראה שאולי לכן סבר גמרא בב"ק שכלל זה וכלל של סתם משנה שווים, שהרי לשניהם יש יסוד אחד, והוא שיודעים שרבי סבר שהוא נכון. ויש לדון, שלא מוכרח שם, שי"ל שהיה פוסק כסתם נגד רשב"ג, ורק קשה למה לא נזכר בתוך מה שמנה ר"י.
** בחזקה
- נמצא, אז, שחזקה ר"ל קנין חזנ ולא מה שגבר ידו עליו. אם כן, צריך לומר שעשו כן בני סיחון לכל ארץ עמון ומואב- ואין זה כל כך פשוט, שיש גדרים לקנין חזקה.
** עובד כוכבים
- צריך ביאור, שלשונו (“מישראל") משמע שהוא חידוש כיון שקונה אותו מן האדון שהוא ישראל, ולא כיון שהוא בר מצוות. ותו"ת.
* לח:
** וכפו את רבה -
צריך ביאור למה אומר כבר שלא יכולה לישא שום אחד, שלכאורה, חילוק זה הוא נעשה רק במסקנת גמרא. אולי סובר שאין זה מה שנתחדש, אלא דין ייחוד עבד הוא מה שנתחדש. עדיין יש לדון, שאז צריך לומר שלא צריך כך, אלא אף אילו לא היה אסור לה לבעול לעבד, היה אותו בעיה. ותו"ת.
** עבד -
יש לדון אם זה מין נשואים ממש, והיא קצת כאשת איש, ואז לא תזנה, או שרק ר"ל שאז אותו עבד ישמור אותה בידים. ותחשב.
** ושחרר עבדו -
לכאורה, רואים מכאן שאין עבד מצרף למנין. לכאורה הוא מפני שמקור שדברים שבקדושה צריך להיות בעשר אומר שצריך להיות בעשר ישראל (שכן הוא שם). ותחשב.
** ודילמא ר"א -
ת’ גמ’ צ"ב, שאם ידע שלא סובר ר"א כן, אז אינו קשה על שמואל, אלא על ר"א לשיטתו.
** ודילמא ר"א -
יש לדון בזה, שלכאורה, לא ידע שמואל שחלקו בזה ר"ע ור"י, שאז היה לו לומר שהלכה כר"ע. ונראה שאולי כיון שהוא ברייתא, לא היה לו לומר כן. ותחשב.
גם יש לומר שאף ששמואל לא ידע אותו, גמרא יודע, ואז היה לו לגמרא לומר כן.
** בעידן בי מדרשא -
מרש"י נמצא שלא רק ר"ל שהיו להם ללמוד אז (אכלו ליותר זמן) אלא שהיה דרשה אז. יש לדון ל"ל אמר הרב דרשתו בזמן אחר. אולי רק היו מיעוט בני אדם אוכלים אז. יש לדון, שמשמע שבעלי בתים עושים כן. ואם תאמר אולי רק אומר שבעלי בתים שיורדים, מחמת זה יורדים. קשה, שאם לא אומר שבעלי בתים יורדים, ומחמת זה יורדים, קשה למה מזכיר בעלי בתים. יש לומר שלת"ח, יש זכות שמציך ממקצת אלו. גם יש לומר שמחמת שעוסק בתורה, יש דברים אחרים שעושה שהוא יעני.
** מתניתא -
לשונו משמע שזה דבר פשוט, אבל בדר"כ, גמ’ מנסה לעשות שלא צ"ל כן. וצ"ב.
** בע"ש -
עיין ברש"י. גי"ל שרק ר"ל שאכל בחול סעודה שאינה של מצווה, כמו שאומר גמרא בפסחים. אז, יום ששי אינו דווקא. כמו"כ מצאנו שיום שני אינו דווקא, כמו בסנהדרין (גבי שמירת שבת) ובמק"א.
** גופיה לא -
יש לדון ל"ל ראוי לבדק, שיכול לבנות. י שלדון אם זה נחשב הוא עצמו קדוש. גם יש לדון אם עבד כשר לבנןי בית המקדש.
** המקדיש כל נכסיו -
היה אפשר לחלק ששם אי אפשר לומר שעושה את הכל לישראל. ותחשב. גם יש להעיר שלכאורה, קדושה נתפשט לתת קדושת הגוף. יש לדון אם זה שייך כאן. ותחשב.
* לט.
** אין אדם -
מחודש (אבל אומר אותו כאן לתרץ) לומר כן אף כאן, שהיה כוונה במילים שלו, אבל רק לא להקדש.
** איהו -
לכאורה, ר"ל שפשוט שלא מכוון לדמי עצמו, שאין אדם חושב על דמים של עצמו, כיון שהוא איו עומד לעבדות. ותו"ת.
** מכחש -
יש לדון אם הוא מפני שהם מתבשלים ביותר, וזה רע, או שכשנתבשל ביותר, הוא נופל, וזה רע לו.
** מחכש -
יש לדון אם הענין הוא שלא נחשב כל כך מחובר, כיון שלא בא טוב ממנו, או שכיון שלא בא טוב (ובא רע), הרי יותר עומד הוא שיקצור אותו. לכאו’, מה שאומר שבא רע, ולא רק שלא בא טוב, משמע כצד שני (על כל פנים, שאף צד שני נכון). ותחשב.
* מ.
** רמ"א מקודשת -
היה אפשר לומר שמוכיח שהוא בן חורין, אבל לא עושה אותו בן חורין, ואז, לכאורה, לא יהיה סתירה. ותו"ת.
** דלעבדיה -
יל"ד, שאין אדם חוטא ולא לו, ואז יש לומר שאולי רק חוטא כיון שנהנה בו.
** עבד שהניח -
משמע שאין לעבד ואשה להניח תפילין. אולי הוא מפני גוף נקי. אפשר שיכולים, אבל לא נהגו, שלא רצו עבדים בקיום מצוות.
** אמרו לפניו -
כ"ז עד רשב"י הוא בדיבור ר"ד.
** איסורא הוא דאיכא -
משמע שאיסור הוא קצת של האדון (לכאו’, ר"ל שבא מיחס לו). אם כן, צריך ביאור מה קורה אחר שמת, שלא מוריש אותו, כמו שאומר גמרא[fn:13], והרי הוא מת. אולי צ"ל שיכול להיות יחס למת. גי"ל שמחמת שהיה יחס, עדיין נאסר. זה מחו’.
אפשר שלשון זה לאו דווקא, ורק ר"ל שיש איסור שבא ממה שזה היה קונה אותו. ותחשב.
** שהניח
- לילה- וכן שבת אינו זמן תפילין.
* מ:
** אעשנו -
עיין במה שבאר רש"י. מעניין שנחשב עתיד. לכאו’, יש לדון מהו שעת הכתב. במילים אחרים, בכל זמן שנאמר שדבר נאמר על שם עתיד או על שם עבר, צריכים לדון עתיד ממה. בדרך כלל, הוא עתיד משעת דיבור. אף בזה, צריכים לדון אם הוא עתיד מכל הדיבור, מקטע ממנו, ומאיזה קטע (שום קטע, קטע מסויים. אם הוא קטע מסויים, יש לדון איזה; אולי הוא ראשון, אולי אחרון, ואולי אמצע.). כאן, שכותב, צריך לדון אם הוא זמן כ’ או זמן מסירה או זמן קריאה[fn:14]. לכאו’, צריך להיות עתיד. אז, אי אפשר להיות זמן קריאה. אולי הוא זמן כ’. גם אולי הוא תחילת שעת מסירה. ותחשב.
אבל, לשון עבר גם יכול להיות מהני. אולי זה מפני שיכול להיות יותר מזמן אחד לאותם מילים, ומניחים איזה שיהני. גם אפשר שאולי לשון עבר מהני כיון שלא חושב על החלות כשאומר לשון זה, אלא חושב על עשיית שטר, שעושה שהחלות עומד (או שום דבר כעין זה).
** אמר
- הודה- ק"ק, שמשמע שבאלו דנים מה קונה, ולא מה נחשב הודאה. ותחשב. אולי סבר שכיון שהוא לשון טוב להודאה, גם יהני עם שטר. דחוק.
** אמר
- נמצא שרש"י סובר שהוא נחשב לעתיד גבי עבד אבל לא גבי שדה. ראשון, צריך לומר שרש"י לא סובר שהוא עתיד משעת כתיבה, שאם כן, שניהם עתידים. אלא, נראה שסובר ששעת הדיבור הוא שעת מסירה. אבל, בחירות, חל אחר כן. יש לדון למה. אולי הוא ממש חל אחר כך. זה יהיה כיון שצריך לקנות את עצמו. אז, יש יותר דברים שצריכים לעשות (חלות של קנין ממון יחול, ויקנה את עצמו). גם אפשר שאינו ממש זמן, אלא הוא אחר עוד סיבות. על כל פנים, צריך ביאור קצת למה לא יהיה זמן ממסירה עד חלות, אם מניחים שחלותים שוהים לבוא.
ובענין שהיית חלותים, עיין במרגנליא.
** שורת הדין -
לכאו’, אף בלי רבא, לא היה העבד חייב כלום, אלא היה עבדו. לכאו’, צ"ל שכן ר"ל.
** חמץ -
לכאו’, אביי יחלק על דין זה, שסובר שכל גיבוי קורה למפרע. אולי אף שנחשב שגבה אותו למפרע, הרי היה ברשותו של ישראל. וצריך לעיין שם בפסחים.
* מא.
** שפיר נאה -
עיין בגמ’ תענית ונדרים שאומר שיותר קל ללמוד למי שהוא מכוער. אם כן, זה רע לו. יותר מזה, יש להק’ שאז נמצא שכינו לו שם מגונה.
נראה שאולי היה לשון סגי נהור. (ויש לדון, שחושב אני שכ’ במק"א שהיה שופריה מעין שופריה של ר"י.) אולי אינו רע, שאיה"נ אינו ת"ח כ"כ, אבל היה אנוס. ויש לציין למה שאומר כן גמ’ על כמה וכמה ת"ח. וצ"ב למה. (באמת, אומר שצ"ל כה"ג גדול בנוי.)
** גובים -
נמצא שיכול לוה למכור, ולא רק שיכול מלווה לקחת מדבר אחר אם רוצה. זה מחודש, ויש לדון מהיכי תיתי, שלא אומר גמרא כן בפירוש. ותחשב.
** את עצמו -
לכאו’, ר"ל שתקנתם דין עבדות שלו, אבל לא חיוב פו"ר. נראה שאולי ר"ל שרבו מתוקן לגמרי, שרק שייך לדין ממון, אבל הוא לא מתוקן, ששייך אף לדין פו"ר.
** ויאמר לו עבדי -
יש לדון למה רק אומר כן על בניו. ויש לומר שלא יעיזו לומר כן לפניו. גי"ל שלא מעיזים, אלא שוכחים, ולא ישכחו בחייו, או אם יטענו כן, ידע להחזיר להם לומר להם טעותם.
** צריך לדון
בכל גמרא זה בחיובי הנאה. לכאו’, צריך ביאור למה עבד חייב כלל לתת דמיו. לכאו’, צריך להיות מחמת הנאתו. אז, צריך ביאור למה לא חייב אם מזיק שעבוד חברו חייב. אולי הוא מפני שחברו כבר שלם לו. ויש לדון למה חברו ישלם לו ולא הוא. ותחשב.
** שאינו ניכר -
מעניין שלא נחשב ניכר, שהרי ניכר הוא שיש קול, אבל רק לא ניכר זה בגוף העבד. כמו"כ יש לומר שלא ניכר מה שצריך להיות משוחרר.
ויש לדון אם ההיזק הוא מה שעבדו הוא במצב שצריך לשחרוו או שאחר כך עבדו משוחרר (וסובר שעל גרמי חייב. ונראה שאולי אף ראשון גרמי, שגורם חירות, שגורם קול, שגורם תקנה. ויש לדון, שאולי לכן תקנו, אבל כיון ששחררו, ויגרום קול, הרי נפחת מדמיו. ותו"ת.). ותחשב.
** שאין דרכה -
זה רק נכון אם נגדיר את השדה ל"שדה זה,” ו"שדה זאת,” שעל כל אחד, לא סומכת. אבל, יש לומר שיודעת שתבוא לה כל שדה שיהיה בן חורים אז. אולי זה לא נחשב סמיכה, כיון שלא יודע אם יהיה אחד כזה או לא.
אבל, צריך ביאור למה צריכים שהיא תסמוך דעת; אולי כוונה שרוצה אותו ספק. אז, י"ל ששאר שדות עדיין יבואו לו.
* מא:
** לא תוהו -
מעניין שזה רע, אף שהוא אנוס. אז, היה לנו לומר שה’ מצרף מחשבה למעשה, או שהוא אנוס ואז פטור, ואז אין רע כאן. צריך לומר שאין אנוס כמקיים מצוה (על כל פנים במצווה זה). שמעתי שתוס’ אומר שהבעיה הוא חיוב רבו. אבל, קשה, שמשנה אומר שתקנו את רבו. אולי לשון זה בין כך ובין כך קצת קשה, אבל עיין לעיל שישבנו אותו. ותחשב.
** לכסף -
אין הענין, באמת, שהוקש לכסף, אלא שהוקש לקרא שאומר בעצמו מה שיכולה להיות חצי וחצי. (ונראה שצ’ נקודה זה, שאל"ה, היה אפשר לומר שרק אפשר אם היה של שני אדונים וכדו’.)
** חציה -
צריך ביאור למה לא אומרים שמה שקנה עבד קנה רבו, ויחזור החצי. יש לדון אם קנין חצי עבד חזק לזה. (יש להעיר שאם הוא קנה לקנות חצי ממה שקונה עבד, יחזור רבע, ושוב 1/8, ושוב 1/16….) אפשר שקנין עבד חלוק משאר קנינים, ולא ניתן לאדון. גם יש לומר שאין עבד קונה א"ע, אלא הוא רק משוחרר. ותחשב על זה. גם יש לומר שקנה הקנין ופקע, ואין חצי עבד חצי בן חורים יכול להיות נקנה ביותר מחצי קנין, כמו שבן חורים לא יכול להיות נקנה. ותחשב.
** מה אשה חציה -
לכאו’, זה נגד ר"א, שסובר שיכול לגרש חוץ מבני אדם. אולי שם לנגד זה היא כולה מגורשת ולנגד זה לא מגורשת. צריך ביאור מה זה ר"ל.
** רבנן -
משמע שהיקש לא נחשב כתוב בפירוש. אולי רק לא נכתב כל כך בפ’, אבל הוא עדיין יותר מקל וחומר.
** רבנן
- מסיני- חול’ ראשונים כמה נאמר מסיני (אם נאמר כל דין, או כל אותיות (שני המקומות), או רק מקום אחד, או רק האות עצמו (ולא המקומות). יש לדון אם רש"י משמע שהרבה נאמר בסיני. ויש לדון.
** דברה תורה -
מעניין שדיבור בני אדם, אז, לפעמים כופל דבר (“העניק תעניק"), ולפעמים אומר דבר והיפוכו (“הפדה לא נפדתה"). נראה שפאזיטי"ב הוא כפול, ונגיטי"ב הוא דבר והיפוכו. עדיין מעניין הוא.
* מב.
** בעבד של שני שותפים -
היסוד הוא שלא יכול להיות עדיין נשאר לרבו שמשחרר אותו, כעין מה שאי אפשר להיות נשאר לבעל יחס לאשתו. ותו"ת.
** אבל שחרר חציו
- ומכר תחילה- לכאו’, זה פשוט, שהוא שותפים. אולי מחדש שהוא כן אף אם לא היו שותפים מתחילה. לכאו’, זה קצת פשוט. ותחשב.
** חצי -
מעניין שמניחים שהוא אותו חצי, ולא שלא נתן לזה מה שנתן לזה.
** ה"נ קאמר -
מעניין שלא רצה לומר כמו שהקשה לעיל, שבא לגלות.
** עבדי שהיו כבר -
עיין לעיל, שדיננו אם חלות חל לאחר הסיבה או בשעת סיבה. אם חל לאחריו, הרי בשעה ששטר עושה סיבה, עדיין עבד הוא. קצת משמע שלא חל אז.
** עבדיו -
שם לא כ’ בשטר, אלא במשנה.
** לא יצא בן חורין -
יש לדון למה לא חל נתינת הקרקע. אולי הוא שלא יכול לקחת קרקע, כיון שהכל ספק. זה מחודש, שעדיין חל, אלא שלא יכול לקחת אותו. אולי ר"ל שלא פי’ יפה איזה קרקע נותן, ואז אין החלות חל כלל.
ויש להעיר שמחודש שנחשב חלק מן השטר, שהבעיה גופא הוא שלא כתוב כל כך בשטר. ותו"ת.
** חוץ מאחד -
עיין במש"כ. לכאו’, היה אפשר לומר שרק משייר מקצת ממנו, וסובר ששחרור של חציו לא מהני.
** שור יום -
לכאו’, זה מחודש, שהיה נראה לומר שחייב ההיזק למי שהוזק. הרי העבד הוזק, במה שאין לו דמים של לאחר זמן, והרי האדון הוזק, שהרי אין לו דמים של ימיו. אז, יחלקו. אולי זה ראיה שלא משלם להיזק של לאחר זמן (אולי נחשב גרמא כיון שהוא לאחר זמן), אלא רק להיזק של אותו זמן, אלא שזה תלוי על מה שיקרה לאחר זמן.
ודע שבכל היזק, צריך ביאור ל"ל משלם כפלי כלפים, שמחמת זה אינו שווה כל כך היום, וזה כבר נותן בחשבון מה שיחסור עוד, וגם לא שווה כל כך לאחר זמן. אז, ישלם לשניהם. נראה לבאר שאף אם לא נאמר כמש"כ (שלא משלם להיזק של לאחר זמן), קל לומר שממון של ראשון גורם לו סיבה להיות לו ממון לאחר זמן, ואז נתינת ממון כאן נחשב פרעון לכל ההיזיקים. (ויש לדון, שיכול להיות הממון כלה מאז, ואף בלי הנאה ממנו. ותחשב.)
ואפשר שהיזק אינונ חילוף החיסרון, אלא יש לאדם זכות בחפצו שאם הוזק, יבוא לו דמיו. ותחשב. הרי אותו יום של אדונו הוא. ותחשב. (ועיין לקמן, שאולי יהיה לנו ביאור אחר.)
** ממון -
יש לדון מה ר"ל:
1. אולי ר"ל שלא רק מתנים ומחלקים שיעבד לרבו יום אחד ולעצמו יום אחד, אלא אותו יום הוא ממש, ביחס ממוני שעושה עבדות, עבד, וביום אחר הוא בן חורין. אבל, אותו יחס ממוני אינו עושה דיני איסור של עבדות, ודיני איסור של עבדות בא מיחס שלא נחלק.
2. אולי ר"ל שכמו שמתנים ומחלקים שיעבד לרבו יום אחד ולעצמו יום אחד, כך מחלקים היזיקיו. ויש לדון, שזה קצת כמוכר את עצמו להיזיקיו[fn:15] (שאולי לא מהני). ותחשב.
3. ויש להעיר שלצד זה, היה אפשר להם לעשות שביום רבו, היזיקו לעצמו, וביום שלו, היזיקיו לרבו, אלא שכדי לעשות שהוא יותר קל לזכור, מניחים שלא יעשו כן. ותחשב.
* מב:
** קא כליא -
מהמשך גמ’, נמצא ש"כליא קרנא" ר"ל שיש איבוד שלא חוזר. עיין בתחילת ב"ק, שחושב אני שמשתמש בלשון כזה, אבל לא משמע כן.
** קא כליא -
צריך ביאור קצת מה לנו בזה.
** אביי -
כ"ז אינו כל כך ברור לי, אבל נראה שבאים לחלק בין נזק לשבת. אביי אומר שמה שבא לו כיון שאינו שומר קישוין הוא שבת, ומה שבא לו כיון שרק שומר קישואין, ולא עושה יותר, הוא נזק. רבא לא מפרש את זה (וקצת קשה למה סותם ולא מפרש), אלא אומר ששניהם שבת, שכל שבת של כל יום נקרא שבת. אלא, לכאו’ סובר שנזק הוא דבר שלא יחזור. אם כן, מקשה מהו הנזק כאן. צריך באיור.
** מחוסר גט -
לכאו’, השאלה היא שאולי נחשב בן חורין כיון שהוא עומד להיות מזוחרר ולהיות בן חורין. אבל, מה שהוא כבר (בציורים שלעיל) קצת בן חורין, עד שאותו חירות גורם שישחרר אותו לגמרי, אינו חלק מן השאלה- והראיה לזה הוא שיכול להביא ראיה מדין חצי עבד וחצי בן חורין, ושם לא משחרר אותו מחמת מקצת חירות שיש בו, אלא כיון שאי אפשר לו להוליד בנים. (ואפשר שבכל ציור מחמת זה משחרר אותו, ולא מפני שכבר משוחרר ממונו. ויש לדון למה אין בזה כבר זה נהנה וזה לא חסר. ויש לדון בדין זנוזל"ח. גם, כמובן, צריך לדון בדין איסור של מי שכבר משוחרר ממונו.)
** כסף שלשים -
צריך ביאור למה מביא קראי. לכאו’, לא צריך קראי כדי לגמ’ לומר שדין זה הוא רק באדון או בעבד. אז, קשה למה מביא אותו. (קצת משמע, ועיין לקמן, שחלק מן השאלה תלוי באם נקרא אדון, ולא רק אם נקרא העבד עבד. ותחשב.)
** הואיל ומדרש -
עיין בתוס’ שחוש’ שמא יהיה נ’ כעבד. אם כן, לכאו’, כבר בן חורין הוא, ואז ישלם. ותו"ת. אז, רק בא להוציא תנא שאומר שבכלל צריך גט שחרר, ולא ממכריעים לפני חכמים.
** לאו קנין כספו הוא -
יש לדון למה אין זה אותו שאלה ששאל לעיל. אלוי הוא אותו שאלה, אבל נשאל שני פעמים, ובכל זמן אמר כל הצדדים, ואז הביא אותו. גם אפשר שיש חילוק. אולי יש חילוק בין אם נקרא אדון לאם נקרא עבד. לכאו’, אותו חילוק אינו יסודי, אלא הוא הביאור שיתמעט. אבל, יש שום סיבה אחרת. עדיין צריך ביאור מה הוא אותו סיבה שיהיה חילוק בדין. גם יש לומר (וזה גם יבאר הסיבה לחלק) שאולי דין עבדות, לענין נפק"מ חלוקים, הוא חלוק. ותחשב.
** משחררים -
לכאו’, חייבים לשחרר זא"ז, שאי לאו הכי, אין אחד מהם יכול לקיים מצוות פרו ורבו.
** אם יבוא -
צריך ביאור מה לנו בזה. לעיל, היה לו קרק’ (מה שהוא חצי משוחרר) שעשה שצריך להיוןת משוחרר. כאן, יש לו קרק’ (מה שלא ידוע שהוא עבד) שעושה שצירך להיות משוחרר. ותחשב. יש לבאר:
1. יש לומר שממש ר"ל שאפשר שלא יהיה משוחרר, שאפשר שיבוא אליהו. ויש לדון אם יבוא אליהו וירחיק. נראה שכיון שהחזיקו א"ע בספק, ירחיק.
2. יש לומר שמה שלא ידוע מה הוא אינו קרק’ כל כך חשוב. ותחשב.
** כהנת שנתערב -
ר"ל, כהן שנתערב…, אבל לא מצוי שיקרה כשהוא גדול. אלא, מצוי שיקרה כשמולידים אותם, שאז אין מי שיש לו טביעות עין עליו. אז, תלה אותו בכהנת.
** פירות דקל -
לא מביא הציור שבו חולקים רבי מאיר וחכמים בפירוש כיון שלא פשוט שאותו ציור הוא עבידי דאתו. נראה שאין סתם גוי עומד להיות גר, אלא צריך להיות קאי בציור שמסתבר שיהיה גר. (ויש לדון.) אם כן, צריך להביא זה כדי להוכיח כן. ותו"ת.
** ממאי -
לכאו’, כמעט מוכרח שיודה של"ל יודה. אולי בושה הוא לו.
* מג.
** הא קאי שור -
לכאו’, צריך ביאור. היה אפשר לומר שבא לומר שיש עבד, ומוכר קנין בעבד. אבל, אז קשה, שהרי לא צריכים שיש שור בעולם. אולי ר"ל שלכן סומכים דעת. אף זה צריך ביאור. נראה שהביאור הוא שכיון שיש כבר שור בעולם, יכול להיות אותו חיוב חל מיד. אז, מצייר אותו יותר בדעתו, ואז סומך דעת (ר"ל, דעתו יותר דעת). ותחשב.
על פי זה, נראה שלא צריכים שאותו שור שנגח היה בעולם, אלא ששום שור היה בעולם. ותחשב.
* Footnotes
[fn:1] אגב, יש לדון מה בדרבנן.
[fn:2] באמת, מוכיח מה שאמר גמרא, אלא שאז אין צריך ענין ראשון שכ’ גמרא.
[fn:3] ויש לדון, שעל פי ביאור הר"ן שם, זה רק אם אין חשש ממש, אלא חשש לעז. אם אלו מביאים, אלוי יש חשש ממש. ותו"ת.
[fn:4] או לכבד תנא שאמר כן, או מפני שכן היה כבר נזכר.
[fn:5] אולי הענין הוא רק שמשמעות שלהם שווה, ואפשר שהוא מפני שזה בלשון הקודש וזה בארמי. יש לדון אם "הבו" הוא לשון ארמי, שמצאנו בתנ"ך, כמו, “הבו לה’….”
[fn:6] גם, לכאורה, לא נוכל לדעת כן אלא מחמת שאין לחלק מסברה. ותו"ת.
[fn:7] שחושב אני שלא מצאנו שיעור של שהייה אחר חוץ מזה. שוב זכרתי שמצאנו עוד שיעור אחד, והוא שיעור שהייה של שחיטה.
[fn:8] שמצאנו שחוששים להם בכ"מ.
[fn:9] חושב אני שזה עצה טובה להשתמש בו כדי לשאול לרב שלום וכדומה.
[fn:10] כתבתי קצת בנוט"ס.
[fn:11] כמובן, יכולים לומר בדוחק שזה אחר התיובתא, ואחר התיובתא חזר בו רבא. שנים אלו הם דחוקים.
[fn:12] ואגב, אזכור שנראה שאולי סבר רמב"ם כמה שאמר תוס’, שרב חולק על רבי יוחנן. (ואם תאמר הרי גמרא לא נחית ששמואל יחלוק על רבי יוחנן. ויש לומר שרק מדייק כן ממה שהיה חולק עם רב, שלא אמר מה שאמר רב. אז, להיפך, אולי זה ראיה שסובר רב נגד רבי יוחנן. ותחשב.)
[fn:13] ויש לדחות שמוריש אותו אבל רק יכול לכתוב גט מחמתו אם הוא מי שהיה אדון.
[fn:14] ודע שאפשר להיות שיהי איזה מהם שמהני.
[fn:15] ונראה שמוכר את עצמו להיזקיו חלוק ממוכר את עצמו לעבודתו, שאולי יש קנין מיוחד על אדם שיעשה מלאכה זה. אז, נותן לו אותו קנין לאחר זמן. אבל, בהיזק, אולי אין קנין מיוחד לזה. ויש לדון.
