* עז.
** הרי זו -
כאילו נתנה בידה- מעניין שאומר לשון זה שמשמע שנלמד מידה. ויש לדון. ועיין בגמרא.
** קנסיה -
מעניין שנקנס, שהרי, לא גזל, ולא עבר על שום דבר. ונראה ארבע פשטים בזה:
1. אפשר שנקנס כדי להראות רעת גזילה, והוא שרואים שאף מי שעשה דבר דומה לגזירה נקנס. ודחוק.
2. אפשר שעושה רע אף שלא קנה אותו.
3. אפשר שחוששים שמא יגזול אותו ממש כיון שהביא אותו לחצירו. כן נראה שיעשה, שלמה רצה אותו בחצירו, אם לא לגוזלו.
4. אפשר שחוששים שבני אדם יראה מה עושה, וכיון שלהם נראה כגניבה, יחשבו שאין הגונב חייב.
** בכותב -
היה אפשר לתרץ לק’ מבריי’ שנתן לה בלשון מתנה. ועיין בב"ב (מג) שאולי יש כעין זה.
* עז:
** יד דאשה -
ק"ק, שלכאורה, אף לא קונה גוף שדה שלה. ותחשב.
** הרי זו
- ק"ק למה מניח שהוא קנין אגב, ולא קנין חצר. אולי סבר שכדי לקנות בקנין חצר, צריך לבוא לשם, ולא רק להיות שם, כשהוא בעל.
גם ק"ק על רש"י למה צריך להיות בתוכו אם קונה בקנין אגב. וחושב אני שאולי אם לא אומר לשון אגבו, צ"ל צרורים בו. ועדיין ק"ק למה לא רק יאמר אותו לשון. ואפשר שצ"ל בתוכו כיון שאולי גט צריך לא רק קנין אלא אף נתינה, וזה כולל שיהיה ברשותה. ותחשב.
** דחד -
יש לדון מהו הציור. אם אמר, “אתן לך מקום אחד,” ק"ק מהי"ת שאינו העצים (ובפרט כיון שעליו נתן גט). אלא  נראה שאמר שיתן את חצירו. אם כן, הוכחת גמרא (רק יתן מקום אחד) מעניין.
* עח.
** עשרה -
לכאורה, יש בזה שני ענינים (ולכאורה, יש יחס ביניהם):
1. כדי להיות רשות, צריך מקום להיות גבוה עשרה (כמו שאומרים ברה"י).
2. למעלה מעשרה כלה רשות של קרקע (כ"נ שרש"י אומר).
יש להעיר על השני שלכאורה חצר יהיה רה"י, ואינו כלה לעולם. ויש לומר שהלכות שבת חלוק מהלכות קנין, וקצת כלה. ודחוק. יותר נראה לומר שמה שעושה רה"י לא כלה למעלה, ואז רה"י עולה, אבל מה שעושה אותו קונה לזה כלה, ואז, למעלה מעשר אינו חצרו של זה. ותחשב.
** ניעור -
יש להעיר שלכאורה, עדיין משתמרת לדעתה, אלא שאף משתמרת שלא מדעתה. לכאורה, הבעיה הוא שאם אדם אחר שומרו, הוא מיוחס לו, ויחסו עושה שאינו רק שלה. גם יש לומר שצריך יחס של הוא הגורם שיישמר. כאן, אין אותו יחס, שבלי הבעל היה שמור.
** תנ"ה -
לכאורה, מביא ראיה מרבי, ומניח שלרבי צריך שום דבר. מוכיח שאין צריכים נתינה ממש. אינו נראה שאומר שמתניתין ר"ש, שאם כן, רק מביא ראיה שצריך עוד נתינה. זה, לכאורה, היה פשוט לגמרא מדין רבא (ולא משמע שבא להוכיח אותו דין).
** בת איגרושי -
יש לדון מה לנו בזה כיון שנותן לה אחר כך, ואז, אין בנתינה ראשונה כלום. אפשר שבלי סיפא, הו"א שאומר שאין צריך שום נתינה אחר כך. לא נראה כן מצריכותא שניה (ועוד שאז היה לנו לומר את זה לצריכותא). נראה שיש להקשות איך מהני נתינה אחר כך (הנחתי שמה שאומר גמרא הוא ששלף לה מתוך ידה לתוך ידה עוד), שכבר היא בידה, ואינו נתינה. ונראה שהוא מהני כיון שהוא המשך של נתינה ראשונה. אולי הוא נחשב זמן נתינה או אולי נחשב חד מזמני נתינה, ואז די אמירה אז. נמצא שזמן אמירה ראשונה היה אפשר להיות חשוב.
** כי אמר -
נראה שהו"א הוא שעדיין הוא קשור לו. מק’ שאז בי"כ ובי"כ נתינה ראשונה לא יהני. מת’ שאינו קשור לו, ונתן לה מידיה לידה עוד.
* מט:
** עידית -
יש לדון מהו הסברה החיצונה בכל אלו, שהיה לו להיות אחד שבו אינו צריך לפרש סברה (שהוא כסברה חיצונה). ויש לומר שיש גם כן סברה לכל אחד להיות כשאר (כדי שיהיו שווים).
** נאה -
לכאורה, האיסור הוא לא תחמד.
** בינונית -
לכאורה, הוא או מפני שירצה בו לאיזה סיבה, אף שאינו כל כך טוב, או שאולי הוא יותר טוב מעידית שלו. ואם נאמר כראשון, יהיה אותו בעיה אף בזיבורת, אלא שאין דבר אחר לעשות, וצריך ליתן זיבורית כיון שיש בו חשש זה במיעוט.
** וכ"ת -
וא"ת אם כן יבטלו זה את זה. ויש לומר אה"נ, וכן רצה לומר. גם יש לומר שיהיה נפק"מ כמו אם אחד גובה מיתמי (אם גובה זיבורית, או אם אין ליתמי אלא מה שנותן ליתמי). וזה תלוי בדר"נ. גם יש לומר שיש נפק"מ אם אשה מפסדת כתובתה (למשל, זנתה).
** כל לגבי -
אז, יש לומר שהוא ערב.
** ותיפוק -
לשון זה מוזר, שלא אומר סיבה אחרת לאותו הדין, אלא שלא יהיה אותו דין. ותחשב.
** תניא בהדיא -
אם כן, היה לו להביא אותו ברייתא על מה ששואל איזה ר"י הוא. יש לומר שאגב ב"ק הוא. גם יש לומר שהביאו אגב כדי לפרש אותו ברייתא.
* נ.
** תיובתא -
הו"מ לדחות שזהו הסיבה שאין חוש’ לחנא. ואולי הוה ליה לומר הסיבה, ולא סילוק הבעיה. ותח’.
** יש לדון אם
כשניתותב מר זוטרא דחיות שאמר עדיין אמת (רצה לומר, יש לדון מה יסבור רבי מאיר אם גובה ביתומים). ותחשב.
** נמאי עידית -
לכאורה, חידוש הוא שיש כאן תקנה, שאין, לכאורה, כל כך חשש לאיבוד מלוה, שכבר ייחד שדה שממנו חגבה. ויש לדון, שאולי חושש שיאבד. ויש לדון, שאולי יש להוכיח שלא חושש כל כך ממה שלא ייחד עוד שדה.
** בחוץ -
קשה, ששם דן במטלטלים, ולא בקרקע. וצריך אני לעיין בב"ק לראות חילוקי דיניהם (ואם יהיה, מחמת זה, חילוק כאן).
** מה דרכו -
לכאורה, אין צורך לומר כל אריכות זה, שהיה אפשר לומר שאיש מוציא כל מה שרוצה (מה שהוא בדרך כלל זיבורית אינו, לכאורה, הלימוד).
** ורבי ישמעאל -
יש לדון אם תירוץ של רבינא לעיל (מט:) סובר בדין לר"י כת’ ראשון (אלא שרצה שמשנה יהיה, ככל סת"מ, כר"ע). אם לא מודה, יהיה מוכרח שרבא סובר כראשון.
** יתומים שאמרו -
עיין לעיל, שמהנחת אביי (שזה אף על דבר שמדאורייתא אינו בזיבורית) מוכרח כצד ראשון. אם כן, פסק של גמרא מוכרח להיות כרבא.
** תא שמע -
יש לדון מה היה ההוה אמינא גמרא להשוות אותם (ומה יהיה הסיבה שישווה דינים לזה). ותחשב.
* נ:
** במתנה -
ואם תאמר, אולי נתן לו כיון שאוהבו, אבל לא מחמת שום דבר שעשה. ויש לומר שאומר שיש ציורים די שיש בהם פסידה שנחוש להם ונתקן.
** במתנה -
יש לדון למה זה ייחשב הפסד, שהרי אין אדם חייב ליתן לו מתנה (ואף שאין להוכיח זה, שאם לא נתן לו, נמצא שלא נתן לו מקבל מתנה די להיות חייב לו הנותן, מסתבר כן.) ואולי רק רצה לומר שהוא כועס (כן משמע לשון רש"י) ד"ה במקום).
** דשוו -
לא הבנתי, שמשנה אומר בפירוש שלא שוו. ואולי זה הוספה מגמרא, כשמוכיח מזה הדין, לא משמע כן, שרק אחר כן אומר "שמע מינא.”
** אין נפסד -
שאל לי י.ב. אם יכול ליקח את האחרון לבית דין כיון שסוף סוף יפסד. מלשון גמרא משמע שאי אפשר, שאם כן, אינו צריך לומר רק שהוא המפסיד. ותחשב.
** וקתני -
נמצא שדינים של משנה שנכללים ביחד הם לשני סיבות חלוקות.
** מעיקרא -
יש לדון אם גזרה זה (כדי שיקחו בני אדם שדות) אותו גזירה של "שלא תנעול דלת בפני לווים.” זה אומר שיש לדון אם נעשו ביחד, וגם יש לדון אם יש אותו סיבה להם, והוא מפני שיש לדון בגזרה כדי שילוו אם הוא כדי שהאיקונומי יהיה טוב (כמו כאן, לכאורה), או כדי שלא יעברו על איסור שלא ליתן הלוואה למי שצריך. ותחשב.
** שטר -
לא הבנתי ק’ זה, שאם סובר שר"ל שטר, אז אין לו להק’, שאומר שתלוי במי שקודם בשטר, ואי לא, פשוט שאין להק’, שזהו הת’. ונ’ שסבר שר"ל מי שקדם בשטר, ורק הק’ על ציור האחרון שלא אמר שם כן.
** לפי שאין -
אין קול- יש לדון אם אומר שלא יודעים שיש פרות לחוש או שלא יודעים מה נאמר על פרות, שכיון שאינם בעולם לא חושבים עליהם.
* נא.
** ויתרה -
לשון זה מוזר, שלא ויתרה, אלא הפסידה.
** ר"ח -
לכאורה, לא משיב לדברי רבי יוחנן, שאף רבי יוחנן מודה שאין מונע לתקנה, אלא רק אומר שאין סיבה לתקנה, שכבר יש לה ממון. ותחשב.
** צררי -
לכאורה, הוא שכיון שיודעת ביותר שזוכה, אולי לקחה לעצמה. ויש לדון, שלכאורה, אף בת אשתו יודעת כן, שאמר לה (או לאמה כן). ותחשב.
** גירשה -
לא הבנתי למה מניחים למה צריכות להיות מאשה זה; יכול להיות מאשה אחרת, ואין צורך לו לגרשה. ותו"ת.
* נא:
** ל"ש בו -
מניח גמרא שלא רק שלא שנא בו ולא שנא בבנו, אלא אף לא שנא שום איש אחר (כמו בציור של רב יצחק, שהוא רק מצא מציאה של אותו איש). ותו"ת.
** תפילין -
בכל אלו, יש לדון, שהרי לא נתחייב בהם. ויש לומר שלוקח להם כדי שיהיה להם כשבא לגיל שבא חייב. גם יש לומר שחייב מטעם חינוך. ותלוי מי חייב בחינוך (הבן או האב). אף אם אחר מיתת אב, אם נתחייב, עדיין צריך ביאור, שאז הוא לטובת אם. ויש לדון, שאולי כיון שיש לבן קיום ויש לו טוב של מה שנתחנך, יכול ליקח בממונו.
** ליקח שדות -
יש לדון אם הוא מפני שממעט ריס"ק או מפני שבא לו טוב, והוא כנגד ריס"ק המועט. ותחשב.
** בי שמשי -
חושב אני שזוכר אני רש"י שאומר שלא יודע למה נקרא ליל שבת כן, ויש רש"י שאומר שהוא מפני שביה"ש שלו חשוב. ונראה שמקשה למה נאמר עליו יותר מעל מוצאי שבת.
** תורי -
לא אומר שהוא ממש כשדה, שאי אפשר למכור שדה ליקח שדה, אלא הם יותר משדה, שהם עיקר השדה.
** אלא -
צריך ביאור איך מת’. ואולי רצה לומר שיש צד שטענת קטן נחשב טענה. עדיין, עיקרו חסר. ונראה יותר שאומר שנחשב טענת עצמו כיון שאין בו כל כך דין של רבה.
** יש לדון
בדין מי שסמך אצלו יתום, אם צריך לשבע או לא.
* נב:
** מנסך ממש -
שכשך- לכאורה, נמצא אף אם שופכו ומנסכו ממש. ותו"ת.
** קים ליה -
היה אפשר לומר שלא התרו אותו. וזה תלוי במחלקת תנאים אם בכגון זה חייב דברים אחרים.
** משעת הגבהה -
לכאורה, אז, חייב מטעם גניבה. אם כן, הוא חלוק משאר דיני משנה, שהם מטעם קנס (צריך ביאור, אז, למה יש לגמרא צד ללמוד ממנו לקמן). ותחשב.
* נג.
** מקנסא -
יש לדון למה אינו בכלל מדמע ממש, שאותו מילה אומר נתינת איסור בתוך היתר, וכן עושה. ואולי מילה זה אומר כן רק ביבש ביבש. ויש לדון, אז, בתרומה של שמן. ואולי פשוט שאין לחלק בין זה לתרומה של יבש. ותחשב.
** כל הני -
כן יש להקשות אף לצד שהוא ממון.
** כדי שיודיעו… -
יש לדון למה לא אומרים שרצה שילעוג לחבירו על מה שעבר איסור. ואולי לא מסתבר שמי שעושבר עבירה לאסור חפץ של חברו חושב על דברים כאלו.
** יהא כל -
קשה, שלא נדע שהוא מזיד בדרך כלל. אז, יהיה כל אדם הולך ועושה כן במזיד, ויפטור, ואז היה לנו לחייב אף שוגג.. ותחשב.
** העושה מלאכה -
מעניין שאומר זה עליו, שגמרא לקמן יבאר שהפסול אינו זה, אלא הסח דעת. גם מעניין שכולל שניהם ביחד.
** מעניין
שרש"י קורא לזה קרמא. ואולי הוא שבא ממה שלא חושב (שסתם הכנסה הוא לעבודה). ויש לדון (שזה רק אומר שבסתם חושב לעבודה). ותחשב.
דע שכיון שהגענו לזה (שכשעושה אותו במחשבה היא חלוקה), יש לומר כן גם בכהנים. ותחשב.
* נג:
** בגופן -
נראה שהחילוק הוא שאז יש רק סטף אחד, שנענע את המים, והמים כולו אחד, משא"כ במאזנים, שיש מה שמנענע את המאזנים ומה שמנענע את המים. ותחשב.
** פרה -
חושב אני שיש מקשים ששני שערות נכפפות. ויש לדון למה לא אומרים שאין זה מוכיח שפסול, שלא מוכיח שנעשה לדעת, ואז אינו שינוי חשוב. ותחשב.
** גזל מטבע -
אמר ר.מ.ש. שמזה ראיה שהמחלקת אינו אם צריך שינוי, אלא מה נחשב שינוי לגזל.
** קנסו שוגג -
יש לדון למה יעשו כן:
1. כדי שלא יוכל אדם לומר שהיה שוגג.
2. לא פלוג.
3. אף מי ששגג עבר, שלא היה לו לפשוע (שאי לאו הכי, יהיה אונס).
** ורמי -
רצה לומר, אם תדחה שבזה חולקים…, ואז צריך לומר שלא בזה חולקים.
** ע"ז -
זה סברה הפוכה, ויש לדון אם זה בעיה. וצריך לחשוב.
** הא מנסך -
זה רק לרב, ולא לשמואל (על"ע).
** מטמא מדמע -
מעניין שאינו דומה לגרמא, שהוא אסור. ואולי אף אונס אסור רק מדרבנן.
** מיבדל בדילי -
לכאורה, מקום של ר"י היה חלוק משל ר"מ.
** מיבדל בדילי -
גם היה יכול לומר שהוא מפני ששחטו עבודה זרה שלו (יבמות סט:).
* נד.
** שלושים -
ק"ק איך ידעו שהוא נטוע בשלושים. ותחשב.
** באתריה -
נראה שהוא מחמת מה שאומר גמרא בב"ב, שבמקום של רבי יהודה חולקים שדות בפחות, והוא מפני ששם היה הקרקע יותר טוב. אז, לא היו צריכים כל כך לפירות שביעית.
** ואמרי לה כדי -
נראה שכ"פ מחליפים זה עם רבא כיון שהיו כמה "רבא"ים, ואז, זה נאמר בשם רבא, ולא ידעו אי היה רבא סתם או שום רבא אחר. אמרו כדי על שום רבא אחר כיון שהיו כמה מהם. ותחשב.
** גברא לשלומי -
יש לדון אם עכשיו אומר שאינו קנס על שוגג מחמת מזיד, אלא מחמת זה, או מצרף אותם.
** תשלומיו -
מה ששינה לשונו מלשון חכמים הוא לקנטרס"ט עם מש"א גבי שוגג.
** וקמשלם ליה
- יש לדון למה מניחים שלא יידע. ואולי הוא מפני שאכל תרומה, ואז הוא מסתמא אינו ירא שמים גדול.
** אף שהיה
אפשר לת’ שהוא ר"י, היה לו לרש"י לומר שהוא קושטא דמילתא.
* נד:
** תרי -
משמע שאז אסור לבטל איסור לכתחילא מדאורייתא.
** לארעומי -
קשה למה לא אומרים את זה בדרך כלל.
** ואם ליקט
- גם יש לומר שעבר על מה שאמרו.
** אין אדם
- גם מוזר שיהיה ערלה באותו שדה, שלכאורה נוטע כולו בבת אחת.
** בידו -
צריך לומר שיודעים שיש לו דבר טמא. מעניין, שזה לא מצוי, לכאורה. ואולי בידו להוציא קרי עליהם.
** רבי -
מעניין שקרא לר"א רבו. ואולי אמר כן לרבי יוחנן (או שהיה שם, או שאמר כן ללשון בעלמא, כאילו היה שם). ותו"ת.
** ומנא -
לא הבנתי מהיכי תיתי שיש פסול פגול ביום הכפורים כלל, שאולי כיון שאי אפשר להוודע, אינו נמצא.
** חזיניה -
קשה, שאסור להביט בבית קדש הקדשים. ויש לומר שרק ראה כה"ג, ולא החדר. גם יש לומר שעיקר ראייתו הוא בכהן גדול. יש לדון אם זה מהני.
** מנא -
ק"ק למה לא אמר שיש נפק"מ דאי עבר והיה שם.
** מנומר -
לכאורה, רצה לומר שיש מקומות שבו הדיו יותר עב (מחמת שכתב שם שני פעמים). צריך ביאור למה מנומר פסול. ואולי הוא מפני שאינו נאה. קשה, שבדרך כלל, זה לא פוסל.
* נה.
** טעי בדר"י -
מעניין שלא חוששים שטעה לומר שגויל חלוק משאר ספר תורה.
** מוה דתימא -
נמצא שאין החידוש שייך למקור שהביא.
** ולאכול… דאו’ -
אם כן, הוא גזירה לגזירה.
** כהנים -
לכאורה, הענין הוא שלא יאכלו כיון שחוששים שימצא איסור.
** נמצא
- ק"ק ל"ל אמר שהפקר ב"ד הפקר.
* נה:
** מקחו -
לטעם שני, קשה למה אין אומרים כן בכל ציור. ותחשב.
** משעת -
יש לדון למה יעשו אותו ברשותו משעת גזל, שאין צורך לזה. ויש לומר שבאותו זמן כבר יש קצת מעשה קנין, ואין צריך כל כך שינוי לעשות שיחול. ותחשב.
** קמצא
- יש לדון מהיכי תיתי שהיה יהודי.
** מכדי -
לשון זה מוזר.
* נו.
** מקום -
ק"ק ל"ל עשו רבנן בו מום אחר. ואולי מפני שאסור לתת מום בבעל מום. גם יש לומר שהיה בר קמצא שם. ויש לדון, שמי יאמר שהאמינו אנשי רומי לו. גם יש לומר ששלח בני רומי עמו.
** ארבע רוחות -
יש לדון מה זה אומר:
1. שלח לשאר רוחות.
2. שלח לארבע עוד רוחות (וכולל למעלה ולמטה).
** רעב -
יש לציין לגמרא בשבת שאומר שלא אוכלים כלבים כל כך. יל"ד, שאותו גמרא גם אומר שכלבים לא צריכים לאכול כל כך. ואולי רצה לומר שהוא רעב כאילו הוא אדם שרק אכל ככלב. ודחוק.
** אקלידי -
צריך ביאור איך יהיה יותר חשוב, שהרי יכול לאכיל חטים בלי עצים, אבל אי אפשר לאכול רק עצים. ותחשב.
** וכי הוה בריא -
יש לדון מה זה אומר. לכאורה, היה צריך לאכול כלום בתוך ארבעים שנה שהתענה. אם כן, קשה למה לא אכל כן אז. אולי לא היה חלוש עד שהיה צריך לזה  סוף שנות התענית. גם אפשר שאז היה צריך לאכול יותר, שהיה אוכל רק בלילה. גם יש לומר שלא ידע לעשות כן אז, וזה היה חלק ממה שעשו לו רופאים (ולא הזכיר אותו לקמן, שסומך על מה שכבר הזכיר אותו כאן).
** הוה מיתחזי -
עיין במה שפרש רש"י. צריך ביאור איך נראה שם, שהקנה קשה. בפרט קשה כיון שרק אכל משקה מן הגרגרת. אז, לא היה בולט כלל.
אפשר שהוא רק אקספראשיי"ן.
** דחיא קליל -
צריך לומר שידעו כמה גדול היה (רצה לומר, שאילו לא ידע כמה היה קל בחייו, אין כבידתו בעיה). גם תלוי כמה קרוב כבידת מת לכבידת חי. ותו"ת.
** רבן -
יש לדון אם אמרו שהבריונים עשו כן או שר"י ור"ג עשו כן.
** רבן -
יש לדון אם החשש הוא שיאמרו שנוולו לאחר מיתה או שיאמרו שהמיתו אותו. לכאורה, אי אפשר לומר כצד ראשון, שהרי רומיים ראו בכל שיצא, והיו דוקרים כל שיצא, ואז ידעו שהיה רק לבדוק. ויש לדון, שרומיים לא ידעו על בריוני, ואולי סברו שכל שמת היה נדקר. גם יש לומר שרק רצו לדקור ר"י כיון שהיה כל כך רע אם היה יוצא. גם יש לומר שרק חשו על ר"י שהיה משקר במיתתו כיון שהיה קרוב לבריוני, או כיון שהיה חכם כל כך. ותחשב.
** דלאו מלכא -
וא"ת ממ"נ רק עבר על אחד. ויש לומר שהבעיה השנית הוא שמגלה שלא מכבד מלכות רומי. אז, תלוי רק במה שחשב שהוא מלך, ולא בהיותו מלך.
** דלאו מלכא
- עיין במש"כ. לולי זה, היה נראה לומר שהוא מפני שאז אמר שמלך רומי אינו המלך.
** תרי קטלא -
קשה, שכיון שהיה יהודי, היה חייב עוד קטלא (עיין לעיל). ואולי רצה לומר שמחמת מעשיו חייב שני קטלי. ותחשב.
** גרוגרת
- מושג זה של הרחת חולי מוזר.
** אבא סיקרא
- נראה שכתב כן כדי לומר שלא תפרש ששמו היה סיקרא, והיה נקרא "אבא" מפני חשיבותו (כמו שמצאנו בכ"מ), שרק קוראים כן למי שהוא ת"ח, והוא היה בריוני.
** ואגני גבך -
יש לדון מה עשו אחר שהוציאו. לכאורה, נתנו אותו דבר שמסריח בתוך ארונו. ותחשב. ונראה שאולי מפני זה רצו לדחוף אותו כשיצא, לראות אם טמן נבלה עמו. עיין ברש"י שלא כ’ כן, אבל על רש"י ק"ק איך לא ישמור את עצמו מלצעוק.
* נו:
** מלכא את -
מעניין שהיה יכול לקראות אותו כן, כיון שלא היה מלך עדיין.
גם מעניין שמניח שיהיה ירושלים נחרב, שאף בידי סנחריב היה נראה שייחרב, אבל לא נחרב.
גם מעניין, שהרי טיטוס לא היה מלך. ואולי מלך אחר כן. גם יש לומר שמי שמתחיל בזה נקרא על שמו, ושר זה, ולא טיטוס התחיל. ודחוק. ואין לומר שכיון ששלחו מלך היה כאילו מלך לחם, שאף שר זה שלחו מלך.
** בריוני -
עדיין קשה למה לא עשה רמאות זה עד כאן.
** רב יוסף ואיתימא ר"ע -
יש לדון איך יכולים לבלבל זה לזה, שאחד תנא בא"י, ואחד אמורא מבבל, ואין שמם דומה. אולי ר"י אמרו, ולא יודעים אם אמר אותו משמיה דנפשיה או משום רבי עקיבא. לא נראה, שאז היה לו לומר "ואיתימא ר"י בשם ר"ע.”
** סיים חד מסאני -
מוזר שהיה עושה כן בתוך דיבור זה. ואולי צריך קצת זמן עד שגודלים, ולא היה מדבר עוד לשליח ור"י.
** למשלפא -
יש לדון למה רצה לחלצו:
1. יותר טוב להיות בלי מנעלים מלהיות במנעל אחד.
2. אז, היה יכול ללבוש אחרים יותר גדולים.
** אמרי לך -
צריך ביאור למה חזרו על כל דיבורם.
** דר"ג -
מענייין שנקרא ע"ש ר"ג.
** מה עשה -
הפסיק המעשה שהיה אומר, ומתחיל לדרוש הקרא לומר שחירף, ומבאר מה עשה לחרף.
** עבירה -
לכאורה, ביאה עם זונה אינו עבירה לגוי. ויש לדון. ואולי היה הזונה אסורה לסיבה אחרת (אולי היתה נדה או כדומה).
** דם מבצבץ -
יש לדון למה לא אומרים שזה היה הדם שראה ראב"י על הפרוכת (במסכת יומא).
** באלמים -
קצ"ב, שהרי העניש לו. ויש לומר שאילו לא היה עושה שבלתי זה היה נראה שאין לה’ כוח, לא היה מעניש אותו. ויש לדון, שהיה מעניש אותו, מסתמא בעולם הבא. ויש לומר שהיה אלם כיון ששהה.
** בריה קלה -
- קשה, שזה חי זמן רב, ויש לו פה. ותחשב.
** כצפור -
צריך ביאור איפה היה במוחו. אולי היה לו בומ"ף בראשו. גם צריך ביאור מה אכל, שאם אכל כל כך ממוחו, לא היה חי כל כך זמן ארוך. ואולי אכל מעט ממוחו, עד שהיה יכול מוחו לגדל שוב קודם שיאכל שוב.
** בההוא -
מעניין שידע, שהיה בגהנום. ואולי אף בגהנום, בני ישראל יותר חשובים מגויים. גם יש לומר שאמר שלא ראה בני ישראל בגהנום. גם יש לומר שחלק מצער גהנום הוא גופא שיושבים ורואים בטובת גן עדן.
** שבעה -
אפשר שמה שעשה כן הוא שכיון שה’ הראה לו שהוא שופט על הארץ, חשב שאולי פסק מלשפוט על הים, ואז רצה שיהיה בים, כדי שלא יענש אותו.
* נז.
** בבבת עינו -
צריך ביאור מהו משל זה.
** אתו -
יש לדון אם ממש חשבו שמרדו או רק רצו לנקום בהם.
** שפטפט -
אומר לשון זה אגב שדורש אותו גבי יוסף בבבא בתרא.
** והלקוהו -
צריך ביאור מהו הטוב בזה, שכך חייבים לעשות, ולכאורה, לא צריך כל כך גבורה לעשות כן. יש לומר:
1. עדיין הוא גבורה די.
2. אולי כיון שאומר גמרא (כן אני חושב) שאחד מן הסיבות לכל חורבן הזה היו דיינים שלא היו טובים, אומר שאל רק היו צדיקים, ואז היה לה‛ להציל אותם, אלא אין בהם סיבת הכליה. ותחשב.
** דלא איאבול -
לכאורה, היה אפשר לומר שהוא מפני שחזרו למצרים, כמו באלקסנדריא של מצרים. אולי זה סמך לשיטות שזה רק באופנים מיוחדים (עיין באותו סוגיה), ואולי זה אינו באותו אופן.
** אחד מושך -
צריך ביאור למה כל זה שייך.
** שיערו -
לכאורה, ידעו מחמת דנסיט“י שלו ומחמת מראיתו.
* נז:
** שדרכן -
קלון- לשון זה מעניין, שלכאורה, הקלון הוא הבושה (כן הוא משמעותו בגמרא סנהדרין גבי בא על בהמה). לכאורה, לא היו ממיתים את עצמם מחמת אותו בושה. אולי רצה לומר שיש גם כן קצת שלא לשמה להם, והוא שיש להם בושה.
** בר משחיטה -
יש לדון מה רצה לומר:
1. אולי יבוא לו כעין מה שהראה (על פי מה שאומר גמרא בכריתות והריות שמסמני מילתא, ולכן אוכלים דברים מיוחדים בראש השנה וכדומה).[fn:1]
2. מרש"י קצת יותר משמע שחוששים שמא כשעושה כן יזיק את עצמו. ק"ק:
  1. למה יש לו סכין עמו, שהרי הוא לומד. אולי מיירי בשמלמד דיני שחיטה לשוחט לפני שחיטה, ולא כשלומד מסכת חולין. יש לדון, שמסתמא מי שבא לשחוט כבר יודע. ויל"ד.
  2. למה יראה בסכין, שלא מוסיף שום טוב בזה.
  3. ל"ל יאמר צד ראשון, שהוא בוודאי נכון גבי נזיקין. ואולי צרעת שהוא רע רוחני יותר ראוי לבוא לסיבה כזה. ודחוק.
** בר משחיטה -
ק"ק למה אין זה גם ברעות אחרים, כמו אם מראה אדם בעצמו בעל מום.
** זקן אחד -
עיין בתוס‛ חולין שאומר ש“ההוא סבא“ הוא לעולם אליהו הנביא. יש לדון אם זה אמת גם בזה, שהוא פירושו של ”ההוא סבא“ בעברית. יש לדון, שאולי חלוק כיון שאין מילת ”ההוא,“ שמשמע שהוא המיוחד. ויש לדון, שכאן יש מילה מיותרת של ”אחד.“ ותחשב.
** אשכחיה לדמיה -
קצת צריך ביאור למה היה כל כך דואג על דם זה.
** דמים -
עיין באותו קרא, שלכאורה, אינו בתוך הקנטקס“ט.
ויש להעיר שלכאורה, לא כיוון לקיים אותו מקרא (כדי לפייס את הדם), שאז היה לו לשחוט את בני אדם קרוב לו, ולא כדי שצריך לשחוט כל כך כמה עד שיבוא דם לשם.
** יש לדון
למה חשב שהמתת כל אלו ישקט את הדם:
1. אולי היה כעין קרבן (שכך עשו גויים).
2. אולי היה עונש, שבני ישראל הרגו לו, ועכשיו הוא הורג לבני ישראל. על זה, יש להעיר:
  1. מעניין שנקט צדיקים, שהיו הכי נקיים.
  2. מעניין ששב, שחשב שמה שעשה היה נכון, שהיה הורג בני אדם שהיו אשמים.
3. אולי הוא מפני שמיתת צדיקים מכרת.
** דם זבחים -
יש לדון למה מרתח. אולי הוא מפני שמת רק לפני כמה רגע. חושב אני שאולי דם כשיוצא מבהמה מרתיח קצת. ודחוק. גם יש לומר שהודו שמרתיח כיון שעשו בו עבירה, אבל אמרו שלא היה עבירה גדולה.
** לא אדמו -
ק"ק, שאולי מה שהיה שם ומרתח לזמן עשה שנשתנה מראיתו. כמו כן, יש לומר שמה שעשה אותו מרתיח שינה מראתו.
** דם זבחים -
יש לדון למה שקרו:
1. חשש שיהרוג אותם על דמי זכריה. יש לדון למה חשש כן. גם יש לדון למה היה מותר להם לגלות, אז, שהיה דמי זכריה. ויש לדון, שאולי אז היה ”אין ספק מוציא מידי ודאי.“
2. היו מתביישים.
** תנוקות -
מעניין שקורא לתנוקות ”טובים,“ שלכאורה, רק אין להם כל כך יצר הרע. אז, לא בוחרים כלל בטוב. (מה שאומר שהעולם קיים רק להבל פיהם הוא לכאורה, שיש להם יכולת להיות טוב, שלא נפגמו עדיין בעבירות.) ויש לדון, שאולי אין הכי נמי, טעה, שהיה רומי, ומה ידע.
** איגייר -
לכאורה, היה לו לגייר קודם כל זה (זה אומר, לכאורה, מוזר שרק אחר שעושה כן מרגיש שהוא רע, והוא נראה כאומר אחטא ואשוב). ותו"ת.
** ילדים -
צריך ביאור למה היו יכולים להרוג את עצמם. לכאורה, יש שני דינים שהם שייכים כאן:
1. מותר להרוג מי שהולך לעשות עבירה.
2. צריך אדם להיות נהרג כדי שלא לעבור על עבירה.
לכאורה, על עברות כאלו, אין דין ראשון שייך.
יש לדון בדין שני, שלכאורה, ימתינו עד שבאים לרומי, ושם ימחו, ושם יהרגו. אולי חששו שלא יוכלו לעמוד בנסיון. יש לדון אם עדיין מותר להרוג את עצמו (שהניחא לסיבה ראשונה, אולי מותר, שהורג את מי שיבחר ברע, אבל מי יאמר שלשני מותר. ותחשב.).
גם יש לדון בכל זה, שלכאורה, הגויים רצו כן, לא כדי לעשות שבני ישראל יעברו, אלא להנאתם. ועיין בסנהדרין.
** אם אנו טבועים -
יש לדון למה לא:
1. הם רחוקים וקשים להביא לעולם הבא. יש לדון איזה הוה אמינא יש בזה, שאם ה‛ יכול לתת את מתים לעולם הבא, מסתמא גם יכול להצילם מן התהום.
2. המיתו את עצמם, ובזה עברו עבירה.
לכאורה, הקרא מלמד הראשון, שיש לדון מהו ציור של שיני אריה. אם המית את עצמו, קשה למה צריך שני קראי. אם לא המית את עצמו, וקשה לגאול אותו מפני שהוא נחתך ונטחן כולו, אז הוא אומר כצד ראשון. וצריך ביאור.
מעניין שלא היה להם אף לספר לענין 2, אבל היה להם ספק ל1. צריך ביאור.
** שבעה בנים -
מעשה זה רגיל להיאמר גבי חנה ושבעה בניה במלכות יוון. אולי קרה שני פעמים (ואולי עשה כך להראות שהוא יותר חזק מן היוונים, אבל לא עלה בידו).
** שבעה -
כל מעשה זה קצת מוזר, שאם רצה שבני ישראל יעבדו את ע“ז, קשה למה הלך בסדר משפחת; היה לו רק לנקוט כל אחד מכל מקום, ולעשות כן לו. ותחשב. ואולי אין הכי נמי, ולא היה זה אחר זה.
** אנכי ה‛ -
ק"ק ל"ל הביא קרא של ”אין לך…,“ שהוא מאד יותר שייך לענין. ואולי כן היה כוונתו, והרגו אותו קודם שהגיע לאותו חלק מן המקרא.
** זובח לאלהים -
לא היה זובח, אלא משתחווה.
** שמע ישראל -
שמעתי שחולקים רמב"ם וראשונים אם פירוש של אחד שכולל כל מדותיו לאחד או שיש רק ה‛ אחד. זה משמע נגד רמב"ם; ויש לדון, שאולי הוא כעין ”אנכי ה‛,“ שאינו כל כך נוגע.[fn:2]
** יש לדון למה
לא השתחוו כיון שיהיה עבודת עבודה זרה לאהבה וליראה. גם קשה למה לעולם חייב אדם לתת את עצמו למיתה, שבהכרח אם אדם כופה אותו לעבוד עבודה זרה הוא לאהבה וליראה. וצ“ב.
ואין לומר שלא רצה שיהיה נראה כעובד עב“ז, שאם כן מה הועיל בלקיחת הטבעת. ויש לדון, שאולי לא ידע הקיסר את הדין.
** עקדתי -
יש לדון, שלא היתה לה בחירה בדבר, שהם הרגו אותם בלי רשותה. ואף שגרמה כן, שלימדה, אולי, שה‛ אחד, לכאורה, לא ידעה אז מה יקרה להם. ויש לדון, שאולי אמרה להם מה לומר כשבאו לשם.
** אף היא -
צריך ביאור למה זה היה מותר.
** בשמיני -
אינו, לכאורה, כל כך, שאילו לא היו מלים אותם, היו מתים בחיוב כרת. עדיין, יחיו ליותר זמן. גם יש לומר שהוא מה שקבלו מצוות מילה (שאילו לא קבלו, לא היה ציווי וחיוב כרת).
* נח.
** דרעא -
צריך ביאור איך יהיה של ראש שלש פעמים, שיש בו שלש פעמים של עור שיורד עד למטה ועולה. כל אחד הוא כנגד רק שני דפנות של בית, ואז אינו גדול שלש פעמים. ותחשב.
** חדא -
נראה שמוכיח מלשון אגדה זה שלא בא להם כל זהבם מבני ישראל, שמשמע שהורד להם.
** ארבע -
קשה שבב“ב אומר שמלמד תינוק לא ילמד ליותר מחמישים.
** והציתו -
תקנו ברכה על קבורת הרוגי ביתר. יש לדון אם אף אלו נקברו. אם כן, לכאורה, היה עוד נס.
** אי מטרי -
עיין בתענית ט. כעין זה.
** בנו ובתו -
מעניין שהיה נשבה כשהיה תינוק, וגם בנו ובתו היו נשבים. צריך לומר שקרו שבויות אלו לזמן. ותו"ת.
* נח:
** מאי אחריות -
שאל לי י.ב.ח.- ופשוט הוא שצריך ביאור- מתי מקשים על רב מברייתא ומתי אומרים שרב תנא הוא ופליג. להוסיף על הקושיה, יש להעיר שלא רק מתרץ גמרא לפעמים שרב תנא, אלא אומר, ”מתניתא קא רמית על רב; רב תנא הוא ופליג,“ שמשמע שאינו מובן כלל להקשות על רב.
אפשר שרב היה בין תנא ואמורא (קטן מזה וגדול מזה), ולכן היה רבי יוחנן וכדומה יכול לחלוק. אם כן, אולי לא רוצים שיחלק על ברייתא. יש לדון, שלא משמע כן לשון גמרא שהזכרנו לעיל.
גם שמעתי שרבי יוחנן ורב חלקו אם רב הוא תנא. אולי, אז, יש סוגיות חולקות בזה. ותחשב.
** שטר
- לולי רש"י, היה נראה לפרש ששטר הוא אחריות כיון שבדרך כלל שטא עושה אחריות, שאחריות טעות סופר.
** והאמרת -
היה אפשר לחלק לומר שיש חילוק דינו לפני שנים עשר חומש. גם היה אפשר לומר שאומר שאחר שנים עשר חדש אחר התחלת דין סקריקון (שהוא אחר שני שנים) יש לו דין סיקריקון.
** אין אנפרות
- לכאורה, כוונת רש"י הוא לפרש שיש נפק"מ, שלא היה אומר אותו אילו לא היה נפק"מ. ויש לדון, שמצאנו במק"א שאינם כן, כמו אין תענית צבור בבל, לרש"י, ועוד דין בעירובין (כן אני חושב). ותחשב על זה.
** טוענים
- שדי זוזי בכדי- יש לדון בזה, שזה אומר שידע שמכר אותו, אבל ”טוענים“ אומר שלא היה יכול לטעון, שלא היה יכול לדעת. ואולי אמר שאף שלא היה יכול לדעת, היה רואה שום דברים ניכרים קצת.
** עיין במה שבאר
רש"י בחילוק בין סיקריקון לאנפרות. צריך ביאור בחילוק זה, שבשניהם ירא ממנו. ותחשב על זה. אולי החילוק הוא אם חושב שיוכל לעשות דין לאחר זמן. עיין בלשון רש"י בזה.
* נט.
** כולהו שני -
זה מעניין. לולי זה, היה נראה לומר שלא היה אדם בכל שנותיו שהיה גדול מגדולתו.
** פנחס -
לכאורה, יש להקשות שהיה אלעזר.
** עירא
- ק"ק מגמ‛ בסוף סוטה שמשמע שהיו הקדמונים לומדים מעומד. ותחשב. ואולי מלך[fn:3] (ומלמדיו) חלוקים. ותחשב.
** והטהרות והטמאים -
לכאורה, שנים אלו שווים. ותחשב.
** ולא חולקים -
לכאורה, ההוכחה שאינו מחלקת, ושכל אחד אומר שיעור שאינו דווקא, הוא שכל אחד אומר שיעור שכולל שני גילים. יש להעיר שזה אינו אומר שהוא מחלקת, אלא רק אומר שלא אומרים שיעור שהוא כל כך דווקא, שיכול להיות דרגה של חכמה שבנים חכמים מגיעים לו כשהם בני שש, ובנים טיפשים מגיעים לו כשהם בני שבע.
** ולא חולקים -
אם כן, קשה ל"ל אומר כל אחד ”כבר שש כבר עשר.“ אולי חד נקט הפחות, חד נקט הגדול, וחד נקט הרגיל. יש לדון עדיין למה נקטו שנים. אולי שש הא הפחות, אבל לא מצוי כלל, ואז הוסיף שבע… וכמו זה. ותחשב.
** כאמגוזא -
יש לדון מה היה כאמגוזא:
1. גובהו.
2. רוחבו.
רוחבו עושה שהוא דק מאד, שבדרך כלל, אין דבר יכול להיות נכפל עד שהוא כל כך קטן. לכאורה, אין גבהו כל כך גדול, אלא נראה שהוא אומר שהוא גובהו אף אם כופל אותו פעמים הרבה עד שממש אינו יכול לכופלו כלל. ותו"ת.
** כאמגוזא -
יש לדון אם כל אחד הוא כאמגוזא, או ששניהם ביחד הם כאמגוזא.
** מלמלא -
זה רק אומר מה שהוא נמלל, ולא מה שהוא נמתח.
** חד כרעיה -
מוצאים כעין זה גם כן בקידושין (פרק רביעי). יש לדון אם אמרו כך כדי להודיע שזכרו אותו בטוב, שאף זכרו כל דבר שקרה אז, או שעשו את זה כדי להזכיר לבני אדם, שאולי על ידי הזכרת נקודה זה, יזכרו כל המעשה והמימרה. ותחשב.
** קפיצה -
רש"י יודע שהוא סימן יותר חלוש ממה שגמרא מבואר כן (שאומר שהוא כן רק במטלטלים, אבל בגט, צריך יותר). ויש לדון, שיש לומר להיפך (שאומר שבגט אינו צריך כל כך). היה אפשר לומר מסברה שקפוץ מגלה יותר, שהוא יותר פרייסייס. ותחשב.
* נט:
** בור הקרוב לאמה -
יש לדון למה נוקטים את סדר זה. אולי אין יותר טוב מזה (הוא ארביטריירי).[fn:4] יותר נראה שהוא מפני שעפרו לאחרים (כמו שאומר בן סירא שמובא בסנהדרין (פרק חלק) ובבא בתרא.[fn:5]
** מצודות חיה -
יש לדון למה אין בהם כבר משום עני מהפך בחררה. צריך לעיין שם בקידושין (תחילת פרק שלישי) אם אותו איסור נוגע כאן. גם יש לומר שהיא היא- זהו אותו איסור של כאן.
** מנה"מ -
לקמן, יקשה גמרא שמשנה אומר שהוא רק מפני דרכי שלום. אז, צריך לומר שכאן המשיב שואל.
** להקדישו -
לכאורה, לומדים ממה שאהרן נקרא קדש. קשה, שאם מה שהוא קדש די ללמד לנו דין זה, נלמוד כן ממה שעובד בבית המקדש. אולי זה לא מודיע לנו קדושה, אלא אולי דבר אחר. גם יש לומר שזה יותר בפירוש. גם יש לומר שזה לא רק מלמד שהוא קודש, אלא מלמד שצריך ”להקדישו.“ ותחשב.
** מנא הני מילי -
לכאורה, יש מאלו שהם מקור רק לדין כהן. ותו"ת.[fn:6]
** ונגשו -
נראה שיש מעלה בקרא זה ממה שהוא קדם, ויש מעלה בקרא של ראשון במה שהוא לענין תורה.
** דבר שבקדשה -
צריך ביאור איך ”מנה יפה ראשון“ נחשב דבר שבקדושה. אולי ר"ל שמקדימים אותו אף לדבר שבקדושה, שהוה אמינא שאין ישראל צריך להפסיד קדושה. ותחשב.
** משום דרכי שלום -
אם כן, צריך לומר שהוא רבי שמעון, שדורש טעם של מקרא. ויש לומר שכאן אומר קרא בפירוש, שאומר, ”דרכיה….“ יש לדון, שמשמע שר"י לא סובר כן, שאביי מקשה מזה.
** כל התורה -
קשה שגמרא בברכות שאומר ש“אינם אלא גזירות.“ יש לומר שצריכים לקיים אותם מחמת שהם גזירות, אבל לא כן צווה ה‛ אותם. עיין שם, שחושב אני שלא משמע כן כל כך.
** ואם בא -
יש לדון למה נחלק. לכאורה, צריך לומר שיש יותר רצון לעלות ראשון מלאכול ראשון. אז, אי אפשר לומר שמה שאדם רוצה לעלות ראשון הוא שמורה שת"ח הוא. גם יש לומר שאין אדם צריך לתת כיבוד זה לתלמיד חכם, אבל מסתמא עושה כן- אבל רק בדבר שיש בו קדושה. אז, רק מורה שהוא תלמיד חכם יותר בקריאת התורה. ותחשב.
** דשכיחי רבים -
יש לדון אם יש יותר בני אדם בתפלה או בקריאה (שהוא יותר חשוב באותו זמן).
** לוי -
ואם תאמר אולי אין לוי. ויש לומר שאז היה לכהן לעלות. ויש לדון מה ידוע לבני אדם החוששים (שאם יודעים שכהן יעלה, קשה למה חוששים).
** לוי -
לכאורה, לספרדים, שעולים כהן לכל עליות חוץ משני ושלישי, יהיו מקומות שעדיין יש בעיה, כמו אם עולה כהן לשלישי ולרביעי.
** מוחזק -
מוזר להוקים אותו בזה בלי לומר כן. היה אפשר לומר שרוב כהנים כן. אם כן, אף יש לומר כן בראשון (ורק שעדיין חוששים, שיש לומר שעלה בטעות, והביאו השני לתקן לו).
** ליוצאים -
יש להעיר שאסור לצאת בתוך קריאת התורה.
* ס.
** ראש כנסיות -
לכאורה, ר"ל ראש כנסיות ושוב כל אדם, שאי לאו הכי, היה לו לומר רק ראש כנסיות. יש לדון, אז, ל"ל אומר כמו שאר- אחר כן ראשי כנסיות, ואחר כן כל אדם.
** בני גליל -
לכאורה, הם בני גלילא. ויש לדון.
** מחסר -
יש לדון מהו הענין:
1. אינו שלם. יש לדון אם זה בעיה.
2. עומד לשנות, שיוסיפו יריעה. אם כן, גמרא לא אומר החילוק עצמו, אלא סיבת החילוק.
** כבוד צבור -
קצת צריך ביאור איזה כבוד יש בזה. ונראה שאין הענין שמעצמו יש בזה כבוד, אלא שרבנן קבעו כן כדי שיהיה יכולת לכבד צבור, וכיון שרבנן אומרים שהעושה כן מכבר צבור, הרי ממילא שהעושה כן יש בו כבוד צבור, שרוצה בזה כדי לכבד צבור, כמו שאומרים רבנן.
** לא חזי למיקרי -
יש לדון למה לא חזי לכסות פך או כדומה. ויש לומר שקודש הוא ואי אפשר לשמש בו כך. יש לדון אם יש בו קדושה כיון שאסור ללמוד ממנו. גם יש לומר שכיון שהוא חשוב לא ישתמשו בו בני אדם לזה. ויש לדון, שאין בו תשמיש אחר.
** הכא נמי אי אפשר -
ואם תאמר יכתוב מגילה מאת כל נביא בפני עצמו. ויש לומר שאף זה אסור. ויש לדון ל"ל אומרים שנעבור רק על איסור אחד ונעשה כן. ויש לומר שהוא איסור שווה. ויש לדון. גם יש לומר שאף זה אי אפשר, שקטנים הם ויאבדו.
** במגילת ספר -
לכאורה, מזה רואים שדרשות של אגדתא יכולים להיות דרשות ממש, שכאן צריכים לומר שהדרשה הוא שכתוב בתורה. אז, צריך לומר שכתוב. ויש לדחות עדיין שאסמכתא נחשב כתוב (תלוי במחלקת רמב"ם וריטב"א). גם יש לומר שכל דרשה זה אמרו אותו חז"ל, ולא ממש אמר דווד שהיה נתנבא עליו בתורה, אלא אמר דבר אחר דומה, ורבנן שינו מה שאמר למצוא אסמכתא. דחוק מאד.
** עיין בבשלח
שאומר, “כתוב זאת זכרון….” צריך לבאר לשני הצדדים. לצד שלא נכתב מגילה, לכאורה, שזה היה לכתוב מגילה אז. (אם כן, היה אפשר למנותו עם השמונה פרשיות.) לצד שנכתב מגילה, נראה שאמר לו לכתוב אז, שזה היה גמר מגילה אחת.
** שמנה -
צריך ביאור למה נכתבו אלו יותר משאר כל המצוות, שלכאורה, יש כמה מצוות שהיו נוגעים לכל אדם.
** פרשת כהנים -
מעניין שמניח שלא היה איסור טומאה קודם לכן. נראה שסובר שימי מילואים לא רק נתן דיני עבודה לכהן, אלא נתן להם כל קדושתם (או סבר שכל דינים אלו שמנה הם מחמת דין קדושה). ויש לדון ל"ל היו מצוות אלו במשה קודם לכן. ואולי "נאמר באותו יום" רק נאמר ממשה, אבל משה כבר ידע אותם.
** חתומה
- על פה- לא היה בעיה בזה, שלא היה מוציא רבים. וצריך לומר שכתוב "שמע ישראל" או כדומה או שכל אחד אמר בפני עצמם, ולא היו מוציאים זא"ז.
* ס:
** ופרשת פרה -
צריך ביאור למה שהו יום. אולי לא היה פנאי.
** רוב -
ואם תאמר ימנו. ויש לומר שלא קל לבאר איך מונים. (למשל, אם ההלכה הוא שאין קורעים אלא אם כן הוא ירוק וכבד וטהור, יש לדון אם זה הלכה אחת או כמה הלכות, שאין קורעים אם אינו ירוק, ואין קורעים….). ותו"ת. גם יש לומר שחולקים מה נחשב על פה.
** אתמוהי -
עיין במה שפירש. עיין בירושלמי פאה (ועיין בפני משה שם), שנראה שלא מפרש כך. ע"ש.
** חשדא -
לכאורה, נקרא דרכי שלום מפני שאם בני אדם חושדים זה את זה, לא יהיה שלום. יש לדון ל"ל חוששים למראית עין גם כן (ואין צריכים חשש של דרכי שלום). ואולי אין הכי נמי, יש שני סיבות.
* סא.
** מציאת חרש -
צריך ביאור למה מבאר שיטת רבי יוסי (ומחלקתו עם הת"ק) רק בזה, שחולקים אף בציור אחר קודם לכן.
** להוציאו
- לפסול- יש להעיר שאף גזל דרבנן פוסל לעדות. לכאורה, ר"ל שמדאו’ כשר לעדות. קשה, אז, לל"א שמדאו’ כשר. ותו"ת. וצל"ע בסנהדרין שם (קרוב לדף כו).
** משאלת -
איני יודע כל כך מהו האיסור כאן. אולי עובדים בפירות של שביעית לאחר זמן ביעור. גם אפשר שגורמת מה שתאכל לאחר זמן בעור. יש לדון אם גורמת שתאכל, או רק משנה אותו להיות הדבר שאוכלת. ותחשב.
** רוב עמי -
דרבנן- משמע שאילו היה ספק, היה אסור מן התורה. משמע שספק דאורייתא לחומרא מדאורייתא.
* סא:
** מפני שחשודה -
לכאורה, עם הארץ לא יודע מה שאומר גמרא ב"מ (פרק המפקיד) ש"אדם רוצה בקב שלו יותר מתשעה קבים של חברו.” אולי רק סובר כמי שחולק שם.
** לא שכיח -
קצת צריך ביאור למה לא נותנים שני הנקודות ביחד, ודנים מי נוטל יותר ממון.
** משום כדי חייו -
ואם תאמר למה יש חשש כלל. ויש לומר שיש חשש שהוא זב. גם יש לומר שיש חשש שיגע בו, ולא יזכור או לא יחוש למה שאומר.
** בכלי
- משא- ר"ל בהיסט.
** כופלים -
כך היה דרכם למכובדים, כמו שיפרש לקמן.
** מיבעיא -
ק"ק לל"א כמו שכ’ רש"י על המשנה, שנותן שם שמים על גוי. גם ק"ק למה מפרש רש"י במשנה כן. אולי כיון שגמ’ גילה איך יכול לעשות שלא קאי על גוי ממש, אז צריך לומר שאין זה החידוש. יש לדון למה רש"י פירש כן. אולי זה נחשב הוה אמינא של גמרא.
** שפה רפה -
לכאורה, זה נותן פחות הנאה לעכו"ם.
* פב:
** שרבי אליעזר מתיר -
ק"ק למה שואל מאי טעמא על זה קודם. ויש לדון, שואלי הוא מחמת שהוא מאוחר, כמו שאומר גמרא בתחילת נזיר ונדרים.
** איסור כהונה
- לכאורה, אין צריך לומר כן. לכאורה, קושיית גמרא היה שאם חל, חל לשניהם, ואם לא חל, לא חל לשניהם. זה אומר שיש רק אפשרות אחת של חלות גט. לכאורה, גמ’ מתרץ שיש שני אפשריות של חלות גט. לכאורה, אין סיבה להניח שמה שיש בו איסור כהונה הוא מה שמתרת אשה לשוק, שהם דינים חלוקים. ותחשב.
** נראה שיש
נפק"מ בין שני הטעמים באם מגרש ואוסר על הכל, שלצד ראשון, לא חל, ולצד שני, חל.
** קידושי ראשון -
לכאורה, עיקר דינו הוא שצריך קידושין לחדש איסור. יש לדון ל"ל אומר דין יותר פשוט: אם אדם מקדש חוץ מכל אדם, לא חל. נראה שיש שני צדדים:
1. הנחתי בקושייתי שכשאדם אוסר אחד ומתיר אחר, מה שקורה הוא שיש קידושין, ואותו קידושין עושה איסור לנגד אחד ולא לנגד השני. עיין לקמן, שיש, אולי, סיבה לחשוב שמה שעושה הוא קידושין לגבי זה, ולא לגבי האחר. אם כן, פשוט שאם מתיר לכל העולם, נמצא שלא עשה קידושין לענין שום אדם.
יש לדון בזה:
  1. הרי עשה קידושין לנגד עצמו.
  2. אין פשוט מה זה אומר, שלכאורה, אין אפשר לעשות שדבר אמת לנגד אחד ולא לנגד חברו, שמה שקרה קרה, והרי הוא במציאות, ואי אפשר שיהיה במציאות רק לגבי אחד. ותו"ת.
1. אולי כיון שלא עושה שום איסור, פשוט שלא חל. יש חידוש כאן, שעושה איסור, אבל רק לא מחדש איסור. יש לדון אם עושה איסור, שאין איסור חל על איסור, וכבר היה איסור. ונראה כמה צדדים:
  1. אם באיסור חל על איסור יש עדיין סיבה רעה, הרי עשה שום דבר.
  2. אפשר שהיייתי אומר ששני האיסורים חלים (ואפשר שאין הקמ"ל שלא חלים, אלא שאין זה מהני, שצריך לאסור מה שהיה מותר, ולא רק לחדש איסור). זה אומר שאולי מה שאין איסור חל על איסור בא ממה שקשה לדבר להיות לו יותר משם אחד (שרק אחד יהיה עיקר שמו). אם כן, כיון שאין שני השמות סותרים כל כך, שהם שניהם אשת איש, אולי יותר קל לאיסור לחול על איסור. אם כן, יהיה עושה איסור כאן. ותו"ת.
עיין לקמן שנדון בדין כאן, ואז נמצא שאינו כל כך פשוט.
** קידושי ראשון -
לכאורה, בזמן חלות שני, צריך לדון למה אומרים שאין השני עושה איסור, אלא ראשון עושה איסור, שבאותו זמן, יש שני סיבות לאסור, ורק איסור אחד נברא. צריך ביאור למה מה שהיה כבר יברא איסור יותר ממה שלא היה כבר. אולי הוא מפני שיש יותר סיבה לו, שיש סיבה במה שהיה כבר. יש לדון למה כל כך פשוט שזה יותר חזק ממה שהיה בו סיבה באותו זמן (שלהפך, יש לומר שמה שהוא באותו זמן מחזקו), אבל לכאורה, פשוט שהוא כך ממה שאומר גמרא, “השתא מכורה כבר….” וצריך ביאור.
** מאי דאסר שרא -
עיין במה שפירש רש"י בזה. כמו כן, יש לומר שאמר כן בשני גיטים שונים, ודנים איך לפרש כן בגט שני. מרש"י משמע שלא היה גמרא מסתפק בזה כיון שהוא גט שני.
גם היה אפשר לומר שדן אם נותן גט אחר על ראובן ושמעון. יודעים שרק מכוון לראובן ושמעון, אבל דן אם רבנן סוברים שגט מהני לבטל יחס לנגד שאר בני אדם, אלא שיחס לנגד ראובן ושמעון עדיין אוסר (ואז יהני גט זה), או שלא מהני גט ראשון כלל.
צריך לבאר כל זה, שאם יחס לנגד זה אוסר לכל, צריך לבאר מה עושה- ומה נחשב, באמת- “יחס לנגד זה.” וצריך לחשוב.
** ואלא
- עיין במה שפירש. היה אפשר לפרש ששואל איך נמצא מדאורייתא, שהרי הוא קרא, וצריך להיות אופן שיתקיים מן התורה. לא אפשר לומר ציור שפירש רש"י לעיל, שהרי זה תלוי במאמר, ומאמר לא חל מדאורייתא.
אי אפשר לומר כן, שמגמרא יבמות נמצא שאין קרא זה דרשה ממש. וצריך לעיין שם. ותו"ת.
* פג.
** משום דסליק -
דסליק מינייהו- יש לציין לגמרא בתחילת נדרים ונזיר שמזכיר שני הסברות האלו (אם נתחיל במה שהיה ראשון או במה שסלק ממנו). ותו"ת.
** אף אעלמא -
יש להעיר שאם כן, לכאורה, מיותר הוא. ותו"ת.
** כמה מן הפירכות
שיביא הגמרא הם פשוטים ביותר. צריך ביאור מה היה ההו"א להביא ראיות אלו.
** כהן -
זה מעניין. היה נראה לומר, בלי זה, שהיא נחשבת, לגבי כל, קצת מגורשת, דהיינו, שנתק כמה מאיסורי נשואים, אבל לא כולם. אם כן, לא יהיה חלוק בין כהן זה לאחר. משמע שהיא נחשבת מגו’ לזה ולא מגו’ לאחר. צריך ביאור מה זה אומר. אולי איסור כהן הוא רק לבוא על מי שהותר לו על ידי גרושים. צריך ביאור למה יהיה כן. אפשר להסביר קצת לומר שזה נעשה חלק יותר חשוב של שמה לנגדו. ותו"ת. עדיין צריך ביאור למה נחשוב כן מקרא (שקרא רק אומר גרושה). ויש לדון. ותחשב.
** וקל וחומר -
גמרא אומר קל וחומר מרש"י. לכאורה, של רש"י יותר נראה, שרש"י מפרש למה יהיה אסור, וקל וחומר מפרש למה, כרבי אליעזר, היו לו להיות שניהם מותרים, ואז צריך לומר נגד רבי אליעזר. ותו"ת.
** אין משיבים -
יש להעיר שר"ן כ’ שסתם חכמים שחולקים על רבי אליעזר הוא רבי יהושע. אם כן, רבי יהושע, שהיה שם במעשה זה, היה באותו מחלקת. צריך ביאור, אז, ל"ל יפרש להם מה היה המחלקת.
אולי לא היה ר"י שם, אלא אמרו על דבר אחר (אולי על דין אחר, או על דין אחר, אבל לא מחמת שהם השיבו), וגמרא מביאו לזה. דחוק.
** נענה
- היה אפשר לומר שנקרא כאן נענה, כיון שהשיבו למה שאמר רבי אליעזר. ותו"ת.
** אצלו בזנות -
צריך ביאור, שהרי כיון שלא עברה עדיין, הרי מותר אצלו בכל. ותו"ת.
* פג:
** על מנת שלא תשתי -
צריך ביאור למה "שלא תנשאי" חלוק מזה, שאף כאן, אוסר אותה לדבר שיהיה לכל זמן. אולי הוא מפני שאפשר לאותו למות. חושב אני שיש תוס’ ששייכים לזה.
** כוותיה -
היה אפשר לומר שסבר שאינו נכון, אבל אין הקושיות שיש לנו עכשיו מוסיפים בירור גדול לזה, שהרי הוא מת. על זה, היה להקשות שהרי אף הוא השיב, וצריך לומר שסבר שמוסיף בירור (כמו שאמר גבי שאר). קצת קשה ל"ל הקשה גמרא כך. ותו"ת.
** חיי -
יש להעיר שנמצא שגט זה לא עושה כריתוות לעולם[fn:7], שהיא עדיין מיוחסת לו עד שיש סיבה אחרת לניתוק היחס (והוא מיתתו). ותו"ת.
* פד.
** נשיהם נותנים -
לכאורה, הבעיה הוא שיחשבו בני אדם שנותנים נשיהם בלי גט. ותחשב. וקשה, שרק יודעים זה מחמת התנאי, ועשה אותו על גט. אולי ישכחו בני אדם, ויזכרו רק שזה גרם שאשתו ישא זה. גם יש לומר שחוששים שמא יחשבו שחברו נתן או ייתן לו אשה בחילוף זה, ואולי הוא לא גירש. ותו"ת.
** על מנת שתעלי -
קצ"ב למה נותן כל כך כמה ציורים.
** רב יהודה -
משמע שלחולק על ר"י אינו קשה. יש לדון שכדי לישא זה, צריך אף לישא אחר, ואסור לאותו אחר. יש לדון, שאולי כיון שנשא זה בינתיים, לא נראה כמחליפים נשותיהם.
** נמי דיקא -
מעניין, שבדרך כלל, לא מביאים את זה אלא אם כן כבר הביא (או קאי על) משנה. אולי הוא רק אגב אותו גמ’ בב"מ.
** אפשר דאכלה -
קשה ל"ל אומר שמתנה על מקרה אונס שיגרום שתאכל בשר חזיר.
** אלא אבא -
ק"ק למה מניחים שהיא תעבור, ולא שאביה יעבור. אולי הוא רק מפני שזה טוען ששני בני אדם יעברו. גם יש לומר שרק אשה תעבור, שהיא תהנה במה שאז תוכל לינשא. ויש לדון, שאף אב יהנה, שתתן לו ממון (כמו לאותו פלוני שמזכיר גמרא).
* פד:
** על מנת שתשתי יין -
לכאורה, פשוט שאין זה דבר אסור, שיכולה לשאול.
** רבנן -
ק"ק ל"ל אומרים זה בדבר שהוא ממש אי אפשר. אולי בזה אף מגלים שאינו מתנה על מש"כ בתורה.
** מתנה -
זה מעניין, שתורה אומר שקידושין יש לו שאר וכסות…, אבל לא אמר שאין חלות תלוי על דברים אלו. אם כן, צריך ביאור איך יהיה מתנה עמש"כ בתורה. אף ת’ גמ’ אינו כזה. כל גמ’ זה מעניין; וצריך לח’ עליה.
** תיפוק ליה -
יל"ד למה שוהה עד כאן להק’. יש לדון אם זה בעיה.
** איהו קא עקר -
קשה, שהוא רק גרמא, והרי גמ’ לעיל קרא לזה שאינו עוקר. ותו"ת.
* פה.
** לאחר -
צריך ביאור למה לא יחלקו אף בזה, שאף בזה יש לגזור אטו כתיבת חוץ.
** ורבא -
נראה שאולי הוא לשיטתו, שכדי לומר שמשנה מיירי רק בכתיבה, מוכרח לומר לשיטתו שקאי על אחר התורף, שלפני התורף, לא צריך כתיבה אלא אמירה.
** מיחלף -
צריך ביאור למה, שלכאורה, יותר מוזר שישכח מה שהוא עיקר של משנה. עיין ברש"י שכ’ שישכח שניהם, אבל רק זה יזייף מדעתו. נראה שהענין הוא שבפסול או כשר, יש רק שני יכולות, ואז יחשוב ויזייף מדעתו כיון שבין כך ובין כך הוא חצי על חצי. אבל, אין לזייף לומר "הרי זו,” שיש הרבה דברים לומר, שיש לתת שם של כל תנא שם. אם כן, לא יזייף, שמסתמא לא ימצא. (ויל"ד, שלמעשה בכ"מ יהיה נכון לומר "הרי זה" שיהיה שום תנא שסובר כן. ויש לדון.)
גם היה אפשר לומר שבני אדם שוכחים
** לאבא -
נראה שההוה אמינא הוא שיש עדיין אישות, אלא שלא עושה תוצאה. יש לדון אם זה אינו בעיה כיון שאינו חשוב כיון שאין בו נפק"מ, או שכיון שאין בו נפק"מ פקע מעצמו (כמו קידושי חוץ שלא מוסיף איסור). ותחשב על זה.
** בר הוויה -
ר"ל שעושה נפק"מ לאחר זמן. דן אם זה חשוב. ואם תאמר איזה ראיה מביא, שמי יאמר שחשיבות של נפק"מ שייך למה נחשב בכלל ההיקש. ויש לומר שבשניהם דן אם אומרים שעומד להוויה כבכלל הוויה, ואז שניהם תלויים בחד דבר. ותחשב.
** נולדים -
מעניין, שאינם בעולם, ואז אין איסור להם עוד שיכול לשאר. אולי משאר אותו חלק מן הקידושין שיעשה איסור. ותחשב.
** מיתה -
לכאורה, כאן הוא חצי על חצי, שתלוי מי מת ראשון.
** [רש"י
כ’ במק"א שנתגלה שדבר עומד. קשה, שאם עומד תלוי במה קורה, ומה נתגלה למפרע, אז קשה איך אומרים כן בדם שעומד ליזרק. נראה לומר ששני הדברים (שהיה מוכרח לקרות או שהיה מסתבר וכמעט קורה) נחשבים עומד. צריך לדון בזה בכל הגמרות[fn:8].]
** גופו של גט -
יש שדנים למה אין זה בתחילת מסכתא. שמעתי מר"ד ליפשיץ שהוא מפני שדבר הראשון שמזכיר מביא אגבו דיני שטרות ולומדות של שטרות. ותחשב. באמת, אין הקושיה כל כך קשה, שמצאנו כן כמה פעמים. ותחשב.
** איתקש הויות -
עיין ברש"י. כוונת גמרא לומר שאיתקש יציאה, ואיתקש לכל הוויות, שכולם נכללים בקרא זה. ותחשב.
** מתרומתיך
- גם היה אפשר לומר שהוא שתאכל תרומה, אף שתנשאי לזר.
** הפרת נדרים -
מעניין שמניחים שיש לו אותו כוח (ר"ל, אולי הוה גט, ואין התנאי חל).
** משכבי -
לכאורה, כיון שהצד בא ממה שהוקשו שני המשכבות, צריך לומר שיודעים דין של משכב כדרכה. מעניין, שלעיל רק דן בזנות, ולא בדין זנות של משכב בדרכה.
* פה:
** קל וחומר -
צריך ביאור, שלכאורה, בעבד, לא מובן שרק יפקיר לו עבודתו, אבל גבי אשה, יש צד כזה.
** רב ששת -
נמצא שלכאורה, רק מביאים ראיה מר"ש, ולא מברייתא.
** לכשתברח -
מעניין שאומרים, “לכשתברח,” ולא, “אם תברח.” משמע שמניחים שיברח. ותו"ת.
** אמר אביי -
יש לציין לסוף פרק מצוות חליצה, שאביי גם כן אומר כעין זה. יש להעיר שקצת מעניין שאביי אינו כל כך מדקדק בדרך כלל בתוך משניות או דרשות על לשון. ותו"ת.
** יש לדון אם
באלו ממש חוששים שכך ר"ל, או שהוא רק חומרא של אשת איש (שיש חשש קטן שכן ר"ל), או שאין הגט נראה כשר, או שבעל יוציא לעז.
** הרי את בת חורין -
לכאורה, אומר לשון נקבה אגב רישא של משנה.
** ולא איגרת -
עיין במה שפרש"י. יש להעיר שלכאורה, לשון גג לא שייך לכל הגט. אולי הוה אמינא שהוא שטר של נתינת גג.
** תהוייין -
לא הבנתי כל כך הביאור; לא הבנתי כל כך מה אומר רש"י לבאר את זה.
** למחך -
עיין ברש"י. חושב אני שיש שני פשטים בזה, למה יטעה בהי"ה וחי"ת, אם הוא מפני שנראים שווים, או שנשמעים שווים. חושב אני שאולי זה תלוי, שלספרדים, אין ח של ספר תורה דומה לה, אבל נשמעים שווים, אבל לאשכנזים הוא הפוך.
** לורכיה לוי"ו -
מעניין שחושב גמרא שהארכת וי"ו עושה שלא נראה כל כך כיו"ד.
** ודן -
עיין במה שבאר. ק"ק ל"ל שואל גמרא כמי הלכה, אלא שואל לשון זה. לולי רש"י, היה אפשר לומר ששואל אם צריך לומר "וזה,” אלא די לומר עליו "גט כריתות,” ונבין שאומר שהוא גט כריתות. גמרא מביא רבא שלא אומר שצירך לומר כן, ושוב מוכיח שאם נאמר שרבא כרבי יהודה, צריך לומר שלא כ’ כל מה שצריך לומר.
** לאפוקי -
ר"ל, כיון שלא בא לומר כל מה שצריך לומר, צריך לומר שבא להוסיף דברים שצריכים לומר. אם כן, צריכים לבאר למה צריך ולמר אותם דברים בתוך שטרו.
** לאפוקי
- שם פסול- לכאורה, ר"ל שכיון שאין ההלכה כחכמים, לא היינו חוששים לשיטתם, ואף באשת איש החמור, אלא שיש לחוש שבני אדם יוציאו לעז שהלכה כחכמים, ואז רצה לכתוב כן.
* פו.
** וכל שחין -
לכאורה, צריך לומר שאין זה בכלל מום. נראה שלכן כ’ רש"י שמום ר"ל שהוא לסטים מזויין. וצריך ביאור קצת מה עם יש מום אחר. צריך לומר שאין אחר שמקפיד עליו בני אדם. אפשר לדחות שנתרבה משחין. ותחשב.
** צריך ביאור
למה כ’ כל אלו בתוך השטר. מרש"י, קצת משמע שכ’ על שחין כדי לעשות שיעכב (לכאורה, כדי שיש מועטים שמקפידים, ולא די לעשות מק"ט, אבל לא רצה שיהיו אותם מיעוטים עצבים. יש לדון, שעכשיו קשה למוכרים למכור. צריך לומר שלא קשה להם למצוא מי שאינו מן המיעוט.). עדיין צריך ביאור למה כתבו על מה שאינו של אחר.
גם יש לדון למה כתבו שאין בו רושם של אחר, ולא רק שאינו של אחר.
* פו:
** יש לה בנים -
עיין במה שפירש. גם יש לדון שאגב שמכשירים הנשואין לענין הבנים, גם מכשירים לענין הנשואין עצמה. ותחשב.
** זמן לכל אחד -
היה אפשר לומר שכיון שיש דבר אחד שהוא לכולם, מוכרח שהם אחד. קשה, שנאמר שממה שיש עדים על כולם, הם אחד. אלא, אפשר שעדים קאי על אחרון. אם כן, נאמר שאף זמן קאי על אחרון. אולי אפשר להיות גט בלי עדים, שהרי שאולי לא מצאו עדים, אבל לא בלי זמן, שלמה לא יכתבו זמן. אז, צריך לומר שגט קאי על כולם.
גם אפשר שמניחםי שעדים הוא על כולם, שמסתמא כולם בכשרות נעשו, אלא אם כן נוכיח כן ממה שיש זמן לכל אחד ואחד.
* פז.
** אפילו זמן אחד -
אחרון מפסיק- יש לדון למה צריך זה. אולי מה שלא מניחים שקאי על הכל הוא מה שיש הפסק. גם יש לומר שמה שמניחים כן הוא מפני שאין הכרח שקאי על כולם. מבאר למה מניחים שקאי על תחתון. ותו"ת.
** ומשחררים זה את זה -
לכאורה, מניח שנותן חצי של זה לזה וחצי של זה לזה. יש לדון מהיכי תיתי שאינו נותן של זה לזה וזה לזה, ואז אין אחד קונה כלום.
ודע שלכאורה יוצא מזה שיכול חצי עבד לקנות ולשחרר מי שהוא חציו עבדו. ויש לדון, שאולי משחררים בבת אחת, והוא כעין גטו וידו באים כאחד. ותחשב.
** איש פלוני… -
צריך ביאור למה ברייתא מזכיר שלוש, שאם בא להזכיר כולם, יזכיר חמש, ואם רק מראה הצורה, יזכיר שנים. אולי רצה להזכיר את רובו. ותחשב.
* פז:
** שמא דאבוה -
קשה, שאם נאמר שחתם רואבן בן, ויעקב, אז צריך לומר ששמו של אביו הוא ראובן, כמו שפ’ רש"י. אם כן, קשה ל"ל אומרים שיעקב הוא שמו, ולא שם אביו. אולי מכירים שאין זה של איש ששמו יעקב. אם כן, לכאורה הענין הוא שחוששים שהוא של שני אנשים, אחד שהוא בן של ראובן, ואחד שהוא של אדם שהוא בן יעקב. ותחשב.
** חרותא -
צריך ביאור למה עשה כן. לכאורה, אינו יותר קל מכתיבת שמו. אולי הוא יותר קשה לזייף. ותחשב.
** סמך -
יש לדון למה לא כ’ אות מתחילת שמו.
** מכותא -
איני יודע את המציאות כל כך, אבל צריך לומר, לכאורה, שאינו רק עץ אדח שעליו נותנים וילון, שאם כן הוא רק קו, וקל מאד לזייף. ותחשב.
** גט שכתבו -
לכאורה, החידוש בזה הוא שאף ששם איש נכ’ באופן עברי, ושם עדים לא נכ’ כן, כשר. גם יש לומר שהחידוש הוא שלא חוששים שהשם של איש נכ’ באופן יווני ואינו איש זה. ותחשב.
** וכך היו נקיי הדעת
- קשה, שאם רצו לקצר בלשונם, יכתבו, “פלוני עד,” שהוא יותר נמוך. ויש לומר שלא חשו להאריך אם יש טעם טוב להאריך. יש טעם לכ’ את כל שמם כיד שיהיה קל להכיר אותם. אז, הוצרכו לומר שמם ושם אביהם. אז, רק גרעו, כדי לקצר, מילת "עד.”
** וכך היו
- גמרא אומר בפסחים (ד) שיש סיבה לקצר בדברי תורה, אבל לא אומר כן שם בדברים אחרים. אפשר שהוא קצת קל וחומר, שאם בדברי תורה, שכל מילה הוא מצווה, יש לאדם לקצר, לא כש"כ בדברים אחרים. ויש לדון, שלכאורה, יש ללמוד בשאר הזמן. ותחשב. גם מעניין אם נאמר שהוא ממש כך, שאז מי שמדבר במילים גדולים שכוללים כמה מילים לא יקיים כל כך כמה מצוות. ותחשב.
גם יש לומר שעשו כן כדי שלא לבזבז את הזמן. גם יש לומר על פי מה שמשמע מגמרא עירובין (נד) שהיה דרך מיוחד של שיחה שהוא שיחה של חכמים, והיה דבר טוב לעשות כן. מצאנו, אז, שישדרך טוב לשיחה, ואף לשיחה של חולין.
** חניכתו -
עיין במה שפירש רש"י. איני יודע כל כך מהו. מרש"י משמע שהיה שם לאותו משפחה. אם כן, דורות שמזכיר גמרא הוא שנקרא המשפחה באותו שם, ואף אם רק נקרא כן לפני כמה שנים. ותחשב. לולי רש"י, היה אפשר לומר שענין דורות קצת משמע שיכול אדם לחתום בשם של אבי אביו וכדומה (ואולי כ’ בן ואולי לא כ’ בן, ורק לא שביק איניש… לנקט שם של אביו, כיון שהוא קצת בזיון). ותחשב.
** מחתתא דמגילתא -
ואם תאמר הרי בהכרח כתבו כשנטלו מן הבהמה. ויש לומר שלא דומה חתיכה לפני הפרש עור לתוך דוכסוסטוס וקלף, ולפני מליחה, ללאחר מכן. ותו"ת.
** רב -
לכאורה, ק"ק איך היה הגג כלפי הגט, שרב לא חתם באותיות אלא בכוורא. אולי זה חלק מן התירוץ (שחתם באופן שיכול להיות גג כלפי גט, שחתם באותיות). גם יש לומר שלא היה עליון של הדג שלו שווה כתחתון שלו. כמו כן, יש לומר שלעולם עשה שדגו הולך לצד אחד, ואז יכולים להבין מהו העליון ומהו התחתון. ותו"ת.
** חתם סופר -
לכאורה, מכאן נטל חתם סופר שם ספרו (וכן בנו, הכתב סופר). אם כן, לכאורה לא היה לנו לומר כדרך שבני אדם אומרים שם של חתם סופר וכתב סופר, אלא בלשון עבר, שלכאורה כן הוא במשנה. ויש לדון, שאולי אומר שעדות של עד ושל סופר…. קשה, שאם כן, היה לו לומר "חתימת,” או כדומה, ולא חתם. ותחשב על זה.
שוב נראה לי שהוא לשון כמו כתב עם שוו"א תחת הכ’, כמו שנאמר, וזה מילה ממש. נראה שאף חתם הוא כן, ונותנים פתח במקום השווא, וכיון שכן אומרים בלשון נכון. ותחשב.
** ג דורות -
יש לדון אם זה כולל אף דור שלישי או לא. עיין לקמן, שמביא סמך לזה מ"ונושנתם.” רש"י מפרש שמכאן ואילך ונושנתם. יש לדון ברש"י, ויש לדון בגמרא אם ר"ל שאחר כן נושנתם, או שבלידת בנים ובני בנים נושנתם.
נראה שאולי לשון "מכאן ואילך" משמע שדור שלישי כבר נקרא ישן, ואז פסולים להעיד.
** יש להעיר
שמצאנו, לכאורה, סמוכים לצד שצריך שלש ולצד שצריך עשרה. יש סמוכין לשלש מדין מצרי שלשי (אלא ששם דור שלישי מותר, ויש לדון כאן). גם מצאנו כעין זה ביבמות בענין כמה חי ממזר (כן אני חושב). מצאנו עשר לענין מאמר של חז"ל שעד עשר דורות לא משכח גוי את אומיו, וכן לענין דיני ממזרת (לחד שיטה ביבמות).
** כמאן -
כמובן, ק"ק, אז, ל"ל רק אמר שהל’ כמותו. וי"ל שלא ידע שאמר כן, אלא חשב כן מדעתו.
** ז’ בתי דינים -
בתי דינים ר"ל בתי מלכות. לשון זה מוזר; אולי נקראים כן מפני שלא היה להם כל כך דיני מלכות כמלכים של בית דוד.
** עליו עלה -
לא קשה לומר שאף שלא חטאו כל כך, נתמלא סאתם אז, ואז ה’ פרע מהם על הכל. ותחשב.
** פרדסיאות -
משמע שמה שהיו יכולים לטעון שלא באו לפני כן מחמת השומרים היה שקר. אם כן, ק"ק ל"ל ענש אותם ה’, כיון שהכל גלוי לפניו. כמו כן, הערנו בשיח שי גמרא גמרא בכתובות שאומר שצריכים להחזיק טובה לרמאים, שהם נותנים סיבה שלא נענשים אם לא נותנים צדקה. קשה, שאילו היינו נותנים בלי רמאים, אז א"צ, ואי לא היינו נותנים, קשה איך מציל.
מכל זה, משמע שטענה, אף שאינו אמת, מציל. נראה שאולי הענין הוא שמחמת האונס, אין ציווי. אף שלא היה עושה אף אם יש ציווי, זה לא מחייב אותו, אלא נפטר כיון שלא עבר על ציווי.
זה יהני כאן, אבל לא נראה שיהני בגמרא בכתובות, שהרי שם לכאורה אף עם חשש רמאים יש חיוב, אלא שאינו כל כך רע, כיון שהיה לו סיבה טובה שלא לתת. ויש לדון.
** כחרשים -
לכאורה, ר"ל שלא שומעים ולא מדברים, שלא מבינים מה זה אומר, וממילא, אי אפשר להשיב עליו. ותחשב.
ודע שלכאורה שאר חרשים היו מבינים זא"ז, ורק לא היו אחרים מבינים.
** סוגרים -
היה אפשר לומר שהפירוש הוא שכיון שהם סוגרים סוגיה ומסיקים מסקנה, אין אחר יכול להוסיף עליו כלום. אם כן, הוא, לכאורה, שווה לראשון. אז, לא מפרש כן רש"י. ועיין שם.
** גלות צדקיה -
משמע שבניהם ותלמידיהם של גלות יכניה לא היו צדיקים ותלמידי חכמים כמו גולים. לכאורה, זה מחמת שהיו בגלות.
** החרש -
צריך ביאור ל"ל מביא דרשה בשבת שלא החריבו עד שפסקו כל ת"ח (ואף לא ידעו ושכחו…).
* פח:
** מהר -
מניח שהמהר הוא "ונושנתם.” אין זה כל כך פשוט, שלכאורה, מקריאת הפסוק, היה נראה לומר שאם בני ישראל חוטאים ונושנים, אז יביא עליהם ה’ רעה מהרה. אז, אולי הרעה היה בא מיד.
** ותולה עצמה -
קשה, אז, איך מהני אם עושה על דעת ישראל, שיעשה על דעת האשה. ואולי ר"ל שעושה על דעת בית דין. דחוק.
** מיחלף -
מעניין שלא אומרים שכדין דישראל יחלף בכדין דגוי וכדומה, ואז נאסור אותה מלישא. צריך לומר שדין זה ידוע, ודין זה אינו ידוע. ותחשב.
** תנאי -
לכאורה, אין החידוש שנוהגים כאילו היו קידושי תנאי, שלכאורה, פשוט שלא צריכים לנהוג יותר חמור בן האמתלא. אז, לכאורה, החידוש הוא שלא נוהגים קידושין כלל, שאומרים בני אדם (כמו שאומר גמרא לקמן) שבדקו רבנן ומצאו שלא חל הקידושין מחמת תנאי. אם כן, לכאורה, זה רק אם לא ידעו התנאי להיות ידוע שחל (או שלא ידוע התנאי או יכול להיות שלא קרה ובני אדם לא ידעו).
** בתר נשואין -
וי"ל שנוק’ אותו בתר אירוסין. ועיין לקמן בגמ’.
** ובלבד -
משל וטעם- לשון משל קצת מעניין כאן. ותו"ת.
** זרק לה
- איפכא- לכאורה, הזכיר כן כיון שעל כעין זה דן בגמרא יבמות אם שם נהפך.
** הכי קאמר -
ואם תאמר אם כן, כבר נלמד מדין אמתלא. ויש לומר שקול זה יצא לאחר זמן, דלא כאמתלא. קשה, שזה גופא מחלקת באמתלא. וי"ל שאף לחולקים, יש זמן לאמתלא, וזה אף בתר אותו זמן. גי"ל ששאני כאן כיון שאינו מבטל קול ראשון (לומר שלא קרה כך), אלא אומר שקרה דבר אחר. יש לדון מה לנו בזה.
** שם מזנה -
עיין ברש"י בביאור האיסור. היה אפשר לומר שהיא נשואה, ויצא לה שם זנות, אלא שאז מותרת לבעלה, שהוא קול שלאחר נשואין. עדיין יהיה נפק"מ לאסר אותה על כהן אחר מיתת הבע, אלא שאולי כיון שלא חוששים לענין ביאת בעל, אף אל נחוש מחמת אותו קול לכהן. ותחשב.[fn:9]
** משישאו -
יש לדון אם אומרות שזנה או שאכלה בשוק וכדומה.
* טז.
** מתחת ידי שניהם -
לכאורה, לא צריכים ששניהם ממש אדוקים בו, אלא ששניהם שלוחים. ותחשב. אולי לא ידוע (או שלא ידוע לבית דין או לא ידוע ומינכר לבני אדם) אלא אם כן ממש יוצא מתחת ידי שניהם. ויש להעיר שלכאורה, יהיה נאמן לומר שאף חברו שליח מגו שיכול לומר ב"נ וב"נ, ואז נאמין ששניהם שלוחים. (ויש לדון אם יש מגו מנאמנותם לומר ב"נ, שאם כן, יהיה נאמן לומר שהוא עצמו שליח, ולתוס’ יהיה קשה מהו החילוק בין אחד לשנים. וצריך ביאור.)
* טז:
** מכשיר בזו ולא באחרת -
יש לדון אם ברייתא אמר, “ולא באחרת," או שרק מדייקים כן מן הברייתא (כיון שאמר, “בזו").
** דלמא אתי -
נראה שהחילוק הוא שכדי לגזור שמא יקלקל, צריכים לחוש שיחליף כשיקלקל ושיקלקל. כאן, רק צריכים לחוש שמא יחליף. ותחשב.
** לשיולי -
מצאנו כ"פ ששאלו לת"ח כשהיה חולה. אולי רצו להודיע לו שהחשיבו אותו. גי"ל שהיו להם שאלה, וכיון שהיה חולה, הלכו לו (אבל לא שאלו יותר מאילו לא היה חולה). גי"ל ששאלו לו כיון שזמנו קצר.
** רבה בב"ח -
קצת מעניין, שהיה, לכאורה, תלמיד של ר"י ור"ל (ברוב פעמים, מה שאמר בא מהם). רב יהודה היה תלמיד של רב. אם כן, לכאורה, היה גדול מרבה בב"ח, שרב היה גדול מרבי יוחנן, ותלמידי רב היו גדולים משמואל (שמצאנו ששאל לר"ה, וגם מצאנו שרצה שר"א יכנס קודם שיכנס עצמו). ויש לדון, שאולי רב יהודה היה מאחרוני תלמידי רב, שהרי הלך אחר כך ללמוד משמואל (והיה שמואל עיקר רבו, שרוב מעשיו על פיו, כמו שאומר רשב"ם בב”ב). ויש לדון.
אם נאמר שלא ממש היה ספק, אלא רצה להודיע שהחשיבו, אינו כל כך קשה. על"ע.
* יז.
** שאין יכולים -
ק"ק, אז, ל"ל אמר גם בטולא של בבל. ויש לומר שזה יותר קשה, שכבר בטלו בני בבל, שפרסיים באו. ותחשב.
** חברא -
עיין במה שהזכיר כאן רש"י. כן מפרש ג"כ בפרק במה מדליקין (ל). דע ששם היה אפשר לומר שהוא ירא שמא ישכח אותו גוי ויהרוג אותו. יש לציין כעין זה למעשה של ר"ע עם הנר (לענין גם זו לטובה) בברכות (ס:).
** יתד היא -
עיין במש"פ רש"י. גי"ל שאמר בלשון תמיהה אטו אני אין אני יכול לחזור בו ממה שאמרתי- אלא חזרתי בי, ועכשיו אני סובר כשני. ותו"ת.
* יז:
** זנות לא שכיח -
יש לדון אם ר"ל שזנות לא שכיח או שזנות בבת אחותו לא שכיח[fn:10]. כמו"כ י"ל שלא מצוי שירצה לשמור אותה ממיתה (אבל זה לא נראה).
** שעת נתינה -
אצ"ל כן, שאפשר לו לומר שכוע"מ לרבנן, ויש לו פירות עד שעת כתיבה, אז בהכרח יש טעם אחר, לפי רבנן. אולי אז היה לו להשיב לשאלת גמרא למה יש זמן בביאור שני הטעמים.
** דאי לא תימא הכי -
עדיין יש לומר שלא חוששים לאותו יום, שהוא קצר, אבל חוששים לאותו שבוע, שהוא ארוך. אין זה, אז, ראיה חזקה.
* יח.
** מה הועילו -
צריך ביאור למה קשה על ריש לקיש מזה, שהרי כתבו וחתמו במדינת הים. אולי אינו כן, ומקשה מציור שלא חתמו עד שבא למדינת הים. גם יש להעיר שיש שגורסים שרש"י זה קאי על אותיבה בכיסתיה. ויש להעיר שרש"י בביאור תירוץ לקושיית גמרא ממדינת הים מזכיר זמן לפירות. אז, נראה שהיה קשה אף משם.
** קלא אית -
יש לדון אם יש קול מתי ניתן (אולי יש קול שמזכיר ממש מתי ניתן או שמזכיר קרוב למתי ניתן ועכ"פ יודעים שאינו ביום שכתוב בו) או יש קול שבא ממדינת הים. עיין ברש"י שמשמע שהקול לא אומר זמן; ויש לדון, שאולי רק אומר כן מפני שאי אפשר לסמוך על קול לומר זמן מיוחד (אלא רק לומר שאין הזמן שבו נכון), שהרי הוא כספק, או שרק מראה שהוא קרוב לאותו זמן שנאמר. ותחשב.
יש להעיר שלכאורה, הקול בא ממה שאומר ב"נ וב"נ בפני שנים ושלש, שמוציאים את הקול. ויש לדון בבא בשנים. אולי לא מצוי.
** יאמרו -
יש לדון אם הבעיה הוא שבני אדם יחשבו שזמן נתינה עיקר או שבני אדם יחשבו שזמן כתיבה הוא אותו יום של זמן נתינה.
** המשליש -
היה אפשר לדחות שלא מונים משעת כתיבה לכל, אלא רק לפי רבי יוסי, שסובר ביבמות שלא גוזרים לא פלוג בזה, ואז כיון שמניחים שלא בעל, לא צריך לשהות. (ויש לדון, שאין כל כך ראיה כאן שלא בא עליה; אולי רק מניחים כן לענין חשש קטן של גט ישן, ולא לחשש זה.)
** משעת כתיבה -
בדר"כ, אין הלכה כשמואל באיסורי, אבל כאן הלכה כמותו כיון שכן עשה ר"א.
** מאימתי כתובה -
נראה שדן בזה כאן כיון שיש בו מחלקת רב ושמואל, ויש ברייתא ככל אחד מהם.
** תפגום ותזקוף -
צריך ביאור למה צריך שניהם, שלכאורה זקיפה הוא שנעשה מלווה. צריך לומר שבלי פגימה, אין זקיפה חל. צריך ביאור ל"ל. ותחשב.
** משעת העמדה -
לכאורה, “משתזקוף" קאי על כולם, שאומר לשון רבים. אם כן, צריך ביאור, שכל קנס כבר נזקף, שאין חיוב קנב אלא אם כן עומד בדין. אולי אין הכי נמי. דחוק.
** דרבי חייא בר רב -
בדרך כלל, נקרא חייא בר רב.
** עסוקים באותו ענין -
קצת קשה להבין סברה זה. ותחשב.
** משתפגום -
עיין במה שבאר. צריך ביאור מה אומר.
** מה מעשה
- צריך ביאור למה מניחים שחייבו בית דין אותו משעת כתיבה, ולא משעת נשואין. מרש"י משמע שמחייבים משעת נשואין, אלא שמניחים שזהו שעת כתיבה אף אם אינו שעת נשואין. זה מעניין.
* יח:
** חיישינן שמא פייס -
עיין ברש"י שבאר שהוא גט ישן. יש להעיר שכל חשש גט ישן קשה אם נניח שיכול עובר לשהות בתוכה לזמן רב (עיין גמרא ביבמות פ:). אולי בני אדם לא יחושו שכן קרה. אף בלי זה, עדיין זה רק חשש אם נניח שעובר נולד בזמן שאי אפשר שבא מבעל ראשון. אם נולד לשמנה חדשים וכמה ימים, אינו בעיה, אז. ותו"ת.
* כב:
** והלא לאו -
מעניין שלא אומר שהבעיא הוא שלא יכולים לחשוב לשמו, שלא יכולים לחשוב אא"כ אחד אומר להם מה לחשוב. ואולי כן ר"ל.
** הכל כשרים -
משמע שלא צריך להיות שליח הביל (שאין אלו שלוחים).
* כג.
** והוא -
לשונו משמע שאמר כן על המשנה, לבאר אותו, ולא שאמר כן על הקושיה כדי לתרץ אותו. ותו"ת.
** וכתב לה -
ואם תאמר אטו לא ידע גמרא שדרש רבי מאיר משם שצריך לחתום. וצריך לומר שסבר גמרא שלומד ממקור אחר. גם יש לומר שסבר (וצריך ביאור למה) שאף שדורש מזה חתימה, סובר גמרא שלא ידרוש מזה לדיני חתימה, אלא ידרוש דינים עליו לענין כתיבה. ותחשב.
** אמוראי -
אולי הוא אותו אמוראי שחלקו בר"י אם הלכה כסתם משנה או לא (שאם הלכה כסתם משנה, מסתבר שסתם משנה כרבי אלעזר, שהלכה כמותו, ואם אין הלכה כסתם משנה, נאמר שסתם משנה רבי מאיר).
** לאו בר התירא -
ועוד שלא יכול להיות שליח (והיה לו להקשות כאן כמו שהקשה לקמן (שהיה לנו להזכיר אותו פסול)).
** לפי שאינו -
יש לדון אם ר"ל שאז אין סומכים חז"ל שאז קרה בטוב, או שר"ל שאז אין לאיש ואשה סמיכות דעת.
** אמר ר"ש -
יש להעיר שרב ששת ורב יוסף היו שניהם סומים.
** בלילה -
ואם תאמר הרי בכל זמן אסור לו לאדם לבעול כשיכול לראות את אשתו. ויש לומר שביום, הולך לבית אפל. רואה שרק הוא והיא באו שם, ויכול להניח בקל שלא בא אחר. אבל, בלילה, אינו מכיר שלא היה אחר כשבא שם, שלא נכנס שם שום אור. ותחשב.
** לענין הבאה -
אילו שייר כאן, יש לדון מה שייר עמו. אולי עבד שייר עמו.
** אמר"נ היה אומר -
עיין ברש"י. לא הבנתי כל כך שקלא וטריא של גמרא, שלכאורה כשחילק בין רבי אליעזר לרבי מארי, כבר פשוט שמכוון לומר שלר"מ לא צריך דעת. אילו גמרא רק מביא מימרא אחר שאמר שמסיק כן, כמו פשט ראשון של רש"י, לא קשה, אבל לפשט שני, צריך ביאור. ותחשב.
** דלאו בני
- רש"י מביא קרא, אבל גמרא לא אומר כן. נראה שאולי רש"י סובר שמה שלא נקרא איש- מה שבו הוא חלוק מ"איש"- הוא שאין לו דעת. גם יש לומר שגמרא מבאר מה לומדים מאותו דרשה (עד כדי שיכולים ללמוד מקטן לחרש ושוטה, שאף שהם איש, לא יכולים להיות שלוחים[fn:11]).
* כג:
** משחרר חצי עבדו -
צריך ביאור למה דין זה כן, שהרי לכאורה, אין לומר גיטו וידו באים כאחד, שהרי אינו משוחרר אז. ותחשב.
** אלא בפני בית דין -
עיין ברש"י. צריך ביאור למה סובר גמרא שזה עושה שחל גט כשנותנו, אבל רק אם באה לפני בית דין. לכאורה, היה עושה שחל גט כשבאה לפני בית דין, שכך אמר. ותחשב.
* כג:
** הא במילתא דאיתיה -
משמע מרש"י שיש יחס בין איסור אכילת טבל וחיוב לעשר. ותחשב.
* סז:
** מאי אסותא -
יש לדון אם זה בצירוף קמיעא, או כשאין לו קמיעא. לצד ראשון, יש לדון אם צריך קמיעא לכך, או רק מהנה אותו (עושה שהוא יכול מהר או יכול בטוח).
** אמרה לי אם -
נראה שאם של אביי היתה חכמה בזה, כיון שהיתה רק מי שגדל אותו, ולא אם. משמע שהיתה ביביסיט"ר, שהיתה מגדל תינוקות. אולי מחמת זה ידעה לרפאות. ויש לדון.
** שתי וערב -
יש לדון מה אומר:
1. אולי מקרע כמה קריעות לשתי וערב.
2. אולי מקרע קריעה אחת לשתי ואחת לערב.
גם יש לדון מה מקרעים לשתי, כיון שכבר יש כמה חלקים, שנקרע לערב:
1. מקרעים כל חלק.
2. מקרעים רק אחד.
** אפכי -
ואם תאמר איך היה מותר לעשות כן, שרב אמר ביבמות שאין לעשות כן מחמת שקר שבו. ויש לומר שכאן היה סכנה.
** בת חמש -
צריך ביאור איך הוכיח שחתכו מחי, ולא ששחטו עוד בהמה ונתנו את רגלו שם. ותו"ת.
** קמיעא -
משביעים- לשון זה מעניין; לכאורה, הענין הוא שמכריחים אותו לצאת בו, ולא שמשביעים אותו, שמה לנו בשבועה שלו. ותחשב.
** סיכוזי
- בקרן- משמע שהיה דרך אחר להקיז דם. אולי היה גם סכין, או leeches. ותחשב. גם יש לומר שמילת סיכוזי משמע כן רק מפני משמעות קרן.
* סח.
** דאמר ר"ח -
יש לדון אם ממש אמר משמו; אם אמר, יש להעיר שהיה שם, כמו שיבאר גמרא לקמן (אם לא שנאמר ששני המעשים קרו בזמנים אחרים).
** שרות -
משמע ששמע שירת נשים. קשה, שזה אסור. אולי שמע לנשיו.. גי"ל שהוא לשון נקבה כיון שאותם כלי זמר היו לשון נקבה, אבל לא שמע לנשים.
** כי צחי -
צ"ב שלא היה יכול למצוא מקום אחר לשתות ממנו. גם צריך ביאור למה עשו שלא יכיר שבא, כיון שאף שלא רצה לשתות, שתה. יש לומר שהיה מצער עצמו עוד שלא לשתות אילו ראה.
** שמא דמרך -
נראה שר"ל שאם ישבר את השלשלת ויצא, אולי ישבר אותו במקום שם ה’, ונמצא שימחק שם ה’.
** שמיר -
דבר קשה- נראה שבא לבאר איך לא חתך בצמר שבו היה שרוי. ודע שצריך ביאור למה לא חתך לתוך כל העולם. אולי רק חתך כשמי שנתנו שם רצה שיחתוך. אז, אין צ"ל כן לבאר ל"ל חתך בצמר. וכ"ז קצת צ"ב.
* סח:
** שרא דימא -
יש להעיר שגמרא אומר בב"ב שמת כבר מזמן רב.
** זוגיתא -
לכאורה, אילו לא ראה את בניו לא ירחם להביא. גי"ל שאילו לא ראה, לא יכיר שקינו שם.
** כי היכי דליכלא -
לכאורה, שני דברים אלו סותרים זא"ז קצת. וצריך ביאור.
** מאי רבותיה -
צריך ביאור איך היה טפש כל כך לעשות להתיר ממנו שלשלת. אולי סבר שכיון ש"לא יסור שבט,” בטוח שלא ימרוד בו, או שאסור למרוד בו, ואז לא ימרוד.
* סט.
** מגווא דחיותא -
לכאורה, לא ר"ל "מבהמה חיה,” שהרי אוכלו, ויהיה אבר מן החי. אולי ר"ל חיה, ולא בהמה.
** לוי למפרע -
יש לדון אם כותב: “יול,” או שכותב כל אות למפרע.
* סט:
** גירי -
עיין במה שפירש רש"י. נראה שאולי היו שני חלקים לחץ; היה הראש, שבו היה נקבות, ושאר החץ הלך בתוך אותו נקבות. אולי אף בזה היה כן, ולכן, כשהפכו, היה מקום לקבל.
** לגילויא -
יש לדון אם זה גם מהני אם נשכו נחש. אולי שם יש יותר סם. עכ"פ, נ’ שדן בזה כיון שהיה יותר מצוי, ועוד שנזכר כאן.
** כותכא -
נראה שאולי גמרא בשבת מכוון לזה כשאומר שהרבה אכלו כותח ונתרפאו.
** ונזדהר -
משמע שסובר שבמקום שאין נחש מצוי, אין גזירת גילוי. ויש לומר שיכול לעבור על איסור גילוי, מחממת סכנה, אבל רק אסור לו לגרום לעצמו סכנת גילוי.
* ע.
** עד דקאי -
כמובן, לא יקימו אותו אף אז, אלא הוא יקים מעצמו. ותו"ת.
** בטיבול -
עיין ברשי, שמשמע שהוא טיבול ממש. היה אפשר לומר שהוא לאכול, כמו שמצאנו בכ"מ שטבילה ר"ל אכילה.
** אחזתו -
יל"ד אם אוחז מי שמשמש או הבן הילוד. לכאו', ר"ל ראשון.
** שמונה -
ק"ק ל"ל מונה או שנמנו בברכות.
** כפלים -
יש לדון מה ר"ל. נאמר משל: בדרך כלל, זרעו הוא מאה. באלו, הוא שבעים וחמש. אז, יש לדון מהו כאן:
1. הוא חצי של זה (אז, שאר הם כפלים של זה), ואז הוא שלשים ושבע ומחצה.
2. הוא ממעט כפל, ואז הוא חמשים.
3. הוא ממעט עוד פעם, ואז הוא ¾ של שבעים וחמש, שהוא 56.25.
נראה לי שהוא השני.
* ע:
** אלא מעתה -
לכאורה, מקשה על מה שאמר שיודעים שימות.
** שיחיא דהן הן -
ואם תאמר למה חוששים לזה. ויש לומר שכיון שהוא נשתתק, יש סיבה לחשוב שנשתטה. אז, יש סיבה לומר שלא משיב כהוגן. כמו כן, יש לומר שכיון שנשתתק, לא יודעים איזה דברים אחרים מוזרים קרו לו; ויש לומר שגם נפל עליו שיחיא זה.
** ליחוש -
יש לדון ל"ל מוכיחים ממה שרק עושה כן כששואלים לו דבר.
** דבי ר"י תנא -
ואם תאמר הרי פשוט למצוא דבר שיודעים שצריך לענות לו, "לא.” נראה שמחדש שאף זה, שאינו כל כך פשוט, נחשב דבר שפשוט שיענה עליו, “לא.”
* עא.
** בפירי -
היה אפשר לדחות שרק משיב הן כיון שאדם זה שואל לו, וסובר שצריך לומר שיש לאדם זה, על יד שום דבר מופלא, פירות אלו לתת לו.
** וממאי -
לא יכול לומר שהוא מפני שיודע לשון הקודש, שלשון בריי’ משמע שבא להראות פ’ המילים. אז, צ"ל שאינם כל כך פשוטים.
** מפיהם -
היה נראה לומר שהדרשה הוא מ"פי.” אבל, קשה, אז, ל"ל אומר מפיהם, ולא מכתבם, ולא "לא מפי כתם.” ותו"ת.
** פרט לאלם -
ע’ ברש"י. נמצא שרמז כזה נחשב דיבור, על כל פנים לענין שבועה.
** עדות -
צריך ביאור למה סבר גמ’ שממה שלא נח’ דיבור, מי שרק יכול לכ’ אינו בר דעת.
** עדיות -
צריך ביאור איך היה מפרש בלי ת’ ראשון.
** ירושה -
קשה, איך ית’ אם עדות ר"ל עדות ממש.
** בכור -
עיין במה שפרש"י. קצ"ב, שגמ’ אומר שלא יכול להעביר בכעין זה. לולי זה, היה נ’ לומר שר"ל כשאב מכיר בכור. שו"ר שכ"כ תוס’.
* עא:
** חלוקים -
היה אפשר להביא בריי’ שלעיל.
* Footnotes
[fn:1] אפשר שהוא כעין עין הרע, שאז חושבים בני אדם על זה קורה לו, ואף שלא רוצים אותו כמו בשאר עין הרע. ותחשב.
[fn:2] ושוב נראה לי שענין שניהם יכול להיות שידוע שאין ה‛ רוצה בעבודה זרה, ומוכיחים מקרא זה שה‛ הוא גדול, ואז ראוי לשמוע לו.
[fn:3] כמו בעזרה, שמלך יכול לשבת. ויש לדון, שכאן היו אחרים עמו שהיו יכולים לשבת.
[fn:4] ויש לדון, שלכאורה, בכל מצב שהוא כך, צריך להיות שום סיבה להעדיף זה על זה.
[fn:5] ואם תאמר אם כן אינו כל כך רע. ויש לומר שבן סירא נכתב קודם משנה זה. גם יש לומר שאף שיש טובה זה, הרעה היא יותר רעה. ותחשב.
[fn:6] על פי אלו, היה אפשר לתרץ לקושיית אביי.
[fn:7] ר"ל, אינו, לעולם, נצרך לכריתות, שכשעושה שאינה צריכה לעשות דבר מחמתו, גם עשהו אחר.
[fn:8] שצריך לבאר מתי אומרים עומד, שלעולם יכול לומר עומד לשני צדדים, עומד ליקרב או שלא ליקרב. צריך לומר, לכאורה, שמין אחד (מה שכמעט עשה) דוחה מין האחר. ותחשב.
[fn:9] ועוד שכבר לא נהגנו כקול, ואינו יותר רע, אולי, אם תשא כהן (שלא עושה יותר חשד). ותחשב.
[fn:10] או שמסתמא הם אוהבים זה את זה, או שכל קרק’ שנצרך ממעט אותו יותר.
[fn:11] ויש לדון, שגמרא מזכיר ביבמות שיש עודף לחרש על קטן.
