- נראה שמה שקרא רבא לרהבדר"י "קאקי חיורי" הוא שבני אדם נקראים על שם שערם (עיין נדרים), והיה מכסה את ראשו (עיין בשבת ובמקום אחר), ואז קראו על שם זקנו. ותו"ת. (ויש לדון בר"פ.)
- עיין בגמרא טז. צריך ביאור מה אומר בנוגע רבי יהודה, ומהו שיטת רבי יהודה. כנראה, רבי יהודה משתמש בשני דברים:
1. גוד אחית.
2. טופח על מנת להטפיח הוא כחיבור.
צריך ביאור מה אומר להצריך שני נקודות אלו. אולי הענין הוא שגוד אחית עושה שהמים יורד להיות במקווה. יש בעיה בזה, והוא שאי אפשר לחשב כאילו המים הלך למטה, שהרי הוא אינו טופח בשיעור חשוב, ואז יש סתירה לגוד אחית. אז, לא מחתינן. צריך שיהיה טופח ע"מ להטפיח אז, כדי לחשב כאילו המים יורד.
ואם תאמר הרי בדרך כלל, בגוד אחית, אומרים שיש מחיצות שם, אף שאין מחיצות שם כלל. אם כן, אף כאן, נוכל לומר שמורידים המים, אף שאותו מקום כולו יבש. ונראה שאולי יש לומר חילוק (ויש לדון אם זה יחלק) בין גוד אחית זה לשאר גוד אחית. בדרך כלל, גוד אחית רק מוריד דבר. כאן, אינו כן, אלא אינו צריך להיות על גב המים.[fn:1] אם כן, צריך לומר שהולך דרך גופו. אולי כיון שכן, יש יותר צורך לגופו להיות כעין שהמים עליו. ותחשב על זה.
ואם תאמר אם מחשבים את המים להיות עליו, אז נמצא המקווה חסר. ונראה שמחשבים המים להיות במקומו ובכל מקום שהוא תחתיו (ולכן יכולים לעשות גוד אחית במחיצה, לריב"י, אף בפחות מעשר טפחים, שלא מוריד אותו ומפסידו ממקומו, אלא רק מוריד אותו, ומשאיר אותו במקומו.
- עיין בגמרא (מד) שדן באיש מחו"ל שנשא אשה מא"י ויש לה עבדים. יש צד שאף שנכסים שלו, אינו כמוציא עבדים, שאין העבדים שלו כל כך, שאינו קונה את גופם. רש"י מבאר שלא קונה את גופם כיון שצריך להחזיר אותם לאחר גירושין או מיתה. הקשה לי א.יכ. איך זה נכון, ששיטה זה אומר שצריך להחזיר לה רק ממון, אבל יכול לשאר את החפץ בידו. אז, צריך לומר שהוא קונה החפץ, ויש לו רק חוב.
קושיה טובה היא, ונראה שצריך לומר שכיון ששניהם משעבדים את עצמם בכתובה (רצה לומר, תקנו רבנן חיובים על איש וחיובים על אשה בכתובה). יש, לכאורה, שני דרכים לעשות שיקנה אותו בנשואים, ויהיה יכול להחזיר הוא או דמיו:
1. יקנה את גופו. יהיה גם חיוב דמים, אבל יהיה בטל אם מחזיר את החפץ.
2. יקנה את דמו. יוכל לקנות את גופו לאחר זמן, אלא שאז יחייב ממון.
אולי רש"י סבר- ויש לדון למה יסבר כן- שדרך השני הוא יותר מסתבר. ותחשב למה יהיה כן.
- גמרא אומר שחוששים מחמת ממזרים (לג). הקשה לי א.ד.ר.[fn:2] למה לא חוששים מחמת אשת איש. גם הקשה לי שספק ממזר מותר.
על קושיה ראשונה, אמרתי לו שפשוט לתרץ שרבה אמר ביבמות שאין גוזרים יותר על דבר שעונשו יותר חמור. אם כן, אין קושיה למה נקט זה ולא זה. גם יש להוסיף שאיסור ממזר קורה יותר, שיש הרבה יותר ממזרים.
על קושיה שניה, יש לומר שרע הוא לישא ספק ממזר. גם יש לומר שרע להיות ממזרים. נראה קצת סמך לזה מגמרא יבמות (לז:) שיש עליו אותו קושיה (לפי רבא, שם). ממה שאומר לשון "נתמלא כל העולם ממזרים" משמע שהבעיה הוא שיש כמה ממזרים. ותחשב.
- עיין בעח.. יש לדון למה אין ראייתה כשהיא ישנת דומה לנותן גט סתם, שיש ראשונים שאומרים שחל. יש לומר שני מהלכים:
1. לא תבין אלא אם כן רואה נתינת בעל לה.
2. צריך שבעל יהיה באומר לה. כאן, לא רואה מעשה בעל או כדומה, אלא גט, ואז לא חל. (אף כשעדים אומירם לה, מה שאומרים הוא מעשה בעל. ותחשב.)
- הקשה לי א.י.כ. שבפא: חוששים לא חוששים שבני אדם ילמדו לכשר פסולי עדות כיון שמניחים שיודעים דיני עדות. בפרק ראשון (יח:), לא אומרים כן, אלא מניחים שלא יודעים, ואז לא יחתום פסול ראשון (ע"ש). נראה שבדרך כלל, יודעים דיני עדות, אבל ממה שחותמים, לומדים שאין הדין כמה שחשבו. אז, אחד הוא ראיה יותר גדולה מחברו. הסיבה שאחד הוא ראיה יותרהוא אולי שאחד יותר נודע, או שזה יותר נודע להיות אותו דין (שרואים הקשרים, ומכירים). ותו"ת.
- הקשה לי י.ט. על גמ’ גיטין עט. למה מגו’ כיון שהגיע לאויר שלה, שגם צריך לבוא לתוך המחיצה. אפשר שזהו פירוש של אויר שלה. גם אפשר שמיירי בציור שנכנס בנקב או במקום שקצת יותר נמוך, ואז מגורשת משנכנס לאויר שלה. עדיין מוזר איך יהיה קאי על ציור כזה ולא יבאר, שהניחא מעקה מסתבר, שאף יש חיוב לתת מעקה, אבל לא מצוי שיכנס לנקב כזה.
- צריך לבאר דין חזרה שליחות אצל הבעל. לכאורה, יש כמה קושיות פשוטות:
1. לכוארה, כל שליח כלה שליחותו אחר שעושה כן, ואינו שליח אחר כן. לכאורה, הוא כן, כיון שאי אפשר להיות שליח כיון שהוא שליח לעשות חלות שכבר עשוי. ותחשב.[fn:3]
2. קשה למה צריך להיות שליח אחר שכלה שליחותו, שלכאורה רק צריך להיות שליח בשעת שליחותו.
3. קשה למה כלה שליחות האשה כיון שעושה את עצמה לקבל לעצמה. ותו"ת.
- עיין ברש"י גיטין לז. לכאורה, מה שמזכיר שחייב הוא שזה סימן שקנה אותו (לכן הוא חלק מתשלומים שלו). קצת צריך ביאור למה צריך לשלם ליותר מן שויותו. אולי היה חייב אף אם לא ניזוק, כשמשלם, וזהו מה שמשלם. ותחשב.
קשה למה מביא זה לראיה, כיון שגמרא מביא קרא לראיה.
- החשש לבקיעת הנוד הוא שמא ישפוך ונמצא שלא מפריש. אם כן, לכאורה היה יכול להפריש מה שיצא מן הנוד אחרון. אם כן, אף אם נאבד, יכול להפריש. ויש לדון, שאולי יהיה קשה לתת כך לכהן, שאולי קשה לשער אותו כשהוא עדיין בכלי. חוץ מזה, השיב ר.י.ש. לזה שחידוש של יש ברירה הוא שמה שיקרה לחפץ הוא קרק’ חשוב שלו. אולי לא כל מה שיקרה לחפץ שווה, ואולי אין זה חשוב די להיות תולה עליו חלות. ותחשב.
* Footnotes
[fn:1] חושב אני שזה נכון; תחפש למקור.
[fn:2] קושיה פשוטה היא, ורק לא ראיתי את הגמרא באותו פעם עד שהקשה לי.
[fn:3] לזה, אולי אפשר לחלק בין שאר שלוחים וכאן, שבשאר שלוחים, החלות הוא התוצאה לביטול שליחות, אבל כאן, היותה מקבלת מבטל את השליחות. יש לדון מה לנו בזה. אולי הוא שאילו לא היה חל, היה גלגל החוזר. ותחשב. עדיין צריך לחשוב על זה.
