** פרק חמש עשרה נשים ג.
תנא קורבי- קצת מעניין מה לי קורבי, שהניחא חומרי, זה מגלה שיש יותר סיבה שלא לייבם, ולפטור, וזהו גופא חידוש המשנה. אבל קרוב צ”ב. וצ”ל שכיון שקורבה הוא הפוטר (ועוד, שדנים בעריות, וקורבה אוסר בעריות) קורבה נקט. ואין לומא שזה סימן לחומרא, שלכאו’, מה שאין לו עונש חמור יוכיח שאינו באמת חמור. (א”ת הרי יש הוכחה שהוא חמור ממה שהוא קרוב. וי”ל כ”ז אכניס.) ואולי כיון שבא איסור מחמת יותר קורבה, יותר מיוחס הייבום לאיסור, דהיי’, ע”י ייבום נעשה יחס לאשת אח (ואולי זהו קיום שם) (ועוי”ל שזיקה הוא יחס הבא ממילא עם מיתת אח, ומפניהו יכול לקיים שם.). אם יש קורבא אחר, יחסו חלוק, והוא יחס רע, כיון שנעשין חד יחס, אי אפשר לתורה לדלג על יחס רע (תח’). אולי יותר קשה לדלג על יחס יותר חזק, ויותר יהא חשוב באותו יחס אחד. ותח’. (לזה, מש”כ גמ’ ק”ק, שלכאו’ שינוי יחס על ידי מה שלא בא לעולם יהא יותר חשוב, ויותר חלק מיחס, מפני שהוא פרט בעיקר יחסו. ותו”ת.)
אשת אחיו דלאו משום קורבה- צ’ לחלק בין אשת אח שהקידושין הם “בסוף” לבת אשתו שקידושין הם בתחילה.
** ד.
ואמר ר”ש- וא”ת למה מביאין את זה שהוא רק מאמוראים. ואולי מפני שהוא בדברים. ותו”ת.
מופנה- יש להעיר שמוכח עושה שמסתבר לדרוש סמוכין, ומופנה עושה שמסתבר לדרוש.
