** פרק חמש עשרה נשים ב.
וצרות צרותיהם- הק’ לי אחד שלכאו’, אין הנשים פוטרות צרות צרותיהם, אלא צרות פוטרות צרותיהם. תורץ לי שאה”נ, והדרך לקרא את המשנה הוא, “. . . פוטרות צרותיהם, וצרות, צרותיהם.” (ויש לדון אם נכון הוא, שדלמא נפטרו כיון שמיוחסים לערוה. ויל”ד למה נצטרך לזה, ולמה לא יפטרו מחמת אשת אח. ויש לדון, דאולי ייבום התיר את זה, ונשאר רק איסור צרת ערוה. ותח’.)
צרות- חשבתי על פשט לבאר צרת ערוה. צריך להקדים בכמה הקדמות והנחות:
א. איסור אשת אח אינו מחמת יחסו לה, אלא שיש לאח (אול אב שניהם) זכות לעשות שלא ישא אשתו (שמיוחס לו) את אשת בנו (שגם כן מיוחס לו). מניחין שכן ירצה (מסתמא מפני שיש שום רע בו). (וצ”ל שיש זכות זו לאב אף לאחר מיתתו.)
ב.כשיש  יותר טוב מייבום (קיו”ש), ירצה בו, ואז יותר.
ג.אם היא ערוה לו מטעם אחר, לא יבנה בית טוב. אז, לא רוצה בו אב.
ד. רוצה יותר שלא ישא האסור משישא המותר.
ה. רק יכול להתיר או לאסור כלם.
אז, ממילא, כשחד אשה ערוה, כל צרותיה יאסרו.
** ג:
ליתנינהו- לכאו’, זה גם כן קשה על סתם הגמ’, שלא רוצה למעט (כ”נ. ויש לדחות בקל.) אלא שנים. א”כ, קשה למה לא נ’ שאר במשנה. ואולי לא רצה למעטן מפני שהן פשוט, ולא מפני שסוברין שאין הדין כן.
במשנה תורה- ק”ק מה בין מ”ת ושאר קראי, שאי מוכח או מופנה, לעולם נדרש, ואי לא, אף במ”ת לא נדרש. (לא משמע שחוזר בו גמ’.) אולי רק ר”ל ששם נמצא כן בדר”כ (אז, נצטרך להניח שבמכשף וכדו’ אינו מוכח או מופנה. ולאידך צדדין, צ’ להמיח שהוא מופנה או מוכח, דאל”ה, מהי”ת לתלותו זמ”ת.) . גם י”ל שבייתור, לא נדרש, בדר”כ, סמוכין, אלא דרשה אחרת, אבל במ”ת (וצ”ב למה) דורשין סמוכין.
