* ג.
** לידי חיוב חטאת -
צריך ביאור למה לא אמר שמשנה מזכיר הוצאות שיש. הרי, יש רק שמונה הוצאות, ובאחד יש דין לזה ודין לזה. ותחשב. לאיזה סיבה לא אמר כן, אבל עדיין צריך ביאור איך מפרש את המשנה. נראה שצריך לומר שיש הוצאה לכל אחד מהם, וחלק שלו בהוצאה נקרא הוצאה שלו. ותחשב.
** מעשה -
נראה שהוא מה שיש סיבה לאסור אלא שנדחה (דהיינו שרבנן היו גוזרים אלא שחשו לצער), מה שאין כן כאן, שאין אף סיבה לגזור. ותחשב.
** פטורי דאתי -
אולי זה מפני שצריך להיות דומה לצרעת. ותו"ת.
* ג:
** מי קנסוה -
נראה שיש שני דרכים לבאר לשון זה. אולי מכוון לומר- מי קנסוה רבנן. למה יקנסו אותו? כדי שלא יחזרו אותו. איך יקנסו אותו? להיות דינו ככרמלית. גם אפשר שמכוון לומר- מי קנסו רבנן אותו להיות דין שלו ככרמלית, אף שעל ידי זה נמצא שיאסרו מלהחזיר אותו לו. ותו"ת.
** כאן למטה -
בכל כעין זה, צריך ביאור למה לא מבאר הבריי'. אולי רק היה ידוע להם חלק מן הבריי'; היה ידוע שיש בריי' שמדבר על ציור כזה ואומר מותר או אומר אסור. אז, אולי הבריי' באמת מדבר על ציור כזה. ויש לדון.
** דלא התירו -
קשה, שאולי רק כאן לא התירו כיון שאינו וודאי שיעבור, שאולי לא יפיל אותו. ותחשב.
* ד.
** קלוטה -
דנים אם נחשב מונח על הקרקע או באוויר. אבל, לא פשוט לי אם שנים אלו חלוקים. נראה שאפשר שאינו מונח על קרקע או באויר אלא ברשות, ושני המקומות הם שווים. ותחשב על זה.
* ד:
** הא עקירה בעיה -
לכאו', היה אפשר לומר להיפך, שאולי רק לא צריך עקירה, ולכן חייב הוא על הוצאה השנית שעשה. אולי יותר מסתבר לגמ' שיהיה כן. ותחשב.
** נופו בתר עקרו -
ואם תאמר אם כן נאמר שגם נזרוק את ידו בתר גופו. ויש לומר שגופו יכול לבוא לידו אבל עיקרו לא יכול לבוא למקום נופו.
* ה.
** הכא למטה -
אולי מחדש שכאן למטה מי' ואולי מחדש שזה מחלק (שהו"א שאף כאן ירדו מחיצות ויעשו אותו כרמלית). אבל, ע' בתוס', שאילו מכוון גמ' לומר כן, לא היה תוס' מקשה ככה, וגם לא נ' שגמ' אומר תי' של תוס', שיש חסרון גדול מן הספר.
** אחשביה -
ק"ק, אז, למה אמר ר"י דבריו הראשונים. וי"ל שאמר אותם קודם שאמר היותר מחודשים. וא"ת למה לא אמר רק היותר מחודשים ראשון. וי"ל שלא סבר שהיו נכונים אז. גם יש לומר שלא היה צורך להם בראשון (לא היה אותו חידוש נוגע). גם יש לומר שאמר דבריו האחרונים בביאור משנה. במילים אחרים, אם אמר דבריו לסיבה, כמו לת' לקושיה על משנה או כדו', אינו קשה שיכפל את עצמו, שאמר אותו פעם שניה לבאר שמשנה מתבאר על ידי זה. אבל, אם רק אמר איזה הלכה, אז קשה למה כפל אותו. אין צורך שיגרום שיגיד ככה חוץ מרצונו שנדע את הדין- אבל, זה קשה, כי כבר ידוע לנו הדין ממאמרו הראשון.
שוב ראיתי בתוס'. קצת צריך לחשוב למה לא אמר כמו שכתבנו.
** שני כוחות -
עיין בב"ק (כו:). ותחשב.
** והיכא איתמר -
נראה שכל זה חלק מן הקושיה שיבוא, והוא שאיפה אמר כן רבא, רק שם, אבל כאן לא נראה שזה מסתבר.
* ה:
** עבידי -
לשון זה קצת מעניין, שהיה לו לומר שרק יאמר כן גבי ספר, שכשהוא על כותל משופע הוא נח, אבל לא גבי מים, שעדיין הולך. נראה שמכוון לומר- ואל תדחה לי שאף במים אפשר שיונח שם, כמו אם יש איזה מקום באבן שהולך הוריזונטא"ל, שזה לא מצוי, ולא מסתבר להוקים אותו בציור כזה. לכן אומר לשון "עבידי." ותו"ת.
* ו.
** כרמלית -
יש לדון אם זה רשות מדאו' או מדרבנן. במילים אחרים, יש לדון אם מדאו' אין חילוק בינו לבין מקום פטור או שאף מדאו' יש חילוק ביניהם בלומדות. קצת נראה להוכיח שיש חילוק רשות מדאו', שהרי, אם לא, ימנה חילוק שבין חצר שערב לחצר שלא ערב. ויש לדון, שיש לומר ששם, כיון שרק תלוי בעירוב, לא מסתבר לקרא להם רשויות חלוקות, שמה שמחלק להם אינו קרק' החשוב לרשות. ותחשב.
אבל, ע' בגמ' לקמן (תחי' ז:), ששם משמע שהוא מדאו' מקום פטור, ואין חילוק ביניהם. ותחשב על זה.
** לא פסל -
דלאו היינו הנחתו- לשון רשי (שנוקט "דלאו היינו," ולא "ולאו היינו") קצת משמע שאומר שמה שאינו דבר אחד הוא מפני שנחשב צף, ולא שאומר שהצד שיהיו מונחים הוא שייחשבו שני דברים. אבל, אפשר שרשי רק מזכיר הדין, והוא שאומר שהוא כדבר אחר שצף על גב מים במה שלאו היינו הנחתו.
* ו:
** איידי -
קשה למה נקט זה, ולמה לא אמר שהו"א שרבנן רק אומרים שאסור להוציא מרשות הרבים לתוכו. ונראה שאם תעיין שם, מוכרח מן הקונטקסט נגד זה. ותו"ת.
* ז.
** רה"י קתני -
הפשטות הוא שכופל מה שהיה פשוט לגמ' לעיל, ואומר ר"א שאף על פי שיש קושיה על שיטתו, הרי יש לו הוכחה. נראה שאפשר לטעון שדוחה את הקושיה, שאומר שרשות היחיד קתני, ואז לא צריך לפרש שקרפיף הוא. במילים אחרים, קרפיף ובקעה עם מחיצות אותו דבר הוא; כיון שאמר רה"י, פשוט שבקעה עם מחיצות הוא, ואין צורך עוד לומר קרפף. ותחשב על זה.
** כרה"ר דמיא -
יש לדון אם יש משהוא בשינוי לשון זה. נראה שאולי לפי צד ראשון, קל ללכת בו עד שהוא רשות הרבים. לפי צד שני, זימנים שהולכים בו בני אדם, ואז נעשה חלק מרשות הרבים. אולי כיון שהוא כל כך דומה להם, דינו שווה לדין שלהם, או כיון שרבים ממשיכים ממנו לרשות הרבים ומרה"ר לו, נגרר אחריהם. ותחשב.
* ח.
** ורבים מכתפים -
משע שצריך שני דברים:
1. גבוה ט' הוא (שראוי הוא לכך).
2. רבים מכתפים עליו (לא רק ראוי הוא לכך, אלא שבפועל עושים כן).
יש לדון אם שניהם העיקרים או שאחד הוא העיקר. אפשר שהראשון הוא העיקר, ואם אין מכתפים עליו, יש הוכחה שאינו, באמת, ראוי. גם אפשר שהשני העיקר, ורק נקט ראשון כיון שאורחא דמילתא היא. גם אפשר שמה שהוא ראוי משנה את כיתוף שלהם, שצריך כיתוף רגיל של רבים. ותחשב.
ודע שאפשר לומר שאין ענין ראשון בכלל מפני שראוי, אלא אולי כדי להיות רשות הרבים, דבר צריך להיות חשוב, וצריך שיהיה ראוי שיהיה לו שם חשוב של רשות הרבים, ולא רק כרמלית ומקום פטור שבטל לרשויות אחרות. מזה, אולי, נראה שמסתבר למה סובר גמ' לדמות את זה לבור. לכאו', קשה למה נחשוב שכיון שט' של עמוד הוא ככה גם ט' של בור יהיה ככה. אולי ידע גמ' שכן הוא במציאות, אבל דחוק. יותר נראה לומר כמו שכתבנו, והוא שיש חשיבות אחרת במה שהוא ט', וזה חלק ממה שנותן לו שם של רשות הרבים.
ודע שדנו אם יותר מט' נחשב כט' או לא. לפי מה שכתבנו, צריך לומר שנחשב כט'. ותו"ת.
* ח:
לפי שאינה- היה נראה לומר שזה כסברת עולא, אבל באמת הפוך סברת עולא הוא, שחולקים אם לבאר דבר על פי מה שאינו רה"י או מה שאינו רה"ר. ויש לדון, שאולי לדברים חלוקים יש כלל חלוק. ותו"ת.
* ט:
** לגמר הדין -
ואם תאמר אם כן אינו מתחיל, אלא ממשיך, והרי אם התחיל יכול להמשיך. צריך לומר שלפעמים הם חוזרים לדין, והוא שדנו עד גמר שלו, ולאיזה סיבה לא גמרו, ועכשיו חוזרים וגומרים אותו. כיון שהפסיקו (ויש לדון מה בכלל הפסק), לא יכולים לגמור אותו. ותחשב.
** סמוך למנחה -
גמ' מפרש שדין ערבית אולי הוא קצת חלוק, ולכן, נראה, רק אמר דין של מנחה, ולא אמר דין של ערבית. (ויש לדון למה לא אמר שניהם.) אבל, צריך ביאור מהו הדין של שחרית. אם הוא שווה לדין של מנחה, קשה למה לא אמר אותו. אם אינו שווה לדין של מנחה, קשה למה לא. ויש להעיר שלא מצוי שיהיה שייך בשחרית. אז, אולי לא גזרו בו, או אף אם גזרו בו, לא אמר את דינו כאן.
* י.
** כיון דקביעה -
לשון זה קצת קשה, שלא רצה לומר שהוא יותר קבוע, אלא שהוא יותר קטן. בהשקפה ראשונה, היה נראה לומר שמכוון לומר את הדין עם הלשון של הגמ' בברכות, והוא ש"תפלת הערבית אין לה קבע." אבל, לא נראה כן, שהגמ' שם אומר שלשון זה בא לומר שתפלת ערבית רשות. הרי, עכשיו גמ' דן בצד שתפלת ערבית חובה, ואז לא מסתבר לומר שידבר במילים של המשנה שאומרים נגד זה. ותו"ת.
** טריחותא -
לכאו', לא מתרץ לקושיה זו. נראה לבאר שכיון שאומר שצריך להכין לתפלה, תי' לו, שלא רק נותן עליו את האבנט, אלא נותן עליו באופן נאה. אז, נתינתו טרחא. כמו כן, יש לומר שכיון שנתן אותו על עצמו ככה, נטילתו הוא, באמת, טורח. ותחשב.
* י:
** דמאיס -
נראה שאולי דיון של גמ' הוא מהו הצד שיאסר. אפשר להיות שיאסר כיון שיש בו פסול כיון שמצוי בו פסול, ואפשר להיות שיאסר מגזירה, והוא שאם נתיר אותו כשרק הזמין, גם נתיר אותו עם בנ"א שם. אם נאמר כצד ראשון, יש לחלק, שאם אחד יותר מאוס מחברו, אז אולי רק בו בלי מאוס ממש יש מאוס על ידי דמיונו למצבו המאוס. אבל, בשני, לא מסתבר לחלק, שבשניהם יהיה איסור דאו'. אז, בזה דן גמ', ומסיק שיש לחלק ביניהם במה שבית הכסא יותר מאוס, ואז אומר כצד ראשון. ותחשב.
** לעולם אל ישנה -
בלי גמ' זה, היה אפשר לומר ששנאו אותו רק מפני שהיה מוסר דברים רעים ליעקב.
* יב.
** מפני הכבוד -
יש לדון אם הבעיה הוא שמגלה שהיו לו כינים או שמעשה זה מיחס בדעת האדם מחשבה עליו למחשבה על כינים. ותחשב על זה.
* יג.
** אלא קורבה של גילוי עריות -
יש לדון אם חולק רק בנדה או גם באשת איש.
** משום לך לך -
הפשטות הוא שזה חלק ממאמר עולא, ומבאר למה אסור. אבל, אולי יש לומר שזה תי' של גמ' לומר שלא סותר את עצמו, אלא שרק אסור משום "לך לך," ולת"ח כעולא, לא צריכים הרחק זה.
** תפיליו -
איני יודע למה שייכים תפיליו. אולי זה מקור לבני אדם שבודקים תפילין לבאר בעיות בחיי בני אדם. (אינו ראיה שנכון הוא, אלא רק ראיה שהיו נוהגים ככה גם בימי אמוראים. ויש להעיר שלא הצליחו. אבל, זה רק מוכיח שלא כל רע כתוב בתפלין, אבל לא שמה שכתבו בתפילין לא קורה.)
* יג:
** אין שוטה -
נראה שרצה לומר שכיון שאנו כשוטים- לא טובים- ה' לא מראה לנו את הניסים שלו, וממילא אי אפשר לנו לחבב אותם.
** שוטה מת -
...
נראה שאולי יש חילוק בין משלים אלו. נראה ששוטה הוא על שם מש"א גמ' שאין אדם עובר עבירה אלא אם כן נכנס בו רוח שטות. אז, אומר שאנו בעלי עבירה. נראה שמת מכוון לומר שאין לבנו פתוחים לטוב. אז, אומר שאנו לא עושים (או לא רוצים) טוב. ותחשב.
* יד.
** משקים טמאים -
זה רק גזי' לגזי', שאין משקים טמאים מדאו'. (וע' בפסחים, שזה דיון.) וצריך להגדיר.
** ופסיל להו -
מעניין שרק חושש במה שהוא פוסל, ולא במה שמסתמא אוכל אתהתרומה הפסולה. אולי נקט האיסור הראשון. דע שמגמ' לא היה מוכרח להקשות, שיש לדחוק שכוונתו לומר שיפסול אותו וכיון שממילא יאכל אותו, עובר, אבל לא אפשר לומר כן ברש"י.
** פסיל ליה -
צריך לומר שנגיעה בתוך פיו אינו נחשב טומאת בית הסתרים. אפשר לומר שמה שנשאר בפיו אינו נטמא (ולכן אין החשש לאכילה), והבעיה הוא רק שהדרך הוא שלא לאכול או לשתות כולו כאחד, ויש מה שנוגע בפיו בחוץ, וזה נטמא. ותחשב.
* יד:
** משקים הבאים מחמת שרץ -
זה מחלקת בפסחים.
** גזור ברישא -
צריך ביאור, שגזרו ידים בו ביום וגם גזרו ספר בו ביום, ואז צריך לומר שגזרו ידים הבאים מחמת ספר בו ביום. אם כן, קשה למה לא מונה אותו. יש לומר שלא מונה אותו כיון שלא נוגע עוד, אחרי שכבר גזרו על ידים. אבל, עיין בתוס' ד"ה כיון דהך, שאינו כן. גי"ל שהוא חלק מגזי' ספר. ותחשב. מעניין, שמונים ידים ומשקים הבאים מחמת ידים להיות שני דברים
** גזרו טומאה על הידים -
קצת צריך ביאור למה מזכיר אותו כיון שגזרתם לא עמד.
* טו:
** אבר -
מעניין שעדיין דיני חציצה שלו תלוליים במה שהוא זכוכית. נראה שזה מפני שזה מציאות, שתלוי כמה מים נכנס וכמה מקפידים בני אדם. ותחשב.
* טז.
** כי היכי דלא לגזור -
יש לדון למה אין אומרים שכבר יש הוכחה ממה שלא גזרו בו טומאה ישנה. אולי דין זה לא נודע כל כך. גם יש לומר שגזרו על כלי זכוכית קודם שגזרו על טומאה ישנה. לא נראה כן, ששב"ש גזר על טומאה ישנה, והיה קודם שמונים שנה..
* טז:
** אף בנות -
לכאו', אין הוכחה לומר שזה גזרו או זה גזרו. אז, היה אפשר לו לנקוט איזה גזירה שרוצה ולומר שרבי יוסי סובר שאותו גזי' נגזרה באותו היום. צריך לומר שיש לו איזה קבלה שכן סובר רבי יוסי.
** גדר מי חטאת -
יש לדון מה לנו בזה, שיבטלו. אולי חוששים שלפעמים יהיו בני אדם צריכים ולא ידעו למצוא.
** גדר מי חטאת -
קשה, שעדיין יהיה נודע, כיון שבני אדם מטהרים בו. י"ל שחושבים שרק מטהר אדם. אבל, אז קשה מש"כ בדיבור הקודם. אולי אינו כל כך מצוי שבני אדם יהיו טמאים (שיכול לשמור על עצמו). ותחשב.
* יז.
** אם תקנטני -
רצה לומר, אם תמשך להקשות, נחוש שיזכרו רבנן את הקושיה ולא יזכרו את התירוץ, ואז אצטרך גם לגזור בו. ויש לדון, שיהיה גזי' לגזי'.
* נד:
** עשיתו ילתא -
לא נקט מר עוקבא כיון שזה לא שייך למר עוקבא, שמר עוקבא לא היה אשה, ואין זה שייך אצלו.
** כל שאפשר -
צריך ביאור למה מונה כל הציורים האלו- מי שיכול לשמור את משפחתו מעבירה, את עירו מעבירה, וכדומה. לכאו’, ענין של כולם שווה- שאדם נתפס על מה שהיה יכול למנוע- ופשוט שאין חילוק בין משפחה ועיר וכל העולם. ויש לדון, שהואלי הוה אמינא שאין כל כך צורך למנוע חטא של כל העולם, שיש הרבה בני אדם אחרים, וכל אחד מהם יכול למנוע קצת החטא. אז, מה שלא מנע אינו כל כך סיבה, שיש סיבות רבות עמו. ותו"ת.
* נה.
** רב יהודה -
השקלא וטריא קצת קשה לדעת, ואז אני אבאר אותו בתוך מילים של הגמ’. למטה, אבאר המקורות שלי:
“רב יהודה הוה יתיב קמיה דשמואל. אתאי ההיא איתא קא צווחא קמיה [דשמואל],[fn:1] ולא הוה [שמואל][fn:2] משגח בה. אמר ליה [רב יהודה לשמואל][fn:3] לא סבר ליה מר “אוטם אזנו...”? אמר ליה [שמואל לרב יהודה][fn:4] שיננא רישך [אני, רבך] בקרירי [אני יושב בתוך מים קרים, שאין אני מתחייב בזה], רישא דרשיך [הרב של רבי שלך] בחמימי [יושב במים חמים, שהוא המתחייב]. [כוונת תשובתו היה שלא היה יכול לעשות לה כלום, אלא רבו, ריש גלותא, היה יכול למנוע את הרע. אז, רק הריש גלותא היה ה”אוטם אזנו.”]
** אף על גב -
רצה לומר, היה לך לחוש שלא, באמת, אתה מחליט בטוב שהם לא ישמעו. אבל, באמת, אם לפניו גלוי וידוע שלא ישמעו (ויש לדון אם זה אפשר במציאות) אין עליו חיוב להוכיח אותם, כמו שמבואר מגמ’ לקמן.
** מדה טובה -
מעניין שזה נקרא מדה טובה, שלכאו’ הוא רק מה שאין מדה רעה. ותחשב. לא קשה לומר שגם זה נקרא מדה טובה, אבל נראה למתק קצת לומר שלא היה גזירה רק על מקצת בני אדם, ואז המדה טובה היה מה שאין גזי’ עליהם, אלא המדה טובה היה השמירה מן המיתה. וצריך לחשוב על זה.
** כדי -
כיון שאומר את זה לשני הדרכים, צריך ביאור מה יקרה אם לא רושם עליהם כלום. נראה שלא יהיו שמורים ולא יהיו פתוחים להיזק. אז, אולי יזוקו. (הדוגמא יהיה לבני אדם שהולכים לים. מי שלובש לייפגק”ט לא ימות. מי שחברו דוחף אותו לים, ולא מרשה לו לעלות, ימות. מה אם אחרים? אולי יחיו, ואולי ימותו. ותו"ת.
** מאלף עד תיו -
ק"ק, שלא שמרו את כולו, כמו שאומר גמ’, שלא היו מונעים את אחרים מלעשות עבירות. ותחשב על זה.
** סוף חותמו -
נמצא שיכולים לחתום בסוף חתימה. וצריך לע’ בגמ’ בב”ב, בפרק האחרון, לדון אם זה אמת. ותו"ת.
** יסורים בלי עוון -
קשה, שיש יסורים של אהבה. צריך לע’ בברכות אם יש עבירה שם; עיין בשי”ח ש"י על ברכות על הנייר, בגלג ששי, ששם בארנו שאולי זה מחלקת צדדים בגמ’ בברכות. ויש להעיר שאחד שנוקט כאן- צרעת- אולי אינו יסוכים של אהבה; עיין שם בתחילת ברכות.
* נה:
** משה -
קשה ל"ל פשוט שחטא, שמפורש בקרא כן, ומפורש שלכן מת. נראה שסבר שכן גזר עליו, אבל שב. אבל, עדיין היה צריך למות. דחוק מאד, שאז מה שייך גזירה שימות לעבירה כלל, שבין כך ובין כך היה מת, ואז קהש למה ה’ עושה שהוא העונש. וצריך לחשוב על זה ולדון.
** עדיין צריכים -
צריך ביאור למה צריכים לו. כמו כן, צריך ביאור מה הוא לשון עדיין. ממשע שאף שיש לנו דרשה אחרת, צריכים לדרשה שלו. אז, משמע שמודה לדרוש כאחרים, ואף על פי כן, גם דורש כמודעי. יש לדון למה. ותחשב.
** חטאו -
פשוט שחטאו באופן אחר, אלא רצה לומר שחטאו במה שמפרש בו תורה. באמת, מצאנו שלפעמים חטאים יותר גדולים נקראים סתם “חטא.” יותר מכך, נראה לומר שחטא גדול קשה לשוב ממנו. אז, אומר שאי אפשר שבהכרח יש להם חטא. אילו היה החטא מה שמשמע מן הקרא, אז יש להניח כן, כיון שקשה לשוב. אבל, כיון שלא באמת חטאו מזה, מסתבר ששבו. ותחשב על זה.
** מתוך ששהו -
משמע שחלק חשוב מאיסור אשת איש הוא מה שאוסר אותה לבעלה. אבל, דע שאף בלי זה- כמו אם מאנס אותה- עדיין הוא אסור ועדיין הוא מחייב מיתה.
** בעטיו של נחש -
משמע שכל עבירה ראוי למות עליו. ותו"ת. (ודע שהיה אפשר לומר, כדי לת’ ק’ תורה, שהכל חטאו, אלא אלו חטאו באופן שלא חייבו מיתה.)
* נו.
** כדי להרבות -
נראה שאולי חשבו שלא ילכו סופריהם עמהם, ויצטרכו למצוא סופר בכל מקום שילכו. כיון שלא יהיו שם לזמן רב, לא יבואו שכר גדול לאותם סופרים, ויהיה קל למצוא אותם. ותחשב על זה.
* נו:
** מה ראשונים -
צריך לע’ בגמ’ בתחי’ חולין (“מקום הניחו לו”), ולדון למה שם דן בקרא אחר, ולמה שם נותן ביאור אחרת. ותחשב על זה.
* Footnotes
[fn:1] כן יבואר לקמן מן הדיבור, שיבואר שרב יהודה הוא ששאל לשמואל למה לא ענה לו.
[fn:2] פשוט שזה שמואל, כמו שכבר בארנו שהיתה מדברת לשמואל.
[fn:3] כן מבאר משני דברים. ראשון, מה שקרא לו “מר” משמע שהיה תלמיד שלו; ר”י היה תלמיד של שמואל, אבל שמואל לא היה תלמיד של ר”י. שני, מה שהמשיב קרא למי שמשיב לו- שהוא המדבר כאן- בשם “שיננא” מוכיח שמי שמדבר כאן הוא רב יהודה, שקרא שיננא בכמה מקומות.
[fn:4] מוכרח שזה שמואל, שכבר בארנו שרב יהודה הוא המקשה לו.
