* ב:
** הא דומיה -
לא מכוון רשי לומר שיש חולקים לפרש במשנה שאינם לחיוב, שיש אותו קושיה. אלא, רשי בא לפרש למה לא מביאים מהם ראיה, ומפרש שלא מביאים מהם ראיה כיון שבלי ראיה זו שמביא גמ', אף דין שלהם לא נודע. אז, רוצה להיא את הראיה העיקרית. ותו"ת.
** וקמפרש -
עיין בק' תוס'. נראה שיש לומר שאילו לא היה מיד, היה אפשר לומר שהלשון לאו דווקא, ומדבר על ההוצאות (אולי מפני שבמק"א אומר שנים שהם ארבע על הוצאות). אבל, אילו לא היה דווקא, והיה רק אגב הוצאה, לא היה מזכיר אותו ראשון. ותחשב על זה.
* ג.
** פטורי דאתו -
כגון- לשון זה מוזר, שהוא זה, ואינו כגון זה.
** עקירת גופו -
מן הבית- לכאו', עקירה אינו מן הבית, אלא ממקומו. לכן, אם לא היה נח בבית, והוציא אותו, אינו עובר. נראה שרשי מפרש שהעקירה הוא מן הבית. זאת אומרת, כיון שהוא מונח, מקומו הוא הבית. אז, עקירתו הוא מן הבית. ותחשב. אז, לשון רשי לא מכוון על יציאתו מן הפתח, אלא מפרש איך מגדירים מקום החפץ. (ויש להוסיף שאולי כל המלאכה הוא המשך אחד של הוצאתו מן הבית.)
* ד.
** לכשתיכול -
עיין בפשט שני של רשי. נראה שהכוונה היא שלא אוכלים אדם מלח מהר (שטובלים בו ומתבלים בו).
* ה:
** שמן שצף על גב יין -
היה אפשר לדבר בשמן שצף על גב מים שנאכל על טהרת תרומה.
* ח.
** גבוה י' -
לכאו' מרשי יוצא שכשאומרים שלא דק, לא רק מכוון לומר שלא דקדק בלשונו לומר הדין האמיתי, אלא מכוון לומר שלא דקו רבנן בדין שלהם, אלא החמירו עליו. ודע שאינו צריך להיות שלא רצו לטרוח לדקדק, אלא אולי הוא כדי לגזור, שבני אדם לא מבחינים באותו חילוק קטן שבו לא דקו.
** רחבה ו -
משמע שכרמלית אינה רשות לעצמה מדאו'. ע' במה שדנינו בזה על גמ'. ויש לדחוק שכמו שמקום פטור אינו רשות לעצמה, כך זה אינו רשות לעצמה, והוא שאולי רשות שאין בו איסורים לא נחשב רשות לענין זה. ויש לדון, שהיה אפשר לחלק שמק"פ אינו רשות כיון שבטל. אז, היה צריך לומר שגם כרמלית בטל. קשה למצוא, אז, חילוק בלומדות בין שניהם לומר שהם רשויות חלוקות. צ"ל שסיבה שהם בטלים חלוק, וזה מחלק אותם לשני רשויות. ותחשב על זה.
* ט:
** מפסיקים -
ובגמ' מפרש- נראה שמכוון למה שאומר גמ' גבי ק"ש של ערבית, שאותו חשש לא יחייב אותו להפסיק אםלא נאמר שמפסיק כשבוודאי יפסד ק"ש. ותו"ת.
ויש להעיר שכיון שכן, נמצא שההפסק לקריאת שמע צריך להיות הפסק קרוב לזמן קריאת שמע, ולא הפסק כשבלי זה לא יקרא קריאת שמע. ותו"ת.
* י.
** הכון -
בדרך כלל אומרים לשון זה כשאדם עושה מצווה עם חפץ, שאז צריך להתנאות את החפץ. לכאו', נמצא מזה שכשעושה מצווה בלי חפץ אחר, צריך להתנאות את עצמו. ויש לדון, שאולי אף שרשי אומר לשון דומה, אולי לא באמת מכוון לומר שהוא מחמת אותו דין.
* י:
** צריך להודיע -
עיין ברשי, שנראה שיש שני דינים חלוקים לגמרי כאן. צריך ביאור איך יש מקור לשניהם. (כמו כן, כיון שנראה שהם חלוקים, קשה למה כולל אותם בתוך דיבור אחד.)
* יא.
** לא יאכל הזב -
קצת צריך ביאור איך זה שייך לשאר הציורים שבמשנה, חוץ ממה שהוא גזי' והם גזי' (ואין לומר שמחמת זה נכלל, שהרי יש הרבה גזי' שהיה להם להיות הובא אגב ולהביא אגב).
* יא:
** וכן בגת -
יש לדון אם אף שם חוששים שמא יוציא או מפני שדרכו להוציא לא נקרא עראי עוד.
** רבי יהודה -
היה אפשר לתרץ כן גם למשנה שלנו, אלא שסתם משנה רבי מאיר.
* יב.
** מי אלימא -
צריך ביאור מהו הצד שהוא אלים מן המשנה. אולי סובר שלשון בריי' ולשון משנה חלוק או אולי סובר שלשון "אין" ולשון "לא" חלוק. ותחשב.
** ש"מ -
צריך ביאור מהו הראיה, שאולי גמ' מכוון לומר כר"א, ומשנה אומר דין אחר שלא הוזכר במשנה. נראה שלא רוצה להוקים את המשנה כר"א, שבדרך כלל אין הלכה כרבי אליעזר (יש לדון, שבמשניות אלו, הוקבע הל' כב"ש, ואז אולי מה שהוא שמותי אינו בעיה). אז, עיקר שאלת הגמ' הוא אם מוכרח להיות כרבי אליעזר או לא. כיון שמצאנו משנה שאומר דין שיכולים לומר בתוך המשנה ולעשות שאין המשנה ר"א, מפרשים את המשנה כן.
[אגב, ע' באוצר מדרשים הנקרא בית המדרש, בצוואת נפתלי לבניו. שם, מזכיר נפתלי חלום אחד, שבו יעקב אמר לכל בניו לקחת אחד ממאורות. לוי לקח את השמש, יהודה לקח את הלבנה..., ורק יוסף לא לקח כלום. יעקב רחם על יוסף, ונתן לו שור. השור היה קופף, והגיע ללבנה, ושם קבל דברים מיהודה. הוא משל על מה שבן יוסף יקח מלוכה מבן יהודה. אבל, נראה לי שאולי החלום הזה או המדרש הזה הוא מקור לפיוט של בנים של "הקא"ו ג'ומפ"ד אובר ד'י מו"ן."]
** מקטע -
בשבת- יש לדון מהי"ת, שאולי רק מחדש השיו עושים כן בחו"ל. נראה שמסתבר שאמוראים אלו עשו כסתם משנה.
** מתירים -
עיין במה שמביא רש"י מגמ' לקמן. יש לדון אם הענין הוא מה שאין מינים מולידים או איך נולד.
** מתירים -
ידוע הקושיה, והוא שפסטו"ר הוכיח שאין ספונטיו"ס ג'נארישי"ן. יש הרבה תשובות שנאמרו, אבל נראה לומר שכשאנו מדברים על מי ההורים של זה, לא חשוב מי נתן את הג'נטי"ק מאטיריא"ל, אלא מה שחשוב הוא מי גרם את זה. אז, פשוט שכל דבר נגרם מהורים ומאויר ואוכל וכדומה. אם מה שעושה ההורים ניכר, אז הוא חשוב, ונחשב סיבה חשובה. אבל, אם אינו ניכר, לא נחשב סיבה חשובה. ותחשב על זה (תחשב למה מה שהוא ניכר שייך להחשיב אותו לסיבה חשובה).
* יב:
** שבנא איש ירושלים -
נראה שזה גם הפי' של "איש יהודי היה בשושן הבירה." ויש לדון, שאולי זה רק כשאומר "איש ירושלים" וכדומה על שמו. ויש לדחות כל זה לומר שרש"י לא מפרש "איש ירושלים," אלא מפרש ששמו היה שבנא, ולא שבנא איש ירושלים, אלא היה איש שגר בירושלים. רש"י קורא לו אדם גדול כיון שהיה אדם גדול. דחוק, שלא יזכיר כן רש"י.
* יג:
** מגילת תענית -
יש לדון למה כתבו אותו, ולמה הוא יותר חשוב שיזכרו אותו משאר בריי' ומשניות. היה נראה לומר שאינו תורה- אינו דינים- אלא הוא מציאות. במילים אחרים, יש דין אחד, והוא שאין להתענות בימי שמחה. זה רק מגלה מתי הם ימי שמחה. אבל, צריך להגדיר את זה, שיש הרבה דברים שהם כזה. למשל, נגיד שאסור להוציא חפץ חשוב, ואז נוכל לכתוב חלקים גדולים של מסכת שבת. ותחשב.
** האוכל -
יש לדון אם שאר דברים הנמנים כאן צריכים הערב שמש.
* טו.
** כי קאמר -
רבותיהם- בא לבאר למה לא מתרצים על ידי זה הוכחת הגמ' שלא תקנו הלל ושמאי. ותו"ת. (וקשה, שעדיין שם לבסוף הודו. ויש לומר שזה רק אחרי שעשו מנין. ותחשב.)
* נה.
** היום יוודע -
עיין בביאור רש"י בדרשה זו. קצת קשה, שזה קאי על מה שיוודע שה’ הוא האלקים, וזה לא שייך ליחס שלנו לאבות. לולי רש"י, יש לומר שדורש (וצריך ביאור למה) ש”היום” קאי על “אלקי אברהם....,” לומר שאחרי היום, מה שהוא אלקי אברהם לא שייך לנו. אולי ההוכחה לזה יהיה שלא רק היום יוודע, אלא נס הוא ויוכיח לדורות. ותחשב על זה.
* נה:
** ארבע -
ע’ בתוס’. נראה שגם יש לומר שאין צדיק שלא חטא. כל אלו שלא חטאו לא עשו הרבה מצוות, ולא היו, כל כך צדיקים. ויש לדון.
** וש"מ יש -
עיין בק’ תוס’. נראה שכון שנדחה אחד, ורואים שכיון שנגזר שבני אדם ימות, אין צריכים עבירה, כיון שכל בנ”א שווים, כן הוא גבי יסורים. ויש לדון, שיש הרבה יסורים חלוקים, ואין מה שמייסר זה מייסר זה תמיד. ותו"ת.
** והא כ’ -
שם החכם- מבין אני שמכוון רש"י להקשות על דיון הגמ’, אבל איני מבין מה אומר “שם החכם....”
