* ב:
** שנה לשני מלכים -
לגמ' יש הו"א שאין מונים שנה אחת לשני מלכים. יש לדון, אז, מה נעשה. נראה שיש שלש דרכים. הראשון הוא שמונים לראשון, השני הוא שמונים לאיזה שמלך ליותר זמן[fn:1], והשלישי הוא שמונים לאיזה שהוא מלך בשעת כתיבה. עיי ברש"י שכתב כצד ראשון.
** מנין -
רצה לומר: מונים מניסן כיון שזהו דרך בני אדם, כיון שרבנן הנהיגו כן. שואל מהו המקור לרבנן לתקן כן, ומשיב שרבנן מצאו שהתורה מונה כן, ואז אף הם מונים כן.
** לגזרה שווה -
קשה, שאין דורשים גזרה שווה מדעתינו. צריך לומר שמחממת דמיון של הלימודים, מסתבר שאם זה נלמד, בתוך אותו הל"מ, זה נכלל גם כן. זה נראה מחודש. עיין ברש"י, שנראה שסובר שהוא מפני שהגזירה שווה באה מן ה"שנה" שבפסוק. אבל, לשון גמ' לא משמע כן כל כך.
* ד.
** והשתא בקיצותא -
לכאו’, אין איסור לתת צדקה בקיצותא. אלא, לכאו’, רואים מזה שירד מצדקתו. כמו שירד מצדקתו לענין זה, קל לומר שירד יותר, ולא נחשב מלך כשר. גם יש לומר שלמלך לתת בקיצותא זה בעיה, שיש לו כל מה שירצה.
* ה:
** מעמך -
עיין ברש"י. רש"י מחדש כאן גזירה שווה (מבאר שגמ’ מחדש כאן גזרה שווה).
* ו.
** קיימי עניים -
לכאו’, רצה לומר שיעבור מיד, שיש יכולת לתת להם מיד. קשה, שאם כן יעבור רגל ראשון. אלא, צריך לומר או שלא כל כך קל להביא אותו פעם ראשון (שמא ישכח) או שצריך לעבור במצב שקל לו לתת שלש פעמים. אז, דין עני יצטרך להיות ככה גם כן. ותחשב. ודע שלפי מד"א שצריך להיות סוכות ראשון, לא מסתבר שענין שלש רגלים הוא שאז כבר קל לו להביא אותו, שאין הסדר שייך לזה. ותחשב.
* ו:
** והבאתם שמה והא מיחייב -
רצה לומר, הוא המביא אותו, ואז הוא בכלל אותו ציווי.
* ז.
** רוב אביב -
עיין ברש"י שפירש שרוב תבואות מתבכרות בו. גם אפשר שהוא שרוב זמן הביכור קורה בו (אולי הרוב הוא בזמן, ולא בפירות). גם אפשר שאולי הוא שרוב החודש הוא אביב, ולא שרוב אביב הוא בחדש. ותחשב על זה.
** אין מעברים -
עיין בטעם שנותן רש"י. זה מעניין. רש"י כאן מדבר על מה שלא לומר שמעובר, ולא על שלא לעבר. אבל, קודם ר"ה לכאו’ אי אפשר לעבר. אז, יש לדון אם אף כשצריכים לעבר קודם ר"ה, עדיין טוב שלא יגידו. ותחשב.
* ז:
** לא ימסרם -
לכאו’, בכל זמן צריך אדם למסור אותם לציבור. אולי אם חושב שהוא "לשקלים,” זה נחשב מסירה טובה, אף אם לא חושב עליו כל כך, אבל בדברים אחרים צריך לחשוב יותר פרטי. גם יש לומר שיותר קל לו למסור אותו לציבור כשיודע שצריך. ותחשב.
** אמר רבא -
עיין ברש"י, שכ’ בפירוש שרבי ממש סובר כן. עיין ברא"ש בהוריות ושבועות שלא כ’ כן.
* ח.
** כבית שמאי -
יש להעיר שרבי עקיבא אולי היה מסופק מי אמר מה. אבל, תנא זה גם מזכיר מי אמר מה, ואז לא נראה לומר שמהפך כאן.
* ח:
** אלא אם כן קידשו -
יש לדון אם זה הולך למפרע או רק נכנסים אחרי קידוש בית דין. ותחשב.
** מתקדשת -
רש"י כ’ שיש הו"א שימשך עד יום הכיפורים. לכאו’, רצה לומר שידוע שגמר שלו הוא סוף השנה, כמו שהוא בכל דיני שנה. אבל, כמו שקדושה בא לאט, אולי גומר לאט. עדיין מניחים שתחילת גמירתו הוא בסוף השנה, ולא סוף גמירות אז. ותחשב.
** ורבנן -
מגמרא זה יוצא שיש כמה מחלוקתים שתלויים זה בזה.
* יא.
** שנולדו -
עיין בפשט שני של רש"י. לכאו’, רש"י סובר, אז, שלא נולדו בחודש ניסן, אלא בניסן של תקופה. זה מחודש. צד זה, צריך ביאור מהי"ת שנולדו בניסן, ולא באייר ממש. ותחשב.
* יא:
** רבי יהושע -
עיין בביאור רש"י. יש לציין לגמ’ בפסחים, במחלוקת בין חכמי ישראל לחמי אומות העולם בענין מה קבוע ומה מתגלגל.
* יב:
** אין בה אלא מעשר אחד -
איני מבין איך קורא לו כן, שיש לו שנים, כמו בכל שנה. אולי כיון שלווים בכלל מעשר ראשון, יש שנוטלים כל מעשר. דחוק.
** הלך אחר לשון -
יש להעיר שיש דברים במשנה שלנו (כמו שטר) שגם תלוי בלשון בני אדם, אלא שרבנן תקנו דבר שיגרום לשון בני אדם. ותחשב.
* יג.
** מחרת הפסח -
קשה, שמותר אף אם לא הקריב את העומר.
* טז.
** תרי דינא -
קצת קשה למה לא באר שהדין הוא על כל החיטים שהוא שם באותו הזמן. אז, בין אם נזרע קודם, בין אם לא נרע קודם, כל מה שקורה אחר פסח נידון בפסח. ותחשב.
** עיוני -
כיון שאין זה מקור לו, כמו שאומר הגמ’, קשה למה מזכיר אותו.
* יח.
** על אלול מפני -
עיין במה שכתב רש"י. קשה, שנוהגים שני ימים קודש (אלא אם כן כבר נודע בראשון שקדשו אותו). אף אם לא היה רוב, אלא רק ספק, היו חייבים לעשות כן. צריך לומר שרש"י מזכיר את זה לרווחא דמילתא.
* יח:
** הוכפלו -
קשה, שגם בשבעה עשר בתמוז הוכפלו. צריך לומר שלא הוכפלו צרות שכל אחד ראוי בפני עצמו לתקן עליהם תענית. שו"ר בתוס’. איני מבין תי’ שני שלו, שלא משמע כן, ממה שמזכיר גם מה שנחרשה העיר. אפשר לדחות שגם זה דומה, שהוא חורבן בני ישראל ועיר ישראל, ולא רק בית המקדש. במילים אחרים, אולי יש יחס בין בית המקדש לירושלים. ותחשב. אף בלי זה, יש לומר שהביא את כל המשנה, אגב שני הדברים הראשונים שנזכרים שם. צריך לעיין אם, באמת, הביא את כל המשנה. ותחשב.
** גזירת מלכות -
יש לדון אם הענין הוא שיש, אז, שני סיבות לצום – גזירת המלכות, והצום – או שאז הרעות של היום יותר רעות, שב=לולי החורבן, לא היתה גזירות המלכות, ואז בשעה שאנו דואגים על גזירת מלכות, מרגישים את צרת הצום יותר. ותחשב.
** ששקולה -
שתשעה באב יותר חמור רק מפני שהוכפלו בו צרות, ולא מפני שהצרה שלה היתה צרה יותר גדולה.
* יט.
** בעי חיזוק -
מעניין שדרבנן שמחייב לעשות חיוב דאורייתא צריך חיזוק. אולי זה לא צריך חיזוק, אבל כיון שחיוב דרבנן הוא, עשו לא פלוג, לתת לו אותו הדין של חיזוק. אבל, עדיין מחודש שיוסיפו יום זה כדי לעשות נפקא מינא בימים שלפניו ושלאחריו, שאין צורך לימים אלו חוץ מלתת חיזוק, והרי יום זה לא צריך חיזוק, שבין כך ובין כך ישמרו אותו. אפשר שבדר"כ הסיבה הוא לתת חיזוק, אב כאן יש סיבה אחרת, והוא להבחין שיש בו צורך דרבנן, ואינו רק יום שמחה של הנביאים. ותחשב.
* יט:
** על ניסן -
יוצא, לכאו’, שדיון הגמרא כאן (אם מוסיפים חדש או לא) הוא באדר שני, ולא באדר ראשון.
* כא:
** על ניסן -
איני מבין למה לאלו צריך להמתין עד ששומעים שבית דין אומרים, “מקודש.”
* Footnotes
[fn:1] יש לדון מה יקרה אם מלך הראשון לחדש, והתחיל השני, אם מניחים שימלוך ליותר מחודש.
