** (ב:)
גמרא אומר
שבכל זמן שמצאנו שני מנינים של שנים שהם שווים, אומר ר“פ לדרוש ג“ש מזה לזה, לומר שהם מנויים מזמן אחד.[fn:1]
כתיב, ”וישמע הכנעני מלך ערד.“ כנעני זה היה סיחון. נמצא, אז, שלש שמות לו:
1. כנעני.
2. ערד.
3. סיחון.
חולקים מה היה שמו האמיתי:
1. שמו היה ערד. נקרא כנעני על שם מלכותו (מלך על בני כנען), וסיחון[fn:2] כיון שהיה דומה לסיח (עייר בן סוס) שבמדבר[fn:3].
2. שמו היה סיחון. נקרא כנעני על שם מלכותו (נמלך על בני כנען), וערד כיון שהיה דומה לערוד[fn:4] (חמור הבר) שבמדבר. (ג.)
כי משמש בארבע לשונות:
1. אם. זה כולל ג“כ ”כאשר,“ ו"אשר.“
2. דילמא
3. דהא
4. אלא (ג.)
היה מלך אחד שהיה לו שלש שמות: כורש (על שם שהיה מלך כשר), דריוש (כך היה שמו), וארתחשתא (על שם מלכותו[fn:5]).
היה מלך כשר, אבל החמיץ. יש ? ראיות שהחמיץ[fn:6]:
1. שלח ממון לכהנים כדי שיתפללו לו. כשגוי עושה כן, מניחים שרק נותן ע“מ כן, ויטען על ה’ אם לא מהני.
2. נתן עץ לכתלי בהמ“ק באופן שיהיה קל לישרף, כדי שלא ימרדו בנ“י.
3. אומר קרא שהיה מלכה שלו (למשכב) כלב. דן גמ’ אם מוכרח כן מקרא או שהיה קבלה שכן אומר הקרא.
4. אחר שכבר אמר שיתן בלי קצבה, החליט ליתן עם קצבה.[fn:7] גמ’ דוחה שכך רצה לתת מתחילה, אלא שלא ידע מתחילה כמה יהיה נצרך. (ד.)
חייב אדם להקריב שלמי חגיגה[fn:8] בכל אחד מן השלש רגלים. בפסח, יכול להקריב אותו לשבע ימים[fn:9] (שיש שבע ימים בפסח). בסוכות, יכול להקריב אותו לשמנה ימים (ואף ששמיני עצרת הוא, למקצת דברים, יו“ט אחר, לרוב דברים הוא אותו יו“ט). בעצרת, יכול להקריב אותו לשבע ימים. יש שני מקורות לזה:
1. מונה את כל שלש הרגלים. יש שלומדים מזה שיעור שהייה שבו עובר על לא תאחר. יש שלא לומדים כן, אלא דורשים מזה היקש ללמד שאף בעצרת, כמו בפסח, יכול להקריב שלמים לשבע ימים.(לא לומ’ מסוכות כיון ש“תפסת מועט תפסת“) (סוכה נכ’ להטעין לו לינה בליל של חול המועד, כמו בפסח, שבו כ’, ”ופנית בבקר.“)
2. כמו שבר“ח מונים ימים ומקדשים יום אחד לחדש, כך בשבועות מונים שבועות ומקדשים שבוע. (ד:, ה.)
רב פפיס (ת“ח שהיה בזמן רבי יהושע בן חנניה) העיד על שלמים שהיה הוקרב בפסח, וולדה היה הוקרב בחג. (החידוש הוא שולד שלמים הוקרב לשלמים.) מקשה גמ’ שעובר בעשה (”ובאת שמה“) אם לא מקריב קרבנו ברגל אחד שעבר. אז, יש שני קושות:
1. ל"ל הקריבו אותו בפסח. לזה, יש לומר:
  1. היה מחוסר זמן[fn:10], שהיה בתוך שמנה ימים ללידתו, שעדיין פסול הוא.
  2. היה חולה.[fn:11]
2. ל"ל הקריבו אותו בעצרת:
  1. היה חולה.
  2. הקריבו אותו בעצרת. עצרת יכול להיקרות ”חג,“ כיון שהוא חג העצרת, אף שבדר“כ לשון חג נאמר על סוכות. (ו)
מזכיר גמרא כמה דינים בענין חילופי קרבן:
חילופי[fn:12] חטאת מת. זה הלכה למשה מסיני (תמורה).
חילופי עולה ושלמים נחשבים (כעולה וכשלמים).
** (ה:)
חילופי תודה נקרב בלי לחם. אז. אם הבהמה שהוחלף (שנעשה תודה מח’ החילוף), נתערב בתודה[fn:13], אם שניהם קיימים, יביא שניהם ביחד עם לחם של אחד, ויתנה שיהיה של תודה. אם מת אחד מהם, לא יכול להקריב את הנשאר, שהתודה צריכה לחם, והחילוף לא צריך לחם (והלחם יהיה חולים בעזרה).
** (ו:)
גמ’ מזכיר מחלקת בין רבי זירא ואביי. אשה לא חייבת בראיה ברגל. אבל, חייבת בשמחה ברגל. אביי מניח שר“ז סובר שאשה צריכה לעלות כדי לקיים מצוות שמחה. אבל, אביי סובר שלא צריכה לעלות, שיכולה לקיים אותו על ידי מה שבעלה (או איש אחר) ישמח אותה.[fn:14]
** (ו:)
בכור תם נקרב לקרבן. אבל, יש חילוק גדול בינו לבין כל קרבן אחר. בדרך כלל, קרבן מרצה (הוא כפרה או דורון[fn:15]). אבל, בכור לא מרצה.[fn:16]
ר"ה של נטיעות הוא יום ראשון של תשרי. אם הוא נטוע לזמן חשוב לפני זה (עיין לקמן, שנבאר בס“ד איזה זמן בשנה נחשב שנה), אז בביאת אותו זמן, נחשב בר שנה. כדי להיות נטוע, צריך להיות שהשריש[fn:17]. חולקים תנאים מתי קורה השרשה[fn:18]. יש בזה שלש שיטות:
1. רבי אליעזר (יש שלא גורסים ר"א; ועיין בגליון) סובר שזרע משריש שלשים יום אחר שנותן אותו בקרקע.
2. רבי יוסי ורבי שמעון סוברים שזרע משריש שני שבועות אחר שנותן אותו בקרקע. כן פוסק רב. (יבמות סוף פרק הערל)
3. רבי יהודה סובר שזרע משריש שלשה ימים אחר שנותן אותו בקרקע. כן פוסק שמואל. (יבמות סוף פרק הערל)
** (י:)
יום אחרון של ימים אלו יכול להיכנס בחשבון של זמן שצריך להיות נטוע בתוך שנה כדי להיחשב שנה.[fn:19]
לפעמים, יכול להיות שפחות מיום ייחשב שנה.
1. במלכים (גמ’ אומר כן במלכי ישראל, אבל לא נראה לחלק), יום אחד, בתחילת שנה או בסוף שנה, נחשב שנה. (ב:) לא מצאנו מח’ בזה, אבל יל“ד (כיון שיש מח’ בד“א, ולא מבאר גמ’ שזה חלוק).
2. בשכירת בית (אם אדם שוכר בית ”לשנה זה“), אין שנה פחות מחדש, שלא משכיר איש לזמן פחות מחדש. אין חולק על זה. (ז:)
3. בדברים אחרים[fn:20], חולקים ר"מ ורב אלעזר אם יום אחד בשנה חשוב שנה או חדש אחד בשנה חשוב שנה. מחלקת זה הוא בין בתחילת המנין (סוף השנה) ובין בסוף המנין (תחלת השנה).
4. כתיב, ”ויהי באחת ושש מאות שנה בראשון באחד לחדש.“ רבי מאיר סובר שנמצא שאחר יום אחד נקרא שש מאות ואחת שנה, רואים שיום אחד בשנה חשוב שנה.[fn:21] ר“א מפרש שלא מכוון לומר שהיה שנת שש מאות ואחת, שהיה לו לומר אותו באותו סדר. אלא אומר שהוא באחת- דהיינו בתחילת[fn:22] השנה שש מאות. כיון שכ’, ”באחד בחדש,“ רואים שיום אחד בחדש נחשב חדש.[fn:23] כיון שיום אחד לחדש הוא כחדש, חדש אחד לשנה נחשב שנה, שזהו מנויים שלה. גמ’ מפרש שאותו חדש הוא חדש של שלשים יום. לא מפרש למה הוא כן, ולא של כט.[fn:24]
* Footnotes
[fn:1] ויש להעיר שרב פפא אמר כן בציור אחד. גמ’ למד ממנו לומר כן בכל מקום. אבל, הצורך לגמ’ לומר כן נדחה, ואז אין הכרח שנדרש לכל זמן, ואולי רק למקום אחד שאומר ר“פ.
[fn:2] לכאו’, הענין הוא שהוא בהמה שהוא חזק ופרוע.
[fn:3] איני יודע מה לומדים מ“במדבר.“ אולי הוא יותר פרוע שם.
[fn:4] לכאו’, אף הוא חזק ופרוע.
[fn:5] לכאו’, ר"ל שמלך על בני ארתחשת.
[fn:6] קצת קשה ל"ל הזכיר ראיה ממה שמונים לו כמלך שהחמיץ. אפשר שזה מגלה ששינה שום קרק’ שלו, אבל לא פשוט לגמ’ שזהו הקרק’ שיהיה שינוי שלו משה איך נמנה לו שנים.
[fn:7] לכאו’, אין זה בפני עצמו חימוץ, אלא כמו שלא היה כל כך טוב בזה, קל לומר שהחמיץ ולא היה טוב כלל. ותו"ת.
[fn:8] יש שלש קרבנות שחייב להביא: עולת ראייה, שלמי חגיגה, ושלמי שמחה (לכאו’, אין חיוב להקריב את אלו, אלא לשמוח, אבל אין שמחה אלא ע“י שלמים). כאן, רק דנים בשלמי חגיגה. בדין של שאר, עיין בתוספתא בפרק ראשון בחגיגה, ועיין בתוס’ בחגיגה (ו:).
[fn:9] בכל זמן שאומרים שיכולים להקריב אותו ליותר מיום אחד, צריכים לזכור שחלקו אמוראים אם עיקר החיוב הוא ביום ראשון, וכל יום הוא תשלומים לו, או כל יום הוא תשלומים ליום שלפניו. אם כן, לכאו’, יש חיוב לכל יום. (ויש לדון אם אף יש חיוב ליום אחרון.)
[fn:10] כמו כן, אפשר שימיו גמרו כשהיה אמו נשחטה, ולא יכול להיות נשחט בואתו יום שנשחטה אמו.
[fn:11] גמ’ לא אומר כן בפירוש לתרץ לזה, אבל יכול לומר כן. דרך של גמ’ הוא כאן הוא, ”בשלמא פסח, י“ל כת’ ראשון, אבל עצרת קשה.“ מתרץ את זה לק’ עצרת, וכיון שתירץ זה, קל לתרץ את זה ג“כ לפסח (אלא שכמובן מוזר שיחלה שני פעמים. אבל, עדיין קל לת’ כן לתירוץ שני לקושיית עצרת.)
[fn:12] חילוף ר"ל תמורה. אומר לשון חילוף כיון שבריי’ שמובא בגמ’ אומר לשון חילוף. איני יודע ל"ל משתמש בלשון תמורה, כמו שגמרא בתמורה אומר.
[fn:13] ואף בתודה ראשונה, שהרי הוקרב, כמו בכל תמורה.
[fn:14] לכאו’, יקנה דברים לה, ואותם דברים ישמח אותה.
[fn:15] כן אומר רש"י, אבל תוס’ אומר שכדי לרצות צריך להיות כפרה. מציין לגמ’ בזבחים שאומר שעולה מכפר על חייבי עשה. (צריך לומר שמניח ששלמים מכפר גם כן על עבירות קלות. עיין ברש"י בערכין (כא.), ועיין בש“מ שם. לכאו’, קצת נ’ כן כאן, שלכן לא פי’ רש"י כתוס’. ויל“ד, שאולי רק סבר שאין סיבה לחשוב שהרצאה יותר משמע כפרה מדורון. ונ’ שהוכחה של תוס’ היתה שסובר שבכור דורון, שאם לא כן, למה מקריב אותו. ותחשב.)
[fn:16] יש לדחות את זה בשני דרכים:אולי גמ’ רק מבאר דינים של בכור בעל מום, שלא הוקרב. אבל, אולי בכור תם מרצה.אולי זה רק בהו“א שרק בו דורשים שיכול להיות נקרב אחר שאיחר אותו. אז, מבאר גמ’ שאפשר שהוא חלוק משאר קרבנות שאינו בר הרצאה. אבל, כיון שדין זה נלמד בכל הקרבנות, אין סיבה לחשוב שאין בכור בר הרצאה.
[fn:17] כן יוצא מגמ’ (ט:), אבל עיין ברש"י שם שקורא לו הוספה מחול על הקודש. אז, לכאו’, יוצא שההוספה היא שצריך שיהיה הושרש, ולא שיהיה נטוע. (עיין בלשון ירושלמי בנוגע דין תוספת שביעית. היה אפשר לומר שהגדר של הדין הוא שלא ישנה כל כך בביאת שמיטה, שאז הוא זרע של שמיטה, ונמצא שזרע לפני שביעית זרע של שביעית. אולי לכן צריך השרשה קודם לכן. ותחשב.)
[fn:18] יש להעיר שלשון הבריי’ קצת משמע שהוא סוף זמן השרשה, שאחר כן, לא קורה השרשה. אבל, אולי אינו זמן ראשון של השרשה. איני יודע, אז, למה אין דינו ספק קודם כן. ותחשב.
[fn:19] כן אומר גמ’ כאן, אבל יש להעיר שלשון של רבה בר אבוה הוא שצריכים שלש ושלשים יום וכדומה. לזה, צריך לומר שלא ר"ל שצריך 33 ימים, אלא שצריך 3 ימים וצריך עמו 30 ימים, ומחמת שיום אחד עולה לכאן ולכאן, נמצא שהוא 32 ימים. ותו"ת.
[fn:20] מצאנו אותו לענין נטיעות, ומצאנו אותו לענין קרבנות. אז, הנחתי שהוא בכל שאר דברים. ויש לדון.
[fn:21] לא מבאר איך יודעים שלא היה יום אחד שנכנס לשנת שש מאות ושנים. אולי מקראי מוכרח נגד זה. ושו“ר בתוס’.
[fn:22] לכאו’, ר"ל ביום אחת בתוך. אבל, קשה אז למה צריך איזה יום היה.
[fn:23] לא הבנתי כל כך איך רואים כן, שרק אומר שהיה יום אחד לחדש.
[fn:24] אגב, יש להעיר שכיון שגמ’ אומר שמה שסתם הלוואה הוא לשלשים יום הוא מחמת ששלשים יום בשנה חשוב שנה, לרבי מאיר יהיה סתם הלואה ליום אחד. אולי יש אומדנא נגד זה. אבל, אז נמצא שלר“מ אין מקור לשום זמן. אז, יש לדון מה יהיה הדין אליביה. ויש לדון בזה, שאולי ”שלשים יום בשנה חשוב שנה“ שאומר הוא כמו ענין שני שכתבנו כאן. ותו"ת. אז, אף ר“מ מודה לו.ודע שצריך ביאור מהי“ת לרבי מאיר ללומר כדין שלשי. אולי הוא אומדנא, שאז רוצים בני אדם, ואז הוא טוב להם. אולי זהו מה שעושה שנחשב שנה, או אולי מה שהוא יום אחד עושה שנחשב שנה, אלא אף צריכים שאומדנא אומר שרוצים כן. גם אפשר שרבי מאיר סובר כשני הדרשות (שיום אחד כאן נקרא שנה, ויום אחד גם נקרא חדש), ונוקט איזה מהם שהוא יותר מסתבר מן האומדנא. ותחשב.
