* עה:
** בינונים -
נמצא שלפמעים הוא יותר טוב למות מלחיטות. כמו כן אומר גמרא שמיתה טוב לרשעים. (יש לדון אם מיתה היה טוב כאן כיון שהיו רשעים, ומסתמא יחטאו עוד, או כיון שהיו בצער.)
** רב חסדא -
יש לעשות כאן קצת חשבון. רב חסדא מת קודם שמת רבא. רבא חי עד ארבעים ורב חסדא חי עד תשעים ושנים, במועד קטן. אז, רבא היה נולד כשהיה רב חסדא, לכל הפחות, חמישים ושנים. הרי, בת רב חסדא נשא את רבא. יודעים שבחרה ברבא, שהיתה כבר תלמיד של רב חסדא, כשהיתה קטנה, בבבא בתרא. אז, מוכרח שהיה יותר גדול ממנה (שלכאו' לא היה קטן אז). נמצא שהוליד ר"ח כשהיה יותר מחמישים ושנים. זה לא קשה, אבל זה מעניין.
* עו.
** במדה טובה -
יש לדון למה לא אומרים שהוא פי אלפיים (כמו שאומרים במכות), ואז כאן יהיה הרבה יותר מן מזה. ותחשב על זה.
* עו:
** דאמרי -
לשון גמ' משמע שקאי על "משמחתו." אז, אומר שגורם לו שמחה כיון שעושה אותו פקח.
* עח.
** ולית הל' -
יש לדון אם להל' אין שיעור או יש שיעור פחות מזה. נראה כראשון, שלשני קצת קשה למה לא יפרש את השיעור. אבל, אפשר לומר שלא ידע, אלא רק יודע מה אינו- אינו על פי צוואר שלו.
** זקן -
סנהדרין- עיין לעיל שאומר שאברהם וכדו' היו זקנים וישבו בישיבה. שם, בוודאי לא מכוון לומר שהיו יושבים בישיבה של סנהדרין; אז, קצת קשה למה רש"י חושב שזו הכוונה כאן.
* עט.
** בגרעינתה -
יוצא, אז, שעם גרעין שלה הוא שיעור כפול מבלי גרעין שלה.
* עט:
** אכילת -
ואם תאמר אולי היה עראי כיון שכל אכילת פירות עראי. ויש לומר שלא היה צריך להזכיר את זה. אלא, מוכרח שהיה שיעור שהיה עראי גם בשאר מאכלים.
** שיעורו
- עיין במה שכ' רש"י. לכאו', זה מתאים עם מה שיוצא מרש"י בפסחים על זה, שמשמע (כמו שכתבנו) שכל איסור של בל יראה ובל ימצא הוא גזירה מחמת אכילתו. אז, מובן למה אי אפשר שהשיעור שלו יותר חמור משיעור אכילה.
* פ.
** ביצה -
יש להעיר שבשבת יש כמעט אותו הו"א ומס' כגמ' כאן (גבי איזה ביצה היא הכי קטנה).
** שב מידיעתו -
צריך לומר שלא חושבים שבית דין של זמנו טעה, אלא שהשיעור ממש נשתנה, שאם לא כן, נאמר שמחייב, על כל פנים לפי השיטה שטועה מחמת בית דין חייב.
** שיעורים של עונשים -
יש לדון בזה, שמשמע שהוא רק בשיעורין של עונשים, ולא בשאר שיעורים. ותחשב אם יש שיעורים שלא שייכים לעונשים.
* פא.
** הקיאם -
גם בחולין, נראה לי, רבי יוחנן מדבר במי שאוכל דבר שמקיא.
** אכל ושתה -
הכרתי שלא פשוט אם יתחיייב כלל אם אכילה אחרי אכילה (ואולי אף קשה למה יתחייב על שתיה אחרי אכילה), כיון שכבר מיושב דעתו. ותחשב.
* פב.
** עוברה -
לכאו', זה להציל את העובר. יש לדון מהיכי תיתי לדחות כדי להציל את העובר, שרוב מקורות שיתן גמ' הם לפיקוח נפש. אבל, הוא אינו נפש כשאר נפשות, ודוחים אותו מפני נפש אמו. ותחשב.
* פד:
** פרוש -
צריך לחשוב על תי' זה.
* פה.
** ספק ספיקא -
נמצא שאין הולכים בפיקוח נפש אחרי ספק ספיקא. אם ס"ס הוא משום רוב, זה הולך טוב עם מש"א גמ' לעיל, שלא הולכים בפ"נ בתר רוב.
** הסדר -
אולי יש לגרוס "הסבר," שמצאנו רב אחר שנקרא "סבר."
** לוי הסדר
- יש לדון אם רש"י דן מי הוא או רש"י דן מהו "סדר." (יש לדון אם יכולים לכתוב, "מי הוא," בלי היו"ד, כמו שכתוב, כמו שיכולים לכתוב "מה הוא." ותחשב.)
* פה:
** אין אחר -
אז, קשה למה מזכיר יוה"כ, שמכפר עם התשובה. ותחשב.
* פו.
** בעלתי -
עין במה שבאר רש"י. נמצא שלשון "בעלתי" יכול להיות לשון קנין, ולא לשון ביאה. אולי זה רק כשאומר "בכם," ולא "אתכם."
** יסורים -
זה לא מוכיח ש"יראה" רצה לומר יראת רוממות, שאולי יש חילוק בין יראת עונשים שיבואו לעונשים שכבר באו. יש לדון, שייסורים שכבר באו לא גורמים תשובה אלא מפני יראה שיותר יבואו. יש לדון בזה. ראשון, אף אם הוא כן, יש חילוק, שיותר קל להיות ירא כשכבר באו מקצת. שני, יש לדון בזה, שואלי הוא גם מראה לו שה' גרם כל זאת, ואינו רק שגורם לו להיות ירא. ותחשב.
* פו:
** ושניה -
נראה שהוא מחמת מש"א גמ' במק"א, שכיון שניצול אדם פעמיים, ה' עוזר לו שלא יעבור. ותחשב.
* פז.
** לא טוב לו -
יש לציין למשנה בסנהדרין ששקט לרשעים רע להם ורע לעולם. (ודע שיכול להיות שני סיבות- מה שיכולים לעשות יותר רע, ומה שלא נפרע מהם בחייהם).
** אין חטא -
העבירה- רצה לומר, רק עבירה הנוגע לדבר שבו זיכה את הרבים. ויש לדון.
** אחטא ואשוב -
מגמ' משמע שמה שאומר שישוב לא נוגע; הענין הוא שמי שעבר פעמיים לא יכול לשוב. (זה מתאים עם מש"א גמ' שצריך שיבוא מעשה כזה ולא יעבור.)
* פח.
** איזה מסכתא
גומר ב"סימן טוב"? רק יומא ברש"י ד"ה עוונותיו.
