* ב.
** בעלמא -
יש לדון מה אומר:
1. לא נדע שבדרך כלל, אין ראיה קונה. אז, זה מלמד לנו דין. לא משמע כן מלשון גמרא.
2. אף שמוסיף כאן מילים, עושה שבמקומות אחרים יכולים לגרוע מילים, ששם יכולים לומר ”מצאתיה,“ ונדע מהו הדין. יש לדון איך נוכיח שם מכאן:
  1. מכאן רואים שצריך קנין, ולא די בראייה.
  2. מכאן רואים ש“מצאתיה“ אומר שבא לידו.
** ראייה -
יש לדון אם ההוה אמינא הוא שיקנה מדאורייתא (מסתמא, מפני שראייה גופא הוא יחס או מפני שאז הוא קצת עומד לקחת אותו), או מפני תיקון דרבנן (כעין תקנת ד"א).
** ראייה -
חושב אני שיש דיון ברש"י ותוס‛ בב“ק (קרוב לדף ל) בענין קנין בהבטה מהפקר. צריך ביאור איך יפרשו גמרא זה. אולי יסברו שכל זה הוה אמינא. גם יש לומר שיש חילוק בין ראייה להבטה. ותחשב.
* ב:
** בהדי הדדי -
מעניין שכל אחד קונה כלל, ולא אומרים שאין אחד עושה מעשה קנין עליו כיון שחלק ממנו נגבה על ידי חברו. שוב ראיתי שגמרא לקמן (ז.) משמע שמביא ראיה מזה שזה די לקנין. וצריך ביאור למה אינו כחציו על גב עמוד ומגביה חציו השני, שחושב אני שאומר גמרא שלא קונה. ותחשב.
שוב ראיתי בגמרא ח.. וצריך לבאר איך כל הגמרות יתפרשו. ותחשב.
** דליכא למימר הכי -
קשה, שעדיין יכול להיות שמשקר, ועדיין נשביע אותו. ונראה שר"ל שאז אולי לא יהיה כל כך מפחד משבועה, ויותר קשה להניח שרק ישבע על האמת.
* ג.
** רבה -
צריך ביאור, שלכאורה, הענין הוא שיש סיבה להאמין אותו אם לא מודה במקצת. קשה, שבעדים, אז, נאמר שאין הוכחה, שעדים אומרים שהוא מעיז פניו.
** את הימנתיה -
ק"ק ל"ל אמר כן גם כן בשנים שהפקידו, שבעל הבית הוא שהאמין לאותו אחר. ויש לדון, שאולי ידע עליו גם מי שנתן מאתים. וע“ש.
* ג:
** ומה פיו -
קשה, שפיו מחייב אותו קרבן כיון שהוא כל כך נאמן, ומחייב אותו שבועה כיון שאינו כל כך נאמן. ותחשב.
** קל וחומר -
יש לדון ל"ל אומרים מה לפיו שיש לו סברת רבא. אולי כל זה אכניס. ותחשב.
* ד.
** והילך -
קשה למה א"א אותו דיחוי שאומרים לעיל, והוא שכאן יש לו עדים על מה שכפר, ואז לא ישבע. ואם תאמר שמתורץ על פי מה שאמר ש“כעין דאו‛,“ אקשה לך ל"ל אמרו כן גבי דין ראשון של ר“ח.
** הוחזק כפרן -
יש לדון למה אין זה חוטא נשכר.
** צריך באור
למה נקטת דבר נחשב אנן סהדי שהוא שלו, או שהוא נותן אותו.
* ד:
** איערומי -
לכאורה, זה גלגל החוזר.
* ה.
** דחפר -
על פי זה יש לתרץ גם כן קושיית גמרא לעיל, שכלים דומיא דקרקע אינו הילך.
** קרקע -
גם היה אפשר לומר שצריך קרא למעט עבד (שהזיק, ואז אינו הילך).
* ה:
** בפקדון -
יל"ד ל"ל אומרים שמסתמא אכל אותו כיון שישלם לאחר זמן, ואז נמצא שהורה לעצמו היתר, ועכשיו מורה היתר שישלם לאחר זמן. ותחשב.
* ז.
** כרכשא -
לכאורה, אז, אין שום אחד מוחזק, ואין ”אנן סהדי“ ו“הילך“ של לעיל.
* ח.
** מגו דזכי -
ק"ק למה מניחים שמזכה לחברו, כיון שאומר שחברו גזלן. באמת, לכאורה, עדיין חידוש הוא שיכול להיות מעשה קנין, שאם הבעיה הוא המעשה, שצריך שהוא הסיבה היחידית לקנין, אולי מה שחברו מגביה לו אינו מהני. ויש לדון, שאולי אז דברים שיקנו לו הם סיבה היחידי. ותחשב
* ח:
** במקום מנהיג -
נמצא שמניח שאולי יש קנין עליו אף אם אינו הגורם שילך, אלא הוא אחוז בו כשהולך. שוב הבנתי שגמרא חושב שיותר מסתבר שרכוב בלי מנהיג קני, אלא אין הוכחה לדין זה, שהיה הוכחה רק אם היינו אומרים שספק של שמואל הוא על זה, אבל עכשיו הוכחנו שאין ספק של שמואל על זה.
** מנהיג ותפס -
יש לדון מהו הקמ“ל:
1. אין מי שיש לו שני קנינים עדיף.
2. אין לו יותר, שאינו מנהיג באופן כל כך טוב.
** המהיג -
מעניין לפשוט מזה, שלכאורה, שם תלוי רק במי שמוליך אותו (שהוא הגורם האיסור להיעשות), אבל כאן יכול, לכאורה, להיות תלוי במי אוחז בו.
* ט.
** מה שתפוס -
מעניין שנחשב לעשות מעשה קנין על זה, שלא היה נופל כולו בלי מעשיו, שהרי הוא מחובר לחמור. גם יש להעיר שמעניין שיכול אדם לעשות מעשה קנין על חצי חפץ ולקנותו.
* ט:
** קלת -
מה שחצר מהלכת שייך בכליו של לוקח לכאורה אומר שכלים קונים מדין חצר. כן נראה, שאין מקור אחר לרבותם. ותחשב, שיש לומר שאותו ריבוי של חצר מרבה אותם, ואולי הם מסיבה אחרת. ותחשב.
** מגו -
יש להעיר (ורש"י, באמת, קצת מבאר זה) ש“מגו“ זה אינו כמה שאמר רבא לעיל, ששם צריך לזכות בו ממש, וכאן הוא רק שיכול לזכות בו. ותו"ת.
* י.
** תופס לבעל חוב -
נראה שהענין הוא שיש לאדם זכות לעשות דבר לחברו כיון שאין רע שיוצא ממנו. זה אומר שה‛ ברא את העולם ביכולת לעשות חלות לאחר כיון שרק טוב, ולא רע, יבוא ממנו. אם כן, כיון שבא רע ממנו, לא יכול לעשותו, וממילא לא חל.
** נזיקין -
לא אמר שם המסכתא כיון שכל נזקין חדא מסכתא הוא, כמו שאומר גמרא.
* יג.
** בשלמא לר“א -
קשה ל"ל אומרים לאביי שחוששים שכתב אבל לא נתן, שאז לא הקנה. ויש לומר שכיון שמודה לא חוששים לזה (אם לא לקנוניא, כמו שאומר). אם כן, א“צ לחוש לפרעון וקנוניא, אלא אף ללא נתן וקנניא. ותחשב.
* יד:
** גזלן -
יש להעיר שהחשש הוא שבני אדם לא ירצו לקנות כיון שיכול לטרוף מהם שאולי מכר בגזילה. יש להעיר שאם נעשה שלא מצוי שימכור, אותו חשש יתמעט. ותו"ת.
** מה מכר -
מעניין שהוא פשוט לגמרא שמכירה של דבר הנגנג חוזר, שיש לומר שקנה כל זכות שיבוא לידו, ויש טוב בזה, שאולי יקנה אותו המוכר. ויש לדון, שרק קונה אותו כדי שזה לא יחסר, ואם קנה כדי שאולי יקנה אותו, הרי סבר וקבל, ולא יקה. ותחשב.
* טז:
** והאלהים -
משמע שמה שאמר רבא הוא אף לרבנן. זה מחודש. אין לומר שרבא רק פוסק כר“מ איפה שהוא מסתבר לו, שאם אפשר לעשות כן, נאמר שאף רב עושה כן. ותחשב.
* יח:
** שוירי -
צריך ביאור מה רואים מכאן, שאולי כאן שאני, שיודעים שאין שנים בעיר זה שיש להם אותו שם (ולא מניחים שהוא מאחר עם אותו שם עיר, שלחוש לעיר עם אותו שם  ואחר עם אותו שם), כמו שפרש רש"י. ונראה שלא מביאים ראיה מן הציור, אלא מראיה שהביא רבה.
* כא.
** כל שיש בו שינוי -
יש לדון למה אמר כן ר"י במשנה זה, ולא במשנה שאומר דין של מה שחייב להכריז (ולמה לא הפך לשונו לומר מה שאינו חייב להכריז כאן).
** יש להעיר
שלכאורה, מצוות השבת אבידה הוא קצת גלגל החוזר, שאילו לא היה מצווה להחזיר אבדה, היו בני אדם מיאשים, אף אם היו להם סימנים (אם לא שנאמר שיחשבו שבני אדם יעשו לפנים משורת הדין. ועדיין יש לדון אם יהיה לפנים משורת הדין להחזיר אותו.). אז, רק מפני מצוות ה‛ יש סיבה למצווה.
* כא:
** מהשתא הוא דמיאש -
נראה שאפשר לבאר שלרבא יאוש חל למפרע, והוא שבזמן שמיאש, כיון שלא רק חושב שעכשיו אבד ממון, אלא שלפני כן, באיבוד חפץ אבד ממון (שאין הסיבה מה שלא הוחזר לו, שזה כבר היה עומד לעשות מאז), יאושו חל מאותו שעה שאבד את החפץ. ותחשב.
* כב.
** כלך אצל יפות -
יש לדון ל"ל מניחים שזה קפידה, והיה רוצה שילך אצל יפות, ואז לא עושה אותו שליח.
** מצוה הוא -
יש לדון, שאף כאן מצווה של הכנסת אורחים וכבוד תלמידי חכמים יש. ותחשב.
* כב:
** וכי מאחר -
לכאורה, הוא אמר, ”אבי,“ אבל גמרא אומר רבא, כמוש מצאנו שישנה לומר שם כיון שהוא יותר קל (כמו שאומר בב"ב שרב יאמר שדבר הוא כעין מש"א רב יוסף), ועוד שבגמ‛ קדושין מבאר שרק הבן עצמו לא יאמר שם אביו. ע"ש.
גם אפשר ששם רבא היה שם של כבוד, ולא רק שמו הרגיל.
** העשוי -
ש לדון אם סובר שמניחים שלא יידרס או שממה שלא נדרס, צריך לומר שיש דבר שעושה שלא נדרס, ואולי זה הניח. גם יש לומר שממה שהניח בו סימן, רואים שחשב שלא יהיה נדרס. א"כ, הוא רק בשנתן בו סימן, ולא ביש בו סימן.
** מקום -
יש לדון ל"ל יהיה סימן:
1. לא יודע הבעל ששכחו שם.
2. חושב הבעל שיכול להיות כמה דברים שם.
3. חושש הבעל שמקומה נשנה.
** סימן הבא מאיליו -
יש לדון ל"ל יהיה סימן:
1. אולי ענין סימן הוא שגילה שלא מיאש, אלא שחושב שיקח אותו בסימנו. כאן, אין סימן זה.
2. אולי חושבים שלא יודע באותו סימן.[fn:1]
יהיו נפק"מ אם פשוט שהכיר בו. ותו"ת.
- יש לדון איזה דברים יהיו סימנים (על מה יקבעו שדבר סימן):
1. לכאורה, ייתלה רק במה מניח סתם בעל, אם מניח שיהיה יכול למצוא אותו, שאז לא מיאש, או לא, שאז מיאש. גם תלוי במה מניח בדעת המוצא.
2. אפשר שרבנן קבעו דינים על פי מה שסוברים שיכול למצוא בעל. רצו שיקיים מצוות מציאה, ואז קבעו כן. אחר שקבעו אותם דינים, והם ידועים, לא ייאש. ותחשב. יש לדון למה רצו שיחזר.
* כד.
** בתי מדרשים -
מעניין שימצאו מקומות כאלו שהם רובם עכו“ם.
* כד:
** ופליג עליה בחדא -
היה אפשר לומר שכן הוא הדין אף בשל ישראל, אבל מחדש דין יין נסך והיתר קנקן.
* כה.
** בכובא -
יש לציין לכעין זה בב"ב גבי הגבהה ומשיכה לקנין (פה).
** מגדלאה -
שמעתי אומרים שנקרא כן מפני סוגיה זה, אבל ראיתי רש"י שאומר בפירוש שהיה שם מקומו מגדל. לא הייתי יכול למצוא רש"י זה.
** מאי מכריז -
לכאורה, זה קשה לכולי עלמא, שהרי חולקים רק מה נחשב הינוח, אבל אי אפשר להכריז איך הונח, שכל המניחים אותו כן מניחים אותו. ותו"ת.
** נראה שאפשר
שענין שלש מלכים אינו רק שכל דבר שאינו כזה מצוי לעשות כשנופל, שלכאורה, אם הקטן הוא בתחתון, יותר קשה ליפול כך[fn:2], אלא שיש ראיה אז שלא הניח אותם, שזה הדרך הכי טוב להניח מטבעות, ואז רק כן יניח אותם.
* כה:
** כאבני בית קוליס -
ר"ל שאז צריך לתת דבר תחת שנים כדי להגביה את כולם. ותו"ת.
** מאיניש -
צריך ביאור למה מינחים שהיה שלו כלל, שהיה אפשר לדעת שיש בעולם נירונית בלי זה. ותו"ת.
* כז.
** בחנות -
צריך ביאור למה מניחים שאם הוא מציאה שנפל משולחני שלא מיאש. נראה שאולי שולחני או חנווני, שהוא, לזמן רב, שם, ידע שמציאתו שם, ולכן לא מיאש עליו. ותחשב.
* כז:
** לאהדורי -
ואם תאמר הרי בית דין יכולים להפקיע קידושין. ויש לומר שאין הענין כאן שאי אפשר, אלא שלא רצו, שרק במציאה יש סיבה שיבאר לקמן.
* כח.
** דאיכא -
ואם תאמר אין זה משיב על ראיה שאמר רבא. ונראה שאולי בא לומר שיש ראיה נגדו, שאי אפשר לשמוע דין סימנים מכאן, ואז רואים שאין מקור מן התורה. ותחשב.
* כח:
** לאו פרסי אנן -
צריך ביאור למה אומר לשון רבים.
** מאי לא אמר -
נראה שהיה יכול לתרץ שאומר לו, ”אולי מצאת את אבידתי, שהיה… ומזכיר אבידה, ולא סימן.“ נראה שזה לא מצוי.
* כט:
** בחדש -
יש לדון למה יש חילוק:
1. אחד צריך זה יותר.
2. זה עושה רע לאחד.
ותו"ת.
** למימרא דניעור -
לכאורה, היה יכול לתרץ שקצת ניעור מעלי לה, ומאד קשה לה.
* ל.
** פסולה -
קצת יש לדון מה מנסה ללמוד מכאן. לכאורה, הוא שאם יש דעת אחד שהוא רע ואחד שהוא טוב, הולכים אחר הרע. יש לדון, ששני הרעות הם חלוקים. ותחשב.
** היה כהן -
כיון שאינו נלמד, יש לדון למה מז‛. ונראה שהוא גם כן חלק מן המשמעות, אף שאינו נצרך. ונראה שבא לחדש שאף שהוא חלק מן המשמעות, עדיין יכול הקרא ללמד, ולא אומרים שבא לאלו, שהקרא מיותר.
* ל:
** בן גילו -
כיון שבא לו רע, נראה שאולי מסתבר לאחר לבוא כדי שיטול פחות(כמו שמבאר גמרא בנדרים, שהוא כמו עשרייתא דבי רבי).
** אם יש שם ב"ד -
לכאורה, הענין הוא שאם שכרו הוא פחות מדמי אבידה, אז זכאי בשכרו. אם לא, לא זכאי, שיכול היה לטעון שלא נהנה מביטול שכרו. ואם תאמר הרי נכון הוא שלא נהנה, ולמה ישלם לו. וי"ל שמיירי כשיודע שירצה בו הבעל, כמו אם הוא heirloom. ותחשב.
** אטו -
גמרא חשב ששואל מהו אבידה, ומקשה שכל ציורים אלו היו אבידות. אז, מפרש שמקשה מהו כלל של אבידה, ואיך נדע אם דבר הוא אבידה.
* לא.
** צערא דידה -
קשה, שאינו כן בטעינה, לכאורה. ואולי ר"ל שיש לחוש שיהיה לה צער, שאולי אם לא יציל אותו, ייתן אחר אותו על גבו באופן שיצער אותו.
* לא:
** אבל הני תרתי -
יל"ד ל"ל אמר רק אבידה ואחד מהני.
* לב.
** אם יש שם ב"ד -
עיין בגיטין (לג), שלא פשוט שב"ד הוא שלוש. ותחשב.
** הואיל והוקש -
ואם תאמר הרי בלאו ועשה יש גם כן כבוד מקום עם הלאו ועשה. ונראה שאולי הלאו ועשה יש בו רק כבוד מקום, אבל זה יש בו כבוד מקום כיון שהוא מצווה, ויש בו גם כן כבוד אביו ואמו. גם יש לומר שאין כל מצווה נחשב כבוד המקום.
* לג.
** רבצן -
לכאורה, אז נמצא שא"א לעמוד בו. ותחשב.
** חכם -
יש לדון מה לנו בזה, שרבי עדיין הביאו לחיי עולם הבא…. ונראה שאם האב חכם, אי אפשר שלא למדו כלום. ותחשב.
* לג:
** כדדרש -
קדם לרבי; וצריך לומר שאף שדרשו אז, לא ידעו בנ"א שבזמנו.
* לח:
** רב ששת -
נמצא שהיה ר"ש מנהרדעא.
** דקא כליא -
היה אפשר לומר שרק כאן, שאין חוששים שמא יפסיד אותו על ידי התקנה, כמו שאומר רב, מתקנים. ותו"ת.
* לט.
** אפוטרפא לדוקנני -
לכאורה, זה לא מתרץ כלום, שלא הוסיף כלום, ששאל למה לא מורידים לו אפיטרופוס, ואמר כלל שאומר שאין מורידים לו אפיטרופוס. ונראה שהוסיף כיון שאמר הפרט בו שעושה אותו דין. ותחשב על זה.
ונראה שאולי אומר לא שלא רוצים או שהדין הוא שאין מורידים, אלא שבמציאות, לא עושים כן, שאי אפשר לעשות כן. ותחשב. וזהו מובן על פי מש"פ רש"י שיותר קשה לעשות אפיטרופוס לגדולים.
* מא.
** יש להעיר
שמוזר שגזילה קונה במשיכה לפי רבי יוחנן שמשיכה הוא קנין מדרבנן. ותחשב. אולי רק סובר שמשיכה וממון הוא מדאו‛, ומדאו‛, אין צריכים משיכה. ותחשב.
* מא:
** עדיפא -
אפשר שכוונתו הוא שאין חיוב גניבה זה שייך, ולא ילמד על חיוב אחר, שאינו בא משמירה כל כך, אלא מגזלה. ותחשב.
* מב.
** ואחר כך בירך -
לכאורה, ר"ל שאחר כך התפלל (דבר ראשון שנזכר), שהשני הוא רק ברכה לה‛ על שברך את התבואה, והרי אין בזה תפלה. ועיין בירושלמי שצריך להגיד שמותר לומר, ”בטוח אני שיהיה…,“ ואינו תפלת שוא. אולי, אז, לא כל כך רחוק הוא שזה נחשב כעין תפלת שוא. ותחשב.
* מב:
** כיסי -
צריך ביאור ל"ל נאמר שכיון שבידים איבד אותם, הוא מזיק, וכיון שהוא אדם, חייב אף באונס. אולי זה אונס גמור. זה לא יהני לרמב"ן שמחייב על אונס גמור.
** הואיל ונהנה -
לכאורה, מילים אלו אומרים הסיבה לחיוב של שומר שכר. ותחשב.
* מג:
** ובי דינא -
יש לדון בזה, שלכאורה, כבר חייב, אלא בית דין הם הכופים אותו. ותחשב.
** א"ל -
יש לדון מי אמר כן כמו שדיננו בגמרא בכורות. ותו"ת.
** החושב -
היה אפשר לומר שלא חולקים לעיל אם צריך חסרון, אלא אם מחשבה הוא שליחות יד, אלא שכיון שחולקים כאן בזה, לא רצה שיהיה אותו מחלקת.
** החושב -
אם כן, לכאורה, אין שליחות יד צריך חסרון. עדיין יש לדון אם צריך לחשוב על דבר שיש בו חסרון או לא.
* מד:
** צריך לבאר קנין
חליפין, ולמה אינו בכסף. אולי ענין של קנין חליפין הוא כך: יש לאדם יחס לחפץ. מכניס חפץ לרשותו, וכאילו מחליף מה שהוא ברשותו, לומר שבמקום זה, שהיה ברשותו, זה יהיה ברשותו. ותחשב. זהו סיבת קנין סודר.[fn:3]
א"כ, אולי אין לעשות קנין סודר בכסף כיון שאין כסף יכול להיות חילוף של דבר, שהרי הוא חלוק ממטלטלין, שאינו בא להנאת עצמו, אלא לקחת דבר אחר בו. יש על זה עדיין שני קושיות:
1. למה יכול לקנות ממון במטלטלים בקנין סודר. לזה, יש לומר שכיון שממון הוא עומד להנאת מטלטלין, הוא דומה די למטלטלין. צריך לומר שמה שהנתון יכול להיות כעין הנקנה לא די; צריך להיות להיפך. ותחשב על זה.
2. למה לא יכול לקנות ממון בממון. אולי הענין הוא שאף ממון חלוק מממון, ששם נתון לממון על פי מה שעומד ליקח, ולא על פי עצמו, שהרי הנאתו לא בא מעצמו, וכיון שיכול להיות שיקחו דברים חלוקים, אין ממון דומה. צריך לומר שעדיין אין כל שמו על פי מה שייקח, שהרי אינו שווה למטלטלים.
ותחשב על כל זה.
גם יש לומר שקנין חליפין הוא שאגב שמכירה קורה בין שניהם, מכירה שני קורה בין שניהם. נראה שאז יש לדון אם הוא בכליו של לוקח או של מוכר (אבל לא הבנתי כל כך למה לא יהיה בכליו של מוכר. ואולי הדיון הוא אם יש סיבה להיות דבר שווה לו או דבר שהוא symmetrical. ותחשב.). יש לדון בזה:
1. בענין ממון ומטלטלים. נראה בזה שיש לומר כמש"כ לעיל.
2. למה אינו דומה לאגב. יש לומר שבאגב, קרק‛ של חפץ (סיבה או קנין) גורם אותו דבר בחפץ אחר. כאן, יחס בין מוכר ללוקח גורם כן בחפץ אחר. ותחשב.
נראה שאולי לכן אין צריך שיהיה שווה שם (באגב), והוא שכל היחס הוא לעולם דבר שהוא עושה, שהוא נותן חפץ אגב חפץ, והרי אינו חפץ שווה, ואז צריך לומר שמה שמאגב אותם (מסתמא הוא רק מה שרוצה בקנין אגב) עושה שהם מיוחסים די לעשות קנין אגב. אם כן, אולי כיון שרואים שדעתו חשוב בזה, אולי מסתבר שהוא כן אף אם אינם כל כך דומים.
כאן, אינו כן, שהדמיון בין חלות ראשון לשני הוא שהם בדבר שווה- שהם בבני אדם השווים. אם כן, אין דעתו חלק ממה שעושה אותו סיבה[fn:4]. כיון שאין רואים שדעתו חשוב, לא נניח שאף אם החלות הוא חלוק יכול להשוות אותם בדעתו.
ויש לדון, שאף שאין רואים שדעתו כל כך חשוב, שהחפצים שווים, אין החלות שווה. ואף שאין זה כל כך חשוב, זה גם כן עושה שהשינוי שיש כזה ממון וזה מטלטלים אינו כל כך חשוב. ותחשב.
** דינרי -
יש להעיר ששם דן בדינרי לנגד עוד דינרי, מה שאין כן במשנה שדן בו לנגד שאר מיני טבעא. ונראה שאם הוא יותר מכסף, אז הוא הכי מטבע. אז, משערים הכל בו, והוא מה שלא נשתנה, ואז אין בו סאה בסאה. ותחשב.
* מג:
** החושב -
יש לדון אם צריך לדבר או רק לחשוב. ראשון, יש לדון אם יש שום נפק"מ, שבין כך ובין כך צריך עדים. ויש לדון, שאולי יכולים להעיד על דברים שמודיעים את מחשבתו. גם יש לומר נפק"מ כשהודה. עיין לשון רש"י, שמשמע שמדבר. יש לדחות שזה רק כדי שיהיו עדים, שזה הציור הכי פשוט שבו יחייב. גם יש להביא ראיה מלשון הקרא (”דבר“). ויש לדחות שכיון שיודעים שאינו צריך לעשות מעשה ממש, אין סיבה לחלק, ואז קרא שמלמד לנו דיבור ממילא מלמד לנו מחשבה. ותחשב.
* מד:
** פירות על דינרים -
ר"ל פירות על דינרי (שגמרא ב"ב מבאר שדינרי הוא של זהב, ודינרים הוא של כסף). נראה שלא חש לזה כאן שרק דן בדינרים אחד, ששל כסף אינו בדינרים.
** דאמר ר"י -
ואם תאמר אם כן ימצא כב"ש, וקשה למה אמר כב"ש. אולי אה"נ, אבל למעשה מוכרח שאמר כן (וצריך להיות שיש לו שום סיבה). ויש לדון. גם יש לומר שאז לא נניח שאמר כן להלכה, אלא לביאור שיטת תנא. ותחשב.
* מה.
** לגבי נפשיה -
לכאורה, תירוץ של גמרא (שהולך בתר מה זה ונתיקר) פשוט, וצירך ביאור מהו ההוה אמינא שלא לומר כן. וצריך לחשוב.
* מה:
** עיין לעיל שדיננו
למה אין חליפין בכסף. שוב ראיתי בסיבה שאומר גמרא לקמן (מה:). ודע שאולי נצטרך לפשטים שכתבנו לבאר למה לא נקנים בחליפין (ונצטרך לבאר להיפך, לצד זה, למה לא נקנים, אבל נעשים). ותחשב על זה.
** תרווייהו -
לכאורה, ר"ל שלשניהם יש צורה, ואם המשנה אומר שאחד מהני, שניהם יהנו. ותחשב.
** גברא -
ר"ל שאין שום רבותא במה שהוא בכל מקום כיון שהחיוב הוא על האיש. ותחשב.
* מו.
** ואף רב פפא -
אז, מה שאומר משנה שהזהב קונה את הכסף צריך להיות שמחייב אותו, שאינו קונה אותו בחליפין. אם כן, מסתבר שאף הרישא כך, ואין המשנה בחליפין. ותחשב.
** כל הנשום -
ק"ק, שלמד"א שאף כלים בכלל אינו כל דבר. א"כ, כשמק‛ גמ‛ מכיצד, היה לו להק‛ מכאן. וחח‛.
* מו:
** סבר לה כר"י -
אלא שלכאורה, ר"י לא סבר כמותו, שהרי אמר שאין מטבע נעשה חליפין, והיה לו למעטו כיון שאינו כלי. היה אפשר לומר שכיון שקונים בו, חשוב הוא ככלי, אבל רש"י לעיל אמר נגד זה. ותו"ת.
** מטבע הוא -
ואם תאמר הרי צורתו בטל כבר, ואי אפשר למלכות לבטל אותו עוד, ולמה לא יקנה בחליפין. ויש לומר שיכול מי שלא פסל (מלכות או מדינה) לפסול אותו. אז, כשאומר, ”משום דסי… אבל…“ אין ה“אבל“ רק אומר הסיבה שאין יודעים זה כבר מציור השני, אלא הוא חלק מן ההוה אמינא שהוא מטבע. ותו"ת.
** ואין מטבע נקנה -
גם היה אפשר לומר, ”ואין מטבע נעשה,“ אלא שלמס‛, אולי, כולי עלמא מודים לזה. ויש לדון אם למסקנא כולי עלמא מודים לזה, או שרק ר"פ הדר בו בזה.
* מז.
** בההוא הנאה -
יש לצרף את זה למה שבארנו בראש הפרק.
** מקפיד -
לכאורה, הסיבה שהקפדה זה שייך לחליפין הוא שאז אינו כל כך מסויים, שיכול לשנות בזה.
** שופטני -
ק"ק, שמגמרא נדרים נראה שבדרך כלל, בקנין סודר, נותן ע"מ להחזיר.
* מז:
** דכשר -
יש לדון ל"ל ישנה את זה לעיל כשדן בו בתחלה (ואמר שהוא לאפוקי מדשמואל).
* מח.
** תרי מיני -
ק"ק למה ימנה שניהם, שאין סיבה לחלק ביניהם, ותחשב.
** ק"ק
למה לא דוחה ר"י את המתניתא לומר שזה אחר תקנת רבנן. ותחשב.
* מח:
** בעושה מעשה עמך -
יש לדון אם מביא מזה רק שמותר לקלל (ויש שום דרשה אחר שאינו כל כך פשוט לומר שצריך לקלל כאן) או שכיון שאין רע לקלל, וקללה יגרום שלא יחזור בו, אין בעיה לקלל אותו. ותחשב. הדרך השני מסתבר ביותר. ותו"ת.
* מט.
** הבמ“ע -
היה אפשר לומר שאף שיכול לחזור בו, יכול להניח שלא חוזר בו. ואפשר שלא מביא ראיה לדין, אלא מביא ראיה למה שסומך דעתו. ותחשב.
** דור המבול -
צריך ביאור למה מזכיר אלו. ותו"ת.
* נא.
** הוה מחילה -
נמצא שמניח שלא צריך להחזיר אונאה. עיין לעיל שדן בזה גמרא.
** קים ליה -
ואם תאמר הרי אם לא קים ליה, ונמצא שהוא טועה, הרי לא עבר, ואינו מזיד. ויש לומר שזה גופא הוא חידוש של הקרא, שאומר שיש איסור ודאי על דבר שחושש קצת שהוא אונאה, ואז הוא מזיד על אותו איסור. גם יש לומר שלא מחדש איסור, אלא מחדש מה שיש דיני אונאה. עיין ברש"י, שלא אומר כן, שאומר שקאי על האיסור. ותחשב.
* נב.
** ממטה -
צריך ביאור איך יודעים איזה כולל אותו שיעור עצמו (אם יש אונאה באותו שיעור או לא). עיין ברש"י, שמבאר איזה כולל אותו, ונראה שאף מכוון לבאר איך יודע, אבל לא הבנתי מה אומר בזה. ותחשב.
* נב:
** מוכרה בשוויה -
אם הדין הוא כך ליותר מכדי אונאה, קשה מה בין פחות מכדי אונאה ליותר מכדי אונאה. יש לומר שדין כדי אונאה הוא רק אם א"א לשום טעם לקיים אותו כסלע. דחוק, שמה יהיה אותו טעם. גם יש לומר שסובר שבכדי אונאה, מותר אף להוציא אותו כאילו הוא סלע. ואם תאמר הרי אסור להתאנות. ויש לדון אם אסור בפחות מכדי אונאה.
גם יש לומר שפחות מכדי אונאה אסור לקיימו, אבל בכדי אונאה חל (כדיני אונאה). יש לדון, אז, למה החולק יחלוק. צריך לחשוב על כל זה.
** אלא שלחני -
אז, קשה ל"ל אומר אותו שיעור, שנמצא שהוא שווה.
** כל אדם -
אינו כל אדם ממש, שזה לא הכיר עד שהראה לחברו.
* נג.
** נכסי -
יש לדון למה פשוט שזה קולא, שזה גורם קולות וחומרות. ותחשב.
** לא מצטרפים -
הענין כאן הוא שאין פודים מעשר שהוא פחות משווה פרוטה. לקמן דורשים את זה מקרא, ולכאורה, הסברה לזה הוא שצריך להיות דמיון בין מה שפודים ומה שפודים בו. מה שזה ממון, וזה אינו ממון עושה שאינם דומים. ותחשב.
* נג:
** דנפול מחיצות -
קשה, שיש היתר- בבנין מחיצות. לרש"י, קל לומר שזה טורח יותר ממה שצריך לעשות. יותר קשה לר"ן. אולי אינו כל כך דומה להיתר כיון שצריך יותר כדי לעשות אותו היתר. ותחשב.
** דיו -
לא הבנתי ראיה זה.
* נד.
** דבר הראוי להיות -
יש לדון אם צריך שייעשה קדוש על ידי חליפים זה, או שיהיה דבר שראוי להיות נתקדש. ותחשב ותבין.
** אכלה -
יש לדון אם דין שוגג הוא מחמת עשייתו בשוגג (כעין עונש), או מחמת שחסר תרומה, ואין חיוב של מזיד לעשות שאינו חייב על הזיקו. ותחשב.
יש נפק"מ אם, למשל, מתעסק. ותחשב.[fn:5]
* נד:
** הכי אמר רבא -
יש להעיר שלכאורה אין נפק"מ חוץ מהוספת חומש. ויש לדון, שואלי רק בא לבאר לו שעדיין אפשר להסתפק.
* נה.
** האונאה ארבע כסף -
יש להעיר שאין זה ממש שיעורו כשאר שיעורי משנה. כיון ששאר שיעורים לכאורה, רק באים אגבו, מעניין שהם דומים די.
* נו.
** מכל גמרא זה יוצא
שיש חילוק על פי עונשים חלוקים. יש לציין למימרה של רבה לקמן, שאין חילוק, לענין אם גוזרים או לא, בין איסור מיתה לאיסור לאו. יש לדון אם חולקים, או שלענין לגזור ולענין מה לגזור יש חילוק. ותחשב.
* נז.
** לכתחלה -
אם כן, אינו צריך להפך.
* נח.
** רב יוסף בר חמא -
זה אב של רבא (עיין ברש"י בחולין). מעניין, שאין לשון רבא משמע כל כך שמשיב לאביו. אולי היו שני ריב"ח או שני רבא. ותו"ת.
* סה.
** טרשא -
לא הבנתי למה טרשא של רב פפא חלוק מטרשא רגילה, שבשניהם נראה שנותן חפץ עכשיו, ונוטל יותר ממון לאחר זמן. נראה שהוא מפני שכאן לא היה צריך לתת אותו עכשיו, שיכול לתת לאחר זמן, שלא היה החפץ נחסר.
** זוזי לא צריכנא -
צריך ביאור מה לנו בזה, שאינו משיג הממון עכשיו בין כך ובין כך. אולי ר"ל שאינו יכול להיות שכר כנגד ההמתנה, שהוא לא נחסר מחמת זה. יל"ד, שהלוקח נתרווח. נראה שזהו טענת המקשה. ויש להעיר שלכאורה, אין "זוזי לא צריכנא" ודיחויו שייכים לטענה ראשונה שאמר (שיכול למכור לאחר זמן אם רוצה, ולהשיג אותו טובה). ותחשב.
* סו.
** אדעתא דידה -
וצריך לומר שבהוה אמינא זה חזק די לומר תנאי (אף שלא נאמר בפירוש).
** ולא כלום -
מעניין שירגיז לומר שבוודאי הוא נכון, והכל לנגדו אינם כלום, ושוב יחזור בו. אולי לא חזר מלאחר מתן מעות. ותחשב. ועיין לקמן בגמ’ לביאור הטעם.
** אינו כל כך ברור
לי בכל ציורים אלו של מכירה או כדומה אם הוא רבית דאורייתא (שהרי, קצצו אגר נטירה) או רק נראה כמו רבית. יש לדון ל"ל יהיה רבית. אולי הוא מפני שלא ביארו למה נותן הממון המיותר. גם יש לומר שהוא מפני שהוא מכירה. ותחשב.
* סו:
** דלמא לפכוחי -
היה אפשר לומר שלהיפך, מניחים שכיוון להקנות (שכך אמר), אלא אם כן יש לנו ראיה שהוא דואג עליו (שכיון שהוא דואג כל כך, לא מסתבר שהוא נתן אותו, ואז צריך לומר שלא כוון לתת אותו).
** ואי אמר קני -
רצה לומר, אף אם עשה אותו אפותיקי בלשון זה (שאמר "אם"), לא היה חל. דין זה (שלא היה חל אם אמר "אם" מסתבר להניח כדי לפרש גמרא כאן, ומוכרח בגמרא לקמן. ואם תאמר למה יהיה כן. לכאורה, הסיבה שאין כל אפותיקי אסמכתא הוא שאינו חסר כל כך. אם כן, אף כאן נאמר כן. ויש לומר שמה שאין אפותיקי אסמכתא הוא שלא אומר "אם,” שלשון "אם" משמע שלא כל כך ברורו לו שכן יקרה, ומה שמזכיר זה הוא מפני שלא רוצה שיקרה. כמו כן, יש לומר שצריך שני הדברים, שלא הזכיר אם ושלא חסר כל כך. ויש לדון בסברה זה, שלכאורה, מ"לא תהא… אלא מזה" גם פשוט שיכול לתת ממון, ושאולי ייתן ממון. ותחשב על זה.
* סז.
** דלא ידע דאיתיה -
לא הבנתי חילוק זה. בשני המקומות, נתן ממון וידע שנתן ממון. בשני המקומות, חשב שלא היה צריך למחול כיון שחשב שבדין הוא של מי שאוכל. אם כן, לכאורה, אין חילוק. ותחשב.
** צריך ביאור
למה יהיה מחילה בטעות חלוק ממקח טעות. אם נאמר שמקח טעות לא חל כיון שהוא אומדנא שמתנה, קשה, שאף כאן נאמר שיש אומדנא להתנות במחילתו. אולי אין אומדנא, שכיון שאין חפצו בעין, עדיין אפשר לומר שאולי מוחל לו. אם מקח טעות לא חל מפני שאין דעת בטעות חשוב לעשות חלות, אז אולי יש לומר שחלות מחילה אינו כל כך חשוב, ויותר קל לעשות.
גם נראה שיש לומר לשני הצדדים שאין מחליה חלות, אלא הוא שאינו עושה חלות תביעה. כיון שלא תובע, זכה הלה בו. אם כן, כאן, שלא תבע, אף שלא תבע מחמת טעות, זכה חברו. ותחשב.
* סז:
** קיצותא -
לצד ראשון של קיצותא, לא הבנתי הצד שהוא מותר, שהוא רווח אכילת שניים ראשונים. ותחשב.
** מסתקלנא -
לכאורה, המתנה כאן הוא מי שלא מפסיד, ואז אמר גמ’ לעיל שהוא רק פטומי מילי. וצריך ביאור.
* סח.
** קא פריק -
לא הבנתי למה מביא רק מהקדש, שיש עוד דברים כזה, כגון גואל שדה שמכר. ותחשב.
* סח:
** דנפיש טרחיה -
לא הבנתי, שלכאורה, זה חלק מ"כפועל בטל,” שמשימים החילוק בין מה שהיה עושה למה שעשה. אז, קשה למה נאמר שבאחד לא סגי או בשני לא צריך. ותו"ת.
* סט:
** מרא -
צריך ביאור מהו הצד שמותר בשכירות, שאף אסור במכירה. ותחשב. ויש לומר ששאני מכירה ש"כמו הלוואה, יסודו הוא להחליף שווה בשווה. שכירות אינו כן, שיסודו הוא ליתן ממון לתשמיש.
* ע.
** מותר להלוותם בריבית -
יש לדון למה מקילים ביותר גבי קטנים, שכל מה שיכולים גדולים לעשות, נוכל לעשות לקטנים באפוטרופוס. אפשר לומר שאי אפשר להם לשאול על הפתחים, שלא ייתן אדם לאפיטרופוס אלא לעני עצמו. גם יש לומר שלא ימצאו אפיטרופוס שרוצה לשאול.
גם יש לומר שכיון שאין הממון של אפיטרופוס, ממילא לא יהיה כל כך טוב בעסקו, ואז תקנו דרכים אחרים שירווח אותם. ותו"ת.
** רבה בר יוסף -
רבא סתם הוא רבא בר יוסף בר חמא. נמצא שהיה רבה בר יוסף בר חמא, ורבא בר יוסף בר חמא. יש לדון אם היה אחד, ולפעמים היה נקרא רבה ולפעמים היה נקרא רבא, או שהיו שני אחים, או שני סתם בני אדם. גם יש לומר שיש לגרוס כאן רבא.
* ע:
** אפילו רבית עובד כוכבים -
אם כן, לכאורה, אי אפשר ללוות להם כלל, שאי אפשר ללוות בריבית, ואי אפשר ללוות בלי ריבית כיון שהוא מתנת חנם.[fn:6]
* עא.
** יורד עמו -
יש לציין לגמרא קידושין כח..[fn:7]
** ערב -
לא הבנתי, שמותר אף להיות לווה.
** זכירה -
כיון שהוא רק מדרבנן, צריך ביאור איך יתיר ריבית דאורייתא.
* עב.
** ולא היא -
יש לדון אם אומר כן על הדין או על הראיה.
** ורבי מאיר -
יש להעיר שיוצא מדיון של דאקני בגמרא ב"ב שאולי בין כך ובין כך צריך להיות רבי מאיר (של דבר שלא בא לעולם).
* עג:
** משכן -
נראה שמה שקרה היה שגויי משכן אותו לרב מרי, וגוי מכרו לרבא. רב מרי נשאר בבית, ולא נתן שכר עד לאחר שנה, כיון שלא היה נשאר שם מפני רבא לאותו שנה, אלא היה כבר זכאי להיות שם.
** אחמרי -
אם כן, נותן פחות ממון ממה ששאר בני אדם נותנים על חמרא, שכל בני אדם נותנים עך הדעת שאולי הוא חמרא. צריך לומר שכיון שנותנים ממון עליו עכשיו, ועכשיו יש לו, אי אפשר לומר שהוא אגר נטר, שאינו למכירה לאחר זמן.
ולא זוכר אני את הדין, אם יכול לחזור בו אם נתחמץ יינו. חושב אני שהוא מחלקת אמוראים בציורים מיוחדים. לכאורה, אם יכול לחזור, אז פשוט שלא נהנה כלל. אולי זהו מה שאומר גמרא, אבל לא משמע כן. אם לא יכול לחזור בו, קשה איך נאמר שכאילו לקח יין, שאילו יש לו יין ונתן לו, לא היה דין זה נוהג. ויש לומר שלא יודעים מה כאילו נתן לו, אבל כאילו נתן לו. ותחשב.
* עד:
** רבי שמעון -
לא הבנתי כל כך, שאם קונה במעות, למה זה ישנה אם נשתנה השער. אולי לא נתן על דעת זה.
* עה.
** ולאו מילתא -
יש לדון אם קאי על שני המאמרים.
* עה:
** אלא שמשימים -
ר"ל שאומרים שתורה שקר, שאילו היה אמת, היו צריכים לעשות כן, ואומרים שמשה אינו חכם, שאם ה’ לא נתן התורה, צריך לומר שמשה חדש אותו, ואין זה דבר חכם לחדש.
** לפני עור -
משמע שעובר על כן בוודאי, ואף אם משלם. קשה, שבגמרא אומר ש"כל שכן מר,” שישכח ויגרום קללה. אם יש לפני עוור אף אם לא ישכח, הרי בין כך ובין כך גורם קללה. יש לומר שקללה חלוק מלאו של לפני עור. קשה עדיין למה לא השיבו מלאו של לפני עוור.
נראה לבאר על פי רש"י, שמלשון רש"י נראה שאין איסור בכל מצב שעושה שאפשר שיעבור, אלא בשעה שעושה שאדם משים על מחשבתו לחטוא (צריך ביאור למה זה רע, אבל מצאנו רשעים שאומרים שעל מחשבה בלחוד יש פעמים שנענשים). אם כן, אולי בדרך כלל, עובר מיד. בת"ח, שלא יעלה על רוחו לחטוא, לא עובר עד שחוטא.
עדיין צריך ביאור למה יש כל שכן גבי תלמיד חכם, שהרי בכל אדם בוודאי יעבור, ובו הוא רק ספק. אז, נראה שצריך לומר שרק מפרש הקללה, ורק בקללה הוא כל שכן (ולכן רק מפרש את הקללה). ותחשב.
* עו.
** וליחזי -
יש להעיר שאף אם רואים שעשה עבודה טובה, רק יקבל דמי הנאתו. אם כן, יכול להיות שיחסר, ואז יהיו לו תרעומות.
* עז:
** הוה ליה כניזק -
לכאורה, גרמא הוא. ואולי כיון שכל דין עידית הוא (אולי) תקנה, תקנו חכמים אף לגמרא, כל זמן שנוטל כלל.
** מעידית שבה -
לכאורה, עדיין צריך ביאור למה נוטל עידית שבה, שיהיה כבעל חוב. אולי מסתבר שאדם שנותן ממון נותן תחילה על מה שהוא יותר טוב. ותחשב.
* עח.
** שמתה מחמת אויר -
צריך ביאור ל"ל באר זה במשנה (ר"ל, צריך ביאור ל"ל חילק גם בזה). אולי זהו הסתם.
* עח:
** שינוי מעשה -
צריך ביאור, שהדין הוא שרק קונה בשינוי מעשה אם הוא גזלן. צריך לומר שאומר שהוא גזלן. נראה שדוחה גמרא שאינו כן, אלא שינוי מעשה קונה בכל מצב, ואז אולי אינו גנב.
** למיחשדיה -
צריך ביאור ל"ל תירץ כאן כמש"א לעיל (שעל דעת חלוק נתן לו…).
** לאו מי איכא -
לכאורה, הסיבה שלא לומר כן הוא שאולי קאי על ת"ק, ומודה לת"ק, אלא מוסיף דין, ואז אינו כשמואל. ותו"ת.
* עט:
** אפילו -
יש לדון אם אומר שה"אפילו" השני מוסיף על הראשון, או אומר שאין שני "אפילו"ים, אלא אחד, ואומר חד ציור שיש בו שני מעלות.
** שמע מינא -
לא הבנתי כל כך מהו החידוש, ששם הוא גודל בני מעיים, אבל כאן הוא גודל של מה שיש בהמה בתוכה. אולי אף שם, יש דג בתוכו. אם כן, קשה ל"ל יקנה, שיאכל את העובר בתוכה. אולי אינו כל כך טוב לאכילה.
גם צריך ביאור מהו ההוה אמינא, שלכאורה, פשוט הוא שאם יש עוד דברים בה שתהיה יותר גדולה.
* פ:
** תפיש ליה -
אם כן, יהיה כן אף אם כבר גמר ואמר לו לקחת את כליו, שעדיין יכול לתפוס אותו. אולי גילה שלא רוצה לתפוס אותו.
** טפ פורתא -
צריך ביאור ל"ל יהני. אולי מניחים שכמעט צמצם (שכמו שיכול להיות שהותיר, יכול להיות שפיחת). ותחשב.
* פא.
** הואיל ונהנה -
נמצא שהסיבה לחיוב שומר שכר (או חיוב שומר שכר יכול להיות מפני זה[fn:8]) הוא "הואיל ונהנה מהנה. יש לדון מהו סברה זה.
ודע ששני הסברות העיקרות הם שהוא דבר בעצם (יחסו לו גורם שההפסד ילך קצת לו) או שהוא התנה כך.
* פא:
** מהא ליכא -
כאן, אין לומר שש"מ שתנא של משנה זה לא דייק. אם כן, צריך ביאור ל"ל היה מדקדק. ונראה שכמו שבדרך כלל יש ראיה שתנא של משנה לא דקדק, יש ראיה שאחד מאלו לא דקדק, אבל לא יודעים איזה. ותו"ת.
** מה ליה לשקר -
במק"א הערנו על לשון "מה לי לשקר.[fn:9]” כ’ שאולי ר"ל מה לי לעשות שהוא שקר, והוא כמו "לאמת דבריו.” כאן, אי אפשר לומר כן, שאז לא היה לו לומר "ליה.” ותחשב.
** רשותא -
מניחים, אז, שכן כוון השואל, ושהמשיב הבין את זה, ואז, בהכרח, השיב לו שישמור לו.
* פב.
** אלפא זוזי -
נראה שהוא קצת לשיטתו במה שאומר שיכול לפדות הקדש בזוז אחד, שנראה דומה לזה. נראה שסובר שזוז אחד וכמה זוזים הם חילופים של הדדי, וזה עושה שני התוצאות. ותחשב.
** לימא דר"י -
היה אפשר לומר שחולקים בסברות של רבי מאיר (אם הוא מפני שעשה התורה שהוא ש"ח או מפני שעשה מצווה ואז פטור מצדקה).
* פב:
** שלהנאתו -
נמצא, אז, שכל מי שעושה מצווה להנאתו לא פטור ממצוה אחר. זה מעניין. אולי הוא מפני שבזה מצווה השני שבא לו יהיה יותר טוב מן הראשון.
יש לדון אם חולקים אם מניחים שכיוון למצווה או אם צריך לכוון למצווה, או אף להנאת עצמו מהני.
** רבי אליעזר -
פשוט שר"ל רבי אלעזר, שהיה חבר של ר"מ, ולא רבי אליעזר, שהיה רבו של רבו, ולא היה חוזר לו כן. אולי לא משיב, אלא שאומר שאף הוא שמע, ולא הבין. ויש לדון.
* פג.
** אין רואה -
שמעתי פשט בזה שיש ריעותא ממה שלא מביא עדים. גם שמעתי שהוא מפני שרוצה תורה שנוכיח אותו בראיה יותר טובה. גם יש לומר שרוצה תורה שלא יהיה שבועה (או שבועה בשקר). ותו"ת.
* פג:
** יבוא בעל הקוצים -
ואם תאמר נאמר כן אף בחיובי מיתות. ויש לומר שאין הכי נמי, היה לנו לומר כן מסברה, אלא שגילה לנו תורה שלא נאמר כן. ויש לדון איך נאמר אם על ידינו ה’ ממית. ותחשב. ואולי צריכים לחוש לחומרא, שאין רע שייצא, שה’ יכול להרוג בלי מה שנעשה. ותחשב.
** על נערה -
ק"ק שגמ’ אומר מה נעשה לבני אדם שחייבים מיתה בזמן הזה, ואינו זה. ויש לדון.
* Footnotes
[fn:1] ודע שאפשר לומר שענין דבר בלי סימן הוא שממה שלא נתן בו סימן, לא חשש שיאבד, ומיאש אם יאבד, שאילו לאו הכי, היה נותן בו סימן כדי שיהיה יותר קל להיחזר לו. ותחשב.
[fn:2] אלא שאולי נאמר שאז הדין הוא כמגדל זה, וגמרא רק אומר הציור הכי מחודש.
[fn:3] לכאורה, זה רק למד"א שלוקח נותן דבר, ולא שמוכר נותן דבר.
[fn:4] אולי צריך דעתו לעשות עוד סיבה לחלות, אבל אינו נוגע לעשות שיכול לאגב.
[fn:5] ואולי אין נפק"מ, שאולי בין כך ובין כך יהיה כמתעסק בחלבים ועריות.
[fn:6] כותבים כמה פוסקים שאי אפשר ללוות להם בלי ריבית מחמת זה.
[fn:7] ועיין איך מפרש אותו רש"י שם וכאן.
[fn:8] שאפשר שבאופנים חלוקים הוא מסיבות חלוקות
[fn:9] שלכאורה, יכול להיות שיש לו לשקר, אלא היה לו לומר מה לי לשקר כך, שיש לו שקר אחר שהיה אפשר לומר.
