* ב.
** בעלמא -
יש לדון מה אומר:
1. לא נדע שבדרך כלל, אין ראיה קונה. אז, זה מלמד לנו דין. לא משמע כן מלשון גמרא.
2. אף שמוסיף כאן מילים, עושה שבמקומות אחרים יכולים לגרוע מילים, ששם יכולים לומר ”מצאתיה,“ ונדע מהו הדין. יש לדון איך נוכיח שם מכאן:
  1. מכאן רואים שצריך קנין, ולא די בראייה.
  2. מכאן רואים ש“מצאתיה“ אומר שבא לידו.
** ראייה -
יש לדון אם ההוה אמינא הוא שיקנה מדאורייתא (מסתמא, מפני שראייה גופא הוא יחס או מפני שאז הוא קצת עומד לקחת אותו), או מפני תיקון דרבנן (כעין תקנת ד"א).
** ראייה -
חושב אני שיש דיון ברש"י ותוס‛ בב“ק (קרוב לדף ל) בענין קנין בהבטה מהפקר. צריך ביאור איך יפרשו גמרא זה. אולי יסברו שכל זה הוה אמינא. גם יש לומר שיש חילוק בין ראייה להבטה. ותחשב.
* ב:
** בהדי הדדי -
מעניין שכל אחד קונה כלל, ולא אומרים שאין אחד עושה מעשה קנין עליו כיון שחלק ממנו נגבה על ידי חברו.
** דליכא למימר הכי -
קשה, שעדיין יכול להיות שמשקר, ועדיין נשביע אותו. ונראה שר"ל שאז אולי לא יהיה כל כך מפחד משבועה, ויותר קשה להניח שרק ישבע על האמת.
* ג.
** רבה -
צריך ביאור, שלכאורה, הענין הוא שיש סיבה להאמין אותו אם לא מודה במקצת. קשה, שבעדים, אז, נאמר שאין הוכחה, שעדים אומרים שהוא מעיז פניו.
