* ב:
** אימור -
לשניהם נתרצה- יש לדון, שאז נראה איזה קדם. ואולי, כמו שטרות, אין הקדם של אותו יום מהני. גם יש לומר שנתרצה לתת לשניהם, לזה חצי ולזה חצי. ותחשב.
* ה.
** תא שמע -
צריך ביאור מה מוסיף רש"י, שלכאורה, כל ת“ש כן. נראה שמבאר שאינו מביא ראיה לשום אחד, שאין חולק.
* ט:
** ואי אדם חשוב -
לולי רש"י, היה נראה לומר שבדרך כלל, רכיבה של קנין לא יהני כיון שלא רגיל, אבל לו רגיל. מרש"י משמע שלא מיירי ברכיבה שרגיל לקנות, אלא ברכיבה בלי ניהוג. ותחשב.
* י.
** קונות -
מרש"י משמע שאינו קנין ממש, אלא איסור על אחרים ליקח. יש לדחות שרש"י רק מבאר איך זה יגרום שלא אתי לאנצויי.
* טו.
** בלוקח -
ארעי אשבח- יש לדון בכל חשבונות גמרא לצד שגובה למפרע. ותחשב.
* כא.
** מעות -
סימן ניכר- צריך ביאור למה רש"י מוסיף זה. לכאורה, בא לומר שאם יש סימן, אבל רוב בני אדם לא יכירו אותו, מניח שאין הבעל סומך על אותו סימן.
* כא:
** לקוטי -
לכאורה, תרגום מילה שאומר רש"י כאן יכול להיות בכל צד, אם לא שנאמר שבצד זה, לוקטים ביותר. יש להעיר שיש שאומרים ששיעור שנים אלו שווים; א"כ, א"א לומר כן.
* כב.
** הא סתמא -
עיין במה שפירש. לולי זה, היה אפשר לומר שלשון גמרא משמע שנתיאש בפועל (שאומר שנתיאש), ומשמע שאילו לא נתיאש בפועל, לא היה הדין כך.
** אתם -
לשון רש"י משמע שהדרשה הוא שכאן רק אומר שלוחים דומיה דאתם, וכיון שזהו המקור, ממילא לא אפשר ללמוד שלוחים אחרים. יש להעיר שגמרא בקידושין אומר מקורות אחרים, ונמצא, לכאורה, שזה רק מקור לדין שלוחכם לדעתם. אם כן, הלימוד הוא שאומר ”אתם,“ שאומר שצריך להיות מדעת, ויודעים שקאי על דין שליח כיון שגם כתוב באותו קרא שליחות. אין זה כמשמעות רש"י.
* כג.
** סימן הבא -
כ‛ שמניחים שנתן שם מדעת. גם היה אפשר לומר שמניחים שסימן שלא נתן מדעת הוה סימן.
* כד:
** אינו חייב -
דלא אזלי בתר רוב- יש לדון ל"ל מביאים את זה לראיה בב"ב וב"ק במחלקת אם הולכים בממון בתר רוב. ואולי כיון שמסיק שהוא תנאי, אין צורך עוד להביא ראיות. ויל"ד.
גם צריך ביאור למה אומר כן רק לרבנן, שלכאו‛ אף לרשב"א אין הולכים בתר רוב, שרק אומר כן ברבים מצויים שם, וזה מוכרח לומר שלא מניחים שבא מגוי, אלא מניחים שהבעל ייאש מפני העובדי כוכבים שהם שם. ותו"ת.
נראה שרש"י לאו דווקא, ורק אומר לשון גמרא של ”הולך בתר רוב.“ ויש לדון.
* כה.
** והוא -
נראה שמפרש שענין מלכים הוא חלק מ“מגדל“ שצריך. לולי רש"י, היה אפשר לחלוק ע"ז.
* כז.
** ממונא -
עיין במה שבאר. לולי זה, יש לומר שאין צריכים הפקר בית דין הפקר, שכיון שתקנו כן, לא יהיה מיאש, ואז יהיה הדין כן. ותחשב, שאולי צריך שיהיה להם כוח כדי להתחיל את זה. ותחשב.
* לג.
** רוב חכמתו -
לולי רש"י, היה אפשר לומר שרוב חכמתו הוא ממש חכמה, ולא משניות וכדומה. יש להביא קצת סמך לזה ממה שאין ללמוד משניות וכדומה משני בני אדם, ורק סברה יש לו ללמוד מכמה בני אדם. אם כן, יותר נמצא שיהיה רק ”רוב חכמתו“ בסברה.
אפשר שקשה להגדיר ”רוב חכמתו,“ ואז מסתבר שלא עליו קאי.
* [fn:1]לח:
** אמוראי -
משמע שחולקים מתי ההלכה כרשב"ג. היה אפשר לומר גם כן שחולקים בלשון שאמר אותו רבי יוחנן. אפשר שאילו אמר כן רבי יוחנן על כל מחלקת חוץ משלוש, היה תלמידו אומר אותו בלשון ”כל חוץ משלוש,“ שיש ללמד בלשון קצר. ויש לדון, שאולי נקט לשון רבו. יותר קשה מזה הוא שאם כן, היה לו לרבי יוחנן לומר לשון קצר זה. ותו"ת.
** רשב"ג -
מניח גמרא ש“שבויים“ שאומר ר"ל מין הראשון. אין הכרח לזה; נטושים כולל כל שלקחו אותו בעל כרחו, ולא על כל שבוי נשמע שהוא מת, אלא מוכיחים שכן אמר ממה שאין לו חידוש אחר, שאין לומר שאומר שהוא עמו שבוי שלא שמעו בו שמת, שאם כן רק אומר שנטושים כנטושים. ותו"ת.
* לט.
** דוקנים -
עיין במש"כ ”שנתמלא….“ מקור לזה הוא לשון ”דוקנים,“ שהוא מלשון ”זקן.“ לולי רש"י, היה אפשר לומר שאינו מלשון ”זקָן,“ אלא מלשון ”זקֵן.“ ותחשב.
ויש לדון אם שיעור שאומר רש"י הוא דווקא או לא. גם יש לדון אם זקן הוא זקן תחתון או עליון. נראה לבאר שלרש"י נראה שהחילוק בין גדול לקטן הוא שבני אדם רוצים לעזור לקטן ולא לגדול. אולי, אז, תלוי בכמה גדול נראה, ומסתמא זה תלוי בזקנו. ותחשב.
* מא.
** והא לא -
חילוק זה צריך ביאור, שלמה יהיה מה שדרכו לחסר סיבה שצריך לחסר כדי שיהיה גניבה. ותחשב.
* מב.
** שאין העין -
נראה שרש"י סבר שיש שום חילוק בין שני מאמרות אלו, שביאר דרשה חלוקה להם. צריך ביאור מהו החילוק, ולמה דרשות חלוקות מגידות חילוק זה.
** ואם צורבא -
עוי"ל שדרך של צורבא מרבנן הוא ש אין לו כל כך ממון. אז, מסתבר שצריך ממון זה להבדלה.
ודע שאף לרש"י, אין זה ואמר שמי שאינו צורבא מרבנן אינו רגיל להבדיל על יין, אלא שאם אין לו ממון להבדלה חוץ ממה שהפקיד, לא יפקיד על יין[fn:2]. ותו"ת.
* מג:
** שואל שלא מדעת -
ע‛ במש"כ. יש להעיר שאולי רבא לא אמר כן מפני שרוצה שיהיו רבנן אומרים כך, אלא מפני שסבר שאין דבר אחר שיותר מסתבר לומר שבו חולקים. אם כן, היה לומר שהראיה הוא שמסתמא סובר כרבנן כיון שהם רבים. יש לדון אם זה בעיה, שאולי רבים חולקים על משנה כאן, וסוברים שלא חלקו. רק קשה אם יאמר כן רבא מדעתו. ותחשב.
* מג:
** אקיף -
כל מהלך- יש לדון אם בא לפרש שכך היא הלשון (ר"ל, מודיע שכל לשון מקיף פירושו הוא שהולך בדרך יותר ארוך), או שרק מבאר לנו שכן ההכרח, שמקיף ר"ל לסבב, ואם מסבב, ולא הולך ישר, הוא דרך ארוך. נראה שאולי (ולא מוכרח) יהיה הוה אמינא לארוכה וקצרה, אם נחשב הקפה או לא.[fn:3].
* מז.
** לא שנו -
בא לומר שלא תימא שמחלקת זה קאי על דין של פחות משווה פרוטה. ויש לדון, אגב, בדין פרי פחות משווה פרוטה.
* מח.
** אין רוח חכמים -
עיין במקום אחר שפירש רש"י שהוא שאין רוח של חכמה נוחה הימנו. ועיין בשיח שי שדן בזה (ומביא ראיה ממקום שאומר, ”ואותם חסידים אין רוח…“ או כעין זה).[fn:4]
** בדיק -
עיין במש"פ. א"כ אין לגרס ”אשכח.“ ושו"ר בהגהות וציונים בעוזו הדר (מביאים מרש"ש ורמב"ן).
* נ:
** ומחזיר אונאה -
צריך ביאור ל"ל אמר שסובר שמשנה הוא כרבי נתן (עיין לקמן, שדן גמרא בזה). יש לומר שרבא לשיטתו אומר שהוא שיטת רבי יהודה הנשיא (עיין שם).
ויש להעיר שמחודש הוא שרבא פוסק כרבי נתן, כיון שהוא דיין, נגד סתם משנה.
* נא.
** מבעל הבית -
עיין במה שמפרש רש"י. לולי זה, היה אפשר לומר שחלק מן האיסור של אונאה הוא שהמוכר נתייקר יותר מן הצורך[fn:5]. כאן, אינו נתייקר כפי שומתו, שהיה זה חשוב לו אותם דמים (ומה שחשוב לו הוא חשוב, שהרי דנים בחסרון שלו). ותחשב.
יש לדון אם רש"י סובר נגד זה מחמת שסובר שאין מה שחשוב לו חשוב או שאין חלק מן האיסור שמוכר נתייקר יותר מן הצורך. ותו"ת.
* נא:
** שאין בו -
ומקח טעות נמי- אינו כל כך ברור לאיזה פסול מכוון, שאינו כל כך ברור על מה מכוון להוסיף. יש כאן שני פסולים על המכירה:
1. הוא אונאה.
2. הוא נגד תנאו (שהתנה שאין אונאה).
יש לדון איזה אומר רש"י שהוא מקח טעות, שמעניין לקרוא לשום אחד מקח טעות, שלכאורה, אין תנאי מקח טעות, ולכאורה, אם אונאה היה מק"ט, שניהם יכולים לחזור בו. ותחשב. ואולי צריך להוכיח שהוא מק"ט על ידי חזרתו. ותחשב על זה.
אולי מוסיף רש"י שכאן יש עוד בעיה של מק"ט, וברוב אונאות וכדומה אין בעיה זה, שעל כל פנים, חושש שהוא אונאה, אבל כאן, שחשב שבוודאי אינו אונאה, מק"ט הוא. אז, לא דן בשום אחד משני הבעיות שבארנו. ודחוק.
* נג.
** גזירה -
צריך להעיר שלרש"י (במה שבאר פשט בדבר שיש לו מתירים), ענין דיון זה הוא רק איזה קולא יותר טוב להקל. לר"ן, הענין יהיה אם יכול להיות היתר ממש. ותחשב.
* נה.
** והטענה -
יש להעיר שלכאורה זה מחלקת רב ושמואל בשבועות. ותחשב.
** המוצא -
עיין לעיל, שחולקים מהו המקור לדין זה. ואולי שייך למש"א גמ‛ שהוא אף אם זל (וצריך לעיין לעיל).
* נה:
** האוכל -
היה אפשר לומר שמיירי רק באכילה, ומזכיר אותם חמש לחמש שאמר, ואחר כך מזכיר עוד ארבע אגב. מוזר שיהיה מיירי רק באכילה.
* סו:
** אף משבאו -
דאין אדם מקנה- עיין במקום אחר שרש"י מפרש שחולקים בתוך דעת רבי מאיר. אף כאן, אפשר לומר כן, וחולקים אם אדם מקנה דבר שלא בא לעוללם כזה. דחוק, שלשון שאומר גמרא על רבי מאיר בכמה מקומות הוא שאדם מקנה מה שלא בא לעולם. ויש להעיר שגמרא ביבמות (צג) כמעט אומר שר"נ אומר שא"א מקנה דבר שלא בא לעולם. ועיין שם. אז, אינו נראה שיש ראיה מרש"י זה.
** ולא בלאות -
צריך ביאור למה הדין הוא כן אף בבלאות שהם בעין. לכאורה, על אותם בלאות יהיה דין מקח טעות קיים, ולא מחילה. לכאורה, החילוק בין ציורי מקח לציורי מחילה (לא באתי עכשיו לבאר סיבת החילוק בדין, אלא לבאר הגדרת הציורים) הוא שמקח טעות הוא בדבר שהוא עדיין בעין, ומחילה בטעות הוא על דבר שאינו עוד בעין, אלא שצריך לשלם דמיו.
שוב הבנתי שאי אפשר שזה ההגדרה, שאם כן, אין אונאה קשה, שאולי הממון הוא עדיין בעין. שוב הבנתי שזה לא קשה, שחברו קנה הממון, שרצה לתת לו, ורק לא מחל על לקיחתו כיון שזוכה ליקח אותו בדיני אונאה, ולא יבטל המכירה. על זה, הוא כאילו אינו בעין, שענין בעין הוא שחפץ שלו הוא ביד אחר. כאן, אינו כן, שחברו קנה חפצו, והוא רק יכול לתבוע אותו חפץ. ותחשב על זה.
* סז:
** כגדולים -
לא הבנתי מה אומר רש"י, שלכאורה, כולי עלמא מודו שזה אבק ריבית, אלא שלכאורה סוברים שלא מוציאים אבק ריבית. ליתומים, מוציאים אבק ריבית. ר"א לא מוציא אף ליתומים. ותחשב.
** אין בעל חוב -
ערב- זה, לכאורה, נוגע לסוגיית שעיבוד ולסוגיית ערב.[fn:6]
* סט:
** אין מקבלים -
עיין במה שפירש. גם נקרא כן גבי כתובה. יש לדון אם הוא מפני שהגדרים שווה או שאף שם דרכו היה בצאן.
* ע.
** כופרא -
זפת- לא מבאר מה שייך זה ללשון כופרא, אבל מסתמא מילת כופרא וזפת הם שווים. (ויש לציין לבראשית ו-יד.)
* עג:
** והא -
צריך יבוא רמ"ה לנו אם הקרקע נגזל, שהרי  לוקחים הפירות שכבר נגזלו. ותחשב.
* עה:
** אבל לא -
גם היה יכול לומר שמחשיבים כל ימי רביעה ל"קטן" ושל גריד ל"גדול,” ונמצא שמשמלם ביום גדול ליום קטן. ונראה שאי אפשר, שאם כן יהיה בעיה רק אם משלם ימי גריד. משנה לא משמע כן (ויש לדון).
* עו:
** אי סייריה -
רש"י מפרש שכל זה קאי על ראיית הפועלים. גם היה אפשר לפרש שקאי על ראיית הבעל הבית, ואומר שאם ראה אותו אתמול, והיה טוב, אז הוא אנוס, והפסידו הפועלים, ולא צריך לשלם. אבל, אם לא ראה אותו ארץ, הרי פשע, ומפשיעה זה הפסיד את הפועלים. אז, חייב לשלם. ותחשב.
* עז:
** חמרא -
חמור- צריך ביאור מה לנו בזה (למה מניח שאינו יין, ומה לנו אם אינו יין).
* עח.
** מפני רעתה -
שלא יחזור- לכאורה, לא צריך לכך, שיש לומר שהוא רק מפני שרוצה ממון, אבל אינו מעכב לו.
* פ.
** תרוויהו -
מוטל בפסק- קשה, שאז כל אחד יהיה פטור. אולי אומר כסומכוס שאומר שחולקים. לולי רש"י, היה אפשר לומר שמסתמא היה בעיה של שניהם ביחד. נראה שזה לא מסתבר, שאיך נדע כן.
* פ:
** מחיקתין -
שעורים שהתליעו- לכאורה, הפשט בזה יהיה שאז הם יותר דאנ"ס (נופח שלהם יותר קטן לפי משא שלהם).
** שומר שכר -
מצווה- קשה, שלכאורה, כל שומר עושה חסד. גם קשה, שאין מצווה בלקיחת משכון, אלא בשמירה. ותחשב.
* Footnotes
[fn:1] כאן כתבתי על נייר.
[fn:2] אולי זה סימן שהוא עני, ואולי הוא טירחא להוציא מן הנפקד.
[fn:3] לא מוכרח, שלראשון, יש לומר שאינו רק היותר ארוך, אלא היות ארוך בזמן, ולשני יש לומר שהקפה לא רק ר"ל לסבב כלום, אלא לסבב על הדרך הכי טוב לו. ותחשב.
[fn:4] שוב מצאתי שהרש“י שציינתי הוא בב"ק (צד:).
[fn:5] לכאורה, הענין בזה הוא שאם צריך לזה, התיר לו תורה, אבל אם לא נפסד אותו ממון, לא רשאי להפסיד חברו אותו ממון.
[fn:6] למשל, יש אומרים צד לענין דין ערב שהוא כאילו הערב קבל את הממון, ואז אף הוא חייב לשלם. זה אי אפשר לומר, שלכאורה אינו כן גבי קרקע. ותחשב.
