* ב.
** ושאין לה שלשה דפנות -
יש שגורסים כאן שלשה. יש להעיר שהיה אפשר לדון, אם הייתי יישיביש, אם דופן הקטן השלישי הוא מפני שצריך להיות שלש דפנות, ורק צריך דופן קטן, או שצריך שני דפנות, אלא שצריך עוד סעד, והוא אותו טפח. אם נגרוס לשון שלשה כאן, נראה כצד ראשון. גם אם לא נגרס כן, נראה לבאר כן, שהרי היה לו להזכיר פסול זה (של "אין לו טפח סעד"). ויש לדון, שאולי לא הזכיר את כל הפסולים. ותחשב.
* ב:
** דברי הכל -
כיון שסבר שרק דברי רב הונא עושים שכל, קצת צריך ביאור מה היה ההו"א שלא לומר כן. ותחשב. ודע שלפעמים מצאנו גמרות שאינם כסדר, והאו שסוגיה ראשונה מניח כמסקנא של סוגיה אחרונה. ותחשב.
** חינוך -
נמצא שאשה מצווה על חינוך. ודע שהיתה גיורת, ויש לדון מה היתה יחסה לבנים אלו. לכאו', צריך לומר (ולא קשה שגמ' ידע כן) שנולדו לה אחרי שנתגיירה (שרק אז מיוחסים לה). ויש לדון, שכיון שחינוך הוא דין דרבנן, אולי חייבו אף שלא, באמת, מיוחסים לה. ותחשב.
* ג.
** בניה -
קצת קשה, שמתחילה הביאו ראיה ממנה, ולא מבניה. ותחשב.
** פוסלים -
אולי צריך לעיין בגמ' בחולין בביאור לשון פסול. (כוונה שלי לגמ' בחולין במח' בית שמאי ובית הלל במה יכולים לשחוט.)
* כא:
** רבי יהודה -
רשי כ' ששיטת רבי יהודה הולך לטעמו, שסבר לעיל שסוכה צריך להיות דירת עראי. באמת, אמר כן גמ' לעיל (בתחילת פרק זה; וצריך לע' בלשונו בתחילת פרק ראשון), אבל מרבי יהודה רק רואים שיכול להיות דירת קבע. (יש לעיין בזה, שיש לומר שאם לא דורשים שצריך להיות עראי, זה יהיה מפני שיש הכרח אחר, והאו שצריך להיות קבע. ותחשב.) כאן, צריך להיות שרבי יהודה סובר שסוכה צ"ל קבע.
** יש קבע -
נמצא שרבי יהודה רק סובר שצריכים קבע לסיכוך, ולא שצריכים קבע לדפנות. לכאו', זה מפני שהסיכוך הוא חלק העיקרי של הסוכה, כמו שאמר רשי לעיל.
* כב.
** חבוט רמי... טפח -
אם נבאר את זה באופן פשוט, נראה שהביאור יהיה ככה. חלק מן הסיבה שאומרים חוט רמי הוא שקרק' של מקום של דבר הוא גם כן על מקםו שהוא תחתיו. (יש שני דרכים לומר את זה, ואיני יודע אם הם שונים. דרך ראשון הוא שיש לו קרק' של מקום שהוא אותו מקום שתחתיו, מפני שהוא על גבו, ומפני שהוא יכול ליפול שם, והשני הוא שמפני הראשון או מפני מה שגורם לראשון, יש לו יחס לאותו מקום. ותחשב.) אבל, דבר חשוב יש לו גם כן קרק' יותר חשובים. (לכאו', זה פשוט מן הסברה. הרי, בני אדם מקפידים יותר – ויותר תוצאות יוצאות – מקרק' של דבקים חשובים. ותחשב.) כדי לומר עליו חבוט רמי, צריך להיות בו קרק' חשוב שמקומו הוא תחתיו. זה נמצא רק בחפץ חשוב. רק חפץ שהוא רחב טפח חשוב. ותחשב. (וא". אם הוא חשוב גם יש קרק' חשוב לדחות שהוא מקום שהוא בו ממש. ותחשב. ויש לדון, שלא ברור לי שדבר צריך להיות לו רק מקום אחד, שאולי יש לו שני מקומות, ואין צורך לדחות אותו קרק'. ותחשב.)
** אבל אין ביניהם פותח טפח -
לכאו', רצה לומר אינם רחבים טפח (אלא שהם כנגד הפתח, ואז גמ' אמר סימן לזה). ק"ק למה אמר סימן, ולא רק אמר הסיבה. ותחשב.
** שצילתה -
לכאו', המקור שצריך להיות צילתה מרובה מחמתה הוא שסכך צריך להיות דבר שסוכך ושמור. אם חמתה מרובה, אז אינו שומר כל כך. יש לציין למה שאומר רשי בתחילת המס', שאומר שאז בחמה מבטל את הצינה, ונמצא שלא מסכך כלל. ותחשב.
** המעובה -
משמע שאם הוא יותר מעובה מזה, לא כשר. עיין בגמ' שאין זה נכון. (אולי נקט הציור שכשר לכ"ע, ואולי נכון שיותר מעובה מזה פסול, וכשאומר "כוכבים," מכוון לומר כוכבי חמה.) הצד לפסל סוכה מעובה הוא, לכאו', שאז אינו עראי, אלא קבוע. זה יהיה שייך למחלקת תנאים, אז, כמה קבוע יכול וצריך להיות. ותחשב.  גם אפשר שהוא גזירה שמא ישב בבית. (עיין בלשון רשי בע"ב, שהוא ש"אין זה דומה לסוכה." אולי זה פסול חדש, והמקור לו יהיה שסתם סוכות אינם כן, ואז כשאמרה תורה לשבת בסוכה, לא כוונה שיהיה סוכה כזה. יש לדון מהיכי תיתי שזה קרק' חשוב, אבל נוכל לומר שזה נודע מן הסברה. ותחשב.)
** תני תרתי -
יש לדון אם מכוון לומר שיש שינוי גי' ביניהם, ששמואל שונה "ושצילתה," ורב תני "שצילתה," או שרק רצה לומר שיש שינוי בביאור המשנה, שלשמואל, כשאומר "ושצילתה," בא לומר עוד ציור, ולרב, כשאומר "שצילתה," בא לומר עוד קרק'. ותחשב. אפשר שסתימות רשי משמע כצד שני. ותחשב.
** שמואל -
נמצא שמה שרואים אותו מהני גם לראות צל במקום חמה (אף שזה רק תוצאה מן הראיה). אבל קשה, שבוודאי לא אומרים כן, שהרי אז כל סוכה שצילתה מרובה מחמתה יוכשר מחמת לבוד. (אין לומר שהוא כשיש אויר יותר משלש, שאז יפסל מחמת אותו האויר. ותחשב.) אולי כאן מדובר בשצילתה מרובה מחמתה, וצריך חבוט וכדומה כדי לעשות שיש סיכוך אחד שהוא צילתה מרובה מחמתה, ולא שני סככות. תחשב על זה. לא משמע כן מן הגמ', שאומר ששמואל תני שנים. לזה, היה לו לומר ששמואל תני אחד, שראשון צריך שני, ודין של שני כבר נלמד מראשון. ותחשב על זה. (אפשר לומר שכאן סומך על חבוט רמי, ואז רואים אותו כצל, ורק לא רואים אותו בלבוד. יש לדון מהיכי תיתי לחלק. יותר מזה, קשה שאביי אומר שסומכים כאן על לבוד. יש לדון, שאולי אומרים חבוט רמי אף בדבר קטן אם הוא בתוך שלשה טפחים. מחודש לומר כן. ותחשב.) עיין ברש"י ד"ה אמרינן חבוט רמי, שכמעט בפירוש אומר נגד צד זה.
** רב... שמואל -
כמו בכל מקום, יש לדון אם רב חולק על שמואל גם בדין או רק בביאור המשנה. (וא"ת איך אפשר לחלוק עליו, שנודע לנו כלל של לבוד וכלל של חבוט רמי. ויש לומר שלא נודע לנו שיכולים לאומר כן על חמה וצל. עיין לעיל, שדנינו בזה, שאולי אין זה נכון לשמואל. ותחשב על זה.
* כג.
** דירת עראי -
מן הגמ' משמע שצריך להיות דירת עראי או צריך להיות דירת קבע. אין שום צד שיכול להיות זה או זה. (לכאו', מן הסברה נאמר שצריך להיות דירת קבע, שהרי צריך לדור בו, וזה משמע דירה חשובה. הסיבה שלא נאמר שצריך להיות דירה קבועה הוא שנדרוש קרא לומר שצריך להיות דירת עראי. נמצא שמובן למה צריך להיות או זה או זה. ותחשב.)
** דירת קבע -
יש לדון מהיכי תיתי שזה השיטה של רבנן גמליאל, שאולי סובר שצריך להיות ראוי לשבעה ימים, וזה לא ראוי, שמסתמא יפול ברוח (כיון שזה מצוי בים). ותחשב. באמת, לקמן משמע שכולי עלמא מודו לזה. הרי, צריך להיות שרבי עקיבא חולק. ויש לדון, שכאן לא מוכרח שלא יהיה ראוי, שאולי יוכל להתשמש בו בשבעה הימים. אבל, עדיין יכול להיות שר"ג יחלוק מחמת זה.
** רוח שאינה מצויה -
יש שני גי' כאן. נראה שאם גורסים "רוח שאינה מצויה," הביאור יהיה ככה. כוע"מ שאם הוא ביבשה ולא עומד ברוח מצויה, לא כשר, ושאם הוא ביבשה ולא עומד ברוח שאינה מצויה שכשר. רק חולקים כשהוא בים, ולא עומד ברוח שאינה מצויה, שהרי בים מצויה היא. אם גורסים "רוח מצויה," הביאור הוא שכוע"מ שלא כשר אם לא עומד ברוח שמצוי ביבשה, ושכשר אם לא עומד ברוח שאינו מצוי ביבשה, וחולקים ברוח שמצוי בים, שהוא בין שני הרוחות. לצד זה, גמ' לא מזכיר דבר אחר שנראה מן המשנה שהוא נכון, והוא שרק חולקים כשהוא גם על הספינה. ותחשב.
** שמה סוכה -
הייתי אומר שזה משמע שזה לא רק סוכה פסולה, אלא אינה סוכה. (בכ"מ דנים בזה, ובדרך כלל איני רואה בזה שום נפקא מינא.)
** מיתה לא שכיחא -
מעניין שלא דוחים שיש חזקת חיים לו, ולא נניח שימות. אפשר לומר שזהו כוונת הגמ', או שהיה יכול לומר כן, אלא שיש לו תשובה אחרת, אבל לא משמע כן. אפשר לומר שאין לו חזקת חיים, כיון שלבסוף ימות. וא"ת אם כן נאמר כן גם גבי אדם. ויש לומר שאף על פי כן באדם אותו שינוי כל כך חשוב עד שלא נניח שקרה. ותחשב על זה. (עיין בערוך השולחן בהלכות ציצית שמביא מח' אם נאמר שיש לציצית חזקת כשרות כיון שלבסוף מס' יהיו פסולים.) עיין בגמ' לקמן, וע' במה שנכ' עליו.
** דירת עראי -
בכמה מפסולים אלו, יש לדון אם הם פסולים בישיבה או בסוכה.
** שמא ימות... -
קשה למה לא חוששים לזה בסוכה שנסמך על גמל, שגם שם נחוש, ולרבי מאיר לא יוכשר להיות סוכה. צריך לומר שאף אם ימות הגמל, ואף אם יברח, הסוכה יישאר שם. ותחשב.
קצת קשה למה חוששים שימות או שיברח, ולא חוששים לרוח מצויה שבים. אפשר לומר שסוברים כרבן גמליאל, אבל לא נראה כן, שגמ' לא תולה אותם. אפשר לומר שהחשש הוא שימשיך לשבת שם, כיון שלא יכיר ששום דבר קרה לו, או שיכיר מה שקרה לו, ולא יכיר שהוא פוסל את הסוכה. אבל, אם בא רוח מצויה של ים ופסל אותו, בדר"כ יפסול אותו בדרך מאד ניכר, ולא נצטרך לחוש שלא יהיה כשר. (לולא זה, היה אפשר לומר שלא רוצים שיבנה אותו כן כיון שבדר"כ יביא לידי אונס, שלא יהיה לו סוכה, ויבטל מצוות ישיבה בסוכה. ותחשב.)
** בידי אדם -
מעניין, שרבי יהודה הוא האומר שאהל צריך להיות בידי אדם (ורבי מאיר אומר שמחיצה צריך להיות בידי אדם). ותחשב. בשניהם, יש לדון אם הענין הוא שנחשב כיון שנעשה בכוונה או שנחשב כיון שנעשה על ידי בן אדם (ואדם הוא חשוב). ותחשב.
** מיתה -
מעניין שחושב גמ' לתלות שבירה (ואף כשלא תולה אותו, הוא רק מפני שיש אפשרות של שומר), מיתת אדם, ומיתת בהמה ביחד, שלכאו' מסברה אינם שווים. צריך לומר שהוא דיון בעניני חזקה או כדומה. (עיין לעיל שבארנו שיש סברה לחלק; כנראה גמ' לא מחלק.) ותחשב על זה.
* כב:
** ובראש הספינה -
עיין במה שבאר רשי למה יש יותר רוח שם. אינו נראה שזה נכון; בדרך כלל, אין הים יותר גבוה, ומוכרח כן, שאי לאו הכי, ילך חוץ לגדרותיו. אלא, הענין הוא שהמים גורמים לרוח שיבוא. ועיין בזה.
* כו.
** משום -
לית להו- יש להעיר שאף שאין להם דין של משנה שלנו, יש להם מקצת דין של עוסק במצווה פטור מן המצווה, שסוברים שמותר להשתכר, אף שזה יבטל אותם ממצוה. (אף רבי שילא לא מבאר רשי שחולק על זה. אבל, לא נראה שזה מוכרח מן הגמרא.) כנראה, דורשים מקרא של קרבן פסח. (ויש לדון, אז, אם מותר להשתכר באמצע זמן קריאת שמע, שכבר התחיל זמנו, ואז לא כל כך דומה לשל פסח, אבל אינו מבטל בידים כל זמן הקריאה, אלא במקצתו הוא אנוס, ואז הוא דומה לדין פסח. ותחשב.)
** הולכים ביום ובלילה -
מה שיוצא מזה הוא שכל זמן שהוא הולך, פטור מן הסוכה. קצת צריך ביאור למה לא רק אמר כן.
** והתיר -
כנראה, היה רשב"ג, הנשיא, שולח את שאלותיו לרבי יוסי. עיין בגמ' בב"מ שמזכיר כמה ענו היה. אבל, לאידך גיסא, עיין גמ' בסנהדרין שאני חושב שמשמע שלא היה ענו כל כך (צריך לע' שם אם מדובר ברשב"ג או ברבי), וכן בגמ' בסוף הוריות.
** משמשיו -
יש לדון למה הם פטורים. אולי הם עוסקים במצווה, שהם כמבקרים חולה. גם אפשר שהם תמיד עמו, וכעין דירה אומרים שיכנסו. אבל, אז קשה למה לא נאמר כן גם במצטער. אפשר שרק דרכם להיות תמיד עמו כשצריך להם, כמו אם הוא חולה. כמו כן, אפשר שהם מצטערים כשהוא חולק והם לא קרובים לו לרפאות לו.
** והו"ל -
יש לדון אם רצה לומר שלפעמים אוכלים אותו בני אדם והם מחשיבים אותו לסעודת קבע או שלפעמים אוכלים אותו בני אדם לסעודתם, וממילא נחשב סעודת קבע. (החילוק הוא איך לקרוא את הלשון.)
** במוסר... -
ק"ק למה לא יזכיר היתירים אלו כשאומר ששינת עראי אסור. ויש לדון.
** אין קבע -
אם רצה לומר שאז כולו קבע, קצת קשה לשון "אין ישנים שינת עראי."
** תרתי או תלת -
עיין ברש"י. הביאור לזה הוא שמלא בית הבליעה הוא ביצה, ואז שיעור שאומר רשי שווה למה שאומר הגמ'. ותו"ת.
** דפריס -
מרש"י יוצא שהוא כשנתן אותם סמוך לראשו, ונתן עליו סודר. אז, יוצא שכשאומר "על ראשו," אינו דווקא, ורק רצה לומר כל זמן שהוא עליו או שאין עליו סודר. נקט ראשו לומר שאף שם מותר בעראי. ותחשב.
** לא קבע ולא עראי -
לפי מקצת המהלכים לעיל, יכול להיות שהחילוק הוא אם יש מי או מה שיעורר אותו או אין מי שיעורר אותו.
* כו:
** וחכ"א -
צריך ביאור מה שייך מש"א חכמים למש"א רבי יעקב (שהלשון משמע שיש יחס ביניהם).
** כרב
- דממנו למד- כעין זה, עיין ביבמות (צג?) בענן דבר שלא בא לעולם.
** כרב
- משמע שרבה היה תלמיד של רב, ולא רק תלמיד של תלמיד של רב.
** אם בא להחמיר -
גמ' אומר שהחידוש הוא שאין בו יוהרא. יש להעיר שאין הסיפור מגלה כל כך, שמספר על אנשים שהיו, באמת, גדולים וראויים לכך, וידוע שהיו גדולים, ולא נראה שיהיה יוהרא כל כך אם מראים שהם גדולים. תחשב ותבין.
* כז.
** מכאן ואילך -
עיין במקור לזה (מובא ברש"י). יוצא מזה (ואולי כל "דבר היוצא מן הכלל" הוא כזה) שלומדים בו דין ממה שאינו בכלל שאר דברים. אחרי זה, לומדים אותו הדין לכל אותם הדברים. זה קצת מעניין. אם מפרשים את הפסוק שאומר שהם בכלל והוא לא בכלל להיות מדבר על דין זה, אז אי אפשר ללמד להם, שכבר אמר שהם בכלל. ותחשב על זה.
** אי בעי -
מעניין, שהרי נמצא שלא ישב כעין דירה, שהיה צריך לאכול. צריך לומר שאומר תורה שלא צריך דירה כעין ישיבה בלילה ראשונה, על כל פנים בפרט זו. אולי לא צריך אותו כלל, ומתאים עם זה שיטת הפוסקים שצריך לשבת בסוכה, אף אם מצטער הוא, בלילה ראשונה.
נראה שאפשר לדחות כל זה על ידי מה שחוקרים בחיוב זו, אם הוא חיוב לקיים מצוות סוכה (או לאכול בסוכה) או חיוב לאכול. לצד שני, יש לומר שאף ביום חול היה אוכל בסוכה אם היה חייב לאכול. ותחשב.
** חזר -
יוצא שאם יש חיוב מצוות סוכה לשבת בו ביום ובלילה, אינו משלים אם אוכל חוץ מסוכה אחר כך. אבל, משלים את החיוב לאכול לילה ראשונה. משמע שאין זה חיוב לאכול בסוכה, אלא רק חיוב לאכול, וכיון שהוא לילה ראשונה, צריך להיות בסוכה.
לולי פי' רש"י, הייתי אומר שלא קשה לו שיכול להשלים חוץ מזה, שזה רק תשלומים, ולא קיום. מה שקשה לו הוא שרבי אליעזר רק מדבר בי"ט ראשון, ולא בסעודת כל יום ויום.
** שמנ"ע -
ק"ק למה נקט שמנ"ע, ולא שאר ימי סוכות. נראה שזה פשוט, שאז הוא יושב בסוכה (ועוד שהוא אותו היום טוב). רק מה שיכול לתקן אותו בשמיני עצרת הוא חידוש לו, וזה בא לחדש. (אף אם היה צריך לחדש דין תשלומים בשאר ימי סוכות (וצריך לדון מה סוברים רבנן בזה), אמר את החידוש היותר גדול.)
** אם השלים -
משמע שזה בדיעבד. אבל, לשון גמ' משמע שהוא לכת'. ותחשב.
** יצא -
מעניין לומר לשון יציאה על תשלומים. נראה שלא בהכרח רצה לומר שיצא את עיקר החיוב, אלא אולי רק רצה לומר שיצא את התשלומים, ואין עוד חיוב להשלים. ותחשב. גם אפשר שמדבר (כמו שנראה מגמ' לקמן) בדין סעודה שנית בשאר ימי סוכות, ומניח גמ' שיכול להשלים בכל מה שיכול לצאת בו בסוכות עצמו.
* כז:
** שחוזר ובונה -
נמצא שאף שנפלה, נחשבת אותה סוכה. (שו"ר שגמ' יאמר שזהו החידוש. עיין במה שבאר רש"י במס'.)
** עשה סוכה הראויה -
לשון הגמ' ק"ק, שסובר יותר מזה, וסובר שצריך לשבת בתוכו שבעת ימים. ותחשב.
** לא חדש היום -
לפני כמה שנים, הבאתי ראיה מזה שכשאומר "חייב איניש" לא בא למעט נשים. (זה נוגע למה שהיה פלא לי למה אין נשים מקיימות עד דלא ידע בפורים.) שוב נראה לי שאולי מכוון לומר רק אנשים, והראיה הוא ממה שהיתה ענין לה ללכת, שמסתמא הוא מפני שהיה מצווה שהזמן גרמא, וקיימה אותו באופן של לא מצווה ועושה. (אין להקשות מהי"ת שיש שום חיוב, שכבר נראה שאפשר להקשות כן. צריך לומר שמס' יותר שזה חיוב משזה ענין, שלא מצאנו הרבה ענינים בתורה.)
אגב, אמר לי ב.ל. ששמע מרש"ש שליט"א שענין זה הוא רק בנביא, שהענין הוא ללכת למי שיש לו הרבה השראת השכינה. גם סיפר לי שפעם בי"ט מ.ר. שאל לרש"ש שליט"א איפה הוא, כיד לקבל פניו, ואמר לו רש"ש שליט"א שהוא בסין.
* כח.
** לא קדמו -
כמובן, צריך ביאור מה קרה כשהיו שניהם ביחד (כמו כשהיה ר"א לומד אצל ריב"ז).
** אסמכתא -
נמצא שלא צריך שבאמת יש קצת משמעות מקרא כדי להיות אסמכתא, אלא יכול להיות אס' גם אם אין שום משמעות ממנו, ואף משמעות להיפך. (יש לדון בזה, שאפשר לומר שיש משמעות לכאן ומשמעות לכאן, וגמ' יודע שבאמת אחד מן המשמעויות נכון. כן נראה, שלא פשוט לגמ' איזה הוא עיקר הדרשה.)
* כח:
** תשבו כעין תדורו -
אביי הולך כאן לשיטתו, שגם בקידושין מנסה לחייב מחמת חיוב אחרים. (כמובן, יש להסתפק אם, באמת, מכוון לחיייב בעזרה למי שחייב או שזה סימן לחיוב ממש.)
** תוספת עינוי -
נראה לי לדון אגב – ולא נראה שצריך להיות נוגע לכאן – מהו ה"תוספת," אם הוא שמוסיף על זמן עינוי, או שמוסיף על עינוי שלו, כיון שהוא יותר רעב (שהיה יותר זמן מאכילה האחרונה). ותחשב. (יהיה, אולי, חילוק מזה לענין איזה זמן הוא מהנה, זמן תוספת או יה"כ. ותחשב. באמת, כעין זה יש לחקור בכל רגע של יה"כ, אם מה שאינו אוכל הוא מחמת עצמו או מחמת רגעים שלאחריו. ותחשב. אפשר לומר שהוא מחמת שניהם.)
** כל... אסמכתא -
צריך ביאור למה לא דן גמ' מה, למס', לומדים מכאן. יותר מזה, צריך ביאור מה לומדים מכאן. (אולי לא מוכרחים אנו לדרוש מכל "כל," ורק דורשים אם יש דרשה. אולי אין דרשה כאן, ולא לא מבאר אותו גמ', ואולי למעשה יש דרשה, אבל לא נוהג בו קושיה של "מה נדרוש.")
** סוכתו קבע -
יש לדון מה מכוון לומר. בפשטות, אומר דין, שמגדיר איזה דברים עושה בו – עושה בו כל דברים של ישיבה בבית. נראה שגם אשפר לומר שבא להגדיר צער, והוא שלפעמים אדם רוצה לצאת מן סוכה שלו, אבל אם זה היה הבית שלו, אף שיש בו קצת צער, לא היה יוצא, שבדעתו, זה המקום שלו, זה מקום דירה קבועה שלו. אומר שצריך לחשוב כן על הסוכה, ורק אם אף על פי כן, רוצה לעזוב את הסוכה, נחשב מצטער, ופטור מן הסוכה. עיין בגמ', שנראה שמבאר אותו כצד ראשון. אבל, עדיין יכול להיות הדין של השני נכון.
* כט.
** או עד שיאור -
עיין ברש"י. משמע שפשוט שלא חייב ללכת לסוכה עד שיעור (ולא צריך להזמין מי שיעורר אותו), ורק דן אם חייב לצאת לסוכה אם יעור ולא יאור. וע' לקמן בגמ' וברש"י.
* לד:
** אמר לו רבי אליעזר -
הלשון משמע שמשיב למה שאמר רבי עקיבא. אבל, לכאו' אין זה תשובה על דבריו כלל, ואין שום צורך לומר שחולקים. אין לומר שמשיב שלא באמת הוקש לאתרוג, שעדיין נוכל לומר שהוקש ללולב, ולא מסתבר שיבוא לחלקו לומר שרק ללולב הוקש, ולא ללולב ואתרוג. (יש לדון, שאולי אז לא נלמד ממנו, שמאי חזי שנלמד מלולב יותר משנלמד מהדס או ערבה.)
** רבי ישמעאל -
קצת קשה למה מפסיק בין משניות האומרים פסולים לשנות משנה זה.
* לה.
** כתותי מכתת -
קצת צריך ביאור למה חוזר ומבאר את זה כאן, שהיה כן בשלש משניות שלפני כן. (אולי הוא מפני שיש הפסק של משנה אחת ביניהם. דחוק.)
** מעשר שני -
כנראה, אז, חולקים אם דבר שאין בו דין ממון יכול להיות נחשב "שלו." (אפשר שדן אם צריך להיות שלו, לאפוקי משל שאר בני אדם, או שמספיק אם הוא שלו שאין לאחר בעלות בו יותר ממנו.)
** סרוח בפנים -
עדיין אין מזה ראיה, שאולי מדובר בסרוח אף הסימפונות.
** דומה לכושי -
עיין במה שפרש"י. גם אפשר לומר שכושי הוא שהוא ממש שחור, ודומה לכושי הוא שקצת שחור הוא, והוא כעין זה. אם הוא ממש שחור, אז הוא שווה למין אתרוג, ולא פסול. אבל, אם הוא רק דומה לזה, אינו שווה לשום מין, ואז הוא פסול.
