* ב.
** לא פחות ולא יותר -
לשון זה מעניין, שלכאורה, היה לו לומר שלא יקרא קודם לכן ולא אחר כן.
** רבי עקיבא -
מצאנו בכ"מ שר"ע דורש אף דברים קטנים. כן דורש כאן, וכמו כן מצאנו שדורש וי"ו. כמו כן דורש "את"ים. יש לציין לגמרא סוטה (מט.) שאומר שהיה כבוד תורה בטל במיתתו, כיון שהיה דורש כל כך טוב (עיין ברש"י שם).
** כימים -
יש לציין לגמרא ברכות (ג:) שבו יש מחלקת בפירוש "כחצות,” שיש אומרים שר"ל שהוא ביום אחר בחצות, והוא כחצות של עכשיו, או שר"ל דבר אחר. נראה שזה שייך לדיון של גמרא כאן. ותו"ת.
** אלא הכי -
[
לשון אלא קצת מעניין, שמשמע שהאמור נכון, אבל לא כל כך. יש לומר שרצה לומר שכן עיקר דינו (רצה לומר, זמן שבו מצוה יתקיים
טוב), אלא.... גם יש לומר שמקיים באלו ימים מפני יחסם ליום יד. ותחשב על זה. עיין בשי"ח ש"ח על פסחים. אז, רק יד זמנו, אף שיכול לקרוא אותו בימים אחרים. ותו"ת.
כמו כן, יש לומר שמה שיד' הוא עיקר זמנו הוא שבא לזכור מה שקרה ביד'. אז, יד' היה לו להיות זמנו. ותו"ת.
** תיובתא -
נמצא שר"י איתותב רק לשיטתו, שאם אין משנה שלנו ר"ע, יש לומר שלפני זמן הוא, ור"ע (משנה) סבר כר"י.
** זמן קהילה -
צריך ביאור, שלמעשה לא כשר לבני יד’.
* ב:
** כיון דפרזי פרזי -
צריך ביאור מהיכי תיתי שדורש פרזי פרזי, ולא דורש מכאן. ותו"ת.
** לאו ישראל נינהו -
צריך לחשוב מהו קושיה זה, שי"ל שרק ישראל מיוחדים חייבים. נראה שקושיית גמ’ אומר שיודעים סיבת החיוב, והוא שהיו נהרגים, ואז פשוט שאף אלו חייבים, שאף אלו היו להם להיות נהרגים.
** כדי -
מעניין שמצאנו בכ"מ שכדי נתחלף ברבא. אם היה אדם ששמו כדי, יש לומר שהיה שום דמיון ביניהם. אם רק ר"ל "שום ת"ח,” צריך ביאור. אולי שם רבא (אבא) היה מצוי מאד, ואז מי ששמו אבא נשכח. ותו"ת.  (דיון זה בשם כדי הם שני צדדים ברש"י.)
** כיון דאית ליה פרזי פרזי -
ק"ק למה צריך שום קרא, שחי’ בין פרזים לכרכים בפירוש במגילה (וכל דיניה למדים לעיל). ואולי צריך להזכירו ללמד שאר דיניו מקרא זה.
* ג.
** ולא הוה ידעי -
צריך ביאור איך זה חלוק מ"שכחו.” אולי ר"ל שלא הודיע ה’ כלל איזה יהיה באמצע ואיזה בסוף. קשה, שנראה איזה היו בלוחות או כדומה.
** חגי זכריה -
לכאורה, חיו לזמן הרבה, ולא חי יונתן לזמן הרבה, שהרי גמרא אומר שאף ראו את רדב"ה. ותו"ת.
** עבודה שהיא חמורה -
יל"ד מהי"ת.
* ה.
** אכתי לא מטא -
ואם תאמר הרי אחר כן, קדושה ייצא. ויש לומר שיותר קל להשאר כתובה מלהיות לה לקרוא. ותחשב על זה.
