* ב.
** לאפוקי מדר"י -
לכאורה, יש יותר סיבה לומר כרבי יהודה בסמיכה, שמשם מקורו. אם כן, אפשר היה למשנה שלא לומר כמותו שם, ואז, נדע בהכרח שאין הלכה כמותו כלל, שכל דינו נלמד משם. ויש לדון, שאולי לא מניח שנדע מקורו.
* ב:
** בסוכה -
לכאורה, מביא את כל אלו אגב ה"כל" שבמשנה (שהיו ארבע שלהם). גם נראה שאפשר שדומה הא של סוכה לשן כאן, ששם מסיק שמרבה דבר שכתוב במשנה כמו כאן. אולי, אז, הובא של סוכה, וכיון שהוא הובא, מביאים את הכל.
* ג:
** אי הני -
לכאורה, אין זה לשון כל כך טובף שאפשר שרק כהנים חייבים, ואז יש מי שיחייב, ואף אי לא נאמר כמשנה, אבל רק אומר שאין מקור שיהא כן. ותו"ת.
* ד.
** כפרה -
לכאורה, אומר ששם המעשה הוא כפרה ולא אכילה. עיין במסקנת גמרא, שלא משמע שחוזר מנקודה זאת, אלא אומר שאין צריכים שיהיה לו שם אכילה. אם כן, משמע שיכול לברך ולזמן על פחות מכזית אם הוא שבע. ויש לדון, שאולי דעתו להיות שבע בטל (ויש לדון). גם אפשר שאומרים כן רק כאן כיון שקצת יש לו שם אכילה, שאכילה הוא, אלא שהוא יותר דבר אחר (שאותו דבר אחר יש לו שם היותר חשוב). ותו"ת.
** האי וכל -
ואם תאמר אין הכי נמי, וזה הקא משמע לן. ויש לומר שמקשה שכיון שכבר ידעו לנו שכן הדין, פשוט שאין צריכים זה, שנלמד מידיעת דין ראשון. יש לדון, שלכאורה, אין זה כל כך פשוט לבני אדם.
* ד:
** תפסת -
זה נגד פשט שמביא תוס’ בכ"מ שאין לו גדר אם לא המעט, שכאן יש לו גדר גם למעלה. ויש לדון. ודע שלכאורה, אין "תפסת… " צריך להיות סברה שווה בכל זמן, אבל יש לדון למה אין סברה זה לא מהני שם וזו לא מהני שם.
* ה.
** בתם -
יש לדון למה לא יהא קדושת הגוף לתם:
1. אפשר שמה שהוא בעל מום הוא סיבה שאין לו קדושת הגוף. יש להעיר שאפשר שלכן הוא שאין מקריבים תם. ואם תאמר אם כן לא יהא חמור ממקריב חולין. ויש לדון, שאולי אינו . גם יש לומר שבעל מום אינו אף ראוי לקדושה.
2. אפשר שחלק מן הקדושה בא ממה שעומד להיקרב, וקרי אין בעל מום יכול להיות נקרב.
עיין לקמן שמשווה דין אדם לדין בעל מום. יש להעיר שפשוט הוא שאדם לא הובא לקרבן, אבל אינו פשוט שפסולו שווה לבעל מום (יש לדון, שאולי פסולו דומה, שאולי כל פסול בעל מום הוא שאינו אותו מין, שיש חילוקים חשובים בינו ובין מה שכיוון לו תורה כשאמר "פר,” שהוא פר רגיל.). אם כן, אולי אינו כל כך פשוט להשוות את דינם, אלא אם כן נאמר כצד שני (שאז פשוט שששווים הם , ששניהם אינם נקרבים לקרבן).
** הקדיש שדה אחוזה -
נראה שאפשר שהענין הוא שצריך חילוף בין מה שנותן להקדש למה שנוטל. אז, צריך להיות "אותו דבר.” בדרך כלל, נותן דבר שנחשב אותו דבר כיון ששם שלו של שוויותו שווה. חידש תורה שי לקרקע שם על פי מעות שרגיל להיות שווה (מסתמא, כן הוא), וזה דין בית חומר שעורים.
יש להעיר שיש עוד חידוש במה שאי אפשר לפדותו בשוויו. ותו"ת.
** דמים -
צריך ביאור מהו הצד שיפשט קדושת דמים אם הוא תם, שמה שקדוש קדושת דמים (אבר אחד) לא נקרב, וכיון שרק קדושת דמים, לא נתפשט. וצריך ביאור.
* ה:
** מזבין -
ואם תאמר אף זה לא חל, שלא בא לעולם. יש לומר שר"מ לטעמיה סבר שיכול אדם להקנות מה שלא בא לעולם. ותו"ת.
* ו.
** אי אמר -
יש להעיר שכרן לא יכזור כיון שלא יכול או כדומה, אלא מפני שלא ירצה, שסובר שבית המקדש רע. אולי מחודש שאין מחלקים.
** אי אמר -
מעניין, שאם לא רוצה, יאסרו, ומה לו לומר שייתן ולא ליתן. יש לומר שנראה יותר רע אם חוזר על דיבורו שמתירו, מה שאין כן אם לא נותן. יש לדון.
** עלי -
צריך לדון מה לנו בכל זה, שלכאורה אמר רשי שהצד שיהא מותר הוא שמניחים שהתנה כשקדשו. אם כן, מה לנו כמה הוא הבעל.
* ז.
ממונו של- יש להעיר שממיתים עבד הממית, ואף שהוא ממון אחר.
** חד גוף -
יש לדון אם ר"ל שאף עובר חייב מיתה (שאשה חייבת, ועובר חלק ממנה) או שאין עובר חשוב, שרק חלק ממנה, ואין בעיה בהרגתו.
* ח:
** פתחה -
יש להעיר שאין הענין מה פתחה, אלא כמה זמן ראתה. ותו"ת.
* ט:
** רבי -
מעניין שיהא אחד חולק על רבי, שכתב את המשניות, בביאור המשנה. ועיין בבבא בתרא (קלא.).
שוב הבנתי שלכאורה אינו קשה, שיש לומר שלא אומר שסבר כן רבי בביאור המשנה אלא שסבר כן בדין. אז, אין בעיא, שמצינו כמה סתמי נגד שיטת רבי.
** תשעה -
משמע שאף שמשנה אוסר את זה, מותר אם שנה שלפניו לא היה רגיל. כן נראה מסברה. ותו"ת.
* י:
** אמר"פ -
עיין בראש פרק המניח (ב"ק) שאומר שם ר"פ דבר דומה לזה.
** שני כלים -
מנה שלש – קנה, צלצל, ומכתשת. יש להעיר שלא אמר ממה בא צלצל, ואולי לא קאי עליו. ועיין ברשי לקמן שלא משמע כן.
* יא.
** גוזמא -
יש לדון מה מזה גוזמא:
1. רק ברייתא גוזמא. אם כן, הסימן פשוט.
2. שניהם גוזמא. אם כן, הסימן הוא שברייתא יש בו יותר גוזמא, או יותר נראה כגוזמא.
3. אין בכל אחד גוזמא. אם כן, הסימן הוא שברייתא נראה כגוזמא.
4. אפשר שברייתא דווקא, ומימרה נקט פחות כיון שחש שלא יאמינו לו. אז, אומר שבריי’ נראה כגוזמא. ותו"ת.
* יא:
** מר סבר מיתה -
יש לציין לגמרא יבמות (פב.) שאומר שאין חילוק בגזרה בין אם הוא איסור לאו לאם הוא איסור מיתה.
** מיסברת -
לכאורה, אז, נדחה ה"לטעמיך." ויש לדון.
* יב:
** יש לדון
אם מוכרח שר"י מודה שהיו שבע שחילקו ושבע שכבשו. (עיין ברשי).
* יג:
** להקל -
יש לדון אם ר"ל להקל על שאר דמים או על ציורים אחרים של ערכין. מהמשך המשנה מוכרח כראשון.
* יד.
** כמה נאה -
יש לדון איך זה נלמד מכאן (שרק אומר הכי נאה, ולא נאה). ותו"ת.
** מקדיש -
מעניין שאיך יפדהו תלוי באיך מקדישו, שבין כך ובין כך הוא אותו חפץ.
* יד:
** טובא -
במקום אחר, אומר שצריך שלש.
** א"ר אלעזר -
יש להעיר שמבואר מירושלמי שהבעיה בלשון הרע הוא חסרון של שלום. אם כן, צריך ביאור למה נחשב מה שעשו מרגלים לשון הרע.
אפשר שיש שני בעיות בו.
* טו.
** כשם -
ואם תאמר הלא לא ראום. יש לומר שחשבו שיצאו ממקום אחר. גם יש לומר שרק במקומם נפתח, ולא היה עדיין עד גבולו.
** יש עבד -
קצת קשה, שערב נגבה רק אי תובע בעל חוב.
* טו:
** לצמיתות -
יש לדון אם לומד מגזרה שווה או כדומה או מוכיח שזה הוא פירושו של זה. ותו"ת.
* טז.
** לכסות -
יש לדון אם דורש ממקומו או שדורש שקרא אומר שהוא לכסתות בשר ערוותו, ור"ל איסור של ערווה. ותו"ת.
* טז:
** משמיה דריב"ל -
יש לדון אם קאי על שני לשונות או רק שני. נראה שרק קאי על שני כיון שהיה ר"ח קודם ריב"ל (יומא?).
** יכול לא יכנו -
מעניין, שלכאורה, שנאה ר"ל בלב. ותח’.
** ענוה -
קשה, אז, איך לעולם יוכיח. ואולי מצוי אם לו יגע לענוותו.
* יז.
** דור -
יש לציין, ואולי יש לבאר על פי זה, שהיה ר"י פרנס של אותו דור.
* יח.
** סיאה -
נראה שהוא מפני שכל שבועתם לאחד, והרי אין כולו שקר.
** עשיר -
לא הבנתי למה לא אמר שהיה אחר הבאת איזה קרבן שיקבע.
* יח:
** עד יום -
לא הבנתי מהיכי תיתי מכאן. ותחשב.
* יט:
** כרעא -
יש לדון מה זה אומר:
1. אולי אומר שכולו בכלל רגל, ואז, עליו הוא בכלל מעל רגל.
2. אולי אומר שפשוט שיש לכולו דין רגל, ואז בוודאי אין מעל רגל מרבה אותם, ואז צריך לומר שמרבה מה שמעל מעל רגל.
* כ.
** חייבוהו -
יש לדון למה נחשב כמלווה בשטר.
* כא.
** מתכפר -
קאי על עולה, והוא לשון מעניין, שעולה לא מכפר כל כך, ולא מצינו ששלמים מכפר כלל. מוזר למה לא אומר שלא עלה לו. ותו"ת.
* כא:
** אמר שמואל -
אינו צריך לומר כן, שיכול לומר שכוונתו היה כעולא (ואולי “אמר לך שמואל” הוא שמואל עצמו מדבר, או שידעו שכן סבר מקבלה). יש לדון, שאולי אז אין לשנותו על משנתינו ש,אולי, משמע שקאי על דין הקרבה.
* כב.
** דמשכי -
גם היה אפשר לומר שהוא מפני שמזכירו בימי הדין, ובאותם ימים נשמע יותר. ותו"ת.
** זימנין -
יש לדון, אז, באיזה ציור דן גמרא, אם ספק או לא:
1. אפשר שדן בדלא סיפק. אז, רבי יוחנן מסתבר. יש לדון מה סובר רב אסי:
  1. אפשר שסובר שמחמת לא פלוג, לא מזקיקין לה. יש לדון מהיכי תיתי לעשות לא פלוג כזה ולא להיפך. אפשר שברב ציורים, סבר, סיפק.
  2. אפשר שסבר שעדיין אין חסרון די לטעון שנשלם. יש לדון, שיכול להיות יותר מריבית.
  3. אפשר שמניחים שתתחיל לספק (תמצא עבודה), ואז לא יחסרו (כל כך).
2. אפשר שדן בדסיפק. יש לדון בטעם רבי יוחנן:
  1. אפשר שהוא לא פלוג. יש להקשות צהיכי תיית לעשות לא פלוג כזה ולא להיפך. אפשר שברב ציורים, סבר, לא סיפק.
  2. אפשר שסבר שיתחיל שלא לספק, ואז מזקקין. יש לדון למה לא נשהה עד אז. יש לדון, שאולי לא רוצים לשהות אז, שהם נפסדים.
3. אפשר שלא חולקים בדין כלל, אלא שזה מזכירו בציור דלא סיפק (או שסבר שהוא מצוי או שרצה אף להזכיר מה שאינו מצוי) וזה לא מזכירו (או שסבר שלא מצוי או שסבר שהוא מצוי אבל כיון שלא פסיקא (שצריך שני דברים, מה שיש כתובה, ומה שלא סיפק) לא הזכירה).
עיין בהמשך גמרא. ממה שמביא ראיה ממשנתינו, לכאורה, משמע שדן בדין (אלא אם כן נאמר שלא מסתבר שדן בציור מוזר).
** שקבל -
יש להעיר שזה, לכאורה, מובן שמדין תורה, מותר, ואף צורך, לגוי ליקח ריבית, אבל אסרו לו שלא לשהות. ותו"ת.
** והלכתא -
נראה שגמרא אומר כן, ולא שלחו מתם, שהוא ר"א, שהיה תלמיד ר’ יוחנן, והרי ר"ה הוא תלמיד של רבא.
* כב:
** לינטר להו -
יש לדון מה רצה לומר. אולי רצה לומר שאם קיבל, אמאי משלמים לו מיד, שהיה לנו לשהות. אין זה קשה, שדלמא ריבית מוסיף. גם אפשר שרצה לומר שנוכל לשהות כיון שלא יקבל ריבית, שדן כישראל.
** אלא בשבועה -
לכאורה, כל זה אף קשה על הצד של צררי.
* כג.
** אף -
אי גורסים כן, לכאורה נמצא שמוסיף על ר"א. משמע שסבר כמותו. אם כן, כן יהא הלכה, שלעולם הלכה כרשב"ג.
* כג.
** רב הונא הוה ליה -
כן נראה מסברה, שהיה אביו כל כך עשיר (ולא מסתבר שהיו שונאים זה את זה, שעשה את עצמו ערב לכתובתו).
** בריה -
נראה על פי זה, אולי, לתרץ קושיית קצות על דין שבועה מדין סבתא (ב"ב קכה).
* כג:
** למימר -
לכאורה, רצה להקשות למה הוא הדין.
* כד.
** החייהו -
יש לדון אם דורש רק מ"מערכך" או אף מהוא, שצריך להוותו. נראה כראשון, שדורשים הוא לדבר אחר. ותו"ת. שוב ראיתי שרשי משמע כצד שני.
* כה:
** אדרבא -
יש לדון למה נוקטים זה מזה. ותחשב.
* כו.
** בדק -
אפשר שתלוי בכמה דומה זה לזה. ותחשב.
* כז.
** שאין יובל -
אם כן, אין צורך לנקוט שדה, שהוא שווה, אלא שלכאורה,אגב משניות שלעיל נקט כן.
* כח.
** ולא הניחו -
משמע שכבר היו באושא בימי ר"ע. צריך לעיין בר"ה. יש להעיר שלא התקינו כן באושא ממש, אלא שחזרו ויסדו (עיין בירושלמי פאה).
** בהמה -
קצתל מוזר למה צריך קרא לומר שאין אדם מחרים מה שאינו שלו. ואולי צריך קרא ללמד דין בתו. לשון גמרא לא משמע שרק לזה צריך קרא.
** נראין -
אז, “ודברי ר"ש" לא אומר שאז הם נראים לר"י, שאם כן, לא חולקים. אולי ר"ל שנראה היה לו. גם יש לומר שר"ל ש"דברי ר"ש הם.. “ ולא קאי על "נראים." שוב ראיתי ברשי.
** חולפנא -
מעניין שמי שנקרא כן אומר דבר בענין חילוף משמרות. ויש גורסים אולפנא.
** מכל מין -
קשה למה נחשב מ"כל אשר לו" שרק אומר שלא יקדיש כל אשר יש לו ממש, שהרי כבר נלמד מדין אושר (שהוא , לכאורה, הלכה למשה מסיני (עיין ירושלמי)) שאינו יכול לבזבז יותר מחומש. ואלי הוה אמינא שהקדש שאני. אולי חולק על הא דאושא (ואז בא ראב"ע לחלוק על כל המשנה. לא משמע כן.). יש לדון אם אולי דבר שנלמד מהלכה למשה מסיני טרח וכתבו קרא.
* כח:
** טוהת הנאה -
יש להעיר שלא יכול למכור או ליתן אותו זכות, ואז קצת מוזר מה שאומרים שיכול להחרימו כיון שהוא קצת שלו. ותחשב.
* ל.
** ממאי דלקולא -
מעניין שקורא מה שהוא יותר נוח למוכר קולא. ותו"ת. ועיין במקום אחר שדנינו מה הוא קולא ומה הוא חומרא.
** דגמר -
יש לדון, אז, למה צריך שאר הקראי.
* ל:
** אימא אידחיא -
קשה למה לא אמר שהחזירו קרא כיון שאמר "עמך."
** אמר רב יוסף -
נמצא שקורא רב נחמן בר יצחק בשם ר"נ סתם. גם נמצא שהיה רב יוסף מכיר ברנ"ב יצחק; משמע שהיה אפשר שהיה מלמד דינים לרבא. כל זה נוגע מאד למי הוא סתם רב נחמן. אפשר לדחות כל זה לומר שלא קאי על מה שאומר גמרא, אלא אומר שרב נחמן (בר יעקב) אף הוא דרש כן. ויש לדון, שמוזר מה שלא אמר שמו. ותחשב.
** צריך ביאור למה צריך להיות
שיטת שמואל לעיל (גבי הקדש בשנת יובל כרבי שמעון; נאמר שכרבנן הוא. גם יש לומר על אותו משנה שמוקים כרבנן שרבי יהודה הוא. ותו"ת.
** מה טעם -
יש לדון למה אין זה פורך כל קל וחומר שבעולם. ותחשב.
** אדחה -
היה אפשר לומר שאין הענין שלא זכאי בכך, אלא שלא נהנה בכך, שלא ירגיש, ואז יימכר עוד. זה יתרץ מש"כ בד"ה אימא אידחיא.
* לב.
** וכי איצטריך -
יש לדון איך יודעים שלא תקן שיחול אף שלא נתן מדעתו. ותחשב.
* לג:
** תניא… מן הלווים -
יש לדון אם תנא זה יחלוק על תנא דלעיל (גבי מכירת ללוי) או שלא יוציאנו מפשטותו. ויש לדון.
** כגון שנפלו -
יש לדון למה צריך מה שמגרש נפל. ותחשב.
* לד.
** שקיל -
יש לדון מהו חילוק זה.
** ברשותו -
צריך ביאור למה זה סיבה שלא יטול; הרי מה שהם ברשותו הוא, לכאורה, ייפוי כוחו.
