* ב:
** במשנה ראשונה -
עיין בלשונו "ולא קרינן,” שאולי משמע קצת שאף שעומד לשחרר, עדיין נחשב עבד, אלא שאינו נקרא מי שיש לו אדון, שמילת אדון משמע שיש לאחר שליטה עליו, והרי, אף אם נקנה לו, אין לו שליטה, שלעולם יכול ללכת לבית דין לעשות שישתחרר. ותו"ת.
** שאינו צריך -
עיין שם  שלא אומר כן, אלא מסיק שצריך להיות שלא קורא "אימא אימא.”
* ג.
** והצרוע -
נראה לי שני דרכים לפרש דרשה זה:
1. אפשר שמוסיף מין אחר שמטמא, שאומר "איש"- והוא מין אחד- ו"צרוע"- והוא, כיון ששינה את שמו- מין אחר, והוא צריך להיות אשה.
2. אפשר שדורש ממה שמשתמש בלשון "צרוע," שכולל שניהם (איש ואשה) לומר ששניהם בכלל אותו דין. ויש לדון.
* ד:
** שקולים -
יש להעיר שיש, לכאורה, שני פקטורי"ם השייכים לדיון אי לדרוש או לא:
1. צריך לדון כמה מסתבר הוא הדין של הדרשה.
2. צריך לדון כמה נשע מן הקרא.
לכאורה, כשאומרים שהם שקולים, אומרים שבין שנים אלו, הם שקולים. רשי רק דן בשני. צריך ביאור למה. ותחשב.
* ו.
** אמה -
ל"א- יש לדון מה החילוק בין שני הלשונות נראה שדן רשי אם אומר שגורם שלא ישכנו שם או שיצאו (שלא ישכנו שם לזמן רב).
** אלא ל"ש -
יש לדון איך ידע שאינו אומר ש"לא שנא" ואסור.
* ז.
** חייבין -
סתמא- צריך ביאור מהו הקושיא, שהרי זה ברייתא, ואיך יקשה סתם ברייתא על סתם משנה. ותחשב.
* יא:
** נפקא -
לולי רשי, היה אפשר לומר שהחורבה הוא שיאמר שיעכב אף על אלו, ואז ישרפו קרבן שלא כדין. זה תלוי באי שיר מעכב קרבן.
* טו:
** תליתאי -
יש לדון אם רצה לומר שכיון שאומרו הוא השלישי (ויש לדון, שאולי המקבלו נמנה אחריו) או שהוא השליש (מי שהוא בין זה לזה). ותו"ת.
* טז:
** פטיט -
חשאי- יש לדון איך זה שייך לצפור. ואולי הוא כיון שהם שרים בבקר, קודם שאחר משמיע קול. ויש לדון.
** יכול לא יכנו -
עיין בגמרא, שיותר משמע שדן אם איסור שנאה האו רק שלא להכות.
* יח.
** ילד -
אינו צריך לומר כן, שאפשר שהוא בן עשרים על בן חמישים, לכאורה. ותחשב.
* כ:
** חייב -
חשוד- לשון זה מעניין, שלכאורה בא כיון שעבר ולא כיון שחשוד. אולי חשוד יכול להיות משמע שעבר (עיין, אולי, רשבם גבי אבק לשון הרע (ב"ב קסה?) ועיין בשיח שי (הוספות- בבא בתרא).
** חייב -
משמע שלא בא על לשון הרע, ורק צרעת הגוף בא עליו.
* כא.
** ממשכנים -
רק מוצאים (ראש זבחים) שעולה מכפר, אבל לא שלמים. צריך ביאור מהו מקורו של רשי.
* כט.
** רב אגמריה -
יש להעיר שהיה רב רבו של רב קודם המשנה, שהיה רב של רב רבי. ואולי רצה לומר רבי שהיה רב של רב חייא רבו. יש לדון למה לא יאמר רק רבו. ותחשב. על זה. ויש לדון.
* כט:
** [אילנות דקץ] -
לא הבנתי, שכבר חזר, לכאורה, בהכרח, כשקץ. ויש לדון מתי חוזר (שלכאורה, יחזור מיד, שהרי יהא סיבה לו לחזור מיד. ותחשב.
* ל:
** פדיון -
סתם- מוזר, שאינו כן רק מפני שזהו הסתם אלא מפני שאי אפשר למכור ביותר.
* לא:
** דכולי עלמא -
יש לדון למה יניח רבא שחולק באיי’ על משנה. אולי רק אומר שאילו רק היה ברייתא. יש לדון.
** שאין לו -
מבואר שהקדש נקנה לה’.
* לג:
** מוכרים לעולם -
איידי- אם כן, אומר איידי שאינו נכון. וצריך לומר, אם תרצה לדחות, שנכון הוא ברוב שנים (וכשאומר לעילם, לאו דווקא הוא, ולא בא לומר מה שהוא פשוט שאינו כן). ודחוק.
