* יב:
** דתנן -
משמע שאינו בעיה שלא ידע את המשנה. ותו"ת.
* יד.
** הובררה -
קשה, שאי יש ברירה למוקצה, לא יהיה שום ברירה. ויש לדון.
* יד:
** אוכלא דאיפרת -
משמע שהענין אינו שחד מלאכה הוא, אלא שאין שינוי.[fn:1]
* טו:
** כגון -
א"כ, נוקים רב בדלא היה חולה.
* טז.
** כולה חד -
תלוי בדיון שבקדושין אם מוקמים כחד תנא ובתרי ציורי או להיפך.
* קג:
** מבשר דגים -
יש לדון למה אינו בשר.
* קח.
** קסבר ר"י -
תחשוב על זה מסוגיא דלעיל לפרש רב.
* קט:
- ודע שיש שני  דרגות, צלי שהוא יותר קל, ומבושל שהוא יותר חמור. יש לחקור באיזה חולקים. והריאה מדאין קורעים הוא גם כן לבישול. ועוד מק’ להלן על הא"ד שהוה רק ק’ אי אסרו במבושל נראה שחולקים במבשל. ויש לחקור אי ג"כ חולקים בצלי. ונר’ שחולקים דאי לאו הכי מה ראיה יש מן הבאייתא שיש לאוקמיה בצלי. ואי אין ראייה. אבל, אם כן, יש לשאול איך מביאים ראיה מברייתא זה אף לבישול. ויש לומר שמשמע שאיירי בכל ציור. אבל אם כן אין שום ראיה שחולקים בכל ציורים. אבל אולי יש לומר שלדרך זה, שחולקים בשניהם, אין שום חילוק בדרגות. ועיין בערוך השלחן. ואני חושב שזה מח’ ראשונים. ושוב ראיתי שבברייתא נכ’ בשול, ויש לחקור אי אולי בישול יכול להיות לאו דווקא. ועיין במשא "קורעו… "
** אסר לן -
יש לדון אם ידעה הכלל, ואמרה דוגמאות, או שלמדה הכלל מציורים אלו. יש לדון איך תדע אם לא מדוגמאות. ויש לדון. גם יש לדון אם יכול אדם ללמוד מדוגמאות כמו זה. ותחשב.
* קי.
** מתוך פלפולו -
יש לדון אם אומר שהיה מתוך שיעורו, ומה שמכוון לומר, אבל לא אומר, הוא שהיה מחודד…, או שפלפולו רצה לומר חריפתו, ואומר שנאמר דבר זה מתוך חכמתו, ולא היה אחר יכול להבינו.
** דהוה רמי -
יש להעיר שמצינו בכמה מקומות שדקל הוא תמר, ואז החילוף כאן מסתבר.
** דקדחו -
ולכאו’, הא דיב חדש [דיו].
* קיא.
** דאורייתא -
צ"ב הא עכ"פ לא יכנס לתוכו אלא ישרק.
* קיא:
** בכל זה
, עיין בערוך השלחן.
* קיד:
** כדרך -
צריך ביאור מה שייכות זה.
* קטו.
** כלאי זרעים -
ונראה לי להקשות הא אולי שאני אכילת בשר בחלב שאכילת בשר בחלב בא רק על ידי תערובת, ואז תועבה אפקט"ד ביותר עליו. ואולי סבר גמרא שאין זה מסתבר בקרא. ועוד אולי בשבת משונה שטעם של שבת יותר טוב. וצריך ביאור אם מושג זה [fn:2](ששל שבת יותר טוב) גם בתבשיל אסור וגם אי התבשיל אסור בשבת. וגבי כליאים ודישה, אולי הוא יותר טוב על ידי שפר לא אכל ממנו, ושנהנה באדמה מכרם או כדומה. וצריך ביאור אם זה נכון. ותע"ז.
- כתבתי "אבל לכאורה לא בכלאים,” ואיני יודע על מה קאי.
* קטו:
- לא הבנתי למה אין לומדים מקל וחומר מכלאי הכרם.
** ושרו -
יש לדחוק כמש"כ על רש"י.
* קטז.
** ואי לא -
לא הבנתי למה אינו קרוי קל וחומר.
** לא הבנתי למה יהיה
יותר קל ללמוד מחד מללמוד משנים. ויש לומר שכל צד השווה כבר יש לו פירכא במה שיכול להיות שהוא רק אם יש בו או זה או זה. ותו"ת.
** אף כאן אסור… חל על איסור
ונראה שדורשים איסור אכילה מזה ובא עם זה שאין איסור הנאה ושלא נלמד משאר קראי.
לא הבנתי, שאף שמואל סובר כן.
** כרבי יוסי -
צריך ביאור אם זה דווקא או דלמא. עיין בשבת שאומר דילמא. יש לדון אם נניח שכן סובר זה או שממה שמשנה, משמע שהוא חולק. ויש לדון.
* קטז:
** יש לדון
אי וודאי לא ינקה אם אסורה מטעם לא פלוג או שאולי נגזור שהוא או אחר יבאו לזלזל בדבר שאולי ינקה. ותחשב.
** למה אין אומרים
לשחטו לגוי שהוא בעלו, ולא יהא נבלה.
** ומי אמר שמואל הכי -
ונראה שבאמת יש להקשות עליו ממשנה גופא שלכאורה, לרבנן לא יתורץ שבוודאי קבת נבלה אסורה.
* קיז.
** כעורה -
צריך ביאור למה אן משיבין זה להמנה"מ שהשאלה היתה על חלב.
** יש בו מעילה -
והוא באימורין או שזה יותר מסתבר או שזהו מה שמיירי בו קרא.
** לא ימעלו בה -
ורולי נלמד מבא דיש קרא מיותר דאי אינו מרבה זה, מה ירבה. וצריך ביאור.
** לכם -
משמע דמותר לכתחילא. ואולי הוא שהוא שלכם לכפרה.
** צירך ביאור מהו סברה חיצונה
, שאם לא היינו לומדים בכאשר יורם, למה נלמד [אדן]. ותע"ש.
** [וכל שני כתובים] -
בתחלה הניח גמרא שהוא שאינו מסתבר. ועכשיו בגמרא אינו אומר כזה, אלא שנלמד מקור.
* קיט:
** על גב שומר -
והגמרא מניח שבא דרינו מצטרף הוא החיצון.
** [] -
האם זה כיון שחטפנו סברה זו או כיון שצקיך לדחוק כזה ממ"נ.
* קכ:
** וגמר להו -
זה נראה סרקיול"ר.
* קכג:
** ואולי יש לת’
ששאני הכא דהוה כמו דבר שיש לו מתירים, שמותר בטבילה והערב שמש. וצ"ב אם זה יהני לציור דעור. ותחשב.
** ויש לחקור מהו
הגזירה, אם הוא שנראה כמי שאינו חותך את רובו או שחוששים שלא יחתוך את רובו. מסתבר כצד שני.
** מחמשה טפחים -
וצריך ביאור, שאולי זה רק בציור דחושב עליו.
** העשוי לנתק -
מהיכי תיתי שאין חולקין בזה, ולכאורה הוא שאין רוצים להוקים מח’ במחלקת תנאים.
** צריך ביאור בכל הציורים
שאינו מתקנו, [שכל] מה שאמר ר"ל הוא כשמתקנו.
* קכד.
** בטל -
ובפשטות, הוא שלכולי עלמא בטיל. מרש"י משמע שהוא שחולקים בזה גם כן.
** חתניה -
או שמתוך כך לא חשש לחרם וכדונה או שמתוך כך חשב שהוא אדם גדול.
* קכד:
** אין נוגע -
זה יותר מובן לשיטה שאהל ונגיעה שווים.
** קמטהר -
לא הבנתי מביכי תיתי שחולק על נקודה שאת; הוא רק שאינו מפורש מה סובר.
** רבי עקיבה אומר -
וצריך ביאור למה לא אמר שעור מבטלו.
* קכה.
** מי מצרך -
מניח שנוגע מצטרף לנוגע.
* קכה:
- צריך ביאור למה אין המשכה במשנה.
* קכו:
** וחציו אדמה -
אולי רצה לומר שחי עם חציו דייקמפוס"ד.
* קכז.
** כל מקום -
לכאורה, יש לדרשו מטובל ושרף בידו. ותחשב.
** וחציו אדמה -
עשיתי את החשבון ואין זה אפשר שבצד זה לא נדרוש כל המשריץ, ואש נדרוש אותו למ"מ ואז נוציא שבים ודלא כהוה אמינא זו.
** טומאת אוכלים אין -
ומה באבר מן החי? לכאורה, אבר יהא טמא מזה.
* קכח:
** בין רבי לר"ע -
ולכאורה, היה אפשר לומר שיש מושג של אבר ושל בשר ואלו סימנים לומר איזה היו בכלל הטומאה. ואז, אין שום מח’ בין התנאים.
* קכט:
נראה שמקשה שאולי אף ששמעת רק באבר מן החי, לא דייקת יפה. והוא משיב שלא דייק, אלא כך שמע.
* קל.
** מום עובר -
דהוה אמינא שבמום עובר מיקדש ותלי שנתקדש כיון שיעברו מום ואז כאן שנולד מום אחר לפני זה לא נתקדש. וכן נראה מרש"י.
* קלא.
** בטבלייהו -
צריך ביאור אם כן לשון משעת הרמה.
* קלא:
** אין -
יש שני דרכים לפרש את זה או שחזר בו ממה שאמר שראב"ע היא והיה כקנס שגם רבי עקיבה סבר שקנסו מן הלויים או אולי גם כן האי בדראב"ע ומניח שהקנס לראב"ע יהא יותר חמור מלר"ע והקמ"ל הוה או שאינו יותר חמור [ולש"ן] הוה רק לכהן או אולי שהוא יותר חמור, אלא שלר"ע הוה אף לכהן וראב"ע  רק לכהן.
** השוחט לכהן -
אם כן לשון כל יהא דהוה ככלל צריך ביאור.
* קלב:
** לשנים -
צריך ביאור אם זה דווקא או מקסימו"ם.
* קלג.
** אינו בקי בהם -
וצריך ביאור שלא אמר ר"ח אלא שצ"ל בקי בכד מתנות, ואולי א"צ בקי בכל העבודות.
* קלד.
** שבלשון יחיד -
צריך ביאור שבפירוש בלשון יחיד הוא. ועיין בתוס’. ואם כן קשה. אבל זה בעצמו קשה שמביכי תיתי שלא לומר [שעלי לעינים רק] רק שיודע בודאי.
* קלד:
** וצריך ביאור
למה לא אמרו שאין בו עזובה. ואולי הוה לפני מלקט. וצריך ביאור אם כן למה לילפי בהן בלי לשון עזיבה.
** אדם חשוב -
עיין לעילולת’ לבא דאביי שכיון ששמע את דרשה זה הבין שלא הוה חשוב.
* Footnotes
[fn:1] נראה שכוונתי בזה היה לומר שמשמע שאין הענין רק שמלאכות שוות עושים, אלא שזה עושה שהוא אותו חפץ. ותחשב.
[fn:2] לכאורה, כוונתי למה שדבר יותר טוב בשבת. צריך ביאור, שזה לא נאכל אז, אלא רק נעשה אז. אחר כך ראיתי שהייתי מסופק בזה. ונראה שאולי תלוי באם הוא שינוי במעשה או בחפץ. ויש לדון.
