* יג:
** דעובד -
אדוק- לקמן לא משמע כן.
* כט:
** מצוה -
ואין לבי- קצת קשה שאולי מעלת כהן גדול עולה על זה אבל אי אי לא יעשה אותה שום אדם או יעשה אותה האחר, אז בר"ע הדרת מלך.
* עז.
** דחריפא -
קשה מה לנו בזה, שלכאורה, לא דן כאן בסברה. וזה קשה רק לרש"י, שלולי רש"י היה אפשר לומר שר"ל שהיה בקי בשחיטה עד שסכינו לעולם חריף. עיין ביבמות, שאי אפשר לומר כן[fn:1].
* קיד:
- לא הבנתי למה לאין אחותו במעשר לריט"ע.
* קטו.
** מעשה שבת -
ואנן תנן- או זה ראיה שמדרק הוא אסור ורק במזיד נראה שקנס הוא או אולי מקשה ומתרץ שרק קנס.
* קטו:
** מה להלן בהנאה -
לא הבנתי, שאף אכילה הוא הנאה.
* קטז:
** ולא משום טרפה -
או שיבטלו או לא יתנו אותם לישראל וגבי ת’ בגמרא או שאינו ביטול או שיתנו מטמא שבם כמה בימים וכמה רווח.
* קיח.
** יש להכניס -
צריך ביאור מהו סברה זה.
* קיט.
** ואי בשומר -
שומר הוא- לא הבנתי ת’ זה שבודאי שומר הוא, אלא שאולי לא יביא טומאה.
* קכ.
** ציר -
ל"א- כן משמע מדלא אמרינן ציר בזרעים.
* קכא:
** אמר חזקיה -
טומאה חמורה- לא הבנתי אם כן לשון סופה שבכל סופה  יכול לחתכו וטמא רק אי כבר טמא. ואולי סופה הוא שרק בבית הבליע מטמאה. ואין זה נראה שיטמא כל הזמן, אלא שאין שום דבר להיטמא. ותחשב.
* קכג.
** חדא -
אתמול- ויש להק’ למה אין אומרים להקים אותה בציור שנקרא וביום שני טבלו ושוב קרעו שהרואה שטבלו יבין שלא טבלו מאתמול.
* קכג:
** חלים -
צריך ביאור שמה שאמרנו חלים הוא שחלים הוא לעצמו ולא לבשר.
* קכו.
** וקא"ל רבי יוסי -
לא הבנתי מהיכי תיתי שקאי על שניהם.
** מביא -
ורחבו- לא הבנתי כל כך מה זה.
** רבי יוסי -
חלל הגרון- ולכאורה, אומר את זה לפרש למה מניחים שקאי בציור שאין בו טפח. וק"ק שכבר כתב על זה לעיל.
* קכו:
** ואינו מטמא -
צריך ביאור שאולי רק אומר שלמעשה אם מגעו אינו טמא.
** עצם -
פעם אירע לי מעשה ברגל אחד שמצינו שהיה בבית שהייתי דר בו עם אחי, ומפני זה ידענו שלא היה בעיה.
* קכז.
** לוייך -
ויותר גרועים מלבן, שלבן רק רצה לגזול מרגליות, אבל אולי לא היה ליעקב שינים, שגם אלו נטל אליפז. ואין זה נראה.
* קכח.
** מוחלפת השיטה -
צריך ביאור מה אומר. והייתי אומר שרוצה לשנות את המשנה בחילוף שמות.
* קלא:
** וקמסיים -
יש לומר שהגמרא בתירוצו הניח שבאמת כהן ל"ד שלכאורה פשוט הוא שכבר ידעינן שכהן פטור (וצריך ביאור למה). וכיון שיודעים שחייב בטבח מוכרח שאין בין טבח זה לישראל. ואז מוכרח שפטור כהן הוא בכה"ג ואז פשוט הוא ומוכרח שבא רק לומר גם כן את הצחור פשוט בין הא דעכו"םפ שאינו כך פשוט. ואז אין להביא ראיכה מבא דלא נקט לוי שרק בא להשמיענו דין עכום וכללו עם ציור סתם והקא משמע לן הוא שכבן אינו כל כך פשוט וחידוש הוא, ואז הול"ל ביותר מחודש או אולי שהל"ל גם כן לוי ואין זה נראה. או אולי שרק כהן וטבח כהן פשוט. ועיין בתוס’ בג. ביבמות.
* קלג.
[זכי לי]- ועוד כמש"כ ממש קצת לפני כן.
-או שהיה חשוב או שהיה כהן.
* קלד:
** ואיבעית אימא -
שהרי עליו- והייתי מבין את הגמרא רק שמזה מוכרח שקבל מתנות ואז גם הוא יכול, שחושב הוא, ולא שחייב בגידול.
* Footnotes
[fn:1] כנראה, הנחתי כאן שאם שוחטים בסכין, נעשה יותר חד. זה לא נראה במציאות. אבל, אפשר לומר שר"ל שלעולם הוא מוכן לשחוט כיון שהוא שוחט תמיד. ותו"ת.
