* ב.
:PROPERTIES:
:CUSTOM_ID: ב.
:END:
המקנא דיעבד- עיין ברשי שמבאר ל"ל יקנא. יש להעיר שיל"ד אם מה שקינה אותה
הוא סימן לחשוב שהיא טמאה אחר שנסתרה או סיבה. אם נאמר שהוא סימן (מגלה
שהיא פרוצה), אז קשה ל"ל יקנה, שהרי, תורה רוצה שתשתה. אולי תורה רק רוצה
שתשתה מחמת בעיות בשלום בית, שהוא מקפיד על מה שהיא אולי מזנה. גי"ל שהוא
סיבה, והוא שהראיה שזנתה הוא ממה שיחדה אחר שקינה לה ואמר לה שלא לסתור.
ותו"ת.
ותנא- לשונו (שבא נזירות ע"י נדר) הוא מעניין, שלכאורה, לא בא על ידי נדר,
אלא הוא נדר. אולי ר"ל שאומר נדר, והוא חלות של נדר. ותו"ת. גי"ל כמש"כ
בשי"ח ש"י במק"א, והוא שנודר להיות קדושה על עצמו, וממילא בא נזירות, אבל
אין הנדר, אז, הסיבה הדיירקט לנזירות. ותחשב.
המקנא- היה אפשר לדחות שלא אומר מקנא כיון שהיה משמע שיש חיוב, ולא רוצה
לומר כר"ע (לקמן).
* ב:
:PROPERTIES:
:CUSTOM_ID: ב
:END:
איכא עיקר- עיין במה שבאר רש"י. יש לדון אם הענין הוא שלא חושב אדם לעשות
רע לה כשאותו רע צריך כל כך עשייות או שמסתמא אחר כל העשיות כבר לא יהיה כל
כך בכעס עליה, ואז ימנע. ותו"ת.
* ג.
:PROPERTIES:
:CUSTOM_ID: ג.
:END:
הקב"ה מכריז- לכאורה, סובר שאינו עבירה, שאם הוא עבירה, קשה לומר שה' עושה
שצריך לעבור. ויש לדון, שאולי רצה לומר שה' עושה שהוא יותר טוב. יותר נראה
לומר שאולי ר"ל שה' עושה שצריך לקנאות כדי שתהיה לה דין סוטה. הוא מקנה לה
כדי שתהיה לה אותו דין[fn:1], ועושה כן מפני מה שכ' בתורה. תורה כתבו כיון
שרוצה שתהיה בגלוי.
לכאורה, רואים שכן כוונת תורה, אומר גמרא, מלשון עבר, והוא שמה שעל ידי זה
יעובר הקול הוא הסיבה לזה. ותו"ת.
רשות וחובה- לכאורה, מח' זה של איזה רוח הוא אם מותר הוא או אסור. אם כן,
לכאורה נמצא שמח' אם מותר או אסור הוא מח' תנאים, בין משנה שלנו לר"ע ור"י.
צריך ביאור למה יותר מסתבר שברייתא זה הוא כר"י ור"ע. אולי מס' שתנא דבי
ר"י סובר כרבי ישמעאל משסובר כחולק עליו. ותחשב.
לא תשנא את אחיך- לכאורה, עובר על זה כיון שהוא גורם שנאה, כמו שבאר גמרא
לעיל בלשון קינוי. ותו"ת.
וקנא- צריך ביאור איך רואים מזה שהוא מותר, שאולי רק רואים הדין אם עושה
כן. במילים אחרים, אולי "דאי" קתני. אולי אין שום חומרא נמצא בזה. לא נראה
כן, שנמצא דין ע"א, ונמצא איסור בעל כל זמן שמביא אותה לבית המקדש. ותחשב
על זה.
* ג:
:PROPERTIES:
:CUSTOM_ID: ג
:END:
- צריך ביאור למה צריכים קרא ללמד שצריך שנים; נלמד ממה שצריך "עד" להאמין
אחד שבדר"כ צריכים שנים. נראה שהו"א שאף לא צריכים אחד, ואז "עד" יבוא ללמד
שכאן צריך אחד. ויש לדון על מה היינו סומכים אם צריך פחות מע"א. אולי הו"א
שא"צ שאותו אחד הוא עד כשר, ובא קרא ללמד שצריך להיות עד, דהיינו כשר.
ותו"ת.
* ד.
:PROPERTIES:
:CUSTOM_ID: ד.
:END:
חזרה ברוח- נראה שדיון גמרא הוא אם צריך להיות רק בולך במקומו או שב ונח
במקומו. זה אומר שהולך אמה לרוח זה, וחוזר למקומו, והולך חצי אמה לרוח
אחרת, וחוזר למקומות, והולך רביע.... דן אם מונים מזמן ראשון עד חזרה
ראשונה או עד ששב ולא חוזר עוד לצד אחר מחמת אותו רוח מתחילה.
ודע שזה תלוי, לכאורה, בגודל הרוח (ובפרט אם צריך להיות נח שם).
* ה.
:PROPERTIES:
:CUSTOM_ID: ה.
:END:
שכן לעפר- אם כן, לכאורה, צריך להיות ענו, ולא רק שאינו גס רוח. נראה שלכן
אומר "מי שיש בו גסות רוח," והוא שהוא כל מי שיש בו קצת גסות רוח. כמובן,
צריך לבאר כל אלו, שאם כן, כמעט אין אדם שעומד בתחית המתים. יותר מכן, יש
להעיר שמשה היה ענו מכל האדם. אז, צריך לומר שלכל אחד יש קצת גסות רוח.
ותו"ת.
אדם שאין בו אלא- קל וחומר זה יאמר לנו שכל אדם כן, ולא רק מי שיש לו גסות
רוח. צריך לומר שיש פירכא בקל וחומר זה (מסתמא, הוא מה שיש חיוב באדם), ורק
לומד ממנו כיון שקרא מקיש אותם. אם כן, הוא רק ברשעים, שהקיש קרא אותם.
ותו"ת.
סרוחה- נראה שחולקים אם יותר טוב לדרוש כפי אותו אות עצמה או כפי שנשמע.
כמו כן, יש לומר שדן אם ש”שׂ” ו"שׁ" הם אותו אות. ותו"ת.
* ה:
:PROPERTIES:
:CUSTOM_ID: ה
:END:
שאין תפלתו- לכאו', כבר אמר לעיל כן, שאמר שצריך לב בשר. ותו"ת. נראה שלעיל
אמר שלא נענה בלי זה, אבל כאן אומר שבזה נענה. ותו"ת.
ואת אמרת תתייבם- יש להעיר שיוצא מגמרא שיש רק בעיה לתת לו חיוב. אם כן,
היה לו להיות מותר. צ"ל שבלי חיוב, אין היתר. לכאורה, זה יותר מובן אם נאמר
שדחוייה הוא, ולא הותרה, שאם הוא הותרה, צריך לומר שמה שחיוב נדחה עושה
שהציור אינו מותר, ויש ס"ר. ויל"ד.
תסתרי- צריך ביאור למה חוששים לסתירת בית, ולא שתבעל עליו ויהיה אסור לבעול
עליה.
* ו.
:PROPERTIES:
:CUSTOM_ID: ו.
:END:
גבי דהאי- א.ד.ר. אמר שאולי הענין הוא שבא ליבם בעלות של מת. אז, אם אותו
בעלות הוא בעלות שאוסר, כשבא לו אותו בעלות, נאסראף ליבם. מחודש לומר
שהאיסור בא מן האישות, ומחודש לומר שהאישות בא מבעלות, אבל חוץ מזה, הכל
בסדר.
האומרת טמאה- עיין בסוף נדרים, שהוא מח'. נ' שחול' שם אם משנה זה הוא במשנה
ראשונה או אחרונה. גי"ל שזה רק אחר שקינה אותה. חול' שם אם הדין נכון אף
שלא קינה אותה. ותו"ת. אח"כ ראיתי בתוס' כאן.
לאכול בתרומה- גם נמצא אחר שמת או גירש אותה, אם היתה נשואה לכהן או היא בת
כהן.
* ז.
:PROPERTIES:
:CUSTOM_ID: ז.
:END:
והביא- מעניין שיכולים ללמוד ממה שאומר תורה כאן, כיון שאין דין ייחוד אסור
מן התורה. אולי כיון שאסור לו לבוא עליה, הוא אסור מן התורה.
דידעי- עיין במש"כ. נראה שהיה קשה לו שהרי כל מי שאינו ע"ה יודע איך
להתרות. אז, מבאר שאומרים דבר שישמע לו, והוא דבר שלא כל כך ידוע. ויש לדון
למה זה יהיה יותר ידוע מזה.
* ז:
:PROPERTIES:
:CUSTOM_ID: ז
:END:
ורמינהו- צריך ביאור למה משנה יותר קשה על בריי' מבריי' עצמו. ואולי איה"נ,
אלא לכן יכול להביא אותו כאן.
יהודה- יש להעיר שלכאו', טובת הודאה אינו מה שמודה, אלא הוא מה שגרם שלא
יהיו בניו נחשדים או שלא תמות תמר. אם כן, טובה חלוקה הוא בסוטה"ש הוא שלא
ימחקו שם ה'. צ"ב, אז, מה מביא משם.
ידיו- צריך ביאור איזה נצחון היה לו אם לא היה יכול לדעת אליבא דהל'. אבל,
אף היום, יש שלא יודעים ללמוד אליבא דאמת, והם נוצחים...
* ח.
:PROPERTIES:
:CUSTOM_ID: ח.
:END:
לפני ה'- נמצא ש"לפני ה'" ר"ל בעזרה. ותו"ת.
לא מן השם- נ' שרש"י מכוון לומר שאולי זהו הסיבה, אבל לא יכולים לדעת כן,
שאין דורשים טעם הקרא. עדיין קצת דחוק.
פרחי כהונה- עיין במה שבאר. ועוד, שלאביי, לא באו שום אנשים. אז, מס' לא
היו אנשים רואים חוץ מכהנים.
* ח:
:PROPERTIES:
:CUSTOM_ID: ח
:END:
תנא- יל"ד ל"ל נותנים לה לבנים, אז. משמע שאין אשה שלא נ' יפה בלבנים.
שליח ערטיל- יש להעיר שגמ' אומר שמנעלים הוא הדברים החי חשובים. אז, אינו
כל כך רע להיות ערטיל בלי מנעלים, שיותר טוב לקחת מנעלים ממלבושים. ויל"ד.
חבל- עיין בביאור רש"י. יש לדון למה אומר חבל זה בדווקא אם אינו דווקא.
נחש מכישו- יש לדון למה נחשב ארס נחש דבר ששורף. ותח'.
* ט:
:PROPERTIES:
:CUSTOM_ID: ט
:END:
כל צדיקים- קשה, שאם כן, מהיכי תיתי שהיה מדה כנגד מדה גבי משה. כמו כן,
קשה איזה שכר נחשב זה לו, שהרי כבר היה בא לו. ותחשב.
ישרותיה- נראה שזה לשון סגי נהור, ורצה לומר שהוא דבר שאינו ישר.
דלא מפיק שם שמים- כמו כן רואים גבי שדים בתחילת מגילה.
- דלילה דלדלה כוחו. קשה, שהיה אונס. ויש לומר שלא היה לו לישא אותו. גי"ל
שאף שאין עונש בא על ידי אונס, יש תוצאות שקרים, וזה אחד מהם. כמו שאילו
המית את אדם באונס אותו אדם נשאר מת, אף כאן אותו תוצאה של התשת כוח קיים.
- בדבר טמא- ואם תאמר איזה טומאה יש בזה, שבא מים ממנו, ומים טהור. אולי
הוא מפני שכל הבא מן הטמא טמא. דחוק. גם יש לדון, שהיה פיקוח נפש. אולי
עדיין יש סיבות רעות.
מכל זה, היה נראה שיותר קל לומר שאין הכרח שיש שום רע, אלא יש שום גנאי
בזה, מחמת דמיונו לדבר טמא ודבר אסור. ותחשב.
* י.
:PROPERTIES:
:CUSTOM_ID: י.
:END:
חיגר בשני רגלים- ואם תאמר איך הלך אחר פלשתים. אולי הלך בידיו. לא משמע
קראי כל כך כן. אולי חיגר רק ר"ל שהיה קשה לו ללכת בהם, אבל רק לא היה כל
כך קל לו. ותו"ת.
נקם אחת- צריך ביאור למה נוטל שכר על עיניו, שלא עשה טוב בזה. גם קשה למה
נוטל שכר, כיון שכבר הוצרך להיות עונש, כמו שאמר גמרא לעיל.
אמתו- עיין במה שבאר רש"י. לולי רש"י, היה אפשר שאמתו ר"ל אבר שלו, והוא
שייך למה שאומר גמרא לקמן שהיה בועל כל הנשים של פלשתים. ותחשב.
יתומה- אם זה אמת (ורשי מניח שהיה אמת, שעשה חשבון בחיי שם), אז ק"ק למה
רצתה ליבעל לו, שלא היתה נשואה, ואז לא הוצרכה לעשות ייבום.
יתומה- נמצא שיהודה היה מקפיד על התורה. (הנחתי שיש מאיסורים אלו שלא נצטוו
בהם גויים. אינו יודע אם זה אמת.)
* י:
:PROPERTIES:
:CUSTOM_ID: י
:END:
סימניה- דוד- קשה ל"ל אמר שרצה שלא יצא ממנה משיח, שיכה את אדום ביותר,
מסתמא. ותחשב.
מדוד- קשה ל"ל מזכיר דוד לנביא. אולי אין קרא אומר כל כך בפירוש שהיה נביא
(ואולי רק היה לו רוח הקודש).
מכתו תמה- יש להעיר שהיה נימול (כמו שאומר רש"י בשבת, שהיה שמח על שהיה לו
מצוות מילה). נראה שזה מכוון להטפת דם ברית שהיה לו.
דקריב רישיה- ואם תאמר הרי לקמן יש ראיה איזה יקרב לאיזה. וי"ל שכאן הוא
כאותו שיטה שסובר שראש ילך אצל לגופו. יותר נראה לומר ששם תלוי במה קרה
במציאות. כאן, המציאות היה כך. יש לדון מהיכי תיתי. נראה שמסבר שמת על
האילן, ונפל את גופו אחר שתקו בו דברים, ונפל במקומו, ולאחר שחתכו את השער,
אותו כוח גרם שראשו הושלך. ותחשב.
* יא.
:PROPERTIES:
:CUSTOM_ID: יא.
:END:
הבה נתחכמה לו- חושב אני שמצאנו שאומר לשון "לו" על כל בני ישראל.
* יא:
:PROPERTIES:
:CUSTOM_ID: יא
:END:
תחלה- צריך ביאור מהי"ת ששאר הכירו את ה' כלל, שהרי כיון ש"זה קלי" קאי
עליהם (ויש לדון, אגב, מהיכי תי) אין מקור לשאר. אולי זה נכלל ב"ויאמינו
בה'." דחוק.
סימן- ק"ק איך חשב שלא ידעו, כיון שהיו מולידות, כנראה, לכל בני ישראל,
שהיו פרים ורבים מאד.
ותחיין- ואם תאמר הרי הולידו בשדות, ולמה הוצרכו לכבש כלל. צריך לומר שהיו
בזמנים אחרים. יש לדון איזה היה קודם. כנראה, זה היה קיים אחר גזירה, שהיו
צריכים לכבשם בבית (כמו שאומר רש"י וכמו שמצאנו גבי משה לקמן (יב.)). אז,
אולי הולידו בשדות מאד אחר הגזירה או לפני הגזירה. שניהם צריכים ביאור; למה
לא עשו כן כל הזמן. וצ"ב .
צריך ביאור למה עזבו את הילדים בשדות. אולי ידעו שה' יעשה נס. גם אפשר
שחשבו שבוודאי ימותו בבתים.
מה אמך- יש להעיר שקרא זה הוא ביחזקאל, ולא נאמר כבר.
* יב.
:PROPERTIES:
:CUSTOM_ID: יב.
:END:
אף על עמו- עיין במה שכ' שידעו מתי נולד מושיען של ישראל. צריך ביאור, שטעו
מתי נולד משה. אז, לא היה להם לבדוק למשה (ולא היה ליוכבד להצפין את משה)
כיון שחשבו שנולד ביום שאמרו שלא ילד בו מושיעם. אולי חשש שלא היו
איצטגנינים שלו נכונים באותו אצטגנינות.
אלא בעולם הזה- משמע שלא נוחל עולם הבא עד שנולד. עיין בפרק חלק.
תינוק- יש להעיר שלא היה קול משה כקול תינוקים רגילים (כמו שאומר גמרא
לקמן). אז, יש לדון אם היו בודדקים לו, שאולי יחשבו שנולד קודם. יש לדון
כמה קודם לידת משה היה הגזירה. ותחשב. (גם אפשר שלא ידעו שקולו היה כנער.
דחוק.) גי"ל שאף אם קולו היה כנער, ממה שהוא בוכה כנגד תינוק אחר, יכירו
שהוא תינוק.
* יב:
:PROPERTIES:
:CUSTOM_ID: יב
:END:
לרחוץ מגלולי- יש לדון מה ר"ל:
- אולי ר"ל שירדה לטבול לגייר את עצמה.
- אולי הוזהרה על טומאה, ונטמאה מע"ז של אביה.
בעל מום- אם כן, נמצא שלא חש שיהיה לו מום, אלא שייפסל ללדבר. יש לדון למה
בעיה הוא אם נפסל לשירה, שיש דברים אחרים שעושים לווים. אולי רוצים שיהיה
טוב לכל דבר. גם יש לומר שלא היו כל כך לויים, והיה נצרך לשיר. דחוק.
ודע שאם רק צריך להיות ראוי לכל עבודה, קשה למה מקשה מזה בבכורות, יש לומר
שזה מום אבל לא עושה שאינו ראוי (חושב אני שגמ' בחולין אומר שאין מום פוסל
בלוי.) אולי יש שני בעיות: מום ממש ופסול כאן, אין מום ממש כי אם פסול.
עשיתו- קל לדחות שלא היה בעל בעל מום כשגדל, שקולו נשאר להיות של נער.
מלך בשר ודם- לכאו', לא סברו שהיה פרעה בשר ודם, שאמר שהוא אלוה, ואז אולי
אומר גמ' זה לכינוי. ודחוק. אף אם סברו שהיה בשר ודם, קצ"ב למה מזכירים את
זה.
אשתרבב- מעניין שאומר אמה להוכיח את זה, שהרי אמה משמע להיפך, שמשמע שהיתה
ידה רק אמה.
חופת נעורים- יש להעיר שלכאו'לא ראתה בחופתו, שנשא ציפורה כשהיה במדיון.
שראתה אותו מהול- יש להעיר שהיה אפשר שנולד מהול. לכאו', רק לא חששה לזה.
ויש להעיר שלמעשה כן היה, למקצת שיטות לעיל.
מי שעתיד- לכאו', אילו היה מת לא היה מהלל. ותו"ת.
* יג.
:PROPERTIES:
:CUSTOM_ID: יג.
:END:
ארונו- אז, צריך לומר שהיה לו ארון, ולא שהיה נקבר בלי ארון. אם כן, מעניין
איך אומר שנפלו עיני עשו על רגגליו, שהיו בארון. אולי נטלו אותו חוץ מארון
(ורק נשאו אותו עליו, והיה שם כשהניחו אותו). גם אפשר שרצה לומר שנפל על
מקום רגלו בארונו.
איגרתא- משמעש יש להאמין שטר, ואז משמע שעדות שבשטר מהני מדאו'. דנו
ראשונים בזה. יש לדחות שעשו כדינים שלהם, וכך היו דינים שלהם. זה מניח שאין
גויים צריכים לעשות כדיני תורה בממון. ויש לדון, שאולי היו צריכים רק אחר
מתן תורה. ותחשב.
פתחינהו יעקב- אין זה קשה להבין, שהיה חי, כמו שאומר גמ' בתענית.
צף- לכאו', לא היה אפשר לומר שמשה נטמא, שהרי עבד, קודם פרה אדומה. אז, קצת
צריך ביאור איך נטל אותו. אולי טומאה של קודם מתן תורה לא טמא אותם, כיון
שהיו כגויים (או שנשתנו[fn:2] ונעשו פנים חדשות במתן תורה).
* יג:
:PROPERTIES:
:CUSTOM_ID: יג
:END:
מרובים יותר- צריך לומר שאין זה כל כך גדול לדחות מה שכבודו במשה יותר
מבשאר בני אדם. ותו"ת. ויש לדון למה לא עסקו בו כולם.
אף מורידים- צריך ביאור למה יותר גרוע להתחיל משלא להתחיל. ויל"ד.
* יד.
:PROPERTIES:
:CUSTOM_ID: יד.
:END:
נדמה- עיין במק"א שדנינו אם אפשר לה' לעשות דברים הפוכים. אמרנו שלכאו', אם
ה' עושה שדבר נברא, אי אפשר לעשות שלא נברא. לכאו', כן נראה ממה שמניח גמ'
זה שרק נדמה כן, אבל לא היה כן. ותחשב.
אף משה- ואם תאמר רוב בנ"א לא יודעים מקום קבורתם. וי"ל שמת יודע עד שנקבר,
ואז יכיר איפה נקבר.
* יד:
:PROPERTIES:
:CUSTOM_ID: יד
:END:
סדר מנחות- צריך ביאור ל"ל דוחה שאז קדשו, ואז נפסל כיון שהוא בחוץ. משמע
שאם מקדשו בחוץ, לא נקדש ע"כ שנפסל.
* טו.
:PROPERTIES:
:CUSTOM_ID: טו.
:END:
לפי שאין באים- אם כן אין סברה של "לא יהא חוטא נשכר." לכאו', אין זה סיבה
לחייב, אלא יש סיבה אחר לחייב, ואומר שלא היה נראה לפוטרו מחמת שהוא חטא
(לכאו', ההו"א יהיה שווה למס') כיון שאז חוטא נשכר, אבל אותו סיבה (חוטא
נשכר) נדחה.
מנגעיה- נמצא שמניח שמה שמכפר הוא הבושת של הנגעים. זה מעניין.
* טו:
:PROPERTIES:
:CUSTOM_ID: טו
:END:
דאידחי- הדין הוא שאין דיחוי במצוות, ויש דיחוי בקרבנות. נראה שאולי דן אם
המים הם דין בקרבן או דין במצווה. ותחשב. גם יש לומר שדן אם זה, שאינו
מצווה, אלא דבר שכשנעשה עושה מקרה, הוא כקרבן או כמצווה.
קרקע נוב- ק"ק לל"א שמשכן קרוי מקדש ומקדש קרוי משכן.
איסי- מנחת סוטה- עדיין יהיה נפק"מ במביא עפר משם ומביא קרבן אחר שנבנה בית
אחר.
* טז.
:PROPERTIES:
:CUSTOM_ID: טז.
:END:
בטומאה קלה- זה קו"ח מעניין. חדא, אין זה טומאה כל כך, אלא הוא שום דבר רע
שנקרה לה. ותחשב. שני, שם אומר שיש איסור טומאה ששווה בשניהם, אבל כאן אומר
שעפרו ראוי לעשות בדיקה. ותחשב.
ספר- לכאו', זה רק לפי ריה"ג, שממעט מזה, אבל רבנן סוברים שאי אפשר למעט
ממנו כיון שמשמע סיפור, ולא ספר. ויש לדון, שאולי רבנן רק אומרים כן אחר
שיש ריבוי אחד, ואז סוברים שאי אפשר למעט ממנו כלום, מחמת אותו משמעות
שניה. אבל, אולי אין זה משמעות ראשון שלו. דחוק.
והלכה- לא משמע- צריך ביאור למה אומר שהקראי אסמכתא, שהיה אפשר לומר שחולק
על כל הדרשות, ומי שאומר אותם בגמ' אינו הוא. ותו"ת.
עוקרת- עיין ברשי שמניח שר"ל שמיקל. ויש לדון, שזה מקיל, שדוחה איסור בגד
אשה.
* טז:
:PROPERTIES:
:CUSTOM_ID: טז
:END:
מני ר"ע- היה אפשר לתלות המח' ברבם, אלא שמצוי יותר שיחלקו הם וימצאו הם
במשניות.
סמוך- צריך ביאור למה צריך לנקוט לוורידים, שהרי רק צריך לשחוט סמוך למנא
ראשון. אף אם צריך לשחוט על גבו, עדיין צריך ביאור. לכאו', אי אפשר לנקוט
ורידים מיד, שהם מקום החיתוך. אז, קשה למה מסלק ורידים, ולא כל העוף. אפשר
שנוקט אותם כדי שלא יצא מהם דם עד שיביאו למנא שני. ותחשב.
קטנה ונדחית- לכאו', כבר דן בזה.
מכשיר- צריך ביאור מה נחשב מכשיר. ותח'.
* יז.
:PROPERTIES:
:CUSTOM_ID: יז.
:END:
וראו- משמע שחלק מזה הוא מה שיש בו רצועה. באמת, יש לדון אם היה מצווה כלל
בלי רצועה, שלא יכול לשבת שם בלי רצועה. ותחשב. אולי היתה מצותו להיות
במקום אחר, ושם לא היה שם ה' עליך או לא היה נראה. ותחשב.
והא לית- אגב, נראה שאולי לא סובר ר"מ שמה שאינו מהני לתנאי הוא מפני שלא
משמע אותו די, אלא מוכיחים שרבי מאיר סובר כן, שאי לאו הכי, אי אפשר לדייק
ממה שכפלו שצריך לכפלו, שאין חילוק ביניהם. ויש לדון, שצריך להיות שום
חילוק, שאי לאו הכי, קשה למה כפלו. ותחשב.
דאשה- לכאו', היה לו לומר שהוא מפני שבשל איש יש ספיי"ס בין אל"ף ושי"ן,
ולא שיו"ד מפסיק, שכיון שמסלק ה' את שמו, אין עוד י'. ויש לדון.
הנאה- צריך ביאור למה אין שכר במה שאנו יכולים לקיים עוד מצווה (ה' חפץ
למען חפצו).
הנאה- לזכות- לשון זה מעניין, שאומר שמזכה אותם, ולא אומר שמכפר עליהם.
ותחשב.
* יז:
:PROPERTIES:
:CUSTOM_ID: יז
:END:
קודם... פסולה- עיין לקמן, שדן גמ' אם כשר כשנכ' בס"ת. ויל"ד שמוזר שנכ' כל
הס"ת אחר שבועה. אולי השאירו פרשת סוטה לזה. ומוזר שיעשו כן בלי כוונת
סוטה. אולי יש כוונה לסוטה ולספר תורה. אולי על פי זה (שמוכרח שיש שני
כוונות כאן) נוכל לתרץ למה שהקשה תוס' בגיטין (כ.).
קנקנתום- עיין במה שכ'. עיין ברשי ותוס' וראשונים בגיטין (יט.).
אגרת- ואם תאמר הרי כל כ' צריך שרטוט. שו"ר בתוס'.
* יח.
:PROPERTIES:
:CUSTOM_ID: יח.
:END:
על שני דפים- עין בתוס' בגיטין (כ:). צריך ביאור איך ישיב רש"י לזה.
מי בעינן נמי מחיקה לשמה- עיין בגמ' לקמן, שמביא מחלקת אם צריך כ' לשמה או
רק מחיקה לשמה. לכאו', דיון של גמ' זה מניח שצ' כ' לשמה.
לשמה- מעניין שאינו לשמה, שמכוון שתשתה מזה. צריך לומר שכיון שיודע שאף
חבירה תשתה ממנו, הוא לשמה ולשם חברתה. זה קצת מחודש, שנמצא שאף שרק רוצה
במה שהיא תשתה, ולא במה שחברתה תשתה, כיון שיודע שחברתה תשתה, הוא לשמה
ולשם חברתה.
ודע שלכאו', רק שני יהיה פסול, אם לא שיניח שמכוון למחוק אף שני לכאן בשעה
שמוחק ראשון. ותות
שבועה- צריך ביאור איך יש שבועה על אלה. בדרך כלל, שבועה או הוא דרך חזק של
אמירת דבר, או עשוה איסור. אולי כמו ששבועה עושה איסור, יכול לעשות עונש.
ותחשב.
* יח:
:PROPERTIES:
:CUSTOM_ID: יח
:END:
משוי ליה כי ערוה- זה מעניין, שהרי צריך להיות אשת איש. משמע שכל אש"א שהיא
ערווה יש לו דין זה, ואין יותר שצריך. ותחשב.
לכשתטמא- רק יש מקור אחד לדין גלגול. צריך ביאור, אז, מהי"ת שלא רק קאי על
שבועה. נראה שאולי אי אשפר לשבועה לגלגל, שיש חילוק רב בין שבועה על עבר
ועל עתיד, שאחד עושה איסור ואחד רק אומר דבר, ועונשו משום שקר. (אין זה
מוכרח.) אז, מגלגל שבועת אלה, אבל מזה, רואים גלגל כל שבועה, שאלה בא על
ידי שבועה.
* כ.
:PROPERTIES:
:CUSTOM_ID: כ.
:END:
נגנזת- צריך ביאור למה לא נקרא. אולי הוא למד"א שלא נכ' מגילה. (ואולי זה
לא נח' מגילה מלאה. חושב אני שאומר גמ' בגיטין שנח' מגילה.)
* כ:
:PROPERTIES:
:CUSTOM_ID: כ
:END:
ונזרעה- יל"ד מהי"ת שהזרע יהיה בן תשעה חדשים, ולא בן שבע חדשים.
* כא.
:PROPERTIES:
:CUSTOM_ID: כא.
:END:
על שלשה פשעי אדום- זה מעניין, שזה אומר שאין ה' מקפיד עד שלש עבירות. אבל,
לא אומר שכשה' מקפיד, אלא שתולה מחמת מצווה, שונה שלש פעמים. ותחשב. גם
צריך באיור ל"ל אומרים שהזמן הוא ארבע חדשים, ולכן הוא שנים עשרה חדשים.
ותשחב.
דמצווה- ק"ק, שגבי נבוכדנצר היה מצווה. (ויש להעיר שמצאנו במק"א (פ"ק דב"ב)
שצדקה מצלת ממוות.)
ואין עבירה- מעניין שתולה בשכר. היה אפשר לומר שדן בשמירה שלו. ותחשב. אולי
זה בכלל שכר.
מציל- עיין בקידושין (לט:).
רבי יוחנן- צריך ביאור, שבתענית אומר שהיה אביון. אולי לא נתנו לו כל כך.
ויש לדון, שהיה לו לשאול ליותר, ולא ללכת לעבוד. ואולי לא רצו לתת לו יותר.
גי"ל שזה היה אח"כ. ויש לדון, שמרשי משמע שהכל חייבים לתת לו אז. אולי הכל
חייבים, אבל נתנו לו בי נשיאה. זה מעניין, שנמצא שבי נשיאה לא היו נצרכים.
גי"ל שנתנו לו אחר שיצא הוא ואילפא, אבל קודם שנעשה ראש ישיבה. דחוק, שאז
מה לנו שנעשה ראש ישיבה, שאף בלי זה היה לו ממון. וי"ל שרק ר"ל שעכשיו מחמת
שהוא ראש ישיבה הוא עשיר. ותחשב.
* כא:
:PROPERTIES:
:CUSTOM_ID: כא
:END:
חייב אדם ללמד- החשש הוא שתוציא לעז. יש לדון מהו הבעיה:
1. היא תחשב שהתורה אינה נכונה.
2. היא תבזה את התורה.[fn:3]
3. אחרים יחשבו שתורה אינה נכונה.
4. אחרים יבזו את התורה.
5. היא לא תקפיד על מצוות התורה.
6. אחרים לא יקפידו על מצוות התורה.
אם נאמר כחמישי, יש לדון, שכבר לא מקפדת. ויש לדון:
1. בלי זה, אולי תשוב.
2. אולי רק תעבור על א"א שיש לה תאווה גדולה לה.
לאו אורח- יש לדון ל"ל נקט נגיעה. אולי לא כ"כ קשה להציל בלי נגיעה. גי"ל
שאסור ליגע, ואף מחמת הסכנה. ותחשב.
להשלים- ואם תאמר לא יקח העני. וי"ל שלא יודע עני דין זה. (גם אולי אין
נותנים למי שעשה עצמו עני כזה. וצריך להגדיר.)
* כב.
:PROPERTIES:
:CUSTOM_ID: כב.
:END:
אשה פרושה- לכאו', היא הציילנית. אולי גם אלמנה בכלל זה, שרש"י משמע שהיא
מראה א"ע כצדקת.
* כב:
:PROPERTIES:
:CUSTOM_ID: כב
:END:
בשווים- היה אפשר לומר שאסור רק בשווים, ורבה היה הכי גדול.
שווים- גדול בשנים- לכאו', הוא מפני שצ' שום פסק. ותו"ת.
רבה- עיין שם, שרש"י גורם רבא. אם כן, אף כאן יגרוס רבה. ותו"ת.
בשווים- לא היה שווה לרב יוסף, כמו שאומר גמ' בהוריות[fn:4]. אולי חלוק הוא
כיון שמחל לו.
ודע שעל פי זה, יש כמה דברים שצריכים ביאור:
- רבי עקיבא היה לו כד אלף תלמידים אחר כד שנים. לא היה יכול להורות להם
(עיין בתוס'). אולי היה שווים, או אולי היה הכי גודל בשנים.
- ראב"ע היה נשיא כשהיה בן יח'. לא מסתבר שהיה הכי גדול, שלא רצו ראשון
למנות אותו. ויש לדון, שאולי לא רצו למנות אותו מפני גילו.[fn:5]
לא תיתני- לא רואים מבריי' זה שהם רעים. אולי ר"ל שאינם כלל, כיון שכל מי
שעושה כן מיד עושה לשמה (והרי מקורו לא עשה לש"ש עד לאחר כמה וכמה שנים).
נראה שרואים שאין בריי' טוב ממה שלא הזכיר לשמה.
פרוש- יש מאלו שנראים שהם שווים.
* כג.
:PROPERTIES:
:CUSTOM_ID: כג.
:END:
שבעלה בא עליה- מעניין שצריך לשרוף. תלוי בצדדים בגמ' לעיל.
* כג:
:PROPERTIES:
:CUSTOM_ID: כג
:END:
זרעו מחלל- נ' שדייק מזרעו ולא מאשתו כיון שיותר הוא בפשטות הקרא. גי"ל
שהוא מפני שחילול זרעו יותר דומה לשלו משאשתו דומה לשלו. ותחשב.
* כד:
:PROPERTIES:
:CUSTOM_ID: כד
:END:
אנא דאמרי- היה אפשר להעיר כן על הו"א של גמ'.
* כה.
:PROPERTIES:
:CUSTOM_ID: כה.
:END:
כיון דקפיד- עיין במה שבאר רש"י. ואם תאמר הרי לא קפיד, שכך הוא הציור. ויש
לומר שקפיד, אבל עדיין רוצה לינשא לה. כיון שכן, אומר שלא קפיד.
בן סורר ומורה- צריך ביאור איך זה יהני, שהרי נידון הוא על שם סופו. אולי
מה שאביו ואמו יכולים למחול לו מגלה שמה שעשה כבר אינו כל כך רע. גי"ל שרק
נענש בצירוף עבירה שעבר. אם הייתי קצת סייקולוגיס"ט, הייתי אומר שאם היו לו
הורים שמוחלים אותו, אז לא יגדל לאדם רע. ותו"ת.
רב אחא ורבינא- עיין בגמ' בפסחים שאומר שבכל מקום שחלקו רב אחא ורבינא,
רבינא מיקל והלכה כמותו. יש להעיר שכאן אומר גמ' שמסתבר להחמיר. אולי שם רק
נותן כללים למקום שאין לו הוכחה מבריי'. דחוק.
חבירי שבדרום- היה אפשר לציין לגמ' ביבמות שאומר שאחר מיתת תלמידי ר"ע, בא
אצל רבותינו שבדרום.... אולי מה שהיו רבני דרום יכולים להצליח, או הסיבה
שלהם הלך, הוא שהיו מחמירים כל כך על מחלקת, כמו שראינו הכא. דחוק, שמח' זה
איננו בעיה מפני שאין שלום, אלא מפני שנראה כשני תורות. ותחשב.
* כה:
:PROPERTIES:
:CUSTOM_ID: כה
:END:
איילונית- זה עוד שיטה שלא יכול חנה לסבור כמותו (עיין בברכות בטענתה),
שכבר דורש הקרא, ולא סובר כר"י ור"ע, ועוד שאז אולי לא יהני בה המים כלל,
שאולי היתה איילנונית.
* כו.
:PROPERTIES:
:CUSTOM_ID: כו.
:END:
במתנוונה- מהו דתימא- לשונו קשה, שלא בא אותו הו"א להוציא מן הצד שזינתה,
שמשנה אומר שהיא מותרת. אז, היה לו לרש"י לומר, "מהו דתימא, לא מתנוונא
באקראי, אלא מפני זנות באונס."
* כו:
:PROPERTIES:
:CUSTOM_ID: כו
:END:
אסורה וקיימה- אגב, צריך ביאור מהו המקור לאיסור לאשה להיבעל לגוי. לא קל
לגמ' למצוא מקור לאיסור לאיש לבעול גויה, וצריך לדון אם יש יותר מזה בנבעלת
לגוי.
פריצותא מי אסר- עיין במה שפ'. לא פ' שר"ל שהוא מותר לגמרי, לשני טעמים.
ראשון, אין זה ענין של גמ', שבא לדון באיסור של איש ואשה ומסתמא בזה היה
מדבר. שני, אולי הוא אסור, כמו שמבואר בשבת (קרוב לדף ט). ותחשב.
ובת כהן- עיין בקראי שהביא. יש להעיר שיש קראי חלוקים לומר שאין קידושין
חלים בין ישראל לגויה. מעניין שצריכים קראי חלוקים. ותחשב.
* כז.
:PROPERTIES:
:CUSTOM_ID: כז.
:END:
נושא אדם- לכאו', יכול לישא בת דומה לכת' לפי המתיר, שהרי סומכים על רוב
לכתחילה, לכאו'. ויל"ד. לפי זה, דע, יכולים לת' קושיה. למי שאומר שישא בת
דומה, נמצא שאין חלק מן המשנה שהוא נכון, וזה קצת מוזר. למש"כ, אולי יותר
קל להבין.
בת דומה- לכאו', חולקים אם בת דומה מותרת, והולכים בתר רוב, או לא מותרת.
ויש לדון שלא נראה שמתיר בתר רוב, אלא מחמת חזקת כשרות. ויש לדון, שאין קטן
שנולד בחזקת כלום. אז, צריך להיות רק מפני רוב.
וזו באה מביאה- צריך ביאור ל"ל רק אמר שהיא נשואה, ואז כל אדם יעשה ממזר.
ותחשב.
היתה פרוצה ביותר- יש להעיר שנמצא שהולכים אחר רוב, ולא הולכים אחר למי היה
המנין הכי גדול (שאל"ה, היה צריך לומר שיש לחוש שלאחר היה רוב בעילות, ולא
שלאחרים היו. ותו"ת.). ותו"ת.
אין אשה- עיין במה שכ'. נמצא שרש"י מבאר שהבעל הוא השמור אותה מזנות. זה
קצת מעניין, שאז צריכים לומר שהבעל, שהוא עדיין נשוי לה, חושד שהיא מזנה.
אולי היה אפשר לפרש שהאשה לא רוצה להוליד ממזר, ואז שומרת א"ע מזנות אז. אף
אשה לא יודעת מהו קרוב לווסתה, שלא יודעת מתי תבוא. ולא נראה שווסת לא רק
ר"ל זמן ראייה, אלא זמן ראייה הקבוע. אז, בהכרח תדע. ותחשב.
* כז:
:PROPERTIES:
:CUSTOM_ID: כז
:END:
ר"ע תלמידך- לכאו', היה תלמיד תלמידו, שהיו לריב"ז רק חמש תלמידים, ולא
נמנה ר"ע, אלא היה תלמיד של ר"א ור"י. אולי מי שהיה תלמיד של ר"א נחשב
תלמיד של רבו, שרק היה אומר מה שאמרו רבותיו, כמו שאומר גמ' בסוכה וברכות.
ותחשב.
* כח.
:PROPERTIES:
:CUSTOM_ID: כח.
:END:
דמודע לה- משמע שהוא להגיד לה, ולא להגיד לכל העומדים שם. אם כן, נמצא
שחוששים למה שיקרה בין זמן שמתחיל לעשות שלא כזה, וזמן שמתה. (ודע שאם כן,
מס' אף צריכים להגיד לו, שכמו שהודעה שלה הוא לה, אף יהיה שלו לו. אם כן,
צ"ל שאף הוא בא לבדיקה.)
* כט.
:PROPERTIES:
:CUSTOM_ID: כט.
:END:
תרומה נמי- יש לדון בזה, שהרי רק מצאנו שעשה ספק זונה כזונה לענין לאו של
ביאה עם מי שנתה עליו. לכאו', איסור כהונה חמור, ונלמד ממנו בקל וחומר, אבל
יש לדון אם איסור תרומה יכול להיות נלמד ממנו. אולי שניהם איסורי לאו, ואז
לומדים זה מזה. ותחשב.
מילתא דאתיא- אגב, אבאר פשט אחד במילתא דאתיא בקו"ח. יש אומרים שנכ' כיון
שיש פירכא באותו קל וחומר. לכאו', לא מניחים שיש פירכא בקל וחומר אם אין
אנו חושבים עליו, אבל אם כתבו קרא, יש ראיה שאם היינו חושבים די, היינו
מוצאים אותו, וצ"ל שרק לא חשבנו די. רוצים לדרוש דבר אחר, ולא לומר שטרח
וכ' קרא, כיון שמסתבר שאין אנו טועים. ודע שאם כן כל קולא שבא ממה שלא
מניחים שאנו טועים יבוא גם במה שנלמד מן הדרשה. ותחשב.
אגב, יש להעיר הערה אחרת, והוא שצריך ביאור למה אומר, "טרח וכ'," ולא רק
שכ'.
* כט:
:PROPERTIES:
:CUSTOM_ID: כט
:END:
אי ס"ד- צריך ביאור למה יותר טוב ללמוד משם. ותחשב.
* ל.
:PROPERTIES:
:CUSTOM_ID: ל.
:END:
דאם איתא...- גם היה אפשר להביא ראיה ממה שלא אומר ש"אשר יגע בכל טמא" קאי
על שלישי ויביא מקור משם.
ונותנת פחות- עיין במה שכ' בדין פחות מכביצה. עיין בסוף פ"ק של פסחים שריש
מביא שני לשונות בזה.
* ל:
:PROPERTIES:
:CUSTOM_ID: ל
:END:
כסופר- עיין במה שבאר בלשון. שמעתי צד שלשון זה בא מלשון פרוסה, ורצה לומר
חצי. ותו"ת.
* לא.
:PROPERTIES:
:CUSTOM_ID: לא.
:END:
ולא לפוסלה- יש להעיר שכיון שכן, יהיו נאמנות. ר"ל, גלגל החוזר הוא, שאם
אין נאמנות לענין הפסד כתובה, לא ישקרו. אז, יש להאמין אותם לכל דבר.
ותו"ת.
* לב.
:PROPERTIES:
:CUSTOM_ID: לב.
:END:
וברכת כה"ג- מכאן והלאה במשנה, לא מבאר מקורו בפרק זה בגמ'. לכאו', מקור
לברכות יהיה שנתקנו כמו ברכות וקללות. אבל, צריך ביאור מהו מקורות לד"א.
אולי גמ' לקמן יפרש.
לשון הקודש- יש לדון אם הקפידא הוא שיהיה אותו פירוש באותו לשון או שיהיה
אותו פירוש עם אותם מילים. ותחשב. גם יש לדון, כשיכול לומר אותו בכל לשון,
אם מהני מפני פירושו או מפני דמיונו (בפירוש) לאותם מילים בלשון הקודש.
ותחשב על זה.
פרשת סוטה- צריך ביאור מהו הקל וחומר. ראשון, יש להעיר שכאן היה נראה לומר
שבודק, אבל לא מתיר. יש לדון אם מתיר בחליצה. משמע שאינו מתיר. אבל, אף אם
אינו מתיר, צירך ביאור, שהרי אז עושים דברים חלוקים, ואולי צריך לשון הקודש
לאותו דבר אחר שיש לו. ותחשב.
גם צריך ביאור מהו הקל וחומר, שהרי כאן יש איסור לאו, ואף שם יש איסור לאו.
אז, צריך ביאור מהו הקל וחומר. ותחשב.
* לב:
:PROPERTIES:
:CUSTOM_ID: לב
:END:
שלא להוציא לעז- משמע שרק אומרים לה דין אונס. כן נראה גם כן ממה שבן עזאי
אומר שצריך אב ללמד את בתו דין זכות תולה. צריך ביאור ל"ל יאמרו לה כהנים
דין זה.
להודיע צערו- יש להעיר שהסיבה שאומר שם לא נוגע כאן.
מפני מה תקנו- גמ' ברכות אומר שחנה היתה מדברת בלחש. לומדים ממנה לדבר כן.
צריך ביאור מה הועילה בתפלתה בלחש. יש לומר שאז אם צריכה להתוודות, לא
יבינו בה. ואם תאמר אם כן קשה ל"ל יתקנו שווידוי יהיה בלחש. צ"ל שיכירו
שמתוודה. אז, בחנה ג"כ י"ל שיחשבו שהיא מתוודה. אולי מה שהוא כל תפלתה מראה
שאינו ווידוי. גי"ל שידוע היה על חנה. (קשה, שעלי לא ידע, ואף עלי לא חשב
שהיא מתוודה.)
לכאו', תקנו כן אחר שראו את חנה והכירו במעלות בתפלה כזה. יש להעיר שלכאו',
עלי סבר שאינו טוב לעשות כן. אז, קשה למה נעשה כחנה יותר מכעלי. אולי הכירו
שכאן היתה צודקת.
מפני מה- עיין בברכות שאומר שלא להתפלל בקול רם, שנראה שלא מודה בה'. נראה
שאולי זה רק מפני שמשנה מן הדין שצ' להתפלל בלחישה. ותחשב.
והא איכא- יש לדון מה מקשה:
- אולי מקשה שאם כן, נתקן אף על זה.
- אולי מקשה מה מהני, כיון שכבר יש חילוק זה.
ע"ז- יש לדון, אז, למה שוחטים קרבן של ע"ז בצפון. אולי לא צריך כל כך בושת,
ויש שלא יכירו בזכרותו, או שלא ידעו דין חטאת ועולה.
צפון- יש לדון מה היה לו להיות מקומו. נ' שני ביאורים:
- לא היה מקום אחר, אלא רק דן למה כשאומר אותו, מדגיש מה שהוא מקום העולה.
- אולי היה לו להיות לו שום מקום אחר. יש לדון למה:
  - ר"י קבל שכן הוא, שיש מקום אחר שיותר טוב לו.
  - יש לומר כמה שכתבנו בשיח שי על יבמות, והוא שאולי כיון שהוא קרבן אחר,
ומקום שחיטה הוא, כנראה, חשוב להרצאה, לא מסתבר שיהיה לו אותו מקום,
שאיך יהיה אותו מקום עושה הרצאה חלוקה. ויש לדון, שהרי עדיין שווה הוא
בעבודות, ואין זה בעיה.
* לג:
:PROPERTIES:
:CUSTOM_ID: לג
:END:
אתם במה למדנוה- לכאו', זה מוכיח שהוא ג"ש ממש, ולא רק שכיון שהוא מילה
שווה, מניחים שפירושו שווה. גי"ל שאף על הוכחה כעין זה חולקים צדוקים.
ארון נוסע אחר- צריך ביאור מגמ' בברכות שאומר שהיה הארון משווה הכל לפניהם
וי"ל שהיה שמווה אותו מן האמצע ללפניהם. ותחשב. אם לא צריך להיות על מקום
שמשווה, צריך ביאור קצת ל"ל רק ישווה את כל המדבר מיד. אולי רצה ה' שיראו
בנ"י שמשווה לפניהם. דחוק.\
אגב, גם צריך ביאור, שהרי קרא אומר בפרשת בהעלותך שארון הלך לפניהם שלש
ימים. אם כן, אינו כגמ' זה. גם יש להעיר שאם כן אינו כמה שאומרים בני אדם
שממש לא ידעו מתי צריכים לצאת, שהרי ארון היה יוצא שלש ימים לפניהם. ותחשב.
כדרך- לכאו', זה מעניין, שנמצא שה' עשה דבר על פי מה שיקרה מחמת עבירות שלא
כבר נעשו (לכאו'). אם כן, יש שאלות בזה בענין בחירה (בפשט של אור שמח).
אולי לא ידעו שלכן צווה ה'. אולי כבר עבר משה מה שיגרום לו שמת (צל"ע
בקראי), ואולי גם מה שגרם שענן יצא נעשה. ותחשב.
* לד.
:PROPERTIES:
:CUSTOM_ID: לד.
:END:
שנים עשר מיל- לכאו', הכל כאן יש בו שלש צדדים. בני ישראל נטלו מים שהיה יב
מיל על יב מיל על גובה המים. אז, צריך לומר שגובה המחיצה היה (ויש לדון אם
זה כולל גובה המים שרגיל להיות שם) יב מיל על יב מיל על גובה מים רגיל. אז,
לכאו', צריך לומר שהיה רוחב של הירדן כמו גובה הרגיל שלו. ותחשב.
צריך לבאר איך נמצא שהוא יב מיל על יב מיל, שלכאו', כך היה אם היו בני
ישראל רק הולכים בתוך ירדן פסיעה אחת. אבל לא כן הוא, אלא שהלכו בו, ופסעו
את כולו, ויצאו ממנו. אז, הוא יותר משיעור יב מיל על יב מיל. ותחשב. אולי
מחנה בנ"י היה מחסר כבר, כיון שלא היו הכהנים שם. דחוק, שלכאו', לא היו
יותר מארבע כהנים חסרים. ותחשב.
מים קלים- לכאו', צריך לומר שכשמים יצא, לא אותו מים בא לעשות מחיצה, שאם
אותו מים בא, אז פשוט שיהיה יותר, שכדי לבנ"י להתחיל לבוא, צריך שכל היב
כבר יצא. ותו"ת.
שלש מאות- עיין ברשבם בפסחים שאומר שכשאומר לשון זה, גוזמא אומר. מזה, יוצא
קצת קשיא על גמ' לקמן (ע"ב).
עוד בירדן- אז, אף אם אין מים קלים, יהיה יותר מיב מיל.
לא היו באותו עצה- ואם תאמר אז יכירו שכלב משקר כשהיה מראה שרצה להיות עם
המרגלים לבנ"י. וי"ל שחשבו שחלף דעתו. עוי"ל שידעו, אבל ציבור לא ידעו.
גי"ל שחשבו שרק סבר שלא יביאו ענבים להראות שא"י רע. ותו"ת.
* לד:
:PROPERTIES:
:CUSTOM_ID: לד
:END:
פירש- משמע שלא פ' ממרגלים אלא מעצתם. משמע שהיה עם עצתם מתחילה.
אבותי- משמע שמותר להתפלל לצדיקים להתפלל לו.
כגן ה'- קשה ל"ל נקט א"י שם. ותו"ת.
* לה.
:PROPERTIES:
:CUSTOM_ID: לה.
:END:
ראש קטוע- יש להעיר שהיה פחות מחמישים. לבני אדם שזקנו כל כך, לא כ"כ קשה
שלא הוליד כבר.
ראש קטוע- יש לדון למה חשש לכלב, שלא היה ראש קטוע. .אולי היה אז עדיין
קטוע. גי"ל שהיו מוצאים דבר אחר עליו.
הריני מכשלך- צריך ביאור איך זה שייך למה שקרא לעוזא. אולי לא היה חושש
שיפול אם היה על לויים.
* לה:
:PROPERTIES:
:CUSTOM_ID: לה
:END:
סיד- אף לר"י היה אפשר לומר שיש בעיה מח' סיד, שהיה להם לקלוף.
* לו.
:PROPERTIES:
:CUSTOM_ID: לו.
:END:
והעלו- משמע שהעלו קודם שברכו. עיין במשנה שלא משמע כן. קראי משמע כן.
* לו:
:PROPERTIES:
:CUSTOM_ID: לו
:END:
תיובתא- צריך ביאור איך דורשים שהחציו אומר שהוא המעט, ולא שהוא הכי חשוב
והמרובה. ותחשב.
זרעיה דיוסף- יש להעיר שבב"ב מבואר שהיו כמה ילדים. צ"ל שאף ילדים היו על
ההר לברכות וקללות.
יאבד הון- היה אפשר לומר שקאי על מעשה זה, ואומר שיאבד שבטים. ותו"ת.
יהודה מאי היא- ע' לעיל, שלא אמר כן. גם ע' לקמן, שאומר שכר אחר על זה.
ממשלה- ר"ל על שם זה נתן לו יעקב הממשלה. ואם תאמר זה קרה אחר זמן. י"ל כן
גם על שם יהודה. יש לדון, שגמ' ברכות אומר ששמא גרים, אבל לא אומר כן על
ברכת יעקב. ותחשב.
* לז:
:PROPERTIES:
:CUSTOM_ID: לז
:END:
מח' של שש מאות...- יש לדון למה אין מח' בריתות של ערבות על כל מח' של כל
אדם.
* לח.
:PROPERTIES:
:CUSTOM_ID: לח.
:END:
כל הימים- צ"ב איך רואה מזה שאינו רק בעבודת ציבור, שהרי יש עבודת ציבור
בכל יום. אגב, גם צ"ב למה צריך מנין אם אינו צ"ל עבודת ציבור. אולי תפלה
בלי ציבור לא כל כך נקרא עבודה.
בנ"י- נמצא שכל אלו לא נחשבים בכלל מילים "בני ישראל."
* לח:
:PROPERTIES:
:CUSTOM_ID: לח
:END:
אישתייר- מעניין שאם מברך לעם שבשדות תלוי באם יש בנ"א שם. ותו"ת.
* לט.
:PROPERTIES:
:CUSTOM_ID: לט.
:END:
ולא פסעתי- לפיכך- משמע שצריך כיון שנ' כפוסע על ראשם. אין זה מוכרח; אולי
צריך מסיבה אחרת, ורק נקרא כן מחמת זה.
* מ.
:PROPERTIES:
:CUSTOM_ID: מ.
:END:
עמי ואחי- לא הבנתי איך רואים מזה אימה; אולי רק רצה להיות כאח להם אם
יכול.
* מא.
:PROPERTIES:
:CUSTOM_ID: מא.
:END:
שמע- מעניין שמה שאין מתורגמן יתיר, שזה רק עשוה שיש יותר הפסק. ותו"ת.
אחינו אתה- נמצא שאף שלא היה כשר להיות עבד, כמו שמפרש גמ', יש עליו דןי
"שום תשים."
עזרת נשים- אם כן, לא היה בעיה לירבעם. צריך לומר שכשעשו אותו מלכי בית
דווד, עשו אותו בתוך העזרה. ותחשב.
* מא:
:PROPERTIES:
:CUSTOM_ID: מא
:END:
והכיר- מוזר להיות מי שמוזמן הורג מי שהזמינו. ותו"ת.
עוברים- יש לדון איך יודעים (עיין בגמ' לעיל שאמר שצריך מה שהיה אספקלריא
המאירה).
* מב.
:PROPERTIES:
:CUSTOM_ID: מב.
:END:
משוח מלחמה...- בגמרא מבואר שיש שלש חלקים של הדיבור: יש דיבור כהן שמשמיע
כהן (אגב, באותו דיבור, יש לדון אם הוא המשמיע או כהן אחר משמיע. יש לדון
איזה משניהם הם הממונה שנקרא "משוח מלחמה." נראה שאותו כהן משמיע, שהיכי
תיתי שכהן אחר ישמיע. עדיין יש לדון אם צריך להשמיע, או יכול להיות כהן
אחר, או אולי שום איש אחר, משמיע.), יש דיבור כהן שמשמיע שוטר, ויש דיבור
שוטר שמשמיע שוטר. יש לדון איזה צריכים להיות בלשון הקודש.
כה"ג- אז, לכאו' לא דורשים רק שלא צריך להיות כהן גדול, אלא שלא יכול להיות
כהן גדול.
קריאת שמע- יש לציין לגמרא מנחות (צט) שבזה, למקצת תנאים, מקיים חיוב של
"והגית בו יומם ולילה."
* מב:
:PROPERTIES:
:CUSTOM_ID: מב
:END:
על יד בין איש- אף שהה' שרצה להפילו על יד בן איש הוא אותו ה' שגרם שייקרא
בן איש, צריך לומר שלא רק נקרא בן איש מחמת זה, אלא היה אותו שם מכוון למה
שהיה, באופן אחר, בן איש, ורצה להפילו ביד בן איש. אז, נמצא שמה שנקרא בן
איש היה סימן. כמו כן, יש לומר שלא היה יכול לקרוא לכל מי שירצה בן איש, אם
לא שיהיה, בשום אופן, בן איש. וצריך ביאור מהו כוונת בן איש, שהיה נראה
לומר שהוא רק שהוא בן של איש. אם כן, יכול להיאמר על כ"ע.
דוד הדר- עיין במה שבאר. לא באר שהוא רק מפני שגם אמר כן על גלית, שהרי אף
גלית עשה כן, כמו שפרש רש"י. אז, צריך לפרש שהוא מפני שטען שבא בה'.
ארבעים יום- עיין ברשי. לא הבנתי כל כך, שלא מצאנו ארבעים יום שגרמו בני
ישראל שהתורה יאוחר. אם דנים בימים שמאורח בלי גרמתם, אז ימנה יותר מאלפים
שנה.
כדי לבטלן- מפני שק"ש של שחרית וערבית עושה שהם מנצחים. יש להעיר שר"י הוא
האומר שניהם.
הכל דשו- יש לציין לגמ' בנדה (קרוב לדף ל) שאומר שביאה טוב לוולד. אז, אולי
לכן היה גלית כל כך טוב. אבל, יש להעיר שלא לעולם טוב לו (עיין שם), אלא
לפעמים רע לו. וצריך לעיין שם ולחשוב.
* מג.
:PROPERTIES:
:CUSTOM_ID: מג.
:END:
לקח- יש לציין לגמ' בסוף ברכות בדיון על מה מברך שהחיינו.
לא היה זז- נראה שהסיבה שאלו היה זזים הוא כדי שידעו השוטרים מי הם כדי
להביאם לספק לאחיהם שבמלחמה.
ירא מעבירות- מזה משמע שלא צריך להיות ירא מעברות ממש, אלא שהיה לו להיות
ירא (שהרי היה קל לתרץ שהצירו של גזלן הוא שלא שב, ולא ירא).
* מג:
:PROPERTIES:
:CUSTOM_ID: מג
:END:
עלו מאיליהם- לא הבנתי כל כך מהו הראיה מכאן, שרק רואים שמה שעלה באותו
חסרון מחשבה חייב. אבל, לכאו' ההו"א לפטור כאן הוא שבתחילתו היה מחשבה
שפוטרת. אז, קשה איך לומדים נגד זה.
שני שותפים- כל אחד ראוי לבוא לו חלק. אז, החילוק בין זה לאשתו הוא לכאו'
שכבר יש לאידך חלק עכשיו. (אולי הוא מה שגם לחבירו יבוא בוודאי חלק).
ולוקמה- לא הבנתי ל"ל מוקמים אותו בנותן על אילנו של חברו ברשות.
* מד:
:PROPERTIES:
:CUSTOM_ID: מד
:END:
בהא- לשון הציור, ולשון "בהא," משמע שזה דרגא של יראה שהוא יותר ממה שמזכיר
רבי עקיבא. אולי החילוק הוא אם נראה שהוא ירא או לא נראה, אבל עדיין ירא.
מלחמת- יש לדון ל"ל מזכיר למה לחמו, ומזכיר ציור.
* מה.
:PROPERTIES:
:CUSTOM_ID: מה.
:END:
המזוג- אין זה שיעור מזוג סתם. עיין בשבת, בתחלית פרק המצניע.
כצף- יש לדון במה הוא כצף.
* מה:
:PROPERTIES:
:CUSTOM_ID: מה
:END:
סברוה- עיין במה שאומר. מעניין, שלכאו', אביי הוא שמביא ראיה. היה נראה
לומר שהם רצו להבין ראיית אביי, וכך פרשו. לא משמע כן כל כך מרשי.
לא בא לידינו- עיין במה שבאר. רגילים העולם לומר פשטים יותר מוזרים מזה.
רישא היכא דנפיל- צריך ביאור ל"ל אומר שזה נוגע לענין עגלה ערופה, והוא דין
חלוק ממח' שני. ראשון הוא לדעת מה קרה, ומה היתה מקום נפילתו, ושני הוא איך
ללמוד ממקום נפילתו. אולי לא מודדים ממקום נפילתו; צריך ביאור ל"ל.
דרהיט- ואם תאמר איך ירוץ. אולי הוא מפרכס. יל"ד אם נחשב כבר מת, ולכן מקום
ראשו הוא מקומו, או שהולכים אחר מקום ראש, או שהולכים אחר מקום המעשה.
* מו.
:PROPERTIES:
:CUSTOM_ID: מו.
:END:
שאני פרה- מופנה- משמע שרק מופנה יש לו מעלה של כתוב בפירוש (ולא כקל
וחומר). ותחשב. וקל לדחות.
עבד בהם כשהם חולין- נראה שלא צריכים שני קראי לעבודת איסור והיתר כשהוא
קדש, שהרי כל עבודה אז אסור.
כמלא עול- שיעור זה הוא קצת ראנדום. ותו"ת.
פירות- היה אפשר שכבר עשה מלאכה. אז, עשה פירות. אין לומר שרק בנים נחשבים
פירות, שהרי אינו כן גבי הרוג.
הא קמ"ל- כמובן, צריך להבין איך נדע שהשיעור טפח. אולי כשנשמע שיעור זה, לא
נספיק, שלא נבין אותו, ונשאל עד שנמצא שהוא טפח (או ששיעורו טפח או שרחבו
טפח), ואז נמצא שזה גורם שנדע רחבו.
* מו:
:PROPERTIES:
:CUSTOM_ID: מו
:END:
בגופה- יש לדון מה בכלל "בגופו," אם הוא שהקרקע מוציא דבר או אולי גדר אחר.
וצריך לחשוב.
אלא זקנים- קצ"ב איך מותר להם לצאת, שגורמים מיתה לעצמם.
כל המלוה- היה אפשר לבאר על ידי זה למה בזה אומרים זקנים שלא נמנעו מלוויה.
ויש לדון, שגם אומרים יותר מזה. אולי כל זה בכלל לווייה.
ארבע מאות שנה- ראשונים מקשים למה נענשו מצרים, כיון שהיה אברהם מובטח על
פי ה' להיות עמו עבדים. יש אומרים שהוא מפני שלא היה צריך להיות מצרים.
קשה, אז, איך שיעבוד זה יהיה שכר. אולי רואים מכאן ששכר אינו נתינת דבר
טוב, אלא נתינת דבר שאדם רוצה.
על פי זה, יכולים להבין איך ה' נותן שכר בעולם הזה כדי שלא יתן שכר לעולם
הבא. לכאו', קשה להבין שהסיבה שלא רוצה לתת שכר לעולם הבא הוא שהוא יותר
טוב. אז, קשה איך מקיים אותו בעולם הזה. על פי מש"כ, קל לומר שלא תלוי כמה
טוב הוא, אלא כמה רוצה אותו. (עיין לקמן גבי בלק שנראה שדיון גמ' קצת הולך
כמש"כ.)
ארבע מאות- אם נאמר שנמנו מלידת יצחק, צריך ביאור, שלא היו במצרים כל הזמן.
אולי נשתעבדו קצת כל הזמן.
* מז.
:PROPERTIES:
:CUSTOM_ID: מז.
:END:
להוו- משמע שמקשה למה נחשב נס. נקרא שרק דבר נצרך נקרא נס. ואם תאמר ל"ל
פרש שמקשה למה היה יער. וצריך ביאור.
דבעיתי- ואם תאמר יעשה נס אחר, שלא יהיו מתפחדים. אולי היה אשפר, אבל אין
נס זה יותר טוב מנס זה. יותר נראה לומר שאם עשה שאל היו מפחדים, היה צריך
כמה ניסים, שהיה רוצה לפחד בכל שעה, ובכל שעה היה מונע אותו מפחד. מה שאין
אדם מפחד עכשיו אינו סיבה שלא יפחד לאחר זמן.
אבל יער רק צריך נס אחד, שכיון שנברא, דרכו הוא להתקיים. אז, יותר "קל" הוא
לברוא יער מלברוא דובים שאינם יראים.
כמו כן, יש לומר שלא נמצא דובים שלא יראים בלי יער. אבל, נמצא יער. אז, היה
יותר קל לעשות יער. ותחשב.
תאותו מיהא לקללה- עיין לעיל במה שבארנו לענין מה בא לאדם לשכר. ודע שרק
בשני אומר שהיה שכר. לכאו', כיון שמקשה ממנו, נמצא שהראשון ג"כ הוא שכר.
היה אפשר לדחוק שבתירוץ משנה זה, ואומר שכן כוון, וממילא חל קצת, ולא לשכר.
דחוק.
תאותו- קשה, שהיו נקללים בענין אחר, כמו שאומר גמ' בסנהדרין, שנהפכו לקללה.
אולי זה היה רק עונש לעבירות בנ"י, אבל זה היה יותר מעונש. יש לדון,
שבוודאי נראה שאלו היו חייבים מיתה. וצ"ב.
יוסי בן יועזר- עיין במה שבאר רש"י. יש להעיר שבימיו כבר היה מח' (ששם הם
היו החולקים הראשונים).
הגיע עת- לא הבנתי כל כך איך זה מתרץ. אולי אומר שכיון שאלישע דימה אותו
לשכר של תורה, הקרא דבר עליו כאילו היה דבר חשוב. דחוק.
ת"ח- יש לדון אם זה קאי על מה שהיה מחטיא או מזכיר עבירה אחרת. לא נראה כל
כך כצד ראשון, אף שגמרא משמע כן, שקצת קשה לראות במה החטיא את הרבים. אולי
זה היה זלזול תורה בפני רבים.
* מז:
:PROPERTIES:
:CUSTOM_ID: מז
:END:
קמ"ל- יש לדון למה צריכים עוד משנה לבאר כן, שהרי גמ' אומר שלאותו שיטה
שסובר כן, כבר למדנו כן במשנה שלעיל. אולי אין לומדים קולא זה מקולא זה.
ותחשב.
ושונא- ק"ק, שגמ' בברכות אומר שאדם יכול לקבל מתנות כמעשה שונמית. אולי
עדיין לא חי. צריך ביאור מה מלמד; אולי מלמד שמותר לקצר את חיתו כך. דחוק.
* מח:
:PROPERTIES:
:CUSTOM_ID: מח
:END:
דוד ושמואל- עיין ברשי ביומא שרק מזכיר שנים מהם. עיין שם, שמבאר כפי הו"א.
משתמשים- לשון זה קצת משמע שאל רק שמעו בת קול, אלא השתמשו בו. יל"ד מה זה
אומר. אולי סמכו שיבוא.
ואין כל דבר קשה- בדווקא, ולא ר"ל שכל שכן דבר רך, שהרי לכן שמרו אותו
בצמר.
קטנות- גמ' לעיל רק אמר מה הוא קטנות, אבל לא אמר שגורם שום דבר רע.
זימנים- יש להעיר שזה אולי הוא מפני שלא רצה ה' שיהיה אביתר הכהן. ותחשב.
* מט.
:PROPERTIES:
:CUSTOM_ID: מט.
:END:
אלמלא- יש קצת סתירה אם היה מחמת תפלת דווד או מחמת תפלת חבקוק. נבאר: גמ'
אומר שאי לאו תפלת דוד, היו הכל מוכרי רבב. גם אומר שאי לאו תפלת חבקוק היו
שני ת"ח מתכסים בחלוק אחד. קכשה, שמה גרם שבני ישראל לא יהיו ענינם. אולי
שניהם ביחד גרם אותם. אם כן, קשה ל"ל מזכיר שניהם בשניהם. אולי אחד נגרם
כולו מאחד, ואחד משניהם. ואם תאמר ל"ל מזכיר שניהם. ויש לומר שמוסיף. גם יש
לומר שאחד קאי על בנ"י ואחד קאי על ת"ח. גי"ל שאינו מזכיר סיבה, שהרי אין
צריכים סיבה לזה, אולי, אלא הוא רק מניעת הרע. ויש לדון. אם כן, יש לומר
שהיה גזרה שביטל דווד, וגזירה אחר שבטל חבקוק.
אקדושא- עיין ברשי, שאינו כל כך דווקא.
ואלא עלמא- לכאו', ר"ל שכיון שבנ"א חוטאים כ"כ עד שחייבים זה, למה קיים....
גי"ל שמקשה שכיון שיש עולם רק כיון שרצה ה' להיטיב, למה עוד מקיימו. גי"ל
שמקשה שכיון שא"א להם לקיים כל כך תורה, למה מתקיים העולם.
רבה... אבא- שמעתי שהקשה אחר לגר"ק ששם אבא ושם רבה שווים. הקשה כן על שם
של רבה בריה דרבא. אמר לו ר"ק שאולי שמו היה רבה, שהיה נותן לו שם זה אחר
רבה רבו. (כמו כן מצאנו בשבת (ר"נ) ובפסחים (רהבדר"נ)). קשה, שכאן לא נראה
לומר כן, שלא מסתבר שהיה רבה בר רב הונא נקרא רבה, שאחר מי נקרא, שהיה
בדורו של רבה הידוע. ותחשב. אולי אין איסור ששם של בן יהיה של אב. ודע
שמצאנו בירושלמי אבר אבוה דאבא בר זבדא. חוץ מן הקושיא אם היה אבא או זבדא
האב, נמצא שהיה אבא אבא דאבא.
* מט:
:PROPERTIES:
:CUSTOM_ID: מט
:END:
ועל אותה שנה- מסתמא היה לפני מעשה זה, ונתנו אותו כמו שנתנו את התמיד, שאי
לא כן, קשה איך באו לו, שהיה חרם.. אולי נעצר החרם.
עיר של זהב- קשה, שר"ע עשה כן לאשתו. אולי עדיין היה קודם הגזרה.
חכמת יוונית- יש לציין לגמ' חגיגה (ה:) ברמיזה לפני מלך.
אלף ילדים- יש לדון למה הצ' כל כך כמה מהם לדעת לרמוז. אולי רק הצריכו אחד
שהיה כל כך טוב, אבל לא ידעו איזה יהיה. ותו"ת.
בטלה עצה- יש להעיר שאף שלא היה העצה כל כך טובה אח"כ, לא הוצרכו לכל כך
עצה, כמו שאומר גמ' בחגיגה (ה:).
[fn:1] יש לדון בזה, שהיה אפשר לומר שהוא מקנה לה כיון שלא רוצה שתיחד עמו.
[fn:2] ובפרט, אולי קל לומר שמשה נשתנה.
[fn:3] הבעיה אינו רק שחושבת דבר שאינו נכון, ושהוא כנגד עיקרי אמונה, אלא
שאז תורה נבזית. מחשבתה הוא הבזיון. ותחשב.
[fn:4] זה רק קשה אם גורסים כאן רבה, ולא רבא. ותו"ת.
[fn:5] שאלתי את זה לר.ש.ש. ואמר שצ"ל שאף אם אינו הכי גדול, אלא קרוב להכי
גדול, די. לשון גמ' לא משמע כן כלל.
