פירוש המשנה:
שיטה ראשונה:
רבי יוחנן בן ברוקה אומר שהוא מככר בפונדיון מארבע סאין בסלע. במילים אחרים, רבי יוחנן בן ברוקה אומר שהשיעור הוא שתי סעודות, שבין שתיהן הן ככר אחד בככר מיוחד. אותו ככר הוא ככר הנקנה בפונדיון. כדי לדעת גודל הככר, צריך לדעת כמה כסף קונה כמה פת. אז, מפרש שהוא בשעה שקונים ארבע סאה בסלע.\
פשט ראשון:
כדי למצוא כמה פת יש בככר שנקנה לפונדיון, נראה את היחס שבין סלע לפונדיון. אותו יחס יתקיים גם בין ארבע סאין לשיעור של ככר בפונדיון.
הרי, בסלע, יש ארבעים ושמונה פונדיון, כמו שכתבנו למטה.
בסאה אחד, יש ששה קבים. אז, נוכל לקרוא לארבע סאין בשם חדש- נוכל לקרוא אותם עשרים וארבע קבים (שבכל אחד מן הארבע באין יש שש קבים). כדי למצוא היחס של אחד לארבעים ושמונה, נחצה את הקב, שמחצה של עשרים וארבע הוא ארבעים ושמונה. אז, נמצא שגודל של אותו ככר הוא חצי קב.
יוצא לנו שרבי יוחנן בן ברוקה אומר שצריך מזון שהוא חצי קב. שיעור סעודה אחת יהיה רביעית הקב.
דוחה גמ' את זה מברייתא שאומר שדברי רבי שמעון ורבי יוחנן בן ברוקה קרובים. הרי, כמו שנראה לקמן, רבי שמעון אומר ששיעור של סעודה אחת הוא אחד מתשע שבקב. זה רחוק מאד משיעור של רבי יוחנן, שהוא אחד מארבע שבקב.
פשט שני:
** רב חסדא מפרש שרבי יוחנן אומר שהשיעור הוא ככר שניקח בפונדיון כולל דמים מיותרים שצריך לתת לחנווני, אם היה ארבע סאין בקב, בלי דמים המיותרים שצריך לתת לחנווני. אותם דמים המיותרים הם אחד משנים של דמים של הככר. (לא כל כך פשוט למה לשון של רבי יוחנן במשנה יהיה משמע כן. צריך לומר שהיה לתנא של הבריי' מסורה שכך רצה לומר. כשתנא אמר את דבריו במשנה, לא פי', וסמך על משנה אחרת לפרש שהוא קרוב לשיעור של רבי שמעון.) אז, צריכים למצוא היחס שבין סלע לשני שלישי פונדיון. הרי, יש ארבעים ושמונה פונדיונים בסלע. אם נחלק את זה לארבעים ושמונה חלקים של שלש, נמצא שיש מאה ארבעים וארבע חלקים בתוך הסלע. הרי, הככר בא משנים מהם, ואז הוא שנים בתוך מאה ארבעים וארבע. זה שווה לאחד של שבעים ושנים. נמשיך את היחס הזה לארבע סאין. צריכים למצוא מהו אחד משבעים ושנים של ארבע סאין. נוכל לתת שם חדש לארבע סאין, כמו שכתבנו, והוא עשרים וארבע קבים. נוכל לתת שם אחד לזה, שבכל קב, יש שלש חלקים שהם אחד משלש של קב. אז, נוכל לומר שהוא שבעים ושנים חלקים של שלש בקב. הרי, אחד מהם הוא מיוחס לארבע סאין באותו יחס של אחד לשבעים ושנים. נמצא שרבי יוחנן בן ברוקה אומר שאחד משלש בקב הוא שיעור של שתי סעודות. אז, שיעור של סעודה אחת הוא אחד משש בקב. מקשה גמ' שזה עדיין רחוק משיטת רבי שמעון. רבי שמעון אומר שסעודה אחת הוא אחד מתשע בקב, ולא אחד משש שבקב.
פשט שלישי:
** רב חסדא מפרש שלפעמים אדם משלם דמים של הככר לחנווני (זה נמצא כשלא נותן לחנווני העצים לעשות את הפת). שיעור של ככר בפונדיון מדבר באותו ציור, וכולל אף אותם דמים המיותרים. אז, צריכים למצוא היחס שבין סלע לחצי פונדיון. הרי, יש ארבעים ושמונה פונדיונים לסלע. יש כפל זה חצי פונדיונים בסלע; יש תשעים ושש חצי פונדיונים לסלע. נמשיך את היחס הזה לארבע סאין. צריכים למצוא מהו תשעים ושמונה של ארבע סאים. נוכל לתת שם חדש לארבע סאין, כמו שכתבנו, והוא עשרים וארבע קבים. נוכל לתת שם אחר לזה, והוא ארבעים ושמונה חצי קבים. נוכל לתת שם אחר לזה, והוא תשעים ושש רובע קבעים. נמצא שרובע קב מיוחס לארבע סאין באותו יחס. נמצא שרבי יוחנן בן הרוקה אומר שאחד מארבע בקב הוא שיעור של שתי סעודות. אז, שיעור של סעודה אחת הוא אחד משמונה שבקב. אכן, זה קרוב לשיעור של רבי יהודה.
שיטה שנית:
רבי שמעון אומר שהוא שתי ידות לככר משלש לקב. במילים אחרים, רבי שמעון אומר שהשיעור הוא שתי סעודות, שבין שתיהן הם שני חלקים משלש של ככר מיוחד. אותו ככר הוא ככר שיש שלש ממנו לקב. אז, נמצא שאותו הככר הוא שליש הקב. כיון שלא צריך כל אותו הכיכר, אלא רק צריך שני חלקים משלושה ממנו, נמצא שצריך שני חלקים משלש משליש. ניתן לכל ככר שלש חלקים, ונאמר שבין שלש הככרות, יש תשע חלקים. צריכים שנים מהם, ואז יוצא שצריך שני חלקים מתשע מן הקב.
יוצא לנו שרבי שמעון אומר שצריך מזון שהוא שני חלקים מתשע של קב. שיעור סעודה אחת יהיה אחד מתשע של קב.
מנין ביצים שבסאה:
פירוש ראשון:
מזכיר גמ' ששיער רבי שבתוך סאה יש מאתים ושבע עשרה ביצים. מקשה גמ' שאינו כן, שיש רק מאה ארבעים וארבע.
פירוש שני:
דוחה גמ' שיש שני מיני סאין. יש סאה מדברית, שהוא מה שפירשנו, ויש סאה ירושלמית, שהוסיפו עליו חומש, ולשש של מדה מדברית, קראו לו חמש. אז, אומר שבסאה ירושלמית, יש מאתים ושבע עשרה ביצים מדבריות.
הרי, צריכים למצוא חומש של מאה ארבעים וארבע, ונוסיף את זה על אותו מנין למצוא כמה ביצים יש בסאה ירושלמית. אין חומש של מאה ארבעים וארבע, אבל נמצא חומש לש מאה ארבעים וחמש, שהוא קרוב. החומש יהיה עשרים ותשע. אם נוסף עשרים ותשע על מאה ארבעים וארבע, נמצא שיש מאה שבעים ושלש. מקשה שגמ' שזה עדיין פחות משיעור שאומר רבי.
פירוש שלישי:
מדה ציפורית הוא עוד מדה, והוא למדה ירושלמית מה שמדה ירושלמית הוא למדה מדברית. אז, צריכים למצוא חומש של מאה שבעים ושלש ולהוסיף עליו. אין  חומש לאותו מנין, אבל יש חומש למאה שבעים וחמש, שהוא שלושים וחמש. אז, נוסיף שלושים וחמש על מאה שבעים ושלש, ונמצא מאתים ושמונה. גמ' אומר שהוא מאתים ושבע, ולא מוסיף את הביצה האחרון שמנינו. רשי מפרש שזה מפני שלא באמת היה סאה ירושלמית מאה שבעים ושלש, שהחומש לא היה באמת עשרים ותשע, אלא קצת פחות. תצטרף את זה למה שבאמת מאה שבעים ושלש, ולא מאה שבעים וחמש, הוא, ונמצא שיותר טוב שלא להוסיף אותו ביצה. (אם תעשה החשבון האמיתי, נאמר שהוא 144 + 28.8, שהוא 172.8. אחרי זה, יהיה 172.8 + 34.56, שהוא 207.36, שהוא יותר קרוב ל207 מל208. אז, נמצא שחשבון הגמ' מדוקדק.)
פירוש רביעי:
גמ' מפרש שלא אמר כמה ביצים יש בסאה, אלא כמה ביצים יש בעיסה שאם ניטל ממנו חלה יהיה סאה. הרי, חלה היא אחד מעשרים וארבע. אין אחד מעשרים וארבע למאתים ושבעים, אבל יש למאתים ושש עשרת. הוא תשע. אבל, גמ' לא אומר תשע, אלא אומר שמונה. איני יודע למה, ששמונה הוא האחד לעשרים וארבע של מאה שבעים ושנים, שהוא יותר רחוק ממאתיים ושבע. (באמת, במנין האמיתי, בדיוק מאתים ושש עשרה הוא.) רשי מעורר את זה ולא מפרש. על כל פנים, יוצא שהוא מאתים וחמש עשרה ביצים, ולא מאתים ושבע עשרה.
פירוש חמישי:
לשון ראשון של רש"י:
אז, גמ' מפרש שהביצים רגילים הם קצת קטנות, עד שבשנים מהם, חסר אחד מארבעים של ביצה רגילה. אז, בשמונים ביצה, יש עוד ביצה. כשנוסיף הביצה שנמצא בשמונים ראשון, וביצה שיוצא משמונים השני, נמצא שיש עוד שני ביצים, ואז יש מאתים ושבע עשרה ביצים. לא מונים את מה שיוצא מן החמישים וחמש שנשאר, כיון שהוא פחות מכביצה, אף שהוא יותר קרוב לביצה מלכלום, שהוא 0.6875. יש להעיר שאם נצטרף את הייתור מחמישים וחמש ביצים, אל מה שבאמת הוא מאתים ושש עשרה, הוא יותר ממאתים ושמונה עשרה. כן מקשה רשי, ולכן דוחה פשט זה.
אז, נמצא שהיה מדבר בכמה ביצים רגילים (שהם קטנים) יש במה שעושה, אחרי נטילת חלה, סאה ציפורית.
לשון שני של רשי:
גמ' מפרש שהביצים רגילים הם קצת קטנות, עד שבשנים מהם, חסר אחד מעשר של ביצה רגילה. אז, במאתים ביצה, יש עוד עשרים ביצה. כשנוסיף אלו הביצים למאתים ושבע, נמצא שיש מאתים ושבע עשרה. (אף שלא מנינו את החסרון של שבע ביצים, שהוא שבע חלקים מעשר, שהוא יותר קרוב לביצה מלכלום, ללא מונים אותו, כיון שאינה ביצה שלימה.)
אז, נמצא שהיה מדבר בכמה ביצים רגילים (שהם קטנים) יש במה שעושה, אחרי נטילת חלה, סאה ציפורית.
ביאור בריי' שמדבר בשיעורים:
ברייתא מבאר שסאה ירושלמית יתירה על מדברית אחד משש שלו, וסאה ציפורת יתירה על ירושלמית אחד משש שלו. אומר שאז סאה ציפורית יותר על ממדברית אחד משלש.
פי' ראשון:
מניח גמ' שהוא אחד משלש של מדברית. מקשה ששליש של מדברית יהיה ארבעים ושמונה ביצים לסאה. אם נוסיף את זה על של מדברית, נמצא מאה תשעים ושנים ביצים לסאה. הרי, של ציפורית יותר גדול מזה; האו מאתים ושבע ביצים לסאה.
פי' שני:
אז, פי' שהוא שליש של ירושלמים (מוזר שיהיה כן, כיון שאין זה בתוך הדמיון). הרי, בסאה ירושלמית יש מאה שבעים ושלש ביצים לסאה. זה קרוב לחמישים ושמונה. אם נוסיף את זה על מאת ארבעים וארבע של סאה מדברית, נמצא שהוא קרוב למאתים ושנים. הרי, סאה ציפורית יש בו מאתים ושבע ביצים.
פי' שלישי:
אז, פי' שהוא שליש של סאה מדברית. שליש של מאתים ושבע הוא ששים ותשע. אם נוסיף את זה על מאה ארבעים וארבע, נמצא שהוא מאתים ושלש עשרה ביצים לסאה. זה יותר מסאה ציפורי, שבסאה ציפורי רק יש מאתים ושבע ביצים לסאה. (פשוט מן הסברה שיהיה יותר גדול, שמה שמוסיף סאה ציפורית הוא אחד משש שלו ואחד משש של רק חמש משש שלו. אם היה שליש, היה צריך להיות אחד משש ואחד משש.)
פי' רביעי:
אז, מפרש גמ' שמה שסאה ציפורית מיותר על סאה מדברית קרוב לשליש שלו, שמאתים ושלש עשרה קרוב למאתים ושבע. דוחה גמ' שלא אומר קרוב, אלא אורמ שהם שווים.
פי' חמישי:
גמ' מפרש ששליש של ציפורי של רבי (עם צירוף מה שחסר מכל ביצה, כיון שביצה רגילה קטנה) הוא יותר על מחצה של מדברית שליש ביצה. הרי, סאה ציפורי הם מאתים ושבע ערה ביצים של רבי. שליש מזה הוא שבעים ושנים ושליש. מחצה של סאה מדברית הוא שבעים ושנים. (כנראה, בזה לא מדברים בביצים רגילים שהם קטנים, אלא בביצים שונים שהם גדולים.) נמצא ששליש של סאה ציפורית הוא שליש ביצה יותר ממחצה של סאה מדברית.
