1. נתנו את העירוב בחיצונה:
  1. שכח אחד מן הפנימיות- שתיהן אסורות.
    1. לא יכול לבטל לבני פנימי, שאינם גרים עמו, שעירובם בחוץ.
    2. לא יכול לבטל לבני החיצונה, שאין ביטול רשות מחצר לחצר.
  2. שכח אחד מן החיצוניות- שתיהן אסורות.
    1. לא יכול לבטל לבני החיצון, שעדיין בני הפנימי אוסרים עליו. הם לא יכולים לשמש במקום שלהם, שלא עירבו שם, והם רגל האסור במקומם. אז, הם אוסרים במקום אחר.
    2. לא יכול לבטל לבני הפנימי, שאין ביטול מרשות לרשות.[fn:1]
2. נתנו את העירוב בפנימית:
  1. שכח אחד מן הפנימית- שתיהן אסורות.
    1. לא יכול לבטל לבני פנימי, שאף אם ביטל, לא ביטל לבני חיצון, והם אוסרים עליו. (וא"ת הם לא שייכים לכאן. ויש לומר שכיון שעירבו עמהם, שייכים.)
    2. שכח אחד מן החיצונה- הפנימית מותרת והחיצונה אסורה. הפנימית מותרת כיון שאין בני החיצון שלא יכולים לטלטל אוסרים על בני הפנימי (שיש שם מחיצה). כיון שיש לבני הפנימי עירוב, מותרים לטלטל. (קשה למה לא אומרים כמש"א לעיל, שכיון שבני החיצון נתערבו עמהם, יאסרו. רש"י באר שהוא מפני שרק עשו עירוב כדי לעשות הטוב להם. אבל, קשה שנאמר כן גם כששכח מבני הפנימי. צריך לומר שרק אומרים כן אם מפני טעות שלהם (של בני החיצון) בא הרע. ותחשב.)
כתבתי כל זה רק על פי הסוגיה בסו. צריך לחזור על זה כשנגיע לגמ’ לקמן (עה) שיבאר את זה יותר.
* Footnotes
[fn:1] לכאו’, הענין כאן הוא שבוודאי לא יכול לבטל את רשות שלו לבני הפנימי, שהם בני חצר אחרת. רק יכול לבטל לבני החיצון. אבל, אז נמצא שעירוב של בני הפנימי הוא במקום שאינו מותר להם (שבוודאי אין זה עירוב שלהם, שאין ביטול מועיל להם). אז, אינו עירוב כשר להם, ונמצא שאסור לבני פנימי לטלטל במקומם. אז, הם רגל האסור, ואז הם אוסרים.
