הברייתא:
יש שלשה חלקים של עיר. יש עיר עצמו. סביב לו אלפים אמה, יש מגרש. סביב לעיר אלפים אמה, יש תחום העיר. בריי' אומר שהמגרש הוא רובע של התחומים. הפשטים יפרשו איך יוצא שהמגרש הוא רובע התחומים.
פשט ראשון- פשט של בר אדא:
1. מדובר כאן בעיר שהוא אלפיים אמה על אלפיים אמה. כדי להקל על החשבון, נעשה כל אלף לאחד. אז, חשבון העיר כן הוא:
עכשיו, נחשב כמה יש בכל אחד מאלו:
1. בעיר יש ארבע.
2. במגרש יש שנים עשר.
  1. בצדדים יש שמונה.
  2. בקרנות יש ארבע.
3. בתחומים יש שלשים ושנים.
  1. בצדדים יש ששה עשר.
  2. בקרנות יש ששה עשר.
צד ראשון של הגמרא בפשט ראשון:
צד ראשון של הגמרא הוא שמה שהוא (1/4) הוא (ג/ב). נראה אם זה נכון. הרי, (ג/ב) הוא (12/32). זה שווה ל(6/16), שהוא שווה ל(3/8). כיון שרביע הוא (2/8), נמצא שזה יותר גדול מרביע.
צד שני של הגמרא בפשט ראשון:
צד שני של הגמרא הוא שמה שהוא (1/4) הוא ((א+ג)/ב). נראה אם זה נכון. הרי ((א+ג)/ב) הוא (12/32+4). זה שווה ל(12/36), שהוא שווה ל(1/3). נמצא שזה יותר גדול מרביע.
צד שלישי של הגמרא בפשט ראשון:
צד שלישי של הגמרא מחדש שאין העיר מרובע, אלא הוא עגול. אז, נצייר את העיר החדש:
1. עכשיו, נחשב כמה יש בכל אחד מאלו:
2. גודל העיר יבוא מן הפורמיול"א לגודל עיגול. הרי, עיגול הוא π (ראדיו"ס לכח השנים). כאן, זה יהיה π (1^2).  זה שווה לπ. נניח ש π= 3, ואז ייצא לנו שהעיר הוא שלש.
3. גודל המגרש יבוא מגודל המגרש והעיר מינו"ס ג ודל העיר. הרי, המגרש הוא π (2^2). זה שווה ל π (4). אם נניח ש π= 3, נמצא שהוא 12. הרי, העיר הוא 3. אז, המגרש האו 12- 3= 9.
4. כדי לראות גודל התחומים (לא יהיה גa וגb שייך לחשבון זה), צריכים לראות גודל הכל, ונוציא מזה גודל העיר. הרי, גודל הכל הוא שלושים ושש. נוציא מזה 3. אז, נמצא שהוא שלושים ושלש.
נחשב את זה לפי שני הצדדים שלעיל:
כצד ראשון:
מה שהוא (1/4) הוא (ג/ב). אז, הוא (9/33). הרי, זה שווה ל(3/11). כיון ש(1/4) הוא (3/12), נמצא שזה גדול מן (1/4). אז, זה לא נכון.
כצד שני:
מה שהוא (1/4) הוא (ג+א/ב). אז, הוא (9/36). הרי, זה שווה ל(1/4). אז, זה נכון.
פשט שני- פשט של אביי:
1. מדובר כאן בעיר שהוא אלף על אלף. אז, ציור העיר הוא:
צריכים לחשב כמה יש בכל אחד:
1. בעיר, יש אחד.
2. במגרש, יש שמונה.
3. בתחומים, יש עשרים וארבע.
צד ראשון בפשט שני:
מה שהוא (1/4) הוא (ג/ב). הרי, זה (8/24). זה שווה ל(1/3). אז, זה יותר גדול מן (1/4).
צד שני בפשט שני:
1. מדובר כאן בעיר עגול. אז, הציור של העיר החדש
הוא:
2. בעיר, צריכים לחשב כמה יש בעיגול. הרי, הפורמיול"א לכך הוא π (r)^2. זה יהיה כאן π (1/2)^2. אז, זה יהיה π (1/4). אם נניח ש π=3, יוצא שזה (3/4).
3. כדי לראות גודל המגרש, נראה גודל המגרש והעיר, ונוציא מזה את גודל העיר. הרי, נמצא שגודל המגרש והעיר ביחד הוא π (3/2)^2. זה יהיה π (9/4). אם נניח ש π=3, יוצא שזה (27/4). אז, יודעים שצריכים (27/4) – (3/4). נמצא שהוא (24/4). (זה שווה לשש, אבל נשאיר אותו כך.)
4. כדי לראות גודל התחום, נראה גודל כולו, ונוציא מזה גודל העיר. הרי, גודל של כולו הוא עשרים וחמש. נעשה את זה ל(100/4). נוציא מזה (3/4). אז, הוא (97/4).
אנו מחשבים כמה הוא (ג/ב). הרי, הוא (24/97). אז, הוא קצת פחות מרביע, שהרי רביע הוא (24/96). אבל, עדיין גמ' אומר את זה.
אפשר לפרש שגמ' לא דק. תוס' מפרש שגמ' לא מונה תחומים שהוא בתוך ריבוע העיר. קשה להבין את זה; קשה למה רק ימנה את זה.
גר"א פי' שהעיר הוא (5/4), ולא אחד. הציור הוא כמעט שווה, ולא נצטרך לציין אותו עוד. אבל, נחשב את הכל.
1. בעיר, צריכים לחשב כמה יש בעיגול. הרי הוא π ((5/8)^2). זה שווה ל π (25/64). אם נניח ש π= 3, נמצא שהוא (75/64).
2. כדי לראות גודל מגרש, נראה גודל המגרש והעיר, ונוציא מזה את גודל העיר הרי, נמצא שגודל המגרש והעיר ביחד הוא π (13/8)^2. אז, הוא π (169/64). אם נניח ש π= 3, נמצא שהוא (507/64). אם נוציא מזה (75/64), יישאר (432/64).
3. כדי לראות גודל התחומים, נראה את גודל כולו, ונוציא מזה את גודל העיר. גודל כולו הוא חמש ורבע *חמש ורבע. זה שווה ל(21/4)^2. אז, זה (441/16). זה שווה ל(1764/64). נוציא מזה גודל של העיר, ויהיה (1689/64).
הרי, (ג/ב) הוא (1689/64). זה קטן מרובע, שרובע הוא (1728/64). אם נצרף את העיר, יהיה יותר גדול מרביע, שיהיה (432/1764), שהוא קצת פחות מרביע (שרביעי הוא (441/1764)).[fn:1]
אז, צריך לומר שגם הגר"א לא דק.
פשט שלישי- פשט של רבינא:
רבינא אומר שהציור שווה לציור של פשט הראשון בצד הראשון. אבל, אומר שרביע הוא שמגרש של צדדים הוא רביע של תחומים. אז, הוא שווה ל(ג/בa), שהוא (8/32). הרי, זה רביע.
פשט רביעי- פשט של רב אשי:
רב אשי אומר שהציור שווה לציור של פשט הראשון בצד הראשון. אבל, אומר שרביע הוא של מגרש של קרנים בתוך תחום של קרנים. אז, הוא (גb/בb). הרי, זה (4/16), וזה שווה ל(1/4).
מסופק רשי אם רב אשי סובר שיש מגרש סביב כל העיר, ורק מונים כאן את הקרנות, או שרק יש מגרש בקרנות.
לעשות לזה איקווייזי"ן:
אקוויזי"ן אם העיר מרובע:
.
נוכל לעשות את זה לזה:
.
יכולים לעשות את זה לזה:
.
יכולים לעשות את זה לזה:
.
יכולים לעשות את זה לזה:
.
יכולים לעשות את זה לזה:
.
יכולים לעשות את זה לזה:
.
נמצא מזה שצריך לומר:
.
אז, נמצא ש:
.
יש ביאור פשוט לזה מן הסברה. הרי, יש שני חלקים של מגרש ותחום- יש צדדים וקרנות. כמה שהוא גדול או קטן, תמיד בצדדים הוא (1/2), ותמיד בצדדים הוא (1/4). אז, נמצא שאין אפשרות שיהיה, בין הכל, (1/4) אם לא שאין צדדים, והוא שאין עיר. אז, נמצא שגודל העיר צריך להיות אפס.
אקוויזי"ן אם העיר עגול:
.
נניח שπ  שווה ל3, ויכולים לעשות מזה:
.
מזה, יכולים לעשות את זה:
.
מזה, יכולים לעשות את זה:
.
לא כל כך קל להבחין מהו התשובה. יש להעיר שאם נותנים אותו לתוך הקוואדראטי"ק פורמיול"א, בא שני תשובות, אחד שהוא חמשה עשר ואחד שהוא אחד. (זה בא על ידי שני שינויים- מה שלקחנו שלש לπ, ומה ששינו את הסקווא"ר רו"ט שבתוך הקוואדראדי"ק פורמיול"א.) מעניין, אז, שמה שאומר גמ' הוא התשובה הכי קלה שיבוא מן המאטימאטיק"א. ותו"ת.
התשובה האמיתי היא 14.92 ו1.07. יש להעיר שזה יותר קרוב למה שאומר גמ' משהוא קרוב למה שאומר הגר"א. (אבל, זה עדיין עם שינוי של 3 לπ). ותחשב.
* Footnotes
[fn:1] גם אולי לא מסתבר לומר שמצרפים את העיר, שאם כן, קצת קשה למה לא נאמר כצד ראשון, ויהיה דווקא. אולי לא מצוי שעיר יהיה אלפים על אלפים..
