הגמ' מדבר בהגדרת "יד." יד הוא חלק מאוכל שאינו נאכל ונשאר שם כדי להשתמש בו עם האוכל. הדין הוא שלענין טומאה נחשב חלק מן האוכל.
יש מימרא מרב הונא בענין דבר שלא מקבל דין יד. חולקים מהו המימרא:
1. רבי אבא בשם רב הונא אומר שהבוצר לגת אין לו ידות. כיון שמכוון לסחוט את הפירות, אין תשמיש לידות.
2. רב מנשיא בר גדא בשם רב הונא אומר שהקוצר לסכך אין לו ידות, שאין לו תשמיש בידות.[fn:1]
גמ' מפרש שלא מודים ר"א ור"מ להדדי. לר"מ, בין בקוצר בין בבוצר אין ידות. אבל, לר"א, בקוצר יש ידות, שיש תשמיש בידות, כיון שמחבר את הפירות.[fn:2]
גמרא מביא מחלקת תנאים שהוא אולי נוגע למחלקת זה בין ר"א ור"מ. מדובר במסכל לסוכת מצווה בתאנים וכדומה שיש עמהם פסולת. אומר שיש להם דין אוכל כל זמן שהפסולת מיעוט. אבל, חולקים תנא וקמא ואחרים אם צריך להיות מיעוט כנגד רק הפירות או כנגד הפירות והידות. נמצא שחולקים אם יש לידות, באותו הציור, דין ידות.
דוחה גמ' שר"מ יכול לדחות שאין חולקים בקןצר לסכך, ובוודאי אין לו ידות. חולקים בקוצר לאוכל ונמלך לסחך, אם נשאר לידות דין יד.
מקשה גמ' למה רבנן אומרים שלא נשאר דין ידות. הרי,  משנה אומר שכלים, אף שיורדים לטומאה אף בידי מחשבה, לא עולים מן הטומאה אלא על ידי מעשה. דוחה שזה רק נכון בכלים, שהם חשובים, ולא בידות.
מקשה ממשנה שאומר שידות האוכלים בססן בגורן טהורות, ורבי יוסי מטמא. חולקים מהו פי' "בססן," אם הוא שהתיר את האוגד שלהם או שטחן אותם. הרי, כדי לטהר אותו, צריך יותר ממחשבה. (גמ' מפרש שלא קשה אם נפרש כצד ראשון, שלפי זה, יש לומר שזה רק סימן לשינוי במחשבה שלו. אולי גם לענין סוכה עושה קצת סימן או אולי הסימן לאו דווקא.)
מפרש גמ' שהמשנה לא מדבר בסכך שקצר לשם אכילה ונמלך, אלא שבססם ונמלך. מקשה אז מה הטעם של אחרים, שבוודאי יהיו טהורים, כיון שנשתנה במעשה. משיב שסוברים כרבי יוסי, שאומר שנשאר להם דין ידות. מקשה שלא יהיה טעם של רבי יוסי נמצא כאן. הרי, רבי יוסי רק אומר שנחשבים ידות כיון שיש להם קצת תשמיש, שיכולים להפוך את הפרי על ידי עתר יותר כיון שיש לו יד. אבל, לא עושה כלום לסכך. דוחה גמ' שעדיין יותר קל לאחוז את הכל על ידי הידות, ואז יש לו קצת תשמיש. (עדיין, כמו שראינו, אין תשמיש זה מהני לעשות אותו יד בפני עצמו, אלא רק להשאיר לו דין יד.)
אז, בין הכל, מצאנו ככה:
1. ידות שאין להם תשמיש אין נחשבים ידות. מצאנו שתי סיבות שאולי הם כן:
  1. אם בוצר אדם לגת, אין לידות תשמיש.
  2. אם קוצר אדם לסוכה, חולקים ר"א ור"מ אם יש לידות תשמיש.
2. מצאנו מחלקת תנאים בידות לסכך. יש שני מהלכים לפרש את זה:
  1. חולקים בקוצר לסוכה, אם יש ידים תשמיש או לא.
  2. חולקים במחלקת רבי יוסי ורבנן שנביא לקמן.
3. חולקים רבי יוסי ורבנן בידות ששינה את דעתו מהם ובסס אותם. חולקים אמוראים במה חולקים, אם רק התיר את האיגוד שלהם (רק שינה מחשבתו) או ממש דש אותם (ולא קל להשתמש בהם כידים).
* Footnotes
[fn:1] לא קוצר לסכך של מצווה, שכיון שמדברים בידות, מובן שמדברים בדבר שמקבל טומאה. אז, אינו כשר לסכך של מצווה. צריך לומר שמדברים בסיכוך שאינו למצווה.
[fn:2] יש לדון אם אז יותר קל לשים אותם במקום סכך או שאז מסככים יותר טוב.
