הברייתא:
"שני סדינים מצטרפים שני נסרים אין מצטרפים [דברי רבי יהודה]. רבי מאיר אומר אף נסרים כסדינים.[fn:1]"
לשון ראשון של דיון:
לא קשה לשמואל:
שמואל סובר שלפי רבי מאיר נסרים שהם שלשה טפחים פסולים ולפי רבי יהודה נסרים שהם ארבעה טפחים פסולים.
במשנה, מדובר בנסרים שהם בין שלש לארבע טפחים. רבי יהודה אומר שלא מצטרפים, והוא מפני שרק סכך פסול מצטרף לפסול, וסובר שאין נסרים כזה פסולים. רבי מאיר אומר שמצטרפים כיון שסובר שנסרים כזה פסולים. אז, יכול להצטרף לנסרים אחרים לפסול.
קשיא לרב:
רב סובר שלפי רבי מאיר נסרים שהם ארבעה טפחים פסולים ולפי רבי יהודה נסרים תמיד כשרים.
לרב, קשה איך לבאר את המחלקת.
אם המשנה מדברת בנסר שהוא ארבעה טפחים, לשון של רבי מאיר קשה, שהרי אומר שמצטרף לפסול. הרי, שיעור של סכך פסול (------) הוא ארבעה טפחים. אז, נסר כזה לא צריך צירוף.
אם המשנה מדברת בנסר שהוא פחותה מארבע טפחים, קשה למה רבי מאיר אומר שמצטרף. הרי, אינו סכך פסול, ואז אי שאפשר יצטרף לפסול.
תשובה ראשונה לרב:
גמ' משיב שמדובר בנסר שיש בו ארבע טפחים. לפעמים, כשר אם יש סכך פסול בארבע טפחים, והוא אם אותו סכך סמוך לדופן. אז, עד שהוא ארבע אמות, כשרה, כיון שרואים אותו כדופן עקומה. אז, רבי מאיר אומר שנסר כזה סכך פסול הוא, ומצטרפים נסרים כאלו להיות יותר מד"א, עד שלא נאמר שהוא כדופן עקומה. אבל, רבי יהודה חולק ואומר שהוא סכך כשר, ולכן לא צריך דופן עקומה להכשיר את הסוכה, ואין בו צירוף לפסול.
תשובה שנית לרב:
גמ' משיב[fn:2] על פי צד שמפרש שרב סובר שסכך פסול פוסל בארבע אמות, ולא בארבע טפחים. אז, מדובר בנסר שהוא ארבע טפחים, ולכן הוא פסול, ורבי מאיר אומר שמצטרף לפסול בארבע אמות. רבי יהודה אומר שאינו פסול, ולכן לא מצטרף.
לשון שני של דיון:
לא קשה לשמואל:
שמואל סובר שלפי רבי מאיר נסרים שהם שלשה טפחים פסולים ולפי רבי יהודה נסרים שהם ארבעה טפחים פסולים.
הרי, רבי יהודה אומר שאין נסרים מצטרפים. לשון זה מורה שיש סכך פסול, אלא שאינו מצטרף. יכולים לומר שמדברים בנסר שהוא ארבעה טפחים. שמואל אומר שבין לרבי יהודה בין לרבי מאיר זה פסול. אם הוא בצד, ואז נוכל לומר בו שהוא כדופן עקומה, רק פסול אם הוא ארבע אמות. חולקים רבי מאיר ורבי יהודה אם מצטרף נסרים להיות ארבע אמות.
יוצא מזה שלפי צד זה (ויש לדון אם הוא קיים לאחר התי' לשיטת רב) יש מחלקות חדשה בין רבי מאיר לרבי יהודה, והוא אם נסרים שהם סכך פסול מצטרף לפסול את הסוכה מלומר בו דופן עקומה. אז, יש שני מח' שונות בין רבי מאיר לרבי יהודה.
קשיא לרב:
רב סובר שלפי רבי מאיר נסרים שהם ארבעה טפחים פסולים ולפי רבי יהודה נסרים תמיד כשרים.
לרב, קשה איך לבאר את המחלקת.
כיון שאין נסר שהוא סכך פסול לפי רבי יהודה, קשה איך ידבר בצירוף שלו. הרי, צירוף הוא רק נוגע בסכך פסול.
תשובה לרב:
גמ' משיב שכשאומר "אינו מצטרף" רצה לומר שאינו בתורת צירוף, כיון שאינו כשר. אמר לשון של צירוף אגב לשון של רבי מאיר (שאומר שלא רק פסול, אלא גם מצטרף לפסול).
* Footnotes
[fn:1] אגב, לשון "אף" קצת מוזר. הרי, אילו היה אומר שנסרים כסדינים, היה מובן. גם אם היה אומר שאף נסרים מצטרפים זה לזה, היה מובן. אבל, אין דבר אחר שהוא כסדינים (שלא אמרנו שסדינים כסדינים, שזה פשוט, ואין זה אומר כלום) שנאמר בו "אף." צריך לומר שפי' דבריו הוא "אף נסרים, שנסרים כסדינים," אבל לא כל כך פשוט לקרוא את זה למה שאמר. ותחשב.
[fn:2] משיב כן כמה דפים אחרי עיקר הדיון.
