* ביאור מה ניתן למשה בסיני:
** פסוק:
ואתנה לך את לוחות האבן והתורה והמצווה אשר כתבתי להורותם.
** דרשות:
*** לוחות:
מזה דורשים עשרת הדברות. דרשה זו מובנת, שעל הלוחות היו כתובים עשרת הדברות.
*** תורה:
מזה דורשים מקרא. מהמשך נראה ש"מקרא" היא מילה מוזרת, שלא כולל נביאים וכתובים. אלא, רק כולל את התורה. לכאו', גם זה מסתבר מן הפסוק, שתורה היא רק תורה. יש לדון אם זה רק תורה או שגם כולל דרכים שהתורה דרשת בהם. ותחשב.
*** מצווה:
גמרא אומר שזה משנה. לכאו', הביאור בדרשה זו היא שמשנה אומר לנו מה לעשות, ומצווה רצה לומר ציווים שאנו צריכים לעשות. (וא"ת תורה אומרת לנו מה לעשות. ויש לומר שלא קל להבין תורה. וא"ת לא יכולים לפסוק על פי משנה, שצריך גם גמרא. ויש לומר שגמרא בוודאי אינו יכול להיות מצווה, שסומכת כל כך על משנה. יש לומר שאחרי ידיעת הגמרא מבינים את המשנה בטוב, ונמצא שמורה לנו מה לעשות. וא"ת אם כן גמרא כלולה במשנה. ויש לומר שגמרא רצה לומר הדרכים ללמוד את המשנה.)
*** אשר כתבתי:
זה נביאים וכתובים. יש לדון מהיכי תיתי לרבות שני דברים. גם צריך ביאור איך זה מתאים לנביאים וכתובים, שלא כתב ה' אותם כבר, אלא יכתב אותם. צריך לומר שאין דבר אחר לרבות, ואז מ"כתב" מרבים דבר שנכתב, וזה רק נביאים וכתובים. אין סיבה לרבות אחד יותר מחבירו (יש לדון, שבדרך כלל יש יותר קדושה לנביאים, שנאמרו ממש בנבואה), ואז מרבים את שניהם.
*** להורותם:
זה גמרא. רש"י מפרש שהוא מפני שיכולים להורות רק ממנו. זה נגד מה שצדדנו לעיל, וצריך לחלק בין עשיית ציווים להוראה. גם היה אפשר לומר לולי רש"י שיש חילוק בין הוראה ו"להורות," שזה דבר שצריך לעשות כדי להורות.
** הלימוד:
גמרא אומר שזה מלמד לנו שכולם ניתנו למשה בסיני. על זה יש כמה קושיות:
איך משה ידע דינים דרבנן.
אפשר לומר שידע שיגזרו כן רבנן או ידע שיש ענין בזה. יש להעיר שכמו כן אברהם כנראה ידע.
איך משה ידע את התורה שיקרה אחרי מיתתו.
אפשר לומר שניתן לו, אלא ששכח.
אפשר לומר שידע התורה שבו, וזה לא תורה.
בלי חטא, לא היו נביאים וכתובים נכתבים, ואז איך ניתנים למשה.
אפשר שהגמרות חולקים בזה.
אפשר שנאמר למשה, ובלי חטא, לא היה כתוב.
איפה כלולים הלכות למשה מסיני.
אפשר שהם כלולים במשנה, שנאמרו במשניות. דע שיש מהם שאינם במשניות, אבל הם בבריי', וצריך לומר שזה בכלל בריי'.
גם יש לומר תירוץ אחר לכל קושיות אלו, והוא ש"ניתנים למשה מסיני," לא רצה לומר שה' לימד אותם למשה מסיני אלא רצה לומר דבר אחר:
ניתן לו הכוח והיכולת ללמוד אותם.
ניתן לו הזכות ללמוד אותם.
ניתן לו הזכות להכריע ולפסוק בהם:
האמת הוא כמו שפסק.
מותר לסמוך עליו בפסק.
ניתן לו מצווה ללמוד את כולם. כן מאד משמע מדברי רש"י.
עיין בגמרא במגילה (יט:) שאומר שה' הראה למשה דקדוקי תורה ודקדוקי סופרים ומה שהסופקים עתידים לחדש, דהיינו (משמע שלא כולל דבר אחר?) מקרא מגילה. אבל, דורש את זה מ"ועליהם ככל הדברים אשר דבר ה' עמכם בהר." יש לדון מהו דקדוקי סופרים. ותחשב.
* ביאור מעלת קריאת שמע שעל המטה:
** מהו ענין חרב של שתי פיות:
רש"י פי' שהוא להרוג מזיקים. אם כן, קשה ששני הדברים שאומרים הם שווים (או שכיון שבדילים, לא צריך להרוג אותם).
לכאו', ענין של חרב של שני פיות הוא שהוא חרב שהוא מאד טוב, ויכול להכות בו בטוב.
יש לדון אם יכול לשמור את עצמו (אולי שיתפלל בו או אולי ממילא) או שרואים ופוחדים.
יש לדון לכמה זמן מושך אותו חרב, אם הוא רק ללילה (ואם הוא לכל הלילה) ואם הוא גם ביום שלאחירו. ותחשב
שי לדון אם גם הורגים את המזיקים, ולא יכולים להזיק אותו ואחרים לעולם או לא.
** מקור:
המקור הוא שנאמר "יעלזו חסידים בכבוד ירננו אל משכבותם." ביאור "ירננו על משכבותם" הוא אמירת קריאת שמע שעל המטה. מעניין שקריאת שמע שעל מטה נחשב רינה. גם יש להעיר שלכאו' קאי על חסידים. אם הם חסידים, מסתמא הם גם כן תלמידי חכמים, ותלמידים חכמים לא אומרים קריאת שמע שעל המטה. (עיין לקמן.) לזה נסמך "רוממות אל בגרונם וחרב פיפיות בידם." אז, אומר שכיון שרוממות אל בגרונם, שאמרו קריאת שמע (לכאו', הוא רוממות קל ב"ה' אלקינו ה' אחד"), חרב פיפיות בידם.
** מהו מזיקים בדילים ממנו:
משמע שמזיקים לא באים אליו להזיק. אבל, יגביהו לא משמע כן.
** מקור - תורה או קריאת שמע?
גמרא דורש מ"בני רשף יגביהו עוף." עוף רצה לומר תורה שכ', "התעיף עיניך בו ואיננו." רשף רצה לומר מזיקים, שכ', "מזי רעב ולחמי רשף וקטב מרירי," וידוע שקטב מרירי הוא שם מזיק.
נראה שביאור הפסוק הוא שבני רשף יגביה אותו עוף.
מעניין שדורשים שעוף הוא תורה מ"התעיף עיניך ואיננו," ש"עוף" הוא מתי שאין תורה.
יש כמה קושיות על זה:
מי אומר שזה מדבר בלילה ועל המטה?
מי אומר שזה מדבר בקריאת שמע, שאולי מדבר בתורה?
אילו היה אחד מן הקושיות מתורצים, לא היה כל כך קשה לי לומר שאינו דווקא, ושרצה לומר שמתחיל כיון שהוא תורה או כדומה. אבל, אם שניהם אינם דווקא, אין דין זה שייך בכלל לקריאת שמע שעל המטה, והיה לו לומר אותו על תורה.
** מה בתלמידי חכמים:
* ביאור פסוק:
*צריך לבאר עוד מהו ענין הגמרא והשקלא וטריא שלו.* 
** דרשת ריש לקיש:
יסורים בדילים ממי שעוסק בתורה. (כמובן, יש קושיות על זה מהרבה חכמים, כמו רבי עקיבא. יש לומר שיש הרחק, אבל יש דברים שדוחים את ההרחק.) לומדים את זה ממש"כ, "ובני רשף יגביהו עוף." עוף היא תורה, שכ', "התעיף עיניך בו ואיננו" (הערנו לעיל שזה קשה), ורשף היא יסורים, שנאמר "מזי רעב ולחמי רשף."
רש"י פי' שרשף ר"ל יסורים ומזיקים לפי ריש לקיש. איני יודע איך רואה את זה.
** קושיית רבי יוחנן:
רבי יוחנן מקשה שאפילו תינוקות של בית רבן יודעים זה, שנאמר "אם שמוע תשמע לקול ה' אלקיך והישר בעיניו תעשה והאזנת למצוותיו ושמרת כל חקיו כל המחלה אשר שמתי במצרים לא אשים עליך כי אני ה' רופאיך." לכאו', "כל המחלות" רצה לומר יסורים. וא"ת איפה כתוב שם עוסק בתורה. ויש לומר שזהו "האזנה למצוות." דחוק. גם ק"ק, שאולי צריך זה עם קיום מצוות. ויש לומר שבי"כ ובי"כ צריך זה עם קיום מצוות. אבל, עיין בגמרא ביבמות, שיש מחלקת בלימוד תורה בלי מצוות.
יש לדון מהו קושיית רבי יוחנן, אם הוא שאין צורך לומר לומר זה, שהוא פשוט, או שבוודאי אין הפסוק אומר כן, שהוא פשוט.
רבי יוחנן אמר "אלא." יש לדון מה בא לעשות. אולי הוא בא לומר שאם יש דבר לומר בתורה ויסורים, זהו מה שיש לומר. גם אפשר שהוא אומר שאלא כך נדרוש מן הפסוק. לראשון, יורת קל אם נפרש כצד ראשון בקושייתו, אבל גם אפשר לצד שני. לצד שני, נראה שנפרש כצד שני. (רצה לומר, צריך להיות שמה שאומר צד שני הוא נכון. לא צריך להיות שזהו קושייתו, שאולי עיקר קושייתו הוא כצד ראשון. אבל, צריך להיות נכון שאין לדרוש משם.) וא"ת לצד ראשון, מה נעשה עם הפסוק. ויש לומר שנדרוש אותו כרבי יצחק. גם יש לומר שיכול להיות שיש שני מקורות לזה, שה' כופל אותו. אבל, הקשה לו שהיה לו להביא אותו ממקור היותר פשוט. (באמת, זה כעין צד 1.5). ותחשב.
** דין של רבי יוחנן:
רבי יוחנן אומר שכל מי שאפשר לו לעסוק בתורה ולא עוסק, ה' מביא עליו יסורים מכוערים ועוכרים אותו. (לשון מוזר הוא, שכל יסורים עוכרים אדם. נראה שהוא מחמת לשון הפסוק.)
מביא מקור ממש"א "נאלמתי דומיה החשיתי מטוב וכאבי נעכר, שכיון שהחשיתי מטוב - וטוב היא תורה, שנאמר "כי לקח טוב נתתי לכם תורתי אל תעזבו" - כאבי נעכר, שבאו לי יסורים. (אף לומד מזה שזה סיבה לביאת יסורים, ולא שממילא באו יסורים שהיה ה' עוצר כל זמן שהיה לומד. אולי אה"נ כן אומר, ומחדש שחוזרים ובאים עליו, ולא שכיון שבטל שעתם, בטלים לעולם.)
קשה איך רבי יוחנן מביא מקור, שהוא גופא בא לומר איך לדרוש את הפסוק שעוף מעלה רשף. דבר ראשון, קשה איך דורש את זה מן הפסוק. צריך לומר שהוא מעלה עוד יסורים, שהם יסורים שהיו באים לו ממה שלא למד. עיקר החידוש הוא שיש יסורים כזה. וא"ת הרי כבר הביא מקור לזה. יש לומר שכיון שלא פשוט, לא קשה שיהיו שני מקורות. גם יש לומר שאין כל אחד מהם כל כך מוכרח, ואז צריך שני פסוקים.
** למה הביא:
הביא כיון שדורש (על כל פנים, ר"ל דורש) פסוק שהביא לעיל - "בני רשף יגביהו עוף."
* ביאור ענין יסורים:
** יסורים באים על אדם/(ביאור הסדר?):
א. יפשפש במעשיו – נחפשה דרכינו ונקחרה ונשובה עד ה’. /איך אפשר שיפשפש ולא ימצא./
ב. תולה בביטול תורה – “אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו" /(למה לא הביא הפסוקים מלעיל?)/ /(למה אין זה בכלל מעשיו?/) /איך אפשר שיתלה ולא מצא/ /(בדק ולא מצא או חזק ולא הועיל)/
ג. יסורים של אהבה הם – “כי את אשר יאהב ה’ יוכיח.” /למה בידוע – אין סיבה אחרת (אז, צריך לומר שבכלל פשפוש וכדומה הוא תשובה. זה תלוי בענין יסורים של אהבה.) או ראוי לכך. – אם לא כן, יש לדון אם יכול להיות שהם של אהבה./
** יסורים של אהבה:
*מה הם יסורים של אהבה?*
כל שה’ חפץ בו /(מה ר"ל)/ מדכאו ביסורים – וה’ חפץ דכאו החלי. יכול אפילו קבלם מאהבה? /(יכול מה? יכול שישארו? יכול שזה יביא לה’ מה שרוצה? יכול שזה יביא לו שכר?)/ אם תשים אשם נפשו. מה אשם דעת אף יסורים דעת. /(יש לדון בדמיון.)/ אם קבל מה שכרו? “יראה זרע יאריך ימים.” גם תלמודו מתקיים – למה זה חלוק, שהוא בפסוק אחר, שנאמר "וחפץ ה’ בידו יצל.” /צריך ביאור איך זה מוכיח כן. צריך לומר ש"ידו" מלמד כן./
איזה יסורים הם של אהבה? /(יש לדון למה לא אמר שהוא כשמפשפש. נראה שזה גם אם פשפש.... וא"ת מה לנו בזה . ויש לומר שהוא כדי לקבל באהבה. ויש לדון. גם יש לומר שהוא לדעת אם פשפש טוב. גם יש לומר שחולקים. ויש לדון אם מה שמפסיק אותו הוא סימן או מה שלא מפסיק אותו הוא סימן. ותחשב.)/ /יש לדון אם אלו הם סימנים ביסורים או במי שבאים עליו יסורים (שאינו נתבטל על ידם מן התורה, אלא מנצח על היסורים./
רבי יעקב בר אידי ורבי אחא בר חנינא חולקים:
אחד - כל שאין בהם ביטול תורה - "אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו" /מניח שרצה לומר שאין ביטול, אף שהיה אפשר לומר שהוא שנשאר בהם תלמוד/
אחד - כל שאין בהם ביוטול תפילה. /ביטול תפילה בכלל או ביטול כוונה וכדומה?/ - ברוך אלקים אשר לא הסיר תפלתי וחסדו מאתי. /איך זה מקור?/
רבי אבא בריה דרחב"א בשם אביו בשם רבי יוחנן - שניהם יסורים של אהבה /צריך שניהם או שכל אחד מהני/ - כי את אשר יאהב ה' יוכיח. /מזה זה מלמד?/
אז, מפרש "מתורתך תלמדנו" /זה קשה גם לאחד מן הצדדים לעיל/ ואומר שדורשים מזה "תלמדנו," שדבר זה נלמד מן התורה, שהוא קל וחומר משן ועין. מה שן ועין הם אחד מאיברי אדם, ועבד יוצא בהן לחרוס, אז יסורים שממרקים כל גופו של אדם /אז, זה רק ביסורים שבאים על כל גוף אדם./ /קשה, שאין שן של עבד מבטל אותו. ויש לדון, שאינו חייב בתפילה וכדומה. אבל, עדיין אין בו ביטול. ויש לומר שזה ביטול באונס, והוא כעבד./ צריך ביאור מהו העל אחת כמה וכמה שיוצא לחירות. אולי רצה לומר שיוצא מעבדות האנושי, שנעשה יותר רוחני. גם יש לומר שבא ממה שחייב לה', דהיינו עונשים. אם כן, צריך לומר שהענין הוא ביטול עוונות. אבל, לעיל משמע שפשפש ולא מצא, וצריך לומר שלא עבר. אולי צריך לומר שעברתו היה מעט (ובוודאי אם פשפש ולא מצא רצה לומר שלא מצא דבר ראוי - או מתאים או גדול - לעונש כזה.)
מבאר שזה כמש"א רשב"ל, שנאמר "ברית" במלח - ולאשתבית מלח ברית 0 ונאסר ברית ביסורין - אלה דבר הברית. כמו שבמלח ממתקת את הבשר /עושה שראוי לאכילה או שראוי למזבח?/, כך הוא ביסורים, שממרקים כל עוונות אדם. אם זה ממש אותו דבר, צריך לומר שרצה לומר שמסיר עוונות. /(לעיל הזכיר מה שממרק לחומרא שלו. צריך ביאור, שהיה לו לדון בצער שלו.)/
** שלש מתנות שנתן על ידי יסורים:
/מתי יש יסורים - בשעת נתינה ראשונה או בנתינה לכל אדם?/
רשב"י:
תורה - אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו. /נמצא שלש פי' בקרא זה/
א"י - כי כאשר ייסר איש את בנו ה' אלקיך מיסריך כי ה' אלקיך מביאך אל ארץ טובה.
עולם הבא - כי נר מצווה ותורה אור ודרך חיים תוכחות מוסר. /מניח שר"ל דרך חיים שבו תזכה לעה"ב או דרך חיים הטוב (שממילא הוא מה שיש בו עוה"ב)/
** עוד מימרא:
עוסק בתורה וגמ"ח קובר את בניו - מוחלים לו על הכל. /האם זה יסורים של אהבה?/
/יש לדון אם רצה לומר כל אחד בפני עצמו או לא. עיין בקושיית רבי יוחנן. לא מסתבר לומר שת"ת בפני עצמו מהני, אם לא שנדחה שאם הוא מומר על מצוות, אינו נחשב ת"צ, כמו שדן גמרא ביבמות./
רבי יוחנן
ת"ת וחסד יש מקור - בחסד ואמת יכפר עוון. חד הוא גמ"ח, שכ' רודף צדקה וחסד ימצא חיים צדקה וכבוד /מה רואים מקרא זה?/ ואמת היא תורה, שכ' אמת קנה ואל תמכור.
קובר את בניו מנין.
ההוא סבא לומד בנים מג"ש מ"עון," שכ' בחסד ואמת יכפר עוון, וכ' משלם עון אבות על חק בניהם.
** סוגיה:
רבי יוחנן אומר שנגעים ובנים אינם יסורים של אהבה.
נגעים לא - הרי הם מזבח כפרה /זה חשוב בידיעה מהו יסורים של אהבה/ דוחה שהם מזבח כפרה ולא יסורים של אהבה. גם מת' שיש חילוק בין לן להו. גם מתרץ שיש חי' בין צנעא לפרהסיא.
בנים לא - אם היו לו ומת, הרי רבי יוחנן היה אומר דין גרמא /מה ראיה יש משם - לא יבואו לו עונשים אחרים או שלא יאמר לבני אדם או שאין באמירה לבני אדם ענין, שאמר רק להוכיח שהוא של אהבה/, אלא שלא היו לו.
** סוגיה:
רבי חייא בר אבא נתחלה. רבי יוחנן בא לו ושאל לו אם חביב עליו יסורים. /אולי שאל לו אם הם של אהבה./ אמר לא הן ולא שכרן, ואמר שיתן לו יד, ונתן לו יד, ורפא אותו.
רבי יוחנן נתחלה קרה לו אותו דבר עם רבי חנינא. הק' ל"ל הוקים ר"י לעצמו (שרואים שהיה יכול /היה אפשר לומר שרק היה אפשר אחרי כן./). מת' שאין חבוש מתיר את עצמו (/?/)
רבי אלעזר חלש. רבי יוחנן בא לו. ראה שהיה בבית אפל. גילה לזרעו, ונפל אור. ראה שהיה ר"א בוכה. שאל לו למה - אם תורה - אחד המרבה ואחד הממעיט. משוני - לא כל אדם זוכה לשני עולמות. אם משום בנים - דין גרמי. אמר ליה שהוא מפני אותו שופרא שיבלה בעפר. (/?/). אמר לו שעל זה ראוי לבכות, ובכו. קרה להם אותו דבר וריפא לו.
** סוגיה:
רב הונא נסרחו לו אברע מאות דני חמרא. ר"י אחורא דר"ס חסידא ורבנן (/למה לא אמר רבנן/) ואמרו לו לעיין במעשיו. שאל אם חשוד. שאל אם חשוד ה'. (/אולי הם של אהבה? ביטלו אותו מתורה./) אמר שאם יש מי ששמע על יו דבר יאמר. אמרו ליה ששמע שלא נותן שבישא לאריס. אמר שהוא גונב הרבה. אמר שבתר גנבא גנוב וטעמא טעים. (/עביד איניש דינא לנפשיה/) אמר שקיבל שיחזיר לו. יש אומרים שאייקר חלא ויש אומרים שהיה חלא. (/תלוי באם נס גלוי טוב או רע; עיין בשבת גבי אב שינק בן./)
** רש"י:
פשפש ולא מצא – לא מצא עבירה בידו שבשבילה ראוין יסורין הללו לבא: - יש לדון אם רצה לומר שאינו כל כך גדול או שלא כל כך שייך לעונש.
אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו – שבשביל יסורין צריך אדם לבא לידי תלמוד תורה: - מעניין שאומר שבשביל יסורים בא לתלמוד תורה, ולא שאינו מבטל אותו.
יסורין של אהבה – הקב"ה מייסרו בעוה"ז בלא שום עון כדי להרבות שכרו בעולם הבא יותר מכדי זכיותיו:- משמע שאין עוון כלל. יש לדון למה זה מרבה זכר. אולי הוא שכר ממה שלא טען על ה'. גם יש לומר שרצה לומר שהוא בלי עוון הראוי לכך. ותחשב.
וה' חפץ דכאו החלי – מי שהקב"ה חפץ בו מחלהו ביסורין:
אשם – קרבן: - רצה לומר, ולא חטא ממש.
נפשו – מדעתו:
דבר זה – שאשרי אדם אשר תיסרנו יה:
מתורתך תלמדנו – כלומר מתורתך אנו למדין אותו:
נאמר ברית ביסורין דכתיב אלה דברי הברית – אחר הקללות נאמר במשנה תורה:
אף יסורין ממרקין כל עונותיו של אדם – גרסי': - גירסת רש"י נצרך; עיין לעיל.
ודרך חיים – חיי העוה"ב הויין לו תוכחות מוסר לאדם: - רש"י מבאר שחיים רצה לומר חיי עוה"ב. נראה שהוא מפני שרק זה חיים שנמשך. (יש לדון למה נחשב חיים יותר מגיהינום.)
ובנים – קא סלקא דעתיה הקובר את בניו: - יש לדון אם חשב שהוא שלא נולדו ושקובר או רק כשקובר.
ארבע מראות – שאת ותולדתה בהרת ותולדתה. בהרת עזה כשלג שניה לה כסיד ההיכל. שאת כצמר לבן שניה לה כקרום ביצה:
הא לן והא להו – בא"י שערי חומה מקודשות בה ומצורע טעון שילוח חוצה להן אינן יסורין של אהבה. בבל שאין טעונין שילוח והן מזבח כפרה הוו יסורין של אהבה: - צריך ביאור. נראה ששילוח מן המנחה יש בו ביטול תורה. /---יש לדון אם רבי יוחנן סובר שאף זה ואף זה דהיי' שיש ביטול זה וזה-/
בצנעא – תחת בגדיו: - גם יש לומר שלא נטמא מחמתו.
דין גרמא דעשיראה ביר – זה עצם של בן עשירי שמת לו: - גם יש לומר שהוא בן העשירי שלו, ושנודע שלא היו לו בנים. של רש"י נראה יותר.
ביר – כמו בר וצר עצם פחות מכשעורה ממנו בסודרו לעגמת נפש. וגברא רבא כר"י לא באו לו יסורין שאינן של אהבה: - עגמת נפש או שיאמר לבני אדם כן.
דהוו להו בנים ומתו – הוו להו יסורין של אהבה שהאבלות מכפרת על עונותיו: - משמע שהוא לכפר על עוונות.
גלייה – ר' יוחנן לדרעיה:
ונפל נהורא – שהיה בשרו מבהיק שיפה היה מאד כדאמרינן בב"מ בהשוכר את הפועלים (ב"מ דף פד.): - יפה = אור?
אי משום תורה – שלא למדת הרבה כרצונך:
אחד המרבה ואחד הממעיט – לענין קרבנות שנויה בשלהי מנחות (דף קי.) נאמר בעולת בהמה ריח ניחוח ובמנחה ריח ניחוח ללמדך שאחד המרבה וכו':
אי משום מזוני – שאינך עשיר: - נראה שיחשוב שזה סימן שאינו צדיק.
על דא ודאי קא בכית – על זה ודאי יש לך לבכות:
תקיפו – החמיצו:
דני – חביות:
ליעיין מר במיליה – יפשפש במעשיו:
אי איכא דשמיע עלי מילתא לימא – אם יש בכם ששמע עלי דבר שאני צריך לחזור בי יודיעני:
שבישא – חלקו בזמורות הגפן שחותכין מהן בשעת הזמיר ותנן (בב"מ דף קג.) כשם שחולקין ביין כך חולקין בזמורות ובקנים. שריגים מתרגמינן שבשין (בראשית מ):
מי שביק לי מידי מיניה – וכי אינו חשוד בעיניכם שהוא גונב לי הרבה יותר מחלקו: - רצה לומר, רק חשוד, שאינו דן דין לעצמו. אבל, יש לדון, שמשמע שרק טועם טעם גניבה, ואינו באמת גניבה.
בתר גנבא גנוב כו' – הגונב מן הגנב אף הוא טועם טעם גנבה:
** תוס':
הא לן והא להו. פי' רש''י לבני ארץ ישראל שצריכין שילוח חוץ לשלשה מחנות לא הוו יסורין של אהבה. ותימא דשילוח מחנות לא היה נוהג אלא בזמן שהיובל נוהג ובתי ערי חומה. ובימי האמוראין לא היה היובל נוהג כדאמרינן במסכת גיטין (פ''ד דף לו.) והיאך היה מדבר ר' יוחנן מדבר שלא היה נוהג בימיו. וי''מ הא לן והא להו לענין טומאה שנזהרין בא''י ולא בבבל: - משמע שאף בלי דין שילוח, היו עדיין מטמאים אותם. יש להעיר שאז נראה שהיו טמאים לעולם, שאין קרבן שיכפר עליו. - משמע שעוד נוהג בזה"ז (ולא אומרים שבטל או שכיון שאין טהרה, לא נטמא אותו).- אם כן, ממש נוהג בזמן הזה, שחזקת כהונה מספיק להוציא מחזקת טהרה. ותחשב. עיין מנחת אשר תזריע (כז), שדנו בזה הרבה פוסקים. - מהיכי תיתי רק כשיובל נוהג. - מבואר שדן בצרעת ממש שמטמא מגמ', שאם לא כן, קשה ארבע מראות. - יש לדון אם אינו נזהר רצה לומר שאין טומאה נוהג (או שאין כהנים נזהרים לטמא) בחו"ל או שאין נוהגים בחומרות טומאה בחו"ל, שיש הרבה שנוהגים לאכול בטומאה.-מסתמא מפני שאין שם תרומה וכדומה.
והאמר רבי יוחנן דין גרמא דעשיראה ביר. פי' רש''י דלאדם חשוב כר' יוחנן מסתמא לא היו אלא יסורין של אהבה. ותימא דהא מסיק דהיכא דלא הוו ליה בנים כלל לא הוו יסורין של אהבה והרי כמה צדיקים שלא היו להם בנים ואי משום בנות ר' יוחנן נמי הוו ליה בנות בפ' בתרא דקדושין (דף עא:) ונראה לפרש דהכי פריך והאמר ר' יוחנן דין גרמא וכו' אלמא מדהוה רגיל לנחם אחרים בכך ש''מ דהוו יסורין של אהבה. אבל אינו תלוי בכך שהצדיקים עצמם פעמים מעונים ביסורין: - עיין לעיל, שדנינו בזה.
ה''ג לא כל אדם זוכה לשתי שלחנות. אבל אין לגרוס אין אדם זוכה דהא כמה צדיקים זוכין לשתי שלחנות כגון רבי וכדאמרינן בפרק בתרא דהוריות (דף י:): - לגי' שלו, יש לדון איזה נחמה יש בזה. נראה שהוא נחמה במה שבוודאי אינו בדרגה נמוכה, שהרבה יש בדרגה כזה. ותחשב.
דינא בלא דינא. הרבה צדיקים יש שלוקין בגופם ובממונם אלא הם היו יודעים שלא היה נותן שבישא לאריסיה והיו רוצים לרמוז לו שלא יעשה עוד: - אז, היה לו מה להשיב. נראה שהאו הבין למה אמרו כן לו, שהיה פשוט שאינו נכון. קשה, שמיד לעיל אומר שיש הרבה צדיקים שלא היו להם בנים דהיי' שהוא יסורים ממש, ואז קל לומר שיש לצדיקים יסורים. אם כן, קשה למה לא אומר כן כאן. ותחשב.
