למדתי את זה עם ש.ל.
** פרק חמש עשרה נשים
* ב:
** חמור -
נ’ שני מהלכים:
א. מונה על פי קרק’ של ערוה. נוקט קרק’ של חומרא.
ב. מונה על פי חידוש, והוא לא זו אף זו. אז, נקט היותר חמורין קודם. לא נ’ כן, שלא משמש באותו לשון. (ק”ק ל”ל. ונ’ שדוחק לומר לא זו אף זו.)
יש לציין לגמ’ לקמן שמק’, “כולהו מדרשא,” שמשמע שדן בייבומו, ולא בערותו. ואולי אינו שוה לצדדין חלוקים.
* ג.
** אם אתה אומר -
לשונו משמע שאין הענין שאם יחלצו ייבמו, אלא שאם יאמרו שהדין כן, ייבמו. ותח’.
* ג:
** מה -
ע’ לקמן, שיש צד שנלמד מהיקש.
** מותר לאחים -
ע’ לקמן, שיש צד שאינו נל’ ממ”מ.
** עונש -
ק”ק למה לא נאמר שקרא של עליה מרבהו לתוך אשת אח, וממילא פשוט שנכרת. ונ’ שרק צ’ קרא זה לשאר עריות הנלמדין במ”מ (ויש להעיר ממה שכתבנו לעיל בד”ה מה), שאין עונשין מן הדין (יש לדון, שאין לומ’ איסור, אלא שלא הותר איסור. ואולי תלוי למה אין עונשין. ותח’.), אלא שאז נחלל בפרשת עריות ובכרת שבו.
יש להעיר שזה, לכאו’, אינו כרבא, שלכאו’, לרבא כיון שפשוט שלא נדחה, אין צריכים מה מצינו.
ואפשר שלא באמת מק’ ומת’, אלא מזכיר מקור עונשם (דחוק).
* ד.
** במשנה תורה -
לכאו’, ר"ל שבמשנה תורה רגיל שיהא מופנה או מוכח.
* ה.
** שאני כהנים -
נמצא, לכאו’, שיש צד שגבע כהן לאו יותר חמור מעשה. יש לדון אם לאו יותר חמור או יש יותר סיבה לעשות כלאו (כיון שלעולם הוא הכי חמור (ע’ לקמן) ותח’.) ודע שרוצה בהן תורה עשיין ולאוין, ואז, צריך ביאור למה רק לאווין יהיו יותר חמור.
* ו:
** מה לי -
צריך לבאר הבערה אין בו בישול, שיהא בו נפק"מ. ואולי נמצא בפחות משיעור בישול. ואולי שייך אם מכבה מיד או נעשה עפר, שאז לא נתבשל (ויל"ד, שמסתמא, בין כך, נתבשל).
* ז.
** מה עבודה -
צ"ב למה אין לומ’ ממיתת ב"ד כיון שנלמד לשאר דינים. ותח’.
** דוחה אותה -
יש לדחות ששם לא נדחה עבודה. וצ"ל שדי במה שנדחה במה שזה לא מקיים מצותו.
** לא תבערו -
יש לדון אי זה משנה דין קבורת מת מצוה.
** קבורת -
מה שנדחה הוא או מלאכת הוצאה (ולצרך מת הוא, ואז נחשב מלאכה לצורך.) או קבורה או מילוי עפר.
** בהן -
מעניין שנישב סותר לחלל, ששניהם מצריכים מתנות. שו"ר בתוס’. ע"ש.
* ז:
** ואי לא -
לכאו’, זה לא שייך; הענין הוא רק שאי אפשר ללמוד את השאר ממנו בדין זה, ולא שאין דינו חוזר להיות כשאר. ותו"ת.
* ח.
** תינח -
יש, לכאו’, עריות שבהם זה אי אפשר, כמו בתו.
הוקש- מעניין שדחיית חד איסור (אשת אח) נחשב אותו דין של דחיית שני איסורים.
* ט.
** ה"א נחלק -
נ’ שר"ל שרוצים קרבן שירצה באופן הכי טוב לאותו חטא. ממה שהוא חלוק משאר, צריך לומר שבהמה חלוקה יביא. אי לא ביארה תורה, לכאו’, לא נוכל אנו למצוא. ותו"ת.
* ט:
** בנשואין -
יש להעיר שאותו אונס בין כך ובין כך מוכרח במתניתין. צריך לומר שרק לו רצה עליו "תני עלה.” וצריך ביאור.
* י.
** אלא לרבי -
נמצא שר’ חייא אמר כללים אחרים בביאור משנה מרבי. קשה, שרבי כתב את המשנה. יש לומר שלא כתב משנה זה. ותח’.
** ר"ש -
וא"ת תסייעיה לרבנן. וע’ ברש"י שנ’ שבא לת’ לזה.
* יא:
** כיון -
יש לדון מהו צד זה:
א. מקרא יוצא מידי פשוטו.
ב. זה רק דרשה (טומאה מעריות), ורק דורשים אותו לדין קרא ולא לפשטותו.
ג. כיון שכתב היא, ורק הוה פשטות קרא, נתמעט. ותו"ת.
** כשרה -
יש להעיר שחד דוקא וחד אגב. רק משנה איזה דוקא. אפשר לומר- ודחו"מ בלשון גמ’- שמחדש שניהם יכולים להיות לאו דוקא.
* יב.
** היא חולצת -
אם כן, השבנו על חד צד. ותו"ת.
* יב:
** שמא -
א"כ, ק’ על רב"ל.
* יג.
** בלי סימנים -
לכאו’- ואולי יש לדון, אלא שדחוק הוא- סימנים הם סימן, ולא סיבה. אם כן, קשה מה עושה סימנים יותר סימן יותר מבנים, ולמה לא נאמר שבנים הם סימנים (ומה בין זה לת’ קמא):
א. לזה מוכרח שיש סימנים. אכתי קשה מה לנו בזה. אולי מחדש שחוששים לצער לידה (ואולי זה גורם שום נפקא מינא אחר). גם יש לומר שיש נפקא מינא אי לא נמצא סימנים------
ב. יש לומר שבנים באים מסימנים וסימנים באים מדגלות. במציאות, זה לא נראה. גם יש להעיר שעוד אין נפקא מינא.
** משום צער -
קצת קשה למה לא אומרים שמוכרח שנשרו כיון שיש הוכחה לסימנים (משמע שסיבה להניח סימנים קטנה מסיבה להניח שלא נשרו).
** גירש -
משמע שאף אי מת קודם נפטרה (מחמת זיקה).
* יג:
** עד כאן -
יש לומר שהיה אומר כן באמת כיון שהיה חוזר בתשובה. גם יש לציין לגמ’ תענית (ט) שר"י לא הגיע עד קרא של בן ר"ל.
* יד.
** עשו ועשו -
צריך לומר שדנים על לפני בת קול, דאי לאו הכי היה לו להקשות עדיין מלפני בת קול.
** בית שמאי -
אפשר שתלוי באי רוב הוא סיבה להניח שנכונים או שיש סיבה אחרת לפסוק כרוב. יש לבארו לשני צדדים. ותח’.
** שבת -
זה קצת מעניין, שאם הבעיא הוא שנראה כשני תורות, מה לנו בחומרתו. יש לומר שאז אי אפשר לדחות שאינו שני תורות אלא שעובר על דין. ותח’ עוד.
** היכי עביד הכי -
לכאו’, היה יכול לבאר על פי גמרא פסחים (נא:).
* יד:
** לא נמנעו -
אף הכא אפשר לדחות שלא עשו.
* טו.
** שמאי -
נמצא עוד מחלקת שמאי והלל. וק’, אז, על גמרא שבת. ואולי שאני הכא שיש עוד חולקים- תלמידיהם. זה מעניין, שלכאו’ (יש לדון) תלמיד חול’ מרבו ולא ייחשב חולק אחר.ויש לדון.
** שמא -
נמצא שלצד שבת קול שבלאחר בת קול חולקים שכבר היה בת קול בימי שמאי. ואולי רק דן לחד צד.
** לאפושי -
זה ק"ק, שאי לא עשו, הענין הוא שכל כך פשוט הוא שהלכה כבית הלל, ואז לא עשו. אם כן, אף זה קצת צריך ביאור.
* טו:
** הודעתי את אבא -
יש להעיר שהיה בן של ר’ צדוק, והוא המתענה לארבעים שנה. מעניין[fn:1]. ותו"ת.
** אי אמרת לא עשו -
יש לדחות שרבותא הוא שעשה אף דברים שלא ניכרים כבית הלל. ואולי אין טוב בזה.
** שאלו את ר"א -
ר"י, לחד צד, מוכרח לסבור שעשו (אלא שראיית גמרא מניח שאין מציאות שאומר מוטעה. ויש לדון, שאולי לא ידע, ורק הניח לשיטתו שעשו.)
** בני צרות -
צריך ביאור מה ראיה יש; דלמא מי שהתיר היה מבית הלל. ואולי היו ב"ש מוחים אילו היו חולקים.
* טז.
** ועיניו -
יש לדון על מה קאי:
1. מבאר המשך מעשה.
2. מבאר למה היה קשה לרבנן (שהיו בצער איך יחלקו עליו).
** ’ יהושע
ר
- מענייו ששלחוהו, שסבר שאין בת קול. גם מעניין ששלחו ר"ע, שרש"י בב"מ (לז:) כתב שהיה מתלמידי בית שמאי. ואולי רבותא היה, להראות שאף ר"י מודה  בזה.
** אמר לתל
’- היה מוכרח לו לדעת שהיו עוד ממה שאמר שפחתו לשון רבים. אולי סבר שהוא כבוד ר"י לדבר כן.
** הניחום -
בפשטות, רצה לומר שלכן לא כיבשום. ואולי ר"ל שלכן לא קדשום קדושת עולם.
** קרתויים -
יש לדון אם התי"ו דגוש. אי לא, אז אם דל"ת אומר "d,” משמע כספרדים האומרים לתי"ו "t.” (ודע  שאם דל"ת אומר "th” קשה, אולי יותר דומה ל"s..” ויש לדון, שאכתי דומה ל"d.” יותר טוב לבבליים שאומרים לתי”ו “th” רפה.) אם היה דגושה, אז, מובן למה דומים, ש"d” דומה ל"t.” ותחשב ותבין.
* טז:
** ר"י -
לשוטתו, שסבר שעבד וגוי הבא על בת ישראל עושה ממזר. ועיין לקמן.
** שר העולם -
משמע שמלאכים נעשים זקנים. ונראה שזקנה לא רצה לומר סימני זקנה ממש, ואין זקנה לה’ כיון שלעולם היה, ואז אי אפשר שיהא יותר זקן ממה שהיה, אבל מלאכים נבראו, ואז יש להם זקנה.
** מי איכא -
מעניין מה שלא העיר על נערות. ותחשב.
* יז:
** שניה בנשואים -
גם אצ"ל שניה בנשואים, שיכול להיות נשואיה הרביעי, למשל. גם חבירתה יכול להיות נשואה פעם לפני אותה נשואים. אולי לא מונה אותם כיון שאינם שייך לייבום זה או כיון שלא הוזכרו במשנה.
** מלוט -
קצת קשה למה לא תירץ שמקישים לחומרא (ונחשב חומרא כדאמר לעיל (ח.)), שזה אף בגזרה שוה (עיין הל"ע (ד-כב) ומנושאי כליו (שם))
** אמר רב -
מעניין שמקשה כן על רב, רב נחשב תנא (עיין רשי בבא קמא (יח:)). אולי רב חלוק כיון שהיה אחרון עד כדי כך שלא נשנה במשניות (ותחשב מה לנו בזה. ותחשב מה לנו בהיותו תנא. ונראה שהפשטות הוא שאימןו צריך לומר הלכה כפלוני כיון שלולי פלוני היה סובר כן. אם כן, אכתי צריך ביאור.)
* יח.
** ר מאיר -
’
יש להעיר שסובר שחוששים למיעוט. (זה נתעורר על ידי ש.ל., שאמרו, אבל א ידעתי אם אמרו במכוון.)
ר"ג- יש לדון מה סובר גמרא:
א. אין שום איסור לבטל מצות יבמים.
ב. אם אין זיקה, אין לאסור לבטל מצות יבמים.
דשמואל- קצת קשה מהיכי תיתי שאמרו משום שום אדם. נראה שמניח שלא היה חולק על רבו רב. (יש להעיר שלא מצינו בכל כך כמה מקומות שיאמר ר"י דבר בפני עצמו. אע’ שבת קח:)
* יח:
** וצריכי -
קצת קשב איך נאמר "כיון שאיתמר משמיה. . . ." ואולי רק ר"ל שלשמואל אצ"ל שאמוראי היא. ונראה שגם כן מוסיף שמצינו ששמואל סבר דבר הדומה לזה.
* יט.
** מדאו
’- משמע שלצד ראשון היה מדאו’. משמע, אז, שספק דאו’ לחומרא מדרו’. ותח’. ויש לדון.
* יט:
** הא בבא -
קשה למה לא אומר אף על מתניתין לערבינהו.
* כ.
** קדש עצמך -
צריך ביאור מה מהני בזה.
** מידע ידיע -
צריך ביאור למה איין אומרים כן אף בממזר, שאף שם יש הבדל בין מצב ייבום למצב שאינו ייבום. ותחשב.
** ואיתימא ר"א -
יש לדון אי צד זה סובר שהוא היה האומר או שטען כן על רבא (ודחוק לומר שאומר לשון כזה על רבא).
* כא.
** קח -
משמע שיש ס"ר, אלא שהוא יותר קטן. ואולי רק רצה לומר שציווי יותר קטן.
* כא:
** אימא רבא -
יש לדון מהו הענין, אם הוא שרצו שיהא קל לבני אדם לזכור או שבני אדם יטעו בין כלם לערוה. . .  ותחשב. ועיין בשי"ח ש"י בריש ביצה.
* כב:
** מאי שייר -
ואם תאמר הרי יש שנים. ויש לומר שלקמן מנה אותם לחד. ויש לדון שאכתי שנים הם. במקום אחר, כתבתי שדנתי עם א.י.ש. אי ענין מה שצריך שנים הוא שאי יש רק חד, היה התנא גומר, שאין בו כל כך טירחא, או שאם יש רק אחד, בדרך כלל יותר מסתבר לומר שלא סבר כאותו אחד מלומר שלא כתב אותו. כיון שחסר שנים לא מסתבר שלא סבר כשניהם, ואז, צריך לומר שחסר אותם. לצד שני, טוב לומר שכאן, מסתבר שלא סבר כן, שאי לא סבר כחד, לא יסבור כאידך, שחד דין הם. (שוב אמר לי א.י.ש. לעיין בתוס’ כאן.)
** שניות -
יש לדון מה ר"ל:
א. אין ערוה כל כך חמורה, שרק גזירה היא, ולא נגזור.
ב.אולי ר"ל שאף גוים אין להם דינים אלו. יש להוסיף שכ"א טוען רק איסור, ולא מניעה מלעשות איסורים אלו. ותו"ת.
** כיון -
נראה שהענין הוא שכיון שבן יקיים שם עד שאין צורך לייבום, מסתמא אח יקיים שם על ידי הולדת בן. ותו"ת.
* כב:
** פסול -
קצת קשה, שלכאורה לא תלוי בכשרות כי אם באיסורה לו.
** עיין -
יש לדון מהו מדרשה:
א. יש בן בחשבון שהוא מחודש.
ב. יש בן שלא כל כך ידוע (א"ל שונו כל כך ידוע שיש לו בן זה כיון שבא בעבירה), וצריך לעיין למצוא אותו.
** עושה מעשה -
הוה מצי לומר שהולידו באונס או בשוגג. (ואם תאמר אין קישוי שלא לדעת. ויש  לומר שנתכוון לאשתו.)
** סלקא דעתך אמינא -
זה רק הוה אמינא לדין טומאה.
** בעלמא -
קצת קשה למה לא נאמר לדרוש את זה כיון שדורשים אי יש מה לדרוש. ותחשב.
* כג.
** משום רשב"י -
ר"ש לשיטתו.
** בכל סוגיא זה
עיין בקידושין.
* כג:
** לסריס -
בפשטות ענין ייבום הוא שטוב שיהא אדם זכור ושמו מקויים, ואז, אף לאחר מיתתו, יש ענין לקיים את שמו. אולי הענין הוא ששמו כבר עומד ליבטל. ודחוק, שמה לנו בזה. ועוד שאי יש ענין ייבום, אינו עומד לכך. ואפשר שאין ייבום מקיים את שמו, שמה שאי אפשר שיהיו לו בנים גורם שלא יוכל לייחס לבני ייבם. ותחשב על זה.
* כד:
** הא גיורת -
קשה מהיכי תיתי שהיא נתגיירה לשם כך. ואלי נצטרך לחוש.
** לא יוציא -
למס’, צריך ביאור למה לא אמר לא יכניס.
** וב"ד -
הוה מצי לאוקמי בארוסה (עיין בסוף גיטין).
* כה:
** יוציא -
לא הבנתי מה מרוויח לצד שהוא מח’ איסור לבטל מצות יבמין. אולי יש כעין מש"כ רש"י דה ולימא (כח.) (שוב אמר לי א.ר. שיש נאסרה מדרבנן.
** אסור -
אמר ר.ע.ו. שמשנה זה ראיה שחלוצה עושה טוב ולא רק מתיר. ותחשב.
** נראה שמה שחוששים למיתה
כאן יכול להיות על שם מה שכתב גמרא שבת "מת אחד מן האחים ידאגו כולם.” זה יתרץ קושיית תוספות ראש יומא.
** ר’ יוחנן -
נראה שמה שר"י קפד כל כך שיהא תנא שאינו יחידאה ושלא ננקט תרי תנאי הוא מפני שסבר שהלכה כסתם (יש לדון שגמרא בב"ק אומר שאין הלכה כסתם יחידאה. וצריך להגדיר אותו גמרא, שלכאורה מצינו שפוסקים כן.), ואז סבר שכשתנא סתם משמע שס"ל כן.
* כח.
** ר"ש כמאן -
קצת קשה למה לא אמר שר"ש מחדש הפסק. (וכמובן, יש לומר שהיה לו לפסק, אבל עיין רש"י ב"ק (יח.)). ועיין גירסת רש"י כאן ופירושו. ועדיין צריך ביאור למה לא כתב גמרא כגירסא שלנו (שלמה שגרס, הניח גמרא שר,ש מבאר מה אמרו, ודן על זה ואמר, “אב"ה . . . .”)
* כח:
** משום מצוה -
צריך ביאור מה לנו בזה. ויש לומר שזיקה יותר חלוש אם לא עתיד לייבם. ותחשב.
** תרוויהו מוכחי -
לא הבנתי, שכן הוא אם חד אסור בשניהם, שזה גם כן הוכחה. ותחשב.
* כט.
** מגמר -
מרש"י משמע שזה ו"קלא" הוא חד דבר. הומ"ל ששני דברים הם (ואולי צריך רק חד; ואולי צריך שניהם), וחד אמר שדינה ידוע וחד אמר שמצבה ידוע.
** מאמר -
קשה, שאכתי ידחה מצות יבומין. וצריך לומר כצד שיש זיקה.
** דחזיא -
נראה שזה קצת חלוק מתירוץ ראשון, שזה תולהו בהיתר לייבם, וזה בכמה אופנים יכול להתירה. ותחשב. (ותחשב למה כאן צריך לתירוץ זה ולעיל צריך לאותו תירוץ. ואולי אין צורך, וזה פרט אחר שנשנה. ודחוק. ותחשב.)
** צריך ביאור איך רבנן
יתקנו זיקה להפר נדריה (ואף רש"י המעורר שדרבנן הוא רק מעורר שחלוש הוא, ולא מעורר נקודה זה.) ואולי זיקה דרבנן עושה יחס. ותחשב.
** ת"ש -
קשה, שגמרא כבר חזר מלשאול גבי הפרה (ואז שקו"ט של גמרא מוזר).
* ל.
** ואיידי -
אמר ר.מ.ש. צד שמחלקת ואחר כך סתם הוא שרבי סבר כסתם ושוב חזר בו להסתפק בו. (ועיין בתוס’ ב"ב (קכב:)) גם קשה מגמרא כאן, שלאורה, מחלקת, אז, מחודש. ויש לדון. ותחשב. ונראה שני דיחויים:
א. אין מחלקת יותר מחו’. ואולי כאן רק נחשב יותר פשוט מפני שידוע מסברה. פשיטות כחד מאן דאמר- שזהו סתם- אינו יותר פשוט.
ב. מחלקת לא היה יותר חביב לתנא.
* לא.
** ומדעי -
זה קצת קשה לאב"ש, שסבר שחליצה קודמת, שאם כן אי אפשר לדייק ממה שחלצה. אם כן, אפשר להוקים משנתינו כאב"ש (ובפרט כיון שכבר סתם כמותו, ואז מסתבר שכן סבר). ונראה אולי שאין מבינים בני אדם ממה שחולץ, אלא שיודעים הדים שאסור לייבם (ואף שמניחים שלא יודעים דין גירושים).
** דקיימא ערוה -
זה, לכאורה, לא שייך; החילוק הוא אי יכול להיות שרבנן הכריעו עליו. ותחשב.
* לא:
** ואי זיקת -
ק"ק לל"א שהוא דאוריי’, אלא שאין מאמר קונה מדאורייתא. ויש לדון אי יש ציור, אז,שיהא אשת שני מתים מדאורייתא. (ואולי נמצא בקדושי חוץ, לצד שחל.)
** שנאמר -
למס’ הגמרא, צריך ביאור למה מביאים קרא זה.
* לב:
** מוסיף -
יש להעיר שלגבה אינו איסור מוסיף (שלא נאסר ביותר). אם כן, נמצא שרק לו יהא איסור. ויש לדון, שאולי נוכל לפרש שמוסיף ר"ל שנוסף איסור על חפצא, והיא נחשבת חפצא כיון שאינה כל כך העושה.
** כאילו עשה ב’ -
לשון זה משמע שרק עשה חד, דאי לאו הכי, היה לו לומר שעשה שנים; אלא שאז קשה מקום קבורתו. גם לשון "לא חייב,” ולא "לא עשה," משמע להיפך.
** רח"א -
היה מצי לפרש במחלקת שחולקים אי היתירים אלו הם לכל או רק לציור שיש בו צורך, אבל גמרא לקמן לא יפרש כן. ותו"ת.
* לג.
** דאייתי -
אז, חל ס"ר כבר (עיין בסנהדרין (נה:) שמשמע שיש ס"ר לקטן, ועוד שכבר יש אותו שם של חפץ הרע (באיסורים שיש בהם חפץ). ויש לדון, שאולי לנגד אותו קטן אין לו אותו שם.) אלא שאין כבר איסור לקטן. זה, לכאורה, שייך לסוגיא.
* לג:
** לאוי -
יש לדון מהו החילוק בין לאווים לאיסורים:
א. לאו ר"ל מלקות; איסור הוא ביטול ציווי.
ב. לאו הוא ציווי; איסור הוא ס"ר. אם כן, באיסור שלא חל על איסור, אין ס"ר. (זה לא נ’ ממה שכתבנו לעיל ד"ה דאייתי).
** מידי -
יש לדון מהיכי תיתי שלא דן ברשיעי. יש לומר שהוא מפני שמחייב חטאת, ולא נחשב מומר. חושב אני שבמקום אחר דנינו על כעין זה.
** פיתוי קטנה -
ק’ דאף בלי זה, אין ציווי לקטנה (ואולי כן ר"ל). נמצא, לכאורה, שיש איסור בלי ציווי (ובוודאי כן הוא באשת כהן, שאי אפשר להיות ציווי לאונס.).
** ואי במזיד -
זה רק מוכיח שנשים אינם מזידות, ועדיין יש לומר שהחליפו קאי על האנשים.
* לד.
** ר"מ -
קצת קשה מהיכי תיתי שכן סבר ר"מ; דלמא רק לאחר חלות כל האיסורים נעשה גדול. ותחשב.
** בשופעות -
מעניין מה שאי אפשר לאוקמיה בנעשות נדות בעת קבלת קידושין, שאף שבדרך כלל אי אפשר לצמצם, מסתבר שיפרסו נדה אז (כמו שאמר גמרא שפורסת מחמת תאווה). יש לומר שזה רק חשש, אבל לא מסתבר שיקרה או שיקרה ממש אז. עוד יש לומר שכאן, ששולחת שליח, לכאורה אינה שם בעת קבלה (ועוד שכבר יודעת שתשא, ולא מתאווה כל כך).
** ולטעמיך -
היה אפשר לדחות שאינו ר"א.
** במה שיום הכיפורים ושבת
ה"ה בב"א, יש לדון אי זה מוכרח, שיש לומר שקיבל תוספת חד לפני חבירו. ויש לדון אי בקבלת אחד, יבא חבירו (ועיין בחקירות שחקרנו בסוף פסחים).
* לד:
** שלא כדרדה -
אי בעלו שלא כדרכה, קשה למה הוצרכו לזרות מבחוץ, שבין כך ובין כך לא תוליד.
* לה.
** כהוראת -
צריך לחשוב מהו הדמיון.
* לה:
** אינה צריכה . . . מיבעי ליה -
יש לדון מה רוצה לומר:
א. ימנה אף זה (שמנה כל הנפק"מ).
ב. ימנה את זה כיון שהוא מחודש יותר (כיון שהוא לקולא).
** בביאה -
צריך לחשוב איך נחלק (על פי סברה שכתב גמרא לעיל). ותחשב.
* לו:
** יוציא בגט -
כיון שהלכה כר"ל, צ"ל שכנסה קודם, שלא ייבמה.
** יוציא -
וא"ת יחזירה מיד. ויש לומר שלא תרצה. (אכתי ק"ק בדר"מ, שכבר הסכימה פעם אחת. ואולי אף גוזרים שלא יחזירנה.)
** דקפגע -
מחלק בין ספק דאו’ (שיש אומרים שהוא לחומרא רק מדרבנן) ודרבנן. ודע שמצינו (ביצה ?[fn:2]) שאי יש חשש דאורייתא, יותר חמור.
* לז.
** באורתא -
הו"מ לפרש הא דר"ח וב"ק לעיל על ידי זה, אלא שמה שנשבע לא משמע כן. ויש לדון.
** הו"מ -
ק"ק לל"א "תסתיים דרפרם.”
** אליבא דהלכה -
נמצא שהלכה כראב"י אף בברייתא.
* לט.
** אשה הק’ -
תחשב על זה (משמע שמעשי קדושין גורם חיוב, ולא היות קנוי לה.) ותו"ת.
** לענין -
נראה לפרש שאולי חולקין אי על ידי זה מקיים שום ק"ש (עיין בשיעור ר.מ.ש.)אם אפשר שיש יותר ענין בבזיון של מי שיותר היה יכול לקיים שם.
* מ.
** אב"ש -
קצת קשה ל"ל אוקמיה במה שא"א לאכלו של"ש למד"א שמצות א"צ כוונה. ונראה שזה אינו צריך קרא.
** הואיל -
באמת, שליח הוא, ומעשיו מיוחס לכלם, אלא שלמעשה, הוא בחר בו, ותחשב. ודע שאם כן, אין סיבה זה קיים אי כפוהו בית דין. ואולי אכתי יותר נחשב מעשה שלו. ותחשב.
** מידי יבום -
עיין לעין שאמר שייבום בנחלה תלה רחמנא.
** ולמאי דאפכת -
ק’, שאי סבר שהלכה כרבנן, שפיר יסמה ברייתא. ונראה שר"ל שאין בעיא לפסוק כר"י, ויש בעיא רק לפסוק פסק הפשוט. נמצא, אז, שיכול להיות שמסתבר כר"י, אבל לא מסתבר עד כדי שצריכים פסק נגדו, אבל לא כל כך שהלכה כר"י. ותו"ת.
* מב.
** מן השמים -
יש להקשות מגמרא נדה שאומר שתשמיש טוב לולד. ועיין שם (לא.), שאין זה בכל זמן.
* מב:
** שמעתי מפי -
יש להעיר שהיה ר"י מיושבי יבנה (עיין בשבת לג:). ואולי חולק וסובר שלא אמר כן ר"י. גם יש לומר שכיוון ליבנה הראשון (שהיו שן שני פעמים (עיין בר"ה.)).
** סתם -
קשה:
א. הוה סתם יחידאה (בב"ק אומר שאין הלכה כסתם יחידאה).
ב. סתם ואחר כך מחלקת הוא רבים, והוה רבים נגד ר"י, וכבר אמר גמרא שהלכה כר"י רק כיון שחולק על יחיד. אמר א.ר. שאולי חזר גמרא מזה. ודחוק. גם אמר שאולי זה רק ראיה שהוא רבים (ולא שנותן לו כח רבים), וכבר רואים שאינו רבים. יש לדון אם זה, אז, ידחה את הכלל (ואז, יוכרח דלא כמו שאמר). גם יש לדון אי מניחים שרק ר"מ הוא רק כיון שאין סיבה להניח עוד תנאים ( אבל כאן יש סיבה). ותו"ת.
* מד.
** עצה טובה קא משמע לן -
לכאורה, לא רק ר"ל שמשנה אומר עצה טובה, אלא משנה אומר שכך אומרים לו, שאומרים לו עצה טובה.
* מו.
** מעשר -
מה שלא הוה מעשר לכאורה אינו שלא מצווה, שאבות, ואולי אף משה קבלו כל התורה כולה, אלא:
א. אז, לא היה חוב, ואז, היה יכול. יש לדון למה יתלה בחוב. שוב ראיתי שמרש"י פסחים (ע.) משמע שתלוי בחוב. וע"ש.
ב. לא היה פירות מא"י. יש לדון, שאולי יחייב מדרבנן.
ואולי מזה ראיה שמניח גמרא שלא קיים משה את כל התורה כולה.
גם יש לומר שלא הקריבו משל מעשר לסיבה אחרת, והוא שלא היה מותר כיון שלא היו בירושלים.
* מז.
** ואין עדות -
צריך לומר שבועל גרושה יכול להעיד.
** עכו"ם -
יש לדון אי אומר שגר (ומסתמא לא נאמן. ויש לדון, שכאן הוחזק).
** מצות -
נמצא שקורא עבירות בשם "מצות.”
* מז:
** ציצין המעכבים -
זה פשוט, שלכן נקראו "מעכבים.” ויש לדון, שאולי ר"ל שאי נשתייר ממעכבים במלת בן, צריך לחזור.
** עבודת -
ואם תאמר אף לגוי אסורה. יש לומר שמודיע שאף לישראל אסור (שהוה אמינא שכיון שאומר קולת לקט ושכחה יקיל ביותר). כעין זה שמעתי, חושב אני, מאבי, ואינני זוכרו. עוד יש לומר שכבר התיר ה’ שבע מצות. ויש לדון מתי התירו.
** תרי"ג -
כמובן, אין כולם שייכים לה.
** שהוי מצוה -
לכאורה, אין מצוה להיות גר (ואף שכתיב "אשר באת" (מח:), לכאורה, זה רק הכשר מצוה), ורואים שיש ענין שה"מ גבי הכשר מצוה (או מחמת ההכשר או מחמת המצוה).
** דאי הדר -
קצת קשה למה לא אמר נפק"מ שחייב בכל המצות.
* מח:
** ע"ז -
ק"ק, אז, למה לא מזכיר אם כלל.
** שלא קיימו -
ק"ק מגמרא ב"ק (לח.). ואולי נענשים מחמת ס"ר. ותו"ת.
* נ:
** יש לדון באיסור חלוצה
או כדומה, אי נחשב איסור קורבה. ותחשב.
** חליצה להוציאה -
ואם תאמר אם כן לא מצינו שמוציא. ויש לדון, שכו"ע מודי שמותרת לחוץ, ודנים רק בהיתרה ליבם.
** כל כי הני -
ק"ק לל"א שאם תחלוץ תייבם. אולי זה רק אי חייבת לחלוץ.
* נב:
** מצות יבמה -
עיין במשנה, שרש"י מפרש דלא כר"ה. ק"ק למה.
** על הנייר -
יש לדון אם כותב, “ה"א מקודשת" או "מאמרת.”
** אמר אביי -
יש לדון אם ביאור מה נכ’ היה מפורש בבריי’. אי לא מפורש, פלא הוא איך ישאל ברייתא כיצד, ולא יתרץ. אי לא, ק"ק למה לא הק’ גמרא שלא כן כות’ שטר קדושין (וממה שלא הביאו גמרא בקו’ נ’ שרק מקשה איך כותבים). ואולי הק’ קושיא הראשונה (שבא רק משאלה).
** ואישה -
יש לדון אם זה סיבה לגזור (שיותר דומים בדין) או סימן שיש שום דמיון (או שיש לזה קצת חלות גט או שתורה גזרה).
* נב:
** מאמר -
הוה מצי לומר צד שגירושין מונע סיבה לחלות ושסיבה ה"ה מעשה. אם כן, היה אפשר לומר שמונע סיבה לעילוי זיקה. ממה שלא אמר גמרא צד כזה, רואים נגד מש"כ (ויל"ד איזה הנחה נדחה).
** נכסי הגר אחר -
יש לחלק ששפ אופני קנין לא חלוקים. (ותחשב.)
** רבא אמר -
נראה שהוא לשיטתו בריש העמוד.
* נג.
** תני . . . תנא דידן -
נראה מזה ש"תני" לא מוסיף מילים על המשנה. צריך ביאור מה עושה ולמה נצרך כאן.
* נד.
** שניהם אנוסים -
היה אפשר לומר ששניהם חשבו שהאחר הוא אדם אחר. יש לדון, שאין אחר המותרת לאשה חוץ מיבם (ואולי מכוונת לאיש אחר), ואז לא מסתבר שתטעה ותבעל.
* נד:
** ולאו -
קשה; אם אינה במצות ייבום, למה נניח היתר איסורה של אש"א. ותח’. ושו"ר בתוס’.
** מיתת ב"ד -
לכאורה, היה לו להקשות שיאמר כן גבי בהמה עצמה.
** קורבי עצמו -
קשה, שלכאורה יחסו לאחותו הוא מה שבאים מהורים שווים, וזה לכאורה יחס להורים. ונראה, אולי, שאין הענין שמיוחס לה כיון שמיוחס להוריה, אלא שמיוחס לה מפני דמיונם (ששניהם מיוחסים להורים באותו דרך). ותחשב. ועיין בשי"ח ש"י בריש יש נוחלים.
** שכן ודאית -
יש להעיר שבין כך תאסר (דאי אינו אביו, הוה ממזר).
** שכן -
נמצא קצת מעניין, שהוה מצי למימר שתורה אוסר ודאי, אלא שזה לא נמצא, וממילא כל ציור נאסר מחמת חזקה. ותחשב. (מדלא כתב כן, רואים שמניח גמרא, לאיזה סיבה, שהאיסור ה"ה ממש אותו ציור שיש הו רב.) (ואולי רק אוסר ציור שלא הותר) (ואולי רק ר"ל שלא יאסרנוו קרא כיון שבדרך כלל רק חזקתו יאסר. ותח’.)
* נט:
** נ’ שתירוץ הגמרא
למסקנא הוא שר"ל "ראיה . . .” ואז פשוט מקרא שאשה ל"ד, שכל אשה ראויה, ואז יכול להיות קאי אף על טף.
** פנחס -
מניח שכבר היה כהן (עיין בסוף זבחים).
* סא.
** נפש אדם -
יש לדון מהו תירוץ גמרא:
א. כאן, מסמיכה לבהמה, יש משמעות אחר לו, וכאילו היה מילה אחרת.
ב. יש אותו משמעות רע,אלא שיש צורך להשתמש, אף על פי כן, עם מילה זה.
** ומה ישראל -
ק’; דלמא רק הנשים הצריכו, שמא יטמאו בעת מתן תורה (אבל איש יכול לטבול (ותורה נתנה לטבול יום)).
** מ"ט -
ק"ק, שדלמא זה מפני שצ’ שני זכרים.
** מ"ט דב"ה -
נמצא שלולי קרא הוה אמינא שאין בו שיעור, וחייב לעולם. נ’ שזה יתרץ מה שהק’ בד"ה מ"ט.
* סב:
** וכמה -
יש לדון אי זה קאי על הזמן שאסור ביוצא לדרך או הזמן שמותר באשה רגילה. ותו"ת.
** עיסקא -
עיין בקידושין
(ל:). ותחשב. ויש לדון.
** גלימא -
נראה שלכן מכנים, “אפילו גלימא [משעובד].”
* סג:
** גלה -
משמע קצת שהחידוש הוא שתגלה כלל (מדלא אמר "לא תגלה אלא ").
* סד.
** ללמדך -
לשון זה מוזר על דבר שאיננו ראיה אלא זכר.
* סד:
** טומטום -
קצת מעניין, אז, מה שרצה פרעה לבועלה. וצריך לומר שלא ידע עד שהוכה. ותחשב.
** כיון דלא -
* Footnotes
[fn:1] מסתמא, היה כוונתי שאולי יש לברר מכאן אם היה קודם בת קול או לא.
[fn:2] עדיין חושב אני שיש מקור שם, אבל מצאתי מקור אחר בעירובין (לו.).
