** פרק חמש עשרה נשים
* ב.
** חמותו -
וא”ת אפשר אם נושא בת אחיו (ואז א”צ מיתת בעל). וי”ל שוז צ’ מתת אשתו. (יש לדון אם זה מהני, שאכתי אולי סימפ”ל, שיש בו רק מיתה, ולא מיתה ונשואים.) עוי”ל שלא אמרו מפני שכיון שמתה אשתו, מח’ הוא לקמן אי יש איסור חמותו.
* ג.
** ותני -
יש לדון אם יכולים לדייק מכאן שאין הענין רק שאינו כ”כ קורבה, אלא שאין האיסור מחמת קורבה, אלא שמי שנתקדש לבנו (ויש באותו יחס יותר מקורבה) נאסר לו. (אולי הוא דומה למש”כ על גמ’ גלגל ראישון (ב.- ד”ה צרות).)
* ד.
** לסקילה -
אין צריכין מה שהוא חמור מכלם (שהוא מח’), אל מה שהוא חמור מחנק, שכן היה חייב לולי קרא (ובזה, אין מח’).
* ט.
** והאמר -
מדרשת עליה- זה מח’. צריך ביאור למה כתבו רש"י, שאינו, לכאו’, נצרך, ואז למה יביא דבר שלא מוסכם בלי צורך.ותו"ת.
* יב.
** כדמפרש -
כ’ כן גם כן כאן. ואולי שם מפרש יותר.
* יב:
** ואפי
’- הרצה- ע’ בנדה (נב.). וצ"ב.
* טו.
** ’ טרפון
ר
- זה מראה מקום.
** יש -
מעניין מה שאומר רש"י שתנאי עושה מקח טעות. משמע שענין מקח טעות הוא אומדנא, שאז, מקח אעות הוא תנאי. (אלא שאז מעניין שרש"י אומר שהוא מקח טעות, שאז אין מקח טעות אלא תנאי, ולא מוסיף שום ביאור. ותו"ת.) לצד אחר של מק"ט, שלא חל כיון שדעתו מיוסד בטעות, נצטרך לומר לרש"י שאף בתנאי יש חסרון דעת, שתולה דעתו על דבר, יש לדון (שמצינו כמה תנאים שלא כל כך מסתבר שיתלה דעתו בהם. וצ’ לחשוב, שרצונו הוא שיהא חלות תלוי).
* טו:
** היא -
זה אצלו מיעיקרא- צריך ביאור למה אומר כן גבי יבמה לשוק. ותח’.
* טז:
** עיין במש"כ
שהיה ר"ט מתלמידי בית שמאי. יש לציין לגמרא ברכות (י:) שסיכן בעצמו כבית שמאי. ויש לדון למה אין מביאים מזה ראיה שעשו.
** קביעי -
מעניין שזה נחשב קבוע, שעדיין בדרך כלל, איש נותן קידושין.
* יח.
** הא מני (תוס’) -
משמע שסבר שהלכה כסצן משנה. ויש לדון. יש להעיר שכתב שי"ח ש"י שמראה ששמואל  בהר שהלכה כסתן משנה. (עיין, חושב אני, בב"מ סו"פ שביעי). ועיין בתחלת פרק שני בפסחים ובשי"ח ש"י שם בענין שיטת רב.
* יט:
** קדושין -
מעניין מה שלא נדע ממה שהוא קנין, וכל קניינים צריך דעת מקנה. (אולי הוה אמינא שאף שמסתבר כן, ממה שאין צריכים דעת בייבום או בגירושין משמע נגד זה) אולי יש לומר ש(הוה אמינא ש)אינו קנין. גם יש לומר שיש גם כן יחס בעלות. אולי מה שיש לו אותו יחס עושה שיותר קל לקנותה. ותחשב.
* כא.
** ואשת -
קצת קשה למה בחר שמות שאינם נכונים. ותחשב.
* כב.
** השתא -
נזכר וגלוי- צריך לחשוב על זה. ועיין ברש"י שם בחגיגה ובשי"ח ש"י.
* כד:
** בזה"ז -
קצת קשה למה לא מנה את יתרו. ואולי נתגייר קודם מתן תורה, ואולי זה חלוק. ובאמת קצת צריך ביאור למה לא היה מדבר כימי שלמה. ואולי רק בני ישראל הכירו בנסים שקרו. גם יש לדון אי באמת נתגייר יתרו.
* כו.
** בתרי -
מעניין:
א. שיש חזקה בגירושין (שדן גמרא מה גורם שתמית. צריך ביאור איך תגרום גירושין.)
ב. שיש איסור לישא אשה שתתגרש.
אפשר לתרץ שניהם כאחד לומר שהדרך המיוחד שתגרום אותם הוא על ידי זכות. לכן, אין לישא אותה, שחוששים שתזנה. ותחשב.
* ל.
** דאידחיא -
נראה שיותר מסתבר שזה יהני אי זיקה הוא יחס לבעל הטוען ייבום. ותחשב.
* לד.
** ור"מ -
כמאן מרבותיו- מעניין מה שקורא לר"א ור"י רבותיו, שהרי ר"ע תלמידיהם היה רבו.
* לו.
** בשלמא -
צריך ביאור למה רש"י מבאר את כל זה כאן כיון שכבר היה שייך לעיל (לד: ולה.).
** לא אמר -
שהתנה- מעניין שאף צריך זה, שהוה אמינא שאין בידו לירש (שהוא חלות החל ממילא כיון שאין נכסים נקנים כל כך לו), ואם כן, אין לו כח להתנות.
(ואגב יש להזכיר שמה שאומרים בני אדם צד שירושה הוא קנין האב הממשיך לבן. אולי ר"ל שממשיך קנין אב, אלא שעושה דיני קנין לבן. גם אפשר שהוא שמה שקונה אינו מפני שמיוחס לחפץ כיון שמיוחס לאביו, אלא שיש לו שם שהוא מאד דומה לשם אביו, ומפני שיש סיבה לאותו יחס של אב, ממילא חל עליו, כיון ששמו שווה. ותו"ת.)
* לז.
** כותי -
קצת קשה אז למה נניח שקידשה אחד בכסף. ואולי ישראל קדשה. ויש לדון.
** אלא -
עיין במה שכתב. רשהשזה יפרש למה לא הקשה אבי ימיניה.
* מא:
** לימא -
עיין במה שכתב. וחושב אני שיש צד גם כן שמק’ שידוע היו משניות.
* מב:
** מתני’ -
קשה, שלא נשנית שם, אלא נשנה מה אמרו. ותו"ת.
* מו:
** דילמא -
מדמוסיף- משמע שהוא מפני שחולק בו. ויש לדון, שמצינו בכ"מ שחולקים בשמות כשאין נפקא מינא. ולולי רש"י היה אפשר לומר שאי צריך שנים, מה שאין כן אי צריך רק הדיוטות, אכתי צריך שלש, ואותם שלש ישארו.
* מח.
** רגלו -
עיין לקמן (קג. וברש"י שם) שלכאורה מבואר נגד זה.
* מט:
** נסתכלו -
לולי רש"י היה אפשר לומר שאם אדם לא רואה ה’ כל כך, יכול לראותו, ואם רואיהו בבהירות, כמשה, רק אז אי אפשר.
** משנת -
ברייתא- יש שגורסים כן ויש שלא גורסים כן. עיין במק"א (וכן בכ"מ) שמוכרח שזה אף בברייתא. ואפשר שרש"י קאי רק על מה שהוא קב. ותחשב.
* נ:
** ואי -
אשת אח- עיין לעיל שחולקים אם היא אשת אח. ותחשב.
* נב.
** והתניא -
קלות ראש בעצמו- צריך לחשוב על לשון זה.
** נתן -
אין קדושין תופסים באשת אח- משמע שאינה הותרה[fn:1]. יש לדחות שאיין אי-תפיסה תלוי בס"ר, אלא בדבר אחר.
* נו:
** ותנא -
עיין במה שפירש. שם יכו"ל ש"נא" נעשה "נו,” ו"אבונא" נעשה "אבינו.” כאן צריך ביאור מה ר,ל- “תנו"? ונ’ שר"ל תננו- דהיינו, תנא שלנו- וקצר שני הנונים לאחד.
* נז.
** למאן -
ואית- לא הבנתי למה לפירוש זה יהא מוכרח ש"למאן" האמר לע ר"א. יש לומר שחציו נאמר (ע’ ראב"י.)
* נז:
** יש -
כשלא נתקדש- עיין לקמן, שמביא לראיה ציורים שלא נתקדשו.
** ומודה -
גם יש לומר שהוא מפני שהיה תלמיד חכם (ו"אבא" הוא לשן חשיבות) יותר ממנו (עיין ב"ק (פ:?).
** ובגרה -
משמע שיש מצוה בזה, ולא רק לאו הבא מכלל עשה (דנו ראשונים בזה).
* נט:
** רבי -
וכיון שנולד ביום מיתת ר"ע, ור"ע למד לשמונים שנה, ומדלא למד מריב"ז, משמע שכבר היה מת. אם כן, אי אפשר שכהן גדול היה עדיין חי. ותו"ת.
** פניה -
נ’ שבא לאפוקי מהא דיין, דאינו נס.
* סא:
** ב"ש -
העיר ש.ל. שר"ל שלא מוסיף על ב"ה (וכן נ’ מהא דראיתו).
* סב:
** שמם -
שנשתכח- יש להעיר שלכאורה הענין הוא שהיו כל ת"ח מתים, ולא שכחוותחשב. וצ"ל שכלל של ישראל ידעו ושוב לא ידעו, וזה נקרא "שכחה.”
* Footnotes
[fn:1] שוב אמר לי א.ר. שאמר ר.ד.ו. (כן אני חושב) ראיה זה.
