1. משנה א:
א.
נראה שזהו קושיית גמרא. אבל, לא מוכרח כן, שאפשר לפרש שקושיית גמ’ הוא למה שואל על הזמן קודם שאומר שיש זמן. אבל, אולי מניח שיודעים את הפסוק שאומר שצריך לקרוא קריאת שמע. ויש לדון.
ב.
גמרא אומר שממשיך מן הפסוק. לכאו’, רק רצה לומר שמניח שהפסוק ידוע, ואז כשבא לומר הדין, ממשיך מן הפסוק. אבל, אפשר לומר שהכוונה הוא שהתנא, כששנה משנה זה, גם שנה עמו הפסוק, והמשנה נאמר כהמשך מן הפסוק. אף שרבי לא קבע את הפסוק לחלק מן המשנה, כיון שהוא כבר ידוע, עדיין המשיך ממנו. ותחשב.
ג.
אגב, עיין לקמן (כא.), שיש מי שסובר שחיוב קריאת שמע הוא מדרבנן. לפי זה, קשה איך ידוע ק"ק ממה ממשיך לפי מד“א שחיוב ק"ש הוא מדרבנן (כא.).
ד.
יש הרבה זמנים שנמנים במשנה ובבריי’. כולם מניחים (ולא כל כך פשוט לי למה מניחים כן) שזמן שכיבה אינו זמן שכיבה של הקורא, אלא של בני אדם. גם יש להעיר שאפשר שלא חולקים בביאור הקרא, אלא שאולי זה בכלל “שיעורים,” ויש הלכה למשה מסיני בזה, וחולקים במהו ההל”מ. ותחשב.
ה.
וא”ת למה של שחרית יקדים. ויש לומר שהוא כדי שיהיה כמשניות לקמן, שבו שחרית קודם. אבל, צריך ביאור למה הוא כן שם. אז, מסתמא מה שנתרץ לזה גם יתרץ לכאן. אפשר שהוא מפני שבדעת בני אדם בוקר בא קודם לילה, שבני אדם חושבים על תחילת יום כזמן שהם קמים. גם אפשר שהוא מפני שלילה הוא זמן קצת גרוע (עיין בגמ’ לקמן שאומר שלא לומר לשון לילה וחושך, כיון שאינו לשון מעולה), ואז לא מסתבר להתחיל בו. ותחשב.
ו.
אבל, גמרא לא מבאר למה הפסוק התחיל בלילה ראשון. אם, באמת, היתה סיבה טובה להקדים של יום, קצת קשה למה פסוק לא הקדים אותו.
ז.
גמ’ אומר שהולך על הפסוק, ולכן הקדים ערבית כמותו. לכאו’, לא צריך לכך מה שהולך על פסוק, אלא שהמקור שלו הוא פסוק. במילים אחרים, לא צריך חיודש נוסף שאומר גמ’ שממשיך מן הפסוק, אלא רק צריך שמצאנו כן במקום אחר, ולאיזה סיבה שנקט כן שם, גם נקט אותו כאן. אז, יכול להיות סימן, ולא סיבה. ותחשב.
ח.
גם כאן, יש לדון אם זה סימן או סיבה. הצד שהוא סימן הוא שממה שהקדים הקב"ה את לילה בבריאת העולם, רואים איזה חשיבות שיש בו. מחמת אותו חשיבות, הקדים אותו התנא. הצד שהוא סיבה הוא שכיון שהוא נברא ראשון, הקדים אותו התנא. אפשר שזה מפני חשיבות של מה שנברא ראשון, ואפשר שהוא מפני שזה מוכיח שהוא הראשון. ותחשב.
ט.
גמ’ מזכיר קרא (גבי בנין ביה“מ השני) שהוא זכר לדבר. (עיין ברש"י ותוס', שחולקים אם הוא זכר שזמן קריאת שמע מתחלת בצאה"כ או שלילה מתחלת בצאה"כ.)
בביאור צאת הכוכבים, בירושלמי, מזכיר שלש שיעורים של מנין כוכבים. יש מי שאומר שרק צריכים שני כוכבים, ויש צד שצריך שלש כוכבים, ויש שיטה שצריך ארבע כוכבים.
י.
לכאו’, היה לו לומר "צאת הכוכבים" כיון שזה זמן היותר ידוע. יותר ידוע כיון שהוא נוגע בכמה וכמה מקומות, ויותר ידוע כיון שהוא תלוי בדבר הנראה (שבנ"א יכולים לראות את הכוכבים). ותו"ת.
יא.
רבי מאיר אומר שהזמן הוא זמן טבילת כוהנים. מקשה גמרא שזה עדיין יום, ומתרץ שסובר כבין השמשות של רבי יוסי. אבאר:
1. חולקים תנאים מהו בין השמשות. רבי יהודה סובר שבין השמשות הוא כמהלך חצי מיל. רבי יוסי סובר שבין השמשות הוא כהרף עין.
2. רבי מאיר סובר כרבי יוסי, ואז כהנים טובלים בזמן הקרוב לצאת. אז, שפיר יכול לקרוא קריאת שמע אז.
צריכים לדון, אז, מתי זמן זה לנגד שאר שיטות. ראשון, יש לדון אם רבי יוסי סובר שצאת הוא בזמן שווה שסובר רבי יהודה. (חושב אני שגמ' דן בזה (אולי בנדה), אבל לא ידוע לי.)
נניח כאן שהוא אותו צאת הכוכבים כדי להקל את החשבון. אם כן, נמצא שזה צריך להיות קודם 3. גם צריך להיות קודם 2, שצריכים הערב שמש קודם זמן הספק. אם כן, יהיה קודם 2. יש לדון, שאם מי שאומר 2 לא סובר כרבי יוסי, אפשר להיות ש2 יקדים לשיטת רבי מאיר, שאף שאינו זמן קודם ביום (ר"ל, ששל רבי מאיר יום ושל 2 בין השמשות), אולי בא קודם.
יב.
משנה משמע שרבי אליעזר סובר כ3. מקשה גמרא שיש סתירה, אז, בדברי רבי אליעזר. מתרץ שני תירוצים:
1. חולקים תאנים בשיטת רבי אליעזר.
2. משנה לא אומר שרבי אליעזר סובר כ3 (רבי אליעזר במשנה רק הולך על סוף זמנו).
יג.
ירושלמי
(א, א)
אומר שזה קרוב לצאת הכוכבים, ומבאר שזה זמן שאוכלים בכפרים קטנים (שהוא קרוב לצאת הכוכבים, כיון שיש להם זמן להכין מבעוד יום).
יד.
בירושלמי (א, א) מזכיר זמנים אחרים של תחילת לילה. יש לדון אם זמנים אלו יהיו נוגעים לתחילת זמן ק“ש של לילה.
טו.
חולקים רבי ורבי נתן (ג:) כמה משמרות יש בלילה, שרבי סובר שיש ארבע משמרות בלילה, ורבי נתן סובר שיש שלש משמרות בלילה. לכאו’, אין מחלקת רבי ורבי נתן נוגע לזמן קריאת שמע, שלא נראה שחולקים אליבא דרבי אליעזר, אלא חולקים אליבא דאמת. וא"ת אם כן מאי נפקא מינא. באמת, אף אם חולקים אליבא דר"א יש להקשות כן, שלא מסתבר שיפסקו כרבי אליעזר. אז, נראה שאולי חולקים רק במציאות, או בפירוש הפסוקים. גי"ל שנוגע להנהגת אדם, כי בין האשמורות הוא עת רצון לתפילה על ביה"מ, כמו שנראה מן הגמרא. ותחשב.
טז.
ירושלמי (א, א) מבאר (בגזרה שיאכל הנאכלים ליום אחד קודם חצות) שלפעמים לא יבין שכבר בא הבקר, ויבוא לאחר אותו. אז, תקנו שיעשה אותו אף קודם חצות. לכאו’, הירושלמי יאמר כן גם בק"ש. אבל, הבבלי אומר הטעם שהזכרנו (שמא ילך לישון, וימשך לישון עד הבוקר). ותחשב.
יז.
מצאנו במשנה שלש שיטות. אבל, באמת, אינו שלש שיטות, אלא שני מחלוקות. מחלקת ראשונה היא זמן קריאת שמע מדאו’, ומחלקת שנית היא אם גזרו בו רבנן. אז, יש לדון מה סובר שיטה חמישית שנביא, אם סובר שגזרו רבנן (והוא אומר זמן מדאו’, שבא יכול לקרוא קריאת שמע בדיעבד) או שסובר שלא גזרו רבנן (והוא אומר זמן אפילו מדרבנן, שיכול לקרוא עד אז לכתחילה). אף אם לא סובר שגזרו רבנן שיקרא קודם חצות, אפשר שעדיין יגזרו לקרוא קודם עלות השחר, שהוא סוף לילה. ותחשב.
באמת, אף אפשר שרבן גמליאל סובר מדאו’ כשיטה חמישית, ורק חולקים אם גזרו רבנן שיקרא קודם עלות השחר. אבל, לשון המשנה לא משמע כן, שאילו אף ר"ג הודה שגזרו רבנן, היה לו  להזכיר את זה כשהזכיר שרבנן סוברים שגזר. ותחשב.
יח.
לכאו’, זה מוקדם משיטת רבי אליעזר. אין לי הוכחה, אבל כן נראה מן הסברה, שלא נראה שעני ממשיך בסעודה שלו לארבע שעות.
יט.
נמצא שיש ארבע שיטות מדאו’ בזמן קריאת שמע:
1. עד זמן שעני עומד לצאת מסעודתי. רש"י (ב:) באר ש"דריש בשכבך תחלת זמן שכיבה.” יש לדון מהו תחילת זמן שכיבה. נראה שיש שני צדדים:
  1. אולי ר"ל זמן של תחילת שכיבה, שהוא הזמן שבני אדם הולכים לשכוב[fn:1], ולא בזמן שהם שוכבים.
  2. אולי צריך להיות תחילת זמן של שכיבה. אם כן, שכיבה יכול להיות משמע הזמן שהולכים לשכוב או הזמן שהם שוכבים, אבל צריך לקרוא בזמן תחילתו. ק"ק למה נניח כן בקרא, שקרא אומר שצריכים לקרוא בשכבך, ולא בתחילת שכיבתך.
2. עד סוף אשמורה הראשונה. רש"י באר (ט.) ש"לא משמע להו… כל זמן שכיבה, אלא כל זמן שדרך בני אדם להתעסק ילך ולשכב.”[fn:2] זה אומר כצד ראשון שככתנו לעיל בשיטת ראשון, והוא ששכיבה שאומר תורה היא זמן שבני אדם הולכים ועוסקים לשכוב. וא"ת א"כ איך אפשר שראשון ושני חולקים. אפשר ששני סובר כצד שני, ואפשר שחולקים מתי הוא אותו זמן שבנ"א עוסקים לשכוב. (אולי חולקים אחרי איזה בני אדם וכמה בני אדם נגדיר את זה, ואולי חולקים מה נחשב עסק לשכוב.)
יש להעיר שלשון רש"י לא משמע כן כל כך, שכ’ (ב:), “דדריש ובשכבך תחלת זמן שכיבה ובמתניתין תנן….” קצת משמע- ואפשר לדחות- שעל נקודה זה חולק שיטת רבי אליעזר על שיטה ראשונה.
1. עד עלות השחר. רש"י כ’ ש"משמע להו בשכבך כל זמן שכיבה.” לכאו’, זה ר"ל שקוראים קריאת שמע בזמן שבני אדם שוכבים, ולא רק בזמן שבנ"א הולכים לשכוב.[fn:3]
2. עד הנץ החמה. רש"י לא מבאר את זה; לכאו’, סובר כצד שלישי, אלא שחולקים עד מתי בני אדם שוכבים. גם אפשר שכולל כל עסק בשכיבה, כולל תחילת קימה.
כ.
יש להעיר שלא רק שאין מצווה אחרי כן, אלא שגם יש איסור אחרי כן (בהקטרה ובאכילה). אפשר לבאר שההיתר תלוי במצווה, או אפשר שלאיזה סיבה רק מזכיר המצווה (מסתמא מפני שמדבר בקריאת שמע שיש בו מצווה, ולא איסור). ותחשב.
כא.
יש לדון אם זה חלק ממה שאמר להם ר"ג או שמשנה מביא דינים אלו אגב מה שאמר להם רבן גמליאל. (הסיבה שיש לחשוב שהוא השני הוא שאפשר לבאר שחידוש של ר"ג הוא שיגזרו רבנן בדבר שזמנו עד סוף הלילה לומר שצ"ל קודם חצות. לא מצאנו כן בהקטר חלבים, ואז אפשר שלא מסתבר שרבן גמליאל יביא אותו לראיה. אלא, אולי מסתבר שמשנה מביא אותו אגב שדן בדבר שמצוותו כל הלילה. אבל, אינו מוכרח, שאולי חלק מן החידוש של ר"ג הוא שדבר שמצוותו בלילה מצוותו כל הלילה, ואז זה הוכחה טובה. ותחשב. מרש"י נראה כשני. (אבל, אין זה מוכיח שר"ג אמר כן, שעדיין אפשר שהמשנה מביא אותו כיון שהוא הוכחה למש"א ר"ג. ותו"ת.))
כב.
יש לדון למה לא גזרו רבנן בזה. נראה שהוא מפני שכהנים זריזים, ולא יאחרו את זמן ההקטרה. גם אפשר שהוא מפני שהחשש הוא שיישן עד הבוקר. לא יכולים כהנים לישן בעזרה, ולא מסתבר שירצו לצאת ולהכניס עדו מוקדם (שלא פשוט להכניס לעזרה, שצריך לרחוץ ידים ורגלים, וגם שיש סדר גדול בפתיחת השערים). עיין לקמן, שנוסיף עוד טעם.
כג.
ירושלמי (א, א) אומר שיש שגורסים במשנה ”אכילת פסחים,“ ואז המשנה הולך לשיטת ר“ע. גם מבאר שאף אם לא כתוב במשנה, יש לומר שמשנה סובר כר“ע ורק מזכיר דברים שיכולים, אף לרבנן, לקיים אחר חצות. אבל, תקנו רבנן טומאה על פסחים אחר חצות, ואז א“א לקיים אותו אחר כן. לכן, אינו נמנה במשנה.
כד.
רש"י (ב.) מבאר שעבירה זה הוא איסור אכילת נותר, שהוא חיוב כרת. לא הבנתי ל"ל אמר שהוא איסור של ביטול אכילת קדשים, כמו שהוא גבי קריאת שמע (שהוא ביטול עשה). אולי אין חיוב לאכול קדשים, אלא רק מצווה קיומית, ולא היינו גוזרים מחמת זה. אבל, יש חיוב לקרוא קריאת שמע. אף אם יש חיוב לאכול קדשים, אולי אינו בדרגה של חיוב לקרוא קריאת שמע, שאולי קריאת שמע חמור, כיון שיש בו מיסודי אמונה.
נראה שגם אפשר לבאר על פי מה שהבאנו לעיל בהערות מירושלמי. נראה שאפשר לומר שיש יותר חשש בקריאת שמע, שיש לחוש שאדם יישן, ויתלה שיקרא קריאת שמע קודם עלות השחר, כשיקום, ונמצא שלא יקום עד אחרי עלות השחר. אבל, אולי לא מסתבר שאדם ילך לישון על מנת לקום קודם עלות השחר לאכול, שלא רוצים בני אדם לאכול בשר מיד כשקמים. אלא, החשש הוא רק למי שחושב שיש לו זמן, ובאמת הבוקר מגיע, ולא יאכל עד שבא הבוקר. ותחשב.
יש להעיר שזה יכול להיות ביאור למה לא גזרו על הקטרת חלבים ואברים. עיין לעיל.
1. משנה ב:
א.
יש לדון אם כוונת גמרא להקשות שיש לילות שאדם יכול לעשות כן כל הלילה (כמו לילה שיש בו לבנה גדולה והרבה כוכבים), ואז נמצא שאין תחילת זנמן באותו הלילה, או להקשות שידוע שהזמן שבו יכולים לעשות כן הוא מוקדם מאד, ונחשב עדיין לילה, ולא מסתבר שיהיה תחילת זמן קריאת שמע.
ב.
ירושלמי (א, ב) וגמ’ מנחות (מג:), לפי שיטה אחת שם, מבאר שהוא זמן שיכולים להבחין בין תכלת ולבן של ציצית. דורש כן ממש"כ, ”וראיתם אותו.“ סובר שזה קאי על הלבן, ואומר שצריך להכיר אותו מן התכלת הקרוב לו (או שקאי על כל הציצית, ואומר שצריך להכיר את החלקים שבו).
מבבלי בברכות, אין הוכחה שיחלוק, שאומר שצריך לחלק בין "לבן שבה לתכלת שבה.” (באמת, הסתימות (שאומר "בה,” ולא מפרש על איזה דבר קאי) משמע כירושלמי, שהוא דבר שידוע להיות בו לבן ותכלת.) אבל, עיין ברש"י שפי’ (ואחרי דבריו פרשנו בביאורים שלנו) שהוא: “גיזת צמר שצבעה תכלת ויש בה מקומות שלא עלה שם הצבע יפה.” אז, נראה שסובר שבבלי חולק על הירושלמי.[fn:4] אפשר שרש"י סובר שאין חילוק בין ציצית שמקצתו לבן ומקצתו תכלת לגיזת צמר שמקצתו לבן ומקצתו תכלת. אבל, יש לדון.
ג.
מרש“י קצת משמע שהסיבה שאותו זמן מאוחר (שיותר קשה להבחין) הוא מפני שאף הלבן שם קצת צבוע, ורק לא צבוע יפה. אז, הם יותר דומים. אין הכרח לזה; קל לומר שהוא מפני שרק רואה מעט, שהוא דק, ואז קשה יותר להבחין. צריך עיין לעיל, שבארנו מהו “לבן שבה ותכלת שבה.”
לשון רש"י הוא: “גיזת צמר שצבעה תכלת ויש בה מקומות שלא עלה שם הצבע יפה.” בפשטות, כשרש"י אומר "שלא עלה שם הצבע יפה,” מכוון לבאר למה קשה להבחין. אבל, אינו מוכרח, שיש לומר שרק מכוון לבאר מציאות הגיזה, והוא שאינו חתיכה שבה רק צבע מקצתו (אולי מפני שלא מסתבר שישאר מקום קטן של לבן, ואולי מפני שקל להבחין, כיון שקל לדעת איזה מקום רצו להיות תכלת ואיזה מקום רצו להיות לבן), אלא היא חתיכה שלא עלה התכלת יפה על כולה, ואז מקצתה לבן.
ד.
יש לדון אם זה נכון גם בשיעור של רבי אליעזר; במילים אחרים, יש לדון אם רבי אליעזר סובר שהזמן הוא כשמחלק בין תכלת לכרתי, הוא הזמן שיכולים לחלק בין תכלת לכרתי שבבגד אחד או הזמן שיכולים לחלק בין תכלת לכרתי שבשני בגדים. עיין במה שנביא בע"ה מן הירושלמי, שמשמע שהוא נכון גם ברבי אליעזר. אבל, לא מוכרח משם.
ה.
ירושלמי (א, ב) מבאר שר“א דורש את זה מ“וראיתם אותו.“ סובר שזה קאי על פתיל התכלת שבציצית. (נראה שמניח כן מפני מש"א גמ’ בסוטה ובכ"מ שבראיית תכלת זוכרים את כסא הכבוד וה’. זה מתאים עם מש"כ, “וראיתם אותו וזכרתם….” אז, הולך על התכלת.) כיון שנאמר סתם (רק אומר שצריך להכיר אותו, ולא נאמר ממה), מניחים שצריך להכיר אותו מדבר הדומה לו, והוא כרתי.[fn:5]
ו.
לא ידוע לי סדר של שיטות אלו ביום. באמת, גם לא נודע לי איזה מהם חולקים על שאר השיטות, ואיזה רק נותנים סימן אחר.
ז.
ירושלמי מצדד ששיטה זו שווה לשיעור של ר"א.
ח.
לכאו’, סובר ש"וראיתם אותו“ קאי על זאב או כלב (אבל, יש לדון למה יסבור כן), וסובר, כר“א, שצריך להכיר אותו ממה שדומה לו. (א“כ, שיעור ההרחק יהיה ג“כ ד"א, כמו שנבאר באחרים.) (אם סובר כר"א ממש, כמו שמצדד ירושלמי, אז דורש את הפסוק כמותו, אלא שנותן סימן אחר.)
עיין בירושלמי שמזכיר דרשה בענין אחר שדורש ר"מ מ"וראיתם אותו.” אז, לכאו’, רבי מאיר לא דורש את הזמן משם. יש לדון, אז, מה המקור לשיטתו. אבל, גם יש להעיר שאף שבבלי מביא שיטה זו מרבי מאיר, ירושלמי לא מביא אותו ממנו, אלא מ"אית דאמרי,” ובאמת, ירושלמי מצדד שסובר כר"א (ואז, מסתבר שכמו שירושלמי אמר שר"א דרש כן מקרא, גם שיטה זו דורשת אותו מקרא). ותחשב. (עיין במה שנכתב לקמן, בע"ה.)
ט.
ירושלמי מוסיף שהכוונה הוא לחברו שקצת מכיר.
י.
דורש את זה מ“וראיתם אותו,“ שסובר שקאי על ראיית חבר (יש לדון למה סובר כן), וסתם ראייה הוא בהרחק ארבע אמות.[fn:6]
יא.
ירושלמי מצדד ששיטה זו שווה לת“ק של המשנה. יש להעיר שאפשר, אז, שיש שני דרכים לדרוש שיטה אחת מן הקרא (שירושלמי מזכיר דרשות לכל אחד ואחד). ותחשב.
יב.
נמצא, אז, שיש לנו שלש שיטות בדברי רבי מאיר. הראשון הוא מה שאומר בבבלי, והוא שהוא הזמן שיכולים להפריש בין זאב לכלב. זה מובא בירושלמי, אחר דברי אחרים, להיות ”אית דאמרי.“ יש גם שיטת אחרים (שהוא רבי מאיר, כמש“א גמ’ בסוף הוריות, שהוא זמן שיכול להכיר את מי שקצת מכיר בהרחק ד“א. מירושלמי מבואר ששנים אלו דורשים כן מ“וראיתם אותו.“ אז, ר“מ של ירושלמי, שדורש דבר אחר מ“וראיתם אותו“ אינו לא כזה ולא כזה.
ראשון, הערה פשוטה יש בענין שיטת ”אית דאמרי.“ קל לומר שהוא שיטת אחת בר“מ בתוך הירושלמי, שנאמר אחר אחרים, שהוא ר“מ. אז, אולי, בבלי וירושלמי לא חולקים בזה. גם יש לומר שהוא דרך אחר לומר ”אחרים,“ שיש לו אותו פירוש.
אבל, שני, עוד קשה הוא איך ר“מ סותר א“ע כך. אפשר לומר שאין דרשת ר“מ דרשה ממש, ועיקר דרשה הוא להלכה שבו, אבל לא נראה כן. ממש מדייק דרשה שלו מן הקרא, ואז משמע שהוא ממש דרשה. כמו כן מצאנו שגמ’ יאמר שלא דורשים דין מן הקרא כיון שצריך אותו לדרשה של אגדתא. אולי יותר מסתבר שבא לדרשת דין, ואז דורשים ממנו הדין (כיון שאין מקור אחר לדין (ויש לדון, שקרא אומר ”ובקומך“)), אבל דורש ר“מ דרשה שלו מלשון ”אותו.“ דחוק. אז, אולי צ“ל שר“מ חזר בו או שחלקו תנאים בשיטת ר“מ. ותחשב.
יד.
גמ’ אומר ש"לקריאת שמע כוותיקין.” יש לדון אם רצה לומר שיש חיוב ממש לכתחילה, או רק שזה זמנו המובחר. ממה שמזכיר עליו סיפורים משמע שאינו חיוב ממש, שאילו היה חיוב, היו כל האמוראים מקיימים אותו. ותחשב.
(שוב ראיתי שחולקים ראשונים בזה, שרס"ג, רמב"ם, ומאירי סוברים שהוא חיוב, ורמב"ן, רשב"א, רא"ש, ורשב"ץ סוברים שאינו חיוב. ש"ע פסק שאינו חיוב.)
טו.
נראה שיש שיטה שתחלוק על זה.  הרי, גמ’ אומר שזמן הכי טוב להתפלל תפילת מנחה הוא קרוב לזמן שקיעת החמה, כיון שכ’, “ייראוך עם שמש.” אבל, אביי פסק שלא לעשות כן, שמא יפשע, ויעבור זמן תפילת המנחה. רואים שזמן מובחר זה נדחה כשהוא בסוף זמן התפילה. רבי אליעזר סובר שסוף זמן קריאת שמע הוא הנץ החמה. אז, נראה שלפי אביי, רבי אליעזר יסבור שלא יקרא קריאת שמע בזמן המובחר הזה, מחשש שמא יפשע, ולא יקרא קריאת שמע בזמנו הראוי. ותחשב.
טז.
כתבנו שהפסוק נאמר על תפלה. כ"כ רש"י. אבל, ראיתי מי שמעורר שבאותה סוגיה רש"י סותר את עצמו, ופי’ שהולך על קריאת שמע.
יז.
סוגיא זו של וותיקין קשה להבין, ואין כאן המקום להאריך. אבל, למטה, נביא כמה מן הקושיות שבסוגיא.[fn:7]
יח.
עיין ברש"י (ג:) מפרש שזה עד תחילת שעה שלישית, ולא סוף שעה שלישית. אבל, הרמב”ם פוסק שיכולים לקרוא קריאת שמע עד סוף שלש שעות. אז, צ”ל שהוא חולק על שיטת רש”י, וסובר שרבי יהושע סובר שיכול לקרוא עד סוף שלש שעות.
אבל, לא נראה שמוכרח מרש”י שחולק על הרמב”ם. עיין שם (ג:), שמבאר שלפי רבי נתן, שיש רק שלש אשמורות בלילה, חצות הלילה היה, לתי’ אחד, קודם שני משמרות, כיון שסובר כרבי יהושע, והכוונה היא שהיה קודם זמן קריאת שמע, שהיא אחרי שני משמרות. רש”י כ’ שהוא שמונה שעות, שיש שש שעות של לילה, ושני שעות ביום.
לכאו’, הוכחה של רש"י בא ממה שאומר שקדמו עיניו משמורות, אף שהיה לפני שש שעות של לילה, ושלש של יום. אם כן, היה יותר משני אשמרות. צריך לומר ששעה שלישית ר"ל בתחילת אותו שעה. (יש לדון בזה, שהיה קל לתרץ שיש בכלל זה אשמורות, אלא שהוא יותר. נראה שהיה קשה לרש"י ל"ל יזכיר את היתר.)
אבל, נראה שאפשר לומר שרש"י סובר שבזה חולקים שני התירוצים (או שבזה חולקים רבי (שהביא ראיה משם) ורבי נתן). ותחשב.
יט.
ירושלמי (א, ב) אומר שאין לסמוך על זה אלא בשעת הדחק. אז, אם שכח, יקרא אז, או אם צריך לעשות מצווה, יכול להמתין עד אז. יש לדון אם מכוון לומר שטוב להחמיר כשיטת רבי אליעזר או שאף רבי יהושע לא היקל אלא בשעת הדחק.
יש להעיר שלכאו’ יוצא מזה שאין חיוב לקרוא קריאת שמע עם הוותיקין, לפי הירושלמי, שאל”ה, היה פשוט ששיטה זו נאמרה רק בשעת הדחק, ששלא בשעת הדחק, צריך לקרוא קריאת שמע עם הוותיקין.
כ.
** (ג:, ד.)
בגמרא (ט:) גורס "מלכים" במקום "בני מלכים.” מגמרא
מבואר שזה אף גבי מלכים. אפשר שמלכים קל וחומר מבני מלכים, שהם יותר חשובים, ומסתמא הם יותר מעונגים. ויש לדון, שאף יש להם יותר לעשות, ואז נפרך הקל וחומר.
כא.
ידוע שיש מחלקת תנאים בכ"מ אם  בני ישראל נחשבים בני מלכים. (עיין בשבת, שמביא כמה תנאים שסוברים שכל בנ"י נחשבים בני מלכים.) אפשר להיות שגם מחלקת רבי יהושע ורבי אליעזר תלוי בזה. גם אפשר לחלק לומר ששם החולקים סוברים שתלוי לכל אדם בעצמו. אבל, כאן, תלוי בזמן קימה של בני אדם, ולא בזמן של אדם הקורא. אז, אולי זה גם כולל בני מלכים. ותחשב.
כב.
לכאו’, זה הולך גם על קריאת שמע של ערבית, שרק שם יכול אדם לקרוא אותו אחרי זמנו. (אבל, אולי יש לדון בזה, שיש שאוסרים לקרוא פסוקים בלילה. אז, אולי רק לא הפסיד אם קורא אותו בקיום מצוות קריאת שמע.)
יש לדון למה אמר אותו רק כאן, בשחרית. אפשר שהמתין עד הסוף, ואמר אותו על שניהם. גי"ל שאמר אותו על שחרית בדווקא כיון שלא נוגע בערבית, שיוצא קריאתה בזמנה מדאו’ עד זמן קריאת שמע של שחרית, ואז בוודאי יקרא, שיש לו מצווה אחרת. יש לדון, שלרוב שיטות התנאים, יש זמן בין סוף קריאת שמע של ערבית לתחילת קריאת שמע של שחרית. אבל, אפשר שאין הרבה זמן, ואז לא יהיה כ"כ נוגע. ותחשב.
כג.
יש לגמרא שני לשונות בזה. בראשון, רב חסדא אומר שלא יברך עליו, ומביא גמרא תיובתא מברייתא שאומר שמברך עליו. בשני, רב חסדא מפרש ש"לא הפסיד" שאומר גמרא אומר שלא הפסיד הברכות. גמרא מוכיח כן מאותו ברייתא. אחר כן, אומר גמרא שצריך לומר שקריאת שמע יותר טוב מתורה, שהרי אומר שלא הפסיד, והוא כתלמוד תורה. משמע שקריאה בזמנה עדיף מתלמוד תורה.
מדבר ראשון שאומר גמ’, משמע ש"לא הפסיד" רצה לומר שלא הפסיד מלברך עליו.  מדבר שני שאומר גמ’, משמע ש"לא הפסיד" רצה לומר שלא עשה דבר רע, אלא עשה דבר טוב.
באמת, צריך לבאר איך לקרוא משנה, אם "לא הפסיד" אומר שלא הפסיד ברכות. לכאורה, ממשיך לומר שהוא "כקורא בתורה.” קשה, שאין מברכים על תורה.
לשניהם, קשה ל"ל מפרשים כפשטות המשנה, והוא שאין בעיה בקריאתו- לא הפסיד כלום- שהוא כקריאת התורה, שהוא מצווה.
אפשר שאומר שני דברים- לא הפסיד הברכות, וגם הוא כקורא בתורה. לא משמע כן, שלא אומר משנה "וכקורא,” אלא "כקורא.”[fn:8] אפשר שמדייק ממה שלא אומר, “יקרא כאדם הקורא בתורה,” אלא אמר לשון "לא הפסיד,” שמשמע שיש מה שלא הפסיד.
כד.
יש להעיר שלכאו’ זה פשוט, ולא צריכים משנה ולא צריכים גמ’, שהרי הוא ת"ת, ומוסיף עליו עוד מצווה. אבל, דע שיש אחרונים שמצדדים שאין קיום של מצוות ת"ת כשיוצא מצווה אחרת באותו לימוד. צ"ב למה לא יכול לקיים שני המצוות.
יש להעיר שלכאו’ כשמשנה מדמה אותו ללימוד תורה הוא ללימוד תורה באותו דרגה של כוונה. אז, אם לא מכוון כל כך, ולא יודע מה שאומר (חוץ ממקומות שצריכים כוונה), אינו יותר גדול מת"ת עם כוונה. (זה משמע שת"ת בלי כוונה נחשבת ת"ת, שאל"ה ק"ק למה אומר שהוא כת"ת, שלפעמים אינו אף כת"ת, דהיי’ כשלא מכוון בו. ותחשב.)[fn:9]
כה.
גמרא אומר שקורא קריאת שמע בעונתה יותר גדול מן הלומד תורה. לכאורה, הסיבה לזה הוא מפני שהוא מקיים שני דברים, שמקיים תלמוד תורה עם מצוות קריאת שמע. יש להקשות על זה ממה שכ’ ר"ש קלוגר, שכ’ שאין מקיימים מצוות תלמוד תורה במה שמקיימים בו מצווה אחרת. (חושב אני שכ’ כן לבאר למה גמרא מגילה (ב:) אומר שדוחים תלמוד תורה למקרא מגילה, שהרי מגילה עצמו כבר תלמוד תורה.) אם כן, לכאורה כאן לא מקיימים מצוות תלמוד תורה. אפשר לומר שקריאת שמע חלוק, שאולי מצוות קריאת שמע הוא ללמוד- לעשות ולקיים מצוות תלמוד תורה- אותם פרשיות. יש לדון אם זה יהני; כמובן, יהיה תלוי בסברה למה שאמר רש"ק. אפשר שהסברה הוא כעין מה שאין איסור חל על איסור, והוא שיש לו רק שם של איסור אחר[fn:10]; כמו כן כאן, אולי יש לו שם של מצווה אחת.[fn:11] אם כן, אולי כיון שאין שני השמות סותרים זה את זה, ששם של קריאת שמע כולל שם של תלמוד תורה, יקיים מצוות ת"ת. גם אפשר שמצוות תלמוד תורה צריך להיות ראוי להיות לשמה; אין דבר ראוי להיות לשמה כיון שאף יכווןן למצווה אחרת. אולי, אז, כוונה לק"ש יהיה שלשם תורה, כיון שהמצווה הוא ללמוד. ותחשב.
גם יש עוד קושיה על פשט זה. לזה, יהיה נמצא שקריאת שמע לאחר זמנו יותר טוב מתלמוד תורה, שהרי מוסיף עליו קיום של ק"ש. לכאורה, ההוכחה שמוסיף קיום של ק"ש הוא, לכאורה, מה שמברך עליו. ויש לדון. ותחשב.
לא יהיה קשה מזה על מה שאומר גמרא שהוא כקורא בתורה, שאומר שמקיים המצווה כיון שלולי קיום המצווה הוא על כל פנים כקורא בתורה, ואז מקיים המצווה. ותחשב.[fn:12]
ודע שאם אין הפשט כמש"כ, קשה, שהרי "תלמוד תורה כנגד כולם,” ומה שאומר ירושלמי בתחילת פאה שכל חפצי שמים לא שווים לתורה.
משנה ג:
א.
עיין בתוס’, שכ’ שהמחלקת הוא רק אם לא יצא מדרבנן, דהיינו שיתחייב לקרוא עוד מדרבנן. אף אם נאמר שלא יוצא מדאו’, הביאור יהיה שרבנן עשו שלא יוצא מדאו’.[fn:13] אבל, חוץ מדינים של רבנן, בוודאי ייצא מדאו’.
ב.
לכאו’, מזה יכולים להבין מהו דרשת בית הלל. צריך לומר שבית הלל לא דורשים מייתור, שהרי יוצא מכאן שאין הפסוק מיותר. (אפשר לומר שעדיין מה שנקט הליכה בדרך הוא מיותר, שהיה לו לנקוט דבר אחר, אבל לשון הגמרא לא משמע כן.) אלא, משמע שמה שקורא בדרך הוא המוכיח שקורא כדרך שירצה. לכאו’, הביאור הוא שקשה לקרוא בהטייה בערב ובעמידה בשחרית כשהוא על הדרך, ויותר מסתבר לומר שהפסוק מגלה שלא צריך להטות ולעמוד מלומר שחייב להטות כשהוא על הדרך.
לפי זה, מש"א רבי טרפון מובן מאד. רבי טרפון לא רק דחה את הדין, אלא גם דחה את המקור, ואמר שאפשר לקרוא כשהוא בדרך, שהאו עצמו עשה כן. רבנן אולי דחה שלא נכון, והוא פק"נ, ולא מסתבר שצוותה התורה שיעשה כן, או שלא באו לדחות אותו, אלא אמרו שכיון שלא נכון, הוא עבר עבירה גדולה. ותחשב.
גם יש לדון איך היה מותר לר"ט להטות ולסכן את עצמו. נראה שיש שלש דרכים. דרך ראשון הוא שאינו דווקא, ולא ממש היה פק"נ, אלא היה קרוב לו. דרך שני הוא שסבר שכיון שיש בק"ש אהבת ה’ וכדומה, דוחה פק"נ. (יותר מזה, יש לומר שסבר שבוודאי על ק"ש עצמו נאמר "בכל נפשך,” שהוא בפרשת ק"ש.) דרך שלישי הוא שפסוק שמחייב אותו להטות וגם מחייב אותו לקרוא כשהוא בדרך מחייב אותו לדחות את פק"נ.
ג.
עיין בגמ’ בתחי’ פסחים ובכ"מ שאומר שיכנס אדם לעיר בעוד השמש זורח. כנראה, רבי טרפון לא הקפיד על זה (או שנאנס). יש להעיר, יותר מזה, שאם ב"ה סוברים שמה שלא חייב לקרוא בהטייה הוא מפני שגם חייב לקרוא בדרך, ולא מסתבר שיצטרך להטות, אז מחודש שב"ה יחושו שלהולך בלילה, כיון שלעולם ילך אדם כששמש זורח. אז, צ"ל שמדובר בק"ש של בוקר.
לדחות זה, צ"ל שגם לא מסתבר לב"ה שיצטרך לעמוד או שב"ה סובר שגם מדבר בלילה, שלא כל אדם תמיד מקפיד ליכנס לעיר בעוד שהחמה זורחת, שלפעמים קשה לו או לפעמים נאנס (שהדרך נמשך, וחוזר יותר מאוחר ממה שרצה. ותחשב ותבין.
משנה ד:
א.
יש לדון איזה מיני ברכות הם ברכות קריאת שמע. אפשר שהם ברכות המצווה, אבל הלשון שלהם לא משמע כן, שאינם כשאר ברכות המצווה. כמו"כ, קשה, אז, למה מברך עליהם יותר מברכה אחת, ולמה מברך אחריהם. אז, נראה לומר שיש להם סיבה אחרת (אולי בצירוף סיבת ברכת המצווה). אפשר לפרש שמברכים לה' בהודאה על שנתן לנו אותם דברים שאנחנו אומרים בקריאת שמע. כמו כן, אפשר לפרש שמברכים לה' על דברים אחרים, והם באים אגב קריאת שמע, דהיינו שיש יחס ביניהם לבין קריאת שמע. ותחשב.
ב.
יש להעיר שבאמת מצאנו ארבע פעמים שמסדר קריאה של לילה ושל בוקר:
1. הפסוק – אומר של לילה קודם של שחר.
2. משנה ראשונה ושניה – אומר של לילה קודם של שחר.
3. משנה שלישית – אומר של לילה קודם של שחר.
4. משנה רביעית – אומר של שחר קודם של לילה.
גמ’ מפרש שברביעית מזכיר שחר קודם כיון שהוא היה הקרוב לו. אז, קשה למה לא עשה כן בשני, כיון שזה ששל שחר היה הקרוב לו כיון שנמשך מן הפסוק. צריך לומר שלא כל כך הולך על הפסוק עד שצריך ללכת כסדר זה, אלא שכיון שידוע הפסוק, אומרים שקצת הולך עליו. ותחשב. גם קשה למה לא עשה כן בשלישי.
היה נראה לומר שכל זמן שתלוי בדרשת הפסוק, הלך כסדר הפסוק. (לא צריך לומר כן בראשון, ששם כבר יש לנו תי’, אבל נראה שאפשר לומר כן שם, שהוא הולך על הזמן, וזה נלמד מן הפסוק.) אז, כיון ששלישי מדבר בדרשת פסוק "בשכבך ובקומך,” ודרשת פסוק "בלכתך בדרך,” הלך כסדר הקרא. אבל, משנה זו מבארת דין דרבנן, דין שלא יצא מן הפסוק בכלל. אז, לא צריך ללכת כסדר הפסוק, ואז הולכים בסדר היותר מסתבר, והוא להקדים עם הקרוב.
ג.
יש לדון למה רוצה שיקדים בקרוב לו. אפשר שהיה של בוקר במוח של התנא, שהיה דבר האחרון שדיבר בו. אז, המשיך בו. גם אפשר שטוב להיות כל דינים של דבר אחד במקום אחד. אז, מקרב אותם ככל מה שיכול.
ד.
בפשטות, הייתי אומר שעיקר הדין הוא שמברך ברכת יוצר אור וברכת אהבת עולם (או אהבה רבה) לפניו. אבל, אפשר לפרש בלשון המשנה שגם יש ענין שיהיה שתי ברכות לפני קריאת שמע, ואלו הן הברכות שתקנו חז"ל. (כמו"כ יהיה בהמשך המשנה.)
אבל, אין הוכחה לזה, שיש לומר שהמשנה רק מנה כמה ברכות יש, ולא מכוון להגיד לנו שהדין קובע שיהיה כמנין הזה, אלא שהדין קובע שיהיו ברכות אלו שם. ותחשב.
ה.
היום, הרבה נוהגים[fn:14] להוסיף עוד ברכה (ברכת יראו עינינו).
עיין בתוס’ בתחילת ברכות שמביא ירושלמי שנביא לקמן בהערות. ירו’ כ’ שבכל יום אדם מברך שבע ברכות ק"ש (שלש ביום וארבע בערב), ומקיים "שבע ביום הללתיך.” תוס’ מקשה שכיון שמברכים ברכת יראו עינינו, נמצא שמברכים שמונה ברכות, ולא מקיימים את הפסוק.[fn:15] ק"ק ל"ל הקשה תוס’ ממשנה שלנו.[fn:16]
תוס’ תי’ שאותה ברכה היא רק תקנת רבנן כדי שמי שאיחר לבוא לבית הכנסת יכול לסיים את תפילתו בשעה ששאר המתפללים מסיימים (שהוא לא יברך ברכה זו). עשו כן כדי שלא יצטרך אדם לחזור לביתו לבד, שיש בזה סכנה.
ו.
ירושלמי (א, ה) מפרש שני ענינים שיוצאים ממניינים אלו:
1. מנין תפילות (כל ברכה וכל פרשה נחשבת תפלה אחת) של יום ושל לילה שווים. זה מניח שבלילה לא אומרים פרשה שלישית של ק“ש. אז, במקומו, יש עוד ברכה. אז, מקיימים ”והגית בו יומם ולילה,“ שעושים את ההיגיון של יום שווה לשל לילה.[fn:17]
2. מנין הברכות של יום שלם (יום ולילה) הם שבע. אז, מקיימים ”שבע ביום הללתיך.“[fn:18]
ז.
עיין בפני“מ על הירושלמי (א, ה) שפירש שהולך על שנים שלפניו. אז, הולך בין ביום בין בלילה, שבשניהם יש שני ברכות לפניו.
פני משה באר ש"ברכה ארוכה" היא ברכה שיש בה ברכה בתחילתה ובסופה. אז, לפי פני משה, הארוכה היא ברכת יוצר אור וברכת מעריב ערבים, והקצרה היא ברכת אהבת עולם (או אהבה רבה) של שחרית ואהבת עולם של ערבית. (הסיבה שאין ברכה בתחילת ברכות הקצרות כאן הוא שהם ברכות הסמוכות לחברותיהן, שהן דבוקות לברכה ראשונה שלהן[fn:19].)
לפי פני משה יוצא שכשאומר גמ' ש"לקצר אי אתה רשאי להאריך," ו"שלא לחתום אי אפשר לחתום," אומר דבר דומה, והשני נאמר לבאר את הראשון. אבל, יש גם הוספה בשני, והוא שלא יכול לשנות ברכתו של ברכה מתחילתו לסופו ומסופו לתחילתו, אף אם אינו מאריך (ועושה שיש ברכה בתחילה ובסוף) על ידי זה.
רש"י לא מפרש כפני משה, אלא מפרש שהולך על שני הברכות אחרי קריאת שמע של ערבית. בנ"א, רש"י פי' ש"אמת ויציב" היא הארוכה ו"השכיבנו" היא הקצרה.
רש"י לא פי' מהו "אורכה" ו"קצרה" כאן. רש"י לא יכול לפרש כמו הפני משה, שאין ברכה בתחילה ובסוף של אמת ויציב, אלא רק בסוף. אז, לכאו', "ארוכה" צריך לומר "ארוכה" ממש. ברכת אמת ויציב יותר ארוך מברכת השכיבנו, ואז גמ' אומר שהוא הארוכה, והשכיבנו היא הקצרה. (עדיין, הלשון ק"ק, שהיה לו לומר שזה ארוך מזה, ולא שזה ארוך וזה קצר.)
אם לא נגרוס כנ"א שברש"י, היה אפשר להפך, לומר שברכת השכיבנו נחשבת ברכה ארוכה, כיון שחתימה שלה ("שומר את עמו ישראל לעד", ובפרט בשבת, שמברכים, "הפורש סוכת שלום עלינו, ועל כל עמו ישראל, ועל ירושלים") ארוכה, וברכת גאל ישראל נחשבת ברכה קצרה, כיון שחתימה שלה ("גאל ישראל") קצרה. אבל, לא משמע כן, וגם, עכ"פ בחול, אין חילוק גדול ביניהם. ותחשב.
יוצא לפי רש"י שיש חילוק גדול בין "לקצר אי אתה רשאי להאריך," ו"שלא לחתום אי אתה רשאי לחתום."
עיין בתוס', שמפרש דברי רש"י כצד ראשון שלנו, ומקשה ששניהם ארוכים. לכאו', רצה לומר שיש בשניהם יותר מברכה, אלא יש להם הקדמה לברכה. אז, שניהם נחשבים ארוכים. אז, פי' שקאי על ברכת אמת ואמונה. לא מפרש שר"ל שברכה אחת ארוכה וברכה אחת קצרה, כמו שפי' רש"י ופנ"מ, אלא פי' שר"ל "בין ארוכה בין קצרה." אז, אומר שצריכים לקרוא אמת ואמונה כתקנתה, בין אם תקנתה ארוכה, בין אם תקנה קצרה (שפי' שם שיש דרכים שונים לברך ברכת אמת ואמונה). יש להעיר שלא משמע שגמ' קאי על ברכת אמת ואמונה. עכ"פ, לפי תוס', כשאומר, "אחת ארוכה ואחת קצרה," רצה לומר שבין אם היא ארוכה ובין אם היא קצרה, צריך לברך כתיקנה.
כך היא הפי' הפשוט בתוס', אבל ראיתי שרשב"א פי' בתוס' שנקרא עם מש"כ לאחריו, ש"בין אם היא ארוכה בין אם היא קצרה, מקום שאמרו להאריך...." יש להעיר שאז הלשון כפול, שלא נראה י מה מוסיף "בין שהיא ארוכה," שהיה רק לומר ש"מקום שאמרו להאריך אי אפשר לקצר." ותחשב. גם יש להעיר שמתוד"ה מקום שאמרו להאריך לא נראה כן, אלא נראה ש"מקום שאמרו לקצר..." הוא כלל הנאמר על כל ברכות, ולא נאמר על אמת ואמונה במשנתינו.
ח.
פני משה באר (ומסתבר לומר כן) שההו"א הוא שיכול לפתוח בברוך. מלמד לנו שלא מספיק שיפתח בה בברוך, אלא שצריך לסיים בה בברוך. אבל, אינו מצדד שלא יברך בכלל, שפשוט שצריך לברך בברכה.
ט.
לכאו', אומר שאם היא ממין הברכות שמברך עליהם בתחילה ולא בסוף, לא יכול לברך עליו בסוף, לא במקום ברכה בתחילה, ולא בהוספה עליו. אבל, לא כל כך נראה שמדברים בברכה ממין זה, לשני טעמים. טעם ראשון הוא שלא מצאנו הרבה ברכות כזה; נראה לי שרק מצאנו כן בברכת הטוב והמיטב. טעם שני הוא שרש"י מפרש באיזה מדברים, ופי' שהוא מין רביעי. (מצאנו לפעמים שנקרא מין רביעי בלשון של מין שני.)
נמצא שבברכות הפירות וכדו', לא חותמים, שהברכה לא נחשב חתימה, אלא היא כולה. אז, אומר שאי אפשר להוסיף על הברכות, לעשות שזה חתימה. קצ"ב, שמה לנו אם  אומר דבר לפני הברכה, שכבר לא התחיל את הברכה. אפשר שכיון שמכוון אותו לשם ברכה, נחשב שהוא חלק מן הברכה, ופוסל את הברכה. גם אפשר שמדובר במוסיף ברכה בתחילה ובסוף. ותחשב.
יש להעיר שכיון שהגענו לזה – שפירוש ש"לא לחתום" הוא ברכה כמו ברכת המצוות – אפשר לפרש שמה שרוצה אדם לעשות בבבא ראשון של המשנה הוא לברך ברכה משאר המינים, ולומר רק הברכה ממנו, לעשות אותו כמין רביעי.
משנה ה:
א.
נראה שכיון שממשיך ממשנה שמבאר דין ברכות קריאת שמע – שאינו עיקר חיוב קריאת שמע, אלא חיוב צדדי של קריאת שמע, שהוא חיוב של דבר הנאמר עם קריאת שמע – ממשיך לבאר חיוב הזכרת יציאת מצרים, שהוא גם חיוב צדדי, שהוא חיוב שיוצא על ידי קריאת חלק מקריאת שמע. ותחשב.
ב.
צריכים לבאר את זה. הרי, מצאנו שני מחלוקות בגמרא שנוגעים לזה.
מחלקת ראשון הוא אם צריך להתחיל את פרשה השלישית או לא צריך להתחיל. במילים אחרים, נ"ל, מחלקת זו היא אם יש חיוב להזכיר קריאת שמע בפרשה שלישית[fn:20] או אין חיוב להזכיר אותו בפרשה שלישית, אלא יכול להזכיר אותו באיזה אופן שרוצה.
מחלקת שנית תלוייה בדין שכולם מסכימים לו. אף שחולקים אם צריך לקרוא פרשה שלישית, מודים שאם התחיל את הפרשה שצריך לגמור אותו. חולקים כמה מן הפרשה נחשב התחלה שמחייב אותו לגמור אותו. על ידי זה גם ייצא מחלקת כמה צריך לומר, אם נניח שצריך להתחיל את פרשה השלישית, שהרי צריך לומר עד שנחב שכבר התחיל את הפרשה[fn:21].
אז, יוצאים מזה שלש השיטות.
שיטה ראשונה סוברת שצריך להתחיל, ומסופק כמה נחשב התחלה. לכן, מחמיר להתחיל ולקרוא עד (וכולל) "דבר אל בני ישראל ואמרת עליהם." אבל, גם מחמיר שזה נקרא התחלה שמחייב אותו לגמור את הפרשה. אז, בין הכל, יוצא שצריך לקרוא כל פרשה שלישית.
שיטה שנית סוברת שצריך להתחיל, ופוסק מה נחשב התחלה. הצד שאומר גמרא הוא שסובר שאומר עד (וכולל) "דבר אל בני ישראל ואמרת עליהם," ואח"כ ממשיכים לפרשת יציאת מצרים. אבל, לא מוכרח שזה התחלה, שיש חולק על זה, כמבואר בגמ', ויכול להיות מי שסובר כשיטה שנית שסובר שיש התחלה אחרת.
שיטה שלישית סוברת שלא צריך להתחיל. אז, אומר נוסח אחר של הזכרת יציאת מצרים. גמ' מזכיר נוסח – יש לדון אם הנוסח הוא חיוב או לא – והוא: "מודים אנחנו לך ה' אלקינו שהוצאתנו מארץ מצרים ופדיתנו מבית עבדים ועשית לנו נסים וגבורות על הים ושרנו לך."
כל זה מה שאני מניח בסוגיית גמרא בדף יד:. אבל, ממה שפירשתי יוצא שכשאומר שם, "דבר אל בני ישראל ואמרת עליהם אני ה' אלקיכם אמת," אינו דווקא, שרצה לומר שאז צריך לומר סוף הפרשה, שקורא "אני ה' אלקיכם אמת," אף שבאמת מתחיל קודם אותם מילים, שמזכיר יציאת מצרים. כן נראה לי מסברה וכן נראה מכל הגמ' ומרש"י, אבל לא מוכרח כן, שאפשר לפרש שגמ' מצדד שצריך לומר פרשה שלישית, ולא מפני הזכרת יציאת מצרים. דן כמה מפרשה שלישית צריך לומר (ואם, באמת, צריך לומר פרשה שלישית). ותחשב.
ג.
צריך ביאור מה לנו במה שהיה כבן שבעים שנה. אילו היה ממש בן שבעים, ואמר שאף בהמשך הזמן, לא היה זוכה שיקיימו את דבריו, אז אולי היה מובן, שהיה יותר נראה להיות מקובל לזמן ארוך, שניסה ליותר זמן. אבל, כיון שרק אומר שהוא כמו בן שבעים שנה, וכמש"פ רש"י, קשה מה לנו בהיותו כבן שבעים שנה.
אולי ר"ל שאף שהיה כל כך חשוב, שנס כזה נעשה לו כדי שיהיה ראש ישיבה, לא שמעו לו לאמור יציאת מצרים בלילות. כמו"כ יש לומר שבא לדחות הצד שמה שלא שמעו לו הוא מפני שהוא צעיר. לזה דחה שהרי הוא כבן שבעים שנה, ואז באמת פלא הוא מה שלא שמעו לו. עדיין צריך ביאור.
ד.
עיין בירושלמי, שפי’ שהיה בן שבעים שנה, ושלא היה מצוי שמלך יחיה לזמן רב.
משמע שבא לפרש לשון "כבן שבעים שנה," אבל לא פשוט איך מבאר אותו. לכאו', רואה מן המשנה שהיה בן שבעים שנה, ואמר זה תמיהה, שבדר"כ אין נשיא חי לזמן ארוך כזה. אבל, לא פשוט מה לנו ב"כבן." [fn:22] גם אפשר לומר שגמרא מפרש שאומר שהוא כבן שבעים שנה דהיי' שחי זמן ארוך למי שהוא בנשיאות, שלא היה בן שבעים, אלא היה חי שבעים שנה של נשיאות, דהיי' זמן ארוך לנשיא.
ה.
יש לדון למה רק קיבלו אותו אחרי שבן זומא דרש אותו, ולא קיבלו אותו מראב"ע. נראה שיכול להיות שני פירושים פשוטים:
פי' הראשון הוא שרק בן זומא דרש אותו מפסוק זה. כיון ששמעו דרשה זו, בני אדם הסכימו לדברי בן זומא. אבל, ראב"ע לא אמר אותו להם מפסוק זה, ולכן לא הסכימו לו.
על פי' זה, יש להקשות איך ידע ראב"ע דין זה אם לא מדרשת בן זומא. (אפשר לומר שידע אותו מדרשת ב"ז, ורק שלא אמר לבני אדם אותה דרשה. זה דחוק, שכיון שלא שמעו לו, היה לו להסביר את הטעם שלו להם.) אפשר לומר שהיה לו דרשה אחרת, אבל אז נמצא דבר מעניין – נמצא שהוא המביא לנו דרשת בן זומא, וכנראה שמח כשהתחילו לנהוג כמותו, אף שהוא לא סבר כמותו, שסבר שדרשתו לא נכונה. גם אפשר לומר שהיה לו קבלה שצריכים להזכיר קריאת שמע בלילה, אבל לא היה לו מקור. בן זומא חידש לו את המקור.
פי' השני הוא שאף שראב"ע דרש מפסוק זה, לא הסכימו לו. אבל, כשבן זומא דרש מפסוק זה, הסכימו לו, שכיבדו אותו יותר, והקשיבו לו יותר.
על פי זה, יש להקשות למה ישמעו לבן זומא, שאף לא היה מוסמך, ולא לראב"ע, שהיה הנשיא. נראה שהביאור יהיה ע"פ גמ' (בסוף סוטה) שאומר שבן זומא היה דרשן טוב, ודרש פסוקים באופן בהיר. אז, רק אחרי ששמעו דרשה זו מפי מי שהיה בבקי בדרשות – דהיינו, בן זומא – הסכימו בני אדם לדרשה ולדין. אבל, כל זמן שרק שמעו אותו מראב"ע, לא סמכו שהדרשה שלו נכונה. ותחשב.
ו.
איני יודע מהו המקור של רש"י לזה. עיין לעיל, במה שהבאנו מן הירושלמי, שאולי מוכרח שירושלמי חולק על רש"י בזה. ותחשב.
ז.
קצת צריך ביאור למה ממעטים לילה – למה רבנן סוברים שאין מזכירים יציאת מצרים בלילות, ולמה ראב"ע צריך מקור לומר שמזכירים. נראה שהוא מפני שלא היה גאולה בלילה. (אבל, גמ' דן בזה (ד:); עכ"פ, לכו"ע עיקר גאולה לא היה בלילה.) גם אפשר לומר שמשמעות "ימי חייך" הוא רק ימים. אבל, יש לדון אם "ימים" סתם משמע מיעוט על לילות, שגם יום שלם, שכולל יום ולילה, נקרא "יום."
יש להעיר שגם צריך ביאור מהי"ת לפי ראב"ע שפסוק עושה חיוב חדש על לילה, ולא רק אומר שחיוב יום נמשך ללילה, ויש לו יותר זמן לקיים את חיוב שלו. אולי באמת רבנן סוברים כן, שאולי ההו"א הוא שיש רק חיוב אחד ביום, כמו משמעות הפסוק. אז, ראב"ע דורש לרבות עוד חיוב. אבל, משמעות הדרשה לא נראה כן כלל. גם צריך לעיין בגמ' לקמן שמשמע שצריך להזכיר יצ"מ קודם סוף זמן ק"ש של שחר. אז, בוודאי לא יכול להזכיר אותו בלילה לפי רבנן. אפשר שזה כראב"ע. אבל, בין כך ובין כך לא נודע לי למה לא יאמר אותו כל היום. אולי הוא רק דין רבנן, ואז אין להוכיח ממנו כלום. גם אפשר שאם נאמר שהוא כראב"ע יכולים לומר שכיון שמצאנו חיוב יום וחיוב לילה, כמו ק"ש, מסתבר שזמן שלו כזמן קריאת שמע. ותחשב.
ח.
נמצא שיש שני פסוקים. יש פסוק בתורה – "כל ימי חייך" – ויש פסוק בנ"ך שאומר שלא נזכור עוד את ק"ש. לכאו', קשה למה ראב"ע צריך פסוק בנ"ך, שבוודאי לא מזכיר בימות המשיח, כיון שכבר דרש מ"כל." (אם נאמר שראב"ע לא באמת דרש כבן זומא (עיין לעיל) אין זה קשה.) אפשר לומר שאיה"נ, היה אפשר להקשות מזה, אלא שהקשה מפסוק מלא. גם אפשר שבלי פסוק זה, הייתי אומר שא"צ פסוק לרבות ימות המשיח.[fn:23] לרבנן, יש לדון מהי"ת למעט קריאת שמע בימות המשיח, שצריך לרבות אותו. אולי הוא אותו פסוק שמביא ראב"ע  ואולי הוא מה שאין מצוות נוהגים לעתיד לבוא ואולי הוא מסברה (שכבר בא גאולה יותר גדולה). על צד ראשון יש להקשות שעד שלא נכ' נ"ך, איך ביאור "כל." על צד שני, יש להעיר שחולקים אמוראים אם נוהגים מצוות לעתיד לבוא. אז, הכי קל הוא להניח כצד שלישי. ותחשב.
* Footnotes
[fn:1] נראה שאולי מה שיהיה משמע כן, ולא משמע זמן שבני אדם שוכבים, יכול להיות לשני טעמים. אפשר ששכיבה ר"ל מעשה של הליכה לשכוב. לא נראה כן, שאם כן, לא היה רש"י אומר (ט.) שהוא זמן שהולכים לשכוב, אלא ששוכבים, דהיינו שהולכים לישן. ויש לדון. יותר נראה לומר שלשון "בשכבך" מודיע שאינו זמן של שכיבה, שאינו אפשר לקראות, אז, בשכבך. אז, צריך לומר ש"בשכבך" ר"ל כשאתה עסוק לילך לשכב. ותחשב.
[fn:2] אגב, לכאורה לשון של רש"י קצת מוזר, שלכאורה הוא הזמן שעוסקים לילך לשכב, ולא לילך ולשכב. ויש לדון, שאף היום במילי דעלמא בני אדם מוסיפים "וי"ו" בכעין זה.
[fn:3] אם כן, יש לשאול למה אין חילוק בזמן התחלתה, שלכאורה, פשוט שזמן שבני אדם הולכים לשכב מקדים לזמן שבני אדם שוכבים. נראה ארבע מהלכים:אפשר שיש נפק"מ. יש צד אחד בגמרא שאומר שרבי אליעזר סובר שתחלת זמן קריאת שמע הוא מבין השמשות. אולי, אז, חולקים בשני המחלוקות אלו לשיטתם. זה רק מהני לצד שבגמרא שסובר כן. יש צד בגמרא שסובר שיש תנא שלא סובר כן.יש להעיר ששיטה ראשונה גם כן, אולי, סובר שהוא זמן שהולכים לישון. אף על פי כן, גמרא מצדד לומר שלא חולק על משנה שלנו.אפשר שיש שני מחלוקתים, והוא שחולקים אם בשכבך ר"ל זמן שהולכים לשכב או זמן ששוכבים, וגם חולקים מתי הולכים לשכוב ומתי שוכבים. ואם תאמר כיון שבין כך ובין כך חולקים מתי קורה דדבר, ל"ל אומר רש"י שחולקים מתי בני אדם שוכבים או מתי בני אדם הולכים לשכוב, ולא יאמר שחולקים בפירוש הקרא. ויש לומר שלא מסתבר שיחלקו מתי דבר קורה ויהיה רחוק שמנה שעות. ויש להעיר שמגמרא (ד:) משמע שהיה קשה לגמרא לומר (אף שבני א"ג מצדד כן) שסוברים רבנן, שאומרים שהזמן חצות, כרבן גמליאל, שהוא תחלת זמן שכיבה. שם, הוא רק רחוק שני שעות. אף על פי כן, שני שעות הוא יותר מן החילוק שבין בין השמשות לצאת.אפשר שרבי אליעזר סובר ששכיבה משמע זמן שהולכים בני אדם לשכב, וזמן ששוכבים, שצריך ששניהם קורים. רש"י רק מזכיר הסיבה שחלק על חכמים, והוא מה שסובר שההליכה לשכוב הוא חלק ממשמעות המילה.אפשר שרבנן סוברים ששכיבה משמע שניהם, משמע זמן שהולכים לשכוב, ומשמע זמן ששוכבים.
[fn:4] נראה שרש"י יסבור שגמ’ במנחות לא מכוון לומר כירושלמי. שם, אומר ש"וראיתם אותו" רצה לומר שתראה את התכלת ותזכור מצווה אחרת שזמנה תלויה בה, שהוא קריאת שמע. זה משמע כירושלמי, אבל אפשר לומר, אף לפי רש"י, שזמנה תלוי בתכלת – לא בתכלת שבציצית, אלא בתכלת שבבגד שמקצתו תכלת ומקצתו לבן. ותחשב.
[fn:5] הפשטות הוא שצריך להכיר אותו מדבר הדומה לו כיון שלשון הכרה משמע הכרה מדבר הדומה לו, ולא הכרה מדבר שאינו כ"כ דומה לו. גם אפשר לומר שדורשים אותו כן כיון שבדר"כ דורשים לחומרא (כן אומר גמ’ ביבמות (ח.) בהיקש, וראשונים כתבו כן בדרשות אחרות). ויש לדון, שבדר"כ מצאנו כלל זה כשיש שני דרשות לדרוש, שנוקטים לדרוש את החמור. כאן, יש דרשה אחת שלא מבואר. לא פשוט שננקוט את החמור. ותחשב.
[fn:6] יש להעיר שלפי זה מסתבר ששאר ראייות שמצאנו בתנאים הוא בהרחק של ארבע אמות. (יש שני הוכחות לזה. הוכחה ראשונה הוא שדורשים מאותו פסוק, ואז גם הם ידרשו שראייה משמע ארבע אמות. הוכחה שנית הוא שמזכירים ראייה סתם, ואז משמעותו ארבע אמות. אבל, יש לדחות הוכחה שנית, שיש לומר שסתימות הפסוק וסתימות המשנה (בפרט לתנאים שבבריי’, שלא הזכירו ארבע אמות, אף  שתנא אחד הזכיר) לא שווים.) זה יכול להיות בר"ע ור"מ, אבל הוא מחודש בשיטות שבמשנה, שנראה שהוא קשה להבחין בין צבעים (בפרט בין צבעים שבציצית) בהרחק ארבע אמות.נראה שיש שני דרכים לדחות. אפשר לומר ששאר התנאים לא מודים ששאר ראייה היא ארבע אמות. גם אפשר שכשאומרים שסתם ראייה היא ארבע אמות, לא מכוון לומר שכל סתם ראייה היא בהרחק ארבע אמות, אלא שסתם ראיית חבר הוא בהרחק ארבע אמות. אבל, לשאר חפצים הנמנים בשיעורים אלו, אפשר שיש שיעור אחר של סתם ראייה. ותחשב.
[fn:7] מצאתי חיבור טוב על הסוגיא מר’ שמואל טל. שם, כ’ סיכום קושיות גדולות על הסוגיה:"בגמרא נאמר שטעם המנהג כוותיקין הוא כדי לסמוך גאולה לתפלה ולהתפלל ביום, ונראה מזה שמעלת הוותיקין מורכבת מצירוף של ק"ש ותפילה בזמנן. ולפי זה קשה על הרמב"ם שכתב שק"ש כוותיקין היא מעיקר הדין ואילו תפילה כוותיקין אינה מעיקר הדין. ועוד קשה שגם דין סמיכת גאולה לתפילהמובא בדבריו כהנהגה בעלמא ונראה שאינו מעיקר הדין, וקשה שדין הוותיקין מושתת על דבר שאינו מעיקר הדין.בדברי רש"י יש לכאורה סתירה בשאלה האם דרשת הפסוק "יראוך עם שמש" לזמן הנץ החמה מתייחסת לקריאת שמע או לתפילה.בנוסף, צריך ביאור מה שקרא לתפילת שמונה עשרה "תפילת יוצר".אף בברייתא דוותיקין ישנם מספר קשיים: ראשית, לשון הברייתא "ונמצא" מתפלל ביום טעונה ביאור. שנית, לכאורה בשביל להתפלל ביום ניתן להתפלל גם אחרי הזריחה, ואין צורך להתפלל דווקא כוותיקין. שלישית, לא ברור מדוע הפסוק "יראוך עם שמש" מתפרש כמתייחס דווקא לתפילה ולא לק"ש.במשנה דירד לטבול קשה שלא מובן למה האדם נדרש לקרוא את שמע בתוך המקווה אם הוא אינו הולך לסמוך גאולה לתפילה, שזולכאורה מטרת הקריאה כוותיקין.בדברי הרי"ף מבואר שפסק הלכה כוותיקין מעיקר הדין. אך הוא כתב שסתם בני אדם אינם יכולים לכוון את זמן הקריאה כוותיקין, וקשה שלכאורה נקבעה הלכה שהאנשים אינם יכולים לקיימה. וכן קשה מה שכתב שמי שאינו יכול לכוון, יקרא קריאת שמע מעט אחרי הוותיקין, דלכאורה אם הקריאה אינה כוותיקין, כבר אין עניין להקדימה דווקא לזמן זה, והיה צריך להתיר לקוראה גם מאוחר יותר.”
[fn:8] אולי אדם מברך על לימוד של קריאת שמע אם לא כבר אמר קריאת שמע. אז, משנה אומר שהוא לימוד של דברים אלו, ולכן מברך עליהם. אבל, ק"ק מהיכי תיתי חידוש זה, שדחוק לומר שמן הסברה הוא בא.
[fn:9] אבל, כל זה צריך ביאור, שכמו שבארנו, לשון המשנה לכאו’ רק אומר שאינו רע, שתמיד אינו רע לקרוא תורה. אז, לא מכוון למצוות ת"ת, אלא למעשה ת"ת, ואומר שזה לא רע. אז, כל דיוק הגמ’ צ"ב, שלא אומר שמקבל שכר כת"ת, אלא שכמו שקריאה בתורה תמיד אינו רע, כך ק"ש תמיד אינו רע. ותחשב.
[fn:10] נראה שזהו הפירוש הפשוט של אין איסור חל על איסור. הביאור הוא שתורה אסר דבר עם שם מיוחד (לא בגלל שום סיבות לומדי, ולא בהכרח בגלל ששם שייך לעשיית ס"ר, אלא רק מפני שדברים נקראים על שמם- שזהו מה שהוא שם- ואז כשאסרה תורה דבר, אסר דבר שיש לו אותו שם). כיון שדבר כבר יש לו שם של איסור אחד, אין שם של איסור השני נעשה כל כך שמו (מסתמא מפני שאינו סיבה לשינוי בדינו, שכבר יש סיבה לאסור אותו). אז, אינו בכלל אותו איסור. זהו הפשט הפשוט מחמת לשונות של רש"י ביבמות, שמזכיר לשונות שמשמעים כן כ"פ.
[fn:11] יש לדון, אז, למה יש לו רק שם של מצווה אחר, ולא של תלמוד תורה.
[fn:12] כוונתינו בזה הוא למש"כ לעיל, שצריך ללמוד תורה כדי לקיים ק"ש, שהמצווה הוא ללמוד פרשיות של ק"ש.
[fn:13] לא קל להבין איך יהיה כוח ביד רבנן לעשות שלא יוצא את מצוותו מדאו’, אבל לפעמים (ע’ בתוס’ בסוכה) מצאנו כן. לכאו’, נצטרך לומר שיש תנאי פשוט בתורה (כל כך פשוט עד שלא צריך להיאמר), והוא שייעשה כדעת רבנן. (יש להעיר שזה מתאים עם כלל של "כל שמקדש על דעת חכמים מקדש,” שיש לומר שהוא מפני אותו תנאי הסתום. (אבל, עיין ברש"י, שתלה אותו במה שאומר בשעת קידושין שהוא מקדש "כדת משה וישראל.”) גם אפשר לומר שכדי לקיים בו מצווה, מעשה צ"ל הוגדר להיות "מעשה טוב.” אבל, לפעמים רבנן הגדירו אותו ל"מעשה רע,” ואז אינו מקיים את המצווה. אף בזה צריך להיות תנאי שלא מזכיר. ותחשב. גם אפשר לפרש הוא מצווה הבאה בעבירה. (זה יכול להיות, אבל לא צריך להיות, שווה לצד שני שכתבנו.)
[fn:14] כן נוהגים כל בני אשכנז (אבל המתפללים נוסח ספרד לא מברכים ברכה זו במוצאי שבת), וכן נוהגים בני מורוקו.
[fn:15] יש לדון אם כוונת תוס’ להקשות איך מבטלים קיום הפסוק או להקשות שמצאנו שבימות הירושלמי לא ברכו ברכה זו. עיין לקמן למטה, בע"ה.
[fn:16] לפי צד ראשון שכתבנו לעיל למטה, לא כל כך קשה, שיש לומר שלא רואים שהמשנה מקפידה על המנין כ"כ. גם אפשר לתרץ (וזה אפשר לשני הצדדים) שאולי המשנה רק אומר שצריך לכל הפחות ברכות אלו. אבל, אינו אומר שאין להוסיף. אבל, כיון שהירושלמי אומר מנין מדוייק, מסתבר שהוא דווקא, ולא יכול להוסיף עליו. (גם אפשר לבאר שתוס’ כבר ידע המציאות שאומר בתי’ (שתקנו ברכה זו כדי שימתינו בבית הכנסת), וסבר שלכן לא מנה אותו משנה. אבל, סבר שעדיין יצטרף לשמונה ברכות. אבל, לא משמע כן.) לצד ראשון, אפשר לומר שלא קשה לתוס’ שברכה יהיה ניתוסף אחר משנה (אבל עדיין ק"ק שהגמרא לא יזכיר את זה), אבל קשה לו שברכה יהיה ניתוסף אחרי הירושלמי. דחוק.
[fn:17] יש לדון אם סובר שיש ענין של קיום "והגית בו יומן ולילה" בזה או שהענין הוא שכיון שמקיים ביאור אחד ב"והגית בו יומם ולילה,” זה מזכיר בני אדם לקיים ביאור האמיתי של "והגית בו יומם ולילה,” ששהוא ללמוד ביום ובלילה.
[fn:18] פסוק זה מדבר בדוד המלך, שאמר לה’ ש"שבע ביום הללתיך." עיין שם, שהרבה מן המפרשים העירו שאין שבע דווקא. לכאו', יש לדון אם הירושלמי אומר שהשבע דווקא, ומכוון למין פרטי של הילול שהוא ברכות קריאת שמע (או שרצה לומר שהוסיף שבע הללות על הילולים היותר בסיסים), או אינו דווקא, ורצה לומר שפעמים הרבה הילל את ה', כמו שהעירו אותם מפרשים, ורק כיון שנקט מילת שבעה, קבעו שבעה ברכות. (כעין זה יש לציין לפסחים, בתחילת פרק בתרא, שמצאנו שרבא עשה דבר כיון שרבו אמר אותו דבר, אף שלא היה דווקא.)
[fn:19] הביאור הפשוט הוא שכשאדם מתחיל לברך עם ה’, צריך להתחיל עם ברכה. אבל, כשהוא כבר עסוק בברכה, רק ממשיך את דיברו שלו עם ה’, ואין צורך לברך, כמו שאין צורך להוסיף ברכה באמצע ברכה.
[fn:20] לא פשוט מהו המקור שבדר"כ צריך להזכיר יצ"מ בפרק שלישית. לכאו', אין חיוב מן התורה, אלא רבנן קבעו להזכיר אותו בו, מפני שיש בה חמשה דברים, כמו שמפרש גמרא (יב:).
[fn:21] אין מי שאומר נקודה זו בפירוש, אבל נראה שכן יוצא מן הגמ'. לכאו', מסתבר לומר ששניהם תלויים זה בזה, שרק הקדמת הפרשה הוא מה שצריך לומר, ולא מה ששיך לפרשת ציצית. מה שאינו נחשב הקדמה הוא רק התחלת הפרשה. אז, שני הדיונים תלויים זה בזה. ותחשב על זה.
[fn:22] גמ' לא אומר בפי' שבא לדקדק בחילוק שבין "בן שבעים" ו"כבן שבעים," ואולי רק ר"ל שבן כמה שהיה, אם הוא כמו שבעים, בוודאי היה זקן. נמצא שאף שהיה נשיא, חי לזמן גדול, שמת זקן. ותחשב. אז, אולי אמר "כבן" מפני שלא דקדק, שהיה רק קרוב לשבעים, ואולי אמר אותו מחמת עין הרע, שלא יאמר שהגיע לבן שבעים שנה. אם נאמר כשני, יהיה לנו גם הוכחה שבדר"כ אין נשיאים חיים כל כך, ויכול לומר שהירושללמי מביא אות זה לראיה גם עליו, שאם חשש לעין הרע כשהיה רק בן שבעים, שאינו כ"כ זקן, רואים שגדולה מקצרת ימים, ולו היה נחשב אריכות ימים.
[fn:23] כמובן, אז צריך לדון מה נעשה קודם שהפסוק נכתב בנ"ך. צריך לומר שזה מורה על חילוק שיש, ואותו חילוק כבר נודע.
