** צרעת
:
בגד של צמר או פשתן שהוא שלש על שלש אצבעות שיש בו נגע הוא טמא. כשמטמא אותו, הפסוק אומר, “והבגד….” מן הריבוי של "וה" דורשים ששיעור הבגד להיות טמא הוא שלש על שלש אצבעות (שנקרא אריג קטן), שהוא ראוי להשתמשות עניים.
לא אפשר לומר שמרבה בגד של צמר ופשתן של שלשה על שלשה טפחים (שנקרא אריג גדול), שכיון שהוא ראוי להשתמשות עניים ועשירים, נלמד מקל וחומר משתי וערב שמטמא בנגעים. (ככה אומר הגמ’, אבל תוס’ מעורר שמהמשך הגמ’ יוצא שיש מקור אחר לבגד של שלשה על שלשה, והוא שנכלל במילת "בגד" סתם. אבל, מביא קו"ח לרווחא דמילתא.)
לא אפשר לומר שמרבה בגד של שאר מינים של אריג גדול שמצאנו שני מיעוטים כתובים למעט שאר בגדים (שכ’, “צמר ופשתן,” וכתיב בו "ב" יתירה). מזה לומדים למעט אריג קטן ואריג גדול של שאר מינים מטומאת נגעים. (יש להקשות איך יש הו"א שלא נרבה אריג קטן של צמר ופשתן ונרבה אריג גדול של שאר מינים, שאם כן אין חילוק בין צמר ופשתן. רק צריכים מיעוט אחד, אז, לדחות צד זה. ראשונים דנו בזה.)
לכאו’, על פי מש"כ לעיל, שאריג גדול הוא בכלל בגד, כיון שאין טומאה בשאר מינים באריג גדול, אין טומאה בשאר מינים בבגד שלם (היותר גדול מאריג גדול). אין טומאת נגעים כלל בשאר מינים.
אז, בארנו את הדין לענין טומאת צרעת של בגדים. בזה, אין שום חולק, וכולי עלמא מודים: יש טומאה על אריג קטן של צמר ופשתן, ואין טומאה אפילו באריג גדול (ואפילו בבגד שלם) של שאר מינים.
** שאר טומאות:
אבל, יש עוד דין הנוגע לטומאת בגדים. בגד נחשב כלי, ואז בגד מקבל טומאה. לא כל בגד נחשב כלי, אלא צריכה להיות בגד חשוב. בזה, מצאנו מחלקת תנאים. מצאנו שיטת שלש ברייתות. (אפשר שיש יותר תנאים, שאין הכרח שיש רק שיטות אלו, אבל רק מצאנו שלש ברייתות אלו). אבל, הבריי’ לא מבארים את הכל, ויש שלש שיטות באמוראים לבאר את שיטות התנאים.
** שיטות תנאים: בריי’ ראשונה - רשב"א
בריי’ ראשונה היא שיטת רבי שמעון בן אלעזר. רבי שמעון בן אלעזר אומר שאריג קטן של צמר ופשתן יש בו טומאה, אבל אריג קטן של שאר מינים אין בו טומאה.
** בריי’ שנית – תנא דבי ר"י
בריי’ שנית היא בריי’ ראשונה שמדבר בשיטת תנא דבי רבי ישמעאל. אומר שטומאת בגדים רק נוהג בצמר ופשתן, שנלמד מבגד הנאמר בצרעת. לכאו’, לומדים הגדרת בגד (או לומדים גזירה שווה) מצרעת לשאר דיני טומאה.
** בריי’ שלישית – תנא דבי ר”י
בריי’ שלישית היא בריי’ שנית שמדבר בשיטת תנא דבי רבי ישמעאל. אומר שטומאת בגדים נוהג גם בשאר מינים, שכ’, “או בגד.”
** שיטות אמוראים:
בין האמוראים, מצאנו שלש שיטות שמבארות שיטות התנאים:
** אביי:
בריי’ א’ ובריי’ ב’ אומרים דבר אחד. בריי’ ב’ הוא המקור לבריי’ א’.
בריי’ ב’ ובריי’ ג’ חולקים. אז, נמצא שיש מחלקת תנאים בשיטת תנא דבי רבי ישמעאל.
** רבא (א)
בריי' א' ובריי' ב' חולקים בדין אריג גדול של שאר מינים. בריי' א' סובר שמטמא, ובריי' ב' סובר שלא מטמא.
בריי' ב' ובריי' ג' חולקים.
** רבא (ב)
רבא חזר בו, ואמר שבריי' ב' וג' לא חולקים, שבריי' ב' מדבר באריג קטן, ובריי' ג' מדבר באריג גדול. מזה, רואים שחוזר ממש"ב בבריי' ב', ואז אין מחלקת בין השיטות.
** רב פפא
רב פפא באר שבריי' ב' אינו לענין שאר טומאות. אז, לענינינו, אין בריי' ב' נוגע.
לומדים בנין אב מנגעים לומר שאריג קטן מטמא.
שיטת רב פפא דחויה.
כמו שנראה, לקמן יבואר שני ביאורים במחלקת שבמשנתינו לענין טומאה. הראשון מדבר בשלש על שלש (אריג קטן), והשני מדבר בשלשה על שלשה (אריג גדול). איני יודע אם מדברים במינים שונים (ואז יש לדון אם הוא דווקא) או שניהם במין אחד, ויש חילוק ביניהם כיון שבשני מדובר בבגד גרוע, כמו שנראה.
