* ב.
** שתים שהן ארבע -
לשון זה קצת קשה, שמשמע שהשנים הם ארבע. אבל, לכאורה, השנים הם שני ציורים, ואינו נכון שהם ארבע. היה לו לומר: “יציאות שבת שנים וארבע.” ותחשב.
בשאר דברים שיש בהם אב ותולדה, קל לומר שיש שנים שהם האבות, והם ארבע, שהתולדה הוא מין של האב. אבל, כאן, צריך ביאור. ותחשב.
- ממשנה יוצא חילוק ציורים בין אם הוציא עומד בפנים או בחוץ. יש לדון מהו החילוק. (אילו לא היה קרק’ חשוב חלוק ביניהם, לא היה מחלק את הציורים לשנים, כמו שלא מחלק בין בעל הבית שלובש כולו לבן לבעל הבית שלובש כולו שחור. אז, צריך לומר שיש חשיבות במקומו.)
יש לומר שתחילת החפץ הוא קצת במקום אחר, שהוא ביד אדם[fn:1], ולכן מקום אדם קצת שייך לו. גם יש לומר שאז העושה הוא במקום אחר. גם יש לומר שאז המעשה חלוק לנגד העושה (אם מרחיק או מקרב).
יש לדון אם אלו הם, באמת, חילוקים חשובים, אבל לא מספיקים לעשות חלוק דין (יש מהם שאולי ישנה ס"ר, אבל לא ישנו דין), או שלמסקנא אף אינם מחלקים, והם רק קרק’ חשובים במה שהיה נראה לתלות בהם חילוק.
** שתים-
אגב, נראה שצריך קרא למלאכה זה כיון שהיא מלאכה גרועה (כמש"א ראשונים כאן), והו"א שלא ללמוד ממשכן (שכמובן, רק למדו ממשכן דברים שהיו עובודות, שמשכן היה בו הרבה דברים שלא נאסרו. ויש לדון אם היו אף דברים שעשו לצורך בנינו שלא נאסרו. וצריך לעיין.) גם יש לומר שלא היה כל כך לצורך הבנין בבית המקדש, כיון ששינוי ששינה לא היה חשוב (שהוא מלאכה גרועה). ויש לדון בזה, שהדרי נצרך הוא, אף אם לא חשוב הוא. ותחשב.
** שבועות -
מה שמחלק בין עתיד ועבר נראה שהוא מפני שאחד כתוב יותר בפירוש, וזה מחזק את דינו, כמו שאומר רשי בברכות ותוס’ בקידושין (ותוס’ בב"מ), וכמו שבארנו בכמה מקומות. גם היה אפשר לומר שאין עיקר החי’ שכ’ בפ’ אלא שיש בהם מח’. (אבל, לא נראה כן, שגמ’ מוקים משנה זה כתנא שמחייב. למה שכתבנו, היה לו לומר שהוא תנא אחר שידע את המחלקת. ויש לדון. ותחשב.)
* ב:
** מי לא עסקינן -
עיין ברש"י. קשה, שלא כן אומר גמ’ בשבועות. וי"ל שרשי סובר שממה שגמ’ כאן לא מפרש יותר, ולא מקשה יותר כמו גמ’ בשבועות, רואים שגמ’ שלנו חולק על גמ’ בשבועות. גם יש לומר שרשי רק מפרש כהוה אמינא של אותו גמ’ (מסתמא כיון שהוא יותר פשוט להבין, אףא שיש קושיה עליו). ותחשב. (ודע שמושג זה- קל להבין, אבל יש קושיה עליו- אינו כל כך פשוט לי, אבל נראה לי שהוא נכון.)
** הכנסות -
בכל שאר, אלו שנתרבו לארבע אינם כל כך עיקרים, ולכן יכולים למנות שנים מבלי למנות אותם. נראה שהכנסה אינה כל כך עיקרית כיון שרק נלמד מסברה, ולא מן הקרא. ויש לדון, שמסתמא, המביאים למשה היו עומדים בחוץ בשעת הוצאה, ואז צריך סברה גם לעומד בפנים. יש לומר שזה סברה יותר פשוטה. גם יש לומר שלמסקנא אין חילוק (סברה זה אומרת שהוא גם כן רע, אבל הרע קצת חלוק). גם יש לומר שהמביאים למשה אולי עמדו בפנים ואולי עמדו בחוץ.
- יש להעיר שיש ציור שלישית של הוצאה, והוא מי שיוצא עם החפץ. אם הענין הוא חילוק מקום האדם בשעת יציאה, צריך לדון מהו שעת יציאה (אין שעה, שבתחילה הוא כאן, ואחר כך הוא שם) כדי לדון איפה הוא. אז, אם משנה המעשה, נראה שזה סוג שלישי. אם משנה מקומו בתחילת מעשה, אי"ז עוד סוג, אבל לא נ’ שרק נדון במקומו בתחילת המעשה, אלא אף בסופו. אז, זה יהיה סוג שלישי. ותחשב.
** רשויות -
עיין בפירוש רשי. אם כן, הוא מאד חלוק משאר הציורים שבשבועות. ותחשב על זה ותבין.
לולי רשי, היה אפשר לומר שרבא רצה לומר יציאה מרושות לרשות, ומוסיף מילת רשויות, ולא מוחק מילת יציאה.
** רשויות -
יש לדון למה רבא חולק:
1. לא סובר שהכנסה נקרא הוצאה. (אז, אולי תולדה הוא, שהרי, צריך לומר שאין משנה בכלל גדול, שאומר הוצאה, כולל אותו. ויש לדון שאולי מחלק (ובאמת, קצת קשה איך מביאים ראיה, ולא מחלקים כך) בין "יציאות" ל"מוציא מרשות לרשות.” ודע שלא מוכרח שתולדה היא, שאולי משנה מזכיר ציור אחד של האב (כיון שקשה לכלל שניהם בלשון אחד), אבל עדיין שניהם אב אחד. (מעניין שלא יקראו שני אבות, כיון שכל כך קשה לכלל אותם לאחד. זה שייך קצת למה שיש לדון אם החילוק אבות הוא מחלת חילו בסיבות רעות או רק מחמת חילוק בהגדרת מעשים. חילוק חטאות משמע כצד ראשון.))
2. לא סובר שהכנסה טפלה להוצאה.
* ג.
** פטור ומות -
יש לדון למה לא שונה אותו:
1. מיירי בדברים שהם אסורים. קשה, שלא מפרש כן.
2. מיירי בבני אדם שיוצאים (שהםחלק מן הציור). אף שהיה נראה לומר כן לפרש המשנה, מה שנקט גמ’ מה שמותר, ולא מה שלא עשה כלום, לא משמע כן כל כך. יש לומר שהוא המשך אחד, “והקשינו… לא עביד מעשה.” ותחשב. (ועדיין, ממה שמביא כל זה, ולא רק אומרו, צריך לומר שמביא הוכחה ממה שהוא מותר. אז, צריך לומר שלא רק אומרו, אלא מביאו מקדמון.)
** פטור ומותר -
היה אפשר לדחות שכאן אומר כן משנה בפי’, ולכן לא צריך ששמואל  יאמר כן. מה שמשנה אומר כן הוא מחמת קושיה של גמ’ כאן. ונ’ שכיון שזה קשה אף על ציור של איסור, כמו שמקשה גמ’ כאן, לא רצה גמ’ לומר אותו. ותחשב ותבין.
** דאתי בהו לידי חיוב חטאת -
לכאו’, לא רצה לומר שבהם בלחוד נאסר, שנראה ששניהם עשו מעשה, והיה צריך ששמואל ימעט אותו בפירוש. אלא, נראה שלא ומנה אלא אלו שיכולים לבוא לידי חיוב. נראה שזה בכלל של משנה, זה מה שמשנה בא לבאר. לא בא לדון באיסורים, אלא בא לדון בחיובי חטאת, ובדברים המביאים לכך.
** צידת
- מנו להו- לכאו’, רצה לומר "למה.” וע"ש.
** לידי ח"ח -
שניהם יכולים לבוא לידי כך, שלכן גזרו, אלא שבדרך כלל, רק בא לידי כך אם חושב שכשם שזה מותר, כך הותאה מותרת. אבל, זה יכול לבוא לידי כך אם ממשיך את אותו מעשה. (אז, אולי מח"ז בפ"ע יותר מצוי או מח’ בירוף יותר מצוי.) אבל, קשה, ששם לא יחייב, שצריך לעקור משעה ראשונה לדעת להוציא. אולי רק יש סיבה לגזור על תחי’ מעשה (ויש לדון למה), וגזי’ על סוף מעשה הוא רק ל"פ. דחוק.
** ורבותי
- מסתמא, לא גרס בגמ’, “מביא לידי חיוב חטאת.” נראה שהביאור זה הוא שעדיין קצת הוא ברשות שלו, אף שנעקר. לכן, מי שמכניס או מוציא אותו הוא שעושה יותר. ותחשב.
** כל חיוב
- בא לבאר גי’ של גמ’ ש"מביא לידי חיוב חטאת.” מקשה למה נקט ח"ח כאן, ופי’ שאף משנה דן בזה. ויש לדון למה משנה דנה בזה. ויש לומר שהוא יותר קל, שלא צריך עדים והתראה, ועוד יש לדון ביותר, כמו בחילוק מלאכות.
** מעם הארץ -
מעניין שצריכים קרא להוציא את זה מחיוב. הייתי אומר מסברה שפשוט שמה שעושה אחד אינו כל כך רע אם צטרף עם שני, שאינו סיבה היחידית. אז, מהיכי תיתי לחייב אותו. לכאו’, אם אין מקור לחייב אותו, יפטור. אולי הוה אמינא שכמו שעברו בשותפות, כך יהיו חייבים להביא קרבן בשותפות.
** הטעינו חברו -
יש לדון למה יהיה פטור:
1. אולי אינו כל כך ברשות ששמתחיל, שהיה עליו.
2. אולי מעשה שלו נחשב מעשה הוצאת עצמו, ולא כל כך הוצאת החפץ. מחמת זה פטור.
** ל"ג-
יש לדון אם כוונתו לומר שהוא ייתור לשון, וכבר אמרנו אותו או שהוא ביאור אחר, ואותו ביאור לא נצרך, שגמ’ כבר נתן טעם מספיק.
** ל"א-
יש לדון אם רשי מביא שיש גורסים "ידו בתר גופו…,” או שיש גו’, “לשון אחר….” צד ראשון כאן אינו כל כך טוב, שקשה למה נחשב ייתור. צריך לומר שסובר שיותר טוב לומר טעם או לשון שאומר גמ’. ותחשב.
* ג:
** בר פחתי -
מצאנו במקום אחר (כתבנו אותו בחידות שלנו) שהיה אייבו (אבא של רב) תלמיד חכם. גם יש להעיר שאם היה אבא של רב אח של ר"ח מאביו, נמצא שהיה לו יחוס מאחיו של דוד, כמו שאומר גמ’ בכתובות (נ"ל).
** לא אמינא לך -
ואם תאמר הרי אמר גמ’ לקמן (קיד.): “איזהו תלמיד חכם שראוי למנותו פרנס? כל ששואלים אותו הלכ בכל מקום.” ויש לומר שזה רק אם הוא בפי’ במשניות או דבר סדור כזה (שהרי מז’ מסכת כלה). גם יש לומר שנשיא אינו פרנס. אבל, מוזר שצ"ל ת"ח יותר מרבי. וי"ל שרבי חלוק (ויל"ד אם זה ית’ גם לק’ ראשונה) שהיה עוסק לסדר משניות.
** לא תפשוט-
עיין בתוס’. דע שהיה אפשר לומר שאולי כשאמרנו לקנוס כאן, הוא רק במזיד, ודיון של ר"ב היה בשוגג. (צריך לע’ לקמן לראות אם זה יהני.) אז, אב,א שבא אחר כך אינו קאי על זה, אלא חוזר למח’ הבריי’. ותחשב.
** כספתיה -
נמצא שחוששים שמא יתבייש, אבל לא חוששים שיטעה ויאמר דבר שאינו כון. לכאו’, אם בטוח הוא, נכון הוא, ואם לא, יאמר שלא יודע. ותחשב ותבין.(ואגב, יש להעיר שרבי טעה, באמת, בדם נדה, כמו שאומר גמ’ בב"ב ובנדה ובמק"א.)
** כרמלית -
יש לדון אם נקרא כן כיון שהוא מצב שיש עליו דיני כרמלית או שהוא דבר שמדאו’ אינו רה"ר ולא רה"י. ותח’. וע’ בעירובין מתי דבר נקרא כרמלית (שם משמע, חושב אני, כצד ראשון).
** בתר גופו -
לכאו’, זה מחמת שלא נח’ נח. אי נח’ נח, לא יהיו שניהם מצטפרים למלאכה, שבינתיים נח במקום פטור. אם כן, קשה איך נאמר שהוא כרמלית. (אולי, אז, צריך לומר כצד ראשון שכ’ לעיל. עדיין קצת מחו’, שאין מקום שנוכל לתלות דינים אלו עליו, שהענין הוא שאין לו מקום.)
** קנסו-
רשי מניח שהוא קנס (עושים לו רע כיון שהתחיל לעשות רע, ולא רוצים שיתחיל כך). גם אפשר (ודע שגמ’ לקמן מבאר הסיבה, אבל יש לומר שזה נתחדש שם) שהוא רק גזי’ (חוששים שיחלף לו, אם מותר), וקורא לו קנס, כבתחילת בכורות. וע"ש.
יש לדון למה התחלתו היה באיסור:
1. מניחים (וגוזרים מח"ז) מקום שיניח החפץ.
2. אסור להושיט ידו עם חפץ שמא יניח אותו. ותחשב.
* ד.
** תחלתה וסופה -
מעניין, שהרי כבר בא סוף מעשה שלו, ורק לא בא סוף של האיסור. ויש לומר שמעשיו (מה שעשה ליחס לרע) כולל מה שלא מונע את הבישול. ותחשב.
** במזיד -
אז, עדיין נפשט של רב ביבי לעיל. ותחשב ותבין.
** חטא כדי -
לא הבנתי את זה כל כך מימי, שלכאו’, ענין מצוות ועבירות הם שצווה ה’ דברים שעושים ס"ט או ס"ר. אז, אם מסתבר שעל ידי זה, לא יברא רע, אף אם נברא קצת רע, יעשה אותו למנוע מהרבה רע. (אפשר שהוא כעין "מאי חזי דדמא דידך סמיק טפי.” אין עבירות של כל אנשים שווים, ואולי מה שמיוחס הוא לו יעשה שהוא יותר רע. אז, שב ואל תעשה עדיף.) אולי אף שמסתבר כן, כיון שאין צווי לו למנוע את חברו מן החטא, אלא רק יש צווי על חטא שלו, לזה צריך לשמוע. אבל, זה מבקש השאלה למה הוא כן. אף זה צריך ביאור, שעדיין מרוויח צווי, שנמצא שחברו עשה צווי שלו. אולי אם עדיין רוצה חברו לעבור, לא נחשב שקיים צווי שלו, שהיה אונס נגד רצונו. (ויש לדון, שאין ה’ מצטרף מח’ רעה למעשה.) וצריך ביאור למה הוא כל כך פשוט לגמ’.
באמת, מגמ’ משמע שההיתר (אילו היה היתר) הוא כדי שאל יחייב חברו, ולא כדי שלא יקרה הרע. ותחשב.
** לא בעינן -
היה אפשר לומר שסובר שבעינן, ומקום שתחתיו נחשב מקומו. (נראה שיחשב מקומו כיון שבדרך כלל, דבר שהוא שם, בלי דחיפה אחרת, יפול לאותו מקום.) אז, אולי אם יש כבר תחתיו קום שאינו ארבע, אולי לא מהני. אפשר שאין זה הפשט בקלוטה, וגם אפשר שצורך לד"א אינו שהוא מקום חשוב, אלא שבלי זה אינו כל כך מקומו, שחוששים שיפול. אבל, לר"ע, מפרש שהיה נופל לשם עושה שהוא מקומו, ואז בוודאי לא צריך ד"א. ותחשב. ויש לדון בכל זה.
* ד:
** שדי נופו -
ואם תאמר למה נשדה בתר עיקרו ולא נשדה ידו בתר גופו. ויש לומר שידו לא נברא מגופו (ויש לדון, שאולי נברא ממנו במעי אמו. ויש לדון, שאינו עצמו כבר.). גם יש לומר שמקום יד חשוב, ולא יודעים כל כך ממקום גוף. אבל, מקום נוף אינו כל כך חשוב.
** טרסקל -
ואם תאמר למה רק מונים חיובים ואיסורים מחמת מה שנטל ונתן, ולא טרסקל. ויש לומר שרק איסור אחד הוא, שטרסקל בטל לו. ועיין בגמ’ לקמן, שאומר כן גבי כלי.
** טרסקל -
נראה שחשב על זה כיון שדוחה גמ’ לומר שיש מקום דע"ד בציור של אחרים, אף שלא הזכיר אותו. ותחשב. (ואם תאמר אם כן גמ’ סותר א"ע (בין כך ובין כך זה קשה). ויש לומר שכאן מבאר כמה פרטי הציור, אף שלא נצרכים, והיה לו לבאר את זה. גם יש לחלק בין בריי’ למשנה. ויש לדון, שבדרך כלל, בריי’ מבארים יותר.)
** עיקר -
קשה למה אין עשיית מקום ארבע על ארבע כהליכה ממקומו. ויש לומר שעשה כן לפני הזריקה. וחדוק.
** כשני בני אדם -
לא הבנתי הצד לפטור, שכלאו’ רע נעשה, והוא הגורם היחידי. אולי דרך שגרם אותו חלוק, ולכן אינו כל כך מיוחס לו. צריך ביאור למה זה יעשה שאינו כל כך מיוחס. אולי שני יחסים קטנים לא דומה ליחס אחד גדול. ותחשב. יותר נראה לומר שאין מעשה אחד שנוכל לומר שה’ צווה שלא ייעשה. ויש לדון, שאולי ה’ צווה שלא לעשות שניהם ביחד. (ודע שאפשר שענין שנים שעשאוה אינו רק שאינו מיוחס די לשום אחד לפטור, אלא שהעבירה חלוק (שצירך יחס לישראל להיותר רע די), ואז יש לומר שגם כאן, כיון שיחסו חלוק, אולי אינו אותו עבירה. ותחשב על זה.)
* ה:
** מי עבידי -
צריך ביאור למה בשנים אלו אמר, “עביד,” ולא שנח. נראה שרצה לומר שלא ישנה מים, ויהיה אומר שנח על כותל, שלא מצוי שיוכל לנוח שם. אבל, ישנה ספר סתם, ויכוון לזה. אז, אם תנא ישנה אותו סתם (ולא הדין) תלוי באם עביד דנייח. ותחשב.
** אגוז בכלי -
לכאו’, היה אפשר לומר שענין הנחה הוא שיהיה מקומו "ברשות זה.” אם מונח, מקומו הוא יותר שם. אז, לכאו’, פשוט שלא יהני מה שהוא מונח בתוך כלי, שזה רק עושה שמקומו הוא "כלי,” אבל כיון שאין כלי נח, אין מקומו "ברושת זה.” אז, לא נראה לפרש שלכן צריך להיות מונח (ואולי זה הדיון). ונראה שאולי דבר מונח יותר חשוב (יש לדון למה), ואז קרק’ שלו יותר חשובים, ורק אז אומרים שיש לו, באופן חשוב, מקום. ותחשב.
** אמוראי -
נראה שיש חי’ בשני, והוא שצריך כוונה להוציא, אבל אין חידוש בראשון ממנו.
** היכי אשכחנא -
יש לדון אם זה גכ"ק לב"ע למס’ גמ’ שמודה בזירקה או שאולי רק צריך מקור כיון שהוא ראוי לנוח במקום פטור (שיכול אדם להניח אותו שם).
* ו.
** מירי אמעביר -
קשה למה לא לומד ממוציא, שעד שמוציא היה פטור. כמו כן קשה, ששם גם כן עד שמניחו לא חייב. שוב ראיתי בתוס’. אז, צריך לומר שתרצן זה (או מסדר זה) ידע תי’ שיבוא. ותחשב.
** מידי דהוה -
עיין בתוס’. נ’ שמחו’ לומר שהיה צדי רה,ר עם חיפופים כמשכן.
** גדר -
צריך ביאור למה לא מזכיר מה שסביב לו יש גדר עשרה, והוא רחב ארבע טפחים על ארבע טפחים. ויש לומר שיסודו שווה לגדר, שהוא רשות היחיד כיון שכמאן דמלי הוא. ויש לדון גבי בור. א, יש לומר שכבר נח’ חלק מבור. תחשב.
** עניש
- תולה בהתראה. גם היה אפשר לתלות בעדים.
** לא עירבו
- עיין במה שפ’ למה לא נח’ רשות אחר. כל זה אינו כל כך ברו לי. לכאו’, יש שלש דינים דאו’, ורבנן הוספו אחד, והוסיפו אותו על שני ציורים (רצה לומר, על שני דינים דאו’, רה"י ומק"פ). צריך ביאור איך נקרא לדינים דרבנן אחד, כיון שהם חלוקים לשאר דינים (דאו’). זה מניח שנקראים אחד, אבל רשי לא כ"כ, אלא כ’ שהוא רה"י. אז, קשה לל"א שכרמלית ה"ה מק"ם. יש לומר שלא נשתייר דינים שלא נוגעו מדינים דרבנן, שנאסר, אבל לזה, נשאר חיוב, וזה לא נשתנה כלל, שמדאו’ נאסר ומדאו’ חייב. ותחשב. (גם יש לומר שמקום פטור ר"ל שאין בו רשות, שאין המקום שלו חשוב. רבנן החשיבות אותו ואמרו דין עליו. אז, אי אפשר לומר שהוא כבר בכלל מקום פטור. ותחשב על זה.)
** אדם
- בטל אצל- מוזר שרשות אחד יכול לבטל לשני דברים. לכאו’, ענין ביטול הוא שנח’ חלק מזה. אז, קשה איזה הוא. אולי אינו סותר א"ע להיות שניהם. ותחשב. ויש לדון למה זה מתיר את שניהם, וללא אוסר את שניהם. ותחשב.
** מקום פטור -
מעניין שנקרא כן, שאינו רק פטור, אלא מותר. אולי רצה לומר שוהא פטור מדיני שבת, ואין דיני שבת נאמרים עליו. ויש לדון, שיש מקצת דינים דרבנן נאמרים עליו (שלא יחליף). ויש לומר שרק דן בדינים דאו’. אם כן, יש לומר שרצה לומר שמדאו’ פטור, וזה שווה למותר, שלא מצאנו בדיני שבת פטור ואסור מדאו’. ויש לדון במחמר. אבל, עדיין קשה למה ינקוט פטור ולא מותר. ויש לדון איזה יהיה יותר טוב. ויש לדון בכל זה, שמניחים שאין התר נחשב דין שנאמר עליו, והוא שרק יש דין איסור בשאר, ובזה לא נאמר. ותחשב. נראה שזה נכון, שתורה לא אמר בו שום ציווי.
** לחי -
היה, לכאו’, רשות היחיד בלי זה, ומה שמשנה זה ממעט הוא ציור שבו אומר ר"י שמותר בלחי. ותו"ת.
* ו:
** כאן בזמן -
ואם תאמר לתני בזמן שהיו בני ישראל בתוכה. ויש לומר שלא מנה אותו כיון שלא נמצא עוד. גם יש לומר שלא רצה למנות דבר שלא פסקא (שכל ציוריו כן).
- קצת צריך ביאור למה בריי’ נתן כ"F כמה ציורים, ולא רק תני הכללים.
** שאם עשאן -
יש לדון מה מקשה:
1. יודעים שמשנה אמר שחייב הרבה. אז, נמצא שהכותב חלק על משנה זה ולא מסתבר לנו (מס’ כיון שסתם משנה הוא).
2. כמו שמדיי’ כן על משנה, נדייק כן מן הכתוב. (שו"ר בתוס’.)
נראה שהוה מצי להק’ שאולי מיירי כששוכח עיקר שבת. נראה שלצד שני, יש לומר שלא מסתבר שמשנה בתוכו באיזה ציור קאי, ובתחילתו היה דן בשכח מלאכות, שלכן הזכיר המנין.
** אחד מהם -
לכאו’, גמ’ לא מפר’ לעולם איזה הוא. ויש לומר שהוא הבערה לרבי יוסי, שהוא רק לאו.
* ז.
** שם רה"י
(בגליון הש"ס)- קשה הוא שזה בוודאי כרמלית. בהשקפה ראשונה, היה נראה כמש"א גמ’ בכ"מ שתנא רה"י אגב זה, ואז צריך לומר שזה רה,י. אבל, ע"ש, שיש הרבה ציורים שהם רה"י. אפשר שאפשר לומר בזה שהוא כרמלית, שהוא סיפא אגב רישא, אבל כאן צריך לומר רישא אגב סיפא, וגמ’ בזבחים מניח, בהו"א שרק אומרים סיפא אגב רישא. כמו כן, כ’ תוס’ במק"א שיותר קל לומר סיפא אגב רישא. (עיין במקום אחר שהקשנו למה לא משתמשים בזה ללמוד מכל מקום שאומר "אלא מהא ליכא.…”)
כל זה מניח שאומ’ רה"י אגב, ושצריך נקודה זו. ין גמ’ משמע כן כל כך. ותחשב.
** מפסקתן
- רבנן- משמע שכל האסור שם היה רק מדרבנן. אז, צריך לומר או שמחיצה זה מהני מדא’ או שהוא בתוך כרמלית.
וע’ במאירי, שכ’ שהוא איסור דאו’, אבל בחי’ כ’ שהקילו רבנן. וצריך ביאור, שנמצא שהקילו בדין דאו’ בקו"ע.
** רה"י
- לכאו’, רשי פי’ כצד שהוא כרמלית, שאם הוא רה"י, לכאו’ אין הילו רבים משנה כלום. וצריך לע’ בגמ’ שדן בילוך בין פסי ביראות לפי רבי יהודה, אם עושה אותו רה"ר או כרמלית, ואם זה גם כן שייך כאן, שלא צריך קולת רבנן (ר,י לא סובר כן כאן, אבל צריך לדון בו כאן אם הוא שייך.) ותחשב.
* ז.
** רשות היחיד קתני -
אפשר לפרש שרצה לומר שבין כך ובין כך אין הלשון מדוייק.
** ל"א -
היה אפשר לומר שחולקים אם ענין רשות הרבים ה"ה שראוי להליכת רבים או שיש בו הליכת רבים. ותחשב.
** דרסי בה -
משמע שאף שהל"מ הוא, יודעים שתלוי במה שבני אדם דורסים עליו (או, אולי, בדמיונו לקרקע).
** פחות מארבע -
קשה, שאין רה,ר פחות מטז אמה. ויש לומר שזה רק ברוחב, אבל באורך, יכול להיות יותר קטן. יש לדון למה, ששל משכן גם היה ארוך.
נראה יותר שאם משתמשים בו רבים, אין צריכים שיעור זה. שיעור זה הוא רק בדרך להיות דרך ראוי לרבים. (אפשר שהוא כשרשות הרבים בתוך רה"ר.)
** אין כל דינים של רשות
הרבים ורשות היחיד פשוים לי. נתחיל ברחוב. אם רחוב זה הוא רחב טז אמה, ואין מחיצות סביביו, וראוי הוא להילוך רבים, אז הוא רשות הרבים.  יש בו עמוד. אם עמוד זה פחות משלש טפחים, הוא רה"ר. אם הוא גדול מזה, ולא הגיע לתשע טפחים, הוא כרמלית. אם הוא ט טפחים, הוא רשות הרבים. אם הוא עשר טפחים, הוא רה"י. (בין ט’ לי’ הוא מחלקת ראשונים.) כל זה אם הוא רחב ארבע טפחים. אם הוא לא רחב כן, הוא מקום פטור בדרך כלל. (איני יודע אם כיון שהוא בתוך רשות הרבים, הוא בטל לרשות הרבים. אבל, בין כך ובין כך אין הנחה עליו אפשר. (וצריך ביאור אז מהו הנפ"מ של מקום פטור.) חושב אני שכיון שהוא בתוך רה"ר, כאן הוא רה"ר, כמונח באויר, שהוא כשהוא מונח, אבל לא על דבר (אלא על צידו וכדומה). אם מונח בתוך רה"ר, שהוא עשרה טפחים, הוא בתוך רשות הרבים. ותחשב.. רשי מזכיר ציור אחר, והוא שקולט מין האויר. עכשיו, נדון ברשות הרבים. אם יש מחיצות יע לד על ד, אז לפנים מן המחיצות או על המחיצות (או על מה שממלא אותו) הוא רשות היחיד. אם יש בו כל דבר, לעולם,עד לרקיע, הוא, וכן אויריו, רה"י. אם יש מקום שאינו רה"י או רה"ר, מקום פטור הוא מדאו’. אם יש בו דע"ד, הוא כרמלית, וגזרו עליו מדרבנן. אם יש בו דע"ד על י’ הוא רשות היחיד. אם יש פחות מזה, הוא כרמלית, אם הוא דע"ד. אם אינו דע"ד, נראה שהוא מקום פטור. (איני יודע אם בטל לו.)
** שדי נופו
- ל"א- אז, נמצא שאין מי שמצריך הנחה על דע"ד. זה נגד תחילת המסכתא. על כל פנים, ר,ח יחלוק על כל הסוגיה (אבל אולי רק להנחה, ולא לעקירה).
** גבוהה י’ -
לחומרא לא דק לאפרשי- לכאו’, לא רצה לומר שעשה כן כדי להפירש אותו, אלא שעשה כן באופן שלא יטעו, אלא רק מפירש אותו. ותו"ת.
** רחבה י’
- לכאו’, קושיית רשי הוא ראיה (מגמ’) שאין מקום פטור רשות בפני עצמו, אלא הוא, כמו שאומר רשי, בטל לכל מקום. (אין הראיה שאז יפטור, אלא שאז נמצא שטלטלו רשויות, לכאו. ויש לדון.)
** אי אפשר -
לכאו’, אז נמצא שלא הולכים רוב במקום החפץ. כמו כן אומרים בסכך. (אלוי רשי רצה לומר שלא עושה דבר נח חוץ מזה.)
** אבל גבוה
- למחיצות- גם אומר אותו, לכאו’, כשנח על גב מקום פחות מארבע. ודע שמעניין שכשאומרים כן על מחיצות, אומר כן רק על גבה, ולא תחתיהם. ויש לדון אם תחתיהם כולל שוליהם. ותחשב.
** מדרס -
משמע שאינו דמין לבוד. כמו כן היה משמע לעיל (ח.). אבל, קשה, שלא משמע כן ממה שלא צריך דע"ד, כמובאר לעיל (ואלי זה רק היה הו"א).
** מכתף -
עיין ברשי זה. עיין בגליון הש"ס. (ודע שמזה נ’ שבדרך כלל ברשות הרבים פחות מד’ אינו בטל לרשות הרבים, והאו מקטום פטור. אז, מה שכתבנו לעיל אינו נכון.)
** מאי לאו -
אז, רינו צריך לומר כמו שכ’ רשי לחלק בין כלי לרשות לכרמלית.
* ח:
** ולא דחויי -
נראה שאפשר שרצה לומר שלא ידחק כן להעמיד שיטה שלו, שלא צריך דחייה, שיכול לומר שתנאי הוא. אז, אומר תירוץ זה בלי הכרח, ואז צריך לומר שיותר נשמע מן הקושיה. ותחשב ותבין.
* ט:
** עד שיתפלל-
עיין בביאור שנתן למה נכתב משנה זה כאן. ויש להעיר שתוס’ כ’ (וכן נראה שיוצא מגמ’ זבחים בענין מנדב שמן) שיותר קל לומר סיפא מח’ רישא. אז, קשה למה הקדים משנה זה. אולי צריך לומר ששנים אלו נשנו ביחד בסדר זה כבר לפני רבי. ותחשב.
* Footnotes
[fn:1] אף שהגביה אותו בתחילת מעשה, היה ידו עליו, שהתחיל בהגבהה שלו. ועוד, שמיד במעשה שלו היה בידו. ותחשב.
