* צו:
** מקושש מעביר ארבע אמות –
נראה שהסיבה שבחר לעבור בזה הוא מפני שהוצאה מלאכה קלה. רצה להודיע לישראל שאף על מלאכה קלה אדם חייב מיתה, וכל שכן על שאר מלאכות שעושה תוצאה חשובה. ותו"ת.
** ואינו חייב אלא אחת –
וא"ת אולי זה מלמד שאם עשה את כולם בשגגת שבת רק חייב אחד. אפשר שהלשון משמע שתמיד רק חייב אחד, ואין דרך לחייב יותר מאחד. גם אפשר שאין בזה חידוש, ופשוט שאם עבר על כולם בשגגת שבת שחייב אחת. אבל, לא נראה שמסברה יהיה כ"כ פשוט.
* צז.
** ואלא הא גמיר –
עיין בגמ' (נ"ל שהוא בכריתות, קרוב לדף ה) שאומר שג"ש מעיקרי התורה. בכ"מ, בארנו א"ז על פי מה שכתוב בכ"מ שג"ש ככתוב בפירוש. יש לפרש את זה ג"כ עי"ז. אבל, יל"ד, שכאן תלוי בכמה בנ"א יודעים. א"כ, ג"ש עדיין קצת מכוסה, ונמצא שר"ע מגלה אותו יותר מן הכיסוי. א"כ, ק"ק למה הקשה גמ'. ותחשב.
** אלא מהיכא הוה –
לא אומר שלפי רבי יהודה בן בתירה בוודאי היה מ"ויעפילו," שאף ריב"ב מצדד שרבי עקיבא צודק. אלא, שואל מה הצד של ריב"ב שלא היה מקושש, אלא שעבר עבירה אחת. (יש להעיר שצריך עבירה שהיא יותר קלה ושעדיין ימות עליה. צריך להיות יותר קלה, שאם לא כן, לא מוציא לעז, ששם עליו עוון ומכסה אותו מעוון. יש לדון בזה, שעדיין שם עליו עוון שלא עשה, אף שבזה מכסה עוון שעשה. (עיין ברש"י ד"ה מ"ויעפילו" שמשמע כמו שכתבנו.))
** תוך שלשה –
קשה, שרבא אומר שרק חייב אם נח על גב משהו.
* צז:
** רבי יהודה סבר אמרינן קלוטה –
וא"ת אם זהו המחלקת, למה אומר שהלך ארבע אמות ברשות הרבים. נראה שבא לחדש שאף שהלך ארבע אמות, והרחיק ממקום שרצה שינוח (שכל ארבע אמות נחשב מקום אחד), מחייב רבי יהודה, שבאמת נח שם.
** קלוטה –
ק"ק איך יהני קלוטה לעשות שנתקיימת מחשבתו. לכאו', כמו שיכול לברור איפה רוצה שינוח, כך יכול לברור איך רוצה שינוח. הרי, אם רוצה שינוח שם, מסתמא רוצה שינוח בהנחה ממשית שם, ולא בהנחת קלוטה כמי שהונחה, שזה רק דין, וזה לא עושה כלום לו. אז, ק"ק איך נאמר שנתקיים מחשבתו.
** אי להכא –
קשה למה לא משיב, כמו שאמר לעיל, שרבי יהודה סבר שקלוטה כמי שהונחה, ורצה שינוח בשני המקומות, והרי נח. אולי לא מסתבר שאדם ירצה הנחה בשני מקומות ברשות הרבים.
** הרי כתב שם –
יש לחלק, ששם עשה ממש מה שהיה עושה אילו היה משלים, אבל כאן, מה שנח לסוף ארבע אמות שונה ממה שהיה עושה אילו היה נעשה רצונו. אבל, עדיין מדמה אותם, כיון שנעשה חצי התוצאה.
שוב נראה לי שגמ' לקמן אומר החילוק שכתבתי.
** ואלה –
קשה, שאולי נפק"מ של המנין הוא להודיע לנו מה נחשב מלאכה ומה לא נחשב מלאכה, שכיון שידוע שיש רק שלושים ותשע מלאכות, נדע כמה דברים חשובים עד שהם מלאכות. ותחשב.
** קלוטה –
מעניין שיכול להיות שקלוטה כמי שהונחה ועדיין יש חיוב זריקה ברשות הרבים. הייתי חושב שייחשב כמו מהלך לבן עזאי, שכיון שבכל פסיעה מונח, אין חיוב ארבע אמות ברשות הרבים. אפשר לומר שגמ' חושב שאף שנחשב נח, אינו נח כדי לתת לו "מקום חדש," ואז עדיין חייב בארבע אמות ברה"ר (שענין ארבע אמות הוא להוציא אותו ממקום שלו, וכ"ז שלא נח באמצע עד שינתן לו "מקום" חדש, עדיין יחייב). אבל, מקושיית הירושלמי איך בן עזאי מוצא חיוב במוליך ארבע אמות לא משמע כן. אפשר לומר שבבלי, שלא מקשה כן, חולק על ירושלמי, אבל הרבה ראשונים מביאים קושיה ותירוץ של הירושלמי, ולא משמע שהבבלי חולק עליו.
** רה"י באמצע –
הביאור כאן הוא שחיוב העברת ארבע אמות הוא להוציא חפץ ממקום שלו. לכל חפץ יש מקום של ארבע אמות. אז, כשמוציא אותו ארבע אמות, חייב. וא"ת אם כן נמנה גם את הרה"י, ונחייב מיד, בסוף רה"י. וי"ל שלענין זה, כל רה"י נחשב מקום אחד. כמו שלמשל בעירובי תחומין כל העיר נחשב אחד, ולא נכנס לחשבון אלפיים אמה, כך כל רה"י נחשב אחד, ולא נכנס לחשבון ארבע אמות. ותחשב.
אבל, לא כל כך פשוט לי למה זה יהיה כן. הייתי חושב שענין ארבע אמות הוא שזה מקום שבדר"כ משתמש בחפץ. אם כן, איני מבין ל"ל נכניס את הרה"י לחשבון הארבע אמות. ותחשב.
* צח.
** רש"י ד"ה רשויות –
עיין ברש"י. יש להעיר שרבי יוסי מדבר בציור מאד שונה. שם, מצטרפים מה שמוציא לרשות זה עם מה שמוציא לרשות אחר לעשות שיעור חפץ שמוציא. כאן, מצטרף שיעור שהלך עם שיעור שהלך לעשות שהלך ארבע אמות. (אולי זה יהיה קצת יותר קל להבין אם נניח שענין הוצאת ארבע אמות אינו שרק אז נחשב שיצא מ"מקום" שלו, אלא שצריך שהלך "ריחוק חשוב," ורק ארבע אמות חשוב. ותחשב.
* צט:
** רש"י ד"ה מוקף לכרמלית -
לכאו’, דין זה יהיה ג"כ אם אינו מוקף לדירה והיא גדולה מבית סאתים, שאז הוא רה"י מן התורה, אלא שרש"י סובר שלא מסתבר שמדובר בזה, שלמה לו לאדם לעשות מחיצה כזו שלא מוסיף לו היתר. ותחשב.
* ק.
** מלאה פירות -
לכאו’, הענין הוא שכיון שיש בו פירות, אין המחיצות מהנות כ"כ למה שיתן בו מכאן ולהלאה, ולכן, לענין אותם הדברים, לא יכול להיחשב רשות היחיד.
** רבא -
מן הגמ’ יוצא שרבא מודה שאם נאחז באויר שנח אם הוא בתוך שלשה, ולא צריך ממש שיעמוד ע"ג משהו. לכאו’, יוצא מזה שכשהוא ע"ג משהו, לא צריך שיעמוד, ואף אם הולך על משהו, נחשב שנח.
כן יוצא מרש"י, אבל לא הבנתי פי’ הסוגיה כ"כ. לפי רש"י, נראה שגמ’ מביא ראיה לרבא מרבי יוחנן, ושוב דוחה שלא רואים כרבא משם. איני מבין מהו הדיחוי. נראה שלולי רש"י, אפשר שמקשה מרבי יוחנן, שרואים שמה שנח באויר מהני (אלא שלשון הקושיה לא משמע כן), ודוחה שזה רק שם במתגלגל, שלא הולך מכוחו עוד, אלא רק מכוח הרוח, ולכן עומד ליפול. אבל, מה שהולך מכוח הרוח צריך לנוח ע"ג משהו. ותחשב.
* ק:
** לאפסועי –
כנראה, כיון שהוא פחות מארבע אמות, יש בני אדם שמפסיעים אותו. יש לציין למה שאומר הירושלמי בביאור שיטת בן עזאי, שמקשה איך יכול לחייב על הולכת ארבע אמות ברה"ר, שבוודאי יפסע, ומתרץ שהוא כשקופץ. נמצא ג"כ שלפעמים בני אדם קופצים ארבע אמות. (כמובן, שם הוא קצת יותר מכאן, שכאן רק קופץ על פחות מארבע אמות.)
** רש"י ד"ה אבל היכא -
עיין בלשון רש"י, שכ’, “תניא" על משנה שלנו.
* קא.
** רש"י ד"ה אבל לא מן הים -
נמצא שרש"י מתיר לטלטל מכרמלית לרה"י, אם מוליך למעלה מי’. זה קולא גדולה, שרוב תשמישים שלנו הם למעלה מעשרה. אבל, יש לדון אם קולא זו נוהג גם בהולכת ארבע אמות. (אם יכולים להקל על זה, לכאו’, זה יהיה קולא גדולה בעירוב, שאין כ"כ צורך לו, ברוב פעמים.)
אין זה מוכח מן הגמ’, שיש לומר שמה שגובהו פחות מעשרה טפחים אינו דווקא, ובא לומר שאף שאין גובהו עשרה טפחים, עדיין הוא רשות היחיד, ואין מטלטלים מן הכרמלית לתוכו.
* קב.
** נזכר -
נמצא ששוגג בתחילה, אף שא"א לו להעמידה, רק חייב חטאת אם הוא שוגג גם בסוף. לכאו’, מוכרח מזה שענין שוגג אינו רק שיש עליו תביעה במה שלא זכר, ושבא מתביעה זו עבירה, שאז מה לי אם זכר באמצע. אלא, צריך לומר ששגגתו גם משנה את העבירה. (היה אפשר לומר שאם זכר, מסתמא לא רוצה בעבירה, ולכן, בשעת עבירה לא מיוחס לו. אבל, אז כשאומר שנזכר צ"ל שר"ל שנזכר ונתחרט. לא משמע כן מן הגמ’, שמדמה אותו לציורים שיכול לעכב אותו. ותחשב.)
עדיין, מניח גמ’ שאין הילוך שני אמות באמצע במזיד יכולים לפטור אותו. ותחשב.
* קג.
** דחבריה -
נראה שאולי אין זה ראיה לשיטת הערוך שאין חייבים על פסק רישא דלא ניחא ליה, שאולי ענין הוא שכאן אין שיעור מוחלק, אלא כדי שיהיה השיעור כל שהוא, צריך שירצה בתיקון השדה. אז, כיון שהוא של חבירו, ולא רוצה בתיקון השדה, פטור מטעם חצי שיעור.
אבל, צריך לעיין בשקלא וטריא של הגמרא לפי זה. ותחשב.
** בכל לשון -
ממה שלא אמר "בין בשני לשונות,” משמע ששניהם צריכים להיות לשון אחד. ותחשב.
** אטר יד -
וא"ת למה לא אומרים שבטל דעתו לשאר בני אדם. נראה שלש תירוצים:
1. אפשר לומר שיש הרבה בני אדם שהם אטרים, ואז לא בטלים. יש לדון בזה, שלמס’ גמ’ מדובר במי ששולט בשתי ידיו. זה לא מצוי. אבל, עדיין יש לומר שכיון שיש הרבה ששולטים ביד ימין, לא בטל דעתו ליד ימין, וכיון שיש הרבה ששולטים ביד שמאל, שניהם נחשבים דרכו.
2. אפשר שכיון שיש לו טעם טוב במה שמשתמש באותו יד – ואף האחרים היו משתמשים באותו היד אילו היה כן להם – לא בטל דעתו.
3. אולי שמאל שלו נחשב ימין של שאר העולם, כמו שמשמע מלשון הגמ’, והוא שבהגדרת מעשיו, לא אומרים ש"הוציא בשמאל,” אלא אומרים ש"הוציא ביד חזקה.” אבל, יש לדון למה לא נאמר שהוא יד שמאל, כיון שמצאנו חילוקים אף לדין בין יד שמאל ששולט בו ליד ימין.
* קד.
** בימי יהושע בן נון -
נראה שנקט יהושע מפני שזה מראה החידוש הכי גדול. בכל דור שכחו תורה, ואז, כמובן, בדורו של יהושע, ידעו החלק הכי גדול של תורה. וא"ת ל"ל נקט שבדורו של משה לא נודע. וי"ל שאז היה כה"ת כולה נודע, ואז בוודאי היה גם זה נודע. וא"ת הרי גם בימי יהושע, כל מה שנשכח חזר להם, כמו שאומר גמ’ בתמורה. וי"ל שאחרי זה שכחו מעט. ותחשב. גם אפשר שרק ההלכות ששכחו חזרו להם.
אבל, דע שכל זה מניח ש"לא איתמר כוותיהו" רצה לומר שלא נודעו בימי יהושע בן נון. אבל, גם אפשר שרצה לומר שנודע, אבל לא נאמר. אז, יש לדון למה נקט דור של יהושע בדווקא.
גם יש לעיין בביאור מילת "כוותיהו,” שמשמע שלא ר"ל שאלו לא נודע, אלא דבר שהוא כ"כ חשוב כאלו לא נאמר. צריך לעיין בזה.
** שכן דרכו -
יש לדון מתי אומר שהוא מפני שכן דרכו, ומתי אומר שמלמד לנו שכן יהיה דרכו (שבדל"ת אומר שמלמד לנו שיהיה דרכו כן).
** מהדר אפיה -
עיין ברש"י. רצה לומר, הפנים של הרי"ש, שהוא מה שמביט אל מה שבא לאחריו, ולא מה שכבר עבר ובא לפניו, אינו לקוף. וא"ת גם אם היה הקו"ף אחרי הרי"ש, היה הפנים של קוף כלפי שי"ן, ולא כלפי רי"ש. וי"ל שאז היה עכ"פ רי"ש פונה לו, ולא רצה שיהיה אף יכול לחזור לאחוריו ולראות את הרשע. ותחשב.
* קד:
** הוציא כשפים –
ק"ק ל"ל אומר שאין לומדים משם, שרק עשה כן כדי שלא יכירו בו. היה אפשר לפרש שזהו מש"א, שגופא עשה כן מפני שהוא שטות, ואין לומדים משטות. אבל, לא נראה כן מרש"י, שנראה שמפרש שהוא היה עסוק בדבר של שטות, ואין ללמוד ממה שעושה אדם כשהוא עסוק בדבר שטות, שרואים שיש הרחק, בענין אותו מעשה, בינו לבין שאר בני אדם.
* קה.
** נמרצת -
לכאו’, רצה לומר ששמעי קרא לו, “נואף, מואבי….” נמצא ש"קללה" כאן אינו שמקלל שיבוא לו דברים רעים, אלא שמגנה אותו, ואומר שרע הוא.
** רש"י ד"ה אחד שחרית -
מעניין שכיון שהיה שהות בינתיים להבין, ולא הבין, נחשב שגגה חדשה, והעלם חדש. ותחשב.
* קה:
** לעולם במת דידיה -
משמע שדיון הגמרא הוא באיזה ציור מדבר המשנה. אבל, עיין ברש"י, שמשמע שהדיון הוא בפירוש "מת שלו,” אלא שממילא דן באם במשנה מדובר במת שלו. ותחשב.
** ואי חכם -
וא"ת למה מקשה כן, ולמה מצדד שהוא חכם. וי"ל שרק מצדד כן כדי להשמיע לנו ההלכה (שצ"ל שאינו חכם). גם י"ל שמצדד כן ממה שמדובר במת שכ"כ דואג עליו עד שקורע. אז, מתסבר לומר שהמת היה חכם או שהיה שם בשעת המיתה. ותחשב.
* קו:
** והא בית מקורה –
רש"י פי’ שלא ניצוד בבית, כיון שייצא מן החלונות. אז, ק"ק ל"ל מוקים אותו בביבר מקורה שאין בו חלונות. אולי בהכרח יהיו שם חלונות, שצריכים אוויר.
** זמורתא -
לכאו’, אז יוצא שבקטע זה – “הלכה כרשב"ג" – יש מחלקת אמוראים אם נחשב חלק מתורה. אבל, כיון שלומד עליו מחלקת זה, יוצא שלכ"ע הוא חלק מתורה, שאף אם אינו חלק מתורת "הלכה כמי,” בוודאי הוא חלק מתורת "האם יש לומר דברים פשוטים.”
** מקלחות -
החידוש בזה הוא שאף שכל אחד אינו ניצוד ועומד, שאולי הוא יברח, לא קשה למצוא אחד.
נראה שזה תלוי במה שיש לדון (ונראה שאולי על זה גם כן יכולים לתלות דין צידת דבר שאין דרכו ליצוד) אם שינוי החשוב של צידה הוא שיש לו בהמה ניצודה, והוא שינוי בו, או שהבהמה ניצודה, והוא שינוי בבהמה. ותחשב.
** רש"י ד"ה השתא דאתית-
לולי רש"י, אפשר לפרש שרצה לומר שכיון שרואים שיש דברים השייכים לזה שלא כתובים במשנה, יכולים לפרש כן גם בסתירה בבהמה. ותו"ת.
* קח.
** לא לוקמיה ליה בני -
אבל, ראינו שהוקמו לו בנות. נמצא שקללה זו על "בני" לא היה על בנות. אולי רב רק כיוון ל"בני" או, אולי, כיון שיש שני פירושים ל"בני" – בנים או זרע – הולכים אחרי היותר קל בקללה.
* קח:
** דלא תימא צר עין -
לא רצה שיחשוב כן כיון שאסור לחשוד את חברו בחנם. גם, אם יחשוב שלא שלח לו כיון שהוא צר עין, לא יאמין שבאמת אמר שמואל שאין צורך להם, ולא יאמין במימרת שמואל. אז, הוצרך למסור לו כדי שישמע את מה שאמר לו בשם שמואל. ותחשב.
** אלא חדא שמיעא -
גם אפשר ששמע את שניהם מרבו, אלא שאחד גם לוי אמר, ומי שהביא אותו שמע רק מלוי, ולא מאבוה דשמואל.
* קט.
** רש"י ד"ה מעלה –
רש"י מפרש שיד לפי טבעת הוא תמיד, ולא רק קודם נטילה, והוא רק כשמשתמש בה תמיד. אם כן, יש מקום לומר שכל האיסורין האלו הם רק כשמתמש בה תמיד. אבל, אי אפשר שממש כולם תמיד, שהרי אסור לגעת באמה אפילו באקראי. אלא, צריך לומר שיש מהם שהם תמיד ויש שהם באקראי, ויש לדון איך לחלק. ותחשב.
* קיב:
** מהו דתימא מבטל לה -
בכל כעין זה, יש לדון אם ר"ל שכיון שיש צד שיבטל אותה, נחשב (או מדאו’ או מדרבנן) קשר של קייימא, ויהיה אסור, או שנחוש שיבטל אותו, וכשמבטל אותו, נמצא שעבר על איסור, שנמצא קשר קבוע. אז, מחשש האיסור, אסור לקשור. ותו"ת.
* קיג.
** מלילי שבת לשבת -
משמע שהיו נוהגים לישון ביום השבת. אבל, יש לדחות שרצה לומר שיכולים להציע את המטות מלילי שבת לשבת כדי שיהיו נאים בשבת, ולא כדי שישן בהם בשבת, ולא למוצאי שבת, שאם לא מכוון שיהיו נאים בשבת, לא מותר לעשות בשביל שיישן במוצאי שבת.
* קיג:
** וכי בחול -
קשה איך מפרש ש"לא יהיה הילוכך של שבת כשל חול" אומר שלא ללכת בפסיעה גסה בשבת, שאף בחול אין לעשות כן, ואז הילוך של שבת יהיה כהילוך של חול. ותחשב.
** דבר חכמה -
יוצא שרוב העניים אף לא ידעו הלכות לקט, אף שאומנתם היתה בו.
** בימי דוד ובימי שלמה -
אפשר שכללם באחד כיון שהיו זה מיד אחר זה. יותר מזה, אפשר שבימי שלמה זכו רק מזכות דוד. אז, נכללים ביחד.
** רמז -
ממשע שהוא כיוון לרמוז כך. יש לדון אם רות קיבלה את הרמז. אם לא קיבלה, ק"ק למה רימז לה.
* קטו.
** רש"י ד"ה בין שאין קוראים -
עיין ביומא (יח:) וברש"י ד"ה באיוב ובעזרא.
* קיח:
** ולכבוד שבת עשאו -
משמע שכדי להיות עונג שבת, צריך להיות שנעשה לכבוד. מחודש שכוונתו שייכת לזה, וגם מחודש שכוונתו בשעת העשייה תהיה שייכת לזה, ולא כוונתו שבשעת אכילה. ותחשב.
** ולכבוד שבת -
עיין במה שהערנו בצורך לכוונה. יש לדון אם צריך כוונה רק בדבר קטן או גם בדבר גדול.
** לדידי חשדן -
אפשר שמכוון לסיפור שמבאר רש"י במש"א גמ’ שלא לשבת על מטה ארמית, ואפשר שמכוון למה שטענו עליו שהלוה בריבית (אף ששם לא חשדו שעשה דבר שלא עשה, אלא שטענו שמה שעשה היה איסור).
** מאי טעמא קראו לך -
יש לדון אם הכירו בו שהקפיד על כך, ולכן קרא אותו רבינו הקדוש (וא"ת אם כן היו להם לשואלים לדעת. וי"ל שמתחילה ידעו, וקראו לו, ואח"כ נשתכח), או שעל זכות זה נקרא רבינו הקדוש. ותחשב.
** שלא הכניס ידו -
נמצא שרבי לא ידע למה נקרא כן, שחשב שהיה מפני שלא הסתכל במילה שלו, אבל טעה. גם אפשר שהיה מחמת הצירוף. גם אפשר ש"הסתכלתי" רצה לומר שלא הסתכל ידיו, כמו שאומר גמ’ בברכות. אבל, דע ששם לא שווה בדיוק למה שאומר כאן.
** ולא נחית -
רצה לומר, רצה לתקן אותו מיד, ואז תקן אותו שם, על הסולם.
** רש"י ד"ה ממתי מחולי מעיים -
לפי פירוש רש"י, כשאמר רבי יוסי שרצה למות בחולי מעיים, כיוון לסיבה, והוא שמיתת חולי מעיים דבר טוב. (אגב, עיין בברכות שפי’ שיתפלל אדם לעת מצא, שזה מיתה קלה. לכאו’, זה סותר גמ’ כאן. אבל, עיין שם, שמחלקת היא.) לולי רש"י, יש לומר שהוא סימן, והוא שרוצה להיות מן המתים בחולי מעיים, דהיינו מתלמידי חכמים וצדיקים המתים בחולי מעיים. ותחשב.
** רש"י ד"ה לא נסתכלתי -
רש"י פי’ שהוא משום צניעות. גם היה אפשר לפרש שהוא כיון שחוששים להרהורים, כמו איסור לגעת באמתו. ותחשב.
* קיט.
** בני ר"פ בר אבא -
יש להעיר שרפב"א היה שמן. זה מתאים עם מה שאומרים כאן בניו, שהיו רגילים בבשר ויין.
* קכא.
** חוששני-
עיין ברש"י שפי’ שר"ל שחושש אני לומר שחייב חטאת. צריך ביאור מה זה אומר. לכאו’, לא רצה לומר שהוא מסופק אם הוא חייב חטאת, ומחשש זה, מחייב אותו, שאין מביאים חטאת על הספק. צריך לומר שרק ר"ל שחושש ונוטה אני לומר שחייב חטאת, אבל לא יקריב כיון שהוא רק חשש. אבל, לשון רש"י לא משמע כן. ותחשב.
* קכא:
** נהרות -
לכאו’, היה אפשר לחלק ששם היו בעולם, משא"כ צואה, שלא היתה בעולם (וקרה לו שינוי גדול). ממשע שלעשות שדבר מוקצה, כיון שנולד, לא שייך מה שלא היה שם לחול עליו דין מוכן, אלא הענין הוא רק שכיון שאינו שם, לא חושב עליו, ומקצה אותו. עיין בראשונים בתחילת ביצה, שמשמע כן. אבל, עיין בגמ’ בעירובין גבי איך מטר נישא בעננים, שלא משמע כן. ותחשב.
** ותיפוק ליה -
יש לדון אם זה קשה לכ"ע או רק לרב חנן בר רבא (שיש לדון אם יכולים לצדד שרק צואת תרנגולים, ולא צואת קטן, נחשב גרף של רעי).
** אגב מנא -
יש לדון למה יהיה מותר רק אגב כלי. אולי צריכים צירוף קולות (מה שהוא גרף של רעי, ומה שהוא בעיקר מוליך את הכלי) ואולי ההיתר הוא רק שבטל לכלי, כיון שלא חשוב. ותחשב.
* קכב.
** אדעתא דרובא -
נראה שהענין הוא שמחממים אותו על דעת "בני העיר.” כשקובעים אם "בני העיר" הם יהודים או גויים, הולכים אחרי רוב. הגמ’ אומר את זה בקיצור כשאומר שעושה כן "אדעתא דרובא.”
** כבש -
ק"ק ל"ל רק התחיל בכבש. צריך לפרש שמתחילה התנא לא שמע כבש, ואז שנה נר. כשששמע כבש, שנה אותו מפני הסיפור.
** כבש לאחד -
זה קצת מחודש, שהייתי אומר שעושה כבש יותר גדול כיון שיש יותר בני אדם. נראה שר"ל שמה שיש קצת יהודים לא משנה גודל הכבש. ותחשב.
* קכז:
** נעלתו –
יש לדון למה לא חשש ליייחוד. צריך לומר שהצורך לשמור דברי ממשלה יותר חשוב מאיסור ייחוד. (יש לדון אם היתה פנויה, שאז אסור מדרבנן) או אשת איש (שאז לכאו' אסור מדאו'). ותחשב.
* קכח.
** שלא ימלול בכלי הרבה -
לכאו', אז אומר שני קולות – שיכול למלול בכלי, ובלבד שאינו הרבה, ושיכול למלול הרבה, ובלבד שאינו בכלי. אבל, קטימה מותרת רק ביד (אבל, משמע ששם מותר אפילו הרבה).
** מולל בראשי אצבעות –
כמו לעיל, יוצא ממה שאומר, "ובלבד...," שני קולות, שיכול למלול ביד, ובלבד שאינו הרבה, ושיכול למלול הרבה, ובלבד שאינו ביד. אם כן, כשאומר ש"מולל בראשי אצבעות," אינו כל כך דווקא, שגם יכול למלול ביד. אבל, נקט מלילה בראשי אצבעות כיון שאז מותר אפילו הרבה. (אבל, יש לדון למה לא עשה כן בשיטת תנא קמא.)
* קכח:
** צער בעלי חיים דאו' –
נמצא שענין צער בעלי חיים אינו רק כשהוא מצער את הבעל חי, אלא אף כשמניח אותו ליצער. (יש לדון אם שם יש גם איסור צער בעלי חיים, או שיש רק ענין של צער בעלי חיים.
גם יש לדון אם הוא רע כיון שהוא מניח לבהמה להיות בצער או כיון שהבהמה הוא בצער.
** מביאה בכלי דכל שאפשר לשנויי-
הלשון קצת קשה, שלכאו', כולם מודים שמקריב בשער כיון ש"כל דאפשר לשנויי משנינן." אז, ק"ק למה אומר אותו רק בסוף דברי רב אשי.
אפשר לפרש שלרב אשי קשה שאינו שינוי מעליא, שאין התוצאה שונה כל כך[fn:1]. (אילו היה מביא אותו בשער שלו, היה התוצאה שונה, שהיה בא באופן שעוד צריך ליסחט, וגם היה מעורב עם דברים אחרים, וגם היה עושה רושם בשער. אבל, כיון שמביא כלי בשער, אין שינוי כלל.) אז, מפרש שעדיין כל מה שיכול לשנות ישנה. ותחשב.
* קכט.
** ספק נפשות להקל –
יש סיפור ידוע על גר"ח, ששאלו לו למה הוא, המחמיר, תמיד מיקל בשבת, שתמיד חשש לפקוח נפש. השיב להם שהוא לא מיקל, אלא הוא מחמיר בפיקוח נפש.
אבל, לשון גמרא מורה נגד מה שאמר, שכנראה זה נקרא "מיקל," ולא "מחמיר." (ענין הסיפור עדיין אמת, אבל הלשון אינו אמת. ותו"ת.)
** עד מתי –
יש לדון אם ר"ל שאם הקבר עדיין פתוח, רק נחשב פתיחת הקבר עד אז, או שאף אם סגור, נחשב פתוח עד אז, או שמניחים שנסתם אז. ותחשב.
** ל' אפילו-
רש"י פי' שמדבר בשבעה עד שלושים. אם כן, קשה למה אמר שהוא עד שלושים, שכך הוא כל ימיה, שאף אם אומרת שמחמת לידה היא בסכנה לא שומעים לה, שאינה בכלל יולדת. ותחשב.
** רש"י אמרו נחמן –
רש"י משמע שלא שקרו ואמרו שרב נחמן בא לאכול, אלא שאמרו לנשותיהם להכין סעודה כאילו רב נחמן בא להם. זה מבאר למה זה עבד יותר מפעם אחת (שמסתמא לא היה עושה כן להועיל רק פעם אחת). אבל, אף בלי זה, יש לומר שאמר ש"אולי יבוא נחמן."
* קכט:
** רש"י שב"ד של מעלה ושל מטה –
רש"י מתחיל וכ' ש"אדם נידון בכל יום." לכאו', זה פלא, שגמ' ורש"י בהמשך אומר שלא בכל יום אדם נידון, אלא רק בשני וחמישי. אפשר לומר שיש דין קטן ודין גדול (ותלוי במי דן אותו או בכמה קבוע הוא הפסק) אבל אם כן קשה למה מביא אותו כאן.
אלא, נראה שרש"י רק בא לומר שאין יום הדין קבוע של ראש השנה או כדומה, אלא הוא כל יום ויום (שכך הוא הענין של הגמרא שממנו מביא רש"י שיטה זו). אז, כשאומר "כל יום," אפשר שרצה לומר שני וחמישי, שהוא כל יום כנגד ראש השנה, לא רק מפני שהוא יותר מצוי מהם, אלא מפני שהם ימים רגילים, ולא ימים מיוחדים. ותחשב.
גם אפשר לבאר שבעצם הוא כל יום ויום, וכך היה קודם שעזרא תקן שישבו בדין בשני וחמישי, שלא היה יום קבוע לדין. אבל, אחרי שקבעו שישבו בשני וחמישי, גם ב"ד של מעלה עשו כן. אם כן, רש"י אומר שבעצם יושבים בכל יום, אלא שאחרי תקנת עזרא יושבים בשני וחמישי. (יש להעיר שמי שאומר שנידונים בכל יום אמר כן מאד אחרי תקנת עזרא, שזהו שיטת תנא. אבל, אין זה כל כך קשה, שיש לומר בקל שאומר "עיקר הדין," קודם התקנה.)
יש להעיר שלפי צד זה, צריך לומר שדין של מטה הוא הסיבה לדין של מעלה, ולא שהוא רק סימן לו (אולי שהם נגרמים מדבר שווה או שדין של מעלה גורם דין של מטה (שאחריו תקן עזרא)). ותחשב.
** שומר פתאים ה' –
אז, רואים מכאן שאם יש שני דברים בסכנה אחת, ופתאים דשו באחד עד שאומרים עליו "שומר פתאים ה'," עדיין לא הותר השני, ועדיין יש בו סכנה.
על פי זה, היה נראה לומר שאף כשר"מ כ' שלעשן יש בו משום "שומר פתאים ה'" (ודע שמסתמא רב משה לא ידע את המציאות בברור), לא הותר לעשות וויי"פ (אלא שאולי כבר היום יכולים לומר גם על ווי"פ שדשו בה רבים). ותחשב. ויש לדון כמה דומה צריכים להיות.
* קל.
** שאפשר לעשותה –
אפשרד לבאר שיהיה יותר טוב אילו עשה אותה מלאכה בשבת, שהרי למה ייגרע בדבר שלא היה יכול לעשות בערב שבת. אלא, כיון שלא יכול לעשות אותו, בדרך כלל, יעשה אותו בערב שבת, ואז לא רק שימול, גם לא יחלל את השבת כל כך. (זה מניח שעכ"פ למכשירי מצוות מילה, שבת דחויה, ולא הותרה.)
** אפילו מכוסה –
ק"ק למה זה פשוט, שאפשר לומר שעדיין יש חשד, שלא הכל ישאלו את שני העדים מה היה עושה, אלא יניחו שהוציא באיסור. ותחשב. אפשר שענין חשד הוא לשמור את החושדים אותו, שלא רוצים שיחשדו אותו בשקר. אז, אם חושדים אותו בלי בדיקת עדים, הם גרמו לעצמם, ולא שומרים אותם.
** כרבי יוסי הגלילי-
איני מבין למה החשש הוא שדורש כריה"ג, ושלא גזר לאסור מדרבנן; לכאו', גם יש לחוש שדרש כרבי עקיבא ושלא גזר מדרבנן. אפשר שאינו דווקא. יהיה טוב אם נוכל לעיין בדרשות ולראות שאם נדרוש כדרשת רבי עקיבא יהיה יותר מסתבר שגזרו רבנן מאם נדרוש כרבי יוסי הגלילי.
** מילה –
משמע שאפילו מילה דוחה פק"נ בשעת השמד, אף שיכול להמתין (ואולי יבטל השמד). אבל, יש לדחות שרק מותר לבחור למול במקום פק"נ, ולא שחייב למות. ותחשב.
* קל:
** מהאי רישא –
צריך ביאור מה קרה. לכאו', היה בבית, והביא אותו לבית. אם כן, קשה איך הביא אותו גם אם מותר, שבוודאי אסור להוציא מן הבית למבוי. ותחשב.
* קלא.
** מגזרה שווה –
קצת קשה למה לא רק אמר גמ' שבוודאי לא סובר שהוא כן בכל מצווה, שאי אפשר ללמוד ממילה. אולי לא כל כך פשוט שהדחייה נכונה. גם אפשר לומר שלא פשוט שהמקור הוא ממילה, שאולי הוא כלל בתורה (אולי, אז, אף לא צריכים פסוק לו).
** מגזרה שווה –
יש להעיר שאין זה ראיה ברורה, שיש לומר שאחרי הגזרה שווה לומד לכל מקום מצד השווה. ותחשב. נראה שרק בא להוציא מן הצד שיש לימוד כללי על כל התורה כולה. גם יש לומר שידע פירכא לצד השווה. ותחשב.
* קלא:
** רש"י אילימא בטלטול –
רש"י כ' שא"א שמתיר את זה שעדיין בזמן מתן תורה לא היה איסור. וא"ת אף אם היה איסור, היה דרבנן, ולא צריכים קרא לומר שאיסור תורה דוחה אותה. אין זה נכון, שהרבה פעמים מצאנו שרבנן דחו דין תורה בשב ואל תעשה. אז, גם כאן היה יכול להיות שהעמידו את דבריהם. ותחשב.
אבל, דע שאם נאמר ככלל של הרבה ראשונים, שלא גזרו על דבר המפורש בקרא להתיר, ק"ק לל"א שקרא מתיר, כדי שאף אם יגזרו, לא יהיו יכולים להעמיד דבריהם נגד המצווה.
** שכן טעון ארבע מינים –
יש בזה שני ענינים – שצריך ארבע המינים, ושיכול להיות רק ארבע מינים. ותחשב.
* קלב.
** הו"א שביעי –
כנראה, שני הפסוקים בפני עצמם (רצה לומר, אילו לא היה השני) היה ממעט שביעי. ותו"ת.
* קלג.
** לבתר דשמעיה –
וא"ת הרי יש בזה שני מחלקתים אביי ורבא בזה. יש לומר שבשניהם אביי אמר תשובתו קודם ששמע תשובת רבא לראשון. גם יש לומר שרק אחרי קצת זמן חשב על מש"א רבא וחזר לו. ותחשב.
** דליכא אחר –
נמצא שענין א"א לקיים את שניהם תלוי במצב, ולא אם, במצבים אחרים, יכולים לקיים רק אחד מהם. אבל, כמובן צריך לדון כמה דומה צ"ל אותם מצבים. ותחשב.
** עד בוקר –
בפשטות, כל אלו מלמדים שדבר שלא בזמנו לא דוחה י"ט. אבל, אם מלמד איסור שריפת קדשים בי"ט, אף בלי איסור, כמו שמשמע מגמ' בשבת, לא יכולים לומר כן. אפשר שמביא מקצת מאלו אגב המשיבים (שתשובת רב אשי בוודאי מתרץ). ותחשב.
* קלג:
** מאן תנא –
הסוגיה קשה לפרש, שמחלוקות התנאים שמביא הם, לכאו', בענינים שונים. נראה שידע שהמשנה כתנא אחד (אולי ידע כן כיון שבלי זה, מה שאמר יהיה פשוט. אבל, יש לדון, שזה רק הוכחה שיש הו"א לחלוק, ולא שיש תנא החולק.), ואז מחפש איזה תנא הוא זה. גם לא ידע באיזה נקודה יש מחלקת, ואז גם מחפש את זה. ותחשב.
** תמיד –
לכאו', הסיבה שזה נוגע לכאן הוא שרבי יוסי מחשיב את כולו למעשה אחד, אולי מפני שקרו ביום אחד, או – וזה יותר נראה – מפני שזה ממשיך את זה. יש להעיר שאז לא כל כך פשוט איך גמ' אומר בסוף מנחות שלרבי יוסי לימוד תמיד ר"ל בתחילה ובסוף היום, שלא כל כך פשוט שזה ממשיך את זה, וגם לא פשוט שמה שהם נחשבים מעשה אחד עושה שנחשב שלמד כל היום. ותחשב.
* קלד.
** רש"י מינשבא –
דופק –
איני ידוע כוונת רש"י, שלכאו' גמ' מדבר בנשימה, ורש"י מדבר בדפיקת לב. ותחשב.
* קלד:
** אלא אי אמרת –
עיין במה שכ' רש"י. גם יש לומר שאז לא היה לו להזכיר יום שלישי, שרק בזה אמר תנא קמא שיכולים לזלף. ותחשב.
* קלה.
** שאין אמו –
הייתי אומר שאינה טמאה, כיון שהיתה גויה, ואין גויים טמאים. אבל, עיין ברש"י, שכ' שלא נהגו טומאה, שמשמע שהיו טמאים, ורק שלא נהגו בטומאה. מעניין שהיו טמאים, וגם מעניין שמה שלא נהגו טומאה מספיק לעשות שאין להם דין זה. ותחשב.
* קלה:
** הא בהא תליא –
אז, יש לדון למה לא חלקו בנימול לשמונה. נראה שגם יש חידוש בזה, שהו"א שביום ראשון דוחה שבת. ותחשב.
** רש"י מימהל-
כנראה, רש"י סובר שבקושיית גמ' לא ידע שיש ילד שכלו לו חדשיו. אבל, לולי רש"י, היה אפשר לומרש רק ידע שרוב קטנים לא ידוע שנגמרו שנותיהם, ואז מקשה איך מילתם דוחה שבת. ותחשב.
* קלז.
** לשבעה –
וא"ת רק ספק תשעה הוא. אולי כן ר"ל. גם אפשר שכלפי שמיא גליא, לפעמים, שהוא, באמת, תשעה. זה רק אפשר אם נאמר שביה"ש הוא ספק, ולא חצי יום וחצי לילה שיש בו דין ספק. אבל, אם נאמר כצד שני, הוא חצי תשעה ימים וחצי שמונה ימים, ואולי על שם זה נקרא תשעה ימים.
** מפני מראית-
זה קצת מחודש, שבדר"כ אינו נראה ערום. ותו"ת.
* קלז:
** רש"י רוב גובהה –
לשון רש"י – "אפילו רוב גובהה" – מעניין, שמשמע שאם הוא רוב היקפו גם כן מעכב. ותחשב.
** רש"י איכא ביניהו –
עיין במה שכ'. גם היה אפשר לפרש להיפך, ש"נראה ואינו נראה" הוא בכלל נראה ובכלל אינו נראה, כמו שהלשון עצמו משמע.
** שאילמלא –
קצת צריך ביאור ל"ל מברכים כן בשל תינוק.
* קלח.
** רש"י אבל מטה –
דלאו מידי –
יש לדון אם הענין הוא שהחפץ לא שינה כ"כ או שלא עשה לו מעשה חשוב. מרש"י משמע כשני. ותחשב.
** מותר לנטותו –
רש"י מבאר למה מותר. עיין בסוכה, שדורש מקרא שגם כותל נקרא מסכך. צריך לומר שעדיין לא נקרא אהל. ותחשב.
* קלח:
** ולא אמרן –
עיין ברש"י שמפרש שזה בכל צד. נראה שהענין הוא שכיון שיש קרן, לא מצרפים אותו לאהל. זה מבאר איך יכול להיות מטה כל כך קצר, והוא שאינה כל כך קצרה, אלא שיש הרבה קרנות. ותחשב.
* קלט.
** במקום אחד –
לכאו', רצה לומר שיש מקום שיש בו הלכה ברורה, ויש מקום שיש בו משנה ברורה, אבל אינם במקום אחד. גם אפשר שאין מקום שיש בו הלכה ברורה של כל התורה במקום אחד, וכן במשנה ברורה.
** אף הן -
לכא', רואים שלא הקפידו לקדש ביין בשבת.
** אף הם –
וא"ת הניחא יוסף שתה, שידע שבאו אחיו. אבל, קשה למה הם שתו. ויש לומר ששתו מפני שחשו לנפשם (שימית אותם אם לא שתו, ובוודאי אם בארו למה לא שתו).
** אי חכימת -
יש לדון אם רצה לומר שאם אתה חכם ויודע את התשובה, תשלח להם, או שרצה לומר שדבר חכמה הוא לשלוח להם תשובה (ויש לדון למה).
* קלט:
** כלי טפח –
נמצא שיש איסור עשיית אהל בכלי. צריך ביאור למה איןז קורה כל זמן שנותן כיסוי על כלי. נראה שזה כעין מטה, שלא עושה כלום, כמו שפי' בתחילת הפרק.
** דמיחזי –
גמ' אומר שזה בעיה כיון שנראה כמשמרת. אבל, עיין ברש"י, שמשמע שהבעיה הוא שהוא משמרת. ותחשב.
** ניצוצות –
עיין ברש"י. גם יש לומר שהיה מביא רק הניצווצת, אבל לא היה נראה כבורר, שלא חשו שרצה הניצוצות, שהיה לו הרבה שכר.
* קמ.
** אימיה דאביי –
אז, כנראה, היה שומרת אותו אף אחרי שכבר גדל עד שהיה מקפיד על חומרות.
** דשתי –
יש לדון אם מקשה ששותה הרבה או שכיון ששותה כל יום, סובר שיזוק לו, אף ששתה רק מעט.
** מיחזי –
יש להעיר שלא רק לא היה יכול לפשוט, אלא באמת יש חילוק. ותו"ת.
* קמ:
** העומד באמצע –
אולי זה המקור להרחקת נדות שאין לשכב או אף לשבת במטת אשתו נדה.
** רש"י תא שמע –
עיין במה שפירש. גם יש לומר שרק חולקים לומר שלא נולים מלפניהם, אבל יכולים לגרוף. ותחשב.
* קמא.
** רבי יהודה אומר –
יש לדון אם רבי יהודה קאי על של בעל הבית או של כובס.
** טלטול –
משמע שטלטול על ידי דבר אחר וטלטול מן הצד שווים. אבל, שמעתי שלהלכה מחלקים ביניהם. צריך לומר שלפעמים טלטול על ידי דבר אחר ייחשב גם כן מן הצד, אם הוא משונה. אבל, יש לדון, שכאן לא נראה שייחשב משונה, ולא היה נראה להשוות אותם, אם לא נאמר שכל טלטול על ידי דבר אחר נחשב מן הצד, כיון שבדר"כ משתמשים דברים בעצמם. ותחשב.
** אי הכי כי קא נחית –
צריך ביאור מהו ה"אי הכי." נראה שבשני המקומות הוא רק חשש שיוצא. אז, מקשה שכיון שגלית שאתה חושש להוצאה בכרמלית, נחוש נמי גם לזה. ותחשב.
* קמז:
** דלהשתטף -
לכאו’, מניח הגמרא שכמו שיצטרך דבר ליבש אותו כשהוא רוחץ, כך יצטרך כשמשתטף. אז, ממה שנקט רחיצה, ולא שיתוף, רואים שלא היה יכול לשנות שיתוף בלשון דיעבד כמו רחיצה, כיון שאף בחמין, הוא מותר. ותחשב.
** הא רבי -
ואם תאמר, הרי סתם משנה אוסר. עיין בגמרא לקמן, שידחה שאינו סתם משנה.
** בן חכינאי -
אפשר לפרש שרצה לומר שמי ששנה אותו לא היה תנא כל כך חשוב. אז, לא שנה שם, להראות שאין השם מוסיף דבר, שמה שבן חכינאי סבר כן לא מוסיף שזה יותר מסתבר להיות נכון.
אבל, לא כל כך נראה שיוכל להיות שני סימנים מדבר אחד (מסתימות משנה). אז, לא נראה כל כך כצד זה.
גם עיין ברש"י, שכ’ שרבי יוחנן גרס בסוף המשנה "דברי בן חכינאי,” ואז בוודאי לא מפרש רש"י כמו שכתבנו. ותחשב.
** בלני נשים -
נמצא שבלבישת בלני נשים אין איסור של בגד אשה. ותחשב.
* קמט.
** קומות -
לכאו’, הטעם הוא משום "לא פלוג.” נמצא שמקשה מאיסור לאיסור (על כל פנים, באיסורי שבת), שכמו שנאמר לא פלוג כאן, נאמר לא פלוג שם (כיון שהדמיון הוא שווה). ותחשב.
** תנאי -
רצה לומר, חולקים במחלקת תנאים זה. מי שאמר טעם של "שמא ימחוק" אסר בלא פלוג מחמת טעם זה. כיון שנהג בהרבה מקומות, הזכיר אותו לטעם. ותחשב.
* קמט:
** נענש על ידי -
עיין בגמרא ברכות כעין זה (במי שרצה לקלל בשעת רוגז ה’).
** אינו טוב -
מעניין ש"אינו טוב" רצה לומר "רע.” אפשר לומר שאין הו"א שהוא טוב, ואז צריך לומר שכוונת "אינו טוב" הוא "רע.” ותחשב.
* קנ.
** ערוות -
בפשטות, הלימוד בא ממה שנאמר עליו שם "ערווה.” אבל, גם אפשר שהוא מפני שהם בשו מלראות אותו. אבל, יש לדון, שאפשר שהוא מפני שזה היה מצער את נוח. יש לדון, שאם לא יגידו לו, לא יידע. ותחשב. (וא"ת למה לא יהיה הראשון הוכחה. ויש לומר שלא תמיד משתמש תורה במילים במשמעות ההלכתי שלהם. ותחשב.)
** בראשו -
רש"י פי’ שהוא בראש הארי. גם אפשר שר"ל בראש נבוכנצר, כמין כובע.
* קנ:
** נזכר ששבת -
מעניין שחסיד ישכח ששבת היום.
** אם יש בורגנין -
יש לדון למה זה מותר, אם הוא מפני שהוא לא דיבר על דבר שהוא מוכרח להיות אסור או שממה שיש דרך להתיר אותו, נמצא שהוא לא דבר על נקודה האסורה. לא נראה כצד שני, שלא צריכים סימן לזה, שיכולים להוכיח איזה נקודה האסורה. ותחשב.
* קנא.
** להביא לו ארון -
עיין לעיל, שלא פירש כן. צריך ביאור.
** ימתין בכדי -
עיין בקושיית הגמרא. קשה, שלעיל כבר אמר שיהיה מותר כיון שספק הוא. נראה שבא לפרש אליבא דרב. ותו"ת.
* קנא:
** הרוצה שיעצים -
וא"ת מה רווח בזה. ויש לומר שרווח במה שמותר בשבת. יש לדון בזה. צריך לומר שאף שנוגע ברגל המת, לא משתמש בו, ואין בזה איסור מוקצה. גם צריך לומר שאף שממעשיו נעצמים העינים, אין זה נחשב טלטול מוקצה, שהוא בגרמא.
** תינוק… מחללים -
וא"ת למה לא אומר שמחללים גם על רשע. נראה שהחידוש הוא שאף שאין הטעם כל כך נוגע לתינוק, שלא ישמור שבת עד הרבה שנים, עדיין מחללים עליו את השבת. ותחשב.
** שני בני אדם -
קשה למה לי שני בני אדם, שאם דומים לבהמה, נופל עליהם ארי, ואם לא דומים לבהמה, אפילו באחד לא נופל ארי, כמש"א בהמשך הגמרא. ותחשב.
* קנב:
** טהרה -
מה שאומר שגופים שלנו מקבל את נשמות שלנו בטהרה משמע שאין ענין של גלגול. (עיין כעין זה רש"ש בב"מ.) אבל, אפשר שר"ל שהוא בטהרה נגד מה שיוצאים מן העולם. דחוק, שצדיק צריך לא רק לשמור, אלא אף לתקן, אם בכבר מלוכלך. יש לדון, שאולי תיקון קורה ממילא, כששומר.
* קנג:
** זורק כלאח"י -
יש לדון למה צריך לזרוק כאלחר יד, ולא יכול רק להניח כאחר יד. אפשר שאינו דווקא, ואה"נ שיכול לזרוק כאלחר יד. גם אפשר שעיקר המלאכה הוא מה שמביא מרשות לרשות, וזה קורה כדרכו, אם רק מניח שלא כדרכו. ותחשב.
** הסתר -
צריך ביאור, שלא הסתירו אותו, אלא גזרו שזה אסור. ותחשב.
* קנד:
** לוקים על לאו הניתן לאזהרת מיתת בית דין -
נראה שאפשר לבאר שהמחלקת מיוסד על מחלקת אם המלקות (או, אולי, כל עונש) בא על מה שעבר על הציווי או על מה שגרם סיבות רעות (ולשני, צריך לומר שכשנדחה, ה’ גם מסר פטור על העונש). ותחשב.
** תשמיש אילן -
יש לדון מהו תשמיש האילן:
א. מה שהאילן עושה סוכתו כשרה.
ב. מה שהוא "דר" באילן. דירתו חשובה כיון שבו יוצא מצוות סוכה. ותחשב. (כשיש ארבע מחיצות, ורק אחד אילן, לא נחשב שדר באילן, שלא מוסיף דבר חשוב לדירתו.)
* קנה:
** מזונותם -
יש לדון אם סבר החולק שגם אלו מזונותם עליך או שמותר אף אם אין מזונותם עליך (בצד שני, צריך לעיין במשנה בביצה שמשמע נגד זה). ראיית גמרא לא כל כך מובן אם נאמר כצד ראשון, וגם צריך ביאור איך נאמר שדבורים מזונותם עליו. ותחשב.
* קנו.
** עניש וקטל -
עיין לעיל, שבני עירו לא אהבו אותו, על שענש אותם כל כך.
* קנו:
** מהדרנא -
משמע שתלוי במזל, אלא שה’ משנה אותו.
** מאי עבדית -
משמע שיש ענין במזל, וצריך דבר לדחות אותו.
** אזיל -
תפילה -
אינו דווקא, שכאן מעשים טובים הציל אותו.
** אזיל -
כשאומר שיחזור, אינו דווקא, שאולי לא יעשה מעש"ט, אלא רצה לומר שיכול להיות שיחזור.
** צדקה תציל -
בכמה מאלו, יש להעיר שלא מביא ראיה מן הגדול, אלא מן הסיפור.
* קנז.
** הפרה בשבת -
קשה למה זמן שמיעה מתחיל בשבת, אחרי שלא יכול להפר בשבת. אף שזה דין דרבנן, צריך ביאור. ותחשב.
* קנז:
** גיגית -
איני מבין זה כל כך. משמע שהיה המת תחת הסדק, וצריך לומר שהיה רק חלק קטן מן המת, ודן אם יש בסדק טפח, שאז רק מטמא שם, או לא היה בו טפח, שאז מטמא את כל הבית, והכלים שבו.
* Footnotes
[fn:1] כאן אני מכוון למה ששמעתי מחברי ב.ל., שדן אם  שינוי כזה נחשב שינוי. באמת, איני מבין איך שאל שאלה כזה, שגמ' מפורשת היא שנחשבת שינוי, שגמ' אומר שאם מוציא דבר דרך אחוריו או כלאחר ידו נחשב שינוי. לכאו', שם בוודאי אין שינוי בתוצאה. (עדיין יש לפרש כמו שכתבנו, שאינו שינוי כל כך גדול, והו"א שאין כל כך צורך בו. דחוק, שמשנה אותו מאי' דאו' לאי' דרבנן.) אבל, יש לדחות שזה רק בהוצאה שהיא מלאכה גרועה, במה שאין לה תוצאה גדולה. ותחשב.
