* ב:
** ראשונה -
יש לדון למה מונים ראשונה לראשון:
1. אולי הוא מפני שמלך בחלק מן השנה.
2. גם אפשר (וצריך לדון למה לא יהני ראשון) שהוא מפני שכבר כתבו כן (שלא ידעו שימות).
* ה:
** מה מעשר אינו -
יש לדון אם אז יפסל בשעת וידוי מעשר.
** מה מעשר -
יש לדון אם רצה לומר שאינו נאסר ללוי או שישראל עדיין צריך ליתן אותו. ממה שרש"י מביא דין וידוי מעשר, נראה שהוא על נתינתו ללוי, שעל זה קאי דין וידוי. ויש לדון, שגם אפשר שזה מוכיח שעדיין מותר ללויים, אבל מה שישראל עדיין צריך ליתן אותו פשוט. ותחשב. ודע שלשון שאומר שאינו נפסל משמע שהוה אמינא שנפסל לאכילה. ויש לדון.
* י.
** ופירות נטיעה -
לכאורה, זה גלגל החוזר, שמה שצריכים לשהות עד אז הוא מפני שאז הוא אילן, וזמן אילן אז. הרי, אם שוהים עד אז, אינו בן שלש שנים, ואז אינו אילן, ואז אין צריכים לשהות עד אז. ותחשב. ואולי אין חשבון אם הוא אילן ופטור מערלה תלויים בהדדי. גם יש להעיר שזה רק בלשון גמרא, אבל אין זה בעיה מדרשת קרא. ותו"ת.
* י:
** וכי קאמר ל לקליוטה -
לא הבנתי לשון זה, שכי אמר ל, אינו לקליטה, אלא לקליטה עם היום אחד בשנה. ואולי כן ר"ל.
* יא.
** איתן -
נראה שאולי מילה זה שייך לנחל איתן, שהוא מקום שאינו אפשר לזרוע בו, והוא שהקרקע חזק, ואי אפשר לחרוש ולזרוע בו.
** נפקדה -
נמצא שפקידה לא רצה לומר מתי נעשית מעוברת, אלא רצה לומר זמן שגזר ה’ ליתן לה בן.
** ששה חדשים -
ואם תאמר אולי היתה מעוברת קודם לכן, ורק אמרו לה מלאכים שכן היה. ונראה שכיון שלא פרסה נדה עד אז, לא היה אפשר לה להיות מעוברת. אז, היה צריך להיות אחר כן.
* יב.
** מונים -
ק"ק, שכבר אמר גמרא שהוא לשיטתם. וצריך לומר שלא קשה להם מה שלא מזכיר שינוי השנים. גם יש לומר שחולקים במה מונים שנות אנשים.
* יג.
** ממחרת -
ק"ק מהיכי תיתי שהקריבו עומר; אם אין קרבן עומר, חדש מותרת רק אז, ואז אולי לכן שהו.
** קים להו -
משמע מכאן שהבעיה היה איך יכלו חכמים לראות ולדעת אם הביאו שליש. אז, אף על שאר, הקושיה היה איך ידעו לשער.
* יג:
** לגופיה -
יש לדון מה זה אומר, שאין, לכאורה, קרא אומר כל כך חידוש בזה, שאם לא נאכל משל שנה ששית, אין אחר לאכול. ויש לומר שמבטיח שלא נצטרך לקבל צדקה.
** ונמצא -
עדיין יהיה קשה מה יעשה בשנה שני שנכנס לשלישי, ומה יתן לעניים ומה יעלה לירושלים. ואולי יתן את כולו לעניים, ויחייבו להעלותו לירושלים. ויל"ד. (יש לדון בזה, שאולי לא ייחשב מעשר, שאינו שוה כל כך כיון שצריך לאכלו בירושלים. ויש לדון בזה, שהוא רק מחמת ספק. ותחשב.)
* יד.
** קמ"ל -
יש לדון למה לא אמר שהל’ כרש"ש ושאין  בילה חוץ מ…, שאז נדע שיטה שלישית כדי לתרץ אותו סתירה. ותחשב.
** נראה שיש סברה לומר כר"י
, והוא שאם כל מימיו משנה ראשונה, נחשב פרי של אותו שנה. יש גם כן סברה לומר כר"ע, והוא שכיון שגדל על רוב מים, בשנה שניה, כבר עומד להא, והוא כבר כבא, ואז נחשב פרי של אותו שנה. ותחשב.
* טו:
** אפילו כזית -
קשה, שלכאורה הוא אף בפחות מזה, שהוא בכל חנטה. ותחשב. ואולי סבר שאינו בתר חנטה, אלא גמר, וזה נחשב נגמר. עיין ברש"י שלא אומר כן. ותו"ת.
* טז.
** דקיימא -
נראה שהסיבה לחשוב כן הוא שאולי יש דיון רק על מה שכבר בא לעולם (כמו שרב חלותים רק נעשים על מה שכבר בא לעולם). ותחשב.
** כדי -
קצת משמע שסיבת החיוב הוא כדי שיהיה טוב לנו. ויש לדון, שאולי יש חיוב לשום סיבה, ועשה ה’ לנו טובה, שעשה את החיוב בדרך שיהנה לנו. ויש לדון, אז, למה צווה שיהיה בזה, שיחייב, ויאמר לנו עצה טובה.
* טז:
** ההוא זכותא -
ק"ק למה לא מנה גם את זה, אז. ותחשב.
** גמרא ורשי משמע
שבינונים הם בני אדם שהם מחצה על מחצה. קשה, ששאר בני אדם נקראים צדיקים גמורים ורשעים גמורים. צירך ביאור, אז, מה במי שאינו צדיק גמור או רשע גמור, ואינו מחצה על מחצה. ואולי אחד מהם אינו דווקא. ודחוק.
ונראה להעיר שגמרא בקידושין אומר שאם אדם מקדש אשה על מנת שהוא רשע, חוששים שמא באותו שעה חשב לעבוד ע"ז, ונמצא שחטא ורשע הוא. נמצא שקוראים מי שעשה עבריה אחת רשע. (כמו כן רואים בעדות, שרשע פסול, ואף אם רובו זכויות). אז, נראה שגמור רק בא להוציא מזה (ונקרא גמור כיון שרובו ככולו). ותחשב.
* יח.
** שהיו מתיה מתין -
לשון זה מוזר, שממה שמתו, פשוט שהם מתיו. גם קשה, שלכאורה, לא מתו מתיו אלא חייו, ואז אחר כך היו מתיו. ויש לדון. אפשר שר"ל שמי שמת קודם ימיו (קודם, למשל, שבעים) מת אז. ויש לדון, עדיין, בלשון מתיו.
** משפחת רבי יוחנן -
משמע שהיו קורים אותו סתם בימיו, אף שלאחר כן נעשה ששמו נקרא ריב"ז. ואולי קצרו בני העיר. ואפשר שר"י היה חלוק, וכיון שהיה משפחה נקרא אחריו, היו צריכים לשנות שמו ולומר כל שמו, שאם היו אומרים רבי יוחנן, היו חושבים שעל בני משפחה היו מדברים. ותחשב.
* יח:
** הוכפלו -
יש להעיר שאף הוכפלו, לכאורה, בשבעה עשר בתמוז, כמו שאומר גמרא בתענית. ותחשב.
* כ.
** משום דמצוה -
קשה, אז, מה חילוק יש בין חדשים אלו לשאר חדשים. ואולי קידוש ר"ח אלו נותן קדושה ליו"ט שבאותו חדש, ויש יותר קדושה אם נקדש באופן יותר טוב. יש לדון, אז, למה אין עושים כן בעצרת. יש לומר שזה מפני שאין עצרת הוקבע ביום מיוחד של חדש, ולא תלוי בחדש כלל.
** יוה"כ -
עיין רש"י שעל ירקיא אומר שהוא ביו"ט קרוב לשבת. לכאורה, מזה משמע שהוא אף בכל יוה"כ (ואף שאין עשים שני י"ט, כמו בשאר י"ט), שאי לאו הכי, כל שנה חילוק, שהרי אין יו"ט קרוב לשבת אם יה"כ קרוב לשבת. ותו"ת.
** אפשר בעממי -
צריך ביאור למה לא אומרים כן לעולם (ולמה אין הדין כן ביוה"כ).
* כ:
** כד שעי -
זה קשה, ואז אתן ביאור: ירח מהלך ממזרח למערב. נתמעט ליח שעות, ושוב נתגדל עוד ביח שעות כשמשנה מירח ישנה לירח חדשה. ביב שעות ראשונות, הוא יותר קרוב למזרח. אז, בני בבל, שהם בני מזרח, עדיין יכולים לראות אותו, ורק בני ארץ ישראל אינם יכולים לראות אותו. אחר כן, נתמעט עד שאין שום אחד שיכול לראותו.[fn:1] אחר שש שעות, נעשה ירח חדשה, אבל עדיין הוא כל כך קטן שאין אחד יכול לראותו. אחר שש שעות, נתגדל עד שמי שעומד קרוב לו יכול לראותו- אבל כבר הלך למערב. אז, בני א"י הם היכולים לראותו, שהם הקרובים לו. נמצא, אז, שמכל אחד היה נעלם לכד שעות. נעלם מבני מערבא לכד שבתחילה (שיש בהם שש של ירח חדשה בסופם) ומבני מערבה לכד אחרונות (שיש שש של ישנה בתחילתו). ותו"ת.
(שוב ראיתי שרש"י (כד.) כ’ שלבנה בחידושה בקרן מערבית דרומית. לכאורה, רק רצה לומר ששם נראה, שהרי הוא לשש שעות יותר קרוב לאמצע, אלא שלא נראה.)
** חצות -
ק"ק, שמרשי לעיל משמע שדין מאיימים תלוי באם בני אדם יבינו מזה שהם מטעים אותם. אם כן, כאן, כיון שהיה שם לפני חצות, יבינו. ותחשב.
* כא:
** מחללים על כלם -
יש להעיר שבזה אין במך של מה שאומר גמרא (שיהוי לשילוח). ותו"ת.
** שעל מהלך -
רצה לומר, היו צריכים לזה מפני שעל מהלך לילה ויום יצאו, ולא רק על הילוך מועט.
* כב.
** אחר -
יש לדון למה לא שאל מ”אותו” תחלה.
* כב:
** באושא -
מעניין שמניחים שהיה ר”נ שם, שהיה ר”מ (עיין בגמרא עירובין). לכאורה, זה היה קודם שבאו ליבנה, שלכאורה, לא בא ר”מ לשם, שלא נזכר שם.
** זוג -
יש לציין, כמובן, למה שאומר גמרא סוטה ש”עד” ר”ל שני עדים.
* כג.
** להדס -
אולי יש לציין בזה למחלקת בפרק חלק אם היה הכתוב מקלס לנוח או לא. וחושב אני שאף שם ר"י דן. וצריך לעיין שם.
* כה.
** פלוני -
יש לדון למה לא יכולים לומר שהוא אינו כאותם דיינם, שכבר הניח שצריך להיות כמשה לכשר (שלכן אומר כן לאותו שופט), ואם כן, מוכרח ששאר היו כמשה. ויש לדון. ואפשר שר"ל שממה שלא אמר שמם, מוכח שלא היו גדולים כל כך.
* כה:
** כשמואל -
נראה שאמר הגדול (שמואל, ששקול כמשה ואהרן, כמו שאומר גמרא ברכות (ראש פרק אין עומדים), לקטן. ותחשב.
** שמע מקצת -
אם עלה בינתים (כמס’ גמרא), צריך ביאור מה שייכות יש בין תחלת מאמרו לסופו. ותחשב.
* כט:
** לבני בתירה -
מעניין, שהיו בני בתירה נשיאים בזמן הלל, שהיה רבו של ריב"ז. ואולי היו שני בני בתירה. גם יש לומר שהיה זה שם משפחה.
* ל:
** אותו היום -
נמצא שאין בני אדם יודעים ממה שנהגו יום שני קדש שנמצא שלא היה ראשון קודש.
* לא.
** וקמפלגי -
מבריי’ משמע שחולק מפני הלשון. ותו"ת.
* לא:
** יבנה -
עיין במה שמבאר רש"י מתי היו אלו. ק"ק איך באו ר"ש ור"י וכדומה לכרם ביבנה, שהיו לאחר זמן ר"ג, שהיה בדור של ר"א ור"י רבם של ר"ע.
* לב.
** ואם אמר -
אז, שיעור שבע הוא רק אם לא אומר אחד מתורה, אחד מנביאים, ואחד מכתובים.
* לב:
** שאין עמה -
יש לדון, שכבר אמר רבי יהודה בכל זמן שיש עמה כלום שרק מהני לאותו דבר אחר. אולי יש חילוק בין שופרות שיש דבר אחר עמו לדבר אחר שיש שופרות עמו. גם יש לומר שיש חילוק בין שופרות (כך הלשון של גמרא לעיל) ותרועה (הלשון כאן). ותח’.
* Footnotes
[fn:1] כן- חושב אני- היה נראה לי מרש"י. ודע שאין צריך לומר כן, שהיה אפשר לומר שכל זמן זה הוא הולך למערב, ואז, אולי אחר זמן זה, רחק מבבל עד שאי אפשר לראות, ולא קרב לא"י די לראות.
