* ד.
** כלבתא -
צריך לומר שלא כבר הותר איסור זה (אף ששבעה מצות בני נוח הותרו).
* י.
** ומטו בה -
יש להעיר שלשון מטים בענין הלכה משמע שחשבו כן, אבל לא ידוע בבירור. לשון רש"י כאן לא משמע כן.
* יג:
** יצאו -
רצה לומר, שאם חי מחמת מים שלפני כן, צריך להיות שהוא מונח בתוך גופו כבר. אם כן, אחר שיגוז, לא יחיה. יש לדון מהו ההוכחה, שאולי אז, ורק אז, חי מחמת מים שבא לעולם באותו שנה.
** איכא -
עיין בביאורו. לכאורה, מה שגמרא אומר שלשים יום הוא שצריך להיות שנה. ויש לדון.
* יז:
** ברית כרותה -
מעניין שאומר שזה רק בתפילת תענית. ויש לדון מהו המקור לזה. (ולשון "כל זמן" שאומר לא משמע כן. ואולי רצה לומר כל זמן בשנה, ועדיין צריכים להתענות אז.) ואולי ידע כן ממה שמצינו שיש צורך להתענות, ולא רק לומר יג מדות. (יש להעיר שעכשיו אומרים אותו אף בימים שאינם ימי תענית. אם כן, צירך לומר או שלא מניחים כרש"י או שעדיין יש שום טובה בו אף שאינו בתענית, אלא רק אין הבטחה. ויש להעיר שאין צורך שיהיה עודף על שאר תפילות, שלכאורה, כל שאר תפילה שאומרים אין לו אותו מעלה, ואף על פי כן נאמר. זה אומר שאולי נבחר לאותו סיבה שכל שאר תפלה נבחר, ואינו יותר טוב. ותחשב.)
* יח.
** אביי ורבא -
עיין בחולין שכתב רש"י שהיה רבא כהן.
** על תשרי -
משמע שאינו כדי שלא יצטרכו לסמוך על מה שחושבים מפני שאולי נכון הוא, אלא כדי שהם לא יחושו. זה מעניין.
* כ:
** לאכחושי סהדי -
יש לדון למה, אז, נקט דין של שש שעות, ולא של כד, שסותרים סהדי מחמת דין של כד. ותחשב.
* כד.
** כאן -
לא הבנתי חשבון זה כל כך. לכאורה, אומר שבא לבנה קצת קודם שקיעה. אז, תלוי באם בא חמה למערב בשקיעה או קודם לכן (וזה תלוי איפה שוקע). לא הבנתי איך רואים אם הוא לצרון או לא. הניחא אם העומדים הם באמצא (שכשסובבים חמה ולבנה, הולך לאחריהם, יכולים לראות, אבל אם אינם באמצע, יש לדון איך ידעו. ואולי אז הלבנה יותר גדול. ותחשב.
* כה.
** זיל -
צריך ביאור מה הועיל לו בזה; יהיה זמן שיבינו בו בני אדם מה קרה. ואולי באותו זמן, יהיה כבר חוזר לביתו ונועל דלתו.
** ואומר -
נמצא ששמואל ידע על עצמו שהיה כל כך גדול, ואמר כן לבני ישראל. ותחשב.
* כו:
** במה -
צריך ביאור מה אומר רש"י. ויש לומר שאומר שאף שלא היה לו לדעת מה פירושו, היה לו לדעת (ויש לדון למה לא, שגמרא יודע מאותו קרא), על כל פנים, איך לשאול (שישתמש בלשון, “במה"). גם יש לומר שרש"י גרס חלק זה מן הקרא שאומר פירושו, והיה ממשיך הקרא.
* כח.
** מהו -
יש שכתבו שענין מתעסק בחלבים… הוא שבאלו ההנאה הוא חלק מן האיסור. אם כן, קשה מה מנסה ללמוד למצה; מי יימר שכן הוא במצה. ויש לומר שממה שכן כוונת הקרא כשאומר לשון אכילה בזה, אולי מסתבר שכן כוונתו כשאומרו בזה. ותחשב.
* כח:
** לותיב -
יש לדון למה יותר חזק. יש לדון שאין לומר שלא חושב שהוא נכון. לולי רש"י, היה אפשר לומר שמק’ למה לא הק’ ממשנה, שלכאורה, בא בדעתו ראשון, שהיה ידוע לכל.
** כך חולקים -
נצצא שאף בימי אמוראים קראו פרשת האזינו בחד שבוע (אף שלכאורה, אין הוכחה ששאר סדרות קראו כמונו).
* לג:
** אין -
פסוקי- גמרא אומר כן לעיל שני פעמים. יש להעיר שלמסקנא  של גמרא, אין צריכים אותו תירוץ, שיש לומר שאין תחילת תקיעה או סוף תקיעה מהני בפני עצמו. מניח רש"י שאף על פי שאינו נצרך, הוא אמת. ותחשב.
* לד:
** מתשעה -
עיין במה שבאר ב"ח. אם כן, נמצא שאומר שאף זה רק כשהוא משני בני אדם. אולי בא לתרץ בזה למה לא אמרו כן בדברות (שלכאורה, היו חביבים). ויש לדון אם היו חביבים, שהרי בני ישראל מתו, והוצרך ה’ לכוף עליהם הר כגיגית. ותחשב.
