* ב.
** דיני ממונות -
הפשטות הוא שמה שצריך שלש הוא כדי שיוצא האמת מן הדין (שיותר מסתבר שלא שימצאו רב שלשה האמת), ולא לשום טעם לומדי (שלעשות חלות צריך שלשה, או כדומה). יש להעיר שלכאורה יש דברים שבמשנה שאינם כן (למשל, עגלה ערופה או כדומה, שלכאורה, אין צורך לאמת לצאת, וצריכים לשלה כדי לעשות חלות). אם כן, יימצא שדינים חלוקים שבמשנה יהיה לו דין חלוק. (ויש להעיר שאם עושים דברים חלוקים, קצת צריך להגדיר מה עושה שניהם שנעשה שניהם באותו שם של "בית דין.” היה אפשר להגדיר ש"בית דין" רק רצה לומר "בני אדם שבאים ביחד לעשות דבר.” אי אפשר לעשות כן, שאם כן, אף שמחת יום הולדת יהיה בית דין (היה אפשר לומר שאין הכי נמי הוא בית דין, אבל לא נראה כן). אפשר שהוא שבאים לדבר שצריך מנינם. עדיין קשה, שלכאורה מנין לדברים שבקדושה או עדים יהיה בית דין. ותחשב.
** ואדם כיוצא בהם -
מעניין שאומר לשון כזה כאן, שלא אומר כן בשאר הקדשות (ושם רק אומר על כולם "שלש"). ותחשב.
* ב:
** כנגד שרי עשרות -
זה מעניין, שלכאורה, אין כל אחד של בית דין שר על עשר, אלא כל הבית דין שורר על כולם. ותחשב.
** גזירה -
ואם תאמר נגזור שיהיה חד מומחה. ויש לומר שלא מצאנו דין שצריך מומחה אחד, אבל מצאנו דבר (כמו חליצה) שצריך שלש הדיוטות. אם כן, עשו רבנן דינם כדין תורה. לא נראה, שמצינו דין מומחה אחד בנדרים (ויש לדון, שאולי צריך להיות יותר מומחה, או מומחה בדבר חלוק). גם יש לומר שאינו קל למצוא חד מומחה, אבל קל למצוא שלש הדיוטות. קשה, שבכל שלש נמצא חד מומחה. יש לומר שהוא רק מומחה די לדון בשלש (ידע מה לעשות בסיוע שני הדיוטות). גם יש לומר שלא קל לדעת איזה הוא המומחה עד שדנים. ותחשב. עדיין יש לדון למה לא עשו שידון על פי שלש הדיוטות, ורק נרבה על ידי זה, שאחד יהיה מומחה, ולא נמעט כלום. ותחשב.
* ג:
** דכתיבי -
רצה לומר שכתוב שאינו ביותר משבעים, אבל כאן אינו כתוב שאינו ביותר משנים או ארבע (ולא אומר שיש מקור שהוא שבעים ולא פחוץ, שאף כאן יש מקור)
* ד:
** ירשעון דהאיך -
עדיין צריך ביאור, שיכתוב רק ירשיעון, ולא צריך "אלהים" אחר. ויש לומר שסוברים שלא יאמר לשון רבין לגלות שהם רבים (לא יאמר לשון רבים אלא על רבים שכבר הוזכרו). אם כן, לא היה יכול לומר ירשיעון אם לא כבר גילה שהוא רבים. ותחשב.
** קשה למה
לא לומדים שצריך להיות שלש ממה שצריך הטייה לטוה (ואם יש רק אחד או שנים, לא יכולים לפסוק על פי הטייה). ותחשב.
** לא פליגי -
עדיין צריך ביאור מה היה ההוה אמינא של רבי יהודה בן רועץ.
* ה.
** אם קבלוך -
לכאורה, זה פוטר, אף שעדיין גרם, כיון שהבעל גרם עמו בקבלתו. ותחשב.
אם כן, ק"ק למה לא אומר כן כשאומר שידון דין תורה (עיין גמרא לקמן (ו.)). אז, נראה שהענין הוא שהוא כאילו אמר שימחל על כל מה שאומר הדיין. אם כן, כמובן, פטור. כשאומר שהוא על דין תורה, אומר שלא מוחל. ותחשב.
** מ"ז -
יש להעיר שהוא, לכאורה, מוזר מה שלא קיבל רשות מריש גלותא, כיון שהיה אבי אביו[fn:1] (עיין בחולין קכד.[fn:2]) ונראה שיש לציין למש"כ בשיח שי (הוספות) על יבמות שנמצא שר"נ לא נשא בת רבה בר אבוה. נראה שקשה, שהרי לא נמצא סריס (שהוליד בן). נראה, אז, שנשא שני נשים (ואז, יש לומר שבן זה לא היה נכד של ריש גלותא). ותחשב.
ואגב, יש להעיר על אותו גמרא שמצינו שר"נ אומר כמה דברים בשם רבה בא אבוה. מסתבר, שהיה חתנו (או שמסתבר שרצה להשיא לו את בתו כיון שהיה כבר תלמידו). ותחשב.
ושוב ראיתי להעיר שרב נחמן הוא אחד מן המנויים גבי רבנים שהיו מכריזים לישא אשה אחת ליום (כשהלך ממקום למקום). אם נאמר שבעלו אותן נשים (עיין שם, שדן גמרא בזה), אז רואים שהיה לו שני נשים. ותו"ת.
* ה:
** כנגד מחנה ישראל -
מניח שהיה משה דר בקצה אחד. ונראה שלא היה דר שם, אלא שלפעמים היה נמצא שם, ואף על פי כן, הלכו לו לשאול.
* ה:
** על תנאי -
יש לדון מה סובר גמרא:
1. לא יחול
2. יחול לעולם
לכאורה, הצד שיחול לעולם הוא או שכיון שחל, לא פקע (אין דבר שיש לו כוח לפקוע אותו) או שכיון שגילו שיכול להורות, אין סיבה שלא יהיה מותר לעולם. ויש לדון, שרק גילו, אולי , שיכול בדיעבד. ותחשב.
גם נראה שאולי הוה אמינא שמעלים בקדש ואין מורידים. אולי זה יעשה שלא יחול, ואולי זה רק יעשה שאף שיכול, אסור הוא. אם כן, מצאנו עוד צד. ותחשב.
** פשרה -
צריך ביאור למה לא יחול, שיהיה כמתנה עמו למחול.
* ו.
** והלכתא -
יש לדון מי אומר כן (אפשר שר"א אומר כן, ואומר שיודעים שמד"א שצריך שלש סובר שא"צ קנין, והל’ הוא שצריך קנין, ואז צריך לומר שאין הלכה כן).
** וכל הבוצע -
צריכים לדון מהו הרע של ביצוע:
1. אפשר שהוא שנמצא שהרע שעשה אחד גרם לו טובה (או גרם לחברו רע), שגרם שעשה פשרה.
2. אפשר שחיוב בית דין הוא לעשות מה שהוא הכי טוב (האמת), ולכן אי אפשר לו לבצוע.
3. אולי הוא שמפני 1, ירבו גזלנים, שיעשו פשרה אחר כך ויהנו.
יש לציין לרש"י כאן שכ’ שזה רק בדיין. יש לדון למה:
1. אם נאמר כ2, פשוט הוא.
2. אפשר שיש אותו רע לכל אדם, אלא שיוכל אדם לגרום רע או להזיק את עצמו. זה לא יהני ל3, לכאורה.
3. אפשר שיש אותו רע, אלא שנדחה כיון שיכול לחוש שלא יבוא לו מעותיו. יש לדון, שאם יכול אדם לחוש לחסרונו, למה לא יוכל דיין לחוש לחסרון של מי שאומר האמת. אז, לא נראה כצד זה.
4. אז, נחשב שעומד לבוא למי שהאמת עמו. אז, הוא יותר שלו, ורע להפסידו.
יש לדון מה סובר שמי שאומר שאסור רק אחר שיודע איך הדין נוטה:
1. אז, כיון שעומד לבא למי שחושב שהוא נכון, אינו יכול להפסידו, ולעשות שיעשה פשרה.
2. אולי רק עושים פשרה כיון שלא יודעים מה יעשה. נמצא שמטעה אותם.
3. אולי הוא שכיון שדיין יודע מהו הדין, יש לו חיוב לעשות האמת.
נמצא שתלוי בצדדים אלו אם חולקים מתי יש לדיין חיוב לעשות אמת. לכאורה, אז, תלוי בזה אם כשבריי’ אומר מתי חל חיוב של "לא תגורו,” הוא לדברי הכל או רק לשיטה שניה. ותחשב.
** אתאן לת"ק -
לכאורה, רצה לומר שמה שיבוא הוא לת"ק, שמה שאמר שהוא בצע לכאורה הוא נגד ת"ק. ותו"ת.
** אדעתא דתלתא -
לכאורה, זה משמע שאינו רק כדי שנמצא האמת. ותחשב.
* ז:
** עשרה -
צריך ביאור למה נקט עשרה, שאין בית דין עשרה. ואולי נקט מנין שהוא יותר מבית דין סתם(שלש) להראות שכולל אף התלמידים. ודחוק, שעדיין לא מבאר למה נקט עשר בדווקא. ויש לדון מה היה לו לנקוט. ואולי היה לו לומר ארבע. ותחשב. ואולי רצה לומר שני בעלי דינים, שני עדים לכל אחד, שלש דיינם[fn:3], ותלמיד אחד. ותחשב.
ועיין לקמן בגמרא שמשמע שעשרה היה מנין רגיל של תלמידים.
* ח.
** לא דיין -
כמובן, אז צריך לדון מה יהיה אם אדם משלם אחר שהטריח ה’ להחזיר. ותחשב.
* ט.
** עדים -
ק"ק למה נחשוב לחלק בין מאה לשלש. יש לומר שכיון שאחד פסול, יש סיבה להניח שיש עוד פסולים (שלא דק במציאת עדים). עדיין לא מסתבר שכלם חוץ מאחד פסולים. ויש לדון, שאם כן, יצא הדין שאם בדקו, יכשרו. ואולי יש פסולים שאי אפשר לבדוק להם.
ויש לדון אם קמ"ל שאין זה סיבת פסול כאן, או שקמ"ל שאף כאן חוששים.
** דאתרו -
היה אפשר לומר שחולקים אם לאו שניתן לאזהרת מיתת בית דין לוקין עליו.
* י.
** עולא -
לכאורה, רצה לומר שיש לדרוש ממנו רק אם הוא מיותר. לכאורה, הסברה לזה הוא שאם אינו מיותר, קאי על בית דין שכבר נזכרים, ואינו מוסיף שנים. ותחשב.
** מכות במקום -
אז:
1. כיון שיכול לעמוד במקום מיתה, צריך לומר שהוא חמור. ממילא, צריך עשרים ושלש לו.
2. הדרך לחייב מכות הוא לחייב מיתה. כיון שהוא חייב מיתה, ייתן ה’ לו מכות במקומו. אז, צריך עשרים ושלש כדי לחייב מיתה.
נראה שזה רק מהני אם צריך יותר דיינים כיון שעושים עליו חלות יותר גדול, אבל לא אם צריכים יותר מפני שיותר צריכים להגיע אל האמת, שאם כן, דינו למעשה, ולא מה שהיה להיות דינו, שייך. ותחשב על זה.
** ונקלה -
צריך ביאור למה לא ת’ שלאיזה סיבה שרצה ה’ שנעשה דבר שלא יהרג אותו, רצה ה’ שלא יהרג לו מכות. ותחשב. ונראה שר"ל שרואים שה’ הקיל את דינו, ולא יודעים אם הקל עליו עד שעשה לו ספק שימות או עד שעשה לו ודאי שלא ימות. אז, אומר גמרא שנניח שהוא הכי קרוב למה שהיה לו להתחייב. אז, היה לנו להניח שעשה ה’ שהוא ספק אם ימות. אם כן, לא נחוש אם ממיתים אותו על ידי מכות.
* י:
** עיבור -
לכאורה, היה אפשר לומר שנחשב חישוב עיבור עיבור כיון שגורם עיבור על ידי מה שלא מקדש חדש. ויש לדון, שהיו צריכים עדים (ואז, זה מהני רק אם מאיימים). גם נראה לפרש על פי מש"א רש"י שנעשה מעובר קדוש כיון שבשמים קדשוהו, ולא בא ממילא מחמת שמוכרח להיות ראש השנה. אם כן, לא יכולים לומר שהם גרמו לעיבורו, שהרי בית דין שבשמים עשו כן. ויש לדון.
* יא.
** ולא -
יש לדון בכמה פרטים במעשה זה. יש לדון אם רבן גמליאל ידע בזה או לא. אם לא ידע, קשה איך אמר לו לשבת. יש לומר שאמר לו שיכול ללמוד. עדיין קשה איך אמר כן שמואל כיון שגרם שהשנה יהיה מעובר בלי כשרים. יש לומר שדין מזומנים הוא רק דין לכתחילה (זה גם יבאר אולי איך אמר לו לשבת). גם יש לומר שהיה בקי וידע על פי חשבון שלא יהיו מעברים אותו. גם יש לומר שכיון שישב עמהם, היה נחשב כאילו הוא מהם, ונמצא שהיו להם שבעה דיינים. גם יש לומר שחשב שמואל שר"ג ידע, אבל טעה בזה. אם ר"ג ידע, לשון גמרא של "ולא היא…" מוזר. אז, נראה שלא ידע. ותחשב.
** ויצא -
לכאורה, ידע שכולם יצאו, שאי לאו הכי, לא יועיל כלום. ולכאורה, חשב שיצאו כיון שידע שאף מי שהיה בו ריח שום יכיר כך, והיה כפוף לישב עמו. נראה שאולי אף אחרים הכירו בזה, ואז אף הם יצאו עמו, שאף שהיה יכול לטעון אחד היוצא עם ר"ח שהיה יוצא לכבוד רבי חייא, אולי היו יכולים להבין. ועוד שאם אחר כך כלה הריח, יהיה ידוע שהיה ר"ח או אותו ת"ח, ואולי לא כל כך מסתבר שהיה ר"ח עושה כן.
ונראה שאולי אף שמואל חשב ששאר יצאו עמו, ולכן לא חש לעשות שיש רק ששה כשרים (וכיון שנשאר, אולי לא היה בעיה). ותחשב.
** ראויות כל השנים -
לשון זה מעניין. לכאורה, רצה לומר שאף בימי הקדמונים, שהיו שם ת"ח, אתה היית ראוי להימנות עמם לעבר שנה. גם יש לומר שאומר שהוא יכול לקדש כל השנים שיבואו, שהיה בקי עד שיכול לעשות לוח כמו הלל. גם יש לומר שאמר לו שהיה ראוי אף לעבר מה שאינו צריך להתעבר, והיה רק גוזמא לומר שהיה חושב שהוא ראוי מאד.
** ור"מ -
לכאורה, או סבר שלא תאמין לו עד שתנשא על פי אותו גט או שחשב ששאר יכתבו לה גט.
** ירצה נשיא -
לכאורה, זה פשוט, שצריך לזמן. (ואולי אין הכי נמי, אלא שברייתא לא הגיד דין זה לנו עדיין). גם יש לומר שמחדש שיכול נשיא לומר שאינו רוצה, ולא כפוף להזמין. גם יש לומר שיש נפק"מ אם הזמין, ושוב החליט שלא לעבר.
** על מנת -
קשה, אז, מי הזמין אותם. אם הוא רק דין בדיעבד, לא קשה (וזה ג"כ ית’ דיבור הקודם). אם לאו, יש לומר שרק צריכים שגדול יזמין אותם. ותחשב. (וכ"ז ית’ דיבור הקודם).
** משמתו -
כמובן, פשוט הוא שכיון שמתו נביאים אחרונים לא היו עוד נביאים (ואין לשונו משמע שרק מחדש שהיה עדיין בת קול). ואולי אינו כל כך פשוט, שאולי נביאם רצה לומר מי שמסר נביאותו בתנ"ך. ותו"ת.
** יהושע -
כיון שאומרים שהוא פסוק, היה אפשר לומר שמשם למד ר"ח וכדו’.
** ממי למד -
קצת צריך ביאור מה חידוש יש בזה; מי יאמר שלא יכסיף אדם. אין לומר שהחיודש הוא שמותר לבוייש את עצמו לזה, שהרי לא קרה כן ביהושע. אולי החידוש הוא שיכול לכלול מי שהוא נקי בכלל החייבים לזה. ותחשב. גם יש לומרש חידוש הוא שאי אפשר לבייש כאן, כיון שעבר על עבירה.
* יא:
** תקיפי -
ואם תאמר אם כן, היה לנו למנותו בב"מ לאחד מן הענווים. ויש לומר שלא היה ענוו בכל. גם יש לדייק, אולי, מלשון רבים שאומר, שאולי משמע שהענין הוא שכך ענווה כזה היה כל כך נהוג בין ת"ח עד שאף ר"ג היה צריך לעשות אותו. ותחשב. (ודיחוי גמרא אפשר אף למש"כ, אלא שק”ק למה לא מנה אותו אחר אותו זמן לאחד מן הענווים. ותחשב.)
* יב.
** ערב שביעית -
ואם תאמר בין כך ובין כך ייחסר שנים עשרה חדש של עבודת קרקע. ויש לומר שבין כך ובין כך יפסיד מה שמתחלת בידש שביעי, שהרי לא היה יכול להתחיל. אז, רוצים שיותר מן היב חדש יהיה על זה. גם יש לומר לולי רש"י שרוצים שלא נהיו צריכים לשהות בשנה שמינית (שחוששים שמא יהיה פסח קודם שבשלו, ויצטרכו לעבר כדי להתיר). ותחשב.
* יב:
** היינו ת"ק -
ואם תאמר הרי פשוט מה סובר תנא קמא בלכתחילה (שאומר אותו בפירוש), ומה שסבר ר"ש בזה(שאומר שלא היה צריך כפרה). אם כן, קשה למה הקשה גמרא. ויש לומר שסבר שכיון שחל בדיעבד לא יה צריך כפרה. ודחוק.
** ראוי לקבעו -
יש לדון למה:
1. אולי הוא מפני שניסן כבר עומד לבא, וכבר נאמר שאותו ימים, ולא אחרים ניסן. יש לדון אם זה מפני שכבר עומד לבא (והסיבה לזה הוא שיבואו ביום שלשים ואחד אף בלי שום דבר נעשה) או שידוע איזה ימים יהיו (שצריכים לעבר חדש), ואז נאמר על ימים מפורשים. לא נראה, שאולי עדים יבואו בתוך אותו יום. אז, צריך לומר שהוא הראשון. אם כן, לכאורה, יהיה רק מפני קרבתו בזמן לניסן. ויש לדון, אז, למה אין מספקים בזה ביום כט, שאולי לא היה לו לעבר. ואולי עדייןאם יהיה בא מיד, צריך מעשה. עדיין, אין לשון גמרא משמע כלל כצד זה.
2. קצת נחשב חלק של ניסן. ותחשב מה זה אומר. לכן, כמו שניסן הוקבע, אף זה הוקבע.
** מעברים -
צריך ביאור איך טעה תנא בין "מעברים" ל"אינו מעובר.” אולי יש לומר שכוונתו היה לומר "ר"י חולק,” וטעו לאיזה דרך חולק. ועדיין צריך ביאור איך טעו כן, שלכאורה , ממה שאמר בחזקיה פשוט מה סובר. ותחשב. ויש לומר שנשכח קודם מה אומר ת"ק בבדיעבד, ואז היה מוכרח לומר כך בר"י, אף שהיה קשה. ותחשב.
** אין מקדשים -
יש כמה דינים שנוהגים באדר שני. יש לדון אם אותו שנה קרים, שהרי לא קידש אותו חודש. (ויש להעיר שכבר עשה כולם בראשון, שחשבו שלא יהיה שני.)
** דלא סליק -
יש להעיר שדייקנו מרש"י שאיסרו יום שלושים הוא רק אם התחילו לחשב רק מאז. אם כן, לכאורה, משמע שיכול לעשות ביום כט אם התחיל לחשב מאז. ונראה שממסתבר שהיו מחשבים מקודם, וחישבו כל אחד, ואז החליטו אם לחשב ביחד בבית דין. כל אחד לני כן לא הכיר שהצריכו. ותחשב.
* יג:
** העדה -
מעניין שדורשים "ה" כאילו קאי עליהם, ולא על ה"עדה.” ותחשב. ואפשר שהוא חד פריי"ז, ואז ה שעל השני כאילו הוא על הראשון, כמו "בית הספר.” גם יש לדחות שאומר שסנהדרין היה עדה מיוחדת.
** ראש שבעים וחד -
יש להעיר שלא היה יכול להיות כנגד אותו שבעים ואחד, שהיה אחד מן השבעים ואחד. ויש לדון מוה הלימוד שאומר רש"י (שכיון שהיה על גבם ועליהם, רואים שהיה שקול ככולם). ואולי, לולי רש"י, יש לומר שהוא מפני שהביא בית דין רק מפני עצת יתרו, אבל לא מפני הצורך. משמע שלכל מה שהיה בית דין כשר לו, היה משה כשר לו. ויל"ד. ותחשב.
* יד.
** הא אמרן -
נראה שסובר גמרא שכיון שאי אפשר לסמוך בחו"ל, יש לדון אם הוא דין בסומך (שאין לו, באותו מצב, כל כך קדושה) או בנסמך (שלא יכול לקבל כל כך קדושה). נראה שמניח כצד ראשון, שלשני, אף שלא קבל כל כך, מה שקבל ישאר עליו, ויתיר אותו לכשנכנס (רצה לומר, לכאורה, אין צריך כוח לקבל; אז, זה רק מניעה. אם כן, כשיסלק המניעה לפסק, יוכל לפסוק. ותחשב.) ותחשב. אם כן, מניח כראשון. ויש לדון.
* יד:
** מדידה -
נראה שיש להסביר את זה לומר שחלק מן הכפרה הוא שמראה לבני אדם כמה צריכים להיזהר על הריגה, שאף זקנים אלו, שגרמו באופן קטן, נחשבים גורמים. אולי, אז, צריך למדוד כדי שנדע כמה פחות היה גרמותם (שאם הלך כבר יותר, לא היו כל כך גורמים). ותחשב.
** ואל השופט -
יש להעיר שלכאורה הכהן והגלוי אינם השופטים בקרא זה. צריך לומר שדורשים רק ממה שהם באותו קרא.
** בסנהדרין -
לכאורה, הסברה לומר שחולקים הוא שכיון שרואים שצריך מלך, אולי מסתבר שצריך עוד יותר. גם יש לומר שכיון שרואים שדורש קראי אף בלי כל כך משמעות לענין זה (ואז, צריך לומר שהוא מסתבר לו, ואז אינו צריך כל כך הוכחה), אולי אף דורש לרבות כל סנהדרין.
** דילמא כגון ר"פ -
ואם תאמר אם כן מאי רבותא. ויש לומר שמחדש שאף שהם קרובים, אין פסול.
* טו.
** מה לי -
היה אפשר לומר שרגילים בני אדם לטעות רק לפחת, ולא להוסיף, ואז יש לחלק, אלא שסברה זה לא נראה נכון במציאות לגמרא.
* טו:
** אין להם תרבות -
מרש"י נראה שכיון שאסור לקנות אותם, אינם נחשבים שלו. לכאורה, אומר שלקנס, הפקירם חכמים. היה אפשר לומר, לולי זה, שכיון שאי אפשר להרביתם, אי אפשר לשלוט עליהם כראוי, ואז בהכרח אינם שלו.
* טז:
** בניהו -
היה אפשר לומר שהוא יחיד מומחה, אלא שמסתמא לא היו צרכים מומחה כל כך, ואז, לכאורה, נקטו אותו מחמת שהיה אב בית דין.
** במשה -
בכל כעין זה יש לדון איך מביא ראיה מזה, שיודעים שמהני משה ושבעים, אבל לא יודעים שלא מהני פחות (וכך היה, לכאורה, אף בהוה אמינא, שבהוה אמינא, לא יודעים שאין שלש מהני. ויש לדון.) ותחשב. ואולי לא היה משה עושה אותו אם לא היה צריך שבעים.
* יז.
** שנים -
קשה מהיכי תיתי שצריך הטיה על פי שנים; רק צריכים לקיים מה שאומר קרא שצריך להטות לרע, אבל לא כמו שמטה לטוב.
** מוסיפים -
ק"ק למה לא אומרים שנקיים "על פי אחד" בזה (ואז אין לנו מקור לשלש, שנאמר שהוא בשנים, ודין של "אין בית דין שקול" מקוים במוסיפים).
** קמיה -
משמע שאילו ידע, פשוט לגמרא שהיה מוחה. חושב אני שאין זה ידוע.
** אפשר שמה שאין ממיתים
אם ראו כולם לחובה הוא שאם עבר בדרך כל כך פשוט, מסתמא הוא מומר ביותר, ולא זוכה בכפרת עונש. ותו"ת.
* יח.
** כה"ג -
יש להעיר שיש עדיין נפק"מ לו במיתת כה"ג ליציאת עצמיו. ויש לדון, שאולי אחר שנגלה או אחר שממית, מעבירים אותו. כן קצת נראה, שלכאורה, לא יכול לצאת בעיר המקלט לעבוד לכה"ג. ותחשב.
* יח:
** גדול -
יש לדון אם מצטרפים עם הדרשה מה שלשון פשטות הקרא משמע דבר גדול, או שכל הדרשה הוא שצריך להיות דבר גדול, והוא גדול כיון שהוא של גדול וכיון שהוא גדול. ותחשב.
** צינה -
היה אפשר לגמרא לתרץ שאף אם בשנה שצריך להיות מעובר, צינה הוא כפי חדשי עיבור, עדיין יהיה יותר חם אם לא יעברו מאם יעברו. ותו"ת.
* יט.
** מלך ישראל -
כיון שדנים על מלכי בית דוד, היה אפשר לומר שעל זה קאי משנה כשאומר שכהן גדול מעיד(שמעיד למלך מבית דוד).
** שמאל -
קשה, בשני הציורים, שאר בני אדם לשמאלו, ואז אין להוכיח. וצריך לומר שסבר שיותר משסתבר שישנה כשמנחמים אותו משישתנה כשהוא מנחם. ותחשב. ואפשר לומר שמדייק ממה שאומר ש"אבל ועל עם" משמאלו, שמשמע שעם יותר משמאל כיון שנזכר אחרון. ותחשב.
** תניא נמי הכי -
י שלדון אם הראיה הוא ממה שאמר שאם בעלו קנו (וזה אמר שצריך להיות מדרבנן) או שסומכו לדין בעילה שניה, שמשמע שהוא הטעם.
** מעניין
שבכה"ג אומרים חשש לנגיעה ולא לאהל. ותחשב.
* יט:
** דעתו על מלוה -
יש לדון על איזה דעת דנים, שלכאורה, דוד היה המקדש, ואז בודאי אותו דעת היה בטוב, שלכאורה, יידע על מה חושב, ושאול היה המקבל, ובודאי אותו דעת לא היה בטוב, שיודע על מה חושב. ויש לדון, שאולי מיכל היתה המקבל. אם כן, חולקים על מה חשבה. גם יש לומר שסוברים שאם אינו כשיטתם, יהיה בטל דעתו. גם יש לומר שאף אם חושבים דבר מיוחד, יהיה דברים שבלב.
** דעתו -
מעניין שיש לדון בזה אף כאן שלא נתנם בבת אחת.
** דעתו -
מעניין שישלח אותו שאול לעשות כן כיון שידע שבזה לא יכול לקדש. ותו"ת.
** לא חזי -
לכאורה, היה אותו בעיה בגליות, ולא היה צריך לטעם של קידושין במלווה. ואולי איה"נ. גם יש לומרש שם נתן שללו, או ששם הציל את שאול (כמו מה שאומר גמרא קידושין בהצלת כלב, שאולי מקדש). יש לדון למה לא נמצא כן אף כאן. וואלי למעשה, לא היה כל כך סכנה, ולא היה שלל. שו"ר שרש"י כ’ שאמר שיתן לו עושר גדול בשביל גלית, וזה היה הקידושין.
** נעמי -
לא היה בן רות יתום, אלא שכל שכן הוא שכן הוא ביתום. (ויש להעיר שגמרא בראיה כזה לא מזכיר יתום.) ותחשב.
* כ:
** ומוציא -
יש לדון, שאולי משנה אומר שרק מלך יכול לעשות כן ולא אחרים. ויש לדון, שמשנה משמע שבא לחדש מעלת מלך, ולא גרעון של אחרים. ותו"ת.
** ג מצוות -
לכאורה, גם היה מצוות התלויים בארץ. ועיין בסוף פרק קמא של קידושין.
* כב.
** אשתו ראשונה -
לכאורה, אינו רק על אשתו ראשונה, שהרי לא היה דווד יכול לגרש שום אחד משמנה עשרה נשיו. ותחשב.
** כאילו -
יש לדון אם אומר שהוא כל כך עצב לו או שר"ל שהוא כאילו עשה דבר רע, שבוודאי עבר כדי להיענש כזה. ותו"ת.
* כב:
** כגון מאן -
יש לדון למה לא היה זה לשון הרע. אולי ידע כמה שנא אותה, ורק לא ידע מהו פירוש הקרא.
** אין רואים -
לכאורה, צריך להיות שמי שמסתפר להם רואה אותם.
* כג.
** אין העדים -
אין העדים- הק’ ב.ל. שעדיין יש אחד שאי אפשר להם לבדוק. יש לומר שיותר רע אם יש יותר פסולים. לא נראה כן מרש"י, שמשמע שמפרש שמה שהוא רע הוא שיהיה דין שבו דנו פסול. אז, נראה שהוא שיותר מצוי שיהיה נמצא פסול, שיש שני יכולתות.
** סעודה -
זה חידוש, שאין פסול שייך בזה כמובן (לא יהיה הסעודה פסולה). ותו"ת.
** כשזה -
פשוט שר"ל זה, שאל"ה, לא ת’ לק’.
** דקבליה -
נראה שאפשר שרבנן סברי שמה שהאמינו אינו עשוה שום חלות שיכול לחזור, אלא הוא ראיה שהוא איש נאמן. כיון שכן, פשוט שאינו כל כך ראיה.
* כג:
** שלשה -
צריך ביאור למה אין אומרים שבזה פסול לשאר בנינ אדם. וצריך לומר שכיון שהוא על כל פנים
** חזו לעלמא -
אומרים אחרונים צד בדין קבלה שיכול לעשות אותו עד. אם כן, מסתבר למה שייך מה שלפני כן היה עד.
** כגון שקרא -
לכאורה, לשון זה אינו דווקא, ש,כמו מתחילה, רק אומר שפוסל אותו, ואינו מחדש כלום. ויש לומר שמחדש שפוסל אותו, ואינו מכחישו. עיין בלשון רש"י שלא משמע כן, שאף לפני זה אומר שפוסלו. והיינו צריכים לדחוק שרש"י רק אומר שיבטל עדותו.
** כבר העידו -
זה יותר טוב לפי הצד שפסולם הוא חשש משקר. בלי זה, צריך לומר או כצד שני שברשי או לומר שכיון שחל, חל, ואף כאן, כיון שנתקבל, נתקבל. ותחשב.
** נקיי -
יש להעיר שממימרת ר"י, היה משמע שהוא חוב, אבל מזה משמע שהוא רק מדת חסידות. ותחשב.
* כד.
** מיגו בינייהו -
יש לדון אם רק אומר שיש בינייהו אם צריכים לומר מגו כאן או אף אם אומרים מגו במק"א (כמו אם אין לחלק שבזה יש נגיעות ובזה אינו בנגיעות, אלא שפסול לשניהם, ונמצא שאומר אמת באחד). לשון רש"י נראה כשני.
** שבבל -
יש להעיר שהיה ריב"ח מחייך על שמועות של בני בבל, ואף שהיה מבני א"י. ואולי אמוראי א"י רק היו נחות לבני א"י אחרים. ודחוק.
** יש להעיר
שלכאורה, שאלת גמרא בפסול כת ראשון הוא גופא יסוד של דין של צורך לברר. אם כן, צריך ביאור איך שואלו. וצריך לומר שהיה צד שרק יכול לפסלו אם כת שני קיים, ואין נפק"מ לדינו, אלא לפסול אותם לשאר דינים.
** במחשכים -
וא"ת הרי רואים מכמה גמרות (ב"ק, סוכה, וכדומה) שהיו אמוראי בבל גדולים. ויש לומר שחולקים. גם יש לומר שהיו גדוליהם גדולים, אבל רוב ת"ח לא היו גדולים. גם יש לומר שהיו יותר חריפים, אבל לא ידעו כל כך (וכן מסתבר, שמי שקשה עם חבריו יעשה חפיף). ויש לדון.
** בבל -
אולי לכן סבר ר"י שר"כ היה מחייך בו (בסוף ב"ק), שידע שבא מבבל, ושהיה דרכם להיות יותר קשים.
** *
כשבוחרים דיינים, לווה בוחר דיין ומלווה בוחר דיין. הדיין השלישי נבחר לר"מ על ידי הדיינים ובעלי הדינים[fn:4] אם הדיין הוא מערכאות שבסורא, ר"מ סבר שיכול אחד לפסול דיינו של חברו, ורבנן סוברים שאינו יכול. אם הדיין הוא מומחה, אינו יכול לפסול אותו. כמו כן חלקו רבי מאיר ורבנן בעדים, אבל שם יש שלש צדדים במה חולקים: ריש לקיש אומר שחולקים אם יכול אדם לחזור מקבלה על עד פסול (בין אם הוא כשר לעילמא, בין אם הוא פסול). מק’ גמ’ ע"ז מכוח הלשון (שאומר "עדיו,” אף שאמר "דיינו"). ר"א מפרש שחולקים כשבא עם אחר לפוסלו מפני פגם משפחה (וחולקים אם נאמר שעל המשפחה מעיד, והוא כשר, או על העד מעיד, והוא פסול). רבי יוחנן אמר שחולקים כשאמר שיש לו שני כתי עדים, ובעל דין מצטרף עם אחר לפסול הראשון. חולקים ר"מ ורבנן באם צריך לברר (ולהביא כל ראיות שאומר). יש שני דרכים ברש"י לפרש את זה. הראשון הוא שרבי מאיר סבר שצריך לברר, והוא שצריך להביא כל ראיה שאמר, ואם הביא ונפרך, עדיין דינו קיים, שהביא אותו. אם כן, אם כיון שצריך לברר, יודע שיביא כת שני, ואינו נוגע. רבנן סוברים שאינו צריך לברר, ואז אין לנו הוכחה שיביא עוד כת, והוא נוגע. הדרך השני הוא שצריך לברר או שאף אם אחד מראיות הובא, אבל נפרך, בטל דינו. לכן, חולקים בזה, שאם אינו צריך לברר, יכול לפסול כת, שהרי אינו נוגע, אבל אם צריך לברר (כרבנן), אינו פוסל עדיו, שעל ידי זה, פוסל כל דינו. שואל גמרא מה הדין אם נמצא שהכת השני פסול אחר שפסל ראשון (ואז נמצא נוגע). לא ברוור מה משיב גמרא, אבל רש"י רוצה לומר שאומר שעדיין כשרים. (יש מוסיפים שאולי אף בכעי"ז, יש כוח לבעל דין לפסול רק במגו שפסל דיינו (אם אמר, ונמצא, שדיינים היו פסולים. גם אומר כן על פסול דיינים, שצריך מגו. מפרש גמרא שיש נפק"מ בין זה לחולקים באם צריך מגו, ואם מגו מהני בדר"כ.)
יש עוד מחלקת באם צריך לברר, והוא שחולקים רשב"ג ורבי אם מי שטוען שטר וחזקה צריך להביא שניהם. אפשר שאף מי שסובר כאן שצריך לברר יסבור כרבי, ששם חזקה בא מכוח השטר, והוא ראיה אחת.
יכול מלוה לכוף ללוה לדון בעירו, אבל לא בערכאות שבסורא (לחד צד בגמרא), ולא אם אין בחירת לווה מטריח למלוה (כמו אם רצה ב"ד שבעיר מלווה).[fn:5]
ת"ח שבא"י היו נוחים זל"ז בהלכה, אבל שבבבל היו קשים זל"ז. אומר גמרא שמחמת זה היה תלמודם של בני א"י עולה בידם, אבל לא של בבל.
** אמר לו -
כברו הוא מי שאמר כן, שהוא התובע שבועה. ותחשב.
* כד:
** כרבי יוחנן -
מעניין שיותר רוצים שיהיה כרבנן משיהיה כרבי יוחנן, אף שהל’ כר"י נגד ר"ל. ואולי אין כל כך מקור לכלל זה, ויותר קל לחלוק עליו. ותחשב.
** ילמדנו -
יש לדון למה לא הביא ראיה מזה. ונראה שיש לדון מה מפרש רש"י למה לא דוחים ראיה זה, אם הוא שכיון שהיה חולק על ר"י, לא היה פוסק להלכה, או שהיה אומר לשון של ביאור מח’ אם היה מחדש דבר. אם נאמר כדרך שני, אין להקשות. אולי אף אם נאמר כדרך ראשון, אינו קשה לר"נ, שהיה דיין מומחה, לפסוק. ויש לדון אם הוא אותו ר"נ כמובן (שהוא מח’. רש"י לא סובר שהוא אותו ר"נ, ואז אולי צריך לומר רק שהיה ר"נ זה קודם רבא. ותחשב.)
** איכא דמתני -
אין כל כך שווה בין שני שמועות אלו, ואז צריך ביאור למה אומר שזה בחילוף זה נשנה; לכאורה, שניהם נשנו, ושניהם אמת. ויש לדון.
* כה.
** יש לדון למה
רמי מוקים שיש רבנן החולקים על רבי יהודה, ולא שהוא ר"ט. אולי סובר שאין חידוש לומר שהוא רבנן, ואפשר שסובר שאין ר"ט אומר כן בכלל, אלא רק בענין נזירות. זה יישב אולי כמה גמרות שבו משמע שהוא רק בנדרים.
** מלוה הבאה -
נמצא שמחליפים מלוה בחיריק למלוה בפתח. מעניין שיטעו בזה, שלכאורה לא כתבו אלא שמעו. ויש לדון, שנשמעים קצת דומה.
* כה:
** לא מוזפי -
יש להעיר שלכאורה זה אסור כיון שהוא מתנת חנם. לכאורה, רצה לומר שלא מלווה להם כלל.
** בת הכי -
נראה מרש"י שהענין הוא שחושבים שלא יכול לעשות כן בבהמה, שכן בהמה יהיה נרדף מחיות, ואינו טוב לבהמה. מת’ שיכול לעשותו בשור חזק זה. ותחשב.
** חמסן -
יש לדון למה אין אומרים שזה דאו’, שהוא קנאה. וצריך לומר שר"ל- וכן נ’ מרש"י- שאין פסולו דאו’. ואף זה צריך ביאור למה לא.
* כו:
** רבי יהודה -
יש לדון אם צריך בנים לירושה או לקורבה. יש נפק"מ אם מתים (שיורישו בקבר לו).
** עד שיזומו שניהם -
יש לדון למה צריך זה, שצריך עד אחר כיון שבלי הוא, אין גמר דין, ולא יזום. ואולי היה אפשר לו למצוא עד אחר, אלא שאותו עד לא יזום כמו אחיו. ותחשב ותבין.
** יש לדון
אם דורשים ו"ו לרב מריבוי לחוד או שעושה ש"בנים" שני קאי על מי לא יעד אבות עליהם (אבות על בנים ובנים). גירסא שלנו משמע שהוא ממשמעות, אבל רש"י לא גורס כן.
* כח.
** מעניין שבא גמרא
לבאר לשון של סתם גמרא (בן חמותו), ורש"י אומר שהוא רב. ותו"ת.
** בחדא -
כל סוגיא זה מניח שיותר יש לפסול שני לשלישי, אף שדורם יותר קרוב. ותו"ת.
* ל.
** מיחזי -
לכאורה, לא נראה כן לבני אדם, שלא יודעים, שהרי לא הולך רכיל. ויש לדון, שאולי מבינים שלא יכול להיות שלעולם כולם מודים זה לזה. גם יש לומר שהיו בעלי דינים שם בדיון של בית דין, ואותם בעלי דינים ידעו. ותחשב.
* ל:
** בתרא ידע -
לא הבנתי קושיא זו, שיודעים ששניהם טוענים על חד מנה, ששני העדים טוענים שהוא על מנה שהודה לראשון- ראשון טוען כן כיון שכל מה שיודה לראשון הוא, כמובן, מה שהודה לראשון, ושני טוען כן כיון שאמר לו כן. אז, כיון ששניהם טוענים הודאה על דבר אחד, יהיה עדות. ותחשב.
** יש לדון
למה נחלק בין ציורים שבהם מודים חכמים לציורים שבהם חולקים:
1. אולי סוברים רבנן שחיוב לשלם מחמת מנה זה חלוק מחיוב לשלם מחמת מחנה אחר.:
  1. סבר שחייב לשלם אותו מנה (או חילופו). אז, עצם החיוב חלוק.
  2. סיבת החיוב חלוק, ובזה חלוקים שני החיובים.
2. אולי מודים רבנן אם יש חילוק רק בסימן, אבל הסיבה להדין שווה, כיון שסימן אינו כל כך חשוב. זה מניח שכל אלו סימנין. לא נראה כן בבכור. אין לומר שזה מוכרח שהוא בהמה חלוש, שיכול להיות שבא משום אונס שקרה לו. ואולי מגלה שה’ לא רוצה בהקרבתו.
ואם תאמר זה גלגל החוזר, שאיך מגלה כן (אי אפשר שנפסל רק מפני גילוי זה). ויש לומר שמגלה כן כיון שתורה אמר שפסול, והוא מפני שידע תורה (רצה לומר, אמר ה’ בתורה) שכשנותן בו מום, כוונתו הוא להודיע כן לבני אדם. ותו"ת.
* לא.
** מכחשו -
נמצא שאין טעם של ר"י שסובר שכל חיוב אחד, אלא שמניח שעל מנה אחד מדברים. שוב הבנתי שנראה שכאן אומר זה שמה שאמר חברו לא קרה, שמעידים על זמן אחד, ולכן לא יהני.
** בההיא -
לכאורה, לא אומר כמש"א לעיל, שאין סברה לחשוב שהלכה כרשב"ג בדיעבד, שאינו רבים (ויש לדון, שהלכה כר"ש בכל מקום אחר).
באמת, יש לדון מהו הצד לומר שהלכה כמותו שצריך לומר שהלכה כרבנן. ויש לומר שכבר ידוע (או זה גופא בא ללמד) הכלל שהלכה כמותו בכל מקום.
* לב:
** אחר"א ללוד -
אין אלו בחד זמן.
* לג.
** כאן שטעה -
צריך לחשוב מה לנו בזה, שבשני המקומות, בוודאי אינו נכון, שהרי מחייבים אותו להחזיר את המעות. אם כן, קשה למה נאמר שדין אחד קיים ודין אחד לא יקיים. זה גם כן שייך לקמן גבי טועה בדבר שצדוקים מודים בו. ונראה אולי שמה שאי אפשר לחזור דין הוא שכיון שכבר עומד מאד להיות לו אותו חפץ, כבר זכה בו, ויותר קשה להוציא אותו ממנו. נראה שאם עומד הדין להיות בטל, שקל להבין הטעות בו, לא זכה בו, ויכולים לבטל אותו. על פי זה, נראה שיש לבאר גם כן למה אינו בעיה לחזור לזכות, והוא שלא זכה שום אדם בזכות כשימות (ויש לדון, שאולי גואל הדם זוכה, כמה שמשמע מגמרא לקמן).
* לד:
** האי ביום -
היה אפשר לומר שאחד לתחלתו ואחד לסופו, ולהוכיח שאין לחלק על פי קרא שאומר שהוא בכל זמן.
** דין נחלות -
צריך ביאור מהו חידוש זה, שהרי פשוט שדינו צריך להיות ביום. ויש לומר שמחדש שנחשב דינו דין. ויש לדון. גם יש לומר שאינו מיותר, אלא אומר שהוא ביום כיון שהוא ביום. ותחשב. לא משמע כן מלשון גמרא.
* לה:
** רבא -
רבא בא להוכיח שאי אפשר לעשות קו"ח כזה. יש לדון איך מוכיח כן, שמביא קל וחומר חלוק, ומוכיח שאי אפשר לעשות אותה. אולי זה מוכיח שרק אותו קו"ח אינו נכון. ותו"ת. ועיין לקמן ברש"י.
* לו.
** כל ימיו -
וא"ת אף רבי לא היה כן, שכשהיה תינוק, לא היה גדול מאביו. ויש לומר שאומר שלא היה אחד בכל ימיו שהיה גדול ממנו בגדלותו (ולא באותו שעה). ותחשב.
** רב אדא -
נמצא שהיה חי בזמן אחרון. ועיין בקידושין (גבי מיתת רבי). ותחשב.
* לז.
** שדרך -
לא הבנתי איך זה מגלה שהוא בטיבורו של עולם (וגם איני יודע פירוש של מילת "שררך").
** הכל -
יש לדון מה רצה לומר:
1. אומרים פסקים, והכל נהנים מזה, שהם השומרים שדברים יהיו טובים.
2. מבארים דברים שכל בני אדם נהנים מבם, שהם קלים להבין.
לשון "טעמים" משמע כצד שני.
** לפיכך -
יש לדון אם קאי על מה שכל אחד עולם מלא (שצריך אדם להכיר בחשיבותו מחמת זה) או במה שכל אחד חלוק מחבירו, ואז, צריך לומר שיש דבר שרק הוא יכול לעשות. רש"י נראה כראשון. מסדר המשנה, משמע כשני.
גם משמע כן ממה שאומר ש"בשבילו" נברא. לצד שני, אומר שיש צורך לו בעולם, אבל בצד ראשון, לא מוכיח שהעולם נברא בכדי שיעשה מה שיעשה, שלא קאי על שום דבר המיוחד בו. ואולי רק סומך על לשון "עולם" שהוא דומה. ודחוק.
ויש להעיר שלכאורה הנחנו בכל הצדדים שהלימוד שצריך אדם לדעת הוא נלמד ממשנה. היה אפשר לומר שאין אותו לימוד במשנה, אלא צורך לו ללמוד הוא במשנה (כיון שאדם כל כך חשוב, צריך להכיר בגדלותו כדי שיעשה טוב). אולי לשון המימרה קצת משמע יותר כזה.
* לז:
** שני מיתות -
מעניין, אז, שכשאמר כן לו שמעון ומת, לא מת מחמת מה שראה וידע שמעון. ויש לומר שיש דין מיתה על כל מי שחייב מיתה, אלא שנדחה מחמת שיש לו זכות של א להצטער, ואז ממיתים אותו באופן קל (אף שיש סיבה להמיתו באופן שיצער אותו יותר).
נראה כן מלשון גמרא שדורש קולות מיתות מ"ואהבת לרעך,” שמשמע שיש סיבה להחמיר, אלא שנדחה. ויש לדון, שאולי רק אומר שהיה יכול לבחור. ותחשב.
אפשר, אז, שמי שחייב מיתה יותר מצער מאבד זכות שלא להיות מצטער. אם כן, יש לומר כאן, שיש כבר חיוב מיתה חמורה עליו, שכבר איבד זכותו, ואז אף על חיוב שני חייב מיתה חמורה. ותחשב.
ונראה שאפשר שזה ענין של מה שאומר גמרא ש"מלקות במקום מיתה,” והוא שיש סיבה לחייב אותו מלקות, אלא שנדחה מפני זכותו להיות חי (משא"כ בשאר חיובי מיתה, ששם גם מנותק אותו זכות).
* לח.
** אנו בני -
ואם תאמר מה בכך. ויש לומר שאז לא יעמלו צדיקים. גם יש לומר שאז לא יעמלו בני רשעים, ולא ישובו רשעים. ותו"ת.
ודע שלכאורה, קשה להבין איך יהיה כן, שאיזה משפחה יש שכולו צדיקים או כולו רשעים. וצריך לומר שרק סוברים שהם יותר עלילים להיות צדיקים (שהוא יותר קל להם).
** טובע -
יש לדון, שאין כולם בדמותו, שאף כולם באים באים מחווה. משמע מכאן שהיתה חווה נראה שווה לו. כן נראה, שהרי באה ממנו. ותחשב.
** למצוה -
מעניין, שלכאורה, עדיין היה פנאי עד שבת, שהרי הוליד בנים וחטא באותו זמן. לולי רש"י, אולי היה אפשר לומר שהמצווה הוא הכנה לשבת. ודע שבכ"ז, יש לדון איזה מצווה יש, שלא מצֻווה. ויש לומר שאף על פי כן, הוא טוב. גם יש לומר שאילו לא היה חוטא, היה ה’ מצווה אותו בזה. ותחשב.
** שותף -
יש לדון, שכבר היו מלאכים.
** מינים -
מוזר שמניחים מינים שמה שאומר תורה מתי נברא הוא נכון, ולא מה שאמר תורה שה’ עשה כולו. ויש לומר שטוענים שלא אומר כן תורה. ותחשב.
* לח:
** דור -
יש לדון על איזה אמרו כן, שאם על ראשון, צריך ביאור למה שאל עוד (ואולי היו יותר רעים (ואולי רק מחמת שכבר בא רע, ועשו עוד רע)), ואם על שני, רציך ביאור ל"ל על ראשון (ויש לומר שרק על צירוף רעתם אמרו כן).
** ראשונים -
יש לדון איך ידעו זה. ואולי ה’ אמר להם.
** אחד לו -
צריך ביאור למה גמרא משיב רק זה. ויש לומר שהוא מציין לברייתא שמתחיל כך.
* לט.
** של זהב -
יש להעיר שלכאורה, אף על פי כן אסור. ותחשב.
* לט:
** אמר"א גדול -
נראה שחולקים על דרשה שלעיל, שלכאורה, לו מוכיחים כלופ מזה, שרק בעובדיהו הוצרכו לזה. ויש לומר שאף אברהם היה צריך לזה. גם יש לומר שלא מכוון לומר שהוא, אז, גדול, אלא שמה שנאמר גביו גדול. לא נראה כן, שאם כן הוא פשוט, ולא ישמיענו קראי. גם קשה מה לנו בזה.
** עודר -
משמע מגמרא זה (עם רש"י) שאין השגחה פרטית לגויים.
* מ.
** מזרח -
מניחים שאי אפשר שהחליפו מזרח ומערב.
** איני יודע -
צריך ביאור למה לא יצרף לבית דין, שהרי, לכאורה, הענין הוא שיצא אמת על פי דיונם. אולי ל איכול לדון ולשקל ולנטור כאן כיון שלא ידוע. ותחשב. גם אולי הוא סימן, שאינו מבין כפי צורכו.
* מ:
** שפיר -
קשה, עדיין למה אין זה תיובתא לאותם צדדים של אביי ורבא.
* מא.
** לכאורה, היה
אפשר לומר שצריך קרא במלקות כיון שהיה אפשר לומר שרק גבי מיתה, שהוא כל כך רע, צריך לדעת שהוא חייב כדי לענשו. ותו"ת.
** יומת המת -
אם מתיר את עצמו למיתה, לכאורה, יודע שהוא אסור. אם כן, קשה למה צריכים קרא להתראה (רצה לומר, הצורך שיידע שהוא מזיד יוכל להילמד מקרא זה). וי"ל שלא היינו דורשים את זה בלי קרא של התראה. ותחשב. גם יש לומר שחושב שחייב מיתה אף שלא חטא בזה. ודחוק. ואולי חושב שבית דין יטעו בזה ויהרוג אותו. ודע שיש לדון- ומש"כ יהיה, לכאורה, תלוי בזה- אם צריך לקבל שימות או שראוי למות או שניהם. ותחשב על זה. בפשטות, לשון הדרשא משמע שרק צריך לקבל שהוא עומד למת, והוא, לכאורה, שימות. ותחשב.
** בסודר -
נראה שיש רבותא בזה, שאין חילוק באופן מיתה על פי צבע של הסודר. אם כן, היה אפשר לומר שלא מכיר בזה. צירו שנקט גמרא כשאמר דין זה לעיל היה באיזה דבר חתכו להמיתו, ובזה, לכאורה, יעשה חילוק במיתתו. ותחשב.
** באשה חברה -
וא"ת אולי יכולים לומר שלא התרו אותה כדי להורגה, אלא כדי שלא תחטא. ויש לומר שמוכיחים ממה שאמר לבית דין שהתרה. ויש לדון מה אם לא אמר, ובית דין שאל אותו.
* מג.
** ג"ש -
לכאורה, הענין הוא שמילתא דאתיא מג"ש טרח וכ’ ליה קרא.
** בערב פסח תלאוהו -
צריך ביאור למה קרא אותו תלייה, ולא סקילה, שלכאורה, המיתו אותו בסקילה (אלא שאחריו היה נתלה, אבל זה, לכאורה, לא היה העיקר).
* מד:
** לעז -
לכאורה, לא חושש על מה שאין לו כפרה כיון שהוא הזיד בזה.
* מו.
** בן ולא איש -
עיין במה שפרש"י. מעניין שמה שיכול להוליד עושה שאדם איש. ונראה שאיש רצה לומר מי שגדל כל צרכו. אם עדיין לא יכול להוליד, לא גדל כל צרכו. (ועדיין צריך לומר שאינו כל כצרכו ממש, שהרי לא צריכים שיש לו wrinkles. ותחשב.)
* מז.
** שריפא צרעת -
ק"ק למה לא מנים מה שגרם להולדת בן ומה שעשה שמן בכל הכלים, שזה מציל מאין לו בנים וזה מעוני. ותו"ת.
** רשע אצל צדיק -
יש לדון אם זה מחמת הרשע, הצדיק, או שניהם. ותו"ת.
** בדין -
צריך ביאור מה לנו בזה. ונראה שדין עושה גם שאדם מחסר זכותו לחיות. אז, אין כל כך רע נגדו, שאינו נטילת דבר שזכה בו. ויש לדון.
** גם נראה
לי לבאר שבאלו שדינו שנהרג אבל לא צריך להיות נהרג (כמו במורד במלכות או בקנאים פוגעים), נראה שאינו חייב מיתה, אלא שחסר זכותו לחיות. ותחשב.
* מח.
** הטיל -
עדיין קשה למה לא אמר "הזמין,” ולא "הטיל.”
* מח:
** התם מחמת מררהו -
נראה שהענין הוא כך:
יש לדון מהו הזמנה:
1. מיש הוא בעל חושב עליו לדבר. זה עושה דין.
2. עומד הוא לדבר, וזה עושה דין.
גמרא סבר כראשון בהוה אמינא. דוחה כשני, וכיון שהם רק מרים, לא יתנו לו באמת, שהמררות ילך. ותחשב.
** היינו… וינס -
מעניין שמניח שהיה מת מחמת מורד במלכות, שלכמה מן הצדדים שמבאר גמרא, מת מחמת חיוב בית דין (שהרג אחרים).
** אבנר -
קשה, שעדיין היה צריך להביא עדים והתראה (ואולי סבר כריב"י שאין חבר צריך התראה) וכדומה על הכל ולדון בו בבית דין. ואולי עשה כן. מעניין, אז, שלא ידע עליו המלך.
* מט.
** נטה -
צריך ביאור למה מה שנטה אחר אדוניה לא די לעשות שהיה מורד במלכות.
** אילמלא -
נראה שחולק בשני הנקודות, שאילמלא דוד, כבר היו איצטגניניו, ואילמלא יואב, כבר היה איצטגניני דוד. ויש לדון.
* מט:
** למצווה בעלמא -
יש לדון מה מבוון לומר:
1. אולי אומר שרק מונה דברים שבהם אומר סדר מפני דבר חשוב, ולא מפני מצווה בעלמא. (ונראה שאולי יש לדון אם "לא נאמר על הסדר" אומר שלא נסדר כן לסיבה חשובה או שאין ללמוד כל כך מסדרו. ותחשב.)
2. אולי אין מצווה סיבה חשובה שיעשה שינקוט אותו סדר. אז, צרךי לומר שאינו על הסדר, שלא היה נותן סדר מזה. ויש לדון למה לא. ותחשב.
** ואי אפיך -
אם כן, לרהבדר"י, יש למנותו, שהוא למצווה. אם נאמר שמונה אותו, צריך לומר שבא לאפוקי דבר אחר, כמה שממשיך גמרא (ואולי לכן ממשיך).
** לאפוקי -
אם קאי רק על רבא, ולא על רב הבדר”י, היה לו לומר שאף בא לאפוקי משל ר"פ ורהבדר"י. ואולי זה פשוט משקו"ט של גמרא.
** אקדמיה קרא -
נמצא שאי אפשר לומר ש"לא על הסדר" רצה לומר שסידרו ראנדום. אולי רצה לומר שאינו סיבה חשובה, ואולי רצה לומר שלו מלמד דבר חשוב. גם יש לומר שאומר שאינו סדר הקדם. וא"ת אף משנתינו אינו סדר הקדמה. ויש לומר שמה שמי שחייב שני מיתות נידון בחמורה הוא מפני שצריך לדון עלו ולעשות אותו ראשון (וכיון שנעשה, אי אפשר לעשות השני). ותו"ת.
ועיין ברש"י על המשנה, שמשמע שסדר משום חומרא עצמו, דלא כמש"כ. ותחשב.
* נ.
** איזה כוח -
קשה, שיש על זה פירכא, שאין ממון מדיח אבוד.
** שכן הוקש -
קשה, שמי שפוגע בכבוד ה’ ממש, ועובד ע"ז בוודאי חמור ממי שרק פוגע במי שהוקש כבודו לה’. ונראה שאולי מכוון למה שאמרו חז"ל (חושב אני שהוא ירושלמי בפאה) שגדול כבוד הוריו מכבוד ה’, אלא שלו רצה לומר כן על ה’. ותו"ת.
** מרגלא -
יש לדון ביסוד לשון זה:
1. אולי שורשו "רגיל,” ואומר שהיה רגיל לומר כך.
2. אולי שורשו "מרגלית,” ואומר שהיה מאמר זה חשוב לו.
* נא.
** עובד כוכבים -
קשה, שעובד כוכבים לא תפיש בו קדושין. ותחשב.
** איהו אישתראי -
קשה מה נאמר בבעל מום. ואולי במינו אישתראי (מה שאין כן באשה, שנחשבת מין חלוק מזכר).
** אישתראי -
נראה שאולי הענין של זה הוא שכשנעה אותו מעשה מישראל, יש לו שם איסור, דהיינו ששמו (definition) שלו אומר שהוא אסור לעשות. בכהן, אינו כן כל כך, שכיון שלפעמים מותר לעשותם, אין שם שלהם יכול לכלל איסור. כיון שאין שמם כל כך של איסור, לא עושים כל כך מה עושה תוצאות של איסור.
** ללוי -
ק"ק למה לא הזכיר מה שהיא מחוללת לעולם במה שלא יכולה לאכול חזה התנופה (כמה שמפרש אותו גמרא ביבמות). ואולי רק א"צ לפרש, ואז נקט מה שהוא מפורש בקרא יותר.
* נב.
** נוהגים בו -
יש לדון אם זה החילול שהזכיר הקרא או אף זה תוצאה של חילול.
** ננהיג -
ק"ק למה חשבו שינהיגו, שהרי יבוא בירושה, ויהיו בני משה מנהיגים. ויש לומר שינהיגו עמהם, כמו שאהרן הנהיג עם משה. לא נראה כן, שאם כן לא ירצו במיתת שניהם, אלא רק של אהרן. אלא, צריך לומר שרצו להיות המנהיגים היחידים. עוד יש לומר שידעו שלא היו ממלאים מקום משה.
** והא כתיב -
הוה אמינא של גמרא משמע שנשמת אדם נקרא עצמו נגד שאר גופו.
* נב:
** אף אני -
קשה, שאם זהו סברתו, למה אמר במשנה טעם אחר. ואולי במשנה אמר שהוא ניוויל בלי צורך. קשה, שהוא אף מיתה בלי צורך. ותחשב.
ועיין בתוס’ שמעורר את זה.נראה לבאר שאולי ניוול הוא לעשות כחוקי גויים (או שסיבת איסור של חוקי גויים הוא שהוא ניוול). עדיין, אז, יש לדון במה שמשיבים רבנן לו, שהיה להם לומר שהוא ניוול ביותר.
* נג:
** דרשת רבא
צריך ביאור. ראיתי שבפעם שעבר, הבנתי שגמרא אומר שאי אפשר למעט מ"אשת אב היא,” שהרי שם כבר מיירי באמו. אין זה מהני, שהרי מה לנו אם מיירי באמו; לא אומר חיוב מחמת שהיא אמו. גם לא נראה מרש"י כן. אז, אולי יש לומר להיפך, שאותו קרא של אמו כבר הזכיר אמו והזכיר אשת אב, ואז מסתבר שידון מה קורה אם יש שניהם, משא"כ אשת אב יהא, שאותו קרא רק הזכיר אשת אב. לזה, צריך לומר שהגזרה שווה הוא מקרא של אם היא (כן משמע מרש"י). ויש לדון למה אומרים יותר שאותו קרא מיירי באשת אב שהיא אמו. ואולי הוא מפני שמיד אחריו דן באמו. ותחשב.
ועיין בברייתא לקמן, שלא משמע כל כך כמש" כ כאן. וצריך ביאור.
* נד:
** גדול -
מעניין שצריך להזכיר זה גבי בהמה, שהרי כל בהמה אינו בר דעת. ויש לדון למה בכלל היה לנו לחשוב שיש חילוק בין גדול וקטן:
1. אולי רק גדול, שהוא בר דעת, עושה ס"ר בביאתו. אז, כיון שבא על מי שאינו בר דעת, נמצא שלא גרם (כל כך) סיבת רעות.
2. אולי רק גדול, שבא לו סימנים, וגופו כבר נגדל, ביאתו ביאה.
נראה שלצד שני יש לתרץ. ותחשב.
** אביי -
לא הבנתי למה לאביי אין אומרים שחייב שנים, שאזהרת נשכב נלמד מקרא אחר של אזהרת שוכב. וצריך לומר שכיון שנלמד ממנו נחשב אחד. ותחשב. אם כן, לכאורה, כן יהיה הדין בשוחט ומעלה (וצריך לעיין בכריתות בדין שני חיובי כריתות עם לאו אחד. וע"ש, שדן בזה.)
* נה.
** מערה בעצמו -
לכאורה, יש שלש צדדים בזה (ויש לדון באיזה צדדים היה דן):
1. פטור:
  1. אי אפשר בחי.
  2. אי אפשר לגמור ביאה.
  3. אולי עצמו חלוק מאדם אחר. ותחשב.
2. חייב אחת:
  1. חיוב של כל העוסק שווה.
  2. עשה רק מעשה אחד לעבור על אלו (ואי אפשר לעשות יותר מזה, ואז המעשים נחשבים אחד).
3. חייב שנים:
  1. רע של שוכב ונשכב חלוק, וחייב קרבן על כל אחד.
* נה:
** תקלה נמי -
משמע שיש ס"ר לקטן. ונראה שאולי שאני כאן שכתיב קרא שחייב אם בא על קטן, וצריך לומר שיש ס"ר. ויש לדון, שאולי יש לחלק בין אם יש בר דעת אחד. ותחשב. (ודע שא"ץ לזה אף מש"כ לבא על קטן, אלא יכולים ללמוד מדין בא על בהמה עצמה, שאין בה דעת.)
** אב"א -
יש לדון אם מביא עוד מקור, או אומר עוד סיבה למה נלמוד מזה ולא משאר ציורים (שיש בזה שני קראי).
* נו:
** יש לדון
אם העביה עם עבודה זרה הוא שאומר אלהות על מה שאינו או מה שעל ידי זה ממעט אלהות של ה’. ותו"ת.
** ולא ענש -
קשה, שבדרך כלל, צריכים אזהרה הנכתב בפירוש.
** ולא ענש -
מעניין, שמצאנו גבי גויים שענש ה’ בלי אזהרה, שכן עשה אחר שהתיר להם את המצוות. וצריך לומר ששם היה סיבה אחרת- שלא יהיה חוטא נשכר.
* נז.
** אורחייהו קא מגלי -
ק"ק למה צריך קרא של "ויצו" עדיין.
** כי השחית -
מניח שצריך להיות שניהם, ולא רק אחד מהם. ותו"ת. ויש לדון, שאולי ממה שלא אמר מוכרח ששניהם אסורים, שאי לאו הכי, היה לו לפרש. ויש לדון, שאולי מכוון לומר שהיו נענשים, אבל לא רוצה להזהיר עוד עליו.
** לצוותא -
יש לדון למה לא אומר שהוא מפני שרצה לקיים כל מין, וכדי לעשות כן, צריך זכר ונקבה מכל המין. ותחשב. ועיין ברש"י, שלא נראה שזהו כוונת "לצוותא.”
** גילוי עריות -
יודעים, לכאורה, שעונש על ע"ז וג"ע שכן עשה בימי מבול. ויש לדון, שזה לא אומר שיש ביד בית דין לענש.
** אזהרה שלהם -
יש לדון למה משניות ישנו לשונם בגויים (שאומר לשון אזהרה) מבישראלים.
** משום דבעי -
א"צ זה עד שמקשה ממקום שאומר באותו ברייתא חייב, שעד זה יש לומר שאזהרתם ה"ה מיתתם.
** והוא הדין לכולהו -
קשה איך לומדים זה מזה.
** פחות משעה -
ידוע שחז"ל אמרו שגזלו בימי נוח פחות משווה פרוטה כדי שלא לחייב. קשה, שלא היה כבר יהודי מעולם, ולא היה כבר מי שלא היה חייב. ותו"ת.
** צערא -
יש לדון מה אומר:
1. מוחל על הממון, אבל אינו מוחל על הצער. אז, על הצער עדיין חייב.
2. מוחל על הממון, אבל לא מחל מיד, ואז היה זמן שבו היה רע.
* נז:
** באדם -
נמצא שעובר נקרא אדם (ואולי הוא מפני שצריך למצוא אדם שהוא בתוך אדם).
** הוי אומר -
יש לדון למה ידרוש כן. אולי הוא מפני שסבר שאין עובר אדם.
** ואי בדינא -
קשה, שאולי סבר שכל מיתתם בחנק.
** נכנסה לחופה -
יש לדון למה אין זה נחשב שייחדה לביאה, כמה שאמר לעיל. ואולי זה רק בשפחה.
* נח.
** ולא באשת חברו -
ק"ק אז למה צריך קרא אחר ללמד איסור ג"ע. ואולי מוסיף על מה שנאמר בקרא זה. לא נראה כן.
* נח:
** הא לאו הכי -
לא הבנתי מה מנסה להוכיח מזה, שלכאורה, לא היה מי שאמר שאחותו מותר. ואולי לרבי עקיבה, אין מקור לאסרו. וצריך לראות אם חייב בו מיתה.
** וכותי חייב -
ק"ק ל"ל הק’ מפחות משו"פ.
** ואר"א -
ק"ק איך דורש שני דרשות אלו מקרא זה (שלכאורה, הוא אותו שיטה שאמר שייקבר).
** אזהרה -
זה מעניין, שלכאורה, זה רק אומר שברייתא שאומר אזהרה מכוון לומר מיתה. ויש להעיר שלכאורה, הדין הוא שאזהרה הוא מיתתם, שנלמדים ממה שמפורש מיתה גבי אחד מהם. אז, יש לומר שרק נקט אותו לשון שאמר לעיל אגב לעיל.
גם יש לומר שאינו מבאר המקור, אלא מבאר הראיה לזה, והוא שממה שברייתא רק אומר אסור במקום חייב, צריך לומר שעל כל שאסור להם, חייבים, שאי לאו הכי, יש צורך לחלק.
* נט.
** האדם -
חולק על ר"ש שאומר שאין גויים נקראים אדם.
** משום -
קשה, שאף חייבים אם גזלו מישראל.
* ס:
** בלתי לה’ -
לא הבנתי איך יודעים שזה לא אומר שלה’ יהיו כל הזביחות, אבל אולי לא שאר עבודות. ויש לומר שאי לאו הכי, מיותר הוא. גם יש לומר שאינו נקרא לבד לה’ אם אחר כך זורק או עושה מלאכה לע"ז. ויש לדון, שזה רק על דבר שכבר שחט לישראל, אבל לא על דבר ששחט סתם, וזרק לפני ע"ז. ותחשב.
* סא.
** באומר איני מקבלו -
מוזר למה יאמר ציור כזה, שלמה יאמר כן האדם; אם חושב שהוא אלהים, ולכן רוצה לעבדו, יקבל אותו עליו, ואם לא, לא יעבדנו. ואולי אומר שאם עובדו ורואה בטוב יקבל עליו לאלהים. ויש לדון אם יחייב על זה, שעדיין לא קבלו בשעת עבודה.
** זובח להכעיס -
ואם תאמר איך זה יותר חייב מעובד לאהבה וליראה. ויש לומר שלא כולל אותו לכל דיני עבודה זרה, אלא רק עובר בלאו (עיין ברש"י, שכן משמע), ואף עובד לאהבה וליראה כן לרבא. גם יש לדון כאן מי רוצה להכעיס, אם רוצה להכעיס את העבודה זרה או את העובדים. אם נאמר כצד ראשון, אולי שאני הכא שמכיר שיש דעת לעבודה זרה, שהוא חי, ועל זה חייב. ותחשב.
* סב:
** רוק הוא -
יש אומרים שהענין הוא שההנאה הוא חלק מן האיסור, וזה בוודאי בא לו. לא נראה לי כן, שאף עשייתו חלק מן האיסור, וזה בודאי בא לו. אלא היה נראה יותר לומר שאף שלא כיוון לעשות אותו מעשה, שפוט שרוצה בו במעט, שיש הנאה היוצא ממנו, אלא שאולי רק רוצה יותר בדבר אחר. בשאר עבירות אינו כן, שאין ידוע רצונו לזה. ותו"ת.
* סג.
** זיבח -
נראה שאולי תלוי באם רעות עבודה זרה הוא שמראה שיש כוח אחר או שמחזק אותו כוח הטומאה. צד שני אומר שאולי נברא כוח הטומאה בעבודה זרה, ואותו כוח נתחזק על ידי עבודתו. אם כן, אולי כל מעשה שעושה לו הוא חלוק, שהוא עבודה חלוקה. ותחשב.
** כתיב ביה כרת -
עיין בגמרא כריתות שכ’, “הואיל וכתיב כרת דיליה במקום קרבן.” לכאורה, זה חלוק מגמרא שלנו. ותו"ת.
** אזהרה לבן סורר ומורה -
נענש עליו, ואז צריך לומר שיכול להיענש על לאו כזה, אלא רק אין רואים שיש בו מכות. יש לדון, אגב, מהו המקור למה שמניחים שכל לאו יש בו מכות. כמובן, לאו שבכללות רק נמעט ממכות, ולא שאינו אזהרה די להיענש עליו.
* סד.
** ולא עבדו אלא -
צריך ביאור למה היה קל להם לעבוד ע"ז, ולא לגלות עריות. ונראה שאולי הוא מפני שאז אינם היפיקריטי"ם, שמאמינים שמה שעושים הוא נכון.
ועיין ברש"י שכ’, “ואל יוכיחו אותנו….” יש לדון אם אומר שלא יוכיח יצרם הטוב על זה (וזה יהיה, אולי, כמה שכתבנו), או שלא יוכיחו בני אדם על העריותץ לכאורה, זה יהיה מפני שדרך בני אדם שלא להוכיח בני אדם שהם לגמרי רעים. ותחשב.
* סד.
** אלא לקבולי -
כמו שדורש גמרא במכות כג:.
** אלא לקבולי -
קשה, שנמצא שאתגורי אתגר, כמו שאומר גמרא בעבודה זרה וב"ק. ויש לומר שלא איתגורי, שהרי רק אין להם רצון, ואיזה טוב בא להם. ותחשב.
** כחלינהו -
נמצא מקור למה שאומרים בני אדם ש"Love is blind.”
** אתם בית ישראל -
יש לדון מי אמר כן. ועיין ברש"י.
** סבטא -
מצאנו אז סבטא שהוא זכר (זה יותר טוב אם נאמר אותו, ולא נקרא אותו).
* סד:
** זרעו -
קשה למה צריך זה, שבן בתו כבנו.
** לעצמו -
יש לדון מה אומר:
1. אדם מוסר את עצמו למולך.
2. אדם מעביר עצמו למולך (ולא מוסר את עצמו לאחר).
3. אדם מעביר את בנו (ולא מוסרו לאחר).
* סה.
** כשאומרים שבעל
אוב מעלה אדם מן הארץ, צריך ביאור מה אומרים. אולי מעלה את גופם. קשה לומר שמעלה את נשמתם, שהרי אינו בארץ. צריך ביאור מה יידע גופם. באמת, אף צריך ביאור מה יודע נפשם, שתלוי בדיון בגמרא ברכות.
** אלא אמר עולא -
עיין בכריתות שלא אומר כן.
* סה:
** מאי לאו -
לא הבנתי קושיה זה.
* סו.
** ואליבא -
ק"ק ל"ל מזכיר מחמר אחר בהמתו (כמו בפרק בתרא של שבת).
** למה לי -
נראה שר"ל שאז הוא נלמד משלש מקומות, ואז אין פורכים מה שהוא. ונראה שייתור זה הוא הסיבה לאותו דין.
** גמר חול -
קשה למה אין אומרים שהקודש הוא המלמד השלישי, ואז יש שלש מקורות. ואולי שם הוא חלוק כל כך עד שאינו נחשב מלמד כלל. וצריך ביאור.
* סו:
** יחדיו -
החילוק בדין שאומר כאן (עיין ברש"י שמבאר יותר) בין אונס לקטן מעניין. ויש לציין לגמרא שאומר שקטן בעצם חייב, אבל חס עליו תורה (הוא לעיל בסוגיית מיתת בהמה (נד)). ותחשב.
* סז.
** ריבה בהם -
יש להעיר שהיה זה קודם סיני, ולא ריהה בהם כבר מיתות הרבה.
* סז:
** אין עוד מלבדו -
יש לדון בזה, שמודה שיש להם כוח לענין אחרים. אז, אינו נכון ש"אין עוד בלבדו.” באמת, יש לדון בכוונת הקרא. צריך לומר שאומר שלענין ניהוג לצדיקים כמותו, אין עוד מלבדו. ותחשב.
גם יש לומר שקרא אומר- והוא אמר- שאין עוד מבלעדי ה’, שמה שה’ רוצה נעשה, אלא שלפעמים לא ירצה ה’ למנוע דבר. לצדיק, בוודאי ירצה ה’. ותחשב.
** אי לאו זעירי -
מוזר שאיש זה כיבד ת"ח, אבל מכר כישופים, והטעה לזעירי. ונראה שלא כיוון להטעות לבני אדם (עדיין מוזר איך עשה כישופים. ואולי רק קנה מאחרים), אלא מכר אותם לדברים מעניינים. ותחשב.
** כדר"ח -
מעניין שזה נקרא כישוף, שאינו נעשה ע"י כישופים. וצריך לומר שנחשב כן כיון שהוא עושה דבר תמיהה.
* סח.
** בן סורר -
נראה לי לבאר שיש שני חלקי עונש; אחד הוא שאבד זכותו להיות חי, והשני הוא סיבה להמיתו. אולי בכל מלקות יש ראשון (ולכן אומרים שהוא במקום מיתה. וגם אפשר לומר זה להפך, שיש רק שני), אבל לא שני, ולן לא ממיתים אותו.[fn:6] נראה שאולי בבן סורר ומורה, מה שקרה הוא שאיבד זכותו לחיות, שלא יעבוד את ה’. אולי, אז, כיון שיודעים כן, ויודעים שאין צריך כל כך סיבה למות, שאין כל כך סיבה לזה, יש סיבה לרבות קטן, שאולי רק אין לו סיבה למות. ותחשב על כל זה, שיש בו יסודות מעניינים.
* סט:
** בן כמה -
נמצא שהיו מולידים קודם יג. אז, בודאי צריך קרא למעט קטן, אף שאינו אפשר עכשיו, שהיה אפשר בזמנם.
* ע.
** שהכל -
יש לדון, שזה לכאורה הוא רק ביאת פנוי ופנויה (שלכאורה, לא תשא, ותעשה לעצמה איסור חמורה), וזה רציחה. ותחשב.
** לנחם -
יש לציין לגמרא כתובות ח:.
** גפן -
מעניין שמניח שהיה בו יין, ולא רק ענבים. ואולי הוא כמו עולם הבא, שאומר בברכות שיש יין בענבים. ויש לדון, שגם אומר ש"עין לא ראתה.”
* ע:
** דבר מצוה -
ק"ק למה אין זה כולל מעשר שני וכדומה. ותחשב. ומבואר שאינו כוללו כיון ששם לא אומר קרא זה. ותחשב. ואולי אינו מצוה לאכול אותו, אלא אם רוצה לאכלו, צריך לעשות אותו באופן מיוחד.
* עא.
** אני ראיתיו -
זה רק אומר שהיה מי שלא סבר כר"י או כדומה, אבל לא שרבי יונתן לא סבר כר"י.
** אלמים -
קשה, שאז אין קולם שווה.
* עא:
** אם מזנגמר דינו ברח -
קשה איזה ראיה ירצה להביא מכאן שלא ייסתר מרישא.
* עב:
** חבר אין צריך -
נמצא שמניח גמרא שרבנן החולקים אומרים שמניחים שכל אדם מזיד[fn:7]. אז, אף כאן מניחים כן, ויכולים להרוג אותם. לכאורה, הסיבה שצריך לדעת אם הוא מזיד הוא שאם הוא שוגג, אין להמית אותו. יש לדון אם זה מפני שאז אינו חייב או מפני רבי יונתן בן שאול (שאין צורך להמיתו). יהיה נפק"מ אם לא מאמין לנו כשאומרים שהוא אסור. ותו"ת.
* עג:
** משום דבאי -
בדרך כלל על כעין זה אומרים שכל אחד יוכיח. שו"ר בתוס’ כאן. ותחשב.
** בהמה ושבת -
לכאורה, אינו קשה איך דבר אחד ממעט שני דברים, שאומר "רק זה, אבל לא מה שאינו זה,” והרי שניהם אינו זה. אבל קשה למה לא אומרים, אם מניחים כן, שאף ממעט עבודה זרה. ותחשב.
** אפיגמה -
אם כן, רק מצילים מחד דבר- רציחה. אם כן, בטל הקל וחומר של רבי שמעון, לכאורה. אז, אף אין צריך קרא למעטו. ואפשר לומר שזה נודע רק אחר הקרא.
** חד למעוטי -
אם כן, צריך לומר שאף הם סוברים שמזהירים מן הדין. ואולי אף זה נלמד מקרא זה.
* עד.
** רבי יונתן -
מעניין ששמו יונתן בן שאול, שכך היה שם של יונתן בן שאול שבתנ"ך. ונראה שאפשר שהיה שמו יונתן בן שאול, ולא שהיה שם אביו שאול, ושמו יונתן. כמו כן מצאנו בגמרא שבת בבני אדם שקרא ולניהם בשם נתן הבבלי. ותו"ת.
** פגם הדיוט -
משמע שע"ז ממש פוגם בה’. ואין לומר שפוגם בה’ כיון שה’ לא רוצה בו, שלכאורה, כל עבירה כן. ותחשב.
** יעבוד ואל יהרג -
צריך לחשוב למה אין זה שמציל את עצמו בנפשו. ותחשב. לכאורה, החילוקים כאן הוא שאין כל כך צורך לו למות, שלא התחיל בעבירה, אבל לאידך גיסא, יהיה יותר טוב אם ימות, שאף לא התחיל בעבירה. ותחשב.
* עד:
** בעי ר"י -
צריך ביאור למה יחשוב כן.
** קרקע עולם -
ק"ק, שגמרא בב"ק אומר שהנאה כמעשה, ולכאורה, נהנית. ויש לדון.
** על קדושת השם -
משמע שהסיבה לאלו הוא מצוות קה"ש. לולי זה, היה אפשר לומר שהוא שעבירה יותר חשוב מחייו. נראה שקה"ש הוא הסיבה לדין פרהסיא.
* עו:
** מצמצם -
יש להעיר שאין זה כל כך מחודש, שהוא דומה מאד לציור רגיל של מיתת אדם באבן. באבן, אדם גורם שאבן ילך, וזה גורם שימות האדם. כאן, לא גורם שחמה ילך, אלא שחמה הולך לאדם. אז, יש שני סיבות למה הוא חייב:
1. הוא גרמתו בשעה שגורמו (ולא שוהה אחר כך).
2. כמו כוחו, הוא משנה אותו קצת, שעושה שהוא על אדם זה. ותחשב.
* עז.
** כפתו ברעב -
עיין ברש"י. ואולי הענין הוא שצריך לעשות סיבה למיתה, ולא רק מניעה לסיבת החיים.
* עז:
** ואפילו הוא -
קשה למה אין זה כמצמצם, שלכאורה, יש סיבה להמיתו, כמו חמה, והוא עושה שימית אותו. ואולי כיון שלא משנה מקום האיש, אלא דבר שימנע אותו לבוא אל האיש יש חילוק. צריך ביאור למה.
* עח.
** מעצמו -
צריך ביאור למה אין זה כמצמצם. ואולי הוא שנחשב הנחש סיבה כיון שמחליט לעשות כן, משא"כ בשמש. ותחשב.
** אמדוהו -
יש לדון מה סובר ר"נ:
1. מזה רואים שלא מחמתו מת.
2. זה נחשב יצא מבית דין זכאי (שהיה עומד לחיות, שהקיל).[fn:8]
אם נאמר כראשון, רבנן או חולקים מה מניחים או כמה מחמתו צריך להיות כדי לחייבו.
אם נאמר כשני, רבנן או חולקים מתי אומרים שיצא מבית דין זכאי (שאין זה תחילת דיונו), או אם מניחים שיחיה. ותחשב.
* עח:
** הוראת שעה -
לכאורה, הברייתא שמביא לא מוכיח זה, אלא מביא אותו להוכיח ידיעת משה (שדן בזה).
* עט.
** כותי -
מעניין שקבוע שייך כאן, שלכאורה, הפטור הוא שהוא התראת ספק. אם כן, לכאורה, ייתלה בכמה מסתבר הוא להיות שיהרוג כותי, ולא שום דין ביטול. ותחשב.
* עט:
** מפקא -
יש לדון, אז, איך מפרש את הקרא (ולמה מניחים שאין ר"ש מפרש את הקרא כן).
* פ:
** מותרה -
לכאורה, צריך להיות נגד ריב"י, שעדיין הם מזידים. ונראה שיש לדחות על פי מה שנכתוב בדיבור הקודם. ותו"ת.
** מותרה -
ואם תאמר איך יהיה סתם יותר טוב מזה. ויש לומר שאם מזהיר לדבר חמור, יש לומר שאומר שכשם שלזה טועים, אף לחיוב מיתה טועים.
* פא.
** קטילא -
אולי פטור כיון שתורה רק חייב מי שהוא חי, ואולי הוא פטור כיון שכל עדות שעליו הוא עדות שאי אפשר להזים.
** איתגורי -
אם כן, יש חידוש רק אם עשה את הקל תחילה. אם כן, אינו צריך לעיל בלז:.
* פא:
** מלקות -
לולי רש"י, היה נראה לומר שדן אם צריך שרואים שאחר מלקות עובר, או רק שעובר. רש"י לא כתב כן, וצריך ביאור לרש"י למה צריכים מלקות. ותחשב על כל זה.
** צריך ביאור
ל"ל מביא גמרא מימרת רב הונא על חטא ושנה.
* פב.
** הבא לימלך -
יש לדון בביאור זה:
1. אין אנו יכולים להניח שהוא קנאי כראוי, אבל אם הוא יודע שהוא קנאי כראוי, ילך.
2. אם בא לב"ד לשאול דין על זה, בוודאי אינו קנאי כראוי.
** אין חכמה -
לא הכיר באותו קרא דווקא (אף שלשון רש"י משמע כן), שלא היה נכתב עד ימי שלמה שכתב משלי. ותחשב.
* פב:
** שלומיאל בן צורשידי שמו -
ולכן רק מונה אותו בשם אחד (ולא חולק אותו לשמו ושם של בן אביו, כמו בשאר השמות), שרק אומרים שמו, ואינם חלוקים. ותחשב.
** לישבקיה -
היה אפשר להקשות על זה משאר ציורים של משנתינו, שבו חייב מיתה.
* פד.
** בו ולא -
קשה איך ממעטים שני דברים- ולא פחות (לומר שהוא מיותר ורק יכולים למעט אחד), ולא יותר (לומר שמשמע שממעט את הכל) מזה.
* פד:
** דהא אי נמי -
קשה מהיכי תיתי דין זה, ולמה לא אומרים שהקרא אומר שאינו חייב.
* פה.
** ואחר -
קשה, שאם נדחה איסור קל, מי יאמר שנדחה איסור חמור.
* פה:
** לאחר מיתה -
קשה איך יודעים שדין זה נכון גבי הכאה, שאף שאין יודעים שאינו נכון, הרי כתיב "עמך,” ואין קרא להוציא מזה. ואולי ההיקש ילמד נגד זה. ויש לומר שסובר שאין היקש (ע"ש). אז, יש לומר שסובר שאין "עמך" בהכאה, ופשוט שהוא חייב.
** מכה -
לכאורה, לומד אפשר משאי אפשר.
* פו.
** אזהרה לגונב -
לכאורה, הם שני אזהרות חלוקים, ועל שניהם ביחד חייב מיתה. מעניין שיש עונש לצירוף של שני אזהרות. ותחשב.
ואפשר שהוא על אזהרה שניה, אלא שאזהרה שניה כבר מניח ראשון- רצה לומר, שהוא נאמר רק על מכירת נגנב. ותחשב.
** כר"כ -
קשה, אז, למה לא חולקים אם נהרג מי שהעידו עליו, ולמה דן בציור שהוזמו. ואולי יש חידוש בהזמתם שמוסיף.
** להלקותו -
זה רק אומר שהראשונים אומרים עדות בפני עצמם, אבל עדיין אין לומר כן על האחרונים. ותחשב. ואולי הענין הוא שיש שני ספטי"ם בעדותם, אבל כיון ששניהם גורמים ביחד נפק"מ אחד, קורא אותו סט"ף אחד. כיון שיש דבר שקורה ביניהם- יש חלות עדות- לא מונה אותם לאחד עוד. ותחשב.
* פז.
** רבי מאיר -
ממה שלא רוצה לומר שהכל תלוי באם הקדיש ממון על תנאי שהדין כ…, רואים שאינו כל כך טוב לומר נפק"מ הידוע של רב ברוך בער.
* פז:
** אבודימי -
לפעמים, נקרא רי"ב אבדימי, ולפעמים נקרא רי"ב אבודימי. יש לדון אם הוא אותו איש.
** ולוי -
אגב, יש להעיר שחידוש הוא שם שאם היא שופעת לא יכולים להניח ששינה מעיינות, שהיה אפשר לומר שמעיין אחד היה שופך, ושוב התחיל מעיין אחר, והיו ממש זה אחר זה, ואי אפשר להכיר בחילוק.
גם יש להעיר שמניחים שהוא המעיין של קודם, אף שכמו שיש קרק’ של אותו מעיין (התחיל קודם), יש גם כן של מעיין אחר (קרה גם כן אחר הזמן). וצריך לומר שיותר מובן שדבר ימשיך עד חוץ לזמנו משיתחיל קודם זמנו. גם יש לומר שהולכת לחזקתו, שכשהתחיל המעיין מניחים שהוא של אותו זמן, ולא משנים אותו מחזקתו. ותחשב.
* צח:
** לרבה -
יש לציין לגמרא ראש השנה (יח?) שאומר שרבה לא חי כל כך ארוך כמו אביי, שלא עסק בתורה וגמילת חסדים. אולי עסק אבל לא כל כך. גם יש להעיר שיש דיון מה גורסים כאן, ומה גורסים שם. אולי מוכרח לגרוס ההיפך. ותו"ת.
** שמא יעכב -
ואם תאמר אם כן אינם ראויים. ויש לומר שר"ל שיש סיבה, אבל יש מניעה.
** ינאי -
ממה שכולם אומרים שמותם, וזה אומר ”ינון,“ נראה ש“ינאי“ הוא כינוי לשם ”ינון.“ עיין ברש"י.
** ואין לך כל דקל -
יש לדון, אז, איך מותר לקבור אדם בא"י. אולי מותר הוא כיון שהוא רק גרמא. ותחשב.
* צט.
** אלא למשיא -
לכאורה, לא מחדש דין של ת"ח, שזה כבר אמר במימרה של בעלי תשובה. אלא נראה שמחדש דין של עושה פרקמטיא ומשיא בתו. ותו"ת.
** חוץ מקל וחומר -
יש להעיר שמזה משמע שאין קו"ח רק מסברה, אלא ניתנו בהלכה למשה מסיני. יש רש"י שכ‛ כן, אבל יש רש"י שמשמע דלא כזה.
ויש לדון, שאולי דנים במי שסובר שכל קל וחומר שהוא נכון בא מסיני, אבל זה לא בא. ויש לדון.
** קל וחומר -
קשה ל"ל אומרים שכל מי שחולק לשם שמים ולא קיבל קל וחומר או גזירה שווה אחד נכלל בזה. ותחשב על זה. אולי זה באדם שחושב שיש צורך לשמוע לו אבל לא בא מסיני. הרע הוא במה שחושב שיש דבר אחר שעושה דיני תורה חוץ ממה שכתוב וממה שנמסר. ותחשב.
** ר‛ נהוראי -
יש להעיר שהוא האומר, ”אינו מלמד בני אלא תורה,“ וגם הוא היה ראב"ע, ששכח תלמודו….
* צט:
** עמל פה -
מה שתורה נקרא עמל פה משמע שמצוות לימוד תורה הוא מצווה בפה, שצריך לומר דברי תורה, ולא רק לחשוב אותם. יש לדון, שאולי הוא רק עמל פה, והוא שמסתמא יעמול בפה שלו, כיון ש דרך בני אדם ללמוד כך, ואף שאין הכרח. ותחשב.
** מכאן לצדיקים -
לכאורה, זה פשוט, שהם צדיקים. אולי ר"ל מכאן לאלו- וקורא אותם צדיקים כיון שאנו יודעים שהיו צדיקים, אבל לא היה כל כך פשוט בלי קרא זה עד שנאמר שלא גזלו- שלא גזלים. ודחוק.
** כאילו עשה לעצמו -
נראה שהענין בכמה מאלו הוא שאדם נברא כדי ללמוד תורה ולקיים מה שכתוב בו. אם לומד, אז, הוא הסיבה לברייתו. ותו"ת.
* קא.
** שבתות וימים טובים -
ואם תאמר אולי ס"ל כר"ע שאומר, ”עשה שבתך חול….“ יש לומר שמקשה איך החולקים יבארו את זה. גם יש לומר שאומר גמרא שאף לרבי עקיבא צריך להוסיף. ותחשב.
** רבי יהושע בן לוי -
עיין במה שכתבנו בב"ב בזה. ויש להעיר שריב"ל כבר אמר פשט בקרא, ואז אי אפשר שמפרש אותו כפשטותו בזה. אז, צ"ל שמקשה על המשל.
* קא:
** מריבה -
מעניין, שגם החטיא אותם, וזה, לכאורה, יותר גדול ורע מעשיית מריבה.
* קב:
** מחצה -
לכאורה, ר"ל שכפר עד שהיה מחצה על מחצה, ולא, בהכרח, מחצה. ותחשב.
** ושניהם מקרא אחד -
מעניין שאומר כן, שכבר אמר לעיל מקרא אחר שדורשים למקור. ותחשב.
* קג.
** כל האומר -
לכאורה, לא מלחיש ידיהם, אלא לא מחזיק אותם, שרק לא שב, ולא ששב ולא נענה. ותחשב. ואולי מניחים ששב ונענה. צריך ביאור למה יחשבו כן.
** תלתין -
מניח שחזר, ולא שסרח. ותחשב.
** אשתך ספק -
יש להעיר שכיון שכבר לא ישלוט בו יצר הרע, אין בזה בעיה של שמא יתיר אותו לעצמו. ועיין במה שמפרש רש"י בבעיה זה; לפי זה, אין קושיה, ואולי לכן מפרש רש"י כן. ותחשב.
גם יש לדחות באופן יותר פשוט, לומר שאולי לא יהיה נענה תפלה ראשונה שלא ישלוט בו יצר הרע (ולמעשה, שלט בו קצת, שהרי עבר עבירות), ועוד שאולי תפלה ראשונה לא היה שלא ישלוט כלל, אלא שלא ישלוט כל כך. ותחשב.
* קג:
** שקולה נשמה -
יש להעיר שגמרא לעיל אומר כן על כל אדם.
** בהדיוט -
יש לדון למה מזכיר זה, שלכאורה, לא כל כך שייך. ותחשב. ואולי זה שייך לצדדים למה לכתוב או שלא לכתוב. ותחשב.
* קד.
** אין אברהם מציל -
יש לדון ל"ל אומר שא"א מפני שלא נקרא זרע של אברהם. ותו"ת.
** מזכי -
יש לדון אם עושה שיש לו חלק, או שלא נמנה. עיין ברש"י בזה.
** שלשים ושש -
יש לציין לגמרא שם, שלא כל כך פשוט שממש יש שלשים ושש כריתות. ותחשב.
* קד:
** עם קשה עורף -
יש לדון למה זה שייך (למה הזכיר את זה).
** שני -
לכאורה, רק אחד אמר כן; יש לדון למה היה נתפלא על שניהם. לכאורה, היה נתפלא על העם (יש לדון למה למד מאחד), וכיון ששניהם היו יהודים, עשו שניהם בני חורין.
** מה שלא ראו -
לכאורה, אז, היה לו להיות שלא יהיה ”ע“ כלל. נראה שיש ”ע“ כמו שיש כל אות אחר, אלא עושה שיש זמן שיש ”פ“ ולא "ע“ כדי להודיע מה שאומר גמרא כאן. ותחשב.
* קה:
** יעסוק -
יש להעיר שלכאורה, לא כוון לשם שמים (ויש אומרים שצריך כוונה לש"ש). ויש לומר שכיון שכיוון כדי שיהיה נחת רוח לה‛ (אף שרצה זה כדי שיהרג ה‛ את בנ"י) די. ותחשב.
** מעין -
לשון ”גדול“ לא משמע כן. אולי ר"ל שהוא גדול עד שהוא מעין. גם יש לומר שאומר שהוא גדול מרק להיות מעין שלו. ותחשב.
** מנשים -
יש לציין לגמרא הוריות שדורש שהיתה גדולה מקרא זה. וע"ש. אולי זה רק בהוה אמינא שם.
** ויהפוך -
זה לא מראה איזה קללה היה. ותחשב.
* קו.
** עד שתכפור -
נראה שאפשר שאמרה כן, והוא מפני שכיון ששמעו זה, חשבו שבוודאי זה לא יקרה, ואז לא חשו להן. ותחשב.
* קו:
** תלתין ותלת -
מעניין שנקט שני מנינים אלו, שיכול להיות כל דבר פחות מחצי ימיו.
** פנקסיה -
לכאורה, לא היה יכול לכתוב זה על פנקסו, שכבר היה מת.
** מוחלט -
לכאורה, יכול לדרוש כן כיון שענין גזרה שוות הוא הענין, ולא המילה, כמו ”ושב ובא.“ ותחשב.[fn:9]
* קז.
** דלא לימרו -
ק"ק איך ידעו שהיה ה‛ חולק עם דווד בזה. אם הוא רק מה שה‛ ניסה אותו, אז זה יתקיים בכל דבר. ותחשב.
* קז:
** שבע שנים -
העיר לי א.מ.ו. שלא היו ימי צרעת בכלל אותם שנים. וצריך ביאור.
** מכלל -
לא הבנתי מהיכי תיתי שאין חדש בא, ואז הוא צר.
* קח.
** וריש לקיש -
יש לדון אם דנים אם היה נחשב צדיק או אם היה צדיק. ותו"ת. ויש לדון על פי מה שאומר רש"י ועל פי המשל שאומר. ותחשב.
* קח:
** מאותם -
משמע שלא היו כבר פשוט כך מן ”הטהורים.“ זה משמע נגד גמרא בזבחים שאומר ש"טהורים“ משמע מי שלא נעשו עבירה. ותחשב.
** מן הטמאים -
מעניין שמניחים שהיה מן הטמאים, שאם טמא ר"ל שלא היה במינו שלא עשה עברה, קשה איך נדע. אולי היה גמרא. גם יש לומר שכיון שחטא בתיבה, מסתמא כבר חטא קודם לכן. ויש לדון. ואולי צריך לומר שחולק על אותו גמרא בזבחים שאומר כן בפירוש ”טמאים“ ו“טהורים.“
** בנאסר לי -
לא צריך קו"ח זה, שאם נאסר, אין צריך עוד הוספה זה, ואם לא מניח שאותו איסור קיים, אין קו"ח קיים. ואולי ר"ל מה למי שהיה מותר קודם לכן…, מי שהיה אסור קודם לכן[fn:10]. ותחשב.
* קט.
** נעלה -
יש לדון איך זה תירץ לקושיה.
** וחטאתי לאלהים -
יש לדון ל"ל ידרוש מחלק זה. ויש לומר שדורש ש“חטאת“ יכול לומר שניהם, וכיון ש“רע“ כבר אמר גופם, צריך לומר שזה אומר ממונם.
* קט:
** בקש רחמים -
יש לדון אם לא רצה להיות נזכר או לא רצה להיות שמו נדרש לרע. ותו"ת.
* קי.
** מלכות בית דווד -
יש לדון למה מימרא זה שייך למש"נ לעיל. ויל"ד. ונראה שאולי הוא מפני ששניהם הם בתוך עצת אחיתופל בב"ב. וע"ש.
* קיא:
** עטרה -
נראה שעל פי זה יכולים לבאר כל המימרות שאומר גמרא על צדיקים לעתיד לבוא, כמו שיאמרו לפניהם שירה, ושיקראו בשם ה‛. ותחשב.
** ייפדו -
יש לדון אם צריך להיות נאבדים אחר שנפדים, שאולי נשנו די. ותחשב.
* קיב:
** אישתני -
משמע שהבעיה הוא שמה שבא ממנו יש עליו ”זבח…,“ ולא שבא מקדושה דחוייה מחמת זה. ותחשב על זה.
* קיב.
** מזוזה -
לכאורה, היה אפשר לדייק כן אף מדין קדשים, אלא שלא אמר כן על אותו דין עצמו. ויש לדון ל"ל. אולי אינו כל כך מצוי (שהרי כל אדם מצווה במזוזה).[fn:11]
* Footnotes
[fn:1] כמובן, קל לת’ שלא רצה ליטול רשות, שהיה טירחא, וחשב של אהיה כל כך צורך.
[fn:2] לכאורה, הוא אותו ר"נ, שהוא סתם. זה מניח שיש רק אחד סתם (עיין בחבורה שכתבתי). גם זה מניח שסתם שאומר גמרא הוא סתם שאומר לשם אב. ותחשב.
[fn:3] זה נשמע כThe Hungry Caterpillar.
[fn:4] יש לדון, שכן אומר גמרא לומר שיכול להיות שכולם סוברים כדברי רב יהודה ש"אין עד חותם אלא אם כן ידוע מי הוא העד האחר,” אבל אין הכרח אחר שר"מ מניח לדיינים לבחור. ותו"ת.
[fn:5] כל זה אומר גמרא בהוה אמינא של ביאור המשנה, שסובר שאומר שמנשה שיכול כל אחד לפסול בית דין שבחר חברו. כיון שחזר מזה, עדיין רואים שיכול אדם לפסול דיינו של חברו לרבי מאיר. גמרא מוקים את זה בערכאות שבסורא; יש לדון אם היה יכול להוקים את זה בשהיה דיין שרוצה לווה באותו עיר. יש להעיר שלכאורה ממה שבוחרים ביחד, ואין מלווה כופה ללווה, צריך לומר שדיינים שבוחרים הם כולם באותו עיר. אז, ממה שהיה צריך לומר שהם בערכאות שבסורא, צריך לומר שלא די. ותחשב (שאולי צד זה שבגמרא חולק על אותו אמורא, וסובר כצד בראשון, ואולי אותו אמרוא שאמר כן היה אומר כן אף כאן. ותחשב.)
[fn:6] וצריך לומר שעדיין יש דבר רע אם אחר יהרג אותו. ותחשב.
[fn:7] ואין זה מוכרח, שהיה אפשר לומר שרבנן רק אומרים שאף לולי זה צריך התראה, שיש סיבה אחרת בהתראה. ותו"ת.
[fn:8] עדיין צריך אומדנא ראשונה כיון שבלי זה, לא נדע שזה נקרא שהקל, שאולי כך היה עומד מתחילתו, ואין שינוי מן הדרך שהיה עומד למות, ואז אין סיבה לחשוב שיחיה. ותחשב.
[fn:9] גם אולי כיון שתרגום נלמד מסיני יכולים לעשות ג"ש ממנו. ותחשב.
[fn:10] ולא מי שמותר מחמת איסור אשת איש…
[fn:11] ויש להעיר שאלו הם רשעים, עובדי ע"ז. ויל"ד, שלא צריך לומר רשע לעבוד ע"ז, כמו שאמר גמ‛ לעיל.
