* ב.
** גזילות -
צריך ביאור למה זה כן, שהרי שכר שכיר אינו שלו יותר מהלוואתו שללו. ותחשב.
** ואדם -
לכאורה, אינו צריך להיות שפודה את עצמו, שיכול להיות כן בכל זמן שאדם מקדיש דמי חברו. ותחשב.
* ג.
** אי הכי -
היה אפשר לומר שמקשה למה לא יאמר משנה שני דינים (ששניהם בשלשה).
** מדאורייתא -
משמע שחלקם כיון שזה מדאורייתא וזה מדרבנן (ובאמת, גמרא משמע כן). היה אפשר לומר שחילק אותם כיון שדינם במומחים חלוק.
* ד:
** ואל יוכיח -
יש להעיר שללשון שהוא חטאת העוף יש טובה במה שאז אומר רק דמיון אחד, ולא שנים (שלכאורה, אי היה שנים, היה לו ללמוד ממנו, ולא להיות מסופק). כל זה מניח שכשאומר גמרא לשון כזה, ממש מסופק הוא. היה אפשר לומר שרק אומר תחילת דיון (ואם היינו ממשיכים כן, היינו לומדים הפך מן הדין).
* ה:
** רבי חייא -
עיין במה שאומר. יש לציין לגמרא הוריות (יא:) שבו שואל לו רבי (ומזה דנים אם היה ממש תלמידו או לא).
* ו:
** אבל -
נראה שכוונת רש"י לומר שמה שנקרא רודף הוא שהיה צריך לרדוף כדי שישיגם קודם הדין, שרק אז יכול לפשר. יש להעיר שזה מוכיח שאיסור זה רק בדיינים, כמו שאומר רש"י (וע’ בשיח שי על גמרא).
* ז:
** אם ברור -
מאיר- יש לדון מה אומר:
1. אולי אומר שצריך להיות פשוט לך כמו שפשוט לך שבקר מאיר.
2. אולי אומר שצריך להיות כל כך בהיר כמו שבקר בהיר, והארת בקר הוא סימן לבהירות. כן רגילים בני אדם לומר, והוא, לכאורה, מפני שיכולים לראות רק כשיש דבר המאיר, וכמו שזה מגלה אז מה שלא נראה, בהירות מגלה מה לא נראה מפני שבלבול. ותחשב.
אולי לשון גמרא משמע כצד שני ממה שלא פירש כל כך כמו שפירש באחות (“כאחותך שהיא אסורה").
** ששים -
אומר שהוא לאו דווקא כיון שגמרא אומר שהוא לענין דין, ואין ששים דנים. ותו"ת.
** ולואי -
עיין במש"פ. היה אפשר לפרשו על פי מש"א גמרא ב"מ שיהיה יציאה מעולם כמו ביאה לעולם.
* יא.
** מזומנים -
לכאורה, אין הוכחה שזה צריך להיות בערב. גמרא אומר שכן עשה ר"ג, אבל אולי כן עשה, אבל לא היה צריך לעשותו. אם לא נאמר כרש"י, יהיה מובן למה לא חשש שמואל שיהיו רק ששה, שהרי נמצא שהזמין אותו, ויכולים לסמוך עליו (והיה ר"ג מתיר אותו להשתמש כדיין, ולא רק כתלמיד עכשיו). ותו"ת.
** חס ושלום -
ויצאו כולם- יש לצרף זה למש"כ שיח שי על גמרא.
* יא:
** דילמא -
נעשה ענו- לולי רש"י, הוה אמינא שאומר שלכן אמר שהוא אף מחבריו, שלא היה באותו שעה נשיא.
** אין מעברים -
מרש"י משמע שהבעיה הוא אף על עיונה, ולא רק על הפסק. אם הסיבה לדין זה הוא שישכחו בני אדם שנתעבר, קשה למה צריך להיות כולו אחר ראש השנה.
ויש להעיר שלולי רש"י, היה אפשר לומר שהסיבה אינו השכחה, אלא שמשנה אותו שנה, וכדי לעשות כן, צריך להיות שכבר בא לעולם (כמו שאין קניין על מה שלא בא לעולם). ומסקנת גמרא (גלויי) מוכרח, לכאורה,  כמה שאומר רש"י.
* יב:
** ביום -
אם לא ישבו- לשון רש"י משמע שאם כבר התחילו, אינו בעיה להעבירו אז. ותחשב. וקצת צריך ביאור למה, שהרי חלות נעשה באותו זמן. יש לומר שכל החלות נגרר בתר זמן תחילת דין. גם יש לומר שכיון שהיו כבר דנים בו, לא אומרים שניסן עומד לבוא (וזה תלוי במש"כ בשיח שי על גמרא בד"ה ראוי לקבעו).
** אין מקדשין -
זה ניסן- אם הדרשה הוא שזה, ולא אחר, ניסן, צריך ביאור למה לא לקדשו, שאין הבעיה שדבר אחר הוא ימים שהיו להיות ניסן, אלא שימים אחרים ניסן. (ואולי זה נשאר קצת ניסן אם לא מקדש. אז, כשאחר ניסן, אינו כל כך ניסן. ויש לדון מה זה אומר.) אם כן, צריך לומר שניסן בא לאותו חודש בפני עצמו, אף שאין קידוש החודש מפי בית דין. אף על פי כן, אם מקדשים אותו לחודש אחר, לא בא ניסן של אותו חודש. ותחשב.
אגב, מעניין שכשלא מקדשו, לא נעשה חדש אחר (כן משמע מגמרא זה, לכאורה). ויש להעיר שאפשר לומר שזה רק בחדש של עיבור, שאין חדש שעומד לבוא אז. ותחשב.
גם אפשר, ודחוק, שרש"י הזכיר הדרשה אגב, והענין כאן הוא לדחותו שלא בידיים (שמשהה לומר שהוא ניסם, ונמצא שנדחה, ולא נעשה ניסן.
* טו.
** לעצמו -
שמא לדבר אחר- ק"ק למה נאמר כן בג"ש יותר מבשאר דרשה. לולי רש"י, היה לנו לומר שגילה ה’ בהר סיני שאין ג"ש אשר לא נתן לו קבלה. ואולי רק רצה לומר שחוששים שמא לא נתן ה’ לו מסורה. ויש לדון, שמחודש שיש אף חשש שנתן ה’, כיון שלא ידוע אותו מסורה. ותחשב.
* טז:
** מצוה בשבט -
עיין לשון רש"י שמשמע שהוא מצוה על בני שבט ללכת לשבטיהם. לשון גמרא לא משמע כן כל כך, אלא שצריך ביאור קצת איך יהיה בית דין מצווים על זה. ואולי צריכים שלא להיות טורח לבני אדם לבוא להם או כדומה.
* יז.
** בעלי קומה -
משמע שבעלי קומה רצה לומר שהם נראהם מפחידים, ולא שהם נאים. ויש לדון, שאולי בני אדם יראים מבני אדם שנראים יפה.
* כ.
** תוקפו -
ועוד, שהיה יכול להורות היתר לעצמו, שכבר התירו המלך.
** ששהא -
נמצא שסובר שהתחיל מלכות דווד ממיתת שאול, ולא ממשיחותו. (דנים ראשונים בזה).
* כג.
** יצא הדין -
עיין במה שאומר, שמשמע שסובר שהענין הוא ששניהם יקבלו הדין יותר. אולי כן מפרש לשון יציאה שנאמר כאן. לולי רש"י, היה אפשר לומר שזה עושה שיותר מצוי שיצא הדין כראוי, והוא שיימצא שמה שאומרים הוא אמת, והוא שכל נטיעה וטנגיעות של עד יהיה בטל משל חברו. ותחשב.
** נידון -
עיין במה שפירש. זה משמע כצד שתקנה הוא רק תקנה כיון שאינו, בדרך כלל, מקיים את שטרו. ותחשב.
* כו:
** עיין במה
שאומר גבי בן בעל אחותו (שהוא בן אחותו). יש לדון אם רק מייר כשהוא בנו מאחותו אם אף בלי זה, ואומר שהוא בן אשתו כיון שאשתו של אדם כגופו, כמו שאמר לעיל בביאור פסול בעל אחותו. לשונו משמע כראשון, אבל עדיין יש לדון.
** בק’ רש"י,
יש לדון, שמהיכי תיתי להחליף את הכל (שקרא רק אומר בעל אמו, ולא להיפך). גם יש להעיר שגמרא צריך עוד קרא לזה. ואולי רש"י גרס במשנה "הוא לי ואני לו" או כדומה. ותחשב.
** בראיית
רש"י, ביב אפשר לומר שנצרך כדי לרבות בנים וכדומה של המנויים. ותחשב. ואולי רש"י גרס שאותם ציורים נזכרים בפירוש במשנה.
* כז.
** במה שמונה חמותו לאחד
(כן אומר רש"י), נראה אולי שהוא מפני שיש, אולי רק חידוש אחד בכלם, והוא שאשתו כמותו. ויש לדון. יש להעיר שאז לא היה לו למנות כל הח’. ותחשב.
** אגב
, יש לדון אם דיבור האב בבן סורר ומורה הוא מדין עדות או לא. ותו"ת.
** רש"י אומר
֝כן מצאני בנוטס שליׁ לשון דמי גבי קרובים[fn:1]. זה מעניין֚ שלכאורה הפסול הוא הקורבה. ותחשב.[fn:2]
* כט׃
** ושלחו-
יש להעיר שרש"י כאן אומר שצריך שלש כדי שיהיה מפורסם ויהיה דומה למלווה שבשטר. לעיל לא אמר רש"י כן, שאמר שצריך שלש כדי שהיהו כבית דין, ויפקירו כל זמן שרוצים. נראה שאולי במה עושה בית דין גופא חולקים צדדים אלו, ואז בכל אחד רש"י מפרש כשיטתו. ותו"ת.
* לב.
** ולטעמיך -
אלימי…- לכאורה, אומר כאן שני דברים:
1. אלים, שמוכרח שהוא נכון, ואינו אפשר לומר שאין המשנה מתורצת.
2. כולי עלמא ידעו ליה. אז:
  1. היה לו להיות בא על דעתו ראשון.
  2. היה לו לשאול ממנו כיון שכבר היה ידוע , ולא היה צריך להיות מבאר אותו.
* לד.
** ורבנן -
עיין במה שמפרש מחודש שלא שומעים למי שהוא נוגע, אף שאומר טענה טובה. גם מחודש שמניחים ששינו דעתם (שהרי, העידו). ונראה שהוא רק נראה כנוגע, והוא שאולי כיון שעד נוגע פסול, וזה עד, והוא נוגע במה שאמר, דומה לנגיעת עדות.
** אין מונים -
לכאורה, מזה רואים שאין אומרים "אלו ואלו דברי אלקים חיים" על כעין זה, או שאף ש"אלו ואלו…" אין יכולים לפסוק מפני אותו שיטה. ותחשב.
* לד:
** לאתויי יום מעונן -
ע’ במש"פ. גם היה אפשר לומר שסובר שר"מ חולק על הבריי’, ובא לרבותו לנגעים.
* לו.
** מעניין
שרש"י אומר שתמיד הוא עיקר קרבן. ואולי רצה לומר ראשון (כמו "מעיקרא"), שרק בתמיד יכול להיות שיש רק קרבן אחד.
* לז.
** המזג -
עיין מש"פ. ק"ק, שבדר"כ, מוזגים בפחות מזה. ויש יין השירוני שהוא, אולי, כזה. ותחשב.
* מ:
** המית בתוך -
שכבר שכח- זה מעניין. זה מוכיח שצריך ידיעת התראה, ואף שלכאורה, אינו רק לר"י שאומר שהוא כדי להבחין בין שוגג למזיד.
** אלא רואה -
קמי שמיא- זה מעניין, שלרבנן אין התראה להבחין. אולי סובר שרבנן מודים לר"י בטעם התראה, ורק חולקים אם יכולים להניח שאדם מזיד (או אם אומרים שצריך התראה מטעם לא פלוג). גם אולי לא רוצים שמה שידע תורה יעשה שנהרג בלי התראה, שהוא הפוך של חוטא נשכר. ותחשב.
רש"י גם מניח כמו זה בד"ה כי יזיד. ותחשב.
* מא.
** לא שמיה -
ק"ק, שלכאורה, בכל זמן שלא חוקר או דורש כטוב לא מקיים אותו חיוב; אז, צריך לומר שאין זה מעכב בפני עצמו, וצריך מה שאי אפשר לקיים דיני הזמה. ותחשב. ואולי רש"י מזכיר שניהם כיון שצריך שניהם. (זה מניח שיש מקור שצריך לחקור. ואיני יודע אם זה אמת. צריך ביאוטר איך יודעים אותו. ותחשב.)
** תאנים -
לכאורה, אפשר שנתן בו סם המוות, והאכילו אותו בעל כרחו. לכאורה, חייב מיתה על זה (כן נראה מגמרא לקמן).
* מב:
** כי היכי -
נקראית- לולי רש"י, הייתי אומר שאותו גמרא אומר שהוא קטלנית. אם כן, לכאורה, לא שייך לכאן. ויש לדון, שאולי אם כן, לא היה לו לומר "נקראת.”
* מג:
** שחדיה -
משמע שאף שגמרא משמע ששיקר לו, לא היה עושה כן. ותחשב.
* מה.
** הרהורא -
ניעבד לה אנן- קשה, אז, למה צריכים קרא. ותו"ת.
* מח:
** לעלות במרכבה-
אסמכתא לג"ש- לשון זה מעניין, ויש לדון מה מכוון לומר.
* מט.
** עיין בביאור רש"י
בדרשת "ואחרי אבשלום….” גם יש לומר (ולא משמע כל כך מלשון גמרא) שדורש מילת "ואחרי אבשלום" לשני צדדדים- עם לא נטה ועם אחרי אדניה, שמצינו גמרות שעושים כן.
* נא.
** הא לזנות -
נראה שרש"י מפרש שמקשה מן המשמעות ולא משיטת רבנן (נגד ר"א) כיון שאילו ידע שיטת רבנן, מסתמא אף היה יודע שיש שיטה שחולק עליו. אז, צריך לומר שלא מקשה מדין שידע אלא ממשמעות פשוטה. כן נראה מלשון גמרא, שמקשה מן הלשון, ולא מזכיר דברי חכמים.
** אתיא -
יתירה- מרש"י משמע שרק אומרים שגזירה שווה הוא כאילו מפורש בקרא כשהוא מופנה. זה מעניין.[fn:3]
* נא:
** הרי קאמינא -
נשאל את ר"א- משמע שהוא לשון של ר"א, ולא של תנא האומר דבריו. ויש לדון, שאולי אם נדע מה פסק רבי אליעזר, נבין מה אומר הלשון.
** הוציא הכתוב -
סתם מן המפורש- עיין לעיל (ע"א) שקרא רש"י את זה בנין אב.
** בבנותיהם -
בנות בעלי מומים- לולי רש"י היה אפשר לפרש בנות בעלות מום (אבל רש"י אומר לשון זכר (כן אני חושב), ואז נמצא שקאי על האב). לכאורה, זה תלוי במה שיש לחקור אם יש קדושה לבת כהן מעצמה (או מעצמה או מיחס לאהרן הכהן) או רק מיחס לאביה.
ונראה שאולי בי"כ ובי"כ יש לומר כרש"י, והוא מפני שכאן סיבת האיסור אינו קדושה שלה, אלא קדושה שלו, שזנותה מחלל קדושה שלו (כמו שמשמע הקרא). ותחשב. לשון גמרא (“אינהו, אבל בנותיהם לא") לא משמע כן, אלא משמע שדנים אם יש להן קדושה.
* נב.
** היו משקעים -
עיין בביאור. ק"ק למה לא רק קושרים אותו. ואולי זה יותר קל לעשות או יותר נוח לו.[fn:4]
** לא היה -
צדוקי- מרש"י משמע שעשו כן בשיטה (שהיו צדוקים), אבל מלשון משנה משמע שטעו (שלא היו בקיים). ותחשב אם יכולים לומר על מי שבשיטה לא לומד מדבר שאינו בקי, שלמעשה, לא יודע הדינים.
שו"ר שבאמת גמרא אומר כן.
** על עסקי -
שנכנס לנפשותם- צריך ביאור מהו דרשה זה. ותחשב.
* נב:
** להקל -
עיין במה שבאר. לעיל, לכאורה, למד גמרא זה מ"ואהבת לרעך כמוך.” יש לדון למה אין שני הדרשות אומרים דין שווה. ותחשב.
גם יש לדון בסברה זה, שכמו שיש איסור להרבות על המיתה, כך יש איסור למעט, שחייב בית דין לדון ליתן סקילה, למשל, לכל החייב סקילה. ותחשב. ואולי אינו מדין חשש לספק, אלא מדין תפסת מועט. ותחשב.
* נג.
** מקלל -
מעניין ששני רעות מצטרפות לחייב מיתה יותר חמורה.
** נותן מזרעו -
לכאורה, צריך ביאור חילוק בין עבודת כוכבים לחוק של עכו"ם. לכאורה, לא עושים אותו כדי לעשות אליל שלהם רצוי, אלא מפני שחושבים שעושה שום טובה. יש לדון איך יבארו איך עושה אותו טובה; אינו פראקטיקאל, לכאורה, ואינו מפני שאליל ירצה בו. ואולי כוחות אחרים יעשו לו מה שרוצה אם יעביר בנו. ותחשב. גם יש לומר שאולי סברש עבודת כוכבים שלא לשמו (לשם ריצוי ע"כ לצורכו) אינו נקרא ע"כ. זה מעניין.
** איסור מצוה -
עיין במש"כ. יש להעיר (ושו"ר בגליון הש"ס שכ’ כן) שזה רק הוה אמינא של גמרא. ויש להעיר שרש"י ג"כ כותב מסקנה של גמרא. ואולי רש"י צריך זה למקור לומר שאחר שגוזרים עדיין עולה לחליצה. מחודש שצריך קרא לזה, שרק לא עולה מדרבנן.
ועיין בסוכה (כג.) שלכאורה, רבי יהודה סובר שמה שאינו ראוי מדרבנן נחשב שאינו ראוי. אז, זה לא עולה לייבום, ואז צריך קרא. עדיין קשה איך קרא ירבה אותו כיון שהוא רק לא ראוי מדרבנן (על מה היה קאי קרא קודם הגזירה). ותחשב.
ויש להעיר שלטעם שני שאומר גמרא, שיכול לחלוץ, אם היינו אומרים שצריך קרא לגלות שיחלוץ, היה, בלי זה, גלגל החוזר, שהרי אם לא היה חולץ, היה מייבים. ועיין שם.
* נה.
** קבסתן -
לא אפשר- קשה, שדילמא שאל במשמש מת.
* נו:
** כאשר -
יש להעיר שיש שכ’ שמשה אמר פעם שנית, ולכן יש שינויים קטנים בין מה שנאמר בפעם ראשונה ומה שנאמר בפעם שניה. רש"י מוכרח נגד זה.
** יהי מוראי -
רש"י מפרש שאלהים אומר שררה, ושררה הוא דבר שראוי לירא מפניו. היה אפשר לומר ששם אלהים נאמר על מה שראוי לירא ממנו, ולא אומר שררות, אלא דבר שראוי לירא מפניו.
* נז.
** צערא -
בישראל בישראל- לכאורה, רצה לומר שיש איסור של מצער חברו, אבל אינו איסור גזל.
* נט.
** ששבת -
יום ולילה- לכאורה, משמעות הקרא הוא שלילה הוא אחר היום. ותו"ת.
אם כן, מתורץ מה שדנו אם אברהם שבת אם היה גוי. נראה שעשה מלאכה במוצאי שבת.
* סב.
** אחת שהיא הנה -
שם- יש לדון מה לנו שהוא שם בפני עצמו:
1. צריך להיות שמה שנכתב הוא שם חשוב.
2. צריך שמה שנכתב דומה למה שכיוון לכתוב במה ששניהם שמות חשובים.
** תיפוק ליה -
קשה מהיכי תיתי שקאי על שניהם, שרק אומר שלפעמים חייב שנים, ולפעמים אחד. ואולי רצה לומר שאין סיבה לדרוש על שבת יותר מעל ע"ז. ויש לדון, שגבי ע"ז יש קרא שמשמע שרק חייב אחד.
** שבר -
לולי רש"י, היה נראה לומר שהוא כעין תולדות של שבת (שיש מקור שווה), ואז יש דין שווה לאב, והוא שחייב אף אם אין עבודתו בזה. אם עבודתו בזה, ק"ק למה צריך קרא לרבות תולדות. וצריך לומר שמיקל ואומר שהוא רק איסור אחד.
ונראה שיש עוד דרך, והוא שחייב אף אם אין עבודתו בכך, ובלבד שיהיה עבודתו במקל. קשה למה צריך להיות כן.
* סג.
** אר"א -
לא הבנתי מה אומר בזה, שבודאי לא סובר שיצא לחלק, אבל עדיין קשה מהיכי תיתי שאינו בכלל כל העבודות. ואולי יש לומר שאז לא צריכים קרא לרבותו, ואז דורשים לחלק. ויש לדון, שאולי הוא בכלל העבודות רק כיון שיש כבר קרא. ותחשב.
* סג:
** סלמנדריא -
לא מצאנו לו בן- אם כן, יש עוד סיבה למה לא יחייב על מולך (עיין לקמן).
* סד.
** ואף על גב דמכוון -
קשה למה יחייב חטאת, שהרי אינו מקבל עליו באלוה (וגמרא אמר שאין זה כלום).
* סד:
** רבא אמר -
בימי הפורים- זה מעניין.
* סה.
** הואיל -
עיין בכריתות , ששם רש"י אומר שהם בשני כריתות. כן, באמת, נראה מגמרא שם. שו"ר ששם מיירי במיתות.
* סה:
** מה גבר -
עיין במה שפירוש למה הוא חשוב. קשה, שמה לקיסר מגוברין. אז, היה נראה לומר שאמר שאלהותו עשה אותו חשוב. ותו"ת.
* סח.
** ואם אין לאיש -
משמע שאין בני עשו יורשים שלנו. עיין בב"ב (ובשיח שי שם) שרשב"ם דן בעשו בכמה ציורי ירושה.
* עד.
** מרי -
ונכרי- לכאורה, רצה לומר שאז מניחים שממש יהרג אותו, אבל אילו היה ישראל, אף בלי כלל זה, לא היה הורג, שלא היה לו להניח שהישראל יהרוג אותו.
אם הייתי קצת יותר ישיביש, היה אומר שרש"י רק בא לתרץ קושיא גדולה- איך אפשר שיהודי יאמר כן ליהודי אחר, ויאמר שיהרוג אותו אם לא יהרג אדם. אז אומר שהיה גוי.
* עד:
** היכי -
משמע שהיו נוטלים נרות. עיין בע"ז, שרק כבו. ואולי כבו כדי ליקח. גם יש לומר ששני חגים חלוקים היו.
* עו:
** איזהו עני -
משמע שרק זה יעשה ישראל שהוא רשע. זה מעניין.
** המחזיר -
זה מעניין. נראה, אז, אולי פשט חדש בענין "מי שאינו מצווה… הדיוט,” ולא צריכים לומר שלא מקיים שום ס"ט. ותחשב.
* עח:
** נתכוון -
התראת ספק. זה מעניין. באמת, בכל מיתה יש חשש שמא לא ימות, ואז הוא כמעט התראת ספק, אלא שצריך לומר שלא מניחים כן. גם יש לומר ששם אומר שאם תעשה מה שאתה מכוון לעשות, תחייב, וזה בוודאי נכון, אלא דילמא לא יכול לעשות מה שמכוון לעשות, שלא ימות. כאן, אם עושה מה שמכוון לעושת, לא חייב. ויש לדון, שאז אינו התראת ספק, אלא אינו התראה, שבודאי אינו חייב על מה שמכוון לעשות.
ונראה שמסתבר שיש שני דרכים לכלול מעשיו- הריגת הבהמה, וזריקת חץ. בודאי אינו התראה על פי דרך ראשון, ואומר רש"י שאף לדרך שני (שהוא אף יכול ליהות על פיו התראה), אינו אלא התראת ספק. גבי מיתת אדם רגיל, כיון שעל פי דרך אחד הוא התראה גמורה, חייב. ותחשב.
ודע שלולי רש"י, היה אפשר לומר שלא חייב כיון שלא כיוון למעשה הריגה, והוא כמתעסק. ותחשב.
* עט.
** לא צריכא -
אם היה כרובא, יש לדון מה יהיה כרוב. ותחשב. ואולי הקל יהיה כרוב.
** הא נתכווין -
עיין במה שכתב. ק"ק אז ל"ל תירץ כן גמרא (שלכן לא אמר "פטור").
* פב.
** קדש -
זה מעניין. ואפשר לומר שהוא לשון סגי נהור, שחסר קדושה. מרש"י משמע נגד זה, אלא שנקרא כן על שם שמביר קדושה. אם כן, חלק עיקרי משמו חסר.
* פו:
** דאי ר"י -
קשה למה לא אמר כן על איסרו של העובר שמעידים עליו עצמו. ותחשב. גם יש לדון למה צריך איסור זה, שהרי לא מלקים אותם מחמת זה, אלא מחמת "כאשר זמם.” ואולי צריך אזהרה לזה בקרא.
ויש להעיר שאף אם מעידים על מי שחייב מלקות יהיה לא תענה ניתן לאזהרת מיתת בית דין, שהוא הלאו אף אם מעידים על מי שחייב מיתה. ויש לומר שבמעשה זה לא ניתן למיתה. ואם תאמר הוא כן בכל זמן שמתרה עדים למלקות, שאז לא נהרגים. ויש לומר שאין זה חלק מן המעשה. ותחשב.
* פז:
** ספק -
חייב כרת- לכאורה, יהיה רק ספק. אם נאמר נפק"מ לענין חיוב כרת, אין נפק"מ מדאו’. אם נאמר נפק"מ לעונש (כמו קרבן או אם מכניבים אותו לכיפה), רק ספק הוא. ואולי סוברים רבנן שהדין הוא שספק מטמא בוודאי. ודחוק. יותר נראה לומר שרק צריך להיות עבירה ומחלקת שמביא לידי כרת, ולא שחולקים אם חייב כרת או לא. ותחשב.
* פח.
** שלשה -
ק"ק ל"ל אומר שיש נפק"מ אם לוקחו עני, ולאה דן בבעל הבית שחוזר ולוקח אותו.
* ק:
** בשפל גגים -
עיין במה שמפרש. יש לדון אם מה מעורר אותו עני הוא מה שיש קול מן המטר או שנופל עליו. ויש להעיר שלולי רש"י, היה אפשר לומר שהבעיה אינו שמצער אותו עצמו, אלא שהוא מחריב את הגג, ואז אין לו גג. ותחשב.
* קא.
** דעתו -
עיין ברשב"ם בב"ב שלא מפרש כך.
* קד.
** קטן לגדול -
גם יש לומר על פי מש"א גמרא לעיל, שבכזה יותר רגילים לזנות. אולי על ידי זה, ירבו וולדים, ולא ידעו איזה ממזרים, וספק ממזר מותר לקהל. ותו"ת.
* קד:
** קולו נשמע -
יש להעיר שגמרא שם אומר שיש כמה דברים שהיו נשמעים בלי גלגל חמה (כן אני חושב). אם, באמת, אין גלגל חמה בלילה, צריך ביאור למה לא יישמעו אז. אולי קצת נשמע (שמגלגל, אבל הוא רחוק[fn:5]).
** לקובלנא -
עיין בקרא שמביא, שממה שמביא משמע כצד ראשון. ותו"ת.
* קו.
** ותקראנה -
לא הבנתי מה אומר מילה ראשונה שאומר רש"י, שלכאורה ביאור הדרשה הוא שאר מילים של רש"י. ותחשב.
* קי:
** כיום -
נראה שצד אחד אומר שכל בנ"י כיום, שיש ששבים, ויש שנאבדים, אבל צד שני אומר שעשרת שבטים כיום, שהיו אבל אבדו. ותחשב.
* קיא:
** עיין בדרשת
רש"י לבאר למה צריך להיות רוב. ק"ק ל"ל נאמר שהוא מפני שאומר שצ"ל יושבי, וזה אומר שצריך להיות כל יושבי עיר, ורובו ככולו.
* Footnotes
[fn:1] שוב ראיתי שהוא גמרא שאומר לשון זה֭
[fn:2] כתבתי על זה נוטס, והם cryptic. כתבתי:אשת חורגו בנים- רצה לומר ולא באים לחורגו, שפסול לו, אבל אם באים לבנים, היה בעיה. יש לדון בפסול זה, ואולי רצה לומר שבא למעיד על ידי בנים. כמשנה ראשונה. דחוק למה אמר בנים.- רש"י בעל כאשתו- בעל דמעיד. אשה כבעךה- אשת חורגו. עיין רש"י שמצרף שניהם, אבל רק אומר חמות.אחי אחיו- מה אם אין אח באמצע.נוגע לגריעותא- אין זה נגיעות אלא חשד כאן.אולי זה מסקנא. ותחשב.
[fn:3] אגב, אם אין ג"ש מופנה, קשה למה לא יכולים לעשות מה מצאנו (ולמה צריך גזרה שווה). ואולי צריך פירחא יותר חזק (כמו שמצאנו שלפעמים צריך יותר פירכא בחד מקום מבמקום אחר (עיין בחולין קיג)). ותחשב.
[fn:4] לא נראה שהוא יותר נוח לו, שהרי בזבל משוקע, והוא מאוס. ותחשב.
[fn:5] או שהוא רחוק, או שיש דבר ביניהם (הארץ) שמפסיק את הקול
