* ב.
** הנשחטים לשם פסח וחטאת -
יש לדון מה סובר בחטאת ופסח שנשחטים לשם אחרים (אם מוסיף על תנא קמא או חולק עליו).
** לשם קדשים קלים -
משמע שכל קדשי קדשים נחשבים דרגא אחד. (ויש לדון למה, שמצאנו חומרות למקצת מהם על אחרים.)
יש להעיר שמצאנו בכ"מ (עיין לקמן בפרק איזהו מקומן) שגמ' לומד שדבר הוא קדשי קדשים. לכאורה, זה נפקמ אחד של היותו קדשי קדשים. (ויש לדון אם יש נפקא מינא לחולקים, או אם צריך לומר שגמ' מזכיר נפקא מינא זה לשיטה זה.)
* ב:
** אשה בסתמא -
לכאורה, היה לו לומר שאין הגט עומד לאשה זה בסתמא, שכך הוא הדמיון הטוב. ר"ל, חושב הוא על קרבן, וחושב הוא על שם בגט. צריך שקרבן עומד לאותו דבר שבו חושב, ואז הדיון יהיה אם השם עומד לאותה אשה.
באמת, מחודש הוא שלא עומד אותה שם לאותה אשה (על כל פנים בציור שאין לו אשה אחרת עם אותו שם).
** גבי גט נמי -
יש לדון למה, למעשה, אומר לשון כזה שמשמע שסתמא מהני. אולי אמר כן כאן כיון שמהני, ואמר לשון גט אגב זה. יש לדון למה לא יאמר להיפך. גם יש להעיר שמחודש לומר שאמר לשון גבי גט אגב לשון כאן, אף שדינים שלהם חלוק- באותו ענין עצמו.
** יוכיח סופו -
רש"י כ' במק"א שכל מחשבה שבקדשים ר"ל דיבור. כן, לכאורה, רואים אף מכאן (ואפשר לדחוק ולדחות), שהרי אילו כוונה של כאן ר"ל כוונה, אז סתם ר"ל שלא היה לו כוונה. אז, קשה מה מוכיחים לומר- שהרי לא כיוון כן. ויש לדון, שאולי אף שלא כיוון כן בפירוש, הרי כן חשב שהוא (היה מחשבה בכוח, אבל לא בפועל).
כמו כן יש להוכיח מרבי יוסי, שלכאורה, קשה איך לא חושב כלום. ויש לדון, שואלי לא אומרים לכהן מה הוא אותו קרבן, ואז ממש לא חושב עליו.
** לשם שם -
לכאורה, זה אותו דבר של לשם ריח ניחוח. אז, צריך ביאור למה נמנו לשני דברים. נראה שאולי צריך לחשוב שהקרבה זה הוא לה' (יש לו שום יחס לה'), וצריך לחשוב שמהנה את ה'.[fn:1] מחשבה ראשונה (שהוא שייך לה') הוא מחשבה לשם שם, ומחשבה שניה (שמהנה לאחד) הוא מחשבה לריח ניחוח.
** לשם ריח -
לכאורה, אין זה מחשבה, אלא שכך צריך לעשות (שלא לעשות שאין לו ריח). ותחשב.
** מקרין
- לכאורה, גמרא לא ידע עדיין שהוא מקריא לתלמידים ואין גט זה נכתב לשום גירושין, ומכאן גופא מדייק במקום אחר כן. אז, זה רק נודע אחר התירוץ. ותו"ת וע"ש.
* ג.
** תוכו ולא תוך תוכו -
כמובן, חורבן זה הוא באופן אחר, שלא מיירי כשחושב על זה מחשבת מין אחר, אלא מיירי כשמה שהוא בתוך זה הוא בתוך אחר.
ראשון, יש להעיר שזה משמע כצד שהבעיה במחשבה הוא שעושה אותו קצת כקרבן אחר. שני, עדיין מחודש, שכאן חושב כאותו אחר, וכאן הוא בתוך אותו אחר. ותחשב על זה.
** תוכו ולא תוך תוכו -
יש לדון למה, אם הוא מינו, צריך קרא. ותחשב.
* ג:
** רב יוסף בר אמי -
יש לדון אם אף זה קרה בבית המדרש באותו היום שלא היה שם.
** הכי נמי ליתי תוכו -
אין קרא מיותר לדרוש לומר שזה לא מהני, אלא לכאורה ר"ל שדורשים מתוכו, שמרבה כל תוך, לומר כן. ויש לדון, שאולי רק מרבה תוך שאין בו קל וחומר זה. ותחשב.
** שינוי בעלים אתוך תוכו -
יש לדון ל"ל תירץ שיש קרא לשינוי בעלים. באמת, יש לדון מתי צריכים שני קראי, ולא רק אומרים שיש סברה חיצונה כאחד. ותחשב.
** שינוי בעלים -
לעיל, שאל אחר שידע הקרא, והניח שנחשב שאינו מינה. אם כן, קשה למה לא אמר שחלוק כיון שיש קרא, כמו שנמצא מגמרא זה למסקנא. ותו"ת.
גמרא זה נגד מסקנא שם, שכאן מניח שהוא שני מינים.
* ד.
** המקריב את דם השלמים -
כאן, דורש ממה שמזכיר את שמו. אז, אי אפשר להקשות כמו שהקשה לעיל שזהו שמו. ותו"ת.
** חטאות הפנימיות -
מעניין שזריקה נחשבת שאינה בחטאת פנימיות, כיון שהוא במקום אחר. אולי היה אפשר לומר מכאן שדבר חלוק נעשה באותו זריקה. ותחשב על זה.
** אם אינו ענין -
צריך ביאור למה אין אומרים שכאן שינה עליו הקרא לעכב, ויהיה שחיטה בשינוי קדש מעכב. ויש לומר שהוא מפני שמיעט קרא שאר זבחים בחטאת.
** וישנו בציבור
- נמצא ששינוי בעלים הוא רק לחשוב על מי שאינו בעל (או שלא לחשוב על שום בעל), ולא שלא לחשוב על כל בעל. ותו"ת.
** וישנו בד' עבודות
- יש לדון במקור זה, שהיה אפשר לומר שאף פסול אם חושב ששחיטה יכפר. ותו"ת. אולי מה שהוא כל כך פשוט הוא כצד שכתבנו לעיל, והוא שהפסול בא ממה שנעשה מחשבתו קצת. אז, אולי קרבן נעשה קרבן אחר או קרבן לאחר[fn:2], אבל לא מכפר שחיטה. (וזה נלמד ממה שאין קרא אומר שיכול לכפר כלל. ותחשב.)
* ד:
** זביחה אין מידי אחריני לא -
יש לדון ל"ל מקשה משאר קראי. ותחשב.
** שכן -
אז, היה אפשר רק להזכיר חזה ושוק.
** ל"א -
יש לדון אם זה חלוק מלשון ראשון, או הוא רק מילים חלוקים.
* ה:
** למותרו -
ק"ק, שלא נקרב, אז, לאשם.
** חטאת נמי -
קושיית גמרא עכשיו מניח שחטאת חלוק רק מחמת קושיית ריש לקיש. ותחשב.
* ו.
** מקיבעא -
מעניין שאין זה סיבה להביא הקרבן.
** ומתכפר -
איהו הוה בעלים- יל"ד מה ר"ל; לכאורה, קל לומר שמתכפר עושה תמורה כיון שהוא מתכפר בו, ולא מחמת בעלות שיש עליו. מה שאומר רש"י משמע שלא כזה. צריך ביאור איזה בעלות יש לו (ולמה יש לו), ולמה צריך אותו בעלות.
** ומתכפר
- מעניין שרש"י אומר עליו שהוא בעלים שלו, שהוא בעל שלו, שהוא רק יחיד. בני אדם, אף היום, אומרים בישיבות שאדם אחד הוא בעלים של חפץ, אבל צריך ביאור למה יאמרו כן. (אולי הם סומכים על רש"י- אבל עדיין צריך ביאור למה רש"י עושה כן.)
** מכח לשמו -
לכאורה, ר"ל שכבר נשחט, ועכשיו הוא נדבה. כוהנים חייבים להקריב קרבן נדבה. אבל, שני יש בו חיוב על הבעל להביא, וזה קשה, שאין אדם חייב להקריב קרבן נדבה.
אם כן, "מכוח לשמו" ר"ל שכבר נשחט. בא לבאר למה נשחט כבר, ומבאר שהוא מפני שחשבו שיעשו אותו בכשרות. דחוק קצת.
** אמר רבא -
זה מעניין, שזמן שהיה חייב לסמוך אינו שעת שחיטה, שצריך לסמוך קודם. אז, שעת ביטול אינו שעת שחיטה. אבל, השעה שביטל אותו הוא שעה ששחט. וצריך לחשוב על זה, שהוא מעניין מאד.
** אי אמרת בשלמא -
עולה- ק"ק, שלכאורה, מה שצריך להביא עולה שניה הוא שנדר, וזה לא עלה לידי נדרו. אבל, כפרת עשה לא שייך, שאין החיוב בא מן העשה שעבר, אלא מנדר שנדר. אולי מניח גמרא שעלייה לנדרו וכפרת עשה שווים.
** כאילו -
לכאורה, גמרא לא ידע שרצה לומר שהוא שאף על פי כן כיפר, אלא הוא שכיפר על מצוה אחד ולא כיפר על אחר. אבל, עדיין צריך ביאור איך באר לשון "כאילו."
* ו:
** וליקו ולימא -
לכאורה, ר"ל שלא מסתבר לומר שקרא מצריך שיהיו בשני זמנים, שלא אומר כן. אז, צריך לומר שלא מצריך זה. אז, צריך לומר שיש טוב אף אם מפריש אותם בזמן אחד.
* ז.
** ואמר רבא -
נראה שלמעשה הקל וחומר נדחה (ויש לדון למה), שאם כן יכפר אף מקיבעא. ותו"ת.
** דאין בעלים לאחר מיתה -
זה מעניין. עדיין חושב עליו לבעל שאינו בעלו. ותחשב. ועיין לעיל גבי קרבן ציבור. ואולי צריך שניהם (שחושב על מי שאינו בעלו ולא חושב על בעלו) כדי לפסול.
** אלא שמא מינא -
צריך ביאור איך מבארים, לפי זה, כל מה שאמר גמרא שמכפר על עשה. ותחשב. אולי אין הכי נמי, חולק עליו.
** מקופיה -
עיין במה שכתב. צריך לחשוב על אותו סברה.
* ח.
** ולקח הכהן -
למסקנא, לומדים משלמים שכל העבודות שווים. אם כן, רק צריכים קרא אחד. כמו כן, לא צריכים שני קראי לשינוי בעלים, שכבר לומדים למצווה משלמים.
** שינוי בעלים מנא לן -
ואם תאמר הרי כבר יש לנו מקור מזריקה (וכל העבודות שווים משלמים). אולי אומר כן אגב מה שצריך כן למסקנת גמרא, שלא לומדים מחטאת. ויש לדון בזה, שאולי למסקנא, כמו שהוקש לשלמים, הוקש לעצמו, וכל מיני חטאת בכלל. יש לדון, שלא נראה כן, שגמ' בע"ב, שהוא למסקנא, כותב שצריך מה מצאנו וצד השווה.
* ח:
** ואפילו עופות -
צריך ביאור למה רק מזכיר חטאת העוף. יש גורסים עולת העוף; כמו כן, יש לדון למה רק מזכיר עולת העוף.
כמו כן, יש להקשות למה לא אומרים כאן שרבי שמעון חולק, שהרי ניכר שאינו עוף. אולי אין הכי נמי, וגמרא זה הוא רק לפי רבנן.
נראה שאולי ניישב שנים אלו על פי מה שכתב רשב"א, והוא שחטאת העוף ועולת העוף הם שני חלקים של קרבן אחד, וחטאת עוף מתיר הקרבת עולת העוף.
נראה שאולי כן הוא בקרבן, שיודע שזה קרבן, אבל סובר שעושה מעשה קרבן העוף, והוא שמתיר קרבן עוף להיקרב. ותחשב. נראה, אז, שאולי אין חילוק בין מי שאומר שהוא חטאת העוף למי שאומר שהוא עולת העוף, שהם קרבן אחד, וסובר שהוא חלק מאותו קרבן אחד. ותחשב.
(כתבנו זה לתרץ לקושיית ראשון, אבל לתרץ לשני, אפשר לומר שסובר שעושה טובה של חטאת העוף, כל מה שהוא. ותחשב. כתבנו שניהם ביחד כיון שנשמע יותר טוב אז, כיון שאז היתר של קרבן שני יותר מסתבר להיות נעשים על פי בהמה, שהרי מתיר כמה דברים להיקרב. ותו"ת.)
* ט.
** הנאכלים -
היה אפשר לומר שיותר דומה לקדשי קדשים מפני שהוא נאכל לזמן מעט. יש לדון, שאולי עדיין אין זמנו ממש שווה.
** לא עיברה -
אבל הוא קודם זמן הפסח.
** שחטה לשמה -
יש לדון אם זה פסול בשחיטה או בזריקה. נראה שהוא פסול בשחיטה, שהרי אין זריקה בע"ז, וכן אם הוא פסול בזריקה, יהיה יכול לחשוב שני מחשבות פיגול בפיגול. ותחשב.
ויש לומר שעושה כאילו עושה זריקה והוא פסול (וזה רק דוחה ראיה שהבאנו מע"ז).
** שחיטה -
אותו שם- היה לו לומר (ואולי כן אומר) שמעשיהם שווים.
* י.
** פסח יוכיח -
אם כן, קשה ל"ל נלמד שעולה שלא לשמה פסול.
** דמה למעלה -
יש לדון למה חושב גמרא שזה פירכא; לכאורה, הייתי אומר שזה רק חילוק דין, אבל אין זה סיבה להחמיר בחטאת, שאין זה חומרא. אולי לא צריכים שיהיה חומרא; כדי לעשות פירכא, אולי רק צריכים חילוק דין, שמה שהוא חלוק בזה יורה שהוא חלוק בזה (אלא אם כן שני הדינים חלוקים, כמו אם זה לחומרא וזה לקולא). ותחשב.
** הרי אומר -
יש לדון (ויש לדון בכעין זה בכמה מקומות) בכמה ענינים. הרי, נמצא שר"א אמר מקור, ודחו אותו, ואמר עוד מקור, ודחו אותו, ואמר עוד מקור. אז, צריך ביאור מה היה עושה עם מקורות אחרים שלו כשלמד ממקורות ראשונים. אולי אין זה כל כך קשה, שאולי יכולים לומר על כעין זה שטרח וכתב קרא.
אינו כל כך קשה לומר כן על ראשון, שזה קל וחומר. (עדיין כיון שהוא קרא, יש לדון ל"ל הקשה מזה. נראה שאולי יותר קל לחלוק על דרשה מקרא מלחלוק על קל וחומר, ואז הקשה ממה שהיה להם יותר להודות לו בו. כעין זה מצאנו בפסחים (סו.).) יותר קשה לומר כן על שני מקורות שלאחריו, שהרי שניהם קראי. אולי כמו שאומרים כן על קל וחומר, כך יכולים לומר על דרשה מקרא. יש לדון בזה, שאז לכאורה אין מעלה במה שתורה כפלו. ויל"ד, שאולי יש מעלה במה שנכתב שני פעמים.
יותר נראה לומר, אולי, שלא ידע דרשה שנית כשאמר ראשונה, וכן לא ידע שלישית עד שידע שנית. אם כן, מוזר הוא מאד; נמצא שר"א, שחלק לטעם אחד, מצא עוד מקוט, שלא שייך לטעם ראשון שמצא. אז, מוזר שיהיה הוא שלעום מוצא מקורות. ותחשב.
נראה שאפשר לומר שרצה לומר כן- אולי היה לו מסורה שכן הוא הדין (שהרי ר"א לא אמר דבר שלא שמע מפי רבו (סוכה כז: וברכות כז:)), או אולי היה מסתבר לו כן[fn:3]- ואז מצא הרבה מקורות לו. ותחשב.
** אשם נמי... למעלה -
קשה, שנלמוד את זה מהיקש, כמו שאומר רש"י , והרי לא למדנו היקש כבר (אלא דן איך ילמוד בלי היקש). לולי רש"י, יש לומר שמקשה ל"ל לומד אף זה מקל וחומר; אבל רש"י לא כתב כן. ותח'.
** עולה -
קשה ל"ל לומדים גם כן מעולה שאין פסול שלא לשמה.
* יא.
** לפיכך קמצה -
צריך ביאור ל"ל לומדים צד השווה מפסח וזה. אולי זה נחשב שייך לכרת, כיון שהוא מין חטאת.
** אם בשאר
- שינה עליו- נמצא שלזה צריכים לשנות עליו כדי שיעכב. יש לדון בגדר לזה, שלכאורה, לא צריך לשנות על מה שקרבן רק בא ממין בהמה מיוחד. ותחשב.
כמו כן, לא צריכים כפל על מה שמוסף רק הוקרב ביום טוב. יש לדחות שאין מוסף אלא קרבן רגילה שנקרב ביום טוב. אז, אולי, למעשה, אינו מעכב, שאותו קרבן נקרב בכל יום. ותחשב.
** החמרת בשלמים -
יש לדון ל"ל לומד עוד רבי אליעזר לפסול בשאר ימים. ותו"ת.
* יא:
** שאינו כשר לשמו -
יש לדון בזה, שלכאורה, אין הפסול הכוונה, אלא הפסול הוא מה שאז פסח הוא, ואינו בזמן הנכון. ותחשב.
** שלמים קודמים -
מעניין שסובר שזה ראיה לכאן, שהרי שם אף מזכיר דרגות בתוך קדשי קדשים שלא מזכיר כאן.[fn:4]
** אין לך כשרה -
אם דורשים כן, נראה שעדיין קשה, שאז נאמר שכשר מבעוד יום, ורק לא יכולים להקריב דבר אחריו. ואם תאמר אם כן, צריך להביא אותו מאוחר. עדיין לא מהני, שיש נפקא מינא אם לא שהה להביא אותו. ויש לדון, שאולי אין הכי נמי, מהני.
אבל, היה אפשר לומר שהוא כעין פסח, ורק אם כבר באו זמן אחרים לא יכולים להיקרב אחריו. ויש לדון, שבפסח, הדין הוא שצריך להיקרב אחר תמיד. דין זה הוא רק אם יש תמיד. (עדיין צריך ביאור מהו המקור לזה.) אבל כאן, הדין הוא שאסור לאחרים להיקרב אחריו. אם כבר הודלקו, באים אחריו.
** מערב עד הבקר -
היה אפשר לומר שדורשים מזה השיעור, אבל לא שצריך להידלק אז. נראה שגמרא מניח שלכן ניתנה אותו שיעור.
** שלמים
- של היום- עיין לקמן, שדן גמרא מהו הדין אם של ימים חלוקים הם.
** עיקר
- מרש"י נראה שרל שהוא הפעם הראשון שהזכיר אותו תנא. לולי רש"י, היה אפשר לומר שזהו המקום שיזכרו בני אדם ראשון כשחושבים על הדין. אולי זה לא נכון כאן, והיה רש"י צריך לתת פשט אחר (אבל אולי כן הוא במק"א). דחוק.
** גברא אידחי
- עיין במה שפירש רש"י. צריך לחשוב מהו יסוד של חילוק זה.
לולי רש"י, היה נראה לומר להיפך: במומר, קרבן נדחה, שאינו טוב אם נקרב עכשיו. אבל כאן, רק הגברא נדחה, שלא יכול להביא, כיון שפסקו שאין לו להביא, אבל עדיין היה הקרבן טוב אילו הובא, שהרי נמצא שטעו. ותחשב.
* יג.
** בני אהרן -
נמצא שחולקים תנאים אם "בני אהרן" כולל פסולים או לא. חושב אני שיש גמרות שסותרים זה את זה בענין זה; ועכשיו, קל לתרץ שאחד כר"י ואחד כר"ע.
** דיקא... נפסל -
משמע שההוה אמינא להקשות כולל הוה אמינא שמשנה שלנו מבאר דין פיגול. לכאורה, זה מחודש, שהרי משנה הוא בתוך פרק שדן בשלא לשמו ובתוך משנה שדן בשלא לשמו. אם תדחה שכל ההוה אמינא הוא שאומר שני הפסולים (שלא לשמה ופיגול), עדיין קשה, שאז אין לדייק, שאולי אמר לשון פסול, ולא פיגול, כיון שאחד מן המנויים אינו פיגול, אלא רק פסול.
* יג:
** הואיל וחוץ למקומו פוסלת -
קשה, שכמו שנדמה חוץ למקומו לחוץ לזמנו, נדמה טבילת אצבע לעבודות שלמים. נראה מהמשך גמרא שפשוט לגמרא שאי אפשר ללמוד זה מזה כיון שיש פירכא. סובר שבזה אין פירכא. אז, דיחוי גמרא כאן הוא שאולי רק יכולים ללמוד מה שאין לו פירכא. (ויש לדון מהו הפירכא של טבילת אצבע, שלכאורה, לא למד עדיין פירכה של מה שהוא נוהג רק בקרבן אחרד, שאם כן, היה לו לפרוך אף על לימוד שמנסה ללמד.)
גם יש לומר שיכולים לומר ששלא לשמו ופיגול הם שווים כיון שהם מעשה דומה, ששניהם מחשבה. אבל, לא יכולים לומר שטבילת אצבע הוא כעבודה אחרת, כיון שהוא מעשה חלוקה. וחתשב.
** מעכב -
נמצא, לכאורה, שגמרא לומד דין, אף שאינו ממש מה מצינו, שיש פירכות, כיון שלומד יסוד הדין, ועושה שהוא, אז, נוהג במקומות אחרים.
** דבר המעכב כפרה -
צריך להגדיר את זה, שמגמרא לקמן יוצא שצריך כהן ליקח את דם החטאת (החיצונה) באצבע שלו, אבל אף על פי כן, לא מהני מחשבה. אולי שם דורש מן הקרא, אבל בלי זה, היינו אומרים שהוא עבודה. עדיין צריך ביאור מהו עבודה, ולא רק המקור. צריך לומר שהוא כל זמן שגורם אותו באופן חשוב. כמובן, צריך להגדיר את זה.
* יד.
** מודה היה לפסול -
מעניין שיכולים ללמוד פסול פיגול מפסול שלא לשמו. היה אפשר לומר מן הסברה שהם פסולים חלוקים, ששל"ש פסול, אבל פיגול מרצה לפיגול שלו, ומזה בא פסולו. לא נוהג בו, אז, פסול רגיל. ותחשב על זה.
** חוץ לזמנו
- כרת- יש עוד סיבה למה אי אשפר לחייב כרת, והוא שאין עונשים מן הדין. נראה שמזכיר זה כיון שהוא יותר פשוט, שקל להבין שאין סיבה כלל לחייב בכרת (אין שום מקור). ותו"ת.
** שכן נוהג בבמה -
קשה, אז, איך לומדים משלא לשמה למחשבת פיגול. יש לומר שלא נלמוד משלא לשמה, אלא משלמים. קשה, שהרי לשלמים יש תנופה וכדומה. וצריך ביאור.
** אם תימצי לומר -
יש להעיר שזה מוסיף חידוש על המשנה, שבמשנה, לא היה העבודה נצרך, ואז אין מחשבה שבו פוסלת. כאן, אותו עבודה שעושה נצרך- אף שלא נצרך כאן. אז, היה אפשר לומר שיכול לפסול בו.
** שאי אפשר לבטלה
- לאו אורח ארעא- משמע שאפשר לשחוט שם, אלא שאינו אורח ארעא. מעניין, אז, שנחשב אי אשפר לבטלה. אולי רש"י רק מבאר סיבת הדין. ק"ק למה רש"י יעשר כן.
* יד:
** דומה ליושב -
הנחת גמרא הוא שצריך הולכה. אין זה כל כך פשוט, שהרי, כששוחט קרוב למזבח, לא צריך הולכה. אז, רואים שהולכה אינו נצרך. אולי, עדיין, כשנעשה הולכה, יכול להיות פסול בו, אבל אם זה לא נחשב הולכה, מחודש לומר שיפסל.
** הולכת אברים
- עיין במה שפירש. זה מחודש, שהיה אפשר לומר שהבאת הבהמה השחוטה שם נחשב הולכת אברים, שאל נשתנה כל כך אחריו. ויש לדון, שאולי רש"י רק ר"ל שאם שחט שם, לא צריך להוציא להפשט וניתוח.
* טו.
** לבראי נפיק -
היה אפשר לתרץ שיצא לגואי ויצא לבראי, ונטל ממה שיצא לבראי, כיון שהוא כשר. אולי כל הדם נחשב אחד, ואותו הדם הלך. ויש לדון, שכמו שנאמר שאותו דם נחשב אחד, ואז קרב, הרי אף רחק. אז, יש לדון אם נחשב שנקרב. ותחשב.
** רבא אמר אף -
מצאנו כעין זה לרבא בכ"מ, כמו שמצאנו שרבא יאמר "פלוני על פלוני קשה, אחר על אחר לא קשה," ושרבי יוחנן יאמר ששניהם דורשים מחד קרא. לכאורה, מעניין שאמרו כן בכל כך כמה פעמים. הניחא מה שדרך אביי לומר מניני תנאים שסוברים כהדדי אינו כל כך קשה, שיש לומר שכולם סברו כן, אלא לא החשיבו למנותם חוץ מאביי. אבל, כאן, יותר קשה לומר כאן, שאם כולם סברו שזה קשה, היה להם להקשות. אז, צריך ביאור למה הוא דווקא רבא ורבי יוחנן וכדומה שהתעוררו עליו. ותחשב.
* טו:
** וינזרו -
נראה שנקרא,  "ונזרו מקדשי- מי? בני ישראל- ולא יחללו." ויש לדון, שאז אין "קדשי" קאי על כלום, אף שיש אחריו יו"ד. ותו"ת.
* טז:
** שם טומאה -
אומר שהיתר במה לא נחשב הותר. אם כן, ק"ק ל"ל מקשה גמרא איך נלמד מיושב, כיון שאונן הותר מכללו. ותחשב.
* יז.
** קלשא -
צריך ביאור ל"ל אומר כן אף על הלימוד ממנו בעצמו.
* יז:
** קסבר -
קשה, שלכאורה מוכרח כן מקראי, ולא רק שרבה סובר כן. נראה שלולי רבה, יכולים לומר שמילתא דאתיא בקל וחומר טרח וכתב אותו קרא. ותח'.
* יח.
** להבדיל למה לי -
ביאור של גמרא זה הוא כך: דורשים מ"והיתה להם כהונה" לחלל כל עבודה שעליו עבודת זר חילל. כל עבודה הוא כן. אז, לא צריך עוד קרא ללמוד משתויי יין. אז, צריך לומר שלא לומד משתוי יין, אלא מלמד לשתויי יין. אז, לא צריך עוד קרא של שתויי יין, ומקשה מה דורש ממנו, כיון שלא דורש זה.
** חסר… ייתור -
יש לדון אם הם פסול אחד או שנים פסולים (ר"ל אם הפסול הוא דבר שווה או לא). ותחשב.
* יח:
** יתר כמאן דליתיה -
לכאורה, הדיון הוא אם מעלה של דבר שיש בו ארבע הוא בא מחמת שיש לו רק ארבע או מחמת שיש לו ארבע. אם כן, מעניין שסובר ששני חלקי הלכה יהיו תלויים זה בזה.
גם יש לומר שהדיון הוא אם ארבע כנפות שיש להם חמישי הם שווים לארבע כנפות שאין להם חמישי, שאולי כשאין להם עוד כנף הם יותר חשובים. לצד זה, יותר מסתבר למה כל דינים שבתורה יהיו תלויים. עדיין יש לדון למה לא יספק בדיון ראשון.
** פרט
- עיין במה שפירש. משמע כשיטת הרא"ש (שפוטר דבר שדרכו ללבוש בלילה), ולא כרמב"ם (שפוטר כל דבר בלילה).
אפשר לומר שרש"י אף חלוק מרא"ש, שאולי רא"ש תולה אותו על השתמשות שלו, אבל רש"י תולה אותו על עשייתו.
* יט.
** שלא במקום עבודה -
צריך ביאור למה אין שמאל כלול בזה. נראה שאולי "שלא במקום עבודה" מחדש אף מקום שכשר לעבוד, ואפשר שיעבוד בו, אבל לא מצוי שיעבוד בו. החידוש הוא שלא חוששים שיעבוד בו ויפסול.
** חציצה -
צריך ביאור למה לא נאמר שהוא לקיחה על ידי דבר אחר, כמו בגמרא סוכה (לז:). אולי זה כרבה, שחולק שם. גם יש לומר שלקיחה ר"ל שהוא כרוך על שני צדדי אותו דבר. אז, הוא רק לקיחה על ידי דבר אחר אם אותו דבר כרוך, ולא כאן, שהוא רק בצד אחד.
** אגב אורחא -
יש להעיר שעיקר חידוש של המשנה בא, כמו שמבואר ברש"י, ממה שמסי. אז, לא רק נקט אותו למילי דעלמא.
אפשר לדחות שפשוט שמותר בבית המקדש, ורק מחדש שאסור אם מכוון לעשות חבורה. (ההו"א יהיה אולי שאף זה נדחה לעבודה. גי"ל שההו"א הוא שאינו חבורה.)
** שער
- ראש- מקשים שצריך כהן לגוז את ראשו. יש לומר שיש נפק"מ אם מעכב עבודה, שאין גיזתו מחלל, אבל חציצה מחלל. גם יש לומר שמכוון רש"י כאן לזקנו. לשונו לא משמע כן, שהיה לו לומר זקנו, ולא ראשו.
** תפלה -
צריך ביאור ל"ל פוטר מחמת עוסק במצווה. אולי אפשר לקיים שניהם. מוזר לומר שאפשר לקיים תפלה ולא אפשר לקיים תפילין.
** צריך ביאור
למה משתמשים באותו מילה לחציצה ולייתור בגדים. משמע שיש אותו בעיה. נראה שהוא מודיע לנו שהבעיה של ייתור בגדים הוא שווה לחציצה (עיין לעיל), והוא אותו בעיה של מי שיש לו חציצה בינו לבין בגדו. ותחשב.
* יט:
** מתחילת עבודה -
לא דווקא הוא, שהדין הוא כן אף אם לא קידש באותו עבודה, אלא שלא הסיח דעתו.
** ביאה ריקנית -
שמעתי שיש איסור בביאה ריקנית. אז, מעניין שנותן נפק"מ מה לעשות בציור שאסור. אולי יש לומר שרק אסור אם אין צורך להקדש. אבל, אם הוא ליטול שרץ וכדומה, שיש צורך להקדש, אבל לא עובד, מותר; ואומר עליו כאן שפטור מרחיצת ידים ורגלים.
* כ.
** בכלי שרת -
לכאורה, ר"ל שלא צריך עוד מים להיות על ידו. כיון שהפסול הוא המים, נמצא שכאן אין פסול.
** מקום דריסת
- נראה שעד שם מותר ביאה ריקנית, אבל לפנים ממנו אסור. לכן, הוא מקום דריסת רגלי כהנים וישראל. ותחשב.
* כ:
** כעין עבודה -
יש לדון אם זה דאורייתא או דרבנן.
* כב:
** מתכפרים -
ק"ק, שלכאורה, אין זה עושה שלא יכול לשלח קרבנות שלו, אלא רק עושה שלא יכול לאכול. מה שלא יכול לאכול הוא העושה שלא ישלח. ותחשב.
* כג.
** זב -
דחמירא- לכאורה, רק צריך לומר שאינו בתוך הלכה למשה מסיני. אולי כיון שיודיעם שאינו בתוך הלכה למשה מסיני, יכולים לתת טעם, שהוא מפני חומרתו.
* כג:
** צריך ביאור
ל"ל מתרץ גמרא שדן בטומאת כהן, ולא בבעל. ותחשב.
* כה.
** אימא בשמאל -
נמצא, לכאורה, שיש הוה אמינא שפסול שמאל הוא מפני שאינו מהודר. ותו"ת.
* Footnotes
[fn:1] לכאורה, אם כן, לא צריכים מחשבת שם, שהוא כלול במחשבת ריח ניחוח. יש לומר שצריך מחשבה רק שמהנה למי שהקרבן שלו. מחשבה לה' הוא שצריך לחשוב שהקרבן הוא של ה' (ואף אם אין זה אומר שהוא נהנה, בלתי מחשבת ריח ניחוח). ותחשב.
[fn:2] וצריך להגדיר את זה קצת, שאטו אותו איש יש לו ריצוי מחמת זה. ואולי אין הכי נמי, יש לו.
[fn:3] לכאורה, אי אפשר לומר שהיה מסתבר לו עד שלא היה צריך קרא, שהרי צריך מקור. אז, צריך לומר שהגדר של קרא שהיה צריך למצוא היה יותר קטן, כיון שכבר מסתבר כן. ותו"ת.
[fn:4] יש כמה קושיות שבאים מזה:קשה, אז, איך יכולים ללמוד משם.אולי זה מוכיח שצריכים ללמוד משם. אז, קשה ל"ל הוכיח כן בקדשי קדשים, שהוא דבר שיש בו ריצוי. אז, עדיין נשאר ראית גמרא. ותחשב.
