* פא:
** כשם שעליונים -
הלשון משמע שיש דמיון ביניהם. צריך ביאור מהו הדמיון. לכאו’, הענין הוא שיש יותר קדושה בדמים עליונים, וכן יש יותר קדושה בדמים שבפנים.
* פג.
** רבי שמעון -
אפשר לבאר בשיטת רבי שמעון שמה שהוא מונח על המזבח הוא שמקדש אותו. אבל, אלו לא באים בגלל קדושת עצמם, אלא בגלל קדושת קרבן אחרת. אז, מה שהוא מונח על המזבח לא יכשיר אותו.
אבל, זה לא מספיק לפרש את שיטת רבי שמעון, שאם כן, כשעיקר הקרבן כשר, לא ירד. צריך לומר שיש מין קדושה שונה כשהוא על המזבח, וזה לא בא לעיקר הזבח. אבל, עדיין כשר, שאם שניהם נפסלו, ושניהם על המזבח, לא ירד.
אז, לכאו’ צריך לומר שכיון שרק בא בשביל דבר אחר, אינו כל כך קדוש, ואף שמזבח מוסיף לו קצת קדושה, אין בו קדושה כ"כ עד שיכול להקריב אותו. ותחשב.
* פד.
** כדרבא -
גם היה אפשר לדחות שאף בלי חידוש של רבא יש ציור של מנחה הבאה בגלל עצמה, כמו של סוטה. אז, אי אפשר להוכיח כרבא מן המימרא. ותו"ת.
** נסכים הבאים -
קשה, שזה נאמר בפירוש במשנה (שרבי שמעון דן בנסכים). אם כן, אף שחידוש הוא לדרוש אותו מן הפסוק, אחרי שיש לנו המשנה, אין הדין חידוש, ולא היה לו לר"ל להשמיע אותו לנו.
* פד:
** פסולן בקודש -
יש לדון למה הם יותר ראויים להקרבה:
1. מפני שהם היו עומדים יותר להקרבה.
2. מפני שהם הגיע למצב יותר גבוה של קדושה קודם שנפסלו.
** סמיך ליה -
לכאו’, רצה לומר שעיקר מקור שלו הוא משם, שזה מגלה שיש מה לרבות. עכשיו, צריכים לבחור מה לרבות, ובזה יכולים לסמוך על לימוד דבר שלא בהכשרו מדבר בהכשרו.
* פז:
** יש חיבור -
קשה, שלפעמים אין רוב, והוא כשהוא חציו בשווה. וא"ת אי אפשר לצמצם. לא נראה שנאמר כן כאן, שבוודאי יצמצם. נראה שרק צריכים לבטל את האויר, ואף אם הכבש והמזבח שווים, יש מה לבטל את האוויר. ותחשב.
* צא.
** למוספי שבת לא אהני -
צריך ביאור מה היה ההו"א, שאם סובר שאין קה"י של זה מועיל לזה, אז אין קדושת שבת במוספי ר"ה. אם כן, לכאו’ של שבת יהיו יותר קדושים, ועדיין דין של המשנה נכונה. ותחשב.
** מצוי -
ביני ובין א.י.ד.ל. יצא שיש להקשות איך מילה מצויה, שאף שמילה נעשה בכ"מ לכל אחד, הרי פסח נעשה ע"י כל אחד פעם אחת. רק יש יותר מילות מפסח אם יש יותר בני אדם בחבורה משנים שאדם חי. ותו"ת. נראה שהענין הוא שיש יותר זמני מצווה (ומה שהוא מצוי ר"ל שכל זמן האו יותר זמן של מצווה, שיש צד גדול שיקרה אז מצווה) במילה משיש בפסח. ותחשב.
** לגבי פסח -
יש לדון אם אותה מעלה ממש שווה למעלת תדיר או שרק נקרא בלשון תדיר, אבל הוא מעלה אחרת. מרש"י נראה שהוא שווה, וכ"נ מסברה, שא"כ היה לו רק לומר שתדיר אינו דווקא, ולא צריך להוסיף, “… לגבי פסח….” ויש לדון, שאולי לא היה קורא לו תדיר אם לא היה כוחו שווה לתדיר, ואם הוא שווה, עדיין יש להביא ראיה ממנו. ותחשב.
** לברכת היין לא אהנאי -
יש להוכיח כן ממה שבית שמאי לא אומר שמקדימים את ברכת הקידוש מפני שהוא מקודש.
* צא:
** רש"י ד"ה הא ר"ש -
נמצא שלפי רש"י אם יכול לעשות דבר באופן שלא יהיה פסיק רישא, מותר לעשות אותו גם באופן שהוא פסיק רישא. ותו"ת.
* צב.
** זאת -
כנראה, אף שיש מיעוט מלשון שחיטה, היינו אומרים שכמו שלשון אכילה אינו דווקא, כך לשון זה אינו דווקא, ולכן צריכים "זאת.” אבל, כדי לפרש מה נמעט, צריכים לשון שחיטה.
* צב:
** רש"י ד"ה זו שאלה -
רש"י לא פירש שהוא בלשון תמיהה, שאטו מפני שהוא סובר כר"ע, יתמה על מי שלא סובר כמותו. ותו"ת.
* צד:
** פוחתו -
קשה למה אינו מטהר אותו במקוה.
* צז.
** ממתין –
יש לדון מה צריך לעשות אם הוא קודם שנעשה נותר. לכאו', מדברי רבי טרפון, רואים שלא צריך מריקה ושטיפה, אלא רק הגעלה. לא רואים שרבנן חולקים על זה (אלא שחוששים שלא יגעיל או שסוברים שאין בישול דבר אחר עושה הגעלה).
אבל, איני מבין למה אומר להמתין עד שנעשה נותר, ולמה לא יגעיל אותו קודם לכן. ותחשב.
* צז:
** יקדש –
וא"ת אין עשה, כיון שפסול הוא. וי"ל שאין אומרים חענ"ן, ורק הבלוע פסול, ואין בו מצווה, אבל יש מצווה על השאר. ותחשב. (אף ששיטת ר"ת הוא שאומרים חענ"ן גם על שאר אי' מן התורה, צריך לומר שאינו ממש אוסר את כל שאר הדברים, אלא מצטרף אותו לענין שיעור ולענין ביטול. דחוק. צריך לחשוב.)
* צח.
** אין שפיר ושליא –
מעניין שיכולים לדרוש כן, שאם לומדים את כל הדין מאשם, גם נלמוד שאין וולד קדוש. זה אי אפשר לדרוש, שכ' קרא שוולד קדשים קדוש. אבל, מעניין שזה לא נמעט מדרשת מיעוט שפיר ושליא.
נראה שיש חילוק גדול בין הצד שוולדות קדשים במעי אמן קדושים והצד שוולדות קדשים בהוותם קדושים. לצד ראשון, קדושה באה מן האם, שכיון שהיו חלק מן האם, נעשים קדושים, ואז נמשכים בקדושתם. אבל, לצד שבהוויתם הם קדושים, קדושה בא ממה שהם מיחחסים לקדושה. אפשר להוסיף שהחילוק הוא אם קדושה בא מאם לו או שיחס לאם הוא סיבה לקדושה. לצד ראשון הוא בא מאם, ולצד שני הוא סיבה לקדושה.
אם כן, יש לומר שכיון שוולדות קדשים בהווייתן הם קדושים, אין זה דין של האם, אלא של הבן. אם כן, אין לומר דין זה באשם, שלא מקדש את בנו, שתמיד אין זה דין של האם. גם אין לומר דין שאין וולד קדוש, שאין וולד שנאמר עליו שאינו קדוש. אז, אין ללמוד מאשם שאינו קדוש. ותחשב. יותר מזה, אז יש חילוק בין וולד לשליא, שטעם זה שייך רק בוולד. אם כן, ל אנחשב דין אחד, ויכולים לחלק ביניהם. ותחשב.
** אפשר משאי אפשר –
יש לדון למה לא נלמוד אפשר משאי אפשר:
1. שיש פירכא גדולה ביניהם, במה שזה אפשר וזה אי אפשר. וא"ת אין פירכא על היקש. ויש לומר שפירכא גדולה כזה סובר שפורכים.
2. שאין הדין נוהג בו. למשל כאן, אין דין באשם שאין שפיר ושליא קדוש בו, שאין זה דין אלא מציאות. ותחשב.
** אף כל –
עיין ברש"י. נראה שהו"א שרק בשרו מותר, שיכול לקיים בו מצוות אכילה. כמו"כ י"ל שהו"א שרק נלמד שעצמותיו מותרים ליוםם אחד, כיון שלומדים מבשר. ותחשב. וא"ת ל"ל נלמוד מעור. ויש לומר שעור אינו כ"כ חלק מן הבהמה, ואז יש לומר שרק הוא לא קדוש. ותחשב.
** ד"ה אינו חוצץ – תלוי בקפידה –
נראה שהענין הוא שצריך מים על כל הבגד. אם לא מקפיד בזה, הוא בטל לבגד, ואז אין חציצה. אם מקפיד, אינו כחלק מבגד, וממילא היה חציצה. ותחשב.
* צט.
** ד"ה מקריב אונן – א"צ –
ממשע מרש"י שכה"ג א"צ לצאת, אבל, אם רוצה לצאת, יכול לצאת, ואין בזה עבירה.
* צט:
** שלמי פסח –
כמובן, זה אי אפשר לרב ירמיה, שסובר שאין לחלק בין קדשים של פסח לקרבן פסח.
* ק.
** לא קשיא כאן שמת –
אם כן, לא יכול לתרץ כרב אסי, שאומר שבריי' שאמר שרק פסח יכול לאכול הוא רק כשהוא יום קבורה. ויש לדון, שאפשר שלא מוקים את זה כרבי שמעון, ורק רבי שמעון אומר שלא יכול לאכול פסח ביום מיתה. אבל, יש תנא שמתיר פסח ביום מיתה, והוא השונה את הבריי' שמתיר רק פסח. ותחשב.
שו"ר שדרש"י כ' שלא יכול לתרץ כרב אסי.
* קא.
** יותר מדברי תורה –
לכאו', כאן רק צ"ל כמו דיני תורה, שגם בדיני תורה (ביום מיתה) גזרו איסור בלילו. אז, יום קבורה שווה לו, שבשניהם גזרו איסור על לילו. ותו"ת.
** לא שמעתי -
יש להקשות מגמ’ בשבת וחגיגה שאומר שבזמן חורבן ביה"מ היו בני אמנה בתורה, שאמרו שלא למדו, ולא אמור שלמדו ושכחו. כאן, אומר שמשה לא בוש והודה ששכח, שהיה אפשר לו לומר שלא ידע. קשה, שכאן משמע שיותר טוב שלא למד ושם משמע שיותר טוב ששכח.
החילוק הפשוט הוא שכאן כשאומר שאל שמע, יכול להיות שהיה עמל בתורה, ורק שדבר זה לא למד. אבל, שם הם מודים שלא למדו כלל (שכנראה שם שאלו להם בדברים שכל מי שלמד יידע).
יש שמתרצים שאילו משה לא היה שומע, לא היה הדין כן. אבל, קשה, שזה קל וחומר. הרי, לכאו’ אין קו"ח צריך להיות הל"מ. נראה שצריך לומר שאף שאדם דן מעצמו, ה’ אמר את כולם למשה. אז, כדי לדרוש לא צריך לדעת שהוא הל"מ, אבל אם נודע שאינו הל"מ, בוודאי אין לדרוש. ותחשב.
[אגב, עיין בגמ’ בב"ק (צה או קרוב לזה) שאומר אמורא שלא אוהב דברי אמורא אחר שלומד מסברה, שנדחה מבריי’. משמע שאף שכבר חלק על בריי’, אין הל’ כמותו, בהכרח, נגד בריי’. זה נגד צד שאמר רב אלחנן בביאור איך רב חלק על בריי’ ורבי יוחנן חלק על רב, והוא שרב לא היה תנא, אליבא דהל’, אבל חשב שהיה תנא, ואז היה חולק על בריי’, וכיון שחלק, לפעמים הל’ כמותו. ותחשב.]
* קב.
** משה זר הוא -
וא"ת ל"ל אמר שמשה ואהרן היו פסולים כיון שהם קרובים. וי"ל שכיון שיש חסרון סיבה במשה (שהיה זר), לא יזכיר מה שהוא קרוב, שהוא רק מניעה. יש לדון אם זה נכון ואם זה יספיק. גם יש לומר שרצה לחדש שמשה נחשב זר.
** אני כהן -
יש לדון אם ה’ לא נחשב קרוב או שפסול קרוב לא פוסל בה’.
** שאני נגעים -
אז, כשאומר שמשה זר היה, אינו כ"כ דווקא, ורצה לומר שמשה זר לנגעים, שלזה צריכים אהרן ובניו.
** בכהניו -
דורש ש"כהניו" הולך על משה ועל אהרן. וא"ת אם כן צריך לומר "בכהניהם,” ש"בכהניו" הוא לשון הנאמר על יחיד. וי"ל שר"ל שכל אחד הוא בכיהון שלו. (אולי זה שייך למה שיש לדון אם קדושת כהונה של משה היה שווה לשל כהנים או היה מין אחר של קדושה. ותחשב. יש להעיר שיכול להיות שמה שלא ניתן לבניו אינו רק מפני שה’ לא רצה לתת אותו לבנים, אלא שאולי אף נתן לו הקב”ה קדושה ממין שונה שלא הולך לבנים. ותחשב.)
** בשעה שפוסקים גדולה -
קשה, שלמשה פסקו גדולה לו ולא לבניו. ותחשב.
** אם הגיס -
מענייין, שלכאו’ הבעיה בשאול אל היה שהגיס דעתו, אלא שהיה ענו יותר מן הראוי. ותחשב. נראה שכיון שאם מגיס דעתו ניטל מבניו, עונש של שאול היה מדה כנגד מדה, שאחרי שהוא עשה ביותר אותו דבר שישמור את המלכות לבניו, ניטלה המלכות מבניו. ותחשב.
** ד"ה לדורות - לאחר זמן -
גם יש לפרש שמצדד שפסול לא כתוב לומר שרק זרעו לויים, אלא שגם זרעו לויים, שהו"א שכיון שהיה עומד להיות כהן, ואבד את זה, אולי גם אבד את לויות שלו (עכ"פ מבניו). לכן, צריך לחדש שבניו לויים.
** ד"ה לא תיפוך - חס -
זה מעניין, שגמ’ אומר לימוד (שיהיה כעין טמא), ורש"י מוסיף לזה סברה (שענין טמא ובעל מום עובר הוא שלאחר זמן יקבל קדשים). יש לדון אם קמ"ל שמה שבעל מום מקבל אינו מפני שחס עליו תורה או שאף בעל מום עובר נכלל בלא פלוג או שגם עליו חס, כיון שבדר"כ יהיה נדחה לזמן גדול. ותחשב.
* קב:
** לאונסו שאני -
יש לדון אם רצה לומר שהיה נאנס להשיב (וכנראה מה שאדם שואל לו בתוקף נחשב אונס) או שנאנס לחשוב עליו, וכיון שחושב עליו, אין איסור עוד בדיבור (אף שמוסיף דיבור, ועוד שגם מוסיף קושיות, שעליהם אולי לא חשב).
** אמר… דנתה -
מרש"י בסוף העמוד יוצא שאמר כל זה כשהיה בבית הכסא, ולא שאמר בביה"מ שסיפור כזה קרה בבית הכסא. ותחשב.
* קה.
** בשאלת רבי אלעזר –
אין סוגיה זו כל כך מובנת לי. ראיתי בחברותא שמפרשים שעיקר הנידון הוא אם תלוי ביציאת האדם או ביציאת הפרה. הנפקא מינא שהוא שואל הוא אם הפרה נכנס אח"כ לחוץ, שאז יכול להיות שיש מתעסקים עמה בפנים, אף שהוא כבר יצא בחוץ. גמ' מוכיח ממה שעומדים בפנים לא נטמאו, וצריך לומר שתלוי ביציאת האדם, ולא ביציאת הפרה. דוחה שבאמת מוכרח שתלוי באדם מפסוק, שמשמע שאחרי שנטמא, צריך ליכנס. נמצא שתלוי במה שהוא יצא. אלא, מפרש ששאלתו הוא אם כבר יצא, אבל לא יצא עמו, אלא יצא לפניו, ועסק עמו מבחוץ.
* קז.
** העלאה –
בביאור רע של העלאה בחוץ (וכן יש לדון בשאר עבודות בחוץ), יש לחקור אם המעשה עצמו הרע או שהרע הוא במה שמבטל הקרבת הקרבן על ידי הקרבתו בחוץ (זה יכול להרבות רע של ביטול קרבן או רע של הקרבתו בחוץ). ותחשב.
** לערב –
נראה שהוא מפני הוי"ו, שסובר שוי"ו מערב את שני הענינים.
** דם יחשב –
יש לדון מהו הדרשה:
אפשר שהוא שכיון שמזכיר עוד חיוב כרת, צריך לומר שבא להוסיף שיש עוד חיוב כרת, ולרבות דבר. מסתבר שמרבה זריקה.
אפשר שהוא שכיון שאמר "דם" במילים מיותרים אלו, מסתבר שמרבה עבודת דם. זריקה הוא הכי מסתבר (אולי מסתבר מדין ואולי מסתבר מלשון, שהוא עבודה העיקרית של הדם). ותחשב.
כמו כן יש לומר לחולק, שאפשר לפרש כראשון, וגם אפשר לפרש שמ"דם" מרבה כל שהוא מין דמים, ואף עופות. ותחשב.
** שלם –
יש לדון אם זה דין בחפץ הקרבן או במעשה ההקרבה. ותחשב.
* קז:
** מחוץ למחנה –
ישג לדון למה סובר גמ' שזה משמע מחוץ לשלש מחנות. אולי סובר שתופסים מועט, שזה עושה שבפחות ציורים הוא חייב. ויש לדון, שנתפוס מועט לעשות שמחנה ר"ל רק מחנה אחת. גם יש לומר שהוא מפני שבדר"כ חוץ למחנות (כמו בשריפת קרבנות) ר"ל חוץ משלש מחנות.
* קט:
** צריך לעיין
בשיטת רבי אליעזר. הרי, רבי אליעזר אומר שלא חייב אם הקריב פחות מקמיצה, אף שהקריב כזית. אז, כנראה לא מקיים דבר בהבאת כזית. אבל, אם כבר הביא את השאר, חייב על הבאת הכזית. לכאו', זה מפני שקיים דבר, כיון שבזה משלים את ההקרבה. אז, אילו הוקרב בפנים, היה מקיים דבר. וא"ת אם כן למה צריך להיות כזית. ויש לומר שאם הוא חסר מזה, אינו מעשה הקרבה. אז, הבעיה הוא במעשה, ולא בחפץ. גם יכול להיות בחפץ, והוא שהוא חפץ שלא חשוב. על כל פנים, לכאו', הענין יהיה שאין זה משלים אותו, שאף שאחרי זה נמצא שהכל הוקרב, לא הכל הוקרב בטוב, שזה הוקרב כשיש פחות מכזית. נמצא שלרבי אליעזר יש שיעור שונה להקרבה (שהוא קומץ) משיש לעשות שהוא הקרבה חשובה עד כדי שיכול להתטרף עם הקרבות אחרות. ותחשב.
* קי.
** מיקלש –
גמרא מניח שכיון שרבנן מחייבים על חלק אחד, צריך לומר שהוא עושה דבר. אז, דן אם מה שהוא עושה הוא שמתיר חציו או שמקלש האיסור על כולו. (ודע שאם מתיר את מקצתו, צריך ביאור איזה מקצת יתיר. זה אחד מן המקומות שחלות יחול על דבר, ואין סיבה פשוטה לברר על איזה דבר יחול החלות. כמו כן יהיה בשני בכורים שנולדו, אם נצדד שאפשר לצמצם ושלא יכולים שניהם להיות קדושים (שכן יוצא לצד אחד בבכורות, במקצת ציורים). ותחשב.)
* קי:
** מי החג –
כנראה, "מי החג" משמע לגמרא שהוא אפילו לוג. צריך ביאור למה. נראה לבאר שלא משמע כלום – לא משמע לוג ולא משמע שלש לוגים. אם שיטת ר"א תלוייה בשיטתו שהוא שלשת לוגים, היה לו לפרש "שלשים לוגים," ולא רק לומר "מי החג." ותחשב.
** אישתמיטתיה –
עיין בפירוש רש"י. נמצא שרבי יוחנן מביא מאחד שאמר דבר שלא הכיר מה שאמר רבי יוחנן. זה מוזר, שהיה לו לרבי יוחנן לעורר שזה הולך נגד מאמר שלו. גם מוזר לומר שאישתמיטתיה מה שאמר רבי יוחנן, כיון שרבי יוחנן היה תלמיד שלו.
לולי רש"י, הייתי אומר שאומר כן על המקשה, שאומר שלא היה מקשה אילו ידע מש"א רבי יוחנן, שנלמד מהל"מ. נמצא, אז, שכו"ע מודים ללימוד, ורק חולקים אם כולו נלמד משם, או שזה רק מלמד פרטי דינים. (כיון שמלמד פרטי דינים, יש לדון למה אין כולו נלמד משם, כמו שמקשה גמ' בתחילת מועד קטן.) אבל, עיין בגמ' בתחילת תענית, שלא מקשה שדינים נלמדים משם לרבי עקיבא, אלא רק כולו נלמד משם או לא כלום נלמד. ותחשב.
* קיא.
** לדבריו –
בכל כעין זה, צריך ביאור מה באמת סובר. אם סובר כמו שמקשה, קשה למה אומר גמרא שסובר ששיריים מעכבים, שאין לזה שום הוכחה. ואם לא סובר כמו שמקשה, קשה למה מקשה אותו. ותחשב.
* קיב.
** ד"ה גתה – מקום עמוק –
איני מבין למה מזכיר כאן מקום עמוק. כמו שנראה לקמן, לשיטה אחת, זה כולל הרבה מקומות שבא"י. ותחשב.
* קיג:
** נהי דאיפני –
וא"ת אם רק נפנו מירושלים, אין כל א"י בדוקה אף לרבי יוחנן, שיש מתי נבוכדנצר. ויש לומר שחולקים במקדש ראשון. גם יש לומר שהם נפנו מכל א"י, ורק מתי מבול רק נפנו מירושלים. גי"ל שאלו היו מתחילה רק בירושלים (וצריך לומר שלא נפנו מחוץ לירושלים, אלא נקברו), ואז שאר א"י טהור. ותחשב.
** משום הבלא –
אז, יש לומר שהוו, כמו מתי נבוכדנצר.
** משום הבלא –
היה אפשר לתרץ שלא היו גרים בא"י. אבל, כנראה יודע שהיו  גרים שם, או סובר שהיו רצים לשם. ויל"ד, שאולי מתו מיד. לא נראה שימותו מיד, שכיון שלא היו המים רותחים, מסתמא יהיו יכולים לשוט קצת.
* קטו.
** מחמת עצמו –
לכאו', החילוק בין מחוסר זמן מחמת עצמו למחוסר זמן מחמת בעלים הוא שהקרבן עצמו הוא יותר חשוב לענין הקרבתו, ואז, פסול בו יהיה פסול יותר חשוב. ותחשב.
* קטו:
** ידועי –
אולי הוא מלשון אהוב, כמו שלשון ידיעה הוא לשון ביאה. גם אפשר על פי זה לבאר מה שאומר ברחב, "ביודעה ומכירה." ותחשב. (תוס' שם באר שר"ל שבא עליה, מלשון ביאה. אבל, כיון שאמרנו שהוא לשון אהבה, לא צריך לומר כן.)
** גמר עבודה –
קשה למה לא לומדים משחיטה נגד זה. יש שני דרכים לבאר את זה – אולי שחיטה נחשבת גמר עבודה (ונאמר שעבודתו רק שחיטה) או נאמר שלאיזה סיבה בוחרים ללמוד מזריקה ולא משחיטה (אולי מפני שהוא חמור).
** וכן בדוד –
לא אומר שכמו שאהרן עשה כן גם דוד עשה כן, אלא שכמו שאהרן עשה כן, כך דווד צווה כן.
* קטז.
** אין טריפה יולדת –
למסקנת גמרא, קשה מהי"ת למד"א זה שאין טריפה כשרה לקרבן, שאולי צווה ה' שלא יביא בהמות טרפות כיון שרצה בהמות שיולידו. צריך לומר שדורש ממה שאמר מיעוט (כמו "אתך") אחרי שכבר אמר שצריכים להיות ראויים להוליד. ממה שכפל אותו, צריך לומר שלשתי סיבות היה צריך להיות כן. ותחשב.
** מאיליהם –
יש לפרש את זה בשני אופנים.
אפשר לומר שגמ' הקשה למה קוראים להם טמאים וטהורים, שלא היו אז טמאים וטהורים. לזה, משיב שלא היו טמאים וטהורים, אלא נרבעים, והם כבר היו בכלל טמאים וטהורים (שכבר חלו עליהם דינים מפני טומאתם, והוא פסולם לקרבן). מפרש איך ידע איזה נרבע ואיזה לא נרבעו. אגב זה, הביא דרשה אחרת על איך באו לנוח.
אפשר לומר שגמ' הקשה איך ידע נוח איזה היו הטמאים והטהורים, שלא היה זה דין קבוע בימיו. תי' שהיה תלוי באיזה נרבעים, וזה היה דבר שכבר נהג בימיו, והיה יכול לדעת את זה. הק' גמ' שאף שזה היה דין דין שידע, שהיה כבר נוהג, לא יידע מי הוא נרבע, ועדיין קשה איך ידע. אמר שתיבה קלט אותו. שוב אומר שיכול להיות טהורים וטמאים ממש, ושתיבה קלט אותו.
לא נראה כצד שני, שכיון שבין כך ובין כך צריך לומר שתיבה קלט אותו, נמצא שמה שביניהם הוא רק פירוש מילת טמאים וטהורים. לא משמע כלל מגמ' שככה אומר. אלא, נראה שצריך לומר כצד ראשון. ותחשב על זה, שכתבנו אותה בצורה שהיא קל להבין, עד שנשמע פשוט ביותר.
** גנוזה –
עיין במה שפרש"י כאן. עיין בגמ' חגיגה, שמסביר אלף דור באופן אחר, ואז נמצא שלא היתה התורה גנוזה.
בכלל, צריך ביאור מה ר"ל שהיו דורות קודם בריאת העולם.
* קטז:
** יהא מחול –
נמצא שאסור לגויה להיות זונה. אפשר לדחות שהיתה אשת איש, ולכן היה רע. עיין ברש"י, שקרא לאותם שבאו לה מנאפים.
** בני ישראל מצווים –
צריך ביאור למה צריך פסוק למעט גויים מאזהרה זו, שמהיכי תיתי לרבות אותם.  אפשר לומר שכיון שהם בכלל הקרבת קרבנות, הו"א שהם גם בכלל מצווה זו. דחוק. גם יש לומר שהחידוש הוא שבזה יוצאים ידי קרבן שלהם (ולא רק שאין בזה איסור הקרבה בחוץ).
* קיז.
** קלט –
יש לדון למה לא קלט. אפשר שהוא מפני שכבר היו ערי מקלט. צריך לומר שעד אז לא הוקמו כבר. גם צריך לומר שלא רק בשילה לא קלט, אלא שמכאן ואילך לא קלט.
