** יש ברירה אין ברירה
חולקים תנאים אם
או
.
** ציור פשוט של ברירה
הוא כשאדם עושה חלות, וכשמפרש את החפץ שעליו יחול החלות, מפרש אותו בקרק’ שאינו שם כבר, אלא יבוא לאחר זמן. למשל, אדם כותב גט לשם אשתו, אבל לא מפרש לאיזה אשה נכ’, אלא ע"י קרק’ שלא כבר בא. אז, נמצא שכ’ לאחד מהם, אבל אותו אחד לא נתפרש בשום קרק’ שיש עכשיו.
** הפשט הפשוט בברירה
לכאורה,
הוא שכדי לעשות שחלות חל על חפץ, צריך אדם לפרש אותו חפץ. חולקים אם פירוש של קרק’ שיבואו הוא פירוש טוב או לא.
** שיטת רש"י
יש לדון מהו
בדיון זה:
1. בעירובין (לו:), גמרא דן אם רבי יהודה סובר שיש ברירה או שאין ברירה. נוגע הוא לענין ציור שאדם נותן שני עירובין, ומתנה שיחול על איזה שירצה לאחר זמן. רש"י כ’ בביאור צד אין ברירה: "דכי בריר למחר אמרינן שמא אתמול כי קנה עירוב לאו דעתיה אהך הוה אלא אאידך.” לכאורה, זה אומר שהצד שאין ברירה הוא שחוששים שאף שאמר "איזה שארצה,” כבר רצה באחד בשעת קניית עירוב.[fn:1] אז, עירובו לא חל על מה שנתברר, שהרי לא נתלה, למעשה, בברירתו.
2. נראה שיש שני דרכים לבאר מה אומר רש"י, כשאומר שחוששים שמא רצה באחד:
  1. אולי חוששים שחשב שאחד הוא מה שירצה (וממילא רצה בו). אז, לו מילים "איזה שארצה" ר"ל אותו אחד, שזהו מה שקובע בדעתו להיות מה שרוצה.
  2. אולי חוששים שרצה באחד. אף שהתנה, לא רצה מה שהתנה, אולי, אלא רצה מה שאמר.
3. לשון רש"י, כמובן, אפשר לומר לשני הצדדים, שאומר, "לא דעתו אהך אלא אאידך.” צריך לבאר מהו "דעתו עליו,” אם זה רצון או מחשבתו למה יקרה.
4. יש לדחות שמה שאומר רש"י רק שלא יכולים להניח שחשב על הדבר הנכון. זה אומר שאולי אין ברירה כיון שלא אמר החלות על פי קרק’ של עכשיו. עדיין, היה חל על פי רצונו או מחשבתו. רש"י מפרש שלא יכולים להניח שכיוון לדבר הנכון.
5. אם נאמר כן, אז כדי שיוכל רש"י לומר שמפני זה אין ברירה, ולא שמפני זה אין סיבה אחרת שהחלות חל, צריך לומר שמי שאומר שיש ברירה סובר שמניחים שכיוון לדבר הנכון. זה אומר שלצד ראשון שכתבנו, יש רק ענין אחד, והוא מה שחשב על דבר אחר. זהו מה שעושה שלא חל, וזהו מה שעושה שחל על דבר אחר. אז, רש"י מפרש שיש אותו דבר אחר, ומסתמא מפרש שלכן לא חל. לצד זה, אינו כן, אלא יש שני דברים- יש סיבה שלא חל, ויש סיבה שחל על דבר אחר. רש"י מפרש מה שהוא הסיבה שחל על דבר אחר ולא על זה. צריך לומר שסובר שעל אותו סיבה קאי מחלקת אם יש ברירה או אין ברירה, שחולקים אם אותו מניחים שכיוון לדבר נכון.
6. יש לדון למה היה חל על פי מה שחשב. אפשר שהסיבה הוא מפני שחשבו (וזה מהני בפני עצמו), או שמניחים שכיוון לכך כשאמר דיבור שלו, שאין אדם מוציא דברים לבטלה, וידע שלא היה חל כיון שאין ברירה. כמו כן, יש לומר שיודעים שרוצה כן כיון שרוצה שייתלה על מה שיהיה. אז, בוודאי רוצה תלייה במה שחושב שיהיה, שחושב שזה סימן טוב למה שיקרה.
7. אז, מצאנו, לכאורה, שני מהלכים עיקריים לרש"י:
  1. לא חל דיבור שלו על מה שהוברר כיון שחזר וחשב דבר אחר. אותו דעת הוא המכריע. יש לדון אם אותו דעת הוא פירוש או רצון אחר.
8. לזה, מי שסובר שיש ברירה יכול לסבור:
    1. מניחים שחשב על דבר הנכון.
    2. מניחים שלא חשב, ואז מה שחל היה מה שהתנה  מתחילה.
    3. לא חוששים למה כיוון, שמה שאמר הוא העושה שהחלות חל.
  1. לא חל דיבור שלו כיון שמפרש על פי קרק’ שיבוא לאחר זמן. לא חל מחמת מחשבתו כיון שלא יודעים אם מחשבתו נכון.
9. לזה, יכול מי שסובר שיש ברירה לסבור:
    1. חל על דיבור שלו אף שלא פירש כל כך.
    2. לא חל על דיבור שלו, אבל מניחים שדעתו היה נכון. כן צריכים לומר מרש"י זה.
10. יש רש"י אחר שג"כ כ’ כמו"כ. גמרא בחולין (יד.) כ’ שלר"י אין ברירה, ולכן נצטרך לומר שסתם בהמה מוקצה. רש"י מפרש: "ואי בהמה בחייה לאו לאכילה לחודה קיימא כי שחיט לה ביום טוב היך מישתריא דלמא מאתמול דעתיה לגדל הוה.” לכאורה, אף כאן רש"י אומר שמה שעושה שאין ברירה הוא החשש שהיה דעתו מוטעה.
11. על פי שיטת רש"י זה, יכולים לבאר כמה דברים:
12. גמרא בעירובין (לז.) אומר שאם אין ברירה, לכאורה לא יכול שני נשים להביא שני קינים אם לא כבר יודעים איזה של איזה. רש"י מפרש שלא יוכלו כיון ש"איכא למימר חטאת ועולה שהקריב לה לא שלה היו אלא של חברתה.” לכאורה, אילו אמרנו כפשט הפשוט, לא היה לו להיות ספק, אלא בוודאי לא חל, כיון שלא בירר על איזה חפץ רצה שיחול החלות. גם לא היה לו לרש"י לומר שהצד שלא חל הוא שהם של חברתה, אלא שאינם של כל אחד (ששם שניהם קונים אחד בברירה).
13. גמרא בבבא קמא (סט:) מביא ברייתא בענין קונה יין מן הכותי. הוא אותו גמרא שמביא גמרא בגיטין, והוא מחלקת אם יכול אדם לקחת מכותי ולהפריש על ידי ברירה. בבבא קמא כ’ רש"י שאם אין ברירה, לא מהני, ש"לית להו ברירה לומר מן החולין הוא שותה ותרומה ומעשר נותרין בנוד.” לכאורה, אילו רש"י סובר שאם אין ברירה לא חל, היה לו לומר שאין ברירה לומר שמחולין הוא שותה. מה שאומר "ותרומה ומעשר נותרים" משמע שכשאין ברירה, הבעיה הוא שאין תרומה ומעשר בכד. אז, זה אומר שהאיסור הוא שאולי שותה תרומה ומעשר, שאולי מה שעשה לתרומה ומעשר הוא מה שעתיד לשתות. זה טוב לפי מה שפרשנו בדעת רש"י, שהרי רש"י אומר שאין ברירה כיון שאפשר שחשב על דבר אחר כשעושה חלות. אז, החשש הוא שחל החלות על אותו דבר אחר.
14. כמו כן נמצא מרש"י במעילה (כב.), שעל אותו ברייתא אומר, “… ועל כל כוס יש לומר שהוא תרומה ומעשר, ואפילו מראשון.”  לכאורה, רש"י אומר כמו שדייקנו, והוא שהחשש הוא שחל התרומה על חפץ אחר, ולא שלא חל כלל. זה טוב עם שיטת רש"י. כמו"כ כ’ רש"י בחולין (יד.).
15. גמרא בגיטין (כה.) מחלק בין ברירה כשתלה בדעת עצמו לברירה כשתלה בדעת אחרים. יותר מסתבר שלא יהיה ברירה אם תולה בדעת עצמו בכשתולה  בדעת אחרים. רש"י באר: “דילמא תולה בדעת עצמו לית לן ברירה דמדאתני ברישא גילה דעתו שהיה פוסח על שתי סיעיפים וליכא למימר הוברר דמעיקרא דעתיה להאי, אבל זה שתלה באחרים גמר בדעתיה מעיקרא לאיזה שתרצה.” צריך ביאור מה אומר.
16. על פי מה שהוכחנו בשיטת רש"י, נראה שיהיה קל לבאר גמרא. יש יותר צד לחוש שיחשוב מה יקרה אם בידו לברר מה יקרה. זה אומר שאם תולה במה שהוא יבחר, קל לו לדעת או לחשוב על זה, שהרי הוא עצמו, והוא יכול לחשוב על זה. אם תולה בדעת אחרים, יותר קשה לו לחשוב על זה, ואז יותר קל לומר שלא חשב ולא החליט מה יקרה. אז, יותר מסתבר שלא יהיה ברירה אם תולה בדעת עצמו מבתולה בדעת אחרים.
17. אפשר שכן אומר רש"י כאן. עדיין יש לדון בלשונו שאומר "שהיה פוסח על שני סעיפים.” איני יודע מה זה אומר, שבפשטות אומר שהיה לו שני צדדים, אבל בוודאי היו לו שני צדדים, ואף אם מתנה על דעת אחרים, שהיה מסופק- והוא גופא, זה סיבה שהיה לו לחול, שלא היה מברר. אפשר שרש"י אומר שגילה בדעתו שחשב לאחד מן השני צדדים, מה שאין כן אם לא תלה בדעתו, שאז לא חשב כאחד מן השני צדדים, אלא חשב תלייה על מה יקרה. נראה שלשון פוסח ר"ל שהיה מדלג[fn:2] מזה לזה, וחושב שצד זה נכון, ושוב שצד זה נכון. אם תולה בדעת אחרים, אינו כן, אלא לא פוסח כלל, אלא לא לעולם חושב לדעת איזה נכון, שלא יוכל לדעת. ותחשב. דחוק קצת עדיין בלשון רש"י.[fn:3]
18. לכאורה, זה אי אפשר לצד שני שכתבנו ברש"י, שאותו צד אומר שלרש"י, אין חלות חל אם לא מפרש די על איזה דבר קאי. הרי כאן לא פירש. אם כן, אף אם תולה בדעת אחרים, יחול. אלא, צריך לומר שיכול לחול אם תולה בדעת אחרים, אלא שחוששים שלא חשב כן. אם תולה בדעת אחרים, בוודאי חשב כן.[fn:4]
19. ויש לדון, שאולי אין הכי נמי, ובזה חולקים שני הצדדים שבגמרא.
20. משנה (גיטין כה:) אומר שלפי שיטה שיש ברירה, הקונה יין מן הכותים יש לו תקנה: “אומר שני לוגים שאני עתיד להפריש הרי הן תרומה עשרה מעשר ראשון תשעה מעשר שני ומיחל ושותה מיד.” רש"י מפרש (ויש חולקים על רש"י בזה; תוס’ כאן חולק, ופני משה שם באותו משנה חולק) שמיחל ר"ל שמחלל אותו. יכול אדם לחלל מעשר שני על כסף, וכן צריך לעשות לאותו מעשר שני שמפריש. רש"י מפרש למה עושה כן (שהרי, אם יש ברירה, יכול לסמוך על ברירה אף לזה), ואומר ש"מה שאפשר לתקן לגמרי יתקן.” לכאורה, קשה להבין מה אומר רש"י, שלא תקן שום דבר לגמרי, שאם אין ברירה, עדיין אוכל טבל, ואם יש ברירה, אין צורך לחלל אותו.
21. נראה שרש"י לשיטתו. רש"י סובר שהצד שאין ברירה סובר שחל החלות, אבל רק לא יודעים על מה חל. אז, אסור לשתותו- לא מפני איסור טבל, אלא מפני איסור תרומות ומעשרות. כן מסתבר שיסבור לשיטתו, וכן משמע שסובר בבבא קמא (סט:) ובמעילה (כב). אם כן, שפיר תקן לגמרי, שאז הוא דימוע (תערובת) של תרומה ושל מעשר ראשון, אבל לא של מעשר שני, שאף אם אין ברירה, בוודאי אין מעשר שני כאן, שבוודאי נעשה חלק ממנו מעשר שני, ובוודאי פדה אותו חלק, באיזה מקום שהוא. ותחשב.
22. גם יכולים לבאר על פי זה למה תנאי נחשב ברירה[fn:5]. אם בעיה של ברירה הוא שלא באר את הדבר שעליו עושה חלות, אז קשה למה שייך לתנאי. כמובן, יכול להיות עוד צדדים, אבל לרש"י קל לבאר אותו, שלרש"י הענין הוא שאם אין ברירה, כמו שגבי ברירה היה חשש שחושב על מה יקרה, ואז חשב על אחד, ועל אותו אחד חל, כך גבי תנאי יש חשש שחשב על אחד מהם, ואז אולי חשב שלא יחול, וממילא אין לדעת שיחול.
23. גם זה לא נראה לצד שני שכתבנו בביאור רש"י. אם מה שלא חל הוא מפני שלא פרש איזה חפץ רוצה שיחול עליו, שלא נתן קרק’ שהוא בעולם כבר, אז בתנאי, היה לו לחול, כיון שיודע על איזה אישה רוצה שיחול. אז, לכאורה, צריך לומר כצד ראשון. היה אפשר לומר שבזה חולקים שני הביאורים בגמרא, וכמו שאמרנו לעיל. מי שמחלק בין תולה בדעת אחרים לתולה בדעת עצמו סובר כצד ראשון, ולכן יכול להביא ראיה מזה, ולכן מחלק. החולק יאמר כצד שני, ולכן לא מביא ראיה מתנאי, ולכן לא מסתבר לו לחלק. יש לדון, שאז לא יוכל להביא ראיה, שהרי מביא ראיה נגד החולק, ואי אפשר לעשות כן בהנחתו שכבר נגד החולק.
24. אגב, נבאר מה שאומר רש"י גבי תנאי. רש"י מחלק בין תנאי שבו תולה בדעתו לתנאי שתולה דבדעת אחרים. נראה שהכוונה הוא כך: אם אדם עושה חלות עם תנאי, רש"י מניח שמסתבר שרוצה בחלות, שאילו לא רצה בו, לא היה עושה חלות עם תנאי. מה שעשה תנאי הוא רק מפני שרצה שיהיה תלוי בדבר (מסתמא רצה בהפצעה קצת או כדומה), אבל בעיקר רצה חלות[fn:6]. זה רק אפשר אם עשה החלות תלוי במה שבידו, שאז, יכולים לומר שכיון שרוצה אותו, מניח שיעשה אותו מעשה. אבל, אם התנאי לא תלוי במה שהוא בידו, מוכרחים לומר שלא יודע אם יחול, שלא יידע אדם אם יקרה אותו דבר שעליו תלה תנאי. אם כן, אין להוכיח שרוצה, וממילא לא חל.[fn:7][fn:8]
25. אבל בברירה אינו כן, שאין להוכיח כאיזה צד רוצה, שלא יודעים מה יקרה. אז, לא יש עדיין חשש לפי הצד שאין ברירה.
26. זה גם מבאר גמרא בזבחים (ג.). גמרא שם מקשה כך: בקרבן, הדין הוא שצריך מחשבה לשמה. אם מקריב סתם, ולא מכוון לאיזה קרבן מקריב, כשר כאילו כוון לשמה. בגט, אינו כן, אלא אם כותב סתם, לא כשר. מקשה גמרא מהו החילוק. גמרא דן מהיכי תיתי שהדינים הם כך. מנסה למצוא מקור שאין כתיבה סתם מהני גבי גט. מביא ראיה ממשנה כאן, שאומר שאם כותב גט לאיזה אשה שתצא ראשון, לא מהני. אז, מצאנו שאף בלי דעת לאשה שאינה נכונה, לא מהני, כיון שלא כיוון לאשה זה. דוחה גמרא ש"שאני התם שאין ברירה.” לכאורה, דיחוי זה צריך ביאור. מה שאין ברירה הוא רק הסיבה שהוא סתם, ואינו נחשב ציור שכיוון. אבל, כיון שאין ברירה, לכאורה, אין דעת. אז, הוא נשאר כסתם.
27. רש"י שם מפרש על פי שיטתו כאן. רש"י מפרש שאין ברירה לא אומר שאין בירור על איזה חפץ עושה החלות, ואז הוא כסתם, אלא הוא מברר על אחד מהם, אבל אולי אינו נכון. אם כן, דיחוי גמרא מסתבר, והוא שכאן אינו סתם, אלא חשש אולי כיוון לאשה שאינה נכונה.
28. ואם תאמר יש אותו חשש בסתם. ויש לדון, שכיון שלא הזכיר כלום, לא מניחים שחושב כלום. אז, אין זה נכון בסתם. ותחשב. לצד שני, ק"ק, שכיון שהבעיה הוא שחושב על דבר, אז זהו מה שמחדש צד שאין ברירה, אם נאמר שחולקים אם חושב על חד דבר או לא. זה אי אפשר לצד שני, שצריך לומר שלא חולקים בזה. עדיין יש לדון, שאולי עיקר הת’ הוא ששאני התם שהוא ציור ברירה, והרי אין ברירה. ותחשב על זה.
29. נראה שיש דרך לדחות זה. אפשר לומר שמה שהיה סתם מהני הוא שהיה אותו דבר שמחשבה צריך להיעשות מעצמו. גבי גט, למשל, צריך יחס מיוחד בין אשה לגט, שהגט הוא לה. אולי יחס זה נעשה ממילא, מפני שהיא תתגרש בו. אולי מה שמכוון להיות סתם עושה שאינו מיוחס לה. אז, אולי, אם כוון יהיה יותר רע, שאז כבר נתן על הגט שם של סתם, שהוא גט לנשים הרבה. ותחשב.[fn:9]
אף שזה מבאר כמה דברים, יש קושיות על זה:
1. לכאורה, הקושיה הכי פשוטה הוא שאם חל, אלא שלא יודעים על מה חל, יהיה לו דין ספק. יש כמה ראיות מגמרות שאין בו דין ספק:
  1. אם כן, אף שאין ברירה, תאסר אשה לכהן אם מגורשת בגט שסומך על ברירה. גמרא אומר בפירוש שאם אין ברירה (שאף לא מחמירים לומר שיש ברירה), לא נאסרה. [fn:10]
  2. הדין הוא שהדרך שמת ייצא מן הבית טמא, אף קודם שבא מת לשם. אז, גמרא אומר שאם יש כמה דרכים לצאת, כולם טמאים. אם בחר אחד מהם, כולם נטהרים. גמרא מבאר שאם יש ברירה נטהרים למפרע, ואם לא, נטהרים מכאן ולהבא. קשה ל"ל תולה אותו באם הוא ברשות היחיד או ברשות הרבים, שהדין הוא שספק טומאה טמא רק ברשות היחיד[fn:11]. משמע שלעולם טמא.[fn:12]
  3. חולקים בגמרא ביצה (לז:) אם יש ברירה בדין דרבנן להקל או אין ברירה. קשה איך לא יהיה ברירה, שהרי אין ברירה אומר שהוא ספק על מה חל החלות. אז, כיון שהוא ספק דרבנן, נקל.[fn:13]
  4. מה שאומר גמרא בכל זמן הדין גבי צד שאין ברירה שלא חל (למשל, אינו עירוב), ולא מזכיר הספק משמע שאינו ספק, אלא בוודאי הדין כן.
2. כמו כן, קשה קצת יותר, שאינו ספק השקול. לכאורה, יש יותר משני צדדים, שיש גם צד שממש תלה אותו במה שאמר, ואז יחול על מה שהוברר. אז, לכאורה, הוא רק מיעוט לומר שלא חל כמו שאמר. אם כן, אם אין ברירה, יהיה הדין שווה לדין של יש ברירה. אולי צריך לומר שאין לנו צד שמניח את דעתו בספק, ולא חושב על איזה יקרה. ותחשב. יש להעיר שאין זה קשה אם נאמר כצד שני בביאור רש"י. ותחשב.
3. כמו כן, היה קשה אם יש יותר משני יכולות, שאז יהיה רוב שאומר לנו שלא חל כך. יש לדון, שאולי אין הכי נמי, שם יקל. יש להעיר שגמ’ בביצה (י.) משמע שיש יותר משני יכולות. אולי טומאה שאני.
4. היה אפשר לתרץ לשנים אלו שאולי חלות שאי אפשר להוודע, שמי יודע מה חשב (ואולי אף הוא לא ידע מה חשב), לא חל, ורק די לעשות שאין דעתו בשעת חלות מה שצריך להיות כדי שיחול עם ברירה.
5. הבעיה בזה הוא שרש"י משמע שהחלות חל, ורק לא יודעים על מה חל. כן משמע מרש"י שהבאנו בעירובין, וכן מוכרח מרש"י שהבאנו מבבא קמא ומעילה. אם כן, אין לתרץ כן. אז, קשה.
6. קשה, לכאורה, מהו הבעיה אם חשב על אחר. לכאורה, מחשבתו על אחר הוא דברים שבלב. אז, לא יחול, כיון שדברים שבלב אינם דברים. נראה כמה תירוצים:
7. אם נאמר כצד ראשון שכתבנו ברש"י, אז, הקשה הוא למה הולכים עם מה שחשב נגד מה שאמר. אז, יש לומר:
8. אם מה שאומר רש"י הוא שחוששים שמא חשב כבר על מה שירצה, יש לומר:
  1. יש לומר שאינו דברים שבלב, שהרי הוא אמר מה כוון, אלא שאמר אותו במילים שבדרך כלל לא אומרים כן. עיין בגמרא נדרים (כה.) שמצדד שיכול אדם לתת שם לדבר. אז, למשל, שם אומר שהיה אפשרות (בלי מה שהדיר ה’ את בנ"י על דעתו) שכשנשבעו בנ"י לקיים כל המצוות, לא היה חל על כל המצוות, אלא היו יכולים לקרוא שום דבר אחד שרצו בשם "מצוות" ולהיות נדור עליה. אם כן, אף יכולים לומר כאן, שכיון שבדעתו "מה שארצה" הוא אחד מיוחד, ואז הוציא בדיבורו שיהיה ערוב כאן.
9. עדיין קשה, שגמרא שם רק אומר כן בתוך קושיה, ואין זה מסקנת הגמרא. אם כן, לכאורה, אי אפשר לאדם לפרש דבר בתוך דעתו. אולי צריך לומר שזה רק שם כיון שהוא דרך מוזר לפרש אותו. כאן, אינו מוזר לפרש אותו כן, שנמצא בכמה פעמים שאדם יקראו דבר על פי מה שיחשבו שיקרו להם.
10. גם יש להוסיף שלא רק זה קרק’ טוב לקרוא דבר על פיהו (מה חושב שיקרה לו), אלא שלכאורה, מה שמניח שקורה הוא דרב מסתבר להניח. אז, נמצא שיש שמה שעשוה לתת שם (עושה ששמו הוא מה שחושב) מסתבר, ומה שעושה מה שחושב הוא גם כן מסתבר. ותחשב.
11. עיין שם, שגמרא מבאר שהיו רבנן יכולים, אף למסקנא, לקרוא ציצית בשם כל התורה כולה, כיון שהוא כנגד כל התורה כולה. אולי זה כמו שכתבנו, שכיון שדבר מסתבר, אפשר לפרש מילה.
12. רק יכולים לומר כן אם נאמר שהחשש הוא שכבר חשב על מה ירצה, שרק אז נוכל לומר שמחשבתו הוא פירוש של דיבור שלו. אבל, אם החשש הוא שכבר רצה דבר אחר, אי אפשר לומר שמחשבתו מפרש דיבור שלו, שלא חושב על פירוש דיבורו.
  1. יש לדון למה אין דברים שבלב דברים. אפשר לומר שני צדדים עיקרים:
    1. דברים שבלב דברים, אלא שלא מאמינים שכך כוון, אלא מסתמא כוון כדיבור שלו.
    2. דברים שבלב אינם דברים. כדי לעשות חלות, צריך דיבור.
13. אם נאמר כצד ראשון, נראה שיכולים לומר שרק אומרים כן כשאין להניח שאמר כן. כאן, אינו כן, שמסתבר שהניח שהניח שאחד מן המקומות יהיה המקום שיבוא שם. אז, אין כלל של אין דברים שבלב דברים עושה שלא נחוש שכוון לאחד מן המקומות להיות "מקום שירצה.”
14. זה רק מהני אם נאמר שהחשש הוא שכבר חשב איזה מקום ירצה, שאז נוכל לומר שנאמן לומר שכבר החליט איזה מקום ירצה, שמסתבר לומר שחשב כן. לכאורה, לא מסתבר ששינה דעתו לרצות מקום מסויים, ולא מקום שירצה. אז, אי אפשר לומר כן אם החשש הוא שבשעת קניית עירוב רצה מקום אחד.
15. היה אפשר לומר כן, אבל נראה לי שאין זה הפשט בדברים שבלב אינם דברים. נראה לי שני הוכחות  נגד זה:
    1. תוס’ (קידושין מט:) כ’ שדברים שבלב הם דברים אם יש אומדנא שכן חושב, עד שהוא כאנן סהדי. לפי צד זה, קשה ל"ל מספקים קודם לכן. אפשר לדחות שמספקים, אלא שנותן לקונה כיון שהוא המוחזק. יש להעיר כמה הערות על זה:
      1. לא כל כך פשוט שיהיה לעולם הקונה מוחזק עליו. לכאורה, תלוי במחלקת רבא ורב נחמן בבבא בתרא (ל.), שרב נחמן סבר שלוקח מוחזק ורבא סובר שמוכר מוחזק. אפשר לומר שסובר כרב נחמן (שהלכה כמותו), או שתוס’ אומר כן על מטלטלים (ששם כולי עלמא מודו שהוא בחזקת לוקח). גם קל לומר שרק תוס’ לא סובר כצד זה.
      2. עדיין, אף בכל זה, יהיה מחודש לומר שסומכוס יאמר על כל דברים שבלב של ספק שחולקים, ושרב יאמר על כל דברים של רוב שהולכים בתר רוב. לכאורה, לא מצאנו זה בש"ס; וגמרא מקשה על כעין זה (בכמה מקומות; למשל, בהערל) שלא מסתבר שאין שום משנה או ברייתא שיגלה חידוש זה.
    2. גמרא קידושין (נ.) מבאר מקור לדין שאין דברים שבלב דברים. נלמד ממשנה בענין מעילה. הדין הוא שאם אדם מועל בשוגג חייב קרבן, ואם מועל במזיד פטור מקרבן אבל חייב מלקות או מיתה (מחלקת רבנן ורבי הוא). אדם עובר על מעילה אף אם עושה אותו על ידי שליח; אף שבדרך כלל, אין שליח לדבר עבירה, במעילה, יש שליח לדבר עבירה, שנדרש מתרומה בתחילת פרק שני של קידושין (). משנה אומר שאם אמר אדם לשליח בשוגג למעול, ומעל שליח, ושוב אמר המשלח שלא כוון שימעל באותו חפץ, אלא בחפץ אחר, חייב המשלח. רואים מכאן שאין דברים שבלב דברים. ראשון, לכאורה, זה על כל פנים, ציור של ספק. קשה איך נחייב אדם להביא קרבן, כיון שטוען שאינו חייב, והוא ספק, ששמא מביא חולין לעזרה. זה רק אומר שאז קושיה ראשונה נתחזק. גם קשה לל"א שנאמן במגו, שהיה יכול לומר, “נזכרתי.” גמרא בעצמו אומר שהיה יכול לומר נזכרתי, יכולים להביא ראיה שאין דברים שבלב דברים, ולא דוחים ששם חוששים שמשקר כדי לפטור את עצמו. אולי צריכים לדחות שמיירי במצב שאין מגו. תוס’, למשל, סובר שאין מגו למפרע. זה אומר שכל מגו יש בו הודאה על טענה שהיה נאמן, וטענה שלא יהיה נאמן בלתי מגו. אם אמר טענתו אחר שכבר הודה, לא נאמן. אם כן, אולי כן קרה בציור של המשנה. גם חולקים ראשונים ואחרונים אם יש מגו חוץ מבית דין. אולי כאן הודה חוץ מבית דין, ואז אין מגו לו.
16. על כל פנים, נראה לי שהוא דחוק לומר צד זה. שוב ראיתי שלמעשה אמר חכם צבי צד זה, ואז יש לו על מה לסמוך.
  1. נראה שיש לדון למה אומדנא מוכיח מהני לעשות שדברים שבלב הם דברים. אפשר שהוא מעלה בדעת, והוא שדעת שידוע הוא יותר חזק ויותר ראוי לעשות חלות. גם אפשר שהוא חלישות בדיבור, שדיבור שהוא פשוט להיות שאינו נכון אינו חזק.
17. נראה שכאן, אפשר שהדיבור נגד אומדנא. זה אומר שאפשר שיש אומדנא שכוון למקום אחד, שאין אדם אומר תנאי ולא חושב ומניח מה יחול. אז, צריך לומר שהניח מקום. נמצא, אז, שאין אותו דעת חשוב, שאין אומדנא שחשב לו, שאולי חשב על מקום אחר, אבל אין הדיבור חשוב, שיש אומדנא שאינו נכון. אם כן, אפשר שכאן דברים שבלב הם דברים.
18. לצד זה, מוכרח לומר שחוששים שמא כבר חשב איזה שירצה, שלכאורה, לא מסתבר לומר שבוודאי ישנה את דעתו לרצות דבר אחר. אם כן, צריך לומר שמניחים שיחשוב על מה שירצה, ומניחים שזה נגד דיבור. אם כן, אף מחשבה לרצות דבר אחר אולי יחול, אבל אין צורך לחוש לו, שכבר יש לחוש לפירוש של מה שירצה.
19. אם חוששים שלא רצה בו, אלא רצה באחר, יכולים לומר:
  1. אפשר שמה שאינו דברים שבלב הוא מפני שאינו נגד דברים חזקים. זה אומר שאולי דברים שבלב אינים דברים מפני שיש דבר שסותר לזה שדיבר. אפשר שכאן לא סותר כל כך דבריו, כיון שדבריו הם קרק’ שלא מפרש החפץ כל כך, שהרי אינו כאן עדיין.
  2. אפשר שאין דברים שבלב רק כשהוא נגד דיבור. זה אומר שדיבור הוא סיבה יותר חזקה להאמין או לעשות חלות מדעת. ערוב חל בין השמשות. לכאורה, אין אדם מדבר ומתנה בין השמשות, אלא מתנה קודם לכן, ואז חל בין השמשות. אם כן, יש לו דעת של שעת החלות, נחוש, שהוא נגד דיבורו שלפני כן. אולי דברים שבלב הוה דברים אז, שלא סוברים הדיבור בפירוש. זה יותר קל לבאר על הצד שרק לא מאמינים אותו. אז, יש לומר שזה רק אם אמר דבר שהוא נגד אותו סברה. כאן, לא אמר כן כשחשב כן, אלא שחוששים שכשאמר כן, חשב כן, אלא שחזר בו. ותחשב.
20. צד זה לא נראה, שהוא נכון רק גבי עירוב. יש חלותים אחרים (כמו הפרשת תרומה) שחלים בשעת דיבור, ואף בהם יש שיטה שאומר שאין ברירה. אז, נראה שאי אפשר לומר צד זה. יותר מזה, כיון שגמרא מוכיח מהו שיטת רבי יוחנן מדין של עירוב, ולא מחלק כך, צריך לומר שאין זה חילוק. אולי צריך לומר שכיון שהיה אותו דיבור, מה שהיה לפני זמן לא מכחיש אותו. ותחשב.
21. אם כן, אפשר שכאן חוששים שרצה מקום אחד, ולא רק שחשב שירצה מקום אחד, שהרי שנים אלו אומרים שאין כאן דברים, ואז דברים שבלב הם דברים.
22. אם נאמר כצד שני שברש"י, אז הבעיה הוא למה מה שחשב מהני. יש לדון למה חל. יש לומר ככל הצדדים שבארנו, ויש לומר גם פשט אחר פשוט, והוא שלא אומרים שאין דברים שבלב דברים אלא אם כן יש דברים נגדו, אבל כאן, אין דברים נגדו, שלא אמר שום דברים על החלות. ותחשב.
23. - גמרא עירובין (לו.) מזכיר ציור שאדם לא יודע לאיזה צד יבוא רבו, אם למזרח אם למערב. גמרא מפרש שזה נחשב ברירה. רש"י מפרש שהוא ברירה כיון שהוא תלוי בדעת חכם[fn:14][fn:15], וחכם לא יודע עוד לאיזה דרך יבוא. קשה, שלכאורה, היה לו לרש"י לומר שלא יודעים מה חושב המתנה (לאיזה צד יבוא רבו). צריך ביאור למה תלוי במה שחושב רבו. אם הענין הוא מה שרוצה, אז פשוט, לכאורה, לומר שזה בעיה, שמה לנו במה שחושב רבו. אם לא, אולי יש לתרץ:
24. אפשר שכמו שיש לו ביאור על מילים שאמר, כך יש לרבו. כיון שהמילים נאמרו על רבו, ביאור שלו לאותם מילים חשוב. ויש לדון, שלא היה נראה כן, אלא היה נראה שהביאור שאמר הוא עצמו היה חשוב יותר מביאור שאומר רבו.
25. אפשר שמה שתלוי במה שחושב הוא מפני שיודעים שלא יכולים לתלות על קרק’ שיהיה. אז, תולים על דבר שהוא דומה לו, ושבדרך כלל יהיה שווה לו, והוא מה שהוא חושב שיקרה.[fn:16]
26. מה שנוקטים זה הוא אולי מפני שגילה דעת לזה, שהרי רוצה בחלות שתלוי על קרק’ שיבוא, וחלות שתלוי על זה דומה, או מפני שמניחים שכן חושב, שפשוט שלא חשב לתלות על קרק’ שיבוא, שאי אפשר לתלות עליו. ותחשב.
גם קשה עוד על רש"י בביאור ברירה. גמרא שם (לו) מבאר שאם כבר בא חכם, אף אם אין ברירה, חל. קשה, שנחוש עוד שהוא חושב באיזה דרך בא חכם. לצד שני, פשוט לומר שכיון שיכול לחול כביאור פשוט שלו, חל כן, שמה שמפרשים דיבור שלו הוא רק במקום שלא יחול לחול כפשטותו. לצד ראשון, אי אפשר לומר כן, שבארנו שהיה חל אילו לא חשב לדבר אחר.
1. אפשר שהבעיה הוא שאז לא נוכל לומר כמש"כ שדברים שבלב כאן יהיו דברים. לצד ראשון, זה יהיה מפני שכבר יש פירוש אחר למה שאמר, ופירוש זה טוב. ר"ל, יש פירוש שהוא מפרש מה שקורה עכשיו, ואז מפרשים אותו כן, אף שהוא בעצמו לא חושב כן. לצד רביעי, יכולים לומר שרק מהני כיון שלא סותר דיבור חזק. הרי זה דיבור חזק, והוא סותר אותו. על כל פנים, לפשט זה ייצא שמה שמפרש על פי קרק’ של לאחר זמן מכחיש את דיבור שלו.
2. אפשר שהיה חל כמו שאמר, אלא שהוא טעות, שאילו ידע האמת, לא היה מפרש כן. (זה צריך להניח שענין טעות הוא רק על מה שקורה כבר עכשיו.) אז, לא חל החלות כמו שחושב. עדיין מעניין שחל כמו שאמר, כיון שלא כיוון כן, אלא פרש באופן אחר. מרש"י לא נראה כצד זה.
- עיין לעיל שדיננו מה סובר הצד שיש ברירה. יש לציין לכמה לשונות ברש"י בזה:
1. גמרא גיטין (כה.) מבאר ציור שאדם מתנה לשחוט קרבן פסח על מי שיבוא ראשון לירושלים. גמרא מבאר שאם יש ברירה, מהני. רש"י מפרש שאם יש ברירה, “משעת שחיטה היה זה ראוי לכך.” לכאורה, זה אומר שהשיטה שסובר שיש ברירה סובר שמה שקרה מוכיח שהיה ראוי לקרות אף מקודם. אם כן, הענין הוא שנחשב כבר קרק’ שקרה.[fn:17]
2. אפשר לדחות ראיה זה לומר שרש"י מצריך שהוא ראוי לכך לסיבה אחרת, ולא כדי שיהיה ברירה. בפסח, הדין הוא שצריך שיהיה נמנה בשעת שחיטה. אז, רש"י, אולי, מזכיר שאם יש ברירה, היה ראוי בשעת שחיטה, ואז יכול להימנות. לא כל כך משמע כן מרש"י, שגמרא לא דן כבר במה שצריך להיות נמנה בשעת שחיטה. אבל, נראה שיש עוד ראיה:
3. גמרא אומר שאם אדם מתנה על גט שנותן שיהיה חל אם מת, אם יש ברירה חל. רש"י מפרש שאם יש ברירה, הוברר הדבר שמשעת נתינה היה ראוי למות. גם לשון זה משמע כמש"כ לעיל. אף כאן, אפשר לדחות כמש"כ, שאפשר שרק בא לפרש למה לא נחשב גט לאחר מיתה.
שנים אלו משמעים שרש"י אומר שמי שסובר שיש ברירה סובר שמה שיהיה כבר עומד לקרות, ולכן כשאדם מתנה ותולה בברירה, הרי הוא כאילו מתנה בקרק’ שכבר יש.
יש להעיר שזה יכול להיות לפי צד ראשון שבארנו ברש"י, אבל לא נראה לפי צד שני. לצד שני, בארנו לעיל שלרש"י היינו צריכים לומר שמחלקת של אין ברירה ויש ברירה הוא אם יש לחוש שחשב על מה שלא נברר. וצריך לחשוב על זה.
יש להעיר שזה יבאר מה שיש להקשות על מה שאומר גמרא בכמה מקומות בסוגיית יש ברירה. גמרא בכ"מ (למשל, גבי גמרא ביצה שהזכרנו או גמרא ב"ק שהזכרנו) מניח ברירה אף בציורים שלא אמר שום אדם כלום, כמו גבי ירושה או גבי יציאת מת. קשה, אז, איך תולה זה בזה. נראה שלפי מה שנראה מרש"י, מחלקת אם יש ברירה או אין ברירה הוא אם מניחים שמה שקרה היה עומד לקרות או לא. אם כן, אולי מסתבר שיהיו עוד נפק"מ תלויים בזה, ולא רק שייך, אז, בציור שאמר דבר וחשב נגדו.
אבל, יש לציין לרש"י בפסחים. שם, אומר רש"י שיש ברירה "… שהוברר שבזה נתרצה בשעת שחיטה אילו הודיעוהו.” לכאורה, כוונת רש"י לומר שמי שסובר שיש ברירה סובר שמניחים שלא טעה. לא נראה כן, שאין זה שווה בכל הברירות, שהניחא אם הוא עצמו עושה דבר שמברר, אז יש לומר כן, שכמו שרצה אותו לאחר זמן, כך רצה אותו לפני כן.אז, מסתמא מניח שימשיך להיות רוצה בו. אבל, אם לא תולה בו, אינו נראה, שמהיכי תיתי להניח ממה שקרה שהוא ידע שיקרה (ואין זה מה שאומר רש"י לחילוק בין תולה בעצמו ותולה באחרים). אז, נראה שרש"י אומר כמש"כ. כאן, שתלוי במה רוצה, יכולים להניח מה רצה ממה שרוצה, כיון מניחים שדברים שקרים עומדים להיות קרים. כמו כן, אם תולה בדעת אחרים, מניחים שדברים שקרו היו עומדים להיות קרים. ותחשב.
עיין שם בגמרא ועיין בשיח שי.
* Footnotes
[fn:1] עיין לקמן, שנדון מה זה אומר. אף שיש לדון בזה, לכאורה, אף אם לא אומר כמש"כ, עדיין ראיה הוא למה שאמרנו. עיין לקמן. גם בלי זה, כל רש"י אלו הם ראיות חזקות.
[fn:2] נראה שהיה מדלג על צד שבאמצע, והוא תלייה ממש על מה שיברר לאחר זמן.
[fn:3] נראה שיש פשט אחר. מרש"י בעירובין (שם) מבואר שכשתולה בדעת אחרים, לא תלוי במה יחשוב, אלא במה שאחר יחשוב. צריך ביאור למה זה יהיה, אבל כן אומר רש"י. אולי, אז, זהו החילוק, שאולי הוה אמינא שמפרשים דיבורו על פי מה שהוא יחשוב, אבל לא על פי מה שאותו אחר יחשוב. ותחשב.
[fn:4] היה אפשר לומר עוד צד, והוא שאולי רק חוששים לדעתו, כיון שהוא מי שתלוי עליו, וגם הוא האומר. ותחשב. מרש"י לא נראה כן.
[fn:5] אגב, ואם תאמר איך יהיה שיש תנא שסובר שאין תנאי, ולא נדע (שהרי יש כמה משניות שסומכים על תנאי). ויש להעיר שרש"י כ’ בסנהדרין ששיטת ר"י בשם ר"ג הוא שאין תנאי כלל. אם כן, אינו כל כך מוזר שיהיה תנא שסובר כן.
[fn:6] ויש לדון, שאפשר שרוצה שיהיה בידו לאחר זמן לעשות אם חל או לא. אז, אין יודעים שרוצה בו עכשיו. ויש לדון.
[fn:7] ואם תאמר אם אנו אומרים שבוודאי כוון שיחול גבי תנאי, קשה למה לא חל תנאי אף אם לא נתקיים. אין זה קשה, שמה שלא חל הוא מפני שיש חידוש תורה של תנאי, ולא תלוי אותו חידוש בדעתו, אלא הוא חלות שיכול לעשות, והוא שחלות יקרה רק אם דבר אחר קורה. ותו"ת.
[fn:8] עדיין המציאות קצת צריך ביאור, אבל זה מוסיף ביאור.
[fn:9] רצה לומר, שהוא חשב עליו כבר, שיהיה אחד מאלו משתמשים בה. אז, כאילו כבר אינתיק להיות גט של כולם. ותחשב.
[fn:10] יש להעיר ששיטה זה גם כן רבי יוחנן. אז, היה טוב מאד אם נוכל לומר שזהו המחלקת בין רבי יוחנן ורבי אשעיא בביצה, כמו שנכתב לקמן בע"ה. ותו"ת.
[fn:11] עיין שם בגמרא, שמנסה לפרש מתי טהור. היה לו לומר שהוא רשות הרבים.
[fn:12] ואם תאמר בית בכל זמן רה"י. אין זה נכון, שלא כרשות היחיד לשבת רה"י לטומאה, שצריך להיות שאין שלש בני אדם שם.
[fn:13] נראה שאפשר לדחות זה לומר שאין הכי נמי, כן הוא, ובזה חולקים. אם כן, המחלקת אם יש ברירה להקל בדרבנן אינו רק מחלקת אם סומכים על ברירה לזה, אלא מהו "אין ברירה" (ויש אף מחלקת בדין דאורייתא).אפשר לומר אז שכל ראיות שלנו ברש"י הם רק לפי הצד שיש ברירה להקל בדין דרבנן. (ואינו קשה למה רש"י מפרש כן בכל מקום, שהרי כן ההלכה.) יש לדוןאם כן, היה אפשר לומר שציורים שעלינו יש להם קושיות הם לפי מד"א שאין ברירה אף מדרבנן. יש לדון מהיכי תיתי בכל אלו שהם שלא כמו ההלכה.אף שזה גשמק, לא נראה שזה נכון:רש"י שם בביצה (לז:) לא משמע שזהו החילוק בין דאורייתא לדרבנן.רש"י משמע שהפשט באין ברירה הוא כמו שבארנו אף במה שאומר רבי יהודה שאין לסמוך עליו לתחומים. תחומים דרבנן, ומאותו מימרא מוכיח גמרא שרבי יוחנן סובר שאין ברירה אף בדרבנן. אז, היה לו לרש"י לפרש פשט אחר בברירה. אז, צריך לומר שלא כתליה שבארנו.היה אפשר לומר כעין זה, והוא שאולי חולקים אם חלות חל אם אינו ידוע כלל. השיטה שסובר שיש ברירה בדרבנן סובר שחל, והשיטה שאין ברירה סובר שלא חל. אז, לשיטה שיש ברירה, הוא ספק, ולכן יש ברירה, ולשיטה שאין ברירה, לא חל בוודאי, ולכן אינו ספק.על זה יש גם כן שני קושיות:כמו לעיל, לשון רש"י לא משמע כן.רש"י משמע שחל אף בקונה יין מן הכותי. שם הוא שיטת רבי יהודה, ורבי יהודה אומר דינו אף גבי איסור דרבנן של תחומים. אז, היה לו לומר שלא חל כלל.ויש להעיר שאם היינו אומרים כן, היה מתרץ מה שיש להקשות על גמרא עירובין. שם, מנסה להוכיח מה סובר רבי יהודה בברירה. משנה אומר שסובר שיכולים לסמוך על ברירה לעירוב, אבל ברייתא אומר שסובר שאי אפשר לסמוך על ברירה. מכריע כברייתא מברייתא אחר שאומר שאין לסמוך על ברירה ביין מכותים. קשה, שאולי זה רק מדאורייתא. אולי יכולים לוחמר שאותו גמרא אומר כרבי יוחנן, ואז אין סיבה לחלק (מה שאין כן אם נאמר כפשט הפשוט, מוכרח שיש אפשרות לחלק. עדיין יש לדון למה אין אותו פשט פשוט נכון.), שאין שום שיטה שמחלק. ותחשב. עדיין, מוזר שיהיה סתם גמרא כרבי יוחנן, שאין הלכה כמותו.
[fn:14] לכאורה, שם פשוט שתלה במה חושב רבו, ואז הענין הוא פירוש דיברו שלו. ויש לדון, שאולי חוששים שמה שרצה אינו עוד הדרך שיבוא רבו, אלא מה שרוצה רבו אז. מוזר.
[fn:15] עיין שם, שקצת סותר א"ע, שיש לשונות ברש"י שמשמעים שר"ל שתולה בדעת עצמו. יש להעיר שרש"י ראשון שהבאנו באמת קאי על זה. לא פרשנו כל זה לעיל, שלכאורה, אין נפק"מ על פי זה. ותות
[fn:16] ויש לדון למה נוקטים אותו יותר משאר בני אדם, שלכאורה, אינו יותר מסתבר שהוא נכון בשאדם אחר נכון.
[fn:17] יש לדון, שאז היה לו לומר "עומד,” ולא ראוי, שלכאורה, הכל ראוי. לכאורה, זה קשה בין כך ובין כך על רש"י.
