א.ד.- אורי דונר (הוספות- מגילה
א.ד.ר.- אהרן דב רייכמאן (זמן קיץ; ברכות- גלגל שלישי- ל: ; שבת- הוספות; יבמות- הוספות- כד. ; מרגינליא; ברכות- הוספות; חולין- גלגל רביעי- מג. ;
א.י.- אריה יורקאוויץ- מרגילניא
א.י.כ.- אהרן ישעיה כהן (בבא בתרא- הוספות; גיטין- הוספות; תרומות
א.י.ש.- אברהם יצחק שטיין (ב"מ- הוספות- סג. ; חגיגה- הוספות; מרגינליא- דף א; יבמות- גלגל שלישי- כב. וגלגל רביעי ;תמורה- הוספות; הוספות- מגילה
א.כ.- אהרן כהן (ברכות- גלגל חמישי
א.ל.ב.- אריה ליב בראנדר (מרגנליא
א.ל.י.- אברהם ליב ירקאוויץ[fn:1] (ב"ב- הוספות) ;
א.מ.ו.- אברהם מרדכי ווינער (חולין- גלגל רביעי- לב. ;נדרים- גלגל רביעי- עה.; פסחים- גלגל רביעי- פה:; מרגנליה; גליון הש"י (זבחים- צג:); בבא בתרא (גלגל רביעי); סנהדרין (גלגל רביעי); סוטה- גלגל רביעי; מעילה- גלגל רביעי; קידושין הוספות
א.ס.- אהרן הלוי סאלאוויציק (שבועות- גלגל רביעי- כב: נדה- הוספות
א.ר.- אברהם ריבאק (יבמות- גלגל שלישי- כו., מב:. נב.; רש"י עירובין- גלגל רביעי- ק:
ב.ל.- בנימין ליפשיץ (סנהדרין- כג.)
** -
גר"ק
הגאון הרב קלמן (תמורה- גלגל רביעי- כ.; מועד קטן; מרגינליא
דר. בראל- בבא בתרא (נב.); הוספות- ב"מ
ט.ק.ק.- טוביה קליין-קאפמאן (ברכות- הוספות ;סכוה, הוספות; סוטה- הוספות
י.בח.- יהודה בן חיים
י.מ.ו.- ישראל מאיר ואלף (צדי צדדים על יש נוחלים נלמדו עמו; שיחתא דשי על פאה נלמד עמו; עירובין (גלגל רביעי- רש"י- עט:); מרגנליא; ב"מ (הוספות)
מ.ש.- מאיר שטיינהרדט (מכות- גלגל רביעי
נ.א.- נפתלי אולדאק (ברכות- גלגל רביעי- מה.
ע.י.ג.- עזריאל יהודה גרינברג (מרגנליא; מגילה- רש"י- גלגל רביעי
ר.א.ש.- רב ארי שונפלד (מכות- גלגל רביעי)
ר.ד.ו.- רב דוד וויליג (ברכות- הוספות ;יבמות- גלגל שלישי- נב.; שבועות- גלגל לשלישי- טז.; סוכה- הוספות; מרגנליא; סוטה- גלגל רביעי
ר’ דר. נ.ד.- ר’ דר. נחום דוקר (מרגינליא
ר.ז.ש- רב זאב שורמן (מרגליא
ר.ח.נ.- רב חיים נפתלי (מרגנליא
ר.י.ב.- רב יצחק ביליצקי (מרגנליא
ר.י.י.- רב יוסף יפרח (מרגינליא)
ר.י.ש.- רב (י)שעיה שפיץ (גיטין- הוספות
ר.מ.ש.- רב משה שטיין (יבמות- גלגל שלישי- ל וגלגל רביעי. ; מרגינליא; זבחים (רש"י)- גלגל רביעי- טז: מנחות (גמרא)- גלגל רביעי- י.; גיטין (ח"ק יבח)
ר.ע.ו.- רב עקיבא ווינער (יבמות- גלגל שלישי- כו. ;
ר"ג שפיץ- רב גבריאל בן רב שלום שפיץ (גליוני השי- ביצה- י.)
ר"ק- רב קלמן (מרגנליא
ר.ש.ח.ל.- רב שלמה חיים לובינשטין- גיטין (ח"ק אל"י
רש"ש שליטא- רב שלום שפיץ (יומא דדינא; שבועות- גלגל רביעי- ג: חרב אל הבדים- ב"ב- קיץ; זבחים- גלגל רביעי- קא:’ קב.; מנחות- גלגל רביעי- נג.; מרגנליא; עבודה זרה- גלגל רביעי; ברכות- גלגל חמישי
ש.וו.- שמחה וואקסבורג (הוספות- ב"מ
ש.ז.מ.- שמעון זאב מונק (תמורה- הוספות
ש.ח.ח.- שמעון חיים חייט (מרגנליא
ש.ל[fn:2].- שמואל לאוב- למדתי עמו: חולין (שני), בכורות (שני, חצי שלישי, חצי אחר של רביעי), מעילה (שני), תמיד (שני), ערכין (שלישי), תמורה (שלישי), כריתות (שלישי), יבמות (שלישי), גיטין (שלישי), שבועות (שלישי, חצי רביעי), נדרים (רביעי), נזיר (רביעי)- (יבמות- גלגל שלישי- סא: ;ברכות (גלגל חמישי)
* Footnotes
[fn:1] הוא א.ל.י של "חברותא קטן,” ואז כל מה שכתבתי שם נלמד עמו.
[fn:2] לפעמים, הוא ש.א.ל.
