נביא גמרא מעניין בכתובות, ונבאר אותו גמרא. נקשה עליו קושיה, ונביא כמה צדדים לתרץ אותו.
כדי לעשות כל זה, נביא שלש ענינים, ונדון עליהם:
א.
גמ’ שנביא מתובות מתחיל עם שיטה של רבי נחוניה בן הקנה. כדי לבאר את זה, צריך להקדים בדין אחר. אם אדם עושה עבירה (או עבירות) עד שנמצא שבזמן אחד נתחייב מיתה ומממון- משל של הגמ’ הוא ששורף את התבואה של חברו בשבת, שמבעיר בשבת, וגם מזיק לחברו- לא חייב חיוב ממון, אלא רק חייב חיוב מיתה. במילים אחרים, לא יכול אדם להתחייב חיוב ממון אם באותו רגע מתחייב חיוב מיתה.
יש שלש מינים כלליים של חיוב מיתה- יש חיוב מיתת בית דין (הוא הארבע מיתות שבית דין ממיתים לחוטאים מיוחדים), יש חיוב כרת (לקמן נבאר יותר מה הוא), ויש חיוב מיתה בידי שמים (לקמן נבאר מה הוא). רבנן סוברים שפטור מממון הוא רק במין ראשון של חיוב מיתה. רק אם אדם מתחייב מיתת בית דין הוא פטור מחיוב ממון. אבל, אם הוא מתחייב מיתה אחרת, חייב גם חיוב ממון. (וא"ת יהיה כבר מת. ויש לומר שאם מת קודם שמשלם, יורשים שלו חייבים לשלם.)
ר"נ בן הקנה חולק על זה. סובר שגם חיוב כרת פוטר מחיוב ממון; אם אדם מתחייב כרת, לא יכול להתחייב ממון באותו רגע.
גמרא בכתובות מחפש למקור של רבי נחוניה בן הקנה. לבסוף, מביא שני מקורות- מקור של אביי ומקור של רבא. אנחנו נדון בעיקר על מקור של אביי.
גמ’ אומר: “אמר אביי נאמר {שמות כא-כג} אסון בידי אדם ונאמר {בראשית מב-לח} אסון בידי שמים מה אסון האמור בידי אדם פטור מן התשלומין אף אסון האמור בידי שמים פטור מן התשלומין.” יש לדון קצת מהו מקורו, אבל הפשטות הוא שלומד גזרה שווה. הפסוק מספר ריב בין שני אנשים, כשבאה אשה של אחד מהם, ואיש האחר מכה אותו. אם אין אסון- אם לא קרה דבר שמחייב אותו במיתת בית דין, שלא הורג אדם, אלא רק ולד- אז חייב ממון על הוולד שהרג (וזה מפני מה שכתבנו לעיל, שחיוב מיתה פוטר חיוב ממון). מילת אסון מדבר על חיוב מיתת בית דין, שהוא דבר שפוטר אותו מחיוב ממון. יש פסוק אחר שמזכיר מילת אסון. כשהאחים אמרו ליעקב להוריד את בנימין למצרים, יעקב סרב, ואמר שהוא מפני שחשש שמא יקרה לו "אסון.” גמ’ מפרש שיעקב חשש לכל מין אסון- אסון בידי אדם ואסון בידי שמים. נמצא שיש מילת אסון שמדבר גם על מיתה בידי שמים. אז, דורשים גזרה שווה, לומר שכמו שגבי מיתה בידי בית דין, לא יכול להתחייב ממון, כך גבי מיתה שבידי שמים, לא יכול להתחייב ממון.
מסוף הגמ’ יוצא, לכאו’, שיעקב חשש לכל מינים של מיתה- חשש גם לכרת וגם למיתה בידי שמים.
מה שאנחנו נוציא מזה, אז, הוא שחשש יעקב שבנימין ימות בדרך, והיו שני אפשריות במיתה שלו- היה אפשר שימות מיתת כרת והיה אפשר שימות מיתה בידי שמים.
ב.
עכשיו, נבאר מהו כרת ומהו מיתה בידי שמים.
יש לנו שלש מקורות קדמונים ששייכים לזה:
1. גמ’ במועד קטן (כח.) מביא בריי’ שמונה מיני מיתה, ואומר: “מת בחמשים שנה זו היא מיתת כרת חמשים ושתים שנה זו היא מיתתו של שמואל הרמתי ששים זו היא מיתה בידי שמים.” על זה, מר זוטרא אומר: “מאי קרא דכתיב "תבא בכלח אלי קבר,” ו"בכלח" הוא בגמטריה ששים. בעזרת ה’, לקמן נבאר את הדרשה הזו. ממשיך בריי’ לומר שבשבעים הוא שיבה ובשמונים הוא גבורה.
2. נמצא שיודעים מה קורה כשמת בחמישים וכשמת בששים ושבעים ושמונים. אבל, לא יודעים מה קורה כשמת בינתיים. הפשטות מן הבריי’ היה לומר שאין זה שום מיתה מיוחדת, אלא מת באיזה זמן על פי זכותו. אבל, רבה מסביר שאינו כן, ואומר שמחמישים ועד ששים הוא מיתת כרת. לא מזכיר אותו משום כבודו של שמואל הרמתי (שמת בזמן של כרת). עדיין לא יודעים מה קורה בין ששים לשבעים. יש, לכאו’, שני דרכים פשוטים. אפשר שבזה נישאר עם הנחה שלנו שאינו מין מיוחד של מיתה. הדרך השני הוא שהוא כמו כרת- בכרת אומר חמישים, ומכוון לומר כל העשר (או שחמישים יכול להיות השם של כל העשר, או שהוא עד הזמן שנזכר להיות דבר הסותר לכרת). אז, בין ששים לשבעים הוא מיתה בידי שמים.
3. יש להעיר שפני משה כ’ במראה הפנים שזה רק שיטת רבה. אבל, סתם של הש"ס חולק על זה. (מוזר להניח שכל זמן שאמורא אומר דבר יש סתם של ש"ס שחולק עליו.) סתם של ש"ס סובר כירושלמי שנביא, בע"ה, לקמן. אבל, תוס’ ביבמות חולק על זה, ואומר שש"ס בבלי חולק על הירושלמי. יש לדון אם מפרש את הסתם באופן אחר (לכאו’, כמו שפרשנו לעיל) או שסובר שאין סתם שחולק על רבה.
4. יש דיון אחר שיש לדון כאן. כשאומר שמיתה בגיל מיוחד הוא מיתה מיוחדת, יש שני דרכים לבאר את זה. אפשר שמי שמת בכרת, מת באותו גיל. גם אפשר שמי שמת באותו גיל, בדרך כלל מת אז מפני שמת בכרת (אולי זה בכוונה ואולי זה לא בכוונה). (גם אפשר ששניהם נכונים.)
5. לכאו’, אם רבה צודק, יש להקשות מה קורה אם מת בן ששים שנה. בתחילה, בריי’ אומר שזה מיתת כרת, ואחר כן אומר שזה מיתה בידי שמים. לכאו’, יש שני דרכים לתרץ לזה. דרך ראשון הוא לומר שכשאומר שהוא עד ששים שנה, לא כולל כשהוא בן ששים, וכשאומר שמיתה בידי שמים הוא בן ששים שנה, מתחיל מבן ששים שנה (ולא כשהוא בתוך שנה ששית שלו). גם אפשר לומר שיכול להיות שנהק ששיכת לכולם. אבל, עדיין יש חילוק ביניהם, במה שכרת הוא גם בין חמישים לששים. (יש להעיר שאם אין סתירה ביניהם, צד אחד שכתבנו במה שמניחים שהוא עד ששים שנה אינו אפשר. ותו"ת.)
6. גמ’ ממשיך לומר שרב יוסף, כשהיה בן ששים, עשה יום טוב, שיצא מחיוב כרת. לכאו’, זה מוכיח שששים שנה אינו מיתת כרת. אבל, עדיין לא מוכרח שאין מי שהוא בשנה ששית שלו מת במיתה בידי שמים. (גם היה אפשר לדחות שטענת אביי שם הוא שאפשר שימות באותו יום, ולא יכרת משנה אלא מימים. אבל, ראשונים לא מפרשים כן. יותר מכך, לא פשוט שמה שהוא רע הוא שמת קודם ימיו, שיותר היה נראה לומר שהוא סימן שנכרת מה’. ויש לדון בזה. גם יש לומר שכיון שרק מת קצת קודם זמנו, אינו כל כך נכרת. ותחשב על זה.)
7. אז, לכאו’, מה שיוצא מן הגמ’ במ"ק הוא שמיתת כרת ממית אותו בין חמישים לששים, ולא כולל ששים. מיתה בידי שמים ממית אותו בששים (ולא פשוט אם זה בשנה ששים או אחרי ששים שנה), ואולי גם עד שבעים.
8. ירושלמי בבכורות מביא בריי’ שדומה למה שמביא גמ’ במ"ק (לכאו’, הוא אותו דבר עם קצת שינוי בגי’). אומר ש"המת לחמשים שנה מת בהיכרת. לחמישים ושנים מיתת שמואל הנביא. לששים מיתה האמורה בתורה. לשבעים מיתה שלחיבה. לשמונים מיתה שלזקנה." שם, מביא מקור לזמנים אלו.
9. מביא שני מקורות לזמן מיתת כרת:
  1. הראשון הוא מה שאומר קרא גבי עבודת שבט לוי. אומר שצריכים להיזהר לשמור מן הקודש, כדי שלא יכרתו. הרי, לויים לא עובדים כשהם יותר מבן חמישים שנה. אז, נמצא שמיתה זו הוא בן חמישים שנה.
10. אי אפשר שזה יהיה מקור שמתים כשהם בן חמישים שנה או כשהם בן חמישים ועד ששים שנה. הרי, הקרא מדבר בחיוב כרת שיכול להתחייב רק עד חמישים שנה, ואין זה שייך כלל למה שיהיו מתים בן חמישים שנה.
11. לכאו’, צריך לומר שירושלמי סובר שמת עד חמישים שנה (וכך מפרש חמישים שמזכיר). (ונ’ שזה שייך למה שגי’ שלו קצת חלוק מגי’ של הבבלי.) אבל, באמת, אף זה לא פשוט, שהרי קרא מדבר על מה שמתחייב כרת, ואומר שאם שומר א"ע לא יתחייב כרת. צריך לפרש שמבאר את הקרא שאומר שאם שומרים את עצמם- ונדע כן ממה שלא מתו- אז בוודאי לא נתחייבו כרת, שצריך למות קודם חמישים שנה. (גם אפשר שסובר שמילים שאומרים שלא יכרתו הם מיותרים, שרק יאמר שלא יעשו ככה, ואם יעשו ככה יתחייבו כרת. צריך לומר שמכוון לומר דבר אחר, והוא שמיתה קודם חמישים הוא מיתת כרת.)
12. וע’ בתוס’ בשבת, שנראה שמפרש ככה: קרא אומר שני לשונות, שיעשה שלא ימות ושלא יכרתו. כשאומר שלא ימות, מובן שרצה לומר שלא ימותו בתוך עבודתם. (לא פשוט למה תוס’ חושב כן; אולי הוא מפני שבין כך ובין כך מתים. דחוק, שאולי רצה לומר שלא ימותו קודם זמנם.) זה מיתה בתוך חמישים, שאחר כך נפסלים, והרי אומר על זה שלא יכרתו. נמצא שאם לא מת קודם חמישים, אינו נחשב שנכרת. (לכאו’, עדיין אפשר, אז, שאין כרת עד חמישים אלא רק חמישים. אבל, אז אין מקור לזה, ומוזר שיביא מקור רק למחצה של הדין. אז, לא נראה שיהיה חילוק.)
  1. השני הוא שזמן רגיל של חיי אדם הוא שבעים שנה. הרי, לא נענש על מה שעשה בתוך עשרים שנים ראשונים. אז, נשאר חמישים שנה.
13. לא פשוט מה בכלל הוא המקור מזה. פני משה שם מנסה לבאר מה שהוא, אבל לא פשוט מה מכוון לומר. הכלל הראשון שצריכים לדעת כשמתחילים ללמוד ירושלמי הוא שתמיד לא פשוט מה מכוון הפני משה לבאר. על כל פנים, על פי פירושו (וכן משמע מפשטות הירושלמי), לא חולק צד זה על צד ראשון, ושניהם סוברים שעד חמישים שנה הוא מיתת כרת.
14. מביא שני מקורות למה שמיתה בידי שמים הוא ששים שנה:
  1. גזר ה’ במדבר שכל האנשים שבין עשרים לששים לא יגיעו לארץ. הרי, היו במדבר לארבעים שנה.
15. לא פשוט מהו המקור מזה. לכאו’, אפשר שמי שהיה בן חמישים וחמש חי עוד שלושים שנה. נראה שמדייק ממה ששהו שם ארבעים שנה בדווקא. מניח שהוא כדי שימותו כולם בששים. לכאו’, יש שני דרכים לבאר את זה:
    1. היה לו להיות יותר קצר, אבל רצה ה’ שלא יכנסו לארץ, ורצה שימותו מיתה בידי שמים. אז, הוצרכו לחכות עוד ארבעים שנה. לפי זה, צריך לומר שמיתה בידי שמים הוא רק בששים, ולא לפני ששים.
16. יש להעיר שיודעים שלא מתו בשנה אחרונה (לכן ט"ו באב הוא יום שמח). אז, קשה, שלא מתו בן ששים. צריך לומר שבן ששים רצה לומר בשנה ששית.
17. נראה שכך מפרש רשי בבמדבר.
    1. היה לו להיות יותר ארוך, אבל אחרי ארבעים שנה, כולם מתו.
18. יש להעיר שיודעים שלא מתו בשנה אחרונה. אז, קשה למה לא נכנסו כבר. ויש לבאר על פי מה שנכתב לקמן.
19. נמצא שלא פשוט אם סובר ירושלמי שששים שנה הוא עד ששים, ששים, או מששים. אבל, מה שלשונו דומה ללשון כרת, ולשון כרת מורה שעד חמישים מת במיתת כרת, משמע שאף כאן, עד ששים מת במיתה בידי שמים.
20. אבל, אז צריך לדון אם מת במיתה בידי שמים מחמישים עד ששים או מאפס עד ששים. (עיין לעיל, שלאחד מן הדרכים שכתבנו לעיל, מוכרח כצד ראשון.)
21. קצת קשה, שמצאנו סיבה אחרת למה שהה ארבעים שנה, והוא שנה כנגד יום שהיו מרגלים בא"י. לפי צד ראשון, יש לומר שבעצם היה לו להיות ארבעים יום. אבל, עדיין קשה, שנחכה הכי מועט שאפשר, וזה ארבעים שנה. גם לפי צד שני עדיין קשה. צריך לומר שזה קבע כמה ארוך וקצר יכול להיות, ובתוך אותו גדר, היה יכול לנקוט כל מה שרוצה. נקט ארבעים שנה מפני דמיון זה. ותחשב. (עדיין יש לדון מהיכי תיתי, ולמה נדייק כלום מארבעים שנה, שאולי הוא רק מפני שענש שנה כנגד יום. ותחשב. אולי לצד ראשון אינו כל כך קשה, שהיה לו לנקוט יום כנגד יום.)
  1. ירושלמי גם מביא מקור של בבלי, שכ’, “תבוא בכלח עלי קבר.” (ואגב, לשון ירושלמי משמע שאינם שני מקורות, אלא הם מקורות ביחד. הרבה פעמים, מביא גמ’ שני מקורות לדבר, אבל בדרך כלל מבאר למה צריכים שניהם. הרי, כאן לא מבאר. נראה שאף אחד מהם אינו מיותר, ויש, באמת, שני דרכים לנו לדעת זה.)
22. אם נעיין בקרא, נראה שהוא בספר איוב. שם, חברים של איוב מספרים לו שאף שקרו לו הרבה צרות, עוד יבוא ימים טובים לו וימות בזמן הראוי. נראה שיש שני דרכים לפרש איך זה יכול ללמד:
    1. אפשר שאמרו לו שימות בן ששים שנה. זה מכריח שלא ימות במיתה שבידי שמים, שהרי מיתה שבידי שמים ממית אותו קודם ששים שנה. אבל, כמובן, זה רק אפשר אם נאמר ש"ששים" שאומר בריי’ אומר שימות קודם שהוא בן ששים.
    2. אפשר שאין צורך להם להזכיר מתי ימות, או אין צורך להם להזכיר אותו בלשון זה, ואז דורשים שמיתה שמדברים עליו הוא רמז למיתה אחרת. יודעים כבר מתי מת מתחייב כרת- ואינו בן ששים- ואז דורשים מזה מתי מת מי שנתחייב מיתה שבידי שמים. כמו כן, יש לומר שזה אינו מקור, אלא רק רמז. (לכאו’, זה יותר קל לומר בירושלמי, כיון שמביא מקור אחר. אבל, לאידך גיסא, בבלי, כנראה, סובר שאין צריך מקור, שלא מביא מקור לזמן כרת. אז, יש לומר שזה רק סימן שהוא ששים שנה, אף זה מדבר על מיתה טובה. ותחשב.) לזה, לא נראה שיכולים להוכיח אם מת בששים או לפני ששים או לאחר ששים.
23. מה שיוצא מן הירו’ הוא שלכאו’ סובר שמיתת כרת הוא עד חמישים, ולא פשוט מה סובר במיתה בידי שמים.
24. בריי’ במסכת סופרים אומר: “מת פחות מחמשים מת בהכרת לחמשים ושתים שנה זו היא מיתת של שמואל הרמתי מת לששים שנה זו היא מיתה האמורה בתורה שנאמר (איוב ה) תבא בכלח אלי קבר מת לשבעים שנה זו היא מיתה של שיבה שנא׳ (תהלים צ) ימי שנותינו בהם שבעים שנה מת לשמונים שנה זו היא מיתה של גבורה שנא׳ (שם) ואם בגבורות שמונים שנה.”
25. לכאו’, זה בפי’ כירושלמי. אפשר שבבלי לא גורס כן באותו בריי’ או שלשון בריי’ שלו מוכיח שחולק על בריי’ זה.
26. גם יש להעיר שמשנה לשון בין כרת למיתה בידי שמים, ואולי זה משמע שלא שווים, ובאחד הוא כל הזמן עד אז, ובשני הוא רק באותו זמן. ותחשב.
לזה, יש להוסיף כמה נקודות:
1. תוס’ אומר במועד קטן שירושלמי לומד מיתה בידי שמים ממתי מדבר, שלא מתו פחות מבן ששים. אז, בוודאי מפרש שגבי מיתה בידי שמים, לא מכוון לומר שמת עד בן ששים. (ע’ שם, שלשונו הוא ש"אמרינן שלא מת אחד מהם פחות מבן ששים.” איני יודע למה מכוון, ואיפה אמרינן כן, שלא מצאתי אותו. נראה שמדבר על הירושלמי, וגורס כן בירושלמי בביאור הדרשה.)
2. תוס’ במועד קטן מביא צד שמיתה בידי שמים הוא גם בחמישים (לכאו’, משנה את הגי’ בכל המקומות). אז, החי’ בין מיתה בידי שמים וכרת הוא בדבר אחר (אם בניו מתים). ביבמות, נראה שתוס’ אומר שכך הוא שיטת רש"י.
ג.
צריכים לפרש בן כמה היה בנימין כשחשש אביו שימות במיתת כרת ומיתה בידי שמים.
הפסוק אומר שהיה יוסף בן שלושים שנה כשעמד לפני פרעה בפעם הראשונה. אחרי זה, היו שבע שנים של שבע ושני שנים של רעב, עד שירד יעקב למצרים. נמצא שכשהגיע יעקב למצרים, היה יוסף בן שלשים ותשע שנים. הרי, יודעים שהיה בנימין שבע (או יותר) שנים קטן מיוסף, כיון שנולד יוסף ארבע עשרה שנים אחר ביאת יעקב ללבן (ולכן רצה לחזור אז), שהוא שבע שנים לפני חזרתו. יודעים שבנימין נולד בדרך. אז, היה בין שבע לתשע שנים יותר קטן מיוסף. אז, באותו זמן, לא היה בנימין יותר גדול משלושים ושנים. הדיון של האחים עם יעקב אם לשלוח את בנימין קרה לפני שיעקב ירד למצרים.
אז, מכל זה יוצא לנו קושיה: הגמ’ אומר שיעקב חשש שבנימין ימות בכרת או במיתה בידי שמים אם ירד למצרים. אבל, יודעים שבנימין לא כהיה קרוב לגיל חמישים וששים, שהוא זמן מיתת כרת ומיתה בידי שמים. אז, איך אפשר שימות בכרת או במיתה בידי שמים.
יש להעיר שיש, באמת, שני קושיות כאן. הקושיה הראשונה הוא איזה חשש היה לו ליעקב. אין שום עונש בעולם שיגרום שבנימין ימנות, כיון שבנימין לא יכול להתחייב מיתה בידי שמים ולא יכול להתחייב כרת. לא נראה שזה קשה, שיש הרבה עונשים שה’ מעניש לא כתובים בתורה. למשל, ראינו בברכות מי שגזל ולכן נעשה רש. לא כתוב בתורה שזהו עונשו של גזלן, אלא שה’ בוחר, לפעמים, לענש לגזלן ככה. נראה שיש קושיה אחרת שהוא יותר קשה. כיון שאי אפשר שמיתה זו היא מיתת כרת או מיתה בידי שמים- אי אפשר שלזה חשש- איך אפשר ללמוד מזה דינים למיתה בידי שמים וכרת. רק נוכל לדעת מה יקרה במיתה שקורה כשהוא בן שלשים, אבל לא  נדע דין כרת ומיתה בידי שמים.
נראה שיש לקושיה זו שבע תירוצים:
1. אזכיר כאן תירוץ שהוא מאד מעניין, אבל לכאו’ אינו נכון. יש רבינו אפרים על התורה שהוא ידוע לבני אדם שלהם מעניין חלקים מוזרים של תורה. יש שני גי’ של ר"א על התורה, ובאחד מהם אומר ש"בנימין היה זאב וטורף בני אדם לעתים [ובא לו עת שנהפך לזאב].” במילים אחרים, אומר שבנימין היה ווארוואל"ף. (כמו כן מביא החיד"א בספרו דבש לפי.)
2. על פי זה, אז, אולי יש לומר שכמו שידוע שכלבים ומיני חיות אחרות מגדלים יותר מהרים מבני אדם (כמעט כל חיה שבעולם מגדל בזמן יותר קצר מבני אדם. גם בדרך כלל לא חיים זמן ארוך כבני אדם. אין ממ"ל אחר שחי בזמן דומה לבני אדם, אם נשער את כולם על פי ההארטבי"ט שלהם. באמת, כל ממ"ל חי קרוב לזמן שווה, חוץ מבני אדם, שחיים מאד יותר ארוך.), אולי אז גם בנימין שהיה ווארוואל"ף נחשב שהיה כבר בן חמישים או בן ששים כשהיה רק בן שלשים.
3. עדיין, צריך להיות חשש לשני מיני מיתה, וצריך לומר או שיש זמן אחד ששניהם אפשרים, או שהיה בסוף ימי כרת, קרוב לתחילת ימי מיתה שבידי שמים.
4. אבל, חוץ הן החידוש הפשוט, יש להעיר שרבינו אפרים כותב כן להסביר מה היה האסון שלו חשש יעקב אבינו. אומר שכל זמן שהיה בנימין קרוב לעיקב אבינו, יעקב מצא לו רופא שהיה עושה שלא יהפך לזאב. אבל, חשש שכשיצא ממנו, יהפך לזאב, ויתחיל להרוג בני אדם, ויהרגו אותו להציל את עצמם.
5. הרי, אם תמשיך בגמ’ כאן, תראה שגמ’ שלנו לא סובר כן, אלא מזכיר שהיה יעקב חושש משום צינים פחים ומשום גנבים ומשום אריות. אין הגמ’ כל כך קשה על רבינו אפרים, שלאיזה סיבה, ראשונים לא מקפידים לפרש פסוקים כגמ’, אבל אז מוזר לפרש את הגמ’ על פי רבינו אפרים, כיון שאומר כן לבאר מה שגמ’ חולק עליו. צריך לומר שלא צריך ביאור זה ב"אסון" לומר שבנימין היה, באמת, “זאב טורף.”
6. אפשר שאביי, שאומר כן בגמ’ שלנו, סובר כירושלמי שהזכרנו, שסובר שמיתת כרת אינו בחמישים, אלא עד חמישים. הרי, שלשים יותר קטן מחמישים, ויש לחוש שימות במיתת כרת. צריך לומר כן גם במיתה שבידי שמים, ואף הוא עד ששים. (אז, אפשר לשני בני אדם למות באותו זמן, ולהיות אחד מחייבי כריתות ואחד מחייבי מיתה בידי שמים. אבל, עדיין יש חילוק ביניהם, והוא בסיבה שלהם. אחד מהם בא מסיבה אחד, שמחייב מיתה עד גיל שישים, ואחד בא מסיבה שונה, שמחייב מיתה עד גיל חמישים. ותחשב.[fn:1])
7. יש להעיר שזה יותר קל לומר לפי מה שאמר פני משה, שאף סתם של בבלי סובר כן.
8. ועיין בגמ’ במועד קטן, ששם יוצא שרב יוסף לא סובר כמו ירושלמי. עיין שם, שאביי מדבר על מה שאומר רב יוסף. אולי ממה שלא משיב לו אביי שכבר יצא מכרת לפני הרבה שנים משמע שלא חולק אביי. ויש לדון בזה, שזה לא שייך, שבין כך ובין כך היה לו לעשות סעודה, אלא שאיחר תשע שנים. ותחשב.
9. גם אפשר לומר שגם הבבלי סובר כעין הירושלמי[fn:2]. כשאומר שכרת הוא מחמישים ועד ששים, רק רצה לומר שהוא גם מחמישים ועד ששים. אז, סובר כירו’ במה שהוא עד חמישים. ואם תאמר למה מחלק חמישים עד ששים, שהרי אין חי’ בין חמישים עד ששים ללפני חמישים. אפשר שהבריי’ לא מחלק אותם, אלא אומר מה שאינו האמת. (אבל, אז, לכאו’, “חמישים" שנוקט אינו דווקא, והיה יכול לנקוט כל דבר פחות מחמישים ושנים. אולי חמישים קצת יכול לומר בתוך החמישים, שהוא עד ששים.) גם יש לומר שיש חילוק בין חמישים עד ששים לעד חמישים, שאחד מהם יותר מצוי. ותחשב. כמו“כ, יש לומר שמת עד חמישים אם אין מצווה תולה, ומת מחמישים עד ששים אם יש זכות תולה. ותחשב.
10. צריך לומר כן, אז, גם למיתה בידי שמים, שהוא עד שישים. ואם תאמר אם כן מאי בינייהו, שמיתה בידי שמים וכרת הם באותו זמן. אז, קשה למה בריי’ חילוק אותם. ויש לדון, שיש לומר שחילק אותם כדי שלא להשמיע רע על שמואל. (צריך לומר שכיון שכרת יותר חמור, במה שגם ממית את הבנים, היה משמיע רע על שמואל יותר, ולכן רק לו חושש. אבל, צריך לומר כן אף בלי תירוץ זה.[fn:3].) ואם תאמר אם כן איזה חילוק יש בין העונשים. ויש לומר שיש סיבה כללית אחרת שנענש, אבל חוץ מזה אין שום חילוק.[fn:4] (אבל, אז צריך למצוא סיבה אחרת למה אי אפשר ללמוד מכרת למיתה בידי שמים; צריך לומר כרש"י נגד תוס’ במח’ אם בני חייבי כרת מתים. אבל, אז נמצא שיש עוד חילוק ביניהם, והוא זה. ויש לדון, שאולי יכול להליות חילוק במה שלפעמים כרת גורם מיתת בנים, ורק סיבת כרת לפעמים גורם זה, ולא סיבת מיתה בידי שמים, וזה חומרה לכרת, כתוס’. ותחשב.)
11. גם אפשר שיש חילוק ביניהם באיזה גיל יותר מצוי (כמו שכתבנו לעיל). לפי רש"י, יש חילוק במתי בנים מתים, כמו שהזכרנו.
12. וע’ בלשון תוס’ בשבת, שאומר שכרת הוא "שאינו מגיע לששים.” לא מבאר שמיתתו מתחיל בחמישים, ואז משמע כצד זו.
13. אפשר שחשש שיהיה בדרך לזמן רב, וימות כשהוא בן חמישים או בן ששים, ולא יראנו עד אז. לא נראה כן, שנראה שזה חשש רחוק. (אף שזה קרה ליוסף, עדיין חשש רחוק הוא. (אבל, ע’ בגמ’ ברכות  י., שאומר לימוד כזה[fn:5].) יותר מזה, לא ידע כבר מה קרה ליוסף, וחשב שממש מת.) אז, קשה לזה לומר סיבה לחשוב שזה היה בתוך חשש של יעקב. (שוב ראיתי ששיט“מ מביא הקושיה ומביא תי’ זה.)
14. גם אפשר שחשש שבדרך יתחייב בכרת או במיתה בידי שמים (כיון שהוא רחוק משמירה רוחנית של יעקב אבינו). נמצא, אז, שרק חושש שימות, ולא חושש לעבירה עצמו שמחייב אותו. זה מעניין.
15. לא נראה שזה יכול להיות נכון, שלשון גמ’ (שדן באריות וצינים) מוכרח נגד זה.
16. אפשר לומר שאין הכי נמי, לא חשש יעקב לאחד מאלו, אבל מחמת שיש גזירה שווה, חייבים אנו ללמוד ממנו. אז, "אם אינו ענין למיתה הנזכר, תנהו ענין למיתה שלא נזכר."
17. לכאו’, זה תלוי באם גזירה שווה הוא מופנה (בא ממילה מיותרת) או לא מופנה. יכולים לומר כן רק אם ג"ש מופנה הוא. לא פשוט לי אם הוא מופנה. הייתי אומר שמוכרח שהגזירה שווה הוא מופנה, שבוודאי בלי זה אי אפשר ללמוד ממיתת בית דין, שנעשה בדרך אחר, ושנעשה מיד (באיזה גיל שהוא, ואי אפשר בו תשובה), למיתה בידי שמים וכרת.אבל, לא פשוט לי למה זה מיותר כלל; אולי צריך לומר שמילת ”אסון“ והא מילה מוזר, והיה לו רק לומר שאם לא מת, אז הדין ככה. ותו"ת. על כל פנים, כיון שמופנה הוא, מוכרחים לדרוש, ואז אומרים ”אם אינו ענין.“ חוץ מזה, יש לומר שקבלו מסיני לדרוש גזרה שווה זו (אלא שמרשי בכ"מ משמע שרק קבלו המופנים), ואז צריכים לדרוש ממנו. ודע שאם מופנה הוא, צריך ביאור מה עושה בו רבא. אם מה שמופנה הוא מה שנקט מילה מוזרת, אולי לא קשה לומר שרבא סובר שאינו מופנה, ומילה זו לא כל כך מוזרת.
18. ואם תאמר אם כן רק נלמד אחד- מיתה בידי שמים או כרת- ממנו. אפשר שלא נדע איזה לרבות, כמו שבארנו (שיכול להיות תלוי בחומר או בקולא), ואז מרבים שניהם לדין זה. (מצאנו כעין זה בגמ' בזבחים במין אחר של לימוד.)
19. ואם תאמר אולי בא לחדש שאם אדם חייב מיתה בידי שמים שבו מת בגיל פחות מחמישים, אז פטור מתשלומים. ויש לומר שאין אפשרות לדעת שנענש בזה. אם נאמר שיודעים ממה שמת, צריך לדחות שמה שמת לא יכול להיות ראיה לזה; כן נראה גם מן הסברה. אם נאמר שיודעים ממה שראה שעבר על חיוב מיתת בית דין, ולא היה בית דין יכול להרוג אותו, שגמ’ אומר שעל כעין זה ה’ ממית אותו באופן דומה למיתה של בית דין, אז יפטור בלי פסוק, כיון שעבר על מיתת בית דין, כמו שיאמר גמרא לקמן. ותו"ת.
20. הקושיה על זה, אף שיש לנו קצת הוכחה לזה, כיון שיש לנו הוכחה שהג“ש מופנה, הוא שגמ’ מקשה שאולי בידי אדם הוא. אם כן, לא היה מלמד כלום, ואז היה עוד מופנה. צריך לומר שהיה דבר אחר לדרוש- ואיני יודע מהו- ואז גמרא לא אפשר להיות אומר כצד זה. ותחשב.
21. גם אפשר שבדרך כלל, כרת ומיתה בידי שמים רק ממיתים בגיל חמישים וששים. אבל, כשהעובר הוא במקום מסוכן, כמו בדרך, ממיתים בגיל יותר נמוך. כמו כן מצאנו גמ’ בשבת, שאומר שלא ללכת למקום מסוכן. הפשטות של הגמ’ הוא שה’ יותר עליל להעניש אדם כשהוא במצב של סכנה.
22. יש לדון בזה, שאז כל הנפק"מ של חמישים וששים הוא למי שעד אז לא הלך במקום מסוכן. לא כל כך פשוט מה הגדר של מסוכן, אבל אם דרך של בנימין הוא מסוכן (לא מפני שהלך למצרים, אלא גם מחמת צינים ופחים וגנבים ואריות, כמו שאומר גמ’) לכאו’, הייתי אומר שאז חמישים וששים לא מצוי כלל. אם כן, מעניין שבריי’ יאמר אותו סתם. צריך לומר שמה שהוא עיקר דינו די לומר אותו סתם. ותחשב.
23. גם יש להעיר שאז אף שמדבר על חיוב כרת, שמת כיון שחייב כרת, אין עונש שלו כרת, שהרי מת בגיל יותר נמוך. אז, לא כל כך פשוט למה סובר שיכולים ללמוד מכאן לפטור שאר מתחייבי כרת ומיתה בידי שמים.
24. אבל, זה לא פשוט. לכאו’, יש לדון מה פוטר אדם מחיוב ממון, אם הוא שיש עליו חיוב מיתה או הוא מה שייענש בחיוב מיתה. הרי, כאן ייענש ביותר, אבל לא חייב כך.
לפי רש"י, בניהם של חייבי כריתות מתים, קשה למה חשש שבנימין יחייב כרת, שהרי כבר היו לו הרבה בנים. דחוק לומר שהיו הולכים עמו- למה ילכו עמו, ולמה לא יעכב יעקב אותם. צריך לדון למה יותר קל לענשו כשהוא בדרך. אפשר שהוא שאין כל כך מניעה לחיובו. בדרך כלל, יש מניעה על חיוב, והוא מה שה’ לא רוצה ל"הטריח,“ כמו שאומר גמ’ בסנהדרין. אבל, כאן אינו טרחא. אם כן, היינו צריכים לומר שהוא טירחא קצת יותר קטנה כאן, כיון שכבר קל להמית את בנימין. גם אפשר שמה שיש אפשרות בקלה שאדם ימות עושה שה’ דן אם אותו דבר יקרה. אז, מסיר מניעה מחיוב כרת, והוא מה שה’ לא דן. אז, יש לומר כן כאן גם כן, שה’ ידון על מיתתו, ואז ימות, אף אם לא היה מת בלי הדיון. (ודע שאם כן, לכאו’ יהיה שווה אם בן שלו הלך, ולא הוא. ותחשב.)
* Footnotes
[fn:1] לא כל כך פשוט מה מכריע מתי מת. אולי הוא מתי קל ביותר לה’ לעשות שהוא ימות. גם אפשר שהוא צדקות שלו. גם אפשר שהוא אופן שעשה את העבירה. אם כן, שניהם יותר דומים, שבשניהם, הסיבה הוא שימות באותו שנה. צריך לומר שגורמים אותו בענינים שונים- לדוגמא, נגיד שבזה ס“ר עושים שחייב למות אז, ובזה חוצפה לה’ עושה כן. (אף אם שניהם הם רק מחמת סיבות רעות, עדיין יכול להיות שהם מינים חלוקים של סיבות. ויש לדון.)ויש להעיר שלפי רש"י יש עוד חילוק ביניהם, והוא אם בניו מתים או לא מתים. אז, היה אפשר לומר שאין חילוק חוץ מזה.
[fn:2] לא סובר ממש כירושלמי, כמו שנבאר, אבל סובר, כמותו, שמת עד הזמן הנזכר.
[fn:3] ויש להעיר שאם, באמת, בנים של המחייבים כרת מתים, קשה מה היינו חושבים על שמואל שלא מתו בניו. אולי מה שלא הלכו בדרכיו מספיק. דחוק.
[fn:4] יש להוסיף שהיה נראה לומר שיש חילוק ביניהם, והוא שבחיוב מיתה מן השמים, חייב מיתה. אבל, בכרת, לא חייב מיתה, אלא נכרת מה’, וממילא מת מוקדם. ותחשב.
[fn:5] ויש לדון, ששם רק צריכים שהוא אפשרי, ולא שהוא מצוי.
