Hi! Here are the different parts of your kuntres arranged into several poems. The poems do change in rhythm and rhyme, so keep that in mind when reading them. Feel free to edit them, but please run by me any edit that changes the rhythm, rhyme, or alliteration.
1.
Very long before the nes,
something drastic did take place:
Sensing they could not withstand
avodah zara’s outstretched hand,
the Rabbis, yelling, ”בייא בייא בייא,“[fn:1]
made its yetzer hara die.
They punctured its pernicious pull,
and prayed until its death was full.
Distanced so from something bad,
prophecy could not be had;
except for Torah shebal peh,
keeping zeh le’umas zeh,
the balance which must be maintained
so that bechirah can sustain.
Chorus:
The Torah takes us very far;
the Torah makes us who we are.
The Torah is our best connection,
and deserves our best attention.
2.
Chochmah yevanis, a wisdom of sorts,
with brilliant deductions, but falling quite[fn:2] short
of chochmas haTorah, was born around then,
preaching a faith in the powers of men.
They only believed what the mind could achieve,
and they rest they would leave as complete make-believe.
Although excellent thinkers, they grasped not the truth-
that the Torah is emmes, and needs not the proof
of a curious mind or the senses of man;
for we still must believe what we can’t understand.
The Greeks never doubted the Torah was wise-
but they only derhered it with physical eyes.
The Torah’s translation, from Hebrew to Greek,
the most well-known language that would speak,
thus prompted a mourning and prompted a fast-
for they thought it a book, and not something more vast.
This was the problem with their view of Torah;
they thought it mere wisdom and not our mesorah.
Chorus:
The Torah is much more than worldly books;
if you already know it- well, still you must look
in its teachings and wisdom, for only through them,
we are who we are and connect to Hashem.
3.
Thus began a struggle ‘tween opposing schools of thought-
the Jews, who kept the Torah; the Yevanim, who did not.
The Greeks soon made gezeiros ‘gainst our yachas to Hashem,
and, quite confused, some Jews would choose, to be a part of them.
And, as they watched their faithful leave, and watched the Greek school grow,
the Rabbis knew just what to do; the Greeks would have to go.
A couple weak and wizened sages, hardly trained to fight,
faced the forces of the Greeks, despite their frightful might.
The Chashmonaim’s victory soon proved the Torah right,
and quickly banished Yavan’s dark, before the Torah’s light.
But lacking was the tahor oil used to light up bright
the golden tall menorah the kohanim lit each night;
for all of it was tamei now, since midivrei chachamim,
the Greeks who touched the oil all were zavos and were zavim.
Respecting what the rabbis ruled, they received a neis-
the finding of a jug of oil that would burn eight days.[fn:3]
Chorus:
The way to keep Hashem’s hashpa’ah burning strong and bright
is to hold the Torah dear, and learn it day and night;
and when, at last, we know it all, we learn it all again,
for through it is our nationhood and yachas to Hashem.
4.
The Greeks are gone, but what lives on
gives a cause for grief.
Their thinkers still, and always will,
challenge our belief.
The Torah looks like any book
filled with earthly wisdom;
we have to know that it has, though,
holiness that’s hidden.
And, as we learn, the schar we earn
brings Hashem’s hashpah;
so let us strive to energize
our limud haTorah.
This essentially summarizes the chorus; there is really nothing to add.
5.
Past events control the present;
time repeats itself.
Thus, a special strength from Heaven
every year is sent
on the days that, long ago,
these events occurred,
allowing us to learn and grow;
it would be absurd
to squander such a splendid gift,
lasting eight days long-
which is what will happen if
it is spent all wrong.
Chorus:
Like flames alight, we’re burning bright,
reaching very far.
We know we’re on our way to Heaven
and eternal schar.
The nes that happened kept our precious
ruchniyus alive,
and allowed for us to reach
the holiness we strive.
6.
The mitzvos are three:
The candles we see,
The Hallel we say,
Al Hanissim we pray.
Their reason’s the same:
to thank Hashem’s name;
so prepare soon to start
to connect in your heart
to Hashem when we pray,
and light every day.
Chorus:
If not for the nes,
in that faraway place,
our lives could not lead
to the radiant deeds
that bring to us schar;
and, thus, we still are
flowing with thanks
for the wonderful nes.
7.
We have to have true gratitude-
feel it in your heart.
Think it through, and say it too,
and speak out every part-
and far after the candle dies,
you will feel its spark.
Chorus:
Hashem has cleared for us a way
leading us to Him.
Thank him every single day
for the Chashmonaim’s win.
8.
The yetzer hara tries each way
to get us all to sin.
We fight against him every day,
and hopefully we win.
Even when he seems too strong
for us to defeat,
know that such a thought is wrong;
the strong lost to the weak.
And, even when we trip and fall,
or rarely do things right,
we cannot stall- we must stand tall-
we must stay strong and fight.
Though you feel you’re very far,
and the road is long,
just make sure to do your part-
Hashem will make you strong.
Though it’s true that sheva yipol,
afterwards be kam,
for in becoming better people,
what else can be done?
Chorus:
We all are soldiers, ordered up,
to the front to fight;
we wage a war that’s long and tough,
with a stubborn might.
And if we fight for long enough,
our fire will burn bright.
* Footnotes
[fn:1] This could be changed to: ”בייא and בייא,“ but I think the original is better.
[fn:2] Note the change.
[fn:3] I do not understand why this part was removed; it seems pertinent and stresses the point that the nes was necessary for a tumah derabanan.
