* בראשית
כתיב שה’ ברא את האדם בצלם אלהים ובדמות דיוקנו. צריך לבאר איך אדם יכול להיות בדמות דיוקנו של ה’ כיון שאין לה’ דמות. נראה לבאר ש"דמות דיוקנו של ה’" אינו אומר "הדמות שיש לה’,” שאין דמות לה’. אלא רצה לומר דמות דיוקנו של אותו איש של ה’, והוא שכמו שנראה ה’ לו, כן הוא האדם. מי שחושב על ה’, מי שמרגיש ה’, להיות אדון כל ולהיות אלהים ממש, הרי הוא דומה לו, ומקיים מה שאמרו חז"ל לדמות לה’, וקונה מדות אלו. להפך, אם אדם חושב על ה’ להיות מי שאינו חנון, אף הוא לא יהיה כן. אז, נמצא שמה שאדם חושב על ה’ יש לו כוח לפעול עליו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן דרשה דומה של "דמות דיוקנו.”
נראה לבאר הסיבה שמהות האדם תלוי בחושבו על ה’ שהוא שאם אדם חושב על ה’ להיות מי שאינו חנון, מדה כנגד מידה, לא יתן ה’ אותו מידה. אז, ה’ נוהג עמו, כמו שאמר גבי יוסף, כאילו אינו חנון, ועושה אותו דומה לה’ שאינו חנון. זה מפני שכשחושב על אדם, נעשה כך.
* נח
נח עסק בבניין התיבה לזמן רב, למאה ועשרים שנה. חז"ל מבארים לנו שרצה ה’ שיעסוק לכל כך זמן כיון שאז יראו אותו בני אדם. ישאלו לו מה עושה, ויגידו להם שיהיה מבול, ושצריכים לשוב. קשה; אחרי מאה שנה, לכאורה, ידעו כבר מה עושה, ואז לא יועיל בנינו.
נראה לבאר שלא היה רק כדי שיאמר להם שיהיה מבול, אלא כדיש יראו שיש מי שעדיין מנסה להשיב אותם. נמצא שהיה חושב עליהם לבני אדם שיכולים לשוב. כיון שכן, יוכלו לחשוב על עצמם לבני אדם שיכולים לעשות רצון ה’. אז, עדיין היה תקווה שישובו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
* לך לך
אברהם לחם עם ארבעה מלכים והיה יכול לכבוש אותם. מבאר גמרא בתענית (כא) שהיה לו עפר מיוחד ש,כשנזרק, היה נהפך לרמחים. קשה איך היה אברהם יכול לבטוח על נס כזה וללחום שלא בדרך הטבע.
נראה לבאר שהיה אברהם חושב על עצמו להיות מי שה’ עמו, ומי שה’ לוחם בעדו. כיון שכן, היה בוודאי נוצח, וממש לא היה לו יכולת שלא לנצח. אז, לא היה סומך על הנס, אלא היה פשוט לו שה’ יעזור בעדו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
* וישב
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן יסוד חשוב: הכל תלוי באיך אדם חושב על עצמו. לכן, חשוב ונצרך הוא לחשוב על אחרים לטוב, שאם יראו איך הוא חושב עליהם, אף הם יחשבו על עצמם כך, ואז יהיו יכולים להתגבר כמו שעשה יוסף.
* תרומה
יודעים שעל הארון היו כרובים. גמרא מפרש שכרובים היו ציורים של קטנים, והיו מחבקים זה את זה להראות חיבת ה’ לישראל. צריך לבאר למה במקום הכי קדוש ובהראת אהבת ה’, נקט קטנים.
נראה לבאר שקטן הוא מי שמגדיל, הוא מי שלא רק די לא להשאר במצבו, אלא רוצה ומנסה להיות יותר גדול, וכמעט בעל כרחו נשתנה ומגדיל. ועוד, שאין קטן מי שהיה לפני שנה. אם היה, לפני שנה, צועק בכל זמן, אולי אחר שנה, יהיה כבר יותר כגדול, ולא יצעוק כלל. כך אומר הכתוב כשאומר "נער ישראל ואהבו.” ישראל הם לעולם גודלים, ולא ממעטים את עצמם מפני מה שחטאו לפני שנה. לכן, הכרובים הם קטנים.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
יש לדון מה ראה אביו ביוסף שגרם שלא היה יוסף חוטא. נראה לבאר שידע יעקב את יוסף רק כשהיה נער (עד שהיה בן שבעה עשר). אז, נראה שראה יוסף מה שחשב עליו אביו לנער, להיות אדם שהוא לעולם משתנה, ולעולם גודל. כיון שראה זה, היה יכול להציל את עצמו מחטא.
* קדושים
אומר קרא, “ואהבת לרעך כמותך.” צריך לבאר מה בכלל מצווה זה. נראה לבאר שאין המצווה רק לאהוב את חברך כעצמך; אין זה שייך, שאין אדם יכול לאהוב את אחר כעצמו ממש. אלא נראה שהדרך לקרא קרא זה הוא שאומר שצריך לאהוב את חברך- ואיך עושה כן? כמותך! תחשב עליו כמו שאתה חושב על חברך. כמו שאדם חושב על עצמו ומכסה פשעיו, כך תחשב על חברך. ואיזה אהבה יש בזה? יש אהבה גדולה בזה, שכשאדם חושב עליו לטוב, יחשב חברו על עצמו יותר לטוב. כיון שחושב על עצמו לטוב, יהיה יותר טוב.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו הוא חשוב מאד. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
* שלח
אמרו מרגלים, “ונהי בעינינו כחגבים, וכן היינו בעיניהם.” קשה איך ידעו מה היו בעיני בני ארץ כנען. שמעתי משום גדול הדור אחד[fn:1] שתחלת הקרא מפרש סוף הקרא. כיון שהיו בעיניהם כחגבים, חשבו שכן היו בעיני מרגלים. מה שאדם חושב על עצמו חשוב הוא, שגורם איך יחשב על דברים אחרים ו,על פיהם, איך ינהג.
רואים יסוד זה מיוסף:
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
* בלק
כשקוראים פרשה זה, חייבים אנחנו להקשות איך היה שבלעם, שזכה לנבואה עצומה, היה איש כל כך רע, ואיך חטא נגד ה’ כל כך. נראה שיש לבאר על לפי קושיא אחרת. הפסוק קורא לבלעם "שתום עין,” שהיה סומא בעין אחד. קשה למה אומר לנו זה; מה לנו ביכולתו לראות.
נראה שלא אומר שהיה ממש סומא, אלא סומא בראיית פרספקטיב שלו, שהיה ראייתו על עצמו סמוי, שלא היה רואת את עצמו לטוב- וזהו מה שגרם שהיה כל כך רע. אף אם אדם מדבר לשכינה, הוא רק יכול להיות צדיק אם יכול לראות בעצמו טוב.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
* שופטים
כשזקנים עוסקים בעגלה ערופה, חייבים לומר, “ידינו לו שפכו את הדם הזה.” קשה מהו ההוה אמינא שהזקנים הרגוהו.
באר האלטר מקאלם שהענין הוא שאילו היו מלווים אותו ונותנים לו מזון וצידה לדרך, היה רואה בעצמו שהוא אדם חשוב כיון שזקני העיר כבדוהו כל כך. כיון שהיה רואה על עצמו חשויבות זה, לא היה נהרג- היה בורח או היה רודף את רודפיו. כיון שלא חשבוהו למכובד וחשוב, לא היה יכול לחשוב כן על עצמו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שאדם חושב על חברו עושה שחברו חושב כן על עצמו, ומה שחושב על עצמו חשוב. לא היה יוסף יכול לסלק את עצמו מחטא עד שהיה יכול לחשוב על עצמו - על ידי דמות דיוקן שלו של אביו- שלא היה לו לחטוא.
* כי תבא
אומר קרא שקללות של תוכחה באים "תחת אשר לא עבדת את ה’ אלקיך בשמחה ובטוב לבב.” קשה איך ייענשו עונש חמורה כזה על עבירה קלה כזה- עשו את המצוות, אבל רק לא עשו אותם בשמחה.
רב משה פיינשטין שאל שאלה עצומה: ידוע שבאו כמה יהודים לאמריקא ומסרו נפשם בעד שבת ובעד יהדותם. למעשה, לא היו בניהם לבסוף יהודים דתיים, אלא התנכרו מיד. צריכים לשאול איך זה קרה.
באר רב משה שקרה כיון שהיו אביהם שמסרו נפשם כל כך אומרים, “איז שבער צו זיין א איד,” ולא, “איז גשמק צו זיין א איד.” כיון שמעו שלא היה שמחה ביהדות, הבנים נתנכרו.
על פי זה, יש לומר שאם אדם לא עובד את ה’ בשמחה, עומד עבודתו להיבטל. כיון שכן, בני ישראל נענשים על זה.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. צריך לבאר איך ראה אותו אביו. נראה לבאר על פי המשך של הגמרא. גמרא ממשיך לומר שאמר לו אותו דמות שאם יחטא, יהיה שמו מחוי מן החושן. קשה, לכאורה, מה לו בזה; אין מצווה להיות החושן. גם לא מסתבר שיוסף הצדיק ירצה בכבוד כזה. אז, נראה שהענין היה שדמותו שהראהו יעקב היה של איש חשק למצוות, איש שהיה שמח במצוות, איש שרצה במצוות לא כיון שצריך, ולא כדי ליטול שכר או כבוד, אלא אך ורק מפני שהם מצוות. כיון שהכיר יוסף שאביו חשב עליו לאיש כזה, אף הוא היה יכול לחשוב על עצמו לאיש כזה, והיה יכול לעמוד כנגד יצרו ושלא לחטוא.
* וילך
כתיב בפסוק, ,ואתה כתבו לכם את השירה הזאת….” תמוה הוא למש שינה מלשון יחיד (אתה) וללשון רבים (לכם). יש להסביר שכל אחד ואחד צריך לכתוב. לכן, אומר לשון יחיד. אומר לשון רבים כיון שבכתיבת התורה, ובאמת, בכל קיום התורה, אפשר שרק על ידי מה שבני אדם אחרים חושבים עליו להיות איש שמקיים מצוות. אם חברו חושב עליו לטוב, ורבו חושב עליו לטוב, ואשתו חושב עליו לטוב, אז- ורק אז- יכול לקיים מצוות. לכן, אומר כאן לשון רבים- מקיים מצווה רק מפני שהוא מורכב ממחשבת כמה בני אדם עליו.
אומר גמרא סוטה שבא יוסף לבית פוטיפער לחטוא. בא לו דמות דיוקנו של אביו, ולא חטא. צריכים אנו לבאר למה לא חטא- מה גרם דמות דיוקנו של אביו.
יש לבאר שלא ראה דמותו של אביו, אלא ראה דמותו של אביו שלו, והוא שראה איך ראה אביו אותו. ראה אביו אותו לאיש תם, לבחור טוב וירא שמים. כיון שראה שכן חשב עליו אביו, היה יכול להתגבר בעצמו שלא לחטוא.
רואים מכאן שמה שבני אדם חושב על אחד עושה שאותו אחד חושב כן על עצמו, ושרק אז יכול להציל את עצמו מחטא כיוסף הצדיק.
ויקהל- נדיב לב
תרומה- כרובים
ספירה- ר’ ויליג
ראה אהרן הטוב בכל
יונתן של leader (חטא משה, ויקח רומח, אליהו)- יהושע היה מיוסף
במקום אשר ישחט את העולה
אספקלריה המאירה
שלש רגלים- דיוקנן (ירושלמי)
* Footnotes
[fn:1] עיין בגמרא פסחים (סוף פרק שלישי).
