** בנים:
ר’ זירא- אהבה
רבי עקיבה ו(רבי) יהושע (בן קרחה)
רב סלא חסידא- רב יוסף
כייליל- אביי
** אחים:
א. בני ר"פ (סיום ------)
ב. בני רבא (-----)
ג. ר"י ורמי בר יחקאל (-----)
ד. רחב"ג (קידושין -----) עם רשב"ג וריב"ג (ברכות כב -----)
ה. ר’ חנניא אחי ר’ יהושע (מנחות? -----)
ו. שמואל ו----- (בכורות (-----)
ז. אייבו ור"ח
ח. מר ינוקא ומר קשישא (ב"מ? -----)
ט. רמי בר חמא ועוקבא בר חמא (ב"ב -----; ברכות -----)
י. בני שמואל (-----)
יא. בני רבי (סוף כתובות -----)
יב. בני ר’ יוסי (שבת -----)
יג. ר"ד בן הורקנוס ואחיו ----- (יבמות -----)
יד. ר’ ברונא ואחיו ----- (ריש ברכות -----)
טו. בני ר"ח (-----)
טז. ר’ יהודה ור’ יהושוע בני בתירה (-----)
יז. רבה בר חיננא ור"ד בר חיננא (ב"ב יג:)
יח. אביי בר אבין ------ (ברכות כט:)
יט. I ר"י אחוה דרב סלא חסידא (ברכות כט:)
כ. ר"א בר אביי ור"ב בר אביי (שבת ד.)
כא. בני ר"א בר אבין (פסחים מט.)-----
כב. הלל ויהודה בני ר"ג
כג. רבנא נחמיה וריש גלותא
כד. בני ר’ אבין )
כה. בני ר’ מתנה
כז. ר"ה ור"ח בר יהודה
כח. רבנאי ורחב"א
כט. רבנא עוקבא ורבנא נחמיא
ל. רב דימי ורב ספרא
לא. נראה שהיה אחיו של רבי תלמידי חכמים
לב. בן רב זביד ור"ש בר רב זביד
לג. מסתמא, שני בני אותו אשה שצער לבבא בן בוטא
לד. רב מרי ורב פנחס בריה דר"ח. (כתובות סא.)
* Footnotes
[fn:1] עירובין צו:
[fn:2] שבועות ו.
[fn:3] כן אמר רשי (שבועות ו. וכן רשי העליון בבכורות נח.). תוס’ בכורות (שם) חולק.
[fn:4] סוף זבחים הוא (“חד ברא לכיליל… ")
[fn:5] הנחתי שהם אחים כיון שר"ג היה נשיא, ומסתמא היה, ביותר, ר"ג הסתם. יש אחרים במנין זה שהם כזה.
[fn:6] פסחים ד.
[fn:7] מצינו שהיה אייבו תלמיד חכם, שרנב"י אמר שמועה מפיו (ריש ברכות -----).
[fn:8] פסחים נד.
[fn:9] שבת כ:
[fn:10] יש לדון אם היה ריש גלותא ת"ח.
[fn:11] שבת כג:
[fn:12] מצינו אז מבמה מהם מי שיש לו אח תלמיד חכם, והיה אביו ת"ח והיה לאביו אח ת"ח, והם כד וכא; שמואל -----, ור"ח -----.
[fn:13] בבא בתרא קנא.
[fn:14] כתובות כא.
[fn:15] יש לדון, שאולי שם רק דן מה שמן, ולעולם היה רק אחד. גם יש לדון אי היו אחים. מה הוחלפו משמע שהיו אחים.
[fn:16] כתובות כא:
[fn:17] חולין צב.
[fn:18] בבא בתרא (קסד:)
[fn:19] חולין (ו.)
[fn:20] ברכות לח.
[fn:21] נדרים סו:
