א.ד.ר.- אהרן דב רייכמאן (זמן קיץ; ברכות- גלגל שלישי- ל: ; שבת- הוספות- מסמסמסממ; יבמות- הוספות- כד. ; מרגינליא; ברכות- הוספות (II; חולין- גלגל רביעי- מג. ;
א.י.כ.- אהרן ישעיה כהן (בבא בתרא- הוספות)
א.י.ש.- אברהם יצחק שטיין (ב"מ- הוספות- סג. ; חגיגה- הוספות; מרגינליא- דף א; יבמות- גלגל שלישי- כב. ;
א.ל.י.- אברהם ליב ירקאוויץ (ב"ב- הוספות (II) ;
א.מ.ו.- אברהם מרדכי ווינער (חולין- גלגל רביעי- לב. ;נדרים- גלגל רביעי- עה.; פסחים- גלגל רביעי- פה:; מרגנליה; גליון הש"י (זבחים- צג:); בבא בתרא (גלגל רביעי)
א.ס.- אהרן הלוי סאלאוויציק (שבועות- גלגל רביעי- כב:
א.ר.- אברהם ריבאק (יבמות- גלגל שלישי- כו., מב:. נב.; רש"י עירובין- גלגל רביעי- ק:
ב.ל.- בנימין ליפשיץ (סנהדרין- כג.)
** -
גר"ק
הגאון הרב קלמן (תמורה- גלגל רביעי- כ.
דר. בראל- בבא בתרא (נב.)
ט.ק.ק.- טוביה קליין-קאפמאן (ברכות- הוספות ;סכוה, הוספות; סוטה- הוספות
י.מ.ו.- ישראל מאיר ואלף (צדי צדדים על יש נוחלים נלמדו עמו; שיחתא דשי על פאה נלמד עמו; עירובין (גלגל רביעי- רש"י- עט:); מרגנליא; ב"מ (הוספות)
נ.א.- נפתלי אולדאק (ברכות- גלגל רביעי- מה.
ע.י.ג.- עזריאל יהודה גרינברג (מרגנליא
ר.ד.ו.- רב דוד וויליג (ברכות- הוספות ;יבמות- גלגל שלישי- נב.; שבועות- גלגל לשלישי- טז.; סוכה- הוספות; מרגנליא
ר.י.ב.- רב יצחק ביליצקי (מרגנליא
ר.י.י.- רב יוסף יפרח (מרגינליא)
ר.מ.ש.- רב משה שטיין (יבמות- גלגל שלישי- ל. ; מרגינליא; זבחים (רש"י)- גלגל רביעי- טז: מנחות (גמרא)- גלגל רביעי- י.; גיטין (ח"ק (2))
ר.ע.ו.- רב עקיבא ווינער (יבמות- גלגל שלישי- כו. ;
ר"ג שפיץ- רב גבריאל בן רב שלום שפיץ (גליוני השי- ביצה- י.)
ר"ק- רב קלמן (מרגנליא
רש"ש שליטא- רב שלום שפיץ (יומא דדינא; שבועות- גלגל רביעי- ג: חרב אל הבדים- ב"ב- קיץ; זבחים- גלגל רביעי- קא:’ קב.; מנחות- גלגל רביעי- נג.; מרגנליא
ש.ל.- שמואל לאוב- למדתי עמו: חולין (שני), בכורות (שני, חצי שלישי, חצי אחר של רביעי), מעילה (שני), תמיד (שני), ערכין (שלישי), תמורה (שלישי), כריתות (שלישי), יבמות (שלישי), גיטין (שלישי), שבועות (שלישי, חצי רביעי), נדרים (רביעי), נזיר (רביעי)- (יבמות- גלגל שלישי- סא: ;
