איסורי שבות:
מקור האיסורים:
חוץ מן השלושים ותשע מלאכות שאסורים מדאו' באיסור סקילה, יש איסורים הנקראים ”שבות.“ לכאו’, מה שמייחד אותם לכלל אחד הוא שעשיית כל אחד מהם מונע שביתה ומנוחה של שבת.
מדברי פסוקים, מדברי חז“ל, ומדברי הראשונים, מצאנו שבע מקורות לאסור שבות:
1. מכילתא במשפטים דורש אותו מ“ובכל אשר אמרתי אליכם תשמעו.“ כיון שכבר כ’, ”לא תעשה כל מלאכה“ לאסור מלאכת שבת, יכולים לדרוש מכאן איסור שבות.[fn:1]
2. מכילתא בכי תשא דורש אותו מ“את שבתותי תשמרו.“
3. ט“ז ובית יוסף מביאים סמ“ג שמביא מכילתא שדורש אותו מ“כל מלאכה לא ייעשה,“ שמרבה אף עשיית מלאכה על ידי אחר (שהוא שבות אחד[fn:2]).
4. אבל, ע’ בגר“א שלא גורס כן במכילתא. אלא, גורס שמזה דורש מכילתא שמותר לישראל לומר לגוי לעשות מלאכה לו, ורק אסור לישראל עצמו לעשות אותו. ערוך השולחן מביא ראיה מהמשיך המכילתא לגי’ גר“א. שם, רבי יונתן אומר שלא צריכים אותו דרשה, שיש ללמוד אותו ממה שגבי שבת אין איסור לגרום שגוי יעשה מלאכה. ממה שמוכיח מכן שלא צריכים הדרשה, מוכרח שהדרשה היה אותו אותו דבר, והוא שאין איסור לגרום שגוי יעבור.
5. ויש להעיר על מקור זה שהקרא  והמכילתא הם לגבי יו“ט. אז, לכאו’, הוא רק מקור גבי יו“ט.
6. רמב"ם, כשמבאר דיני שבות, מביא מקור מפסוק "תשבות.“
7. יש איסורי שבות שמפורשים בדברי נביאים:
  1. ישעיה מזכיר כמה איסורי שבות בפסוק: ”אם תשיב משבת רגלך עשות חפציך ביום קדשי וקראת לשבת ענג לקדוש יהוה מכבד וכבדתו מעשות דרכיך ממצוא חפצך ודבר דבר.“
  2. נחמיה מזכיר שבות של מכירה.
8. כמו שנבאר לקמן, בע“ה, ריטב“א מביא רמב“ן שמוכיח איסורי שבות ממה ששבת נקרא יום שבתון ויום מנוחה. איסורי שבות מונעים אותו משביתה וממלאכה.
אז, נמצא שיש שש מקורות לאיסורי שבות. לכאו’, צריך ביאור למה צריכים כל מקורות אלו. אם הם רק אסמכתות, יש לומר שאין ייתור, כיון שאין זה דרשה אמיתית, אלא הוא רק קרא שמשמע דין זה קצת. אז, יכול להיות הרבה דינים שמשמעים קרא אחד, ומביאים כל אחד לאסמכתא. גם יש לומר שחולקים זה על זה. ויש להעיר ששלש מהם באו מן המכילתא. דחוק לומר שהם שני תנאים בתוך המכילא. גם יש להעיר שאי אפשר לדחות מקור חמישי, שהרי הוא קרא. אבל, עדיין אפשר לומר שלא לדרוש הפסוק כמו שדורש גמ’ שלנו, ואז לא יגלה (על כל פנים מקור ראשון שבו) אותם איסורי שבות. בערוך השולחן העיר שיש שני מיני שבות- יש שהם איסורי מעשה (כמו למכור) ויש שהם איסורי הגרמת מעשה (כמו אמירה לעכוו“ם). צריכים שני פסוקים לשני מינים אלו. כמובן, עדיין יש ארבע פסוקים מיותרים. (לקמן, בע“ה, גם נביא הוספה על דיון זה.)
סוג האיסור:
רש"י בעירובין (צז:), וכן משמע מרש"י בכ“מ אחרים, סובר שאיסורי שבות הם איסורים דרבנן. רבנן אסרו מלאכות אלו, וכל המקורות שהבאנו הם רק אסמכתות. כמו כן נראה מתוס’ בשבת (יט.). אבל, ריטב“א כ’ בשם הרמב"ן (בשם ”קבלה בידינו“) שאיסורי שבות אינם כאיסורים דרבנן, אלא כאיסורי תורה. מוכיח כן מן המקור הששי שהבאנו. תורה קורא לשבת יום של שביתה ויום של מנוחה. הרי, אם אדם עובר על איסורי שבות- למשל, עוסק בסחורה כל היום- אין מנוחה ושביתה לו באותו יום.
אמירה לעכו“ם:
האיסור לכתחילה:
אחד מאיסורי שבות הוא אמירה לעכו“ם, והוא דיבור לעכו“ם לעשות דבר שאסור לעשות בשבת. בתוך איסור זה יש שני איסורים, יש איסור לכתחילה (לומר לגוי לעשות לו מלאכה) ויש איסור בדיעבד (להנות מאותו מלאכה, כמו שנבאר בע“ה).
באיסור זה, יש שני זמנים החשובים- זמן הדיבור, וזמן עשיית מלאכה. ההלכה הוא שאם אחד מהם שבת (וכש“כ אם שניהם שבת) האמירה אסורה. אז, אסור לומר לגוי בשבת לעשות מלאכה במ“ש, ואסור לומר לגוי בע“ש לעשות מלאכה בשבת, ואסור לומר לגוי בשבת לעשות מלאכה בשבת.
לא בכל ציור שזמן מלאכה בשבת נאסר האמירה, אלא רק נאסר אם נחשב שהגוי עושה אותו בשביל היהודי, ולא בשביל הרווחה של עצמו. לכן, צריכים לדון בגדר ההרווחה, יש, בין הכל, חמש אפשריות. הראשון הוא שגוי לא מקבל כלום. אז, פשוט שהוא אסור. השני הוא שגוי מקבל את הכל, ולא נותן כלל לישראל. אז, פשוט שהוא מותר. אבל, יש שלש אפשריות של הרווחת גוי שצריכים לדון בהם. אפשר שמקבל כל ההרווחה (ונותן לישראל דבר אחר), ואפשר שמקבל חלק מן ההרווחה (ונותן לישראל חלק האחר), ואפשר שלא מקבל מן ההרווחה (ישראל נותן לו דבר אחר). בשני ציורים הראשונים, מותר, כיון שמרוויח לעצמו[fn:3], ובשלישי תלוי בזמן שכירתו. אם גוי צריך לעשות המלאכה בשבת, אז אסור. אם יכול לעשות המלאכה בזמן אחר, אז חולקים אחרונים. יש אוסרים, שלא ניכר שמקבל גוי שכרו בשביל זמן רב, ולא בשביל כל יום ויום. אבל, יש מתירים, שעושה המלאכה בשביל עצמו- כדי שלא יצטרך לעשות אותו לאחר זמן. להל’, ערוך השולחן פוסק כהאוסרים..[fn:4]
נמצא, אז, שיש בכלל זה שני איסורים- איסור לעשות דבר שגורם שמלאכה נעשה בשבת, ואיסור לעשות דבר בשבת שגורם שמלאכה נעשה. לפעמים, עובר על שניהם (כשגורם בשבת שמלאכה נעשה בשבת).
הוסיפו רבנן שני גזירות על איסור שני. הראשון הוא שאסור להנות ממלאכה שעשה לו גוי בשבת. לקמן, בע"ה, נבאר דין זה. השני הוא שאסור לגרום לגוי לעשות מלאכה באופן שנראה שעושה אותו לישראל. אז, במה שידוע שהוא של ישראל (כמו אם כבר קנה אותו לפנני זמן), אסור לגרום לגוי להשתמש במה שלא רגיל לשכור (כמו תנור ומרחץ שלא כבר השכיר), אלא רק במה שרגיל לשכור (כמו שדה וריחיים), אם הוא בפרהסיא וידוע שהוא שלו. בגדר ”פרהסיא,“ יש שלש מינים: יש תיקון מחובר לקרקע, יש מה שנעשה לצורך מחובר לקרקע, ויש תלוש. מחובר לקרקע נאסר אא“כ אין יהודי שגר בתוך תחום של מקום מלאכה. מה שנעשה לצורך מחובר לקרקע נאסר אא“כ הוא בעיר אחרת מעיר שגר בו הישראל. תלוש מותר כל זמן שאינו בבית היהודי. בגדר ידוע שהוא שלו, דנו אחרונים אם מותר כשבונים אותו בעיר שלא גר. אבל, חוץ מזה, יהיה אותו היתר קיים כשקנאו מיד לפני כן.
אז, בין הכל, יש שני איסורים- לומר לגוי לעשות מלאכה בשבת, ולומר לגוי בשבת לעשות מלאכה. על השני, יש שני אופנים שהוא אסור- אם גוי עושה לישראל (דהיי’, שגוי לא מקבל שכר של תוצאת המלאכה או שמקבל שכר על מלאכה שצריך לעשות בשבת) או שנראה שהגוי עושה לישראל.
מצאנו שלש (ואולי אף ארבע) טעמים לאיסור:
1. רש"י בעבודה זרה (טו.) כ’ שאיסורו הוא משום ”ודבר דבר,“ דהיינו איסור השבות על דיבור על דברים שהם אסורים לעשות בשבת. זה רק אוסר אמירה לעכו“ם שיש בו זמן דיבור בשבת.
2. רש"י בע“ז (כב.) כ’ שאיסורו הוא מפני שנראה כשליח של ישראל. אינו, באמת, שליח של ישראל, כיון שאין גוי יכול להיות שליח, אבל נראה כן לבני אדם, ולכן אסור להגיד לו לעשות מלאכה בשבת. זה רק אוסר אמירה לעכו“ם שיש בו זמן עשיית מלאכה בשבת. (אז, רש"י צריך שני המקורות שלו.)
3. רמב"ם כ’ שאיסורו הוא כדי שלא יהיה המלאכה קל בעיני הישראל.[fn:5]
4. אולי לפי ריטב“א בשם רמב"ן שהזכרנו לעיל, הוא אסור כיון שהוא מבטל שביתה ומנוחה.[fn:6]
כלול בתוך דין זה הוא גם חיוב למחות בגוי שעושה לו מלאכה, אף אם לא שאל לגוי לעבוד לו. יש שני ציורים שבו חייב למחות. חייב למחות אם גוי עובד לו בפרהסיא. גם חייב למחות לו אם הגוי עושה המלאכה לו כדי שישראל יהנה, ולא לעצמו. אז, אם מגיע שכר לגוי[fn:7] (לכאו’ באופן שבארנו לעיל), א“צ למחות לו, כיון שהגוי עושה כן בשביל השכר.[fn:8]
הדין בדיעבד:
בענין דין בדיעבד, יש שני דברים שיוצאים מאיסור זה, ועל שניהם צריכים לדון.
דבר ראשון הוא התוצאה של המלאכה עצמה. אז, למשל, אם אמר לגוי לבשל חפץ, צריכים לדון על דין של אותו חפץ שבשל הגוי. זה תלוי באיזה זמן הוא המחשיב אותו להיות אסור- זמן אמירה או זמן מלאכה. אם רק זמן אמירה בשבת, המלאכה שעשה הגוי הוא מותר. אם זמן מלאכה היה בשבת (בין אם אמר לגוי, בין אם הגוי עשה לישראל מעצמו), אינו מותר מיד, אלא אסור הוא עד קצת אחר מוצאי שבת, אחר שהיה אפשר להכין אותו כבר לאחר שבת. דין זה גזי’ הוא, שלא ישתכר ממלאכת הגוי, שמא יגיד לגוי לעשות אותו.
דבר שני הוא השכר שבא ממה שגורם לגוי לעשות מלאכה. לפעמים, אדם מרשה לגוי לעשות מלאכה בדבר שהוא שלו, וגוי מקבל התוצאה, ונותן שכר לישראל. אז, אף על שכר זה צריך לשאול אם הוא מותר או אסור. איסור זה בדיעבד הוא רק כשזמן מלאכה הוא בשבת, ולא כשזמן אמירה הוא בשבת. ההלכה הוא שאם נתן אותו רק לשבת (דהיינו, שקצב שכר לשבת- ואף אם משכיר אותו להרבה ימים, אלא שקצב שכר לכל יום ויום), אז השכר אסור, כיון שקבלתו הוא כעין עשיית מקח וממכר בשבת.
* Footnotes
[fn:1] לקמן, יבואר, בעזרת ה’, אם זה דרשה מדאורייתא או רק אסמכתא. מה שמוכיח שהוא קרא מיותר משמע שהוא דרשה, שמצאנו הרבה אסמכתות בגמ’ שאינם מיותרים. צריך לדחות שרק מצאנו אסמכתות שיש בהם דרשה אחרת. אבל, בא להוכיח שזה לא נצרך לפשטות שלו. אילו היה נצרך לפשטות שלו, לא היה משמע שום דרשה, ולא היה יכול להיות אף אסמכתא.
[fn:2] לכאו’, שאר האיסורי שבות נלמדים ממנו, כמו שבארנו, שיש להם יסוד אחד. (וגם ע’ לקמן, בביאור למה צריכים הרבה פסוקים).
[fn:3] כמו שבע“ה נבאר לקמן, יש איסור אחר, והוא, לפעמים, יאסור אותו מלקבל אותו שכר. וע’ לקמן.
[fn:4] יש לדון מהו הדין אם מרוויח בשני אופנים, שאז נמצא שאופן המותר הוא רק מקצת מן הסיבה. ותחשב.
[fn:5] נראה שזה יכול להסביר איסור כשזמן דיבור הוא בשבת ואיסור כשזמן מלאכה היא בשבת. לכאו’, בשניהם, יש קלות של שבת, שבאחד נמצא שבשבת גורם מלאכה ובשני נמצא שגורם שמלאכה נעשית בשבת. (אבל, אם כן, קצת צריך ביאור למה אין הגרמה אסור בע“ש, מאותו טעם. אולי, אז, צריך לומר שאין גרמת מלאכת שבת אסור, שזה לא עושה אותו קל בעיניו. אלא, בזה מודה לטעם של רש"י (יהיה טעם שני). נראה שאולי אפשר לומר שכשצריך בחירת אדם אחר, חושב על זמן מלאכה להיות שבת, וחושב על עצמו שגרם מלאכת שבת. אבל, אם מוכרח הוא לקרות- שכן הוא, בדרך כלל, כשגורם אותו לפני שבת- אינו כן, אלא חושב על זמנו להיות בערב שבת, ולכן אינו עושה את האיסור קל בעיניו. ותחשב.
[fn:6] עיין במה שכתבנו בהערות בסוף.
[fn:7] אף אם ישראל לא הבטיח לו שמגיע לו שכר, אלא שמסתבר שגוי הניח שמגיע לו שכר (כמו אם מציל חפץ של הישראל) אין צריכים למחות בו.
[fn:8] מגמרות בביצה נראה שאף במלאכה שלא צריך למחות, אסור להנות ממנו בשבת.
[fn:9] אני חושב שלהלכה כולם בסקילה. אבל, ע' בשבת (ו:), שיש שיטה שיש אחד מהם (ולא ידוע לאיזה אחד מהם) שאין לו חיוב סקילה. כמו כן, מצאנו שיטה בתנאים בשבת (ע.) שבהבערה אין חיוב שריפה. כן סובר רבי יוסי, ודורש אותו ממה שקרא מזכיר אותו, שכ', "לא תבערו אש בכל מושבותיכם." (כמובן, אפשר לומר ששני השיטות סוברים דבר אחד.) וצריך לעיין אם מה שאין לו סקילה יש לו חיוב כרת. יש נפק"מ לענין חיוב קרבן (וגם, אז, יש תוצאה באם נוכל להוכיח מן הסתם משנה שמחייב קרבן על כל אב מלאכה).
[fn:10] מה שיש דבר אחד שמייחד אותם מוכח ממה שיש להם שם אחד. כמו כן, מה שיש להם מקור (או אסמכתא) אחד, כמו שנבאר לקמן, מוכיח שיסודם שווה.מה שכתבנו שמייחד אותם נראה משם שלהם, שמשמע שהם באים כיון שהוא חייב לשבות, וכן מביאור שנביא לקמן מן הריטב“א בשם הרמב“ן. ועיין שם.וצריך על’ לקמן, במה שנכתב בע“ה בביאור טעם לאיסור אמירה לעכו“ם שהוא שבות, שאולי יהיה מוכרח שאף שקרק’ זה מאחד אותם, אין קרק’ זה סיבה לכולם (ואולי אינו סיבה לאף אחד מהם). כמובן, אולי זה לא ייתכן לפי ריטב"א ורמב"ן, כמו שנבאר.
[fn:11] לא פשוט לי איך מכילתא דורש כן מאותו קרא. הרי, הקרא אומר, ”כל מלאכה לא ייעשה,“ שמשמע שלא טוב שמלאכה נעשה, ולא שלא טוב שעושה מלאכה. אז, היה יותר מסתבר לרבות איסור לומר לגוי לעשות אותו, ולגרום אותו להיעשות. דחוק לומר, אבל אולי צריכים לומר, שעיקר כוונתו אינו לדרוש מ“לא ייעשה,“ אלא לדרוש ממה שנאמר מיד לפניו, שהוא "לכם,“ שמשמע שהאיסור הוא רק לבני ישראל. מצאנו שתוס’ סובר (ע’ בכתובות (כט.) ובמקומות אחרים) שלפעמים גמ’ יביא תחילת המקרא כשמכוון לדרוש מסופו, אבל לא ברור מזה שיביא סוף הקרא כשרוצה לדרוש מתחילתו. וע’ במה שנבאר בדרשה זה לקמן בע“ה.
[fn:12] יש להעיר שלפי הגר“א נמצא שתורה התיר אותו בפירוש. אז, ק"ק איך רבנן אסרו אותו. יש לומר שלא אומר שקרא התיר אותו, אלא מביא מזה שקרא שאוסר לא הזכיר אותו. ויש לדון, שהיה לו להביא כל הקראי שאוסרים. אולי כוונתו לומר שאף קרא זה, שקצת משמע- כמו שבארנו לעיל- שאסור לומר לגוי לעשות מלאכה, אינו משמע כן די. (אם כן, זה יבאר מהו הדרשה לפי הגר“א. אין דרשה להתיר, אלא קרא רק אומר שאין דרשה לאסור, שאינו משמע כן די. ותחשב. (וצל“ע בתחילת פרק שני של פסחים, במשמעות של מילה כעין ”ייעשה.“) וצריך על’ במה שנכתב לקמן, בע“ה.
[fn:13] לכאו’, לפי גי’ הגר“א, פשוט שאין איסור שבות מדאו’. ע’ לקמן, שנדון בזה קצת.
[fn:14] גם יש להעיר שמשלונו (שאומר שאינו צריך) מוכח הוא שדרשה הוא, ולא רק אומר שאין דרשה לאסור. ותו"ת.
[fn:15] באמת, לכאו’ הגמ’ אומר כן בפירוש בכמה מקומות (ע’ בשבת (ח:) ובעירובין (ל:, לב:, לד:, לה. ועח:), ובב“ק (פ:)). בע“ז, ע’ לקמן, במה שנכתב כשנדון בשיטת ריטב“א בשם הרמב“ן.
[fn:16] לא כל כך ברור לי מהו כוונה של זה. לשון הערוך השולחן (איני יודע אם זה לשון הריטב“א) הוא: ”קבלה בידינו ששבותי שבת אינם כשארי איסורי דרבנן, אלא הם כאיסורי תורה. וראיה לזה, דאם לא כן, אלא נאמר דמן התורה אינו אסור אלא מלאכה ממש, אבל משא ומתן מותר, וכי לזה יקרא יום מנוחה ושביתה, שכל אחד יעסוק במסחרו וישב בחנות ויקנה וימכור? ואין זה אלא מן המתמיהים! אלא עיקר העניין הוא, דעל מלאכה ממש – חייבה התורה סקילה, ועל השבותים - לא חייבה סקילה, אבל איסורן איסור גמור כאיסור תורה.“ מצד אחד, ראייתו משמע שהוא דין דאו’. כמו כן משמע מסוף לשונו, שבחילוקים בין זה לשאר מלאכות, רק מזכיר מה שאין בו חיוב סקילה. אבל, לשונו, כשאומר שאינו כאיסורי דרבנן (ולא אומר שאינו מן איסורי דרבנן), וכשאומר שהוא כאיסורי תורה (ולא אומר שהוא מן איסורי תורה), משמע שאינו ממש איסור תורה, אלא מה שהוא דומה לאיסור תורה.לכאו’, יש ראיות חזקות שאינם איסורי תורה. הזכרנו שיש כמה גמ’ שכמעט אומרים שהם מדרבנן, כיון ששימשו בלשון גזירת רבנן עליהם. כמו כן, יש הוכחה מגמ’ בפרק כלל גדול (עג.). אבל, אם רצה לומר שאיסור דרבנן הוא, קשה מהו כוונתו כשאומר שהוא כאיסור תורה. גם יש להעיר שאם איסור תורה הוא, ומקורו הוא משביתה, לכאו’ אין ציווי לזה. תורה אומרת ששבת היא יום מנוחה. מזה מובן שצריכים לשבות, אבל אין זה ציווי לשבות. אולי זה די, ולא צריכים ציווי יותר מזה, כיון שמובן מן הקרא שיש חיוב. גם יש לומר שזה מוכיח שאחד מן המקורות שלעיל הוא מקור אמיתי, ואותו מקור הוא, אז, הלאו. גם נראה שיש לומר שאין הכי נמי, אין ציווי, אלא הוא דין שתורה גילתה בלי ציווי. אולי זהו כוונתו כשאומר שהוא כעין דאו’, שאינו ממש דאו’, כיון שאין ציווי. אבל, עדיין צריך לדון איך להגדיר אותו דבר. צריך ביאור אם אנו חייבים לעשות אותו מחמת התורה או לא. אם חייבים, אז עדיין קשה לשון ”גזרו.“ אם לא חייבים, אז נמצא, לכאו’, שהוא שווה לתפלה או כדומה, דהיי’ דין דרבנן עם סיבה מדאו’. (יכול להיות כן, אבל לשונו לא משמע כן.) ותחשב על כל זה.
[fn:17] ויש להעיר שצריך לדון אם נאסרו מחמת מה שמבטלים שביתה או שנאסרו מחמת איזה טעם אחר (וההוכחה שנאסרו בא ממה שתורה קורא לשבת יום של שביתה). ע’ לקמן, שנבאר טעם של איסור אמירה לעכו“ם. יש להעיר שאפשר שלפי רמב"ן וריטב“א מוכרח להיות מפני ביטול השביתה. (וצריך לעיין אם מוכרח שריטב“א אומר כן בכל איסורי שבות או רק במקצת מהם. ותו"ת.)
[fn:18] יש להעיר שלכאו’ שאר המקורות- ובכללם, מכילתא- הם קשים לרמב"ן, שכבר יש לו מקור ממה שנקרא יום מנוחה. אם עדיין דין דרבנן הוא, יש לומר שיש הרבה אסמכתות, והוא הביא אחד מהם. (ויל“ד אם זה יהני לשיטת ריטב“א בביאור ענין אסמכתא.) לפי מה שצדדנו שצריכים ציווי, ואז קרא של מנוחה מגלה על אלו שהם ציווים, מובן הוא מאד.
[fn:19] כמו שנראה, אולי אינו איסור אחד, אלא יש בו הרבה איסורים.
[fn:20] עיין בערוך השולחן, שבביאור ציור שני כ’ שהנאתו מותר כיון שרק בא לו ממילא. צריך לחשוב על כוונת זה. לכאו’, הייתי אומר בביאור הדין (ואולי לכך כיוון ערוך השולחן) שכל האיסור הוא רק במה שגוי מהנה בשבילו, והרי אין זה בשבילו.) אולי ציור ראשון שכוון להגיד הוא שצריך לעשות דבר בכל יום ויום, במשך שנה. נראה לי שזה אמת.
[fn:21] ואם תאמר כיון ששדה הוא רגיל באריסות, ולכן מותר באריסות, יהיה מותר אף כאן בשדה, שיחשבו שבאריסות נותן אותו לגוי. ויש לומר שרק חושבים כן אם רואים שהאריס נוטל פירות, כמו שנבאר לקמן. אבל, כאן, כמובן, לא מקבל פירות, ואז לא נראה כאריסות.
[fn:22] ואם תאמר אף כל אריסות נראה כן. ערוך השולחן מסביר שרואים בני אדם שנוטל פירות, ואז מכירים שאריסות הוא. מעניין, שלכאו’ רק בסוף נוטל את הפירות, ולא בשבת. אולי זה די, אף שכולם טועים למקצת הזמן ומקצת טועים לכל הזמן.
[fn:23] זה לא כל כך פשוט לי. מתחילה, ערוך השולחן כ’ כמעט בפירוש שלא כזה, אלא שלעולם אסור, אבל שוב כ’ כן בנוגע לקבלנות (שהגוי עושה כל מה שצריך להיעשות ומקבל סכום כסף). לכאו’, ציור זה יהיה כולל כל ציור שישראל מקבל התוצאה, אלא שנותן לו שכר. וצריך ביאור.
[fn:24] אין החילוק כל כך פשוט לי. וצריך לחשוב.
[fn:25] יש לדון למה אין זה בכלל גזי’ לגזי’.
[fn:26] הנחתי שהיתר זה הוא רק בציור שנראה שישראל עשה אותו באופן איסור. אבל, היה אפשר לומר שכל הבעיה הוא שנראה כמו שליח (כמו שקצת משמע מרש"י, כמו שנפרש לקמן). אולי, אז, אם אינו ידוע שהוא שלו, יהיה מותר בכל ציור. ותו"ת.
[fn:27] כן כתב ערוך השולחן. אבל, זה לא ברור לי, שלעיל בארנו (מן ערוך השולחן) שמה שאין חוששים שנראה כאיסור גבי אריסות הוא שרואים שמקבל את הפירות. אם כן, כל אריסות יהיה מותר. צריך לומר אחד משני דברים. אפשר לחלק בין דברים אלו- לא במה שהוא עומד לאריסות, אלא במה שיכולים להכיר את האריסות, שיכול להכיר מה שמקבל. ויש לדון אם זה מסתבר (לחלק ככה), אבל לא משמע כן מלשון ערוך השולחן. יותר נראה לומר שצריך שני דברים, שצריך מה שעומד קצת לאריסות, וצריך שיש מוכיח לאריסות. לכאו’, ההסבר יהיה או שמה שמקבל פירות אינו ראיה ברורה, כיון שאולי בחר אחר כך לתת לו פירות, או במתנה או בשכרו; או שמה שמכירים בני אדם שנותן פירות הוא רק מפני שמסתכלים בזה, שלא יודעים באיזה אופן הוא משכיר. (שוב נ“ל שאולי גם יכולים לומר שמה שלא חוששים לזמן עד שרואים קבלת פירות הוא מפני שהם מסופקים כל אותו הזמן, שלא יודעים איך קבל אותו, בקבלנות או בשכירות. אז, באלו, שמסתבר שקבל אותו בקבלנות, יהיה אסור מחמת אותו זמן קצר. ותו"ת.)
[fn:28] אין זה כל כך ברור לי, שהרי ערוך השולחן התיר מרחץ פרטי בתוך בית היהודי. לכאו’, מרחץ מחובר לקרקע. וצריך לחשוב. אולי ענין מחובר לקרקע הוא רק כשבונה במחובר. כן נראה לי.
[fn:29] ואם תאמר הרי להלכה כל מה שנאסר מחמת מראית עין אסור אפילו בחדרי חדרים. ט“ז תי’ שזה רק באיסורים דאו’. אבל, איסור זה מדרבנן הוא, ולכן מקילים להתיר אותו בחדרי חדרים.
[fn:30] כן מניח ערוך השולחן בפשיטות. לא מבאר למה הוא נכון, אבל לכאו’ הענין הוא שיש כל כך הרבה בני אדם, ואז מאד רע הוא שיהיה נראה כשליח, ואז צריך לעשות שלא נראה כשליח.
[fn:31] אין לי מקור מפורש לזה, והיה אפשר לומר שהוא אסור עד כדי שיגיד לגוי במ“ש ויעשה, אבל לא נראה כן, ממה שלא הוזכר אותו איסור.
[fn:32] אם כן, ק"ק למה אסרו אותו אם לא אמר לגוי, אלא הגוי עשה בעצמו לו.
[fn:33] אין לי מקור לזה, אבל נראה לי שהוא נכון. וצריך לעיין.
