1.
Read this little rhyming note,
and tell me if you find
any giant paper clips;
they probably are mine.
2.
Cen you please
guess who I am-
who wrote this note
in short iamb?
3.
You did not learn
enough today!
Things cannot
go on this way!
Make a change
and make it fast!
This situations
cannot last!
4.
Can you guess me?
Can you, please?
Here’s a hint:
I often sneeze.
5.
This poem’s not my greatest-
it just might be my worst.
This poem hold its message
like a boxer holds a purse.
6.
Do you remember me?
Have you forgot
those whimsical signs that
you laughed at a lot?
7.
For many months,
I wrote the rhymes;
but now I’m gone-
I’ve had my time.
Won’t you keep
the flame alive?
Won’t you scrawl
a silly sign?
8.
This poem indicates a name
known to greatness, not to fame.
Do you know me? Ponder hard.
Let me tell you: I’m the bard
9
What are you doing,
you black hatted bum
your lomdus is wacky
your svaros are dumb
your knowledge is tiny
your feelings are fake
go learn some real learning
for dear heaven’s sake!
10.
Long ago, you had a friend
of brilliant mind and clever pen
Think it through, now- think again;
can you think who I intend?
11.
Hey there, buddy[fn:1], how are you?
Feeling happy? Feeling blue?
Well, I'm a note, that's all I am
so I don't really give a da…
12.
I know not who you are,
nor ever shall I learn;
for I am very far,
and never shall return.
13.
Read this little poem
and smile a little smile;
then go back to your learning-
but think of me a while.
14.
Take this paper,
read it slow.
Recall the boy[fn:2]
you used to know.
15.
Do you know me?
Yes, you do!
Your dearest closest
friend Shaoool!
16.
Here’s a little note from me,
to try to say goodbye;
a pasing wave, a fleeting smile,
and a silent sigh-
and this little note from me,
to try to say goodbye.
17.
Let me write my final lines
and write my final poem
cross my t’s and dot my I’s
then wander off from home
18.
If you sang the nussach wrong
that would not bother me.
If you droned a moaning song
I’’m happy as can be.
I really would not mind a bit
if you sang way off key;
because today, I will not stay,
for davening, you see.
* Footnotes
[fn:1] reader
[fn:2] The friend
