כדי לעשות לוח, רק צריך לדעת חמש דברים:
1. זמן הקבוע מן התורה למועדים.
ר"ה הוא בא' (וב') תשרי, יוה"כ בי' תשרי, סוכות בטו' לכא' תשרי, ושמנ"ע בכב' תשרי. חנוכה הוא כה' כסלו לשמנה ימים, ופורים הוא יד/ טו אדר (הקרוב לפסח). פסח הוא טו עד כא ניסן, ועצרת ו סיון. יש ארבע צומות: ג' תשרי, י' טבת, יז' תמוז, וט' אב. כל א' בחדש הוא ר"ח, וכל יום שביעי לשבוע הוא שבת בראשית.
1. מין השנה:
יש שני פקטורים בביאור מין השנה:
  1. שלם, כסדרו, או חסר. יש שני מיני חדש, יש חסר (בן כט ימים) ושלם (בן ל יום). רוב החדשים קבועים, שכל ראשון שלם וכל שני חסר. אבל, חשון וכסלו לא קבועים. אם שניהם שלמים, נקרא שנה שלמה, אם שניהם חסרים, נקרא שנה חסרה, ואם אחד שלם, נקרא כסדרו.
** מנין הימים שבין ר"ה לר"ה
הדרך לדעת את זה הוא להביט אל
.
  1. פשוטה או מעוברת. ברוב חדשים, יש יב' חדשים. שנה כזה נקרא שנה פשוטה. יש שנה שיש בו עוד חדש שלם, ונקרא שנה מעוברת.
** גו"ח א"ד ז"ט
הדרך לדעת את זה הוא כך: יש מחזור של יט' שנים. בתוכו, יש יב' שנים פשוטות וז' שנים מעוברות. הסימן לשנים מעוברות הוא
(שהוא שנה 3 ו6 ו8 ו11 ו14 ו17 ו19). הוא כל שלש שנים, חוץ מאחר השני מתחילה ומסוף, שאז הוא אחר שני שנים. אז, צריך לחלק מנין של השנה ל19 חלקים, ולהביט במה שנשאר.
1. זמן בין מולד למולד.
** 29 ימים, 12 שעות ו793 חלקים
מולד הוא זמן שנראה הלבנה אחר שהיה מכוסה. בין מולד למולד יש
(מ1080 חלקים לשעה).
1. מתי מולד אחד.
כדי לחשב את המולדות, צריך לדעת זמן של מולד אחד.
1. מתי ראש השנה.
** ביום של המולד ארבע יוצאים מן הכלל
בדרך כלל, ר"ה הוא
. יש
:
  1. לא אד"ו ראש- ראש השנה לא יכול להיות ביום ראשון, רביעי, או ששי.
  2. מולד זקן- אם המולד נופל ביח' שעות או לאחריו, נדחה ר"ה ליום שלאחריו.
  3. ג"ט ר"ד פשוט- אם, בשנה פשוטה, המולד נופל ביום ג', ב9 שעות ו204 חלקים או לאחריו, נדחה ר"ה ליום ה.
  4. בט"ו תקפ"ט אחר מעוברת- אם בשנה שאחר מעוברת, המולד נופל ביום ב, ב15 שעות ו589 חלקים או לאחריו, נדחה ר"ה ליום שלאחריו.
מאלו, יכולים לדעת עיקרי הלוח.
יש עוד שני דברים שטוב לדעת:
1. תקופות. תקופה הוא זמנים של החמה, ונוגע לשני דינים:
  1. הזכרת טל ומטר בחו"ל (שמתחילים ששים יום אחר התקופה).
  2. ברכת החמה (שמברכים לסוף כל כח יום מתקופות ניסן הראשון).
כדי לחשב, רק צריך לדעת שני דברים:
1. זמן בין תקופה לתקופה.
** 91 ימים, ו7 שעות וחצי שעה
בין תקופה לתקופה יש
.
1. מתי תקופה אחת.
כדי לחשב את התקופות, צריך לדעת זמן של תקופה אחת.
1. פרשת השבוע. יש בזה חמש כללים, ומהם תדע את הכל:
  1. לעולם קוראים פרשת דברים בשבת שלפני תשעה באב.
  2. לעולם קוראים נצבים בשבת שלפני ר"ה.
  3. יש פרשה קבוע קודם פסח:
    1. בשנה פשוטה- צו.
    2. בשנה מעוברת:
      1. אם ר"ה הוא ביום ה'- הוא אחרי מות.
      2. אם ר"ה הוא ביום אחר- הוא מצורע.
  4. יש פרשה קבוע קודם עצרת:
    1. בשנה מעוברת שר"ה הוא ביום ה'- הוא נשא.
    2. בשאר שנים- הוא במדבר.
  5. רק יכולים לחבר ויקהל לפקודי, אחרי מות לקדושים, בהר לבחקתי, חקת לבלק, מטות למסעי, ונצבים לוילך.
** לוח שלהם עם לוח שלנו
גם יש דבר אחר שנאה לדעת, והוא חשבון של
. יש שני דברים לדעת:
1. שנים- לעשות כן, רק מנכים 3760 שנים משנה שלנו (אם כבר עבר Jan 1 אחר ר"ה).
2. ימים וחדשים- בכל שנה ראשונה של מחזר של 19 שנה, ר"ה נופל הוא Oct 3 בשנה פשוטה שלהם והוא Oct 4 במעוברת שלהם. אחר זה, צריך להקדים 11 יום לשנה פשוטה, ולאחר 19 יום לשנה מעוברת שלנו. אבל, גם צריכים להביט בכמה דברים:
  1. אם השנה חסרה, שלמה, או כסדרו.
  2. כמה שנים מעוברות היו להם.
  3. אם השנה הזה מעוברת להם.
