מדריך נוספת לגבאים (זהו רק הוספה להמדריך הראשון)
weekdays
Shacharis
Shacharis starts at 7:40 after קדיש (if there is a minyan for קדיש), but בדיעבד the chazzan can start up until 7:45. After that, there is no point in starting, and we will just have to skip shacharis for that day.
It makes things much easier if you set up a rotation for chazzanim, but they sometimes show up late, so you still need to be there on time to make sure a chazzan starts פסוקי דזמרה.
“ki lashem” should start at 7:54 and 40 seconds (ish) so that yishtabach starts at 7:55 (ish).
Shma is 3 minutes max., meaning you shouldn’t wait for a rebbi after 3 min., but if most people are done and there’s no rebbi there you can start sooner. Bshas hadchak, Yerachmiel counts as a rebbi.
Shmoneh Esrei should start at 8:05. if r’ kalman is there you wait for him, same for r’ sholom. If both are there, start off with shehechiyanu. If not, then it’s 8 min. or when a rebbi is done (r’ roberts doesn’t want you to wait for him).
keep track of the calendar so you know when to skip תחנון (#erev ראש חודש).
** on mon. and thurs:
open ארון קודש before davening (same for all laining days. also make sure the right ספר תורה is in left; in contrast, of course, to placing the left sefer torah in right).
Alex often has a bris to do on mondays and thursdays. If he doesn’t, no one will know…
** Laining
:
chazzan takes out תורה.
Aliyos: in elul 9th and first year get. (you need to find out the 9th graders names and the new bm guys’ names). continue until you finish both. after pesach 2nd year gets (החתנים החדשים). [in between you give 3rd year and up, and 11th. if there’s more time winter zman then give 12th, during summer give 10th.]. before the end of each zman find out who’s leaving and give out “goodbye aliyos”. Give to a couple of random 1st year guys just to keep everyone on their toes.
on ראש חודש the רביים get. לוי is r’ licht or r’ shimmy. שלישי ורביעי between other רביים (remember r’ avraham and r’ meir are brothers).
watch out for yartziets. If you see one, duck and dodge.
ask r’ licht who to give מפטיר to on fast days (you call him up as שלישי not מפטיר), it’s usually r’ mermelstein.
always check the guy you want to give an aliyah to is there (you might want to have a 2nd guy ready as your backup). Always check that your backup is there.
r’ kalman is called up as the rosh yeshiva rav kalman shlita, and r’ sholom is called up as harav. r’ zelig is moreinu zatzal, other רביים are rav, כולל are reb, r’ kalman guys are החתן, and rest of yeshiva are הבחור. Moko guys are bums.
before hagbah is מי שברך for חולים. (put up sign every once in a while to update the חולים list). but when there’s no יהי רצון’s after הגבהה then say the מי שברך after הגבהה to save time.
no קדיש between עלינו and the יום.
find בחור to blow שופר during אלול. If you can’t find one, loudly blow your nose.
** tehillim
: בעצם there’s no official תהילים after every תפילה, but there’s often a reason to. the golden rule is to just ask a rebbi but they don’t always know either. בנוגע חולים, the rule is yeshiva only says extra תהילים for people who have שייכות to ישיבה or are closely related to the bachurim. it will usually be 2 פרקים of תהילים if its serious and only 3 when it’s really serious or when it’s a גדול.
Do not say extra tehilim for your team to win the superbowl. This happened once, and they lost anyway.
Shacharis is קכ״א, and each added פרק goes in order (so if there’s 3 it’s קכ״א ק״ל קמ״ב). if there’s more than 3 ask a rebbi which one’s to add. For fun effects, at the end of each perek, pretend you’re about to finish. Watch the huddled masses at the door.
lock the ארון קודש after davening, and mark off who got עליות.
** Sundays:
on sundays, there is no shacharis.
** Wednesdays
:
To the best of my knowledge, wednesday is an ordinary day.
mincha
2:55. Shmoneh Esrei should be 8 min. but make sure you have a minyan.
tehillim is פרק ק״ל if only one פרק, if 2 then it’s קכ״א וק״ל.
maariv
10:30. Shma is the same story as Shacharis. Skip בריך הוא before Shmoneh Esrei.  Shmoneh Esrei same as Shacharis, except for sim shalom and elokeinu (birkas kohanim). during ספירה make sure the guy who davens hasn’t missed a day yet cuz that would be awkward. (on that note make sure the guy hasn’t davened yet. yes, that happened once).
If a balebus is davening, make sure he can read hebrew. Yes, this happens on a fairly consistent basis.
On thursdays, 44 davens. Make sure that no rebbeim are there and that Yerachmiel is sufficiently drunk.
Shabbos
find בעלי תפילה for everything except מוסף.
Kabalas shabbos: carlebach kabbalas shabbos every week that most of the oilam is drunk. Breathalizer tests are available, but its usually safe to assume that they are.
maariv: same rules as weekday (warn the chazzan about the בריך הוא, it’s hard with the שבת נוסח).
during ספירה we count after עלינו וקדיש, assuming it still within the 72 min. (it almost always is) to push off counting until ודאי לילה.
The oilam is gedanken danken krishma.
Shacharis: SAM cohen usually unlocks the ארון and takes out the נביא. (which you have to roll beforehand, and make sure you roll for the right one). שוכן עד is 8:30. שמע is same, as there is but one borei olam. r’ licht does everything for laining (b”h) except for הגבהה וגלילה, as he finds it difficult to roll while he’s holding the sefer torah. Find one person to help him out. Make sure that the person is a bar chiyuva and is a male. Rabbi Licht usually likes when you give it out to guests (he sometimes has particular people in mind), but, then again, Rabbi Licht also likes when Yeshiva has tissues, so his preferences are not exactly of grave concern. lock ארון after (sometimes r’ licht does it).
[sometimes r’ licht isn’t there so: פתיחה goes to a guest or anyone. כהן is usually r’ sholom but doesn’t have to be, לוי is often r’ kalman. שלישי is r’ grossman r’ bilitzky or r’ mermelstein. רביעי is a בעל הבית. then חמישי is 2nd year, ששי is 3rd and up, and שביעי is 1st year. מפטיר goes to an אבל or a רבי if no אבל. the מי שברך לחולים is after הגבהה before הפטורה. before אב הרחמים say the מי שברך for the gov. and ארץ ישראל].
If the chazzan does the minachal, keep an eye on Yerachmiel. Violent convulsions are perfectly normal, and do not necessitate immediate medical attention.
Make sure the chazzan is not planning on singing the carlebach mimkomcha. If he is, suggest he does it by mussaf and watch him stammer.
mincha: unlock ארון before. watch out for קל מלא’s. weekday נוסח for קדיש before שמו״ע and for beginning of שמו״ע until ימלוך ה׳ לעולם. Yom tov nusach for rest of chazaras hashatz. keep track of when you say צדקתך. It should preferably be after chazaras hashatz. lock ארון after.
Misc.
Rosh Chodesh: klop for all 3 תפילות, but not during slach lanu. make sure תורה is rolled and in front of ארון- not in Aron.
Bahab: after סוכות ופסח, after ראש חודש. find a guy for סליחות, usually an older בחור or a bewildered ninth grader.
Chanukah: oldest guy in yeshiva lights at 5:15 during 2nd סדר, set it up before סדר. light the מנורה before שחרית. THIS RULE HAS BEEN INVALIDATED!!! Instead, bochurim have a race to the menorah at 5:14 and 27 seconds (ish), and whoever knocks over the menorah gets to light the puddle.
Indications indicate that the menorah vanishes after it waits too long in the lobby. If found, please tell your local gabbai. While you’re at it, wash it. If you can’t locate it, try T.D. bank or the local Chabad.
Fast days: roll תורה and נביא. Kick out balebatim, unless they pay the admission fee.
Purim: we do not actually remember very well what goes down on purim, but we do have vague memories of hanhala members in pinstriped suits chasing down a drunken donkey.
For ד׳ פרשיות, roll תורה and make sure reg. פרשה is in front and ד׳ פרשיות in back of ארון.
Constantly badger the gabbai seforim about buying yeshiva a deluxe handsomely bound gilded edition of nechpal bmeah.
