-חקרתי לעצמי, ושוב שאל לי א.י.ש., מהו ענין מה שכותבים "בס"ד" בראש שואה, אם הוא לומר שכולו בא מה’ או להתפלל לה’ לסייעתא. יש נפקא מינא באי יש להוסיף כן אחר כתיבה. יש להביא ראיה לצד שני מר"ן על נדרים שכותב כמה פעמים "כמו שכתבתי בס"ד.”מראה שיש לדחות ראיה זה. זה רק ראיה שיש ענין לכתוב שם בס"ד, אבל לא נוהגים כתיבת בס"ד אלא על דפי נייר. אולי כמו שרק נוהגים כן שם, רק נוהגים על ענין ראשון (צד ראשון שכתבנו). ותו"ת.
-עיין ברש"י על נדרים (ד:) שלכאורה מוכרח שאין בין "הכי קתני" ל"חסורי מיחסרא."
לעוד מראה מקום בזה יש לעייין ברש"י זבחים (קיד:).
-אגב, יש לדון בענין איסורי כלאים, מהו היחס בין האיסורים השונים (כמו כלאי זרעים, כלאי בגדים, כלאי הרכבה, וכלאי הכרם.) אם אינם מיוחסים, אלא שהם דומים במה שהם עירוב זה עם זה, יש לדון למה אין בשר בחלב בכלל כלאים. ותחשב.
- ירושלמי כ’ שעשרת הדברות מרומזים בק"ש. קשה שנחוש לתרעומת המינים. ויש לומר שלא יכירו מינים במה שיש בו עשרת הדברות. עוד יש לומר שלא יוכלו להכיר עשרת הדברות כי אם בק"ש, וא"כ, ידעו שיש אף שמע (עיין במש”כ על ברכות, שלא פשוט שזה יהני). עוי"ל שאם ידעו, גם ידעו שכל המצוות כלולות בהם (זה יותר טוב אם נאמר שלכן רמז לעשרת הדברות בק"ש). גם יש לומר שלא יידעו שרק אלו עשרת הדברות, ולא שאר מצוות מרומזים. ותחשב.
- בענין יסורים של אהבה, נראה שאולי הוא חלוק מעונש, אף ששניהם באים על חטא. עונש בא מפני שחטא טוען שיקרה דבר רע למי שחטא. יסורים של אהבה באים מפני שחטא מרחיק אדם מה’, ועונש מקרב אדם לה’ (יש לדון למה). ותחשב.
- יש לדון למה גורעים מדמי אמה. צד ראשון הוא מפני שכבר קבל האדון את שוויו בזה. יש לדון, שמסתמא היא שווה יותר כשהיא גדולה, ולא ינכה כפי שנים. גם יש לומר שיש חיוב על אדון לעזור לפדות אותה, וחיוב זה גדל ככל זמן שהוא האדון. ממילא, הוא יותר חייב באותו זמן. לצד זה, לא פשוט שיהיה כל מכירה דיוויד"ד משנים שלה, שרק נדע שיהיה יותר כפי השנים שקנתה. ותו"ת.
- צריך לומר שיכולים לקרוא תורה ולברך בצואה תחת צפורניים, שגמ’ אומר שתמיד יש צואה תחת צפורניים (בנדרים). ותחשב. יש לדון אם זה מפני שאין זה נחשב בשרו או מפני שכיון שהוא רגיל, אין בזה מיאור, וממילא אין איסור ובעיה בו. ותחשב.
- במה שכהן שלא יכול לעבוד לא זוכה לעשות שליח לעבוד, יש לדון אם הוא מפני שכיון שלא יכול לעבוד, לא זוכה בעבודה, וממילא לא יכול לתת אותו לחברו, או הוא שרק זוכה שהוא יעבוד, ושלוחו כמותו, אבל כיון שאינו יכול לעבוד, ממילא אין שליח שלו שליח (שאין דבר שהוא עצמו לא יכול לעשות והוא יכול לעשות שליח עליו), ואז אין זכות שלו לעבוד בו עושה שום דבר. ותחשב.
- בתחילת ברכות גלגל רביעית כתבתי:
אגב, עיין במש"כ במק"א צד שמה שג"ש נחשב כאילו נכ’ בפי’ ר"ל שגלוי הוא שאמר אותו ה’ בפירוש. כ’ שזה רק אפשר לצד שה’ סכם את הציווים לכתוב בתורה. העיר לי א.ד.ר. שנוכל לומר אף בלי זה, שאולי לא כל מה שאומר ה’, וכל מה שקרה נכ’, אלא רק מה שנצרך. אז, אף אם ציווי שכ’ הוא ציווי ה’, אולי יש ציווים אחרים. הוסיף, אולי, מה שצריך, כמו ג"ש, או שאמר אותו באופן שיהיה ג"ש. יש להוסיף שאולי גם כ’ כל מה שאמר ה’, אם לא שגילה ע"י ג"ש או כדומה שה’ אמר כן. ותחשב.
[אגב, יש לדון למה יש דברים שהמוצא אותם יכול להשאר לעצמו, כיון שלא הול' בממון בתר רוב. כמו"כ, יש לדון למה לא חוששים שת"ח הוא הבעל, ויש לו טב"ע.)
- אגב, יש להעיר מגמ’ פסחים שכ’ שאין סדר לתורה, והק’ מדין כלל ופרט (ו:). נראה שצריך לבאר מהו כלל זו, והאיך יהיה שייך בין לסיפורים של תורה, בין לדינים של תורה. נראה שצ"ל שמחדש שאין סדר מקרה חשוב. קשה, שמה זה מועיל בדיני תורה כעין כלל ופרט וכלל, אלא צריך לומר שבהו"א חשב גמ’ שנסדרו בסדר דיבור ה’, שהוא מזכיר מקרה של דיבור ה’, ושו"פ בא מאותו סדר. כיון שיודעים שאינו באותו סדר שקרה, קשה דין כו"פ. סתירצו, והו"א זו, כמובן, אפשר רק לצד שנכ’ לספור מש"א ה’, ואינו כל כך מסתבר לומר שחוזר מזה, שלא נראה שזהו המס’ של הגמרא שם.
- אגב, בענין כ’ יווני, הק’ רב קלמן שבכת"י של רמב"ם עצמו, כתוך כף הפוך (כמו c). קשה, שידוע שבאמת ביוונית הוא x. הניחא רש"י אולי לא ידע יוונית (כן אמר), אבל רמב"ם בוודאי ידע. נראה שאפשר שסבר רמב"ם שכי יוונית ר"ל חלק היוונית של אותו אות. כיון שהוא כנגד כף שלנו, ולכן לפעמים נקרא כף יוונית, נמצא שרק אחריתו נוסף, שc + נ = x. אז, הנשאר הוא כף הפוך, כמו שאמר הרמב"ם. ותחשב.
- אגב, עיין בחגיגה, בשיח שי שדנינו בו למה הוה כ"כ זמן ללכת לרקיע. יש להעיר שתוס’ כ’ שה"ה ג"כ אותו זמן להקיף כ"ע. צריך ביאור. עוד עשיתי חשבון אם נניח שמנין ארבע מאה פרסי עד גודל כה"ע נכון. אם נכון, נמצא שהוא 126,000 miles בcircumference. (יש לדחות שעולם רק רצה לומר יישוב או שרק רצה לומר מקום בארץ שאינו בכלל גן עדן או גהנום. ותו"ת.) אם כן, אם מהלכים בחמש מאות שנה, נמצא שהוא 7/236, שהוא .337 miles לשעה. זה מאד מאד לאט. אפשר שרק הלכו ביום, ואולי הוצרכו לחכות במקומות שונות. עדיין, הוא מאד לאט. אולי האוקיינים וימים היו יותר לאט. עדיין דחוק. גם אפשר שבחייל רב היה יותר לאט. גם יש להעיר שגמ’ פסחים (צד) אומר שאדם הלך עשר פרסה ביום. על פי מה שהבאנו לעיל, גוד העולם הוא 40,800 פרסה. אם כן היה לו להיות 4080 ימים, שהוא כמו 11.5 שנה. אם נאמר שהוא 27,000 feet, כמו מה שהוא באמת, נמצא שהוא 9315 פרסה. נמצא שהוא מהלך של 931.5 ימים, שהוא פחות משלשה שנים. אגב, אם נמצא שאדם מהלך עשרה פרסה ביום, שהוא כעין שלושים miles ביום, הוא, אם נחלק לעשרים ושנים שעות, כמו 2.5 mph. אולי זה כולל זמן שנח.)
- יש שחוקרים אם במצב אונס יש מצוה או לא. יש לדון מהו שאלה זה, שהרי פשוט שאין לו ציווי וחיוב כיון שאי אפשר לו לקיימו. בפשטות, יש שני ענינים:
א. יש סיבת המצוה.
ב. יש ציווי.
אפשר שדנים רק בראשון.
גם נראה (וחושב אני שיש לי קצת סמך משי"ח ש"י (-----)) שיש שני ענינים בב’:
א. יש חיוב.
ב. יש ענין (וצריך ביאור מה לנו בזה) בהיות ציווי ה’. למשל, אם אמר ה’ שכל אדם חייב, ושוב אמר- או שפשוט- שמי שיש לו אונס זה פטור, נכנס לציווי, משא"כ אי אמר ה’ שמי שאין לו אונס זה חייב. ותו"ת.
- רגילים בני אדם לפרש מעשה רב להיות "מעשה של רב" או "מעשה גדול.”הביאר ר.מ. ש. ראיה נגד זה מגמרא ב"ב (קל:). הוסיף א.ד.ר. ראיה לזה מרש"י שבת (קכו:).
- מצינו שלש שמות לרמב"ם בר"ן על נדרים: נקרא רמב"ם, נקרא רב משה בן מיימון, ונקרא ר"מ במז"ל.
- לפעמים, גמ’ יאמר שמה שעולה כליל הוא חומרא, אף שנראה שלפעמים אומר שמה שיש בו שני אכילות הוא חומרא. צריך לעיין, אבל אולי זה נוגע למחלקת אמוראים (ב"מ מט, אולי, כנזכר בתוס’ שם) גבי שומרים, אם אומרים שחומרא שמוכיח קולא נחשב חומרא, כיון שחומרא שלו גדול מקולא שלו. עיין שם. ותחשב.
- יש שיר ידוע (של א.פ.) למילים של "דא קני.… “יש להעיר שאין מילים אלו נכונים לגירסת ר"ן שם.
- עיין בירושלמי בסוף כלאים שמביא דברי רב שכל שאסור משום מראית עין אסור אפילו בחדרי חדרים. מקשה עליו מכמה בריי’, ומסיק שאין קיום לדברי רב. וא"ת הרי רב תנא הוא ופליג. אפשר לומר שהוא מפני שירושלמי נתחבר ע"י רבי יוחנן. רבי יוחנן חלק על רב בכמה מקומות, מפני שסבר שרב לא היה תנא. נמצא שלא סבר שרב תנא הוא ופליג, ואז מובן למה אומר בירושלמי שחיבר שדברי רב אין להם קיום. ותחשב.
- יש שמקשים שלצד שאסמכתא הוא רמז מן התורה לרבנן לתקן, קשה למה לא תקנה תורה. אפשר שרק רצה שיהא לו חומר של דברי תורה. יש לדון אם אי אפשר לתורה ליתן לו אותו קולא (או חומרא- עיין עירובין). גם אפשר שרק רצה שיהא נוהג בזמן מיוחד. מה שאי אפשר לומר שיחול אז הוא שתלוי במצוה בני אדם, ואז אין זמן קבוע.
-בגמרא חולין (יט:) אומר שעורף רוצה לומר אחרית הראש. אז מה שרגילים כמה בני אדם לתרגם מילות "עם קשה עורף" ל“stiff-necked people” אינו נכון. ודע שבפשטות יותר מסתבר לומר שהוא "stiff-necked people,” שהרי לכל אדם יש עורף קשה, ור"ל שיש להם מול עורף קשה, ואז לא נוטים ממה שרואים. וצריך ביאור.
- נראה שלשון "ראשך והר" הוא לשון שיש לבני אדם להשתמש בו,שיש לו קול טוב.
- מקור שר"י סובר שלוקין על לאו שאין בו מעשה הוא בריי’שגמ’ חולין (פג.) אומר שאולי (מח’ הוא) אינו נכון
-עיין ברש"י סוכה (ו:). אמר לי א.י.ש. שמשמע לו שרש"י אומר שהל"מ בסוכה הוא אותו הל"מ בגדר מחיצות. דן מה הביאור שהוא אחד, אם הוא שנאמר יחד או אולי דבר אחר. עיין שם ברש"י, שנראה שרק אומר שהוא כלול במה שאומר גמ’ ש"מחיצות הל"מ,” אבל לא אומר שהוא כלול באותה הלכה עצמה. ותחשב.
- מבואר מגמרא חולין (צא.) שלא היו יעקב ומלאך אבוקים ונגע בו, אלא שעשה כן ללו בדרך בהפתאה. לשון קרא (“כי לא יכול לו") לא משמע כן כלל, ולא מדרהרים בני אדם כן.
- עיין ברשי שכתב למה נקרא שמואל אריוך. אפשר שאריוך הוא כמו "ארוך,” וקראוהו כן על שם שהיה קטן (עיין בנדרים), בלשון סגי נהור.
קצת צריך ביאור למה לא נקרא רבן שמעון בן גמליאל בשם רבן שמעון בן רבן גמליאל, אף שמצינו כן בדרך כלל כשאביו רב, כמו רבי יהודה בר’ אילעי.
- יש להעיר שאומרים בתפלה "חקיו ומשפטיו לישראל לא עשה כן לכל גוי ומשפטיו בל ידעון.” יש להעיר שחולקים פוסקים אם חייבים גויים בכל דיני חושן משפט (אם זה בכלל דינים). אם הם בכלל, דינים, צריך ביאור מה זה אומר. אפשר שמשפטים לא ר"ל דיני חושן  משפט אלא מצות היותר שכליות מחוקים. יש לדון. גם אפשר שקרא זה נכתב כשכבר הותר שבע מצות. גם אפשר שנאמר על זם אותו זמן. ויש לדון, שאז מוכרחים לחטוא, שמוכרח שיהו חוטאים ויהיו מצות בטלים.
- יש לדון מה קורה כשמביא גמרא מימרא של רב, למשל, בסתם, ומה חלוק מאם מביא שם האומר, שבהכרח היה אומר. גם יש להעיר למה שאומר אביי "בשם גמרא.” יש לדון מה זה, ויש להעיר שממה שאומרו כאן ולא במקום אחר. משמע ששאר מקומות אינו כן. ותו"ת.
- מצינו כמה פעמים שחד ראשון (למשל, הרשבא) יאמר מה שאומר ראשון אחר ממש (למשל, הרמבן). יש לדון מה קרה שם; אטו זה פלייגיריי"ז את זה. אולי רק היו להם בכמה וכמה מקומות הערות שוות. (עיין בגמרא ב"ב שדן בת"ח שחושבים על אותו נקודה.) גם מצינו לפעמים שיאמר אמורא דבר, ויביא גמרא ברייתא שאומר כן ממש (באותם מילים). יש לדון אם ידע אמורא אותו בריי’; אם ידעו, קשה למה לא הביאו, ואם לא ידעו, קשה איך אמר אותו לשון ממש. אפשר ששניהם אמרו אותו  לשון כיון שהוא הכי טוב ליאמר. ודחוק.
נראה שלא אמר אותו לשון ממש, אלא גמרא השווה את לשונם.
- שמעתי מר.י.י. בשם ש"ס כהן לבאר רשב"א בסוגיית קידוש במקום סעודה שלא מציינו שתלמיד מובהק כר"ה יחלוק על רבו. יש לציין לגמרא חולין (יט.), ששם אמר שר"י נכון כיון שכן סבר ר"י (לאידך גיסא, עשה מעשה כעצמו. אולי לא ידע אז שרב חלק. אולי לעולם לא סבר שרב חלק, ורק אמר שלשיטת ר"י טוב לרגוז. המשך גמרא לא משמע כן, אלא משמע שחזר ממש.)
- לכאורה, מה שהיו רבנים (ובני אדם) נקראים על שם אביהם הוא כדי שלא להחליפם. יש לדון, שהרי רשב"ג נקרא רשב"ג, אף שהיה שמו רבן שמעון, ואין רבן שמעון אחר אלא רבי שמעון אחר. אולי נקראים כן לכבוד אביהם (או לכבד אביהם בהם או לכבד אותם באביהם). מוזר, אז, מה שיש תנאים סתמים. אולי לא בכל יש צורך או קיום בזה. עדיין קשה למהלא עשו כן בר"ג, שהיה אביו נשיא. אפשר (ואולי אף זה יהא קשה) שנקרא ב"ג מפני שהיה נקרא כן קודם שהיה נקרא רבן, והוא קודם שהיה נשיא. ותו"ת.
- נראה שמילת "מילה" ו"וימלל,” שהוא תרגום וידבר, יש להם חד שורש. ויש לדון.
- יציבא… ר"ל אזרח (מפרש אונקלוס אזרח להיות יציבא) בארץ וגר בשמים. משמע שגויים אינם כל כך טובים. יש להעיר לשיטת ר"א (?) הגר בתוספות שגרים הם יותר טובים. יש לדון, שאולי ידוע שלא חושבים על גרים טובים, ואומר שהוא כאילו יש מי שישים גרים במקום הכי חשוב. (על פי זה, נראה שאפשר לומר שכל זמן שמקשה כן, לא מקשה על הסברה, אלא מקשה שנראה כחוכא ואטלולא, שכמו גבי גר, מקשה מדרהר של בני אדם. אבל, לא נראה כן.)
- לא שמיעא לי- עיין שי"ח ש"ח (ב"ב- הוספות)
- במה שאין איילונית ערווה פוטרת צרתה, יש לדון אם מה שאינה במקום מצווה משנה את היחס שבין העריות או משנה את הערווה עצמה.
- בביאור מילת חשוד, עיין בשיח שי (ערכין- גלגלג רביעי- כ:- רשי)
- מצינו לפעמים (למשל, תוס’ ב"ב קכה:) שיש חילוק בין מימרא בשם תנא לברייתא. יש לדון מהו החילוק כיון ששניהם לא נחתבו. אולי חד היה יותר ידוע או כדומה. ותחשב.
- מצאנו שבתר עניא אזלא עניותא. עיין בב"ק בשני מקורות לזה. יש להעיר שבשני, אם נאמר שלומדים מזה שדאגה בלב אדם יסיחנה לאחרים, לא רק נוהג במצורע, אלא בכל מי שבא עליו צרה, שגם צריך להגיד לבני אדם צרתו, ומסתמא לא רוצה בזה. נראה שיש להעיר שגם אפשר לתלות כלל זה במה שאומר גמ’ בכ"מ שה’ נותן חכמה לכחם, והוא שטוב הולך לטוב כמו שרע הולך לרע. ותחשב. אולי כמו כן יש לבאר מגלגלים חוב לחייב וכדומה, וכמו רמב"ם הידוע בשכר מצוות, שה’ לא נותן שכר בהאי עלמא, אבל מיטיב כדי שיעשה עוד מצוות (שהוא באמת יוצא מן הגמ’ בפרשת כי תצא, שאומר שנסמך לומר שאם תעשה מצווה זו, תזכה למה שצריך כדי לקיים מצווה אחרת.)
- שמעתי שיש אומרים שהיו בני רב פפא בני רב פפא חלוקים. הראיות לזה הם שדברו עם רב וכדומה. יש להעיר שכנראה יש מחלקת רשי ותוס אם מוכרח שהיה ר"פ גדול מרבא (שלרשי, כיון שרק חי ארבעים שנה, וקרא לרב פפא ורב הונא בדר"י קאיקי חוורי כיון שהיו זקנים, מוכרח שהיו זקנים ממנו). אולי, אז, זה אינו לרשי.
- מצינו בכתובות שהיו תנאים לומדים רחוק מביתם לזמן ארוך. לאידך גיסא, מצינון שאומר גמרא "ריחיים…" אולי היו אמוראים חלוקים מתנאים. גם יש לומר שהיו בני אדם חלוקים.
- עיין בשיח שי (ריש כריתות) שכתבנו שם צד למה אומרים כמה כללים (כל ה"כל"ים או כדומה) בכריתות וערכין. נראה אולי שגמרא מניח שלומדים שס כדרכו, ואז כיון שהגיע לזה, כבר למד רב שס. אז, כיון שיש פתח לו לבא אגב, בא כאן. זה יבאר גם כן כללים של חולין (כל שיש בזה… ) ונדה. ותחשב.
- נראה שמילת מחוור לכאורה בא ממילת חוורתא, שהוא לבן, ואומר שהוא נקי ונכון. ותחשב. כמו כן, יש להעיר ש"מקצת" (חצי) בא מ"מ (מן) קצה," שהוא דבר שבא מקצה (ולא מגיע לקצה אחר, שאז לא יהיה רק מן קצה אחת). ותחשב. (וגם קצת הוא כן, שהוא רק קצה אחד. ותו"ת.)
- מעניין שבבית מדרש של ימי אמוראים היו רב, שהיה ארוך (פסחים ונדה) ושמואל, שהיה גוץ ושמן (נדרים) ור"י הינדוואה, שהיה שחור (עיין בשיח שי). ותחשב.
- נראה שלשון "כשר" בא מ"כשורה," דהיינו שהוא ישר. ותחשב.
- נראה שאולי יש יחס בין לשון גרון ומילת grain.
- עיין בגמרא חגיגה (יג.). עיין בשי"ח ש"י שם.
עיין ברש"י (פסחים צד:) שאומר שחמש מאות שנה הוא גם כן מסוף העולם ועד סופו. עיין בשיח שי:
- יש להעיר שאומר מדרש ספר הישר שהיו בני בבל צריכים לעלות במגדל לשנה אחת להביא לבינים לבוני מגדל. כיון שרואים שיש אותו זמן לעלות להילוך, יש לחשב גודלו, שהוא שנה, שהוא 354 יום * עשר פרסא ליום. זה, אז, 3540 פרסה, שהוא 28,320,000 אמות. זה, נניח, 42,480,000 feet. זה נעשה ל8,045.45 miles. זה גדול מאד נראה שאפשר ששאני התם שיש עמו לבינים. אולי המשא עושה שאינו כל כך מהר. גם אפשר שאז אינו יכול לעלות בידיו. אולי, אז, היה צריך לעלות במדרגות, ולא סולם, וזה יש בו יותר הרחק (ואף בלי נקודה זו של לבינים היה אפשר לומר שהיו מדרגות. ונוכל לחשוב אף את זה קצת. נניח שרב מדרגות ארכם כגובהם (כן היו כמה בבית המקדש, אני חושב.עדיין זה 63.42 miles. בגובהו (אף אם נאמר שארכו כפול, הוא יותר מחמישים (51.8 miles).. זה מניח שהמדרגות ישרות. לכאורה, זה אי אפשר, שאם כן, יהיה רחב מאד. אפשר שהוא גלגל, ואם כן, יהיה אותו גודל. גם אפשר שהיה turn בו בlanding. אם כן, יהיה יותר קטן, אבל לא כל כך. דע שיש גם כן מדרשים (פרקי דר"א) שאומרים שהוא שבעים מיל. זה מאד יותר קטן.
- יש מדרש (ילקוט שמעוני דניאל) שאומר שהיה נבוכדנצר רק טפח. העיר לי א.מ.ו. שאז מוזר מעשה שערלתו נמשך כל כך (שבת). נראה שאינו קשה, שמה לנו אם ערלה של קטן נמשך או של גדול נמשך. נראה שיותר קשה איך בעל מי שהוא בן טפח מלאכים אחרים.
- מעניין שרב פעמים שמוצאים "אמוראי נינהו… " הוא אליבא דרבי יוחנן, ורב פעמים שמוצאים ש"תנאי נינהו… " הוא אליבא דרבי יהודה (זה אינו כל כך כמו רבי יוחנן). נראה, על כל פנים, לבאר הא דרבי יוחנן שאולי כיון שהיה בארץ ישראל, שהיה רחוק מהם, לא היו שמועות כל כך טובות ממנו. ויש לדון. ותחשב. גם נראה שאולי הענין הוא שידעו על כל חזרותיו, שהיה רחב"א מחזר לימודו לפניו כל שלשים יום (עיין ברכות גבי שלקות), ואז מצוי שהיו שני לשונות בשמו של רבי יוחנן.
- נראה שאפר (והיה לי הוכחה לזה, אבל שכחתי אותו) ש"מה לי לשקר" רצה לומר למה אניח שהוא שקר, ולמה אשקר, ומילת שקר הוא דומה למה שאומרים "לאמת דבריו." והוא לעשות שנניח שדבריו אמת. ותח’.
- נראה שאולי מה שאומרים בני ראשונים שיש עדויות ש"אינם בתורת עדות כלל" רק אומר שאינו עושה כלל (או לאופן חשוב) מה שעדות עושה לגרום פסק דין. יש לדון, שאם נניח שעדות רק מחמת נאמנות, אם הם נאמנים כלל, אם אין ראיה אחרת נפסק כן. וצריך לומר שהוא כל כך קטן שאין פוסקים עליו. ויש לדון. גם יש לומר שר"ל שיש קצת מן הסיבות שיש לעדים נאמנים לעשותם נאמנים, אבל אין להם שום נאמנות כלל. ועיין בחרב אל הבדים (ב"ב- זמן חורף) שדנינו קצת בזה. ויש לצרף של שם לכאן ושל כאן לשם.
- הקשה לי י.מ.ו. למה אומר בלק שמי שבירך בלעם היה מבורך, שמגמרא משמע שרק ידע מתי ה’ יהיה ברוגז. ועיין בבעל הטורים שם (כן העיר לי). ונראה שאינו כל כך קשה, שאולי בלעם שיקר לומר שהיה יכול לעשות יותר ממה שהיה יכול לעשות (והיה נראה כברכותיו מקויימות, שהיה מקלל מי שנגד מי שבירך).
- נראה ששם "מעיים" בא ממה ששופכים מזה לזה כמעיין. עיין רש"י תענית (י:).
- עיין רש"י בבכורות (וכמה מקומות שנזכר ר"י בן קרחה) שאומר שהיה ר"ע קרח. נראה שזה מפני שהיה זקן (שהתחיל ללמוד כשהיה קצת זקן), וממילא היה קרח. ותו"ת.
- נראה שמילת "משפחה" אולי הוא "מ- רצה לומר מן- שפחה," שאשתו של אדם נקרא שפותו, שמשמשתו.
-נראה שמילת "בן חורין" בא ממילת חור, שהוא כמו גומא, והוא שיש לו כמה מקומות וחורים לנוס ולדור שם.
- התעורריתי לומר שמה שעונשים שבעולם הזה אינם כל כך רעים כמו בעולם האמת הוא שיכול להראות על ידי עונשיו שיש בורא… ואם כן, לא רק מכפר מחמת צער, ולכן אינם צריכים להיות כל כך רע, שלא רק מחמת רעותם מכפרים. ותו"ת.
- אם הייתי בעל מוסר, הייתי אומר:
1. עיין בתענית שאומר רבי יוחנן שאם היה שם, היה עושה צום תשעה באב בעשרה באב. יש לדון למה לא נעשה כן. נראה שאולי סברו רבנן שכמו שלא יכול להרגיש רעת צרות בני ישראל אם לא נהיה בצער (ואז צריכים לצער את עצמינו), לא נוכל לקוות לגאולה עד שנפדינו מאותו צער. אז, בעשרה באב, צריכים להיות נפדים, ומתוך כך, לקוות לישועה.
2. עיין בערכין (וכן כמו כן נמצא בכמה מקומות) שדורש גמרא שלשון הרע יכול להמית אף לרחוק. קשה למה מביא קרא לזה; פשוט הוא (ולא קשה למה אומרו קרא, שקרא רק מזכיר כל מה שהיה רע בימי החורבן. ותו"ת.). נראה שסברו רבנן שמה שאומרו קרא הוא יותר סיבה להניחו ממה שרואים אותו בחוש. ותו"ת.
אבל, ברוך ה’, אינני בעל מוסר.
- שמעתי מאבי (הוא לא כותב חיודושיו, ואז אכתב לו) שיש להקשות למה אומר "וזאת התורה… " באמצע, ולא בתחילת דבר או בסוף. באר שהוא לאחר שאומר קרא שהבדיל משה שלש ערים. מזה דורש גמרא (מכות) שאוהב מצוות לא ישבע… אומר תורה שזה הדרך לקיים תורה- וזהו וזאת התורה…
- בכמה מקומות אומר גמ’, “והא לא תניא הכי…" עיין בשיח שי (רש"י- זבחים- גלגל רביעי- צו:).
- בקרא של, “כי לא על הלחם לבדו…" עיין במה שאומר אבן עזרא. מעניין, שהיה להם מה לאכול, שהיה מין, ואף שבא מנס. יש לדון, שאולי היה מוכרח שהיה כחו רוחני כיון שלא הוצרכו להוציאו. ודחוק. לולי מש"כ, הייתי מפרש שאומר שלא רק על עמל אדם יחיה אדם, אלא יש לה’ כוח לזון אותנו. ודחוק.
- הק’ לי ע.י.ג. למה לקחו לאסתר כיון שלא היתה בתולה (שהיתה נשואה למרדכי).
- יש שכתבו שיוסי הוא כינוי ליוסף (כן מצינו, למשל, ברש"י בדיון גמרא ביבמות במה נקרא קיום שם). ק"ק למה לא מוצאים כינויים לשמות אחרים. ויש לדון, שיש אומרים שרבא ורבה הוא רב אבא. ודע שיש לדון אם נקראו כן או שגמרא קוראים כן להם. ויש לדון. גם אפשר שרק דםוס’ כ’ כן. אם כן, אולי אינו כינוי אלא קיצור.
שוב הבנתי שלכאורה, אין יודעים מה היו שמם, ואז אין יודעים מה כינוי, ואולי יש הרבה כינויים בגמרא. אולי, למשל, פפי היה כינוי לפפא.
- יש לדון מהו ענין חדא ועוד:
1. רצה לומר חד מתרי טעמי נקט (ר"ל חד נקט, ויש עוד). מה שלפעמים אומר כן בפירוש, ולפעמים לא אומר כן משמע שהם שני דברים חלוקים.
2. משנים מה שאמר
3. רק אמר מה שאינו כל כך ידוע., והוסיף על מה שהניח שידעו בני אדם.
- לכאורה, יש שייכות בין מילות ורידים (שדם יוצא מהם) ווורד (rose). צריך ביאור מהו. אולי הוא ששניהם אדום בדרך כלל. ויש לדון.
- נראה שאולי ביאור במה שחוקים העולם בכמה דברים (למשל, לפני עור) אם הוא דין בכל מצוה או בכל התורה הוא אם כשאמר ה’ את המצוה, אמר זה בכל מצוה או פעם אחת. זה מניח שלא אמר ה’ ממש מש"כ בתורה, ושדיבורים (ולא רק דינים שיוצאים) שאמר ה’ חשוב. ותחשב.
- נראה שלשון נחל איתן בא (או להיפך) מלשון איתן, שהוא חזק, והוא מפני שהקרקע חזק עכ"כ שאי אפשר לעבוד בו, לחרשו ולזרעו.
- שמעתי כשהיה ר"ק קורא משנה בראש בכורות שאמר מילת "כוי" עם חחולם. שמעתי שרש"ש שליטא אמר אותו מילה עם חיריק, אבל שאלתי לו, ואמר שלא ידע איך לאומרו (אמר שהוא כדינו), ושנראה בארטסקרול.שם, אומרו בחולם. ויש להעיר שהיה ר"ק קורא מארטסקרול כשאמרו עם חולם.
- מעניין שכמעט כל קיום של ציבור שמצינו הוא בענין קרבן. ותחשב.
- אולי מילת "חס" (כמו "חס ה’ עליו") שייך למילת "חסד.”
- עיין במק"א שהערנו שמוזר מה שמצאנו שאמוראים אומרים דבר בלשון בריי’ ולא מביאים הברייתא. ויש לומר שלא אמרו באותו לשון, אלא גמרא אחר כך קבעו אותו כן. ותחשב.
- עיין בדרשות הרן (שביעי) במש"כ למה לא יהיו גויים שונאים אותנו אחר ביאת משיח. צריך ביאור, שלכאורה, אי אפשר לגייר אחר ביאת משיח. אולי רצה לומר שיאמינו באמונתינו, ואז לא יבינו שאנחנו חלוקים מהם, ולא ישנאו אותנו מחמת זה. לא משמע כן. שאלתי את זה לרש"ש שליט"א, ואמר שאולי רק נתגיירים לאחר זמן. קשה, שאז בוודאי לא יעשו מלחמה, שבימות משיח אין מלחמה. ת’ שלא יעשו מלחמה אבל ישנעו אותנו או יכו אותנו. זה לא אפשר ממה שאומר שם בפירוש שמפני זה לא יהיה מלחמה. אז, אמר שאולי סובר שעל ידי זה יתקיים לא ילמדו עוד מלחמה. ותחשב.
-גם שאלתי, והודה לי, למה מקשה על רמב"ן שם, שרמב"ן סובר שזה מצווה, ולא הבטחה, לכאורה.
- גם שאלתי אותו על חז"א שאמר שאין לפסוק מספרים שהיו גנוזים, שמסתמא ה’ הסירם ממסורה שלנו לסיבה. קשה, שה’ נתן אותם לנו למצוא אותם. (ודע שע"י גלגל החוזר, אינו ק’, שה’ ידע שכבר נדע אין לפסוק מהם. ויש לדון, שעדיין אין צור למצוא אותם.) הודה לטענה זה, ואמר שהיה לו אותו טענה. עוד אמר שמצאנו שפסקו כמה גדולים (משנ"ב, חת"ס) על פי דברים כזה. גם העיר’ מה יהיה אם רק היה לבני ספרק- רק ספרדים יכולים ללמוד אותו?
- נראה שלשון ארמי של שאלה (המליך) אומר שעשה אותו מלך, ועשה שיכול להחליט. ותחשב.
- ראיתי בעין זוכר שחולק חיד"א במה שאמר אחד שספק ספיקא שאומר גמרא יבמות (שאולי הוא נפל, ואולי הוא נקבה) אינו מתהפך. לכאורה, הצד שאינו מתהפך הוא שאין לומר שאם הוא נקבה, טוב, ואם הוא זכר, אולי הוא נפל, שאין נפל נחשב זכר. תחילה, יש לדון אם זה אמת. שני, יש לדון למה אומרים, “אם הוא זכר,” שלכאורה, היה לנו לומר, “אם אינו נקבה,” ובודאי יכול להיות שנפל אינו נקבה. ויש לדון, שאולי אם אינו שייך להיות זכר או נקבה, אינו אפשר להשתמש באותו לשון. ודחוק. ותחשב. ואולי זהו דחיית חיד"א.
- מעניין שאומרים בהושענות "המלמדנו תורה נביאים וכתובים שלשה" (או דבר כמו זה), שהרי אומר גמרא נדרים (לפי מפרש שם) שמה שיש כל כך תנ"ך הוא עונש. ואולי מברכים את ה’ על מה שעשו היה דבר שיביא לנו שכר. ותחשב.
- דנים (עיין רב אלחנן בקובץ שעורים (כח)) אם היתר שבא לאשה מחמת מיתת בעלה בא כיון שאין מי לייחס לה (ואז, ממילא אינה נשואה) או שמיתת הבעל מנתק הקנין. עיין שם. אומר שבזה תלוי אם אשת אליהו מותרת לינשא, שהרי בעלה לא מת, אבל לא היה עדיין בעולם.
נראה- ושמח וצחק ר.ד.ו. כשאמרתי את זה לו- שאולי יש לדון בו להיפך באשת רבי זירא, ששחטיה רבה והחייה אותו. נמצא, אז, שמת, והיה יכול לייחס לאשתו עדיין. ויש לדון עדיין. ותחשב.
- צריך ביאור למה המון העם אומרים שראם ועוג נתנו חוטמם בתיבה, כיון שלפי רש"י, גמרא בזבחים (קיג:) מסיק שרק עמדו, והיו גבוהים.[fn:1]
- צריך ביאור למה כל המון העם אומרים שהיו שני בהמות ממינים כשרים ושבע ממינים פסולים, שהרי גמרא בזבחים (קטז.) מסיק שהוא שלא נעבדה בהם עבירה. וע"ש. (אגב, לכאורה, שם אומר שהיו מינים מלאים שהיו כולם בני עבירה, שאי לאו הכי, יביא שבע מכל מין. ותחשב.)
- אמרתי פשט לר.ש.ש. וצחק ואמר שהוא פשט טוב. ר"ח סגן הכהנים אומר להתפלל בשלומה של מדינה…. יש לציין למש"כ רש"י ביומא (כן אני חושב, אבל אולי אינו ביומא, ואולי אינו ברש"י) שהיה ר"ח היודע ביותר, ולכך היה סגן לכהנים הרבה, אבל מינו אחרים מפני ממונם, ומתו הרבה. נראה שהיה אומר שאף שידע ברעת המלך, שרע בא לו בגללו, אף על פי כן, אמר להתפלל בשלומם. ותחשב.
- ידוע שקל וחומר הוא אחד מן הי"ג מדות שהתורה נדרשת בהם. ממה שצריך להיות כלל משמע- ויש לדון- שהוא חידוש הקרא (על כל פנים, כן מוכרח לרש"י, שאומר שכל היג מדות הם הלכה למשה מסיני). קשה, למה הוא חידוש הקרא. ונראה שהוא מפני שמוכרח להיות פירכא, והוא שאין לזה סיבות רעות של זה, בהכרח, כיון שהוא איסור חמור. אז, חידוש הוא שיש לדרוש קל וחומר אף שיש פירכא זה.
- צריך לבאר למה בגלגל השנה או גלגל החיים אומרים שהוא גלגל. לכאורה, אי אפשר להיות שלעולם הולך והולך, שאף סקוו"ר הוא כן. אפשר להיות שבסקוור יש קרנות, ובהם, אם הולך ממילא, יפול. יש לדון, שאף בעיגול, אם הולך ממילא יפול, שצריך לטור"ן את עצמו בכל זמן מעט. אז, לא בא ממילא. דברתי על זה עם ב.ד.ת. וא.מ.ו. ובא לנו כזה:
1. בסקוור יש מקום שהוא יותר מסתבר להתחיל ולסיים (שהוא קרן)[fn:2]. אז, יש התחלה, מה שאין כן בגלגלים אלו שכיון שהם מגלגלים והולכים, אין מקום כזה.
2. יותר יש לומר שלענין הליכה מנקודה לנקודה, אין מקום בעיגול שהוא יותר חשוב מחבירו. בסקוו"ר, כל קרן הוא יותר חשוב. כמו כן בגלגל השנה או כדומה, כל חלך ממציא את חבירו באותו חשיבות ובאותו הכרח. ותחשב. גם יש בזה הענין שכל פרט חשוב לעשייתו מהו, ולא רק בא ממילא (כמו בסקוור, שיש מה שרק בא בקו).
צריך לאמר את זה במילים יותר טובים. לכאורה, הענין הוא שאם ממשיך כל נקודה, היה טוב, חוץ מבקרנות, שצריך להפכו. אז, אלו הם החשובים ביותר. ותחשב. אבל בגלגל, חל חלק ממנו הוא נצרך.
(ואגב, נראה מזה להוסיף למה שאמר ר.י.ג. שאין יהדות תלוי בימים קדושים כשאר אומות, אלא כל יום חשוב, וכל יום הוא יום נצרך. נראה שהוא נקודה שנית שכתבנו בגלגל.)
- ידוע שבכ"מ חולקים ראשונים בביאור קראי עם גמרות ומדרשים. שמעתי מכמה בני אדם (ר.ש.ש. וגם ר.מ.ש. בשם גדול אחר (שכחתי שמו)) שאין זה כל כך קשה. ר.ש.ש. אמר שאולי כיון שהוא רק אגדתא, אין לומדים מדברי גמרא (כמו שאין לפסוק כאגדתא). יש להעיר שבע"ז (ט, גבי מנין שני דברים. רמב"ן חולק על כל זה.) לכאורה פוסק דינים מזה. ועיין שם. (שוב ראיתי שלכאורה אין אותו מחלקת נוגע לאותו דין שם. עיין בשיח שי שם).
- עיין במק"א שהבאתי ראיה שאין "אין חוטא נשכר" שאם כן, יעשה עוד עבירות, שהרי גמרא ב"ק (לח.) אומר אותו על התרת מצוות. אם כבר התיר אותם ה’, אין לחוש עוד. ויש לדון, שאולי אין החשש לחוטא זה, אלא שיהיו עוד בני אדם חוטאים, אף שהם עדיין מצווים. גם יש לומר שבני אדם יעשו אותם מעשים, אף שהם עדיין רעים. ותחשב.
- שמעתי מר.י.ב. שפסק רח"ק בשם חזון איש שיכול אדם לכוון אחר שכבר אמר קרא. הקשיתי לו- והודה לי- שאם כן, קושיית גמרא ממה שאין לכפול ק"ש קשה, שמי שלא כיוון יכול לכוון אז. צריך לומר שהזמן שלאחריו אי אפשר לכוון יותר קצר מן הזמן שלאחריו לא נראה כאומר שמע לשני אלוהות.
- לרבי אליעזר, שיכול אדם לנדב אשם תלוי בכל יום, שמסתמא הוא חטא, קשה למה לא חייב אדם להביא בכל יום. ותחשב. ואולי על חייבי לאווים אינו חייב להביא, ורק יכול. ואולי אומר שמניחים שחייב רק אם רוצה להביא, שיש שום סימן לדבר (מסתמא, הוא דבר רוחני) שעבר. וזה לא נראה כן.
- גמרא אומר לשון "תקף ליה עלמא" לומר שאדם היה קרוב למות. יש לדון במשמעות אותו לשון:
1. אולי אומר שעולם הבא תקף בו, שהיה קרוב לבוא לשם.
2. אולי הוא לשון סגי נהור, ואומר שעולם הזה תקף בו.
- בפשטות, חלות קנין הוא שיש מעשה קנין שעושה יחס שעושה דיני קנין. העיר לי א.ד.ר. שאולי מעשה קנין עושה דיני קנין (מפני שמראה שליטה, ואז נותן קנין), ואז עושה יחס. ותחשב.
- רגילים בני אדם לומר ששידוכים הם קשים כקריעת ים סוף. יש להעיר שזה נאמר על זווג שני בלחוד (עיין גמרא סוטה ב. עם רש"י, ועיין בגמרא סנהדרין כג). ותו"ת. ועיין במאירי בסוטה.
עדיין מוזר מה ששמעתי בני אדם מקשים למה כל כך קשה הוא אם כבר יצא בת קול קודם לידה, שהרי גמרא מקשה כן בפירוש שם.
ועיין במדרש רבה (פרשת ויצא- ד). משמע מזה שהוא בזווג ראשון[fn:3], שלכאורה, לא מסתבר שכל העבדים היו הזווג שני. ויש לדון, שאם באר לה שהוא רק כשהם בזווג שני, אולי מצתה עבדים שהיו כבר נשואים בדווקא.
- ר"י הנדוואה- ע’ במק"א שהערנו שרש"י מתרגם שהנדווא הוא כוש. לפעמים, זה אפריקא. גם מצאנו שהוא אינדיא (אם הודו קרוב לכוש. ועיין במסכת מגילה.). אם כן, יש לומר שהינדווא, בא ממילת הינדו ואינדיא.[fn:4]
שוב ראיתי סמך לזה מגמרא עבודה זרה (טז.) שאומר "פרזלא הנדוואה[fn:5],” ורש"י פירש שהם מהודו. ותו"ת.
- יש לדון במילת "איזה.” לכאורה, היה נראה לומר שהוא מורכב משני מילים, שהוא "אי זה,” שהרי רואים שלפעמים נאמר בשני מילים. אם כן, קשה למה אומר "איזה הוא.” נראה שהוא כמו שמוסיפים הוא על כמב דברים כמו שנהפוך, אם נרצה, “יעקב איש גדול" ל"יעקב איש גדול הוא.” ותחשב.
יש לציין לרש"י בזבחים (צא:) שאומר, ”ואיזו זו? זו….“ ותו"ת.
- נראה שמה שבני אדם אומרים במקום אלף יוד (כמו ב"ראב"ד") מקורו ממשנה ברכות פרק רביעי (“הודייה"). עיין בשיחתא דשי שם.
- עיין ברש"י בגיטין שכתב שלא פלוג הוא מפני שאם לא תחמיר על זה, לא יחמירו על זה. יש לדון אם הוא מפני שיחשבו שאין האיסור כל כך חמור או שישכחו את הגדר. ותחשב.
- ידוע שיש אומרים שהיו שפחות האמהות אחותיהם. אם נניח שהיו אף מלבן (אם היו אחיות, כן נראה, שלא היה לו שליטה לתת אותן לשפחות אילו לא היו בנותיו), ק"ק למה לא נתן לבן לקטנה שבהם שם רחל, כיון שהיתה קטנה מכולם (כמו שאומר רש"י), כמו שהיה עושה עם לבן (כמו שאמר יעקב). ואולי יעקב כיוון לאותו רמאות, אבל לבן לא הכיר בו, ויעקב רק חשש שיכיר בו, אף שלמעשה לא חשב עליו. דחוק שלא יכיר בו, ובפרט כיון שיעקב כבר גילה אותו לו קצת. ותחשב.
ויש לדון, שאולי לא היה זילפה הכי קטנה, שאולי רק רצה לומר שבשעת עיבורה היתה הכי גדולה.
- גמ’ בחולין אומר שמותר לאכול בהמה כשמפרכס, ואף לא נחשב אבר מן החי כיון שאגב שהותר מחמת שחיטה, הותר מחמת אבר מן החי. עיין שם. ידוע מה שמביא רש"י שאכלו אחי יוסף בשר שהיה מפרכס. נראה שסבר יוסף שכיון שלא היה אז צווי שחיטה (ואולי אף לא היה מי שמקפיד על שחיטה), לא היה אגב זה קיים. ותחשב.
- יש להקשות איך אומר ירושלמי שיכול אדם להזכיר גשמים בשומע תפלה, שלכאורה, זה תפלה, ולא הזכרה.נראה שכשאדם שואל לדבר, גם אומר ששואל למי שיכול להשיב לו. אם כן, יש בכללו הזכרת גבורה. אז, נמצא שהוא מסתבר למה יכול לשאול להזכרה.
- אומר קרא, ”בוגדים בגדו ובגד בוגדים בגדו.“
- אומר משנה בשבת שר“מ אומר, ”אין ראיה לדבר, אבל זכר…,“ ורבי יוסי משיב ”משם ראיה.“ קשה, שלא אמר משם ראיה, אלא אמר משם זכר. אפשר שהלשון אינו דווקא. גם יש לומר שביאור ”משם ראיה“ אינו שמתמיה איך מביא ראיה משם (אפשר שלפעמים הוא כן, אבל לא כאן), אלא אומר שמשם ראיה לדידי, לצד החולק. אולי לרבי יוסי זה ממש ראיה, ולא זכר, שאולי מה שהוא רק זכר ולא ראיה הוא שצריכים להניח כמה שאמר רבי מאיר בגמרא, שמזכיר כלי שחשוב וכלי שאינו חשוב. לרבי יוסי, אין צריך הנחה זה (וצריך לומר שסובר שיותר קל להניח שאינו כן, עד שיכול להביא ראיה ממש). אם כן, יהיה נמצא ביאור לשון ”ראיה משם.“ ותחשב.
- צריך ביאור למה נקרא "שילוח הקן,” שהרי שולח את האם. אולי הוא אומר שהוא שילוח שעושה כשעוסק בקן. עדיין הוא שם מוזר. ותו"ת.
- שאל לי א.מ.ו. בשם אחיו הקטן למה מתחילה רצה עשו לחכות להרוג את יעקב עד שימות אביו, ושוב נסה להרוג לו ע"י אליפז. נראה שאפשר שהיה נחית להרוג אותו ע"י שליח, והיה צריך לשהות עד שאליפז יגדל או כדומה. דחוק. גם יש לומר שאחר שראה שלא היה אביו מת בגיל שמת אמו, ואז אולי יחיה לזמן רב, היה צריך להרוג את יעקב. ותחשב. ואם תאמר אם כן למה שהה כל כך. ונראה שזה כמעט מוכרח להיות קשה אם לא נברא שום מציאות. ותחשב.
- שמעתי מאבי מי שמקשה (ר.ז.ש.) איך היו לפרץ כבר בנים בירידה למצרים כיון שמפורש שיהודה נשא אשתו אחר מכירת יוסף, והוליד בנים, שהיו נענשים (ואז צריך לומר שהיו בני שלש עשרה), ואז שהה, ואז ייבם, ואז הוליד, ואז פרץ הוליד עוד, והיה כל זה בתוך עשרים ושנים שנה. ותו"ת. וצריך ביאור.
שוב שמעתי בשם אחי ש.ח.ח. שאמר שחוזקני כ’ שהיו בני שבע. יש לדון ל"ל הביא גמ’ מהם ראיה בסנהדרין (פרק בן סורר ומורה). ויש לדון, שאולי לא כל כך פשוט ללמוד כן מן הגמרא.
- שמעתי בני אדם אומרים בכמה ציורים שדבר הוא כוח רוחני. בכל זמן כזה, צריך לחפש אם הוא יש שום הוכחה לומר שהוא כוח רוחני, ולא רק דבר פשוט במציאות. למשל, אמר תלמיד חכם אחד שתורה היא גדולה וחשובה, שבכל זמן שצריך לשנות, משנה. למשל, היו חסידים בזמן שהיה צריך, והיה ר"ח בריסקר בזמן שהיה צריך…. שם, פשוט שקרה מפני שהיה צריך- היו רוצים אותו ומחדשים אותו והיה נתקבל מפני שהיה צריך. ותו"ת.
- צריך ביאור למה אין לכל קל וחומר פירכא במה שהנלמד, אף אם לומדים לו אותו הדין, יהיה לו הדין באופן יותר חלוש, שלא יהיה נכתב בפירוש (וזה יותר חלוש, כמו שאומר גמרא ב"מ פח, ותוס’ קידושין (טו:)). ותחשב על זה. אולי הוא מפני שיש הלכה למשה מסיני שאומר לדרוש קל וחומר. נראה שאולי לכן צריך הלכה למשה מסיני לומר לנו כלל זה, ולא פשוט הוא מן הסברה. ותחשב.
- יש משמעותים חלוקים כשאומר, “אין… גדול מזו.” עיין ברש"י בביצה כב. שמשמע שהוא שזה הכי גדול.
- עיין ברש"י ביצה לב:. מעניין, שאף באנגלית הוא כן, שaround ר"ל שני פירושי של מקיף[fn:6]. ותו"ת.
- גמרא אומר על רב הונא אחד (ריש גלותא) שהיה גדול מנשיא (הדרך שאמרו רב שלום הוא שהיה גדול מרבי[fn:7]). רש"י במ"ק אומר כן על רב הונא אביו של רבה בר רב הונא. חושב אני שגמרא אומר (ביצה) שרבה בר רב הונא היה בן של תלמיד של רב (בענין צד). אם כן, נמצא שהיה אותו רב הונא הריש גלותא שעליו זה נאמר. זה מוזר. ותחשב על זה.
- יש אומרים שלא מולים חלה של שבת בלילה שאין קרבנות בלילה. זה מניח שאי אפשר למלוח בלילה, אף שאפשר להעלות בלילה. צריך ביאור. הקשיתי את זה לר.ש.ש. ולא ידע.
- ביני ורש.ש. יצא ההערה שלכאורה, כשאומר גמ’ בב"מ וסנהדרין שאמר דוד לשונאיו ש"מי שעבר על אש"א יש לו חלק…" אי אפשר לומר שיש לו חלק בכל ציור, שגמ’ אומר שלא עולה (וכן גם נראה שאין לו חלק מרבינו יונה בפרק שלישי של אבות). לכאורה, ר"ל שהוא שב, והם לא שבו, ואז יש לו חלק. ודחוק.
- שאלתי לר.ש.ש. למה אומרים, “בלי נדר" כיון שהוא בדרך כלל נאמר על דבר שנאמר בלשון שבועה. אמר שלא היו חלים אם לא מדין נדרי מצווה, ואז הם נדרים.
- חולקים אם מעשר כספים דאו’ (ואם הוא בכלל "עשר בשביל שתתעשר"). לכאורה, כיון שמותר לנסות בזה (ואולי אף אין צריך לזה, שלכאורה, כאן אינו מנסה את ה’), יש לנו לבדוק אם מעשרים.
- שמעתי מר.ד.ו. שמנ"ח מק’ איך מלך יכול למחול על מי שמרד בו, כיון שמלך שמחל על כבודו אין כבודו מחל. תירץ (באר את זה בתוך תירוץ של מנ"ח) ר.ד.ו. שמלך לא יכול למחול על כבודו כיון שהוא בזיון להעם. אם כן, כאן, שכבר קרה, ואין מחילתו נראה רע לעם, אלא נראה טוב, יכול למחול.
נראה לי שקל לומר תירוץ אחר, והוא שמה שלא צריך להרוג מי שמרד אינו מדין מחילה, אלא שאין אותו אדם חייב מיתה, אלא רק יכול מלך להרוג אותו אם רוצה. ותחשב.
- הביא ר.ד.ו. רש"י בדברים שאומר שחש יעקב להוכיח את ראובן שחשש שמא ילך לעשו. הקשה למה היה חלוק לפני מיתתו. נראה שאולי ידע הנבואה שהוא ועשו ימותו או יקברו ביום אחד. אז, אין לחוש כל כך, שלא יוכל ללכת לעשו לזמן רב. אמר שזה מחודד.
- יש לציין לגמרא ביצה שאומר לשון גזירה שווה על דבר שהוא פשוט להיות דרבנן. שם הוא ג"ש מעניין, שהוא, לכאורה, מה מצאנו. על"ע שדיננו בג"ש שנקרא היקש.
- נתעורר לי ע"י א.מ.וו. שאולי רבי אלעזר פר פדת הוא בר פדת של מעילה (ד:). יש לדון, שמעניין שלפעמים ייקרא זה ולפעמים זה. ויש לדון (יש לציין לתחילת תענית בבן בתירה). אם כן, ר"א היה בן אחותו של בר קפרא. זה מעניין.
- ק"ק למה אומר ה’ למשה שיהיה לו אות, שכשיצאו מארץ מצרים, יעבדו את ה’ על המקום הזה. לכאורה, אז, יהיה אות יותר גדול, והוא מה שהיה משה מוציא אותם ממצרים. ותחשב. צריך לומר שאחר כל זה, עדיין לא היה משה יודע שהוא הנכון. אולי הוא מפני שביותר היה ה’ שהוציא את בני ישראל, שהיו נסים גלויים. אם כן, משה יאמר שלא עשה כלום. ותחשב.
- עיין ברשב"ם שכ’ שאין מקור בדברי תנאים ואמוראים לומר שמשה היה מגמגם בלשונו. העיר לי א.מ.ו. שיש מקור לזה במדרש רבה שמות (א, כו). צריך ביאור.
- עיין בשיח שי (סוף כתובות- גלגל רביעי) בביאור דרשת "עם הדומה לחמור.”
- לשון רבים של עם הארץ הוא "עמי הארצות,” ולא רק עמי הארץ. כן אומר גמרא כתובות קיא:.
- “The apple doesn’t fall far from the tree” בא מקהלת (יא-ג). עיין בע"ז (לא.).
- נראה שאפשר להיות שהיו שני ר"נ, והוא שהיה ר"נ דיין מומחה. אולי, אז, יש ר"נ שנסתם גבי ממון, והוא הדיין, ולא היה סיבה לסתמו כי אם גבי ממון, ויש ר"נ אחר שהוא סתם ר"נ במקומות אחרים. וצריך לעיין במראה מקומות שבשיטות רש"י ותוס’.
-יש שיטה שאין איסור בשוגג בדרבנן. יש להעיר שאפשר שהכוונה הוא כך: אם אדם לא מכיר שמה שעושה הוא מה שאסרו רבנן (לא שלא מכיר שגזרו רבנן, אלא לא מכיר שהוא אותו דבר), אז אולי אין סיבת האיסור, שסיבת האיסור הוא שאם העושה עושה כך, יבוא לעשות איסורים, שסובר שאם זה מותר, אף איסורים מותר. אין סברה זה שייך אם לא יודע מה הוא. אם כן, לא גזרו בו רבנן, שקל לומר שרק גזרו כשהסיבה שייך. ותחשב ותבין.
- העיר לי א.ד.ר. (מאת א.ל.ב.) שקשה למה לא מסרטים היום, שכתבו פוסקים שהוא בכל כתב אשורית. לכאורה, אף שאנו לא כותבים כל כך כתב אשורית, כל ספר כן (ויש לדון, שנראה לי שאולי רק צריך כן אם כותב, ולא אם מדפיס), ורביים של כתה א’ כותבים כן. אולי הוא רק כתב של ספר תורה. ויש לדון, שלא נמצא כן.
נראה לי שאולי העולם סומכים על השיטה שרק צריכים שרטוט של שיטה ראשונה. נראה שאין צריכים לזה שירטוט ממש, אלא רק דבר ישר, שיעשה הכתב ישר. אם כן, כיון שאנו כותבים על נייר וכדומה שהוא ישר, אין בעיה. ותו"ת.
- לפי הצד שהיו צפרדעים קרוקודיי"לים, קשה איך הפלו את עצמם לתוך תנוריהם (כמו שאומר גמרא פסחים). אולי רק נתנו ראשם שם. גם אפשר שהיו פרו"גים וקרוקודיי"לים. גם אולי היו תנורים גדולים או קרוקודיי"לים קטנים.
- מעניין שמצאנו שריב"ח, אביו של רבא, היה תוקף בעבדים (ב"מ סד:), וגם מצאנו שהיה בנו (רב שעורם אחוה דרבא) תוקף בעבדים (ב"מ עג:). נמצא שהוא runs in the family לתקוף עבדים.[fn:8]
- עיין בגמ’ תענית(ט) בענין ינוקא של ריש לקיש. יש שלא גורסים "זיל נסי,” אלא הקשה על הקרא עצמו. כן גורס אור זרוע. קשה, שאור זרוע גם אומר שמה שמותר גבי מעשר הוא שהותר בזמן בית שני מפני הצורך. קשה, אז, איך יפרש קרא על ידי זה, שמזמן כתיבת קרא היה אסור. ותחשב.
כן הקישיתי לר.ש.ש. והודה לי.
-חוקרים אם חלות חל בזמן הסיבה או אחריו. לכאורה, פשוט שחל בזמן הסיבה, שבאותו זמן יש סיבה לו לחול, ואין מניעה, ואז ל"ל יחול.[fn:9]
היה אפשר לומר צד שמה שאי אפשר לאדם לקנות חפץ של חברו הוא מפני שקנין של חברו מעכב עליו. נראה שאי אפשר לומר כן, שלכאורה, אם קונה, אין קנין של חברו מעכב עליו. אם כן, עיכוב קנינו תלוי בדבר שאולי בטל. וצריך לחשוב, שזה, כמובן, גלגל החוזר, שנמצא שהוא גורם את עצמו. אולי מה שמעכב אותו הוא קנין של חברו לפני כן. ותחשב.
- בט"ו בשבט, התחיל ר’ שיעור בוקר ואמר שהוא ט"ו בשבט שהוא יום של התחדשות. באותו יום, ר"י ברגמאן היה לו סורגר"י, על ידי אורגנייזישי"ן שנקרא renewal. גם אמר שצריכים ללמוד מן המאורעות, ובאותו יום היה אירטקוויי"ק בטורק"י שהיה נרגש אף בא"י. הרבה מתו בטורק"י, ואף זה כעין התחדשות.
- שמעתי מעשה כך: נתן שאול ליברמן את ספר שלו לר.ש.ש., ואמר לו ר.ש.ש. ש”גמרא חוקר אם יותר טוב להיות עוקר הרים או סיני- אבל אתה עוקר סיני!” שאלתי את ר.ש.ש. אם המעשה הוא נכון, ואמר שהוא שקר וכזב, אבל הודה לי שהוא מאמר מצחק. אמר ששאול ליברמן היה תלמיד חכם, ורש”ז אורבאך מביא דבריו. אמר שהיה על הכל איש דתי, אבל היה בעיה לו במה שלימד בJTS.
- שמעתי מאת ר.ד.ו. בשם ר’ שכטר בשם רי"ב סולובייציק שהקשה כך: יש שפירשו שדיון גמרא ביבמות בענין אם בית דין מצווים להפריש קטן הוא אם מעשה קטן הוא מעשה איסור או לא. הקשה ממה שאסור להאכיל בידים, ומגמרא סנהדרין (נה), ופירש שהוא רק מתעסק, ואז יש מעשה איסור בחלבים ועריות. צריך ביאור, שלכאורה, גמרא ביבמות גם דן באכילה, וגם דן באיסורי ביאה. ר.ד.ו. אמר שזה הערה חזקה.
- שמעתי מר.ד.ו. בשם ר"ח שאמר שאולי באנדרוגינוס, שאומר שהוא חצי זכר וחצי נקבה, שהוא בן יב, יש איסור ללכת לבית הקברות, שנקבה מביא את הזכר, והרי אסור להאכיל איסור בידים לקטן. קשה, שלכאורה, גדלות תלוי בדעת (אם לא שנאמר שזה ל"פ), ויש לאנדרוגינוס רק דעת אחד, ואז נדון אם יש לו דעת או לא, ואם יש לו דעת, יש איסור מחמת זכר עצמו, ואם לא, אין שום איסור. ותחשב.
- עיין בקידושין פ:, שקורא ר"י לריב"ל בריבי (כן פ’ רש"י). אולי זה נוגע למה שדנו ראשונים (עיין בסדר הדורות) אם היה ריב"ל תלמיד או רבי של רבי יוחנן.
- עיין בחיד"א (מדבר קדמות) שדן למה לא באר אליהו כל ההויות כשבא אל תנאים ואמוראים. עיין שם. אפשר שאינו אותו אליהו, שהיו שני אליהו, כמש"כ רש"י בקידושין ע.
- ביום ראשון של ראש חדש אדר, הזכיר גר"ק שזקנו היה אומר ביום ראשון של ראש חדש, “חדש טוב, ולמחר גם כן ראש חדש.” באר שחששו שאם אמר חדש טוב, בני אדם יחשבו שרק היום ראש חדש.
- ידוע שאומר גמרא לפעמים שיש דברים שנבראים מאיליהם. כמובן, זה קשה כיון שאינו כן למעשה, ואין דברים נבראים מכלום. נראה לבאר, אולי, שאב או אם הוא מי שמוליד- דהיינו, מי שגורם היות הוולד. נראה, אז, שיש הרבה דברים שיכולים לקרוא אב ואם, שיש הרבה גורמים לחיות הוולד. אולי מה שקוראים לאב ואם בלחוד אב ואם הוא מפני שהדרך שהם עושים אותו יכול להיות נראה (ר"ל בא מהם ובא ממעשם) ומובן. ותחשב. אם כן, אולי כיון שדברים אלו לא נראים שהם באים מאב ואם, שהאב והאם קטנים מאד, לא נחשבים אב ואם אמם ואביהם יותר ממה שאויר או מים נחשב כן, שצורך למים או לאויר יותר נראה. ותחשב על זה.
עדיין חידוש גדול הוא שאב ואם הוא רק מי שגורם אחר, שהיה אפשר לומר שבא ממשם. ותחשב.
- שמעתי מאת ר.ח.נ. שדן מדרש ל"ל צריכים ללכת אחרי רבים ולהיות כגויים. יש להעיר שאין קשר רשעים מן המנין, ואין הולכים אחר רבים להטעות, אבל זה מניח שהם לא נכונים. לכאורה, אז, יש גלגל החוזר, שאם נלך אחר רוב, נמצא שנניח שאינם רשעים, ואז יש רוב, ואם לא, נניח שאין רוב. אפשר להוסיף שאין לגויים מושג של הליכה בתר רוב (איני יודע אם זה אמת). אם כן, אין צד שנלך בתר רוב, שאם נניח כתורה, אז הם קשר רשעים, ואם נניח כמותם, אין ללכת בתר רוב. ותחשב.
- לכאורה, אם יש חיוב לשתות עד דלא ידע בין ארור המן לברוך מרדכי בפורים, יהיה חיוב על נשים כמו על אנשים, שאף הן היו באותו הנס[fn:10]. לא מצאנו שנשים ישכרו בפורים, אבל לכאורה, אנשים ששותים יסברו שאף נשיהם ישתו. ותחשב.
ואולי צריך לומר שנדחה כיון שאינו צניעות או כדומה. ויש לדון, שלכאורה אינו כל כך טוב כך אם אנשים שותים. ותחשב.
- נראה שאולי מה שבני אדם סומכים לעבור על לא תחנם (לקלס גוי[fn:11]) הוא מפני שמבואר ממה שיכול לתת (לחד תנא) נבלה לגר תושב שאין איסור זה לגר תושב. אם מניחים (וגם זה מחלקת, והוא בע"ז) שגר תושב הוא מי שלא עובד ע"ז, לא קשה לומר שאלו הגויים הם גרי תושב (לכאורה, תלוי באם הם, באמת, נוצרים, ואם זה נחשב עבודה זרה). אם כן, לא יהיה אסור לחנות אותם.
- נראה שמה שגמרא אומר שאדם מחפה על בת אחותה, ולא על בת אחיו, אף שיכול לישא זה וזה, הוא מפני שאדם יותר אוהב בת אחותו, מפני גמרא בב"ב, שרוב בנים הם אחרי אחי האם. אם זה אף נכון בבנות, אז הם דומים לו. ותו"ת. אולי לכן אוהב אותם. ותחשב.
- נראה שבכל חלות לאחר זמן, יכול להיות שלש צדדים:
1. עושה שסיבה יברא לאחר זמן.
2. עושה שיש עוד סיבה שנצרך, והוא קורה לאחר זמן (ואולי הוא אף היותו לאחר זמן).
3. יש מניעה עד לאחר זמן.
4. יש סיבה ל"חלות של לאחר זמן.”
- עיין בבכורות (ב.) במה שקורא שם בשם קנס. מעניין, שבדרך כלל, קנס הוא דבר שחייבו אותו חכמים מפני שעשה דבר שאינו טוב, כדי שלא יעשה אותו דבר עוד. נראה שאולי זהו משמעות של קנס נגד עונש, אבל כאן, דנים במשמעות של קנס נגד ממון. המשמעות הוא שקנס הוא דבר שהוא פייר. אם כן, כיון שאינו פייר שישלם זה, נקרא קנס. צריך לומר ששאר בכור שנותן לכוהן הוא פייר. ותחשב.
- אולי כתבתי את זה כבר: יש שיטה שכל דרבנן דאורייתא, שאמר תורה לשמוע אל רבנן. יש חולקים. לחולקים, צריך ביאור למה נשמע לרבנן. נראה שאולי אינו כל כך קשה, שאף צריך ביאור למה נשמע לתורה. אז, צריך לומר שיש דבר יסודי ביחס שבינינו לה’ שעושה שצריכים לשמוע לו. אף שיחס לרבנן חלוק, אולי יש דבר כמו זה ביחס לרבנן. זה יהיה הצד לומר כן. ותחשב.
שוב העיר לי א.י. שאינו כל כך פשוט, שמי יאמר שיש חיוב לשמוע אל דברי תורה. זה אומר שאולי אין חיוב לעשות אותו, אלא שה’ אמר לעשות אותו, ואם אין עושים אותו, אז ה’ יעניש אותנו. אם כן, אין לומר כמש"כ, אלא אם כן נאמר שכמו שמעניש ה’ על מה שהוא צווה, כך מעניש על מה שחכמים צוו. לא כל כך נראה כן, שה’ גילה רצון במה שציווה, ולכן מעניש. יש לדון, שזה אפשר רק אם נאמר שענין העונש הוא הסיבה, ולא הציווי עצמו. ותחשב.
- דנים אחרונים אם היה לרב זירא קדושת כהונה אחר שמת והחיה אותו רבה. צריך לדון למה לא יהיה לו קדושת כהונה. אפשר שהוא מפני שמת אין לו קדושת כהונה, והוא בא ממת, שהיה מת. צריך לחלק, אז, בין מת למי שלא נולד כבר. גי"ל שכהן הוא מי שסיבת חייו הוא כהן. אינו כן כאן, שהיה סיבה אחר לחייו (לא רק שלא ימות, אלא לחייו), והוא רבה. קשה, שרבה היה כהן. וצריך לומר שצריך שכהן יגרום את חייו באופן מיוחד, והוא שיוליד אותו. ותחשב.
- שאלתי את גר"ק אם הוא טוב לקרוא חיים של רב מרדכי אליפונט. אמר שאין תועלת בקריאתו, אבל הוא מעניין מאד. שאלתי לו אם הוא אמת, ואמר שכמה מן הדברים שחשב שהם מוזרים ואי אפשר להיות אמת שמע מצא שהיו אמת.
גם שמעתי שר.ש.ש אמר על מעשה אחד שם עם ר.ש.ש. וג’ו דימאג’יו שהוא שקר וכזב. אין זה כל כך ראיה שהוא שקר.
- גר"ק אומר שחושב (אבל יש חולקים) שבתנאי יששכר זבולון, מאבד אדם שכר. גם הניח שלא רק מאבד כפי ממון הניתן, אלא כפי הפירסינטיי"ג; אם אדם נותן לו חצי ממונו, אז נותן לו חצי שכר. שאלתי לו אם אז יותר טוב לקבל ממי שהוא עשיר גדול, שאז לא יאבד כל כך שכר. לא השיב כל כך, אבל נראה שזה הערה טובה. ותחשב על זה.
- נראה שאולי מה שצריך הלכה למשה מסיני לצד השווה הוא שלא לומר שצריך אחד מן שני ההלכות כדי לגרום אותו הלכה שלומדים. אגב, זה לכאורה שווה ל"צד חמור פריך.” אז, צריך ביאור איך דורשים שום צד הושווה. אפשר שרק צד חמור פריך, אבל לא צד קל. צריך ביאור מהו החילוק. אולי אמר הל"מ רק על אחד.
- ר.ש.ש. אמר על המשנה של "גימטראות פרפאות…" שחשב שפשט הפשוט בזה הוא שר"ל geometry, והוא, כמו תקופות, מחדד את האדם. זה מבאר למה אינו חכמה ותורה עצמה.
- מצאנו לשון ש"אין דבריו של אחד במקום שנים.” מעניין, שהרי הלכה כיחיד אם הוא יותר מסתבר. אפשר שאין הלכה כיחיד שהוא יותר מסתבר, אלא שאז מניחים שאינו ממש יחיד, אלא יש אחרים שלא נמנים שסוברים כמותו. ותחשב. יש להעיר שרש"י כ’ שסתם מראה שדבר כעין רבים (עיין במש"כ על זה בשיח שי). אפשר שהוא מפני שהלכה כרבים בכל מקום, אף אם יותר מסתבר כיחיד, אלא שאז לא נחשוב שהוא רבים. אבל כאן, כבר יש לנו דבר שיוכיח לנו שהוא רבים. ותחשב.
- בתחילת שיעור אחד על משניות (על בכורות ה-ב) אמר’ שאף שיש כמה טעותי דפוס, יש סדר למשנה, וחילוקי פרקים ומשניות נעשו מאדם חשוב. אז, צריך לבאר למה משניות ופרקים נחלקים, כמה פעמים, בדרך שלא מסתבר כל כך. אותו משנה (ה,ב) היה דוגמא ללו, ששם אין סוף המשנה שייך כלל לתחילתו. אמר שמגורי אריז"ל יש ספר שבאר כל המשניות וכתב טעמים על פי קבלה לחילוקיהם.
- נראה שלשון זנות בא מלשון מזונות (כמו מאכל) כיון שעיקר המילה אומר להיות לו הנאה (כן אומר רש"י בפסחים (כו.)).
- לפעמים, גמרא ידייק מברייתא, וידחה שיש לדייק מסיפא להיפך- “אלא מהא ליכא למשמע מינה.” לכאורה, היבאור הוא שצריך לומר שחלק אחד הוא אגב חברו. קשה, שגמרא בזבחים אומר שיותר טוב שסיפא יהיה אגב רישא (וכן מבארים כמה ראשונים). אם כן, יש כבר דבר שמסתבר. אולי אין הכי נמי, אבל אין ראיה.
- יש סימן טוב במה שדבר בטל באחד בששים, ופחות מזה הוא נ"ט, שהוא "נותן טעם.”
- עיין ברש"י ע"ז עה. ד"ה מדיחן. נמצא שפוסקים נגד סתם משנה אם מגמרא יוצא שכן מניח. ותחשב. יש לדון אם זהו השיטה שהלכה כסתם משנה או לא. אם הוא כר"י, ק"ק מהי"ת שאמורא זה מניח שהל’ כסת"ם; אז, א"א ללמוד ממנו.
- במילת "מצה,” יש דגש בתוך הצדי"ק. אם כן, צריכים לכפול קולו. לספרדים, נמצא שהוא כמעט שווה, אבל לאשכנזים, נמצא שצריך לומר, “מטסטסה.” נראה לי שאין העולם מוזהרים על זה.
- מקשים העולם מה אומר בדיינו, “אילו הקריבנו לפני הר סיני…,” שהרי לא היה די, שלא היה עושה כלום. תירץ זקני ר’ דר. נ.ד. שאמר משה לפני פרעה שרצה לצאת ולעבוד ולזבח לשלשת ימים. מה שאומר הפיוט כאן הוא שאילו רק עשה כן ה’ (והטוב היה שהיינו מקריבים קרבנות ומתקרבים לה’) היה די. ותחשב.
- שמעתי מאחד שדייק (ואמר שיש לו עוד הוכחות) ממה שנמנו לחם הפנים בפרשת ויקהל כשאומר מה הביאו למשכן שאין שולחן כלי בלי לחם הפנים. קצת קשה מגמרא בשבת, שאומר שמנה באבות בישול ולא אפייה כיון שאין אפייה נצרך בסדר עשיית המשכן. קשה, שנצרך ללחם הפנים.
- יש רב חיים ידוע בענין אמירת הלל בפסח. גמרא ערכין (י.) אומר שלא קוראים הלל שלם בימים אחרונים של פסח כיון שקרבנות החג שווים. מבארים שזה סימן שאין חילוק בקדושת היום, והרי כבר אמר הלל לאותו יום. מדרש אומר שאין אומרים מפני ש"מעשי ידי טובעים בים….” מפרש ר"ח שראשון דוחה דין הלל של יום טוב, ושני דוחה דין הלל מחמת נס.
הבנתי שיש קושיה על זה, והוא שקושיית גמרא על דין הלל על נס שבחו"ל (במגילה ובערכין) משמע שאומרים הלל מחמת הנס. אין זה קשה על ביאור פשט ראשון, שמה שכל הימים שווים מוכיח דבר על הנס. ותחשב על זה.
- מקשים איך אפשר שלא נתחמץ בצק של בני ישראל ביציאתם. ונראה שאפו אותו קודם, שהיו צריכים לחם, ולא בצק, ולא היה להם זמן לשהות כיון שהיה להם כל כך כמה דברים לקחת. ותחשב. שו"ר שיש ראשונים שכ’ בפירוש נגד זה, וכתבו פשטים מענינים.
- שמעתי בני אדם חוקרים, וידעתי שלא הבינו מה הם חוקרים. אני הבנתי מה הם חוקרים, והוא נקודה פשוטה, אבל נאה, ואז אכתוב אותו:
לפעמים, מצאנו מצווה שצריך לקיים, אבל צריך פרט אחד בזמן אחד שמקיים אותו. יש לדון, אז, אם יש חילוק בין שני פעמים שמקיים אותו. יש, כנראה, שלש צדדים:
1. מפני ההוספה, חלוק הוא. אפשר שההוספה עושה שהוא חלוק או רק מוסיף קצת.
2. ההוספה מגלה שחלוק הוא. זה אומר שמה שצריך להוסיף הוא מפני שהכל עושה דבר חלוק.
3. אפשר שיש שום דבר אחר שעושה שכדי לעשות מה שהוא רגיל, צריך דבר קצת חלוק. אז, עושה דבר שווה.
יש להעיר שבכל זמן שאנו כותבים, "עושה דבר חלוק," אומר שעושה דבר חלוק, אבל אף אולי אומר שהענין חלוק. זה נוגע בתוך צד שני, והוא שאולי לא מגלה שעושה דבר חלוק, אלא שדבר חלוק ממה שעושה הוא הנוגע, ובא עמו מה שבדרך כלל נוגע, כמו שבא עם מה שבדרך כלל נוגע אותו חצי שלא עושה כלום בלי אותו פרט שמוסיף. ותחשב.
- יש רש"י מעניין בברכות (יט) שאומר שלבישת בגד נחשב מעשה. תוס' בנזיר אומר שמה שנזיר נשאר בבית הקברות יש בו מעשה, שהוא מעשה של השארתו שם. יש לדון למה אינו כן גבי השבת אבדה. אולי הענין הוא (וצריך לחשוב עוד על זה) שתלוי באם הבעיה האו במה שעושה או במה שלא עושה. זה אומר שגבי אבידה, מה שהוא רע הוא הכל חוץ ממעשה אחד; אז, מה שעושה הוא שלא עושה אותו דבר. בדברים אלו, מה שהוא רע הוא מעשה שעושה. ותחשב על זה.
- הדין הוא שאין חוזרים לומר יעלה ויבוא בערבית כיון שלא מקדשים את החדש בלילה. יש לדון אם זה תלוי במה שאין מקדשים בלילה או במה שאי אפשר להיות כן. לכאורה, מסתבר לומר כשני, שאמירת יעלה ויבוא תלוי בהיותו ראש חדש. אפשר לדחות לומר שלא כן, אלא תלוי בעשייתו ראש חודש. זה אומר שאולי הכרה שהוא ראש של חדש מוסיף בו קדושה, ועושה אותו מועד של ראש חדש. אולי, אז, צריך להיות זמן של ראש חדש. ותחשב.
גם יש להעיר שלכאורה, חדש מעובר נעשה קדש כבר בלילה. ויש לדון, שאולי אינו כן, אלא אולי רק נעשה קדשו ביום. אולי זה מפני שאי אפשר להיות קדוש בלילה (וזה חידוש, שלכאורה, הבעיה בלילה הוא עשיית דין ולקדש אותו), ואולי אף שמים לא מצי מקדש אותו בלילה. נראה שזה קצת תלוי על מה ר"ל ששמים מקדש אותו, אם הוא ממש כעין בית דין או אם רק ר"ל שקדוש ממילא כיון שמוכרח להיות ראש חדש (דינם בזה ראשונים).
ויש להעיר שלכאורה, הלל כבר קדש הכל מפני זמן. אם כן, נאמר שהכל קדוש היום. אם כן, צריך לומר שהוא מפני שברוב שנתות, או שלכתחילה, אינו כן. (זה רק אם תלוי במה שהוא קדוש, ולא במה שיכול להקדיש אותו אז).
ויש להעיר שלכאורה (ואולי כן הוא הדין; אני לא מקשה) אף לא יחזור ליעלה ויבוא של סעודה כשהוא בלילה, שיש אותו טעם. .ותחשב. ויש לדון, שאולי יש אותו יחס לזמן בערבית, שהוא מיוחד ללילה. לא נראה כן. לא נראה שיחס זה יהיה חילוק, ולא נראה שיש יותר יחס, שכמו שמברכים בכמה זמנים, כך אומרים שמ"ע בכמה זמנים. ותחשב. ויש לדון, שאולי תפלולת עושים דבר חלוק בזמנים חלוקים. ועוד, שבוודאי יש זמנים מיוחדים לתפלה, שלא יכולים להתפלל בכל זמן (ויש להעיר שלשיטת רבנן, רק נתמעט חצי שעה אחת אחר חצות[fn:12]), ואז זמן יותר חשוב לו. ותחשב.
-במקום אחר דנינו מהו איסור גברא ואיסור חפצא. לכאורה, לא מסתבר לומר שדן אם יש איסור על חפץ, שאין ה’ אוסר חפץ, שהרי אין לחפץ בחירה. ויש לדון, שאם נאמר שרק דנים במילים שאמר ה’, אז יש לומר שאפשר לה’ לומר מילים על חפץ (“חפץ לא ייאכל”), ועלינו לקיים אותם מילים. לא נראה כן- ראשון, לא נראה שזה ציווי, שני, לא נראה שה’ יעשה כן, אלא יצווה, ושלישי, בדרך כלל, אין אדם חייב בחיוב של חבירו. ותחשב.
אפשר שהענין הוא אם הבעיה הוא שהחפץ רע, ולכן אכילתו רע, או לא (אלא הוא דבר אחר). יש לדון ,שאם החפץ רע, אז יהיה מצווה לבער אותו. אלא, צריך לומר שהוא רק רע באכילה. אבל, כל צד יודה שהוא רע באכילה. אז, אי אפשר לומר כן. ויש לדון, שאולי הוא דומה לטומאה, שלכאורה, הוא רע (שהוא נחשב ביפוך של קדושה), והרי אין חיוב לבער אותו. ותחשב על זה.
גם אפשר שהדיון הוא מה רוצה ה’, אם רוצה שלא ישנה החפץ או לא ישנה האדם. יש להעיר שלכאורה, אין ה’ רוצה קיום החפץ במצב מיוחד, שיכול לעשות שאם אוכל, אין החפץ קיים כמו שאם מזיק אין החפץ קיים. אז, לכאורה, בשניהם אין החפץ קיים באופן מיוחד. אלא, צריך לומר שלא רוצה ה’ שהחפץ ייאכל. צריך לדון אם יש, באמת, חילוק בין אם ה’ לא רוצה שחפץ ייאכל לאם ה’ לא רוצה שאדם יאכל חפץ. ותחשב על זה.
ודע שגם אפשר לומר שאין ה’ רוצה אותם תוצאות של אכילת חפץ זה, שהוא מה שסוקר מאותו חפץ בא למעים..., אבל לא נראה כן כל כך. ותחשב.
- נראה שאולי מה שאין לקטן דעת אינו רק מפני שאינו יכול לחשוב. נראה שאף קטן שיכול לחשוב אין לו דעת מפני שהוא קצת דומה לדברים שבלב. דברים שבלב מגיד לנו שדעת בלחוד לא מהני, אלא צריך אף שאותו דעת ידוע. אולי מה שאינו מסתבר שלקטן יש דעת עושה שלא כל כך גלוי דעתו, וכל מה שחושב הוא קצת דברים שבלב. ותחשב.
עדיין יש לדון למה כל גדול יש לו דעת. צריך לומר שממש כולם יש להם, אי לא שנאמר שעשה תורה דינים כאילו יש להם דעת אף כשאין לה דעת. אם כן, קצת לפני שנעשה בר מצווה, לכאורה, מסתבר כבר שיש לו דעת (לא מוכרח, אבל מסתבר). אז, ק"ק למה לא יחייב אם יש לו דעת. צריך לומר שכדי להיות שאינו דברים שבלב, צריך להיות אותו גדר שבו יכולים לחייב, והוא אחר בר מצווה. ותחשב.
- נמצא מגמרא יומא שכשדנו במלא לוגמא וכדומה, שאלו במלא לוגמא גדולה. אולי זה מפני מה שמזכיר גמרא בנדה כמה גדול היו כמה מן התנאים.
- ביני וא.ד.ר. יצא שמקור לרמב"ם שתרי"ג מצוות הם רק אם הם נוהגים לדורות הוא שנלמדים מ"תורה צווה לנו משה,” והרי "אין צו אלא לשון זירוז מיד ולדורות.” ותו"ת.
- אביי נקרא נחמני, כיון שגדלו רבה בר נחמני. עיין במה שכתבנו בזמן חורף בזה. לכאורה, הדרך לבאר (אולי כתבנו זה שם) הוא שאמר ערוך שהיה בן אחי רבה. אם כן, היה זקנו נחמני, ולכן נקרא כן. אין זה מטעים עם מה שכתבו ראשונים שנקרא כן כיון שרבה גדלו. ותחשוב ותבין.
- לא היה ברור לי לזמן אם מה שקורה בסוטה הוא אקספלושי"ן או אמפלושי"ן. עיין בר"ן נדרים סו: גבי צבה, שמשמע שהוא אקספלושי"ן. יש לדון בלשון במה שאומר שבטנה נופלת. ותחשב.וצריך לעיין קצת.
- במקום אחר, הערנו שר"נ היה חתן ריש גלותא, ושהיה רבה בר אבוה רוצה לתת את בתו לו. שם, דנינו בזה. דע שאפשר לומר משם שרבה בר אבוה היה ריש גלותא. יש לדון, שהיה לגמרא להזכיר כן. ועוד, שלא מסתבר שהיה ריש גלותא כל כך טוב, שהיו עבדים שלו רעים.
- עיין בנדרים (כג). לכאורה, ממה שנחשב שתנא סתמו, צריך לומר שתנא לא כתב מה שחסורי מחסרא, אלא רק כתב מה שהוא בפנינו. יש לדחות שמה שאמר רבא הוא מה שסתם תנא. ותו"ת.
- בחלום, הייתי מדבר עם אחד בתורה, ושאל לי דבר אחד בענין "beam של טומאה.” כוונתו היה טומאה שהולך ממקום למקום שלא על ידי נגיעה. עניתי לו שהוא מניח שטומאה הוא חפץ[fn:13], ולכן נעשה beam, אבל מסתמא אינו כן, אלא הוא קרק’. אפשר להיות שיש לאויר אותו קרק’, אבל יותר נראה שיש לאותו חפץ שהוא קצת רחוק אותו קרק’, כיון שהוא נגדו או כדומה.
אחר שעררתי, חשבתי עליו קצת, ומסתבר שמה שאמרתי הוא הנכון, שלכאורה, אין חפץ של טומאה. ויש לדון, שאף שפשוט שאינו חפץ כרוב חפץ גשמיים, אולי כמו שטומאה יהיה קרק’ רוחני, אף יכול להיות, אולי, חפץ רוחני. אינני מבין כל כך מה זה אומר. ודעשאז כשחפץ טמא, נצטרך לומר שיש שני חפצים כאן, והם מחוברים, וזהו הבעיה.
ודע שיש צד אחר ששמעתי מר.מ.ש. שהזכרתי ליושב חלומות, והוא שאין שום מושג של טומאה. אחר שעררתי, חשבתי על זה, וצריך ביאור, שלכאורה, פשוט שיש קרק’ ששינה בתוך חפץ זה, והוא הסיבה לדינים. אז, קשה מה בין זה לטומאה. נראה טומאה משמע שיש דבר רע, או פרוד מה’, בנוגע אותו חפץ. צד זה אינו אומר כן, אלא הוא לסיבה חלוקה לגמרי (למשל, דברים שנוגעים בשרץ בדרך כלל הם מאוסים בטיט). וצריך ביאור.
- רש"י בברכות (מג.) משמע שאורחים נקראים כן כיון שאורח ארעא היה להכניס אותם. (יש לדון למה זה קבע שם אורחים, ולא מאריחים.)
- רש"י בברכות (מג.) כ’ שיריחו נקרא כן מפני שעשה שמן עם ריח טוב.
- גמ’ (ברכות לג:) אומר שאין לומר יותר תשבחות ממה שאמר משה. קשה, שאומרים פסוקי דזימרא, שהוא מלא תשבחות. אולי זה חלוק כיון שאמר אותם דווד. אם כן, יכול לומר הרבה תשבחות שאמר דוד בתוך שמ"ע. אולי אין רע כשאינו בשמ"ע. צ"ב למה.
- עיין בכתובות (פרק שני)  שקורא אביי לר"פ יתום. יש להעיר שגמרא אומר (יבמות קו) שעשה אביי לר"פ יתום, אחר שטען דבר טוב כיון שהיו לו הורים. (אף שבכתובות לא ר"ל יתום ממש, מעניין הוא.)
- פני משה באמצע שביעית אומר דבר ושמו בלשון ערבי ולשון ישמעלי. נמצא שאינם שווים.
- פ"מ כ’ בשביעת (כא:) שמלוגמא ר"ל מלא לוגמא.
- מילת "קץ" (כמו שאם אדם מקיץ בדבר, שחושב שהוא מאוס) הוא מפני שהוא כאילו יש לו קוצים בגופו. (רש"י סוטה יא.)
- במקום אחר דנינו אם חלות חל בשעה של סיבה שלו. היה פשוט לנו שחל. ויש להעיר שאז צריך לומר שיכול מעשה קידושין לעשות חלות על אשה מקודשת לו, שאי לאו הכי, יהיה גלגל החוזר. וצריך ביאור. ואולי יכול לחול לאשה מקודשת לו, כיון שבלי אותו מעשה לא חל. ותחשב. ודע שאולי חלות חל לאחר זמן, שלעיל רק כ’ שלא חל לאחר זמן כיון שלא היה לנו סיבה ל"ל יחול מיד. אולי זהו אותו סיבה. ותחשב. אבל, אז צריך לבאר מתי חל. ותחשב.
- יש להזכיר כאן פשט מעניין שבא ל[fn:14]י ביום שני של שבועות:
יודעים שהיה לרבי עקיבא כד אלף תלמידים שמתו בימי ספירת העומר. לכאורה, אז, כשמוצאים- ומוצאים לפעמים בש"ס- תלמידי ר"ע שאינם מן החמש הנזכרים ביבמות, צריך לומר שהיו מאותם כד אלף.[fn:15]
גמרא קידושין ופסחים אומר שהיה נחמיה או שמעון העמסוני דורש כל "את"ים שבתורה עד שהגיע ל"את ה’ אלקיך תירא,” ואז פירש. ר"ע אמר לרבות ת"ח משם. דנים למה ר"ע היה דורש אותו ונחמיה לא היה דורש אותו.
יש לציין לירושלמי (חושב אני שהוא בברכות) שאומר שהיה נחמיה תלמיד של ר"ע, והיה דורש "את"ים, ולא ידע את זה, ואמר לו רבו ר"ע לרבות ת"ח. אז, לכאורה, היה נחמיה אחד מן הכד אלף.
אם כן, יש לומר שלא הכיר ת"ח ולא כבד אותם כראוי, ולכן לא נהג בכבוד עם חבריו, ולכן לא היה דורש כן. כמו כן יש לומר להפך (כיון שלא דרש כן, לא נהג עמהם בראוי).
יש להוסיף שגמ’ בפסחים אומר (סוף פרק שלשי) שר"ע אמר שכשהיה ע"ה היה שונא ת"ח כל כך שהיה נושך אותם כחמור. אמרו לו תלמידיו שהיה לו לומר שהיה נושך אותם ככלב. אמר להם ששל חמור הוא יותר רע. הפשטות הוא שדנים במציאות של איזה יותר רע. גם אפשר לומר שהקשו לו איך אפשר שהיה שונא אותו כל כך, שלא עושה כלום, אלא רק יושב ושונה. אז, השיב להם ר"ע שהיה רוצה לחתוך עצם, שאין ת"ח רק יושב ושונה, אלא הוא יותר מיוחס לתורה. אולי אף זה יכול להיות שייך למה שתלמידי ר"ע לא כבדו חבריהם, שהיו ת"ח, כראוי.
- גמ’ אומר ביבמות שאחר מיתת תלמידים של רבי עקיבא, היה העולם שמם. צריך ביאור מה קרה לרבי יוסי הגלילי ורבי ישמעאל ורבי אלעזר בן עזריה ורשב"ג  וריב"ב וכדומה. לא מסתבר שכולם מתו כבר בלי תלמידים ולא הוזכר (ועוד שאין סיבה ניכר לזה), ולא מסתבר שהיו מתלמידי ר"ע וכבר מתו. וצריך ביאור.
- יש לדון למה מחוסר כפורים נקרא כן, שלכאו’ לא צריך עוד כפרה, שאינו חוטא, אלא צריך קרבן. אולי קרבן בדר"כ מכפר, ולכן נקרא כן. (ואין לומר שבא על שום חטא קטן, מגמ’ בסוטה טו..)
- לפעמים, נחשב סמיכה כישיבה. צריך לדון בגדר זה, שצריך לדון אם אסור לסמוך בכל דברים שצריך ישיבה. כמו כן, יש לדון אם מי שסומך יכול לשבת באמצע קדיש, ואם יכול לסמוך כשצריך לשבת. צריך לציין לגמ’ שאומר שסמיכה יותר טוב מישיבה בלי סמיכה. צריך לעיין בתורה תמימה בפרשת ואתחנן בדיון אם נתנה תורה בעמידה או בישיבה. ותחשב.
ודע שלא הבנתי, באמת, כל כך למה צריך עמידה כשצ’ ולמה צריך ישיבה כשצריך. ותחשב.
- דנים הפוס’ אם מברכים שעשה לי כל צרכי, שנתקן על מענלים, בתשעה באב. יש שאומרים שמברכים כיון שיש לנו מנעלים אחרים. יש לדון בזה, שהרי לא דורשים להוציא של עור, אלא שדורשים שצריך עינוי, וזהו מה שהוא בכלל הסרת עינוי. נמצא שאותם פסוקים טוענים שהם בכלל עינוי, אבל הם גם כן בכלל עשיית כל צרכינו. ותחשב.
- עיין בגמ’ יומא (כח:) ובגמ’ קידושין (פב.). עיין בקושיית מסורת הש“ס בקידושין. נראה לתרץ שבא רב לחדש אף דינים דרבנן.  ואם תאמר הרי מוסיף אותו אמורא אחר ביומא. וי"ל שאותו אמורא מוסיף גזירות, שהיה אפשר לטעון שלא היה סיבה לגזור לו, כיון שגזירה הוא שלא יעבור על איסורים אחרים. הוא היה ת“ח, והיה יכול לשמור א“ע. כמו“כ, י“ל שכיון שאינו כל כך רע אילו עבר על איסורים אחרים, לא יקפיד על גזירות. אז, זהו מה שמחדש אותו מד“א. (ומסתמא, רב לא יחלוק על זה.) אבל, מה שרואים מרב הוא הקפדה על איסורים אחרים שהם מדרבנן, איסורים שרבנן חושבים שהם נכונים, אבל תורה לא אמרה, כמו שבות. ותחשב על זה. גם יש לומר שאותם אמוראים אחרים רק באים לבאר דברי רב (מה מוסיף). ועיין שם, שגמ’ אומר שרב אומר כן ואיתימא רב אשי. אם נאמר שהוא רב, אז נמצא שרב מפרש את עצמו, וזה קצת טוב. אבל, יש שלא גורסים שם רב. אז, אף לצד זה, נמצא שיש אמורא אחרת שמפרש דברי רב. ותחשב.
- עיין בגמ’ בזבחים שדן במקום מזבח. שם, דן לרבי יהודה אם קדושת היכל ואולם חד או לא. יש לציין לגמ’ בעירובין, שדשם רב אומר דבר, ובו גמ’ יש לו שני צדדים ברבי יהודה, ואחד מניח שקדושת אולם והיכל אחד, ואחד אין צריך להניח כן. גם עיין שם שרבי נחמן בר יצחק חולק על רב שם, ואומר תירוץ אחר שלא צריך להניח שרבי יהודה סובר שהם אחד. ותו"ת.
- גמ’ אומר (פסחים, סנהדרין) שצריך, ”בכל מאדך“ למי שחביב עליו ממונו מגופו. לכאו’, צריך למי שחביב עליו ממונו ממה שחביב גופו על מי שחביב עליו גופו מממון שלו, שאף לו, לכאו’, חייב תורה למסור את נפשו, כיון שאמרו סתם. אז, רואים דרגא יותר גדולה ממה שצריך למסור. ותו"ת.
אכן, קצת טוב מה שפירש תורה תמימה, שאנשים אלו הם ת“ח שחשובים עליהם ממונם כמו שאומר גמ’ בחולין וסוטה. לכאו’, בת“ח, חשוב ממון, ולא שלא חשוב גופם.אז, בהם נצטרך קרא אחרת. ותו"ת.
- עיין בתורה תמימה (ואתחנן) במה שפירש בדברי ר“ת איך מקיימים היום, ”ושלשת.“ יש להעיר שפשוט שלא מכוון תוס’ לומר כן, שהרי מביא אותו גמ’ בסנהדרין, אבל תו“ת בא לומר שאולי ר“ת אמר דבר חלוק ממה שאמר תוס’, ותוס’ לא פ’ את דבריו יפה. כמובן, זה דבר מחודש לומר.
אבל, צריך לומר שפשט שאומר תו“ת הוא מעניין.
- גמ’ אומר שדוד תקן שיברכו מאה ברכות בכל יום. לכאו’, אז, רואים שכבר היו ברכות בימי דווד, אף שהם רק מדרבנן. אולי בזה נתקנו ברכות. יש לדחות שרק תקן שיש לברך, אבל לא מה לברך. ויש לדון, שאין נוסח קבוע, כמו שאומר גמ’. אבל, יש לדון, שעדיין יש דברים קבועים בנוסח שלנו. ותחשב. דע שאפשר שקודם חיוב הברכות היה רשות לברך. ותחשב.
- עיין בגמ’ ברכות (יג:) שמבואר שיש ענין להזכיר יציאת מצרים בשעת חיוב ק“ש. קצת צריך ביאור מהיכי תיתי, שלכאו’, הייתי אומר שיש חיוב להזכיר יצ“מ שלא נוגע כלל לחיוב לומר ק“ש. לא כ’ בו שום זמן, ואז לא נניח בו זמן. ותחשב.
- תמיד הנחתי שסיבות רעות הם תוצאות רעות של עבירה. בא לידי שאולי הוא שה' לא ואהב את המעשה (כמו שיש לומר שה' לא אוהב את התוצאה. אבל, נראה שלא כל כך מסתבר כן, שלכאו' זה נאבד עם זמן, שאחרי שאין מעשה, אין עוד סיבה לרע. אז, מושג של תשובה קשה. צריך לומר שה' עוד דואג על הרע אף לאחר זמן. ותחשב על זה.
- נראה שאולי הסיבה שבני אדם לא לובשים נעליים כשלומדים בבית המדרש הוא מפני שחוששים שמא ירדמו, והרי אין לישון עם נעליים. אני חידשתי את זה, ואמרתי את זה לבחור אחד, ודקה אחר זה, שמעתי ב.ל. שאמר אותו דבר גם כן. (זה קצת בדיחה.)
- ראיתי בחתם סופר שמביא על פרשת ואתחנן מה שמהרש"א כ' ש"ונשמרתם מאד לנפשותיכם" הוא בשכחת התורה (עיין במנחות צט, שמבואר (וכן משמע מן הפסוקים) ששאר הפסוקים כאן מדברים בשכחת התורה), ומעורר על זה מן הגמ' בברכות (לב). היה נראה אולי לומר שזה היתה מחלקת בין התנאים, שיש שהיו חסידים, שלא היו חוששים לשכחת התורה, אלא היו מתפללים, והיו מבטיחים שה' ישמור את התורה בידם, כמו שאומר הגמ' בברכות, ויש שלא היו עושים כמו החסידים, ולא היו בוטחים בה' לשמור את התורה בידם, אלא היו חוזרים וחוזרים על הלימוד שלהם. על פי זה, גם נראה לבאר למה משנה בברכות אומר ש"חסידים הראשונים היו שוהים שעה אחת ומתפללים," ובבריי' שמביא גמ' משמע שחיוב הוא; והוא מפני שמחלקת הוא, שיש שסברו שחיוב הוא, ויש שסברו שאין לעשות כן (אבל מביא מה שהיו נוהגים לעשות כן להראות שיש טובה במה שעושים כן, אלולא ביטול התורה שבו). אז, אם נחזור לנידון שלנו, נאמר שכיון שסיפור זה היה עם חסיד (ונניח שזה שווה ל"חסידים הראשונים," ממילא צריך לומר שהוא חלק על המהרש"א, ולכן ידע השר להקשות לו מן הקרא. אבל, המהרש"א מפרש לפי המשנה שלנו, שאינו כשיטת החסידים. ותחשב.
- אגב, הבנתי שכמו שלכא'ו המציאות הוא שיש דברים רוחניים שאנו לא מבינים אותם בכלל, כמו ה' ומלאכים, כך יכול להיות שלדברים גשמיים שאנו מבינים, יש קרק' רוחניים שאנו לא מבינים. נראה שקדושה הוא קרק' כזה, שאם החפץ קדוש, הכוונה היא שיש ל ו אותו קרק' רוחני של קדושה.
- בדיון גבי שומע כעונה, נראה שיש שלש צדדים עיקרים:
1. יוצא על ידי מעשה שמיעה.
2. יוצא על ידי אמירת חברו, כיון שמיוחס לחברו. יש לדון איזה חלקים יש ליחס, שאולי יש מה שגרם אותו לעשות דבר, או מה ששמע אותו, או מה שכיוון לצאת, או מה שחברו חשב עליו לצאת.
3. יוצא על ידי אמירת חברו, כיון שמיוחס לאמירה. היחס לאמירה יהיה או מפני שמיוחס לחברו או מפני שגרם את האמירה (לא נ' שזה יהני בכל מצב).
- ע' בחגיגה (ה:) ברב אידי אבוה דר' יעקב בר אידי. אם לא משנים את הגי', נמצא שקוראים לו "רב יעקב בר אידי" אף שאביו היה רב (שקורא לו רב אידי). הרי, זה קשה על רש"י בתענית (כא:), שמשמע שכשאומר "רב" בכוונה הוא. אפשר לומר שרק אם נאמר "רב" כשהוא האב, אז מוסמך הוא. אבל, אפשר להיות שייקרא "רב אידי" אבל אינו מוסמך, ולכן נקרא "רב יעקב בר אידי."
- יש חקירה ידוע בדין שומע כעונה, אם השומע ממש כעונה או אינו ממש כעונה, אלא שלא צריך לענות. בכ"מ (ובפרט בשיח שי על פסחים, בפרק בתרא) דנינו מהו הכוונה, אבל נראה לנו לבאר החקירה ככה. צד ראשון אומר שהוא מדין שתיקה כהודאה, שלכא' הוא שכיון שהוא עומד בפני מי שאומר כן, ולא אומר כן, כאילו מוסר שגם הוא חושב שהוא אמת. (אין זה כל כך פשוט, שבכ"מ יכול להיות דבר שאי אפשר לו לדעת, כמו אם הוא שומע ברכה שאומר שה' עשה את הכל. צריך לומר שכיון שאינו יותר קל לחבר שלו לדעת, היה לו לומר שלא נכון שוודאי הוא, אלא עומד במצב ספק.) עיקר של דיבור הוא מסירת דבר, ואז שמיעה מהני. (ויש לדון אם אז נוכרח לומר שגם כתיבה מהני. ויש לדון, שאולי שם אינו כל כך קל לדעת, שרק מי שקורא מה שכתב מבין. ותחשב.) זהו צד ראשון. החולק יחלוק, או מפני שצריך דיבור, ולא מסירה, או שאינו מוסר אותו כל כך, ואינו ברור מה חושב, או שאינו קל להבין כן, שצריך גם ראייה, שצריך לדעת שהוא שם כדי לדעת שהוא מסכים, ולא רק שמיעה. (ויש להעיר שנראה לי שני צדדים בצד זה. צד ראשון הוא שמוסר שהוא מסכים לזה, ומוסר כן על ידי שתיקה שלו. צד שני הוא שמוסר שזה נכון, והוא שבידו לעשות שלא כל כך פשוט שהוא נכון, שאפשר לומר שחולק עליו. אבל, אינו עושה כן, אלא שותק. אז, כאילו עשה מה שהוא נכון בדעת בני אדם, ואז נחשב שהוא אמר אותו.) צד שני הוא שאין זה הענין כלל, אלא הוא מפני יחס למדבר, שעושה שגם הוא יוצא בלי דיבור. ותחשב.
- יש חיוב לאהוב את ה' "בכל לבבך...." יש להעיר שיש שני דרכים לבאר את זה. דרך ראשון הוא שמבאר איך לעבוד את ה' – נעבוד את ה' בכל לבבנו. דרך שני הוא שמבאר מתי לעבוד את ה' – בכל מצב של לב, עדיין צריך אתה לעבוד את ה'. ותחשב על זה.
- עיין בגמ' בשבת גבי רבי אלעזר בן עזריה. קצת קשה, שחזר לו תורתו, ואז קשה למה לא הובא בשאר משניות. יש להעיר שרבי יוסי ורבי שמעון תלמידי רבן יוחנן בן זכאי גם כן לא הובאו במשניות. אבל, שמעתי שתוס' אומר שמפני מעשה זה לא הובא במשנה. לכאו', הביאור הוא שלא חידש הרבה, כיון ששכח. נראה שרק התפללו שיוכל לזכור מה שידע בטורח. היה לו כוח גדול בלימוד, וכיון שהפסיד את לימוד שלו, ה' נטל ממנו אותו הכוח. התפללו שיוחזר לו, וכיון שהוחזר לו, טרח שאר חייו להגדיל לכמו שהיה. אבל, כיון שהיה עוד טורח להיות כמו שהיה, לא גדל עוד כחבריו. ותחשב.
ענין שינה עליו לעכב-נראה שגם יש להוסיף קצת טעם, לומר שבעצם כל הלכה מעכב. אולי יש לחדש שבשאר מצוות אין סיבה טובה (או, על כל פנים, אין סיבה טובה כל כך חשובה), חוץ מקיום המצווה, ואז רק בזה יכול להיות עיכוב. אבל, עיקר קרבנות הוא בריצוי. אם כתוב רק פסוק אחד, נאמר שאומר שמעכב חלק מן הריצוי, אבל מקיים את החיוב שלו. ותחשב. אבל, יש להעיר שעדיין צריך להיות שיש קצת ריצוי, או שלא צריך ריצוי כדי להוציא ידי חיוב שלו. ותחשב.)
- ביני ובין א.מ.וו יצא הערה שלכאו’ בני יהודה היו פחותים מגיל שראויים לעונש כשבאו על תמר, שיהודה יצא מן האחים במכירת יוסף, וכבר היו בנים לפרץ וחצרון. כדי לעשות שהיו בן יג’, ואף זה מחודש, שמיתה ביד"ש אינו לפני עשרים, ואולי אף הוא בדר"כ אחרי ששים, צריך להיות שהולידו בן שמונה או תשע. ותחשב.
- העיר לי א.מ.ו. שכשהיה מנשה מתרגם לאחים, היה בן שמונה, שהרי יוסף נשא אסנת כשנעשה שני למלך, שהיה לפני שני שנים של רעב ושבע שנים של שובע.
- הקשה לי א.מ.וו. למה אומר גמ’ בב"מ שיוסף הכיר את האחים שהיה להם זקן, שיש אחים שהיו כמעט אותו גיל, כמו זבולון. אפשר שהיו קצת יותר גדולים, ואז היה להם זקן. גם אפשר שכיון שיוסף היה מסלסל בשערו, היה מגלח. דחוק. יותר נראה שהיכר ראובן ואחים היותר גדולים, ומזה הכיר את שאר האחים.
- יש להעיר שאם נניח שבנים נולדים כסדר הקרא, נמצא שאף שיוסף נולד אחרי שבע שנים מנשיאות יעקב, בין זה לזה היו תשע בנים נולדים, עם זמן הריון לכל אחד, שנולדו ראובן, שמעון, לוי, יהודה, גד, אשר, יששכר, זבולון, ודינה. ותחשב.
- חלקו אחרונים למה אין בשר בחלב בששים בבשר נגד החלב, שרע"א אומר שהוא מפני שאינו כדרך בישול, ואחרונים אחרים אומרים שהוא מפני שבטל. לצד שני, קצת קשה, שיודעים שש"ע סובר שאם לא נודע לו, לא בטל (ולכן צריך ביטול בפעמיים ששים בתחיבה שנית). אם כן, כיון שלא בטל, כולו יהיה בשר בחלב מיד, ונמצא שנאסר הבשר והחלב. אז, בוודאי לא מהני פעמיים ששים, וגם ייצא שדין ששים בב"ח, שהוא משנה בפי’, הוא נוגע רק אם נודע לו כשנפל. אבל, אם רק נודע אח"כ, כבר נאסר וכבר נ"נ, ונמצא שאסור לאכול אותו תמיד, וצריך ששים נגד כולו. ותחשב.
- אולי ענין לאו השווה בכל כמו ענין מצוי, שנמצא שמקיים אותו כ"ז שלא עובר, וכיון ששווה בכל, נמצא שהוא מאד מצוי, שכל אחד מקיים אותו תמיד. ותחשב.
* Footnotes
[fn:1] באמת, ק"ק למה רש"י שם מניח כן, שלכאורה לא רואים חזרה ממה שאמר גמרא מתחילה חוץ מנוקדה של רתיחת המים. ותחשב. ונראה שבא לתרץ קושייה על עוג, שלא היה לו קרנות לקשור. ועיין שם.
[fn:2] באמת, איני יודע למה הוא כן, אבל לא מצאנו מי שיתחיל בין קרנות. ונראה שהוא שאז יכול למעט בקווים שכותב.
[fn:3] ואף לא משמע כמאירי, שם לא היה כן, לא היה עושה שיכולה לבדוק, שמי יאמר שיהיה זמן של כעס. ויש לומר שלא הניח לה, אלא עשתה כן בפני עצמה. כן משמע.
[fn:4] ונראה ששם אינדיא בא מהינדו, שהוא ריליגיא"ן שלהם, והיו כל בני אדם משם נקראים הינדויים לפני זמן.
[fn:5] אגב, יש לדון אם היה כבר הינדואיזים אז, ועל זם זה נקרא אינדיא כן, או שהיה הינדואיזים נקרא על שם אינדיא.
[fn:6] לא ממש אומר לעשות שני דברים קרובים, אלא שמנין שאינו כל כך נכון נאמר שהוא around מנין הנכון. ותחשב.
[fn:7] צריך לחפש למקור של אותו מאמר.
[fn:8] אלא שכמובן, היו בציורים שונים. וע"ש.
[fn:9] אין לי צד נגד זה אלא אם כן נאמר ששמה שחושבים שעושים קנין אינו ממש עושה קנין, אלא מה שעושה קנין הוא מה שקרה אותו דבר קצת לפני כן. ק"ק למה יהיה כן; אולי הוא מפני שמעשים אלו הם חשובים במה שגורמים שחושבים בני אדם שיש קנין, והרי לא יכול לגרום כן מיד, אלא לאחר זמן, שצריך קצת זמן לבני אדם לראות ולחשוב. ותחשב.
[fn:10] אם לא שנאמר שמי שאינו שמח בשתיה לא ישתה. אם נאמר כן, זה יפטור אף כמה אנשים.
[fn:11] למשל, לקלס מי שמשחק בכדור.
[fn:12] גם נתמעט שאר זמנים אם כבר התפלל באותו זמן, שאז אין צורך להתפלל בו. ותו"ת.
[fn:13] היה לי דיון כעין זה עם א.ד.ר. (אבל לא היה א.ד.ר. בחלום. איני זוכר מי היה, אבל אני זוכר שהיה איש ישיביש. חושב אני שידעתי אותו ממחנה תורת חיים, אלא שגדל מאז.) באמת, ומסתמא החלום בא מזה. על כל פנים, נשמע טוב שאני חולם על לומדות של טומאה.
[fn:14] המילתא דבדיחתא שאמרתי הוא שבוודאי בא מרוח הקודש, שהייתי כל כך יעף שלא הייתי יכול לחשוב על דבר כעין זה.
[fn:15] אבל דע שהיו ת"ח אחרים באותם דורות, ואף אלו שכנראה היו תלמידי רבי עקיבא, כמו שאומר גמ’ בעירובין שהיה תלמיד שהביא לו מים ליטול ידיו, ואינו מן החמש. באמת, כל הגמרא יבמות צריך ביאור, שהיו ראב"ע ורבי ישמעאל קיים, ומה קרו עם כל תלמידים שלהם. וצריך ביאור.
[fn:16] יש לציין למה שאומר ר"י אייבשיץ שעשו מגדל זה כדי שלא יהיה להם gravity, וילכו לירח. צריך, אז, למצוא איפה כלה gravity לבני אדם. ותחשב.
