* Hakdama
* To The Tune of: V’Hi She’amda (Yankel at the Seder)
Begin with Chorus:
Every Yom Tov we’re reliving the events of years before
we return to all that happened and they come once more;
And, every Pesach every year, we’re returning once again,
and we’re marching out of Egypt through the nissim of Hashem.
Before Yom Tov to prepare is a task we have to do
if we want to be affected by the day we’re living through.
If we think about the day, then we’ll surely take away
all its lessons and kedusha, and make changes which will stay
Chorus.
And on Pesach it is crucial that we learn from what was done,
because Pesach is the first of all the moadim to come;
we remember it each day in the krias shma we say;
it’s the founding of our people; it’s our national birthday.
Chorus.
For what happened then will teach us lessons for our present times-
it’s a personal experience which opens up our eyes
to the way the world is run, to how everything is done,
that Hashem’s the master of the world, tat Hashem is one.
Chorus.
* 1
* To The Tune of: Lev tahor (Dveykus I)
The Mitzrim enslaved us, and yet the galus was not caused by them-
the galus had a purpose, orchestrated fully by Hashem.
To refine His children, Hashem had to make us into slaves,
so we could be his nation, after, through Hashem, we were saved.
Chorus:
As metal in a furnace, leaving just what’s pure,
Hashem brought us to slavery, to purify us for
Our role as his nation, a nation apart,
with spiritual freedom in our heart.
As slaves in Paroh’s Egypt, our physical enslavement hurt us so,
but far worse was our ruchniyus, sinking us as low as we could go.
Our freedom from Mitzrayim gave to us a holiness to stay,
ensuring that we always will have freedom in the most important way.
Chorus.
* 2
* To The Tune of: Our Fate is in His Hands (The Golden Crown)
By freeing us, Hashem’s great strength was put on real display-
He could have had us walk out free in just a normal way-
instead, he made us miracles, and let his nation see
and understand he’s in command of every entity.
Chorus:
And all could see and watch as we were shockingly set free,
teaching them about Hashem and showing you and me
Hashem’s the boss, does what he wants, controlling everything-
no entity has strength like he- Hashem’s the only king.
By freeing us, he taught us well, and gained our faith in him,
with mitzvos to remind us of yetzias mitzrayim
we turned from idol-worsh’ping slaves to servants of Hashem-
He even made believers of King Paroh and his men.
Chorus.
The korban pesach also showed- avodah zarah’s weak;
we took the god they’d so revered, and roasted lots of sheep.
In this their faith the Jews declared, no longer were they swayed
by idol gods with powers fake- in Hashem they placed their faith.
Chorus.
* 3
* To The Tune of: Ani Ma’amin (Dveykus IV)
Nowadays, we struggle hard to try and understand
that all we see is only make believe
it seems to us that things are caused by prowesses of man
Alas! Sometimes, our senses do deceive.
Chorus:
Ein tzayar KaHashem
what we see seems so genuine
know there’s so much we don’t see
Hashem’s what makes things be
there is no one else but He,
Hashem is there directing behind each scene.
When we think we get it all, its time to think again
and think about yetzias mitzrayim
everything is but a piece in the pattern of Hashem
and everything’s attributed to Him.
Chorus.
* 4
* To The Tune of: Rabos Machshavos (Rabbis Sons I)
Sometimes it seems
that what will be
is all determined
by otzem yadi.
Then how did Paroh
never know
that in his palece
Moshe did grow?!
Chorus (both paragraphs):
Hashem alone,
it’s clearly shown,
has total power and full control
He’s all aware,
He’s always fair,
His every action has a special goal.
In an act so puzzling,
the shvatim sold
their brother Yosef
for a drop of gold.
So understand
it all was planned,
caused by Hashem,
and not by man.
Chorus.
We feel we’re thinking
we feel we choose
now watch what Pesach’s
story proves.
Why take an eved
and make him king,
the chief commander
of everything?!
And how did Egypt
refuse to see
its time to set the
bnei yisrael free?!
Our every feeling,
our every thought-
it seems ours, but
we know it’s not.
Chorus.
With plans so cunning,
with plans so wise,
He runs the briah
before our eyes.
King Paroh thought
he could choose or not
to free our nation
but he was taught:
Chorus.
So let’s not make
that same mistake
for all we see is
a patent fake.
Hashem devised it,
he pulled the strings,
he fully runs it,
causing everything.
Chorus.
We also see
that prophecy
gives true rendition
of what will be.
For all that happened
Moshe was told,
and as he heard it
it did unfold.
Chorus.
He make decrees
not sweepingly
but on each yachid,
individually.
And every evil
has its treturn
from every makkah
we all did learn
Chorus.
* 5
* To The Tune of: The Little Bird (Tzlil V’Zemer)[fn:1]
Tortured in mitzrayim,
our fathers saw no hope.
‘midst tearful mournful sighing,
they thought of Hashem and spoke:
”Hashem, we’re so forsaken,
we’re left with no way to cope;
Hashem, please hear our crying,
and set your children free.“
Running from their masters,
keen upon the chase,
while we could run no faster,
we had no hiding place.
We cried out to Hashem
”Please won’t you grant us a nes“
and walked into the water,
as he split the sea.
Hashem hears all who call him,
and listens to each word
He saves those who are falling,
ensures that their troubles are cured/
and though we may seem small,
our voice is always heard,
He greets our cries with kindness,
and listens lovingly.
Though sometimes we’re not seeing
an answer to our cries
why waste our strength on pleading
why waste our precious time
but we’re tolaas yakov
we all must realize
persistently continue,
he’ll answer faithfully.
And as you’re praying, notice
and pay attention to
although it seems so hopeless
what you are going through
Hashem gave you this trouble
knowing what you would do
for Hashem’s true goal is
your praying tearfully/
Hashem hears all who call him,
and listens to each word
He saves those who are falling,
ensures that their troubles are cured/
and though we may seem small,
our voice is always heard,
He greets our cries with kindness,
and listens lovingly.
* 6, 7
* To The Tune of: Trust in Hashem (I Hear a Mitzvah)[fn:2]
By freeing us from Egypt,
Hashem made us his slaves,
we follow every single mitzvah
every single day
he made us and he saved us
and caused that we should be
his faithful servants for forever-
avadim shehotzaisi
Chorus:
Serving Hashem
fulfilling His decrees
liberates our nefesh
and makes us truly free.
The freedom to chase pleasure
can never make us free
it strains us and constrains us
as we’re feeling so empty.
Only through the torah
is proper cheirus felt
it breaks our yetzer hara and it
frees our deeper self.
Chorus.
And that’s why we, on Pesach,
are machmir as can be,
we show we love restrictions
for in slavery we’re free
we also count the omer
waiting eagerly
for the time we got the torah
that would set us really free.
Chorus.
* 8
* To The Tune of: Ani Maamin[fn:3]
On the Seder night,
we all recount a tale
and we try hard not to fail
to say the story right.
For it holds
the basics and the keys
to all that we believe
and so it must be told.
Chorus:
We tell our children- that is true
But first we tell to ourselves too
and think about the lessons that we say.
Think about it ‘till you feel
it’s happening, it’s really real
and live it all in a deeper way.
Only once
do we have this chance
now it’s in our hands
now it can be done.
We receive
a special holiness
allowing each of us
to teach what we believe.
Chorus.
And we must
thank Hashem, for He,
with nissim set us free,
He did so much for us.
Thank Him well
He had no pressing need
In him, we’d still believe
If it happened to someone else
Yes, He did
His nissim to save the Jews
not only to prove
the power that is his
Chorus.
And at the end
we pour an extra kos
for a special guest we hope
whom Hashem will send
Eliyahu,
for this noght we can bring
Moshiach, our king,
to make us free again.
Chorus.
* 9
* To The Tune of: Finjon
Mitzrayim left no way to leave,
as far as all people could see,
there was no big war,
no fighting occurred
and the king was so nasty and mean.
Chorus:
The nes that took place in yetzias mitzrayim could not be created by men
We left, quite bereft of all sustenance trusting and putting our fauth in Hashem-
the more than three million men woman and children who marched to the desert that day.
Six hundred thousand now free
without any food they could see
they followed Hashem,
theese thousands of men,
Hashem would make sure they’d succeed.
Chorus.
* 10[fn:4]
* To The Tune of: Yisroel V’Oraysa
The Jews were chased, they need a nes, to be saved from swords and knives.
To split the sea is what must be to save our nation’s lives.
We were not good and so how could the sea be split to make us saved.
We asked Hashem to help again, a battle would be waged.
Spiritually, this could not be, we were not devout.
But Hashem is above the way the world runs and so He helped us out.
Many thought, they were not taught, other deities did have strength.
Now they knew Hashem was true vayaaminu baHashem.
Everyone who chose to come with bnei Yisroel felt
zeh keili they all could see, more than Yechezkel.
All who hear had fits of fear, trembling frightened men
as we began a song and dance, az yashir laHashem.
* 11
* To The tune of: Vay’hi Beyeshurun Melech
Just like we believe from Mitzrayim we did leave
with Hashem’s nissim, earning Him our trust,
the same thing will be true from this bitter galus too
He’ll send Moshiach, and he’ll rescue us.
Mitzrayim had but one prophecy
and look at what wonders came to be.
The next geulah has many and many
imagine what will be when Hashem will set us free.
* 12
* To The tune of: Chasal
lman tisaper es asher hisalalti
Hashem made the mitzrim a silly mockery
they looked so strong yet all were proven wrong
they looked like giborim but really were nothing
when Hashem destroyed them and beat them thoroughly
Egypt was a symbol of strength and majesty
through the bitter famine they had what to eat
guided by Hashem through yosef’s famine plan
while others would cower, they held their power
and saved by yakovs blessing, making them mighty
but when we left mitzrayim, all was plain to see
Hashem had sent them blessing for one purpose only
He made them grand so we would understand
he built up their kingdom granted them wisdom
all to help his people when he set them free
the same is true in (all) our struggles too
Hashem has a reason for all which he does do
All that he does has a perfect cause
we’ll think we’ve got it but sometimes we’ve botched it
its a theater by Hashem that we must all see through
lman tisaper es asher hisalalti
Hashem made the mitzrim a silly mockery
they looked so strong yet all were proven wrong
they looked like giborim but really were nothing
when Hashem destroyed them and beat them thoroughly
* Footnotes
[fn:1] Also the Yisro song on 613 Torah Avenue, as well as an Israeli ant-war song (Be’Arvot Hanegev) and a Russian anti-war song.
[fn:2] The high part is also The Russian sailor’s dance in The Red Poppy.
[fn:3] This is a rather obscure English Ani Maamin; I’ll send you the tune.
[fn:4] There was not enough of a unifying theme in this section to write a chorus. Every paragraph with two lines is a high part.
