לשון הגמרא הוא, “הו”א תירוש ויצהר... הוא דאין תורמין... אבל תירוש ודגן... כ’ תרים מהגוי אהאי לא לקי.”
מרישא ד”הוה אמינא רק על תו”י אין תורמים” משמע שבהוה אמינא תו”ד תורמים.
אבל, מסיפר ד”כי תרים... לא לקי.” משמע שבהוה אמינא תו”ד אין תורמים, אבל אין לוקים עליו.
ברשי ד”ה אבל תירוש ודגן כ’, “אימא דמצי תרם....” ואז, לכאורה, נראה שמפרש שההוה אמינא היא שיכול לתרום. ויש לדחות שאין רש"י קאי על צד ראשון, אלא על צד שני. וזה קשה, שלמה יחכה רש"י לבאר כל זה עד צד שני (שבכלל רש"י זה יש כמה דברים שצריך גם לצד ראשון).
ואם תחושב ותעשה חשבון שאם צד הראשון סובר שתורמים בהוה אמינא, ושצד שני קאי גם על דגן על דגן (ורשי סובר כשניהם), אז אין שום חילוק בין צד ראשון לשני. ובאמת, יש לדון אם יכולים לומר לשון אחר בגמרא אם אין ביניהם אלא לשון. ובאמת, כאן כתב שיטה מקובצת שראוי צד השני למחק. לכאורה, הוא מפני שסבר שאין חילוק בינו לבין צד ראשון. ודע שרש"י כותב כ”ם שכותבים לשון אחר אף אם אין ביניהם אלא הלשון שבו אומר ענין שווה.
ועל צד הגמרא, נרשם ש”מילת לק’ צריך תיקון,” וכן כ’ הרב יחזקאל לנדא )הובא בשמו בסוף הגמרא). ובאר רי”ל ש”מלקות מאן דכר שמיה.” ולכאורה, ר"ל כמש”כ שמרישא משמע שקאי על איסור לתרום ממין על שאינו מינו, ולא על חיוב מלקות.
במראה כהן הביא ההגההה שבצד, וביאורו בע”א. באר שאין כאן שום מחלקות; אין בתרומת מין על מין מלקות בכלל. ואם כן, אף למסקנא, אין לוקים, ואף בתו”י אין לוקים. אלא, מוכרח שקאי באיסור.
ולא ידעתי איך יודע שאין לוקים, שלכאורה, הוא לאו רגיל. (ברמב”ם לא מזכיר שום מלקות.) ואולי הוא לאו הניתק לעשה, שצריך לתרום עוד אחר שתרם ממין על מין אחר, וכסברת ריב”ח לעיל. וקשה, שמשמע שלא הסכימו לו רבנן. אלא, יותר ניחא שהא דאינו לוקה הוא דאין אזהרה לו. וכן פשוט.
אבל, כ’ מראה כהן, כיון שנכתב מילת “לקו” בכמה מקומות, קשה לומר שבכל הגירסא נשתבש. ולכאורה, אם כן יל”פ שאינו ר”ל לק’, שחייב לט מלקות, אלא שלק’, ר"ל שעונש יש לו, שצריך לתרום שוב פעם. וצריך ביאור מה עונש יש בזה. וכ’ המא”כ בעצמו שר”ל “לא ילפינן בק”ו.” ולכן מפרש שר”ל “לא לק”ו” ולא “לא לקו.” ועוד יש לפרש שר”ל “לא לקו” ולקו הוא ר”ת “לקל וחומר” ילפינן[fn:1]. ועוד יש לומר שר"ל “לא לק’,” ולא “לא לקו.” והק”ו שמפ’ הוא הקל וחומר דכלאים מבכורות נד. (עיין שם).
וע”ז ק”ק הלשון, שאומר “אימא כי תרים... לא לק’,” והיה לו לומר, ,אימא יתרום... דלא לק’.” ועוד קשה שמלשונו ד”אימא... לא לקי קמ”ל” משמע שהקמ”ל קאי על ה”אימא” שהוא דלא לקי, שלא ילפינן קל וחומר. וקשה, שלכאורה, למסקנא אינו מלמד שלומדים את הקל וחומר, אלא מלמד שאין תורמים מזה ע”ז, ושדין ק”וח נכון.
ותחשב על כל זה.
יב- ועל כל פנים, צריך לפרש לפי הצד שבזה חולקים, במה חולקים:
1. אא: ראה שחולקים במה הוה מניחים בלי הקרא. צד ראשון סובר שמניחים שאסור, אבל פטור, וצד שני סובר שמניחים שמותר הוא.
2. נראה שהבנת צד שני הוא שאין שום מקור לומר שאסור הוא.
3. נראה שהבנת צד ראשון הוא שלומד האיסור מן תו”י, כמו בגמרא בכורות (ובזה נוכל לתרץ את הסתירה בין גמרא להא דבכורות), אלא שכיון שאין עונשים מן הדין, היה צריך קרא.
4. יג- ובחק נתן גריס: “ל”א הא דגן ודגן דכולהו מיני דגן כי תרים...” וגריס צד שני דלא כפשטות גמרא דידן. לזה, סבר צד שני שבלי קרא ד”ראשיתם,” הוה ידעינן שאין לתרום מתירוש על דגן. צריך “ראשיתם” רק לאסור דגן על דגן.
5. אא: פשוט שחולקים במה היה ידעינן לפני “ראשיתם.” צד ראשון סובר שהיינו יודעים רק שאין תורמים מתירוש או דגן על יצהר, וכן להיפך. צד שני סובר שהיה אף ידעינן שאין תורמים מתירוש על דגן, וכן להיפוך.
6. בב: הדרך הפשוט לבאר את זה הוא שלצד ראשון, אין לומדים הקל וחומר דבכורות (וצריך ביאור למה לא), ולצד שני לומדים, אלא שגבי דגן על דגן, יש להפריך, מה לדגן על דגן שהם חד מין. (ויש לדון מה עושה אותם חד מין. ולכאורה, הוא שכן נחשב בעיני בני אדם, והוא מחמת כמה דברים שנודעים באופן דומה, שנראה דומה.... גם יש לומר שהוא אותם דמיונים. ותו”ת.)
7. (ולכן, יש לפרש שגם צד ראשון סבר כאותו פירכא, אלא שסבר שאף תירוש ודגן הם קצת כמין אחד, שדומים הם. ולכן, אין לומדים את הקל וחומר. ועוד יש לפרש שאינו סובר כקל וחומר, שסובר שיש ג’ סוגיות בכאים:
8. אאא: אם שני דברים אינם נחשבים לזרעים אחרים, אז אינו כלאים. משל לזה הוא תפוחים עם תפוחים, אחד של מאקינטו”ש, ואחד של סבתא סמי”ט.
9. בבבב: אם שני דברים נחשבים לזרעים אחרים, אז אסור. משל לזה הוא תירוש ודגן.
10. גגג: אם שני דברים נחשבים לזרעים אחרים עכ”כ שאם נזרעים ביחד, אינו נחשב כחד שדה, אז מותר.
11. סבר צד ראשון שמשל לזה הוא תו”י, ולכן אין בו כלאים. אז, א”א לעשות קל וחומר, לומר שדו”ת הם יותר חלוקים מדו”י, שמכלאים, אין ראיה שדו”ת הם יותר חלוקים.
12. צד שני, לכאורה, ידחה בשני אופנים:
13. א: אולי לא סבר שיש דבר כגגג.
14. ב: אולי סבר שאף שמלומדות אין לעשות קל וחומר, עדיין מדין יש קל וחומר, שראינו גבי כלאים יותר רחוק בין דו”ד לדו”י, ואז גבי תרומה גם כן צריך יותר ריחוק.
15. ב: יש עוד דרך לבארו, והוא קומפליקייט”ד, שתלוי בצדדים לעיל.
16. כולי עלמא סברי שאותו הדרשה דגמרא בא מ”...תם.” דראשית. חולקים מה דורשים מראשית. צד ראשון סבר שצריך ראשית לגופיה, ולכאורה, הוא שתרומה יקדים למעשה, ואז, מ”תם” דורשים דין דע”ד, ודין דע”ת.
17. צד שני סבר שמראשית דורשים שאין תורמים דע”ת. ויש לעיין למה לא צריך לגופיה:
18. א: אינו סובר שצריך תרומה להקדים למעשר.
19. ב: דורשו ממקום אחר (לכאורה, מ”מלאתך ודמעך לא תאחר.”)
20. ג: סבר שמדאמר ראשית, ולא רק ראש, אולי יש לדרוש שנים.
21. ד: סבר שיכול לקרות הקרא בשני דרכים: חלב תירוש ודגן [ראשית], וגם [ראשית] אשר..., ואז דורשים דין שניהם. דורשים כעין זה בכמה מקומות.
22. יד- קשה להבין קושיה זה:
23. א: הגמרא מניח שזה קשה רק לרבא. קשה מה חשב לתרץ קושיה של צד השני על אביי. לכאורה, יש ממה נפשך שקשה. אם סבר כצד שני, ושאין זה חל, אז, קשה למה צריך להחזירו. ואם סבר דלא כצד שני, וסבר שאף שצריך להחזירו, עדיין הגט חל, שאם למשל, יצץה וזינתה, לא תיהרג, אז גם לאביי קשה למה לא לק’.
24. ב: הגמרא בוודאי כבר ידע הדין של לאו הניתק לעשה (ברייתא מפורשת הוא). הגמרא גם כן יודע שצריך להחזירו. אם כן, קשה למה לא ידע שהוא מפני שהוא ניתק לעשה. קשה למה צריך קרא לצאר מהו העשה. אל תתרץ שאם לא כן, לא היה יודע גמרא מהו העשה, שאם כן, יקשה על הא ד”מחזיר.” ומדלא מק’, מוכרח שידע שיש שום לאו. לכאורה, בזה יש שני דרכים:
25. אא: אולי יש אפשרות שיצטרך לתקן הלאו, ולא יהא ניתק לעשה, כמו אם, למשל, אמר תורה לאו הניתק ללאו. אז, גמרא חושב שכאן הוא לאו הניתק ללאו. וקשה למה נניח כזה.
26. בב: הגמרא חשב שכשאומר מחזיר אנו מזכיר מ”ע, אלא מציאות, שכיון שאין הגט חל, אז מחזיר, ר”ל שמחוזר הוא, שלא חל שום גט.
27. ואז, בתירוץ הגמרא, מדתווה תורה להחזירה, מוכרח שנתגרשה לגמרי, ויש עוד ענין בחזרתה.
28. טו- צריך להבין צד זה:
29. א: צריך ביאור למה לא הק’ כצד ראשון, למה אינו לוקה, שבודאי לא ידע שיש עשה דחזרה, שאי ידע לא היה שום קושיה על אביי.
30. ולכאורה, נראה שחולקים רק איזה הוא הקושיה הכי טובה.
31. ב: קשה למה מניח שלא חל; הא בוודאי חל, שאם לא כן, למה צריך להחזיר אותו, שהרי כבר הוחזרה ועומדת הוא.
32. ונראה שגם צד זה הבין שמחזיר ר"ל שמוחזר ביא. וזה קצת דחוק, שהניחא לרבא, כשמפ’ שמחזיר הוא מוחזר, אז, קמפ’ ברייתא לרבא בענין שיהיה כשיטת רבא בסתם מקום, שאין דבר חל. אבל, לאביי, קשה, שעיקר שיטת אביי הוא שבסתם מקום, חל, ואם כן, למה נפרש מכאן שאינו חל. ואולי רצה להוקימו כשיטת אביי, שאין לוקים על מה שאינו חל.
33. ועוד יש לומר שעיקר הקושיה אינו שאינו חל, שבוודאי סבר צד זה שחל, אלא מקשה למה מחזיר אותה. ובאר המקשן שאין קושיה זו קשה לרבא, שלרבא יכולים לפרש מחזיר למוחזר. אבל לאביי, אף זה אי אפשר שאם כן נקשה שהרי סבר שאם עבר, חל.
34. טז- לכאורה, אין לפרש שלצד ראשון דורשים “עד בא השמש” כלל, ואז חולק בדין כסות ליללה, או סבר שלומדים שניהם מהשב תשיב, שהרי למה נאמר שחולק בזה, שהרי סתם גמרא הוא במקבל, ועוד שאם כן “עד בא” הוא מיותר.
35. יז- וצריך ביאור למה נקטו קראי אחריני. יש ג’ דרכים:
36. א: שניהם סוברים שבגמרא ננקוט היותר מחודש, להשמיע חידוש יותר. אז, צד אחד נקט כסות לילה, שאינו חיותא, וצד אחר נקט כסות יום, שאינו מצטער בליהם (כמש”כ רש"י).
37. ב: שניהם סוברים שננקוט הכי פשוט, כדי לתרץ לרבא בענין הכי פשוט, וחולקים איזה יותר פשוט.
38. ג: חולקים אם ננקוט הכי פשוט או הכי מחודש. ויש לבאר ב’ דרכים בענין מי סבר מה.
39. יח- צריך לבאר במה חולקים:
40. צד אחד לא סבר כצד שני:
41. א: שצד שני אינו מבאר למה ואיך אינו תלוי, שלכאורה, על פי סברה, תלייה טובה היא, אלא מביא ראיה שאינו תלייה. סבר צד ראשון שיותר טוב להקשות מדבר שמבאר איך המיהמימרא אינו נכון מלהקשות מדבר שהוא ראיה שאין המימרא נכון.
* Footnotes
[fn:1] איני יודע כוונתי כאן; אולי הכוונה הוא שיכול לומר כן אף בלי “. דחוק.
