* בענין מי הוא סתם  רב נחמן:
* א.שיטות במי בוא ר"נ
מצינו בכמה מקומות שיש שני תנאים עם חד שם. בדר"כ, נקראו בשם אביהם. לכן, מצינו שיש, למשל, "רבא בר שרשום" וכדו'. בדר"כ, חד מן התנאים או אמוראין שיש לו שם זו יקרא בו סתם; ואז נמצא שרבא בר יוסף נקרא "רבא." חולקים מי הוא סתם רב נחמן. יש להעיר שהסיבה לדון בזה הוא, לכאו', מיוסד על גמ' קדושין (מד.), שאומר שיש נפקא מינא לענין "למרמא דידיה אדידיה," והוא שכשנדע שיטת אמורא, נוכל להוכיח מיניה, לפעמים, שיטות אחרות, שמניחין שלא יסתור את עצמו. מצינו, לכאו', שלש שיטות בזה (וע' לקמן):
1.רש"י משמע שהוא רב נחמן בר יצחק. מצינו שני ראיות שכן סבר רש"י:
1. בגיטין (לא:), מזכיר גמ' מעשה שבו לא הלך ר"נ בר יצחק לרב נחמן בר יעקב כיון שחשש שהוה מבי ריש גלותא (שהיו רעים). אומר שאף שרבא הלך לו, לא הלך רנ"ב יצחק, שלא היה צריך לו. מפרש רש"י שם, "דרב נחמן חתניה דנשיאה הוה." לכאו, ר"ל שמה שלא היה צריך לו היה מפני שהיה חתן הנשיא, ומביא גמ' חולין(קכד). שם, אומר כן גמ' על רב נחמן סתם. נמצא שסובר רש"י שהוא הוא. נוכל לדחות שרש"י לא מפרש למה לא היה צריך, אלא למה הו"ל להיות צריך. יש ע"ז שלש הערות:
א.ק"ק למה יצטרך לבאר למה הו"ל להיות צ', שגמ' כבר הז' עושר רנ"ב יעקב.
ב.ב"ח גורס בדברי רש"י "בר יצחק." אז, צ"ל שקאי על רנ"ב יצחק, ולא על רנ"ב יעקב. אפשר לדחות שרש"י גרס "בר יצחק" בחולין. א"כ, יש עוד דרך לדחות ראיה זו.
ג.א"כ, הו"ל לרש"י לאומרו על "רבא צריך."
1. במגילה (כח:), גמ' קורא לרב נחמן "מחסידי בבל." כתב עליו רש"י ש"רב נחמן בר יצחק מחסידי בבל בשילהי מסכת סוטה (מט:). . . " שם, אומר, "אמר ר"נ לא תתני יראת חטא, דאיכא אנא." יש כמה גרסאות בכל זה. גורס ב"ח במגילה "רנ"ב יצחק" במקום "ר' נחמן." עין יעקב בסוטה גרס "רנ"ב יצחק” במקום "ר' נחמן." נדון בכל הגרסאות להבין אי יש ראיה:
א. אם גורסין בשניהם ר"נ סתם, אז יהא ראיה ממה שקראו רש"י רנ"ב יצחק, אלא אם כן נדחה שאלו הגורסין כן גם גורסין ברש"י "ר"נ."
ב. אם גורסין בשניהם רנ"ב יצחק, אז אין ראיה, שרש"י רק מזכיר דמיון רנ"ב יצחק ורנ"ב יצחק
ג. אם גורסין במגילה רנ"ב יצחק ובסוטה ר"נ, יהא ראיה ממה שמביא רש"י ראיה מזה על זה-שאפשר רק אי חד איש  הוא.
ד.  אם גורסין להיפך, יהא אותו ראיה, וגם יהא ראיה ממה שרש"י קורא האמורא שבמגילה בשם רנ"ב יצחק.
יש להעיר שבגמ' שבת (לז:) קורא לרב נחמן בר יצחק "מרי דעובדא," שפירש"י שהוא מדקדק במעשיו. שם, גורס ב"ח רנ"ב יצחק. יל"ד ל"ל הביא רש"י גמ' זה:
1.אולי אין זה אותו איש (שכאן גרס רנ"ב יצחק, ושם גרס ר"נ)
2.אולי רצה להביא ראיה ממקום דאומר אותו שם, כדי שלא נצטרך לדון מי הוא מי. זה א"א אא"כ גורסין בשבת היפך מה שגורסין במגילה.
3.אולי אין סיבה להעדיף זמ"ז. ויל"ד.
רע"א (סוטה שם; גיטין (לא:) ) מביא ראיה זו. צ"ל שסובר כא[fn:1], ג, או ד.
1. תוס' בכ"מ (ב"ב (מו:), גיטין (לא:), ועירובין (מג:)) כתב שסתם רב נחמן הוא רנ"ב יעקב.
2. מסוהש"ס (ב"ב (מו:)) מזכיר צד שהוא רב נחמן בר אבא.[fn:2]
* ב.הראיות לכל צד
1.מצינו 3 ראיות לזה:
1.בשי"ח ש"י (קדושין (גלגל  שלישי-סו:)), כ' שמצינו שרגיל רנ"ב יצחק לתרץ ע"י קרי וכתיב. בקדושין שם, דורש ר"נ סתם כעין זה.קצת משמע שהוא רנ"ב יצחק. ע' במסוהש"ס שם שגורס "רנ"ב יצחק." א"כ, כמובן, אין ראיה.
2.אולי יש ראיה לרש"י ממה שבגמ' גיטין הנזכר, משמע  שלא היה רנ"ב יצחק צריך לנשיאה. זה מובן אם נפרש כרש"י שם. יש להעיר שאין זה ראיה, לכאו', שקל לומר שאף רנ"ב יעקב עשיר גם כן, אלא שלא הוזכר במקום אחר בגמ' (ולכאו', לא מוזר שלא יזכרנו במקום אחר,  של"ל לגמ' להזכיר שהיה עשיר); אלא שמצינו ראיה כזה בשבת (כח:). הבעיה הפשוטה עם ראיה זו הוא שבאותו גמ' בגיטין גם מזכיר שרנ"ב יעקב הוה עשיר. אז, זה ראיה לומר או כרש"י או כתוס'. נ' שרש"י סובר שלא די שיהא עשיר, אלא צ"ל אף חתן נשיא (שאז נמעט מוכרח שלא יעני).[fn:3] אז:
1.א"א להיות רנ"ב יעקב, אלא רנ"ב יצחק.
2.אולי לא נניח שני חתנים לר"ג. אז, נדחה דחייה ראישונה שכ'.
3.אולי סבר רש"י-וע' לקמן-שמסתבר שר"נ הסתם יהא הר"נ הכי מצוי. לכאו', רנ"ב יצחק הוא הכי מצוי. לא נראה, שאולי מה שלא מצוי הוא מפני שהכל מקום נסתם.
כמובן, אפשר לצרף ראיות שלו. ותו"ת.
2.מביא תוס' 2 ראיות לזה:
1.לא הוזכר "בן יעקב" אלא אם יש עמו ר"נ אחר. יש לדון מה ר"ל:
1.אפשר שר"ל שלא קשה מה שמצינו שלפעמים הוזכר בשם רנ"ב יעקב, ולפעמים הוזכר בשם ר"נ סתם. יש לדון למה יזכיר את זה:
1.אי לא מתרצו, יהא קשה לו. כמובן, זה רע.
2.אולי ר"ל, "אף שלרש"י זה קשה, לי לא קשה, מפני . . ."
2.אפשר שמביא ראיה, והוא שאי אינו רנ"ב יעקב, נצטרך להניח שרנ"ב יעקב הובא רק כשיש ר"נ אחר עמו.
מתוס' ב"ב נראה כשני, שכ', "תדע [ומביא ראיה זו]." יש להעיר שלא כתבו תוס' עירובין בצורה זו (ע"ש), ואפשר שהוא מפני שאומר כצד ראישון. אכתי נצטרך לבאר למה לא יאמר ראיה. ויש להעיר שתוס' בגיטין (וכן בעירובין) בעיקר בא להק' על רש"י-דלא כתוס' בב"ב שבא לבאר מי הוא ר"נ סתם-ואז מסתבר מה שלא בא להוכיח פשטו (ובפרט לצד שני שכתבנו, שבעיקר דן בקושיא שכבר הק' על רש"י). ויל"ד, שמביא ראיה לשיטתו. ואולי רק רוצה חד.
2.גם מביא ראיה ממה שמצינו שבירושלמי מביא רנ"ב יעקב עם רב ששת. בגמ' שלנו מצינו ר"נ סתם הובא עם רב ששת בהרבה מקומות. בעירובין ובגיטין אומר תוס' רק שבשניהן אומר שהיו חברים, אבל בב"ב אומר תוס' שבשניהם הן בעלי פלוגתא. צ"ב ל"ל לומר כתוס' בב"ב-שלכאו' לא חולקים אם הוא אמת. אולי כן ר"ל.
יש להעיר שיש ראיה להיפך, שנמצא שנמצא שסתם שלירושלמי מוכרח (אא"כ נדחה כמש"כ ברש"י לקמן) שאין רנ"ב יעקב ר"נ סתם. הדרך לדחות ראיה זו הוא לומר שאין בבלי וירושלמי סותמין ר"נ שוה. נראה שיש לדון במקור הסתמות:
1.אפשר שנסתמו מי שהביא את המימרא. דע שכשאנו אומרים "מי שהביא את המימרא," יש שני צדדים בזה:
א.רב אשי ורבינא קבעו את כל הגמ'. אז י"ל שהם קבעו את הסתמות.
ב. אפשר שמי שהביא להם המימרות-או מי שאמרו להם. . . -סתמו. וא"ת, א"כ יהיו כמה ר"נ הסתם. וי"ל שכראישון נסתם (א. ר"א ורבינא קבעו כראישון (או כהכי מצוי). ב. רבנים שלאחר הראישון בחרו לסתום כמותו-או כדי שלא יהא קשה או מפני שע"י הראישון, נעשה לסתם, שהיה אותו הנסתם, ע"פ הראישון, הידוע.) כמובן, הצד לומר  כזה הוא שהם קדמו. אז אם נניח שכל אחד סתם-ומסתבר כן, לכאו'-הם יסתמו ראישון. הצד שלא לומר כן הוא:
א.סתמוהו, ורבינא ור"א שינוהו. יש להעיר מגמ' ברכות (לג:) ושבת (טו.) וכ"מ שמצינו שיש ענין לומר לשון רב, ואף שאינו כ"כ טוב.
ב.לא סתמוהו כיון שידעו שיהיו ר"נ אחרים שיסתמו אחרים כמותם. אחר גמירת תלמוד, ידעו שלא יהיה ר"נ אחר באותו קטיגורי, ואז ואכלו לסתום. (יש בזה שני ענינים: 1. חששו שאחרים יקבעו סתמים אחרים, ואז לא קבע, כדי שלא יהיה שני סתמות, שאז יבלבל בני אדם. על זה, יש להעיר שק"ק למה חששו-מפנו מה שהערנו על א. 2. חששו-כדין-שאחרים לא ישנוהו. רצו שאחרים ישנוהו, ואז לא קבעו סתמות. יל"ד, שאכתי יהיו יסתמות שינוי מן הלשון. ואולי רצו למעט. (ויל"ד, שאולי כיון ששרו רב, אין ענין לומר בלשון רב. ותלוי באי אומרין לשון רב מפני כבודו או מפני שבזה זוכרו יותר.))
יש לדון ע"פ מה סתמו:
1.אפשר שסתמו כלשון בני אדם-דהיינו, שהיו בנ"א קוראין לחד ר"נ בשם ר"נ סתם. מפני זה שהיה אותן ר"נ נקרא כן בלשון בנ"א, קבעו שייקרא כן בגמ'.
2.אפשר שמה שלא הזכירו שמו הראה חשיבות לו:
1. הראה שפשוט שעליו דברו-כמו שאומר, "ר"נ הכ"כ חשוב עכ"כ שידוע מי הוא.
2. אפשר שהוה משמע שאין צריך אחר להחשיבו, שחשוב בפנ"ע, ואז מז' בפנ"ע.
3. אפשר שהמדפיסים (הפרינטאר"ס) סתמו. מסתמא, נקטו הכי מצוי ועשוהו סתם.
נראה שפשוט, אז, שיש לחלק בין בבלי לירושלמי:
1.אי ר"א ורבינא סתמו את הבבלי, אז, פשוט לחלק, שרבינא ור"א לא קבעו את הבבלי (ר' יוחנן קבעו), ואז יסתם באופן חלוק. לצד החולק, י"ל שראישון או מצוי היה חלוק.
2.אי תלוי בדיבור בנ"א, לכאו' מסתבר לחלק, שבני ננל היו בנ"א חלוקים מבני א"י.
1. לצד זו, מביא שי"ח ש"י (קדושין-גלגל שני-לג.) ראיה:
בגמ' קדושין שם אומר:"רב נחמן משדר גוזאי אמר אי לאו תורה כמה נחמן בר אבא איכא בשוקא. " לכאו', מבואר ששמו של ר"נ היה רנ"ב אבא. (שם תמה שלא הוזכר ראיה זה. שוב מצאתיה במסוהש"ס הנזכר.) לכאו', גמ' מפורשת הוא; א"א שרש"י ותוס' לא הכירו בראיה זו; צ"ל דרך לדחותו. נמצא 3 דחיות:
1. שם דחה שלא הוה שם אביו אבא, אלא שלא רצה להזכיר שם אביו מחמת כבודו (ויל"ד, שבדר"כ, לכאו', לא הקפידו על זה. וע' ביבמות (טז.). ואולי באותן מקומות לא הביא לשונו ממש, אלא אמר פאראפריי"ז (וע' בקידושין (לב.), שאומר, "תורגמן אינו משנה לא שם אביו."). ויל"ד למה נניח שבחד מקום עושה ין ובחד מקום לא עושה כן. ואולי שאני הל' שאומר ממימרא שאומרת ותו"ת.), כמו שאנו קוראין לאבינו בשם אבא. בשי"ח ש"י הק' על דחייה זו שלא אמר שמו, שלא שהיה מדמה את עצמו לאחרים עם אותו שם. א"כ, לכאו, אין בזה כיבוד אביו.
2.עוד דחה שם שאפשר שאינו אותו ר"נ, ורק סתמו כיון שיזכיר שמו מיד. דחה את זה מפני שרש"י שם אומר, " סריסים שהיו תמיד לפניו לפי שהיה שר חתן הנשיא . . . " נמצא שצ"ל ר"נ סתם (דגמ' חולין וגיטין).
3.אפשר שלא היה אומר מה היה בלי תורה, אלא היה מדמה אותו לבני אדם שבשוק. וא"ת א"כ למה נקט נחמן. י"ל שהיה שם מצוי. גם י"ל שרצה לנקט שם שיידמה לשמו, ואז נקט נחמן, אבל לא כשהוא ש"ש מוזר, כמו יצחק או יעקב.
* ג.קושיות
נדון בקושיות על כל צד. (כמובן, כל ראיה יהא ק' על שאר הצדדים):
1. רק מצינו ק' על רש"י. מצינו 5 קושיות על רש"י:
1.בגמ' גיטין (לט:) אומר: "אמר רמי בר חמא א"ר נחמן הלכה כר' שמעון ורב יוסף בר חמא א''ר יוחנן אין הלכה כר' שמעון אשכחיה רב נחמן בר יצחק לרבא בר שאילתא דהוה קאי אפיתחא דבי תפלה א"ל הלכה או אין הלכה א"ל אני אומר אין הלכה ורבנן דאתו ממחוזא אמרי אמר רבי זירא משמיה דרב נחמן הלכה וכי אתאי לסורא אשכחתיה לר' חייא בר אבין אמרי לי' אימא לי איזי גופא דעובדא היכי הוה אמר לי דההיא אמתא דהוה מרה שכיב מרע אתיא בכיא קמיה אמרה ליה עד אימת תשתעביד ותיזיל ההיא איתתא שקל כומתיה שדא בה אמר לה זיל קני הא וקני נפשיך אתו לקמיה דרב נחמן אמר להו לא עשה ולא כלום מאן דחזא סבר משום דהלכה כר' שמעון ולא היא אלא משום דהוה ליה כליו של מקנה." מזה, מוכיח תוס' ב"ב נגד רש"י. יל"ד מהו הראיה:
1.יל"ד במה דנו רנ"ב יצחק ורבא. אפשר שדנו מה אמר ר"נ, ואפשר שדנו מה הל'. לראישון, יהא ראיה שרנ"ב יצחק אינו ר"נ, שלא ידון בשיטת עצמו. אפשר שתוס' סבר כאותו צד. לדחות, י"ל כצד שני (וע' ברש"י ד"ה ולא היא, שאומר שרבא אומר שמס' ר"נ הוא " כדאמינא מדעתאי." מדהשיב רבא מה סבר מדעתו, נ' שדנו מה ההל'.). צ"ב למה יניח תוס' כצד ראישון.
2.י"ל שהוה ק' לתוס' שישאל ר"נ אי הלכה כעצמו, שהוא בוודאי סובר כן. ויש לדחות שדן מה חוש' שאר רבנן. כמו כן מצינו בב"ב (קמב:).
3.י"ל שסבר שאם שואל לו הל', ק' מה משיב לו. רש"י ידחה שמשיב שדנו בשיטתו, שהוא הקובע. זה,כמובן, דחוק, שהו"ל לומר כן בפי'. גם י"ל שר"ל, "כן אני סובר, וכן אתה סובר; ויודע אני שכן אתה סובר . . ."
1. י"ל שתוס' מביא ראיה ממה שנקרא ר"נ ורנ"ב בחד מעשה. וע' לקמן.
יש לדחות כל ראיה זו לומר שכיון שהז' כבר רנ"ב יצחק, פשוט שלא דן בו, ויכול לסתום ר"נ אחר. יל"ד בזה, שהניחא שלא נחשב שהוא רנ"ב יצחק, אבל איך נדע איזה ר"נ הוא. וצ"ל שיש אחר שהוא הכי מסתבר לסתם, חוץ מרנ"ב יצחק. צד זו יתרץ כמה מן הקושיות על רש"י. (ויש להעיר שזה דחוק לצד שנסתם מלשון בנ"א.)
כמו"כ י"ל שמביא דיבורו כמו שדברו(יש להעיר שגמ' חולין הוא בדיבור אחר) . לא היה קורא רנ"ב יצחק סתם ר"נ, שאולי רק לאחר זמן קראוהו כן (ואפשר שתוס, מסכים לזה, ורק סובר שכיון שמצינו שהיו כבר קוראין לר"נ אחד ר"נ סתם, לא ישנו. וא"ת א"כ לעולם יהא הראישון הסתם, ולא מצינו כן. וי"ל שלא לעולם סתמו (על"ע). גם, אולי יש לחלק בין הנססם מפני שאין אחרים והנסתם מפני שיסתם. (ויל"ד, שלעולם יהא השני. ויל"ד, שאולי לא לעולם סתמו חד, משא"כ אי יש רק חד, שמסתבר להם לסתום.) ויש להעיר שאז ק"ק איך ידע תוס' שאין זה הקודם. וי"ל שלא היה רנ"ב יצחק-שכ' תוס, שהיה תלמיד רבא-כ"כ מוקדם.), או שכשדברו לו-ואז, הוה פשוט שלא היה אומר רנ"ב יצחק-היה סותם ר"נ אחר.
2.בגמ' עירובין (מג:) כ', "יתיב רב נחמן בר יצחק אחוריה דרבא ויתיב רבא קמיה דרב נחמן א''ל רב נחמן בר יצחק לרבא מאי קא מבעיא ליה לרב חסדא . . . " מזה, מוכיח תוס' ב"ב נגד רש"י. יל"ד מהו מראיה:
1. בפשטות הראיה הוא שתוס' סובר שחד עובדא הוא, ובו ישב ר"נ ב"י אחוריה דרבא ירבא קמיה דר"נ. אז, אם ר"נ ורנ"ב יצחק היו בחד מעשה, בהכרח אינו חד איש. רש"י ידחה:
א.אינו חד מעשה, אלא שני מעשים שקרו. לא נראה כן לשון גמ', שרק מזכיר שאלה מאת רנ"ב יצחק. צ"ל שרק מזכיר רנ"ב יצחק, אבל אף רבא שאלו לר"נ.
ב.אולי חד מעשה הוא, ורק אומר שישב ר"נ לאחוריה רבא, וממילא, היה רבא קמיה דר"נ. דחוק למה יזכיר שניהם, שלכאו', אין צורך.
2.י"ל שסבר תוס' שא"א ששאל רנ"ב יצחק כן אי היה ר"נ, שכיון שכבר פסק, בודאי ידע התשובה. ת"ב איך רש"י ידחה את זה.
3.י"ל כ4 שב1. זה יותר טוב אם הוא חד מעשה (ונ' שאינו מוכרח).
3.מביא תוס' ראיה ממה שמצינו הרבה (לו) פעמים "אמר רבא אמר ר"נ" (במק"א (קדושין (מב:)), אומר תוס, שהיה רבו. ע' לקמן.), וגם מצינו שרנ"ב יתחק היה תל' רבא (מביא ראיה מגמ' ב"ב (כב.), ולא הבנתי מהו, ששם רק מזכיר שהיה דורש ושוהה לר' אדא  בר אבא שהיה תל' רבא. וצ"ב.). א"א, אומר תוס', שהיה רבו ותלמידו. נראה שלרש"י יש לדחות שאף שהיה רבא רבו, אמר מימרות משמו (או שהיה רבו ותלמידו או שהיה תל', אבל היה יותר זקן, ואז שמע יותר. נ' שמח' זו לשיטתן, שבר"ה (יח.) כ', רבה ואביי מדבית עלי קאתו רבה . . . חיה ארבעין שנין." שם גרס רש"י (עכ"פ בפשאו הראישון) רבא. א"כ, מת רבא כשהיה רק בן ארבעים, ואפשר שהיו תל' זקנים ממנו[fn:4] (ואז מסתבר שידעו מה שלא ידע רבא ומסתבר שהיו רביו). נ' שיש ראיה, לרש"י, שהיו לו תל' זקנים מיניה, דאומר בגמ' גיטין (עג.) שרבא קרא לר"פ ור"ה בדר"י "קאקי חוורי" על שם שהיו זקנים. ברש"י עירובין (כו.) אמר שהיו ר"פ ור"ה בדר"י תל' רבא. רבא לא חי להיות זקן, ותלמידיו היו זקנים-צ"ל שהיו זקנים מיניה. תוס' בר"ה (שם) חולק וגורס רבה. א"כ, לא נניח שהיו לרבא תל' זקנחם ממנו. נ' שיש להעיר ג"כ שתוס' בקידושין הנז' בא להק' על רש"י, שלפשפו שם, נמצא שרבא חולק על רבו ר"נ. לפמש"כ, אינו ק', שר"נ לא היה לעולם רבו של רבא לרש"י.
1. בעירובין (יח:), אומר ר"נ ש"מנוח עם הארץ היה שנאמר, 'ויקם וילך מנוח אחרי אשתו'." מיד, "מתקיף לה רב נחמן בר יצחק אלא מעתה . . . " מזה מוכיח תוס' בגיטין שאין סתם ר"נ רנ"ב יצחק, דאל"ה, נמצא שמק' על עצמו. אפשר שרש"י סובר שבאמת מק' על עצמו, וכמו"כ מצינו (אבל לא בלשון זה) במק"א (ע' מכות (ח:), יבמות (כ:), וקידושין (לט.)) אפשר שאבתי סובר תוס' שק' שנשנה שמו בכ"כ קרוב.
5.יש להק' לרש"י למה ייקרא לפעמים ר"נ ולפעמים רנ"ב יצחק. אפשר (על"ע) שתוס' מכוון להק' כן. דע שמצינו שר"ל נקרא בשם ר"ל ונקרא בשם ר"ש בן לקיש. (ויל"ד למה:
א.מי שהביא מימרא זו קראו זה ומי שהביא מימרא זה קראו זו.
ב.אפשר שהיו שני תקופות חייו.
דע שמצינו כן אף בחד ענין.) עכ"פ, נמצא שלא ק' שישנה שמו, ואף בחד ענין.
דע שיש צד אחר, והוא שסבר רש"י שיש שני רנ"ב יצחק. אז, נוכל לת' כל המקומות שבא רנב"י באופן קשה לומר שהוא רנב"י אחר. מצינו לפעמים שיהיא תרי סתמי (כמו ר"כ (שחד היה רבו של רב ואחד היה תלמידו), ורבינא, ורב אשי, ועוד.)
גם יש צד אחר, והוא שיש יותר מחד ר"נ. זה דחוק (יותר ממש"כ לעיל, שכאן יש לו לפרש ולבאר בקל), אבל מצינו כן בכ"מ (על"ע). (הו"מ לפרש שסובר תוס' שיש שני ר"נ, אלא שסבר שמוכרח שחד רנ"ב אבא. אז, דן על האחר. ונ' שזה א"א, שא"כ, אין קושייתו ק', שי"ל שאותו ר"נ הוא ר"נ אחר. ותו"ת.)
* Footnotes
[fn:1] נראה שלא אפשר לומר צד זו, שרע"א מביא ראיה זו בהרבה מקומות, ובכללם בסוף סוטה. לצד זו, לכאו' אין ראיה שייכת כלל לגמ' שם, שראיה ה"ה ממה שרש"י קורא לר"נ בשם רנ"ב יצחק.
[fn:2] מצאתי בסדר תנאים ואמוראים שמז' ר"נ ורנ"ב יצכק ורנ"ב יעקב. ת"ל שר"נ סתם אינו רנ"ב יצחק או רנ"ב יעקב. אפשר שהוא רנ"ב אבא או שום ר"נ אכר- ואולי לא ידוע מי הוא.
[fn:3] כ"נ מתוס', שאומר, דלא כרש"י, שהיה עשיר. הקנטרסט בין זה לרש"י צ"ב; אף רבא סובר שהיה מפני שהיה עשיר (ואפשר שלרש"י לא היה עשיר, אלא חתן נשיא, ואין נפק"מ בזה). נ' שרש"י סובר שאין הענין רק היותו עשיר, אלא כמש"כ.
[fn:4] יש לציין לגמ' הוריות (יג:) שכ', "אמר רב פפא לא אמרו אלא לקטנים אבל לגדולים לא הוה ליה למבדק נפשיה מעיקרא דאמר רב יהודה אמר רב לעולם ילמד אדם עצמו להשכים ולהעריב כדי שלא יתרחק (אמר רבא) האידנא דחלשא עלמא אפילו לגדולים נמי." ע' בשי"ח ש"'י שם שכ', "-אמר רבא-לכאו',אין לגרוס זה, שרבא קדם לר"פ. וי"ל שהא דר"פ נאמר קודם זמן רבא (ע' בחבורת שי"ח ש"י במי היה ר"נ). גם יש לדחות שר"פ רק מפרש מה שאמר בריי'.  גם י"ל שרבא לא ידע מה אמר ר"פ, ורק הבין שיהא צד לאומרא כיון שידע הא דשמואל. אז, רבא ור"פ חול' מתי קיים. ותח'."
