* Hakdamah
* To The Tune of:
* Shalom Aleichem- Regesh
Once a year, each yomtov’s here, and so it holds
a special shine we can’t decline- and so it helps us grow.
But Shabbos comes far more than once- it grows so old;
we pass it by, and do not try- to let it help us grow.
Chorus:
But Shabbos is so holy, and if we would only, grasp its kedusha, we’d truly grow.
It’s a seventh of our days, so what a shame to waste, this Holiest of Holies- yom shabbason.
Each law has a body part that it is kineged
Shabbos’s part is like the heart- and so it helps us live.
It’s each week’s fruit, because, in truth, it’s its main member
the other six just live off it- and the holiness it gives.
Chorus (omit “but”).
Hashem gave us a special gift- ours and no one else’s-
it shows us dear, and holds us near to Hashem with all his love.
A present from a melech’s treasures is surely precious-
Do you know what His present was- veshabbos shimah.
Chorus.
So, understand this time was planned for his avodah
give it care, and be aware- that Shabbos pays it back.
So, spend the time on things sublime, like limud torah,
and give your best, and you’ll be blessed- cause Shabbos pays it back.
Chorus.
* 1, 2
* To The Tune of:
* Koh Ribon- Toronto Boy’s Choir.
Zochor es yom hashabbos lekadisho- ki vo shavas el mikol melachto.
Shabbos reminds us: Hashem made the world, in one day of rest, and six days of work.
Chorus:
Ve’atem eiday- Shabbos signifies-
Hashem made the world and keeps it alive- this we testify.
We don’t have to work, so our time is not spent with anything other than thoughts of Hashem.
So, let us keep Shabbos, and make our faith grow- let us keep Shabbos and help ourselves so.
Chorus.
Shamor es yom hashabbos lekadsho- He freed us from Egypt a long time ago.
The issur melacha this passuk explains- cause we’d have to work if we were still slaves.
Chorus.
It’s also the best way to prove Hashem true- look what He did and what He can do.
He made it from nothing, sustains it each day- Hashem runs the world- in every way.
Chorus.
* 3
* To The Tune of:
* Yedid Nefesh- Traditional (Young Israel)
A special day of rest,
A special day that’s blessed,
Given by Hashem,
To forge a connection with us.
A link between us formed,
The other nations scorned,
A day of true menucha,
The day of Shabbus.
Chorus:
Shabbos is a bris, bonding us to Him;
And shabbos is an os, a proof to this link.
Shabbos is our own, our connection and our bond,
Exclusive to our nation, of whom Hashem’s so fond.
For six days every week,
An extra os we seek,
To prove our dedication
To Hashem above.
On shabbos we desist-
‘cause Shabbos itself is it-
It shows we serve Hashem,
And displays our love.
Chorus.
Our marriage to the shabbus
Breeds belief around us
In hakadosh baruch hu
And a proper life.
There are things so holy,
Possible but only
On the day of shabbos,
With our shabbos wife.
Chorus.
* 4
* To The Tune of:
* The Forgotten Princess- London School of Jewish Song
Sunday has a Wednesday,
Monday has a Thursday
Tuesday has a Friday,
But shabbos is alone.
And so this day was given
A husband called the yidden
We honor it with love,
And make this day our own.
Chorus:
Bo’ee beshalom ateres baalah
Every week we greet the shabbos malkisa
Boee beshalom ateres baalah
Our princess and our queen, our holy kallah.
We pamper our new wife,
And dress up clean and nice,
Acting like a chassan
On his wedding day.
Early must we meet it
In song and dance we greet it,
And treat it like our kallah,
When we stand and say
Chorus.
It would be a folly
To just prepare our body
Hachanas shabbas tells us
To purify our souls
Because we all expect a
Neshama that is extra
We must take extra caution
That our neshama’s whole.
Chorus.
* 5
* To The Tune of:
* The Vayeshev Song- 613 Torah Avenue
Shabbos has a holiness that comes from deep inside
A holiness that spreads itself and cannot be denied
Which goes to every single day and lends kedusha to
Every single boy and girl, every single Jew,
Giving him a holy strength and shining bright its light
To dissipate the yetzer hara in its frantic fight.
When shabbos has to say goodbye, that holiness will stay
Perpetuating kdusha in the shabbos of each day
Siphoning off bracha to the rest of the week
(that’s why we mention shabbos when the day’s names we do speak)
And leaving an impression in the heart of every Jew
Guiding him and teaching him just what he has to do.
* 6
* To The Tune of:
* Shabbos is Going Away- Uncle Moishy
Imagine the Olam haba
the purest enjoyment in giluy shchina.
On shabbos, everyone
gets a glimpse of the world to come.
Chorus:
Shabbos is holy with holiness from
olam haba, the world to come,
a glimpse of the kedusha you’ll find
beyom shekulo shabbasoin.
The pleasure the next world will give
is greater than what we can have when we live
-above what this world can explain
and growing with each passing day
Chorus.
Shabbos is also the key
to enter the next world, for how could it be
that one could have kdusha so high
without the taste shabbos provides.
Chorus.
* 7
* To The Tune of:
* Veleyerushalayim- Dveykus
if I don’t work on shabbos, well why not just lie down,
or catch up with the chevra on the hock that’s going round?
Why not take the day off- use it only to relax?
We’ll stretch our tired feet out and rest our weary backs!
Chorus:
The rest we rest on shabbos is a ruchniyus recharge;
this day we have potential which reaches very far;
we distance all distractions and pay no heed to them;
this day we have menucha, to come close to Hashem.
We spend our time on learning- its gates are open wide
its power is enormous, greatly multiplied
by the day of shabbos, which we’re mekadesh through
the torah that we learn and the mitzvos that we do.
Chorus.
* 8
* To The Tune of:
* Koh Ribon- Dveykus I
tov lehodos lahashem
on shabbos, we all have the time
to look at the world around us
and see in it all that’s divine.
Shabbas was specially set
as a thanks giving day
our shiros rise higher than angels’
with all our sins wiped away.
Chorus:
On shabbos, Adam sang it;
on shabbos, the leviim sang it;
on shabbos, we all sing it;
on shabbos, shabbos sings it.
Mi’izmor shir
shir liyom hashabos
the song to thank Hashem
for all that he does.
Bemaysei yadecha aranen
the world was perfectly formed,
beautifully shaped by Hashem,
gorgeous and grandly adorned.
Mah amku machshivosecha
Hashem determines each day
how the world should be and
runs it the perfect way.
Chorus.
Each generation’s a body
and each one of us is a part;
sanhedrin, the eyes of the nation;
the melech, the am’s throbbing heart.
And each generation, in turn,
is part of the body which forms
klal yisral through the ages
and each has its own chore.
Chorus.
Bifroach reshaim kmo esev
since everything happens with cause
don’t be confused when the wicked
are not getting punished for flaws.
There is a cheshbon for this
Hashem must pay up their debts
and after this brief day of glory
doom in this world and the next.
Chorus.
* 9
* To the Tune of:
* Shabbos Kedusha (originally Erev Shel Shoshanim)
The shabbos meal’s a feast,
but not just to enjoy;
it’s to make the shabbos zeese
for every girl and boy.
Our eating is korbanos
uplifting it a lot;
easy pleasant happy talk
with gentle chinuch taught.
Chorus:
When we treat it so
our reverence we show
for shabbos kodesh,
the holiest day, we know.
Feast so happily
enjoy it gratefully
honor shabbos kodesh
a day so holy.
* 10
* To The Tune of:
* Yom Zeh Mechubad
Chilul of shabbos is very severe
because shabbos is proof that Hashem we fear.
One who’s michalel is like a non-jew
and with that evil sinner- have nothing to do!
Nowadays, many are sadly lost
and they desecrate shabbos, not knowing the cost.
Don’t let their mistakes influence you,
so try not to look at the chilul they do.
Chorus:
Every yid is a part of one soul;
we all are but pieces in one greater whole,
so all of the actions that all of us do
has an effect on every Jew.
By caring for shabbos and doing our best,
our influence spreads and reaches the rest
of klal yisral’s nefesh and helps them stay strong
and withstand the temptation to do what is wrong.
Our limmud hatorah spreads far and spreads wide
and gives every yid a fire inside;
the best way to help out your brothers who’ve strayed
is by limud hatorah- every day.
Chorus.
