* 1
* To The Tune of: Yisrael (Dov Levine)
Standing by
Har sinai,
We all saw the shchinah face to face.
Hashem appeared
Far more clear
than any view that had ever taken place.
This view of Hashem
to thousands of men
and millions of women and kids
shows us the truth
is the ultimate proof-
we accepted the Torah from him.
Chorus:
How can we ever deny
the truth that was taught by our fathers and teachers,
who knew that it was not a lie-
they saw it with their very eyes!
Never can there ever be
a question to challenge or doubt our belief in this.
We all watched it- you and me;
how can we doubt what we see?!
Never since then
has ever Hashem
made such a public display,
for the Torah has stayed
as it was on that day,
did not change in any single way
Chorus.
* 2
* To The Tune of: V’Hu Keili
Wherever we are-
In our land or very far-
In poverty, famine, or war.
One thing remains:
Our Torah’s still the same
Our mesorah is unbroken through each dor.
Chorus:
For thousands of years,
‘midst troubles and tears,
the Torah was taught through generations;
and each dor, in turn,
made sure the next would learn-
ki lo sishakach from our nation.
it’s what keeps us alive,
ensures we can thrive,
and guides us through each storm we’ve weathered;
stronger nations fade away,
but we are here to stay-
unchanged for forever…  and forever
Through bitter decrees,
and in high society,
where no other nation stands proud;
though others would despair,
it shows how much we care:
Torah is what keeps us around.
Chorus:
Our mesorah is passed
By those with knowledge vast
And with purity, quite through and through.
These giants pass it on
So Torah can stay strong;
Their greatness is proof that its true
Chorus.
* 3
* To The Tune of: Sh’ma Koleinu (Dveykus)
By Har Sinai, what we got
Was no mere present, it was not
A simple giving, friend to friend,
But our marriage to Hashem
And just like by her wedding day
No other man can lure her away;
She’ll always be by her husband’s side,
Her husband’s wife, his joy and pride.
Chorus:
Our marriage made, we now became
More like angels than like men-
A real part of a baal we love
Connected to Hashem.
Our loving marriage to Hashem
Changed who we are- we’re himmeldike men;
And though we’re living way down here
We play a part in the upper spheres.
Chorus.
* 4
* To The Tune of: Mi HaIsh (Rabbi’s Sons)
Different than the gentiles, bonded with Hashem;
We must know that we’re special and stay away from them.
Vatem tihyu li mamleches kohanim
Klal yisrael must be separate from goyim
Chorus:
In music and in books, in our house or on the street
in clothing and in looks, in what we hear and in what we see.
Keep yourself at distance, in what you think and in what you do
Uvichukoseihem lo seileichu
A simple sneaking glance, a joking word exchanged
The little seed it plants can make us greatly changed
Why would we see them as our goal and guide
When, compared with yidden, they’re empty deep inside?
Chorus.
Why would goyim hate the yidden for so long
It’s ‘cause that will create a fence that keeps us strong
When yidden make pirudim, and do what goyim do,
Hashem bring us yissurim to remind us that we’re jews
Chorus.
* 5
* To The Tune of: The Anavah Song (Marvelous Middos Machine)
Hashem called us his nation, mamleches kohanim-
And that’s a hefty statement- we mean a lot to him.
So, next time when you’re feeling that you’re nobody at all,
Remember what Hashem called you, and stand up straight and tall!
Chorus:
So next time when you’re tempted, just remember who you are:
Hashem says that we’re special- that every yid’s a star!
You’re a holy yid who Hashem holds really close-
A mamleches kohanim- and a goy kadosh!
By toiling in Torah, we recognize we’re great-
The Torah has a special strength to lift and elevate.
So, look at your neshama- the holiness inside,
And think about your ancestors and feel a rush of pride!
Chorus.
* 6
* To The Tune of: The Noach Song (613 Torah Avenue)
The yidden were selected as Hashem’s beloved ones,
From the time of Avraham, for all that he’d done.
We’re the am hanivchar and we always would be
Hashem’s beloved nation, for all of history.
And if the other nations had accepted for themselves
The Torah and the mitzvos, and had kept them really well,
We still would be a lot more dear to Hashem above-
The nation that he chose, the nation that he loves.
* 7
* To The Tune of:  VHaarev na (I) (Boruch levine)
Standing by har sinai, every yid had come,
And we each received a portion of the Torah, one by one.
For every yid is special, each has his own share-
The Torah must be given when every jew is there.
Chorus:
Now every single jew has a portion to accrue
A chelek being given day by day
And as we’re learning more Torah never seen before
We’re receiving Torah in a special way.
Asher bochur banu, about maamad har sinai
Ends off in the present tense- and let me tell you why
Cause the giving is ongoing, its being given when
any yid thinks up a chiddush- he’s accepting Torah then.
Matan Torah has no Zecher, we set aside no time
To remember how Hashem gave us a Torah most sublime
‘cause a zecher’s on what happened, and not what’s happening
And matan Torah happens with every Torah thought we think
Chorus.
* 8
* To The Tune of: Don’t Sit on the Afikoman
From peasach ‘till shavuos, there are fifty special days-
Days that help us fix ourselves in many different ways.
They have a special power, and in them the yidden grew,
And we can grow then too
These days are like a chol hamoed, for extended time;
They’re like the days a zavah counts to make her fit and fine;
They magnify our actions, helping everything we do,
So we can grow then too
They’re the days on which the mending and the fixing must be done;
They’re the days of preparation for the Torah soon to come;
And eagerly we count these days which bring us to the time
Of mamad har sinai.
This fixing is on far than more than your learning, you must see,
If you want to learn or do what’s right, there’s something else you’ll need.
We work now on our middos, which will help us truly shteig
From this special holy time.
