* 9
* To The Tune of: Essa Einai (JEP)
The torah is the reason hashem made
This lovely world and all that it contains
That’s why he made the torah first of all
Without it, the whole world would just fall
By matan torah, klal yisral received
the purpose of the briah for when we
are learning the torah- that’s the reason why
hashem ensures the world does not die
Chorus:
By learning, we’re keeping all the world around
The world lasts to help us as we learn his wisdom
In us the function of the world is found
Torah- its study night and day.
imagine how happy and how glad we’d be-
those eager emotions as we learn his wisdom-
if only we’d open up our eyes and see
torah is what makes the world stay
A general who wins a mighty war
Will certainly receive a great reward
He only saved a kingdom, by learning we
Ensure that we all won’t cease to be
Picture all the chessed you’ll have done
Far more than that battle that was won
You’re saving and sustaining everyone who lives
By torah and the power that it gives
Chorus.
* 10
* To The Tune of: The Middos Song (Marvelous Middos Machine 1)
Since torah is the key to make the world be
Then surely it can do much for each and every Jew
When we learn its laws, then surely it will cause
A kdusha to sustain us, and keep us strong and true.
Chorus:
Torah has a special strength, far more than we can know
It has a power peerless and unique
And every word we ever learn will sanctify us so
And give to us the holiness we seek
A potent cure that’s useful for the yetzer hara’s might
a potion that can keep its plots at bay
to give us bren to serve hashem and really do things right
And help us get back up when we have failed.
While every mitzva holds a power we are told
They never can compare to what the torah will bestow
They fix one body part, our hand or leg or heart
While torah makes us holy from our head down to our toes
Chorus.
Every single drop of limud torah stops
The yetzer hara’s power and helps to make us strong
To do with all our might every action that is right
And helps us bounce back better when we do things wrong
Chorus.
So, think a little while and give a little smile
As you realize the importance of the torah that you learn
Your learning is the key to the yid you want to be
And next world it will bring you all the sechar that you’ll have earned.
Chorus.
* 11
* To The Tune of: Yankel am Haaretz (Journeys 2)
it may be hard for you to learn gemara-
you might hardly understand a line
ligmor hamlacha is lo alecha
but you always have to keep on try’ng
and sometimes it seems as though your work is wasted-
you’ve worked so very hard and really tried-
but this precisely is why we’re created
to learn with all the strength we have inside
High:
and when you’re feeling beaten
you’re certain that you’ve lost
hashem will pay- he always does- the schar repays the cost
your pain will be but fleeting
your gain will be a lot
you’ll be served what you deserve for how hard you fought
and maybe in this world you’ll be forever
no one smarter than you were before
do not doubt that it will happen ever
for in the next world, you will know far more
and none of your effort is at all for nothing
cause there’s a lot of pain to come someday
better let that pain be spent on learning
than on other things in other ways
High:
it may not be smooth sailing
but when all is said and done
you’ll know the difference when you see the person you’ve become
while you thought you were failing
you felt you were too dumb
your neshama grew, uplifting you, and in the end, you’ve won
* 12
* To The Tune of: To Live a Life of Torah (Miami Experience 2)
The best way to learn the torah better
The best way to stay in it forever
Is to have a cheshek and a drive
that makes the torah come alive
Torah should be our greatest love
A pleasure we love partaking of
Enjoying every little drop never wanting it to stop
with feelings of sweetness and joy
Chorus:
To feel the joy of torah, to taste the sweetness it brings
To live with all of the happiness to which it clings
Is to learn the torah better, to connect with learning and grow
For the highest way to learn it is to love it so
The torah is hashems shashuim
We should feel the same for all of our limmuddim
This love and joy will bring on
A connection that is very strong
The yetzer hara prevalent this dor
Is pleasure, tayva, lust, and so much more
The way to fight and stay away is by learning every day
with feelings of sweetness and joy
Chorus.
* 13
* To The Tune of: Kibud Av Va’eim (Marvelous Middos Machine)
Each of us can merit a cheshek and can be
A masmid and a gadol, learning happily
But everyone is different; we each have our own way
To reach this lofty level and learn with bren each day
Chorus:
There’s a portion just for you, there’s a holy special part
So, when you learn, it’s now your turn to do what’s in your heart
You’ll have a special drive for the chelek set for you
Learn what you want and how you want and your torah will ring true.
When you choose your limmud, pick something light and fun
And you’ll enjoy each second of the learning you’ll have done
Stay away from pressure, from anxious nervous stress
And do not learn for kavod or merely to impress
Chorus.
Make sure your pick’s not lazy, you’ve got to push yourself
But don’t drive yourself crazy by learning too intense
Stay within a framework, a portion of a group
And daven for hatzlacha that hashem should help you through.
Chorus.
Learning that is hazy and vague and misconstrued
Will never give hatzlacha or be geshmak for you
Make sure you know the basics and get them clear and sharp
Their clarity will give to you a love deep in your heart.
Chorus.
