** ציורי איסור:
ש"ך –
רשב"א (וכן הלכה) – יש חמש ציורים שבו אסור:
1. אם ניתן בו דבר לח[fn:1], אפילו אם הדבר היה צונן (אף לא מלוח וכבוש)[fn:2], אפילו באיסור חמץ[fn:3], אם הכלי לא הודח ולא קונח, אפילו אם אינו כלי חרס[fn:4], אפילו אם אינו בן יומו[fn:5], אפילו אם האוכל שני היה יבש[fn:6], אפילו אם אוכל שני לא היה חריף[fn:7], אפילו אם אוכל שני לא היה חם[fn:8], אפילו אם משתמש בו עראי[fn:9].
2. אם ניתן בו אפילו דבר יבש[fn:10], אם ניתן בו בבית שאור, חמין, או מלוח וכבוש[fn:11], אפילו באיסור חמץ, אפילו אם הכלי קונח או הודח[fn:12], אפילו שלא בכלי חרס, אפילו אם אינו בן יומו, אם האוכל שני היה לח, ואם האוכל שני היה חריף, אפילו אם אוכל שני היה צונן[fn:13], אפילו אם משתמש בו עראי.
3. אם ניתן בו דבר יבש, אם ניתן בו בבית שאור, חמין, או מלוח וכבוש[fn:14], אפילו באיסור חמץ, אפילו אם הכלי קונח או הודח[fn:15], בכלי חרס, אפילו אם אינו בן יומו[fn:16], אם האוכל שני לח[fn:17], אפילו אם האוכל שני אינו חריף, אפילו אם אוכל שני צונן, אפילו אם משתמש בו עראי.
4. אם ניתן בו  אפילו דבר יבש, אם ניתן בו בבית שאור, חמין, או מלוח וכבוש, אפילו באיסור חמץ, אפילו אם הכלי קונח או הודח[fn:18], אפילו שלא בכלי חרס, אם הוא בן יומו[fn:19], אפילו אם אוכל שני יבש, אפילו אם אוכל שני לא היה חריף, אם אוכל שני חם[fn:20], אפילו אם משתמש בו עראי.
5. באותו אופן שאסור אם אוכל שני חם, אסור להשתמש בו בקביעות אם אוכל שני צונן, מגזירה שישתמש בו כשהוא חם.
לפי הש"ך, כשאסר בעה"ע לתת בכלי של איסור דבר של היתר שאין דרכו להדיח, כוונתו היה לאסור ציור ראשון.
לפי הרמב"ם, מצאנו עוד ציור שאסור:
1. אפילו אם דבר ראשון יבש, אם ניתן בבית שאור, חמין, או מלוח וכבוש, אפילו באיסור חמץ, אפילו אם הדיח, אפילו אם אינו בן יומו, אפילו אם אוכל שני יבש[fn:21], אפילו אם אוכל שני לא חריף[fn:22], אפילו אם אוכל שני לא חם, אפילו אם משתמשים בו עראי.
ט"ז- יש שני ציורים שאוסר:
1. אפילו אם דבר ראשון יבש[fn:23], אפילו אם נתן בצונן, אפילו באיסור חמץ, אם הכלי לא נקי[fn:24], אפילו שלא בכלי חרס, אפילו אם אינו בן יומו, אפילו אם אוכל שני יבש[fn:25], אפילו אם אוכל שני לא חריף, אפילו אם אוכל שני לא חם, אפילו אם משתמשים בו עראי. סובר שאין בזה חידוש.
2. אפילו אם דבר ראשון יבש, אם נתן בבית שאור, בחמין, או במלוח וכבוש[fn:26], אפילו אם הדיח, אפילו שלא בכלי חרס, אפילו אם אינו בן יומו, אם אוכל שני לח, אפילו אם אוכל שני לא חריף, אפילו אם אוכל שני לא חם, אפילו אם משתמשים בו עראי. ש"ך חולק בפירוש על זה.
לפי הט"ז, כשאסר בעה"ע לתת בכלי של איסור דבר של היתר שאין דרכו להדיח, כוונתו היה לאסור ציור שני.
** ציורי היתר:
ש"ך – מן הש"ך מוכרח שכל ציור אחר מותר, ממה שלא מוקים בעה"ע באותו ציור.[fn:27]
ט"ז – מן הט"ז יוצא שלש ציורי היתר:
1. אפילו אם ניתן בו דבר לח[fn:28], אפילו אם נתן בבית שאור, בחמין או במלוח וכבוש, אם הדיח, אם אינו בכלי חרס[fn:29], אפילו אם הוא בן יומו[fn:30], אם אוכל שני יבש, אפילו אם אוכל שני חריף[fn:31], אם אוכל שני צונן, אם משתמשים בו עראי[fn:32].
2. אפילו אם ניתן בו דבר לח, אם היה צונן, אם הדיח, אם אינו בכלי חרס, אפילו אם הוא בן יומו, אפילו אם אוכל שני לח, אפילו אם אוכל שני חריף, אם אוכל שני צונן, אם משתמשים בו עראי.
3. אפילו אם ניתן בו דבר לח, אם היה צונן, אם הדיח, אם אינו בכלי חרס, אפילו אם הוא בן יומו, אם האוכל שני יבש[fn:33], אפילו אם אוכל שני חריף, אפילו אם אוכל שני חם, אם משתמשים בו עראי.
* Footnotes
[fn:1] איני יודע מהו הדין אם ניתן בו דבר יבש, שלא מדבר בו.
[fn:2] כן נראה, שכיון שהאיסור יהיה מפני שלא קנח והדיח אותו, נראה שהענין הוא הממשות שיש בו, וזה לא תלוי באם נתן בו חמין או צונן. אבל, לא מוכרח כן, שיש לומר שכשיש בו בליעות, הבליעות יוצאות, ומערבות עם הממשות שיש שם, ואז יותר אוסר.
[fn:3] שהש"ך לא מודה לצד של הרמ"א לחלק בין איסור חמץ לאיסורים אחרים להקל באיסור חמץ.
[fn:4] זה מוכרח, שאוסר כלי חרס אף אם הודח.
[fn:5] כן נראה ממה שלא מזכיר אותו החילוק. גם נראה כן מסברה, שכאן הבעיה הוא הממשות שיש בו, ולא הטעם שנותן, ואז לא שייך בו נותן טעם לפגם (שלא מצאנו היתר נ"ט לפגם בהדחה).
[fn:6] כן נראה, ממה שמקשה על הרמ"א מהי"ת לחלק בין לח ויבש, שרק מצאנו חילוק בהם באופן אחד שנבאר לקמן בע"ה. אבל, גם מצדד לבאר תוס' ומרדכי לומר שמה שאוסר בדבר לח הוא בלא קינוח. אז, על כל פנים, יוצא שלפי תוס' יש חילוק בין דבר לח לדבר יבש בזה. אבל, גם מצדד נגד פירוש זה (ואולי, אז, לא צריכים הדין שחידש בו).
[fn:7] כן מוכרח, שלא מזכיר נקודה זו עד אופן אחר לקמן.
[fn:8] כן אומר בפירוש.
[fn:9] כן מוכרח, שאוסר אף בלי כל זה, אם משתמש בו קבוע.
[fn:10] כן נראה, שהאיסור כאן יהיה מפני בלעיות, וזה לא תלוי בדבר לח ויבש.
[fn:11] נראה שצריך אחד מהם, שזה יהיה אם קינח והדיח אותו. אז, לכאו' לא נשאר כלום עליו, וצריך לומר שאוסר מחמת בליעות. אין זה מוכרח, שיש לומר שכיון שיש דבר חריף, יכול לשאוב טעם מעט שנשאר אחרי קינוח והדחה. אבל, לא נראה כן. כיון שצריך אחד מהם, נראה שכולם שווים, שש"ך לא מחלק ביניהם.
[fn:12] שהש"ך משמע שמסיק כרא"ה שאין חילוק בין הדחה לקינוח.
[fn:13] זה בפירוש בש"ך.
[fn:14] נראה שצריכים זה, שנראה שבציור זה מדבר (שמדבר באופן שבישל בו בשר בחלב).
[fn:15] לא אומר כן ממש בפירוש, אבל כן נראה מלשונו.
[fn:16] כן נראה ממה שלא מזכיר בן יומו.
[fn:17] כן מביא מתוס' ומרדכי.
[fn:18] כן משמע מלשון ש"ך, וכן מוכרח, שמתיר בצונן, והרי אינו מותר בצונן אם לא קונח.
[fn:19] איני יודע אם צריך להיות בן יומו. מסברה, נראה שצריך להיות.
[fn:20] זה מוציא בפירוש מן הגמ'.
[fn:21] כן נראה, שבדר"כ מצה יבישה.
[fn:22] כן נראה, שמצה אינה חריף.
[fn:23] אינו אומר כן בפירוש, אבל כן נראה, ממה שלא מחלק.
[fn:24] יש לדון אם הט"ז סובר שקונח נחשב אינו נקי.
[fn:25] אינו אומר כן בפירוש, אבל כן נראה, ממה שלא מחלק.
[fn:26] הנחתי שלא מחלק, שלא מצאנו שיחלק.
[fn:27] אין זה ממש מוכרח, שיש לומר שיש סיבה אחרת שלא רצה להוקים אותו בו, כמו שצריכים לומר בשאר ציורים שאוסר.
[fn:28] כן נראה, שהט"ז לא מזכיר שום חילוק בין דבר לח לדבר יבש.
[fn:29] איני יודע מה סובר בענין כלי חרס, אם מודה לש"ך שיש להחמיר יותר בו.
[fn:30] כן נראה, ממה שלא מזכיר אותו.
[fn:31] כן נראה ממה שלא מזכיר נקודה זו.
[fn:32] לא מזכיר הדין אם משתמשים בו קבוע.
[fn:33] איני יודע אם יתיר גם אם אוכל שני לח. רק מזכיר היתר בציור שיבש. לא נראה שיחלק, אבל ט"ז רק מדבר בדבר יבש.
