* 1[fn:1]
* To The Tune of- Ashreinu (Dveykus IV)
On Rosh Hashana, there’s a judgment passed on each and every man
so from Elul, we’re expected to do the best we can.
Every drop of joy and sadness that the coming year will find
comes from this tekufah’s actions, so try to keep in mind
Chorus:
Forty days of mercy; forty days of special growth;
forty days to mend our ways- Hashem brings Himself close.
Now’s the time for tshuvah; now’s the time to fix ourself;
Hashem is here this time of year to give us special help.
These are special days for prayer, times to ask Hashem for aid.
On these days to atone for the the eigel, Moshe cried and prayed.
Tell Hashem your fights and struggles; ask Hashem to help you through;
Pray to Him and your tefillah will bring Him close to you.
Chorus.
Often, we can feel inspired, glimpsing kdushah more and more;
after time, we just feel tired- we’ve done this all before.
Tell yourself it’s not for nothing- every action that you do
certainly has brought you something, unnoticed still by you.
Chorus.
And feelings of inspired ambitions, even if they bring no act
lie in wait for those conditions that bring those feelings back.
For, bit by bit, those sparks are mounting; drop by drop they will accrue.
And when you meet a task too daunting, you’ll find they’ll bring you through.
Chorus.
* 2
* To The Tune of: The Six Thirteen Torah Avenue Theme Song
A korban’s checked to make sure it
is truly fine and truly fit
for four days it’s set away
to make that sure the animal’s okay.
Before the din, we do the same-
Removing our neshama’s stain
Four days before, one time a day,
Slichos and vidui we do say.
* 3
* To The Tune of: We Can Do Teshuva (The Purim Story)
Right after each selicha, the yud gimmel middos are said and are prayed right then
they’re a special prayer that moshe received, that came to him straight from Hashem.
By the sin of the egel, Moshe did pray Hashem answered all of his pleas
In this special time, he also was given a tfilah that came guaranteed.
Chorus:
The yud gimmel middos
were given to us by hashem
with these special tfilos
hashem will have rachamim when
we plead our case
and mention his traits
we cry and we daven
hashem hashem
And even in galus, without the korbanos, Hashem will forgive all our sins
This holy prayer does not come back empty, for there was a krisas habris.
Chorus.
This tfilah’s unique- it has no bakasha- we simply recite Hashem’s praise
So learn what you’re saying and start emulating Hashem in these wonderful traits
Chorus.
* 4
* To The Tune of: Acheinu (Lev V’nefesh)
When one does aveiros, a malach is made
To prosecute the sinner – make sure his price is paid
In the beis din shel maalah, this angel asks for stringent din,
And does its best to keep hashem so far away from him.
Chorus:
But when vidui you do say,
This kateigor goes away;
He sees there’s no work to do
And so he leaves you.
Umodeh v’ozev yerucham
Hashem will be mochel on all that you have done
If you tell him what you did, and take on not to sin again
then after you confess, you’ll get kapparah from hashem.
Chorus (replacing “but” with “for”)
Viduy means you say the aveiros that you did,
Say them clearly with your mouth; it’s not enough to think.
Yet saying them is half the job- say it with regret and show
You really feel so bad that you ever acted so.
Chorus (replace “but” with “and”)
* 5
* To The Tune of: Children Of Silence (London School Of Jewish Song)
1
There is a judgement which determines our year,
Our joy and laughter, our sobs and tears.
Think of what happened in the year gone by
How many times you smiled, how many you cried.
2
But, through Hashem’s mercy, we all can emerge
With verdicts that will make us grin
A few simple practices must be observed
To bring Hashem’s rachamim.
3
Forsake your ego and pride
Pray with humility
Like a poor man asking for help
Hashem will answer with mercy.
3
Act with others with care
Have pity on each jew
And Hashem will do the same
He’ll have rachmanus on you.
1
Be you rich or poor, be you old or young
You’ll be judged before Him, same as everyone.
And everything you did, said or thought
Is counted by hashem- there’s nothing he’s forgot.
2
But, through Hashem’s mercy, we all can emerge
With verdicts that will make us grin
A few simple practices must be observed
To bring Hashem’s rachamim.
3
Ignore your right to be mad
See virtue in your friends
Kol hadan lkaf zchus
Hashem will do the same for them.
3
Speak only good not bad
Be wary to accuse
For hashem will act the same
Won’t let the malach prosecute.
* 6
* To The Tune Of: V’zakeini (Baruch levine)
On Rosh Hashanah, we crown Hashem in tfilah-
Hashem’s our ruler- he’s in charge of us
A ruler is someone who cares for every subject
Someone giving; someone we can trust
Chorus:
Hashem is our only king
And we pledge our very lives to him
We accept the ol that a statement like this will bring
We will always follow his commands
Even when we do not understand
Ana avda dkudsha brich hu with pride we sing
Hashem is all controlling all powerful all knowing
What he wishes is what must be
We must ignore our pride that makes us feel control
We must acknowledge that his subjects are we.
Chorus.
While hashem is never lacking there are mitzvos for us he’s asking
They will bring us true good and schar
For as his loyal men, we’re honored and we’re privileged
To do his mitzvos,, whatever they are.
Chorus.
* 7
* To The Tune Of: Olam Haba (Moshe Yess)
Rosh Hashana’s also known,
As yom truah, for we blow
A shofar, ‘cause Hashem said so
Yom tiruah yihyeh lachem.
Hashem makes judgement like bes din
So there must be mekatrigim
The shofar’s sound is baffling
No claim can be made to Hashem.
An ayil’s horn is most preferred;
This day the akeidah occurred
In yitzchak’s stead,, there was a ram slaughtered
It’s shofar brings our prayers to Hashem.
* 8
* To The Tune Of: Shemos Song (613 Torah Avenue)
By the akeidah, Avraham passed
A trying test- his very last-
Yitzchok was then to be brought to Hashem
Vhaalahei lolah
Avraham struggled; he wept and cried
How could he let his ben yachid die
But in the end, he would follow Hashem
And with zrizus gave his all.
Chorus:
Hashem had tested Avraham
He gave up his only son
Yitzchak let this all be done
We try to act the same.
In the tfillos that we say
In the parsha that we lein
We recall as we daven today
And try to act the same
Yitzchak asked to be tightly tied
Fearing he’d jerk and disqualify
The shchitah of Avraham’s ben that he loved
Rosho vraglav akad
In tying Yitzchak gave in to Hashem
And nullified everything other than
The ratzon of Hashem who he loved
So akeidah it is called
Chorus.
The satan tried his very best
To make sure that Avraham failed this test
But despite all the tricks that he threw in the mix
Avraham still stayed strong and true
Though in the end Yitzchak was not killed
There was a ram that was slaughtered still
It stood in his stead as if Yitzchak were dead,
As if Yitzchak had been brought
Chorus.
Avraham and Yitzchak gave in to Hashem
They showed nothing matters other than
Hashem our king, so we follow each thing
And submit ourselves to Him.
And if no akeidah is asked of you
You’ll stilkl have made such a sacrifice too
If you’re set and intent on a korban lahashem,
He’s mitzarfo limaseh.
Chorus.
* 9
* To The Tune Of: Sukkos In Jerusalem (Moshe Yess)
When we hear the shofar blow, we listen with high anticipation
because the shofar’s sound we know signals Hashem’s new coronation
and just like when a new king is anointed
we’re filled with thrill to find that he’s appointed
ki chedvas hashem hu miuzchem
Rosh Hashana is the day of judgement for the yachid and the masses
and that should bring us lots of joy, because if not we’d watch our sins ammasing
this way they will never grow too heavy
before they are forgiven in His mercy
ki chedvas hashem hu miuzchem
and so we sing our tefilos in a pleasant happy manner, with elation
amidst a solemn soberness, in the coming judgement’s trepidation
rosh hashana is a day of simcha
on which we feel a gilu braadah
ki chedvas hashem hu miuzchem
* 10
* To The Tune Of: The Teshuva Song (Marvelous Middos Machine)
Each time a Jew does a sin
it makes hashem farther from him
but with teshuva that all disappears
he’s returned to Hashem, so close and so dear.
the timtun halev that has come
with teshuva will all be undone
his neshama is pure once again
and he’s granted the tools to cling to Hashem
Chorus:
For teshuva is always accepted
hashem’s waiting for your return
your teshuva will not be rejected
and none of your tears will be spurned.
sometimes, we see just how far
and filled with aveiros we are
and we dread we’re too late to atone
can I ever return? can I ever come home?
but teshuva was made for us all
for all of us struggle and fall
and hashem will forgive all your sins
and bring you right back, so close to him
Chorus.
so look at the ways that you’ve strayed
note the mistakes that you’ve made
and regret how you’ve saddened Hashem
and commit that you’ll never do it again
confess to Him what you’ve done wrong
tell him the times you weren’t strong
and with that your forgiveness will come
umodeh viozeiv yerucham
Chorus.
dirshu hashem bihimatzo
call upon Him when he’s close
in these ten days, your sins disavow
and hashem will accept your teshuva right now
Chorus.
* 11
* To The Tune Of: The Lech Lecha Song (613 Torah Avenue)
To finish your teshuva and make sure you grow
you must choose the path where you’ll go
accept a kabbalah you always will guard
and make sure that it’s not too hard
and when your kabbalah is easy to do,
add to it something that’s new
for rung after rung is the way to ascend
the ladder that leads to Hashem
Chorus:
accept to add a tiny drop
try hard to keep at it and never do stop
this bit that you do will surely accrue
and have a hashpaah on you.
When thinking of what you should try to accept
Look back on yourself and reflect
Find the main issue you need to repair
Your pledge should begin right there.
Everyone’s different we all have our fight
So pick what for you seems just right
But there are some things that are one size fits all
These things help all people who fall
Chorus.
Learn sifrei mussar, they’ll show you the way
Through the words of hadracha they say
Torah will fight off the yetzer hara
And help you receive kaparah
Make sure that it can be fulfilled even when
you don’t feel so close to Hashem
Pick something specific and make sure it’s clear
If not, your pledge might disappear
Chorus.
Pick something tiny that’s easy to do
Like the yetzer hara does to you
He never does tell you to do a big sin,
But, bit by bit, he will get in
Prepare a small pad, to track how you’ve done
and work on your pledge with someone
fines and rewards can add some desire,
with mussar that’s meant to inspire
Chorus.
* 12
* To The Tune Of: Vayera Song (613 Song)
In these days no korban is brought
we need yom kippur quite a lot
the only way to cleanse our soul
is the kapparah yom kippur holds
Chorus:
the happiest day of the year
our aveiros disappear
our neshama’s free from sin
when we come right back to him
yom kippur is a special day
a day that’s set aside to pray
our tefilos go straight to Hashem
there’s no force that can block them.
Chorus.
On this day teshuva we must do
Our yachas to hashem renew
Every sin is always seen
Repent and make your soul so clean.
Chorus.
Sooner or later, you’ll have to do
The chores hashem has set for you
Without teshuvah, you’ll have to pay
In the next world, and so we say
Chorus.
* 13
* To The Tune Of: Vayigash Song (613 Song)
When yom kipur goes away,
A shofar we must blow
Hashem forgave us all our sins
That’s what this blast does show
Chorus:
Now we’re holy, now we are pristine
So keep the purity you got and keep your soul so clean.
We break the fast and eat a meal
A seudah of yom tov
And thus, we show the joy we feel
Of kaparas avonos
Chorus.
* Footnotes
[fn:1] Some of the sections have more than one song.
