* Hakdama
* To The Tune Of: Hakshiva (Shalsheles I)
Yomim Tovim are times we celebrate
The favors that Hashem has sent our way.
But they are more by far, for what he did creates
A kedusha that clings close to those days.
Sukkos celebrates the sukkos that Hashem
Granted us for forty wand’ring years.
This time receives the great kedusha that was then,
and brings it back every single year.
Chorus:
As days go by, events will return
As the circle of the year slowly cycles, slowly turns;
Every Yom Tov brings with it a gust
Of kedusha; and grow from it we must.
End of Chorus.
Not only is the same holiness revived-
There is an addition granted too.
Something extra’s gained every single time;
Every sukkos brings us something new.
Special times like these can bring us holiness
That will last us all throughout the year.
So follow his decrees with joy and eagerness;
show hashem you’re happy yom tov’s here.
Chorus.
Chol hamoed too is a special day-
Set aside to come close to Hashem.
Melacha we can’t do, and so we stay away
From anything but focus on Hashem.
* 1
* To The Tune Of: Vi’Samachta Bi’Chagecha
Four minim that we take; four minim that we shake
need not be so nice; they can be rather plain.
But, Jews the whole world through try their best to do
this special mitzvah in the most mehudar way.
Chorus:
We spend our money and our time
as we try so very hard to find
a daled minim that’s divine,
even though a cheaper one is fine.
End of Chorus.
Just go take a look at a daled minim shuk,
overflowed with yidden, crowding near each stall;
they all wish to fulfill His ratzon and his will
in a way that’s special- that’s what brings them all.
Chorus.
We show our boundless love for Hashem above
As we do his mitzvos the very best we can.
His mitzvos we enjoy, and they’re our pride and joy;
So we buy the set that’s beautiful and grand.
Chorus.
Many years ago, it was so hard, we know
Just to get a set that didn’t have a psul.
But, thankfully today no longer is that way;
we all can get a set that is so beautiful.
Chorus.
If our gahsmiyus must be perfectly lovely,
We better make sure that our ruchniyus as well
Is top of the line, the best that we can find;
We better buy the greatest set the store will sell.
Chorus.
* 2
* To The Tune Of: The Lashon Hara Song (Marvelous Midos Machine)
The sukkah is a Zecher to the clouds Hashem did send
To protect the Jews so long ago;
On right, on left, on top, in back, and one to scout ahead,
And one beneath to lift them from below.
Chorus:
Seven clouds that kept us safe from any threat to come
And showed Hashem’s affection for his darling firstborn son
The ananei kavod
The sukkah, too, is shomer you from every sort of harm,
Wrapped up safely, lovingly, in Hashem’s right arm
Biymino tichabkeini.
End of Chorus.
No worldly threats could cause us harm in their warm embrace
We’d be forever safe and sound.
They helped us with our ruchniyus, and lifted us above
The other nations living on the ground.
Chorus.
The sukkah too can bring us to our spiritual goals;
It brings these clouds back in our day.
It’s a mitzvah where we can involve our body as a whole;
We give ourselves to him in every way.
Chorus.
* 3
* To The Tune Of: No Words (Baruch Levine)
We all leave our homes and we go out to live
In a small outdoor hut- in a diras arai;
This shows us exactly just what this world is
Through the life-changing lessons it gives.
Chorus:
All wealth is worthless; all pleasures, pretend;
Our lives have no purpose but yiras Hashem;
All we accomplish, all we achieve
Without fear of Heaven is all make-believe.
End of Chorus.
The sefer koheles on Shabbos is leined,
Which teaches us not to run after pleasures
Of olam hazeh, for in truth they contain
Nothing at all to be gained.
Koheles was written by Melech Shlomo[fn:1],
A powerful king with bountiful treasure;
If riches had value, he surely would know
He says, “mah yisron bichol amalo.”
Chorus.
But nowadays’ world is sadly replete
With many havalim that look like real pleasures;
To make sure their terrible pull can be beat
We must know that torah’s more sweet.
Chorus.
* 4
* To The Tune Of: Oh! My Yerushalayim! (Yossi Tov)
Every yom tov, ther’s a mitzvah to be happy as can be,
And on sukkos this commandment is multiplied by three.
Vihayisa ach sameach, visamachta lifnei hashem,
Vishamachta bichagecha are the three of them.
Chorus:
Sukkos is zman simchaseinu-
We’re happy we’re loved by Hashem.
Sukkos is zman simchaseinu-
We’re so filled with happiness when
We’re serving our King and we’re close to Hashem.
End of Chorus.
There’s a mitzvah every second to be happy and be glad
Make sure not to waste a second by feeling down and sad.
And if you’re happy on this yom tov, Hashem will make that feeling stay
And Hashem will keep you happy every other day.
Chorus.
We buy special food and clothing that will help us feel this joy-
Meat for men and clothes for ladies and nosh for the little boys.
And that’s why the time of harvests is the time of sukkos day,
For it brings a joy that helps us feel so glad, and grow this way.
Chorus.
* 5, 6
* To The Tune Of: Shabbos Yerushalayim (Miami Boys Choir)
Every mitzvah should be done with happiness-
The zchus should make us feel so good.
Simchas mitzva brings Hashem on us to rest
More than the mitzvah ever could.
So, understand how very grad a mitzvah is-
It has a heavy impact on
The gashmiyus, the ruchniyus of all that is-
You’re helping everything along.
Chorus:
We have to serve Hashem with simcha,
Every mitzvah done so happily
And, try hard not to do, just ‘cause Hashem said to
We have to do the mitzvos with happy joyous glee.
End of Chorus.
What a special privilege to serve our King!
We’re proud and thrilled to work for Him.
Hashem picked us as servants and so everything
We do for Him should make us grin.
Thoughts of schar will bring you far and keep you glad-
The mitzvos make us feel so rich!
Olam haba is the best schar to be had-
And every mitzvah leads to it!
Chorus.
* 7
* To The Tune Of: Hamalach (Dveykus IV)
All the moadim are done.
The last day of sukkos has come and has gone-
“Won’t you please stay just a little more?;
The thought of you gone makes me sore.”
We’re connected together again,
With no outside parties- just us and Hashem.
We come back and have Hsshem alone;
There’s no need for a mitzvas hayom[fn:2]
Chorus:
Ikvu imi od yom echad!
Hashem wraps us up in a warm loving hug
Just one more day- won’t you please stay?
I’m so sad you’re going away.
End of chorus.
Nagilah vinismicha bach-
We dance with the Torah, which we love so much;
It keeps us so close all throughout the year,
And that’s why we hold it so dear.
Each yid will twirl and dance;
For in limud hatorah, we all have the chance,
For the point is just how hard we try,
And not if we’re learned or wise.
Chorus.
* Footnotes
[fn:1] Pronounce this as “oh,” not as “oy.”
[fn:2] Pronounce this as “oh,” not “oy.”
