* לט
משנה אומר שכל אחד עשר יום של זיבה, אשה בחזקת טהרה. בגמ’, יש כמה פשטים לאיזה נפקא מינא זה נאמר. פשט אחד הוא שמחדש שאין קביעות וסת בימי זיבה. אף אם שלש פעמים ראתה דם בימי זיבה, אין לה וסת לראות דם אז.
רב יוסף אמר שלא שמע אותו מימרא (ששכח ר“י את תלמודו, והיה שואל אם היה יודע, לפני ששכח, אותו מימרא). אמר לו אביי שהוא ידע אותו ושנה אותו להם. לא אמר כן על המשנה, אלא על בריי’. בריי’ אומר שאם היה לה וסת קבוע ביום חמשה עשר, וראתה ביום עשרים, אין וסת שלה בטל, וכשיבא חמשה עשר עוד, אסורה לשמש. אבל, ניתוסף לה וסת אחר, וצריכה לחוש שתראה ביום עשרים, ואז אף אז אסורה בביאה.[fn:1] כמו“כ, אם ראתה ביום עשרים, ושוב ראתה עוד ביום עשרים, שאז נמצא ששינה שני פעמים, שני הימים- חמש עשרה ועשרים- אסורים בשימוש, שצריכים לחוש לראייה בשניהם. על זה, אמר רב יוסף בשם רב יהודה בשם שמואל שכוונת הבריי’ כשאומר שהיה לה ווסת ביום חמש עשרה אינו שהיה לה וסת ביום חמש עשרה מראייתה, שאז נמצא שהיה בתוך ימי זיבתה (שהרי, כל הגלגל, מראייה ראשונה, הוא שמנה עשרה ימים), ואין קובעים וסת בתוך ימי זיבה. אלא, הפירוש הוא חמשה עשר ימים מיום טבילתה, שהוא עשרים ושנים ימים מראייה. אז, הווסת אינו בימי נדות, אלא בימי זיבה.
ר“פ אמר שאמר שמועה זו לפני ר“י מדסקרתא, ושאל לו[fn:2] אם, אף שאין וסת, צריכים לחוש ליום וסת שבימי זיבה. אין הנחה שרואה אז- למשל, אין קולת מעל“ע, ואין צריכים שלש פעמים כדי לשנות את הווסת שלה- אבל אולי יש חשש שרואה אז, ואסור לשמש עם בעלה אז. לא ענה לו ר“י, והתחיל ר“פ לדון. מביא בריי’ שהבאנו לעיל, ודן עליו. הרי, נניח שוסת שלה, של יום חמשה עשר, היה ביום ראש חודש (ונניח כל חדש להיות שלשים יום), ולא ראתה אז, אלא ראתה ביום חמש לחדש. אז, וסת שניה, שהוא יום עשרים ושנים יום מוסת שלה, יהיה עשרים ושנים[fn:3] שבחדש. הרי, בין ראייה שלה, אז, לימי וסת שלה, יש שבע עשרה ימים. נמצא, אז, שוסת שלה נמצא בסוף ימי זיבתה. אף על פי כן, משנה אומר שאסור לשמש אז.[fn:4]
מעורר גמ’ שנמצא שמניח ר“פ שלמצוא וסת שלה, היינו מונים מוסת שלה שעבר, אף שלא ראתה אז. מקשה ר“ה בדר“י שנמנה מראייתה. אז, כיון שראתה ביום חמישי, יהיה הווסת שלה ביום עשרים ושבע. אז, וסת שלה הוא בתוך ימי נדתה, ולא בתוך ימי זיבתה; ואין ראיה לשאלת ר“פ. מביא ראיה שנמנה כך ממה שראינו במציאות כעין זה בביצת תרנגול, שאם למודה להיות מטילה ביתה ביום ראשון ושלא להטיל ביום שלאחריו, ושוב לשני ימים לא הטילה, כשחוזר להיות מטילה אחד לשני ימים, מתחיל מיום שלאחר שני הימים, ונמשך להטיל בכל יום אחר. נמצא שהווסת שלה נמנה, אז, משעת הטלה, ולא משעת וסת הראשון.
מק’ גמ’ על שיטת ר“ה בדר“י שלנו משיטת ר“י. חלקו רבי יוחנן ור“ל אם אשה קובעת וסת בימי נדתה או לא קובעת וסת. (שניהם מודים שקובעת בימי זיבתה, ואז הם חולקים על שמועה זו.)אז, רבי יוחנן, שאומר שאשה קובעת וסת, חולק על שמועה זו. צריכים לבאר מהו קביעות בימי נדות. מסביר גמ’ שראתה בר“ח וביום חמישי (שהוא בתוך ימי נדתה), וכן ראתה עוד פעם, ובפעם שלישית, רק ראתה ביום חמישי. ממה שנקרא קביעות וסת בתוך ימי נדה, משמע שמונים מוסת שלה, דהיי’ שכיון שהיתה רואה ביום ר"ח, חמש ימים אחריו נקרא יום נדות, אף שלא ראתה בר"ח. דוחה גמ’ שהציור הוא שראתה בר"ח שני פעמים, ושוב ראתה בעשרים וחמש לחדש ושוב בר“ח, שאז ראייה שלישית הוא בתוך ימי נדה.[fn:5]
* מח:
בריי’ מדבר על בנים ובנות שצריכים להיות נדבקים כדי לדעת אם הם גדולים או קטנים. בנות לא נבדקות ע"י אנשים, אלא רק ע“י נשים. מחדש ת“ק (וכן סובר רבי אליעזר ורבי ישמעאל) שנשים נאמנות להגיד מה שמצאו בבדיקה שלהן.[fn:6]
רבי יהודה חולק ואומר שלפני הפרק (כשהיא פחותה מבת יא), וכן אחר הפרק (כשיהא יתירה מבת יא), נשים נאמנות. אבל, אין נאמנות על בת יא. מסביר גמ’ שסובר שתוך הפרק כלאחר פרק, דהיינו שאם יש לה סימנים אז, היא גדולה. אבל, חזקת רבא, שאחר שאשה היא בת יב, מוחזקת שיש לה סימנים, לא נוהג אז. אשה רק נאמנת עם חזקת רבא (ומוסיפים נאמנות אף להקל), ואז רק נאמנת אחר הפרק, ולא בתוך הפרק. (לא הבנתי למה נאמן לפני הפרק. אולי הוא מפני שרק מוקים אותה על חזקת קטנות שלה, שהרי היתה קטנה לני כן.)
רבי שמעון חולק, ואומר שנאמנות תוך הפרק. גמ’ מסביר שסובר שתוך הפרק כלפני הפרק. אז, אין שערות אז אומרים גדולתה, אלא אומרים ששערות שלאחר הפרק הם שומא, ואז אשה נאמנת, כמו שהיא נאמנת על לפני הפרק לדברי הכל.
משנה מוסיף שנאמנת להחמיר. דן גמ’ מי אומר כן. אפשר שרבי יהודה אומר כן על תוך הפרק, שאף שאין לה נאמנות, יש לה נאמנות די להחמיר על פי דיבורה. גם אפשר שדברי רבי שמעון הוא, ולא סובר שיש חזקה דרבא. כיון שכן, אין אשה נאמנת לאחר הפרק, אלא רק חוששים לדבריה. ותחשב.
* נג
אם אשה רואה דם על בגדיה, אז זה הנקרא כתם. דין כתם הוא כך: אם יכולה לתלות על שום דבר, היא תולה, ולא חוששת. אף אם לא עברה קרוב לדם, יכולה לתלות תמיד על מאכולת. אבל, אין כל כך דם בתוך מאכולת. אז, אם ראתה כגריס דם, אין מה לתלות בה. אז, חוששת שראתה דם.
משנה (נב:) מביא מחלקת בין רבי מאיר לרבנן (גמ’ מפרש ש“רבנן“ הוא ר“ח בן אנטיגנוס) אם חוששים לזיבות מחמת כתם[fn:7] או לא חוששים. לקמן (בגמ’) שיטתם יבואר.
גמ’ מבאר שלר“ח, אין שום כתם אחד יכול לעשות אשה לזבה בפני עצמה. אבל, אם ראתה ממש לשני ימים, יכול כתם לצרף עמהם. כמו“כ, אם ראתה שלש כתמים על שלש בגדים שלבשה בשלשה ימים זא“ז, היא זבה.
רבא אומר שיותר מסתבר לומר כר“ח מלומר כרבי מאיר[fn:8] כיון ששיטת ר“מ כמעט סותר א“ע. הרי, להיות זבה, צריכה לראות דם לשלשה ימים רצופים. לכן, סוברים ר“מ שאם רק ראתה שני גריסים וחצי, לא מטמאה, שיש לומר שראתה שניהם בשני ימים, ולא בשלשה. אז, אף אם ראתה שלש גריסים, יש לחוש שנים וחצי בשני ימים, ושהשאר בא ממאכלת.[fn:9] ר“מ חולק ואומר שכיון שאפשר לחלק אותו לשיעור כתם לכל יום (דהיי’ גריס לכל יום), כך עושים, וכך מניחים.
מק’ גמ’ שא“כ יודה ר“ח גבי שלש גריסים בשלש מקומות בבגד אחד, כיון שאי אפשר לחלק אותם לשני ימים[fn:10]. הרי, בריי’ אומר שמודה ר“ח גבי בשלש חלוקות, שמשמע שבשלש מקומות בחלוק אחד לא מודה ר“ח. גמ’ מפר’ שרק מק’ לשיטת ר“מ- לומר שיודו לו עכ“פ שרק גבי שלש מקומות בבגד אחת מטמא יש לחוש.
גמ’ מביא בריי’. בריי’ מזכיר מחלקת (אליבא דר“מ, לכאו’) כמה צריכה לראות כדי שנחוש לזיבה. ת“ק אומר שצריכה לראות שלש גריסים. אבל, ר“י בן אגרא אמר משום רבי יוסי שאף אם רואה פחות מזה, חוששים. על זה אמר רבי שדברי ת“ק נראים כשבדק ודברי ר“י נראים כשלא בדק.
גמ’ מסביר שכאן בדקה עצמה ולא בדקה חלוקה. הצד שיכול לטמא בלי שלש גריסים הוא שראתה רק שני פעמים- ועדיין היא זבה. זה נמצא אם ראתה בין השמשות. אז, צריכים שתבדוק א“ע בין השמשות. הרי, חלקו מהו בין השמשות. בריי’ שלנו מדבר בשבדקה בתוך ביה"ש של רבי יהודה, ולא ראתה, אבל לא בשל רבי יוסי. לכן, רבי יוסי עוד חושש שראתה בין השמשות. אבל, עדיין צריכים להסביר דברי רבי.
נראים דברי רבי יוסי כשלא בדקה- יש שני אפשריות של לא בדקה:
1. לא בדקה כלל.
2. לא בדקה בשל רבי יוסי, אבל בדקה בשל רבי יהודה.
גמ’ דוחה צד שני. ממה שרבי אומר ששם נראה לו דברי רבי יוסי, ולא רק אומר שנראים לו דברי רבי יוסי, צריך לומר שחולקים גם בציור שיותר יש לומר כרבנן. צריך לומר שהוא בציור שבדקו בשני ביה“ש. אז, קשה איך רבי יוסי יחלוק שם. אז, צריך לומר שלא כ2 כאן, אלא כ1. נמצא שחולקים בציור שלא בדקה כלל- ושם נראה לרבי כרבי יוסי- ובציור שבדקה בביה“ש של רבי יהודה, ולא של רבי יוסי- ושם נראה לרבי כת“ק.
נראים דברי רבנן כשבדקה- יש שני אפשריות של ”בדקה“:
1. בדקה בשל רבי יהודה, אבל לא בשל רבי יוסי.
2. בדקה בשל רבי יוסי ורבי יהודה.[fn:11]
גמ’ דוחה ראשון. כיון שיש מקום שלא נראה דברי ת“ק, צריך לומר שחולקים גם כשלא בדק פחות מזה. אם נאמר כראשון, צריך לומר שחולקים כשלא בדק כלל. זה לא מסתבר. אז, צריך לומר כצד שני. נמצא שחולקים בציור שבדקה בשל רבי יהודה אבל לא בשל רבי יוסי- ושם נראה כרבי יוסי- ובציור שבדקה בשל רבי יוסי ורבי יהודה, ושם נראה לרבי כת“ק.
נמצא שיש סתירה בין שני דברי רבי, שגבי בדקה בשל רבי יהודה אבל לא בשל רבי יוסי, בדיבור ראשון אמר שמודה לת“ק ובשני אמר שמודה לרבי יוסי.[fn:12]
תי’ גמ’ שדיבור ראשון של רבי אמר שלא חולקים אם לא בדקו כלל, שאז נראים דברי רבי יוסי לת“ק. ודע שעדיין יש שני דרכים לבאר המשך של רבי, שיש לדון אם ממשיך לומר שכו“ע מודים לת"ק כשבדקה בשל רבי יהודה ורבי יוסי או שאומר שכשבדק רק בשל רבי יהודה, נראה לו דברי ת“ק, שדבריהם יותר מסתברים. יש להעיר שאם נאמר כשני, יש לדון איזה ”נאמר“ הוא לבאר המחלקת ואיזה הוא לבאר שיטת רבי, שהיה יכול להיות לשני הצדדים. ותחשב.
שוב ראיתי שרש"י מפרש שמילים של גמ’ מפרשים שניהם, שאומר שנראים דברי ר“י לכולם אם לא בדקה, שנראה שרבנן רק חולקים אם בדקה. אם כן, נמצא ש“נראה“ אומר שני דברים חלוקים.
גמ’ מביא בריי’ אחרת. אותו בריי’ מביא שרבי יוסי אומר שרק חוששים אם יש בו שלש גריסים (כשיטת תנא קמא), אבל רבי אומר בשם רבי יוסי שאף חוששים כשיש שני גריסים. רבי אומר ששמועה ראשונה (דהיי’, כת“ק) נראה כשבדקה.
יש אותם שני צדדים בביאור בדיקה- אולי בדקה רק בשל רבי יהודה או אולי בדקה בשניהם. אומר שאי אפשר שרק בדקה בשל רבי יהודה, שאז היה יוצא ששיטה ראשונה הוא אף אם לא בדקה כלל (שיש מקום שחולק שלא נראה כמותו). קשה איך חולק שם. אלא, צריך לומר שרק נראה שיטה ראשונה כשבדקה בשניהם. אז, נמצא ששיטה ראשונה סובר שאם בדקה רק בשל רבי יהודה, צריכים שלש גריסים. קשה, שהרי שיטה ראשונה של שם הוא רבי יוסי של בריי’ ראשון (הוא אותו תנא שאומר שניהם). אז, נמצא שיש סתירה, שבבריי’ ראשון, לפי רבי, סובר שלא צריכים שלש גריסים אם בדקה רק בשל רבי יהודה, ובבריי’ שני סובר שצריכים שלש גריסים אם בדקה רק בשל רבי יהודה.
היה נראה לומר שאף לולי רבי, זה היה קשה, שבבריי’ ראשונה אמר אותו שיטה לר“י שלא צריכים שלש גריסים, ובבריי’ שני אומר שלא צריכים שלש גריסים. זה היה אפשר לתרץ בלי רבי, שהיה אפשר לומר שצריכים שלש גריסים כשבדקה בשניהם (ושם אין חולק), ולא צריכים שלש גריסים אם רק בדק בשל רבי יהודה. אבל, כיון שרבי מפרש שבריי’ שנית הוא כשבדק רק בשל רבי יהודה (שהרי, רבי מפרש ששיטה ראשונה חולק עמו בשני מקומות, וצריך לומר, אז, שאחד מהם הוא כשבדק רק בשל רבי יהודה. אז, על פי רבי, קשה הוא. צריך לומר שיש שני תנאים אליבא דאותו שיטה (ר“י בן אגרא) אליבא דרבי יוסי. (כמובן, שניהם סוברים כרבי יוסי, שהם בשם רבי יוסי. חולקים אם בדיקה בבין השמשות של רבי יהודה יעשה בדיקה בביה“ש של רבי יוסי. תלוי באם ביה"ש של רבי יוסי הוא בתוך ביה“ש של רבי יהודה או אחריו.)
* Footnotes
[fn:1] אינו פשוט לי למה חוששת ביום כ’, שרק ראתה אז פעם אחת, ואין קביעות וסת בפעם אחת. אולי כיון שיודעים שהיא אשה עם וסת, מסתבר ששינוי שלה עשה וסת.
[fn:2] מגמ’ לא כל כך פשוט מה קרה. נראה שר“פ שאל לר“י (אבל אפשר להיות הפוך), שכן נראה מהמשך הגמ’.
[fn:3] כן מניח רש"י. כנראה, מניח שהעשרים ושנים ימים כוללים יום ראייה. לא מוכרח כן, אבל אין חילוק גדול.
[fn:4] ויש לדון, שקבעה וסת שלה בתוך ימי נידתה, אלא שעכשיו נמצא שהוא בתוך ימי זיבה.
[fn:5] יש לדון ל"ל תי’ שחולקים כשראתה כל ר“ח ויום חמשה.ותחשב.
[fn:6] כן הפשטות- שת“ק הוא שיטה בפני עצמה. ויש לדון; וצל“ע.
[fn:7] יש להעיר שבכל ציור שכתם עושה זב (אף בציורים שלר“ח), לא עושה זב וודאי, אלא ספק. יש נפקא מינא בהבאת קרבנות.
[fn:8] לאיזה סיבה, מתחיל גמ’ לקרוא לרבי מאיר בשם רבנן כאן.
[fn:9] אין כל ענין זה כל כך ברור לי. ראשון, צריך ביאור למה לא חוששים בשנים וחצי שהחצי בא ממאכלת. אולי זהו כוונת גמ’. אבל, לא נראה כן, שאז מהו קושיית ר“ח, שאולי רק מניחים שבא מאכלת אחד. נראה שצריך לומר שידע בתוך שיטת רבנן שרק יש חשש שראה בשני ימים. אז, אמר שיהיה עוד חשש, דהיי’ החשש למאכלת. אבל, דע שעדיין יודה ברואה כארבע גריסים. גם לא פשוט לי למה לא הקיל, אילו היה, באמת, שלש גריסים, כיון שאפשר שראתה כולו בשני ימים. משמע שמודה קצת לסברת רבי מאיר (ואני לא הבנתי אותו סברה כל כך), דהיי’ שכיון שאפשר לחלק לימים מחלקים אותו.
[fn:10] יש לדון ל"ל, שאולי מקום נתינתו שינה קצת בתוך היום.
[fn:11] צריך ביאור ל"ל דוחה את זה לומר שאילו כאן היה נראים דברי רבי מאיר, צריך לומר שרבי יוסי חולק. נראה שהיה אפשר לדחות שמכוון לומר ששם דברי ת“ק נראים לר“י. ותחשב. כמו“כ יש להעיר גם לעיל, בדיון על ר"י.
[fn:12] לכאו’, יש קושיה אחרת, והוא שמשמע שחולקים בשני דברים, אבל גמ’ דחה את זה מסברה. אז, קשה איך בכלל מחלק רבי.
