* ב:
** גמרא והא וכן קתני -
ק"ק למה לא אמר שקאי על חיוב לבנות כותל (שהוא במצב חלוק, אלא שבשניהם, באותו מצב חייב). ותחשב.
** כותל חצר שנפל -
יש לדון אם הוא מפני שזכאו בכותל (רצה לומר, יש לו זכות להיות לו כותל) או שזכאי בחצר בלי היזק ראייה. ותו"ת. גם יש לומר צד אחר, והוא שכיון שהוא כבר רגיל בכותל, הוא יותר כבית, ויותר יעשה בו דברים צנועים.
על פי זה, יש לבאר שמה שלא חייב ביותר בארבע הוא שאינו כל כך טוב, ואז אין בו כל כך זכות. יש לדון בזה, שהניחא לצד בתרא, יש לומר שלא הורגל בכל כך כמה דברים שהם כל כך צנועים. אז, אין כל כך היזק. לצד ראשון ושני, עדיין צריך ביאור, שיש לו אותו זכות. וצריך לומר שמניחים שמוחל עליו כיון שאין בו כל כך טוב. ולא נראה, שהרי עומד וצווח. ויש לומר שאז זכות חברו בחצר (שיהיה כמה שרוצה) דוחה זכותו. זה מניח שכיון שהזכות לא הביא לו כל כך הנאה, אינו זכות כל כך חזק. ותחשב.
** דרבים -
יש לדון אם הוא מפני שיש יותר בני אדם שרואים או שרואים ביותר זמנים. ותו"ת.
** ולא ידענא -
ואם תאמר לא יעשה כלל, ולא יהיה גרוע מחצר. ויש לומר שר"ל שלא יכול לראותו, ואז לא ידע זמן שאינו שם לעשות מלאכה צנועה. קשה, שאם כן, לא היה לו לומר, “לדידך לא קביעא,” אלא שאינו יכול לראותו אותו. אולי רצה לומר שמפני זה יעשה מלאכה, ויהיה מתבייש, משא"כ בחצר, שאף לא יתחיל. ודחוק, שלא היה לו להתחיל, כיון שיודע שהוא רע לו, ואף שאינו קבוע. ותחשב.
** אסור לאדם -
כיון שלא מזכיר שיש שום אדם אחר שם, וכיון שלא מזכיר שהוא כן בכל ציור, אלא רק בשדה, פשוט שלא אומר רק שיש היזק ראייה, ואז צריך לומר שאומר דין אחר. מזה מביא גמרא ראיה.
** רש"י הוה אמינא במסיפס -
עיין במש"א. קשה, שאז הוא שווה להוה אמינא שדוחה גמרא כשאומר שהיה לו לומר "לחצות.” ואולי צריך שני הדיוקים לדחותו. לולי רש"י, היה אפשר לומר שאומר שצריכים לחלוק, ואם אף רצו לעשות מסיפס, עושים. ותחשב.
* ג.
** גמרא שקנו -
נמצא שעושה קנין רגיל עליו. קשה איך עושה קנין לעשות כותל (אם רצו קאי על בנין כותל). ותחשב.
** ולטעמיך גויל -
בכל כעין זה, יש לדון מהו ה"לטעמיך,” שלכאורה, מקשה רק ממה שלא הקשה עוד. אז, מוכיח, לכאורה, רק שהמקשה לא סובר שקושייתו קשה. ק"ק, שמה חשב המקשה; אם ממש חשב כן, היה פשוט לתרץ. אם לא חשב כן, קשה למה לא הקשה על שניהם. ותחשב. גם יש להעיר שאם נאמר שמקשה על גויל, הקשה על ראשון, ואינו כל כך קשה למה לא הקשה על האחרת, שכבר הקשה, והוא אותו קושיה. ותחשב.
** קאי -
ק"ק, שדילמא המנהג הוא לעשות מחיצת חצר שעומד בחוזק, אבל אין צריך לזה לעמוד בלי כל כך חוזק, וכך היה בבית המקדש. ונראה שאינו מסתבר לגמרא לומר שמחיצת בית המקדש (שהוא חשוב, וצריך לקיים, ואין בו עניות) גרוע מכותל חצר. ותו"ת.
** גמרא גמירי -
משמע שאומר לשון זה אף על דבר שאינו הלכה למשה מסיני. חושב אני ששמעתי שכ"פ שאומר כן, הרמב"ם לא מפרש שהוא הל"מ. גמרא זה טוב למה שכתב.
* ג:
** גמרא עבדא -
לכאורה, זה נגד שמואל שסובר שכל עבד שאין לו רב אינו עבד, והרי כאן מת רבו.
** מלך… תיוהא -
נראה שטעם ראשון רק מהני אם הבעיא הוא פשיעותא, ולא אם הבעיה הוא צלויי בינתיים. נראה שלכן נותן סיבה שנית.
ויש להעיר שהיה אפשר לומר שכל בעיה של צלותא לא שייך בבית המקדש, שאין כל כך צורך להיות בכל זמן מקום לקרבנות כמו שיש להיות בכל זמן מקום להתפלל. ויש לדון.
** אי כולהו
־ לכאורה, אז, אין צריך לומר שלא היה קאי בלי גג. ויש לדון, שאולי "כולו" לא אומר "כולו" דווקא, אלא מה שנוהג גבי בית ראשון (שממנו לומד), ואולי אם יש שלושים של מחיצה, מהני. ותחשב.
** דיקא נמי -
נראה שאין זה עושה שמסיק שאומר הוא בטינא, שאולי יש אריח שהוא רק שני טפחים או כדומה. ויל"ד, שלא מצאנו שרבנן מדברים עליו. ויש לדון.
** כי היכי -
צריך לומר שחשב שלא שמעו את קולה. גם יש לומר שחשב שיחשבו בני אדם שהציל אותה או שחזרה מלהמית את עצמה. ותחשב.
** רברבתא -
יש לדון למה לא אומר כאן "זוטרתא" או "רברבתא.” קצת משמע שחילוק בין רברבתא וזוטרתא הוא גודל טפחים, ולא מעט זה, ואז כבר נשמע ממה שאומר מנין טפחיו. ויש לדון, שאולי זוטרתא הוא הסתם.
** שרגי -
דנים אחרונים מה חייב אדם ליתן לפקח נפש חבירו. יש להעיר שלכאורה, פדיון שבויים יש בו פקוח נפש (עיין גמרא לקמן שאומר שהוא מצוה רבה כיון ד"כולם אית ביה"). עדיין אומר גמרא שאינו חייב ליתן בית בנוי. ותחשב. ויש לדון אם כל גמרא דן אם זה יותר מחומש של ממונו או לא. גם יש להעיר שאולי הוא חלוק כאן כיון שהוא ממון הציבור, ואז הוא למה שהציבור צריכים יותר.[fn:1]
** כל מאן -
יש לדון למה לא רק מניחים שהוא שקרן:
1. אולי הוא מפני שאין אדם משקר ביחוסם חוץ מעבד שצריך לברוא יחוס לעצמו. ויש לדון, שגם היה יכול להיות חסיד.
2. אולי הוא מפני שמסתמא בא מהורדוס, וחושב שבא ממלכות.
* ד.
** גמרא אהדר -
יש לדון אם אומר שעשה שני דברים (נתן זה עליו, וגם נקט את עיניו). יש לדון למה צריך לזה. יש לומר שנתנו עליו, וזה נקר את עיניו. יש לדון למה לא רק נקר בעצמו באופן יותר קל. גם יש לומר שאמר שנתן לו דבר שהיה מנקר עיניו כדי שלא יראה ולא ייסמה.
** לגובא -
מעניין שזה נחשב עונש, כיון שניצל.
** דזהרי -
לא היה זה כל כך חכמה, שאולי היה כל כך זהיר רק מפני שידע שאותו מלך הרג כל שאר חכמים, ואז אין טוב להלחם עמו.
** מסתפינא -
אם כן, מעניין שעדיין אומרים, “מלכותא… ולא הדר.”
** רבנן -
ק"ק איך היו רבנן אז.
** דאי לא מלכות -
יש לדון למה:
1. אין לאחר כוח וממון לבנות אותו.
2. לא היה יכול לאחר לבנות אותו מפני הבעיה שאומר בגמרא לעיל.
** דאי לא -
יש לדון למה היה צריך להבנות:
1. אולי מפני שחזי תיוהא. זה אי אפשר ל2 שכתבנו בדבור לעיל.
2. אולי מפני שאז יהיה יותר טוב. ותו"ת.
** עבדא -
יש להעיר שלשמואל, שמי שמפקיר עבדו, עבדו יוצא לחירות, לא היה עוד עבד, אלא היה בן חורין.
* ד:
** גמרא אם עמד ניקף -
אז, כשאומר לעיל, “לא שנא…,” הוא נגד זה.
** טינא -
לא הבנתי, אז, למה צריך שיוציא סינופי יריכי (אבל ממה שלא אמר גמרא "אלא" משמע שלא חזר בו). ותחשב.
** אלא בשטרא -
או חולק על רבי יוחנן לעיל או סובר שטינא ע"ג הו"ד חלוק מע"ג כותל. ותו"ת.
** ואי לא עביד חבריה -
קשה, שהוספת חזית יהיה ליפותא, ויהיה ניכר, ולא ירווח. ותחשב.
** אביי -
נראה שכוונת גמרא לומר שאומר תקנה לרמאי, ואף שלא היה אומר כן בדרך כלל, אומר כן כאן לגלות דין אחר, והוא לאפוקי מדאביי. ותחשב.
הדרך שמגלה אותו הוא שצריך להיות דין, ואין דין בלי זה, ואז צריך לומר שזהו הדין הנצרך. ותו"ת.
** רש"י אגר נטירא -
עיין במה שפירש רש"י. נראה שגם אפשר לומר שפירושו הוא כמו "אגר נטר" של ריבית, והוא שאם לא היה בונה, אלא היה שוכר שומר, היה משלם לו דבר מועט לכל שנה, ולא כולו כאחד. אז, היה לו הממון ליותר זמן. אותו ממון של אגר נטר (שהיה נשכר כיון שהיה אותו ממון אצלו לזמן יותר) מנכה ממה שמשלם. יש לדון, שגמרא משמע שמשלם אגר נטירה, ולא שמנכה אגר נטירה. ותו"ת.
* ה.
** גמרא הקובע זמן -
משמע שהוא רק כשקובע זמן, והוא שכיון שקבע שיהיה אז, מסתבר שרוצה שיהיה יכול להשאיר הממון אצלו עד הזמן, ולא ישלם בתוך הזמן. אולי סתם הלוואה, שהוא לשלושים יום, לא יהיה לו דין זה, וכולי עלמא יודו לאביי ורבא. יש לדון, שאולי אף זה נכלל בלשון קביעות זמן, שעל ידי מה שלא פירש, קבע זמן (לא רק מפני שנעשה שכן קורה ממילא, אלא אף מפני שאולי הסיבה שסתם הלוואה הוא לשלושים יום הוא מפני שכן רוצים סתם בני אדם. אם כן, כשאמר שילווה סתם, זמן קצב).
יש לציין לרש"י שאומר, “במלווה שהלוהו" שעושה את המלווה לסובגק"ט, ולא את הלווה. אולי משמע שהמלווה הוא הקובע זמן, ולא הלווה. אם כן, אי אפשר לומר כמש"כ.
ודע שאולי אז יש לבאר להפך שרק אם קבע לו מלווה זמן אומרים אביי ורבא שיטתם, שרק אז רואה מלווה שמקפיד לווה, ואז מנסים לשלם לו בזמנו. ותחשב.
** רש"י הקובע זמן -
יש לדון למה מניח שמיירי במלווה הקובע זמן (עיין לעיל, שבארנו שכן משמע מלשון רש"י. ויש לדון בזה.). יש לומר שהוא מפני שסבר שרבא ואביי לא יאמרו שיטתם אלא אם כן קבע מלווה זמן. גם יש לומר שבא לבאר שלא קבע לווה זמן (שאם קבע, אז, אולי לא היה רבא ואביי אומרים שישלם תוך זמנו). גם יש לומר שפירש גמרא כן רק מפני שדרך הוא שהמלווה יקבע זמן, כיון שהוא ה"בעל דבר" (רצה לומר, שהלווה שואל לחסדו, ואז, בדרך כלל, לא עושה תנאים). ויש לדון.
* ה:
** גמרא תא שמע -
לכאורה, מקשה ראשון ידע התשובה לזה, שאי לאו הכי, היה לו לדעת שמוכרח שאי אפשר להביא ראיה מתחילת המשנה. אז, צריך לומר שיש שני מקשים. ויש לדון, שיש לומר שידע שיש סתירה, ולא ידע איך להשיב לו, ואז הקשה בכל אחד לראות איך ישיב לו המבאר מחלקת אביי ורבא. גם יש לומר שידע תשובה, אבל כיון שראה שהשיב המשיב תשובה אחרת, סבר שלכאורה, אין אותו דחייה נכון. אז, הביא ראיה ממנו, ועדיין דחה אותו משיב מאותו תשובה שהיה סובר המקשה לומר. ותו"ת.
** שאני הכא -
יש לדון מה אומר:
1. אפשר שאומר שאין הכי נמי, קשה מהו החידוש, שאז הוא פשוט, אלא שמוכרחים אנו לומר שאין חידוש (ושהוא אגב סיפא), שהרי כל זמן הוא זמנו.[fn:2]
2. גם אפשר שאומר שהוא גופא מחדש שכל שיפא ושיפא זמנו. לכאורה, נראה שזה חידוש, שהרי לא ידע מקשה את זה. ותחשב.
** זימניה הוא -
כאן, לכאורה, לא קבעו זמן, אלא הזמן נקבע ממילא. אף על פי כן, מניח גמרא שאין לחלק. זה שייך למש"כ לעיל בד"ה הקובע זמן (על גמרא).
ודע שאפשר שזה גופא הוא חידוש של המשנה (שהם שווים). ותחשב. כדי לומר כן, צריך להניח שבראיית גמרא, “זמנו" היה זמן שקבע, ומיירי בשקבעו זמן. אם כן, היה יכול לתרץ שלא קבע זמן, ושחייב בגמר כותל, אלא שסבר שחייב אף קודם לכן. ותחשב.
** מי יימר דמחייבי -
לכאורה, יש בזה שני ענינים:
1. יש לו טענה טובה, וסובר שיצדק בדין.
2. חושב שהוא נכון (ושהוא, באמת, פטור), ואז סובר שרבנן יכריעו כמותו בדין.
יש לדון מהו הדין אם יש רק אחד (יודע שיש לו טענה טובה לרמות או יודע שהוא נכון, אבל חושב שאין לו טענה טובה).[fn:3]
** אלא בשבועה -
יש לדון מה אומר:
1. אף שבדרך כלל, צריכים שבועה, כאן הוא כל כך פשוט עד שאף אין צריכים שבועה.
2. אף שבדרך כלל, כל כך קשה לפרוע מהם עד שלעולם, אף בלי טענה, צריך שבועה, כאן, שיש טענה ש,למקצת אמוראים, טוב, אולי הוה אמינא שהוא פטור, אבל הוא כל כך פשוט, שיכול להגבות, אם נשבע. ותחשב.
ונראה כראשון.
** במקום חזקה -
יש להעיר שאולי אין כל "מה לי לשקר" כל כך חזק, אבל "מלל"ש" זה חזק ביותר, שנראה מוזר לומר כמה שאומר, ויותר היה לו לומר טענת "פרעתי בזמנו.” אז, יש פחות סיבות שיגרום שיאמר כן, וצריך לומר שאומר את האמת. ותו"ת.
ונראה שאפשר לומר שפשוט לגמרא (ויש לדון למה) שדוחה אם הוא מה לי לשקר חזק, כמו מש"כ למעלה, אבל לא דוחה אם הוא מה לי לשקר רגילה. רק דן, אולי, אם הוא חזק או לא, ואם אדם יודע שאין בני אדם רגילים לשלם, ואם מחשב את זה בתוך חשבון שלו מה לטעון.
נראה שאולי, אז, יש לפרש שלא מכוון לומר "מי אמרינן, במצה של חזקה, שנטעון מה לאדם לשקר,” אלא אומר, “מי אמרינן שטועון, ‘במקום חזקה, למה אשקר, שבוודאי אראה כמשקר.’” ותו"ת.
לא נראה כן ממה שבצד שני אומר לשון "לא אמרינן" באמצע. (ואין להקשות כן מצד ראשון, כמש"ג ב"ח.)
* ו.
** גמרא שפא -
כיון שהגענו לזה, לכאורה, אינו פשוט, ויש לומר שתבעו בזמנו. ותחשב.
** במקום חזקה -
לשון דיון גמרא- אם אומרים מה לי לשקר כשיש חזקה, ולא אם אומרים חזקה כשיש מה לי לשקר- משמע שדנים בכוח של מה לי לשקר, ולא בכוח חזקה. ותחשב.
** לא פרעתי -
אם הייתי לומדיש, הייתי דן אם ממש כאומר שלא פרע, או שאינו כטוען שפרע, ואי אפשר עוד לטעון שפרע, שהרי זה יסתור טענתו עכשיו.[fn:4]
* ו:
** גמרא עד תלתין -
נראה לציין למה שאומר גמרא לקמן שלאחר שלשים יום, אדם נחשב יושב העיר. ותו"ת.
** רש"י ובעובי -
לא הבנתי למה צריך להיות בעלייה. באמת, לא הבנתי מהו עובי הכותל כל כך, אבל נראה שהוא הצד הקצר[fn:5], ואז לא הבנתי למה צריך להיות בעלייה. ואולי מקום זה הוא מקום הכניסה, ואז אין בית נגדו אל בעלייה (שכיון שהוא גבוה, אינו מקום הכניסה). ותחשב.
** תוס’ -
גם יש לומר שאם לא קדים, היה טענת שניהם ליתן ממון שווה, ואז היו צריכים לחלק כזה, אבל הוה אמינא שאולי כאן, יש בזה יותר הנאה בין הכל לאם מחלקים, ואז נכוף לעשות כן. קמ"ל של גמרא הוא או שאין יותר הנאה או רק שאין כופים. ותו"ת.
* ז:
** הלכות קבועות -
יש לדון אם אומר שמואל שבזה קובעם, או שאומר ר"נ שבזה קובעם, או שרב נחמן אומר שידע ששמואל קבע אותם או שאחר קבע אותם, או ששמואל אומר שידע שאחר קבע אותם. ותחשב.
** קנה -
יש לדון אם ענין אלו שווה (שהוא שאז מסתבר שישאר שם לזמן הרבה) או לא (וזה מפני שדר שם לזמן, וזה מפני שמסתמא ישאר שם או מפני שקונה בו בית). מסתבר שמה שיהיה שייך הוא שישאר שם, ואז נהנה בטובת העיר.
* ח.
** גמרא פסים -
יש לדון אם אומר שמשנה שלנו הוא לענין פסים או שאומר הזמן שבו חייב בכל.
** שאינו רוצה ליהנות -
ממה שידע מי היה, משמע שלא היו תלמידי חכמים אחרים שעשו כן. אז, קשה למה התיר לכל לבוא וליקח. ויש לדון (אולי היה אחד או שנים יותר שעשו כן). ואולי אי לאו הכי, יבינו שאותו אחד שלקח, אף שכנראה היה עם הארץ היה תלמיד חכם. רצה, אז, לשמור את תלמידו. ותו"ת.
** ק"ק למה
חייב יתומים במה שמהנה אותם, שאומר גמרא בגיטין שפטורים ממה שאין לו קצבה, כעין זה. ואולי שם מיירי רק לענין מצוות, שאין בהם הנאה, שמצוות לאו ליהנות. אז, כאן, שיש הנאה, אפשר לומר שחייבים.
** לאחשבינהו -
יש לדון מה זה אומר:
1. אולי יראו בני אדם שנותנים צדקה, ויחשבו שהם צדיקים חשובים.
2. אולי יראו בני אדם שנותנים צדקה, ויחשבו שהם עשירים חשובים.
* ח:
** גמרא כל המאוחר -
נראה שאפשר לומר שלא רק מביא ראיה מרבי יוחנן, שהוא רק סברתו, אלא ממה שיש קרא לומר כן על שלש ראשונות, שאומר שכך הוא המשך הקרא (לומר הרעה מאוחר). ותו"ת.
** ושקיל מיניה -
יש לדון אם רצה לומר שכפה אותו ליתן אותו סכום ממון זה או שאומר שכפה אותו על ידי נטילת אותו ממון למשכון. נראה שאולי על פי צד שני יש לבאר למה כפה (עיין קושיית תוס’), והוא שלא ממש כפה, אלא רק נטל משכון. ותחשב.
** האי קמצטער -
יש לדון, שלאידך גיסא, זה מנוול. ויש לדון אם מי שמת ברעב גם כן מנוול. גם יש לומר שצער שבחייו יותר קשה. ותו"ת.
** אכפיה -
ע’ בתוס’. ר"א פירש (לשום טעם; ועיין שם) שאיסור לאו של צדקה נפטר כיון שנתן פחות משוה פרוטה. הקשה לי אחד אז למה הוציא ממנו. הערתי לו שבלי תוס’, היה החיוב על פרוטה, ואז בין כך ובין כך קשה. אלא צריך לומר שהחיוב הוא על מנין שהוא טוב. ר"א רק מחדש שיכול להיות אותו סכום פחות מפרוטה, ויוציא ידי חובתו אם הוא מנין טוב ליתן (כפי ממונו). ותחשב.
* ט.
** גמרא מתנה מועטת -
לכאורה, כן מוכרח, שאי לאו הכי לא ירוויח, שאף אם ילך מפתח לפתח, לא יתנו לו. ולא נראה, שהרי אף שאין צריכים ליתן לו, מסתמא יתנו לו מקצתם כיון שמקיימים מצווה. ותחשב.
ונראה שקושייתינו יכול להיות מה שאומר, “אם אתה…,” והוא שהיה מביא ראיה כמש"כ שחייב ליתן לו מתנה מועטת. ותחשב.
** קמצטערא -
יש לציין למחלקת בסנהדרין אם מער גוף או בזיון להיות ערום יותר רע (גבי אשה נסקלת ערומה).
** ואף על פי כן -
רצה לומר, אף שאל חסר עי"ז, נחשב צדקה. מענין מהו ההוה אמינא שצריך לחסר.
** לא אהדר -
אולי לא רצה לגלות שהיה אדם חשוב. גם יש לומר שלא רצה לדבר עמו כיון שגילה שלא חשב שרבא חשוב די. ותו"ת.
** שי"ן -
יש לדון אם רצה לומר שנקרא בsh, שכך נקרא לצד זה, או שנקרא בs, ואומר שלכן יכולים לחלף לsh. ותו"ת.
* ט:
** גמרא אפשר שמה לא ידע
ר"ש קראי שאמר ראב"א הוא שהיה סומא, והיה קשה לו ללמוד תורה שבכתב. ותחשב.
** אלא שרץ -
לא הבנתי, ששם לומד ממה ששרץ נוגע בגדים ומטמא אותם, ובזה אין פירכא של "חיבורים.” אם כן, אין להוכיח ממנו, ששם כולי עלמא יודו שיכולים ללמוד ממנו. ותחשב.
** ואיתי -
יש לדון אם אף תקן מה שאיתיקר עליו תלמודו, וזכר תלמודו. ותחשב.
** אף כופה -
קשה, שמשה אמר שהיה ירא מאף וחימה, ואז אולי רק כיוון לומר שהוא גדול ממשה כמו שראינו גבי אף. ותחשב.
** כדי שלא יקבלו -
משמע שאין אדם מקבל שכר (על כל פנים, כל כך) אם עשה מעשה שצווה לו ה’ (שחשב שזה עני), אם נמצא שהיה מוטעה. ותחשב. וצריך לומר שמקבל שום שכר, שעל כעין זה צריך כפרה (גבי הפרה), ומדת טובה מרובה ממדת פורענות.
* י.
** גמרא מזונותיו -
שם בביצה, ממעט אכילת שבת. אז, משמע שאינו רק אומר ממון שבא לו, שהרי אין מה שאכל בשבת שייך לזה. נמצא שקאי גם על חסרונות. היה אפשר לומר שגמרא כאן מבאר שלא רק נגזר מה יהיה הפרופיט, אלא מה יתרווח ומה יחסר (החילוק הוא שפרופיט לא יאמר אם יבואו לו מאה דולר ויפסיד חמשים או יבוא לו מאה וחמישים ויפסיד מאה. ותו"ת.).
עיין ברש"י כאן שלא משמע כן. ואפשר שגמרא בביצה אומר שנגזר מה יבוא לו, וזה יהיה תלוי קצת במה יצטרך. אומר שמה שיצטרך לנאות שבת ויום טוב אינו נכלל באותו צורך (רצה לומר, כל מה שמוסיף נחשב צורך גמור, ולא רק ממון שמפסיד). ותחשב.
** מחייבתן -
קשה למה אמר בלשון "הן" ולא בלשון "אותך.” ותו"ת.
** למיחסר -
משמע שמה שמפסיד כדי ליקח או כדי לאכול אינו בכלל. ותו"ת.
** רש"י הגוף סובלו -
לולי רש"י היה אפשר לומר שכוונתו הוא שאין רוח מביאו למקום אחר כמו שעושה עם עבים. ותחשב. נראה שרש"י לא הניח כן כיון שאז רוב חפצים כן, ולא היה לו לנקוט רק אדם. ויש לדון, שאולי רק רצה דבר שנשבר מפחד. ותחשב.
** זכה -
עיין במה שפירש. גם יש לומר שרצה לומר שזכה במצוות אחרים (על דרך מה שאמר גמרא בפרק יש נוחלים שמגלגלים זכות על ידי זכאי).
ודע שלכאורה, יש פשט שהוא פשוט מאד, והוא שזכה רצה לומר שנתן ממון לעניים, וקיים מצות צדקה. ותחשב. ונראה שעדיין יש דברים שתלויים בה’, ועל זה מניח רש"י שגמרא מפרש. דברים אלו הם אם בני אדם מהוגנים באים לו, ומתי יוצא הממון מידו שלא בדרך צדקה (שכל מה שקודם ממעט זמן שיכול לתת אותו לצדקה).
** וזו שאלה -
יש לדון אם ברייתא זה אומר כן, ברייתא אחרת אמר כן, או רבי מאיר אמר כן.
** חייא בר רב -
לכאורה, נמצא שיש שני חייא בר רב. אולי זה מבאר למה לפעמים נקרא עם שב רבי (עיין ב"גיטין עם ח"ק"), והוא שאולי אחד נעשה רבי. (כוונתי בזה הוא שקשה לומר שהיה אחד, ונעשה רבי, שהרי רוב דיבוריו היה קודם שנעשה רבי, ומוזר שיהיה כך. עכשיו יש לומר שלא היה לו דיבורים רבים, ורוב דיבורי "חייא בר רב" הם מחייא בר רב אחר. ותו"ת.)
** צדקה -
לכאורה, מוכרח שמציל מכל מיתה, ולא רק ממיתה משונה. ועיין לקמן שמשמע נגד זה (שרק אומר מיתה משונה). ותו"ת.
** ספק מקבלים -
לכאורה, כן הוא אף גבי צדקה, שאולי מי שנותן לו אינו עני (כמה שאומר גמרא שה’ עושה למי שאינו כל כך טוב). ואולי יכול אדם לבדוק ולדעת, ואז לקיים מצווה, אלא שאומר ה’ שינסה שלא יקיימו מצווה, ואז אם לא בודקים, יביא להם עניים שאינם עניים. ותחשב.
** אדרבא -
לא הבנתי איך ינסה להוכיח שה’ מכוון שלא ליתן לעניים צדקה כיון שאומר קרא ליתן לעניים צדקה. ותו"ת.
** מיתה משונה -
ק"ק, שגמרא במקום אחר (גבי מעשה בנשיאת בת רבי עקיבה) אומר שמציל אף ממיתה שאינה משונה.
* י:
** גמרא וכל המייהר -
יש להעיר שבשאר פשטים, היה אומר שהוא רע רק כיון שאינו לשמו. יש לדון למה לא אמר כן כאן. ותחשב. ואולי רק מוסיף לרווחא דמילתא.
** להתגדל -
נמצא, לכאורה, שאין אומרים לעשות מצות שלא לשמה כדי להגיע ללשמה גבי גויים. מעניין שמניחים שיעשו שום מצווה לשמה!
ויש להעיר שרש"י בראש השנה (ד.) משמע שהוא מפני שקורא תגר אם לא קורה לומר שה’ בדאי ושגזל ממונו. יש להעיר שזה לכאורה אינו שייך כאן. ויש לדון אם "להתגדל" אומר שבא לו גדולה או שחושב על עצמו גדולה. אם נאמר כראשון (וכן נראה, שאם לא כן, צ”ב מהו החילוק בין זה לכדי ליהיר)[fn:6], נראה לתרץ. על פי זה, אולי נראה שיש מה שהקשינו בד"ה וכל המתיהיר, והוא ששם הוא כדי לחשוב טוב על עצמו, ואז אין בעיה שאומר כאן שייך.
** ותו לא -
משמע שתלמיד חכם יכול לעמוד שם. אם כן, יש בריה שעומד שם עם הרוגי לוד- כל תלמיד חכם. ותחשב. אולי רק רבי עקיבה, שהיה חכם עד שרצה משה שלו היה נתון התורה, כך. לא נראה, שלא רק אומר רבי עקיבה כאן, אלא רבי עקיבה וחביריו. ותחשב.
** קבלינהו -
קשה למה לא חלקם לגויים בעצמו. ואולי אם לא כבר הלכה לאחד חשב שלא תדאג כל כך אם לא רצו שתתן. ותחשב.
* יא.
גמרא
** מבזבזם -
יש לדון על מה קאי:
1. על הממון, שהיה נותן את כולו, ומבזבז אותו ממון.
2. על האבות (שכן משמע מקריאה פשוטה), ואמר שעשה שכל טירחות שלהם לא היו לכלום.
** הראוי -
יש לדון אם משנה יכול להיות כאותו שיטה, וש"בית דירה" רק רצה לומר דבר הראוי לבית דירה.
** מונבז -
נראה שהיה נקרא כן על שם שבזבז ממון.
** עמד ופרנסה -
יש לדון למה זה נחשב מצווה כל כך גדול, שחייב לעשות כן. ואולי אעפ"כ נחשב גדול. גם יש לומר שאינו חייב ליתן מעצמו כל כך, אף אם הוא פק"נ.
* יא:
** גמרא אכסדרא -
לא הבנתי למה צריך להיות לו דפנות, שאם היה אפשר לו לפרקו בחוץ (שכך היה עושה אם לא היה אכסדרא), בודאי יכול לעשות כן בתוך אכסדרא זה. וצריך ביאור.
** פרץ -
רצה לומר שאם עשה כן, גילה מחילה על זכותו, אבל אם לא עשה כן, גילה שעדיין רוצה בזכותו.
* יב.
** גמרא בית סתום -
מביא ראיה מזה, שמניח שמה שלא יהיה לו דין פתח הוא מפני שמחל. ויש לדון, שמסיפא רואים שממש אין לו דין פתח. אם כן, לכאורה, אין צריכים מחילה. ויש לדון, שאולי אין צריכים מה שנחשב פתח לדיני טומאה כדי להשיג אותם ארבע אמות. ויש לדון, שאולי כיון שהיה לו לפני זמן ארבע אמות עשה לו קנין בחצר קודם חלוקה, ואז צריך מחילה.[fn:7] ויש לומר שמה שאינו פתח הוא גופא מפני שלא עמוד להיפתח. בזה תלוי, לכאורה, אם ימחול, שאם לא יפתח, ימחל. אם כן, דין פתח של סיפא ומחילה תלויים זה בזה.
** חכמים -
נמצא שהיו נביאים שלא היו חכמים.
** רש"י אטו -
עיין במש"כ. ונראה שגם יכולים לומר שפשוט שלא ניתן לחכם שאינו גם כן נביא. אם כן, לא ניתן לחכמים, אלא כבר היו להם. ותו"ת.
* יב:
** גמרא טעם יהיב -
ק"ק למה לא יכול להיות כסומא בארובה אף בזה (שאולי אמר דבר שהיה מסתבר לו, והיה נמצא להיות נכון). ותחשב.
** כי קא פלגו -
נראה שמבאר למה יש נפק"מ לדין שאמר לעיל כיון שצריך ליתן לו אותו שדה שקרוב לשדה שני שלו מדין כופים על מדת סדום. קשה איך רבה ישיב לזה.
* יג.
** גמרא גוד -
ואם תאמר הרי יכול עבד ליקח את עצמו, שכן, לכאורה, עושה לפי בית שמאי. ויש לומר שכיון שלא יכול לשלם באותו זמן לא נחשב שיכול לומר גוד או אגוד, שיש סיבה חזקה שלא לבחור אחד מן הצדדים. ותו"ת
* יג:
** גמרא לית דינא דגוד או אגוד -
לא הבנתי זה כל כך, שלכאורה, גוד או אגוד אומר שאחד נוטל את כולו; אם היו חולקים, היה נקרא "דין חלוקה.” אם כן, כשאמר רבא שאין בו דין גוד או אגוד, אומר שאין אחד נוטל את כולו (או כופה את חברו ליטול את כולו). מה שכל אחד צריך שניהם אינו, לכאורה, שייך לזה. ואולי אין הענין מה ששניהם נצרכים, אלא ששניהם נצרכים לכל אחד, שהם צורך, ולא רק רצון. אז, אין לכפות לאחד לחסר אותו. ויש לדון.
** מדביק -
רש"י מניח שזה אומר שיכול אדם לעשות כן, ולא שאדם צריך לעשות כן (וכן מה שאומר שיטה לקמן שעושה כל אחד בפני עצמו הוא שצריך לעשות כן, ולא שיכול לעשות כן). מקורו, לכאורה, הוא ברייתא לקמן שאומר שיכול לעשותם אחד, וכן מקושיית גמרא לקמן (בע"א) של "הכי קאמר.”
** אחד בפני עצמו -
צריך לבאר למה לא ידביק את כולם. ואולי חוששים שזה יעשה שיהיה יותר קשה לו ללמוד, שצריך להביא את כולו בכל זמן שרוצה. גם יש לומר שיש ספרים שיש להם יותר קדושה, ואין לדבק אותם עם ספרים שאין להם כל כך קדושה. ויש לדון אם זה, באמת, בעיה. גם יש לדון אם כל ספר של תנ"ך יש לו מדרגה חלוקה (שהניחא תורה, יודעים שיש לו יותר קדושה, אבל לכאורה, לא יודעים שיש ספרי נביאים שהם יותר קדושים מספרים אחרים.). ותחשב.
** ארבע שיטים -
לא מפרש כמה מניח בין תורה לנביאים.
** לדידך -
משמע שלא היה ר"נ רבו של רבא (כמו שאומר גמרא ברכות על זה (פרק רביעי)). ועיין בכמה תוס’ שדנים מי הוא ר"נ, שזה שייך.
* יג:
** גמרא מעשה -
מעניין שקורא את זה מעשה, שאין כל כך מעשה בו. ותו"ת.
* יד.
** גמרא דילמא תורה צוה לנו משה -
צריך ביאור למה יעשה כן (למה יכתוב "תורה צוה…" ארבע מאות פעמים).
ונראה שאולי כתב כן כדי שתנוקות ילמדו (אולי היו להם כתבים של תורה צווה שממנו היו מלמדים תינוקות (שלומדים את זה, כמה שכתב תוס’)). ותחשב.
** כתב ר"א -
על"ע שהקשינו למה יכתוב אותו קרא ארבע מאות פעמים. ונראה שלא קרה זה, אלא שאל אותו לו לחדות אותו, ולראות אם היה יכול לומר דבר שיפרש מימרה סתומה שחידש. ויש לדון (שלכאורה, לא אמר פירוש כל כך טוב, שהרי לא אמר דבר שמובן שהיה ר’ אמי עושה.)
ודע שהוא קצת מעניין שיהיו רבנן מנסים לר"ה, שלכאורה, אין זה רק שרב מנסה לתלמיד. ויש לדון.
* יד:
** רש"י הכי קאמר -
רש"י מפרש שאומר סיבה שצריך להתחיל בראש דף. גם יש לומר שבא לומר סיבה שכשמתחיל ספר החדש בראש הכרך אינו צריך שורות להבדיל, והוא שמה שיכול להבדילם ממש (לחותכם) עושה אותם שני ספרים חלוקים. ותחשב.
* יד:
** גמרא רווחא דביני ביני -
לכאורה, אף בלי זה יהיה בעיה, שכלל שאומר גמרא הוא רק בעיגול, אבל כאן, כיון שיש שני עמודים, הוא oval, ואז יהיה יותר גדול.
ונראה אפשר לתרץ על ידי זה מה שהעירו שגמרא מקשה רק מחמת שלא דק לומר שπ הוא 3.1415, ולא רק 3. נראה שאולי לא דק כיון שאף לא דק לומר שהוא oval, ולא circle, ואולי שניהם כמעט מבטלים זה את זה
נראה שגם יש לומר לתרץ קושייה ראשונה שלנו שאולי כשאומר כקיפו, לא רצה לומר היקף של הoval, אלא גודל של circle שיקיף את כולו.[fn:8]
שוב הבנתי שלכאורה, אומר ששש הוא כשהוא על עמוד אחד, אלא שאין עושים אותו על עמוד אחד. עדיין קצת צריך ביאור, שאז יהיה כל אחד יותר רחב מחצי של שש, שהרי יש בכל אחד מהם עמוד. ותו"ת.
** שיצא ממנה דוד -
צריך ביאור למה מביא הא דרבי יוחנן; לכאורה קרא בפירוש אומר שבא ממנה דוד, וקרא בפירוש אומר אחרית של רות. אפשר לומר שכוונתו לומר שראשיתו מזכיר כבר הטובה שיזכיר אחריתו (שאומר שם "רות")[fn:9]. אם כן, זה יתרץ קושיית תוס’ (שאין ראשית של איוב מזכיר אחריתו), אלא שממה שתוס’ לא אומר כן, משמע שחולק.
ויש להעיר שהיה, לכאורה, פורענות אף קודם רות, שהיה רעב בארץ…. ותחשב.
** תחילה -
עיין בפסחים שאומר מזה שהיה הגדול מכולם, ולא שהיה תחילה שבכולם. ותחשב.
** שברי לוחות -
ואם תאמר למה לא אמר שהוא עמודיו. ויש לומר שכבר כתב "עמודיו.” ויש לדון, שהיה אפשר לומר, אולי, שאינם בתוך הארון (כמה שאומר החולק).
** דברי הימים -
ק"ק למה לא מתחילים בזה. ותו"ת.
** רש"י שברי -
מעניין שמניח שהיה תחת הלוחות (ויש לדון למה מניח שהיה תחתיהם, ולא על גביהם. ונראה שהוא פשוט כיון שיש להם פחות קדושה, שהם רק שברים.)
* טו.
** גמרא מסייע ליה לר"ל -
יש להעיר שלכאורה, לא רק לו מסייע, אלא לכל מי שאומר שהיה קודם משה רבינו.
** ישנו -
לכאורה, כיון שהגענו לזה, יש לומר שכן כוונת נביא כשאומר "עוץ" (והוא שאפשר שקושיית גמרא הוא רק איך ישנה משה לומר שם שאינו שם מקומו, כיון שהוא מבלבל אותם, אבל אולי, לאיזה סיבה, לא ידקדק נביא. ויש לדון.)
* טו:
** גמרא עיקר -
צריך ביאור למה לא מונה יונה. ונראה שאולי ה’ ציווה אותו לעשות כן כדי שיראו בני ישראל וישובו. ואולי ניבא פעמים אחרים, אבל אינם נכתבים בתנ"ך, והיו ידועים בקבלה. ותחשב.
** לבר מיש אומרים -
יש להעיר שאז נמצא שהיו בנות יעקב נושאים גויים.
** שובי -
א.מ.וו. תמה לי איך עושים שירה מקרא זה שמדבר בזנות.[fn:10] ונראה שהוא בשבח בני ישראל, שכל הגויים רוצים שיעזבו את ה’ ותורתו לזנות בהם (וזה גופא שבח, ועוד שבני ישראל לא יוצאים).
** לעכו"ם -
יש לדון אם רצה לומר שנבואתם נאמר לאומות או שהיה לטובת אומות. עיין בדיבור לעיל, שהנחנו כצד שני. ותחשב.
** גדול הנאמר -
זה, לכאורה, אפשר רק אם נאמר שהיה טוב (עיין בגמרא לעיל שאמר צד שה’ רק ביקש לטורדו מן העולם).
** ויבקשו -
קשה, אז, למה בחר את אסתר למלכה. ויש לומר שהיו דברים שרצה חוץ מיופי. גם יש לומר שנס היה, ולא בחר את הכי יפה. גם יש לומר ששום אונס קרה לאלו.
** לא בא לעולם אלא -
ואם תאמר קודם שבא, איזה שכר יש לו. ואולי זהו מקור למושג של גלגול. ועוד יש לומר שעשה מעשיו כאילו רק בא לעולם לקבל שכר, ולא לעבוד את ה’, שהיה רשע. ותו"ת.
עדיין צריך ביאור- וזה קשה בין בך ובין כך- מה שאומר שקורא אותו חסיד.
** עזים… זאבים -
יש לציין לגמרא תענית שאומר מעשה בעזים שהרגו דובים, ורש"י מפרש שהרגו זאבים. עיין שם. ואולי רש"י מניח שנקט כן מחמת שזכר הוא לזה, ואז צריך להיות זאבים שיהרגו, ולא דובים.Queen of Sheba לא טועה.
** שטתי -
יש לדון אם אומר בsh, והוא לעוף, או בs, שהוא לעשות מעשה של שטן. מלשון הפסוק (שמזכיר הראשון), נראה כראשון.
** רש"י אימא -
לכאורה, יש סיבה גדולה לומר שלא הוכפלו, והוא שאם כן, נטל פי ארבע, שנטל פי שנים של טוב, ונטל אותם לפי שנים של הזמן. ותחשב.
** תוס’ בלעם ואביו -
עיין במה שאומר. יש להעיר שגמרא בסנהדרין דורש "בן בעור" להיות קאי על בלעם (כן אני חושב). ותחשב. ודע שיש קרא אחר שדורש לומר שאביו היה בנו בנביאות. זה היה יכול להיות מקוד לזה שאומר שהיה נביא.
* טז.
** גמרא מינשי ליה -
אף אם היה איוב ישראל, זה היה רע, שלא היה אב של כל בני ישראל כמו אברהם, ולא היה נותן זכות לכל בני ישראל. גם יש לומר שאז כל אחד מהם לא יהיו כל כך חשובים, שמה שאחר השיג כל כך יעשה שאין האחד כל כך חשוב (ואף אם היה איוב יותר גדול, חלק ממה שנעשה יהיה כבר נעשה על ידי אחר, ואז היה נתמעט).
** הוא שטן -
לא רצה לומר ששטן הוא מלאך המוות ויצר הרע, אלא מי שהיה באותו מעשה הוא שטן ומלאך המוות ויצר הרע, שהרי מביא ראיה ש"הוא שטן.” ותו"ת.
** שני נימים -
עיין בגמרא נדה שאומר "בראשו של אדם.” זה יותר מדוייק כמו שמפרש שם. ואולי לכן שם מדקדק לומר כן. ויש לדון, שזה לפני אותו תירוץ שעושה אותו מדוקדק. ותחשב.
** לגומא -
קשה איך יידע כן איוב, שהרי יש בני אדם שהם סומים. ואולי רק רל שטעה בטעות יותר גדול. ק"ק מה לנו בזה.
** מכאן שכפר -
רבא לשיטתו שאומר שהיה איוב כופר.
* טז:
** גמרא אחרים -
לזה, לא אמר שהשיג את הכל, ואז כשדורש גמרא לקמן כל מיני טובות לאברהם יצחק ויעקב כיון שזכו לכל, אין זה כאחרים. ואולי אין מקרא יוצא מידי פשוטו, ואף לאחרים זכה לכל.
באמת, צריך ביאור קצת למה צריך גמרא לדרוש את זה (אלא אם כן נאמר ששואל איך יזכה אדם לכל טוב, ובא לבאר. אם כן, לכאורה, אם אחרים משיב לזה, צריך לומר שתשובתו הוא שלא זכה לכל, אלא למי ששמו טוב.). אם כן, אין לומר כמש"כ.[fn:11]
** נשר -
נראה שאולי יש שייכות בין זה למש"א קרא, “על כנפי נשרים.” ותחשב.
** ימימה -
יש לדון איך ידעו כן כשנולדה. ואולי אמר כן ברוה"ק. גם יש לומר שנתנו אותם שמות אלו אחר שגדלו. גם יש לומר שהיו יכולים לדעת בלידתן. ותו"ת.
** שלא היתה -
מעניין שנחשב ברכה מה שלא קיים מצווה. ויש לדון בזה, שאולי כיון שבעל את אשתו בכל זמן, קיים מצות פרו ורבו (כך אומרים אחרונים).
** דרדקי -
יש להעיר שמצינו לשון זה נאמר בדרך כלל כשניער גדול למצוא תלמידיו אומרים דבר (עיין בשבת קמה:). וזה מובן, שלכאורה, בלי זה, לא היו מדברים לרבם בלי כל כך הכנה. ותחשב.
** דרדקי -
היה אפשר לבאר שאמר כן על דרך סגי נהור, שמצינו שהיו לרבא תלמידים זקנים (עיין בגיטין עג, שקורא לתלמידיו אווזים לבנים), אלא שיש להעיר שמזה גופא מצינו שהיו לו תלמידים שלא היה קורא בלשון זה. ותו"ת.
** ישמעאל -
קשה למה ישמעאל הלך בתר יצחק, שהרי "במקום שבעלי תשובה עומדים….” (הפשטות הוא לתרץ שאף שעשה תשובה, לא עשה תשובה שלמה, שלא עשה על הכל, או לא עשה מאהבה ממש.) ויש לומר שחלק מתשובתו היה לכבד את יצחק. ויש לדון איך היה יצחק יכול לקבל כבוד זה. ואפשר שרבי יוחנן לשיטתו, שאומר שם (ברכות סוף פרק חמישי) שצדיק יותר טוב מבעל תשובה, ולא סובר כרבי אבהו ש"במקום….” אז, צ"ל שר"א ידחוק כמה שאומר גמרא (שמנה אותם בחכמה), אלא שלפעמים אומר קרא כן, ולפעמים לא מונה אותם כן. ודחוק. ותחשב.
** רביה -
יש לציין לגמרא פרק מי שמת שאומר שלידת בת הוא סימן טוב ללידת בנים.
** רש"י בביעי -
עיין במה שפירש. גם יש לומר להיפך שהוא גלגל (כיון שהוא גלגל קצת), ומה שאין לו פה לא מהני, שאינו ממין שבדרך כלל יש לו פה (כמו עדשים, שהם ממיני קטניות), ואז לא יהיה ניכר. ותחשב.
* יז.
** גמרא לא שלט -
מעניין שאומר לשון עבר, שגמרא בשבת אומר (ואינו כל כך פשוט שם, שלכאורה, חולקים בזה) שרמה הוא רק שעה אחת לפני ביאת משיח. ואולי גמרא מחכה שיבוא משיח באותו זמן, ואז אפשר שכבר שלט בהם. ויש לדון, שלא בא אליהו כבר.
** מעין עוה"ב -
קשה למה לא מנה איוב, שאף לאיוב הטעים. שוב ראיתי לתוס’.
** על פי ה’ -
מעניין, שבדרך כלל, לא מפרש למה אומר גזרה שווה, ולא אומר אותו בהדיא. ונראה שהתרצן שאל כן (כמו שמצאנו בכמה מקומות (עיין בר"ן נדרים (עא.)).)
** או סד -
יש גורסים "וסד.” ואם תאמר, אם כן, לערבו בבבא ראשונה. ויש לומר כמו שאומר גמרא בתחילת פרק ראשון של קידושין, ששמע זה, ורק אחר כך שמע זה. ועיין שם. גם יש לומר שבאלו סדים הבור שעושה, ובאלו סדים הכותל שבין החצרות. גם עיין ברש"י שמשמע ש"כותלים" של רישא רצה לומר כותלי בור. אם כן, יש חילוק גדול כשאין כותל (או שיש חילוק גדול במה שהם רעים לכתלים (עיין בגמרא לקמן).)
** ואת הסיד… סד בסיד -
כמובן, צריך ביאור. ואולי כשהסיד על הכותל ממש, מחזקו, ואינו בעיה. ותחשב.
** רש"י כדאמרן -
מטיפה- חושב אני שמצאתי (אולי עיין בגמרא ערכים בדיון של מי מת ראשון- עובר או אשה) שאינו ממית על ידי טיפתו כשאדם נהרג. אם כן, קשה למה יהיה בו רמה. ותחשב.
** בכל -
לא חסרו- קשה, שאף בלי זה נאמר כן, כמו שאמרנו במה שאין להם יצר הרע.
* יז:
** גמרא הא קמ"ל -
לא הבנתי, שאולי צריך להרחיק שלש מכותלי בור חברו, וכותלי בור הם פחות משלש, וצריך להרחיק בין כתלים לכתלים. יש לומר שלא מסתבר כן. קשה, שאז אין צריך לומר כתלים כלל, שיש לדעת אותו מעיקר דין של משנה. ויש לומר שאז הייתי אומר שבורו הוא בשום מקום, ומה שמפריש ביניהם הוא לכתלים. ותחשב. שוב ראיתי בגמרא.
** מכותל בורו -
לא הבנתי שקלא וטריא של גמרא זה, שאף שלרבא לא יכול לסמוך, לא ידוע שיעור עד שאומר משנה את דינו. אם לא היה כותל בורו, היו חולקים השלש ביניהם, והיה מרחיק אמה וחצי. אז, היה משנה מובן. ואולי מקשה, אז, למה לא אמר דין על הראשון. וקשה, שזה קשה אף לתירוץ שאומר גמרא.
** שבאו לחפור -
קשה למה אי אפשר לומר שמרחיק שש (שלש מכותל בורו). ואולי לא מסתבר לגמרא שצריך להרחיק מכותלי בור חברו כשנתן אותו כותל ברשותו. ויש לדון. ועיין בביאור רש"י. וצריך ביאור מה אומר, שלא רק זה מלמד אותנו, אלא מלמד דין מקח וממכר (מה נכלל ב"בור"). ותחשב.
** מבורו של חברו -
קשה למה לא אומר שיש יותר נפקא מינה ביניהם, והוא שאילו אמר כך, רק היה צריך להרחיק בין הבור עצמו לבור עצמו, ולא בין בור עצמו לכותל בור. ותחשב. משמע שאף לשון זה היה משמע הרחקה מן הכותל. אם כן, מש"כ בד"ה הא קמ"ל לא מהני, שאף אי לא תני כותל, היה הדין ידוע. ותחשב.
** מבורו -
קשה, שאולי אז הוה אמינא שמרחיק מן הבור עצמו (מפני שכתלים הם אמה וחצי).
* יט.
** גמרא לא משכחת -
בביאור המחלקת, לא נראה שחולקים אם יש שום היזק, שיכולים לראות אם יש. נראה שחולקים כזה:
יש מעט היזק, אבל לא כל כך. יש לודן למה צריך מזיק להרחיק את עצמו:
1. מפני שאינו פייר שיזיק.
2. מפני שאסור להזיק.
נראה שלצד ראשון, יהיה יותר חייב על מי שמזיק יותר. כך אומרים רבנן. לשני, אולי יהיה שווה, שעל שניהם אמר תורה איסור אחת. כך סבר ר"י.
** רש"י לא משכחת -
צריך ביאור למה רש"י מפרש כל זה כאן, שלכאורה, גמרא אמר את כולו לעיל (בע"ב). ותחשב.
** בהדיא -
רק שנה מה שמשנה אינו אף בנדיין, אבל לא שנה שיעור נדיין.
** או סד -
נראה שדן בראשון, ומניח ששני אומר "או" או להיפך. ודע שבמשנה שלנו, אין מי שגורם "או" בראשון. ותו"ת.
** ותיפוק… מיא -
מניח שקאי על זרעים. לולי רש"י, היה אפשר לומר שקאי על מחרישה, ומקשה שאילנות צריכים מים. ונראה שכיון שגדילים על רב מים (עיין בראש השנה, ואולי לא כתבתי אותו נכון), פשוט שמטר די להם. ותחשב.
* יט:
** גמרא רקיק דמאיס -
נראה לבאר למה רקיקי יותר מאיס מעבה בשני אופנים:
1. יש לחלוח בשניהם רק בחוץ. אז, ברקיק, שאין כל כך בפנים, כמעט רובו לחלוח, ומאוס. בעבה, שיש חלק גדול ממנו בפנים, רובו אינו לחלוח, ואינו מאוס.
2. אולי לא יאכל אדם שום דבר מלוכלך, אלא יחתוך אותו מקום. זה אפשר רק בעבה ולא ברקיק, שברקיק לא ישאר כלום אחר שחתך השפות. ותחשב.
** בכדי שלא יזיק -
לכאורה, לעולם כן הוא השיעור. ואולי ר"ל שהוא בכדי שלא יזיק באותו מעשה עצמו, ולא שיחלש אותו, ולאחר זמן יזיק, שזה לא קורה. ותחשב. ואולי היה ידוע אותו שיעור. ואם תאמר למה כתבו כלל. ואולי תנא שני הוסיפו כיון ששכחו. ותחשב.
** רקיק -
זה שייך להכא כיון שיביא דין אגבו דין זרעים קרוב לכותל לקמן.
* כ.
** גמרא בכחושה -
אם הוא כל כך אינו ראוי, קשה למה יקשרנו. ואולי אינו מפני שרוצה אותו, אלא מפני שאינו רוצה אותו, והוא שהיה מזיק לו, ועל ידי זה ריחקו. גם יש לומר שעשה מצודה שיקשר בהמה שבא לו, וקשר זה, שבא ראשון, אף שלא היה רוצה בו הצייד (שהרי המצודה לא חש לזה). גם יש לומר שנתחכש אחר שקשרו. מעניין שאז לא יוכל לצאת. גם יש לומר שרצה מכסה לחלון.
* כ:
** גמרא לא אמרו -
משמע מר"ש שלא רק חולק לומר שפטור מלשלם, אלא שאומר שרק לזה נאמרו שיעורים אלו, ואינו אסור לתת יותר קרוב[fn:12]. ותחשב.
** מהו -
גמרא שואל מה נחשב תחילת אוצר, אבל יש לשאול גם לאידך גיסא, מה שנחשב שכבר יש רפת. ותחשב.
** אי הכי ליתני -
נראה, אולי, שאביי סבר שתינוקות יותר נשמעים, ואזבחצר אחרת, רק ישמע תנוק. אז, מה שאמר שווה לאומר "חצר אחרת.”
** רש"י תמרי -
עיין במה שמפרש. ויש לדון למה לא יהיה התחלה:
1. לא ימלא את כולו מזה. אז, חלק חשוב ממנו חסר בכולו (והוא חלק של תבואה).
2. לא התחיל כבר מה שינזק.
לולי רש"י, היה אפשר לומר שגמרא שואל אם אלו ניזקים (ועל אוצר כזה קאי משנה) או לא. נראה שלרש"י, סמיכות גמרא יותר טוב, שהרי היה שואל מה נחשב התחלה.
* כא.
** גמרא ברם -
לכאורה, רצה לומר שלא היה כל כך טוב, שקנה כהונה בממון, אבל אף על פי כן, זכור לטוב כיון/ במה שעשה כך….
** שבתחילה -
ק"ק למה אומר שהיה נשתכח, שהרי רק היתומים היו שוכחים. ויש לומר שאז לא היה רבי עקיבה לומר, שכבר היה איש, ואז לא היו לו תלמידיו, ואז היה נשתכח. גם יש לומר שאז בחורבן הבית, שלא היו רוב בנים עם אב שלהם, היה נשתכח. ותחשב.
** רש"י דייק -
מרש"י משמע שדייק לא רצה לומר דייק כשלומד, אלא כשמלמד. ותו"ת. ויש לדון אם אף גרס כן, ולא אומר שהוא תלמיד חכם ביותר, אלא שיכול ללמד יותר דברים. ותחשב.
* כא:
** גמרא דלא הדר -
ק"ק, שרבא הוא האומר שטעות ממילא יצא, ואז, לכאורה, הדר. ותחשב.
** שויסקי -
לא מבאר גמרא מהו חילוק זה. וצריך ביאור.
* כב.
** גמרא דאנינא דעתאי -
לכאורה, מה שאין חזקה הוא שמוכרח שלא התיר הבעל את זה, שמי יעשה שיכול אדם להזיק אותו. ואם כן, לכאורה, צריך להוכיח שאנינא דעתו, שאם לא כן, לא נניח כן. ויש לדון, שאולי חבירו הוא המוציא את החפץ. ותחשב. ועיין בפרק שלישי, שלכאורה, חולקים רבא ור"נ מי הוא המוציא. וע"ש.
** פיל שבלע -
יש להעיר שבמנחות משמע שזה שאלה קשה. וע"ש.
** רבא -
מעניין שהיה יכול לחשוב שזה רבא, שר"א היה זקן (עיין במגילה, אני חושב), ורבא מת בארבעים. וצריך לומר שלא ידע עליו כלום.
** ענשיה -
מעניין לומר לשון זה על ר"נ, שלכאורה, לא ענש אותו, אלא גרם מיתתו. ותחשב.
* כג.
** גמרא מאן פייס -
צריך ביאור מי הוא אותו שמוחל (למס’ גמרא). ותחשב.
** מאן פייס -
קשה, שעדיין אפשר ששכנס לתוך שלו.
* כג:
** גמרא ואף על גב דחד -
קשה למה משנה מזכיר רק קורבה, ולא רוה. ויש לדון, שאולי דין רוב כבר הוזכר כמה פעמים במשניות. ואולי בדרך כלל הם שווים. ואם תאמר אם כן נוכיח מאיזה מהם חסר עוף אחת. ואולי רק בדרך כלל הם מנין הדומה.
** קרוב לזה -
יש לדון למה צריך לומר כן לשניהם, שהרי שניהם שווים. ונראה שמזה דייק גמרא בקושייתו. ותו"ת.
* כד.
** גמרא הדר ביה -
יש לדון מה אומר:
1. עכשיו סובר שיש להביא ראיה מרוב ומצוי לרוב שאינו מצוי.
2. עכשיו סובר שיש חידוש בדין רוב ומצוי. ולא נראה שאף לעיל לא אמר שאין חידוש, אלא שלא שייך לנדון שלנו, שאינו מוכיח דינו של ר"ח.
** דתני -
לא הבנתי למה כותב כאן דל"ת, שלא מוכיח ממנו, לכאורה. ותחשב.
* כד:
** גמרא קודם -
משמע שיש לו זכות, בעצם, לומר כן (וקצת יש לדון למה), ומה שאינו יכול הוא רק תקנה. קשה, שגמרא לקמן לא משמע כן, שמבאר למה אי אפשר ליטול. ונראה שיש תקנה שלא יכול לתבוע קודם קציצה, ואחר קציצה, אי אפשר לתבוע מפני סיבה זו.
** מאי טעמא… ותיפוק ליה -
נראה שהתרצן שאל כאן. ותו"ת.
* כה.
** גמרא דאינו עושה כלל -
לכאורה, יש עוד צד, והוא שלא מודה רבי עקיבה למוזג של חמישים אמה כלל, ובשאר צדדים סומך ממש, ובאותו צד, לא עושה כלל. ותו"ת.
** דמורו -
זה מעניין. נמצא שלא חש שילמדו בני ישראל לעשות כן, שהרי אין בעיה אם יעשו כן. רק חשש שגויים ילמדו. לכאורה, הסיבה לזה הוא שהוא, אז, חלק למה שעושים בעבודתם (אף שהיו עובדים אף בלי זה). וצריך ביאור. גם קצת צריך ביאור למה ילמדו ממנו, שהוא מתפלל לה’ אחר. ותו"ת.
שוב באר לי א.מ. ו. שר"ל שהם מורים כן לע"ז שלהם, ואז לא היה רוצה לראות כמותם.
** אילמלא בן נץ -
יש להעיר שיש דמיון ממש לזה בGreek mythology; והוא מוזר. ותו"ת.
* כה:
** גמרא צפון -
קשה למה לא נראה. ויש לדון אם הוא כל כך קל לראות. גם יש לומר שהוא קצת למזרח גם כן (כמו שמצאנו שא"י נקרא מערבא), ואז מחדש מזה שנחשב לצפון, אף שהוא לצפון ולדרום. ויש לדון למה (ואולי הוא יותר לצפון מלמזרח, או שרובו של א"י לדרום מלמערב, או שעיקרו שם. ותחשב. גם צריך ביאור, אז, למה נקרא מערבא. ותחשב.)
* כו.
** רש"י שכחת -
לכאורה, רצה לומר ש"שכחת" היה שמו, ולא שברי היה שמו, שהיה בן של ר"ח (כן אומר רשב"ם לקמן). ואולי רש"י חולק. ויש לדון למה יחלוק.
** שפעמים -
לא הבנתי למה זה רק לר"א. ותחשב.
** אילני לאילני -
גם יש לומר שזה רק גפנים לשום דבר אחר, אבל לא דבר אחר לגפנים.
** מעמיק שלשה -
קשה למה יביא זה, ולא משנה של בור. ואולי הביא תחילת משנה, וסבר שיבין בשאר.
* כז.
** גמרא לא דק -
יש להעיר שיש קולא היוצא מזה,, שיש נפק"מ סותרות, שיש פטור ביכורים, ואיסור הקדש. ותחשב.
* כז:
** גמרא דאי ס"ד -
קשה, שאולי רק לא חושש לזה. ותחשב.
* כח:
** רש"י שאין עמה -
לכאורה, רש"י סותר את עצמו, שבתחילה אומר שצריך לומר שלא אמר אדם דבר מעולם, אבל אם לא אמר כלום (ואז אין כל כך ריעותא, לכאורה, שלא טען בלי טענה טובה), יש בו טענה, ושוב אומר שהוא כל זמן שלא אמר אתה מכרתו לי. ויש לדון. ונראה שאולי בא סיפא לומר שהוא מקום שאמר שהוא שלו כיון שלא מחה, ורק אם לא גם כן אמר שחבירו נתן לו, שהוה אמינא שאף אם אמר שמכר לו, אמר שני טענות, ואחד אינו טענה, ואז הוא חזקה בלי טענה. מחדש או שמניחים שזה אינו טענה, אלא ראיה שאמר, או שכיון שאמר טענה אחת, אף שאמר עוד טענה שאינו טענה, יש לו חזקה. וצריך לחשוב על כל זה.
ועיין לקמן בפרק בציורים שאומרים לחזקה שאין עמה טענה (כמו אם אומר שקנה מאחר, ולא אמר שקנה אחר ממרי קמא), שלכאורה מוכיחים שאין צריך לומר "לא אמר לי אדם דבר מעולם" כדי להיות חזקה שאין עמה טענה. ותו"ת.
* כט:
** רש"י עיטרא -
שלא בשביל כך- קשה, שנוכיח שלכן עשו השטר והחלוקה כך. וצריך ביאור.
* ל:
** גמרא אין לך מחאה -
יש לדון מה אומר:
1. אולי אומר שהמוכר מחה כשמכר אותו, שעשה דבר לגלות שהוא הבעל.
2. אולי אומר שהלוקח (שהוא הבעל החדש) עשה דבר לגלות שהוא הבעל ושיוציא את השדה, שלקח את השדה, ולא היה עושה כן אם לא שכיוון להנות ממנו. ותחשב.
* לב.
** גמרא לזילותא -
קשה למה צריך לדון בתנאים סתומים אלו, ולא בתנאים שהם יותר בפירוש בקידושין (מב.).
** רש"י ואחתיניה -
ייתור לשון שאינו צריך- הערנו שרגיל רשב"ם לשמש בלשון זה שהוא גופא ייתור לשון שאינו צריך (שרק צריך לומר אחד מהם). ותו"ת.
* לג.
** רש"י א"ל -
שמוכר לצורך הוצאתו- אף בלי זה, היה קל לתרץ שאין הכרח שכאן מוכרים (שיש לומר שרק משלמים מן הממון של יתומים גופא), אלא שרש"י אומר מה שסובר להיות קושטא דמילתא.
* לד:
** רש"י תפסינן -
לרש"י, שני הדיונים תלויים זה בזה. קשה, אז, למה גמרא מביאם לשני מחלוקתים. ותחשב.
** זה אומר -
אם כן, לכאורה, ילך לשני, שאז רואים שחזר בו. ויש לומר שאי אפשר לחזור בו (ורק אפשר לעשות שקנין אחר גם כן יחול) אף שיחול הקנין לאחר זמן. ויש לדון אם זה אפשר. גם צריך ביאור אז מה עושים שומא. ויותר נראה שכוונתו בסוף היום הוא המהני, ודנים מהו כוונתו אז. ויש לדון למה נניח ששינה ממה שהיה באמצע היום, כשנתן שטר לשני. ותחשב.
** אלא -
מדיליף אביי- ע"ל שדן רש"י אם ממש לומדים ממנו. אפשר שכאן אומר כצד שני, ואפשר שמה שאומר מהני אף לצד ראשון, והוא שדימו זה לזה. ועדיין לשונו משמע כצד שני.
** וכל דאלים -
יש לדון מה אם זה הביא ראיות, וזה יותר חזק. ונראה שהכל תלוי במי חוטפו, וענין ראיות הוא שהביא ראיות עד שהpublic opinion אומר כמותו, ואז חברו מניח לו ליקח אותו. ותו"ת.
** לאו שמיה גזלן -
היה אפשר לומר שממש לאו שמו גזלן, וכשאפשר להיות של שניהם, אין מי שחטפו נחשב גזלן, שלא היה שום אחד יכול ליקח אותו, ואז לא הפסיד שום אחד (או שלא היה של שום אחד, שיחס של כל אחד כחוש כיון שאי אפשר לו ליקח אותו). ותחשב.
** ומאי לא שמיה -
איירי נמי ר"ח- לכאורה, היה אפשר לומר שמיירי באותו ציור שאומרים נהרדעי שמיירי ר"ח, שלכאורה, אף כאן, נאמר אותו דין, והוא שאי אפשר לשלם, שלא ידע של מי הוא לשלם. ותחשב.
** דלי -
ומדידיה- משמע שמה שהוא מסתבר שנתן משלו הוא חלק מן ההוכחה. אז, לא נראה שהוא שלא היה אדם חציף ליתן לאדם דבר שהוא שלו כאילו הוא מתנה, שאז הענין הוא שהוא של המקבל, ולא שאינו של הנותן. אז, יש לומר שהוא שאין אדם נותן מתנה מדבר שאינו שלו כיון שמחזיק לעצמו טוב בלי חסרון. לא נראה, שלא חש לגזול חפץ; יחוש לגנוב דעת. ותחשב. ואולי לא יכשיל בני אדם.
** ישראל -
דאיהו הוא דאפסיד אנפשיה- קשה מה לנו בזה, שאף בלי זה, הרי אין לו טענה, ואז אין סיבה שיהיה שלו. ותחשב.
* לו.
** גמרא משלמי -
זה בא ממילת שלם, ולא ממילת תשלומים, ואומר שגומרו מיד ליד, ונותן ליד הבעלים עצמם. קצת קשה, אז, למה לא אמר שכן גם כן מתחיל (ובפרט שהתחלתו בא ראשון, ואז היה לו לנוקטו ראשון). ותחשב. ואולי יותר מחודש שמשלמי מיד ליד, שאף הרועה, שלא רוצה כל כך במה שלא יהיו אבודים[fn:13], משלם אותו מיד ליד. ותו"ת.
** שביעית -
יש להעיר שלכאורה, זה יותר פשוט משאר ציורים, שאין שום מעשה בעל באכילתו כיון שמותר לכל (מה שאין כן בשאר, שהם, לכאורה, גזל). ותחשב.
** רש"י לדידי -
זה מעניין, שנמצא שרש"י סובר שמה שאינו מהימן בדרך כלל הוא שאין לדעת שיש מגו. ק"ק למה לא אמר שאף שיש מגו, אין שום טענה כלל, שלא אמר שקנאו גוי. ותחשב. ואולי זה פשוט מטענתו, שבוודאי חושב כן, אבל רק אם אומר כן יודעים שחושב עליו די לחשוב על עוד טענה (זקנה אותו מישראל עצמו).
** האי מאן -
דלא אחזיק- משמע שמה שלא מהני הוא מפני שלא החזיק כמו שבני אדם מחזיקים, ואל מפני שנטל דבר שהיה עומד להיות נאכל. זה מעניין. ועיין לקמן גבי ערלה, שמשמע שהוא מפני שלא איכפת לבעל בפירות של ערלה, ולא מפני שלא החזיק כמו שבני אדם מחזיקים.[fn:14]
** הגודרות -
אתה הכניסתו- קשה למה לא נאמר על זה חזקת כל מה, שהניחא במה שאמר שאולי בא לרשותו, יש לומר שיש חזקת כל מה רק על מה שאדם מכניס לרשותו, ולא על מה שמעכב ברשותו, אבל כאן אי אפשר לומר כן. ויש לומר שכיון שהיה אפשר ליכנס לרשותו, אין אדם מעכב את עצמו מלהכניסו. ותחשב.
* לו:
** גמרא גדולי הדור -
עיין בסוף פרק שלשי של פסחים, ששם אומר שאין גדולי הדור התלמידי חכמים, אלא הצדיקים. לכאורה, ר"א כאן משמש עם אותו מילה במשמעות חלוקה. ותו"ת.
** וכל גדולי -
יש לדון אם כוונתו לומר כל אותם גדולי הדור של רב אשי (ושמע מהם או מרב אשי) או של דור אחר (יש לדון אם היה בדורו של רב אשי. גם אפשר שאומר דורו של רב אחא).
** חכמים -
ואם תאמר אם חכמים הם במשנה (עיין במחלקת רש"י וראשונים בתחילת הפרק), קשה מה בא לחדש. ונראה שלא בא לחדש שחכמים חולקים, אלא מה סוברים חכמים. קשה, שלשונו לא משמע כל כך כן, שהיה לו לומר, “חכמים סוברים ש…,” ולא ש"כן הוא שיטת רבי ישמעאל….”
** מיום ליום למעוטי מאי -
קשה למה לא לומדים ממה שסוברים ששלש חדשים לא מהני. ואולי סוברים שצריך, לשום טעם, המשך של שלש שנים, ובו מעשה בעלות כמו ניר. ותו"ת.
** מיום ליום -
וא"ת אולי בא למעט מפוזרים או מקוטעות כמו שאומר לעיל. ויש לומר שאף ר"י ור"ע מודים לזה, ולא היה אומר את זה ברבנן. ויש לדון, שעדיין יכול להיות שממעט מקוטעות, שר"י ור"ע סובר שיכול להיות מקוטעות. ואולי רצה לומר כיון שסוברים שצ"ל זמן שאומר כולו, ולא אותו מקוטע, כך יהיה ברבנן, ולא נצטרך לפרש בהם יותר מבר"י. ותחשב.
* לז.
** רש"י ה"מ -
לא אסיק מוכר אדעתיה- נמצא שרש"י סובר שמה שמוכר אדם בעיין יפה אינו שרוצה להטיב ללוקח, או שרוצה שיקנה ממנו, אלא מפני ששכח להשאיר לעצמו. ותחשב.
* לז:
** האי מישרא -
מה שאומר רש"י כאן- שלפעמים יקשו אמרואים רק כדי לחלוק- מעניין.
* לח.
** גמרא ואי כורכמא -
יש להעיר שרב אשי מקשה כעין זה לעיל. אולי שמע ממ"ק, ושוב הקשה אותו. לא נראה כן, שכבר אמר תשובה. אלא  נראה שרב אשי שאל, שמע תירוץ, ושוב שאל מ"ק לו, ואמר התירוץ ששמע. ותחשב על זה.
** רש"י לחזקה -
מה שאומר שהיה לו ליזהר בשטרו, ולא רק אמר שאז אין ראיה ממה שלא מחה משמע שאין חזקה מחמת הראיה. תחשב, אז, מהו. עוד יש להעיר שלקמן (ד"ה לעולם) רש"י אומר שאז אין ראיה.
** אמר רבי יהודה -
לא חלקו- היה אפשר לומר שהם חלוקים, וכשאמרו שלש שנים, אמרו רק כדי לחזק שנה ולילך שני שנים, ואז אמרוהו ביהודה וגליל (אולי מפני שכן מצוי או מפני שזה מקסימום[fn:15]), ואז, אם ידוע להיות במקום קרוב, חזקה בפחות. ותחשב.
ודע שיש אחרונים, חושב אני, שאומרים שכיון שחזקה הוא, בעצם, ראיה לא עשו בו לא פלוג. לכאורה, שיטת רש"י בביאור רבי יהודה מוכרח נגד זה, שלכאורה, כל זה לא פלוג. ותחשב.
* לח:
** רש"י אין מחזיקים -
רבי יהודה- לכאורה, היה אפשר לומר שרבי יהודה סבר שצריך לבוא כיון שמיירי במקום שאין השיירות מצויות. ותחשב.
** מחזיקים -
לאו דוקא- יש להעיר שאם נאמר שיש חזקה, נמצא שמאמינים שלא חטף אותו. אם כן, אין לומר שהוא יותר מצוי לקרות כיון שקל לגזול אותו, שהרי מניחים שאין זה מצב שהיה גזול. ותחשב.
** כאן בבורח -
גואל הדם- נמצא שלכאורה, מיירי בבורח מחמת בית דין. ויש לדון, שאולי אף לגויים יש מושג של גואל הדם, ובזה מיירי. ותחשב.
** היכי דמי מחאה -
יש לדון אם אמר לשון שבין שניהם (אמר שמחזיק באוות קרקע בגזלנות, ולא אמר שיקח ממנו, או להיפך). ותחשב.
* לט.
** גמרא עצה טובה קמ"ל -
בדרך כלל, כשאומר גמרא זה, כוונתו לומר שאמר לנו משנה דבר להראות לנו דבר שהוא עצה טובה. כאן, אומר שתקנו כן מפני שכן הוא דבר המסתבר לעשות, ועצה טובה לעשות כן[fn:16]. ותחשב.
* לט:
** רש"י ומ"ד -
ולכך תקנו- היה אפשר לומר שצריך שנאמר, אבל לא שנאמר כל כך. כיון שלא נאמר כל כך, יש לחוש שלא נאמר די להיות חזקה. ותו"ת.
** אם מחמת -
הוחזק כפרן- קשה, שהוחזק כן מהודאתו, ונאמר מגו. ותחשב.
* מ.
** גמרא הודאה -
לא הבנתי את זה, שהחוב הוא, לכאורה, רק במה שנוכיח האמת נגד שקר שאומר[fn:17], ואז למה לא יכתבו. אפשר שאם כותבים, לא יודה. ויש לדון, שלכאורה, אין גמרא אומר טעם זה. ותחשב.
שוב ראיתי שגמרא בסנהדרין (כט:) שמשמע שהענין הוא שלא רוצה חוב חזק כחוב הכתוב, ולא מפני שזה חוב היותר יכול להוכיח. ותחשב.
** רש"י ואין צריך -
עיין במש"פ. עיין כעין זה בקדושין (ו.).
* מ:
** גמרא ואי לא כבישנא -
קשה, שאם עדים ישמעו זה, יעידו על זה, ויסתלק האונס.
* מא.
** גמרא כרבי יהודה -
עיין במה שכתבנו על רש"י שם. לכאורה, לפי רש"י ק"ק למה לא אומרים כאן לא פלוג. ותחשב.
** מחילה בטעות -
לכאורה, יש לומר כן גם כן על החזקה. ויש לומר שמסתמא היה מכיר באותו זמן שהוא שלו. ויש לדון.
** כמאן -
קשה למה אומרים את זה כאן, שיותר שייך לגמרא לעיל (כשדן מה עושה חזקה). ותו"ת.
* מא:
** גמרא בית הלל -
ק"ק למה אין גמרא תולה זה במחלקת רב הונא ורב חסדא (כן אני חושב) אם נפסל עדים שמכחישים זה את זה, שלכאורה, כאן, אחד מן העדים שקרנים. ויש לדון, שאולי מי שאומר הפחות אינו משקר, אלא רק לא אומר את הכל. ויש לדון, שעדיין יהיה ספק. ותחשב. ואולי נניח כן כדי שלא נניח שעד משקר. ויש לדון אם כל כך רע לומר שעד אחד משקר. ותחשב.
** רש"י איבעיא להו -
היה אפשר לומר שהוא אף לרב, ובציור שלא טען שקנה אותו ומכרו מיד. ויש לדון אם צריך לטעון כן; על כל פנים, יכול להיות כשהודה שלא קנה ומכר מיד. ויש לדון (שאולי זה לא מצוי, או אולי נאמר לא פלוג). ותחשב.
* מב.
** גמרא כי היכי -
יש לדון למה:
1. לוקח שמח.
2. מוכר שמח.
3. כדי שימצא לוקחים. ואם תאמר אם כן רק מפרהסים שדות שלא מכר כבר. ואולי ידוע כשמכר, שאז לא מפרסם עוד. ותחשב.
** רש"י הרי זו חזקה -
שדרך הבן לירש- לכאורה, הענין הוא שלא בחר האב למות, ואז אי אפשר לומר שעשה דבר מוזר וחלוק בחזקתו. לא הבנתי כל כך מה אומר רש"י כאן שהדרך הוא שבן יורש, שלכאורה, אין הדרך למות (אלא היה בעל כורחו), ואז משמע שאומר שהוא מה שבן יורש, ולא אחר, אבל זה, לכאורה, אינו שייך, שיהיה אותו בעיה בכל מי שיורש. ואולי הוא מה שלא הראה באופן יותר חזק (על ידי שטר) כדי שיהיה חזקה. ותח’.
* מב:
גמרא
** מערתא
־ צריך ביאור מה זה אומר. ותחשב.
* מה.
** גמרא דידיה -
יש לדון אם יש ראיה אם לא אניס אוכפיה, או יש ריעותא אם אנס אוכפיה.
** מידע ידע -
צריך ביאור למה אומר מילים אלו.
* מז.
** גמרא לא צריכא -
לא הבנתי למה, אז, צריך חזקה כלל, שנסמוך על העדים שאומרים שאינו של מרי קמא. לכאורה, היה לו לומר כתוס’, והוא שטוען כן, ויש לו מגו, שהיה יכול לומר שקנה אותו ממנו.
** דאבוהון -
קשה למה לא אמר כן גבי גנב ואריס עצמו, שהוא שווה. ותו"ת.
** דבית -
יש לדון אם אף צריך שהוחזק על אותו שדה בגזלנות.
* מז:
** גמרא אונס דנפשיה- נראה שר"ל שבאונס כעין רב הונא, יש שני סט"פים- אם מוכר, יהיה קרקע למי שכופה אותו, ואז יהיה טוב לו. אז, התוצאה העיקרי (רצה לומר, הראשון, שגרם לשאר) הוא שינוי במי שמעכב בו. כאן, יש עוד סט"ף, והוא שיש לו ממון (ואז, יכול להיות, נותן ממון…). אם כן, סט"ף ראשון הוא נוגע בו עצמו. זהו החילוק, אבל עדיין צריך ביאור קצת למה מחלק. ותחשב.
* מח.
** גמרא עד שיאמר רוצה אני -
ואם תאמר אם באמת נחשב רצון, למה צריך עוד קרא. ויש לומר שקרא גופא מגלה זה. ואם תאמר מהיכי תיתי שזהו הקא משמע לן; אולי הקא משמע לן הוא שאין ממש צריכים רצון. ויש לומר שעדיין כתיב "לרצונו.” ויש לדון בזה, שיהיה רצון- אבל רק רצון קצת, שלא די לשאר חלות. ותחשב.
** מעות -
נמצא שרק מצינו הכרח לחלק בזה לשמואל. יש לדון אם אף רב סובר כן, או שמסיק כתירוץ ראשון שאומר גמרא לו.[fn:18] ותחשב.
** מעות -
יש לדון אם לרב צריך שטר. ותו"ת.
* מח:
** גמרא הוא עשה שלא כהוגן -
קשה למה לא אומרים כן גם כן במכר.
* מט.
** גמרא לא אמר כלום -
היה אפשר לומר שזהו הקא משמע לן, ולכן אין חזקה. ותו"ת.
** רש"י אין נאמנים -
לא מבעיא- לכאורה, לא נראה כן מאותו גמרא בכתובות, ששם אומר גמרא שאם אומרים שהיו אנוסים או כדומה, נאמנים, אבל רק אם אין כתב ידם יוצא ממקום אחר. לכאורה, שם עוקרים עדותם, וכיון שיש להם פה שאסר, נאמנים. ויש לומר ששם מוכיחים שלא היה עדות כלל, אבל כאן, אומרים שהיה עדות, אבל לא על מה שאמרו. תחשב מה זה אומר, שלא נראה מובן. וצריך לחשוב על כל זה.
** דכיון דאית -
לכאורה, אין הענין שכל בני אדם יודעים שיש לאיש פירות בנכסי אשתו, אלא שכולי עלמא יודעים שהם איש ואשה, ובית דין יודעים שיש לאיש פירות. ויש לדון.
* מט:
** גמרא ממקום אחר -
נראה שר"ל ממקום חוץ ממקום שאומר תורה (דהיינו, נחלות דרבנן). עיין ברש"י ד"ה וכדרבא, שמוכרח נגד זה, שלרש"י אותו מילה (וכדרבא) הוא מה שמבאר באיזה נחלה מיירי. ותו"ת. ולולי רש"י, היה אפשר לומר ש"כדרבא" רק מציין ציור שבו אמרנו דין זה. ותו"ת.[fn:19]
** וכדרבא -
משמע שאין ר"כ מביא ראיה זה, אלא גמרא. ויש לדון.
* נ.
** רש"י ה"ג -
באחת- היה שני פעמים, אבל אומר שגזרו אחת מן הפעמים. ותו"ת.
* נ:
** גמרא כי א"ל נמי -
לא הבנתי למה גמרא מניח שאמר לו כן, ולא לא מוקמינן בציור שאין צריכים מגו. ואולי גמרא אומר זה רק לחדש שיש אף מגו כאן. ותחשב.
** רש"י ואב"א -
גם היה אפשר לומר ש"אי בעית אימא שאין ‘אין חזקה לנזיקין’ משמע שאין דין חזקה….” ותחשב.
* נא.
** גמרא כדר"י -
יש לדון אם אומר שכן כיוון רב כשאמר שהלכה כדייני גולה (רצה לומר, שלא אמר שהלכה כמותם בכל, אלא הלכה כמותם רק בציור של רב יוסף), או שאומר שכן אמרו דייני גולה (ואז אין מחלקת בין רב לדייני גולה). ותחשב.
** חזקה -
לכאורה, היה אפשר לדחות שאין לדייק שאין חזקה אבל יש ראיה, אלא שאין חזקה אבל יש ראיה עם חזקה, שכיון שיודעים שהיה מכירה, שלה הוא, שאין לומר שמכר לה רק לגלות זוזי, שאם כן, לא היה לו לשהות אותו שדה לה. ויש לדון, שאולי המתין עד שצריך את שדהו מפני איבה (וקשה, שאז נאמר כן בכל שהחזיק בו אשתו, ולא צריכים חשש שמא שדה זה למזונותיה. ואולי אין הכי נמי, כן אומר גמרא. ויש לדון.)
שטר מתנה- מעניין שמניח שאם אין שטר קונה, אין לדייק ממנו. ויש לדון, שעדיין הוא כל כך קשה למה הוצרך לכתוב שטר, ותשובה (שהקנהו ממש) עדיין הוא כל כך יכול. ותחשב.
** רש"י מזוני -
מה שצריך לומר שכולי עלמא יודעים כן (ולא שיכול בעל לטעון שהוא ידע כן) הוא שאם לא כן יהיה כמוריד לפירות או למשכנתא דסורא. ותחשב.
** דיחד לה -
עיין במה שפירש. גם היה אפשר לומר שהחידוש הוא שאינו חש אם רצה לשנות שדה זה לזה ליטול משדה אחרת.
** בתחומא -
נראה שאולי מה שהיה בתחום היה מפני שרצו שתלמידי חכמים ילכו רק לבית מדרש, ולא למקום אחר. אז, עשו אותו בצד תחום שיכול להגיע לו רק על ידי עירוב. אז, ממעט שאר מקומות שיכולים תלמידי חכמים להגיע לו. ותו"ת.
* נא:
** רש"י
- מעניין שרש"י גורס שרב למד מרבי מאיר. ועיין במסורת הש"ס.
- צריך ביאור איך נחשב רבי יוחנן רברבי נגד רב (ובאמת, רש"י עצמו מבאר כמה גדול היה רבי יוחנן). ואולי כיון שהלכה כרבי יוחנן נגד רב, נחשב רברבי. ויש לדון, עדיין ברש"י.
* נב.
** רש"י אם לא -
שני הפירושים דומים לשני הפירושים שאומר רש"י בשבת (בגמרות שאומרים רפואות), והם שלא מהני או שלא נמצא. ותו"ת.
** מרתא -
איני יודע איך ידע רש"י שהיה תלמיד חכם. ואולי מפני שהיו שני אחיו תלמידי חכמים, מסתמא אף הוא היה תלמיד חכם. כמובן, דחוק.
* נב:
** גמרא בפניו -
הקשה לי דר. בראל למה אין אומרים שצריך אדם לומר, “לך חזק וקני" בכל קדושין. ונראה לתרץ על פי גמרא זה, והוא שעושה מעשה קנין בפניה, ואז בכל זמן אין צריכים לומר, “לך חזק וקני.”
** אשה -
יש לדון מה לנו בזה:
1. כבר יש לה שכר, ואז לא תרצה כל כך לגנוב.
2. כבר יש לה שכר, ואז לא תוכל להורות היתר לעצמה לגנוב.
3. רוצה יותר שלא תחשד, שמה שעושה כאן יותר נצרך ליתן לה נאמנות. ותחשב.
** רש"י עבד -
עיין במה שפרש. לא הבנתי, אז, למה הוא חלוק אם הוא חי. ותחשב.
* נג.
** גמרא ברווח -
יש לדון אם צריך לעשות שנכנס ממש ברווח או רק שהוא יותר ברווח ממה שהיה לפני כן. ותו"ת.
** רש"י ואלא -
עיין באיך מפרש הקושיא. גם היה אפשר לפרש שמקשה למה אז צריך עשר. ממה שלא מפרש רש"י כך, אולי משמע שאינו כן, ושעדיין צריך עשר, ואף בציור שעושה שינוי כל כך גדול.
** האי מבריח -
גם היה אפשר לפרש שלא היה אומרו כאילו הוא דבר קטן כיון שבו מקיים חיובו.
* נג:
** רש"י כנגד פתח -
עיין במה מפרש רש"י. גם יש לומר שהוא כנגד יציאה, והוא על גב פתח, שרואים אותו בכל זמן שיוצאים. ולשון גמרא לא משמע כן כל כך. ותו"ת.
** הנעילו -
נראה לומר שכולו על סדר (ותו"ת), ונעילה אחד הוא בבקר ושני הוא אחר שהלך לבי באני. ועדיין יש לדון למה נצטרך שניהם. ונראה שאולי מגביהו גם נאמר על אותו סדר, והוא מפני שמצינו שלפעמים נפחת בי באני, והיה צריך מי שיגביה אותו. ותחשב.
- עיין ברש"י שמבאר דרשת חזקה. ק"ק למה לא אומרים ש,כמו בסוכה, ישיבה כולל אכילה. ואולי אין הכי נמי, ואם אוכל בה קונה.
** אותה קנה -
נמצא שבציור דשמואל, נתינת ממון סיבה, ואין מניעת בממון בעיה.
** פנימי -
מעשיו פועלים על חצר (שנותנים קצת קנין בו), ואז יש יחס בהם, ואז אף יש לקנות:
1. יש יחס בין מעשיו לחיצון, ואז קונה.
2. קנין דרך בחיצון ה"ה מעשה קנין בחיצון.
* נד.
** גמרא דרב -
נמצא שמביא את מעשה עצמו לראיה. צריך ביאור. גם נמצא שקרא לעצמו בשם "רב.” אז, היה אפשר לומר שכיוון כאן לרבי, וקרא אותו בשם רב כיון שהיה רבו. ונראה שמפני בעיות אלו פירש רש"י שגמרא אומר כן, ולא רב.
ויש לדון בלשון "לא קנה אלא…,” ולא "קנה ב….” נראה שאומר שלא עשה שני מעשה קנין, שנוכל לספק באיזה קנה, אלא רק עשה מעשה קנין זה, ורק בזה קנה. גם יש לומר שאולי כל זה נאמר ע"י מר עוקבא (אין זה כל כך נראה אם הוא לוי), ואמר שרואים שאף דבר קטן מהני אם הוא דרך הקנין, שמה שנצרך הוא רק דרך קנין. אז, אם אין דרך קנין, כאוות ציור, בוודאי לא מהני. אז, כיון שבא לומר שרק זה נצרך, לשון "לא… אלא" יותר מסתבר. ותחשב.
** רש"י ארעתא דבי -
היה אפשר לומר שזה רק בארעא של גר, שאז אין מי שאומר שאומר לו לעשות קנין. אבל, אולי, אם יש מי שאומר לו לקנות, מסתבר שמה שעשה הוא מעשה קנין (כיוון לקנות). ותחשב.
* נד:
** גמרא כדאזיל -
עיין במה שפירש רש"י. ונראה שהענין הוא שבדרך כלל, שדה הוא מה שבתוך מצריה. אבל יכול להיות גם כן דבר אחר. כיון שעשה דבר גדול כזה, גילה שלו שדה הוא דבר אחר, והוא השדה שעבד עד מצריו. ויש לדון מה הוא הדין אם לא עשה כל מצרה, אם קונה את כולה כנגד אותו מצר. למש"כ, לכאורה יקנה, אלא שיש לומר שאין חפץ כזה מסוים מן המוכר. ותחשב.
** זוזי -
מעניין שמניחים שיש שום סלוק, שהיה אפשר לומר שבכל קנין הוא רק שיש יותר סיבת קנין לקונה, כיון שיש לו סיבה אף ממקנה, ואז קנינו דוחה (וכל הבא מאוחר בא ממי שיש לו יותר קנין). ותו"ת. מזה משמע שגם יש סלוק (אף אם אינו נצרך, נראה שנעשה ממילא כיון שמתיר לאחר ליקח. ויש לדון, שכאן אינו לוקח עדיין. ותחשב.
** רש"י מעני המהפך -
עיין בתוס’ קדושין בזה שם. ויש להעיר שכאן יש רק אחד כזה שבו כבר נתן מעות. ואולי זה תלוי באם צריך להשיב מעות לו (ע"ל).
** היה יודע התירוץ -
גם יש לומר שאמר שידע מעשה, ואת,ל יש סתירה, מעשה רב.
** שאין יכולים עוד לחזור -
נ’ שמפ’ שמה שמסתלק הוא שאינו בידו לחזור. כיון שאינו בידו לעשות אותו שלו, אינו מיוחס לו. זה יבאר מה שדנינו לעיל.
** והאמר שמואל -
עיין במה שפירש. עיין בר"ן בנדרים (כן אני חושב), שאומר שהוא מפני שלא גירש אותם. נראה שאולי הם שווים, והוא שרק רואים שמקבלים אותו ממה שנשארים שם ולא נגרשים. ותחשב.
** אמר -
אלא בחזקה נמי- מעניין שיחלקו בדין מלכות.
** אתא לקמיה -
עיין במה שאומר. מעניין שמניח גמרא זה. גם, לכאורה, היה אפשר לפרש שידע שרב סבר כן, ואמר משמיה אחד מהם, ואז מוכיח שאינו סתירה. זה נגד מש"כ בד"ה היה יודע. ותחשב.
ודע שזה מ"מ. ויש לדון אם הוא כן גם במאמרות של ר"י, או רק במעשיו. לא נראה למה נחלק.
* נה.
** רש"י מקטע רגליהם -
גם רש"י שם מפרש כן. לולי אלו, היה אפשר לומר שמקטע רגליהם כיון שעושה שאי אפשר לגזול. כמו כן, יש לומר שמקטע רגליהם כשגוזלים, שמראה את האמת.
* נה:
** רש"י ספק ביאה -
לכאורה, חולקים בדין ס"ס שאינו מתהפך (ועל כל פנים, ר"א סובר שמהני. ואולי רבנן חולקים לסיבה אחרת.)
* נו.
** גמרא חצובא -
ק"ק למה לא דן בזה מתחילה כשאמר אותו.
** גיטין -
יש לדון למה לא מנה כאן גיטין.
* נו:
** גמרא אבא חלפתא -
לשון שני זה מעניין שגמרא (עירובין?) משמע שהיה ריב"נ רבו של רבי יהושע, שהיה רבו של רבי עקיבה, רבו של רבי יוסי. ותו"ת.
* נז.
** רש"י שכיב חד -
לא הבנתי למה צריך מה שאז אינו חצי ממון על פי זה, שאף בזה, יש לומר שרוב ממון יוצא על ידי קרובים, שאדם קרוב לעצמו. ותחשב.
** היה מעמיד-
ארבע או חמש- משמע שאז מקפיד. אם כן, אז יהיה חזקה.
* נז:
** גמרא אסורים -
נראה שאולי חולקים רבי אליעזר ורבנן למה אסור ליכנס לשדה שלו אם אינו רגיל, שרבי אליעזר סובר שהוא מפני שנהנה מנכסיו, וזה נחשב הנאה ממנו, ורבנן סוברים שהוא מפני שנהנה ממה שלא עצר אותם. ויש לדון.
* נז:
** רש"י רשע -
אין הוכחה מגמרא, לכאורה, שאז נקרא רשע, שהיה אפשר שרק אומר שאם רואה אינו רק שאינו חסיד, אלא הוא רשע.
** לא הבנתי
למה רש"י מניח שהוא חיוב, כיון שהוא עצמו אומר שהוא גם כן מדת חסידות.
* נח.
** גמרא יצרא -
צריך ביאור מה אומר, שאטו על אדם וחוה היה יצר, אלא היה שייך לר”ב. ותו"ת.
** רש"י כל שאין תחתיה -
עיין ברש"י אחר שאומר שהוא כדי שלא יהיו בני אדם רגילים במטתו.
* נח:
** גמרא לעקור -
ק"ק ל"ל אמר, “לצדד.”
* נט.
** רש"י מדלא מיחה איכא למימר -
לכאורה, היה לו לומר שמדלא מיחה, מוכרח לומר…. ותחשב.
* נט:
** גמרא רב חייא -
קשה, שגמרא (סנהדרין) אומר שלא היה רוצה ר"ח לחלק על ריב"י. ואולי זה רק אם כבר עשו דין על פיו.
* ס:
** גמרא פירות -
קשה מה יעשו בסעודות שבת. ואולי צורך מצווה חלוק.
** שכבר נזגרה גזרה -
ועוד, לכאורה, שיש סיבה לו. ותחשב למה לא אמר כן.
* סא.
** גמרא שלש שמות -
לכאורה, רצה לומר שלש שמות שבפסוקים או משניות, שיש עוד שם (אפתא).
** ואב"א -
ק"ק למה יביא משנה ולא קרא. ותחשב.
** תא -
יש להעיר שהיו בתוך בית של היכל. ואולי הם רק דומים ליציע שבפתח הבית. ותחשב.
** חדא תשמישתא -
לכאורה, זה צריך להיות כ"הכא תרגימו,” ולא כרב יוסף, שלר"י (לרש"י) יש שני תשמישים חלוקים להם.
** חדר מיבעיא -
לכאורה, זה רק ל"הכא תרגימו.” נמצא שההוכחה לדין של ר"נ הוא רק לאותו שיטה. נראה שלכן לא אומר גמרא שאביי ב"ל כמשנה, אלא כר"נ, והוא שהיה יכול לדחות כר"י. ואף בלי זה יש לומר שמשנה הוא רק יתירה, אבל לא אומר דין זה בדווקא. ותו"ת.
ויש לדון בכל זה, שעדיין הוא יתירה, שכבר אמר יציע, שהוא שוה. ואולי חדש יותר חלק בן הבית בבנין. ותו"ת. יש לדון, שאז רישא הוא משנה יתירה. ואולי יותר קל לומר לא זו אף זו מלומר זו רין צריך לומר זו (חשוב אני שכן ראיתי). ותחשב.
** אף על פי שאינו -
יש לדון על מה קאי (מה אינו צריך להיות גבוה עשרה טפחים):
1. המעקה.
2. צורת הפתח.
** פתוח לתוכו -
אם פתוח לתוכו, ויש לו תשמיש של בית, צריך ביאור מה עושה שאינו הבית עצמו.
* סא:
** גמרא דרובא -
לקמן, אומר "דאיכא,” ויש גורסים כן אף כאן. אם כן, יש לדון מהו "דקרו לבירה" שאמר לעיל. נראה שזה אומר שכל או רוב בני אדם קוראים אף לבירה בשם בית (ואולי אף בשם בירה). צריך צירוף של הוכחת גמרא עם מה שלא מסתבר כל כך שהוא מן החצי. ותו"ת.
** רב אשי -
רש"י אומר ש"חייא" הוא רב חייא. ר"ח לא חי בזמן ר"א, ואז צריך לומר שהוא רב חייא אחר, רב אשי אחר, או שקנה לפני זמן הרבה. ותו"ת.
** רש"י בבירה -
הבירה אשר הכינותי- יש לדון מה הראיה מזה. ואולי אותו קרא נאמר אף על החדרים היוצאים ממנו, אף שרק אמר בירה. וצריך לעיין שם. ותחשב.
** בבקעה -
דאין אונאה- חולקים אם אין אונאה כיון ששווה אותו ממון או מפני שלא חידש בו התורה דין של אונאה, אף שנתאנה. מרש"י זה נראה כראשון. אולי יש לדחות שדמים מודיעים רק מפני שמניחים שלא היה עובר על אונאה, שיש לומר שמחל. ויש לדון, שאחר לא ידע שחבירו מחל (שלא אמרו בפירוש), ואז אולי מניחים שלא יקבל אותו באונאה. ותחשב.
* סב.
** גמרא רוחין -
קשה, שאף בזה יש לומר שרק נתן לו מקרן אל קרן, שכל קרן יש לו שני צדדים. ואולי לומדים מייתור הלשון. עדיין יש לדון איך יודעים שנתן כל הצד, ולא רק חלק ממנו. ואולי מסתבר לנו לנקוט הכי גדול. ותחשב למה יהיה כן, שלא נקטינן כן בלי הוספה זה.
** גאם -
קשה למה אין זה כראובן בצפון ומזרח….
** מודה -
מצאנו, אז, עוד שתיקה כשלא הודה (שממה שמודה כאן, משמע שחלק בשאר ציורים).
** תרין -
יש להעיר שאף אי היה ראש תור, היה ממצר אותו בתרי רוחים. אולי לומדים מייתור לשונו.
* סב:
** גמרא ולא היא -
נמצא שלא בכל זמן שאדם שותק מודה. ויש להעיר שאביי הניח שהודה, ואז צריך לומר שבדרך כלל, מי ששותק הודה. ותו"ת. ואולי מה שלא אמר כלום הוא מפני שידע שאביי יבין (כמו שמצאנו שלבסוף הבין). ותו"ת.
** רש"י אבל מובלע -
כרב- יש לדון בזה. ותו"ת.
** אבל מובלע -
המע"ה- יש לדון אם המוציא מחבירו עליו הראיה הוא factor כאן. יש לדון למה לא יהיה.
** מבי מר -
רביע- קשה, שאולי כתב לשון זה רק מפני שהיה מפרש. לולי זה, היה נראה לומר שידע שפסק כן על שטר שכתב בו אותו לשון. ותו"ת.
* סג.
** גמרא פלגא -
יש לפרש שתשעה קבין נקרא חצי כיון שאז יש שני חלקים, וזה אחד מהם, דהיינו חצי.
** למקום מעשר -
צריך ביאור, אז, איך מהני המעשר, שהרי אינו מפריש מטבלו. אין זה כל כך קשה, שנראה שלוי מעשר משלו על של בעל הבית. ותו"ת. כיון שמעשר משלו, נותן לעצמו. ויש לדון. זה תלוי בלמי טובת הנאה כשאדם תורם על של חברו. כן מסיק הגמרא. ואולי כאן התנה, ואז בוודאי יש לו טובת הנאה. ויש לדון אם יכול אדם להתנות, שלא בא לעולם, ולא יהני שיור.
* סד.
** גמרא אי ס"ד סתמא -
קשה, שאולי החידוש של שיור דיוטא הוא כשכתב לו עומקא ורומא (או "מתהום…").[fn:20]
** רבא תוספאה -
יש להעיר שמצאנו בכ"מ שרבינו מדבר עם רבא, ותוס’ מעורר שרבינא היה תלמיד חבר של רב אשי, ורב אשי נולד כשמת רבא. אז, אומר (חשוב אני) שיש שני "רבינא"ים. לכאורה, היה אפשר לומר שיש שני "רבא"ים, בפרט כיון שראינו שהיה רבא חלוק מרבא סתם שהיה רבינא דן עמו. ויש לדון, שאולי כיון שמצאנו שכאן נקרא רבא תוספאה, אי אפשר שזה הנקרא סתם במקום אחר. ויש לדון, שאף רבא נקרא בשמו במקומות מיוחדים. ותחשב.
* סה.
** גמרא לטעמייהו -
ק"ק, שאומר שר"י גרס איפכא. אז, קשה למה מניחים שחולקים.
** אין להם… זע"ז -
קשה, שלמה מניחים שהוא בעין רעה, וזה מוכר את הבור; אולי הוא בעין יפה, וכל אחד הוא כמוכר את הקרקע סביביו. ותחשב.
** רב -
אז, לכאורה, מוכרח שהוא רב, ולא רבא (ולעיל כשהביאו אמר רבא. שו"ר בב"ח שם.).
* סו.
** גמרא יערות דבש -
ק"ק ל"ל ילמוד מזה לשאר מחוברים לקרקע.
* סו:
** גמרא רבה בריה דר"ה זוטי -
נראה שזה רבה זוטי (נמצא במק"א (זבחים)). אולי זוטי קאי עליו או אולי על שם אביו. אם קאי על שם אביו, אז אין צריך לומר עוד שפירוש שמו היה גדול הקטן[fn:21]. ותו"ת.
** ר’ יוסי בר’ חנינא -
יש לדון אם זה אותו איש של ר’ יוסי בר’ חנינא.
** רש"י ומשני -
אין לך- משמע שאין לך לא אומר שהוא הכי גדול. עיים במקום אחר שדנינו בזה.
** אליבא -
כללא- זה לא די בפני עצמו, שגמרא לעיל הקשה כן. ותו"ת.
* סח.
** גמרא הסנטר -
נראה שהוא על שם מש"א גמרא שבת ש"לא קראתי לאשתי אשתי… אלא ביתי,” שחפץ נקרא על שם דבר שהוא (אותו חפץ) עיקרו.
** רש"י אלא מאי -
להוליכו- לכאורה, רצה לומר "להוליך א"ע.”
* סח:
** רש"י פיסקי באגי -
רחוקים ומופלגים- משמע שצריך להיות רחוק ומופלג בצונמא. ואולי רחוק אומר שיש צונמא בפניהם. ויש לדון אם זה נקרא רחוק.
* סט.
** גמרא צבורות לגדר -
לכאורה, יש לומר שזה רבי מאיר. ואולי אף רבי מאיר צריך תיקון יותר מזה.
* סט:
** רש"י גופני -
אלא אלו- יש לדון, שאולי יש פרובוביליטי שווה שאחד יקרא לזה אילן ושיקרא לזה אילן. אבל מה שאדם מן הקרואים גפן אילן לא מגלה כלום, אולי, על מה קורא לדקל. ותו"ת.
* ע:
** גמרא דכולי עלמא -
בדרך כלל, כשגמרא אומר כן, אין זה קאי. כאן, קאי. ותו"ת.
* עא.
** גמרא מאה ועשרים -
מעניין לדמותם, ששם אמר "בור,” ואפשר שזה אף כולל זה, אבל כאן אומר לשון שלא כלל בית זה. ותו"ת.
* עא:
** גמרא אלא חורב -
אם זה הסיבה, גם לאילנות יהיה הדין כן. נראה שיש להם אותו דין, אלא שלא צריך לשנות אותם, שהם נמכרים גם כן, ולא רק באים בהקדש. ותחשב.
* עב:
** גמרא רבי מנחם בר’ יוסי -
אם כן, יש לתרץ שני הסתירות ברבי שמעון לומר שאין זה רבי שמעון, אלא רמב"י.
** אלא ר"ש -
עיקר הת’ לקושיה ראשונה הוא שהוא מחלקת בדעת ר"ע, וזה רק שיטת ר"ש. אם כן, אין צריך להביא כל הסתירה לזה, אלא בא אגב, ובא לתרצו. ותחשב.
* עג.
** גמרא כדכתיב -
רצה לומר, כדאמר הוא לשון ארמית, וכדכתיב הוא לשון עברית.
* עג:
** גמרא גודפייהו -
יש לבאר: הנוצים נשארים בעוף כיון שהם תוחבים בבשר. אז, כשיש שומן הרבה, נראה ששני דברים יכולים לקרות:
1. אפשר שכיון שמה שהוא בתוך בשר אינו בשר לבד, אלא בשר עם שומן, יכול להיות שמה שהוא קרוב לנוץ הוא שומן. כיון ששמן לא מדביק כל כך (הוא slippery), נופל הנוץ.
2. כיון שיש כל כך שמן, השמן דוחק את הנוץ עד שיוצא.
** ההוא כוורא -
עיין ברש"י שמבאר שאין הים סובל דבר מת. יש לדון למה לא זורק, אז, את שרו של הים (עיין לקמן).
* עד.
** גמרא דלמא שקלת -
מוזר איך יכול להיות שלקח במלי שהישמעאלי יבין, שהיה גדול. משמע שאף שהבגדים, לכאורה, היו גדולים, לא היו החוטים גדולים. ותו"ת.
** דבחישא -
עיין במש"כ רש"י בביאור בחישא. אם כן, כבר מבואר שיש לה קרנות. ואולי רש"י בא לפרש שניהם. ותחשב. גם יש לומר שאומר שבחישא, ולכן יש לו קרנות. ותחשב.
** נשקי -
עיין בירושלמי ברכות (פרק ראשון) וחגיגה (פרק שני) בביאור קירבות שמים וארץ.
** אוי לי למה -
עיין עבודה זרה (ד.). ואולי שם הוא כרבה. גם יש לומר ש"אוי לי" ו"מי יתן" חלוקים.
** רש"י היכא -
היה אפשר לדחות שהלך על אחד מן אותם דגים שהזכיר או כעין זה, ואז הלך לסוף העולם. ויש להעיר שמוזג של סוף העולם לכאורה אפשר רק אם העולם אינו כדור. ותו"ת.
* עד:
** גמרא ים… אלא שרו של ים -
נראה שהוא על דרך "אשתי ביתי,” ששרו של ים הוא עיקר של ים.
** בישרא מליחא -
קשה, שא"צ להמיתו, ולכן לא ימיתנו. ותחשב.
** שמע עיניו -
לכאורה, נזדעזע ר"י כיון שהיה ירא. יש לדון איך זה יתיר יראתו. ואולי רק בא לבאר לו, ולא לעשות שלא יפחד. ותחשב.
שו"ה שאולי אמר לו שאין לחוש לו, שכיון שנסתרס, אינו כל כך מפחיד. ויש לדון.
** פריצי -
קשה, שהרי הוא סריס וצוננת, ואז קשה מה לנו שהם פרוצים:
1. אולי יש דגים אחרים שיבואו על לויתן.
2. אולי מתוך שרוצה ביאה, יזיק.
* עה.
** גמרא מלאכי -
כמובן, יש לציין לגמרא נדרים (כ:).
** כדין -
נראה שאפשר להיות שכך הוא ענין של כל "אלו ואלו דברי אלקים חיים,” והוא שה’ עושה ששניהם נכונים (שבורא ס"ר או ס"ט). לכן, רק בגמרא גיטין מקשה על מושג זה, כיון ששם דן מה קרה במעשה, והרי שם קרה מה שקרה. ותו"ת.
** לוויתן -
יש לדון אם אכל ממה שהרג גבריאל או ממה שמלח (או משניהם). אם לא אכל ממה שהרג גבריאל, יש לדון למה הרגו.
* עה:
** גמרא משיח -
משמע שלא היה צדיק, שאילו היה צדיק, לא היה צריך מקור אחר. ויש לומר שנקרא על שם ה’ קודם שאר צדיקים. ודחוק.
** לדידי -
יש לדון איזה ירושלים ראה (של בית ראשון או שני), שאם ראה של בית שני, צריך להיות זקן מאד, אבל אם ראה של בית ראשון, צריך להיות מאד מאד זקן.
ונראה לפרש על פי מה שמביא תוס’ בתחילת חולין שכל "ההוא סבא" הוא אליהו הנביא, שראה אף של בית ראשון.
* עו:
** גמרא מראה מקום -
עיין בקידושין (מח:) שמונה אביי הסוברים ש"מראה מקום הוא,” ולא מזכיר את זה. צריך ביאור לשיטתו. ותו"ת.
* עז:
** גמרא מטבע… חליפין -
ק"ק למה לא אמר "שאינו נקנה בשטר…,” שבזה דנים.
** רש"י אין הדמים -
גמרא אומר שהוא ביטול מקח, ולא שהוא מק"ט. מרש"י משמע שהם שווים.
* עח.
** גמרא דאף על גב דלא אמר -
צריך לומר שסבר שאין אומרים שלשון יתירה בא לטפויי.
* עח:
** גמרא סיח -
דורשים את זה להולך אחר סיח נאה (גבי עיר), וגם דורשים אותו להיות ת"ח. זה מעניין.
** נתן -
לכאורה, אף רבנן של כאן סוברים כן, שגמרא לעיל אמר שרק חולקים לאיזה תשמיש עומד. ולכאורה, מכוון לומר נחום ומחלקתו.
* עט.
** גמרא במה שבתוכן -
נמצא שאינו כמו קנין רגיל. אולי קנין הקדש חלוק, ואולי אין ענין הקדש למעילה קנין.
** נפח -
יש לדון איך דורשים מזה לאש שאינו צריך ניפוח. ותו"ת. ויש לומר שקורא אותו נפח כיון שהוא נפח לעצמו, שאין צריך עוד נפח אחר. ותו"ת.
** דברי של -
לכאורה, זה ייתור, ש"דברי" הוא כבר סמיכות.
ויש לציין לרש"י בפרשת תולדות שאומר שלפעמים אומרים ת"ף בסוף מילה, אף אי כתב "של.”
* פ:
** גמרא תורניסא -
קשה, אז, איך רואים מן הקרא שגזעם מחליף, שאולי לא מיירי בארזים אלו. ויש לומר שסתם ארז גזעו מחליף. גם יש לומר שבלי זה אין הייתור מודיע כלום. ותו"ת.
* פא.
** גמרא זוזי -
אם כן, לא יהיה הדין כן אם נתן לו אדם. ויש לדון.
* פא:
** גמרא שהראשונים -
יש לציין לגמרא שאומר שסתם דבר שר"א אמר היה בשם ר"י רבו.
** שמא -
היה אפשר לומר שמסופק אם צריך ליקח קרקע, ואולי אם כן, לא הוה ליה לדון בקנה שום אילן, אלא רק פירות.
** שגרן -
צריך ביאור למה אין בעיה כאן במה שאינו ראוי לבילה.
* פב:
** גמרא עובדא הוה -
מצאנו שאמר כן כ"פ. אפשר שהוא מפני ששכח כל תלמודו, ורק זכר מעשה. ותחשב.
** שוב
נראה שלי שאף מה שאמר לו אביי לר"י הוא מפני שר"י שכח, ואז אמר לו שלא לחלוק. ותחשב.
* פג:
** גמרא קנה וקנה -
יש לדון מה אומר:
1. קנה קרקע, וקנה הארז.
2. אולי כוונתו היה רק לכפל לומר שבוודאי קנה (כמו שמצאנו כ"פ). אם כן, אינו מוכרח (אבל עדיין אפשר) לומר כרש"י (שקנה ארז).[fn:22]
** רש"י מוכר -
כגון- משמע שאינו רק באונאת שתות. אם כן, נמצא שרש"י סובר שיש חילוק בין מק"ט לאונאה. יש להעיר שלקמן (פרק ששי[fn:23]) לא משמע כן מרש"י.
ויש לדון, שאולי אף אם ביטול מקח הוא מפני מקח טעות, אולי עדיין רק יכול מי שנתאנה לקבוע כן, שאולי מה שעושה אותו מקח טעות הוא מה ששוויותו אינו שווה למה שניתן לו, ותלוי באמידת מי שנתאנה. ויש לדון למה ייתלה לו, ולא בחבירו, שהרי הוא דבר חלוק. ונראה שאף יש לומר שבכל מקח טעות תלוי רק במי שחסר (שרק לו אינו fair, ורק לו אומרים שלא היה רוצה בזה), אלא שבדרך כלל, אין סיבה לחשוב שכל אחד כבר רוצה בזה. בכגון ביטול מקח, פשוט שכל אחד רוצה. ותו"ת.
* פד.
** גמרא הצל -
לכאורה, צל אומר הקרקע. קשה, אז, למה מקשה מחמה עצמו; היה לו להראות ממראהו על הקרקע. צריך לומר שצל רצה לומר מקום שברקיע שאין חמה. ותחשב. וצריך ביאור.
שוב ראיתי שחמה אומר אף מקום שבקרקע שאין צל (כמו מש"א גמרא ברכות גבי "יש צל ואין חמה"). עדיין יש לדון אם אותו מראה הוא אדום. נראה שהוא אדום.
** רש"י דא"ל -
חוטא נשכר- משמע שזה הסיבה שאי אפשר לחזור. ראשון, יש להעיר שזה ישיב למש"כ בד"ה מוכר (בע"א). שני, זה מעניין. ודע שאולי אין זה סיבה, אלא הוא סימן, והוא שידוע לנו שלא יהיה ההלכה גורם טוב לחוטא, ואז בהכרח לא יוכל לחזור בו, ויש שום סיבה אחרת לזה. ותו"ת.
* פד:
** גמרא דא"ר אילעא -
ק"ק, שלכאורה, אין זה סיבה שהם מין אחד, אלא סיבה שאין בעיה אחרת שמעכב עישורו. ויש לומר שאין הכי נמי, אלא שכיון שאומר שהנפקא מינא הוא למעשר, צריך לפרש איך יש נפק"מ, ואין בעיה ממה נפשך. גם יש לומר שמוכיח מזה שאין קפידת בני אדם עושה דברים שני מינים. ותו"ת.
** כדלא גמרי -
נראה שר"ל כאילו הוא לא למד, אלא שנקט לשון טוב (כמו, “שונאיהם של ת"ח").
** מדד -
צריך ביאור, אז, מה יהיה הקנין אם לא כליו. ותחשב. ואולי הוא מפני שעומד ליקח אותו.
** רש"י רבי ינאי -
זה מראה מקום.
* פה:
** גמרא כליו של מוכר -
היה אפשר לומר שאף על פי כן, חצרו קונה. ותחשב. ונראה שאי אפשר כיון שגופא דן בצד שכליו של לוקח קונים ברשות לוקח, שאומר שהכלי, ולא החצר, הוא העיקר. ותחשב.
* פו:
** גמרא פשתן -
ק"ק, שהיה אפשר להקשות את זה בין כך ובין כך, שקשה למה אינו כפירות. ותחשב.
* פח.
** גמרא קייצי -
קשה, שאף בלי זה, יהיה דבר הגזול, ואי אפשר להקדיש. אולי אז היינו מצריכים דעת לגנוב.
** קיים בנפשיה -
לכאורה, צריך להיות ששמואל אומר זה. ק"ק, אז, איך מקיל על ידי זה. ואולי סמיכות זה עושה קנין גמור. ותו"ת.
** מעשר -
קשה איך מחזיר אותו כיון שהוא חסיד כל כך. ואולי הוא אם ע"ה מסכים.
* פח:
** גמרא גירומין -
לא הבנתי מושג זה כל כך, שכיון שכבר ידוע כן, אמירת "שני לוג" יהיה אומר "שני לוג עם גרדומים,” ואז לא ירווח. ותחשב.
* פט.
** גמרא מה שמך -
כיון שזה כבר קרה לו כשבא לרב, לכאורה, היה לו לתרץ דבר כעין "ברוך,” שאז אי אפשר לקללו. ונראה שידע שימצא רב איך לעשות שהוא קללה, ואז אמר קרנא כדי שיתן אותו קללה, ויהיה רק נתקלל פעם אחת. ותחשב.
** רש"י נפקא -
עיין שם, שלא אומר שכן קרה. ותו"ת.
ויש להעיר שלא ידע שמואל את שמו, צריך לומר שמעשה זה קדם.
* פט:
** גמרא אמרה -
וא"ת בודאי אמרה, שאנו יודעים אותם, ואז בודאי היה מי שאמר אותם, ולמה נניח שחלק ריב"ז ע"ז. ויש לומר שאולי אחר שהיו ידועים אמרום. ותחשב.
** כי ישרים -
ק"ק למה לא אומר כן בגמרא הורות ונזיר שדן בזה. ותחשב.
** מהנדסי -
לכאורה, רצה לומר שאי אפשר לו לעשות אותו למשקל, שיבינו, ואז צריך לשאר אותו לעביט לעולם.
* צ:
** גמרא יותר משתות -
היה אפשר לשנות את זה לומר ששל מקדש הוא 2.4 של גבולים, ואי אפשר להוסיף.
** רוז פפא -
אולי זה שייך לא רק למה ששמו היה ר"פ, אלא מה ששם העיר היה פאפונא.
* צא.
** גמרא הזאת -
יש לדון מהו הדרשה:
1. מילת הזאת ומילת חזית הם דומים.
2. אולי הזאת משמע שהראה להם (כמו גמרא בסוף תענית וגמרא בפרק אלו טרפות). אם כן, צריך לומר שעשו כמו זה. ויש לדון.
לשון גמרא משמע כראשון, אבל קשה למה לא נאמר כשני. ותו"ת.
** חד -
אם זה קאי על מנוח, קשה מה לנו במה שבועז הוא אבצן. ותו"ת.
* צא:
** גמרא יואש -
מעניין שדורשים שני שמותם על שניהם, ולא אחד על אחד. ותו"ת.
** דרכם -
ואם תאמר הרי אם כן יישן אותם. ויש לומר שיותר קלים לאבד. גם יש לומר שיש יותר טורח מן הטוב שיוצא. ותחשב.
* צג.
** גמרא אפילו לר"א -
עיין במה שהערנו ב"חברותא קטן" שמשמע שחזקה יותר טוב מרוב. ונראה שאולי רק אומר כן בר"א, ואין הקושיה מר"א.
* צג:
** גמרא מנהג -
מעניין, שלעיל לכאורה פסק כן, ועכשיו אומר שרק מנהג הוא. ותחשב.
* צה:
** גמרא זהו אוצר -
יש לדון אם ברייתא או ר"ז אמר כן.
** מודה -
משמע שמה שמחדש הוא שמודה בזה, ולא שמשנה מיירי בזה. ותחשב.
* צו.
** גמרא כמאן פשט -
יש לדון מה קרה:
1. לא באר כמי סבר כשאמר לאביי; דנים כמי סבר.
2. באר כמי סבר לאביי, אלא חולקים מה באר.
נראה כצד שני.
** דרומאי -
קצ"ב למה יאמר כן, ולא יאמר כרבי יוחנן. אולי סוברים ש"כל שלש יום" משמע שיש יותר מ"שלש יום" אחד שפושט. ודחוק. ותחשב.
** סיפתקא -
אם ר"י לא מיירי בזה (עיין ברשב"ם), קשה ל"ל לומד ממה שלא נעשה סיפתקא שלא נעשה חומץ לפני כל כך זמן. ויש לומר שלא לעולם נעשה חומץ מיד. ותחשב. עוד יש לומר שמשנתינו אף בארבע ימים, ואז אין לומר שיש זמן ודאי שהוא יין, שאותו זמן תלוי בארכו. ותחשב.
* צח.
** גמרא כל המתגאה… ואינו ת"ח -
משמע שבלי זה היה נכנס במחיצת ה’, אף שאינו ת"ח.
** חלא לא -
צריך ביאור למה אומרים מזל גרם רק גבי חלא.
** רש"י אבל -
מעיקרא- קשה למה אין זה בעיה אם ברייתא שלעיל גבי הפריש יין ומצא שהוא חומץ. ותחשב.
* צח:
** גמרא דרכיה -
משמע שהוא רק הדרך, ואין צורך. ויש לדון, שנראה שמשמעותו הוא כעין "דרך הארץ.” ותחשב.
* צט.
** גמרא גופייהו -
משמע שאין בעיה בכנפות שלהם, אף שגמרא לעיל אמר שאין שני טפחים בשני טפחים יושב. ועיין במה שכתבנו בסוכה. ותו"ת.
** דמצדדי -
ק"ק איך יודעים שאותו מד"א הוא האומר שמצדד…, וחבירו אמר, “כאן בזמן…" ולא להיפך. ותו"ת. ושוב ראיתי ברש"י שמפרש שגמרא בלשון ראשון שאומר (רצה לומר, כשאומר שמר סבר שהוא…, קאי על תחילתו…. ועיין שם.
** למטה כלמעלה -
אף שלא היה למטה משמע כלום, היה משמש בגובה (דהיינו, שהיה לו space לגובה), שרואים כאן שהיה רק עשרים אמה על גבו.
אם כן, אינו ממש כלמעלה.
** רש"י כזה -
במקום אחר הערנו שאין זה נכון, שהתמונה מראה שלא היה קו ישר בין כנפותיהם. אם כן, אף אי לא היו באלכסון של בית, לא היה צורך לנס. ותו"ת.
* צט:
** רש"י דרך המלך -
הכהן הגדול- אם כן, אף כה"ג יש לו דין זה. זה מחודש.
** מאי שנא -
תקינו- לכאורה, צריך תקון מפני שאין רבים לקנות ולהקנות.
* ק.
** גמרא שאבדה -
קשה, אז, משנתינו. ואולי מוקים שהוא בזה. קשה, שאז פשוט שלא יקנה את דרכם ראשונה, שלא נתן להם כלום. גם יש לומר שהוא מחמת דין שני, שאומר שא"א לקלקל. לא נ’ כן מרש"י.
** אידי ואידי -
ק"ק, אז, למה צריך שניהם. אולי זה מכלל זה נאמר. גם יש לומר שמשמע שהם חד שיעור. נפק"מ הוא אם אומר לו אדם שהוא כשיעור אחד, שיאמר שלדברי שניהם טוב הוא.
** רש"י רב אשי -
עבמש"כ לעיל. ק"ק ל"ל כ’ שרק לא תקנו לו סיבה.
** ה"ג -
ע’ במק"א בב"ב שאומר עליהם תנאי. ואולי צריך לומר שהם מביאים שם ברייתא.
* ק:
** גמרא הדרך -
יש לדון מה דורש:
1. הדרך משמע שהוא הדרך הכי גדול וחשוב. יש לדון איך רואים איזה מנין הוא (שאולי רק מוסיפים אמר או כדומה).
2. אולי לשון ה אומר עוד דרך (יש לדון למה). ותחשב.
** ביום הקבורות -
יש לדון מהו ת’ גמרא, שאינו באותו יום, ואם זה די, קשה למה לא יכול להיות בכל זמן ביום ששי. ותחשב.
** רש"י משבעה -
הבל- יש לדון, שמצאנו כמה סגולות שהם מוזרים.
* קא.
** גמרא לבראי -
זה בתחתית חצר, שהוא כותלי מערות, כיון שהם עמוקים מחצר.
** טמא -
קשה למה לא עושה טפח אויר.
* קא:
** גמרא מעמיק -
קשה, אז, למה לא עושה הרבה כוכים.
** חרותא -
זה rhyme עם "ברותא.” אז, יותר טוב אם לא אומר "בדותא.”
* קב.
** גמרא מד -
מעניין שנאמר רואים, אבל רק אם הם קצת רחוק. ותחשב.
* קב:
** גמרא בנפלי -
קשה, שמודדים את החצר, ואין המת בכלל. אז, קשה מה לי בנפלים. ויש לומר שעשו כל החצר קטן וייחדו אותו לנפלי. היה יותר קטן כיון שא"צ אמר רוחב. יש לדון למה לא רק קברו יותר שם.
* קג.
** לקדשייהו באנפי נפשייהו -
קשה, שיאמר שיש נפק"מ אם אומר שדה זה הקדש, ועומד בשדה שלו, ולא בתוך נקעים וכדומה. ותחשב.
* קג:
** גמרא סמוך למצר -
לא הבנתי החילוק בין זה לסלע יחידי.
* קה:
** רש"י בי רב -
עיין ברש"י ביבמות פג: שחולק על זה. ואולי רש"י כאן רק קאי על "אמרי בי רב" זה, שכיון שהזכיר רב הונא צריך להיות רב המנונא.
* קו:
** גמרא והא רב ושמואל -
יש להעיר ששם מנכה, וכאן מוסיף על מה נותן לו.
* קז:
** גמרא מאה ותליסר -
קשה מהו הצד לומר כן, שלכאורה, הסיבה להוסיף את היג הוא שיש שנים שאומרים שהוא יותר. אם כן, יהיה יג פחות מן השלושים. ותחשב.
** רש"י אדאכלת -
גם יש לומר שהוא על שם שעושה שקשה ללמוד, כמו שאמר גמרא בפסחים ובמק"א (ברכות?). ותו"ת.
* קח:
** גמרא אח -
קשה, שלכאורה, יודעים שבת קודם לאח, ויודעים שבן קודם לבת. אם כן, בן קודם לאח, ויותר מסתבר שאב ידחה אח משידחה אח. ויש לדון:
1. אולי לא  יודעים שבת קודם לאח, ורק לומ‛ אותו מזה.
2. אולי אין יודעים זה כי אם בציור שאין אב. אולי בן נתחשב ביותר כשאין אב. ותחשב.
** הא לאו הכי -
לכאורה, שואל את זה רק מפני שיודע בתשובה, שאין זה קשה, שמצאנו בכמה מקומות שגמרא לא יאמר ”הני נפישי,“ אף שיכול.
** ותנא -
לשון זה מעניין, שלכאורה, הקשה, והיה לו לתרץ באמירת התשובה. נראה שהוא מפני שאמר טעמים של המקשה, ואז חושר לומר ”ותנא“- אלו טעמיו.
* קט:
** גמרא והוא לוי -
קשה על יסוד זה מרבי, שתוס‛ כ‛ שהיה מאמו מיהודה, ואז היה יכול להיות שבט של ארץ ישראל, אף שקרא אומר שלא יסור שבט מיהודה. ותחשב.
* קי.
** גמרא ממשמע -
משמע שרק מקשה שכבר הוא ידוע. לולי זה, היה יכול להקשות מה לנו בזה כלל. יש לדון, שאולי זה קושיה יותר טובה.
* קי:
** גמרא ניתנה תורה -
משמע שקודם לכן, כן היה ההלכה, ורק אז נשתנה (כן משמע ממקום בשבת שאומר לשון כזה). לולי זה, היה אפשר לומר שהוה אמינא שהם טעו, ולא ידעו הדין.
** רוב בנים -
יש לדון אם בנים דווקא, או כולל אף בנות. גם יש לדון אם בנות דומה לאחות האם. גם יש לדון אם אחי האם דווקא, או אולי אף הוא כולל אף אחיות. ותחשב.
** רש"י אמר ליה -
לא יכחיש סברת- עיין לעיל שרבא עושה כן (חושב אני שהוא בפרק חזקת הבתים).
* קיא.
** גמרא אפס -
מעניין שאומר כן על ר"ז, וקורא לו בשמו בלי שם רבי, וכולו מפני שאין הלכה כמותו. ותחשב.
** ארבעה עשר -
יש לדון למה יהיה כן. ותו"ת.
** ממטות -
צריך באיור, אז, למה צריך קל וחומר. ואולי אומר, ”אילו לא היה קרא….“
** רש"י וגולתיה יאי -
נראה לומר אולי כפשט ראשון לומר שכך השיב לו ר"י (ולכן דן בבגדו אם מטמא כשק), והוא שאמר לו השמש שהיה נאה, והוא השיב שכמדומה לו, היה כעין שק.
* קיב.
** גמרא זבין -
כיון שאומר שאין לומדים מן הקרא, היה אפשר לומר שמדבר בהסבת בן.
* קיג.
** גמרא מאי משמע -
יש להעיר שיש ברייתא שמשמע שנלמד ממה שהשני הוא בן. ותחשב.
** דבק -
יש להעיר שקרא שאומר לשון דיבוק גבי איש ואשה הוא קרא שאומר שצריך אדם לבדוק באשתו, ולא באשת איש או כדומה. אם כן, לכאורה, פשוט שאין דיבוק לשון קידושין, ואינו רק באיש ואשה. אולי צריך לומר שהוא לשון ביאה, ואז שייך לאיש ואשתו, שזה חלק מן הנשואים. גם יש לומר שיכול להיות משמע שניהם, קידושין או ביאה. יש לדון איך נדע שמשמע קידושין כלל, ולא רק ביאה. גם יש לומר שאין לומדים מזה פירוש המילה, אלא לומדים רק שנכ‛ גבי איש ואשה, ואז אף כאן נאמר על איש ואשה, אבל כאן יאמר שלא לישא אותו, ולא שלא לבעול לו. ותחשב.
* קיד.
** גמרא יש לדון מהו הדין
לר“י אם כבר עמד ולרבה אם כבר שינה את הענין. נראה שלא די לשנות את הענין לרבה, שאם כן, היה גמרא דוחה, ”… לרבה נמי, ששנו את הענין.“ עדיין יש לדון מהו הדין לר“י בשעמד. ותחשב.
* קיד:
** גמרא דבר תורה -
לשון זה מעניין, שלכאורה, אין צד שישנה מדין תורה, ואין צד שכן הוא הדין, אבל רק מדרבנן. ותחשב על זה.
* קטז.
** גמרא עובדיה -
קשה, שאולי לא היה לו בן, וזה היה בן הבת. יש לומר:
1. כיון שנחלה משמש והולך עד בן, יש אותו טוב.[fn:24][fn:25]
2. אולי ”בן“ שאומר כאן אינו דווקא, ורק רצה לומר ילוד.
** לא עיין בה -
הפשטות הוא שאומר שלא עיין לראות התשובה לשאלתו. יש לדון אם ”בה“ היא השאלה או המשנה. ואין חילוק כל כך. גם היה אפשר לומר שלא עיין לראות מה היה שואל, שכיוון לומר שאלה אחרת, אבל לא דק, ושאל את זה במקומו. אם כן, ”בה“ בוודאי קאי על השאלה. ותו"ת.
* קיז:
** גמרא ונתתי -
לא הבנתי למה מניחים שום יחס בין שני הפסוקים.
* קיח.
** גמרא מעינא בישא -
היה אפשר לומר שחידושו הוא שאין בבני יוסף עין הרע. יש לדון, שיש קרא אחר (שני קראי) שאומרים כן.[fn:26] יש לדחות שלא קל לדרוש אותם קראי; אף יהושע לא ידע לדרוש אותם.
* קיח:
** גמרא מתלוננים שבעדת קורח -
ואם תאמר אם כן למה צריך לומר ”מתלוננים.“ ויש לומר שבלי זה, לא היינו מרבים המאתיים וחמישים איש, אלא הוה אמינא שהוא רק עדה מיוחדת של קורח, שהיה הוא ודתן ואבירם. ותח‛.
** וידגו -
היה נראה לומר שזכה מפני ששמר את עינו. עיין בסנהדרין שאומר פשט אחר (חושב אני שכן ראיתי).
** אחי דאבא -
יש לדון איך תנא קמא (החולק על ראב“י) מונה עשר. אולי לא חולק על ראב“י.
* קיט.
** גמרא נטלו חלק -
ואם תאמר אולי לא נטלו חלק בכורה, אלא היה עוד אח לאביהם. ויש לומר שרק מניחים אחים כשיש לנו קראי מיותרים, כמו שאומר גמרא.[fn:27]
** וכך היה רבי שמעון -
מעניין שמשנה את שמו כאן לקרוא לו רבי. ותו"ת.
** עשרה -
ק"ק למה מנה של אחים, ומנה עשר, ולא דילג של אחים ומנה שמנה או תשע. ותחשב.
** וראויה היתה -
לכאורה, זה לא תלוי במה שאומר שלא ידע משה. ואולי אמר שלא שכח משה, שאילו שכח היה נענש, אלא לא היה כבר נאמר לו.
* קיט:
** גמרא מאי קא מסתפקא -
כמובן, צריך ביאור על איזה צד יהיה זה מובן, שבוודאי הוא קשיא, שמניח שמה שנתרץ למה לא היה ראוי הוא קשה. ויש לדון, שאולי אין הכי נמי, ורק מקשה על צד זה כיון ש הוא ת‛ גמ‛. גם יש לומר שאילו אמר גמרא שבנחלת הארץ, היה הדין חלוק, והיה בכרות אף בראוי, אז לא היה קשה.
** מורשה -
מעניין שיהיה משה מסופק בפירוש קרא שהוא למד כבר מה‛. לכאורה, צריך להיות שלא הבין אותו כראוי כשלמד אותו מה‛, אבל זה מוזר לומר. ואולי ה‛ לא פירש לא כל כך באותו קרא, אלא אמר שיפרש אותו קרא לאחר זמן (במעשה של בנות צלפחד).
** נעשה להם נס -
וצריך לומר שהן ידעו שיקרה להן נס, וגם מי שנשא אותן ידע (ולכן נשא אותן). נראה שאולי הנס שקרה לא רק היה שהולידו, אלא שחזרו להיות ילדות, כמו שאומר גבי יוכבד.
** לפני משה… אמרו -
לשון רבים מעניין, אבל נראה שקאי על כולם, ומפני שאחריו אומר נשיאים. ותו"ת.
** רש"י אבא חנן -
עיין בגמרא יומא שמביא ראיה שיש לכבד תלמיד במקום רב, ודוחה ששם כולו כבוד של רב הוא. נראה שאין זה קשה על זה, שדנים מתי אומרים כן, ומה שאומר שם הוא רק שכיון ששם כולם עובדים את כה"ג, הכל כבודו, אבל כאן, אולי אינו כן. ותחשב.
* קכ.
** גמרא הותרו לינשא לשאר שבטים -
צריך ביאור למה היו חלוקים משאר נשים.[fn:28]
* קכ:
** גמרא צריך ביאור
למה בכל גמרא זה קוראים להתרת דברים בשם הפרה (ובפרט שגמרא יאמר לקמן מה שא"א לומר את זה בלשון זה).
* קכא.
** גמרא מאי דרוש -
יש לדון אם באותו יום דרשו כן או באותו יום כלו דור ראשון. אם נאמר כצד שני, מעניין, שלכאורה, שמחים על מיתת דור. ותחשב.
ודע שלכאורה, ידעו אז שהיה סוף דור, כמו שממשיך גמרא לומר שאז כלו מתי מדבר. אם כן, נראה לומר כצד שני. ותחשב.
** ממנו ולא מבנותינו -
מעניין, שלכאורה, הם תקנו, וידעו מה תקנו. אולי לא תלוי במה כוונו, אלא בלשון שאמרו, ואז בזה הוצרכו לדון. גם יש לומר ששכחו מה כוונו (שהיה דור אחר). ויש לדון, שלכאורה, העושים גזרה זה היו יכולים להיות קיים.
* קכא:
** גמרא דאמר -
לכאורה, זה שאומר על ברכת הטוב והמיטב רק מוכיח שהיה דבר טוב, ולא שמפני זה היה טוב. לעיל, כשאמר שחזר דיבור של משה, רש"י כ‛ שלכן היה שמח.
* קכו.
** גמרא הא דר“פ -
יש לדון מה אומר:
1. כשאומר דבר בשם רבא, לא אומר בשם מה ששמע ממנו בפירוש, אלא ממעשה.
2. לא אמר כן ר“פ בפירוש, אלא אמר דבר בביאור אותו מעשה. ותו"ת.
* קכז:
** גמרא נאמן -
צריך ביאור למה בדרך כלל מאמינים דיבור ראשון יותר מדבור שני. ותו"ת.
* קכט:
** גמרא דכשתי שדות -
יש לדון, שהוא אותו ממון, שהוא הנשאר ממנו.
* קלא:
** גמרא דלא תקשה -
יש לדון למה נקשה; ולמה לא נאמר, לאותו סיבה, שלכן עשו זה דומה לזה. ומשמע ש“לא תקשה“ רצה לומר שמי שטועה יקשה כן, ולא רוצים שיקשה. ותחשב.
* קלג.
** גמרא אמר ליה אין -
צריך ביאור מאי אהני בזה. ואלי רצה לומר שאמר כן על מעשה שהיה, ואז רק אמר ההלכה שכך צריכים לדעת. גם יש לומר שמחדש שלא אמר לשון ירושה, ואז ח’ לומר כר"י.
** אי לית לה -
לשון זה מעניין, שלכאורה, היה לו לומר, ”כיון שנחית…,“ שזה הסברה העושה דין זה. מה שאילו לא היה לו, היה מוכרח שלא היה לו אותו אילן לכאורה, הוא רק תוצאה מסברה זה. אם כן, קשה למה מזכיר אותו.
** אי סברה לך -
לכאורה, היה לו לומר, ”יש לך לומר שהל‛ כר“י,“ ולא ש“אי סבירה לך…,“ שכבר גילה דעתו שכן סובר.
** אלא לשון ירושה -
מעניין שלא אומרים שכיון שפסק אותו גילה שהוא מתנה, ולא ירושה. אולי כך הוא קושיית גמרא ש“הוא פסקיה,“ ואז מתרץ שמניחים שטעה. ותחשב.
* קלג:
** גמרא איכסיף -
עיין גיטין עז: שהכסיף ר"ע את רבא.
** דאמירתו -
היה ת"ח, אף שלא היה נוהג כל כך כשורה.
** ליכא למשמע -
יש לדון למה לא, שנשמע שהוא מחלקת של שני הלשונות. נראה שמסופק אם חולקים אליבא דרבנן, או שאחד כר“ש ואחד כרבנן.
** בראשו -
יש לדון ראשו של מי:
1. של הנותן. רצה לומר, לא היית מרוויח כלום. מה שלא אומר לשון ”ראשך“ הוא שלא רוצה לומר קללה על חברו. ויש לדון.
2. של המקבל (ולא רצה לומר כן על עצמו), שהוא נתן לו לאכול. יש לדון, שלמעשה לא גרם לו קנין, ואז לא עשה כלום.
** שמאי -
מעניין שהיה מדבר עמו בלשון זה, כיון שהיה חבר של רבו. וראינו שכשת“ח הם יודעים בברור שהם נכונים, אומרים כך (כמו שמואל לר“ז (”אפס זכריה“) לעיל). ותחשב. ונראה שלכן נקרא הטחת דברים.
* קלד.
** גמרא קטן שבכולם -
במקום אחר, דיננו אם היה קטן של העשרים או של שמונים. נראה שלשון "כולם" משמע כצד שני. ותחשב.
** תלי -
נראה שמה שמצאנו שהיה ר"י רגיל לומר כן הוא מפני שהיה בקי בברייתות (כמו שקורא לו גמרא בסוף הוריות, ובמק“א, סיני).
** משלי שועלים -
גם מצאנו במק"א משלים של שועלים. צריך ביאור למה יש ענין שועלים אצל משלים.
** רש"י במקלו -
כיון שעברת- אם כן, חוזר למת, ויחזור ליורש. אז, יותר טוב למת שיחול, וירצה באותו מתנה. יש לדון אם זה בעיה, שלמעשה לא נתן על דעת כן. ותחשב למה לא יעשה כן. ואולי האמין שיעשה כמה שאמר. אז, קשה למה נתן על מנת כלל.
** הטיח עלי -
מילתא דבדיחתא- אין זה כל כך בדיח. נראה אולי שמה שבדיח הוא שמטיח עמו דברים כמו שעשה לו, שקורא לו ”בן עוזיאל“ בלשון גנאי כמו שקרא לו, ועל שם זה אומר שהטיח דברים. ויל"ד.
* קלה.
** גמרא אחונא -
יש לדון למה פעם אחת אומר ”אחונא,“ ופעם אחר אומר ”אחינו.“
* קלה:
** גמרא ואין שטר לאחר מיתה -
אין זה ראיה, שלעיל שניהם הסכימו לפסק דין.
* קלו.
** גמרא בעי מינה -
קשה ל"ל שאל ר"ה עצמו. נראה שר"נ היה יותר קרוב לו כיון שהיה תלמידו (ואולי חתנו (עיין ביבמות בהערל בסוגיה של סריס)). זה לא מבאר ל"ל שאל ר"ה, אבל מבאר למה איזה בעיה שיש בשאלת ר"ה אולי לא יהיה בבעית ר"נ.
* קלו:
** גמרא במקום נפשיה -
מעניין, שבדר"כ אומרים שהנותן מתנה בעין יפה נותן.
* קלז.
** גמרא המשיא עצה -
מגמרא משמע שאף רע למכור, ולא רק להשיא עצה. חושב אני שלא כ’ כן רשב"ם. ותחשב. ואולי מיירי כשאחר השיא לו עצה (יש לדון, אז, ל"ל אמר, “כאן כשלא השיא עצה"), והוא רע כיון שאז נמצא שהאחר גרם רע לשני. ותחשב.
** ממאי -
הוה אפשר לומר שיש סיבה לחזור מזה, שאולי אחר ששמעה מרבא הסכים לו, כמו שמצאנו בכ"מ. גם יש לומר שכיון שהלכה כרבא, מסתמא כן סובר אביי. ותו"ת.
** לשוינהו איסורי הנאה -
קשה ל"ל, שבא לו הנאה ממנו בעשייתם תכריכים, ואז ל"ל יתן לו לזה. אין לומר שהוא מפני שאחר כך אינו מותר, שלכאורה, יכול לאכול אותם נכסים, אף שאז חברו לא יוכל להנות ממנו. ויש לדון, שאולי לא אפשר. לא נראה, שיכול למכור. ותחשב.
* קלז:
** גמרא מכרה או אכלה -
זה מעניין, שלכאורה, צריך לומר שנתן לו קנין גוף, שיכול לקיים בו מצוותו. אם כן, קשה למה זה תלוי במחלקת של רבי ורשב“ג. ונראה שאולי כיון שאמר ”אחריך,“ כאילו גילה לו שההגדרות יהיו דומות, במה שיכול, ל“אחריך.“ אז, הוה כאילו התנה שלא יכול לאכול או למכור. ותחשב.
* קלח.
** רש"י כאן בצווח -
שני לשונות שאומר (אין מזכין… חוב הוא) אלו סותרים, לכאורה, שראשון אומר שהוא זכות, אבל אי אפשר, ושני אומר שהוא חוב. נראה שזכות רצה לומר דבר שהוא זכות לרוב בני אדם. נראה שזה יותר טוב אם נאמר שכן הוא לענין סיבת דין זכין, וכשאמר שהוא חוב, זה רק מבניעה על דין זכין.
** כאן -
ק"ק למה צריך רש"י לתת טעם, שלאיזה טעם שלא רוצה, הרי לא רוצה. ויש לדון אם זה בעיה, שאשי אולי בא לת‛ איך לא ירצה. גם יש לומר שבלי זה צריך לומר שבאמת, רוצה, ורק לא רוצה לומר כן.
* קלט.
** גמרא ניחא דלא ננול קמ"ל -
יש לדון מהו הציור- שנראה מה רוצים אחרים. אולי אינם שם.
* קמ.
** גמרא אמר רבא -
עיין איך מפרש רש"י את זה. קשה ל"ל רק אמר שמועטים הוא אי לא די לבנות. יש לומר שמחדש שאף זה ברשות בנות (שאף כעין זה נחשב מועט, ולא נחשב שנתמעטו).
** דאילו מתה -
זה מוכיח כצד שני ברש"י, אבל אולי כך הוא הסיבה שהוא רק את"ל. ותו"ת.
** רש"י ונתרבו -
ק"ק ל"ל לעיל אמר שני ציורים, ועכשיו אמר רק אחד. לכאורה הסיבה הוא שהיה משמיע לנו דין לעיל, וכבר השמיע לנו, ואז אין צריך לכופלו. ותחשב בביאור זה.
* קמ:
** גמרא מה בת… -
זה גם כן אומר שאלמנה ממעטת.
** וראוי -
יש לדון אם הענין הוא שאז יותר יש צורך שלא יטרח לממון או שאז הוא חשוב וזוכה בנכסים.
** דוחים -
לא הבנתי עדיין ל"ל אמר שזכרים ונקבות דוחים אותו.
** רש"י האומר -
ולא מת’- עיין שם, שיש שמתרצים אותו שם.
** ה"ג -
נראה שתלוי במחלקת ר"י ור"י באם וא"ו צריך "יחדיו.” ואולי לשון משנה חלוק מלשון תורה בזה.
** יורש את הכל -
לא הבנתי למה מניחים שבת יותר קרוב ממנו. ואולי הוא לאותו סיבה שבן קרוב למת (אלא שאין ידוע לי מהו אותו סיבה). היה אפשר לומר שבן אינו יותר קרוב, אלא חשיבות זכר עושה שנוטל. יש לדון אם זה שייך כאן.
* קמא.
** גמרא ראוי -
לשון "ראוי" כאן מעניין.
עוד קשה, ששם יורש כמו בן, שכל בן, כמותו, לא יורש כלום. כאן, אינו כשאר בנות. ואולי זה לא יד, שלא רק אומר שהוא כבן, אלא שיורש כמותו. ותחשב.
** ואין העברה -
צריך ביאור איך רואים את זה מאותו קרא.
** דלא שלטא ביה -
לכאורה, זה גלגל החוזר. ויש לדון, שאולי הוא משום שלרוב בני אדם, “בוצינא טוב מקרה.”
ונראה שאולי לכן אמר רב חסדא שרצה בבנות- שילד בנים, ורצה שלא יהיה לו עין הרע.
** בנות -
יש להעיר שיש ציורים שנזכרים במשנה שאדם רוצה יותר לתת לבן (שמתנה רק לתת לו), ורק שבציורים שרוצה רק לתת לבת, נותן יותר. ותחשב. ואולי הוצרך להזכיר אותו ציור כדי להודיע אותו דין, אבל לא הוצרך לומר שנותן יותר ממון לאשה. ותחשב.
** בכל -
הראיה בא ממה שקורא אותו ברכה, ולא מה שהוא הכל שברך את אברהם, שלא היתה כל, אלא כך היתה שמו. ותחשב.
** עינא בישא -
לכאורה, זה לא יועיל ליותר מבן אחד, שאחר אותו אחד ישלוט עין הרע. ויש לדון.
** ליתזלן -
אם כן, זה שווה, לכאורה, לתירוץ ראשון. ונ’ שאומר שאז אין צריך לומר שיש שום טוב במה שממונו הולך לבנו.
** רש"י לדידי -
אינו מוכיח כך- יש לדון מה לשון זה אומר:
1. לשון זה מוכיח נגד זה. אף שאין לשון שאומר רש"י אומר כך, כן רגילים בני אדם לדבר (אומרים, ”אני לא אוהב את זה“).
2. אולי רצה לומר שלשון ”לדידי“ לא מוכיח כלום על זה; אם כן, לא היה לו לומר אותו על צד זה. אז, קשה על צד זה. ותחשב.
* קמא:
** גמרא הוה מזכה לעובר -
קשה למה צריך לומר דהרי מזכה לעובר, שזה פשוט. ותחשב.
** מאיליה -
משמע שיש כבר שם מי שיכול לקנות. אז, צריך ביאור למה אי אפשר להקנות לו. ותחשב.
** רש"י למעוטי -
גם יש לומר שמקשה שמשנה לא משמיענו כלום,אם לא אומר שרק באלו, ולא בציור אחר, נוטל.
גם יש לדון למה מניח רש"י שכל אלו הם בציור אחד. ואולי מקשה למה לא ישמיענו דין זה כשאומר כולם בציור אחד. ויש לדון, שאולי זה לא מצוי.
** אימור - ל
מלשון רש"י, וכן מגי‛, נ‛ שלא פירש שהבעיה הוא נתינה
דבר שלא בא לעולם, אלא שעובר לא בא כלל לעולם. ויש לדון בזה, שלמה פרי יותר בעולם מעובר. ותחשב.
עיין
ברש"י
לעיל שלא אומר כן. ותו"ת.
* קמב.
** גמרא שמעו -
קשה, שנאמר שחוששים שאין זה נכון, כמו שחשו כן כששמעו שאין לו בנים. ויש לומר שלא שמעו כן, אלא רק לא שמעו שיש לו בנים.
** יש לדון למה
אין כל קנין של דבר שלא בא לעולם ברירה, שהוא אומר דבר על שם קרק‛ שיבוא לאחר זמן. לרש"י, אולי אינו קשה, שאין חפץ אחר שנאמר שדעתו עליו. יש לדון, שאולי דעתו על חפץ שיבוא מצד זה של העץ, ולא על זה שבא מצד אחר. נראה שאולי יש לומר שכיון שבשעת חלות, אותו קרק‛ הוא שם, יכול לחול. אם כן, אם כבר בא חכם לפני שבת, ולא לפני דיבורו, חל. זה בוודאי אינו נכון לרש"י (שתלוי במה כוון כשאמר כן, לכאורה,. ויש לדון.). ויש לדון אם הוא אמת כלל. גם יש לומר שכאן אין שום צד אחר, שאין חפץ אחר שיש לו אותו קרק‛. לכאורה, במילים יותר טובים, זה אומר שברירה לא חל כיון שיש קרק‛ זה לשני חפצים כיון ששניהם יכולים להיות כן לעתיד. אם כן, צריך לומר שאם יכול לחול על שניהם , יכול לחול.
** ורבא אמר -
צריך ביאור למה אין כל תנאי כך.
** רש"י ורבא -
לא הוה- אם כן, קשה מה לנו אם נמצא שהיה לו בן או לא, שבלאו הכי, רפה ידיו. אולי אם לא נמצא כן, לא מניחים שפרו ידיהם. ותחשב. אם כן, אם לא היה אפשר להם כלל לדעת על אשתו שהיתה מעוברת, לא נאמר שרפו ידיהם, אף אם מולדת. אז, יש עוד נפק"מ.
** ומשנינן -
יש לדון למה לא ינקוט בנימין, כיון שבאותו יום שנולד מתה רחל. אולי כיון שלא מת בנימין באותו יום, לא נהנים לומר שמו. ויש לדון.
** בן יום אחד -
היה אפשר לדחוק שהוא אגב שאר דינים שבמשנה. ויש לדון. וצריך לעיין שם במה לא אומר.
* קמב:
** גמרא יכיר - .
שאל לי א.ל.י. מהו הדין אם האב סומא. אולי הוא עדיין יכול להכיר. עדיין יכול להיות שוטה. וצריך לדון מה בא בכלל ראוי, שלכאורה, אין אומרים שאם הוא במדינה אחרת אין אותו דין. ויש לדון, שאומרים כן על אלם
** יש לדון
למה אומרים ראוי לבילה על זה, כיון שאינו קדשים, ואז יעכב בפעם אחת.
** רש"י עיר שנולד -
גם היה יכול לומר ששם דר.
** נכסי -
גם יש לומר שלא קאי כאותו שיטה.
גם יש לומר שאם לא נתעברה, אין קורבה זה מהני, שאינו בעולם כלל. ויש לדון.
** בריה קשישא -
יש לדון למה צ“ל מאשתו ראשונה. ונראה שאולי מניח רש"י שאמר כן לה כדי שתרצה לנשא לו. עדיין אפשר שמחזיר גרושתו.
* קמג.
** גמרא רבי -
היה אפשר להביא מדרת רבי עקיבה מאותו קרא בעבודה זרה (י:).
** על ידי כולם -
לכאורה, יש שני דברים לדון כאן (לומר שלא יחול):
1. לקיחת הקידושין (שקנתה לכולם).
2. חלות קידושין (שמקדש לכולם).
** היינו דחזאי -
יש לדון אם אומר שלכן ראה אותו או אם תמה איך זה הסיבה שראה אותו כיון ששאל תיובתא חלושה כזה. ותו"ת. ועיין ברש"י.
** היינו -
יש לדון אם אומר שראה בחלום שישאל תיובתא, או אם אומר שלכן ראה אותו- כיון שישאל תיובתא.
** הראויה -
מעניין שאין שום אחות מתקדשת, שנאמר שאחד מתקדשת. צריך לומר שכיון ש“הי מינייהו מפקת,“ כל אחד לא נכלל. ואולי כיון שלא פירש, נהיה מסופק, ועל כל אחד אולי לא תהיה נשואה לו, ונמצא שהיא אסורה לו בביאה, שדילמא היא אחות אשתו.
** אהרן -
ק"ק שאולי קרא מחדש שאהרן נוטל אף אם אינו משמרתו. אולי זה לא נשמע מן הקרא (אבל הוא תוצאה של הדרשה, שכיון שנוטל יותר מחילוק משמרה, מסתמא אין חילוק משמרה שייך לו). גם חושב אני שכבר יש קרא לזה. גם יש לומר שזה קודם שנתקנו משמרות. ועיין בסוף תענית. עדיין צריך באור, אז, למה לא תקנו משמר שלפעמים יכלול כהן גדול ולפעמים ימעט אותו. ותו"ת.
** הוה עובדא -
לא משיב להני.
** רש"י ואסטרוגי -
עשירים- לולי זה, היה נראה לומר שתלוי בכמה איסטרוגי יש וכמה אאבולי. ותו"ת.
* קמג:
** גמרא מעיקרא לקרבן גדול -
צריך ביאור למה מניחים שרוצה זה.
** והלכתא -
מעניין שכאן:
1. רבה לא חולק.
2. יש אחרים שסוברים כרב יוסף. ודע שדנים אם אומרים כללים זה כשאחרים סוברים כשיטות אלו.
** קרו אינשי -
לכאורה, שואל לא רק אם יכול להיות שקורא לו כן, אלא אם נוכל להניח שכן עושה כדי להפסיד הבן. ותו"ת. ואולי אף אם רק יש שקורא, ואין הכרח שלזה מכוון, לשון רבים יהיה הכרח, ואף אחר דרשת גמרא לקמן. גם יש לומר שרק דן אם הוא וודאי לבן, ספק, או וודאי אף לבן בן.
** נכסאי -
יש להעיר שאם לא רצה לתת לבן בן, לא היה לו לומר כלום, שילך הכל לבנו. ואולי אף יש לו בת הבן של בן המת.
** מותר -
אין זה כל כך ראיה, שנדרים הם לשון בני אדם.
** מותר -
אין זה כל כך ראיה, שיש לומר שיש חילוק אם יש לו בנים מאם אין לו אלא בן אחד. ויש לדחות:
1. סובר גמרא שאין חילוק. אולי זה מפני שכבר אומר קרא לשון בנים על בן אחד.
2. סובר שממה שמשנה נשנה סתם, צריך לומר שהוא בכל ציור, ואף אם יש לו רק בן אחד.
** רש"י נכסיי -
וגם בנות- לא צריך שהיו לו בנות, ואף יכול שיש לו רק בת.
* קמד.
** גמרא אחולי אחלה -
יש לדון מה קורה:
1. כשאומרת כן, לא עושה חלוקה עד שתבוא לה שכר.
2. כשעושה כן, מוחלת, אף שחולקת. יש לדון למה תחלוק.
* קמד:
** גמרא לפי ברכת הבית -
יש לדון איך נחשוב כן:
1. נראה בטוב שבא, ונחלק לפי בני אדם.
2. נראה בשינוי הטוב ממה שהיה שם למה שיש עכשיו.
* קמה.
** גמרא תנו לי בעלי -
לשון ”ואשמח עמו“ מעניין, שמה שאשה כפופה לבעל אינו בפרט לשמח עמו. ותו"ת.
** לימא -
רצה לומר, ואז יהיה לנו תירוץ אחר.
* קמה:
** גמרא תרעומות -
איני יודע אם יש לנושא תרעומות על שלא שמע חברו, או שיש לחבר תרעומות על שלא הודיעו נושא. ותחשב.
* קמו.
** גמרא כל ימי עני רעים -
יש לדון אם מפרש את הקרא כפשוטו או רק מקשה שנראה שלומד ממשל שאינו נכון. ותו"ת.
** ושתה -
נמצא שהיה עשיר שנשא אשה, ונתנו לו מה לשתות, והוא מת. אם הייתי פולי“ס דיטאקטי“ב, הייתי חושב שאולי היה קצת הומוסיי“ד בזה. ותו"ת.
** אין נגבים -
יש לדון אם זה כשאכל. מגמרא נראה שהוא רק כשאכל.
** דבלו -
קשה לל"א דבלו. אולי בא לחדש שצריך להיות ראויים ושבלו.
* קמו:
** שכיב מרע -
אין לומר שמניחים שחושב שימות, ולומדים ממה ששייר שלא חושב כן, שאולי עושה כן כיון שרוצה בירושה. אלא צריך לומר שמניחים שחשוב כן כיון שנתן הכל., וצריך לומר שחושב שימות. יש לדון ,שיודע שאם חי, חוזר. זה, אז, גלגל החוזר. ותחשב.
** כרבי שמעון שזורי -
יש לדון למה יותר טוב. אולי הוה ליה לומר שניהם . גם יש לומר שפוסקים כרש"ש יותר בהדיא (אולי), ואז יש לומר שהוא כמותו.
ונראה לבאר על פי מש"א תוד"ה רש"ש, שיש לומר שכיון שדי לו באינונ מוכרחת, יש לו לומר שהוא אף כרבנן של רש"ש. אם כן, היה לו להביא ואתו ברייתא שאין בו אף חולק על נקודה זה.
** בתר אומ’ -
יש לדון אם החי’ הוא שמניחים שכן רוצה או שאין זה דברים שבלב. כמובן, גם תלוי באם דברים שבלב אינם דברים רק מפני שלא מניחים שחושב כן, שאז, כמובן, שני הצדדים שווים.
** רש"י נפלה -
אם ימצאנה- מעניין, שלכאורה, לא נמצאת בעל מום. ויש להעיר שמי שנושא על תנאי, אז, לא יורש את אשתו. ותחשב.
** שוב אין לבעל פירות -
יש לחלק ששם עומד לגרשה, אבל כאן מת, ואינו עומד לכך. ותחשב.
* קמז.
** גמרא שהיא מן התורה -
מעניין שאומר זה למקור שהוא מדאו’, ולא למקור שחל. אולי רצה לומר "מתנת שכיב מרע, שהוא מדאו’,….” עדיין מוזר לו לומר כן.
** ויצב אל ביתו -
לכאורה, לא היה אז שכיב מרע. אולי מניחים שהמית את עצמו עד שהיה שכיב מרע (רצה לומר, שהמית את עצמו עד שעה אחת קרוב למיתתו, ואז צווה). ואם תאמר למה יעשה כן; יצווה קודם. ויש לומר שלא רצה שבני משפחתו ידעו שימית את עצמו. עוד יש לומר שידע שאז לא יצטרך לקנין. ודחוק.
** שלשה דברים -
לכאורה, זה כדיחוי גמרא שרק צווה להם מה לעשות. ויש לדון, שאולי הוה אמינא סבר שלשון ציוי אומר שניהם (רצה לומר, בהכרח שניהם, ושמוכרח שממון בכלל. נראה שאולי משמע שציווה כל ציוויו, ומסתמא היה ממון בכלל.)
ונראה שאפשר שרש"י מכוון לזה כשאומר ש"כך היה קים להו.” נראה שכוונתו הוא לומר שאין לומר שכן רואים מן הקרא, שאז אין לדעת שציווה לגבי ממון. אז, צריך לומר שידע כן מגמרא, והמביא ראיה לא היה לו אותו לימוד. ותחשב.
ויש להעיר שלפי רש"י נמצא שהיה גמרא קים להו נגד אותו ת‛. נראה שאולי אין זה כל כך קשה, שרק קים להו שכן קרה, ומחדש שזה פי‛ הקרא (יש לדון מהו ההוה אמינא שלא יכול להיות פירוש הקרא). גם יש לומר שחשב שמסתמא לא מדבר בו קרא, שכבר קים להו. דוחה שעדיין כתבו, או שרק קים להו ממי שבאר קרא כן.
** במלכות בית דווד -
קשה, שזה כבר בכלל מחלקת. אפשר שהוא אף אם אינו מחלקת, וכבר נכבש בית דווד, אין למרוד בהם, שסופם לעלות[fn:29]. ודחוק. גם יש לומר שאם בין כך ובין כך יהיו במחלקת, יעשו כבני דווד.
** רש"י הא לן -
גם היה יכול לומר שכשיש הרבה בא“י, אין הרבה בבל.
** כולה -
נ‛ שמקורו הוא שיש שנה שהוא קצת כזה וכזה. יש לדון, שאולי לפעמים אין חמה או קר באותו יום. יש לדון למה אז אין כל השנה כן. ויש לדון. אם גם יש לומר שלפעמים מקצת היום כך ומקצת אותו יום כך. עדיין יש לדון, שאולי היה לכל יום להיות כן.
גם יש לומר שרש"י יודע שלא קורה (על כל פנים בשנים שראש השנה כך) שיהיה כל השנה כן.
* קמז:
** גמרא כשל תורה -
נראה שלהפך לכן אי אפשר למחול, שלא הוא עושה הקנין, אלא רבנן עשו אותו. ותחשב.
** א"א בשלמא -
לא הבנתי למה יהיה חלוק משאר מתנות דאורייתא.
** רש"י לתפלתו -
לכאורה, רצה לומר שיהיה תפלת שווה (או, על כלל פנים, יותר קשה) להתפלל שיהיה נגד מה שאומר ראש השנה.
** מתנת שכיב -
עצה טובה- קשה, שגמרא לעיל כבר דחה. ואולי מפרש אותו גמרא כך.
דעתו של חולה- מעניין שחוששים לזה, שמה לנו אם לא חל. ואולי יש לצרף שניהם, שמחמת אותו שאגב שלא יחול ימות. גם יש לומר שהוא כעין מצווה לשמוע לדברי המת.
** מחול -
דמלוה- יש לדון בזה, שאם ענין מחילה הוא שעושה כאילו קבל, אין קבלתו מהני, ואז לא יכול למחול. ותחשב מהו צד זה.
דכפייה- מעניין שהיה מי שכפה לר“א, שהיה גדול בתורה ועושר.
* קמח.
** שייר -
קשה מה לנו אם שייר, שיהיה כנותן לאחר. ונראה שיש נפק"מ אם הוא כחוזר ליתן, שאז ראשון לא יחזור.
* קמט.
** גמרא ולודי -
ק"ק איך זה מותר. ואולי יותר קל לצד שכל הודאה הוא כעין מתנה.
* קנ.
** גמרא אמר איהו -
לכאורה, רצה לומר ”ואמר איהו….“
* קנ:
** רש"י אמר נכסי -
ואם תאמר מה אומר כשאומר שתרגומו שווה; אין חידוש בזה, שתרגום כולל כל אלו מפני שתרגום הוא, וזה כולל כל אלו. ואם אינו פשוט, אז קשה איך מוכיח מכאן. ויש לדון. יש לומר שאינו פשוט, שאולי אין תרגומו כל כך מדוקדק, אלא רש"י אומר שידוע שזה האמת, שהוא מדוקדק. אם כן, לא מוכיח אותו. עוד יש לומר שחי‛ גמרא הוא כמה מעשות צריך, ולכן יש להוכיח תרגומו ממנו. ותחשב.
* קנא.
** רש"י דתנן -
לבדק הבית- הוה מצי להוכיח מכאן שממון נקרא נכסים.
* קנב.
** גמרא הרי הוא כמתנת -
יש לדון אם נתן שני כוחות אלו, אם התנה איך יתן אותו על פי מה שיקרה.
* קנג:
** גמרא ומה ספינה -
קשה, שכאן מת (ומוכרח שהיה דבר שהמיתו). ויש לדון, שצריכים להניח כן על מי שהוא בספינה, שאם לא כבר מת, ימות.
* קנד.
** גמרא ובפלוגתא -
עיין ברש"י איך מבאר את זה.
* קנח:
** גמרא בחזקת מי -
לכאורה, קאי על נכסי צאן ברזל.
* קס:
** גמרא נתרבה -
נצמא שאומ’ לשון ריבוי במקום לשון חומרא. ותו"ת.
** וכתב -
לכאורה, גמרא דורש מכפל הלשון, שאומר כתיבה וחתימה. אם כן, צריך ביאור איך גמרא דוחה את זה לומר שהוא עצה טובה, שעדיין קשה למה צריך לכתוב שניהם. ונראה שדורש מתחילה ממה שהקרא מיותר, ודורש, אז, שאומר שני מיני תנאים, ומבאר איך שניהם נשמעים מן הקרא. אבל, לשון כפל של הקרא איו קשה. ויש לדון ל"ל.
** תלוייה -
צריך באור ל"ל חוששים שיוסיף על התלוייה. ואולי כותבים בשטר שהוא תלוי. ק"ק ל"ל יכתבו מחק.
* קסג.
** גמרא על המחק -
לא הבנתי איך יש מי שיכשיר את זה, שבכל הנפק ימחק את כל השטר ויזייף עליו עדים.
** גייז -
אין צורך לו לגוז; יכול למחוק אותו. ואולי יש לחוש שיהא רשומו ניכר. אולי אז יכירו בו. ודחוק. גם יש לומר שיותר קל לגוז, ויגוז כל מה שיכול.
* קסג:
** גמרא שטר הבא -
לכאורה, אף צריך להיות שאין מקום בשיטה של עדים, שאי לאו הכי, יכתוב שם.
* קסד.
** גמרא ולשהייה -
יש לדון, שאז צריכים לזכור גם מה שזה הראשון היה לאחר אותו זמן. אולי אין להניח שנזכור בדיוק. ותו"ת.
* קסה:
** גמרא ועל דא -
לכאורה, קאי על כל הצדדים.
* קסו.
** גמרא דינרי זהב -
צריך ביאור איך זה ראיה, שאומר ”זהב.“
** נכנס לבית דין -
צ“ב למה לימד כן בבית דין, ולא בבית מדרש. ותו"ת.
* קסו:
** גמרא חנן -
יש להעיר שבאמת יש שני חלוקים, שאחד הוא סופיי. נראה שהענין הוא שישכח שיש אותו אות, ולא שישכח לכתוב אותו.
* קסז:
** גמרא מחזיק -
לכאורה, היה גמרא יכול להקשות שיוסף ילך לעיר אחרת- וזהו.
** שני יוסף בן שמעון -
צריך להזכיר האשה, ואז כ“ז אם גם שם אשתו שווה.
* קסח:
** גמרא רישומו ניכר -
עיין במה שבאר רש"י. עדיין צריך ביאור למה יעשה כן. ותחשב. אולי יטריח אותם אם לא רואה שכותב אותו, אלא אלף בית. ותחשב.
* קסט:
** גמרא אדברי -
קשה, שיודעים ממי ייקח, ולו ניתן שובר.
** כל זמן -
אם הוא רק קנין לזמן, יש לדון איך מוריש.
* קעא.
** גמרא שיכוף -
זה לא יהני אף אם אחר שפורע את כולו, נותן שובר. ואולי אז יכול לומר לו שאם יפרע, יקרע את שטרו, ולא יכתוב שובר. גם יש לומר שעושה שיכול לטעון, אם אבד שטרו, שהוא פטור, ולא צריך שבועה.
** עונתו -
ואם תאמר אולי הוא מוקדם. ויש לומר שכמו שלא מניחים שסםת שטר מוקדם ואז פסול, אף גבי זה לא מניחים כן.
* קעא:
** גמרא שטרא אירכס -
משמע שרק אם אירכס כותבים. ואולי רצה לומר שבלי זה היה עושה לו טובה זה. יש לדון למה אומר את זה לו.
** אבד שטרו -
משמע שיכול לחייב בלי שטר במה שאין שובר. צריך ביאור, שיאמר שאבד שוברו.
* קעב.
** גמרא לא משוינן -
קשה; מה נח‛ יותר טוב לו, שהם סותרים. אולי רצה לומר שכיון שהוא טוב לאחד, אי אפשר לשום אחד מהם לכפות. לא משמע לשונו כן. אולי כיון שאין כל כך בעיה, שבין כך ובין כך טוב, אי אפשר לשנותו. ויש לדון למה צריך לזה.
** חד בר חמשים -
ק‛ ל"ל נאמר כן בכל ציור של רבא גם כן. ואולי אין הכי נמי, אלא סיבה של רבא יותר טוב. ויל"ד.
* קעב:
** גמרא היום -
צריך ביאור מה מוכיח מזה. נראה שחוץ מבעיה של נפילה, היה בעיה אחרת, והוא איך כ‛ השם בפירוש די. מכאן מוכיח שזה נחשב בפי‛ די. מעניין שזה יהיה בעיה, שלכאורה, רק צריך שהשטר מגיד, והרי הגיד. ויש לדון, שרק הגיד בצירוף דעת של מי הוא אותו איש שאוחז בו. ותחשב.
* קעג.
** גמרא אותיות -
ק"ק ל"ל הביא רש"י בפסקו לעיל מה שכאן יש סתם משנה שאומר שקונה.
** להביא ראיה -
נראה שאולי אביי לשיטתו, שחושש שנופל. אף שלא חושש כן כשצריך ליפול מאחד מיוחד, יש לומר שכיון שחושש לו בציורים, יכול להצטרף לשאר חששות. ותו"ת.
** צריך ביאור למה
”שדה…,“ יש לו משמעות של ”חוב שיש…,“ שלכאורה חלק מאותו משמעות הוא מה שאומר, ”חוב.“ ותו"ת.
* קעג:
** גמרא אנכי -
ק"ק למה אומר אותו לשון כיון שקבלנות הוא.
** לא יפרע מן הערב -
קשה, אז, מתי ישלם ערב אם לא מתנה כן. זה אומר שלכאורה, אין חילוק בין אם מתנה כן לאם לא מתנה כן (אולי אין הכי נמי, ואינו ר“ע שדורש לעיל לישנא יתירא), שבשניהם צריך לגבות מן הלווה ראשון. אולי יש נפק"מ אם יש לו נכסים, אבל אינו שם. יש לדון למה אין בית דין מורידים אותו לשדה שלו. גם יש לומר שיש נפק"מ אם לוה אינו שם, ולא יודעים אם יש לו נכסים. ותחשב.
* קעד.
** גמרא מאן חכים -
תחשב על זה, שבין כך ובין כך משלם מנכסיו.
* קעד:
** גמרא אבא לגבי -
מעניין שלא רצה לתת ממון כאן, אף שהיה צריך לו.
** התקבלתי -
לר“ה בדר“י, קשה מה לנו אם כותב כן.
* קעה.
** גמרא להשביע -
יש לדון, שהוא מת, ומה לו בזה, אבל בניו חיים. ויש לדון, שלהפך, לא ירצה לגרום עיין הרע לעצמו כשקרוב הוא למות.
** הא דמקיים -
אם כן, לכאורה, פשוט הוא. ויש לומר שאומר שלא יכולים יתומים לטעון שפרע.
* קעה:
* Lגמרא
** זיבורית -
יש לדון מה יהיה אם אין שעבוד. לכאורה, אז תורה רק אומר שישלם, ולא גילה ממה ישלם. תיקו.
* קעו.
** גמרא דלית ליה קלא -
צריך ביאור למה יותר טוב שהם לא יפסידו, אבל יורשים נפסדים.
** אין לומר
שעדות רק על ערב, שאין ערב בלי חיוב.
* Footnotes
[fn:1] רצה לומר, ואז אולי אף אם הוא חומש, חייב. אבל זה לא יתרץ בעיה ראשונה. ותחשב.
[fn:2] כיון שהגענו לזה, יש להשיב על קושיא שהקשינו בדיבור הקודם לומר שסבר שהיה אפשר לדחוק בדין שני של משנה שמיירי בציור שהוא פשוט, ורק כתבו אגב. רק כשרואים שרישא של משנה אגב יכולים להביא ראיה ממנו. ואם תאמר, איזה ראיה מביאים- הרי יכולים לעשות כל איזה שרוצים אגב, וממילא הראייה יידחה. ויש לומר שיותר מסתבר שרישא דווקא (כן אומר גמרא בזבחים. (עיין זבחים (צא:). עיין תוס’ כריתות (יב:)). ויש לדון, לכאורה, זה עדיין לא די להביא ממנו ראיה (שכמו כן רואים בכמה מקומות שגמרא יאמר "אלא מהא ליכא למשמע מינה,” שלכאורה, אומר שרישא וסיפא סותרים את עצמם, ואחד צריך להיות נתפרש על ידי חבירו, ובא דיוקו רק אגב לשון חברו, ואז אין לדייק. אם כן, קשה למה אין מביאים ראיה לומר שסיפא אגב רישא. אלא, צריך לומר שאין זה כל כך פשוט לגמרא, ואינו ראיה.) ותו"ת.ואפשר שאין הכי נמי, היה אפשר לומר כן, אלא שרצה לא רק לדחוק כן, אלא מביא ראיה. ותו"ת.
[fn:3] רצה לומר, יש אפשרות לשני דברים אלו כאן. אינו פשוט ששניהם כאן, שמי יימר שסתם בני אדם מניחים שזה טענה טובה, ומי יימר שלא יודעים בני אדם הלכה בזה. כדי שיהיה אותו דין, פשוט ש,על כל פנים, אחד מהם נכון, אבל אין הוכחה ששניהם נכונים. כוונתי בזה לדון איזה נכון, ולעורר שאם במציאות שניהם נכונים כאן, יש לדון מה יהיה הדין בציור שרק אחד מהם נכון. ותחשב על זה.
[fn:4] זה אומר שאולי כדי להיות דבר נחשב הודאה, צריך להיות יותר בפירש (יש לדון למה יצטרך לזה). אז, זה יעשה שרק אין לו טענה לטעון.
[fn:5] נראה שהוא זה:
[fn:6] ועדיין יש לדון, שאולי עושה אותו כדי להשיג גדולה, אבל לא שרוצה שה’ יתן לו גדולה מחמת זה, אלא שחושב שיראו בני אדם מה שעושהש ויכבדו אותו. אם כן, לכאורה, אין אותו בעיה שאומר רש"י בראש השנה שייך. ותחשב.
[fn:7] קצת תלוי באם מה שבא לו ד"א אלו הם אם יש יותר צורך לו (רצה לומר, חלוקה נעשה כך- כל אחד נוטל הנאה שווה. אם לא יקח זה, לא ימלא צורכיו, ואז יהיה לו יותר צער מאחרים. ותחשב.) או שיש לו יותר זכות בחצר, שהיה משתמש עמו (והיה לו זכות להשתמש עמו) ביותר, שהיה לו שני פתחים. ותחשב.
[fn:8] כזה:    , ולא כזה:
[fn:9] יש להעיר שלזה לשון גמרא (“פורענות שיש בו אחרית") מדוקדק, שהענין אינו רק שבא אחרית, אלא שכבר הוזכר בפורענות. ותחשב.
[fn:10] דימה אותו למה שעשה אברהם פרייד שירה ממקרא של "איש את רעהו יעזרו ולאחיו יאמר חזק,” שמדבר בעובדי כוכבים שמזרזים זה את זה לחזק בעבודה זרה.
[fn:11] גם יש להעיר שאז צריך לומר כן אחרים אף בשאר שנאמרים בהם כל. מוזר שיהיה לכולם בת ויתנו לכולם שם מוזר לזה. ויש לדון.
[fn:12] או שלהפך, לעולם אסור. ותחשב. ולא מסתבר שיהיה אסור ופטור. ויש לדון, שגרמה אסור ופטור. ויש לדון.
[fn:13] רק רוצה אותו כדי שיהיה שה לשלוח לו, או כדי שירצה בעל הבית לשכרו (שהוא שומר ליותר זמן)
[fn:14] וממה שרש"י כאן אומר, משמע שאינם חד דבר. ותחשב.
[fn:15] ואז, מי שמחזיק צריך לחוש שהוא שם, ואז יש ריעותא דאחוי שטרך לשלש שנים.
[fn:16] ולכאורה, לא מסתבר לומר שתקנו כדי להודיע עצה טובה. ותחשב.
[fn:17] אם לא שאומר שהודאה הוא כנתינת מתנה, והוא כאילו אומר שנותן, אבל רק אם ירצה לאחר זמן. ודחוק.
[fn:18] יש שלש יכולתות:סובר כחילוק שאומר, ולא כחילוק של שמואל.סובר כחילוק של שמואל, ולא כחילוק שאומר גמרא לו.סובר כשני החילוקים.
[fn:19] באמת, אף לרש"י צריך להיוצ שאף מכוון לעשות כן, שאם לא כן, קשה למה לא אומר שהוא בנחלה דרבנן בפירוש. ותו"ת.
[fn:20] נראה שיהיה צריך להיות השני, שאם רק הראשון, לכאורה, לא יקנה דיוטא עליונה, שהרי בלשון ראשון רק קונה יכולת לעשות דברים שם (כמו לכרוע בור), אבל לא מה שהוא כבר שם. ותחשב.
[fn:21] אף שלא לכך נקרא כן, שרבה הוא רב אבא, עדיין כך יהיה משמעות שמו.
[fn:22] ואגב, יש להעיר שיש לדון על מה היה שאלת גמרא:הקרקעהארזשניהם
[fn:23] עיין בשיח שי שם.
[fn:24] עיין לקמן (סו“פ מי שמת), שיש לגמרא צד שבן הבן או בן הבת יורש את אבי אביו אף שלא מכוח אביו.
[fn:25] יש להעיר שיש לדון אם זה מהני, שאולי לא אומר אותו לשון על שם מה שקרה אלא על שם מה ששמעו (עיין באותו קרא). אם כן, צריך להיות שאותו בן כבר נולד. יש לדון אם זה קרה. ותחשב.
[fn:26] לכאורה, זה אי אפשר, שאם ידוע שדורשים כן, ידעו שיש עין הרע. ואולי יודעים כן בפשיטות אחרי שכבר הודיע לנו יהושע. ותו"ת.
[fn:27] באמת, ק"ק למה צריך הני קראי, שהרי קרא כבר אמר שהיו עשר חלקים, ואין עשר אלא אם כן נחדש שיש אחר. ונראה שכתב גופא כדי שנדע שרק היו שני אחים (או אח אחד), ולא יותר. ותחשב.
[fn:28] ואולי יש כעין מגו, שלא היו צריכים לטעון שיירשו. ודחוק.
[fn:29] כמו כן, יש לומר שאם יכל להיות neutral, לא יעשה כן, אלא יעשה כבית דווד.
