קכג:- לרבות קדשים קלים- הבשר והעור (ברש"י)- משמע שאימורים אינם של בעל. זה מעניין. [fn:1]
רובן בגזל- עיין ברש"י שכתב שרובם חשודים. קצת קשה איך ידע שלא לפרש שרובם עוברים בגזל. אמר לי א.ל.י. שאולי היה קשה לרשי איך שום אדם יגיד אחרי שרב בני אדם גזלנים הפסולים. אלא, צריך לומר שרק חשודים. עדיין צריך לדחוק ברשי שאינם חשודים די לפוסלם (ואפשר שרק ר"ל שחשודים שאם יכלו, יגנבו, אבל אכתי לא גנבו. ויש לדון אם אולי לא נאמין אותם אז. ואין צריך זה, שיכול להיות שרק יש חשש קטן.)
בלשון הרע- לכאורה, זה חולק על מימרא ראשונה של רב, שהיה לו לומר שכלם גם כן בעיון תפלה וכדו’. ויש לדון, שאולי לא בא לומר כל מה שבני אדם עוברים עליהם. יש לדון מה בא לומר.גם אפשר שחולקים מה אמר רב (ואולי לכן הובאו סמוך להדדי. ותו"ת).
תהלים- במקום אחר (גבי ללימוד של מה שלבו רוצה) קוראו תילים.
אבק… גנותו- יש לדון אם חוששים כן על האומר או השןמע. על כל פנים, מוזר שיש אותו חשש גבי רבי ובנו (ואולי אם חוששים לבנו, אינו כל כך קשה, שראינו (וזה סימן לסיבה לחוש או סיבה לחוש) שעבר, אבל לחוש לרבי מוזר.) עיין לעיל כט: ובמפרשים שם.
ובפירוש ר"ח- זה בוודאי גמרא (נמצא בשבת) ורק חולקים אם הובא כאן. ותו"ת.
קירות- יש לדון למה אין אומרים שמיותר רק מה שאומרו בלשון רבים. אם כן, יש רק ייתור אחד לכל. יש לדון, שאולי באמירת קיר פעם אחת, נדע שצריך להיות קיר. אכתי, רק נדע שצריך שלש. אולי באמת מיותר הוא. וצל"ע. אפשר שלא רק דורשים דרשת ייתור, אלא דרשת משמעות, דהיינו שדורשים ממה משמע מילה מיותרת, והרי אותו מילה הוא קירות, ואז הוא משמע שתוסיף קירות למה שצריך. ואם תאמר אם כן, למה שכתבנו לעיל, נצטרך חמש. יכול לנו לחזור ממש"כ, שאפשר שאי היה כתוב קיר, אולי היינו חושבים שאינו דווקא. גם אפשר שטוב יותר לדרוש לשון קירות לומר שצריך שנים. ואז דורשים הראשון כן, אבל אי אפשר לדרוש כן לשני, וצריך לומר שבא להוסיף עוד שנים.
ארכן- אפשר, לולי רשי, שהוא מלשון מלך (כמש"כ רשי שבת גבי "אריוך").
אריוך דיגון- יש לדון אם קוראים אותו כן כיון שקצת הוא שנה ראשונה וקצת הוא שנה שניה או מפני שהוא פעם שניה של שנה ראשונה. יהא נפקא מינא אם בפעם ראשון שמלך, מלך ליותר משעה אחד. ותו"ת.
כך מנהגה- משמע שתלוי במנהג. רשי משמע שהוא תנאי ב"ד. ומוזר. ואולי יכלו ב"ד לתקן רק כיון שיש נוהגים כן.
כל מנהגה- כיון שאמרנו שיש צורך למנהג, יש לומר שר"ח לא חולק על רבי (ואולי אף לא על רבנן), אלא שבמקומו לא כתבו זמן כן, ואז הם שווים. גם אפשר שכיון שהוא בידו ליזהר, לא חש ר"ח לזה, והוא שיש לו ללווה שלא שלפרוע קודם זמן שלא יוכל לרמותו כן. ותו"ת. ויש לדון אם רבי סובר שטורמ לו להצריכו לעשות כן, שפעמים שירצה לשלם מיד או שחוששים שמא ישכח. ותו"ת.
ארכן- היה אפשר לומר שהוא שרוצים אנו שיאריך זמנו.
ארכן- יש לדון למה זה שייך רק בראשון. ואולי שייך ביותר, אבל צריך להיות הבדל ביניהם. יש לדון למה נוקטים כן בראשון. אולי עוזים כן עד שאי אפשר. ותו"ת. גם אפשר שאז נאמר על הכל. גם אפשר שרב בושות מלך באים בשנה ראשונה כשאינו בקי כל כך בדרכי מלכות.
והלא- משמע שיש חילוקים כדי שיאריך זמנו. יש לדון איך מאריך. אולי צריך לעיין בהלכותיה או שהוא יותר לאט כיון שאינו כל כך רגיל בזה. גם אפשר שהוא שלפעמים יהא פסול. ללולי רש"י, היה אפשר לומר שהוא רק שכיון שיש קצת חילוקים ביניהם, עשו רבנן יותר חילוקים כדי שלא יבלבלו בין זה לזה.
כבר החזיק- יש לדון אם ר"ל שיש לו כח כאילו היה מלך לשני שנים או שמובטחים אנו שימלך לעוד שנה, וכבר מוחזק הוא על אותו מלכות. ותו"ת. יש לדון לזניהם למה אומרים רק שנים. אולי אם לא ננקוט זה, אין לדבר סוף, שלעולם אפשר להוסיף אחד.
למחקא- נראה שהענין הוא שאם הו עב, יש פחות דיו בסורפ"ס שלו, שיותר נבלע. אז, פחות נמחק מאותו מקום.
בפניהם- לא הבנתי מה לנו בזה שהוא בפניהם. אין לומר שעכשיו יכולים להעיד,ש אולי לא יהא שם כשנגבה. זה יש לדחות שלא יודע כן מלוה, ולא יזייף. עדיין קשה למה אין אומרים שיעידו שמקצתו מחוק. ותחשב.
- כבר קדמוך רבנן- יש להעיר שלא קדמו רבנן, אלא אביי עצמו קדמו, שהוא בעל מימרה זה. ואולי אמר לשון זה אגב שאר פעמים שאמר לשון זה (ויש לדון) שמצינו שאומר כן בכמה פעמים (למשל, עיין בסוף פרק קמא של שבת).
- דילמא מזייף- יש לדון למה אין אומרים שכיון שכתוב בתוך margin יבינו שהוא מזויף. ויש לדון. ואולי לפעמים לא יהא השורה justified, ואז יהיה רווח בין סוף השורה לmargin.
- מעברנא- לכאורה, הוא מפני מה שאומר גמרא לעיל (ט?) שתלמידים פטורים מכמה מסות. יש לדון, שאולי אפשר שרק מוכס זה בחר לפוטרם.
- שני אותיות- היה אפשר לומר שהוא מפני שאז יכול להוסיף שלשים בפעם ראשון אם אומרו קרוב לשורה. ויש לדון.
- רב- לכאורה, רצה לומר שכיון שיש בעיה לפעמים כיון שיכול להיות רב, עשו רבנן שלא יעשה כן לעולם. יש לדון למה. גם, באמת, צריך ביאור למה יש בעיה אם לומדים רובו. אולי לא מסתבר שישכח רובו.
- חנן- יש להעיר שחנן יש בו סופית, דלא כחנני. ועיי בגמ’ שבת שמקשה כעין זה.
- דדהבא- יש לדון למה לא. היה נראה לי בפשטות שהוא מפני שקטנין הן ונוחים לאבד. אם תאמר אם כן לא יעשה אף של נחשב. יש לומר שאין כל כך חסרון אם יאבדו. גם יש לומר שיש יותר צורך, אבל כאן יש כבר כמה מטבעות שהם כנגד זה. ויש לדון. יש להעיר שלשון גמרא מעניין, שאומר שלא "עבדי אינשי." משמע או שבעצם יקבלו, אלא שלא עושים אותםמטבעות או שלא יקבלם, אבל רק מפני שאינם רגילים כיון שאין עושים אותם בני אדם בדרך כלל. משמע שהבעיה הוא שאינו קל לעשותם או כעין זה. ותחשב.
- דינרי- נראה שהחילוק הוא ש"דינרי" יש בו צירי תחת הרי"ש, ואז תרגומו הוא "דינרים של," שמראה שהוא מין דינרים שבהם צריך לפרש ממה נעשים. זה זהבף שאינו הסתם. (גם היה אפשר לומר שדינרי יש בו חיריק תחת הרי"ש, והוא לשון רבים של ארמי, והיו בני אדם שדברו ארמי יותר מצויים בדינרי זהב. ויש לדון.
- תדע- אפקוהו- אין צריך זה לבאר למה לא רק אמרו לו, שיש לומר ששלחו מארץ ישראל לבבל (שלכאורה, שם דר).
- שלחו מתם חברייא- יש לדון אם זה ככל שלחו מתם (ואז צריך לומר ששלחו מתם הוא על בית מדרש של ר"א, ולא רק ר"א. כבר כתבנו צד כן) או לא (ושאני הכא שאומר מי שלחו). שוב הראה לי א.ל.י. שיש שאין גורסים מתם. כן, לכאורה, נראה, שהיה ר"י דר בבל (עיין בבדר הדורות שדן בזה), ואז איך היה בית מדרשו בתם. אפשר שלא שלחו כן לו בית מדרשו, אלא אחר, ובית מדרשו שמע מה השיב, ואז עיילוהו. ויש לדון.
- ספק- כדנפקא- יש להעיר שיש שיטה שאיסור זה הוא מדרבנן (כן אני חושב). אם כן, פשוט הוא, שספק דרבנן לקולא.
- אי הכי רישא- זה מחודש, שהיה אפשר לומר שכיון שלא אמר "ב" רצה לומר מטבע ממש.
- אימא נסכא- יש להעיר שאם כן, ישלם מעט מעט, שלא אמר בשטר כמה, והמוציא מחבירו עליו הראיה. יש להעיר שאין מיעוט; אולי אז היה לו לומר שלכן לא מסתבר שכן דעתו כשאמר דהב.
- לא שמיע לי- עיין ברשי בשבת (כן אני חושב) שדן אם לא שמיע לי משמע שלא סבר כן או שלא שמע כן. יש להביא סמך ממה שאומר כאן (וכן אומר בכ"מ) או שלא סבירה ליה (שאולי מסתבר שכל זמן שאומרים לשון זה שווה הוא) או שלא שמיע ליה, שכאן הוצרך לפרש, ורק כאן אומר כן ולא במקום אחר. יש לדון. גם יש להביא ראיה כן ממה שאומר זה ביותר מחד מקום, והוא כעין שני כתובים הבאים כאחד. ותו"ת. ויש לדון.
שוב ראיתי גמרא ערכין (טז.) שאומר, “לא שמיעא לי, ואי הוה שמיעא לי, הייתי מקיים אותו.” זה מוכרח כצד שממש לא שמע לו. ותו"ת.
- הקשה לי א.י.כ. מרשי (סו:) שהרי גמרא מצדד שרק אומר שבעין יפה מוכר. נראה שאפשר שמה שאמר שהוא כללא אינו מפ ני לשונו אלא מפני שאומר אותו דין ואותו לשון בכמה מקומות, שמשמע שהוא כלל. ויש לדון.
- שמעתי שסובר אור שמח שעובר אדם על שבואה לשעבר אף אם חזר תוך כדי דיבור. נראה שאולי סבר שלא עושה שינויו שלא חל (למפרע) אלא משנהו מכאן ולהבא. אז, למשל, אנו עובר אם אחר כן עובר על נדרו. בשבועה, כיון שעובר בעת דיבור, עובר, אף שנעשה שאינו רע מיד. כיון שכןן, חייב. ויש לדון.
- מעניין מה שמצינו שרבה אומר לאביי "לדידך קשה… " ולא לשון מר, שכן מצינו בתלמידים, כמו שמצינו בברכות (ראש פרק זמני תפלה). ויש שמשנים את הגירסא. גם יש לומר ששאני אביי כיון שהיה כבנו, והיה רגיל בו. גם יש לציין למקומות אחרים שאומר אביי מר לרבה.
- ק"ק איך דורש ממה שאומר, “בת לוי,” שאולי רק אומר שהיתה בתו של לוי. יש לומר שאין צריך לכך שקרא אחר כבר אומר כן. גם יש לומר שכיון שבעמרם רק אומר שבטו, מסתמא אף בה רק היה אומר את השבט. כנגד מה שאמר גבי עמרם "איש,” אמר בה "בת.”
נולדו- ק"ק, שכבר נולדו קודם לכן, שהולידה מרים. ויש לדון, שאולי כך אמר, שנולדו קודם לכן. ודחוק.
- חושב אני שראיתי רש"י שאומר שכל קנין לזמן הוא קנין פרות. איני יודע איפה הוא, אבל אז יוצא ששאלה וכדומה צריך להיות רק קנין פרות. צריך ביאור, שלגמרא יש צד ש"אחריך" הוא קנין הגוף. אולי הוא מפני שבהכרח לא יאבד אותו עד מיתתו. צריך ביאור מה לנו בזה. גם צריך ביאור למה לא יכול לתת קנין לזמן. זה לא קשה, שיש לומר שאם נותן קנין, לא יחזור, כמו באישות. אז, אם רוצה שיהיה לזמן, לא יתן קנין הגוף. ותחשב.
אם נוכל לומר שבאחריך חל, אז, רואים שעדיין יחול לנתק הקנין אחר כך. אם כן, צריך ביאור. ותחשב.
* Footnotes
[fn:1] עיין במה שכתבנו בזה בסדר ראשון.
