א.
פני משה אומר שהוא מפני שצריך להיות שיריים שלו ניכרים. כן הוא לשון של גמ’ בעירובין כשדן בברירה. אבל, כאן רק דורשים שצריך להיות שיריים. (באמת, גמ’ זה הוא מחלקת (עיין שם), אבל כולי עלמא מודה לדין זה, לכאו’.) מסתמא, פני משה מודה לזה, ורק מביא לשון של אותו גמרא.
ב.
צריך לפרש מהו ”אין לו שיעור“ של משנה שלנו. יש שני מיני שיעורים:
1. שיעור למעלה.
2. שיעור למטה.
אז, נמצא שיש ארבע דרכים לפרש משנה שלנו:
1. דברים אלו אין להם שיעור למעלה.
2. דברים אלו אין להם שיעור למטה.
3. דברים אלו אין בהם שיעור למעלה ואין בהם שיעור למטה.
4. דברים אלו אין בהם שיעור למעלה ולמטה.
יש שני מראה מקומות (חוץ מדיון זה) שנוגע לכאן:
1. גמ’ בחגיגה (ז.) מצדד שלראיון יש שיעור למטה. אז, לאותו צד, אי אפשר לומר כצד שני ושלישי.
2. ירושלמי אומר (ב:) מביא מחלקת אם יש לפאה שיעור למטה. אבל, צריך לבאר למה, אם יש לו שיעור למטה, הוא נשנה במשנה שלנו:
  1. אולי הוא מפני שלא אומרים כצד שני ושלישי.
  2. אולי הוא מפני שאותו שיעור הוא רק מדרבנן. אז, כשאומר ש“יש לה שיעור,“ לא רצה לפרש את המשנה, אלא אומר, אגב, שיש לה שיעור מדרבנן. (אולי כן נראה קצת ממה שלא אומר (כמו שאומר גמ’ בחגיגה) שמשנה ר"ל שיעור למעלה, אלא רק אומר שיש לו שיעור למטה. ותו"ת.)[fn:1]
  3. וכן נראה מגמ’ לקמן (ב.) שאומר שלא ממעטים דברים שיש להם שיעורים מדרבנן.[fn:2]
אחד מן הסיבות למעט תרומה הוא שיש לו שיעור למעלה. נמצא שמה שיש לו שיעור למעלה אינו בכלל המשנה. אז, צריך לומר נגד צד שני ורביעי. אם נאמר שלפאה ממש יש שיעור למטה (או אם נאמר שגמ’ בחגיגה סבר כתי’ זה בהו“א שלו), נצטרך לומר כצד ראשון. ותחשב. ויש לדחות שלעולם מונים שיעורים דרבנן, ופשוט שלתרומה יש שיעור למטה. אז, גמ’ רק אומר שאין לו שום דבר שאין בו שעיור, שיש לו שיעור למעלה ויש לו שיעור למטה.
בביאור סיבה אחרת של גמ’, הרי כל השיטות מודים שצריך לשייר קצת. אז, לכאו’, אי אפשר לומר שכוונת הגמרא הוא שלא נמנה כיון שיש לו שיעור למעלה, שאז לא צריכים להזכיר מה שהוא מחלקת. אז, צריך להיות שיכול להיות במשנה, כיון שמשנה רק מצריך שאין שיעור למטה (או שיש דבר אחד שאין בו שיעור) ומדאו’, אבל כיון שבדבר אחר בו, יש מחלקת בנוגע השיעור, לא מזכיר אותו. זה מעניין.
גם יכולים לומר שלעולם סובר שהבעיה הוא שיש לו שיעור למעלה. אבל, רק סובר שמה שלא אפשר לתת את כולו אינו שיעור. לא פשוט לבאר מה נחשב שיעור (שמה שלא אפשר לתת את כל השדה לפאה אינו, כמו שמבאר גמ’, נחשב שיעור, ומה שצריך לעשות אחד מכל דבר לא נחשב שיעור למטה), אבל אולי סובר שאין מה שאינו יכול לתת את כולו נחשב שיעור. ותחשב.
ג.
ואם תאמר הרי אף בפאה לא יכול לעשות כל שדה שלו פאה. ויש לומר שזה רק מפני שחיוב רק חל אחר שקצר קצת. אבל, מה שיש עליו חיוב (הנשאר) יכול לעשות, כולו, פאה[fn:3]. (ויש לדון אם היה אפשר לומר, לפי צד לקמן בגמ’ שאומר שאין לו שיעור למטה) ששאני פאה שכבר אין לו שיעור למטה. ותחשב. ועיין לעיל.)
ד.
יש מאלו שיש לדון בהם אם יש להם שיעור למטה או לא. למשל, רוק יבמה צריך להיות נראה. יש לדון אם זה נחשב שיעור או לא (והוא כעין מה שצריך לעשות כל מצווה פעם אחת). ותחשב.)
ה.
עיין שם בירושלמי, שלא רק אומר תירוץ זה, אבל מניח שתירוצים אחרים לא מתרצים. (שם אומר שרבי יוחנן אומר כצד ראשון. מפרש שמוכרח רבי יוחנן לומר כן כיון שסובר שהשיעור הוא מדאו’. משמע שסובר ששאר תירוצים לא אפשרים. ויש לדחוק שאומר שאפר שרבי יוחנן סובר ששאר תירוצים אינם אפשרים, ולכן מפרש את המשנה ככה. דחוק.)
ממה שלא תירץ הירושלמי כמו שתירץ הבבלי, לומדים שסובר שלא מסתבר שמשנה שלנו אומר דבר שרק אין לו שיעור למעלה, אבל יש לו שיעור למטה. (דחוק לומר שהוא רק לשיטה בירושלמי שלפאה אין שיעור למטה. אז, משמע שאותו שיטה סובר, כמו שבאמת מפורש כאן, שאין שיעור זה בעיה כיון שהוא רק שיעור דרבנן[fn:4].) נמצא ש“אין לו שיעור“ צריך להיות או כצד 2 או כצד 3 שהזכרנו.)
ו.
כתבנו שהוא שיעור למעלה. כן כתב בפני משה. ויש לציין לשי“חתא דש“י, שכתבנו שם: ”יש להעיר שלכאורה, היה אותו שיעור של תרומה שיעור למטה (כמו שהוא גבי תרומה). אז, צריך לומר ששיעור של חומש הוא גם כן שיעור למטה.
עיין בפני משה שכתב שהשיעור הוא "חומש ולא יותר.” משמע שזה שיעור למעלה. אולי הוא שניהם. ודחוק. עדיין, לשונו משמע שגמרא דן בשיעור למעלה. אז, לכאורה, צריך לומר ששיעור שדומה לשל תרומה הוא שיעור למעלה. ותחשב.
יש לדון לפי פני משה מה הוא קושיית גמרא שייצא בלי שום ממון; הרי אינו צריך לתת. נראה שאומר ששיעור למעלה הוא כדי שלא יעני; אין זה מעכב אותו מלעני, שאף בזה יעני. ותו"ת.“
ושוב מצאתי בתולדות יצחק (הוא פירוש על הירושלמי שחבר ר’ יצחק אייזיק קראסילשציקאוו, במאסקבא מתשי“ב עד תשכ"ה), שכנראה[fn:5] מפרש שפני משה רצה לפרש ”עד היכן“ (שיעור אחר) שאומר גמרא להיות שיעור למטה. לא משמע כן מלשון הפני משה. כן כתב מהר"א פולד“א וגר“א בפירוש[fn:6]. עיין בר"ש סירליאו שפי’ ששואל מהו שיעור למעלה של חיוב, ולא של רשות.
ז.
יש לדון אם נותן חומש ממה שבא לו או ממה שהרוויח. למשל, אם הפסיד חמש ולקח עשר, יש לדון אם נותן מעשר או מחמש. גם יש לדון אם יש חילוק בין אם חסר החמש בשביל העשר או שלא בשביל העשר. ותחשב.
ח.
לכאו’, צריך לומר שלא ממש נדרש מן הקרא, כיון שנמצא שזה היה טעות. לכאו’, היה אסמכתא. ויש לדון, שאפשר לומר שטעו בפירוש הקרא.
ויש להעיר שתרומה אין לו שיעור מן התורה. אם נאמר ששיעור זה הוא שיעור למעלה, אי אפשר לומר שאומר ששיעור המעט של תרומה הוא השיעור למעלה כאן. (אבל, יש לומר שאומר שאין שיעור. אבל, לא נראה כן כלל מן הגמ’.) אז, יותר טוב אם נאמר שהקרא הוא אסמכתא. ותחשב.
ט.
ואם תאמר הרי אין לו עדיין שיעור למטה. אולי זה ראייה שאם יש לו שיעור למעלה, אף שאין לו שיעור למטה, לא נמנה במשנה. ויש לדון, שאולי יש לו שיעור למטה, שצריך לתת פרוטה או דבר הראוי לפי עושרו (עיין בב"ב ח:).
ואם תאמר הרי שיעור זה הוא רק מדרבנן, ולמה נקרא שיעור. ויש לומר שהוא הל“מ, ולא מדרבנן. ויש לדון, שגמ’ רק מחדש כן לאחר זמן, ולא נראה שידע כבר גמ’ כן. גם לא נראה שבבלי סובר כן, שלא מזכיר אותו. (ויש להעיר שאולי אם בבלי לא יודע כן וירושלמי יודע כן, הלכה יהיה כירושלמי, שיש לומר שכמו שירושלמי שכח ולא זכר עד לאחר זמן, בבלי שכח, ולא זכר כלל. ותו"ת. במילים אחרים, זה דבר שיכול להיות אמת ולא ידוע, ולא כל כך קל להיות שקר וידוע. ותו"ת.) אפשר ששיעור דרבנן של איסור הוא חלוק משיעור דרבנן של פטור. לא נראה לי כן. גם אפשר שכל ענין זה (אם שיעור דרבנן נמנה) הוא דיון ומחלקת בירושלמי, והוא המחלקת של פאה, אם יש לו שיעור למטה מדרבנן או לא. אז, אולי יש לומר שגמ’ לעיל, שאמר שמה שיש לו שיעור דרבנן אינו נחשב כיש לו שיעור וגמ’ זה חולקים. ותו"ת.
י.
ואם תאמר אם יש כבר שיעור למעלה של אחד ממאה, מה לנו בשיעור למעלה של אחד מחמישים. עיין בגמ’. היה אפשר לפרש שהשיעור הוא אחד ממאה עם אחד מחמישים, שהוא שלש ממאה. אבל, פני משה לא מפרש כן. אולי היה מסופק, וידע שהוא אחד, אבל לא ידע גמ’ איזה אחד. גם יש לומר שאחד הוא לאיסור ואחד הוא לפטור. וצריך לחשוב יותר.
יא.
צריך לדון בזה. ראשון, נביא את הגמרא, ושני נדון במה שכתבנו.
גמרא אומר ששאלו את ר“י אם מותר ללמד לבנו יוונית. השיב שהוא אסור כיון שכ’, ”והגית בו יומם ולילה.“ הקשה גמ’ שצריך ללמד אומנות, ולא נאסר מחמת ”והגית בו יומם ולילה.“[fn:7] תי’ שאסור ללמד לשון יוונית מפני המוסרות (חוששים שמא יהיה מוסר).
עכשיו, נדון על הגמ’. נראה שנדון בשני נקודות:
1. האם ר“י באמת חולק על המשנה. נראה שיש שני צדדים לומר שלא חולק על משנה שלנו:
  1. אפשר שכשאומר גמ’ ”מפני המוסרות,“ בא לבאר שיטת רבי יהושע, לומר שרבי יהושע אמר כן לו, אף שאין האמת כן, מפני שחשש שיהיה בנו מוסר. (אבל, לא רצה להגיד כן לאב, כיון שחשש שהאב לא ישמע לא או ירגז עליו.)
2. ויש להעיר שיש סיבה חזקה לחשוב כן, והוא שבלי זה, גמ’ רק תירץ את קושייתו שלא אליבא דרבי יהושע. אבל, לר"י, הוא עוד קשה. ותחשב.
3. אבל, זה מביא עוד נקודה אחרת, והוא שצריך לדון אם בבלי מודה לירושלמי בזה. ירושלמי מביא מעשה זה באופן קצת חלוק מבבלי. בירושלמי, שאלו את רבי יהושע אם מותר ללמד לבנו. בבבלי (מנחות צט) אומר[fn:8] שבן דמא, בן אחותו של רבי יהושע שאל לו אם מי שלמד כל התורה כולה (כמו בן דמא) יכול ללמוד חכמה יוונית[fn:9].
4. לכאו’, בבלי אין כל כך חשש מוסרות, שבן דמא כבר היה תלמיד חכם גדול (שלמד כל התורה כולה), ולא היה חשש שיהיה מוסר. ויש לדון.[fn:10]
  1. נראה שאפשר שרבי יהושע מפרש שהמצווה הוא ללמוד כל שעה, ולא שהמצווה הוא ללמוד, וזמנו הוא כל שעה. אין החילוק כל כך מובן לי, אבל כן צריך לומר גבי דברים כמו רוק יבמה, כמו שבארנו לעיל. ותחשב.
  2. אולי משנה מונה דברים שיש להם שיעורים מלמטה, ורק לא דברים שיש להם שיעורים מלמעלה (או מלמעלה ומלמטה). עיין לעיל, גבי ראיון, שלא נראה כן.[fn:11]
5. איך מבארים החולקים על ר“י הקרא של רבי יהושע. עיין בגמ’ במנחות[fn:12], שיוצא שם שני דרכים:
  1. חולקים רבנן ורבי יוסי מהו משמעות ”תמיד“ (שם, הוא נוגע ללחם הפנים). רבנן סוברים שהוא תמיד ממש, ורבי יסוי סובר שהוא רק בתחילת יום ובסוף יום. אז, לרבי יוסי, רק חייב ללמוד בתחילת יום ובסוף היום[fn:13]. אבל, אז, צריך לומר עדיין שרבנן חולקים על משנה שלנו.
  2. יש שיטה שם שקרא זה רק אומר ברכה לבנ“י, ולא חיוב.
יב.
קצת צריך להגדיר מהו ”מצוות שקולים.“ לכאו’, יש שני מהלכים:
1. מנין המצוות שקולים. זה מעניין, שלא, אז, אומרים שמצווה שהוא יותר גדול ויותר חשוב הוא נחשב ליותר.
2. חשבון המצוות שקולים. יש מצוות שנחשבים ליותר, ויש עבירות שנחשבים ליותר. בין הכל, שווה. ויש להעיר שמחודש שנותנים לו שכר כיון שעשה אלו, שאינו יותר זכאי. צריך לומר שיש שיותר נותנףים שכר, ולא מפני שהם יותר טובים. וצריך ביאור.
מצאתי שבשאלות ותשובות מסדר שני של כתב יב, כתבתי כצד שני (ואז, מסתמא יש איזה מקור לזה שר’ שמואלביץ נתן על הדף שהיה רגיל ליתן). שו“ר שבהערות מכתה יב, הבאתי את זה מן הרמב"ם. גם הקשיתי מה שהקשיתי פה, והוא שקשה למה נותנים לו שכר, כיון שהוא מחצה על מחצה. שם כתבתי, כעין מה שכתבתי כאן, שאולי יש לאחד כוח לעורר רחמנות ה’, עד שה’ נותן לו שכר כאילו היו לו יותר מצוות. אז, בעצם יש לנו שני תירוצים: אולי מצווה הוא יותר סיבה לשכר, ואולי מצווה הוא סיבה למה שעושה סיבה לשכר (אולי עושה שה’ מגדיל מצוותיו או כובש עוונותיו או כדומה).[fn:14]
חשבתי על עוד ענין (ועיין בר“ש סירליאו, שאולי זהו כוונתו), והוא שעי“ז הוקשו כולם, ואז רק צריכים מקור אחד, וכולם ילמדו מאותו אחד.
שוב ראיתי ביפה מראה שמפרש שבקרא זה כ’ כפל שכר, ואף שדורשים מזה גופא לרבות כל אלו דברים, עדיין דורשים ממנו שכר של עולם הבא ועולם הזה בדברים אלו. ותחשב.
יג.
בארנו גמרא זה לפי הסבר של רבא באותו משנה. לפי הסבר של אביי באותו משנה, סובר המשנה ששכר מצוות בהאי עלמא ליכא, וכשאומר ”מטיבים,“ רצה לומר ”עושים לו רע, שהוא טוב לו, כיון שאז שכרו יהיה גדול ועונשיו יהיו מועטים לעתיד לבוא.“ אם כן, אפשר לומר שלחולק על המשנה, אין הגדרה של מה מקבל שכר בעולם הזה צריך להיות שווה למה שהוא לפי רבא. יש לדון, אז, מה הוא.
יד.
אחר זה, מביא גמ’ קרא ”צדיק טוב… פרי מעלליהם….“ היה אפשר לפרש (עיין שם) שרק מביא אותו להוכיח שיש מושג של צדיק טוב וצדיק שאינו כל כך טוב. עיין ברש"י, שנראה שסובר שעכשיו חוזר גמ’ על כל המקורות, ואומר שיש מקור לכל, והוא קרא זה, ומרבה כל שהוא רע לה’ ולבריות. אם כן, ירבה כל דבר שהוא בין אדם לחבירו. ותחשב. (זה קצת יותר טוב, שבלי זה, ק"ק, שאף שרואים שיש ענין של צדיק טוב, מהי“ת שזה נצרך לדרוש כן. ותחשב.) (אולי על פי זה, נוכל לתרץ למה שהקשינו בסתירה בין דין תורה לדין שילוח הקן. אולי הק’ משילוח הקן רק כיון שדרשה שלו דומה לשל כיבוד אב ואם. אבל, כיון שאין כיבוד אב ואם נדרש משם, אולי אין לדרוש ככה, ורק משל תורה יש לדרוש (צריך לומר שלשון חיים חלוק). אז, בין הכל, יש שני מקורות: ”כי פרי מעלליהם“ ו“חיים“ שנשנה גבי תלמוד תורה. ותחשב.
גם צריך לעיין בירושלמי שאומר, ”ר’ מנא [אמר] שמע כולהוןמן הדין קרא: ”כל לא דבר רק הוא מכם [זה תלמוד תורה] כי הוא חייכם [זה כיבוד אב ואם] ובדבר הזה תאריכו ימיכם [זה גמילות חסדים] על האדמה [זה הבאת שלום].“
אז, לכאו’, יש לנו עוד מקור. אבל, נראה לי שאולי אינו עוד מקור, שלא כתוב שם שיש שכר בעולם הזה. היה נרא הלומר שגמ’ רק אומר שכולם גם נלמדים מעלתם מקרא אחד, שיש קרא אחד שמזכיר את כולם ביחד, ואומר שהם טובים. אבל, לא בא לומר מקור. ותחשב.
טו.
עיין ברש"י, שקצת משמע שסובר שרק אינו חלק מן המנין, אבל הוא חלק מן הדין. (אז, אי אפשר שהלימוד הוא מ“פרי.“) כן חשבתי עכשיו, וראיתי שהנחתי כן, אבל הערתי שאינו מוכרח, בכתה יב.
טז.
עיין בגמ’, ועיין בשאר מקורות. נראה שאפשר לומר שלא מביא קרא זה להיות מקור כאן, אלא להיות מקור ללמד ממנו שאר הדברים, שאולי דרשת גדולה בכל שאר מקום אינו מחמת משמעות הלשון, אלא מחמת לימוד מגזירה שווה מכאן. ותו"ת.
יז.
ואם תאמר הרי יש הרבה עבירות שיש להם תוצאות ניכרות, כמו נבלה, שעכשיו אינו רעב, ושעטנז, שעכשיו הוא חם, ומלאכות שבת, שעכשיו נעשה המלאכה. (ויש לדון, שאולי צריך שמה שהוא רע ניכר. ותחשב, שלא נראה שכן הוא בכל ארבע אלו.) ונראה שכל מה שנאסר צריך להיות שיש לו תוצאה ניכרת- אבל לא כל מה שיש לו תוצאה ניכרת נאסר, אלא צריך מקור עליו. אבל, אולי לשון גמ’ לא משמע כן כל כך. ותו"ת.
יח.
עיין שם בסנהדרין. כן נראה מקושיית אביי שם.
יט.
עיין שם. צריך להגדיר את זה. פשוט שאם מקשה קושיה שאינה טובה, לא נחשב בכלל זה מחמת כן. (ויש לדון, שאולי רציך ליזהר מאד, ולחשוב על כל מה שקשה לו.) אולי הוא רק אם מקשה מה שיודע שאינו קשה. ותחשב. (ודע שלשון דורש אגדות של דופי הוא קצת מוזר, שלא דרש כלום מהם, אלא היה מקשה. אולי דרש ר"ל אמר בשיעור לרבים. ותחשב.)
כ.
ואם תאמר מהו החידוש בזה. נראה שזה מחדש שני דברים:
1. שאם רוצה לתת יותר, זהו צדקות, שטוב לתת יותר. ואם תאמר כבר נודע ממשנה שלעיל, שבלי זה היה לנו להזכיר רוק יבמה. ויש לדון, שאולי טוב לכפול אותו יותר בפירוש.
2. שמה שנותן יותר נחשב פאה, ופטור מן המעשר. (לכאו’, מה שהיה חייב צריך להיות דין דרבנן, שאילו היה דין דאו’, נמצא שמצדדים שמדאו’, מה שלא חייב לתת אינו פאה. אם כן, מדאו’, כמעט אין נפק"מ במה שפוטר פאה ממעשר.
כא.
יש לדון אם רבי שמעון גם כן סובר שרק נותנים אחד מששים שבקרקע, ולא מחמירים לתת אחד מששים של פירות, או בזה לא חולק. ותחשב.
כב.
ואם תאמר איך יודעים שמשנה שלנו לא אומר כן. גמ’ תי’ שממה שגם מזכיר ”ענוה,“ וזה אי אפשר להיות לטובת בעל הבית, צריך לומר שאף השאר אינם לטובת בעל הבית, ועושים מה שהוא הכי טוב לעניים.
כג.
כן נראה מן הגמ’ (מראייתו שאינו כר“ש). ויש לדון בזה, שצריך לתת את הפאה, ולא האמצע. אז, לא יכול לתת כל חלק שרוצה. ותחשב.
כד.
כן נראה מגמרא כאן. אבל, צריך לעיין בשבת (כג.) שמשמע נגד זה. יש לומר שהם חולקים. וצריך ביאור.
* Footnotes
[fn:1] ואגב, אם תקשה למד“א שכל שיעורים דרבנן (ג.), איך נאמר שיש שיעור מדרבנן שאינו דומה לשיעורים מדאו’. ויש לומר שאין הכי נמי, וצד זה אפשר רק לפי רבי יוחנן (ושניהם הם מחלקתים בגמ’). גם יש לומר שלפעמים עשו רבנן שיעורים שלהם חלק יותר גדול מדין התורה. ותחשב. (וצריך לעיין גמ’ לקמן, שיוצא שאף שם, כיון שהם מדרבנן, יש קולות, ואינם ממש חלקים מן הדין.)
[fn:2] רק אציין כאן שאותו גמ’ צריך ביאור, שלכאו’ שם רבנן עשו שיעור לחומרא, ומקשה גמ’ איך אפשר שרבנן עשו כן. לכאו’, עשו כן בפאה. אולי צריך לומר שאף חולקים אם שיעור פאה הוא מדאו’, וכן שיעור תרומה, וכדומה. וצריך לעיין שם. אבל, עכשיו נניח שיש שום קולא שם גם כן (אולי אם אין לו שיעור פטור מלהקריב), וזהו מחלקתם.
[fn:3] יש לדון אם הענין הוא שיש לו שיעור, אבל לא נחשב שיעור, אלא הוא אופן עשיית מצווה. ותו"ת. (וזה יהיה דומה למה שרוק יבמה נחשב, אולי, שאין לו שעיור, אף שצריך להיות נראה.) אפשר שהענין אינו כן, אלא ששיעור רצה לומר ששיעור של שעת חיוב, והרי אין שיעור בשעת חיוב, שאז יכול לעשות את הכל. ותחשב.
[fn:4] וצריך לבאר את זה, שצריך להיות, אז, שרבי יוחנן סובר שאותו שעיור הוא מדרבנן. וצריך להגדיר מתי מודה רבי יוחנן ומתי לא מודה.
[fn:5] שם כותב בפירוש שלו אותם מילים של פני משה (מסתמא, דרכו הוא להביא פני משה כשמסכים לו, כמו הר“ן על הרי“ף), ובהגהה מפרש שכן ר"ל.
[fn:6] אבל, הלומד פני משה ידע שמצוי מאד שפני משה יאמר פשט שמתנגד לגמרי (בכ“פ בלי שום טעם הנראה) לפירוש שאומרים כל שאר המפרשים. בקצת בדיחת, נראה שמה שכבר פי’ הגר“א והר“ש סירליאו כן הוא קצת ראיה שפני משה לא מפרש כן. ויש לדון, שאולי התולדות יצחק ימצא דרך לפרש שפני משה מסכים להם גם בכל שאר המקומות שחולק. וצריך לעיין בזה.
[fn:7] אגב, אזכיר כאן שאני לא מבין קושיית גמ’. היה לו להקשות שצריך לישון. אלא, צריך לומר ש“יומם ולילה“ הוא חוץ מזמנים שאי אפשר ללמוד. אף אם תחלק בין דבר שמוכרח מצד בריאתו לעשות לדבר אחר, היה אפשר להקשות מכל תרי“ב מצוות (על כל פנים, מן העשיים). ותחשב.
[fn:8] ואולי מעשה זה קרה שני פעמים, ואז אין מחלקת.
[fn:9] יש להעיר שצריך לבאר מהו ההו“א לאסור. במעשה שמזכיר הירושלמי, בפשטות הצד לאסור הוא ביטול תורה. בבבלי, לכאו’ הוא גזי’ (בסוטה) שלא ללמוד חכמה יוונית. אבל, עיין שם, שיש לדון מה לנו, אז, שלמד את כל התורה כולה. אולי לא ידע למה נאסר. ותחשב. (גם אפשר שכשירושלמי אומר לשון יוונית, כוונתו לומר חכמה יוונית.)
[fn:10] אם הייתי בעל מוסר, הייתי אומר שלהיפך מה שהוא חשב שלמד כבר את כל התורה כולה (או מה שחשב שזה יפטור אותו מללמוד עוד), זהו הראיה הכי גדולה שצריך לחוש שיהיה מוסר.
[fn:11] אגב, יש להעיר שמלשון גמ’, לא נראה שר“י חולק על המשנה, שמביא המשנה, ועליו מביא המעשה של רבי יהושע, ולא מעורר שרבי יהושע אינו כמשנה. משמע שרבי יהושע הוא כמשנה, ולא חולקים.
[fn:12] עיין שם, שדן ראשון על ”לא ימוש,“ אבל הוא אותו קרא, ונראה שדורש כולו כאחד.
[fn:13] לכאו’, יוצא מזה עוד חומרא, שצריך להיות לומד באותם זמנים. נראה לי שלא נוהגים כן עכשיו, אלא בדרך כלל ישנים או מתפללים אז. ותחשב. (באמת, יש לדון איך קיימו הוותיקים ענין זה.) ותחשב. אולי בזמן תפלה פטורים מלילמוד תורה. לא כל כך פשוט למה מותר להתפלל אז, ולפטור את עצמו מחיוב זה. ותחשב. ואפשר לומר שהבעיה הוא רק שלא ילך כל הלילה בלי לימוד, ושם רק נתנו קודם הלילה כיון שלא יכולים לעשות עבודה בלילה. ותחשב. וצריך לעיין שם.
[fn:14] אגב, צריך לבאר מה שאומר גמ’ שה’ מטה כלפי חסד כשהוא מחצה על מחצה, שמחמת זה יקבל שכר. ותחשב.
