מצאנו שש מחלוקות בין הלל לשמאי. גמ’ אומר שיש רק שלש, ואז נבאר, בע"ה, איזה מונה, ולמה מונה אותם.
אלו שלש שנמנים:
א.
אם אדם עשה עיסה מתבואת א"י, חייב להפריש חלה לכהן. אבל, לא מכל עיסה חייב להפריש, אלא מעיסה כשיעור. חלקו שמאי, הלל, ורבנן מהו השיעור:
שמאי אומר שהשיעור הוא קב.
הלל אומר שהשיעור הוא קביים.
חכמים אומרים שהשיעור הוא קב ומחצה.[fn:1] (רבי יוסי אומר שצריך להיות יותר מקב ומחצה להתחייב. מסתבר שבא לפרש שיטת חכמים, ולא לחלוק עליו, ששאר החולקים היו הרבה שנים לפניו.)
ב.
מקווה נפסל אם ניתן לתוכו מים שאובים (קודם שנגמר). חולקים שמאי, הלל, ורבנן כמה מים צריך לתת לתוכו עד שנגמר:
שמאי אומר שהשיעור הוא תשעה קבים, שהוא שלשים ושש לוגים.
הלל אומר שהשיעור הוא שלש קבים, שהוא שנים עשר לוגים.
חכמים אומרים שהשיעור הוא שלשה לוגים.
ג.
אם יוצא דם ממקורה של אשה, טמאה בדם נדה. אם אשה בודקת ומוצאת דם, ולא יודעים מאיזה זמן בא הדם, חולקים שמאי, הלל, ורבנן בטומאתה למפרע:
שמאי אומר שלא מטמאה למפרע. גמ’ נותן ארבע טעמים לזה:
1. מעמידים אותה על חזקת טהרה שלה.
2. ממה שלא הרגישה, מוכרח שלא יצא דם מן המקור.
3. ממה שלא יצא דם מחוץ לגופה, מוכרח שלא יצא מן המקור.
4. כדי שיולידו בנים, לא חששו לאסור אותה.
גמ’ מפרש שאף אם היתה מטמאה למפרע, רק היתה מטמאה טהרות, ולא בועלה.
הלל אומר שמטמאה למפרע. הלל צריך לדחות ארבע הטעמים של שמאי:
1. דוחה הלל שיש ריעותא בגופה.
2. לפעמים, מרגשת אבל חושבת שזה הרגשת מ"ר.
3. לפעמים, כותלי בית הרחם מעמידים את הדם בתוך גופה.
4. לא הקילו מחמת זה.
רבנן אומרים שמטמאה למפרע עשרים וארבע שעות (אא"כ בדקה ומצאה את עצמה טהורה בינתיים). סוברים שחייב אשה לבדוק פעמיים ביום. אם לא בודקת, קנסו והוסיפו עונה אחת, עד שקונסים אותה עונה שבטלה ועונה אחרת, שהוא עשרים וארבע שעות.
אלו שלש שלא נמנים:
א.
מצאנו בביצה שהיו קונים מאכלם לשבת באופנים חלוקים, ששמאי היה קונה תמיד מה שראה לכבוד שבת, ונמצא שאכל כל יום לכבוד שבת, והלל היה בוטח בה’, וקונה לשבת לבסוף. גמ’ לא מזכיר את זה, ואף לא מקשה ממנו בשבת. נראה שסובר שאינו מחלקת, אלא שני ההנהגות טובות. עיין שם בביצה, שמבריי’ שמביא לא משמע כן כל כך.
ב.
חולקים אם לסמוך קרבן שמביאים ביום טוב או שלא לסמוך. גמ’ בביצה מסביר שאפשר שחולקים אם צריכים סמיכה ואפשר שחולקים אם צריכים סמיכה מיד לפני שחיטה.
יש הרבה חולקים בדבר זה:
לא מונים את זה כיון שיש אחרים שחולקים עם הלל ועם שמאי.
ג.
אם אדם בוצר לגת, חולקים אם הענבים טמאים:
שמאי- טמאים, כיון שחוששים שנפל עליהם יין והכשיר אותם. וא"ת הרי אינו לרצונו. וי"ל שחוששים שיבצר בכלי טמא, ואז לא צריך רצונו. אבל, מח’ הוא אם צריך רצונו. אם עדיין צריך רצונו, אז חוששים שירצה במשקים  או חוששים שרצה במשקים .
הלל- טהורים. אבל, לבסוף הודה הלל לשמאי.
לא מונים את זה כיון שהודה הלל לשמאי.
* Footnotes
[fn:1] יש להוסיף כאן שאלו הם השיעורים על פי מדות הישנות. אבל, הגדילו המדות, וקראו לשש לוגים חמש לוגים. אז, נחשב לכולם. נתחיל לקבוע שקב הוא ארבעה לוגים, ולוג הוא ששה ביצים. נמצא ששמואל סובר שהשיעור הוא עשרים וארבע ביצים, הלל סובר שהשיעור הוא ארבעים ושמונה ביצים, ורבנן סוברים שהשיעור הוא שלשים ושש ביצים.עכשיו, נשנה את זה למדה חדשה.עשרים וארבע ביצים נעשים עשרים ביצים, ארבעים ושמונים ביצים נעשים ארבעים, ושלשים ושש ביצים נעשים שלשים, שהוא חמש לוגים, שהוא קב ולוג.
