לילה ובין השמשות
יש זמן שהוא ספק יום ולילה, והוא בין השמשות. נבאר מתי הוא בין השמשות, מתי התחיל ומתי נגמר.
שיעורי בין השמשות. בין הכל, מצאנו אחת עשרה שיטות. בכל אחד, נדון במה שאומר, ומתי מתחיל ומתי גומר:
1. רבי נחמיה- מתחיל משתשקע החמה, וממשיך לזמן שבו יכול אדם ללכת חצי מיל. אחר זה, נגמר.
גם מצאנו שיעור אחר לזה. בבלי אומר שמניח את החמה על ראש הכרמל[fn:1], וירד ויטבול בים, ויעלה[fn:2] ירושלמי אומר שיעמוד בראש הר כרמל כשמתחיל גלגל החמה לשקע, וירד דרך קפנדריא לים הגדול, ויטבול ויעלה.[fn:3]
1. רבי יהודה (שבת)- יש שלש שיטות בדברי רבי יהודה:
  1. רבה- מתחיל משתשקע החמה, וממשיך עד שהשחיר עליון ותחתון של הרקיע. זמן זה הוא מהלך ¾ מיל. יראים אומר שמתחיל כששמש נוטה לשקע, ונגמר כשמתחיל השמש לשקע.
  2. רב יוסף- מתחיל אחרי שפני מערב נעשה אדום, כשהכסיף (נעשה שחור), עד שכל הרקיע נעשה שחור.[fn:4] זמן זה הוא מהלך 2/3 מיל.
  3. ירושלמי- מתחיל אחרי שפני מזרח נעשה אדום, כשהכסיף למטה, עד שכל הרקיע נעשה שחור.[fn:5]
גם מצאנו שרבי יהודה אומר שהוא ארבע מיל (שהוא 1/10 של יום; אבל, יש לדון אם "יום" זה כולל בין השמשות). ואם תאמר סתירה הוא. וי"ל שחולקים אליבא דרבי יהודה. לא משמע כן מגמ' בפסחים (שמק' מרבי יהודה זה, ולא משיב שכיון שכבר יש מח' בו, יכול להיות עוד חולק. ויל"ד.). ר"ת תי' שזה מונה מתחילת שקיעת החמה, אבל בין השמשות (והוא מה שמזכיר גמ' בשבת) מתחיל בסוף השקיעה. (לכאו', תחי' שקיעה הוא הזמן שקצת מן החמה שוקע, וסוף שקיעת החמה הוא הזמן שכל החמה משקע.) אחרים תירצו שצאת הכוכבים של גמ' שני אינו לילה, אלא הוא הזמן שיש הרבה כוכבים נראים.
1. כעין זה, מצאנו שרבא סובר שהוא 1/8 של יום. זה נדחה בגמ'. לצד אחד שהזכרנו, אין זה שייך בכלל לבין השמשות. אף אם שייך, יש לדון אם חול' בהמשך שקיעת החמה, שאז לא שייך, או מתי מתחיל או גומר בין השמשות. ותחשב.
2. רבי יוסי- רבי יוסי רק אומר משך של בין השמשות, והוא שכהרף עין (סתימת העין ברפיון) הוא. יש ארבע שיטות מתי הוא אותו הרף עין של בין השמשות:
  1. בבלי אומר (שבת) שהוא אחרי גמר בין השמשות של רבי יהודה.
  2. בבלי מצדד נגד זה (בנדה) שהוא באמצע של רבי יהודה. (מסתמא, יש ספק בכל רגע של ביה"ש של רבי יהודה.)[fn:6]
  3. ירושלמי מצדד שהוא אחרי גמר בין השמשות של רבי נחמיה.
  4. ירושלמי מצדד שהוא באמצע של רבי נחמיה. (מסתמא, יש ספק בכל רגע של ביה"ש של רבי נחמיה.)
3. שיטה אחת שניתוסף בירושלמי- מיציאת שני כוכבים עד יציאת ארבע כוכבים. (כל זמן שאנו נדון בכוכבים, נדון בכוכבים בינונים[fn:7].)
4. שיטה שנית בירושלמי- ממקצת אחרי יציאת כוכב אחד[fn:8] עד יציאת שני כוכבים.
5. שיטה שלישית בירושלמי- משעה שהתחיל חמה לשקע, שמתחיל לבנה לעלות באמצע חדש, הוא בין השמשות. לא מפרש עד מתי נמשך.
6. שיטה רביעית שבירושלמי- מססוף שקיעה של החמה, שמתחיל לבנה לעלות באמצע חדש, הוא בין השמשות.[fn:9] לא מפרש עד מתי ממשיך.
7. שיטה חמישית שבירושלמי- זמן שטיפה של דם מתחלק על ראש חרב. (הוא זמן קצר מאד.) (יש שכ’ שהוא כהרף עין, אבל לא נ’ כן מפני משה.)
8. שיטה ששית שבירושלמי- ירושלמי מבאר שיש חולק, ומוכיח מקושיה שיכולים להקשות. מקשה איך אפשר להיות שבקר, כל זמן שהחמה הוא בעובי הרקיע, יום הוא, אבל בלילה, יכול להיות לילה באמצע עובי הרקיע (שבאים שני כוכבים כשהחמה הוא עדיין שם). אבל, יש לדון אם סובר שנעשה לילה כשנכנס לעובי רקיע (וכמו יום, נמשך אז הזמן שלפניו) או שנעשה לילה כשיוצא מעובי רקיע (אבל כל זמן שהוא בעובי רקיע, יום הוא, כמו בבקר.)[fn:10]
9. שמואל אומר שמזמן שיש שני כוכבים בינונים[fn:11] עד זמן שיש שלש הוא בין השמשות. (עיין במה שהבאנו מירושלמי. אפשר שגם שמואל כוון למה שאומר ירו', כמו שמשנה ירו' את פי' השיטה שם.) גמ' גם מוסיף שמי שלא שיעור של רבנן (לא פשוט לאיזה שיעור מכוון) יכול לדעת שקודם ששמש בראש דקל, וכן כשתרנגולים ועורבים יושבים על הקורות, ובשעה שכפופים עשבים עוד לחמה, אינו לילה.
כמובן, אין הכרח שכל אחד חולק על חבירו. אפשר שיש מאלו שהם שווים לאחרים.
נמצא, בין הכל, כמה דברים:
מתי מתחיל:
מצאנו לזה שבע צדדים:
1. בשקיעת החמה. יש שלש צדדים בביאור זה:
  1. יראים אומר שהוא כשנוטה החמה לשקע.
  2. תחילת שקיעתו. כן אומר שיטה אחת שבירושלמי.
  3. רבינו תם אומר שהוא סוף שקיעתו. לכאו', זה כשכל החמה שקע כבר. כמו כן אומר שיטה אחת שבירושלמי.
  4. אפשר שהוא זמן אחר שבשקיעה. השנים שהם מסתברים הם תחילת שקיעה או אמצע שקיעה.
כן סובר רבי נחמיה, וכן סובר שיטה אחת ברבי יהודה, ואולי רבי יוסי.
1. אחרי שיעור של רבי יהודה. כן מצדד בבלי לפי רבי יוסי.
2. אחרי שיעור של רבי נחמיה. כן מצדד ירושלמי לפי רבי יוסי.
3. כשפני מזרח מאדים. כן סובר שיטה אחת ברבי יהודה.[fn:12]
4. אחרי יציאת שני כוכבים. כן סובר שיטה אחת בירושלמי וכן אומר שמואל.
5. קצת אחרי יציאת כוכב אחד. כן סובר שיטה אחת בירושלמי.
6. זמן אחר. יכול להיות כן לפי שיטה אחת בירושלמי, שלא מבאר מתי מתחיל. גם מצדד בבלי ורישלמי לפי רבי יוסי שהוא זמן אחר, אבל מגבילים אותו זמן, צריך להיות בתוך של רבי יהודה (כן אומר בבלי) או בתוך של רבי נחמיה (כן אומר ירו').
לא מוכרח שכל אחד מאלו חולקים זה על זה, ואפשר שיש מהם שהם שווים.
מתי נגמר:
מצאנו בזה חמש צדדים:
1. צאת הכוכבים. גמ' במגילה וירו' דורשים את זה מקרא (וירו' אף מקשה מזה), אבל גמ' בברכות משמע שהוא רק זכר לדבר.[fn:13] חולקים כמה כוכבים צריך:
  1. ירושלמי מניח בפשטות שצריך שנים. אבל, שוב חוזר מזה. אבל, עדיין יש שיטה אחת בירושלמי שסובר כן.
  2. כשיוצאים ארבע כוכבים. יש שיטה בירושלמי שסובר כן.
  3. כשיוצאים שלש כוכבים. שמואל סובר כן.
2. כשהשחיר עליון של הרקיע, עם התחתון שלו. כן סובר רבי יהודה.
3. ירשלמי מביא שיטה שסובר שהוא כשחמה נכסת לעובי הקריע או אולי סובר שהוא כשחמה יוצאת מעובי רקיע.
4. יש זמנים שמוגדרים על פי זמן התחלתו- הוא זמן מצומצם אחרי התחלתו.
5. אולי יש זמן אחר. (זה אפשר לצדדים שלא מבארים מתי סוף.)
כמו כן כאן, לא מוכרח שחולקים.
משך בין השמשות:
מצאנו בזה שש צדדים:
1. חצי מיל. כן סובר רבי נחמיה.
2. ¾ מיל. כן סובר רבה לפי רבי יהודה.
3. 2/3 מיל. כן סובר רב יוסף לפי רבי יהודה.
4. כהרף עין. כן סובר רבי יוסי.
5. כזמן שטיפה של דם מתחלק על פי חרב. כן סובר שיטה אחת בירושלמי.
6. יש אחרים שמזכירים תחילה וסוף, אבל לא מזכירים כמה זמן הוא ההמשך.
גם בזה לא פשוט מי חולק על מי.
עוד:
בין השמשות הוא ספק יום וספק לילה (וספק שמקצתו יום ומקצתו לילה). ואם תאמר כיון שדורשים שצאת הכוכבים הוא לילה (למקצת שיטות), למה זה ספק. ויש לומר שמסופקים מה נחשב צאת הכוכבים. גם יש לומר שחושבים שהם גם היו מסופקים (וקראו לו לילה כיון שהיה ודאי לילה). ויש לדון למה נאמר כן.
כשיש מחלקת, יש לדון אם תלוי באיזה מין כוכבים צריכים או כמה מין ראייה צריכים או לכמה זמן צריכים שכבר יהיה נראה או אם תלוי בכוכבים בכלל. ותחשב.
למס', גמ' פוסק כרבי יהודה (לא מפרש איזה) ורבי יוסי, כחומרות של כל אחד. (יש לדון אם הוא כן גם בשאר שיטות, שגם מחמירים כמותם.)[fn:14]
* Footnotes
[fn:1] רש"י שם פי' שרצה לומר שיראה את החמה על ראש הכרמל. מירו' מוכרח נגד זה, ואז צריך לומר שרש"י סובר שירו' ובבלי לא נותנים אותו סימן.
[fn:2] לא מפרש איפה מתחיל, ולא מפרש לאן עולה. אז, מסתבר לומר שמתחיל קרוב לים, וטובל ועולה לקרוב לים.
[fn:3] יש לדון אם יעלה להר כרמל או יעלה מן הים.
[fn:4] נראה שהסדר הוא שמתחיל להתאדם, והאדום נעשה יותר ויותר קרוב לשחור עד שנעשה שחור. (יש לדון מה, בדיוק, הוא הזמן שנחשב שחור.)
[fn:5] זה לא כל כך ברור לי. עיין בירושלמי, שבאמת, רק אומר כרב יוסף. אז, היה אפשר לפרש אותו כמו שאמר רב יוסף (וכפירוש רבא, שמסתמא הוא מסקנא של הגמ'). אבל, פני משה לא פי' כן. אפשר שפני משה רק רוצה לחלוק על הבבלי (הפני משה תמיד מוזר וקשה להבין), אבל יותר מסתבר לומר שפני משה סובר שסתימות הירושלמי משמע שחולק על הבבלי. אבל, יש להעיר שאז צריך ביאור איזה קודם. איזה שקודם, יש להקשות, לפי אחד, מה שהקשה בשבת, והוא שיש דיוקים סותרים בין זה לזה. (אפשר לדחות שהאדים מזרח הוא מיד לפני הכסיף מזרח והאדים מערב הוא מיד לפני הכסיף מערב. אז, אפשר שגם "הכסיף" לא שווה, ואז בשניהם אין דיוק הסותר. ותחשב.) נראה שרק מצאנו שרב יוסף חש לזה, ואז צריך לומר שתחילה מאדים פני מזרח, ושוב פני מערב, ושוב הכסיף. אז, נתרץ לירושלמי כמו שתירץ רבה לבבלי. ותחשב.
[fn:6] ואם תאמר אם כן אין נפקא מינא ביניהם. ועיין בירושלמי (שנביא ב4), ששם, בירו', משמע שחושב שיש נפקא מינא. וצריך לעיין שם.
[fn:7] באמת, אין זה פשוט, שיש לומר שזה רק לענין מה שצריך שלש או ארבע להיות לילה. אבל, אולי מתחיל בין השמשות אף בשנים גדולים. וחתשב.
[fn:8] אומר שכוכב אחד יום. אבל, בין כוכב אחד לשני כוכבים, ספק הוא.
[fn:9] כמובן, קצת צריך ביאור למה לא נסתכל בלבנה.
[fn:10] יש להעיר שאפשר שהראשון הוא כיראים, ואפשר שהשני הוא כרבינו תם.
[fn:11] עיים שם, שרבי יוסי מוסיף נקודה זו. ק"ק, שלכאו' לפי רבי יוסי זה לא שייך. ויש לדון, שאולי מודה שאז לילה הוא, ובין השמשות הוא הרף עין שלפניו. וזה תלוי באם גם מסופקים מתי ביה"ש של רבי יוסי הוא. ותחשב.
[fn:12] אולי יש גם זמן אחר להתחיל לפי רבי יהודה, והוא מה שדנינו בו בירושלמי.
[fn:13] ויש להעיר שאף שירו' אומר שהוא זכר לדבר, מקשה ממנו. אפשר לומר שהוא רק זכר לזמן קריאת שמע, ולא ללילה.
[fn:14] מראה מקומות לזה: ברכות (ב), שבת (לד), נדה (נג), ירושלמי (ברכות א, א).
