- יש שלש מחלקתים בין רב לשמואל שבהם רבה הקיל כשמואל. בכל השאר, הקיל כרב או החמיר (או כרב או כשמואל).
השלש הם:
1. מדליקים מנר לנר. גמ’ מפרש שני מהלכים בביאור מחלקת זה:
  1. חולקים אם שימוש במצווה נחשב ביזוי מצווה.[fn:1]
  2. חולקים אם מותר להכחיש מצווה.[fn:2]
2. מתירים ציצית מבגד לבגד. ע’ ברש"י כאן, שכ’ שטעמו מפורש במנחות. אינו כן, אבל רש"י פי’ שם שהוא מחמת בזיון של טלית ראשון. לכאו’, אז, צריך ביאור מה בין מח’ זה למח’ ראשון, ולמה מונה אותם לשנים. (לכאו’, גם, יהיו שני צדדים במח’ זה, כמו שהיו שני צדדים במח’ ראשון.)
3. הלכה כרבי שמעון בגרירה. חול’ רבנן ור“ש אם דבר שא“מ מותר או אסור. הל’ כר“ש שמתיר.
היה אפשר לומר שכולם תלויים זה בזה, והוא שחולקים אם הולכים בתר איך שסתם בני אדם יחשבו על מעשים שלו או איך שהוא מחשיב אותם. זה נוגע לענין בזיון, אם מחשבים דעתו, שיודע למה הוא מדליק או מתיר, או בתר דעת בני אדם, שלא יודעים למה הוא מדליק. גם בדבר שא“מ, דנים אם דעתו מספיק להתיר לכולם ללכת.
- גמ’ מקשה על פשט אחד שנותן גמ’ בביאור מחלקת בין רב לשמואל. חולקים רב ושמואל אם אסור להדליק מנר לנר או מותר להדליק מנר לנר בנרות חנוכה. מביא משנה. משנה מדבר במי ששוקל דבר כנגד מעשר שני, ואוסר, אפילו אם שוקל כדי לחלל עליו. לכאו’, אז, נפרש הבעיה לפי שני השיטות. גמ’ דן למה ייאסר הדלקה מנר לנר, אם הוא מפני הבזיון או מפני שמכחיש את המצווה. לכאו’, כאן, האיסור צריך להיות בזיון. אז, לכאו’, נראה שיש איסור מחמת בזיון, וצריכים לומר שכולי עלמא מודו לזה, שהרי יש בריי’ לזה.
מה שקצת מוזר בגמ’ זה הוא שכשמוכיח כן גמ’, לא אומר צדדי הביאור, אלא אומר אותם בתוך נפקא מינא שלהם. יש נפק“מ לדין בין שני הצדדים בביאור המחלקת, והוא כשמכחיש אותו ולא מבזה. זה נמצא כשמדליק מנר לנר בלי משהו ביניהם, שאז מכחש את המצווה, אבל לא מבזה אותו. אז, דן גמ’ בראיה זה באותו לשון.
- גמ’ שואל אם הדלקה עושה מצווה או הנחה עושה מצווה. לא מובן לי שאלה זו כל כך. לכאו’, אם מדברים בציור שהדליק אותו ושוב הניח אותו, לא זה ולא זה עשה את המצווה, שלא קיים את המצווה, כמו שיבאר גמ’. אז, צריך לומר שהניח ושוב הדליק. פשוט שלא קיים מצווה בהנחתו, שצריך להדליק אותו תחילה. אפשר שכיון שצריך שני דברים- שיהיה אש, ושיהיה כאן- ולזה צריך שני מעשים, דהיינו הבערה והבאת מה שמקבל את ההבערה, דן איזה הוא היותר חשוב. אבל, צריך ביאור איך יהיה אחד יותר חשוב. רואה אני איך נוכל להגיד שהאחרון יותר חשוב, שמה שאין דבר בינו לבין התוצאה של קיום מצווה מייחס אותו לקיום. אבל, איני רואה איך נצדד שהנחה הוא העיקר. אולי הענין הוא שמאותו שעה כבר עומד לגמור אותו. אז, הוא סיבה גם לסיבה שנית. ותחשב. גם אפשר לומר ש"הנחה“ לא רצה לומר הנחת מנורה שם, אלא הנחת אש שם. אז, דיון גמ’ הוא אם המצווה הוא שהדליק או שגרם שיהיה אש שם. לא כל כך פשוט מה יהיה הצד, אז, שהדלקה עושה מצווה. לכאו’, רבנן רצו דבר- רצו שיהיה פרסום הנס. זה בא על ידי שיש אור שם. אז, רצו שישים אור שם (באופן שיהיה פרסום). אולי דן איזה פרסום רצה תורה, פירסום שבא על ידי שיש אור שם או שבא על ידי שעשה מעשה הדלקה. ותחשב. וצריך ביאור.
- לרבי שמעון בן אלעזר יש מימרא: מסככים בכל היוצא מן העץ חוץ מבפשתן. לשונו- בפשתן, ולא בבגד פשתן- משמע שממעט כל פשתן שיש, ואף שאינו בגד, כיון שמטמא בנגעים (של שתי וערב). אביי מעורר שמצאנו תנא אחר שגם סובר כאותו חידוש, שלא מסככים בדבר שיש בו טומאת נגעים (אף שאין בו טומאה אחרת). סומכוס אומר שלא מסככים בחוטים שנטוו, שאחרי טוייתם, נעשים ראויים לטומאת נגעים.
יש שני פשטים בגמ’ שיבוא, ונבאר כ“א בפני עצמו.
גמ’ אומר ששיטת סומכוס הוא כתנא אחר שמצאנו. חולקים רבי מאיר ורבי יהודה מתי דבר נחשב שתי וערב כדי לטמא, אם הוא מיד אחרי טוייה או שגם צריך ליבון ביורה (וצ’ גם שלייה מאותו יורה) או בתנור. סומכוס שפוסל משנטוו סובר כרבי מאיר.
גמ’ אומר שאביי הוא כתנא אחר שמצאנו.[fn:3] חול’ ר“מ ור“י מתי דבר נחשב שתי וערב, אבל מה שחשוב לגמ’ שלנו הוא שבתוך הדיון, רבי יהודה אומר זמן של טומאת אונים של פשתן. אונים של פשתן הם לא בגדים- ואף על פי כן, הם מטמאים בנגעים. אז, רואים כמו שאמר אביי.
* Footnotes
[fn:1] כן נראה. גם אפשר לפרש שחולקים אם מותר לבזות מצווה. ודע שבין לזה ובין לזה, צריך ביאור אם מותר להשתמש לאור של המנורה של חנוכה, שלא נראה לי שיהיה חלוק מזה. נראה ששמואל מתיר רק מפני שהוא, לבסוף, למצווה, שהוא להדליק נר אחר של חנוכה. ויש להעיר שאין השני מצווה כמו הראשון, שהראשון הוא חיוב. ויש לדון, שיש לומר שרק מיירי בהדלקה מן השני. סתימות גמ’ לא משמע כן. ותו"ת. וע’ בגמ’ לקמן (גבי חילול מעשר). אבל, עדיין יש לדון אם צרך להיות שיש שימוש חשוב לו או שימוש של מצווה בדווקא.
[fn:2] אף כאן, יש לדון אם חולקים אם יש שום הכחשה במצווה זו וגם יש לדון אם שמואל יתיר אף בלי שייכות למצווה. ותו"ת.
[fn:3] כן הוא לשון רש"י, והכוונה הוא ככה: אביי הניח שרשב“א לא מדבר בבגד. אז, צריך לומר שסובר שפשתן מטמא בנגעים, אף קודם שהוא בגד. אותו שיטה הוא שיטה של תנא אחר שנביא.
