** האוכל חצי פרס[fn:1][fn:2] אוכל טמא -
אם אכל אוכל שהוא ראשון, חולקים רבי אליעזר ורבי יהושע מהו דינו. רבי אליעזר אומר שהוא ראשון (שמצאנו בנבלת עוף טהור שאוכל יותר טמא ממאכל, ואז לא נעשה המאכל יותר טמא כאן[fn:3]) ורבי יהושע אומר ששני הוא (שלא לומדים מנבלת עוף, שחי’ הוא, אלא לומדים מן השיעור, שבו אוכל יותר קל ממאכל).[fn:4][fn:5]
אם אכל אוכל שהוא שני, הוא שני. כאן, אף רבי יהושע מודה, כיון שמצאנו שני שעושה שני (על ידי משקין).
אם אכל אוכל שהוא שלישי שנעשה על טהרת תרומה, רבי אליעזר אומר שהוא שלישי (כמו שסובר בכל מקום, שנותן לאוכל דין של המאכיל) ורבי יהושע אומר שהוא שני לקודש (כיון שטהרת תרומה לא שומר לקודש).
אם אכל אוכל שהוא שלישי שנעשה על טהרת קודש, רבי אליעזר אומר שהוא שלישי, ורבה בר בר חנא בדברי רבי יוחנן בדברי רבי יהושע אומר שהוא שלישי[fn:6] ורבי זירא בדברי רבי יוחנן אומר שהוא שני (לא מבאר גמרא למה).[fn:7]
כדי לטהר את עצמו, לכאו’ צריך לטבול במקווה והערב שמש.[fn:8]
גזרו בית שמאי ובית הלל על זה בעליית חנניה בן חזקיה.
טעם של כל תקנות אלו הוא שחששו רבנן שיאכל אוכלים טמאים וישתה משקים של תרומה באותו זמן. אז, יטמאו משקים של התרומה מאוכל הטמא. לכן, גזרו בו טומאה שלא מרשה לו לאכול תרומה.[fn:9]
** השותה רביעית[fn:10] משקים טמא-
דינו שווה לדין אוכל אוכל טמא[fn:11].
גזרו בית שמאי ובית הלל על זה בעליית חנניה בן חזקיה.
טעם של תקנה זו הוא שחששו רבנן שישתה משקים טמאים ויאכל תרומה באותו זמן. אז, יטמא אוכל תרומה ממשקים הטמאים. לכן, גזרו בו טומאה שלא מרשה לו לאכול תרומה.[fn:12]
** הבא ראשו ורובו למים שאובים-
אם אדם בא ראשו ורובו למים שאובים (מים שניתן בכלי לרצון), הוא שני.
גזרו בית שמאי ובית הלל על זה בעליית חנניה בן חזקיה.
טעם של תקנה זו הוא שהיו בני אדם רגילים לרחוץ במים שאובים אחרי שטבלו במקווה (כיון שמי מקווה היו סרוחים), והתחילו לחשוב שלא צריך לטבול במקווה, אלא לרחוץ במים שאובים כדי להיטהר.[fn:13]
** מי שנופל שלש לוגים מים שאובים על ראשו ורוב-
אם נפלו שלש לוגים מים שאובים על ראשו ורובו של אדם, הוא שני.
גזרו בית שמאי ובית הלל על זה בעליית חנניה בן חזקיה.
טעם של תקנה זו הוא כדי לחזק לתקנת טומאה של הבא ראשו ורובו למים שאובים.[fn:14]
** ספר קודש-
ספרים מתנ"ך הם שני.
גזרו בית שמאי ובית הלל על זה בעליית חנניה בן חזקיה.
טעם של תקנה זו הוא כדי שלא יצניעו בני אדם תרומה עם ספריהם (כך היו עושים, כיון ששניהם היו קדושים), כיון שזה גורם שעכברים באים ומזיקים את הספרים.[fn:15]
** ידים -
ידים הם שני.
היו שלש גזירות על ידים. בתחילה, שלמה גזר שידים פוסלים[fn:16] את הקודש (ועל זה שמח קרא וכ’, “בני אם חכם לבך…"). באו הלל ושמאי וגזרו שהוא שני גם לתרומה, אבל בני הדור לא קבלו את הגזירה. באו תלמידי בית שמאי עם תל’ בית הלל בעליית חנניה בן חזקיה וגזרו עוד שהוא שני לתרומה, ואז קבלו את הגזירה.[fn:17][fn:18]
כדי לטהר את ידיו, צריך ליטול אותם. נטילה זו מהני עד שמסיח את דעתו מידיו.
אם נטמא תרומה מחמת טומאת ידים, שורפים אותו.[fn:19][fn:20]
טעם של תקנה זו הוא שידים עסקניות הם. רש"י מבאר שבגלל זה, מצוי שהם מאוסים, וגנאי הוא לתרומה. (גם מביא פשט שבגלל זה חוששים שנגעו בטומאה.)[fn:21]
** ידים שנגעו בספר:
ידים שנגעו בספר מתנ"ך הם שני.
לא ברור מי גזרו על זה; עיין במה שדנינו בזה בסיכום "שמונה עשרה דבר.”
וא"ת מה מוסיף תקנה זו על תקנת ידים. מזה מוכיח גמ’ שנתקן קודם תקנת ידים. תוס’ מסביר שמוסיף דין, שאם נגע בספר, ידיו טמאים אף אם לא הסיח דעת מהם, אבל לא היו גוזרים אם רק היה מוסיף אותו דין קטן.[fn:22]
טעם של התקנה הוא להרחיק אותו מלגעת בספר, כיון שמי שנוגע בספר בידיו לא מקבל שכר של המצווה שעשה עם הספר אז.[fn:23]
** ארץ העמים:
אויר ארץ העמים וגוש (שיעור גורש ארה"ע שמטמא הוא כפיקה גדולה של סקאין, שהוא שווה לחותם המרצופים.[fn:24]) ארץ העמים מטמאים[fn:25].
בגמ’ יש דיון ואולי מחלקת אם גזרו על גוש והמאהיל עליו או גם על אויר.
יוסי בן יועזר ויוסי בן יוחנן גזרו לתלות מגוש ארץ בעמים, ושמונים שנה קודם חורבן בית שני, רבנן גזרו לתלות גם מאויר אה"ע[fn:26], ורבני אושא[fn:27] גזרו לשרוף מגוש אה"ע.[fn:28]
חולקים אם צריך הזאת מי חטאת כדי להיטהר.[fn:29]
טעם של גזירה זו היא שחששו בכל מקום באה"ע שנקבר שם גוי.
** כלי זכוכית:
כלי זכוכית מטמא ככלי מתכת, עם שני חילוקים- שבירה מטמא אותם (ע’ לקמן), ואין פשוטים של כ"ז מקבלים טומאה. (עיין לקמן, שנבאר טעם של אלו.)
אין שורפים תרומה מח’ טומאה זו, אלא רק תולים.
לא פשוט לי אם יש להם טהרה במקווה.[fn:30] (אם אין להם טהרה, יש עוד חילוק בינו לבין כלי מתכת.)
מצאנו שיוסי ויוסי תקנו זה ומצאנו שרבנן תקנו את זה שמונים שנה קודם החורבן, ולא משיב גמ’ לסתירה זו.
טעם של תקנה זו הוא שדומים לכלי חרס, כיון שבאים מחול.[fn:31] חולקים למה לטומאה שלו יש גדר של כלי מתכת. אולי הוא מפני שיש לו דמיון לכלי מתכת, במה ששניהם יש להם תקנה אם נשתברו.[fn:32] אז, הסיבה לחילוקים הוא שלא גוזרים בו דינים דרבנן (של טומאה אחרי שבירה) ושמקילים כדי לדעת שלא לשרוף תרומה עליהם. אולי דינם ככלי מתכת כיון שנגיעת חוץ שלהם כביאת תוך של כ"ח, כיון שנראה תוכו מחוצו.[fn:33]
** כלי מתכת שנשבר:
אם כלי מתכת נטמא, ונשבר כשיעור, נטהר מדאו’. אבל, מדרבנן, נשאר עליו טומאה. חולקים אם זה רק בטומאת מת או גם בכל טומאות. אולי יש יוצא מכלל זה, והוא כלי שנשבר לגמרי.[fn:34]
שמעון בן שטח תקן זה.
טעם של תקנה זו הוא מח’. אם הוא רק בטומאת מת, הוא כדי שלא יישכח מי חטאת. אם הוא בשאר טומאות, אביי אומר שהוא מפני חשש שלא ישבר אותו כשיעור, ורבא אומר שהוא מחשש שיראה כטהרה בלי הערב שמש.[fn:35]
** בית הפרס:
שדה שנאבד בה קבר או שדה שהיה בה קבר ונחרש טמא.
שורפים לתרומה שנטמא בזה.
רבנים של אושא גזרו על זה.
טעם של תקנה זו הוא שחוששים שנטמא בטומאת מת.
** בגדי עם הארץ:
בגדים של עם הארץ הם טמאים.
שורפים לתרומה שנטמא בזה.
רבנים של אושא גזרו על זה.
טעם של תקנה זו הוא שעם הארץ לא שומר את בגדיו מטומאה, ויש לחוש שאשתו נדה ישבה עליהם ועשה אותם לטומאת משכב.
** כלים הנמצאים:
כלי הנמצא טמא.
שורפים לתרומה שנטמא בזה.
רבנים של אושא גזרו על זה.
טעם של תקנה זו הוא שחוששים שהכלי נטמא.
** הרוקים:
רוק הנמצא טמא.
שורפים לתרומה שנטמא בזה.
רבנים של אושא גזרו על זה.
טעם של תקנה זו הוא שחוששים שרוק זה בא מזב, ואז הוא טמא.
** מי רגלים:
מי רגלים שנמצא- אף אם לא יודע אם הם של אדם או של בהמה[fn:36]- הם טמאים.
שורפים לתרומה שנטמא בזה.
רבנים של אושה גזרו על זה.
טעם של תקנה זו הוא שחוששים שמ"ר אלו באו מן הזב, ואז הם טמאים.
** מטלטלים כעובי מרדע:
מדאו’, כלי נעשה אוהל להמשיך טומאת מת רק אם עוביו הוא טפח. אז, אם הוא גלגל, היקפו צריך להיות שלש טפחים.[fn:37] אבל, מדרבנן, אף אם היקיפו טפח (ועוביו הוא ) מטמא.
בית שמאי ובית הלל תקנו את זה בעלייה של חנניה בן חזקיה.
טעם של תקנה זו הוא שחוששים שבני אדם יחשבו שכמו שאינו מטמא כשעביו טפח, כיון שידעו שלא מטמא כשהקיפו טפח.[fn:38][fn:39]
כל זה שיטת רבי עקיבא. אבל, רבי טרפון סבר שלא גזרו כן, ואינו מטמא עד שעביו טפח, שאז מטמא מדאו’.
** תרומה טמאה שזרע:
אם אדם זרע תרומה טמאה, אף שמדאו’ נטהר, מדרבנן לא נטהר.[fn:40]
טעם של תקנה זו הוא שחוששים שישאיר תרומה טמאה אצלו כדי לזרעו. קודם שיזרע אותו, אולי יאכל אותו באיסור.[fn:41]
** בנות כותים:
כל נדה טמאה, ואפילו קטנה, מדאו’. כיון שכותים לא דורשים כן, לא מודיעים לנו על נדות קטנות שלהן. חוששים שכל קטנה כותית נדה.
ב"ש וב"ה גזרו על זה בעליית חנניה.
למטה, נבאר הטעם לזה. [fn:42]
** כל תינוק נכרי מטמא בזיבה:
תינוק נכרי מטמא כאילו היה זב.
ב"ש וב"ה תקנו את זה בעליית חנניה.
תקנו כן כדי שלא יהיה רגיל תינוקות בנ"י לשחק עם תינוקות עכו"ם, כיון שתינוקות עכו"ם מרגילים אותם במשכב זכר.
* Footnotes
[fn:1] מעילה יז:
[fn:2] עיין בטעם התקנה. וא"ת אם כן למה תקנו שיעור. ויש לומר שכיון שאוכל יותר, הוא בפיו ליותר זמן, ויכלו להיות יותר זמן שישתה משקין של תרומה. כמו כן, כיון שאוכל יותר, ירצה יותר לשתות.
[fn:3] וא"ת אם כן יהיה יותר טמא ממנו. ויש לומר שאין זה אותו חומרה שמצאנו, ואז אין ללמוד חומרה זו.
[fn:4] לכאו’, אין אלו לימודים, שכל הדין הוא מדרבנן. אלא, אלו סיבות שיגידו לרבנן מה לגזור.
[fn:5] חולין לד.
[fn:6] יודעים שאינו שני. אבל, אולי אף מקילים, ואינו אף שלישי. וצריך ביאור.
[fn:7] חולין לד
[fn:8] כן נניח בכל שלא נבאר נגד זה.
[fn:9] שבת יד.
[fn:10] מעילה יז:
[fn:11] יש להעיר שכל משקים ראשונים. אז, לכאו’, דינו שווה לאוכל אוכל ראשון, ויהיה בו מחלקת רבי אליעזר ורבי יהושע. יש לדון, שיש לחלק שכאן אין כל כך סיבה לגזור, כמו שאומר גמ’ בשבת (יד.), ואזנ אולי אף רבי אליעזר מקיל. יותר מזה, איננו ראשון מדאו’, אלא רק מדרבנן, ואז אפשר שר"א לא מחמיר בו כאוכל ראשון מדאו’. (שו"ר בתוס’ שבת (יג:).)
[fn:12] שבת יד.
[fn:13] שבת יד.
[fn:14] שבת יד.
[fn:15] שבת יד.
[fn:16] יש לדון אם גזר שהם שני או שלישי.
[fn:17] עיין בע"ז (לו.) שנ’ שחלקו אם צריכים לעשות כגזירה שלא קבלו רוב בני ישראל. אם לא צריך לשמוע, מובן למה ב"ה וב"ש גזרו עוד. אם צריך להקשיב לו, צריך לומר שלא חזרו וגזרו, אלא חזרו לקיים את הגזירה, שחזרו והגידו לבני אדם מה שצריכים לעשות, והפעם שמעו להם. ותחשב. (וא"ת אם כן למה בתחילה לא רצה ב"ה להגיד להם. וי"ל שסברו בתחילה שכיון שלא קבלו אותו בנ"א אין צריכים להקשיב לו. גם יש לומר שסברו שלא יגידו להם ב"ד עוד פעם, שמסתמא לא ישמעו.)
[fn:18] שבת יד:
[fn:19] שבת יד:
[fn:20] בהרבה מאלו לא מבאר גמ’ אם לשרוף אם לתלות, ואיני יודע את הדין.
[fn:21] שבת יד.
[fn:22] שבת יד:
[fn:23] שבת יד.
[fn:24] בכורות כב.
[fn:25] איני יודע באיזה דרגה מטמאים.
[fn:26] לכאו’, זה צריך להיות כמי שאומר שגזרו על אוירו. ויש לדון, שאולי כאן "אויר" רק רצה לומר "מאהיל על גושו.”
[fn:27] עיין בר"ה (לא) שהיו הרבנן באושא פעמיים.
[fn:28] שבת טו:
[fn:29] נזיר נד:
[fn:30] עיין בגמ’ שבת טו:, שמדמה אותם לכלי חרס, ומקשה ממשנה שאומר שיש להם טהרה במקווה. שם, דוחה את הקושיה, אבל לקמן מוכרח לומר שיש לו דינים של כלי מתכת. אז, קל לומר שחוזר גם לאותו קושיה לומר שגם דין זה של כלי מתכת יש לו. כן נ’ קצת מלשון רש"י בד"ה טמאתן ישנה, אבל יש לדחות ששם בווודאי לא יהיו דינם ככלי חרס כיון שאין לכ"ח אותו חומרה.
[fn:31] כן אומר גמ’ (טו:), אבל אפשר שזה נשתנה כשמתרץ גמ’ ש"כיון דכי נשתברו יש להם תקנו, שוינהו ככלי מתכת,” שאולי אומר שדמיון שלהם לכלי מתכת הוא הגורם להם טומאה. אבל, פשטות לשון הגמ’ לא משמע כן, ואז פרשנו פי’ אחר.
[fn:32] וא"ת גם לכלי חרס יש תקנה. וי"ל שאין תקנה לו בלי ביטול הכלי.
[fn:33] אם כן, לכאו’ גם יטמא מאוויר שלו. וצריך לע’ אם כן הוא הדין. אולי גזרו על זה כדי שלא לשרוף (אבל, אז צריך לומר שגמ’ מניח שבגלל זה בלחוד לא היינו יכולים לבאר למה רק ממטמא בחוץ ולא בפנים). ותחשב.
[fn:34] לכאו’, זה לא יוצא מן הכלל לפי הטעם הראשון שבארנו. גמ’ אומר את זה לנפקא מינא בין טעם שני לטעם שלישי, ורשי דן לפי איזה מהם יהיה הכלי טהור.
[fn:35] אם כן, לכאו’ אם מעריב שמש יהיה מותר. אבל, לא משמע כן מגמ’, שרק נותן נ"מ אחר.
[fn:36] משמע שברוק צריך להיות שנודע ששל אדם הוא. (וצריך לעיין במציאות אם יכולים להבחין בין רוק אדם לרוק בהמה.)
[fn:37] באמת, כדי שיהיה עוביו טפח, צריך להיות שהיקיפו π טפחים, אבל בכ"מ אומר גמ’ שלש במקום π. ראשונים דנים אם גמ’ אינו דווקא או שקבעו את הדין כאילו היה שלש, כדי להקל על החשבון.
[fn:38] לכאו’, אין הכוונה שיחשבו שהיקף ועובי יש להם אותו דין, אלא ישמעו הדין, וישכחו שנאמר על היקף ולא על עובי.
[fn:39] שבת יז.
[fn:40] יש לדון אם גם גזרו עליו טומאה או רק איסור לאכול (יש נפקא מינא אם היה טמא שני וכדו’).
[fn:41] שבת יז:
[fn:42] צריך לע’ בסוגיה בנדה (לא:, לב.). משם יוצא שחוששים רק לפי רבי מאיר, כיון שחיישינן למועט. אם כן, צריך לומר שרבי מאיר סובר כן רק מדרבנן, שהרי רואים מכאן שהיה גזירה, שכל שמונה עשרה דברים אלו הם תקנות. תוס’ שם דוחה שכאן מיעוט שלא מצוי הוא שתהיה נדה בשעת לידה (אף שגמ’ שם מביא מעשה לומר שמיעוט המצוי הוא שתהיה נדה בתוך שלשה יום. ויש לדון, שאולי רצה לומר שאם זה קרה, בוודאי ראייה אחריו הוא מיעוט המצוי), ואז יש חזקה שאומר שלא לחוש למיעוט המצוי. וא"ת אם כן זה רק שיטת רבי מאיר, והחולקים לא יהיה להם שמונה עשרה דבר. תוס’ תי’ שיש טעם אחר לגזי’ זה, והוא שלא נטמע בכותים, אלא שגמ’ שם קאי על המשנה, ומאותו משנה מוכרח לומר הטעם של חשש למיעוט.עיין שם, שבמשנה ממשיך לומר שכותים מונות נדה באופן חלוק משאנו מונים. וא"ת אם כן נגזור על קטנות מחמת זה. ויש לומר שזה רק נוגע לומר שטבילות לא יטהרו כמו שהיו מטהרים אם היו כדינם. אבל, אין מי שמטביל קטנה, ואז זה לא ישנה כלום, ואילו היו מודיעים לנו על נדות, לא היה זה סיבה לטמא.
