סימנים של חגבים טהורים:
יש ששה סימנים, ארבעה סימנים מוסכמים, ושני סימנים שיש בהם מחלקת:
יש לו ארבע רגלים[fn:1]. זה כתוב בפירוש- "אך את זה תאכלו... ההולך על ארבע."
יש לו ארבע כנפים. לומדים את זה מן הארבע המפורטים, שלכולם יש ארבע כנפים.
יש לו קרצולים[fn:2][fn:3]. זה כתוב  בפירוש- "את זה תאכלו... אשר לו כרעים."
1. גמ' מפרש שלא צריך שממש יהיו לו, אלא מספיק אם לאחר זמן יהיו לו[fn:4]. לומדים כן ממש"כ, "אשר לא כרעים [קרצולים]." (כוונת הפסוק הוא להיות נקרא "לו," אבל נכתב "לא," שמשמע שלפעמים מותר אף אם אין לו כרעים.)[fn:5]
כנפים שלו[fn:6] חופים את רובו. לומדים את זה מן הארבע המפורטים.
1. בגמרא יש שני לשונות בביאור זה:
  1. חופים את רוב אורך שלו.
  2. חופים את רוב היקף שלו.[fn:7]
2. לכן, להחמיר, צריך להיות חופה את רוב אורך ורוב היקף שלו.
ראשו לא ארוך.[fn:8] חולקים בזה שני ביאורים של הדרשה. הטוען זה לומד אותו מן הארבע מפורטים, והלא טוען את זה לומד אותו ממילה יתירה של "סלעם." אם לדרוש מן מילה יתירה תלוייה באם כלל ופרט הוא (שלא דורשים) או כלל ופרט וכלל (שדורשים). עיין לקמן, בביאור הדרשות.
שמו חגב. חולקים רבי יוסי ותנא קמא אם צריכים סימן זה או לא צריכים. המקור של רבי יוסי הוא שכתיב "חגב," ודורש מזה שצריך להיות שנקרא חגב.[fn:9][fn:10]
ביאור הדרשות:
הפסוקים:
הפסוק אומר: " אַ֤ךְ אֶת־זֶה֙ תֹּֽאכְל֔וּ מִכֹּל֙ שֶׁ֣רֶץ הָע֔וֹף הַהֹלֵ֖ךְ עַל־אַרְבַּ֑ע אֲשֶׁר־[ל֤וֹ] (לא) כְרָעַ֙יִם֙ מִמַּ֣עַל לְרַגְלָ֔יו לְנַתֵּ֥ר בָּהֵ֖ן עַל־הָאָֽרֶץ: אֶת־אֵ֤לֶּה מֵהֶם֙ תֹּאכֵ֔לוּ אֶת־הָֽאַרְבֶּ֣ה לְמִינ֔וֹ וְאֶת־הַסׇּלְעָ֖ם לְמִינֵ֑הוּ וְאֶת־הַחַרְגֹּ֣ל לְמִינֵ֔הוּ וְאֶת־הֶחָגָ֖ב לְמִינֵֽהוּ:"
רואים מזה שלשה דברים:
1. הכלל:
הפסוק מתחיל בהזכרת כלל, שאומר שתאכל כל שהולך על ארבע ויש לו כרעים.
1. הפרט:
נפרטו ארבע מיני חגבים טהורים. הם:
1. ארבה. גמ' מפרש שזה הנקרא "גובאי."
2. סלעם. גמ' מפרש שזה הנקרא "רשון." יש שקראו לו "ניפול."[fn:11]
3. חרגול. גמ' מפרש שזה הנקרא "ניפול." יש שקראו לו "רשון."
4. חגב. גמ' מפרש שזה הנקרא "גדיאן."
5. למינהו:
הפסוק מוסיף על כל אחד מן החגבים הטהורים מינת "למינהו" או "למינו." נמצא שכתוב ארבע פעמים.
הדרשה:
שיטה ראשונה:
הפסוק מתחיל בכלל, וממשיך לפרט. אז, כלל ופרט הוא, והדין רק נוהג בפרט. אבל, כתיב ריבויים, שאחרי כל אחד מן המינים מרבה את מינו.
"למינו" של ארבה מרבה את ציפורת כרמים, וכל שיש לו ארבע הסימנים וגם אין לו גבחת.[fn:12]
"למינהו" של סלעם מרבה את האושכף, וכל מה שאין לו זנב, אף שיש לו גבחת.[fn:13]
"למינהו" של חרגול מרבה את הכרספת והשחלנית, וכל שאין ראשו ארוך, אף שיש לו גבחת וזנב.
לעיל, בארנו דרשת חגב.[fn:14]
תנא דבי רבי ישמעאל:
הפסוק מתחיל בכלל, וממשיך לפרט, וממשיך לכלל ("למינו" ו"למינהו"ים). אף שלא שווים שני הכללים, -----, דורשים ממנו כלל ופרט וכלל.
1. אם כ' רק ארבה בכופו"כ, רק נרבה את ציפורת כרמים, וכל שיש לו ארבע סימנים וגם אין לו גבחת.
2. אם מוסיף חרגול בכופו"כ, רק נרבה את הכרספת והשחלנית והאושכף, וכל שאין ראשו ארוך. (זה מרבה מה שיש לו גבחת ומה שיש לו זנב, שלחרגול יש גבחת וזנב.)
3. כיון שגם כ' "סלעם" מרבים גם מי שראשו ארוך. אף שאין ראש של סלעם ארוך, מיותר הוא, ואז דורשים זה ממנו.
מן הגמ' יוצא שמה שיכולים לרבות מסלעם, ומה שמכשיר גם אם ראשו ארוך, הוא מפני שדורש מכופו"כ, ולא מריבוי הפסוקים של "למינהו" באמצע פרט וכלל. אין זה כל כך מובן, שכנראה הדרשה אינו מן כופו"כ, אלא מן ייתור הקרא. צריך לומר שכלל ופרט ממעט כל דבר אחר, ורק אם כופו"כ הוא, נוכל לומר ריבוי כזה. אבל, צריך ביאור למה כתיב סלעם לפי שיטה ראשונה.
היה אפשר לחשוב שלא רק נרבה מה שראשו ארוך מ"סלעם," אלא אף מה שאין לו כנפים שחופים את רובו[fn:15], ואז כ' "למינהו" בחגב, לומר שעדיין צריך להיות לו כנפים על רובו.
* Footnotes
[fn:1] לא מפרש משנה אם ארבע הוא גבול למטה, גבול למעלה, או שניהם. באמת, לא ידעתי שיש אינסק"טים שיש להם פחות משש רגלים. ועיין במה שנכתוב, בע"ה, לקמן גבי קרצולים.
[fn:2] יש להסתפק בפירוש מדוייק של קרצולים. קרצולים הם ברכים גדולים, שבהם יכול לקפוץ, אבל לא פשוט לי אם זה השם של הברכים עצמם או של הרגלים שיש להם הברכים. החילוק הוא שלצד שני, יכול להיות שאין רגלים אלו בכלל רגלים, שקרצולים הם רגלים נוספות. אז, צריך שבין הכל יש לו יותר מארבע רגלים. (זה, אולי, מיישב מה שהקשינו לעיל למטה איך יהיה ארבע גבול, שלא מצוי שיהיו לו פחות מארבע רגלים.) מלשון הפסוק נראה שאף הרגלים שיש בהם כרעים נמנים למנין ארבע, שרק צריכים שהולך על ארבע רגלים. ויש לדון.
[fn:3] יש להסתפק אם צריך להיות לו ארבע קרצולים או רק שנים. הספק הוא אם כשאומר "קרצולים" ממשיך ממה שאמר "ארבע" או לא. נראה שלא צריך להיות לו ארבע קרצולים, שאז היה ממשיך מארבע גם בכנפים, ויאמר שצריך שיהיו לו ארבע רגלים, כנפים, וקרצולים.
[fn:4] יש להסתפק אם זה נכון גם גבי שאר דברים שצריכים שיהיו לו.
[fn:5] יש להסתפק בדין של חגב שהיה לו כרעים, אבל עכשיו חסר לו.
[fn:6] יש לדון כמה מן הכנפים שלו צרכים לחפות, ואם מצטרפים בחיפוי זה. בצירוף, יש לדון בצירוף של כנפים של שני צדדי החגב, ויש לדון בצירוף של כנפים של שני מקומות בגב וצד החגב.
[fn:7] אם לומדים אותו מן הארבע המפורטים, קשה למה לא רואים מה יש להם. אפשר לומר שלא נודע לנו איזה ארבע מפורטים (שלא נודע מה הם, באמת). לא נראה כן, שגמ' נותן שמות להם. אולי יש להם שניהם, ולא ידוע איזהו הקרק' החשוב שממעט.
[fn:8] איני יודע ההגדרה של זה.
[fn:9] גמ' לא מבאר איך דורש ת"ק את זה. (אולי ת"ק לא חולק, ורבי יוסי רק מוסיף מה שלא הזכיר ת"ק. אבל, מה שלא מזכיר הת"ק אותו לא משמע כן, אלא משמע שיש בזה מחלקת.
[fn:10] יש להעיר שמסיק גמ' שלפי שיטה ראשונה בביאור הדרשה צריך להיות דומה למה שכתוב בקרא בשני צדדים, ולפי תנא דבי רבי ישמעאל צריך להיות דומה לו בצד אחד. אבל, באמת, צריך להיות דומה לו בשלש לפי ת"ק, ובשנים לפי רבי ישמעאל. ותחשב.
[fn:11] עיין במה שכ' גמ'. מסתבר לי לפרש שגמ' רצה לומר כמו שכתבנו לעיל, שקראו שם רשון לדברים שונים, וקראו שם ניפול לדברים שונים. נראה לבאר ששם ניפול ורשון האו על שם שמפילים את בני אדם מנכסיהם ועושים אותם רשים. אז, הם שמות שמסתבר לנקוט, ואינו פלא ששני מקומות בחרו בשמות זה, אבל רק לא בחרו באותו שם לאותו מין. ותחשב.
[fn:12] מבואר כן מדרשת תנא דבי רבי ישמעאל. אף שתנא זה חולק על תדר"י, מבואר מן הגמ' שבזה לא חולק. ודע שיש לדון אם, באמת, מרבה שום דבר, על ידי זה, יותר מציפורת כרמים. הרי, גמ' מזכיר, באחד מן הריבויים, שני דברים שמרבה, עם קרק' אחד. אז, משמע שמזכיר כל מה שיש לו אותו קרק', וכל מה שנתרבה. אז, אולי משמע שרק ציפורת הכרמים נתרבה. יש לדון, שאולי שם לא כל כך פשוט שיש לשניהם אותו קרק', ולכן צריך להזכיר אותם. ותחשב.
[fn:13] יש לדון אם עכשיו נרבה מה שיש לו זנב ואין לו גבחת.
[fn:14] לא פשוט מה דורש מ"למינהו" של חגב. הרי, לא מרבים עוד דבר, ולא נאמר שצריך אותו כדי לומר שצריך ארבע הסימנים, כיון שלא דורשים מסלעם למעט סימנים כמו שדורש רבי ישמעאל.
[fn:15] בגמ' אומר שנרבה כל דהו, ורשי מפרש שנרבה מה שרק דומה בסימן אחד. לכאו', יש שני דברים שבהם צריך להיות דומים, והם שיש לו ארבע כנפים ושחופים את רובו. הנחנו שהראשון הוא הקיים (ולכן נאמר ראשון, שגמ' ידע שהוא יותר בסיסי), אבל לא מוכרח כן, ואולי זה או זה יהני.
