* ב:
הוקשו כל העריות- נמצא שהוה אמינא של גמרא היה לחייב אחד אם עשה הרבה רק על אחד של עריות,אבל על שאר עבירות (כגון אם עבר באיסור שבת ובאיסור ערוה) היה פשוט לו שיחייב עכ"א. לכאורה, זה מפני שהם עבירות חלוקות, ואין דבר שמייחד אותם אלא מה ששניהם קרו בהעלמה אחת.
* ג.
ארבעים חסר אחת דתניא- היה לו להביא ברייתא זה על קושיא ראשונה, לכאורה. ותו"ת.
* ג:
הא פלוגתא- דכולהו למניינא- ואם תאמר; הרי אינו אומר מנין, שלפעמים יחייב יותר (כמו על שבת). ויש לומר שלא סובר כת’ של גמרא שרק מזכיר שמות או כדומה. גם יש לומר שר"ל שדבר הוזכר רק אם מוסיף לקרבנות (ויכול להוסיף אחד או יותר), אבל כל שלא מוסיף כלום לא הוזכר. ותחשב.
מעשה- קצת מעניין שאין נתינת העצם לתוך פיו נחשב מעשה העבירה. ותחשב.
הואיל- ששמה ידוע- יש לדון אם שם עצם או שם חיה כך.
* ד.
** ראייה -
עיין במה שפירש"י. גם היה יכול לומר שהוא מה שהיו נראים לעדים שמזימים אותם. ובאמת, תלוי קצת למה צריך זה (אם הוא חלק מן העולה או לא. וצריך לחשוב.).
** מגמרא זה משמע
שיש יחס בין דיני חלב ודיני קרבן. וצריך לחשוב.
* ב.
** כל הנך -
עיין במה שאומר רש"י. מזה יוצא שאין כרת בשוגג. לולי רש"י, היה אפשר לומר שיש חיוב כרת בשוגג, אלא שיביא קרבן ויתכפר (או שיעשה תשובה ויתכפר). רש"י לא אומר כן. יש לדון למה נחלק:
1. במזיד, מראה יותר שלא מקפיד לעשות מה שה’ לא רוצה, שבידים עושה נגד מה שרוצה ה’, אבל בשוגג, לא מראה כן כל כך, שרק לא נזהר ואז שגג.
2. אולי הרע שעשה הוא יותר גדול אם עבר במזיד מאם עבר בציור אחר, והוא מפני שהיה בו יותר רצון באותו מעשה (שבשוגג או לא חשב לעשותו, או לא חשב שהוא רע, ונמצא שחשב שהוא מעשה קצת חלוק). ותחשב.
זה תלוי באם עבירה על צווי ה’ (לכאורה, זהו 1, שלכאורה מה שרע לעשות נגד ציווי הוא שבציווי גילה ה’ רצונו למה יעשה, והוא עושה נגדו. ויש לדון בזה, ואין זה בהיר לי) או עשיית רע מחייב כרת. יש להעיר שאפשר שאין כרת כשאר עונשים.
יש להעיר שאפשר שבעצם חייב כרת, אף בשוגג, אלא שממילא עושה תשובה, וכמו שאומר גמרא בסוף מנחות[fn:1]. ויש לדון, שאולי הוא מומר, אלא שלמעשה כאן לא כיוון לאותו מעשה (לא שב מידיעתו). זה קושיא טובה, אבל הוא קושיא על אותו גמרא, והרי למעשה במקומו עומד, ויש לומר כמותו. ותו"ת.
** כל הנך -
דחמורות- יש לדון מה אומר:
1. סדרם כן כיון שבענין אחר הם יותר חשובים (שהם יותר חמורות).
2. סדרם כן כיון שיש יותר סיבה לכרת (שהם יותר חמורים, כמו שרואים ממה שבהתראה חייבים סקילה)
3. סדרם כן כיון שיש יותר כרת באלו, והוא שהם יותר נכרתים מה’ כיון שהוא יותר חמור. ויש לדון, שעדיין עונש של כרת (מה שהוא מת קודם זמנו) אינו יותר עליהם.
4. גם יש לומר שסדרם כן כיון שאז יש יותר סיבה לחטאת (אולי אין יותר סיבה לכרת, אבל יש יותר סיבה לחטאת, ואולי יש יותר סיבה לכרת, אבל אין זה הסיבה שמנה אותם ראשון). זה תלוי במה שנדון אם משנה בא לדין כרת או לדין חטאת. גם תלוי באם יוכל חטאת להיות תלוי בדבר חוץ מכרת (וזה תלוי במה שנדון מהו היחס בין כרת לחיוב חטאת)[fn:2]. ותחשב.
באמת, שני ושלישי שווים, אלא שלשני "כרת" אומר עונש שלו, ולשלישי (אף) אומר מה שנכרת מה’. יש לדון- ואולי מה שיהיה במשמעות מילת ועונש "כרת" תלוי בזה- אם הם שני עונשים[fn:3] שבאים שני סיבות במעשה אחד, מסיבה אחת, או שכריתתו מה’ גורם עונש השני.
גם יש להעיר על לשון "חייב כרת.” אם דנים במה שימות לפני זמנו, זה טוב. אם דנים במה שנעשה נכרת מה’, לכאורה היה לו לומר, “נכרת,” שקורה מיד ממילא. ויש לדון, שאולי אין ה’ כורתו ממילא[fn:4]. גם יש לדון, שאולי אומר לשון זה מפני חיוב השני שבו (שמת קודם זמנו).
** שלשים ושש כריתות -
זה בקדשים כיון שימשיך לומר שעל חיוב כריתות יש קרבן מיוחד, והוא קרבן חטאת…. באמת, יש לדון מהו עיקר המשנה, ומה בא להשמיענו. אפשר שבא להשמיענו כולו, אפשר שבא להשמיענו דין כרת, ואגבו בא דין חטאת, ואפשר שבא להשמיענו דין חטאת, וזה היה הקדמה לו.
** יש לדון
אם חיוב חטאת הוא מפני הכרת (רצה לומר, כיון שנכרת מה’, צריך קרבן לרצות לה’) או מפני דבר אחר הבא עם הכרת (וחיוב כרת הוא רק סימן (או אולי סיבה) לאותו דבר אחר). ותחשב.
זה יהיה נוגע לציורים שיש בהם כרת אבל אין בהם קרבן. אם כרת אינו מה שמחייב הקרבן, קל לבאר אותם ציורים. אם כרת הוא מה שמחייב קרבן, קשה למה לא יחייבו בקרבן שם. ואולי אינו כל כך חייב בכרת, ואינו נכרת כל כך. ותחשב. גם יש לומר (בדוחק) שחיוב כרת שם חלוק לגמרי, ויש סיבה רוחני חלוקה למה מת קודם זמנו. אם כן, נמצא שעל זה, ולא על כריתתו מה’ אומרים שהוא חיוב כרת, שאין כולם חיוב כרת על פי כריתתו מה’. ותו"ת. (וגם אפשר שחיוב חטאת בא מדבר שיש בכל לאו שיש בו מעשה בצירוף חיוב כרת. אז, אף שיש לאלו חיוב כרת, לא יחייבו בחטאת).
** כל הנך -
ובשוגג בחטאת- מעניין, שלולי רש"י, הייתי אומר שאין זה כנגד חיוב כרת, שאינו עונש, אלא שכיון שעשה רע, מביא קרבן לכפר על אותו רע. צריך לבאר קצת מהו עונש, שאף עונש מכפר על רע. נראה לומר שעונש נותן לו צער; מה שמכפר על העבירה הוא שיש לו צער[fn:5]. חטאת אינו כן; מכפר על עבירה מחמת הרצאה וכוח רוחני שבו. ותחשב.
לכאורה, אין לומר שצריך להביא קרבן כדי לצער אותו (שמפסיד בהמה), שאם כן, קשה למה יש חילוקים בדיני הקרבת דם חטאת והקרבת כל נדבה, שיחייב להקריב נדבה. ותחשב. ואולי כיון שחייב קרבן, מחייבים[fn:6] אותו שגם יכפר עליו. ותחשב.[fn:7]
גם יש לומר שרש"י ר"ל שלא חייב כרת, ומנה מה שחייב, שאמר שאז חייב רק חטאת (שלא רצה לומר "פטור" כיון שיש לו חיוב). ויש לדון למה לא אמר "פטור מכרת.” ואולי השמיע עוד דין- חיוב כרת- אגבו. ויש לדון בזה.
** הבא -
יש לדון מתי מחלקים במילה זה (רצה לומר, מתי אומרים, “הבא… הבא…,” ומתי רק אומרים "הבא… ועל…"). לכאורה, יהיה תלוי כמה מיוחסים שני הציורים, שאם הם בכלל אחד, ימנה אותם ב"הבא" אחד. וצריך לחשב על אחד.
** הבא על האם -
מעניין- והערנו על כגון זה במק"א- שלא נחשב זה לשנים- הבא על האם והנבעל מבנה, אף שהוא מעשה חלוק עם איש חלוק. ואולי אומר שיש שלשים ושש ציורים שבו יש מי שחייב כרת. מוזר למה יאמר כן. אלא נראה שהרע שעושים הוא שווה. זה מעניין, שאף אם נאמר שרע אחד יוצא מאותו ביאה, ומיוחס לשניהם, היה נראה לומר שמיוחס לשניהם באופן חלוק, שהרי עשו מעשים חלוקים לעשות אותו. ויש לדון.
** הביא בהמה -
לכאורה, יש לחקור למה זה חלוק מבא על בהמה:
1. עשה מעשה חלוק.
2. יש רע חלוק.
לכאורה, צריך לומר כצד 2, שלעיל בד"ה הבא על האם הוכחנו שאף במעשים חלוקים נקראים חד כרת. ותחשב.
על האם- יש לדון למה לא אמר, “הבא על אמו.”
אשה ובתה- מבואר ברש"י שיש יותר ממעשה אחד הכלול בזה, שבו נכלל בא על אשה ובתה עם בא על אשה ובת בתה עם בא על אשה ובת בנה. יש לדון מה עושה כולם לאחד, ומה עושה שאר עריות לאחר:
1. אפשר שהוא אותו סיבה רעה (או שהוא שווה) בכל שהם בכלל אחד.
2. אפשר שיש מינים חלוקים של כרת, דהיינו שנכרת באופן חלוק מה’. אולי באלו שהם בכלל אחד, יש מין אחד של כרת.
3. אפשר שאין חילוק בין שהוא רק מפני שום דמיונים אחרים (למשל, בת ובת בת יש להם יחס דומה), ולא שאז עושים סיבה היותר דומה.
4. יש לדון בזה, שיש דבר יסודי בזה, שהרי בזה מחלקים דיני חטאות (שמביא חטאת אחת על כל אחד הנמנה במשנה). ותחשב. ויש לדחות שאינו מיוסד בדבר יסודי, אלא שכיון שנחשב כאחד[fn:8], חייב רק אחד.
ופסח ומילה מצוות עשה (רש"י)- יש לדון למה רש"י מבאר את אלו קודם עריות, שהיו עריות מפורשים במשנה. ממה שרש"י מתחיל לבאר לאו רק בעריות, ולא מבאר כרת שלהם קצת משמע שרש"י רק מבאר כרת כשנצרך, ולא היה נצרך בעריות. בא לבאר עריות כדי לבאר לאו שלהם (כדי שלא יהיה כפסח ומילה), ואגב זה, באר מקור בהם לכרת.
יש להעיר שאילו לא היה לאו גבי עריות, לא היה עשה כמו פסח ומילה, אלא לא היה ציווי כלל. אז, לא היה נכרת, שלא עונשים אלא אם כן מזהירים. אולי משמע שיש כרת בלי אזהרה, שאין כרת עונש רגיל, אולי. ותו"ת. אז, רק דן אם יחייב חטאת כיון שאינו דומה לשאר חייבי כרת.
ויש לדון בכל זה, שממשיך לדון בעוד מאלו שבהם יש מקור פשוט ללאו שלהם, כמו עבודה זרה. וצריך ביאור. ואולי צריך לומר שלרש"י היה סדר חלוק במשנה.
** והעובד (רש"י)- דבר ה’- לכאורה, אז, יכלל גם דיבור ראשון. נמצא שאם אדם כופר בה’, אבל לא עובד אלהים אחר, יחייב כרת. אם כן:
1. יש כרת אחר שלא נמנה במשנה.
2. יש עשה אחר שיש בו כרת.
** וצריך ביאור. ועיין בסנהדרין ששם דן בביאור על מי נאמר, “כי דבר ה’ בזה,” ואומר רבי ישמעל ש"זה העובד עובדה זרה.” מבאר תנא דבי רבי ישמעאל: “’דבר ה’ בזה’ זה המבזה דיבור שנאמר לו למשה[fn:9] מסיני ‘אנכי… לא יהיה לך….’" אם כן, לכאורה, גם אותו תנא אומר כמו שאומר רש"י כאן (אם לא שדוחה שגם העובר על העשה של אמונה בכלל זה, ורק מנה אחד שהוא באותו כלל. ודחוק.) גם יש להעיר שאומר שהוא מי שהוא בכלל אותו "דיבור,” ולא אותו דיבורים. ק"ק, שלכאורה, הוא שני דיבורים חלוקים. וצריך ביאור. ואולי יש לחדש שיש דיבור אחד שכולל שני הדיבורים, והוא שאומר ה’ שכיון שהוא הה’, לא יעבדו אלהים אחרים, שאינם אמת. מזה, יש דיבור בפירוש שלא לעבוד אלהים אחרים, ונלמד עשה להאמין בה’, אולי, ביותר דיוק. יש לדון איך לומדים, אז, אותו ציווי. באמת, בדרך כלל, קצת צריך ביאור איך לומדים אותו כלל, שהרי אין התורה אומר ציווי, אלא אומר שה’ הוא האלהים, וזהו. צריך לומר שפשוט שנובע מזה שיש לנו להכירו, שכך עושים למלך. צריך לומר שאף דיוק כזה נחשב חלק מן הדין. אז, יש לומר שכיון שהוא רק דיוק, אינו כל כך נחשב חלק מן הדיבור. אולי כיון שדבר ה’ בזה משמע דיבור אחד (ויש לדון בזה, אלא שנראה שדבר משמע דיבור, ואם היה רוצה לומר דיבורים, היה אומר דברים), מניחים שהוא איסור של עבודה זרה, שהוא האיסור היוצא בפירוש מאותו דיבור. גם יש לומר שאין כולו דיבור אחד, ונקרא דיבור אחד כיון שרק קאי על דיבור אחד של ה’. מסתבר שקאי על עבודה זרה כיון שהוא לאו. גם יש לומר שכיון שדיבור ראשון שאומר מלמד דינו רק בדיוק, אותו דין אינו נחשב כל כך הדיבור. אז, אי אפשר שקרא נאמר עליו, ומוכרח להיות שהדיבור שבו מיירי הוא הדיבור של עבודה זרה. ותחשב. ולכל הצדדים חוץ מן הראשון, יש לדון למה הביא כל הקרא, שהיה לו להביא רק "לא יהיה לך,” שזהו הדיבור. ותחשב. יש להעיר שמביאים קרבן חטאת על עבודה זרה. חולקים רבנן ורבי אם מקור יסודי לזה הוא מהיקש לעבודה זרה או מ"עליה" שנאמר גבי אשת אח. אם נאמר כרבנן, יהיה נמצא שאין שאילו לא היה כתיב, “כי דבר ה’ בזה,” היה כל לאו (או אולי אף כל איסור) מביא קרבן חטאת. אין זה בעיה. אבל לרבי, לכאורה, היינו יודעים שצריך להביא רק על מה שחייב כרת. אם כן, נדע שעל ע"ז חייב כרת. יש לדון:
1. אולי לא היינו לומדים ממנו כיון שאין ע"ז שחייב בו כרת.
2. אולי זה היה מלמד שחייב כרת, כמש"כ, אבל רק בציור אחד, שאחר שלמדנו לציור אחד, אין עוד הכרח. יש לדון איזה ציור יהיה, אבל אולי קרא של "דבר ה’ בזה" מוסיף על זה. יש להעיר שאז לא היה רש"י צריך להביא אותו קרא של "דבר ה’ בזה" במשנה, שבין כך ובין כך, היה שום ציור עם אותו דין ובו היה משנה מדבר, אלא שרש"י מפרש כקושטא דמילתא.
** ובעל אוב (רש"י)- אל תפנו- לכאורה, האיסור הוא מי שעושה כישוף זה. נקרא פונה אל האובות אף שהוא אינו השואל מפני שהוא שואל לאוב כדי להגיד את התשובה. אם כן, לכאורה, השואל את בעל אוב הוא רק מסייע ידי עוברי עבירה (שלא היה שואל אם לא שזה רצה שישאל). ותו"ת. מפטם את הקטרת (רש"י) -
אבל המריח- מעילה- מעניין, שלכאורה, יש איסור לסוך שמן חוץ מאיסור סיכה (שהרי, מביא לאו אחר).
מפטם (רש"י)- מעשה- יש לדון מהו החילוק בין מריח וסך:
1. אולי ריח טוב אינו הנאה חשובה; רק סיכה הוא הנאה חשובה. זה מחודש, שהרי מברכים על הנאת הרחה.[fn:10]
2. אולי מעילה הוא כשמשנה חפץ של הקדש (באמת, כן הוא משמעות "מעילה"), ונהנה מאותו שינוי. כשאדם מריח בדבר, לא משנה אותו.
3. אולי כשאדם מריח, לא בא ההנאה מן החפץ, אלא מדבר קטן שנותן באויר, שהוא ריח. כשסך, נהנה מן השמן עצמו. לכאורה, עדיין צריך ביאור למה אין אותם חתיכות קטנות של ריח שנותן באוויר לא מקודשות. ויש לומר שאינם גדולים די להיות חשוב לתפוס קדושה. ותחשב. גם יש לומר שבטל הוא לאויר. אי אפשר לנהוג קדושה עם חלק מן האויר (לא ניתנה תורה למלאכי השרת), שאם הוא מנשים אותו, ימעול, וזה אי אפשר להקפיד עליו.
רש"י לא משמע כן, אלא משמע שהוא מפני שלא עושה מעשה כשהוא מריח. לכאורה, זה מפני שרק מנשים, והיה מוכחר להנשים. ותחשב.
מפטם (רש"י)-  אין בו משום מעילה- קשה, שגמרא בפסחים מסיק שיש בעילה במפטם את השמן. ותחשב.
אין לתרץ לשני קושיות שהקשינו (זה ובד"ה מפטם את הקטרת) שרש"י באמת לא דן במעילה, ואומר לשון זה לאו דווקא, שלא מסתבר לומר שהסיבה שאין איסור חדש במריח הוא שאין בריח כלום, שהרי גמרא אומר שיש בריח כלום, ועוד שיש סיבה אחרת, והוא שלא אמר בו תורה איסור. מוזר שרש"י יחשוב שצריך לבאר למה תורה יאסור זה ולא זה; הלא דברים חלוקים הם. ותחשב.
פסח- כרת הוא שמת בלי בנים- עיין במועד קטן (כח.) שמבואר שגם מת קודם זמנו. ק"ק למה לא הזכיר רש"י את זה כאן. נראה שני מהלכים:
1. אולי יש עונשים, ויש תוצאות שהם ממילא. אולי רש"י רק מונה עונש (שהרי, אומר רש"י קונטרס"ט עם שאר עונשים[fn:11]).
2. החילוק בין עונש לדבר שבא ממילא הוא שעונש בא כדי ליתן לו צער. דבר שבא ממילא לא בא לצורך, אלא בא.
3. יש להעיר שגמרא (כריתות כג:) אומר שכרת יותר חמור ממיתה בידי שמים. לכאורה, יש שלש סיבות לזה:
  1. כרת ממית בחמישים; מיתה ממית בששים.
  2. כרת אף עושה שמת בלי בנים.
  3. איסור כרת אף מחייב חטאת. ויש לדון, שהיה אפשר לדחות שחטאת לא מהני על חיוב מיתה (גם יש לומר כן בשאר הצדדים, אלא ששם יש סיבה, לכאורה, חוץ מכפרה, והוא שטוב שמי שחטא ייענש, אבל כאן, בקרבן, לכאורה, הוא כדי שיכפר ה’. ויש להעיר שאולי ה’ לא רוצה בכפרה לטובתו[fn:12] אלא לטובה בדרך כלל (אז, אין כל כך עבירות). ויש לדון אם כפרה מוחק את העבירה או עושה שאין זה מיוחס לו.
4. ונראה שאולי רש"י הוא קצת לשיטתו בשלש רשיי"ם, שרש"י משמע לעיל שחטאת הוא עונש (עיין ברש"י ראשון,שמנה אותו עם עונשים), וסבר שאין מיתה קודם זמנו עונש, ואז מבאר למה נקט עונש לגלות על עונש, ולא זמן מיתה, שאינו עונש. עדיין לא מבואר למה לא נקט שמת בלי בנים, שהוא פרט אחר בעונש (לא היה לו לומר שעונש נתקיים בשוגג, אלא שהוא עונש יותר גדול. ואולי כיון שזה דן בכמה רע הוא לו הוא יותר דומה למיתה קודם זמנו, ולא קל לדעת איזה יותר רע לאדם, ואיזה עונש יותר גדול. אבל, מה שעבירה טעון עונש אף בשוגג מראה שלענין עונשים, הוא עבירה יותר גדולה, ואז מסתבר שעונש מזיד שלו יותר רע. ותחשב.
5. אולי רש"י אומר שבין כך ובין כך (בין אם התרה בין אם לא התרה) מת קודם זמנו, שהרי בית דין ממיתים אותו. ועדיין יש לדון, שאם הוא קרוב לחמישים, וחייב כרת ומיתה, אפשר שבית דין לא ימצאו פנאי לדון בו עד שמגיע לגיל חמישים.
על שגגתו- יש להעיר שאין זה המקור שחייב על שגגתם חטאת, אלא הוא המקור שרק על שגגתם חייב חטאת, ולא על שגגת חטא אחר. אם כן, אין צורך להזכירו כאן. ותחשב.
ועל לא הודע- ואשה שהביאה בהמה נמי- צריך ביאור למה מפסיק בביאור אשם תלוי קודם שמבאר את אלו.
ועל לא הודע- ע"ז- ק"ק, שכיון שמפרש שיכול להיות אומר מותר, קל להבין שיש לפרש שאר כך. אם כן, אינו צריך לפרש. ותח’.
ועל לא הודע- נתכוון להוציא- מעניין שזה נחשב שוגג, שבדרך כלל, אדם שולט על מה אומר. צריך לומר שיכול להיות שחושב, “שם ה’,” ובא לו שם אחר לפיו, ונחשב שוגג. הוא קצת מוזר. גם לא מסתבר לומר שטעה איזה הוא השם של ד’ אותיות, שלכאורה, יש סימן מובהק להכיר בחילוק בין שם של ד’ אותיות ושל ב’ אותיות, והוא כך: שם של ד"א יש לו ד"א ושם של ב"א יש לו ב"א.
ועל לא הודע- בבמת יחיד- לכאורה, גם יש לומר להיפך, והוא שחושב שקרא הוא רק בשל ציבור. לכאורה, רש"י סוברש הוא קל וחומר, שאם נאסרו במות יחידים שאינם כל כך קדושים (שהרי אין מביאים כל כך קרבנות עליהם, כדאיתא בפרק אחרון של זבחים).
ועל לא הודע- מעלה- לכאורה, יש לומר כן אף בשוחט, אלא שהוא טעות שרב בני אדם לא יטעו.
ועל לא הודע- אנוס- צריך לחשוב למה נחשב יותר אנוס. אולי הוא רק סימן, שבדרך כלל, מי שיודע קצת בענין האיסור, לא קל לו
לדעת יותר, אבל מי שלא יודע כלום אולי הוא יותר קשה לו לדעת יותר. אז, הוא נחשב אונס. ותחשב.
** ב:
שאם עשאם- יש לדון מהו התירוץ:
1. אולי מגלה אותו הדין. לכאורה, מגלה אותו הדין מפני שאומר שלפעמים טוב הוא לדעת כמה יש (שאז אין צריכים למנות). צריך לומר שזה אם עשה כולם. לא נראה שאפשר לומר כן, שהרי רק חייב שלשים וארבע, שהרי על שנים לא חייב. ויש לדון, שמשנה אומר כן, ואז רק צריכים למנות כמה ממעט משנה ולנכות מנין זה- וזה יותר קל מלמנות כל מה שמונה משנה.
2. אולי אומר"י שמפני אותו הדין, צריך לומר המנין, מפני שלפעמים יהיה שייך לדעת, ויהיה קשה למנות.
3. עיין לקמן, שגמרא יקשה מי יכול לחייב על כל ציור שבמשנה. לכאורה, זה לא קשה לצד זה, שלצד זה יש לומר שרק אומר שכל אחד חלוק, ויהיה נפק"מ בזה לזה ובזה לזה. קושיית גמרא צריך להניח דלא כצד זה. ותו"ת.
המעלה לומר פשט ראשון הוא שלכאורה, אינו מצוי שיהיה נוגע. אז, לא היה תנא חש לאותו מקרה. אז, צריך לומר כראשון, ורק אמרו כיון שהוא theoretically אפשר להיות נצרך. ותחשב.
עיין בשבת (ו:) שיש לשון כזה. מרש"י משמע כצד שני (אלא אם כן נאמר שמבאר המשמעות שמוכיח כן). מקושיית ת"י משמע כצד ראשון. ויש לדון שרק מקשה למה גמ’ מקשה מר"י, ולא ממשנה. אולי כן משמע ממש"א "מה משמיענו ר"י,” ולא "מה משמיענו אותו משנה.” אם כן, אומר כשני.
עיין ברש"י שם (עג:) שלכאורה משמע כצד ראשון. ויש לדחוקת.
מניינא- נראה שבא להוציא מצד זה: אפשר לומר ש"מניינא למה לי" מקשה למה ימנה את כל הציורים כיון שרובם נמנו במקומות אחרים. ויש לדון. משיב כמו שהיה משיב לשאלת רש"י, והוא שמרוויחים במה שאז אם נרצה לדעת מניינם, רק צריך לראות כאן. (עדיין יש לדון למה לא רק אמר מנין, ולמה מנה את כולם.)[fn:13] יש לדון מהיכי תיתי לרש"י שלא לפרש כך:
1. אולי רק לא נראה כן מסברה. לכאורה, מצוי הוא שמשנה ימנה כמה וכמה ציורים הידועים. ויש לדון.
2. אולי ממה שמקשה גמרא כמו כן אף בציורים שצריך מה שמנה (חושב אני שיש מקומות; ויש לדון.), רואים שאין זה הקושיה. ויש לדון, שאולי שניהם קושיות, ושם הקשה מה ששייך, וכאן יותר היה קשה, והקשה אותו. ואולי לא מסתבר לומר שישתמש באותו לשון להקשות קושיות חלוקות. גם אולי לא מסתבר כן ממה שגמרא ממשיך לדון בציורים שלכאורה מקשה רק מהזכרת מנין, ולא ממה שמונה דברים.
על כל אחת- יש לדון מה היה ההוה אמינא:
1. חייב אחת על הכל.
2. חייב אחת על כל מין (אחת על עריות…).
על כל אחת ואחת- יש לדון מה יהיה הסיבה שלא יחייב על כל אחת:
1. אולי ס"ר של חיוב כרת אחד דומה לס"ר של חבירו עד שלא מוסיף רע. ויש לדון, שאם כן נצטרך לומר שבשני העלמות, שחייב שני קרבנות, הוא חלוק. ותחשב.
2. אולי הוא מפני שמביא קרבן על מה ששגג (לא מפני ס"ר, אלא שעשה נגד ציווי ה’ כששגג מלשמור את עצמו מעבירה). עשה כן רק פעם אחת. למסקנא, יש לדון אם לא מביאים קרבן על זה או שאם מחמתו עשה כמה עבירות, מביא יותר קרבנות, שהוא יותר רע.
3. אולי הוא מפני שקרבן אחד יכול לרצות לכמה עבירות. נראה שיש לדון אם עושה סיבה לכפר עבירה או לכפר לאדם. ותחשב מה זה אומר. אולי זה תלוי בדיון זה. ויש לדון.[fn:14]
מחוסרי כפרה- יש לדון מה עושה אותו מחוסר כפרה:
1. גירות.
2. היותו נכרי.
[fn:15]לאפוקי מדר"ש- קשה למה צריך מנין שם למעט, שהרי כיון שמונה לחיוב מה שר"ש פוטר, אי אפשר ליישב שהוא כרבי שמעון (שאין "תנא ושייר" לומר כאן)[fn:16]. אולי רק אומר שאמר מנין כדי שתזכור יותר שאינו אומר כר"ש. אז, כשאומר רש"י לעיל שכיון שתני מנין, אין אומרים תנא ושייר, לא אומר שרק תנא מנין כדי שלא נאמר תנא ושייר, שאף אם היינו כבר לא אומרים תנא ושייר, היה אומר מנין. אולי אומר עוד דבר שבא ממנו, ואולי אומר שלא היינו יכולים שמנין בא כדי שיהיה יותר קל לזכור שאין המשנה כרבי אליעזר אם לא שאין המשנה כרבי אליעזר. אז, צריך לומר שאין אומרים תנא ושייר. ויש לדון, עדיין, למה צריך לומר רש"י שאז אין אומרים תנא ושייר, שפשוט שאז אין לומר תנא ושייר (וכיון שזה רק מסלק מניעה, לא היה לו לאומרו). ותחשב.
** - קשה למה לא אומר לשון שווה למה שאמר גבי ר"ש (שלכאורה, התירוץ שווה, והוא שרוצה למעט מי שחולק על אחד מן הציורים). ותחשב. ואולי אם לא היה עושה כן, היה קצת monotonous. ותו"ת.
משום דקא בעי
** חדא טומאה אריכתא- לולי זה, היה אפשר לומר שאינו חד טומאה ארוכה, אלא שמה שנטמא שלא בימי נזירות (רצה לומר, בימי טומאתו) אינו מחייב אותו קרבן. ותחשב. - יש לדון למה, אז, יחייב עוד קרבן:
בשעה הראוייה
1. אולי כבר חייב בקרבן אחד. קשה למה זה עושה שאותו קרבן לא מועיל לטומאה שני. נראה שאולי צריך שהקרבן ייחס באותו כוח לטומאה ראשון ושניה. אם כבר חייב קרבן על ראשון, יותר מיוחס לראשון, שהרי היה עומד לו ליותר זמן. לא נראה כן, שהרי לא היה קרבן אז, ולא היה עומד לשום דבר. ותחשב. ויש לדון.
2. אולי שני הטומאות חלוקות, שהם בצדדים חלוקים של חלות חיוב. יש לדון אם זה יחלק אותם.
** אחותו דפרט- צריך ביאור מה אומר רש"י כאן, שלא מפרש חיוב כרת בשום קרא אחר. אולי מצרף מה שמחייב "ערירי.” קשה, עדיין מהו תירוצו. משמע שמדייק ממה שיצאו כלל להימנות, ולא רק אמר שעל כל עריות האסורים יש חיוב. קשה, שאין זה יציאה של אחותו. ואולי אין הכי נמי, ורש"י רק מקשה למה אינו יציאה די, שהרי אומר שהם חלוקים, ואין נפק"מ לזה חוץ מלחטאת. ויל"ד, שיש נפק"מ גם כן למלקות (אם חייב על לאו שניתן לאזהרת מיתת בית דין). ותחשב. יש לדון  אם מביאים קרבן חטאת מחמת העבירה, סיבת העבירה, או חיוב הכרת. יש להעיר שאולי סיבת העבירה הוא חיוב כרת (שעבירה גורם לאדם להיות נכרת מה’, וזה רע). אחד- יש לדון למה נניח כן:
1. אולי הוא שכיון שכרת כתיב בחד קרא, מניחים שכולו כרת שווה. אם הוא כרת שווה, רק יביא קרבן אחד עליו.
2. אולי הוא שכיון שכרת כתיב בחד קרא, צריך לומר שיש דבר שמייחד אותם. אולי זה הוא מה שעל כולם מביא קרבן אחד. זה יכול להיות אם מניחים שהוא כרת אחד (ועדיין לא פשוט שיכול להקריב קרבן אחד, שאולי כיון שיש כמה סיבות לאותו חיוב כרת, לא יועיל קרבן אחת), או שהם כריתות חלוקות (ולא אומרים שקרא מגלה שהוא כרת אחד, שכיון שהמעשים והלאווים חלוקים, לא נראה כן).
** אחותו- יש לדון מהו הדרשה שדורשים מזה:
1. לצד ראשון שכתבנו לעיל, יהיה שאומר כרת בזה. אז, צריך לומר שהוא כרת חלוק. אז, יחייב קרבן עליו.
2. לצד שני שכתבנו, יהיה שזה נחלק לומר שבדין נחלק, והוא שעל זה מביא קרבן אחר.
** יצא מן הכלל- לכאורה, לצד שני, הקרא אומר שיש לו חיוב כרת. לא אומר בפירוש שיש לו חיוב כרת מיוחד, אלא ממה שאמר אותו חלוק מחיוב כרת הכללי, רואים שאין לו חיוב כרת הכללי. אם כן, יש להעיר שני הערות:
1. אולי כיון שלא אומר תורה בפירוש שכרת שלו חלוק, לא נוכל לומר שדבר שיצא מן הכלל ללמד…, שלא יצא מן הכלל ללמד כרת חלוק, אלא חיוב כרת. צריך לומר שכיון שלמעשה פשוט מן הקרא שהוא כרת חלוק, מניחים שאף זה מלמד.
2. היה אפשר לומר שלומדים שכל אחד חייב אותו כרת (עם אותם קרק’ שעושה אותו חלוק ממה שחשבנו להיות כרת). אם כן, עדיין יהיו חייבים אחד על הכל. ויש לדון, שאז אין נפק"מ, ואולי לא מסתבר שקרא יגלה לנו איזה מין כרת הוא.
** - יש לדון איך דורשים זה:
יצא מן הכלל
1. אולי הוא רק כלל שחידש לנו תורה. זה אומר שאין סיבה לדרוש חוץ ממה שאמר תורה לדרוש כן, ולא יודעים למה.
2. אולי הוא מפני שאז מה שכלל את כל הכלל כולו בלשון אחד צריך להיות לאו דווקא. לצד ראשון, צריך לומר שלא אומר שעל כולם חייב אחת, שעל אחד מהם יחייב בפני עצמו. לצד שני, צריך לומר שאין כרת שלהם אחד[fn:17], ואז לא רואים שהוא שנים, ולא שיש לכל אחד כרת בפנ"ע (ואז מניחים כן).
3. יש לדון אם יש לומר כעין זה בכל "יצא מן הכלל.”
4. יש להעיר שלפי זה, יכולים לתרץ מה שהערנו בדיבור הקודם, שאף שלא ישוו דינם, רואים שאין הכלל דווקא. ותו"ת.
5. לא נראה כצד זה, שאם כן, מהו תירוץ גמרא (שאומר שרק דורשים דברים שהם ביותר דומה לו), שהרי כיון שידוע שאין הכלל דוקא, יהיה כל דבר חייב כרת אחד. ותחשב.
** בכלל- יוכשר ליקרב- יש לדון אם זה סימן או סיבה. אולי הוא סימן, והוא שדבר שראוי ליקרב ראוי לכך כיון שיש בו קדושה גדולה. אז, אכילתו יותר רע. אולי הוא סיבה, והוא שמה שראוי הוא לקרבן עושה לו יותר קדושה. גם יש לומר שהוא סיבה, והוא שחלק מן הרע הוא שמבטל אותו מלהיות נקרב. אם מטמא דבר שאינו ראוי להיקרב, לא מבטל אותו מדמיו. יש לדון באיסור של טומאת דבר קדוש:
1. אולי רע כיון שעושה שדבר קדוש טמא.
2. אולי רע כיון שעושה שדבר טמא קצת קדוש.
3. אולי רע כיון שעושה שדבר קדוש אינו כל כך קדוש.
בכל אלו מובן למה יש יותר איסור אם הוא יותר קדוש.
יצאו קדשי בדק הבית- קשה למה צריך זה, שהרי קרא אומר, “יקרב,” שאומר שצריך להיות שראוי להיות נקרב. אין קדשי בדק הבית נקרב. אולי הוה אמינא שלא לדרוש "נקרב.” גם י"ל שהוה אמינא ש"נקרב" רק אומר שעושים בו קדושה שלו עומד (לאפוקי קרבן פסול, שאין עושים בו קדושה, אלא שורפים אותו, או כדומה).
** קדשי בדק הבית- יש לדון אם זה דווקא או אם רק רצה לומר קדשי קדושת הגוף, ולא רק קדושת דמים. יתר
ה
בחיי אוסרה- יש לדון למה לא אומרים שאחותו חלוק כיון שהוא קורבה שאינו צריך קידושין (הוא קורבת דם). גם יש לדון למה לא אומרים שאחותו חלוק כיון שאין לה היתר עולמית.
** -קשה למה לא ממעט מכאן נדה גם כן (ואם, באמת, ממעט אותה, קשה למה לא נמנה). ותו"ת.
היתר
** ונראה לתרץ כל אלו שכיון שכבר מיעט דבא אחד, יש פתח לר"ב להקשות. אז, אומר שאף אם תאמר שמזה לומדים דבר שהוא רחב ביותר, עדיין יהיה קושיה (וכיון שיש קושיה אחת, יש לר"ב להקשות, ואין צורך להזכיר שיש שני קושיות). ותחשב. ערוה ואין לה -
מ"ואין לה…" ממעטים אשת איש. צריך ביאור מה ממעטים מ"ערוה.”
חייב עליה- יש לדון מהו הקמ"ל:
1. אם ההוה אמינא הוא שחייב אחת, אף שיש כמה כריתות חלוקות, אז פשוט שההוה אמינא הוא שאינו חייב אחת, אלא יותר מאחת.
2. אם ההוה אמינא הוא שכולו כרת אחת, ואז רק מביא אחת, יש לדון מהו הקמ"ל:
  1. אולי מחדש שכריתות חלוקות הם.
  2. אולי מחדש שאף שהם כרת אחד, חייב על כל אחד ואחד.
ואל אשה- אם כן, לכאורה, יחייב אחד על כל גוף, אף בשמות חלוקים. חושב אני שאין זה הדין. אולי יש לומר בדוחק ש"אשה" רצה לומר ערווה שנזכר בקרא, ומשמע כן כיון שכל ערווה שנזכר היה ציור של אשה. אז, אומר שעל כל ציור של אשה שהזכיר, חייב אחת. ודחוק. ותחשב. שוב הבנתי שאולי דין שמות חלוקות נלמד רק מקרא של אחותו לקמן. לשון גמרא לא משמע כן כל כך, שאומר שמחלק ב"אחותו שהיא אחות אביו שביא אחות אמו.”[fn:18] משמע שרק צריך באותו ציורים. ויש לדון למה נאמר שבשאר עריות חייבים בשמות חלוקים קרבנות חלוקות, ובאלו לא נאמר כן. אולי הם יותר דומים, כיון שיש אחווה[fn:19][fn:20]. ויש לדון. גם יש לדון למה לא ילמדו מן השאר מהיקש של ר"י. ויש לדון, שאולי יכולים ללמוד רק מי שיש לו שם חלוק מאד משם, כמו המלמד. ותו"ת.[fn:21]
עוד קשה איך יודעים שחייב אחת לבא על זכר, ולבא על בהמה, שאינם נשים. ואולי לומדים מן השאר, מהיקש דר’ יונה[fn:22] (וגמרא לא באר כן כיון שכבר באר אותו לימוד). גם יש לומר שלומדים היסוד- שגוף מחלק, ולא מסתבר לחלק בזה בין עריות חלוקות. ויש לדון.
אולי יש לומר דרך אחר בכל דרשה זה שיתרץ כל הקושיות. אולי בא לומר שאם בא על כמה נשים שהם נדות, חייב על כל אשה. כיון שיודעים דין נשים חלוקות, מניחים שזה דין של שמות חלוקות. יש לדון אם יכולים ללמוד זה מזה[fn:23]. אף אם אפשר ללמוד, לשון גמרא חסר, שהיה לו לפרש זה. ותחשב.
** ג.
ואי בעית אימא- עיין במה שבאר רש"י. לולי רש"י, היה אפשר לומר שר"ל שלמד אותו כלל מלימוד ממה שאין מזהירים מן הדין. ואם תאמר איך ידע עונש זה. ויש לומר כמה שאומר רש"י. גם יש לומר שביבמות מבואר שני קראי- אחד ללמד דין זה, ואחד ללמד שאין עונשים מן הדין. באמת, כיון שהגענו לזה, קשה על מה שאומר רש"י שדן גמרא למצוא מקור לחיובו. ותו"ת. וצריך לעיין באותו גמרא.
נראה לחקור למה אין עונשים מן הדין:
1. לא נדע בוודאי שראוי הוא ליענש, שלא נדע אם הקל וחומר נכון. חושב אני שכן אומרים מפרשים, אבל לא הבנתי, שסומכים על קל וחומר לדחות שבת וכדומה.
2. אולי צריך שקרא יגלה אותו באופן חזק. זה דומה למש"א תוס’ בקידושין (טו:) שדבר שאומר תורה בפירוש יש לו אותו דין באופן יותר חזק.[fn:24] מה שלא גילה את העונש בלשון חשוב אומר לנו שלא כיוון לגלות עונש. כמו כן, יש לומר שמה  שלא גילה עונש על אותו עבירה בפירוש אומר שאין אותו עבירה ראוי לעונש. ותו"ת.
כמו כן יש לדון באין מזהירין מן הדין, אם חוששים שלא ידע כל שקורא בתורה באותו הלכה, ונמצא שאינו מזיד (לא נראה שזה אפשר, שצריך התראה. ואולי אף התראה לא יגלה עליו, שלא יאמין למתרים עליו. גם יש לומר שיש נפק"מ כאן, שעשה תורה אותו מזיד, ואז יחייב כרת, שאינו צריך התראה), או אם הוא שלא אמרה תורה כל כך בפירוש.
נראה שאולי אם יכולים ללמוד זה מזה יהיה תלוי באם הסברה להם שווה. ותחשב.[fn:25]
מאי היא- קשה למה לא אמר שהיא עריות. ואולי רצה לומר שבלי זה, היה הגמרא דורשים כמה שאמר לעיל לעיל, ואז אין מקור זה מחדש דבר אלא על שנים אלו. ויש לדון.
לרבי יצחק- משום חידוש אחד- כן שיטת תנא דבי ר"י (חולין (סה או קרוב לו), וסוטה (ג)). ק"ק ל"ל הביאו רש"י משם. משמע שרק צריך זה לומר שעושה קרא כן בפרשה, אבל לא שעושה כן בפסוק, שזה פשוט. וצריך לעיין שם אם קאי על פרשה אן קרא.
ב לאוים- יש לדון למה:
1. אפשר שזה מגלה ששני כריתות חלוקות הם
2. אפשר שמביא שנים אף על פי שיש כרת אחת, שעבר על שני ציווים.
3. אפשר- באמצע של שנים אלו- שמחייב כרת אחת שני פעמים, וכיון שיש שני סיבות לו, צריך שני קרבנות.
כדאית- ק"ק לל"א שבא אגב סיפא (שלא דן למה בא סיפא, אלא למה בא רישא). ותו"ת.
בפני עצמו- לכאורה, היה אפשר ללמוד כן ממה שאמר ר"י לבאר לימוד המנין, אלא אומר שאף בלי זה, יש דיוק. ותחשב.
מה- רצה לומר, רוצים שיהיה פיטום קטורת קרוב לשניהם כדי ללמד זה על שניהם. ויש לדון, שאף לימוד על אחד מהם יהני[fn:26], כמובן, שאם אחד אינו נפטר בחטאת אחת כשעשה הוא וחבירו, אף חבירו לא יפטור. ותו"ת. ואולי אינו כן, שאולי תלוי על איזה מביא אותו חטאת. ותחשב. וקצת צריך ביאור למה נחשב כן מן הקראי.
לולי לשון זה, היה נראה לומר שהבדילם משנה לומר שהם מובדלים, ועל שניהם חייב שנים, ולא אחד. ותו"ת.
גברא- ואם תאמר בין כך ובין כך אין שלשים ושש חטאות, שיש שנים מהם שלא חייב עליהם חטאת. ויש לומר ששאני התם שמיעט אותו משנה בפירוש (שאז יותר קל להוציא אותם, שאין צריכים לעיין בכל המנין)[fn:27]. ותחשב.
איתתא- אם נאמר כן, ק"ק למה יאמר כל המשנה בלשון זכר (הבא על…). ואולי הוא אגב לשון תורה.[fn:28] ויש לדון למה לא ידון בזכר אגב לשון התורה.[fn:29] ואולי הוא כדי למצוא יותר חטאות. גם יש לומר שקצת חידוש הוא שאף האשה חייבת, אף שתורה אומר כן ביותר פירוש על הזכר. אז, רצה לשנות את החידוש.
פסח ומילה (רש"י)- יש לדון בזה. מניח שאין חיוב כרת בפסח[fn:30]. זה מחלקת (חושב אני) בפסחים. מניח שאין חיוב כרת במילה. זה, לכאורה, נכון. ותחשב.
ורבי ישמעאל- קשה, שאז יש שלושים ושבע כריתות. ואולי אף שחייב שנים על אלו, עדיין נחשבים בחד קטיגור"י. דחוק. גם יש לומר שר"ל שגורסים זה, ולא גורסים, “אשה שנבעלה….”
דאמר (רש"י)- העושות- משמע יחס בין הנאה ללשון עשייה. זה מעניין. שו"ר שגמרא ב"ק אומר כן.
העושות- קשה איך רואים מזה לאו, שקרא זה מדבר בכרת. ויש לומר שהמשך הקראי הוא, “ושמרתם… ולא תעשו מכל התועבות… כי כל אשר יעשה… הנפשות העשות” אם כן, אולי משמע שכרת והלאו הם על בני אדם שווים. יש לדון בזה, שהיה אפשר לומר שהקרא אומר, “כי כל אשר…" על מה שאמר, “ולא תקיא… כאשר קאה….”
גם ק"ק איך לומדים מעריות של איש לשל אשה לחילוק קרבנות. ותחשב.
דאמר- ק"ק ל"ל דורש עושה מ"כל אשר יעשה.” אולי דורש מלשון רבים (שכולל אף אשה שעושה).
שלשים ושלש- יש לדון מה סובר בביאור לימוד של מנין:
1. אולי סובר שהלימוד הוא שמחלק אותם כיון שהם כריתות חלוקות. אז, מביא עליהם חטאות חלוקות.
2. אולי סובר שהלימוד הוא שאומר מנין כיון שיש פעמים שיותר קל לדעת מנין, שאז רק צריכים לראות אלו כריתותו ולמנות על מה פטור. ותחשב. ויש לדון אם הוא יותר קל, שבין כך ובין כך צריך לראות כל המנין שמונה. ואולי הוא יותר קל מפני שהמנין שמונה יהיה יותר קטן. ותחשב.
שב ואל תעשה- יש לדון איזה קרק’ לומדים מזה:
1. צריך להיות שהציווי הוא שב ואל תעשה.
2. צריך לומר שעבר אותו בקום ועשה.
מלשון גמרא משמע שהוא צד ראשון. ויש לדון, שאולי ראשון הוא רק סימן לשני (ויש לדון למה לא רק נאמר שני). אם נאמר שצד ראשון הוא דבר חלוק, צריך ביאור מה הוא. ותחשב.
וניתני… דתניא- לכאורה, לא צריך לההיא ברייתא לזה, שכבר הניח כן בקושיה, ולא הביא ברייתא עליו. ואולי זה קודם שנתחדש שיש, בודאי, פעמים שאינו כן, ויש קרא שמשמע שאינו כן. ותו"ת.
שגגת מלאכות- יש לדון למה אז חייב שנים:
1. חייב מחמת טעותו (לא היה לו לטעות). כיון שטעה בשני טעויות, חייב שנים.
2. אולי המעשנים שעשו הם חלוקים במה שטעות חלוק גרם עשייתם.
* ג:
** דעד כאן- יש להעיר שאף אביי צריך חידוש זה (עיין ברש"י, שכן כתב). אם כן, מעניין מה שאומר כן רק כאן. ויש לדון מהו הצד לפטור. אם הוא שטעה בדבר שהוא פשוט במאד, ואז הוא קרוב למזיד, אז יש לומר ששבת פשוט, וע"ז פשוט, אבל דין אביי אינו פשוט. שור- קשה, אז, למה יכתוב שור; ישתוק, ונדע את הדין.
* ד:
** מצטרפים- היה אפשר לומר שצריך קרא שני לכלל גם מה שאינו בזרצים המטמאים. נראה שאז קשה למה צריך קרא גבי שרצים המטמאים. אז, צריך לומר שהוא כדי לגלות צירופם לטומאה. לדם קדשים- אז, קשה למה צריך ההיקש. ואולי זה רק לפי רבנן. וקשה, שהמשך גמרא משמע שהוא אף לרבי יהודה. ואולי לא היינו דורשים אותו כן לרבי יהודה בלי היקש, והיינו דורשים קרא השלישי כרבנן שחולקים על רבי יהודה בדם התמצית. נמצא, אז, ששיטת רבי יהודה הוא לשיטתו. ותו”ת.
* ו.
ריח- יש להעיר שסיבת ריח חלוק מן השאר, ואף על פי כן, כוללם לליס"ט אחד. ותחשב.
* ו:
** א"ל ההוא- לא היה אדם במעשה שיאמר כלום. צריך לומר שקאי על רבי שמעון (שזה שיטת רבי שמעון).
* ז.
** במבעט- קשה, שעדיין יאמר שיש לו לומר "חוץ ממי שאינו מבעט ובא יום הכיפורים.” מכפרת- מוזר שלא יהיה נחשב מומר. ואולי חושב שאינו ראוי לכפרה כיון שחטא. רבי- משמע שרבי כתב סיפרא. עיין בעין זוכר לחיד"א, שמביא שרמב"ם כתב שרב כתבו. ועיין בגירסת רש"י. שבים- יש לומר שקאי על אותם שלש עוונות שמזכיר רבי. דלא הוי ליה שהות- ק"ק ל"ל אומרים ש"קל וחומר מכורה כבר….” ורמינהו- צריך ביאור מה קשה, שאולי רוצה בכפרה, אלא רוצה אף בעבירות. ותחשב. תימא לי (רש"י)- יש להעיר שזה רק הוה אמינא.
* ז:
אור שמונים- מעניין שנוקטים בציור סתם יולדת נקבה.
* ח.
** בבלי- עלו בני הגולה- קשה, שהיה ר"ח בזמן רבי, ואיך נאמר שנשתכחה תורה מישראל. ונראה אולי שזה היה אחר ששכח רבי תורתו, ור"ח בא והחזיר לו שש סדרים (עיין גמרא נדרים). ויש לדון, שאז לא היו בניו שייכים. עוד יש לומר שהיה אחר מיתת רבי. לא נראה כן, שלחד צד בכתובות, מת קודם רבי. ותחשב.
ח:
עד שיזרוק- לשון זה מוזר, שהכל מחוסרי כפרה עד שיזרוק. ונראה שאולי היה אפשר לומר בלי מילים אלו שרק אומר שמה שצריך טבילה אינו כדי להיות גר (או שלכן צריך מילה), אלא הוא מפני שאז הוא מחוסר כפרה, וזהו כפרתו. אז, אומר שהוא מחוסר כפרה עד שעת הקרבת קרבן. (ואז, אין סיבה לחשוב שהוא רק מחוסר כפרה בלי טבילה, אלא מניחים שהוא חלק ממה שעושה אותו יהודי).
זב- יש לדון אם הם טומאות חלוקים, או רק יש חילוקים ביניהם. באמת, יש להעיר שמעניין שיש להם אותו שם, שמה שיוצא מגופו חלוק, ומה שעושה אותו חלוק. הדמיון הוא רק דינים שיש לו. ותחשב.
* ח:
בשרו (רש"י)- עיין בגמרא נדה לה: שכתב שבא מבשר מת. ותחשב.
עולה ושלמים (רש"י)- נראה שאומר שרצה לנקוט תרי מינים כדי לשאול על תרי מינים אחר. ותו"ת.
אפילו מנחה- משמע שהוא יותר חשוב מעוף. וצריך ביאור, שאין עני יכול להקריבו.
* ט.
ויאמר ה’ (רש"י)- משמע שמה שאמר ה’ ומה שכתוב בתורה אינם שווים. ותחשב.
* ט:
המקנא- ק"ק למה עשה שנים אלו לשני משניות.
* יא.[fn:31]
* יג.
** אמר"פ- צריך ביאור מה אומר, שלכאורה, זה אמת בכל איסורים. ואולי רישא מיירי ברק אכל זית. לא נראה כן, שאז היה לו לומר כן אף בסיפא. ואולי אין זה הדרך בסיפא כל כך כמו ברישא.
דמליא- יש לדון מה אומר:
1. לפעמים, פיו כבר מלא, ואז לא יונק לזמן. באותו זמן, יש טיפה על הדד.
2. דד בפיו, ופיו מלא חלב. אז, בזה נוגע דד בחלב.
* יג:
משנה- עיין במה שפירש רש"י. גם יש לומר שהוא זיל קרי בי רב, כיון שהיה ידוע. עדיין צריך ביאור שלא חשב גמרא כן בהוה אמינא (ואולי רש"י רק מבאר את זה), שלא היה פשוט לגמרא לומר כן. ותחשב.
זיל קרי בי רב- לכאורה, רצה לומר שהוא פשוט, ולא יטעה בו.
ויש להעיר שלכאורה, אם אומר את הקרא ממש, אז צריך לומר שאף במשנה אומר את המשנה ממש. אז, פשוט שהוא מותר, שרק אומר משנה. ונראה שחוששים שמא טועה בו. אז, קשה למה לא אומרים כן בקראי. ויש לומר שיודע קראי כל כך טוב עד שלא יטעה  (או שאם חושש שאינו יודע אותו כל כך טוב, יעיין בו).
גם היה אפשר לומר שמניחים שמא שכח, אבל אין אחד פוסק מפיו, שכיון שאמר שקרא הוא, יראו בקרא, ומזה יפסקו. אז, אי אפשר לו לטעות בדבר שיגרום רע. ותחשב.
יד.
רובא- קשה ל"ל אומר שחתך את האבר, והעלה חצי ממנו. אולי אז היה קל לתרץ שמיירי בחתיכה אחת.
כגון שאכל- לא הבנתי למה זה חלוק מהא דר"פ, שלכאורה, הענין הוא שאכילת חלב זה יש בו מכל האיסורים. ואולי דן אם אף צריך שהוא חלק מכל מה שיש בו איסור.
אלא דרפרם- אז, עדיין יש לדון על מה אמרו.
יש בא- ק"ק למה לא מנה גם בא על אשת אב (וכגון אם עשה ייבום).
יד:
איסור מוסיף- בביאור זה, נראה שאולי מה שאין איסור חל על איסור הוא שאין לדבר השני שם של מעשה השני כל כך, שאין מה להוכיח שהוא כן, שאין איסורו מוכיח כן, שכבר היה אסור. אז, כיון שמשנה דיני איסורו, יש שמוכיח כן, ואז יש לו שם של איסור שני. ותחשב על זה.
דאיכא- לשון זה (ולא "דאי איכא") משמע שצריך להיות שיש בן כדי שיהיה הנפק"מ נוגע, ולא די מה שיש לו כוח לחדש נפק"מ.
אר"א… דבר אחד- בדרך כלל, אביי אומר "… אמרו דבר אחד.”
ריב"נ- אין להקשות איך נושא בתה ובת בתה, שקידושין לא חלים על אשה ובתה, שיש לומר שנשא אשה ובת אחותה.
גופים מוחלקים- בשניהם, עובר בשעת מעשה אחרון, וזה רק מעשה אחד. אז, צריך לומר שמחשיב אותו גופים מוחלקים כיון שהאיסור אינו רק בעשיית השני, אאל בעשיית שניהם (קשה, אז, למה לא צריך התראה לפני הראשון. ואולי אין הכי נמי, צריך.). צריך לומר שבאשה ובתה אינו כן. ותחשב בחילוק זה (שלכאורה, רק אסור כשהוא נשוי לבתה). ותחשב על זה.
* טו.
אלא אמר קרא- קשה, אז, עדיין על ר"ג.
* טו:
וחותכו (רש"י)- היה אפשר לומר שהוא מפני שחששו שמא יפול ברגל, ויטמא אז, וברגל, רגילים בקדשים, ואז חותכו קודם כדי שלא יטמא קדשים. ותחשב.
זב או טמא מת- משום שסופו- נראה שהענין הוא שלא מטמא את המים כיון שהוא לא חשוב, שעומד ליבטל, שעומד ליבלע. מקשה ממה שבסיפא אומר שטהור (ק"ק, שלא מביא את זה), ואף שהמים נוגעים בבשר הטמא. ותחשב.
מה לאוכל שכן נהנה- זה לכאורה, סיבה או שמה שעשה הוא יותר רע או שמה שעשה יותר עשה. עדיין צריך ביאור למה אז יחייב יותר חטאות, שלכאורה, הסיבה לפטור אותו מיותר מאחד הוא שנחשבים כאחד. אם כן, קשה למה אלו יעשו שלא נחשב כאחד.  מדרהר אני צד לומר שאולי אף שכל עשייה עושה דבר שווה, ואז חייב רק אחד, יש יותר הנאה לו, ויש יותר ממה שרע, ואז יותר קל לומר שיחייב שנים עליו, שיש שני רעים, שיש שני הנאות לו. זה אומר, חושב אני, שאולי ההנאות רעים, ואז בשני הנאות, רעו כפול, אבל במעשים, מעשים גורמים רע. ותחשב למה יהיה כן. ותחשב.
מאי קשיא- נראה שסובר שאילו לא היה דבר קשה לר"ש, לא היה אומר ששמע ששאלו על דבר אחר, שאין חילוק על מה אמר אותו. ויש לדון, שאולי אמר אותו כדי שנוכל לומר דבר כמו ששמענו מרבותינו. נראה שאולי הסיבה לומר כמו ששמענו הוא רק שאז יותר קל לזכור, שזה מראה לו אמירת רבו (ותחשב). אם כן, אם אדם לא זוכר שרבו אמר כן, אין סיבה לומר כן, אף שרבו אמר כן.
כיון שהגענו לזה, נראה שהוא טוב לומר מה שחושב שרבו אמר, שזה יראה לו אמירת רבו. אז, לא רק מדייק ממה שלא היה סיבה לרבי שמעון לומר כן, אלא אף רע היה לאחרים להניח כמותו. ותחשב.
מה לאוכל- יש לדון אם רבנן לא מודים לזה, או שסוברים שהיה אפשר לר"ע לדחות כן, אלא שכבר דחה בכמה מהלכים אחרים. ויש לדון, שאולי להיפך, כיון שדחה בכמה דרכים, רואה שדוחה בכל אופן שירצה. אם כן, היה לו לומר דיחוי זה. ותחשב.
** מן הדין- קשה, שכבר אמרו שלא שמעו, אלא למד מן הדין. ונראה שאול יהיה אומר שלא שמע מי שידע מרבו מרבו… דין זה, אלא רביו אמרו קל וחומר. ודחוק.
לשון "ורואה אני" משמע שאמר הקל וחומר מעצמו.
אמר"ש לא כך שאלו (בגמרא)- לא הבנתי מה עושה כאן גמרא, שאמר כן ממש לפני כן. ותחשב.
המאכיל- רצה לומר מעשה זה כולל יותר, שיש מינים חלוקים להביא לו הנאה. מעניין לי שזה נחשב פירכא. ותחשב.
ונראה שאין לומר שהפירכא הוא רק מה שזה בדבר שאין בו זה, שהרי זה יהיה פירכא כמעט בכל דבר, שאיסור חלב, למשל, נוהג בחלב, דלא כאיסור דם (ויש לדון, שאולי יש חילוק בין אם יש יותר מעשים לאם יש יותר חפצים שעליו נוהג). אז, נראה שהענין הוא שהוא על יותר דברים. ותחשב.
צירף- נראה שאולי הענין הוא שאין האיסור עשיית מעשה, אלא היות לו ההנאה. אולי, אז, אין בעיה בצירוף, שצירוף הוא בעיה כיון שאין שניהם בתוך חד מעשה, ולא עשה אותו מעשה שאמר תורה שלא לעשות. כאן, שהבעיה הוא רק שבא לו ההנאה, כאן, כיון שבא לו ההנאה, חייב. וצריך לחשוב על כל זה.
מה’ זבחים- דר"ש- משמע שרבנן לא יסברו כן. יש לדון למה לא יאמרו כר"ש (גמרא רק מקשה זה על רבנן, אבל לא על ר"ש).
גם איני יודע מה כוונת רש"י כלל, שאין שום ר"א נזכר בעמוד זה. גם צריך ביאור מי הוא רבי יוסי זה. נראה שהוא ריב"י, ורק אומר שמו הראשון, כיון שיש רק רבי יוסי אחד בעמוד זה. שוב ראיתי בתוס’ פ"ד ששם גורס אף ר"א. לכאורה, רש"י גרס כך.
טז.
תנאי- לולי זה, הייתי אומר שמשנה אומר ראשון כדי להודיע שכן הוא אף לר"י ור"א, ושוב מביא המחלקת בשני, לומר שרק בזה חולקים. אם כן, אין לדייק מזה, ואין צריך לומר שהוא מחלקת תנאים בתוך הברייתא. ותחשב. אם כן, לכאורה, יש ראיה.
חמשה דברים- נראה שלומד ממה שצריך ברייתא לומר שמצטרפים, ואז צריך לומר שיש חילוק חשוב ביניהם. ותחשב.
שני אזהרות- יש לדון מה לנו בזה. לכאורה, לא עושה שהאיסור הוא יותר רע לו (אלא אם כן נאמר שחלק מן האיסור הוא שגורם לה לעבור), אלא הוא סימן שהאיסור הוא יותר רע, שצריך להזהיר איש ואשה. יש לדון, שאולי צריך להזהיר שניהם לציור שאחד מהם קטן או קטנה[fn:32]. גם יש להעיר שאין זה שייך, לכאורה, בשבת. אז, יש לדון אם יכל להיות פירכא. ותחשב.
ימים שבינתיים- יש לדון מה זה אומר:
1. מניחים שזכר בימים שבינתיים, אלא שכח שזכר.
2. אולי ענין שני העלמות הוא שיש שני תביעות עליו, ששכח שני פעמים. אם כן, יש לומר שכאן יש תביעה עליו במה שלא זכר בכל השבוע. ותחשב.
3. על שני צדדים אלו, יש לדון, שהרי לכאורה, יהיו גם בשוכח מלאכות. ואולי זה יותר קל ללמוד.
4. אולי רק רצה לומר שיש חילוק ביניהם, ולא דומה החלוק להעלמה, אלא עושה דבר שווה, והוא שיחייב שני חטאות.
5. החלוק הוא שזה בשבת זה, וזה בשבת אחר.
6. לא נראה כן, שנראה שזה השאלה אם הם כגופים. ועיין לקמן. על כל פנים, בזה היה נראה פשוט לחייב שנים אף בשגגת מלאכות. ותחשב.
7. אולי שני שכחות הם, ששכח דבר חלוק- שכח שיום זה שבת, ושכח שיום זה שבת. ותחשב. אף על זה, דמיון לשני העלמות לא נראה. גם יש לדון למה זה נחשב שכחה חלוקה אם לא שנאמר ששני שבתות חלוקים (שאי לאו הכי, נאמר שאף בשני פעמים בחד שבת הוא כן, ששכח שזה שבת ושזה שבת. ויש לדון, שאולי שם הוא אותו קדושה ששכחו.). ואולי אעפ"כ הגדר היה חלוק. ותחשב.
אי לא- אם יודע שכגופים דמיין, קשה למה לא יהיה אותו סברה שייך בשגגת שבת. ותחשב. ועיין ברש"י שמבאר שחייב על שני גופי מלאכות בשגגת שבת רק אחד. צריך לחשוב על זה, שלכאורה, מה שחייב שנים על שני מלאכות בשגגת מלאכות אבל לא בשגגת שבת הוא שיש שני שגגות בשגגת מלאכות, ששכח מלאכה זה וזה. אם כן, כאן, ייתלה באם נחשב שני שגגות (ששכח זה וזה). אם כן, אין לחלק ביניהם.
באמת, לא הבנתי כל כך למה אין אומרים בשוכח עיקר שבת שיחייב על כל מלאכה אם אומרים כאן שיחייב בכל שבת. בשניהם, אין שכחה חדשה, אלא ששכח על שני דברים רעים. ותחשב. וצריך לומר שהוא מפני ששבת זה יותר חלוק משבת אחר מחילוק שבין מלאכה למלאכה. זה מעניין. ותחשב על כל זה.
טז:
מודה- אם כן, אין ראיה מה סובר שידיעות מחלקות, אלא מניחים שלא שאל על זה. ויש לדון, שאולי בלי זה, לא היה לנו לומר שר"ג מחייב, שאז כולי עלמא מחייבים, שאין ידיעה לחלק. ותחשב.
יז.
בהמה (רש"י)- או שמודה לו ופושט מזה (שאין הכרח שר"ש יסבור שלא הודה ר"ע).
יז:
מצוות- יש לדון איך דורשים כן, שלשון רבים קאי על מה שעושה. ויש לומר שכיון שאין צורך לזה, אומרים שלשון רבים הוא על חתיכות שהם שם.
זו ואצ"ל זו- לכאורה, היה אפשר לומר שאמר סיפא לגלות על רישא, שממה שאומר סיפא בציור מיוחד משמע שרק הוא שם, שלמה יכפול ציור. ותחשב. ואולי עדיין מה שגילה כן, ולא רק אמר בפי’ הוא מפני שרצה לומר זו ואצ"ל זו.
פרושי- כמובן, קשה אז למה אמר ראשון כלל.
ר"א סבר- רצה לומר, כבר מצאנו מחלקת תנאים באם דורשים יש אם למקרא או למסורת. קשה, עדיין, איך אומר כן בשאר הציורים. ותחשב. ואולי רצה לומר שרב תנא הוא ופליג. קשה ל"ל רק אומר כן.
יח.
איקבע- נמצא מגמרא שאין צריכים שייקבע בשעת חיוב.
יח:
ונודע לו- מניח שנודע לו שעבר (או שאולי עבר). גם יש לומר שנודע לו שהוא אסור לעשות כן, ואחר כך שכח עוד. יש לדון, שאולי אף זה לא מחלק אלא מפני שגורם שיש ידיעה על חיוב האשם. ותחשב.
יום הכפורים- מניח גמרא שאם ידיעות ספק מחלקות, יום כיפור יחלק. יש לדון למה. יל"ד למה ידיעות יחלקו:
1. אז, כבר חל חיוב קרבן (שאי אפשר לחייב אדם שלא יודע שהוא חייב[fn:33]. זה לא שייך ליום הכפורים, שלא חל שום חיוב.
2. אולי הוא מפני ששניהם חלוקים במה שראשון לא היה בעולם בשעת שני. מה שאומרים שלא היה בעולם הוא שהיה עומד להתכפר, שהיה מביא עליו אשם. אם נאמר כזה, אז דמיון הגמרא פשוט.
3. אין הראושן כאן כל כך, ששינה המצב מן המצב שבו עבר. אולי ענין ידיעות הוא שבמצב כזה, לא היה עובר, שלא היה אוכל.[fn:34]
** עוד צד, והוא שאולי לא מקשה מדמיונם בלבד, אלא מקשה איך יכולים לומר ש"כל שבחטאת…" הוא דווקא, שידוע שיום הכיפורים מכפר על אשם תלוי, ועל כגון זה, היה פטור מאשם תלוי, ואז לא היה אחד מכפר לשני. אז, חייב שני חטאות. ויש לדון, שלא עושה שני חיובי אשם תלוי, אלא אפס חיובי אשם תלוי. ותחשב.
נראה
** על כל פנים, אם נאמר כן, אינו קשה אלא על ראייתו. ותו"ת.
עדיין אז, יש לדון למה יש דמיון יותר לידיעה וודאית בחטאת, ויש לדון בדמיון לחטאת כלל. וצריך לחשוב על כל סוגיה זה.
דמתיידע ליה וכפר ליה- לכאורה, לשון "דמתיידע" אינו דווקא, שבוודאי אפשר שלא ידע, ורק רצה לומר שבודאי נתכפר. ותחשב.
יח:
** - מעניין, שאם אכל, חייב חטאת, ולא אשם, ואם לא אכל, פטור, ואז אין צד שהוא חייב באשם תלוי. ויש לומר שכל שעשה דבר שיחייב אותו חטאת בעצם חייב גם אשם תלוי, שכמו שיש רושם על מי שאינו יודע, יש רושם על יודע. פטור רק מחמת חיובו להביא חטאת, שנמצא שלא נתרווח על ידי האשם, שעדיין צריך לחטאת, ולא יתרווח יותר מעל החטאת. אז, אי אפשר להביא אותו. כאן, שאי אפשר להביא חטאת, צריך להביא אשם. ותחשב.
מתנה
** אומר אני- חושב אני- ואולי שמעתי כן- שמה שרבי אומר לשון "אומר אני" טוב לשיטות שרבי סתם משניות כהכרעת רוב רבנן. נמצא, אז, שהיה רבי רגיל לומר הסכמות רבנן. אם כן, אולי צריך לבאר במקומות שאינו כן. ותחשב. על כולא- על כל אלו, צריך לחשוב. יט.
גמרא- יש לדון מהו הצד שהיה מודה ואומר שהלכה למשה מסיני הוא, שלכאורה, אין שום סיבה לחשוב שיסבור כן. ותחשב. ואולי הוא מפני שתנא לא אומר בפירוש שחולק, שאולי אז משמע שלא חולק, אלא מודה.
יט:
** מתעסק בעריות (רש"י)- ציור שאומר הוא ממש דומה למה שאמר גבי אכילת שוגג. צריך ביאור למה זה נחשב מתעסק, וזה נחשב שוגג. ותחשב. שוב ראיתי שכן מקשה שיטה מקובצת.
חתיכא דאיסורא- נראה שאולי מה שלא סובר כן אביי הוא שהוא גלגל החוזר, שאם נמצא שהוא מתעסק, נמצא שאין זה חתיכה של איסור, ונמצא שכיוון לו, ונמצא שהוא של איסור…. החולק יסבור או שמפני זה לא יוכל לחייב או שהוא של איסור במה שעושה ס"ר. גם יש לומר שהוא אסור במה שחייב אדם להרחיק את עצמו מזה (אלא אם כן הוא אונס). ותחשב.
מלאכת- צריך ביאור למה מביא את זה כאן, כיון שבא לבאר לפי ר"א, שחולק על מושג של מלאכת מחשבת. ותחשב.
* Footnotes
[fn:1] הוא בקט:. ואולי יש לדחות שאותו גמרא רק מכוון לומר שלא היה לו לומר, “אם שב…, “ אלא היה לו להניח שישוב כפשטות, שרוב שוגגים מכפרים, ועומד לשוב, והיה לו לומר, “אם לא שב….” אם כן, אין להביא ראיה מאותו גמרא. ותו"ת.
[fn:2] ולכאורה, יהיה אפשר בכל צד, שאולי כמו שכרת עושה שום סיבה, אולי אף עונש אחר עושה סיבה כזה, וחיוב סקילה מוסיף סיבה הכי גדולה לחטאת. ותחשב.
[fn:3] כמובן, לזה יהיה כל דין כרת יוצא מן הכלל של מה שאדם חייב רק עונש אחד. ותחשב.
[fn:4] לכאורה, יש להביא ראיה ממה שאינו חייב כרת אם שב. הרי, כבר קבל כרת. ויש לומר שאין הכי נמי, ורק פוטר אותו מכאן ולהבא. יותר נראה לומר שחוזר למפרע קירבת ה’ לו. וזה קשה להבין, אלא שהוא כמו מה שאומר גמרא שחטאותיו נהפכים לזכויות למפרע. ותחשב.
[fn:5] באמת, צריך ביאור למה יהיה כן, שלכאורה, רע נברא, ואיך היות לו צער יכפר עליו. היה אפשר לומר שהוא מפני שרע שעבירה יגרום טוב (זהו מה שנקרא, “אין חוטא נשכר"), ואז, כשנענש, הוא טוב.      כיון שהגענו לזה, יוצא שיש חילוק אחר, והוא שקרבן מכפר, והוא שעושה שמה שהיה רע אינו רע. עונש אינו כן, שעונש עושה שאין אותו רע (של עבירה גורם לטוב) כאן. ונראה, אולי, לומר צד אחר, והוא שאולי רע של חטא שגורם עונש הוא שגילה שלא חושב שה’ הוא שולט עליו, שהלך ועשה נגד מה שצווה לו ה’. כיון שנענש על מה שעבר על ציווי ה’, פשוט שה’ הוא השולט עליו. אם כן, אולי מבטל הרע של העבירה. ולא נראה כן, שצריך אדם לקבל מיתה. נמצא שאף בידיעת עונש, יש עדיין רע. ואולי אין הענין שכיון שיודע שנענש, לא יוכל לחשוב עוד שה’ אינו השולט, שלכאורה, אין זה נכון, שאולי יחשוב שבלי שליטה עשה בית דין לו כן, אלא הוא שבני אדם מכירים שה’ שלט בו. יש לדון מה לנו בזה. ותחשב.גם קשה על זה למה לא שולט בו ה’ בעשיית דבר טוב. אולי הוא מפני שאז חוטא נשכר. קשה למה לא עושה שדבר מוזר שאינו רע ולא טוב קורה לו. ואולי גם רוצים לקיים ענין ראשון שכתבנו.ודע שבכל זה, הנחנו שעושה שום טוב ומבטל הרע. אולי כפרה לא רצה לומר שמבטל הרע, אלא רצה לומר שמגין עליו מיסורים. ואם תאמר פעמים שגמרא אומר קנטרס"ט בין הגנה על יסורים לכפרה. ויש לומר שר"ל שמגין עליו לעולם. גם יש לומר שמבטל סיבה לעונשים (שהסיבה לעונשים ויסורים הוא שפייר הוא שמי שעושה רע בא לו רע). ותחשב. דבר שמגין עליו הוא כמגן, והוא שיש סיבה, אלא שמונע אותו מלהגיע לו. ותחשב.
[fn:6] ויש להעיר שיש ראשונים (רמב"ם) שסוברים שאין חיוב לשוב. ויש לדון. זה אומר שאף שתשובה גורם כפרה, לא חייב ה’ שאדם ישוב, אלא שאם ישוב, יכפר. אולי, אז, לא יהיה ה’ מחייב הקרבת קרבן לכפר, כמו שלא חייב תשובה לכפר, אלא חייב אותו כדי לצער לו.
[fn:7] אגב, יש לדון למה נקרא שמו "קרבן חטאת.”:הפשטות הוא שנקרא כן כיון שבא על חטא.אפשר שהוא מפני שהוא מחטא (מטהר) אותו.
[fn:8] ו"נחשב כאחד" אומר או שבני אדם מחשיבים אותם כך או שיש בהם דמיונים שהם בדרך כלל, אבל אולי לא הכא, יסודיים בעשיית שני דברים כאחד. ותחשב.
[fn:9] כך היא הגירסא בגמרא שלנו, אבל לכאורה, אינו נכון, וצריך לגרוס כמש"א גר"א, שכל הדברות נאמרו למשה, ורק אלו נאמרו לכל ישראל מה’. אז, צריך לגרוס" “שנאמרו להם לישראל.”
[fn:10] ועיין ברש"י בתחילת נדה (נב.) גבי ברכה על ריחני.
[fn:11] אבל, הוא גופא- מה שרש"י מניח כן במשנה- צריך ביאור.
[fn:12] רצה לומר, ואז יש סיבה חוץ מטובתו., ואז הוא כשאר ציורים. ותחשב.
[fn:13] עיין בשי"ח ש"י שדנינו למה מזכיר כאן כל המנינים ודרושיהם: “מנינא- כאן דורש כל המנינים; ובתחילת ערכין דורש את ה"כל"ים וה"כהנים…"ים. ואפשר שמסודרים כאן כיון שסוף של ש"ס הוא (וקצת קשה למה אינו בנדה. ואולי אין "כל" או מנין בנדה. אינו נכון, שמונים ארבע מיני דם טמאים.). עוד יש לומר שהיו מסכתות אלו קטנות, ואז נתנו הבם סידור דברים אלו.”גם נראה שיכולים לומר שכאן דורש את כולם מפני שמקשה שאלה של מנין שהוא ביותר קשה, שמה שמנה קשה, ולא רק מה שאחר כך או לפני כך מזכיר הסכום. זה, כמובן, רק אפשר לצד זה. ותחשב. (ונראה שכאן מונה מנין כיון שרובם (ובפרט ממה שמביא בתחילה) ממסכתא זה.
[fn:14] כוונתי לומר שיש לדון אם יש סיבה שאותו אדם יכופר או שאותו עבירה יכופר. לראשון, יהיה נמצא שצריך קרבן אחד על חטאות הרבה. ויש לדון, שאולי יש סיבה לשנות את האדם בכפרה זה רק קצת. ותחשב.נראה שגם יש לדון איך מכפר, אם משנה את האדם, וממילא אינו מיוחס לאותו עבירה, שהרי הוא אדם חלוק, או שמשנה את העבירה, ואז אינו רע, או שאינו מיוחס להאדם. לצד ראשון, לכאורה, יעשה שאינו מיוחס לשום אחד מעוונותיו. ויש לדון, שלכאורה, פשוט שאין מי שמקריב קרבן נמחל על כל עוונותיו (שהרי צריך גמרא לדון למה אינו רק באחותו). ותח’.
[fn:15] ויש לדון, שאולי רק היו בני אדם מגרעים ציור מדעתם, ולא היו מוסיפים ציור, ואף בלי מנין. ותחשב.
[fn:16] ואולי אפשר- ועיין רש"י לקמן, שכן משמע (ויש לדון למה אומר כן רק לקמן)- שהיינו אומרים שתנא טעה והוסיף דבר.
[fn:17] יש לדון בזה, שאולי קרא רק מוסיף כרת שני לאחותו, אבל עדיין הוא בתוך כרת ראשון. לא נראה כן, שאין חייבים חטאת שני עליו. ויש לדון, שזה תלוי אם חייב מחמת העבירה או הכרת. ותחשב.
[fn:18] ודע שגם היה אפשר לומר שגמרא אומר כן כיון שלמסקנא רק מלמד אלו. אף בזה, יש לדון למה לא לומדים מהיקש דר"י. ואולי לומדים, ונקט אלו כיון שלומדים את אלו קודם. ותו"ת.
[fn:19] שוב ראיתי שכן אומר רש"י.
[fn:20] נראה שיש לדון בעריות שהם יחס עם יחס (כמו אחות אמו), אם הענין הוא שיש רע מפני שיש יחס קלוש זה, או שכיון שהיא דומה (מיוחס) לאם, יש קצת מאותו רע, וכיון שהיא דומה לאחות, יש קצת מאותו רע. אם כן, לכאורה, רעתה בא משני רעות מורכבות. אולי יש הוה אמינא שכיון שיש צד השווה בין שניהם, לא יחייב קרבן שני על השאר. יש לדון אם מחדש שמביא על השאר (לא נראה כן, שאם כן, יהיה נמצא שאם בא על אמו, על אחותו, ועל אחות אמו, יחייב רק שנים. לא נראה שזהו הדין.) או שכיון שהוא מורכב כולו חלוק, או כצד ראשון. ותחשב.ויש להעיר- ונראה שבין כך ובין כך זה קשה על הגמרא- שצריך ביאור למה אין הוה אמינא כזה גם גבי אחות אמו ואמו. ואולי יש הוה אמינא כך, ונלמד שחייב שנים ממה מצאנו (או גזרה שווה) מזה. ותחשב.
[fn:21] גם ק"ק למה, אז, לא תירץ גמרא כן למה שהקשה, “הרי שמות… הרי גופים….” ויש לדון, שאולי קושטא קאמר, ולא סבר באמת שיש הוה אמינא בשמות וגופים חלוקים, אף שהשמות דומים. ותו"ת.
[fn:22] או מ"יצא מן הכלל.” ויש לדון אם מה שזה אשה ושה אינו אשה די לומר שהם כללים חלוקים.
[fn:23] וגמרא לא רק מניח שיכולים ללמוד, אלא מניח שמוכרח ללמוד, שלא דוחה שרבנן לא לומדים מזה כיון שסוברים שאין ללמוד זה מזה. ותו"ת.
[fn:24] זה יכול להיות, לכאורה, סימן או סיבה, אבל נראה שהוא סימן. ותחשב.
[fn:25] יכול להיות אף שהם שווים שאי אפשר ללמוד זה מזה, שאפשר שנוהג אותו סיבה יותר באחד מבחברו. באמת, כן צריכים לומר אם לא תאמר צד שווה בשניהם. ותו"ת. וצריך לחשוב למה נאמר סברה אחת יותר בדין אחד. ותחשב.התלייה שכתבנו שייך רק אם יש קל וחומר ללמוד; וזה יהיה אפשר רק אם לשנים יש אותו סברה. ותו"ת.
[fn:26] ויש לדחות באופן פשוט לומר שלא היינו לומדים אם רק היה קרוב לאחד מהם, שלא היה אז הוכחה שקירב אותם כדי ללמד, אלא מפני דמיונם. ואם תאמר יכתוב קטורת אחר סך, שלא שייך לו. ויש לומר שהוה אמינא שכתבנו אחר פיטום, אחר שגמר כל הענין של פיטום. ויש לדון, שהיה לו להקדימו, כמו שאומר גמרא כאן. גם יש לומר- וזה יותר נראה- שרוצה יותר לגלות כך, שאז עדיין הוא קרוב לפיטום. ויש לדון, שלאידך גיסא, עכשיו מפריד בין שמן. ותחשב.
[fn:27] כמו שבארנו לצד ראשון שבד"ה שאם עשאן. וע"ש.
[fn:28] באמת, יש לדון למה תורה יעשה כן. אין זה כל כך קשה, שסתם דברים נאמרים בלשון זכר (כמו אם אומר אדם לשון רבים שכולל זכרים ונקבות). גם יש לומר שיותר יש צורך לזרז לזכרים, שיש להם תאוות יותר חזקות.
[fn:29] יש שני טובות בזה:אז, יהיה דומה לתורה.אז, הלשון שאמר אגב מה שאמר תורה יהיה טוב.
[fn:30] אולי רק חש לשיטה שאומר כן.
[fn:31] מצאתי שכתבתי בצד גמרא שלי:קריאה- צל"ע למה על זה נקטינן (למה נקרא שם מכות על שם הקריאה). ועוד, שהרי לכאורה, יש לומר משמעות שניה. ותחשב. אז, כיון שהגענו לזה, יש לומר שלא חולקים, אלא אומר שמשמע אותו בשני דרכים.תהיה- צריך ביאור מה הוה ליה לומר. (נראה שהנחתי שפירוש הקרא הוא ש,בקורת" אומר מלקות או כדומה, ועליו אומר ש"תהיה,” והוא שהבקורת תהיה. קשה, אז, מה מדייק שצירך לומר לשון נקבה, כיון ש"בקורת" הוא לשון נקבה. הבנתי שאולי בקורת אומר שהיא חייבת מלקות, ואז מובן דרשת גמרא. ויש לדון.דברי ר"ע- רצה לומר רישא דזה.כל עריות- עיין בריש מסכת חגיגה.
[fn:32] אין זה שווה לקושיית משנה. ותו"ת.
[fn:33] ויש לדון, שאולי יש חיוב לדעת אם הוא חייב, ולשמור שיביא אם הוא חייב. ותחשב.
[fn:34] אם נקודה זה נכון, קשה למה אומר כן בכפרה. אז, יותר היה נראה לומר שרק רצה לומר שיש חילוק בין הזמנים. ותחשב.
