** גמרא רמב"ם תוס’
דן
אם אי כבתה זקוק לה. מביא קשיא מברייתא שאומר שזמנו הוא משתשקע חמה עד שיכלה רגל מן השוק. הניח גמרא שזה אומר שבכל אותו זמן, צריך להדליקו עוד אם כבתה. דוחה גמרא שאומר שיכול להדליק מזמן שקיעה לזמן עד שתשקע חמה. גם אומר שאולי אומר שצריך להדליקו באופן שיוכל להידלק לאותו זמן.
כ’ שאותו זמן הוא "יותר לחצי שעה.” שני תירוצים אלו נוגעים למעשה, כיון שפוסקים שאם כבתה אין זקוק לה. גמרא אומר "אי נמי" בין שני התירוצים, ודנים ראשונים אם חולקים שני התירוצים.
כ’ שמפני הספק, מחמירים כשני השיטות.
** ר"י
יש לבאר תירוץ ראשון. יש ראשונים שכ’ שלכת’ ידליק משתשקע החמה, שכן משמע לשון גמרא (שאומר שלאחר כן מדליק אם לא הדליק).[fn:1]
כ’ שכיון שבזמנו ומקומו הדליקו בפנים, אין זמן זה נוהג. יש חולקים. זה תלוי במחלקת אחר, שחולקים אם תלוי סוף זמנו בזמן שאומר גמרא או זמן שבזמנינו ובמקומות שלנו כלה הרגל.
** פוס בשבת בפסחים ראשונים פוס’
תחילת זמן (משתשקע החמה) הוא זמן קצוב. יש לדון מהו "משתשקע החמה.” חולקים
’ לאיזה זמן מכוון גמרא כשאומר "תשקע החמה.” יש סוגיה
, ויש סוגיה
. דנים
ו
בביאורו בגמרא כאן. יש כמה שיטות בזה בראשונים:
1. יראים כ’[fn:3] שזמן ההתחלה הוא משמתחיל חמה לרדת מראיית העין.[fn:4] אומר גמרא שבין השמשות הוא שלש חלקי מיל. כ’ שזה הזמן קודם שהשמש יורד ושוקע ממש, שזה כבר נחשב לילה. כ’ שצריך להיות ההדלקה בזמן שניכר שנדלק למצווה. אז, צריך להדליק כשהוא עדיין יום. (ויש מן הפוס’ שאומ’ ששקה"ח הוא סינסו"ט שאומ’ שצריך להדליק כשעדיין ניכר, קודם בין השמשות. יש ראשונים שכ’ שצריך לשהות אחר זמן היראים, שאין אור ניכר ביום.) שיטת יראים הוא שיטת יחיד; אף בני אדם שמקפידים להדליק ארבע פעמים לא מקפידים כשיטת יראים.[fn:5] רק לנר חנוכה לא מקפידים לו; בהלכות שבת, יש שמקפידים לו (ולכן מדליקים נרות שבת שמנה עשרה מינו"טים קודם שקיעה). גם חשו לו בערב יום הכיפורים, שקבעו זמן תוספת לכלל שיטת יראים.
2. יש שכ’ שהוא סונס"ט[fn:6]. בפשטות, צריך להיות כולו תחת ההורייזו"ן. בכמה זמנים, כשזמן סונסי"ט נכ’ בעתונות, הוא הזמן שאמצע חמה שקוע. הוא קצת מינו"טים לפני זמנינו, אבל אינו בעיה כל כך גדולה, שראיית החמה תלוי בכמה דברים, והזמן שנותנים תלוי בחום היום ודברים אחרים[fn:7]. אז, בין כך ובין כך, אין הזמן כל כך דווקא
3. שיטת הגר"א בבין השמשות והדלקה[fn:8] הוא שזה מתחיל מסונסיי"ט. יש בני אדם שנוהגים כך. אומרים שכך עשו פרושי ירושלים. אולי כך היה, אבל אינו כן עכשיו. באמת, אינו כל כך פשוט שגר"א עצמו עשה כן. אולי הוא מפני שלא רצה לשנות בפרהסיא ממנהג הקהל. ביאור הלכה מביא רמב"ם שסובר שמדליק בשקה"ח.
** חז"א ר’ שמואל עורבאך
לא פשוט אם לגר"א עושים בתחילת שקיעה או בסוף שקיעה; יש סיבה לומר השני, ואז הוא קרוב (או ממש) צאת הכוכבים.[fn:9] יש קצת סתירה בזה בגר"א. פרושים שבירושלמים עשו כתחילתו.
נהג להדליק כעשרים מינו"ט אחר שקיעת החמה, ואמר[fn:10] שכך היה מקובל במשפחתו לשיטת גר"א. זה סוף שקיעה של גר"א.
אמר שכן פשוט לו שגר"א סובר. אם כן, “משתשקע…" רצה לומר סוף של בית השמשות. סוף בין השמשות קשה, שהוא ¾ מיל. תלוי מהו מיל.
** תרומת הדשן שו"ע חק יעקב יש רש"י
כ’, וכן פסק
לקולא ולחומרא, שהוא שמונה עשרה מונו"טים.
סובר שהוא עשרים ושנים ומחצה מינו"ט. גם
סוברים שמיל הוא עשרים וארבע מינו"ט. תלוי בסוגיה בפסחים. פשטות הגמרא שם הוא כחק יעקב.[fn:11] (גר"א סובר או כשו"ע או כחק יעקב.) גר"א כ’ מ
שכל זה הוא רק ביום השווה, שאז הוא הכי מהר להיות לילה. הכי גדול הוא בתוך הקיץ (לא ביום הכי גדול, אבל קרוב לו). בחנוכה, הוא יותר גדול מביום שווה. אז, שהה חזון איש קרוב לעשרים מינו"טים.
** ר’ חיים וואלאזין בעל התניא מהר"ם מרוטונבורג
הקשה רבי איך נדלק באותו זמן כיון שמספק אינו לילה, ואז, ביום ראשון, אולי אינו חנוכה. קשה למה יתקנו כן. העיר’ שאולי וודאי יום הוא, ש
קבל שלילה הוא שש מינו"טים אחר סונסיי"ט.
כ’ שהוא ארבע אחר סונסיי"ט. אין חשבונות של ימים תלוי בלילה זה, אלא בשקיעה או כדומה. באר בעה"ת שהוא מפני ששקיעה הוא סוף היום של גובה א“י. לילה הוא זמן שהוא שקיעה בכל א"י. באמת
כ’ בפ’ שידליק בעוד היום גדול, כדי שיהיה ניכר שמדליק לפרסם את הנס.
בלוחות של חב"ד יש זמן מוזר. בעל התניא סובר כגר"א, וסובר שיש מיל של עשרים וארבע מינו“ט. אם כן, היה לו להיות כמו עשרים וחמש מינו"טים אחר שקיעה. מדליקים אחר זה; ר"ק שאל לאחד ולא ידע. אמר’ שחושב שמדליקים כמה שאמר רבי שלהם שהוא זמן הדלקה בחנוכה.[fn:12]
1. רבינו תם סובר שבין השמשות הוא מאוחר מזה. שקיעת החמה של פסול לינה הוא סונסיי"ט, אבל "משתשקע חמה" הוא שקיעה שניה. מאז, מתחיל בין השמשות[fn:13], ויש משם ¾ מיל עד לילה. זה הנקרא שבעים ושנים מינו"טים. אז, “משתשקע" הוא שלש רבעי מיל קודם סוף השבעים ושנים.
חולקים ראשונים אם זמן ההדלקה הוא בתחילת שקיעה שניה או בסופו.[fn:14] נתקבל לעשות בסופו, שהוא צאת הכוכבים. לכאורה, יהיה תלוי בכל מקום. אם כן, צריך להיות קצת מאוחר משבעים ושנים.
** חת“ס ר‛ נתן אדלר משנה ברורה פוסקים חת“ס
לא היה נהוג לעשות כן עד בימינו. באמת, השיעור של שבעים ושנים יש לדון. ביורו“ף, היה נהוג להחמיר בשבת עד צאת הכוכבים ממש (מתי נראו הכוכבים), ומחמירים לראות כוכבים קטנים, אף שיכול להקל בבינונים, כדי שלא לטעות, וכדי להוסיף על שבת. בארמאריק“א, כשכ‛ לוחי זמנים, כתבו זמנים מוזרים[fn:15], אבל לא כתבו שבעים ושנים מינו“טים. בבני פרק, כולם שהו עד שראו אור שבפוניבי“ץ (עד רמת גן ראו). אותם אורות היו חמישים מינו“טים אחר שקיעה. הוא זמן מאוחר אחר צאת הכוכבים בכל השנה בבני ברק. היה מיוסד על החזון איש, וכוון לעשות כר“ת, והיה על ידי ראיית כוכבים. בזמנינו שוהים אחר שבת מאד, אבל אולי זה רק לשבת, אבל לחנוכה אולי אין לעשות כן. ר“מ אמר לבני אדם להדליק כשראה הכוכבים, והוא כוכבים בינונים. זה כמו שבע או יותר מינו“טים קודם סוף זמן שבת.[fn:16]
נהג כר“ת, אבל היה לו לוח מרבו (
) שתלה הזמן בכוכבים (והיה קצת מוקדם). צריך ביאור איך ראיית כוכבים אלו תלוי בר“ת, שר“ת סובר שצריך לשהות ארבע מיל, שהוא לכאורה מאוחר מאד מראיית כוכבים. לכאורה, עושים כראיית כוכבים כיון שגמרא תולה בזה בכ"מ. עדיין צריך ביאור איך נבאר מש"א ר"ת.
מז‛ חומרת שעה וחומר למו“ש. יש
שכתבו ששעה וחומש הוא לילה בכל מקום ובכל זמן. אף שרואים כוכבים קודם לכן, צריך לומר שאין ראיית כוכבים ממש לילה. עדיין צריך ביאור ל"ל נאמר שאותו חושך של שעה וחומר יהיה לילה, ובמקומות אחרים יהיה, אז, זמן אחר. יש שסוברים מחמת זה שצריך להיות 16.9 דיגריי“ם תחת ההורייזו“ן. (כמו כן בעמוד השחר יש לדון בזה, שהוא שעה וחומש בא“י בימים מיוחדים, אבל במקומות וזמנים אחרים, רואים אותו אור בזמן אחר. בעלות, לא כ"כ קל לדעת מה עשו; אפשר שקעו אותו בראייתם. העיר‛ שבלי שעון וידיעת הנץ, קשה לדעת מתי הוא קודם הנץ, שרק יודעים מהו אחריו.
לא קבע על פי שעה וחומש. יש, ג“כ, פוסקים שכתבו שהוא לעולם שעה וחומש קודם הנץ.) לכאורה, קשה לומר שייתלה בזמן ולא, לפי האופק והזמן, בחושך שנראה. לכאו‛, צריך לומר שהסוברים שהוא לעולם שעה וחומש סוברים שכיון שהוא בא“י, קבעו כן בכל זמן ובכל מקום.[fn:17] יש הוכחה קצת לזה, שראשונים דנים בחשבונות של ד‛ מיל, ולא מעוררים שזה רק בא“י ובזמן מיוחד של שנה. (אין לנו לוחות של ראשונים.) למעשה, החומרות שעושים במ“ש לא נוהגים בנר חנוכה.[fn:18]
בלייקווד, קובעים סיי“ן של זמן הדלקה. הוא עשרים ושלש מינוטי“ם אחר שקיעה. שם, מדליקים בתוך סדר, אבל בשער התורה לא עושים כן, כיון שרב משה אמר לחוש לביטול תורה דרבים. חשבון של לייקוד תלוי במה שחושב שיוצא כמה שיטות שיכול (שיהיה בתוך שלשים או כדומה). רב משה אמר היה אומר להדליק בצאת הכוכבים. לכאורה, יש חילוק בין ראש ישיבה לפוסק, שפוסק ראה מהו ההלכה, ופסק כן, אבל ראש ישיבה ראה מה יכול לקיים. לכאורה, רואים כזה ברב משה בכ"מ, שאם נשאל לו, אמר הלכה, ואם שואלים אם יש ענין להחמיר, אומר שיש קצת ענין. שאל רבי לדיין וויס (מנחת יצחק) מה עושים בני חו“ל בא“י ב“ותן טל.“ אמר‛ שר‛ שאך פסק שבני חו“ל יאמרו בשומע תפלה. אמר שאינו פסק, אלא היה מסופק, והפסק הוא שיאמר בא“י. רב משה היה פוסק, ולא חש לפסוק.
(שאל אחד לרבי בענין ”ותן טל ומטר.“ בשנה שלפני שפברוארי אומרים אותו בלילה של דיסמבר חמישי. שאל איך שנה שלאחריו יעשה בו רושם. אין השנה שלאחריו עושה רושם, אלא הוא סימן. החשבון הוא שביום ששים אחר תקופת תשרי, משנים לומר ”ותן טל.“ יש שני חשבונות של תקופה. יש תקופת רב אדא, ששייך למלון, ויש תקופת שמואל, שהיה נקבע, אף שהיה ידוע שאינו כל כך נכון. זה תלוי בקביעות של לוח של יוליאן, ולא של גרגרי. שנה של חמה הוא שסה ימים ורבע. עושים כל שנה של שסה ימים, ומוסיפים יום אחד בשנה רביעית. תקופה הולכת שש שעות מחמת אותו רבע. אם התקופה הוא בתשע בלילה, יהיה בשלש בבוקר, ושוב תשע בבקר, ושוב שלש בין הערבים, ושוב תשעה בלילה. לכן, בשנה רביעית לחשבון יהיה בתשע בלילה שלאחר יום שהיה. אז, אומרים אותו ביום שלאחר יום שבדרך כלל אומרים אותו. אבל, בשנה שלאחר שנה רביעי, מוסיפים יום, ואז חוזר להיות ברביעי של דיסמבר. בשנה של מאה, שאין בו הוספת יום, ישנה ותן טל ומטר יום.
הקשה רבי למה באמריקא יש אותו חשבון של ”ותן טל ומטר.“ תקופה כאן אינו באותו זמן של יום או אותו יום של בבל, שכאן מוקדם שבע שעות. אם כן, לא נאמר בחמישי בשנה רביעית (אבל נאמר בשלישי בשנה ראשון). ותו"ת. ראשונים, כשדנים בזה, גם כן לא קשה, שגרו במקומות שהיו זמנם שווה עד כדי שלא יהיה חילוק לזמן של בבל. לא ידוע מי קבע לעשות כן באמריקא. אולי פוסקים קבעו כן, אבל אולי הבאים ראשון עשו כן כיון שלא ידעו, ואולי לא שנו אף שכבר עשו כן (כמו שרא“ש לא שינה בספיי“ן, אף שחשב שבמקומות שצריך גשם בשאר חלקי שדה), שאולי הקובע של הזכרות הוא מה עושים ציבור. כמו כן, שינוי של משיב הרוח תלוי בציבור, שאין זמן ביום קבוע, אלא שבזמן שציבור קובע שינוי הוא זמן השינוי. גם אפשר שכיון שנקבע לבני בבל, חו“ל נגרר בתר אותו תקנה, כמו שרק אומרים אותו בזמנים של שנה שצריכים מטר בבבל, ולא בשאר זמנים.
לפני כמה שנים, שאל רבי לר“ד פיינשטיין, שהיה מומחה בעניני לוח. חשב לזמן, ואמר שהוא שאלה טובה. כמה שנים אחר כן, מצא רבי חוברת שבו היה מכתב מר“ד פיינשטין בתקופות, והקשה שם אותו קושיה. היה נכתב כמה שנים קודם ששאל רבי. לא היה ר“ד שוכח דברים. לא השיב לרבי, ”כבר הקשיתי את זה,“ אלא אמר שהוא קושיה טובה, כאילו היה קושיה של רבי. רב משה היה עדיין בחיים בזמן הכתיבה (אמר רבי שאין כל בני אדם עסוקים בענינים אלו), שאל רבי לאחד אם היה ר“ד מדבר בזה עם ר“מ, ואמר שדן בו, ולא אמר יותר.)
חזר ר‛ לבעל התניא שמתחיל לילה אחר שקיעה. כשמבאר זמנים, תולה אותו בשקיעה והנץ, ולא כולל אותם ארבע מינו“טים. לכאורה, גר“א לא כולל שש מינו“טים של ר“ח מואלאזין. רבים מדליקים בשקיעת החמה, לעשות כשיטת הגר“א. לכאורה, לפי ר“ח, אין לילה מתחלת אז, ואינו אף בין השמשות, אלא לילה. אפשר, עדיין, שזמן ההדלקה הוא שקיעה (ואולי יש להדליק ביום דווקא, כמש“כ ר“י לעיל). על כל פנים, נמצא שבדעת הגר“א יש שלוש זמנים: שקיעה, לילה, וצאת הכוכבים.
* Footnotes
[fn:1] שאלתי את הגר"ק אם כן איך אפשר להדליק בשעה שכלה רגל מן השוק. אמר שני תשובות:אפשר שאז עדיין יש בו היכר. הערתי לו- והסכים- שאם כן, צריך לומר שחולק על רי"ד.אפשר שזה דין לכתחילה, אבל אין צורך. אם כן, צריך לומר שזמן ההתחלה הוא הזמן לכתחילה (על"ע).
[fn:2] יש שכ’ שזה רק מפני שזריזים מקדימים למצוות.
[fn:3] זה נוגע לדינים אחרים גם כן.
[fn:4] באר’ שהוא שקשה לראות אותו, והוא קרוב להארייזי"ן.
[fn:5] אמר’ שיודע שני בני אדם שמדליקים ארבע פעמים, אבל לא חוששים לזה.
[fn:6] כשהחמה שוקע תחת ההורייזו"ן.
[fn:7] שהרי, רואים את החמה כיון שצריך זמן לבוא ראיית החמה לנו. אז, יכול לפלוקטשואי"ט קרוב לשני דים ומחצה. הזמן הוא בחום האבאריד"ג.
[fn:8] כן כתב בעל התניא. מצוי הוא שגר"א ובעל התניא מסכימים, וזה מעניין.
[fn:9] תלוי בגר"א שכ’ שצאת הכוכבים הוא אחר לילה קצת, מפני ביה"ש של ר"י.
[fn:10] היה שמועה נאמנת.
[fn:11] תרומת הדשן יש לו פשט מחודש בגמרא. לכאורה, כד מינו"טים הוא ההוה אמינא, אבל יש ראשונים שאומ’ כן אף במס’.
[fn:12] הוסיף ר’ שכמו כן בכל הזמנה לנשואים, כות’ 5:00, שאז נשא רבי שלהם. יש שכות’ שהוא 5:00, שהוא זמן אחר במעון שלנו.
[fn:13] כתב ערוך השולחן שכך היה מנהג עירו. כך היה מנהג של כמה מבני הונגרי.
[fn:14] שבעים ושנים עשוי ממיל של שמנה עשרה מינו"טים.
[fn:15] באר‛ שכתבו זמנים אלו כיון שהיה כמו חמישים מינו“טים בקיץ, וכדי שלא יהיו שבתות קטנים וגדולים, קבעו כן לכל שבוע.
[fn:16] רב משה עצמו הדליק  כעשר מינו“טים אחר שקיעה, אבל אמר לבני אדם להדליק בצאת הכוכבים.
[fn:17] דימה ר‛ את זה למש"א בעל התניא ששקיעה הוא קודם לילה ארבע מינו“טים מפני שיש מקום אחד בא“י ששם שוקע חמה אז.
[fn:18] אגב, הזכיר ר‛ שאם זמן מעריב שאדם נוהג וזמן הדלקה סותרים, כ‛ משנ“ב שידליק כמו רבע שנה מוקדם, שהוא תחלת בין השמשות.
