** גמ' תוס
דורש
מ"ונתן" שאדם מגרש כשנותן גט בחצר אשתו.
’ מבאר שהוא כופו"כ. כיון שאומ' ש"ושלחה מביתו" הוא כלל שני, רואים שסובר שאומ' מה עושה, ולא הדין שיוצא.
** גמ' רש"י
מק'
איך קונה אשה גט שנתן בחצרה; מה שקנה אשה קנה בעלה.
מפרש שמק' למה נחשב רשותה. היה אפשר לפרש שמק' איך גט נעשה שלה; לכאורה, יש לדחות שאשה קונה מתנה שניתן לה. מוכרח כן ממה שלא מק' כן על גט שבא לידה.
** גמ'
אומ' שאילו כתיב קנין חצר גבי גט, לא היינו לומדים שיש קנין חצר בגנב, כיון שגט חל בלי דעת האשה. באר’ שלש מהלכים בזה:
1. כיון שמצאנו שתורה נתן כוח לבעל בגט, שיכול לתת אותו בלי דעתה, אולי יכול לתת אף לחצר. א"כ, ק' למה לא אמר גמ' לאידך גיסא שאילו היה כ’ רק בגזל, הו"א שהוא מפני שיש באותו חלות דעת קונה. רש"י לא אומ' פירוש זה, שלא מזכיר כוחו, אלא שקני.[fn:1]
2. אז, נראה שאומ' שכמו שלא צריכים דעת קונה (רצה לומר, שהוא קנין שאינו צ' כ"כ), אולי גם לא צריכים מעשה של קונה כ"כ.
3. רח"ע (סימן ל) מביא נתיבות שמק' שלומדים קידושין בשטר מגט בשטר, וקידושין הוא מדעתו. אז, נלמד מקידושין. מת’, לאמורא שגדרי שניהם שווים, שכוונת גמ' הוא להוכיח שלא קונה אשה גט, ונתינת הגט עושה גירושין. בגניבה, שצ' קנין, אין ללמוד שחצר מהני, שרק רואים שנחשב נתינה, ולא קנין. אף ששטר קידושין נלמד מגט, צ' שאשה תקנה אותו. כיון שלא ידוע דין זה בקידושין, אין ללמוד ממנו. העיר’ שכיון שנלמד קידושי שטר מקידושי גט, מחודש לומר שמה שעושה לגרום החלות חלוקה. התחלנו לדון בחידוש זה.
המקור לחידוש זה הוא חילוק בכתיבה על איסורי הנאה, שבגט כשט כשר ובקידושין פסול (לרוב ראשונים, המובאים ברמ”א). זה נובע ממה שאין הקנאה באיסורי הנאה; אז קידושין, שצ' הקנאה, פסול, וגט, שרק צ' נתינה, כשר. רש"י, שלא באר כ"ז, ואף אמר לשון "קני לה,” לא מש' כן.
** קצות קה"י ראשונים
אם אדם נותן שטר בחצר אשה, מגורשת מדין גוב"א.
דן אם זה אף בשטר מכירה, ומסיק שלא יהני, שרק בגט, שלא צריכים יותר מנתינה (שחל בע”כ), מהני, אבל במכירה, שצ' קנין (כיון שכ’, “ואקח את ספר המקנה.”), לא מהני. כ’ שקדושין כגט, ולא צ’ קנין, אבל באבנ"מ חזר בו.[fn:2]
כ’ שחול’
אם צ"ל קנין שטר מכירה; חל’ רבי לומר שאין שום ראשון מוכרח.
** רש"י חת"ם
יל"ד למה קידושין צ' דעתה וגרושין לא צ'. בקדושין, האיש הוא המקדש, ואף על פי כן, צ' דעתה.
פ' שהוא מפני שהיא מקנה; במק"א פ' שהוא מפני מש'ות "והיתה.” בגט, אין אלו, שאינה מקנה, ואין "והיתה.”
הוסיף שנל’ מאיסור לשלח אשה שאנס. זה רק אם לא רוצה להישלח, וצ"ל שחל אם לא רוצה. ק' ל"ל מקישים גרושין לקדושין.
לכאורה, כלל של גוב"א אומ' שחלות יכול לחול בשעת סיבתו, ולא אחריו. עפ"ז, באר’ חי’ של הקצות; חלות קנין רק חל אחר סיבתו. עדיין, גוב"א רק מבאר איך יכול להיות חל. לא מבאר למה חל, שלא מבאר למה אומ' שהוא ביד עבד, ואז חל, ולא שאינו ביד עבד, ואז לא חל. כאן, דורשים אותו מקרא. אולי, אז, אינו כ"כ ק' למה יחול, שגזה"כ הוא. גמ’ רק צ’ לבאר איך יכול לחול. (הוסיף ר’ שכשיכול להיות חל, ויכול להיות שלא חל, ושניהם בגלגל החוזר, יותר מסתבר שלא יחול. באר’ שמעשה קנין (כמו כסף, שהוא נתינת דבר בחלוף דבר, ומשיכה, שמכנס לשליטתו) עושה בעצם סיבה לחלות, והוא דבר מסתבר לעשות חלות. כן הוא בשטר, שהשטר מורה שהוא שלו, וזה סיבה שיהיה שלו; כן הוא בגט. אם נותן שטר מקנה בקרקע שלו כדי להק’ לאחר, לא נראה כן, שאין הקרקע ביד מקבל. אז, בוודאי אינו מעש"ק. הקרא ילמד שא"צ הוכחה זה לחלות גט, אלא נתינה מגלה רצונו, שנותן אותו במקום שאם חל, עושה סיבה לגט. כיון שרב קנ’ אינם כן, צ’ גזה"כ.
** ראשונים רש"י רי"ד
אומ’ כלל זה בגנב שמקדיש, שהקדש שינוי כיון שחל. ק’ מה מקור שם. (גם ק’ ל"ל אמר קצות שבשטר מכירה אין קרא.) באר’ שיש לגנב שליטה, ולכן יש סיבה עם מניעה להקדש. אז, מה שקורה ממילא הוא חלותו (שמניעה לא יחול, שהוא סיבה לעצמו). כן אפשר לומר בגט, שאולי יש סיבה לחלות עם מניעה. בביאור קושיית גמ', נ’ מ
שעדיין לא יצא מרשות בעל. מש' שיש סיבה, אלא שנמנע. א"כ, י"ל שבכ"א מונע המעכב, שיכול לחול אם חל, וא"צ קרא לחדש סיבה. בביאור למה א"א להיות של בעל, יש כ’ שאז אינו כריתות. א"כ, הוא רק בגט. י"א שא"א להק׳ מה שהוא ברשותו. א"כ, הוא בכל קניין.
לא מש' כרש"י, שכתב, “שכל נכסי אשה קנויים… מה כוח יש לאשה….” מש' שמק' שאין סיבה.
** רמב"ם רש"י וראב"ד
כ’ שבעל, ולא משמש, קונה בק"ח.
חול', ופרש"י שכיון שהוא משמש נחשב בעל החצר. לכאורה, ע"ז ייתלה מי קונה בק"ח בנ"מלוג. אז, יש סתירה ברש"י.
** אחרונים קצות
לרמב"ם גמ’ שלנו ק'. י"ל כמש'ות רש"י.[fn:3]
מק’ על רמב"ם שיש משניות שאומ’ שיכול להק’ בשכירות מקום. מת’ שכשאדם משכיר, לא מכוון לתת השתמשות ק"ח (לא כ"כ מסתבר לומר שלא כוון לתת אותו אלא שאין סתם שכירות כן)[fn:4]. א"כ, באשה, שלא יכולה לשאר לעצמה תשמיש, לא קונה בחצר.
הוסיף שרק באותו ציור אומ' שלא כוון משכיר לתת לשוכר אותו תשמיש. לשון רמב"ם ("אע"פ שהשכירם לאחרים”) לא מש' כן.
** קצות רש"י ריטב"א רש"י רמב"ם אחרונים
לעיל, הבאנו
שכ’ שאין גט צ' קנין.
מש' כן, ו
מש' כן אף בשט"מ. ק’ מגמ’ שאמר שאם מעכב הבעל הנייר לעצמו, לא מגורשת. שם,
באר שלא מגרש כיון שלא נתן כולו.[fn:5]
כ’ שאינו כריתות (גט צ’ להורות על כריתות שלהם; אם יכול הבעל לקחת אותו, לא מורה כן). (
מעירים שלכאורה שני הפשטים אמיתיים.)
** ר"ש
גם קשה איך כתיבה על א"ה מהני. י"ל שכיון שנחית בעל שלא לקחת אותו, נחשב נתינה.
כ’ שאולי א"ה נקנים, שתורה מקנה גט, שהרי נותן בע"כ. (אין לומר שאין א"ה ניתן לקנינים, שהורש.) העיר’ שזה מניח שיש גזה"כ שחל, ולא שאין מקור לדעת. גם הק’ ר’ מסברה, שלכאו’ בעל גירש בע"כ, ולא ה’, והתורה גילה שיכול להק׳ הגט לה בע”כ.
** ר"ש
בא
שבעלות נותן יכולת לראיה לאותו חלות. אז, יש לאשה זכות לגט לראיה. זכות זה כולל הנייר. יש זכות למוכר שלא לתת (ולכן, כשאומר שלא יתן לה הנייר, לא חל), אבל כאן, לא מגלה שלא רוצה לתת גט.
לרמב"ם, מובן מה שאז חל; כיון שאין יכול לקחת אותו, חסרון כריתות לא מונע החלות. לרש"י, י"ל שמה שנתינה אינו לחלוטים רק מונע החלות.
** גמ רש"י ירושלמי תוס’
דורש
' מ"ונתן בידה" שקונה בחצר. ע’ ב
.
מבאר שדורש ממש"א ש"פ. ע’ ב
.
** אחרונים רש"י קצות מהרי"ט רש"י תוס שיט"מ קצות
דנים
אם קנין חצר דומה לידה, ששניהם הם רשויות שלה. לתוס’, שווים, שכולם נלמדים מחד קרא שאומר שצ’ כעין הפרט.
בב"מ כ’ שרואים ש"יד" לאו דווקא, ור"ל רשות. מש' שהם דין אחד.
כ’ שהם חלוקים. במק"א מביא
שכ’ שיד קונה שלא מדעתו (בקו"ח מחצר). קצות תולה אותו במח’ ראשונים:
כ’ שיד קונה רק אם הגביה שלש טפחים.
’ מק' למה צ' זה כיון שהוא כבר על גופו ממש. נמצא שחול' אם היותו בידו קונה או שצ' הגבהה.
כ’ שאף גט צ' הגבהה. מביא קצות צד שבגט אף לרש"י לא נצטרך הגבהה. לכאורה, לשיטה, אי אפשר לומר שיד וחצירה הם מצד שהם רשותה, שיד צ' הגבהה.[fn:6][fn:7]
במק"א כ’ שקנין חצר הוא למשמש, שזה העושה שהוא ברשותו ובשליטתו.[fn:8] ק', אז, למה מק’ גמ, “ידה גופא…,” שיש לו תשמישים. כ’ שא"צ תשמישים, שכ’,"נתן בידה.” נמצא שהוא חלוק מחצר.
** תוד"ה רע"א רי" קצות
ע'
ידה. ת’
שיכולה לשמש לעצמה. כמוכ"כ
(שא"א לבעל לכפותה למה שרוצה)[fn:9]. באר’ שאולי ת’ זה מהני רק לרי"ד, ולא לרש"י, שבא לומר שיש לה כוח, ולא שאין לו כוח.
כ’ שמשמש קנה כיון שקניין תלוי בשימוש. מתוס’ (“כאילו קני…") לא מש' כן. ויל"ד מהו פרות.
** רע"א תוס רע"א
מביא
’ בכתובות שמבאר למה יכולה אשה לבטל זכות מעש"י, ולא פרות. כ’ שיש לו זכות בחצר להיות לו פרות, אבל לא קונה ידי אשה (כיון שהיא בע"ח). אולי כן אומ' כאן. חסר, שהיה לו לבאר שא"א לו לזכות במעש"י. מש' שאומ' שאין זכות בידיים כיון שהוא מעלמא.
באר שאין מעש"י באים מידיים.
** רשב"א
בת’ שני של תוס’,
כ’ שכאילו אמרה שרוצה לסלק א"ע. ק’ בגט בע"כ. גם כ’ שבכ"ז יכולתה מכחיש כוח בעל.
מה שהתירו לשכ"מ לגרש, ולא למוקצה, הוא מפני שמוקצה היה כללי, ולא רק לגירושין.
** תוס רשב"א
אומ'
’ שהתירו כדי שלא תפול קמי יבם.
מוסיף שהוא שלא תטרוף דעתו.
** ראשונים יש
מז’ שגם אסור להק׳ בשבת. ק’, שהוא איסור כללי.
שכ’ שאין הקנאה כיון שרק שאל (חול’ ראשונים בזה)..
** ראשונים רי"ד גמ
דנים ל"ל קנו בקנין סודר. ת’ שיותר דומה למשו"מ. אז, התירו היותר קל. (כ’
שבסודר אסור להק׳ בשבת. מש' שהקנאה זה אין בו שום איסור. צ"ע, ש
' עירובין מש' שאסור להק׳ בשבת. אולי רק רצה לומר שאין איסור להק׳ בשאלה. אז, צ"ל שסובר שיכול לקנות בק"ס לשאלה. דנים בזה.
** רשב"ם יש יש מרדכי ב"י ראשונים
כ’ שלא היה הגט מוקצה, אלא היה רשות איסור בין הגט לו.
שכ’ שהותר איסור מוקצה בשכ"מ.
שכ’ שאין מוקצה, כיון שיכול לצור בו.
כ’ שבזמנינו, שאין איסור ללמוד מכתב, אינו מוקצה, שיכולים ללמוד הלכות גט ממנו. מק’
שבזמן רבא, אחר רבי, כבר התירו לכ’[fn:10] חול’
אם היה מותר ללמוד מכתב אחר ימי רבי (תלוי בשני ג’ באגרת רש"ג). גם מחודש שזה בכלל "דברים…" הוא שאינו  הל’ הכתובה, סמל הנכ’.
** רש"י ראשונים גמ רש"י
כ’ שקנתה גט באגב. (מק’
למה צ”ל צבורים.) נמצא שסבר שאף בלי נתינה, שכאן אין היות החפץ בחצר צ’ לקנין, מתג'. יש חול’.
’ כ’ שמתג' כשקנתה חצר שיש בו שטר.
שם כ’ שהוא בקניין חצר. ק"ק ל"ל כ’ שהוא קנין אגב.
** תוס רע"א תוס’ גמ תוס
’ כ’ שאינו כ"טלי גיטך,” שבא מרשות בעל לרשותה. מש' שיש ק"ח. יל"ד, שאולי אומ' שמקנה לה, ומבטל אותה לקרקע (ולא רק קונה).
מדייק מ
אחר שאין קנינים מהנים בלי נתינה:
’ כ’ שיכול לגרש בנתינת עציץ נקוב. כ’
’ שא"א להק׳ לה עציץ בלי מביטול יניקת עציץ, שבמחובר, הוא קרקע, ואין קניני מטלטלים קונים בו, ואז א"א לגרשה. מש' שא"א לגרש בשטר על אותו קרקע. מבואר שאי היה לו דיני מטלטלים, היה יכול לגרשה ע"י הגבהה ומשיכה. נמצא שאף שאין קניני קרקע מהני, קניני אחיזה יהנו.
** ראשונים קצות
יל"ד אם ראשונים שחול’ על רש"י כיון שהוא כ"טלי גטך" יודו לזה (ששלט עליו, אבל אין לו שליטת החפץ) יל"ד אם לתוס’ חזקה היה מהני, אילו לא היה שאינו קנין אחיזה. אולי שם לא משתתף הבעל. כ’ תוס’ שיש קנין יד (בלי הגבהה ומשיכה). ק' ל"ל מז’ קנין זה כאן. מצאנו, אז, רש"י שאומ' שקנין מצד הבעל מהני, תוס’ שאומ' שקנין של אחיזה מהני, וראשונים שאולי סוברים שצ' (גם) נתינה לרשות.
מק’
למה צ"ל צבורים.
ת’ שבלי"ז לא היה כריתות, שהוא עדיין ברשותו.
** חש"ש יש
קשה למה רש"י לא כ’ שקונה בחצר.
כ’ שלרש"י צ’ קניני אגב וחצר. “ונתן בידה" אומ' שצ' נתינה לחצר, וגם אומ' שצ' קנין (וחצר לא יהני, כש”ך[fn:11]).[fn:12] המקור לזה יהיה ש"יד" שאומ' תורה יש בו נתינה וקנין. לעיל, בכעי"ז, גמ’ דן בחצר, ואז מוכח שחל בחצר.
שכ’ ששם קונה באגב, אלא שצ"ל ראוי לקנ"ח כמו שצ"ל צבורין. ק' לקצות, שעדיין יהיה כריתות. גם ק’ שאין קונים אגב עבד. אפשר שק"ח לא יהני לרש"י כיון שמשכיר את החצר. ק', שרש"י סובר ששוכר קונה. אולי לא קונה ממשכיר, שדומה לחצר השותפים. גם י"ל שאין חצר כאן, שבקנין חזקה, אינו מסייע (משא"כ שם, שנותן שטר).
** ר"ח נתיבות
יש שכ’ שרש"י סובר שרק צ’ קנין. א"כ, צ"ל שכל קנין חל בע"כ. לחש”ש, שצ' אף קנין, כל קנין יחול בע"כ.
כ’ שלרש"י, צ’ נתינה או קנין.[fn:13] רק נתינה חל בע"כ (ואף תקנה גט, כר"ש). אביי סובר (לעיל) שא"א לגרש באופן שלא יחול בע"כ. א"כ, יחלוק ע"ז.
כ’ כר”ח, אבל סברה שלו חלוק. רח"א שאין קנין בלי דעתה. נתיבות אומ' שבלי דעת, אין מעש"ק מעש"ק.[fn:14] אז, אולי אינו בכל מעש"ק. אולי, אז, יהני בקנין אגב, כיון שהמקנה הוא המאגב.
מה שאין בעיה שם של "טלי גטך" כיון שלא חל מיד (כש"ך) הוא אולי מפני שחול' על ריטב"א או מפני שכיון שנתן אותו לחצרה, אינו כ"טלי.”
נמצא שלרש"י, יכול להיות שצ' קנין, שצ' קנין ונתינה, או שצ' קנין או נתינה. לצד שלישי, מה שחצר אי אפשר לעשות קנין הוא כשני צדדי ש"ך. גמ’ לעיל ק', וצ"ל שהוא אגב (אף שהוא עבד). לצד שלישי, מה שחצר אי אפשר בנתינה) הוא שלא נתינת חצר נתינה[fn:15]. לא מהני גבי קנין כמש”כ. גם י"ל שהוא טל"ג, שחצר מכחה[fn:16], ולא כאגב. לצד ראשון, י"ל שלא מקנה החצר, ואז אין הקנין גט מכוחו. זה גם כן יבאר גמ' לעיל.
ראשונים החול' סוברים או שצ' הקנאה שיש בו נתינה או נתינה. הקנאת מקום הגט של כאן נחשב נתינה.[fn:17] תוס’ כ’ שאינו כט"ג כיון שבא מרשותו לרשותה. מש' נגד ראשונים.[fn:18] קה"י מגיה תוס’ לומר כמה שכתבנו. מק’ אחרונים לתוס’ שיהיה דומה ללקחה ממנו, ולא יהיה נתינה. אבנ"מ כ’ שחצר הוא יד אשה וחצר איש הוא שליחות. אז, חצר שנתנו הוא כשליח שנתן. העיר שלא חזרה שליחות אצל בעל.[fn:19] ע"ש בת’. ר"ש מק’ שאין חצר שליח לתת גט, אלא קונה לו מה שבתוכו. גמ’ לקמן מק’ על "מצאו לאחריו" שהוא טל"ג. אומ' ששלפתו ממנו, ומק’ שאינו "ונתן בידה.” מש' שיש שני בעיות, שצ' לתת לה גט, וצ' לבוא ממנו. אולי תוס’ דן רק בשני, ואמר שהתחיל ברשותו.
כ’ ש"ך שכשאדם מקנה חצר כדי לקנות מטלטלים שבתוכו בקני"ח, צ"ל קנין החצר קודם ומטלטלים אחריו. שט"מ[fn:20] כ’ שא"א לקנות מטלטלים שהיו בחצר קודם שהיה חצר שלו. קצות כ’ שש"ך רצה לומר כשט"מ, והוא שצ' לבוא מט’ לחצר אחר שקנה אותו. מק’ מגמ’ של "מקומו מושכר" כשכבר היה שם החפץ[fn:21]. רע"א באר ש"ך שצ’ שקנין חצר יחול קודם.[fn:22] ריטב"א ורי"ד כ’ כן.[fn:23] מק’ על ש"ך איך אומ' גטו וחצירו כאחד. י"ל שא"צ גט, ויכול לבוא לחצר מיד, ורק לא נקנה.[fn:24]
דן רמב"ן[fn:25] אם עכו"ם הקנוי לישראל (שאין לו דיני עבד כנעני) קונה בשטר עי"א, או לא, כיון שרק מהני כיון שנלמד מאשה, ואין עכו”ם נלמד[fn:26]. ק"ק איך תתגרש אשה בחצרה למד"א שאין קנין שטר לעבד.[fn:27][fn:28] יש לדחות שאולי א"צ' מקור לזה, שחל מסברה (שיש סיבה כרש"י). לא חל בעבד כיון ששם אין סיבה.
גמ’ אומ' שני לשונות- “בצד ביתה" ו"בתוך ביתה.” רשב"א כ’ שלשון שני דווקא. ק' מגמ’ שדן בעבד וכלי שמקבל גט מתורת חצר. יש שכ’ שהלשון הוא לאו דווקא, ורק צ' להיות נוגע, או הכי קרוב שהוא רגיל להיות.[fn:29]  יש כ’ שלשון ראשון דווקא. רמב"ם מש' שבצד אומ' בתוך ד"א, שמצאנו שנחשב רשותו. ריטב"א כ’ שרק צ' להיות יכול לשמר.
גמ' עירובין כ’ בחצר קטנה הפתוחה לגדולה, לפעמים קטנה פתחה של גדולה, ולפעמים אינו פתחה של גדולה.[fn:30] נמצא לפרש"י בגמ' שם שאם אשה בגדולה, וגט בקטנה, מתג', כיון שלה הגט בפתחה[fn:31]. מש' כרשב"א. אפשר לדחות שהוא בציור שאינה בתוד"א, אבל סתימות גמ’ לא מש' כן. לכאורה, ראיה זה גם יהיה ראיה נגד צד שאומ' שרק צ' להיות נוגע בחצרה. ואולי סתם ציור אינו כן. תוס’ מביא פשט אחר. לזה, אין ראיה.
אם צ"ל בתוך ד"א או יותר קרוב, צ’ זה כדי שתהיה סמוך, כמו יד, שהוא יד שלה. אם צ"ל קרוב לשמר, הענין יהיה שרק זה נקרא היות לה גט. יותר קל להבין צד זה, שאומ' שאז יכול להיות שסיבת קנינו הוא שהוא שומרו, אבל לא שסמוך יהיה שייך.
לכאורה, מגמ' ב"מ יוצא שחצר יד ושליח. בגט, א"א להיות שליח, שהוא חוב, ואז הוא יד. במתנה, יכו"ל שליח. כן פסקים רב ראשונים שם. ק' מהו המקור שחצר יכו"ל יד ושליח. רש"י שם סובר שאם הוא שליח, לא צ' קרא (אלא נלמד מקרא של שליח). ראשונים מעוריים שצ"ל בר דעת להיות שליח. צ"ל שאינו ממש כשליח, אלא שכיון שתורה אומ' שמעשה שליח כמעשה שולח, נדע דין זה בחצר.[fn:32] רש"י כ’ שבשליח צ’ קרא לגלות שיש שליח לעבירה. ק"ק, שאז א"צ צריכותא של גמ’ שלנו. תוס’ חול’ על רש"י שם. רש"י מבאר שאם דורשים מקרא של יד, דורשים להיות חצר משום יד, שאילו היה שליחות, לא היה צ' קרא. לתוס’, רואים אותו ממה שחל בע"כ. לתוס’, ק', אז, מהו המקור ששניהם יהיו. העיר’ עוד שלשון "לא גרע משליחות" מעניין. ע' ברש"י שכ’ לשון מוזר שמש' שנלמד מקרא. ע' במהרש"א שכ’ שחלק מן הרשי הוא תוס’. יש שכ’ שלתוס’ לומ’ שליחות מקרא של גנבה. ק’ מהי"ת שאינו יד. ע’ ברש"י שכ’ שמלמד שאין שלל"ע. ק’ מהי"ת שאינו מלמד שהוא יד.
רשב"א דן בציורים שיכולים לומר שליחות. ע' בר"ן. ריטבא ח’ וכ’ שלא יכו"ל שליחות בגט מל"פ. רשב"א כ’ שאולי יהני אם נתן גט שלא בפניה, ואמרה, “תקני לי חצירי.”[fn:33] אם אומ'ת כן קודם, מסופק אם מהני (כמו עשיית שליח קבלה קודם קבלה).[fn:34] לכאורה, הספק הוא אם מינוי חצר הוא כמינוי שליח, וצ' ביטול, ולא די לשנות דעתה. צ' להגדיר שינויים שבין שליחות זה לשאר שליחויות. העיר’ שכ’ שלא מהני כשאומ'ת לפני כן זמן גדול שלא מהני, שאינו זכים, כיון שאולי חזרה. אז, ק' למה בזה אומ' לשונות שמש' שממנה שליח[fn:35]; יכו"ל זכין. בציור שאומ'ת כן, ואחר כך בא לרשותה, פשוט למה צ' אותו דיבור ואותו מינוי, ששם יש לחוש שמא חזרה אילו לא היה מינוי. רן כ’ שגט כשר רק אם בעל אומ', “הא גטך" אחר אמירת "תקני לי חצרי.” אז, ציור שאמרה כן אחר נתינה לחצר לא יהני אא”כ אומ' אחריו “הא גטך.” מדמה אותו ל"נתן לה לפקדון.” לכאורה, היה אפשר לומר שאצ"ל אחריו ממש, אלא קצת לפני אמירתה, ותוכ"ד. ר"ן מש' שזה לא די.
עדיין מודים שבשעת נתינת גט לחצר, אינו שליח, ועדיין אינו כטל"ג. בגט בתורת פקדון, למעשה נתן גט לידה. כאן, נתינה לחצירה אינו נתינה, שאינו ידה ואינו חצירה. א"כ, יהיה כגל"ג. גם ק', שלכאורה, אינו חצרה, שלא נאמר גו"י בכ"א אז, שלא חל גט אז.( זה תלוי במחלקת רש"י ורי"ד.)
היה לנו על הכל ארבע תירוצים:
תו"ג כ’ שכיון שצ’ גו"י לקנות, זה נח’ נתינה. גירושין נעשה מבעל, וזה הנותן יד לגירושין.[fn:36] הערנו על זה ארבע הערות:
או"ג מק’ מדמיון לפקדון (ששם, אין הנתינה בשעת חלות גט).
מק’ ר"ש איך גרושין הנתינה, שצ’ נתינה מוק’.[fn:37]
גם מק’ שנתינה הוא שנותן דבר מממנו לה. אם הנתינה גירושין, אין דבר נתון לה, שרק מגרש אותה, אבל לא נותן לה בעלותו.
לתו"ג, זה חל רק בחצר שיש לו פירות, אף שלשון סתם שאומ’ מש' שהוא בכל.
או"ג כ’ שנתינה הוא כשנותן לחצירה, אף שאל אמרה אז שרצה, שאף שאינו יד או חצרה, “בנוגע שנחשב נתינה לה, נחשב שלוחה.” כ’ שאולי זה רק אם החצר היא ממש שלה, ולא כשיש לו פירות.[fn:38][fn:39] לקמן, חול’ בציורים שנותנת גט, ואעפ"כ, מתג' לאח"כ, כמו "כנסי שט"ח.”
י"ל כעין או"ג שיד שאינה בצדה נח’ נתינה. יש שכ’ שצ"ל בצדה הוא כדי שהחפץ צ"ל הקרוב לאשה. אולי, אז, אין לומר שהוא יד, אלא שיש בעיה בקנינו.[fn:40] הבאנו ראיה למושג זה:  גמ’ דן בעבד לחצר. מק’ שהוא חצר מהלך, ומוקים אותו בכפות. ברמב"ם מבאור שאם נתן לו כשלא היה כפות, חל אם מגיע גט ליד אשה[fn:41]. רשב"א מק’ שהוא טל"ג. ר"ח כ’ שתלוי בחסרון- אם אין גט בידה (שאז אינו נתינה) או דבר שנצרך לידה אינו שם[fn:42] (שאז הוא נתינה). מבאר שמח’ זה תלוי בחסרון חצר מהלכת. תוס’ מבאר שהבעיה הוא שלא דומה ליד. רש"י כ’ שלא קונה כיון שלא משתמר. רמב"ם יסבר כרש"י. באר"ח שתלוי באם הוא חסרון שנמצא גבי יד עצמו; אם נמצא, צ' לומר שאינו חסרון בעצם, ועדיין נחשב יד. אז, כאן, צ"ל שחצר נח’ יד, אלא יש בעיה. אז, במשנה בעח. גם רואים מזה חידוש שיכול הנתינה להיות קודם חלות הגט. רי"ד כ’ שבמשנה א"צ נתינה שני כיון שכבר היה נתינה לשם גרושין, שלא צ’ דעתה. רק צ"ל אחריו ש"הא גטך,” כיון שאינה יכולה לשומרה, או שאין אמירה זה ידוע. נמצא שיש נתינה קודם החלות. כ’ שאם נתן לפקדון, לא חל. לכאו’, זה רי"ד לשיטתו, שהנתינה הוא הנתינה הראשונה, ואז נתינה זה לפקדון לא מהני. ר"ן כ’ שאף אם נתינה ראשונה הוא לפקדון, חל; וזה ציור של משנה של "כנסי שטר חוב זה.” מחו’ לומר שנתינה שלא לשם גרושין נח’ נתינה. רמ"ה חול'.[fn:43] כ’ שהנתינה הוא כשאומ'. זה אומ' שהגט בידה מכוח נתינתו לה. אז, יש נתינה, ועכשיו הוא לשם גירושין. לשיטתו, רמ"ה כ’ שצ"ל שעדין בידה. רי"ד כ’ שישנה אינו נתינה כיון שאינה משמרתה. זה מבאר למה יכול להיות נתינה. א"כ, אף אם נופל מידה, חל.
על פי רמ"ה, י"ל עוד מהלך לבאר הרשב"א, והוא שיש נתינה ממשכת.
צ' לבאר מהו חלקת רי”ד ורמ”ה. לכאורה, ב"כנסי" חול' מהו החסרון (אם הנתינה הוא לשם גרושין). יל"ד אם חל’ בזה בישנה, או שחול’ מה נח’ נתינה. דנים אם יש לישנה חצר. רשב"א כ’ שאין חצר, שחצר מטעם יד, וכיון שאין יד, אין חצר. אם אין בעיה ביד, אלא שאינו שמור, ק', שהחצר שמור. יש שכ’ שכאילו אין בה דעת באותו שעה. אז, אין לה יד. זה יבאר את הרשב"א. אם נאמר כן, מובן שאין נתינה, וצ"ל כרמ"ה. גם י"ל שהוא רק גזירת הכתוב.
ר"ן מוסיף סברה שישנה עושה שאין חצרה משתמרת. לכאורה, כדי להיות שנחשב שאין לו חצר, צ' לומר שקנין חצר הוא רק מפני שליטתה על מה שהוא בחפץ. כאן, אין שליטה. לא מובן כ"כ, שהוא נשמר, ואז יש קצת שמירה. גם כ’ סברה שכיון שצ"ל בצד ביתה, לא מהני. מובן יותר אם אומ' שענין עומד בצד הוא יחס בין אשה לגט, שאומ' שצ' דרגא חשובה של יכולת לשמור.
רמ"ה כ’ שבציור של רשב"א לא יחול, שצ"ל בצד חצר בשעה שנותן לחצר, ובשעה שאומ' דיבורו. נסתפק אם צ"ל שם כל הזמן. זה אומ' שצ’ שתהא בצדה בתחלת נתינה, בפעולת נתינה. כ’ שהוא כן אף בגטה וחצרה בכ"א. בא להוסיף אף אם אין לה כלום בחצר, ונותן לה שטר מתנה. אולי נתינת שטר בחצר נח’ פעולת נתינה. נמצא שסובר שנתינה הוא נתינת גט, ולא הק’ מקום. ק’ מה לנו בעמידה בצד, שאין החצר שלה. צ"ל שאין עמידה בצדה ליחס לחצר אלא ליחס לחפץ. עדיין מחודש הוא.
רשב"א מק’ שאף אם הוא מטעם יד, אצ"ל עומדת בצדה, שלא גרע משליחות. מניח ר"א מודה שהוא שליח רק אם מגלה דעת שרוצה. לא קל להבין ת’. רע"א כ’ שאיה"נ, חול' רק בביאור המשנה. כ’ שזה ת’ טוב עכ"כ שק’ ל"ל כ"כ רשב"א. ר’ שזה דוחק. אבנ"מ כ’ שלצד שהוא שליחות, הוא בע"כ.
* Footnotes
[fn:1] כוונת רבי הוא לדייק ממה שרש"י לא אמר, “הלכך עושה אותו אף בנתינת חצר,” אלא "הלכך בחצר קני.,
[fn:2] העיר’ שאינו פשוט בראשונים ששטר מקנה צ' קנין שטר.
[fn:3] באר’ שיותר קל לומר כן אם הוא בעיא רק בקנין גיטין. אם נאמר שהוא מפני סיבה שניה, שדומה לחצר שותפים, יל"ד, שכאן לא יכול כ"א לקנות בקני"ח.
[fn:4] אמר’ שמחודש שק"ח הוא אחד מזכויותיו בחצר, אלא שקונה מחמת שהחצר שלו, או שיש לו זכויות עליו. אולי לא מכוונים לומר שהוא זכות שיש לבעל, אלא שיש חלק מקנין משתמש שייר לעשות דין זה.
[fn:5] מוסיף ש"נמצא אותיות פורחות באויר.” לכאורה, זה בא לבאר למה אין נתינת האותיות כשר, והוא שאין זה נחשב (נתינת) אותיות.
[fn:6] מן הסברה, ק' למה לא נאמר כתוס’. אולי קונה חצר, אבל לא ידו. מוזר לומר כן, שאינו בעל כיון שהוא יותר מזה.
[fn:7] גם צ' לבאר את זה לפי צד ש"חצר לפי יד איתרבאי.”
[fn:8] זה מש' כרי"ד.
[fn:9] שא"א לבעל לכפותה לכל תשמיש שרוצה.
[fn:10] שהיה אחר רבי
[fn:11] אומ' את זה לשני הצדדים (יש כזה ויש כזה). הבעיה לצד שני יהיה שהוא טלי גטך. מחודש שזה עושה שהוא כטל"ג.
[fn:12] זה מחודש; בלי זה, היה נ’ שרק אומ' אחד מהם- או שצ' אחד מיוחד, או שצ' רק אחד (כ”א ר”ח. הוסיף ר’ שאולי כדי לגרש בע”כ צ’ נתינה.). עכשיו אומ' שצ' שניהם. (יש להעיר שטלי גטך בוודאי לא מהני, ואז צ' שום מין נתינה. יש לדחות שאומ' שצ' שיהיה העושה הקנין.) העיר’ שהיה הפשטות לומר שרק מש' אחד מהם, שרק רואים אחד, לכאורה, בתוך הקרא (אמר’ א"ז על ר"ח, אבל נראה שהוא כן אף לצד שאומ’ עכשיו).
[fn:13] אמר’ שאין זה כ"כ ק' לומר כבית באיר, שלכאורה, היה נראה לומר שכל שנקרא נתינה יחול, ולמה צ' שני הנתינות.
[fn:14] רצה לומר, לר"ח יש מין קנין, וצ' דעת כדי לצרף עם מעש"ק. לנתיבות, צ' דעת כדי לעשות המעש"ק. גם אמר ר’ שלנתיבות, נתינה קונה כיון שהוא מעש"ק שא"צ דעת להיות מעשה קנין.
[fn:15] אבל, לעיל, נתן מקום הגט, ואז הוה נתינה. כאן, לא הקנה נתן מקום הגט, שהיא החזיקה. שוב באר’ שזה אף נחשב קנין, אולי.
[fn:16] אף שיש לו דעת, ה"ה כטל"ג.
[fn:17] דנים אחרונים בזה. ואיני יודע אם רבי אמר שהוא שנתן מרשות לרשות, או שנתן לה יכולת ליקח אותו.
[fn:18] שלא רק בא, אלא הוא נתן אותו מרשותו לרשותה.
[fn:19] שעדיין הוא שליח בשעת חלות שליחותו.
[fn:20] ב"מ
[fn:21] ר"ש מת’ ששט"מ הוא רק כשהוא שלא מדעתו.
[fn:22] אמר’ שאין זה ממשיך לזמן. אמר’ שר"ל שצ’ לכוון על איך יחול- שזה יחול ויגרום שזה יחול.
[fn:23] כ’ ריטב"א כן לבאר איך לומדים מ"עם ערי…" לקנין אגב, ולא אומ' שהוא קנין חצר.
[fn:24] אין בעיה מחמת שאין כריתות (וכדומה) כיון שאחר כך יקנה אותו בקנין חצר.
[fn:25] יבמות
[fn:26] יש ראשונים שכ’ שא"צ מקור.
[fn:27] נראה שכוונת רבי היה לומר שלומדים זה מרמב"ן שרואים שצ' מקור.
[fn:28] אז, אותו שיטה או לא סובר כמשנה או לא סובר כרבא. אמר’ שדחוק לומר שהוא רק כחכמים שסוברים שמגרש ע"י עצמו.
[fn:29] העיר’ שק"ק מהיכי תיתי, שאם צ' ליהות הכי קרוב, נאמר שבאלו, שאי אפשר להיות קרוב די עד שהוא בתוכו, לא קונה.
[fn:30] תלוי במאיזה פרספקטי"ב רואים את הציור.
[fn:31] שם כ’ רש"י "ואשה א"צ לקנות הגט.” ק' להבין מה עושה בזה, שלהפך, רוצים שצריכה לקנות גט, ואז רואים מפרספקטי”ב שלה. אז, יש משנים גירסה ברש"י. עדיין אולי לא צריכה לקנות גט, אלא רק צ’ נתינה. וע"ש.
[fn:32] רצה לומר, שמחדש שא"צ מעשה שלו ממש. אז, פשוט לגמ' שחצר יהני.
[fn:33] מש' שם שמכריע בציור זה, אבל רבינו ירוחם כ’ שמסופק בזה.
[fn:34] לכאורה, חושש שחוזרת.
[fn:35] “תקנה לי חצרי.”
[fn:36] העיר’ שק"ק שהיה לגמ’ הו"א שצ’ גו"י בכל ציור גט, וא"כ אין שום ציור של טל"ג. (אי"ז ק’, שיש ציור שיש בעיה, והוא אם מסלק א"ע.)
[fn:37] אמר’ במילים אחרים שחלות בב"א הוא מעשה נתינה למקום שאם חל, יחול. א"כ, אין גירושין סיבה לגירושין. גם זה א"א לרש"י שיש לה כבר יד.
[fn:38] להפך מן התו"ג.
[fn:39] העיר’ שכיון שאומ' שהוא שליח "לגבי…,” נוכל לומר שהיא שלה "לגבי….”
[fn:40] אמר’ שאין הפשטות כן. גם אמר שכן נראה מראשונים שאומ' שהגדר של עומד בצדה הוא שיכול לשמור את החפץ.
[fn:41] יש מדחיקים בלשון רמב"ם, אבל לא משנה כ"כ.
[fn:42] באר’ שהענין הוא אם אפשר אותו פסול ביד ממש.
[fn:43] מדפיסי ריטב"א כ’ שריטב"א הוא רבינו קרסקס, וכתב יד אחר כתבו שהוא ריטב"א. אמר’ שאין זה כ"כ פשוט. מה שאין ריטב"א שלנו ממש ריטב"א כבר כ’ חת"ס, שפקפק בו. על כל פנים, ריטב"א כ’ יד מביא רמ"ה זה.
[fn:44] לא הבנתי איך זה תירץ קושיה ראשונה.
[fn:45] אולי יש סיבה לשניהם לקנות, ולשוכר יש יותר סיבה.
[fn:46] לכאורה, י"ל יותר פשוט שיש רק איסור אחד, ואז רצו שיעשו כן. ויל"ד, שאולי יש אף איסור קנין. ואם תאמר בין כך ובין כך יש איסור קנין גט. וזה תלוי באם צ' לקנות גט. ואף אם צ', עדיין בזה יש שני איסורי קנין. יל"ד אם זה שני איסורים.
[fn:47] לכאורה, החילוק הוא אם הוא כדי שלא תבוא רע לה, או כדי שלא יבוא רע לו. גם י"ל שהחילוק הוא אם הוא כדי שלא יבוא רע לה או כדי שלא ימות (ולא רוצים כן כיון שאז בא רע לו, אלא מפני שרע הוא לעולם כשבני אדם מתים.). אגב, יל"ד מה אם הוא רשע, שאז טוב הוא שימות. ואולי הוא לא פלוג.
[fn:48] נראה שיש עוד איסורים שי"ל:אולי כיון שרק צ' נתינה כאן, אין איסור הקנאה (שלא מקנה). ויל"ד, שצ' הקנאה לבסוף (כדי שלא יהיה חסרון בכריתות וכדומה). וע' לעיל בשיעור. ודע שכדיין יש איסור של קניין קרקע.אולי אין איסור קנין כאן כיון שהבעל יקנה את הפירות (ורק תקנה פירות מחמת גט, ולא מחמת נתינת קרקע). יל"ד אם הניח רבא בצד זה שבעל יקנה פירות. גם יל"ד אם נתינה כזה אסור בשבת. גם יל"ד כיון שעושה נתינה גמור, אף על קנין הגוף, אלא שאחר חלות הקנין, בא קנין פירות לבעל. ויל"ד. וכל זה שייך למה הם קנין פרות. וע' בשיח שי ובצדי צדדים.אולי כיון שחל בגיטו וידו באין כאחד, ואז אין כל סיבות החלות שם בשעה שעושה החלות, עד שעושה את החלות, אולי נחשב שני החלותות גרמא. א"כ, יש עוד סיבה למה נתיר גירושין, ואין צריכים לומר כמש"כ תוס’. ויל"ד אם אלו אסור או מותר בגרמא. עכ"פ, הוא, לכאורה, איסור יותר קל. צד זה גם כן מניח שרבא כבר ידע שגטו וידו בכ"א גורמים את החלות הזה. ע' בצדי צדדים בזה.
[fn:49] יל"ד למה:צ' לתת דבר כדי לקנות, כמו במכירה.אולי הוא קנין שבו יותר רגילים בני אדם, שמהני למטלטלים וקרקע.
[fn:50] גם י"ל שאומ' שרק סודר אסור כאן כיון שהוא שכיב מרע. וצ' לע' בלשונו.
[fn:51] הציור צ' ביאור. בין כך ובין כך, היא באה לגט (שבאה לחזק במקומה). צ' לומר, אז, שהוא אינו יכול לבוא לגט. לכאורה, אין זה כ"כ ק', שאולי אי אפשר לבוא כיון שהוא חלוש, שהרי הוא נוטה למות. ויש להעיר שהיה אפשר לומר שאף בלי איסור, אולי לא הקנה לה על ידי נתינה כיון שלא היה חזק לתת אותו בידיו (או להגביה אותו או לבוא לו). ויל"ד, שאולי יותר טרחא הוא לשאול לרבא מלהגביהה את הגט. ויל"ד. גם ק"ק ל"ל יעשה שליח, אז. באמת, זה ק' אף על מש"כ ראשונים אלו.
[fn:52] ק', שאף אחר כך היה איסור, כמו שמצאנו בר"י ור"ל בתמורה, וכן כל הגמ' שם מבואר כן. ויל"ד, שאולי דרשו כן ר"י ור"ל לא רק על מה שצ', אלא על הכל. ותו"ת.
[fn:53] נראה שהצד שזה חידוש הוא שאולי אין איסור כתיבה רק שרוצים שדברים יהיו נלמדים בעל פה, אלא שאין לתורה להיות בפאור"ם של "נכתב.” יל"ד למה זה לא יהיה נחשב נכתב:אין עיקר תכלית של מילים אלו (בדרך כלל, או כאן) להגיד אותו דין.כדי לדעת ממילים אלו, צ' לדעת שנכתב בכשרות. אז, אין מילים אלו מגידים את הדין כ"כ, ואינו נחשב שהתורה נכתב.
[fn:54] כל זה מניח שאי אפשר ללמוד מדברים הכתובים, ולא רק שאסור לכתוב אותם. רש"י (שנוגע מגילת סתרים) גם כן מש' כן. אולי שייך לדיון בגירסת גמ' האוסר, אם אומ' שלא לכותבם או שלא לאומ'ם בכתב (לצד ראשון, לכאורה, רק אומ' שלא לכותבם; לצד שני, יל"ד אם אומ' שלא לכתוב אותם (ולאומ' בכתב רצה לומר לאקספרי"ס אותם בכתב) או שלא לאומ' מתוך הכתב). ותחשב.
[fn:55] יל"ד למה צ"ל של אחיזה. אפשר שהוא שקניני אחיזה קונים כיון ששלט עליו, אף שאין לו שליטה. אז, אותו יחס של שולט (אף שאין בו רוב שליטות) הוא די לעשות שהיא ברשותה. גם י"ל שאז מה שהוא בידו (בשליטתו) יותר נצרך, שרק מפני זה היה יכול למשוך וכדומה (שבא מאותו מצב). ותחשב.
[fn:56] גם י"ל יותר פשוט שהוא כדי שיהיה נתינה ממנו, ולא כטלי גטך.
[fn:57] זה יכול לת’ אף לקצות.
[fn:58] ק' למה לא נאמר שאותם דיני חצר שאומ' שם הם נצרכים לנתינת חצר.
[fn:59] גם י"ל שכאן מיירי בבע"כ, ואז צ' קנינים מיוחדים.
[fn:60] וריטב"א יסבור שרק צ' נתינה.
[fn:61] לא הבנתי למה לא אומ' כן אף כאן.
[fn:62] מבארים שזה מפני שמה שעושה הקנין אינו היותו בחצר, אלא ביאתו לתוך חצר.
[fn:63] לכאורה, צד זה מוכיח שבאגב, אין קנין סיבה לקנין, אלא מעשה קנין סיבה לקנין.
[fn:64] נמצא, אז, שהניח רבי שלא היה אפשר לומר קנין גט וחצר כאחד אם הם זה אחר זה, אף בחד זמן. לא הבנתי מהו צד זה, ומהו הצד שאינו כזה, שלכאורה, פשוט שזה סיבה לזה.
[fn:65] קצת צ' ביאור, שהקצות הוא המק' כן, ולשיטתו (שא"צ קנין), אין לו להקשות. צ' לומר שסבר שנתינה כעין יד בזה.
[fn:66] לכאורה, היה אפשר לומר שלכן אומ' רש"י שכאן קנה בקנין אגב, שצ' להיות שהוא בחד זמן. אולי רש"י שלא רצה לומר שדי בנתינה הוא לשיטתו, שסבר שקנין אגב, שאין בו נתינה מהני. אז, מסתבר, אולי לומר שסבר שנתינה ממש לא מהני, שאין נתינה דווקא, שלא נצרך. גם יש להעיר שלא באר כמש"א רח"ע על ידי זה לעיל בביאור הפירכות. שוב העיר לי א.מ.ו. שאי אפשר לומר שלכן אומ' רש"י קנין אגב, שהרי בוודאי על משנה שלנו אומ' רבא שקונה בגטו וידו, אף ששם קונה בקנין חצר, כמו שמפורש בגמ'. ותחשב. עדיין י"ל שסבר כפשט הראשון שבש"ך. גם י"ל ששם רק ננותן בחצר, אבל לא מקנה בחצר. ותו"ת.
[fn:67] אולי על ידי זה יש ליישב לשון "תוך.”
[fn:68] באמת, יש, לכאורה, ראיה להפך.
[fn:69] לא הבנתי החילוק, ששניהם נלמדים מדמיון ליד. צ' לומר שר"ח רואה חילוק מן הסברה ביניהם.
[fn:70] אולי חול' אם יש מעלה להיותה בביתה (אם יש יד או לא). שו"ה שזה כמעט מש"א רע"א.
