** ראשונים רמב"ם גמרא רמב"ם
[fn:1]מבואר מכמה
שאין עוסק בתורה פטור ממצווה.
באישות פוסק שאם היה אדם טרוד בתורה, ולא נשא אשה, רשאי, שעוב"מ פטור ממצווה וכש"כ[fn:2] ת"ת[fn:3].
(שבת) אומר שבימי ר"ש, לומדי תורה הפסיקו לק"ש, ולא תפלה; ר"י מוסיף שבימיו (שאין תורתנו אומנתנו) חייבים אף בתפלה. כ"פ
. נמצא שעוסק בתורה חייב במצוות.
** גמרא ירושלמי רמב"ם[fn:4]
המקור שעוסק בת"ת חייב הוא
(מ"ק) שמק’ סתירה מפסוקים שמשמעים שמצוות שוות לתורה ושאינם שווים לתורה. מת’ ש"כאן במצווה שאפשר לעשותה ע"י אחרים, וכאן בשא"א לעשות עי"א.”
(ברכות, שבת) כ’ שר"ש היה פטור אף מק"ש, אבל לא משאר מצוות, ומק’ שיהיו לומ’ שלא ע”מ לעשות, ומת’ שק"ש חלוק משאר מצות כיון ש"הכא שינון והכא שינון.”). נמצא מירושלמי שחיובו הוא מפני שאם היה פטור, לימודו נפגם.
כ’ ש"אין מצווה שהיא שקולה כנגד ת"ת" ולכן תורה וקדם לכל מצוות, אא"כ אפשר לעשות עי"א.[fn:5]
** נצי"ב ור"א נצי"ב שו"ע הרב
כ’ לתרץ סתירה שברמב"ם שכיון שיכול לקיים לאח"ז, נחשב אפשר לקיים עי"א. מק’
שלשון רמב"ם לא משמע כן, שמשמע שנלמד מכלל רגיל של עב"מ.[fn:6]
כ’ שיש שני חיובי תורה- יש חיוב ללמוד בכל זמן, ועל זה אין העוסק פטור; ויש מצווה שיהיו דברי תורה מחודדים בפיך, ועל זה יש פטור עב"מ[fn:7]. דחוק בלשון הרמב"ם.
** באר’
שבאמת, מצוות ת"ת מחייב אדם ללמוד תמיד. כיון שצ"ל נעשה בכל זמן, רואים שצריך להיות חיי אדם מנודב לת"ת, שדבקים בה’ ע"י דבקות בתורתו. לעוסק בזה, יש פטור- אם בא מצווה שסותר לדבקות בתורה, פטור ממנה. אם כן, בנשואים, חושש שלא יוכל ללמוד אחר שיישא אשה, יש פטור מחמת עסקו בת"ת.[fn:8]
* Footnotes
[fn:1] אמר’ שלא יודע אם יאמר שיחה או שיעור; שמע מאדם גדול שאם לא יודעים בחורים אם הוא שיחה או שיעור, אותו ראש ישיבה צריך פרנסה אחרת.
[fn:2] ש"ת"ת כנגד כולם.”
[fn:3] אין להקשות מגמרא, שיש טעמים אחרים שיכולים להסביר אותו דין.
[fn:4] העיר’ שנכתבים בשני אותיות, אבל באמת הם באות אחת.
[fn:5] כס"מ מביא ירושלמי למקור לזה. ק"ק למה, שהוא גמרא מפורשת במ"ק.
[fn:6] לכאורה, הניח ששני הדינים- דין תורה כשא"א לקיים עי"א, ועב,מ- הם דינים חלוקים.
[fn:7] העיר ר’ שמואליביץ על פי זה שכל בחור שאינו יודע כבר על התורה כולה יכול לפטור את עצמו מכל מצווה שרוצה כדי ללמוד. אם אין קיום, נמצא שאי אפשר לכל בחור לברך על מצוות.
[fn:8] העיר’ שזה דומה לשוע הרב, אלא שהגדרתו קצת חלוק.
