אומרת תורה שבכור נוטל פי שנים- דהיי’, שיש לו שני חלקים. אומר שהוא ב”כל אשר ימצא לו,” שהוא דברים שכבר היא לאב.  חול’ תנאים מה נחשב “מצוי לו.” חול’ אם הושבח לאחר מיתה, בפני עצמם, אם “מצוי לו” או היה ראוי. העיר ר’ שמעניין מה שצ’ מקור לרבנן (ושואל זה ראשון), ואין אומרים שכן הוא פשטות הקרא. אלא נ’ שפשטות קרא כרבי. ק”ק למה.
(אמר ר’ באגב שקצת מוזר למה אין נותנים מתנות בזה”ז, ואף בחו”ל. יותר קשה אי מטבל (אלא שאין הל’ כן). כבר כ’ ראשונים שנהגו שלא לתנו בחו”ל, ומחלקת תנאים הוא.)
חל’ ראשונים אם “ילדה” קאי על מוחכר (ולא דן בשכר) (רבינו יונה) או רק על רועה בעפר (תוס’).  יש שכ’ כראשון כיון שיהא כמלווה לתוס’. גם לא נ’ לשון גמ’ כן, שלא מזכיר שכר.
לגירסתינו, מק’ גמ’ שראוי הוא. רמ”ה גו' “אמאי.” באר’ ברש”י שלא נחשב ראוי בבריי’ (לידת פרה) כיון שבא מחפצו (העיר’ שמעניין שנחשב ולד דבר אחר), אבל כאן לא בא כלום לאב. באר’ שמניח רש”י-והמקור לזה הוא ממה שמחדש נגדו במס’-שלא היה נשחט בחיי אב. לרמ”ה, ק’ גמ’ הוא שלא ניתן לאב כלל, ואין ירושה.
בכמה מקומות, דן גמ’ בזה במתנות שצריך להפריש, ואומר שהופרש חלק ספיסיפי’ להיות המעשר, ואז יכול לזכות בו אחר. לזה, נמצא שאינו מעשר עד שלא הופרש כי אם על ידי “כהורמו...” העיר’ שיש אומרים שיש בעיה ד”לכם,” ומסתמא זה לכו”ע. אז, דנים רק איך נדרהר ממון לוי. כאן, יודעין מה ינתן לכהנים . כ’ ר”י שאעפ”כ, יש דיון כאן. משמע שיש ענין הרמה, שעושה שנעשה מתנה. בביאור הרמה, באר’ שע”י הרמה, נעשה “בעלות כללי” לכהנים (ולא שותפות), ואף כהן שנולד אחר כן קונהו (החילוק דומה לחי’ קרבן צבור ושוטפין). (שמעתי שבאר’ שהרמה עושהו מתנות, ולא רק חלק מבהתה, ובטל נגדו). הביא ר’ תוס’ שמק’ שר’ הוא הסובר ש”לא כהורמו.” מתרץ שסובר כמותו בחד וחול' באידך. גם מחלק בין תו”מ ומתנות, שמתנות ניכרות. נמצא שאכתי צריך הרמה. לכאו’, מבואר כן ממה שיש שיטה שעושה טבל (ותוס’ כ’ שאסור מדין, אף שאין חיוב מיתה. דנים אם הוא מדאו’. גם דנים אם הוא איסור כטבל או חיוב ליתן קודם שיאכל.) נמצא מושג של הרמה במתנות, שאי יש כבר שם מתנות למתנות לא יטבלו בהתה, שאינם צ’ ליפרש ממנו. יש לדחות שרק מאסר כיון שצריך לותן לכהן.
צריך לבאר למה זוכה (או כאילו זוכה) מכירי כהונה. תוס’ באר שהוא מפני שמתנה מועטת הוא, ואסור לחזור בו, (שסמך דעת) והוה מוח'. (א”צ להיות מועטת, שלא חסר בנתינה, שצריך ליתנו (כ”כ ריטב”א).) אף שלא אמר שיתן, מניחין שיתן, והוה כאילו אמר. לכאו’, דין משנה יהא אף במתנה מועטת ממש. כ’ קצות (רעח-טו) בנשבע ליתן לאב ומת, שכיון שחייב, מתוס’ רואין שיש כפלום לבכור. לשיטתו הוא, שכ’ שנשבע ומת, חייב ליתן לבנים. (העיר’, ולא לק’, שיכול לשאל על שבועתו.) לא מבאר כאן קצות למה שייך ירושה על כעין זה, שבפשטות, אין חלות קנין, אלא יש חיוב ליתן (ובשבועה, לא חייב ליתן, אלא לקיים שבועה), אבל במק”א דן בזה (כמו שהז’).
לכאו’, יותר קל להבין שיהא מוח' משיהא ירושה, שעל פי דין, יבא לו; לכאו’, ואולי מכאן רואין נגד זה,  יש ירושה רק על מה שקנה אב. יש שלש מהלכים למה יהא ירושה:
א.ר”ש”ר באר שכשנשבע או כדו’, הוה כמחייב עצמו לתת כאילו נתן לו, ותלאו בדיני ירושה כאילו בא לו עכשיו. (ואז יחייב ליורשים). (ציין ר”ש למח’ תנאים במתנה “שתתן לי מאתים זוז,” אם יכול ליתן ליורשים. אמר’ שיש לחלק בין תנאי לשבועה.) יהא נפ”מ באי נח’ מתנה או ירושה. קשה לומר כן בקצות.
ב.פשטות ראישונים ואחרונים הוא שיש בזה ירושה.
ג.ר”א באר בתוס’ שיש בעלות במכירי כהונה (דע שמהו בעלות לא פשוט). לכן, הוה מצוי, ולכן יש ירושה. מביא תוס’ (כתובות יב) שכ’ שיש חלותיין בלי קנינין כשיש סמ”ד (אולי כל ענין קנין הוא להראות סמ”ד). לדוגמא, מביא מ”כ (הוא בתוס’ חלוק שם, ואומר לשון שוה, שקונה). מבאר קו”ש שיכול לחזור בו כיון שיש אומדנא שהתנה. מוזר שנאמר שיש סמ”ד חזק עד שא”צ מעש”ק, אבל אכתי מניחין שמתנה. גם אפשר (אולי כן ר”ל ר”א) שיש קנין שיכול לחזור עליו, שאף שגמ”ד חזק לעשות קנין, לא חזק כל כך שלא ליבטל (אולי שייך ל”דיבור מבטל דיבור”). נמצא כעי”ז בשלש מקומות: בנתינת כסף במטלטלין, אומר ר’ שמעון ש”מי שממון בידו יכול לחזור בו”- אם חד לא חוזר, צ”ל שחל. אז, צ”ל שחבירו קונה ויכול לחזור. ר”י סבר שמדרבנן, אין קנין מעות. מרש”י, נ’ שרק עושה שיכול לחזור, ולא שלא חל (שמשמע שהוא רק כשחיטיו בעולם, וחזרה רק כשהוא בעולם, דאל”ה א”א לעשותו של מוכר.) אמר’ שרש”י ג”כ כ’ שיכול לק’ במה שקנה בממון. צ”ל שאכתי קונה, ורק יכול לחזור בו. אלו דינים דרבנן, אלא שרואין יכולת לזה. יש להק’ שאכתי שלא ייחשב מצוי, שלא נח’ כן כשיחול לחזור בו.
חול’ נתיבות על קצות, שלא מסתבר שמתנה מועטת ושבועה מוח', ורק מכירי כהונה נח’ מוח'. באר שבמ”כ, כיון שאסור לחזור, תפיסת כהן יהני (כ”כ תוס’ בב”ק). תפיסת כהן בדר”כ לא יהני (כ”כ תוס’ בב”ק.) מפני טובת הנאה של בעל. לכאו’, מניח שטו”ה ממון, והוא שיש זכות שנתן תורה לבעל הטבל על ממון כהן (ולא שטו”ה אינו ממון, שהוא שאינו זכות, אלא שפראקטיקאלי הוא הבוחר, שברשותו הוא, שאז, תפיסה, שיבטל אותו מציאות, יהני.) אם מ”כ הוא, לא נתן לו תורה זכות זה כיון שאסור ליתן לאחר (אמר’ שחידוש שטו”ה ישנה, שאין נשבע שלא לשמש עם חפץ מפקירו, שמה שאין לו יכולת להשתמש לא מפקיע רב קנינין. א”כ, לא נניח שיפקיע זה. צ”ל ששאני טו”ה שאינו כל כך חזק, שכבר היה ממון שבט.). כיון שאין בעלות מעכבו, יכול לתפוס. העיר’ שרק מכיר זה יכול לתפוס, ורק כלפי אותו כהן, בטל זכותו (ר”ל, זכותו למנוע אותו כהן בטל). פשטות לשון נתיבות כאן משמע שסובר שמ”כ בא מצירוף מה שאמר קצות ומה שהוסיף. אמר’ שנ’ לו שרק שני עושהו מוח', ורק נגרם מראישון. אף נתיבות לא דן בירושה כ”א במצוי.
תוס’ כאן לא משמע כנוסח תוס’ בכתובות, שרק כ’, “. . . עביד מוח' . . .“ משמע- וקשה- שמוח' הוא (ולא רק כאן, אלא אף בגיטין). העיר’ שאותו גמ’ בגיטין לא דן במוח'ות, אלא, לכאו’, בקנין. (משנה שם דן בפריעה מכהן לישראל במה שלא צ’ להפריש. מק’ שאכתי יצטרך להפריש. מת’ שמכירי כהונה הוא. כדי שכהן יפרע, לכאו’ יצטרך להיות שלו, ולא רק מוח' לו.) משמע מלשונו (ואכתי ק’) שאין קנין, אלא מוח'ות, ושזה די לפריע”ח.
יש שכתבו (כעין נתיבות) שמכירי כהונה נקנים, שכיון שלו בטל טובת הנאה, קונה. (אמר’ שק”ק איך יוכל לחזור כיון שיש קנין.) לא נראה כן מתוס’ שלנו, שמדמה אותו למתנה, ומשמע שבשניהם רק עושה מוח'ות.
אפשר שתוס’ אומר שיש לכהן קנטר”ל של חפץ (שכן הוא, בדר”כ, פ’ מוח'). אף בגיטין, יש לכהן קנטר”ל (שצריך לבא לו), עכ”כ שיוכל לשלם חוב. אולי, אז, כבר נתקיימו מתנת כהונה (נ’ שרבי סבר שזה סיבה שיהא שלו יותר.). (אמר’ כעי”ז שמסתבר שנתקיים מתנות כהונה אף אי לא מכוון כהן לקנות.) רק נתקייים אם למעשה ניתן לו. אז, אולי לא רק ליכול לתפוס, אלא יש לו זכות לתופסו (אמר’ שאפשר שא”צ זה). א”כ, יש לו זכות, אולי לעשות שאחר לוקחו, ואז, לפרוע חובו.
דיון זה, איך שייך ירושה כאן, שייך בכ”מ. דן ר”ש איך יורשין חוב. אם יש שעיבוד מדאו’, י”ל שיורש אותר שעיבוד. אם אין שעיבוד מדאו’, אלא יש רק מצוה- ואם אין ללוה נכסים, שאז אין שעיבוד- אכתי יש זכות שיבא לו ממונו (אלא שאין כופין עליו). יש, לכאו’, סוברים שיש ירושה בלי זכות ממון. לעיל בארנו מח’ אי גו’, “ראוי.” ר”י כ’, לבאר לרש”י, שאולי אף בהו”א ידע שאפשר שמכירי כהונה דן (כמו”כ מוצאין, כות’, כמק”א.). גם אמר שאמר שיתן. משמע שאף מחיי בהמה, שאין חיוב זרוע, יהא ירושה. (העיר’ שר”י לא ס”ל כתוס’, שכיון שלא קונהו, שיכול לחזור, הוה ראוי. (אלא שעשו שאינו זוכה שזוכה. הוא לכאו’ דין מדרבנן (וחלוק מת’ קמא שם במתי אומ’ כן.) לא מק’ שאז אין ירושה.) אז, אולי, לכן יש ירושה בחוב. הענין הוא שבממון (ואולי אף לד”א) במקום מת הוא, ואף אי אינו של מת. אמר’ שחי’ שזה אף במ”כ ובשבועה, שאינם חוב ממוני. ויל”ד, שאולי הוא ממוני. זה מחו’, ולכן צריך קצות ראיות.
כ’ רשב"ם שמכירי כהונה “מזכין לו זיכוי גמור.” משמע שיש קנין. אור זרוע כ’ שרשב"ם בהמשכו לא משמע כן.[fn:1]אם מכוון לומר שהוא זיכוי, אולי ר”ל כר”א. גם אפשר שבעל מזכה לכהן. יש להעיר שחב הוא לשאר כהנים. אולי מפריש עצמו יכול כיון שיכול ליתן לכל מי שירצה, אף שחב לאחרים. גם יש להעיר שבדר”כ אין אדם זוכה בדבר שהוא שלו. כאן, אינו שלו, ששל כהונה הוא.
רש”י כ’ ששאר כהנים מסיחים דעת ומיאשים (כמו נמושות) (שיודעים שלא יבא להם), אז נעשה כאילו יש רק כהן אחד. אולי אף דומה ליאוש דאבידה. אינו כרשב"ם, שסבר שממש מקנה, אבל רש”י סובר שקנה ממילא.
(תוס’ סבר ששלמים שנאכל לבעל הוה ממון בעל לר”י (ורק מה שנאכל לכהנים בא משלחן גבוה).)
אומר רש”י שלא נקרא “בכל אשר . . . .” משמע שיש אכתי ירושה. קשה, שאינו ממונו. יש שמוסיפים שאסור ליהנות כיון שיש שם קדושה (יש פשטים אחרים למה). לכאו’ מביא כל זה דמעילה לומר שהו”א שבקדשי קדשים יש מעילה, ואז פשוט שאינו שלו (זה טוב עם ר”ח שאמר שמעילה הוא איסור גזילה.), ואז מחדש שאף קדשי קלים יש להם שם קודש (שייך למה שהוא חייב להקריבו להקדש), ואז אינן ממונו. אפשר שיש חילוק ביניהם במה שאינם ממונו, שקדשים קלים אולי הפ קצת ממונו, ואולי אז בם בייחוד יש ירושה. אולי לכן מוסיף בר”י “לכל דבר,” שרק בפרט זה מוסיף (ששניהם קצת ממונו).
בפשטות, לר"י ממונו ממש הוא. קשה, שגמ’ אומר שאי אפשר למכור קדשים קלים. לכן סבר קצות שאי אפשר לקדש אשה בקרבן שבו- שיש לו זכות כיון שהוא הבעל- ורק אפשר ליתן זכות אכילה. חידוש הוא בפרט לרש”י שאין בשר ממונו, ולא אוכלו מפני בעלותו. אז, מוזר שיש לו זכות זה. צ”ל שמוכר בשר, ושלחן גבוה נותן למי שכבר היה קונהו.
העיר רש”ש שק’ למה מזכיר חטאת, שחטאת שמת בעליה למיתה אזל וכל שבחטאת מתה באשם רועה. אפשר שיסוד הל’ למשה הוא שאין לו בעל (כן יסוד על אלו, במו כיפרו. . . ). יש לדון אם זה כעין טעם קרא. אם כן, צריך לומר שאף אין ירושה. אולי רש"י משמע נגד מש”כ (במה שיש ירושה אף שאינו ממון)- אף שאינו ממונו, קרבנו הוא (“נקרא תורא דראובן”), ויהא בו ירושה (ויש לדחות.) הק’ ר’ בהא שיש ירושה ושנח’ ממונו קצת. אומר שאולי הוא קצת ממונו (דלא כקק”ד). מבאר שיש בעלות, אלא שיש קדושה שמעכבו מלעשות כמה דברים. מביא ראיה ממה שיש ירושה (להוספת חומש) במעש”ש. העיר’ שדנים בזה. ר”ח אמר בביאור מעש”ש, והוא שיכולתו לאכלו הוא מפני בעלותו. נפקא מינא של ממון גבוה הוא אי יכול למכור וכדו’. חידוש הוא לוומר שכמו שהוא במעשר הוא בקדשים. דיון זה במעשר כבר דן בו ראב”ד בתו”כ, שמפרש מה שיש לו ירושה להיות או שממון בעל הוא או שיש ירושה על זה אף שהוא ממון גבוה כיון שיש גילוי מיוחד. משמע שבדר”כ אין ירושה, שאינו ממונו.(לכאו’, כל זה מניח שיש ירושה רק על ממונו.)
קונטרס הספיקות כ’ שדיון של ישנה לשכירות מתחלה . . . הוא (חלוק מ"משתלמת בסוף"-שראשון באיזה זמן חל (סיבת?) חיוב, ושני הוא מתי משלם.) רק בעבודה, אבל בשאר שכירות יש חיוב מתחילה, שיש דיון בפועל רק מפני שיכול פועל לחזור בו, ואינו קנוי. שאר שכירויות אין בהם חזרה, ואז חייב בשעת מעשה, והוא שלא משלם שוכר לעבודה, אלא למה שנותן לו זכות, וזה בא לו בשעת קנין. רש"ר מביא ראיה מר"י נגד קונטרס הספיקות. ר’ יונה כ’ שיש חילוק בין שכר שלפני מיתת אביו לשל אחריו, ששלפניוו הוא  מלוה (אף לצד שילדה). נמצא שלא משלם לחלות, שאז כולו מלוה. קונטרס הספיקות מביא ראיה מרשב"א שכ’ במי שהיה שוכר ומת וירשו שכירותו. לא יכולים יורשים לומר שלא רוצים בשכירות, שכבר חל, ואי אפשר לחזור. נמצא שכבר חל חיוב, כקונטרס הספיקות, ולא רק שחייב מחמת עבודתו, שאז יאמרו שלא יעבדו ולא יחייבו (אגב, העיר"א שרק היה לקה"ס רשב"א שבב"י, אבל באמת ממשיך לומר שזה אף אי ישנו מתחלה ועד סוף.) (וצ’ לדון על נכסי מי דנים) נמצא שאף שקנה זכות, ישנו מתחלה ועד סוף, שלא משלם לחלות קנין, אלא לעבודה (ק’, שאף אי לא עובד בו, חייב לשלם) או לזכות להשתמש בו לאחר זמן. יש ראיות שאף שבדר"כ כן הוא, יש אפשרות לעשות שכירות ולקבוע שיחייב לחלות. “מרבין על השכר ואין מרבין על המכר.” יכול אדם להשכיר בית ולהתנות שאם ישלם לאחר זמן, ישלם יותר, ואם מיד, יחייב פחות. מבאר גמ’ חילוק שבמכר חל חיובו מיד, ימה שפוחת הוא אגר נטר, אבל שכירות משתלמת לבסוף, ואז רק מנכה אם משלם מיד. הק’ ר"י מיגש שיהא מה שמנכה ריבית, שניתן לו כיון שמנכה לו מעות. מתרץ שכשמשלם מיד, אינו הלוואה, אלא שקונה דבר אחר, שמשלם לזכות, ועל זה פוחת דמים. נמצא שיש שני דרכים לעשות שכירות.
תוס’ כאן נוגע לזה. דנים מהו המשך דברי תוס’. (העיר’ שאינו מוכרח שיש המשך בין ראש תוספות לסופו.) יש שני מהלכים:
רש"ר פירש שיכול להק’ רק מפני תחילת תוס’, שזה עושה שאינו שבח שהשביחו יתומים. מניח שאז אף שכר אינו ראוי, שהוא תמורת ותשלומי עבודה (ודומה לציור שמכרו חפץ). מרשב"א נראה שיש לחלק לומר שעבודה אינו ראוי, ותשלומיו הוא ראוי. ופירשו שחלק מקשה גמ' הוא שאי אפשר להשכירו כיון שראוי הוא. אז, אין לרשב"א קושיית תוס’. לרשב"א, יש מקום לחלק בין דמי שכרו, שאינו כעבודתו, שאי בנים שכרו, הוה שבח שהשביחו יתומים. אבל מפני תחילת תוס’, אין לומר כן, שהוא חילוף דבר שאינו ראוי, והוא שוה לשכירות אב- וזהו ק’ תוס’. (באר’ ענין אמירה לומר שהוא כעין חלוקה.)
מהר"ם באר שלולי ראש תוספות נניח ששכר שכירת יורשים מוח' ממש, שבא מעבודה שהוא מוח' להם. זה רק אי ירושה משתייך לעבודה. אם כשמת כבר הושכר, אינו שלו, ואז, אינו מוריש אותו עבודה, אלא את השכר. בזה חול' רבי ורבנן. תוס’ סבר שאף בשכירות בחיי אב, ביסוד עדיין בעל הוא, ואז שכר לא יהא ראוי. לא מוכרח לדחות הנחה זו רק מפני תירוצו.
זה שייך לקונטרס הספיקות, שסבר שלא משלם שכירות לזכות כי אם לחלות קנין. אם כן, דמיון צריך ביאור, שלא שייך שכר לעבודה, שאינו אלא תשלומין לאותו חלות, ולא לעבודה. רק מובן אם נאמר שמשמלם לזכות, דלא כקה"ס, אלא כר"י.
רשב"א מחלק בין שכר לעבודה, ושואל גמ' לעיל רק איך לחלק עבודה. נמצא שחילק בין מכירת חפץ לשכירות. באר רבי: מכירת חפץ הוא אקסטשיינ"ג. אז, פשוט שנוטל מקום חפץ. דמי שכירות אינו כן; יכול אדם לחייב על מה שיש לאחר זכות השתמשות, אכל אין הנותן ממש נותן, שלא היה לו אותו יכולת שנותן שלו (אפשר היה לומר שנותן עבודה שהיה עובד לעצמו, אבל במציאות אינו כן, שאין הכרח שיעבד לעצמו) (כמובן, אם יש תשלומין לחלות, אולי הוא אקסטשיינ"ג של זכות.), אלא חייב מפני שצריך לשלם לזכות תמידי. אולי, אז, אין תשלומין במקום חפץ. אפשר שאף תוס’ סובר כן, ורק סובר שכיון שהוא תשלומיו, מסתבר שדינו שווה. לקה"ס, צריך לומר שהוא אקסטשיינ"ג.
הביא רבי ראיה לקה"ס מריטב"א. רבינו יונה כ’ שמה שעשה כבר מחיים נחשב מלווה. ריטב"א משמע נגד זה, אלא שלעולם מלווה הוא. (לכאורה, הדרך לבארו הוא על פי קונטרס הספיקות. ויש דרך אחרת גם כן, והוא על פי "שכירות אינה משתלמת אלא לבסוף,” שאולי כיון שזמן פרעון הוא בסוף, הוה מלוה. (עיין במאירי שהרבה בזה.)) הביא רב אלחנן סמך לזה מריטב"א שמביא מחלקת בשוכר דבר שבתוך זמנו נאבד. רא"ה מחייב ורמב"ן פוטר. לכאו’, אי אפשר לחייב אם לא סובר כקה"ס (ואולי בזה חול').
העיר’ שבמשנה של איזהו נשך שהבאנו קשה לקה"ס, שלעולם משלם לחד דבר (ויהא מיד). צריך לומר שלא משלם לאגר נטר, כיון שאין שכירות משתלמת . . ., אף שכבר היה חלות.
“אבל בנו בתים.” צריך לבאר למה אין פי שנים לבכור. לכאו’, הוא מפני שאינו שבח דממילא, שבא ממעשה יתומים. יש ראשונים שהם משמעים שאינו (רק) מפני שצריך מעשיהם. רמ"ה ור"י מיגש מביאים צד שאין שום ראוי לרבי, ומסיק רמ"ה נגד זה ממה שצריך להיות, בברייתא, שבח דממילא. אז, צריך לומר שלא מקיש רבי שני החלקים לכל דינים. מה שיש לו הוה אמינא, אף שאומר בפירוש דין "בנו בתים" משמע שאינו כל כך פשוט. רי"מ לא מביא ראיה מכאן כלל. נמצא שיש יכולת לפשט אחר כאן. אמר’ שהוא מסברה, כיון שהוא עבודת יתומים, ואולי שאינו חלק מירושה (אמר’ שלא יודע כל כך מהו הלומדות). גם שייך ל"ימצא לו,” אבל אולי אינו רק ראוי. אולי לכן רק מעשה יתומים אין בו חלק בכור (ברש"י) (אבל, לאידך גיסא, רש"י אומר לשון "שבח ממילא" כשאומר כן). דנים אם יש חלק בכורה אי אחרים בנו בתים.
דנים ראשונים מתי נתעבר בהמה, ואם הוכר עוברה בשעת מיתה (עיין ריטב"א). גמ' מביא ר"פ בדקל ואלים וכדומה, וחול' רק אי נשתנה שמו. יש שכתבו שאם לא היה חפץ בעולם, שלא היו פירות, משמע (ע"ש) אולי ששם אין חול' ואינו רואי. יש (בכללם, ריטב"א) שחול'. אז, אין צריך שהיה כבר עובר.
גמ' כאן אומר שמקור לשיטת רבנן הוא מ"לתת לו." גמ' לקמן אומר שמקור לדברי רבנן הוא מ"כל אשר ימצא לו,” ולא מהא דנתינה. תוס’ אומר שנדרשים ביחד, שכיון שנקרא מתנה, אומרים שימצא אומר ימצא ממש. וצריך ביאור. כתב ר"י צד שחול'. אמר שאולי מימרת ר"פ הוא רק למקור שני. סתימת ראשונים משמע נגד זה.
בדרשת לתת לו, יש שני מהלכים. רש"י כתב שמטי לידיה מכוון לידיה של אב, ואומר שצריך להיות דהר שיכול אב לזכות, ולא דבר שלא בא לעולם. מוסיף ר"י שאף למי שבוסר שיכול אדם להקנות דבר שלא בא לעולם, אינו יכול להקנות אלא לאחר זמן. אם כן, הדרשה דומה ל"ימצא לו,” ששניהם אומרים שרק נכסים שהם מאד של אב יש להם חלק לבכור. ר"ן כ’ שמטי לידיה מכוון לידיה של מקבל. (יש מקשים שיש מתנות קודם שבא לידו, שיכול לזכות. אולי כיון שיכול לחזור, אם אינו רוצה לקנות, עד שיבוא לידו לא נחשב שבא לו עדיין.) אז, אף בבכור, זוכה רק כשבא לידו. (יש להעיר שבמתנה צריך קנין. כאן, לכאורה אינו צריך מעשה קנין אלא חלוקה.) אז, ממילא, אין לו פי שנים במה שבא ממנו, שיש לו חלק פשוט במה שעשאו. אם כן, הלימוד חלוק מ"ימצא," שאינו דין במה בא לו אלא במתי קונה. מקרא של לתת לו, יזכה בן אם בנכסי סבא שמת אחר מיתת אביו, אלא שיש דין אחר מ"ימצא,” שממעט מה שלא היה לאב. לצד שני יותר נראה שחול' שני הסוגיות, שחד ממעטו מפני שראוי הוא וחד ממעטו מפני שלא זכה עדיין בחלקו, והיה בא לו רק מפני חלקו.
חול' בגמ' אי יש לבכור קודם חלוקה או לא. מסיק גמ' שיש לו קודם חלוקה. קשה, אז, למה לא נוטל שבח. רש"י מבאר ש"יש לו" לא אומר שהוא שלו אלא שיש לו זכות לו. (אומר רש"י שזהו "בכור שמיחה,” שיש לו זכות ליטול חלקו. זה גם כן ענין מה שאמר תוס’ לעיל (שיכול לומר).) אז, יכול למכרו כיון שישלו זכות למכרו (או שמוכר זכות ליטלו) כמו שיש לו זכות ליטל מקשה רי"ף למה לא נוטל כי שנים בשבח כיון שנוטל קודם חלוקה (שיש לו קודם חלוקה). משיב שזה רק לענין גוף נכסים. צריך ביאור מה אומר; אם שלו הוא, יזכה בשבח.  אי אפשר לומר שהוא שלו ממש ושאין השבח שלו (ולא נראה שרק אומר שהוא גזירת הכתוב). משמע יותר שהוא בעל למחצה, כמו שנמצא אי אחד קונה גוף וחברו קונה פירות.. (מקור שיש קודם חלוקה הוא אולי "לתת לו." קשה שכבר דרשנו את זה לדין זה.) ברי"ט אלגאזי משמע שאף ששלו הוא יש גזה"כ. גם יבאר על פי זה (של רש"י ועל פי רי"ף) יש לבאר איך לכול למחול חלק בכורתו.
רשב"ם סבר שיכול בכור למכור רק חלק בכורה. (לרש"י "לא עשה ולא כלום בפלגא" שאומר גמ' הוא חלק פשיטותו (רק בו לא עשה כלום). זה. אז,חידוש. לתוס’ (שחול' על רש”י), צריך להיות חלק פשיטות שלאחיו. אז קשה, וכן הקשה תוס’, שזה פשוט. תירץ רבי שאולי יש חידוש שלא יכול למכור חלק אחיו, שאינו ממש שלו (כמה שכתבנו ברש"י בחלק בכור), ורק יש לאותו אחד יכולת למכור.) חול' ראשונים על זה. ומביאים ראיות שיכול שותף למכור חלקו; אז, אף יורש יוכל. יש שני מהלכים לבאר לרש”י:
ר"א אומר שאפשר שיש לחלק בין שותפות לתפיסת הבית. בשותפות יש לכל אחד חלק, אבל בתפ"ב יש לאחים בעלות כללי (כמו שאמרנו במתנות כהונה). מבואר שתפ"ב חלוק משותפות, שחייב יורשים במעשה בהמה אף ששותפים פטורים. (רב אלחנן מדמהו לקרבן ציבור. מביא רמב"ן ורש"י שחול' אי  שותפים שהם רוב ציבור עושה קרבן ציבור או לא. אם הוא קרבן ציבור, אולי אין חילוק בין קרבן שותפים לקרבן ציבור, וקרבן ציבור הוא רק קרבן שותפים כשיש שותפים הרבה. גם אפשר שרמב"ן סובר סובר שכיון שרב בנ"י בעליו, נעשה של כלם בכלל. מביא עוד שהיה משה מתפלל שלא יאכל אש את חלק מקרבן של מורדים. משמע שיש מושג של קנין פרטי בקרבנות ציבור. אולי רק ר"ל שלא רצה בכפרת אותם אנשים. עוד מביא גמ' דיון אם כהנים שוקלים. הצד לפטרם הוא שמנחת כהן שרוף, ואז לא יהיו מנחות ציבור נאכלים כיון שיש לכהנים חלק. משמע שיש להם חלק. יש לדחות שבזה חול'.) אולי, אז, מובן מה שאי אפשר לכל אחד למכור.
ר"א מביא מהר"ח או"ז שדן בזה. שם מביא רש"י בחולין שאומר שיש חיוב מעש"ב כיון שהוא בחזקת אב,ואז של יחיד הוא. העיר’ שמצינו מושג כזה שנחשב של אב קצת. יש מושג כזה בלא"ו של עכשיו (ואולי אין להביא ראיה מזה), שנחשיו אסטיי"ט, והיורשים הם האגזאקיטו"ר. (ואם לא היה של יורשים, סבר, בהכרח יהיו נחשבים להיות של שותפים) .גם זה יבאר למה אינו נמכר (ואין זה מוכרח, שאפשר שהחול' על רש"י מודים לזה, אלא שסוברים שיש ליורשים שליטה, ואז יכולים למכור( אלא שאם כן קשה למה דנים ראשונים אי יכולים שותפים למכור חלקם)).
גמ' אומר קל וחומר משבח למלוה (ללמד שפשוט שמלוה שלא בא מחפצו אין בא פי שנים). רבינו יונה דן בזה. מקשה שלפשט שמטי לידיה קאי על מקבל, לא מובן קל וחומר ודין; מה שלא בא לו שבח הוא כיון שלא קנה חלקו (אמר’ שמסתמא חלקו הוא שחיוב על אחים הוא), מה שאין כן במלוה שהיה חלק מירושה, וכשמחלקים, יטול פי שנים. לא מתרץ, ואומר שאולי הוא מחלקת הסוגיות. (יש לדון אם זה אומר שמדחה פשט זה מפני אותו קושיא יש שכ’ כפשט זה.) העיר’ ש(אף שאינו הערה חזקה) שאומר לשון ש"לאו ארעא דידהו אשבח." היה לו לומר שהוא קרקע שלהם. אולי כן ר"ל. על מימרת ר"פ מביא י"מ שר"פ לא סבר שמקור לשיטת רבנן הוא מ"לתת לו,” שאז אין לחלק בשבח, שלא היה יכול להקנותו לו. צריך להיות שלומד מ"אשר ימצא לו.” אומר רבינו יונה שקל וחומר של גמ' מובן רק ללימוד של "ימצא" (אף לפשט רש"י של דרשת מתנה), שללימוד של מתנה אין קל וחומר, שלא יכול להקנות רק מה שלא בא לעולם, אבל יכול להקנות חוב. דוחה שקל וחומר הוא רק במלוה בפה, שאי אפשר להקנותו. מוסיף שאולי אף בשטר הוא, שהוא מדרבנן. בקושייתו אולי סבר שמלוה בשטר ניתן מדאורייבא, ואז לא ימעט מלוה בשטר. גם אפשר שסבר שמה שאי אפשר להקנות אינו סיבה, שאב לא מקנה, אלא סימן הוא מה מוריש. אולי במלוה יש לו אותו יחס הנצרך, ויש סיבה צדדי שממעט מכירתו, והקנאה דרבנן קצת סמך לקנין.
יש לדון לרבי למה נוטל שבח. חול' בגמ', כמש"כ, אי יש לבכור קודם חלוקה. אם אין לו, אז אינו שלו אלא של תפיסה. אז, יקבל התפיסה את החוב. אף אי יש לו קודם חלוקה, יהא קשה לרש"י. אפשר לומר שכל דיוני גמ' ברבנן. אם כן, נעשה קשה למה לא בא לו שבח שהשביחו יתומים, שבא מנכסיו. אפשר שרק גזירת הכתוב הוא.
העיר’ שאי נכסים הם של תפיסת הבית, באים לבכור מיורשים; ומשמע קרא שבא לו מאב.
אז, משמע שבחזקת מת הוא. הביא רבי ראיות למושג של בעלות המת. גמ' אומר לשון בתכריכים שקנה אותם מת. אולי אין זה ראיה כל כך, שיכול להיות שהלשון לאו דוקא. הדין הוא שנכסי מת חייבים לצרכי מת (ואולי לכן חייבים יורשים בחובותיו). לכאורה זה רק מפני שעדיין ממונו הוא. קשה להגדיר את זה, שאולי לא ממש הוה כבעלות חי.
זה יבאר מה שבא נכסים מן האב בירושה. גם לא קשה איך יורש שבח, שאינו של יורשים. גם יש לבאר שלכן לא מקשה ר"י ש"ארעא דיתומים אשבח,” אלא ש"לא ארעא דידהו אשבח.” גם באר רבי שעל פי זה נוכל לתרץ קושיית ר”י, שדומים למלוה כיון שבאים ברשות אב. אפשר שר"י סבר שכיון שהיה שוה להם לפני כן, יש להקשות. אולי זה שייך למשמוש.
קראנו גמ' בענן ירושת בנות צלפחד. מקשים על לשון רש"י, ומשמע קצת כשיטת בה"ג, שהוא שבכור נוטל פי שנים בנכסי אבי אבי, אם הוא בכור בן בכורו. מקשים שראוי הוא. יש שני מהלכים בביאור בה"ג. מרמב"ן נראה שהוא שבכור שנירק  נוטל פי שנים בחלק בכורה של אביו בשל אבי אביו. לכאורה, פלא הוא. גם אפשר לומר שיש לו כל חלק בכורה של אב. פוסק מאירי כצד ראשו. ואומר שיש שכותבין כצד שני, וחול'. מבואר מזה שיש מושג שבכור בן בכור נוטל בכרות אביו, שאז הוא במקומו. אז, דנים אם נוטלו לגמרי או שיש לו הלכות בכור, אלא שאכתי הוא רק בן בן, שהוא בכור לחלק עם אחיו. כל זה מחודש, שמהיכי תיתי שיהא בכור נוטלו יותר משאר אחים. (אמר’ שאין זה ראיה שהוא במקום אב ליותר מבכרות).
גמ' מזכיר דין חוב. הבאנו רש"י. תוס’ סובר כרש"י שהוא רק במלווה בשטר. יש ראשונים החול'. בתחילה נראה מרש"י שכאילו שטר משבח. צריך ביאור למה נחשב כן, ולמה נחשב כעין פרה וולד. ממשיך לומר שרבי היא. זה לכאורה מחלקת לקמן בגמ'. אולי לא מכוון לצדדי גמ' אלא למה שפוסק גמ' להלכה. אולי לכן מדמהו לשבח, שאי אינו שבח, קשה למה מזכירו רבי כיון שאינו תלוי במחלקת דלעיל[fn:2]. סוף רש"י צריך ביאור, שמשמע שלא יטול כיון שמוח' בשטר, שאי לא כן היה לו לומר במלוה על פה שאין לו שטר, ואינו שבח נכסיו. אם כן, הא דמלוה בשטר ש"מוח' בשטר" צ"ל לאו דוקא. סוף סופו משמע כתחילתו (“… דנימא דנכסים שבחו מעצמן"). תוס’ חול' וסובר שמה שלא נחשב ימצא לו אינו מפני שהוא שבח. נמצא, אז, שאומר שני טעמים לחילוק, ויש נפקא מינא בציור שאינו יכול לומר שפרע, כמו מלוה על פה שאומר בו שלא יפרע אלא העדים. (ואולי שם יש טענה אחרת שלהד"מ, שאז צריך עדים וכדו’, ואין ראיה לפנינו.)
מקשה תוס’ למה לרבנן לא נוטל פי שנים; יהיו חול' יתומים בשטרות. אחר חלוקה יהא לבכור פי שנים, שכבר קנה גוף השטר. אולי סבר רש"י שאי אפשר לעשות חלוקה על שטר או שסבר שאינו גוף ושבח ממש, והוא רק דמיון בעלמא.
באר’ שההו"א שלא לגבות מחלק בכור הוא שנקרא מתנה. אולי ר"ל שלשון מתנה משמע שהוא דבר הנתון מפני גודל רצון ה’- ואף שלא זכאי בו.כיון שיש כל כך רצון, לא יוכל ליטרף ממנו. גם יש לומר שאז אינו כיורש, אלא כמקבל מתנה, ויורשים קודמים. (ואם אין שעיבוד דאו’, לא יוכל לגבות ממתנה כלל.) רבינו יונה אומר שיש הו"א שקודם חלוקה לא יגבה, שאינו של בכור עדיין (הקמ"ל הוא שחייב כיון שיש לו זכות, ועומד לבא לו).
פשטות הברייתא הוא שמחלקים גיבוי החוב. אז, בכור נותן פי שנים. אף שגמ' אומר דין השייך שבע"ח כשגבה מאחד, תוס’ מבאר ששם היה אפותיקי. ברא"ש בב"ק מגדיר יותר מתי גובה מאיזה שירצה (ע"ש). יש להקשות, שיכול בעל חוב לגבות מכל לוקח שרוצה אם בשעה אחת קנו. משמע שיש ליורשים שום עמידה במקומו לשלם, ויש חיוב לכל אחד לשלם (אולי זה שייך למה שנכסים בחזקת אביהן). רבינו יונה חול' על רש”י, ואומר שיכול לגבות ממה שרוצה בכל ציור( אלא שאולי גובה ממי שיש לו בינונית, כיון שדינו בו). אז, ר"י מפרש שחידוש של גמ' כאן הוא שאי צריך חלק בכורה (שחלק פשיטות לא די), יכול ליטול חלק בכורה. אם כן, לשון גמ' דחוק, שהיה לו לומר שגובה מבכורה, ולא שנותן פי שנים.
העיר’ על לשון "איני נותן . . . “ שהיה לו להקדים שלא יטול. יש גו' כן. הביאור לגירסא שלנו הוא שלא יתן ולכן לא יטול.
לקמן משמע מרש"י שאין קודם חלוקה בחלק פשיטות כיון שלא הא לו עדיין, אבל כאן אומר רש"י אי אפשר למחול כיון שניתן לו בע"כ. יש ליישב.
רמב"ם מביא שנוטל פי שנים בפרה שילדה. ראב"ד כתב שפוסק כרבי. קשה, שאומר מימרת ר"פ, ומסתמא סובר כחילוק ר”פ. צריך לומר שלא ממש סובר כר"פ. מג"מ כתב שסבר רמב"ם שאין שינוי בעובר, ושכעין זה שנוי במחלקת (ר"פ וחול') אם בכעין זה חול'. אם כן, צ"ל שכבר נתעברה, ואולי אף כבר הוכר או יותר. סתום מרמב"ם.
ראשונים אומרים נק"מ לבאר למה ירצה לומר כן. אומרים שלש נפק"מ:
רש"י אמר נפק"מ (ע"ש). מקשים על רש"י שאף אי אינו שם, יורדים לנכסיו. דנים אם זה, למסקנת גמ', בכל מצב.
מניח רי"מ שכשאדם גובה מלוה, לא רק יכול לגבות כל נכסיו, אלא שחייב לוה ליתן לו דמי ממונו (ואולי לא חייב למכור, אבל חייב לשום וליתן חפציו), ובית דין כופים אותו. כתב רי"מ- ומשמע שסובר שהוא פשוט- שאותו דין נוהג ביורשים, שאף הם חייבים לגרום שיישלם החוב. אז, חידוש (וסיבה שיעשה כן) של "איני נוטל" הוא שיכול לסלק את עצמו מלטרוח לתנו לו (אבל פשוטים אחרים לא יכולים, שכיון שיירשו בע"כ, חייבים לטרוח בעדו). יש חול'; רשב"א מקשה שאין כופים אף לוה לגרום פרעון, ורק משעובד נכסיו. (ואומר שאולי אם פריעת בע"ח מצוה, חייב, אבל אי שעיבודא דאו’, ועל זה כופים, אין לכפותו לגרום פרעון. העיר’ שאולי אף אי שעיבוד דאו’ יש מצוה). ר"ן מקשה על הדמיון, ויורש לא חייב על זה, שיכול לומר שלא יטול חלקו בירושה (נגד רש”י). על כל פנים, רי”מ שמחייב יורשים כמו לוה משמע שלענין חוב מנכסי אב, יורש במקום אב. רשב"א, שלא חול' על הדמיון, גם כן משמע כיסוד זה. גם ר"ן, שרק מקשה למה לא יכול לסלק את עצמו, משמע כן.
מאירי אומר שאפשר לבכור לזכות על ידי מחילה זה. בכור רק נוטל במוח', ולא בשבח, בעל חוב, מניח, גובה משבח. אם חציו, למשל, שבח, יטול שנים של חציו. אז, משש מאות, יטול בכור שנ ופשוט יטול רנ. אם חוב הוא תנ, יחייב בכור לגבות פי שנים אם נוטל פי שנים. אז, יחייב קנ יותר ממה שהיה חייב, אף שרק רווח ק מפשוט. נמצא שאי לא יטול, יהא רווח כה. זה מחודש, שבפשטות, רק משלם פי שנים כיון שירש יותר, ומשלם כערך שירש. אז, אם יש שבח לא ישלם פי שנים ממש. זה מחודש ממ"נ; ועל כל פנים משמע שיורש חייב, וכיון שהוא יורש כפול, הוא משלם כפול.
ראשונים מביאים פשט אחר לפרש מהו הנפקא מינא בין בחור לפשוט מראב"ד, והוא שאם סילק את עצמו, בכור לא יכול לחזור בו. פשוט יכול לחזור כיון שכבר זכה, ואז צריך קנין כדי לסלק את עצמו. כל זמן שאומר שלא יטול, לא חייב, אבל כשאומר שישלם, חזר בו. אם קנה מיד, קשה למה יכול לומר "איני נוטל.” אפשר שכשמת נעשה של תפיסת הבית. כל יורש יש לו זכות לטעון לחלוקה לו, אבל עד זמן חלוקה, של כללם הוא. יכול לסלק כיון שנטילת חלק משנה בעלותו, ויכול לטעון שלא רוצה לקנותו (אף שיש לו אותו זכות). אבל, עדיין יכול לחזור, כיון שיש לו זכות חלוקה. רק בכור, שחלקו נקרא מתנה מסלק את עצמו עד שלא יכול לחזור בו.
רי"מ פירש ששיטת רבא הוא שהלכה כרבנן, וצריך לעשות כן, אבל מסברה מטין כרבי, ואז לא חוזר.
כל סוגיה זה נוגע לכללי פסק (איך פוסקים). לפעמים פוסקים כיחיד (ר’ יוסי, ראב"י). אף שלהלכה,  “אחר רבים להטות,” במחלוקות אלו לא דנו ביחיד וקבעו הלכה, אלא חלקו בבית מדרש. שם יש כלל לפסוק כרבים, וכלל זה דומה לכלל שנפסוק כתנאים מיוחדים (תלוי במי יותר גדול בחכמה (חול' מה זה) ומנין (אמר’ שהיה לו יותר תלמידים, ולמד מלימודו עמהם)).
העיר’ שהיה ר"נ יכול לדון בקבלת כלל של "הלכה . . . ,“ אבל מוזר לומר כן, לכאורה, בר"ח (ורב), שחיו בימי רבי, והיו כבר חכמי ישראל כשדנו בזה, והיו יכולים לדון בזה. (העיר’ שהיה אפשר לומר שרב דן מהו הלכה ולא מה היה נקבע, ולא משמע כן מראשונים שמוזר לומר שלא דנים כל אמוראים בחד דבר, וכתבו שאין האמוראים הבתראים חול' מסברה אלא מקבלה.)
הק’ ר"א שאם ר"ח מסופק, לא יוכל לפסוק כמו שרוצה; מצינו שבכור נחשב מוציא, ולא יוכל לגבות. מביא מר"מ אטלס שמי שראוי להכריע יכול להכריע בכעין זה. מביא ר"א רא"ש בסנהדרין שדן בפסקי קדמונים לענין טעה בדבר משנה. אם יש פסק קדמון, אם חלק מפני שלא ידעהו, חוזר. אם חלק, לא חוזר, אם הוא בר הכי. אינו ממש שייך לגמ' שלנו, שרא"ש דן במי שראוי אף לפסוק ולחלוק, ולא רק להכריע, ואומר שיכול לעשות כל אלו. לא מוכיח שיכול להכריע (כמו כאן) אי לו יכול לחלוק; וכאן לא יכול לחלוק על שיטת רבי, שיש מהם שהם אמוראים (אבל אין לומר כן בר"ח). צריך ביאור למה יכול, אף לר”ח, לחלוק, שכיון שיש לספק שהלכה כרבנן, איך יוכל לפסוק כרבי. מניח ר"א שר"ח אומר שיכול לעשות מה שרוצה (ו"מותר לעשות"). אין הוכחה להנחת ר”א בר”, ולא משמע כן מרש"י. אף בשאר אמוראים, יכול לעשות מה שרוצה רק כיון שלא קבעו כלל, ואז הניחו לאמוראים לפסוק כמו שרצו. מצינו מקומות שגמ' אומר שיכול אדם לנהוג כמי שרוצה (מחלקת ר"י ורבנן). שם צריך ביאור, שכיון שאין הל’ פסוקה יש כללים איך לפסוק. (אמר’ שמצינו כעין זה רק, אולי בחד מקום, ואף שם רק נראה כן.) שם כתבו שיכול אדם להכריע רק חד פסק ולנהוג כן לעולם. ויש לדון. מה שיכול אדם לעשות כמו שרוצה מוזר, שמחלקת הוא, והיה לו לפסוק על פי כללים, וכיון שספק דרבנן הוא, יקיל (ואולי חלוק כיון שיש בו ברכה). אז, אלו ראשונים שהבאנו צ"ב. (כוונת רבי הוא להקשות מה שהקשינו על ר"א אף כאן.)
אם דיון גמ' רק היה בקבלת הכלל, יש לדון ממי קבל “,נ לחלוק על קבלתו מרב. לא אפשר שקבל משמואל, שאף שמואל סובר (בפסחים) כרב. אולי קבלו מאדם אחר. גם אפשר שחלקו מסברה מה היה נקבע (ולא קבל כלום).
חול' אי "שטר" דווקא או לא. יש שכתבו שדרך ללוות בשטר, ולכן נקט שטר. יש אומרים ששמואל בדוי ושלחו בישראל, שיותר קל לנשות גוי. רש"י יסבור שאין לחלק לומר שיותר קל לגרום שגוי ישלם.
יש שלש בריי’ בענין חוב, והובאו בגמ' במקומות חלוקין. יש לדון למה.
רש"י כתב שהריבית שבו דן גמ' הוא אף אי נקט שטר וכבר עבר זמן, שהוא ראוי שלא אותו ממון נתן. (רש" י כתב שנתחייב "משמת אב"; ואולי יש שגו' "כשמת אב.” כמו"כ ראשונים מביאים רש,י גסי מוחכרת שכ’ שדן בקודם לכן ולא שלאחר החן, ארין מראה כן מרש"י שלנו. דן תורי"ד בזה בין מהדורא קמא לבתרא.
תורי"ד ור"י כ’ ששכירות שלאחר מיתת אב דומה לריבית שנתחייב לאחר מיתה. צ"ל ששכירות קאי על לאחר מיתה; אז, אף ריבית כן. בבתרא מחדש ששניהם של חיי אב. רי"ד באר ששכירות בחיי אב הוא דבר חדש, ורק נוטל מדבר שהתחיל בחיי אב. ר"י סבר שמה שהיה בחיי אב הוא מלוה ממש (וכן ריבית). ואולי יטול פ"ש לרבנן, וחול' בשל לאיר מיתה.
ריטב"א מחלק ביניהם, וסובר ששכירות לעולם מלוה (כקונטרס הספיקות). גם סובר שדבר חדש לגמרי הוא בכלל דין רבי. לגבי רבית, כתה שרק נוטל אי היה בחיי אב. קשה, שלא יגרע מדבר חדש.
העיר’ שיש שני מיני רבית, והוא כשנגדל לזמן (שאומר שישלם יותר אם ישהה ליותר) או שקוצץ זמן וממון. גם אפשר שיקצץ ממון וריבית, ולא תלוי בזמנו. כולם הם ריבית דאורייתא. על השנים ראשונים, יש לדון אם חיוב בא מתחילה ועד סוף או חולו מחתחילה. אם בציור שלשישי (או כצד שחייב מתחילה) יהא אי אפשר לחלק בין קודם ללאחר מיתת אב.
יש לדון למה חייב לריבית, לצד שנגדל החיוב בזמן. אפשר שהוא כעיין שכירות מומנו (ששכירות גם כן נגד, (אי  ישנו מתחילה ועד סוף). (קשה שכבר כלה ממונו, שקנאו לוה. אבל בודאי יש מושג כזה  ד"ממוני גבך”). גם אפשר שחייב מפני שלוה חייב לשלם למה שצריך מלוה לשהות, שזה שוה ממון (לשון “אגר נטר” משמע כן). אולי, אז, אינו כשבח, שאינו שבח מירושה, אלא שחייב לשלם לדבר ששהה בו. לזה, יש לתרץ לריטב"א שכאן לא בא שבח מחפץ אב (מלידתו או משכרותו), שאין לאב ממון, אלא חוב הוא שחייב כיון שמפסידו.
ר"א מביא רשב"א שדן אי יש חוב ריבית בעת הלוואה (אומר נפק”מ לענין מכירת ריבית, שתלוי באי נחשב חלק מן השטר). מסיק שאין חוב אז, שנגדל בזמן (לשונו שם הוא כצד ששכירות הוא). מביא ראיה מגמ' שלנו, שאומר חילוק בין חוב לריבית. צריך לומר שהוא ששטר, אף שאומר בו ריבית, אינו מחייבו כיון שרק נתחייב כשנגדל בזמן. אז, רק יש שטר על חוב. מניח כרש"י, שרבנן סוברים שיש לו מלוה רק אי הוה בשטר. (מרש"י נראה שהוא מפני שלא היה לו ריבית לעולם, ואף שיש עליו שטר.) יהא נפקא מינא אם מתנה על ריבית להיות חל מיד (כמש"כ). (ואפשר שרש"י סובר שכל ריבית חל מיד, ואין הכרח.)[fn:3]
מקשה ר"א שסותר רשב"א א"ע, שמשמע במקום אחר שנעשה חיוב מיד, אף שתולה בזמן שישאר ממון בידו. שם דן בשני גויים שתובעים ריבית מאחד שאין לו ממון די. בדרך כלל, מי שקדם חובו, גובה אם אין ממון לשניהם. יש לדון על ריבית שבא על זמן שלאחר הלוואה שניה לראשון, אי קודם לקרן דשני או קרן קודם לו. רשב"א פוסק שיש לראשון קרן וריבית קודם, שחייב מיד. מתרץ על פי מושג מר"ש על פי כס"מ שכ’ על רמב"ם שכ’ שאף ששואל חייב בעת אונס, שלגבי שאר דינים, אינו כן; והוא שסה"ח הוא שאלה, והוא קודם, ושעיבוד- זכות לגבות אי יש חוב-, אף קודם חיוב, חל אז. (כ’ נמו"י שאם זרק חץ ושבר לאחר מיתה, חייב. אפשר שהוא מפני שהוא משעובד בעת סה"ח, שהוא הזריקה.) (ודע שאינו כל כך פשוט לתרץ על פי זה ולהניח שסה"ח הוא ההלוואה.)
הזכרנו מה שאמר רשב"א בביאור למה אין ריבית כמאן דגביא. מפני כן, אף כותב שאי אפשר למכור את הריבית. הזכרנו מה שאומר רש"י בדמיונו למשכון. אפשר שיש נפקא מינא בין רש"י לרשב"א אם שטר לא נכתב אלא כמה זמן אחר הלוואה. גם יש נפקא מינא כשמתנה על ריבית להיות חל מיד. לא לבאר לומדות של רשב"א זה, ששטר הוא ראיה לחיוב ריבית (שלא יטעון שלא קרה ושלא יטעון שפרע) כמו שהוא ראיה לחוב. (למש"א רש"י שתלוי באי יכול לומר פרעתי, פשוט שיהא חלק משטר.) אמר ששטר חוב הוא אף שטר קנין קצת (הוא מחלקת ראשונים בגיטין), ואינו כן על ריבית, ואז אינו מצוי. אמר’ שהוא דחוק. אלא, אמר- והודה שהוא קשה להבין-, שאינו ממש דומה למשכון לרש”י, אלא דומה במה שנחשב שיש לו אכתי דבר במקום מעותיו (החוב נתגשם בשטר, והוא רפריזנ"ט אותו). מצינו כגון זה גבי "שטר אפסרא דארעא,” במכירת ממון. (אמר’ שתלוי בדרהר.) לכן, גם כן, נמכר חוב על ידי מסירת חוב. אז, יש לומר שעל זה נתמעט ריבית משטר, שלא היה שם בחיוב כשנתן שטר. אם כן, רש"י ורשב"א דומים; חול' רק אי מה שאין שטר על חוב כיון שלא היה אותו ממון למלוה או כיון שלא היה אותו חיוב, אז, למלוה. אולי לכן לא מבאר מה שאינו כרש"י.[fn:4]
בר"י מיגש כ’- וסובר שדנים על כל ריבית, בין לפני בין לאחר מיתה- אומר שרבית דומה ללידה. מקשה שאם כן יהא ריבית של חיי אב מוח'. שוב אומר פשטו של רש"י לבאר את זה. שוב אומר- ולכאורה מביאו כיון שמחודש הוא לו לומר שאף שחייב בחיי האב, לא נחשב מוח'- שאפשר שדן באבק ריביית (דרבנן) לישראל, שלא מוציאים כיון שגבו יתומים. לא נחשב למלוה מפני שאין מוציאים אותו מן לוה (ועוד, אמר’, שהוא אסור לגבות). רבי חול' כיון שאף שלא גובה, כיון שהיה לו זכות מחיים, נחשב זכות (אומר שאגלאי מילתא שזכה בו, והוא לשון מוזר).
רש"י וריטב"א סוברים שאף בריבית קצוצה יש חוב, אף שאי אפשר לגבותו, ומוציאים אותו. באר"ש שיש ענין משפט חלוק מדיני יו"ד. (חז"א סובר שלא ממש סובר כן רש"י.) לכאורה, אז, כל שכן יש באבק ריביית חוב. יש שמשמעים נגד זה, שרק לא חוזר אם שילם, אבל אם תפס, גזל הוא, ומוציאים אותו ממנו. אם יש חוב, קשה מה לנו בזה. אלא משמע שרבנן הפקיעו את החוב. אפשר שרק חול' זה על זה (ואולי יש בעיא, אז, להלכה). ר”ש דוחה שאולי אי פחות חוב גבי אבק ריבית, שלא רצו רבנן לעקור דבר מן התורה לאסור לשלם, אלא הפקירו (שהפקר ב"ד הפקר) לעשות שאין חוב. לכאורה, לרי”מ, כיון שיש ירושה, צריך לומר שיש חוב. (צריך לבאר לשון רי”מ שהזכרנו לעיל.) גם משמע רי”מ בתשובה שר"ק חוב.
העיר’ שאף שמואל היה מנהרדעא, ואם כן, אף שהוא כחד מבני נהרדעא, חול' על שני.
העיר’ שמחודש שיש חילוק בין קרקע לממון מפני השעיבוד אף ששניהם נגבים מלווה. גמ' יש לו צד שיש למטלטלים שעיבוד מדאו’, ונגבה מלקוחות. מדרבנן, לא נגבה מלקוחות. דנים ראשונים אם נשאר להם שעיבוד; יתלה איך ביטל רבנן גבייה מלקוחות. יש אומרים שקרקע יותר מצוי, שקשה לאבדו, ואינו נפקע ממנו במכירה.
יש שמוסיפים ברש"י לומר ש"מעות נתן…” כיון ש"עיקר חוב" הוא מעות, שעיקר החיוב הוא להחזיר מה שדומה למה שנתן לו (וכשמחזיר דבר אחר, הוא כאילו מוכר לו במקום המעות). ר"ת אומר שבחוב, צריך לשלם ממון. לא משמע כן מלשון רשבם, ומשמע שלא סובר כן. יש לדון, אז, למה צריך ליתן ממון אם יש לו. אולי זה מפני שסומך דעת על ממון.
אמר’ שאולי מה שרשבם לא אומר כר”ת בביאור שיטת רבה הוא שסתימות גמ' משמע שרבה ור”נ מודים לחד שיטה. יודעים שכן סובר רבה ממה שסובר שאין נכסים לבעל בת וסבר שאין שעיבוד דאורייתא. רי”מ ג”כ מניח ששניהם שוים, אלא שאומר צד להיפך של רשבם. מוכיחים שרבה סובר שבשניהם אין לו כיון שאומר גמ' שסבר שאין שעיבוד. רי"מ יבאר שזה רק אומר שלכן אי אפשר לו לחלק, אבל אולי סבר שאף בלי שעיבוד מצוי. קשה מה לנו אם אין שעיבוד דאו’; אכתי יש שעיבוד.מגדיר"א שתקנו רק שגובה, ולא עשו שעיבוד. אז, יש לו זכות רק כשבא לגבות. ק"ק מהי"ת. אפשר שאם הוא דאו’, יותר חזק מאי הוא דרבנן. אמר’ שמצינו במק"א שדנים על שעיבוד דרבנן כאילו אין שעיבוד, וצ"ב.
אמר’ שאפשר שרבינא לא סבר שרבה אמר כן, אלא שר”נ כפשוטו.
העיר’ ששרבם גו' מעשה קצת חלוק, והוא שהניח נכסיו לסבתא ובתרה ליורשי סבתא (ויש גו' כן בגמ'). יש לדחות שר”ל שראוי לירשה כיון שראוי ליקח ממי שהתנה. בע”ב, גו' כגמ' שלנו.
צריך לבאר “אי קדם וזבין,” שיכול לגבות ממשעובדים. כתב רשבם ש”אי בעי היה מוכר את זה ומסלק ב[דבר אחר].” צריך ביאור למה צריך מה שיכול למכור; הענין יהא מה שיכול לשלם מדבר אחר. אולי רק הביאו אגב לשון רבה בסבתא. גם העיר’ שאם מכרו, צריך לשלם מממון אחר, ולא רק שיכול.
בארשבם שתירוץ גמ' לרבה הוא שסברת “כיון דאי קדם” אינו כל כך נכון כאן, שיכול לטרוף. ר”נ סובר כרבה, ודינו מרב”א היה מפני שדר”נ. בארשבם לקמן שדין “אי קדם” הוא הוכחה שאינו כמעכשיו. אם כן, לא יוכל להיות סברה שיהא ראוי כאן, וקשה למה דן בו רשבם כאן. צריך לומר שהוא יותר מסיבה שלא לומר שהוא שמעכשיו; וקצת מוזר למה לא מזכיר רשבם אף זה בע”ב. תוס’ כ’ שסברת אי קדם שייך כאן, אלא שהוא רק לדברי רבה.( גם אומר צד שצריך סברה זה לומר שאין גובין רק כיון שהוא כאומר מעכשי.ו. (זה נגד רשבם שאומר שאם היה סברה זה וסברת מעכשיו, היה מצוי, שלכן צריך לדחותו אף שיש נקודה זה.)
יש שמקשים- וצ”ב מה קשה בזה, שמטלטלים של יתמי לא משתעבדי, ואז מה שהם מצוי לא עושה שיגבו- אם למפרע גובה אף מטלטלים, יהא דין רב”א אף על מטלטלים. אולי תלוי כמה שייך לשעיבוד.
רמבן סובר שרבה סובר שאין לו ולא ידע מה סובר ר"נ.
הזכרנו שלש פשטים למה ריבית ראוי. אמר"ן שאינו כל כך ברור, שימחה לווה על פריעתו. מושג זה (שתלוי באם נניח שיבא) אומר שלא רק תלוי בגדרי למדות (בזכויותיו). כמו כן הוא חילוק שאמר תוס’. (אמר’ שמצינו שדברים ייתלו בדרהר של בני אדם, שבל בדרך כלל זה רק כשמשנה מציאות שישנה את הדין (למשל, יעשהו יותר שלו). כאן, תוס’ שלא אומר כן.)
חקר’ אם מה שיכול לסלק בזוזי הוא סימן שאין לו זכויות או סיבה שלא סומך דעתו.
העיר’ שמרשבם משמע שמה שקרקע זה לא היה ממש שלו לא מהני אלא בצירוף מה שיכול להפקיעו, שמודה אביי שיש עליו שעיבוד, וסבר שזה לא יהני כיון שלא יכריח שיינתן לו.
משמע מרשבם שסובר שמה שיכול למכרו לא יהני נגד מעכשיו. תוס’ חול' .מעניין, שמשמע שלמפרע מפקיע חלות דמעכשיו, וכיון שיכול ליפקע בשעת מיתה, אינו מצוי. נמצא שאף שהוא שלו, אינו מצוי. כמו כן, כתב רמב"ם שאין ספינה שבים נחשב מצוי. לכאורה, רשבם יחלוק לומר שכיון שהוא שלו, מה שאפשר ליפקע אינו עושה שאינו מצוי. לתוס’, חשבון גמ' שלנו הוא שיש לנו ראיה מגמ' לקמן שיש סברה חזקה- חזקה מכעכשיו- שעושהו ראוי. לרשבם, צריך להיות שמה שיש סברה שיהני אם אינו כמעכשיו יגלה שכאן, שאינו מעכשיו, ראוי הוא. אם כן, נמצא שאם אינו כאומר מעכשיו, אינו נכון שאין כלום שעושהו שלו, שאז אין ראיה משם, ששם אין שום שעיבוד או חוב ,והוה ראוי ממש, ולא מוכיח שכשיש שום בעלות נחשב ראוי כיון שיכול למכור, ששם נחשב ראוי כיון שאין שום בעלות. (באמת, מקשים ראשונים כן על אותו דמיון.) אלא,  צריך לומר שיש כבר שום זכות בהא דסבתא (ולכן חל לאחר זמן). מעניין, אז, שמניח גמ' ששני הזכויות שווים, ויכולים ללמוד אחד מחבירו. יש לדון בציורי תנאי.)
אביי מק’ קושיותיו על רבה בהנחה שאין שעיבוד עושהו מוח’. העיר’ שלאביי בע"ח למפרע גובה, ויהא כמעכשיו. (מעניין שרשבם לא מזכיר כלל גיבוי למפרע כאן) אפשר שסבר שרבה לא סבר כן, שאם כן, אף מעות יהיו מצויים (על"ע, שדנינו בזה). ר"י מזכיר גיבוי למפרע כאן ומבאר שהוא אף במעות (באמת, סותר א"ע בזה לקמן). אמר’ שעדיין יהיו בעיות. גם אפשר שלמפרע חלוק ממעכשיו, שלמפרע צריך גבייה לעשותו חל למפרע (משא"כ במעכשיו, שאינו צריך מיתה לשעשותה בעל). אולי כיון שצריך מעשה, אינו מצוי. כ"ז מחודש.
יש שחול' על רשבם לומר שאביי מק’ (לר"י) מפני ששעיבוד אינו דאו’ (שאביי סבר, אמר, שאינו דאו’. לכאורה, א"צ זה; צריך רק מה שאומר אח"כ שרבה סובר כן. ) כיון שאינו דאו’, אין לחלק בין קרקע למעות. (הק’ רן שיהא מצוי אף אם אינו דאו’. תי’ שדרבנן חלוק. וצ"ב.) מוסיף ר"י שהיה אפשר לאביי להק’ על דין קרקע, מבלי ראיה ממעות. על זה דוחה ר"י שהיה אפשר לדחות ק’ ראשון שלמפרע גובה. ממעות, מוכיח נג"ז. חזר’ לסתירה שבר"י (שלקמן אומר שאביי מק’ שיהיו מעות ראוי מכש"כ לר"נ, שעליו אין גובין למפרע. אפשר שתלוי באם שעיבוד דאו’; שעיבוד הוא סיבה להיות למפע נגבה. א"כ, בר"נ, מניח ששעיבוד דאו’, ואז, רק בקרקע יהא למפרע, שיש שעיבוד. אם שעיבוד אינו דאו’, כברבה, אין לחלק. יש לדון מה סובר אביי האומר שלמפרע גובה; ייתלה במה אומר בשעיבוד. אם גו' שאומר כאן (ואולי אין לגו'ו, שאין צריך) ר"י שאין שעיבוד, נמצא שאומר על כל. אם כן, קשה למה נניח שיש חילוק אי שעיבוד דאו’. אם לא גו’ כן, יש לומר שאביי מחדש צד שגובה למפרע אם אין שעיבוד כדי לבאר רבה.
ר"י מעורר שיש לחלק בין כאן לסבתא, שכאן, אף אי נמכר, צריך סילוק מעות. אומר שאינו דמיון ממש ואם שם מהני נגד מעכשיו, כאן יהני מה שקצת יכול לסלקו נגד יחסו (כיון שאין שעיבוד דאו’). ר"י דן בסבתא בהפקעה של מכירה, וכאן בסילוק זוז בפ"ע רן דן בהפקעה של מכירה. אז, דומים ממש, שבשניהם מדאו’ רק צריך למכור (ומה שהוא מדרבנן לא מחשיב). יש לדון בנקודת מח’ ר"י ורן, שאף שר"י סובר שכיון שהוא מדרבנן לא מחשיבים אותו, ואין זכות, אמר שאינו דומה. רשי מביא מר"ח שק’ גמ’ על ר"נ הוא שמוכיח שקרקע מוחזק, שאי לאו הכי לא יגבה. (היה אפשר לדחות שזה רק בכתובה הקל.) ר"י משיג על רשבם (בב"ח בראוי) וכ’ שאף אי לא גובה מראוי, זה לא יהא ראוי בנוגע חוב, שרק לא עומד לבא לו. יש מיני ראוי: לפעמים הוא לא היה שלו מעולם, אבל כאן הוא מפני הספק, ואף שהוא שלו. כיון שאין זה בעיא בבעלות (בפרט אם למפרע גובה), זה רק בעיא ב"ימצא,” ולא בחוב (שאף שנלמד מקרא, אינו מ”,ימצא.”). (דן הגהות אשרי בפיקדון ביד אחרים (כמו מלווה על פה) שאולי ראוי לבכור. כבר הזכרנו רמבם גבי ספינה (מחודש, ועוד שמקורו דחוק). אלו משמעים שלבכור רק צריך שלא עומד, ואף ששלו הוא.) רשי יחלוק לומר שספק בעלות משנה בעלות (ורק אז ראוי). 65חי’ הוא. אולי ר”י סבר שצריך להפקיע יכולתו לגבות, ורן סבר שצריך לסלק זכותו. (אמר’ שבוודאי סובר ר"י שאין צריכים שהפקעה גורע קנין, שיכול להיות שגורע יכולת. אפשר שעדיין לא מודה לרמבם, שבוודאי קונה, ואולי רק יאבד ממנו או כדומה.)
העיר’ שלסוברים שאי אפשר לאדם לשעבד את עצמו אם אין שעיבוד דאו’, וכן לצדדים שרק יכולים רבנן להפקיר, מוכרח שרק יכלו רבנן לתקן שיסלק מלווה או לוקח, אבל לא לעשות שעיבוד. אולי אין צורך לעשות זכות. אם מלוה הכתובה בתורה יש לו שעיבוד דאו’, אז, אולי יש יותר צורך לעשות שיהיו שווים.
דנים מי יורש באופן דיירק”ט, ואז נקרא יורש. אינו תלוי במה כתוב בתורה, שאף שאחי אביו נכתב, רק בא לו ירושה ע"י משמוש. חול’ ראשונים איך יורש אח. רשבם כאן אומר שנחשב יורש, והוא שלא יורש ממשמוש.
רשבם אומר שלר"ע יורש הוא בעת מיתת זקנה. כן מוכח, שאי לאו הכי, היה לו לומר בת בפירוש.
אמרשבם שמק’ על ר"ה. רק מימרא הוא, אבל לא מצינו חול’ בפי’, שאז מניח שלא יחל’ ר"ה. מעניין, שכל ירושת בעל (ודין ראוי) סתום וחול’ אמוראים (וראשונים להל’) אם יורש מדאו’ או מדרבנן. לכאו’, צ"ל שלא תלוי דין ראוי על מקור ירושתו. כמה ממקורות ק=דין ראוי הם דרשות מקראים בנביאים. צריך לומר, אפ הוא מדרבנן, שכבר תקנו רבנן.
רי"מ כ’ ש"נפתח…” אומר שהוא כבר דיון בתנאים ואף באמוראים.
דנים אם בעל יורש מלווה.
נלמד מה שאין בעל נוטל בראוי מקראי בנביאים. אינו ממש נל’ משם; אותם קראי רק מגלים שהוא כן. אולי הוא הל"מ או יש מקור אחר. אם ירושת בעל תקנה, אז, ידוע היה, והוא שלא תקנו (יל"ד למה) לבעל.
דנים למה יורש בעל. לכאו’, הוא מפני שהוא קרוב. יש אומרים שאינו כן (ואולי אין מי שסובר כן (רי"מ משמע שיש ענין קורבה בו).) אומר רשבם שלכן קודם לבן, שרואים שסיבתו קודם לסיבת ירושה. תוס’ אומר כמותו, ואומר שיורש מחמת שארות (שהם בשר אחד). (כ"ז יותר קל מדאו’). במק"א מביא ריב"ן שכ’ על מה שאין בן יורש אמו בקבר להנחיל לאחים מאב (ורק להנחיל לבניו) שמדמה גמ’ לבעל, שלא יורש בקבר. יש לדון אם אשה (כן אומר רשבם, והוא אותו דין שאינו יורש בראוי) או איש בקבר (זה עושה את הדמיון יותר טוב, אלא שאז ק’ מהי”ת). ריבם כ’ כשני, וכ’ שהוא פשוט כיון ששארותו פקע במיתה כמו בגט. זה אף יבאר למה לא יורש ראוי. אז, זה מקור לדין ראוי, וקראי שמביא גמ’ אינם מקורות ממש. רי"מ אומר כעי"ז שתלוי באישות. אפשר- ואולי כן משמע- שתלוי בקרבה הבא מאישות. זה בטל לאחר מיתה. תוס’ מק’ על ריבם ואומר"י שפשוט שאין משמוש בשארות, שנלמד משמוש מקרא בקורבה זה אף יבאר דין ראוי. רי"ד אומר שירושתו הוא זיכוי מגזה"כ, אף שאינו קרוב, וזה רק אם נשוי לה. לריבם, ק’ שבהכרח ירושתו אחר מותה. צ"ל שצ"ל קרוב בשעת או קצת לפני מיתה. (יל"ד אם זה אמת לחול’ על ריבם.) תוס’ מק’ למה צ’ אז קראי לדין ראוי. אם סברות אלו הם נכונים, קשה איך לומדים ממנו דין בן בקבר (לא משמע כן מתוס’ כ"כ, שכ’ “[במקום אחר לומדים אותו] מקרא אחרינא,” שמשמע שהוא לימוד ממש. יש גורסים, “לומדו מקרא.”)
אם מה שכתבנו נכון, פשוט לומר שיש חילוק בין בעל לבכור כיון שסיבת דין ראוי חלוק; בבעל הוא רק מפני שאז אינו שאר. לכן, חולק רי"מ על תוס’ בחוב, שהוא שלה, אבל רק אינו מצוי. ר"ש מקשה למה נחלק בין בעל ובכור. הז’ ראית תוס’ מגמ’ ב"ק. רי"מ יש לו גירסא אחרת (גמ’ חוזר לומר ש"בעלמא [גבי בעל] כרבי ס"ל [שלא חולקים רבנן]." (חול’ (ר"י) כ’ ש"רי"מ שיבש את הגירסא.”) עדיין מחלק רי"מ ואומר ציורים שאין לבעל מלווה (מג"מ אומר שכן סבר רמבם; וסתום הוא.), שסבר שרק יורש אם הוא בשטר (ואף שלא הגיע שעת פרעון) או אם הגיע זמנו (ואף אם הוא על פה). נמצא שיש בראוי יותר מלאח"מ. כן משמע מגמ’, שכל הו"א של גמ’ שם הניח דמיון. גמ’ שם אומר מקור אחר למה לא נוטל בראוי (לומדים שכופר אשה ליורשיה כמו שכופר איש ליורשיו). רי"מ מבאר שכופר הוא ראוי כיון שרק בא לאח"מ, דלא כסתם מלווה. תוס’ מק’ למה צ’ קרא שם כיון שכבר יש קרא כאן לראוי. אומר צריכותא. ק’, שכיון שיודעים הסברה, לא נמעט חובות וכופר, ואז פשוט לתרץ. אפשר שאף כופר לא בא אלא לאחר מיתה, והוה ככל ראוי. לכאורה, אם כן, אין מקור לדין חובות ונזקים, ששם הוא כבר שם בעת ירושה. תוס’ מז’, “וכן חובותיה… [נלמד מכופר].” אם כן, צריך לומר שאין דין כופר מפני אותו דין, אלא מפני ראוי. אם כן, פשוט ששניהם נצרכים (כמש”כ לעיל). גם קשה, שאם יכולים ללמוד מכופר, נוכל ללמוד משם לכל (ע"ש). תוס’ בבכורות כ’ שאף שמקור ראוי דבעל הוא רק על לאח"מ, יודעים דין חוב משם כיון שמצינו שתורה דימה בעל לבכור, עכ"פ לדינים שלאחר מיתה. (וכן נאמר אם הוא מדרבנן, שממה שדימהו לבכור לאח"מ, מסתבר שדימהו בכל.) אם כיון, לכאורה, אי אפשר לומר טעמי ראוי שהזכרנו לעיל.
(אגב, אמר’ שמעניין שגמרא אומר שם "מה בעל… ליורשיו, אף היא… ליורשיה,” דהיינו קרובים שלה. משמע שאין בעל נחשב יורשה. זה מוזר לכל הצדדים שכתבנו (חוץ מרי"ד). אולי אינו יורש, אלא הוא בשר אחד עמה, והוא עומד במקומה באופן חלוק.)
הזכיר’ שאף לרשי, יש אותו ביאור לדין ראוי (אומרו כריבם).
בריבם, יש אותו ביאור לראוי. אמר’ שיש לדון אם טעם של רי הוא אף סיבה לדין ירושה, שאולי רק אם המת אינו קרוב למוריש, אין משמוש; תלוי באי יש חידושע במה שהוא מוריש בקבר או רק במה שהוא יורש בקבר. הזכרנו רי"מ. לכאורה, אף לזה, ויל"ד (שיש חילוק במי מת לענין עריות, אולי), יבאר דין ראוי. הז’ רי"ד. אמר ר’ שלכאורה, אין זה מוכרח לבאר ראוי, שכיון שהוא חי, נתן לו תורה. אם סברת זה יהני לזה, לכאורה, יהא חד סברה לשניהם, ולא יהא דומה כלל לסברת בכור. אי לא, לכאורה, יהא להם סברות חלוקות, ואולי יהא סיבת בעל כסיבת בכור. לראשון, מובן מאד למה נחלק בדינים (רי"מ, למשל, אומר שיש מלווה לבעל.) יותר מעויין, שהרי לא בכל מצב נוטל בעל מלווה. אפשר שיש עוד דין למלווה (והוא נלמד מכופר); וקשה איך ילמד (כמש”כ)[fn:5]. ר”ש כ’ שאין כופר כ”כ קשה, שיש לומר שאין חוב כלל, והוא רק לאחר מיתה. אמר שאולי כשיש לאדם סיבה ליקח דבר מחבירו לאחר זמן, צריך להיות שיהא לו זכות וסיבה באותו זמן, והוא שזכות ליטול מלווה- ואף זה דיון- שלא הגיע זמנו אינו זכות, אלא זכות להשיג ממון לאחר מיתה (כשהגיע זמנו). כיון שבאותו זמן שיש לו רשות, אין קנין, אין ירושה, ואין לו זכות. זה יבאר, אז, רי”מ. הזכרנו תוס’ שמניחים שדין בעל ובכור שווים (ולומדים זה מזה). זה, לכאורה, אינו אפשר אם נאמר שיסוד דין ראוי הוא כמש”א ריב”ם, שאז אין סיבה להניח אותו דמיון.) רש"א שאפשר שדין שיש בבעל הוא ביסוד אותו דין של בכור. מלווה לא הורש, שאינו קנין ממש, ושעיבוד גם כן, אולי, כיון שרק בא מחוב, לא הורש. אם כן, צריך להיות שיורש במקום המוריש, ולכן לו יישלם. כן הוא גם כן בכופר, שכולו חל רק לאחר מיתה. אז, מה שלא נוטל פ"ש בחוב בבכור הוא מפני שלא בא עדיין, ואין פי שנים בהיותו במקומו, אלא בירושת ממון. אם כן, כל הבא לאחר מיתה אין בו פי שנים. הדרך שאומרו הוא שיש שני מיני ירושה, יש ירושת נכסים ועמידה במקומו. רק על מה שהוא שם בשעת מיתה יש ראשון. בבעל ובבכור, אין שני. לדרכו, אינו צריך להיות שלעולם יש שני סיבות ודרכים אלו; אפשר שאפשר שיש רק מין שני. על דרך זה, יש לומר חילוק מסתבר, שהוא שבעל, שאינו במקום מורישו, יורש בדרך אחר (וזה יבאר מה שאמרנו לעיל שאינו נקרא יורש), והוא מפני שזיכה לו תורה. כמו כן בכור הוא "מתנה קרייה,” והוא מתנה שזיכה לו ה’, ואינו מפני עמידתו במקומו. אמר’ שאין זה מהני בראשונים (תוס’ בבכורות) שבא לבאר, שתוס’ ור"י (שאומרים כן, ומדמים להדיא, שיש אחרים שאומרים שהדין שווה, אבל לא לומדים זה מזה) אומרים שדין בעל נלמד מדין בכור לדין מלווה, שנדרש גבי בכור. לר"ש, אין צרוך ללמוד דין בעל מדין בכור; כיון שאין קורבה לאחר מיתה, פשוט שאין לו מלווה. לכאורה, עוד יש בעיה למה שאומר תוס’ ורבינו יונה שסברת "זביני זביני" הוא שאף שהוא כמעכשיו, כיון שיש צד הפקעה אינו מצוי, שהרי נתגלה שהיה מעכשיו, ואז לא יצטרך קורבה לאחר מיתה. צריך לומר שראוי של בעל הוא כהלכות בכור, וצריך להיות מצוי (ואז אין צורך לומר שהוא כלל מחמת שאין שארות לאחר מיתה). (אז, גם כן, צריך לומר נגד ריבם).
רב ראשונים סוברים שפסק של ר"פ הוא הפסק להלכה. יש שמדייקים ממה שלא אמר שאין בעל נוטל במלווה שרק בכור לא נוטל.
דנים מי מוחזק במצב בכור. אם אין מוחזק או מרי קמא, אז, אפשר שיחלקו (ואולי הוא שודא דדייני. תלוי במהו שודא דדייני.) אולי תוס’ מניח שכיון שקראו מתנה, לאחים מוחזק. אינו מובן מהו "בעין יפה… ." אולי רצה לומר שאינו רק שעיבוד (שאינו מוחזק) אלא קנין יותר מזה. אולי רצה לומר בעלות גמור. לשון רשבם משמע שהוא שעיבוד יותר חזק. אולי רצה לומר קנין. אם לא רצה לומר כן, צ"ב. יש ראשונים שאומרים שביאור גמרא הוא שיש לו פי שנים עם מלווה שעמו (אולי גורס "פליגי," והוא שחולקים בני מערבא לומר שלוקחים פי שנים. צ"ב, שחול’ על כל מלווה.) עכ"פ, כוונתו הוא שבזה, הל’ כבני מערבא. ר"ג מבאר שהספק לרשבם הוא שכיון שיש לו שם מלווה (בכל זמן שאומרים "שם" הוא לומדיש)… . לשונו משמע שאינו ספק, אלא הוא מוחזק ומלווה, ואז חולקים. מוזר, וצריך לומר שר"ל שהוא ספק, והספק הוא שמוחזק הוא מסברה, אבל יש לו שם מלווה. לכאורה, רצה לומר שכיון שלומ’ שאין פ"ש במלווה, ולימוד מ"ימצא לו," אולי כולל כל מלווה. קשה, שלכאורה, לימוד הוא רק על מה שאינו מחזק.
הק’ על ר"ש שיש צד בראשונים שצריך בכור לשלם כפול (ולא רק מפני שעיבוד נכסים). צ"ל, אז, שעומד במקומו.
על רשב"ם של "מלווה שעמו" באר’ שיכול להיות שסובר כסומכוס, שכן פוסק.
יש שמבארים שיחלקו הוא מדינא (ולא מתקנה) (כן משמע מריף ורמבם, שלא מז’ שהוא תקנה). כן אומר רמה, ואומר שאין מוחזק, ואומר שאין בכור מוחזק, אף שממון בידו, כיון שממון בא לו מירושה מאב ועוד שאין טענת ברי (שסובר שהספק הוא מלימוד). לא כל כך קל להבין למה צריך שניהם. משמע שאי היה בכור ברי, היה הכל שלו.
יש לדון מה סובר תוס’- מי המוחזק. אפשר שתוס’ סובר שבכור מוחזק. נתיבות אומר שאחים מוח’. מביא ראיה שאין בכור מוח’ מגמרא לקמן שאומר בשנים שחולקים איזו מהם בכור שאין מוציאים בלי הרשאה. מה שיכולים אחים ליקח, ולא צריכים להניח לשניהם לחלוק, משמע שכל אחד מוציא מן האחים. אין הכרח לזה מתוס’ זה.
בביאור ספק של מלווה שעמו, בארנו רשב"ם ור"ג. רמבם וריף אומ’ שספק הוא אם אומרים שכיון שהוא ביד בכור, מוחזקת היא. קשה, שצ"ל ימצא לאב. משמע שאף שלשון תורה אומר שצריך להיות ימצא לאב, אף אם אינו כן, של בכור הוא (ונלמד מקל וחומר מימצא לאב). אם כן, הדיון כאן הוא אם אומרים קו"ח או לא. רמ"ה אומר שדן אם נדרש מימצא לו, שאז נתמעט, או לתת לו, שאז לא יתמעט, שיכול למחול. מק’ ר"א למה יחלקו, שבכור מוציא לפי נתיבות (ולא משמע שהוא תקנה). אמר’ שבאמת נתיבות העיר כן, ואמר שבכור נח’ מוציא כיון שחלק בכורה חיוב על אחים, כמו חוב. אמר’ שאולי אף בנתיבות הוא מוציא רק מפני שפשוטים חייבים ליתן, אבל כאן כבר בידי בכור. אמר’ שנתיבות מחו’, שקרא משמע שחלק בכורה מתנה מאב. גם אמר שתלוי מדרשת לתת לו, שלרשבם מוכרח שנותן הוא אב. (ורמה סובר כרשבם.) אמר’ שי"ל, כמו נתיבות, שהוא מתנה מאב, ובכור מוציא מחזקת אב (אם זה תפיסת הבית).
אם לא ידוע מי אח, פוס’ משמעים שצריכים הרשאה. לנתיבות, זה קשה. צ"ל שהוא מפני שאין ספק מוציא מידי וודאי. אז, אין ראיה לנתיבות. כן היה ר"א אומר בבכור לבאר למה אחים מוח’. מחו’ שאומרים כן בבכור, שבדרך כלל, כל זה רק שאין ידוע שיש לו בוודאי כלל. כאן, בוודאי יש לו חלק פשיטות (וזה כולל כל הנכסים, אלא שאי אפשר כיון שאחים אחרים צריכים להשיגו). אומר"א שהוא סיבה חדשה, ולא רק ירושה חזקה. לזה, יש לומר שנתיבות אומר כפוס’, ורק סובר שאין סברה זה בבכור, אלא בפשוט.
לבאר רמה, אמר’ שיש לומר שסובר כר"א, שהבעיא הוא שהוא ספק מוציא מידי וודאי. כאן, אינו ספק בכור (ורק לא ידועים אם זה סיבה להשיג אלו נכסים), הוא ספק שקול, ולא ספק מוציא מידי וודאי. כן משמע מרשבם וריד, שמשמעים שיש אותו סיבה להרשאה כבפשוט.
מחלק במתנה יכול להיות במתנת שכ"מ או בריא, אבל לשון "בפיו" משמע שהוא בשכ"מ.
מבואר שלולי בעיית מתנה על מש"כ בתורה, היה יכול אב להתנות. מחודש שיהיה לו אותו כוח, שאין נכסים לאחר מיתה שלו. מבואר שאינו זר לנכסים; או מפני שהם בחזקתו לאחר מיתה או מפני שלפני מיתה היו שלו, וזה הגורם לירושה.
יש שני חלקים לדין תנאו בטל- יש מה שקידושין חל, ואין בו אותו שינוי שעליו התנה. אפשר שאלו שני חידושים, שתנאי בטל לשום  סיבה ומעשה קיים כיון שרק מפליג בדברים, או שהם חד חידוש, שתנאי בטל כיון שאינו כבני גד וראובן, ומעשה קיים כיון שלא התנה כהלכתו.
יש שמשמעים ש"תנאי" של מתנה על מש"כ בתורה הוא, בפשטות, תנאי ממש, כמו בשאר. קצות סובר כן בהנחה ראשונה; מקשה על סילוק של מה שיש לאדם ליקח, שאומר שלכאורה, לא יהיה בכלל "מתנה… ,” שאינו תנאי. צריך ביאור למה יהיה נוסח תנאי שייך לדין זה. מביא קצות מגמ’ שלנו ראיה שאין צורך לאותו לשון. על כעין זה, רק דיון שני (מה שאין אותו שינוי) שייך. רע"א (משניות פאה) גם כן יש לו סברה חיצונה שזה רק כשמתנה. משנה אומר שמי שקוצר ואומר שהוא על מנת ששכחה שלו, אינו שלו. מפרש ירושלמי שהוא מפני שמתנה על מש"כ בתורה. מק’ רע"א שאין תנאי כאן- בין כך ובין כך קוצר. שוב מסיק שכלל זה הוא אף אי אינו אומר תנאי. מביא ראיה מסילוק בעל מירושת אשתו, שאומר גמ’ שא"א לפי הצד שיורש מדאו’ (עיין שם בכתובות). נשאר בק’ למה אין אומרים שאין לשון תנאי ב"על מנת שאין שאר… ," שרק עושה שאין חלות שאר (כמו במשנה פאה). אז, קושיית תוס’ שמניח שהוא תנאי (אומר שצ"ל שכפל תנאו, שצ"ל תנאי, ומק’ איך יחול כיון שחייב בשאר) קשה.
תוס’ מק’ למה צריך מה שמתנה עמש"כ בתורה לאמר שאי אפשר להתנות על נזירות שלא יאסר ביין; א"א להתנות כלל כיון שאינו בשליחות. מת’ שיכול אחרים להק’ קרבנות. הק’ רע"א ממה שיש בנדרים תנאי. רח"א שדיני תנאי נלמד ממה שצריך "האדם בשבועה.” אז, אין צורך שיהיה כתנאי בגוב"ר. לבאר תוס’ אומר שמה שאומר תוס’ שמתנה עמש"כ בתורה הוא מדין תנאי הוא מפני ששווים במה שבשניהם משנים חלות. אז, צריך לימוד מתנאי ממש, שרק בזה יש חידוש של שינוי חלות. (העיר’ שק"ק למה יחול כיון שלא היה לו דעת אלא אם דבר קורה.) חידוש הוא לומר שיכולים ללמוד שתנאי זה יכול לשנות את החלות כיון שיש לו משפטי תנאים, שלא גילה דעת שלא רצה בשאר, ורק גילה דעת שרצה לתלות. לגרי"ז, יהיה נמצא שאף שכשתנאו קיים, אין אדם משנה דיני תורה אלא במשפטי תנאים. קשה, שיש ציורים (בקצות וכדומה) שמשנה דיני תורה בממון בלי משפטי תנאים, כמו שהזכרנו לעיל.
נראה לומר נגד גרי"ז שרע"א וקצות, לכאורה, לא חשבו שאם קיים בממון צריכים תנאי לעשותו; חשבו רק שר"מ סבר שרק על ידי תנאי אי אפשר לשנות דין תורה. אז, בלי דיני תנאי, חשבו, יוכל לשנות. מחדש שגמרא אומר שאף בלי תנאי יש צד שלא יחול. המס’ הוא שכיון שיכול לשנות, אינו נחשב נגד מה שכתבה תורה. אז, יש לבאר שתוס’ סובר שכיון שאומר נוסח תנאי- ורע"א מק’ למה אין אומרים שדי כיון שגילה שלא רוצה חלות- צריך דיני תנאי. קשה איך מקיימו על ידי תנאי, שכיון שאינו כאומר שלא יחול חיוב שאר, יחול שאר. רש"ר אמר שכשאמר גרי"ז זה, הק’ משאר ציורים, ולא השיב. אמר’ שמואל שר"ש אמר שתנאים עושים כן כיון שחלות שסותר את עצמו אי אפשר לחול (ולכן אין חלות בגלגל החוזר). כאן, אם יחול, יהיה שאר, ולא יחול, ולא יהיה שאר, ויחול… . גרי"ז אמר על זה, “נו נו.”
בדין מחילת בכור, מדייק קצות מאריכות רש"י שאם מוחל בפירוש, חל. נמצא שיכול לסלק את עצמו מחלק בכור אף מחיי אב. אי אפשר לפשוט לסלק את עצמו. יש ראשונים שאומרים שאינו דווקא, שאף אם היה מוחל, לא היה חל. קשה, שמבואר בגמרא לעיל שמח’ גמ’ ביש לו או אין לו לבכור קודם חלוקה הוא אי נחשב בעולם, אבל אם אינו בעולם, בוודאי אינו יכול לסלק את עצמו. אם כן, כאן, שבוודאי אינו בעולם, לא יוכל לסלק. קצות מביא ראשונים ודיונים ומוכיח שיכול למחול על חלק בכורה. על חלק פשיטות, לכאורה, אי אפשר למחול. אמר’ שלכאורה, משנה דן אף בחלק פשיטות (שאומר, “פלוני בני לא יירש…”). לכאורה, אז, שקו"ת של גמ’ על שניהם. אז, יש לדייק אף על חלק פשיטות, קשה, שקצות מודה שא"א על חלק פשיטות (או כיון שכבר הוא שלו או שלא בא לעולם). צ"ל שדיוק רק על בכור (ולכן נאמר אותו לשון). (מביא הג"א שאומר שירושלמי אינו כן. קצות אומר שלא מצא אותו ירושלמי. יש ט"ס כאן, והג"א ר"ל שבירושה (פשיטות) אינו כן.) קצות אומר שיכול לסלק את עצמו כמו שיכול לאחר מיתה. הק’ נתיבות שרש"י סובר שדין לאחר מיתה תלוי באי יש לו או לא, שאז אינו בעולם. אפשר לתרץ לראשונים אחרים שמה שלא יכול לוותר אם אין לו הוא שלא מניחים שמוחל כיון שאין לו. ר"א אומר שסילוק מחיים הוא על עצם שם בכור, ועל לאחר מיתה מסלק את עצמו מנכסים, ורק על שני יש צד שאינו אפשר לסלק כיון שאין לו נכסים. צריך לומר שאי אפשר ליורש אחר לסלק את עצמו מלהיות יורש. באר’ שיש דין בכור שחל רק לאחר מיתה. כיון שאין לו, יכול לסלק את עצמו לעשות שלא חל (כיון שיש כבר מציאות לו). אחר מיתה כבר חל שם בכור, ולא יכול לסלק. אינו כל כך קל להבין מה נעשה לבכור לאחר מיתה שהוא השם; לכאורה, שם בכור הוא שנולד קודם. גם קשה איך מסלק את עצמו משם בכור, שמציאות הוא, שנולד ראשון. נתיבות אומר פשט, וקשה להבינו ברשב"ם. בביאור רשב"ם, היה אפשר לומר שלא היה מחלה חל, אלא היה התנאת אב, אז, חל, דהיינו, שמה שלא חל הוא כיון שבן מעכב. כאן, לא יעכב. אז, אף על חלק פשיטות יהני (פרט זה נגד הג"א).
אמר’ שלצד ראשון צריך לומר שגמרא מק’ (אף) מחלק בכורה. כן מבואר באור זרוע. אין הוכחה שרק על בכור הק’. קשה, שעל חלק בכורה לא יוכל לבכר, ואם כן, בוודאי לא יוכל להנות, כמו שלא יכול לריב"ב. חולקים ראשונים אם "לא יוכל לבכר" הוא איסור או דין (שאינו חל). אם איסור הוא, אולי לר"י יחול, אלא שאף מי שסובר צד ראשון (חוץ מצד אחד המובא במאירי), יש בו גם כן דין (ובאמת, אם לאו הוא, קצת קשה מהיכי תיתי שאינו יכול (כמו "לא תוכל לאכול בשעריך.”) (רמב"ן משמע שהענין הוא שכיון שאסור, נעשה מתנה על מש"כ בתורה. צ"ב. לאחר כן מביא סיפרי, ששם משמע שמדייק מלשון "לא יוכל.”). גם קשה למה מקשה גמרא למה צריך קרא זה אם לא שיכול גבי שאר בנים.). אפשר לדחוק שק’ רק היה על חלק פשוט, אבל אמר דבר ששייך אף לחלק בכורה, אבל או"ז אומר בפירוש נגד זה. רשב"ם אומר שמתניתין נגד ריב"ב. ר"י מיגש חולק, ובאר שכיון שמשווה את הבכור, כולו בטל. היה אפשר לומר שאם משנה הוא כחכמים, לא דורשים "לא יוכל לבכר" (שגמרא אומר כן רק לריב"ב) כן, אלא רק אומר לאו (ויש לדון אם יהיה "אם עביד, לא מהני.” אינו נראה כן, שרק אומרים כן לרבנן כיון שאין צורך (ועוד שיש ראשונים שאומרים נגד זה). אז, מצינו צורך לומר שלא יבכר, ואז ידרשו כריב”ב. אז, יותר היה נראה שגמרא לא דן בחלק בכורה.
רמב"ם אומר שכשא"א לשנות ירושה, הוא מפני "חקת משפט.” קשה, שגמ’ מסיק שאף לר"י א"א, כמש"א גמרא. מג"מ אומר שגמרא רק אומר תירוצו לרווחא דמילתא. מאירי אומר שמש"א רמב"ם הוא נרמז במדרשים (אמר’ שפשוט שלא היה אומרו אם לא שהיה לו מקור).  לרמב"ם פשוט שאין לדייק כקצות, שכולו ל"ד. (אמר’ שאינו קשה לרמבם לומר דרשה שסובר שהוא יותר פשוט כיון שאין נפק"מ בין אותו דרשה שמצא למש"א גמ’.
עיין ר"י מיגש שהבאנו לעיל. ריטב"א כ’ שביטול רק קאי על חלק בכור, וא"א שכיון שבטל חציו, בטל כולו. מרי"מ מבואר שאינו יכול להעביר אף חלק פשוט של בכור, שאם לא כן, נאמר שכאן מעביר מחלק פשיטותו, ולא מחלק בכורתו. אפשר שכיון שמשווה אותם, כולם שווים לחלק פשיטות (ובפרט כיון שיש נפק"מ לראוי). זה מחודש, שלכאורה, חלק פשטות של בכור שווה לשאר בנים. חול’ ראשונים בזה בפירוש (בריטבא, שמביא רא"ה שסובר כן, וחולק). באר ריטבא באותו שיטה שצ"ל לו פי שנים, וא"א לסלקו כלל. אפשר שסיבה לזה הוא מה שדורשים פי שנים, שאז צריך בכורתו להיות חלק שני, ויש לו שם בכורה רק כשיש חלק פשיטות. אז, צריך להיות לו חלק פשיטות. אמר’ שלא נראה מסברה (שאין בעיה להעביר חלק בכורה על ידי זה). אלא, נראה שהביאור הוא שחלק פשיטות של בכור יש בו דיני בכור. (אמר’ שיש שני דינים בחלק פשיטות- פשיטות, ופי שנים.) על חידוש זה דנים הראשונים. לפי זה, אם יכול לסלק ראוי שבפשיטות. ציין ר’ לרש"י שאומר שאין טמטם ממעט חלק בכורה, אבל ממעט חלק פשיטות של בכור. זה לא נראה כמש"כ. רמב"ם כתב כרשב"ם ברב דפוסים, אבל יש כתבי יד (שמובאים בפראנקל) שגורסים שלא ממעט חלק פשיטות של בכור. יש שכ’ שחזר לומר כרשב"ם (יש סיבה לזה, שסוברים שכתבי יד תימנים, שבו חלק על רשב"ם היו כ"י ראשונים. מוציאים שכ”י של תימן הם קדמונים. גם יש הוכחה ממה שמוצאים שיש מקומות ידועים שרמב”ם חזר. מצינו בכ”מ לשונות מוזרות, והוא מוזר כיון שלא רצה לשנות כל לשונו (שקשה היה לכותבו), ואז שינה דינו עד שנעשה לשונו מוזר או קשה. כאן, יש לשון מוזר לבאר איך חולקים (כרשב”ם), שאומר “והחצי והרביע,” ומסתמא הוא שבא מלשון “והרביע.” כ”כ מדפיסי רמב”ם, ולזה הסכים ר’.). משמעות רמ"ה הוא שיש דיני בכורה לענין "לא יוכל לבכר" בפשיטות. אם כן, כאן היה צריך לומר נגד רשב"ם, אבל לא אומר כן. אפשר שדין "לא יוכל לבכר" הוא שצריך שיהיה בכור גורם לו ליקח יותר. קשה. רמ"ה מביא ראיה שיכול למעט מחלק פשיטות של בכור מדיון שדנים בו אחרונים (עיין בפסקי תשובה), והוא שאומר שכמו אם יש רק טמטום ובכור, טומום ממעט חלק פשיטות, אף כשיש פשוט עמו כן הוא. נמצא שסובר שאם אינו ממעט חלק פשיטות, הכל יהיה לבכור, שהוא הפשוט היחידי (ועל זה אומר שאי אפשר שבכור נוטל את כולו) מוסיף שאף שממעט, אז, אף חלק בכור, לעשות שאינו כולו, אין זה בעיה, שבלי טומטום, לא היה שום חלק בכורה. יש לדון מה יהיה אם לא היה לו למעט. כשאחרונים דנים בו, דנים ביותר צדדים, אבל אנו לא נדון בהם.
העיר’ שיש חידוש בספק מטמטום, שהיה זמן לידה, שבו היה יכול להיות הוכר, אבל בטמטום, אינו כן.
העירש"ש שמשמע מרש"י (יש שלש הוכחות: א.לא אומר רש"י שהוא רק בכור, אף שלא מבאר כן גמרא שם. ב.אומר סברה לאותו דין, ולא קרא. יש שדוחים שבא לבאר למה לא אומרים שהוא רק כשלא הוכר לעולם. ג.שע"מ גם מדייק מתחלת רש"י, שאומר, “כגון שני נשים של שני אנשים,” שאינו נצרך אם דן בבכור.) בבכורות שאף בבן אין כותבים הרשאה, ולא רק בבכור. לכאורה, ק’ שמגמרא משמע שהוא דין בכור, שכשאינו ידוע, אינו בכור. אם קאי אף על פשוט, צ"ל שיש סברה (שאי לאו הכי, צריך להיות שנלמד מבכור. אם כן, קשה למה לא אומרים דין טמטום בפשוט), וקשה למה צריך קרא לבכור. אפשר שקרא אומר דין של הוכרו קודם, ור"י חולק על ברייתא. דנים ראשונים בזה, שיש לדון אם "לאפוקי מדדרש רבא" רצה לומר מה שדרש מתחילה, או אף לבסוף (כריב"ב). מרשבם כאן נ’ שדן בזה, שצריך להוסיף שרק נגד דרשת רבא מתחילה, שרק נוקטים הכי מסתבר. מסיק רי"מ שרק בא לאפוקי מה שדרש מתחילה (כרשבם). מה שכותבים הרשאה גבי הא דשמואל מוכיח, לכאורה, שכותבים הרשאה על ספק בכורה. צריך לומר שדין גמרא הוא רק אם עירבו קודם. אמר’ שהשלמה מביא שרי"מ אומר שאין כותבין הרשאה לפשוט. שיט"מ ומאירי מפורשים נגד זה. יש שמעירים שאם כותבין הרשאה רק מפני שכבר הוכרו (במעשה של שמואל), רק מי שכבר אמר עליו בכור יכתב הרשאה, שהיה מוחזק וכבר ידוע והוכר. רי"ט אלגאזי אומר שאולי אם מן הסברה יודעים שאין הרשאה לבן, אולי ספק מציאות וספק דין חולוקים, שבספק דין, לעולם עומד ליפשט. אז, אומר, לשון "זה לזה" יותר טוב (כמה שבארנו לעיל).
נצי"ב כתב שרשבם סובר שאין פשוט כותב הרשאה (כרשי). רשב"ם אומר שבכור יכול לכ’ הרשאה רק מפני שיש לבכור קודם חלוקה, ואז פשוט (שסובר רשב"ם שאין לו) לא יכתב הרשאה. (חלקו אם יכולים לכתוב הרשאה על מה שאי אפשר ליתן. תלוי על זה אם צריך יש לו קודם חלוקה או לא (כתוס’).) זה לא מהני ברש"י, אלא ברשבם (נציב מיחד שני השיטות), שרש"י משמע שהוא שווה לבכורה לזה (ואז, “זכה… " שאומר רש"י הוא מה שהיה ידוע, ולא מה שבא לו עד שיכול ליתן אותו).
(לא קל להבין סברת רש"י, אבל הוא כמו "כשנולד, וידענו מי הוא, נקרא ש"זכה בנכסי אביו" או "זכה בחזקת בכור," שבא לו שם יורש ושם בן. אם לא ידוע, כאילו לא היה בן. זה- פלא!- מן הסברה. אפשר שאין ספק מוציא מידי ודאי עושה שאינו בן. אבל כיון שנעשה כבר בן, נשאר בן, ואז הוא ספק. (הזכיר’ רן שאומר שא”א לסלק מירושה כיון שכבר זכה בו לפני מיתה.) גד"א כ’ שרש"י לשיטתו, ואז מבארש"י באופן חלוק (וק’ בלשונות). רש"י בשבועות כ’ שהרשאה הוא רק על מה שכבר בא לידו (כמו חוב, שהיה לו כבר אותו ממון, אבל לא נזיקין. ויש לדון אם הוא כל כך פשוט לומר כן בנזקים, שאולי ממון הוא תמורת החפץ). לא כ"כ קל לדעת למה. אם כן, כיון שלא היה לו לעולם ירושה, אינו כותב עליו הרשאה. והוא שכל זמן שהוא ספק, אין ספק מוציא מידי ודאי. קשה שאף הוכרו קודם לא היה לו לעולם. (גם קשה איך מבאר מיעוט הקרא, שמקושיא זה, מוכרח שלא אומר כמש"כ, שממעט אף הוכרו.) באר שרק רצה לומר שהוכרו אחר מיתה (וק’, שיש לשונות של "לא הוכורו מעולם.”) צריך לדון מה נחשב בא לו, אם הוא שצריך להיות לו קודם חלוקה או לא. לולי זה, היה נראה לומר שכיון שהיה ידוע, היה לו דין ליקח. בביאור איזה דין בא לו (זה חוזר לסברה ראשונה) כיון שניכר מחיים צריך ביאור; הוא רק שיש לו שם יורש. מאירי דן אם פשוטים כותבים הרשאה, ומביא ראיה שכותבים מגמרא בכורות שמחלק בין שני בכורות שנתערבו שנולדים לשני אבות שצריך ליתן חמש סלעים לכהן שאם נמצא שחד אינו חייב, שמת בנו בתוך שנים, אם נתן לשני כהנים אינו חייב להחזיר (מיירי בשנתן ממון קודם ל יום. זה מהני אם ממון הוא בעין, ולחד אמורא, חל אף אם אינו בעין), אהל לכהן אחד מחזיר. גמרא אומר שהוא רק בבא בהרשאה. יש לדון אם תובע פקדון (אם ממון צריך להיות בעין) או חוב (אם אינו צריך). מזה ראיה שאף אי לא הוכרו, כותבים הרשאה. דוחה שאולי הוכרו. עוד אמר שאולי חלוק כיון שאבות הוכרו, ורק בנים לא הוכרו. צריך ביאור מה אומר, שכאן כיון שמת, לא נודע, ולא היה הכרה בשעת תביעה כלל. אף שאומר סברה שמשמע כעין רש"י, צריך ביאור מה אומר.
רש"י בקידושין אומר ש"אינו נאמן" קאי על בן גרושה וחלוצה. רשב"ם אומר שקאי אף על בכור. קשה, שגמרא אומר שחולק בבכור. צ"ל שר"ל שמודים לחד ציור של בכור.
הלכה כר"י כיון שכן שלח להו ר"א (ואומר גמרא שהלכה כהני דברים ששלח להו).
רשב"ם אומר שדן במוחזק אחר להיות בכור בקול בעלמא. יש חולקים ואומרים שאף נאמן נגד עדים כיון שמניחים שאין האחרים בניו. על קושיית תוס אומר רשב"ם שסברה הוא. תוס’ לא אומר כן. תירץ ראשון של תוס’ נגד מה שאומר רש"י כאן מתי נאמן אב. אולי רש"י מודה לדין זה, וכשמוציא עדים, מוציא עדים שאחר בכור (למשל, הם תאומים). ריא"ז אומר שנאמן לומר שבן ממזר רק אם אומר כן על בנו, ולא לומר שאינו בנו (לומר שאינו בנו) (אפשר שחולק כיון שגה"ח הוא. דימה רבי לגמ’ יבמות גבי אומר שהוא גוי). לריא"ז, אז, אי אפשר לומר כתוס’. אולי כן סובר רש"י (ואולי לכן אינו נאמן נגד עדים). (קצות מביא ריא"ז זה, אבל לא מביא כמה ראשונים כאן שאומרים כתוס’ וחולקים על ריא"ז.)
אמר שעבדו הוא, נאמן לומר אחר כך שהוא בן, שאפשר שאומר שמשמשו כעבד, אבל לא להיפך, שאין אדם קורא עבדים בן. רשב"ם אומר שהאמינו תורה לומר שהוא בנו, דכתיב יכיר, וכיון שהגיד… נמצא שיכיר כולל אף אמירה שהוא בן. יש לדון, שהוא גלגל, שרק נאמן אם הוא נאמן (ועוד שמוחזק להיות שאינו בן). יש לדון אם אומר שנלמד מסברה או שנשמע מקרא (כן אמר’ שהוא מסתבר). יש דנים אם  "כיון שהגיד… " הוא ממש או לאו דווקא. עיין רע"א שמביא רשב"ם על משנה שיכול אדם לומר "זה בני" לירושה וליבום. שואל גמרא שירושה פשוט. מבארשב"ם שפשוט כיון שיש לו מגו. זה סותר מה שאומר רשב"ם כאן. חלקו ראשונים בדין זה. תוס’ שם כתב שנאמן רק אם ידוע להיות בנו. גמרא אומר שיש חידוש לפטור את אשתו מייבום. מק’ שכבר יש משנה. שם דן. מבאר שנאמן לפטור כיון שבידו לגרשה. העיר קצות שאם נאמן לירושה מפני דין יכיר, קשה למה לא אומרים שזה מהני לייבום. תוס’ מק’ מהי"ת שנאמן לחללו. לתירוציו, אפשר שאין לומדים מזה לדין אחר (יש לדון אם הם שני מובנים חלוקים או חד דין). לרשבם (שהוא מסברה) הוא חד דין.
גמרא בקידושין אומר ששלש נאמנים על בכור: חיה אם ואב. חולקים אם נאמנות אם וחיה מדרבנן או מדאורייתא. ראש סובר שהוא מדאורייתא, ושנלמד מנאמנות אב, שנאמן כיון שהוא היודע. קשה, שאם בתחילה אם וחיה הם היודעים, ולא אב, קשה איך אב נאמן אחר כך. אפשר שיודע כיון שאמרו לו. קשה, אז, לצד שהוא מדרבנן. היה לראש לומר שזה המקור (ממה שאב נאמן כיון ששמעו מהן), ולא שלומדים מאב. צריך לומר- אם לא אומרים שאב נאמן אף שבדרך כלל אינו יודע, ודנים כשיודע, אלא שאז ראש קשה (איך לומדים ממנו)- צריך לומר (ועיין בש"ש) שנאמנות של יכיר אינו מצריך ידיעתו מעצמו, אלא אמירתו ומחשבתו שהוא יודע. על כל פנים, נמצא שלראש, יש סברה לדין זה, ואינו רק גזה"כ. אפשר לראש (כן אומר טור שסבר, אבל קשה לדעת מה אומר בי"נ ובתשובה) שנאמן לומר זה בני. צריך לומר, אז, שמניחיים שידע בזה.
גר"א אומר שמקור לומר שאדם נאמן על מי שאינו מוחזק להיות בנו הוא מה שאומר, “זה בני בכור.” גבי ממזר, משנה רק אומר, “בני זה… " העיר’ ששם אומר שאינו נאמן (שהוא חכמים, ור"י שם חולק). אז, אפשר שאומר כן לרבותא.
אם רשב"ם סובר כראש, אולי מובן למה סובר שאפשר ללמוד מסברה, שאף על פסול זה הוא היודע. (עדיין ק"ק, שאין לומ’ איסור מממון.)
אם מקור לדין ממזרות הוא כצד ראשון של תוס’, משמע שאילו לא היה נאמן לעשות שאר ממזרים, לא היה נאמן לומר שזה בכור, ולא היינו פולגים. אם נאמן על מי שאינו בן (נקרא לזה שיטת רמבם), לכאורה פשיטות גמרא קלד הוא מחמת יכיר. יכו"ל שהוא פשוט אף לרבנן (שיכו"ל בצריך היכר). ק’ למה חלוק ירושה מייבום. אינו נאמן לייבום, אומר שמעתתא, כיון שנאמן רק לענין דין בניו, ולא דין אשתו. נמצא, על כל פנים לרמבם, שפלגינן בזה (שעדיין אומרים שהוא בכור). אפשר שחול’. העיר’ שראש אומר כצד ראשון שבתוס’, ואף שאולי אומר כרמבם. חד מהם בתוספותיו, ואז אין להק’ סתירה.
גמרא כתובות אומר שאם אמר על אחד שהוא בנו וכהן, אינו נאמן לכהנו. לתוס’, אינו מחמת יכיר, שאינו מוחזק לבן. כיון שאינו בידו לכהנו, לא נאמן. לרמבם, מק’ קצות שהו"ל להיאמן. ר"ש מוסיף על ש"ש שאף אם נאמן מיכיר לבן, לא עושה את עצמו לאב, אלא בנו לבן. ממילא, אין נאמנות בייבום. על פי זה, אומר שצריך להיות אב להיות נאמן לומר שהוא כהן, צ"ל אב, שרק אב נאמן. אז, לא נאמן, שנאמן על מי שאינו מוחזק רק לומר שהוא בן. א"כ, לא יאמן לומר, “זה בני בכורי.” ק’ שלא יהיה נאמן על זה. רש"א שאולי רק אומר שהוא בנו וכבר ידוע שהוא הגדול. לא משמע כן מרמבם. דנים אם יכול אדם לומר שאחד בנו ויירש אותו. לכאורה, פלא הוא לומר שמהני. לר”ש, לא קשה. בממזרות, לכאורה, פשוט שאינו יכול לעשות כל אחד שבעולם בנו וממזר. אפשר לומר כמו ר"ש בדרך יותר פשוט שאין אדם יכול ליתן לעצמו נאמנות. אמר’ שך שא"א שיכול אדם לומר זה בנו וממזר הוא שאם כן, יכול כל אדם לעשות כל אדם ממזר. יש לדון אם לא אומר שהוא בנו, וממזר, אלא שהוא בנו, ולכן ממזר. כ’ נמו"י שאומרים שנאמן לומר זה בני להכשיר (כמו ארוסה שנתעברה). קצת צריך ביאור למה לא יהיה נאמן. משמע שהוא שרק נאמן לפסול, שרק על זה יש קרא. בשער יושר, יש צד כזה לר"ש (לבאר למה א"א לומר, “זה בני וכהן.” מסיק נמו"י שמקו"ח מכוח לפסול נאמן. אומר ר"ש צד שיש ראבד שאומר שזה בני נאמן רק לענין ירושה. לא מוכרח. יהיה מחודש לומר כן. צ"ל שני שדין ירושה וייחוס הם שני דינים חלוקים, ונאמנים בציורים חלוקים. יש עוד בעיות. לכאורה, כמו שנאמן להכשיר בן ב"זה בני,” כך נאמן לפוסלו כן. לזה, נמצא שכל ממזר יכול לפסול כל אחד שבעולם לומר שהם בניו. זה דין מוזר. יש ראיה מרמבם, שכשאומר הלכה שביחוס, אומר שאדם אומר בני זה ממזר, אבל בירושה אומר שאומר זה בני ויורש הוא. משמע שרק נאמן לפסול אם כבר ידוע שהוא בן. גם אומר שאין אדם נאמן לומר על אשה שזינה שוולד שלו, שלא יודע, שאולי של אחר הוא. משמע שבלי זה, היה נאמן. שם, יש נאמנות רק כיון שבדיבור אחד עושה אותו ממזר לומר שעמו זנה האשה. לעיל, הק’ על ר"ש למה נאמן לומר זה בני ובכור הוא. לשון רמב"ם ולשון קרא (שאומר שמבכר, ומיירי אף כשאומר שבנו הוא) לא משמע כן. היה אפשר לומר שזה בני ובכור הוא חלוק מלומר שממזר הוא, שכאן הוא הגדה אחת, שכשאומר זה בני, מגיד על עצמו שהולידו, ועל אמו שהיתה חייבי כריתות עמו, אבל זה בני בכור רק אומר חד דבר, והוא שהוא בכורו, וממילא הוא בנו (נראה שהוא מפני שבכור הוא רק קרק’ של בן, ולא יכול להיות נאמר בפני עצמו, דלא כממזר.) טור פוסק כרמבם אומר שיכול לומר על מי שאינו מוחזק להיות בנו שהוא בכור. אולי אומרו כן כמש"כ לבאר שהוא דיבור אחד.
משיטת בה”ג (מפורש כן מבה”ג, אבל כנראה יש שלא גרסו כן, שכתבו שרק משמע כן מבה”ג) נמצא סברה הפוכה ממה שאומר תוס’, שאומר שאילו לא היה נאמן על ממזרות, לא היה נאמן כלל. לבה”ג נמצא שכיון שנאמן על זה, נאמן על זה. לכאורה, בה”ג רק אומר שרק בזה פוסקים כר”י, ולא שרק בזה אמר כן ר”י (ואז, לא קשה מה שאין ציור כזה בבן גרושה). לכאורה, מה שאומר כן הוא מפני שמשנה גבי ממזר משמע כרבנן.
אמר’ שלכאורה מוכח שיש מקומות שלא פולגים. נאמן אדם רק לפסול בניו, אבל לא בני בנים. ממילא, כשיש בני בנים, אומר גמרא שלא נאמן על בניו. זה קשה, אז, לרמב”ם. באר”ש שהכא לא פולגים (אמר’ שאולי יכיר חלוק משאר נאמניות לענין פלגינן) כיון שכאן חד דין הוא, שזה נובע מזה- דין בן גורם דין בן בן, ולא ששניהם נגרמים מחד דבר. בייבום, אינו כן, שמה שבן יורש אינו גורם פטור ייבום. רמבם אומר שאם אמר אדם על בנו שהוא ממזר, נאמן. אם אמר על עצמו, נאמן לחומרא (שוויה אנפשיה חתיכא דאיסורא) ובנו כמוהו. קשה למה יש לבנו אותו דין, שלא אומרו על בנו (ואם יש בזה יכיר, היה לבן להיות ממזר ממש, ולא כמוהו), ואין לו שום נאמנות עליו. באר”ש שאי אפשר לפלוג כאן. אז, אומר שנאמן על בנו מחמת יכיר כפי ערך שאין סתירה. צריך לומר שנאמנות לחצי כזה אינו סתירה. צריך להניח, למה שאמר, נגד האומרים שאין “שוויה... “ נאמנות, אלא כעין נדר.
אמר’ שהיה אפשר לומר שלא חולק תוס’ על רמבם, אבל דחוק. גם ק’ שאומר רבמם שאם אומר אדם על אחד שאינו בכור, נאמן לעשותו לא יורש וממזר. אומר שאף כשלא נאמן לממזרות (כמו אם יש לו בנים), נאמן לירושה. זה דומה מאד לציור של תוס’ שבו אומר שלא פלגינן. רמב"ם אומרו בתורת חידוש. אולי ק"ק למה אינו פשוט, שלשיטתו מבואר מגמ’ שפלגים. יל"ד שאותו דין של רמב"ם אינו כל כך פשוט.
* Footnotes
[fn:1] אור זרוע משמע כשני. היו שני לשונות במה אמר רבי- אם סבר שחול’ אי יש קנין או אי יש מעשה קנין.
[fn:2] לא מבואר מה אמר.
[fn:3] העיר’ שבחידושים אמר רשב"א כרש"י.
[fn:4] אולי לכן אינו בעיא כל כך שסתר את עצמו לומר כרש"י.
[fn:5] לא הבנתי, שדן במלווה שלאחר מיתה, כמו כופר. קשה יותר על תו
