** העיר תוספתא מדרש
’ שההו"א שלא יכול כה"ג לפרוע ראש סוטה מוזר .כ’
שהיו מגרילים מי היה צ’ לגלות ראשה, ואף אם נפל על כה"ג, היה צריך. (וכן
אומר שהיה ה’ אומר קו"ח ממה שמלך עוסק בסוטה שאף כה"ג יעסוק.) נמצא שהוא קצת בזיון, ואז יש צד שלא יכול כהן גדול לעסוק בה.
** רש"י רש"י ר"ן ר"י לוניל רמב"ם רב נתן בר’ מאיר ספר מאורות רמ"ה העיר’
יש לדון למה כה"ג יפרם למטה; הא אינו מקיים בזה קריעה. לשון
(“הלכך מותר בכה"ג") משמע שאינו חיוב.
(כת"י) במ"ק (כו:) כ’ שאינו מצות קריעה, ורק עגמת נפש (כמו מה שקורעים בגדי קטן). נמצא שיש ענין בקריעה זה.
במ"ק (שאינו ר"ן) כ’ שכיון שאינו חייב באבילות, הוא רק זכר לכבוד אביו. זה דומה למש"כ רש"י.
כ’ כמו"כ.
כ’ (אבל- ז- כו) ש"כה"ג חייב בכל דיני אבילות, אלא שאסור לו לקרוע בגדיו למעלה…..” זה נגד ר"ן ורי"ל. גם כ’, “אבל חייב לקרוע על מתו. הקורע [שלא במקומו] לא יצא, אלא כה"ג שקורע למטה.” משמע שמקיים בזה קריעה. גם משמע כן מרבו של רמב"ן (
).
(חבר רמב"ן) כתב בשמו על גמרא שאומר שלפעמים הכל צריכים לקרוע שכיון שמצינו שקריעה למטה נקרא קריעה לכה"ג, מהני אף לזה. לכאורה, משמע כרמב"ם. לרש"י, שהוא רק היכר, בודאי אין ראיה. לרי"ל, אין הוכחה, שאינו דין קריעה.
(סנהדרין יט) כ’ שכה"ג חייב בכפיית מטה. משמע שיש לו דיני אבלות (אבל אולי עדיין אין לו דין קריעה).
שכן משמע מלשון "לא פורם כדרך שבני אדם קורעים,” ולא פטור.
** סה"ח מנ"ח רמב"ם תו"כ בגמרא תו"כ חסדי דוד העיר’
כ’
שאין כה"ג רשאי לקרוע על מת שימות לו. כ’
שמשמע ששלא על מת יכול לקרוע, ומק’ למקור. מביא ש
משמע שהוא אף אם אינו על מת. מביא רמב"ם אחר שמשמע כסה"ח. מביא אח"כ רמב"ם  שאומר שכה"ג מצורע קורע כיון שעשה דוחה לאו. משמע שיש איסור אף אם אינו על מת. באמת, נדרש כן ב
(ולכא’, הובא
כשאומר במ"ק (יד:) ש"והצרוע" מרבה כה"ג. יש מפרשים שמרבה אותו לפריעה.) בפירוש.
כ’ בשיטת ר’ ישמעאל שלא פורע כדרך שבני אדם פורעים על מתם. משמע שהוא רק על מתו.
כ’ שאולי מרבה אף מתו. לשון סה"ח לא משמע שבא לרבות, ואז לכאורה, עדיין קשה. סה"ח כ’ שכמו שקריעה למת צ"ל טפח, צ"ל כן לכה"ג לעבור.
שמה שגמרא משווה דין מת לכה"ג משמע שהוא רק קריעה על מתו. אפשר שכיון שלשון תורה בכה"ג ובמת (שנל’ מאזהרת קרא לאהרן ובניו) שוה (פריעה ופרימה). אם כן, אולי יש ללמוד זה מזה.
** רש"י טורי אבן זכר יצחק העיר’ תו"כ אונקלוס. העיר אב"א רבי ר"ש אורבך
(נדה לז) כ’ שאשה שהיא מצורעת וזבה משלחת קרבנות. הק’
שמצורע לא משלח קרבן.
(מג, מד) כ’ שמצינו כמה הל’ אבלות במצורע (כמו פריעה ופרימה; תשמיש המטה; כיסוי ראש). מצורעת מותרת באלו. משמע שאין לה אבלות של מצורע. אם נאמר שדין שילוח קרבנות הוא דין אבלות (שאין אונן, ואולי אף אבל משלח קרבנות), נוכל לת’ לרש"י.
שגמרא (מ"ק יד:) שואל אם מצורע ינהג צרעתו ברגל. מוזר מה ששאל זה; כל טומאה נוהג ברגל. משמע שהוא מחמת דיני אבלות.
כ’ ש"יטה ראשו [מצורע] כאבל.” כמו"כ אומר
’ שמעניין שואמר כן רק בדין שפם.
כ’ שטעם דין פריעה הוא כעין אבל. שאל
ל
שגמרא אומר שטומאת מצורע חמור כיון שיש בו פרו"פ. משמע שהוא מדין טומאתו. ת’ שאבלות מחמת טומאתו.
עפ"ז, פשוט שכה"ג מצורע צריך קרא לרבות כה"ג מצורע.
* Footnotes
[fn:1] אולי זה שייך למצורע חשוב כמת. זה אולי גם יכול לבאר למה הוא חומרא בטומאה (שאולי לכן טמא). לא נראה, שלכאורה, הוא כמת מחמת דינים אלו. גם אולי יש לומר (וצריך ביאור למה) שהאיסור הוא קריעה שעל מת.
[fn:2] לכאורה, יש לבאר, אז, לשון תו"כ על פי זה.
[fn:3] לכאורה, לא מצינו שממעט דין כיסוי שפם.
