רמב"ם פוסק שנח' ספק מגו' בעבד.
אין איסור בכ' קעקע עד שישרט ויכ'. אז, אולי מותר כאן. תוס' כ' שאסור מדרבנן. דן בדינו אילו היה דאו'. יל"ד מהו ההו"א.
יל"ד אם לא היה מוח' עבד שלו. משמע שהיה מהני, שנ' שניתן לה. כ"פ רמב"ם. מק' ב"ש מה לנו שמוח' שלו, שנניח שנתן. דנים בזה. אולי חוש' שהחליט שלא לתת, אבל אם לא הוכר להיות שלו, נתנה לו לתת. אז, יתן. אז, לא ית' אם של אחר הוא.
רמב"ם כ' שעדים חתמו על כ"ק. ק' ל"ל יכ', שלא יזדייף. ע' ב"ח (אילו כולו נכ' בקעקע, ועד לא נכ' בקרקע, נזדייף.
הק' ב"ש ל"ל פס' לעדות מדרבנן (אם עובר מדרבנן). אולי צ' הכרזה; דנים בזה. (ואם תאמר רק פוס' אחר עדות. וי"ל שהוא קודם זמן חתימה.)
מבואר מגמ' שא"א שקלף יהיה שלה, שצ' נ'. משמע שקלף חלק מנ'. (אולי טבלא חלוק, כמש"כ, אבל ק"ק, שר"א מביא מקלף (אבל אולי שם כ' בדיו).) (אפשר לומר ששניהם חלק מחפץ גט. רק צ' לתת לה יחס של גט של קנין אחד מהם. אבל לא נקרא נ' אם כבר יש לה יחס של קונה קלף. ויל"ד.) הומ"ל שכל דיוני גמ' הם משום נ'. אבל, פשטות גמ' לקמן מחדש חסרון כריתות, שלכן צ' לתת כל השור שעל קרנו כ' גט (פנ"י). (שם מק' בספקת גמ' במשייר בין שיטה לשיטה, אבל מניח שאין גליון (ששווה יותר) בעיה. ק' למה אין שיור פר כגליון. שאר העבד מחיה את היד ומחיה את הקרן. יש להעיר שקרן כשר אף אם מת, ואז ק"ק מה לנו שמחיה אותו. אולי הוא שהחיה אותו, וגדל הקרן. ר' ת' ששייר עיקר. קשה, שבי"כ ובי"כ לא מראה גירושין. אולי תלוי במה יקרה, אם תחזור האשה החפץ לו או לא. אם עיקר לבעל, מחזירים לבעל, וישלם דמי קרן. יל"ד שכאן נהנה מקרן, שצ' ראיה. לכאו', זה לא שייך לדיני ממון, ונכ' עוד ראיה.) נ' כ' פשט אחר למה צ' לתת כל העבד, אבל קשה.
רמב"ם כ’ שאילו לא הוח’ שעבד שלו, מגו’. ק’, שצ’ להקנות לבעל, וצ’ שבעל הק’ לה. ק’ למה נאמן, כמו שלא נאמנת לומר שבעל נתן לה. פ"ח כ’ שכשניתן לו לתת לה לגט, מס’ שיתן ולא שיאבדו. ת"ג שממ"נ עבד בידה שלה, שנתנה לו ע"מ שיגרש אותה (נאמנת לומ' כן). אז, מגו' בוודאי. לכאו', תהיה נאמנת לומר שנתנן לו לג'. לכאו', לא אומר כן כיון שאולי לא נאמנת לטעון ג', שמחדשת שהיא מגו', שאין מגו עוד, שאין גט אם לא נתנה לו. אבל, כאן, לא צ' מגו, כמו שנאמנת לומר שלא נתנה כלל. נמצא שמניח שכיון שזוכה בעבד, מניחים שנתן לה גט.
ב"י כ' שאילו היתה לה חזקה על עבד, כמו עבד קטן או נמסר לרועה וחז' של"ש אחר כ'(משמע שקצת מסופק), היתה מגו'. ק"ק שאין לאשה חז' בנכסי בעלה. י"ל שעל גט לא אומ' כן. ב"ש כ' שממ"נ שלה, שאף אם מנפשיה עייל (כמו שחוש' בגמ'), יש ראיה ששלה הוא. ק', שאם בא מנפשו, אינו ג'. משמע כת"ג. כמוכ"כ אב"ע. צ"ל שגט שלה, וגט הוא עדות שכיון שהיא שלה (זה מחו', שהומ"ל שיש הל' עדות רק אם מס’ שניתן לה), היא מגו'. (לכן לא חוש' לתנאי.)
מתוס' משמע שכ' על א"ה יאסר. תלוי מה נח' הנאה[fn:1]. לכאו', הנאה ר"ל שימוש כשצ'. גמ’ אוסר שחיטה בסכין של ע"ז רק בבהמה מסוכן. צ"ל שלא כל שימוש אסור[fn:2], אלא צ’ להעלות דמיו.
תוס' לא מבאר הו"א. משמע שלא צ' לבאר. צל"ד ב"אי עביד לא מהני." יש שכ' שזה הו"א של תוס'. ק"ק שחל' אמוראים. צ"ב ג"כ מהו הדיחוי. רע"א דן בו, אבל לא בפ' בתוס'. כ' שאולי לא מהני כיון שס"ר לא נעשים. זה לא ת' א"ה. (יל"ד, שלא נהנה, אבל נשתמש) ג"כ שרק אומ' כן כשמפ' מש"א תורה להיות שלא מהני. תוס' לא סובר כן. גי"ל שלא אומ' אי עביד לא מהני כיון שלא נעשה חלות כבר. עדיין בא"ה ק'. גמ' ביבמות כ' שלא יחלוץ בסנדל של א"ה, ואם חלץ, כשר, אא"כ עומד לישרף וכתתי מכתת. רש"י מק' שנהנה מא"ה, ת' שמצוות לאו ליהנות. שם, דנים בו ראשונים. מקש' שיש הנאה בהיתר לישא. ת' שחליצה מצווה, ולא מתיר, אלא שקיום מצווה עושה שמותרת. יש שת’ שאינו הנאת גוף. (יש גמ’ שלא משמעים כן.) (יש להעיר שבסכין ג"כ לא נהנה מגופו.) חל’ רשב"א ורן אם הנאת גוף בכלל מצוות לאו ליהנות. יש שכ’ שאף שעובר איסור הנאה, חל. כאן, לא חל כיון שעשה בו עבירה. לומ’ מגמ’ ר"ה. (אבל, ע"ש, שיש שתלו שם מפני מצהב"ע. ק"ק, שלא פשוט שלא יצא בזה מדאו’. כמו”כ, יש שסוב’ שהוא רק בקרבנות ומעין קרבנות.) משמע שמחדשים פסול חדש משם, שאין מה שגורם חטא מוציאו למצווה. תוס’ בע"ז כ’ במה שאין מקדש בא"ה. מק’ ששווה קצת, ות’ שאסור לק’ בא"ה, כמו מכירה. שם מוס’ שגם לא דומה לכסף של שדה עפרון, שבשד"ע כל שבא לידו יכול להשתמש במו בכ"ז. באר’ שכשאמרה תורה לק’ בק"כ, לא כלל א"ה, שהרי אסור. מסופקים אם אפשר, כיון שלא כ"כ דומה לשל נחשון. אז, הול’ אחר סברה שלנו שלא מהני. כך אומ’ ראשונים בביאור יציאת שופר. שם, יש רק סברה. הכירו איך חל חליצה, והכירו שאין סברה זה שייך שם, שלא היה עובר. נ’ שזהו הו"א של תוס’, שהוא סברה.[fn:3] יל"ד מהו המס’ ( למה כ’ איסור בכלל וכ’).
אולי צ’ שיתן גט, ואולי צ’ שאינו שלה. ע’ רמב"ן. ע’ טור בשם רמ"ה בב"א.
יש שמבארים שמס’ גמ’ הוא שחכמים הקנו.
ע’ בתוס’. רי"ד כ’ שצ’ מלוה לשעבד קרקע (כך תקנו בתוך תק’ שצ’ קול). שט"ה צ"ל של מק’, מל"פ.
רמב"ם פ’ שבמוח’ שהוא שלו, ספק. הק’ ר"ח ל"ל א"מ בוודאי. אילו מניחים שיש ע"מ בד"כ, י"ל שמסופק. אבל רמב"ם משמע שע”ח מהני כיון שמוכיחים על מ’, ואז ק’ שכאן אין עדים על מסירה. לכ’, אם עח"כ ממש, אולי ספק יהיה. כאן, אין סיבה לח’ שיש ע"מ ואין עדים אלו מוכיחים מ’. הומ"ל שמסופקים אם יש ע"מ, שלכת’ צ"ל. לא פ’ מה מת’, אבל שייך למה לח’ כוח שטר. אפ’ לחדש שיש ס’ אם יש עדות, ותלוי באם גט שלה. אולי אף שלהל’ שלו, כיון שמ"ק, אין מכריעין שלא נ’.[fn:4]
ק’ איך בעל מג’ א"ה, שלא מק’ (רש"י: אינו ברשותו. יש: אינו שלו.). אח’ כ’ שרק לא מק’, אבל מניח לק’. עד"ק כשמג’ בע"כ. אולי כיון שיכולה לק’, אינו נייר שלי.[fn:5] ד’ שאולי חס"כ. עד"ק ממג’ קטנה. ר"ש ת’ שכיון ששטר ראיה, נק’ ממילא למי שצ’ ראיה (אם לא עכבו).
גיטה וחצרה באים כאחד של כאן אינו כ"כ מחו’. אומ’ של"צ שמקום גט כבר שלה קודם נ’. אבל, לא צ’ כדי לומ’ שחצר שלה.[fn:6]
רש"י שם פ’ שיש קנין אגב; כאן דן בקנין חצר. י"ל ששטר הוא מצד מק’, ואז יש נ’. אבל, כשעשתה מעש"ח, צ’ שהוא מאגב אותו.
חל’ ראשונים אם קנינים מהני לגט. אולי רק מהני בהקנאות, ולא בקנינים. אם חל, נמצא שנתינה לידה לא ר"ל נ’ לידה אלא הקנאה. אז, ק’ למה צ’ גטו וידו. (לכאו’, סבר רבי שכיון שמילת "ונ’ בידה" ל"ד, לא נאמר שצ"ל שהוא שלה בשע"נ כדי לקיים נ’.) אפשר שרש"י סובר שכאן לא מהני בתורת קנין, וצ"ל נ’ (כיון שהוא מחמת קנין שלה). אז, צ"ל שרש"י סורב שיש שני אופני קנין.
ע’ בת’ תוס’. ריטב"א כ’ ששני אופני חצר לא כ"כ דומים כמו שני אופני שליחות. הונ"ל להיפך.
אביי מק’ שכיון שתורה הניח לבעל לגרש, צ"ל שהוא מג’. אז, צ"ל ברור שלא צ’ אשה. אבל, אם צ’ רצונה, לא מהני, כיון שמסייע. אכ"ק גמ’ מובן, אבל ת’ לא מובן, שמראה שמהני אף אם נצרכת. צ”ל שיש מינים חלוקים של ג’. (אף שצ’ לקנות חצר, כיון שלא קנתה לג’, לא בעיה.[fn:7] גי"ל שבשליח צ’ דעת בשעת חלות. גם ת’ שני צ"ב, שצ’ דעת כיון שאינה קטנה.
פוס’ לכא’ פוס’ מדאו’.
לייפות- מתוס’ משמע שלא צ"ל ליפות, אבל מרא"ש מש’ שצ’. רמ"א מביא ספ"ת שפ’ רק אם חותך הרבה יותר מכ’ הגט. אולי ר"ל, “הרבה, יותר….” פס’ שלכת’ לא יחתך כלום, שכן מש’ מבה"ג.[fn:8]
רש"י קצת סותר א"ע. בע"א פ’ ששקל ויהב שמא יקטם, שהוא קציצה ממחובר, שמשמע כר’ שמעיא.[fn:9] (גם רש"י כ’ שיכול לקוץ מקלף גדול.) רש"י כ’ שלא חוש’ שיקטם עציץ, שלא יפ’ אותו. אז, כר"ת הוא. אפשר שעציץ חלוק, כיון שנשתנה, ונעשה דבר חלוק. אומר מן המחובר כיון שלא משנה את העלה. ראשונים מק’ סתירה; צ"ל שלא מחלקים כך.[fn:10]
מק’ למה אומ’ רבותא דאביי כיון שאין הל’ כמותו.[fn:11] אולי החי’ הוא שלא כ"כ מס’ לקטם מנקוב, שיגדל עוד. גי"ל שלא גז’ בא"נ כיון שאז נגזר בכל ציור. מחובר חלוק, ואז גוז’ (לכן יותר מחו’ לאביי). גי"ל רבותא שיכול לתת עציץ (כ"א תוס’). (העיר’ שזה יותר מחו’ לר"ש, שכל החיבור הוא לקרקע.) כ"ז נוגע ללומדות של מחוס"ק. לשון גמ’ משמע שאם צ’ עוד מעשה לפני"כ, פ’. מח’ ראשונים, אז, תלוי כמה חשוב הוא קציצה או כמה חשוב צ"ל. (ר"ן מק’ ל"ל נח’ ע"נ מח"ק. ת’ שאין מעשה ניכרת.)
הק’ ב"ח למה חוש’ שמא יקטם, שכבר צ’ לפסוק יניקה. נמצא שלא עוקר מגידולו. ת’ שלא חוש’ שירצה לקטום בשע"נ, אלא לפנ"כ. אז, יקטם קודם פיסוק. ריטב"א כ’ שיכול לחתוך מעל שור מת.[fn:12] שו"כ שאף יכול להרגו. חי’ הוא כיון ששני מעשים מצטרפים להיות מעשה שעושה להגיע לקרן, כקציצה.[fn:13] שו"כ שאולי לא מהני אם מת, שבשע"כ לא היה יכול לתת קרן. לכאו’, בורא פ’ חדש. (לא מס’ שדן בלומ’ של מחס"ק.) אפשר שאינו בעיה במעש"ק, אלא בשינוי בין מש"כ ומה שניתן. אז, ק’ למה יכשר אם לא חתך קרן אלא מת מעצמו.[fn:14] אז, צ"ל שיש בעיה בדבר שמחוסר ק’. דיון ריטב"א ודיון ב"ח שווים.
ראשונים דנים בחותך קצת. חול’ ראשונים בשיטת בה"ג. מראייתם, רואים שלא צ"ל ליפותו.[fn:15] ראיה צ"ב, שמק’ רק ממה שרק מק’ משלש ספרים. מאירי דחה שלא קוצץ קודם נ’. דחה שעדיין נח’ ב וג’ ספרים.[fn:16] ג"פ פ’ שכל העומד, כקצוץ. אב"נ מק’ שכמו שאין פ’ יניקה ניכר, אי"ז ניכר. ג"ק שרק עומד לקצץ אחר נ’.[fn:17] י"ל שכיון שנתן ושייר, איגלאי שהיה עומד. בשנים ושלש ספרים, י"ל שלא נח’ חד ספר כיון ששל אחר באמצע. אם מחס"כ הוא שאין כ’ ונ’ על אותו דבר, י"ל שנשתנה הדבר מח’ שנשאר שלו. ק’ בריטב"א. רמ"ה מביא שאם כ’ גט בתלוש וחברו ותלשו ונתנו פ’. אולי זה ספק בירושלמי. רשב"א מכ’. מדיי’ כן ממה שצ"ל ח’ בתלוש אחר שאמר כ’ בתלוש. נמצא שתלוש וחברו מחובר. אבל, משמע שאם חברו אח"כ, כשר. כ’ שכיון שבבלי לא מסתפק, לכאו’, פשטו. הק’ פ"ח איך נביא ראיה ממה שלא דן בו, שמצוי. אולי זה פשוט לדון. (אגב, פ"ח מפ’ ירושלמי באופן אחר, וכ’ שסובר כרמ"ה, אלא מוספק אם תלוש ולבסוף חברו חבור.) יש דוחים שאמר חתימה בתלוש כיון שנוגע לשאר דינים (לומר שיש לח’ דיני כ’). גם דחה שהוא רק אם בטלו ונשתרש. לכאו’, פשוט שאין פ’ אם הבעיה הוא דמיונו. מרשב"א, אז, נ’ נגד זה. אלא, רק דן אם נח’ אותו מעשה בעיה כיון שלא נצ’. אבל, ק’ שרשב"א מביא אותו ראיה.
מתוס’, משמע שא"א לקנות בחזקה, אבל ב“ש כ’ שמהני לתוס’. ת“ג כ’ שלא מהני כיון שדורשים מ“ידה“ שצ“ל ניתן מיד ליד. צ’ הכנסה לרשותו, ואינו טל“ג, שהיא ממשכת מעשיו, אבל בחזקה אינו כן.
ת“ג כ’ שאם תלש עציץ, ושוב תלש עלה, פ’. מבאר בתוך ר"ן שא“א להיות הפ’, אבל פסיקת יניקה חלק מנ’. בנטילת עלה, אינו כן.
ירושלמי פ’ מחובר לקרקע כיון שלא דומה לספר. דנים ראשונים אם בבלי מודה לזה. רמב"ם סובר של"צ. (אולי לא דורש ספר, ולכן לא צ“ל מתקיים.) רש"י כ’ שפ’ כיון שמחס“ק. לא מבאר ל"ל יתן בלי קציצה. ראשונים מבארים באותו משנה שהוא מפני ספר או מפני ”ידה.“ מרשב"א משמע שצ’ דרשת מחס“ק, אף אם דורשים ספר או ”ידה“ (נ’ שסובר שהוא דרשה על חפץ. ריטב"א כ’ שאינו דרשה, אלא מצ’ נ’ ליד. ק’ ל"ל יעשה שקרקע בחצרה. י“ל כהו“א של או“ש.) לכאו’, דרשה שני קאי על נ’, וראשון על כ’. אבל, מרשב"א נ’ שהוא על נ’ (שאל“ה לא צ’ קרא למחס"ק) כ’ אור שמח שלרשי פ’ כיון שאם מחובל“ק, טל“ג. אף מק’ בשטר, שהוא קנין שלו, טל“ג, כיון שהיא משותפת בקנין הגט. אבל, אם נתן בחצר, והק’ חצר, יודעים שאינו טל“ג, אלא ששם צ’ שיתוף על חצר, אבל לא על גט. לא יכולים לק’ קרקע בחצר. שוב חוזר (אבל נ’ כ’ שאין קנין חצר בקרקע), וכ’ שיש ק“ח בקרקע. (מביא ראיה מעבד.) אז, מבאר שלא מהני כיון שצ“ל חפץ[fn:18] שיכול לג’ בע“כ, שכל פרשה דן בו, כיון שכ’ בו שלא מצא חן בעיניו, שמשמע שרק זה צריך. מחו’ לדרוש דבר מחו’ זה , שצ’ שחפץ ראוי לג’ בע“כ. לא נ’ כן מראשונים. אולי כן סובר רש"י, ולכן לא בארו רש"י.
לכא’, רש"י סובר כריטב"א; כיון שאינו דרשה, לא באר. ק’, שרש"י כ’ שאגב מהני. רמב"ן כ’ כעין ריטב"א ומש’ שלא צ’ לבאר כ"כ. מתחיל בק’ למה קרן של פרה מחוס“ק, כיון שיכול לתת גט זה, אבל רק לא באופן זה. לא מפ’. מצדד שרק בקרקע פ’ (ושאר צ’ גז’ מח’). שו“מ ירושלמי, ומבאר שאז צ’ כן שאל“ה, יתן קרקע, כמו מניח גט בחצרו וכ’ מתנה עליו. משמע שלא יהני כיון שאינו נ’. קצת מש’ מרמב"ן שלא צ’ מחס"ק במחב“מ. אולי דיון ראשונים הוא אם קונה חצר מחובר לקרקע (כיון שאינו בחצר, אלא הוא חלק ממנו).
כוונת רמב"ן הוא לבאר שמירושלמי, צ“ל שמחס“ק הוא אף אם אינו קרקע ממש, ואז יכול להק’ כמש“כ, ולא יכול לת’ כמש"א לעיל שגז’ הוא. לכאו’, לרמבן הבעיה הוא שכ’ צ”ל בדבר שראוי לנ’. ת’ שתלוי במח’. לכן, מביא ר"ח שכ’ שאם כ’ ולא מכוון לקצוץ, יכול לקצוץ. לרב האי, יל”ד אם לא קוצץ. רמב"ן כ’[fn:19] שהוא כשר. שו”כ שבפרה לא צ’ דעת, כיון ששיורו חשוב אצל הכל, ומשנה שמו. לכאו’, זה אותו פ’, שמה שעשה היה עשיית גט של קרן. כמו כן, שהפ’ הוא שבשע”כ אינו ראוי לגט בלי קציצה, כ’ רשבא להכשיר אם חיברו אח”כ. אבל, רק מח’ לת’, אף שרמבן מק’ מח’. אולי ספק של ירושלמי הוא אם מחס”ק פסול כיון שיש מחס”ק שפ’ או כיון שבשע”כ לא היה ראוי. גם אפשר שמסו’ אם נדחה או לא. אור שמח מביא גמ’ בזבחים בענין טהרת כהן בין זביחה להקטרה. יל”ד אם כל דרשה שווה בזה. ריטב"א דן בכ’ על קרן שאח”כ מת. לכאו’, זה אינו כרמבן, שאז כ’ אינו על מה שניתן. ריטב"א מוסיף שדיונים אלו הם רק בפרה, ולא בקרקע, ששם פ’. נ’ שהוא מפני שאין החפצא ראוי לגרש בו, ולא תלוי בהיות מעש”ק.
קצות כ’ שלא צ’ להק’ גט. מש’ ראשונים אינו כן. רש"י כ’ שקנין מהני; לכאו’, אין שני דברים מהנים. ראשונים מק’ שצ’ נ’ ליד. לכאו’, לא חול’ על עיקר דברי רש"י. יש ריטב"א שמשמע שקצות, וכ’ שקטנה מקבלת ק’ שטר, וכגט, לא צ’ לק’. ירו’ מסו’ אם מג’ בקנין מסירה. אולי דנים אם צ’ הקנאה או נתינה, או אם צ“ל כולא בידה. מאירי כ’ שמהני כיון שקנה. אבל כ’ שאגב לא מהני. לכאו’, הוא מפני שצ’ קנין של ידה. תוס’ כ’ שיכול לגרש במשיכה והגבהה, אבל לא בקניני קרקע. כ’ שרואים שקנינים לא מהני. ב“ש כ’ נג“ז. לכאו’, י"ל שסובר כעין מאירי, שצ’ קנין של ידה.
רש"י כ’ שאין כות’ במחובר כיון שהוא מחוס"ק. ק’ למה צ’ לקוץ. לכאו’, רש"י סובר שחז’ לא מהני, מטל“ג, ולכן צ"ל בקנין אגב (בהזורק), כיון שהיא קונה חצר בחז’. לרש"י ק’ ל"ל מק’ קר’ בחצר. י"ל שאין חצר. גי“ל שכיון שלא נותן כל קרקע, הוא חסר“ק, כמו אם משייר נייר (ע’ ראשונים). ק’ ל"ל נותן כל הקרקע.[fn:20] רמב"ן משמע שאפשר.
העיר’ שמעניין שרש"י רק מפ’ שהוא ר“א בר“ה. אולי סבר שר“ה הק’.
לדעתה דנפשה פ’ ר“ח שמוכרח כן בלומדות. לא נ’ כן מרש"י.
לרשי, ק"ק ל"ל מפ’ שהתנא של המשנה משתנה.
לכאו’, לא לכל דבר מהני גדול עומד על גביו, שלא יכול לק’ ולהק’.[fn:21] הומ“ל שמהני רק אם עושה פעולה. אבל, יכו“ל מעשה באלו. יש לחלק בין ציור שצ’ כוונה לחלות לציור זה, שרק צ’ כוונה למעשה. כמו“כ צ“ל בחליצה.
* Footnotes
[fn:1] אולי כשבא הנאה, בא מזה.
[fn:2] אולי אינו כדרך הנאה, כמוש אומ’ גמ’ בפסחים.
[fn:3] מה מוסיף על זה כל דאמר רח’ לא תעביד. גם צ"ב למה אומר שכמה מהני קראי נצרכים לאביי מחמת זה. ע"ש. אולי אותו הוכחה שיש לאביי שמה שאמר רח’ לא תעביד מהני גם יאמר נגד זה. ותחשב.
[fn:4] אם סובר ר"ח שהוא הכרעה, צ"ב ל"ל רק אמר שלא מהני כיון שלא נ’, ולא כיון שאין ע"מ.
[fn:5] גי"ל שאינו כ"כ שלו להיות בעיה בכריתות.
[fn:6] איני יודע למה, שהיא נשואה, ויהיה קה"פ לו. אולי כשבעל נותן אינו כן. אולי כשנותן ומק’, מגלה שנותן אף פירות.
[fn:7] יל"ד שאולי אף כשמקבלת רוצה קרקע. עכ"פ, נחית לגט.
[fn:8] אמר’ שאולי מש"א רבינו שמעיא בא לרש"י (יש שמביאים את זה מרש"י), ויש כתבים מתל’ רש"י שניתנו ברש"י.
[fn:9] קל לדחות שמחובר ר"ל כל דבר מחובר לו. אולי אז הוא מיותר.
[fn:10] או שחושבים שאף עלה נח’ שינוי או אין חרס נח’ שינוי.
[fn:11] תחילת ביצה.
[fn:12] צ"ב, שא"כ נאמר שדומה למה שכשר. אולי לא יכול להרגו, שזה מעשה, ואז לא דומה לדבר כשר שבידו. אבל ע’ לקמן. אולי צ"ל לא רק שמה שנותן דומה אלא שכל מעשיו דומים.
[fn:13] הניח ר’ שכשר אם שחטו. יל"ד. אולי זה רק מפני שדומה לפר חי, כיון שהוא פר. ויל"ד (וע’ ביומא).
[fn:14] ויש לדון, שאולי קרק’ של דבר הוא שנעשה בו מעשה חשוב ששינה אותו.
[fn:15] יש לדחות שרק ר"ל שהוא להנאת גט, ולא לקלף. גם יש דרכים אחרים לדחות באותו ראיה, שראיה לא מובן כ"כ. אולי יבואר לקמן, ואולי זה נוגע לכאן.
[fn:16] אם הענין הוא השינוי, י"ל שפ’ כיון שהוא דבר חלוק. אולי עשייתו עומד מעשה.
[fn:17] יל"ד שעומד כיון שעומד לתת לה. ויל"ד, שאילו היה פ’, לא היה עומד. אז, הוא גה"ח. ויל"ד אם לא עומד.
[fn:18] צ“ל שמניח שהחפץ נשתנה כפוסק יניקתו, אף שלא נח’ חסרון קציצה.
[fn:19] רבי אמר כן לפשטות, אבל נ’ שרמבן כ’ כן בפירוש.
[fn:20] אולי משנה לא מז’ כיון שלא מצוי. גי“ל שסדנא דארע"א חד הוא. גיל“ד אם יהיה בזה קנין חצר.
[fn:21] נראה שאולי הוא מפני ששם צריך לבחור, ולא רק לחשוב. לכאו’, אם אחר אומר לו מה לעשות, איך יעשה שיבחר יותר טוב. ויש לדון בזה, שהיה אפשר לומר שבחר, על פי מה שאמר חברו, שעכשיו רצה כן. ותחשב.
