** תוס‛ ר“י
כ‛ שיש לגט שנים עשרה שורות. מביא שני מקורות לזה. יש שמביאים פשט של
באופן אחר, שרק שלש מן השורות הם נוספים (שצריך שורה בין פרשה), וכופלים פי ארבע.
** רי“א חבר גר"א
גם הז‛ רבי שנקרא גט מפני שיש בו יב‛ שורות[fn:1], וגט בגימטריא יב. עיין ב
.
כ‛ שנקרא גט כיון שג‛ לא קרוב לט‛ בתנ"ך[fn:2][fn:3], ואז מורה על ההפסק.[fn:4]
** רש"י
כ‛ ששליח להולכה אומר ”בפני…“. מקורו הוא שהבאת אשה, שמק‛ גמ‛ שכיון שבא גט לידה חל. יש כמה פשטים:
1. מבאר ר"ן ששליח לקבלה לא צ"ל[fn:5], שכיון שגט חל מיד (לא היה זמן בין נתינת בעל לחלות)[fn:6], לא יערר בעל[fn:7]. ר“ן, לשיטתו, סובר שחששות של גמ‛ הם רק שיערר כן בעל. רש"י לא נ‛ כן; אז, ק‛ לשיטתו.[fn:8]
2. פנ"י מבאר בגמ‛ לקמן שיש נאמנות זה רק כשעושה ג‛ (שהוא זמן חשוב, ולא ישקר[fn:9]). עפ"ז, יש לבאר רש"י. (תלוי במח‛ ראב"ד ורמב"ם, שחול‛ אם צ‛ קיום גט במקום שא"צ ”בפני נכ‛“ או לא. ריב“ש כ‛ שרש"י סובר כראב"ד.)
3. מהר“ם שיף משמע שתקנת האמירה הוא חלק מנתינת גט, ורק כשיכול להיות כך, אומר[fn:10]. אז, שליח לקבלה, שאינו בא לב"ד בשעת חלות, לא אומר.[fn:11]
** ר‛ זעליק הרב מסלונים
כשהיה
קטן, שאל לו
לראיה לרש"י. הביא ר"ז ראיה מגמ‛ לקמן שאומר שמי שאינו יכו"ל אמירה זה אינו"צ לאמרו. גמ‛ מפ‛ שמיירי בפקח ונתחרש. לא גזרו רבנן שמא ישכחו, שלא שכיח. לכאו‛, לא שכיח כיון שאומר מיד אחר הנתינה. אילו היה מקבל חייב לומר, היה שכיח, שיש זמן רב לו להתחרש.[fn:12] אחר שאמר כן ר“ז, נשק אותו הרב.
** תוס‛ רמב"ן
מניח שכיון שכבשת עולי בבל קדשו, עליו תלוי דיני חביבות א"י[fn:13].
מצדד לחלק שאולי גבולות א"י או כבישת עולי מצרים עושה דיני חביבות.[fn:14]
** רש"י ש“ך [fn:15]
מבאר כאן איך מקיימים שטר. לא כ‛ אופן של דמיון כתיבה. אולי לא מהני כאן;
כ‛ שהוא מדרבנן (ואף שקיום הוא רק מדרבנן, החמירו בגט להצריך קיום דאורייתא).
** גמ‛ רוב ראשונים יש
מפ‛ למה צ‛ אמירה. רבה אומר שהוא מחשש לשמה, ורבא אמר שהוא מפני שקשה למצוא עדים לקיים. שוב, אומר גמ‛ שרבה אף מודה לרבא.
פוס‛ כרבא, אבל
חול‛.
להו"א של רבה, המשך המשנה ק"ק (למה מז‛ קיום). אולי אף לזה, יהני לקיים[fn:16].[fn:17]
** תוס
יל"ד אם מש“א
‛, ”לא שבקת…“ הוא סיבה או ראיה. משמע כשני. לראשון, ק"ק ל"ל כ"כ לחלק בגט ובמלווה. יל"ד למה אינו הסיבה.
יש שכ’ שהיינו אומרים ל"פ. אמר’ שאינו ל"פ, אלא גדרו וקבעו גדרם לכל.
** תוס’ יש תוס’
מסיק שגט א"צ קיום ושאר שטרות צ’ קיום.
שכ’ ש
מביא ראיה ממשנה ששאר שטרות לא צ’ (ויש דוחים). יל"ד אם צ’ קיום מחשש זיוף או מטענינן. תוס’ משמע כשני. ק’ איך טוענים פרוע, ולא מזויף (כיון שלא שכיח), כיון שפרוע נגד ראיה, ואז אינו שכיח כלל. י"ל שפרעון שכיח, אלא שיש ראיה נגדו.[fn:18] (זה יותר טוב אם "שטרך בידי" אינו ראיה אלא דין (תנאי).) העיר’ שאולי זה אפשר רק לדיון של טענינן, ולא לחשש זיוף.
** מהר"ם אחרונים תומים ש"ך
הק’ רבי למה דן תוס’ אם מה שטוענים הוא פרוע או מזויף.
כ’ נפק"מ בתו"ז.[fn:19] הק’
שא"כ יזייף.[fn:20]
מביא ראיה מזה שטענינן פרוע בתו"ז (ואף על הצד שלא טוענים מזויף).
חול’.[fn:21] לכאו’, דנים אם הוא שכיח (אם הוא חלק מ"פרוע").
** תומים
כ’ שאם לא שכיח, ק’ ל"ל שבקת. י"ל שבכל אחד לא שכיח, ועל הכל, יהיה מצוי.
** ר"ן רמב"ן [fn:23]
משמע שגם דן בצד שחוש’ לזיוף (ולא טענינן). בצד זה,
(ב"ב ותשובה) כ’ שאחר שקבעו רבנן שצ’ לקיים שטר, שטר בלי קיום הוא חספא. גמ’ כ’ לשון כזה. כ’ כן אף בשטר להחזיק.[fn:22] קצת תלוי באם מגו זה הוא פש"א או מגו. רמב"ן יאמר שהוא פש"א, שא"צ אמירתו.
** רא"ש תוס’ הרא"ש רמב"ם ר"ן רמב"ן
כ’ שגט חלוק כיון שאין בו חשש זיוף, שלא יזייף שליח ולא יזייף בעל.[fn:24]
מוס’ ש"הפקעת ממון שאני, אבל הכא משום עגונא הקילו.” דבר ראשון משמע כמש"א ראשונים שבעל לא מפסיד ממון. דבר שני לא נ’ כן. אולי צ’ צירוף הסברות (או חיל’ איסור וממון) כדי לא נאמר ל"פ[fn:25].
כ’ ש"אין דיני אסורים כדיני ממון.”
כ’, "לפי שאין אשה ממונו של בעל, אלא ברשות עצמה היא להינשא, ואנן לא מנעינן (יש ג’ ברמב"ן שכ’ "טענינן,” אבל מגיהים אותו לומר כר"ן. ר"ן בח’ כ’ מצערינן. לכאו’, מנעינן הוא הנכון) לה.” “אנן למ"ל" נ’ מיות’. גם מוסיף שמתוך חומר… מקילים מתחילה. לכאו’, אומ’ שני ת’.
בתשובה כ’, “אשה ברשות עצמה היא להינשא האמינוה על עצמה כמו שהאמינוה לומר מת בעלי מתוך חומר….” משמע שהוא ת’ אחד.[fn:26] יישב ר’ שהוספת ר"ן ורמב"ן בח’ אינו ת’ בפנ"ע. היא נאמנת כיון שהיא ברשותה (שרק לה נוגע). הסיבה שמתירים הוא מחמת חומר בסוף.
** רמב"ן ריטב"א
דייק ר’ מ"אנן לא מנעינן" שב"ד לא פס’ היתר, אלא לא עוצרים לה. מחו’.
כ’ ל’ זה במק"א, וכ’ פשט זה ולא כ’ למ"ל. מדמה אותו שם לע"א, שהוא פסק.
מתחיל בנוסח ר"ן, וכ’ "ועוד [מאריך לומר שלא מנעינין].” נ’ כמש"כ.
** רא"ש רשב"א ר"ן[fn:27] ריטב"א רשב"א
דן בגבוי כתובה.
כ’ שגובה, שהיא מדרש כתובה.
ו
חול’, שיכול בעל לערער ולבטלו.
כ’ שאינו במדרש כ’ כיון שלא התירו לה. יל"ד אם ר"ן מכוון לריטב"א (ואם ריטב"א חשב שכן אומר ר"ן). לא אומר כריטב"א בראית כתובה; מש’ שפסקו. גם הדמיון לע"א (שהוא פסק) לא נ’ כריטב"א.
כ’ כתוס’ א"נ שלא מגבינן מבעל מידי (כר"ן), אלא אפקועי ממונא. באר’ שלא מוציאים מבעל לה, אלא מפקיעים זכותו. צ"ב מה מחלק. אולי ר"ל שכיון שיש לה כבר סיבה, לא חוש’. גם דחוק שחול’ על שאר ראשונים. י"ל שיציאת ממון בא ממילא מהיתרה, ודנים בהיתרה. יש לבעל זכויות אישות באשה, אבל זה איסורה אינו נוגע לו. א"כ, רשב"א לא חו’ על ראשונים.
** רא”ש ר”ן רא”ש ר"ן רב מבריסק פנ"י רמב"ם ב"י
כ’ שרק גובה מבנ”ח;
כ’ שבע”א גובה מלקחים. מדי’ מ
שבאמירה, גובה מלקוחות. מק’ שכבר רואים מרא”ש שלא גובים מלק’ ממדרש כתובה. י”ל שלא גובה מלק’ מפני חשש קנוניה.
משמע כרמב"ן, שכ’ שנאמנת כמו בע"א (מניחים שמוסיף על פשטו הראשון. למעשה, רמב"ן כ’ כעי”ז בפשט אחד.). מז’ גם לשון "אנן לא מנעינין.” אבל, ג"פ שאין מד’ כ’ שאין פסק. כ’
מלשון "אין אשה ממונו של בעל" שאין בעל נח’ בע"ד. מערער כיון שהוא בעל שטר, ולא בעל דבר.
כ’ שאש"א הוא גזלה. זה נגד ראשונים אלו. מוכיח מ
שכ’ שערער בעל על גט בא"י עושה שאמ"ג וולד ממזר.
מדי’ ממה של"א "גט בטל" שהוא רק קרוב לוודאי. גמ’ לא מש’ שהבן יהיה ממזר. [fn:28]לכאו’, נאמן כיון שבעל שטר הוא. חי’ שבעל, ולא עדים, ברא שטר. י"ל שמתחילו, או שמתחייב. מביא גמ’ שאומ’ שאם הודה לוה לשטר, גובים מלקוחות. צ"ל שנאמן כיון שהוא בעל שטר. ראשונים שם מק’ על דין זה, ואז אינו ראיה ברורה. ג"ק ששם טוענים לוקחים שאינו שטרו, ואז אינו בעל. לשון של פרשת סוטה וכדו’ משמע שהוא בע"ד. פשטות אינו כן, אלא שהוא בע"ד.
באר’ שמה שחוששים שיקיים אותו, ויגבה בו, אף שנפל ואיתרע, הוא מפני שחוש’ שישכחו שנפל.
** תוס’
בב"מ מש’ שחשש זה (איתרע) הוא דרבנן. אז, לווה ימצא אופן לפסול ההכשר, ולא חוש’ שלא ימצא[fn:29]. (גם העיר’ שבב"מ דן בבא לידו בהיתר והוח’ בהיתר, שהשני משמע יותר חוזק.) נ’ שתוס’ כאן סובר שהוא מדאו’.[fn:30]
** מרדכי ר"א ש"ך נתיבות
ענין "הוחזק בהכשר" הוא שכיון שכבר פסק ב"ד כן, לא חוז’. כעי"ז מצאנו:
כ’ בשם
שקיו"ש דרבנן רק בלי טענת ברי לזיוף.
דן בזה, ודוחה אותו. מוכיח מגמ’ שלנו, שכיון שע"א מעיד, בעל לא נאמן בטענת זיוף, כיון שהוא מדרבנן.
ת’ לחלק בין אם ב"ד כבר הכשירו שטר לאם לא כבר הכש’.[fn:31]
** רע"א רש"ג ש"ך
ת’ לק’ תוס’ ע"פ
, שכ’ שדמיון כ’ לא מהני לשטר בחתימת לוה בלחוד.
באר שאופן זה דרבנן, וכיון שאין "עדים… כמי שנחקרה,” צ’ קיום מדאו’. אז, י"ל שגמ’ ב"מ דן בזה, כיון שאיתרע, צ’ קיום מדאו’, וחוש’ שידמו.
אפשר לומר שלמס’, צ’ "בפנ"כ’" כר"א, ו"בפנ"ח" לקיים.
** רע"א ראשונים רש"י ש"ע רי"ף ב"י נתיבות רמב"ן ראב"ד
הק’
לרבה שח’ של"ש חסרון בהגדה עצמה. אז, לא שייך בקיאות בלשמה.[fn:32] יש
שכ’ שלשמה צ’ דבור. אז, י"ל. גם ת’ שאם תברר איזה אשה מג’, יש רק בעיה בלשמה.[fn:33]
כ’ במס’ שחוש’ שנטל מחברו. זה נגד רע"א.[fn:34]
כ’ שאם נפס’ עדים אחר חתימתם בשטר, כשר, שעדותם הוא שעת חיתום. מביא י"א שהגדתם הוא יציאת שטר מידי עדים.
ביבמות כ’ שא"א נח’ עדותם עד שיצא מידם לבע"ד. יל"ד אם תלוי במה שיש לעדים או אינו לבע"ד.
מניח כראשון. מקורו הוא שלשון רי"ף הוא שאינו זמן עדות כיון שעדים יכולים להסתירו.
חלק, כצד שני. (מה שנחשב נחקרה כבר בסוגיה שלנו הוא שמיד ייתן אותו לאשה). באר שנח’ הגדה כשמי שרואה השטר, יבין שקרה. אז, צ"ל ביד בע"ד. (אז, אינו"כ בשטר הקנאה.)
ביבמות כ’ שרי"ף ר"ל כ
, שסובר ששטר שאינו נעשה להיות ביד בע"ד לא נח’ נחקרה בב"ד. אבל, אם נעשה לבע"ד, נחקרה מיד. נתיבות מפ’ שכוונת רמב"ן כמותו.
** ר"ף
לכאו’, כע"מ שיש הגדה אף שעדים לא יודעים שיקרה מה שמעידים. (לנתיבות, נעשה הגדה אחר שקרה, אבל עדיין לא ידועים עדים מה יקרה כשכ’.).
כ’ שאף לר"א ע"ח מהני, כיון שמעידים על מסירה. נמצא שעדים חות’ על חלות, אף שלא יודעים, בדר"כ, שיקרה, אלא יודעים שאם מה שכ’ בשטר יקרה, החלות יחול. אז, חולקים אם צריך שההוכ’ יקרו או שכבר קרו (השני הוא שיטת נתיבות).[fn:35]
** תוס’ ובעה”מ אחרונים
גם היה אפשר לומר שעדים מעידים על דעת מתחייב .אין כות’ וחות’ בלי דע”מ.
כ שזה מה שעושה שאינו מפי כתבם (בע"מ כ’ שהוא מפי כתבו). אף שתוס’ כ’ פשט אחר, שצ”ל נכ’ בנוסח שטר, עדיין צ’ דע”מ. (יש
שמניחים שדע”מ הוא מה שעושה שטר לשטר. העיר’ שתוס’ שם מביא ציורים שאפשר בלי דעת מתחייב.[fn:36]) הק’ ר’ שלא כ’ דע"מ בשטר.
אז, בטוב הק’ רע"א. מניח שעדים מעידים על המאורע. אילו מעידים על דע"מ, יהיו חתימתם נכון, שהרי שאל מתחייב להם לחתום.[fn:37] אבל, כיון שמעידים על המאורע, צריך שעל אותו מאורע מעידים, ואי אפשר להיות שחושבים על אחר.
** גמ’
חול’ ב
אם, כשיש שני יוב"ש בעיר, מוציא אחד שטר- אם חוש’ לנפילה או לא. לרע"א, ק’ למה יכשיר, שלא מעיד מי הלווה. (גם אמר’ שפשוט שאין בע"ד צל"ד ממי ילווה.) כמו"כ, אין לווה שכ’ שטר בלי מלווה צל"ד מי ילווה. י"ל שפורט יוב"ש- מי שילווה, כמו שלעולם לא נתברר עד לאח"ז שילווה.
** ש"ע ש"ך תומים נתיבות
מלווה אמר לעדים לכ’ (ולאש לתת לו), לא כות’.
כ’ שהוא מחשש הערמה.
הק’ שאין שטר כשר, כיון שלא נכ’ מדע"מ.
ת’ לשיטתו[fn:38] ששטר הוא שטר רק כשבא לבע"ד, ורק אז צ’ דע"מ. (היה אפשר לומר, נג"ז, שהגדה ממשיך מזמן כ’.)
** תוס’
(ד) מק’ למה פסול של"ש שייך למזויף מתוכו, שמזויף מתוכו הוא שמא נסמוך על העדים (ואף שהדבר אמת, אין לעשות אלא בעדות כשר), אבל בשל"ש נוכל לסמוך. ת’ שלפעמים יחתמו קודם כ’. אז, ליכא עדות כלל. זה ק’ לנתיבות, שאינו הגדה עד אחר כ’.[fn:39]
** גמ’ תוס’ אמרי משה
(כג) דן אם משניות גיטין הם כר"מ או כר"א. מק’ ממש’ שכ’ שצ"ל נכ’ לשמה, ות’ שצ"ל[fn:40] נחתם.
מק’ שתחילת משנה הוא, "שמע קול סופרים מק’… ואמר זה שמי, פסול לג’.” כ’ שאף מחת’ עדים להתלמד.[fn:41]
כ’ שרואים מתוס’ שאצ"ל לשם ג’ כלל להיות עדות. יש לבאר כנתיבות, שעדות הוא רק כשניתן, ובזה מכוון. יל"דחות שזמן הגדה הוא לאח"ז הוא רק אם א"א להם להיות מעידים כשחות’.
** תוס’
כ’ בחשש לשמה שאף בלי לשמה צ’ שגט יודיע מי מג’, אלא כ’ שחוש’ לכ’ להתלמד, ובעל החתים עדים. ק’ למה צ’ שבעל הח’, למש"כ לעיל.
ע"פ נתיבות, י"ל לק’ רע"א, שלהג’, צ’ תנאים אלו רק בשעת הגדה, ולשמה צ’ זה בשעת ח’.
** ריטב"א
כ’ כע"ז. יש שני לשונות ברש"י ב"ב"נ וב"נ" לרבה. כ’ ריטב"א שכיון שאמר שנכ’ בפניו, יודעים שלשון גי’ שבו נכ’ לשמה, ולא שסופר כ’. בפ"נ נצ’ לומר שעדות היה לשמה, ולא שסופר החתים. נמצא שסובר שזה כשר לולי לשמה.  כאן, שלא כ’ שמות, הוא כעין חתימה על נייר חלק, ואומר ריטב"א שמהני. (כאן מכוונים לעדות, אבל לא כ’ מהו עדות. לכאורה, אין זה מחלק בי"ז לשל תוס’.) לכאו’, צ"ל שעדים מאמינים סופר בזה. אם לא, צ"ל שרק חותמים אם מבררים שלא ניתן שלא כדין.
אפשר שאם נכ’ שטר מדע"מ, כשר למתחייב אחר. לא נ’, שרק על מתחייב ה"ה עדות. אז, א"א לבאר "מצא ב"ע" כך.
** א"מ חת"ס
קשה ל"ל צ’ דעת אשה בגט, שאף היא מתחייבת.
הביא
שכ’ שאם עדי חתמה כרתי, אין מג’ אשה בע"כ, שכות’ גט בלי דעתה מפני שכשנושא, מקבלת, שיודעת שזה הדין.[fn:42] אחר חרם ר"ג, אינה מקבלת.[fn:43] אולי אף לר"א, כמזויף מתוכו.
** א"מ פוס’
ת’ לק’ רע"א שברב שטרות, עדים אצ"ל מלווה, אלא לווה. בג’, צ"ל לשם מתגר’.
כ’ שצ"ל שמה של מתג’. אם מניח שמעידים על המאורע, אומר שבשטר הלוואה, רק צ"ל חלק מן המאורע, ומעידים על חיוב של מי שילווה ממנו. לשמה אומר שצ’ יותר מזה, אלא צ’ לדעת לשמה. ק"ק למה צ’ ידיעת שמה; צ’ ידיעת קרק’ שלה לכוון בה. א"כ, מח’ של "לאיזה שיתן גט" ג"כ לשמה. י"ל שברירה הוא, אלא שאז זה שווה לת’ של רע"א.[fn:44] אולי ר"ל שלא צ’ אף קרק’, שרק מעידים על דע"מ.
יש דיבור אחר של רע"א שבו לא מודה לק’ זה. אולי סובר שאה"נ, זהו בעיה בעדות, וב"נ אינו מח’ לשמה[fn:45]. תוס’ מק’ שאילו צ’ לשמה מח’ גז’ על ציור שאינו עדות כלל שא"כ יהיה בשאר שטרות. לא מק’ שא"כ אינו בעיה של לשמה.
אפשר לת’ לק’ רע"א בציור שכ’ שטר ראיה שגירש את אשתו, ולא לגרש בו (לשמה הוא, ולא לשם גי’, ואז לא מהני). לכאו’, לא חוששים לזה מפני לשון הגט.
** רב שאך ר’ א"ז תוס’ ר"ח
כ’ אגרת ל
שכמו ששטר מלווה הוא עדות על הלוואה, כך הוא עדות שלא פרוע.
משמע נג"ז. זה מחו’, שלא כ’ כן בשטר. זה גם נגד
שאומר שהוא דין, ולא הוכחה.[fn:46]
** רב אלחנן תוס’
(ב"ב) כ’ שעדים חות’ בלי דע"מ כשיתן רק בדע"מ. כ’ שכן מבואר, אבל לא פשוט כך. עפ"ז, מת’ לק’ רע"א, שהעדות הוא אח"ז כשהשטר ניתן לדע"מ. נמצא שסובר כנתיבות במח’ לעיל.
בכתובות מק’ לחלק בין שטר לעדות שנכ’. כ’ שצ’ דע"מ או נוסח מיוחד. (אומר שמיד נחתם, שכך הוא הציור שם.) אפשר שעדיין סובר כתוס’ שכ’ שיכולים לח’ להתלמד. אפשר ששניהם יכו"ל זמן הגדה.[fn:47]
לכאו’, אם מעידים לאחר זמן, צריך להיות עדיין שמעידים לאותם בעלי דברים. אז, צריך שעדים ידעו, אז, למי הולך הגט. הוסיף ר’ שצ"ל שעדים יגרמו אותו נתינה, שבזה עושים עדותם. אז, אם יכולים לת’ לק’ רע"א תלוי במהו החשש. צריך להיות שחלק מן החשש הוא ללשמה, וזה רק אם נשאר בידי עדים. גם יש להעיר שאם יש נחקרה כשחותמים, אם אפשר, הרי כאן אפשר, אלא שהוא לאחר.
** ראשונים רש"י
חול’
אם צ’ לשאול, או שסתמא לשמה, או שאם נכ’ לפניו, פשוט שהוא לשמה.
כאן כ’ ששואלים, ולקמן מביא, עם אותו פשט, השני. אפשר שרש"י משנה בין הו"א למס’, שגמ’ משנה אם הוא חשש ממש.
** ראשונים רש"י
דנים
אם חוש’ לערעור בעל בשקר או באמת. מ
שכ’ שכיון שעד מברר, לא יבוא. מש’ שמשקר.[fn:48]
** ריטב"א
לכאו’, כיון שע"א נאמן, צ"ל שחוש’ רק לערעור בשקר.[fn:49] עדיין, כשבא, נאמן (כן אומ’ רש"י). אם כן, צ"ל שכיון שבא, מניחים שהוא באמת. גם כ’ רש"י למס’, שאם בא, לא נאמן. צ"ל שיש סיבה להאמין ע"א. מעניין שלרש"י צ’ שניהם (שלא יערער, ושאינו אמת).
מצ’ למש"כ גמ’ שכ"מ שהאמין תורה ע"א, ה"ה כשנים. לכאו’, צ"ל שזה רק אם הוא ענין שצ’ שנ"ע, וזגר תורה שצ’ רק אחד. מראשונים שכ’ שגמ’ לא ת’ כן, נ’ שכאן אינו כן, שרק צ’ עדות דרבנן, ולא האמינו תורה כשנ"ע.
** רב מבריסק
מק’
למה כ’ רש"י שמוקמים חד לבהדי חד, כיון שגמ’ כ’ שערעור בעל חזק משל שאר ע"א. י"ל ששם אין לו נאמנות, אלא טענת בע"ד, וזה רק נותן כוח להתעורר ספקות.[fn:50]
לכאו’, “עדים החת’…" מוכיח שאין חשש זיוף, שרק נח’ נחק’ כיון שיכולים להבין עדותם משטר. צ"ל שידעו שלא מזויף.
ברבא, אין חש’ בלי טענה (שצ’ טענינן; ובגט, צ’ טענה[fn:51]). אז, הדיון הוא כמו דיון ברבה לרש"י (אלא שלרש"י זה רק נתחדש יותר קרוב למס’ ברבה), שחוש’ לערעור שקר.[fn:52]
** רש"י תוס
כ’ ש"רבנן הוא דאצ’" הוא מח’ חשש.
’ כ’ שהוא שמא יערער ויוציא לעז.
ברבא, בוודאי, אם מער’, נאמן בעל (כמו בא"י).
** משנה תוס’ רש"י רמב"ם חת"ס תו"ג
כ’ שאם יש עור’ יתק’ בחות’.
כ’ שאולי זה אף אם נאמר בפ"נ (בהו"א).
(ט) כ’ שאם יש עור’ שגט פסול, ולא מזוייף כמש"כ כאן. (לא פשוט מה קרה בדפוסי רש"י, שלכאו’ מפ’ משנה בשני מקו’. לכאו’, תלוי בשני ג’ איך משנה נח’ במשנה, שהם יותר ממשנה אחד, אבל בכ"מ נתנו אותו בגמ’ לאחד. אולי הם שני דפוסי רש"י.)
בפ"מ כ’ כרש"י (ט). ק’ מה מהני קיום בחות’.[fn:53]
כ’ שטען במגו מזויף. (לרש"י (ט), המשך משנה יותר טוב, לרבה בהו"א.)
כ’ שאף לרבה בהו"א, נאמן לקיים.
העיר’ שאף שחשש דרבנן הוא, לא היה נאמן בלי תק’ עגונות, שחשש דרבנן טוען עדות דאו’.
** גמ’ רש"י תוס’
מק’ שנחוש שבעל יפסול הגט. מ
, פשוט שיפ’ אותו ממש. כ’
שיפ’ מח’ לעז שיוציא. מק’ אם כן למה יהיה ע”א. ת’ שלא יער’ בעל; אבל אם ער’, פוסל. לזה, הק’ שמשנה (אם יש עליו) קאי אף ע"ז.[fn:54] דחה, וכ’ שרק ר"ל שיאמר שפסול.
** מהר"ם מהר"ם שיף
כ’ שקאי על דיון ברבא. לכאו’, יתקיים בחותמיו קאי על שעת זיוף, ואז צ"ל שדן ברבא. לא מב’ איך תוס’ יב’ רבה.
כ’ שקאי על רבה (וכן הפשטות, שבלי”ז, ק’ למה מניח שהוא רק לעז). מבאר ש"ית’ בחות’" ר"ל שנדע מעדים איך נכ’.
** תוס’ ראש
כ’ תוס’ כמהרם וכמהרם שיף, שמתחיל ברבה, ודן בו, ואז דן לשיטת רבא. שם, מניח מס’ תוס’, ומוס’ שאף לרבא, כיון שאמ’ ב"נ, הוא לעז. (יש סמך לזה, ממה שמשמש עם מלים שווים.) אולי זה מפני מש"כ ריטב"א (על"ע).
** מהרש"א
כ’ שאף לרבה, רק אחר ב"נ, הוא לעז. ק’, שלכאו’, תוס’ מיוסד עמש"כ תוס’ לעיל, והוא שצ’ ב"נ מח’ לעז.
** רבנן ר"מ תוס’
אף שאמירה זה רק מח’ לעז (לתוס’), מעכב.
פוס’ גט, ו
ממזר וולד כיון ששינה מתק’ ח’. יל"ד אם רבנן פוס’ כיון שלא קי’ תק’, או כיון שלא קי’ סיבת תק’. אם לא נכ’ כראוי, שמואל אומר שחכמי’ אומ’ שגט כשר, ורב אומר שגט פסול. אי"ז ק’, שאולי תק’ בפ"נ יותר צ’. (הוס’ ר’ של
שבלי תק’ עגונות, חייש’ לזיוף, ק"ל שמעכב.[fn:55]) לרבה, בהו"א, לרש"י, שהוא חשש, י"ל כ"ז, שאפשר שפ’ כיון שחש’ רבנן ללש’. לתוס’, שחוש’ ללעז, יותר קשה לומ’ כן, שאין חש’ לפ’.[fn:56] יותר קל לומר כצד קמא.
** תוס’
הק’ לקמן שלר"מ תק’ רבנן מדיני חתימה לכ’. א"כ, הו"ל לגמ’ לומ’ כן ללשמה. ת’ שלא יתק’ מח"ז אמירה. יש מק’ שלתוס’, רק חוש’ ללעז. א"כ, כיון שאין כ’ של"ש מעכב, אין לעז. אז, ת’ תוס’ פשוט. אולי מניח שכיון שהצ’ רבנן עדות ללשמה (לחת’), עשו רבנן שיש חשש לשמה[fn:57]. אז, יש חשש אף לכ’. אז, י"ל כצד שני.[fn:58]
** גמ’
מק’ ל"ל צ’ שנ"ע (ומת’ שהק’ משום עיגונא). אם רק מפקיע לעז, ק’ למה צ’ שנ"ע, שאין אלו מבררים. מש’ שתק’ רבנן עשה שנחוש.[fn:59][fn:60]
** רי"ד רא"ש תוס’
ע’ בריי’ לקמן (ה). חול’ אם גורסים "אלא מה יעשה,” או "מה… .”
גו’ כראשון, ומפ’ שהוא המ’ שיטת רבנן. ר"מ לא יסבר שיהני.
כ’ כראשון וכ’ שמורה שקאי על ר"מ.
כ’ שמהני לכו"ע, לפעמים. לרבנן, מהני בכ"ז. לר"מ, מהני רק קודם נשואין, שאח"כ כבר נאסרה על בועל. עו"כ שם שממש"צ ליטול ולתת, רואים שצ"ל כן בשעת נתינת גט (או אפילו תוכ"ד או עסוקים בא"ע).[fn:61]
** רע"א
מציין למח’ רשב"א ורבי בגט פ’, אם צ’ ליטול ולתת או רק לומר. תוס’ שם מק’ שברי’ שהבאנו לעיל כרשב"א. ת’ שנאמן רק בשעת נתינה. ג"ת עו”ת (נתינה כבר נגמר כיון שמהני מדאו’). אם תלוי (או לת’ קמא), צ"ל שמה שלא אמר ב"נ מעכב מח’ בעיה בנתינה. בת’ שני, מצאנו סיבה אחרת שצ"ל בשע"נ. א"כ, אין להוכיח שהוא חלק מנתינה. אין סיבה לומ’ שחוזר מהנחת ק’. אם נאמר שמעכב כיון שהוא חלק מנ’, העיר’ שלכאו’, לצד שני של תוס’, יש שני סיבות לפ’, החשש ונתינה. ק’, אז, למה עשו שני התקנות. אולי לת’ שני של תוס’, לא פוסל מח’ שאין נאמ’, אלא לכן לא מקיי’ תקנת חז"ל.
** גמ רש"י רי"ד
מק’
’ ש"משום דלא אמר (אלא לאח”ז), הוולד ממזר.”
מפ’ שמק’ שהרי נכ’ לפניו. רואים שנחית גמ’ לומ’ שאי לא אמר, מעכב מח’ חשש. (כן משמ’ג"כ לשון גמ’ ש"משום דלא אמר.”) רק רואים שיכו"ל שתק’ רבנן חשש, ולא שעשו.
כ’ כרש"י, ומפ’ יותר. ג"פ שמק’ שכיון שבעל לא מערער, למה יפ’. נמצא שלא חוש’ בלי אמ’.
** ר"ן
מוס’ עמש"כ תוס’ (ה), שכיון שמעיד לאח"נ, אין חוש’. נמצא, שבלי אמ’, היה הוולד ממזר. גם נמצא שאף שאמ’ כן, צריך ליטול ולתת. צר"ל כצד ראשון, ולא כצד שני.[fn:62] מצאנו, אז, שני סיבות לפסול.
מתוס’, רואים יסוד שבא מכ"מ שרבנן גז’ בגדרי לומדות.
** ר"י מקינון רא"ש רמ”ה מרדכי
רא"ש כ’ שבריי’ קאי על רבנן, שאף שלא סוברים כר"מ, אם שינה, תצא. משמע כצד ראשון. רא"ש מביא מש"כ תוס’ מתי צ"ל ב"נ. מביא מ
שצ’ לטול ולתת כדי שישמעו ע"מ; לא צ’ שישמעו בעת נתינה, אבל דן בציור שכבר אינם שם. צ’ להיות עדים שראו מסירה כיון שהוא חצי דבר.
חול’, שלשון גמ’ משמע שצ’ בכל ציור.
מוסיף שגם מהני אם אומ’ לפני עדים שיודעים על ע”מ. לכאו’, ר"ל שראו, אבל לא נקבעו. כל זה משמע שאינו חלק מנתינה, שלא צ”ל בשעת נתינה.
דן אם צ’ לקרוא גט לפני נ’ או אף אחריו. כ’ שר”מ כ’ שצ”ל שיודעים עדים שהוא גט, בשעת נתינה, כמו ב”נ. אם הוא פסול בנתינה, אז אין להביא סמך מזה. משמע שאינו חלק מנתינה.[fn:63] (כל אלו מניחים שע”מ כרתי.)
** רשב"א
(ה) מסופק אם מהני ב"נ לאח"ז, כמו קיום, ואף לר"מ. נמצא שכשגמ’ אומ’ שהוא מצורת גיטין, אינו מצורת גט או נתינה, אלא תקנת חשש שתקנו חכמים.
** רמב"ם גמ תוס’ ראשונים משנ"ל
פשטות הוא שקיום מהני לאח"ז. זה ק’ לתוס’. יש קטעים מ
שמשמעים שצריך לקיים קודם נתינה. כ’ ש"[אם לא ראה], לא ינתן אא"כ יתקי’ בחותמיו.” ג"כ, “נתנו לו, ולא הספיק לומר עד שנשתתק (
’ אומ’ שנתחרש, ו
מק’ ל"ל אומ’ אלם; דנים
אם יכול אלם לכ’ לעדות זה) יתקיב"ח ואח"כ ינתן לה.” הראשון היה אפשר להיות רק עצ"ט (שאין טוב בגט בלי קיום). בשני, צ"ב מה אומ’, שכבר נתן. צ"ל שנוטל אותו ושוב מקי’. זה א"א בגמ’, שדן בחרש, שאינו בר דעת. ג"כ, “[אם שליח נתן גט בינו לבינה],  או שנתנו לה בפנ"ש, ולא אמר ב"נ, אף אם נשאת, נוטלה ונותנה ואומר. ואם לא נטלה, ה"ז פסול עד שיתקב"ח.” משמע שקיום מהני, אף שלא נטל. מ’ שקיום קודם נתינה רק לכתחילה.
מק’ איך מהני אם נתן בינו לבינה, שאין ע"מ. ת’ שכיון שמק’, אינו פסול, ורק צ’ עוד נתינה.[fn:64]
לכאו’, צ"ל שרבנן לא עקרו עיקר הדין של קיום של שנ"ע, אלא רק דין של קיום ע"י ב"נ. אולי תק’ כן מח’ עגון, אבל נשאר הגדרה מוזרת.
** גמ’ תוס’ יש רש"י תוס’ שב שמעתתא רש"י רמ"א ט"ז ש"ך ש"ש אחרונים יש [ ]
אומ’ שע"א לא נאמן כיון שהח’ איסור, והוא דבר שבערווה. יל"ד אם אומ’ אחד או שני סיבות למה אין ע"א מהני.
מבאר צורך לשניהם.
אומ’ שנעשה דבר שבערווה רק כשהוח’ איסור.
כ’ שהאמינו תורה על תרומה, שחיטה, ניקוט, וחלב. אלו אינם מפורשים, אלא סובר שלא מס’ שהתיר תורה רק אם עדים ראו. רש"י מבאר למה א"א ללמוד מטבל ושחיטה.
מעורר שסותר א"ע.
כ’ שבידו עושה שלא הוח’ איסור. נאמנות בא מע"א.
לא חוזר לדון בניקור. משמע שלא ק’ שאית’ איסור[fn:65].
כ’ שלא נאמן בו ע"א.
מק’ שלא אית’ איסור; מה שהיה הוא רק איסור בבשר. רש"י משמע כט"ז.
נ’ שחול’ על ט"ז. ההגדרה יהיה שירך זה לא היה אפשר להיאכל, ואז אית’ איסור.[fn:66]
כ’ שאין תוס’ קשה לרמ"א. כ’ שאף שאין ח"א, יש חז’ שלא הוקר (מדמה לחז’ שלא בדוק, שאין אית’ חל על בית, ועדיין יש חז’). דנים
בזה. מעורר שאם בידו לנקר, נאמן.
שכ’ שלא נח’ בידו, שלא קל למצוא בקי.
היום לא מנקרים כיון שהוא קשה, ויותר קל למכור לגויים. עשו אותו בא"י לפני זמן, וכשעשו אותו, שאלו לאמו של ר"ק (שלא ישבה על מטה), שלמדה לנקט בפולי"ן, שלא היו מתירים להם לשחוט הרבה בהמות. גם ר"ק ראה איך לימדה, ואז, אף הוא יודע.
[fn:67] נמצא שהוא בחז’ אינו מנוקר, ואינו בחז’ שהוא גה"נ. לא יכול לשנות גיד לשאינו גיד, ואין זה בידו. אז, נמצא שעל מה שאית’ איסור, בידו הוא, ובמה שאינו איסור, אינו בידו, ונאמן מח’ ע"א.[fn:68] הק’ רבי שכבר הוא בידו לעשות שאין גיד שם; אז, כבר פשוט שאי"ז גיד, שפשוט לראות שהוא בשר. באר’ שלא יכול לראות, שגיד כולל אף מיני בשר, וגם יש גידים אחרים שם שמותרים. אם לא נאמר כש"ש, אינו נח’ בידו.[fn:69]
** תוס’ יש רמב"ן ש"ש ר"ש רשב"א
כ’ מקור לנאמנות ע"א.
שדוח’ שאין למ’ אפשר משא"א.
מבאר בתוס’ שנ’ כיון שבידה לספ’ ולטבול.
כ’ שרמב"ן לא כ’ לת’ תוס’.
כ’ שרמב"ן ותוס’ מודים להדדי. צ’ לדעת שלא רואה דם עוד, וששהתה שבעה ימים מראשונה. תוס’ מפ’ שעל קמא, אינו נגד חז’. שני נח’ בידו, שבא ממילא, והוא נגד חז’, שהוא מה שמטהרה.[fn:70]
משמע שרק על טבילה דן בבידה. לכאו’, דנים בצורך לשהייה, אם נגד חז’, שהוא חלק מסדר טהרה אלא ברור שלא רואה עוד.[fn:71]
** תוס’ ראשונים רע"א רמב"ן
משמע שגמ’ מק’ ק’ אחת.
חול’ בע"א נאמן בדבר שבערווה בלא אית’ איסור. מק’
מתוס’ לקמן שמק’ למה צ’ "וספרה" אם ע"א נ’ נגד אית’, ומת’ שהו"א שהוא דשב"ע. ק’ מהו ההו"א, שלא אית’.
מפ’ שגמ’ מק’ שני ק’, אבל גם כ’ שאם לא אית’, אינו דבר שבערווה. אם בידו עושה שלא אית’ איסור, יהיה תלוי באם דשב"ע צ’ חז’. ג"ק, אז, מה נתחדש בדשב"ע. י"ל שצ’ תורת עדות כממון. גי"ל שבידו לא מהני.
** ר’ שלמה
באר’ בשם
שע"א לא נאמן כשסותר חז’. בדשב"ע, לא נאמן ע"א כלל, אלא שאינו דשב"ע אא"כ הוח’. אז, מש"כ תוס’ ש"אינה בחז’ שתהא רואה כל שעה" רק מהני לראשון, ולא לשני. א"כ, תוס’ לא ק’, שזה מוציא מהו"א שנדה דשב"ע. ג"כ יבאר רמב"ן, שאז יש שני ק’ חלוקות. גם מבאר ל"ל מהני מה שהוא בידו.
** ר"ש רע"א תו"ג רמב"ם יש
היה אפשר לומר שיש חזקה שאין רואה, אבל מתוס’ נ’ שאין חז’ שרואה, שאל"ה ק’ איך לומ’ שע"א נאמן. אז, אם טובלת, תהיה עדיין טמאה מח’ חז’ טומאה. אעפ"כ, ע"א אינו נג"ח.
מז’
שכ’ שעד שמעיד שבהמה קודם שנשחט שהוא יותר משמנה ימים נג"ח. היה אפ’ לומ’ שרק נג"ח אחר שחיטה, שאז אין נבלה בפנינו, ודוחה מגמ’ כאן, שע"א לא נאמן להכשיר גט קודם התירה.
פוסל ע"א שמעיד שמקווה כשר, שהוא נגד חז’ טומאה. זה מחו’ לדין. מחלק בין אם מעיד לפני או לאחר טבילה, כיון ש
מחלק בין אם מעיד ע"א על חלב לפני אכילה או לאחריו לענין מלקות.
חול’ על רמב"ם. (יש לחלק שרמב"ם מניח שלא מעיד על מלקות, אלא על איסור. אין תוצאה להיותו מקוה חוץ מטהרתו.) באר"ש שע"א לא נאמן להתנגד לחז’, ולא שלא נאמן אם חז’ יכריע דין (רק לא נאמן על פעולה שישנה הדין). אז, עד נאמן לומר שמקווה כשר. אז, חז"ט לא יאמר לנו שרואה עוד. צ"ל שכ’ גט לשמה נגד חז’, אף שחז’ על אשה. הוא חלק ממה שמתיר אותה, ואז הוא נגד חז’. (וכ"ז הוא הגדר רק גבי ע"א באיסור, ולא בדשב"ע.)
** תוס’ ר”ח ראשונים חת”ס
הק’
ממה ששטר צ’ שנ”ע.
הק’ (או באר ת’ תוס’) שצ’ שנ”ע לשטר. ת’ תוס’ לא משמע ככ”כ. (יש
שכ’ שע”א בשטר מהני לדברים שבהם מהני ע”א.)
כ’ שע”ק צ’ שנ”ע. מק’ מהו ההו”א שרק ע”ק צ’ שנ”ע, שכ’ קרא בבירור. ת’ ר’ שגמ’ בהו”א לא ידע “אין דבר...,” ולא ידע מקורו. מלשון תוס’, משמע שצ’ שנ”ע למה שעושה חלות, אבל לא לברר יותר. עדיין ק’ ל"ל נל’ כולו מממון. י”ל כמש”כ לעיל.
** רע”א
מק’ שגמ’ לקמן אומר שצ’ שני כיתי עדים, אחד על עשיית שליח לקבלה, ואחד על קבלה.
** רש"י
לשון "עדי חתימה כרתי.” מעניין. יש אומרים שעושים חלק מן הכריתות.
משמע נג"ז, שכ’ שר"ל שעושים גט לספר כריתות.
** תוס’
על ביאור
במזוייף מתוכו, העיר’ שזה חשש חלוק משאר מזוייף מתוכו. לכאו’, צ”ל שמימרא זה מח’ שאין חוש’ שנ’ כחוכא כיון שיש סיבה לפ’.
** תוס’ רמב”ן רי”ף
מפ’ שמניחים ע”מ מע”ח, שמס’ בהכשר נעשה.
חול’. תוס’ סובר שצ’ ע”מ לר”א. כן מש’ מרש”י במק”א, שכ’, “לא סגי ליתן בלי ע”מ.” (רש"י פ’ שבע”כ צ’ שנ”ע, שלומ’ מממון. אם גט שטר, ק’ למה צ’ זה, שי”ל כר”ח. אולי זהו המקור שגט צ”ל שטר.)
חול’.
** רמב”ן רשב”א גר"א
כ’ שלר”א “וכתב” כולל כל כ’ (ואף חתימה) שנצ’. ק’ גמ’ הוא שצ’ לתת לפני שנים או שלש, ויש ע”מ. ת’ שלא יודעים שינתן לפני ע”מ[fn:72], ואז נצ’.[fn:73] אז,[fn:74] הפסול דומה למזו’ מתוכו שבמק”א.
כ’ שאין מזוייף מתוכו כאן כשאר מזו”מ. מק’ ק’ תוס’, ומפ’ שאף שכשרים לראיה, יש פ’, והוא שהם מצורת גט, וצ”ל לשמה מדאו’. ממשיך שלרי”ף ק”ל שהם מצורת גט, ש,אף שאל נצ’, מכשירים גט. דוחה שניהם (שרק צ’ כ’ לשמה). בהו"א, באר’ שגט ראיה לחלות, כמו שכל שטר ראיה, וראיה זה חלק מצורת ג’. א"כ, מובן שכל ראיה שבגט חלק מגט. עדיין מחו’, שא"צ אותו ראיה, שיש ע"מ. בהוספה לרי"ף, יש להעיר שהם העושים הגט, שכבר הוא גט (וצריך לומר שאם חות’ של"ש עושים אותו לס"כ פסול), ואז ע"מ לא עושים כלום. לחול’, אין ע"ח בלחוד עושים חלות, ששני כתי העדים עושים כן. (ע’ ב
על שו"ע.) מסיק רשב"א שצ"ל שגז’ הוא. לא מבאר הגז’ (התחיל בק’ תוס’, ות’ שהוא מדאו’, וחזר לומ’ שהוא גז’).
** ר"ן
מה שלא אומ’ "אף ע"מ" לרמב"ן הוא שפשוט שע"ח מהני.
כ’ לרי"ף שע"ח מהני לע"מ. א"כ, לשון "אף" לא ק’.
** ריטב"א בן אחיו של רא"ה[fn:75] גמ’ רמב"ן ר"ן קצות
כ’ בביאור שקו"ט שדן במח’ רשב"א ורמב"ן, או שמח’ גז’ של מז’ מתוכו. ג"כ בשם
שכשיש רק ע"ח, רק חתימה צ"ל לשמה. צ"ע בפ’ קרא, שצ’ שח’ לשמה, וששום דבר לשמה. כשעדים חות’, מעידים עמש"כ. א"כ, אולי אותו ח’ לשמה ה"ה כ"כ’ לשמה[fn:76], שכ’ גט נכלל בח’. העיר’ שאז מובן שמניח ר"מ ש"וכ’" ר"ל חתימה.
מכשיר שני גיטין שנתערבו. דן אם זה אפשר לר"א. (אותו גמ’ צ"ב; בפ’ הצד לפ’ הוא שאין ע"מ יודעים; א"כ, מה שמק’ למה צ’ נ’ לשמה מוזר.) ק’ לרי"ף. ת’
שכמו שר"מ צ’ ח’ לשמה, צ’ נ’ לשמה (ש"לה" קאי על כ’ ונ’) כיון שע"מ מג’. לכאו’, מפ’ שהפוסל סובר שאין הבעיה שאין ע"מ ידעי. (מה שתולה נ’ לשמה בע"מ מג’ צ"ב.) מק’ שכשיש ע"ח, לא צ’. ת’ שכמו שצ’ כ’ לשמה כשיש ע"ח, כך צ’ כאן, ש"לה" קאי על כ’ ונ’ כיון שלפעמים עושה כריתות. משמע שכשיש ע"ח, אין ע"מ כרתי. לכאו’, היה נ’ לומ’ שלר"א ע"ח לא שווים כלום, ואף אם נאמר שיכולים ע”ח לעשות ח’, לא כ’ עליהם וכ’ לה. מרמב"ן נ’ שאם שם, עושים ג’. (גר"א כ’ שאף אם ע"ח מהני, הם מדין שטר, ולא כבר"מ. רשב"א לא כ"כ ברי"ף.) כשרמב"ן מבאר ר"א, מח’ שמסברה, ואז מקרא, נ’ לשמה. סברה זה, ומה שפשוט לד’, הוא רק כשאין ע"ח; כשיש ע"ח, לא היה כן בכ’ ונ’. אז, דיני כ’ היו על ח’. משמע כב"א של רמ"ה. יל"ד במס’ (אינו כב"א או ל"פ או שצ’ בכ’ בפ’). כ"ז מניח שר"א כר"מ, אלא אף ע"מ מהני.
כ’ שע"ח עושים מה שצ’ מע"מ.
פ’ שר"ל שאנ"ס שנמסר. גם י"ל שעדים מעידים על מקרה שכ’ בשטר, וזה הוכחה שניתן כדין, בעדים. נחשבים על נתינה, כיון שמה שמעידים שגט חל מוכיח לנו שיש נתינה. יל"ד לר"ן אם צ"ל ע"ח לשמה. כ’ שפ’ מזוייף מתוכו הוא פ’ מח’ כשאין ע"מ. משמע שצ"ל לשמה (אבל לא מוכח, שכותבו בח’, ושם סובר כרמב"ן, ולא כצד זה). לקצות, ק"ק.
** ר"ת תוס’ קצות ראשונים יש רמב"ם יש רש"י
כ’ שצ’ ע"מ אף לר"מ, שאין דבר שבערוה פחות משנים.
מביא ראיה נגד רמב"ן מע"מ שלא יודעים, שלא כשר לר"א בע"ח. לכאו’, ק’ לר"ת, שלכו”ע יפ’ כיון שצ’ ע”ק. צ"ל שלר"א ע"מ כרתי, ולכן צ’ לדעת; אבל לר"מ, לא צ’ לדעת, שהם רק ע"ק. ק’ מה סובר חול’ על ר"ת (לכאו’, צ"ל שרמב"ן חולק, שאל"ה, בוודאי צ’ ע"מ). לר"ן, י"ל שע"ח מקי’. (אולי ר"ת לא יח’ על ר"ן במה מעידים, אלא יאמר שעדות כזה לא מקי’.)
כ’ ש"אדשב"ע פחמ"ש" אומר שחלות צ’ להיברר (ולכן לא צ’ ע”ק בד”מ). א"צ ע"מ כדי לברר. מק’ ע"ז שליח יכול להיות עד לברר, אבל יש שיטה שלא כשר לע"ק. יש
שמצדדים (ואולי ר"ן סובר כן) שאין ג’ צ’ ע"ק של דשב"ע, כיון שלא חב לאחריני.
שכ’ שאיסורה לכהן נח’ חב לו. (ק’, שכבר אסורה לו. יל"ד שמיתתו היה מתיר אותה לכהן.)
כ’ שצ’ ע"מ כיון שצ’ ע"ק, שהוא דשב"ע.
שמק’ שצ’ אף בלי"ז, להיות "כרתי.”[fn:77] גם
כ’ כרמב"ם.
** רש"י ראשונים רמב"ן ר"ש
מפ’ שעדים שכרתי נותנים כוח לגט. לכאו’, בא למעט מצד שעושה חלות ג’. יש
שמשמעים כצד שני.
כ’ להוכיח שע"ח מהני שמצאנו כבר ש"עדיו בחתומיו זכים לו" (חלות חל בחתימת עדים) אם בא ליד הקונה. שם, לכאו’, אין עדים רק עושים שטר, אלא עושים חלות.[fn:78] עפ"ז, בא
שאם ע"ח כרתי, חלות נעשה בחתימה, ואז א"צ ע"ק בשעת מ’. לכאו’, אצ"ל שעושים כל החלות (כמו שיהיה בהכרח[fn:79] למד"א אין עדיו זוכים לו); אפשר שהם חלק מסיבה לחלות. זה ג"כ יבאר יותר כל דיני נתינה (ור"ש יאמר שכולם חלק מן התנאי לחלות ח’ עדים). לכאו’, אם ע"ח ר"ל כן, ע"מ ירצה לומר כן ג"כ. א"כ, מש"א ר"א, לכאו’, אינו אדשב"ע פחמ"ש.
** רש"י רמב"ן
ר"י פוסל בפו: כיון ש"לא ידעי….” היה אפשר לומר שאומר שלא ידוע, אבל רש"י אומר (וכן משמע) שלא יודעים עדים.
מפ’ שצ’ עדות ברורה לשמה. באביי, רש"י כ’ ש”לה” קאי על "וכ’ ונ.’" ק’ מהי"ת שקאי על נ’.
ג"כ מתחיל בדיון על ידיעת ע"מ, ושוב דן בנ’ לשמה. באר’ שכדי לעשות חלות, צ’ שעדים עושים דבר, ולא רק רואים. צ"ל משתתפים בנתינה ע"י ראייתם של נתינה הנעשה לשמה.[fn:80] עדיין, מקור לזה צ"ב.[fn:81] אז, מובן מש"א רמב"ן ש"כיון שעמ"כ, צ’ נ’ לשמה.”
** תוס’ רש"י תוס’ רע"א אבנ"מ מרדכי ר"נ
כ’ שאם הוח’ שני יב"ש, פסול.
לכאו’, חול'.
מוסיף שצ’ לדעת שבעל עשה אותו שליח.
הק’ שגמ’ אומר שלא צ’ שע"מ ידעו ששליח הוא, אלא שעדים אחרים ידעו.[fn:82]
מק’ על
שכ’ שאם ראו עדים זריקה, ולא ידעו אם קרוב לה, אין ע"מ, שבמק’ בפחות משו"פ, חוש’ שהוא שו"פ במדי. לכאו’, עדים לא יודעים אם מקו’. באר
שמצרפים כתות, ומס’ עדים במדי יודעים אם הוא ש"פ.[fn:83] א"כ, י"ל לק’ תוס’. ק’ שמהי"ת שיש עדים בשליחות להול’. שם, קאי על ע"ק, אבל כאן קאי על עמ"כ, ויש לחלק. גי"ל’ שצ’ עדים על מעשה חלות, ולא לדעת שחלות נעשה.
** ר"נ תוס’ בעה"מ ר"נ רמב"ם ר"ש רוזובסקי
ת’ שעדים מכשירים שטר רק אם חות’ עם דע"מ. אפשר שזה מה שעושה שהוא שטר.
כ’ כעי"ז בכתובות ולא הביא מקור, ו
דרשו ממפי כתבם, ולא כתבו. לבעה"מ, יהיה שטר, אבל לא יהיה העדות שבשטר מהני. מתוס’, יותר משמע שעושה שהוא שטר.
אפ’ רק כתוס’. כ’ שע"מ שעושים שטר צ"ל בדע"מ. מביא סמך מ
שכ’ שהעושה שליח להול’ צ"ל לתת בפנ"ע. רק אומר כן בגט, לכאו’ מפני שצ’ זה לדע"מ. אם ע"מ לא יודעים שבעל שלח שליח, לא יודעים דע"מ (מניח שצ”ל לא רק מדע"מ, אלא שיודעים שהוא מדע"מ), ולא יכולים להשוות השטר.
מעורר שרק רצו שישוו שטר לינתן לשליח לקבלה. אז, ק’ שאף בשליח לקבלה צ’ לדע"מ. צ"ל שלזה לא צ’ לדעת בברור.
העיר’ שלא פשוט שנצ’ דע"מ, שאי"ז כ’, ועוד שאולי רק צ’ כדי להכ’ עדות, ולא לשוויה שטר.
** תורא"ש
זה אינו כ
, שבאר שהחסרון הוא פסול שדומה לפסול גט שאינו מוכח מתוכו לר"מ (ומביא משיטת ר"י בפו). (אגב, מתו"ד, רואים שהחסרון שם אינו כרמב"ן ותוס’. לזה, צ"ב מה השיב אביי; צ"ל שחלק בסתימות, והשיב לד"א.)
** קה"י תורא"ש
כ’ שע"ח צ"ל מוכח מתוכו, שמעידים שחל, וכמ"כ ע"מ. כ’ שיש שני מהלכים בדין מוכח מתוכו. לכאו’, צ"ל מוכח עמהם מה הם מעידים. גי"ל שצ"ל מוכח מגט ע"מ קאי גט. אם ע"ח כרתי, צ"ל כצד שני. גם לר"א צ"ל כן, וצ"ל שעדים חלק מגט. אז, בציור דרע"א, גט מעיד מה שלעולם מעיד, והוא שגט רק צ’ להוכיח שיחול אם נ’ מאיש מיוחד לאשה מיוחדת. אם יש שנים באותו שם, אז לא יודעים מאיזה יבוא. מוכיח מ
שהוא חסרון בעדים, ולא בגט, שכ’ שכמו שע"ח צ’, כך ע"מ צ’. א"כ, עדיין ק’.
לכאו’, רע"א הניח שאינו מוכח מתוכו, אלא שע"מ צ"ל יודעים הכל.
אם עדים רק מוכיחים דע"מ, ק"ק למה צ’ מוכח מתוכו. לכאו’, צ’ להעיד אף מי היה לו דע"מ, שמעידים על מה נאמר להם בשטר, וזה לא ברור. גם אם מעידים על מאורע, אין דין מוכח מתוכו שצריך לדעת מעדים אם חלות נעשה, אלא על איזה חלות. ממילא, אין בעיה בק’ רע"א.
רא"ש מביא ראיה למוכח מתוכו מגמ’ פו:. ק"ק שאביי חול’. עכ"פ מחו’ שהבעיה אינו נ’ לשמה, אלא מוכח מתוכו. אף שיודעים מח’ שני גיטין שבוודאי מגו’, לא יודעת על איזה, ואז לא מהני. אביי סובר שמהני כיון שבין שניהם בוודאי חל. לשון אביי ק"ק.
** תוס’ אחרונים יש יש יש יש
כ’ שאולי ע"ח בממון מהני כהודאה. קצות מפ’ שע"ח לעולם משווים שטר, וצ’ ע"מ לר"א רק לקיים. בממון א"צ קיום. נמצא שני מח’ בין ר"מ לר”א, ואחד הוא רק בדין קיום (אם לא שנאמר כר"ת). כמ"כ יבאר תוס’ (י) שכ’ ש"ידוע ע"י ע"ח.” זה מבאר למה ע"ח משווים שטר, אף לר"א. (לשון תוס’ שם ק’ על תוס’ כאן.) מק׳
למה צ"ל ע"מ לשמה לר"א, כיון שלא בו משווה שטר.
שכ’, ומדי’ מלשון "ידוע…,” שמה שמשווה שטר אינו חתימה, אלא היותו ידוע שנמסר (כמש"כ ר"ן לרי"ף). ק"ק שיהני לזה ולא לקיום. קצות מציין לרש"י שכ’ שצ’ ע"מ מח’ שאדשב"ע פמ"ש. מש’ שרק צ’ לע"ק.
שכ’ שמלשון רש"י (“דאינהו עשו כריתות") משמע נג"ז, אלא שאדשב"ע פמ"ש רק מהני שנוכל להניח שצ’ ע"מ לעשות גט.
שכ’ שזה מקור שצ’ שני ע"מ, ולא אחד.
שכ’ נג"ק של"צ ע"מ להשוות שטר, שהודאה עושה כן. ק’, אז, למה צ’ ע"ח, כיון שהיות בע"ד בחלות יהני. (יש צד של"צ עדים כלל, אבל תוס’ משמע שצ’.) צ"ל ששטר צ’ שיגיד שטר דבר; בלי עד, אינו ראיה (ששטר הוא דבר שמוכיח דבר- אף אם יודעים כן רק כיון שיש ע"מ). לא קל לבאר כן לקמן (י), שמשמע שע"ח עושים דבר להשוות שטר.
** יש קצות רש"י
כ’ תוס’ שמהני "במקום הודאה.”
שכ’ שמהני כשיש הודאה. ק’, שלעולם יש.
כ’ שע"ח הם במקום הודאה (תחתם). צ"ב.
ביבמות שדימה אותו מהוציא כת"י, שגובה. נמצא שצ’ ראיה להוכיח שנח’ שטר. כיון שהוא אף בגט, צ"ל שאינו גט מח’ הודאה, אלא מח’ שבע"ד כ’. אולי הוא מפני שעיקר שטר הוא דע"מ. תוס’, אולי, דן בשטר שכ’ בע"ד, ומכשיר בממון. נמצא שני אופני שטרות- של עדים ושל הודאה. זה עושה שהוא שטר ומוכיח דבר, אבל עדיין צ’ ע"מ לתת לו כוח לעשות חלות. אולי צ’ זה רק בשטר שיסודו עדות, ולא שיסודו הודאה; אותו שצ’ הודאה רק צ’ הודאה לתת כח לעשות חלות. תוס’ מח’ שאינו כן, אלא שאף אם יש בו עדים, סגי בע"ח בחילוף הודאה. אז, עדיין אומר כפשט של קצות, אלא מבאר שההו"א שבא תוס’ להוציא ממנו הוא שהודאה רק מהני לזה באופן מיוחד, אבל ע"ח לא יהני לזה כאן. א"כ, לא שייך לתוס’ לקמן, שלא בא לבאר זה. (אמר’ שכשאמר "וכן כשר…" ר"ל בשטר שראיתו בא מכת”י.) כשכ’ כאן "הודאת בעל דין,” ר"ל שטר של כת"י.
** רע"א
הק’
ל"ל מת’ גמ’ שרבה סובר כשמואל, שסובר שכתב סופר ועד כשר. נמצא שבכל גט שיש עליו שני עדים, סופר הוא עד שלישי. אז, צ’ שסופר לשמה יכ’, שאם אינו לשמה, בטל מקצה ואז בטל כולה. כ’ שצ"ל שרק אומ’ כן על פ’ בגוף עד, שפסולו פשט בכל עדים. מק’ עליו שיש ראשונים שכ’ כן על עדות שא"א יכול להז’. גם ק’ ק’, שאי"ז פ’ בעדות. מזה רואים שכיון שע"ח כרתי, הג"ע עושה שטר. אם לא עושה שטר, צ"ל שהג’ פסול.[fn:84] לא מש’ שת’ חוזר בו (יש שכ’ שחוזר). אפ’ לת’ מש"הק’ שרק בביטול בנאמנות, ולא בעדות בד"א, אומ’ כן. ק’ מהי"ת.
** גמ רש"י ריטב"א
’ כ’ שגט שכ’ בעל בלי עדים, כשר.
ביבמות כ’ שמהני לגבות (ורואים שהוא שטר).[fn:85] ה
הק’ מהו הראיה, ששם הודה. לכאו’, ריטב"א ר"ל שנתינת שטר ה"ה ראיה. אולי רש"י סובר שאינו ראיה די, וצ’ כוח שטר. גי"ל שרש"י סובר שעל כת"י לא יכול לטעון פרעתי, ואז רואים כח שטר (כר"ח, שכ’ ששטר הוא כאילו התנו).
** רש"י ראשונים רא"ש
(פו) כ’ שני מהל מי מכ’ בכת"י: דורש שכת"י מהני מלשון "וכ’ ונ’,” שמש’ שבעל כ’ ונותן[fn:86]. (אולי צ’ ראיה כדי לד’.) ק’ מהי"ת שאינו כר"מ. אם נאמר שצ’ שליחות בעל, משמע שוכ’ קאי על בעל, ואז הו"מ לומ’ שחתימות עדים בשלחות מהני. אז, הו"מ לומר כזה בר"מ, שלא אומ’ שצ’ ע"ח אלא בעל. ג"פ שכת"י כמאה עדים. לשון רש"י מבולבל, שכ’ אח"כ שאינו כר"מ (ב"ח מוחק מש"א שהוא ר"מ, וכ’ שבא מתוס’). יש
שמביאים זה מרש"י (
כ’ שבא מתשובה מרש"י).
** יש רשב"א ר"ת רשב"ם
לעלכאו’, רש"י סובר שאדשב"ע פחמ"ש. אז, ק’ איך כת"י יהני.[fn:87]
שת’ (ויש ראשונים נג"ז) שהוכחה שניתן מקיים.
מביא צד שר"מ הוא, ודורש מ"וכ’" שכת"י מהני כיון שהוא כמאה עדים. לכאו, ל
צ’ ע"מ לקיים.
כ’ שזה מהני כיון שבדיעבד עמ"כ. הק’ ל"ל הוק’ משנה כזה, שלכאו’, כשיש ע"ח.[fn:88] א"כ, ק’ למה א"א שמשנתינו כאותו תנא.
** ריב"ם ראשונים ר"ן תוס’ יש
חי’ שחת"י מהני. הוה אמינא קל לפי ביאור ראשון של רש"י. מביאים
ראיה מחתם ידו של ממון, ואז צ"ל דלא כזה, אלא שאינו הוכחה. י" שמהני רק מפני תוקף שטר (כרש"י שלעיל).
דן אם צ’ חת"י. לכאו’, דיונו הוא אם בלי ח’ הוא הוכחה, וזה דיון מס’. (כ’ צד שכ’ שמו בגט מהני לח’. ק"ק איך זה מהני הוכחה לעשות שמעיד יותר. ויל"ד שאולי מכוון לזה, אף שאינו בתחתונו (ואולי כוונתו לשיטה אחרונה).
כ’ שח’ מהני כיון ש"אין לך ח’ גדולה מזו.” צ"ב.
שכ’ שחות’ לדע"מ, ופשוט שזה מגלה דע"מ. תוס’ לא משמע כ"כ. אפ’ שלא מבאר דין, אלא מבאר למה א"צ חתם ידו.
** יש ר"ש ראשונים רשב"א רא"ה רמב"ן ריטב"א ר"ש
ק’ למה אין בעיה של "אין דבר שבערוה פחות משנים.”
שכ’ שאם עח"כ, ולא צ’ ע"מ לק’, מקו’ ע"י הוכחה.[fn:89]
מביא ש
דנים למה אין בזה אדשב"ע פמ"ש (בגיטין; ודנים אם כשר בשט"ק.)
פ’ בק’ כיון שאדשב"ע (אבל בגיטין לא חב לאחריני או תורה גילה כשרות מוכ’, ולא לומ’ מג’ לק’ (שצ”ל שדבר קאי על שום דין)).
בשם
מכשיר בק’. (
כ’ שהוא כש"כ. צ"ב.) מראשונים שפוס’ בק’, צ"ל שאין הוכחה מהני לע"ק.
כ’ שלרשב"א צ"ל שע"ח מהני מפני שאז נעשה החלות, ואז ע"ק אז מהני. זה מחו’, שלכאו’, נ’ עושה חלות, וח’ עושה גט. אף אם ח’ עושה גירושין, לכאו’, שניהם כורתים. כמ"כ י"ל בכ’ גט נוכ"ל לר"א, אלא שר"א סבר שאין צ’ עדים בכ’. א"כ, ק"ק לל"א כן לר"א, שנאמר ש"וכ’" הוא הסיבה, כמו שאומ’ בר"מ. (העיר’ שא"כ צ’ עדי קיום על כל ח’, ודין זה נאמ’ בגמ’ מטעם אחר.) (צ"ל כן אף לר"א בכת"י בעל (והודאת בעל מהני, ואף לא צ’ ע"ח).[fn:90])
מניח שהבעיה של ראשונים הוא בע"ק. אפשר שדנים במה נותן לו תורת שטר, שאין עדים עליו, וצ’ עדים כיון שדבר ערווה היא. ראשונים כ’ לשונות שמש’ כן; רשב"א כ’ שבגט גה"כ ש"שטר גמור הוא…,” וריטב"א כ’ ש"כ’ ידו חשיב כעדים למעבד מעשה בשטר.”
רשב"א כ’ שלא ללמד לק’ כיון שצ’ לקיים אדשב"ע בשום מקום. ריטב"א כ’ שק’ חב לאחרים, ולכן לא ילפינן. לכאו’, זה קאי על הצד שגה"כ הוא (וק’ למה צ’. אולי קצת חב לאחרים.), וכשמביא רא"ה, כ’ שהוא כש"כ. הכש"כ הוא שיותר קל לעשות חלות לחומ’ מחלות לקולא. יל"ד למה מוסיף כש"כ זה.
** רש"י ריטב"א נמ"י ר"ח רמב"ם ראב"ד ר"ח
כ’ שרואים שכת"י שטר ממה שנח’ שטר בממון. הק’
ב
שבממון צ’ ראיה, וכאן צ’ כריתות. לכאורה, מק’ שהוא רק ראיה, אבל לא שטר.
לא מפ’ כן, אולי מפני שראיה צ’ תורת שטר או מפני שכדי להיות ראיה צ’ תו"ש. מוכיח שלא כפ’ זה כיון שת’ הוא שנל’ מוכ’, ואם מק’ מהי"ת לעשות יותר מראיה, עדיין ק’ מהי"ת לעשות חלות ממון.הומ"ל שהוא כש"כ, שהוא בע"ד ביותר. פ’ ר"ח, אז, בק’ שהוא מהי"ת שמהני כאן שצ’ שנ"ע לערווה. אלא, צ’ קרא. באר שרש"י (לשיטתו, כ’, אבל צ"ב, שרש"י (פו) משמע נג”ז) סובר כר"ת שלעולם צ’ שנ"ע בשעת נ’. אז, יש שנ"ע. העיר’ שלכאו’, רש"י כ’ שנל’ מגה"כ. אז, צ"ל שרק מביא הוכחה לדרוש קרא כן, ואז יכו"ל שהוא ממה שהוא ראיה או משווה שטר ממון. מניח שבעיה של ראשונים היה קיום (על”ע שכ’ שאולי קיום אינו בעיה לענין קיום, אלא לענין אשווי שטרא.). יל"ד מה אומ’ גזה"כ. אולי הוא שלא צ’ שנים או שנח’ כשנים. ר"ח כ’ שאשווי שטרא רק צ’ הוכחה, ולא עדים. צ’ עדים מח’ קיום. יל"ד למה הוא כן, ולמה רק בע"ק צ’ עדים.
כ’ ששליח לקבלה צ’ עדים, אבל שליח להול’ ל"צ. מביא ראיה ממה שמביא גט כשר, אף שא"ע שהיה שליח.
דוחה שגטו מוכיח עליו, ולכן נאמן.
ת’ שגטו מוכיח לא יהני לע"ק, ואף שרמב"ם סובר כרי"ף (ששם יש עדים בגט על גט).
* Footnotes
[fn:1] לכאו', רצה לומר שקראו לו חז"ל ”גט“ כדי להודיע לנו דין זה. אז, תוס‛ לא אומר הסיבה, אלא אומר המקור. (עיין במהרש"א.)אם לא נאמר כן, צריך לומר שדורשים גמטריא ממנו או מפני שהוא בלשון הקודש או מפני שהוא הלשון שמשתמשים בו בכל זמן גבי גט אשה.
[fn:2] יל"ד ל"ל נקרא טג. אולי מקדימים הקודם בא“ב. גם יש לומר שיש ט ואחר כך ג. ותחשב.
[fn:3] וא"ת איך נקרא כן קודם גמר תנ"ך. ויש לומר שנקרא על שם עתיד. גם יש לומר שלא קראו גט עד אחר גמר תנ"ך. גם יש לומר שמה שלא היה בתורה הוא די, ורק מוסיף גר"א שאף לא בתנ“ך.
[fn:4] יש להעיר שבכל אלו, יש להפך לעשות הסימן סיבה והסיבה סימן.
[fn:5] גם יש לומר שלא צריך לומר כיון שקשה לו להיות רואה כתיבת וחתימת גט, שאין בעל עושה אותו, אלא אשה, ואשה לא יודעת לומר לו על כתיבת גט (ואולי בעל לא יודע שיש שליח).
[fn:6] אם כן, אם נותן הבעל משליח הולכה לשליח קבלה, צריך לומר, ”בפני נכ'.“
[fn:7] יל"ד אם הענין הוא שכבר חל לזמן, ולא עירר (או שבעל רק יערר כשחושב שלא חל), או שלא יערר אם הוא עשה שיחול, או שלא יערר אם חל מיד אחר מעשיו.
[fn:8] אף אם יש לחוש רק אם בא בעל ועירר, לכאו', לא יהני מה שאומר ר"ן, שזה רק עושה שלא כל כך מסתבר שבא בעל, אבל כיון שמניחים שבעל לא ישקר, זה לא יעשה שאינו כל כך מסתבר שיבוא בעל. ותחשב.עדיין יש לומר כמו זה שכמו שאין אדם נותן גט אלא אם כן בוודאי רוצה בו, כך לא נותן אלא אם כן יודע בוודאי שיחול. ויל"ד, שאולי חוששים שאינו בידו לדעת זה, שממש אינו יודע ההלכות. ותחשב.
[fn:9] רבי באר שהוא מפני שהוא זמן חלות גט, שהוא זמן חשוב. גם יש לומר שהוא מפני שהוא שליח אז, מה שאין כן אם כבר קבל את הגט. ותחשב.כמו כן יש לומר ששליח לקבלה לא היה לעולם שליח כל כך חשוב (שכמו שבעל יותר חשוב לגט, אולי (שצריך דעתו), כך שלוחו יותר חשוב). ותחשב.
[fn:10] ר"ל, הנתינה משתנה על ידי אם יש דיבור זה עמו. כדי לשנות את הנתינה, צריך להיות אותו דיבור עמו. גם יש לומר שאופן התקנה היה שכללו רבנן את זה בתוך איך לתת את הגט. יש לדון למה יעשו כן. ותחשב.
[fn:11] יש לדון, אז, אם יהני אם לא אמר "בפני…,” ובאו עדים לקיים השטר אחר כך. ותו"ת.
[fn:12] אינו כל כך ראיה, שקל לומר שלא מצוי שפקח יתחרש. גם יש לדחות ששם גמרא מדבר על שליח להולכה (ומה שמצוי בשליח לקבלה אולי לא יהני, שאינו מצוי בשליח הזה, שהוא שליח להולכה).
[fn:13] יש לדון אם זה סיבה (קדושה עושה חביבות) או סימן (כיבוש של בבל עשה קדושה מחמת חשיבותו, וזה מה שעושה החביבות.
[fn:14] יש לדון למה. אולי יש קצת קדושה (או דבר טוב) שיש מזה. גם יש לומר שמה שהוא מיוחס לקדושה עושה שהוא חביב, שאותו קדושה שלו מיוחס הוא חשוב.
[fn:15] יש להעיר שעד אחד מהני כאן. אולי זה רק מפני שלא מסתבר שיטעה או ישקר, כמו שאומר גמרא. גם יש לומר שכיון שזה מהני, אין צורך לעוד תקנה לעגונות. ותחשב.
[fn:16] גם יש לומר שכיון שמשנה חידש שצריך דיבור ללשמה, רואים שמאמין את הבעל, ואז גם צריך קיום השטר. אז, מבאר איך לקיים את השטר. עדיין יהיה הדין שחידש רבי (שהוא נאמן לקיום) נכון, שרק אומר דין זה בארץ ישראל. ותו"ת. היה אפשר לדחות שקיום מהני ונצרך בכל מקום, אלא שלא רגיל לערר עליו בחו"ל כיון שכבר אמר עד אחד נגדו, ואף שהיה נאמן נגד העד, היה נראה קצת כמשקר. ודחוק.
[fn:17] יל"ד למה עשו כן:כיון שחייבו לומר כן, האמינו אותו.כיון שרואים שמאמינים אותו לענין ”לשמה,“ מאמינים לענין קיום. קיל"ד למה.
[fn:18] צריך ביאור, שפרעון עם מה שמניח שטר בידו אינו פרוע. אולי אין זה קרק’ כל כך. ויש לדון, שהיה אפשר לומר כן אף בזיוף, שבני אדם מזייפים בכמה מקומות, אבל רק לא כשמלווה באותו זיוף. ויש לדון, שאולי אין המציאות כן. גם יש לומר שזה קרק’ יותר חשוב.
[fn:19] גם היה אפשר להיות נפק"מ כשהודה שלא פרע הלווה, אבל אינו יודע אם אינו מזויף. גם יש לומר שדן בו כיון שהוא נוגע לסיבת דין של גט (אם הוא מפני תקנת עגונא או מדין).
[fn:20] אין זה כל כך ק', שתוס’ חוזר לקושיה זה.
[fn:21] לא הבנתי, שגמרא דן בזה, אם נאמן תוך זמנו לומר שפרוע אם יש לו מגו. וצריך לעיין שם.
[fn:22] צריך ביאור, ששם, כלאורה, אין ראיה נגדו, ששטרו בידו בעי ובעי, שיש לו שובר, ואינו צריך להוציאו. ויש לדון.
[fn:23] כאן הזכיר רבי שיש לדון אם יש להניח שלשונות שהם קצת חלוקים אומרים דברים קצת חלוקים.
[fn:24] צריך ביאור ל"ל אומרים שאשה זייפה. אפשר שאם כן לא יהיה ביד שליח. יש לדון, שאולי מערמת. גם יש להעיר שאז ייצא חידוש שדין של משנה הוא רק כשהוא ביד שליח. גם יש לומר שאשה לא תעשה כן.
[fn:25] אפשר ששני דברים שאומר הם שהוא לא חסר כל כך (שאין לו זכות, שאינו הפקעת ממון), והיא נרווחת. צריך שנים אלו כדי לתקן.
[fn:26] נראה שאולי ענין "ברשות עצמה" ר"ל שרק דנים בזכות אשה, שרק רשותה מפסיד, אבל לא רשות בעל, שאינה לעלום ברשותו, וכיון שכן, רוצים שלא תהיה עגונה, ולא חשים לצער בעל. כעין זה אמר ר"ק.
[fn:27] כן אמר’, אבל לקמן יביא שר"ן לא אומר כן. שובאר’ שאמר שניהם.
[fn:28] ק’ מהי"ת שאינו נאמן כיון שהוא בע"ד. נ’ שרק מוכיח שיש לו פסול, ומוכיח מראשונים שאינו בע"ד.
[fn:29] לא הבנתי מה אומר, שאז היה לנו להחזיר ללוה, שאיזה קלקול ייצא.
[fn:30] גם דייק רבי ממש"א תוס’, “לא יגבה מן הדין.”
[fn:31] יש לחלק בין כאן, שהוא ממון, לשם, שהוא איסור. יש לומר לשני הצדדים. יש להעיר שתוס’ כאן סובר שמה שצריכים בממון צריכים אף באיסור. עדיין יש לומר שאולי הענין הוא שכיון שהוכשרו, נעשה מוחזק, ואין מוציאים ממנו.
[fn:32] גם היה אפשר להקשות למה צריכים קרא של "וכתב לה.” שוב אמר’ כן.
[fn:33] יש לדון למה רק חוש’ לאלו, ולא לשלא לשמו כלל.
[fn:34] יש לדון שאולי נוטל אותו, ואומר לעדים שיחתמו לאיזה שיברר.
[fn:35] איני יודע אם אומר שמעידים כן על מנת שיהיה בידו, או שמעידים שיקרה כן על מנת שיהיה בידו. צריך ביאור מה זה אומר.
[fn:36] לא הבנתי כוונת רבי בזה, שלכאורה, אותם אחרונים רק אומרים כתוס’, ואז ית’ כשמ"ת תוס’ שם.
[fn:37] יש לדון, שהרי לא היה דעת לכתוב לזה. מניחים שדעת מתחייב לזה מהני. לכאורה, אז, לא לומדים מזה דעת גירושין, דעת לחלות זה, שזה לא רואים, אלא רואים מזה פרט אחר בשטר, והוא דין כתיבת שטר.
[fn:38] צ"ב למה צ"ל לשיטתו, שאולי צריך שני דברים- חתימה, ודעת מתחייב. כאן, יש שניהם.
[fn:39] לא הבנתי למה צ’ שיכתבו, שיהיה החתימה שאילו כותב ונותן…. נ’ שהבעיה בזה הוא שלא אומר כן. אם כן, יש לומר כן אף לנתיבות, שלא חתמו על זה. ותחשב.
[fn:40] אמר’ שלא משנה גי’, אלא פי’.
[fn:41] יש לדון אם זה ללמד לעדים או ללמד לסופרים. ותו"ת.
[fn:42] כמובן, זה גלגל החוזר.
[fn:43] יש לדון מה לנו שהיא מקבלת. אולי זהו דעת מתחייב. ק"ק, שגמ’ משמע שצ’ שליחות. אולי, אז, א"צ דע"מ. יל"ד, אז, למה אומרים שצ’ שליחות, ולא שבכל מקום מניח שמוחל.
[fn:44] אולי החילוק הוא אם צ’ לכתוב זה בגט.
[fn:45] עדיין ק’ שניה שבארנו קשה.
[fn:46] אגב, נראה שאפשר לומר שיש הגדה כל זמן שהשטר נחתם, שההגדה הוא שרואים השטר, ואומר דבר, וזה לעולם. מה שאומרים שזמן ההגדה הוא זמן חתימה הוא שההגדה נקרא על זמן של המעשה שעשה כן. ותחשב.
[fn:47] אם כן, לכאורה, לא נעשה כשבא ליד מלווה, כקצות, אלא כשנכשר, כשיש דעת מחייב (או בציור ריטב"א, כשנכ’ שטר).
[fn:48] לא מוכרח, שיש לומר שלא יבוא, אף באמת, כיון שלא יאמינו לו בנ"א. יל"ד, שזה צ"ל שחוששים שנאמין ערעורו, ולא רק שכן הוא, שאל"ה, מה לנו אם בא או לא.
[fn:49] ק"ק למה צ’ זה, שאולי אומר שמפני טובתה, נחוש שעושה איסור, ולא נקל לה, שאין זה יותר טוב.
[fn:50] היה אפשר לומר שמה שבעל לא מערער הוא רעותא, ולכן אין ערעור אחד נאמן. יש לדון, שיהיה ציורים שאי אפשר לבעל לערער.
[fn:51] מניח שידע כן כבר בגמ’. יל"ד, שלתוס’ אולי לא יודעים תקנת עגונות עד מס’ גמ’.
[fn:52] יש לדון אם יכול להיות צד שחוששים שיערער, ואז נאמן אותו, ואז יהיה איסור. תחשב מה זה אומר, שנראה שאינו אומר שום דבר.
[fn:53] אולי נאמן במגו, עד שנתקיים. שו"אמר’ שכ"א חת"ס.
[fn:54] צריך ביאור איך קיום חותמים מהני (לפי חת"ס).
[fn:55] צריכים לבאר, עדיין, ל"ל תקנו משום עיגונא כאן. י"ל שלא צריך, שיכול לסלק ערעור באופן אחר, והוא ע"י בפ"נ. א"כ, הוא כצד שני. גי"ל שלא תקנו למי שלא שומע לתקנתם. ותח’.
[fn:56] אפ’ לומ’ שאמ’ שפוס’ מח’ חשש לעז, שאין בעיה במה שפוס’ אותו, שאם הוא כשר, קל לומ’ ב"נ. אז, לא יעשה כ"כ רע, אלא יעשה שבדר"כ יסולק לעז.
[fn:57] קצ"ב מה זה. אולי ר"ל שיש צורך לדחות אותו צד מח’ ל"פ. ותח’. גי"ל שהוא כעין טענה. ותח’.
[fn:58] אצ"ל כצד שני, שי"ל שלא מעכב מח"ז, אלא שצ’ לחוש מח"ז, אבל לא צ’ לחוש די לעכב.
[fn:59] צריך ביאור למה יעשו כן רבנן, ול"ל רק עושים תקנה שיעיד אחד. אולי נעשה ממילא. צריך ביאור למה.
[fn:60] אגב: היה אפשר לומר שטענה יותר נאמן רק מפני שלא מניחים שאדם משקר. אולי טענינן רק אומר שאין צריך ראיה כזה. ותו"ת.
[fn:61] יש להעיר שכאן, אינו בשעת נתינה מדאורייתא.
[fn:62] יש לדון, שאולי יש קצת נאמנות כשלא נותן.
[fn:63] אינו מסתבר שבא להוכיח שאף זה פרט בנתינה, שזה פרט רק מפני שרבנן עשו כן. ותחשב.
[fn:64] שוב אמר’ שצ’ נתינה לכת’. לא הבנתי מה כוון לומר בזה.
[fn:65] לא כל כך פשוט לי שאית’ איסור, שלכאורה, רק הגיד אסור, אלא שמניחים שהוא בתוך אותו חתיכה. אם כן, לא יודעים מהו אותו חתיכה, אבל לא יודעים שהיה אסור. ותחשב. שוב אמר’ זה בשם הט"ז.
[fn:66] לא הבנתי למה חלוק משני דברים- אחד אסור ואחד מותר- שנתערבו. אולי שם יש ח"ה מלפני כן.
[fn:67] נראה שמש"כ רש"י יהני אף לזה (על כל פנים, ברוב ציורים), ורק מבאר טבל, שאומר גמ’, ושחיטה, לחדש שיכו"ל אף שהיה בידו, ולא רק שהוא בידו. עדיין קשה ל"ל הק’ תוס’ למה מונה רש"י את זה.
[fn:68] מעניין שצ’ עדות שזה אינו גיד, שלכאורה, ניכר שאינו גיד. באמת, צריך ביאור איך זה שני דיונים, שלכאורה, יש רק דיון אחד על כל מה שאוכל, והוא אם הוא גיד. שוב הק’ רבי כעי"ז. שוב נראה לי שאולי הוא מפני שבזה מכחיש ע"א, ואף שלא שייך לדיון אם הוא מותר.
[fn:69] לא הבנתי כל כך ל"ל, שיכול להסיר הגיד, וזה יתיר אותו.
[fn:70] לא הבנתי כל כך, שלא בא ממילא, שאולי תראה דם. אולי אומר שאותו שהייה מן הראשון עדיין בא מלה.מילא. מעניין שזה חשוב.
[fn:71] קשה, שאם רואה לאחר זמן, או אם טבלה לפני השבעה ולא רואה, אין הדין נשתנה. אולי הוא ל"פ.
[fn:72] לכאורה, ר"ל שאולי יתן אותו חוץ לבית דין אף שצריך לתת אותו בבית דין כדי לומר זה.
[fn:73] לא הבנתי למה צריך נקודה זה, שקל לומר שיש חשש שנאמין גט מחמת זה, כמו הפשטות. אולי אין לומר כן מח’ ק’ תוס’.
[fn:74] יש להעיר שלרי"ף אינו ראיה שיש ע"מ, ואז אין ענין זה.
[fn:75] מביא אותו בכ"מ. כן אמר רבי, אבל לא ידעתי על איזה מן השלש קאי.
[fn:76] עדיין צריך ביאור למה מהיכי תיתי שצ’ ע"ח אם יש ח’. אולי זהו הכ’ הכי חשוב, שמאותו כ’ מג’.
[fn:77] יש לציין לרש"י שכ’ שצ’ מפני אין דשב"ע פחות משנים. שוב העיר’ כן. איני יודע למה כל כך פשוט לו כן. דחה רבי ברש"י שלא היינו אומרים שעדים משווים אותו לגט אלא כיון שכבר יודעים שכבר צריך עדים לקיום. אי"ז אפשר ברמב"ם.
[fn:78] אולי עושים חלות על פי עשיית שטר. ותחשב. אם כן, כן יהיה גם כן כאן. ויש לדון, שאלוי כאן אף צריך נתינה.
[fn:79] יש לדון, שאולי אותו מד"א רק סובר שחל לאחר זמן. וצלע"ש.
[fn:80] איני יודע ל"ל אמר רבי בדרך קל שיש בעיה שכשאומרים שיש בעיה בנתינה ר"ל שיש בעיה במה שעושים ע"ח.
[fn:81] צריך ביאור למה אמר, אז, שעדים לא ידעי.
[fn:82] אולי צריך שעדים ידעו כל פרט, ולא אותם עדים. שו"א ר’ שאבנ"מ אמר כן.
[fn:83] זה מטעים עם שיטת תוס’ שרק צ’ שיוכל ליברר.
[fn:84] היה אפשר לומר שסובר שאומ’ עדות שבטלה… אף על שאר פסולים, ולא רק בפסול עדות. אולי ק’ מהי"ת.
[fn:85] לכאו’, רק צ’ זה אם הוא כר"מ. לא נ’ כן מרש"י כאן.
[fn:86] מרש"י כאן משמע שהוא כר"א, ופוסל מדרבנן.
[fn:87] אפשר לומר ככל הצדדים שכתבנו לדחות ר"ת לכאו’.
[fn:88] לא הבנתי מהיכי תיתי, שאולי רק צ’ ע"ח, אבל לא צ"ל לשמה. נ’ שאפשר שצ"ל, שאין הוכחה נגד זה, כמו שמצדד גמ’ לר"א ור"מ, וכיון שאין הוכחה נג"ז, נאמר כן. רבי היה משמע שהוא מסתבר, שסבר שוכ’ קאי על חתימה אילו יש חתימה. שוב אמר שאין זה מוכרח.
[fn:89] נראה שמסתבר לומר שאין צריך רק שנים, שלימוד בא ממה שיש יכולת להביא ראיה, והרי ראיה שיש בממון הוא בהודאה, והוא יותר חזק מכל דבר שיכול להיות בדבר שבערווה. אז, בין כך ובין כך צריך לומר שלא לומדים להיות ממש שווה. עדיין היה יכול להיות שלומדים מה שהוא הכי דומה, שהוא דבר הכי חזק. אבל, צריך לומר שאינו כן, ורק לומדים שצריך ראיה שפוסקים מחמתו. ותחשב.
[fn:90] לא הבנתי כל כך מה אומר.
