הערה:
רב אלעזר אומר שמי שטוען שמצא פ"פ באשתו נאמן לאוסרה עליו. לשונו משמע שלאוסרה עליו נאמן, אבל לא להפסיד את כתובתה, כמו שאומר רש"י.
הערה:
רש"י מוסיף שנאמן, אף שלא יכול להתברר אלא על פיו. לכאו’, כוונת רש"י הוא כך: לפעמים, אדם נאמן בדבר שעתיד להתגלות. כאן, אף שלא יכול להתגלות, הבעל נאמן.[fn:1]
שוי"א- למה נאמן:
צדדים:
הסיבה שנאמן אדם לאסור את אשתו ולטעון שפתח פתוח מצא הוא ששוויא אנפשיה חתיכא דאיסורא. בביאור שוויא אנפשיה חתיכא דאיסורא, חוקרים האחרונים[fn:2] למה הכלל נכון. יש שלש צדדים עיקרים:
1. שוויא אנפשיה חתיכא דאיסורא הוא נדר. כן נראה מלשון הכלל עצמו, שהוא ש"שוויא אנפשיה….” יש לבאר צד זה בשני אופנים:
  1. אפשר שמניחים שכשאמר כן, חשב לעשות איסור. אז, זה באמת נדר עם קצת דינים אחרים[fn:3]. נדר הוא כשאדם מכוון לנדור, ואומר לשון שתופס בדבר הנדור. שוויא אנפשיה חתיכא דאיסורא הוא כשאדם מכוון לנדור ואומר שהוא דבר האסור. גם יש חילוק דין ביניהם, שבזה אין שאלה, אבל בנדר יש שאלה.[fn:4]
כן נראה שמפרש אותו חתם סופר, שכ’ שאם מאמינים שטעה, וחושב שבאמת יש איסור, אין נדר, שאז בא להגיד לנו את האיסור, ולא לעשות נדר[fn:5].
יש להקשות על צד זה מהיכי תיתי שבא לנדור. הרי, תמיד יש לומר שאומר כן כדי להטעות את השומע. בנוסף על זה, יש ציורים שלא מסתבר שירצה לאסור את עצמו ככה.
  1. אפשר שאמירת איסור עושה שיש איסור[fn:6].[fn:7] אף שלא מכוון שיהיה איסור כמו שמכוון גבי נדר, עדיין האיסור נעשה
עדיין יכול להיות שהדין שאמר חת"ס נכון. אולי כדי שייעשה האיסור, לא מספיק שיאמר האיסור אם רק אמר כן מחמת טעות (שחשב שהוא נכון)[fn:8]. (אבל, עדיין מילים של חת"ס לא משמעים כצד זה, שלשונו אומר שנדר הוא, וממילא פשוט שאם רק טועה, לא יאסר.)
1. שוויא אנפשיה חתיכא דאיסורא הוא נאמנות[fn:9].
שני צדדים אלו גם גבי הודאת בעל דין, אם הוא נאמנות או התחייבות. ר’ אמר ששם מצאנו דינים שלא באים בהתחייבות, ואז משמע שנאמנות הוא[fn:10]. גם מצאנו פעמים שאין התחייבות שייך, ועדיין אומרים בהם שהודאת בעל דין כמאה עדים, ש"כל האומר לא לויתי כאומר לא פרעתי.”[fn:11] רבי גם העיר שמצאנו חילוקים בין שני הענינים (בענין אמתלא). אבל, קצות (לד) כ’ ששניהם שווים, כיון שסובר שדין שוויא אנפשיה חתיכא דאיסורא נלמד מדין הודאת בעל דין.
1. יש שמוסיפים צד שלישי. תרומת הכרי (א) מבאר שאף אם אין הודאת בע"ד שלא בפני ב"ד, יתחייב מדין שוי"א. מבאר שאינו נאמנות, אלא כיון שהוא חוש' שיש אי', חייב להח' ככה (כמו שאשה צ' כפרה אם עברה על נזי' שהופרה) אף ב"ד מצווים על אותו איסור.
משמע ששוי"א הוא שמאמינים שחו' כן, ולכן בוודאי יש איסור עליו לנהוג כן.
דחה ר' שאין מקור שנאמן שחו' כן. יותר נ' לומר שכוונת תה"כ הוא לומר שאין נאמנות ממש, כמו שיש בהודאת בע"ד (שם, נאמן על כל מה שאמר כשאינו מפסיד אחרים), אלא רק נאמן לענין דין שלו.[fn:12][fn:13][fn:14]
הוכחות:
הבאנו הרבה שיטות, כדי לדון אם סוברים ששוויא אנפשיה חד"א הוא נדר (ואיזה מין) או נאמנות:
1. קצות מביא שיטה משם יעקב. שם יעקב כ’ שאם אדם לא מבין שאוסר את עצמו (למשל, אומר ששוחט פלוני שחט, ולא ידע ששוחט פלוני פסול)[fn:15], אין דין שוויא אנפשיה חתיכא דאיסורא. קצות באר שזאת אומרת שנדר הוא. לכאו’, אומר כצד ראשון של אותו צד, והוא שרק נאסר כיון שמניחים שכוון לנדור. אבל, אם לא הכיר באיסור, יודעים שלא כוון לנדור.[fn:16]
2. ט"ז כ’ שאם אשה טוענת שנתגרשה (כשאין לה נאמנות), ואחר טענתה נתקדשה לאחר, לא צריכה ממנו גט. קצות ובית שמואל מבארים שהוא מפני ששוויה אנפשיה חתיכא דאיסורא הוא נדר. כיון שלא היה איסור בשעת נדר שלה, אי אפשר לומר שכוונה לנדור. זה מוכיח שט"ז סובר שנדר הוא, וכצד ראשון.[fn:17]
העיר’ שיש לדחות ששם מה שלא מהני הוא מפני שלא יודעת שיש איסור (שלא חשבה שתקבל קידושין מיד אחר), ולא מפני שלא מכוונת לאיסור. (בע"ה, נביא קצת ראיה מרע"א לדיחוי זה.)
1. מצאנו שלש דיבורים מרע"א[fn:18] ששייכים לנידון זה:
  1. תו"י (כב) מדבר על ציור שיש בו "כל האומר לא לוויתי כאומר לא פרעתי" באיסורים, ורע"א מקשה ל"ל אומריםבו שוויא אנפשיה חתיכא דאיסורא; ותי’ שאולי לא אומרים "כל האומר…" בשוויא אנפשיה חתיכא דאיסורא[fn:19].
  2. משנה אומר שמי שאומרת, “שבויה הייתי ולא נטמאתי" נאמת מחמת פש"א. הק’ למה צ’ פש"א, שאין שוויא אנפשיה חתיכא דאיסורא, כיון שלא אומרת שהיא אסורה[fn:20], והרי, כ’ רע"א, אין נאמנות כאן, אלא שוויא אנפשיה חתיכא דאיסורא.
ר"א העיר שאף שטוענת היתר, הודאה ראשונה עושה שוי"א, כיון שטענה סיבה לח’ איסור, כמו בהודאת בע"ד. (לכאו’, זה רק אפשר אם נאמנות הוא; ר"א כ’ בפי’ שנאמנות הוא.)
  1. רע"א כ’ בתשובה ששוויא אנפשיה חתיכא דאיסורא הוא נאמנות.
ר"ש למד מרע"א השני שסובר ששוויא אנפשיה חתיכא דאיסורא הוא נדר. (לא מפרש איך דוחה השלישי.) לכאו’, אם נדר הוא, יהיה פשוט שאין "לא לוויתי" שייך, וכמסקנת רע"א הראשון. אבל, העיר ר’ שאף למסקנא, לא ברור לרע"א שכן הוא. אילו היה נדר, היה לו להיות ברור לו. כמו כן, מהו"א שלו נראה שנאמנות הוא, ולא מסתבר שכל הלומדות נשתנה בין הקושיה לתירוץ.
אז, רבי פי’[fn:21] שיותר נראה לומר שרע"א סובר ששוויא אנפשיה חתיכא דאיסורא הוא נאמנות, ורק יש נאמנות אם טוען איסור. לכן, אין נאמנות בשני, ולכן מצדד שאין נאמנות בראשון.[fn:22]
1. תלמידי רבינו יונה (מובאים בשיט"מ) ורשב"א (שו"ת חלק ד) ומאירי אומרים ש"אדם נאמן על עצמו כמאה עדים.” מוכרח, אז, ששוויא אנפשיה חתיכא דאיסורא הוא נאמנות.[fn:23]
2. חולקים ראשונים אם שוויא אנפשיה חתיכא דאיסורא נאמן נגד עדים. (עיין לקמן.) אם אינו נאמן, צריך לומר שנאמנות הוא, שאם עושה איסור, איך אפשר שעדים יכחישו לו.[fn:24]
3. רשב"א כ' שאומרים כעין "כל האומר לא לויתי..." בשוי"א. לכאו', זה רק אפשר אם נאמנות הוא.[fn:25]
4. כמו שנבאר לקמן, דיון של מס' הגמ' שייך לזה.
5. רמב"ם כ' שמענישים ע"פ שוי"א. ממה שלא אמר שמענישים מחמת נדר[fn:26], משמע שנאמנות הוא.
גמ' מסיק שחי' של ר"א הוא שלא אומרים שכיון שלא קים ליה לבעל איך לדעת שמצא פ"פ לא נאמר ששוי"א. יש לדון מהו הקמ"ל:
1. קים ליה. כ"כ תוס' בפי' (ב.)[fn:27] וכ"כ ריטב"א ורא"ה. נמצא שאם לא היה קים ליה, לא היה איסור. לכאו', זה מוכיח שאין שוי"א נדר, אלא נאמנות.[fn:28]
2. אף שלא ק"ל, נאסר כיון ששוי"א. גמ' לקמן מחלק בין בחור (שלא ק"ל) ונשוי (שק"ל) לענין טענתו לאבד כתובתה. הרבה ראשונים מבארים שאין נ"מ לשוי"א. משמע שאף שלא ק"ל, שוי"א. לכאו', סוברים שנדר הוא.[fn:29]
אבל, קשה, שריטב"א ורא"ה כ' כן. כמו"כ, רשב"א כ' כן, אף שסובר ששוי"א הוא נאמנות. פי' ר' ששוי"א הוא נאמנות, וצ' שק"ל, ונאמן כיון שאמר שק"ל. (דייק ר' כן מלשון רשב"א.)
הערה:
יוצא ממקצת השיטות (ש"י, ט"ז) שצריך שהאומר יודע שעל פי דבריו יש איסור. אם כן, צריך לומר שבציור שלנו מדובר על מי שיש סיבה להניח שיודע דין שיוצא מדבריו[fn:30]. סתימות הגמ’ לא משמע כן.[fn:31]
נאמנות נגד עדים:
מאירי מביא מחלקת אם שוויא אנפשיה חתיכא דאיסורא נאמן נגד עדים. הרבה ראשונים מניחים שנאמן. אבל, מצאנו ריטב"א שהקשה למה אין לאשה (בציור של גמ’ שלנו) מגו נגד שוויא אנפשיה חתיכא דאיסורא. אם מגו נאמן- אף שלא נאמן נגד עדים- צריך לומר שעדים נאמנים נגד שוויא אנפשיה חתיכא דאיסורא. אבל, ריטב"א סותר א"ע, שבסוף קידושין כ’ שאדם נאמן על עצמו יותר מעדים.[fn:32]
מקור:
לא פשוט מהו המקור לשוי"א. אם גדרים שלו שווים להודאה, י"ל שנל' מהודאה. אם לא, קשה,[fn:33] וצ"ל שסברה הוא.
עונשים:
גמ' בקי' אומר שכוע"מ שאין אשה נסקלת ע"פ דיבור שלה. אז, ק' על הרמב"ם שכ' שעונשים למי שטען שכהן הוא ועבר על איסורי כהונה. מצאנו שני תי’:
1. משנה למלך תי’ שרמב"ם סובר שיש עונשים רק אם הוחזק. (דחוק, שרמב"ם לא מזכיר חזקתו.)
2. רע"א תי’ שיש לחלק בין עונש מלקות לעונש סקילה[fn:34].[fn:35][fn:36] ר"א מביא מר’ ליב רובין שמלקות באים מאיסור (או ממרידה), ומיתה בא ממה שהיא אש"א[fn:37].
וא"ת ל"ל פלגינן נאמנות.[fn:38] רב אלחנן תי’ שלא מפלגים בין סיבה (איסור) לתוצאה (עונש), אלא רק בין שני תוצאות של סיבה אחת. (עדיין, ק’ למה לא מחייבים מיתה, כמו שהז’.[fn:39])
כמו"כ, רמב"ם מזכיר שע"פ ע"א לוקים. גם בזה, חול’ אם צ"ל הוחזק. המקור מירו’, שלומ’ ממה שנאמן בעל להפ’ לסוטה כ’, ורואים שנאמן בד"א אגב איסור. בסוטה, א"צ שנתחזק. (ע"ז גכ"ק מגמ’ שהבאנו לעיל, שמשם מוכח שכיון שנותן תורה נאמנות, נענש.)
ספק ספיקא:
סיבת ההיתר:
יש לבאר ענין של ספק ספיקא. מצאנו שלש מהלכים יסודים:
1. פני יהושע צידד שרוב הוא. יש שלש דרכים לבאר את זה:
  1. אולי רוב ממש הוא. כל זמן שיש ספק ספיקא, יש יותר מחמישים אחוז צד שהוא מותר.[fn:40]
  2. אולי הוא רוב היכולות. רוב הצדדים שאפשרים הם להיתר.
  3. אולי רוב הסיבות לחשוב מה קרה אומרים לנו שהיתר הוא. כעין זה באר ר"ש בכמה רובים (כמו רוב דיינים, ורוב חנויות). רבי באר שכאן, יש רק מה שיכולת יש. אין זה סיבה לחשוב שקרה כן יותר משלא קרה כן, אבל כיון שהוא גורם לבני אדם לחשוב כן, מספיק.[fn:41]
תוס' כ' ששני הספקות של ס"ס צריכים להיות שקולים. לכאו', זה דוחה את הצד שהוא רוב ממש[fn:42]. אבל, עדיין אפשר להיות מין אחר של רוב (שי"ל שרק מחשיבים את הצד אם אין רוב נגדו). גם יש לפ' שס"ס הוא רוב ממש, אבל ספק שקול אינו חמישים אחוז, אלא לא נודע.
1. חולקים ראשונים אם סד"א לחומרא מדא' (כן סובר רשב"א) או מדרבנן (כן סובר רמב"ם). אם מדרבנן הוא, יכול להיות ביאור אחר בס"ס:
  1. פני יהושע באר שכיון שספק אסור מדרבנן, ספק ספיקא הוא ספק איסור דרבנן. סד"ר לקולא. העיר ר' שלכאו' אין זה נכון, שאינו ספק אם גזרו רבנן. רבנן גזרו במצב של ספק, ואין זה אותו מצב, אלא מצב של ס"ס. ספק תלוי במה שיודעים, ואז א"א להסתפק אם יש ספק.
  2. מרבינו דוד קצת משמע שכיון שאסור מדרבנן, יש לומר שרבנן רק גזרו על ספק, ולא על ספק ספיקא.
יש להוסיף שר"ש כ’ כעי"ז גם אם סד"א לחומ’, שיש איסור מיוחד על ספק. כיון שאין באותו איסור ס"ר, אין ספק שלו נאסר. וא"ת ל"ל חוש’ לאיסור שיש בו ס"ר. דן בזה, אבל לא מובן כ"כ מש"א.[fn:43]
1. אולי מרבינו דוד (ומלשון רש"י) נראה שלא שואלים ספק על ספק.[fn:44][fn:45]
ספקות שקולות- נגד חזקה:
תסו' כ' ששני הספקות של ס"ס צ"ל שקולים, ולא יכול להיות רוב נגד אחד מהם. חולקים אחרונים אם יכול להיות חזקה נגד אחד מהם.
1. שב שמעתתא כ’ שרק אומרים ס”ס אם יש חזקה על שני צדדי הספק, שאז הס”ס דוחה את החזקה.[fn:46] (צדד ר’ שאולי זה רק אם ס"ס מטעם רוב.) כ"נ מפרי מגדים.[fn:47]
2. יש שכ’ שאומרים ס”ס בין אם יש חז’ על צד אחד בין אם יש על שני הצדדים.
3. יש שכ’ שרק אומרים ס"ס אם יש חז’ על צד אחד, ולא אם יש על שני הצדדים.[fn:48]
תוס' כ' שבספק מתי נבעלה, יש חזקת הגוף שאומר שנבעלה אחר נישואים. חלקו אחרונים אם בין זה וחזקת היתר, נעשה מחצה על מחצה או לא (כיון שחזקת הגוף יותר בסיסי[fn:49]). אם לא נעשה מחצה על מחצה, צריך לומר שאומרים ס"ס אף אם יש חזקה באחד מן הצדדים (אבל אולי רק מפני שיש חזקה להתיר, אף שהוא חלוש, נגדו).
ואם תאמר מה בין ספק שיש בו חזקה לספק שיש בו רוב. אחרונים מבארים שרוב מברר מציאות וחזקה מגיד מה לעשות.[fn:50]  אז, כשמחשבים ספק של ס"ס, צריכים לחשב עם רוב (שהוא מציאות), אבל לא עם המציאות  (שהוא רק נוגע אחרי שהגענו לציור, ורוצים לדעת מה לעשות).
שם אחד:
תוס’ כ’ שאין ס"ס בשני מיני אונס כיון "ששני מיני אונס.” יל"ד למה:
1. ס"ס הם שני צדדים שמתירים מח’ דינים שונים.
2. ס"ס הם שני צדדים שהם שני מציאויות, אבל צ"ל שלכל מציאות יש דין שונה.
3. אולי צ"ל ס"ס המתהפך, שאם נבעלה ברצון, צ”ל גדולה. לא נ’ שתוס’ סובר שצ"ל ס"ס המתהפך, כמו שנבאר לקמן.
ס"ס שאינו מתהפך:
תו"י כ’ שא"א ס"ס שאינו מתהפך. (בארו שהוא מפני שאפשר להתחיל מצד שאין בו ס"ס. יל"ד, שגם אפשר להת’ בצד שיש בו ס"ס.) תוס’ חול’, שמק’ לל"א ס"ס ממכ"ע. וא"ת ייאסר כל קטנה שנישאת (שס"ס שלה לא מתהפך).
1. אולי תו"י סובר כרמב"ם, שאין פיתוי קטנה מותר לבעל[fn:51]. (אבל, הרבה חלקו על הרמב"ם.)
2. אולי כשיש דרך יותר מסתבר להתחיל את הס"ס, לא צ"ל מתהפך.
3. אולי מתהפך הוא. אם נאמר שצדדי ס"ס תלויים במתירים שונים, ולא במציאויות שונות, י"ל שהיתר אונס פיתוי קטנה והיתר קודם נישואים אפשר להפך.
להוציא ממון:
דנים הפוס' אם ס"ס מוציא ממון. מצד סברה, אם ס"ס הוא מדין סד"ר (או כעין מש"כ ר"ש), לא יוציא ממון. אם הוא רוב, ייתלה במח' רב ושמואל. (יש שני דרכים לחלק- אולי מין שונה של רוב הוא; ואולי רוב דאיתא קמן מוציא ממון (דנים פוס' בזה), ואולי רוב צדדים נח' רוב שאיתא קמן (כיון שהצדדים הם קמן)[fn:52].) אם הוא כמש"א ר"ד, י"ל שאין מוציאים.
מתוס' כאן (ע' לקמן) נ' שס"ס מוציא ממון. אבל, כמו שנכ' לקמן, ש"ך, פנ"י, וש"ש דוחים את הראיה. ש"ך מביא רא"ש שכ' שס"ס לא מוציא ממון. כמו שנכ' לקמן, ש"ש דוחה את זה.
תוס' (ד"ה אי למיתב) משמע שס"ס מוציא ממון. יש שלש דרכים לדחות:
1. פני יהושע כ' שרק מוציא ממון כיון שמצורף עם טענת ברי נגד טענת שמא.
יש לדון אם יש כאן ברי ושמא. הרי, הבעל לא ק"ל, אבל הוא ברי[fn:53] (אלא שטועה). נראה שזה תלוי בסיבה למה ברי חזק משמא:
  1. ר"מ פיינשטין פי' שהוא מפני שיש קצת הוכחה בטענת ברי. אז, אין לו טענת ברי.
  2. ר' שך פי' שהוא מפני שיש כוח לטענת ברי. אז, אולי יש לו טענת ברי.
הק' ש"ש מתוס' לקמן שכ' כן גם בטענת ברי נגד טענת ברי.
1. ש"ש כ' שרק מוציאים ממון כיון שמצורף עם שטר. שטר עושה קצת חזקה.
יש להעיר שכאן לא נודע שהשטר היה כשר מעולם. אז, אין חזקת כשרות לשטר. נ' שבאמת כל ציור כן. אם אשה מזנה, אין לה כתובה. זה לא מפני פ' בכ', אלא שכ' רק מח' כ' כשתעשה מה שאמרה- ולא תזנה. עדיין, שטר מהני כזה אם לא נודע שזינתה, אף שאין חז' כשרות שטר מורה. צ"ל ששטר גורם שנראה בו חיוב.
1. ש"ך בתקפו כהן כ' שכוונת תוס' אינו לומר שס"ס מוציא ממון, אלא לומר שכיון שס"ס מתיר אותה[fn:54], צ"ל שיש כתובה. יש לדון למה זה מוכיח שיש לה כתובה:
  1. אפשר שסובר שכתובה הוא תוצאה מהיתר פראקטיקאל"י שלה. כיון שהוא עוד נשוי לה, צ"ל לו כתובה, כדי שלא תהא קל בעיניו להוציאה.[fn:55]
  2. אפשר שסבר שכתובה הוא תוצאה מדין שלה. כיון שפוסקים בדין שלה שלא זינתה, כך נפסק בדין שלה שיש לה כתובה. כן יוצא מן התומים, כמו שנבאר.
יש להעיר שלא מוכרח שתלויים זה בזה; אפשר לומר ששניהם תלויים באותו דבר, אבל לא זה בזה.
הק' התומים (בפי' לקיצור תקפו כהן) מגמ' שלנו, שצדד שיש היתר ואין כ'. תי' שיש לחלק בין פסק ע"פ ס"ס לפסק ע"פ חז' היתר. בביאור התי', יש שכ' שמצרפים כוח ס"ס עם זה. גם יש שפ' שחז' היא רק הנהגה, ורק ס"ס קובע את הדין. לשני הצדדים, צריים לומר כצד שני בביאור סברת הש"ך.
יש שמק' על ש"ך מדין כהן, ששם משתמשים בס"ס, אף שנאסר. צ"ל שאיסור כהן שונה מאיסור ישראל[fn:56], ותלוי כתובה רק באיסור ישראל. זה גם אפשר רק לצד שני.
יש רא"ש שמשמע שאין ס"ס מוציא ממון. דחה ש"ש שרא"ש כ' כן רק שם, שאינו נח' ס"ס כיון שהוא ספק בדין. לא פשוט למה נחלק; אולי לפשט בס"ס שאין שואלים ספק על ספק יש לחלק.[fn:57]
הערה:
תוס’ מקשה פעמיים למה אין מוקמים אשה על חז’ היתר שלה. פעם אחת, מק’ ל"ל מוק’ על חז’ לבעלה ופעם אחת מק’ ל"ל מוק’ על חז’ לכהנים. (ע’ בתוהרא"ש שלא משנה.) לכא’, חז’ היתר לכהונה יותר גדול (שיש בו יותר שינוי); יל"ד ל"ל נקט רק זה.
חזקה:
ע’ בתי’ תוס’. יל"ד אם חה"ג יותר חזק מחה"ד (או שיותר חזק או שיותר יסודי) או שהוא שווה להח"ד. יש שכ’ שרק ח"ד כהונה שווה לחה"ג.
קושיה על ק’ תוס’ (בענין רוב כנגד ס"ס):
הק’ פנ"י שאינו רוב נגד ס"ס, שחלק מצד אונס הוא פיתוי קטנה.
1. תי’ שיש חה"ג שלא קרה כשהיתה קטנה. זה רק מת’ אם חז’ נגד שני הספקות דוחים ס"ס.
2. גם תי’שתוס’ רק מדבר בציור שנ’ כשהיתה גדולה. אז, כל באונס הם לפני נ’, וא"א שהתיר את ביאת אש"א.
3. אולי שני הצדדים אינם שונים במציאות, ששניהם הם שקרה כשהיתה קטנה.
פיתוי קטנה אונס:
בביאור פיתוי קטנה אונס, חת"ס כ’ שהוא משום שאין קונסים קטנה כמו שאין עונשים קטנה. אולי, אז, סיבתה לא שווה לאונס. (זה נוגע לדיון של מש"א תוס’ שכל מין אונס אחד.)
קושיה על תי' תוס' (בענין מה חזקה מגיד):
מתוס' יוצא שחזקה מגיד לנו שנבעלה לאח"ז, ואז מוכיח איסור. נמצא שחז' לא רק אומר לנו שלא נעשה דבר, אלא אף שנעשה מאוחר.
אם נולד תינוק ביה"ש (בין ע"ש לשבת), לא נימול בע"ש, ולא בשבת. אם ספק נולד בע"ש וספק נולד בביה"ש, לא נימול בע"ש, אף שיש ס"ס (אולי כיון ששני הצדדים יש להם שם אחד, שאומ' שנולד בע"ש ואולי כיון שהוא נגד חז' שנשארה האם מעוברת). אם ספק נולד בשבת וספק נולד ביה"ש (אם לא נסמוך על ס"ס, כיון ששם אחד הוא), אבני נזר כ' שלא נימול בשבת. אף שחז' אומר שנשארה אם מעוברת, לא יוכל לומר שנולד (אלא שלא נולד קודם לכן). ההסבר לזה הוא שחז' הוא הנהגה, ואז לא מוכיח מה קרה. (העיר' שעדיין מחודש שלא יגיד לנו לנהוג ככל מציאות שיוצא מהנהגתו.)
יש שמוכיחים נגד זה (וכתוס') מפוס' שכ' שספק אבילות הולך בתר חזקה. דחה ר' ששם תלוי בזמן שהוא חי או לא חי, ולא מתי קרה מיתתו.[fn:58]
יש שת' שמה שנל' מהנהגת חזקה מספיק לדחות חזקה, ולא לעשות חזקה.
הערה:
גמ' כ' שאשה נאסרה ע"י ע"א רק בקו"ס. יש להעיר שאז לא צ' ע"א, שכבר נאסרה ע"י קו"ס.
דין ספק סוטה:
ספק סוטה בלי קינוי וסתירה מותרת. ואם תאמר למה אינו כסד"א שהוא לחומ'. ר"י מיגש תי' שהוצאת אשה מבעל הוא כהוצאת ממון וצ' ראיה ברורה. ואם תאמר הרי זה רק סיבה שלא נכפה על גי', ולא שלא נאסור. (ע' בתוס' בזבחים שמצדד שאין חיוב לגרש סוטה, אלא שנאסרה בביאה.) וי"ל שאף איסור בביאה- שמונע זכויות הבעל בחפצו- נחשב הוצאת דבר מן הבעל. ואם תאמר הרי יש עדיין איסור דאו'. באמת, זה ק' גם בדיני ממון. צ"ל שבדברים אלו, נוהגים גם בדיני איסור על פי קביעות מזה.
ספק סוטה עם קינוי וסתירה נאסרה בוודאי. רואים כן ממה שספק טומאה, שנלמד ממנו, אסור אף אם הרבה ספקות מצורפים עמה.
אז, צריכים לפרש למה יש איסור ספק בספק סוטה של גמ' שלנו.
פני יהושע באר שהיא כסוטה שאין רגלים לדבר. אז, קושיה ראשונה נדחית. ר"ש באר (וכן יוצא מרי"מ) שרק צ' רגל"ד כשדנים אם נבעלה, ולא איך נבעלה. לא מבאר למה; יותר קשה להבין אותו ע"פ מש"כ ר"י מיגש למה אין מוציאים אשה מן הבעל[fn:59]. לומדים ספק טומאה מספק סוטה, וצ"ל שכיון שכ' טומאה ללמד, לומדים לו אף שלא דומה (כיון שאין רגל"ד).
שט"מ באר שכאן יש רגלים לדבר[fn:60]. אז, קושיה שנית נדחית. כיון שכאן לא נודע הספק בשעת האיסור (אם יש איסור), לא נתחזק האיסור, ולא נעשה וודאי. (כן באר חז"א בת' שט"מ.)[fn:61]
תי' לק' תוס' (ל"ל הול' בתר חז"ה):
הקשה תוס' למה לא הול' בתר חזקה. ר' שלמה תי' שלא הול' בתר חזקה בספק סוטה. מביא גמ' בנדה (ג.). מגמ' שם יוצא שר"ש מחלק ספק סוטה לשני דינים- מה שלא הול' בתר חז' ומה שנטמא בוודאי. רק לשני צ' רגל"ד. אז, מסתבר שאף רבנן עושים כן. (הק' ר' שאולי ר"ש עושה כן רק כיון שצ"ל שלומד דבר לספק טומאה, כיון שכ' בסוטה טומאה. אבל, רבנן, שמלמדים דינים שצ' רגל"ד, אולי לא מחלקים אותו לשנים.) אז, אף שסוברים שבס"ט לא צ' רגל"ד לשני הדינים, כיון שסוברים שסוטה צ' רגל"ד לדין השני, כאן יתקיים רק דין ראשון. נמצא שייאסר אף עם ח"ה. (באמת, כן סובר רא"ה.)
הערה:
הק' ראשונים איך גמ' יק' שדין של ר"א פשוט, ושוב יק' שסותר א"ע.
שקלא וטריא של גמ':
מתוס' יוצא שק' גמ' הוא שצ' ע"ק. לא פשוט אם מס' מודה לזה (אלא שאומר שכיון שיש אפשרות לבירור, ששוי"א, יש קיום) או לא מודה. לא כתוב שינוי בגמ', ואז נ' שכן מסיק. ק"ק, אז, למה לא רק אמר שפ"פ כשנ"ע, שכבר ידע ששנ"ע מהני.
רשב"א באר ברש"י כתוס'[fn:62]. (ק"ק, אז, למה כ' רש"י הוכחות ששנ"ע מהני, שהנחת הק' מיוסד על צורך לעדי קיום[fn:63].)
שט"מ באר ברשי שמק' שאין נאמנות לשוי"א.[fn:64] ואם תאמר איך נת' לק' תוס'. וי"ל שיש לח' בין שני האיסורים. לזה, מס' גם לא צריך ע"ק.
רשב"א כ' שמק' שאין נאמנות לפ"פ, ואין ספק סוטה נאסר אלא על ידי קו"ס.
לרשב"א ושט"מ, ק' ל"ל נאסר לדוד, שנודע לדוד בידיעה וודאית. תי' רשב"א שכיון שלא נודע לבעל, לא נאסר לבועל.[fn:65]
אם צריכים עדי קיום לאסור סוטה:
תוס' כ' שלהו"א של גמ' צ' ע"ק לעשות איסור סוטה. יש לדון אם תוס' סובר כן אף למס'.
רשב"א כ' שרש"י סובר שצ' ע"ק לעשות איסור סוטה. שט"מ כ' שרש"י סובר שלא צ' ע"ק.
רשב"א כ' שלא צ' ע"ק. מוכיח כן מפני שעדים לא עושים את החלות, אלא הביאה עושה אותו. ק"ק, שנאמר כן גבי קידושין ג"כ.[fn:66]
עדי קיום שלא ראו מעשה:
יש שמדייקים מלשון תוס' שעדים נאמנים על פ"פ. משמע שלא צ' ע"ק שראו מעשה, אלא שידעו עליו, ואף שלא בשעת המעשה. (כ"כ ר"ש איגר, ושיטה זו כ' בית שמואל.) דן ר"ש מתי יחול.
העיר' שיש לחקור אם צ' עדים כדי שנוכל להתברר (כ"כ פנ"י וקצות) או להחשיב הקי'. יותר מס' לומר כן לפי צד ראשון.
מי היה אוריה החתי:
גמ' פי' שאוריה היה ישראל מיוחס שגר בחת. רמב"ם ובנו פי' שבא מאומת חת. רמב"ם פי' שהיה גר תושב (ולכן אשתו לא נאסרה לבועל) ור"א פי' שהיה גר צדק.
ביאור האונס:
בפשטות, דוד הכריח את אשת אוריה. חשק שלמה הביא מאחיו שבאר ע"פ גמ' בסנהדרין שכ' שהיתה קטנה. אז, אנוס הוא כיון שהיה פיתוי קטנה. הוסיף שאולי צד שני סובר שא"א שפק"א, ושזה המקור לרמבם שאוסר פק"א.
קושיית גמ' מהיתר לדוד:
רש"י כ' שנאסר כיון שהיו הרבה עדים. וא"ת איזה עדים ראו הביאה. תוהרא"ש פי' שעדי יחוד היו עדי ביאה. ק"ק, שביאה זו אסורה, ולא נניח שבעל.[fn:67] וא"ת ל"ל נאסר לדוד כיון שדוד ידע. וי"ל שרש"י בא לפ' לשון גמ', שמשמע שמק' למה ב"ד לא יאסרו.[fn:68] גי"ל שכיון שלא נודע לאוריה (ואולי אף אין קיום לאוריה), לא ייאסר לדוד.[fn:69]
תוס' כ' שנאסר כיון שדוד ידע. קשה, שאין קיום (אם יש צורך לקיום) ואין ידעה לבעל. צריך לומר שאף בלי זה נאסר. ואם תאמר א"כ איך נת' שאונס היה (ושאז לא נאסר לבועל כיון שלא נאסר לבעל). וי"ל שחוזר גמ'. וא"ת א"כ נאמר שמותר כיון שאוריה לא ידע. וי"ל שנקט חד מתרי טעמי. (דחוק, שכל גמ' כבר היה דן באותו תי', והיה לו לומר אותו כאן.) גי"ל שרק צ' שיהיה לבעל איסור כלפי שמיא.
לפי מש"כ רשב"א, שכבר נודע תליית איסור בועל באיסור בעל, קשה למה מק' גמ'. צ"ל שחוזר גמ' ולא מניח כאותו הנחה, ומק' ושוב מוקים על אותו הוכחה.
יחס בין איסור בועל לאיסור בעל:
תוס' בשבת כ' שאיסור בועל תלוי באיסור בעל. (כן ייצא מתי' ראשון של גמ', אבל אולי תי' שני חולק עליו.) כ"כ תוס' ביבמות, ובאר שאף שיש איסורי סוטה שנאסרים בספק, מס' שאיסור לבועל ייתלה באיסור לבעל.
יש שני שאלות כאן. שאלה ראשונה הוא אם תלוי איסור בועל באיסור ממש לבעל או באיסור כלפי שמיא לבעל. בזה, רש"ש כ' כראשון. כ"כ בית שמואל (שדייק מרמ"א), ואמר שאז מאנס אשת כהן אסור לה.[fn:70] אבי עזרי כ' כשני. שאלה שנית הוא יחס בין שני איסורים. מלשון רשב"א וריטב"א (שכ' שתלוי בדידיה[fn:71]) משמע שאיסור בעל סיבה לאיסור בעל. (כן מוכרח לפי רש"ש וב"ש.) מלשון רמב"ן (שכ' שהכל תולי באשה) משמע שאיסור בעל ובועל תלויים בשינוי אחד בה. (אז, צריך לומר נגד רש"ש, כמו שכ'.)
ביאור של "לטעמיך":
דנים ראשונים מה מוכיח גמ' ב"לטעמיך." רשב"א פי' שמוכיח שאין הלשון דווקא. ריטב"א ורא"ה כ' שמוכיח שחוששים לספק שאין בו קו"ס. אז, צ"ל שמוכיח כן מעדים שלא מעידים אם קרה באונס או ברצון.
למה מדבר רשב"א בקו"ס עם ע"א:
רשב"א כ' שכדי לאסור סוטה צריכים קו"ס וע"א, כדי שיהיו רגלים לדבר. יש להק' שלא צ' ע"א, שנאסרה בלי זה.
1. יש לומר שלא נאסרה מחשש ביאה, אלא כדי שתשתה מי סוטה.[fn:72] דחה ר' שאף אם לא יכולה לשתות (כמו אם הבעל לא מנוקה מעוון) אסורה לבעל.[fn:73]
2. יש שמקשים שאין קו"ס רק עושים הוכחה לביאה כמו שפ"פ עושה, אלא גם עושה יותר. יודעים כן מפני שיכול בעל למחול על קינוי שלו. צריך לומר שקו"ס נצ' כדי לעשות דבר חוץ מן ההוכחה. אז, לבאר הדמיון לפ"פ, יש לומר אחד משני מהלכים:
  1. אפשר לומר שבאמת קו"ס רק עושים הוכחה. בעל יכול למחול מפני שמחילתו מגלה שלא כיוון כל כך לקנות לזה. אז, אין כ"כ רגליים לביאה. פ"פ, אז, הוא דומה לקו"ס במה שיש הוכחה לביאה.
  2. אפשר לחלק בין שני מיני קו"ס. קו"ס בפני עצמו אוסר מפני אותו הוספה של קו"ס, ולא יכולים לדמות אותו לפ"פ. אבל קו"ס עם עדים אוסר מפני שמוכיח ביאה, כמו פ"פ. לפי"ז, נמצא שאין בעל מוחל קינוי שלו במקום עדים.
  3. אפשר לומר שתי' גמ' לא מדמה פ"פ לקו"ס, אלא אומר שרק צ' קו"ס כשלא נודע שהיה ביאה. לעיל, בארנו א"ז.
לת' שני, נמצא שרק יכולים לדמות פ"פ לקו"ס עם ע"א, שיש צורך לדבר שלא נמצא בפ"פ בציור של קו"ס בלי ע"א.
1. יש לומר שלשון הרשב"א אינו דווקא, ומכוון לומר שקו"ס עושים רגלים לדבר.
למה חוששים לקירור דעת:
משנה אומר שנושאים ביום רביעי כדי שישכים לב"ד אם מצא שאין אשתו בתולה. רש"י כ' (ב.) שרוצים שיבוא לבית דין כדי שייצא הקול, ויבואו עדים. תוס' הק' מגמ' (ט:), שמבואר שרוצים שיבוא כיון שנאסר כשטוען. תי' שצ' טעם של רש"י לציורים שאין בהם איסור, כמו אשת ישראל שנשאה יותר מבת שלש. גם תי' שגמ' מכוון לומר כרש"י, ורק מביא ראיה שיש קול. אם לא היה קם ליה, לא היה קול.[fn:74]
רש"י על הגמ' (ט:) כ' שרוצים שיבוא כדי שאז ייאסר. לכאו', זה רק מובן לצד ראשון של תוס' בביאור רש"י. לצד שני, צ"ל שכשרש"י אומר "אסור" רק רצה לומר שיש חיוב בדיקה, כיון שס"ס הוא. (בס"ס ורוב וביטול, לא סומכים אם יש בירור קל. אם יש בירור קשה, סומכים, ואם יש בירור באמצע, דנים הפוסקים. אז, יש לומר שרש"י סובר שצ' בירור ע"י קול.)[fn:75]
האומר לא לויתי כאומר לא פרעתי:
גמ' אומר שכל האומר "לאלויתי" גם הודה שלא פרע. חולקים ראשונים למה אומרים כן:
1. רשב"א, נמ"י, וריטב"א (במקום אחד) מבאר שההודאה בא ממה שלא טען שפרע. בזה מוכיח לנו שלא פרע, ונחשב שהודה שלא פרע. העיר' שמחודש שהוכחה כזה יהיה לה כוח של הודאת בע"ד.
רש"י, רמ"ה, וריטב"א (במקום אחד) מבארים שאמר שלא פרע, כיון שאי אפשר לפרוע בלי הלוואה. מחודש שזה נחשב הודאה כיון שאמר אותו בתוך אמירת טוב לעצמו.
ר' שך תלה על זה מח' אם מהני הודאה חוץ לבית דין. הרי, אין מוכיחים ממה שלא טען, כיון שאינו בבית דין. אז, לרשב"א אינו הודאה. אבל, עדיין נוכל ללמוד שלא פרע ממה שלא לווה, ואז לרש"י יהיה הודאה.
באר' שענין של הודאה אינו שיש הוכחה, אלא הוא שאין בית דין מתחיל בלי טענה, וכיון שלא טען כבר מניחים נגדו. [fn:76] (ק"ק מהי"ת שזהו הביאור בו.)
הביא ר' הוכחות לזה:
1. עדים נאמנים להעיד על הודאה, אבל לא על עדות.
2. שני עדים מצטרפים כשמעידים על הודאה. כשמעידים על נ' חפץ, באר גמ' שהוא מפני ששניהם מעידים על אותו חיוב אחד. אז, צריך לומר כעי"ז כאן, שזה נח' עדות על חיוב אחד.
3. רמבן כ' שא"א לב"ד לעשות כלום בהודאה נגד הודאה (ואינו כשנ"ע נגד שנ"ע[fn:77]).
4. רשב"א כ' שהודאה "מבטל" עדות.
קושיה על תוד"ה אי למיתה:
חז"א הק' למה לא אומרים "לא לויתי כלא פרעתי," שאמרה שלא נבעלה, ואז צ"ל שלא נבעלה באונס. כיון זה נוגע לממון, אז, נאמר שיש הודאה שלא נבעלה באונס, ולא נצדד כן.
תי' שהוא מפני שאין אונס סיבה לחיב. באר' שיש לדון אם מה שביאה הוא אונס עושה שאין סיבה לבטל כ' או שעושה שהסיבה נמנע. חז"א אומר כראשון. עדיין לא קל לפ' את התי' שלו, אבל אולי אפשר על ידי מה שכ' לעיל בביאור "כל האומר לא לויתי."[fn:78]
מגו לקבל כ':
העיר' מהרש"א שתוס' סותר את עצמו. בד"ה אבל בגליל כ' שאשה נאמנת במגו לקבל כ', ובד"ה לא דקא טען כ' שלא נאמנים במגו.
ר' אמר שיש לחלק בין מיני מגו, שיש שהם יותר חזק ויש שהם יותר קלוש. (יותר מזה, יש שמחלקים לומר שיש שמועילים מפני "מה לי לשקר," ויש שמועילים מפני "כוח הטענה.")
חיוב כתובה:
אם כתובה דאו':
תוס' פסק שכ' דאו', כיון שזהו שיטת רשב"ג ושיטת רב אשי. יש שפ' ר"א באופן אחר, ולכן פסקו שכ' דרבנן. בין הכל, נמצא שלש שיטות:
1. תוס' סובר שכ' ומנין שלה מדאו'.
2. רמב"ן סובר שכתובה מדאו', וסכום שלה מדרבנן (או מסור לרבנן). לומד כן מן המשנה, שרבנן ורשב"ג חולקים בשקלי קפודקיא; משמע שמודים במין כסף- אם צ"ל כס"מ או כס"צ. אם דרבנן הוא, מניח שמוכרח שהוא כס"מ. אז, צ"ל שאף אם כ' דאו', כס"מ הוא.[fn:79]
3. רמב"ם ורא"ש סוברים שכתובה וסכום שלה הם מדרבנן.
לשון כתובה:
תוס' ורא"ש כ' לכ' בכ', "דחזי ליכי מדאו'." תוס' פי' שהוא מפני שכ' דאו', ורא"ש פי' שהוא מפני שהוא כסף כעין דאו' (כיון שהוא כסף צורי). רמב"ם כ' לכ' בכ', "דחזי ליכי" או "דחזי ליכי מדרבנן," כיון שכ' הוא מדרבנן, וכסף מדינה משלם. רא"ש כ' שאף שכ' דרבנן, יכ', "דחזי ליכי מדאו'," כיון שחייב כסף צורי (שהוא מה שחייב, בדר"כ, בדינים דאו').
יש להעיר שיש שמק' למה אין כ' דאו' כיון שכ' חוב. יש שני תי'. אולי לא כיוון לעשות עוד חיוב, ואולי כיוון לעשות חיוב שלו בהגדרת חיוב דרבנן. לשני, יש חיוב דאו'; ק"ק למה לא אמרו לכ', "דחזי ליכי מדאו'" מחמת זה.
טענת בתולים:
מן הגמ' שלנו משמע שיש טענת בתולים רק מפני שחיוב כ' הוא רק מדרבנן. תוס' מק' שרבי מאיר מודה שיש טענ"ב, אף שסובר שכ' דאו'. י"ל שרק ר"נ סובר שצ' שכתובה דרבנן. אבל, אולי רב יהודה חולק עליו בזה.
טענת בתולים בתוספת:
רי"ף מביא מגאונים שרק נאמן על הכ', אבל לא על התוס'; כיון שחייב א"ע בו, חייב מדאו'. יל"ד, שי"ל שרק חייב א"ע בגדרי חיוב כתובה. רשב"ם חולק על גאונים, שאם נאמן על דין דרבנן, קו"ח שנאמן על חיוב שמחייב א"ע. משמע שיש שום נאמנות בעצם, ואינו רק "הם אמרו." צל"פ, אז, שגמ' אומר שאף שרבנן חייבו אותו, נאמן.[fn:80]
כסף כתובה:
יש שני מיני כסף- כסף צורי וכסף מדינה. כסף צורי בא מכסף יותר נקי, ולכן היה שווה פי שמונה של כסף מדינה[fn:81]. חולקים אם כסף כתובה הוא כסף צורי או כסף מדינה. גמ' אומר שכל כסף דאו' הוא כסף צורי וכל כסף דרבנן הוא כסף מדינה, ואז לכאו' תלוי באם כתובה דאו' או דרבנן. אבל, רמבן פי' שאף אם כ' דאו' סכום שלה דרבנן (או שהוא תקנת רבנן או שנסמר לחכמים[fn:82]). תוס' ורא"ש כ' שאף אם כ' דרבנן, חייב בכסף צורי. רא"ש מסביר שהוא מפני שאין צורך של הכתובה- כדי שלא תהא קלה בעיני הבעל להוציאה- מתקיים בכסף מדינה.
משנה מביא מח' בדמי כתובה (אם צריך לשלם בדמי קפודקפיא אם כ' שם), שבו חולקים אם כ' דאו' או דרבנן. אבל, משמע שאין מחלקת איזה מין כסף הוא. אז, משמע או שאף אם דאו' הוא, כס"מ חייב, או שאף אם דרבנן הוא, כס"צ חייב.
איזה מין ממון קבוע:
חיוב הכ' הוא סכום של כסף. יש לדון אם אומרים שהחיוב הוא לשלם הכסף או המטבע; זה תלוי באם מה שנחשב קבוע הוא המטבע או הכסף[fn:83]. היום, אין מטבע שלנו תלוי בכסף או בזהב, ועדיין לא חוששים לסאה בסאה.
מה נחשב שקל:
גמ' אומר שאם הוסיפו על שקל בקפודקיא, לפעמים חייב לשלם אותו שקל. מחודש שיכולים בני עיר אחד להוסיף על שקל. צריך להגדיר את זה, מתי אומרים שמוסיפים על שקל, ומתי אומרים שבוראים מטבע חדש, וקוראים לו בשם ישן של שקל. אפשר לתלות אותו במה שבני אדם מדרהרים. גם יש שכ' שאין חילוק, והכל תלוי במה נחשב מטבע עיקרי של בני אדם.
ק' תוס' בהוספת שקל:
תוס' מה לנו בהוספת שקל, שרק בפדיון הבן רואים שחייב לשלם מה שמחשיבים לשקל. ע' בריטב"א שמשמע שזה רק קשה אם מדרבנן הוא. יש שפי' שגם רמב"ם כ' כן.
שיעור שקל:
חייב אדם חמישים שקלים של תורה לכתובה. חולקים כמה הוא שקל. מצאנו שלש שיעורים:
1. רש"י כ' שהוא מחצה של אונק"י (ounce) של קולוני"א (Cologne). האונקי הוא 29.23 גרם, ואז חציו הוא 14.615 גרם. אז, חיוב כתובה הוא קרוב לשבע מאות ושלשים גרם. בסוף ימיו, רמבן כ' כזה (אחרי שבא לירושלים ומצא שקלים שהיו כשיעור זה).
2. גאונים וגדולי ספרד כ' שהוא שווה לדינר ערבי של זהב. זה קרוב לשבע עשרה גרם, ואז כתובה קרובה לשמונה מאות וחמישים גרם.
3. גאונים גם מוספים שהוא שווה לשלש מאות שמונים וארבע שעורים. במשוך הימים, כשלא היו לבני ישראל אונקי של קולניא ודינר ערבי, התחילו למדוד בזה. תוי"ט מדד בזה, ומצא שחיוב כתובה יהיה קרוב לשמונה מאות גרם. חז"א ורמ"פ מדד בזה, ומצאו שהוא קצת פחות מאלף גרם.[fn:84][fn:85] (רבנות של א"י הוציאו מטבע לפדיון הבן (שהוא אחד מעשר של כתובה) והיה מאה גרם.) ואם תאמר איך רמ"פ וחז"א יחלקו על התוי"יט. וי"ל שכיון שהבינו שממש היה תלוי בשעורים (שניתן לרבנן כוח לקבוע בו או שהיה להם מסורה שתלוי בו) כדי שיהיה תמיד דרך למדוד אותו. אז, משנה עם שינוי השעורים.[fn:86]
* Footnotes
[fn:1] לקמן, נדון אם דין של שוויא אנפישה חתיכה דאיסורא הוא נאמנות או נדר. יש להעיר שאם נדר הוא, פשוט שלא צריך נאמנות נוספת של דבר שעתיד להתגלות. אז, ממה שרש"י צריך להוסיף את זה, נראה שרש"י סובר ששוויא אנפשיה חתיכא דאיסורא הוא נאמנות, ולא נדר.אבל, יש לדחות את זה בשני אופנים פשוטים. האופן ראשון שיש לדחות הוא לומר שאין הכי נמי, כך הוא ההו"א שבא רש"י לדחות, אבל רש"י דוחה אותו. אולי האמת הוא שנדר הוא, ולכן אין ההו"א נכון. האופן השני הוא שאולי נדר זה רק מהני אם אומר דבר שיש בו קצת נאמנות. (לא כל כך פשוט למה יהיה כן, אבל כן נדר זה לא כל כך פשוט.)
[fn:2] שו"ת חתם סופר (יורה דעה קפה), שב שמעתתא (שמעתתא ו), קצות (לד), וכן שער המלך, תרומת הכרי, והרבה אחרונים אחרים.
[fn:3] באמת, אף בצד זה, יש לדון אם הוא ממש נדר, ומחדש לשון אחרת שבו יכול לנדור (וכשנודר כן יש חילוק בדין שאלה) או שזה חלות כעין חלות נדר. לצד שני, כמובן, צריך למצוא החילוק בין שניהם.היה נראה לבאר (והוא כצד ראשון) שבדרך כלל, כשאדם עושה נדר, הוא תופס בדבר הנדור. אז, זה עושה שהוא כעין אותו דבר. אותו דבר ניתר בשאלה עליו, וזה דומה, במה שגם הוא ניתר על ידי שאלה, אבל לא שווה, כיון שניתר על ידי שבועה על עצמו. כאן, אומר שהוא איסור. לכן, אין בו שאלה, כאיסור. אבל, אם אומר שהוא כמו איסור (תופס באיסור), לא מהני, שאי אפשר להיות נדר עם שאלה, שאז אינו דומה לדבר האסור, ואי אפשר להיות נדר בלי שאלה (שאז אינו דומה לדבר האסור, אלא הוא שווה לו). ויש לדון בזה, שעדיין אין החפץ ממש שווה, אלא דין שלו לענין שאלה שווה. אז, לא קשה שרק מדמה אותם. ותחשב. על כל פנים, פשט זו אומרת שהוא ממש נדר, והוא שמזכיר איסור, ונעשה מה שמזכיר. אם מזכיר דמיון לדבר הנדור, נעשה כן, ואם מזכיר דבר אסור, גם נעשה כן, באותו מין איסור.ויש להעיר שאם פשט זה שכתבנו הוא נכון, נמצא שאין שוויא אנפשיה חתיכא דאיסורא גבי נדר, שיהיה דומה לזה, ולא ממש זה. ויש לדון, שאולי יכול להיות נקרא שווה גם כן, שהם שווים אם נפרש מה שואלים עליו להיות "דבר הניתר.” ותחשב.
[fn:4] רבי העיר שלא רק נדר יש לו שאלה, אלא כל חלות שאדם עושה (כמו שבועה, והקדש, ותרומה) יש לו שאלה. אז, מחודש לומר שלזה יש דין אחרת. אבל, העיר שיש מין אחד של נדר (נזירות שמשון) שאין לו שאלה.
[fn:5] נבאר לקמן שיש דרכים אחרים לבאר אותו הדין. אבל, מה שאומר אותו החת"ס בפשיטות מורה שמפרש כצד זה, שאז אותו הדין יהיה נכון בפשיטות.
[fn:6] יש להעיר שכיון שמצאנו שהוא חלוק משאר חלותים שאדם עושה, במה שבדרך כלל אדם צריך דעת לעשות חלות, אבל כאן לא צריך, לא קשה לומר שהוא חלוק משאר חלותים במה שבדרך כלל יש שאלה, אבל כאן אין שאלה. ברט, אם נאמר ששאלה שייך לדעתו (עושה את החלות לחלות בלי דעת נכונה), פשוט שזה לא יהיה שייך כאן, כיון שלא צריכים דעת.
[fn:7] גם בזה יש להעיר שיש לדון אם עושה לומדות של נדר או דבר אחר.
[fn:8] אם כן, לכאו’, תישאר לנו מה שהקשינו לעיל, שעדיין קשה למה לא אומרים שרק אמר אותו מפני טעות שחשב שבית דין יקשיבו לו ויאמינו לו, אבל כיון שנמצא שבית דין לא מאמינים אותו, לא יוכל לעשות חלות.
[fn:9] איני מבין צד זה כל כך. אי אפשר לומר שתורה מגלה לנו שזה ראיה גדולה, שאם כן נאמין אותו לכל נפקא מינא. אז, צריך לומר שאינו נאמנות, אלא סיבה לחלות. (אפשר לדחות שמאמינים אותו, אלא שיש מניעה לפסוק דין של אחר מחמת מה שאומר. כמו כן, יש לומר שבאמת, נאמנות הוא, אבל אילו היה גם נאמן על אחרים, לא היה סיבה להאמין אותו, אולי מפני שרק נאמן מחמת מה לי לשקר ואולי מפני שרק נאמן כיון שרק מדבר על עצמו (שרק בא לבית דין לעשות נפקא מינא לעצמו, כיון שבוודאי אין בית דין מאמינים אותו על יותר). (צריך לחשוב על צד זה לזכך אותו.) ותחשב על זה.) ועיין בצדי צדדים שדנינו בצדדים כזה קצת. אבל, עדיין יש להעיר שאם נאמר שנאמנות ממש הוא, צריכים לבאר למה מאמינים כן. מה לי לשקר הוא, באמת, סיבה להאמין כן, אבל מה שהוא מדבר על עצמו אינו סיבה להאמין, שסיבה להאמין צריך להיות תלוי במה אדם חושב. ותחשב. אולי אף צד זה אומר שהוא סיבה לחלות, אבל אינו ממש סיבה לחלות איסור, אלא הוא סיבה לבית דין לפסוק שיש איסור (אז, לכאו' אם לא בא לבית דין, לא יהיה נוהג. אבל, אולי פשוט שהוא צריך לנהוג כמה שאמר) או שינהוג כמו שאמר (לא מה שאומר נעשה חיוב עליו- חייב לעשות אותו- אלא שחייב לעשות כמו שאמר. זה לא פשוט, אבל זה אומר שעושה חיוב, והקרק' של החיוב הוא שהוא על מה שאמר, ולא שהוא על דבר מיוחד. ותחשב אם זה אומר כלום.). ותחשב. (אולי אחרונים מכוונים לומר, בצד זה, לומר שבורא איסור, אלא שאינו נדר, ואולי כינו את זה בשם נאמנות כיון שהרבה דברים שבתורה שהם נראים שהם נאמנות הם, אולי, כן. אבל, לא נראה כן, שעדיין לא היה להם לומר לשון נאמנות.) גם יש לומר שבדרך כלל, יש נאמנות קצת, אלא שצריך הרבה נאמנות; שוויא אנפשיה חתיכא דאיסורא עושה שלא צריך הרבה נאמנות. אבל, מוזר לטעון כן כשיש עדים, לומר שיש לו נאמנות יותר מעדים.  אולי גם זה חלק מן החידוש (ואז לא צריך לומר שחלק ראשון הוא חלק מן החידוש, שיכול להיות מן הסברה), שכמו שקרא אומר שעדים הם נאמנים, וראיה גדולה הם, כך שוויא אנפשיה חתיכא דאיסורא הוא נאמן, והוא ראיה גדולה.
[fn:10] לא הבנתי למה אומרים שזה לא בא בהתחייבות. נכון הוא שלא בא שבועה אם משיב לטענת מנה חצי מנה, אבל כאן הכוונה הוא שחוששים שהתובע אומר האמת, כל זמן שאין לנו הוכחה ממה שלגמרי פטר את עצמו, ולכן צריך לעשות שבועה. (צריך לע’ לאיזה ציור היה רבי מכוון, שאיני מבין הוכחתו כל כך.)
[fn:11] אפשר לדחות את זה. תחילה, אם נאמר כצד שני שבצד ראשון, יש לומר שכל דבר שאדם אומר הוא סיבה לגרום כל איסור כל זמן שהוא הדבר היחידי שנצרך לגרום איסור. אז, אף אם אינו כן בשעת דיבור, ואף אם הוא לא כוון לכן, נעשה כן, ואז מובן ש"כל האומר לא לוויתי כאומר לא פרעתי.” גם לצד ראשון, נראה שאולי יכולים לדחות שכמו שמדייקים ממה שאמר איסור שרוצה לאסור, אולי כאן יכולים לדייק ממה שאמר שלא לווה, ולא אמר שלא פרע (שהוא קצת יותר טוב, כיון שאז אין עדים לא יכולים להוכיח שהוא משקר) שרוצה גם לנדור שיהיו לו נפקא מינות של כאילו לווה. אבל, יש לדון אם אפשר לעשות נדר כעין זה. לכאו’, הוא תנאי, ויש לדון אם לשון שאמר הוא די לעשות תנאי (שצריך לשונות מיוחדים לתנאי). ותחשב. אבל, אולי אפשר שהתלייה לא בא מתנאי, אלא ממה שאמר, והוא שנדר לשנות את עצמו- לשנות איך? לשנות כאילו נאמין הכל ונאמין שלא לווה. אם נמצא ששינוי זה הוא שחייב, אז יש לו שינוי זה. ותחשב. ויש לדון בזה, שאולי נלך בתר הביאור של זה בשעת חלות הנדר, ובשעת חלות הנדר זה לא יחייב אותו. ותחשב על זה. (וצריך לחשוב אם מחשבתו יהני לנדור כלל, שאולי הוא תופס בדבר המותר. אבל, לפי פשט אחרון שכתבנו, לא נראה שזה כל כך בעיה.)
[fn:12] אם רק נאמן לענין דין שלו, יש לדון למה מותר לאחר לקבל אותו. במילים אחרים, אפשר להגדיר את הנאמנות באופן חלוק או אפשר לומר שלא יהני בגזל, אבל קשה איך נאמר שניהם. אין לומר שעכ"פ יינתן למתנה, שלא מכוון אותו למתנה, שסובר ששל אחרים הוא. ותחשב על זה.
[fn:13] היה אפשר לומר שרק נאמן במה שמאמינים שסובר שהוא אסור, כמו פשט ראשון. איני יודע איזה מעלה יש לפשט זה על פשט ראשון. ותחשב על זה. אולי החילוק בנאמנות יותר מסתבר בפשט זה.
[fn:14] אז, צריך לפרש המשך של התה"כ. נראה שקשה לו למה מאמינים אותו לענין לכוף אותו, שאין זה דין שלו. אז, על זה פי’ שהוא מפני שמאמינים אותו שהוא אסור לו לעשות, וכיון שהוא אסור, מוכרחים לכוף. זה לא נראה לי; צריך לחשוב על זה, ולא נראה נכון.
[fn:15] יש לדון אם הענין הוא שלא יודעת כל מה שצריכים כדי לאסור או שלא אומרת כל מה שצריכים לאסור.
[fn:16] הדרך לדחות את זה הוא לומר שזה אפשר גם לצד שני שבצד ראשון וגם לצד שני (שנאמנות הוא) כיון שדיבור שלו רק עושה איסור אם יודע מה סופו או שצריך לומר כל חלק ממה שגרם האיסור (כמו שנבאר לקמן למטה), וכן רק נאמן אם מכיר שאומר איסור. כיון שאין אנו מבינים הטעמים לזה או לזה, אין סיבה לחשוב שאין זה נכון.
[fn:17] יש לדחות, כמו שכתבנו כמה פעמים, שאולי צריך להיות שיודע באיסור, או צריך להיות שאיסור בא מיד, גם לצד שני שבצד ראשון ולצד שני. ותחשב.
[fn:18] אגב, רבי אמר על זה, “יש שנים- עכשיו יש יותר משנים. כנראה, הוא ממשיך לכתוב, כי בכל שנה יש לנו יותר דברים מר’ עקיבא עיגר. יש לו מין מיוחד של "שפפתיו דובבות בקבר.”” אבל אמר שזה רק בבדיקה, ולא מתנגד לרע"א החדשים.
[fn:19] אם מין ראשון של נדר הוא, מובן למה נאמר כן, שלא מכוון לאסור, אלא טוען דבר המותר. אם מין שני של נדר הוא, קל לומר כן, שלא אומר שאסור הוא, אלא שמותר הוא. (ושי לדון למה יצטרך לומר כל הדברים שגורם שאסור הוא, אם הוא מפני שאז כאילו אמר שאסור הוא (אלו הם מילים אחרים לומר שהוא אסור) או מפני שרק גורם האיסור כיון שהוא דומה לו במה שהוא כל מה שגורם האיסור.) וא"ת הרי תמיד לא אמר הכל, שלא מזכיר מה שיש איסור בתורה על כעין זה. וי"ל שהזכיר כל ממה שיש להסתפק בו. (ויש לדון, שאם יש דין שיש להסתפק בו, לא נראה שצריך להזכיר אותו. ותחשב.) אולי, אז, יהיה נפקא מינא בין שני הצדדים כשהזכיר כל מה שצריך כדי לאסור, אבל לא חשב שזה גורם איסור. ותחשב.) ויש להעיר שכאן יש יותר מכך, שאמר ששאר חלקי האיסור אינם כאן, ולא רק לא ידע עליהם.
[fn:20] העיר’ שזה רק לפי הראשונים שסוברים שצריך לומר המתיר של פש"א בתוך כדי דיבור. אבל, לכאו’ הל’ כאותם ראשונים.
[fn:21] לכאו’, קצות יודה לר"ש, ולא לרבי, שהרי קצות אומר שכשרק אמר חלק מן האוסר, ולא ידע חלק האחר, אף שאל אומר נגדו, צריך להיות נדר כדי שנאמר שלא נאמן. אז, בוודאי כאן נאמר כן ג"כ. ותחשב.
[fn:22] יש לסכם קצת, לומר שקצות מביא ש"י שמדבר על ציור שלא אומרת כל מה שצ’ כדי לאסור, ולא יודעת כל מה שצ’ כדי לאסור; ט"ז מדבר על ציור שלא אומרת ולא יודעת מה שצ’ לאסור, וגם לא בא איסור מיד, ורע"א מדבר על ציור שגם מתנגד לחלק של מה שצ’ לגרום איסור (אבל אולי יודע אותו).
[fn:23] לא נראה שזה מוכרח. הרי, הודאת בע"ד הוא כמאה עדים, ויש שמצדדים שאינו נאמנות. צריך לומר שהחילוק הוא ששם לא אומר שהוא נאמן כמאה עדים, אלא שהוא גורם דינים כמאה עדים. וא"ת הרי עדים לא גורמים דין. (זה לא כל כך פשוט, שאולי הם סיבה להיות הדין כן, ואינם נאמנים.) אבל, אפשר להיות שהם עושים דבר שנפסוק כן, כמו שזה עושה דבר שגורם שנפסוק כן. ותחשב.
[fn:24] יש לדחות את זה. אפשר לומר שכיון שאמר הנדר בלשון זה, מובן שהוא אומר שאם דבריו עומדים (שאין ראיה נגדם) יהיה איסור. ותחשב. גם אפשר לומר שצריך שהוא אומר אותו בלשון חזק, והוא שאומר אותו בלשון שהוא נאמן קצת. אם יש עדים נגדו, הרי לא אמר אותו בלשון חזק. יש לדון, שכשאמר אותו, לא היו עדים נגדו. אולי אינו חזק אם לא נמשך חזקו. אבל, בוודאי לצד שני שבצד ראשון יש לדחות שכדי שאיסור נברא, צריך שהוא אמר דבר שהוא קצת נאמן. נראה שגם כאן יש אותו בעיה, במה שבאו עדים רק אחרי שכבר גרם את האיסור. ותו"ת.
[fn:25] העיר' שרע"א מביא שני צדדים בביאור "כל האומר...," אם ההודאה בא ממה שלא טען (כן כתבו מקצת ראשונים) או ממה שטען (כ"כ רש"י). אין חי' ביניהם לענין ראיה זו, שבי"כ ובי"כ, לא מכוון לחייב א"ע.
[fn:26] כנראה, כן דייק רבי. איני יודע למה זה כל כך פשוט לו.
[fn:27] עיין שם, שלא נראה שצריך לומר כן, שהיה אפשר לומר שרק אם, בדרך כלל, על ידי זה יכול לברוא איסור על עצמו, בני אדם מקשיבים לו. ויש לדון. על כל פנים, לשון תוס' בוודאי מוכיח שזהו הקמ"ל.
[fn:28] אמר' שאפשר לדחות, אבל לא כל כך מסתבר.
[fn:29] אפשר להיות שיש לו נאמנות, אבל מפשטותם, לא נראה שסוברים כן.
[fn:30] רבי היה משמע שיהיה כן אף אם יש רק ספק אם יודע. לכאו’, אז יהיה ספק אם יש איסור זה. אז, יהיה ספק ספיקא, שהאיסור שיבוא מדבריו יהיה ספק. ותחשב על זה.
[fn:31] יש לדחות שמניחים כן על סתם בני אדם.
[fn:32] נראה ליישב שאולי אין כוונתו להקשות שאשה תהיה נאמנת מכוח מגו, אלא כוונתו להקשות שתהיה לה כוח מחמת המגו. האיש נאמן על איסור שלו כיון שהוא איסור שלו. אולי הריטב"א טוען שכיון שהיא יכולה להתיר את האיסור בכל זמן שרוצה, האיסור הוא שלה (גם כן), ואז אינו נאמן אם היא מכחישתו. (אז, צריך לומר שתירוץ שלו- שלא רוצה להודות שפ"פ מצא- יהיה שכיון שלא קל ולא מצוי שתגרום כן, אינה כל כך שלה.) וצריך לע’ בלשון ריטב"א, לראות אם זה אפשר.
[fn:33] אפשר שנלמד מהודאה, וגדרים שלו חלוקים מפני שיש חילוקים שיבואו בין דיבור על ממון לדיבור על איסור. ותחשב.
[fn:34] היה אפשר לת’ שהאשה נסקל, אבל לא האיש. אבל, רש"י ורמבם לא מפרשכים כן.
[fn:35] נ' לבאר שאולי לבית דין יש כוח להכות בנ"א כמו שמצאנו במכות מרדות (ואף שגמ' ביבמות דן בזה, מתי' נראה שלא דן בזה, לפי השיטות שתי' שלו הוא שהוראת שעה שאני, שהרי זה לא ית' מכות מרדות). אז, יעשו כמה שאמר, כיון שאין בו חשש איסור להם. אבל, לא ימיתו אותו, לא יתנו לו אותו דין שאמר, כיון שזה גם דין שלהם, שזה לומד היתר להרוג אותו. ויש לדון. (אבל אם, באמת, יש לב"ד אותו כוח, יש לדון מהו המקור.)
[fn:36] גם נ' שנוכל לחלק בין דיבור שהוא כהן, שהוא קרק' חשוב מאד, לדיבור שהיא מקודשת, שאינו קרק' כל כך חשוב. כיון שנאמן כיון שמדבר על עצמו, אם מדבר על עצמו יותר, נאמן יותר, לענין יותר דברים.
[fn:37] לכאו’, רצה לומר שאחד בא מעבירה על ציווי ה’, ואחד בא על סיבות רעות. רק מאמינים אותו לענין שיש איסור, אבל לא שיש סיבות רעות, שרק מאמינים לדין שלה, והרי רק עבירה שלה הוא דין שלה, ולא ס"ר.
[fn:38] העיר’ שמצאנו פלגינן הברבה מינים של נאמנות, כמו בהודאת בעל דין, נאמנות בידו, ושני עדים.
[fn:39] עיין בלשון ר"א, שכ’ שמחמת זה גם מענישים מיצה. כמו שידוע לכל תלמידי רבי, ר"א לא כ’ קובץ שיעורים, אלא תלמידים שלו כתבו, והרבה פעמים טעו. נראה שכוונת רב אלחנן הוא להקשות איך מחלקים.
[fn:40] אם כן, צריך ביאור למה יש לו שם חדש, ואינו רק נקרא רוב.
[fn:41] כוונת רבי בזה לא כל כך ברור לי. לכאו', יש הערה חשובה כאן, והוא מה שיש לחלק בין זה לדיינים. בדיינים, יש הוכחות טובות, והם מה שתלמידי חכמים חשובים אומרים כן. אז, מסתבר לומר שנלך בתר רוב אותם הוכחות. אבל, כאן, אין שום הוכחה, ויש רק יכולות. נראה שרבי מבאר שעדיין יכול להיות לו חשיבות כיון שמה שהוא יכולת גורם שחושבים על הצד. איני יודע למה רבי לא חושב שכן הוא גם בתשעה חנויות, שאף שם הייתי אומר שהוא רק מוסיף אפשריות (ורוב האפשריות עושה שהוא יותר מסתבר), ולא הוכחות. אינו ברור לי שמכוון רבי לומר צד חלוק מצד שני. אפשר שרבי רק מכוון לומר שביאור זה של ר"ש ברוב יכול להיות שווה לביאור זה שלנו ברוב של ספק ספיקא.
[fn:42] רבי מניח שלא אומרים שכיון שיש רוב כנגדו, לא יכולים לצרף את המיעוט. איני יודע למה זה כל כך פשוט לו מסברה, אבל כנראה יש גמרות שמשמעים כן.
[fn:43] העיר’ שלפי זה, יצא שיש סיבות רעות. רבי תמיד דבר על מה שאין היתר בו, אלא שאין איסור, ואולי יש לו להחמיר. איני מבין את זה כל כך. לכאו’, הייתי אומר שכשתורה לא אסר אותו, התורה התיר אותו. ידע תורה שאולי יש חשש, אבל ה’ לא הקפיד על זה. ותחשב.
[fn:44] זה לא מבאר כלום; רבי העיר שזה לא אומר כלום. אבל, כנראה רבי סובר שאמר כלום, שאם לא כן, לא היה לו לומר אותו.
[fn:45] הוסיף ר’ שדנים אם ס"ס מוציא ממון. אולי לצד זה, אמר, יותר מובן שלא נוציא ממון.
[fn:46] איני מבין את זה כל כך. היה נראה יותר לתלות אותו באם חה"ג או חה"ד הוא, שאם אינו ספק, חה"ד לא יעשה כלום. שוב נראה שאולי הענין הוא שחזקה אומר לנו דבר שקרה, ואותו דבר הוא נגד ס"ס. אז, לא מסתבר שקרה. ותחשב.
[fn:47] כ’ שאין מלים ביום ששי תינוק שאולי נולד ביום ששי ואולי נולד ביה"ש מח’ חזקת מעוברת. אולי סובר כן גם אם יש חזקה נגד שני הספיקות. ואולי יש להוכיח מרידב"ז נג"ז, שלא משיב ככה, אלא משיב שאין ס"ס כיון שספק אחד היה לנו לדעת. (אולי נקט זה כיון שנוגע גם אם ספק אם נולד בשבת ספק אם נולד ביה"ש.)
[fn:48] באר’ שזה יהיה שאז יש חזקה על הדין, ואומרים חז’ על דין, ולא רק על צד אחד בספק, שרק אומרים חזקה על דיון מהו ההל’.
[fn:49] ממה שנכתב לקמן, ייצא שאף אם הוא חזקה שיש לה יותר כוח, כאן אינה כל כך חזקה, שאינו על השאלה, אלא על דבר אחר, ולומדים ממנו הפתרון לשאלה. ע"ש.
[fn:50] אמר רבי שאין רוב ממש מברר את המציאות, אלא עושה שצריכים לחשוב שהמציאות כך. כיון שכן, העיר' שק"ק מהיכי תיתי שרוב חלוק מחזקה. איני יודע כל כך מה היה כוונת רבי בזה. לכאו', הייתי אומר שרוב עושה שמסתבר שמה שקרה הוא דבר אחד, ולכן התורה אמרה להקל. כיון שרוב עושה כן, כשיש ספק, סומכים על רוב. לכאו', מלשון בירור סבר רבי שאינו כן, שבירור משמע לו בירור וודאי. לכן, באר שהוא שתורה אמרה (מסתמא מפני שעושה שהוא מסתבר) שצריכים להניח שמה שרוב אומר הוא נכון. אין זה כל כך מובן לי. לכאו', אי אשפר שממש יש חיוב לחשוב אותו, שאם אין סיבה לחשוב שהוא נכון, אי אפשר לחשוב אותו. ויש לדון, שאולי בני אדם יכולים להטעות את עצמם. יותר נראה שננהוג כאילו הוא נכון. אבל, אז קשה איך הוא חלוק מחזקה. אולי חזקה רק אומר לנו שבספק ננהוג כן, אבל רוב אומר לנו תמיד לנהוג כן. ותחשב. על כל פנים, נראה שמחמת זה- שאין כל כך חילוק ביניהם שיעשה אחד יותר מסתבר- הקשה רבי מהיכי תיתי לחלק. ותחשב.
[fn:51] רצה לומר, אז אינו בצד ש"אם אין היתר אונס….”
[fn:52] לא ברור למה רבי חושב שצדדים הם דברים שהם לפנינו. נראה שרצה לומר שהוא תלוי בדבר שידוע ממש, ואינו רק דרהר על פי מה שנראה כמה מצוי הוא. ותחשב.
[fn:53] יש להעיר שתוס' רק אומר כן אם סומכים על ס"ס, ולא מספיק לו מה שהוא ברי ושמא בלי ס"ס. אולי זה רק מפני שחושש לתנא שאומר לקמן שאין מוציאים ממון כאן מחמת ברי ושמא.
[fn:54] צ' לע' איך קורא הש"ך תי' של תוס'.
[fn:55] איני מבין למה זה פשוט; אם, באמת, יש איסור, יהיה קל בעיניו להוציא אותה. נראה שרצה לומר שבוודאי אסור לקיים אותה בלי כתובה, ממה נפשך. אז, צריך לכ' כתובה כדי להתיר.
[fn:56] נראה שדן אם שינוי בין אשת כהן לאשת ישראל באונס הוא כמה נטמאת או אם אותו דרגה של טומאה אוסרת.
[fn:57] לא באר' איך יש לחלק, אבל הכל אפשר בצד שלא מבינים.
[fn:58] הביאור יהיה שצריך להתאבל שבע ימים שלא היה חי. אז, לא יכול למנות ימים של ספק, כיון שמניחים שהיה חי באותו זמן. אבל, לא תלוי בשבעה זמנים מזמן מעשה של המיתה. כך היה נראה ממה שאמר רבי. גם אפשר לומר שהמקשים מניחים שצריך למנות מזמן שהוא מת. אז, נאמר שנוכל להוכיח מתי הוא עוד חי, אבל אלא מתי הוא מת. לזה, נוכל לדחות שלא יכולים למנות כשהוא חי, וממילא רק נמנה שאר הימים. נראה שאפשר שלא מסתבר להקשות כזה בכלל, שמת רצה לומר שהוא לא חי. אז, אי אפשר לומר שלא נוכיח זמן מיתה, שכיון שמוכיחים שהוא חי עד זמן מסויים, נמצא שהוא מת רק מאותו זמן ולהלן. ותחשב על זה.
[fn:59] היה אפשר לפרש הוא מפני שיותר קשה להוציא אם לא יודעים שבוודאי יש סיבה להוציא. אם דנים אם נבעלה ברצון או באונס, יודעים שיש סיבה לאסור (הביאה), ורק דנים אם יש מה שמפקיע את הסיבה. יש בזה חידוש, שמחדש שבאונס יש סיבה לאסור, אלא שיש מפקיע. אבל, לא נראה שאפשר לומר כן. הרי, אחד מן הדיונים כאן הוא אם נבעלה תחתיו או לא. הרי, אם לא נבעלה תחתיו, אין סיבת איסור. אז, צריך לומר שאף בספק אם יש סיבת איסור, כל זמן שנודע הביאה, נאסרה. זה צריך ביאור.
[fn:60] במילים אחרים, רק צריכים רגלים לדבר כדי שייחשב ספק. אז, כאן, שספק הוא, לא צריכים רגלים לדבר.
[fn:61] הזכיר' שאולי נוגע לזה מה שהעירו אחרונים שא"א שקו"ס רק עושה שיותר מצוי שנבעלה, שיכול בעל למחול על קינוי. צ"ל שגזה"כ מסיבה אחרת הוא.
[fn:62] העיר' שכ"נ מלשון "אשה מזנה..." שברשי, שמשמע שבוודאי זינתה, ורק חוקרים מה צריך כדי לאסור אותה.
[fn:63] יש לדחות שהו"א של גמ' היה שצריך קיום, אבל אף על ידי עדים לא יספיק. ותחשב.
[fn:64] קצת יש לדון איך לפרש את זה אם שוי"א הוא נדר. צריך לומר שמניח ש"נאסרת על בעלה" כולל על ידי נדר, כשלא נודר בפירש. דחוק.
[fn:65] צריך ביאור, אז, איך מביאים שום ראיה ממנו, שאין שום הוכחה לבעל, לכאו', ופשוט שמותר לו, ואז גם פשוט שמותר לבועל.
[fn:66] אמר רבי קצת תי' לזה, אבל איני יודע כל כך מה אמר. אמר שהחילוק הוא שקידושין הוא סדרד שנתן לנו תורה. אבל, ביאה אסורה, ולא מסרה תורה לנו. לכאו', כוונתו לומר שכיון שקידושין הוא דבר שתורה רצה שייעשה, עשה דרך שבו ייעשה, ואמר שאם לא עושה כאותו הסדר, לא יחול תוצאה של הקידושין. אבל, ביאה אינו דבר שרוצה תורה- הוא דבר שאסור באיסור מיתה. אז, לא נותן בו תורה סדר איך לעשות אותו.
[fn:67] אף שלת' שני לא אסורה, לא ידע כן גמ'. יותר מזה, אף לזה, מהרבה גמ' לא נראה שהיה מותר.
[fn:68] ואם תאמר ל"ל הק' גמ' ל"ל אסורה לדוד. וי"ל שאין קושיה זו כל כך חזקה, שאולי אסורה לו, ונשא אותה באיסור.
[fn:69] יש להעיר שהיה נראה שאף אם היו הרבה עדים, לא ידוע לבעל, שהוא נפטר. אולי מה שהוא ראוי לדעת משנה. דחוק. יותר נראה שצריך לומר שצריך עדים כדי להיות קיום.
[fn:70] שם, רק מוכרח שלא צריך שגרם טומאת סוטה. אבל, עדיין אולי מספיק סיבת איסור, ולא צריכים איסור ממש.
[fn:71] רבי אמר שאולי אפשר לגרוש "בדידה," כמו שיאמרו כרמבן שנביא בסמוך. אבל, אמר שעדיין לא נראה לומר כן ברשב"א.
[fn:72] לכאו', רצה לומר שלא יכולים ללמוד משם. אולי בדרך כלל, לא חוששים לאיסור. אבל, כאן, עושים איסור כדי שתשתה, שהיא אסורה אם לא שותה. (כמו כן, יש לומר שמה שהיא לא שותה הוא הודאה קצת.) ואם תאמר למה רוצים שתשתה. ויש לומר שהוא בירור יותר טוב, ועל פיו בעל יסולק מאשה שאסורה לו. גם יש לומר שתורה רוצה שתשתה מי סוטה, כדי שכל הנשים יראו, וכדי שתיענש. אז, עשה איסור כדי שתשתה.
[fn:73] יש לדחות שם שאם לא כן, היה חוטא נשכר. וצל"ע בסוטה, שנראה שיש ציורים אחרים שלא שותה שאסורה.
[fn:74] יש להעיר שייאסר. אז, קשה עדיין למה יבואו עדים, שאין נפקא מינא בביאתם. יש לומר שיבואו באשת ישראל יתירה מבת שלש. אז, הציור שעליו מדבר צריך להיות שווה; החילוק הוא רק שלפי צד זה אין צורך לומר שלא היינו אומרים לא פלוג. אבל, יש לדון, שצריך להיות שרוצים שיבואו עדים, שאם לא כן, קשה למה מזכיר אותו רש"י, ולמה מביא גמ' ראיה ממה שעדים יבואו. ראיית גמ' לא כל כך קשה, שגמ' אומר שאף אילו לא היה נאמן לאיסור, בין כך ובין כך צריך לומר שקים ליה, שאי לאו הכי, אין קול. אבל, עדיין ק"ק למה רש"י מזכיר אותו. נראה שצד זה יסבור שבירור ס"ס יכול להיות סיבה בפני עצמו (ולא רק למה לא לומר לא פלוג). ותחשב.
[fn:75] יש להעיר שקצת שונה כאן, שיכול לברר על ידי הוצאת קול שאולי יברר לאסור. אבל, לכאו' לא יברר להיתר. יש לדון, שאולי מה שלא באים הוא קצת בירור לקולא. ותחשב.
[fn:76] כנראה, רבי חשב שעל ידי זה אין כל כך חידוש בצד שני. איני מבין כל כך למה. נראה שרצה לומר שאין בו נאמנות, שאז נאמר שנאמנות בא ממה שאמר דבר שלא טוב לו, שמסתמא לא משקר בזה. אלא, הוא מפני שצריך טענה כדי שבית דין ידון על דבר. אין צריכים, אז, הסרת הטענה, אלא מה שאין טענה. הרי, לא היה טענה. ותחשב.
[fn:77] אפשר לדחות שכן יקרה בכל ציור שיש ודאי נגד ודאי, ואף בעדים. אבל, בעדים נוכיח מכאן שיש איזה פסול בכת אחת של עדים. אז, ממילא נעשה ספק.
[fn:78] איני מבין כל כך מה כיוון רבי לומר כן. הביאור שנראה שאפשר לומר הוא שאף שטען שלא קרה אונס, הרי אונס הוא רק שלא קרה ביאת רצון. לא דחה אותו טענה. כנראה, רבי סובר שזה יותר קל לומר על פי אחד מן הצדדים (נראה שהוא על פי הביאור שלו בצד שני). איני יודע למה זה נכון.
[fn:79] קצת צריך ביאור למה רבנן יחמירו בחיוב שלו- מה צריך לשלם- למעות קפ', ולא למנה צורי. ותחשב.
[fn:80] יש לדון למה לא אומרים שעדיין לא מודה אילו היה חיוב דאו', ולא חיוב שלו. אז, גמ' אומר שכיון שכ' הוא רק מחיוב דרבנן, ואז אין כל כך צורך לשלם, נאמן. ותחשב על זה.
[fn:81] הקשה רבי למה אינו קצת פחות מפי שמונה. כנראה, הניח שהכסף שבו הוא פי שמונה של הכסף שבכסף מדינה, ולכן הקשה שיש גם כסף של שאר מיני מתכת שנמצאים בכסף מדינה. אבל, לא מוכרח כן, שיש לומר שבין הכל, היה שווה אחד משמונה שבו. ותחשב.
[fn:82] נמצא שמש"א שכסף מדינה הוא בדינים דרבנן כולל מה שמסור לרבנן, אף שעושים דינים דאו'.
[fn:83] לא צריך לשלם איזה חפץ בדווקא. אלא, הדיון הוא כשאנו משלמים היום, למה אנו מדמים, לכסף כזה או למטבע. (אינו כל כך פשוט לי איך נדע כמה המטבע שווה; נאמר שלא שווה כלום, שלא יכולים לקנות כלום במטבע כזה היום. ותחשב.)
[fn:84] יש להעיר שהיה מדה של אגלי"א, שנקרא "גריי"ן," שהיה שווה לשעורה. הוא היה עושה כתובה שקרוב ל אלף מאתים וחמישים גרם.
[fn:85] ר' אמר שאף הוא בדק למצוא שעורה, אבל מנין שמצא היה גדול מאד; היה קשה לו להבחין איך לבדוק, כי יש הרבה גודלים בין השעורים.
[fn:86] יש להעיר שאם נשנה, יש לומר שאין שום מחלקת כאן (אף בין רש"י לשאר ראשונים), והכל תלוי במקום ובזמן. ותחשב.
