יש שלש דרכים שאילן גדל:
נטיעה:
נטיעה הוא כשנוטע זרע בקרקע. הדין הוא שמונים שלש שנים מן הזמן שנטע.
הברכה
הברכה היא נטיעת ייוחר, בין מחובר בין תלוש, בקרקע.
בהברכה, יש שלש מקורות. יש תורת כוהנים שדורש מ"ונטעתם" למעט הברכה מחיוב ערלה. אבל, יש גמ' בסוטה שאורמ שחוזרים מערכי מלחמה על אילן הוברך שלא מחולל. כיון שרק חוזרים אם יש לו דין ערלה, צריך לומר שהברכה נתחייבה בערלה.[fn:1] שם, ראב"י חולק, ואומר שלא חוזרים לו. גם יש גמ' בראש השנה שמבאר ממתי מונים שנים לאילן שהבריך.
ראשונים מבארים- וכן נ' ממשניות- שיש שני מיני הברכה. אם נוטע ייחור שמחובר לאמו וממנה יונק מן הארץ (שיעור שורש), לא נחשב נטיעה חדשה, והוא בטל לאמו, ויש לו דיני אמו. אבל, אם נוטע ייחור שעקר, נחשב נטיעה חדשה.
אם נוטע ייחור שמחובר, ושוב נעקר הייחור, מונים שלש שנים משעה שנעקרה.
נמצא שיש שלש זמנים שיכול להיות מנין משלש זמנים- מזמן נטיעת האילן (כשמחובר), מזמן נטיעת ייחור (כשעקרו ונטעו), ומזמן עקירת הייחור (כשעקרו אחר שנטעו).
הרכבה
הרכבה הוא נטיעת אילן לתוך אילן אחר. יש שני מיני הרכבה:
הרכבת ייחור[fn:2]
יכול לחברו לתוך ששה מיני אילנות:
לתוך אילן זקן
דין הייחור שווה לאילן זקן, ואין בו ערלה[fn:3].
לתוך אילן ילדה
דין הייחור שווה לאילן ילדה, ויש בו דין ערלה. אבל, מונים שנות הערלה מזמן נטיעת ילדה שבו הרכיב[fn:4].
לתוך אילן שנטע לסייג ולקורות
חולקים תנאים בדין זה:
רבנן
דין הייחור הוא שיש לו ערלה. אף שאין ערלה, בדרך כלל, לאילן שנטע לסייג ולקורות[fn:5], כיון שלא נטע אותו לפירות, אם חשב עליו לפירות, יהיה לו דין ערלה[fn:6]. לכן, אין לייחור דין האילן.
ירושלמי כ' שמונים שלש השנים משעת נטיעת האילן. לפי ריטב"א, בבלי חולק, וסובר שמונים משעת הרכבה.
ראב"י[fn:7]
דין הייחור שווה לדין אילן, והוא שאין לו ערלה, אלא אם כן חושב עליו לאכילה.[fn:8]
לתוך אילן שנטע להקדש[fn:9]- דינו שווה לדין ייחור שהרכיב לתוך אילן שנטע לסייג ולקורות, שכמו שיכול לחייב אילן שנטע לסייג ולקורות ע"י שינוי מחשבתו, כך יכול לחייב אילן הקדש על ידי פדיון.
לתוך עצי אשירה
חולקים בזה. טורי אבן כ' שיש ערלה לייחור, ומונים משעת הרכבה, אבל אפשר שיש חולקים^.
לתוך אילן סרק
דין ייחור הוא שיש לו ערלה. חולקים בירושלמי איך מונים שלש השנים שלו. ריש לקיש סובר שמונים משעת הרכבה ורבי יוחנן סובר שמונים משעת נטיעת אמו. רמב"ן מפרש שבבלי סובר כריש לקיש.
הרכבת אילן
יש להקדים שיש ארבע יניקות ששייך לדון בהם בתוך הרכבת אילן. יש יניקה שהולך מן הקרקע לאילן ראשונה, יש יניקה שהולך מאילן ראשונה לאילן שניה, יש יניקה שהולך מן הקרקע לאילן שניה, ויש יניקה שהולך מאילן שניה לאילן ראשונה.
גם יש להקדים שלפעמים, דין זה יהיה תלוי בכוח היניקה, אם כוחו יפה או רע. חולקים בביאור "כוח יפה." חז"א פי' שכוח יפה הוא שיונק ממנו באופן חזק משאר מיניקה האחרת. (אז, צד אחד של יניקה לעולם יפה וצד האחר לעולם רע.) ר"ש וראב"ד פי' שכוח יפה הוא שחיבור הוא חזק וכוח רע הוא שהחיבור הוא חלוש, וכמעט יכול להיות נפרד ברוח. אז, לכאו', רק ביניקה שנית ושלישית יכול להיות כוחו רע.
ירושלמי נותן סימן לדעת אם יניקה יפה או רע. עוקץ העלה יותר קרוב למקום שכוחו יפה. לפי חזון איש, תמיד הולכים אחר סימן זה. אבל, לפי ר"ש, אפשר שכוח יפה או רע שרואים דוחה סימן זה.
אין חילוק בין אם מרכיב ילדה לתוך זקנה או זקנה לתוך ילדה, אבל אולי יש חילוק בין פירות שיוצאים מענף הזקנה ליוצאים מענף הילדה.
הכלל בזה הוא שתמיד הולכים בתר מה שכוח יפה. היניקה שנותן לו כוח יפה גם נותן לו דינים. אבל, יש שלש נקודות שצריכים להוסיף על זה:
לפי הר"ש, אפשר להיות שכוח שניהם יפה. אז, לא פשוט מה לעשות.
רמבן כ' שפירות שיוצאים מן הילדה אסורים, אף אם כוח הזקנה יפה, אם הילדה מחובר לקרקע כאילן.
חז"א כ' שפירות שיוצאים מן הזקנה מותרים, אף אם כוח הילדה יפה, אם הזקנה מחובר לקרקע בשורש.
* Footnotes
[fn:1] היה אפשר לתרץ שאותו גמ' הוא כשמבריך אילן ילדה. אז, כמו שחוזר לילדה, חוזר להברכה שלו. אבל, זה אי אפשר, שאם כן יחזור מפני ילדה ראשונה (שהבריך). ואם תאמר, הרי רק חוזר על כרם של חמש אילנות, ואז אפשר לברוא ציור שנטע ארבע והבריך אחד מהם. צריך לומר שהברכה לא עושה אילן חדש (על כל פנים, באופן שיש לו דין ערלה של אמו.)
[fn:2] כל ייחור יש עליו דין אילן ילדה לענין ערלה (שאינו חלק מאילן זקנה).
[fn:3] המקור לזה הוא מגמ' סוטה. לכאו', אותו גמ' דן בייחור, ולא באילן, שאם כבר יש לו אילן ילדה, יחזור מחמתו. אלא, צריך לומר שרק ייחור יש לו. כמו כן כ' הרמב"ן בפירוש, וכן נראה מרש"י.
[fn:4] הראיה לזה הוא מגמ' בסוטה. שם, דן איך אפשר שיחזור מערכי מלחמה מחמת חיוב ערלה של ילדה. לא מתרץ שנמצא אם הרכיב ילדה לתוך ילדה, וכבר עברו שלש שנים של האילן ולא של הייחור. צריך לומר שאף לייחור מונים משעת נטיעה.
[fn:5] קצת יש לדון מהו "לסייג ולקורות." לכאו', היה נראה לפרש הוא הסיבה העיקרית למה נטע אותו. אבל, קצת קשה, אז, איך אדם יכול לשנות את דעתו (נבאר לקמן שאדם יכול לשנות את דעתו). צריך לומר, אז, שהוא השימוש שרוצה ממנו ביותר. ותחשב.
[fn:6] אפשר שראב"י חולק על זה. ועיין לקמן.
[fn:7] אפשר להיות שיש עוד שיטה בזה. רבי יוסי אומר שיכול אדם לחלק אילן, לעשות חציו פטור מן הערלה, כיון שחושב עליו לסייג ולקורות, ולעשות חציו חייב. יש מפרשים שחכמים חולקים עליו. אם חולקים, יש לדון אם מחייבים כולו או פוטרים כולו. (ע' בלשון המשנה, שנראה מלשון רבי יוסי שמחייבים.)גם צריך לדון למה לא פטור ייחור שנרכב לתוך אילן שנטע לסייג ולקורות, אם הו א מפני שאין לאילן דין די לבטל אחר לתוך אותו דין או אם הוא מפני שנמצא שחשב על חצי האילן. לצד שני, כמובן, משנה שלנו הוא כדברי רבי יוסי. אז, אפשר שאף אילן שלסייג חייב לפי רבנן.גם אפשר, אז, שרבנן חולקים על שיטה זו, ואומרים שדין הייחור שווה לדין האילן. יש להעיר שאפשר שראב"י, אז, רק סובר כרבנן אלו.
[fn:8] יש לדון, באמת, באיזה נקודה חולק ראב"י. אפשר שסובר שבטל לאילן שנטע לסייג ולקורות, ואין לו דין ערלה. גם אפשר שסובר שאי אפשר לחייב אילן שנטע לסייג ולקורות. (אולי סובר שמחשבה רק חשוב בשעת נטיעה או שרק מחשבה של למה נוטע חשוב.) גם אפשר שסובר שפטור כיון שצריך נטיעה, והרי, זה לא נטוע כלל, אלא הוברך. עיין לקמן, בע"ה.
[fn:9] הדין הוא שעץ של הקדש פטור מערלה. אבל, זה רק אם הוקדש קודם זריעה. רמב,ן מחדש שהוא רק אם הקדיש קודם נטיעה, ולא רק קודם השרשה. (היה נראה לומר שצריך להיות לפני "חלות חיוב ערלה." החלות חל כשנוטע, אבל צריך השרשה לעשות פירות, שעליהם יהיה דין זה. אז, מונים משעת השרשה. ותחשב.
