שנה ראשונה:
מתי מתחיל:
מתחיל אחר שעת השרשת האילן. חולקים תנאים מהו שעת השרשה:
1. רבי יהודה- שלשה ימים אחר נטיעה.
2. רבי יוסי ורבי שמעון- שני שבועות אחר נטיעה. כן ההלכה.
3. רבי מאיר- שלשים יום אחר נטיעה.
ימים אלו אינם ימים מעת לעת, אלא ימות בראשית. רמב"ם ורע"ב כ' שצריכים להיות ימים שלימים. רא"ש כ' שלא צ"ל ימים שלימים[fn:1].
חזון איש מכריע כרא"ש, וכ' שאף רמב"ם ורע"ב מודים, וט"ס הוא ברמב"ם ורע"ב[fn:2].[fn:3]
לרמב"ם, יש יכולת (אם מונים שלש שנים מעת לעת, כמו שנבאר לקמן) להתחיל משעת נטיעה. ע' לקמן.[fn:4]
מתי נגמר:
אם השרשת האילן הוא שלשים יום שלמים[fn:5] (או יותר) לפני א' תשרי:
נגמר בא' תשרי שלאחר ההשרשה. נמצא ש"שלשים יום בשנה חשוב שנה."
גם יש יכולת אחר, לפי הרמב"ם, והוא שנגמר השנה מעת לעת של נטיעתו. עיין לקמן, למה זה יהיה נוגע.
אם השרשת האילן הוא יום אחד (קטוע[fn:6]) לפני א' תשרי:
רבי מאיר:
נגמר בא' תשרי שלאחר השרשה. נמצא ש"יום אחד בשנה חשוב שנה."
רבנן:
נגמר בא' תשרי שהוא יותר משנה שלימה אחר ההשרשה.
גם יש יכולת אחר, לפי הרמב"ם, והוא שנגמר השנה מעת לעת של נטיעתו. עיין לקמן, למה זה יהיה נוגע.
מה הדין שלו:
כל פרי שיוצא ממנו הוא ערלה (באילנות החייבים בערלה, שהוא כל אילן שעושה פרי חשוב שמחשיב). לעולם נשאר אותו פרי באיסור שלו (שכ', "יהיה ").
שנה שניה:
מתי מתחיל:
מתחיל מיד כשנגמר שנה רשאונה.
מתי נגמר:
נגמר שנה שלימה אחר שהתחיל. זה לא מפני שצריכים שנה שלימה, אלא מפני שנגמר בא' תשרי, והרי התחיל בא' תשרי.
(לרמב"ם, אם משתמשים בשנה מעת לעת, נגמר מעל"ע אחריו, שכל אותם שלש שנים צ"ל מעל"ע.)
מה הדין שלו:
כל פרי שיוצא ממנו הוא ערלה (באילנות החייבים בערלה). לעולם נשאר אותו פרי באיסור שלו (שכ', "יהיה ").
שנה שלישית:
מתי מתחיל:
מתחיל מיד כשנגמר שנה שניה.
מתי נגמר[fn:7]:
אם לא התחילה שנה ראשונה בראש השנה:
נגמר בט"ו בשבט. דורשים את זה מפסוק, וחול' בירושלמי מהו הטעם (אם הוא מפני שגדל על מי פירות של שנה שלפני כן או שרוב פירות חונטים אז, והוא גדר טוב).
אם התחילה שנה ראשונה בראש השנה:
רש"י ורמב"ם:
נגמר שנה שלישית בראש השנה שלישית. נמצא שבין הכל, היו שלש שנים שלימות. כיון שלא מקילים בתחילה (לסמוך על שלשים יום בשנה חשוב שנה), יכולים להקל בסוף.
בעל המאור ור"ן:
נגמר שנה שלישית בט"ו בשבט. סובר שאין לחלק בין זה לציור שלא התחילה שנה ראשונה בר"ה.
רמב"ם מוסיף שאם אם כבר היו שלש שנות עולם (ובזה שלישי נגמר בראש השנה), אז יכולים למנות שלש שנים מעת לעת. משעת נטיעה נמצא שמונים של"ש מעל"ע כל זמן שהתחילה שנה ראשונה שלשים יום לפני ראש השנה. יש נפקא מינא, אז, לכל מי שנוטע באופן שישרש אחר ר"ה עד נטיעה ביד' שבט.
להל', חזון איש כ' שבא"י, מחמירים כבעל הבאור ור"ן. בחו"ל, מקילים כרשי ורמב”ם (בחי' הראשון), אבל לא כרמב”ם (בחי' השני).
מה הדין שלו:
כל פרי שיוצא ממנו הוא ערלה (באילנות החייבים בערלה). לעולם נשאר אותו פרי באיסור שלו (שכ', "יהיה ").
שנה רביעית:
מתי מתחיל:
מתחיל מיד אחר שנגמר שנה שלישית.
מתי נגמר:
נגמר שנה שלימה אחר שהתחילה. (זה לא מפני שצריכים שנה מעל"ע, אלא מפני שר"ה שלה הוא אותו יום שבו התחילה.)
לרמבם, לפעמים נגמר מעל"ע מתחילתה כיון שצריכים שנה מעל"ע.
מה הדין שלו:
יש לפירות האילן דין נטע רבעי. דין נטע רבעי הוא כדין מעשר שני, שאסור לאכול חוץ מירושלים בלי פדיון. חולקים אם דין זה נובג רק בענבים או בכל פירות.
שנה חמישית:
מתי מתחיל:
מתחיל מיד אחר שנגמר שנה שלישית.
מתי נגמר:
נגמר שנה שלימה אחר שהתחילה (אבל אין נפק"מ, שמתחילתו עד ביאת משיח (ומסתמא, אף אחר ביאת משיח), אין דינו נשתנה).
מה הדין שלו:
הפירות מותרים.
* Footnotes
[fn:1] באמת, רא"ש רק כתב שצריכים רק ארבעים וארבע ימים. אפשר שסובר ששלשים יום לא צריכים להיות שלם, אבל ימי השרשה צריכים להיות שלמים. אבל, יש ראיות שימי השרשה לא צריכים להיות שלמים, ואז יותר קל להניח כן ברא"ש.
[fn:2] חזון איש רגיל לטעון על כל דבר פלא שהוא טעות סופר.
[fn:3] יש שני ראיות לחזון איש בזה. יש גמ' בפסחים שאומר בפירוש שאומרים מקצת היום ככולו (אבל, אולי רק בפעם אחת (בתחילה או בסוף)) בהשרשה, לענין חדש. גם יש גמ' בר"ה שאומר שיום אחד עולה לכאן ולכאן בענין השרשה ויום אחד בשנה (עיין לקמן) בערלה. זה מיוסד (ע' גמ' נזיר) על מקצת היום ככולו, ואז צ"ל שאומרים מקצת היום ככולו בהשרשה.
[fn:4] הנחתי שלפי הרמב"ם השנה מתחיל ונגמר כאילו הוא שנה מעת לעת. יש לדון בזה (וכל סברת הרמב"ם לא פשוט), שהרי צריך להיות שהשריש שלים יום לפני ראש הנשה, ונמצא שצריך למנות שנה ראשונה גם לבריאת העולם. על כל פנים, נראה שהוא יותר קל אם אכתב כזה, ולא נראה הוכחה שהוא יותר רחוק מן האמת.
[fn:5] מראשונים, מוכרח שצריכים ימים שלימים לזה, ולא אומרים שמקצת היום ככולו, שאי לאו הכי, נאמר שסוף ימי השרשה עולים לכאן ולכאן, ואז צריכים, בין הכל, רק ארבעים ושלש ימים. הרי, ראשונים לא אומרים כן, אלא אומרים שצריכים ארבעים וארבע או ארבעים וחמש ימים.
[fn:6] כן מבואר מגמ' שאומר עליו שיום אחד עולה לכאן ולכאן.
[fn:7] באמת, כל הדיונים שכתבתי הוא מתי מותר פירות ערלה. אבל, כתבתי את כל זה בתוך גמר שנה שלישית. לפי מה שכתב רש"י לבאר, זה נכון בלומדות, אבל בוודאי נכון בדין. ותו"ת.
