** {ישעיה לח-ב} {תהילים יז-יד} {בראשית כה-כד}
אבא בנימין חומרות אבא בנימין (צריך לחלקם) תניא אבא בנימין אומר על שני דברים הייתי מצטער כל ימי על תפלתי שתהא לפני מטתי ועל מטתי שתהא נתונה בין צפון לדרום על תפלתי שתהא לפני מטתי מאי לפני מטתי אילימא לפני מטתי ממש והאמר רב יהודה אמר רב ואיתימא ריב''ל מנין למתפלל שלא יהא דבר חוצץ בינו לבין הקיר שנאמר
ויסב חזקיהו פניו אל הקיר ויתפלל לא תימא לפני מטתי אלא אימא סמוך למטתי ועל מטתי שתהא נתונה בין צפון לדרום דא''ר חמא ברבי חנינא אמר רבי יצחק כל הנותן מטתו בין צפון לדרום הויין ליה בנים זכרים שנאמר
וצפונך תמלא בטנם ישבעו בנים רב נחמן בר יצחק אמר אף אין אשתו מפלת נפלים כתיב הכא וצפונך תמלא בטנם וכתיב התם
וימלאו ימיה ללדת והנה תומים בבטנה: ה:
אבא בנימין מזיקים תניא אבא בנימין אומר אלמלי נתנה רשות לעין לראות אין כל בריה יכולה לעמוד מפני המזיקין אמר אביי אינהו נפישי מינן וקיימי עלן כי כסלא לאוגיא אמר רב הונא כל חד וחד מינן אלפא משמאליה ורבבתא מימיניה אמר רבא האי דוחקא דהוי בכלה מנייהו הוי הני ברכי דשלהי מנייהו הני מאני דרבנן דבלו מחופיא דידהו הני כרעי דמנקפן מנייהו האי מאן דבעי למידע להו לייתי קיטמא נהילא ונהדר אפורייה ובצפרא חזי כי כרעי דתרנגולא האי מאן דבעי למחזינהו ליתי שלייתא דשונרתא אוכמתא בת אוכמתא בוכרתא בת בוכרתא ולקליה בנורא ולשחקיה ולימלי עיניה מניה וחזי להו ולשדייה בגובתא דפרזלא ולחתמי' בגושפנקא דפרזלא דילמא גנבי מניה ולחתום פומיה כי היכי דלא ליתזק רב ביבי בר אביי עבד הכי חזא ואתזק בעו רבנן רחמי עליה ואתסי: ו.
** {מלכים א ח-כח} {תהילים פב-א} {תהילים פב-א} {מלאכי ג-טז} {מלאכי ג-טז} {שמות כ-כד}
אבא בנימין מתי שכינה באה  תניא אבא בנימין אומר אין תפלה של אדם נשמעת אלא בבית הכנסת שנאמר
לשמוע אל הרנה ואל התפלה במקום רנה שם תהא תפלה אמר רבין בר רב אדא א''ר יצחק מנין שהקב''ה מצוי בבית הכנסת שנאמר
אלהים נצב בעדת אל ומנין לעשרה שמתפללין ששכינה עמהם שנאמר אלהים נצב בעדת אל ומנין לשלשה שיושבין בדין ששכינה עמהם שנאמר
בקרב אלהים ישפוט ומנין לשנים שיושבים ועוסקין בתורה ששכינה עמהם שנאמר
אז נדברו יראי ה' איש אל רעהו ויקשב ה' וגו' מאי
ולחושבי שמו אמר רב אשי חשב אדם לעשות מצוה ונאנס ולא עשאה מעלה עליו הכתוב כאילו עשאה ומנין שאפילו אחד שיושב ועוסק בתורה ששכינה עמו שנאמר
בכל המקום אשר אזכיר את שמי אבוא אליך וברכתיך וכי מאחר דאפילו חד תרי מבעיא תרי מכתבן מלייהו בספר הזכרונות חד לא מכתבן מליה בספר הזכרונות וכי מאחר דאפי' תרי תלתא מבעיא מהו דתימא דינא שלמא בעלמא הוא ולא אתיא שכינה קמ''ל דדינא נמי היינו תורה וכי מאחר דאפי' תלתא עשרה מבעיא עשרה קדמה שכינה ואתיא תלתא עד דיתבי: ו.
** {איוב יח-ד} {איוב יח-ד} {דברים לב-יח} {ישעיה מח-יח}
אבא בנימין תפלה שהוי לחברו תניא אבא בנימין אומר שנים שנכנסו להתפלל וקדם אחד מהם להתפלל ולא המתין את חברו ויצא טורפין לו תפלתו בפניו שנאמר
טורף נפשו באפו הלמענך תעזב ארץ ולא עוד אלא שגורם לשכינה שתסתלק מישראל שנאמר
ויעתק צור ממקומו ואין צור אלא הקב''ה שנאמר
צור ילדך תשי ואם המתין לו מה שכרו אמר ר' יוסי ברבי חנינא זוכה לברכות הללו שנאמר
לוא הקשבת למצותי ויהי כנהר שלומך וצדקתך כגלי הים ויהי כחול זרעך וצאצאי מעיך וגו':  ו.
אבות אמהות ת''ר אין קורין אבות אלא לשלשה ואין קורין אמהות אלא לארבע אבות מאי טעמא אילימא משום דלא ידעינן אי מראובן קא אתינן אי משמעון קא אתינן אי הכי אמהות נמי לא ידעינן אי מרחל קא אתינן אי מלאה קא אתינן אלא עד הכא חשיבי טפי לא חשיבי תניא אידך עבדים ושפחות אין קורין אותם אבא פלוני ואמא פלונית ושל ר''ג היו קורים אותם אבא פלוני ואמא פלונית מעשה לסתור משום דחשיבי: טז:
** {ישעיה מו-יב}
אבירי לב
שמעו אלי אבירי לב הרחוקים מצדקה רב ושמואל ואמרי לה רבי יוחנן ורבי אלעזר חד אמר כל העולם כולו נזונין בצדקה והם נזונין בזרוע וחד אמר כל העולם כולו נזונין בזכותם והם אפילו בזכות עצמן אין נזונין כדרב יהודה אמר רב דאמר רב יהודה אמר רב בכל יום ויום בת קול יוצאת מהר חורב ואומרת כל העולם כולו נזונין בשביל חנינא בני וחנינא בני די לו בקב חרובין מערב שבת לערב שבת ופליגא דרב יהודה דאמר רב יהודה מאן אבירי לב גובאי טפשאי אמר רב יוסף תדע דהא לא איגייר גיורא מינייהו אמר רב אשי בני מתא מחסיא אבירי לב נינהו דקא חזו יקרא דאורייתא תרי זמני בשתא ולא קמגייר גיורא מינייהו:  יז:
** {בראשית טו-ח} {דניאל ט-יז}
אברהם א''ר יוחנן משום ר''ש בן יוחי מיום שברא הקב''ה את העולם לא היה אדם שקראו להקב''ה אדון עד שבא אברהם וקראו אדון שנאמר
ויאמר אדני (אלהים) במה אדע כי אירשנה. אמר רב אף דניאל לא נענה אלא בשביל אברהם שנא'
ועתה שמע אלהינו אל תפלת עבדך ואל תחנוניו והאר פניך על מקדשך השמם למען אדני למענך מבעי ליה אלא למען אברהם שקראך אדון:  ז:
** {שמואל ב יב-יא}
אבשלום מזמור לדוד מזמור לדוד בברחו מפני אבשלום בנו מזמור לדוד קינה לדוד מיבעי ליה אמר ר' שמעון בן אבישלום משל למה הדבר דומה לאדם שיצא עליו שטר חוב קודם שפרעו היה עצב לאחר שפרעו שמח אף כן דוד כיון שאמר לו הקב''ה
הנני מקים עליך רעה מביתך היה עצב אמר שמא עבד או ממזר הוא דלא חייס עלי כיון דחזא דאבשלום הוא שמח משום הכי אמר מזמור:  ז:
** {תהילים ג-א} {תהילים ג-ב} {תהילים ב-א}
אבשלום קשה מגוג ומגוג וא''ר יוחנן משום רבי שמעון בן יוחי קשה תרבות רעה בתוך ביתו של אדם יותר ממלחמת גוג ומגוג שנאמר
מזמור לדוד בברחו מפני אבשלום בנו וכתיב בתריה
ה' מה רבו צרי רבים קמים עלי ואילו גבי מלחמת גוג ומגוג כתיב
למה רגשו גוים ולאומים יהגו ריק ואילו מה רבו צרי לא כתיב:  ז:
אגרא ד...  אמר ר' זירא אגרא דפרקא רהטא אמר אביי אגרא דכלה דוחקא אמר רבא אגרא דשמעתא סברא אמר רב פפא אגרא דבי טמיא שתיקותא אמר מר זוטרא אגרא דתעניתא צדקתא אמר רב ששת אגרא דהספדא דלויי אמר רב אשי אגרא דבי הלולי מילי: ו:
אוכל איך לחתוך בשר אמר להו רבא לבניה כשאתם חותכין בשר אל תחתכו על גב היד איכא דאמרי משום סכנה ואיכא דאמרי משום קלקול סעודה  ח:
** {בראשית לא-ד}
אומה מדיים טובים תניא אמר ר''ע בשלשה דברים אוהב אני את המדיים כשחותכין את הבשר אין חותכין אלא על גבי השולחן כשנושקין אין נושקין אלא על גב היד וכשיועצין אין יועצין אלא בשדה אמר רב אדא בר אהבה מאי קראה
וישלח יעקב ויקרא לרחל וללאה השדה אל צאנו:  ח:
אומה פרסיים טובים תניא אמר רבן גמליאל בשלשה דברים אוהב אני את הפרסיים הן צנועין באכילתן וצנועין בבית הכסא וצנועין בדבר אחר: ח:
** {ישעיה יג-ג}
אומה פרסיים רעים
אני צויתי למקודשי תני רב יוסף אלו הפרסיים המקודשין ומזומנין לגיהנם: ח:
** {קהלת ז-א}
איוב ר' יוחנן כי הוה מסיים ספרא דאיוב אמר הכי סוף אדם למות וסוף בהמה לשחיטה והכל למיתה הם עומדים אשרי מי שגדל בתורה ועמלו בתורה ועושה נחת רוח ליוצרו וגדל בשם טוב ונפטר בשם טוב מן העולם ועליו אמר שלמה
טוב שם משמן טוב ויום המות מיום הולדו. יז.
** {תהילים קג-א} {שמואל א ב-ב}
אין צור בלתך רב שימי בר עוקבא ואמרי לה מר עוקבא הוה שכיח קמיה דר' שמעון בן פזי והוה מסדר אגדתא קמיה דר' יהושע בן לוי אמר ליה מאי דכתיב
ברכי נפשי את ה' וכל קרבי את שם קדשו אמר ליה בא וראה שלא כמדת הקדוש ברוך הוא מדת בשר ודם מדת בשר ודם צר צורה על גבי הכותל ואינו יכול להטיל בה רוח ונשמה קרבים ובני מעים והקב''ה אינו כן צר צורה בתוך צורה ומטיל בה רוח ונשמה קרבים ובני מעים והיינו דאמרה חנה
אין קדוש כה' כי אין בלתך ואין צור כאלהינו. מאי אין צור כאלהינו אין צייר כאלהינו מאי כי אין בלתך אמר ר' יהודה בר מנסיא אל תקרי כי אין בלתך אלא אין לבלותך שלא כמדת הקדוש ברוך הוא מדת בשר ודם מדת בשר ודם מעשה ידיו מבלין אותו והקב''ה מבלה מעשיו  י.
** {מלכים א יח-לז} {מלכים א יח-לז}
אליהו הנביא תפלתו
ענני ה' ענני א''ר אבהו למה אמר אליהו ענני ב' פעמים מלמד שאמר אליהו לפני הקב''ה רבש''ע ענני שתרד אש מן השמים ותאכל כל אשר על המזבח וענני שתסיח דעתם כדי שלא יאמרו מעשה כשפים הם שנאמר
ואתה הסבות את לבם אחורנית: ט:
** {דברים יא-כא} {משלי ח-לד}
אריכות ימים אמרו ליה לר' יוחנן איכא סבי בבבל תמה ואמר
למען ירבו ימיכם וימי בניכם על האדמה כתיב אבל בחוצה לארץ לא כיון דאמרי ליה מקדמי ומחשכי לבי כנישתא אמר היינו דאהני להו כדאמר ר' יהושע בן לוי לבניה קדימו וחשיכו ועיילו לבי כנישתא כי היכי דתורכו חיי א''ר אחא ברבי חנינא מאי קרא
אשרי אדם שומע לי לשקד על דלתותי יום יום לשמור מזוזת פתחי וכתיב בתריה כי מוצאי מצא חיים.  ח.
אריכות ימים למען ירבו ימיכם וימי בניכם על האדמה כתיב אבל בחוצה לארץ לא ח.
ארמית לא לשבת על מטתה (מעשה) וא''ד ארמית ממש ומשום מעשה דרב פפא דרב פפא אזל לגבי ארמית הוציאה לו מטה אמרה לו שב אמר לה איני יושב עד שתגביהי את המטה הגביהה את המטה ומצאו שם תינוק מת מכאן אמרו חכמים אסור לישב על מטת ארמית ח:
** {משלי יח-כב} {קהלת ז-כו}
אשה טובה תפלה לה אמר ר' חנינא לעת מצא זו אשה שנא'
מצא אשה מצא טוב במערבא כי נסיב אינש אתתא אמרי ליה הכי מצא או מוצא מצא דכתיב מצא אשה מצא טוב ויפק רצון מה' מוצא דכתיב
ומוצא אני מר ממות את האשה וגו'  ח.
** {שופטים ז-יט} {תהילים קיט-סב} {תהילים קיט-קמח}
אשמורות   ת''ר ארבע משמרות הוי הלילה דברי רבי ר' נתן אומר שלש מ''ט דר' נתן דכתיב
ויבא גדעון ומאה איש אשר אתו בקצה המחנה ראש האשמורת התיכונה תנא אין תיכונה אלא שיש לפניה ולאחריה ורבי מאי תיכונה אחת מן התיכונה שבתיכונות ור' נתן מי כתיב תיכונה שבתיכונות תיכונה כתיב מ''ט דרבי א''ר זריקא א''ר אמי א''ר יהושע בן לוי כתוב אחד אומר
חצות לילה אקום להודות לך על משפטי צדקך וכתוב אחד אומר
קדמו עיני אשמורות הא כיצד ארבע משמרות הוי הלילה ור' נתן סבר לה כרבי יהושע דתנן ר' יהושע אומר עד שלש שעות שכן דרך מלכים לעמוד בשלש שעות שית דליליא ותרתי דיממא הוו להו שתי משמרות רב אשי אמר משמרה ופלגא נמי משמרות קרו להו: ג:
** {ירמיה כה-ל}
אשמורות עד סוף האשמורה: מאי קסבר ר' אליעזר אי קסבר שלש משמרות הוי הלילה לימא עד ארבע שעות ואי קסבר ארבע משמרות הוי הלילה לימא עד שלש שעות לעולם קסבר שלש משמרות הוי הלילה והא קמ''ל דאיכא משמרות ברקיע ואיכא משמרות בארעא דתניא ר' אליעזר אומר שלש משמרות הוי הלילה ועל כל משמר ומשמר יושב הקב''ה ושואג כארי שנאמר
ה' ממרום ישאג וממעון קדשו יתן קולו שאוג ישאג על נוהו וסימן לדבר משמרה ראשונה חמור נוער שניה כלבים צועקים שלישית תינוק יונק משדי אמו ואשה מספרת עם בעלה. מאי קא חשיב ר' אליעזר אי תחלת משמרות קא חשיב תחלת משמרה ראשונה סימנא למה לי אורתא הוא אי סוף משמרות קא חשיב סוף משמרה אחרונה למה לי סימנא יממא הוא אלא חשיב סוף משמרה ראשונה ותחלת משמרה אחרונה ואמצעית דאמצעיתא ואב''א כולהו סוף משמרות קא חשיב וכי תימא אחרונה לא צריך למאי נפקא מינה למיקרי ק''ש למאן דגני בבית אפל ולא ידע זמן ק''ש אימת כיון דאשה מספרת עם בעלה ותינוק יונק משדי אמו ליקום וליקרי. אמר רב יצחק בר שמואל משמי' דרב ג' משמרות הוי הלילה ועל כל משמר ומשמר יושב הקב''ה ושואג כארי ואומר אוי לבנים שבעונותיהם החרבתי את ביתי ושרפתי את היכלי והגליתים לבין אומות העולם: ג.
** {ישעיה נ-ב}
בית הכנסת אין עשר אמר ר' יוחנן בשעה שהקב''ה בא בבית הכנסת ולא מצא בה עשרה מיד הוא כועס שנא'
מדוע באתי ואין איש קראתי ואין עונה. ו:
בית הכנסת לעבור לאחוריו בזמן תפלה  ואל תעברו אחורי בית הכנסת בשעה שהצבור מתפללין מסייע ליה לרבי יהושע בן לוי דאמר ר' יהושע בן לוי אסור לו לאדם שיעבור אחורי בית הכנסת בשעה שהצבור מתפללין אמר אביי ולא אמרן אלא דליכא פתחא אחרינא אבל איכא פתחא אחרינא לית לן בה ולא אמרן אלא דליכא בי כנישתא אחרינא אבל איכא בי כנישתא אחרינא לית לן בה ולא אמרן אלא דלא דרי טונא ולא רהיט ולא מנח תפילין אבל איכא חד מהנך לית לן בה: ח:
** {דברים יא-כא} {משלי ח-לד}
בית הכנסת מאריך שנים אמרו ליה לר' יוחנן איכא סבי בבבל תמה ואמר
למען ירבו ימיכם וימי בניכם על האדמה כתיב אבל בחוצה לארץ לא כיון דאמרי ליה מקדמי ומחשכי לבי כנישתא אמר היינו דאהני להו כדאמר ר' יהושע בן לוי לבניה קדימו וחשיכו ועיילו לבי כנישתא כי היכי דתורכו חיי א''ר אחא ברבי חנינא מאי קרא
אשרי אדם שומע לי לשקד על דלתותי יום יום לשמור מזוזת פתחי וכתיב בתריה כי מוצאי מצא חיים.  ח.
** {ירמיה יב-יד} {ירמיה יב-יד}
בית הכנסת מי שלא נכנס אמר ר''ל כל מי שיש לו בית הכנסת בעירו ואינו נכנס שם להתפלל נקרא שכן רע שנאמר
כה אמר ה' על כל שכני הרעים הנוגעים בנחלה אשר הנחלתי את עמי את ישראל ולא עוד אלא שגורם גלות לו ולבניו שנא'
הנני נותשם מעל אדמתם ואת בית יהודה אתוש מתוכם.  ח.
** {תהילים יב-ט}
בית הכנסת מתפלל לאחוריו אמר רב הונא כל המתפלל אחורי בית הכנסת נקרא רשע שנאמר
סביב רשעים יתהלכון אמר אביי לא אמרן אלא דלא מהדר אפיה לבי כנישתא אבל מהדר אפיה לבי כנישתא לית לן בה ההוא גברא דקא מצלי אחורי בי כנישתא ולא מהדר אפיה לבי כנישתא חלף אליהו חזייה אידמי ליה כטייעא א''ל כדו בר קיימת קמי מרך שלף ספסרא וקטליה  ו:
** {ישעיה נ-י}
בית הכנסת רגיל לבוא אמר רבין בר רב אדא אמר רבי יצחק כל הרגיל לבא לבית הכנסת ולא בא יום אחד הקב''ה משאיל בו שנאמר
מי בכם ירא ה' שומע בקול עבדו אשר הלך חשכים ואין נוגה לו אם לדבר מצוה הלך נוגה לו ואם לדבר הרשות הלך אין נוגה לו יבטח בשם ה' מאי טעמא משום דהוה ליה לבטוח בשם ה' ולא בטח: ו:
** {הושע ו-ג} {הושע יא-י}
בית הכנסת ריצה ביציאה וכניסה אמר רבי חלבו אמר רב הונא היוצא מבית הכנסת אל יפסיע פסיעה גסה אמר אביי לא אמרן אלא למיפק אבל למיעל מצוה למרהט שנא'
נרדפה לדעת את ה' אמר רבי זירא מריש כי הוה חזינא להו לרבנן דקא רהטי לפרקא בשבתא אמינא קא מחליין רבנן שבתא כיון דשמענא להא דרבי תנחום א''ר יהושע בן לוי לעולם ירוץ אדם לדבר הלכה ואפילו בשבת שנא'
אחרי ה' ילכו כאריה ישאג וגו' אנא נמי רהיטנא. ו:
בית הכסא סעודה  ת''ר הרוצה ליכנס לסעודת קבע מהלך עשרה פעמים ד' אמות או ד' פעמים י' אמות ויפנה ואח''כ נכנס  כג.
בית הכסא קרוב ותפלה לו מר זוטרא אמר לעת מצא זה בית הכסא אמרי במערבא הא דמר זוטרא עדיפא מכלהו ח.
בית הכסא רשב''ג אומר עמוד החוזר מביא את האדם לידי הדרוקן סילון החוזר מביא את האדם לידי ירקון: כה.
בית שני ממה הציל רב הונא רמי כתיב לענותו וכתיב לכלותו בתחלה לענותו ולבסוף לכלותו: ז:
** {תהילים קמד-יד}
ברכות ותפילות כי הוו מפטרי רבנן מבי ר' אמי ואמרי לה מבי ר' חנינא אמרי ליה הכי עולמך תראה בחייך ואחריתך לחיי העולם הבא ותקותך לדור דורים לבך יהגה תבונה פיך ידבר חכמות ולשונך ירחיש רננות עפעפיך יישירו נגדך עיניך יאירו במאור תורה ופניך יזהירו כזוהר הרקיע שפתותיך יביעו דעת וכליותיך תעלוזנה מישרים ופעמיך ירוצו לשמוע דברי עתיק יומין. כי הוו מפטרי רבנן מבי רב חסדא ואמרי לה מבי ר' שמואל בר נחמני אמרו ליה הכי
אלופינו מסובלים וגו' אלופינו מסובלים רב ושמואל ואמרי לה רבי יוחנן ור' אלעזר חד אמר אלופינו בתורה ומסובלים במצות וחד אמר אלופינו בתורה ובמצות ומסובלים ביסורים אין פרץ שלא תהא סיעתנו כסיעתו של דוד שיצא ממנו אחיתופל ואין יוצאת שלא תהא סיעתנו כסיעתו של שאול שיצא ממנו דואג האדומי ואין צוחה שלא תהא סיעתנו כסיעתו של אלישע שיצא ממנו גחזי ברחובותינו שלא יהא לנו בן או תלמיד שמקדיח תבשילו ברבים: יז
גיורת שלא לישא (יש לדון בגר) ואל תשבו על מטת ארמית. ואיכא דאמרי דלא תנסבו גיורתא  ח:
גניבה מגנב אמרו ליה הכי שמיע לן דלא יהיב מר שבישא לאריסיה אמר להו מי קא שביק לי מידי מיניה הא קא גניב ליה כוליה אמרו ליה היינו דאמרי אינשי בתר גנבא גנוב וטעמא טעים ה:
** {תהילים קיט-קמז} {משלי ז-ט} {שמואל א ל-יז} {שמות יא-ד} {דברי הימים א כז-לד} {שמואל ב טז-כג} {שמואל ב כ-כג} {תהילים נז-ט} {תהילים פו-ב} {תהילים קיט-סב} {תהילים קיט-מו} {משלי כג-טו} {משלי כז-יא} {תהילים כז-יג} {בראשית כח-טו} {בראשית לב-ח} {שמות טו-טז}
דוד (מתי היה קם, מה היה עושה אז, אם ידע חצות, אם ידע משה חצות, אם היה דוד חסיד, למה היה דוד חסיד, מפשבשת דוד ודניאל.)  ודוד בפלגא דליליא הוה קאי מאורתא הוה קאי דכתיב
קדמתי בנשף ואשועה וממאי דהאי נשף אורתא הוא דכתיב
בנשף בערב יום באישון לילה ואפילה אמר רב אושעיא אמר רבי אחא הכי קאמר (דוד) מעולם לא עבר עלי חצות לילה בשינה. רבי זירא אמר עד חצות לילה היה מתנמנם כסוס מכאן ואילך היה מתגבר כארי רב אשי אמר עד חצות לילה היה עוסק בדברי תורה מכאן ואילך בשירות ותשבחות. ונשף אורתא הוא הא נשף צפרא הוא דכתיב
ויכם דוד מהנשף ועד הערב למחרתם מאי לאו מצפרא ועד ליליא לא מאורתא ועד אורתא אי הכי לכתוב מהנשף ועד הנשף או מהערב ועד הערב אלא אמר רבא תרי נשפי הוו נשף ליליא ואתי יממא נשף יממא ואתי ליליא. ודוד מי הוה ידע פלגא דליליא אימת השתא משה רבינו לא הוה ידע דכתיב
כחצות הלילה אני יוצא בתוך מצרים מאי כחצות אילימא דאמר ליה קודשא בריך הוא כחצות מי איכא ספיקא קמי שמיא אלא דאמר ליה (למחר) בחצות (כי השתא) ואתא איהו ואמר כחצות אלמא מספקא לי' ודוד הוה ידע דוד סימנא הוה ליה דאמר רב אחא בר ביזנא א''ר שמעון חסידא כנור היה תלוי למעלה ממטתו של דוד וכיון שהגיע חצות לילה בא רוח צפונית ונושבת בו ומנגן מאליו מיד היה עומד ועוסק בתורה עד שעלה עמוד השחר כיון שעלה עמוד השחר נכנסו חכמי ישראל אצלו אמרו לו אדונינו המלך עמך ישראל צריכין פרנסה אמר להם לכו והתפרנסו זה מזה אמרו לו אין הקומץ משביע את הארי ואין הבור מתמלא מחוליתו אמר להם לכו ופשטו ידיכם בגדוד מיד יועצים באחיתופל ונמלכין בסנהדרין ושואלין באורים ותומים אמר רב יוסף מאי קרא (דכתיב)
ואחרי אחיתופל בניהו בן יהוידע ואביתר ושר צבא למלך יואב אחיתופל זה יועץ וכה''א
ועצת אחיתופל אשר יעץ בימים ההם כאשר ישאל (איש) בדבר האלהים בניהו בן יהוידע זה סנהדרין ואביתר אלו אורים ותומים וכן הוא אומר
ובניהו בן יהוידע על הכרתי ועל הפלתי ולמה נקרא שמם כרתי ופלתי כרתי שכורתים דבריהם פלתי שמופלאים בדבריהם ואח''כ שר צבא למלך יואב אמר רב יצחק בר אדא ואמרי לה אמר רב יצחק בריה דרב אידי מאי קרא
עורה כבודי עורה הנבל וכנור אעירה שחר. רבי זירא אמר משה לעולם הוה ידע ודוד נמי הוה ידע וכיון דדוד הוה ידע כנור למה ליה לאתעורי משנתיה וכיון דמשה הוה ידע למה ליה למימר כחצות משה קסבר שמא יטעו אצטגניני פרעה ויאמרו משה בדאי הוא דאמר מר למד לשונך לומר איני יודע שמא תתבדה ותאחז רב אשי אמר בפלגא אורתא דתליסר נגהי ארבסר הוה קאי והכי קאמר משה לישראל אמר הקב''ה למחר כחצות הלילה כי האידנא אני יוצא בתוך מצרים:
לדוד שמרה נפשי כי חסיד אני לוי ור' יצחק חד אמר כך אמר דוד לפני הקב''ה רבונו של עולם לא חסיד אני שכל מלכי מזרח ומערב ישנים עד שלש שעות ואני
חצות לילה אקום להודות לך ואידך כך אמר דוד לפני הקב''ה רבונו של עולם לא חסיד אני שכל מלכי מזרח ומערב יושבים אגודות אגודות בכבודם ואני ידי מלוכלכות בדם ובשפיר ובשליא כדי לטהר אשה לבעלה ולא עוד אלא כל מה שאני עושה אני נמלך במפיבשת רבי ואומר לו מפיבשת רבי יפה דנתי יפה חייבתי יפה זכיתי יפה טהרתי יפה טמאתי ולא בושתי א''ר יהושע בריה דרב אידי מאי קרא
ואדברה בעדותיך נגד מלכים ולא אבוש תנא לא מפיבשת שמו אלא איש בשת שמו ולמה נקרא שמו מפיבשת שהיה מבייש פני דוד בהלכה לפיכך זכה דוד ויצא ממנו כלאב וא''ר יוחנן לא כלאב שמו אלא דניאל שמו ולמה נקרא שמו כלאב שהיה מכלים פני מפיבשת בהלכה ועליו אמר שלמה בחכמתו
בני אם חכם לבך ישמח לבי גם אני ואומר
חכם בני ושמח לבי ואשיבה חורפי דבר. ודוד מי קרי לנפשיה חסיד והכתיב
לולא האמנתי לראות בטוב ה' בארץ חיים ותנא משמיה דרבי יוסי למה נקוד על לולא אמר דוד לפני הקב''ה רבש''ע מובטח אני בך שאתה משלם שכר טוב לצדיקים לעתיד לבוא אבל איני יודע אם יש לי חלק ביניהם אם לאו שמא יגרום החטא כדר' יעקב בר אידי דר' יעקב בר אידי רמי כתיב
והנה אנכי עמך ושמרתיך בכל אשר תלך וכתיב
ויירא יעקב מאד אמר שמא יגרום החטא כדתניא
עד יעבור עמך ה' עד יעבור עם זו קנית עד יעבור עמך ה' זו ביאה ראשונה עד יעבור עם זו קנית זו ביאה שנייה מכאן אמרו חכמים ראוים היו ישראל ליעשות להם נס בימי עזרא כדרך שנעשה להם בימי יהושע בן נון אלא שגרם החטא:  ד
** דף י - ב {קהלת ה-ו} {ישעיה לח-ב} {ירמיה ד-יט} {ישעיה לח-ג} {שמות יב-ב}
א''ר חנן אפי' בעל החלומות אומר לו לאדם למחר הוא מת אל ימנע עצמו מן הרחמים שנאמר
כי ברוב חלומות והבלים ודברים הרבה כי את האלהים ירא מיד
ויסב חזקיהו פניו אל הקיר ויתפלל אל ה' מאי קיר אמר רשב''ל מקירות לבו שנא'
מעי מעי אוחילה קירות לבי וגו' ר' לוי אמר על עסקי הקיר אמר לפניו רבונו של עולם ומה שונמית שלא עשתה אלא קיר אחת קטנה החיית את בנה אבי אבא שחפה את ההיכל כולו בכסף ובזהב על אחת כמה וכמה
זכר נא את אשר התהלכתי לפניך באמת ובלב שלם והטוב בעיניך עשיתי מאי והטוב בעיניך עשיתי א''ר יהודה אמר רב שסמך גאולה לתפלה ר' לוי אמר שגנז ספר רפואות תנו רבנן ששה דברים עשה חזקיהו המלך על ג' הודו לו ועל ג' לא הודו לו על ג' הודו לו גנז ספר רפואות והודו לו כתת נחש הנחשת והודו לו גירר עצמות אביו על מטה של חבלים והודו לו ועל ג' לא הודו לו סתם מי גיחון ולא הודו לו קצץ דלתות היכל ושגרם למלך אשור ולא הודו לו עבר ניסן בניסן ולא הודו לו ומי לית ליה לחזקיהו
החדש הזה לכם ראש חדשים זה ניסן ואין אחר ניסן אלא טעה בדשמואל דאמר שמואל אין מעברין את השנה ביום שלשים של אדר הואיל וראוי לקובעו ניסן סבר הואיל וראוי לא אמרינן:
** דף יז - א
בפמליא של מעלה ובפמליא של מטה ובין התלמידים העוסקים בתורתך בין עוסקין לשמה בין עוסקין שלא לשמה וכל העוסקין שלא לשמה יהי רצון שיהו עוסקין לשמה. ר' אלכסנדרי בתר צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שתעמידנו בקרן אורה ואל תעמידנו בקרן חשכה ואל ידוה לבנו ואל יחשכו עינינו איכא דאמרי הא רב המנונא מצלי לה ור' אלכסנדרי בתר דמצלי אמר הכי רבון העולמים גלוי וידוע לפניך שרצוננו לעשות רצונך ומי מעכב שאור שבעיסה ושעבוד מלכיות יהי רצון מלפניך שתצילנו מידם ונשוב לעשות חוקי רצונך בלבב שלם. רבא בתר צלותיה אמר הכי אלהי עד שלא נוצרתי איני כדאי ועכשיו שנוצרתי כאלו לא נוצרתי עפר אני בחיי ק''ו במיתתי הרי אני לפניך ככלי מלא בושה וכלימה יהי רצון מלפניך ה' אלהי שלא אחטא עוד ומה שחטאתי לפניך מרק ברחמיך הרבים אבל לא ע''י יסורין וחלאים רעים והיינו וידוי דרב המנונא זוטי ביומא דכפורי. מר בריה דרבינא כי הוה מסיים צלותיה אמר הכי אלהי נצור לשוני מרע ושפתותי מדבר מרמה ולמקללי נפשי תדום ונפשי כעפר לכל תהיה פתח לבי בתורתך ובמצותיך תרדוף נפשי ותצילני מפגע רע מיצר הרע ומאשה רעה ומכל רעות המתרגשות לבא בעולם וכל החושבים עלי רעה מהרה הפר עצתם וקלקל מחשבותם יהיו לרצון אמרי פי והגיון לבי לפניך ה' צורי וגואלי.  יז.
** {בראשית כה-לג} {בראשית כז-מא} {בראשית כז-לו} {דברי הימים א ה-א} {בראשית לז-כא} {תהילים מו-ט}
דרשת שמות ראובן א''ר אלעזר אמרה לאה ראו מה בין בני לבן חמי דאילו בן חמי אע''ג דמדעתיה זבניה לבכירותיה דכתיב
וימכר את בכרתו ליעקב חזו מה כתיב ביה
וישטם עשו את יעקב וכתיב
ויאמר הכי קרא שמו יעקב ויעקבני זה פעמים וגו' ואילו בני אע''ג דעל כרחיה שקליה יוסף לבכירותיה מניה דכתיב
ובחללו יצועי אביו נתנה בכורתו לבני יוסף אפי' הכי לא אקנא ביה דכתיב
וישמע ראובן ויצילהו מידם: רות מאי רות א''ר יוחנן שזכתה ויצא ממנה דוד שריוהו להקב''ה בשירות ותשבחות מנא לן דשמא גרים אמר רבי אליעזר דאמר קרא
לכו חזו מפעלות ה' אשר שם שמות בארץ אל תקרי שמות אלא שמות:  ז:
** ה’ לא חוזר בו {דברים ט-יד} {דברי הימים א כג-טו} {שמות א-ז}
וא''ר יוחנן משום ר' יוסי כל דבור ודבור שיצא מפי הקב''ה לטובה אפי' על תנאי לא חזר בו מנא לן ממשה רבינו שנא'
הרף ממני ואשמידם וגו' ואעשה אותך לגוי עצום אע''ג דבעא משה רחמי עלה דמלתא ובטלה אפ''ה אוקמה בזרעיה שנא'
בני משה גרשום ואליעזר ויהיו בני אליעזר רחביה הראש וגו' ובני רחביה רבו למעלה וגו' ותני רב יוסף למעלה מששים רבוא אתיא רביה רביה כתיב הכא רבו למעלה וכתיב התם
ובני ישראל פרו וישרצו וירבו: ז.
** {תהילים פז-ב}
הלכה אמר ליה רבא לרפרם בר פפא לימא לן מר מהני מילי מעלייתא דאמרת משמיה דרב חסדא במילי דבי כנישתא אמר ליה הכי אמר רב חסדא מאי דכתי'
אוהב ה' שערי ציון מכל משכנות יעקב אוהב ה' שערים המצויינים בהלכה יותר מבתי כנסיות ומבתי מדרשות והיינו דאמר ר' חייא בר אמי משמיה דעולא מיום שחרב בית המקדש אין לו להקב''ה בעולמו אלא ארבע אמות של הלכה בלבד.  ואמר אביי מריש הוה גריסנא בגו ביתא ומצלינא בבי כנישתא כיון דשמענא להא דאמר רבי חייא בר אמי משמיה דעולא מיום שחרב בית המקדש אין לו להקב''ה בעולמו אלא ארבע אמות של הלכה בלבד לא הוה מצלינא אלא היכא דגריסנא. רבי אמי ורבי אסי אף על גב דהוו להו תליסר בי כנישתא בטבריא לא מצלו אלא ביני עמודי היכא דהוו גרסי:  ח.
וידוי יוה”כ אלהי עד שלא נוצרתי איני כדאי ועכשיו שנוצרתי כאלו לא נוצרתי עפר אני בחיי ק''ו במיתתי הרי אני לפניך ככלי מלא בושה וכלימה יהי רצון מלפניך ה' אלהי שלא אחטא עוד ומה שחטאתי לפניך מרק ברחמיך הרבים אבל לא ע''י יסורין וחלאים רעים והיינו וידוי דרב המנונא זוטי ביומא דכפורי.  יז.
** {קהלת ח-א} {מלכים א יח-ב} {מלכים ב כ-א} {איוב יג-טו}
חזקיה אמר רב המנונא מאי דכתיב
מי כהחכם ומי יודע פשר דבר מי כהקדוש ברוך הוא שיודע לעשות פשרה בין שני צדיקים בין חזקיהו לישעיהו חזקיהו אמר ליתי ישעיהו גבאי דהכי אשכחן באליהו דאזל לגבי אחאב (שנאמר
וילך אליהו להראות אל אחאב ישעיהו אמר ליתי חזקיהו גבאי דהכי אשכחן ביהורם בן אחאב דאזל לגבי אלישע מה עשה הקב''ה הביא יסורים על חזקיהו ואמר לו לישעיהו לך ובקר את החולה שנאמר
בימים ההם חלה חזקיהו למות ויבא אליו ישעיהו בן אמוץ הנביא ויאמר אליו כה אמר ה' (צבאות) צו לביתך כי מת אתה ולא תחיה וגו' מאי כי מת אתה ולא תחיה מת אתה בעולם הזה ולא תחיה לעולם הבא אמר ליה מאי כולי האי אמר ליה משום דלא עסקת בפריה ורביה א''ל משום דחזאי לי ברוח הקדש דנפקי מינאי בנין דלא מעלו א''ל בהדי כבשי דרחמנא למה לך מאי דמפקדת איבעי לך למעבד ומה דניחא קמיה קודשא בריך הוא לעביד אמר ליה השתא הב לי ברתך אפשר דגרמא זכותא דידי ודידך ונפקי מנאי בנין דמעלו א''ל כבר נגזרה עליך גזירה א''ל בן אמוץ כלה נבואתך וצא כך מקובלני מבית אבי אבא אפי' חרב חדה מונחת על צוארו של אדם אל ימנע עצמו מן הרחמים אתמר נמי רבי יוחנן ורבי (אליעזר) דאמרי תרוייהו אפילו חרב חדה מונחת על צוארו של אדם אל ימנע עצמו מן הרחמים שנא'
הן יקטלני לו איחל:
** {משלי יט-כג}
חלום לן בלא חלומות א''ר יונה א''ר זירא כל הלן שבעת ימים בלא חלום נקרא רע שנאמר
ושבע ילין בל יפקד רע אל תקרי שבע אלא שבע יד.
** {ירמיה לג-יא} {שמות יט-טז} {שמות כ-יח} {ירמיה לג-יא} {ירמיה לג-יא}
חתן וכלה לשמח אותם וא''ר חלבו אמר רב הונא כל הנהנה מסעודת חתן ואינו משמחו עובר בחמשה קולות שנאמר
קול ששון וקול שמחה קול חתן וקול כלה קול אומרים הודו את ה' צבאות ואם משמחו מה שכרו אמר רבי יהושע בן לוי זוכה לתורה שנתנה בחמשה קולות שנאמר
ויהי ביום השלישי בהיות הבקר ויהי קולות וברקים וענן כבד על ההר וקול שופר וגו' ויהי קול השופר וגו' והאלהים יעננו בקול. איני והא כתיב
וכל העם רואים את הקולת אותן קולות דקודם מתן תורה הוו רבי אבהו אמר כאילו הקריב תודה שנאמר
מביאים תודה בית ה' רב נחמן בר יצחק אמר כאילו בנה אחת מחורבות ירושלים שנאמר
כי אשיב את שבות הארץ כבראשונה אמר ה': ו:
** {בראשית מט-כב} {בראשית מח-טז}
טבילה ר' יוחנן הוה רגיל דהוה קא אזיל ויתיב אשערי דטבילה אמר כי סלקן בנות ישראל ואתיין מטבילה מסתכלן בי ונהוי להו זרעא דשפירי כוותי אמרי ליה רבנן לא קא מסתפי מר מעינא בישא אמר להו אנא מזרעא דיוסף קא אתינא דלא שלטא ביה עינא בישא דכתיב
בן פורת יוסף בן פורת עלי עין ואמר רבי אבהו אל תקרי עלי עין אלא עולי עין רבי יוסי ברבי חנינא אמר מהכא
וידגו לרוב בקרב הארץ מה דגים שבים מים מכסין עליהם ואין עין הרע שולטת בהם אף זרעו של יוסף אין עין הרע שולטת בהם ואב''א עין שלא רצתה לזון ממה שאינו שלו אין עין הרע שולטת בו: כ.
טבילה רב גידל הוה רגיל דהוה קא אזיל ויתיב אשערי דטבילה אמר להו הכי טבילו והכי טבילו אמרי ליה רבנן לא קא מסתפי מר מיצר הרע אמר להו דמיין באפאי כי קאקי חיורי כ.
** {ויקרא כג-לב}
יום כיפור אכילה לפניו כתיב
ועניתם את נפשתיכם בתשעה לחדש בערב וכי בתשעה מתענין והלא בעשרה מתענין אלא לומר לך כל האוכל ושותה בתשיעי מעלה עליו הכתוב כאילו מתענה תשיעי ועשירי. ח:
** {דברי הימים א יז-כא} {דברים כו-יז} {דברים ו-ד} {דברים ד-ז} {דברים לג-כט} {דברים ד-לד} {דברים כו-יט}
יחס ה’ עם בני ישראל הני תפילין דמרי עלמא מה כתיב בהו א''ל
ומי כעמך ישראל גוי אחד בארץ ומי משתבח קוב''ה בשבחייהו דישראל אין דכתיב
את ה' האמרת היום (וכתיב) וה' האמירך היום אמר להם הקב''ה לישראל אתם עשיתוני חטיבה אחת בעולם ואני אעשה אתכם חטיבה אחת בעולם אתם עשיתוני חטיבה אחת בעולם שנאמר
שמע ישראל ה' אלהינו ה' אחד ואני אעשה אתכם חטיבה אחת בעולם שנאמר ומי כעמך ישראל גוי אחד בארץ אמר ליה רב אחא בריה דרבא לרב אשי תינח בחד ביתא בשאר בתי מאי א''ל
כי מי גוי גדול ומי גוי גדול
אשריך ישראל
או הנסה אלהים
ולתתך עליון ו.
** {משלי טז-ו} {משלי כא-כא} {משלי כג-כג} {ירמיה לב-יח}
יסורים  תני תנא קמיה דר' יוחנן כל העוסק בתורה ובגמילות חסדים 
וקובר את בניו מוחלין לו על כל עונותיו אמר ליה רבי יוחנן בשלמא תורה וגמילות חסדים דכתיב
בחסד ואמת יכופר עון חסד זו גמילות חסדים שנאמר
רודף צדקה וחסד ימצא חיים צדקה וכבוד אמת זו תורה שנאמר
אמת קנה ואל תמכור אלא קובר את בניו מנין תנא ליה ההוא סבא משום ר' שמעון בן יוחאי אתיא עון עון כתיב הכא בחסד ואמת יכופר עון וכתיב התם
ומשלם עון אבות אל חיק בניהם. ה:
** {איכה ג-מ} {תהילים צד-יב} {משלי ג-יב}
יסורים אמר רבא ואיתימא רב חסדא אם רואה אדם שיסורין באין עליו יפשפש במעשיו שנא'
נחפשה דרכינו ונחקורה ונשובה עד ה' פשפש ולא מצא יתלה בבטול תורה שנאמר
אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו ואם תלה ולא מצא בידוע שיסורין של אהבה הם שנאמר
כי את אשר יאהב ה' יוכיח. ה.
יסורים- מתי של אהבה  א''ר יוחנן נגעים ובנים אינן יסורין של אהבה ונגעים לא והתניא כל מי שיש בו אחד מארבעה מראות נגעים הללו אינן אלא מזבח כפרה מזבח כפרה הוו יסורין של אהבה לא הוו ואב''א הא לן והא להו ואי בעית אימא הא בצנעא הא בפרהסיא ובנים לא היכי דמי אילימא דהוו להו ומתו והא א''ר יוחנן דין גרמא דעשיראה ביר אלא הא דלא הוו ליה כלל והא דהוו ליה ומתו. ה:
** {דברים ח-ה} {משלי ו-כג}
יסורים מתנות  תניא רבי שמעון בן יוחאי אומר שלש מתנות טובות נתן הקדוש ברוך הוא לישראל וכולן לא נתנן אלא ע''י יסורין אלו הן תורה וארץ ישראל והעולם הבא תורה מנין שנאמר אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו ארץ ישראל דכתיב
כי כאשר ייסר איש את בנו ה' אלהיך מיסרך וכתיב בתריה כי ה' אלהיך מביאך אל ארץ טובה העולם הבא דכתיב
כי נר מצוה ותורה אור ודרך חיים תוכחות מוסר. ה.
יסורים רב הונא תקיפו ליה ארבע מאה דני דחמרא על לגביה רב יהודה אחוה דרב סלא חסידא ורבנן ואמרי לה רב אדא בר אהבה ורבנן ואמרו ליה לעיין מר במיליה אמר להו ומי חשידנא בעינייכו אמרו ליה מי חשיד קב''ה דעביד דינא בלא דינא אמר להו אי איכא מאן דשמיע עלי מלתא לימא אמרו ליה הכי שמיע לן דלא יהיב מר שבישא לאריסיה אמר להו מי קא שביק לי מידי מיניה הא קא גניב ליה כוליה אמרו ליה היינו דאמרי אינשי בתר גנבא גנוב וטעמא טעים אמר להו קבילנא עלי דיהיבנא ליה איכא דאמרי הדר חלא והוה חמרא ואיכא דאמרי אייקר חלא ואיזדבן בדמי דחמרא: ה:
יסורים- רפואה רבי חייא בר אבא חלש על לגביה ר' יוחנן א''ל חביבין עליך יסורין א''ל לא הן ולא שכרן א''ל הב לי ידך יהב ליה ידיה ואוקמיה. ר' יוחנן חלש על לגביה ר' חנינא א''ל חביבין עליך יסורין א''ל לא הן ולא שכרן א''ל הב לי ידך יהב ליה ידיה ואוקמיה אמאי לוקים ר' יוחנן לנפשיה אמרי אין חבוש מתיר עצמו מבית האסורים רבי אליעזר חלש על לגביה רבי יוחנן חזא דהוה קא גני בבית אפל גלייה לדרעיה ונפל נהורא חזייה דהוה קא בכי ר' אליעזר א''ל אמאי קא בכית אי משום תורה דלא אפשת שנינו אחד המרבה ואחד הממעיט ובלבד שיכוין לבו לשמים ואי משום מזוני לא כל אדם זוכה לשתי שלחנות ואי משום בני דין גרמא דעשיראה ביר א''ל להאי שופרא דבלי בעפרא קא בכינא א''ל על דא ודאי קא בכית ובכו תרוייהו אדהכי והכי א''ל חביבין עליך יסורין א''ל לא הן ולא שכרן א''ל הב לי ידך יהב ליה ידיה ואוקמיה. ה:
** {ישעיה נג-י} {ישעיה נג-י} {ישעיה נג-י} {ישעיה נג-י} {תהילים סו-כ} {ויקרא ב-יג} {דברים כח-סט}
יסורים של אהבה  אמר רבא אמר רב סחורה אמר רב הונא כל שהקב''ה חפץ בו מדכאו ביסורין שנאמר
וה' חפץ דכאו החלי יכול אפילו לא קבלם מאהבה תלמוד לומר
אם תשים אשם נפשו מה אשם לדעת אף יסורין לדעת ואם קבלם מה שכרו
יראה זרע יאריך ימים ולא עוד אלא שתלמודו מתקיים בידו שנא'
וחפץ ה' בידו יצלח פליגי בה רבי יעקב בר אידי ורבי אחא בר חנינא חד אמר אלו הם יסורין של אהבה כל שאין בהן בטול תורה שנאמר אשרי הגבר אשר תיסרנו יה ומתורתך תלמדנו וחד אמר אלו הם יסורין של אהבה כל שאין בהן בטול תפלה שנאמר
ברוך אלהים אשר לא הסיר תפלתי וחסדו מאתי אמר להו רבי אבא בריה דר' חייא בר אבא הכי אמר ר' חייא בר אבא א''ר יוחנן אלו ואלו יסורין של אהבה הן שנאמר כי את אשר יאהב ה' יוכיח אלא מה ת''ל ומתורתך תלמדנו אל תקרי תלמדנו אלא תלמדנו דבר זה מתורתך תלמדנו ק''ו משן ועין מה שן ועין שהן אחד מאבריו של אדם עבד יוצא בהן לחרות יסורין שממרקין כל גופו של אדם על אחת כמה וכמה והיינו דרבי שמעון בן לקיש דאמר רשב''ל נאמר ברית במלח ונאמר ברית ביסורין נאמר ברית במלח דכתיב
ולא תשבית מלח ברית ונאמר ברית ביסורין דכתיב
אלה דברי הברית מה ברית האמור במלח מלח ממתקת את הבשר אף ברית האמור ביסורין יסורין ממרקין כל עונותיו של אדם: ה.
** {משלי ג-יב}
יסורים של אהבה אם תלה ולא מצא בידוע שיסורין של אהבה הם שנאמר
כי את אשר יאהב ה' יוכיח ה.
** {דברים טז-א} {במדבר לג-ג}
יציאת מצרים זמן הכל מודים כשנגאלו ישראל ממצרים לא נגאלו אלא בערב שנאמר
הוציאך ה' אלהיך ממצרים לילה וכשיצאו לא יצאו אלא ביום שנא'
ממחרת הפסח יצאו בני ישראל ביד רמה על מה נחלקו על שעת חפזון ר' אלעזר בן עזריה סבר מאי חפזון חפזון דמצרים ורבי עקיבא סבר מאי חפזון חפזון דישראל  ט.
** {בראשית טו-יג} {שמות יב-לו} {תהילים סח-יג} {שמות יב-לו}
יציאת מצרים שלל דבר נא באזני העם וגו' אמרי דבי ר' ינאי . אין נא אלא לשון בקשה אמר ליה הקב''ה למשה בבקשה ממך לך ואמור להם לישראל בבקשה מכם שאלו ממצרים כלי כסף וכלי זהב שלא יאמר אותו צדיק
ועבדום וענו אותם קיים בהם ואחרי כן יצאו ברכוש גדול לא קיים בהם אמרו לו ולואי שנצא בעצמנו משל לאדם שהיה חבוש בבית האסורים והיו אומרים לו בני אדם מוציאין אותך למחר מבית האסורין ונותנין לך ממון הרבה ואומר להם בבקשה מכם הוציאוני היום ואיני מבקש כלום:
וישאלום א''ר אמי מלמד שהשאילום בעל כרחם איכא דאמרי בעל כרחם דמצרים וא''ד בעל כרחם דישראל מ''ד בעל כרחם דמצרים דכתיב
ונות בית תחלק שלל מ''ד בעל כרחם דישראל משום משוי:
וינצלו את מצרים א''ר אמי מלמד שעשאוה כמצודה שאין בה דגן ור''ל אמר עשאוה כמצולה שאין בה דגים: ט:
** {תהילים ד-ה}
יצר הרע א''ר לוי בר חמא אמר ר''ש בן לקיש לעולם ירגיז אדם יצר טוב על יצר הרע שנא'
רגזו ואל תחטאו. אם נצחו מוטב ואם לאו יעסוק בתורה שנאמר אמרו בלבבכם אם נצחו מוטב ואם לאו יקרא קריאת שמע שנאמר על משכבכם אם נצחו מוטב ואם לאו יזכור לו יום המיתה שנאמר ודומו סלה. ה.
** {קהלת יב-יג} {קהלת יב-יג}
יראת שמים  וא''ר חלבו אמר רב הונא כל אדם שיש בו יראת שמים דבריו נשמעין שנאמר
סוף דבר הכל נשמע את האלהים ירא וגו' מאי
כי זה כל האדם א''ר אלעזר אמר הקב''ה כל העולם כלו לא נברא אלא בשביל זה רבי אבא בר כהנא אמר שקול זה כנגד כל העולם כולו ר' שמעון בן עזאי אומר ואמרי לה ר' שמעון בן זומא אומר כל העולם כולו לא נברא אלא לצוות לזה: ו:
כבוד זקן ששכח לימוד שלו והזהרו בזקן ששכח תלמודו מחמת אונסו דאמרינן לוחות ושברי לוחות מונחות בארון ח:
כביכול ברכה לה’ תניא א''ר ישמעאל בן אלישע פעם אחת נכנסתי להקטיר קטורת לפני ולפנים וראיתי אכתריאל יה ה' צבאות שהוא יושב על כסא רם ונשא ואמר לי ישמעאל בני ברכני אמרתי לו יה''ר מלפניך שיכבשו רחמיך את כעסך ויגולו רחמיך על מדותיך ותתנהג עם בניך במדת הרחמים ותכנס להם לפנים משורת הדין ונענע לי בראשו וקמ''ל שלא תהא ברכת הדיוט קלה בעיניך:  ז.
** {ישעיה סב-ח} {דברים לג-ב} {תהילים כט-יא} {דברים כח-י} {דברי הימים א יז-כא} {דברים כו-יז} {דברים ו-ד} {דברים ד-ז} {דברים לג-כט} {דברים ד-לד} {דברים כו-יט}
כביכול תפילין של ה’ א''ר אבין בר רב אדא א''ר יצחק מנין שהקב''ה מניח תפילין שנאמר
נשבע ה' בימינו ובזרוע עוזו בימינו זו תורה שנאמר
מימינו אש דת למו ובזרוע עוזו אלו תפילין שנאמר
ה' עוז לעמו יתן ומנין שהתפילין עוז הם לישראל דכתי'
וראו כל עמי הארץ כי שם ה' נקרא עליך ויראו ממך ותניא ר' אליעזר הגדול אומר אלו תפילין שבראש א''ל רב נחמן בר יצחק לרב חייא בר אבין הני תפילין דמרי עלמא מה כתיב בהו א''ל
ומי כעמך ישראל גוי אחד בארץ ומי משתבח קוב''ה בשבחייהו דישראל אין דכתיב
את ה' האמרת היום (וכתיב) וה' האמירך היום אמר להם הקב''ה לישראל אתם עשיתוני חטיבה אחת בעולם ואני אעשה אתכם חטיבה אחת בעולם אתם עשיתוני חטיבה אחת בעולם שנאמר
שמע ישראל ה' אלהינו ה' אחד ואני אעשה אתכם חטיבה אחת בעולם שנאמר ומי כעמך ישראל גוי אחד בארץ אמר ליה רב אחא בריה דרבא לרב אשי תינח בחד ביתא בשאר בתי מאי א''ל
כי מי גוי גדול ומי גוי גדול
אשריך ישראל
או הנסה אלהים
ולתתך עליון אי הכי נפישי להו טובי בתי אלא כי מי גוי גדול ומי גוי גדול דדמיין להדדי בחד ביתא אשריך ישראל ומי כעמך ישראל בחד ביתא או הנסה אלהים בחד ביתא ולתתך עליון בחד ביתא וכולהו כתיבי באדרעיה ו.
** {ישעיה נו-ז}
כביכול תפלה של ה’ א''ר יוחנן משום ר' יוסי מנין שהקב''ה מתפלל שנאמר
והביאותים אל הר קדשי ושמחתים בבית תפלתי תפלתם לא נאמר אלא תפלתי מכאן שהקב''ה מתפלל. מאי מצלי אמר רב זוטרא בר טוביה אמר רב יה''ר מלפני שיכבשו רחמי את כעסי ויגולו רחמי על מדותי ואתנהג עם בני במדת רחמים ואכנס להם לפנים משורת הדין. ז.
** {תהילים ז-יב} {במדבר כד-טז} {מיכה ו-ה} {מיכה ו-ה} {במדבר כג-ח} {תהילים ל-ו} {ישעיה כו-כ} {תהילים קמה-ט} {משלי יז-כו}
כעס ה’ ומי איכא רתחא קמיה דקודשא בריך הוא אין דתניא
ואל זועם בכל יום וכמה זעמו רגע וכמה רגע אחד מחמשת רבוא ושמונת אלפים ושמנה מאות ושמנים ושמנה בשעה וזו היא רגע ואין כל בריה יכולה לכוין אותה שעה חוץ מבלעם הרשע דכתיב ביה
ויודע דעת עליון השתא דעת בהמתו לא הוה ידע דעת עליון הוה ידע אלא מלמד שהיה יודע לכוין אותה שעה שהקב''ה כועס בה והיינו דאמר להו נביא לישראל
עמי זכר נא מה יעץ בלק מלך מואב וגו' מאי
למען דעת צדקות ה' א''ר אלעזר אמר להם הקב''ה לישראל דעו כמה צדקות עשיתי עמכם שלא כעסתי בימי בלעם הרשע שאלמלי כעסתי לא נשתייר משונאיהם של ישראל שריד ופליט והיינו דקא''ל בלעם לבלק
מה אקב לא קבה אל ומה אזעם לא זעם ה' מלמד שכל אותן הימים לא זעם. וכמה זעמו רגע וכמה רגע א''ר אבין ואיתימא רבי אבינא רגע כמימריה. ומנא לן דרגע רתח שנא'
כי רגע באפו חיים ברצונו ואב''א מהכא
חבי כמעט רגע עד יעבור זעם ואימת רתח אמר אביי בהנך תלת שעי קמייתא כי חיורא כרבלתא דתרנגולא וקאי אחד כרעא כל שעתא ושעתא נמי קאי הכי כל שעתא אית ביה שורייקי סומקי בההיא שעתא לית ביה שורייקי סומקי. ההוא צדוקי דהוה בשבבותיה דר' יהושע בן לוי הוה קא מצער ליה טובא בקראי יומא חד שקל תרנגולא ואוקמיה בין כרעי' דערסא ועיין ביה סבר כי מטא ההיא שעתא אלטייה כי מטא ההיא שעתא ניים אמר ש''מ לאו אורח ארעא למעבד הכי
ורחמיו על כל מעשיו כתיב וכתיב
גם ענוש לצדיק לא טוב תנא משמיה דר' מאיר בשעה שהחמה זורחת וכל מלכי מזרח ומערב מניחים כתריהם בראשיהם ומשתחוים לחמה מיד כועס הקב''ה:  ז.
** {תהילים יב-ט} {תהילים סו-יב}
כרום זלות (בושת מקבל) א''ל ההוא מרבנן לרב ביבי בר אביי ואמרי לה רב ביבי לרב נחמן בר יצחק מאי
כרום זלות לבני אדם אמר ליה אלו דברים שעומדים ברומו של עולם ובני אדם מזלזלין בהן ר' יוחנן ור' אלעזר דאמרי תרוייהו כיון שנצטרך אדם לבריות פניו משתנות ככרום שנאמר כרום זלות לבני אדם מאי כרום כי אתא רב דימי אמר עוף אחד יש בכרכי הים וכרום שמו וכיון שחמה זורחת מתהפך לכמה גוונין ר' אמי ור' אסי דאמרי תרוייהו כאילו נדון בשני דינים אש ומים שנאמר
הרכבת אנוש לראשנו באנו באש ובמים: ו:
** {תהילים לב-ו} {משלי יח-כב} {קהלת ז-כו} {משלי ח-לה} {תהילים סח-כא} {איוב ג-כב}
לעת מצא
על זאת יתפלל כל חסיד אליך לעת מצא אמר ר' חנינא לעת מצא זו אשה שנא'
מצא אשה מצא טוב במערבא כי נסיב אינש אתתא אמרי ליה הכי מצא או מוצא מצא דכתיב מצא אשה מצא טוב ויפק רצון מה' מוצא דכתיב
ומוצא אני מר ממות את האשה וגו' ר' נתן אומר לעת מצא זו תורה שנאמר
כי מוצאי מצא חיים וגו' רב נחמן בר יצחק אמר לעת מצא זו מיתה שנא'
למות תוצאות תניא נמי הכי תשע מאות ושלשה מיני מיתה נבראו בעולם שנאמר למות תוצאות תוצאות בגימטריא הכי הוו קשה שבכלן אסכרא ניחא שבכלן נשיקה אסכרא דמיא כחיזרא בגבבא דעמרא דלאחורי נשרא ואיכא דאמרי כפיטורי בפי ושט נשיקה דמיא כמשחל בניתא מחלבא ר' יוחנן אמר לעת מצא זו קבורה א''ר חנינא מאי קרא
השמחים אלי גיל ישישו כי ימצאו קבר אמר רבה בר רב שילא היינו דאמרי אינשי ליבעי אינש רחמי אפילו עד זיבולא בתרייתא שלמא מר זוטרא אמר לעת מצא זה בית הכסא אמרי במערבא הא דמר זוטרא עדיפא מכלהו. ח.
** {תהילים סח-כא}
מיתה מינים ותפלה רב נחמן בר יצחק אמר לעת מצא זו מיתה שנא'
למות תוצאות תניא נמי הכי תשע מאות ושלשה מיני מיתה נבראו בעולם שנאמר למות תוצאות תוצאות בגימטריא הכי הוו קשה שבכלן אסכרא ניחא שבכלן נשיקה אסכרא דמיא כחיזרא בגבבא דעמרא דלאחורי נשרא ואיכא דאמרי כפיטורי בפי ושט נשיקה דמיא כמשחל בניתא מחלבא
** {ישעיה ו-ו} {דניאל ט-כא} {דניאל י-יג}
מלאכים א''ר אלעזר בר אבינא גדול מה שנאמר במיכאל יותר ממה שנאמר בגבריאל דאילו במיכאל כתי'
ויעף אלי אחד מן השרפים ואלו גבי גבריאל כתי'
והאיש גבריאל אשר ראיתי בחזון בתחלה מועף ביעף וגו' מאי משמע דהאי אחד מיכאל הוא אמר ר' יוחנן אתיא אחד אחד כתיב הכא ויעף אלי אחד מן השרפים וכתי' התם
והנה מיכאל אחד (מן) השרים הראשונים בא לעזרני תנא מיכאל באחת גבריאל בשתים אליהו בארבע ומלאך המות בשמנה ובשעת המגפה באחת: ד:
** {מלכים א יח-ב}
מלך ונביא חזקיהו אמר ליתי ישעיהו גבאי דהכי אשכחן באליהו דאזל לגבי אחאב (שנאמר
וילך אליהו להראות אל אחאב ישעיהו אמר ליתי חזקיהו גבאי דהכי אשכחן ביהורם בן אחאב דאזל לגבי אלישע י.
** {משלי טו-א} {תהילים קיא-י} {שמות כד-יא}
מרגלא בפומיה מרגלא בפומיה דר''מ גמור בכל לבבך ובכל נפשך לדעת את דרכי ולשקוד על דלתי תורתי נצור תורתי בלבך ונגד עיניך תהיה יראתי שמור פיך מכל חטא וטהר וקדש עצמך מכל אשמה ועון ואני אהיה עמך בכל מקום. מרגלא בפומייהו דרבנן דיבנה אני בריה וחברי בריה אני מלאכתי בעיר והוא מלאכתו בשדה אני משכים למלאכתי והוא משכים למלאכתו כשם שהוא אינו מתגדר במלאכתי כך אני איני מתגדר במלאכתו ושמא תאמר אני מרבה והוא ממעיט שנינו אחד המרבה ואחד הממעיט ובלבד שיכוין לבו לשמים. מרגלא בפומיה דאביי לעולם יהא אדם ערום ביראה
מענה רך משיב חמה ומרבה שלום עם אחיו ועם קרוביו ועם כל אדם ואפילו עם נכרי בשוק כדי שיהא אהוב למעלה ונחמד למטה ויהא מקובל על הבריות אמרו עליו על רבן יוחנן בן זכאי שלא הקדימו אדם שלום מעולם ואפילו נכרי בשוק. מרגלא בפומיה דרבא תכלית חכמה תשובה ומעשים טובים שלא יהא אדם קורא ושונה ובועט באביו ובאמו וברבו ובמי שהוא גדול ממנו בחכמה ובמנין שנאמר
ראשית חכמה יראת ה' שכל טוב לכל עושיהם לעושים לא נאמר אלא לעושיהם לעושים לשמה ולא לעושים שלא לשמה וכל העושה שלא לשמה נוח לו שלא נברא. מרגלא בפומיה דרב [לא כעולם הזה העולם הבא] העולם הבא אין בו לא אכילה ולא שתיה ולא פריה ורביה ולא משא ומתן ולא קנאה ולא שנאה ולא תחרות אלא צדיקים יושבין ועטרותיהם בראשיהם ונהנים מזיו השכינה שנאמר
ויחזו את האלהים ויאכלו וישתו: יז.
** {הושע ב-ט} {משלי יז-י}
מרדות בלב אדם וא''ר יוחנן משום רבי יוסי טובה מרדות אחת בלבו של אדם יותר מכמה מלקיות שנא'
ורדפה את מאהביה וגו' ואמרה אלכה ואשובה אל אישי הראשון כי טוב לי אז מעתה וריש לקיש אמר יותר ממאה מלקיות שנאמר
תחת גערה במבין מהכות כסיל מאה:  ז.
** {שמות ג-יד}
משה אהיה אהיה אשר אהיה א''ל הקב''ה למשה לך אמור להם לישראל אני הייתי עמכם בשעבוד זה ואני אהיה עמכם בשעבוד מלכיות אמר לפניו רבש''ע דיה לצרה בשעתה א''ל הקב''ה לך אמור להם
אהיה שלחני אליכם: ט:
** {שמות לג-טז} {שמות לג-טז} {שמות לג-יג} {שמות לד-ז} {דברים כד-טז} {שמות לג-יט} {שמות לג-כ} {שמות ג-ו} {שמות לד-ל} {במדבר יב-ח} {שמות לג-כג} {דברים ט-יד} {דברי הימים א כג-טו} {שמות א-ז}
משה קבל מה’ וא''ר יוחנן משום ר' יוסי שלשה דברים בקש משה מלפני הקב''ה ונתן לו בקש שתשרה שכינה על ישראל ונתן לו שנאמר
הלוא בלכתך עמנו בקש שלא תשרה שכינה על עובדי כוכבים ונתן לו שנאמר
ונפלינו אני ועמך בקש להודיעו דרכיו של הקב''ה ונתן לו שנא'
הודיעני נא את דרכיך אמר לפניו רבש''ע מפני מה יש צדיק וטוב לו ויש צדיק ורע לו יש רשע וטוב לו ויש רשע ורע לו אמר לו משה צדיק וטוב לו צדיק בן צדיק צדיק ורע לו צדיק בן רשע רשע וטוב לו רשע בן צדיק רשע ורע לו רשע בן רשע: אמר מר צדיק וטוב לו צדיק בן צדיק צדיק ורע לו צדיק בן רשע איני והא כתיב
פקד עון אבות על בנים וכתיב
ובנים לא יומתו על אבות ורמינן קראי אהדדי ומשנינן לא קשיא הא כשאוחזין מעשה אבותיהם בידיהם הא כשאין אוחזין מעשה אבותיהם בידיהם אלא הכי קא''ל צדיק וטוב לו צדיק גמור צדיק ורע לו צדיק שאינו גמור רשע וטוב לו רשע שאינו גמור רשע ורע לו רשע גמור ופליגא דר' מאיר דא''ר מאיר שתים נתנו לו ואחת לא נתנו לו שנא'
וחנתי את אשר אחון אע''פ שאינו הגון ורחמתי את אשר ארחם אע''פ שאינו הגון
ויאמר לא תוכל לראות את פני תנא משמיה דר' יהושע בן קרחה כך א''ל הקב''ה למשה כשרציתי לא רצית עכשיו שאתה רוצה איני רוצה ופליגא דר' שמואל בר נחמני א''ר יונתן דא''ר שמואל בר נחמני א''ר יונתן בשכר שלש זכה לשלש בשכר
ויסתר משה פניו זכה לקלסתר פנים בשכר כי ירא זכה
לוייראו מגשת אליו בשכר מהביט זכה
לותמונת ה' יביט:
והסירתי את כפי וראית את אחרי אמר רב חנא בר ביזנא א''ר שמעון חסידא מלמד שהראה הקב''ה למשה קשר של תפילין: וא''ר יוחנן משום ר' יוסי כל דבור ודבור שיצא מפי הקב''ה לטובה אפי' על תנאי לא חזר בו מנא לן ממשה רבינו שנא'
הרף ממני ואשמידם וגו' ואעשה אותך לגוי עצום אע''ג דבעא משה רחמי עלה דמלתא ובטלה אפ''ה אוקמה בזרעיה שנא'
בני משה גרשום ואליעזר ויהיו בני אליעזר רחביה הראש וגו' ובני רחביה רבו למעלה וגו' ותני רב יוסף למעלה מששים רבוא אתיא רביה רביה כתיב הכא רבו למעלה וכתיב התם
ובני ישראל פרו וישרצו וירבו:  ז.
** {בראשית טו-יג}
משה שלל מצרים אין נא אלא לשון בקשה אמר ליה הקב''ה למשה בבקשה ממך לך ואמור להם לישראל בבקשה מכם שאלו ממצרים כלי כסף וכלי זהב שלא יאמר אותו צדיק
ועבדום וענו אותם קיים בהם ואחרי כן יצאו ברכוש גדול לא קיים בהם אמרו לו ולואי שנצא בעצמנו משל לאדם שהיה חבוש בבית האסורים והיו אומרים לו בני אדם מוציאין אותך למחר מבית האסורין ונותנין לך ממון הרבה ואומר להם בבקשה מכם הוציאוני היום ואיני מבקש כלום:  ט:
** {קהלת ט-ה} {קהלת ט-ה} {שמואל ב כג-כ} {יחזקאל כא-ל} {דברים יז-ו} {איוב יד-כא} {איוב יד-כב} {דברים לד-ד}
מת יודע ואיכפת רבי חייא ורבי יונתן הוו שקלי ואזלי בבית הקברות הוה קשדיא תכלתא דרבי יונתן אמר ליה רבי חייא דלייה כדי שלא יאמרו למחר באין אצלנו ועכשיו מחרפין אותנו אמר ליה ומי ידעי כולי האי והא כתיב
והמתים אינם יודעים מאומה אמר ליה אם קרית לא שנית אם שנית לא שלשת אם שלשת לא פירשו לך
כי החיים יודעים שימותו אלו צדיקים שבמיתתן נקראו חיים שנאמר
ובניהו בן יהוידע בן איש חי רב פעלים מקבצאל הוא הכה את שני אריאל מואב והוא ירד והכה את הארי בתוך הבור ביום השלג בן איש חי אטו כולי עלמא בני מתי נינהו אלא בן איש חי שאפי' במיתתו קרוי חי רב פעלים מקבצאל שריבה וקבץ פועלים לתורה והוא הכה את שני אריאל מואב שלא הניח כמותו לא במקדש ראשון ולא במקדש שני והוא ירד והכה את הארי בתוך הבור ביום השלג איכא דאמרי דתבר גזיזי דברדא ונחת וטבל איכא דאמרי דתנא סיפרא דבי רב ביומא דסיתוא. והמתים אינם יודעים מאומה אלו רשעים שבחייהן קרויין מתים שנאמר
ואתה חלל רשע נשיא ישראל ואי בעית אימא מהכא
על פי שנים עדים או (על פי) שלשה עדים יומת המת חי הוא אלא המת מעיקרא: בני ר' חייא נפוק לקרייתא אייקר להו תלמודייהו הוו קא מצערי לאדכוריה א''ל חד לחבריה ידע אבון בהאי צערא א''ל אידך מנא ידע והא כתיב
יכבדו בניו ולא ידע א''ל אידך ולא ידע והא כתיב
אך בשרו עליו יכאב ונפשו עליו תאבל ואמר רבי יצחק קשה רמה למת כמחט בבשר החי אמרי בצערא דידהו ידעי בצערא דאחרינא לא ידעי ולא והתניא מעשה בחסיד אחד שנתן דינר לעני בערב ר''ה בשני בצורת והקניטתו אשתו והלך ולן בבית הקברות ושמע שתי רוחות שמספרות זו לזו אמרה חדא לחברתה חברתי בואי ונשוט בעולם ונשמע מאחורי הפרגוד מה פורענות בא לעולם אמרה לה חברתה איני יכולה שאני קבורה במחצלת של קנים אלא לכי את ומה שאת שומעת אמרי לי הלכה היא ושטה ובאה ואמרה לה חברתה חברתי מה שמעת מאחורי הפרגוד אמרה לה שמעתי שכל הזורע ברביעה ראשונה ברד מלקה אותו הלך הוא וזרע ברביעה שניה של כל העולם כולו לקה שלו לא לקה לשנה האחרת הלך ולן בבית הקברות ושמע אותן שתי רוחות שמספרות זו עם זו אמרה חדא לחברתה בואי ונשוט בעולם ונשמע מאחורי הפרגוד מה פורענות בא לעולם אמרה לה חברתי לא כך אמרתי לך איני יכולה שאני קבורה במחצלת של קנים אלא לכי את ומה שאת שומעת בואי ואמרי לי הלכה ושטה ובאה ואמרה לה חברתה חברתי מה שמעת מאחורי הפרגוד אמרה לה שמעתי שכל הזורע ברביעה שניה שדפון מלקה אותו הלך וזרע ברביעה ראשונה של כל העולם כולו נשדף ושלו לא נשדף אמרה לו אשתו מפני מה אשתקד של כל העולם כולו לקה ושלך לא לקה ועכשיו של כל העולם כולו נשדף ושלך לא נשדף סח לה כל הדברים הללו אמרו לא היו ימים מועטים עד שנפלה קטטה בין אשתו של אותו חסיד ובין אמה של אותה ריבה אמרה לה לכי ואראך בתך שהיא קבורה במחצלת של קנים לשנה האחרת הלך ולן בבית הקברות ושמע אותן רוחות שמספרות זו עם זו אמרה לה חברתי בואי ונשוט בעולם ונשמע מאחורי הפרגוד מה פורענות בא לעולם אמרה לה חברתי הניחני דברים שביני לבינך כבר נשמעו בין החיים אלמא ידעי דילמא איניש אחרינא שכיב ואזיל ואמר להו ת''ש דזעירי הוה מפקיד זוזי גבי אושפזיכתיה עד דאתי ואזיל לבי רב שכיבה אזל בתרה לחצר מות אמר לה זוזי היכא אמרה ליה זיל שקלינהו מתותי בצנורא דדשא בדוך פלן ואימא לה לאימא תשדר לי מסרקאי וגובתאי דכוחלא בהדי פלניתא דאתיא למחר אלמא ידעי [דלמא] דומה קדים ומכריז להו ת''ש דאבוה דשמואל הוו קא מפקדי גביה זוזי דיתמי כי נח נפשיה לא הוה שמואל גביה הוו קא קרו ליה בר אכיל זוזי דיתמי אזל אבתריה לחצר מות אמר להו בעינא אבא אמרו ליה אבא טובא איכא הכא אמר להו בעינא אבא בר אבא אמרו ליה אבא בר אבא נמי טובא איכא הכא אמר להו בעינא אבא בר אבא אבוה דשמואל היכא אמרו ליה סליק למתיבתא דרקיעא אדהכי חזייה ללוי דיתיב אבראי אמר ליה אמאי יתבת אבראי מאי טעמא לא סלקת אמר ליה דאמרי לי כל כי הנך שני דלא סליקת למתיבתא דרבי אפס ואחלישתיה לדעתיה לא מעיילינן לך למתיבתא דרקיעא אדהכי והכי אתא אבוה חזייה דהוה קא בכי ואחיך אמר ליה מאי טעמא קא בכית אמר ליה דלעגל קא אתית מאי טעמא אחיכת דחשיבת בהאי עלמא טובא אמר ליה אי חשיבנא נעיילוה ללוי ועיילוהו ללוי אמר ליה זוזי דיתמי היכא אמר ליה זיל שקלינהו באמתא דרחיא עילאי ותתאי דידן ומיצעי דיתמי אמר ליה מאי טעמא עבדת הכי אמר ליה אי גנובי גנבי מגנבו מדידן אי אכלה ארעא אכלה מדידן אלמא דידעי דילמא שאני שמואל כיון דחשיב קדמי ומכרזי פנו מקום . ואף ר' יונתן הדר ביה דאמר רבי שמואל בר נחמני אמר ר' יונתן מנין למתים שמספרים זה עם זה שנאמר
ויאמר ה' אליו זאת הארץ אשר נשבעתי לאברהם ליצחק וליעקב לאמר מאי לאמר אמר הקדוש ברוך הוא למשה לך אמור להם לאברהם ליצחק וליעקב שבועה שנשבעתי לכם כבר קיימתיה לבניכם ואי ס''ד דלא ידעי כי אמר להו מאי הוי אלא מאי דידעי למה לי' למימר להו לאחזוקי ליה טיבותא למשה אמר רבי יצחק כל המספר אחרי המת כאלו מספר אחרי האבן איכא דאמרי דלא ידעי ואיכא דאמרי דידעי ולא איכפת להו איני והא אמר רב פפא חד אישתעי מילתא בתריה דמר שמואל ונפל קניא מטללא ובזעא לארנקא דמוחיה שאני צורבא מרבנן דקודשא בריך הוא תבע ביקריה יח
** {משלי יט-יז} {משלי יד-לא}
מת מלווה ואם הלוהו מה שכרו אמר רב אסי עליו הכתוב אומר
מלוה ה' חונן דל
ומכבדו חונן אביון:  יח.
** {שמואל א ז-יז}
מתנה אמר אביי ואיתימא ר' יצחק הרוצה להנות יהנה כאלישע ושאינו רוצה להנות אל יהנה כשמואל הרמתי שנאמר
ותשובתו הרמתה כי שם ביתו וא''ר יוחנן שכל מקום שהלך שם ביתו עמו. י.
מתפלל בחורבה  תניא א''ר יוסי פעם אחת הייתי מהלך בדרך ונכנסתי לחורבה אחת מחורבות ירושלים להתפלל בא אליהו זכור לטוב ושמר לי על הפתח (והמתין לי) עד שסיימתי תפלתי לאחר שסיימתי תפלתי אמר לי שלום עליך רבי ואמרתי לו שלום עליך רבי ומורי ואמר לי בני מפני מה נכנסת לחורבה זו אמרתי לו להתפלל ואמר לי היה לך להתפלל בדרך ואמרתי לו מתיירא הייתי שמא יפסיקו בי עוברי דרכים ואמר לי היה לך להתפלל תפלה קצרה ואמר לי בני מה קול שמעת בחורבה זו ואמרתי לו שמעתי בת קול שמנהמת כיונה ואומרת אוי לבנים שבעונותיהם החרבתי את ביתי ושרפתי את היכלי והגליתים לבין האומות ואמר לי חייך וחיי ראשך לא שעה זו בלבד אומרת כך אלא בכל יום ויום שלש פעמים אומרת כך ולא זו בלבד אלא בשעה שישראל נכנסין לבתי כנסיות ולבתי מדרשות ועונין יהא שמיה הגדול מבורך הקב''ה מנענע ראשו ואומר אשרי המלך שמקלסין אותו בביתו כך מה לו לאב שהגלה את בניו ואוי להם לבנים שגלו מעל שולחן אביהם:  ג.
** {תהילים קיב-א} {תהילים קכח-ב}
נהנה מגיעו ואמר רבי חייא בר אמי משמיה דעולא גדול הנהנה מיגיעו יותר מירא שמים דאילו גבי ירא שמים כתיב
אשרי איש ירא את ה' ואילו גבי נהנה מיגיעו כתיב
יגיע כפיך כי תאכל אשריך וטוב לך אשריך בעולם הזה וטוב לך לעולם הבא ולגבי ירא שמים וטוב לך לא כתיב ביה:  ח.
** {משלי כג-כה}
נידוי ואמר ר' יהושע בן לוי בכ''ד מקומות בית דין מנדי' על כבוד הרב וכולן שנינו במשנתנו אמר ליה ר' אלעזר היכא אמר ליה לכי תשכח נפק דק ואשכח תלת המזלזל בנטילת ידים והמספר אחר מטתן של תלמידי חכמי' והמגיס דעתו כלפי מעלה המספר אחר מטתן של תלמידי חכמים מאי היא דתנן הוא היה אומר אין משקין לא את הגיורת ולא את המשוחררת וחכמים אומרים משקין ואמרו לו מעשה בכרכמית שפחה משוחררת בירושלים והשקוה שמעיה ואבטליון ואמר להם דוגמא השקוה ונדוהו ומת בנדויו וסקלו בית דין את ארונו והמזלזל בנטילת ידים מאי היא דתנן א''ר יהודה חס ושלום שעקביא בן מהללאל נתנדה שאין עזרה ננעלת על כל אדם בישראל בחכמה ובטהרה וביראת חטא כעקביא בן מהללאל אלא את מי נדו את אלעזר בן חנוך שפקפק בנטילת ידים וכשמת שלחו בית דין והניחו אבן גדולה על ארונו ללמדך שכל המתנדה ומת בנדויו ב''ד סוקלין את ארונו המגיס דעתו כלפי מעלה מאי היא דתנן שלח לו שמעון בן שטח לחוני המעגל צריך אתה להתנדות ואלמלא חוני אתה גוזרני עליך נדוי אבל מה אעשה שאתה מתחטא לפני המקום ועושה לך רצונך כבן שמתחטא לפני אביו ועושה לו רצונו ועליך הכתוב אומר
ישמח אביך ואמך ותגל יולדתך ותו ליכא והא איכא דתני רב יוסף תודוס איש רומי הנהיג את בני רומי להאכילן גדיים מקולסין בלילי פסחים שלח ליה שמעון בן שטח אלמלא תודוס אתה גוזרני עליך נדוי שאתה מאכיל את ישראל קדשים בחוץ במשנתנו קאמרינן והא ברייתא היא ובמתני' ליכא והא איכא הא דתנן חתכו חוליות ונתן חול בין חוליא לחוליא ר' אליעזר מטהר וחכמים מטמאים וזהו תנורו של עכנאי מאי עכנאי אמר רב יהודה אמר שמואל מלמד שהקיפוהו הלכות כעכנאי זה וטמאוהו ותניא אותו היום הביאו כל טהרות שטיהר ר''א ושרפום לפניו ולבסוף ברכוהו אפילו הכי נדוי במתני' לא תנן אלא בכ''ד מקומות היכא משכחת לה ר' יהושע בן לוי מדמה מילתא למילתא ור' אלעזר לא מדמה מילתא למילתא: יט.
** {דברים י-יז} {במדבר ו-כו} {דברים ח-י}
נשיאות פנים של ה’ דרש רב עוירא זמנין אמר לה משמיה דר' אמי וזמנין אמר לה משמיה דר' אסי אמרו מלאכי השרת לפני הקב''ה רבש''ע כתוב בתורתך
אשר לא ישא פנים ולא יקח שחד והלא אתה נושא פנים לישראל דכתיב
ישא ה' פניו אליך אמר להם וכי לא אשא פנים לישראל שכתבתי להם בתורה
ואכלת ושבעת וברכת את ה' אלהיך והם מדקדקים [על] עצמם עד כזית ועד כביצה: כ:
** {ישעיה לב-ט}
נשים גדולה הבטחה שהבטיחן הקב''ה לנשים יותר מן האנשים שנא'
נשים שאננות קומנה שמענה קולי בנות בוטחות האזנה אמרתי א''ל רב לר' חייא נשים במאי זכיין באקרויי בנייהו לבי כנישתא ובאתנויי גברייהו בי רבנן ונטרין לגברייהו עד דאתו מבי רבנן.  יז.
** {בראשית מט-כב} {בראשית מח-טז}
עין הרע יוסף אנא מזרעא דיוסף קא אתינא דלא שלטא ביה עינא בישא דכתיב
בן פורת יוסף בן פורת עלי עין ואמר רבי אבהו אל תקרי עלי עין אלא עולי עין רבי יוסי ברבי חנינא אמר מהכא
וידגו לרוב בקרב הארץ מה דגים שבים מים מכסין עליהם ואין עין הרע שולטת בהם אף זרעו של יוסף אין עין הרע שולטת בהם ואב''א עין שלא רצתה לזון ממה שאינו שלו אין עין הרע שולטת בו: כ.
עצות לבניו רבא אמר להו רבא לבניה כשאתם חותכין בשר אל תחתכו על גב היד איכא דאמרי משום סכנה ואיכא דאמרי משום קלקול סעודה ואל תשבו על מטת ארמית ואל תעברו אחורי בית הכנסת בשעה שהצבור מתפללין. D ח:
עצות לבניו רבי יהושע בן לוי אמר להו ר' יהושע בן לוי לבניה אשלימו פרשיותייכו עם הצבור שנים מקרא ואחד תרגום  והזהרו בורידין כרבי יהודה דתנן רבי יהודה אומר עד שישחוט את הורידין והזהרו בזקן ששכח תלמודו מחמת אונסו דאמרינן לוחות ושברי לוחות מונחות בארון ח:
ערווה מסתכל א''ר ששת למה מנה הכתוב תכשיטין שבחוץ עם תכשיטין שבפנים לומר לך כל המסתכל באצבע קטנה של אשה כאילו מסתכל במקום התורף כד.
פתחת פה לשטן אמר אביי לא מבעי ליה לאינש למימר הכי דארשב''ל וכן תנא משמיה דרבי יוסי לעולם אל יפתח אדם פיו לשטן  יט.
** {שמות לד-ז} {דברים כד-טז} {שמות לג-יט} {שמות לג-כ}   ז.
צדיק ורע לו אמר לפניו רבש''ע מפני מה יש צדיק וטוב לו ויש צדיק ורע לו יש רשע וטוב לו ויש רשע ורע לו אמר לו משה צדיק וטוב לו צדיק בן צדיק צדיק ורע לו צדיק בן רשע רשע וטוב לו רשע בן צדיק רשע ורע לו רשע בן רשע: אמר מר צדיק וטוב לו צדיק בן צדיק צדיק ורע לו צדיק בן רשע איני והא כתיב
פקד עון אבות על בנים וכתיב
ובנים לא יומתו על אבות ורמינן קראי אהדדי ומשנינן לא קשיא הא כשאוחזין מעשה אבותיהם בידיהם הא כשאין אוחזין מעשה אבותיהם בידיהם אלא הכי קא''ל צדיק וטוב לו צדיק גמור צדיק ורע לו צדיק שאינו גמור רשע וטוב לו רשע שאינו גמור רשע ורע לו רשע גמור ופליגא דר' מאיר דא''ר מאיר שתים נתנו לו ואחת לא נתנו לו שנא'
וחנתי את אשר אחון אע''פ שאינו הגון ורחמתי את אשר ארחם אע''פ שאינו הגון
** {תהילים קמה-ט} {משלי יז-כו}
צדיק מענש ההוא צדוקי דהוה בשבבותיה דר' יהושע בן לוי הוה קא מצער ליה טובא בקראי יומא חד שקל תרנגולא ואוקמיה בין כרעי' דערסא ועיין ביה סבר כי מטא ההיא שעתא אלטייה כי מטא ההיא שעתא ניים אמר ש''מ לאו אורח ארעא למעבד הכי
ורחמיו על כל מעשיו כתיב וכתיב
גם ענוש לצדיק לא טוב ז.
** {איוב ג-כב}
קבורה תפלה לו ועד לו ר' יוחנן אמר לעת מצא זו קבורה א''ר חנינא מאי קרא
השמחים אלי גיל ישישו כי ימצאו קבר אמר רבה בר רב שילא היינו דאמרי אינשי ליבעי אינש רחמי אפילו עד זיבולא בתרייתא שלמא  ח.
קרבנות שמור... אל תהי ככסילים שחוטאים ומביאים קרבן ואינם יודעים אם על הטובה הם מביאים אם על הרעה הם מביאים אמר הקב''ה בין טוב לרע אינן מבחינים והם מביאים קרבן לפני  כג.
** {ישעיה א-כח}
קריאת התורה מניח ס"ת אמר רב הונא בר יהודה אמר רבי מנחם אמר ר' אמי מאי דכתי'
ועוזבי ה' יכלו זה המניח ס''ת ויוצא רבי אבהו נפיק בין גברא לגברא.  בעי רב פפא בין פסוקא לפסוקא מהו תיקו רב ששת מהדר אפיה וגריס אמר אנן בדידן ואינהו בדידהו: ח.
** {במדבר לב-ג} {ויקרא כג-לב}
קריאת התורה שנים מקרא אמר רב הונא בר יהודה אמר רבי אמי לעולם ישלים אדם פרשיותיו עם הצבור שנים מקרא ואחד תרגום 
ואפילו
עטרות ודיבון שכל המשלים פרשיותיו עם הצבור מאריכין לו ימיו ושנותיו רב ביבי בר אביי סבר לאשלומינהו לפרשייתא דכולא שתא במעלי יומא דכפורי תנא ליה חייא בר רב מדפתי כתיב
ועניתם את נפשתיכם בתשעה לחדש בערב וכי בתשעה מתענין והלא בעשרה מתענין אלא לומר לך כל האוכל ושותה בתשיעי מעלה עליו הכתוב כאילו מתענה תשיעי ועשירי. סבר לאקדומינהו אמר ליה ההוא סבא תנינא ובלבד שלא יקדים ושלא יאחר כדאמר להו ר' יהושע בן לוי לבניה אשלימו פרשיותייכו עם הצבור שנים מקרא ואחד תרגום ח:
ראשונים לאחרונים אמר ליה רב פפא לאביי מאי שנא ראשונים דאתרחיש להו ניסא ומאי שנא אנן דלא מתרחיש לן ניסא אי משום תנויי בשני דרב יהודה כולי תנויי בנזיקין הוה ואנן קא מתנינן שיתא סדרי וכי הוה מטי רב יהודה בעוקצין האשה שכובשת ירק בקדרה ואמרי לה זיתים שכבשן בטרפיהן טהורים אמר הויות דרב ושמואל קא חזינא הכא ואנן קא מתנינן בעוקצין תליסר מתיבתא ואילו רב יהודה כי הוה שליף חד מסאניה אתי מטרא ואנן קא מצערינן נפשין ומצוח קא צוחינן ולית דמשגח בן אמר ליה קמאי הוו קא מסרי נפשייהו אקדושת השם אנן לא מסרינן נפשין אקדושת השם כי הא דרב אדא בר אהבה חזייה לההיא כותית דהות לבישא כרבלתא בשוקא סבר דבת ישראל היא קם קרעיה מינה אגלאי מילתא דכותית היא שיימוה בארבע מאה זוזי א''ל מה שמך אמרה ליה מתון אמר לה מתון מתון ארבע מאה זוזי שויא: כ.
רבו דירה במקומו ואמר רבי חייא בר אמי משמיה דעולא לעולם ידור אדם במקום רבו שכל זמן ששמעי בן גרא קיים לא נשא שלמה את בת פרעה והתניא אל ידור לא קשיא הא דכייף ליה הא דלא כייף ליה: ח.
** {שמות לג-יד}
ריצוי בכעס וא''ר יוחנן משום ר' יוסי מנין שאין מרצין לו לאדם בשעת כעסו דכתיב
פני ילכו והנחותי לך אמר לו הקב''ה למשה המתן לי עד שיעברו פנים של זעם ואניח לך  ז.
** {שמות לג-יד}
ריצוי בכעס וא''ר יוחנן משום ר''ש בן יוחי מנין שאין מרצין לו לאדם בשעת כעסו שנאמר
פני ילכו והנחותי לך: ז:
** {ישעיה נד-א}
רני עקרה אמר לה ההוא צדוקי לברוריא כתיב
רני עקרה לא ילדה משום דלא ילדה רני אמרה ליה שטיא שפיל לסיפיה דקרא דכתיב כי רבים בני שוממה מבני בעולה אמר ה' אלא מאי עקרה לא ילדה רני כנסת ישראל שדומה לאשה עקרה שלא ילדה בנים לגיהנם כותייכו: י.
** {משלי כח-ד} {תהילים לז-א} {משלי כג-יז} {תהילים י-ה} {תהילים י-ה} {תהילים י-ה} {חבקוק א-יג} {תהילים לז-לג} {משלי יב-כא}
רשעים להתגרות וא''ר יוחנן משום ר''ש בן יוחי מותר להתגרות ברשעים בעולם הזה שנאמר
עוזבי תורה יהללו רשע ושומרי תורה יתגרו בם תניא נמי הכי רבי דוסתאי בר' מתון אומר מותר להתגרות ברשעים בעוה''ז שנא' עוזבי תורה יהללו רשע וגו' ואם לחשך אדם לומר והא כתיב
אל תתחר במרעים אל תקנא בעושי עולה אמור לו מי שלבו נוקפו אומר כן אלא אל תתחר במרעים להיות כמרעים אל תקנא בעושי עולה להיות כעושי עולה ואומר
אל יקנא לבך בחטאים כי אם ביראת ה' כל היום איני והאמר ר' יצחק אם ראית רשע שהשעה משחקת לו אל תתגרה בו שנאמר
יחילו דרכיו בכל עת ולא עוד אלא שזוכה בדין שנאמר
מרום משפטיך מנגדו ולא עוד אלא שרואה בצריו שנאמר
כל צורריו יפיח בהם לא קשיא הא במילי דידיה הא במילי דשמיא ואיבעית אימא הא והא במילי דשמיא ולא קשיא הא ברשע שהשעה משחקת לו הא ברשע שאין השעה משחקת לו ואב''א הא והא ברשע שהשעה משחקת לו ולא קשיא הא בצדיק גמור הא בצדיק שאינו גמור דאמר רב הונא מאי דכתיב
למה תביט בוגדים תחריש בבלע רשע צדיק ממנו וכי רשע בולע צדיק והא כתיב
ה' לא יעזבנו בידו וכתיב
לא יאונה לצדיק כל און אלא צדיק ממנו בולע צדיק גמור אינו בולע ואב''א שעה משחקת לו שאני:  ז:
** {תהילים קד-לה}
רשעים להתפלל שיחזרו (ע’ לעיל צדיקים מענש) הנהו בריוני דהוו בשבבותיה דר''מ והוו קא מצערו ליה טובא הוה קא בעי ר' מאיר רחמי עלויהו כי היכי דלימותו אמרה לי' ברוריא דביתהו מאי דעתך משום דכתיב
יתמו חטאים מי כתיב חוטאים חטאים כתיב ועוד שפיל לסיפיה דקרא ורשעים עוד אינם כיון דיתמו חטאים ורשעים עוד אינם אלא בעי רחמי עלויהו דלהדרו בתשובה ורשעים עוד אינם בעא רחמי עלויהו והדרו בתשובה:  י.
** {מלכים ב ד-כז}
שונמית גחזי קדוש הוא א''ר יוסי בר' חנינא הוא קדוש ומשרתו אינו קדוש (שנא')
ויגש גיחזי להדפה א''ר יוסי בר' חנינא שאחזה בהוד יפיה. י.
** {מלכים ב ד-ט}
שונמית היכר אורח
ותאמר אל אישה הנה נא ידעתי כי איש אלהים קדוש הוא א''ר יוסי בר' חנינא מכאן שהאשה מכרת באורחין יותר מן האיש קדוש הוא מנא ידעה רב ושמואל חד אמר שלא ראתה זבוב עובר על שולחנו וחד אמר סדין של פשתן הציעה על מטתו ולא ראתה קרי עליו י.
** {מלכים ב ד-י}
שונמית מהו קיר
נעשה נא עליית קיר קטנה רב ושמואל חד אמר עלייה פרועה היתה וקירוה וחד אמר אכסדרה גדולה היתה וחלקוה לשנים בשלמא למ''ד אכסדרה היינו דכתיב קיר אלא למ''ד עלייה מאי קיר שקירוה בשלמא למ''ד עלייה היינו דכתיב עליית אלא למ''ד אכסדרה מאי עליית מעולה שבבתים. ונשים לו שם מטה ושולחן וכסא ומנורה י.
** {תהילים לד-טו} {ישעיה ג-יד}
שלום להקדים  וא''ר חלבו אמר רב הונא כל שיודע בחברו שהוא רגיל ליתן לו שלום יקדים לו שלום שנאמר
בקש שלום ורדפהו ואם נתן לו ולא החזיר נקרא גזלן שנאמר
ואתם בערתם הכרם גזלת העני בבתיכם: ו:
** {דברי הימים א א-כז}
שם אברהם
אברם הוא אברהם בתחלה נעשה אב לארם ולבסוף נעשה אב לכל העולם כולו יג.
שם שרה שרי היא שרה בתחלה נעשית שרי לאומתה ולבסוף נעשית שרה לכל העולם כולו: יג.
** {קהלת ד-יז}
שמור רגלך  ואמר רבי שמואל בר נחמני אמר רבי יונתן מ''ד
שמור רגלך כאשר תלך אל בית האלהים שמור עצמך שלא תחטא ואם תחטא הבא קרבן לפני וקרוב לשמוע (דברי חכמים) אמר רבא הוי קרוב לשמוע דברי חכמים שאם חוטאים מביאים קרבן ועושים תשובה מתת הכסילים [זבח] אל תהי ככסילים שחוטאים ומביאים קרבן ואין עושים תשובה כי אינם יודעים לעשות רע אי הכי צדיקים נינהו אלא אל תהי ככסילים שחוטאים ומביאים קרבן ואינם יודעים אם על הטובה הם מביאים אם על הרעה הם מביאים אמר הקב''ה בין טוב לרע אינן מבחינים והם מביאים קרבן לפני  רב אשי ואיתימא רב חנינא בר פפא אמר שמור נקביך בשעה שאתה עומד לפני כג.
** {מלכים ב ג-יא}
שמוש תורה  וא''ר יוחנן משום רבי שמעון בן יוחי גדולה שמושה של תורה יותר מלמודה שנא'
פה אלישע בן שפט אשר יצק מים על ידי אליהו למד לא נאמר אלא יצק מלמד שגדולה שמושה יותר מלמודה:  ז:
שמע גדול מתורה א''ר מני גדול הקורא ק''ש בעונתה יותר מהעוסק בתורה מדקתני הקורא מכאן ואילך לא הפסיד כאדם הקורא בתורה מכלל דקורא בעונתה עדיף:  י:
** {תהילים סח-טו}
שמע דקדוק א''ר חמא ברבי חנינא כל הקורא ק''ש ומדקדק באותיותיה מצננין לו גיהנם שנאמר
בפרש שדי מלכים בה תשלג בצלמון אל תקרי בפרש אלא בפרש אל תקרי בצלמון אלא בצלמות:  טז.
שמע כוונה (הארכה) תניא סומכוס אומר כל המאריך באחד מאריכין לו ימיו ושנותיו אמר רב אחא בר יעקב ובדלי''ת אמר רב אשי ובלבד שלא יחטוף בחי''ת ר' ירמיה הוה יתיב קמיה דר' [חייא בר אבא] חזייה דהוה מאריך טובא א''ל כיון דאמליכתיה למעלה ולמטה ולארבע רוחות השמים תו לא צריכת (אולי משמע שחיוב הוא, שמשמע שבדרך כלל צריכת. אולי רצה לומר שלא צריך כדי לזכות לאריכות ימים. ודע שהיה אפשר לומר שרחב”א לא סובר ככל זה, ואומר שרק צריך כוונה. ויש לדון, שלא יחלוק על סומכוס, שהיה תנא.):  יג:
שמע סדר  אמר ר' יהושע בן קרחה למה קדמה פרשת שמע לוהיה אם שמוע כדי שיקבל עליו עול מלכות שמים תחלה ואחר כך מקבל עליו עול מצות והיה אם שמוע לויאמר שוהיה אם שמוע נוהג בין ביום ובין בלילה ויאמר אינו נוהג אלא ביום בלבד:  יג.
שמע סדר תניא ר''ש בן יוחי אומר בדין הוא שיקדים שמע לוהיה אם שמוע שזה ללמוד וזה ללמד והיה אם שמוע לויאמר שזה ללמוד וזה לעשות אטו שמע ללמוד אית ביה ללמד ולעשות לית ביה והא כתיב ושננתם וקשרתם וכתבתם ותו והיה אם שמוע ללמד הוא דאית ביה ולעשות לית ביה והא כתיב וקשרתם וכתבתם אלא הכי קאמר בדין הוא שתקדם שמע לוהיה אם שמוע שזה ללמוד וללמד ולעשות והיה אם שמוע לויאמר שזה יש בה ללמד ולעשות ויאמר אין בה אלא לעשות בלבד ותיפוק ליה מדרבי יהושע בן קרחה חדא ועוד קאמר חדא כדי שיקבל עליו עול מלכות שמים תחלה ואח''כ יקבל עליו עול מצות ועוד משום דאית בה הני מילי אחרנייתא. יד:
** {תהילים קמט-ו} {תהילים קמט-ה} {איוב ה-ז} {משלי כג-ה} {דברים לב-כד}
שמע שעל המטה   א''ר יצחק כל הקורא ק''ש על מטתו כאלו אוחז חרב של שתי פיות בידו שנאמר
רוממות אל בגרונם וחרב פיפיות בידם מאי משמע אמר מר זוטרא ואיתימא רב אשי מרישא דענינא דכתיב
יעלזו חסידים בכבוד ירננו על משכבותם וכתיב בתריה רוממות אל בגרונם וחרב פיפיות בידם. ואמר רבי יצחק כל הקורא קריאת שמע על מטתו מזיקין בדילין הימנו שנאמר
ובני רשף יגביהו עוף ואין עוף אלא תורה שנאמר
התעיף עיניך בו ואיננו ואין רשף אלא מזיקין שנאמר
מזי רעב ולחומי רשף וקטב מרירי. ה.
שמע שעל המטה ואל תשבו על מטת ארמית. איכא דאמרי לא תגנו בלא ק''ש ח:
** {תהילים סג-ה} {תהילים סג-ו} {תהילים סג-ו}
שמע תפלה א''ר אלעזר מאי דכתיב
כן אברכך בחיי בשמך אשא כפי כן אברכך בחיי זו ק''ש בשמך אשא כפי זו תפלה ואם עושה כן עליו הכתוב אומר
כמו חלב ודשן תשבע נפשי ולא עוד אלא שנוחל שני עולמים העוה''ז והעולם הבא שנאמר
ושפתי רננות יהלל פי: טז:
** {תהילים ג-א} {תהילים נז-א} {תהילים קיא-ח}
תהילים  א''ל ההוא צדוקי לר' אבהו כתיב
מזמור לדוד בברחו מפני אבשלום בנו וכתיב
לדוד מכתם בברחו מפני שאול במערה הי מעשה הוה ברישא מכדי מעשה שאול הוה ברישא לכתוב ברישא אמר ליה אתון דלא דרשיתון סמוכין קשיא לכו אנן דדרשינן סמוכים לא קשיא לן דא''ר יוחנן סמוכין מן התורה מנין שנא'
סמוכים לעד לעולם עשוים באמת וישר למה נסמכה פרשת אבשלום לפרשת גוג ומגוג שאם יאמר לך אדם כלום יש עבד שמורד ברבו אף אתה אמור לו כלום יש בן שמורד באביו אלא הוה הכא נמי הוה: י.
** {תהילים קד-לה} {תהילים א-א} {תהילים ב-יב}
תהילים אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' יהודה בריה דרבי שמעון בן פזי ק''ג פרשיות אמר דוד ולא אמר הללויה עד שראה במפלתן של רשעים שנאמר
יתמו חטאים מן הארץ ורשעים עוד אינם ברכי נפשי את ה' הללויה. הני ק''ג ק''ד הויין אלא שמע מינה אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' שמואל בר נחמני אמר רבי יוחנן כל פרשה שהיתה חביבה על דוד פתח בה באשרי וסיים בה באשרי פתח באשרי דכתיב
אשרי האיש וסיים באשרי דכתיב
אשרי כל חוסי בו:  ט:
** {משלי לא-כו} {תהילים קג-א} {תהילים קג-כ} {תהילים קג-ב} {תהילים קד-לה} {תהילים קד-א} {תהילים קד-כט}
תהילים ברכי נפשי אמר ר' יוחנן משום רבי שמעון בן יוחי מאי דכתיב
פיה פתחה בחכמה ותורת חסד על לשונה כנגד מי אמר שלמה מקרא זה לא אמרו אלא כנגד דוד אביו שדר בחמשה עולמים ואמר שירה דר במעי אמו ואמר שירה שנאמר
ברכי נפשי את ה' וכל קרבי את שם קדשו יצא לאויר העולם ונסתכל בכוכבים ומזלות ואמר שירה שנאמר
ברכו ה' מלאכיו גבורי כח עושי דברו לשמוע בקול דברו ברכו ה' כל צבאיו וגו' ינק משדי אמו ונסתכל בדדיה ואמר שירה שנאמר
ברכי נפשי את ה' ואל תשכחי כל גמוליו מאי כל גמוליו אמר ר' אבהו שעשה לה דדים במקום בינה טעמא מאי אמר (רבי) יהודה כדי שלא יסתכל במקום ערוה רב מתנא אמר כדי שלא יינק ממקום הטנופת ראה במפלתן של רשעים ואמר שירה שנאמר
יתמו חטאים מן הארץ ורשעים עוד אינם ברכי נפשי את ה' הללויה נסתכל ביום המיתה ואמר שירה שנאמר
ברכי נפשי את ה' ה' אלהי גדלת מאד הוד והדר לבשת מאי משמע דעל יום המיתה נאמר אמר רבה בר רב שילא מסיפא דעניינא דכתיב
תסתיר פניך יבהלון תוסף רוחם יגועון וגו' הני חמשה ברכי נפשי כנגד מי אמרן דוד לא אמרן אלא כנגד הקב''ה וכנגד נשמה מה הקב''ה מלא כל העולם אף נשמה מלאה את כל הגוף מה הקדוש ברוך הוא רואה ואינו נראה אף נשמה רואה ואינה נראית מה הקב''ה זן את כל העולם כלו אף נשמה זנה את כל הגוף מה הקב''ה טהור אף נשמה טהורה מה הקב''ה יושב בחדרי חדרים אף נשמה יושבת בחדרי חדרים יבא מי שיש בו חמשה דברים הללו וישבח למי שיש בו חמשה דברים הללו:
** {תהילים קמה-א} {תהילים קיט-א} {תהילים קמה-טז} {תהילים קלו-כה}
תהלה לדוד  אמר רבי אלעזר א''ר אבינא כל האומר
תהלה לדוד בכל יום שלש פעמים מובטח לו שהוא בן העולם הבא מאי טעמא אילימא משום דאתיא באל''ף בי''ת נימא
אשרי תמימי דרך דאתיא בתמניא אפין אלא משום דאית ביה
פותח את ידך נימא הלל הגדול דכתיב ביה
נותן לחם לכל בשר אלא משום דאית ביה תרתי  ד:
** {עמוס ה-ב} {תהילים קמה-יד}
תהלה לדוד אמר רבי יוחנן מפני מה לא נאמר נו''ן באשרי מפני שיש בה מפלתן של שונאי ישראל דכתיב
נפלה לא תוסיף קום בתולת ישראל במערבא מתרצי לה הכי נפלה ולא תוסיף לנפול עוד קום בתולת ישראל אמר רב נחמן בר יצחק אפילו הכי חזר דוד וסמכן ברוח הקדש שנא'
סומך ה' לכל הנופלים:  ד:
תורה ה’ אמר רבי זירא ואיתימא רבי חנינא בר פפא בא וראה שלא כמדת הקב''ה מדת בשר ודם מדת בשר ודם אדם מוכר חפץ לחבירו מוכר עצב ולוקח שמח אבל הקב''ה אינו כן נתן להם תורה לישראל ושמח שנא' כי לקח טוב נתתי לכם תורתי אל תעזובו. ה.
** {במדבר כד-ו}
תורה ואמר רבי חמא ברבי חנינא למה נסמכו אהלים לנחלים דכתיב
כנחלים נטיו כגנות עלי נהר כאהלים נטע וגו' לומר לך מה נחלים מעלין את האדם מטומאה לטהרה אף אהלים מעלין את האדם מכף חובה לכף זכות:  טז.
** {תהילים לט-ג} {משלי ד-ב}
תורה ויסורים   אלא כל שאפשר לו לעסוק בתורה ואינו עוסק הקב''ה מביא עליו יסורין מכוערין ועוכרין אותו שנא'
נאלמתי דומיה החשיתי מטוב וכאבי נעכר ואין טוב אלא תורה שנאמר
כי לקח טוב נתתי לכם תורתי אל תעזובו.  ה.
** {שמות טו-כו}
תורה יסורים אמר רבי שמעון בן לקיש כל העוסק בתורה יסורין בדילין הימנו שנאמר ובני רשף יגביהו עוף ואין עוף אלא תורה שנאמר התעיף עיניך בו ואיננו ואין רשף אלא יסורין שנאמר מזי רעב ולחומי רשף אמר ליה רבי יוחנן הא אפילו תינוקות של בית רבן יודעין אותו שנאמר
ויאמר אם שמוע תשמע לקול ה' אלהיך והישר בעיניו תעשה והאזנת למצותיו ושמרת כל חקיו כל המחלה אשר שמתי במצרים לא אשים עליך כי אני ה' רופאך ה.
תורה לן משביעתו א''ל רב אחא בריה דרבי חייא בר אבא הכי א''ר חייא א''ר יוחנן כל המשביע עצמו מדברי תורה ולן אין מבשרין אותו בשורות רעות שנאמר ושבע ילין בל יפקד רע: יד.
** {שמות כד-יב}
תורה של סיני  וא''ר לוי בר חמא אמר ר' שמעון בן לקיש מאי דכתיב
ואתנה לך את לוחות האבן והתורה והמצוה אשר כתבתי להורותם לוחות אלו עשרת הדברות תורה זה מקרא והמצוה זו משנה אשר כתבתי אלו נביאים וכתובים להורותם זה גמרא מלמד שכולם נתנו למשה מסיני: ה.
** {משלי ח-לה}
תורה תפלה לו ר' נתן אומר לעת מצא זו תורה שנאמר
כי מוצאי מצא חיים וגו' ח.
** {משלי ל-טו}
תחיית המתים  וא''ר טבי א''ר יאשיה מאי דכתיב
שלש הנה לא תשבענה שאול ועוצר רחם וכי מה ענין שאול אצל רחם אלא לומר לך מה רחם מכניס ומוציא אף שאול מכניס ומוציא והלא דברים ק''ו ומה רחם שמכניסין בו בחשאי מוציאין ממנו בקולי קולות שאול שמכניסין בו בקולי קולות אינו דין שמוציאין ממנו בקולי קולות מכאן תשובה לאומרים אין תחיית המתים מן התורה: טו:
** {בראשית כט-לה}
תחילה להודות לה’  ואמר ר''י משום ר''ש בן יוחי מיום שברא הקב''ה את עולמו לא היה אדם שהודה להקב''ה עד שבאתה לאה והודתו שנאמר
הפעם אודה את ה': ז:
** {בראשית טו-ח}
תחילה לקרוא לה’ אדון א''ר יוחנן משום ר''ש בן יוחי מיום שברא הקב''ה את העולם לא היה אדם שקראו להקב''ה אדון עד שבא אברהם וקראו אדון שנאמר
ויאמר אדני (אלהים) במה אדע כי אירשנה. ז:
** {תהילים קכה-ה}
תלמיד חכם כבודו  אמר רבי יהושע בן לוי כל המספר אחר מטתן של תלמידי חכמים נופל בגיהנם שנא'
והמטים עקלקלותם יוליכם ה' את פועלי האון שלום על ישראל אפילו בשעה ששלום על ישראל יוליכם ה' את פועלי האון יט.
תלמיד חכם מארח  עובר עלינו תמיד א''ר יוסי בר' חנינא משום רבי אליעזר בן יעקב כל המארח תלמיד חכם בתוך ביתו ומהנהו מנכסיו מעלה עליו הכתוב כאילו מקריב תמידין.  י.
תלמיד חכם תשובה תנא דבי ר' ישמעאל אם ראית תלמיד חכם שעבר עבירה בלילה אל תהרהר אחריו ביום שמא עשה תשובה שמא סלקא דעתך אלא ודאי עשה תשובה והני מילי בדברים שבגופו אבל בממונא עד דמהדר למריה:
תענית אגרא אמר מר זוטרא אגרא דתעניתא צדקתא ו:
תענית רב ששת כי הוה יתיב בתעניתא בתר דמצלי אמר הכי רבון העולמים גלוי לפניך בזמן שבית המקדש קיים אדם חוטא ומקריב קרבן ואין מקריבין ממנו אלא חלבו ודמו ומתכפר לו ועכשיו ישבתי בתענית ונתמעט חלבי ודמי יהי רצון מלפניך שיהא חלבי ודמי שנתמעט כאילו הקרבתיו לפניך על גבי המזבח ותרצני. יז.
** {תהילים סט-יד} {ישעיה מט-ח} {איוב לו-ה} {תהילים נה-יט}
תפלה ברבים זמן רבים א''ל רבי יצחק לרב נחמן מ''ט לא אתי מר לבי כנישתא לצלויי אמר ליה לא יכילנא א''ל לכנפי למר עשרה וליצלי אמר ליה טריחא לי מלתא ולימא ליה מר לשלוחא דצבורא בעידנא דמצלי צבורא ליתי ולודעיה למר א''ל מאי כולי האי א''ל דאמר ר' יוחנן משום ר''ש בן יוחי מאי דכתיב
ואני תפלתי לך ה' עת רצון אימתי עת רצון בשעה שהצבור מתפללין. ר' יוסי ברבי חנינא אמר מהכא
כה אמר ה' בעת רצון עניתיך ר' אחא ברבי חנינא אמר מהכא
הן אל כביר ולא ימאס וכתיב
פדה בשלום נפשי מקרב לי כי ברבים היו עמדי תניא נמי הכי רבי נתן אומר מנין שאין הקב''ה מואס בתפלתן של רבים שנאמר הן אל כביר ולא ימאס וכתיב פדה בשלום נפשי מקרב לי וגו' אמר הקב''ה כל העוסק בתורה ובגמילות חסדים ומתפלל עם הצבור מעלה אני עליו כאילו פדאני לי ולבני מבין אומות העולם ז:
תפלה גאולה לתפלה העיד ר''י בן אליקים משום קהלא קדישא דבירושלים כל הסומך גאולה לתפלה אינו נזוק כל היום כולו א''ר זירא איני והא אנא סמכי ואיתזקי א''ל במאי איתזקת דאמטיית אסא לבי מלכא התם נמי מבעי לך למיהב אגרא למחזי אפי מלכא דא''ר יוחנן לעולם ישתדל אדם לרוץ לקראת מלכי ישראל ולא לקראת מלכי ישראל בלבד אלא אפילו לקראת מלכי עכו''ם שאם יזכה יבחין בין מלכי ישראל למלכי עכו''ם. אמר ליה רבי אלעא לעולא כי עיילת להתם שאיל בשלמא דרב ברונא אחי במעמד כל החבורה דאדם גדול הוא ושמח במצות זימנא חדא סמך גאולה לתפלה ולא פסיק חוכא מפומיה כוליה יומא. היכי מצי סמיך והא א''ר יוחנן בתחלה הוא אומר ה' שפתי תפתח ולבסוף הוא אומר יהיו לרצון אמרי פי וגו' אמר ר' אלעזר תהא בתפלה של ערבית. והא אמר ר' יוחנן איזהו בן העוה''ב זהו הסומך גאולה של ערבית לתפלה של ערבית אלא א''ר אלעזר תהא בתפלת המנחה רב אשי אמר אפי' תימא אכולהו וכיון דקבעוה רבנן בתפלה כתפלה אריכתא דמיא דאי לא תימא הכי ערבית היכי מצי סמיך והא בעי למימר השכיבנו אלא כיון דתקינו רבנן השכיבנו כגאולה אריכתא דמיא ה''נ כיון דקבעוה רבנן בתפלה כתפלה אריכתא דמיא.  ט:
תפלה הוספות ר' אלעזר בתר דמסיים צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שתשכן בפורינו אהבה ואחוה ושלום וריעות ותרבה גבולנו בתלמידים ותצליח סופנו אחרית ותקוה ותשים חלקנו בגן עדן ותקננו בחבר טוב ויצר טוב בעולמך ונשכים ונמצא יחול לבבנו ליראה את שמך ותבא לפניך קורת נפשנו לטובה. רבי יוחנן בתר דמסיים צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שתציץ בבשתנו ותביט ברעתנו ותתלבש ברחמיך ותתכסה בעזך ותתעטף בחסידותך ותתאזר בחנינותך ותבא לפניך מדת טובך וענותנותך. ר' זירא בתר דמסיים צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שלא נחטא ולא נבוש ולא נכלם מאבותינו ר' חייא בתר דמצלי אמר הכי יהי רצון מלפניך ה' אלהינו שתהא תורתך אומנותנו ואל ידוה לבנו ואל יחשכו עינינו. רב בתר צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שתתן לנו חיים ארוכים חיים של שלום חיים של טובה חיים של ברכה חיים של פרנסה חיים של חלוץ עצמות חיים שיש בהם יראת חטא חיים שאין בהם בושה וכלימה חיים של עושר וכבוד חיים שתהא בנו אהבת תורה ויראת שמים חיים שתמלא לנו את כל משאלות לבנו לטובה. רבי בתר צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו ואלהי אבותינו שתצילנו מעזי פנים ומעזות פנים מאדם רע ומפגע רע מיצר רע מחבר רע משכן רע ומשטן המשחית ומדין קשה ומבעל דין קשה בין שהוא בן ברית בין שאינו בן ברית ואע''ג דקיימי קצוצי עליה דרבי. רב ספרא בתר צלותיה אמר הכי יהי רצון מלפניך ה' אלהינו שתשים שלום
** {מלכים א יח-לו} {תהילים קמא-ב} {תהילים ה-ד}
תפלה זהירות בתפלות מיוחדות ואמר רבי חלבו אמר רב הונא לעולם יהא אדם זהיר בתפלת המנחה שהרי אליהו לא נענה אלא בתפלת המנחה שנאמר
ויהי בעלות המנחה ויגש אליהו הנביא ויאמר וגו' ענני ה' ענני ענני שתרד אש מן השמים וענני שלא יאמרו מעשה כשפים הם ר' יוחנן אמר אף בתפלת ערבית שנאמר
תכון תפלתי קטרת לפניך משאת כפי מנחת ערב רב נחמן בר יצחק אמר אף תפלת שחרית שנאמר
ה' בקר תשמע קולי בקר אערך לך ואצפה:  ו:
** {שמואל א יב-כג} {שמואל א כב-ח} {תהילים לה-יג}
תפלה לחבר ואמר רבה בר חיננא סבא משמיה דרב כל שאפשר לו לבקש רחמים על חבירו ואינו מבקש נקרא חוטא שנאמר
גם אנכי חלילה לי מחטא לה' מחדול להתפלל בעדכם אמר רבא אם ת''ח הוא צריך שיחלה עצמו עליו מ''ט אילימא משום דכתיב
ואין חולה מכם עלי (ואין) [ו] גולה את אזני דילמא מלך שאני אלא מהכא
ואני בחלותם לבושי וגו': יב:
** {ישעיה לח-ב}
תפלה מקום האמר רב יהודה אמר רב ואיתימא ריב''ל מנין למתפלל שלא יהא דבר חוצץ בינו לבין הקיר שנאמר
ויסב חזקיהו פניו אל הקיר ויתפלל ו.
** {תהילים קל-א} {תהילים קב-א}
תפלה מקום וא''ר יוסי בר' חנינא משום ראב''י אל יעמוד אדם במקום גבוה ויתפלל אלא במקום נמוך ויתפלל שנא'
ממעמקים קראתיך ה' תניא נמי הכי לא יעמוד אדם לא על גבי כסא ולא ע''ג שרפרף ולא במקום גבוה ויתפלל אלא במקום נמוך ויתפלל לפי שאין גבהות לפני המקום שנאמר ממעמקים קראתיך ה' וכתיב
תפלה לעני כי יעטוף.  י.
תפלה מתעטש הא מילתא אבלעא לי בי רב המנונא ותקילא לי כי כולי תלמודאי המתעטש בתפלתו סימן יפה לו כשם שעושים לו נחת רוח מלמטה כך עושין לו נחת רוח מלמעלה כד:
** {בראשית יט-כז} {תהילים קו-ל}
תפלה קובע מקום א''ר חלבו אמר רב הונא כל הקובע מקום לתפלתו אלהי אברהם בעזרו וכשמת אומרים לו אי עניו אי חסיד מתלמידיו של אברהם אבינו ואברהם אבינו מנא לן דקבע מקום דכתיב
וישכם אברהם בבקר אל המקום אשר עמד שם ואין עמידה אלא תפלה שנאמר
ויעמוד פינחס ויפלל:  ו:
** {שמואל ב ז-י}
תפלה קובע מקום וא''ר יוחנן משום רבי שמעון בן יוחי כל הקובע מקום לתפלתו אויביו נופלים תחתיו שנאמר
ושמתי מקום לעמי לישראל ונטעתיו ושכן תחתיו ולא ירגז עוד ולא יוסיפו בני עולה לענותו כאשר בראשונה  ז:
** {שמות לב-יג} {תהילים קו-כג} {מלכים ב יט-לד} {ישעיה לח-יז}
תפלה תולה בזכות א''ר יוחנן משום ר' יוסי בן זמרא כל התולה בזכות עצמו תולין לו בזכות אחרים וכל התולה בזכות אחרים תולין לו בזכות עצמו משה תלה בזכות אחרים שנא'
זכור לאברהם ליצחק ולישראל עבדיך תלו לו בזכות עצמו שנאמר
ויאמר להשמידם לולי משה בחירו עמד בפרץ לפניו להשיב חמתו מהשחית חזקיהו תלה בזכות עצמו דכתיב זכר נא את אשר התהלכתי לפניך תלו לו בזכות אחרים שנא'
וגנותי אל העיר הזאת להושיעה למעני ולמען דוד עבדי והיינו דריב''ל דאמר ריב''ל מאי דכתיב
הנה לשלום מר לי מר אפי' בשעה ששיגר לו הקב''ה שלום מר הוא לו:  י.
** {יחזקאל טז-סג} {שמואל א כח-טו} {שמואל א כח-יט} {שמואל ב כא-ו}
תשובה ביוש ואמר רבה בר חיננא סבא משמיה דרב כל העושה דבר עבירה ומתבייש בו מוחלין לו על כל עונותיו שנאמר
למען תזכרי ובשת ולא יהיה לך עוד פתחון פה מפני כלמתך בכפרי לך לכל אשר עשית נאם ה' אלהים דילמא צבור שאני אלא מהכא
ויאמר שמואל אל שאול למה הרגזתני להעלות אותי ויאמר שאול צר לי מאד ופלשתים נלחמים בי וה' סר מעלי ולא ענני עוד גם ביד הנביאים גם בחלומות ואקראה לך להודיעני מה אעשה ואילו אורים ותומים לא קאמר משום דקטליה לנוב עיר הכהנים ומנין דאחילו ליה מן שמיא שנא'
(ויאמר שמואל אל שאול) [ו] מחר אתה ובניך עמי וא''ר יוחנן עמי במחיצתי ורבנן אמרי מהכא
והוקענום לה' בגבעת שאול בחיר ה' יצתה בת קול ואמרה בחיר ה'  יב:
