בית הכסא לענין טפח וטפחיים דתני חדא כשהוא נפנה מגלה לאחריו טפח ולפניו טפחיים ותניא אידך לאחריו טפח ולפניו ולא כלום מאי לאו אידי ואידי באיש ולא קשיא כאן לגדולים כאן לקטנים ותסברא אי בקטנים לאחריו טפח למה לי אלא אידי ואידי בגדולים ולא קשיא הא באיש הא באשה אי הכי הא דקתני עלה זהו ק''ו שאין עליו תשובה מאי אין עליו תשובה דרכא דמילתא הכי איתא כג.
ט’ אב מלאכה מקום שנהגו לעשות מלאכה בתשעה באב עושין מקום שנהגו שלא לעשות אין עושין וכל מקום תלמידי חכמים בטלים רבן שמעון בן גמליאל אומר לעולם יעשה כל אדם את עצמו כתלמיד חכם קשיא דרבנן אדרבנן קשיא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל אמר רבי יוחנן מוחלפת השיטה רב שישא בריה דרב אידי אמר לעולם לא תחליף דרבנן אדרבנן לא קשיא ק''ש כיון דכ''ע קא קרו ואיהו נמי קרי לא מיחזי כיוהרא הכא כיון דכולי עלמא עבדי מלאכה ואיהו לא קא עביד מיחזי כיוהרא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל לא קשיא התם בכונה תליא מילתא ואנן סהדי דלא מצי לכווני דעתיה אבל הכא הרואה אומר מלאכה הוא דאין לו פוק חזי כמה בטלני איכא בשוקא:  יז:
טומאה תנור עכנאי חתכו חוליות ונתן חול בין חוליא לחוליא ר' אליעזר מטהר וחכמים מטמאים וזהו תנורו של עכנאי יט.
טעימה בעי מיניה אשיאן תנא דבי ר' אמי מר' אמי השרוי בתענית מהו שיטעום אכילה ושתיה קביל עליה והא ליכא או דילמא הנאה קביל עליה והא איכא א''ל טועם ואין בכך כלום תניא נמי הכי מטעמת אינה טעונה ברכה והשרוי בתענית טועם ואין בכך כלום עד כמה ר' אמי ור' אסי טעמי עד שיעור רביעתא:  יד.
יוהרא חתן אם רוצה לקרות וכו': למימרא דרבן שמעון בן גמליאל חייש ליוהרא ורבנן לא חיישי ליוהרא והא איפכא שמעינן להו דתנן מקום שנהגו לעשות מלאכה בתשעה באב עושין מקום שנהגו שלא לעשות אין עושין וכל מקום תלמידי חכמים בטלים רבן שמעון בן גמליאל אומר לעולם יעשה כל אדם את עצמו כתלמיד חכם קשיא דרבנן אדרבנן קשיא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל אמר רבי יוחנן מוחלפת השיטה רב שישא בריה דרב אידי אמר לעולם לא תחליף דרבנן אדרבנן לא קשיא ק''ש כיון דכ''ע קא קרו ואיהו נמי קרי לא מיחזי כיוהרא הכא כיון דכולי עלמא עבדי מלאכה ואיהו לא קא עביד מיחזי כיוהרא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל לא קשיא התם בכונה תליא מילתא ואנן סהדי דלא מצי לכווני דעתיה אבל הכא הרואה אומר מלאכה הוא דאין לו פוק חזי כמה בטלני איכא בשוקא:  יז:
יוהרא חתן אם רוצה לקרות קרית שמע לילה הראשון קורא רבן שמעון בן גמליאל אומר לא כל הרוצה ליטול את השם יטול:  טז:
כלל פסק יחיד ורבים הלכה כרבים (נגד רבן גמליאל) ט.
לשון כל התורה  למימרא דסבר רבי דכל התורה כולה בכל לשון נאמרה דאי סלקא דעתך בלשון הקודש נאמרה והיו דכתב רחמנא למה לי איצטריך משום דכתיב שמע למימרא דסברי רבנן דכל התורה כולה בלשון הקודש נאמרה דאי סלקא דעתך בכל לשון נאמרה שמע דכתב רחמנא למה לי איצטריך משום דכתיב והיו: יג.
** מאוס- צריך לעיין בכל גמ’ שהבאנו גבי שמע ותפלה.
מגילה הפסק בעא מיניה אחי תנא דבי רבי חייא מרבי חייא בהלל ובמגילה מהו שיפסיק אמרינן ק''ו ק''ש דאורייתא פוסק הלל דרבנן מבעיא או דלמא פרסומי ניסא עדיף א''ל פוסק ואין בכך כלום יד.
** מתני' גמ'
מזוזה
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן:
מתפלל בדרך באותה שעה למדתי ממנו שלשה דברים למדתי שאין נכנסין לחורבה ולמדתי שמתפללין בדרך ולמדתי שהמתפלל בדרך מתפלל תפלה קצרה ג.
נטילת ידים א''ל רבינא לרבא חזי מר האי צורבא מרבנן דאתא ממערבא ואמר מי שאין לו מים לרחוץ ידיו מקנח ידיו בעפר ובצרור ובקסמית א''ל שפיר קאמר מי כתיב ארחץ במים בנקיון כתיב כל מידי דמנקי דהא רב חסדא לייט אמאן דמהדר אמיא בעידן צלותא והני מילי לק''ש אבל לתפלה מהדר ועד כמה עד פרסה והנ''מ לקמיה אבל לאחוריה אפילו מיל אינו חוזר [ומינה] מיל הוא דאינו חוזר הא פחות ממיל חוזר:  טו.
** {תהילים כו-ו}
נטילת ידים ואמר רבי יוחנן הרוצה שיקבל עליו עול מלכות שמים שלמה יפנה ויטול ידיו ויניח תפילין ויקרא ק''ש ויתפלל וזו היא מלכות שמים שלמה א''ר חייא בר אבא א''ר יוחנן כל הנפנה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל מעלה עליו הכתוב כאלו בנה מזבח והקריב עליו קרבן דכתיב
ארחץ בנקיון כפי ואסובבה את מזבחך ה' א''ל רבא לא סבר לה מר כאילו טבל דכתיב ארחץ [בנקיון] ולא כתב ארחיץ [כפי]  טו.
נידוי כל המתנדה ומת בנדויו ב''ד סוקלין את ארונו יט.
** {תהילים כו-ו}
נפנה נטילת ידים וכו’ ואמר רבי יוחנן הרוצה שיקבל עליו עול מלכות שמים שלמה יפנה ויטול ידיו ויניח תפילין ויקרא ק''ש ויתפלל וזו היא מלכות שמים שלמה א''ר חייא בר אבא א''ר יוחנן כל הנפנה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל מעלה עליו הכתוב כאלו בנה מזבח והקריב עליו קרבן דכתיב
ארחץ בנקיון כפי ואסובבה את מזבחך ה' א''ל רבא לא סבר לה מר כאילו טבל דכתיב ארחץ [בנקיון] ולא כתב ארחיץ [כפי]  טו.
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
נשים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
נשים ברכת המזון א''ל רבינא לרבא נשים בברכת המזון דאורייתא או דרבנן למאי נפקא מינה לאפוקי רבים ידי חובתן אי אמרת (בשלמא) דאורייתא אתי דאורייתא ומפיק דאורייתא (אלא אי) אמרת דרבנן הוי שאינו מחוייב בדבר וכל שאינו מחוייב בדבר אינו מוציא את הרבים ידי חובתן מאי ת''ש באמת אמרו בן מברך לאביו ועבד מברך לרבו ואשה מברכת לבעלה אבל אמרו חכמים תבא מארה לאדם שאשתו ובניו מברכין לו אי אמרת בשלמא דאורייתא אתי דאורייתא ומפיק דאורייתא אלא אי אמרת דרבנן אתי דרבנן ומפיק דאורייתא ולטעמיך קטן בר חיובא הוא אלא הכי במאי עסקינן כגון שאכל שיעורא דרבנן דאתי דרבנן ומפיק דרבנן: כ:
** {שמות כ-ח} {דברים ה-יב}
נשים קידוש מר רב אדא בר אהבה נשים חייבות בקדוש היום דבר תורה אמאי מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות אמר אביי מדרבנן א''ל רבא והא דבר תורה קאמר ועוד כל מצות עשה נחייבינהו מדרבנן אלא אמר רבא אמר קרא
זכור
ושמור כל שישנו בשמירה ישנו בזכירה והני נשי הואיל ואיתנהו בשמירה איתנהו בזכירה כ:
סוטה אין משקין לא את הגיורת ולא את המשוחררת וחכמים אומרים משקין ואמרו לו מעשה בכרכמית שפחה משוחררת בירושלים והשקוה שמעיה ואבטליון ואמר להם דוגמא השקוה יט.
** {במדבר ה-כג}
סוטה מה מוחק גבי סוטה אלות כותב צואות אינו כותב והתם הוא דכתיב
וכתב את האלות האלה טו:
סוכה דתנן מי שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ב''ש פוסלין וב''ה מכשירין אמרו להם ב''ה לב''ש מעשה שהלכו זקני ב''ש וזקני ב''ה לבקר את ר' יוחנן בן החורנית מצאוהו שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ולא אמרו לו כלום אמרו להם משם ראיה אף הם אמרו לו א''כ היית נוהג לא קיימת מצות סוכה מימיך יא.
ספר תורה ולא ישתין בהן מים ולא יישן בהן לא שינת קבע ולא שינת עראי. כג.
ספר תורה כבוד רב אחאי איעסק ליה לבריה בי רב יצחק בר שמואל בר מרתא עייליה לחופה ולא הוה מסתייעא מילתא אזל בתריה לעיוני חזא ספר תורה דמנחא אמר להו איכו השתא לא אתאי סכנתון לברי דתניא בית שיש בו ספר תורה או תפילין אסור לשמש בו את המטה עד שיוציאם או שיניחם כלי בתוך כלי אמר אביי לא שנו אלא בכלי שאינו כליין אבל בכלי שהוא כליין אפילו עשרה מאני כחד מאנא דמי אמר רבא גלימא אקמטרא ככלי בתוך כלי דמי. אמר רבי יהושע בן לוי ס''ת צריך לעשות לו מחיצה עשרה מר זוטרא איקלע לבי רב אשי חזייה לדוכתיה דמר בר רב אשי דמנח ביה ספר תורה ועביד ליה מחיצה עשרה אמר ליה כמאן כרבי יהושע בן לוי אימר דאמר רבי יהושע בן לוי דלית ליה ביתא אחרינא מר הא אית ליה ביתא אחרינא אמר ליה לאו אדעתאי: כה:
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
עבדים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
עבדים ת''ר עבדים ושפחות אין עומדין עליהם בשורה ואין אומרים עליהם ברכת אבלים ותנחומי אבלים מעשה ומתה שפחתו של רבי אליעזר נכנסו תלמידיו לנחמו כיון שראה אותם עלה לעלייה ועלו אחריו נכנס לאנפילון נכנסו אחריו נכנס לטרקלין נכנסו אחריו אמר להם כמדומה אני שאתם נכוים בפושרים עכשיו אי אתם נכוים אפילו בחמי חמין לא כך שניתי לכם עבדים ושפחות אין עומדין עליהם בשורה ואין אומרים עליהם ברכת אבלים ולא תנחומי אבלים אלא מה אומרים עליהם כשם שאומרים לו לאדם על שורו ועל חמורו שמתו המקום ימלא לך חסרונך כך אומרים לו על עבדו ועל שפחתו המקום ימלא לך חסרונך תניא אידך עבדים ושפחות אין מספידין אותן ר' יוסי אומר אם עבד כשר הוא אומרים עליו הוי איש טוב ונאמן ונהנה מיגיעו אמרו לו אם כן מה הנחת לכשרים: טז:
עבדים תנחומים וכשמת טבי עבדו קבל עליו תנחומין אמרו לו תלמידיו למדתנו רבינו שאין מקבלין תנחומין על העבדים אמר להם אין טבי עבדי כשאר כל העבדים כשר היה טז:
** {יחזקאל כד-יז}
עוסק במצוה בשבתך בביתך פרט לעוסק במצוה ובלכתך בדרך פרט לחתן מכאן אמרו הכונס את הבתולה פטור ואת האלמנה חייב מאי משמע אמר רב פפא כי דרך מה דרך רשות אף כל רשות מי לא עסקינן דקא אזיל לדבר מצוה ואפילו הכי אמר רחמנא לקרי אם כן לכתוב רחמנא בשבת ובלכת מאי בשבתך ובלכתך בשבת דידך ובלכת דידך הוא דמחייבת הא דמצוה פטירת אי הכי אפילו כונס את האלמנה נמי האי טריד והאי לא טריד אי משום טרדא אפילו טבעה ספינתו בים נמי וכי תימא ה''נ אלמה א''ר אבא בר זבדא אמר רב אבל חייב בכל המצות האמורות בתורה חוץ מן התפילין שהרי נאמר בהם פאר שנאמר
פארך חבוש עליך התם טריד טרדא דמצוה הכא טריד טרדא דרשות וב''ש ההוא מבעי להו פרט לשלוחי מצוה יא.
עוסק במצוה החופר כוך למת בקבר פטור מק''ש ומן התפלה ומן התפילין ומכל מצות האמורות בתורה הגיע זמן ק''ש עולה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל  יד:
עוסק במצוה נושאי המטה וחלופיהן וחלופי חלופיהן את שלפני המטה ואת שלאחר המטה את שלפני המטה צורך בהם פטורים ואת שלאחר המטה צורך בהם חייבין ואלו ואלו פטורים מן התפלה קברו את המת וחזרו אם יכולין להתחיל ולגמור עד שלא יגיעו לשורה יתחילו ואם לאו לא יתחילו העומדים בשורה הפנימיים פטורים והחיצונים חייבים יז:
עוסק במצווה חתן פטור מק''ש לילה הראשונה ועד מוצאי שבת אם לא עשה מעשה ומעשה בר''ג שנשא אשה וקרא לילה הראשונה אמרו לו תלמידיו למדתנו רבינו שחתן פטור מק''ש אמר להם איני שומע לכם לבטל הימני מלכות שמים אפי' שעה אחת  טו.
עוסק במצווה ת''ר שורה הרואה פנימה פטורה ושאינה רואה פנימה חייבת רבי יהודה אומר הבאים מחמת האבל פטורין מחמת עצמן חייבין: יט:
** {ירמיה כז-כב}
עלייה מבבל רבי אבא הוה קא משתמיט מיניה דרב יהודה דהוה קא בעי למיסק לארעא דישראל דאמר רב יהודה כל העולה מבבל לא''י עובר בעשה שנאמר
בבלה יובאו ושמה יהיו עד יום פקדי אותם נאם ה'  כד:
** {יחזקאל טז-ז}
ערוה (יש לדון אם רק לשמע) בעי מיניה רב יוסף בריה דרב נחוניא מרב יהודה שנים שישנים במטה אחת מהו שזה יחזיר פניו ויקרא ק''ש וזה יחזיר פניו ויקרא ק''ש א''ל הכי אמר שמואל ואפילו אשתו עמו מתקיף לה רב יוסף אשתו ולא מיבעיא אחר אדרבה אשתו כגופו אחר לאו כגופו מיתיבי שנים שישנים במטה אחת זה מחזיר פניו וקורא וזה מחזיר פניו וקורא ותניא אחריתי הישן במטה ובניו ובני ביתו בצדו הרי זה לא יקרא ק''ש אא''כ היתה טלית מפסקת ביניהן ואם היו בניו ובני ביתו קטנים מותר בשלמא לרב יוסף לא קשיא הא באשתו הא באחר אלא לשמואל קשיא אמר לך שמואל לרב יוסף מי ניחא והתניא היה ישן במטה ובניו ובני ביתו במטה לא יקרא ק''ש אא''כ היתה טליתו מפסקת ביניהן אלא מאי אית לך למימר אשתו לרב יוסף תנאי היא לדידי נמי תנאי היא: אמר מר זה מחזיר פניו וקורא ק''ש והא איכא עגבות מסייע ליה לרב הונא דא''ר הונא עגבות אין בהם משום ערוה לימא מסייע ליה לרב הונא האשה יושבת וקוצה לה חלתה ערומה מפני שיכולה לכסות פניה בקרקע אבל לא האיש תרגמה רב נחמן בר יצחק כגון שהיו פניה טוחות בקרקע: אמר מר אם היו בניו ובני ביתו קטנים מותר ועד כמה אמר רב חסדא תינוקת בת שלש שנים ויום אחד ותינוק בן ט' שנים ויום אחד איכא דאמרי תינוקת בת י''א שנה ויום אחד ותינוק בן שתים עשרה שנה ויום אחד אידי ואידי עד כדי
שדים נכונו ושערך צמח א''ל רב כהנא לרב אשי התם אמר רבא אע''ג דתיובתא דשמואל הלכתא כוותיה דשמואל הכא מאי אמר ליה אטו כולהו בחדא מחתא מחתינהו אלא היכא דאיתמר איתמר והיכא דלא איתמר לא איתמר כד.
ערוה עגבות רב הונא עגבות אין בהם משום ערוה  כד.
** {שיר השירים ב-יד}
ערוה קול אמר שמואל קול באשה ערוה שנא'
כי קולך ערב ומראך נאוה כד.
** {ישעיה מז-ב} {ישעיה מז-ג}
ערוה שוק אמר רב חסדא שוק באשה ערוה שנאמר
גלי שוק עברי נהרות וכתיב
תגל ערותך וגם תראה חרפתך  כד.
** {שיר השירים ד-א}
ערוה שער  אמר רב ששת שער באשה ערוה שנא'
שערך כעדר העזים: כד.
ערוה שער א''ל רב מרי לרב פפא שער יוצא בבגדו מהו קרא עליה שער שער: כד.
ערווה טפח א''ר יצחק טפח באשה ערוה למאי אילימא לאסתכולי בה והא א''ר ששת למה מנה הכתוב תכשיטין שבחוץ עם תכשיטין שבפנים לומר לך כל המסתכל באצבע קטנה של אשה כאילו מסתכל במקום התורף אלא באשתו ולק''ש כד.
** {שמות יב-ח} {שמות יב-יב} {שמות יב-יא} {שמות יב-י} {דברים טז-ו} {דברים טז-א} {במדבר לג-ג}
פסח זמן אכילה ואילו אכילת פסחים לא קתני ורמינהי ק''ש ערבית והלל בלילי פסחים ואכילת פסח מצותן עד שיעלה עמוד השחר אמר רב יוסף לא קשיא הא ר' אלעזר בן עזריה הא רבי עקיבא דתניא
ואכלו את הבשר בלילה הזה רבי אלעזר בן עזריה אומר נאמר כאן בלילה הזה ונאמר להלן
ועברתי בארץ מצרים בלילה הזה מה להלן עד חצות אף כאן עד חצות אמר ליה ר' עקיבא והלא כבר נאמר
בחפזון עד שעת חפזון א''כ מה תלמוד לומר בלילה יכול יהא נאכל כקדשים ביום תלמוד לומר בלילה בלילה הוא נאכל ולא ביום בשלמא לר' אלעזר בן עזריה דאית ליה גזירה שוה אצטריך למכתב ליה הזה אלא לר' עקיבא האי הזה מאי עביד ליה למעוטי לילה אחר הוא דאתא סד''א הואיל ופסח קדשים קלים ושלמים קדשים קלים מה שלמים נאכלין לשני ימים ולילה אחד אף פסח נאכל שתי לילות במקום ב' ימים ויהא נאכל לב' לילות ויום אחד קמ''ל בלילה הזה בלילה הזה הוא נאכל ואינו נאכל בלילה אחר ור' אלעזר בן עזריה
מלא תותירו עד בקר נפקא ורבי עקיבא אי מהתם הוה אמינא מאי בקר בקר שני ורבי אלעזר אמר לך כל בקר בקר ראשון הוא. והני תנאי כהני תנאי דתניא
שם תזבח את הפסח בערב כבוא השמש מועד צאתך ממצרים ר' אליעזר אומר בערב אתה זובח וכבוא השמש אתה אוכל ומועד צאתך ממצרים אתה שורף רבי יהושע אומר בערב אתה זובח כבוא השמש אתה אוכל ועד מתי אתה אוכל והולך עד מועד צאתך ממצרים א''ר אבא הכל מודים כשנגאלו ישראל ממצרים לא נגאלו אלא בערב שנאמר
הוציאך ה' אלהיך ממצרים לילה וכשיצאו לא יצאו אלא ביום שנא'
ממחרת הפסח יצאו בני ישראל ביד רמה על מה נחלקו על שעת חפזון ר' אלעזר בן עזריה סבר מאי חפזון חפזון דמצרים ורבי עקיבא סבר מאי חפזון חפזון דישראל תנ''ה הוציאך ה' אלהיך ממצרים לילה וכי בלילה יצאו והלא לא יצאו אלא ביום שנא' ממחרת הפסח יצאו בני ישראל ביד רמה אלא מלמד שהתחילה להם גאולה מבערב:  ט.
פסחים תודוס איש רומי הנהיג את בני רומי להאכילן גדיים מקולסין בלילי פסחים שלח ליה שמעון בן שטח אלמלא תודוס אתה גוזרני עליך נדוי שאתה מאכיל את ישראל קדשים בחוץ  יט.
פרקדן אמר רב יוסף פרקדן לא יקרא קריאת שמע מקרא הוא דלא ליקרי הא מיגנא שפיר דמי והא רבי יהושע בן לוי לייט אמאן דגני אפרקיד אמרי מיגנא כי מצלי שפיר דמי מקרא אע''ג דמצלי נמי אסור והא ר' יוחנן מצלי וקרי שאני ר' יוחנן דבעל בשר הוה:  יג:
** {דברים ו-ד}
קול תנן התם חרש המדבר ואינו שומע לא יתרום ואם תרם תרומתו תרומה מאן תנא חרש המדבר ואינו שומע דיעבד אין לכתחלה לא אמר רב חסדא ר' יוסי היא דתנן הקורא את שמע ולא השמיע לאזנו יצא דברי רבי יהודה ר' יוסי אומר לא יצא עד כאן לא קאמר ר' יוסי לא יצא אלא גבי ק''ש דאורייתא אבל תרומה משום ברכה הוא וברכה דרבנן ולא בברכה תליא מילתא וממאי דר' יוסי היא דילמא ר' יהודה היא ואמר גבי ק''ש נמי דיעבד אין לכתחלה לא תדע דקתני הקורא דיעבד אין לכתחלה לא אמרי האי דקתני הקורא להודיעך כחו דר' יוסי דאמר דיעבד נמי לא דאי ר' יהודה אפי' לכתחלה נמי יצא במאי אוקימתא כר' יוסי ואלא הא דתניא לא יברך אדם בהמ''ז בלבו ואם בירך יצא מני לא ר' יוסי ולא ר' יהודה דאי ר' יהודה הא אמר לכתחלה נמי יצא אי ר' יוסי דיעבד נמי לא אלא מאי ר' יהודה ודיעבד אין לכתחלה לא אלא הא דתני ר' יהודה בריה דרבי שמעון בן פזי חרש המדבר ואינו שומע תורם לכתחלה מני לא ר' יהודה ולא ר' יוסי אי ר' יהודה הא אמר דיעבד אין לכתחלה לא אי ר' יוסי הא אמר דיעבד נמי לא אלא לעולם רבי יהודה ואפי' לכתחלה נמי ולא קשיא הא דידיה הא דרביה דתנן רבי יהודה אומר משום ר' אלעזר בן עזריה הקורא את שמע צריך שישמיע לאזנו שנאמר
שמע ישראל ה' אלהינו ה' אחד אמר ליה רבי מאיר הרי הוא אומר אשר אנכי מצוך היום על לבבך אחר כונת הלב הן הן הדברים השתא דאתית להכי אפילו תימא רבי יהודה כרביה סבירא ליה ולא קשיא הא רבי מאיר הא רבי יהודה. תנן התם הכל כשרים לקרות את המגילה חוץ מחרש שוטה וקטן ורבי יהודה מכשיר בקטן מאן תנא חרש דיעבד נמי לא אמר רב מתנה רבי יוסי היא דתנן הקורא את שמע ולא השמיע לאזנו יצא דברי ר' יהודה רבי יוסי אומר לא יצא ממאי דרבי יוסי היא ודיעבד נמי לא
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
קטנים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
** {שמות כ-ח} {דברים ה-יב}
קידוש מר רב אדא בר אהבה נשים חייבות בקדוש היום דבר תורה אמאי מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות אמר אביי מדרבנן א''ל רבא והא דבר תורה קאמר ועוד כל מצות עשה נחייבינהו מדרבנן אלא אמר רבא אמר קרא
זכור
ושמור כל שישנו בשמירה ישנו בזכירה והני נשי הואיל ואיתנהו בשמירה איתנהו בזכירה כ:
שמע ברכות בעל קרי מהרהר בלבו ואינו מברך לא לפניה ולא לאחריה רבי יהודה אומר מברך לפניהם ולאחריהם  כ:
תורה כתיב על לבבכם לדבר בם ההוא בדברי תורה כתיב וה''ק רחמנא אגמירו בנייכו תורה כי היכי דליגרסו בהו: יג:
** {יחזקאל כ-כה} {ישעיה ה-יח} {במדבר טו-לא} {דברים לב-מז}
תורה מאוס אמר רב הונא א''ר יוחנן היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל רב חסדא האלהים אם אמרה לי ר' יוחנן בפומיה לא צייתנא ליה איכא דאמרי אמר רבה בר בר חנה אמר ריב''ל היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל ר' חסדא האלהים אם אמרה לי ריב''ל בפומיה לא צייתנא ליה ומי אמר ר' הונא הכי והאמר רב הונא ת''ח אסור לו לעמוד במקום הטנופת לפי שאי אפשר לו לעמוד בלי הרהור תורה לא קשיא כאן בעומד כאן במהלך ומי אמר רבי יוחנן הכי והאמר רבה בר בר חנה א''ר יוחנן בכל מקום מותר להרהר בדברי תורה חוץ מבית המרחץ ומבית הכסא וכי תימא הכא נמי כאן בעומד כאן במהלך איני והא רבי אבהו הוה קא אזיל בתריה דרבי יוחנן והוה קא קרי ק''ש כי מטא במבואות המטונפות אשתיק א''ל לר' יוחנן להיכן אהדר א''ל אם שהית כדי לגמור את כולה חזור לראש הכי קאמר ליה לדידי לא סבירא לי לדידך דסבירא לך אם שהית כדי לגמור את כולה חזור לראש תניא כותיה דרב הונא תניא כותיה דרב חסדא תניא כותיה דרב הונא המהלך במבואות המטונפות מניח ידו על פיו ויקרא ק''ש תניא כותיה דרב חסדא היה מהלך במבואות המטונפות לא יקרא ק''ש ולא עוד אלא שאם היה קורא ובא פוסק לא פסק מאי אמר ר' מיאשה בר בריה דריב''ל עליו הכתוב אומר
וגם אני נתתי להם חוקים לא טובים ומשפטים לא יחיו [בהם] ר' אסי אמר
הוי מושכי העון בחבלי השוא רב אדא בר אהבה אמר מהכא
כי דבר ה' בזה ואם פסק מה שכרו אמר ר' אבהו עליו הכתוב אומר
ובדבר הזה תאריכו ימים: כד:
תורה מוליך ת''ר המוליך עצמות ממקום למקום הרי זה לא יתנם בדסקיא ויתנם על גבי חמור וירכב עליהם מפני שנוהג בהם מנהג בזיון ואם היה מתירא מפני נכרים ומפני לסטים מותר וכדרך שאמרו בעצמות כך אמרו בספר תורה אהייא אילימא ארישא פשיטא מי גרע ספר תורה מעצמות אלא אסיפא:  יח.
תענית טעימה בעי מיניה אשיאן תנא דבי ר' אמי מר' אמי השרוי בתענית מהו שיטעום אכילה ושתיה קביל עליה והא ליכא או דילמא הנאה קביל עליה והא איכא א''ל טועם ואין בכך כלום תניא נמי הכי מטעמת אינה טעונה ברכה והשרוי בתענית טועם ואין בכך כלום עד כמה ר' אמי ור' אסי טעמי עד שיעור רביעתא:  יד.
תפילה נהוג עיטוש רבי אבא אמר איזיל ואשמע מיניה (מר’ יהודה) מילתא מבית וועדא והדר אפיק אזל אשכחיה לתנא דקתני קמיה דרב יהודה היה עומד בתפלה ונתעטש ממתין עד שיכלה הרוח וחוזר ומתפלל איכא דאמרי היה עומד בתפלה ובקש להתעטש מרחיק לאחריו ד' אמות ומתעטש וממתין עד שיכלה הרוח וחוזר ומתפלל ואומר רבש''ע יצרתנו נקבים נקבים חלולים חלולים גלוי וידוע לפניך חרפתנו וכלימתנו בחיינו ובאחריתנו רמה ותולעה ומתחיל ממקום שפסק אמר ליה אילו לא באתי אלא לשמוע דבר זה דיי: כד:
** מתני' גמ'
תפילין
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: כ:
** {יחזקאל כד-יז}
תפילין אבל א''ר אבא בר זבדא אמר רב אבל חייב בכל המצות האמורות בתורה חוץ מן התפילין שהרי נאמר בהם פאר שנאמר
פארך חבוש עליך יא.
תפילין בית הכסא  וא''ר הונא שכח ונכנס בתפילין לבית הכסא מניח ידו עליהן עד שיגמור עד שיגמור ס''ד אלא כדאמר ר''נ בר יצחק עד שיגמור עמוד ראשון ולפסוק לאלתר וליקום משום דרשב''ג דתניא רשב''ג אומר עמוד החוזר מביא את האדם לידי הדרוקן סילון החוזר מביא את האדם לידי ירקון:  כה.
תפילין בית הכסא תנו רבנן הנכנס לבית הכסא חולץ תפיליו ברחוק ד' אמות ונכנס אמר רב אחא בר רב הונא אמר רב ששת לא שנו אלא בית הכסא קבוע אבל בית הכסא עראי חולץ ונפנה לאלתר וכשהוא יוצא מרחיק ד' אמות ומניחן מפני שעשאו בית הכסא קבוע איבעיא להו מהו שיכנס אדם בתפילין לבית הכסא קבוע להשתין מים רבינא שרי רב אדא בר מתנא אסר אתו שיילוה לרבא אמר להו אסור חיישינן שמא יפנה בהן ואמרי לה שמא יפיח בהן תניא אידך הנכנס לבית הכסא קבוע חולץ תפיליו ברחוק ד' אמות ומניחן בחלון הסמוך לרשות הרבים ונכנס וכשהוא יוצא מרחיק ד' אמות ומניחן דברי בית שמאי ובית הלל אומרים אוחזן בידו ונכנס ר''ע אומר אוחזן בבגדו ונכנס בבגדו ס''ד זימנין מישתלי להו ונפלי אלא אימא אוחזן בבגדו ובידו ונכנס ומניחם בחורין הסמוכים לבית הכסא ולא יניחם בחורין הסמוכים לרשות הרבים שמא יטלו אותם עוברי דרכים ויבא לידי חשד ומעשה בתלמיד אחד שהניח תפילין בחורין הסמוכים לרשות הרבים ובאת זונה אחת ונטלתן ובאת לבית המדרש ואמרה ראו מה נתן לי פלוני בשכרי כיון ששמע אותו תלמיד כך עלה לראש הגג ונפל ומת באותה שעה התקינו שיהא אוחזן בבגדו ובידו ונכנס תנו רבנן בראשונה היו מניחין תפילין בחורין הסמוכין לבית הכסא ובאין עכברים ונוטלין אותן התקינו שיהו מניחין אותן בחלונות הסמוכות לרשות הרבים ובאין עוברי דרכים ונוטלין אותן התקינו שיהא אוחזן בידו ונכנס אמר רבי מיאשא בריה דריב''ל הלכה גוללן כמין ספר ואוחזן בימינו כנגד לבו אמר רב יוסף בר מניומי אמר רב נחמן ובלבד שלא תהא רצועה יוצאת מתחת ידו טפח אמר רבי יעקב בר אחא אמר רבי זירא לא שנו אלא שיש שהות ביום ללבשן אבל אין שהות ביום ללבשן עושה להן כמין כיס טפח ומניחן אמר רבה בר בר חנה אמר רבי יוחנן ביום גוללן כמין ספר ומניחן בידו כנגד לבו ובלילה עושה להן כמין כיס טפח ומניחן אמר אביי לא שנו אלא בכלי שהוא כליין אבל בכלי שאינו כליין אפילו פחות מטפח אמר מר זוטרא ואיתימא רב אשי תדע שהרי פכין קטנים מצילין באהל המת ואמר רבה בר בר חנה כי הוה אזלינן בתריה דרבי יוחנן כי הוה בעי למיעל לבית הכסא כי הוה נקיט ספרא דאגדתא הוה יהיב לן כי הוה נקיט תפילין לא הוה יהיב לן אמר הואיל ושרונהו רבנן ננטרן אמר רבא כי הוה אזלינן בתריה דר''נ כי הוה נקיט ספרא דאגדתא יהיב לן כי הוה נקיט תפילין לא יהיב לן אמר הואיל ושרונהו רבנן ננטרן  כג.
תפילין ולא ישתין בהן מים ולא יישן בהן לא שינת קבע ולא שינת עראי. אמר רבא אמר רב ששת לית הלכתא כי הא מתניתא דב''ש היא דאי ב''ה השתא בית הכסא קבוע שרי בית הכסא עראי מיבעיא מיתיבי ... עד שיש חזרה.הכי קאמר בית הכסא קבוע דליכא ניצוצות שרי בית הכסא עראי דאיכא ניצוצות אסרי  כג.
תפילין זמן אחרים אומרים משיראה את חברו רחוק ד' אמות ויכירנו  אמר אביי לתפילין כאחרים ט:
תפילין כבוד בית שיש בו ספר תורה או תפילין אסור לשמש בו את המטה עד שיוציאם או שיניחם כלי בתוך כלי אמר אביי לא שנו אלא בכלי שאינו כליין אבל בכלי שהוא כליין אפילו עשרה מאני כחד מאנא דמי אמר רבא גלימא אקמטרא ככלי בתוך כלי דמי.  כה:
תפילין כיס תני חדא צורר אדם תפיליו עם מעותיו באפרקסותו ותניא אידך לא יצור לא קשיא הא דאזמניה הא דלא אזמניה דאמר רב חסדא האי סודרא דתפילין דאזמניה למיצר ביה תפילין צר ביה תפילין אסור למיצר ביה פשיטי אזמניה ולא צר ביה צר ביה ולא אזמניה שרי למיצר ביה זוזי ולאביי דאמר הזמנה מילתא היא אזמניה אע''ג דלא צר ביה צר ביה אי אזמניה אסיר אי לא אזמניה לא כג:
** {במדבר ה-כג}
תפילין מה כתוב תני ר' אושעיא קמיה דרבא וכתבתם הכל בכתב אפילו צואות א''ל דאמר לך מני ר' יהודה היא דאמר גבי סוטה אלות כותב צואות אינו כותב והתם הוא דכתיב
וכתב את האלות האלה אבל הכא דכתיב וכתבתם אפי' צואות נמי אטו טעמיה דר' יהודה משום דכתיב וכתב טעמיה דר' יהודה משום דכתיב אלות אלות אין צואות לא אצטריך סד''א נילף כתיבה כתיבה מהתם מה התם אלות אין צואות לא אף הכא נמי צואות לא כתב רחמנא וכתבתם אפי' צואות:  טו:
תפילין מטה בעא מיניה רב יוסף בריה דרב נחוניא מרב יהודה מהו שיניח אדם תפיליו תחת מראשותיו תחת מרגלותיו לא קא מיבעיא לי שנוהג בהן מנהג בזיון כי קא מיבעיא לי תחת מראשותיו מאי א''ל הכי אמר שמואל מותר אפילו אשתו עמו מיתיבי לא יניח אדם תפיליו תחת מרגלותיו מפני שנוהג בהם דרך בזיון אבל מניחן תחת מראשותיו ואם היתה אשתו עמו אסור היה מקום שגבוה ג' טפחים או נמוך ג' טפחים מותר תיובתא דשמואל תיובתא אמר רבא אע''ג דתניא תיובתא דשמואל הלכתא כוותיה מ''ט כל לנטורינהו טפי עדיף והיכא מנח להו אמר ר' ירמיה בין כר לכסת שלא כנגד ראשו והא תני רבי חייא מניחן בכובע תחת מראשותיו דמפיק ליה למורשא דכובע לבר בר קפרא צייר להו בכילתא ומפיק למורשהון לבר רב שישא בריה דרב אידי מנח להו אשרשיפא ופריס סודרא עלוייהו אמר רב המנונא בריה דרב יוסף זימנא חדא הוה קאימנא קמיה דרבא ואמר לי זיל אייתי לי תפילין ואשכחתינהו בין כר לכסת שלא כנגד ראשו והוה ידענא דיום טבילה הוה ולאגמורן הלכה למעשה הוא דעבד  כג:
** {דברים יא-יח}
תפילין מקום של יד דאמר
ושמתם את דברי אלה צריכה שתהא שימה כנגד הלב יג:
תפילין סעודה אמר ר' יצחק הנכנס לסעודת קבע חולץ תפיליו ואח''כ נכנס ופליגא דר' חייא דא''ר חייא מניחן על שלחנו וכן הדור לו ועד אימת אמר רב נחמן בר יצחק עד זמן ברכה  כג.
** {דברים כח-סו}
תפילין תלייה אמר ר' חנינא אני ראיתי את רבי שתלה תפיליו מיתיבי התולה תפיליו יתלו לו חייו דורשי חמורות אמרו
והיו חייך תלואים לך מנגד זה התולה תפיליו לא קשיא הא ברצועה הא בקציצה ואיבעית אימא לא שנא רצועה ולא שנא קציצה אסור וכי תלה רבי בכיסתא תלה אי הכי מאי למימרא מהו דתימא תיבעי הנחה כספר תורה קמ''ל:  כד.
** מתני' גמ' {תהילים נה-יח}
תפלה
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
** מתני'
תפלה אומנים
האומנין קורין בראש האילן ובראש הנדבך מה שאינן רשאין לעשות כן בתפלה טז.
תפלה אומנים ת''ר האומנין קורין בראש האילן ובראש הנדבך ומתפללין בראש הזית ובראש התאנה ושאר כל האילנות יורדים למטה ומתפללין ובעל הבית בין כך ובין כך יורד למטה ומתפלל לפי שאין דעתו מיושבת עליו רמי ליה רב מרי ברה דבת שמואל לרבא תנן האומנין קורין בראש האילן ובראש הנדבך טז.
** {ויקרא יט-כו} {מלכים א יד-ט}
תפלה אכילה קודם (א''ר יצחק וא''ר יוסי בר' חנינא משום ראב''י מאי דכתיב
לא תאכלו על הדם לא תאכלו קודם שתתפללו על דמכם (א''ד) א''ר יצחק א''ר יוחנן א''ר יוסי בר' חנינא משום ראב''י כל האוכל ושותה ואח''כ מתפלל עליו הכתוב אומר
ואותי השלכת אחרי גויך אל תקרי גויך אלא גאיך אמר הקב''ה לאחר שנתגאה זה קבל עליו מלכות שמים: י.
תפלה בא מאוחר אמר רב הונא הנכנס לבית הכנסת ומצא צבור שמתפללין אם יכול להתחיל ולגמור עד שלא יגיע ש''ץ למודים יתפלל ואם לאו אל יתפלל ריב''ל אמר אם יכול להתחיל ולגמור עד שלא יגיע ש''צ לקדושה יתפלל ואם לאו אל יתפלל במאי קא מפלגי מר סבר יחיד אומר קדושה ומר סבר אין יחיד אומר קדושה  כא:
תפלה באחיזה ת''ר לא יאחז אדם תפילין בידו וס''ת בזרועו ויתפלל אמר שמואל סכין ומעות וקערה וככר הרי אלו כיוצא בהן.  כג.
תפלה בית הכנסת כמה יכנס אמר רב חסדא לעולם יכנס אדם שני פתחים בבית הכנסת שני פתחים סלקא דעתך אלא אימא שיעור שני פתחים ואחר כך יתפלל:  ח.
** {תהילים סט-יד} {ישעיה מט-ח} {איוב לו-ה} {תהילים נה-יט}
תפלה ברבים זמן רבים א''ל רבי יצחק לרב נחמן מ''ט לא אתי מר לבי כנישתא לצלויי אמר ליה לא יכילנא א''ל לכנפי למר עשרה וליצלי אמר ליה טריחא לי מלתא ולימא ליה מר לשלוחא דצבורא בעידנא דמצלי צבורא ליתי ולודעיה למר א''ל מאי כולי האי א''ל דאמר ר' יוחנן משום ר''ש בן יוחי מאי דכתיב
ואני תפלתי לך ה' עת רצון אימתי עת רצון בשעה שהצבור מתפללין. ר' יוסי ברבי חנינא אמר מהכא
כה אמר ה' בעת רצון עניתיך ר' אחא ברבי חנינא אמר מהכא
הן אל כביר ולא ימאס וכתיב
פדה בשלום נפשי מקרב לי כי ברבים היו עמדי תניא נמי הכי רבי נתן אומר מנין שאין הקב''ה מואס בתפלתן של רבים שנאמר הן אל כביר ולא ימאס וכתיב פדה בשלום נפשי מקרב לי וגו' אמר הקב''ה כל העוסק בתורה ובגמילות חסדים ומתפלל עם הצבור מעלה אני עליו כאילו פדאני לי ולבני מבין אומות העולם ז:
תפלה הא ר''ג הא ר' יהושע אי ר' יהושע מאי איריא פועלים אפילו כל אדם נמי טז.
תפלה הוספות א''ר יוחנן בתחלה הוא אומר ה' שפתי תפתח ולבסוף הוא אומר יהיו לרצון אמרי פי וגו' ט:
** {תהילים קד-לה} {תהילים א-א} {תהילים ב-יב}
תפלה הוספות מכדי האי יהיו לרצון אמרי פי משמע לבסוף ומשמע מעיקרא דבעינא למימר מ''ט תקנוהו רבנן לאחר י''ח ברכות לימרו מעיקרא א''ר יהודה בריה דר' שמעון בן פזי הואיל ולא אמרו דוד אלא לאחר י''ח פרשיות לפיכך תקינו רבנן לאחר י''ח ברכות. הני י''ח י''ט הויין אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' יהודה בריה דרבי שמעון בן פזי ק''ג פרשיות אמר דוד ולא אמר הללויה עד שראה במפלתן של רשעים שנאמר
יתמו חטאים מן הארץ ורשעים עוד אינם ברכי נפשי את ה' הללויה. הני ק''ג ק''ד הויין אלא שמע מינה אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' שמואל בר נחמני אמר רבי יוחנן כל פרשה שהיתה חביבה על דוד פתח בה באשרי וסיים בה באשרי פתח באשרי דכתיב
אשרי האיש וסיים באשרי דכתיב
אשרי כל חוסי בו:
תפלה הכון הפסק ת''ר היה עומד בתפלה ומים שותתין על ברכיו פוסק עד שיכלו המים וחוזר ומתפלל להיכן חוזר רב חסדא ורב המנונא חד אמר חוזר לראש וחד אמר למקום שפסק לימא בהא קמיפלגי מר סבר אם שהה כדי לגמור את כולה חוזר לראש ומר סבר למקום שפסק אמר רב אשי האי אם שהה אם לא שהה מיבעי ליה אלא דכולי עלמא אם שהה כדי לגמור את כולה חוזר לראש והתם בדלא שהה קמיפלגי דמר סבר גברא דחויא הוא ואין ראוי ואין תפלתו תפלה ומר סבר גברא חזיא הוא ותפלתו תפלה  כג.
** {עמוס ד-יב}
תפלה הכון תנו רבנן הנצרך לנקביו אל יתפלל ואם התפלל תפלתו תועבה אמר רב זביד ואיתימא רב יהודה לא שנו אלא שאינו יכול לשהות בעצמו אבל אם יכול לשהות בעצמו תפלתו תפלה ועד כמה אמר רב ששת עד פרסה איכא דמתני לה אמתניתא במה דברים אמורים כשאין יכול לעמוד על עצמו אבל אם יכול לעמוד על עצמו תפלתו תפלה ועד כמה אמר רב זביד עד פרסה אמר רבי שמואל בר נחמני אמר רבי יונתן הנצרך לנקביו הרי זה לא יתפלל משום שנאמר
הכון לקראת אלהיך ישראל. כג.
תפלה הפסק  ודכולי עלמא מיהת מפסק לא פסיק (למודים וקדושה) איבעיא להו מהו להפסיק ליהא שמו הגדול מבורך כי אתא רב דימי אמר ר' יהודה ור''ש תלמידי דרבי יוחנן אמרי לכל אין מפסיקין חוץ מן יהא שמו הגדול מבורך שאפילו עוסק במעשה מרכבה פוסק ולית הלכתא כותיה:  כא:
** {תהילים קמו-ח} {מלאכי ב-ה}
תפלה השתחויות ואמר רבה בר חיננא [סבא] משמיה דרב המתפלל כשהוא כורע כורע בברוך וכשהוא זוקף זוקף בשם אמר שמואל מאי טעמא דרב דכתיב
ה' זוקף כפופים מיתיבי
מפני שמי נחת הוא מי כתיב בשמי מפני שמי כתיב אמר ליה שמואל לחייא בר רב בר אוריאן תא ואימא לך מלתא מעלייתא דאמר אבוך הכי אמר אבוך כשהוא כורע כורע בברוך כשהוא זוקף זוקף בשם. רב ששת כי כרע כרע כחיזרא כי קא זקיף זקיף כחיויא: יב.
** {תהילים עב-ה}
תפלה זמן  לק''ש כותיקין דאמר ר' יוחנן ותיקין היו גומרין אותה עם הנץ החמה תניא נמי הכי ותיקין היו גומרין אותה עם הנץ החמה כדי שיסמוך גאולה לתפלה ונמצא מתפלל ביום א''ר זירא מאי קראה
ייראוך עם שמש ולפני ירח דור דורים ט:
** {תהילים פה-יד}
תפלה חפציו קודם אמר רב אידי בר אבין אסור לו לאדם לעשות חפציו קודם שיתפלל שנאמר
צדק לפניו יהלך וישם לדרך פעמיו ואמר רב אידי בר אבין אמר רב יצחק בר אשיאן כל המתפלל ואח''כ יוצא לדרך הקב''ה עושה לו חפציו שנאמר צדק לפניו יהלך וישם לדרך פעמיו:  יד.
תפלה כבר התפלל  ואמר רב יהודה אמר שמואל היה עומד בתפלה ונזכר שהתפלל פוסק ואפילו באמצע ברכה איני והאמר רב נחמן כי הוינן בי רבה בר אבוה בען מיניה הני בני בי רב דטעו ומדכרי דחול בשבת מהו שיגמרו ואמר לן גומרין כל אותה ברכה הכי השתא התם גברא בר חיובא הוא ורבנן הוא דלא אטרחוהו משום כבוד שבת אבל הכא הא צלי ליה: ואמר רב יהודה אמר שמואל התפלל ונכנס לביהכ''נ ומצא צבור שמתפללין אם יכול לחדש בה דבר יחזור ויתפלל ואם לאו אל יחזור ויתפלל וצריכא דאי אשמעינן קמייתא ה''מ יחיד ויחיד או צבור וצבור אבל יחיד לגבי צבור כמאן דלא צלי דמי קמ''ל ואי אשמעינן הכא משום דלא אתחיל בה אבל התם דאתחיל בה אימא לא צריכא כא
** {משלי כא-כז}
תפלה מאוס תניא אידך היה עומד בתפלה וראה צואה כנגדו מהלך לפניו עד שיזרקנה לאחוריו ד' אמות והתניא לצדדין ל''ק הא דאפשר הא דלא אפשר היה מתפלל ומצא צואה במקומו אמר רבה אע''פ שחטא תפלתו תפלה מתקיף ליה רבא והא
זבח רשעים תועבה אלא אמר רבא הואיל וחטא אע''פ שהתפלל תפלתו תועבה:  כב:
תפלה ניהוג ואמר ר' חנינא אני ראיתי את רבי שגיהק ופיהק ונתעטש ורק וממשמש בבגדו אבל לא היה מתעטף וכשהוא מפהק היה מניח ידו על סנטרו מיתיבי המשמיע קולו בתפלתו הרי זה מקטני אמנה המגביה קולו בתפלתו הרי זה מנביאי השקר מגהק ומפהק הרי זה מגסי הרוח המתעטש בתפלתו סימן רע לו ויש אומרים ניכר שהוא מכוער הרק בתפלתו כאילו רק בפני המלך בשלמא מגהק ומפהק לא קשיא כאן לאונסו כאן לרצונו אלא מתעטש אמתעטש קשיא מתעטש אמתעטש נמי לא קשיא כאן מלמעלה כאן מלמטה אלא רק ארק קשיא רק ארק נמי לא קשיא אפשר כדרב יהודה דאמר רב יהודה היה עומד בתפלה ונזדמן לו רוק מבליעו בטליתו ואם טלית נאה הוא מבליעו באפרקסותו רבינא הוה קאי אחורי דרב אשי נזדמן לו רוק פתקיה לאחוריה א''ל לא סבר לה מר להא דרב יהודה מבליעו באפרקסותו א''ל אנא אנינא דעתאי: כד:
תפלה ספק ספק התפלל ספק לא התפלל אינו חוזר ומתפלל ורבי יוחנן אמר ולואי שיתפלל אדם כל היום כולו:  כא.
תפלה ערווה היתה טליתו של בגד ושל עור ושל שק חגורה על מתניו מותר לקרות ק''ש אבל לתפלה עד שיכסה את לבו  כד:
** {ישעיה ה-טז}
תפלה עשרת ימי תשובה ואמר רבה בר חיננא סבא משמיה דרב כל השנה כולה אדם מתפלל האל הקדוש מלך אוהב צדקה ומשפט חוץ מעשרה ימים שבין ראש השנה ויום הכפורים שמתפלל המלך הקדוש והמלך המשפט ורבי אלעזר אמר אפילו אמר האל הקדוש יצא שנאמר
ויגבה ה' צבאות במשפט והאל הקדוש נקדש בצדקה אימתי ויגבה ה' צבאות במשפט אלו עשרה ימים שמר''ה ועד יוה''כ וקאמר האל הקדוש מאי הוה עלה אמר רב יוסף האל הקדוש ומלך אוהב צדקה ומשפט רבה אמר המלך הקדוש והמלך המשפט והלכתא כרבה:  יב:
תפלה קול המשמיע קולו בתפלתו הרי זה מקטני אמנה: אמר רב הונא לא שנו אלא שיכול לכוין את לבו בלחש אבל אין יכול לכוין את לבו בלחש מותר וה''מ ביחיד אבל בצבור אתי למיטרד צבורא:  כד:
** {יחזקאל א-ז}
תפלה רגלים וא''ר יוסי בר' חנינא משום ראב''י המתפלל צריך שיכוין את רגליו שנא'
ורגליהם רגל ישרה י.
תפלה של חול בשבת בען מיניה הני בני בי רב דטעו ומדכרי דחול בשבת מהו שיגמרו ואמר לן גומרין כל אותה ברכה הכי השתא התם גברא בר חיובא הוא ורבנן הוא דלא אטרחוהו משום כבוד שבת כא.
** {ישעיה ב-כב}
תפלה שלום קודם אמר רב כל הנותן שלום לחבירו קודם שיתפלל כאלו עשאו במה שנאמר
חדלו לכם מן האדם אשר נשמה באפו כי במה נחשב הוא אל תקרי במה אלא במה ושמואל אמר במה חשבתו לזה ולא לאלוה מתיב רב ששת בפרקים שואל מפני הכבוד ומשיב תרגמה ר' אבא במשכים לפתחו יד.
** {ויקרא כב-ז}
תרומה זמן מלתא אגב אורחיה קמשמע לן כהנים אימת קא אכלי בתרומה משעת צאת הכוכבים והא קמשמע לן דכפרה לא מעכבא כדתניא
ובא השמש וטהר ביאת שמשו מעכבתו מלאכול בתרומה ואין כפרתו מעכבתו מלאכול בתרומה. וממאי דהאי ובא השמש ביאת השמש והאי וטהר טהר יומא 
דילמא ביאת אורו הוא ומאי וטהר טהר גברא אמר רבה בר רב שילא א''כ לימא קרא ויטהר מאי וטהר טהר יומא כדאמרי אינשי איערב שמשא ואדכי יומא. במערבא הא דרבה בר רב שילא לא שמיע להו ובעו לה מיבעיא האי ובא השמש ביאת שמשו הוא ומאי וטהר טהר יומא או דילמא ביאת אורו הוא ומאי וטהר טהר גברא והדר פשטו לה מברייתא מדקתני בברייתא סימן לדבר צאת הכוכבים שמע מינה ביאת שמשו הוא ומאי וטהר טהר יומא. ב.
