** {שמות כב-יז}
אוב וידעוני בן עזאי אומר נאמר
מכשפה לא תחיה ונאמר כל שוכב עם בהמה מות יומת סמכו ענין לו לומר מה שוכב עם בהמה בסקילה אף מכשפה נמי בסקילה אמר ליה ר' יהודה וכי מפני שסמכו ענין לו נוציא לזה לסקילה אלא אוב וידעוני בכלל כל המכשפים היו ולמה יצאו להקיש להן ולומר לך מה אוב וידעוני בסקילה אף מכשפה בסקילה כא.
** {דברים כז-ט}
אומנים אלמא לא בעי כונה ורמינהי הקורא את שמע צריך שיכוין את לבו שנאמר שמע ישראל ולהלן הוא אומר
הסכת ושמע ישראל מה להלן בהסכת אף כאן בהסכת אשתיק א''ל מידי שמיע לך בהא א''ל הכי אמר רב ששת והוא שבטלין ממלאכתן וקורין והתניא בית הלל אומרים עוסקין במלאכתן וקורין לא קשיא הא בפרק ראשון הא בפרק שני טז.
** מתני'
אומנים
האומנין קורין בראש האילן ובראש הנדבך מה שאינן רשאין לעשות כן בתפלה טז.
אומנים ת''ר האומנין קורין בראש האילן ובראש הנדבך ומתפללין בראש הזית ובראש התאנה ושאר כל האילנות יורדים למטה ומתפללין ובעל הבית בין כך ובין כך יורד למטה ומתפלל לפי שאין דעתו מיושבת עליו רמי ליה רב מרי ברה דבת שמואל לרבא תנן האומנין קורין בראש האילן ובראש הנדבך טז.
אומנים ת''ר הפועלים שהיו עושין מלאכה אצל בעל הבית קורין ק''ש ומברכין לפניה ולאחריה ואוכלין פתן ומברכין לפניה ולאחריה ומתפללין תפלה של שמונה עשרה אבל אין יורדין לפני התיבה ואין נושאין כפיהם והתניא מעין י''ח אמר רב ששת לא קשיא הא ר''ג הא ר' יהושע אי ר' יהושע מאי איריא פועלים אפילו כל אדם נמי אלא אידי ואידי ר''ג ולא קשיא כאן בעושין בשכרן כאן בעושין בסעודתן והתניא הפועלים שהיו עושים מלאכה אצל בעל הבית קורין ק''ש ומתפללין ואוכלין פתן ואין מברכים לפניה אבל מברכין לאחריה שתים כיצד ברכה ראשונה כתקונה שניה פותח בברכת הארץ וכוללין בונה ירושלים בברכת הארץ במה דברים אמורים בעושין בשכרן אבל עושין בסעודתן או שהיה בעל הבית מיסב עמהן מברכין כתיקונה:  טז.
אונן הוצאת המת אם יכולים להתחיל ולגמור את כולה אין אבל פרק אחד או פסוק אחד לא ורמינהו קברו את המת וחזרו אם יכולין להתחיל ולגמור אפילו פרק אחד או פסוק אחד הכי נמי קאמר אם יכולין להתחיל ולגמור אפי' פרק אחד או אפילו פסוק אחד עד שלא יגיעו לשורה יתחילו ואם לאו לא יתחילו:  יט.
אונן הוצאת מת ת''ר אין מוציאין את המת סמוך לק''ש ואם התחילו אין מפסיקין איני והא רב יוסף אפקוהו סמוך לק''ש אדם חשוב שאני: יט.
אונן לועג לרש אמר רחבה אמר רב יהודה כל הרואה המת ואינו מלוהו עובר משום לועג לרש חרף עושהו  יח.
אונן לועג לרש ואמר רבי זריקא אמר רבי אמי אמר רבי יהושע בן לוי אין אומרין בפני המת אלא דבריו של מת אמר רבי אבא בר כהנא לא אמרן אלא בדברי תורה אבל מילי דעלמא לית לן בה ואיכא דאמרי אמר רבי אבא בר כהנא לא אמרן אלא [אפילו] בדברי תורה וכ''ש מילי דעלמא: ג:
** {משלי יז-ה}
אונן לועג לרש מתו ומשמרו אין אבל מהלך בבית הקברות לא והתניא לא יהלך אדם בבית הקברות ותפילין בראשו וספר תורה בזרועו וקורא ואם עושה כן עובר משום
לועג לרש חרף עושהו התם תוך ארבע [אמות] הוא דאסור חוץ לארבע אמות חייב דאמר מר מת תופס ד' אמות לק''ש הכא חוץ לד' אמות נמי פטור:
אונן לועג לרש רבי חייא ורבי יונתן הוו שקלי ואזלי בבית הקברות הוה קשדיא תכלתא דרבי יונתן אמר ליה רבי חייא דלייה כדי שלא יאמרו למחר באין אצלנו ועכשיו מחרפין אותנו יח.
** {בראשית כג-ג}
אונן מוטל לפניו אין ושאינו מוטל לפניו לא ורמינהי מי שמתו מוטל לפניו אוכל בבית אחר ואם אין לו בית אחר אוכל בבית חבירו ואם אין לו בית חבירו עושה מחיצה ואוכל ואם אין לו דבר לעשות מחיצה מחזיר פניו ואוכל ואינו מיסב ואוכל ואינו אוכל בשר ואינו שותה יין ואינו מברך ואינו מזמן ואין מברכין עליו ואין מזמנין עליו ופטור מקריאת שמע ומן התפלה ומן התפילין ומכל מצות האמורות בתורה ובשבת מיסב ואוכל בשר ושותה יין ומברך ומזמן ומברכין עליו ומזמנין עליו וחייב בכל המצות האמורות בתורה. רשב''ג אומר מתוך שנתחייב באלו נתחייב בכולן וא''ר יוחנן מאי בינייהו תשמיש המטה איכא בינייהו קתני מיהת פטור מקריאת שמע ומן התפלה ומן התפילין ומכל מצות האמורות בתורה אמר רב פפא תרגמא אמחזיר פניו ואוכל רב אשי אמר כיון שמוטל עליו לקוברו כמוטל לפניו דמי שנאמר
ויקם אברהם מעל פני מתו ונאמר ואקברה מתי מלפני כל זמן שמוטל עליו לקוברו כמוטל לפניו דמי  יז:
אונן מוליך עצמות ת''ר המוליך עצמות ממקום למקום הרי זה לא יתנם בדסקיא ויתנם על גבי חמור וירכב עליהם מפני שנוהג בהם מנהג בזיון ואם היה מתירא מפני נכרים ומפני לסטים מותר  יח.
** {עמוס ח-י}
אונן מ''ט דרבן (שמעון בן) גמליאל קסבר אנינות לילה דרבנן דכתיב
ואחריתה כיום מר ובמקום אסטניס לא גזרו ביה רבנן:
אונן מי שמתו מוטל לפניו פטור מק''ש ומן התפלה ומן התפילין ומכל מצות האמורות בתורה  יז:
אונן משמר גופא המשמר את המת אע''פ שאינו מתו פטור מקריאת שמע ומן התפלה ומן התפילין ומכל מצות האמורות בתורה היו שנים זה משמר וזה קורא וזה משמר וזה קורא בן עזאי אומר היו באים בספינה מניחו בזוית זו ומתפללין שניהם בזוית אחרת מאי בינייהו אמר רבינא חוששין לעכברים איכא בינייהו מר סבר חיישינן ומר סבר לא חיישינן: יח.
אונן מת משמר מתו אין אבל משמרו לא והתניא המשמר את המת אע''פ שאינו מתו פטור מק''ש ומן התפלה ומן התפילין ומכל מצות האמורות בתורה משמרו אע''פ שאינו מתו מתו אע''פ שאינו משמרו יח.
** {ישעיה א-ט}
אונן סדר תנחומים ת''ר העוסקים בהספד בזמן שהמת מוטל לפניהם נשמטין אחד אחד וקורין אין המת מוטל לפניהם הן יושבין וקורין והוא יושב ודומם הם עומדים ומתפללין והוא עומד ומצדיק עליו את הדין ואומר רבון העולמים הרבה חטאתי לפניך ולא נפרעת ממני אחד מני אלף יהי רצון מלפניך ה' אלהינו שתגדור פרצותינו ופרצות כל עמך בית ישראל ברחמים אמר אביי לא מבעי ליה לאינש למימר הכי דארשב''ל וכן תנא משמיה דרבי יוסי לעולם אל יפתח אדם פיו לשטן ואמר רב יוסף מאי קראה שנאמר
כמעט כסדום היינו מאי אהדר להו נביא שמעו דבר ה' קציני סדום:  יט.
** מתני'
אונן רחיצה
רחץ לילה הראשון שמתה אשתו אמרו לו תלמידיו למדתנו רבינו שאבל אסור לרחוץ אמר להם איני כשאר בני אדם אסטניס אני טז:
אונן ת''ר העוסקים בהספד בזמן שהמת מוטל לפניהם נשמטין אחד אחד וקורין אין המת מוטל לפניהם הן יושבין וקורין והוא יושב ודומם הם עומדים ומתפללין והוא עומד ומצדיק עליו את הדין יט.
** {משלי כא-ל} {דברים יז-יא} {דברים כב-א} {במדבר ו-ז}
אין חכמה ואין תבונה אמר רב יהודה אמר רב המוצא כלאים בבגדו פושטן אפי' בשוק מ''ט
אין חכמה ואין תבונה ואין עצה לנגד ה' כ''מ שיש חלול השם אין חולקין כבוד לרב מתיבי קברו את המת וחזרו ולפניהם ב' דרכים אחת טהורה ואחת טמאה בא בטהורה באין עמו בטהורה בא בטמאה באין עמו בטמאה משום כבודו אמאי לימא אין חכמה ואין תבונה לנגד ה' תרגמה רבי אבא בבית הפרס דרבנן דאמר רב יהודה אמר שמואל מנפח אדם בית הפרס והולך ואמר רב יהודה בר אשי משמיה דרב בית הפרס שנדש טהור ת''ש דאמר ר' אלעזר בר צדוק מדלגין היינו על גבי ארונות של מתים לקראת מלכי ישראל ולא לקראת מלכי ישראל בלבד אמרו אלא אפי' לקראת מלכי עכו''ם שאם יזכה יבחין בין מלכי ישראל למלכי עכו''ם אמאי לימא אין חכמה ואין תבונה ואין עצה לנגד ה' כדרבא דאמר רבא דבר תורה אהל כל שיש בו חלל טפח חוצץ בפני הטומאה ושאין בו חלל טפח אינו חוצץ בפני הטומאה ורוב ארונות יש בהן חלל טפח וגזרו על שיש בהן משום שאין בהן ומשום כבוד מלכים לא גזרו בהו רבנן ת''ש גדול כבוד הבריות שדוחה [את] לא תעשה שבתורה ואמאי לימא אין חכמה ואין תבונה ואין עצה לנגד ה' תרגמה רב בר שבא קמיה דרב כהנא בלאו
דלא תסור אחיכו עליה לאו דלא תסור דאורייתא היא אמר רב כהנא גברא רבה אמר מילתא לא תחיכו עליה כל מילי דרבנן אסמכינהו על לאו דלא תסור ומשום כבודו שרו רבנן ת''ש
והתעלמת מהם פעמים שאתה מתעלם מהם ופעמים שאין אתה מתעלם מהם הא כיצד אם היה כהן והיא בבית הקברות או היה זקן ואינה לפי כבודו או שהיתה מלאכתו מרובה משל חברו לכך נאמר והתעלמת אמאי לימא אין חכמה ואין תבונה ואין עצה לנגד ה' שאני התם דכתיב והתעלמת מהם וליגמר מינה איסורא מממונא לא ילפינן ת''ש
ולאחותו מה תלמוד לומר הרי שהיה הולך לשחוט את פסחו ולמול את בנו ושמע שמת לו מת יכול יחזור ויטמא אמרת לא יטמא יכול כשם שאינו מטמא להם כך אינו מטמא למת מצוה ת''ל ולאחותו לאחותו הוא דאינו מטמא אבל מטמא הוא למת מצוה אמאי לימא אין חכמה ואין תבונה ואין עצה לנגד ה' שאני התם דכתיב ולאחותו וליגמר מינה שב ואל תעשה שאני:  יט:
** {דברים כג-א}
אנוסת אביו דתניא רבי אליעזר אומר נושא אדם אנוסת אביו ומפותת אביו אנוסת בנו ומפותת בנו ר' יהודה אוסר באנוסת אביו ובמפותת אביו ואמר רב גידל אמר רב מאי טעמא דר' יהודה דכתיב
לא יקח איש את אשת אביו ולא יגלה (את) כנף אביו כנף שראה אביו לא יגלה וממאי דבאנוסת אביו כתיב דסמיך ליה ונתן האיש השוכב עמה וגו' כא.
בין השמשות זמן מי סברת דאנא אבין השמשות דידך קא אמינא אנא אבין השמשות דרבי יוסי קא אמינא דאמר רבי יוסי בין השמשות כהרף עין זה נכנס וזה יוצא ואי אפשר לעמוד עליו ב:
בית הכנסת כמה יכנס אמר רב חסדא לעולם יכנס אדם שני פתחים בבית הכנסת שני פתחים סלקא דעתך אלא אימא שיעור שני פתחים ואחר כך יתפלל:  ח.
בית הכסא לענין טפח וטפחיים דתני חדא כשהוא נפנה מגלה לאחריו טפח ולפניו טפחיים ותניא אידך לאחריו טפח ולפניו ולא כלום מאי לאו אידי ואידי באיש ולא קשיא כאן לגדולים כאן לקטנים ותסברא אי בקטנים לאחריו טפח למה לי אלא אידי ואידי בגדולים ולא קשיא הא באיש הא באשה אי הכי הא דקתני עלה זהו ק''ו שאין עליו תשובה מאי אין עליו תשובה דרכא דמילתא הכי איתא כג.
בית המקדש סדר שמע ובשבת מוסיפין ברכה אחת למשמר היוצא. מאי ברכה אחת א''ר חלבו משמר היוצא אומר למשמר הנכנס מי ששכן את שמו בבית הזה הוא ישכין ביניכם אהבה ואחוה ושלום וריעות: יב.
בית המקדש סדר שמע תנן התם אמר להם הממונה ברכו ברכה אחת והם ברכו וקראו עשרת הדברות שמע והיה אם שמוע ויאמר וברכו את העם ג' ברכות אמת ויציב ועבודה וברכת כהנים ובשבת מוסיפין ברכה אחת למשמר היוצא מאי ברכה אחת כי הא דרבי אבא ור' יוסי בר אבא אקלעו לההוא אתרא בעו מנייהו מאי ברכה אחת לא הוה בידייהו ואתו שיילוהו לרב מתנה לא הוה בידיה אתו שיילוהו לרב יהודה אמר להו הכי אמר שמואל אהבה רבה ואמר רבי זריקא אמר רבי אמי א''ר שמעון בן לקיש יוצר אור כי אתא רב יצחק בר יוסף אמר הא דרבי זריקא לאו בפירוש אתמר אלא מכללא אתמר דאמר ר' זריקא א''ר אמי אמר ר' שמעון בן לקיש זאת אומרת ברכות אין מעכבות זו את זו אי אמרת בשלמא יוצר אור הוו אמרי היינו דברכות אין מעכבות זו את זו דלא קא אמרי אהבה רבה אלא אי אמרת אהבה רבה הוו אמרי מאי ברכות אין מעכבות זו את זו דלמא האי דלא אמרי יוצר אור משום דלא מטא זמן יוצר אור וכי מטא זמן יוצר אור הוו אמרי ואי מכללא מאי דאי מכללא לעולם אהבה רבה הוו אמרי וכי מטא זמן יוצר אור הוו אמרי ליה ומאי ברכות אין מעכבות זו את זו סדר ברכות: יא:
** מתני' גמ'
בעל קרי
זב שראה קרי ונדה שפלטה שכבת זרע והמשמשת שראתה נדה צריכין טבילה ורבי יהודה פוטר:
איבעיא להו בעל קרי שראה זיבה לר' יהודה מהו כי פטר רבי יהודה התם בזב שראה קרי דמעיקרא לאו בר טבילה הוא אבל בעל קרי שראה זיבה דמעיקרא בר טבילה הוא מחייב או דילמא לא שנא תא שמע המשמשת וראתה נדה צריכה טבילה ורבי יהודה פוטר והא משמשת וראתה נדה כבעל קרי שראה זיבה דמיא וקא פטר רבי יהודה ש''מ תני רבי חייא בהדיא בעל קרי שראה זיבה צריך טבילה ורבי יהודה פוטר: כו.
** גמ'
בעל קרי בעל קרי מהרהר בלבו ואינו מברך לא לפניה ולא לאחריה ועל המזון מברך לאחריו ואינו מברך לפניו רבי יהודה אומר מברך לפניהם ולאחריהם:
אמר רבינא זאת אומרת הרהור כדבור דמי דאי סלקא דעתך לאו כדבור דמי למה מהרהר אלא מאי הרהור כדבור דמי יוציא בשפתיו כדאשכחן בסיני ורב חסדא אמר הרהור לאו כדבור דמי דאי סלקא דעתך הרהור כדבור דמי יוציא בשפתיו אלא מאי הרהור לאו כדבור דמי למה מהרהר אמר רבי אלעזר כדי שלא יהו כל העולם עוסקין בו והוא יושב ובטל ונגרוס בפרקא אחרינא אמר רב אדא בר אהבה בדבר שהצבור עוסקין בו והרי תפלה דדבר שהצבור עסוקין בו ותנן היה עומד בתפלה ונזכר שהוא בעל קרי לא יפסיק אלא יקצר טעמא דאתחיל הא לא אתחיל לא יתחיל שאני תפלה דלית בה מלכות שמים והרי ברכת המזון לאחריו דלית בה מלכות שמים ותנן על המזון מברך לאחריו ואינו מברך לפניו אלא ק''ש וברכת המזון דאורייתא ותפלה דרבנן:  כ:
** {דברים ד-ט} {שמות כב-יז} {דברים כג-א} {דברים ד-ט} {דברים ד-ט} {ירמיה כג-כט} {דברים כב-ט}
בעל קרי למימרא דקסבר רבי יהודה בעל קרי מותר בדברי תורה והאמר ריב''ל מנין לבעל קרי שאסור בדברי תורה שנאמר
והודעתם לבניך ולבני בניך וסמיך ליה יום אשר עמדת וגו' מה להלן בעלי קריין אסורין אף כאן בעלי קריין אסורין וכי תימא רבי יהודה לא דריש סמוכים והאמר רב יוסף אפילו מאן דלא דריש סמוכים בכל התורה במשנה תורה דריש דהא רבי יהודה לא דריש סמוכין בכל התורה כולה ובמשנה תורה דריש ובכל התורה כולה מנא לן דלא דריש דתניא בן עזאי אומר נאמר
מכשפה לא תחיה ונאמר כל שוכב עם בהמה מות יומת סמכו ענין לו לומר מה שוכב עם בהמה בסקילה אף מכשפה נמי בסקילה אמר ליה ר' יהודה וכי מפני שסמכו ענין לו נוציא לזה לסקילה אלא אוב וידעוני בכלל כל המכשפים היו ולמה יצאו להקיש להן ולומר לך מה אוב וידעוני בסקילה אף מכשפה בסקילה ובמשנה תורה מנא לן דדריש דתניא רבי אליעזר אומר נושא אדם אנוסת אביו ומפותת אביו אנוסת בנו ומפותת בנו ר' יהודה אוסר באנוסת אביו ובמפותת אביו ואמר רב גידל אמר רב מאי טעמא דר' יהודה דכתיב
לא יקח איש את אשת אביו ולא יגלה (את) כנף אביו כנף שראה אביו לא יגלה וממאי דבאנוסת אביו כתיב דסמיך ליה ונתן האיש השוכב עמה וגו' אמרי אין במשנה תורה דריש והני סמוכין מבעי ליה לאידך דריב''ל דאמר ריב''ל כל המלמד לבנו תורה מעלה עליו הכתוב כאלו קבלה מהר חורב שנאמר
והודעתם לבניך ולבני בניך וכתיב בתריה יום אשר עמדת לפני ה' אלהיך בחורב תנן זב שראה קרי ונדה שפלטה שכבת זרע המשמשת וראתה דם צריכין טבילה ורבי יהודה פוטר עד כאן לא פטר רבי יהודה אלא בזב שראה קרי דמעיקרא לאו בר טבילה הוא אבל בעל קרי גרידא מחייב וכי תימא ה''ה דאפילו בעל קרי גרידא נמי פטר רבי יהודה והאי דקא מפלגי בזב שראה קרי להודיעך כחן דרבנן אימא סיפא המשמשת וראתה דם צריכה טבילה למאן קתני לה אילימא לרבנן פשיטא השתא ומה זב שראה קרי דמעיקרא לאו בר טבילה הוא מחייבי רבנן המשמשת וראתה דם דמעיקרא בת טבילה היא לא כל שכן אלא לאו ר' יהודה היא ודוקא קתני לה משמשת וראתה נדה אינה צריכה טבילה אבל בעל קרי גרידא מחייב לא תימא מברך אלא מהרהר ומי אית ליה לרבי יהודה הרהור והתניא בעל קרי שאין לו מים לטבול קורא קריאת שמע ואינו מברך לא לפניה ולא לאחריה ואוכל פתו ומברך לאחריה ואינו מברך לפניה אבל מהרהר בלבו ואינו מוציא בשפתיו דברי רבי מאיר רבי יהודה אומר בין כך ובין כך מוציא בשפתיו אמר רב נחמן בר יצחק עשאן ר' יהודה כהלכות דרך ארץ דתניא
והודעתם לבניך ולבני בניך וכתיב בתריה יום אשר עמדת לפני ה' אלהיך בחורב מה להלן באימה וביראה וברתת ובזיע אף כאן באימה וביראה וברתת ובזיע מכאן אמרו הזבים והמצורעים ובאין על נדות מותרים לקרות בתורה ובנביאים ובכתובים לשנות במשנה וגמרא ובהלכות ובאגדות אבל בעלי קריין אסורים רבי יוסי אומר שונה הוא ברגיליות ובלבד שלא יציע את המשנה רבי יונתן בן יוסף אומר מציע הוא את המשנה ואינו מציע את הגמרא רבי נתן בן אבישלום אומר אף מציע את הגמרא ובלבד שלא יאמר אזכרות שבו רבי יוחנן הסנדלר תלמידו של רבי עקיבא משום ר''ע אומר לא יכנס למדרש כל עיקר ואמרי לה לא יכנס לבית המדרש כל עיקר ר' יהודה אומר שונה הוא בהלכות דרך ארץ מעשה ברבי יהודה שראה קרי והיה מהלך על גב הנהר אמרו לו תלמידיו רבינו שנה לנו פרק אחד בהלכות דרך ארץ ירד וטבל ושנה להם אמרו לו לא כך למדתנו רבינו שונה הוא בהלכות דרך ארץ אמר להם אע''פ שמיקל אני על אחרים מחמיר אני על עצמי: תניא ר' יהודה בן בתירא היה אומר אין דברי תורה מקבלין טומאה מעשה בתלמיד אחד שהיה מגמגם למעלה מרבי יהודה בן בתירא אמר ליה בני פתח פיך ויאירו דבריך שאין דברי תורה מקבלין טומאה שנאמר
הלא כה דברי כאש נאם ה' מה אש אינו מקבל טומאה אף דברי תורה אינן מקבלין טומאה אמר מר מציע את המשנה ואינו מציע את הגמרא מסייע ליה לרבי אלעאי דאמר רבי אלעאי אמר ר' אחא בר יעקב משום רבינו הלכה מציע את המשנה ואינו מציע את הגמרא כתנאי מציע את המשנה ואינו מציע את הגמרא דברי רבי מאיר רבי יהודה בן גמליאל אומר משום רבי חנינא בן גמליאל זה וזה אסור ואמרי לה זה וזה מותר מ''ד זה וזה אסור כרבי יוחנן הסנדלר מ''ד זה וזה מותר כרבי יהודה בן בתירא אמר רב נחמן בר יצחק נהוג עלמא כהני תלת סבי כרבי אלעאי בראשית הגז כרבי יאשיה בכלאים כרבי יהודה בן בתירא בד''ת כרבי אלעאי בראשית הגז דתניא רבי אלעאי אומר ראשית הגז אינו נוהג אלא בארץ כרבי יאשיה בכלאים כדכתיב
(כרמך) לא תזרע [כרמך] כלאים רבי יאשיה אומר לעולם אינו חייב עד שיזרע חטה ושעורה וחרצן במפולת יד כרבי יהודה בן בתירא בדברי תורה דתניא רבי יהודה בן בתירא אומר אין דברי תורה מקבלין טומאה כי אתא זעירי אמר בטלוה לטבילותא ואמרי לה בטלוה לנטילותא מאן דאמר בטלוה לטבילותא כרבי יהודה בן בתירא מאן דאמר בטלוה לנטילותא כי הא דרב חסדא לייט אמאן דמהדר אמיא בעידן צלותא: תנו רבנן בעל קרי שנתנו עליו תשעה קבין מים טהור נחום איש גם זו לחשה לרבי עקיבא ורבי עקיבא לחשה לבן עזאי ובן עזאי יצא ושנאה לתלמידיו בשוק פליגי בה תרי אמוראי במערבא רבי יוסי בר אבין ורבי יוסי בר זבידא חד תני שנאה וחד תני לחשה מאן דתני שנאה משום בטול תורה ומשום בטול פריה ורביה ומאן דתני לחשה שלא יהו תלמידי חכמים מצויים אצל נשותיהם כתרנגולים אמר רבי ינאי שמעתי שמקילין בה ושמעתי שמחמירין בה וכל המחמיר בה על עצמו מאריכין לו ימיו ושנותיו אמר ריב''ל מה טיבן של טובלי שחרין מה טיבן הא איהו דאמר בעל קרי אסור בדברי תורה הכי קאמר מה טיבן בארבעים סאה אפשר בתשעה קבין מה טיבן בטבילה אפשר בנתינה אמר רבי חנינא גדר גדול גדרו בה דתניא מעשה באחד שתבע אשה לדבר עבירה אמרה לו ריקא יש לך ארבעים סאה שאתה טובל בהן מיד פירש אמר להו רב הונא לרבנן רבותי מפני מה אתם מזלזלין בטבילה זו אי משום צינה אפשר במרחצאות אמר ליה רב חסדא וכי יש טבילה בחמין אמר ליה רב אדא בר אהבה קאי כוותך רבי זירא הוה יתיב באגנא דמיא בי מסותא אמר ליה לשמעיה זיל ואייתי לי תשעה קבין ושדי עלואי אמר ליה רבי חייא בר אבא למה ליה למר כולי האי והא יתיב בגווייהו אמר ליה כארבעים סאה מה ארבעים סאה בטבילה ולא בנתינה אף תשעה קבין בנתינה ולא בטבילה רב נחמן תקן חצבא בת תשעה קבין כי אתא רב דימי אמר רבי עקיבא ורבי יהודה גלוסטרא אמרו לא שנו אלא לחולה לאונסו אבל לחולה המרגיל ארבעים סאה אמר רב יוסף אתבר חצביה דרב נחמן כי אתא רבין אמר באושא הוה עובדא בקילעא דרב אושעיא אתו ושאלו לרב אסי אמר להו לא שנו אלא לחולה המרגיל אבל לחולה לאונסו פטור מכלום א''ר יוסף אצטמיד חצביה דרב נחמן מכדי כולהו אמוראי ותנאי בדעזרא קמיפלגי ונחזי עזרא היכי תקן אמר אביי עזרא תקן לבריא המרגיל מ' סאה ובריא לאונסו ט' קבין ואתו אמוראי ופליגי בחולה מר סבר חולה המרגיל כבריא המרגיל וחולה לאונסו כבריא לאונסו ומר סבר חולה המרגיל כבריא לאונסו וחולה לאונסו פטור מכלום אמר רבא נהי דתקן עזרא טבילה נתינה מי תקן והאמר מר עזרא תקן טבילה לבעלי קריין אלא אמר רבא עזרא תקן טבילה לבריא המרגיל מ' סאה ואתו רבנן והתקינו לבריא לאונסו ט' קבין ואתו אמוראי וקא מיפלגי בחולה מר סבר חולה המרגיל כבריא המרגיל וחולה לאונסו כבריא לאונסו ומר סבר לבריא המרגיל מ' סאה וחולה המרגיל כבריא לאונסו ט' קבין אבל לחולה לאונסו פטור מכלום אמר רבא הלכתא בריא המרגיל וחולה המרגיל ארבעים סאה ובריא לאונסו תשעה קבין אבל לחולה לאונסו פטור מכלום: ת''ר בעל קרי שנתנו עליו ט' קבין מים טהור בד''א לעצמו אבל לאחרים ארבעים סאה ר' יהודה אומר מ' סאה מכל מקום ר' יוחנן וריב''ל ור''א ור' יוסי בר' חנינא חד מהאי זוגא וחד מהאי זוגא ארישא חד אמר הא דאמרת במה דברים אמורים לעצמו אבל לאחרים מ' סאה לא שנו אלא לחולה המרגיל אבל לחולה לאונסו ט' קבין וחד אמר כל לאחרים אפילו חולה לאונסו עד דאיכא מ' סאה וחד מהאי זוגא וחד מהאי זוגא אסיפא חד אמר הא דאמר רבי יהודה מ' סאה מכל מקום לא שנו אלא בקרקע אבל בכלים לא וחד אמר אפי' בכלים נמי בשלמא למ''ד אפי' בכלים היינו דקתני ר' יהודה אומר מ' סאה מכל מקום אלא למ''ד בקרקע אין בכלים לא מכל מקום לאתויי מאי לאתויי מים שאובין רב פפא ורב הונא בריה דרב יהושע ורבא (ברבי) בר שמואל כריכו ריפתא בהדי הדדי א''ל רב פפא הבו לי לדידי לברוך דנפול עילואי ט' קבין אמר להו רבא (ברבי) [בר] שמואל תנינא במה דברים אמורים לעצמו אבל לאחרים מ' סאה אלא הבו לי לדידי לברוך דנפול עילואי ארבעים סאה אמר להו רב הונא הבו לי לדידי לברוך דליכא עילואי לא האי ולא האי רב חמא טביל במעלי יומא דפסחא להוציא רבים ידי חובתן ולית הלכתא כוותיה:  כא:
בעל קרי שכח היה עומד בתפלה ונזכר שהוא בעל קרי לא יפסיק אלא יקצר כב:
בעל קרי שכח ת''ר היה עומד בתפלה ונזכר שהוא בעל קרי לא יפסיק אלא יקצר היה קורא בתורה ונזכר שהוא בעל קרי אינו מפסיק ועולה אלא מגמגם וקורא ר''מ אומר אין בעל קרי רשאי לקרות בתורה יותר מג' פסוקים כב:
ברכה דאמר כל ברכה שאין בה הזכרת השם אינה ברכה שפיר אלא לר' יוחנן דאמר כל ברכה שאין בה מלכות אינה ברכה יב.
ברכה דבר המיזן אפילו סיים בדנהמא נמי יצא מאי טעמא דתמרי נמי מיזן זייני: יב.
ברכה טעימה  מטעמת אינה טעונה ברכה טעמי עד שיעור רביעתא (מסתמא זה גם קאי על ברכה). יד.
ברכות התורה  א''ר יהודה אמר שמואל השכים לשנות עד שלא קרא ק''ש צריך לברך משקרא ק''ש א''צ לברך שכבר נפטר באהבה רבה אמר רב הונא למקרא צריך לברך ולמדרש א''צ לברך ור' אלעזר אמר למקרא ולמדרש צריך לברך למשנה א''צ לברך ור' יוחנן אמר אף למשנה נמי צריך לברך [אבל לתלמוד א''צ לברך] ורבא אמר אף לתלמוד צריך (לחזור ו) לברך דאמר רב חייא בר אשי זימנין סגיאין הוה קאימנא קמיה דרב לתנויי פרקין בספרא דבי רב הוה מקדים וקא משי ידיה ובריך ומתני לן פרקין. מאי מברך א''ר יהודה אמר שמואל אשר קדשנו במצותיו וצונו לעסוק בדברי תורה ור' יוחנן מסיים בה הכי הערב נא ה' אלהינו את דברי תורתך בפינו ובפיפיות עמך בית ישראל ונהיה אנחנו וצאצאינו וצאצאי עמך בית ישראל כלנו יודעי שמך ועוסקי תורתך ברוך אתה ה' המלמד תורה לעמו ישראל ורב המנונא אמר אשר בחר בנו מכל העמים ונתן לנו את תורתו ברוך אתה ה' נותן התורה אמר רב המנונא זו היא מעולה שבברכות הלכך לימרינהו לכולהו: יא:
ברכות כוונה פשיטא היכא דקא נקיט כסא דחמרא בידיה וקסבר דשכרא הוא ופתח ומברך אדעתא דשכרא וסיים בדחמרא יצא דאי נמי אם אמר שהכל נהיה בדברו יצא דהא תנן על כולם אם אמר שהכל נהיה בדברו יצא אלא היכא דקא נקיט כסא דשכרא בידיה וקסבר דחמרא הוא פתח ובריך אדעתא דחמרא וסיים בדשכרא מאי בתר עיקר ברכה אזלינן או בתר חתימה אזלינן ת''ש שחרית פתח ביוצר אור וסיים במעריב ערבים לא יצא פתח במעריב ערבים וסיים ביוצר אור יצא ערבית פתח במעריב ערבים וסיים ביוצר אור לא יצא פתח ביוצר אור וסיים במעריב ערבים יצא כללו של דבר הכל הולך אחר החתום שאני התם דקאמר ברוך יוצר המאורות הניחא לרב דאמר כל ברכה שאין בה הזכרת השם אינה ברכה שפיר אלא לר' יוחנן דאמר כל ברכה שאין בה מלכות אינה ברכה מאי איכא למימר אלא כיון דאמר רבה בר עולא כדי להזכיר מדת יום בלילה ומדת לילה ביום כי קאמר ברכה ומלכות מעיקרא אתרוייהו קאמר ת''ש מסיפא כללו של דבר הכל הולך אחר החתום כללו של דבר לאתויי מאי לאו לאתויי הא דאמרן לא לאתויי נהמא ותמרי ה''ד אילימא דאכל נהמא וקסבר דתמרי אכל ופתח אדעתא דתמרי וסיים בדנהמא היינו בעיין לא צריכא כגון דאכל תמרי וקסבר נהמא אכל ופתח בדנהמא וסיים בדתמרי [יצא] דאפילו סיים בדנהמא נמי יצא מאי טעמא דתמרי נמי מיזן זייני:  יב.
ברכות מקום שאמרו להאריך אינו רשאי לקצר לקצר אינו רשאי להאריך לחתום אינו רשאי שלא לחתום שלא לחתום אינו רשאי לחתום יא
ברכות שמע אמר ר' זריקא א''ר אמי אמר ר' שמעון בן לקיש זאת אומרת ברכות אין מעכבות זו את זו (אולי) מאי ברכות אין מעכבות זו את זו סדר ברכות יא:
** מתני' גמ' {שמות טז-ח}
ברכת המזון
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
ברכת המזון א''ל רבינא לרבא נשים בברכת המזון דאורייתא או דרבנן למאי נפקא מינה לאפוקי רבים ידי חובתן אי אמרת (בשלמא) דאורייתא אתי דאורייתא ומפיק דאורייתא (אלא אי) אמרת דרבנן הוי שאינו מחוייב בדבר וכל שאינו מחוייב בדבר אינו מוציא את הרבים ידי חובתן מאי ת''ש באמת אמרו בן מברך לאביו ועבד מברך לרבו ואשה מברכת לבעלה אבל אמרו חכמים תבא מארה לאדם שאשתו ובניו מברכין לו אי אמרת בשלמא דאורייתא אתי דאורייתא ומפיק דאורייתא אלא אי אמרת דרבנן אתי דרבנן ומפיק דאורייתא ולטעמיך קטן בר חיובא הוא אלא הכי במאי עסקינן כגון שאכל שיעורא דרבנן דאתי דרבנן ומפיק דרבנן: כ:
ברכת המזון אמר ר' יוחנן למדנו ברכת התורה לאחריה מן ברכת המזון מקל וחומר וברכת המזון לפניה מן ברכת התורה מקל וחומר ברכת התורה לאחריה מן ברכת המזון מקל וחומר ומה מזון שאין טעון לפניו טעון לאחריו תורה שטעונה לפניה אינו דין שטעונה לאחריה וברכת המזון לפניה מן ברכת התורה מק''ו ומה תורה שאין טעונה לאחריה טעונה לפניה מזון שהוא טעון לאחריו אינו דין שיהא טעון לפניו איכא למפרך מה למזון שכן נהנה ומה לתורה שכן חיי עולם ועוד תנן על המזון מברך לאחריו ואינו מברך לפניו תיובתא: כא.
** {דברים ח-י}
ברכת המזון אמר רב יהודה מנין לברכת המזון לאחריה מן התורה שנאמר
ואכלת ושבעת וברכת כא.
ברכת המזון ועל המזון [בעל קרי] מברך לאחריו ואינו מברך לפניו רבי יהודה אומר מברך לפניהם ולאחריהם כ:
ברכת התורה אמר ר' יוחנן למדנו ברכת התורה לאחריה מן ברכת המזון מקל וחומר וברכת המזון לפניה מן ברכת התורה מקל וחומר ברכת התורה לאחריה מן ברכת המזון מקל וחומר ומה מזון שאין טעון לפניו טעון לאחריו תורה שטעונה לפניה אינו דין שטעונה לאחריה וברכת המזון לפניה מן ברכת התורה מק''ו ומה תורה שאין טעונה לאחריה טעונה לפניה מזון שהוא טעון לאחריו אינו דין שיהא טעון לפניו איכא למפרך מה למזון שכן נהנה ומה לתורה שכן חיי עולם ועוד תנן על המזון מברך לאחריו ואינו מברך לפניו תיובתא: כא.
** מתני' {דברים לב-ג}
ברכת התורה
מנין לברכת התורה לפניה מן התורה שנאמר
כי שם ה' אקרא הבו גדל לאלהינו כא.
** {דברים ו-ז} {תהילים נא-יז} {תהילים יט-טו}
גאולה לתפלה אמר ר' יוחנן איזהו בן העולם הבא זה הסומך גאולה לתפלה של ערבית רבי יהושע בן לוי אומר תפלות באמצע תקנום במאי קא מפלגי אי בעית אימא קרא איבע''א סברא איבע''א סברא דר' יוחנן סבר גאולה מאורתא נמי הוי אלא גאולה מעלייתא לא הויא אלא עד צפרא ור' יהושע בן לוי סבר כיון דלא הויא אלא מצפרא לא הויא גאולה מעלייתא ואב''א קרא ושניהם מקרא אחד דרשו דכתיב
בשכבך ובקומך ר' יוחנן סבר מקיש שכיבה לקימה מה קימה ק''ש ואח''כ תפלה אף שכיבה נמי ק''ש ואח''כ תפלה ר' יהושע בן לוי סבר מקיש שכיבה לקימה מה קימה ק''ש סמוך למטתו אף שכיבה נמי ק''ש סמוך למטתו מתיב מר בריה דרבינא בערב מברך שתים לפניה ושתים לאחריה ואי אמרת בעי לסמוך הא לא קא סמך גאולה לתפלה דהא בעי למימר השכיבנו אמרי כיון דתקינו רבנן השכיבנו כגאולה אריכתא דמיא דאי לא תימא הכי שחרית היכי מצי סמיך והא אמר רבי יוחנן בתחלה אומר
ה' שפתי תפתח ולבסוף הוא אומר
יהיו לרצון אמרי פי אלא התם כיון דתקינו רבנן למימר ה' שפתי תפתח כתפלה אריכתא דמיא הכא נמי כיון דתקינו רבנן למימר השכיבנו כגאולה אריכתא דמיא: ד:
** {ויקרא כב-לב} {במדבר טז-כא}
דבר שבקדושה וכן אמר רב אדא בר אהבה מנין שאין היחיד אומר קדושה שנאמר
ונקדשתי בתוך בני ישראל כל דבר שבקדושה לא יהא פחות מעשרה מאי משמע דתני רבנאי אחוה דרבי חייא בר אבא אתיא תוך תוך כתיב הכא ונקדשתי בתוך בני ישראל וכתיב התם
הבדלו מתוך העדה הזאת מה להלן עשרה אף כאן עשרה  כא:
** דף טו - ב {דברים כז-ט}
דילמא רבי יהודה היא ולכתחלה הוא דלא הא דיעבד שפיר דמי לא ס''ד דקתני חרש דומיא דשוטה וקטן מה שוטה וקטן דיעבד נמי לא אף חרש דיעבד נמי לא ודילמא הא כדאיתא והא כדאיתא ומי מצית לאוקמה כרבי יהודה והא מדקתני סיפא רבי יהודה מכשיר בקטן מכלל דרישא לאו רבי יהודה היא ודילמא כולה ר' יהודה היא ותרי גווני קטן וחסורי מחסרא והכי קתני הכל כשרין לקרות את המגילה חוץ מחש''ו בד''א בקטן שלא הגיע לחנוך אבל קטן שהגיע לחנוך אפילו לכתחלה כשר דברי רבי יהודה שרבי יהודה מכשיר בקטן במאי אוקימתא כר''י ודיעבד אין לכתחלה לא אלא הא דתני ר''י בריה דר' שמעון בן פזי חרש המדבר ואינו שומע תורם לכתחלה מני לא ר' יהודה ולא ר' יוסי אי ר' יהודה דיעבד אין לכתחלה לא אי ר' יוסי דיעבד נמי לא אלא מאי ר' יהודה ואפילו לכתחלה נמי אלא הא דתניא לא יברך אדם ברכת המזון בלבו ואם בירך יצא מני לא ר' יהודה ולא ר' יוסי אי רבי יהודה הא אמר אפי' לכתחלה נמי ואי ר' יוסי הא אמר אפי' דיעבד נמי לא לעולם ר' יהודה היא ואפילו לכתחלה נמי ולא קשיא הא דידיה הא דרביה דתניא א''ר יהודה משום ר' אלעזר בן עזריה הקורא את שמע צריך שישמיע לאזנו שנאמר שמע ישראל אמר לו ר' מאיר הרי הוא אומר אשר אנכי מצוך היום על לבבך אחר כונת הלב הן הן הדברים השתא דאתית להכי אפי' תימא ר' יהודה כרביה ס''ל ולא קשיא הא ר' יהודה הא רבי מאיר א''ר חסדא אמר רב שילא הלכה כרבי יהודה שאמר משום רבי אלעזר בן עזריה והלכה כרבי יהודה וצריכא דאי אשמעינן הלכה כר' יהודה הוה אמינא אפילו לכתחלה קמ''ל הלכה כר' יהודה שאמר משום ר' אלעזר בן עזריה ואי אשמעינן הלכה כרבי יהודה שאמר משום ר' אלעזר בן עזריה הוה אמינא צריך ואין לו תקנה קמ''ל הלכה כרבי יהודה אמר רב יוסף מחלוקת בק''ש אבל בשאר מצות דברי הכל לא יצא דכתיב
הסכת ושמע ישראל מיתיבי לא יברך אדם ברכת המזון בלבו ואם בירך יצא אלא אי אתמר הכי אתמר אמר רב יוסף מחלוקת בק''ש דכתיב שמע ישראל אבל בשאר מצות דברי הכל יצא והכתיב הסכת ושמע ישראל ההוא בדברי תורה כתיב: טו
** {תהילים צב-ג}
הז’ גדלות ה’ אמר רבה בר חיננא סבא משמיה דרב כל שלא אמר אמת ויציב שחרית ואמת ואמונה ערבית לא יצא ידי חובתו שנאמר
להגיד בבקר חסדך ואמונתך בלילות: יב.
הז’ יצ”מ א''ל רב לר' חייא לא חזינא ליה לרבי דמקבל עליה מלכות שמים אמר ליה בר פחתי בשעה שמעביר ידיו על פניו מקבל עליו עול מלכות שמים חוזר וגומרה או אינו חוזר וגומרה בר קפרא אומר אינו חוזר וגומרה רבי שמעון ברבי אומר חוזר וגומרה א''ל בר קפרא לר''ש ברבי בשלמא לדידי דאמינא אינו חוזר וגומרה היינו דמהדר רבי אשמעתא דאית בה יציאת מצרים אלא לדידך דאמרת חוזר וגומרה למה ליה לאהדורי כדי להזכיר יציאת מצרים בזמנה  יג:
הז’ יצ”מ והא בעי לאדכורי יציאת מצרים דאמר הכי מודים אנחנו לך ה' אלהינו שהוצאתנו מארץ מצרים ופדיתנו מבית עבדים ועשית לנו נסים וגבורות על הים ושרנו לך: יד:
הלל הפסק בעא מיניה אחי תנא דבי רבי חייא מרבי חייא בהלל ובמגילה מהו שיפסיק אמרינן ק''ו ק''ש דאורייתא פוסק הלל דרבנן מבעיא או דלמא פרסומי ניסא עדיף א''ל פוסק ואין בכך כלום אמר רבה ימים שהיחיד גומר בהן את ההלל בין פרק לפרק פוסק באמצע הפרק אינו פוסק וימים שאין היחיד גומר בהן את ההלל אפי' באמצע הפרק פוסק איני והא רב בר שבא איקלע לגביה דרבינא וימים שאין היחיד גומר את ההלל הוה ולא פסיק ליה שאני רב בר שבא דלא חשיב עליה דרבינא: יד.
הרהור כדבור אמר רבינא זאת אומרת הרהור כדבור דמי דאי סלקא דעתך לאו כדבור דמי למה מהרהר אלא מאי הרהור כדבור דמי יוציא בשפתיו כדאשכחן בסיני ורב חסדא אמר הרהור לאו כדבור דמי דאי סלקא דעתך הרהור כדבור דמי יוציא בשפתיו אלא מאי הרהור לאו כדבור דמי למה מהרהר אמר רבי אלעזר כדי שלא יהו כל העולם עוסקין בו והוא יושב ובטל ונגרוס בפרקא אחרינא אמר רב אדא בר אהבה בדבר שהצבור עוסקין בו והרי תפלה דדבר שהצבור עסוקין בו ותנן היה עומד בתפלה ונזכר שהוא בעל קרי לא יפסיק אלא יקצר טעמא דאתחיל הא לא אתחיל לא יתחיל שאני תפלה דלית בה מלכות שמים והרי ברכת המזון לאחריו דלית בה מלכות שמים ותנן על המזון מברך לאחריו ואינו מברך לפניו אלא ק''ש וברכת המזון דאורייתא ותפלה דרבנן: כ:
ורידים כרבי יהודה [אמר ריב”ל לבניו] והזהרו בורידין כרבי יהודה דתנן רבי יהודה אומר עד שישחוט את הורידין ח:
חורבה ת''ר מפני שלשה דברים אין נכנסין לחורבה מפני חשד מפני המפולת ומפני המזיקין. מפני חשד ותיפוק ליה משום מפולת בחדתי ותיפוק ליה משום מזיקין בתרי אי בתרי חשד נמי ליכא בתרי ופריצי. מפני המפולת ותיפוק ליה משום חשד ומזיקין בתרי וכשרי. מפני המזיקין ותיפוק ליה מפני חשד ומפולת בחורבה חדתי ובתרי וכשרי אי בתרי מזיקין נמי ליכא במקומן חיישינן ואב''א לעולם בחד ובחורבה חדתי דקאי בדברא דהתם משום חשד ליכא דהא אשה בדברא לא שכיחא ומשום מזיקין איכא: ג
חצות זמן ולא זו בלבד אמרו אלא כל מה שאמרו חכמים עד חצות מצותן עד שיעלה עמוד השחר הקטר חלבים ואברים מצותן עד שיעלה עמוד השחר וכל הנאכלים ליום אחד מצותן עד שיעלה עמוד השחר א''כ למה אמרו חכמים עד חצות כדי להרחיק אדם מן העבירה: ב.
ט’ אב מלאכה מקום שנהגו לעשות מלאכה בתשעה באב עושין מקום שנהגו שלא לעשות אין עושין וכל מקום תלמידי חכמים בטלים רבן שמעון בן גמליאל אומר לעולם יעשה כל אדם את עצמו כתלמיד חכם קשיא דרבנן אדרבנן קשיא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל אמר רבי יוחנן מוחלפת השיטה רב שישא בריה דרב אידי אמר לעולם לא תחליף דרבנן אדרבנן לא קשיא ק''ש כיון דכ''ע קא קרו ואיהו נמי קרי לא מיחזי כיוהרא הכא כיון דכולי עלמא עבדי מלאכה ואיהו לא קא עביד מיחזי כיוהרא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל לא קשיא התם בכונה תליא מילתא ואנן סהדי דלא מצי לכווני דעתיה אבל הכא הרואה אומר מלאכה הוא דאין לו פוק חזי כמה בטלני איכא בשוקא:  יז:
טומאה תנור עכנאי חתכו חוליות ונתן חול בין חוליא לחוליא ר' אליעזר מטהר וחכמים מטמאים וזהו תנורו של עכנאי יט.
טעימה בעי מיניה אשיאן תנא דבי ר' אמי מר' אמי השרוי בתענית מהו שיטעום אכילה ושתיה קביל עליה והא ליכא או דילמא הנאה קביל עליה והא איכא א''ל טועם ואין בכך כלום תניא נמי הכי מטעמת אינה טעונה ברכה והשרוי בתענית טועם ואין בכך כלום עד כמה ר' אמי ור' אסי טעמי עד שיעור רביעתא:  יד.
יוהרא חתן אם רוצה לקרות וכו': למימרא דרבן שמעון בן גמליאל חייש ליוהרא ורבנן לא חיישי ליוהרא והא איפכא שמעינן להו דתנן מקום שנהגו לעשות מלאכה בתשעה באב עושין מקום שנהגו שלא לעשות אין עושין וכל מקום תלמידי חכמים בטלים רבן שמעון בן גמליאל אומר לעולם יעשה כל אדם את עצמו כתלמיד חכם קשיא דרבנן אדרבנן קשיא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל אמר רבי יוחנן מוחלפת השיטה רב שישא בריה דרב אידי אמר לעולם לא תחליף דרבנן אדרבנן לא קשיא ק''ש כיון דכ''ע קא קרו ואיהו נמי קרי לא מיחזי כיוהרא הכא כיון דכולי עלמא עבדי מלאכה ואיהו לא קא עביד מיחזי כיוהרא דרבן שמעון בן גמליאל אדרבן שמעון בן גמליאל לא קשיא התם בכונה תליא מילתא ואנן סהדי דלא מצי לכווני דעתיה אבל הכא הרואה אומר מלאכה הוא דאין לו פוק חזי כמה בטלני איכא בשוקא:  יז:
יוהרא חתן אם רוצה לקרות קרית שמע לילה הראשון קורא רבן שמעון בן גמליאל אומר לא כל הרוצה ליטול את השם יטול:  טז:
כלל פסק יחיד ורבים הלכה כרבים (נגד רבן גמליאל) ט.
** {נחמיה ד-טו} {נחמיה ד-טז}
לילה זמן ואע''פ שאין ראיה לדבר זכר לדבר שנאמר
ואנחנו עושים במלאכה וחצים מחזיקים ברמחים מעלות השחר עד צאת הכוכבים ואומר
והיו לנו הלילה משמר והיום מלאכה מאי ואומר וכי תימא מכי ערבא שמשא ליליא הוא ואינהו דמחשכי ומקדמי ת''ש והיו לנו הלילה משמר והיום מלאכה ב:
לילה זמן תניא ר''ש בן יוחי אומר פעמים שאדם קורא ק''ש שתי פעמים בלילה אחת קודם שיעלה עמוד השחר ואחת לאחר שיעלה עמוד השחר ויוצא בהן ידי חובתו אחת של יום ואחת של לילה. הא גופא קשיא אמרת פעמים שאדם קורא קרית שמע שתי פעמים בלילה אלמא לאחר שיעלה עמוד השחר ליליא הוא והדר תני יוצא בהן ידי חובתו אחת של יום ואחת של לילה אלמא יממא הוא לא לעולם ליליא הוא והא דקרי ליה יום דאיכא אינשי דקיימי בההיא שעתא אמר רב אחא בר חנינא אמר רבי יהושע בן לוי הלכה כרבי שמעון בן יוחי איכא דמתני להא דרב אחא בר חנינא אהא דתניא רבי שמעון בן יוחי אומר משום ר' עקיבא פעמים שאדם קורא קרית שמע שתי פעמים ביום אחת קודם הנץ החמה ואחת לאחר הנץ החמה ויוצא בהן ידי חובתו אחת של יום ואחת של לילה הא גופא קשיא אמרת פעמים שאדם קורא ק''ש שתי פעמים ביום אלמא קודם הנץ החמה יממא הוא והדר תני יוצא בהן ידי חובתו אחת של יום ואחת של לילה אלמא ליליא הוא לא לעולם יממא הוא והאי דקרו ליה ליליא דאיכא אינשי דגנו בההיא שעתא אמר רבי אחא ברבי חנינא אמר רבי יהושע בן לוי הלכה כר''ש שאמר משום רבי עקיבא. אמר רבי זירא ובלבד שלא יאמר השכיבנו. כי אתא רב יצחק בר יוסף אמר הא דרבי אחא ברבי חנינא אמר ריב''ל לאו בפירוש איתמר אלא מכללא איתמר דההוא זוגא דרבנן דאשתכור בהלולא דבריה דר' יהושע בן לוי אתו לקמיה דריב''ל אמר כדאי הוא ר''ש לסמוך עליו בשעת הדחק: ח:
לשון כל התורה  למימרא דסבר רבי דכל התורה כולה בכל לשון נאמרה דאי סלקא דעתך בלשון הקודש נאמרה והיו דכתב רחמנא למה לי איצטריך משום דכתיב שמע למימרא דסברי רבנן דכל התורה כולה בלשון הקודש נאמרה דאי סלקא דעתך בכל לשון נאמרה שמע דכתב רחמנא למה לי איצטריך משום דכתיב והיו: יג.
מגילה הפסק בעא מיניה אחי תנא דבי רבי חייא מרבי חייא בהלל ובמגילה מהו שיפסיק אמרינן ק''ו ק''ש דאורייתא פוסק הלל דרבנן מבעיא או דלמא פרסומי ניסא עדיף א''ל פוסק ואין בכך כלום יד.
** מתני' גמ'
מזוזה
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן:
מתפלל בדרך באותה שעה למדתי ממנו שלשה דברים למדתי שאין נכנסין לחורבה ולמדתי שמתפללין בדרך ולמדתי שהמתפלל בדרך מתפלל תפלה קצרה ג.
נטילת ידים א''ל רבינא לרבא חזי מר האי צורבא מרבנן דאתא ממערבא ואמר מי שאין לו מים לרחוץ ידיו מקנח ידיו בעפר ובצרור ובקסמית א''ל שפיר קאמר מי כתיב ארחץ במים בנקיון כתיב כל מידי דמנקי דהא רב חסדא לייט אמאן דמהדר אמיא בעידן צלותא והני מילי לק''ש אבל לתפלה מהדר ועד כמה עד פרסה והנ''מ לקמיה אבל לאחוריה אפילו מיל אינו חוזר [ומינה] מיל הוא דאינו חוזר הא פחות ממיל חוזר:  טו.
** {תהילים כו-ו}
נטילת ידים ואמר רבי יוחנן הרוצה שיקבל עליו עול מלכות שמים שלמה יפנה ויטול ידיו ויניח תפילין ויקרא ק''ש ויתפלל וזו היא מלכות שמים שלמה א''ר חייא בר אבא א''ר יוחנן כל הנפנה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל מעלה עליו הכתוב כאלו בנה מזבח והקריב עליו קרבן דכתיב
ארחץ בנקיון כפי ואסובבה את מזבחך ה' א''ל רבא לא סבר לה מר כאילו טבל דכתיב ארחץ [בנקיון] ולא כתב ארחיץ [כפי]  טו.
נידוי כל המתנדה ומת בנדויו ב''ד סוקלין את ארונו יט.
** {תהילים כו-ו}
נפנה נטילת ידים וכו’ ואמר רבי יוחנן הרוצה שיקבל עליו עול מלכות שמים שלמה יפנה ויטול ידיו ויניח תפילין ויקרא ק''ש ויתפלל וזו היא מלכות שמים שלמה א''ר חייא בר אבא א''ר יוחנן כל הנפנה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל מעלה עליו הכתוב כאלו בנה מזבח והקריב עליו קרבן דכתיב
ארחץ בנקיון כפי ואסובבה את מזבחך ה' א''ל רבא לא סבר לה מר כאילו טבל דכתיב ארחץ [בנקיון] ולא כתב ארחיץ [כפי]  טו.
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
נשים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
נשים ברכת המזון א''ל רבינא לרבא נשים בברכת המזון דאורייתא או דרבנן למאי נפקא מינה לאפוקי רבים ידי חובתן אי אמרת (בשלמא) דאורייתא אתי דאורייתא ומפיק דאורייתא (אלא אי) אמרת דרבנן הוי שאינו מחוייב בדבר וכל שאינו מחוייב בדבר אינו מוציא את הרבים ידי חובתן מאי ת''ש באמת אמרו בן מברך לאביו ועבד מברך לרבו ואשה מברכת לבעלה אבל אמרו חכמים תבא מארה לאדם שאשתו ובניו מברכין לו אי אמרת בשלמא דאורייתא אתי דאורייתא ומפיק דאורייתא אלא אי אמרת דרבנן אתי דרבנן ומפיק דאורייתא ולטעמיך קטן בר חיובא הוא אלא הכי במאי עסקינן כגון שאכל שיעורא דרבנן דאתי דרבנן ומפיק דרבנן: כ:
** {שמות כ-ח} {דברים ה-יב}
נשים קידוש מר רב אדא בר אהבה נשים חייבות בקדוש היום דבר תורה אמאי מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות אמר אביי מדרבנן א''ל רבא והא דבר תורה קאמר ועוד כל מצות עשה נחייבינהו מדרבנן אלא אמר רבא אמר קרא
זכור
ושמור כל שישנו בשמירה ישנו בזכירה והני נשי הואיל ואיתנהו בשמירה איתנהו בזכירה כ:
סוטה אין משקין לא את הגיורת ולא את המשוחררת וחכמים אומרים משקין ואמרו לו מעשה בכרכמית שפחה משוחררת בירושלים והשקוה שמעיה ואבטליון ואמר להם דוגמא השקוה יט.
** {במדבר ה-כג}
סוטה מה מוחק גבי סוטה אלות כותב צואות אינו כותב והתם הוא דכתיב
וכתב את האלות האלה טו:
סוכה דתנן מי שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ב''ש פוסלין וב''ה מכשירין אמרו להם ב''ה לב''ש מעשה שהלכו זקני ב''ש וזקני ב''ה לבקר את ר' יוחנן בן החורנית מצאוהו שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ולא אמרו לו כלום אמרו להם משם ראיה אף הם אמרו לו א''כ היית נוהג לא קיימת מצות סוכה מימיך יא.
** {שמות כב-יז} {דברים כג-א}
סמוכים אמר רב יוסף אפילו מאן דלא דריש סמוכים בכל התורה במשנה תורה דריש דהא רבי יהודה לא דריש סמוכין בכל התורה כולה ובמשנה תורה דריש ובכל התורה כולה מנא לן דלא דריש דתניא בן עזאי אומר נאמר
מכשפה לא תחיה ונאמר כל שוכב עם בהמה מות יומת סמכו ענין לו לומר מה שוכב עם בהמה בסקילה אף מכשפה נמי בסקילה אמר ליה ר' יהודה וכי מפני שסמכו ענין לו נוציא לזה לסקילה אלא אוב וידעוני בכלל כל המכשפים היו ולמה יצאו להקיש להן ולומר לך מה אוב וידעוני בסקילה אף מכשפה בסקילה ובמשנה תורה מנא לן דדריש דתניא רבי אליעזר אומר נושא אדם אנוסת אביו ומפותת אביו אנוסת בנו ומפותת בנו ר' יהודה אוסר באנוסת אביו ובמפותת אביו ואמר רב גידל אמר רב מאי טעמא דר' יהודה דכתיב
לא יקח איש את אשת אביו ולא יגלה (את) כנף אביו כנף שראה אביו לא יגלה וממאי דבאנוסת אביו כתיב דסמיך ליה ונתן האיש השוכב עמה וגו' אמרי אין במשנה תורה דריש כא:
** {תהילים קיא-ח}
סמוכים א''ר יוחנן סמוכין מן התורה מנין שנא'
סמוכים לעד לעולם עשוים באמת וישר י. (אגב, אם נאמר שזה מקרו בדרך כלל, צריך לומר שדרשות אגדתא הם ממש דרשות)
ספר תורה ולא ישתין בהן מים ולא יישן בהן לא שינת קבע ולא שינת עראי. כג.
ספר תורה כבוד רב אחאי איעסק ליה לבריה בי רב יצחק בר שמואל בר מרתא עייליה לחופה ולא הוה מסתייעא מילתא אזל בתריה לעיוני חזא ספר תורה דמנחא אמר להו איכו השתא לא אתאי סכנתון לברי דתניא בית שיש בו ספר תורה או תפילין אסור לשמש בו את המטה עד שיוציאם או שיניחם כלי בתוך כלי אמר אביי לא שנו אלא בכלי שאינו כליין אבל בכלי שהוא כליין אפילו עשרה מאני כחד מאנא דמי אמר רבא גלימא אקמטרא ככלי בתוך כלי דמי. אמר רבי יהושע בן לוי ס''ת צריך לעשות לו מחיצה עשרה מר זוטרא איקלע לבי רב אשי חזייה לדוכתיה דמר בר רב אשי דמנח ביה ספר תורה ועביד ליה מחיצה עשרה אמר ליה כמאן כרבי יהושע בן לוי אימר דאמר רבי יהושע בן לוי דלית ליה ביתא אחרינא מר הא אית ליה ביתא אחרינא אמר ליה לאו אדעתאי: כה:
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
עבדים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
עבדים תנחומים וכשמת טבי עבדו קבל עליו תנחומין אמרו לו תלמידיו למדתנו רבינו שאין מקבלין תנחומין על העבדים אמר להם אין טבי עבדי כשאר כל העבדים כשר היה טז:
עבדים ת''ר עבדים ושפחות אין עומדין עליהם בשורה ואין אומרים עליהם ברכת אבלים ותנחומי אבלים מעשה ומתה שפחתו של רבי אליעזר נכנסו תלמידיו לנחמו כיון שראה אותם עלה לעלייה ועלו אחריו נכנס לאנפילון נכנסו אחריו נכנס לטרקלין נכנסו אחריו אמר להם כמדומה אני שאתם נכוים בפושרים עכשיו אי אתם נכוים אפילו בחמי חמין לא כך שניתי לכם עבדים ושפחות אין עומדין עליהם בשורה ואין אומרים עליהם ברכת אבלים ולא תנחומי אבלים אלא מה אומרים עליהם כשם שאומרים לו לאדם על שורו ועל חמורו שמתו המקום ימלא לך חסרונך כך אומרים לו על עבדו ועל שפחתו המקום ימלא לך חסרונך תניא אידך עבדים ושפחות אין מספידין אותן ר' יוסי אומר אם עבד כשר הוא אומרים עליו הוי איש טוב ונאמן ונהנה מיגיעו אמרו לו אם כן מה הנחת לכשרים: טז:
** {יחזקאל כד-יז}
עוסק במצוה בשבתך בביתך פרט לעוסק במצוה ובלכתך בדרך פרט לחתן מכאן אמרו הכונס את הבתולה פטור ואת האלמנה חייב מאי משמע אמר רב פפא כי דרך מה דרך רשות אף כל רשות מי לא עסקינן דקא אזיל לדבר מצוה ואפילו הכי אמר רחמנא לקרי אם כן לכתוב רחמנא בשבת ובלכת מאי בשבתך ובלכתך בשבת דידך ובלכת דידך הוא דמחייבת הא דמצוה פטירת אי הכי אפילו כונס את האלמנה נמי האי טריד והאי לא טריד אי משום טרדא אפילו טבעה ספינתו בים נמי וכי תימא ה''נ אלמה א''ר אבא בר זבדא אמר רב אבל חייב בכל המצות האמורות בתורה חוץ מן התפילין שהרי נאמר בהם פאר שנאמר
פארך חבוש עליך התם טריד טרדא דמצוה הכא טריד טרדא דרשות וב''ש ההוא מבעי להו פרט לשלוחי מצוה יא.
עוסק במצוה החופר כוך למת בקבר פטור מק''ש ומן התפלה ומן התפילין ומכל מצות האמורות בתורה הגיע זמן ק''ש עולה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל  יד:
עוסק במצוה ושאי המטה וחלופיהן וחלופי חלופיהן את שלפני המטה ואת שלאחר המטה את שלפני המטה צורך בהם פטורים ואת שלאחר המטה צורך בהם חייבין ואלו ואלו פטורים מן התפלה קברו את המת וחזרו אם יכולין להתחיל ולגמור עד שלא יגיעו לשורה יתחילו ואם לאו לא יתחילו העומדים בשורה הפנימיים פטורים והחיצונים חייבים יז:
עוסק במצווה חתן פטור מק''ש לילה הראשונה ועד מוצאי שבת אם לא עשה מעשה ומעשה בר''ג שנשא אשה וקרא לילה הראשונה אמרו לו תלמידיו למדתנו רבינו שחתן פטור מק''ש אמר להם איני שומע לכם לבטל הימני מלכות שמים אפי' שעה אחת  טו.
עוסק במצווה ת''ר שורה הרואה פנימה פטורה ושאינה רואה פנימה חייבת רבי יהודה אומר הבאים מחמת האבל פטורין מחמת עצמן חייבין: יט:
** {ירמיה כז-כב}
עלייה מבבל רבי אבא הוה קא משתמיט מיניה דרב יהודה דהוה קא בעי למיסק לארעא דישראל דאמר רב יהודה כל העולה מבבל לא''י עובר בעשה שנאמר
בבלה יובאו ושמה יהיו עד יום פקדי אותם נאם ה'  כד:
** {יחזקאל טז-ז}
ערוה (יש לדון אם רק לשמע) בעי מיניה רב יוסף בריה דרב נחוניא מרב יהודה שנים שישנים במטה אחת מהו שזה יחזיר פניו ויקרא ק''ש וזה יחזיר פניו ויקרא ק''ש א''ל הכי אמר שמואל ואפילו אשתו עמו מתקיף לה רב יוסף אשתו ולא מיבעיא אחר אדרבה אשתו כגופו אחר לאו כגופו מיתיבי שנים שישנים במטה אחת זה מחזיר פניו וקורא וזה מחזיר פניו וקורא ותניא אחריתי הישן במטה ובניו ובני ביתו בצדו הרי זה לא יקרא ק''ש אא''כ היתה טלית מפסקת ביניהן ואם היו בניו ובני ביתו קטנים מותר בשלמא לרב יוסף לא קשיא הא באשתו הא באחר אלא לשמואל קשיא אמר לך שמואל לרב יוסף מי ניחא והתניא היה ישן במטה ובניו ובני ביתו במטה לא יקרא ק''ש אא''כ היתה טליתו מפסקת ביניהן אלא מאי אית לך למימר אשתו לרב יוסף תנאי היא לדידי נמי תנאי היא: אמר מר זה מחזיר פניו וקורא ק''ש והא איכא עגבות מסייע ליה לרב הונא דא''ר הונא עגבות אין בהם משום ערוה לימא מסייע ליה לרב הונא האשה יושבת וקוצה לה חלתה ערומה מפני שיכולה לכסות פניה בקרקע אבל לא האיש תרגמה רב נחמן בר יצחק כגון שהיו פניה טוחות בקרקע: אמר מר אם היו בניו ובני ביתו קטנים מותר ועד כמה אמר רב חסדא תינוקת בת שלש שנים ויום אחד ותינוק בן ט' שנים ויום אחד איכא דאמרי תינוקת בת י''א שנה ויום אחד ותינוק בן שתים עשרה שנה ויום אחד אידי ואידי עד כדי
שדים נכונו ושערך צמח א''ל רב כהנא לרב אשי התם אמר רבא אע''ג דתיובתא דשמואל הלכתא כוותיה דשמואל הכא מאי אמר ליה אטו כולהו בחדא מחתא מחתינהו אלא היכא דאיתמר איתמר והיכא דלא איתמר לא איתמר כד.
ערוה עגבות רב הונא עגבות אין בהם משום ערוה  כד.
** {שיר השירים ב-יד}
ערוה קול אמר שמואל קול באשה ערוה שנא'
כי קולך ערב ומראך נאוה כד.
** {ישעיה מז-ב} {ישעיה מז-ג}
ערוה שוק אמר רב חסדא שוק באשה ערוה שנאמר
גלי שוק עברי נהרות וכתיב
תגל ערותך וגם תראה חרפתך  כד.
** {שיר השירים ד-א}
ערוה שער  אמר רב ששת שער באשה ערוה שנא'
שערך כעדר העזים: כד.
ערוה שער א''ל רב מרי לרב פפא שער יוצא בבגדו מהו קרא עליה שער שער: כד.
ערווה טפח א''ר יצחק טפח באשה ערוה למאי אילימא לאסתכולי בה והא א''ר ששת למה מנה הכתוב תכשיטין שבחוץ עם תכשיטין שבפנים לומר לך כל המסתכל באצבע קטנה של אשה כאילו מסתכל במקום התורף אלא באשתו ולק''ש כד.
** {שמות יב-ח} {שמות יב-יב} {שמות יב-יא} {שמות יב-י} {דברים טז-ו} {דברים טז-א} {במדבר לג-ג}
פסח זמן אכילה ואילו אכילת פסחים לא קתני ורמינהי ק''ש ערבית והלל בלילי פסחים ואכילת פסח מצותן עד שיעלה עמוד השחר אמר רב יוסף לא קשיא הא ר' אלעזר בן עזריה הא רבי עקיבא דתניא
ואכלו את הבשר בלילה הזה רבי אלעזר בן עזריה אומר נאמר כאן בלילה הזה ונאמר להלן
ועברתי בארץ מצרים בלילה הזה מה להלן עד חצות אף כאן עד חצות אמר ליה ר' עקיבא והלא כבר נאמר
בחפזון עד שעת חפזון א''כ מה תלמוד לומר בלילה יכול יהא נאכל כקדשים ביום תלמוד לומר בלילה בלילה הוא נאכל ולא ביום בשלמא לר' אלעזר בן עזריה דאית ליה גזירה שוה אצטריך למכתב ליה הזה אלא לר' עקיבא האי הזה מאי עביד ליה למעוטי לילה אחר הוא דאתא סד''א הואיל ופסח קדשים קלים ושלמים קדשים קלים מה שלמים נאכלין לשני ימים ולילה אחד אף פסח נאכל שתי לילות במקום ב' ימים ויהא נאכל לב' לילות ויום אחד קמ''ל בלילה הזה בלילה הזה הוא נאכל ואינו נאכל בלילה אחר ור' אלעזר בן עזריה
מלא תותירו עד בקר נפקא ורבי עקיבא אי מהתם הוה אמינא מאי בקר בקר שני ורבי אלעזר אמר לך כל בקר בקר ראשון הוא. והני תנאי כהני תנאי דתניא
שם תזבח את הפסח בערב כבוא השמש מועד צאתך ממצרים ר' אליעזר אומר בערב אתה זובח וכבוא השמש אתה אוכל ומועד צאתך ממצרים אתה שורף רבי יהושע אומר בערב אתה זובח כבוא השמש אתה אוכל ועד מתי אתה אוכל והולך עד מועד צאתך ממצרים א''ר אבא הכל מודים כשנגאלו ישראל ממצרים לא נגאלו אלא בערב שנאמר
הוציאך ה' אלהיך ממצרים לילה וכשיצאו לא יצאו אלא ביום שנא'
ממחרת הפסח יצאו בני ישראל ביד רמה על מה נחלקו על שעת חפזון ר' אלעזר בן עזריה סבר מאי חפזון חפזון דמצרים ורבי עקיבא סבר מאי חפזון חפזון דישראל תנ''ה הוציאך ה' אלהיך ממצרים לילה וכי בלילה יצאו והלא לא יצאו אלא ביום שנא' ממחרת הפסח יצאו בני ישראל ביד רמה אלא מלמד שהתחילה להם גאולה מבערב:  ט.
פסחים תודוס איש רומי הנהיג את בני רומי להאכילן גדיים מקולסין בלילי פסחים שלח ליה שמעון בן שטח אלמלא תודוס אתה גוזרני עליך נדוי שאתה מאכיל את ישראל קדשים בחוץ  יט.
פרקדן אמר רב יוסף פרקדן לא יקרא קריאת שמע מקרא הוא דלא ליקרי הא מיגנא שפיר דמי והא רבי יהושע בן לוי לייט אמאן דגני אפרקיד אמרי מיגנא כי מצלי שפיר דמי מקרא אע''ג דמצלי נמי אסור והא ר' יוחנן מצלי וקרי שאני ר' יוחנן דבעל בשר הוה:  יג:
** {דברים ו-ד}
קול תנן התם חרש המדבר ואינו שומע לא יתרום ואם תרם תרומתו תרומה מאן תנא חרש המדבר ואינו שומע דיעבד אין לכתחלה לא אמר רב חסדא ר' יוסי היא דתנן הקורא את שמע ולא השמיע לאזנו יצא דברי רבי יהודה ר' יוסי אומר לא יצא עד כאן לא קאמר ר' יוסי לא יצא אלא גבי ק''ש דאורייתא אבל תרומה משום ברכה הוא וברכה דרבנן ולא בברכה תליא מילתא וממאי דר' יוסי היא דילמא ר' יהודה היא ואמר גבי ק''ש נמי דיעבד אין לכתחלה לא תדע דקתני הקורא דיעבד אין לכתחלה לא אמרי האי דקתני הקורא להודיעך כחו דר' יוסי דאמר דיעבד נמי לא דאי ר' יהודה אפי' לכתחלה נמי יצא במאי אוקימתא כר' יוסי ואלא הא דתניא לא יברך אדם בהמ''ז בלבו ואם בירך יצא מני לא ר' יוסי ולא ר' יהודה דאי ר' יהודה הא אמר לכתחלה נמי יצא אי ר' יוסי דיעבד נמי לא אלא מאי ר' יהודה ודיעבד אין לכתחלה לא אלא הא דתני ר' יהודה בריה דרבי שמעון בן פזי חרש המדבר ואינו שומע תורם לכתחלה מני לא ר' יהודה ולא ר' יוסי אי ר' יהודה הא אמר דיעבד אין לכתחלה לא אי ר' יוסי הא אמר דיעבד נמי לא אלא לעולם רבי יהודה ואפי' לכתחלה נמי ולא קשיא הא דידיה הא דרביה דתנן רבי יהודה אומר משום ר' אלעזר בן עזריה הקורא את שמע צריך שישמיע לאזנו שנאמר
שמע ישראל ה' אלהינו ה' אחד אמר ליה רבי מאיר הרי הוא אומר אשר אנכי מצוך היום על לבבך אחר כונת הלב הן הן הדברים השתא דאתית להכי אפילו תימא רבי יהודה כרביה סבירא ליה ולא קשיא הא רבי מאיר הא רבי יהודה. תנן התם הכל כשרים לקרות את המגילה חוץ מחרש שוטה וקטן ורבי יהודה מכשיר בקטן מאן תנא חרש דיעבד נמי לא אמר רב מתנה רבי יוסי היא דתנן הקורא את שמע ולא השמיע לאזנו יצא דברי ר' יהודה רבי יוסי אומר לא יצא ממאי דרבי יוסי היא ודיעבד נמי לא
** מתני' גמ' {תהילים נה-יח} {שמות טז-ח}
קטנים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל: ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: ובמזוזה: פשיטא מהו דתימא הואיל ואתקש לתלמוד תורה קמשמע לן: ובברכת המזון: פשיטא מהו דתימא הואיל וכתיב
בתת ה' לכם בערב בשר לאכל ולחם בבקר לשבע כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
** {שמות כ-ח} {דברים ה-יב}
קידוש מר רב אדא בר אהבה נשים חייבות בקדוש היום דבר תורה אמאי מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות אמר אביי מדרבנן א''ל רבא והא דבר תורה קאמר ועוד כל מצות עשה נחייבינהו מדרבנן אלא אמר רבא אמר קרא
זכור
ושמור כל שישנו בשמירה ישנו בזכירה והני נשי הואיל ואיתנהו בשמירה איתנהו בזכירה כ:
** {בראשית יז-ה} {בראשית יז-ה} {בראשית יז-טו} {בראשית מו-ב} {נחמיה ט-ז}
שם אברהם  תני בר קפרא. כל הקורא לאברהם אברם עובר בעשה שנאמר
והיה שמך אברהם רבי אליעזר אומר עובר בלאו שנאמר
ולא יקרא עוד [את] שמך אברם אלא מעתה הקורא לשרה שרי הכי נמי התם קודשא בריך הוא אמר לאברהם
שרי אשתך לא תקרא את שמה שרי כי שרה שמה אלא מעתה הקורא ליעקב יעקב ה''נ שאני התם דהדר אהדריה קרא דכתיב
ויאמר אלהים לישראל במראות הלילה ויאמר יעקב יעקב מתיב רבי יוסי בר אבין ואיתימא רבי יוסי בר זבידא
אתה הוא ה' האלהים אשר בחרת באברם אמר ליה התם נביא הוא דקא מסדר לשבחיה דרחמנא מאי דהוה מעיקרא: יג.
** {בראשית מו-ב}
שם יעקב אלא מעתה הקורא ליעקב יעקב ה''נ שאני התם דהדר אהדריה קרא דכתיב
ויאמר אלהים לישראל במראות הלילה ויאמר יעקב יעקב יג.
** {בראשית לה-י}
שם יעקב כיוצא בו אתה אומר
לא יקרא שמך עוד יעקב כי אם ישראל יהיה שמך לא שיעקר יעקב ממקומו אלא ישראל עיקר ויעקב טפל לו  יג.
** {בראשית יז-טו}
שם שרה אלא מעתה הקורא לשרה שרי הכי נמי התם קודשא בריך הוא אמר לאברהם
שרי אשתך לא תקרא את שמה שרי כי שרה שמה יג.
** {דברים כז-ט}
שמע אומנים אלמא לא בעי כונה ורמינהי הקורא את שמע צריך שיכוין את לבו שנאמר שמע ישראל ולהלן הוא אומר
הסכת ושמע ישראל מה להלן בהסכת אף כאן בהסכת אשתיק א''ל מידי שמיע לך בהא א''ל הכי אמר רב ששת והוא שבטלין ממלאכתן וקורין והתניא בית הלל אומרים עוסקין במלאכתן וקורין לא קשיא הא בפרק ראשון הא בפרק שני טז.
** מתני'
שמע אומנים
האומנין קורין בראש האילן ובראש הנדבך מה שאינן רשאין לעשות כן בתפלה טז.
שמע אומנים ת''ר האומנין קורין בראש האילן ובראש הנדבך ומתפללין בראש הזית ובראש התאנה ושאר כל האילנות יורדים למטה ומתפללין ובעל הבית בין כך ובין כך יורד למטה ומתפלל לפי שאין דעתו מיושבת עליו רמי ליה רב מרי ברה דבת שמואל לרבא תנן האומנין קורין בראש האילן ובראש הנדבך טז.
שמע אופן אמר רב יוסף פרקדן לא יקרא קריאת שמע מקרא הוא דלא ליקרי הא מיגנא שפיר דמי והא רבי יהושע בן לוי לייט אמאן דגני אפרקיד אמרי מיגנא כי מצלי שפיר דמי מקרא אע''ג דמצלי נמי אסור והא ר' יוחנן מצלי וקרי שאני ר' יוחנן דבעל בשר הוה:  יג:
שמע אופן אתה כל זמן שאני זקוף אתה מוטה עכשיו כשאני הטתי אתה זקפת אמר לו אני עשיתי כדברי ב''ה ואתה עשית כדברי ב''ש ולא עוד אלא שמא יראו התלמידים ויקבעו הלכה לדורות מאי ולא עוד וכי תימא בית הלל נמי אית להו מטין ה''מ דמטה ואתא מעיקרא אבל הכא כיון דעד השתא הוית זקוף והשתא מוטה אמרי ש''מ כב''ש סבירא להו שמא יראו התלמידים ויקבעו הלכה לדורות. תני רב יחזקאל עשה כדברי ב''ש עשה כדברי ב''ה עשה רב יוסף אמר עשה כדברי ב''ש לא עשה ולא כלום דתנן מי שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ב''ש פוסלין וב''ה מכשירין אמרו להם ב''ה לב''ש מעשה שהלכו זקני ב''ש וזקני ב''ה לבקר את ר' יוחנן בן החורנית מצאוהו שהיה ראשו ורובו בסוכה ושלחנו בתוך הבית ולא אמרו לו כלום אמרו להם משם ראיה אף הם אמרו לו א''כ היית נוהג לא קיימת מצות סוכה מימיך רב נחמן בר יצחק אמר עשה כדברי בית שמאי חייב מיתה דתנן אמר ר''ט אני הייתי בא בדרך והטתי לקרות כדברי ב''ש וסכנתי בעצמי מפני הלסטים אמרו לו כדאי היית לחוב בעצמך שעברת על דברי ב''ה:  יא.
** {יחזקאל כד-יז}
שמע אופן ב''ש מ''ט לא אמרי כב''ה אמרי לך ב''ש א''כ נימא קרא בבקר ובערב מאי בשכבך ובקומך בשעת שכיבה שכיבה ממש ובשעת קימה קימה ממש וב''ש האי ובלכתך בדרך מאי עביד להו ההוא מבעי להו לכדתניא בשבתך בביתך פרט לעוסק במצוה ובלכתך בדרך פרט לחתן מכאן אמרו הכונס את הבתולה פטור ואת האלמנה חייב מאי משמע אמר רב פפא כי דרך מה דרך רשות אף כל רשות מי לא עסקינן דקא אזיל לדבר מצוה ואפילו הכי אמר רחמנא לקרי אם כן לכתוב רחמנא בשבת ובלכת מאי בשבתך ובלכתך בשבת דידך ובלכת דידך הוא דמחייבת הא דמצוה פטירת אי הכי אפילו כונס את האלמנה נמי האי טריד והאי לא טריד אי משום טרדא אפילו טבעה ספינתו בים נמי וכי תימא ה''נ אלמה א''ר אבא בר זבדא אמר רב אבל חייב בכל המצות האמורות בתורה חוץ מן התפילין שהרי נאמר בהם פאר שנאמר
פארך חבוש עליך התם טריד טרדא דמצוה הכא טריד טרדא דרשות וב''ש ההוא מבעי להו פרט לשלוחי מצוה וב''ה אמרי ממילא ש''מ דאפילו בדרך נמי קרי:  יא.
** מתני' {דברים ו-ז}
שמע אופן קריאתו
בית שמאי אומרים בערב כל אדם יטה ויקרא ובבקר יעמוד שנאמר
ובשכבך ובקומך ובית הלל אומרים כל אדם קורא כדרכו שנאמר ובלכתך בדרך אם כן למה נאמר ובשכבך ובקומך בשעה שבני אדם שוכבים ובשעה שבני אדם עומדים א''ר טרפון אני הייתי בא בדרך והטתי לקרות כדברי ב''ש וסכנתי בעצמי מפני הלסטים אמרו לו כדי היית לחוב בעצמך שעברת על דברי ב''ה: י:
שמע אחר זמנו אמר רב חסדא אמר מר עוקבא ובלבד שלא יאמר יוצר אור מיתיבי הקורא מכאן ואילך לא הפסיד כאדם שהוא קורא בתורה אבל מברך הוא שתים לפניה ואחת לאחריה תיובתא דרב חסדא תיובתא איכא דאמרי אמר רב חסדא אמר מר עוקבא מאי לא הפסיד שלא הפסיד ברכות תניא נמי הכי הקורא מכאן ואילך לא הפסיד כאדם שקורא בתורה אבל מברך הוא שתים לפניה ואחת לאחריה  י.
** מתני' גמ'
שמע בעל קרי
זב שראה קרי ונדה שפלטה שכבת זרע והמשמשת שראתה נדה צריכין טבילה ורבי יהודה פוטר:
איבעיא להו בעל קרי שראה זיבה לר' יהודה מהו כי פטר רבי יהודה התם בזב שראה קרי דמעיקרא לאו בר טבילה הוא אבל בעל קרי שראה זיבה דמעיקרא בר טבילה הוא מחייב או דילמא לא שנא תא שמע המשמשת וראתה נדה צריכה טבילה ורבי יהודה פוטר והא משמשת וראתה נדה כבעל קרי שראה זיבה דמיא וקא פטר רבי יהודה ש''מ תני רבי חייא בהדיא בעל קרי שראה זיבה צריך טבילה ורבי יהודה פוטר: כו.
שמע ברכות אמר רב חסדא אמר מר עוקבא ובלבד שלא יאמר יוצר אור מיתיבי הקורא מכאן ואילך לא הפסיד כאדם שהוא קורא בתורה אבל מברך הוא שתים לפניה ואחת לאחריה תיובתא דרב חסדא תיובתא איכא דאמרי אמר רב חסדא אמר מר עוקבא מאי לא הפסיד שלא הפסיד ברכות תניא נמי הכי הקורא מכאן ואילך לא הפסיד כאדם שקורא בתורה אבל מברך הוא שתים לפניה ואחת לאחריה  י.
שמע ברכות בעל קרי מהרהר בלבו ואינו מברך לא לפניה ולא לאחריה רבי יהודה אומר מברך לפניהם ולאחריהם  כ:
** {ישעיה מה-ז} {ישעיה מה-ז} {ירמיה לא-ג}
שמע ברכות מאי מברך אמר ר' יעקב א''ר אושעיא
יוצר אור ובורא חשך לימא יוצר אור ובורא נוגה כדכתיב קאמרינן אלא מעתה
עושה שלום ובורא רע מי קא אמרינן כדכתיב אלא כתיב רע וקרינן הכל לישנא מעליא הכא נמי לימא נוגה לישנא מעליא אלא אמר רבא כדי להזכיר מדת יום בלילה ומדת לילה ביום בשלמא מדת לילה ביום כדאמרינן יוצר אור ובורא חשך אלא מדת יום בלילה היכי משכחת לה אמר אביי גולל אור מפני חשך וחשך מפני אור ואידך מאי היא אמר רב יהודה אמר שמואל אהבה רבה וכן אורי ליה רבי אלעזר לר' פדת בריה אהבה רבה תניא נמי הכי אין אומרים אהבת עולם אלא אהבה רבה ורבנן אמרי אהבת עולם וכן הוא אומר
ואהבת עולם אהבתיך על כן משכתיך חסד  יא:
** מתני'
שמע ברכות
בשחר מברך שתים לפניה ואחת לאחריה ובערב מברך שתים לפניה ושתים לאחריה אחת ארוכה ואחת קצרה מקום שאמרו להאריך אינו רשאי לקצר לקצר אינו רשאי להאריך לחתום אינו רשאי שלא לחתום שלא לחתום אינו רשאי לחתום. יא.
שמע דקדוק  תני רב עובדיה קמיה דרבא ולמדתם שיהא למודך תם שיתן ריוח בין הדבקים עני רבא בתריה כגון על לבבך על לבבכם בכל לבבך בכל לבבכם עשב בשדך ואבדתם מהרה הכנף פתיל אתכם מארץ טו:
שמע דקדוק קרא ולא דקדק באותיותיה ר' יוסי אומר יצא רבי יהודה אומר לא יצא  טו.
שמע דקדק א''ר טבי א''ר יאשיה הלכה כדברי שניהם להקל: טו:
** {במדבר כג-כב} {במדבר כד-ט}
שמע הוספות אמר ר' אבהו בן זוטרתי אמר רב יהודה בר זבידא בקשו לקבוע פרשת בלק בקריאת שמע ומפני מה לא קבעוה משום טורח צבור מ''ט אילימא משום דכתיב בה
אל מוציאם ממצרים לימא פרשת רבית ופרשת משקלות דכתיב בהן יציאת מצרים אלא אמר ר' יוסי בר אבין משום דכתיב בה האי קרא
כרע שכב כארי וכלביא מי יקימנו ולימא האי פסוקא ותו לא גמירי כל פרשה דפסקה משה רבינו פסקינן דלא פסקה משה רבינו לא פסקינן יב:
שמע הוספות א''ר יהודה אמר שמואל אף בגבולין בקשו לקרות כן (עשרת הדברות) אלא שכבר בטלום מפני תרעומת המינין תניא נמי הכי ר' נתן אומר בגבולין בקשו לקרות כן אלא שכבר בטלום מפני תרעומת המינין רבה בב''ח סבר למקבעינהו בסורא א''ל רב חסדא כבר בטלום מפני תרעומת המינין אמימר סבר למקבעינהו בנהרדעא א''ל רב אשי כבר בטלום מפני תרעומת המינין: יב.
שמע הפסק א''ר אבהו א''ר יוחנן הלכה כר' יהודה דאמר בין אלהיכם לאמת ויציב לא יפסיק יד.
** {ירמיה י-י}
שמע הפסק א''ר אבהו א''ר יוחנן מאי טעמיה דרבי יהודה דכתיב
וה' אלהים אמת חוזר ואומר אמת או אינו חוזר ואומר אמת א''ר אבהו א''ר יוחנן חוזר ואומר אמת רבה אמר אינו חוזר ואומר אמת ההוא דנחית קמיה דרבה שמעיה רבה דאמר אמת אמת תרי זימני אמר רבה כל אמת אמת תפסיה להאי  יד.
שמע הפסק בפרקים שואל מפני הכבוד ומשיב ובאמצע שואל מפני היראה ומשיב דברי ר' מאיר ר' יהודה אומר באמצע שואל מפני היראה ומשיב מפני הכבוד ובפרקים שואל מפני הכבוד ומשיב שלום לכל אדם אלו הן בין הפרקים בין ברכה ראשונה לשניה בין שניה לשמע בין שמע לוהיה אם שמוע בין והיה אם שמוע לויאמר בין ויאמר לאמת ויציב ר' יהודה אומר בין ויאמר לאמת ויציב לא יפסיק יג.
שמע הפסק תניא נמי הכי הקורא את שמע ופגע בו רבו או גדול הימנו בפרקים שואל מפני הכבוד וא''צ לומר שהוא משיב ובאמצע שואל מפני היראה ואצ''ל שהוא משיב דברי ר' מאיר ר' יהודה אומר באמצע שואל מפני היראה ומשיב מפני הכבוד ובפרקים שואל מפני הכבוד ומשיב שלום לכל אדם יד.
שמע הרחק ממאוס ולא יתכסה לא במים הרעים ולא במי המשרה עד שיטיל לתוכן מים וכמה ירחיק מהן ומן הצואה ד' אמות:  כב:
** {תהילים עב-ה}
שמע זמן  לק''ש כותיקין דאמר ר' יוחנן ותיקין היו גומרין אותה עם הנץ החמה תניא נמי הכי ותיקין היו גומרין אותה עם הנץ החמה כדי שיסמוך גאולה לתפלה ונמצא מתפלל ביום א''ר זירא מאי קראה
ייראוך עם שמש ולפני ירח דור דורים ט:
** מתני' גמ'
שמע זמן
מאימתי קורין את שמע בשחרית משיכיר בין תכלת ללבן ר' אליעזר אומר בין תכלת לכרתי (וגומרה) עד הנץ החמה ר' יהושע אומר עד שלש שעות שכן דרך מלכים לעמוד בשלש שעות הקורא מכאן ואילך לא הפסיד כאדם הקורא בתורה:
מאי בין תכלת ללבן אילימא בין גבבא דעמרא חיורא לגבבא דעמרא דתכלתא הא בליליא נמי מידע ידעי אלא בין תכלת שבה ללבן שבה. תניא רבי מאיר אומר משיכיר בין זאב לכלב ר''ע אומר בין חמור לערוד ואחרים אומרים משיראה את חברו רחוק ד' אמות ויכירנו אמר רב הונא הלכה כאחרים ט:
שמע זמן אמר מר משעה שהכהנים נכנסים לאכול בתרומתן. מכדי כהנים אימת קא אכלי תרומה משעת צאת הכוכבים לתני משעת צאת הכוכבים. ב.
** {נחמיה ד-טו} {נחמיה ד-טז}
שמע זמן אמר מר משעה שהכהנים נכנסין לאכול בתרומתן ורמינהו מאימתי קורין את שמע בערבין משהעני נכנס לאכול פתו במלח עד שעה שעומד ליפטר מתוך סעודתו. סיפא ודאי פליגא אמתניתין. רישא מי לימא פליגי אמתני'. לא עני וכהן חד שיעורא הוא. ורמינהו מאימתי מתחילין לקרות ק''ש בערבית משעה שבני אדם נכנסין לאכול פתן בערבי שבתות דברי ר''מ וחכמים אומרים משעה שהכהנים זכאין לאכול בתרומתן סימן לדבר צאת הכוכבים. ואע''פ שאין ראיה לדבר זכר לדבר שנאמר
ואנחנו עושים במלאכה וחצים מחזיקים ברמחים מעלות השחר עד צאת הכוכבים ואומר
והיו לנו הלילה משמר והיום מלאכה מאי ואומר וכי תימא מכי ערבא שמשא ליליא הוא ואינהו דמחשכי ומקדמי ת''ש והיו לנו הלילה משמר והיום מלאכה קא סלקא דעתך דעני ובני אדם חד שעורא הוא ואי אמרת עני וכהן חד שעורא הוא חכמים היינו רבי מאיר אלא שמע מינה עני שעורא לחוד וכהן שעורא לחוד לא עני וכהן חד שעורא הוא ועני ובני אדם לאו חד שעורא הוא. ועני וכהן חד שעורא הוא ורמינהו מאימתי מתחילין לקרות שמע בערבין משעה שקדש היום בערבי שבתות דברי ר' אליעזר רבי יהושע אומר משעה שהכהנים מטוהרים לאכול בתרומתן רבי מאיר אומר משעה שהכהנים טובלין לאכול בתרומתן אמר לו ר' יהודה והלא כהנים מבעוד יום הם טובלים ר' חנינא אומר משעה שעני נכנס לאכול פתו במלח ר' אחאי ואמרי לה ר' אחא אומר משעה שרוב בני אדם נכנסין להסב. ואי אמרת עני וכהן חד שעורא הוא ר' חנינא היינו ר' יהושע אלא לאו שמע מינה שעורא דעני לחוד ושעורא דכהן לחוד שמע מינה. הי מנייהו מאוחר מסתברא דעני מאוחר דאי אמרת דעני מוקדם ר' חנינא היינו ר' אליעזר אלא לאו שמע מינה דעני מאוחר שמע מינה: אמר מר אמר ליה רבי יהודה והלא כהנים מבעוד יום הם טובלים שפיר קאמר ליה רבי יהודה לרבי מאיר ורבי מאיר הכי קאמר ליה מי סברת דאנא אבין השמשות דידך קא אמינא אנא אבין השמשות דרבי יוסי קא אמינא דאמר רבי יוסי בין השמשות כהרף עין זה נכנס וזה יוצא ואי אפשר לעמוד עליו קשיא דר' מאיר אדר''מ תרי תנאי אליבא דר''מ קשיא דר' אליעזר אדר' אליעזר תרי תנאי אליבא דר' אליעזר ואב''א רישא לאו ר' אליעזר היא: ב:
שמע זמן אמר רב יהודה אמר שמואל הלכה כרבי יהושע י.
שמע זמן אמר רב יהודה אמר שמואל הלכה כר''ג ח:
שמע זמן חכמים עשו סייג לדבריהם כדי שלא יהא אדם בא מן השדה בערב ואומר אלך לביתי ואוכל קימעא ואשתה קימעא ואישן קימעא ואח''כ אקרא ק''ש ואתפלל וחוטפתו שינה ונמצא ישן כל הלילה אבל אדם בא מן השדה בערב נכנס לבית הכנסת אם רגיל לקרות קורא ואם רגיל לשנות שונה וקורא ק''ש ומתפלל ואוכל פתו ומברך וכל העובר על דברי חכמים חייב מיתה ד:
שמע זמן לימא תנא סתמא כר' אליעזר דאמר עד הנץ החמה אפי' תימא ר' יהושע ודלמא כותיקין דא''ר יוחנן ותיקין היו גומרין אותה עם הנץ החמה: כה:
** מתני'
שמע זמן
מאימתי קורין את שמע בערבין. משעה שהכהנים נכנסים לאכול בתרומתן עד סוף האשמורה הראשונה דברי ר' אליעזר. וחכמים אומרים עד חצות. רבן גמליאל אומר עד שיעלה עמוד השחר. מעשה ובאו בניו מבית המשתה אמרו לו לא קרינו את שמע אמר להם אם לא עלה עמוד השחר חייבין אתם לקרות
שמע זמן עד סוף האשמורה: מאי קסבר ר' אליעזר אי קסבר שלש משמרות הוי הלילה לימא עד ארבע שעות ואי קסבר ארבע משמרות הוי הלילה לימא עד שלש שעות לעולם קסבר שלש משמרות הוי הלילה ואב''א כולהו סוף משמרות קא חשיב וכי תימא אחרונה לא צריך למאי נפקא מינה למיקרי ק''ש למאן דגני בבית אפל ולא ידע זמן ק''ש אימת כיון דאשה מספרת עם בעלה ותינוק יונק משדי אמו ליקום וליקרי. ג.
שמע זמן תניא ר''ש בן יוחי אומר פעמים שאדם קורא ק''ש שתי פעמים בלילה אחת קודם שיעלה עמוד השחר ואחת לאחר שיעלה עמוד השחר ויוצא בהן ידי חובתו אחת של יום ואחת של לילה. הא גופא קשיא אמרת פעמים שאדם קורא קרית שמע שתי פעמים בלילה אלמא לאחר שיעלה עמוד השחר ליליא הוא והדר תני יוצא בהן ידי חובתו אחת של יום ואחת של לילה אלמא יממא הוא לא לעולם ליליא הוא והא דקרי ליה יום דאיכא אינשי דקיימי בההיא שעתא אמר רב אחא בר חנינא אמר רבי יהושע בן לוי הלכה כרבי שמעון בן יוחי איכא דמתני להא דרב אחא בר חנינא אהא דתניא רבי שמעון בן יוחי אומר משום ר' עקיבא פעמים שאדם קורא קרית שמע שתי פעמים ביום אחת קודם הנץ החמה ואחת לאחר הנץ החמה ויוצא בהן ידי חובתו אחת של יום ואחת של לילה הא גופא קשיא אמרת פעמים שאדם קורא ק''ש שתי פעמים ביום אלמא קודם הנץ החמה יממא הוא והדר תני יוצא בהן ידי חובתו אחת של יום ואחת של לילה אלמא ליליא הוא לא לעולם יממא הוא והאי דקרו ליה ליליא דאיכא אינשי דגנו בההיא שעתא אמר רבי אחא ברבי חנינא אמר רבי יהושע בן לוי הלכה כר''ש שאמר משום רבי עקיבא. אמר רבי זירא ובלבד שלא יאמר השכיבנו. כי אתא רב יצחק בר יוסף אמר הא דרבי אחא ברבי חנינא אמר ריב''ל לאו בפירוש איתמר אלא מכללא איתמר דההוא זוגא דרבנן דאשתכור בהלולא דבריה דר' יהושע בן לוי אתו לקמיה דריב''ל אמר כדאי הוא ר''ש לסמוך עליו בשעת הדחק: ח:
** {דברים ו-ז}
שמע חיובו אמר רב יהודה ספק קרא קריאת שמע ספק לא קרא אינו חוזר וקורא ספק אמר אמת ויציב ספק לא אמר חוזר ואומר אמת ויציב מאי טעמא קריאת שמע דרבנן אמת ויציב דאורייתא מתיב רב יוסף
ובשכבך ובקומך אמר ליה אביי ההוא בדברי תורה כתיב תנן בעל קרי מהרהר בלבו ואינו מברך לא לפניה ולא לאחריה ועל המזון מברך לאחריו ואינו מברך לפניו ואי ס''ד אמת ויציב דאורייתא לברוך לאחריה מאי טעמא מברך אי משום יציאת מצרים הא אדכר ליה בקריאת שמע ונימא הא ולא לבעי הא קריאת שמע עדיפא דאית בה תרתי ור' אלעזר אמר ספק קרא קריאת שמע ספק לא קרא חוזר וקורא ק''ש ספק התפלל ספק לא התפלל אינו חוזר ומתפלל ורבי יוחנן אמר ולואי שיתפלל אדם כל היום כולו: כא.
** מתני' גמ'
שמע חייבים
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ק''ש פשיטא מצות עשה שהזמן גרמא הוא וכל מצות עשה שהזמן גרמא נשים פטורות מהו דתימא הואיל ואית בה מלכות שמים קמ''ל:  כ:
שמע חתן חתן אם רוצה לקרות קרית שמע לילה הראשון קורא רבן שמעון בן גמליאל אומר לא כל הרוצה ליטול את השם יטול: טז:
שמע חתן חתן פטור מק''ש לילה הראשונה ועד מוצאי שבת אם לא עשה מעשה ומעשה בר''ג שנשא אשה וקרא לילה הראשונה אמרו לו תלמידיו למדתנו רבינו שחתן פטור מק''ש אמר להם איני שומע לכם לבטל הימני מלכות שמים אפי' שעה אחת טז.
שמע טעות קרא וטעה יחזור למקום שטעה:
שמע טעות רבי אמי ורבי אסי הוו קא קטרין ליה גננא לר' אלעזר אמר להו אדהכי והכי איזיל ואשמע מלתא דבי מדרשא ואיתי ואימא לכו אזל אשכחיה לתנא דקתני קמיה דר' יוחנן קרא וטעה ואינו יודע להיכן טעה באמצע הפרק יחזור לראש בין פרק לפרק יחזור לפרק ראשון בין כתיבה לכתיבה יחזור לכתיבה ראשונה אמר ליה ר' יוחנן לא שנו אלא שלא פתח בלמען ירבו ימיכם אבל פתח בלמען ירבו ימיכם סרכיה נקט ואתי אתא ואמר להו אמרו ליה אלו לא באנו אלא לשמוע דבר זה דיינו:  טז.
שמע כוונה אמר רב נתן בר מר עוקבא אמר רב יהודה על לבבך בעמידה על לבבך סלקא דעתך אלא אימא עד על לבבך בעמידה מכאן ואילך לא ורבי יוחנן אמר כל הפרשה כולה בעמידה ואזדא ר' יוחנן לטעמיה דאמר רבה בר בר חנה א''ר יוחנן הלכה כר' אחא שאמר משום ר' יהודה:  יג:
** {דברים ו-ו} {דברים יא-יח} {דברים ו-ד}
שמע כוונה הדברים על לבבך יכול תהא כל הפרשה צריכה כוונה תלמוד לומר האלה עד כאן צריכה כוונה מכאן ואילך אין צריכה כוונה דברי ר' אליעזר א''ל רבי עקיבא הרי הוא אומר
אשר אנכי מצוך היום על לבבך מכאן אתה למד שכל הפרשה כולה צריכה כוונה אמר רבה בר בר חנה אמר ר' יוחנן הלכה כר''ע איכא דמתני לה אהא דתניא הקורא את שמע צריך שיכוין את לבו ר' אחא משום ר' יהודה אומר כיון שכוון לבו בפרק ראשון שוב אינו צריך אמר רבה בר בר חנה אמר ר' יוחנן הלכה כר' אחא שאמר משום ר' יהודה על לבבך ר' זוטרא אומר עד כאן מצות כוונה מכאן ואילך מצות קריאה רבי יאשיה אומר עד כאן מצות קריאה מכאן ואילך מצות כוונה מ''ש מכאן ואילך מצות קריאה דכתיב לדבר בם הכא נמי הא כתיב ודברת בם ה''ק עד כאן מצות כוונה וקריאה מכאן ואילך קריאה בלא כוונה ומאי שנא עד כאן מצות כוונה וקריאה דכתיב על לבבך ודברת בם התם נמי הא כתיב על לבבכם לדבר בם ההוא מבעי ליה לכדרבי יצחק דאמר
ושמתם את דברי אלה צריכה שתהא שימה כנגד הלב:   אמר מר ר' יאשיה אומר עד כאן מצות קריאה מכאן ואילך מצות כוונה מ''ש מכאן ואילך מצות כוונה משום דכתיב על לבבכם הכא נמי הא כתיב על לבבך ה''ק עד כאן מצות קריאה וכוונה מכאן ואילך כוונה בלא קריאה ומ''ש עד כאן מצות קריאה וכוונה דכתיב על לבבך ודברת בם התם נמי הא כתיב על לבבכם לדבר בם ההוא בדברי תורה כתיב וה''ק רחמנא אגמירו בנייכו תורה כי היכי דליגרסו בהו: ת''ר
שמע ישראל ה' אלהינו ה' אחד עד כאן צריכה כוונת הלב דברי ר''מ אמר רבא הלכה כר''מ  יג:
** מתני'
שמע כוונה
היה קורא בתורה והגיע זמן המקרא אם כוון לבו יצא ש''מ מצות צריכות כוונה מאי אם כוון לבו לקרות לקרות והא קא קרי בקורא להגיה: יג.
שמע כסדר לרבנן נמי הא כתיב והיו ההוא מבעי להו שלא יקרא למפרע ורבי שלא יקרא למפרע מנא ליה נפקא ליה מדברים הדברים ורבנן דברים הדברים לא דרשי  יג.
שמע כסדר ת''ר והיו שלא יקרא למפרע יג.
שמע לשון  ת''ר ק''ש ככתבה דברי רבי וחכ''א בכל לשון מ''ט דרבי אמר קרא והיו בהוייתן יהו ורבנן מאי טעמייהו אמר קרא שמע בכל לשון שאתה שומע ולרבי נמי הא כתיב שמע ההוא מבעי ליה השמע לאזניך מה שאתה מוציא מפיך ורבנן סברי להו כמאן דאמר לא השמיע לאזנו יצא ולרבנן נמי הא כתיב והיו ההוא מבעי להו שלא יקרא למפרע ורבי שלא יקרא למפרע מנא ליה נפקא ליה מדברים הדברים ורבנן דברים הדברים לא דרשי למימרא דסבר רבי דכל התורה כולה בכל לשון נאמרה דאי סלקא דעתך בלשון הקודש נאמרה והיו דכתב רחמנא למה לי איצטריך משום דכתיב שמע למימרא דסברי רבנן דכל התורה כולה בלשון הקודש נאמרה דאי סלקא דעתך בכל לשון נאמרה שמע דכתב רחמנא למה לי איצטריך משום דכתיב והיו:  יג.
שמע לשון מאי טעמא דר' יוסי משום דכתיב שמע השמע לאזנך מה שאתה מוציא מפיך ות''ק סבר שמע בכל לשון שאתה שומע ור' יוסי תרתי שמע מינה .  טו.
שמע מאוס אמר אביי צואה כל שהוא מבטלה ברוק אמר רבא וברוק עבה אמר רבא צואה בגומא מניח סנדלו עליה וקורא ק''ש בעא מר בריה דרבינא צואה דבוקה בסנדלו מאי תיקו כה:
** {יחזקאל כ-כה} {ישעיה ה-יח} {במדבר טו-לא} {דברים לב-מז}
שמע מאוס אמר רב הונא א''ר יוחנן היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל רב חסדא האלהים אם אמרה לי ר' יוחנן בפומיה לא צייתנא ליה איכא דאמרי אמר רבה בר בר חנה אמר ריב''ל היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל ר' חסדא האלהים אם אמרה לי ריב''ל בפומיה לא צייתנא ליה ומי אמר ר' הונא הכי והאמר רב הונא ת''ח אסור לו לעמוד במקום הטנופת לפי שאי אפשר לו לעמוד בלי הרהור תורה לא קשיא כאן בעומד כאן במהלך ומי אמר רבי יוחנן הכי והאמר רבה בר בר חנה א''ר יוחנן בכל מקום מותר להרהר בדברי תורה חוץ מבית המרחץ ומבית הכסא וכי תימא הכא נמי כאן בעומד כאן במהלך איני והא רבי אבהו הוה קא אזיל בתריה דרבי יוחנן והוה קא קרי ק''ש כי מטא במבואות המטונפות אשתיק א''ל לר' יוחנן להיכן אהדר א''ל אם שהית כדי לגמור את כולה חזור לראש הכי קאמר ליה לדידי לא סבירא לי לדידך דסבירא לך אם שהית כדי לגמור את כולה חזור לראש תניא כותיה דרב הונא תניא כותיה דרב חסדא תניא כותיה דרב הונא המהלך במבואות המטונפות מניח ידו על פיו ויקרא ק''ש תניא כותיה דרב חסדא היה מהלך במבואות המטונפות לא יקרא ק''ש ולא עוד אלא שאם היה קורא ובא פוסק לא פסק מאי אמר ר' מיאשה בר בריה דריב''ל עליו הכתוב אומר
וגם אני נתתי להם חוקים לא טובים ומשפטים לא יחיו [בהם] ר' אסי אמר
הוי מושכי העון בחבלי השוא רב אדא בר אהבה אמר מהכא
כי דבר ה' בזה ואם פסק מה שכרו אמר ר' אבהו עליו הכתוב אומר
ובדבר הזה תאריכו ימים: כד:
** {תהילים קנ-ו} {תהילים לה-י} {ויקרא יג-מו} {דברים כג-טו} {דברים כג-יג} {דברים כג-יד}
שמע מאוס אתמר צואה על בשרו או ידו מונחת בבית הכסא רב הונא אמר מותר לקרות ק''ש רב חסדא אמר אסור לקרות ק''ש אמר רבא מ''ט דרב הונא דכתיב
כל הנשמה תהלל יה ורב חסדא אמר אסור לקרות ק''ש מ''ט דרב חסדא דכתיב
כל עצמותי תאמרנה ה' מי כמוך: אתמר ריח רע שיש לו עיקר רב הונא אמר מרחיק ד' אמות וקורא ק''ש ורב חסדא אמר מרחיק ד' אמות ממקום שפסק הריח וקורא ק''ש תניא כותיה דרב חסדא לא יקרא אדם ק''ש לא כנגד צואת אדם ולא כנגד צואת כלבים ולא כנגד צואת חזירים ולא כנגד צואת תרנגולים ולא כנגד צואת אשפה שריחה רע ואם היה מקום גבוה עשרה טפחים או נמוך עשרה טפחים יושב בצדו וקורא ק''ש ואם לאו מרחיק מלא עיניו וכן לתפלה ריח רע שיש לו עיקר מרחיק ד' אמות ממקום הריח וקורא ק''ש אמר רבא לית הלכתא כי הא מתניתא (בכל הני שמעתתא) אלא כי הא דתניא לא יקרא אדם ק''ש לא כנגד צואת אדם ולא כנגד צואת חזירים ולא כנגד צואת כלבים בזמן שנתן עורות לתוכן בעו מיניה מרב ששת ריח רע שאין לו עיקר מהו אמר להו אתו חזו הני ציפי דבי רב דהני גנו והני גרסי וה''מ בדברי תורה אבל בק''ש לא ודברי תורה נמי לא אמרן אלא דחבריה אבל דידיה לא: אתמר צואה עוברת אביי אמר מותר לקרות ק''ש רבא אמר אסור לקרות ק''ש אמר אביי מנא אמינא לה דתנן הטמא עומד תחת האילן והטהור עובר טמא טהור עומד תחת האילן וטמא עובר טהור ואם עמד טמא וכן באבן המנוגעת ורבא אמר לך התם בקביעותא תליא מילתא דכתיב
בדד ישב מחוץ למחנה מושבו הכא
והיה מחניך קדוש אמר רחמנא והא ליכא: א''ר פפא פי חזיר כצואה עוברת דמי פשיטא לא צריכא אע''ג דסליק מנהרא א''ר יהודה ספק צואה אסורה ספק מי רגלים מותרים א''ד אמר רב יהודה ספק צואה בבית מותרת באשפה אסורה ספק מי רגלים אפילו באשפה נמי מותרין סבר לה כי הא דרב המנונא דאמר רב המנונא לא אסרה תורה אלא כנגד עמוד בלבד וכדרבי יונתן דר' יונתן רמי כתיב
ויד תהיה לך מחוץ למחנה ויצאת שמה חוץ וכתיב
ויתד תהיה לך וגו' וכסית את צאתך הא כיצד כאן בגדולים כאן בקטנים אלמא קטנים לא אסרה תורה אלא כנגד עמוד בלבד הא נפול לארעא שרי ורבנן הוא דגזרו בהו וכי גזרו בהו רבנן בודאן אבל בספקן לא גזור ובודאן עד כמה אמר רב יהודה אמר שמואל כל זמן שמטפיחין וכן אמר רבה בב''ח א''ר יוחנן כל זמן שמטפיחין וכן אמר עולא כל זמן שמטפיחין גניבא משמיה דרב אמר כל זמן שרשומן ניכר א''ר יוסף שרא ליה מריה לגניבא השתא צואה אמר רב יהודה אמר רב כיון שקרמו פניה מותר מי רגלים מיבעיא א''ל אביי מאי חזית דסמכת אהא סמוך אהא דאמר רבה בר רב הונא אמר רב צואה אפילו כחרס אסורה והיכי דמי צואה כחרס אמר רבה בב''ח א''ר יוחנן כל זמן שזורקה ואינה נפרכת וא''ד כל זמן שגוללה ואינה נפרכת אמר רבינא הוה קאימנא קמיה דרב יהודה מדפתי חזא צואה אמר לי עיין אי קרמו פניה אי לא א''ד הכי א''ל עיין אי מפלאי אפלויי מאי הוי עלה אתמר צואה כחרס אמימר אמר אסורה ומר זוטרא אמר מותרת אמר רבא הלכתא צואה כחרס אסורה ומי רגלים כל זמן שמטפיחין מיתיבי מי רגלים כל זמן שמטפיחין אסורין נבלעו או יבשו מותרים מאי לאו נבלעו דומיא דיבשו מה יבשו דאין רשומן ניכר אף נבלעו דאין רשומן ניכר הא רשומן ניכר אסור אע''ג דאין מטפיחין ולטעמיך אימא רישא כל זמן שמטפיחין הוא דאסור הא רשומן ניכר שרי אלא מהא ליכא למשמע מינה לימא כתנאי כלי שנשפכו ממנו מי רגלים אסור לקרות ק''ש כנגדו ומי רגלים עצמן שנשפכו נבלעו מותר לא נבלעו אסור ר' יוסי אומר כל זמן שמטפיחין מאי נבלעו ומאי לא נבלעו דקאמר ת''ק אילימא נבלעו דאין מטפיחין לא נבלעו דמטפיחין ואתא ר' יוסי למימר כ''ז שמטפיחין הוא דאסור הא רשומן ניכר שרי היינו ת''ק אלא נבלעו דאין רשומן ניכר לא נבלעו דרשומן ניכר ואתא ר' יוסי למימר כ''ז שמטפיחין הוא דאסור הא רשומן ניכר שרי לא דכ''ע כ''ז שמטפיחין הוא דאסור הא רשומן ניכר שרי והכא בטופח על מנת להטפיח איכא בינייהו: כה.
שמע מאוס כמה ירחיק מהן ומן הצואה ארבע אמות: אמר רבא אמר רב סחורה אמר רב הונא לא שנו אלא לאחוריו אבל לפניו מרחיק מלא עיניו וכן לתפלה איני והא אמר רפרם בר פפא אמר רב חסדא עומד אדם כנגד בית הכסא ומתפלל הכא במאי עסקינן בבית הכסא שאין בו צואה איני והאמר רב יוסף בר חנינא בית הכסא שאמרו אע''פ שאין בו צואה ובית המרחץ שאמרו אע''פ שאין בו אדם אלא הכא במאי עסקינן בחדתי והא מיבעי ליה לרבינא הזמינו לבית הכסא מהו יש זימון או אין זימון כי קא מיבעי ליה לרבינא למיקם עליה לצלויי בגויה אבל כנגדו לא אמר רבא הני בתי כסאי דפרסאי אע''ג דאית בהו צואה כסתומין דמו:  כו.
שמע מאוס לא יתכסה לא במים הרעים ולא במי המשרה כלל ומי רגלים עד שיטיל לתוכן מים ויקרא ת''ר כמה יטיל לתוכן מים כל שהוא ר' זכאי אומר רביעית אמר רב נחמן מחלוקת לבסוף אבל בתחלה כל שהן ורב יוסף אמר מחלוקת לכתחלה אבל לבסוף דברי הכל רביעית אמר ליה רב יוסף לשמעיה אייתי לי רביעיתא דמיא כר' זכאי: ת''ר גרף של רעי ועביט של מי רגלים אסור לקרות ק''ש כנגדן ואף ע''פ שאין בהן כלום ומי רגלים עצמן עד שיטיל לתוכן מים וכמה יטיל לתוכן מים כל שהוא ר' זכאי אומר רביעית בין לפני המטה בין לאחר המטה רבן שמעון בן גמליאל אומר לאחר המטה קורא לפני המטה אינו קורא אבל מרחיק הוא ארבע אמות וקורא ר''ש בן אלעזר אומר אפי' בית מאה אמה לא יקרא עד שיוציאם או שיניחם תחת המטה איבעיא להו היכי קאמר אחר המטה קורא מיד לפני המטה מרחיק ארבע אמות וקורא או דלמא הכי קאמר לאחר המטה מרחיק ד' אמות וקורא לפני המטה אינו קורא כלל ת''ש דתניא ר''ש בן אלעזר אומר אחר המטה קורא מיד לפני המטה מרחיק ארבע אמות רבן שמעון בן גמליאל אומר אפי' בית מאה אמה לא יקרא עד שיוציאם או שיניחם תחת המטה בעיין איפשיטא לן מתנייתא קשיין אהדדי איפוך בתרייתא מה חזית דאפכת בתרייתא איפוך קמייתא מאן שמעת ליה דאמר כוליה בית כארבע אמות דמי ר''ש בן אלעזר היא אמר רב יוסף בעאי מיניה מרב הונא מטה פחות משלשה פשיטא לי דכלבוד דמי שלשה ארבעה חמשה ששה שבעה שמנה תשעה מהו א''ל לא ידענא עשרה ודאי לא מיבעי לי אמר אביי שפיר עבדת דלא איבעיא לך כל עשרה רשותא אחריתי היא אמר רבא הלכתא פחות משלשה כלבוד דמי עשרה רשותא אחריתי היא משלשה עד עשרה היינו דבעא מיניה רב יוסף מרב הונא ולא פשט ליה אמר רב הלכה כר''ש בן אלעזר וכן אמר באלי א''ר יעקב ברה דבת שמואל הלכה כרבי שמעון בן אלעזר ורבא אמר אין הלכה כר''ש בן אלעזר  כה:
** {דברים ו-ז}
שמע מקור תנא אקרא קאי דכתיב
בשכבך ובקומך
שמע סדר הקורא למפרע לא יצא  טו.
שמע סדר עם תפילין  אמר עולא כל הקורא ק''ש בלא תפילין כאילו מעיד עדות שקר בעצמו א''ר חייא בר אבא א''ר יוחנן כאילו . הקריב עולה בלא מנחה וזבח בלא נסכים:  יד:
שמע סדר עם תפילין רב משי ידיה וקרא ק''ש ואנח תפילין וצלי והיכי עביד הכי והתניא החופר כוך למת בקבר פטור מק''ש ומן התפלה ומן התפילין ומכל מצות האמורות בתורה הגיע זמן ק''ש עולה ונוטל ידיו ומניח תפילין וקורא ק''ש ומתפלל הא גופא קשיא רישא אמר פטור וסיפא חייב הא לא קשיא סיפא בתרי ורישא בחד מ''מ קשיא לרב רב כרבי יהושע בן קרחה סבירא ליה דאמר עול מלכות שמים תחלה ואח''כ עול מצות אימר דאמר רבי יהושע בן קרחה להקדים קריאה לקריאה קריאה לעשיה מי שמעת ליה ותו מי סבר ליה כרבי יהושע בן קרחה והאמר רב חייא בר אשי זמנין סגיאין הוה קאימנא קמיה דרב ומקדים ומשי ידיה ומברך ומתני לן פרקין ומנח תפילין והדר קרי ק''ש וכ''ת בדלא מטא זמן ק''ש א''כ מאי אסהדתיה דרב חייא בר אשי לאפוקי ממ''ד למשנה אין צריך לברך קמ''ל דאף למשנה נמי צריך לברך מ''מ קשיא לרב שלוחא הוא דעוית:  יד:
שמע ערוה  ת''ר היה ישן בטליתו ואינו יכול להוציא את ראשו מפני הצנה חוצץ בטליתו על צוארו וקורא ק''ש וי''א על לבו ותנא קמא הרי לבו רואה את הערוה קסבר לבו רואה את הערוה מותר  כד:
שמע ערווה  אמר רב הונא היתה טליתו חגורה לו על מתניו מותר לקרות ק''ש תניא נמי הכי היתה טליתו של בגד ושל עור ושל שק חגורה על מתניו מותר לקרות ק''ש אבל לתפלה עד שיכסה את לבו כד:
שמע ערווה  ירד לטבול אם יכול לעלות ולהתכסות ולקרות עד שלא תהא הנץ החמה יעלה ויתכסה ויקרא ואם לאו יתכסה במים ויקרא  כב:
** {יחזקאל כג-כ} {בראשית ט-כג}
שמע ערווה אמר רב יהודה עכו''ם ערום אסור לקרות ק''ש כנגדו מאי איריא עכו''ם אפילו ישראל נמי ישראל פשיטא ליה דאסור אלא עכו''ם אצטריכא ליה מהו דתימא הואיל וכתיב בהו
אשר בשר חמורים בשרם אימא כחמור בעלמא הוא קמ''ל דאינהו נמי איקרו ערוה דכתיב
וערות אביהם לא ראו:  כה:
** {דברים כג-טו}
שמע ערווה אמר רבא צואה בעששית מותר לקרות ק''ש כנגדה ערוה בעששית אסור לקרות ק''ש כנגדה צואה בעששית מותר לקרות ק''ש כנגדה דצואה בכסוי תליא מילתא והא מיכסיא ערוה בעששית אסור לקרות ק''ש כנגדה
ולא יראה בך ערות דבר אמר רחמנא והא קמיתחזיא  כה:
שמע ערווה והרי לבו רואה את הערוה א''ר אלעזר ואי תימא ר' אחא בר אבא בר אחא משום רבינו במים עכורין שנו דדמו כארעא סמיכתא שלא יראה לבו ערותו. ת''ר מים צלולין ישב בהן עד צוארו וקורא וי''א עוכרן ברגלו ות''ק והרי לבו רואה את הערוה קסבר לבו רואה את הערוה מותר והרי עקבו רואה את הערוה קסבר עקבו רואה את הערוה מותר אתמר עקבו רואה את הערוה מותר נוגע אביי אמר אסור ורבא אמר מותר רב זביד מתני לה להא שמעתא הכי רב חיננא בריה דרב איקא מתני לה הכי נוגע דברי הכל אסור רואה אביי אמר אסור רבא אמר מותר לא נתנה תורה למלאכי השרת והלכתא נוגע אסור רואה מותר  כה:
** {במדבר טו-לט} {תהילים יד-א} {שופטים יד-ג} {שופטים ח-לג}
שמע פרשה שלישית  פרשת ציצית מפני מה קבעוה א''ר יהודה בר חביבא מפני שיש בה חמשה דברים מצות ציצית יציאת מצרים עול מצות ודעת מינים הרהור עבירה והרהור ע''ז בשלמא הני תלת מפרשן עול מצות דכתיב
וראיתם אותו וזכרתם את כל מצות ה' ציצית דכתיב ועשו להם ציצית וגו' יציאת מצרים דכתיב אשר הוצאתי וגו' אלא דעת מינים הרהור עבירה והרהור ע''ז מנלן דתניא אחרי לבבכם זו מינות וכן הוא אומר
אמר נבל בלבו אין אלהים אחרי עיניכם זה הרהור עבירה שנאמר
ויאמר שמשון אל אביו אותה קח לי כי היא ישרה בעיני אתם זונים זה הרהור ע''ז וכן הוא אומר
ויזנו אחרי הבעלים:  יב:
שמע פרשה שלישית אמר רב יוסף כמה מעליא הא שמעתתא דכי אתא רב שמואל בר יהודה אמר אמרי במערבא ערבית דבר אל בני ישראל ואמרת אליהם אני ה' אלהיכם אמת אמר ליה אביי מאי מעליותא והא אמר רב כהנא אמר רב לא יתחיל ואם התחיל גומר וכי תימא ואמרת אליהם לא הוי התחלה והאמר רב שמואל בר יצחק אמר רב דבר אל בני ישראל לא הוי התחלה ואמרת אליהם הוי התחלה אמר רב פפא קסברי במערבא ואמרת אליהם נמי לא הויא התחלה עד דאמר ועשו להם ציצית אמר אביי הלכך אנן אתחולי מתחלינן דקא מתחלי במערבא וכיון דאתחלינן מגמר נמי גמרינן דהא אמר רב כהנא אמר רב לא יתחיל ואם התחיל גומר חייא בר רב אמר אמר אני ה' אלהיכם צריך לומר אמת לא אמר אני ה' אלהיכם אינו צ''ל אמת והא בעי לאדכורי יציאת מצרים דאמר הכי מודים אנחנו לך ה' אלהינו שהוצאתנו מארץ מצרים ופדיתנו מבית עבדים ועשית לנו נסים וגבורות על הים ושרנו לך:  יד:
** מתני' {דברים טז-ג} גמ' {ירמיה כג-ז} {בראשית לה-י} {ישעיה מג-יח} {ישעיה מג-יט}
שמע פרשה שלישית מתי
מזכירין יציאת מצרים בלילות א''ר אלעזר בן עזריה הרי אני כבן שבעים שנה ולא זכיתי שתאמר יציאת מצרים בלילות עד שדרשה בן זומא שנא'
למען תזכור את יום צאתך מארץ מצרים כל ימי חייך ימי חייך הימים כל ימי חייך הלילות וחכ''א ימי חייך העוה''ז כל להביא לימות המשיח:
תניא אמר להם בן זומא לחכמים וכי מזכירין יציאת מצרים לימות המשיח והלא כבר נאמר
הנה ימים באים נאם ה' ולא יאמרו עוד חי ה' אשר העלה את בני ישראל מארץ מצרים כי אם חי ה' אשר העלה ואשר הביא את זרע בית ישראל מארץ צפונה ומכל הארצות אשר הדחתים שם אמרו לו לא שתעקר יציאת מצרים ממקומה אלא שתהא שעבוד מלכיות עיקר ויציאת מצרים טפל לו כיוצא בו אתה אומר
לא יקרא שמך עוד יעקב כי אם ישראל יהיה שמך לא שיעקר יעקב ממקומו אלא ישראל עיקר ויעקב טפל לו וכן הוא אומר
אל תזכרו ראשונות וקדמוניות אל תתבוננו אל תזכרו ראשונות זה שעבוד מלכיות וקדמוניות אל תתבוננו זו יציאת מצרים
הנני עושה חדשה עתה תצמח תני רב יוסף זו מלחמת גוג ומגוג משל למה הדבר דומה לאדם שהיה מהלך בדרך ופגע בו זאב וניצל ממנו והיה מספר והולך מעשה זאב פגע בו ארי וניצל ממנו והיה מספר והולך מעשה ארי פגע בו נחש וניצל ממנו שכח מעשה שניהם והיה מספר והולך מעשה נחש אף כך ישראל צרות אחרונות משכחות את הראשונות: יב:
** {דברים כג-טו}
שמע צואה אמר רבא צואה בעששית מותר לקרות ק''ש כנגדה ערוה בעששית אסור לקרות ק''ש כנגדה צואה בעששית מותר לקרות ק''ש כנגדה דצואה בכסוי תליא מילתא והא מיכסיא ערוה בעששית אסור לקרות ק''ש כנגדה
ולא יראה בך ערות דבר אמר רחמנא והא קמיתחזיא כה:
שמע קול א''ר טבי א''ר יאשיה הלכה כדברי שניהם להקל: טו:
שמע קול ולרבי נמי הא כתיב שמע ההוא מבעי ליה השמע לאזניך מה שאתה מוציא מפיך ורבנן סברי להו כמאן דאמר לא השמיע לאזנו יצא  יג.
** מתני'
שמע קול
הקורא את שמע ולא השמיע לאזנו יצא ר' יוסי אומר לא יצא מאי טעמא דר' יוסי משום דכתיב שמע השמע לאזנך מה שאתה מוציא מפיך ות''ק סבר שמע בכל לשון שאתה שומע ור' יוסי תרתי שמע מינה . טו.
שמע קריאה ' זוטרא אומר עד כאן מצות כוונה מכאן ואילך מצות קריאה  אמר מר ר' יאשיה אומר עד כאן מצות קריאה מכאן ואילך מצות כוונה מ''ש מכאן ואילך מצות כוונה משום דכתיב על לבבכם הכא נמי הא כתיב על לבבך ה''ק עד כאן מצות קריאה וכוונה מכאן ואילך כוונה בלא קריאה ומ''ש עד כאן מצות קריאה וכוונה דכתיב על לבבך ודברת בם התם נמי הא כתיב על לבבכם לדבר בם ההוא בדברי תורה כתיב וה''ק רחמנא אגמירו בנייכו תורה כי היכי דליגרסו בהו: יג:
שמע קריאה ת''ר שמע ישראל ה' אלהינו ה' אחד זו ק''ש של ר' יהודה הנשיא א''ל רב לר' חייא לא חזינא ליה לרבי דמקבל עליה מלכות שמים אמר ליה בר פחתי בשעה שמעביר ידיו על פניו מקבל עליו עול מלכות שמים חוזר וגומרה או אינו חוזר וגומרה בר קפרא אומר אינו חוזר וגומרה רבי שמעון ברבי אומר חוזר וגומרה א''ל בר קפרא לר''ש ברבי בשלמא לדידי דאמינא אינו חוזר וגומרה היינו דמהדר רבי אשמעתא דאית בה יציאת מצרים אלא לדידך דאמרת חוזר וגומרה למה ליה לאהדורי כדי להזכיר יציאת מצרים בזמנה אמר ר' אילא בריה דרב שמואל בר מרתא משמיה דרב אמר שמע ישראל ה' אלהינו ה' אחד ונאנס בשינה יצא אמר ליה רב נחמן לדרו עבדיה בפסוקא קמא צערן טפי לא תצערן אמר ליה רב יוסף לרב יוסף בריה דרבה אבוך היכי הוה עביד אמר ליה בפסוקא קמא הוה קא מצער נפשיה טפי לא הוה מצער נפשיה  יג:
** {תהילים ד-ה} {תהילים לא-ו}
שמע שעל המטה א''ר יהושע בן לוי אע''פ שקרא אדם ק''ש בביהכ''נ מצוה לקרותו על מטתו אמר רבי יוסי מאי קרא
רגזו ואל תחטאו אמרו בלבבכם על משכבכם ודומו סלה אמר רב נחמן אם תלמיד חכם הוא אין צריך אמר אביי אף תלמיד חכם מיבעי ליה למימר חד פסוקא דרחמי כגון
בידך אפקיד רוחי פדיתה אותי ה' אל אמת:  ה.
תורה כתיב על לבבכם לדבר בם ההוא בדברי תורה כתיב וה''ק רחמנא אגמירו בנייכו תורה כי היכי דליגרסו בהו: יג:
** {יחזקאל כ-כה} {ישעיה ה-יח} {במדבר טו-לא} {דברים לב-מז}
תורה מאוס אמר רב הונא א''ר יוחנן היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל רב חסדא האלהים אם אמרה לי ר' יוחנן בפומיה לא צייתנא ליה איכא דאמרי אמר רבה בר בר חנה אמר ריב''ל היה מהלך במבואות המטונפות מניח ידו על פיו וקורא ק''ש א''ל ר' חסדא האלהים אם אמרה לי ריב''ל בפומיה לא צייתנא ליה ומי אמר ר' הונא הכי והאמר רב הונא ת''ח אסור לו לעמוד במקום הטנופת לפי שאי אפשר לו לעמוד בלי הרהור תורה לא קשיא כאן בעומד כאן במהלך ומי אמר רבי יוחנן הכי והאמר רבה בר בר חנה א''ר יוחנן בכל מקום מותר להרהר בדברי תורה חוץ מבית המרחץ ומבית הכסא וכי תימא הכא נמי כאן בעומד כאן במהלך איני והא רבי אבהו הוה קא אזיל בתריה דרבי יוחנן והוה קא קרי ק''ש כי מטא במבואות המטונפות אשתיק א''ל לר' יוחנן להיכן אהדר א''ל אם שהית כדי לגמור את כולה חזור לראש הכי קאמר ליה לדידי לא סבירא לי לדידך דסבירא לך אם שהית כדי לגמור את כולה חזור לראש תניא כותיה דרב הונא תניא כותיה דרב חסדא תניא כותיה דרב הונא המהלך במבואות המטונפות מניח ידו על פיו ויקרא ק''ש תניא כותיה דרב חסדא היה מהלך במבואות המטונפות לא יקרא ק''ש ולא עוד אלא שאם היה קורא ובא פוסק לא פסק מאי אמר ר' מיאשה בר בריה דריב''ל עליו הכתוב אומר
וגם אני נתתי להם חוקים לא טובים ומשפטים לא יחיו [בהם] ר' אסי אמר
הוי מושכי העון בחבלי השוא רב אדא בר אהבה אמר מהכא
כי דבר ה' בזה ואם פסק מה שכרו אמר ר' אבהו עליו הכתוב אומר
ובדבר הזה תאריכו ימים: כד:
תורה מוליך ת''ר המוליך עצמות ממקום למקום הרי זה לא יתנם בדסקיא ויתנם על גבי חמור וירכב עליהם מפני שנוהג בהם מנהג בזיון ואם היה מתירא מפני נכרים ומפני לסטים מותר וכדרך שאמרו בעצמות כך אמרו בספר תורה אהייא אילימא ארישא פשיטא מי גרע ספר תורה מעצמות אלא אסיפא:  יח.
תענית טעימה בעי מיניה אשיאן תנא דבי ר' אמי מר' אמי השרוי בתענית מהו שיטעום אכילה ושתיה קביל עליה והא ליכא או דילמא הנאה קביל עליה והא איכא א''ל טועם ואין בכך כלום תניא נמי הכי מטעמת אינה טעונה ברכה והשרוי בתענית טועם ואין בכך כלום עד כמה ר' אמי ור' אסי טעמי עד שיעור רביעתא:  יד.
תפילה נהוג עיטוש רבי אבא אמר איזיל ואשמע מיניה (מר’ יהודה) מילתא מבית וועדא והדר אפיק אזל אשכחיה לתנא דקתני קמיה דרב יהודה היה עומד בתפלה ונתעטש ממתין עד שיכלה הרוח וחוזר ומתפלל איכא דאמרי היה עומד בתפלה ובקש להתעטש מרחיק לאחריו ד' אמות ומתעטש וממתין עד שיכלה הרוח וחוזר ומתפלל ואומר רבש''ע יצרתנו נקבים נקבים חלולים חלולים גלוי וידוע לפניך חרפתנו וכלימתנו בחיינו ובאחריתנו רמה ותולעה ומתחיל ממקום שפסק אמר ליה אילו לא באתי אלא לשמוע דבר זה דיי: כד:
** מתני' גמ'
תפילין
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
ומן התפלין: פשיטא מהו דתימא הואיל ואתקש למזוזה קמ''ל: כ:
** {יחזקאל כד-יז}
תפילין אבל א''ר אבא בר זבדא אמר רב אבל חייב בכל המצות האמורות בתורה חוץ מן התפילין שהרי נאמר בהם פאר שנאמר
פארך חבוש עליך יא.
תפילין בית הכסא  וא''ר הונא שכח ונכנס בתפילין לבית הכסא מניח ידו עליהן עד שיגמור עד שיגמור ס''ד אלא כדאמר ר''נ בר יצחק עד שיגמור עמוד ראשון ולפסוק לאלתר וליקום משום דרשב''ג דתניא רשב''ג אומר עמוד החוזר מביא את האדם לידי הדרוקן סילון החוזר מביא את האדם לידי ירקון:  כה.
תפילין בית הכסא תנו רבנן הנכנס לבית הכסא חולץ תפיליו ברחוק ד' אמות ונכנס אמר רב אחא בר רב הונא אמר רב ששת לא שנו אלא בית הכסא קבוע אבל בית הכסא עראי חולץ ונפנה לאלתר וכשהוא יוצא מרחיק ד' אמות ומניחן מפני שעשאו בית הכסא קבוע איבעיא להו מהו שיכנס אדם בתפילין לבית הכסא קבוע להשתין מים רבינא שרי רב אדא בר מתנא אסר אתו שיילוה לרבא אמר להו אסור חיישינן שמא יפנה בהן ואמרי לה שמא יפיח בהן תניא אידך הנכנס לבית הכסא קבוע חולץ תפיליו ברחוק ד' אמות ומניחן בחלון הסמוך לרשות הרבים ונכנס וכשהוא יוצא מרחיק ד' אמות ומניחן דברי בית שמאי ובית הלל אומרים אוחזן בידו ונכנס ר''ע אומר אוחזן בבגדו ונכנס בבגדו ס''ד זימנין מישתלי להו ונפלי אלא אימא אוחזן בבגדו ובידו ונכנס ומניחם בחורין הסמוכים לבית הכסא ולא יניחם בחורין הסמוכים לרשות הרבים שמא יטלו אותם עוברי דרכים ויבא לידי חשד ומעשה בתלמיד אחד שהניח תפילין בחורין הסמוכים לרשות הרבים ובאת זונה אחת ונטלתן ובאת לבית המדרש ואמרה ראו מה נתן לי פלוני בשכרי כיון ששמע אותו תלמיד כך עלה לראש הגג ונפל ומת באותה שעה התקינו שיהא אוחזן בבגדו ובידו ונכנס תנו רבנן בראשונה היו מניחין תפילין בחורין הסמוכין לבית הכסא ובאין עכברים ונוטלין אותן התקינו שיהו מניחין אותן בחלונות הסמוכות לרשות הרבים ובאין עוברי דרכים ונוטלין אותן התקינו שיהא אוחזן בידו ונכנס אמר רבי מיאשא בריה דריב''ל הלכה גוללן כמין ספר ואוחזן בימינו כנגד לבו אמר רב יוסף בר מניומי אמר רב נחמן ובלבד שלא תהא רצועה יוצאת מתחת ידו טפח אמר רבי יעקב בר אחא אמר רבי זירא לא שנו אלא שיש שהות ביום ללבשן אבל אין שהות ביום ללבשן עושה להן כמין כיס טפח ומניחן אמר רבה בר בר חנה אמר רבי יוחנן ביום גוללן כמין ספר ומניחן בידו כנגד לבו ובלילה עושה להן כמין כיס טפח ומניחן אמר אביי לא שנו אלא בכלי שהוא כליין אבל בכלי שאינו כליין אפילו פחות מטפח אמר מר זוטרא ואיתימא רב אשי תדע שהרי פכין קטנים מצילין באהל המת ואמר רבה בר בר חנה כי הוה אזלינן בתריה דרבי יוחנן כי הוה בעי למיעל לבית הכסא כי הוה נקיט ספרא דאגדתא הוה יהיב לן כי הוה נקיט תפילין לא הוה יהיב לן אמר הואיל ושרונהו רבנן ננטרן אמר רבא כי הוה אזלינן בתריה דר''נ כי הוה נקיט ספרא דאגדתא יהיב לן כי הוה נקיט תפילין לא יהיב לן אמר הואיל ושרונהו רבנן ננטרן  כג.
תפילין ולא ישתין בהן מים ולא יישן בהן לא שינת קבע ולא שינת עראי. אמר רבא אמר רב ששת לית הלכתא כי הא מתניתא דב''ש היא דאי ב''ה השתא בית הכסא קבוע שרי בית הכסא עראי מיבעיא מיתיבי ... עד שיש חזרה.הכי קאמר בית הכסא קבוע דליכא ניצוצות שרי בית הכסא עראי דאיכא ניצוצות אסרי  כג.
תפילין זמן אחרים אומרים משיראה את חברו רחוק ד' אמות ויכירנו  אמר אביי לתפילין כאחרים ט:
תפילין כבוד בית שיש בו ספר תורה או תפילין אסור לשמש בו את המטה עד שיוציאם או שיניחם כלי בתוך כלי אמר אביי לא שנו אלא בכלי שאינו כליין אבל בכלי שהוא כליין אפילו עשרה מאני כחד מאנא דמי אמר רבא גלימא אקמטרא ככלי בתוך כלי דמי.  כה:
תפילין כיס תני חדא צורר אדם תפיליו עם מעותיו באפרקסותו ותניא אידך לא יצור לא קשיא הא דאזמניה הא דלא אזמניה דאמר רב חסדא האי סודרא דתפילין דאזמניה למיצר ביה תפילין צר ביה תפילין אסור למיצר ביה פשיטי אזמניה ולא צר ביה צר ביה ולא אזמניה שרי למיצר ביה זוזי ולאביי דאמר הזמנה מילתא היא אזמניה אע''ג דלא צר ביה צר ביה אי אזמניה אסיר אי לא אזמניה לא כג:
** {במדבר ה-כג}
תפילין מה כתוב תני ר' אושעיא קמיה דרבא וכתבתם הכל בכתב אפילו צואות א''ל דאמר לך מני ר' יהודה היא דאמר גבי סוטה אלות כותב צואות אינו כותב והתם הוא דכתיב
וכתב את האלות האלה אבל הכא דכתיב וכתבתם אפי' צואות נמי אטו טעמיה דר' יהודה משום דכתיב וכתב טעמיה דר' יהודה משום דכתיב אלות אלות אין צואות לא אצטריך סד''א נילף כתיבה כתיבה מהתם מה התם אלות אין צואות לא אף הכא נמי צואות לא כתב רחמנא וכתבתם אפי' צואות:  טו:
תפילין מטה בעא מיניה רב יוסף בריה דרב נחוניא מרב יהודה מהו שיניח אדם תפיליו תחת מראשותיו תחת מרגלותיו לא קא מיבעיא לי שנוהג בהן מנהג בזיון כי קא מיבעיא לי תחת מראשותיו מאי א''ל הכי אמר שמואל מותר אפילו אשתו עמו מיתיבי לא יניח אדם תפיליו תחת מרגלותיו מפני שנוהג בהם דרך בזיון אבל מניחן תחת מראשותיו ואם היתה אשתו עמו אסור היה מקום שגבוה ג' טפחים או נמוך ג' טפחים מותר תיובתא דשמואל תיובתא אמר רבא אע''ג דתניא תיובתא דשמואל הלכתא כוותיה מ''ט כל לנטורינהו טפי עדיף והיכא מנח להו אמר ר' ירמיה בין כר לכסת שלא כנגד ראשו והא תני רבי חייא מניחן בכובע תחת מראשותיו דמפיק ליה למורשא דכובע לבר בר קפרא צייר להו בכילתא ומפיק למורשהון לבר רב שישא בריה דרב אידי מנח להו אשרשיפא ופריס סודרא עלוייהו אמר רב המנונא בריה דרב יוסף זימנא חדא הוה קאימנא קמיה דרבא ואמר לי זיל אייתי לי תפילין ואשכחתינהו בין כר לכסת שלא כנגד ראשו והוה ידענא דיום טבילה הוה ולאגמורן הלכה למעשה הוא דעבד  כג:
** {דברים יא-יח}
תפילין מקום של יד דאמר
ושמתם את דברי אלה צריכה שתהא שימה כנגד הלב יג:
תפילין סעודה אמר ר' יצחק הנכנס לסעודת קבע חולץ תפיליו ואח''כ נכנס ופליגא דר' חייא דא''ר חייא מניחן על שלחנו וכן הדור לו ועד אימת אמר רב נחמן בר יצחק עד זמן ברכה  כג.
** {דברים כח-סו}
תפילין תלייה אמר ר' חנינא אני ראיתי את רבי שתלה תפיליו מיתיבי התולה תפיליו יתלו לו חייו דורשי חמורות אמרו
והיו חייך תלואים לך מנגד זה התולה תפיליו לא קשיא הא ברצועה הא בקציצה ואיבעית אימא לא שנא רצועה ולא שנא קציצה אסור וכי תלה רבי בכיסתא תלה אי הכי מאי למימרא מהו דתימא תיבעי הנחה כספר תורה קמ''ל:  כד.
** מתני' גמ' {תהילים נה-יח}
תפלה
נשים ועבדים וקטנים פטורין מק''ש ומן התפלין וחייבין בתפלה ובמזוזה ובברכת המזון:
וחייבין בתפלה: דרחמי נינהו מהו דתימא הואיל וכתיב בה
ערב ובקר וצהרים כמצות עשה שהזמן גרמא דמי קמ''ל: כ:
** מתני'
תפלה אומנים
האומנין קורין בראש האילן ובראש הנדבך מה שאינן רשאין לעשות כן בתפלה טז.
תפלה אומנים ת''ר האומנין קורין בראש האילן ובראש הנדבך ומתפללין בראש הזית ובראש התאנה ושאר כל האילנות יורדים למטה ומתפללין ובעל הבית בין כך ובין כך יורד למטה ומתפלל לפי שאין דעתו מיושבת עליו רמי ליה רב מרי ברה דבת שמואל לרבא תנן האומנין קורין בראש האילן ובראש הנדבך טז.
** {ויקרא יט-כו} {מלכים א יד-ט}
תפלה אכילה קודם (א''ר יצחק וא''ר יוסי בר' חנינא משום ראב''י מאי דכתיב
לא תאכלו על הדם לא תאכלו קודם שתתפללו על דמכם (א''ד) א''ר יצחק א''ר יוחנן א''ר יוסי בר' חנינא משום ראב''י כל האוכל ושותה ואח''כ מתפלל עליו הכתוב אומר
ואותי השלכת אחרי גויך אל תקרי גויך אלא גאיך אמר הקב''ה לאחר שנתגאה זה קבל עליו מלכות שמים: י.
תפלה בא מאוחר אמר רב הונא הנכנס לבית הכנסת ומצא צבור שמתפללין אם יכול להתחיל ולגמור עד שלא יגיע ש''ץ למודים יתפלל ואם לאו אל יתפלל ריב''ל אמר אם יכול להתחיל ולגמור עד שלא יגיע ש''צ לקדושה יתפלל ואם לאו אל יתפלל במאי קא מפלגי מר סבר יחיד אומר קדושה ומר סבר אין יחיד אומר קדושה  כא:
תפלה באחיזה ת''ר לא יאחז אדם תפילין בידו וס''ת בזרועו ויתפלל אמר שמואל סכין ומעות וקערה וככר הרי אלו כיוצא בהן.  כג.
** {תהילים סט-יד} {ישעיה מט-ח} {איוב לו-ה} {תהילים נה-יט}
תפלה ברבים זמן רבים א''ל רבי יצחק לרב נחמן מ''ט לא אתי מר לבי כנישתא לצלויי אמר ליה לא יכילנא א''ל לכנפי למר עשרה וליצלי אמר ליה טריחא לי מלתא ולימא ליה מר לשלוחא דצבורא בעידנא דמצלי צבורא ליתי ולודעיה למר א''ל מאי כולי האי א''ל דאמר ר' יוחנן משום ר''ש בן יוחי מאי דכתיב
ואני תפלתי לך ה' עת רצון אימתי עת רצון בשעה שהצבור מתפללין. ר' יוסי ברבי חנינא אמר מהכא
כה אמר ה' בעת רצון עניתיך ר' אחא ברבי חנינא אמר מהכא
הן אל כביר ולא ימאס וכתיב
פדה בשלום נפשי מקרב לי כי ברבים היו עמדי תניא נמי הכי רבי נתן אומר מנין שאין הקב''ה מואס בתפלתן של רבים שנאמר הן אל כביר ולא ימאס וכתיב פדה בשלום נפשי מקרב לי וגו' אמר הקב''ה כל העוסק בתורה ובגמילות חסדים ומתפלל עם הצבור מעלה אני עליו כאילו פדאני לי ולבני מבין אומות העולם ז:
תפלה הא ר''ג הא ר' יהושע אי ר' יהושע מאי איריא פועלים אפילו כל אדם נמי טז.
תפלה הוספות א''ר יוחנן בתחלה הוא אומר ה' שפתי תפתח ולבסוף הוא אומר יהיו לרצון אמרי פי וגו' ט:
** {תהילים קד-לה} {תהילים א-א} {תהילים ב-יב}
תפלה הוספות מכדי האי יהיו לרצון אמרי פי משמע לבסוף ומשמע מעיקרא דבעינא למימר מ''ט תקנוהו רבנן לאחר י''ח ברכות לימרו מעיקרא א''ר יהודה בריה דר' שמעון בן פזי הואיל ולא אמרו דוד אלא לאחר י''ח פרשיות לפיכך תקינו רבנן לאחר י''ח ברכות. הני י''ח י''ט הויין אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' יהודה בריה דרבי שמעון בן פזי ק''ג פרשיות אמר דוד ולא אמר הללויה עד שראה במפלתן של רשעים שנאמר
יתמו חטאים מן הארץ ורשעים עוד אינם ברכי נפשי את ה' הללויה. הני ק''ג ק''ד הויין אלא שמע מינה אשרי האיש ולמה רגשו גוים חדא פרשה היא דאמר ר' שמואל בר נחמני אמר רבי יוחנן כל פרשה שהיתה חביבה על דוד פתח בה באשרי וסיים בה באשרי פתח באשרי דכתיב
אשרי האיש וסיים באשרי דכתיב
אשרי כל חוסי בו:
תפלה הכון הפסק ת''ר היה עומד בתפלה ומים שותתין על ברכיו פוסק עד שיכלו המים וחוזר ומתפלל להיכן חוזר רב חסדא ורב המנונא חד אמר חוזר לראש וחד אמר למקום שפסק לימא בהא קמיפלגי מר סבר אם שהה כדי לגמור את כולה חוזר לראש ומר סבר למקום שפסק אמר רב אשי האי אם שהה אם לא שהה מיבעי ליה אלא דכולי עלמא אם שהה כדי לגמור את כולה חוזר לראש והתם בדלא שהה קמיפלגי דמר סבר גברא דחויא הוא ואין ראוי ואין תפלתו תפלה ומר סבר גברא חזיא הוא ותפלתו תפלה  כג.
** {עמוס ד-יב}
תפלה הכון תנו רבנן הנצרך לנקביו אל יתפלל ואם התפלל תפלתו תועבה אמר רב זביד ואיתימא רב יהודה לא שנו אלא שאינו יכול לשהות בעצמו אבל אם יכול לשהות בעצמו תפלתו תפלה ועד כמה אמר רב ששת עד פרסה איכא דמתני לה אמתניתא במה דברים אמורים כשאין יכול לעמוד על עצמו אבל אם יכול לעמוד על עצמו תפלתו תפלה ועד כמה אמר רב זביד עד פרסה אמר רבי שמואל בר נחמני אמר רבי יונתן הנצרך לנקביו הרי זה לא יתפלל משום שנאמר
הכון לקראת אלהיך ישראל. כג.
תפלה הפסק  ודכולי עלמא מיהת מפסק לא פסיק (למודים וקדושה) איבעיא להו מהו להפסיק ליהא שמו הגדול מבורך כי אתא רב דימי אמר ר' יהודה ור''ש תלמידי דרבי יוחנן אמרי לכל אין מפסיקין חוץ מן יהא שמו הגדול מבורך שאפילו עוסק במעשה מרכבה פוסק ולית הלכתא כותיה:  כא:
** {תהילים קמו-ח} {מלאכי ב-ה}
תפלה השתחויות ואמר רבה בר חיננא [סבא] משמיה דרב המתפלל כשהוא כורע כורע בברוך וכשהוא זוקף זוקף בשם אמר שמואל מאי טעמא דרב דכתיב
ה' זוקף כפופים מיתיבי
מפני שמי נחת הוא מי כתיב בשמי מפני שמי כתיב אמר ליה שמואל לחייא בר רב בר אוריאן תא ואימא לך מלתא מעלייתא דאמר אבוך הכי אמר אבוך כשהוא כורע כורע בברוך כשהוא זוקף זוקף בשם. רב ששת כי כרע כרע כחיזרא כי קא זקיף זקיף כחיויא: יב.
** {תהילים עב-ה}
תפלה זמן  לק''ש כותיקין דאמר ר' יוחנן ותיקין היו גומרין אותה עם הנץ החמה תניא נמי הכי ותיקין היו גומרין אותה עם הנץ החמה כדי שיסמוך גאולה לתפלה ונמצא מתפלל ביום א''ר זירא מאי קראה
ייראוך עם שמש ולפני ירח דור דורים ט:
** {תהילים פה-יד}
תפלה חפציו קודם אמר רב אידי בר אבין אסור לו לאדם לעשות חפציו קודם שיתפלל שנאמר
צדק לפניו יהלך וישם לדרך פעמיו ואמר רב אידי בר אבין אמר רב יצחק בר אשיאן כל המתפלל ואח''כ יוצא לדרך הקב''ה עושה לו חפציו שנאמר צדק לפניו יהלך וישם לדרך פעמיו:  יד.
תפלה כבר התפלל  ואמר רב יהודה אמר שמואל היה עומד בתפלה ונזכר שהתפלל פוסק ואפילו באמצע ברכה איני והאמר רב נחמן כי הוינן בי רבה בר אבוה בען מיניה הני בני בי רב דטעו ומדכרי דחול בשבת מהו שיגמרו ואמר לן גומרין כל אותה ברכה הכי השתא התם גברא בר חיובא הוא ורבנן הוא דלא אטרחוהו משום כבוד שבת אבל הכא הא צלי ליה: ואמר רב יהודה אמר שמואל התפלל ונכנס לביהכ''נ ומצא צבור שמתפללין אם יכול לחדש בה דבר יחזור ויתפלל ואם לאו אל יחזור ויתפלל וצריכא דאי אשמעינן קמייתא ה''מ יחיד ויחיד או צבור וצבור אבל יחיד לגבי צבור כמאן דלא צלי דמי קמ''ל ואי אשמעינן הכא משום דלא אתחיל בה אבל התם דאתחיל בה אימא לא צריכא כא
** {משלי כא-כז}
תפלה מאוס תניא אידך היה עומד בתפלה וראה צואה כנגדו מהלך לפניו עד שיזרקנה לאחוריו ד' אמות והתניא לצדדין ל''ק הא דאפשר הא דלא אפשר היה מתפלל ומצא צואה במקומו אמר רבה אע''פ שחטא תפלתו תפלה מתקיף ליה רבא והא
זבח רשעים תועבה אלא אמר רבא הואיל וחטא אע''פ שהתפלל תפלתו תועבה:  כב:
תפלה ניהוג ואמר ר' חנינא אני ראיתי את רבי שגיהק ופיהק ונתעטש ורק וממשמש בבגדו אבל לא היה מתעטף וכשהוא מפהק היה מניח ידו על סנטרו מיתיבי המשמיע קולו בתפלתו הרי זה מקטני אמנה המגביה קולו בתפלתו הרי זה מנביאי השקר מגהק ומפהק הרי זה מגסי הרוח המתעטש בתפלתו סימן רע לו ויש אומרים ניכר שהוא מכוער הרק בתפלתו כאילו רק בפני המלך בשלמא מגהק ומפהק לא קשיא כאן לאונסו כאן לרצונו אלא מתעטש אמתעטש קשיא מתעטש אמתעטש נמי לא קשיא כאן מלמעלה כאן מלמטה אלא רק ארק קשיא רק ארק נמי לא קשיא אפשר כדרב יהודה דאמר רב יהודה היה עומד בתפלה ונזדמן לו רוק מבליעו בטליתו ואם טלית נאה הוא מבליעו באפרקסותו רבינא הוה קאי אחורי דרב אשי נזדמן לו רוק פתקיה לאחוריה א''ל לא סבר לה מר להא דרב יהודה מבליעו באפרקסותו א''ל אנא אנינא דעתאי: כד:
תפלה ספק ספק התפלל ספק לא התפלל אינו חוזר ומתפלל ורבי יוחנן אמר ולואי שיתפלל אדם כל היום כולו:  כא.
תפלה ערווה היתה טליתו של בגד ושל עור ושל שק חגורה על מתניו מותר לקרות ק''ש אבל לתפלה עד שיכסה את לבו  כד:
** {ישעיה ה-טז}
תפלה עשרת ימי תשובה ואמר רבה בר חיננא סבא משמיה דרב כל השנה כולה אדם מתפלל האל הקדוש מלך אוהב צדקה ומשפט חוץ מעשרה ימים שבין ראש השנה ויום הכפורים שמתפלל המלך הקדוש והמלך המשפט ורבי אלעזר אמר אפילו אמר האל הקדוש יצא שנאמר
ויגבה ה' צבאות במשפט והאל הקדוש נקדש בצדקה אימתי ויגבה ה' צבאות במשפט אלו עשרה ימים שמר''ה ועד יוה''כ וקאמר האל הקדוש מאי הוה עלה אמר רב יוסף האל הקדוש ומלך אוהב צדקה ומשפט רבה אמר המלך הקדוש והמלך המשפט והלכתא כרבה:  יב:
תפלה קול המשמיע קולו בתפלתו הרי זה מקטני אמנה: אמר רב הונא לא שנו אלא שיכול לכוין את לבו בלחש אבל אין יכול לכוין את לבו בלחש מותר וה''מ ביחיד אבל בצבור אתי למיטרד צבורא:  כד:
** {יחזקאל א-ז}
תפלה רגלים וא''ר יוסי בר' חנינא משום ראב''י המתפלל צריך שיכוין את רגליו שנא'
ורגליהם רגל ישרה י.
תפלה של חול בשבת בען מיניה הני בני בי רב דטעו ומדכרי דחול בשבת מהו שיגמרו ואמר לן גומרין כל אותה ברכה הכי השתא התם גברא בר חיובא הוא ורבנן הוא דלא אטרחוהו משום כבוד שבת כא.
** {ישעיה ב-כב}
תפלה שלום קודם אמר רב כל הנותן שלום לחבירו קודם שיתפלל כאלו עשאו במה שנאמר
חדלו לכם מן האדם אשר נשמה באפו כי במה נחשב הוא אל תקרי במה אלא במה ושמואל אמר במה חשבתו לזה ולא לאלוה מתיב רב ששת בפרקים שואל מפני הכבוד ומשיב תרגמה ר' אבא במשכים לפתחו יד.
** {ויקרא כב-ז}
תרומה זמן מלתא אגב אורחיה קמשמע לן כהנים אימת קא אכלי בתרומה משעת צאת הכוכבים והא קמשמע לן דכפרה לא מעכבא כדתניא
ובא השמש וטהר ביאת שמשו מעכבתו מלאכול בתרומה ואין כפרתו מעכבתו מלאכול בתרומה. וממאי דהאי ובא השמש ביאת השמש והאי וטהר טהר יומא 
דילמא ביאת אורו הוא ומאי וטהר טהר גברא אמר רבה בר רב שילא א''כ לימא קרא ויטהר מאי וטהר טהר יומא כדאמרי אינשי איערב שמשא ואדכי יומא. במערבא הא דרבה בר רב שילא לא שמיע להו ובעו לה מיבעיא האי ובא השמש ביאת שמשו הוא ומאי וטהר טהר יומא או דילמא ביאת אורו הוא ומאי וטהר טהר גברא והדר פשטו לה מברייתא מדקתני בברייתא סימן לדבר צאת הכוכבים שמע מינה ביאת שמשו הוא ומאי וטהר טהר יומא. ב.
