לא כתבתי את הכל, שיש מן ההערות שלא היו טובים בכלל.
נשלם
** פרק מאימתי
* ב.
** רש"י ד"ה אי בעית אימא -
עיין ברש"י שזה קאי רק על ק’ שניה (וע"פ דרך ישיביש, יש לומר שמתרץ לשני קושיות, לומר שכיון שברא ה’ את הכל, ואף אנו עם הנבחר, איך לא נודה ונקרא קריאת שמע). אם כן, קאי על "בשכבך.” ואם כן, קשה למה לא אומר כפשט הראשון. וצריך ביאור. (אפשר שתירוץ זה מוסיף על תי’ ראשון, ואומר שלא רק כאן נכון לומר לילה ראשון, אלא בכל מקום נכון. כיון שהוא מוסיף והוא אמת, אמר אותו, אף בלי צורך.)
** אי הכי -
עיין בתוס’. בלי מילים "אי הכי,” היה אפשר לומר שמק’ שסיפא (רצה לומר, משנה שלאחר זה) יהא דומה למשנה זה. אבל, לשון "אי הכי" לא משמע כן, אלא משמע שמקשה שאותו הסיבה יהיה שייך גם שם.
* ב:
** במערבא –
ק"ק למערבא, שלא דייקו כרבה בר ר"ש, מהו המקור לבריי’. יש לומר שידעו את הדיוק, אבל לא ידעו אם הוא דיוק נכון ומוכרח או לא. מן הבריי’ רואים שהוא דיוק נכון. (במילים אחרים, מה שהם לא ידעו לא מוכיח שאין מקור. כיון שהגענו לזה, יכול להיות שיש מקור אחר – אולי פסוק אחר ואולי הל"מ.)
* ג.
** אי קסבר –
יש לדון למה יותר טוב לומר השעות:
א. בני אדם מצויים בשעות, ויותר קל להם לדעת שעות.
ב. “אשמורה" אינו כל כך בהיר, שהרי חולקים מהו.
** בבית אפל –
תימא, אם כן דלמא תחילת אשמורות קחשיב, למי שהוא בבית אפל, ורוצה לקרוא ק"ש של ערבית.
** ושמר –
עיין ברש"י. לולי רש"י, יש לומר שר"ל ששמרו מנפילת החורבה. (נראה שרש"י מניח שלא כזה, שלא היה נופל עליו, שמצאנו בתענית שת"ח נשמרים מדברים כזה. אבל, יש לדון, שיש לומר שזהו שמירתו, שיבוא מלאך לשמרו. גם יש להעיר שרק מצאנו שמירה כזה כשלא עבר לסכן את עצמו, אלא נסתרכן באונס. אבל, כאן, הוא סיכן את עצמו, ולא פשוט שיישמר.)
* ג:
** ה"ק מעולם לא עבר –
קשה, אם כן מהו שקלא וטריא של רבי ור"נ.
** משה לא הוה ידע –
צריך ביאור; הא ה’ קאמר כבר חצות, ואם כן, למה אמר כחצות, אף אם, מצד עצמו, היה מסופק. נמצא שיכולים לשנות מדברי ה’ בנבואה, כיון שאינם המילים שהיה משה עצמו אומר. אבל, יש לומר שה’ ציווה לו לומר "כחצות,” כיון שידע שמשה לא ידע.
* ד.
** לאיתערורי –
ודלא כר’ אושעיא.
* ד:
** דתניא קשה –
קשה, לכאו’, כן בפרוש במתניתין. (ובאמת, אולי דבר ר"ג, ואין כ"כ ראיה. אבל, כיון שא"א שסבר כר"א, מוכרח כמש"א ר"ג. וצ"ב.)
** תפילות באמצע –
לכאו’, הא דבאמצע אינו סיבה לשום דבר, אלא נתן סימן לדבר. צריך ביאור למה לא אמר פשוט שק"ש אחר תפילה. (יש לדחות שלצד שברה הוא, הסברה אומר רק שאין ענין להקדים ק"ש, אבל לכאו’ יקדים כיון שדאו’ הוא. ויש לומר שתדיר ושאינו תדיר, תדיר קודם. ויש לדון אם זה נוגע בתפילה, שהוא דרבנן, נגד דין דאו’. ועי"ל שטוב שק"ש יהיה סמוך לשכיבה. אבל, עוד י"ל שטוב שתפילות יהיו באמצע, ולכן אומר לשון זה. ותחשב.)
* ה.
** ואם לאו –
יש לשאול אם זהו הכי efficacious, למה אינו ראשון. וי"ל שאינו הכי טוב; כ"א לא יצילנו מחצי (למשל), אבל אינם אותו חציים.
** אלי נ"ך –
ק"ק למה קדם משנה לנ"ך.
** מוכר –
ר"ל לא רק נתן וכמו ה’, אלא אף אם מכרו, וקבל כסף.
* ו.
** עשרה –
לכאו’, יש לתרץ שעשרה, אף שאינם לומדים, אלא מתפללים.
** תפילין שבראש –
ק"ק שדנים עכשיו במה שלובש ה’ על זרועו. ויש לדחות בפשיטות.
** אין –
קשה מה ראיה יש משם, ששם מגדלים את ה’ בפה, לומר שה’ הוא האלקים.
** לראות –
נראה שיש שלש דרכים לפרש את זה:
א. אם היה רואה, היה ירא, והיה נופל (או מתוך מיתה או שהיה נתעלף).
ב. אם היה רואה את כל השדים שעליו, הם מפילים אותו (ולפי זה, רואה ר"ל מכיר). (על פי זה, מבואר מש"א אביי, ששיייך למש"א אבא בנימין. לאידך צד, ק"ק מה מוסיף.)
ג. אם היה רואה אותם, היו כולם יכולים להזיק אותו, ולא היה יכול לעמוד מפני נזק זה.
** במקום רנה –
קשה, שיאמר רנה בבית. ואם תתרץ שעדיין אינו נקרא מקום רנה, קשה שאם כן נדרוש שצריך להיות מקום תפילה. ותחשב.
** שם תהא –
לכאו’, ר"ל שם "לשמוע.”
** בעדת קל –
ע’ ברש"י. וקשה, שמהיכי תיתי שהעדה ה"ה המקום; להיפך, מסתמא, ה"ה העדה ממש. ואולי, לולי רש"י, יש לומר שדורש מ"מוצב" ולא עומד, שאולי משמע שתמיד שם, והוא שאינו יוצא אף שיוצאים עשרה, ונראה שהוא בביה"כ שברו"פ באים עשרה.
** ומנין -
צריך ביאור מה חשב בהו"א (רצה לומר לפני מש"א בעשרה). עוד קשה למה לא אמר "וכיון שבעשרה בה"כ.”
* ו:
** אבל לעיילי –
צריך ביאור מהו ההו"א, שאמר "יצא" בפ’. ואולי הו"א שלאו דוקא הוא, או שבחול הוא.
** חמשה קולות –
נ’ ש"ברקים" בכלל, שאי לאו הכי, יש רק ארבע. שוב הבנתי שיש לומר ש"קולות" משמע שנים, ואז, אף ששורש של קול נאמר רק ארבע פעמים, יש כאן חמשה קולות.
** אחרי ה’ ירדפו –
צריך ביאור למה הביא קרא זה, ולא "נרדפה.” ואין לומר שיש דיוק שזה רק בשבת, שקשה מהו.
** קמחליין –
קשה, הא דרושים "חפציך אסורים….”
** נקרא רשע –
משמע אם פניו אינו לאחרו, משמע שאינו רשע. וקשה, הרי לקמן אומר שמי שיש לו בעירו ואינו נכנס נקרא שכן רע. כאן, שהוא אחרוי ביהכ"נ, שהוא בעירו, ג"כ יהיה כן. יש לומר שזה במי שתמיד לא מגיע לביה"כ. גם יש לחלק בין שכן רע לרשע.
** כיון שחמה –
רצה לומר שכיון שיש דבר המגלה (ר"ל חמה), פניו נשתנית, אף אדם, כיון שצריך סיוע, זה מגלה שאינו כל כך חזק וחכם, וכשאחר מסייע אותו, בכמה זמנים, זה מגלה עוד מידות רעות. לכן, על זכירות והזכרת דברים אלו, פניו נשתנות.
** רבי יוחנן אמר אף –
ק"ק, שהניח אאם היה הא דמנחה ראיה שמנחה טוב, אומר שגם ערבית טוב, אבל זה אינו, אלא ראיה הוא שמנחה יותר טוב. (כן נראה מלשון הגמ’, ואז הראיה ממה שנקט להתפלל במנחה. ויש לדחות ולומר שהוא רק ראיה שמנחה טוב.) ונראה שר"ל שאף שמנחה יותר טוב, אף מערב חשוב, וצריך זהירות.
** שהוא –
בפשטות, רצה לומר שחברו רגיל. ועוד יש לומר שר"ל שהוא רגיל בחברו, ואומר שאם ברו"ם, אומר שלום, ואמר בכ"ז. ואינו נ’ כן, מלשון "יודע בחבירו.” לצד ראשון, נראה שר"ל שרק לו יקדים שלום, ולא למי שאינו אומר לו שלום, שאינו נ’ כחברות, אלא נראה קצת מוזר.
* ז.
** תנא בשמיה דר"מ –
לכאו’, א"כ אינו בשלש שעי קמייתא, שקמו אחרי כן, כמו שאומר משנה לקמן. אבל, דע ששם יש שני גירסאות – יש שגורסים מלכים ויש שגורסים בני מלכים. אם גורסים שם בני מלכים, יש לומר שמלכים קמים מוקדם.
** כמה חסדים –
בלי ר"מ, היה ניחא, שר"ל שלא זעם בשום רגע. אבל, לר"מ, קשה, שיש רק רגע שזועם בו. אולי יש לומר שר"ל שהוא לכמה ימים. ועד יש לומר שה’ זועם בכל רגע אחר זה, אם לא שכבר זעם. ותחשב.
** תפלתו –
ולולי זה, היה אומר שנקרא תפלה שלו שנאמר לו, ולא מפני שהוא אמרו.
** וקמ"ל –
יש לדון אם רצה לומר ש"יכולים אנו ללמוד…" או שכך היה הסיבה למה שעשה ה’.
** ואין כל בריה –
ק"ק, שיש תרנגול. יש לומר שא"א לו לכון, ורק ממילא נשתנית. אבל, גם הוא לא יודע זמן הדיוק. וא"ת למה לא ידוע מחמת השינוי שקרה בו. ויש לומר שלא מרגיש באותו שינוי. ותחשב. גם יש לומר שאין תרנגולים יודעים שזה מחמת זעם ה’.
** כמימריה –
יש לדון אם ר"ל כמימרא שנאמר או כזמן אמירתו. הראשון נראה מיותר.
** עונש לצדיק –
משמע שהוא מפני שרע לצדיק לענוש.ובט’, משמע שהוא מפני שה’ אינו רוצה במיתת רשעים, אלא בתשובתם.
** צדיק וטוב לו –
לכאו’, קושייתו הוא מ"צדיק ורע לו.” נראה שר"ל שאם תתרץ שלכל אדם, ניתן רק עולם אחד, אז לא היה קשה, אבל א"א לומר כן מפני צדיק שטוב לו, שיש לו שנים.
* ז:
** אין נענה אלא –
לכאו’, יש רק ראיה שצירף זכותו, ולא שמפני זה נהנה.
* ח.
** תנ"ה –
ק’ שמזה משמע שעל תפילה ברבים קאי, ולעיל משמע שעל מתפלל באותו זמן קאי.
** יראי שמים –
ואין להקשות שאם אין "טוב לך" אטו טוב לו בעוה"ז ולא בעוה"ב. ויש לומר שאם יש אחד, מניחים שעוה"ב הוא, וגבי עמל, יש שנים, ואז "אשרי לעוה"ז.”
** כי ברבים –
קשה, אולי ר"ל ברבים ממש. ואולי זה נלמד מ"קל כביר.”
** גורם גלות –
מסתמא, יש הרבה זמנים שה’ רוצה בגלות אחד, אבל כדי שיהיה לו ביה"כ מרחם, ואינו גולה אותו. אבל, זה, אין לו רחמנות זה, שבי"כ ובי"כ אינו הולך לביה"כ.
** שכן רע –
צריך ביאור מה זה שייך לשכן. ואולי מפני שגרם שלא יהיה מנין בביה"כ.
** נהנה מיגיעו –
פשוט שבדברים טובים לחוד נאמר.
** דכייף –
עיין ברש"י. ויש לומר להיפך; אם כייף ליה, א"צ להיות כנגדו לשמוע לו, אבל אי לא כפף ליה, צריך להיות אצלו, שאי לא, לא יקבל את התוכחה.
* ח:
** הזהירו –
נראה על פי מוסר שיסודם שווה, שכל אחד מהם הוא דבר הנראה קטן, אבל באמת, דבר גדול וחשוב הוא.
** משום קלקול –
עיין ברש"י. וקשה, שהא היה לו לומר שיאסרנו. ואם תתרץ שאינו נ"ט, אם כן, קשה מה מיאוס יש. נראה שאפשר שאין שום טעם ממנו, הוא מאוס למי שיודע.
** ומשום מעשה –
נראה שר"ל מפני שמא אירע דבר כזה, והגמ’ קיצר. אבל, לכאו’, לא ידע רבא אותו מעשה, שהיה ר"פ אחריו. יש לדון, שכיון שתלמידו היה, יש לומר שכבר קרה המעשה. גם יש לציין למה שכתבנו במקום אחר, שמצאנו שהיו לרבא תלמידים שהיו יותר זקנים ממנו, שמצאנו שרבא מת כשהיה בן ארבעים, ומצאנו שאמר לתלמידיו בכתובות שהיו אווזים לבנים, מחמת שהיה להם זקן לבן, ומסמא היו גדולים מבן ארבעים.
* ט.
** רבנן כוותי –
קשה, שהא היה לו לומר "מסתבר טעמי,” שהרי פסק שמואל כמותו. על פי דבר בעלאבאטיש, יש לומר שלא ידע שהיה טעמו מסתבר לאחרים. עוד יש לומר שלא הבינו מהו טום רבנן, לומר איזה יותר מסתבר, עד שהשיב להם.
** אחר חצות –
נראה שר"ל חצות, שהרי הכה ה’ את מצרים בחצות, ולא עד חצות.
** בשלמא הזה –
קשה, לכתוב לילה, ונלמד ג"ש מאותו מילה. ונראה שלא ידעינן מאיזה "לילה" ללמוד. גם יש לומר שאין להקשות שנלמד ג"ש. אבל, עיין ביבמות (ד:) נגד זה.
** ביום –
קשה, אם כן למה צריך "בחפזון.” אולי הו"א שנדרוש שיכול להאכל עד זמן חפזון, ואז, מסתמא, גם כן כל היום.
** ביום –
קשה, שכבר נאמר "לא תותירו.” עיין לקמן בגמ’.
* ט:
** מצולה –
החילוק הוא שמצודה שאין בו דגן רצה לומר שאין בו מה להביא אחרים. מצולה רצה לומר שאף אם נראה שיבואו בני אדם, לא באו. ותחשב.
** אני הייתי –
קשה מהו לשון "אהיה,” ולא "הייתי.”
** שלא יאמרו –
עיין בסיפור קצר של מארק טויין במה שעשה אליהו.
** שאם יזכה יבחין –
צריך ביאור על מה קאי. נראה שהוא על מה שקדם מלכי ישראל, ואכתי הלשון "ש" קשה.
** הני יט הווין -
עיין בת’. ונראה שזהו עדו סיבה לסיים כן, ששניהם מסיימים יט’ שהם יח.
* י.
** למה נסמכה –
נראה לי שיש שני דרכים לפרש כל זה:
א. שואל את ק’. ת’ שאנו דורשים סמוכים. אם כן, היה מוכרח לתורה שלא לכתוב מוקדם ומאורח. אגב זה, דרש דרשה אחרת.
שאל קושייתו. תי’ שאינו, שדורשים סמוכים, סוברים שצ’ קרא דאבשלום להיות כאן, כדי לדרוש לגוג ומגוג. נראה שיש להק’ שא"כ נאחר פרשת גוג ומגוג. ואם זה א"א, נקדים פרשת שאול.
** וכל קרבי –
עיין ברש"י. קשה אם כן מהו "קרבי,” ששל אמו הוא. ויש לומר שבראותו קרבי אמו, הבין גם כן בטובת קרובי עצמו. גם יש לומר שהיה קרובים, והיה גופו שלו. אז, נקרא "קרובי.” עוד יש לומר שקראו שלו על מה שהיו זנים אותו באותו תקופה. (הדיון היהי אם דבר על המעיים או על עצמו.)
** עולמים –
קשה שנקראים עולמות שונים.
** כל גמוליו –
אולי שייך קצת לשון "בהגמל את יצחק.”
** מקום ערווה –
מלשון זה, משמע שהעיקר היה שלא היה במקום ערווה. הלשון שלעיל "עשה לה במקום בינה" לא משמע כן.
** צורה בתוך צורה –
נראה שר"ל אדם בתוך עולמו.
** רואה ואינו נראה –
צריך דיון בparrellelism בין זה לברכי נפשי.
** כי מת אתה –
לכאו’, ה"כי" קאי על "מת אתה, ולא על ה"לא תחיה" שבעוה"ב נאמר, ומה לביתו ע"ז.
* י:
** אפילו –
צריך ביאור מהו החידוש, שכבר ראינו שאמר כן חזקיהו נגד נבואה. בפשטות, קאי על החרב חדה. גם יש לומ שהאפילו נאמר קודם אמירת הסיפור, ורק שאינו כסדר בגמ’.
** שגנב –
אפשר לומר שזע"ז היו: גנב ספר רפואה, ואז, לרפואה, באו לאותו נחש שריפא כבר, והתפללו לו. מפני זה, כתתו חזקיה. כיון שנאבדה ע"ז שלהם, התחילו לעבוד עצמות מלכים (כמו שמצאנו גבי יעקב, ועוד יש לומר שהreliance על הספר בא מאחז, ואז עבדו אותו, שהיה שארית מכוח רפואה). לכן, גרר עצמותיו. אבל, רש"י משמע שזה היה מיד במיתת אביו.
** תולים –
קשה, שאי תולים ממש, טוב שיתלו על זכות אחרים, שלא יפסיד זכויות. ואם רק נאמר כן, צריך ביאור למה לא נאמר כאמיתו. צריך ביאור.
** ואם אינו רוצה –
עיין ברש"י, שהחשש בזה הוא משום יוהרא. צריך ביאור איך מה שעשה שמואל יהני. (ושנאה הוא או שיהיה נראה כשונא אחרים או שמתוך שא"א לעשות לו טוב, לא יבוא בני אדם לאהוב אותו.)
** כשמואל –
קשה דילמא שאני שמואל שהוצרך לכך, ששופט היה, ולא רצה שיהיה שום שוחד.
** מאי לא הפסיד –
עיין ברבינו יונה, שמביא שיטה שפי’ ש"מאי לא הפיסד לענין דברים שבכ’ א"א רשאי לאומרם על פה.” קשה, שבגמ’ לא אמר כן. נראה שלפשט ראשון קאי. אף שנדחה, סובר שאין אותו הדין נדחה. ותחשב.
** תניא נמי הכי –
נראה שזה רק ראיה שדינו אמת, ולא שזהו מה ש"לא הפסיד.”
** מאי לא הפסיד –
שקה, אם כן מהו ה"כאדם הקורא.”
** יותר גדול מת"ת –
נראה שר"ל מפני שבכללו ת"ת.
** אמר ר"ט –
בפשטות, מביא מעשה שנהג כב"ש. ויש לבאר שמקשה איך "בלכתך" משמע בכל דרך שרוצה, שהרי יכול אדם להטות בדרך. אמרו לו שעבר על דבר בית הלל, שבית הלל אמרו שסכנה הוא. (נראה שר"ל שלא רק חייב מיתה כיון שעבר על דברי בית הלל בק"ש, אלא שעבר על דברי בית הלל בסכנה, שב"ה אמר שזה סכנה, ולכן אמרו שאי אפשר להטות בדרך.)
* יא.
** אבל חייב –
לכאו’, יש לחלק ששם עושה ה’ שמשכח צערו. כן קצת נראה ממה שאונן פטור. ובאמת, צ"ב בזה.
** יהיה כנגד –
ע’ ברש"י. עוד יש לפרש שאומר שגדילו כנגד האומרים לו להשחית את זקנו. נראה שר"ל שאומרים שטוב מה שמשחית.
** שמא יראו –
יל"ד אם ר"ל שלא היה לשום אחד לנו להטות מפני חשש זה או שר"ל שכאן שמטת, לא היה לו להטות, אלא לעמוד להורות שלא להלכה צריך להטות כב"ש.
** כי דרך –
יש להקש’ איך נתרץ "בשבתך" שאינו כ’ שם דרך. ואולי אין הכי נמי, היה אפשר להק’ כן. ועוד יש לומר שעכ"פ נסמך לדרך. עוד יש לומר שנסמך ללכתך (ועל זה, יש להק’ אם כן למה צריכים "שבתך" ו"לכתך" שיכתוב רק אחד ונלמד ממנו חברו. ויש לומר שאם היה רק אחד ממשמעות חברו, מדילוג ך יהיה משמע להיפך.)
** דתנן –
צריך ביאור בראיה זו, ששם ב"ש מחמירים, ואז סוברים שאם עשה קולא, אינו יוצא. אבל, כאן, ב"ה מקילים. נראה שב"ה גם מחמירים לומר שזה נחשב סכנה.
* יא:
** להזכיר מדת –
לכאו’, יש שני דרכים לבאר את זה:
א. הוא כדי להזכיר מדת יום ולילה, ולא מפני שכן כ’.
ב. אומרים כמה שכ’ כדי שנזכור מדת יום ולילה. לזה, קושיית גמ’ ד"אם כן לילה" צריך להיות שסובר גמ’ שאין מעלה בהז’ רק לילה ביום בלי יום בלילה.
** לגמ’ א"צ –
עיין ברש"י. וקשה למה אומר כן רק כאן, ולא גבי "למדרש.” ראיתי שיש גורסים כן.
** לגמ’ –
עיין ברש"י. נראה שהסיבה הוא שיש יותר קדושה במקרא ממשנה. וקשה למה יש יותר במדרש ממשנה. ברבא, יש לדון אם ר"ל שיש יותר בגמ’ ממשנה או שוה או שאמר שאף על פי שיש פחות, מברכים על אותו פחות. (גם אפשר שאף שאין כל כך קדושה בו, צריך לחשוב בו יותר, ויש שווה קדושה בלומדה.)
** הממונה –
עיין ברש"י. וקצת קשה למה צריך לומר את זה.
** רש"י אמר להם הממונה –
עיין במה שכ' רש"י. ולכאו', אינו שייך כ"כ.
** יחלה –
יש לדון מה רצה לומר:
א. צריך שיצער את עצמו עליו (או רצה לומר סיבה (שיצער את עצמו) או סימן (שיהיה במדרגה שממילא יהיה לו צער)).
ב. שיתפלל מאד עד שיחלה.
ג. שיקבל יסורים על עצמו לרפואת האחר.
** עמי –
שמואל היה מובטל לו שלא לעלות בדין, כמש"כ בחגיגה (ד:).
* יב.
** דאי נמי –
נראה שהגמ’ מניח שכיון שברכה א פועל למין של ברכה ב, גם מחשבה לברכה א פועל לברכה ב’, שמוכרח שבכלל א, יש ב. יש לדחות שהברכות שאני, אבל שניהם יכולים להתיר דבר אחד. רצה לומר, אין שהכל כולל כל ברכה, אבל כולל כל מין שאוכל.
** תמרי מיזן -
יש לדון אם זהו קמ"ל או שקמ"ל הוא כמש"כ לעיל, שאם כיוון לומר ברכה כוללת וארמר ברכה מועטת, יצא. נראה שאם כן, לא היה מביא ציור דנהמא, אלא ציור שלעיל.
** התם קב"ה –
נראה לי שני פשטים בזה:
א. חד היה דיבור ה' לאברהם, וחד היה ציווי התורה. צריך עיון אם זה נכון.
ב. בשנותו את שמה, קרה לה שרי, כלומר: את – שרי – תהא לך שם אחרת, שהאו שרה.
* יב:
** אם ת"ח הוא –
צריך ביאור מהו התלייה בין תפילה ובין מה שהוא ת"ח. ועיין ברש"י.
* טז.
** רש"י סרכיח –
עיין ברש"י. עוד יש לפרש שכיון שהתחיל ב"למען," מניחים שלא טעה, ושבזה קאי.
** מה שאינן –
עיין במש"כ. וא"ת גם ק"ש צריך כוונה. ויש לומר שלזמן יותר ארוך צריך. ועוד יש לומר שסוג אחר של כוונה היא. וצריך ביאור. עוד יש לומר שאין הענין שצריך כוונה, שזה מדרגה קטנה, אלא שירצה לכוון יותר מפני שרחמים הוא.
** מה -
במש"כ, "דצלותא רחמי נינהו, ובעי כוונה," יש לדון אם רצה לומר שני דברים או שהראשון סיבה לשני, שכיון ששואל לשום דבר, אינו נחשב שאלה כל כך או שש בזה בזיון, בלי כוונה.
** רש"י לפי –
עיין ברש"י. עוד יש לומר שפועלים אינם יראים, שכך אורחיהם, דלא כבעה"ב.
* יז.
** רש"י ושמא –
עיין ברש"י. עוד יש לומר שמא תאמר אינו יותר טוב....
** רש"י ערום ביראה –
עיין ברש"י. עוד יש לומר בלי תחבולות שמכסים אותו.
** שלא כסייעתו –
צריך ביאור למה צריך שלשתן.
* יח.
** יותר מד"א –
קצת קשה אם כן למה תלאו ב(ה)ולך בכיה"ק. יש לדחוק שכן דרך ביה"ק.
** פרק שלישי
* כ.
** אי משום תנויי –
אפשר להקשות מהו ההו"א לזה, שהרי בפ' אינו נכון. ואין זה כ"כ קשה, שמי יאמר איך פשוט הוא שאינו אמת. ועדו שי לומר שראשונים אינו רק זמן ר"י, ובאמת, היו זמנים שהיו בהם יותר תורה. (ולפי זה, תירוץ הגמ' הוא שגם ימות ר"י היו ראשונים, ויגלה על השאר.)
** כרבלתא-
נסתפקתי אם חטפו מפני שהיה בה כלאים, ונקט צבעו מפני שהיה לו להבין שלא היתה ב"י מזה או שהבעיה היה שהיה אדום ומפני זה חטפו. (וא,ת יותר גרוע אם לא מלובשת. ויש לומר שידע שהיתה מלובשת דבר אחר תחתיו.)
* כ:
** כמצות –
ויש לדון אם ר"ל שמפני שזמנו ברו"פ קבוע, הו"א שנשים יפטרו או שהו"א שקרא זה מדמתו לזמן גרמא כדי לגלות שנשים פטורות עליו.
* כא.
** אלא ק"ש –
קשה אם כן למה אינו אומר ק"ש כמו ביהמ"ז.
** ר"י... קו"ח –
פשוט שרק אחד קו"ח, שכיון שאותו דין נלמד, השני מ"מ.
** אמת ויציב –
קשה לחזור על שמע במקום אמת ויציב, שיש בו תרתי, ועוד שאין בו ספק ברכה.
** אמת... חוזר –
לכאו', זה רק כשלא אמר קריאת שמע (צריך לומר שאף על פי כן, אינו ברכה לבטלה), דאם לא כן, כבר קיים את חיוב שלו בקריאת שמע. ותו"ת.
* כא:
** איך דריב"ל –
לכאו', אם כן נמצא סתירה בדבריו. נראה מזה שאפשר לדרוש ב' סמוכים. אלא, שכיון שכבר דרש ר"י אחד, אינו מוכרח לו לדרוש אחר.
* כב.
** מה אש –
ועוד שאש מטהר (כמו שמצאנו שה' טובל במקווה של אש).
** שזו –
יש לדון אם זה אף אם יאחרנו עד שנקרא פושע.
* כב:
** נחזי –
קשה זו עדיין קשה במח' רבנן וריב"ב.
** אלא נפול –
לכאו', הענין הוא שרב פפא אמר שנפל עליו ט' קבים. רבא השיב לו שאין זה סיבה, שהרי לא מהני לאחרים. לכן, לא יתן לו. אלא, רבא אמר שיתנו לעצמו, שעליו נפלו ארבעים סאה. (נמצא שאף בלי הוכחתו היה שווה לרב פפא; הוכחה שלו רק עשה שהוא יותר טוב מרב פפא.) שוב אמר רב הונא שלא זה ולא זה קרה לו, אלא לא היה טמא בכלל (שהלך למקווה מזמן שהיה בעל קרי.) (יש לדון אם "לא זה ולא זה" רצה לומר לא בעל קרי ולא מ' סאה או שרצה לומר לא ט' סאה ולא מ' סאה.)
* כג.
** תקנו שיהיו מניחים בידיהם –
קצת קשה למה לא יתקנו שיתם בחורי ביה"כ. אל תאמר שזה א"א מבלי ליכנס בבית הכסא, שאפשר לדחפו. זה מניח שחורים הלכו על פני כל הכותל. ועוד, שכן מוכח מבריי' לקמן, שמבאר סדר תקנות. צריך לומר שכבר בטלו זה מפני עכברים.
** איבעיא להשתין –
עיין לקמן, שיש בריי' שאוסר את זה בפירוש. עיין לקמן בגמ' שדן בבריי' זו.
** דכ"ע אם שהה –
לכאו', יש לומר להיפך שכו"ע מודים שכששהה א"צ לחזור. וצריך לומר שהיה מסתבר לגמ' שצריך לחזור, ולכן הניח שכולי עלמא סוברים כן.
** הכון –
משמע שהענין הוא שצריך לזהרר לפני תפילה, ושלא יצטרך לנקביו בתוכו (או שרע הוא אם יצטרך (ר"ל שהתפילה אינו כ"כ טוב) או כדי שלא יפסיק) ואם לא הכין, זלזל בתפילה, וצריך לחזור. בלי זה, היה אפשר לומר שכיון שתפילה כשצ' לנקביו רע, אינו יוצא בתפילה זו.
** מהו שיכנס –
קשה, אם יכול (ואף לרבא) למה צריך לחלוץ תפיליו ברחוק ד"א. צריך לומר שהוא כמו גזירה. לב"ש, אפשר לומר שצריך לחלצם שם (או שמסתבר יותר לחלץ אותם שם) כדי שיטלם סמוך לשם. וא"ת מהו הסברה שלא יטלנו בתוך בית הכסא אבל יניחם בבית הכסא עצמו. ויש לומר על פי דרך פשוט ש"בטל" קצת לו. עוד יש לומר על פי דרך ר' שטיין שמיחסים לו, נתמעט קצת יחסם עם בית הכסא (ואולי זהו מושג "בטל לו." עוד יש לומר ששם ר"ל שאין שמו תפילין כ"כ אלא "מלבושיו" או "הוא עצמו." ותחשב.
* כד.
** ולאגמורן –
עיין ברש"י. עוד נראה שלכך הודיע להם שהיה יום טבילה.
** הכא מאי –
נראה שר"ל הכא – שאין תיובתא 0 מאי – היש קו"ח שנפסוק כמותו.
** היכא –
י' במש"א לעיל שלכאו', בפי' אמר שם שאינו בכ"מ (שאמר שהוא "כל לנטרינהו טפי עדיף.")
** באשתו –
עיין ברש"י. ק"ק למה לא אמר בפנויה. ואולי שכיח נקט.
** קל –
יל"ד אם גם זה לק"ש מיירי, שמדכלל עם ירך וכדו' משמע כזה, שאפשר שזה חידוש ב"איסתוכלי ביה," שהוא שכיון שאינו מן הגוף, ואינו מסתכל בו, יהיה מותר.
** שער שער –
בפשטות, רצה לומר שער שער מהו, שדבר קטן וגרוע הוא. עוד יש לפרש שרצה לומר ש"שער" אינו אלא "שער" כמו שער הגוף, שאינו יותר רע משער שעל ראשו, והרי הוא כשער סתם.
* כד:
** לא צייתנה –
אולי מפני שלא היה מסתבר לו כן או מפני שסתירה הוא בדר' יוחנן (כמש"כ לקמן).
* כה.
** סכנתם –
עיין ברש"י בלשון כמעט. נראה שצריך לחזוק מהו הסכנה: שאם יבעול יהיה סכנה, דילמא ימות מחטאתו. ב. במצב הזה יש סכנה, דילמא יבעול. ונראה שרש"י סובר כראשון.
* כה:
** והרי לבו –
עיין ברש"י. צריך ביאור למה פי' רק כאן, ולא לעיל. נראה שמשום עקבו נקט.
** מתכסה –
צריך לומר שר"ל כל גופו, דאל"ה מה בין זה לצלולים. וצריך ביאור אם הוציא את ראשו כדי לקרות, מה ביניהם. ואולי החי' הוא שכוע"מ. וצ"ב.
** פרק רביעי
* כז.
** לאחוריה דרביה –
יש לדון פשט בזה:
א. נראה שמשווה את עצמו לרבו, שתפיפלתו "שייכת" לשל רבו.
ב. נראה שמשתחווה לרבו.
ג. גורם שאי אפשר לרבו לעבור.
מגמרא זה, שלא חידש עדיין איסור עבירה לפני המתפלל אי אפשר לומר כשלישי. אבל, רק אי אפשר לומר שזהו הטעם בהו"א. אבל, יכול להיות שהוא הטעם במסקנא, ולומר שבהו"א עדיין לא נודע הטעם.
* כז:
** רש"י ד"ה אחורי רבו –
עיין במה שכ'. וכן נראה מר"א (שבכלל עם מחזיר שלום...).
* כח.
** וחד אמר –
יש לדון אם רצה לומר כן היו או כן ניתוסף.
* ל.
** שאמר משום ראב"ע –
קשה, אם כן נפסוק כתנא קמא, שגם הוא אמר דבר בשם ראב"ע. ונראה שאין "שאמר" סיבה, אלא רצה לומר, "במה שאמר."
* ל:
** רש"י מאן –
עיין במה שכ'. עוד יש לומר שר"ל מאן גברא שעליו מסהדין, שגברא רבא הוא, ובוודאי כיוון.
** פרק חמישי פרק אין עומדים
* ל:
** והיא מרת נפש -
נ"ל שלש דרכים לפרש גמרא זה:
1. הגמ’ סבר שכיון שאמרה שהיא מרת נפש, מסתמא גם אנו צריכים לכוון לבנו כמותה. דוחה גמ’ שאולי רק ר"ל שמרה היתה.
2. הגמ’ סבר שכיון שאמר שהיא מרת נפש- ומה צורך יש להשמיענו את זה- מוכרח שכוונתו לומר שגם אנו כמותה נהיה. יש לדון מה דוחה:
א. דוחה שאמר כן להגיד שהיה צערה גדול מאד (וזה פרט בסיפור ומוסיף בסיפור.)
ב. דוחה שרק עצה טובה אומר (זה רק אפשר אם זה חוב. ע’ בשי"ח ש"י (גלגל חמישי-כאן).)
ג. דוחה שרק אומר שמי הוא כבר בכובד ראש אינו יכול להקל ראשו, שזה בודאי בזיון (ועוד,
שאין בזה, לכאו’, כל כך טורח.)
** והיא מרת נפש –
נראה לי שלש דרכים לפרש גמרא זו:
א. הגמרא סובר שכיון שאמרה שהיא מרת נפש, מסתמא גם אנו צריכים לכוון את לבנו כמותה. דוחה גמ' שאולי רק בא לומר שהיתה מרה, ולא שנהיה מרים.
ב. הגמ' סובר שכיון שאמרה שהיא מרת נפש – ומה צורך – מוכרח שר"ל שגם אנו כמו זה. דוחה גמ' שאולי אין חיוב לזה, אלא, אם אדם מר, לא ימתק את עצמו לתפילה, שזה גנאי, אלא ישאר במרירותו.
ג. הגמ' סבר שכיון שאמרה שהיא מרת נפש – ומה צורך – מוכרח שר"ל שגם אנו כמו"ז. דחה גמ' שאולי אמרה כן מפני שמרירותיה חלק גדול בסיפור. (זה כמעט בצד ראשון, אלא שלצד ראשון אין ההו"א כל כך מובן, שמצדד שההו"א ללימוד הוא שמבארים למה היתה מרת נפש.)
נראה להוסיף עוד צד, והוא שאולי הגמ' אומר שצריך קרא לומר שאף מי שמר מאד יכול להתפלל, שכיון שהיתה כל כך מרה, הו"א שלא יכולה להתפלל. ותחשב.} – גי' אחרת של אותה נקודה, עם קצת הוספות.
** כי הא -
קשה; הא כבר יש "הכון" (שבת י.)
* לא.
** מר"י רביה -
נ’ שלרבותא נקט ששמעה מר"י בהיותו רבו ולא חבירו, ומאותו זמן, שמר על עצמו.
שכן מצינו- צ"ב מה ר"ל. ותח’.
** מאי הל’ פסוקה -
צריך לפרש ארבע דברים:
1. אם חולקים.
2. במה חולקים.
3. מהא שאלת גמ’; כמה וכמה משניות הם פשוטים כאלו.
4. למה צריך הלכה פסוקה (ואם יש להוסיף ולבאר על מש"כ רש"י.)
אפשר שהיה קשה לגמ’ נקודה שלישי, ולכן שאל מהו אותו הלכה.
ת’ ראישון הוא הל’ שממנו רואים גדלות כלל ישראל, ויחשב שאין לגדול לחטא ולא לכוון. אז, יהנה את תפלתו.
ת’ שני הוא משנה שמראה שפלות האדם, שרגילים בני אדם להפסיד מצוה שלא להפסיד ממון. ידע שבא לחטא תמיד אי לא יזהר, ואז ישים לב.
ת’ שלישי אומר משנה שמראה גדר דרבנן, ומראה שצריכים לעשות גדרים כדי שלא נחטא.
(אולי הם כנגד סלבודקא, נובהרדוק, וקאלם.)
** וכן -
צריך ביאור מהו ה"וכן," שבזה צריך שמחה של מצוה, ולא דבר הלכה. יש לומר שקאי על "ולא. . . “ גם יש לומר שבשניהם צריך שמחה של מצוה, אלא שבשני צריך גמ’ לפרש איך יעשנו, כיון שאינו כל כך קל לשני בני אדם לשמח בשמחת מצוה בהדדי.  שו"ר בגי’ אחרת.
** שכן -
צ"ב מה זה. מרש"י נראה ששמחה של מצוה ה"ה שבח והוא שמחה של מצות שמחה, והוא שבח וכדו’.
שמתוך כך- בזה, אינו כתפלה, לכאו’.
** שכן -
נראה שאין זה ראיה על "שמתוך כך . . . ,” אלא על מה לעשות (אם כן, לכאו’ מוכרח שמוסיף סיבה. וי"ל שזהו הסיבה לזכרון; שיאמר לו חבירו דבר, ויענה לו . . . , ומתוך כך זוכרו.
** זוכרהו -
לכאו’ על חבירו קאי. ותח’ אם יכול להיות קאי על ההלכה.
** יכול יהא כוללם -
יש לדון אם יצטרך להפסיק, כמו בין תפלה לתפלה.
** אל הרנה -
זה נראה מוזר. נ’ שרנה אי אפשר להיות שום דבר חוץ מתפלה, ותפלה אפשר להשמיע גם כן בקשה. אז, צ"ל כמה שאומר גמ’.
* לא:
שצריך להודיעו- קצת קשה; דילמא אמרה כן מפני שרצה ברכה. אולי דורש ממה שאמר כן קרא. ישלדון, שאולי אמרו כדי לבאר מה שצריך לברכו.
משום- אין זה מגלה כל המעשה, ורק סמך הוא.
אדון אתה- צריך ביאור מהו דרשה זה.
איכא דאמרי- נראה שיש שלש חילוקים בין שניהם:
1. אם גם נאבדה ממני רוח הקודש.
2. אם דנה לכף חוב או רק חשדה.
3. אם ר"ל שאינך אדון בדבר ואין לך שכינה או שאינך אדון במה שאין לך שכינה.
ונראה ששכינה היא המדרגה העליונה שנותן יכולת לאדם לברר דברים; רוח הקודש הוא המפסיק אותו מלחטוא ולהניח רעות. נ’ שלצד ראשון אמר שאתה אינך אדון בדבר זה (ר"ל, אתה אדון על רוחך, שעדיין יש לך רוח הקדש, אלא אין אתה אדון על מעשה זה), והסיבה לזה, ביארה, היא שאין לך שכינה, ולכך חשדה; אבל לא דנה לרע, שעדיין נשאר לו רוח הקדש. פשט שני אומר שאמרה לו שאתה אינך אדון על רוחך (ר"ל רוח הקדש ושכינה) ומפני זה, דנת אותי לרע, שהרי לא היה לך אף רוח הקדש.
** אר"א לחושד -
נ’ כדרך ראשון שלעיל.
** מי לא ידעת -
מסתמא, זה על ראשון ג"כ קאי.
** אלא שצריך לברכו -
יש לדון אם ר"ל שצריך לפייסו ולברכו או שפיוסו יהא על ידי ברכה. לצד ראשון יש לדון אם צריך ליתן עוד ברכה אם פייסו על ידי ברכה.
** ויסתתרו -
יש לדון למה זה רע. נראה שש מהלכים:
1. חשד הוא. קשה, ששותים. ויש לומר שבעלם לא ירצה לשתותם.
2. יבטלו מתפלה.
3. אולי יבאו לידי עבירה (שיסתרו)
4. יעברו על איסור ייחוד.
5. לאיזה צורך לא נתן ה’ להם בנים. צורך זה יבטל. (אפשר שזה שוה ל2.)
6. רשעים יעברו, ויטענו שרצו בנים. (אולי רק יסתרו או אולי אף יבעלו, ויסמכו שבעלם לא ישתה אותם.
** אל הנער -
צ"ב מהו ת’ זה:
1. אמרה לו למחול על כבודו.
2. אמרה שהתפללה לבן בינוני, ואז אי אפשר שכיוון לאותו דרשה- ולשום דרשה- אי לאו ששמע כן מרבו. אז, יהא כמש"א גמ’ (שכחתי איפה) שסתמו הוה במזכיר שרבו אמרו. (יש לדון אם זה יעשה שלא יחייב.)
* לב.
** עכשיו -
לכאו’, זה פיגיוראטי"ב, שהרי יהיו נאבדים. (ואולי קאי על זרעו או על אומות העולם).
* לב:
** אמר"א (שני
)- ק"ק; דילמא צ’ שניהם.
** מקצר -
לכאו’, יש לדחות שזה בגוי.
* לג.
** מעידין שמת -
לכאו’, זה גם כן סתירה עם מתניתין אף בלי ר"ש. י"ל שבהו"א סבר שצריך למסור נפשו. צריך ביאור למה. אולי לתפלה, שנפשו תלויה עליו, צריך למסור נפשו. ודחוק.
** ראה שוורים -
כמש"א "מלא עינו.”
** דתני ר"א -
יש לדון אי יש מכאן ראיה לדין תפלה או רק שצריך להרחיק, ואז צסתבר שהוא אף בתפלה.
** וקבעוה בתפלה -
מסתמא אשרו קצת, שאי לאו הכי, קשה איך אפשר בכוס (שיקבעו חיוב). ותע"ז. ויש לדחוק שכאן רק היה חיוב, ואם נאנס, נאנס. לעיל היה דרך יחידי להבדלה. ותו"ת.
* לג:
** מטין -
צריך ביאור מהו ראיה זה שא"ת שהוא שיש ראיה מזה שיש חולק, יכול לאומרו אף בלי מטין.
** הכל בידי -
יש שמקשים מצנים פחים. ויש לומר שזה בקר’ של אדם וזה במה נעשה לו.
* לד.
** אמצעית חדא -
יש להקשות שאף לר"א מוכרח כן בברכות ראשונות. ויש לומר שאין הכי נמי, ויוקים את המשנה באמצעיות.
* לד:
** רש"י באבות –
עיין ברש"י. ועוד יש לומר שיותר חשוב הוא (וכמו באיכא דאמרי).
** פרק ששי
* לה.
** אשכחן לאחריו –
קצת קשה שנימא אשכחן לפניו, שזה אינו כל כך מחודש. ויש לומר שיותר מסתבר לומר כן, שכבר מצאנו כן. וקצת קשה שאף מצאנו ברכה ראשונה מקו"ח. וצריך לומר שיש חשיבות במה שכבר ראינו כן  מפורש בקרא. ולא נ' ברש"י כן (וזה מבאר למה הוצרך להביא את הקרא.) ועיין בתוד"ה תינח. (ואולי רצה ליישב א"ז. וק"ק למה לא בארו לעיל.)
** שכן חייב בעוללות –
נראה לי שני דרכים לפרש את זה:
א. זה סימן שהוא יותר חשוב, ואז ראוי לקבל ברכה.
ב. זה סימן שהוא יותר "אינו שלו," ולכן צריך ברכה יותר.
** מה שבעת –
קשה א"כ למה צריך כל הני קראי דלעיל. עיין תוד"ה אלא.
** ועוד התינח –
קצת קשה למה מקשה כן, שכבר תי' לזה.
** אלא סברה הוא –
קשה למה צריך כל הני קראי דלעיל. עיין בתוד"ה אלא. עוד יש לומר שסברה זו נלמדה מכל הני קראי, שמסתבר שאין באים כולם ללמד דין מיותר, אלא סברה. (אבל, קשה, שלמס' הסברה מדרבנן.)
** ר' לוי –
קצת קשה, שנלמד ברכות מזה. ויש לומר שלאחריו לא נדע. עוד יש לומר שהוה דרשינן כרחב"פ.
* לה:
** מחטיא –
צריך ביאור במה מחטיא.
** רש"י וכנסת ישראל –
עיין ברש"י. לכאו', אפשר לומר שגונב אותם מפני שמחטיא אותם. עיין לקמן ד"ה חבר.
** סעיד –
לכאו', יש שני דרכים לפרש את זה:
א. זה סימן שיותר חלוק מעיקר הפרי.
ב. זה סימן שיותר חשוב (ולכן ראוי לו ברכה חדשה).
** חבר –
ק"ק אינו חבר לו, אלא הוא עצמו משחית בנ"י. ונראה שרק משחית אחד או שנים, אבל מפנ"זד דוחה לירבעם.
* לו.
** רש"י כיון דאית ליה הנאה –
עיין ברש"י. ועוד יש לומר שהקמ"ל הוא שכיון שיש הנאה מרפואה, מברך עליה. לכאו', ידע רש"י שאין זה הדין.
** וכל היכא –
היה אפשר לומר שצ' זה רק כשמתקשה (שכשמתקשה, צריך יותר דעת לרכותו, אבל אם בכ"ז רק הוא, למה יצטרך דעת).
** וקמחא דשערי –
ועוד יש לחלק שלא הגיע לסופו.
* לז.
** כמעשה קדירה –
קשה למס' למה נקט מעש"ק ולא ביצים וכדו'.
* לז:
** אינו מברך ולא כלום –
ויש להקשות למה לא אוקמוה כר"ג:
א. יחיד ורבים הלכה כרבים.
ב. אם כן, היה צריך למחוק בבא.
** פורכן –
צריך ביאור בגדר זה, שלכאו', הו"א שבעיקר לא נשתנה (שאם לא כן, כשחותכו לאכלו או ללפסו, לא יהיה מברך שלש ברכות עליה).
** ואי בשעירסן –
לכאו', מתירוץ זה גופא, יצא ראיה.
* לח.
** איכא דאמרי –
צריך לחלק בין השני לשונות, שמגמ' נראה שני חילוקים:
א. הראשון צריך להביא ראיה.
ב. השני מוסיף שרפואה ממילא בא. וצריך לחשוב.
* לח:
** רש"י טעמא –
עיין במה שפרש"י. צריך לפרש איך זה נכנס מילת טעמא. (ואולי ר"ל כמו טעמי מקרא, שהם שם לס' קרא. ודחו"מ.) ונראה שר"ל שמפרש את הטעם לשניהם, שהוא אותו קרא, ואז, יהא אותו קרא מבואר.
** רש"י בר מן דין –
עיין ברש"י. עוד יש לבאר "בר ממנו (ר' בינמין), ובר ממנו (רחב"א)" רצה לומר חוץ ממי היו אומרים, יש עוד להשיב....
** רש"י ואני אומר –
ע' ברש"י שכ' שהוא ליישב דבריהם. עוד אפשר לומר שסברת עצמו קאמר, אבל יודע שחולקים. עיין רש"י לקמן, שמפ' לשיטתו.
** ואני אומר –
צריך לבאר למה פי' כן, ומה יישוב צריך. ונראה לפרש שסבר שקשה לומר שהכל מראיית גמ', וקשה לומר האדמה, שאין ראיה אלא לתחילתו שהכל שהוא האדמה, דאטו רק בלחים חיטין קמיירי. (והחולק – אם יש חולק – או סבר שרק ראייה הוא, ולא מקור, או שמסתמא בכל מין מיירי (או מסתמא בחטין, שהוא עיקר).
** מאי קמ"ל –
נראה לי בזה שני קושיות:
א. קשה דילמא לא עשה כן אלא מפני שכן פסק שראוי לעשות, ואם כן, מה היה לו לעשות – אטו יהיה מראה הלכה שסובר שאינו נכון.
ב. מהיכי תיתי שהוא רצה לקיים כל השיטות, שאולי כר"נ פסק.
ג. למה נוהגים לברך המוציא ולא מוציא.
נראה לתרץ כולם לומר שכיון ששניהם נכונים, לייחד ה' בה"ה הידיעה יותר טוב. ידע גמ' שפסק כרבנן, שהרי רבים הם. אז, ידע שהוה ליה לומר כוותיהו כמש"כ. (ק"ק אם כן, אמאי תלאו במה שמראה לבני אדם, ולא בפי' כמש"כ. וצריך ביאור.)
* לט.
** דזיין –
או י"ל שמפני זה הוא יותר חשוב או שמפני זה, אכילתו יש בו יותר הנאת הגוף, ומביא לברכה.
* לט:
** סמרוסי –
נראה שרצה לומר שמור בתוכו. וא"כ, צריך לומר תי' כאשכנזים (כמו s) או כמו בבליים (כמו th). וצריך לומר או ששי"ן (sh) דומה לס או שכבני אפרים אמרו אותו (איני זוכר איזה שבט, אבל יודע אני שהיה שום מעשה כזה בשופטים במילת שיבולת שאמרו סיבולת.)
** אלא היפה –
קשה אם כן יש ראיה שזהו היפה. וצריך לומר שיש חלוק בין ברכה לתרומה.
* מ.
** דאמר ר' יהודה –
יש לדון אי רבי יוחנן חולק על זה או סבר שעכ"פ אינו דייראק"ט.
** אין מי רגלים –
כ' ברש"י שמציאות אומר. ועוד אפשר שעצה אומר לנו, שלא יחשבו בני אדם על בניו. (ומלשון גמ' לאחר כך, נראה כעצה. ויש לדחות ששם אומר עצה כדי לגמור, שזה, מסתמא טוב.)
** לא נצרכה –
לכאו', היה אפשר לגמ' לומר "לא נצ' אלא למעט מרבי יהודה," אלא שזה היה יותר מסתבר לגמ'.
** מביא ואינו קורא –
או שסוברים שאין הקרקע עיקר או שסוברים שאכתי צריך קרקע הראוי.
** תן לו מעין –
נראה שהפשט בזה הוא שמסברא, כולי עלמא מודים שצ"ל שום שייכות בין הברכה להמאכל. ור"י דורש שצריך לא רק שייכות, אלא יחס יותר קרוב מזה.
* מ:
** סד"א הני מילי –
מגמ' משמע שאינו חדוש שיכול לעשות מה שאמרו חכמים, והחידוש הוא רק שאפשר לאומרו בלשון חול ולשנות.
** שאין בה –
יש לדון אם מוסיף (ר"ל לא ששמע רב והוסיף, שבדרך כלל, לא שמע ר"י את רב, אלא שר"ל שבברכה צ"ל שה' ה"ה המלך וכדי לעשות כן, צריך לומר שם ה') או חולק (ויכול לומר ברוך אתה מלך.). ועוד יש צד שהגמ' אומר כן להוסיף (ור"י עצמו אמר שניהם.) לקמן, נראה כשלישי (וראשון.)
** כמהין –
קשה, הא בפ' אמר שאינו נק' "פרי הארץ," ואז בפה"א אי אפשר. ונראה שמקשה מלשון הבריי'. אבל, אם כן, קשה מהו הקושיה ותי' שני של הגמ'. וצריך ביאור.
* מג.
** דעתיה לארוחי –
צריך ביאור מה היה ההו"א. ונראה שחשב הגמ' שכשאוכל, עושה מעשה, וכשמריח, כמעט בא לו הריח. (רצה לומר, שריח הוא דבר שבא ממילא), ואז, דילמא אפשר לברכה לחול על מעשה שעושה לעתיד ולא דבר שיקרה לו (צ"ב), מה שאין כן לאחריו, שאפשר לברך על מה שכבר נהנה (וצריך ביאור למה זה א"א לפניו). והמסקנא הוא או שאפשר ברכה לחול על דבר שאינו מעשה או שחל על ההנאה או שזה מעשה (שאפשר להפסיק אותו).
* מג:
** הוי אומר –
יש לדון מהו ההו"א. ואולי הוא כמש"כ. ועוד יש לומר שהוא שאינו הנאה לגוף, אלא לנשמה (ויש לדון אם הקמ"ל הוא שא"צ הנאה לגוף או שהוה ג"כ הנאה לגוף או שמתוך שנהנה נפש, נהנה גוף), או שאינו הנאה כ"כ. עוד יש לומר שבאכילה, יש שתי תוצאות – הטעם ומה שהוא זן. בכל מאכל, השני נוגע קצת, ואז על כולם יש לברך. אבל, בריח וכדומה, יש רק ראשון, ולכן הוה אמינא שלא תקנו ברכה. יש להוסיף שהראשון יותר סבגוקטי"ב, ויש לומר שעליו לא תקנו ברכה.
** קבוע –
קצת קשה איך קבעו. ונראה שקבעו שלא ביחיד.
* מד.
** רש"י ההוא מבעי –
עיין בש"י. נראה שיש שתי דרכים לבאר את זה:
א. אינו מיותר שנאמר שבא לחלק, אלא יש דרשה.
ב. הוה חלק מדין זה, והוה כאומר "חיטים שאינם כססים," ואז איך אפשר לחלק.
* מד:
** רש"י כאידך דר"י -
עיין ברש"י. ודחו"ק. עוד יש לומר שר"ל שאנא ס"ל שיש איסור באכילה, ולכן לא אכלתי, אף שזה יתיר אותי בדבור. וקשה לא לאכול ולא לדבר. עוד קשה למה נדחה את זה מפני זה, ולא להיפך. אולי שב ואל תעשה עדיף.
** פרק שביעי
* מה.
** אכל טבל –
הפירוש בזה הוא שכיון שא"צ ברכת המזון, אין צריך זימון. לכאו', פשוט שאם אינו מברך שאינו מזון, ואם כן כל החידוש הוא שאינו מברך. וקשה אם כן למה לא תנאו בענין ברכת הזימון. ונראה שמוכרח שבאמת יש חידוש בהא דאינו מזמן. נראה לי שני דרכים.ראשון נ' לי על פי גמ' לקמן שיש הו"א שעושה בזימון דבר שאינו שייך לברכת המזון, ואם כן, אולי אף שאין מברכים מזמנים. ויש לומר תירוץ אחר שכמו שבתפילה א"ת אלא ששה מתפללים, כמו כן בזימון אולי די במקצת מברכים.
** רש"י שאני התם –
עיין ברש"י. עוד יש לומר שא"כ, נמצא הראשון נפטר. ויש לדון בטיב הזימון, אם האו לזמן / לענות לזימון או שיהיה זימון. לדחות מש"א, אפשר לפשט שני (אף שיש דבר טוב בהתחייחס כ"א, לא יהיה זה מעכב שאין החיוב על זה). ועוד אפשר שברוב עם הדרת מלך, אלא, נראה שרש"י לא אמר כן מפני שבמשנה כ' בפירוש שארבע יכולים לחלק. ואז, מש"כ א"א. ויש לדחות שחיוב בא רק על איזה שלש. אבל, אם כן, יש לדחות כן ג"כ כאן. ותחשב.
ואין לומר שא"כ יהיו שנים מבטל חובה, וא"כ יטבלו, בלי רע. ויש לומר שעדיין יתקיים עליהם החובה. וא"ת שא"כ היו מצווים ועושים. ויש לומר שרש"י רק ר"ל שאין הזימון זימון שעושה מצוותם. וצריך ביאור.
* מה:
** במעשה דרב פפא –
יש לשאול כמה שאלות בזה:
א. צריך ביאור מה ר"ל מפסיקים, אם רצה לומר שמפסיקים ולאחרי זה ממשיכים או רצה לומר שגומרים ומברכים עצמו.
ב. לצד שני, יש לדון אם שנים צריך להפסיק ולהמשיך אחר כך, או לא צריך.
ג. לצד שני, יש לדון אם ר"פ הפסיק ושוב המשיך או ברך.
ד. יש לדון אם רק רב פפא פסק או אף חברו. לכאו', סיבת גמ' שייך רק לר"פ. אפשר שעשאו כיון שראה ר"פ. עוד יש לומר שכיון שר"פ פסק, נמצא רוב מברכים וגם הוא הצריך לפסוק. וזה, לכאו',  רק לצד שני שבא'.
(ושוב הנתי שעוד יש לשאול לצד ראשון אם ר"פ הפסיק או בירך מחמת כבוד (ויש להקשות שאם כן נימא לטעמיך, שמוכרח שלא עשה כן מפני ששנים צריכים להפסיק ולהמשיך. ויש לומר שאין הכי נמי, מגמ' זה, רוצים להוכיח שצריך לברך. עוד יש לומר שלא ידע ממש מה קרה.))
(יש להקשות לצד זה מה היה הו"א דגמ' ללמוד מזה. וצריך לומר שלא ידע ממש מה קרה.
בגמ' לקמן שואל עד כמה חוזרים. לכאו', מזה מוכרח שיש מי – אחד או שנים – שמפסיק וממשיך. ויש לדחות שבטעה ועבר קמיירי.
** רב אשי עני –
יש לדון אם היה באותו במצב דאביי או לא (ושלכן שינה). אם לא, יש לדון אם חולקים בחומר שמיעת שאר אדם או בגדר שמיעת פועלים.
** במעשה דיהודה בר מירמר-
יש לדון מה היה ההו"א שלהם. נראה לי כמה פשטים:
א. כל סיבת זימון הוא שיכבדו את הגדול בזימון. אם כן, אין סיבה זו קיימת, ואין זימון.
ב. יש לזימון סיבה אחרת, אלא שבזה יבוא לבזות ת"ח (שלא ידוע איזה לנקוט, וכ"א יתבזה בלא נקט אותו).
ג. יש לזימון סיבה אחרת, אלא שיש ג"כ רע בזימון (שאחד מברך לכולם), וסובר שרע זו נדחית רק בשני הטובים של זימון וכיבוד.
** לכבוד אדם גדול –
תימא אטו לא ידעו שניתן לאורח וכדומה.
* מו.
** סבירא ליה כי הא דאמר ר"י –
נראה שאי אפשר לומר שהיה סובר כן בתחילה, שאם כן, למה אמר לו לבצוע. גם אי אפשר שידעו לבסוף, שמי הודיע לו. אלא, נראה שרצה לומר שאחר מש"א לו ר"ז, נתחדש לו זה. ונראה שבהו"א או לא חש כלל או סבר כר"ז שהבוצע מברך וסבר שאורח יברך, ולאחר מש"א ר"ז, הסיק שהעיקר הוא ברכת אורח, ואף עם ע"י זה, נמצא שלא יברך הבוצע.
** שלש וארבע שפיר –
שהטוב והמטיב דרבנן. ויש לומר שסבר שדאו', ובברכת פועל. ויש לדחות שא"כ, איך נאמר שלש וארבע, שהרי אינו מדלג הטוב והמיטב כיון שהוא דאו'. ויש לדון בזה.
* מז.
** הכי נמי דאין –
היה אפשר להקשות יותר טוב, שכבדרו בביהכ"נ במיוחד.
** אם בא לחלוק –
יש לשאול למה מהני בזה, שא"א לאכלו עד שיאכל בוצע. ויש לומר שאף על פי כן כבוד הוא. עוד אפשר שאין צריך לשהות אחר אכילת בוצע (רצה לומר, עד שיגמור לעיסה, ויהיה יכול לחתוך). עוד יש לומר שחולק על הך דרב.
** כל המאריך –
לא יותר מדאו' כמש"כ.
** שנים ושבת –
צריך ביאור מהו ההו"א. ויש לומר שהוא הנשמה יתירה (ואם כן, נמצא שחמשה וזמנו כעשר). יש לדון, שאולי כל נשמה יתירה שווה, ונחשב אחד. עוד יש לומר ששבת קובע יותר, וכל ענין שלש ה"ה קביעות. חבירי אמר לי בדרך שחוק קצת שמיוסד על פי מדרש שקרא לשבת זוג של בני ישראל, שמשמע שהוא כאדם. וא"ת אם היא כאשה לא יכול לברך. ויש לומר שהיא כזכר, שגם ה' כבן זוג של בני ישראל, וכנראה בני ישראל נחשבים ככלה. אבל, דע שאומרים ששבת נחשבת כלה. ותחשב. גם יש לומר שגמ' אומר שלא מצרפים רק מחמת פריצות, ואין חשש בזה אם האשה היא שבת. אם הייתי מאד משחק, הייתי אומר שכן הוא קושיית גמרא, לומר שאינו גברא, ושנאמר לא פלוג.
** תשעה וארון –
לזה, מוכרח שלר"א היו שני עבדים, והיו רק שש בנ"א חוץ משלשתם. ואולי אין ארון ועבד שניהם גומרים. אבל, אם כן, אין להוקים בשני עבדים, אלא בארון.
* מח.
** רש"י ואיהו סבר –
עיין ברש"י. צריך לומר שלא גרס כמונו. עיין ב"ח. נראה לגי' שלנו שהרגיש ר"י שר"ז לא שאל מחמת טעם אחר.
** רש"י עד שיאכל בדחיית שיטת בה"ג –
יש לומר שבה"ג סובר שאין כזית כאן מה שצריך שמעון לעשות, אלא שר"ל שכיון שאנו צריך כזית בציור רגיל, מוכרח שצריך להיות במצב של מברך אחר (וק' שהיה אפשר לדחות את זה שזה בברכות חלוקים, וזה בדאו' ודרבנן).
* מח:
** ובשבת –
לא הבנתי כל כך. נראה שר"ל שיש נחמה לפניו ולאחריו.
* נ.
** ור"ע –
עיין בגמ' כתובות, שמביא עוד דרשות מאותו קרא.
** נחלקים לשנים –
נראה שלאו דווקא הוא, שאם לא כן, תשע צריך לחלק לשלש. ויש לדחות שכיון שמבטלים דין ברוב עם, צריך עכ"פ לעשות שום טוב, ואותו טוב הוא להיות יותר זימונים (ובט' וו' נתבטל באופן כמו שוה. ותו"ת.).
** לשון אחר –
יש לדון במה חולקים. ונראה שחולקים אם זה נלמד ממשנה יתירה או ממשמעות. עוד יש לדון אם משנים את הגירסא לגרוס כן במשנה או רק ר"ל שלומדים דין זה.
* נ:
** ה"נ –
נראה שרצה לומר שכיון שפרח שם זימון מיניה, אינו חייב, ופירחא זו אינו בשעת אכילה, שכיול לחזור ולצרף עמהם, אלא צריך להיות בשעה שזמנו בלי הוא, שנמצא שא"א לו לצרף עמהם.
* נא.
** אפילו גמר –
לא הבנתי מהו האפילו כאן, שהרי בציור כזה, יותר נראה לברך. וצריך ביאור.
** אם כבר אכל –
צריך ביאור למה לא יברך.
** רש"י ויאכל –
עיין ברש"י. והק' רש"א שלכאו' מפורש דלא כזה בגמ'. עוד קשה איך אפשר שטעו הדפוסק בדבר כזה, להקדים את התשובה לפני השאלה. אלא, נראה לקיים גי' רש"י, לומר שגרס רש"י שאלה זו גם על מי שאכל וברך במזון בפיו, ועל זה השיב שאין לברך. ותחשב.
** ללע"ט –
קשה, שאולי זה בשכר.
** כשהוא –
לכאו', היה אפשר לומר את זה לבאר שיטת רבנן לעיל.
* נב.
** תרי תנאי –
או ר"ח ותנא דמשנה, או שני תנאים דמשנה.
** ושותהו –
יש לדון אם מקשה משותהו, שמשמע כולו או לשון שתייה, שמשמע ולא מאצבעו.
* נב:
** ב"ש... מותר להשתמש –
נמצא עוד קולת ב"ש. אולי על זה לא מיתשל (אולי אין לומר כן כאן שעיקר הדין קולא).
** בית הלל –
אינו מבאר למה חוששים יותר לטומאת מאכל מלטומאת ידים.
** חכם הרזים –
קשה, שהרי עיקר קשיא זו על ידיעת דיעת כולם, ואף אם נאמר שהיה חכם נגד כל כך כמה, כבר כ' רש"י שעיקר הענין הוא שיודע דעתם, אף שדעתם חלוקים, וכאן חלוק דעת א"א (ויש לדון), וצריך לומר שלא אמר כן באמת, אלא היה רק דרך כבוד.
* נג.
** מפני –
נראה מש"אכ אם כולם יברכו, לא יאמרו בקול רם, ולא יצטרכו לענות אמן.
** מיעוטא –
ועוד, לכאו', מיעוטא עכו"ם.
* נה:
** מהרהור –
יש לדון אם חולק על הא דיש אות בחלום או לימי"ט אותו (ואין לשון משמע כן) או מבאר שעל כל פנים אין ה' שולח אותו אלא בעין מה שחשב.
* נו.
** הקשה לי
אחד אטו רבא לא ידע שהכל הולך אחר פתרונו. ויש לדון אם ידע מה קרה לאביי. ויש לומר שכשמעתתא סבר, שהכל אחר הלב, ועיין לעיל. וצריך ביאור אז למה הלך לו. לכאו', לזה, צריך לומר שמס' היה כצד אחר במה שחקרנו לעיל. עוד נראה לומר דחשב שחלומותיו א"א לפרש לטוב. ויש לדון.
** אשתך –
צ"ל בשניה.
* נז:
** שלש נביאים –
יש ארבע.
* נח.
** כל אלו לשמשני –
ביבמות נאמר "לא נברא אלא לשמש לזה..."
** טרח בעה"ב –
אפשר לפרש שצ"ל כן על ה', כמש"כ לעיל (וק"ק מיהו ה"בני בית" שעושה ה' להם. ויש לומר שהוא ת"ח. וק"ק א"כ מה יאמר ת"ח (רצה לומר, מה "ידחה"). ומסתמא חשב שיש יותר גדולים ממנו או לא לעצמו נאמר.
** חמור –
צריך ביאור מה השיב. ויש לומר שכך היו דיני מדינה. עוד יש לומר שזה היה נחשב ידוע משכל.
** למימרא להו –
או שקרא לגוים גמורים או שלא באמת עבר.
** רש"י ר"ה אמר –
עיין במש"כ רש"י. עוד יש לומר שמפ' שמואל.
** ממעי אמו –
י"ל שא"א שדין עליו (ועדיין ק"ק דילמא דין הוא על משפחתו).
* נט.
** והיינו גוהא –
נראה שידעו שקול עושה וואיבריטשו"נים.
** מיום שחרב –
קשה, שאולי מש"א אביי לא קרה. ואולי ראו שקרה. עוד יש לומר שקאי על ריב"ל, שלא היה אומר הלכה בלי צורך.
* ס.
** רש"י בדברי תורה –
עיין ברש"י. עוד יש לומר שמא יטעה.
** רש"י במקום שדנים –
לא הבנתי את רש"י. נראה שגמ' ר"ל שאי יש ב"ד, א"צ לחשש כ"כ (או שדילמא כולם יחייבו ולא ימותו).
** רבי אבהו –
אפשר שמביאו לחלוק, לומר שלא רק מאור ניצל, שיש סכנות אחרות.
** כדר"א –
נראה שכמותו בהא דצריך להתפלל אף במקום שבדרך כלל אין סכנה.
** שקיל –
קשה מה רעה יש בזה (ר"ל סוף סוף הוה שווה). ואין זה קושיה כ"כ (שאפשר שזהו חידוש). והעיקר על הלשון קשה.
** מעשה ניסים-
קשה, שנתפלל לנס.
** בתוך מ' ימים –
ואז צריך לומר שנהפכה ל"ד. ויש לומר שר"ל ממה שרצה ה'. עוד יש לומר שכבר התחיל ברייתו לזכר.
* ס:
** בציצית –
זה חלוק, שברכת המצוות היא.
