* ב.
** רשי מצוותן –
זמן אכילתן – יש לפרש את זה בכמה אופנים:
1. כאן מצוותן ר"ל כשרותן (ונקט מצוותן אגב שאר דינים במשנה).
2. רצה לומר שמצוותן, שהוא תלוי בכשרותו, שהרי אם פסול, אין בו מצווה, הוא כל הלילה.
3. רצה לומר שמצוותן עד עלות, וממילא אכילתו עד עלות, שהרי היתר אכילה הוא רק מפני מצוותו.
4. רצה לומר שמצוותו, שמסתבר שתלוי באותו דבר שבו תלוי כשרותו, כלה בעלות..
** אי הכי –
יש לדון אם זה ג"כ ק’ על הראשון. וי"ל שכיון שהסדר בא מקרא דק"ש, רק בק"ש קפיד. ויש לדון, ששם בברכות ק"ש קאי. עוד יש לומר שרק במשנה זו, שבא מקרא זו (“מהתם קאי"), צריך להיות על סדר זו. שו"ר בתוס’. נראה שאומר כת’ ראשון שכתבתי.
** משעת צאת הכוכבים –
קשה איך לומדים שני הדינים מכאן, כיון שמסופקים בשניהם. ויש לומר שיש רק זמן אחד שיכול להיות זמן קריאת שמע וגם זמן שיכול לאכול תרומה, שבין כל הזמנים ששייכים לכל אחד מהם, יש רק זמן אחד שהוא הצד השווה שביניהם, והוא צאת הכוכבים. עיין בתוד"ה ובא.
** בדין ק"ש
, יש מצוות לילה ומצוות יום. יש לדון אם יש שום יחס בין שני מצוות של יום אחד.
** ממעשה בראשית –
קשה ל"ל אמר שהוא כמו בכ"מ שיום אחר לילה. אולי כן ר"ל, אלא שהביא מקור לדין זה, אבל יותר נראה שר"ל שרוצה שהלשון יהיה parallel ללשון בראשית.
** דכפרה -
וא"ת מהי"ת שבכהנים הצ’ כפרה דן. ויש לומר דאל"ה היה פשוט ביותר.
** ד"ה ליתני –
עיין במש"כ. ונראה שהיה קשה לו למה מק’ על זה מהא דלאחריו, ולא על דלאחריו מזה.
** ד"ה מאימתי –
ואם ת"ח – יש לדחות שת"ח לא יתפלל במנין של רש"י, ויקרא ק"ש בזמנו. אף אם יקרא במנין של רש"י, אולי יזכור לקרוא קריאת שמע בזמן הנכון.
** ד"ה מאימתי –
כריב"ל – הניח שלסמיכות גאולה לתפלה צריך קריאת שמע שיוצא בו או קריאת שמע האמור בזמן של חובה.
** ד"ה מאימתי –
סברה לן כהני תנאי – וא"ת למה פסק כן נגד סתם משנה. אולי סומך עליהם רק בצירוף שיטת רבי יהודה.
* ב:
** רש"י בערבי שבתות –
עיין במש"כ. עוד יש לומר מפני שיש רק שתי נרות, שא"א שתדליק יותר לפני הדלקה, שא"כ, א"א להדליק, וא"א שתדליק לאח"כ, שקבלה שבת, והוא אינו מצוי בבית באותו זמן. אבל, לכאו’ מש"כ ראשון מוזר, שכל ענין אלו שיהיה אור, ואיך אפשר שמפני זה נמצא שאור נתמעט.
** רש"י שאין –
שהיום כלה – ואף שענין הגמ’ אינו סוף יום אלא תחילת לילה, נקט כן מפני שקרא מיירי בהגדרת יום.
** רש"י משהעני –
ועוד, שלכאו’ רעב הוא. עיין לקמן.
** רש"י חד שיעורא –
וא"ת כיון שצאת הוא, ונחשך לגמרי, מה לו לקדם. ויש לומר שר"ל שיש לו רק נר אחד, וזה יכלה מפני זמן אכילה אם יאחר (כן קצת נראה מרש"י, שלא כ’ שא"א להיות לו נר דלוק, אלא שא"א לו להדליק נר, והוא להדליק נר חדש). עוד יש לומר שחזר לומר שהוא בחלוק מבנ"א מפני רעבתנותו. עוד יש לומר שחזר לומר שמאוחר הוא משאר בני אדם, ולא מוקדם, כדי שיאכל סמוך למיתה, ולא יעורר ויהא רעב, אלא שרש"י לקמן לא כ’ כן וכן נ’ מרש"י לקמן לא ת’ גבי ר"מ שיעור אחד הם.)
** פשטו מבריי’ –
קשה למה לא לומדים ממשנה. אולי סברו שזה בא"צ כפרה. דחוק, כמש"כ. ש"ר בתוס’.
** עני וכן חד שיעור –
וא"ת א"כ ל"ל תני צאת. וי"ל שהוא אגב סיפא, שתני משל. (וא"ת למה בזה תני משל. יש לומר שאין דרך אחר להגיד אותו הזמן.) גי"ל שק’ גמ’ על המשנה הוא רק מפני שלא היה בו משל ידוע, ואז היה לו לומר זמן ידוע. גי"ל שרק ק’ במשנה שמקפיד על דבריו.
** עני ובני אדם לאו –
וא"ת מ"מ יש חולקים. י"ל שלא רוצים שיחלקו חכמים או שיחלק סתם בריי’ עם סתם משנה. עוי"ל שאיה"נ ואין בזה תועלת, אלא שרוצים לומר שמש"א לעיל לא מוכרח.
** מקדמי –
וא"ת מה שייך תחילת יום. ויש לומר שרק אגב הוא. עוד יש לומר שתחילת וסוף יום תלויים אהדדי, שאם זה הנץ, זה שקיעה, ואם זה עלות, זה צאה"כ.
** במה שגמ’
דן ב"לילה" נראה שאף שכ’ "בשכבך,” דורשים שר"ל זמן מצווה שיש בו שכיבה, שהוא הלילה. (אבל, אם כן קשה מהי"ת שאין ר"ג דורש "בשכבך" כר"א, אלא שזמן מצווה שכולל אותו הזמן הוא כל הלילה. אפשר לומר שאשמורה גם נחשבת זמן מצווה. זה מבאר למה ר"א תלה אותו באשמורה, שתלוי במזן הלכתי, ואילו לא היו משמרות, או אילו היה להם זמן שונה, היה הדין שונה. ותחשב.
** בעוד יום –
יל"ד אם ר"ל שלכן, א"א להיות נקרא בשכבך או שאז לא ייקרא "ק"ש של לילה.”
** רשי בין –
עיין במש"כ. קצת מענין, שנמצא לר"מ שיום הוא.
** זכר –
יש לדון למה אינו ראיה:
א. שצ’ שכיבה, ולא לילה.
דלמא יום ולילה כאן אינם דווקא.
דילמא עבדו ג"כ בלילה, ורק הוסיפו משמר.
** רוב בנ"א עניים –
עיין ברש"י. ויש לפ’ ג"כ כפשוטו, שרוב בנ"א עניים, אלא שא"כ קשה אמאי נקט ע"ש, ועוד שעיקר התי’ חסר מן הספר.
** ד"ה משעה –
עיין במש"כ. נראה שקו’ הוא שאם בכ"ז מוכרח עני לדחות עבודתו, ימצא שאין זה זמן סעודתו. ויש לדחות שבגוי או שבמה רוצה עני, דן. ועל הראשון, עדיין יש להק’ מבן אדם בע"ש, שזה בוודאי אינו בגוי. ותחשב.
** ד"ה ואי ס"ד -
עיין במש"כ. עוד יש לומר שא"א להיות בעב"ש, שזה אחור, וא"א להיות קודם.
** ד"ה א"ל –
במש"כ שר"י לא דרש, נ"ל כמש"כ ד"ה במה.
* ג.
** מאי קסבר –
וא"ת למה צריך להביא כל זה, שבוודאי יהא בו זמן. ויש לומר שר"ל שהוא זמן שקל לומר, ולא זמן שקשה לבאר.
** קשיא דר"מ –
במש"כ שהוא שיעור מאוחר, ולא מוקדם, נ"ל שהוא מפני שיש הו"א להשוותו לשיעור עני, שהוא אחרי צאה"כ. ע’ בתוס’.
** ד"ה קשיא דר"א –
נראה שרש"י לא הוצרך לומר כן, שסבר שיודעים מהו זמן התחלת שבת, והרי אינו שווה לצאת, אלא ביה"ש. ויש לדון, שאולי ר"ל בתחלתו ודאית.
** קמ"ל בארעא –
יש לדון מהו ההוכחה:
אולי הוא ממה שיכולים לשער בזה.
אולי הוא ממה שלא נקט זמן. כן נראה מרש"י.
** רשי מאי קסבר -
יש לדון בקושיא זו:
א. למה לא אמר רק הזמן, שהוא יותר פשוט, ושכן אומרים בני אדם.
ב. למה לא אומר רק הזמן, שהוא יותר ניכר. כ"נ מרש"י.
** יש להעיר
שבת’ הגמ’ יש שני ענינים: א. היה ניכר כמו זמן. ב. יותר טוב מזמן, שיש בו חידוש.
** בבית אפל -
וא"ת למה לא אמר כן ג"כ בצאת הכוכבים. וי"ל שלא רצה לנקוט תחילת זמן, שאינו מסתבר שבנ"א ידברו זא"ז אז (אלא שלעיל נקט ק’ אחר, וע’ במש"כ לקמן ק"ה אב"א.) עוד יש לומר שמי שיבוא בבית אפל לא ישמע חמור נוער, שהוא בעיר. עוד יש לומר שסובר כאב"א דלעיל (אליבא דר"ש) או כתנא החולק על מתניתין בשיטת ר"א, ולכן ר"א לשיטתו, דר"א סבר שק"ש מלפני צאה"כ.
** אב"א –
יש לדון למה לא סבר כתי’ ראשון:
א. כמש"כ לעיל, שאינו מסתבר שיהיו בנ"א מדברים זא"ז בתחילה.
ב. יותר בהיר ומדקדק, שכל זמן שווה.
** שמנהמת –
קשה למה נקט לשון הווה. ודע שלמס’ גמ’ שהוא בכל זמן, אינו קשה. יש לדון.
** מנהמת –
יש לדון אם היה מנהם ושוב אמר כן או שאמר כן בקול של נהימה.
** מפני שלשה –
נמצא שי"ל שלכך שמרו אליהו (ולומר ששימור ר"ל שימור ממש).
** רשי לאו ר"א –
קשה למה צריך להביא כל זה. נראה שבלי זה, הו"א שכוע"מ שצריך זמן שבנ"א שכובים, ולכן, צריך רק משעת צאה"כ, אלא שר"א סבר שג"כ צריך שהולכים לשכוב. אבל, כיון שראינו שמתחיל מביה"ש, מוכרח שרק ה"ל זמן שבנ"א הלכים לשכב.
** רשי שואג –
עיין במש"כ רש"י. ופשטותו רק שזה סימן למה ששואג.
** סימן לדבר -
יש לדון אם ר"ל סימן למשמרות או לשאגת ה’ (ואולי תלוי באב"א), כמש"כ ד"ה סימן.
** רשי אשרי –
עוד יש לפרש "אשרי המלך שמקלסים כך בבית הכנסת, ואיזה טוב היה בבית המקדש.
** אמר רבי יוסי –
נקט מעשה זה מפני הבת קול, ומפני בשלש פעמים.
** זמנים –
יש לדון איזה שלש זמנים: א. זמן תפילה. ב. שליש יום. ות’.
* ז:
** ד"ה במקומן –
ע’ במש"כ. רצה לאפוקי מלומר שת’ גמ’ הוא ששאני חורבות שהוא מקומן, שאל"כ, בטל שאר תי’ גמ’.
** כרבי יהושע –
ורבי, שלא מסכים לכך:
א. לא סובר כר"י.
ב. סובר שהיה לו דוד למנות כוותיקין.
ג. סבר שדוד היה מונה אשמורות ממשיות, ואין אשמורות ביום.
ד. לא מונה אשמורה שבא באמצעו. אז, בין הכל, אין שני אשמורות.
** מ"ט דר"נ –
קשה למה א"א קרא בשאגה כלל.
** רשי אלא –
חייבים – פשטות טעם לזה הוא שמקנה אותם שהם, ולא הוא, זוכה למצות ודברי תורה. לשון רש"י קצת מוזר.
** ד"ה מתנמנם –
במש"כ עוסק בתורה, ק"ק מהי"ת.
** מיד… ועוסק בתורה –
עיין לעיל שאי"ז לכ"ע.
* ד.
** לאור –
זה נגד ר"א לעיל (ולכן חלק כאן).
** רב אשי –
צריך ביאור למה יאמר משה כזה – ביום שלאחר זה – באותו זמן כמו הזמן שיהיה בלילה הזה. ותו"ת.
** לא חסיד אני –
נקט כן מפני חסדות דוד, מה שקם בחצות, ודמיון לשאר מלכים.
** שמא יגרום –
וא"ת אם כן נמצא שאינו חסיד. ויש לומר שחסיד הוא רק שעושה טוב. עדו יש לומר שחביד רק שמה שעושה טוב, עושה טוב מאד. אינו נראה כן. יותר נראה לומר שחשש שיפסד בעבירה קטנה.
** רש"י מפיבושת – מ - בייש פ י
ועדו יש לומר שסרסו ודרשו
נ
דוד. ותחשב.
** ולא בשתי –
וא"ת הרי אמר שהיה מבייש פני דוד. ויש לומר שהשני סבר כצד ראשון בחסידות של דוד. עוד יש לומר ש"לא בושתי" אינו שלא הרגיש בושה, אלא שלא נמנע מפני הבושה. עוי"ל שמבייש לא רצה לומר שהיה מבייש ממש, אלא שהיה עושה לו מה שבדרך כלל יבייש את האדם.
* ד:
** אונס שינה –
יש לדון אם קאי על תקנת תפילה או תקנת ק"ש. עיל"ד אם ר"ל שמצוי שיטעה מחמת אונס שינוי או שאם יטעה, מצוי שיבטל ק"ש דאו’ (על אותו צד).
** קמ"ל דחובה –
יש לדון אם ר"ל שאמרו בלשון זה להודיע שחובה היא או שיותר חמור הוא כיון שיש צד לומר שרשות הוא. נפק"מ יהיה אם יותר חמור משאר דינים דרבנן.
** אף שכיבה נמי –
נראה שיש נפק"מ בין השני צדדים לריב"ל אם צ"ל לאחר שמ"ע דווקא. ויש לדון.
** רגזו –
וא"ת למה צריך להביא רישא של קרא. ויש לומר שכן הוא דרך הגמ’. יש לדון אם זה נכון. עוד יש לומר שהוא מפני שדורש את כולו כאחד לקמן, ואז כבר מביא את כולו. אבל, יש לדון, שאולי רק ממשיך לדרוש את כולו לקמן כיון שכבר הביא את כולו.
* ה.
** רש"י ואם ת"ח –
במש"כ לחזור, צריך ביאור למה כ’ כן.
** כגון –
קצת קשה למה צריך ציור.
** אין צריך –
עי"ל ששא"צ כיון שמקיים בקראי, מסתמא, כדרשת ר"ל.
** זו מצווה –
ק"ק למה קידם משנה בקרא. אין זה קושיה על גמ’, שמוכרח ש"מצווה" אינו נ"ך, שאין בו הרבה מצוות (ומה שיש הם, בדר"כ, רק מדברי קבלה, שלא מגלה הרבה מצוות מדאו’).
** אדם מוכר חפץ –
לכאו’, הו"ל לנקוט ציור דנתן, דומא דציור של הקב"ה. שוב הבנתי שגמ’ בא מלשון הפסוק של "לקח.” אז, ק"ק על הקרא. אפשר לומר שע"י נתינת תורה, זכה בבנ"י כעבדים, ואז נחשב כמכירה. יש לדון בזה, שלכאו’ זכה בהם ביציאת מצרים. עדיין יש לומר ששיפר את העבדים שלו, וגם הוא נהנה, ואז זה נחשב מכירה.
אפשר שר"ל שאדם עצב אף שמכר, וקבל דבר בחילוף שלו. ותחשב.
** יתלה בביטול תורה –
מקשה העולם שביטול תורה בכלל מעשיו. יש לומר שמעשים רצה לומר בקום ועשה. קשה, שנמצא שאם לא מוצא קום ועשה, תולה בביטול תורה, ולא בשב ואל תעשה אחר. אולי זה מפני שאין עונשים על שב ואל תעשה. צ"ל שזה אף שאין עונשים מן השמים. ותחשב.עוד יש לומר שר"ל שיבדוק שוב בתורה, שמצוי שלא הכיר בו. עוד יש לומר שר"ל שיבדק בת"ת של עכשיו, שמצוי שבא לאבדו מת"ת ולנסותו. עוד יש לומר שר"ל שיתלה בביטול תורה, אף שאינו נראה לו שראוי לבוא עליו יסורים מזה. (לשון גמ’ ש"תלה" ולא "יפשפש" משמע שא"צ לבדוק בתורה עוד, אלא שיתלה בו. ותחשב.) גם יש לומר שאם לא מצא מה שראוי לו ליענש עליו, צ"ל שאינו עונש, אלא כדי להורות לו לתקן את מעשיו. מפני זה, אולי, מסתבר שהוא ת"ת.
** אם נצחו –
צריך לבאר למה לא יזכור יום מיתה תחילה. לכאו’, אין זה יותר טוב מזה, אלא שכ"א פועל בזמן שאחרים פועלים (ולהיפך, אולי תורה הוא הכי טוב, ולכן קדמו). ותחשב.
** אלו ואלו –
צריך ביאור למה לא דורש "ברוך….”
** והיינו –
זה ג"כ מקור מתורה ללמד.
* ה:
** סמוך למטה –
יש לדון אם רצה לומר סמוך בזמן או במקום. לצד שני, מסתבר שצ"ל גם קרוב בזמן.
** מי חשוד –
קשה, שאולי של אהבה היו. עיין בתוס’.
* ו:
** לא אמרן… למיפק –
ק"ק שהרי זה פשוט. ואולי הו"א שאין כבוד לביה"כ לחץ לפניו. עוי"ל שעיקרו הוא הסיפק (שמצווה לרוץ לביה"כ).
** אחרי ה’ –
צריך ביאור איך זה מלמד את דינו. נראה שמלמד שמצוה הוא, וכיון שמצינו כן, מסתמא מותר בשבת, כיון ש"חפציך….”
** כי זה כל האדם –
יש לדון מהו הדרשה:
א. זה כל האדם רצה לומר שלזה נברא אדם. קשה, שמי יימר שהעולם נברא לו, ולא רק אדם.
ב. כעין ראשון, אלא שי"ל שכיון שיודעים שעולם נעשה לאדם, ממילא כיון שאדם נעשה לו, עולם נעשה לו.
ג. כעין שני, אלא שקרא ר"ל שזה כל האדם שלהם עושה עולם. ותחשב.
* ז.
** ומי איכא –
לא רצה לומר שזה היה שעת זעמו, שהרי א"א לו לה’ לומר "חכה לי" ברגע, אלא נראה שר"ל שכמו שיש זעם שם, אף אפשר שיש כאן.
* ז:
** אף דניאל –
רצה לומר, אף יכולים לראות גדולתו של אברהם או אף  היה גדול ע"י שדניאל לא נענה…. גם יש לומר שאף שדניאל היה יכול להיות נענה מגדולתו, נענה משל אברהם, מסתמא מפני ששל אברהם יותר גדול. אז, רואים גדלות אברהם.
** ראובן –
יש לדון אם מרמז ל"ראו בן" או "ראו בין.”
** פני ילכו –
קשה, ששם היה כעס של ה’.
** רש"י רות –
קשה ל"ל אמר כן גבי ראובן. אולי זה אפשר להיות רק אגב לאה, ואגב שמות שאמרה (ר"ל ולא בכל שמות).
** דשמא גרים –
וא"ת למה כ’ כן רק כאן, ולא גבי ראובן. ויש לומר ששהה עד לבסוף. עוי"ל שהיה לאה דן בראובן, ופשוט שגורם בו עוד יש לומר ששם היה סימן, שהכיר לאה שהיה ראוי לזה, וזה א"א ברות, שמה שיעשה דוד לא שייך לזה.
* ח.
** כי ברבים –
קשה, שאולי זה רק בצבור, ולא בזמן ציבור.
** גורם גלות –
יש לומר מפני ששכן רע הוא, ואז צריך לשנות שכינותיו.
** ירא שמים –
שקה להבין שbill gates יותר טוב מרב חיים קניבסקי. אולי רצה לומר שטובת זה יותר מטובת זה. אבל, עם יראת שמים בא הרבה מצוות, ואלו יותר טובים. ותחשב.
** ד"ה לעת מצא מיתה –
עיין במש"כ. עי"ל שית’ לעת מצא, שלא יבוא עד לאחר זמן. התניא נמי הכי לא משמע כן.
** שני פתחים –
יש לדון אם רצה לומר לבד מפתח ממש או לא. עיין לקמן.
** שני פתחים –
יש לדון אם רצה לומר רוחב פסח או אורך פתח או פתחתו.
** הא דמר זוטרא –
וא"ת איך אפשר שזה יותר חשוב מת"ת. יש לומר שלזה תפלה מהני יותר. עוי"ל שהא דמ"ז יגרום ג"כ לת"ת טוב (ואולי אף למיתה טובה).
** דבי כנשתא –
וא"ת הלא אומר רע על ביה"כ וטוב על שערים מצוינים בהלכה. ויש לומר שהיו לומדים שם. עוד יש לומר שר"ל לא אמר מילי מעליתא על בי כנשתא, אלא על שערים המצוינים בהלכה.
** שערים המצוינים –
קשה איך רואים את זה בקרא, שרואים רק מצויינים, והיה יכול להיות בברכת שמואל. צריך לומר שיודע כן, בי"כ ובי"כ מסברה, וכיון שכן ידוע שזהו כוונת הקרא.
** יגיע כפיך –
עיין במש"כ. ושוב נ"ל מק’ דלעיל ולת’ למה יש שכבר לת"ח יותר מזה שדן במי שהיה נולד להיות ירא שמים נגד מי שעמל וטרח להיות ירא שמים. ותחשב.
** רש"י לעת בית הכסא –
עוד יש לומר שלא יהיה לו קושי כש"הולך לבית הכסא.” עיין במש"כ על הא דמ"ז טוב יותר וקצת מזה הניח נגד רש"י.
** לא תגנו בלי ק"ש –
וא"ת הרי זה דאו’. וי"ל שיכול לקום ולקרוא קודם זמנו. וא"ת הרי יש ק"ש שעל המטה. וי"ל שלזה מכוון, שאינו חיוב ממש או אינו חיוב פשוט. עוד יש לומר שת"ח היו. עוד יש לומר שאמר להקפיד מאד.
** דבית הכסא –
מדלא מביא קרא, נראה שדורש מצא מסברתו. אולי הוא שהענין הוא שיהא ביה"כ מצוי לו. אולי לכן מסיק גמ’ שכמותו מסתבר.
* ח:
** אסור לישב –
משמע שאיסור ממש הוא, ולעיל משמע שהוא ענין טוב.
* ט.
** רש"י אשתכור –
עיין במש"כ. לכאו’, היה אפשר לומר שכיון שהיו שכורים, לא היה אפשר להם לקרוא קריאת שמע. נראה שאינו מסתבר שהיו כ"כ שכורים לכ"כ זמן.
** רבנן –
צריך ביאור מה חשבו על צד זה, שכבר כ’ גמ’ לעיל שזה א"א.
** השכיבנו –
עיין ברש"י. עוד יש לומר מספק ברכה לקולא. אם כן, יש לומר שעל זה קאי ראיית גמ’ של "שעת הדחק" שכיון שבדרך כלל אין סומכים על זה, אין מברכים.
** רש"י עד מתי –
שאם לא מאי בינייהו – זה אומר שמדתנא שניהם במשנה אחת, ולא כשיטה אחת, מוכרח שיש מחלקת. עוד יש לומר שממה שלא הוקים בקר כר"י מוכרח שחולקים.
* ט:
** דאי לא תימא –
הגמ’ מוכיח את הראשון משני, וחוזר ומוכיח את השני מראשון.
** מיבעי לן למיהב –
יש לדון מהו תי’ זה:
א. אף שחסרת, ג"כ זכית, ונמצא שאתה שווה.
ב. אף שחסרת, זה רק מחמת שטעית בדבר, אבל בדר"כ נשמר מדבר רע.
** לא פסיק חוכא –
פשטותו הוא ששמח כ"כ במצוות. עוד יש לומר על פי מש"כ לעיל בצד שני בד"ה מיבעי, ואומר שלא טעה כלל, וממילא לא נעשה לו אלא טוב. ותחשב.
** לבסוף –
היה אפשר לומר שאמרו לבסוף שלא יהיה הפסק בין גאולה לתפלה (או שאם אינו צ"ל שם, אינו כתפילה ארוכה, שאינה כ"תחילת תפלה" ודחוק או שאכתי יותר טוב שלא להפסיק. ותחשב.)
** לאחר –
יש לדון אם זה סימן או סיבה.
* י.
** כי היכי דלימותו –
יש דלון אם יש בזה בעיה של עונש ע"י צדיק (שאולי אין זה כל כך דייראקט).
* י:
** מאי קור –
פשטות קור הוא כותל. יש לדון אם ר"ל שמסתבר שלא היה קור ממש, שא"כ למה יאמרו קרא, אלא צ"ל שקור ר"ל דבר אחר, ודן מהו, או שדן מה רצה לרמז בזה.
** ד"ה גדול –
צריך ביאור מהו ק’, שאולי איה"נ. עוד קשה שלכאו’, פשוט שהת’ הוא שר"ל מתורה של מי שתורה אומנתו. עוצ"ב מהו תירוצו, איך תורה בזמן זה גרוע מבזמן אחר. ותחשב.
* יא:
** ד"ה
ורבנן – הניח שאף בערבית חולקים.
* יב.
** מיזן זייני –
וא"ת אם כן פשוט. אולי זהו גופא הקמ"ל. ק"ק למה לא רק אמר שיוצא בברכת מזונות. עוד יש לומר שהקמ"ל הוא שהברכה חל אף שהברכה שכיוון חל על ענין אחר (רצה לומר שמו של מה שזן, וברכתו האמתי הוא שמו של הפרי) ודלא כשהכל. ותחשב.
* יב:
** חמשה דברים –
או שיש כמה דברים בפרשה קטנה או שר"ל שיש כמה ענינים השייכים לעיקר שמע.
* יג.
** ד"ה שכבר –
עיין במש"כ בחילוק בין ברכת התורה לאהבת עולם. יש לדון אם אה"ע יותר קלוש בענין זה, ולכן חל רק על ד"ת דלאלתר או שכיון שעיקרו אינו לד"ת, צריך גילוי שבא לברכת התורה, ולכן צריך ללמוד לאלתר.
** פרק שני: בפרקים –
צריך ביאור איך זה שייך לרישא.
