* ג.
** ואין עבירה אלא לשון הכרזה -
לא היה צריך להביא קרא זה; היה אפשר להביא ראיה ממה שעבירה נקרא עבירה. יש לומר שאם היה רק מילה שנקרא, ולא שכתוב בתורה, אין לדרוש אותו. גם יש לומר שאין יודעים לקרוא לעבירה באותו שם אלא מכאן. גם יש לומר שכאן הרי נכרז על בעל העבירה, ואז מביא קרא זה. גם אפשר שעבירה לא ר"ל שנכרז, אלא שמכריז. אז, צריך קרא זה, שאומר שהוא מכריז עליה (והיא בעלת עבירה).[fn:1]
** והא כי כתיבא -
לכאורה, היה אפשר להעיר כן על המשנה. יש לדון, שאולי נכתב שלא כסדר, כשמקדים קנאה לסתירה. ותחשב.
** דתניא -
דקאמר- לשונו משמע שקושיית גמרא הוא שצריך תנא דבי רבי ישמעאל לסבור כרבי ישמעאל. אם כן, מקשה מרבי ישמעאל לחודיה. יש להעיר על זה:
1. מעניין שמניחים שצריך תנא דבי ר"י לסבור כר"י, ש"תדבר"י" רק אומר שבבית מדרשו, שנו ברייתא. לא צריך שהיה ממנו.
2. לא משמע גמרא שרק מקשה מרבי ישמעאל, שמקשה גם ממה שרבי עקיבה אומר שהוא מצווה. אפשר שלא רוצה שיהיו חולקים בשני דברים, ואז יכול להוכיח מרבי עקיבה. ותו"ת.
** ורבי ישמעאל -
ואם תאמר מה חידוש יש באיסורו; הרי כל ספק אסור. יש לומר שכאן יש חזקת היתר. ותו"ת.
* ג:
** עדות הראשונה -
היה אפשר לומר שהוא קינוי. ותו"ת.
** אין מתקיימת -
ואם תאמר הרי גמרא לומד את זה מ"בה,” והיה לו לרש"י לפרש כך. נראה שרש"י עדיין קאי בהוה אמינא של גמרא, שגמרא דן בדין של עדי טומאה. עד שלא יודעים דין של עדות טומאה, לא יכולים ללמוד מ"בה,” ש"בה" ממעט מדין ע"א של עדות טומאה. אז, היה צריך המקור להיות "דבר" מגזירה שווה. ותו"ת.[fn:2]
* ד.
** זכר לדבר -
לכאורה, נמצא שיש סיבה לומר שיאמרו חכמים דברים כעין זה על קרא- ר"ל שיאמרו רבנן קראי אף שאינם מקורות, ואף לא מקורות לרבנן לגזור דינים. זה כעין מש"א רמב"ם על אסמכתא. אפשר ששאני הכא שמפרש גמרא שאינו ראיה.[fn:3] ואפשר שאין צריך לזה, ואף ריטב"א יודה שלפעמים כן הוא.
** כדי מזיגת הכוס -
כמובן, צריך ביאור למה כל אחד ינקוט סימנים חלוקים. יש לומר שיש מי שאינו יכול לשער בזה, ויש מי שאינו יכול לשער בזה. אז, יותר קל לשער בין שניהם. עדיין יש לדון למה ינקטו מה שנשמע כל כך כשיטת חבריהם.
* ד:
** סוד ה’ -
יש לדון מה זה אומר. אם היה שום רוח הקודש, אז צריך ביאור איך היו יכולים לחלוק עליו. אולי סברו שחשב שהיה רוח הקודש, אבל באמת, ברא אותו מלבו. זה מוזר. ותו"ת.
אולי סוד ה’ ליראיו רק ר"ל שהיה יכול לצייר כן בדעתו. דחוק. גם לא משמע כן לקמן כשאומר כן גבי ביאור חולי רגלים. ותו"ת.
** לדינה -
ואם תאמר הרי משמע שאין שאר עבירות כן. אולי אין הכי נמי, ותורה מציל מעונש. יותר נראה לומר שמפני שהוא תלמיד חכם, ה’ מעניש אותם בעולם הזה. ותו"ת.
** ולא תביא -
אם כן, אם אדם לא נכנס לביתו, אין איסור. יש לומר שגוף של אדם נחשב ביתו לענין זה. ותו"ת.
** שמא -
יש להעיר שכל זה קשה להבין, שלא קל להבין למה רק ידים טמאים, שאם הם טמאים, הכל טמא (אלא אם כן נאמר שחוששים שיש קצת של דבר טמא שנדבק בהם, ולא טמא די לטמאות אותו, אבל מטמא דבר אחר), ועוד שאם הוא טמא, לא יהני נטילה, ועוד שאם המים נעשים טמאים, איך יטהרו, ועוד שמים טמאים לא יטהרו על ידי נטיילת מים שניים, אלא יטמא אותם מים טהורים. ויש לדון. ותחשב על כל זה.
* ה.
** בסתר -
קשה איך זה נשמע מן הקרא. אולי משמע שהוא כל מתן מיד ליד, ואף כעין זה, שהוא הכי טוב. דחוק. אולי זהו המתנה המיוחדת שיש הוה אמינא שיציל.
** השמר -
אם כן, לכאורה, רק עובר בגרמא, שעושה שישכח. מעשה של שכחה הוא האיסור, ולא עשה את זה בידיים, שלא בחר לעשות אותו, אלא גרמו. ויש לדון. גם יש לומר שהאיסור הוא זה, שאי לאו הכי, קשה מהו האיסור של שכחת ה’, שאי אפשר לשכחו בידיים, ואז צריך לומר שקאי על שכחה בגרמא. ותו"ת.
** רוח קימעא -
ואם תאמר כיון שעוכר אותו, מה עושה שהוא קלה. ויש לומר שלרוב בני אדם הוא קלה. גם יש לומר שהוא קל כיון שרוב פורעניות הוא הרבה יותר גדול ממנו. גם יש לומר שהוא קל כיון שעיקר תוצאה רעה שלו הוא קל. ותו"ת.
** לא ממנה -
לא יחפוץ- ק"ק למה אמר כן על חפץ לו, ולא על היותו לו (שלא יתגאה). ותו"ת.
* ה:
** דבור -
היה אפשר לציין לגמרא כתובות (במחלקות בין ר"י ור"ג) שלחד אמורא אומר דיבור כשר"ל ביאה. צריך לומר שלא רוצה גמרא לומר כן, שחושב שהוא יותר דחוק. ותו"ת.
* ו:
** דכח קדוש -
ק"ק שבין כך ובין כך, בין אם היתה בדוקה או לא, היה טעות, שאילו ידעה שלא היתה צריכה בדיקה, לא היתה מקדש אותה. ותחשב.
** ולאו מטעמיה -
ואם תאמר הרי ר"ש עצמו לא הסכים למקורו, שאמר שאין להביא ממנו ראיה. וקל לתרץ שלא הביא ממנו ראיה, אלא מקור, וידע לדרוש ממנו מאותו המשנה. ותו"ת.
** ורבי שמעון -
היה אפשר להקשות כן על רב ששת גם כן, שדורש, אבל לא מקרא זה. יש לדון, שלרב ששת, קל לומר שקרא ראשון רק יותר משמע לו. ויש לדון, שאם אותו קרא, שאמר גמרא שאינו כל כך ראיה, משמע לו יותר, בווודאי לא סובר כמו שמקשה גמרא ל"ל ללמוד מקרא זה. ותו"ת.
* ז.
** שאינם כדי לשומעים -
יש לציין לגמרא מגילה שאומר שמעשה של הודאת יהודה (שרש"י מזכיר בכלל זה) נקרא ומתורגם, שהוא שבחו של יהודה. צריך ביאור.[fn:4]
** אם היה לבה -
יש לדון איך יודע. אולי שואלים בני אדם. יש לדון מי נאמן[fn:5]. אולי כהן רואה (ואף שאינו טוב לכהן לראות, אם לא רואה, יגלה בפני כל). ותחשב.
* ז:
** במקום שאין כותבים -
צריך ביאור למה יכולים שלא לכתוב כתובה, שאז צריכים שובר. ותו"ת.
** מנא -
אחד משני בתי דינים- צריך ביאור מהיכי תיתי שצריך להיות שום בית דין כלל. ותו"ת.
* ח.
** שמא תצא -
היה אפשר לומר כן גם כן גבי הורגת, שהרי מחפשים לזכות, אבל אינו כל כך מצוי. ותו"ת.
* ח:
** שליח -
לא הבנתי מה שייך מה שהוא שליח לזה. אז, היה לו לומר, “אדם….” וצריך ביאור.
** ארבע מיתות -
צריך ביאור מה זה שייך, שמשנה דן במדה כגנד מדה, ועכשיו דן בדין אחר. צריך לומר שהם שווים במה שהם עונשים שהם מיוחדים. ותחשב.
** חיה -
עיין במה שפירש"י. נראה שזה דומה לאבן גדול שנותנים עליו. זה מניח שמה שממית אותו הוא מה שהחיה נשאר עליו. יש לדון אם זה אמת.
* ט.
** לכמדה -
קצת צריך ביאור מה היה ההוה אמינא, שאין שני הקראי שייכים כלל זה לזה. ותו"ת.
** אשיא -
מעניין שמביא ראיה מתלמיד של רבי עקיבא שאומר דבר שנדחה מרבי עקיבא רבו מיד אחר כך.
** לא הכיתי לאומה -
קשה, שהיה מצריים. אולי גם מתנה הקושיה עליו, ואז אומר שצריך לומר מלך. אגב, נראה שמה שטעה הוא על שם מה שאומר גמרא שנקרא אשה בית, כיון שהיא עיקר בית, ואז אף מלך נקרא אומה, אולי. ותו"ת.
* ט:
** גחזי -
קשה, שהרי נטל ממון של נעמן.
** שעה -
אם נאמר שמדת פורענות הוא אחד מחמש מאות של מדת הטובה (“אלפים דור,” כמו שאומר רש"י במכות ובכ"מ), צריך לומר שבא לה חמש מאות פעמים של מה שהיתה עושה. אם כן, צריך לומר ששהתה לו כמו עשרים דקים.
ואין זה מוכרח, שיש לומר ששהתה מאה דקים, והיתה מקבלת יותר שכר, אלא שלא היה צורך. ותו"ת.[fn:6]
** לא על משה -
ק"ק, אז, שנחשב שכרו, כיון שאף בלי זה, היה מקבל אותו. ותו"ת.
** שם שמים לבטלה -
יש לציין לכעין זה בתחילת מגילה (ג.) גבי מלאך שבא ליהושע.
** בתר ישרותיה -
נראה שר"ל כמו שאומר רבי עקיבא בנדרים וחגיגה שאף מי שנמצא  נדרה מופרים צריכה כפרה. ותו"ת.
* י.
** לשון עבירה -
יש לדון ל"ל היה ממית א"ע, שהיה, לכאורה, יהרג ואל יעבור. אולי אינו יהרג ואל יעבור לבעול גוי. ותו"ת.[fn:7] אולי כיון שהיה סומא, לא ידע, ולא הכיר מה היו עושים לו (ועל כל פנים, היה מסופק. אולי מספק לא היה יכול להמית א"ע, שאין ספק מוציא מידי וודאי, שהרי בווודאי יש רע במיתתו).
** אשתו מזנת -
יש לציין לגמרא לעיל שאומר שזנות גורם רעה בבית, ואומר שהוא רק בזנות שלה. נמצא שהוא אף בזנות שלו, כיון שגורם זנות שלה. אין זה קשה, שהוא רק בזנות שלה, שרק זה הגורם.
גם יש לומר שהוא רק כשמזנה מעצמה, ולא נגרמת מחמת זנותו. ותו"ת.
** היכי דמי -
יש להעיר שקושיית גמרא אינו רק איך ידע, אלא איך ידע לשאול לו. ויש לדון אם זה קשה, שאולי יותר קל לומר שהיה לו ספק שמא שמע מרבו. ותו"ת.
** במקום אחר הקשינו
שאין מעלה בפשט זה על פשט שהוא חש בה, שבין כך ובין כך צריכים להניח שאחד חש בו. ויש לדון, שצד זה יותר קל, שיכולים להניח כן על שום רב שלו או רב של אותו רב, ונמצא שדנים בו ביותר בני אדם, ויש יותר צד שאחד מכולם היה לו מצד שהיה לאחד מיוחד (רב נחמן). ותו"ת.
** עשה אנגריא -
צריך לומר שזה יותר רע מעשיית אנגריא עם חתנים, אף שתורה אומר את של חתנים בפירוש בדין מלחמה. גם יש לומר שאינו יותר רע, אלא יש יותר ת"ח, ובזה עבר יותר.
* י:
** מישאל אלצפן -
אם כן, אותם שני נביאי שקר (ששרף אותם המלך כדי לראות אם היו צדיקים כשלש אלו) היו להם לומר ששאני מישאל… שהיו להם סיבה זה. אולי לא ידעו.[fn:8]
** נקרא כולו -
ק"ק, שהרי נקרא כן קודם שעשה כן, ואין יראת ה’ ביד ה’ לומר שהיה כבר עומד לכך. ותו"ת.
** כיון שהודה -
עיין לקמן, שגמרא אומר שלא קאי על זה, אלא על מעשה של נחשון בן עמינדב בים סוף.
* יא.
** עבדי -
ק"ק, שאין שליח לדבר עבירה. אולי נענש על מה שגרם כן, שיודעים שגרמת נזיקים אסור. ותו"ת.
* יב.
** כי היכי דלשמעיה -
ק"ק, שהיה למשה קול של נער. אם כן, לא יבינו. אולי, אף אם ישמעו קול נער, יבדו לו. גם יש לומר שגזרו מצריים לפני זמן די שלא היה להיות נער חי, והיו ממיתים אף אותו. גם יש לומר שגופא מה שהיה בוכה בבכיית קטן מגלה שאינו נער.
* יג.
** קבורתם מיהא -
ק"ק מהיכי תיתי שהיה עשו נקבר באותו יום.
** תלמידו -
אם כן, אף אלישע תלמידו, והיה אפשר לומר מזה עצמו. ואולי אין הכי נמי, אלא מוסיף עד שהוא כל שכן יותר. אם כן, היה אפשר להוסיף עוד, שמה אלישע, שהיה תלמיד של תלמיד של תלמיד…. ותחשב.
* יג:
** כתוב בזה -
משמע שהשבטים (או, על כל פנים, יוסף) קיים את כל התורה כולה. אין זה כל כך פשוט (יש תוס’ שדן בזה גבי "טבוח טבח").
** כתוב בזה -
לאו דווקא, שלא כתב כלום בארון. אולי היו לוחות שם כבר[fn:9], ונכלל בהם כל המצוות. גם יש לומר שהיה ספר תורה כתוב שם. לכאורה, לא נכ’ כל התורה עד סוף ימי משה. אולי אין הכי נמי, ולא קיים כל התורה (על"ע), ורק שקיים כל כמה שכבר נתון, ותורה נכ’ עד אז, במצוות שהיו נצטווים בו. ותו"ת.
* יד.
** כדי שיתקיימו -
צריך לומר שמה שהוא נאנס עושה שאינו מקיימו כל כך, אף שהקב"ה מצרף…. אולי זהו מה שאמר ה’. (ואגב, קצת צריך ביאור ענין של "שכר,” שלכאורה, משה רצה לקיים מצוות, ולא שכר. ויש לדון אם מה שאמר ה’ היה אף לטוב או רק לשכר.)
* יד:
** לית ליה -
יש לדון אם זה דיחוי או לא. ותו"ת.
** לקדשה -
קצת קשה ל"ל אומרים שאף זה משמע כן. צריך ביאור מהו המשמעות ממה שאמר מתחילה. וצריך לחשוב. ותו"ת.
** פני -
קצת צריך ביאור למה נקרא פני. לכאורה, הוא מפני הכבש שהוא שם. יש לדון למה הוא נעשה פני מחמת זה. ותו"ת.
* טו:
** כדי שיראה -
ק"ק ל"ל יכול לתת שיעור, שהרי יש שיעור מיוחד של מים, ויהיה שיעור שיראה בו. אולי תלוי כמה עכור הוא המים, או כמה שחור הוא העפר. ותו"ת.
** איסי -
צריך ביאור ל"ל אומרים שמקדש בכלל משכן, כמו שאומר גמרא בתחילת עירובין.
* טז.
** בטומאה קלה -
כמובן, קל לחלק, שכאן דן באם אותו עבירה שייך, וכאן דן אם בודק לאותו עבירה. ותו"ת.
** אסמכתא -
לכאורה, אסמכתא על הל"מ אי אפשר להיפרש כריטב"א אלא כרמב"ם. ותו"ת.
* טז:
** שבתוך החותם -
צריך לומר שעדיין נחשב מגולח כדלעת (כיון שכל שער שבחוצו גלח).
** מכשיר למעלה -
צריךב יאור איך להגדיר מה נחשב מכשיר. ותחשב. אולי הענין הוא שחפץ אחד נהפך, שכשמצרפים שניהם, נעשים דבר אחד, והוא על שם הכי גדול, שלו בטל החפץ האחר. אם כן, כאן המים הוא המכשיר, שנשאר מים, ודבר אחר בטל ומשנה את המים. ויש לדון, שכיון שהדם נראה, לא בטל (כמו שאומר גמרא בזבחים). ותחשב.
** ואימא -
חיותן- קצת קשה איך יעשה כן, שלכאורה, כשנותן במעיין, יצוף העפר ויצא מן הכלי. יש לדון, שאולי הם כבדים עד שלא יצאו מן הכלי. גם יש לומר שמעיין יורד לתוכו, ואין מי מעיין יוצאים ממנו כלל.[fn:10]
* יז.
** והא לית -
יש לציין לגמרא שאומר שלא סובר כן רבי מאיר לענין איסורים. באמת, כל גמרא קידושין שם צריך ביאור על פי זה. ותחשב.
* יח.
** מחיקה לשמה -
צריך באור למה פשוט לו שאינו לשמה, שהרי הוא לשמה ולשם אחר. ותו"ת.
* יט.
** ורבי יהודה -
מלשון רש"י קצת משמע שחולקים אם מסור לחכמים או יש כלל בזה. ותו"ת.
** היה נטל -
שאין זר- לכאורה, אומר כאן שני דברים חלוקים- שהוא חלק מן העבודה, ושהוא קרוב למזבח. ותו"ת.
** וכהן -
לשון רש"י שקורא לאשה בעלים מעניין, שהיא בעל, ולא בעלים. מצאנו בזמן הזה שיש שקוראים לבעל בלשון רבים. לא הבנתי למה יעשו כן. ותו"ת. אולי רש"י רק ר"ל שכשגמרא אומר בעלים, וקאי על בעלים בעלמא, בציור זה, יהיה קאי עלה. דחוק.
** גמרא זה
קשה, ואז אכתוב בו סיכום:
יש שלש קראי, ושלש שיטות:
שלש קראי הם: והשקה קמא, אחר ישתה, ווהשקה בתרא.
יש שלש שיטות:
רבנן:
והשקה קמא- לומר שמשקה קודם שיקרב מנחה.[fn:11]
אחר ישקה- לומר שצריך שיהיה רושם של האותיות נמחק.
והשקה בתרא- לומר שאחר שנמחק, כופים לה לשתות.
רבי שמעון:
והשקה קמא- לומר שאם השקה קודם שיקרב מנחה, מהני.[fn:12]
אחר ישקה- לומר שישקה אחר הקרבת מנחה.[fn:13] גם מלמד כרבנן.[fn:14]
והשקה בתרא- לומר שאחר זמן מסויים, כופים לה לשתות.
רבי עקיבא:
והשקה קמא- לומר שאחר זמן מסויים (עיין לקמן) כופים לה לשתות.
אחר ישקה- כרבנן.[fn:15]
והשקה בתרא- לומר שישקה אחר הקרבת מנחה.
גם יש עוד דבר שצריך לסכם:
לרבי עקיבא, מצאנו שלש שיטות לענין מתי כופים:
לא כופים- גמרא מפרש שזה אומר שאם בריא היא בהודאתה, לא כופים. רבי יהודה חולק על זה.
אחר שנמחק- גמרא מפרש שזה אומר שאם לא בריא היא בהודאה, כופים. חולקים אם צריך לזה גם כן השלישי.
אחר שהוק’ מנחה- גמרא מפרש שזה אומר שאם לא בריא היא בהודאה, כופים.
מן הגמרא נמצא שלר"ע כופים רק אם לא בריא היא, ונמחק (אחר הק’).[fn:16]
** שלש דברים מעכבים -
לא הבנתי, שמשנה אומר שרבי שמעון אומר שאין הסדר מעכב. ותו"ת. ואולי יש לחלק בין אם מתחילים מנחה, שאז צריכים לגמרו, ואם לא, שאז רק משנים כל הסדר. כמובן, זה דחוק.
* כ.
** מגילתה -
קצת צריך ביאור מה שאומר שאינו ראוי לקרוא בו, שהרי יכולים ללמוד ממנו. אולי סמך על מה שאומר בגיטין שאין לכתוב וללמוד מתורה שנכתב מגילות (עיין שם). ותו"ת. ק"ק ל"ל הביא גמ’ שם ראיה מכאן.
** אגב
, צריך ביאור ל"ל אומרים שיוציאו לעז על כל אשה טהורה וכדומה, מחמת שאולי בא עליה בעל או כדומה. ותו"ת.
** מכאן אמר בן עזאי -
יש לדון אם זה סיבה, כדי שתדע, או הוא סימן, שממה שתורה לא חש שמא לא תדע תורה, צריך לומר שהניח תורה שכל אחד מלמד את בנו תורה.
** היא מתמלאת גידים -
כמובן, נראה שזה מדה כנגד מדה.
* כא.
** על שלשה -
זה אומר ששוהה שלש פעמים של מה שהיה ראוי. קצת קשה למה יזכיר בברייתא ראשונה מה שהוא ראוי, ולא מה שלמעשה שוהה. אולי לא ידע קרא שני עדיין (לשון גמרא מוזר הוא, ומשמע שלא ידע קרא שני לעולם. אולי גופא מחמת זה אומר לשון כזה.).
** מניח גמרא
שאם אינה מצווה, בוודאי לא יהיה שכרה גדול עד כדי שיציל אותה. אולי רק מקשה מהיכי תיתי שיציל אותו, שכל הקראי שאומרים שמציל אותו זכות יש להוקים בזכרים.
** באגרא דמקריין -
יש להעיר שלא מצווים אף בזה. לכאורה, המעלה הוא שגורמים ליותר טוב, שגורמים למי שמצווה לעשות מצווה. יש לדון, שאם הענין הוא רק שנוטלים שכר על הדאגה, אז קשה, שזה לא מכשיר אותו לדאוג על המצווה. אז, קשה מה תירץ גמרא. ותו"ת.
** זה ת"ח -
לכאו’, הפרשת דרכים הוא רק יום המיתה, ומשנה מיירי (וכן פשוט משאר המשלים) בתלמוד תורה. ותו"ת.
* כא:
** מתשעת קבים -
היה נראה לומר שמדה זה לאו דווקא בכל מקום, שהרי נמצא כאן ובב"מ (פרק המפקיד). עיין שם, שדן בזה. נראה שהצד שאינו דווקא הוא מה שנמצא בשנים מקומות אלו, שמשמע שהוא מנין שנוקט כדי לגזם (כמו יג’)[fn:17], והצד שהוא דווקא הוא ששם דווקא הוא, ונקט זה אגב זה. היה אפשר לומר שהצד שאינו דווקא שם הוא שנקט שם מחמת כאן, אבל לא נראה שהוא דווקא כאן. ותו"ת.
* כב.
** מגוש -
חולקים בשבת מהו מגוש; צריך לבאר כל אחד, אם אפשר, בתוך מה שאומר גמרא כאן.
** ולא שכר פסיעות -
מעניין שניתן שכר על זה, שהרי היתה יכולה להתפלל בשכנתה, ואז, נמצא שמה שהלכה לא היה כדי להתפלל. ותו"ת. יש לדחות:
1. אין הכי נמי, לא קבלה שכר, שטעתה, אבל למעשה, למדה חביבות של שכר פסיעות.
2. אולי היתה לה סיבה שהיה יותר טוב ללכת לאותו שרחוק ממנה, ורק שאל לא ר"י למה לא היה סיבה לדחות זה, והוא הטורח, ולזה תירץ שכיון שיש שכר, נדחה הטורח.
* כב:
** אל תתיראי -
וכשמת- חשבתי שחזר להיות לא כל כך רע לת"ח. אולי זה רק הורדוס. וצריך לעיין.
* כג:
** ואפילו רבנן -
דדילמא בתרא דידה- לשון זה מעניין, שמשמע שהוא ספק, ולכן יש לו דין זה, ולא שהוא קצת של כהן, וקצת של ישראל. ותו"ת.
* כד.
** דלא מיחסרא -
קשה, שכל אשה יכולה להיות נשואה בביאה בלחוד. אולי אין זה הדין[fn:18]; או אולי זה נקרא נשואים. גבי שומרת יבם, אף לא צריכה שום כוונה, ולזה מכוון.
* כה.
** אבל מקנים -
משמע שכדי לגלגל עליה, צריכה קינוי.
** סתמא דמילתא -
לשון תירוץ זה קצת חלוק ממה שאמר כמו כן לעיל. נראה שזה לא אומר שמניחים מסתם שכן רוצה אדם, אלא שרוצה אדם, בסתם, במה שבית דין עושה- כיון שבית דין עושה כן. זה אומר שדרך בני אדם להסכים לדעת בית דין. ותו"ת.
זה אומר שבית דין יעשו לא דבר, אף שלא רוצה באותו מעשה, כיון שרוצה בו כיון שבית דין עושים אותו, ואף שנמצא שהיה יותר חפץ לו אילו לא עשו אותו, שאז היה דבר שנעשה בבית דין ועוד שהיה כרצונו. ויש לדון, שאין הענין מה שעשו בית דין, אלא מה שרצו בית דין לעשות (שהוא סימן). ותו"ת.
** אחליה לקינויך -
עיין לקמן בגמ’, שזה נדחה.
* כה:
** ונקתה -
אין דרשה זה, לכאורה, שצריכה להיות "ראוי לבילה,” שאם כן, כל מי שאינו מוליד יש לו דין זה. צריך לומר שיש דרגה של ראוי לבילה שהוא יותר משאר ראוי לבילה, שכולל רק מה שלא ראוי מחמת דבר שנשתנה באופן חשוב בגופו. ותחשב. צריך ביאור ל"ל נניח ראוי לבילה כרגיל. אולי ראוי לבילה הרגיל הוא כך. לא נראה כן, שלכאורה, אין אלם כך. ויש לדון. וצריך לעיין.
** מקנים על ידו -
אם היה צד למעט אותו מקרא זה (ואז צריך מימרת שמואל), ק"ק איך מק’ פשיטא. ויש לדון, שאולי הקרא קאי על קטן, ואגב, ברייתא מזכיר מי שאינו איש. דחוק.
** שחוף -
יש לדון למה ייקרא "מי שאינו איש.”
** חזקת כשרות -
קקק למה יש לה חזקת כשרות, שלכאורה, מתחילת לידתה, נולד עמה הספק. אולי לא היתה ידועה אמה להיות דומה עד לאחר מכן.[fn:19]
* כז:
** תלמיד תלמידך -
עיין במה שבאר רש"י. יש להעיר שלכאורה, לא היה רבי עקיבא תלמיד של רבי יוחנן בן זכאי. אם כן, היה תלמיד של תלמיד תלמידו. אולי ר"ל שלמד ר"ע מתורתו (כמו שפירש רש"י לעיל גבי אליהו). ותו"ת.
* כח.
** כי אית בה עוון בדידה -
יש לדון אם מקשה שאם כן פשוט שלא יבדוק אותו, או מקשה על לשון "כשם" במשנה. לכאורה, אין אחד מהם כל כך קשה, שאין הכרח לומר ראשון, ויש לדחות השני לומר שר"ל שכשם שהמים בודקים את האשה אם רק היא עברה, כך בודקים את האיש אם עבר. ויש לדון.
* כט.
** שכן אב -
קצת צריך להגדיר מה נחשב אב, שאין אב רק דבר שיש לו אותו דרגה של טומאה, שהרי זה אינו מטמא כל כך (אולי הוא טמא כל כך, אבל לא מטמא כל כך), ואינו דבר שטמא מחמת עצמו (שהרי נוגע במת טמא). וצריך לחשוב.
אולי יש שני דברים שנחשבים אב- אב יש לו דאפינישין חלוק בשני מקומות.
* לא.
** כאספקלריא -
שמעתי מי שאומר שאספקלריא המאירה הוא mirror, אבל מכאן, וכן ממה שמשה ראה באספקלריא המאיה, לא נראה כן.
** צדיקי גמרי -
ואם תאמר הרי אחד לא גמור, שרק עשה מיראה. ויש לומר שר"ל שהוא, על פי רוב, צדיק. כמו כן מצאנו במסכת ראש השנה, גבי שלש ספרים.
* לב.
** פרשת סוטה -
עיין בקל וחומר שאומר. יש להעיר שכאן, הדיבור מתיר איסור לאו לשוק. כאן, מגלה על איסור לאו לבעל אם, באמת, אסורה או לא. גם מגלה אם עברה על איסור כרת. צריך ביאור למה, אז, זה יותר חמור. ותו"ת.
* לב:
** מפני מה תקנו -
מעניין שקורא לו תקנה, שהרי לומדים אותו ממה שעשתה חנה. לכאורה, צריך לומר שזה היה אחר התקנה. ק"ק, שאם כן, היה לעלי לדעת, שהניחא אם חנה חשבה מדעתו, מסתבר שעלי לא חשב עליו. אבל, אם היה תקנה, לכאורה, הוא, שהיה השופט, ידע. אולי אותו גמרא רק ר"ל שתקנו אחר שהבינו ממעשה חנה שהוא טוב. יש לדון, שלא רואים טובה זה ממעשה של חנה.
* לג.
** ואכלת -
עיין במה שבאר רש"י. גם היה אפשר לומר שכמו שעל אכילה ושביעה, אין אופן מיוחד, כך על ברכה אין אופן מיוחד, וזה צריך להיות לענין לשון. ויש לדון.
* לד.
** שנים עשר מיל -
היה אפשר לומר שהמים הלך למעלם, ואז רק צריך מקום של מחנה להיות יבש. דחוק.
** באותו עצה -
יש לדון ל"ל למדו מזה שהיה כלב נגדם. אולי הם עשו כיון שהיה חשוב, אבל הוא עשה כיון שהיה מתנגד לאותו עצה. גם יש לומר שהם הכירו, אלא חשבו שחזר בו. גם יש לומר שהם הכירו, אבל כל בני ישראל לא הכירו (ולא יכלו להזהיר את בני ישראל). גם יש לומר שלכך לא עשו, אבל לא הבינו אחרים שלכך לא עשו. ותחשב.
* לה.
** ראש הקטוע -
מעניין שנקרא כן אף שהיה לו בת (או בנות), כמו שאומר גמרא במגילה.
** זמירות -
מרש"י משמע שמה שקרא לו שעשועיו היה רע. אם כן, מה שאמר, "לולי תורתך שעשועי" אינו כל כך טוב. אם כן, מה שבני אדם שרים אותו קצת מוזר.
** על עסקי שלו -
עיין ברש"י. אז, לכאורה, רק אומר קרא שעשה דבר רע. לכאורה, זה פשוט, שאילו לא עשה דבר רע, אטו היה נהרג. ויש לומר שאין, היה נהרג, כדי לענש לדוד, כמו שימשך גמרא לומר.
* לה:
** אלא שריפה -
אין מתגיירים- נמצא שגויים צריכים להתגייר, ולא די לקיים שבעה מצוות. כמו כן רואים מגמרא יבמות (“על אשר שהת לבוא תחת כנפי שכינה").
אפשר שזה רק אחר שבטלו שבעה מצוות, שאז היותו גוי הוא רע מאד, שאין עליו שום מצווה. ותו"ת.
* לו:
** עדות ביהושף -
כ’ בגמ’ ב( ) סוף הקרא. מרש"י זה, נמצא שלא גרס אותו. ותו"ת.
* לח.
** בכל מקום ס"ד -
קצת יש לדון מהיכי תיתי לא. עיין ברש"י
* לח:
** אריכי -
נמצא שזה מהני רק מפני שאם לא כן, אין לדבר סוף (לכאורה, ר"ל שיהיה קשה ביותר לקיים דין זה). ותחשב.
* מ.
** על שאנו -
ואם תאמר הרי אין יראת שמים ביד שמים. ויש לומר שה’ עשה יותר קל לזה ממה שהיה צריך. ויש לדון.
דע שלולי רש"י, היה אפשר לומר שזה ר"ל ש"על כל דבר שאנו צריכים להודות לך, בזה אנו מודים לך.” דחוק.
* מא.
** משום פגמו -
ואם תאמר נאמר אף כאן כה"ג שאינו פסול. וצריך לומר שזה רק מסלק חשש קטן. דחוק.
* מא:
** אגרופה -
נראה שזה קצת פו"ן, שעשו כן לאגריפס.
** מצווה שאני -
יש לבאר על פי מש"א ר.ד.ו., והוא שאחרונים מבארים שאי אפשר למחול כיון שהוא בזיון לעם. אינו נראה רע לעם, אלא טוב, אם אין כבוד למלכם מחמת מצווה.
** שהחניפו -
לכאורה, ר"ל שאף שלא היה עבד, כיון שאמו מישראל, לא היה מבית דווד.
* מב.
** ולא שמעון על בנימין -
יש להעיר שכשהיו לוחמים על בנימין, היו הורגים את כולם, ולא היה כל כך נוח, ואף בזה היה להם לחלוש. ותו"ת.
* מב:
** מכל מום -
של כיעור- אבל לא כל מום, שמה שהיה כל כך גדול הוא גופא מום. ויש לדון, שאף משה היה גדול, וגמרא אומר שהוא רק אם הפרופורשי"נים שלו הם מוזרים.
* מג:
** כל שנותיה -
אומר שערלה מותר- משמע שכך הוא שחשש של מראית עין. ויש לדון, שאפשר שלפעמים יש חשש אחר, אלא שזהו החשש כאן. ותו"ת.
** ת"ל כרם -
יש לדון איך זה חלוק מרבי אב"י. אולי ראב"י דורש מאותו קרא, אבל מרבה יותר. ותו"ת.
* מד:
** שח בין תפילה -
לכאורה, זה איסור דאו’, שגורם ברכה שאינה צריכה. משמע שאיסור זה הוא רק דרבנן. יש לדחות שלא בירך עוד, וזהו האיסור. לא נראה כן, שהיה לגמרא לדחות שהוא איסור דאו’, ולהוקים אותו כשבירך. ותחשב. אולי לשון משנה לא משמע שבירך, שלא אמר כן.
* מו.
** כמלא עול -
קצת מוזר למה יהיה שייך גודל עול למשיכתה. אולי הענין הוא שכיון שהוא שם, רגילים בני אדם לשער בו, שרק צריכים לראות בו, ולראות כמה משך. כיון שבני אדם מודדים בו, הוא נעשה חשוב בתוך קנטקס"ט זה. ותחשב. גם יש לומר שמעיקר הדין, שיעורו דומה לזה, ועשה תורה שיהיה שיעורו זה כדי להיות קל לראות. ותו"ת.
* מו:
** אין לו שיעור וכמה -
גמרא מניח ש"אין לה שיעור" לאו דווקא, ואז שואל מהו השיעור. גם יש לומר שהמשיב שואל (כמו שמצאנו בכ"מ. בר"ן בנדרים מונה אותם.).
מה שהוא קצת יותר מעניין הוא שאומר "אין לו שיעור,” אף שלא רק שיש לו שיעור, אלא אינו הכי גדול, שיש דבר שיש לו שיעור יותר גדול ממנו. ותו"ת.
** שמנוערים… קטני -
כיון שדרש "נערים,” אין צריכים לדרוש "קטנים,” שיש לומר שהם קטנים ממש, אלא נראה שלא היה קרא אומר עליהם שהם מנוערים ממצוות כיון שהיו קטנים, שאין להם דעת. באמת, על מי שאומר שנאמר שהיו מן נעורן, קשה איך נאמר שהיו קטנים ממש, כיון שנענשו. יש לומר שלא בא לבאר שהיו קטנים ממש, אלא לומר שלא היו נערים. דחוק מה לו בזה. גם מרש"י מוכרח נגד זה. אולי לא ענש אותם, אלא היה צורך שימותו (מסתמא, כדי שלא ילעיגו שאר בני אדם).
** ולא בזרעם -
כמובן, צריך ביאור איך יידע זה, שיש להם בחירה….
* מז.
** תאוותו מיהא -
יש להעיר שכבר נתקיים קללות, כמו שאומר גמרא סנהדרין (שהכל נהפך לקללה). צריך לומר שזה בא בלי שום חיוב מחמת ישראל[fn:20]. צריך ביאור, שלכאורה, אנשים אלו נתחייבו. ותו"ת.
** משרבו -
נראה שהענין הוא שמותר למחוק שם ה’ רק מפני שלום בית. אם בין כך ובין כך זונים, לא יהיה שלום בית, כמו שאמר גמרא לעיל. גם יש לומר שאם היא תמות, לא טוב שתיבדק. רק נבדקת מפני הציורים שבו לא מתה, ואז יש שלום בית. אם כן, כאן, שרבו ציורים שתמות, לא בדק.
* מז:
** ולארץ לא יכופר -
לכאורה, קל להוכיח כן ממה שאין עושים ע"ע בכל ציור ופוטרים הורג (ואז מקיימים, “והצילו העדה"). אולי אין להוכיח משם, שאולי אסור לכתחילה לעשות כן. כמו"כ יש לומר שלא מכפר אא"כ בא על ספק.
** בימיו -
רש"י פ’ שא"צ לשאול ר"ל שכבר התקין אותו. גם יש לומר שא"צ לשאול אם הוא דמאי, ומה דינו, שיכולים להניח שהוא מעושר, שלא גזר כבר על דמאי. רק עליו יש לומר כן כיון שגזר; אז אומר כעין "עד ימיו.” אולי לשונו לא משמע כן. ותו"ת.
* מח.
** ואנן -
אם כן, היו להם לבטל מזמן קודם. אולי חלק על כל השאר בדין. גם יש לומר שמתחילה לא היה להם לומר, ולא היו הרבנים יודעים שאמרו. דחוק. גם יש לומר שהת"ח הראשונים חשבו שאין רע באומר אותו, אלא רק אין קיום. ותו"ת.
* מט.
** אחד מת -
סימן למיתה- לא הבנתי כל כך מה אומר בזה.
** אקידושא -
עיין במה שפרש"י. נמצא שאינו רק קידושא…, אלא אף התורה שנלמד שם. אולי סמך על גמ’ ברכות שאומר שאין כל כך ענין לתורה שנלמד שם. לא נראה כן, ששם אומר עוד ענינים. גם לא משמע לשון רש"י כאן כן. וצריך ביאור.
** ביטלה -
משמע שביטול הטעם לא היה שנטל טעם טוב, אלא שנתן טעם רע, וזה בטל טעם הטוב. ותו"ת.
* מט:
** לשון סורסי -
העיר לי א.מ.וו. שאולי רק ר"ל לשון ארמי שהוא מסורס (שאומר "מר" במקום "אמר" וכדומה).
** או לשון יווני -
עיין במה שפרש. גם יש לומר שהוא טוב כיון שיכולים לכ’ ס"ת בו (זה סימן או סיבה).
** עיר של זהב -
נמצא שר"ע, שעשה כן לאשתו, היה, באותו זמן, לפני החורבן. אם כן, היה ריב"ז עדיין קיים, ואפשר שלמד ממנו. אם כן, מקויים מש"א רש"י לעיל (גבי "תלמיד תלמידך" קרוב לדף כח).
** חכמת יוונית -
עיין ברש"י בביאור מעשה של החזיר (חושב אני שרש"י זה בערכין), איך מבאר חכמה יוונית.
* Footnotes
[fn:1] ואין זה כל כך פשוט, שהיה אפשר לומר שגמרא אומר שנכרז עליו שקינא את אשתו, והרי אין לקנאות אשה. אולי זה קצת יותר מסתבר, שהרי מי יודע אם, באמת, עברה אשה. ויש לדון. יש לדחות שאיסור של האשה הוא ייחוד (או איסור ייחוד בפני עצמה או פריצות שגרם קינוי, עם הייחוד). ותחשב.לא נראה, למעשה, שקאי עליו. רש"י לא פירש כן, ונראה שהוא נכון, שלא כל כך קל לומר שהוא "עובר עבירה בסתר,” שאף שהוא לא מקנה אותה בפני כל העולם, הרי מביא שני עדים לזה, והרי הוא, לכאורה, כאילו הכריזו. ויש לדון, שאם נאמר כן, צריכים לומר שמה שמעשה שלה נחשב בסתר הוא שכוונה שיהיה בסתר, שהרי עדים ראו. גם יש לומר שמה שהוא בסתר אינו ייחוד שלה, אלא הביאה. עיין לעיל בזה.
[fn:2] עדיין צריך ביאור מה היינו לומדים מ"בה,” אז, בלי לימוד זה. אז, קשה למה צריך לימוד זה, ולא רק לומדים מ"בה.” ויש לדון, שאולי לא קשה למצוא שום הערה אחרת.
[fn:3] ואולי להיפך, זה ראיה שאין אסמכתא כך. ויש לדון, שרמב"ם ידחה שאומר כן גמרא רק כשהוא פשוט ביותר שאינו ראיה, שאז אינו אף צריך להיות נראה כראיה.
[fn:4] אולי אינו ראוי לרשעים לשמוע, שלא יבינו שהוא טובתו. היא שנחשדת ונתייחדת מסתמא אינה כל כך צדקת.
[fn:5] לכאורה, אי אפשר להיות ששני עדים כשרים נצרכים, שאיזה שני אנשים נמצא. אולי צריך שני נשים, או צריך בעלה, או צריך עד אחד (ואף אשה). וצריך ביאור.
[fn:6] גם יש להעיר שחשבון זה מניח ששהיה של ארבעים דקים הוא כפול של עשרים דקים. אין זה כל כך מוכרח, שאולי הוא יותר או פחות מזה, שלא רק דנים בזמן, אלא בטורח. ותו"ת.
[fn:7] אין לומר שלא היה יכול לגרום שימות, שהרי אין קישוי אלא לדעת.
[fn:8] מסתמא, אותם רשעים לא היו תלמידי חכמים נפלאים.
[fn:9] יש לדון באיזה זמן של יציאה קאי.
[fn:10] ר"ל שהוא כעין waterfall לתוכו.
[fn:11] שם כתיב השקאה קודם.
[fn:12] רבנן חולקים כיון שלא סוברים שתחיל קרא בדין בדיעבד.
[fn:13] שכך הוא הסדר שם.
[fn:14] מלמד שצריך להיות אחר כל מה שנאמר לפניו בפרשה. זה כולל מחיקה, ואומר שצריך לעשות כמו שדורשים רבנן, ואף כולל הקרבת המנחה.
[fn:15] גמרא לא מפרש מה דורש, ואז מסתמא דורש כרבנן.
[fn:16] משמע שלא רק צריך שנמחק והקריבו, אלא שנמחק אחר שהקריבו. יש לדון, שאם כבר הק’, אולי מה שטעו אינו שייך. ויש לדון, שאולי לא היו יכולים למחוק עכשיו.
[fn:17] ואגב, יש לדון ל"ל נקט יג’ אם רוצה לגזם.
[fn:18] הנחתי שזה הדין כיון שאפשר לישא, אולי, בביאה, כשמקדש בו, אבל אולי יש חילוק בין כשמקדש בו לכשלא מקדש בו. ויל"ד.
[fn:19] לכאורה, כדי להיות ספק בה, צריך לומר שידועה אמה להיות דומה בשעת לידתה, אף אם לא נודע כן בשעת לידתה. יש לדון אם יהיה עדיין חזקה. ותו"ת.
[fn:20] יש להעיר שלכאורה, הקללה הוא יותר טוב, שהוא בא ממש מחמת בלק. זה, לכאורה, לא שייך לבלק, אלא גמרא מניח שבא מחמתו. ותו"ת.
