** פרק תפלת השחר
* כט:
** לייט אביי -
יל”ד אי פוסק כר”ג, ולייט על מי שלא נוהג כן, או כר”ע, וסובר שרע להיות ע”ה ולהצטרך תפלה קצרה (ולכן, אף שסבר שטוב לו לומר תפלה קצרה, גרם בעצמו שיצטרך רעה זו, ואז, לייטו).
* ל.
** ר’ יהושוע -
אם גורסים זה, לכאו’ סותר דבריו שבמשנה.
** תפלה קצרה -
רצה לומר תפלה קצרה של עת צרה. יש לדון מהו הדין בזה במעין כל ברכה וברכה.
* ל:
** מעומד -
יש לדון אי צריך לעמוד ממש או רק שלא ללכת. ותו"ת.
** אין הל’ -
כיון שיש שלש שיטות, הוה ליה לומר כמי הלכה. ותו”ת.
ר’ אמי-צ”ב למה הוז’ זה כאן.
** כמה ישהה -
צ”ב למה שואל כן רק כאן ולא בציורים שצריך לחזור (לעיל).
** פרק אין עומדין
* ל:
** אין עומדים -
יש לדון אם זה חוב. לשונו משמע שהוא חוב.
** אפילו -
סמיכותו משמע שמה שלא מפסיק אינו רק מפני שהוה הפסק, אלא שימנע כווני. (ולא נ’ שכיון שהופסק. בי”כ ובי”כ יתפלל לאחר כן, ועל זה לא הפסיק כוונתו.)
** גילו -
א”כ, לכאו’ לא שייך משנה זו בשחרית, שלובש תפילין. ותח’.ינ’ (מרש”י שקרא זה נדרש לשני נפ”מ-לדין זה ולדין שלא ישחק ביותר. דין תפילון רק שייך לדין שני.
* לא.
** יש לדון בחילוק
בין שיחה לדברים בטלים. ותחשב.
** בנות -
נ’ שהוא פסוקה מאד, שאין לשאל עליו ולחשוב בו, שכיון שמנהג הוא, הכל תלוי במנהג ולא בסברה.
** ואב”א -
יל”ד אם גמ’ או רבא אומר את זה.
** ואי בעית -
יש לדון אם אלו חולקים או שרק מביא כמה ציורי הלכה פסוקה כדי לבארו.
** וכל שלא -
צ”ב קצת איך זה מפרש. ונ’ שר”ל שלא ישב אדם בה, והסיבה לזה הוא מה שאדם לא הושיב שם שבת. וא”ת הוה ליה לומר שלא העביר שם אדם. ואולי רק על ישיבה היה לו כח זו.
** רב מרדכי -
יש להעיר שלכאו’, אין מעשה זה שייך לסוגיתינו. (שייך קצת במה ששניהם דנים בלוייה. אם גורסים “רשב”א” כאן, אז קרו בחד איש.) אולי הובא רק כיון שבמקום אחר שהובא מעשה ראישון, הובא.
** רשב”א -
ע’ במסוהש”ס. ואפשר ששני מעשים הם. וא”ת למה לא יאמרו חד. כאן, צריך לומר זה כיון שיש בו רשב”א. קשה מה ששם א”א לומר ר”ש.  (גם יש להעיר שלכאו’ (ויל”ד) ליווהו כ”כ מפני שהיה רבו מובהק. אולי לא מסתבר שיהא לו שבי רבים מובהקים.
** אדם -
יש להעיר שראישון (מה עשה בציבור) דן בזמן, והשני (מה שעשה כשהיה בעצמו) דן במה עשה. ונ’ שאי אפשר לומר בראישון שלא כרע כ”כ, שיש מאריכין בלי כריעות ובשני ר”ל שכוון כ”כ שכרה, והיה אומר כמה טוב היה לולי מה שהיה בציבור.
** בציבור -
לכאו’, מכאן רואים שני חידושים:
א. היה, לפעמים, ר”ע מתפלל שלא בציבור. ואולי היה נאנס.
ב. אף שהיה מתפלל באופן יותר טוב בפנ”ע, לפעמים היה מתפלל עם הציבור.
** חלון -
בכל כזה, יש לדון אם ממש עושה רושם רוחני או שכיון שנמשלו להעלאת תפלה, יוכל לכוון יותר טוב על העלאת תפלה.
** יכול -
בכל אלו, יש לדון אם נחשב שכן צריך לעשות או שיכול לעשות. ותח’ בסיבות. גם יל”ד אם ר”ל שנחשב כן או נהיה מסופקים.
* לא:
כל הנשים- צריך לומר שאין חשש זה לר"ע כיון שאין השכר כל כך גדול. עוד יש לומר- ותלוי במהו הרע בזה- אין רע אם תעשה את עצמה לסוטה.
** כלום -
נראה שלא רק אומרת שלכן תזכה, אלא נראה שאומרת שלא יכול ה’ לומר שלא רוצה שיהא לה בן מפני שאז תמות (מפני לידה), שלא תמות, שרק מתין מחמת בדקי מיתה (ע’ בשבת, שזה, לכאו’, רק לגי’ של “בדקי.” וצ”ל שהאחר הובא אגב.)
** שמושך -
צ”ב למה זה יהא דבר שרוצה.
** והקריבו -
יש לדון אם זה דרשא (שמסברה חיצונה נאמר שכיון ששחיטה נצרך ומח’ בו פוסל ...., צריך כהן; אלא שבא קרא לומר שא”צ כהן) או שרק אמר שאין מקור שצריכים כהן.
** עונש -
יש לדון אם מותר או לא. אם מותר, מעניין שיענש. ואולי רק ר”ל שיש רע שצרעך לסלק. ודחוק.
** כל היושב -
לכאו’, מביא זה כיון שר"א שדן בחנה אמרו. צריך ביאור, אז, למה לא חכה עד שסיים כל מימרותיו בענין חנה. אולי, אז, משמע שיש ענין אחר. צריך ביאור מהו. גם אפשר שאל של הטחת דברים לא היו נאמרים אי לאו אגב ר’ אלעזר. שני לא כל כך קשה, שלא דן רק בחנה. ראשון יותר קשה.
* לב.
יש לדון אם דן בהטחת דברים כיון שר"א שדן בחנה (וכבר הביא גמ’ מימרותיו אגב זה) דן בו או מפני שחנה הטיחה דברים או מפני שניהם (כאו"א או בצירוף).
** אלמלי שלש -
נראה שאומר אלו רק מפני שיבא אחד הדומה שהוא שייך להטחת דברים (הא דמשה). קצת קשה למה לא הביא הא דמשה ראשון.
** של רגל אחד -
לא הבנתי שמשה יש לו זכות אבות, ואז יצרף להיות של ארבע.
** אשתא דגרמי -
ק"ק מה רווח בזה, שהוא תרגום ממש. ויל"ד. ואולי רווח להגיד שאין לו שם אחר, ומה שהם קוראין כן אף תנא קרא כן.
** ואתחנן -
יש להעיר שאותו תפלה לא נענה. (וע’ לקמן שמשמע שנענה קצת.)
* לב:
** זה -
משמע מענין צדקה הוא מה שמחליש ממונו, דאי לאו הכי יחלק לומר שצדקה יותר טוב, שמהנה עני. ואולי סובר שאף על פי כן, כל כך יותר גדול כיון שבגופו הוא. ודחוק.
מאי תקנתיה- יש לדון מה עושה:
תפלתו נענה.
לא חושב שיבא לו, ואז לא מצער לו.
מתנחם על מה שלא בא לו.
** חזק מתורה -
יש להעיר שבשאר כתיב שני לשונות. גם יש לדון מהו מקורו. אפשר שהוא מדכתיב שני לשונות. קשה, שבשאר כתיב שני לשונות. ואולי אם אין צריכים לומר שיש שני לשונות על חד דבר, אין אומרם כן, שדחוק וקשה לומר כן. אולי דורש משמירה ועשייה.
** אמרה ציון -
צריך ביאור למה זה הובא כאן.
מנה"מ- הני מילי הו אמה שטוב לעשות כן, ולא מה שהיו עושים כן.
** לאחר שסיים -
נמצא שלא שהה שעתו. אולי שאני כאן שהיה צורך. דם יש לומר שעסק היה אכתי בתפלה (שהיה אומר שבח תפלה). ותח’.
ממעשה דחסיד משמע שיכול אדם להחמיר לעצמו במצב של סכנה. ואולי לא ידע שירצה להרגו. גם אפשר שידע שהיה יכול להציל את עצמו.
* לג.
** מאי טעמא -
לא באר טעם ר"ע ור"א. אפשר שר"ע סבר כטעם שני שאמר. צ"ב מה יסבור ר"א. ותחשב.
** בתחילת -
יש לדון מה ר"ל:
א. אולי ר"ל שכיון שהוא כל כך חשוב בחד ענין (מה שעיושה חול), נתנו הראש של שייכים לאותו ענין.
ב. אולי ר"ל שכיון שמבדיל בין קודש לחול, עשו סמל זה, ובו הבדילו.
ג. אפשר שקצת מבדיל, ואז צריך לומר אותו קודם ברכות חול.
** גדולה דעה -
מעניין מה שלא אמר שהוא בתחלת בקשות. ואולי כן ר"ל. ותחשב.
** וכל מי -
יש לדון אם זה מימרה בפני עצמו או שאף עליו קאי "גדולה דעה . . . ."
** מכדי -
יש, לכאורה, להקשות כן בכל מחלקת. ותחשב.
** חוזר לראש -
יש לדון למה יחזור, שאומר שמ"ע בלי צורך. ותחשב. גם צריך לבאר מהו טעה בזה ובזה, שאם עבר זמנו כבר, פשוט שלא יחזור, ואי לא עבר, צריך ביאור למה נחשב שכח. שוב ראיתי שהוא שאכל. לא הבנתי למה זה עושה ששכח. ותחשב.
* לג:
** ודילמא -
לכאורה, מקשה שאין הוכחה שמדבר לשני אדונים, שאולי לא כיוון. מתרץ שמניחים שיכוון. ותחשב.
** דאמר רחבא -
יש לדון מי אומר כן:
א. גמרא.
ב. ר"ז.
יש לדון מה עושה בו:
א. מוכיח שהיה רחבא מדקדק. יש לדון בזה שאין זה כל כך שייך לגמרא שלנו. ואולי רק אגב הוא. זה עדיין מוזר אם ר"ז אמרו.
ב. אומר עד מה היה רחב"א, שהיה כרחבא, מדקדק.
* לד.
** אם אין שם -
יש לדון מה אומר:
א. אף אי אין שם כהן אחר, לא ישא את כפיו.
ב. אם אין שם אלא הוא, ואז יש יותר אימה מפני הציבור, לא ישא את כפיו.
** דומה -
לכאורה, קאי על המתפלל. ואולי קאי על התפלה.
** יותא מדי -
יש לדון אם ר"ל שמסרב יותר פעמים, שמסרב ביותר כשמסרב, או שניהם.
** מעט -
קצת קשה למה לא מנה גאוה (ע’ בסוטה (ה.)). אולי חשש לחולק שם.
** כלום -
צריך ביאור למה זה הובא כאן.
** קצרן -
ואם תאמר אם יכול לקצר למה יאריך; יהא ביטול תורה. ואולי הענין הוא שלפעמים צריך למעט ולפעמים צריך להאריך.
** יותר מדאי -
ר"ל, יותר מן הרגיל (שלא היה יותר ממה שהיה טוב, כמבואר במעשה. ואולי ר"ל שהיה שפי הנראה יותר מדי.).
* לד:
** דקא עביד -
יש לדון למה שינה את הלשון.
** אהייא -
יש לדון למה לא יניח (לצד ראשון) שהוא בכולם. יש לדון. ואולי שואל המשיב, כמו שמצינו בכ"מ.
** ארחב"א -
נראה שמביא זה אגב מימרה של נבואה.
* לה.
** מכאן אמר ר"ע -
מוזר, שכבר אמר שהוא חוב; זה היה רישא של הברייתא. ותו"ת.
** שעל הפת -
לשונו משמע שזה הסיבה שאין על לפץ ברכה שווה, והוא שאינו אומר שבזה חלוק, אלא שחלוק מפני זה, מפני שצריך לומר ברכה זה. והוא שבורא מיני מזונות יהא טוב לו, אלא שלא יברכו כיון שיש ברכה אחרת שהוא יותר טובה.
** שכן חייב -
יש לדון למה זה שייך. אפשר שזה סימן שהוא חשוב. גם אפשר שהוא סימן שהוא יותר "של ה’.”
** כאילו נהנה -
חוקרים אם בעיה של מעילה הוא שאוכל מה שהוא קדוש ביותר או שהוא אוכל מה שהוא של ה’. דמיון זה משמע כצד שני, שהרי כאן, לכאורה, הבעיה הוא שאכל מאשר היה לה’.
** דאמר"י -
לא אפשר שרבי יהודה אמר כן, שקדם לר’ ינאי. אפשר שרבי יוחנן אמר כן, אכתי צריך ביאור מי אמר מרבי יוחנן. אולי רבה אמר (ואולי אמר שניהם). אולי גמרא אמרו.
** לא קובע סעודה -
אם זן, כלחם, מוזר למה לא.
** זו וזו לא -
יש לציין לגמרא שאומר שהיו עניים בימי ר"י ב"א (שהוא האומר מימרא זה).
* לו.
** מהו דתימא -
קצת קשה למה לא אמר שיש הוה אמינא שיהא כיין ויהא לו ברכה בפני עצמה. אפשר שכיון שהוכיח שאין ברכה שלה עליה ברב ציורים, סבר שלא יתקנו לה ברכה, ואין צריכים תירוץ ראשון של גמרא.
** עביד איניש -
יש לדון אם ההוה אמינא תלוי במה שאינו מצוי או במה שמזיקו. לשון זה משמע כראשון. ותו"ת.
** וסופו -
יש לציין לסוגיות (בחולין בשני פעמים ובזבחים בחד פעם) שדן בבשר שעומד להקשות. יש לדון למה נחלק בין שם וכאן.
** כוותך -
יש לדון אם זה אומר שחזר בו. אם לא, צריך ביאור למה לא יחזור בו. אולי היה לו שום קבלה. גם יש לומר שרק אומר שרואה סברה חזקה- אבל לא חזק כשלו- לומר כר"י, וההוכחה מזה לפסוק כן הוא שאף החולק סובר שאינו כל כך מוטעה וזה סימן שהוא סברה טובה. ויש לדון.
** רבן גמליאל -
כיון שהגענו לזה, אין תיובתא לרב ושמואל, שיש לומר שסוברים כרבנן.
* לז:
** אמר רבא -
כיון שכבר דן גמרא בזה (עיין ברשי), קצת קשה למה לא מזכירו. ויש לדון.
** מנא אמינא -
צריך ביאור למה אין ראיה מברייתא שלעיל של מעשה קדרה. ואולי שם חלוק כיון שפשלו בקדירה, ושינהו באופן יותר חשוב.
* לח.
** כהאי -
יש לדון אם ר"א חולק או שרק לא אומר דבר שהוא ראיה לדין זה (ולעולם אפשר שרק סבר שדין זה נוהג לע מה שבא מפרי, ואף זיעה.) לשונו משמע שחולק.
** וצריכא -
יש לדון אי זה רק קודם דין של רב ושמואל, אבל אחריו, אף בשבת יכול לכוון לרפואה או לא.
** ורפואה -
יש לדון מהו החילוק בלשון זה. אולי הוא אם מה שאין העיא ברפואה הוא שהרע הוא עלי די כוונה לרפאות (שרק בזה יש לגזור) או שרע של רפואה  הוא על אף איל א מחוון, אלא שלא אסו רבנן אלא כשהוא מכוון (שאם אינו מכוון, שאין המעשה שלו כל כך אם אינו מכוון. ויש לדון.)
** כי היכי -
לכאורה, הוא שכשיודעים כן, יהיה לשון עבר, ועל אותו ידיעה קאי. יש לדון.
* לח:
** טעמא -
מצינו שישאל גמרא בביאור קרא וישאל מה לנו בזה. לפעמים, ורק אי אין לו ביאור אחרת, יאמר שיש נפקא מינא לביאור קרא. אז, מוזר מה שאומרו כאן ראשון למה שלומדים ממנו. ותו"ת. אפשר שדן מה מקיים כשזוכר ש’ הוציא בני ישראל, שלרבנן יש ענין ממה שאמר ה’ שהוא כדי שלאחר כן ידעו. יש לדון, שבין כך ובין כך יש מצוה.
** אני ראיתי -
אם כן, למדו ממעשה, ואולי אינו כל כך טוב (עיין גמרא ב"ב). נראה שהצה לומר ששמע וגם ראה. גם יש לומר שכיון שחוזר וראה, אז פשוט שלא טעה, שהבעיא בראייה יסולק כיון שמוכרח שכן סובר באמת. ותו"ת.
** שלוקים אמאי לא -
לכאורה, רצה לומר, "וקל וחומר שבשולים יצא בהם," כמה שאומר רשי.
* לט.
** כתנאי -
לשון זה מעניין על מחלקת של שני תלמידי בר קםרא (שרק תלמידים הם, וגם יש לדון למה לא נחשבו אמוראים).
** צריך שתכלה -
יש לדון איך יודעים שזה אף מעכב. ותו"ת.
* מ.
** הביאו -
יש לדון למה שינה מ"הבא" ל"הביאו." נראה שאומר חידוש שיכול לומר כן לכמה בני אדם, אף שאולי הוה אמינא שיש לשהות לראות אם ישיגנו הראשון. ויש לדון.
** אינו צריך -
משמע שכל זה בדיעבד. לכאורה, הוא שיש לו להשיג אותו בפני עצמו או לשאל לו קודם לכן.
** ביום -
יש לדון אם קאי על זמן אכילתו או על זמן שיש לו לדאוג.
גם יש לדון עד מתי דואג. אפשר שכל ימי חייו ידאג. גם אפשר שהוחזק (לאחר שנים או שלש ימים) שלא לבא, לא צריך לדאוג.
** ביתו -
זה לשון מעניין, שלכאורה, רצה לומר ממנו. ותחשב. אפשר ששומר על כל בני ביתו. אם כן, לכאורה, הוא ענין סגולי.
** אחד מששים -
צריך ביאור מהו הקושיא; דילמה גורם מיתה, אבל מציל מזה. ואפשר שאז אין נפקא מיינא במימרה זה, שאין לאכלו בין כך ובין כך.
** לרבי יהודה -
צריך ביאור איך לומדו, שהרי רק קאי על פירות הארץ, ומהיכי תיתי שמרבה חיטה. אולי לומדים מייתורא. ויש לדון.
* מא:
** ואידך -
משמע שהחולק סובר שממש נדרש משם. עיין בעירובין, שלא משמע כן שם.
* מב.
** לא סבר לה -
קשה למה הביאו לו. יש לומר שרצה לנסותו. גם יש לומר שרצה לדעת מה סובר בזה. גם יש לומר שמותר אם מברכים עליו קודם, ורב פפא לא בירך.
** תכף -
כמובן, זה חלוק משאר. ותו"ת.
* מב:
** בשעה -
לא מנה אותם ר"י כיון שרק מונה ימים, ולא מאורעות. ותחשב.
* מג.
** אבל… לא מהני הסיבה -
יש לדון אם מהני ישיבה עם אמירה שיאכלו שם. ותו”ת.
** דחביבא -
יש להעיר שאף על פי כן, הוא היה האוסר לעלות לארץ ישראל.
** ההוא סבא -
עיין בתוס’ חולין (ו). קשה, אז, איך נלמד ממנו הלכה. ויש לדון בגדרי לא בשמים היא, שכאן רק מגלה פסק. עיין חתם סופר גבי פסק של רבה גבי צרעת (בב"מ), ש,חושב אני, אומר שהוא בשמים כיון שרק ידעו על ידי גילוי משמים. (ועיין שם, שמבואר, לכאורה, שאינו דווקא בכל ציור. ויש לדון אם שם מקשה עליו או רק אומר שאינו דווקא.)
** כדברי המכריע -
משמע שאומרים כלל זה אף כשאינו אומר כאמצע שני השיטות. אולי רק אומרו כאן, ולא פוסק כיון שהוא המכריע, אלא אומר שהלכה כמותו.
* מד.
** מה שמברך
רק בתחלה הוא כיון שאומר גמרא לעיל (לה) קל וחומר לומר שמברך בסוף.
** כל שהוא כביצה -
יש לדון אם רצה לומר שיש ביותר מכביצה שהם יותר טובים כיון שהם יותר גדולים או שיש מיני אוכלים שהם יותר מכביצה (רצה לומר שכן הם בדרך כלל), והם יותר טובים (בproportion לגודלם). ותחשב.
** כאידך -
ואם תאמר הם עצמם חלקו עליו (שדברו עם הדדי), ואז למה חשב שהוא לא חלק. אולי סבר שכיון שסבר כחד של ר"י, מסתבר שסבר כאידך. אם כן, עיקר דיחויו חסר מן הספר (ואולי גילה ששני מימרות חולקים אהדדי, והם שני נוסחאות במימרא אחד). גם יש לומר שסבר שלכן לא אכל (שאותו מאמר גם מגלה, אולי, שרע לאכול). אם כן, בוודאי סובר כן. גילה שלא אכל מפני מימרא אחר.
** נפש -
נראה לציין לגמרא חולין (לג.). חושב אני שראיתי מי שציין שם לכאן, אבל אין אני זוכר.
* מה.
אין מזמנים עליו- לכאורה, זה מפני שאינו מברך כיון שאכל דבר אסור. יש לדון, וז, למה אומרו רק לענין זימון. אולי יש כאן יותר חידוש, שהוה אמינא שאף שאינו מברך, אולי כיון שאכל יהיה זימון, והוא שאולי יש סיבה לו לברך, אלא שיש דבר רע בברכתו. אולי זימון רק צריך שיהיו שלש בני אדם עם סיבת ברכה.
אז, יש לדון למה, למעשה, אי אפשר לזמן עליו, אם הוא שאין לו סיבה לברך או שלא די מה שיש שלש עם סיבה לברך אלא שלש שחייבים לברך או שכמו שבדרך כלל יהיה סיבה רע שידכה סיבה טובה, אף כאן יש סיבה רע, אף שאינו החוטא שאומר מילים של זימון.
יש להעיר שגבי שמש ונכרי, לכאורה, הבעיא הוא שאין להם סיבה. אולי נניח שהם דומים כיון שהם באותו בבא.
** נשים -
יש לדון למה אין אלו באותו בבא של אחרים.
** כי שם -
לא מוכיח שצריך להיות ששלש אלו אכלו כאחת, אלא שמברכים יחד. נראה שרק מוכיח ממנו שיש ענין בשלש מברכים, אבל לא דינו. ויש לדון.
** גדלו -
יש לדון אם דורשים מה שלא יגביה את קולו מלשון "אתי" או מלשון "יחדיו.” על כל פנים, נראה שהדרשה הוא מלשון שמשמע שהם יחד בדבר. אם כן, קשה למה לא אמר שלא יעשה קולו נמוך. אולי דורשים מ"אתי," ואין זה מגלה שצריכים להיות ביחד, אלא שמי שמברך הוא העיקר, והאחרים הם רק עמו (שראינו שדורשים (בבא קמא, גבי שור הנסקל) ש"את" מרבה הטפל לו (אלא שזה יש לדחות שאולי צריך להרבות שום דבר, ומרבה מה יותר דומה לו, ומה יותר יכול להיות בכללו).)
יש להקשות כמו כן (למה לא אמר שלא יעשה קולו נמוך) אף גבי מתרגם, ששם לכאורה רק אומר בקולו של משה. אולי- וזה טייף- יש בקול כל קולות שהם נמוך ממנו. יש לדון, אז, למה אי אפשר להרים קול, שעדיין יש בו מקול של מברך (זה רק בראשון, אבל בשני אומר אחר כן שצריך להיות שווה, ולא נמוך ממנו. ותחשב.)
** רשות -
יש לדון למה נחלק. לכאורה, הענין הוא שאינו כל כך טוב כששנים מזמנים מכששלש מזנים. יש לדון אם הזימון עצמו אינו כל כך טוב או שאין כל כך בני אדם העושים כן, ואז לא חסר כל כך. ותחשב.
** אין רשאים -
יש לדון מהו קושיית גמרא:
רואים כן רק בשלש, ולא בשנים. צריך לומר שאין זימון בשנים.
למה אינו יכול לצאת; בין כך ובי"כ יוכלו לזמן. כן אומר רש"י, וכן משמע מלשון תירוץ גמרא.
לראשון, תירוצו יהיה כלעיל (ואם תאמר כבר יודע כן. ויש לומר שאין זה קשה, שמצינו שעושה כן גמרא כן בכמה מקומות.) לשני, יהיה תירוצו שחייבים לעשות של חיוב.
אם נאמר כשני, נמצא שהיה לגמרא הוה אמינא שיש ענין בשנים, אבל לא חיוב, ויש חיוב בשלש שיהיו שנים שמזמנים. יש לדון, אז, למה יהיה שנים חלוק משלש כיון שעושה אותו דבר (מזמן בשנים). נראה שאולי אין כל כך טורח, שיכול אחד לצאת. ויש לדון, שבשניהם, שנים צריכים לשאר. ותחשב.
* מה:
** דאפילו מאה -
לא הבנתי מה אומר. עיין ברשי; ולא הבנתי אף מה הוא אומר. תחילה, יש לדון למה הוא כל כך פשוט לשעולם לא חייבים. נאמר שזה רק מפני שכן משמע ברייתא (ויש לדון מהו המקור לברייתא). עדיין צריך ביאור מהיכי תיתי שמאה נשים עושים דבר טוב השווה לשני זכרים (באמת, זה תירוץ גמרא, אבל לכאורה, הוא פשוט עד כדי כך שצריך לבאר ההוה אמינא). משמע שכל הדיון הוא אי יכול אם אין חוב, והוא שאולי יש צד שרק מותר אם חכמים צווהו לברך (אולי רק אז יש טוב המתיר הזכרת השם), ובצד האחר, פשוט שבשניהם יברך. צריך ביאור למה. ותחשב.
** טעמא דקוראין -
משמע שמקשה ממה שיש נפקא מינא למה שמהני לקרא לו. לכאורה, גמרא אומר שיש נפקא מינא, והוא אם נחשב שזימן עם שלש או שנים. נפק"מ של זה הוא אם כבר איקבע בחוב. לולי לשון זה של גמרא, היה אפשר לומר שמקשה שמימרת רב משמע (ויש לדון) שיש חיוב לקראות לו. מקשה למה חייב. (יש לדחוק שכן רצה לומר, והוא ש"קראוהו, יצאו מה שחייבו לעשות… ." ויל"ד.)
** לאו אורח ארעא -
יש לדון אם רצה לומר שאינו כל כך מכובד אם רק אחד יאמרנו או שאז אינו כל כך טוב, ואינו מכובד אם נאמר באופן שאינו כל כך טוב. ותחשב.
** והלכתא -
נמצא שגמרא פוסק נגד רב אשי.
** הא דאשכחנהו -
פשוט הוא, שאין להשיב אמן למה שאומר שיברכו, שלא אמר כבר שום ברכה (יש לדון, שאולי רמז שראוי לברך ואולי אף אם יש טוב בזה, יותר טוב לומר ברכה מלהסכים שטוב לברך. גם יש לומר שאי אפשר להסכים לברך אם לא שיברך, שהוא hypocritical. אז, צריך לברך.). כשאומר מזמן ברכה, אין צורך לומר ברכה, שיכול לומר רק אמן, שקאי על ברכה.
** אין זימון למפרע -
יש לדון למה לא:
אפשר שזימון מהנה ברכת המזון. אם כן, כיון שכבר ברכו, אי אפשר לשנותו.
אפשר שזימון טוב רק אם יש להם חיוב ברכת המזון (זה, לכאורה, סימן, ורק רצה לומר שיש להם סיבה להודות… ). כבר נפטר אחר שבירך ברכת המזון.
** נראה כעשרה -
נראה שזה חשוב כיון שהענין בעשרה (ו,משמע, אף בשלשה) הוא אורח ארעא. אולי מה שהוא בזיון תלוי על מה שבני אדם רואים וחושבים, “זה מבוזה.” כיון שלא יחשבו כן אם יראוהו, כיון שיטעו במנין, אין בעיא. זה רק לצד ראשון שכתבנו בביאור "אינו אורח ארעא.” ותחשב ותבין.
** אחד -
אף שפשוט הוא שיש לטורח שנים יותר שוויות מטורח אחד, אין דין זה פשוט, שהוה אמינא שיש ענין להדקים מצווה. גם יש לומר שהוה אמינא שיש יותר טורח לאחד, שטורח באופן חלוק (שלא מפסיק, אלא משהה).
** הא בבונה -
יש לדון בחילוק. אולי רצה לומר שלעולם הוא טוב, אלא שהוא הפסק, ואז, רק בסוף ברכותיו שאין לחוש לזה, יאמר כן. קשה, שאז יאמר כן אף אחר כל ברכה שאומרים בפני עצמה (יש לדון אם יש). גם צריך ביאור בדרך כלל למה יענה אחר ברכת עצמו; כיון שאמר הברכה, אין סיבה להסכים לעצמו ולומר אמן. ותחשב.
* מו.
** בעל הבית בוצע -
קשה, אז, למה נתן לו לר"ז לברך. אולי חשב שהיה לו דין בעל הבית כיון שלו נעשה כל סעודה זה. יש לדון.
** ורבי -
יש לדון אם זה (ו,באמת, כל לשון ברכה) במילת רבי יוחנן.
** נכסינו -
יש לדון למה יאמר אומר כן, שלכאורה, יש לו לברך בעל הבית. אולי מהנה הברכה אם כולל יותר בני אדם. ותחשב.
** מאן -
יש לדון למה מניח שלמאן דאמר שצריך שלש לברכת הזן הוא חד ברכה עם זימון. ואולי זה סיבה לשיטתו. ותחשב.
** שחייב -
יש לדון כאן, וכן בכמה כמו זה, אם אומר שזה הנפק"מ או שמפני זה יש נפק"מ. לשונו משמע כראשון.
* מו:
** במחוג -
יש להעיר שזה לא שייך לר"ש, שהיה סגי נהור. ותו"ת.
* מז.
** אינו אלא טועה -
יש לדון מה לנו בזה:
אפשר שאמן ממשיך ברכה כיון שעושה סיבות טובות שלו יותר חזקים (או כעין זה). אמן הנמשך לא עושה כן.
אפשר שברכה הוא של מברך, ויש רשות לאחרים להמשיכו רק אם נמצא הנאה לו (שעושה טוב, והוא גורם אותו טוב). כאן, שלא גורם אותו טוב, אולי אין לאחר זכות להמשיך ברכתו של חבירו. כמו כן, יש לומר שמה שאינו עושה טוב הוא שאינו חלק מברכתו של חבירו, ומה שאינו חלק ממנו הוא מפני שאין חבירו מתירו להמשיך ברכתו, כיון שרוצה לאכול. ותחשב.
** עיקר -
יש לדון אם הוא עיקר כיון שהוא ראשון או כיון שהיה שם כל הזמן (אף שאולי לא היה אוכל).
* מז:
** אפילו קרא ושנה -
יש לדון אם קאי על העם הארץ או על בניו. ותו"ת.
* מח.
** אביי ורבא -
זה הגמרא שמשמע שהיו תינוקות באותו זמן (שבא לבאר ידיעת תינוקות למי מברכים), והוא קשה לסוברים שיש לגרוס בר"ה (בהא דעלי) שקרה לאביי ורבא, שאביי חי יותר זמן, ומת קודם לרבא (יבמות). אם כן, לא היו תינוקות בחד זמן. ויש שלא גורסים כאן רבא.
** היכי -
לכאורה, לא היה מזמן (שהיה רק הוא וינאי, שאשת ינאי היתה אשה. ואולי גמרא זה סובר שיכול לזמן בשנים.), אלא היה מלמד לו לברך. אם כן, רק לא יאמר שם ה’ או כדומה. ואולי מלך לא רצה לטרוח לומר המילים, ורק רצה לצאת.
** לגרמיה -
קשה, שאינו יחידי, שאף רבן גמליאל סבר כן. ונראה שממה ששאל ליין בדווקא, ולא שאר שבעת המינים (זה מניח ששאל לשום דבר, ולא רק נתנו לו), רואים שלא סובר כר"ג.
* מח:
** כשהוא שבע -
אם כן, יצטרך ארבע ברכות לפניו.
** רעב -
רצה לומר, לכאורה, שכיון שהוא רעב, יכול יותר לדרהר צורך והנאת המזון. אז, יש לו יותר להודות.
** וברך -
אם כן, לכאורה, נמצא מקור אף לברכה על מים. אם כן, שאר ילמדו ממים. ואולי אין הכי נמי, יש מקור למים, אלא שמים חלוק כיון שנקרב על מזבח. (גם אפשר שהוא דרשת ייתור, ואולי כיון שנדרש על לחם, אין ייתור).
** לא כל שכן -
אם כן, יברך אחר שלמד. ויל"ד. ותחשב.
** הטוב -
יש לדון איך יודעים שלא רק בא לזה.
** מלכות בית דוד -
ואם תאמר מה עשו בברכתם קודם לכן. יש לומר שרק רצה לומר שלא קיים חובתו מדרבנן. גם יש לומר שאף אז ידעו שיהיה מלכות בית דוד, ש"לא יסור שבט מיהודה.” גם יש לומר שמה שצריך להזכירם הוא מפני שהם כל כך חשובים בהסטרית ארץ ישראל. אז, לא היו חשובים, כמובן, שלא חיו עדיין, ואז לא היה צורך להזכירם. ותו"ת.
** כי הוא -
לא הבנתי, שזה ברכת המצווה, ולא יוכל ללמוד ממנו ברכות נהנים.
* מט.
** מד"א אינה צריכה -
צירך ליישב כל זה עם גמרא לעיל (מו:).
** ארץ דמפקא -
יש לדון מהו תשובה זה. נראה שר"ל שגרם ה’ את פרי זה- וזהו הדבר היחידי- ואומרים שגרמו במה שגרם שארץ יעשה אותו ובמה שעשה ארץ שגרמו.
** צריכה שני -
קצת קשה מה עשו קודם שאמרו הטוב והמיטב. וצריך לומר שכיון שאי אפשר, בטלו.
* נ.
** עדיף -
רק מוכיח שאינו יותר רע (ועיין ברשי).
* נ:
** הכא נמי פרח זימון -
משמע שהענין הוא שהיה החיוב על הכלל, והרי אינו הכלל, אלא הוא הוא (כמו כן, יש לומר ששינה באופן חשוב מעת שהיה החיוב חל עליו, והוא שפירש ממי שגרמו לו החיוב או שכיון שהיה זמן שלא היה לו חיוב (כיון שלא היה לו יכולת), פקע חיובו, ולא חוזר. (כן משמע מרשי)). לולי זה, היה נראה לומר שלא נפטר, אלא קיים, שהכלל עשו זימון. ותחשב.
** מסלקן -
יש להעיר שכיון שאכלו בלי ברכה, גזלו. אם כן, אי אפשר לברך עליו. יש לומר שלא אכלו כל כך עדיין, ולא נחשב גזלו. גם יש לומר שלא ממש גוזלו. גם יש לומר שאין בעיה כיון שאין גזילה שעשה נצרך להמשך אכילתו, שלא היה צריך לאכול בלי ברכה להמשיך אכילתו, שהיה בידו לברך. אבל, בשאר גזל, לא היה בידו לבא לו באופן היתר. גם יש לומר שלכן אומר ששכח, שאולי כיון שרק גזלו בשוגג, אין עליו דין מאכל נגזל לענין ברכה (ודע שזה לא נוגע לגזל ממש, ששם מצווה להחזירו. כאן, אין חזרה.) גם נראה שאולי שאני הכא שעל ידי ברכה, עושה שאינו גזול עוד. ויש לדון, שבבת אחת נעשה. ויש לדון. ותחשב.
** הואיל ואידחי -
יש לדון מהו סברה זה. אין אומרים, לכאורה, דיחוי במצוות, ואז אי אפשר שסברה זה הוא דיחוי ממש. ותחשב.
* נב.
** טפי משיעור -
כיון שהגענו בזה, יש לומר שטעם ממש (וכצד שאין טעם פוגם, אלא שפוחת).
* נב:
** אוכלי תרומה -
יש לדון אם זה מפני שהם כהנים, וכהנים זריזים, או שהוא סיבה אחרת. יש לדון למה לא יסמך רק על מה שכהנים זריזים. אולי יש אותו איסור לאוכלי קדשים. גם יש לומר שמרבה אוכלים בטהרת תרומה, אף שאינם אוכלים תרומה. עדיין מחודש שיעשו כן זרים (ועיין בגמרא חולין, שמניח שלא יעשה כעין זה אלא על מין שדרכו ליקדש כעין זה). ותחשב. (שוב ראיתי שכונתי למסורת הש"ס בזה. ועיין שם.)
** דאית -
לכאורה, זה סימן. ותחשב.
** בורא -
יש לדון איך יהיה משמע לשעבר, הרי רואים שלשון זה אומר שעכשיו עושה כן. ויל"ד. ונראה אולי שיכולים לפרש שלא אומר שה’ בורא (verb) אותם, אלא שה’ הוא הבורא (noun) של האור. אם כן, לא אומר שום tense. אולי, אז, יכולים לומר שמכוון למה שקרה, והוא שבראו לשעבר. ותו"ת.
** משום -
מעניין שנחשב שנעשה בו עבירה. משמע שיש ס"ר בעשייתו, ואף לגוי. (ויש להעיר שגוי צריך לעשות מלאכה בשבת. אולי יש ס"ר וס"ט. יש לדון.)
** מתיב רב יוסף -
אם גורסים רבא, מעניין, שלא מצינו כמה פעמים שאומר רבא מימרא, ורב יוסף מקשה עליו.
** יוצר אור -
קשה, שדילמא הוא על שם שמחדש אותם בכל יום. ותחשב.
** נהורי -
נראה שיש לדון איך נראה, אם יש אור היוצא מנר, וbounce על כל דבר, וזה מה שנראה (כן אומרים חכמי אומות) או אם הוא שכל חפץ נותן שום particle או ray שנוגע בואר וחוזר אל החפץ ושוב לעין אדם. נראה שאם אומרים שיש בו כמה אורות, כוונתינו הוא לצד ראשון, שאז, יש כמה
אורות היוצאים מן הנר, ונוגעות בכמה דברים, ואם אומרים שיש רק אחד, אומרים כצד שני. ותחשב. (ועיין במה שאומר רשי.)
מסבת- היה אפשר לומר שהוא בסתם גוי ואליבא דר"א שאומר (חולין) שסתם גוי מחשב לעבודה זרה. ותחשב.
** נהגו -
נמצא, לכאורה, שמנהג דוחה סתם משנה. ותחשב.
* נג.
** חולה -
לכאורה, “עבירה" של כאן צריך להיות סיבה רעה, אין איסור לגוי. אם כן, נמצא שאין סיבות רעות בפיקוח נפש. (יש להעיר שלשון גמרא כשאומר סברה שמתיר פקוח נפש הוא "מוטב יחלל חד שבת כדי שישמור… " או כעין זה. זה, לכאורה, הוא רק סברה לדיחוי שבת, ולא להיתירו. ותחשב.
שוב ראיתי בזה רא"ש שאומר:
** מחצה על מחצה נמי -
צריך ביאור למה מברך, שלכאורה נאמר שספק ברכות להקל, וכיון שהוא מחצה על מחצה, ספק הוא. ותחשב.
** אקרי ונקט -
נראה שזה חידושו של ברייתא (שיש צד שהוא ישראל), שאי לאו הכי, לכאורה, פשוט הוא. שוב נראה לי שאף זה לא מחודש, שאף שחידוש הוא שיש צד שהוא ישראל, אין נפקא מינא, שאם בין כך ובין כך צריך לבדוק אחריו, מה לנו בזה (והוא רק סיבה שכדי שיהיה ציור שמסתבר לבדוק, צריך להיות תינוק). ואולי עושה שאין צריכים כל כך ראיה שהוא ישראל. ודחוק. ואולי ברייתא מחדש ששל גוי פסול, וזה אופן אמירתו. יש לדון למה ינקט אופן זה. ותחשב. (ונראה, אולי, שהיו משניות שאמרו דינים בציורים מצויים כדי שבאותם ציורים ידעו לא יצטרכו בני אדם ללמוד דבר מדבר.) (שוב נראה לי שאולי יש חידוש במה שיש צד שהוא ישראל, והוא שאי אפשר לברך עוד מחמת ספק, שיש לחוש שכבר קיים מצוותו.)
** מפני ביטול -
קשה, שבין כך ובין כך, צריך לשהות אותו זמן. ואולי יש נפק"מ לזמן אמן. ומעניין, שזה זמן מועט. ויש מזה מוסר…
** תניא -
יש לדון מה זה מוכיח- שאין לבטל בית מדרש- הרי זה פשוט!. אולי מוכיח שאף שיש צורך לא אלבטלו, ואף שהוא לזמן קטן אין לבטלו (לכאורה, יש חידוש רק בצירופם).
** נתרצה -
לכאורה, הוא בעל כרחו, ואז יהא תלוי על דיון של בעל כרחו ומכוון (בפסחים).
* נג:
** מאי לאו ריחקו -
קשה למה לא מקשים כן ממשנה עצמה (מאי "ראוי" ומאי אינו ראוי).
** גוריא בא חמא -
נראה, אולי, שהיה דודו של רבא, שסתם רבא הוא רבא בר רב יוסף בר חמא (עיין בנדרים ועירובין. עיין בשיח שי במראה מקומות.).
* נד.
** שנעקרה -
יש לדון אם רואה מקום כזה בחו"ל:
אפשר שאינו מברך כלל. לכאורה, זה יהיה מפני שאין טוב כי אם בהסרת עבודה זרה מארץ ישראל. ויש לדון, שלעולם עכו"ם רע, ואז הסרתו טוב. אולי לא מברך כיון שמניחים שלא עובדים ממש בחו"ל.
אולי מברכים עליו כמו שאמר במשנה. צריך לומר, אז, ש"ארצינו" משמע כל הארץ. דחוק.
אפשר שמברכים כמו משנה, אלא אומרים "מן הארץ,” ולא מארצינו. ותחשב.
** לא יקל -
קצת קשה למה כתב זה כאן.
* נד:
** שלש פרסה -
זה קשה להבין, שאם היה קרסולו (ankle) גבוה שלשים אמה, נמצא שהיה ratio של אחד לשמנה מאות ממה שהגביה לעד קרסילו. אז, לכל inch, יש יותר מששים feet. אז, אם נניח שבאדם בינוני, קרסולו גבוה שני inches, נמצא שהוא כאדם שמגביה דבר שהוא 120*120 feet. צריך לומר שלא רק היה גדול; אף היה גבור. ותו"ת.
אבן שמשה- יש לדון איזה נס יש בה. יש לומר שהוא סימן לנס של אותו מלחמה. גם יש לומר שאין מברכים על הסלע כלל, אלא על המלחמה (ולא רק שמברכים על האבן כיון שהוא סימן לנס), אלא שזהו מקומו של נס. גם יש לומר שהיה נס שמצאו לו אבן, וזה גרם שינצחו. ותחשב ותבין.
* נה.
** עצבונו -
אם כן, גלגל החוזר הוא, שלא יהא דואג מפני שיודע שכיון שדואג אין רע אחר הבא ממנו. ותחשב.
* נה:
** כי הא דרבא -
יש לדון אם גמרא  אומר כן או הם אמרו כן.
** עולי -
יש לדון כמה מזה הוא ממה שאומר וכמה ממנו הוא מה שאותו אמורא אמר וכמה הוא ממה שגמרא אומר. ותחשב ותבין.
** שנאמר
- נמצא שאומרים לשון זה על מה שאינו קרא (רצה לומר שאומר כן על מה שאינו לשון הקרא). ועיין בתוס’ שבת קכח.: ונראה שאינו כל כך קשה כאן, שאין גמרא מחפש למקור לדבר, אלא אומר שמושג זה נלמד מקרא, ואז רק אומר המושג. (רצה לומר, אין “שנאמר... “ מביא קרא, אלא שלא אומר כולו, אלא אומר מה מגלה קרא.
** את אמרת -
כן קרב לאביי (עיין בנדרים).
** נפישין -
מעניין שלא רואים כל כך בני אביי (לכאורה, רק רואים רב ביבי. אפשר שלא היו כולם תלמידי חכמים או שלא היו כולם נקראים “... בן אביי.”
** לפכוחי -
יש לומר כן בכל טוב לעשותו רע, וקצת קשה למה לא אמרו בכל. ותו”ת.
** מעניין שרבא
, שאמר שרק מראים לאדם ממה שחשב, פשר חלומותיו. אולי זה אחר שהבין שאין פשרונות חלומות דווקא. גם יש לומר שרצה לומר שחפתים ומעשים באים ממה שחשב, אבל נשנו להיות רע או טוב כדי לגלות לו מה יקרה. ותחשב ותבין.
** חזן -
לכאורה, משמע שאמרו כן לו ביחד. לכאורה, אז, אף פשר להם ביחד (או על כל פנים, שאלו זה את זה, או הבינו ממה שקרו להדדי). אם כן, מוזר מה שרבא לא הבין שאולי יש מה שהוא שגורם שלאביי לעולם הוא טוב ולו הוא לעולם רע.
** קל וחומר -
יש לדון מהו הקל וחומר:
“אם רבא, שהוא צדיק, נענש, אנו, שאין אנחנו צדיקים כרבא, לא כל שכן.”
“אם רבא, שהוא צדיק, נחשב בגנב, ואף שאומר גמרא שאין חושדים את אדם אלא אם כן יש בו מעין זה, אנו, שיש בנו, אולי, יותר ממעין שלו, לא כל שכן.”
“אם רבא, שהוא צדיק, ופשוט שלא גנב, נחשד, אנו, שאינו פשוט שלא גזלנו, כל שכן.”
“אם רבא ששולח ממון למלך, ואז אינו צרך להפסיד ממון נחשד, אנו לא כש"כ.”
“אם רבא ששלח ממון למלך לא מצא חן בעיניהם ונחשד, אנו לא כל שכן.”
** ניסא -
נראה שאולי הנס שקרה היה מעשה בתענית שניצול ממיתה משמים.
** דמלכא -
כיון שקללו רבא כן, מוזר למה הלך למלך. ותו"ת.
* נו:
** שונרא -
עיין בעוז והדר (הגו"צ- ה). נראה כן, שלגירסתנו קשה למה מחלק בין שני הלשונות, ולמה אחד יותר משמע זה ואחד יותר משמע זה. ואולי לגירסתינו, כיון שאינו כל כך שווה, אומר שאפשר שאומר דבר טוב זה, אף שאינו שווה, כיון שבין כך ובין כך אינו כל כך שווה. גם יש לומר שאם עלה וירד בחלום יורד מגדולה שכבר יש לו, אלא שזה לא נראה.
ממה שאומר רבא ואביי, נראה כצד ראשון. ויש לדחוקת.
** ירד -
יש לדון אם רצה לומר שאם ירד אחר שעלה, יורד מאותו גדולה או שאם ירד סתם יורד מגדולה שכבר יש לו. ותו"ת.
** יש -
אפשר שרצה לומר שמי שמזכיר אותו קרא טוב… כמו שאמר לעיל (“קודם שיקדמנו… ").
* נז:
** מגלת -
צריך ביאור למה לא נמנה לאחד מן הכתובים.
** נסים -
קשה, שלכאורה, אינו של ציבור. יש לומר שכיון שהיו בני ישראל צריכים לדניאל, לחשב של בני ישראל.
* נח.
** נתן -
נמצא שיכול לעשות כן אף שהוא סומא. ותו"ת.
** ואסהיד -
משמע שקבלו אף שהיה רק עד אחד. ק"ק, ששאלו אם היה לו "סהדי,” שהוא לשון רבים.
* נח:
** ברוך… שהחיינו -
עשה גר"ק מעשה בזה, ובירך על י. שודר אחר רוב שנה.
* נו.
** תחת השמש -
מעניין שזה נחשב תחת שמש.
* נט:
** בית אפל -
נראה שעל זה סומכים לשמש כמימרת רבא (שבבית אפל מותר) (שהיה רבם).
** רב -
עיין בתענית שמשנה את הסדר. נראה שאין חילוק ביניהם, אלא שר"פ אמרו שני פעמים, וחד זמן אמרו כזה, וחד זמן אמרו כזה. נראה שאולי על פי זה נוכל לבאר מה ששמעתי (אולי בשפ ר"מ אטלס) שאומרים עשר בני ר"פ בסיום כיון שאומר ר"פ עשר זמנים שנעבד כתרוויהו. קשה, שחד מהם כפול (הוא זה). נראה שאולי יש להוכיח שאמרו שני פעמים, ואז נחשב שנים.
* ס.
** כחא דהתירא -
זה קשה על רש"י בביצה שכתב שהוא מפני שיותר קשה להקל, שהרי יותר קל לומר שלא לברך. עיין בפסחים כיוצא בזה. וצריך ביאור.
** דאי שמע -
לכאורה, זה רק סילוק אותו טובה. ותחשב.
* ס:
** רבי עקיבה -
נראה לציין לגמרא בסוף שבועות שאומר שרבי עקיבא היה תלמיד של נחום איש גם זו.
* סא.
** והא קחזינן -
היה אפשר לדחות שיש לו רק יצר הרע, ואין לו יצר הטוב. ודע שצריך ביאור כל מושג זה של יצר במה שאין לו ברירה.
* סב.
** פעם אחת -
ק"ק למה, אז, אמרו שלו משם רבי יהושע. ותו"ת.
* סב:
** כשמה -
אפשר שר"ל שכמו ששמה הוא קימור של מה שהוא עושה, הוא קיצור דרך. אף אם רבא לא רצה לומר כן, הוא מעניין.
