** פרק אין עומדין
* ל:
** עבדו -
עיין במה שפירש. יש לדון אם דין זה דין עבודה , ונוהג בתפלה כיון שנסמך לתפלה , או שנאמר גבי תפלה , וקרא מזכיר תפלה על ידי לשון זה כיון שהוא נסמך לעבודה . יש לדון למה לא נפרש כפשטותו. אולי זה פשוט ביותר.
* לא.
** לישרי -
בא לבאר שלא ר”ל שיתיר להם דבר.
** במוץ -
יש לדון למה אכילת בהמה נח’ עראי. אפשר שהוא רק שלא חשוב כ”כ. ולא נראה. יותר נראה שלא מביא לו כ”כ הנאה, ואז לא גזרו עליו.
* לג.
** מזכירים -
יש לדון אם בא לבאר לשון "מזכירים" או שבא לבאר דין המשנה. ותו"ת.
* לד.
** לא ישא -
אימת הציבור- ואם תאמר בין כך ובין כך יהא אימה. ונ’ שר"ל שמפני האימה כשיש דבר שיבלבלו, כמו שינוי, יבלבל. ותו"ת.
** מדקתני -
כ’ בגר"א. ואכתי לא הבנתי מהו הראיה. ואולי עיין במ"מ שמביא.
* לה.
** קמה -
יש לדון מה היה הצד ללמוד מחמת זה ולא מחמת מה שהוא חד מן השבע מינים; הרי הדרשה הוא, לכאורה, שווה. אולי אין הדרשות כל כך שוות. וצריך ביאור.
* לז:
** וכולם -
אלמא- משמע שרב יוסף בא להוכיח שכשהוא כזית מברכים עליו המוציא לחם מן הארץ, ולא שאם אינו כזית לא מברכים עליו כן. ויש לדון. יש להעיר שלכאורה יש כמה ראיות שנחשב פת, שהרי מזמן עליו. ואולי יש צד שאינו צריך להיות ברכתו המוציא לזה. ויש לדון למה אינו סימן. ותחשב.
* לח.
** וצריכא -
דתניא- נמצא שאומרים דתניא על משנה.
* לח:
** דבעי -
שפ פרי- יש לדון למה יהיה ברכתם בורא פרי האדמה:
לא נשתנו ממה שהיו, ועדיין יציאתן מן האדמה נחשב עיקר סיבתן.
אולי הוא מפני שיש לו אותו שם שלפ פרי, ואז יש לו דינים שלו.
עיין בלשון רשי כאן. יש לדון אם הוא משמע כחד צד. ותחשב.
* מג:
** סמלק -
לכאורה, רצה לומר jasmine, אבל אל נראה jasmine כן.
* מד:
** ותרי -
משמע שהיה שמו מר. אולי כשאומר רש"י שמו, רק רצה לומר שכן היה נקרא. (באמת, אם הוא שמו, קצת מעניין מה היה אם לא היה תלמיד חכם. אם היה שמו, יש לדון מי זכה לשם כזה, ומה הוצרכו לעשות להשיגו. ויש לדון.)
** מצוות -
לולב- יש להעיר שבשאר אמר מעשה שלהם או מעשה של סילוקם. כאן, לא אומר.
** מוריק -
תואר פנים- אולי זה המקור למה שאומרים העולם שcarrots עושים בני אדם orange.
** אוי לבית -
עיין במקום אחר שאומר על דברים שהם מונעים חולי מן הבית. יש לציין שם לרשי כאן, שאומר שהוא רק רצה לומר כרסו. ותו"ת.
** קודם -
מספרים קודם- משמע שדן במי שמספר קודם זמן אכילה, ולא (רק) במי שמספר עם מי שאכל קודם אותו זמן.
* מה.
** מאי עמא -
ולאחריו- צריך ביאור למה זה שייך. אולי רצה לומר שמפני מנהג זה גם כן אי אפשר לעשות כר"ט, שאי אפשר לעשות שני הברכות שוות. יש לדון למה לא. אולי צריך להוסיף שבח. יש לדון, שאם אוכל דבר שני לאחר זמן, אומר אותו ברכה ראשונה. אולי זה רק מפני אותו הפסק זמן. אולי, אז, יש לבאר שמה שלא מברך על מאכל שני מיד אינו שכבר יצא ידי חובת הברכה, והודה על כל מה שאכל, שמה שעשה לא היה הודאה על הכל, אלא שאי אפשר להוסיף יותר, שאינו יותר טוב, אבל לעולם לא הודה (דהיינו, שטובתו של דבר שנילא גרם ברכתו ראשון).
גם יש לומר שהוא רק סימן, והוא שידוע לגמרא שברכה אחרונה חלוקה מברכה ראשונה, שהרי על דברים חלוקים באים (יש לדון בזה, ששניהם באים על חד הנאה, לכאורה). אז, מוכיח מברכה אחרונה שאין לומר אותו ברכה ראשונה. יש לדון, שהניחא פשט ראשון שאמרנו היה מבאר שני סיבות למה על פי מנהגינו אי אפשר לעשות כר"ט, אבל שני רק אמר טעם אחד, ולא מהני סימן כלל, שמה לי סימן אם אומר בברכה ראשונה עצמו. אולי רצה לומר שאם לא עושה כן, לא רק הולך נגד חד מנהג- חד דבר שבני אדם עושים- אלא נגד שנים. מעניין שכשדבר תלוי בו, נחשב הליכה לנגדו, אף אי רק עבר על מה שנגדו. יש לדחות שרצה לומר שיכריח שלא לברך אותו ברכה אחרונה, ואז יעבור על שניהם. גם יש חידוש אולי שנחשב עבר על שנים כיון שיש אותו סברה לשניהם. ותחשב. ויש לדון.
** ובכל הני -
משמע שאין החידוש מה שאין בו איסור, אלא מה שאף שדומה לאיסור יכול לזמן עליו. יש לדון בהוה אמינא זה, שיש מהם שהם אסורים באכילה, אבל יש מהם (כמו מעשר) שאינם כן. אולי רש"י רק קאי על אלו שיש בהם איסור. לשונו (דמי… ) לא משמע כן.
על כל פנים, אולי רש"י זה יתרץ מה שהבאנו מנ.א. שהקשה למה צריך לכפול משנה זה כמה פעמים. לרש"י, יש לומר שמחדש על כל אחד שמותר אף שיש דמיון לדבר עבירה.
ודע שאפשר לדחות כל דיוק זה בדוחק שר"ל שאין ברכה בעבירה כיון שאין עבירה.
** עד כמה -
היה אפשר לומר שיש נפק"מ מתי חייבים בזימון. נראה שהיה קשה לרש"י שאם היה גמרא מכוון לומר כן, היה לו לומר, “עד מתי חייבים,” ולא, “עד מתי מזמנים.” ותחשב.
** מנה"מ -
יש לדון מה היה הסברה חיצונה. אפשר שאין סברה חיצונה, ולא היה ידוע מה יהיה הדין. גם אפשר שלא נניח שלעולם חלוק. גם יש לומר שיש צד שבשנים חלוק, כיון שהוא יותר מרבים, או שבעשר יחלק, כיון שחלוק לכל דברים שבקדושה.
לשון רש"י משמע שמסברה חיצונה לא יהיה ידוע שיכול לזמן בשלש. ותחשב ותבין. זה אינו כצד שהוה אמינא שיכול בשנים.
** שאני -
קצת מוזר למה לא אמר הסיבה למה זה חיוב וזה אינו חיוב (יש לדחות שכן כוונתו, וסובר שזה הענין בגדול מצווה ועושה. ותחשב ותבין.), שלכאורה הוא שזה יותר טוב. אולי לא סבר כן, אלא סבר כצד שכתבנו שהסיבה הוא שיש יותר טרחה בשנים.
** רב אשי -
עיין תוס’. אמת הוא שיודה אביי שאין צורך להרים קול, אבל אולי חולק לומר שיכול אם רוצה. יש לדון, שאולי לא נניח שחולק על רב אשי. גם יש לומר שתוס’ אומר לא שאביי מודה, אלא שלא מפסיד כלום, שאינו רע לנהוג כן לאביי.
** לא הוה -
ואם תאמר אטו כולם נולדו בחד יום. ויש לומר שמופלג משמע שהיה זקן מהם ביותר. יש לדון למה צירך זה, ולמה לא יכריע מה שהוא קצת זקן מהם. ותחשב ותבין.
** לפנים -
משמע שעשה כן לעשותו נראה חשוב. קשה למה לא אמר שעשה כן כדי לעשות לו חסד, שרצה לצאת.
* מו.
** כדתניא -
יש לדון למה אומר שהוא רק בתחילה; אולי נאמר שהוא רק בסוף. ויש לדון. באמת, יש להק’ על גמרא למה אין אומרים שיש לו בתחילה ובסוף.
* מו:
** לפני כל אחד -
יש לדון אם אומר שכך נהגו הכל או שכך נהגו פרסיים. ותו"ת.
* מז:
** האי אידגן -
חלה עליו רשות כהן- זה לשון מעניין. ותחשב.
* מט.
** אין חותמים -
עיין בסיבה שכתב. קשה, שכאן אם לא עושה כן, רק יאמר אחד מהם (ודומה לציור שבפסחים שיש לו רק כוס אחד). צריך לומר שסבר שזה יותר טוב. ותחשב למה. שוב ראיתי שבאמת גמרא אומר כן.
* מט:
** והדר לרישא -
יש לדון, אז, למה צריך שיתחיל הטוב והמיטיב, ולא רק שיסיים ברכה שלפני כן. ואולי אינו דווקא. ודחוק.
* נ:
** אין מעבירים -
בזויה- יש לדון בבזוי זה. אולי אומר שעושה שאינו כל כך טוב להיאכל. משמע מלשון ביזוי שאין זה הענין, אלא עושה בזיון לה, ואין לבזות דבר הגורם טוב. יש לדון בזה, ויש לדון מה בזיון יש. ואולי עושה שאינו כל כך טוב, וזה אינו רע בפני עצמו , אלא כיון שהוא עושה בזיון (ומה שאי אפשר לעושת תכליתו בטוב הוא הביזיון.)
* נא.
** מי שאכל -
יעשה ברכה- לשון זה מעניין (ודע שאף באנגלית משתמשים בלשון כעין זה), שהיה לו לומר שאומר אותו או כדומה.
* נג.
** מה שעקר -
נראה שהיה אפשר לרש"י לומר שלא הוציאו כלל, שהיה חפץ אחר. נראה שזה לא נראה לרש"י, שלכאורה, לא שינה באותו זמן שבו עובר לרשות היחיד (וכמובן, כדי להיות שאינו כן, צריך להיות שנוכל להניח ששינה באותו זמן ממש שמקומו שינה.)
* נד.
** שיהא -
יש לדון אם כוונתו לומר ש”לא אמרינן שמזלזל... [אלא תקנו כן] לכבוד הבריות.... “ או ש”לא אמרינן שמזלזל כיון שמכבד בריות בשמו של ה’.” יש להיער שנמצא חילוק אולי למה יש בזיון, אם הוא מפני שמשתמש בשם ה’ לכבד בכיות או מפני שמשתמש עמו בלי כל כך צורך (רצה לומר, לראשון, אולי רע הוא, ולא רק שאין צורך טוב. ותו”ת.)
* נה.
** הימנותא -
לולי רש"י, היה אפשר לומר שאומר שנשבע במי שמאמין בו (ולכך הוא לשון שבועה). ולא נראה שרש"י אומר כן, אלא נראה שאומר שאמר לה שהוא אומר כן באמונה, שהוא באופן שתאמין אותו, שאינו משקר. נראה שזה לשון שבועה כמו מה שאומר גמרא שבועות (לה?) שאף מי שכופל "לא" וכדומה הוא לשון שבועה, שלשון שבועה הוא רק כשאומר דבר, ומוסיף בו דבר לעשות שנראה כאמת.
* נז.
** והני מילי -
משמע שלא קאי על ישמעל (שמזכיר כמה, ולא מזכיר את זה). ויש לדחות. ונראה שאולי יש הוכחה לזה ממה שחילק בינו לשום טעייא. אם רק ראה שמו, פשוט לחלק (שלכאורה, ויש לדחות, הסברה לדמותם הוא שדילמא אותצו טעייא הוא ישמעל. ויש לדון. ואפשר שהוא שהו”א שישמעאל רצה לומר בני ישמעאל. אם כן, אין ראיה.). ותחשב.
** תאנה -
נראה שהענין הוא כמו שאמר גמרא נדרים (מט:) שיש מינים שלא יוצא ממעיים.
* נז:
** דמסרג -
מוזר שלא הזכיר שני הצדדים לעיל (נז.).
* נח:
** ר"ה אמר -
עיין במה שאומר. היה אפשר לומר שבא לבאר מהו כוכבא דשביט.
* ס.
** מדריש -
משמע שהענין הוא שיש לו אותו משמעות. לולי זה, היה אפשר לומר שבא לחדש שיש לו משעות נכון בשני הדרכים. ותו"ת.
* ס:
** שכוי -
דאיכא דוכתי- מוזר מה שיתקנו ברכה על אותו מקום, שלכאורה, אין משתמשים באותו מילה בדרך כלל בגמרא. אולי רבנן שהתקינו ברכות השתמשו בו. ודחוק.
* סב.
** טעמי תורה -
יש לדון מה אומר. משמע שאומר שיש בעיה בלימוד על ידי כתיבתה או שירו או מראהו בידיו. ויש לדון, שנראה שכולל שני האחרונים ביחד. ותחשב.
* סג:
** ינגן -
משמע שאין שררותם ממשפחתם, שאי לאו הכי, היה לו אף להוכיח שהיה מן המנגנים.
