* אין פחות ואין יותר
משניות מזכירים ---- דברים שיש להם גדר מלמטה וגדר מלמעלה:
1. דמי ערכין. אם אדם מעריך אדם, יש גדר למטה ויש גדר למעלה.
2. הגדר למטה: הגדר למטה הוא סלע. חייב לשלם סלע כשמעריך וכהן בודק את המעריך (ולא הנערך, שכ’, “אשר תשיג יד הנודר") ואומר שאין לו ממון לשלם שאר. לומדים שמשלם סלע, ולא כל ערכו, ממש"כ, “ואם מך הוא…," ושלא משלם פחות מסלע ממש"כ, "וכל ערכך יהיה בשקל הקדש." יש שני ציורים:
  1. לא יכול לשלם כל ערכו, אלא רק לשלם סלע. כאן, ההלכה הוא שרק משלם סלע.
  2. לא יכול לשלם כל ערכו, אבל יכול לשלם יותר מסלע. כאן, חולקים רבי מאיר ורבנן אם רק משלם סלע (שכ’ רק סלע, לומר שאם לא משלם כל ערכו, משלם אחד) או משלם מה שמשיג ידו (שכ’, “על פי אשר תשיג יד הנודר").
3. גדר למעלה: הגדר למעלה הוא חמישים סלע, שאומר תורה את זה לערך הכי גדול.
4. בינתיים: אפשר להיות שחייב דבר שהוא בין הגדר למטה ולמעלה. יש שני דרכים שיוכל לחייב:
  1. אם מחייב על עצמו ערך שהוא פחות מחמישים, ומשיג ידו. אז, חייב אותו ערך.
  2. אם מחייה ע"ע ערך שהוא חמישים, ומשיג ידו ליותר מסלע. על"ע, שזה רק שיטת חכמים, ור"מ חול’. (ז:)
5. פתח[fn:1] נדה. יש שני טומאות לאשה שרואה דם: נדה וזבה. פעם ראשונה שאשה רואה דם, היא נדה. אחר כך, יש אחת עשרה ימים; אם רואה אז, היא שומרת יום כנגד יום. אם רואה שלש ימים רצופים, היא זבה. לא טהורה עד שתשהה שבעה נקיים. אחר כן, אם כבר יצא מאחת עשרה ימים ורואה, היא נדה, וחוזר הגלגל.
6. אם אשה לא יודעת אם היא זבה או נדה, צריכה לשהות ימים אחר ראייתה, ואז תדע שחזרה להיות נדה. יש לזה גדר למטה ודגר למעלה.
7. גדר למטה: אם אשה רואה שלש עשרה יום או יותר, פתחה שבעה ימים. אם רואה כן, בטוחים אנו שראתה שלש ימי זיבה. אז, צריכה שבעת ימי טוהר אחר כך, כדי לטהר, ואח"כ, אם תראה תהיה נדה, שבוודאי נגמרו אחת עשרה ימים.
8. גדר למעלה: אם אשה רואה שלש ימים או פחות, פתחה שבע עשרה יום, שחוששים שמא יום אחרון של ראייתה היה יום ראשון של נדות. אז, תשהה שאר ששה ימי נדות ואחת עשרה ימי זיבה.
9. בינתיים: אם רואה אשה בינתיים, אז הוא כלל הוא כך: תקח ימי ראייתה ותחסר ממנו שנים. תחסר אותו מנין שנשאר משמנה עשרה, ואותם ימים הוא פתחה. אז, למשל, אם ראתה שש ימים, פתחה ארבע עשרה ימים. הענין הוא כך: אם ראתה ביום ראשון לנדות, יהיה פתחה מקדים מאם היה רק יום שלאחריו תחלת נדות. אבל, אם היה יום רביעי נדות, אז כבר היתה זבה, ואין שאר ראיות עושות תחלת נדות, וזה תחלת נדות. אז, החשש הוא ששני ימים ראשונים לא היו נדות, שהיו בימי זיבה, ויום שלישי היה יום זיבה. כן הוא עד ראיית שנים עשר ימים. שם, בוודאי היא זבה, שבוודאי ראתה שלש ימים, אלא שהחשש הוא שאותם שלש הם בסוף ימי נדה בתחילת ימי זיבה. אחר שבע ימים נטהרת, ויש עוד יום אחד שהיא באחד עשר ימי זיבה. אז, שוהה שמנה ימים.
10. כל שראתה שלש ימים או יותר יכולה להיות זבה. זבה צריכה קרבן עוף כדי להיטהר, ולכן מביאה. כיון שהוא ספק, לא נאכל. אם ראתה שנים עשר או שלש עשר ימים, בוודאי היתה זבה, ואז קרבנה נאכל. (ח)
11. צרעת. יש ארבע מיני צרעת (בהרת, שאת, ותולדותיהם). אם אדם רואה לבן על בשרו, צריך שכהן (ואפילו הדיוט (ג)) יבדוק אותו. אז, הסדר הוא כך:
צרעת:
ארבע מינים: שאת ספחת בהרת … (גמ’ שבועות)
כהן רואה- שער הפך לבן, ומראה עמוק, טמא אותו
אינו עמוק ושער לא הפך לבן (שניהם או אחד?), הסגר שבעה ימים.
עמד בעיניו- הסגר שבע ימים.
כהה, ולא פשה- טהור.
פשה (או לא כהה?)- נראה שנית (אחר כמה זמן? שבעה ימים?)
פשתה- טמא.
שער לבן, מחיה- טמא
* Footnotes
[fn:1] פתח ר"ל כמה ימים צריכה להיות טהורה עד שתדע אם היא נדה. איני יודע אם מילת פתח ר"ל השיהוי, ואומר המשנה שפתח נדה הוא לימים אלה, או שהפתח ר"ל תחילת נדתה, ואומר שהוא בידוע רק לאחר ימים אלו. לשון פתח יותר משמע כצד שני, שקל להבין איך פתח ר"ל תחילתו (שפתח הוא קרוב לראש ותחלת גוף, וגם הוא תחלת אכילה), אבל לא כל כך קל איך פתח אומר ימי שהוי. ותחשב. אולי ר"ל ימים שצריכה שדבר מסויים יקרה לפתחה. דחוק.ויש להעיר, אגב, שלא לעולם צריכה להיות טהורה לכל הימים. לכאורה, יכולה לראות אם עדיין שוהה שבע ימים באחרון, ואם לא פסק כבר שבעה ימים, שאז רק ייעשה רואה שלש עשר יום. ותו"ת.
[fn:2] קרא אומר שני דברים: מראהו עמוק מן העור, ויש בו שער לבן. יש סימן טומאה אחר שמזכיר הקרא אחר כך, והוא בשר מחיה בתוך הנגע. איני יודע אם אותו סימן צריך עמו מראה עמוק מן העור (אף שאין בו שער לבן) או שיש בו שער לבן (אף שאין בו מראה לבן).
