ב.
הגיע זמן (רש"י)- עיין במה שכ’. יש להעיר שזה דיון בגמרא לקמן (ע"ב). (ונראה שרש"י הוא לשני הצדדים, וגמרא רק דן מה נחשב עיכוב הבעל. אם "נסתחפה שדהו,” אז אותו אונס קרה מחמתו, והוא עכבו. ותו"ת.)
צנועות- צריך ביאור מה לנו אם לא נושאות, שעכשיו שגזרו בוודאי לא ישאו. אולי ר"ל שאין טוב בזה, שבין כך ובין כך אלו לא יתקנו.
ב:
דלמא מת דוקא- יש לדון מה לנו שלא רוצה בביטול הגט:
1. אולי כל הצד שאונס עושה שגט לא חל הוא שאין רע בא לאדם כשנאנס. כאן, מה שבא לו אינו רע.
2. אולי הוא כאילו התנה על תנאו שהוא רק אם הוא עדיין בחיים.[fn:1]
היא גופא קמ"ל- קשה איך משמיע אותו דין, שאפשר לומר שמת הוא גט, ומה שלא מהני כאן הוא מפני שיש אונס בגיטין.
ג.
קדיש בביאה (רש"י)- מה תהא בביאתו- לא נראה שמקשה שהרי הוא אסור, שלא נראה שאז לא נראה שגמ’ מתרץ. אלא נראה שמקשה לאיזה דבר יכולים לשנות ביאתו. אז, מתרץ שיכולים לשנות שיש להם אותו כוח.
ג:
מאי שקדו (רש"י)- יש לציין לרש"י בב"מ שמזכיר (וכן יש רש"י במק"א שמזכיר כן) שלפעמים מקשים מחשוב אחד על אמוראים אחרים.
אונס הוא- לכאו’, לא מקשה על הדין, שלכאו’ יש להם לעשות שלא יקרה אונס זה, אלא מקשה על הלשון. ויל"ד.
אי הכי- קאי על מה שנהגו כן.
ספיקא- ואז אפשר לומר שלכן לא תקנו רבנן (שאם תקנו, יבואו אף בשלישי, ולא יועילו בתקנתם).
ד:
כאן באבילות- אבל בנדה, שהוא גם כן איסור עלה, לא מחמירים. אז, צריך לומר שלו איסור נדה יותר חמור, אבל לה איסור אבילות יותר חמור. ותחשב. אולי היא רק לא נתרצה כיון שהוא מרצה אותה כשאין לו אותו מניעה, אבל כשיש לו אותו מניעה, כמו שיש בנדה, היא מתרצה. ותחשב.
ה.
ידחה- צריך ביאור למה כל כך פשוט לגמ’ שיכולים לדחות יום הכיפורים לזה. אולי שואל שבית דין יאיים על עדים לזה. ויל"ד מהי"ת שלא עושים כן.
מאי איכא בין- עיין ברש"י שכתב (בביאור דיוק גמ’) שלא צ’ להקפיד על הברכה. א"כ, יש עוד נפק"מ.
ה:
מקלקל- משמע שרק אם נאמר כר"י וכצד שלא מכוון לעשות פסח יש לדון בזה, אבל אם מכוון לעשות פסח, לא יכול להיות מקלקל, כיון שמכוון לו. ותח’.
ו:
טרדא- קשה ל"ל ת’ כגמ’ ברכות (יא.). צ"ל שאף שם רק מת’ כיון שטרד על מצווה שיעשה היום, ולא על מה שלא עשה מצווה או על מה שצ’ לעשות לאחר זמן.
וע’ ברש"י שמבאר שכן מפ’ אביי במחלקת תנאים.
ואביי- אף לאביי, אז, נדחה הראיה.
מפיס מורסא- קשה, ששם מותר רק מפני שיש צער. אז, להיפך נק’ משם שיהיה אסור כאן. וי"ל שיש צער במה שלא יכול לבעול אשתו ראשונה. גי"ל שמה שיש מצווה שווה למה שיש צער.
ז:
ואסר לנו (רש"י)- עיין במה שכ’. לכאו’, סובר שפנוי הבא על הפנויה הוא רק דרבנן, והוא נגזר באותו גזירה (שאי לאו הכי, היה יכול לומר שהאיסור הוא איסור דאו’ של ביאה).
מאי מברך (רש"י)- יצירה ראשונה- צריך ביאור למה רק נברך על יצירה שניה. לכאו’, יש שני בני אדם מזדווגים- זכר ונקבה. אז, צריך לברך לכל אחד, שברק אחד, לא היה זווג. ותחשב.
ח.
משמח חתן עם הכלה- רק מונה שש, אבל מוסיפים על זה ברכת בורא פרי הגפן.
בר מערבא- לכאו’, זה לא היה שם אביו, אלא ר"ל שבא ממערבא. ויש לדון למה לא היו כל בני מערבא מכונים כן. אולי היה הראשון לבוא. גי"ל שהיה עוד תחליפא בבבל. ואם תאמר יקראו לו בשם אביו. אולי היה אחר באותו שם אב בבבל. גי"ל שהיה שם של אביו של ר"ת קשה לומר.
בנין עדי עד (רש"י)- יש להעיר שלא חיתה חווה עד עד. אולי כיון שיש נשים עד עד נקרא בנין עדי עד.
ח:
חשיב את- מענין שתולה בחשיבותו ולא בחשיבות בנו.
חשיב את- ואם תאמר הרי זה דבר נאה, אבל אין זה שייך כלל לנחמתו. אולי אין הכי נמי, אבל כיון שמשמח אותו, נמצא מתנחם. יותר נראה לומר שחלק מן הצער בא ממה שחשב שבא מחמת עונש לו (א. ירא שמא חוטא הוא. ב. חשב שכמעט המית את בנו.). אז, אמר לו שאינו כן, אלא מת לסיבה אחרת.
דר"ל- יש להעיר שכאן אמר אותו מתורגמן של ר"ל.
רבים ישתו- ואם תאמר איזה פתיחת פה לשטן יש כאן, שבהכרח ימותו.. מחודש לומר שהזכרת מיתה יעשה שימותו יותר מוקדם. אולי אפשר שמשיח יבוא ולא ימות. זה מניח שלא מתים אחר ביאת משיח.
ט.
מפני מה (רש"י)- רש"י מזכיר שהרבה עדים ידעו. משמע שבלי זה, לא היה קשה. צריך ביאור ל"ל נקשה איך דוד נשא אותה, שיודעים אנו וידע דוד שבא עליה. ותחשב. שו"ר בתוס’. תוס’ כ’ כמש"כ (אבל קשה למה צריך להביא הא דפתח פתוח, שלכאו’ אין גמ’ מחדש שלא צ’ עדים לעשות איסור, אלא להודיע, אלא גמ’ מחדש שזה נחשב ידיעה. ויש לדון.)
אונס- זה מחודש; היה נראה לומר שדין אונס רק עושה שרע לא בא לה, אבל רע יכול לבוא לו. אולי זה בכלל רע לה, ואז לא בא. (וקשה, שאז מי שבא על אשת איש ואנסה יהיה פטור מן המיתה, שהוא אנוס. וצריך לחלק בין אונס שפוטר ממיתה ואונס שמתיר לחזור לבעל[fn:2], ולומר שכמו שמתיר לחזור לבעל, כך מתיר לישא את הבעול. ותחשב.)
ט:
ביהודה- צריך ביאור למה זה עושה שלא יהיה לו טענת בתולים, שהרי היא עדיין אינה בתולה. אולי היה לו לדעת שאולי טעה כך. ותחשב.
י.
אפך- נמצא שיכול לומר "מכאן סמכו" לומר שדין דאו’.
מאי קנסא (רש"י)- משמע שצריך אדם לפשע כדי לחייב אותו על קנס. עיין בתוס’ ותורא"ש בגיטין יט:.
ממעות קפטקיא- צריך ביאור למה פשוט לגמ’ מזה שהוא דאו’, שאולי רק מחמיר כך אף בדבר שהוא מדאו’.
י:
נתחייב- לכאו’, לא ידע לפני כן. (ויש לדון, שאולי היה משקר.) אם כן, מעניין שאינו נחשב מקח טעות.
יב.
עדים- נמצא שאף שסמך על קנה רצוץ, שאנן לא סומכים עליו, כיון שסמך עליו, נחשב מקח טעות. ותו"ת.
יב:
צד כהונה- צריך ביאור מהו הצד שאחרים לא יוכלו, שלא יהיה אלא תנאי בעלמא. ויש לומר שלא טוב לאבד ממון. אף שבאמת חל, אולי היו רבנן אומרים להם שלא לעשות כן. גי"ל שהו"א שהוא תנאי לתת ממון, ואין לו דיני כתובה. ותחשב.
דאיכא מגו- לא מבאר גמרא מה יש מגו, ולמה נאמנת כשטוענת שהיא מוכת עץ תחתיו.
יג.
אלא לאו- זה כל כך קשה, שהיה אפשר לומר שאין אותו מד"א שאומר הלכה, אלא יש כלל של הלכה, ושמואל חולק על מה שיכריע אותו כלל, ואז לא יהיה הלכה כשמואל. ותו"ת.
ליכא למימר מגו- אז, לרבי יוחנן, צריך לומר שדוחים שנאמנת מחמת חזקתה. יש לדון אם חזקה יהני לה כאן. ואפשר שאף בראשון שאמר שמואל רק מוסיף ראשון, ולא מוסיף שאר שבאמצע. ותחשב.
נתין- ואם תאמר ל"ל הולכים בתר רוב. חושב אני שגמ’ לקמן יאמר שהוא קבוע.
בד"א- צריך ביאור איזה דין יוצא כאן משתיקות שלו. אולי הוא פסול לכהונה. אם כן, רק נוגע בבן. לא משמע כן מן המשנה. ותחשב.
יד:
והא אמרת רישא- היה אפשר לומר שסבר כר"ג, שפוסל באלמנת עיסה.
טו.
ובנמצא- ר"ל, ואז לא גוזרים רוב אטו קבוע.
קבוע (רש"י)- אין שם אלא אחד- נמצא שאף חוששים למעוטא דמיעוטא גבי קבוע. לכאו’, אין מקור לזה מן הקרא, וצריך לומר שאין סברה לחלק.
אלא (רש"י)- נמצא שסובר רש"י שצפרדע, על כל פנים כאן, הוא פרו"ג, ולא קרוקודיי"ל.
ספק נפשות (רש"י)- מעניין שצריכים קרא לומר שלא להרוג מספק. (קצת משמע כצד שכתבנו שחיוב מיתה לא רק עושה טוב במיתתו, אלא עושה שאין לו זכות לחיות, ואז אין רע במיתתו. אם כן, אין וודאי של רע נגד הספק של טוב. ותחשב.)
טו:
להחזיר- לכאו’, עדיין לא חייב, שהוא רוב נגד חזקה. ותו"ת.  אבל שו"ר ברש"י. וצ"ב.
תורא דידיה- אם כן, לכאו’, קצת פשוט הוא. ותחשב.
טז.
הכא- אערומי- קצת צריך ביאור מה נהנה בהערמה זה. ותו"ת.
טז:
במקום שאין כותבים- במקומות אלו, יש לחוש שמוציא עדים שני פעמים בבתי דינים. שו"ר שגמרא מק’ כעי"ז.
והדר- מעניין שחוששים שעדים יעידו שני פעמים, כיון שגורמים גזל.
יז:
יתמי- יש להעיר שעשה שהוריו מתו ביבמות (קה). אם כן, מוזר שקרא לו כן, ואף אם הוא רק משל. אולי קרה לו כן קודם לכן.
יח:
אין אדם משים- זה מענין, שלא צריכים דיני עדות, כיון שמהני מדין פה שאסר פה שהתיר. ותו"ת.
הרי אלו (רש"י)- כי היכי- לשון זה לא משמע שנאמנותו הוא מחמת מה לי לשקר.
יט:
רב פפא- נמצא שיש שני נידונים:
1. אם נחשב תנאי דבר חלוק, והוא שלא עוקרים שטר. אומרים שנח’ דבר חלוק.
2. אם נחשב קיום שטר עם ביטול או לא נחשב קיום השטר. להל’, לא נח’ קיום השטר.
אין שנים אלו תלויים זה בזה. ותו"ת.
כ.
והוא שאכלום- מעניין שצ’ זה, שלא צריך כן בכתובה.
וביוצא (רש"י)- מניח רש"י שזה רק בשני שטרות הדומות שלא נתעררו בב"ד. היה אפשר לומר שקאי גם על שטר אחד שעררו עליו.
אבל לית- משמע שמה שדר בו אינו חזקה להחזיקו בידו. אולי מיירי בציור שלא דר בו עוד.
כ:
הוה מחסם- יש לדון למה שאל לו עוד אם סבר שלא יעיד.
ואי ליכא תרי- זה ג"כ תקנה לרבי בציור של מתניתין.
מגלתא לא- יל"ד מהו הח’:
1. על מגילה יכול לכ’ יותר. א"כ הוא הדין בחספא גדול.
2. אולי לא מאמינים שטר שבא על חספא, שסתם שטר כשר לא נכ’ על חספא.
ובהא אפילו- אבל לא חשש שיש שום מי שיסבור שהלכה כמותו אפילו מחביריו.
כא:
בפני כל אחד- לכאו’, זה פשוט, שאי לאו הכי, איך יודע שיש לו לחתמו. ותחשב. אולי יכול להאמין את חבריו.
ור"י לרב…- יל"ד אם ר"ל שאחר ששאל אותו, שאל הוא לאחר…, או שהוא כבר שאל אותו….
כשקרא- לכאו’, חוששים שאחד ראה כתיבתם שלא ע"פ עדים, ויכירו שגובים בו. כמו"כ י"ל שרק רואה שחתמו, ויחוש שיגבו בו. אז, עושים שלא יחתמו, שלא מהני.
כג.
שמואל- יש לדון ל"ל היה טענת שמואל נכון. אולי היה נכון, אבל לא היה לו לומר אותו. גם יש לומר שאז אם יבואו עדים לזמן עד אז, תהיו מותרים. (שמואל טען שלא מצוי שיהיו עדים, ואביו טען שאילו הכיר באותו צער, היה חושש לאותו צד.)
בנתיה דשמואל- צריך ביאור מה רצה לקיים על ידי זה. לכאו’, לא רצה שבית דין יפסקו פסק שאינו פסק, שהרי אז אסורים לישא, ומסתמא לא ילך נגד הדין. אז, לכאו’, רצה שיפסקו פסק שהוא פסק. אם כן, צריך לומר שלא חשש למה שהוא טעות, וסמכו על דבר שאינו נכון.
נבאר: צריכים לדון אם יש כאן פה שאסר. אם נניח שפה שאסר מהני מטעם מגו, אז יש לדון אם יש כאן מגו. לכאו’, אין כאן פה שאסר, שהרי שמואל אמר להם מה לומר, ולכן אומרים כן, ולא רק לא באים לבית דין. (באמת, צריך ביאור איך לעולם יש פה שאסר, שמרווחים כשבאים עדים. אולי לא חוששים שרוצים באותו הרווחה כל כך עד לעורר ספקות בדין שלהם.) אבל, כאן, כך היה כוונת שמואל, ולכן לא יהיה נאמן. ותחשב.
בנתיה- יש להעיר שלכאו’, היו נבעלות, שמזה נולד רב מרי. אולי קרה שני פעמים.
כד.
ואינו נאמן להשיאו- צריך ביאור מהו הנפק"מ, שאם תרצה לישא, תישא, ואם לא, לא.
כד:
מעלים מתרומה- ואם תאמר נעלה אותם. וי"ל שלא מעלים אותם מתרומה דרבנן של חו"ל.
כה:
ר"ל- ק"ק, שגמ’ בתחילת יומא אומר שלא היה ר"ל מדבר עם ר"א.
בידו- קשה, שאז יהיה כל כהן נאמן. אולי מצרף זה עם נאמנות אב. ויש לדון, שאם דורש שיש לאב נאמנות, יהיה לו נאמנות לכל (כר”י). אם לא דורש, לא יהיה לו נאמנות כלל.
כו.
ואחתיניה- קשה, שאין ערעור של קול ערעור. ואם תאמר מעלה הוא ביוחסין, קשה שרש"י אומר כן אף כאן בע"ב.
הנך לאכילה- לכאו’, יוצא שמה שיכול לעשות בהם לא משנה שוויותו.
תרי ותרי- קשה, ששם לא חוזרים כל כך כמו כאן. וי"ל שננקוט ציור שחוזרים כל כך.
כז.
לא קושיה כאן- היה אפשר לת’ שלא קשיא, כאן הורהנה וכאן נחבשה. נ’ שסבר כהו"א של צד שני, שאין חילוק.
לכולם כבת אחת- צ"ב ל"ל יאמר שתלוי איך שואלים. אולי כיון שיודעים שהיו שנים קודם שפסקו, הדין שווה.
כז:
חתימת זקן- יל"ד ל"ל חייב לגלח את זקנו כדי להראות מי הוא. אולי לא מאמינים שחנא יאמר שהוא הוא. גי"ל שזה טירחא גדולה מדי. גי"ל שזה רק סימן שיש שינויים, ואולי שינה באופן אחר. לא נ’ כן מרש"י.
תרתי- לא רואים שמשתקי, שאולי לא יודעים.
כח.
אגורי- ואם תאמר נראה מי מוגיר. אולי דנים מי יכול להוגיר אחר כלות אגירות. ותחשב.
לא מזדקקינן- לכאו’, היה לו לשלם קודם (בשעת גי’).
שמותי- יל"ד אם מוסיף או חולק. גיל"ד על מי מוסיף ר"ה.
דרך- ק"ק ל"ל רק אמר שלא נאמן לומר שדבר הוא של פלוני. אולי אלו יותר נזכרים, והם יותר מחו’.
כיון שרוב- אז, צ"ל שיש קול. על"ע בפרק שאמר שאם יש רוב, לא תצטרך עדים. אולי אף רוב שנתרע קצת טוב. גי"ל שזה כשמואל שלא פסוק כרוב גבי ממון, אבל עדיין מהני קצת.
כח:
לא העדתי- לכאו’, זה ראיה שלא רק אומרים כן לענין אכילה, אלא אף לענין שאר איסורים (חלקו ראשונים בזה). ותחשב.
אפוקי ממונא- הומ"ל שהוא דאו’, שהוא גזל. אולי ענין של דרבנן לעיל הוא שיש לרבנן אותו כוח. כאן, יש להם אותו כוח. ותחשב.
דדעתיה- לכאו’, רואים כן ממה שגייר. גי"ל כמו שאומר גמ’ בגיטין שמצוי שגויים מתגיירים.
פירות- צ"ב ל"ל נח’ בל תשחית או איבוד אוכלים, שלכאו’, אפשר לעשות אותו בלי אוכלים. ותחשב. אולי כ"א לוקח פרי. קשה, שמשמע שלוקחים זכרון לדורות.
כט.
הבא (רש"י)- איצטריך- ע’ בגמ’ שלא ממש אומר כן.
כותית (רש"י)- לכאו’, מניח שאיסור זה הוא על כל גויה. חלקו בזה בקידושין.
כט:
ור"פ נמי מיבעי- גם היה אפשר להקשות שאז רק צריך קרא אחד. ותו"ת.
לקיימה- דורש אותו כמו שאומר גמ’ בכ"מ שבהוייתה תהיה. ויש לדון, שאף צריך לומר שישא אותה. אז, קצת צריך ביאור מהי"ת לדרוש שניהם. אולי הוא ממה שנקט לשון זה.
לאו… כריתות- צריך ביאור ל"ל דורשים אחד לעשה ואחד ללאו.
מאי בינייהו (רש"י)- היה אפשר לומר שאיה"נ אין חילוק, ורק משמעות דורשים איכא בינייהו.
ל.
בידי אדם- אם מיתת גנבים הוא בידי שמים, צ"ב ל"ל נחשב מיתת ב"ד שמים. ותחשב.
איבעי ליה- נמצא שחייב על היזק שלא עושה לו מעשה, אלא חייב מחמת שלא הציל אותו.
לא מצי- לכאו’, זה תלוי בגמ’ פסחים (רוצה וא"א). ותו"ת.
לא.
שיראים- ואם תאמר א"א לצמצם. וי"ל שהוא בתוך המשך המעשה. גי"ל שהוא ספק, שאולי צמצם (ורק א"א לדעת), ומוציא מחברו עליו הראיה. גי"ל שזה כר"י הגלילי.
וקרע- הק’ לי מ.ז. שהקרא שממנו לומד הוא מיתה לזה ותשלומים לזה. ויש לדון מהו האסון, אם הוא אילו היה נחשב וולד כחי או אילו המית אב.
לא:
אין דרך יציאה- אז, ל"צ להיות כב"ע.
לח.
ולא עין (רש"י)- עיין במה שפ’. נראה שחושב ששניהם נמלמדים מכאן. קצת צריך ביאור איך רואים שניהם. לכאו’, היה נראה לומר שרק רואים אחד, ואז רק צריכים עוד קרא אחד, ולא שנים אלו. ותחשב.
סובר לה- ר"ל, לכאו’, שאומר כן אליבא דידיה.אולי רק יעשה כן כיון שסובר כמותו.
לא חלקת- קצת יש לדון למה אין זה מקור בפני עצמו, ואז קשה למה צריכים שאר המקורות. ותו"ת.
אשר לא ארשה… מןפנה- ואם תאמר איך ר"ע חולק על ריה"ג, שקרא אומר בפ’ כמותו. אולי אף בזה יכולים לומר אם אינו ענין לומר שלא ר"ל כן. גי"ל שאומר שקאי על זמן שעדיין נשואה, שאז הדין נכון, אבל פשוט. אבל, מוכרח נגד זה (וצריך ביאור למה), כיון שלא אומר כן לת’ בתולה. ותו"ת. אבל, צריך ביאור שאז חוזר גמ’ ואומר כעין זה. קשה ל"ל תי’ עי"ז. אז, אולי רק מק’ על ר"ע שבמשנה. גם צריך ביאור ק’ גמ’ לקמן, שלא קשה שהוא מיותר, שהוא ג"ש מופנה. וצריך לחשוב.
לח:
האי סברה מנא ליה- ר"ל, האי דין מנא ליה.
בגר בקבר- נראה שאולי הדיון הוא אם בגר מהני מחמת הרחק זמן מקטנותאו מחמת שינוי הגוף. ויש לדון, שמצאנו לפעמים שמקטנותה יצתה לבגר.
מ:
פגומה- צריך ביאור למה סבר שמסתבר לומר כן אחר שדחה הראשון. כמו כן, צריך ביאור ל"ל דוחה את זה כמו שדחה את הראשון.
דאי בעי מסר- צריך ביאור, שהממון שנותנים לו אינו אותו ממון שהיה נהנה בנתינת אשתו בתולה למוכה שחין. צריך ביאור למה, אז, נותן אותו ממון. באמת, צריך ביאור איזה הנאה יתירה בא לו מחמת יכולת שלו לתת למוכה שחין מיכולת לתת לאחר. ותחשב.
* Footnotes
[fn:1] אולי אינו ממש כמתנה בתנאו, אלא שמה שממעט אונס הוא תנאי בתנאו, ולא ממעט אונס זה מתנאו. אבל עיין ברש"י לקמן (ג.).
[fn:2] ויש להעיר שנלמדים מפסוקים חלוקים.
