1. חטאת:
משנה אומר שמכפר. רש"י מבאר שצריך תשובה, ומניחים שמי שמביא קרבן שב.
(פשוט שרק מכפר על מה שמחייב אותו, שרק הובא על החיוב. רק לאו (חול’ אם צ“ל בו מעשה) שיש בו חיוב כרת (אף עם שאר חיובים) מחייב כרת.)
1. אשם ודאי:
משנה אומר שמכפר. רש"י מבאר שצריך תשובה, ומניחים שמי שמביא קרבן שב.
(פשוט שרק מכפר על מה שמחייב אותו, שרק הובא על החיוב. יש עבירות מיוחדות שמחייבות אשם.)
1. אשם תלוי:
משנה לא אומר שמכפר. גמ’ מדייק מבאר שני סיבות ל"ל מזכיר אותו. הראשון הוא שלא מכפר כפרה גמורה. רק תולה, שלא יבואו לו יסורים, עד שיודע ומביא קרבן חטאת[fn:1]. השני הוא שלא כתוב כיון שיש דבר אחר (יום הכיפורים) שמכפר עליו. מביא משנה להוכיח כן.
לכאו’, ת’ ראשון מודה לת’ שני (שמביא משנה), אבל יש לדון אם תירוץ שני מודה לתירוץ ראשון או סובר שיש כפרה גמורה. יש לדון, אז, למה היה חייב להביא קרבן חטאת. אז, נראה שמודה.
1. יום הכיפורים:
כפרת יוה“כ אינו פשוט. משנה אומר שיום הכיפורים ומיתה מכפרים עם תשובה. יש לדון אם צריך שלשתם או ר"ל שיוה“כ מכפר עם תשובה ומיתה מכפר עם תשובה. צ“ב. יש שני דרכים לקרוא לאותו משנה. אפשר שאומר שיה“כ צריך תשובה, ואפשר לומר שתשובה צריך יה“כ. דין שיוצא משני הקריאות הוא מח’ תנאים, שרבי אומר שיה"כ לא צריך תשובה (חוץ מפורק עול, מגלה פנים בתורה, ומיפר ברית, שצריכים תשובה), ורבנן סוברים שיה“כ צריך תשובה.
לא מכפר על מה שמחייב חיוב אחר (חוץ מאשם תלוי). מכפר על לאו, אבל (לכאו’) עדיין ילקה. (אז, רק מכפר עליו אם אין בו חיוב, כמו אם אין עדים או אין התראה.) על כריתות ומיתות בית דין, תולה כשיש תשובה, עד שייסורים מכפרים.
לא מכפר באיזה כפרה דן אם צריך תשובה או לא. אפשר שדיון זה היה רק באיסור כרת או כדומה, אבל לא בחיוב אשם תלוי. ותחשב.
1. תשובה:
יודעים שתשובה מכפר, כיון שכ’, "ונקה.“ מכפר על עשה. מכפר על לאו שאין בו עונש. לא מכפר על איסור של לא תשא, כיון שכתיב בו ”לא ינקה.“ יש אומרים שמכפר על לאו שיש בו עונש, כיון שכ’, ”את שמו,“ שממעט שאר לאווים מדין לא תשא. יש אומרים שלא מכפר על לאו שיש בו עונש. (בריי’ אומר שלא מכפר על לאו שיש בו כרת או מיתת בית דין. נאמר בתוך בריי’ שניה, אבל יש לדון אם בריי’ ראשונה יודה לזה. נראה שלא יודה, שנראה שאף הוא יתמעט מ“שמו,“ שכל המקור שלא יכפר עליו הוא שיהיה נלמד מלא תשא. אבל, נתמעט, ולא נלמד. ויש להעיר שאם כן, אם רבנן סוברים כן, צריך לומר שיה“כ מכפר רק על לא תשא, שאין ד“א שלא נתכפר כבר בתשובה. שוב הבנתי שאולי יש מקור אחר, והוא המקור שמזכיר גמרא לשלש דרגות של ראב“ע.)
כשאין תשובה מכפר, לפעמים תולה מייסורים עד שבא יה“כ לכפר (כך אומר בריי’ גבי חיוב לאו שיש בו עונש), ולפעמים תולה עם יוה"כ (יל“ד אם כל אחד יכול לעשות כן או שצריכים שניהם) עד שיסורים מכפרים[fn:2] (כן אומר בריי’ גבי חייבי כריתות ומיתות בית דין).
בריי’ אומר שלא מכפר ולא תולה על חילול ה’, ואין בו כפרה עד שמת. יש לדון אם זה אף לשיטה שסובר שרק על לא תשא לא מכפר, אבל מכפר על לאו שיש בו עונש.
יש שלש דרגות של תשובה. יש תשובה מאהבה, תשובה מיראה, ותשובה מייסורים. תשובה מאהבה עושה שאינו אף בעל מום, שחטאיו נעשה כאילו נעשה בשטות וזדונות נעשים כזכיות. תשובה מיראה עשוה שעדיין בעל מום הוא, אלא שנתרפא, וזדונות נחשבים כשגגות. בשנים אלו, נקראים בנים. אבל, בתשובה מייסורים, נקראים עבדים.
1. מיתה:
מיתה מכפר על חילול ה’. לכאו’, מקל וחומר מכפר על שאר עבירות (שבהם תשובה על כל פנים תולה). יש לדון אם זה רק אם יש עמו תשובה, יה"כ, ייסורים, או שנים מהם, או כולם. גמ’ אומר שמיתה מכפר עם תשובה. יש לדון אם אומר שתשובה צריך מיתה או אף שמיתה צריך תשובה. כמו כן דן גמ’ גבי יה“כ שנאמר שם. יש לדון אם חילול ה’ שווה לשאר לאווים במה שצריך עם מיתה.
ודע שבמיתה ויסורים, גמ’ לא משתמש במילת כפרה, אלא במילת מירוק. לכאו’, הדרך שבו מכפר הוא חלוק, שכאילו העבירה לא טוען עוד דבר, כיון שכבר קרה אלו, ולא שבטל העבירה. ותחשב.
1. יסורים:
יסורים מכפרים על לאווים שחייבים עליהם כרת ומיתות. צריך עמו תשובה. (כן נראה ממה שאומר שם שכולם צ’ תשובה, אבל יש לדון, שאולי זה קאי על מה שצ’ תשובה כדי לתלות.) יל“ד אם צריך עמו יה"כ.
* Footnotes
[fn:1] אם כן, לכאו’, אם מת, עדיין יש לו חטא זה. אולי מיתה יכפר עליו.
[fn:2] צריך ביאור, שאמר שתולה מייסורים. ותחשב. אולי יש חילוק בין יסורים לכפר ליסורים לעונש.
