פקוח נפש- ואף ספק פק“נ- דוחה כל מצווה שבתורה, חוץ משלש מצוות[fn:1].
יש כמה מקרות שדוחים. בכל אחד, נדון אם נדחה, נדחה קצת, או קיים:
1. רבי ישמאל: קרא מתיר להרוג מי שבא להרגך, כדי לפקח על נפשך.[fn:2] רואים שפק“נ דוחה מצוות.[fn:3]
2. קצת נדחה: אולי זה פק“נ וודאי, שיש חזקה שבעה“ב לא יניח לו לקחת ממונו. אבל, לא רואים שספק פ“נ דוחה את השבת.
3. רבי עקיבא: קרא אומר שלא נוטלים מי שעובד ליהרג. מדייקים שנוטלים אותו להחיות, כמו אם הוא עד. רואים שפק“נ דוחה עבודה. (גמ’ מבאר שיודעים שעבודה חמורה משבת, כיון שדוחה שבת.)
4. קצת נדחה: אולי זה פק“נ וודאי, שמוסרים זוג של ת“ח ששומעים אם יש בדבריו אמת. אבל, לא רואים שספק פ“נ דוחה את השבת.
5. ר“א בן עזריה: מילה דוחה שבת, אף שהוא מצווה של אבר אחד. קו“ח שפק"נ ידחה שבת, כיון שהוא בכל גופו.
6. קצת נדחה: אולי זה רק בפ“נ וודאי, אבל לא רואים פ“נ ספק.
7. רבי יוסי בר’ יהודה: כ’ ”אך“ גבי שמירת שבת לומר שלא לעולם- כמו בפקוח נפש- צריכים לשמור את השבת.
8. קצת נדחה: אולי זה רק בפ“נ וודאי, אבל לא רואים פ“נ ספק.
9. רבי יונתן בן יוסף: כ’ ”כי קדש היא לכם,“ שאומר ששבת מסורה בידכם, ולא להיפך. אז, לא מתים כדי לקיים שבת.
10. קצת נדחה: אולי זה רק בפ“נ וודאי, אבל לא רואים פ“נ ספק.
11. ר“ש בן מנסיה: דורשים מ“ושמרו בנ“י את השבת“ שנדחה שבת אחת לקיים כמה שבתות.
12. קצת נדחה: אולי זה רק בפ“נ וודאי, אבל לא רואים פ“נ ספק.
13. שמואל: כ’ ”וחי בהם,“ שאומר שרק מקיימים מצות אם יגרום שנחיה.
14. לא נדחה.
השלש שאינו דוחה הם:
עבודה זרה:
כתיב, ”בכל נפשך,“ שואמר שצריכים לעבוד את ה’ אפילו אם הוא נוטל את נפשך.
שפיכות דמים:
לומדים כן מסברה. רק יכולים לעבור עבירה כדי להציל נפש. אבל, כאן, בין כך ובין כך אחד ימות. אז, לא מציל נפש, ואז, לא יכול לעבור.
עריות:
קרא מדמה מי שעברה על איסור אשת איש למי שעבר על רציחה. לומדים מרציחה שיהרג ואל יעבור.
* Footnotes
[fn:1] עיין בכתובות (יט.) שמצדד שיש עוד איסור שלא דוחה, והוא עדות בשקר. אבל, דוחה צד זה.
[fn:2] קשה, שאין פק“נ דוחה רציחה. צריך לומר שכיון שבא במחתרת שאני. וצריך ביאור.
[fn:3] לא מפרש גמ’ איך רואים כן בשאר מצוות. זה יהיה בעיה בכמה מדרשות אלו, אבל לא מבאר גמ’ איך לתרץ לזה.
