** פסולי שעיר המשתלח. שלש
מצאנו
פעמים שיפסל שעיר המשתלח:
1. בעל מום. דורשים את זה מ"לה’" שכ’ גבי בע"מ.[fn:1]
2. ואם תאמר איך נמצא שיהיה בעל מום, שצריך הגרלה, ולהגרלה, צריך להיות ראוי לה’. יש לומר:
  1. זה כשיטה שלא צריכים הגרלה.
  2. זה נמצא אם שעיר נגרל, ואותו שעיר נעשה בעל מום, ונפדה על זה.
3. מחוסר זמן. דורשים את זה מ"לה’" שכ’ גבי מחוסר זמן.
4. ואם תאמר איך נמצא שיהיה בעל מום, שצריך הגרלה, ולהגרלה, צריך להיות ראוי לה’. יש לומר:
  1. זה כשיטה שלא צריכים הגרלה.
  2. זה נמצא אם שעיר נגרל, ואותו שעיר נעשה בעל מום, ונפדה על זה.
  3. נמצא אם נעשה מחוסר זמן אחר הגרלה. זה נמצא על ידי חסרון זמן של שחיטת אמו. (ואם תאמר הרי לא שוחט אותו. וי"ל שאף ירידת שעיר המשתלח נחשב שחיטה לענין איסור שחיטת אותו ואת בנו.)
5. לא נעשה עבודתו. (אין זה פסול בשעיר, אלא בעבודה.) עבודתו כולל:
  1. הגרלה. רבי שמעון סובר שלא צריך הגרלה. לחולקים, צריך הגרלה. אף לחול’, חלקו אם צריך עליית גורל או הנחה. (שני לשונות של גמ’ חול’ אם מח’ זה הוא רק לפי ר"י, אבל ר"נ סובר שצ’ שניהם, או רק לר"נ, אבל לר"י רק צ’ עלייה.)
  2. שיהיה חי עד זריקת דם של לה’. (יל"ד איזה זריקה צריך.)
* Footnotes
[fn:1] כל זמן שדורשים שלה’ הוא ריבוי, צריך להיות מפני שמקרא עצמו כבר נשמע מיעוט. אז, צריך להיות שמרבה.
