* לשון ראשון:
רב אסי אמר בשם רבי יוחנן: זר שסידר את המערכה חייב. מקשה גמ’ שסידור מערכה כשר בלילה, וכל עבודה שכשרה בלילה, כשרה בזר. מק’ גמ’ על כלל זה מאברים ופדרים (כשרים בלילה ופסולים בזר) ומתרומת הדשן (כשרים בלילה ופסולים בזר), ולשניהם דוחה שהם עבודות יום (סוף עבודה או תחילת עבודה של יום).[fn:1] אז, נשארים בקושיה, והמימרא נדחה.
לכן, פי’ גמ’ שר”א אמר בשם ר”י שזר שסידר שני גזירי עצים חייב, כיון שעבודת יום הוא. מק’ גמ’ שאז יצטרך פייס. תי’ שנכלל בפייס של תרומת הדשן. לומר גמ’ מזה שעבודת יום צריך פייס, ועבודת לילה לא בעיא פייס.[fn:2] מקשה מאברים ופדרים שצריכים פייס, ות’ שסוף עבודת יום הוא. מקשה מתה”ד שצ’ פייס. היה אפשר לת’ כמש"א לעיל, אבל תי’ שהוא מפני סכנה המוזכרת במשנה.
* לשון שני:
רב אסי אמר בשם רבי יוחנן: זר שסידר את המערכה חייב. מקשה גמ’ שאין עבודה שיש אחריה עבודה שפסולה בזר. יש שגורסים שקו”ט של אברים ופדרים ותה”ד, אבל רש"י מבאר שאינו שייך לכאן (שהוא דיון בעבודות לילה).
לכן, פי’ גמ’ שר”א אמר בשם ר”י שזר שסיד שני גזירי עצים חייב. מקשה גמ’ שאז יצטרך פייס. תי’ שצ’ פייס, כמו שבארנו, ומקשה למה אין לו פייס בפני עצמה.[fn:3] לומד גמ’ בזה שעבודה תמה צריכה פייס ועבודה שיש אחריה עבודה לא צריכה פייס. יש שגורסים שקו”ט של אברים ופדרים ותה”ד, אבל רש"י מבאר שאינו שייך לכאן (שהוא דיון בעבודת לילה).
* Footnotes
[fn:1] עיין בתחילת הפרק, שסותר מה שתה"ד הוא תחילת עבודת יום.
[fn:2] לימוד זה לא פשוט, שנראה מזה שעבודת יום צריך פייס, אבל לא נראה מזה שעבודת לילה תמיד אין לו פייס. נראה שאולי יודעים שרבא ידע שאין סיבה למעט סידור שני גזירי עצים מן הפייס חוץ ממה שבלילה הוא. דחוק.
[fn:3] צריך ביאור למה לא הקשה כן לעיל.
