עבודות שזר חייב עליהם:
יש עבודות שהם פסולים בזר. לפעמים, אם עובד זר, חייב מיתה. כדי לחייב מיתה על עבודה, צריך להיות אותו עבודה מקיים שנים או שלש תנאים תנאים:
1. צריך להיות עבודה תמה. אחר שנשלם אותו עבודה, אין עבודה אחר שצריך לעשות לאותו תכלית. זה נדרש ממה שכ’, “ועבדתם.”
2. צריך להיות עבודת מתנה (ולא עבודת סילוק). זה נדרש ממה שכ’, “עבודת מתנה.”
3. צריך להיות עבודת יום. יש שני לשונות בזה (כז:), וחול' אם צ"ל עבודות יום לחייב או לא.[fn:1]
מחמת שני תנאים אלו, רב סובר שיש רק ארבע עבודות שעליהם זר חייב מיתה, והם:
1. זריקה.
2. הקטרה.[fn:2]
3. ניסוך המים.
4. ניסוך היין.
רבי יוחנן מוסיף אחד:
1. סידור שני גזירי עצים יש שני חידושסובר שאין אחריה עבודה, שאין עבודת הקטרה נחשבת להיות לאותו תכלית.
לוי מוסיף עוד אחד, והוא מפני שממעט אחד מן התנאים. לוי סובר שתנאי שני הוא רק "מבית לפרכת" (בהיכל ובפנים מהיכל), כמו שכ’ בקרא, אבל לא חוץ ממנו. אז, מוסיף:
1. הרמת דשן.[fn:3]
* Footnotes
[fn:1] לא ממש מוכרח כן; גמ' רק מזכיר ציור ומביא שני צדדים מה מקשים עליו. לכאו', כולי עלמא מודו לקושיה שניה (עיין שם), אבל יש לדון אם מודים לקושיה ראשונה. הנחנו שלא מודים, שאי לאו הכי, אין שום מחלקת ביניהם. ויש לדון, שאולי אין הכי נמי, אין מחלקת בדין ביניהם.
[fn:2] ואם תאמר הרי הוא עבודת לילה, שלפעמים מקטירים בלילה. וי"ל שזה רק סוף עבודה של יום. (כז:)
[fn:3] ואם תאמר הרי הוא עבודת לילה. ויש לומר שהוא תחילת עבודת יום. (כזז:)
