הוצאת הדשן:
הוצאת הדשן הוא הוצאת התפוח מעל המזבח אל מקום שריפה, שהוא חוץ מן העזרה.
גבי הוצאת הדשן, קרא אומר שילבש הכהן שעושה אותו "בגדים אחרים.” מסברה חיצונה, היינו אומרים שמחייב אותו ללבוש מין בגדים חלוקים ממין בגדי כהונה, כמו שחייב לעשות במקצת עבודות ביוה"כ. זה יעשה שצריך ללבוש בגדי חול.
כ’,”ופשט… ולבש,” שמקיש בגדים שפשט לבגדים שלבש. זה מוכיח ששניהם הם ממין אחד של בגדים, ושניהם הם בגדי כהונה.
אז, צריכים לפרש מה שאומר קרא, ומה הם ה"בגדים אחרים.” יש שני פירושים:
1. תנא קמא אומר ש"אחרים" ר"ל בגדים פחותים. מבאר גמרא שדרך כבוד הוא שילבש בגדים יותר נאים למלאכות יותר נאות. אז, ילבש בגדים פחותים להוציא את הדשן, וילבש בגדים רגילים, שהם יותר נאים, לעבודה.
2. רבי אליעזר אומר ש"אחרים" לא קאי על הבגדים, אלא נדרש על הכהנים. מתיר כהנים אחרים להוציא את הדשן. מפרש שכהנים בעלי מומים כשרים להוצאת הדשן.[fn:1]
הרמת הדשן:
ריש לקיש סובר שאף בהרמה חולקים רבי אליעזר ורבנן אם בעלי מומים כשרים או פסולים[fn:2].[fn:3] מוכיח שאינו עבודה, כיון שרק מחייב הקרא שילבש כתונת ומכנסים.[fn:4]
רבי יוחנן סובר שבהרמה אף רבי אליעזר מודה שאין בעל מום כשר.[fn:5] סובר שצריך ללבוש כל ארבע הבגדים (עיין לקמן, שנבאר שני מקורות לזה), והשנים שנכתבים מגלים על השאר. כתב אותם שנים[fn:6] לדרשות מיוחדות (כתב כתונת כדי לכ’ "מדו בד,” לגלות שצריך להיות כמדתו, כמו שמפרש גמרא בתחילת פרק שני של זבחים, וכתב מכנסים כדי לכ’, “על בשרו,” לגלות שלובש אותו ראשון).
מחלקת תנאים:
גבי הרמת הדשן, כתיב, “ילבש" מיותר. חלקו חכמים מה לדרוש ממנו:
1. רבי יהודה דרש ממנו שצריך ללבוש שאר בגדים (ולא רק כתונת ומכנסים) כשמרים את הדשן.[fn:7]
2. רבי דוסא דורש מכאן שבגדי כה"ג ביוה"כ כשרים לכה"ה בכל יום. החידוש כאן הוא שאבנט של כ"ה היה של בוץ, ולא של כלאים.
  1. רבי דוחה את זה לשני טעמים:
    1. סובר שאבנט של כ"ה היה של כלאים, ולא של בוץ.
    2. סובר שכיון שכהן גדול שמש בבגדים אלו, לא יכול כ"ה, שאינו כ"כ קדוש, לשמש בהם.
3. גמרא גם דורש את זה מ"והניחם שם.”[fn:8] רבי דוסא דורש מ"והניחם שם" שלא יכול לשמש בהם ליוה"כ אחר, אבל כ"ה יכול לשמש בהם.
4. רבי דורש מזה שבגדים שחקים כשרים לכל עבודה.
לפי ריש לקיש, צריך לבאר שחלקו תנאים כמה בגדים צריכים. רבי יהודה סובר שצריך ארבע בגדים, וריש לקיש לא אמר את דינו אליבא דרבי יהודה, והחול’ אומרים שצריך רק שני בגדים, שאין להם קרא מיותר.
לפי רבי יוחנן, אפשר לפרש כריש לקיש. אז, לא חולק עם ר"ל אלא כמי ההלכה. אבל, גם יכול לפרש שיטתו לחול’ על רבי יהודה, ולומר שלא סוברים שאין הדין נכון כיון שאין קרא, אלא סוברים שלא צריכים קרא לאותו הדין, שכיון שגילתה תורה שצריך שני בגדים, פשוט שצריך שנים הנותרים גם כן.
* Footnotes
[fn:1] לא מפרש גמרא מהיכי תיתי שבא להכשיר כהנים בעלי מומים, אבל מצאנו במק"א (שכחתי איפה, ולא מצאתי) שמרבים בעלי מומים כיון שיכולים לאכול קדשים.
[fn:2] כמו כן, סובר שרבנן מחייבים אותו ללבוש בגדים פחותים.
[fn:3] לא מפרש גמרא מה יהיה מקור לשיטת רבי אליעזר ללמוד מהוצאה להרמה.
[fn:4] אין זה מפרש כל כך כוונתו. לכאו’, סובר שמוכרח שאינו עבודה, ולומד אותו מקרא. אז, צריך לומר שסובר שרבנן סוברים שאף שאינו עבודה, צריך בגדי כהונה (כמו ששחיטה, שכשרה בזר כיון שאינה עבודה, צריך להיות בבגדי כהונה, וצריך להיות במקום מסויים. אז, רק בא לפרש איך היה אפשר לרבי אליעזר לומר כן. אבל, אין זה קושיה על רבי יוחנן שחולק, שהיה אפשר לרבי אליעזר לומר כרבנן. ויש לדון, שאולי מקשה שאז הרמה שווה להוצאה, וכמו שמכשיר ר"א בהוצאה, אף יכשיר בהרמה.
[fn:5] לא מבאר מקור לזה. אין אני יודע מהו המקור לדמות אותם, ואז אין אני יודע למה לא מדמה אותם. יהיה קל אם נאמר שנלמד ממה מצאנו, והפירכא יכול להיות שזה עבודה וזה לא עבודה. אז, מה שזה צריך רק שני בגדים יגלה שאין זה פירכא, ובזה, אז, חולקים רבי יוחנן וריש לקיש. ותחשב.
[fn:6] לא הבנתי, באמת, חשבון הגמרא, שמתחיל לומר שגילה רחמנא בשנים אלו, והוא הדין לשאר, ושוב מפרש למה כתב שניהם. לכאו’, היה לו לפרש רק למה כתב אחד מהם, שחברו יכול להיות כדי לגלות. אם נאמר שאין הדרשות שידרוש דרשות של ייתור, אז יכולים לומר שהיה אפשר לקיים שני הדרשות באחד, ולכן צריך דרשה לכל אחד.
[fn:7] יש לדון מהיכי תיתי לרבות שני הבגדים, ולא רק אחד. אולי לא יודעים איזה אחד לרבות.
[fn:8] לכאו’, לשון רבי משמע שלא דורש משם, אלא יודע אותו מסברה.
