יש בין הכל 16 בהמות:
כבש של תמיד של שחר- 1
כבש של תמיד של בין הערבים- 2
פרש שלו- 3
שעיר לה'- 4
שעיר המשתלח- 5
פר לעולה- 6
שבע כבשים 7-13
שעיר של חוץ- 14
איל שלו- 15
איל של עם- 16
(יש עוד אחד, והוא איל שני שמחייב ראב"ש. לא יודעים כלום עליו.)
טבילה- טובל בפעם ראשון שנכנס, כמו שבכל יום טובל אז.
לובש בגדי זהב לעבוד.
עושה כל סדר 1. במקום אחר, בארנו את הסדר.
[fn:1]אולי עשה 6, 7- 13, 15, 16.
טובל בכל זמן שמשנה בגדים.
לובש בגדי בוץ לכנס לפנים.
מתוודה על 3 לעצמו.
קובע את שני השעירים (4, 5) על ידי גורלות.
קושר לשונות על שני השעירים.
מתוודה על 3 לכהנים.
שחט 3
וקבל ונתן לכהן.
פנה גחלים, והכניס גחלים עם קטורת היום, ועבד בקה“ק.
נטל דם 3, והזה בקה“ק.
הניח דם 3
על כן.
שחט 4
וקבל.
הזה דם 4
בקה“ק.
הניח דם 4
על כן.
הזה מדם 3
על פרכת.
הזה מדם 4
על פרכת.
נתן דם 4 ו3 ביחד- חולקים תנאים אם יעשה כן.
נתן דם (4 עם 3, או 3 ושוב 4) על קרנות מזבח הפנימי.
הזה על טהרו של מזבח.
שופך את דם (4 עם 3, או 3 ושוב 4) ביסוד של חיצון.
התוודה על 5
(לכל בנ“י)
שולחו.
הוציא אימורי 3 ו4, והוציא שאר 3 ו4 לשרף.
** 5
הגיע
למדבר.
קרא ובאותו שעה נשרף 3 ו4.
טובל.
לובש בגדי זהב.
אולי עשה 7- 13, 14, 15, 16, ואימורים של 3 ו4.
טובל.
לובש בגדי לבן
הוציא כף
טבול.
לובש בגדי זהב
עשה 2.
אולי עשה 6, 7- 13, ו14.
טובל.
לובש בגדי חול.
עכשיו, נבאר, בע"ה, זמנים של 6- 16 ואימורים של 3 ו4.
יש שש עשרה קרבנות, כמו שבארנו.
יש שלש זמנים: עם 1, עם 2, אחר טבילה שלישי (נקרא אותו 1.5)
יש על זה כמה הערות:
1. כמובן, מצאנו כמה דברים שלא מבוארים לפי ר"א של משנה ור"ע של משנה. גמ' מעורר על זה.
2. מצאנו כמה מח' בין ר"א של משנה ור"א של בריי' ובין ר"ע של משנה לר"ע של בריי'.
3. לר"ע של משנה, לא מצאנו דבר בטבילה שלישית. אבל, צריך להיות דבר. אז, לכאו', צריך לומר שאימורים של 3 ו4 הם אז. אבל, לא כל כך משמע כן מגמ', שמקשה שלא נדע מתי הוק' אימורים.
הסדר הוא כמה שכתוב, חוץ מ? יוצאים מן הכלל:
1. מוציא כף ומחתה אחר טבילה רביעית, ולא במקום שכתוב.
המקור לזה הוא שלומ' מהל"מ שצריך חמש טבילות ועשרה קידושין, ובלי זה, לא נמצא.
1. לר"ע, אין הכל נקרב כסדר שנאמר. דורש את זה מקראי אחריני, כמו שבארנו.
2. אימורים של 3 ו4. דורש את זה מ"יעמד חי," או מהיקש לשילוח.
* Footnotes
[fn:1] איני יודע אם זה אחר או קודם תמיד של שחר. לכאו’, הקרבתו צריך להיות אחר תמיד של שחר, שהרי תמיד צריך להיות הראשון. אבל, אולי רק הקטרתו אחר הקטרת תמיד.
[fn:2] גמרא מפרש שעושה את הכל כמה שסדר שכתוב בתורה.
[fn:3] שני שיטת של ר"ע דורשים 6 ו7-13 מ"מלבד עולת," שנאמר גבי אלו, שמשמע שנקרבים עם אותו עולת הבקר.
[fn:4] ראב"ש ור"י סוברים שיש שני כתובים שסותרים זא"ז. חולקים אלעשות אחד, שחוש' שיפשע מחמת זה, או שש, שהוא המרובה, ולא יפשע בעבודת היום.
