* יט.
** גמרא תנן -
קשה למה לא הקשה ממה שאין אומרים שכל סוכה כשרה כיון שיש לה סכך, וא"צ דפנות כיון שסכך יורד. ותחשב.
* יט:
** רש"י יחידאה -
חכמים שבדורו- נמצא פירוש של "חכמים.”
* כא.
** רש"י והרי דלת -
אין דרך אהל- יש לדון מה לנו בזה. ותחשב.
* כא:
** גמרא מטה -
קשה, שנעשה בידי אדם. אולי הוא מפני שאינו לגבה או מפני שהוא עראי. ותחשב. ועיין ברש"י.
** רש"י ויש כמה אגרופים -
קשה, שלכאורה, דן גמרא ברוחב, ולא בקומה.
** על הרועים -
דמרגיל- זה מעניין, וחושב אני שאינו ידוע.
** מלתא -
דבר תורה מדבריו- אף שזה שיחב, יש לומר לזה כיוון. נמצא שכאן לא כוון. ואולי דן באי נ’ שכיוון.
* כב:
** גמרא והתחתונה -
ורבנן חולקים כיון שלא מעמיד.
** רש"י כאן -
בכ"א אמר איך מגלה על חבירו. יש לדון איזה ההכרע, ולמה צריך להיות שניהם. ואולי נקט לקנטרסט. ותחשב.
* כג.
** גמרא דכשרה -
י"ל שמשנה בזה. אולי זהו כוונת אביי.
** דירת עראי -
יש לדון איך תלוי. צריך ביאור, שהרי שלר"ע אינו תלוי ביכולתו לעמוד ממש, ואז נראה לומר שדנים אם נח’ מצוי (כיון שרק באותו מקום מצוי). ואולי צריך מצוי ליבשה לסיבה אחרת. ותחשב.
** בפחות משלשה -
גוז’ מח’ זה או מיירי בזה.
* כד.
** גמרא אלא לדידך -
ולדידך שחיישת למיתה….
** ר"מ חייש
למיתה כיון שחושש למיעוט. למס’ גמרא (לצמד האחר), צריך ביאור איך מפרשים זה.
** רש"י דאוקמה -
ק"ק ל"ל אמר שהנוד עם האוויר היה הדופן.
** אוסרים -
וכש"כ- נראה שהוא מפני שאדם ימות לאחר זמן, ואז כבר קצת עומד למות.
