Edgar Allan Poe is a man who has strongly influenced my life. He was a poet, a literary editor, and a thinker, and the glimpses of him which I got from his writings have had a positive impact on me. His works show a tenacity for truth in a firm logical mind, a mind in which clarity of observation and straightforward thinking are in control, as well as a poet’s soul, a metaphysical dreamlike sense which seemingly pervades his consciousness. These traits- and their fusion- have exerted a great influence upon me.
Poe’s works indicate a clear and unyielding emphasis on logic and truth. One of his great contributions to literature is the genre of the detective story, which began with his C. Auguste Dupin. The notion of a story written expressly about the search for and discovery of hidden information reveals a mind uniquely suited to uncovering such information. Indeed, Poe’s second story in this genre, The Mystery of Marie Roget, was his attempt to solve a real life mystery[fn:1], further indicating his care for truth and his talents in seeking it.
Poe’s stated methodology also reveals his affinity for clear thought. In reviewing works which he deems unworthy, he consistently stresses those elements necessary for proper poetry or prose, detailing each. He often clarifies terms- terms such as “fancy,” “imagination,” and “poetry”- to gain a better understanding of the concepts implied. After doing so, he typically proceeds to break down the writing process to its units- to what rhyme is, and why it matters, to what originality is and why it matters, and other points of this sort. Detailing such a process indicates a thoughtfulness, indicates a mind suited to sober reflection and logical thought. In fact, the great poet and critic James Russel Lowell wrote about him that “his criticisms are distinguished for scientific precision and coherence of logic. They have the exactness, and at the same time, the coldness of mathematical demonstrations.”[fn:2]
Another indication of Poe’s clarity of thought is found in his Marginalia. His marginalia were- as the name indicates- small notes, supposed to have been jotted down on the sides of his pages. These consistently contain pointed acerbic remarks about little lapses of logic found in others’ writings. That Poe jotted down logical inconsistencies shows how much proper thinking mattered to him.
This quest for truth and love for logical thought is something that has influenced me greatly. Aside from simply learning processes of thought, I also learned the value of clear thought. A well-executed logical argument- an argument which strives for truth and clarity- causes, in its reader, a sense of delight at just how much sense it makes. I have often experienced this delight while reading Poe’s writing; and it is this delight which leads me to pursue similarly coherent reasoning. Thus, Poe influenced me to appreciate and strive for intellectual excellence.
Poe’s work also shows another quality, a quality somewhat more vague than his aforementioned logic. His writing tends to contain something of the metaphysical, something of the mystical, something that appeals to the soul, not to the mind. He has the capacity to impact the reader in the same way that a dreamy tune can lull a listener to any sort of vague feeling. Thus, he recognizes the power of the soul, of non-rational processes.
Poe’s fusion of the two- of the strict and straight knowledge with the vague dreaminess- is another influence on me. In Judaism, we are often called upon to harmonize the body, together with its probing rational mind, and the soul, with its spiritual sensing. Experiencing the harmony that Poe is able to create from these two elements helps me with this process.
Thus, through Poe’s clear thinking, and through Poe’s esteem for truth, my own thinking has grown a little bit clearer, my own esteem for truth has climbed a little bit higher. Through Poe’s fusion of these qualities with a dreamlike appeal to the soul, the relationship between my rational side and my spiritual side became a little bit stronger, a little bit more refined, and a little bit more sensitive. In this way, Edgar Allan Poe, through his writing, has been an influence upon me.
* Footnotes
[fn:1] See note on beginning of most publications of this story; it can be found on page 506 in the LOA edition. Some notes were written by Poe, while others were written by Griswold.
[fn:2] See ”Edgar Allan Poe“ by Lowell, printed in the beginning of The Raven Edition of the works of Edgar Allan Poe.
