Over the years, my Torah learning has formed the bulk of my studies. As it grows, I find that it does not push other subjects to the side; on the contrary, it provides a framework for understanding everything else I learn. In particular, it has had a great impact on the history I have learned. It provides a different backstory- a different set of cause and effect- to the simple facts of history, and it provides me with a more personal relationship with the times and people mentioned in my historical studies.
One of the most important facets of a proper understanding of history is the causes and effects of various historical events. It is because of this aspect that history is still taught; it is not comprised merely of aging irrelevant facts but of patterns of causation which are relevant indeed. The famed Roman statesman Cicero wrote: ”The causes of events are ever more interesting than the events themselves.“[fn:1] History is, thus, not the study of the past, but the study of the future through the lens of the past; and that lens is forged through a thorough understanding of the causes and effects of the past.
My religious studies have greatly impacted my understanding of history in this regard. My learning has caused me to recognize and internalize that the cause is not to be found in the mere physical circumstances of nature; the cause is Hashem. Thus, what a historian would call cause and effect is not, in truth, cause and effect at all, but rather a mere mechanism- it is not the “why” but the “how.” This, obviously, has a huge effect on my studies of the past. The causes and effects of events, which are the crux of the study, are, in this way, entirely different than what they would seem to be without my religious studies.
The study of the First World War is a good example of the aforementioned shift. Full books have been written to explain the precise causes of the war- the tense “powder keg’ of Europe, the nationalist energy that stormed the continent. Based on these, different lessons are able to be learned, each a means of preventing a reoccurrence of these causes and an ensuing war. Learning Torah, though, gives me a different view. The war was caused by Hashem’s will. There are, then, very different lessons to be learned, for it is a very different cause which must be prevented from reoccurrence. For example, one may claim that the world war was a punishment for the rapid assimilation of European Jewry immediately before the war. Then, the way to avoid a war would not be by preventing nationalism but assimilation In this example, thus, we see that a study of the past which is rooted in a study of the Torah leads to a different conclusion than a study not rooted in Torah.
Another way in which my religious studies have impacted my study of the past is in my relationship to past people and events. It is often difficult to relate to historical figures; they lived in a world years before our own, in a world with customs and assumptions which greatly differed from ours, and this causes us to view them as notions, as facts, and not as real people and real occurences. This is a deterrent to the serious study of history; our lack of connection with the people and times of the past cause a certain lack of care, a certain lack of passion about the subject material. This missing passion can have negative consequences, as it is much easier to invest effort and energy into something for which one has passion.
My Torah study has led me to a real relationship with the past. Because of my learning, many historical figures are no longer foreigners to me. People like Ravina and Rav Ashi, people like Rashi and Rabbeinu Tam, are my teachers and, in a sense, friends. Together, we’ve learned Mishnayos and together we’ve learned Gemara; and, because of that, they and their contemporaries are real people to me, and I feel deeply connected to them. As an extension, their times and their places are connected and relatable to me, as well, for they are the times and places of my friends. This feeling, this relation, is able to cause that passion which is often missing in the study of past events.
In addition, I believe that relating past occurences and people to ourselves provides a depth of understanding. To persist in thinking of the past as a foggy notion, and of its actors as statistics, is to deny their nature- for they were real events and they were real people. Obviously, such an error hampers clear thought about the past. Thus, the relationship to these figures and events that my Torah study affords me is a benefit in the clarity of my picture of these people, and, in being so, is a cause for further clarity in the study of history.
Thus, my religious studies have greatly impacted the way I learn the past. Because of the Torah that I have learned, my notion of cause and effect, one of the cornerstones of any serious study of history, has been largely altered. In addition, my learning has given me a connection to many historical times and figures, greatly enhancing my study of them. Hence, my inclination to learn history, as well as the points gleaned from this study, has a strong relationship to my study of Torah.
* Footnotes
[fn:1] Epistolae ad atticum, Book IX, Section 5
