Over the years, my religious learning has formed the bulk of my studies. As it grows, I find that it does not push other subjects to the side; on the contrary, it provides a framework for understanding everything I learn. In particular, the values it has taught me have had a great impact on the history I have learned. It provides a different backstory- a different set of cause and effect- to the simple facts of history, and it provides me with a more personal involvement in the story that history tells.
One of the most important facets of a proper understanding of history is the causes and effects of various historical events. It is because of this that history is still taught; it is not comprised of aging irrelevant facts but patterns of causation which are relevant indeed. In this vein, the Roman statesman Cicero wrote: “The causes of events are ever more interesting than the events themselves.”[fn:1] History is, thus, not the study of the past, but the study of the future through the lens of the past; and that lens is forged through a thorough understanding of the causes and effects of the past.
My religious values have greatly impacted my understanding of history in this regard. I recognize that the cause of every event is not to be found in the mere physical circumstances of nature; the cause is Hashem. Thus, what a historian would call cause and effect is not, in truth, cause and effect at all, but rather a mere mechanism- it is not the “why” but the “how.” This, obviously, has a huge effect on my studies of the past. The causes and effects of events, which are the crux of the study, are, in this way, entirely different than what they would seem to be without my religious beliefs.
The study of the First World War is a good example of this shift. Many books have been written to explain the causes of the war- the “powder keg’ of Europe and the nationalist energy that stormed the continent. Based on these, lessons can be learned, each a means of preventing a recurrence of these causes and an ensuing war. The Torah, though, gives a different view: the war was caused by Hashem. There are, then, very different lessons to be learned, for it is a very different cause which must be prevented. For example, one may claim that the war was a punishment for the rapid assimilation of European Jewry- then, the way to avoid a war would be by preventing assimilation, not nationalism. Thus, a study of the past which is rooted in Torah values leads to a different conclusion than a study not rooted in Torah.
My values have also made me a more sympathetic learner. In almost every historical narrative, my morals point to a “right side” and “wrong side” of history. This causes me to associate with one side, which adds passion to this study. That passion is an asset to a serious study of the past, as it is far easier to invest effort and energy into something for which one cares. Thus, a set of values turns history into a far more relevant and personal story, which aids the study of history.
The collapse of the Roman empire is a topic which highlights this point. To me, there was a definite moral side. The Romans, flawed as they may have been, stood for civilization and knowledge, certainly a moral value, while the Germanic tribes stood for barbaric cruelty. Reading about this era, I find myself hoping for a Roman victory. Since I care about the topic, I can more readily delve into it, and can, hopefully, understand it more deeply.
Thus, my religious values have greatly impacted the way I learn the past. Because of my belief in Hashem, my notion of cause and effect, one of the cornerstones of any serious study of history, has been largely altered. In addition, my values have given me a passion, through causing me to sympathize with one side of a historical struggle. Hence, my inclination to learn history, as well as the points gleaned from this study, has a strong relationship to my religion.
* Footnotes
[fn:1] Epistolae ad atticum, Book IX, Section 5
