* Marginalia
-Old friends aren’t measured in years but in times they’ve shared.
- I walk everywhere I go, so I don’t waste anytime getting there or coming back. The whole journey, I am already there.
- I find a lot of comfort in the reflection that the avos did not have, by any objective standards, happy lives. Once, when I desperately wanted something and daily prayed for it, the thought flashed into my head- It’s not fair! Whenever anyone in the Torah needed anything, Hashem would constantly promise it to them! A second later, I realized that this is not at all true, and that their lives were filled with bitter hard sad moments.
In a similar vein, I really appreciate the lyrics describing Dovid HaMelech in Baruch Levine’s The Power of a Nigun; it paints him in such a human light. Perhaps the strength of Tehillim lies in how touchingly and rawly human it is.
- A good friend is a friend you don’t talk to more than once a year- and yet you feel he’s your friend.
-A few necessary new words:
Paradam[fn:1] (PAH-ruh-dam)-a word used (almost) exclusively in conjunction with another word.
Parmedon (PAHR-mih-don)-the word with which a paradam is used.
Thus, in the phrase “to coin a phrase,” “to coin” would be a paramad and “a phrase” would be its parmedon. (Alternatively, “a phrase” would be a parmedon, and “to coin” would be its paradam.)
If both words are paradams of each other, they would be “paradam pairs.”[fn:2]
- “Saints are presumed guilty until proven innocent,” wrote George Orwell. Perhaps it would be more accurate to say that “saints are presumed guilty until proven guilty.”
- Someone once quoted to this author-with, it must be noted, a great deal of confusion-that “no good deed goes unpunished.” All actions, possessing a multitude of effects, are almost certain to cause both good and bad effects. An action done with intent to cause good will, if successful, produce more and more important good effects. The veracity of the above statement stems from the dissonance of the two definitions of good assumed; the “good” of the “good deed” is a moral and spiritual good, while the “good” of which the referenced punishment is a negation is a physical good. Thus, the intent will not cause a predominance of good effects of the second definition, but of the first; whereas an action done for the sake of physical good will cause that predominance. Thus, one who acts for the good of the first definition will appear punished.
- I have heard many argue that a simple life, free from riches, is the happiest way of life. These people also assert that the wicked are repaid in this world in the form of riches. These two statements seem contradictory. (Perhaps they assume that reward is not given in the form of true good, but as what the receiver perceives to be good.)
- It is remarkable just how spectacularly-and speedily-Joe Biden has failed. In a matter of months, he created a health crisis (by encouraging vaccine hesitation and reducing testing), immigration (the southern border), foreign policy (the Middle East, Afghanistan, and Ukraine), and economics (low unemployment due to government handouts, inflation, gas prices). Serves him right!
- There is a famous dillemma concerning free will: if very action has a cause- and things do, indeed, seem to have causes- then every choice must have had a cause. If this course is followed down to it’s logical beginning, every action is preordained and must happen. Gerald Schroeder answer, based on quantum physics, that there the notion of cause and effect is not, necessarily, true.
It is worthwhile to point out that, while this addresses the free will problem satisfactorily, it removes one of the basic proofs to the idea of a Creator- namely, the “First Cause” proof. Nothing can be indicated from the need for a prime cause if it has been admitted that there is no need for a cause at all.
- “He has influence and affluence.” This is a good quote.
- Gus The Balebus; Mattis Balebatish
- “It’s a step in the right direction, but I should be taking the bus.”
- The author was once unable to locate a piece of Gemara and was forced to ask around. Seeking in vain  for someone to ask, he remarked that it was a case of “where does Rechnitz go when he needs money?”
A girl named Green - who’d ever think
That she would always dress in pink?
You still look good, but all the same,
Perhaps I’d better change your name.
I know you make some tasty nosh
Like brownies in a hamentosh.
Very sweet and sugary-
But snapple must be sugar-free?
At every chance, you’ll always talk,
Of eli, and you will not stop;
Don’t even try, you simply can’t,
‘Cause you’re the world’s greatest aunt.
Our thirty dates have been such fun,
And I can't wait for what’s to come.
I’m still as anxious as can be,
But still- Oh! Won’t you marry me!
Will you join me as my wife
And, together, forge a life,
build a warm and loving home,
raise a family of our own;
be a team through everything,
The griefs and joys that life may bring?
And, trust me, we’ll have fun as well;
So will you marry me yael?
- It seems that Occam’s Razor is often misunderstood. It is used to prove the lack of “empty time”- time in which nothing occurs, which could, it is argued, periodically occur without any apprehension. Occam’s Razor does not state that that which is not indicated is assumed untrue, but that it is not assumed true` the point of the rule is that each assumption lessens probability, and so an explanation requiring the least assumptions is, on average, more accurate.
It is also interesting to note that Occam’s Razor would assume the existence of a G-d, for that would be the simplest explanation for all, that would be an explanation which requires but one assumption.
- Probably, sheep were picked as an animal to be counted in bed because of their rhyme with “sleep.”
- Shaar Hatorah’s slogan should be: “Shaar Hatorah- the yeshiva that fulfills ‘maichaverai yoser mrabai.”’
- Probably, most people manage to stay up during second seder because they’re so bothered by their questions, and can’t manage to fall asleep. The ones who do fall asleep are just smart enough to have answered all their questions and understood the whole topic. I think this explains why I generally wind up with chavrusos who sleep through most of first seder.
This is a joke.
- A few expressions:
1. Let‛s drop the chicken- Let‛s go!
2. Similarly, “let loose the (or “this” or “that”) lion,” or “let the lion loose” is a nice phrase which can mean “let’s go,” or, really, anything.[fn:3]
3. Run around the race car- This refers to someone who strenuously pushes to achieve that which can be much more easily achieved through a vastly simpler method.
4. Go peel a gizzard/ I‛ll peel your gizzard/
5. Skewer a porpoise.
6. I‛ll bust your drainpipes.
7. Go conjugate a verb.
8. Go dismember an octopus/ Go dismember a porcupine.[fn:4]
9. … a bamboozled baboon.
10. Grizmi (גריזמי)- this is a word for ”thingie.“
- A bad yeshivish joke:
What should one do if he has a Nida and an Avoda Zara on front of him? Learn them!
- I started a trend of writing signs[fn:5] in poetry on the bulletin board. This led to some signs scanned in my Notes section.
These signs led to some spirited poetry.
An author of some of this rubbish, leaving his Gemara on my table too often, recieved from me this following poem:
Take your Talmud; take it quick-
All this clutter makes me sick.
Take it now; take it fast-
This situation cannot last.
If to this poem you say, No!"
Who knows just where your book may go...
Someone found a tie, which prompted me to write:
As I was walking on the ground,
I heard a queit rustling sound.
"Oh my!" said I,
"I spy a tie,"
for that, indeed, was what I'd found.
Similarly, I found a pencil and wrote:
'Twas a pencil that I found,
sprawled along the stony ground.
If you believe you own this stick,
come and claim it really quick.
In promoting the נכפל במאה, I wrote:
Why wate your time
on silly signs?!
Save them for later;
preorder my sefer!
It's quite geshmak
that pshat is not...
So preorder fast
while suppli'es still last.
For a bulletin board bereft of verses, I composed:
'Tis a burning shame, indeed
-this lack of rhyming signs to read.
Methinks I shall dash off a line,
to give to thee a pleasant time.
And, if, perchance, thou doth not find
sweet solace in my silly rhymes
feel free to rip apart this letter
provided you can write one better.
A colleague suggested putting up a sign about Rav Shalom Spitz's shiur as a parody to a Marvelos Midos Machine song. I suggested replacing:
"I'm a hippopotamus,
from my top to my bottomus..."
with:
"I'm a Rabbi Shalom Spitz,
from my top to my bottomitz...."
These poems brought forth a plentitude of pretty poor poetry; in response, I wrote:
Poetry means rhythmic line,
not just random words that rhyme.
While I am pleased by all your signs,
take the time to learn from mine.
On  Y. Juni’s wedding invitation, I suggested:
I did not give chosson candy[fn:6],
but it would be really dandy
if to my wedding you would come-
I want to dance with everyone!
P.S.
If this sign is really loony,
do not blame Yechezkel Juni.
This led to an absolute multitude of petry, as well as a fued over whether poetry should be written on the bulletin board. Some of what I wrote was scanned; the rest is:
I find these rhymes
quite geshmak
so stop your signs;
stop your hock.
(I write no extravaganza;
I stick to my single stanza)
P.S.
To this poem don't respond-
this is lasting far too long
the pen is might'ier than the sword
but such a battle's too absurd.
And:
Isnt the bulletin board looking bare
with nothing to study and nowhere to stare?
some charts for mishnayos and one lonely psak
that sort of and maybe was uttered by Grak
Countrymen, patriots, pick up your pens!
Let us adorn it with doozies again!
Upon postponement of Rav kalman’s morning shiur, I wrote:
Bechoros will just have to wait;
morning shiur is one day late.
There will be no sleepy slouch
on Rav Kalman’s fluffy couch.
You won’t rest your feetsalach
on his fancy footrest zach.
On the plus side, though, you’ve scored
a poem for the bul’tin board.
- excerpted from “I’m so cool ‘cuz I’ve been in Grak’s office”
Attached to a sign on safe drinking, I wrote:
If you don’t want a hangover
on shushan purim morning,
listen to this little poem,
and hearken to my warning.
It isn’t very difficult;
it’s simpler than you’d think:
if you don’t want a hangover,
then simply do not drink!
(If you’re feeling worried
you might get an aveirah
I think you can fulfill your mitzva
on nechpal b’meah!)
Another time that morning shiur was pushed off to Tuesday morning, I wrote on Monday:
No more suff’ring
no more sorrow
R’ Kalman’s giving
shiur tomorrow
- Be there when the door leisurely swings open at 7:18
On Purim, I wrote the following poem in someone’s mishloach manos:
It seems it has become quite hot
to send a short poetic thought
about your feelings on the day,
with some puns along the way.
But I’m a bachur, sad to say,
so I can’t write a rhyme.
After a sign announcing R’ Shalom’s shiur was ripped down, I wrote:
We’re sorry that this week we don’t have a sign;
but there will be shiur at the regular time.
On the Sephardi Minyan campaign, I jokingly threatened:
Send us money, Maskaltzoni,
Or we’ll send you Chazzan  Cronie.
Won’t you love a lovely evening
Listening to Mr. Kriegsman?
On a boring bulletin board, I wrote:
Nothing on this board today;
If I were you, I’d look away.
(But if you’re bored, come over later,
and preorder my new sefer.)
On request of R.Y.S., I wrote:
There’s a certain delight in the thought of[fn:7] the day
when your bones decompose and your organs decay[fn:8]
Your skeleton smirks with a hideous grin;
you have worms for a body and shrouds for a skin.
Once you were proud of your looks and your hair;
and so are the ravens- they pick your bones bare.
You’ll be missing an elbow, two toes, and your head;
you’ll be goner than gone; you’ll be deader than dead[fn:9]
for dust shall ye be- for from dust have ye come;
every “slaughter” has “laughter”; each “funeral” “fun.”[fn:10]
The following is a subtle warning about a local “cult leader”:
Here’s some simple safety rules which everyone should know
we all must try to follow them wherever we may go.
Do not walk around at night[fn:11]- by all means, not alone
from strangers don’t take candy canes or even ice cream cones[fn:12].
Cults are very dangerous[fn:13], so please stay far away-
do not let them lecture you[fn:14] at night or in the day.
There’s Someone always watching us- Ori Viyishi[fn:15]
But still we must use utmost care to act responsibly.
One fish two fish red fish blue fish
tall fish short fish old fish new fish.
Have you ever seen the fish
called the fearsome Shalom Spitz?
hIs fangs are sharp, his eyes are keen;
he always yells, “Bentzeeyn, Bentzeeyn!”
We brought him home once as a pet.
We do not feel quite better yet.
Here’s a fish our father found.
He’s very old and very round.
He has a head that’s full of hair
(we try our utmost not to stare).
He sits and snoozzes on the ground,
and twirls his glasses round and round.
We find his presence very calming;
I think that we shall call him Kalman.
Oh me! Oh my! Egad! Oh no!
I think this pet will have to go!
Good grief! Gevalt! Oy vey! Oh dear!
I think there won’t be morning shiur![fn:16]
Rav Shalom will,
if he's not ill,
give shiur this sunday evening
he might not come
(he's 0 for 1);
the prospects are intriguing.
Tune in to SHIURWATCH- Weekend Edition, and hear our derher.
Real time updates on this and other shiurim, because ”Shiurwatch never stops!“
Be the 500th listener and receive a free signed copy of נכפל במאה with a small preorder sum!
”Keep your antennas up“- מורינו ראש הישיבה שליט“א
Brought to you by CLERRED DERHERS, a subsidiary of SHIURWATCH.
chevra, wont you take a look
for a ritva by rabbi kook?
If you search and find your goal,
return it soon to chaim yo'l.
the continued adventures of shalom j. spitz,
returning this sunday if weather permits.
filled with further excitement in horayos land
and packed with delight- but no microphone stand.
there's a vad on chavrusos, today at three thirty
which all of third year must attend
so whether you're sleepy or sweaty or dirty,
you better be ready by then.
we're sure you'll enjoy every suffering yoy…
Yes, I’ve found what you’ve lost- it’s a USB dongle;
and it’s black and it’s short and it’s sort of oblongal
(If this poem won’t work, well then, maybe a song’ll
songs won’t wake Azi, but maybe a gong’ll.)
If you own the USB dongle, please come over to ש"י הכהן.
If you like this poem, please come over to ש"י הכהן (and preorder).
If you hated this poem, please come over to Yeshaya Deitel.
I have mareh mrkomos
to know just what to do
and if you really want them,
I’ll give them right to you.
if you want mareh mekomos,
I’ll tell you what to do.
Just wander right on over
and I’ii give them to you.
oh my oh me
a usb
cable on the floor
that's what i found
right on the ground
beneath the old dorm door
i would not mind
if i would find
the owner of this cord
or else it will,
like my found bill,
be watched for evermore.
- exactly who you think.
well i come from shar hatorah with a laptop on my knee
and i heard there won't be morning shiur, o won't you cry for me
oh rav kalman give morning shiur to me
for ill sit down on your sofa with my laptop on my knee
well the barbecue, it lasted long, to honor father's day
then zelig stole his ipad's case, so no shiur will he say
oh rav kalman...
This poem indicates a name
known to greatness, not to fame.
Do you know me? Ponder hard.
Let me tell you: I’m the bard
What are you doing,
you black hatted bum
your lomdus is wacky
your svaros are dumb
your knowledge is tiny
your feelings are fake
go learn some real learning
for dear heaven’s sake!
Rav sssss is a magid shiur
rav sssss has outrageous hair
his hair reminds me of a bear
his hair is simply everywhere.
long ago you had a friend
of brilliant mind and clever pen
think it through, now- think again
can you think who i intend?
as you sit and read this note
which months ago i fondly wrote
close your your eyes and try to see
that i'm with you and you're with me
hey there buddy (reader?) how are you
feeling happy? feeling blue?
well, i'm a note, that's all i am
so i don't really give a da…
listen to this monologue
on a watch that's analog-
which, frankly, is quite double faced,
this watch not in its proper place,
but stretched out, rather, on a table
so swing by, if you are able,
and, in swinging, drop a hand,
to clutch it by its rubber band,
and take it out, if it is yours
- thus this monologue adjourns
whats up with your rhythm
its not getting better
so practice your poems
and practice your letters
(this is trochaic)
what's up with your rhythm
it is not getting better
so please work on your poems
and please work on your letters
(dactyl)
if you really want to find
the current mareh makom sign,
do not fear to come to me,
the guy who took them to his seat.
whoever leaves their cellphone
ringing every morning-
we hear it in beis medrash,
so listen to my warning:
if you don't get your cellphone
out of this here building,
I'll bash it when it's buzzing
and smash it when it's ringing.
Walking slowly up this street,
I noticed[fn:17] something by my feet.
Looking down, what did I see?
I saw a little metal key![fn:18]
מבית מדרש יצאתי
מפתח פה מצאתי
צריך להיות שמח
אם שלך המפתח
בגלל שאני אחזיר אותו לך אם תתקשר אלי
lying there, alone, forsaken,
waiting merely to be taken-
a short and small and battered cable,
waiting there for someone able,
someone willing, someone knowing,
someone who could write this poem.
Chevra, won’t you take the time
to read this rather little sign.
(I think it most unusual-
a sign with rhymes so beautiful.)
read it quickly; read it through,
do what it tells you to do.
This is a really long leonine line. It’s middle and ending together do rhyme.
It’s really quite easy to write such a verse. This won’t be my last and it wasn’t my first.
Erev shabbos shower:
how could anybody shower
during such a busy hour?
Moshe Yess style;
Here’s a little happy tune;
Here’s a little song.
Moshiach’s coming very soon-
it won’t take too long.
The beish hamikdash will be built;
the galus will be done.
And all the prophecies fulfilled
when moshiach comes.
- Sometimes, it’s hard to remember that a long time[fn:19] is made up of days, one after the other.
Bob is in yeshivas mir.
Bob is in rav asher’s shiur.
Bob is shtark and lots of fun;
Bob is friends with everyone.
But every day at twelve- fourteen,
for some reason, Bob is mean.
He pushes in his haste to hearken
every kneitch in every shiur.
He stumbles over someoine’s feet,
and runs to grab a better seat.
He shoves his neighbor as he flies,
but bob does not apologize;
he’s focused still on hearin g shiur,
but that was not to be, we fear.
Something happened one fine day
that made poor Bob stay far away.
In his rush to get to shiur,
a tzaddik with a flowing beard
was pushed and knocked by our friend Bob,
who, turning, gave a little sob,
as he watched rav Asher fall,
and bounce and smash into the wall.
Bob no longer pushes through,
and WON’T YOU PLEASE STOP PUSHING TOO!!!
I sit down at the table on a comfy pillowed seat
on the plush new carpet floor and right under the heat.
I’m learning bava kama; the gemara’s counting sheep;
what else am I supposed to do, if not to fall asleep?!
Scene- child throws clock out of window; Why? To see time fly; well, the clock no ,onger has the time; it flew away.
I really did not want at all
To pin this poem on the wall…
forget about the next- to- mir;
all you want is cheaper here!
Our prices simply can’t be beat,
so come to six hanaggar street.
Did you ever wonder what constitues a wall?
Or think about the gid hanasheh or nikvas harayah
then come to sixhanaggar, for they have got it all,
except for just one sefer, and that;s nechpal bemeah.
I try to like yeshiva’s lunch, but I confess I’m beaten
when I see what’s on the plate right after I have eaten.
It is far easier to convince people of irrational ideas than of rational ones.
The difference between a high class man and a low class man is whether he eats what he picks out of his nose or not.
I’ve lost my sfardi siddur; won’t you help me please,
to search the books that litter every bench one sees?
If you find my siddur, write so on this sigh.
(It would be a hiddur if you wrote[fn:20] in rhyme.)
corny yeshivish song:
for a couple of years now,
there’s something I do,
a substance that I’m hooked on,
a drug that I use.
When I’m bored of a lifestyle
which makes me feel weary
or tired of living
and worn- out and weary,
I turn to my substance,
and get myself high,
‘cause lulei totrasecha
sha’ashu’ai.
I treat all humans equal. But some people aren’t really so human.
This poem is boring; this poem is bland;
and poems like this one should really be banned.
But they’ll force you to read it ‘till you understand
that poems most boring are poems most grand.
Why do so many prisoners find religion? Captive audience.
If I were in charge of the patchkevielach, I wouldn’t put tham on the street, where everyone has something else to do- I’d put them in the bathrooms, where everyone would read them.
My favorite comedian is the guy who named rutabagas.
Ifi had a sense of pitch like him, I’d never sing in public. Then again, if I had a sense of pitch like him, I probably wouldn’t know that I had a sense of pitch like him.
Let nothing be muchrach, but always be aware of what’s mistaber.[fn:21]
how can you expect of me to wake you every day?!
You’re twenty-one, you’re far from dumb- find another way!
If it would be but once per day, it would not be so bad,
but when it happens seven times, it starts to get me mad!
You know what time first seder starts- you know what time to come-
so don’t roll into seder late, and DO NOT BE A BUM!
If you think your phone will ring,
kindly do not bring it in.
turn your cellphone’s ringer down
so it does not make a sound.
Munching ‘round an apple core
is really something I adore.
I love to feel its juicy crunch,
as I eat my daily brunch.
And, so, I keep right by my seat,
six or seven fruits to eat.
Some might think it quite obscene,
to learn while chewig tangerines,
but I will have to disagree
and crunch and munch and eat my pri.
You’re learning in beis medrash now, and this is nt the place
to bite into an apple, with juice dripping down your face.
Your seat is strewn with apple cores; your shtender’s wet with juice.
Seder’s simply not the time to eat your seven fruits!
The pen was small; the pen was black;
the pen was lying on its back.
By beis shalom’s entrance door-
lying there, right on the floor.
I picked it up and penned this poem;
perhaps the pen will find its home.
Help the pen find home! If it is yours, report its disappearance to me at 055-323-5711. while you’re at it, don’t forget to ask about נכפל במאה.
Aphorists are usually quite good at writing until they realize they’re aphorists.
Advice on curing a cold: you can’t.
Never trust a man with too many opinions.
It’s easy to spot a Mirdo. Yo can smell ‘em a mile away. Literally.
I found these on my shtender;
watch you papers better!
If this happens latter,
you will not get a letter!
Remarkably fast, they’ll be thrown in the trash-
and there they will rot, if you like it or not!
So if you want your papers,
please try to remember-
‘cause if this happens later,
you will not get a letter!
- I left this donut in your room-
won’t you please feel better soon?
I want to see you smile and beam,
and see your fac (with your face?) e all smeared in cream.[fn:22]
- A great voicemail would be: ”hi! You’ve reached the person you were trying to reach, unless you’ve dialled the wrong number. Presumably, you had a reason for calling. Please state it, after the tone.“
-A little coin fell to the ground,
beneath a bench so big and brown,
and sat there, waiting to be found.
I spied the little coin of gold,
this little coin which slowly rolled
beneath the bench so big and bold.
You know to whom this coin belongs?!
Well, come to me- come right along,
and find out if you’re right or wrong!
Please contact us at our toll- free hotline (055-323-5711(, at any hour of any day.
Recieve a free copy of נכפל במאה with a five dollar contribution to the נכפל במאה fund, for the purchase of נכפל במאהs to recipients just like you!
- A scowling monster[fn:23] four feet tall,
standing in my way`
standing solid as a wall,
and yelling, ”Go away!“[fn:24]
- you little namby pamby brat-
any fool can rhyme like that.
To write as I do takes some skill;
I frankly doubt you ever will
learn to write the way I do,
so na na na na na on you!
I have nothing to write; i have nothing to say;
I have nothing that needs my attention today.
But I'm not the sole person to feel just this way-
the board has been bare for a couple of days!
Preorder: נכפל במאה
When: Now!
Why: All the vertlach you'll love to hate...
Please wish Yeshaya Deitel a Mazel Tov on his big win. Do not mention that he learns with THE PERSON WHO RAN THE WHOLE CONTEST!
Can you tell me- can you please?
what to do when i must sneeze.
I search my right; I search my left;
Alas! of tissues I'm bereft.
Paper towels can't be found,
just machines of awful sound.
Why is it so big an issue
for this place to order tissues!?
P.S. If you have no tissues to wipe your nose on, you can use נכפל במאה instead.
Preorder now and hold in your sneeze until publication!
Tonignt, I fear, there shan't be shiur
I have not got the sugya clear
and, besides, i won't be here
and so there wont be shiur, i fear.
- murmuring of the heart, from The Collected Poems of Shalom J Spitz (The Curzoner Rav)
Tonight, I hope,
Shiur is a nope
Although I'm the GOAT,
my havanah's not dope.
- Anguished cries from a troubled youth, from the collected poems of the curzoner rav.
Preorder the נכפל במאה! Don't scream at me for this sign!
These signs led to some spirited poetry. An author of some of this rubbish, leaving his Gemara on my table too often, recieved from me this following poem:
Take your Talmud; take it quick-
All this clutter makes me sick.
Take it now; take it fast-
This situation cannot last.
If to this poem you say, No1"
Who knows just where your book may go...
Someone found a tie, which prompted me to write:
As I was walking on the ground,
I heard a queit rustling sound.
"Oh my!" said I,
"I spy a tie,"
for that, indeed, was what I'd found.
Similarlay, I found a pencil and wrote:
'Twas a pencil that I found,
sprawled along the stony ground.
If you belieeve you own this stick,
come and claim it really quick.
In promoting the nechpal b'meah, I wrote:
Why wate your time
on silly signs?!
Save them for later;
preorder my sefer!
It's quite geshmak
that pshat is not...
So preorder fast
while suppli'es still last.
If you believe that you have dropped
a paltry sum, the you can stop
your search for it, for I have found
your money crumpled on the ground.
!REDROERP
!WON
Maybe:
If you believe that you have dropped,
a paltry sum- well, then, please stop
your search for it- for I have found
your money, crumpled, on the ground.
Aint gonna speak on saturday
aint gonna speak on saturday
double, double, triple pay?!
I'm retired anyway!
Aint gonna speak on saturday
Shiur's on Sunday night.
- Hey dum diddle dee dum by Big Rav Shalom Goomba
חברה פריאורדר!
beneath a noble time-worn tree
i found a fallen usb
whose drive this is i do not know;
i think it has a siman, though.
- stopping by a tree on a freezing evening by Rabbi Frost
PS
I'm not watching this like my five dollar bill,
lying forlorn in my white binder still.
I have reason to think there was yiush habal,
so come before pesach or don't come at all.
Don’t ever smirk as you pass by a cave,
Because sooner or later you’ll go to the grave
There’ll be a funeral; many will cry,
“What’s going to be!” and, “Oh me!” and, “Oh my!”
All the people will say :”We will always remember;
We’ll never forget you- not now and not ever!”
But time’s always moving; it flows on and on`
And the pressures of life start to sneakily come;
As the worms and the rats, right through your bones, chew
Never comes quickly; they all forgot you
Since you to a cellphone can be compared not
For the phone can be charged- while you will just rot.
Are you uncertain of the whereabouts of your ספרים?
As part of the new Sifrei Codesh Removal And Management (SCRAM) program, your ספר may have been temporarily relocated. In an effort to reduce human-caused clutter on the front center table, numerous ספרים have found a new home.
See the top of the שמות bin for more details.
The continued adventures of Shalom J Spitz,
premiering this sunday, if weather permits-
exciting, suspenseful, and carefully planned:
"The Amazing Adventures in Horayos Land!"
Premieres this sunday, April 30, in a beis medrash near you!
"An intriguing blend of drama and humor... [his] rare erudition lends itself to a scholarly profundity."- SHIURWATCH
Terms and Conditions:
1. Particapants must learn two and a half hours twodays prior to the viewing. 2. Recordings may not be misused; pracy is prohibited under federal law that will be enforced. Fines may exceed ten thousand dollars or twenty three thousand guineas. 3. The Surgeon General does not recommend this viewing to pregnat persons. 4. All participants must provide proof of vaccination, as well as ID. Failure to do sa may result in fines up to five thousand dollars (or nineteen thousand guineas). %/ A full night seder on the thursday night prior to the viewing has been shown to more than double the comprehension of the viewer. As such, all are advised to act accordingly. 6. a thorough perusal of the nechpal bemeah is deemed crusial for a full and proper understanding of te subject material. 7. There shall be no wanton handling of the Wooden Chair.
The נכפל במאה derhers a teif tayneh
he's sayoing a vort that is moiridig feine
But, in order to print it, we must find some gvirim
to sponsor the printing
- A freilechen peerim.
(We have a brilliant vort to share
but alas no cash to spare!)
BY GRASE OV GOD AM HOMELESS ANYTHING WILL HELPS.
A gaze upon the bul'tin board
keaves one feeling quite absorbed
notes with rhythm notes with rhyme
poetry in every sign
but, alas, here comes a letter
that proposes something better
I defy this silly fretter
Professor says to tar and feather
It seems he does not like the sound
of "sprawled along the stony ground."
He does not like- I know not why-
"oh my said i I spy a tie.
If I get kicks for writing these-
then what care I for his unease
I hope that someday not too far
we'll see a rhymed halacha card.
Do you know who began this trend
that you so dearly want to end?
It's time that i remind you it's
none other than Rav Shalom Spitz!
PS
All of this writing is making me weary
poems with too many stanzas are dreary
from now on lets limit these poems and rhymes
to only one stanza, one stanza per sign.
Poetry means rhythmic lines,
not just random words that rhyme
While i am pleased by all your signs,
take the time and learn from mine.
It was little it was blue
it was very far from new
I saw it last a week ago
and where it went i do not know.
'twas a stroll across the sidewalk
on a sunny summer's day
when i spied a single pencil
simply sprawled along my way.
so i stopped and stooped, but, searching,
I spotted not a soul;
thus I scrawled this silly poster
to assist me with my goal.
- He’s quite good looking for such an ugly guy.
- I read a book which claimed inherent bias from a test which determined that people more quickly put pictures of white people in a “good” category and of blacks in a “bad” category than vice versa. There are two problems with this. The first is that these results may be due to an inhibition to calling whites bad, not to calling blacks good. Secondly, it may be that people refrain from holding blacks above whites, but not at all to holding them equal to whites.
Essentially, inherent racism is a nebulous and undisprovable hypothesis, and should be treated as such.
Oh well! What the ….!
Won’t you quell this nasty smell!
It’s very important to always derher
The koach hayom, as we handel and kler,
And mutcher and tayneh, and try to speak out
What the medinah is really about;
We can’t know for sure if it’s treifeh and fre
Or chevlai Moshiach – a shver mutcherai!
But, though we’re mesupak – the sugyah is shver –
Today has chashivus that we can derher.
So, let’s take a moment to think of today
As a day that is special in some special way!
When midnight came, I lay in bed,
Resting for the day ahead.
Then sudden shrieking pierced the night,
I jolted up, turned on the light.
Left my covers, ventured out,
As I heard a strangled shout
I heard a bang, I heard a boom
Coming from the next door room;
I heard a snap, I heard a crash;
I heard a long and drawn-out smash-
Tables piled, armchairs stacked,
A broomstick swinging in attack.
In frightened tones, they told me that
They’d seen a large and nasty rat.
I slammed the door; I shut it tight;
And did not sleep much more that night.
I really did not want at all
To pin this poem on the wall,
But as I came in through the door,
I noticed something on the floor-
Something rusty, something brown,
Something lying on the ground-
‘twas a penny I had found!
After purim, you can find in any coffee room
A plethora of candy which must all be finished soon
Dum dums lollies taffies, cookies chips and cakes
All of it is hefker, and free for you to take
Cause all of it is chametz and all of it must go
But no one really wants it, as everybody knows
This year we’re spreading simchah; you’ll be happy as can be
Cause every single product has been branded OUP.
You might be growing older and you might be growing frail
The nights are getting colder and your mind begins to fail
Your back is stooping shorter and you shuffle all the time
You cannot tell a quarter from a nickel or a dime
Your hair is getting thinner if its still there anymore
You’re fast asleep by dinner and you’re wide awake by four….
Standing strangely, blue and green,
Daring softly to be seen,
Mega flavours, mega size,
So let us stand and sympathize,
With he who lost what he held dear,
And now holds far what he held near.
We’ll watch his happy smiling face
As we return them to their place
I found two boxes of mike and ikes. It would be difficult for me not to find them; they were right in front of my seat. Alas, there are only two people on my table, and they were certainly not brought there by either of us. Hence this poem, a valiant effort to locate the owner of the jelly beans.
Thank you for reading this far. Please accept this little gift: you are entitled to one (1) copy of nechpal bemeah for five (5) dollars. Please purchase through our affiliate links.
Listen up here, you who say
קכא with a ה
It’s a ל- learn to read!
Before you get up there and lead
A crowd of dolts who follow you
And make the same mistakes you do!
So, listen here: if you’re a  bum,
We’d much prefer you do not come.
-Dr. Dikduk
Shlomo was born in a warm loving home
His mother a nurse and his father a lawyer
They taught him he’s never, no never alone
That he is a;ways is watched by hashem
At bedtime at night, since the day of his bris,
His mother sang shma, as she tucked him in softly
She gave him a hug and a warm goodnight kiss
And then softly she started to sing
All wealth is worthless, all pleasures pretend
Our lives have no purpose but yiras hashem
All we accomplish, all we achieve
Without fear of heaven is all make believe.
Shlomo grew older and started to learn
First as a child, and then in mesivta
He loved every moment- he strived and he yearned
To forever be close to hashem
The years passed him by and Shlomo became
An upstanding mentch with a passion for torah
Climbing and growing and reaching each day
The levels he’s hoped to attain.
All wealth is worthless, all pleasures pretend
Our lives have no purpose but yiras hashem
All we accomplish, all we achieve
Without fear of heaven is all make believe.
But money was tight, some choices are hard
And Shlomo was forced to enroll in a college
“I’ll never lose sight and I’ll never stray far”
Was the promise he made to hashem.
Shlomo worked hard and he gave it his all
And he landed a job with a firm in the city
He knew he would make sure he never would fall
That he’d still be an eved hashem
All wealth is worthless, all pleasures pretend
Our lives have no purpose but yiras hashem
All we accomplish, all we achieve
Without fear of heaven is all make believe.
A  bustling day, as he closes the deal
He laughs in delight and in pure satisfaction
Words can’t express the excitement he feels
As he watches his dreams become real
Rolling his sleeves, so his brand new watch shows
He makes his way home, in a mood of elation
And softly he’s whistling a tune as he goes
A song that he distantly knows
All wealth is worthless, all pleasures pretend
Our lives have no purpose but yiras hashem
All we accomplish, all we achieve
Without fear of heaven is all make believe.
How has happened and what have I done
What has this cost me what have I become
All I’ve accomplished, all I’ve achieved
Is hevel havalim, is all make believe.
Miracles song
Sitting on a pile of leaves
His voice breaks down his shoulders heave
He whispers slowly, “Can’t you see
I’m doing all I can (trying very hard) to be
Someone who’s worthy someone who’s pure
Someone who’s holy who’s sanctified for
Leading his nation
In his generation
Sheva yipol tzaddik vikum
* Footnotes
[fn:1] The word comes from the Biblical phrase “pereh adam,” which, as Y.K. pointed out, is a paramad.
[fn:2] This  point comes from Y.K..
[fn:3] It can be used for “We’ll cross that bridge when we get to it.”
[fn:4] This has the undeniable benefit of a mental picture involving painstakingly plucking out porcupine quills, one by one.
[fn:5] The background here is this: Rav Shalom was speaking about pizmonim of Rishonim. When asked why they spent time writing poetry, he responded that the questioner clearly lacked a poetic soul. He was asked whether he had composed any and (jokingly?) said that he had notebooks full of such. He later spoke about the power of writing to make clear that which would have remained “murmurings of the heart”- at which point he exclaimed, “Look! I’ve got a poetic soul-  eh?!”The scanned signs were written immediately after this incident.
[fn:6] He had not been in Yeshiva for years prior.
[fn:7] It would be better to write: There’s a certain delight in recalling the day.”
[fn:8] Could be: organs give way
[fn:9] I really like the cheery Dr. Suess feeling of this line
[fn:10] This line was heard by R.Y.S.
[fn:11] His cult meeting tended to stretch late into the night.
[fn:12] He was famous for his wife’s home made ice cream. The opponents of this cult seized on the ice cream of somewhat symbolic of the cult’s nefarious pull. Cult members were sometimes simply called “ice cream eaters.’
[fn:13] Obviously, thuis references his cult.
[fn:14] He was known to have long intense private conversations by his seat, the “kisei hakavod.’
[fn:15] The leader’s name is Ori. This line reflects the beliefs of the cultists which tended to boorder questionably on heresy.
[fn:16] This was written after I started a trend of announcing canceled shiurim in rhyme. This fit to the suggested title of “one shiur two shiur, red shiur no shiur.”
[fn:17] spotted
[fn:18] A little black metallic key!
[fn:19] forever
[fn:20] write
[fn:21] This fits rav kalman fairly well.
[fn:22] Written on a donut box given to Y.C. after he had been sick for a couple of days (which, for some reason, prmpted some odd reactions, such as a serenade).
[fn:23] woman
[fn:24] This references a time the author was kicked out of a bank by a female manager with quite a confused grasp of the situation at hand.
