Dear Rebbi Shlita,
How can one express in words the gratitude due to a Rebbi so dear to me, to a figure that so truly shaped me into the ben torah I am today! Rebbi’s years of labor and devotion for me truly changed my life, and formed me as a yarei shomayim and talmid chacham. If I had to describe Rebbi in one word, it would be ”Rebbi,“ because Rebbi was, indeed, first and foremost, a Rebbi to me and to countless other privileged talmidim. Rebbi’s loving care for each and every one of his bochurim shone forth in his every act. There was always something special about Rebbi that transcended the mundane, and drew us close to him, allowing us to tap into that special koach. I was truly fortunate to be zoche to a role model like Rebbi in my formative years. It is with trepidation and a profound sense of unworthiness that I write this letter and attempt to convey to Rebbi my deepest thanks for his role in making me into the baal madreiga I have become.
* בברכה להצלחה בתורה ומעשים טובים,
* ר’ ארי שונפלד
