Rainbow connection- kermit the frog
Why are there so many klers about migu
and why do they all hurt my head
migu is simple- he has a neemanus
and beis din believes what he said
he could have said something that made him lose nothing
instead he said something more shver
when will they get it- those kriechers and kvetchers
and when will they stop their dumb klers
who said there such a thing as koach hataana
and that its the pshat in this case
somebody dreamed it up and someone believed it
look what its done to their brains
they think they’re lamdanim talmidei chachamim,
but still they just sit there and kler
they still think that migu is koach hatana,
just cause thats what they derher
all of them swinging their thumbs they think migu’s probably magic
Have you been half asleep in second seder
I have for hours of shiur
he’s been klerring about migu and koach hattana,
I don’t think he has it too clear
I’ve heard it too many times to ignore it
it’s something I’m supposed to derher
someday they’ll find that its silly and pointless
and someday they’ll notice its shver
wharts the name of that song- ernie and bert
yoy yoy yoy yoy yoy
yoy yoy yoy yoy yoy
what oh what is the word…
lydia- rowlf
jackie oh jacki	e say have you met jackie
jacky that funny rebbe
he has hair that’s very crazy
I think his barber’s very lazy
Jackie oh Jackie so crazy and wacky
Jackie’s a little bit weird
He has a long and dishevelled beard
….
have you ever sat down for a shmuze
jackie oh jacke so crazy and wacky
I’m five- robin frog
its shver its shver
rav kalmans shiur is shver
rav kalman never does explain
and no one asks him to
they know darn well its much to shver
so what are you gonna do?
its shver its shver
rav kalmans shiur is shver
he waddles in and sits right down
and waves around his hand
and then says things that are too shver
for us to understand
what do you think- you chap?
Please stop!
You think you have it clear?
Get out of here!
We’ve haven’t finished his first shiur
it’s shver
blackbird- beatles
baby crying in the dead of night
lift your sleepy head and go to him
every night, you are always waiting for that boy to be asleep baby sleep (all through the night maybe once or twice)
side of a hill- paul simon
on the top of a hill, the holy ground weeps
and waters a mosque with its sacred tears
as an arab screams and polishes a gun
its been crying like this for two thousand years
on the top of a hill, there once stood a house
that brought hashem’s shechina down to earth
but many ignored its calls for repentance
and people forgot what a friends love was worth
on the top of a hill, on some day to come
there will be a house that stands again
where yidden will come and stand and pray together
and our nation as one will come and serve hashem
59th street bridge song
speed up you’re learning too slow
there’s so much torah you don’t know
just sitting on the same old blatt
thinking of pshat and moving slowly
da da da dada da da you’re moving slowly
hey there yankel where ya holding
all your time is being stolen
by that blatt you’re scared to leave
just sittin there thinkin, moving slowly
inch by inch
word by word line by line
surely you can find the time
bit by bit you’ll slowly climb
what you never thought you would.
a minute here and a minute there
just a little- don’t be scared-
soon you’ll find that unawares
you’ll have grown the best you could.
Add a bit add a drop
keep on learning do not stop
very soon you’ll know a lot
you’ll be learning everywhere.
a page each day or a little more
it wont be long at all before
you’ll finish shas and so much more
with a minute here and there.
If I had a hammer
If id gone to kollel
id be learning in the morning
id be learning the evening
and whenever I can
id be learning during breakfast
I’d be learning during supper…
once upon a time back in yeshiva
we would sit and learn for hours a day
nowadays those sdarim all just seem a
distant dream I wish I had today
those were the days my friend
we thought they’d never end
and we would learn forever and we’d shteig
we thought we’d never leave
we never could believe[fn:1]
without our learning, how could we survive?
Then one day you left to go to college
it was not very long till I left too
we said we’d still learn all that we could manage
and for a while we made those words come true.
Those were…
But as we’re sitting here I have to wonder
what happened and where did we go so wrong
somehow we slipped away from all that mattered
we couldn’t keep our fire burning strong
Those were…
מי ימלל גבורות הקל אותם מי ימנה
הן בכל דור מקים הגבור וגואל העם
אה (שמע?) בימים ההם בזמם הזה
אה ה' הוא המושיע ופודה....
Overs- Paul Simon
No shtark zmans, no shver zams, there’s no zmans at all but the zmanim chart
Oh Susannah
Well I flew in straight from London
And I landed just today
And I need an Aliyah now
So hagomel I can say
Mister gabbai
Send shlishi down my way
For I flew in now from London
And hagomel I must say
I am no kohen, am no levi,
And I am no sage
But I need to recite hagomel
Call me anyways
Mister gabbai
Send shlishi down my way
For I flew in now from London
And hagomel I must say
My bonnie
Last week as she sat by the table
Last week as she sat eating lunch
A tractor ran over poor Mabel
And all of her bones just went “Crunch!”
Oh dear Oh dear poor Mabel is dead as can be can be
Oh dear Oh dear poor Mabel is dead as can be
Her body is oozing her insides
Her body is missing her head
Her body has lost all its insides
I fear that her body is dead
Oh dear Oh dear poor Mabel is dead as can be can be
Oh dear Oh dear poor Mabel is dead as can be
butterfly
There are times when I look in the mirror to take a close look at my clothes
and the brands that I see are a great pride for me
and the best thing is everyone knows
that I have oodles of cash and buckets and buckets of dough
my money is lovely my money is grand and I make sure that everyone next to me knows
its time to fly to cancun my dear brother in law
show ourselves and the world just how rich we are
we can fly we can soar
we’ll have cash left for more
and the world will look on and applaud.
It’s never too late
I begin to look up at my roof
I discover unmistakeable truths
I’ve got to repair my ceilings, but I’m unsure
Can I really fix the holes and cracks
Can I really pay my property tax
But I hear the rain drops falling on the floor
בגומלן חי בחור אחד נעים
בים ולילה הלך בשידוכים
אשה אחת נשא הוא לכל כספה
היתה רגזנת, והיתה עשירה
כמה היתה שווה
הוא רצה לדעת
אולי מאה שקלים
על זה לא איכפת
אולי מיליון דולר
אף זה לא יספיק לו
אפשר כבר יותר מזה
בטח- צריך לו
טוב לבחור זה- טוב
הכסף יביא לו מזל טוב.
בגומלן חי בחור אחד עשיר
קנה הבית ושוב קנה העיר
בגומלן אף אחד לא האמין
איך זה התעשר כפלי כפליים
תגיד לי אם הוא עשיר
בטח ובטח
עד מתי יישאר לו
יישאר לנצח
האם הוא שמח בו
הכל יודע
האם באמת זכה
אין שום שאלה
טוב לבחור זה- טוב
הכסף יביא לו מזל טוב.
We’ve got a lot of scholars
Got a ton of sages
All throughout the ages
We’ve got a lot of scholars
Avtalyon, Hillel, and shammai,
Reb Yehuda ben tabbai
…
challenges
In Zimbabwe is a freeway that’s paved with cobblestones
And you need more than tires to drive that road
No choddesh tov to wish to you
And no gutt vuch, gott yurr, I want to say
But what it is something true
Made up of these two words I say each day
I just called to say gutt morgen
I just called to show that I’m polite
I just called to say gutt morgen
And I hope I said those two words right.
I’m a loser
I’m a weirdo
And I think that something’s wrong with me
I’m a weirdo
And I make that fact quite plain to see
(Sometimes I daven and stand facing west
I send the mother and eat up the nest
I learn a sugya without all the reid
I live in lakewood without Medicaid
As a camper, I did not play sports
I stood all day in my new Shabbos shorts
And every Sunday, its cholent I eat
And when I shuckel, I’m way out of beat.
When I add things, I count on my toes.
I use my pants leg when I blow my nose.
I eat some galleh when I want a snack.
I wear my tie with the thick part in back.
(I never snap when a dog is around
Instead, I shuffle my feet on the ground
I have a doctor who gives me some pills
I never take them but pay all his bills.)
Let it be
When I find myself in shmoneh esrai
Spacing out and in a haze
Feeling kind of dizzy
In a daze
yesterday
Yesterday,
Chess was such an easy game to play
But now I’ve lost both arms some crazy way
So I cant play
Like yesterday
Suddenly
I have zero arms and zero feet
That car right next to me bumped into me
I clocked his speed
At ninety three
Now he’s almost dead and his head has lost its hair
I said knock and knock no one’s there
Its clear to me.
The worms came crawling one by one hurrah hurrah
The worms came crawling one by one hurrah hurrah
Mabel’s flesh was so much fun
They ate until the meal was done
And the worms came crawling one by one
The worms came crawling two by two hurrah hurrah
The worms came crawling two by two hurrah hurrah
They’d all that they could chew
They ate up all her toenails too
And the worms came crawling two by two
The worms came crawling three by three hurrah hurrah
The worms came crawling three by three hurrah hurrah
They slowly nibbled through her knee
And topped her off with bloody tea
And the worms came crawling three by three
The worms came crawling four by four hurrah hurrah
The worms came crawling four by four hurrah hurrah
They ate her bones and brain and gore
And then came back to eat some more
And the worms came crawling four by four
The worms came crawling five by five hurrah hurrah
The worms came crawling five by five hurrah hurrah
We fear poor mabel’s not alive
We think she did not quite survive
And the worms came crawling five by five
The worms came crawling six by six hurrah hurrah
The worms came crawling six by six hurrah hurrah
They lingered on their final licks
Her bones became as dry as sticks
And the worms came crawling six by six
The worms came crawling seven by seven hurrah hurrah
The worms came crawling seven by seven hurrah hurrah
As mabel gazed straight down from heaven
She saw her flesh stripped down to ribbons
And the worms came crawling seven by seven
The worms came crawling eight by eight hurrah hurrah
The worms came crawling eight by eight hurrah hurrah
They ate and ate and ate and ate
Cause mabel tasted really great
And the worms came crawling eight by eight
The worms came crawling nine by nine hurrah hurrah
The worms came crawling nine by nine hurrah hurrah
With mabels help they’ve wined and dined
Poor mabel tasted truly fine
And the worms came crawling nine by nine
The worms came crawling ten by ten hurrah hurrah
The worms came crawling ten by ten hurrah hurrah
This lovely meal comes to an end
They wish that she could die again
And the worms came crawling ten by ten
up, up, and awake
it’s getting far too late
I’ve been working in the graveyard all the livelong day
I’ve been working in the graveyard on those who’ve passed away
hungry, starving, and exhausted- I need something to eat
hungry, starving, and exhausted- there’s meat right by my feet
dig and dig and dig
dig and dig and dig
I’ll find a bite to eat
dig and dig and dig
dig and dig and dig
a yummy piece of meat.
Unspoken words
I wake up with your stinky feet just inches from my nose
There’s a smell that’s in the air
That’s coming from your toes.
And when I go to sleep, I smell your feet; it makes me want to gag
Have you ever had a thought
Of a shower or a bath?
The dandruff in your hair
that falls and stays on every place you’ve been…
How is it that every song you sing
Always sounds a little bit off key?
When I get older losing my hair
Many years from now
Should I wear a red toupee on my head
Or should I wear a hat instead
And, should I wake up at five every day
And go to sleep at six
Shuffle to the bathroom …
American pie (somewhat cringeworthy, but with a few redeeming points)
A long long time ago
I can still remember
How my learning used to make me smile
And I knew someday I’d become
A Tzadik and talmid chacham
That thought kept me going for a while
But winter zman was long and dreary
when sof zman came I felt so weary
each blatt would leave me so drained
I could stand or bear the strain
I don’t remember what I learned
But I abhorred each grating word
Until one day it all turned clear-
Why why am I here?
I started learning
With a goal in my soul to learn all I could know
What was biting turned exciting and I just love it so
I’m learning and I’m happy and now it starts to become clear
I’m feeling why I’m here
I’d like to live beneath a bridge
With the soft and swampy shoreline as my bed
Without a home, I’m all alone
In my little shelter built beneath a tree
All by myself, with no one else
Just lying there, enjoying being me.
Second chance
They cornered him in a stolen sedan far away from home
With a stolen gun and some stolen cocaine and a stolen phone
They arrested him and threw him in a cold and lonely room
And they said to him, “We doubt you’ll leave too soon.”
But there always is a spark that’s left inside you
Even when you’re feeling empty
And that spark will help you grow and it will guide you
Through the lowest of the low
All the roads where you will go
And bring you home
Polythene Pam
Well, have you seen Gerald the Jew
He’ll do all of your accounting for you.
And he talks with his hands ‘bout his dreams and his plans
You could say he is unlike me and you.
And, have you seen Caleb the black
He’s in the back, with all his weed and his crack
…
And, do you know the Indian raj
He runs a tech support from his garage
Then there’s Faqhir from Pakistan
He’s a dark and a swarthy man
…
Nowhere man
He’s a real yungerman, speaking out things with his hands
Always thinks he understands what pshat is.
Always has a point of view, knows just what he wants to do,
Isn’t he a bit like me and you.
Silver Hammer
Ahmad al Jalip
Living in the Gaza Strip
With fourteen lovely wives
Each of whom would give up their lives for Allah lah lah
Woke up Saturday
Said I’ll kill some Jews today
Packed his stolen gun
And went off searching for someone to murder er er
But as he snuck so silently close, a shot came from behind
Bang bang Ahmed al jalip no longer had a head
Bang bang Ahmed al jalip was certified quite dead
Come gather round seekers wherever you roam
For the age that is coming won’t leave you alone
And the call you’re ignoring may soon bring you home
If your soul to you is worth saving
Then you better be doing your best to atone
For the times will be a’changing
Come lawyers and doctors with heads that are bare
And briefcases bursting with bills to be shared
For the time is too short to just sit down and stare
If you can’t hear the voice that is calling
Then your high-class convictions are in for a scare
For the times will be a’changing
You philosophy majors and champions of thought
You’ll quickly unlearn all the truths you were taught
For soon you’ll be served all the answers you’ve sought
And it’s your choice to hear what they’re saying
So you better start thinking, if you like it or not
For the times will be a’changing.
And don’t keep on stumbling until you can say
That you’ve learned all the road signs that map out the way
Through the twists and the turns of what might and what may
for a single wrong step leaves you sprawling
by the weight of a cost that’s too heavy to pay
For the times will be a’changing
And it’s time you start humming and singing along
And don’t be concerned if you don’t know the song
For no one will know when you’re singing it wrong
And the rhythm is rolling and raging
And the notes that are missing are where you belong
When the times will be a’changing
Side of a Hill
In a small little home in a town in Israel,
A little boy hides in bed, in fright;
He’s scared of the men he watched take his brother,
So he hides in the dark as he cries to sleep each night
In the small little home, the little boy wakes up
To the sound of a cry he’s learned to fear.
He’s tired and wan, he’s sad and he’s frightened
And he’s far far too young at the age of seven years.
And the war rages on near the town in Israel
And terrorist plunder and kill and attack
And the town lies in ruins, its people forgotten
And the little boy waits for his brother to come back.
On Kikar Shabbas, there’s a Hassid with a scowling face
Peeking out beneath his mounted cardboard sign
and a plastic cup for your dimes- don’t you dare decline
yerushalayim’s in my ears and in my eyes
as I roam beneath its blue and cloudless skies
I sigh and meanwhile back
In meah shearim there’s a child who holds his brother’s hand
As he takes him off to cheder today
And, as they walk they skip and dance and play in a lively way
yerushalayim’s in my ears and in my eyes
as I roam beneath its blue and cloudless skies
I sigh and meanwhile back
There’s a group of Jews who’ve come to see the Western wall
I’m watching one who gives the wall a gentle kiss
And he wipes his wet cheeks with his fist he’s never felt like this
Yerushalayim
In moussayaf someone’s waiting for a minyan now
He’s been at it for a very long time
And so far he’s only gotten nine, but he keeps on trying
Yerushalayim
A group of children run and hide inside a playground yard
They have a pack of cigarettes that they stole
And they smoke until the night grows cold they’re only ten years old
Yerushalayim
Unspoken Words
I wake up with your silly songs still stuck inside my head
How I hate it when you sing
As I try to go to bed.
And (/‘cuz) when you sing to me, you’re so off key I cannot tell the song-
If you have to sing so loud,
Do you have to sing so wrong?
The hoarseness in your voice
That raspy edge that makes your high notes crack,
So that every song sounds a little flat.
How is it that every song you sing always sounds a little bit off key?!
And how is it that every song you start (every note you hold) goes on forever?!
How is it that your voice never gives out, even though you shout and shout and shout?
Oh, how I hate, oh, how I hate your singing!
Rabbi rosenshein’s leining
Yerachmiel’s complaining
He’s yelling and banging my knees with his cane
Leiniמg is dragging
My shoulders are saggin
Rabbi licht gives a shout- vnomar amen
Always kriech
Always kriech
Always kriech
Always kriech
I think that I’ll kill him
If he says tehillim
Chelki meayan vharbe he’ll yell
And chas vechalilah
He’ll give himself gelilah
I wish I could tell him to please go to h
Always kriech
Always kriech
Always kriech
Always kriech
boxer
I am just a young boy,
But my story should be told
I have squandered my potential
For the promise of excitement and enraptured thrill
All jokes and lies but a boy sees what he wants to see, and never will realize..
Lie la lie…
When I left my school and way of life, I was just a little boy
in the throes of brand new freedoms
in the late night haze of midnight clubs and potent drugs
moving fast, seeking out the hallowed places where the happy people went
looking for the hang outs where the happy days are spent.
Lie la lie...
I was searching for redemption; I was trying to be free
Of the hindrances and questions
And tedious observances confounding me
All alone,
In a vast and many peopled mass, we wandered on our own…
Lie la lie…
Deep in my heart I do believe
He shall surely come someday
We’ve waited many years
Weve cried so many tears
He shall surely come someday.
We never lost our faith
Through endless nights and days
Last night I dreamed the strangest dream
I’d ever dreamed before
I dreamed the countries all agreed
To let us fight our war
I dreamed the un conference hall
Was decked in blue and white
And shamefaced leaders stood up tall
And said we know that you’re right
And when they’d finished saying this
They took the floor again
and loudly they declared they’d stop
The killing of innocent men
The anchor on the evening news
said sorry I know I was wrong
she said she’d stop her slanted views
and promised to help us stand strong
I heard a loud and mighty boom
I heard a muffled roar
I knew that we’d be safe real soon
with no more fear anymore
Last night I dreamed the strangest dream
I’d ever dreamed before
I dreamed the countries all agreed
To let us fight our war
Oh, how l’d hate to go into the army,
Oh, how l’d rather remain at home.
That’s why I am here today,
In the Kollel where I’ll stay
We’re dodging the draft,
We’re dodging the draft,
We’re dodging the draft in kollel.
Some day you may have to go into Gaza
We’ll say some tehillim for you if we  can.
While you’ll be tensely standing guard
I’ll be learning torah hard.
It’s great to be a chareidi man.
התורה היא חיינו
היא חכמה אמיתית מאת הקל
הלימוד הוא מגיננו
הוא צבא ההגנה לישראל
ובדרך הכופרים אין אנו מאמינים- אין אנו מאמינים!
ולגיוסיהם אין אנו מקשיבים- אין אנו מקשיבים!
בדרך התורה נלך- ביום ובלילה
בדרך התורה נלך- נגד הממשלה.
הבחורים הם חיילינו
הלוחמים בעד עם ישראל
העזרה הגדולה בעדינו
הוא לימודים ועבדות הקל.
ובדרך הכופרים- אנחנו עוד מפגינים- אנחנו עוד מפגינים!
ולגיוסיהם אין אנו מקשיבים- אין אנו מקשיבים!
בדרך התורה נלך- ביום ובלילה
בדרך התורה נלך- נגד הממשלה.
הממשלה הטמאה
אמרו לצאת למלחמה
ביטול של ימים ביטול של לילות מן התורה
להתחזק בתפלה
נגד הגזרה הרעה
על חורבן של הבית המדרש הקדושה.
עוד יבוא ימי הדין
אני מבטיח
עוד יבוא ימי הדין
בכל השעות החשוכות של האומה
תמיד תורה היא המגן ששמר עלה- כי חכמתה מאירה את הלילה
תמיד הוא הכי חשוב בעת מלחמה
ובכל דור ודור
היא תמיד מה שעמדה- לרחק מהר את מה שמפחיד לך – צרה וצרה
דחו מפני לומדיה- וברור שעכשיו
היא מאד נצרכה.
להתחזק בלימודים
נגד כפירת הציונים
ללמוד בכל עת ולהתחזק בחכמתה
כי הגיוס הוא המחבל
שמחריב את ישראל
וחייבים אנו לעמוד לביטולה
עוד יבוא ימי הדין
אני מבטיח
עוד יבוא ימי הדין
בכל השעות החשוכות של האומה
תמיד תורה היא המגן ששמר עלה- כי חכמתה מאירה את הלילה
תמיד הוא הכי חשוב בעת מלחמה
ובכל דור ודור
היא תמיד מה שעמדה- לרחק מהר את מה שמפחיד לך – צרה וצרה
דחו מפני לומדיה- וברור שעכשיו
היא מאד נצרכה.
Zoo
Someone told me it’s all happening right at shteebs
I do believe it, I really do believe- yuh yuh yuh yuh yuh
There’s a smelly sort of feeling as you walk into the room
And sort of dreary melody off tune…
Elul, we start at school
A fresh new zman has come again
Tishray, I will stay
Learning with a fiery bren
Cheshvan a zman’s begun
The winter months are dark and slow
Teves I will face
With a dreariness I know
Shvat I’m learning pshat
As I Kriech and Kriech again
Adar we’ll go far,
As the zman comes to an end
מחבלים הארורים
חטפו מאתים שבויים
והרגו וגם חבלו את אחינו.
ועוד אנחנו דואגים
על גיבורי החיילים
שהולכים למלחמה בעדנו.
עוד יבוא ימי שלום
אני מבטיח
עוד יבוא ימי שלום.
בכל השעות החשוכות של האומה,
תמיד תורה היא המגן ששמר עלה,
כי חכמתה מאירה את הלילה,
ותמיד זה הכי חשוב בעת מלחמה.
ובכל דור ודור היא תמיד מה שעמדה
לרחק מהר את מה שמפחיד לך
צרה וצרה דחו מפני לומדיה
וברור שעכשיו היא מאד נצרכה.
להתחזק בלימודים
נגד הגזירה והדין
על אחינו בית ישראל שבצרה.
כי אלקים הוא השומר
והוא מושיע ועוזר
לא ינום ולא ישן בכל שעה.
עוד יבוא ימי שלום
אני מבטיח
עוד יבוא ימי שלום.
בכל השעות החשוכות של האומה,
תמיד תורה היא המגן ששמר עלה,
כי חכמתה מאירה את הלילה,
ותמיד זה הכי חשוב בעת מלחמה.
ובכל דור ודור היא תמיד מה שעמדה
לרחק מהר את מה שמפחיד לך
צרה וצרה דחו מפני לומדיה
וברור שעכשיו היא מאד נצרכה.
שלום ילדות שלום
למדנו טוב היום
היום נגמר הגיע כבר
הזמן להגיד שלום.
אני מאד שמחה
להיות המורה
של כיתה כל כך טובה
שלום ילדות שלום
(אנחנו מאד שמחות
להיות תלמידות
של מורה כל כך טובה
שלום מורה שלום)
היום זה כבר נגמר
אבל נמשיך מחר
נלמד נקרא ביחד עוד
שלום ילדות שלום.
היום זה כבר נגמר
אבל נמשיך מחר
נלמד נקרא ביחד עוד
שלום ילדות שלום.
וגם אני נוהג כמו לוט
כמו כן אני בועל בנות
יצר גדול בתוך גוף שפל
וכמו זמרי, אני בועל מואביות.
Ani Maamin
They tell me that I’m holding on to someone else’s Long John’s, Long John’s, yeah.
I look into the mirror I will check what I have got on, got on, yeah.
No need to check the tag and name (no need to turn and check the tag) to know they’re not my own,
They’re pink and lacy, with the nicest purple ruffles sown
They say forget about those pants you’re wearing,
I will hold on, I’ll hold on
I will keep wearing tights, in my bed in the dark of night,
They’re so cozy I don’t care at all, yeah, I will hold on, I will hold on.
Self-Control
It’s a picture perfect moment, everything is going well.
‘till the air is filled with such a vile and nasty smell.
What should I do? – I’m so embarrassed! I know they all can tell
Everybody knows I suffer from incontinence.
They look askance at my dirty pants.
Somehow I don’t know
When I have to go
Everybody knows I suffer from incontinence.
Diapers, creams, and lotions, supplements and loads of pills,
I try every solution, yet I find I always spill
What should I do I have this problem and I think I always will
Everybody knows I suffer from a lack of self control
I never stop – I just go
There’s guilt and there is shame
I’m not potty trained
Everybody knows I suffer from a lack of self control.
Tzedakah
If you are reading a sefer and you find
A paper clip that’s massive, it probably is mine
So do not simply leave it and go back to your seat
Try to call my number, and give it back to me
551
551
223
9466
9466
Bring my clip back to me.
Twinkle twinkle
Spangle spangle
Every star
O’er the ramparts
Near and far
Spangle oh you stars so bright
(on the lovely dawnzer light)
Spangle spangle
Every star
In every banner
Where you are
Yankee doodle
Mnr thulley came to town
Riding on a trolley
Going to a business meeting
With his father solley.
I will
Do you know how much I hate you
I really think you should
Would I shove you down a staircase
Oh, you better bet I would
When, at first, I met you
I noticed right away
How I felt, and so I warned you
And I told you: stay away
I’ll hate you forever and forever
And I’ll always wish you ill
could we be friends? No we could never
I hate you and always will
A bochur came to lander landers? Lander
A bochur came to lander to learn and shteig
We showed him all around and we he saw where the beish medrash is
But we never showed him that there’s no one inside
A guy showed up in landers…
A brand new guy in Landers we’d never seen
We asked him when he came and he looked at us peculiarly
And he said I’ve been here since 2019
You’re always welcome in landers
Any time of the year
You’re always welcome in landers
And you don’t have to go to shiur
A man came to landers
A man came to hear the rosh yeshiva’s address
We asked him if he liked it and he turned to us and cleared his throat
And he slowly nodded: absolutely yes
A bochur came to landers
A bochur came to try out rebbi’s shiur
We asked him to come in and he sat right in the very front
And still he sadly told us that he could not hear
A bochur came to landers
The bachur was as skinny as could be
But after just a month, he looked like a hippopotamus
In landers you can always find food for free
A guy came to landers
He came for rabbi soloveichik’s shiur
He sat up right in front and he listened so attentively
But he sadly told us that he could not hear
A guy came to landers
A guy that we had never seen before
He asked for rabbi elbaz and we brought him in to speak with him
And the first thing that we heard was: hey! Chamor!
Ida, how do you feel?
Did the aches and the pains that afflicted you heal?
Ida, I don’t want to know-
But has Gida come back, and – oh! – how did it go?
Your grunts and your grimace, your harsh bitter tears
Tell me that Gida did not disappear,
Oh Ida, how do you feel?
Hey there mr. chuphead
You think your chup is cool?
Well I think your biluris
Leaves you looking like a fool
Hey there mr shtoty
You like your neat trim beard
I’m sorry mr. shtotty
But your beard makes you look weird
To every thing
Teif teif teif
There is a svara
Teif teif teif
And a kler for every cheftzah in the briah
Is shomeah koneh really for real
Is hanaah a feeling the neheneh feels
Koyach hataanah or simply a proof
Is shvuah an issur or not telling the truth
When we are meisiv is it a part of matzah…
What is the mlacha, the act or the goal
Is m’ilah a chillul or maybe he stole
Is shlucho shel adam really like you
A safek Mehadrin- what should you do
Is tmurah a transfer or a hekdash
I Know You Will Protect Me
I know you will annoy me
I know that you will bother me
I know that you won’t leave me alone.
You’re stinky and you’re whiny
you’re stupid, you’re a crybaby
I wish that you would just go home.
You are so nasty,
so very nasy,
you are so nasty,
and I hate you so.
There is nothing you can do to make it up to me.
How I hate you – yes, I hate you – go away!
You are so nasy,
so very nasty,
you are so nasty,
just go away!
You are my baby
my tired baby
you are my baby
now go to sleep
there is nothing that is stopping you from slumbering
you have blankets pillows bundled at your side
you are my baby
my tired baby
you are my baby
layla tov.
* Footnotes
[fn:1] We’d live the life we’d chooseWe’d learn and never shmooze
