* Fragmentary Lines
* Thomas T. Taylor
1.For he/she who was a part of me
Now lies beside me dead.
2.Somewhere high up in a tree,
A sparrow sings/chirps a melody.
3.Gleeful shouts resound about
The wide and sweeping golden fields.
Freedom sings-her trilling brings
A smiling, gaily blowing wind.
4.All along the grassy peaks
Which nobly ringed my childhood home,
The rain would fall in gusts of wind
Upon the ground on which we roamed.
5.The cold and calculating mind
That lay behind his/ those calming/azure eyes
6.Gist: Battered soldier proudly flying flag snatches heroic victory from the jaws of defeat, dies bravely in the process.
The stench of war is in the air,
With bullets flying everywhere.
The soldier holds his head up high,
Waves the flag he proudly flies.
…
All around hi, sights of war-
Limbs and bodies, blood and gore.
He sees but one thing with his eyes-
That faithful flag he proudly flies.
All around him soldiers fall,
And yet he stands up, proud and tall,
His emblem makes his courage rise;
He waves the flag he proudly flies.
The soldier cannot strategise,
Just waves/ prays to the flag he proudly flies.
…
The soldier, hit, says his goodbyes
To the flag he proudly flies
…
The soldier will be buried soon
In/with the flag he proudly flew.
(…
Oh heaven, let this hero rise
With the flag he proudly flies.)
7.. . . song that saw my spirit swoon.
8.What care I whose body lies
Beneath this marble stone
…
…alone.
9.The fearful frightful fury of a fierce and fearsome/fiery face.
10.Glassy-eyed and unkempt youth.
11.I shall think as I thought
And fight as I fought.[fn:1]
(and never let go of
The truth I have sought.)
12.For a fragile/trusting heart, once broken,
Is a hard thing to rebuild/can scarcely be rebuilt
And a soul unkindly shattered
Takes a long time to be healed.
(Perhaps this could reference cw’s victims?)
13.Once I was fair, and my radiant hair
Teased/turned your affection towards me.
Your eyes shined so bright as I held you each night/held your hand tight./I’d watch your eyes shine, and I’d know you were mine.)
Remember how/that you loved me.
A pitiful pauper who’s peddling pans,
A miserable mendicant, barely a man
I watch you recoil/I watch as you shudder, afraid of a glance/and try not to glance.
Remember how/that you loved me.
I know not why you left me-perhaps I never will
But now what does affect me is can you love me still?
(Look at me as I once was, not as I am now)
Remember . . .
Oh, silly me! Why can’t you see
That I’m longing to embrace thee.
Have pity; behave kindly
Remember . . .
1. I wander down the winding roads
(Which stretch) beneath the looming clouds
15.The wind is whistling in my ears,
The rain has drenched my hair/ my hair is drenched with rain/ the mist ha wet my eyes.
16.You are not who I thought you were;
You are not who you were before.
17.Little boys with dirty hair.
18.Burning/blazing brightly, fading fast.
19.Hardly can I recognize
The truth that slips/sleeps/seeps/you slip between your lies.
20.Bravely once we stood-we four-
Bravely so /shall we stand no more/bravely once, but never more.
One was hanged/shot, and one was drowned;
One was lost and won’t/can’t be found.
Alone I stand, a tired (two syllables)/weary/tired (one syllable) old man
Pursued by all I understand/and wearily do all I can.
. . .
‘tis but he firmness of my feet
That guards against a/our sad retreat.
‘tis but the keenness of my eye
Ensuring that we do not die.
(These four lines could stand alone.)
Bravely once…
…
…drowned
The fourth will fade without a sound/ has faded with no sound.
21.(Taliban and Afghanistan rhyme.)
22.I spied a bird upon a limb
Standing silent ‘midst the din.
Around it, flocks chirped merry tones,
But it stood mute, aloof, alone.
“Bird,” I cried, “I truly long
To hear you/thee trill your/thine lovely song.
So play your/thine whistle, pipe your/thine flute.”
The bird stood still; the bird stood mute.
Oh bird said i Why cant i hear
The only song that i hold dear
The creature opened up its beak
To give to me the song i seek.
But as it tried to pipe its sound,
It fluttered softly to the ground
[the bird, at long last, begins singing-in an obviously weakened condition]
The sweetest sound I’d ever heard
Was warbling from the dying bird.
23.Spread your legs, and I will see
If you truly care for me.
(Spread your legs and you will see
What you truly mean to me.)
24.For I can see what you cannot
And what I see tells me a lot.
(It tells of Israel’s misery
Of her desire to be free.)
1. It seems that it was all for naught
I never really had a shot
1. In fractured fits of fury,
I flail my frantic mind.
1. Mr. Greenberg[fn:2], get your feet
off my lovely leather seat!
Mr. Greenberg, won’t you stop
climbing on the countertop!?
Mr. Greenberg wipe your nose
-on your tissues, not your clothes!
Mr. Greenberg, won’t you quit
acting like a little[fn:3] kid!?
[further childish acts from the irrepressible Greenberg]
Mr. Greenberg, won’t you stop
acting like a tiny tot!?
[the further misadventures of the mischevous Mr. Greenberg]
Mr. Greenberg, won’t you, maybe,
stop behaving like a baby!?
Streams of water skipping down,
And splashing as they strike the ground;
Weathered stones of grey and brown,
A soft and slow incessant sound.
A room in Australia,
A bed in Brazil;
A place to call home in the Indian hills.
A garden in Paris,
A courtyard in Spain;
An acre of cornland in Idaho’s plains.
Wouldn’t it be a ridiculous sight…
He’s not so clean, and sort of smelly;
His only hair is on his belly.
We know this all too well, quite sadly,
His shirt is fraying rather badly.
His pants are ripped and very dirty,
They’re an antique from nineteen- thirty.
Here lies one who never was
All that he could be[fn:4]
…
He looked but did[fn:5] not see.
I often write the poem first, and then think of its meaning
…
Vapour gathers in the sky, and joins to make a cloud;
Its waters shift, the lightning hits, and then it thunders loud.
What once was shall be no more-
Lock the shutter, close the door!-
The waves may splash and lap the shore,
but what once was shall be no more!
He was a young man with dreams,
and not much more.
He was looking, but did not know,
what he was looking for
Hindu, Bhudda, Zen-
He’d tried all of them
He was a young man, with dreams
and not much more.
… [interlude where he finds Jews, who demean his as a Baal Teshuva]…
He was an old man who lived
the American way
He was happy, but what he believed,
he really could not say.
Relaxes every Sunday,
works hard every Monday
He was an old man, who had
his dreams no more.
And so, my friend, we've reached the end;
I shall not write to you again.
Its battered branches (dry and) bare
when I was young, I always thought
my father was a king.
Well, it turned out that he’s not;
that didn’t change a thing.
I find I love him much more now-
now that I’m a man;
mature enough to realize how
he made me what I am.
what was once (what once was) shall be no more
cry the footsteps on the floor
let me mourn my silent pain
letmy face be flushed with shame
lock the windows close the soor
for what once was shall be no more
what once was shall be no more
close the shutters lock the door
still the cries of silent pain
flush the faces of their shame
halt the gestures of the hand
that no mortal understands
banish footsteps from the floor
for what once was shall be no more.
many years have made their way
past dear belinda's simple grave
it wears its wrinkles wrought by time
better far than i wear mine
my wisdom works in many (in wonderful) ways
a single thought diverts the haze
of mist which overclouds my mind
and fogs it so until its blind
and yet at times my wisdom fails
to muster forth a single gale
to clear the air and shine the sun
and then my wisdom is undone
go find another feeble (filthy) mind
to sew your socks and press your wine
i only write in simple rhyme
i use this rhythm every time
its like i know a single way
of writing what i want to say
and, truth be told, i only know
the single style that i show.
This is a series of rather meaningless poems. Bob Dylan and TS Eliot were my models for these.
I should like to go swimming and then take a walk,
a lecture on spinach, and darning a sock,
a silent enjoyment, enraptured, serene
uncouth and ungifted, depraved and obscene
a wild and mad forbidden dance
a misty psychedelic trance
a day that comes then comes no more
a tapping at the kitchen door
rooms that never will suggest,
heavy work and heavy rest
march’s clouds and april showers,
but where are the bright may flowers?
Walking on a simple path
purples greens and half and half
buzzing sounds that drone around
passing a forgotten town
deserted streets and rotting homes
web encrusted catacombs
a mist of dust in cloudy haze
wasted empty useless days
onward stretching
never ending
crooked blessings
lead to rome
long forgotten
ill begotten
dark and rotten
drifting home
a battle fought a battle won
prizes now for everyone
a bloody hand a tortured brow
a rusty dagger beat from plow
islands of unwanted life
shouts of terror shrieks of strife
huddled shapes of cloudy black
surging forth yet holding back.
Long forgotten shades of blue
in foamy green I dimly knew
golden sun on golden sand
a union of the sea and land.
Drops of turquoise in a coldness never felt this late
icy spoons and icy saucers showing signs of hate
dim lit doors
and fractured floors
monkey bars and see saw  seats behind the rusted gate
a wearisome woman recounting a fable
a pitcher of wine and a place at the table
a rapid alliance that never could be
and a shifting defiance that bent at the knee.
Someday I will show you
who I really am
someday I will know you
really understand
someday I’ll have told you
my dreams and hopes and plans
and that day I will owe you
everything I can
the left is going lefter the right is going righter
we’re waiting for the galleys and the rope is getting tighter….
I think I came a bit too early; think I stayed a bit too late
That is why I’m sad and[fn:6] surly, feeling angry bitter hate.
Alone I am and always shall be
Never shall I find a home
None can ever understand me
Always shall I be alone
Goodbye, my friend, goodbye, goodbye
It’s time you heard my final cry
Time you felt my final touch
(I doubt I’ll miss you very much)
I don’t believe I ever sighed
Ever sat and softly cried
Till the pain I felt inside
On the day my goldfish died (This could be made more serious.)
Skipping in a field of flowers,
Hair that’s wet from gentle showers.
The working class is (I know that you are) fed up,
But try to keep your head
For there will come a day
When all of our crying
All of our sighing
Will soon be wiped away
/
We’ll rise in revolution,
There will be retribution,
Our fears (tears) (foes) shall fade away.
There is no choice for us
We know what lies ahead
And yet we march – we must!-
Despite our rising dread
The road that takes us here
May (will) (shall0 never take us home
And yet we cannot fear
Our lives are not our own.
/
And none will shed a tear
Nor lie a lonely stone.
A beatles song-
Come on, baby, take (stay) the night
You know that it is only right
(and) we may not get another chance again
Come and spend the night with me
Wild and crazy, mad and free
Will we ever (laugh and) dance again?
I’m going away
In a day
And I may
Never return again
And I fear I may tire
Lose my desire
The flame of our fire
May never burn again.
When I was born the doctor
Shook his worried head
It’s mental retardation
That is what he said
But mommy quickly hugged me
And mommy held me tight
And mommy said she’d love me (she loved me)
And things would be alright
I don’t really remember this
It’s a story mommy tells
I always love to hear it
‘cause she tells it all so well.
I really love my mommy,
And she loves me too
She says it never matters
All the things I cannot do
I have a hard time learning
I really don’t like school
Ever since my classmates
Told me I’m a fool
But so so many people
Are always nice to me
They always see me watching
And smile back at me
/
And when they see me watching
They smile back at me
They always try to help me
I love them so so much
No matter how I thank them
It never is enough
Yes, my friends are all so friendly
And yet I wish they’d see
I’m satisfied I’m happy
I’m glad just being me (glad that I am me)
-
And will you never heed the call
And will you never come
And must we falter, flee, or wall
And must our hour be done?
Where were you a week ago,
When I lay here alone?
I miss(ed) you more than you can know,
So won’t you please come home (I wish you would come home)
My (his) head is nodding, soon will drop
My (his) feeble struggles soon will stop (maybe switched order)
What is he saying?
I don’t understand
What he’s explaining
Using his hand (how he’s explaining his words with his hand)
It’s not entertaining
It’s quite irritating
I won’t stop complaining
Until this is banned.
Her coffee tasted funny
It did not taste quite right
He found out she had money
And brewed a cup tonight.
Do you really love me?
I do not think I do,
But I will never tell you,
Until you tell me to.
What a roller coaster ride!
I’ll ride it one time more-
Alas! What started off inside
Now tossed across the floor!
A brown shoe
Tells you
He’s modern and he’s cool
A black hat
Means that
He spends his days (nights) in shul
A black fedora
Should ensure a
Measure of respect
A sturdy shtender
Should engender
The shtarkness you’d expect
I’m a better jew
Cause I’m shtarker (frunmer) than you
And I put my shtarkness right in view
A battle coming up and i
Must do my best or I shall die
(must do my duty till I die)
I never understood
What made you be this way
You used to be so good
Just the other day
I often say you falling
Yet never came to see
I often heard you calling
And crying out to (for) me.
Who’s to say
I’ve lost my way
There is no more left to say
Since you’ve left and gone away
And I light each night in bed
And I wish that (and imagine) I were dead
Quite afraid and very scared-
Yellow yellow yellow-
Very new and unprepared-
Green yellow yellow-
A commie by his comrade’s side-
Green red yellow yellow-
He’s so depressed he sighs and cries-
Green red blue yellow
The time has come
The time is here
This must be done
We cannot fear
We must stand strong
We must stand proud
And sing this song
And sing it loud
There’s nothing poetic, cause everything’s bland
There’s nothing exciting I don’t understand
There’s no more adventure, no magical spark
Or trace of excitement to light up the dark
I feel like there’s something that’s missing inside
I feel like a part of me shrivelled and died
Like something has vanished; I’m empty in there
And saddest of all- I don’t even (really) care
Empty lines I read and scan
Words (lines) I do not (cannot) understand
Abcdefg
Won’t you come and play with me?
Hijklmnop
Come this afternoon for tea
Qrstuvwxyz
There once was a girl with a goose in her gut
And a stomach that would not stay still
And sometimes the goose would get nervous and strut
And make her so queasy and il
Al ahavatecha
I’ll always love you
And I’ll hold you tight
I’ll always be there
To sing to you each night
Hearing your steady breaths
Watching your smile
I always will love you, my child
I never thought you were
What I found you are no more
ר"ע
A little stream that drips and drops
For many years and never stops
As time goes by will slowly bore
A hole within the rocky floor
The road is hot, the day is dry
He tarries not, nor wonders why
And the wind outside is tinged with retribution
He’s drifting down the inept street
The boots of sorrow on his feet
In the air, there is the smell of revolution
Wake up sleeper from your dreams
Creaking bedstrings, rotted (rotting) beams
For every man is just his brother’s keeper
Your sheep have have wandered far from home
They prance and play; they roam alone
And yet you slumber on, so wake up sleeper.
Hear the ringing martial beat
Of clapping hands and marching feet…
Join me as we stand and say
We will not bend we will not sway
And joined together hand in hand
We’ll bravely make a (our) final stand
9we’ll fight and fight and not give in
Until, at last out cause (the truth) shall win)
Flashing lights and billboard screens
I think I heard a woman scream
A man sits on the side, unseen
And drifts into a drugged-up dream
The crowd begins to dance and cheer
An old man yells an ugly jeer
I see a wide-eyed child draw near
And watch his eyes fill up with fear
The rumble of a subway train
Calling those who can’t remain
“g-d-m” I hear a girl excloam
“but all is well; I can’t complain.”
“Brother won’t you stay the night
A little rest would treat you right
The lazy dreams and mad delights
That shock your mind and hold you tight
A line is snaking single file
And fills a block and goes a while
Past the tattooed man who smiles
And giggles like a juvenile
A public bathroom on the street
I see a man who slyly peeks
Beneath the door, at ragged feet
And laughing lewdly takes his seat.
Molly was a trouble child
She never laughed and never smiled
She stomped her feet and threw a fit
She would not budge a tiny bit.
Every day, at half past two
Molly was sent home from school
With a note they know would say
Molly misbehaved today
At home she always misbehaved
She never shared and never gave
She yelled for everyone to hear
I wish you all would disappear
She kicked her sister, pulled her hair
When Mom sat down, she tipped her chair
When daddy asked are you alright
She slammed the door and locked it tight.
Daddy, won’t you look and see
And hug me tight and play with me
Daddy won’t you smile again
And pick me up and be my friend.
Perhaps we’ll meet some other (another) day
And, hand in hand, we’ll walk away
But as for now, we’ll have to cry
Goodbye, my friend, goodbye goodbye
Glistening green amidst glittering blue
Lush forest floor, with a cov’ring of dew
We all have our fight (job) and we must plot our way
Through the challenging tests and the wild desires
Watching our time as its drifting away
And we know we’ll stand judgement someday
All wealth is worthless…
How I hate the minute hand
As it moves so slow
Why will it not understand
That it is time to go
Run run run run
All around the clock
Till you reach the other side
As you tick and tock
(run and do not stop0
Never will I understand
Hard as I may try
Why you will not take my hand
Or look me in the eye
Beatles song:
This is just a little song to tell you how I feel
These are just some words I wrote to show you love is real
Beis yaakov play
But, as jews we choose to stand firm and tall
And despite their might we will not bend or fall
And time and time again
We cling close to hashem
הקב"ה מצילנו
Centuries… our cries and pleas
Slleping in shiur;
Eighteen pairs of eyes
…
No one even tries
…
They shut and disappear
…
To stay awake by shiur
Half my life has dripped away
I cannot (must not) waste another day
The stars never twinkled as bright
As they did tonight
And the sun never set
As it did when we met
Maybe all you want from me is to break my heart
But darling cant you see if we drift apart
I’m suffering and I just cry and moan
how I miss you, please, won’t you come back home…
little child, you cannot know
all the places you will go
you may be small you may be meek
but little child you’re far from weak
who I am, I do not know
won’t you tell me where to go
I think that I have lost my way
I had it just the other way
Will I never see again…
For I have lost my closest friend(s)
We thought that jack was quite alright
He came in here the other night
He drank a case or two of beer
And tried to box the waiter’s ears
He banged his fist, began to roar
And asked us please to bring some more
We brought him all the rest we had
He drank it up and then got mad
He asked us for some rum and gin
And drank it with a wicked grin
He asked us for some liquor too
Just to see what we would do
We brought it out; he drank it up
And asked us for another cup
He changed his mind and then he said
I think I’ll have some wine instead
He burped and yawned and cleared his throat
And left our house without his coat
So as I said, he seemed alright
You say you found him dead (he killed himself) last night (tonight)
Children never notice
That they will not make it far
For nothing’s ever hopeless
When a child is what you are
Every time I lift my pen,
I have to put it down again
[and so, my friend, we’ve reached the end,
I shall (can) not write (sing) to you again.
-- as an end for a book of poems, saying that we do not really know each other but through our poems.]
* Footnotes
[fn:1] Or: I shall think as I have thoughtand fight as I have fought
[fn:2] In this silly poen, Mr. Greenberg is an adult, probably in a suit and tie, who is acting in a manner highly inappropriate. Why he is doing so is irrelevant to this poem.
[fn:3] Could be “… acting like a spoiled kid.”
[fn:4] All that he was meant to be
[fn:5] could
[fn:6] Why I look so surly
