* Real Estate Development
* For Low-cost And Great Solutions
* Your Israel real estate company
* Specializing in special locations for your special ones
We, at the RED FLAGS Company, have heard of your search for the perfect location for your dear son Shimon and his fiancé Bertha Peninah. Therefore we, at the RED FLAGS Company have sent you this little letter, to assist you in your search. We (at the RED FLAGS Company) have collated some of our top picks. And, remember- we specialize in doing our specialty.
Our first location seems to have been tailor-made for Shimon. Right near the Mir, it is Rechov Shimon HaTzaddik, as pictured below.
Our second location is a bit feistier, perhaps, but just as specialized- so specialized, in fact, that its specialization is truly something special. Located between Rechov Malchei Yisroel and Machane Yehuda is our next pick, Rechov Shimon HaMacabi, pictured below.
We (at the RED FLAGS Company) believe that our third special location will suit you in a special way. Located right near the Kotel, with an apparent abundance of piñatas (which, to us, seems a fairly close fit for Penina), is Rechov Shimon Ben Shetach, pictured, as before, in a special spot- namely, right below.
Another special location that popped to mind is Rechov Penina. Rechov Penina is a hidden little street. It used to be bustling, with many offshoots, but somehow, as its neighbor, Rechav Channa, gained, it lost, until now it has zero offshoots. Pictured below is this special location, Rechov Peninah.
But, we (at the RED FLAGS Company) get it- not everyone is cut out for an apartment in Yerushalayim, no matter how special it may be, and no matter how special they may be. Some special people realize that they cannot afford an apartment in this special city, and so we specialize in finding them their own special location. As such, it is a special privilege to present the special Shimon Hatzaddok Lightrail station. Located conveniently near the lightrail, this station combines the placid calm of Arzei HaBirah with the special thrill of Sheikh Jarreh. Pictured below is the station.
* With special effort,
* RED FLAGS
