Tom was selling lots of seeds,
and so I bought a dozen.
He said it was a pygmy breed-
turns out that it wasn’t.
Donald bought a danish, and Cathy bought a cat.
Tommy bought a tuba and Harry bought a hat
Garry got a Gatorade and Iggy got an ice cream cone-
Why do I wind up with nothing but a xylophone?!
- Xavier
”Have you ever been around the boiling lake of tar?
Have you scaled an icy cliff? Played hopscotch in the car?
Have you crossed the arctic sea, and said you found it hot?
Have you dangled from your nose-“ ”Darling, I have not.“
It’s not my day
stay far away
I’m grouchy[fn:1] and have lots to say.
If I didn’t have you,
I don’t know what I’d do-
why, I hardly can walk straight without help from you.
If I stood up, I’d fall,
if you left me at all-
yes, I surely do need a good lace in my shoe.
Well, Roger, I’ve got just the right girl for you:
she’s clever and funny and knows what to do.
She’s gorgeous and playful- and just so you know,
she’s a labrador mix, from her tail to her nose.
* Footnotes
[fn:1] grumpy
