פרק א, משנה א, הקדמה:
- מכניס את צד- לא כל כך פשוט מגמרא אם יש צד אחד שצריך להכניס (צד שיש בו אגודל או צד שיש בו זרת), ואיזה צד, אם יש צד.
פרק א, משנה א, הקדמה:
- את הצד- לקמן, בע“ה, נבאר שאולי יש אופנים אחרים לקמוץ. ודע שאין צורך לקמיצה רק כדי שנבחין כמה צריך להקטיר, שלא יכול לעשות מידה כדי קמיצה שלו[fn:1]. אלא, צריך לעשות בו מעשה קמיצה. אז, יש לדון בצד לפסול אופנים אחרים של קמיצה, אם הוא מחמת המעשה (אינו המעשה הנכונה) או מחמת השיעור (אף שהוציא אותו בקמיצה, לא הוציא שיעור הנכון). גם יכול להיות בעיה בשניהם.
פרק א, משנה א, הקדמה:
- אמצע- עיין בפירוש שני של רש"י בביאור מן הצד (יא.), שנמצא שיש צד ברש"י שגמ’ מסופק אם יכול לקחת מאמצע הכלי או לא. לצד ראשון של גמ’, יש לדון לאיזה צד פשוט לגמ’, שכשר או שפסול.
פרק א, משנה א, הקדמה:
- הוא הקומץ- עיין בגמ’ יומא, שמסופק אם מה שנשאר בין אצבעות שלו נחשב גם כן מן הקומץ.
פרק א, משנה א, קנאות:
- מנחת קנאות- עיין לקמן ברש"י (ה:) שאומר שמנחת קנאות פסול כיון שתורה קרא אותו חטאת. לכאו’, זה נגד מה שדורש גמ’ מפורשת, שאין זה הדרשה. וצריך ביאור.
פרק א, משנה א, מנחת קנאות:
- כיון שלא התיר- ואם תאמר יהיה הבריי’ קשה גם על צד זה. אולי אין הכי נמי, ובריי’ מוכח כר“י ור“ל. ואולי יש גם תנאים שחולקים במח’ ר“י ור“ל. וצל“ע בזה.
פרק א, משנה ב, אחד כל המנחות:
- קרבנו מהודר- לא פשוט לי למה לא רוצים קרבן של חוטא להיות מהודר, שהרי אין הקרבן רע, אלא החטא רע. הקרבן הוא טוב, שמכפר על חטא. ותחשב. אולי לא רוצים שהחוטא יתפאר את עצמו על ידי קרבנו זה. ותחשב על זה.
פרק א, משנה ב, אחד כל המנחות:
- כמו שבארנו- עיין שם, שבארנו שבאמת, מחלקת אמוראים הוא אם יכול להיות משנה שלנו כרבי שמעון. אז, תירוץ זה של גמ’ לא מהני לכל האמוראים. ויש לדון, שנראה שאולי מה שיש צד לחשוב שמשנה שלנו אינו כר“ש די, שאז נפרש שמשנה זה אינו כר"ש, ואז נניח גם שמשנה ראשונה אינו כר“ש, ולא נפרש אותו, בהו“א זה, כאותו אמורא. ותו"ת.
פרק א, משנה ב, אחד כל המנחות:
- אינה כר“ש- נמצא שמוכיחים תנא של משנה שניה מתנא של משנה ראשונה. גמ’ עושה כן בהרבה מקומות. עיין ברש"י ביומא שמבאר שהענין הוא  שכיון שיש הרבה משניות שמדברים על ענין אחד, הם כמשנה אחת, וצריך להיות שתנא אחד כתב את כולם. ותחשב.
פרק א, משנה ב, אחד כל המנחות:
- כיון שאומר- אין זה נלמד ממשמעות; שניהם היו משמיעים כל המנחות, ואף מנחת חוטא. אבל, כיון שאומר אותו באופן יותר ארוך (ואולי יש גם משמעות ממה שאומר אותו באופן שמשמע שיש לחלק[fn:2]), לומדים שהוא אף לפי שיטת ר“ש. ותחשב.
פרק א, משנה ב, זר:
- דורשים- רק הבאתי את כל המקורות מזבחים, ולא עיינתי לראות אם הם המקורות למנחות. מסתמא, צריכים להיות, שאין גמ’ שלנו מביא מקורות. אם לא, נאמר שנלמדים מהיקש מזבחים, שכ’, ”זאת התורה למנחה….“
פרק א, משנה ב, פסל:
- חטאת ואשם- דורש אותו מן ההיקש לחטאת ואשם. אומר שאם בא לעובדה ביד, עובדה בימין, כחטאת, ואם בא לעובדה בכלי, עובדה בשמאל כאשם (לשיטתו). צריך לבאר על מה זה קאי. מלשון הדרשה, וכן מבאר רש"י בכמה מקומות, נראה שקאי על ההקטרה. אם מביא אותו ביד, מקטיר אותו ביד ימין. אם מביא אותו בכלי, מקטיר אותו אף משמאל. אבל, מגמ’ זה מוכח נגד זה, שאומר אותו גבי קומץ (ולא מסתבר לומר שסובר שלא יכול לשנות אותו מיד ליד, ואז ממה שמקיטר אותו מימין, צריך להיות שקמץ מימין, ועוד שצריך מקור לכשרוצה לתת אותו לכלי). אז, צריך ביאור.
פרק א, משנה ב, פסל:
- שלא נוגע לידו- גמ’ קורא לזה ”מן הצד“; וצריך ביאור למה צריך להיות בצד (במקום שרואה אוויר) כלל. עיין בשני לשונות של רש"י; לא הבנתי מהו התי’ כלל ללשון שני. ותחשב.
פרק א, משנה ב, כיצד הוא עושה:
- לפס ידו- רש"י לא מבאר את זה כל כך. לכאו’, יש לדון אם ידיו הם כפופים או פשוטים כשנכנס. ותחשב. גם יש לדון אם יש חילוק בין איזה צד של ידו נכנס בו הקמח. צריך לבאר למה אין זה שווה ל“צדדים“ ששואל לקמן. ותחשב.
פרק א, משנה ג, חסר שמנה:
- ששיעור- צריך ביאור מהיכי תיתי שאומר ששיעור שמן מעכב, ולא רק ששמן מעכב. ותחשב.
פרק א, משנה ג, חסר לבונתה:
- כל הקומץ- יש לדון מהו הדין לפי רבי מאיר אם הפריש יותר מן הקומץ וחסר ממנו עד שהוא רק קומץ. נראה שהוא כשר, אף שיכול לטעון שרבי סובר שכל חסרון של לבונה שנקבע עם מנחה פוסל. (לא מסתבר שיפסל כאן, שהרי בהכרח ”יחסר,“ שבהכרח לא ייקרב ע“ג מזבח.) ויש לדון, שלשון גמ’ בביאור מקור לשיטת רבי מאיר קצת משמע שיפסל.
פרק א, משנה ג, והנותן בכלי:
- כנגד- אין כל זה כל כך פשוט לי. איני יודע המקור לארבע עבודות בזבחים, ואיני יודע המקור שצריך להיות עבודות של המנחות דומים לאותם עבודות. ותו"ת.
פרק ב, משנה א, ואין בו כרת:
- נחשבים מתיר אחד- יש לדון אם חולקים כמה צריך להיות נחשב אחד או חולקים כמה נחשב אחד. אולי זה נוגע ללומדות של הקרבת המנחה. ותחשב.
פרק ב, משנה א, מן המנחה:
- אינו כ"כ מובן- כן אומר גמ', אבל לא הבנתי כל כך למה. לכאו', אילו היה אותו מתיר, פשוט שיכול לחשב, שבוודאי יכול לחשב על זרידת דם אחר בשעת זריקת דם. אם כן, קשה למה לא נבאר כמו שבארנו בצד שלישי. וצריך ביואור.
פרק ב, משנה ב, פסול ואין בו כרת:
- כמו שאם נטמא- לכאו', אז, אם מה שחושב עליו מחובר דבר אחר, אותו דבר נתפגל. עיין בגמ', שלא משמע כן כל כך.
* Footnotes
[fn:1] יש לדחות בדוחק לומר שאינו רק כדי קמיצה האבארי“ג שלו, אלא שלו באותו רגע. אז, אי אפשד שכלי כעין מידתו יהיה מצומצם ממש, ואז אינו כשר. דחוק לומר כן.
[fn:2] ויש לדון, שבוודאי יש לחלק אילו סוברים כר“ש, ואולי רק זה בא להפקיע ממנו. ותו"ת.
