** א. משעה שהכהנים
- עיין במה שאומר. היה אפשר לומר שמפרש שאוכלים רק בלילה, ולא קודם, שצריך הערב שמש (וגמרא ביבמות (פרק הערל) דן למקור לזה). ויש להעיר שלפני משה, ק"ק למה לא אומר "מחוסרי כפורים" או כדומה, שהרי אין כל כהן כך- ובפרט כיון שאפשר לומר שלא עליהם קאי, ורק אומר חידוש שכתבנו. (צריך לומר, לכאורה, שלא סובר שמש"כ חידוש; צריך ביאור למה לא.)
** עד סוף
- יממא... זמן שכיבה- כוונתו הוא למה שגמרא יפרש שזה זמן צאת (ומביא קרא שאומר שזה לילה), ומבאר שזה זמן שכיבה, ולכן הוא זמן קריאת שמע. ותו"ת.
** ואיברים
- צריך ביאור למה אומר בלשון מוזר זה- תמיד, ואף שאר עולות, ולמה לא רק אומר עולות.
** כדי להרחיק
- צריך ביאור למה מביא הא דזבחים כלל (שהוא פלוגתא, ואינו כל כך נצרך). ויש לדון.
** כדי להרחיק
- כרת- קצת משמע שהגזירה הוא מחמת העונש (ואולי כרת בפרט, שהעונש הוא דבר רוחני רע), ולא מחמת האיסור או הס"ר.[fn:1]
** נכנסים -
יש לדון למה לא רק אומר נכנסים. אפשר שהיו טובלים מיד קודם לזה, ונכנסו שוב ליישוב. ויש לדון למה ישהו.[fn:2] גם יש לומר שאולי אכלו אותו בהר הבית או בעזרה (מסתמא לאכלו עם שאר קדשים. זה יבאר עזרה, אבל לא הר הבית. ותחשב.). ויש להעיר שאם היו מחוסרי כפורים, לא היו יכולים לבוא לעזרה, ואז זה אי אפשר לפני משה. גם יש לדון מה דינו בהר הבית (ששכחתי). אינו יותר מגזירה דרבנן, אבל אף זה יכול להיות קשה למה שאמר פני משה. ותחשב.
** משעה -
עיין ברש"י בבבלי שמבאר שזה קצת קודם כיון שסבר רבי מאיר שלא תלוי בצאת הכוכבים, אלא בזמן שכיבה. גם היה אפשר לומר שחולקים מתי זמן צאת הכוכבים, ותנא של משנתינו לא אומר "כשכהנים יכולים...,” אלא כשעושים אותו ממש, שהיה להם זמן שהיו חושבים להיות צאת הכוכבים. על כל פנים, לשון ברייתא שאומר סימן למה שעשו (צאת הכוכבים), ומביא ראיה מן הפסוק משמע כמש"א רש"י.
** א: באילין -
נראה שמפני זה צריך לומר, “וקרובים...,” שהיה אפשר לטעות לומר שהם חלוקים. ותחשב.
** באילין -
קצת צריך לדון למה הקדימו. נראה שיש שני צדדים:
1. אולי רצה לומר שהכינו את השולחן וכדומה לפני ביאת היום. ויש לדון למה זה גורם שהיית שעה או שנים. ונראה ששעה לא רצה לומר hour, אלא רק זמן. ותחשב.
2. אולי רצה לומר שהתחילו את המזון קודם שבת הרבה זמן, ואז היו יכולים לאכול אותו מיד בשבת. אבל, במקומות אחרים, היו צריכים לשהות כיון שלא הכינו עד מיד לפני שבת, והיו צריכים לשהות למזונות.
ויש לדון בשני אם יהיה שהייה. ויכול להיות אופנים שלא יהיה בהם שהייה. ותחשב.
** דצדו
- כשאומר ש”ממהרים לאכול,” לכאורה, לא אומר שאכלו מהר, אלא שהתחילו לאכול מהר, ואז התחילו מוקדם.
** ספק קרא
- עיין בפני משה בביאור השאלה. צריך ביאור, שהרי אם יצא ידי חובתו בפסוק ראשון, כמו שאומר פני משה, אז לכאורה פשוט מהו הדין כאן. ואולי סמכו רבנן חיוב דרבנן על החיוב דאורייתא, ודן אם על זה גם כן יש חיוב (או שנתנו לו דיני דאורייתא לענין ספקות כיון שהיה מצורף עם דאורייתא או שחייבוהו כל זמן שצריך לומר ק”ש, והרי כאן, מחמת הספק, צריך לומר קריאת שמע). ותחשב.
** מפסדת -
זה מבאר איך יכולים לומר תפלה שניה, וגם מבאר למה טוב לומר תפלה שניה. ותו”ת.
** לא יצא -
צריך ביאור מה רואים מזה, שאולי רק רצה לומר שצריך לקרוא פסוק ראשון עוד. ואולי אם כן היה לו לומר שקיים מקצת ממה שצריך, ולא נאמר שלא יצא, שמשמע שלא יצא כלל.
** קןדם לכן -
יש לדון, שאולי קודם לכן רצה לומר קודם הזמן האמיתי, באיזה זמן שהוא. ויש לדון, שאם זמן שכהנים טובלים או כדומה לא זמן שאז יכולים, אלא זמן שממש עושים כן, אולי היה זמן קבוע, ולפני זה היה ספק. ותחשב. ונראה מלשון “כהנים זכאים” שאינו זמן שעשו כן, אלא שהיו יכולים לעשות כן. ותחשב.
** קדמיא -
נראה שמונה השני כיון שהוא על כל פנים ספק. גם יש לומר שמונה את השני כיון שעושה לו קצת דיני לילה (כיון שהוא ספק). ותחשב.
** והכתיב -
מביא ראיה מן הקרא, אבל קרא רק זכר לדבר. נראה שמביא ראיה מברייתא שהביא קרא. ותו”ת.
** אשם תלוי -
לא איקבע איסורא, ואז הוא מחלקת תנאים.
** ב. אין תימר -
גמרא זה צריך ביאור. פני משה מפרש שהיה שואל אם זה התראת ספק. לכאורה, ראשון צריך ביאור למה לא יהיה התראת ספק. אולי שואל אם חייב על התראת ספק. לא נראה כן מפני משה.
גם צריך ביאור מה השיב לו, שרק מבאר לו שבוודאי עבר, אבל לא מבאר שיהיה התראה. וצ"ב.
- אגב, נראה לי שאולי דיון של התראת ספק אינו אם התראה על הספק מהני, אלא הוא אם קבלת עונש (שגם הוא נצרך כדי לחייב) על הספק נחשב התראה, שאולי חוששים שסומך שאינו עובר. ותחשב. ויש לדון אם צריך קבלת עונש לדברים חוץ ממיתה (שגמרא בסנהדרין אומרה על מיתה). ותחשב.
** יש לציין
לחרדים כאן, שאומר יסוד שלא כל זמן שאומר הירושלמי לשון "בעי" צריך לומר שהוא שאלה. וע"ש.
** ראה
- ק"ק שקורא אותו "את"ל,” שהרי אמר, שגמרא השיב על זה. ואולי שאל אותם כסדר, וגמרא השיב על הראשון, וסדר גמרא אותו תשובה קודם שסדר את שאלתו השני, אף שהיה אחריו בלי הפסק.
** ראה -
לא הבנתי למה נחלק לומר שלענין צירוף לא נאמר אותו ממ"נ.
** מה נפשך
- צריך להיות בחד זמן כיון שאין משך זמן בקצירה. יש לדון למה לא אומרים כאן שאי אפשר לצמצם. ותחשב.
** דיתחמון -
אם כן, קשה עוד אותו ברייתא לעיל (א:) שהוקמנו שמיירי בכוכבים שלאחר ראשון. ואולי עכשיו אומרים שהוא לאחר שני.
** בר מן -
קשה, שנאמר כן על כל ראשון. אם כן, לעולם לא יהיה לילה.
** ב: עליון שוה -
משמע שעליון נעשה שוה לתחתון, ולא שתחתון שוה לעליון. לכאורה, מה שהוא קרוב למערב יותר מנהיר. אם כן, לכאורה, הוא לילה כשמזרח ועליון שווים בשיחור, ומערב עדיין מנהיר.
** התחיל -
מפני משה משמע שאין אומרים בזה סימן אחר, אלא אומרים שיש עוד דבר שקורה אז. יש לדון מה לנו בזה. אולי יש נפק"מ אם רוצה אדם לדעת יום החודש.
אולי לא הניח שהוא סימן מפני שבדרך כלל יותר קל הוא לראות את החמה יורד מלראות הלבנה עולה. ותו"ת.
** ג. ותני שמואל -
מעניין שכשם ששוהה לבנה אחר חמה לרדת שוהה לעלות, שהרי, אין זמן לילה ויום שווים, ואז, לכאורה, נמצא שיש יותר מהלך באחד מהם. אם כן, לא ישווה זמן עלייה לזמן ירידה. ותו"ת.
** חזקה ביום -
לכאורה, יש עוד חידוש בזה, והוא שלאחריו (לאחר שעולה) חזקה לילה. משמע שסובר שזה פשוט.
** סייף - נחלק -
מים- גם היה אפשר לומר שנקט דם כיון שדרכו להיות על סייף. ויש לדון, שלכאורה, רק נקט סייף כיון שבו דרך להיות דם. ויש לדון מה רגיל להיות עליו מים. ואולי סכין. ויש לדון אם היה דרכם לרחוץ או לטבול סכינם כל כך. ואולי יכול להיות כוס. ויש לדון, שאולי צריך להיות חוד.
יש לדון מה אומר:
1. אולי כשחודו למטה, ויש טיפה שמנטף משם, gravity יחלק את הטיפה לשנים; חלק יפול, וחלק ישאר שם מחמת surface tension. זהו החלוקה. (וצריך להיות על חוד, אולי, כדי שלא יהיה כל כך surface tension.)
2. אולי כשחודו למטה, ועליו טיפת מים באמצע ממש (קצת קשה איך ייתן אותו אדם אותו כן. ויש לדון.), רואים כמה זמן הוא עד שנחלק לשנים, אחד שהולך לחד צד של הסייף, ואחד שהולך לצד אחר. אם כן, מובן למה נוקט סייף, שרק בזה מתחלק. ותו"ת.
** משתשקע
- מסוף- נראה שדיוקו הוא ממה שאומר, “משתשקע,” שמשמע שהוא מזמן שהוא שקוע, שמשמע שקוע כולו, ולא “משמשקע,” שהוא זמן של מעשה שיקוע, שיכול להיות בכל זמן שמשקע את עצמו (או בתחילה או בסוף).
** הרף
- קריצה- ראיתי בJastrow שאומר על לשון שהוא סגירה, וגם שהוא blinking. ויש לדון איזה הוא. רגילים בני אדם לומר השני.
** לא מסתברא -
מעניין שדולג מילת "אלא,” שמשנה כל הפריי"ז. ותו"ת.
לולי זה, היה נראה לומר שאמר כן בלשון שאלה: “אטו לא מסתבר…?”
** לא מסתברא
- משמע שהוא אחר סוף של ר"נ. לולי זה, משמעות גמרא הוא שהוא הרף עין האחרון. ותחשב.
** כל הרף -
אם כן, לכאורה, כל חלק ראשון יהיה ספק ספיקה (אולי הוא יום, ואף אם אינו אולי הוא בין השמשות, ואולי זה לילה. ויש לדון, שיש צד אחד שבו ליכא לספק. ותחשב.).
ודע שבדרך כלל קשה למה לא אומרים שיש חד ספק בכל זמן (אם הוא יום ולילה), ומה אומר שיש הרף עין שהוא ספק מיוחד של בין השמשות. ותחשב.
** אלא
- לא הבנתי מה אומר (ובפרט כיון שגמרא מקשה לקמן מהו הנפק”מ, לכאורה).
** ג: רבי יוסי -
מעניין שאומרים שרק ר"י אומר כן, שהרי אומר משנה ש"מודה ר"י.” צ"ל שרק מודה לדין שאמרו בציור אחר.
** על דעתך -
לא הבנתי זה.
** זהו בין השמשות -
לא הבנתי למה, כשבא אליהו, לא יפשוט כל ספק של בין השמשות.
גם קשה מה אומר שאי אפשר לאחד להמשך בתחילת הרף עין אחרון לעד סופו, שיכול להיות שמתחיל קצת לפניו, ומושך עד קצת לאחריו (לכאורה, אין צריך אף זה, שכל חלק זמן יכול להיחלק). ותחשב.
** אמר"א -
מוכיח מזה מפני שלמד משחר (כמו שהיה לומד מערב לשחר).
לכאורה, החולקים על זה ילמדו מקרא שהביא לפניו שאומר שעבדו מצאת…. יש לדון למה לא ילמד אלו מזה. ותחשב.
** ד. אמר’ יוסי בר בון -
לא הבנתי למה לא נדע. ותחשב. ולולי רש"י, היה נראה לומר שבאותו הזמן, הילוך של יום ולילה שווים, ואז אם עובי אחד של לילה ואחד של יום, יהיו שווים. ותחשב.
** אמר"י -
לא הבנתי, שרק מביא ברייתא לראיה, והקשה מקרא, ואז עדיין קשה מהו המקור. משמע שרק הקשה על הדין הידוע, ולא מהו מקורו. ותחשב.
** זה שעומד -
צריך ביאור למה מזכיר את זה כאן.
** עקב -
יש אומרים שצריך להתפלל כך, ויש אומרים שיכולים להתפלל כך. לולי כל זה, היה נראה לומר שלא חולקים, ורק אומר שכך צריך לפסוע לתפלה.
** קפיצים -
נוהגים העולם לפרש שזה knees, וכן מרפש רח"ק כאן. קשה, שיכול אדם לשבת בלי knees. לכאורה, היה נראה לומר שהוא waist. אולי כן משמע מר"ש סיריליאו.
** ד: וכמו השחר -
צריך ביאור איך דורשים כן, שיש הרבה מילים בין שני הקראים. ותחשב.
** איילת -
רגיל בני אדם לומר שהוא morning star. נמצא שהם טועים. על כל פנים, morning star יותר poetic ממה שהוא באמת. ותו"ת.
** בי רבי
- נראה שהוא שווה ל"ברבי" שמצאנו בבבלי.
** עובי -
נראה לפרש שהקרקע הוא כזה:
הקו הירוק נראה להיות עובי שמים, והקו האדום נראה להיות עובי קרקע. קשה, שלכאורה, משהאיר עד הנץ, לא עולה מכנגד קרקע עד כל עלייתו לרקיע. ותחשב.
** חוג -
מעניין שלא אומרים שגודל עובי תהום שווה לגודל עובי ארץ ושווה לגודל עובי רקיע. ותחשב.
** נהר -
לכאורה, משמע שהוא בעולם זה ממש. אם כן, קשה, שהוא אורך של כל העולם. אם כן, קשה איך יש מקום לדבר אחר.
** לא סוף
- נראה ששניהם שווים במה קורה, ורק דן אם משנה אף מזכיר שיש גודל זה (יותר ממנה) אף בצל.
** ה. תוך
- זה אומר שהוא באמצע, אבל לא הבנתי איך אומר שהאמצע הוא גודל שאר. ואולי הוא מפני שנתן אותו בכלל אחד עמהם. ותחשב.
** על רשב"ל -
קשה למה אין זה אף על ר"י. ואולי הוא על ר"י גם כן, אלא שכשאמרו, אמרו על רשב"ל. יש לדון למה. אולי סבר כר"ל.
** אשמורה
- נמצא שר"נ ורבי לא רק חולקים כמה אשמורות יש, אלא אף חולקים בביאור המשנה. ועיין בבבלי (ברכות (ג.)) שמביא ברייתא שבו פירש ר"א את דעתו בפירוש. אולי רבי ור"נ חולקים על זה. גם יש לומר שרבי אליעזר אמר בשם אחר שזמנו הוא עד סוף אשמורה ראשונה, וחולקים בדעת אותו אחר. יש לדון למה רש"י יניח כן. ותו"ת.
** סועד -
יש לדון מה זה אומר:
1. אולי רצה לומר שאם אכל מאד ביום שלפניו, היה צריך לישון יותר, שמי שאוכל ישן (כמו שאומר גמרא ביומא גבי כהן גדול). אולי רצה לומר שאם אכל עם מלכים ביום שלפניו, נמשכה סעודתו, ולא ישן עד זמן מאוחר.
2. אולי רצה לומר שאם אכל עם מלכים ביום שלאחריו, היה צריך יותר לישון, כדי שלא ינמנם כשיבואו.
** ה: דרך מלכים שחר -
יש לדון, שהרי קמים אחר שלש שעות. ואולי זה עדיין נקרא שחר (עיין גמרא בברכות שמבאר מתי נחשב שחר). גם יש לומר שיש מלכים כזה, ויש כזה.
** מילתיה -
באמצע- עיין שם, שיש שני לשונות, ופני משה רק אומר אחד מהם. ותו"ת.
** ו. כד הוה נחית -
לשון כל זה משמע שכך היה רגיל לעשות. מעניין שהיה צריך לעשות כן יותר מפעם אחת. ותחשב. ויש לדון אם באמת משמע כן (שאין אני רגיל כל כך בלשון ירושלמי).
** עד דהוה שקע
- משמע שרק לא אמר פסוקים אחריו. כן משמע גם כן ממימרה שאמר לפני כן (“אין אמר דברים”). לשון גמרא זה משמע שלא היה מפסיק בכלום. אולי כל הפסק רע, ודברים, שהם הפסק ביותר, הם יותר רעים, אבל אם יכול, טוב שלא להפסיק אף בשתיקה. ותו”ת.
** אמרו
- עיין בפירושו. קשה מהיכי תיתי שלא קאי על תפלה. עיין בר”ש סירליאו, שאומר פשט נאה בזה.
** שחרית -
גם, לכאורה, היה אפשר לומר שסבר שצריך לסמוך גאולה לתפלה בערבית. ותו"ת.
** אין פסול נוגע
- אחר כך- נראה שבא למעט אם כבר היה טריפה. ותחשב מהיכי תיתי. ודע שמצאנו שגמרא יחוש לשמא ימצא טריפה (כן אני חושב), ואם לא כפנ"מ, היה להם לסמוך קודם. ונראה שמקור של פני משה הוא שאם היה פסול קודם לכן, לא סמך קודם שחיטת קדשים, שהיה פסול. ותו"ת.
** ו: רבי מאיר -
ק"ק, שמשמע שרק לעצמו נהג כחכמים, אבל כאן פסק לבניו.
** ז. לית -
יש לדון למה יהיה פסח חלוק משאר קרבנות. ואולי הוא מפני שיש באכילתו שני מצוות- מצוות אכילת פסחים ומצות אכילת קרבן. ותו"ת.
** אחר חצות -
יש לדון מהו הראיה:
1. לא היו גוזרים בזה אם רצו שיאכלו אותם אז. ויש לדון, שאולי רצו שיאכלו אותם לפני כן, ולכן גזרו (שקשה להיות קרוב לדבר שמטמא ידיים), אבל אם לא אכלו, עדיין יאכל אותם.
2. אולי אי אפשר לאכול אותם, שיטמא את ידיהם. ק"ק, שיחייב לאכול בלי נגיעה בידיהם. ויש לדון אם אכילה גם כן יטמא את ידיו. ועדיין אולי יוכל לאכול את כולו בבת אחת.
** קדשים -
צריך ביאור למה מבאר את הגזירה רק כאן. ותו"ת.
** כל
- חמירי- עיין לקמן, שאין הענין מה שהוא יותר חמור. וע"ש.
** ז: אותה -
זה מעניין, שהיה נראה לומר שקאי על  הפתיל, כמה שאומרים החולקים.[fn:3]
** וראיתם -
אומר שקאי על מצווה. גם יש לומר שקאי על ציצית או תכלת.
** וכבר -
אין כל כך ראיה מכאן, שיכולים לקראותו אף לאחר זמן.
** רב זבדיה -
נמצא שהיה שמו רזביבזב"י.[fn:4]
** הלכה
- קשה מה נפק"מ יש, שבין כך ובין כך הוא כקורא בתורה. ויש לדון, שאולי זה עושה שהוא חיוב.
** ח. זמנה קבוע -
יש לדון,ש כיון שעסק ר"ש בתורה בכל זמן, בין כך ובין כך היה מפסיד אותו. ואולי חולק על מה שיאמר גמרא לקמן. ותחשב.
** לשיטתו -
משמע שהוא מחלקת, אבל ממאמרות שלהם, היה משמע שהוא מפני מציאות חלוקה (כמה למדו). ותחשב.
** פה -
הראיה הוא ממה שהיה דוחה את של תפלה לפה של ד"א.
** פה -
משמע שד"ת צריך פה. ותו"ת.
** הר סיני -
יש לדון למה צריך להיות אז, ולא בבריאה. אולי רק אז היה סיבה.
** ח: ד"א -
יש לדון מהו הצד הראשון. ותו"ת.
** האומר -
עובר על איסור דאו’, אבל כפי פירוש חכמים.
** ט. והגית -
עיין במה שבאר רח"ק. לולי זה, היה נראה לבאר שמקיים אותו כיון שסובר שהקרא קאי עליו (שלכן דורש השוויה עליו). ותחשב.
ונראה שמה שהקרא קאי עליו הוא או מחמת מש"א בבבלי בסוף מנחות לשיטת רבי שמעון ורבי יוסי, או מפני שמשמע חיוב שהוא ביום ובלילה קבוע. ותחשב.
** ה’ אחד -
יש רמב"ם ידוע שאומר ש"ה’ אחד" אומר שכולל כל מדותיו באחד. ירושלמי זה לא משמע כן. ותחשב. ויש לדון, שאולי רק דורש ממה שהלשון אומר שהוא אחד, אף שאין פירושו ממש כן. ותחשב.
** לא תגנב -
ק"ק, שבאמת, קאי על גזילת נפשות.
** למען ירבו -
יש לדון איך יודעים שלא קאי על שילוח הקן.
** ט: אלקים חיים -
לא רואים זה מ"אלקים מלך תמיד.
** ביתך -
נראה שלא מניחים שזה על גזל מפני שכבר נאמר, ועוד שאין גזילה בקרקע.
** ביתך
- קשה למה צריך לומר שזה יביא ליותר קנאה, ולמה אין קנאה זה די להיות אומר שהוא רע. ותחשב.
** אין
- זה רק טעם לברכות שלפניו (ובאמת, פנ"מ כ’ בפירוש בד"ה זאת שרק קאי על ברכות שלפניהם).
** יוצר -
ק"ק ל"ל אמר שאינו מברך כיון שכבר אמר עשרת הדברות, ואין צורך לברך. ותחשב.
** י. ארוכות -
אין זה ארוכות כשמשנתינו, שכאן רק אומר שיש בו הרבה מילים.
** מגונה -
צריך ביאור מה הראיה מכאן, שאולי זה קאי על סיפא. עיין ברח"ק שמוכיח נגד זה ממה שלא רק אמר כן על סיפא.
לולי לשון זה, היה נראה להביא דיחוי ממה שאף סיפא אומר, “אלו,” ולא מונה כל הברכות. ותחשב.
** מכרוע -
אין רואים כל כך מזה, שרק רואים שהיה כרוע בסוף ברכה אחרונה.
** כפיו -
ק"ק איך רואים מכאן שלא היה נע.
** עם הש"ץ -
מגמרא לקמן, נראה שגמרא בתחילה אמר לשון שמשמע שהוא בכל ברכה, ואז מפרש שהוא רק כשאומרים, “מודים,” שהוא בתחילת הברכה.
** י: סבר
- היה אפשר לומר שאף כל "סבר למימר" בש"ס הוא כך. ותו"ת.
** יא. שנכנס -
נמצא שסובר שהיה זקן ממש. יש לדון, אז, למה אמר "כשבעים.” אולי לא היה ממש בן שבעים שנה, אלא קרוב לו.
** אין אומרים
- לקמן, מרש"י ד"ה דהוא וד"ה אמרין מבואר נגד מש"א כאן, שאינו שאחר השם אומר קרא, אלא שלפני השם (לפני הברוך) אומר קרא.
** יא: אלו אבותם -
יש להעיר שמדרש רבה אומר (והובא ברש"י) שה’ קרא ליעקב בשמו (על הקרא "ויקרא שמו יעקב”).
** תמן אמרין -
נראה שחולקים בשני דברים:
1. חולקים אם יתחיל, והוא אם הלכה כראב"ע. רבנן דתמן סוברים שאין הלכה כראב"ע[fn:5], ושל הכא סוברים שהלכה כמותו (שהרי, מביא ממשנה שאומר כמותו להוכיח בשיטתם).
2. חולקים מהו הדין אם התחיל, אף אף יגמור.
יש לדון עד כמה מתחיל לרבנן דכאן. יש שמשתמשים בלשון של "פסוק אחד.” לולי זה, היה נראה שהוא עד פרשת יציאת מצרים, שמבואר בפני משה שעל זה דן רבנן של התם (ולכן אומרים שיגמור). ותחשב.
אם כן, קשה למה לא יאמר יצ"מ שבקרא, ולמה יאמר לשון של עצמו. ויש לומר שהוא לשון יותר טוב (יותר בהיר או כדומה), אלא שאגב מה שצריך לומר ציצית, תיקנו רבנן לומר אותו פרשה. כאן, שא"צ, לא תקנו כן. ויל"ד
** מחמיר -
ק"ק, שאף יש קולא (שלא יתחיל). ויש לומר שר"ל שסבר כן כבבני בבל, שסבר שיתחלו. ותחשב.
** יאשיהו -
יש להעיר שקרא זה לא נאמר עליו בדווקא, אלא נאמר שיבוא לאחר זמן רב בן כזה. ותחשב.
** אלו מלכיות -
ק"ק, שמלעיל משמע שמלכיות הם העיקר. ואולי הם בזמנים שונים.
** צרה -
לכאורה, הוא מפני שהגאולה, אז, הוא יותר חזק. לולי זה, היה אפשר לומר שגם תלוי בגודל הנס, ולא רק בכמה נצרך הנס. ותחשב.
** צריך
- חסד- שמעתי מרש"ש שביאר חילוק בין זכירה וסיפור של יצ"מ לומר שהראשון הוא מפני שנקבע אמונה בלבו, והשני הוא הודאה. אם כן, ק"ק כאן. ואולי זה רק חיוב דרבנן. ותחשב.
** יב. אם כוון לבו -
לכאורה, שני הצדדים שאומר לצד שמצוות אין צריכים כוונה הם:
1. אף שאינו צריך כוונה לקיום, צריך כוונה לאותו מעשה.
2. אם אינו מכוון, אולי לא עושה המעשה הנכונה.
צד ראשון מעניין.
** התיבון -
יש להקשות על זה:
1. קשה למה צריך לכוון, שכבר התחיל בכוונה.
2. קשה מה אומר שצריך לכוון בשלש פרשיות, שאין זה שייך לדיחוי שאומר.
3. קשה למה שואל גמרא על זה; הרי אמרו, ולמה לא יהיה נכון. זה אומר שבדרך כלל, לא מצאנו שישאל גמרא על מימרת אמורא אם הוא נכון או לא.
נראה שאותו מימרא שאומר בתחילת דיחויו אומר שאין 1 קשה (ועדיין צריך ביאור), אלא צריך כוונה בשלש פרשיות. אז, נמצא שהוא שייך, ו2 מתורץ. על זה שואל אם מה שאומר הוא דווקא, או רק מכוון לומר שבוודאי צריך לכוון. אז, אף מתורץ 3. ותחשב על כל זה.
** יב: ג פסוקים -
עיין לעיל (פ”א הלכה ב), שפני משה אמר את זה בביאור חילוק בכוונת ק"ש ותפילה. לכאורה, שם החילוק הוא אם צריך לכוון בפירוש המילים. ויש לדון, שבברכה ראשונה צריך לכוון. גם גמרא זה, כמובן, לא מיירי בכוונת מילים. אז, נראה שצריך לומר בכוונה לצאת וכדומה. מעניין שא"צ זה בתפלה. וצריך לחשוב על כל זה.
** רב חונא -
יש לדון אם רצה לומר שזה אמר בשם זה בשם זה…, או שכולם אמרו בשם שמואל.
** שמים וארץ -
אם ד’ רוחות אינם כבר נכללים בשמים וארץ, צריך ביאור מה אומרים.
** שלש ראשונות -
צריך ביאור למה רק מקשה שמרבי רואים שאין צריכים לכוון; גם אומר שאין צריכים לומר. ויש לומר שאין הכי נמי, אלא מקשה מכוונה כיון שכן אמר גבי שלש ראשונות. ותחשב.
ויש להעיר שאותו דין שיוצא ממה שאומר רבי מעניין, שלכאורה, נמצא שאין חיוב לומר דבר חוץ משלש קראי ראשונים, ולהזכיר יציאת מצרים.
זה נוגע לענין מה צריך לומר, ואולי אף לענין זמן שנחשב הפסק. ויש לדון, שגמרא רק שואל על ברכות, ולא מזכיר איזה חלק מק"ש צריך להיות. ותחשב על זה. ועיין לקמן בע"ה בד"ה ק"ש.
** בטוב -
יש לדון אם אומר שני ברכות:
1. יחיו שנים ארוכים.
2. אותם שנים יהיו מלאים טוב.
או ברכה אחת, והוא שיהיו שנותיו בטוב (כמו כן מצאנו בשבת (קה).
** בעי -
זה מענייין מאד; וצריך לחשוב עליו. ויש לדון מה יקרה, שהתוקע, אולי, אינו כשום אחד מהם. יש לדון איזה יוציא. ותחשב על זה.
** כדי לגמור שליש -
קשה למה אינו אומר מחצה.
** ק"ש
- אפילו- מעניין שזה "אפילו.” ותחשב. זה קשה ביותר אם אינו זמן של כל ק"ש, אלא רק של מה שצריך לומר.
** מתנמנם -
זה, לכאורה, היתר גדול. קשה למה אינו יותר ידוע. יש להעיר שבסייעתא דשמיא, אף שאינו ידוע, ה’ עשה שהוא כבר נהוג.
** מתנמתם -
יש לדון אם קאי על הפסיק כדי כולו או לא. ותחשב.
** יג. כדי דיבור -
יש לדון למה זה יהני. וצריך לעיין ברן בנדרים בענין זה. ואולי דיני כדי דיבור הוא סיבה לזה (נחשב אותו זמן מפני שיש בו כמה דינים של חד זמן).
** ר"א -
יש לציין למה שאומר גמרא בכ"מ "חזא ביה בישות.”
** מהו מעביר -
צריך ביאור מהו הצד שצריך להעביר. ונראה שרק אמר לו כן כדי שישיב. ותו"ת.
** יג: כבוד -
יש לדון מהיכי תיתי שכבוד רצה לומר כבוד של חיוב. ותחשב.
** נשמעינא -
אם לא גורסים כפני משה, צריך ביאור.
** מתפלל -
צריך ביאור למה מזכיר זה, שלכאורה, הענין הוא רק קבלת מלכות שמים עם תפילין, וזה ק"ש. ותחשב.
** מקום טהור -
יש לדון למה צריך זה. ואולי הוא כדי שלא יהיה לועג לרש.
** יד: כמין פקדון -
לשון זה מעניין, שאם לובש אותו כדין, ורק מכוון שלא לצאת, קשה למה בתפילין של ראש היה צריך לתת אותו לצדדים (ואולי לא היה צריך, אלא כך עשה, לשום סיבה, ואמר את זה לראיה שכיוון שלא לצאת). אם רצה לומר שנתן אותו במקום שאינו יוצא, אז קשה למה צריך מחשבתו לפקדון. אם אינו חושב לפקדון, ורק אומר שהוא כמו פקדון כיון שאינו במקום הנכון, קשה למה מזכיר אותו כלל, ולמה רק בשל יד.
** תרין -
יש לדון אם זה משמע שענין אסמכתא הוא כרמב"ם ולא כריטב"א. ותחשב.
** מיחו -
קשה למה ימחו, שאינו רע להם לעשות כן. שו"ר שאולי יש בעיה שיבואו לומר שחייבות.
** טו. שני פעמים -
קשה, אטו לא ילך לבית הכסא על כל פנים זמן אחד ביום. ואולי לא. ועיין בגמרא תמיד (ומק"א) שאומר לפנות בבקר ובערב כדי שלא יצטרך ללכת לבית הכסא כל היום.
** טו: יעשה צרכיו -
עיין במראה הפנים שבאר שזה אסור מפני שהוא קלות ראש. יש לדון איזה קלות ראש הוא. יותר היה נראה לומר שהוא מפני בזיון המתים.
** לך
- מעניין שצריך מי שיאמר להם. באמת, צריך ביאור איך אומר להם.
** קרא
- שני תיבות באות אחת- לולי זה, היה נראה לומר שהוא מפני שאז עושה שני תיבות לתיבה אחת. ותחשב.
** ארצנו -
לא הבנתי למה צריך ציור לזה; לכאורה, אינו כל כך קשה לצייר.
** בית אלהים -
רצה לומר, דין של מעלה (שלכן מזכיר אחר כן "מקורך ברוך." ויש לדון, שאולי הם רק דומים במה ששניהם דינים. ותחשב.
** עת ללדת -
זה משמע כמה שאמר רש"ש (חושב אני שהוא בבא מציעא) מכמו זה שאין גלגולים.[fn:6]
** טז.
הלכה כסתמא- משמע שאף רב סובר שהלכה כסתם משנה. ועיין בשיח שי בב"מ.
** אר"י
- זה מעניין. יש לדון אם זה רב יוסף של הבבלי.
** טז: יוצר -
מעניין שצריך שום דקדוק לומר המילה נכונה.
** אם היה
- לולי זה, היה נראה לומר שאומר שאם היה לשונו כבר ידוע (שרבים אומרים כן), אין בעיה. חושב אני שיש מפרשים על ש"ס שלנו שכתבו כן. ותחשב.
** יז. לימות המשיח -
זה אומר, אז, זמן של כל דברים אלו (ימות המשיח, מלחמת גוג ומגוג, ועולם הבא).
** אף -
כוונת פני משה לומר שאין להקשות איך אומרים ברכות האמצעיות קודם האחרונות, שהרי אמצעיות בלשון עתיד נאמרו, שבכללם יש לשון עבר, והוא שאומר ליתן דעת, כמו שנתן כבר…. ותחשב.
** הוא צמח
- מעניין שזה די לעשות שני שמות אחד.
** שמנה -
ואם תאמר נאמר שהוא מפני אותו קרא שבהיא. ויש לומר שכיון שאינו מיד אחריו (שגאולה מפסיק), אינו סיבה נכונה. ותחשב.
** יז: ה’ עוז -
נמצא שאין עוז מה שנתן, אלא הוא אופן נתינתו. ותו"ת.
** שרי תורך -
לכאורה, רצה לומר שיש לשבות מעבודה כדי לאבל. גם מעניין שאומר לו שא"צ להתאבל מפני לידת משיח, אף שלא גאל עדיין.
** אנא מן יומי
- עבמש"כ. קשה למה, אם הרהרו בתורה, הסיחו דעתם. ונראה שהוא מפני שכוונו להתפלל, אבל להם הסיח לחשוב בדברי תורה. אם כן, מפני סתירה זה של דעתם, היה יותר קל להסיח. ותחשב.
** בעי מכוונא -
אף בזמן זה לא כיוון, ואז קשה מה ייחד זמן זה. משמע שרק אז אף ניסה. זה, כמובן, קשה. ואולי רצה לומר שפעם אחת כשבעי, כמו שהיה בעי בכל זמן, קרה כן לו. גם יש לומר שהיה אז יותר קרוב לכוון (תחשב). ותו"ת.
** יח. נדבך -
פסוק ראשון- לעיל אמר שלש פסוקים. עיין לעיל שבארנו שלכאורה, זה קאי על כוונה לצאת, ולא כוונת המילים. ותחשב.
טרחתו- עיין בברכות (טז.), שרש"י לא מפרש כן.
** יט. מה בינה -
מניח שהאיסור יהיה הפתח, ולא חבורת דם. ועיין בכתובות.
** יט: דלמא תרין -
ק"ק למה ישאל לשניהם, ובפרט אחר שאם החמיר לו אחד, אי אפשר לשאול לשני ולהקל מפיו.
** רבנן דהכא -
לכאורה, מה שאומר, “אי רבנן דדרומא" הוא תשובה לשאלה, שאומר שהוא צריך להיות לרבנו דכאן, שאי לשל התם….
** קיבל -
יש לדון למה נחמו לו ושוב שאלו. אולי אמרו להם לנחם. גם יש לומר שיש נחמו ויש שאלו. ותחשב.
** כ. כיני -
עדיין צריך ביאור למה שנה להם כך.
** דודי -
לכאורה, זה לא שייך למה שאמר שהיה חביב לו כבן. אולי רצה לומר שכיון שהיה כל כך חביב לו, היה נותן לו הספד טוב.
** והתליעו -
אין זה נחמה כל כך טוב, שאומר שהיה מתליע אם היה קיים, שלא היה יכול לעמוד במה שיבוא. ואולי רצה לומר שרצה למנוע ממנו שכר, ולא שרצה למנוע ממנו עבירה. ואין כל ההערה קשה כל כך. ותחשב.
** עשרים -
אם מניח שהתחיל בשעה שמשנה באבות אומר להתחיל, נדע כמה שנים חי (ועיין בב"ב שמבואר שלא היו לעולם מתחילים כך, והצריכו תקנה מכהן גדול. ואולי משנה מזכיר דין שלאחר תקנה, ואז יש ללמוד ממנו.)
גם יודעים שני חיי ריב"ז, ר"ע, רבא (או רבה), ואביי.
** כ: ר’ לוי -
ע’ בר"ש סיריליאו שאומר שזה לוי. מקורו הוא מגמרא לעיל שאומר שהראה קידה לרבי. גמרא אומר כן על לוי.
** אבוה -
הספידו אבוה דשמואל, אף שהיה בבלי, כיון שמת לוי בבבל, שירד לשם, כמו שאומר גמרא בשבת (פרק במה מדליקים).
** ככל אדם -
יש לדון אם רצה לומר שכנגדו היה כאילו לא היה אדם, או שרק רוצה להראות שיכול להיות דבר אחד שהוא כל כך יקר לאדם.
** אתא
- אם חשב שר"י לא יבין, קשה מה הנאה בא לו בזה. אם חשב שיבין, יאמר לו בפירוש. ואולי רצה לומר לאחר זמן שחשב שהבין.
** בר נש -
נקרא אשת אביו כיון ששכינה גלה עם בני ישראל. ותחשב.
ונראה שאולי זה מקור או סמך לענין של Motherland. ותו"ת.
** כא. דר"ג -
נמצא שפוסק להלכה שאין אומרים שכל המקיים דבר שאינו מצווה בו נקרא הדיוט. זה מעניין. גם יש ללמוד מכך איזה פטורים נכנס בכלל מאמר זה, שפשוט לגמרא שאין לחלק בין שני פטורים אלו. ותחשב.
** כב. א"ר בון -
שייכי- נראה שאומר שמצוות ק"ש שייך למצוות תפילין (או להיפך) שצריך ללבוש תפילין בשעה שקורא את שמע. ותו"ת.
** כבוד -
יש לדון למה זה מתיר לו שלא לעשות מצווה. ואולי הוא כשהוא טרוד מחמת מחשבה (יש לדון בזה, שאין לו מה לעשות, ויהיה כחתן בשבת; ועיין בכתובות), ורק דן אם יכול לקרוא אם רוצה.
** כב: דרגש -
נראה שלמעשה הוא שתוחבים את החבל בעץ, אבל מטה הוא שמסרגים את החבלים בין נקבים שבתוך העץ. ותו"ת.
** כפיפה -
נמצא מגמרא זה שלא רק כופים, אלא צריך אף לישון על גבי מיטות אלו. ותחשב. לולי זה, היה אפשר לומר שישן על קרקע. ויש לדון, שאולי יכול, אלא שמסתמא יישן על מטה, שהוא יותר קל. ותחשב.
** ולא מיסב -
יש לדון אם זה קאי על כל אונן או רק על אוכל בבית של מתו.
** כג. ר"י בריה -
יש לציין לגמרא סנהדרין (בבלי) שאומר שלא נברא יין אלא לנחם אבלים ולפרוע לרשעים. נראה שלכן מתחילה לא חשו על שהיו משתכרים, אבל אחר כך השתכרו יותר מדאי. ותחשב.
** כג. אבא -
לכאורה, רצה לומר רב חייא בר אבא, שהיה אביו, ולא אבא אבי אביו, שלא היה קורא אותו בשמו. ותחשב.
** אבא -
לכאורה, צריך לומר שלא היה דרך אחר, על פי מש"א פני משה.
** כד. קברו -
פרשה- משמע שפרשה ראשונה הוא החיוב. לעיל אמר ששלש פסוקים הראשונים חיוב.
** כד: מעשה -
לכאורה, מביא מעשה לחלוק. קשה, שעל כגון זה גמרא מקשה "מעשה לסתור.”
** כבוד -
לכאורה, שינה מפני שלפני כן, לא היו רואים פני אבל ולא רואים, אלא כיון שכולם עברו, כולם היו רואים פני האבל. יש לדון אם דין כבוד שינה. ממה שלא מזכירו, משמע ששינה (אבל יש לומר שרק אומר הדין שנתחדש). ותחשב.
יש לדון למה ישנה.
** כה. קטן -
עיין במה שפירש  למה פטור מק"ש. לולי זה, היה נראה לומר שפטור מקריאת שמע כיון שאין כל כך צורך לומר אותו בלי תפילין, שלא יעשה כן כשיגדיל. ועיין בפ"מ, שאומר לשון של תלייה של זה בזה, אבל לא ממשיך לומר כמש"כ, אלא שאינו עם אביו באותו זמן. וצריך ביאור.
** מזוזה -
פני משה אומר סיבה חלוקה ממה שמבאר בגמרא. וצריך ביאור. ועיין בחרדים שמרכיב שני הפשטים (לומר כפשט ראשון של פני משה). ותחשב.
** כה: סוכה -
מעניין שאומרים שיכולים לקיים מצוותו בכל זמן, שלא יכול לאכול בכל זמן, שיהיה אכילה גסה, ולא יכול לישון בכל זמן. ואולי יכול לאכול, ושוב לישון, ושוב לאכול…. גם יש לומר שלא צריך אכילה וכדומה, אלא אף דברים שאינו חייב בהם, אבל מקיים מצווה, כגון ישיבה שם.
גם יש להעיר שאין הענין שכל זמן ראוי למצווה, שאף תלמוד תורה כן, אלא שאפשר לעשותו בכל הזמן, אבל ת"ת מוכרח בו הפסק. ותו"ת.
** כו. בעלי קריין -
לכאורה, אין צורך למילה שנית להיות רבים, שיש לומר שהם בעלי קרי. ותחשב.
** מהו מהרהר
- יש לדון מה אומר כשאומר "רק בק"ש, שרק פסוק ראשון דאורייתא":
1. אולי אומר שבק"ש רק מהרהר שאר חוץ מקרא ראשון, אבל זה אומר. הוה אמינא שמהרהר אותו רק כיון שאינו דאו’. מחדש שאף ברכת המזון, שהוא דאורייתא מהרהר.
על זה, צריך ביאור:
  1. למה שאר ק"ש חלוק משאר אמירות דרבנן. ואולי הוא מפני שהוא חלק ממצות קריאת שמע. ותחשב מה זה אומר. לכאורה, הוא שכיון שתקנו רבנן לומר אותו עם ק"ש, נתנו לו דיני ק"ש.
  2. למה ק"ש דאו’ חלוק מברכת המזון. ואולי זה מפני שקריאת שמע יש קבלת עול מלכות שמים.
1. אולי אומר שבק"ש רק מהרהר קרא ראשון. הוה אמינא שרק אותו מהרהרים כיון שהוא רק קרא אחד. יש לדון מה לנו בזה:
  1. אולי הוא אומר שיש פחות איסור- כיון שיש פחות מילים- אבל בשניהם מקיים מצווה אחת. אז, אולי יש להרהר רק הכי פחות, שלא עובר על כל כך. ותחשב.
  2. אולי הוא אומר שאין להררהר בדבר גדול, שקשה לזכור מקומו. ויש לדון אם אז יאמר אותו או אז לא יהרהר (שאין טוב בא ממנה בוודאי).
** כו: צינה -
לולי זה, היה נראה לפרש שצינה הוא שלא באים עליהם זכרים, כמו שאומר בבלי בב"ב על לוויתן. ונראה ששם אומר שאין תאווה, אבל כאן רק אומר שאין ביאה.
** צינה -
מעניין שלא חשו נשים לזה (שאם רוצות להיבעל, צריכות טבילה לנדותם). ואולי היו טובלות בין כך ובין כך כדי להיטהר. זה אפשר רק אם אומרים שחשו לטומאה אז.
** עוברים -
מעניין שהוצרכו לשהות למצוא מקווה; בדרך כלל, יעברו ושוב ימצאו מקווה, שבדרך כלל, מקוויות מצויות, שהרי יש נשים. ותחשב.
** ולא כבהמה -
זה מראה מקום.
** טיטס -
יש גירסות חלוקות בזה. מעניין שיהיה אדם ששמו טיטס. אולי היה גוי, והיה נולד מגוי. יש לדון, שלא מזכיר שם של אביו של רב מרי בר רחל וכדומה.
** הגדה
- עיין במה שפירש. רש"י כ’ על מדרש שהוא מפני שיש בו כמה קראי.
עיין במש"כ רש"י גם על ברכות התורה כעין זה.
** כתחילה -
יש להעיר ששם אף ראו את הקולות.
** כז. צבור -
צריך ביאור למה מתפלל בצבור חלוק. אולי הוא ש”ץ, ואינו כבוד הצבור. ותחשב.
** תיפתר -
קשה, שפני משה לעיל אמר שמשנה רק קאי על עביט של מי רגלים וצואה. ותחשב.
** כז: נעוריו -
קשה למה מביא דרשה של זה, שבלי דרשה, היה אומר שכשהוא נער לבו רע, וזה מה שאומר גמרא. ותחשב.
** ננער -
קשה איך זה ראייה למה שאומר גמרא, שלפי זה יתחיל קודם שיכול לאכול כזית דגן. ותחשב.
ויש שמפרשים שמקשה מזה קושיה (רידב”ז). זה גם יתרץ קושיה שלפני כן, אבל פני משה לא כותב כן.
ויש להעיר שאם היינו אומרים כן, היה המשך טוב, שאומר שהוא בקטן, ומפרש שתלוי במחשבות, ומקשה. כיון שאומר שאינו תלוי במחשבות, יכול לומר אחר כך שהוא אף בבהמה שאין לו מחשבות רעות. ותחשב.
לפנ”מ, צריך לומר שאף שאין לבהמה מחשבות רעות (לכאורה), יש בעיה אחרת שעושה שצריך להרחיק מצואתו. ותחשב.
** מפני -
מעניין שאומר כן רק במי רגלים, ולא בצואה. יש לדון אם הוא דווקא או לא (שאולי הזכיר רק אחד, והוא הדין לשאר). אם נאמר שהוא דווקא, נראה שאולי פירש כן כיון שהיה קשה לו מפני מה שהערנו לעיל גבי צואת חמור.
** מי רגלים -
חשבתי, אגב, שקשה למה לא מנסה גמרא להוכיח מזה על ביאור לשון רגלים (חושב אני שדיון הגמרא הוא ביבמות בפרק מצוות חליצה). שוב נראה לי שאין בעיה בזה כיון שיש רק מים אחד היוצאים מן המים. אם כן, פשוט על מה קאי; ואין להביא ראיה מזה אז. ותחשב.
** תני (שני)
- יש לדון למה מזכיר שהוא ברייתא. ונראה שהוא נותן מקורו, ומקורו הוא בברייתא שאינו תוספתא או מדרש או כדומה, והוא ברייתא שאין לנו חוץ מבגמרא). ותחשב.
** שעיניו -
קאי על מה שמוציא הריח, אף שכשדן בלאחריו קאי על הרוח עצמו. ותחשב.
** ר’ לייא -
אוהבים אנו את הלשון של “רב לייא וחבריא” שאמרו “מיליא בפונדקיא.” ותו"ת.
** שלפני -
לא ידעתי מה בא ת”ק למעט מזה, שאם ממעט מלאחרי המטה, לומר שאם יש חציצה אין צריך זה, אם כן הוא רשב”ג. אז, לא בא למעט זה, לכאורה. אז, קשה מהו ממעט. ותחשב.
** כח. שייף -
אם נאמר שהיה מתפלל (כן משמע מגמרא, אבל יש מפרשים שלא כ’ כן), קשה איך שף בתוך תפלה, שצריך לדבק רגליו. אולי זה דוחה אותו ענין. ותחשב.
היה אפשר לומר שלא שף ברגלו, אלא בידו כשמשתחווה או כדומה, אבל פני משה כתב שהוא ברגליו. ותחשב.
** והטיל -
קשה, שהוא ספק דרבנן. ואולי כיון שכבר הוחזק להיות אסור (אף שהוא מסיבה שלא ישאר עדיין) יותר מחמירים. ותחשב.
** כט. עד כדון -
ק"ק ל"ל אמר "עד כדון באשה… .” ותחשב.
** נשמענא מן הדא -
צריך ביאור מהו הראייה מן המשנה (שלכאורה, הראיה הוא רק מה שגמרא לא סבר שיש לחלק). ותחשב.
והיה נראה אולי לגרוס "הדא היא הדא,” ולא "היא הדא היא הדא,” ואומר שמדייק ממה שרק אמר כן גבי אשה, ואומר שרק זה הוא זה, ולא איש הוא זה, שאין לאיש אותו דין.
** תפלת
- משמע שאין שום חיוב לתת את האימורים וכדומה באש, ולא רק שאינו מעכב הרצאת הקרבן. ותחשב אם זה נכון.
** כט: פלח -
קשה איך יודעים שזה תפלה, שרק אומר שיש דבר שהוא עבודה. ותחשב. ואולי ידע שהוא עבודה, וזה רק מוכיח שהוא חיוב.
** ל. בארבע -
חושב אני שבבלי מניח שזה היה בתחילת שלש. יש לדון אם חולקים מתי היה קרא זה או מה אומר רבי יהודה.
** טליים
- מעניין ששהו מפני שרצו הרגלם.
** וקפץ -
בבלי אומר ארבע מאה פרסי.
** קפץ
- עיין במה שכתב. מעננין. גם יש להעיר שאומר שעשה כן מא"י. יש לדון אם אומר שהתחיל בא"י (ולא נראה כן, שזה, לכאורה, כבר פשוט), או שהלך חוץ לא"י אותו הולך. ותו"ת.
** וחרבו -
גמרא רק אומר כן בשני מלכים שהיו לוחמים, וצריך לומר שנתגלגל הדבר עד שנחרב הבית. ותחשב.
** והוא
- משמע שלא היו מנתחים אותו קודם (או שהחזירו לאותו מקום[fn:7]).
** והוא
- מעניין שיש מעלה בידיעת איזה הוא קרבן הוא מה.
** ל: פתר לה -
קשה איך דן בלפני זמן מנחה, שאז לא יצא חובת מנחה. נראה שאולי רצה לומר שאז לא ישהה למנחה.
** פתר
- כאן אומר שזמן מנחה הוא שש ומחצה. עיין לקמן בפנ"מ שאומר שהוא שש.
** פתר
- קשה מה אומר שלא בא זמן מנחה ולא זמן מוסף, שכבר בא זמן מנחה בשש.
** ויהא -
קשה, שכבר אמר שכן עשה. ונראה שהראשון נאמר על של בוקר (ונראה שלכן מעורר כן פני משה), ושני נאמר על של בין הארבעים, שהיה יותר קשה, שמא לא יתפלל בזמן. אז, זה לא עשה, אבל רצה שיהיה כל כך טוב לשמור א"ע מאיסור עד שאף זה יוכל לעשות. ותחשב.
שמעתי שיש מפרש על ירושלמי (אולי רח"ק) שאומר כן.
** לא הוקשה
- נמצא שלומד מזמן שחיטה, ולא מזמן הקרבה. מעניין שלא נלמד מן הזמן הכי מוקדם שאפשר להיות. ותחשב.
** ושמשא
- משמע שהלכו בתר זמן א"י. עיין ברח"ק, שעושה שאין זה כל כך איקסייטינ"ג כמו שמשמע. ותחשב.
** לא. בנעילת שערי -
בתחלתה- רצה לומר בתחילת הלילה, ולא בתחילת יום הכיפורים. וקשה איך נקרא תפלת יום הכיפורים כיון שנתפלל אחריו. ותחשב.
** על ידי שריבתה -
יש לדון מה היה לה לעשות:
1. היה לה לומר שתתן לו לה’, ולא היה לה להוסיף "לעולם.”
2. היה לה להתפלל בלי התנאי הזה.
** עולם -
צריך ביאור למה זה נקרא עולם, שרק לא יכול לעבוד עוד אז. גם צריך יבוא רלמה מונים שנים שלו לפני כן (שלא מתחיל לעבוד מתחילת ימיו), אבל לא לאחר מכן. ותחשב.
עיין בפני משה שמשמע שכל ענין זה הובא לאו דווקא. לא הבנתי, שהרי לכאורה זה ההוכחה שתפלה שלה גרמה לשמואל שימות בן חמישים ושנים שנה. ותחשב.
ואם תאמר למה לא רק עשה ה’ שיצא מבית המקדש אחר חמישים שנה. ויש לומר שיש גם משמעות אחר של לעולם, והוא "לכל זמן [שאפשר],” ולא רצה להפקיע מאותו משמעות.
** האיך הוא מזכיר של הבדלה -
קשה, שאין הבדלה מעכב. ואולי צריך להיות "ראוי לבילה.”
** בצומא רבא -
לעיל אמר כן לענין מנחה. ואולי לפעמים עשה כך ולפעמים עשה כך.
** לא: קל הקלו -
לא הבנתי למה זה יעשה שידלגו על חיוב שמונה עשרה ברכות ולא שידלגו על חיוב הבדלה. ותחשב.
** לב. יצחק סחורה -
מעניין שכל אדם שואל למי ששמו כשמו.
** משכני -
יש לדון מה מועיל בזה שמראה לו, שלא מוכיח כלום. ואולי הוא שייך למה שאמר גמרא פסחים (פרק מקום שנהגו) שיאכל ספיחי ספוג רק לפניו. ותחשב.
** ולא צריך -
לשון "צורך" מעניין. ותחשב.
** נתפלל -
לכאורה, רצה לומר "התפלל.”
** ועוד דהא -
זה רק ראייה לענין ראשון.
** שכן מוסיפים -
משמע שהוספה על שבת עושה שהוא לילה ממש. יש בזה שני חידושים:
1. משנה את הזמן.
2. משנה הזמן להיות לילה, ולא רק להיות שבת.
ויש לדון אם מה שעושה דיני שבת סיבה שהוא שבת, או שיש לו כוח לעשות שהוא שבת מסיבה אחרת.
** לב: פוטרת -
ואם תאמר מה לנו אם פוטרה; הרי הוא רשות. יש לומר שאז אין סיבה עוד להתפלל. ותחשב. ולא הבנתי, באמת, תלייה זה. ותחשב.
** בן שש -
בבבלי אומר שהיה בן שמונה עשר. עיין בגירסאות שבעוז והדר. יש שגורסים שהיה בן שלש עשרה. אם כן, לכאורה, רק ידעו מחזקה שהיה גדול. מעניין שלא חשו להעמיד קטן. ואולי כיון שבאו סימנים ניכרים אלו, לא חשו. לא נהירא, שהרי עשו אותו נשיא קודם שבאו סימן זה.
** שמונים -
הוסיפו- יש לדון אם רצה לומר שכך היו או שכך הוסיפו. לשון גמרא משמע שכך היו. אם כן, פני משה רק אומר שהוסיפו עד שכך היו. ותו"ת.
** לג. הודייה -
נראה שכתיבה כזה הוא המקור לבני אדם שאומרים "אלפ"ים ו"עיינ"ים כאילו יש "יוד"ים שם, כמו "רייב"ד" במקום "ראב"ד" וכדומה.
** טרטיות -
יש לדון אם בכלל זה הוא ספורט"ס גיימ"ז. יש לדון, שעושים שם מיני שחוק, אבל אינו טיאט"ר וקרקס ממש. ויש לדון מה עושה אלו, שהרי רואים בני אדם עושים דברים מופלגים, ואז אולי נקרא כן.
אז, יש להסתפק במי שלומד בתוך ספורט"ס גיי"ם, אם יאמר תפלה זה.
** שלש תפלות
- עיין במה שבאר. דחוק הוא, אבל לכאורה, צריך לזה, שהרי הוא ארבע תפלות. ויש לדון, שאולי קנאה ושנאה נחשבים כאחד מפני שהם דומים (בלשונם ובתוכנם).
** מלבינו -
אם כולל הכל בזה, שאומר לשון רבים, קשה למה צריך לכופלו, שבכלל "שנאתנו על לב אדם" הוא שנאת אדם בלבנו, שהוא בכלל "שנאתנו" והאומר הוא בכלל "כל אדם.” ויש לדון, שאולי לשון רבים נאמר על עצמו, כמו שיש שמתמשים כן.
** איסבלוסטיקא -
זה שם מעניין, ואינו שם שנמצא בדרך כלל ביהודים.
** לג: תשע עשרה -
יש גורסים כאן "יז.” אם אומר תשע עשרה, הוא נגד השיטות שהביאו לעיל שהיו מתפללים רק שמנה עשרה ברכות.
** אית לך
- אינם נהגם- צריך ביאור מה זה אומר. אולי יש לגרוס "אינם נמחקים.” צריך לעיין שם בשבועות אם זה אמת.
** ה’ ידין -
ע"ש שר"ה הוא יום הדין. יל"ד אם צ’ לזה, שגם נפקדה אז.
** שמי -
אף שבקרא אחר אמר "עליו,” אינו מזכיר אותו עם שאר האבות. ותחשב.
** והתני כולל -
עיין בחרדים שמבאר שיש אחד כנגד כל מה שכולל.
** משמע מפ"מ
שהוסיפו ברכת מינים להגיע לשמנה עשרה. ואפשר שרק אומר שלכן הוסיפו אותו, ולא רק כללו. ותחשב.
** לה. אזכיר -
מפרשים (ר"י סיריליאו) ביארו שדורשים אותו כאילו אמר "אזכר"- אהיה נזכר, שהוא המקום שה’ בדרך כלל נזכר שם, שהוא בית הכנסת.
** השתחווה
- עיין בבבלי שדורש את זה מן הקרא שאומר שהתפלל אברהם במקום שהיה מתפלל. אז, מביא ראיה מדבר שנכתב באופן שבו אומר הירושלמי כאן שאי אפשר להתפלל שם. נראה שאולי יש לדון למה יש טוב בהיות לו מקום קבוע להתפלל:
1. אולי טוב להתפלל במקום שקובע את עצמו להתפלל שם לעולם.
2. אולי טוב להתפלל במקום שכבר היה מתפלל.
נראה שסבר ירושלמי כצד ראשון. אז, מביא ראיה מקרא שאומר לשון עתיד. נראה שבבלי אומר צד שני, ואז הביא ראיה מקרא שאמר כלשון עבר.
נראה שהסיבה שלא סבר ירושלמי כצד שני הוא שסבר שאם כן לא יחייב (או לא יהיה ענין) בפעם ראשון. אז, צריך לומר שיש חיוב להתפלל במקום שיקבע את עצמו.
הבבלי ידחה או שאין הכי נמי, אין חיוב או ענין מתחילה, או שיש ענין בראשון כדי להגיע לענין בשני. ותחשב.
** ר’ חלבו -
יש לדון למה מזכיר את שמו שני פעמים.
** קיר -
קשה איך דורש זה, שאז אי אפשר ללמוד ממנו לשאר בני אדם. ותחשב.
** אל מקום -
אז, אין מתפללים רק לארץ ישראל, אלאלהר הבית. אם כן, קשה למה צריך קרא לכל אחד. אולי הוה אמינא שמי שהוא בחו”ל הוא כל כך רחוק עד שאין צורך.
** בתתם -
זה פריי”ז נאה, שיש לו כמה פעמים s וחיריק. ותו”ת.
** לה: ר"ח -
יש לדון למה קורא לו לפעמים ר"ח רובא, ולפעמים ר"ח. ואולי אינו אותו אדם.
** דביר -
מסתמא, מי שאמר גבי דביר שהוא מקום של רע לעובדי ע"ז יאמר כן גבי ארון. ויש לדון, שאולי לאידך גיסא כבר יש רמז.
** אסכריא -
ע"ש, שגמרא ורש"י לא אומרים שהוא מה שמפרש בזה פני משה (או מה שנראה מן המשנה כאן).
** לו. את שמע
- לחומרא- קשה, שכאן אומר כן להביא ראיה, ואילו היה ספק, יש לומר שסובר שאינו חלק מציפורי והתפלל לחומרא. ויש לומר שהיה לו לחוש לברכה לבטלה.
** ונעשה -
נמצא שלא היו רגילים כל כך לומר כן בתפלתם (לפי שמואל). אנו קובעים אותו במוסף.
** שחרית -
לכאורה, הענין הוא שאם מתפלל עמהם אותו תפלה, יש יותר צורך לו להתפלל, שתפלה זה עם הציבור הוא יותר טוב.
** רבי יוחנן -
לא הבנתי למה שייך למעשה זה, שמפני משה משמע שכבר התפללו, ושוב התפלל עוד כיון שלא כיוון בתפלה ראשונה. ונראה שבא לבאר שאף שהיה יוצא ממה שאמר הש"ץ, זה לא יוציא אותו בכל, כמה שאמר ר"י, ואז צריך להתפלל עוד מחמת שלא כיוון.
** לו: סדר ברכות -
צריך ביאור בכל זה, שלכאורה, רק יוצא מקצת הברכות מן הש"ץ, כמה שאמר ר"י.
** לז. השיבנו -
משמע שהכפילות הוא ממש חלק מן הספר, ולא רק איך קוראים אותו. ויש לדון, שאולי ענין שלא יסיימו ברע הוא מחמת קריאה שלנו.
** ודברת -
גמרא (מנחות) דורש את זה על דברי תורה (אבל חושב אני שאף דורש אותו על ק"ש). יש לדון אם זה חולק או שדורשו לענין ק"ש כיון ששם כתוב, ולא מפני שעליו קאמר). ותחשב.
** נחמות -
קשה, שהיה קודם החורבן.
** לז: איכן הוא קרוב -
צריך ביאור למה לא משיב לזה. וראיתי שיש גורסים אף על זה "בתי….”
** אלהיהן -
לשון זה מוזר.
** בצנעה -
יש לדון אם רצה לומר שלא רואים אותו לומד או לא אומר לבני אדם שהוא לומד.
** בן בעור -
אין זה משל כל כך טוב, שכמעט כולם חזרו לקללות. ותו"ת.
** לח. ויראו -
חולקים רמב"ם ושאר ראשונים אם מזיקים הם בריות בפני עצמם או רק בני אדם ובהמות שעלילים להזיק.
אם נאמר כרמב"ם, המשך של גמרא זה טוב מאד, שאמר איך שמלך שרצה להזיק לו לא היה יכול להזיק לו, ושוב דורש את זה לומר שאין מזיקים יכולים להזיק. (אינו קשה לשאר מהלכים, אבל הוא טוב ביותר לרמב"ם.)
** שוגג -
היה אפשר להביא מעשה שאומר גמרא במסכת שבת גבי הטיית נר.
** לח: בדייתיקי -
צריך מה זה אומר.
** לט. לעבודה בש"ת -
לכאורה, רק רצה לומר "בש"ת.” ויש גורסים כן.
** לט: העונה אמן -
לולי זה, היה אפשר להיות בברכת הגפן.
** מ. כנותן -
עיין בפני משה. לולי זה, היה נראה לומר שנותן קצבה לומר שעד כאן הוא רחמים שלו, אבל לא יותר. צריך ביאור למה לא יפרש כן פני משה, ואיך יפרש פני משה את מה שאמר בתוך לשון גמרא.
** כי יסכר -
נראה שמביא קרא זה מפני שהוא בלשון רבים, ואומר שלפעמים בענין דבר שקר, רק ברבים אסור.
** ופליג -
יש לדון אם הדינים שהביא לעיל (שלש ראשונות…) הם בש"ץ או ביחיד. ממה שאומר רק מזה שיש תנא שפליג משמע שזה שלעיל לא פליג. אם כן, צריך להיות ביחיד.
יש לדחות ש"פליג" כאן לא אומר שחולק, אלא שמחלק, ולא סובר שכל הברכות שוות בזה.
** מחיה -
לא הבנתי ל"ל אומרים שאם לא אומר מגן אבות, או כדומה, לא מאמין בזה.
** מ: בטיטי -
עיין בגרח"ק. לולי זה, היה אפשר לומר שרצו לומר קדושה ברבים.
** אר"ז
- לכאורה, הענין הוא שיש שני ברכות, ורק קיום אחת. אז, לא צריך ברכה אחד. ותחשב.
** מא. לפניו -
יש שלש מיני צדדים:
1. צדדים שלפניו.
2. צדדים שלאחריו.
3. צדדים ממש.
עיין במה שמביא גמרא סוטה מברייתא זה. נמצא שם סתירה בדין צדדים ממש, שרק דן בצדדים שלפניו ושלאחריו. נראה שני תירוצים:
1. אולי אי אפשר לדון בצדדים ממש, שאי אפשר לצמצם. ואם תאמר אם כן למה היה גמרא צריך לדון בצדדים שלפניו; אי אפשר שלפניו הוא ממש, שאי אפשר לצמצם. ויש לומר שלפניו רצה לומר שהוא בין שני הכהנים המברכים, שהוא לפני כלל הכהנים. אין לומר שהוא לצד של מין הכהנים, שאז הוא כבר בצדדים שלפני אחד מהם. ודחוק.
2. אולי אחד אגב חברו. ממה שלא שואל גמרא למצוא איזה אגב, צריך לומר שלא כוון לשאול אלא על צדדים שלפניו, ועל זה היה דן מתחילה. ויש לדון למה רק ידון בו.
ועיין בגי’ פני משה כאן, שאז כל הדיון לא מתחיל, לכאורה, שאז כאן מיירי בצדדים ממש.
תהא מבושר- ואם תאמר הרי זה עיון תפלה. ויש לומר שעיון תפלה הוא כשחושב שהוא זכאי לבוא לו בקשתו מתוך תפלתו; כאן רק אומר שתהיה בטוח שה’ יתן לך. ודחוק.
** מא: מצווה -
עיין במה שבאר פני משה בדרשה זה. צריך ביאור. ואולי כל העולם נקרא מצווה על שם "דבר ה’ שמים נעשה…,” שכולו הוא שם מפני ציווי ה’. ודחוק.
** בלעדיך -
איני יודע מה אומר בזה:
1. לשונו משמע שאומר שה’ מבטיח שלא ייתן טוב אלא לו. זה מוזר, שאין זה דבר טוב. ואולי רצה לומר שה’ יבטיח לו טוב עד שנראה שאינו נותן טוב לאחרים.[fn:8]
2. אולי אומר שאין טוב בא מבלעדי ה’. הבעיה הפשוטה בזה הוא שקשה מאד לקרוא בקרא. ותחשב.
** בבליא -
יש שגורסים שהיה ר"ח רובא. אז, אל גורסים, לשיטתם, בבלאי, שלא היה מדבר ר"י, שהיה מקטני תלמידי רבי (עיין חולין) לרבי חייא, שהיה תלמיד חשוב (ואולי אף חבר) של רב.
** מב: ומת‛ אמרה -
צריך ביאור מה מקשה מזה, שלכאורה להיפך; נלמוד מזה שדבר שנשחק משנה ברכתו. ותחשב.
** מג. רב חייא בר ווא -
ממה שגמרא אמר שהוא בבלי, וממה שהיה תלמיד של ר"י, וממה שכן אומר גמרא בבלי כל זה על רחב“א, נראה שרב חייא בר ווא הוא רב חייא בר אבא.
** ירק -
קשה למה אינו להיפך. ותחשב.
** מג: ורבנן -
פני משה, כנראה, מפרש שחול‛ מהו לשון עבר. אם כן, תלייה שאומר גמרא צריך ביאור. היה אפשר לומר שרק אם יש לו משמעות של לעתיד (אם ה‛ יוציא) יהיה בעיה. לא משמע כן מפני משה לקמן. וצריך ביאור מה אומר בתוך דיבור זה. ותחשב.
** אמת המים -
לכאורה, דעת על איזה מים יבוא הוא ברירה. ואולי רק רצה לומר שדעתו הוא שאינו חפץ זה שהוא לפניו ממש.
** מעתה -
רצה לומר, אף שמשנה בזה כוונת הברכה, אף כאן משנה כוונת הברכה.
** יש להעיר
שגי‛ ירושלמי יש בו פעם אחת רב נחמן ופעם אחרת רב נחמיא. בוודאי יש טעות במקום אחד.
** מה: פועלים -
יש לדון למה עושה כן שם.
** פת טמאה -
יש לדון למה אינו גבי מה שנטמא ממש:
1. הוא אף שם, אלא שהוא יותר מזה; אף אם אינו טמא ממש, יש לו אותו דין.
2. אז, הוא כל כך גרוע עד שאין לו אותו דין.
3. אסור לאכול דבר שהוא טמא, ואז אין דין זה נוגע.
** מו. לא שינה -
עיין בפני משה, שגורס להיפך. לכאורה, לגירסא זה, אומר שכיון ששינה את החפץ, מוכרח ברכתו לשנות, ואם לא שינה את הברכה, לא יצא.
** מו: החמיץ יינו -
יש לדון אם מביא כאן פסק או ברייתא. נראה שלא אומר ספק, שאם כן, היה לו לומר שהלכה כת”ק.
** מז: אבל -
לשרות- יש לדון אם זה אף להיפך (ר”ל, יש לדון אם מברך בתוך הסעודה אם שתה לפני הסעודה).
** מח. אחר המזון -
מעניין מה שאומרים שמברכים אחר המזון וכרב, שלכאורה, חידוש של רב הוא שמברכים עליו אף שבירך על פת. אז, הוא כן אף בתוך הסעודה. וצריך לחשוב על כל זה.
** תמרים -
מעניין שמניח גמרא שדין תמרים ודין פת הבאה כסנים שווה.
** רבנן -
לכאורה, רואים שכיון שיש ברייתא שמזכיר שם אחד, מניחים שיש חולקים עליו. ואולי כך הוא מחלקת רבי יוחנן ורבנן. ונראה שאולי זה תלוי במה שרבי יוחנן סובר שהלכה כסתם משנה (וחושב אני שרב לא סובר כן. ועיין בשי”ח ש”י בבבא מציעא.). לרבי יוחנן, שסתם משמע יותר שכן ההלכה, אם אין חולק, יש לו לאומרו בסתם. לרבי יהודה, שלא אומר כן, אולי אומר אותו בלשון יחיד כיון שממנו שמע, ואף שמסתבר שאין חולק, שלא מפסיד כשאומר שהוא הסובר כן, שבין כך ובין כך אין סיבה לחשוב לפסוק כן. ותחשב.
** מח: מעניין
שחולקים בברכה אחרונה של מחה שבא לפני פת רק אם כוון לאכול פת מיד אחריו, ולא רק אחריו. ותחשב.
** בתוך המזון
- לכאורה, יש שני דרכים לבאר חשש זה:
1. אפשר שחושבים שלא מכוונים.
2. אפשר שחוששים שיכוונו ויסכנו את עצמם.
עיין בפני משה, שכנראה אומר שניהם. צריך ביאור. ותחשב.
** והוא
- אף שאיכא גדול- אם יש גדול, קשה למה התחיל. לולי פני משה, היה נראה לומר שאף שיש אחר שראוי לכבד (שאף שזה הכי גדול, אין לומר שצריך לתת לו כל הכבוד[fn:9]), צריך ראשון זה לעשות את הכל. ותו"ת.
** שבוע הבן
- משמש- יש לציין למעשה בר“ג בקידושין (חושב אני שיש מעשה כעין זה גם באב של אחר. מסתמא הוא בחגיגה).
** מט. אמר רבי יהושע -
כאן, גורס ירושלמי הרגיל ”רבי יהושע,“ ולקמן גורס ”רב.“ צריך ביאור, כמובן. אולי קורא לרבי יהושע ”רב,“ כמו שמצאנו שיש שקוראים לרבם בשם ”רבי.“ יותר נראה לומר שאין הגירסא נכון.
** צריך לפסול
- קידוש- קשה למה אין סברה זה שייך בברכת המזון. היה אפשר לומר ששם לא מקדש היום, אלא מזכיר קדושתו. לא נראה שסברת רש"י הוא כך.
** ורב חיננא
- משמע מפני משה שאין הענין שכל הפסול היה ששינה מקומו, אבל כאן היה כבר עומד לבוא לאותו מקום, שהרי חשב עליו, אלא שהבעיה הוא שאכל עם דעת לאכול במקום אחר, והרי כאן לא שינה. ותחשב.
** מט: אהן -
על“ע שדנינו בסיבה שלא יצא (אם רוצים שלא יכוון או שמניחים שלא יכוון). לכאורה, זה אפשר רק אם נאמר כצד שהוא שרוצים שלא יכוון.
** אהן -
יש להעיר שכאן פשוט ביותר, שאמירה זה הוא כדי לשומרו, ואיך ידחה שמירת נפש עצמו.
** מוגמר -
מה שאומר מעניין, שמשמע שהוא רק מפני שאינו מוכרח להיות בחד זמן. לולי זה, היה אפשר לומר שכל אחד טועם יין חלוק. ותחשב.
באמת, צריך ביאור למה כל זה עושה שרק צריך ברכה אחת. ויש לדון אם זה עושה שרק צריך ברכה אחת או שיותר קל לאחד לצאת בברכה של חברו. ותחשב.
** כיון
- אף על פי- לכאורה, זה פשוט, שלעולם צריך לברך קודם שנהנה. (לכאורה, אין דרך אחר לבאר הגמרא שאין לו קושיה זה, אבל פני משה אומר אותו יותר בפ‛, ואז הערתי את זה עליו.)
** והכתיב
- גם היה אפשר לומר שהוא מפני שיש בו עץ קטן ועב בתוכו. ותו"ת.
** נ. המרבץ -
עיין במה שפירש פני משה. לכאורה, אז, מברך כשמרבץ; רק לא מברך על בית שנתרבץ. אם כן, הלשון קצת לאו דווקא. ותו"ת.
** נא. שנים בכלל -
צריך לבאר מה בכלל ”זימון,“ שאם הוא רק אמירת, ”הן לן…,“ אז בוודאי רשות הוא בשנים, ובוודאי יכול לומר כן בשנים, שלמה לא יכול לומר כן.
** בדעתון -
וא“ת הרי בב“ד יכול אף באחד. ואולי אף כאן יכול אף באחד. גם יש לומר (וכן משמע מפני משה) שלא מנסה להביא דמיון (שיהיה מסתמא זכר), אלא לומר שהוא לשיטתו ממש בדרשת לשון משנה, שאומר שהוא לאו דווקא. ויש להעיר ששני הלשונות לא שוות, ואז אינו לשיטתו ממש. אז, נראה לצרף שניהם לומר שהוא זכר בענין ביאור לשון המשנה.
** הכא איתמר אין רשאים -
אינו ”הכא,“ שהוא לקמן. בדרך כלל, היה לו להיקרות ”התם,“ אבל כיון שהוא בפרק זה, נקרא ”הכא.“
ודע שהוא דומה למה שבני אדם אומרים ”כאן“ בשני הדברים שהם מדמים. ותו"ת.
** שלשה -
לכתחילה- לשון שאומר, ששלוש הוא לכתחילה, הוא מעניין.
** אני
- דווקא שלוש- יש לדון, שמשנה רק מיירי בחוב. יש לומר:
1. ממה שרק דן בחוב מדייקים.
2. אולי רצה לומר שמשמע שמשנה אומר דינו רק בשלוש, ואז אין מקור לומר דין שנים. לא נראה שאין צריך משמעות לזה; בפירוש הוא במשנה שרק אומר דין של שלוש. ותו"ת.
** נא: על דעתיה -
אומר שמיירי בבאים משלוש. יש לדון איך מותר, אז, לצאת מן השלוש. יש לומר שאסור, ועשה כן באיסור. גם יש לומר שכיון שכל אחד הולך לזימון, מותר.
** נב: תורה -
עיין במה שמפרש לרבי. לא הבנתי, שלכאורה זה קשה לכולי עלמא, שאף לראשון כן הוא. ויש לדחות על פי מש"כ בהערות על חבורה של "אפקעינהו.” זה נגד רש"י בבבלי על זה. ויש לדון למה לא נאמר כרש"י, שהרי יש גמרא בפי’ כן (עיין בב"מ פח). וצריך לעיין שם.
לולי פני משה, יש לומר שחולק על דרשה שלעיל, ואז צריך לומר שסובר שאין זה קו"ח טוב. אז, מקשה מהו הקו"ח השני, ששני הקו"ח שווים, ואם חולק על אחד, מסתמא אף חולק על שני.
** נג: אפילו -
צריך ביאור מה שואל. לכאורה, שואל אם יכול קטן להיות אחד מן התשע. שמעתי פשט ששואל אם צריך קטן לעשירי או אין צריך שום עשירי. לא נראה כן, שאז לשון ”אפילו“ גבי קטן לא נראה. ותחשב.
** בעין קומי -
לכאורה, אומר שאחר שאל קמי רשב“ש. גם יש לומר ששאל שמואל בר שילת קמיה רב שמואל בר שילת, שהיו אנשים חלוקים.
** כמה זמנין -
קשה, שאין קטן נאמן בזה. ותו"ת.
** נד. תני -
צ“ב מה אומר שדן בהלכה, שלא ראיתי שידון בו בגמרא.
** נד: כמה דאנא -
מה שדעת שמש עושה שיש בעיה, אף שאין השותה שמש, הוא מעניין. ותחשב.
** מבורך
- ע‛ במה שכתב פני משה. גם יש לומר שהוא שהוא קורא אותו מבורך, והוא כעין שאמר שמברך אותו. ותו"ת.
** נה. ואין מחניפים -
צריך ביאור מה מתרץ בזה, שלכאורה, קושייתו היה איך יכול אדם לפסוק שבחו של ה‛, ששבחו של ה‛ כולל הכל. אם כן, צריך ביאור מה משיב. אולי היה אפשר להשיב שידע שבאותו עת לא היה שבחו של ה‛ כולל הכל (אף שזה נשמע ככפירה), אבל אין זה מה שאמר גמרא. וצריך ביאור.
** תני היה יושב -
צריך ביאור למה מביא את זה כאן.
** אם מתוך -
לכאורה, הסיבה שנלמד מאותם שאר מקומות הוא שבכל זמן מחמירים מלימוד (לומדים הדבר הכי חמור), ואז היה לנו ללמוד שלא להזכיר את השם. ותחשב.
** נה: כל יום -
יש להעיר שזה ביודע ששכח, אולי, ור“י אמר דינו בספק. ותחשב.
** כל יום -
היה אפשר לומר שזה בהזכרה שבשמונה עשרה.
** נו. הלילה -
יש לדון למה פשוט למגרא שהיה מעביר אותו בלילה. ותחשב.
** מלא -
יש לדון למה אומר סדר זה, ולא כסדר שאומר הקרא.
** ר“ז בר חמוי דר“ז -
צריך ביאור איך זה קרה. אולי היה גר (או היה שום גר שם) או אשת אם. ותחשב. גם יש לומר שהיו שני ר“ז.
** וצריך
- היה אפשר להיות שאין לו מים, אבל זה לא מצוי. ויש לדון, שיש פעמים שאין לשתות מים, כמבואר בסוף פסחים. ותחשב.
** נו: כלום -
לכאורה, מה שאומר כאן אינו מה שיבאר גמרא לקמן (שיאמר כן על שכר). ותחשב.
** נז. נשמעינא מן הדא (שני) -
כל זה צריך ביאור. נראה שהענין הוא כך. מזון קודם ליין, כמו שאומר בית הלל, וצריך להיות דבוק לו, שאי לאו הכי, לא מברך למזון על היין (כן אומר חרדים). הבדלה צריך להיות קודם יין. אז, יש שני מקומות שיכול להיות:
1. יכול להיות קודם מזון. הבעיה בזה הוא שמשנה ורבי יהודה אומרים שאין זה נכון.
2. יכול להיות בין מזון ליין. הבעיה בזה הוא שאז מפסיק. נראה שגמרא מוכיח מרבי יהודה הסדר, שאי לאו הכי, כיון שיש רק הבדלה בין מזון ליין לא יהיה הפסק.[fn:10]
** הבדלה
- אנן לא תנן- אינו משנה, ואז לשון ”תנן“ מעניין. ותחשב.
** אמר‛ בא
- קשה, שאולי רק יזכור ברכת קידוש. גם קשה שבכל זמן יזכור ברכת הבדלה. נראה ששני הקושיות יתרצו הדדי. נראה שכשזוכר קידוש, יזכור יין, שאין קידוש בא בלי יין. כשאומר הבדלה, לא יזכור יין, שהבדלה באה אף בלי יין, שנאמר בתפלה.[fn:11]
** נז: סוכה -
יש לדון למה אומר גמרא כן בתוך זה. נראה שאומר כן חנין בר בא, ומביא את כל דבורו כאן.
** וקשיה -
יש לדון למה נחוש שיכבה הנר, שרק ידליק אותו.
** מה עבד -
יש לדון ל"ל אומרים כן בכל הבדלה, שאף שם יש יין.
** נח: יושבת -
יש לדון בראיה זה, שאולי לבישת בגדים לאשה כזה אינו כל כך חשוב כנטילת.
** נח: ר‛ זעירה -
נקיות- יש לדון אם ר"ל ששמר עצמו מלכלוך טיט וכדומה, או שר"ל נקיות כמו שאומר גמרא ע“ז (קרוב לדף כ). ותו"ת.
** נט. מתניתין ב"ש -
עיין בגמרא, שלא מבאר כן, לכאורה, שמבאר שמיירי בשולחן שאינו מקבל טומאה. ותחשב.
** ס. וטחו -
לכאו‛, ר"ל שמה שצירך להטיחו בראשו, ולא לתת אותו על ידיו הוא ש“גנאי הוא….“ לכאורה, לאו דווקא ידים, שהרי אם השמש ת"ח אין לתת אותו על ראשו. ועוד שא"כ יש לו לתת אותו על ראש של עצמו.
ונראה שאולי אומר רבותא, שהוא אף על ידים, שאז נראה שרק נתן אותו שם להריח. נראה שגמרא אמר רבותא, שכיון ששמש שלו אינו תלמיד חכם, אף יכול לתת אותו על ראשו.
אגב, יש להעיר שבבבלי ברכות מבואר שהבעיה הוא שחוששים למשכב זכר. צריך ביאור, אז, למה הוא רק בתלמיד חכם. וצריך לומר שאין כל כך חשש עד שיש איסור ממש, אלא יש רק חשש די עד שלמי שהוא תלמיד חכם, אינו ראוי. ותחשב.
** פיסקא -
לא הבנתי החילוק, שבשניהם יכולים לעשות חדש, אבל זה שמברך עליו היה נעשה קצת לפני זמן. ותחשב.
** במיונס -
זה מעניין. עיין בסדר הדורות שמביא משלשלת הקבלה שנבראו מינים מוזרים של בני אדם בחילוק לשונות. ועיין שם (דף ריג).
** מעל -
יש שיטה לרבינו תם שאין איסור מעילה על כהנים שאינו לובש בגדי כהונה. גמרא זה לא משמע כן. ותחשב.
** סא: אפילו טרקלין -
לא באר גודל האש, ואז לא אומר כל כך.
** אילו שכח -
צריך ביאור מהו סברות אלו.
** עונים
- להר גריזים- אולי ר"ל לע"ז שמצאו שם במסכת חולין.
** עד מתי -
לכאורה, משנה מבאר. אז, צריך לומר שחולקים בפירוש המשנה. אם כן, מי שאומר, ”עד שיתעכל“ לא אומר כל כך. ויש לדחות, שאומר שמשנה אומר כפשוטו.
גם אפשר שחולקים אם הלכה כמשנתינו או כשום ברייתא אחר שיש להם.
** אבא בר -
מעניין שלא נדע איזה אמר בשם איזה. צריך לומר, לכאורה, שהיו חברים, ופעמים שזה אמר דבר בשם זה ופעמים שזה אמר בשם זה.
** ברוך הבא -
אין זה ברכה; יש לדון אם כשאומר שצריך לומר ראשי פרקים, אומר כן אף בברכות, או רק מכוון לזה.
** סב: כבשן האש -
ק"ק למה מברך שעשה נסים לאבותינו באלו. אולי כבשן האש הוא של אברהם. בלי זה, ועל של אריות, קשה, ויהיה תלוי על שאלת גמרא לעיל. ותחשב.
** מאדם -
נמצא שאומר שה‛ ברא אדם וחווה בצלמו, וכל הילוד נברא מאדם ומה‛ בצלם של שניהם, כיון שהוא צלם אחד.
** עבודה זרה -
נראה שעל פי זה בא לבאר את הקרא, שכשאומר אלהים קרובים, קאי על כמה אלהויות, דהיינו כמה ע"ז. ותו"ת.
** סד. אבל כך היא -
צריך ביאור מה זה אומר. אולי אומר שכן הוא ראוי להיות, אבל למעשה אינו כן. צריך ביאור מה זה אומר. ותחשב.
** אבל כך -
אם ידע התשובה, יש לדון למה שאלו. אולי רצה לדעת מה יהיה (מה ראוי להיות). אולי רק הכיר בו להיות אמת כיון ששמע אותו, אבל לא ידע שיהיה אמת. ותחשב.
גם יש לומר שהיה רק מבחין אותו. ותחשב.
** לצורך -
לכאורה, זה גלגל החוזר, שאם כן, יש צורך, וממילא אין צורכו נתקיים. ותחשב.
** עוד -
נראה שאומר שלבד מזה, יש צורך אחר. כמובן, קשה, שכיון שיש צורך אחר, בטל הראשון. וצריך ביאור.
** כמה -
ואם תאמר זה תלוי מה עשה (שמה שעשה בשני הציורים אינו שווה). ויש לומר שבשניהם עשה דבר שווה, שהביא כמה לפניו, והוא אכל רק אחד.
** כמה -
לא יאמר כן ברבים, שזה אבק לשון הרע. גם יבואו בני אדם שאינם מהוגנים לאכסניא.
** על הזיקים
- לא הבנתי כל כך החילוק בין שנים אלו. ותחשב.
** סד: עד גלות -
אותו נביא היה קבור קרוב לאדו, ואז צריך לומר שגלות הוא גלות של עשרת השבטים. ותחשב.
** סה את הלבנה -
לכאורה, לא מבאר את זה. נראה שמכוון לברכה על לבנה בחידושה. ותחשב.
** עד שנראה -
יש לדון מה זה אומר. נראה שלפעמים המטה נתמלא קודם למעלה שלו, ועל אותו זמן (או מה שיהיה אותו זמן בדרך כלל, ואף אם לא נתמלאה ממש, או רק אם נתמלאה) קאי. ותחשב.
** וראשי -
לא נראה- צריך ביאור, שבדרך כלל, רואים, ואז מקדשים. אף היום, שאין מקדשים על פי ראייה, לכאורה, מתוקן אגב מה שהיו עושים. וצריך ביאור.
** הקשת בענין -
נראה לי שרוב קשתות שנראים אינם בענין. אם כן, לכאורה, לא נברך עליהם. אולי רק קורא אותם בענין כיון שנבראים מחתיכות קטנים של מים, כמו עננים. ודחוק.
** בקעה -
אולי מה שנתיחסו שני דברים אלו לרשב"י הוא סיבה למה שחושבים בני אדם שמוצאים זהב תחת קשת (אף שברשב"י לא היה קשת).
** סה: לא סוף -
יש לדון אם ר"ל שקנה אותם מחדש, או שהם יקרים לו כאילו היו חדשים. ותחשב.
** שלש טפחים -
אם זה רוחב, צריך ביאור קומה…. ואולי זה volume. ותחשב.
** א"כ מה יעשו -
יל"ד ל"ל אומר כן על חיטים. וי"ל שגם הוא בארץ קרוב לגשם, ואז נכנס בו גשם. אבל תאנה לפעמים הוא בצור, כמו שאומר גמרא, ואז אי אפשר לינק אלא מסופם, וזה באדמה עמוקה. ויש לדון.
** ר"ב… -
נמצא שהיה אבא אבא דאבא. זה מצחיק לי מאד.
** סו. ייבא -
עדיין יכול להיות ציור שלא יפטור, והוא אם בירך על של יד כשהוא עליו, ומיד אחר כך נתן את של ראש עליו. ותחשב.
ויל"ד למה מותר לעשות שני ברכות כיון ש יכול לקיים מצוותו באחד, שיהיה ברכה שאינה צריכה. צ"ל שהוא יותר טוב אם אומר שני ברכות. צ"ב ל"ל אומר, אז, אף בזמן אחד. ותחשב.
** בשעת
- עיין במה שבאר. אז, לא רק ר"ל בשעת מעשה של קיום, אלא בשעת קיום ממש. אם כן, צריך לומר שרק מתחיל הברכה אז (שבדרך כלל, אין זמן די), וממשיך לאחר המצווה.
** בשעת
- מזה מוכרח שאין מברכים אם הוא אנוס מלעשות מצווה, אף שמקבל שכר עליו. ותחשב על זה.
** העושה -
לכאורה, סבר כרבי יהודה שלולב צריך אגד. ותחשב. ויש לדון, שאולי מברך כשחותך אותו מן האילן. ותחשב.
** סו: אמר יהודה -
לכאורה, חולק על מתניתין אז. ותחשב. ויש לומר שחולק בביאור משנה לומר שלעולם יכול לישנות על ידי תפלה, ואז אי אפשר לומר שלא מתפלל כיון שא"א לישנות, אלא סיבה אחרת יש (שרע לשנות דבר שכבר נעשה), ואז, אף כיון שנתעברה, לא יתפלל. ותחשב.
** משבר -
יש להעיר שכבר נעשה חילוק בין נקבה לזכר (עיין בנדה בענין מתי נחשב עובר ולא מים, שאולי הוא חלוק בזכר מבנקבה. יש לדון, ששם חולקים בזה.).
** היה בא -
לכאורה, צריך ביאור מה מהני על ידי אמירה זאת, וגם צריך ביאור מהו ההוה אמינא לומר שהוא אסור. ותחשב.
** מאחר -
עיין במה שביאר בתפלתה. אם כן, צ"ל שיוסף נולד לפני לידת לאה. אין זה סדר הקראי. וצ"ל שהוא מפני שאין מוקדם ומאוחר בתורה.
** בכניסה -
צריך ביאור למה יש יותר סכנה בכניסה ויציאה מבשאר זמנים. אולי יש שוטרים בחומה.
** מן האור -
יש לדון למה רק מזכיר אור. ותחשב.
** סז. חייב אדם -
פני משה מוסיף שלא רק אומר שכמו שיש ברכה על טובה, יש ברכה על רעה, אלא שיש דמיון בין שני הברכות. נראה שהסיבה שאומר כן הוא שאילו אינו כן, אז:
1. אין צורך לומר שהוא כעין טובה, שהיה יכול לומר רק שיש ברכה; אין צריכים דמיון כדי להבין מהו ברכה.
2. אין צורך לומר דין זה כלל, שכבר אמר שמברכים על הרעה.
לא היה אפשר לו לומר שהדמיון הוא שהוא אותו ברכה, ואז פירש שהדמיון הוא שמברך אותו באופן שווה. ותחשב.
** והיצר הרע
- זה מעניין, שאומר שיצר הרע רק אומר הזמנים שאין הכל הולך בטוב.
יש לדון למה נקרא כך. אולי הוא מפני שבאים על שעבר, או שבאים לנסותו, ונסיונות נעשים מיצר הרע. ותחשב.
** אקיף לי -
עיין במה שכתב פני משה לבאר אלו. נמצא שרובם כמעט שווה, והוא שמראה שהוא עושה המצווה, אלא אומר דרכים אחרים להראות כך. ותחשב.
** מאן דאית
- לכאורה, הוא שאומר כן, ואז מראה שהוא עושה מצווה. ותו"ת.
** סז: אבל דוד -
צריך ביאור למה גמרא מניח שזה יותר טוב; לכאורה, היה נמצא שאברהם עשה שיהיו לו שני יצרים הטוב. ותחשב.
** דבר שאי אפשר
- לא הבנתי, שגמרא אומר פעמים שמתפללים על גשם שלא לבוא. וצריך לעיין בגמרא תענית שם.
** נחמיה -
מעניין שהיה תלמיד של רבי עקיבה.
עיין בבבלי, שכשאומר מעשה זה אומר שהיה דורש כל האתים, וכיון שהגיע לזה פרש. אמרו לו תלמידיו (רואים שהיו לו תלמידים, ואז קצת מעניין אם נאמר שהיה תלמיד של רבי עקיבה. וצריך לומר שהיה מלמד בחיי רבו.) מה בשאר, ואמר דבר (עיין בגמרות חלוקות במה אמר), עד שבא ר"ע ודרש אותו.
כאן, אומר שהיה תלמיד של ר"ע, ושאל לר"ע, ודרש לו. דע שאם היה תלמיד של ר"ע, מוזר מה שלא היה שואל לר"ע קודם שיחזור על כל מש"א. אולי סבר שאי אפשר לתרץ, שאי אפשר להיות אחר כעין ה‛ בזה.
על כל פנים, נמצא לנו אולי שני סיבות לחשוב מן הבבלי שלא היה תלמידו. ותחשב.
** בית דין של מעלה -
ואם תאמר מלאך זה בא קודם למעשה של בועז (כן אני חושב). ונראה שרק יודעים שתקנו לעשות כן מפני אותו מעשה של בועז, אבל אולי תקנו לעשות כן קודם לכן. ויש לדון ל"ל נאמר שגופא למדו ממה שאמר מלאך. ותחשב. אולי לא היה מסתבר ללמוד ממלאך, שואלי מלאך חלוק. קשה, שאז לא נדע שהסכים ה‛ לידינו. אולי אילו לא היינו נכונים, לא היה מלאך אומר כן, שמא יחזיק ידינו בטעות. ודחוק.
אז, יותר נראה לומר שגמרא ידע, ולא מקראי, מה קדם, ואז ידע שמלאך היה אחריו, ושהיה הסכמה מאם השמים למנהג זה. ותחשב.
** סח. דיינו ברכות -
בבלי אומר, ”עד שיבלו שפתותיכם מלומר די.“ מקשים העולם שאין אות שיש בו שפתים ב“די.“ נראה שאין זה קשה לירושלמי זה (ואולי לכן לא אומר כפשטות של קרא שאומר ”די,“ אלא שאומר ”די ברכה“), שהרי אומר בית של ברכה.
ודע שגם מסתבר יותר כירושלמי, שמסתמא יש עליו לומר בקשתו השלם, וזה כולל מהו די. ותחשב.
** ואם לאו כנוש -
לבזיון- גם היה אפשר לומר שאינם זכאים בו, אז. ותחשב.
** כיון שהפליג -
יותר- לכאורה, הוא רק יותר ממה שהראשון הוא עתה, אבל לא רואים שהוא יותר ממה שהיה. ותו"ת.
* Footnotes
[fn:1] ויש להעיר שאפשר שס"ר של איסורי כרת הוא שחייב כרת, והוא שחיוב כרת בא ממילא.
[fn:2] עיין בגמרא שבת (לה.). ונראה שאין סיבה לומר שזה אומר שהיו טובלים אז, אלא שיכולים לטבול אז. ותחשב. ויש לדון, שאולי אם כן לא היה לו להזכיר כהנים, שכן דין כל הטמאים, אלא אם היה מנהג שמזכיר, אולי כהנים נהגו כן. ויל"ד בזה. עוד יש להעיר שממה שחולקים שם בזה (שתלוי במחלקת תנאים), נראה שאינו מזכיר מנהג. ויש לדון.
[fn:3] הבנתי שכך היא סדר כל הגמרא, שמביא שני שיטות שסוברים שקאי על פתיל, ואחר כך מביא רבי מאיר שחולק ודורש אותו בענין אחר.
[fn:4] יש להעיר שלא היה שמו ממש, אלא אמר מימרא זה בשם ר"י, ואז אותו מאמר נאמר מרזב"י בזב"י.
[fn:5] ויש לדון, שאולי רבנן דהתם סוברים שהלכה כמותו, וסוברים שאומר שרק אומר "מודים.” לא נראה כן, שאז היה לו להקשות אף על לשון זה. ותחשב.
[fn:6] עיין שם; ויש להעיר שכאן יש ראיה יותר חזקה, ששם רק אומר שיהיה כביאה לעולם, ויש לומר שזה אומר ביאת נשמתו לעולם, והוא ביאתו ראשונה, אבל זה רק אומר לידה, והראשון אינו נקרא לידה יותר מלידה של אותו זמן האחרון. ותחשב.
[fn:7] יש לדון, אז, למה צריך להיות מקום לשחיטה.
[fn:8] מה שנראה כן הוא או שהוא כל כך טוב עד שיחשוב אדם שלא נשאר, כביכול, עוד טוב לתת, או שה’ מעדיף לו יותר משאר בני אדם, שרק נוטלים מה שצריכים, עד שכנגדו, כמעט לא נוטל אדם כלום. ותחשב.
[fn:9] ואין לומר שזה תלוי באם מכבדים לתלמיד במקום רב, שאולי זה רק אם אחד תלמיד, שהוא גרוע ביותר לנגד רבו. עוד יש לחלק ששם אף התלמיד חייב ביותר בכבוד רבו, אבל כאן, אינו חייב לכבד את מיש הוא קצת יותר תלמיד חכם ממנו. ותחשב.
[fn:10] מסתמא, זה מפני שהוארק ברכה אחת, ועוד שהוא כבר עצמו דבוק ליין. ותחשב.
[fn:11] יש לדון, שלכאורה, רק בא בלי יין בתפלה; ואף שזה שכח לברך על יין, לכאורה, על כל פנים זוכר שאינו מתפלל עכשיו. ותחשב.
