** א. עד שיעלה -
עיין בפני משה. משמע שאין חילוק בדין בין ר"ג לרבנן, אלא רבנן אומרים לנו עצה טובה. לולי זה, הייתי אומר שאין חילוק בדין ביניהם בדיעבד, אבל יש חילוק ביניהם בענין אם יש חיוב מדרבנן לומר ק"ש קודם חצות. ותחשב על זה.
** אברים
- יש לדון למה מחלק אברי עולת תמיד של בין הערבים ואברי שאר קרבנות לשני בבות. אולי הוא מפני שתמיד יש עולת תמיד של בין הערבים, שכמעט אי אפשר להקטיר אותו קודם צאה"כ. עדיין איני רואה כל כך למה לחלק אותם.
** כדי להרחיק
- עיין ברשי על המשנה שכ' שכאן אין גזירה. מפני משה לא משמע כן; צריך לעיין בדין זה.
** א: ספק -
היה אפשר לדחות שנכון הוא שספק לילה הוא, אבל אינו ספק זמן קריאה, כיון שזמן קריאה תלוי בשכיבה, ואינו, אולי, זמן שכיבה.
** תפילה -
לכאו', לפי רבי יוחנן יהיה רשות, שאין חיוב לקיים דין דרבנן מספק. עיין בפני משה, שנראה שלא סובר כן. ותחשב. (נראה שאולי ההסבר הוא שאין מטריחים אותו לקיים דין דרבנן. אבל, תפילה הוא גם חיי שעה (כמו שאומר גמ' בשבת, והוא מפני שמתפלל על צורכו), ואז אינו טורח. ותחשב.
** מה נפשך -
עיין בביאור פני משה. איני מבין למה אינו התראת ספק.
** מה נפשך
- איני מבין כל כך מהו המשך השאלות, כמה שבאר פני משה. באמת, איני מבין כל כך מהו השאלות.
** ג. לא מסתברא -
איני מבין למה לא כתב, מחמת זה, שהוא ה"הרף עין" האחרון.
** ר' נחמיה -
כמובן , לצד שני של גמ', לא פשוט מהו החילוק, שלשניהם אותו זמן הוא ספק. אם נאמר שיש לו דיני ספק, מחמת שינוי מציאות (שנעשה יותר לילה כשנמשך) נוכל לומר שבמציאות זה יש חילוק ביניהם. עדיין מוזר שיחלקו בזה, כיון שאין נפקא מינא. ותחשב על זה.
** ד. קפיצים
- עיין במה שפירש פני משה. רגילים בני אדם לפרש שלמלאכים אין ברכים (ניי"ז), אבל מדברי הפני משה לא משמע כן, שיכולים לשבת בלי ברכים. אלא, יותר היה משמע שהוא ההי"ף. אבל, מילה של "קפיצים" לא משמע כן, שלכאו' הוא שייך למילת "קפיצה" שהוא ג'ומף[fn:1], והרי עושים קפיצה עם ברכיים, ולא עם הי"ף.
אז, נראה שקפיצים הם ברכיים, וכשפני משה אומר שאי אפשר לשבת בלי ברכיים, כוונתו לומר שקשה מאד לעמוד מישיבה בלי ברכים. כיון שיצטרכו לעמוד לפעמים (מסתמא), אי אפשר להם לשבת. ותחשב על זה.
** ה. אחד מכד' -
בבלי אומר שהוא אחד מחמש רבוא, וכן תני שמואל (הבבלי) כאן. וא"ת הרי שניהם מודים שוהא זמן שצריך כדי לומר "רגע." ויש לדון, שיש לומר שזה מחלקת. ונראה שאולי בני ירושלים לא היו מדברים מהר, ולכן היו צריכים לדבר לשון סורסי. אז, היו צריכים יותר זמן לומר כל המילה "רגע." ותחשב.
** לא הוה שחרא -
כבר אמר כן, שכבר אמר שהיה מתעורר בחצות או לפני שני אשמורות.
** רבי
- פ' שהנפ"מ הוא לביאור שיטת ר"א. קצת קשה שר"א סובר, בבריי' המובא בבבלי, שיש שלש אשמורות. אין רואים שרבי סובר כר"א לומר שמפרש את שיטתו כאן. וצ"ב. (נראה שכיון שרבי סובר שזה נכון, צריך להיות שסובר שר"א סובר כן, ואז מוכרח שיהיה נ"מ בשיטת ר"א.)
** וכ' קדמו
- הן חצות- לשון זה מאד מוזר, שאינם חצות, אלא חצות בא כשהם מתחילים.
** ה: מלכים -
נמצא שסותר א"ע מתי מלכים קמים. (גם יש לציין לבבלי שאומר שה' זועם קודם שלש שעות, ושזועם מתי שמלכים עובדים לשמש.) צ"ל שיש מלכים שקמים בשחר, ויש מלאכים שקמים בשלש שעות. גי"ל ששחר מעורר אותם, וקמים בשלש שעות.
** חברי תורה -
צריך לומר או שהלך לביתם, או שכל העיר שמע, או שהיו דרים קרוב לו. כ"א מאלו דחוק.
** לא מתחשבא -
כמובן, לכן הוא זמן של קריאת שמע (שהוא הזמן שבו אנשים עוד נעורים, והלכים לישון). אבל יש להעיר שזה הזמן של רבי, ור"א אומר כזמן של רבי נתן. (על"ע.)
** ו. מלתיה -
ע' בפני משה, שפי' את זה רק לפירוש שני שכ'. איני מבין איך לבאר אותו לפי' ראשון.
** גו שינה -
יש לדון למה אין בזה משום כופל שמע. אולי כיון שאמר כל הפרשה (ושאר פרשיות) אין איסור. ותחשב. גם אפשר שכיון שהיה בו צורך, אין בו איסור. (לא נראה כן, משאלת גמ' בענין כוונה. וי"ל ששם לא ניכר הצורך.)
** ו: עובדא -
קצת קשה, שהיה מחמיר רק לעצמו. אבל, כאן היה ר"ג פוסק לאחרים, ולא לעצמו, ואז לא קשה שהקיל על פי שיטתו. אולי צריך לחלק בין בניו לתלמידיו. (יש לציין לביצה ולכ"מ שמצאנו שיטות שכנ' היו מנהג של משפחת בית ר"ג.)
** עובדא -
קשה למה לא יעשה עובדא כעצמו, שהל' כיחיד אם מסתבר טעמו, ובוודאי היה טעמו מסתבר לו. ותחשב.
** ז: חבריה -
קשה מהי"ת שאינו חבר שמכיר, שאינו יכול לראות אותו קודם עלות, שאין אור, ומסתמא אף לא מיד אחרי עלות. נראה שיכול להכיר אותו קודם, על ידי שמיעה. ויש לדון.
** תני ר"י -
נמצא שהיה ראב"ע חי בזמן שחי רבי יהודה. אז, קשה למה אומר שהיה העולם שמם במיתת תלמידי רבי עקיבא, אחרי שהיה ראב"ע גם קיים. (יש להעיר שבאמת, מוכרח ש"שמם" אינו דווקא, שרבי עקיבא היה קיים.)
** זבדי -
נראה שאולי זה כינוי. כן נראה לומר גם על פפי.
** ח. כוונה -
עיין בביאור שאומר פני משה. גם היה אפשר לומר שאינו מפסיק כל כך אם לא צריך הפסק במחשבתו. ותו"ת.
** שלייתו -
צריך ביאור מה מוסיף ר"י. אולי רוצה לומר שהיה כדאי לקבל צער לידה, ורק לא כדאי להיות נלוד אחרי כן. ותחשב על זה.
** ח: יטו -
מלשון פני משה יוצא שמילת שכיבה משמע שינה, ולא הטייה. ותו"ת. ויש לדון, שאולי אומר שלא צריך לעשות לאיינ"ג דוו"ן ממש, אלא הטייה מהני, שהוא דומה ללאינ"ג דוו"ן. וע' ברשי בתחילת זבחים שמשם מוכח ששכיבה לא רצה לומר שינה.
** חמורים -
קשה, שיש גם קולות, כמו פטור מלולב. ויש לומר שיש בזה חומרא גם כן, שאסור לקיים את המצווה.
** ט. אטיף -
ואם תאמר יש מוטב שיהיו שוגגים. וי"ל שזה רק בשוגג, אבל לא במזיד.
** כ' עליו -
ואם תאמר רק לא יראה את הכ'. וי"ל שכ' להם כבר עליו. גי"ל שממש כ' עליו, כמו על ידו, במקום שיראו אותו.
** י. מכרוע -
אז, לכאו' גם הדרך שהשתחווה היה חלוק (שהיה כורע, ולא משתחווה).
** לוי -
מן המעשה נראה שזה האמורא שתלמוד בבלי קורא "לוי." מעניין שנותנים לו שם שמשמע שנסמך, ובבבלי משמע שלא נסמך. אפשר לומר שמקצת הדברים נאמרו קודם שנסמך ומקצתם אחר כך. וע' בשבת (נט:), שקורא לו לוי אחר שנעשה חיגר. אולי לא ידעו שנסמך. גם אפשר שנסמך אף אחר זה, וגמ' שלנו קרא לו רבי לוי על שם העתיד.
** במודים -
ואם תאמר מה מוסיף בזה. ויש לומר שמוסיף שבאותו מילה שבהודאה הוא. ותחשב.
** י: רבי זעירא -
אנחנו לא נוהגים להשתחוות בסוף הפיוט, אבל אולי זה תלוי במה שהיו נוהגים לומר "ברוך אתה ה'" בסוף, מה שאין אנו נוהגים לעשות.
** סמך -
נמצא שלא היה פשוט, לכאו', לסיים עם הש"ס, והיה צריך להאריך. ע' לקמן, שלמקצת השיטות (בוודאי, לשיטה אחרונה, שאומרת שצריך לומר את כולם), לא צריך להאריך, אלא אולי צריך למהר.
** צב -
איני יודע מה, בדיוק, הוא צב. בדרך כלל, אומרים שהוא טורט"ל או טו"ד. שניהם, לכאו', לא כורעים. אפשר לומר שכשטורט"ל מכניס את רגליו לתוך הש"ל שלו, נחשב שכורע. גם אפשר שכריעת טו"ד הוא כשמוריד את גופו קודם שקופץ.[fn:2]
שמעתי שיש אומרים שהוא נחש, ושכורע בכפיפת קומתו.[fn:3]
** יא. חוזר וכוללם -
רח"ק מבאר שהוא כדי להוציא את בני משפחתו.
** ראב"ע -
עיין בבבלי שחולק. אפשר לטעון שבבלי לשיטתו, שאומר שהיה העולם שמם במיתת תלמידי רבי עקיבא, והוא שראב"ע כבר נפטר אז (לכאו'). אם כן, צריך לומר שכבר נפטר לפני שהגיע לארוכת ימים, ולכן פי' שלא רואים מכאן שחי הרבה זמן. אבל, ירו' הביא לעיל שלא מת מוקדם, ומפרש זה לומר שהאריך ימים. ותחשב על זה.
** כבן
- הלבינו- משמע שמה שקרה רק היה ששער שלו נעשה לבן, אבל לא שגדל יותר שער (יותר זקן) להיות לו זקן לבן. אולי כבר היה לו זקן, או אינו כל כך מוזר שלא יהיה לו.
** כשבעים -
ירו' מפרש שרצה לומר שהיה גיל קרוב לשבעים (ששים ותשע או שבע ואחת). נראה שאולי היה יותר משבעים, ואמר לשון כשבעים מחמת עין הרע (שלא רצה לומר שהגיע כבר ליותר משבעים שנה).
** יא: מתני' פליגא -
לכאו', חולק על שניהם. יש שגורסים כן (ע' בגר"א).
** צדיקים -
עיין במה שבאר בפני משה בישמעאל. אגב, יש להעיר שהיה שרי נכונה בהגרשה את ישמעאל, כיון שהיה משחק עם יצחק, ואז מעניין שהוא נחשב צדיק עד שה' הציל אותו בנס.
** יב. כוונה -
נראה שהתלייה היא שהצד שלא יפסיק הוא שבזה מסיח דעת. זה רק בעיה אם צריך כוונה. ותחשב. ויש לדון, שגם מדבר. אם, באמת, זה נכון, אז קשה למה לא מוכיחים מן משנה שלנו שצריך כוונה בכולו. אז, תחשב על זה.
** יד. תלתא ימין -
מלשון הגמ' (שמוכיח מכאן שהחולי היה ממרק את הגוף שלו) משמע שרצה לומר שאף שברוב ימים לא היה לובש אותם כל היום, בשלש ימים שאחרי חולי שלו היה לובש אותם כל היום, כי ידע שגוף שלו יהיה נקי, כיון שהיה חולה.
עיין בפני משה, שמתחיל ככה, אבל מסיים עם לשון שמשמע שהיה מתחיל ללבוש אותם שלש ימים אחרי שעמד מחולי שלו. זה צריך ביאור.
** כד הוה -
איני מבין.  מתחילה אומר שהיה לובש אותם רק בבית יעקב, ועכשיו אומר שהיה לובש אותם מיד כשעלה מן הרחיצה (כפי פי' פני משה).
היה נראה לומר שסובר שיש איסור לערום לעמוד בפני התפילין (כמו שאסור, מעיקר הדין, להביא תפילין לבית הכסא). אז, הקשה איך נתנו לו את התפילין כשהיה ערום, אף שהיה לובש אותם רק אחרי כך.
** יד: אית דבעי -
אם מצוות עשה רק עושה שלא ילבש אותם, ולא שיסיר אותם, לא יברך בהסרתו, שאין חיוב להסיר אותו.
** אשתו של יונה -
צריך לעיין מה היה רע בזה, ולמה לא תקיים את המצווה. (הניחא בתפילין יש חשש של גוף נקי, אבל כאן, לא נראה מהו החשש. יותר מזה, יש להעיר שמצאנו שהיה חנה עולה לרגל.)
** טו. צררה -
עיין בביאור פני משה. מוזר שיהיה צואה יבישה בים, שהוא לח.
** סמכים על הוראה
(בתוך פני משה)- לשון סמך על הוראה לחומרא הוא מוזר.
** טו: צרכיו בביה"ק -
מעניין שזה ועג לרש, שמראה לו מה שאינו כל כך טוב במה שהוא חי.
** אביי -
לא פשוט מה לגרוס כאן, אבל יש גורסים "... בר אביי." לכאו', זה לא "אביי" של תלמוד בבלי, שלא בא בן זה בתלמוד בבלי, וגם אביי לא בא הרבה פעמים בתלמוד ירושלמי. אז, נראה שהיו שני "אביי"ים. אם זה לא היה שמו, אלא היה מכונה כן על שם שהיה יתום ("אשר בך ירוחם יתום"), צריך לומר שגם יתומים אחרים היו מכונים כך. אם "אביי" היה שמו, לא קשה לומר שלאחרים גם היה להם אותו שם.
** רבי מאיר -
אם אינו יוצא, מעניין שיש שום ענין בזה בשעת הסכנה.
** רבי מאיר
- לכאו', רבי יוסי, שהיה תלמיד של ר"ע עם רבי מאיר, היה גם אומר שמע ככה באותו מעשה. אז, לא רק מביא ראיה ממה שר"ע לא חלק עליהם, אלא אמר שאף רבי יוסי החולק לא סבר כן. אולי זה אינו ראיה גדולה, ששינה את דעתו, וזהו.
** יז. צדקנו -
מעניין לסכם ברכת הצדיקים ככה.
** יז: לא חמיתיה -
בדרך כלל, אם אדם אומר לך שרצה להרוג אחר, ושוב לא רואים אותו אדם מאותו היום, המשטרה יקחו אותו על רציחה.
** יש להעיר
שלא היה ממש נולד בשעה שבית המק' נשרף, כמו שנראה ממה שקרה עם השור. אבל, לא ידע כן האם. ותו"ת.
** ערבי -
כמו כן, יש ערבי בב"ב שיודע הרבה. צריך ביאור איך ידעו כל זה. אולי סתם ערבי הוא אליהו הנביא (יש לדון למה ייקרא כן) כמו שסתם סבא הוא אליהו.
** יט. ר' ינאי -
עיין בלשון פני משה. משמע שהיה נהוג לישא קטנות שלא הגיעו זמנן לראות, והיה עושה כן ברגילות. מוזר לטעון כן; כמה נשא כבר.
** מהו לבעול -
עיין בביאור פני משה. צריך ביאור מהו הקושיה; הייתי אומר להיפך, שכנראה סובר שדם נדה מצוי, ויחשוב שדם זה הוא דם נדה, ולא דם המכה, ואז אין איסור.
** ר' ינאי -
צריך ביאור למה ערק. הרי, אין צריכים ראיה ממה שלא ראה דם, שהרי מותר לבעול בלי בדיקה. אולי מדברים בשיצא הרבה דם או שיצא דם גם אחר הביאה.
** יט: דרומיא -
לגירסא שלנו, יכול להיות אומר או "דרום" או "של רומי." מהמשך הגמ', מוכרח לומר כצד ראשון. יש גי' שונות שעושים שזה יותר מוכרח.
** תענוג -
אז, משנה שלנו הולך כמתירים (אף שגמ' קורא להם הזעירים).
** תנחומים -
יש לדון למה לא מקבל תנחומים:
1. אינם קרובים שלו. יש לדון, שקונה אותם.
2. אינם בני אדם, אלא עבדים.
עיין בלשון גמ' שמשמע שמצרף שניהם.
** כ. עבדיו -
צריך ביאור מהו תי' הגמ'. מת' שכך אמר ר"ג. אבל, קשה למה אמר ר"ג ככה. צריך לחלק בין ציור שמקשים אדם פרטי על ציור פרטי לדין שנאמר לכולי עלמא להלכה.
** שושנים -
צריך לע' בכתובות (ח), ושם היה שמש של ר"ל.
** מלך -
לכאו', זה קאפיטאליז"ם. אולי רק אומר שכן קורה, אבל לא שזה טוב. דחוק, שאומר כן על ה'. אולי יש לחלק בין קאפיטאליז"ם לה' או למלך מלאומה שלימה. אבל, בין כך ובין כך, יודעים מן ראיות גדולות (כמו רוסיה וסין) שקאפיטאליז"ם יותר טוב לכל האומה.
** כ: לוי בר סיסי -
מבואר לעיל שזה לוי. צריך להעיר שבא לבבל כשהיה רב שם, וצריך לומר שעדיין היה אבוה דשמואל קיים, ואף אחר מיתתו. (אולי אמר כן עליו כשיצא מן הארץ הקדושה. דחוק מאד.)
** דמנהגא כן -
איני מבין כל כך למה זה עושה שאין לענש אותו, שאף אם המנהג כן, הרי הכה תלמיד חכם במקום קבלת כסף. (נראה שהוא מניח שכיון שכל שאר בני אדם עושים כן, גם לו מותר לעשות כן. אף שזה חשבון של הבל, רוב בני אדם עושים חשבנות כזה הרבה פעמים בכל יום.)
** אא"כ מינו -
יש לדון מה רוצה לומר. אולי מתיר אם ראוי למנות אותו פרנס (כעין מה שאומר בבלי). גם אפשר שאומר שאף אם לא ראוי, אם כבר מכבדים אותו כאילו הוא ראוי, אין חשש יוהרא עוד.
** לשם שמים -
נראה שקושייתו היה שאף שלא כיוון ליוהרא, היה לו לירא מן היוהרא.
** כן תני -
משמע, וכן ייצא מןהגמ', שדבר של צער רק מותר שלא מפני אחרים. צריך באור מה, אז, יהיה חשש יוהרא. אולי הוא מפני "כל דבר שאסור ברה"ר, אפילו בחדרי חדרים אסור."
** אמר ליה -
רצה לומר, משנה שלנו הוא רק בקריאת שמע. ואם תאמר מהיכי תיתי לחלק. וי"ל שממשנה של רבן גמליאל (מלשונו) נראה לחלק.
** כב. לתלמידיו -
נמצא שהיו לו תלמידים אז, אף שהיה בחרם. (אין לומר שזה היה קודם שנתנו אותו בחרם, שהרי רבן גמליאל נתן אותו בחרם, וכמובן, זה קרה לפני מיתתו.)
** כב: אם אין לו -
ציור מוזר הוא שמת קרוב שלו, ולא מוצא שום אדם שירשה לו לאכול בבית שלו.
** רב חייא בר ווא -
נמצא, לכאו', שזה שקבל קבלו עליו. משמע שרח"ב ווא ורח"ב בא הם אותו אדם. אולי צריך לשנות גירסת אחד מהם.
** כג. רבן גמליאל -
יש גורסים רשב"ג ויש גורסים ר"ג. היה נראה לגרוס ר"ג, שהרי היה לכבודו, ומסתבר שיתקנו אותו אחרי שמת ויצא בבגדים זולים. אולי הגורסים רשב"ג גם גורסים רשב"ג שם. ע"ש, שאינו כן.
** כה. ה' אחד -
יש לדון מהו כוונת הדרשה:
1. ה' הוא אחד, ואין אדון אחר חוץ ממנו. יש להעיר שאולי ה' אחד במה שהוא ה' אחד, ולא מה שהוא אדון אחד. במילים אחרים, ה' הוא הרבה דברים- ה' הוא אדון שלנו, וה' הוא האלקים, וה' הוא סיבה לחיים שלנו וכדומה. כמו שלא אומרים שצריך להיות מי שאין לו סיבה אחרת לחיים שלו, ואז כל מי שניצול נפשו מחמת רופא יפטר, כך לא נאמר שצריך להיות מי שיש לו אדון אחר. ויש לדון בזה, שאולי קרק' זה יותר חשוב בשם ה', או במי הוא ה'.
יש להעיר שרמבם פי' ש"ה' אחד" רצה לומר שכל מדות של ה' אחד. (נראה שהענין הוא שלפעמים בני אדם עושים דברים שבזמנים אחרים לא רוצים. כאילו, דעתם ומדות שלהם משתנים. אבל, ה' אינו כן, ומה שעושה ה', תמיד ה' רוצה.)[fn:4] לכאו', אם נאמר כפי' זה ירושלמי נגד הרמב"ם.
אבל, יש להעיר שיש ראיה לדברי הרמב"ם ממה שאסור לשנות קריאת שמע, כיון שנראה שמדבר לשני אלוהות. לכאו', אם "אחד" רצה לומר שיש רק אחד, קשה איך יאמר כן לשני אלהויות. (אולי משקר להם, וחושב שלא יבינו; מוזר לומר כן על עבודה זרה.) אז, יותר נראה לומר כרמבם. ותחשב.
1. אולי דורשים מ"ה' אלקינו," שמשמע שרק ה' אלקינו, ואין אחר. (אין דיוק זה כל כך פשוט, שיש לומר שה' הוא אלקינו, ואין אחר אלקינו." על זה קשה גם מה שהקשינו על צד ראשון.
אפשר לדחות את הבעיות לומר שלשוןן אלקים משמע שאין אדון אחר. לא נראה כן.
יש הלעיר שלצד זה איש כזה גם לא יוכל להתפלל ולקרוא לה' אלקיו, וכל תפלות שלו מתחילים בברכה מזוייף, ואין בהם שמונה עשרה ברכות כהוגן.
** תדיר בה -
יש לדון מהו כוונת הפני משה. צד ראשון הוא שמכוון לומר שטעם של כאן הוא טעם של קריאת שמע. אינו תדיר במצוות תפילין, ולכן אין בו חיוב חינוך, וגם (מוסיף פני משה) אינו תדיר במצוות קריאת שמע, שלא כל יום הוא קרוב לאבא שלו באותו זמן, ואז לא חייב בו. צד השני הוא שמפרש שסיבת הפטור בקריאת שמע הוא פטור שלו בתפילין. כיון שאינו חייב בתפילין, לא יקום להיות מצוי אצל אביו בזמן קריאת שמע. כיון שלא קל לו לחנך את בניו בזה, לא חייבו רבנן אותו בו. (קצת צריך ביאור, שכמו שהיה בא לתפילין, יבוא לקריאת שמע. ותחשב.)
** תדיר בה -
אז, קשה שגם אנחנו לא נלבוש אותם כלל, כיון שאין אנו יכלים ללבוש אותם כל היום (או על כל פנים מספיק להיות תדיר). אולי אם יכול ללבוש אותם לזמנים חשובים, כמו שאנחנו עושים, נחשב תידר. קטן לא יכול לעשות אף את זה. גם אפשר שכיון שאנו יכולים, אבל מניחים שלא נעשה, אנו חייבים בלבישת תפילין. ותחשב. גם אפשר לומר ש"תדיר" לא רצה לומר שילבש אותו כל היום, אלא שילבש אותם כל יום. (ודע שלא פשוט שיש חיוב ללבוש תפילין כל יום ויום.) ותחשב על כל זה.
** מזוזה -
מה שאומר גמ' ומה שאומר פני משה לא שווים. גם לעיל (גבי "הרי אני כבן שבעים שנה," שבסוף פרק ראשון) פני משה בפי' על המשנה סתר מה שיאמר ירושלמי. ותחשב.
** תדיר -
ואם תאמר איך יכול לפטור אותו מחיוב חינוך (שהוא מדאו') שהוא דרבנן. ותחשב. נראה שנוכל לומר שלא רצה לומר שאין חיוב, אלא שיש איסור, שתמיד חוששים שלא יוכל להעמיד על עצמו. ותחשב.
** כו. אבל אמרו -
קצת צריך ביאור למה כופל את זה; כבר אמרו שיבוא לו רע על זה. מפני משה משמע ש"אבל" זה רצה להוסיף כוח ברירות זה. אומר שלא רק נראה כן, אלא אמרו בוודאות כן. דחוק.
** עונה -
עיין במה שפי' פני משה. לכאו', זה פשוט, אז, שיכול לצאת. אולי הו"א שכיון שמקשיב באמצע כל מילה, לא יוצא. (אולי הוא מפני השקט שלו שמפסיק ואולי הוא מפני שלא יכול לגמור בלי אותו הפסק קטן, שצריך אותו כדי להגיד לו מה יקרא. באל, קשה, שאינו חלוק מדיבור עם סידור, אם אינו יודע אותו כל כך יפה.)
** מאירה -
עיין במה שפי' פני משה. יש להעיר שהיה נראה לומר שרצה לומר שהוא מקבל קללה. (יש להוסיף שמילת "מאירה" בא ממילת "ארור.")
** ל. בשש שעים -
יש להעיר ששם כ' "וחם היום." כמו שנראה מסוף העמוד, "יום" יכול להיות משמע "שמש." אז, לא כל כך פשוט שמשמעות שלו חלוק מ"חם השמש." ותחשב על זה.
** הקורא מכאן -
צריך ביאור למה לא רק הביא מן המשנה שאומר זמן קריאת שמע (שהוא נגמר בשלש שעות). אולי היבא את היותר מאוחר, כיון שהוא יותר קרוב למשנה שלנו.
** גדי -
עיין בגמ' בסוף כריתות, שאומר שגדיים וטליים שווים. צריך לומר שאף על פי כן, רצו מה שהיה רגיל להם. ותחשב.
** קפץ -
לא מבאר מה קפץ (אם הוא החזיר או החומה או הקופה או דבר אחר). עיין בפני משה שכ' שהיה החזיר שקפץ.
** וחרב -
לא אז חרב, אלא אחר כך, מחמת זה, חרב.
** שיהא יודע -
נמצא שהשאיר אותו שם כל היום, ולא נתח אותו קודם והשאיר אותו שם. ותחשב.
** לג. רוח נמוכה -
לא כל כך פשוט לי מה החילוק בין רוח נמוכה ונפש שפלה, שחשבתי ששניהם אומרים שיהיה ענו.
** לאל שחלק לי
- לכאו', לא בא לחלוק על הבריי', אלא הבריי' הזכיר מה אמר ר"נ בן הקנה, והוא מזכיר מה שצריך לומר.
יש להעיר שאם כן צריך לומר שזה חוב. (בוודאי משמע מלשון זה של פני משה שהוא חוב.)
** לג: עליו -
לכאו', החילוק הוא שלא מזכיר אותם ביחד, אלא מזכיר שה' היה נצב עליו, ומזכיר דבר אחר ביחס לאברהם ויצחק. ותחשב.
** בשם בית ר"י -
מוזר לומר שרבי ינאי אמר דבר בשם אחר בשם בית של רבי ינאי. באמת, צריך ביאור מהו בית של ר' ינאי. אולי היה נראה לומר שהוא אשתו של רבי ינאי, כמו לשון של רבי יוסי בשבת ("לעולם לא קראתי לאשתי אשתי...").
** לד. איזהו שבע -
לא היה נראה לגרוס כן, שלשון זה כבר אומר כשמואל נגד רב. אלא, היה נראה לגורס, "איזהו מעין יח...." ותחשב. עיין בפני משה; איני יודע מה הוא אומר, אבל בילבול שלי על פני משה אינו דבר חדש.
** לה. דוד -
לומד מדוד ולא מאברהם. נראה שיותר קל ללמוד מדוד, מפני הו"א של גמ' בימוא (כח:). (לא צריך להיות שסובר כן, אבל לא רוצה לבאר כנגד ההו"א.) ותחשב.
** באיזה קיר -
לכאו', זה סותר מה שאמר שצריך להתפלל קרוב לקיר. (המפרשים כאן כתבו ששני אמוראים שונים אומרים שני דברים אלו, אף שנאמרו ביחד. זה לא כל כך מוזר לומר בבבלי, שלא אומר אותם קרובים, אבל יותר מוזר לומר בירושלמי.)
** מאתים -
יש להעיר שמסתבר שיהיו לה הרבה בנים, כיון שהיתה זונה. ויש לדון, שראיתי בבריטאניק"א שלא מצוי שזונות מולידות (ולכן יכולות להיבעל תמיד). לא כל כך פשוט למה.
** יכוין את לבו -
לכוא', רצה לומר שיחשוב כאילו בית המקדש הוא לפניו. לכאו', הענין הוא שבתפילתו לבית המקדש, יש חלק מן הטוב שבא ממה שמכיר במה שתפילתו לבית המקדש. אז, אף אם אינו כן, אם חושב כאילו הוא כן, יכול אותו טוב לבוא לו. (לדוגמא, אולי הענין הוא שעל ידי זה מכיר שכל בני ישראל מתפללים למקום אחד, ושכולנו ציבור גדול אחד. אז, יש לומר שכשחושב כאילו הוא מתפלל לאותו פנייה, חושב על אותו מחשבה, ומתקיים ענין הלכה זו.)
** היה רוכב -
פני משה מפרש שזה נגד רבי. לא מוכרח כן, שאולי "אם אינו יכול" רצה לומר שלא יכול לרדת ולכוון. הציור שיכול הוא רק אם יכול לקשור אותו (או דבר אחר שמבטיח לו שמירת החמור), שאז יתפלל אחרי שירד מן החמור.
** תל
- עיין במה שפ'. קשה, אז, איך לומדים מכאן לפנות לו. אולי כיון שמתפללים שיחזור לנו, נפנה לו. ותחשב על זה.
** בחורבתו -
מעניין שלזה מביאים קרא שאומר, "בנוי...." ותו"ת.
** לה: לאי זה -
נמצא שלא רק מכוון שהוא לפניו, אלא מכוון שהוא לאותו צד. (אם רק מכוון שהוא לפניו, היה אפשר לומר שמחשב על אחד ולא על שני. אלא, צריך לומר שהו א שמחשב שהוא לאותו צד, וכיון שממילא נמצא שהוא גם לצד של השני, מהני. מעניין שזה יקרה; אולי מניחים שיודע שהם באותו צד, ואז יודע שהוא לצד של שניהם. ותחשב. עדיין יש להוכיח שחושב על מקום שלו, ולא על שינוי מקום מקדש (כאילו נשתנה מקומו להיות לפניו). יש לדון, שאולי אילו הוא נשתנה גם של עליון היה משתנה עמו.)
** רבי ינאי -
קצת קשה מהיכי תיתי שרבי ינאי סובר כרבי יהודה בשם רבי אלעזר בן עזריה.
** לו. שהא -
יש לדון אם מספיק כשהלך ד"א בפחות מכדי הילוך ד"א (כמו אם הלך אותם מהר).
** שומע -
עיין בגרח"ק. גם יש לומר שצריך לענות אמן חשוב אחד. בחול, אף אם לא ענה להקל הקדוש, יש עוד (שומע תפלה). אבל, בשבת, אין עוד, ולכן צריך להיות שיסיים באותו זמן.
** לו: רבי יוחנן -
לא הבנתי מה מכוון לומר כאן.
** דראון -
אמר לי א.מ.וו. שגם ישעיה חוזר על פסוק שלפניו, ואינו רע, אלא הוא כאיכה.
אגב, מעניין שמה שאנו חוזרים עליו מהני. אולי צריך לומר שזה ממש חלק מן הספר.
** לז. בנחמת -
יש להעיר שזה היה הרבה שנים קודם שנחרב בית המקדש.
** לז: בית הכנסת -
מעניין, שבדרך כלל לומדים בבית הכנסת.
** ענוה -
יש לדון אם רצה לומר שלא יגלה כמה יודע או שלומד במקום שלא רואים אותו. אם לומד בבית הכנסת, אולי אי אפשר לו להשיג את זה. לא קשה- יהיו שני דרכים להגיע לזה. ותחשב.
** בן בעור -
יש להעיר שנהפך עוד לקללה. אז, אין זה דמיון כל כך טוב.
** לח. תרין זיקוקין -
נראה שאולי באו מתפילין של ראש שלו (לקיים דרשה אחרת של קרא זה).
** ישגה -
מעניין שקורא לזה שוגג, ולא אונס. לכאו', לאו דווקא הוא, וקורא לזה כן כיון שהוא גם שוגג. במילים אחרים, אולי יש שני מיני שגגה, אלא ששגגה סתם אינו אונס, שאז רק נקרא אותו אונס.
** לח: כגון רבי יוסי הגלילי -
איני יודע למה נקט בדווקא רבי יוסי הגלילי. אולי קרה שום מעשה כזה עמו, או אולי רק היה ידוע להיות זקן.
** לא כל שכן -
כמובן, זה מחודש, שלכאו' מה שיכול לומר אותו בשומע תפלה הוא מפני שגם הוא תפלה. אולי כדי לעשות שאינו כל כך קשה, יש להעיר שזה יותר קל לומר (לדחות את הכל שכןן) אם נאמר שמהני מתורת הוספה בשמונה עשרה. אבל, מגמ' לקמן מבואר שאז לא היה מהני לרבים. אלא, יוצא מאותו גמ', מהני כיון שהוא חלק מקביעות רבנן בשמונה עשרה אף שם. אולי, אז, אין חילוק. ותחשב.
** גשם -
מעניין שיש בעיה במי שמתפלל לגשם, שמי אומר שלגשם של היום מתפלל, ולא לגשם של מחר. (באמת, כן מוכח, שהרבה והרבה מן התפילות שלנו רק נענים קצת לאחר זמן, ואין אף אחד אומר שרואים מזה שלא באמת נתקבל התפילה.) אפשר שעושה סיבה תמידית. אותו סיבה הוא, במקצת הזמן רע, ואז לא רוצים בו. ותחשב.
** לט. לעבודה -
לא קל לפרש מילה זו, ויש שמוחקים אותו, ורק גורסים "שומע תפלה." עיין בפני משה, שמלשונו נראה שגורס אותו ובא לבאר אותו, לומר שרצה לומר שיחזור לשמע קולינו וימשך משם לעבודה. חוץ ממה שקשה לקרוא את זה למילים של גמ', קצת צריך ביאור למה יאמר גמ' כן, ולמה לא רק יאמר שיחזר לש"ת.
** לט: אלא בגין -
עיין ברשי שפי' שהיה שיטתו חשוב לו כיון שהיה תנא. יש להעיר שבדרך כלל הולכים אחרי קביעות הלכה של אמוראים יותר משהולכים אחרי קביעות הלכה של תנאים. (לכן, הלכה כ"הלכה" שנאמר בגמ', אף שאינו בדווקא כ"הלכה" שנאמר במשנה.) ותחשב. אולי צריך לחלק בין סתם גמ' לסתם משנה. יש לדון, שאז לא יהיה הלכה כ"הלכה" שאומר אמורא, שלא יהיה גרוע משל משנה. אולי צריך לומר שממה שאמר אותו במשנה, ואמר בו "הלכה," ולא רק סתם, יש ריעותא על מה שאמר שהלכה כן, וצריך לומר שלא באמת כל כך ברור לו שכן הוא ההלכה, ורק רצה לומר שנוטה לחשוב שכן הוא ההלכה. ותחשב.
** ולא יהא
- פי' שהוא גנאי. יש לדון אם הוא גנאי לתפילה (אני מרגיש שיש גנות לתפילה, אבל איני יודע כל כך למה, ואיך מראה שלא מחשיב אותו) או שהוא גנאי לקהל. (עיין בבבלי ביומא שאומר שמחמת טורח ציבור, כבוד ציבור הוא שלא להטריח אותם. ותחשב.)
** מ. עד -
פי' שסובר שהוא מפני שעושה את מדותיו של ה' רחמים. לא היה נראה כן, אלא נראה שהוא רק מפני שממעט רחמי שמים, שאומרים שרק עד שם הוא, ולא יותר מזה.
** על קן -
יש להעיר ש"על אותו איש לא הגיעו" הוא יותר שייך בתוך בקשה, ושאר הדברים הם יותר שייכים בתוך שבח לה'. ויש לדון.
** ביחיד -
לכאו', משמע שיש טובה אחרת בו ביחיד, ולכן לא נראה שמדבר לשני אלהויות. יש לדון מהו אותו טובה אחרת, ולמה הוא רק נוהג ביחיד. אולי רק כשבני אדם מדברים לעצמם כופלים מילים לכוונה.
אפשר לדחוק שכוונת הגמ' לומר שיש יותר בעיה בציבור (אולי מפני שנשמע לבני אדם, ואז יש לחוש למה שנראה שמדבר לשני אלהיויות), ואז יוצא שבציבור הוא רע, אבל ביחדי, להיפך, דרך תחנונים הוא, וטוב הוא. דחוק, שמשמע שנותן טעם ההיתר. ותחשב על זה.
** מא. למי הם מברכים -
יש לדון למה לא יכולים לומר שמברכים שורה אחרונה למי שלפניהם וכדומה. אולי מקשה למי מברך שורה שלפניהם. גם יש לומר שכל הכהנים דבר אחד, וצריך להיות לפני הכהנים. ותחשב.
** למי -
ואם תאמר אולי לא מברכים לשום אדם, אלא שאם לא יברכו יעברו. ויש לומר שלא עוברים אם לא עושים כלום על ידי ברכה שלהם.
** נשים -
קשה למה לא אומר שמברכים לנשים וטף. גם צריך ביאור למה לא אומר שמברכים לחזן. אולי כיון שחזן מקריא להם גם הוא אינו מן המבורכים.
** טף -
לכאו', טף לא מבינים (כמו שאומר גמ' בחגיגה), ואף על פי כן יש ענין בענייתם. ויש לדון, שאולי לא מבינים תורה, אבל מבינים ברכה זו.
** טף -
משמע שאין קטנים נושאים את כפיהם. יש לדון כמה קטנים הם טף זה, שאולי הם כל כך קטנים עד שפשוט שלא ישאו את כפיהם. ותו"ת.
** וצריך שיהא החזן ישראל -
יש לדון מה עושים בציור הנזכר- בעיר שכולו כהנים. נראה שלא רצה לומר שכדי לישא את כפיהם, החזן צריך להיות ישראל, אלא אומר שחזן צריך להיות ישראל, כדי שלא יבטל כהן מן המצווה הזו. ותחשב.
- מעשה- נמצא שכשהתפלל לבנו של רבן גמליאל, אמר שמונה עשרה עם אבות (שרק על זה תלוי).
** מא: המצוות
- עיין במה שפי' פני משה בהיקש. קצת קשה לומר ש"מצוות" יהיה משמע כל דבר שאוכל ולא מצוות ממש. אולי זה כבר בכלל "תורה," ולא רק לימוד תורה. ודע שמש"א שה'  נותן לנו מצווות, אז, קצ"ב, שמה נתן לנו ה'. אולי לא ר"ל שה' נתן לנו את המזון, אלא ברכות של המזון. לא נראה כן מן ההיקש. גם אפשר שכל העולם יותר נעשה שלנו כשקבלנו את התורה (כעין גמ' בב"ק ש"ויתר גויים"). ותחשב.
** מה: כוסמים -
נמצא שאינו אחד מן שבעת המינים. יש לדון בזה, שגבי חלה נחשב מין חיטם או שעורים (שכחתי איזה). צריך לומר שזה רק בנוגע אותו דין, אבל לא בנוגע שבעת המינים. ותחשב.
** פת טמאה -
משמע שכל דיון הגמרא הוא רק אם לא שמר אותו, אבל לא אם יודע בוודאי שהוא טמא.
** מו. דהדין -
נמצא שכשאומר, "חפץ הזה," לא רצה לומר שאומר המילים "החפץ הזה," אלא רצה לומר שאומר שם של החפץ. ויש לדון, שאולי זה או זה מהני.
** מו: גחיך -
משמע שיש צורך לנקוט הברכה שפוטר הרבה דברים. היום, עושים בדיוטק להיפך, אלא מברכים תחילה ברכה הכי פרטית. יש צד בגמ' שנעשה כן. ותחשב.
** מז. בדעתו -
יש דון אם חייב בברכה אחרונה קודם שאוכל פת. (הצד לחייב אותו הוא  שאכל והצד לפטור אותו הוא שלא גמר את אכילתו.) אם חייב, נמצא שאף שחייב בברכה אחרונה, עדיין לא מקדימים מה שיש לו מעין שלש.
** לא בירך
- נמצא שהפת טפילה לו. צריך ביאור למה אינו כ"ברך על פרפרת לא פטר את הפת" לקמן. ותחשב.
** מז: וכל הסמוך -
כ' שזית קודם לשעורה. יש לדון אם זה גם אם מברך בורא מיני מזונות על שעורים (כמו אם אוכל אותו בתוך פת הבאה בכיסנים) או רק אם אוכל אותו באופן שמברך עליו בורא פרי האדמה.
** אבל
- עיין בפני משה. יש לדון אם החילוק העיקרי הוא הסיבה ששותה או כמה שותה.
** כהדין -
עדיין יש לדון מהו הדין בהם לענין יין שבתוך המזון. ותחשב.
** מח: רב אבא בר פפא -
בהדרן, מזכירים השמות של בני רב פפא. לא מזכירים "אבא בר פפא." יש ליישב לזה בשני מהלכים- שמזכירים אותו, ושיש סיבה למה לא מזכירים אותו.
מהלך הראשון הוא שבאמת מזכירים אותו. אפשר שהוא אבא מרי בר פפא. לפעמים נקרא "אבא מרי," ולפעמים נקרא "רב אבא." גם אפשר לשנות את הגי' כאן לומר, "רב אדא בר פפא."
מהלך שני הוא שאין מזכירים אותו. אולי הוא בן של רב פפי, ולא של רב פפא, כמו גירסא של פני משה. גם אפשר שהיה בן של רב פפא אחר. (אין זה פשוט, שיש אומרים שלא היו כל אלו בנים של רב פפא אחד.) איני כל כך מבין למה אומרים עשרה בנים של רב פפא, ואז איני יודע אם יהיה קשה לומר שרק אומרים עשר מהם, והיו עדו בנים לרב פפא שלא מזכירים. (אבל, יש להעיר שאם זה נכון, נמצא שהיה לו בן הנקרא אבא מרי ובן הנקרא אבא (ובן הנקרא אדא). ויש לדון, שאולי אין שם של אבא מרי באמת אבא, אלא זה היה שם של גדולה. אבל, עדיין מוזר שיקראו לו כן אחרי שיש לו אח שכבר נקרא אבא. ותחשב על זה.
* Footnotes
[fn:1] עם יותר פרי.
[fn:2] עיין בציור שנכתב בע"ה על ענין זה.
[fn:3] גם את זה אצייר בתוך אותו ציור.
[fn:4] אגב, נראה שזה ביאור מה שאומר ה' שממליך על דברים, והוא שדרך משל הוא, לומר שמה שקרה גרם לו כל כך הרבה רוגז (או הרגש אחר כזה) עד שאילו היה דעתו יכול להשתנות, היה בוודאי משתנה להיות שלא רוצה לברוא אותם. ותחשב על זה.
