* ב.
** רש"י כי היכי -
לולי רש"י, היה אפשר להיות שהוא לרמז לו דבר בנוגע היותו חיטאת. ויש להעיר שלרש"י, לכאורה, קצת מוזר איך לא יזכור שהוא עסוק בפרה כיון שרק מחמת זה היה טהור כל ימיו ועכשיו הוא בחדר בפני עצמו. ותחשב. ואולי אין צורך לזה, אלא הוא חלק מן החומרות (והענין הוא שיזכור שיעסוק בפרה ולא יטמא).
* ב:
** גמרא דיום הכיפורים -
ק"ק, אז, למה נצטרך שני קראי.
** ואין דנים -
מעניין שעל זה לא מקשים מ"זו היא שיבה….” נראה שהענין הוא שזה אינו אומר שאין צריכים להיות כל כך דומים, אלא רק אומר שאף שצריכים להיות שווים, השווית צריך להיות במושג שאומר, ולא במילה עצמה. אם כן, כאן, שאומר מושג חלוק (רצה לומר, שזה אומר צווי שלאחר…), פשוט שאין להוכיח כלום מ"זו היא שיבה.” גם יש לומר שסמך על גמרא לקמן. ויש לדון אם זה דרך גמרא.
** לכולא -
ק"ק למה לא אומר שנעשה פייס לפני זמן פרישה, ומי שזכה נפריש. ונראה לבאר על פי מה ששמעתי מרש"ש שליט"א שאולי ענין פייס הוא שמזכה לכהן אותו עבודה. אולי צריך להיות שעבודה זה כבר בעולם- כבר עומד לבוא- כדי שיוכל לפייס עליו ולזכות בו.
** רש"י ואימא -
יש לדון למה רש"י מניח שזה רק בקרבנות צבור.
* ג.
** רש"י התם חד -
צריך לבאר חילוק בין מוסף לחובת היום. מרש"י, משמע שהענין הוא שיש דבר שנצרך, ויש מוסף, ומוסף הוא דבר שלא נצרך כל כך, ואף על פי כן, חייבו תורה. אולי הענין הוא שכיון שהוא יום טוב, צריכים אנו לעשות אף מה שאינו כל כך נצרך (בגלל שאנו יותר קרבים לה’, וזה מחייב לנו לעשות יותר). גם, אולי, יש לומר שיש טוב הבא ממה שעושה דבר אף שלא מביא כל כך טוב, אלא רק מוסיף. ויש לדון, שכיון שמביא אותו טוב, נמצא שאינו מוסיף, שעושה טוב גדול. ותחשב.
* ג:
** גמרא דרביה -
לא היה של רבו ממש, לכאורה, שרבי ישמעאל היה כמה זמן קודם רבי יוחנן (שהיה חבר של רבי עקיבא, שהיה רבו של רבי שמעון שהיה רבו של רבי שהיה רבו של רבי יוחנן (ורבי יוחנן לא היה אף תלמיד קדמון של רבי)). ותחשב. לכאו’, רק רצה לומר ששמע אותו מרבו ששמע אותו מרבי ישמעאל (ורבין רק הזכיר שנים, כמו שאומר גמרא בנזיר).
** רש"י מעלה -
לטמא מדעת- קצ"ב למה הוסיף מילת "מדעת,” שאומר שמטמאים אותו בדעת, ולא שנטמא, שהרי, לכאורה, כן היה משמעות מילה של "מטמאים אותו.” ויש לדון. והיה אפשר לומר שרש"י אומר שמטמאים אותו מדעת של הנטמא, וסובר שהמעלות אינם לעם, אלא לנטמא. ותחשב.
** תחילה למקום -
מעניין מה שאומר שלא היה עבודת משה נחשב עבודה. גם יש לדון אם מה שאומר גבי חלוק לבן הוא סימן או סיבה. גם יש לדון למה לא נקט מה שמשה היה זר. נראה שהוא מפני שלא היה משה זר (כן משמע מגמרא זבחים).
* ד.
** גמרא לטומאת ביתו -
לא הבנתי, שנאמר שרק מפני זה הופרש. ואולי אז לא היה צריך להיות בפני עצמו. קשה, שאז נאמר כן אף על יום ראשון. ואולי צריך לומר שכיון שבי"כ ובי"כ יהיה מופרש לאחר יום ראשון, וצריך להיות מופרש מביאה ליום ראשון, מצרפים את שניהם. ודחוק.
* ד:
** גמרא שהוא בבל יאמר -
יש לדון מה מחדש:
1. אין אדם יכול להגיד לאחרים מה שאמר לו אחר כשאותו אחר לא רוצה שיגיד.
2. בסתם (אם לא אמר לו שלא לגלות ולא אמר לו לגלות), לא יכולים להניח שרוצה (או שצריכים להחמיר מספק או שמניחים שלא רוצה, שכן דרך בני אדם), ואז לא יכולים להגיד.
ואפשר שמחדש שני נקודות אלו. ותחשב.
* ה.
** גמרא מתקינים -
לכאורה, עדיין צריך ביאור איך יודעים זה. ותו"ת.
* ה:
** רש"י למסבר קראי -
עיין בלשון רש"י. מרש"י משמע שיש ענין בזה רק כיון שקראי סותרים זה את זה; זה אומר שאין הענין, לכאורה, שנבין את הקראי, אלא שלא יהיה סתירה בתורה. ותחשב.
* ו.
** גמרא ותמצא ספק נדה -
כאן (במסקנא), מובן למה אומר שתמצא ספק נדה, ולא שתמצא נדה ודאית, שבדרך כלל לא תדע בוודאי שהיתה נדה כשבא עליה. לא ידוע, עדיין, למה אמר גמרא כן בהוה אמינא. אפשר שידע גמרא מסקנא (לכאורה, רצה לומר שהיה לשון ידוע, ודן גמרא איך לפרשו, אם אומר שהיא בשעת ביאה ספק נדה, או לאחריו ספק נדה). גם יש לומר שאז אינו כל כך קשה למה בא עליה, שאינו רשעות כל כך.
** אטו ברשיעי -
יש להעיר שהיו כמה מן הכה"ג (בימי בית שני) שהיו רשיעי. ואולי גמרא מקשה למה נתקן בשבילם (כדי שלא יטעו). ויש לדון, שאולי הוא כדי שלא יהיה עבודה פסולה (מפני שה’ רוצה בעבודה, ובני ישראל צריכים עבודה). ותחשב.
** כר"ע -
משמע שהבעיה הוא שלא יוכל לעבוד, ולא שיהיה נמצא שעבודתו פסול. משמע שכיון שמותר לו לעבוד, יהיה עבודה מרצה אף אם, באמת, הוא טמא. ותחשב. (ואולי ת’ ר"י חוזר על זה, ורק אומר סימן שכולי עלמא מודו שנעשה טמא. ודחוק, שלכאורה, פשוט שנעשה טמא אם היתה, באמת, נדה.)
* ו:
** גמרא באותו בית אב -
בפשטות, החילוק בין הותרה לדחוייה הוא שאם דבר הוא הותרה, אין ס"ר שם, ואם הוא רק דחוייה, יש ס"ר, אלא שגם יוצא ממנו טוב (שדוחה את הרע), ועל הכל הוא טוב לעשות אותו. לכאורה, צריך לומר לצד זה שאינו ממש הותרה, שאז לא יהיה צריך לעבוד בטהורים, אלא רק רצה לומר שיש לו כוח גדול להידחות, ואף מה שרוצים להשאיר העבודה ביד אותו בית אב דוחה. גם אפשר שאין ס"ר, אבל רק באותו מצב. ויש לדון למה יהיה חילוק בזה. ותחשב.
* ז.
** גמרא במזיד -
צריך ביאור למה אין זה קשה לשני שיטות, שאף אם דחוייה, היה לו לזורקו. ואולי רצה לומר שדם נטמא במזיד. וחושב אני שדן גמרא בזה (פסחים?).
* ח.
** גמרא הזאה כלל למה לי -
יש לדון, שלעיל מבואר שאולי אם בבית אב יש טהורים, לא הותר.
* ט:
** גמרא סנינא לכו -
יש לציין לגמרא בתחילת סנהדרין שמשמע שיצא מארץ ישראל.  אם כן, היה מן העולים עם עזרא (על כל פנים, אין סיבה לחשוב שלא היה מן העולים). יש לומר ששם רק היה בא"י כדי ללמוד, אבל לא דר שם. גם יש לומר שאמר זה לסימן לומר שדירה בבבל רע. ותו"ת.
ואפשר שרבה בר בר חנא ורבה בר חנא הם בני אדם חלוקים.
** ר"א -
אם היה ר"ל כ"כ יותר חשוב ממנו, יש לדון מה היה ההוה אמינא שילמוד ר"י עמו אחר מיתת ר"ל.
* י:
** גמרא דילמא -
קשה, שמצינו כמה פעמים מעשר דרבנן.
* יא:
** גמרא ביתך ולא ביתה -
דרשה זה צריך ביאור, שכיון שנאמר לאותו אדם, אף לאשה היה לו לומר "ביתך,” אלא רק היה לניקוד להיות חלוק.
* יב.
** גמרא אני לא שמעתי -
יש להעיר שאם כן, מה שאומר רבי יהודה ומה שאומר רבנן אינם כל כך שייכים זה לזה, שאין מה שאומר ר"י שייך לפטור ירושלים, ואינו רק שם. ותחשב.
** רצועה -
יש לדון אם רצה לומר שכל מה שבמקום שאין יסוד, קרוב למזבח הוא של יהודה, או שאף חלק מן המזבח עצמו, או כולו, הוא של יהודה.
* יב:
** גמרא שלא ישתמש -
יש לדון אם הוא לטעמיה כיון שלא דורש שטעונים גניזה, ואז יכול כוהן אחר להשתמש בהם (ואולי רבנן סוברים שטעונים גניזה כיון שאין אחר יכול להשתמש, ונמצא שלא חולקים על ר"ד ביותר ממה שחלקו עליו כבר), או שמה שאומר שאין כה"ג משתמש בהם הוא מפני שמסתמא כבר משתמשים בהם כ"ה (ואולי אז אינו ראוי לו). ותחשב.
** רש"י את השחקים -
עיין בפשט שני. נמצא שאין הענין רק שילבש בגדים טובים כשמביאו לרבו, אלא אף שלובש פחותים כשמבשל אותו. ויש לדון למה; ואולי אז יעשה אותו יותר טוב, שלא יחוש לבגדיו. ונראה שאפשר שהוא רק אומר שאותו בגד עצמו (ולא רק אותו מין) לא ישמש בה, ואז, ישמש בבגדים שחוקים שלא לאבד בגדי הקדש.
** תוס’ כה"ג משום איבה -
עיין במש"כ תוס’. ודע שהיה אפשר לומר שיש חיוב לעבוד בשמנה בגדים רק כשיכול (שכיון שהיה יכול לעשות יותר, ולא עשה, פסל את עבודתו). אם כן, אין להק’ כמש"א תוס’.
* יג.
** גמרא שאם מת -
לכאורה, יש בזה חידוש במה שלא אומרים שהוא נראה ונדחה. ותחשב.
* יג:
** גמרא אי חזי דקא בעיא -
לכאורה, אפשר לומר כן אף לאחר מיתתה.
* יז:
** גמרא אבל הכא -
עיין בזבחים, שחושב אני שלומד דבר מדבר שהוא "חושבנא בעלמא.” וע"ש.
* יח.
** גמרא לא היו מניחים -
אף שמצווה לאכול.
* יח:
** גמרא רב כי מיקלע -
סמיכותו משמע שהוא כדי שלא יראה ש"ז ותבזה.
** רש"י באיוב -
מעניין שקורא לאיוב דבר המושך את הלב, שהוא, לכאורה, קשה להבין, ורובו רק דבורי פילוסופי.
* יט.
** גמרא צדוקי -
נמצא מגמרא זה שמניחים שוויות בין צדוקי למי שאינו ירא שמים. יש לציין לגמרא לקמן שאמר צדוקי שהיה רוצה שדבר זה יבוא לידו ויקיימנה.
* כ.
** גמרא תלת מאה -
ואם תאמר הרי זה שנת חמה. ויש לומר שאומר האבריי"ז של השנים (כיון שיש לנו מעוברות).
* כ:
** גמרא תנו רבנן -
מה שלא מזכיר קול נשמה במאמרות שלעיל (שהיה נשמע אילו…) הוא מפני שכבר בטל, כמו שאומר גמרא לקמן. ולא הבנתי כל כך למה בטלוה, שלא היה נשמע, שגם היה קול רומי וקול גלגל שמש. ואולי בשלש, אחד מבטל אחד, ושלישי נשמע. יש לדון מה יבטל מה. (ועיין בגמרא, שואמר שאולי אינו שלש, אלא ארבע או כדומה. ואולי גופא חולקים מתי יבטל.)
** רש"י לא היה אמורא -
עיין במה שפירש. עיין ברש"י מגילה (ד.) שמבאר שהיה מלמד בלשון הקודש (ולא רק, לכאורה, לתלמידי חכמים, שאותם שטעו שם לכאורה, לא היו ת"ח כ"כ). ותחשב.
* כא.
** רש"י דמו בראשו -
מעניין איך מפרש אותו, שהיה אפשר לומר שרק אומר שגרם מיתתו, ולא שהעוון הוא על ראשו. ותו"ת.
* כא:
** גמרא לחים כיבשים -
יש לציין לגמרא זבחים שאומר גמרא שיש צד שלא ייתן לתוך המערכה יין, שמכבה אותו במקצת. ותחשב למה יהיה חילוק בזה בין יבש ללח. ותחשב.
** רש"י הא לן -
לא הבנתי למה הרים ובקעות עושה שמיבש יותר. ואולי רצה לומר שההרים אין להם מים, שנופל מהם לבקעות. קשה, אז, למה מזכיר הבקעות. ותחשב. ואולי רצה לומר שרוב מימיה הם בבקעות, ואינו יכול להיכנס לקרקע כיון שהוא כל כך מים, ואז, נתייבש. ותחשב.
* כב.
** גמרא לא חשיבא -
יש לדון אם רצה לומר שאז לא היה צורך לתקן פייס (ויש לדון למה יותר טוב שלא לתקן. ואולי אז יבואו יותר בני אדם. גם יש לומר שטורח הוא לפייס.) או שרצו שבני אדם יבואו, ואז לא תקנו פייס, כדי שיבואו (ואולי, אז, הודו שהיה צורך לפייס כשהיו כל כך בני אדם שם שיבואו מחמת שאין פייס).
* כב:
** גמרא רמי -
היה אפשר לת’ שהוא לאו, ולא הבטחה. ונראה שאולי מקשה איך נאמר שהם כחול הים- אם כן, אי אפשר להיות לאו למנותם, שאינו אפשר. ויש לדון, שיכול להיות שאסור לקצור מקצתם. ואולי לשון הלאו לא משמע כן (ואז, אולי אף אם יש איסור במנין מיעוט בני ישראל, עדיין אין לפרש כן בקרא).
יש להעיר שאז ת’ גמרא ש"כאן ע"י אדם…" לא מובן אז.
** כאן בידי -
לכאורה, רצה לומר שיש להם מנין באמת, אלא הוא כל כך גדול שאי אפשר למנותם. צריך לבאר מה משנה בין קשיא לת’, שבוודאי ידע שיש ממש מנין. אם כן, רק משנה אם חול הוא דבר הנמנה בידי אדם. זה מוזר. גם יש לומר ששינה אם חול הוא דווקא (והוא רק נמנה מבני אדם) או לא (ורק רצה לומר דבר גדול).
** מתעשר -
יש לדחות בקל שמלך שאינו כיון שיכול לקחת ממון ממס.
** הא איפרעו -
יש להעיר שעדיין לא הפריעו ממנו כמו שפרע משאול (שנטל ממנו לגמרי את המלוכה).
** כרב נמי -
לכאורה, רצה לומר, “ואב"א כרב…” לשונו מוזר. ואולי רצה לומר שידע שסובר כשמואל. ואף אם היה סובר כרב….
** לרב נחמן -
נמצא שקורא לרנב"י בשם ר"נ סתם (כשיטת רש"י). ונראה שאולי זה רק מפני שכבר אמר רנב"י (וכמו כן מצינו שיקרא ריב"י ר"י אם כבר אמר את כל שמו). ותחשב.
* כה.
** גמרא עבודת יחיד -
צריך ביאור למה רק עובד עבודת יחיד, ולא עבודת ציבור (כיון שבין כך ובין כך גמרא אומר שצריך למוסרו לציבור). ותחשב. ואולי יש לציבור זכות להשיג להם כפרתם מדבר שבא מממונם. ויש לדון, שנאמר כן אף ביחיד, ויהיה יכול ליתן בגד ולכוף כהנים ללבוש אותם בקרבנותיהם. ויש לדון.[fn:1]
* כה:
** רש"י תליסר -
לפי שהיא עבודה- ביאור זה מעניין. ותחשב. עוד יש להעיר עליו שני הערות:
1. מעניין שקורא אותו עבודה, כיון ששחיטה לאו עבודה.
2. מעניין שלא אומר שהוא מחמת ששחיטה אינו עבודה שאינו צריך להיות במי במי שרחץ ידו. ואולי כן מכוון, ורק אומר סימן לו. ותחשב.
* כו:
** גמרא אתרוגיהם -
יש לדון בראיה זה, שאומר גמרא סוכה שאנשי ירושלים היו רגילים ללכת בלולביהם בידיהם כל היום. לכאורה, כוונתו הוא שכן עשו בכל ארבע המינים. ותחשב.
** אתרוגיהם -
יש להעיר שמצינו שאף אז נטלו אתרוג בבוקר (אף שלכאורה, אין חיוב לזה).
* כט.
** רש"י הרהורי -
עיין במה שמבאר. וזה מעניין ו,חושב אני, אינו ידוע.
* כט:
** גמרא ניהדר קומציה -
יש לציין לגמרא מנחות, שלכאורה, חולקים תנאים בזה.
** רש"י דקמותיב -
יש להעיר שלאידך גיסא, כיון שהוא ברייתא, יש לומר שחולק. ותחשב. משמע שהוא יותר מסתבר לומר שאמורא טעה בברייתא מלומר ששני בריי’ חולקים. זה מעניין, שמצינו כמה וכמה תנאים חולקים. ויש לומר שמוזר שלא יביא ברייתא חבירו החולק.
* ל:
** גמרא לא מצורעים -
לכאורה, רצה לומר שאז אינו נקרא לשכת מצורעים. ויש לדון אם זה אף אם אומר שאינו רק מצורעים (שיש לומר שהיה עדיין רוב מצורעים).
* לא.
** גמרא שכל גופו -
היה אפשר להיות רק אמה אחד גובה, והיה שוכב בו. ותו"ת.
** רש"י שמה ביאה -
שדן גמרא בו לענין שאר דינים, ולא מביא כל דיון זה כאן.
* לג:
** גמרא עבורי -
קשה, שהרי גמרא במנחות דורש דין זה מקראי (“כל זמן שהם בין עיניכם יהיו שנים). ותחשב.
גם קצת צריך ביאור למה מניחים שמגביה את השל יד קודם, אי לא שכבר יודעים דרשות אלו. ותחשב.
* לה:
** גמרא רשע -
מעניין שאומר שם זה על מי שנראה יפה. ונראה שהוא כמו שקורא לאותו עבירה בשם עבירה סתם בכמה מקומות, אז גם קורא למי שעומד יותר לו רשע. ודחוק. ונראה, אולי, שכך הוא פירוש גמרא בסנהדרין שאומר ששמא יאמר אדם שבא ממשפחת רשעים (שבא מרשע). שם, הקשה שיח שי אטו לא היה אחד במשפחה שלא היה רשע. ונראה שרק רצה לומר שכוללם עלילים לרשעות, ואז יחשב שלעולם יהיה עליל לזה. וזה אולי יותר מסתבר להיות ברוב משפחתו.
ונראה שאפשר שמי שממש עבר קורא רשע, ומניח שעבר כיון שהיה נאה (או, על כל פנים, זה היה טענת רשע לפטור את עצמו). אם כן, מי שלא חטא לא נקרא רשע. ותו"ת.
* לו.
** רש"י ועל -
יש לו וידוי- עיין במעשר שני (ה-י) שמבואר שיש וידוי אף על לקט שכחה ופאה, ורק אין מעכבים את הווידוי (שיכול להתוודות אף אם לא הוציא אותם מביתו). ונראה שעל נקודה זה קאי (ואפשר שעליו עצמו קאי או שהוא סימן, שכיון שאינו מעכב, מוכרח שאינו קאי עליו כל כך). ותחשב.
** רבי עקיבא -
יש לדון למה תלוי בעונש:
1. אפשר שהוא שכיון שנתן בו תורה עונש, מוכרח שלא כיוון שיביא עולה, שאם הביא, היה מכפר, ולא היה צורך לעונש. ויש לדון, שאולי העונש הוא לכשלא הביא את העולה.
2. אפשר שחיוב קרבן על חטא הוא מטעם עונש (כמו שכ’ רש"י על עשה של לאו הניתק לעשה[fn:2]). אומר שכבר אומר עונש אחר. לא נראה כן:
  1. אפשר שיש שני עונשים. ויש לדון, שיש כלל שאין לדבר שני עונשים. ודע שעדיין מצינו לפעמים חיוב כרת ומלקות. ואולי אין כרת עונש.
  2. לכאורה, אין חיוב להביא עולה; אז אי אפשר שהוא עונש. ותחשב.
* לז.
** רש"י יהושע בן גמלא -
צריך ביאור למה מניח רש"י שאלו היה כ"ג; משמע שאי אפשר לאדם אחר לתקן דבר בבית המקדש. ויש לדון, שיש מאלו שהיו רק נדבות והוספות לבית, ולמה לא יכול כל מי שרוצה לעשות כן. וצ"ב.
* לח:
** גמרא דהא כתיב ושם רשעים… -
צריך ביאור למה לא למד ממה שקרה לפני כן להשיב לו על מקור לזה. ויש לדון (שאפשר שאין כל כך הוכחה ממה שאמר לשון זה לשאלה חלוק. ועוד, אולי יש הוכחה נגד זה, שכבר גילה המשיב מה שמשמע לשון זה לו, ואז מניח שהיה השואל זוכר זה, והיה שואל על דעת כן. ויש לדון.). (ואפשר שהיה מכוון ללמדו לשאול בלשון יותר מדוקדק).
** שוב אינו חוטא -
קשה, לכאורה, ממשה רבינו. ויש לומר ששם לא קיים מצוות לרוב ימיו, שלא היה אז תורה. כמו כן, יש לומר שנעשה בריה חדשה בקבלת התורה, ומה שכבר עשה לא היה מהנה לו. לכאורה, זה לא יהני, שאף היה לו רוב שנותיו של אחר קבלת תורה (אבל עדיין ראשון יהני, שנמצא שלא קיים כמצווה לאוב שנותיו). ותחשב.
ויותר נראה לומר שכמו שמצאנו שיש מילים (כמו עבירה) שיש להם משמעות של חטא מיוחד, אף למילה זה יש משמעות כך. יש לדון על מה קאי, אם הוא על ג"ע או כפירה או כעין זה. ותחשב.
* לט.
** גמרא משל -
משמע שיש טוב ביחס ה’ למצווה[fn:3]. ותחשב. ואפשר שרק אומר זכר לדבר, אף שהוא לסיבה חלוקה.
** עבירה מטמטמת -
רגילים בני אדם לומר כן על איסור דברים הנאכלים. יש להעיר שגמרא זה משמע שהוא כל איסור (שאומר לשון עבירה סתם, ודחוק לומר שמכוון רק לאכילות)[fn:4], ואף משמע שיש טמטום שווה, שאם היה אפשר לחלק, לכאורה, לא היה יכול ללמוד מאכילות. ותחשב.
** כי הדדי -
לא הבנתי, שלכאורה, סבר שהשמאל עדיף. ותחשב. משמע שהענין הוא שהם שווים, ואז בוחרים בכבוד כה"ג. אם כן, צריכים לומר ש"עדיף" לא קאי על כל פקטור (ואולי רק אומר טובה של המצווה- מה עושה המצווה באופן שנעשה יותר טוב, ולא מה שעושה שאר טובים. ותחשב.)
** יש אוכלו -
היה אפשר לומר על פי מהלך בעלאבתיש שאולי לא היה ממש ברכה בו, אלא שבאותו דור הרבו בשיעורים, וממילא היה יותר לכל כהן גדול, ואז כל כוהן היה צריך רק לאכול כזית. ולא נראה, שלא מאנו שהרבו. ועוד שבדרך כלל, מניחים שאין אכילה קבע עד שהוא כביצה (או כעין זה). אם כן, היינו צריכים לומר שכפלו את השיעורים, וזה אינו אפשר (גמרא מנחות).
* לט:
** גמרא ולא היה -
יש לדון אם זה היה הפעם הראשון שלא הלבין או שאומר שמאז לא הלבין שום שנה. (עיין לעיל שגמרא אומר שלאחר שמעון לא הלבין. יש לדון מתי היה.)
** גער ריב"ז -
יש להעיר שלא היה מלמד כבר תורה אז (שלימד לארבעים שנה (סנהדרין), והרי חי אחר החורבן.
* מא.
** גמרא תיובתא דמד"א -
יש לדון למה לא מזכיר את שמו (כמו שרגיל לעשות).
* מו:
** גמרא דהותרה -
לכאורה, היה אפשר לומר להיפך, שאין כולו הותר, שאולי רק זה חלוק כשהוא באותו מצב, אבל בדיחוי, שראינו כוח זה לחלק ממנו, מסתמא יש כוח כעין זה לחלק אחר. ותחשב.
* מז.
** גמרא וראתה -
יש לדון למה לא ימנו את הראשון שמנו כשנפסל אחיו. ואולי כבר מת. אם כן, לכאורה, לא היה כל כך זכות לאמו. ואולי אף הוא נטמא או כדומה. וזה מוזר.
* מז:
** גמרא הדר פשטה -
צריך ביאור למה זה נקרא פשיטות, שאמר שהוא מסופק בו.
* מח.
** גמרא קס"ד -
מצינו, אז, קס"ד שלא דוחה גמרא (ואף לא מקשה עליו).
* מט.
** גמרא לי התיר -
כיון שהיה ר"ח רופא, לכאורה, אין כל כך הוכחה ממה ששאל לו ריב"ל. ואולי הראיה הוא ממה שקרא אותו ר"ח, ולא חנינא.
** וחיה -
לכאורה, אין ראיה ממה שידע כן, שראה, אלא מביא ראיה ממה שהיו בני אדם מראים אותו מכות.
* מט:
** גמרא בשיניו -
ק"ק, שגמרא לעיל אמר שאין עובדים בשינים.
** בפר -
אם דם פר, ופר מת, קרויים פר, צריך ביאור למה אין אומרים שאז אינו שינוי לדיני גזילה. ותחשב. ואולי פר של קרבנות חלוק כיון שעומד למות, ויכול לעשות תכליתו רק על ידי זה.
* נ:
** רש"י פשיטא -
הוי בעליו- לשון זה מעניין, שמשמע שתלוי בקנין. ויש לודן, שאולי רק רצה לומר שהוא השליט בו.
** המקדיש -
בעלים- נמצא שאומר לשון זה אף על יחיד, אף שהוא לשון רבים. כן נוהגים בני אדם היום.
* נא.
** גמרא מי דחי -
אומר גמרא את זה בלשון פלא ותמיהה, אף שמחלקת הוא לקמן ובפסחים.
** מפני טומאה -
לכאורה, פשוט שאין אומרים כן אם הותרה בציבור (שלכאורה, כן הוא כאן, שהרי אם אין רובם טמאים, אין לומדים מקרבן פסח). ויש לדון, שעדיין אינו קרבן ציבור, אלא רק רוב המביאים אותו טמאים. ותחשב.
* נב:
** גמרא אתיא -
יש לדון אם דורשים אלו לדעת מה קרה לו או שדרש יאשיהו את אלו. ותחשב. ואם תאמר איך דורש מאלו שהיו קודם שלקחו (ואז מוכרח כשני). ויש לומר שאמר עליו קרא שעתיד שיילקחו.
** רש"י ויעלו -
עיין שם (בחגיגה) שאומר נפק"מ אחר.
* נג:
** גמרא אל תהי -
משמע שאמרו לו את המשנה. משמע שהיה להם משנה אף אז (בימי בית שני).[fn:5]
* נט:
** גמרא סתום -
נמצא, לכאורה, שחולקים אם יותר דומה כשהוא בצד השווה או הצד השווה לנגדו (רצה לומר, שזה לנגד המלמד שווה לזה לנגד הלמד). ותחשב.
* ס.
** גמרא האמור על הסדר-
יש לדון מה ממעט מילים אלו.
* סא:
** גמרא ולראב"ש -
ק"ק, שהרי אין קרא שאומר שאין מזים הזאה שני פעמים (כמו שיש כאן). ותחשב.
* סו:
** גמרא זאת אומרת -
לא הבנתי הראיה, שאולי החידוש הוא שיכול לדחות עוד איסור (שאולי הוה אמינא שיש בו כוח רק לדחות אחד, ורק לדחות איסור שאין בו חיוב מיתה). ותחשב.
** התראה -
כיון שבין כך ובין כך היה ממית שניהם, קשה מה לנו בהתראה. משמע שיותר קשה אם עברו בהתראה. ויש לדון, שואלי מיתת משה היה בידי אדם, ואז הוצרך להתראה, אבל של שמים לא היה צריך.
** תנוח -
יש לדון למה הונח דעתו, שאמר שחכמים שנאו את בני בבל, והרי היו אבותיו מבני בבל. ותחשב. ואולי לא היו חכמים שונאים אותם, אלא בני אדם שם, ולכן בני אדם כינו אותו שם.
* כתבתי שאר הערות מזה בנייר
* Footnotes
[fn:1] היה אפשר לומר, אולי, שאף אם כהנים אינם שלוחים שלנו, זה רק לקרבנן יחיד, שאין יחיד מביא אותו קרבן, ואז אינו צריך להיות שליח, בהכרח, אבל אם יכול להיות שליח, כמו בקרבן שלציבור, נעשה שליח. כיון שכן, עושה בעד הציבור, וצריך ללבוש את בגדיו. יש להעיר אם כן, אף גבי מי שעובד לכוהן נאמר כן. ותחשב.אם כן, נאמר כן גם כן בקושיית גמרא במה שאומר שכה"ג הוא שלוחינו. ויש לדון, שאולי כיון שיש רק כה"ג אחד בציבור, חלוק מכאן, שיש הרבה כוהנים בציבור. ותחשב.
[fn:2] אגב, זה מעורר שיש להקשות למה לא אמר שכבר יש עונש על לאו הניתק לעשה, והוא העשה. ותחשב.
[fn:3] לכאורה, זה מוכיח שאין ענין של קיום מצוות שממליכים ה’, שעושים שאנו עמו, שהרי אין אדם ממליך את עצמו. ויש לדון, שאולי יש טוב גם כן כשה’ אומר שהוא המלך.
[fn:4] הדרך לומר כן הוא לומר כמה שכתבנו לעיל שמצינו שמילת עבירה יכוון לעבירה מיוחדת, אלא שבדר"כ, לא מכוון לאכילות אסורות, אלא לביאות אסורות. ויש להעיר שיש דמיון בין שני איסורים אלו במה שהם איסורי הנאה. יש לדון אם זה שייך.
[fn:5] ודע שלכאורה, זה דבר מסתבר, שהרי היו כבר הלכות, והיו צריכים לשנות אותם, וממילא היוו משניות.
