** ב. מי כתיב האור -
יש לדון מה היה אז. אולי היה יכול להיות שם דבר ואולי היה מוכרח להיות שם דבר. ר"ל, יש לדון אם זה סיבה לומר כצד שהוא שם דבר, או סיבה שלא לומר כצד שמפרש גמרא עכשיו לדחות הצד שהוא שם דבר. הצד הראשון הוא שאילו היה כתיב מילה שאינו ידועה, ואחר כך המילה הידועה, היה אפשר לומר שהוא מפרש אותו. אבל כיון שלא כתיב כן, צריך לומר שאינו מפרש אותו. הצד השני יהיה שנוכל לומר שאומר שבקר האיר רק אם אומר הבקר אור, ולא אם אמר האור בקר. יש לדון בזה.
וצריך לעיין לקמן ולדון בכעין זה בשאר "מי כתיב" שיבואו לקמן.
** ב: הרחקה -
יש לדון אם חלוק כיון שהוא הרחקה או כיון שקאי על דין דאורייתא או כיון שאי אפשר לו להיות כל היום, שכבר יש דאורייתא, ואז אי אפשר שגזרה יוסיף דין זה על כל היום. ותו"ת.
** דתני שמואל -
יש לדון ל"ל אומר שמואל לשון מעליא.
** אורחא -
יש לדון מהו תירוץ זה, שעדיין לא טוב לדבר עליו. ויש לומר שזהו ארוחא, וכל לשון היה עושה שבני אדם חושבים על זה, שכך מוכרח להיות. ותחשב.
** ג: אין בודקים -
יש לדון אם מקשה למה הוצרכו לבדוק או איך יהיה שלא מצאו בו שמץ פסול פעם ראשון. לכאורה, תירוץ שני של גמרא אי אפשר לצד שני, ואז צריך לומר שמקשה כצד ראשון. אפשר שמקשה שניהם, ותירוץ שני רק לא קשה לו קושיה שניה. אולי קצת משמע מרש"י כך, שרש"י מיישב קושיה שניה.
** אליה לגבוה -
לכאורה, היה לו להיות חכם עכשיו שלא לומר מי אמר לו. נראה שחשב שהיו משקרים.
** וקטלוהו -
נראה שחייב מיתה כיון שעל כל עבירתם חייבים מיתה. אם כן, צריך ביאור למה אין זה נמנה במצוותם. אז, אולי נראה יותר לומר שאין זה בכלל מצוותם, ומה שחייב מיתה לא היה מן הדין, אלא שלא יעשו אותו עוד. אם כן, לכאורה, צריך לומר שמצווה זה הוא ציווי על בני ישראל שלא לתת לגוי. ויש לדון ל"ל יצווה ה’ את הגוי, ורק יצווה את ישראל.
** ד. אמא -
אפשר שכך היתה שמו, ואפשר שלאביו קרא לו בשמו ולאמו לא קרא לה בשמה. יש לדון למה. עיין ברשי, שנראה שקצת משמע שהיה שמה.
(ונראה שאולי חשב ר"ח שרב היה מרגז ואומר שכיון שלא קראת להם בלשון כבוד, לא אענה על אבא, ואז תשאל על אמא- ואמר לשון כבוד- ואענה. דחוק.)
** דן ידין -
ואם תאמר זה רק אומר שידין, ולא שירצה שידונו אותו. ויש לומר שכיון שחשוב שדיין טוב, רוצה שידון אותו, שאיך יעשה גדול כזה טעות. ויש לדון. גם יש לומר שדן ידון עמו ר"ל שידון שבטו (כמו שאומר גמרא בהוריות). אם כן, אומר שדן ידין עמו, שעמו ירצה שידון אותו. אז, אומר שעמו ירצה דיון. ותחשב.
** וישכם -
ואם תאמר אולי רק הקדים כל זמן שיכול, אבל לא הקדים בלילה כיון שאין מלים בלילה. נראה שמרשי משמע (ויש לדון מהיכי תיתי) שהקדים בתחילת עלות השחר, אף קודם הנץ החמה, ואף שטוב להמתין עד שעת הנץ החמה. (עדיין אולי אפשר לחלק לומר שהיה שעת חיוב עדיין).
** בשעה שבני -
מלשונו משמע שיש שני סיבות. יש לדון אם צריך שניהם. לכאורה, צריך ביאור למה נצטרך שניהם. ותחשב.
** בשעה שבני -
יש לדון אם הענין הוא שלא להטריח אותם יותר או כדי שיזכרו.
** ד: מדרבנן -
יש לציין לגמרא בתחילת גיטין, ששם צריך סיבה עם מה שהוא דרבנן. נראה שהחילוק הוא ששם רק צריך נאמנות מדרבנן, אבל כאן צריך נאמנות בדבר שצריך מדרבנן. ותחשב.
** כמקח טעות -
ה"כ" מעניין; רש"י לא גורס אותו.
** לילי חמשה עשר -
קשה, אז, מה נעשה עם "אך.”
** אפילו באתרא -
אז:
1. אינו נוטל כל כך מצווה.
2. מחסר כיס.
3. כבר גילה שלא רוצה במצוה זה כל כך, ששוכר אחר, ולא עושה בפ"ע.
** זמן שחיטה -
יש לדון, אז, אם זה נוהג אף בזמנינו, שאין קרבן פסח. ותחשב.
** ה: אלא שריפה -
יש לציין לרא"ש (כן אני חושב) שפוסק כרבי יהודה שסובר כן. נראה שהוא מפני שרבי יהודה איתותב לשיטתו, אבל מצאנו תנא אחר שסובר כן- רבי עקיבא כאן- ואין עליו קושיה. ותו"ת.
** הבערה לחלק -
מניח ש"אב" אומר שחייבים עליו כרת. גם מניח שדיני שבת ויו"ט שווים. יש לדון מהיכי תיתי.
** כלפי לייא -
יש לדון מהו הסברה כאן. ותחשב.
** דעתו לחזור -
צריך ביאור מה לנו אם דעתו לחזור או לא, לפי רש"י שהחשש הוא מפני לא יראה ולא ימצא. משמע כתוס’, שהוא מחמת חשש שמא יאכל חמץ בפסח.
** שלשים יום -
מעניין שתלוי בזמן שבו ילמד הלכות פסח. אולי הענין הוא רק שאז יותר קל לו לבדוק, שיודע ההלכות. אז, רק אז חייבו אותו. ותחשב.
** ו: חשיבי -
לכאורה, ר"ל שיש לו יחס חזק לו, במה שהוא משמר אותם. ותחשב.
** וכי משכחת -
קשה, שכמו שחוששים שישהה בביעורו, נחוש שישהה בביטולו. ותחשב. שוב ראיתי שכן מקשה תוס’ על רש"י.
** ז. שרבו ימי מצה -
ר"ל שכבר לזמן רק נתן בו מצה. אז, מניחים שהוא הדבר האחרון שיכול להיות, כדי שנניח שמה שלא מצא אותו היה לזמן מועט, והוא מצה.
** ז: לא סגיא -
ואם תאמר אם לא משמע כן, איך נאמר כן. ויש לומר שמשמע כן, אבל לא כל כך. אז, יותר טוב לומר "לבער.” גם יש לומר שמה שלא משמע כלל עתיד הוא שאילו היה רוצה לומר עתיד, היה לשון יותר טוב לומר, והוא "לבער.” כאן, אין לו לשון שיותר טוב שיאמר.
** יצא -
קשה ל"ל צריך לברך קודם שיקיים המצווה.
** בכל הג"ש
, יש להעיר שכל דין בדיקה הוא רק מדרבנן.
** ח. כל מקום -
יש לדון אם דן מה שנחשב מקום שלא מכניסיים בתוכו, או אם דן למה צריך בבא זה כלל, או אם דן למה צריך מילת "כל.” תלוי על זה יהיה מהו התירוץ, שלשני ושלישי, צריך לומר שאלו מחודשים במה שלא נכנסים בתוכם חמץ. ותחשב.
** ח: פלימו -
ואם תאמר מהיכי תיתי שאין פלימו מיירי כשנפל. וישל ומר שאם נפל, אין להבחין אם הוא בתוך מקום שידו מגעת או לא. אז, צריך לומר שאין ת"ק מיירי בציור כזה; ואז לא מסתבר שפלימו, שקאי עליו, דן באותו ציור.
** שאין דרכם -
שיש להם מזל, כמו שאומר גמרא ב"ק (שמועד לבהמה אינו מועד לאדם). שו"ר שרש"י מוסיף כן כאן.
** בתר דבדק -
מעניין שמה שאין בודקים שם לחמץ יעשה שלא יבדוק למחטו, שהרי היה בודק בלי דין בדיקת חמץ, שהרי בדק אחר שכבר קיים בדיקת חמץ. ויש לדון, שאולי חושב שמקיים במקצת דין בדיקת חמץ, שבודק, ואם ימצא חמץ, יבער אותו. ותחשב.
** ט. מ’ יום -
לא הבנתי למה יהיה השיעור מ’ יום, שקשה למה מניחים שלא זנה עד שבא לכאן. ותחשב.
** ואין ספק מוציא מידי וודאי -
ק"ק ל"ל יאמר ר"ז כן. אולי סובר שספק מוציא מידי וודאי. ותחשב. גם יש לומר שלא סובר שהוא וודאי שהוא שם, שאם אכלו, לא נח כאן כלל, אלא לעולם מקומו היה בחולדה. ותחשב. גם יש לומר שסובר שלא נחמיר מחמת אין ספק מוציא מידי וודאי בדין דרבנן.
** ט: שמא תטול -
אם חושבים שכן יקרה, אז היה לנו לחוש שיקרה, ואף אם לא נצטרך לבדוק לו. ותחשב. ואם תאמר אם לא מניחים שקרה, ק"ק למה מניחים שיקרה. צריך לומר שגמ’ ר"ל שלענין בדיקה, לא חוששים די עד כדי שנחייב אותו, אבל עדיין אפשר הוא. ותחשב.
** י. דר"א ורבנן -
קשה, ששם ספק טמא, ואז דנים אם אף ספק כזה טמא. כאן, לכאורה, כיון שדין דרבנן הוא, ספק יהיה מותר. אז, קשה למה נאסור. ותחשב. ועיין ברש"י. עדיין לא משמע כן כל כך מגמ’.
** י: אתי למיכל מיניה -
צריך ביאור איך זה טוב בלשון משנה, שצריך ביאור למה אומר שלש זמנים, שהיה לו לומר שיבדק עד זמן ביעור. ותחשב.
נראה שאומר שלכתחילה, יבדוק בלילה כדינו. אם לא בדק, יבדוק בשחר. אם לא בדק בזמן היתר חמץ מדרבנן, אף יבדוק בזמן היתר חמץ מדאורייתא, ואף שיש חשש שיעבור איסור דרבנן. ותחשב.
** יא: כל שכן -
יש לדון אם החשש הוא שיעבור כשצריך מום קבוע או כשלא צריך מום קבוע. זה אומר שאפשר שחוששים שכשצריך מום קבוע כדי להקיז דמו (איני יודע אם זה אפשר במציאות), יעשה בו מום, שיחשב שמותר כמו כשלא עושה מום, כיון שהוא בהול, או אומר שכיון שהוא בהול, יעשה בו מום, ואף שלא צריך. ותחשב.
גם יש לדון במה שאומר רבנן. מה שאומרים פשוט אם נאמר שרבי יהודה חושש רק כשצריך מום קבוע, שיש לומר שרבנן אומרים שהם חוששים אף למקום שלא צריך לעשות מום, שכיון שהכל אסור, יעבור על איזה שירצה, כיון שבהול.
אם רבי יהודה חושש לכל מקום, אז צריך ביאור מה אומרים רבנן. אפשר שעדיין י"ל כשמ"כ. ותחשב.
** צערא בעלמא -
גם היה אפשר לומר שלא מיחלף. ותחשב.
** או בסוף -
צריך ביאור ל"ל נניח שהוא כי יוצא ובא, ול"ל נניח שהוא בחצי השעה. ותחשב על זה.
** יב. ושפטו והצילו -
היה אפשר לדחות שראיית עדים אומר לנו שלא משקרים עד, ואז מניחים שהם כשרים. ותחשב.
** קשה, שאף לרבא
קשה מהיכי תיתי שמעידים על חד זמן, שאף שיכולים להיות מעידים על חד זמן, מהיכי תיתי שמעידים כן. לכאורה, צריך לומר שמניחים כן כיון שהם עדים כשרים, אם לא שיש הוכחה נגדו. קשה, שאז נאמר כן אף לאבייי. וצריך לחשוב.
** באיזה יום -
אם כן, לכאורה, יכולים להבין אם אחד יודע
** יב: זמן סעודה -
יש לדון אם ר"ל שכיון שהוא זמן סעודה, הכל רעבים אז, ולכן מכירים, או שרגילים למצוא אותו זמן על פי השמש, ואז יוכלו למצוא אותו. ותחשב. נראה שמרשי משמע כשני, אבל אינו מוכרח כלל.
** יג. לאו הכרעה -
קשה ל"ל נאמר שהלכה כרבן גמליאל כיון שסתם משנה לקמן כמותו.
** אף לדבריכם -
יש לדון, שזה ס"ס, שצריך אליהו וגם אוכל. יש לדון אם יכול אליהו לאכול (היה כהן אם הוא פנחס, אבל הוא מלאך).
** יג: בכדי חסרונם -
עיין שם, שחושב אני שהוא מחלקת שם.
** גלל -
נראה שענין דין זה הוא שיכול אדם לשנות הלחם עד שהוא דבר שניתר קר על ידי קרבן מיוחד- דהיינו, תודה זה. לא שייך לשנות תודה כן שיתיר רק בשר זה, שאין יחסו לבשר דומה ליחס לחם לו, שהוא המתיר והמקדש את הלחם. ותחשב.
גי"ל שהענין הוא שיחסו לזה הוא בעיה ביחסו לזה. יחסו של לחם לתודה יותר חזק משל תודה ללחם, מפני שזה גלל זה. ותו"ת. ויש לדון מה יקרה אם אין תודה ראשון בעולם, שאי אפשר להיות מיוחס לו. אולי מה שהיה מיוחס לו גורם שאין יחס השני כל כך חזק. ותחשב.
** נמצא שאף שיש
סימנים לזמן איסור, הוצרך רבנן לגזור. לכאורה, גזרו למי שלא היה קרוב לירושלים די לראות. גם יש לומר שגזרו לנוטלים הלחם. דחוק, שמסתמא הם בקיאים כמו מעידים. ותו"ת.
** מתו-ך -
יש לדון למה זה יפסל אותם. יש לומר שהיה הדרך להביא אחרים לאכול עמו. כאן, כל אחד כבר אוכל שלו. גם יש לומר שהיו כל כך כמה תודות, מסתמא אחד מהם נפסל. מרש"י נראה כצד ראשון.
** אין מביאים קדשים -
מעניין שאין זה סיבה שלא להביא בשלש עשרה. נראה שלצד שני שכתבנו בד"ה אין מביאים לא קשה. ותו"ת.
ונראה שאפשר שאין זמן אחר להקריב. זה אומר שלא מטריחים להביא בזמן שלא עולה לרגל, ואין זמן אחר שעולה חוץ מזה. ויש לדון, שאולי יצטרך לשהות עד סוכות. ויש לדון, שאולי יפסלו אז, שהכל מביאים אז. ותחשב על זה.
** בלינה -
נמצא שיכולים לשהות שריפתו, ולא צריך לשהות מיד בבקר. ותחשב.
** נשחט הזבח עליהם -
יש לדון מה אומרים מילים אלו. הפשטות הוא שר"ל שנשחט זבח כשמכוון לקדש אותם. גם יש לומר שהם עושים כלום לזבח (עושים שיכול להיות תודה), וזהו היחס לזבח שגורם שזבח מקדש אותם. וצריך עדיין לבאר למה אינו גלגל החוזר, שלא מכשיר אותו אם לא קדוש. צריך לומר שעושים דבר קטן לו, וזה עושה שעליו קאי. ותחשב.
** יד. הוסיף -
ואם תאמר למה מקשה מ"הוסיף,” ולא מקשה ממה שאמר כלל. ויש לומר שאולי יש רבותא בעוד עדות, שאז יש עוד הוכחה שהדין נכון. ותחשב.
** אביי -
עיין ברשי שמפרש שדורש מנבואת חגי. יש לדון מהיכי תיתי שזה מדאורייתא, שאולי כבר נגזרו מאז. ותחשב על זה.
ואגב, נראה שקרא קאי במוקדשים (כן נראה שם), ורק מדמה תרומה למוקדשים יותר מחולין, שמסתבר יותר שכשקרא מוציא מוקדשים, מוציא תרומה עמו. ותחשב.
** טו. ממחלקתם -
צריך ביאור מהו התירוץ, שעדיין רק לומדים מרבי יהושע. אולי ר"ל שלומדים מר"י, ולומדים לפסוק כן ממה שהחולק הוא ר"א. ותו"ת.
** טז. תרגמא אדם -
אם כן, לשון "לא דיין שהם דכן" קצת מעניין, שכל דם טהור, שאינו משקה. ויש לדון, שאולי יש ששותים אותו, עד שנחשב משקה. ותחשב. וע’ לקמן בגמ’.
** טז: מדרבנן ודלא -
קשה ל"ל מוקים אותו אף מדאורייתא, ואומר שהוא לפי הסוברים שטומאת משקין הוא מדאורייתא (שברייתא אומר בפירוש שיש סוברים כן). ותחשב.
** יז. אישתביש -
קשה, שיכול להיות שלא חולק על קרא, אלא רב לא סובר כיוסי בן יועזר. ותחשב.
** יז: קשיא -
משמע שקשיא הוא תיובתא. ודע שרש"י מפרש ש”קשיא” קאי על מה דין של ר”פ, ולא של ר”א. כן נראה, שהרי מרב פפא שמביא לאחר מכן, נמצא תירוץ לרב אשי, וכמו שבאר רש"י לעיל. ותו"ת.
** יט. יורד לעמקי תהום -
עיין בלשון רש"י שאומר כן. יש לציין לב”ב שאומר רשבם לשן כזה.
** כא: ליתהני -
קצת צריך ביאור מהו אותו הוה אמינא, שאסור להנות ממנו, והרי נהנה ממנו. ותחשב.
** עיין בביאור
שכ’ למקור שנאסר בהנאה. צריך ביאור איך נשמע כן מ"לא ייאכל,” שזה רק אומר שאין החמץ נאכל, ולא שלא יגרום הנאת אכילה. ותחשב.
** כב. ואימא כמים -
היה אפשר לומר שאם כן הוא מיותר.
** כב: ולפני עור -
קשה, שאולי מיירי בציור שאין לו הנאה. אולי היה צריך לפרש כן. דחוק. אולי בכל זמן שמושיט לו יהיה הנאה, שיש בזה טובת הנאה קצת. יש לדון אם זה נחשב הנאה. גם יש להעיר שבנתינה לכלב, לכאורה אין שום הנאה כזה. ויש לדון איזה קרק’ של המצב נותנים לציור של כלב, שאולי מביאים קרק’ של "יש הנאה לו,” ולא קרק’ של מושיט.
ויש לדון אם צריך זה; עיין ברש"י שמשמע שהענין הוא שמשמע שהאיסור היחידי הוא לפני עוור. אז, רק צריך שיש הנאה בציור זה של מושיט לאדם. ותחשב.
** ולחזקיה למאי -
יש להעיר שאף ר"א סובר כן, שאי לאו הכי, היה לנו ללמוד מזה, ולא מנבילה. ויש לדון, שאולי אין אחד יותר טוב מחברו ללמוד ממנו.
** כשם שקבלתי שכר -
נראה ששאלו לו מה תהא עליהם, שהרי היה לך פשטים נאים, ואמר שיטרח למצוא למה אין פשטים שלו נכונים. ויש לדון, שאז אין צריך לבאר מה שיש שכר מחמת פרישה, שהיה לו לומר שיפרש. גם ק"ק מהו שאלתם, שפשטו שלא ידרוש אותם עוד, ויבאר ל"ל לדרשם. גם ק"ק מה היה קושייתם, שבמה הם גזרות טובות, שאין הוכחה לדרוש אותם חוץ ממשמעות, והרי אין משמעות. ויש לדון, שאולי ממשנה יודעים לדרוש אותם. דחוק, שהיה תנא, ואז אין משנה נגדו סותר אותו. ויש לדון, שאולי אין תנא חולק על חברו שגדול ממנו. ותחשב.
** כג. אלא למעט -
יש לדון איך יודעים איזה מן השנים (ליחיד ולרבים) נמעט. ותו"ת.
** מערבים -
ואם תאמר מצוות לאו ליהנות. ויש לומר שכיון שמצוות גורמים הנאה, נחשב אותו הנאה הנאה (כן אומר ר"ן בנדרים). אז, כאן יש הנאה במה שיכול ללכת יותר. (יש להעיר שגם יש חסרון כנגדו; נחשב הנאה כיון שיודעים שכן רוצה.) מעניין, שזה רק הנאה במה שדבר מותר, שהיה אפשר לו ללכת בלי זה. ותחשב אם זה נחשב הנאה (שהרי בכל מקום יכול לומר שאותו מצווה הוא הנאה, במה שאינו צריך לעשות אותו מצווה עוד). ותחשב על זה.
** כג: חולין שנחשטו דאורייתא -
יש לדון מהיכי תיתי למעט זה יותר משאר איסורים. יותר מזה, קשה ל"ל נמעט את כולם, כמו שהיינו ממעטים את כולם אילו היה מדרבנן. נראה שסובר שיכולים למעט כולם, אלא שאילו היה כתיב כן, היה נראה לומר שהקמ"ל הוא שלשון אכילה אוסר בהנאה. אם כן, אפשר לומר שלא נמעט חולין. אז, קשה לו המקור לזה. צריך לומר שהוא מכאן, ואז קשה מקור לחמץ. ותחשב, שזה עדיין צריך ביאור.[fn:1]
** כד. ואים אינו ענין לאכילה -
מעניין שהיה הוא אמינא לדרוש את זה לענין אכילה, שכתיב שישרף אותו. אז, היה נראה יותר לומר שאומר שאסור בהנאה. ויש לדון, שהרי לא טעון שריפה. אם כן, בין כך ובין כך לאו דווקא. ויש לדון, ששריפה יותר טוב על מה שאין לו הנאה, של"ל ישרוף (וגם לעפמים חייב לשרוף, כדאיתא בסוף [מסכתא אחד]). ותחשב.
משמע שאין דורשים כלל משמעות כשיש אם אינו ענין, אלא רק דורשים ייתור. צריך ביאור ל"ל, וגם צריך ביאור ל"ל אומרים שמלמד שום דין אחר שאינו שייך כלל. ותחשב. ואפשר שאין דין אחר בכל התורה כולה שהוא כל כך מסתבר כזה. דחוק.
** אכלה פוטיתא -
לכאורה, ר"ל שלא דוחים לאוים אלו לומר שבהרכח על דבר אחר קאי. גמרא דוחה שאין דבר אחר שכל כך מסתבר שיהיה קאי עליו.
** מעשר -
קשה למה צריך זה, שקשה ל"ל דורשים כבר שכל שבקדש באש תשרף, ואז מה שאומר כאן שנשרף מיותר. אז, נדרש ממה שנשרף. ותחשב.
** כד: כל היכא דאיכא -
נמצא שיותר דורשים "אם אינו ענין" מ"ליתן לו לאו שני." יש לדון אם זה מפני שכבר נאסר או מפני שכבר לוקה. (הנפקא מינא הוא כשבא קרא להוסיף לאו על עשה. אז, עשה מוסיף דחייה, ולאו מוסיף עונש.)
וצריך ביאור איך לעולם דורשים להוסיף לאו, שהרי לעולם יכולים לדרוש "אם אינו ענין," שבוודאי יש דין אחר בתורה שיכול להילמד. אולי אומרים כן רק בדין שמסתבר או ביחס לקרא שמסתבר. קצת צריך ביאור, שנראה שזה לא כל כך שייך לקרא. אם כן, מחודש שדורשים את זה. ותחשב.
** כה. להכי קא גמר מנבילה -
מעניין שצריך כן, שמה שמקור לאיסור, אף בלי נבילה, בא מערלה וחמץ, והרי אחד מהם אסור רק בדרך הנאה, ולא נלמד יותר מכן. אולי אין הכי נמי, ורק נקט מלמד אחד. זה נוגע למה שדנו אחרונים אם יש דיו על מלמד אחד של צד השווה.
** כה: צריך ביאור
מהו לא אפשר. לכאורה, אם ממש לא אפשר לצאת ממנו, אז צריך ביאור איך ייאסר. אין זה כל כך קשה, שאפשר שאין הכי נמי, לא נאסר אלא אם כן יש בחירה, שהרי זה מותר. ויש לדון, שלצד ראשון, זה מחלקת רבי יהודה ורבי שמעון (עיין בברוך מתיר איסורים שהוכחנו את זה). אז, צריך ביאור.
** כו. לולין -
היה אפשר לומר שהוא רבי שמעון.
** מעילה -
מעניין שממעטים מעגלה ערופה, שאינו קדשים, ואז אין עליו מעילה. צריך לומר שכיון שהוקש לקדשים (כן אני חושב) וכיון שהוא איסור הנאה, יכולים ללמוד ממנו, שאיסורו דומה די. ותחשב.
** כז: נותר אסור -
קשה, שזה קולא בקצת, כמו שמבאר גמרא, והרי יש פירכא שאומר שזה יותר חמור. ותחשב.
** חלבו של שור -
יש לדון, שהרי אין איסור הנאה שלו מחייב כרת. אולי משמע שאינו כן גבי חמץ גם כן, ואין יחס בין איסור הנאתו לאיסור אכילתו. ותחשב.
** כח: הוקש למצה -
לכאורה, אין מצווה לאכול מצות לשבעת ימים, אלא ר"ל שאז אי אפשר לאכול חמץ, וממילא מה שאוכל צריך להיות מצה. אם כן, היה לו להביא ראיה משם, שקרא זה כמעט אומר זמן איסור חמץ. (ואם תאמר אולי לא מזכיר כל הזמן, שאולי האיסור הוא לשבעת ימים- אבל אף לעוד. קשה, שאם כן, עדיין אין דרשת גמרא אפשר.) אולי משמע שעל כל פנים יש לגמרא צד שיש קיום באכילת מצה כל שבע. ותחשב.
** לא: וצריך שיבטל בלבו -
ואם תאמר אם כן למאי נפק"מ נחשב מבוער. ויש לומר שאז לא צריך לבערו מדרבנן (שמדרבנן לא יכול לסמוך על ביטול, אבל עכשיו יכול לסמוך). גם יש לומר שלא צריך ביטול מדאורייתא. אם כן, יוצא שאולי אין לדין זה נפק"מ מדרבנן. (אבל, למעשה, לכאורה, נפק"מ ראשון שכתבנו הוא ג"כ נכון.) גם יש לומר שאין הכי נמי, אין חילוק בין זה לשאר חמץ, ומשנה מחדש שביטול של זה נחשב ביטול, שהוה אמינא שאם לאחר זמן מוצא אותו, זה מגלה שהביטול היה בטעות, ולא בטל. אז, מחדש המשנה שיכול להיות מבוער. ותחשב. לשון משנה לא משמע כן כל כך.
עיין ברש"י, שנראה שסובר שצריך ביטול מדרבנן.
** יש לדון
בצירוף בין זה לביטול דרבנן. היה אפשר לומר שהוא צירוף, שכל אחד מבטל אותו מלהיות חמץ קצת. גם יש לומר שזה לא מהני כלל מדאורייתא, ואז צריך ביטול, וזה מהני לדין בדיקה מדרבנן. גם יש לומר שמפולת שלא גרם שיבטל אותו לא חשוב די, ולא נחשב מבוער.
** משום ריחא -
משמע ששיעור של כלב הוא מחמת חשש ממש של כלב, ואינו רק שיעור. עדיין יש לדון אם הוא חשש שמא יקח אותו כלב או שכיון שיכול כלב להציל אותו, לא נחשב מבוער. ותחשב.
** לב. לא גרע מגזלן -
יש לדון ל"ל גרע מגזלן:
1. מניחים שדין משלם תרומה לא קל מגזלן לענין זה. לא מבואר עדיין מהיכי תיתי או למה.
2. הרי הוא גם כן גזלן, וחייב אותם דנים מחמת גזלנותו. לפי זה, לכאורה ייצא שיכול לשלם שווה כסף, שהרי הוא משלם ככל גזלן.
** וכי מה הנאה -
צריך ביאור כאן (וכן בכמה מקומות שמבאר גמרא שר"ל שיודה לי מיהת מחמת סברה) למה צריך קרא, שהרי מבאר שכבר סובר שיש סברה.
היה אפשר לומר שהוא מפרש למה הוא בכלל הקרא. זה אומר שפשוט לו לדרוש הקרא אם אפשר, ואז טוען שאפשר, שזה נחשב שאי אפשר להיות תרומה, שהרי אין לו הנאה ממנו. ותחשב. על כל פנים, מרש"י יוצא שאין זה נכון. וע"ש.
** לב: וא"ש מאי טעמא… -
כל המשך גמרא זה משמע שחולקים על הדדי לגמרי, ואין אחד מוסיף על שיעור של חברו. כן הוא על פי מסקנת גמרא לקמן.
** ולסוף אלימא -
ק"ק ל"ל נאמר שיש אלימות לכל אחד. אז, אי אפשר ללמוד מזה או מזה. משמע שרק דנים מהו, בין הכל, הכי אלם. עיין בגמרא ב"מ מא: (ובתוס’ שם). ותחשב.
** לג. בשאר מצוות -
צ"ב, שכל חלבים ועריות כן, שאומר גמ’ בכ"מ שהנהנה מהם, אף אם מתעסק, חייב.
** לג: ראשית ששיריה ניכרים -
לא הבנתי הדרשה כל כך. ותחשב.
** שיריה ניכרים -
אם כן, רק החולין צריך להיות מצה, אבל עדיין התרומה יוכל להיות חמץ.
** דאי בעי דריך להו -
ואם תאמר הרי לעיל לא גזר עליו. ויש לומר שרק גוזרים שמא יאכל מן הפרי, ולא חוששים שמא ימצא שיטמא את המשקין.
** לד. גבל -
גם היה (לחד צד) קובר מתים (נדה כד:).
** בדבר שאין -
ק"ק מהיכי תיתי שאינו בזרעו כלה, ומח’ כמו בכל תרומה בגידולו. ותחשב.
** לד: אא"ב פסולי טומאה -
לכאורה, אז צריך לסמוך שתרי גווני טומאה קתני. ותחשב, שלא משמע כן מגמרא, שמקשה כן על הדיחוי. ותחשב. אולי כאן פשוט לגמ’ שצ’ שניהם, שזה מחדש שהוא פסול טומאה.
** לה. העריב שמשו -
עיין בגמ’ יבמות פרק הערל, שמשמע שזה דין דאורייתא. עיין שם.
** בני אטמויי -
וצריך לומר, אז, שהוא אסמכתא. עדיין צריך ביאור מהיכי תיתי שאין קרא זה מרבה את העצים לטומאה.
** וחייבים על חימוצו -
היה אפשר לחלק שכאן פסול באופן אכילה, ולא פסול בחפץ. ממה שלא אמר כן, צריך לומר או שאף זה פסול בחפץ או שאין זה חילוק שיחלק לענין דרשה זה (או דין זה).
** לה: ואמר ר"ה -
זה שייך לתירוץ כיון שר"ל, כמו שאומר רש"י במק"א, שאם תמצא ברייתא נגד זה, אל תאמר שדין זה אינו נכון, או אף שהוא מחלקת בין תנאים השייכים, אלא אותו ברייתא כבית שמאי, ואין לחוש לו.
זה שייך לדין משנה (אם לפסוק כמותו) ואם יכול להיות כמשנה (שאז נמצא שיותר קל לומר שהוא שיטת משנה שלנו, שאין חולקים חשובים).
** מצה שווה בכל אדם -
צריך ביאור מהיכי תיתי שנצטרך כן.
** חומש -
חידושו אולי הוא לכאורה שיש אופנים שהם כשרים בדיעבד ופסולים לכתחילה. יש לדון אם החידוש הוא אף שהם פסולים לכתחילה או רק שהם כשרים בדיעבד. ותחשב.
** לו. אי הכי מילתת -
היה אפשר לתרץ בקל שאף זריזים לא יהנו לזה.
** לו: אפילו ביכורים -
צריך ביאור למה לא נאמר שזה מרבה וזה ממעט. ותחשב.
** שמחה כתיבא -
ק"ק, אז, למי שדורש ההיקש, שלא צריך, אז, מקור. ויש לומר שבעיקר בא ללמד עוד דינים של מעשר שני. ותחשב. גם יש לומר שאין הכי נמי, קשה עליו, אבל לא חש גמרא לזה, שלא בא לבאר אותו מד"א.
** לז. ואמאי קרו -
מתירוץ שני, יוצא שלתירוץ ראשון לא היה נקרא כן במקום שלו. אם כן, מוזר שקרא אותו כן, אף שהלשון אינו כל כך רע, כיון שלא נקרא כן. ותו"ת.
** תנ"ה -
יש לדון, שמצאנו שיאמר גמ’ שאף שאומר דבר על יו"ט, הוא רק על יו"ט מיוחד. (יש לדון אם עושה כן לימים שאר מסוכות, שאולי סוכות אינו כל כך ראיה, שכבר ראינו שנקרא כג סתם. ובאמת, תחשב למה. אולי הוא שייך למה שהוא יום שמחה ביותר.)
** עושים סריקים כמין -
יש לדון אם מחמיר או מיקל.
** לז: תנאי -
קשה, שכבר מנה ריב”י שאומר כמותו, ואז כבר תנאי הוא. ותו"ת.
** לט. ובמרור -
מעניין שנמנה אחרון, שהוא מה שאומר קרא. ויש לומר שהמין נקרא כן, אבל לא לזה מכוון תורה. ויש לדון ל"ל נאמר שתורה מכוון למין זה.
** תמכא -
לכאורה, לשון ארמי הוא. מעניין שנאמר במשנה.
** אף עולשי -
ואם תאמר אם כן למה מזכיר שנים. ויש לומר שר"ל שהוא כשר, ולא מזכיר כמה טוב הוא; ואילו היה מזכיר רק אחד היה משמע שהוא אף טוב כאותו אחד. אז, מזכיר שנים, וצריך לומר שרק ר"ל שהוא כשר, ולא דן כמה טוב הוא.
אגב, יש לדון כמה טוב הוא. משנה נשנה בסדר, אבל יש לדון במה שהוסף בגמרא.
** מינים הרבה -
הוא חמש מינים (ואף מרור כן, אולי), אבל יש להעיר שהוא קצת נחשב כשני מינים (שכולם בכלל חיטין או שעורין).
** מא. אין מפיגים טעמם -
יש לדון אם הענין הוא שאז יותר בטלים או שיש ענין בטעם הפסח. ותחשב.
** חמוע -
עדיין יש לדון מהיכי תיתי שמחמע כל כך מהר (שאולי יש לו עדיין כדי הילוך מיל).
** מא: נחמן -
משמע מגמרא זה שרנב"י אינו ר"נ סתם. חושב אני שמביאים ראיה זה.
** מג. טופלות -
אם כן, קשה מהו החילוק בין זה לקולן (לפי שיטה אחת לעיל).
** מתכילתא -
נמצא שדיברו בלשון ארמי בא"י. ותו"ת.
** כותח -
עיין במה שפרש"י למה פרש. ממה שמבאר שלכן נשנה במשנה, היה יותר נראה לומר שידע שיש בו חמץ. לכאורה, לרש"י צ"ל שרק לומד מזה שיש טוב לדעת מהו אוכל. ותחשב. ק"ק ל"ל יפרש רש"י כמש"כ.
** שאור -
לא הבנתי את זה כל כך, שגמרא ביצה (ז:) אומר ששאור חימוצו קשה. אולי זה רק ר"ל שיכול לעשות דברים אחרים חמץ. עדיין ק"ק איך זה מבאר לשון "חימוצו קשה.” גם מציאות מוזר הוא שמה שאינו כל כך חמץ יכול לחמץ ומה שהוא חמץ ביותר לא יכול לחמץ. ותחשב.
** מג: נשי -
מעניין שרק צריך ריבוי לעונש ולא לאזהרה. ותו"ת.
** מו. מצטרף -
יש לדון אם הענין הוא שאגב שניתן דין לענין כזית שמחשיבו, גם ניתן דין זה להחשיבו, או שכיון שהוא חלוק (או באיסור או בסיבת איסור) נחשב חלוק, ולא בטל.
** מו: אגב,
מעניין שלרשי רק חייב בלא יראה ולא ימצא על חמץ שהוא שלו, שהרי הוא גזירה שמא יאכל. נראה שכיון שהחמץ הוא של חברו, לא חוששים שיאכל אותו, שכבר נזהר עליו כיון שיש איסור גזילה, וזוכר שלא לאכול אותו.
** ביום טוב מיבעיא -
מעניין שנחשב ליום טוב, אבל לא מותרים לדברי הכל (שאוכל נפש מותר). ותחשב.
** מז: הואיל וחזי -
לא הבנתי; משמע שמותר לחרוש בשביל להשיג דם לצפור. אם כן, קשה למה אין כתישה מותר.
** אהבערה לא לחייב -
צריך ביאור למה אין קושיה זה קשה אף על דין מבשל. ויש לומר שאין מי שמותר לו לאכול גיד (שסובר שאסור לבשל לגוי), אבל אפשר שיבוא אחר, וצריך אש כדי לבשל עליו דבר אחר.
** מח. ושתיק -
ואם תאמר הרי בין כך ובין כך מוכרח שהיה לו שום תירוץ, שאי לאו הכי, היה לכאורה חושב על אותו בעיה, ולא היה אומר כן. ונראה שאילו אמר ר"י כמו שמבאר רש"י לא כל כך קשה ל"ל חשב עליו ר"א, שהוא קושיה שקשה לחשוב עליו, אבל כל קושיה שהוא "לא נאמר הואיל" הוא קל לחשוב עליו. ויש לדון. ותחשב.
** מט. לא ניחא -
לכאורה, זה ר"י התנא, שהוא סתם ר"י. אם כן, מעניין שהיה מדבר בארמי. אולי גמרא רק פאראפריי"ס אותו לשון.
** מט: זה טעון ברכה -
לא טעון ברכה על אדם, אלא הוא מעשה שבמקום אחר טעון ברכה.
מזה משמע, אגב, ששחיטה הוא יותר מצער, שאי לאו הכי, קשה למה היה לו לומר שחיטה (שלכאורה, נראה ממעשה עם ר"ע שרצו שיאמר מה שהוא יותר רע, והוא חידש מה יותר רע. ויש לדון, שאולי רצו שיאמר מה שהוא יותר שכיח. ויש לדון למה ירצו כן.) עדיין יש קצת הוכחה כן ממה שלא ענה להם שנקט מה שהוא יותר מצער. יש לומר שלא רצה לצער אותם כל כך. דחוק.
** חזרתו כטומאתו -
צריך ביאור למה זה כן. משמע שמה שאפשר לטמא אחרים כשהוא כביצה מראה (או הוא סיבה לעשות) טומאתו יותר גדול. ותחשב.
** נ. חומרי מקום שיצא משם -
זה קאי על ציור שני. ותו"ת.
** נ: מאי איריא -
ק"ק ל"ל ת’ שרק נהגו שלא לעשות מלאכה בע"פ. י"ל שידע גמ’ שאינו כן.
** נא. בני מדינת הים -
יש לציין לגמרא בתחילת גיטין (שיטת רבה). אבל, עיין בשיטת ר"ת (תוס’ בב:)[fn:2]. ותו"ת.
אין בזו מפני- על כל פנים מכל זה, יוצא שיש כמה דברים שעושים שצריך אדם לנהוג כמנהג. יש מה שחוששים שמא יתירו דברים אחרי כמו גבי בני כבול. יש מחלוקת, שממשנה משמע (ומאביי מוכרח) שהוא חשש. גם יש מה שצריך לנהוג כמדינה שלו. ותחשב.
ויש לדון למה צריך כל הני גזירות. אולי אינם גזירות, אלא גמ’ אומר שיש גזירה אחת מפני כל דברים רעים אלו. דחוק, שאם כן יהיה אסור אף אם אינם כותים. ויש לומר שדברים אלו לא יגרמו מחלקת. צריך ביאור קצת.
** ולמה אמרו -
קצת קשה עדיין למה אמרו שיש שלש ארצות בתוך כל השלש ארצות, שלא נראה שום נפקרא מינא מזה. ותחשב.
** נג. תרתי בתרייתא -
בגמ’ גיטין (ה.) דנים ראשונים למה מזכיר מה שאומר ר”י שם, שלא שייך לקושיה. צריך ביאור מהו השייכות כאן. היה נראה לומר שאין שייכות לקושיה, אלא שגמרא מזכיר מה שחושב שיהיה נצרך כדי לתרץ הקושיה. אז, צריך ביאור של הברייתא או של הדין. ותחשב.
** מקום שלא נהגו למכור -
היה יותר נראה לומר שר"ל מקום שנהגו שלא למכור, שלכאורה, אסור מפני שמשנה ממנהגם, ואז צריך לומר שנהגו שלא לכמור. יש גורסים כן כאן.
** נד: ואין אדם יודע -
צריך ביאור למה משנה סגנון של מה שאומר.
** אינו כראשונות -
אז, לשון “אינו כתענית צבור” מוזר, שהוא כמקצת תענית צבור. יותר קשה איך מה שאינו כתענית ציבור אומר כלום, שכל דבר אינו כתענית צבור, שיש חילוקים בתענית ציבור, ואם הוא כזה, אינו כזה. וצריך לומר שזה סתם “תענית ציבור.” יש לדון למה.
** נה. כל מלאכה -
יש לדון מה נחשב בכלל מלאכה אחת.
** נה: מתירים -
לכאורה, מיחו על מה שאכלו מהם, ולא על מה שהתירו. ותחשב.
** נז. והקדישום -
ואם תאמר איך עושה כן כיון ששל כהן הוא. ויש לומר שיכול להקדיש לו קודם שמקדיש שאר במהה לקרבן. ותחשב.
** וימלא כריסו -
לשון מעניין הוא, שלא היה ממש אוכל כל כך, אלא היו גביו כמה כהנים (כמו שמבאר רש"י כאן).
** נח. בין הערבים -
יש לדון איך משמע “משעה שמתחיל לנטות לערב.” אפשר שערב הוא כל זמן שחמה בערב. אבל, לא נקרא כן, שדרך בני אדם אינו לדבר על זמן כל כך גדול. אז, כשאומרים “ערב,” משמעותו הוא לזמן פרטי, והוא או לתחלתו או לסופו (ויש לדון). אם כן, יש לומר שמכשיר בין שני ערבים אלו. ותחשב.
** אדיניה -
לשון מעניין הוא, שלא מוקמינן אדין יותר מבשאר ציורים, אלא רק מקדימים אותו כמה שיכולים לעשות. אולי ר"ל שמוקמינן אותו על דין של “זריזים מקדימים למצוות.”
** נט: כמי שנטמאו -
היה אפשר לומר שני דרכים לתרץ לזה:
1. הוא שווה לאילו נטמאו אימורים, ואז לא צריך אימורים כדי לאכול בשר.
2. הוא שווה לאילו נטמא בשר, ואז לא צריך אכילה כדי לכפר.
ותחשב על זה. גמרא משמע שאומר ראשון.
** ס. ואפילו לר”מ -
נראה שהחילוקים יהיו אם רבי מאיר מודה בעבודה אחת, ומי הוא תנא של משנתינו.
** וקא מחשב -
משנה לא משמע כן; לכאורה, נלמד ממשנה יתירה.
** ומדסיפא -
ואם תאמר אם כן עדיין קשה, “אם לשמו ושלא לשמו....” ויש לומר שעכשיו לא מיותר, שגופא מגלה לנו באיזה ציור נכון דין לשמו ושלא לשמו. ותו"ת.
** ס: מדסיפא -
מביא עוד ראיה, אף שיכול לדחות כמה שדחה, כיון שעכשיו אין הדחייה כל כך טוב, שכשיש יותר דברים, יש יותר סיבה לשנות אגבם, כמו שאומר גמרא (תחלת קידושין).
** מכשירו... -
נמצא שמה שמכשירו שלא בזמנו אינו מה שיהיה פסול לפסח. לכאורה, הוא מה ששמעתי מגר”ק, והוא שמחשבת שלא לשמה משנה מה הוא הקרבן. ותחשב.[fn:3]
** ממשכי -
מעניין, שהרי בוודאי הוא ל”אוכליו,” אלא אולי אינו לאלו, שאולי אין אלו אוכליו. ותחשב.
** סא. אגב, נראה
שמה שאין מחשבת שינוי בעלים אלא לזרוק לאחר הוא שאין דבר אחר נעשה לבעלים כל כך, שאין שוחטים להם, שאין יחס בין בעל לשחיטה. ויש לדון, שאפשר לכוון של מי הבהמה היה. גם היה אפשר לכוון של מי שליח (אי הני כהני שלוחי דידן, ולא שלוחי דרחמנא). ותחשב.
** אגב
(
, עיין איך רש"י מפרש מחצר לחצר. צריך ביאור למה אין זה כבר נלמד מרישא.)
** סא: מתקיף לה ר"א -
יש להעיר שק"ק לר"א למה לא הביא ברייתא זה בהוה אמינא, אלא למד ממקורות אחרים. ותחשב על זה.
** סב: שמתחילתו לא בא -
עיין במה שמפרש רש"י. מעניין, שנמצא שעיקר סיבת הבאת פסח הוא לאכילתו. ותחשב.
** ישנו בציבור -
מעניין שמחלק בין ציבור ליחיד, ולא מחלק בין קרבן זה לקרבן אחרים. שו"ר בתוס’.
** סג: חוץ לחומת בית פאגי -
יש לדון אם צריך להיות בתוך אותו בית מחמת "על,” או כדי לקדשו (זה אומר, שאולי אינו נלמד מחמת שאומר "על,” אלא שאולי ממה שנקדש, פשוט לנו שצריך להיות במקום הכשרו, שבלי זה לא נקדש.
** התראת ספק -
עיין במה שמפרש רש"י. יש להעיר שנמצא שהתראת ספק תלוי על ידיעת המתרה, ולא על ידיעת העובר. ותחשב.
ויש לדון אם זה נכון אף למסקנת גמרא כאן, שאם כן, הרי לריש לקיש לא צריך דרשת "על.” ותחשב. ויש לדון, שיש נפק"מ אם ידוע, אף שאינו שם. ותחשב.
** סד: קצת צריך
ביאור למה דורשים ש"ישראל" הוא עשרה. ותחשב.
** ננעלים -
גמרא מבאר שהמחלקת הוא אם סומכים על הנס או לא. לכאורה, זה אומר שלרבא יש סיבה לחשוב שאותו הנס יקרה, שאי לאו הכי, לכאורה, אין מי שסובר שסומכים על הנס. ותחשב. אם כן, יש לדון קצת מהו האותו סיבה לחשוב כן שלא מכריח אותו. ותחשב.
** חס ושלום -
ק"ק, שהרי אף נתנו ר"א בשמתא. ויש לדון, שאולי לא מניחים אותו אלא אם כן יודעים אותו בוודאי. ותו"ת. גם יש לומר שר"י סבר שלא קרה, ואמר שהוא רע לומר כן, שכיון שהוא טעות, הוא רע ביותר, שעקביה היה ת"ח גדול. כמו כן מצאנו בשבת (צז.).
** הולכה שלא ברגל -
לא הבנתי את זה כל כך, שלכאורה, יסוד הראיה הוא ההנחה שצריך הולכה. קצת קשה מהיכי תיתי, שאטו השוחט קרוב למזבח צריך הולכה. צ"ל שמניח חילוק בין שני הציורים. צריך ביאור מהו החילוק. אולי הוא שבציור אחד יכול להוליך. ותחשב.
** סה. בניו נקבות -
כמובן, ר"ל שבנותיו נקבות (אלא שנקט מילת "בניו" אגב תחלת המאמר).
** עצלנים -
יד לדון על איזה כת קאי. לשון יחיד של גמרא משמע שרק קאי על אחד, ואם כן, לכאורה, צריך להיות כת שלישית, שאם הוא כת שניה, מכל שכן יהיה כת שלישית כן. ויש לדחות בשני אופנים:
1. לא רק קאי על כת אחד, אלא גמרא אומר אותו על כת אחת. זה אומר שגמרא אומר דין זה על כת שני כיון שבא ראשון במשנה, ופשוט שכן נכון אף על כת שלישי.
2. אפשר שכת שלישי הוא יותר רע מעצלנים.
מקטע של משנה שהביא, משמע שקאי על כת שני. ותחשב.
עיין ברש"י; מלשון "אחרון" שאומר משמע שקאי על כת שלישית. ותחשב.
** לא סגי דלאו הכי -
לכאורה, פשוט שלא נ מצאשכל בני שיראל יבואו שם בזמן אחד. לכאורה, זה יכול להיות מפני שכלם באים ממקומות חלוקים, ואונסים כעין זה, ויכול להיות מפני העצלנים. לכאורה, גמרא מניח שהוא מחמת עצלנותקצת.
יש לדון מה אומר גמרא בהוה אמינא:
1. אולי אומר שאין להניח שהוא מחמת עצלנות, שאף בלי עצלנות היה כן, שהרי הם ממקומות חלוקים, ואז אי אפשר להוכיח עצלנות.
2. כיון שהיה כן בלי עצלנות, לא יהיו נקראים על שם עצלנות שלהם, שלא גרם רע. לא נראה כן, שעשה שהם יותר מאוחרים (ויש לדון, שאולי בין כך ובין כך, בזמן שהיו מחכים לכת ראשון, היו מתאחרים עד אותו זמן). אבל, לא נראה שגמרא משיב לזה.
3. אולי מקשה גמרא שאף שהם עצלנים, עשו טוב, שהיה נצרך. ותחשב.
** סה: אין דם מבטל דם -
לכאורה, בין כך ובין כך צריכים זה, שבלי זה, דם של שאר קרבנות יבטל דם של קרבן זה.
** והא קא חייץ -
נראה שזה קושיה על שניהם. (אפשר שגמרא רק אומר אותו כאן כיון שאומר שהוא עד ארכבותיהם.)
** איצטבי -
צריך ביאור למה לא היה בעיה של "הכל בכתב עלי השכיל.”
** לכאורה,
יוצא מגמרא זה שרבי יהודה סובר שיש בילה.
** סו. נאמר מועדו -
מגמרא לקמן מבואר שכוונת גמרא כאן הוא לומר ג"ש, ולא לומר שכמו שדורשים אותו כך כאן, כמו כן דורישם אותו במקום אחר. גם אפשר לומר שאינו ג"ש ממש, אלא גמרא מפרש מילת "מועדו,” והוא שמשמעות מועדו נתפרש על ידי מקום אחר שנמצא.
** שמעתי ושכחתי -
ואם תאמר אם כן למה מלך עליהם, שאף הוא שכח. ויש לדון, שאולי הוא שכח אחד והם שכחו שנים. גם יש לומר שהוא שכח דבר שאינו כל כך מפורש בקראי. גם יש לומר שהיה לו עליל למה שכח, והוא ששכח כיון שיהיר. ויש לדון אם נאמר על זה ש"יצא השכר בההפסד.”
גם נראה שהוא שמע ושכח, והם לא שמעו כלל. עיין בגמרא שבת וחגיגה בענין זה (גבי שעת חורבן ירושלים).
** קל וחומר פריכא -
נראה שעכשיו חוזר מתירוץ ראשון (וכן מורה לשון "אלא" שאומר גמרא), והוא שעכשיו אומר שהיה מקשה עליהם ל"ל ידוע לשיטתם. אם כן, אין צורך לומר שלא כבר אמר את הג"ש. ותחשב.
** קל וחומר פריכא -
אם לא ידע שהוא קל וחומר פריכא, אלא חשב שהוא קו"ח נכון, קשה למה הוצרך לג"ש. משמע שאומרים "מילתא דאתיא בקל וחומר טרח וכתביה קרא,” אף אם לא כתביה קרא בפירוש, אלא אף אם רק נתנו בג"ש.
** בחובות שקבוע להם זמן -
יש להעיר שלכאורה אין זה מחמת שמוכרח לכך, שאם כן לא יהיה מותר כאן לשהות עד שבת לקדשו. ויש לדון, שאולי מותר כיון שיש צורך, שאי אפשר בלאו הכי להביא סכין (או שנחוש שימעל). ותו"ת. גם יש לומר שכיון שהגיע שבת ויש צורך לו לדחות, נדחה שבת. נמצא שאין איסור ואין ציווי אז. ותחשב על זה.
** אמר רבי יוחנן -
יש לדון במחלקת בין הדורש מזה למי שלא דורש אותו. אפשר שמי שדורש אותו סובר שמסתבר יותר לומר שהקמ"ל הוא שמקריבים בפסח ראשון (ולכן לא מקריבים בפסח שני) מלהיות שהקא משמע לן הוא שאין מקריבים כלל (לא בראשון ולא בשני). גם יש לומר שסובר שאילו לא היו יכולים להקריב בפסח שני, היו מקריבים בפסח ראשון. זה אומר שהקמ"ל (מה שנשתנה בין הוה אמינא למסקנא) שווה לשניהם, אלא שחולקים אם אז יקריב בראשון או לא יקריב כלל. יש להעיר שיש מחלקת כעין זה בטמא בשני. ותחשב על זה.
** במקום אחר
, בארנו שצריך ביאור מהו מקור של רבי אליעזר. משמע (וכן משמע מקל וחומר שאומר) שלא מחלק בין מכשירים שאפשר לעשות אותם בע"ש לשאי אפשר. קשה, שמבואר שבשבת מחלק, ולפעמים לא מתיר. זה לא כל כך קשה, שיש לומר ששם כשאומר מכשירים, כוונתו למכשירים ממש, אבל כאן, כוונתו למה שחולק עם ר"ע, שהוא מכשירים שאי אפשר לעשות אותם בע"ש. עדיין צריך ביאור מהו מקור שלו. העיר לי א.י.ש. שמן המשנה משמע שדורש מ"מועדו,” ומזה יש לו ייתור. מעניין, ששני המקורות הוא מאותו קרא, לג"ש ולדרשה. ותחשב. אגב, נמצא שאז בלי ריבוי לר"ע נקל במכשירים שא"א לעשות אותם בע"ש, שהרי מרבה בלי קרא, ולר"א, לפי חשבון שלנו, נחמיר.
** סז. וכי תימא הכי נמי -
לכאורה, היה קשה אז למה צריך טמאי מתים. זה אומר שבין כך ובין כך, יהיה חילוק רק בין שנים מהם. אם כן, לא צריכים שלש דברים נכתבים. ותחשב.
** לנפש למה לי -
עיין במה שבאר רש"י. יש לדון אם הענין הוא שממעט שאר טמאים מדבר, וצריך לומר שהוא הקרבה בטומאה, או שזה מכריח לנו לדרוש כרבי יוחנן. ותחשב.
יש להעיר שלזה כבר דרש מ"איש איש.” אז, לכאורה, אי אפשר לומר כרבי יוחנן. למעשה, מה שאומר אביי (“לעולם מקרא קמא" קצת משמע שקאי על רבי יוחנן, ודורש כמותו. אז, אולי יש לומר שמתחיל לדרוש כרבי יוחנן, ומוכרח לומר כצד ראשון שכתבנו. גם יש לומר שיכול לדרוש שני דרכים מ"איש,” כיון שנכפל. ויש לדון, שזה אפשר רק אם אנרמ שדורש מ"איש,” ולא מכפילותו.
** והתניא -
לא מביא ראיה מן הברייתא עצמו, שדן במקור לו, ולמה לא נדרוש כן, אלא מביא ראיה מקרא שמביא. ותו"ת.
- ממה שגמרא קורא כאן לטומאת שרץ בשם טומאת מת, היה נראה לומר שיש דמיון בין שני הטומאות. אפשר שהוא רק מה ששניהם באים על ידי מגע של טמא, ואפשר שהוא יותר מזה, והוא ששניהם באים מדבר מת (אפשר שזהו דמיון בפ"ע, ואפשר שזהו סימן לדמיון יותר גדול). דע שאפשר ש"טומאת מת" ר"ל טומאת מת אדם, ושרץ בכלל זה, וגם אפשר שהוא משמע כל טומאה שבא מדבר מת, בין אם הוא אדם מת בין אם הוא שרץ מת. ותו"ת.
** עשה -
עיין במה שבאר רשי שהוא לאו הניתק לעשה. אגב, יש להעיר שהיה אפשר לומר שפטור לאו הניתק לעשה הוא שלכל עשה יש עונש בידי שמים. כיון שרק נענש עונש אחת, פטור מעונש של לאו. (וא”ת למה לא נענש עונש לאו. ויש לומר שגזירת הכתוב הוא, ונלמד מהיקש לחסימה. אולי כן כוונת רשי כשאומר שכבר יש עונש אחד, והוא העשה. ותחשב.)
יש להעיר שכאן יש יותר מלאו אחד, ורק כתוב עשה אחד. עיין בתחילת תמורה, שכתב שאין זה נחשב לאו הניתק לעשה. ותחשב.
היה אפשר לומר שאולי יש חילוק בין אם העשה אומר לתקן את הלאו, שאז הוא לאו הניתק לעשה, ואם העשה הוא על אותו דבר חלוק מן הלאו, שאז אינו לאו הניתק לעשה- אבל, עדיין אולי הוא פטור מסיבה אחרת, והוא ממה שכתבנו לעיל (שעל אותו דבר עצמו, ולא על מה שאינו מתקן אותו[fn:4], נענש). כמו כן, יש לומר שמה שיש עליו עשה מגלה שהוא איסור עשה, ולא איסור לאו (זה אומר שהוא סימן לדבר בסיבת האיסור, וזהו מה שעושה שאין בו מלקות, שמגלה שלא רצה ה’ שילקה על זה). ותחשב. חושב אני שמצאנו כעין זה גבי נושא חלוצתו, אבל איני יודע. ותחשב.
** אונס -
צריך לבאר קצת מתי אומרים שדבר הוא פירכא ומתי אומרים שדבר הוא חלק מן הדין. זה אומר שהיה אפשר לומר פירכא אחרת, והוא שזב רק בא לאיש או שרק בא על ידי דבר שיוצא ממנו. אבל, לא אומרים כן, שהרי זהו טומאת זב, ואינו קולא בו במה שאינו מטמא בלי זה. ותחשב. אם כן, היה אפשר לומר כן כאן גם כן, והוא שטומאת זב הוא ראייה בלי אונס. אולי טומאת זבה מוכיח כן. באמת, צריך ביאור מהו החילוק בין קולא לדבר שאינו בכלל הטומאה. ותחשב.
** סז: ראיה ראשונה -
נמצא שטומאת ראיה ראשונה של זב הוא אותו טומאה של זב שראה שלש זמנים. ותו"ת.
** כחתימת פי האמה -
ק"ק ל"ל פרכים ממה שעדיין שיעורו יותר קטן. ואין לומר שלא נחשב זה פירכא, ראשון שמסברה ייחשב פרכא, ושני, שגמרא פורך כן בכמה מקומות לומר שלא נלמד טומאת מת מטומאת שרץ. ותחשב.
** סח: שמחת יום טוב נמי מצווה -
ואם תאמר הרי אף רבי אליעזר מודה לזה לפעמים (כמו אם עושה כולו לכם). ויש לומר שעל כל פנים, אינו מצווה מוכרחת). גם יש לומר שיאמר שדין זה נכון- אבל רק אם אינו מצוה. מסתמא, ר”י הקשה כיון שיש לו מקור  (שאי לאו הכי, אינו ראיה, שר”א יחלוק), ואז ר”א יוקים אותו מקור בציור שאינו מצוה, כמו אם כבר למד. ותחשב.
** דבעינן נמי לכם -
יש לדון אם לפי רבי אליעזר צריך אף לכם או צריך לכם. לשון גמרא קצת משמע כצד ראשון, אבל זה יותר מחודש; היה נראה לומר שעושים כביאור אחד בקראי, והוא ביאור שכולל אכילה. ותחשב על זה. יש להעיר שאם כן, “מודה” הוא רק נכון במקצת, שעדיין חולקים קצת בדין זה (אם צריך חציו לה’). ותחשב.
** לבר מעצרתא -
קצת קשה למה לא אכל בשבת.
** בזמנו -
עיין ברש"י, שמבאר שטוב להקריב אימורי קרבן בזמן הקרבן. יש לדון אם הענין הוא להקריב קרבן בזמן זריקה או שחיטה של אותו קרבן או בזמן שצריך הקרבן להיות נזרק. זה אומר שיש קרבנות שיש להם זמן (למשל, קרבן פסח הוקרב ביד). אפשר שרק בהם יש דין זה. לא נראה כן; דייקנו מרש"י שאין יד’ זמנו, אלא שצריך להיות הוקרב בליל פסח. ותו"ת.
** סט. אמר לו ר”ע -
צריך ביאור ל”ל השיב רבי עקיבא ששאני דברים שהם לאחריו שאינם יכולים בע”ש. ותח’.
** גמרא
אומר ששחיטה שאי אפשר….. לכאורה, יוצא מזה יסוד אחד משנים אלו:
1. אף מצווה עצמו לא דוחה שבת אילו אפשר לעשות אותה מבעו"י (ואי אפשר לחלק בין מצוה למכשירים שלו).
2. שחיטה הוא מכשירים למצוות הקרבה, ואינו דוחה מחמת היותו מצווה.
** עקיבה בשחיטה -
יש להעיר שלכאורה לא מת בשחיטה (עיין בברכות). קשה, שקללת חכם, אפילו על חנם, באה. נראה שאולי שאני כאן, שחלק מן הקללה (חלק מן המילים שאמר) כלל מה שעבר בשחיטה. אז, נמצא שלא היה אפשר לקיימו כלל. ותחשב.
** טלטולי -
נמצא שפשוט לגמרא ששבות זה לא דוחה שבת, אף שמסיק ששבות אחר דוחה שבת.
** גברא גופיה חזי -
כמובן, צריך לפרש מה בכלל "חזי.”
** סט: בשביעי שלו -
צריך ביאור למה גמרא מניח שהם שווים, שזה עדיין מחוסר הזאה. צריך לומר שכיון ששניהם יכולים לטהר על ידי מעשה והערב שמש, הם שווים. דחוק.
** שלא לאוכליו -
לכאורה, כן מוכח ממה שאין ערל בכלל "שלא לאוכליו.”
** חולה -
יש לדון אם החילוק הוא שזה אפשר (אלא שאסור) או שזה יכול לטהר א"ע.
** כרת -
יש לציין לרש"י שאומר שמילה דוחה שבת מפני שמציל נפש מכרת. ותו"ת.
** ע. שוחט בה מיד -
מעניין שמניחים שכיון שצריך סכין, הטביל זה, שאולי היה לו סכין אחר שהטביל. אולי לא היה דרך בני אדם להיות להם יותר סכינים ממה שהיו צריכים לקרבן פסח. ותחשב.
** ע: אבין -
מכאן רואים (וכן אומר רשב"ם בב"ב) ש"רבין" הוא ל"אבין" (מסתמא ל"רב אבין").
** עא. מה ראית -
ואם תאמר נביא ראיה להיפך מכאן. ויש לומר שהראיה מיוסד על הנחה שיותר קל לומר שקמ"ל של הקרא הוא שאי אפשר לקיים בדבר שלא נזבח בשעת שמחה מלומר שהקמ"ל הוא שאין חיוב שמחה ביום אחד. אז, קל לדחות שאינו יותר קל לומר כן, ולכן צריך הוכחה זה. ותחשב.
** שעיכב ושחטה -
לא הבנתי כל כך; לכאורה, לא יכול לשחוט אותו בלילה, שכל הקרבנות פסולים בלילה. אז, צריך לומר ששחט אותו בטו. צריך ביאור למה ישחוט אותו בטו (ולמה נחשב דבר שבחובה), שהרי חיובו הוא רק להביא אותו כדי לאכול עם הפסח; אבל כבר אכל את הפסח. אין לומר שנשאר חיוב, שהרי אין חיוב במרובה. אולי כיון שכבר נתחייב (או כבר הקדיש לכך), חייב. דחוק.
** כסות נקיה -
לא הבנתי כל זה כל כך, שלא הבנתי איך זה יהיה מעולה מקדשים שנשחטו שלא בשעת שמחה. ותחשב על זה.
** עא: אימורי -
לא הבנתי ל"ל דן בשחט לשם קרבן ציבור עצמו. נראה שאם הוא קודם ששחט, אז יחלוק. אם הוא אחר ששחט, אז לא דוחה עוד. ותו"ת.
** עב. של שבת -
ואף שעדיין יש עליו מצווה, שלא קיים מצוה בכך, הרי לא חושב שיש לו את של שבת (אלא שחושב שאחר הוא של שבת). ותחשב בזה.
** עג. מידי נבלה -
מעניין שנחשב מתקן מזה, שלא היה נבלה כלל. גם מעניין שלא אומר שמתיר איסור אבר מן החי. (אולי משמע שנחשב איסור אחד. עיין בחולין גבי איתחזק איסור (קרוב לדף ט), שיש אומרים כן שם. עדיין יש לדון ל"ל אומר שתקן אותו לאכילת גוי. ותחשב.
** עג: דלית ליה בעלים -
צריך לחשוב למה פסול שאין בו בעלים הוא פסול בגוף יותר מפסול של זמנו. ותחשב.
** נראה ונדחה -
מרש"י נראה שמפרש למה יש פסול פסחים. אז, זה אומר שאף שלא מקריב לפסח, מה שהיה כשר למה שהיה עומד ושוב נדחה עושה פסול. היה אפשר לומר גם כן שאומר שאי אפשר להיקרב שלמים כיון שהיה נראה קודם חצות, ושוב נדחה בחצות. ויש לדון שלא היה עומד כל כך מתחילתו, שיכול לשהות, ולא נפסל כל כך אחר חצות. ודע שאילו היה כן, יש לדון אם זה פוסל אותו או עושה שאינו שלמים, אלא פסח, ואז יש פסול במה שאין בעל. ותחשב.
** עד. אינו נשרף -
ק"ק, שאף מה שאינו בתוך הבהמה לא נשרף. להוכיח ותחשב.
** כבולעו כך פולטו -
אין כל ענין זה כל כך פשוט לי. ראשון, יש לדון למה יפלוט את הכל; אם נעשה על ידי דיפיושין, אז, ישאר בו מקצת. כמו כן, העיר לי א.י.ש. שיחזור ויבלע בו. באר לי- וזה פשוט- שזהו כוונת רשי כשאומר שיוצא על האור, והוא שכשיוצא לאור, הוא יוצא מן העולם. זה יתרץ שני הקושיות. עדיין נמצא שצריך לומר כן בכל ציור שאומרים כבולעו כך פולטו. ותחשב.
** עד: בכל התורה כולה -
אם יודעים, אז, מי אמר מה, קשה למה לא נאמר שמותיהם. אפשר שראשון שמעו ממי שלא ידע ש”חד אמר וחד אמר,” ושוב שמעו ממי שידע שזהו הכלל. כיון שכבר ידעו במחלקת בדרך ראשון, הניחו אותו כן (או לכבד מי שאמר כן, או כיון שכבר היה ידוע כן לבני אדם, ויהיה קשה לזכור דבר שאינו ממש כך).
** אסמיק חלייה -
לא מבאר גמרא כל כך מהו הציור. ראיתי בערוך השלחן שמבאר שזהו כשלא בשל אותו כלל, אלא נתן אותו בחלא. דנים אם הלך דם לחלא ואסר אותו.
** עה. אעצים קפיד -
לא הבנתי, באמת, למה לא נאמר כן. אז, צריך ביאור מה סובר תירוץ ראשון.
** והא גבי בת כהן -
אם כן, יכול להקשות משני ברייתות על הדדי, שאם של מתכת נקרא אש, קל וחומר ששל עצים ייקרא אש. ויש לדון, שאולי אפשר לומר צד לכל אחד למה ייקרא אש יותר (למשל, של עצים הוא יותר רגיל, אבל של מתכת יותר קל). ותחשב.
** אש עצמו -
לכאורה, אין זה קשה על גמרא כאן, אלא מקשה על אותו ברייתא. ותחשב. אפשר שהיה דורש שצריך להיות מה שאינו ממש אש, אבל כיון שכבר דרש מאותו קרא שהוא אש, לא דורשים כן. דחוק. ותחשב.
** אש עצמו -
עדיין כבר רבינו כל שבא מחמת אש. אז, נמצא שיכולים לעשות שניהם להמית אותו; יש לדון איך יכריעו בית דין מה לעשות. ותחשב.
** באש בסוף -
לכאורה, מחלק בין כלל ופרט לפרט וכלל. ק"ק ל"ל אומר כן (שלא אומר מילים אלו); קצצת משמע שלא אומר כן. אז, יש לדון מהו החילוק בין זה לכלל של כלל ופרט; ויש לדון ל"ל יאמר כלל ופרט כאן. ותחשב.
** עה: כרוך -
יש לדון למה גחלת חלוק משאר דברים, אז. אולי הוא מפני שהוא יותר מצוי. יש לדון אם הוא יותר בכלל קרא כיון שקרא נאמר סתם (שמשמע ציור רגיל שבו ישרף אדם) או שאז הוא יותר בכלל מילת אש. ותחשב.
** אלמא אפילו -
נראה שהיה אפשר לתרץ הכל לומר שלוחשות ועוממות נקראים גחלים, ועוממות ובוערות נקראים אש. ותחשב.
** עו. בסולת רותחת -
יש לדון למה יאמר כן גבי סולת, ולא יבאר כן כבר ברישא של המשנה. אולי רק בא באמצע הדיון. ותו"ת.
** קליפה מיהא -
אם כן, לכאורה, החלב יאסר, שאי אפשר לקלפו. ויש לדון, שאולי מה שהיה צריך לקלף הוא כל כך קטן שבטל. ותו"ת.
** מאן חכים -
כן דרך רבא לומר בכ"מ.
** עו: ריחא מילתא -
יש לדון אם הריח סימן (שמראה שיש ממשות של האיסור בו) או סיבה (שדבר עם אותו ריח אסור). ותחשב.[fn:5]
** אפילו -
ק"ק ל"ל אומר גמרא שזהו החידוש של "אפילו טלי וגדה,” שאומר שאף כשאין לחוש לתערובת בהמות עצמם, יש לחוש לתערובת טעמים.
** טעמים -
לכאורה, לאו דווקא הוא, ורצה לומר ריח. ועיין לעיל בד"ה ריחא מילתא.
** כיון דלא דחיא -
לא הבנתי התלייה, שנלמדים מפסוקים חלוקים. ותחשב. ונראה שהוא מפני שגמרא כאן הולך לשיטת גמרא לקמן שיאמר שדורש מ"מועדו…,” ולא כגמרא לעיל (סו) שלא דרש כן לשבת, וגמרא שם שלא דרש כן לגבי טומאה. באמת, צריך ביאור, ששני גמרות אלו סותרים הדדי. אולי גמרא כאן רק בא להזכיר הג"ש. דחוק, כמובן.
** הכתוב קבע מועד -
צריך ביאור מה אומר. לכאורה, הדרשה הוא שאומר מועד בהם, כמו בכל שאר הדרשות. צריך ביאור מה מוסיף, אז, במילים אלו.
** עז. דאין באים לכפר -
לכאורה, הדיון תלוי בלמה באים, ולא במה עושים. זה אומר שהיה אפשר לומר צד שיותר קל לומר שקרבן כפרה בא בטומאה, כיון שהוא כל כך קדוש, ואז, אף שהוא טמא, מועיל די. נראה שאין גמרא אומר כן; אילו כן, היה צריך לומר שהוא מכפר. אלא, נראה שהכוונה הוא שבא לתוצאה חשובה, ואז צריך לבוא. ותחשב.
ואגב, יש לדון למה אין אומרים שמה שהוא מכפר, ואז הוא קרבן קדש, הוא סיבה שלא ללמוד לו, שאולי כיון שהוא קדוש, טומאה בו הוא רע ביותר. ותחשב.
** דליכא תנא -
ואם תאמר ליכא תנא ששמענו שחולק אלא ר"ש. קצת משמע שהלכה כרבי שמעון נגד רבי יהודה. דנו בזה (עיין בחיד"א בעין זוכר). גם אפשר שהוא מפני שיש אחרים שאומרים כרבי שמעון לקמן. זה היה ידוע מגמרא, ורק מביא ברייתא זה להוכיח שהוא רק שיטת רבי יהודה שחולק.
** במועדו -
עיין לעיל (סו.), שמבואר שלא דורש מ"מועדו,” אלא זה ג"ש ללמוד מזה לזה.
(לעיל כבר הערנו על זה.)
** דם זבחיך ישפך -
צריך ביאור מהו המשמעות מזה, שרק אומר לשפוך דם, ולא אומר שזה אף אם אין בשר. אולי הוא מיותר, ואז מרבה ציור אחר שצריך לזרוק.
** עז: כל היכא -
משמע שכלל זה מחלקת, ורבי אליעזר חולק עליו. אז, יש חידוש: רבי אליעזר סובר שכל מקום שיכולים לומר שכתב תורה דבר אף שיש קל וחומר, לא דורש ר"א ממנו.
ויש לדון; אפשר שפשוט שלא לעולם דורשים; לפעמים יהיה הדחק של אמירה שטרח וכתב ליה קרא פחות מן הדחק לומר אותו דין. אז, לא נדרש. ר"א רק אומר שכן הוא כאן. יש לדון, שסתום בשקו"ט של גמרא.
** עח: רב דאמר -
יש לדון ל"ל מחלקים בין מחשבה למעשה (שאולי יש בעיה רק במחשב לכך). ויש לומר שכיון שאינו ראוי לאכילה, נמצא שמכוון שלא ליאכל. עדיין יש לדון, שלא נשחט לשם כך.
** עט. כגופיה דזבח -
יש לדון מהו הקא משמע לן:
1. אינו כגוף הזבח. כדי לזרוק, צריך להיות מתיר אותו זבח, והרי זה רק מתיר זבח אחר. קצת יש לדון למה צריך להיות מתיר אותו זבח.
2. אינו די לזרוק עליו. זה אומר שזריקה צריך לעשות יותר מהגרמת מנחה[fn:6].
לשון גמרא משמע כראשון. (שוב הבנתי שיש לדון, שאפשר ש"כגופא דזבח" לא ר"ל שהוא כגוף זבח לענין שיהיה צד ראשון, אלא שאז יהיה חשוב די, ועליו נזרק דם, שהוא יותר משאר מנחות. ותחשב.)
** נטמא הסכין -
ואם תאמר אם כן, נטמאו כהנים. ויש לומר שרוב כהנים לא נטמאו בהכרח, שלא צריכים להשתמש בכלים אלו.
** צריך ביאור למה
יכולים להקריב שאר בטומאה אם טומאה דחויה. נראה שיכול להיות שני תירוצים:
1. אין מעלה בעשייתו בטהרה. לכאורה, זה אומר שכיון שרוב כבר הוקרב בטומאה, אז כל הקרבנות נשתנו. אולי יש לעשות מזה יסוד לומדי עם מה שנחשב קרבן ציבור.[fn:7]
2. יש מעלה ביכולת לעשות בטומאה. לכאורה, זה לא פלוג וכעין זה.
** הללו עושים -
צריך ביאור ל"ל נאמר על פי דרשת הקרא שאמר לעיל שדוחה טומאה שאם רובם טמאים, ואז היו נדחים ולא יכולים לעשות, אז צריכים לעשות בטומאה. ויש לדון, שאולי רק יודעים שנעשים אז מחמת שהם יותר ממחצה, ולא כל מי שלא יכול להקריב בפסח שני. ותחשב.[fn:8]
** עט: לרב וללישנא -
יש לדון למה מתחילים מזה כדי לתרץ.
** ונשים -
יש לדון למה, אז, ברייתא מונה אותם כלל. ותו"ת.
** וס"ל כר"י -
אינו ממש כר"י, שר"י סובר שמחמת זה מביאים הכל בטומאה, וזהו. כאן, מניחים שצריכים לטמא אחד קודם. ותחשב.
** פ. דחזי -
אגב, ק"ק למה אומרים כן, שהרי גמרא לקמן אומר צד שפסח שני הוא תשלומים של פסח ראשון. אם כן, קשה ל"ל אומרים שמי שאינו ראוי לקרבן פסח ראשון לא מביא פסח שני.
** פ: נזרק ואחר כך נודע -
היה אפשר לדחוק שאינו אגב, אלא כך הוא הדין אם טמא אותו במזיד. ממה שלא אומר כן, נראה שכשטמא אותו במזיד, אף אם רק נודע כן אחר כן, עדיין לא מהני. נראה לדחות שרק לא מצוי כן, שכדי שיהיה כן, צריך לומר שטימא אותו במזיד, ועדיין חשב שלא נטמא (צריך לומר שחשב שלא מהני מה שעשה). ותחשב על זה.
** פא: יליף מועדו -
עיין במכות (יא.) שנמצא שם שמחלקת הוא אם לומדים הל"מ על ידי היקש.
** וטומאת -
כמו שכ’ רש"י, גמרא לעיל כבר יודע התשובה לזה, ויודע שהוא הל"מ. אם כן, סדר הגמרא קצת מעניין, שמביא מה שכבר יודע כן, ומיד אחר כך, מביא מה שלא יודע כן. אולי ענין ראשון מביא אותו, ושוב אומר שיודע כן, דאיתמר…, ומביא כל זה.
** קרא אמסכתא -
מעניין שמשתמשים באסמכתא שהיה אומר דבר חלוק ממה שהוא הדין. גם מעניין שיש אסמכתא להלכה למשה מסיני. לכאורה, שני דברים אלו מוכיחים שהוא כעין מש"א רמב"ם, ולא כמש"א ריטב"א (על כל פנים, כאן). עדיין ק’ ראשונה ק"ק, שזה רמז שאומר דבר קצת חלוק. ותחשב.
** פב. רב זביד -
רש"י מבאר שרב זביד חוזר לבאר תירוץ של רב חמא. אז, זה סגנון מעניין.
** לגופיה איצטריך -
היה אפשר לומר שאחד מאלו נצרך למה שהיה גמרא דורש ממנו בהוה אמינא לעיל בפרק שני (דין איסור הנאה).
** פג. רש"א -
ואם תאמר אם ת"ק אומר כר"ש, אז כופל מה שאומר, ואם אומר כר"י, אז כופל מש"א. אז, קשה למה נכפל תנא. ויש לומר שאין ת"ק כאן, אלא משנה אומר כך: יש קרא, ודורשים ממנו זה. רבי יעקב מפרש מה שדורשים כך, ור"ש מפרש מה שדורשים כך. ותו"ת.
** לבתר דנהוו נותר -
קצת יש לדון מה מניחים שקרה לאותם עצמות. לכאורה, לא היה רוצה לאכול אותם, שאסור לאכול נותר. אז, אין להניח שקרה אחר שנעשה נותר, שבין כך ובין כך עושה איסור (ויש לדון, שאולי אסור מחמת ספק, וצריך הוכחה ממה שלא יאכל נותר שלא ניתותר). אז, אולי שרף אותם. אם כן, צריכים להניח שלא ידע שהדין הוא שצריך אף לשרוף שימוש נותר.
** פג: דילמא הני -
לכאורה, נמצא שמניחים שרק חלץ מחצה. אז, צריך לומר שמניחים שעבר, אבל רק על חציו. מעניין להניח כן, שאם לא חש לאיסור, יחלוץ את כולו. ותחשב.
** לגיד הנשה -
נמצא שפשוט לגמרא שאילו הוא אסור, לא צריך לשרוף אותו. זה מעניין, שהיה אפשר לומר שהוא בשר, שנאכל, אלא שהוא אסור. אז, טעון שריפה. היה אפשר לומר שמה שנותר טעון שריפה הוא שלא נזהר די מלאכלו, אבל זה כבר לא יאכל. כמו כן, יש לומר שהוא מפני העבירה שקרה בו, ששהה, אבל כאן כך היה צריך לעשות. ויש לדון, שאף בספק לר"י, הרי היה אנוס. ותחשב. גם יש לומר שכיון שלא למעשה נאכל, אינו נחשב בשר די. ותחשב.
** עולת שבת -
רש"י לעיל למד מזה שחביבה מצווה בשעתו. אם כן, נמצא שלענין מקצת ימים הרי הוא רק לכתחילה, אבל לענין מקצת ימים הרי הוא אף מעכב לעשות שלא יכול להקריב אז. קצת צריך ביאור איך זה יכול להיות.
** לבדו ולא מילה -
מדמה אותם כיון שאינו בזמן מצוותם. יש לדון, שכאן הוא זמן מצווה של שריפת נותר, אלא אינו זמן אכילתו. אם כן, הוא חלוק, לכאורה, ממילה, שגבי מילה, אילו עשה מה שהיה חייב, היה, לכאורה, אותו דבר שעושה ואותו דבר שמקיים. אז, אולי רואים שאין זה כל כך טוב. גבי נותר, אינו כן, שאילו עשה מה שהיה צריך לעשות, היה עושה קיום חלוק. אולי כיון שביטל אותו קיום, יש צורך לעשות דבר אחר, ואותו צרוך הוא חזק. ותחשב.
** פד. שלקא -
מזה נראה פשוט ששלקא הוא בישול יותר מבישול, שלכאורה רק על ידי זה יהיה רך. עיין בראשונים בנזיר, שדנים בזה.
** בגדי הרך בצלי -
היה אפשר לומר עוד צד, והוא שמחדש שנאכל בגדי הרך בשליקא (הוה אמינא שנאכל רק מה שיכול ליאכל בכל בהמה בכל אופן. קמ”ל שצריך רק מה שנאכל בכל בהמה באופן זה.). ותו"ת.
** תניא כוותיה -
ורבה ידחה שזה תנא אחד מן החולקים.
** רבי יעקב אומר -
גמרא בכ"מ מדייק שרבי יהודה סובר שלוקים על לאו שאין בו מעשה. במקום אחר, הערנו שגמרא בתחילת תמורה אומר מכאן שרבי יעקב סובר שלוקים על לאו הניתק לעשה. הערנו שלכאורה צריך לומר שחולקים איזה יותר טוב לומר; אחד אומר ששל רבי יהודה יותר טוב לומר, ומי שלא אומר אותו צ"ל שחולק, ואחד אומר ששל רבי יעקב יותר טוב לומר. ותחשב.
נראה שאין זה מוכרח, שיש לומר ששל רבי יעקב הוא יותר טוב לכ"ע, ולא חולקים, אלא יש לעשות עוד דיוק ממה שאמר ש"לא מן השם הוא זה,” שאומר שאין אותו השם פוטר. ויש לדון, שהיה יותר נראה לומר שר"ל שלא נצרך, שכבר יש סיבה אחרת. ותחשב.
** לומר שאין לוקה -
לשון זה מעניין; לכאורה, אין לשון זה רק אומר שלא לוקה, אלא עושה שלא לוקה. קצת משמע שנתינת עשה הוא רק סימן. עיין במק"א שכתבנו צד שאומר כן.
** האי לאו בר אכילה -
לא הבנתי את זה כל כך. לכאורה, מה שיצא הוא ככל אבר שיצא. אז, צריך לומר שלא דן בו, שאילו דן בו, לא היה לו לדון ביצא כולו לחוץ. אז, צריך לומר שדן במה שנשאר בתוך. מה שנחתך כדי לחתוך אבר אינו אסור כלל והוא ממש ראוי לאכילה. אז, פשוט, לכאורה, שמותר הוא. אולי דן בעצם שנשאר. ויש לדון, שמה יעשה עמו. אולי יש נפק"מ אם פותח או נפתח את העצם למוחו.
** פה: מה שבת -
מעניין, שלכאורה, לא כתיב גבי שבת הוצאה, שמלאכת הוצאה נלמד ממלאכת המשכן, ולא מקרא. אפשר שלא מכוון להביא מקור, אלא ראיה, שמשניות משתמשים באותו לשון ואוסרים רק כשעוקר ומניח; וצריך לומר שסוברים שזהו הוצאה. ותו"ת.
** פו: להוסיף דמים -
אין הדיון כל כך ברור לי. לכאורה, יש שלש דיונים:
1. שכרו אותו לשעה. קודם שעה, רובם יצאו, ונשאר אחד. לזה, יכול להיות כמה דיונים:
  1. יש לדון אם צריכים לשלם לו כל דמי שכירות או לא (שהרי לא שמש כל כך למקצת זמנו).
  2. יש לדון מי משלם לדמי שכירות שבא מסוף השעה. הרי כולם שכרו לשעה, אבל היה חלק מאותו השכירות שרק אחד נהנה ממנו.[fn:9]
2. שכרו אותו לשעה. אחד מאריך אחר השעה. לזה, נראה שיש שני דיונים שבארנו. בתוך דיון ראשון, נראה שיש ארבע צדדים; לא רק דנים אם ישלמו לו שכר כמו שפסקו או פחות, אלא יש עוד שני צדדים, שאולי ישלמו כסתם שמש (שאין זה בכלל הפסיקה), או שלא ישלמו כלל (שאין זה בכלל הפסיקה).
3. שכרו אותו לשמש לסעודה. רובם גמרו סעודה בזמן אחד, ואחד ממשיך. אף לזה, נראה שיש לדון בשני הדיונים. בראשון, הדיון יהיה אם זה עדיין בכלל הסעודה או לא. לשני, הדיון יהיה אם כולם יחלקו את הסעודה בשווה או לא, כיון שאחד המשיך את הסעודה.
ותחשב על כל זה.
** פז: ואותיות פורחות -
יש לציין לגמרא עבודה זרה (יח.).[fn:10]
** עולא איקלע -
יש לדון אם זה נאמר לפי הוה אמינא של עולא (ואז הוא מפני שבבל הוא ארץ קל ללמוד, ואז עשה ה’ שיהיה קל לבני ישראל ללמוד), או לפי מסקנתו (ואז הוא שרצה ה’ לרבות שכרם של בני ישראל, ואז הניח להם לעסוק בתורה מחמת קושי).
** ובבלי עסקי -
ואם תאמר מהו הבעיה; אם לא אוכלים אותם, לא יצערו. אז, אינו קשה איך עוסקים בתורה. אפשר שר"ל שאם אף זה נמכר, צריך לומר שקשה לקחת מזון בבבל. גם יש לומר שאינו צער כל כך[fn:11] לאכול אלו, אלא שאין גוף נקי, ואי אפשר ללמוד. אז,  נמצא שהיה קל מאד לו אם לא לומד. ותחשב.
** פח: מלך -
לכאורה, זה מוכיח כפירוש רש"י ביש ברירה (ואולי חולקים לא יבארו גמרא זה כמו שבאר רש"י), שצריך ביאור מהו תירוץ של גמרא זה. הקשה שלא יהיה הבעל נמנה, שהרי נמנה על איזה שיהיה נשחט ראשון. זה ברירה. תירץ שמיירי במלך ומלכה שלא מקפידים איזה אוכלים. קשה, שעדיין הוא ברירה, שלא נשחט אחד ראשון עדיין. אז, צריך לומר כמו שאומר רש"י, שהבעיה אינו שאינו מפרט די על ידי קרק’ שיבוא, אלא שחוששים שמא חשב על אחד, וחשב על הנכון. אז, גבי מלך ומלכה, שלא מפקידים, לא חשבו, שמה להם בזה. אם כן, צריך לומר כרש"י, וכפירוש ראשון שכתבנו בחבורה שלנו על זה.
** גדי שלי -
ואם תאמר למה לא רק יקריב אחד מהם, ויתנה שאיזה שרצה רבו הוא של רבו והאחר חולין. ויש לומר שאם כן שחט חולין בבית המקדש. מעניין, שאם רבו רוצה שיאכל עבד עמו, נמצא שאין עבד יכול להקריב לעצמו. נראה שכיון שאין אפשרות להביא אלא אם כן מתנה כן, פשוט שרבו יודה. (ויש לדון, שרבו לא יודע. ויש לדון, שאולי כל אדם חושש לכך ומתנה.)
** פט: דעות שאני -
לכאורה, פשוט לגמרא שאם מסתבר להם להקפיד[fn:12], אז הדין עמהם. אז, הידון הוא אם מסתבר להם להקפיד. מחלק גמרא שכאן יותר מסתבר להם להקפיד. לכאורה, הוה אמינא של גמרא אולי סבר שהסברה הוא שווה. ותחשב.
** דעות שאני -
עיין ברש"י. צריך ביאור, שזה רק יתיר להם לעשות שלא ישב האחר עמהם. לא יעשה שלא יאכל כל כך. לא נראה שגמרא אומר שלא יאכל עמהם אלא שלא יאכל כל כך. צריך ביאור. אולי יכולים לקנוס אותו אם עושה דבר שלא רוצים בו. ותחשב. צריך לומר, אז, שאוכל עמהם, שאי לאו הכי, לא עשה שום רע להם, ואין להם לקנוס אותו. ותחשב.
** מאה -
כמובן, ל"ד, שמאה יאכל יותר.
** צ. החייהו -
לכאורה, ר"ל שיש לו קדושה קצת, עד שצריך להיות משתמש עמו לקרבן. ותחשב.
** צ: עד שיכלו -
אגב, אם נותן ממון, וכהנים קונים בזה גוזלות, יש לדון איך יודעים שקנו קן לכל אחד, שאולי נשתנה דמי קנים. ותחשב.
** דילמא פשע -
לא ר"ל שכיון שלא כל כך פשוט שיקרה לא נחשב ראוי, שאם כן יהיה כן מדאורייתא. גמרא לקמן מוכיח שהוא רק מדרבנן. אם כן, צריך לומר שזה רק דין מדרבנן, והוא שחוששים שלא יאכל אותם, וזה רע, שלא יטבול.
** שחל שביעי -
יש לדון למה פשוט שהם שווים, שאף מחוסר הזאה.
** שחל שביעי -
קשה מהיכי תיתי, שאולי מה שיכולים להקריב ביום שלאחר כן הוא מפני שאותו יום שלאחר כן הוא יום שביעי, וערב פסח היה יום ששי. צריך ביאור. חושב אני שדנים בזה.
** שחל שביעי -
קשה, שיזרקו עליהם ויטבלו, שאז הם רק טבולי יום, וכולי עלמא מודו שיקרבו. אז, צריך ביאור מה היה טענתם למשה, שהרי לא יגרעו.
** רב שמעיא -
נמצא שצריך כך למסקנא. כיון שהוא הדין גבי טמא טומאת מת בשביעי שלו, צריך לומר שאף מזים זריזים.
** צא. בפני עצמם -
לכאורה, חולה אינו מחמת חשש, אלא מפני שבוודאי יותיר, שרק יכול לאכול כזית, ולא כולו. לכאורה, יש עדיין נפק"מ (לא יכול לשחוט אם סומכים עליו לכזית). ויש לדון, שאולי מניחים שאז אחר יאכלו כדי שלא יהיה נותר. אם כן, ק"ק על רש"י שמפרש שאולי לא יאכל כזית.
** יש להעיר
שיוצא מזה שיש בעיה בשחיטת פסח שלא נאכל. יש לדון למה. אולי יש בעיה בקרבן (שנשחט ולא נאכל), ואולי יש בעיה במה שאז זה כבר יצא ידי ק"פ, ולא מביא פסח שני. רוצים שיביא פ"ש, שאז יקריב ויאכל. יש לדון, שמי יאמר שיוכל לאכול אותו יותר טוב. ותחשב.
** מי עבדינן חבורה -
ר"ל, עדיין תקשה על רבי יהודה מזה.
** צא: מעניין שגמרא
מניח שחיוב והבאה בפני עצמם תלויים זה בזה. ותו"ת.
** צב: אילימא אשוגג -
צריך ביאור למה צריך משנה וקרא למעט אותם, שהרי אינם בני כרת. ותחשב. צריך לומר ש"אינם בני כרת" אינו מסברה, אלא שכן נלמד מן המשנה (שפשוט לגמרא שלא נחלק). ותחשב. צריך ביאור.
** צג: לרחב"ע פטור -
יש לדון למה זה כל כך פשוט לגמרא, שהרי קל לומר שצריך עשייתו לתקן על ראשון. כיון שלא עשה, לא תקן, אף שנאנס עליו. ותחשב.
** מכה מהלך -
צריך לדון בחשבון זה לענין זמן מעלות להנץ וכדומה. ותחשב.
** כל שאין יכול -
לכאורה, ר"ל שלא יכול להכניס מזמן תחילת כשרות שלו (חצי היום) לסוף זמן כשרות שלו (סוף היום). ותו"ת.
** ואין דרך רחוקה לטמא -
לא הבנתי למה זה יהיה כן, ולמה טומאה יעשה שפטור לא יפטור.
** צה. עשה -
קצ"ב איך ממעטים פרט של עשה, שצריך אותו קרא כבר להוסיף ציור, והוא כשאינו בגופו. ותחשב.
** צה: מצווה דגופיה עדיף -
משמע ששחיטה על חמץ אינו נחשב בגופו. יש להעיר שדנים אם האיסור הוא לשחוט או להיות לו שחיטה. ותחשב מה זה אומר (שיש מצה אחד שהוא רע). משמע מגמרא שאינו שחיטתו שהוא רע. ותחשב. ויש לדון, שעדיין יש לומר שמה שהוא רק רע מחמת דבר שקרה שלא בגופו עושה שאינו כל כך בגופו. דחוק.
** צו: חצות -
ואם תאמר למה יקבע לו חצות, שהרי נקבע הוא בכל זמן שחיטה, כיון שיכול לשחוט אותו. ותחשב. אולי הענין הוא שאז כבר אחר קבוע, שבחצות, השני קבוע, כיון שאין לו ראשון. כיון שכבר קבוע על אחר, אינו קבוע על זה. ויש לדון, שאם כן, הוא רק אם קבע כבר שני (ולא אם לא הפריש שני עד לאחר מכן). ותחשב על זה.
שוב הבנתי שאין זה אפשר, שגמרא אומר לקמן (צח.) כן אף אם לא הפריש אלא אחר חצות. ותחשב.
** אסמכתא -
נמצא שאומרים כן על דבר שאינו אף דין דרבנן או הלכה למשה מסיני, אלא פשוט. לכאורה, זה אי אפשר לאסמכתא של ריטב”א, וצריך לומר כאסמכתא של רבמ”ם. צריך לומר שאף שפשוט לנו, יש בני אדם שאינו כל כך פשוט להם, ולאן צריך אסמכתא. ותו”ת.
** צט: מן המנחה -
צריך ביאור למה יאמר כן אם ר"ל קודם מנחה (כמו שאומר גמרא לקמן).
** קא. כחומרי דרב -
יש להעיר שלא ר"ל שלא עשה כשום קולי רב, שאז היה לו לומר שהחמיר חוץ משלש ציורים אלו. אלא, ר"ל שהיה עושה ככל חומרות רב, אבל לא ככל קולות רב.
** קב: אין אומרים שני קדושות -
לא מבאר למה, ואז אינו מוסיף כלום בביאור הגמרא.
** קד. תנאי היא -
לא כל כך פשוט, לכאורה, שהוא תנאי, שרק אומר שנוהגים כן. יכול להיות שני דרכים אחרים:
1. אולי נוהגים כן בטעות. נראה שממה שתנא הזכיר אותו, רואים נגד זה, שלא היה מזכיר אותו אילו לא היה בו ממש.
2. אולי נוהגים כן כיון שיש קצת טוב בו, אבל אין חיוב. (ואין לומר שגמרא מפרש שכך אומר ר”א, משלש טעמים:
  1. לשונו לא משמע כן. ויש לדון.
  2. אם כן, לא היה לו לומר שהוא תנאי, אלא היה לומר שרק מזכיר מנהג טוב. ויש לדון, שאולי “היה אומר אחת” לא ר"ל שהיה אומר שרק צריכים לומר אחד, אלא ר"ל שהיה אומר רק הבדלה אחד. אז, צריך לומר שסובר שאין ענין לומר יותר מאחד.
  3. אם כן, אין צריכים ברייתא זה, שיש לו לומר ממה שברייתא אומר שהרגיל אומר שלש (על כל פנים, אין הוכחה מן הברייתא שאין ענין לעשות יותר). ותחשב.
** כל החותם -
מסתמא, ר"ל שאומר שניהם. גם היה אפשר לומר שעל מי שחותם כך אומר כן ועל מי שאומר כך אומר כן. ותו"ת.
** והא מר לא שלש -
צריך לבאר מה אומר בזה, שאם יכול לומר רק שנים, אז מה יהיה הבעיה באמירת שבע. ויש לומר שהוה אמינא שהם הפסק. ואם תאמר למה יאמר אותם אדם. ויש לומר שרוצה להראות שיודע כל ההבדלות. אם כן, קשה ל"ל יכול לומר ארבע, מאותו טעם.
לא כל כך מסתבר לומר שהוא יותר טוב לומר שבע, שאז היה לו לאמורא שנזכר בגמ’ לומר שבע. ותחשב.
** מאן -
נראה שהוא לבאר שהוא תנא (שהיה ידוע מי הוא ריב”ס). (יש לציין לרשבם גבי מה שאין הלכה כמותו.)
** קד: שמעתתא מפומיה -
יש לציין לגמרא שאומר שנאמר בשם מי שהוא ראשון באמירתו ומי שהוא אחרון. כיון שהמימרא הוא שכן נהג, נמצא שאילו הלך ובדק לעצמו, היה לעלום נזכר, אבל כיון שלא הלך, לא יהיה נזכר חוץ מעל ידי בני אדם ששמעו ממנו.
** כברכת המצוות -
קשה, שהרי הזכיר בברייתא שאר דברים שהם כברכת המצווה.
** קו. שבת היא קובעת -
ואם תאמר ל"ל אמר שהלכה כרבי יוסי. ויש לומרש הוה אמינא שרבי יוסי לא אומר ששבת קובעת את זה לסעודת שבת, אלא שמותר להמשיך. אז, צריך לחדש שלרבי יוסי יכול להיעשות סעודת שבת.
אבל קשה, שלכאורה, צריך ביאור כמי פוסק, שהלכה כרבי יוסי, אבל רבי יוסי אומר בפירוש שלא צריך לפסוק. ותחשב. ונראה שר"ל ששבת אוסר לאכול אם לא התחיל לאכול, אבל כיון שכן, רואים ששבת עושה נפק”מ, ומסתמא די לעשותו סעודת שבת. עיין ברשי. עיין ברשבם שלא משמע כן. וצריך ביאור.
** קה: חביבה מצווה בשעתה -
לא כל כך פשוט מהיכי תיתי שלילה זמנה. הניחא בהקרבת אימורים, כתיב, “עולת שבת בשבתו.” אבל, כאן, בא לקדש שבת, והרי שני זמנים אלו הם בתוך שבת. אז, בין כך ובין כך יקדש בשבת.
** קו. עד כמה -
לכאוהר, המשיב שאל כן, שאי לאו הכי, קשה ל"ל יחשוב ש”כל השבת כולו” ר"ל כל השבת כולו.
** קח. כולי יומא -
ק"ק ל"ל חושב גמרא שאולי היה בכור, ולכן התענה. אולי פשוט לגמרא שהיה מיקל כמו שאנו נוהגים. גם יש לדון מתי התחילו מנהג זה, שלכאורה לא מוזכר בש"ס.
** קט. רביעית של פסח -
לכאורה, בו משערים כל רביעית, ואז צריך ביאור למה פרט של פסח. אם רק שיערו של פסח שם, קשה למה יהיה של פסח חלוק. נראה שאולי היו להם מדות, אבל בפסח, לא רצו להשתמש בהם מחמת חשש חמץ, ואז שיערו באלו שהיו ישנים או לא היו קבועים לתשמיש כל כך.
** בחשבון רביעית,
הענין יהיה כך:
נחשוב תחילה רום3 של אותו מקום. נעשה הכל ל():
שנים נעשה 2*10, שהוא 20. כן הוא בשנים השני. כן הוא בשנים השלישי, אלא שמצורף עמו *10, שהוא 5, וגם *10, שהוא 2. אז, אותו הצד הוא 20+2+5, שהוא 27.
נמצא שהרום הוא 27*20*20, שהוא 10,800, עשרון אצבע3.
עכשיו, נדון במקוה. מקוה הוא אמה על אמה על שלש אמה. נעשה כל אמה לטפח. אז, צריכים לכפול כל אחד פי שש. אז, נמצא שהוא 6*6*18. נעשה כל אחד לאצבע. אז, צריכים לכפול כל אחד פי ארבע. אז, נמצא שהוא 24*24*72.
עכשיו נעשה אותו ל ל(). כדי לעשות כן, צריכים לכפול הכל פי עשר. נמצא שהוא 720*240*240, שהוא 41,472,000, עשרון אצבע3.
עכשיו, נדון מהו הרישיאו ביניהם. כדי לעשות כן, צריכים לדעת מהו . זה נעשה ל3840.
נדון עכשיו ברישיאו בין ארבעים סאה לרביעית:
ארבעים סאה הוא 240 קב. זה 960 לוג. זה 3840 רביעות.
נמצא, אז, שהרישיאו הוא שווה. אז, החשבון מושלם.
** קט: ים שעשה שלמה -
ואם תאמר אין החשבון עולה כן. עיין בעירובין שמבאר כל החשבון.
** קי. לצאת לשוק -
אז, היה אפשר לומר שלכן אין חשש בסדר ליל פסח, שלא יוצא אז לדרך. ויש לדון, שאולי נמצא שיצא אדם למקום אחר[fn:13] כשגומר סדרו. (ובאמת, גמרא לעיל אמר שהיו רגילים ללכת לחבורות אחרים.) גם יש לומר שחוששים לחשובים. ויש לדון, שמסתמא ידעו חשובים לשתות עוד כוס. ויש לדון אם חשובים אף כולל חשובים שאינם ת"ח.
** ארבע כוסות -
אם כן, לא צריך רבא לתרץ לקושיית גמרא לעיל (שמביא לידי סכנה). ועיין ברשבם.
** הלכה למשה מסני -
זה מעניין, שלכאורה מציאות הוא.
** קיב. ואי לא -
עיין ברשי בשבת שמזכיר שני פשטים בביאור ואי לא (אחד אומר שהוא אי לאו אפשר לו, ואחד אומר שהוא אי לא מהני). לכאורה, זה אי אפשר לומר כצד שני, שאיך ידע אם מהני להסיר רוח הרעה.
** קיג: כולהון בי -
יש להעיר שכבר אינו נחשב כחי, כיון שהיה סומא.
** קיד. היין גורם לקידוש -
ק"ק, שלכאורה, שניהם גורמים לקידוש שתאמר. ותחשב.
** מאי ד"א -
צריך ביאור למה שואל כן רק על בית הלל, ולא על בית שמאי. נראה שהיה דרך של בית שמאי לדבר ראשון (כן אומרים העולם, וחושב אני שגמרא אומר כעין זה), ואז בית שמאי לא ידעו מה ישיבו בית הלל לשיטתם, ואז הוצרכו לכמה ראיות. לא נראה כן שאף ב"ה לא ידעו אם ב"ש ישיבו, שהרי לא ידעו מה משיבים על ראיותם קודם שאמרו אותם. באמת, צ"ב ל"ל אומר גמרא סיבה זה למה אמרו שנים. היה נראה לומר ששואל על לשון ד"א, אבל צריך באיור איך משיב. ותחשב.
** קיד: כי היכי דליהווי -
צריך ביאור, עדיין, איך מברך על השני כיון שכבר יצא ידי חיובו בראשון. אולי אין הכי נמי, ולצד זה יוצא בראשון, ורק על זה מברך. לא נראה כל כך, שפרש"י במשנה שמה שהוא מוזר הוא שטובל בתחילת סעודה.
אולי ר"ל שיחשוב שלא לצאת, כדי שיוכל לפכול, ואז יראו שמה שאוכל עכשיו הוא מוזר מאד, שאינו רק קיום מצווה. (יש לדון, שלכאורה ישאלו אף אם מצווה הוא.) אילו לא היה כן, היה רק חשש שמא לא יחשבו, ואז צריך ומר שמצות לא צריכים כוונה, ולא שיכוון שלא לצאת.
** קיד: לית דחייש -
לכאורה, רק מביא ראיה שרב הונא לא חש לו. נראה שאילו היו מחמירים, לא היה ר"ה נוקט את זה לציור, אלא יאמר דבר שהוא לכולי עלמא. יש לדון, שהיה אפשר לומר שלהיפך, אמר כן כדי להכריע הלכה.
** קטו. לאחר שמילא -
קשה ל"ל יאכל פחות מכזית ושוב יברך.
** ומבטל -
נראה שאילו היו שניהם דאו’, אז היה כעין מין במינו (כמו שאומר ר”ן הידוע גבי דבר שיש לו מתירים), ולא היו מבטלים זה את זה.
** קטו: פטרתם -
נמצא שלא צריכים לשאול כל השאלות, שהרי אביי לא שאל על כולם, אלא הם רק פתח לביאור. ויש לדון, אז, למה יש כל כך כמה שאלות.
** קטז. אף כאן בפרוסה -
עיין ברשי. קשה, שבכל זמן אדם צריך לפרוס את לחמו קודם שאוכל ממנו (גמרא שבת קיז:). לולי רש"י, היה נראה לומר שצריך שני חתיכות לחם (שלמים) עם פרוסה. ותחשב.
** הלילה הזה -
ואם תאמר איך יכיר הבן בהלכות אלו, ואיך יכיר שצריך להיות צלי לילה זה, ולא רק שכן רצה אביו לעשות. יש לומר שידע כן ממה שכולו צלי. גם יש לומר שלא מכיר כן, ובן לא ידע לשאול כן. משנה אומר מה שישאל אב לבנו כדי לבאר לו, ואב יאמר הלכה זה לבנו וישאל אב עליו. ותחשב (ואם תאמר אם כן למה לו לא יכול לומר לשון חיוב, כמו שאומר גמרא. ויש לומר שהוא מפני שאומר, “אנו,” וקאי אף על התינוק.)
** קטז: ולא עוד -
נראה שאולי חילקם לשני דברים כדי לומר שאין סיבה להגביה אותו, כיון שאינו קרבן, ואף יש רע אם מגביה אותו. ותו"ת.
** אגדתא -
צריך לבאר תליית דין סיפור עם דין מצה. אולי לא יכול להראות חיוב מצה אם אינו מחוייב.
** קיז. פסלו -
יש להעיר שאף בזמן קריעת ים סוף, “הללו עובדי ע”ז....”
** אפשר -
לכאורה, רצה לומר שהיו מצווים, ואז הוצרכו לומר הלל. יש לדון מהיכי תיתי ציווי זה מן התורה; נאמר שהוא מדרבנן, ומתוקן אחר כך. וצריך לעיין בערכין (י).
** וכן לדבר -
בכל אלו, יש לדון אם ר"ל שגם יכולים לעמוד מאלו או שצריכים לעמוד כך אף לאלו. גם יש לדון אם הם שווים או לא. ותו"ת.
** ידיד חול -
צריך ביאור מה נפקא מינא של היותו חול, שלכאורה, בין כך ובין כך, אינו קדש בפני עצמו. נראה שיש נפקא מינא מה יכול למחוק אם כתוב ביחד.
** קיט: שני אחיות -
משמע שהיה ס”ר. ויש לדון, שאולי רק כיון שעכשיו אסור, נראה רע.
ויש להעיר שממה שמשה לא אמר כן, משמע שמשה לא עבר עבירה, ואף קודם מתן תורה. אם כן, לכאורה, צריך לומר שקיים את התורה, כמו האבות.
** שיצא ממני -
אף שלא נקרא בן אברהם, כמו שאומר גמרא בנדרים (לא).
** קיט: נפיש טעמיה -
זה אומר, לכאורה, שמה שאין לאכול אחר מצה הוא כדי שלא יאבד הטעם. ואם תאמר הרי שותה כוס של יין. עיןי ברשבם (קכ.) שכ’ שאין זה מאבד הטעם כיון שהוא רק שתייה. אולי יש לציין להלכות גבי מי שצריך לרחוץ את פיו אחר שאכל דבר כדי לאכול דבר אחר.
ועיין בשי”ח ש”י על משניות (בהשלמות) שהערנו על ענין זה.
** קכ: מאי בקר -
עיין לעיל, שהביא גמרא קרא להוכיח על בקר אחד לומר שהוא בקר ראשון, והקשה מברייתא שסתם בקר הוא ראשון. נראה שאינו כל כך קשה, שהקושיה ומה שמקשה עליו חולקים במחלקת זה של ראב”ע ור”ע. ותו"ת.
* Footnotes
[fn:1] באמת, צריך ביאור למה מסברה נלמד רק לאלו שכתוב בהם אכילה, ול"ל נלמד לכל. ותחשב. אולי בחולין שנשחט לא רק לא כתיב לשון אכילה, אלא לא נאסר אכילה. אם כן, מובן למה אי אפשר ללמוד לו. ויש לדון, וצריך לעיין שם.
[fn:2] אבל עדיין, לכאורה מה שלא דורשים כן הוא חסרון ידיעה, שאילו ידעו מה שהוא נכון, היו דורשים כחכמים.
[fn:3] לכאורה, זה ר"ל שיש לקרבן זה קדושה מיוחד, והוא חלוק ממין קרבן אחר. אז, מחשבה הוא חלק ממה שקובע אותו קדושה. ותחשב.
[fn:4] יש להעיר שנקודה זה הוא, לכאורה, הסיבה שלא מפרשים לאו הניתק לעשה כך, שאין החיוב האחר על עבירתו, אלא על מה שלא מתקן אותו. ויש לדון, שבעבירה שלו, לא מתקן אותו. ותחשב. גם יל”ד, שאינו צריך להיות על אותו נקודה כדי לפטור, אלא רק באותו זמן. ותחשב אם נחשבים אותו זמן. ותחשב.
[fn:5] ואפרש לומר שהענין הוא כך: יודעים שטעם עושה שלא בטל (ואף בזה יש לדון אם הוא סימן או סיבה. מה שלא בטל, ולא רק שיש סיבת איסור מחמת טעמו, משמע שהוא רק סימן). נראה שכאן טעמו משתנה, אבל זה רק מחמת שינוי בריח (שידוע שטעם וריח תלויים זה בזה). אם כן, דיון גמרא הוא אם זה די להיות נקרא טעמו ניכר. ותחשב. ויש להעיר שכמובן, אפשר שזה תלוי באם הטעם הוא סימן או סיבה. ותחשב.על פי זה, מה שקורא לו גמרא חילוף טעמים הוא טוב. ותחשב.
[fn:6] אולי זה כן גבי כל מנחה, ואולי זה רק גבי זה, ומחדש גמרא שהוא מנחה קלושה (מסתמא זה שייך למה שלא הוקרב בפני עצמו).
[fn:7] ויש להעיר שלא תלוי, משמע מגמרא, על כמה פסחים יובאו בטומאה, אלא תלוי על כמה בני אדם טמאים. ותו"ת.
[fn:8] אין כוונת זה להקשות על גמרא, אלא לתת קצת קנטקסט.
[fn:9] באמת, יש לדון קצת למה נאמר כן, שהרי לפעמים היה רק נותן מזון לזה, ושוב נתן לזה….. ויש לדון, שאולי הביא לכולם בב"א. אף בלי זה, מרגיש אני חילוק, שהרי הוא נחשב עסוק בכולם, שהוא יביא להם מה שצריך בזמן שפנוי, מה שאין כן עכשיו, שאינו עסוק כך. וצריך ביאור.
[fn:10] אם הם ממש דומים, יש לדון ל"ל מנה אותם. אולי לא נחשבים באים מה’ (ואז אין ה’ מטעתם), שהרי נעשו בידי אדם.
[fn:11] כמובן, לשון גמרא לא משמע כן.
[fn:12] אולי הענין הוא שאז מסתמא רצונם יותר גדול או שאז מסתמא כבר קבל או לא קבלו.
[fn:13] אבל, דע שגמרא אמר שאין זה גבי אורח. אולי זה כמש"א רשב"ם, שלא היו עושים כן רבנן כיון שעדיין יש לחוש. יש לדון אם כאן עדיין יש לחוש.
