** ק. ה”ג -
אם רבן גמליאל הוא, קצת מוזר הוא, שמת בימי ר”ג (כמו שאומר גמרא בב"מ), והרי ר”א מת בימי ר"ע (כמו שאומר גמרא בסנהדרין), והיו ר”י ור”י תלמידי ר”ע. גמרא שלנו (וכן אומר רשב”ם עצמו לקמן) גורס רשב”ג, וזה יותר נראה.
** אמר”י אמר שמואל -
היה אפשר לדון אם זה קאי בפסח או בשאר יומים טובים ושבתות. עיין ברשב”ם, שמבואר שהוא בשאר ימים טובים. נראה שהוא מפני הסיבה שמבאר (עיין לקמן).
** ולא גרסינן -
לכאורה, אז, יוצא טעם מעניין למה מכסים את הלחם. לכאורה, אז, הוא רק בסעודת לילה, שרק אז בא שבת. ויש לדון, שאולי נתקדש יותר בכל סעודה. דחוק.
ואגב, יש להעיר שמה שצריך להביא אחר קידוש מטעם זה משמע שקידוש עושה שהוא יותר קדוש, שאי לאו הכי, לכאורה, הוא שבת אחר כך כמו שהיה לפני כן. ויש לדון, שאולי מיירי במי שמקבל עליו שבת בכך (והוא לפני ביאת שבת). ותחשב. גם יש לומרש הענין הוא שיבינו בני אדם שהוא שבת, שאז יבינו למה בא. אז, לא מקדש שבת, אלא עושה שבני אדם יודעים שהוא שבת.
** קא. והלכה כר”ש -
אמאי- עיין בלשונו; משמע שמקשה למה לא פסק כרב כאן כיון שכללו הוא לפסוק כרב. היה יותר נראה להקשות שיש סתירה, שאומר שפסק כרב בכל ציור חוץ משלש אלו, ואז צריך לומר שפסק כרב כאן. אולי אין למדים מן הללים, כמו שאומר גמרא בפרק קמא דקידושין. ותו"ת.
** קב. כוחו דרבי יהודה -
זה נגד מה שאומר רש"י בביצה לבאר למה כוח של היתר עדיף, שהרי יותר חידוש הוא להטעין ברכה, שספק ברכות להקל. ותו"ת.
** קד. רבי מנחם -
עיין במש"כ. בגמרא שלנו, כל זה כתוב כאן; צריך לומר שלא גרס אותו.
** קה. דאי -
משמע שהענין הוא מה שעבר, ולא מה שלא מצוי.
** קו. קידושא רבא -
גי”ל שהוא לשון סגי נהור, כיון שאינו ארוך כלל.
** קז. ש”מ -
משלא יבדיל כלל- יש לדון, שהרי כאן אומר ברכה, וצריך להיות שאינו לבטלה.
** קח. אשה -
מפרש... אין דרכייהו- צריך ביאור אז ל"ל פטור אף שלא בפני בעלה. ואולי אין הכי נמי, וחולק על גמרא שלנו. ותחשב.
** קח: בבת אחת -
עיין במה שכתב. ק"ק, שהרי כך הוא הדין. ונראה שמקשה שאם כן פשוט הוא. ותחשב.
** וכי מה תועלת -
עיין במה שאמר. לכאורה, צריך ביאור מהו הקנטקראס”ט למה שממשיך לומר שנותנים להם קליות ואגוזים. היה אפשר לומר שהוא רק שהם מה שעושים קטנים. אולי משמע שת”ק חייב לקטנים כדי שלא ישנו. דחוק. ויש להעיר שאז הוא יותר שייך למחלקת שמביא גמרא לאחר זה בין ת”ק ור”י. (אבל לאידך גיסא, צריך ביאור למה כאן ר”י אומר שנשים חלוקים וכאן לא אומר כן. ויל”ד שאולי צריכים יין לחירות, וד"א לשמחה. ותחשב.)
** קי: דלא קפדי -
הכי הו"ל למימר...- יש לדון, שהיה אפשר לומר שאף זה נחשב קפידא על זוגות, שעושה דבר כדי שלא יוזק בזוגות. ותו"ת.  כמו כן יש לומר גבי הצד שזוגי לקולא.
** קטז: בעבור -
לא גמרי- ואם תאמר אם לא גמרי, אם כן למה צריך הוכחה. וצריך לומר ששמעו זה, אבל שמעו שיש אומרים שאינו כנון (או שגמרו אבל לא ידעו אם הוא ואתו מילה, או מילה אחר שהוא אותו מילה), וממה שאין הכרח הוכיחו שאינו זה. ותו"ת.
** קיח: כשחלה -
עיין בשני פשטים שאמר. יש להעיר ששאל ל”שנים או שלשה דברים.”
** קכ: רבי יוסי -
עיין במה שמביא לראיה שהלכה כר”י. יש לדון, שהיה אפשר לדחות שאומר לו שאף לפי רבי יוסי מה שעושה אינו בעיה, וכל שכן לחכמים. דחוק.
** קכא. ולדר”ע -
שלא מצאנו- לכאור"ה אין זה הוכחה הכי חזקה, שיש להוכיח באופן יותר חזק משיטתו כאן. נראה שמבאר איך ידע גמרא שלא אמר שר”ע לא אומר שאף שיכול לקיים זריקה בזריקה של זה, אין ברכה שלו מהני, והוא שבין כך ובין כך, מסתמא חולק על נקודה זה. ותחשב.
