** ב. בכי טוב -
עיין ברש"י שתולה אותו בהנץ החמה. אם כן, לכאורה, גם תלוי בשקיעת החמה, ולא בצאת הכוכבים. לכאורה, רש"י מניח שצריך אור גדול, דומה ללילה. אפשר שמכאן דורשים זה (שצריך להיות אור, ולא רק יום), ולא כל הדרשה. ותחשב. זה אולי יבאר מה שהעיר תוס’ שלומדים מקרא אחר. ותחשב. (ואולי לכן לא אומר כטעם שמבואר שם, שסובר שזה דין אחר, והוספה על דין זה.)
** הא  קמ"ל -
עיין במה שכתב. מה שאומר שלכל כוכבים יש להם אור אינו מוכרח, שאולי יש כוכבים שאין להם אור, ורק מחדש שאלו שנראים שיש להם אור נקרא אורם אור, ואסורים בהנאה למי שנודר כן. על כל פנים, משמע מרש"י שהוה אמינא של גמרא היה שאין לכלם אור, וזהו הלימוד מקרא זה, לכאורה, שיש להם אור. גם אפשר שרש"י לא מבאר מה מלמד הקרא, אלא רש"י מבאר למה אין דורשים מזה שהוא רק כוכבים שיש להם אור, ואומר שלכל כוכבים יש אור.
** ב: הכי קאמר -
נראה שמה שאומר כן על אב על בן הוא שאומר שבספק אסור, וגמרא בסנהדרין (עב:) מוקים את זה רק באב על הבן. ותו"ת.
** משעת -
עיין במה שכתב. גם היה אפשר לומר שיש נפק"מ כדי לדעת אם המקום נהגו באותו חומרא או לא, שאם רק התחילו אחר כך, אולי לא נחשב שום מנהג, שמנהג הוא רק להקפיד ככל דין זה. ותחשב.
** ד. נבדוק -
משש- גם היה אפשר לומר שמקדימים מחמת זריזים כמו אברהם. ויש לדון כמה מן התירוצים שנדחו ידע הגמרא.
גם יש להעיר שאם ר"ל בקר, כמו שדייקנו מהרבה קראי לעיל, יש לדון אם יכול להיות משמע שש שעות. עיין בברכות (תחלת פרק רביעי) אם זה נקרא בקר. אולי שם דן רק לענין שחר. צלע"ש.
** חובת הדר -
זה מעניין. ותחשב.
** ה. ואימא כל חד -
עיין איך מבאר תירוץ של גמרא. מעניין שמניחים סברות כזה גבי דינים דאורייתא.
** אך -
בין השמשות- צריך ביאור מה מוסיף, אז, שכבר יודעים שלילה בכלל. אפשר שמוסיף שספק אסור. אם כן, צריך לומר שבדרך כלל, דין ספק דאורייתא לחומרא הוא רק מדרבנן (או שכן יהיה בהוה אמינא זה). ותחשב על זה.
** ו. הואיל וכי איתיה -
נראה שר"ל שאין החפץ נחשב ממונו מחמת זה (אין יחס זה כיחס שיש לממונו), אלא שלעשות אין לאדם דבר שגורם ממון הוא כלעשות שאין לאדם ממון, ואז חייב עליו. ותחשב.
** עושה לו מחיצה -
היכר- גי"ל שאז נחשב שהוא כחצר שמיוחד לכך, כגמרא לעיל.
** ז: על ביעור -
לא בדק- לכאורה, ר"ל שלא בדק וכל שכן שלא בער.
** דאכתי גברא -
אז, תנאים שסוברים שאין צריכים טבילת עזרא (עיין בברכות) יסברו שעל כל טבילה מברך לפניו, ולא לאחריו. ותחשב.
** ח: ולא אמרינן -
משמע שנחשב לשמה. צריך ביאור, אז, מה נחשב שלא לשמה. אולי ר"ל שלא אומרים ששלא לשמה עושה, ואז אינו טוב. דחוק, שעיקר חסור מן הספר אז. ודע שממה שנחשב צדיק גמור, ולא רק צדיק, משמע שהוא לשמה. ותחשב.
** ט. שאם כן -
קשה קצת למה צריך לרש"י לדקדק מה ר"ל מחצר לחצר, שהרי בין כך ובין כך אומר מעיר לעיר. ויש לומר שאין הכי נמי, אלא שמפרש מה ר"ל כיון שקשה לו שיאמר חצר לחצר ולא יאמר בית לבית. גי"ל שקשה לו בדין שעיר לעיר ר"ל מעיר לעיר, ששם פשוט לחלק. אז, צ"ל שר"ל בין חצר לחצר בעיר זה. אז, אומר שצריך לומר שאין חצר לחצר אומר כן. כמו כן, יש לומר שפשוט לו שבין חצר לחצר או עיר לעיר לא חוששים, ואז שניהם צריכים לומר בין בית לבית באותו עיר (כגון שאין חצרות בעיר, אלא רק בתים), או באותו חצר (והוא, אז, כעין עיר, אלא שחצר יותר קטן).
** ודאי וודאי -
אין כאן הליכה אחר רוב- תחשב על זה.
** ואי בעית אימא -
על דרבנן, סומכים על חזקת חבר- קשה, שאם כן, נאמר שספק מוציא מידי וודאי אף לענין בדיקה, כיון שהוא דרבנן. צריך לחלק בין ספק לרוב שחבר בדק. ויש לדון ל"ל חלק בזה בפני עצמו. צריך לומר שלא סובר שזה די אם ספק בדרך כלל לא מוציא מידי וודאי, שאז אף רוב לא יוציא. ויש לדון בזה. ונראה שמניח גמ’ שרוב של דין דאורייתא שווה לספק של דין דרבנן, ששניהם מותרים. ותחשב.
** י. בבת אחת -
אי אתה יכול לומר טהורים- קשה, שגם אי אתה יכול לומר טמאים. ותחשב.
** י: שלש השבתות -
משמע שהענין הוא שיש שלש לשונות, ולא שנאמר בשלש קראי. ותחשב.
** יא. בכור -
אפילו גרמא- יש לדון למה מזכיר זה. אולי המום שנעשה רק נעשה על ידי גרמא. לא היה נראה כן, לכאורה, שלכאורה, המום בא כיון שחותך אותו. ותחשב.
** יא: אחד אומר בחמש -
צריך ביאור למה צריך צל, שרק יראה אם השמש למזרח או למערב. צריך לומר שזה יותר קשה לעשות מלראות את הצל, שעדיין הוא קצת קרוב לאמצע (וקשה לראות חמה לזמן רב, ואז לא נוכל להבחין מקומו). ותחשב.
** יב: שעת ביעורו -
ימתין- ק"ק, שלכאורה, נדחה, שיש צורך אז שייאבדו. אז, לא מחכים לבער אותם. אם כן, לכאורה, יש צורך שיהיו לו עצים קודם לכן, כדי שלא ידחה. ותחשב. צריך ביאור מה רווח יש במה ששוהה לזמנו. ותו"ת.
** יג. מזון שני -
ק"ק ל"ל אומר שהוא מחמת שמה שמשייר הוא חמץ, ואסור אז לאכול חמץ.
** ואין מוכרים לעצמם -
רש"י אומר שחוששים בני אדם שנתן בזול. היה אפשר לומר שחוששים שלא נתן שום ממון. אולי לא חוששים שיגנב בהדיא, אלא רק יורה היתר לומר שזה דמיהם. דחוק.
** יד: דתנן כל הפוסל -
נראה שיש שני דברים שמזכיר רש"י בטבול יום:
1. איקלש, ואז לא גזרו עליו.
2. אינו דרבנן, ואז לא צריך כל כך חיזוק.
צריך שני דברים אלו, אחד לבטל גזרה שנצרך כיון שהוא דבר חמור, ואחד למעט גזירה שנצרך כיון שהוא צריך חיזוק. ותחשב.
** רש"י כ’
לבאר אביי ור”א בשם רבא שדורשים מקרא גבי חגי. היה אפשר לומר שסוברים כקושיה בגמ’ (טז.). ותו"ת.
** טו. ממחלקתו -
אומר כצד שאין הלכה כרבי אליעזר כיון שהיה בחרם.
** טז: דלא כר”י -
קשה, כיון שאינו כיוסי בן יועזר, היה אפשר לומר שסובר שמטמא מדאורייתא. ותחשב.
** יח. טומאה קלה -
כל מושג זה צריך ביאור, שלכאורה, קשה מתי נגעו בעצמם. אם היה קודם שהיו טהורים, לא יטמאו, ששבע לה טומאה. אם היה בשעה שהיו טהורים, לא יטמא, שנגע בטהורים. ותחשב על זה.
שוב הבנתי שלכאורה בכלל כל טומאה יש טומאת נוגע, ואותו חלק לא נסתר ממה שאינו עדיין חפץ הטומאה, שיכול להיות כן בכל נוגע. ויש לדון אם זה נכון, שהוא מחודש, שהניחא בנוגע, יש לו יחס לדבר טמא. ויש לדון, שאין לו יחס עוד, אלא היה לו יחס של נגיעה. אם כן, יש לומר שזה יש לו יחס של מה שהיה. נראה, באמת, שזה אולי פשט חדש, והוא שיש לזה יחס של מה שהיה. ותחשב.
שוב הראה לי ר.מ.ש. שהוא גמרא מפורשת במנחות שבא להוכיח שלא אומרים שבע לה טומאה. שם דוחה שנטמא בבת אחת, שכשנטמא במדרס ונעשה טמא, גם נוגע בעצמו אז.[fn:1]
** יח: דיו לבא מן הדין -
קצת יש לדון מהיכי תיתי, אז, שהנוגע במים שנגע בזב עושהשני, ולא נעשה שלישי. ותחשב. ותחשב.
** דמטמא משקין -
צריך ביאור מהיכי תיתי. ויש לומר שאף שמוקמינן בכלי, אין הוכחה למעט משקין. גם יש לומר שר"ל שבין כך ובין כך נמצא שהוא חמור ממנו בדבר אחד, ואז אין למעט כלי. ותחשב.
** דמשקין עלולין -
קשה, שאכניס זה, והרי אין משקין מטמאים משקין. ותחשב על זה.
** מילתא דאתיא -
מעניין, שהיה נראה לומר שזה אף יותר מקל וחומר, שהיה נראה לומר שיש כבר טומאת שניבראשון. ויש לדון, שאולי אינו כן. גם יש לומר שאף זה טרח וכתב. ותחשב.
** כ. נשאלים -
לא הבנתי לשון שני שאומר רש"י.[fn:2]
** כ: תלויה וטהורה -
נראה- מעניין שתלוי במה נראה. אולי נראה ר"ל איך מניחים, שנראה לנו שכן הוא. דחוק.
** צריך ביאור למה
(
צריך קרא למשקה שנגע בזב, שלא מטמא עוד משקה, שנאמר עליו דיו. נראה שאין הכי נמי, ואמר כן גמרא רק אגב אוכל.)
** כא: שלשים -
כב"ש- לכאורה, נאמר שסובר שלא חולקים בזה (שלא דרך תנאים לסבור כבית שמאי). אולי כן ר"ל.
** כג. צריכי -
רש"י זה משמע שאיסור בל יראה הוא גזירה. יש להעיר שהיה אפשר לומר שהוא רק בהוה אמינא, והוא שאילו רק כתיב חמץ, הוה אמינא שזה רק בחמץ, ומשום שהוא גזירה, ויותר ראוי לגזור עליו. עדיין הוה אמינא מעניין הוא. ותו"ת.
** כה. מנבילה -
מה שאומר שאין טריפה משתריא בשחיטה מעניין. יש לדון אם ר"ל שלא הותר בשחיטה, שאף אחר שחיטה אסורה, או שאיסורה הוא שלא הותר בשחיטה, שאין שחיטה כשרה עליו. יש להעיר שלכאורה גבי אבר מדולדל, האיסור הוא מין שני, ואם כן, יותר טוב לדמות כן כאן. ותחשב. א"כ, קצת משמע כצד שכתבנו בשיח שי בחולין שאיסור טריפה הוא שאין שחיטה מתיר אותו כל כך, שלא ממית אותו כל כך על ידי שחיטה, שכבר עומד הוא למות. ותחשב.
** כו. יזונו -
יש לציין למה שאומר קרא שזקנים אכלו ושתו, שר"ל שנהנו מזיו השכינה.
** כז: שאם -
צריך ביאור מהו החילוק (או, על כל פנים, מקור לחילוק) בין זמן ביעור לזמן אחר, שבוודאי אינו שבלי זה, לא יבוער כלל. ותחשב.
** כח. פיזור -
נמצא שפיזור ר"ל שלא יתן אותם לשק. יש לדון אם כן הוא אף בלחם. נראה שבלחם גם אומר שצריך ממש לפרר אותו. ויש לדון.
** כט: אי נימא -
קשה לל"א שר"ש הוא וגזר אטו זמנו. אולי רק מצאנו שקנס, ולא גזר אטו זמנו. יש לדון ל"ל אומרים שגם זה חלק מן הקנס. ותחשב.
** לא: לא קשיא -
מעניין שמניח שלמסקנת גמרא עדיין צריך שהרהינו אצלו, אף שאמר לו שיהיה שלו מעכשיו. לכאורה, אין צורך עוד לחדש שהרהינו, אלא שרש"י סובר שמסתבר שנצרך. ותחשב.
** ומדמדי -
תשלומה לכפרה- נמצא שתשלומי תרומה נחשב כפרה, אבל תשלומי גנב אינו כן.
** לג: בכביצה נמי -
זה מראה מקום.
** לד. פסול הגוף -
בקדשים- עכשיו, אומרים אותו אף לענין תרומה. ותו"ת.
** לד: אתרא דחשוכא -
עיין במה שפירש. גם יש לציין למש"כ רש"י במה שאין תענית צבור בבבל, ובמקומות אחרים, שהיה הרבה מים בבבל. אם כן, אפשר לומר שהיה מאד גשם, והיו עננים כבדים. אם כן, היה חושך.
ודע שמה שהוא עמוק לא יעשה שהוא חשך ברוב היום; רק יעשה שעלות ונץ ושקיעה וצאת יהיו יותר חשוכים. ותו"ת.
** לה: דמאי -
מה שאומר ראשון אינו, לכאורה, נכון כפי מס’ גמ’ (עיין לקמן). מה שאומר שני צ"ב, שאז קשה למה צריך אותו דרשה של "מי שאיסורו….”
** שהקדימו -
כדי שלא- לא בהכרח הוא מחמת כן; יכול להיות שרק רוצה מעשה שלו עכשיו.
** לז: כמחלקת -
מחומרי- היה אפשר לומר שחלקו לענין חומרא שלו (היתר מצה), ואז לא נחשב מקולי ב"ה. אם כן, צ"ל שבמה שב"ה לא מחשב לכם, חלקו לענין חמץ. מוזר.
** רוב עניים עושים -
נראה שר"ל שכך הוא סתם "מעשה אילפס.” גם היה אפשר לומר שר"ל שרוב עניים עושים כן למצה, ואז רואים שנהגו להקל. ותו"ת.
** לט. שלוקים -
חושב אני שזה מחלוקת ראשונים בנדרים.
** מב. ואלו עוברים -
יש לדון ל"ל פ’ שר"ל שעובר על אכילתם. (אולי רש"י סובר שעובר על שניהם, ובמש"א שעובר על זה, פשוט שעובר על אכילה, שרש"י סובר (אולי, ועיין לעיל) שכל איסור בל יראה הוא גזירה. ותחשב.
גם יש להעיר שלפי רש"י, משנה מוכרח לשנות לאכילה בסופו. אז, קשה ל"ל פירש אותו באופן שלא צריך לשנות- דהיינו, שכולו דן באכילה.
** ירק חי -
הרבה- נראה שאולי אמר כן מפני שאי לאו הכי, זה עוד סיבה שלא לאכול ירקות, וגמרא בשבת לא מנה אותו. ותו"ת.
** מב: במ"ך -
שעורים- אומר שיש בו סמ"ך, אבל באמת שי"ן הוא.
** מו. לפניו -
ואם תאמר למה בפניו צריך ללכת ארבע, ולאחריו רק הולך אחד (שהוא שנים בין הכל, שצריך לחזור). ויש לומר שכשהולך לפניו גם נתרווח מה שאין צריך ללכת שם לאחר זמן. אם כן, מה שאומר רש"י שלא חסר מידי ק"ק, שהיה לו לומר שנהנה. ונ’ שלא נחשב נהנה, שהיה הולך שם לאחר זמן. ותו"ת.
** נ. למידרשיה -
רש"י מפרש שרצה לדרש יותר מן מה שאמר גמ’ שאילו היה צריך להעלים מה שנאמר בגמרא לא היה לגמרא לאומרו. ויש לדון, שהיה אפשר לומר, “עת לעשות לה’" אף על זה. ותחשב.
** נג. אבל חיטי -
עיין במש”כ. ויש לדון, שהרי אף בשר אינו נקדש (ואף שקדש נעשה כמותו, קשה מה זה יעשה). ותחשב. היה נראה לומר, לולי רש"י, שאין כל כך צורך לומר שבשר הוא לפסח (שרק ישהה אותו עד פסח). אז, משמע שר"ל לקרבן פסח. אם אומר כן על חיטין, אולי מזהיר לבני ישראל לשמרם, שלכאורה חיטין צריכים שמירה גדולה. ותחשב.
** נג: מה ראו -
שלא דרשו וחי בהם- צריך ביאור איך למדו מזה שלא לדרוש “וחי בה,” שלכאורה אין “וחי בהם” בצפרדעים, ואז נפרך הקל וחומר. ותחשב.
** נד. ראשית -
באש- יש לדון מהי”ת שלא נכתב בעור. ויש לומר שאז צריך שעור נעשה. ותחשב. גם יש לומר שאז צריך שמכתב נעשה. ויש לדון, שהיה אפשר שנעשה של  ע”י מכתב, אלא ה’ עשה שהוא נכתב. ותחשב.
** באש -
אם כן, כבר נברא אש.
** שמואל -
מה שאומר שהיה הלכה כמותו לכאורה לא מפרש רבא. אולי הלכה כמותו בדינים. יש להעיר שאף בשאר דברים בדרך כלל הלכה כמותו. ותחשב.
** נו. לשון אחר -
יש לציין לגמרא לעיל שאמר שזכר אינו מוציא פירות גדולות. צריך ביאור.
** נז. וחציצה -
יש לציין לגמ’ בסוכה (שבו גמ’ מזכיר מחלקת אם לקיחה ע”י דבר אחר נקרא לקיחה).
** נח. צליית פסח -
מעניין שלא ידחה כאן, כיון שאי אפשר בציור כזה. ויש לומר שר”ל שיותר טוב שלא לדחות, ולכן עושים כן. ותחשב.
** נח: בשני -
עיין במה שבאר- יש לציין לגמרא בסנהדרין (נח:). ויל”ד, עדיין למה נקט אותו יום. ותחשב.
** סא. סורסי -
עיין ברש"י בסוף סוטה.
** סא: ת"ל זאת -
עיין ברש"י. משמע שיש חילוק בין שחיטה לזריקה. מרש"י לעיל, היה משמע שאין החילוק בין זריקה לשחיטה, אלא בין זריקה לאכילה (דהיינו, אם חשב שיכפר (דהיינו, שעליו יהיה זריקה) או חשב שיאכל). וצריך ביאור.
** קבע פגול -
עיין במה שפרש. ק"ק מה לנו בזה. לולי רש"י היה אפשר לומר כמה שאומר גמרא בתחילת מעילנ, והוא שרק זריקה שנתפגל לא נחשב עבודה. לא נראה כן, שהרי שיטה זה נדחית. ותחשב.
** סב: תשש כחן -
עיין במה שפרש. לולי זה, היה נראה לומר שר"ל שתשש כוחם כיון שלא היו יכולים להוכיח שאחרים ממזרים. אז, לא היו להם כוח על אלו. (עיין כעין זה בסוף קידושין.) ותחשב.
** וקסבר רבי מאיר -
נמצא שגמרא מקשה מסתם משנה על אחרים, ששניהם רבי מאיר.
** סג. עדיין היא מחלקת -
עיין במה שאומר. מה שמבאר לענין למה צריך להיות שאין לשחיטה אלא לבסוף צריך קצת מחשה- אז, תחשב.
** סג: חוץ לחומת בית פאגי -
יש לדון אם צריך להיות בתוך אותו בית מחמת "על,” או כדי לקדשו (זה אומר, שאולי אינו נלמד מחמת שאומר "על,” אלא שאולי ממה שנקדש, פשוט לנו שצריך להיות במקום הכשרו, שבלי זה לא נקדש.
** סה: חציצה -
עיין בדרשה שמביא. צריך ביאור איך דורשים כן. ותחשב.
** שחיטתו -
עיין במה שכתב. משמע שלא היה בעיה במה שמקריב אותו ביום טו, ולא ביום יד. ותחשב.
** הרכבתו -
דקיי"ל- יש לעיין בגמרא שבת (פרק המצניע) לראות אם ציור זה בכלל מחלקת רבי נתן ורבנן.
** סו: שיש לו היתר מן התורה -
מעניין למה רשי צריך לומר שהוא שינוי וגם לא מצוי (שהוא דרבנן הקל). אפשר לומר שמה שהוא רק מדרבנן הוא שהוא לא נמצא, אבל לא נראה שרשי אומר כן (וכן לא נראה כל כך מסתבר למה יהיה כן, אם לא נאמר שאיסור דאורייתא שלו היה גזירה). לא נראה כן, שהרי כל איסורי שבת יש להם היתר זה, ולא נראה לומר שכולם הם רק גזירות. ותחשב.
** לא בחר -
עיין במה שבאר רש"י. מעניין שה’ לא יבחר מחמת רגזנות שיקרה לאחר זמן. ואם תתרץ שה’ מאס מחמת שהוא איש שדרכו להתרגז, קשה למה זה חלוק משאר האחים. נראה שר”ל שנברא ביכולת להיות מלך, אבל מדות שלו לא היו טובים, אלא היה מרגז, והיה לו לתקן את עצמו. כיון שלא תקן את עצמו, לא מלך. ותחשב על זה. גם יש לומר שמה שקראה לאחר זמן הוא סימן לגמרא שהיה מרגז. אז, מסתמא ה’ מאס על רגזנות של ללפני כן. לא נראה כן מרש"י.
** סז. אלא לעולם -
צריך ביאור מהיכי תיתי שבא להחמיר. ותחשב.
** סז: מחילות -
צריך ביאור מהיכי תיתי ששמע שניהם מרבו כן, ולא רק שכן אמר (אמר שניהם ביחד). אין לומר שאי לאו הכי, קשה למה אמר אותם ביחד, שאז רק נדחה הקושיה לרבו, שאז קשה למה רבו אמר שניהם בבת אחת. ותו”ת.
** סח. לא אפיקתיה -
לא הבנתי את זה כל כך; צריך לחזור עליו.
** כתיב -
יכול לרפאות- לכאורה, הענין אינו רק שיכול לרפאות, אלא שמרפא (שרוצה לרפאות). היה אפשר לומר שאף זה נשמע (אבל לא כל כך פשוט, שאולי יש יותר צורך לה’ להחיות מתים), אבל עדיין ק”ק ל”ל אמר כן רש”י.
** סח: דבעינן נמי לכם -
עיין במה שמבאר. נראה שהענין הוא שהיה אפשר לומר שאין עצרת יום טוב, שתורה הוא קשה. (כמובן, אי אפשר לומר כן על פסח וסוכות, שהם זוכרים דברים שהיה הצלת גוף). אז, צריך להראות שהוא טוב. ותחשב.
** סט. אלא ודאי -
גמרא זה אומר ממש אותו דבר, ולא מוסיף כלום. אם כן, קצת צריך ביאור למה רש"י מביא אותו. ותחשב.
** ע. על השבע -
צריך ביאור מה כוונת רש"י כאן. ראשון, יש להעיר שלכאורה, משמע שמה שנאכל על השבע עושה שהוא יותר נהנה. זה מעניין. מה שאומר "ותיחשב" לכאורה, אומר שהאכילה או המאכל נתחשב כיון שרוצה ונהנה בו.
לולי רש"י, היה נראה לומר שמה שענין של על השבע הוא שמראה שאף שקשה לאכלו, אוכל אותו. זה מראה שמה שאוכל אותו הוא למצוה. נראה שאולי ההוכחה שאינו כן הוא מה שצריך להיות תאב למצה. אם כן, רואים שלא רוצים כן. ותחשב.
** ע: מנא ידעי -
עיין במה שפרש. יש לדון, שהיה אפשר לומר שהם החליטו שלא למשוך ממנו. יותר היה נראה לומר שמקשה איך יודע המוצא אותו שבא מחבורה קטנה ולא מחבורה גדולה. ותחשב.
** ישב לו בדרום -
עיין במה שפרש. ק"ק, שאם היו יכולים לעלות וכדומה במקום הראשון שלהם, אז יעלו. אם לא, כבר אנוסים הם. וצריך ביאור.
לולי רש"י, היה נראה לומר שרק לא רצו להתקרב לת"ח שפשעו כך. ויש לדון, שהרי הסכימו שהיו חכמים ודרשנים גדולים.
** לא צריכא -
עיין בגירסא שמביא. נראה שכוונת אותו גירסא הוא לומר שרק מת ביד’, ולא מת קודם לכן. לכאורה, זה קצת פשוט, אבל לא נראה כל כך קשה שגמרא יבאר את זה בפירוש.
** עא. הכי קשיא -
מעניין, שמשמע שאין גמרא משנה לומר שלא הקשה כך אלא כך, אלא אומר שהקשה כך, אבל רק הקשה אותו בעיה שאינו בעיה מפני שהיה לו בעיה שהיה בעיה. ותחשב בזה.
** עא: הפסח -
רש"י כ’ שני טעויות חלוקות. יש לדון למה; עיין בגמרא כשדן בציור של משנה שלנו.
** עג: וממאי -
עיקר מקומו- לכאורה, לא קשה שלא יודעים עיקר מקומו, שמסתמא היה בשום ברייתא ותוספתא שאין לנו, אבל היה לבעלי גמרא. ותו"ת.
** עד. רבי ישמעאל -
רבי קלונימוס- עיין ברשי ביצה כד: שקורא לו בקי בש”ס.
** כאחד -
בחוץ- לכאורה, אין בעיה במה שאוכל אותו בזמן הזה, שיכול להקריב קרבן בלי בית (כמאן דאמר שקדושה ראשונה לא בטלה). עדיין צריך ביאור למה אין בעיה במה שאוכל חוץ מירושלים. אולי יחשבו בני אדם (או אולי שיטה זו סובר) שנעשה כזמן היתר במות, ויכולים להקריב בכל מקום. ותחשב.[fn:3]
ועיין בגליון שגורס כאן “בחוץ.”
** עה. ברחים -
עיין בביאור רש"י. יש להעיר שעדיין צריך לומר שמניח גמרא שכיון שלא נוגע בו המתכת (הוא רק שם להעמיד את העץ) לא מבשל אותו, אף שהוא חם, והוא קרוב לו. ותו"ת.
** עו: חמשה -
מרש"י נמצא שלא רק ממעט ממה שתנא מנינא, אלא ממה שמנה כל אחד, ולא רק כללם בשם קרבנות ציבור. יש לדון ל"ל לומד אף ממה שמזכיר סכומם.
אפשר לדחות שכן אומר רש"י, ומה שהיה מתחיל עמו אינו "אלו דוחים…,” אלא "קרבנות ציבור…,” ושוב ימנה אותם. לא נראה כן כלל.
** עח. ביחיד -
אם כן, עדיין לא תירץ לשון פסול.
** עט. טהורים עושים -
צריך ביאור מה אומר. לכאורה, בא לבאר למה אומר שמביאים בטהרה, שהרי הם מיעוט, ומיעוט מביא בטומאה. ראשון, יש לדון למה זה צריך ביאור, שלכאורה, זה רק מפני שרובם מביאים בטומאה. כאן, אין רובם מביאים בטומאה. אלא, יוצא שסובר שלא תלוי בהקרבת רוב בטומאה.[fn:4] עדיין צריך ביאור, שגמרא מניח שיכולים לתקן מחצה ומחצה על ידי עשיית שאחד נעשה נרחק מקום. יש לדון למה זה מהני, שהרי עדיין יש טהור, ויהיה נמנה. אולי רק הקרובים נמנים- ר"ל הראויים לשון הקרבה נמנים. צריך ביאור. שני, מעניין, שמרשי משמע שיכולים להביא בטומאה, אבל אף יכולים להביא בטהרה. לא משמע כן. ותחשב.
** פא: בירה -
עיין בגמרא בזבחים (סופו)[fn:5] שחולקים רבי יוחנן ור"ל בזה. רש"י כאן מפרש כר"ל; יש לשון למה.
** פב. פנימה -
עיין במה שמפרש רש"י. גם היה אפשר לומר שלומד מפנימה ששאל שאולי יצא פנימה, שמשע שאף שאל על יצמיאה חוצה. ויש לדון, שאולי יש שני יציאות, ורק שאל על אחד, ובזה באר איזה שאל.
** כי האי -
אף שלא היה כן אילו לומדים ממנו, נראה שר"ל שיכולים לקיים שני המקראות, לומר שלעוםל הדין הוא שצריך עיבור צורה אלא אם כן יש הוראת שעה.
** חוץ למחיצה -
עיין במה שבאר בקרא. יש לציין לחז"ל על אותו קרא (חושב אני שהוא מדרש שם, אבל אולי הוא רש"י) שלא מפרשים כן. וע"ש.
** פג. דם ובשר חדא -
רש"י מניח שחולקים (וכן משמע לשון גמרא). היה אפשר לומד שלא חולקים כלל, אלא דנים במשמעויות חלוקים, שאחד אמר דבר אחד לענין מה שכוללים פסול שאינו בגוף, ואף אם לא מודים לכל פסול שאינו בגוף, ורק אומרים כן בפסול דם, ואחד אמר דבר אחד לענין מה שכוללים כל פסול שאינו בגוף.
** פד. בא הכתוב -
רש"י מזכיר כאן שני דברים. נראה שאפשר שהענין הוא שלא דמי ללאו דחסימה. חילוק זה חשוב הוא כיון שיש סיבה לחשוב שמחלק, והוא שמשמע שתעשה זאת ותינצל. לא משמע כן די לפטור מחמת זה. אם כן, אפשר לומר שאין הפטור ממש מחמת זה, אלא שזהו המשמעות שמוכיח כן, ועושה שהוא חלקו מחסימה. אם כן, יש לומר שהוא רק סימן, כמו שבארנו על גמרא.
** פה: וכן לתפלה -
גמ’ שלי כ’ ברש"י "פסח,” וצריך לומר, “פתח.” בגמרא חדשה כ’, “פתח.”
** פז. לא יאכל משל רבו -
עיין במה שבאר. מעניין, שהרי אין העבד יכול להימנות באחר, שצריך רשות מן האדון. אז, יש אותו צורך של שאר עבד. ואין לומר שמה שלא חשב אינו מפני שאין לעבד יכולת אחרת, אלא הוא מפני שצריך דעת עבד (למנות חלקו), שכיון שעבד אין לו אפשרות אחר, בוודאי ירצה. ויש לדון, שאולי ישאל לרבו להתיר לו למנות על פסח אחר, ולא יתן רשות לרבו, וחושב שעי"ז רבו יתן לו. ותחשב.
** פז: בהא נחתינן -
עיין במה שכ’. נראה שמפרש שר"ל שאנו עוסקים בזה כשאנן יורדים וכשאנו עולים, שתמיד הוא על מחשבה שלנו. גם יש לומר שר"ל שבהא דיון אנו דנים, ובזה אנו עולים, שכן אנו מסיקים. גם יש לומר שאומר שדנים באותו בעיה, ובזה יוצאים, שמסיקים שהבעיה הוא בעיה, ואין להם תקנה לו. ותו"ת.
** צ. והשתא -
משייר- נמצא שכשהוא ממון שלו, הוא כיון ששייר. היה אפשר לומר שרק לא נקדש עד שאינו ממונו, ולא ששייר. זה אומר ששיור משמע שכוון להשאירו שלו, ולא שאין סיבה שלא יהיה שלו. ותחשב.
** צב. חצר -
מרש"י משמע שנקרא כן מפני החידוש על קדושתו. יש לדון אם חדשו קדושה לעשות דין זה, או שחידוש קדושה היה תוצאה מדין זה. לולי רש"י היה אפשר לומר שנקרא כן כיון שחדשו בו דין. ותו"ת.
** צח. קדושת דמים -
עיין במה שפירש. יש לציין לתחילת ערכין שאומר שאף אם הקדיש מה שאינו ראוי, מיגו שבא קדושת דמים, בא קדושת הגגוף. אם כן, כאן, לכאורה, יהיה קדושת הגוף, אלא שרק לא נקדש להיקרב. ותחשב אם זה כוונת רשי. ותחשב.
** צט: לא יאכל -
הידור- יש להעיר שרש"י משמע שגבי אכילת פסח על השובע שאכילה שהוא על השבע הוא יותר טוב. צריך ביאור איך לפרש, אז, חילוק בין מצה לפסח. ותחשב.
** תשע -
מניח רש"י שסמוך ר"ל חצי שעה, ואז רואים מברייתא זה שאף שבת כפסח. יש לדשון, שמהיכי תיתי שזה סמוך. אלא נראה (ואולי כן כוונת רש"י) שמוכיח שאין "מנחה" דווקא, ורל סמוך למנחה. אז, אין סיבה לחלק. ויש לדון, שבאחד אמר סמוך על ידי אמירת "מנחה,” ואז צריך להיות יותר קרוב. ותחשב.
** קב: והא יום ראשון -
אפילו עני- יש לדון בזה, שצריך אותם ארבע לשאר מצוות. ותחשב.
** קג. על המזון שהוא בתחילה -
צריך ביאור למה אומר שחייב בו תחילה, שהרי בסוף הסעודה היה חיוב ברכת המזון בא וחיוב הבדלה בא (שהוא מוצאי שבת). ותחשב. אולי חיוב לברך בא בשעה שאכל (אלא שלא חייב לברך אז, אבל חל החיוב לברך בשום זמן. ותחשב על זה. ויש לדמות אותו להלוואה, שיש חיוב לשלם בשום זמן.). מרש"י לא נראה כן.
** קיא: מפחד -
ואינו יודע למה- ר"ל, כשאומר גמרא כן לקמן, קאי אף על זה.
באמת, יש לדון מהו החידוש כאן. לכאורה, הפחד בא ממה שסיכר או כדומה, ואז, יש לדון מה לא ידע. אפשר שרל שלא ידע שהפחד בא ממה שסכר. אם כן, כיון שגמרא אמר זה, קשה איך לא ידע. גם יש לומר שלא יבין סיבת פחד בדבר שמפחד. אם כן, לכאורה, פשוט הוא, שאילו היה דבר שמפחד, אז לא היה סיכור גורם אותו. ויש לדון, שנראה שאפשר להיות שיגרום שדברים שלא מפחדים אותו יפחדו אותו, אבל רק אם הם בדרך כלל מפחדים לבני אדם. ותחשב. כמו כן, יש לומר שיגרום שיבואו לו דברים המפחדים.
ודע שאם מבין שפחדו בא ממה שסיכר, צריך להבין איך הוא מפחד, כיון שיודע שאין בו כלום.. ותחשב.
** קיג: בכלדיים -
קשה, שאז הוא לאו בפירוש בתורה. שו"ר שכן הקשה רשב"ם. ונראה שאולי אסור לשאול את המת שמדבר מפי אוב, אבל אולי הוה אמינא שמותר לשאול לבעל האוב, והוא ישאל למת. ותחשב.
** קיט: זה המכיר מקום -
עיין במה שפ’. נראה שר"ל שמכיר מקום ישיבתו. גם יש לומר שמכיר מקום שלו בספר (באיזה דף הוא). ותו"ת.
** אבן מאסו -
עיין במה שכתב. גם היה יכול לומר שהוא מפני מה שאומר גמרא (סו:) שהיה אחיו ראוי למלכות, אלא שה’ מאס בו מחמת כעסו. אולי זה לא היה נודע, ואז לא מסתבר שאמרו כן. דחוק. גם אולי זה נחשב שמחה בקלון חבירו.
** קיט. שלש מטמוניות -
ואם תאמר אם כן אינו כל הזהב. אולי חולקים על הדדי. גם יש לומר שלא היו של זהב.
** מפתחות -
יש לדון איפה היתה בית גנזיו, שהיו במדבר. אולי היו הולכים עמו. גי”ל שהשאיר אותם במצרים. דחוק.
** קיט: אין מפטירים -
עיין במה שכתב. צריך ביאור מה אומר שהוא עיקר קיום מצוותו, שהרי כבר קיים את מצוותו. וצריך לחשוב על זה; משמע שיכול אדם לקיים מצווה אחר שכבר קיים אותו. אולי הוא רק כאן שהוא יותר טוב. ותחשב.
** קכ. כולם -
או בזמן הזה- צריך ביאור מה אומר. אולי ר"ל, “וכן בזמן הזה....”
** קכא. ברכת הפסח -
על אכילת- יש לדון אם אומר על מה מברך, או אם אומר הנוסח שאומר (ואז חולק על רשב"ם).
* Footnotes
[fn:1] עיין באותו גמרא שם. יש להעיר שמגמרא היה אפשר לומר שזה רק בטומאת תחתון, ונאמר שטומאה שם בא ממש בבת אחת על ידי עליון, שטומאת משכב בא ממנו (אם נאמר שמה שמטמא תחתון הוא מה שעליון הוא על גביו, ולא מה שזב על גביו), וטומאת מגע משכב בא ממנו. אז, נטמא שניהם. אבל, גמרא לא מביא ראיה, ואולי יש להוכיח כמש”כ ממה שלא מביא ראיה, מטומאת דבר אחד.אבל, עיין בתוס’, שמבאר שהיה אפשר לגמרא להביא ראיה. ותחשב.
[fn:2] הבנתי שיש כמה מאלו שהם על גמרא.
[fn:3] אגב, יודע אני שדנים פוסקים ביכולת להביא קרבן בזמן הזה. גם יודע אני שתולים באם קדושה ראשונה הוא לשעתה או לא. לא הבנתי כל כך, שאם הוא רק לשעתה, יהיה מותר בבמות. צריך לומר שאיסור במות לא תלוי בהיות קדושה אחרת. היה אפשר לומר צד שהדין הוא כך: יכולים להקריב בבמה אלא אם כן יש מקום אחר שהוא יותר טוב ממנו. אולי זה עושה שאין אותו מקום כל כך חשוב, או שאין ההקרבה כל כך חשובה, או שחייב לעשות הכי טוב (לא נראה כן, שעדיין לא יהיה רע ממי שלא הקריב קרבן כלל). אם כן, אם בטלה קדושת ירושלים, יהיה מותר. נראה שצריך לומר שסובר שלא מקריבים בבמה אף בלי זה. אולי הוא מאותו טעם, אלא לא נחשב כיון שהיה אופן יותר טוב לפני זמן. ותחשב.גם אפשר (איני יודע, וצריך לעיין) שלא דנים בקדושת ירושלים, אלא קדושת א”י. אף זה לא ברור לי, שהיו אבות מקריבים קודם קדושת א”י. כמו כן, הקריבו במדבר. ותחשב.
[fn:4] אולי כן משמע קצת ממה שהערנו במקום אחר, והוא שגמרא משמע שרוב תלוי על בני אדם, ולא כמה קרבנות נקרבים. ותו"ת.
[fn:5] הוא גם כן (בשינוי קצת) ביומא.
