א.
עיין ברש"י, שפירש ששואל במה מדליקים – "לעשות פתילה." כמו שנראה, המשנה ימשיך לדבר בפתילות ובשמנים. מתחיל בפתילות, וכנראה רש"י סובר ששאלת הגמרא הוא בענין פתילות, ומשם ממשיך לשמנים. אבל, אין הכרח כן, שאפשר לומר ששאלת גמרא הוא לענין פתילות ושמנים. איני מבין כל כך למה לא יפרש רש"י כן.
ב.
המשנה מתחיל למנות מן הציור הנזכר שני בהקדמה. גמרא בנדרים (ב:) מפרש שאין סדר לדברים, ולפעמים המשנה יתחיל מן הנזכר ראשון, ולפעמים יתחיל מן הנזכר שני. (עיין בר"ן שם, שבאר שאף שיש שני צדדים באותו גמרא, שניהם מסכימים אין הסדר צריך להיות דווקא. עיין בגמרא נזיר, שאומר שאין הסדר דווקא, אבל מיד אחריו, מנסה לבאר איך הסדר הוא דווקא. ע"ש.)
ג.
מאירי מבאר שמה שאין השמנים נדלקים הוא שהם עבים. גם מבאר שמה שאין הפתילות נדלקות הוא שבהם השמן נתעכב במקום אחד, וקופצת למקום אחר.
ד.
כתבנו את זה כמו שמבארים רוב הראשונים. אבל, מצאנו עוד שני מהלכים בזה.
הרמב"ם מבאר שכיון שאלו לא דולקים יפה, חוששים שבני אדם יצאו, שלא רוצים לשבת בפניהם. (איני יודע אם הענין הוא שאינו טוב לשבת לפניהם או שהוא רע לשבת לפניהם.) אם ייצאו, לא יוצאים ידי מצוות הדלקת נרות בטוב. )קצת יש לדון למה לא אומר שמה שהם לא דולקים יפה הוא בעצמו סיבה שאין קיום המצוה כל כך טוב. ותחשב.)
יש להעיר שלולי הרמב"ם המשך המשניות מבואר, שבפרק ראשון דן באיסור לקרוא לאור הנר, שמא יבוא להטות. אז, ממשיך בנרות שאסור אף להדליק, שמא יטה. אבל, לפי הרמב"ם אינו כן. לא כל כך קשה למה ידבר בזה, שהוא דיני שבת. גם אפשר שכיון שסוף פרק ראשון מדבר בערב השבת, הנוטה לשבת, ואז מדבר בהדלקת נרות שבת, שנעשה אז. ותחשב.
איני מבין איך הרמב"ם מפרש את הגמרא שמכשיר פתילות אלו לשבת של חנוכה כיון שאין נהנים מאור חנוכה. הרי, לפי' הראשונים, זה מובן, שכיון שלא נהנה ממנו כלל, לא חוששים שיבוא להטות. אבל, לרמב"ם, כיון שהוא לא דולק יפה, עדיין יצאו בני אדם, ואינו כשר להיות נר. נראה שהרמב"ם מפרש שלא רק פסול מלהיות נר שבת, אלא פסול להדליק בו בערב שבת, שמא יסמוך עליו לנר שבת. אז, אומר שיכול להדליק בו לנר חנוכה, שכיון שאסור להנות ממנו, לא יבוא לסמוך עליו לנר חנוכה. (באמת, אולי זה מוכרח, שאם הוא אסור בהנאה, בוודאי לא יכול לסמוך עליו לנר שבת, שהוא כדי לגרום שלום בית, על ידי הנאת ראייה שבו. יש לדון בזה, שאולי רק אסור להנות ממנו באופן יותר מוכח, כמו לשבת לפניו ולקרוא. אבל, לא אסור שיהיה האור שבבית. יש לדון. גם אפשר לפרש על פי מה שכתבו מקצת פוסקים להלכה, והוא שלדין יש שני חלקי מצוות הדלקת נרות שבת – יש חיוב שיהיה אור (מפני שלום בית), ויש חיוב להדליק נרות שבת (מסתמא מפני שתקנו רבנן שיקיים את החלק הראשון על ידי הדלקה, כיון שרוב מצוות תלויות במעשה. אז, אפשר לומר שמדובר כאן כשכבר מקויים מצווה ראשונה, ודן בקיום מצווה שניה. אולי בהדלקת נר – אף של נר שאין בו הנאה – מקיים מצווה זו, ואז יכול לקיים בו, אף שאסור להנות ממנו. ותחשב.)
לרמב"ם, קשה למה גמרא מבאר כל זה רק על משנה שנית. אולי הוא מפני שלפני כן אין הכרח לפרש כרמב"ם, ואז לא הקשה גמרא. ותחשב.
פי' שני הוא פי' הירושלמי. (עיין שם בירושלמי, שלא פשוט שמדבר בפסול שמנים גם כן, שאולי מדבר רק בפסול פתילות. אבל לא נראה שיפרש מקצת המשנה, ויסתם חלק אחר שלא הולך כאותו פירוש. עיין בפני משה, שכ' שגם מפרש פסול שמנים.) הירושלמי אומר שהוא שוכח ומוציא את הפתילה. איני יודע אם מכוון לומר כמו פי' הראשונים, והוצאת הפתילה רצה לומר שמוציא אותו באופן שיהיה השמן הולך לו יותר טוב, או אם מכוון לומר פירוש אחר. אפשר שמכוון לומר שהוא יוציא את הפתילה לגמרי, ויהיה כיבוי, כיון שאין לו עוד שמן. (לא נראה שצריך להיות שממש מכבה, אבל כיון שמסיר את השמן ממנו, נחשב כיבוי. יש לדון, שמחזיר אותו לשם, לכאו', וצריך לומר שנחשב כיבוי, אף שלבסוף לא נכבה. אם כן, בחזרתו, גם עובר בהבערה, לכאו'.) אולי מוציא אותו כדי לתקן אותו, כדי שידלק יפה (ראיתי שכ"כ פני משה), או אולי מוציא אותו כיון שאין צורך שילדק עוד (אם כן, ממש מכבה אותו). ותחשב. נראה שיש הכרח, שהרי הגמרא אומר שכיון שאסור משום טעם זה, מדליקים באלו בחנוכה, כיון שאסור להנות לאורו. אז, צריך לומר שמוציא את הפתילה כדי לתקן אותו. אבל, יש לדון, שאפשר לדחוק שכיון שמכיר שענין נר חנוכה אינו הנאה – שהרי אסור להנות ממנו – לא יוציא את הנר, אלא ישאיר אותו דלוק, למצוות נר חנוכה. ותחשב.)
ירולשמי מוסיף פי' שני, והוא שהפסול של אלו מיוסד על מה שצריך שידליק רוב הפתילה מבעוד יום, אם לא שפשוט שימשך בפני עצמו. (איני יודע למה צריך כן. אפשר שהוא גזירה, שחוששים שאם אין הרוב נדלק שלא יידלק, וייכבה מעצמו. אז, אולי חוששים שיבוא להדליק אותו בשבת, או חוששים שלא יהיו לו נרות שבת, ויבטל מצוות שבת. (יש נפקא מינא גדול ביניהם, והוא אם זה נוהג רק בנרות שבת שבו מקיים מצוות הדלקת נרות או בכל נרות שמדליק לשבת.) אם הייתי רוצה להיות למדן, הייתי מפרש על פי מה שדנו האחרונים למה לא אוסרים לאדם להדליק נר לפני שבת, כיון שהוא כחיציו, ונמצא שהוא כמדליק נרות בשבת. עיין שם, בדיון. אבל, אפשר לומר שמתיר כיון שכבר נדלק רוב, ואז הכל כבר עומד להיות נדלק, ונחשב שההדלקה שלהם קורה בערב שבת. ותחשב.) כיון שאלו לא דולקים יפה, חוששים שלא יהיה רובם דולקים מבעוד יום. (זהו הפשטות, אבל אפשר לומר שרצה לומר שכמו שצריך הדלקה ברוב, צריך הדלקה בדבר שקל להמשיך להידלק. אז, לא מדליקים באלו. אפשר לומר, לפי זה, שבאמת מפרש כמו גמרא שלנו, ושהסיבה שצריך הדלקה ברובו הוא כדי שלא יטה. אבל, עיין שם בירושלמי שמפרש שלפי זה יהיה אסור גם בחנוכה, אף שאסור להנות מן הנרות. אז, צריך לומר שאין החשש שמא יבוא להטות. ותחשב.)
ה.
יש לדון אם נמצא שדבר שבמנין זה מדליק היום או שנמצא דבר אחר שלא מדליק, ומהו הדין. נראה שהראשון לא נמצא, ונראה שפשוט שהשני אסור.
ו.
עיין שם, שכן אומר לפי רבה. אין לומר שאולי זה רק לפי רבה, שקושיית הגמרא מוכיח שהוא מוכרח לכולי עלמא.
ז.
כן היה נראה לומר בפירוש הירושלמי. אבל, עיין בפני משה, שפי' הירושלמי כמו הש"ס שלנו, ופירש שהירושלמי בא לומר שהוא פשתן ששחקו ולא נפצו, כיון שאי אפשר שהוא נעורת של פשתן, אחרי שמצאנו ש"היה הפשתן לנעורת." אבל, לשון הירושלמי לא משמע כן.
ח.
כמובן, זה כמעט אותו שם שנמנה במשנה. אפשר שמחדש שנשאר לו אותו השם. (אם כן, צריך לומר שלא יכולים להניח שמה שנקרא כלך הוא כלך של משנה, אם לא שנוכל להוכיח כן.) גם אפשר שמחדש שאין לו שם חוץ מזה, ושאין להוסיף על המשנה. (עיין בפני משה, שמפרש דברים כזה כן.)
עיין בגמרא חולין (סג) שמפרש שה"נץ" הוא הנץ, ומקשה: "אטו קמן קאי." לכאו', קושיה זו לא מובנת לפי הפני משה, וצריך לפרש כצד ראשון, ולפרש שלא היה עוף באותו זמן ומקום שנקרא נץ. אבל, אולי אף לפי פני משה, יש לומר שידע שאין שום דבר שנקרא כן, ואי אפשר שאין לו שם אחר. ותחשב.
ט.
בירושלמי אומר שרשב"ג שאל להולכי ים, ואמרו לו שכולכא שמו. יש להסתפק אם שניהם עשו אותו, או אם יש שני גירסאות מי עשה אותו. אם יש גירסאות שונות, יש להסתפק אם הירושלמי והבבלי חולק בגי' או אם, מתחילה, דבר אחד היה כתוב בשניהם, וברבות הימים, הגירסא של אחד מהם – אולי הבבלי ואולי הירושלמי – נשתכח, ואז נמצא שלא היו שניהם שווים. ותחשב.
י.
יש לדון אם ריב"ז חולק על שמואל. אם נאמר כצד שני שכתבנו לעיל, שמואל אומר שאין לו שם אחר, ואז מוכרח שריב"ז חולק על שמואל. אבל, אם נאמר כצד ראשון, אין הכרח. אבל, עדיין, מלשון הגמרא נראה לי שחולקים. (וא"ת איך ידע גמרא שחולקים. ויש לומר שמסתמא היה שמואל אומר מש"א ריב"ז אילו סבר כן. גי"ל שידע מהו הדבר שאמר שמואל, וידע מהו הדבר שאמר ריב"ז, וידע שאינם שווים. (באמת, רק צריך שידע אחד מהם, וידע שלא נקרא בשם שקרא לו השני.))
יא.
אביי אומר בגמרא שהוא "שירא פנדרא." הנחנו שבא לפרש שיטת ריב"ז, ולא שיטת שמואל. זה בוודאי נכון אם נאמר כצד שני שכתבנו לעיל בביאור שיטת שמואל (אם לא שנאמר שנוסף לו שם אחרי ימי שמואל, שאביי חי אחרי שמואל), אבל מלשון הגמרא נראה שהוא כן, ואז אני אומר כן גם לצד ראשון שבשמואל. גם לא משמע מן הגמרא שהוא עוד שיטה, אלא נראה שהוא מפרש שיטת ריב"ז. עיין ברש"י, שמשמע שאינו שיטה בפני עצמה, שאומר, "... אותו הכלך." לכאו', בא לומר שהוא אותו הכלך שדיבר בו ריב"ז. ותחשב.
יב.
עיין בדחיית גמרא, שמקשה על זה, ודוחה אותו, ושוב מצדד שאולי אין לדחות אותו. יש לדון מה מכוון לדחות שם, אם דוחים מה שאמר אביי (שמה שנקרא) או שמסתמא אביי צודק, ואם אביי אמר שנקרא כן, בוודאי נקרא כן, ואז דוחים מזה שיטת ריב"ז.
יג.
נראה שהטעם שזה יותר גרוע אינו מפני שעושה משי גרוע לעצמו לשבת בו, אלא מפני שהוא כבר נעשה לבגד, שהוא כבר קוקו"ן, וכשעושים מזה משי לבגד אחר, לא כל כך קל לעשות אותו בגד, ורק נעשה גרוע. ותחשב.
יד.
עיין בירושלמי שגם אומר שהוא אנבין קייסרי (במק"א, קורא לזה אגבין קייסרי). איני יודע אם זה בא לחלוק על פי' ראשון או לבאר אותו (ששם כמעט אומא אותם ביחד). זה נוגע למה שדנינו בביאור מש"א שמואל, שדנינו אם כוונת שמואל והולכי הים לומר שאין לו שם אחר. אם נאמר ששם זה שאומר לא בא לחלוק על שמואל, אלא לפרש, לא יהיה אפשר לומר ששמואל מכוון לומר שאין לו שם אחר, אם לא שנאמר שאותו שם נתחדשה בין זמן של שמואל (שם, הוא רשב"ג, ואז יש יותר זמן) וסדור תלמוד הירושלמי. עיין שם בפני משה שבאר שהוא הפסולת של המשי, שהוא הפי' שאומר רש"י בשיטת ר"י בר זעירא. אבל, אנו גם מסופקים אם ר"י בר זעירא חולק על שמואל או לא חולק.
טו.
כן ראיתי שהוא מתורגם. אבל, דע שאין וויל"ו כשר לערבה, שאין העלים שלו כשרים. אולי עדיין נקרא ערבה, אולי שהיא ערבה פסולה, ואולי שנקרא ערבה שלא לענין מצוות לולב.
טז.
כן כתב מאירי בפשט ראשון שלו. עיין בפשט שני, שמצדד שהוא המוח של הגמי. אבל, דוחה את זה, ומסיק שהוא כשר להדליק בו.
יז.
יש להסתפק אם מדליקים בשברא עצמו או אם יש בין העץ לקליפה מין צמר. כמו שבארנו, באנגלית, נקרא מולי"ן, וראיתי שהוא ווי"ד גדול, וראיתי שעשו ממנו עצמו פתילות, ולא עשו מן צמר שבו.
יח.
יש לדון למה, אז, לא יכול להיות נמנה במשנה. אולי הוא מפני שאז אין המשנה מחדש לנו דין, שאין לומר שאסור שישתמש בו כפתילה, שאין מי שרוצה להשתמש בו (ויותר מזה, אולי אף אי אפשר להשתמש בו). גם אפשר שאז דין של המשנה פשוט, שפשוט שהוא לא דולק יפה כלל, ובוודאי יש חשש שיטה. נראה כראשון. (אבל, כמו שבארנו, יש שני צדדים בראשון, אם הוא שבני אדם לא ירצו להדליק בו, או שאי אפשר להדליק בו.)
יט.
גם כאן יש לחקור כמו שחקרנו לעיל . אין הכרח שהם שווים. (אבל, משמע שצמר ושער שווים בזה.)
כ.
יש להעיר שאינו מוכרח ליישב כן, שאפשר לומר שכיון שהם שני דברים, תנא ושייר. (אבל, זה תלוי במה שחקרנו במקום אחר, בענין תנא ושייר, למה אומרים אותו רק אם יש שני דברים שמשייר תנא. אפשר לומר שהוא מפני שיותר גרוע לשייר דבר אחד, שהוא רק אחד, וגם אפשר לומר שאם הוא רק אחד, נמצא פשט לבאר אותו, אבל אם הוא שנים, קשה למצוא פשט, וכבר מוכרח שתנא ושייר. צריך לחשוב יותר על זה, אבל יוצא שלשני, כיון שיש פשט אחד שמבאר לשניהם, כאן כאילו שייר דבר אחד, ואז לא נאמר עליו שתנא ושייר. ותחשב.)
כא.
עיין בגמרא. יש לדון אם מי שאומר שהוא קירותא ומי שאומר שהוא פסולת דבש חולקים. עיין שם בגמרא, שנראה שמוכרח שלא חולקים, שאחרי שאומר רמי שהוא פסולת של דבש, גמרא מקשה מהו הנפקא מינא. ממה שלא אומר שהנפקא מינא הוא דין של המשנה, צריך לומר שכולם מסכימים בביאור המשנה, ושלא צריך לחדש את זה. אבל, יש לדון, שאולי רק כולם מסכימים לדין, ואם יהיה מחלקת יהיה רק בפירוש המשנה. אבל, עדיין לא נראה שישאל על זה מהו הנפקא מינא. (אבל, הערה נכונה היא שיש לחקור, בכל מחלקת שמצאנו כאן, אם חולקים גם בדין או לא.)
כב.
עיין בביאור מאירי בכשרות ופסול שעווה. יוצא מן המאירי שיש ארבע דברים שיכול אדם לעשות עם שעווה:
1. יכול לעשות אותו לשמן.
2. יכולים לחפות בגד בשעווה, כמו נרות שלנו.
3. יכולים לחפות פתילה בשעווה, ולתת אותו בשמן.
4. יכולים לעשות פתילה משעווה.
מן הגמרא פשוט שהראשון פסול. המאירי מסיק שהשני פסול, שרואים שאין אור שלו חזק. (היום, רואים שאור שלו חזק; קצ"ב.) מסיק שהשלישי הוא הציור שמכשיר הגמרא, ומסיק שהרביעי לא אפשר, שא"א להדליק פתילה של שעווה.
כג.
עיין בירושלמי, שגם מצדד שהוא הנקרא "קיסוסא." איני יודע אם זה חולק על שיטות אלו או מפרש אחד מהם.
כד.
** צריך לבאר למה לא אומר שאסור להבעיר בי"ט כיון ששורף קדשים בי"ט, כמו שנבאר מיד. אפשר שלמסקנא יסיק כן, וגמרא רק מפרש שהוא גזירה כיון שלא ידע כבר שאין שורפים את הקדשים בי"ט. לא נראה כן, שבסוף הגמרא נראה שסובר שחולקים רב הונא ורבה בזה, שמביא בריי' לסמך לשיטת רב הונא. צריך לעיין בזה, שזה קושיה פשוטה. שוב ראיתי שמאירי הקשה זה, ומתרץ שכאן הוא לצורך י"ט, ואז יהיה מותר. קצת קשה למה נאמר כן, שמדובר כאן בהטייה לקיים את המצווה, וזה אינו לצורך י"ט. אולי כיון שמדליק יפה, יוצא ממנו צורך יום טוב, כיון שאור שלו יפה, ואז מותר. עיין בלשונו, שנראה שרק שיטה זו סוברת כן, אבל אין הוכחה לומר כן לכולי עלמא. ותחשב.
כה.
עיין במאירי, שמשמע (וכן משמע לשון הגמרא) שרב הונא לא גוזר, אלא מוקים אותו בציור כזה. אבל, אין הכרח לזה מן הגמרא.
עיין לקמן, שנבאר למה אסור בי"ט. אם נאמר שיש גזירה, יכולים להבין אותו, כמו שנבאר. אם לא, קשה מתי יהיה אסור בי"ט. אולי מדבר בשני י"ט של גליות, ואולי גוזרים בעי"ט לי"ט, מפני י"ט שחל בע"ש, אף אם לא גזר בע"ש לשבת (כיון שאין י"ט בשניהם). גם אפשר שהמשנהף כשאומר שאין שורפים בי"ט, רצה לומר שאין בידיים שורפים בי"ט, ולכן אין מקיימים הדלקת נרות בו בי"ט שחל בערב שבת. כן נראה. ותחשב.
כו.
לפי זה, מה שאסור להדליק בו לי"ט הוא, לכאו', מפני חשש של י"ט שחל לפני י"ט, והוא שני ימים טובים של גליות או שני ימים טובים של ראש השנה.
היה אפשר לומר שגם רב הונא מודה לרבא שהוא גזירה על י"ט מחמת שבת, אבל עיין בבריי' שמביא סמך לשיטת רב הונא, שמשם מוכח שר"ה לא גוזר יום טוב אטו שבת.
עיין לעיל, שדנינו אם יש גזירה.
כז.
עיין בירושלמי, שיש לו שיטה אחרת בגמרא זה. שם, נותן שני פירושים. הפירוש הראשון הוא שאסור להדליק בערב שבת כיון שאסור לשרוף קדשים בשבת, ובכלל איסור זה, מחדש, הוא לגרום שקדשים נשרפים בשבת. (אז, אינו רק חסרון היתר למלאכה, שכאן לא עושה מלאכה, אלא הוא איסור.) כיון שמדליק אותו לפני שבת, נמצא שהוא דולק בשבת, ונמצא שמבעיר קדשים בשבת. הפירוש השני הוא שאסור להדליק משום גזירה מחמת יום טוב שחל להיות בשבת. אבל, משקלא וטריא שלו (הדיון בהדלקה בלילה) יוצא שהבעיה אינו שאסור להדליק בי"ט מחמת איסור מלאכה שבו, אלא אסור לבער קדשים בי"ט, וכיון שמתחיל בי"ט, נמצא שכל שריפתו באיסור (אף שנמשך אחרי י"ט), ואז יש בזה איסור. (יש לדון אם אסור לבער קדשים בי"ט או שאין זה ביעור טוב, ונמצא שמונע אותו מביעור טוב.) (מעניין שירושלמי צריך לחדש שכיון שמתחיל בזמן שאינו ראוי, יש איסור בביעור, ולא אומר שכיון שנמשך לשבת, וגם שבת כי"ט במה שאין מבערים קדשים, נמצא שכל ביעור שלו הוא בזמן שאינו ראוי.) יש להעיר שיש מקורות למה שאין מבערים קדשים בי"ט שמובנים רק בשיטת הבבלי, ולא בשיטת הירושלמי. כנראה, הירו' לא יסבור כאותם השיטות. ותחשב. ירושלמי גם מוסיף שמותר להוסיף קצת שמן של חולין, ולהדליק בשמן שרפה. (איני יודע אם הירושלמי מכוון לומר דין לכתחילה או דין בדיעבד, שמלשונו קצת משמע שמכוון לומר דין בדיעיבד, אבל אינו קרוב להיות מוכרח כן.) איני מבין כל כך למה זה יתיר, שלכאו' עדיין יש איסור שריפת קדשים בשבת וי"ט. נראה שצריך להיות שהולך בפשט השני שלו, וסובר שכיון שמשנה, שמוסיף בו קצת משמן אחר, לא גזרו בו רבנן. ותחשב.
כח.
מניח שיש בזה איסור יום טוב. זה מחודש, שהיה אפשר לומר שאף אם אין בו צורך אכילה, יהיה מותר מפני שנאמר בו "מתוך."
כט.
איני יודע למה מחלק אותם. אפשר שיש צד לחלק ביניהם, שאולי שורפים בדרך שונה.
ל.
עיין במאירי שמפרש שאליה הוא שומן, וחלב הוא חלב.
לא
לכאו', אין זה קשה על דין שמן דגים, שנראה שהוא דבר שונה, שזה קרב, וזה שמן.
שו"ר במאירי, שכ' בפירוש שאין זה שווה לשמן דגים. אבל, עיין ברש"י, שכ' שהם שווים. כן משמע מגמ' לקמן (כו.), ועיין בתוס' שם שחולק על רש"י.
לב.
עיין במאירי שמזכיר שיש מחלקת אם מהותך שווה למבושל. עיין שם, שנראה שמניח שמהותך ומבושל שווים לפי רש"י.
לג.
עיין בגמ', שנותן טעם ראשון, ומוסיף טעם זה. ק"ק למה לא אומר גמרא את זה לעיקר, כיון שהוא סכנה, וסכנה חמירא מאיסורא, כמו שאומר גמרא בתחילת חולין. אפשר שכיון שסכנה חמורה, טעם זה פשוט, ולכן אומר טעם הראשון, כיון שהוא המחודש.
לד.
צריך לבאר אם זה עושה איסור גם בחול. מגמרא לא משמע כן, שרק מזכיר איסור בשבת. באמת, נאמר סתם, אבל לכאו' היה לו לפרש שהוא גם אוסר בחול. כמו כן משמע ממה שלא אומר טעם של עף, שהוא נוהג גם בחול, ואמר טעם שאוסר רק בשבת. אבל, קשה, שטעמו שווה לטעם של נפט לבן, וכמו שנפט לבן אסור בחול, כך צרי יהיה אסור בחול. אפשר שחולקים תנאים בזה, ואפשר שזה לא כל כך עף כמו נפט לבן. עיין לקמן, שאולי יש הכרח נגד זה.
לה.
יש הרבה דברים שלא מדליקים בהם בכל יום, כמו כל איסור הנאה. כנראה, מזכיר רק אלו שיש בהם חידוש.
לו.
כן אומר הירושלמי בפירוש, אבל עיין ברמב"ם שפי' שאסור שמא יברח ממנו ויצא. צריך לבאר איך מבאר מה שאוסר גם בחול. ותחשב.
לז.
אבל, קצת צריך ביאור למה נקט ציור זה. גם עיין בגמ' כאן, שמשאלתו, מוכרח שלא מפרש כן. אפשר שסובר שהגמ' אומר דין אגב, והוא שאינו מותר לבער קדשים בי"ט. אבל, לא משמע כן מגמרא לעיל, שמקשה מכאן שאותו הפסול נוהג בי"ט.
שוב ראיתי שראשונים (עיין בתוס' וברש"י) סוברים שגזרו רק בזה בי"ט אגב שבת. מאירי מפרש שהוא מפני שלא ניכר האיסור בשבת. עיין בגמ', בבריי' שמסייע לר"ה, שקצת משמע נגד זה, שבפשטות, מה שמסייע לר"ה הוא שמתיר להדליק בשאר שמנים שנמנו במשנה בי"ט. צריך לומר שהם מפרשים שהראיה הוא ממה שנותן טעם ש"אין שורפים קדשים בי"ט." אין זה ראיה כ"כ חזקה, שיש לומר שמבאר למה אסור להטות בשבת. אבל, לא נראה שזה צריך ביאור, וגם לא נראה שיבאר את זה כאן, שבא לבאר למה אסור גם בי"ט. ותחשב.
לח.
הנחתי שהם לא שווים, והנחתי שכשמשנה אומר "נפט" לא מכוון לכלול כל מין נפט. אבל, לא מוכרח כן, ואפשר לומר שהבריי' שמביא הגמרא חולק על המשנה. אבל, לא נראה כן, שהגמרא מביא שיטה שאין מדליקים בצרי, ונותן שני טעמים. טעם ראשון הוא שריחו טוב, וחוששים שיקח ממנו, וטעם שני הוא שהוא עף. בתחילה, הגמ' רק נותן טעם ראשון, ומקשה גמ' למה נותן טעם ראשון ולא טעם שני. לכאו', אם יש מחלקת בטעם שני, היה לו לומר שלכן לא מזכיר אותו, שבא לחדש שאף לתנא של המשנה הוא פסול (או מפני שסובר כתנא של המשנה). אפשר לדחות שצרי יותר עף, ופשוט שכולי עלמא יחושו לו, אבל דחוק לומר כן.
שוב ראיתי שכן אומר הירושלמי בפירוש; ע"ש.
לט.
לקמן, יאמר כן. שם, הוא לענין פתילה, אבל יש להסתפק אם שם רק פוסל משום פתילה, או שפוסל לכל דבר (שמן ופתילה), חוץ מן הפשתן, שהוא כשר לפתילה. (עיין שם ברש"י, שמשמע כצד ראשון.) איני יודע אם זה לענין פתילה, או לענין שמן, או לשניהם. לכאו', שאר השיטות הם בענין שמן, ואז נראה שמדבר בשמן. אבל, יש לדון, שאולי כל אחד הוא למה שייך לו יותר.
מ.
לכאו', כבר אמרו רבנן כן במשנה. לכאו', רבי שמעון שזורי בא למעט שאר שמנים שמנו רבנן. אבל, אין זה מוכרח, שאולי רק דיבר על אלו, וגמרא רק הביא אותו כיון שהוא תנא שמדבר בזה, אף שאינו שיטה אחרת. אבל, לא נראה שיכולים לומר כן, שמיד אחרי כן גמרא מקשה ששני התנאים לא חולקים.
מא.
גמרא מקשה שזה שווה לשיטת תנא קמא. אומר שיש ביניהם דין אם נתערב בהם שמן. עיין בגמרא שאומר שדין של רב ברונא ביניהם. משמע שדינו הוא שם, ושאותו ציור שבו דיבר ר"ב הוא ציור שבו מדבר. אבל, איני יודע אם מוכרח כן. אם נאמר כן, צריך לומר שקרבי דגים שנימוחו שווים לשמן הדג. אפשר שאינם שווים, אלא שגמרא תולה אותם, או שאילו היה פוסל בשמן, מסתמא היה מפני שתלוי בקרבי דגים שנימוחו, ושהם שווים. ותחשב.
מב.
כך פירשו הראשונים. קצת קשה למה, שהרי זה נלמד מגזירה שווה (או גילוי לשון) אהל, והרי בשניהם כתיב לשון אהל. צריך לומר שנלמד מסברה, שלא מסתבר שמה שהוא למעלה ממנו משנה טומאה שבא ממה שהם באהל אחד. אין סברה זו נראה לי כל כך, אבל לכאו' מוכרח. ותחשב עוד.
מג.
יש להעיר שמקצת הדברים שמנה לעיל לפסול הם דברים היוצאים מן העץ. אז, ק"ק למה מנה אותם, ולמה לא כלל אותם כאן. ודע שצריך להגדיר מה בכלל "יוצא מן העץ," שפשוט שאין אומרים ששמן זית יוצא מן העץ, אף שיוצא מן הזית שיוצא מן העץ. אולי נמצא הגדרה שגם יתרץ לקושיה ראשונה שלנו.
מד.
יש לדון אם ממש גזירה שווה היא, שהייתי אומר שהוא רק מפרש מילת “אהל,” שמגיד לנו מה נקרא אהל. אבל, גמרא אומר לשון "גמר אהל אהל ממשכן," שהוא לשון של גזירה שווה. (יש לדון, שאולי לא צריך להיות כן, אלא אולי הוא רק רצה לומר שנלמד מאותו מילה אחרת, ויכול להיות נלמד באופן גזירה שווה או באופן אחר. גם יש להעיר שלפעמים מצאנו שגמ' יאמר דרשה אחת, אף שבאמת נלמד בדרשה אחרת, כמו שמצאנו כעין זה בסופ"ק דביצה, ובסוף זבחים.)
אבל, אפשר שצריך גזירה שווה, כיון שאהל אהל ריבה, כמו שיאמר גמרא לקמן.
נראה שמרש”י על המשנה משמע שהוא רק פירוש. עיין ברש”י בתענית, שקצת משמע שענין גזירה שווה הוא לפרש מילה. אבל, לכאו’ פשוט שלפעמים עושה יותר מזה. (כל אותו רש"י שם מעניין, שהוא הולך על גזירה שווה של אגדה.)
מה.
המשנה יבאר דיני טומאת בגדים. מצאנו בזה מחלקת אמוראים במחלקת תנאים, ואז צריכים סיכום על זה. עיין בסיכום שנכתוב בסוף הספר.
מו.
יש להסתפק למה הוא טהור. אפשר שהוא מפני שאינו בגד עוד, אלא הוא פתילה. כן נראה לי שהוא הפשטות. אבל, גם אפשר שהוא מפני שנמצא שאינו שלש על שלש עוד (שקפל אותו).
מז.
מלשון מאירי משמע שרבי אליעזר סובר שלא נחשב פתילה כיון שלא ידוע שלא יחזיר אותו להיות בגד.
מח.
וא"ת למה אין זה תמיד אוסר הבערה בכלי, שאחרי כן נעשה שבר כלי. עיין בגמ’ שקצת דן בזה, ומשמע שאכן צריך שיוסיף עליו רוב עצים.
מט.
עיין בירושלמי, שגם מצדד שרבי אליעזר אוסר כיון שגורם לו טהרה, ואסור לגרום לכלי טהרה בשבת. יש לדון אם הוא מפני שנחשב שעושה דבר חדש, שעושה את זה לדבר שלא מקבל טומאה, או הוא מפני שעושה תיקון, שהוא טוב שלא מקבל טומאה. ותחשב. שם, דן אם צריך להיות שהוא שלש על שלש מצומצמות, שאז מיד אחרי שמדליק נעשה טהור, או שיכול להיות גם יותר משלש על שלש.
נ.
ירושלמי מצדד שאסור כיון שהוא מטפטף לשם בשבת, ונחשב כמוסיף שמן בשבת. לכאו', רצה לומר שנראה כמוסיף שמן בשבת, וכיון שנראה כמלאכה, אסור לעשות. (יש להעיר שלפי פי' הירושלמי, אין חרס דווקא.) לכאו', זה צריך לבאר גם ציור אחרון שבמשנה. זה מעניין, ששם לא מטפטף, אלא הפתילה הוא בתוך שניהם.
נא.
יש לדון, שאפשר לומר שהוא מותר, ורק חוששים למי שלא מומחה שרואה אותו. אבל, אם אדם שעושה כן אינו חכם מופלג, ולא ילמדו ממנו, ואולי גם אם אינו לפני אחרים, מותר לגמרי. ויש לדון.
נב.
מצאנו שבעה מקורות לזה ביומא (פה:), אבל רק אחד עומד למסקנא:
1. רבי ישמעאל – כתיב, "אם במחתרת ימצא הגנב." זה מלמד לנו שאם אדם בא במחתרת, ולא ידוע אם מכוון להרוג את בעה"ב, יכול בעה"ב להרוג אותו כדי להציל את נפשו.
דורשים מזה קו"ח – ומה זה שספק על ממון בא ספק על נפשות בא – והאיסור שיעבור הוא חמור, ששפיכות דמים מטמא את הארץ וגורם לשכינה שתסתלק מישראל – ניתן להצילו בנפשו, קל וחומר לפקוח נפש שדוחה את השבת.
גמרא דוחה שזה רק יכול ללמד לנו וודאי פ"נ, ולא ספק פ"נ (וכיון שיביא מקור אחר לספק פ"נ שגם מלמד לנו וודאי, מוכרח שאין זה המקור). הרי, אינו ספק אם מי שבא במחתרת מכוון להרוג את בעה"ב, שיש חזקה שבעה"ב מעמיד א"ע על ממונו, ויש חזקה שבא במחתרת מכיר בזה ומוכן להרוג אותו. אז, יש וודאי פ"נ בזה.
1. רבי עקיבא – כתיב, "וכי יזיד איש על רעהו... מעם מזבחי תקחנו למות." מזה דורשים שרק לוקחים אותו "מעם מזבחי," ולא "מעל מזבחי," שאם הוא עובד, לא ממיתים אותו. מדרשה זה יוצא דין אחר, והוא שמה שיש חילוק בין "מעם" ו"מעל" הוא רק להמית אותו, אבל להחיות (להביא אותו להעיד, כדי להחיות על פיו),  שאז מביאים אותו אפילו "מעל מזבחי."
דורשים מזה קל וחומר – מה זה שספק יש ממש בדבריו ספק אין ממש בדבריו – והאיסרו שיעבור הוא חמור, שעבודה דוחה שבת – פיקוח נפשות מתיר, קל וחומר לפקוח נפש שדוחה את השבת.
גמרא דוחה שזה רק יכול ללמד לנו וודאי פ"נ, ולא ספק פ"נ. הרי, קודם שמביאים אותו מן המזבח, מוסרים לו זוג של תלמידי חכמים, לראות אם נפטור על ידי עדותו וטענתו. אז, אינו ספק פיקוח נפש, אלא וודאי.
1. רבי אלעזר אומר שנלמד מקו"ח ממילה. מה מילה שהיא אחד ממאתים וארבעים ושמונה איברים שבאדם דוחה את השבת, קל וחומר לכל גופו (פיקוח נפש, שהוא הצלת כל גופו) שדוחה את השבת.
גמ' דוחה שרק מצאנו וודאי של מילה שדוחה את השבת. אז, אי אפשר ללמוד שספק פ"נ דוחה את השבת מכאן.
1. רבי יוסי ברבי יהודה אומר שנלמד ממה שאחרי שכ', "את שבתותי תשמורו" כתיב "אך," למעט משמירת שבת, לומר שפ"נ דוחה את השבת.
גמרא דוחה שרק יכולים ללמוד מכאן שוודאי פ"נ דוחה את השבת, ולא שספק פ"נ דוחה את השבת.
1. רבי יונתן בן יוסף אומר שנלמד ממש"כ, "כי קודש היא לכם." שבת מסורה בידינו, ולא אותנו מסורים בידה. זאת אומרת שלא צריכים למות עליה.
גמרא דוחה שרק יכולים ללמוד מכאן שוודאי פ"נ דוחה את השבת, ולא שספק פ"נ דוחה את השבת.
1. רבי שמעון בן מנסיא אומר  שנלמד ממש"כ, "ושמרו בני ישראל את השבת." אמרה תורה חלל עליו שבת אחת כדי שישמור שבתות הרבה.
איני יודע אם הדרשה הוא מסברה או אולי ממה שיש לשון רבים על שבת, שכולם שומרים שבת אחת שלו, כיון שמצילים אותו, או מלשון שמירה, שהוא על העתיד. ותחשב.
גמרא דוחה שרק יכולים ללמוד מכאן שוודאי פ"נ דוחה את השבת, ולא שספק פ"נ דוחה את השבת.
1. שמואל אומר שנלמד ממש"כ, "וחי בהם," שמזה דורשים שלא ימות בהם.
גמ' לא דוחה מקור זה, ויכול ללמוד שוודאי פ"נ וספק פ"נ דוחה את השבת.
נג.
זהו ההנחה הפשוטה במסכת שבת. אבל, עיין בכריתות, ששם רש"י מבאר שרבי אליעזר חולק על כלל זה, וסובר שלא צריכים מלאכת מחשבת בשבת.
נד.
כן אומר הרמב"ם. ודע שרמבם אומר כן רק על חולה. צריך ביאור, אז, למה לא חייב על השנים. ותחשב. אבל, ירושלמי מזכיר שיש שגרסו כאן "מותר."
נה.
איני מבין את המציאות כל כך, שהרי, נר הוא הכלי שבו שמים את השמן. אז, איני רואה איך, על ידי כיבוי, הוא חס על הנר, שהנר לא נשתנה מביעור.
אפשר שבריבוי הבערות הנר נעשה יותר מאוס או שנעשה יותר חלש. גם אפשר שכאן מדבר בוואק"ס שחופה את נר, שהוא נתמעט ברוב הבערות. וצ"ב.
נו.
עיין ברש"י, שמשמע שלא צריך זה מעיקר המלאכה, אלא צריך זה כדי שלא יהיה נחשב מקלקל.
יש לדון למה, אז, צריך להיות במקומו. נראה שצריך כן כדי שלא יהיה נחשב שגורם קילקול והנאה, שאולי אז עדיין ייחשב מקלקל, אלא שייחשב כולו ביחד להנאה.
נז.
איני מבין למה על ידי הכיבוי עושה פחם, שלכאו' זה נעשה על ידי הבערה, ורק שחס כאן על הפחם. (אבל, אולי המציאות שלו לא צודק, ואולי צריך גם הכיובי, שמביא אותו קרירות, כדי לעשות אותו לפחם.) אולי כיון שאי אפשר להשתמש בו בלי כיבוי, כמובן, זה נחשב מה שעושה פחם.
נח.
יש לדון אם מתים כיון שלא נזהרים בזה או כיון שעוברים. כמובן, הלשון משמע כראשון, אבל אפשר לדחוק שרצה לומר שכיון שלא נזהרים, לפעמים עוברים, או לדחוק שפירוש של "אינה נזהר" הוא שעוברת.
נט.
עיין בירושלמי שאומר שתנאים אלו חולקים בגירסת המשנה. אינו אומר כן בבבלי, אבל אין הכרח נגד זה מן הבבלי.
ס.
איני מבין את זה כל כך, שלכאו' זה רק מהני לומר שתמות מחמת דם נדה. אבל, לכאו', לא מצוי שזה קורה. אולי מכוון לומר שלכך מתה בשעת לידה, בדווקא, שהיא במקור. אבל, לשון רש"י לא משמע כן, וגם שזה רק מתאים לשיטה של "יולדות," ולא לשיטת של "ילדות" (עיין לקמן).
סא.
מן הגמרא משמע שזהו המסקנא. אבל, איני מבין למה צריך לחזור מן הראשון. כנראה, זה יותר דומה לשאר ציורי המשנה. אבל, איני מבין כל כך למה.
סב.
כן נראה לי, אבל הגמרא לא מבאר כל כך. ע"ש.
סג.
נראה שיש שני דרכים לפרש את זה. יש לדון אם רצה לומר שלכן רק לה יש עונש כזה, או אם רצה לומר שלכן נקט המשנה אותה, אף שנוהג לכל אדם. לא נראה כשני.
סד.
עיין שם, שגם מבאר בזה למה ניתן לה מצוות דם נדה, אבל אני לא כתבתי את זה, שזה כעין טעמא דקרא.
באמת, נראה להוסיף ששני הטעמים שנותן רש"י לא חולקים, שניתן לה מצווה זו כיון שעוסקת בבית, כמו שניתן לה נדה כיון שרק שייך לה, ומה שיש מצווה כזה הוא מפני טעם ראשון שאומר רש"י, כמו שהוא בנדה.
סה.
עיין בסיכום שנכתוב בביאור ביה"ש.
סו.
איני מבין למה זה קלוש, שכל "אולי יבוא לידי...." הוא גם ספק, שאולי לא יבוא לידי כן. צריך לעיין בזה.
סז.
וא"ת אף אם יחם, בהכרח יחם קודם שבת. ויש לומר שכאן רצה לומר שלא יתחיל להטמין, שאולי כשבא להטמין, אז יבין שאינו חם, ומאז יחמם אותו, ואז יעבור, שכבר הוא בין השמשות.
סח.
בכ"מ בעירובין מבואר שחולקים רבנן ורבי אם גזרו על איסורים דרבנן בין השמשות או לא גזרו. כאן, מצאנו שגזרו על מקצת איסורים בין השמשות. יש לדון אם זה שיטה של אחד מהם (ויש לדון איזה אחד) או שהוא שיטה שלישית. ותחשב. רש"י ורע"ב פירשו שתנא זה הוא התנא שסובר שגזרו שבות ביה"ש. אבל, ראיתי שדנים המפרשים בזה.
