** ורבנן –
הלשון ק"ק, שהיה לו לומר "רבנן," ולא "ורבנן," שלא מוסיף על שום דבר.
** היכל -
עיין בבבלי שמצדד כן בשיטת רבי יהודה ובשיטת רבנן בתחילת עירובין. אבל, קשה איך זה יהיה נוגע לסוכה. שם, בעירובין, מובן, שהדיון הוא איזה דבר נחשב פתח (ולא מבטל את המחיצה). אבל, כאן הדיון הוא מה כשר לסוכה, ואין פתח נוגע לנידון זה. ותחשב. אולי ירושלמי סובר שהפסול הוא מפני שהפתח מבטל את המחיצה אם הוא גבוה מעשרים אמה. אם כן, אם אצל הפתח יש עשרים אמה, או אם אין פתח, וכולו מוקף, הסוכה כשרה, לצד זה.
גם אפשר לומר שגמ’ כאן מדבר במחלקת רבי יהודה ורבנן בעירובין (כן נראה מבריי’ של ר"ח שהביאו, שגמ’ בבלי בעירובין מביא אותו בריי’ בענין עירובין), ומובא כאן אגב. עיין בקרבן העדה שפי’ שנחשב סכך כשר אגב שהוא קורה כשרה. אבל, עדיין לא מבאר למה לא יהיה סכך כשר, ולמה צריך אגב כדי להכשיר אותו.
** אמר רבי אבין –
עכשיו, חוזר גמרא מלומר שחולקים אם לדמות לפתח אולם או לפתח היכל. כולי עלמא מודים לדמות אותו לפתח היכל, אבל רבי יהודה סובר שנחשב כפתח היכל, כיון שרואים אותו כאילו נעשה למטה. גם יש לומר שכיון שרבי יהודה סובר כן, לא לומד אותו מפתח היכל, שאין הענין שכל מה שהוא בתוך עשרים נחשב פתח, אלא שזה נראה כבתוך עשרים, כיון שמשפילים, אלא פתח הוא כל זמן שיש דבר על גבו להשפיל, והרי יש. במילים אחרים, כיון שסובר רבי יהודה זה, אין עשרים אמה אומר כלום, ואין לימוד מהיכל. ותחשב.
** מבוי -
ירושלמי מקשה שיש חילוקי דין בין מבוי לסוכה. לכאו’, רק מקשה על מש"א ששיטת רבנן ושיטת רבי יהודה במבוי וסוכה תלויים זה בזה. מקשה שכיון שמצאנו חילוקים, לא צריך להיות שתלויים זה בזה.
על פי מש"כ קרבן העדה, יכולים לפרש ביותר דקדוק. קה"ע סובר שגמ’ מנסה לבאר למה מכשיר רבי יהודה, ואומר שהוא אגב מה שהוא כשר למבוי. (קשה, שזה דין דאו’, וזה דין דרבנן. אבל, כן משמע מד"ה היא דעתיה. צריך לומר שכיון שחידשו רבנן ההלכה, בא לסכך גבוהה חשיבות.) אם כן, קושיית גמ’ יכול להיות שמוכיח שאין אומרים שמגו שכשר לזה כשר לזה, שמצאנו חילוקים, וגם יכול להיות שמקשה איך נאמר מגו ביניהם, כיון שיש חילוקים ביניהם. (אז, אין זה ההוכחה, אלא המניעה עצמה.)
** למעלה מכ’ לדפנות -
נמצא שלא פוסל כשהוא למעלה מעשרים, כל זמן שאין המחיצות הולכות כל הדרך עד הסכך, אלא פוסל כל זמן שיש עשרים אמות בין דפנות לסכך. נמצא, אז – ואולי לכן הקשה עליו – שתמיד אינו פסול כשהוא גבוה עשרים אמות, שבוודאי יש מחיצות (שאם לא כן, יש פסול אחר), ובוודאי הם עשרה טפחים, ואז בוודאי הסכך הוא בתוך עשרים אמה. ותחשב.
** והרי אכסדרה –
יש לדון למה לא דחה שאף שאין לה מחיצות ממש בכל ארבע רוחות, עדיין יש לו מה שנחשב כמחיצות בכל ארבע רוחות. אבל, יש סוכה שאין לה דבר שנחשב כמחיצות בכל ארבע הצדדים.
** מגופף –
אם כן, לכאו' אם הסוכה מגופפת, כשרה למעלה מעשרים אמה. נראה שהיה אפשר להק' כן (שתנא היה לו לפרש אותו), אבל יש לו קושיה יותר טובה.
** בצילן של דפנות –
רצה לומר, מונים מאיפה שהוא יושב. אם כן, גם לענין עשרים אמה, נמנה מאיפה שהוא יושב. יש להעיר שהיה לו לפשוט כן ג"כ מן הטעם שמזכיר גמ' לעיל ג"כ.
** מחיצה –
נראה שר"ל שיכול להיות למעלה מן המים או במים. אם הוא למעלה, עדיין צריך שחלק מן המחיצה תגע במים, כדי לראות איזה מן המים הוא במחיצה. אבל, עכ"פ מספיק מחיצה שהוא רק עשרה טפחים ממקומו, אף שאינו עשרה טפחים מן הרשות. וא,ת למה מהני עשרה טפחים שאינו אצלו, אלא שאצל הרשות. ויש לומר שכיון שדן דין הנוהג ברשות, כמו שמקומו חשוב, גם מקום הרשות חשוב. ותחשב.
** כרמלית –
נמצא שדין דאו' של עשה יותר חמור מדרבנן של חיוב כרת. עיין לקמן בגמ', שאולי לא משמע כן.
** ואם לאו ממעטים בה לכשר –
לכאו', רצה לומר שלא ממעטים אותה, ואז הוא כשר. אבל, הלשון קשה. עיין בקרבן העדה, שלא קשה לגי' ראשון שלו. גם מביא גי' זו, ואיני יודע מה שמפרש בו. אולי ר"ל שממעטים את הדבר הניתן שם. אם כן "ממעטים בה" קאי על דברים חלוקים.
** ואם לאו-
קשה למה לא ממעט אותה, שאי אפשר לדור שם, כיון שיש דברים שיושבים שם. צריך לומר שכיון שלא מבטל אותם, ואינם נחשבים כחלק מן הסכך, אף שעכשיו קשה לשבת שם, הסוכה עצמה יש בה ישיבה. מה שקשה לשבת שם אינה פסול בישיבתו, אלא בסוכה, ואז כיון לסוכה פסול זה, כשר.
** כשם שאמרו –
וא"ת אינו כשם, אלא הוא שונה. וי"ל שענין כשר לסכך שווה, שהוא ישאיר אותו שם, כיון שהוא כשר לסכך. יש לדון, שכנראה לא דנים בכשרות הסוכה כאן, שאל"ה נאמר שכל דבר שיפסל סוכה הוא יוציא. אלא, נראה שר"ל שכמו שדבר יכול להיות בטל לסכך, כך דבר יכול להיות בטל למטה. ותחשב.
** כל פני –
יש לדון מה נוקטים את המיעוט. י"ל שתפסת מועט תפסת. יש לדון, שזה מכניס יותר דברים לכלל מחיצה, ותפסת מרובה לא תפסת.
** חמשה –
יש לדון למה לא לומדים משם, למעשה. אולי לא דורשים ג"ש, או אולי סוברים שה' דיבר לו מעל הכפורת עמעל כמה טפחים, ולא ממש מעליו.
** עגלות –
קשה מהי"ת שעגלות היו רשות לעצמם.
** אילו חור –
כנראה, מקשה שכיון שהיה עליהם כיסוי, נחשבים כחורי רה"ר, ולא היו רשות לעצמם. איני מבין למה זה יהיה כן. ותחשב.
** אילין רבנן –
נבאר את זה כקה"ע. קה"ע פי' שרבי יהודה מחייב אף בלי ד"א וד"מ. מחייב אותו בסוכה ומחייב אותו במזוזה. רבנן לא מודים שיש שום חיוב מזוזה, שסוברים שלא צ"ל קבע. צ"ב מהי"ת משיטתם שלא צ"ל קבע, שאולי סוברים שבאחד מאלו הוא קבע, כמו שר"י סובר שבלי אחד מאלו קבע.
** מדבריהם –
יש לדון אם סובר שהוא מדרבנן (ויש לדון למה גזרו) או שסובר שהוא הל"מ (ואז נמצא חי' במה ש"מדבריהם" רצה לומר הל"מ, ובמה שמחמירים בהל"מ).
** אלו שלא כנגד אלו –
איני יודע מה זה אומר, שהרי הם באמצע, ואין אחד נוגע בחבירו. אולי רוצה שארבע אמות עצמם הם שלא כנגד זה, ולא שורה אחת. דחוק.
** אותה של טפח –
עיין בקרבן העדה. יש לדון אם גם על זה קאי מה שאומר גמ' שצריך להיות בתוך שלש טפחים לכותל.
** ונטל עאים –
רבי יוחנן מביא ראיה ממה שסתם אותו, ולא התיר אותו בצורת הפתח, שאין צורת הפתח מהני ביותר מעשר. ויש לדון מי אמר כזה, שאם אינו רבי יוחנן, אלא רבי יהושע בן קרחה או רבי יוחנן בן נורי, אז אמרו כן בפי' (שהוא עושה כן כיון שאין מתיר בתוך עשרה טפחים). ויש לדון, שאולי רק אומרים שיותר מעשר אמות לא נקרא פתח, ולא מדברים בצורת הפתח בכלל. ותחשב.
** דיו בקשר אחד –
צריך ביאור כמה גבוה צ"ל כדי להיות צוה"פ, שיש לומר ששם היו רק עמודים גבוהים עשרה טפחים.
** יאות –
איני מבין איך מביא ראיה משם, ולמה נניח כלל שהוא למעלה. יותר מזה, לכאו' אלו שבאמצע אינם למעלה. יותר מזה, מקשה למה לא עשה תקנה יותר קל, והוא שישים אותה בצד. אף אם שם מדובר ששם אותה למעלה, יש להוכיח ממה שלא אומר שישים מן הצד, שאז רק צריך אחד.
** מגופפת –
נמצא שאין זה צורת הפתח, אלא ארבע צורות הפתח.
** מגופפת –
קשה, שבקורה יש ממש מחיצות בכל ארבע המחיצות, וזה יותר טוב מפאה. צריך לומר שאין הענין שחוץ מזה יש מחיצות טובות, אלא כיון שהוא עושה ארבע המחיצות, כוחו גדול, עד שיכול להיות למעלה מעשרים אמה. ותחשב.
** שבת החמורה –
יש לדון אם גם מחמיר לענין מבוי, שהוא רק מדרבנן, כיון שהוא מאיסור כרת. אם מחמיר, נמצא שדרבנן של איסור כרת יותר חמור מדאו’ של איסור עשה.
** לא רבי יוחנן בן נורי -
צריך לעיין, שלעיל גמ’ הביא סיפור עם רבי יוחנן בן נורי, ושם אף לענין כלאים החמיר, שאמר שצריך עאים, ולא מהני צורת הפתח. ותחשב.
** משלשה ועד ארבעה… -
בכל זה, לכאו’ המדה שמזכיר הוא מידה של העומד וגם מידה של הפרוץ. אז, ציור ראשון הוא כשהעומד פחות משלש והפירצה פחות משלש. כן יוצא מוכרח מן הגמרא. אבל, אז, ק"ק למה מביא ראיה מקנים, ולא הקשה סתירה ממה שרק חלק ר"ח בבין שלש לארבע, ולא בפחות משלש. ותחשב.
** מכל מקום -
לכאו’, לא מצאנו חולק על זה. אז, נראה שבא לפרש, לומר שכשאומרים, “מותר" רצה לומר שמותר אף כנגד הפרוץ.
** על פני כולה -
מקרבן העדה, יוצא שצריך שני דברים (וכנראה, סובר ששניהם נלמדים מלשון זה):
1. צריך שיוצא על פני כולו. יש לדון אם זה בא ממעט כל מה שלא הולך על פני כולו או שבא למעט כל מה שלא הולך בגודל סוכה (ומדבר בסוכה הכי מועט). ותחשב. הלשון נראה כראשון.
2. צריך להיות יוצא מן הצד הפתוח, ולא על מחיצה. הענין הוא, לכאו’, שכיון שיוצא מן המחיצה, אז יש מחיצה בינו לסוכה, ולא נצטרף לסוכה. ותחשב.
** שלא כנגד הדופן -
איני מבין כל כך מה זה אומר. נראה שהוא שווה ליוצא מן המחיצה שפסל קרבן העדה לעיל (ולאיזה סיבה, פי’ כרבי יסא לעיל). אז, לפי לשון הגמ’, נפרש כביאור חדש, והוא שאז אין שום מחיצות למה שיוצא מן הכותל, שהמחיצה היחידי שיש לו נעשה לצדו האחר. ותחשב.
** חמתה מרובה -
לכאו’, רצה לומר שהקולא הוא שיכול לצרף לסוכה לעשות שאין חמתה מרובה מצילתה. ותחשב.
** שדרכו לפסע -
עיין במה שפי’ קרבן העדה. וא"ת עדיין יהיה כשר לתחילת החג. ויש לומר שנקט "צילתה מרובה" כדי שיהיה דבר שכשר לכל החג. אולי אף מכוו לעצה טובה, לומר לך לנקוט דבר כזה, שנשאר בכשרותו לכל החג. גם אפשר לפרש שכיון שעומד שלא להיות סכך, לא נחשב סכך כשר. אבל, סתימות קה"ע לא משמע כן בכלל. ותחשב.
** הישנה –
גמ’ מבאר שחולקים ב"ש וב"ה אם צריך כוונה לסוכה של מצווה. אבל, תוך שלושים יום, כיון ששואלים ודורשים בסוכה, בוודאי עשה אותו לשם החג. יש לדון מה הדין אם עשה אותו סתם אז, אם נאמר שענין של שלושים יום קודם הוא רק גילוי שמכוון לו, והרי כאן לא כיוון, או שכיון שהוא בתוך שלושים יום, עומד לכך, וסתם בני אדם כן, ואז לא צריך מחשבה.
** על פני כולה -
יש לדון אם צריך כן גם למד"א שצריך טפח. אם לא צריך כן, יש לדון כמה אורך צריך. אולי צריך ארי"א של טפח, ואז הוא טפח על טפח. לזה, יש לדון אם יכול להיות חצי טפח על טפחיים.
** דבר בריא -
אז, יש נ"מ לב"ה במה שצריך כוונה, ויש נפ"מ לב"ש במה שאסור לאכול, ולא רק לא כשר לקיום המצווה.
** שלושים יום -
יש לדון איזה מחשבה צריכים – אם הוא מחשבה שאדם מקיים מצוה זו או שהוא מחשבה שעושה אותו לחג. ותחשב.
** החתחון אין חמתו מרובה –
קשה, שכיון שתחתון אין חמתו מרובה מצילתו, לא צריך צירוף לעשות שצילתו מרובה מחמתו. אולי צריך לשנות את הגי'. גם יש לומר שכאן שווה ושווה הוא. עיין לקמן, שידון גמ' בדין שווה בשווה. גם צריך ביאור למה נקט ציור של שווה בשווה. אולי רק שם יכולים לדון בזה, שאם מועט הוא, כבר בטל, ולא יהני צירוף. דחוק, שלא מהני צירוף בעליון. ותחשב. שו"ר שקרבן העדה משנה את הגי'.
גם עיין בל"א של קרבן העדה. לפי זה, יוצא שאם גורס כמונו, פוסל גם בחמתה מרובה מצילתה. אבל, הגי' שלנו לא מובן לפירושו, שלמה לי שבצירוף שלהם יש צילתה מרובה מחמתה. אז, בוודאי משנה איזה דבר.
** דיורים ממש –
יש לדון אם מספיק שיהיו שם בחג, או שרק כשהם ממש שם התחתון נפסל.
** פחותה מכה –
לכאו', הענין הוא שבפחותה מזה, אינו כל כך גדול, ולא מצוי שאדם נותן אותו שם אחרי עבודתו שלא לשם סוכה, ואז אין כ"כ סיבה לגזור.
** הדא דאת אמר-
עיין בקרבן העדה. יוצא שלאורך, שפוסל, רצה לומר שהוא פאראלאל לשתי המחיצות, שאז אין מקום שיש לו שלש מחיצות, בלי קורה. אבל, אם הוא לרוחב, שהוא פאראלאל לצד הפתוח, יש מקום (לפנים מן הקורה) שיש בו שלש דפנות, ובאותו מקום כוע"מ שכשר.
** רבי זריקן –
איני מבין כל כך מה אומר. נראה שחולק על שניהם ואומר שבין באורך בין ברוחב פוסל, שאף שיש משם ולכותל סוכה כשרה, הרי כולו סוכה אחת, ואותה סוכה פסולה. שוב ראיתי שמפרשים שר"ל שלפי רבי יוחנן, קטע זה רק לפי רבי יהודה, שרק הוא מכשיר בכל אופן. כן נראה מקרבן העדה.
** מתניתא –
איני מבין קושיה זו. ראיתי שיש שמשנים לומר שמקשה על שמואל, והוא שכאן יש רק שלשה טפחים, שאינו הכשר סוכה, חוץ מן הקורה. אז, תמיד הוא כלאורך. אם כן, כדי להכשיר, צריך לומר כרבי יוחנן. ותחשב. (אבל, קשה, שאולי סובר שמשנה שלנו כרבי מאיר והבריי' כרבי יהודה. אולי ידוע שבא לפרש שיטת רבי יהודה. אבל, קשה, שלא משמע כן בגמ', שמשמע שרק לרבי יוחנן הפוסל במשנה פוסל כאן. יש לדון, שאולי קאי על שניהם.)
** מה נפק –
יש עוד נפ"מ פשוט, והוא אם טלטל אותו, ועשה שאינו "תעשה ולא מן העשוי," אם הוכשר על ידי זה.
** רבי יוחנן –
איני מבין איך דברי רבי יוחנן הולכים לשיטתם, שלהיפך נראה שסותרים זה על זה, שאומר שרבי יוסי, שאמר שרק אמר כן לענין סוכה, אומר דבר שווה לרבי יהודה, שאומר כן לשבת ג"כ. ותחשב. שוב ראיתי שקרבן העדה גרס כאן רבי יוסי בר"ח, ולא רבי יוחנן. אז, הכל מיושב.
** ותלו –
צריך ביאור איך היה מותר להם להוציא אותם ולתלות אותם בשבת. אולי ר"ל שכבר תלו אותם לפני שבת (שידעו שיבוא).
** טיט הנרוק יוכיח -
זה לא מוכיח שלא כשר, אלא מוכיח שלא צריך להיות שכשר, שיכול להיות שאף שמצטרף לא כשר.
** שאם היתה –
איני מבין את זה. מה לי אם הסוכה היא על אבנים טפח, שבין כך ובין כך האהל יהיה על יותר מטפח, שהוא על כל הסוכה. ותחשב. גם איני מבין מהו "... פותח טפח." צריך לעיין בזה.
** אבל פורס –
רואים מגמ' זה ששם יש עליו שיעור אוהל, שאל"ה זהו החילוק. מה שהוא משופע, שנתלה משני צדדים גם לא מחלק, שלא מחלק בין מטה לו בזה. אלא, צריך לומר שיש סיבה אחרת שמתרת את זה, שכנראה כיון שהוא עומד על שני עמודים נשחב הכל בטל לו, כסדין שלו. וצריך לעיין.
** דירוין-
שבוודאי יש ישן על גביו, שאל"ה הוא יישן במטה.
** המעשה קדם-
איני יודע מהו בריי' זה, אבל כנראה אומר שאין לימוד תורה פוטר אדם ממצות.
** מדובללת –
נמצא שיש שני פירושים במשנה:
1. בין סוכה מדובללת בין סוכה שצילתה מרובה מחמתה כשרים.
2. סוכה מדוללת שצילתה מרובה מחמתה כשרה.
קשה למה אין פירוש שלישי:
1. סוכה מדובללת שצילתה מרובה מחמתה כשרה.
במילים אחרים, כנראה פשוט לגמרא שסוכה מדובללת שאין צילתה מרובה מחמתה (סוכה שמחמת שסכך שלה נכנס ויורד מכניס חמה) כשר. קשה מהיכי תיתי. ותחשב.
** הדא אמרה –
גמרא לומר מ"אף על פי" שלכתחילה יראה את הכוכבים. קצת קשה ל"ל מפרש שאמר לשון זה לאפוקי משיטת בית שמאי, שבית שמאי סובר (ע' בבבלי) שאם לא נראים כוכבי חמה, הסוכה פסולה. אפשר לפרש שכוונת גמ' ליתן שני מהלכים – אולי כוכבים ר"ל כוכבים ממש, ואז יכולים להוכיח שלכתחילה נראה את הכוכבים, ואולי כוכבים ר"ל כוכבי חמה, ואז בא לאפוקי משיטת בית שמאי. אבל, סתימות הגמרא לא משמע כן.
יותר נראה לומר שלא היה משנה אומר " אף על פי" לאפוקי משיטת בית שמאי, שהיה רק אומר כנגד שיטת בית שמאי. (יש להעיר שלקמן נראה שלא רוצה הירושלמי לעשות שמשנה יסתום נגד תנא אחד. אז, אולי לא כל כך קשה שיאמר "אף על פי" כשסותם נגדו. אבל, עדיין אפשר שנגד בית שמאי לא צריך לומר "אף על פי." ותחשב.)
** אין עולים –
יש לדון למה לא:
1. כיון שהוא נשען על האילן. אז, צריך לומר שתחתון הסוכה נשען על האילן. אבל, לא משמע כן כלל מן המשנה, שמשמע שהדפנות סומכים על האילן. אם התחתון נשען על האילן, איני יודע איך לקרוא את המשנה. ותחשב.
2. כיון שהדפנות הם על הסוכה, והוא משתמש בדפנות, כיון שבהם מכשיר את הסוכה, נמצא שמשתש בסוכה. וא"ת איך זה שונה מעושה סוכה בין האילנות, שהוא שיכול לעשות סוכה שדפנות שלו הם האילנות:
  1. אולי זה לא מכשיר בי"ט, ובאמת אסור בי"ט. זה רק אומר שנחשב סוכה כשרה. אבל, אז יש לדון מהו ההו"א. אולי הו"א שיש פסול "תעשה ולא מן העשוי" על מחיצות כזה. ותחשב.
  2. אולי זה מתיר כשיש מחיצות אחרות. הו"א שאף שיש מחיצות אחרות, כיון שיש מחיצות מאילן שמכשירים, משתמש בהם, אף  שאינו צריך להם להכשיר את הסוכה. ותחשב.
  3. אולי אין כל תשמיש אסור באילן, אלא רק סמיכה עליו (כיון שזה עיקר תשמיש האילן). אז, אם הוא הדופן, אין איסור. אבל, אם הדופן סמוך עליו, יש איסור. זה קצת נראה כחוכא ואתלולא. ותחשב.
** מחלקת –
יש לדון אם לא רוצה שיהיה סתם משנה שלא מזכיר מחלקת (אבל, זה קשה, שיש הרבה סתמי משניות) או שלא רוצה שיהיה סתם משנה נגד ראב"ע (ויש לדון למה לא, שר"ע הוא סתימתאה, כמו שאומר בבלי בתחילת מגילה). ותחשב.
** דבר אחד –
יש לחלק בין שיטות אלו, שיש שמדברים בספינה, לומר שלא נחשב שמקומו קבוע, ויש שמדברים על דבר שעל ספינה, לומר שאין מקומו קבוע. אפשר שאיה"נ קל לחלק, אלא ידע שכולם סוברים דבר שווה, ושמפני זה פסוק דברים אלו. דחוק. יותר נראה ומר שר"ל שאומרים דברים דומים, אף שאינם ממש שווים.
** ומותר לטלטלו –
קשה, שאולי אסור מדרבנן לטלטל אותו, כיון שמשתש באילן, ועדיין העירוב כשר, כיון שהוא שבות בבין השמשות, כמו שאמר גמ' מיד לעיל. ותחשב. אולי מניח גמ' שרק נתיר שבות אחת, ולא נתיר שתי שבותים. דחוק. ותחשב.
** למעלה –
נראה שמסתבר שלא מדובר בשנשען ממש על ראש אילן, אלא שיש Y באילן, ונשען באמצע, בין שני הראשים. ותחשב.
** לילות כימים –
לכאו', גם רצה לומר ששם גם עשה כל הימים כיום ראשון. כמו כן, כאן, עושה כל הימים כיום ראשון. אז, כיון שחייב בלילה ראשון, שלומדים מפסח, לומדים גם ליום שלו וגם לשאר ימים. ותחשב.
** שאר הימים רשות –
יש לדון אם רבנן ר"ל שאין מקור ששאר הימים יהיו חובה, וממילא הם רשות, כמו ששם, כיון שאין מקור, הם רשות, או שר"ל שכמו ששם הם רשות, כיון שאין מקור שיהיו חובה, יש מקור שכאן יהיו רשות. נראה שלא יכולים לומר כצד שני, שאם יש מקור כאן שיהיו חובה, בוודאי ידחה לימוד משם, שילמד שכאן הוא חובה, ויחזור וילמד באותו ג"ש לשם לומר שהוא חובה. ויש לדון, שכיון שהג"ש הוא על טו', אולי לא מלמד דינים על שאר הימים. ויל"ד, שגופא אומרים בצד זה שלומדים מה שאין חיוב נוהג בשאר ימים מג"ש זה. ויש לומר שזה דין של חיוב טו', שהוא חיוב מיוחד. אבל, אז יכולים לומר כן בלימוד חובה בשאר ימים, לומר שאינו חיוב מיוחד. ויש לומר שעדיין זה לא ילמד לנו הדין הברור, שלדין הברור צריכים לדעת מתי בשאר הימים נוהג, וזה בוודאי אינו דין של טו'. אז, לא יכולים ללמד אותו מחמת הג"ש. ותחשב.
** שבעה –
וא"ת איך (בהו"א שמחייב שאוכל כל שבעה) מבאר את המשנה. ויש לומר שאומרים שלענין לילות, רק חייב בראשון. אבל, עדיין צריך ביאור מהי"ת לשיטה כזה. ונראה שלומדים משני המקורות, ואז מרבים וממעטים. ותחשב.
** בשלא נתן דעתו –
עיין בביאור קה"ע. נמצא שלא תולה באם עשה, אלא אם כוון. לכאו', באמת תלוי באם עשה, אלא שמחדש כאן שאם לא כיוון, לא עשה. הרי, צריך לומר שסובר שמצוות צריכות כוונה. אבל, גם יכולים לדחות שסובר שסבוכה צריכים כוונה, כמו שכ' הב"ח הידוע.
** משלים –
וא"ת למה גמ' מחשיב את זה לסתירה, שיש לומר שצריך להשלים ולאכול שלש סעודות ביום. ויש לומר שסעודה זו שמוסיף לא נחשב כסעודה שחסר, שנאכל ביום שכבר נאכל שתי הסעודות. ותחשב.
גם היה אפשר לומר שקושיית הגמ' אינו כמו שפי' קה"ע, אלא הוא שמשמע שרק ראשונים צריכים השלמה, ולא אחרונים, שמשמע שאין אחרונים חובה. ותחשב.
** מקדימים –
יש לדון אם ר"ל שהיו שוהים לב"ש לדבר או שהיו שונים דברי ב"ש ראשון כשהיו שונים את המחלקת. מהמשך הגמ', ומביאור קה"ע, נראה כשני.
** זקני –
נמצא שבמקום שב"ה הקדימו לב"ש, הוצרכו לחזור בהם והלכה כב"ש. ויש לדון, שלכאו' זה מגלה על שאר המקומות שבית הלל תמיד הקדימו דבר ב"ש לדבריהם. ותחשב.
** אר"ל –
יש לדון אם אומר שמקור שלו מסברה או שכיון שהוא פסול, מבאר כמה רע הוא. וא"ת למה לא יהיה סברה זו מקור לו. ויש לומר שזה רק מורה שיש בו רע. אבל, אפשר שיש בו ג"כ טוב (שהרי, יותר טוב להחזיר גזילה משלא להחזיר). גם יש לומר שלא פשוט שנחשב זה דבר שגזל מהקב"ה (עיין לקמן). גם יש לומר שלא פשוט שהוא מוסר אותו לה'. אפשר לומר שעיקר המצווה הוא לעשות מעשה עם החפץ. אז, אף אם החפץ הוא של איסור, המצווה הוא במעשה, ואין המעשה גזולה. ותחשב.
** משלו –
לכאו', אין המשל נכון, שאינו שלו, אלא של חברו. אפשר לומר שהענין הוא רק שמכוון לרצות את פני האדון בדבר שמראה שהוא עשה רע. בציור של אדון, כיון שאין אדון מקפיד כל כך אם גוזל מאדם אחר, צריך להיות שגזל ממנו. אבל, הקב"ה מקפיד שלא נגזול מאף אחד, ואז יהיה כן גם אם אינו של ה', אלא של אחר.
גם יש לומר שגוזל מה', כיון שכל דבר הוא של ה', אלא שיש לנו רשות להשתמש בו. אז, כיון שאין לו רשות להשתמש בו, נמצא שגוזל מה'. גם יש לומר שנעשה של ה' אחרי הגזילה, שאין מי שיש לו הזכות והרשות חוץ מה'. ותחשב. יש להעיר שאז לא גזל מה', אלא שנותן לו מה שהוא כבר שלו. ותחשב.
** יום תרועה –
בפשטות, אומר שהפסול אינו משום שכתותי מכתת שיעורא, אלא מפני שאינו שלו. אז, אומר שרק בלולב שכ', "לכם" צריך שיהיה שלו. אבל, בשופר, לא צריך להיות שלו.
יש לדון אם הפסוק שמביא רק מורה שאין מקור שצריך להיות שלו, שאף כשכ', "לכם," לא מדבר על חפץ המצווה, או שהפסוק שמביא מורה שאצ"ל שלו, שכיון שכ', "לכם" בדבר שלא יכול לללמד שצריך להיות שלו, מכוון להורות שאין לומר שהחפץ צריך להיות שלו. ותחשב.
עיין בקרבן העדה שכ' שהדרשה הוא מ"תהיה" שמרבה אף אם אינו שלו. זה מחודש.
אם יש מפסוק זה ריבוי, צריך ביאור מהו הצד לומר שצריך להיות שלו בשופר. לכאו,' צריך לומר שהוא סברה (וא"ת אם כן למה צריך קרא בלולב. וי"ל שהפסוק מלמד סברה זו. גי"ל שאחרי שנדחה בשופר, צריך מקור מפסוק.), כמו שפירשנו לעיל (בר"ל).
הנחנו שהפסול הוא מפני שאינו שלו. אבל, אפשר לפרש שהפסול הוא שכתותי מכתת שיעורא. אז, לכאו', צריך לבאר הריבוי כמו שכ' קרבן העדה. אבל, קצת קשה מה כוונת הקרא שמביא ללולב, שאין זה המקור שצריך שיעור. ותחשב.
** בקולו –
זה אומר סברה, וזה אומר קרא. יש לדון אם חולקים, או שזה מבאר את זה. ותחשב.
** קרקע –
קשה, שקרקע לא נגזלת, ובוודאי לא קונה בשינוי.
** קול –
לכאו', יכולים להוכיח מזה שמצוות תקיעת שופר אינו לתקוע אלא לשמוע. קל לדחות שהמצווה הוא לברוא את הקול, ולא לתקוע בשופר.
** מאן שרא –
אין הדיוק כל כך פשוט לי. קרבן העדה פי' שהדיוק הוא ממה שרק אמר לו כן, ולא אמר לו שלא יצא מצוות סוכה. וא"ת אולי כיוון לומר לו, "מי נתן לך רשות לבנות כאן – וממילא אין אתה יוצא." ויש לומר שלא ידע סתם אדם שכיון שאין לו רשות לבנות שם לא יצא מצוות סוכה. אז, היה לו לפרש לו נקודה זו, אילו היה נכון. ותחשב.
** לא המתים –
זה מקור מעניין. אפשר לומר שחלק מענין של הארבע מינים הוא להורות שאף המינים מודים לה'. (קרבן העדה כ' שזה פסול בהדר; אז, צריך לומר שלהורות זה הוא ענין של הדר.) צריך לחשוב על זה. גם יש לומר שזה רק סימן לפסולם, אבל אינו, בכלל, לסיבה לפסול. ותחשב.
** בשאר מינים –
רצה לומר, ממה שהכשיר בשנים קטומים, צריך לומר שסובר שרק צריך אחד, אלא שיש להוסיף שאר להיות הדר. אז, אף אם הם קטומים, לא פסול, שלא צ"ל שם (ואף אם הם קטומים, מוסיפים קצת הידור). אז, מקשה למה לא נאמר כן בשאר מינים, שיוסיף הידור על ידי הוספת המין.
דוחה גמ' שסובר שיוצא בקטום, ולא שצריך אחד. יכולים להוכיח כן ממה שר"ט אומר שמהני שלש קטומים, שהרי בוודאי סובר שצריך עכ"פ הדס אחד. אלא, צ"ל שקטום כשר. וא"ת ממ"נ, אם קטם לא כשר, נמצא שצריך רק אחד, ואם קטם הדור, קשה למה לא יהיו כולם קטומים. צריך לומר שצריך אותה דרגה של הידור שבא כשאחד מהם שלם ושאר קטומים. אבל, ק"ק, שמגמ' לקמן משמע שזה פחות הידור. (באמת, אז אפשר לקרוא שר"ל שאף זה כשר. אבל, לא נראה כן.)
כשגמ' מוכיח מלשון "אפילו," נראה שכוונת גמ' הוא לומר שכמו שר"ט בוודאי סובר שקטום כשר, כך סובר ר"י, שר"ט מוסיף על ר"י, וסובר בעיקר כמותו. ודחוק. ותחשב.
** לא שמיעא –
יש לדון למה אין חשבון שלו נכון:
1. אולי מוכיח נגד רבי טרפון מסתם זה. דחוק שנסמוך על בריי' סתם, לקבוע שלא כרבי טרפון.
2. אולי סובר שצריך להיות שהיה הדר, אלא שנקטם, ולא רק שמינו הדר.
3. אף ר"ט מודה שלכתחילה צריך להיות שלא קטום, שזה יותר הדר.
** עצו הדר –
יש לדון מה עושה עץ הדר:
1. נראה יפה.
2. יש לו טעם טוב.
3. יש לו טעם הדומה לפריו.
4. הקשיב למש"א ה' כשציווה שיהיה טעם עץ ופרי שווה. קה"ע משמע כצד זה.
** בית שמאי אומרים –
יש לדון אם בית שמאי ובית הלל חולקים במנהג או רק בדין. ותחשב.
** שופר –
הציור קצת מוזר,  שצריך ביאור למה הוא הולך בדרך בראש השנה.
** תמן תנינן –
יש לדון אם גמ' סובר ששתי השאלות תלויים זה בזה (ולכן הביא אותם ביחד) או שהם רק שאלות דומות (ולכן הביא אותם ביחד). ותחשב.
** בשגזלן -
נמצא שיש ענין של שינוי בדבר של עבודה זרה, שאחר שינוי נעשה שלו. צריך לעיין בזה, שלא חשבתי שזה נכון. ותחשב.
** אנסים –
באר קה"ע שסובר שאין הפקר כשלא רוצה, אלא שנאנס. יש לדון מה הכוונה שנאנס:
1. אפשר לומר שהוא שלא בחר להפקיר שהיה חייב להפקיר, שרבנן חייבו אותו.
2. אפשר לומר שהוא שלא רצה אותו מצב שגרם שיפקיר אותו, שלא רצה שעניים יקחו אותו. צריך להגדיר מתי אומרים זה, שברוב פעמים לא רוצים אדם את המצב שמביא לידי הפרק. (בפרט, למד"א שיאוש מהני מטעם הפקר, יל"ד ל"ל אומרים כן. י"ל שיאוש רק עושה כן כיון שאינו ברשות שלו. ותחשב.)
** טעמא טעונא –
איני יודע מהו פירוש מילים אלו. נראה שרצה לומר שהוא צריך טעם לדינים אלו, שהוא לא שמע אותם, ולכן לא יקבל אותם בלי טעם.
** והושע –
צריך ביאור איך לקרוא אותו. נראה שהוא בשורו"ק בה"ה וו"י, ופתח בשי"ן, שאז אומר שבאה לו ישועה. ותחשב.
** הוצאתך –
צריך ביאור איך לקרוא אותו. לולי לשון הדרשה, הייתי אומר שאין דרך אחר לקרוא אותו, אלא שכיון שנקרא חסר, מראה חסרון, כביכול, בה', שהיה במצב חסר, שהיה בגלות. אבל, לשון גמ', שמשמע שיש דרך אחר לקרוא אותו, לא משמע כן.
** לא אמרו אלא-
לכאו', זה נגד מה שפי' קה"ע במשנה, שלקה"ע יש לומר שרק מקטנים יכולים לגזול, שרק מהם גזילה מדרבנן.
נראה שבוודאי היה מותר לגזול מגדולים, שמסתמא מוחלים, כיון שהמנהג כן. (וא"ת אולי לא היה המנהג כן. נראה שמניח שלולי איסור, מסתבר שכמו שנוהגים בזה כך ינהגו בזה.)
זה מניח שמה שמותר לאכול של קטנים הוא מפני שלא הוקצה כ"כ למצווה, שרק הוקצה למצוות קטן, שאינה מצווה מדאו'. אבל, לולי זה, היה אפשר לפרש שגמ' אומר שתינוקות היו אוכלים אתרוגיהם. לא היה להם איסור מוקצה, כיון שהיו תינוקות. אבל, יש לדון, שמדין חינוך, יהיה להם מצווה (כמו שיש להם מצוות ארבע מינים מדין חינוך). ותחשב.
** מלמד שאדם חייב –
נראה שההו"א לחלק הוא שיש שמחה מיוחדת בחג, וזה לא נובע עד שמיני עצרת, ולכן אין דיני שמחה שבו כ"כ חמורים. ותחשב.
** ששחטן קודם לרגל –
צריך ביאור למה לא ייצא באלו.
** בכהנים –
יש להקשות מקה"ע ד"ה ולילו (שצידד שלא מזכיר הלל של ערב פסח, כיוןש הוא רק של לויים). ויש לומר שכאן בדר"כ גם שאר בני אדם מקיימים אותו שמונה ימים. גם יש לומר שכאן יש סיבה לכ"ע בשמונה ימים, אלא שיש דחייה. שם, אף אין סיבה לשאר בני אדם. ותחשב.
גם אפשר שדנים בבריי' שונים. יש שמכניס דבר שאינו שווה בכל, ויש שאינו מכניס אותו.
** שבת –
איני מבין ל"ל רק מקשה מן ההו"א שחייב בלילה ראשון, שבוודאי אין לו מה ששחט בחג.
בכלל, אין שקלא וטריא של הגמרא כל כך מובן לי.
** בימה –
נמצא שהיה נוהג כמונו, להתפלל מן הבימה.
** אף על פי כן –
נראה שהרבותא הוא שאף שהיה גדול מאד, והיה קשה לסדר את כולו, סדרו אותו כדי שיהיו בני אומנות יושבים ביחד. ותחשב.
** בין קדש –
נראה שנקטו נפק"מ של סקילה כיון שבשקיעה היו תוקעים, וצריך תוספת שבת, ואז כבר שבתו לפני כן, ואין נפק"מ למנוע ממלאכה. קשה, שהתוקע צריך להוסיף על שבת. גם ק"ק, שבבלי אומר שתקעו קצת קודם שקיעה. אם כן, אם עושה מלאכה מיד אחריו, לא נסקל.
** מרקדים לפניהם –
לא מפרש לפני מי. לא יכול להיות לפני המנסכים מים, שזה היה כל שבעת הימים, ולא רק בזמן ניסוף המים. ותחשב.
