** ד"ה ומשני – ולא ילפי –
משמע מקרבן העדה שאין שום לימוד מהיכל. קשה למה לא אמר שרבנן עדיין לומדים מהיכל. (עיין בגמ' לקמן.)
** ד"ה היך מה – פי תקרה –
נמצא שאין שיטת רבי יהודה שכל דבר שהוא למעלה נראה כלמטה, אלא רק דברים מיוחדים, כמו פי תקרה או מעלה של פתח.
** ד"ה ראשו ורובו - הסיבה -
בא לבאר למה צריך להיות מחזיק שניהם, שהרי הראש יושב על רובו, ובוודאי, אם יכנס בו רובו, יכנס בו ראשו. אז, מפרש שהיו מטים, ואז לא יושב הראש על רובו.
יש לדון אם לנו, שלא אוכלים כמותם, השיעור (כל שיעור שתלוי בראשו ורובו) יהיה כדי להחזיק ראשו ורובו שלהם (ר"ל, בהסיבה) או שלנו (ר"ל, בדרך אכילה שלנו). ותחשב.
** ד"ה ומשני הדא - אם גבוהים שלשה טפחים מן הארץ -
לכאו’, אין זה כ"כ דווקא, ורצה לומר שגבוהים שלשה טפחים ממחיצות הסוכה. אבל, לשונו לא משמע כן כ"כ. ותחשב.
** ד"ה את יושב – ברוב היום –
וא"ת למה פסול בשאר היום. ונראה שכיון שברוב היום לא מסכך, לא נחשב סכך. אם כן, הוא פסול בסכך, ולא בישיבה בתוכו.
** ד"ה אלא – אי נמי –
אם כן, אם, לפעמים, דבר עומד בפני עצמו, ושוב בית בא בו, נמצא שהוא נחשב רשות בפני עצמו. ירו' אמר לעיל שנפק"מ מזה הוא שיהיה אסור לטלטל מזה לזה, ואז נמצא שיש נפ"מ גדול מזה. ויש לדון, שאולי צריך להיות שהוא עיקר הבית, במה שהוא קובע את הרוחות. ותחשב.
** ד"ה א"ת מלעלן – דדמיא למחיצה –
איני מבין למה זה יותר דומה למחיצה. ותחשב.
** ד"ה באילן - אי נמי -
הדיון בשני לשונות של קרבן העדה הוא אם "אילן" רצה לומר "אילין,” דהיינו "אלו,” או רצה לומר "אילן,” דהיינו עץ. ותחשב.
** ד"ה צריך - למצוה מן המובחר -
מלשון קרבן העדה משמע שאף שכ’ שצריך, לא רצה לומר שחייב. אלא, רצה לומר שכדי לקיים מצוה מן המובחר, צריך לחדש בה דבר. במקום אחר, הערנו ש"צריך" רק רצה לומר, “כדי להגיע לאיזה תכלית, צריך….” ותחשב.
** ד"ה קנים - טפח -
צריך ביאור למה אומר שקנה פחות מקטפח, שהענין אינו שפחות מטפח, אלא שפחות משלשה טפחים. אולי ר"ל שהוא כ"כ קטן עד שלא רק קטן משלש טפחים, אלא אף מטפח אחד קטן.
** ד"ה חברייה – דאל"כ –
מניח שבעצם צריך להיות שווה, אלא שכדי להיות שווה, צריך רווח יותר גדול. אז, לא מדבר בנותן סיכוך על גבי הקורות, אלא ביניהים. לולי זה, היה אפשר לומר שסובר שצריך להיות יותר על סכך הפסול. ותחשב.
** ד"ה מה אנן קיימין – הכא במאי עסקינן –
עיין במה שמבאר בגמרא. גמ' מקשה שיש סתירה בין דברי רב, שאומרים שיורד להיות אוכל ומטמא ע"י מחשבה, ודברי אחרים, שעולה מלהיות מקבל טומאה במחשבה. גמ' לא מתרץ שירידה לטומאה שונה מעלייה ממנו (וצריך ביאור למה לא), אלא משיב שמדובר בחשב להחזירם לגורן. לכאו', הענין הוא שרב אמר שמחשבה לשם אכילה מהני רק איפה שמתחילה כבר כיוון להחזיר אותם לגורן. כמו"כ, אולי רב לא מדבר בציור שחוזר וחשב עליו, אלא חשב לחזור עליו, ומתחילה היה לו אותו דעת. אבל, הלשון לא משמע כן. ותחשב.
** ד"ה כשרה ובלבד- מן הצד-
מפרש שדין זה רק נכון אם הוא מן הצד. יש להעיר שחולקים אמוראים (בין בבבלי בין בירושלמי) אם סכך פסול פוסל בארבעה טפחים או בארבע אמות באמצע סוכה. כאן, מפרש את המשנה כמי שפוסל בארבעה טפחים; יש לדון למה בחר לפרש אותו כן. ותחשב.
** ד"ה תמן נכנס ויוצא – התם איירי-
עיין במה שפירש, שלא הבנתי אותו כל כך. לכאו', הפשטות הוא לפרש שרצה לומר שכשאומר שנכנס כאן, צריך להיות שר"ל שיש יותר מן סכך הכשר, שמניחים שנכנס כאן רצה לומר שנכנס ויוצא. זכוכית רק נכנס, ולא יכול לצאת. אבל, אם כן, לשון תמן והכא מהופים. אין זה כל כך קשה, שמצאנו כזה בירו'. גם אפשר לומר להיפך, שדבר חזק יכול לכנס ולצאת בשווה, ודבר רק, בקצת יותר משווה, יכול ליכנס ולא לצאת. אולי מש"א רק ליכנס מוכיח לנו שצריך שיכול ליכנס ולא יכול לצאת. ותחשב. אבל, לא פשוט לי מה מכוון קרבן העדה לומר. ותחשב.
** ואין מטבילין- נ"א –
לכאו', נ"א שלו מוכרח, שאל"ה אין הנידון דומיא דראיה, שגם בסכך אומרים שסכך פסול בפני עצמה לא כשר, וזה כבר פשוט. אבל, זה לא מורה על שאלת גמרא, שהיה אם יכלו לשבת תחת סכך פסול כשהסוכה כשרה. ותחשב.
ויש לדון, שאולי ענין של ארבע אמות הוא שיש שיעור חשוב. אז, כיון שכולו סכך פסול, פשוט שאותו שיעור של סכך פסול הוא חשוב. לכן, שווה לארבע אמות שלו. אבל, לא מצאנו גודל של טיט הנרוק שפוסל, ולכן מממה שפוסל בכולו טיט הנרוק, צריך לומר שטיט הנרוק תמיד הוא עצמו פסול. ותחשב.
** מפני שאין לה גג- אינו ניכר-
איני מבין כל כך מה אמר. בתחילה אמר שהבעיה הוא שלא ניכר מהו הגג ומהו המחיצות, ואח"כ אמר שאין שיפוע גג קרוי גג. לכאו', צריך לומר ששיפוע גג לא כשר להיות גג כיון שלא ניכר אם הוא גג או מחיצות. איני רואה סברה זו כ"כ, שאינו מבין למה לא פשוט שהוא גג ומחיצות (שזה לא סותר את זה). ותחשב.
** שומר –
עיין בקרבן העדה, שמתחילה משמע שהוא פטור כיון שכמו שאין דרכו לשבת בבית, לא צריך לשבת בסוכה, שסוכה הוא במקום בית. אבל, בהמשך משמע שפטור כיון שעוסק במצווה. אולי שני הדרכים הם שני השיטות (שמגמ' יוצא שיש מחלקת בשומר מן הגנבים.) ותחשב.
** משובתי –
קרבן העדה משמע שהבעיה הוא שאינו אצל אשתו. אולי הבעיה הוא שאין אשתו משמחתו או אולי הבעיה הוא שאינו משמח את אשתו. בי"כ ובי"כ, איני רואה למה לא יאכל כשהוא רחוק, כמו שיאמר הגמ'. ותחשב.
** עד שאכל –
קרבן העדה פי' ששואל אם צריך לאכול כזית או כביצה. יש להעיר שלשונו הוא ששואל אם, כמו מצה, הוא "עד שאוכל כזית." לכאו', אז, לפי קרבן העדה לשון זה קצת מוזר, שהיה לו לומר ש"יוצא כשאכל כזית," שבא להקל, ולא להחמיר.
צריך לומר שמפרש שהוא אגב לשון שאומר בפסח, ששם הוא חומרא, שאומר שלא רק יכול לאכול משהו, אלא צריך שיעור כזית.
לולי קרבן העדה, הו"א שיש הו"א כאן (ואולי יש שני הו"א כאן) שיכול לקיים אותו באכילת משהו, שזה קיום מצוות סוכה, אף שאינו חייב בסוכה. גם נראה שהו"א שכיון שאוכל כביצה בסוכה, נמצא שכל משהו חשוב, ואז אולי יוצא באכילת משהו. וא"ת כיון שכבר אוכל כביצה, מהו הנפק"מ. ויש לומר שהנפק"מ הוא שלא יכול לאכול מה שהוא כנגד מצה עם דברים אחרים (כמו במצה). ודע שנמצא אז שהשאלה הוא אם צריך כביצה אלא שבמשהו יש דיני מצה או שצריך כזית ובכולו יש דיני מצה (ולצד זה לא צריך כביצה, שאין מקור לכך).
** לא סוף דבר –
עיין בקרבן העדה. לוי פירושו, הייתי אומר שר"ל שאין מחלקת רק ששולחנו שם, אלא הוא גם לענין שיעור סוכה, כמו שמפרש הבבלי. אבל, הוא לא פירש כן. לכאו', ייצא מקרבן העדה שכל זמן שיש טפח פנוי בבית קרוב לסוכה, יש מחלקת שאנו מחמירים עליו. מסתבר שאף בית שמאי מחמיר רק כשהוא פונה אל אותו מקום פנוי. גם יש לדון אם כל זה רק אם אי אפשר להפך ולאכול בסוכה (ר"ל, שאין מקום לשולחן בסוכה). ותחשב. גם אפשר שזה רק כשאוכל מאותו מקום פנוי (בלי שולחן).
** לולב – והדר תני –
יש לדון, באמת, למה חילק את כולם. לכאו', הוא מפני שיש פסולים בזה שלא שייך בזה. אבל, עדיין קצת צריך ביאור למה לא תני הפסולים שנוגע בכולם ביחד. ותחשב.
** של אשירה – שיעורא –
פי' קרבן העדה שהטעם שלא יכול לצאת בלולב של אשירה הוא שעומד לשריפה, ואז כתותי מיכתת שיעורא. אבל, עיין בגמ', שיש צד נגד זה. גמ' מצדד ששופר של עבודה זרה ושל אשרה כשר, כיון שלא כ' בו "לכם." משמע שאין הפסול מפני שכתותי מיכתת שיעורא. ועיין במה שנכ' על זה בהערות שלנו על הגמרא בסייעתא דשמיא.
** נקטם – הדר –
גם אפשר לפרש שהפסול הוא מפני שחסר חלק חשוב ממנו. הנפקא מינא יהיה אם רבי יהודה, שלא סובר שיש תנאי הדר בשאר מינים חוץ מאתרוג (עיין לקמן) יפסול בזה.
** כל לולב- כנגד –
עיין בגמ', שיצדד קרבן העדה שיש שיטה שצריך להיות שלשה טפחים חוץ מכנגד הדס וערבה. ותחשב.
** היבש עצמו – אתרוג –
אם כן, הרבה מן הפסולים יהיו כשרים לפי רבי יהודה. צריך לעיין בהם, לראות אם, באמת, הם כשרים. ותחשב.
** כדי לנענע –
עיין בשני לשונות שהביא (אם זה ארבע או ששה טפחים). נראה שחולקים אם גורסים (או אם מפרשים) שצריך "שלשה טפחים כדי לנענע" או "שלשה טפחים וכדי לנענע." ותחשב.
** דרכו לגדל-
עיין במה שפירש. נמצא שאין העלים ירוקים, שאם לא כן, דומה לעצו.
לולי רש"י, היה נראה ומר שמדובר במין הדס שדרכו לגמור את הענבים שלו כשהם ירוקים, שאף שבדר"כ ענבים ירוקים לא נגמרים, במין זה הם נגמרים. אז, נמצא שכבר הגיע לגמר פרי, אבל עדיין הם דומים לעצים. ותחשב.
** אמר למה – דלא בעינן-
עיין בגמ', שמשמע שזה נחשב הדר, ולא שלא צריכים הדר.
** כל שעה –
עיין במה שפירש. גם יש לפרש שר"ל שבכל זמן שהוא נוטל אותו ביום יכול לברך, אם לא שכבר ברך, שהוא מצווה הממשכת, כמו תפילין וציצית.
** והיכן – מדהר התנא-
קרבן העדה בא לפרש כאן "תנא היכי קאי," שאי לאו הכי, קשה למה תנא מתחיל לשאול מתי מנענע, ולא אומר תחילה שמנענע.
** תחי' וסוף –
עיין בשני פירושי קרבן העדה. השני קל להבין, שהוא שינענע ב"הודו" שנאמר בתחילה וב"הודו" שנאמר בסוף. פי' ראשון אומר, לכאו', שהיו מנענים פעמיים ב"הודו," אחד בתחילה, ואחד בסוף. נמצא שלא עשו ניענוע בכל סיליבא"ל. גם יש לומר שרצה לומר שימשיך את הניענוע מתחילת הודו עד הסוף. דחוק.
** דלא כר"ד – הפקר –
עיין במה שפי' קה"ע. וא"ת ל"ל אמר שצריך להפקיר אותו כדי שלא יעבור על גזל. נראה שבא לפרש למה מפקיר אותו, ולא נותן אותו במתנה. אבל, יש לדון למה צריך לפרש את זה, של"ל ליתן אותו במתנה יותר מלהפקיר אותו. ויש לומר שאף מי שסובר שאין הפקר אנסים הפקר יסובר שמתנת אנסים מתנה. ויש לדון.
** רבי יהודה – גזירה –
לולי מש"כ קה"ע הייתי סובר שרבי יהודה אומר שאין ברירה (ונראה שגם בבבלי מפרש שיטת ר"י כן), ולכן לא יכול להפקיר אותם מקודם, שלא ידוע על מה יחול הפקר שלו. ותחשב.
** אני והוא – בגימטריא –
זה רק מהני אם גורסים "אני והוא," ולא אם גורסים, "אני והו," אם לא שלא נחוש שיהיה אחד פחות מ"אני ה' (בשם יו"ד ה"ה ווא"ו וה"ה).
** מיד תינוקות – גזל –
לכאו', הביאור הוא שכיון שהמנהג היה כן, וגזל מקטנים רק אסור מדרבנן, מותר, שלא העמידו רבנן את דבריהם לאסור את זה. ותחשב.
** לילו –
קרבן העדה פי' למה לא מונה של עשיית קרבן פסח. אפשר לבאר שזה אינו הלל של זמן, אלא הלל של עבודה. כמו כן, יש לומר שזה לא נאמר בתורת הלל, אלא בתורת שירה שנאמר עם עבודה.
יש להעיר שמה שכתבנו מניח ששל אכילת פסחים הוא מחמת זמן ושהוא בתורת הלל.
** ד"ה מתנמנמים –
עיין במה שפי'. קשה למה לא פירש שממש לא ישנו כלל, אלא התנמנו. נראה שסובר שאם כן גם הנודר יכול להתנמנם ולא לישון. ויש לדון, שיש לומר ששינה של נדר שונה משינה זה. ויש לדון, שכיון שנדרכים הולכים אחר לשון בני אדם, מסתמא יהיו שווים. ויש לדון, שלא תמיד כשבני אדם אומרים מילה אחת מכוונים לדבר אחד. אז, אם תשאל לאדם "מהו שינה," יכול להיות שישיב דבר שונה מאם תשאל לו "ישנת." ותחשב.
