* ב.
** כדי להרחיק –
לכאו’, מרחיק מביטול מצווה. יש לומר שקורא את זה עבירה. גם יש לומר שקאי על דין קדשים, ואומר שחוששים שיאכל נותר או שיותיר.
** יש לדון
אם ר"ג גוזר בנותר. אם גוזר, יש לדון למה מחלק. אולי הוא חמור כיון שיש בו איסור כרת.
** נכנסים –
לשון "נכנס" קצת מעניין. מסתמא, רצה לומר שנכנסים להיתר. אבל, עדיין צריך ביאור למה יאמר לשון זה.
** שכיבה –
צריך לדון מה ענין שכיבה:
א. סיבה הוא. רצה לומר, מה שרוב בני אדם שוכבים אז (או מה שהוא אותו זמן שרב בני אדם בדרך כלל שובתים או שהוא הזמן הכי טוב לזה) גורם שיכול לקיים מצוות ק"ש. ודע שאפשר, אז, שאין זה מצווה התלוייה בזמן כל כך.
ב. סימן:
א. הסיבה שבני אדם ישנים שם הוא מחמת שום דבר במציאות, וזהו העושה אותו זמן קריאת שמע.
ב. הסיבה לק"ש הוא שום דבר, וקורה בעת שבני אדם ישנים.
גם צריך לדון אם עושה יותר יכולת לס"ט או יותר צורך לס"ט.
** רש"י כדי –
מניח רש"י שהוא כדי שלא יאכלן לאחר כך. וא"ת נחוש שלא יאכל אותם בזמנו, כמו בק"ש. וצריך לומר שסבר שיש לחוש לשניהם, וכ’ זה מפני שהוא יותר חמור, ועוד שנכלל בו חשש שלא יאכל את כולו לפני זמן נותר ועוד שכבר גילה את השני מדין ק"ש. ודע שיש לדחות על פי מה ששמעתי מאת רש"ש שליט"א שיש צד באחרונים שמצוות אכילת קרבן לכפר ה"ה רק בזית ראשון.
** היכא –
ועוד יש לומר שמק’ מהי"ת שיש זמן לו. וכן קצת נראה ממה שמניח גמ’ בעירובין (ב.) שיודעים קראי (ע"ש), ואז יש לומר שרק בזה, שלא כל כך מפורש בקרא (שמהי"ת שר"ל "זמן שכיבה"), דן).
** בריאה –
יש לדון אם זה סימן או סיבה.
** מילתא –
וא"ת אם כן מהי"ת שצאת הוא (ר"ל, זמן ביאת שמש). ויש לומר שאין זמן קבוע להקרבת קרבנות. אף אם יש זמן קבוע, בוודאי אינו זמן שכיבה.
* ב:
** כדאמרי –
יש לדון מה ר"ל:
א. מתרץ למה נכפל לשונו.
ב. מבאר מהו "וטהר.”
** מבריי’ –
עיין במה שהק’ לעיל. ויש לומר פשוט שהו"א שר"ל שכשר מסוף זמן שמקריבים קרבנותיהם ולעלם בשעת כפרה הוא. וא"ת למס’ מהי"ת שאינו כן. ויש לומר שזה בשקיעה. עוד יש לומר שזה צ"ל קודם תמיד, ואז אינו בצאה"כ.
** עני –
עיין לעיל שהק’ למה לא אמר צאת. וי"ל שזמן זה יותר ידוע, שהרבה עניים יש, משא"כ זמן דמשנה, שאין כ"כ אוכלי תרומה, ועוד שלא תמיד אוכלים בזמן הרשאון שמותרים לאכול.
** עני וכהן -
וא"ת אם כן  ליתני רק חד. וי"ל שחד משמיענו דין כהן, וחד נקט היותר שכיח. ותחשב.
** זכר –
משמע שלק"ש צריך לילה, וזמן שכיבה נח’ לילה לק"ש. זה אומר שיש שום דבר הקורה בלילה, וקורה בשום ענין בזמן שכיבה, ולכן נח’ לילה דק"ש. עוד יש לומר שמניח שזמן שכיבה ולילה שייכים להדדי. קצת קשה למה. גם עיין במה שכתבנו בפסחים שיש מושג של חד זמן להיות מיוחס לזמן אחר. אם כן, יש לומר שזמן שכיבה מיוחס ללילה ביחס מיוחד, וצ’ זה לקיום מצוות ק"ש. זה nebulous, at best.
** ר"מ היינו רבנן –
הו"מ למימר שחול’ בזמן תחילת אכילת תרומה.
** עני ובנ"א –
צריך ביאור למה סבר כן (ואולי כן היה נ’ לו במציאות).
** רש"י מבריי’ –
לשון ראיה קצת מעניין.
** רש"י שאין –
זה נגד תוד"ה אף על פי.
** רש"י ומקדמי –
דהוי – ק"ק למה מזכיר כן בעלוה"ש, ולא בצאה"כ.
** אנא אבין –
קצת משמע שלא ממש סבר כן, אלא אומר מה יהא אז הדין, אלא שאז אין סתירה בר"מ.
* ג.
** ק’ דר"מ –
ק"ק למה א"א ששניהם חד שיעור. ואולי לא מסתבר כן במציאות.
** סימן לדבר –
יש לדון אם הוא סימן למשמר או לשאגת ה’. באמת, צריך ביאור מתי בכל משמר יש שאגה.
** מכי אשה –
נמצא שאין אשה סומכת על  ראית חמה, שאם לא כן, איך תדע. יש לדחות שיש נשים בחוץ הראות, ואלו רק שומעים.
** סוף –
וא"ת ליתני תחילה. ויש לומר שיותר מסתבר שבן אדם יישן בבית אפל, וישאר עד אחר עמוד השחר משילךל לשם קודם צאת הכוכבים. עי"ל שאינו מצוי שיהיה בבית אפל, ויהיה קרוב לחמור עד שיוכל לשמוע אותו.
** למקרי ק"ש –
ק"ק למה צריך נקודה זו (שבפשט ראשון של גמ’, אין נפ"מ בדין).
** שמתפללים –
נמצא שיש הו"א שאף תפילה קצרה לא יתפלל כיון שחושש שמא יפסקנו עוברי דרכים.
** רשי ישאג –
יש להעיר שלא נל’ מה שיש שלש מכאן. (ודע שאפשר שזה רק מקור ששואג שלש פעמים, ותנא סובר שכיון שיש שלש משמרות, יש יחס בין השאגות למשמרות.)
** תיפוק –
רצה לומר, למה נמנה כולם (אבל, טעמים הם מפני שהם. ויש לדון, שאולי קבעו איסור. אז, אולי משמע שכ"א סיבה לאיסור.)
* ג:
** הוה להיו –
לכאו’, לא משמרות ממש, אלא זמן שתי משמרות. עוי"ל שכיון שקצת נח’ לילה, שכשר לק"ש, יש בו משמרות.
* ד.
** כחצות –
נמצא שלר"א יודע
מתי היה חצות. צריך לומר שאכתי דוד לא ידע, דא"א לומר שהוצרך להעורר אותו, שהרי ר"א לעיל אמר לו שכבר קם. ויש לומר שצריך להתעורר מלימוד שלו. ויש להעיר שלכאו’ א"צ ר"א להא דאמר ד"משמרה ופלגא,” שיש לומר שקם קודם ולמד. ותחשב.
** כחצות –
צ"ב למה תלה בדעת משה, שיאמר שיהיה בחצות, וה’ יעשנו בחצות.
** רש"י ואביתר –
וזה קודם ימי אבשלום, שנמנה אחיתופל.
** כרתי –
עיין לעיל. מצאתי כ’ בגמ’ שלי: “רש"י סבר שהם או"ת. עיין רלב"ג שם, שר"ל סנהדרין. כן יותר נ’ מקרא, אלא שלשון גמ’ שלא אמרו מיד אחרי בניהו ק"ק. ושו"ר לעיין בתוס’.”
** מפיבושת –
על"ע, שהק’ שאמר דוד שלא בוש. נראה מרש"י שבוש בשטעה, ומה שאמר שלא בוש הוא שלא היה בושה לו לשאול ממפיבושת.
** שמא –
משמע שאין הענין שבא בזמן שאינו חצות, ואמרו שטעה בזמן, אלא יחשבו שכבר בא חצות, ולא בא מכה, ועד ביאת מכה, יחשבו שטעה משה על ביאת המכה.
* ד:
** ואי כר"ג –
וא"ת הרי כן אמר בפי’ במשנה. ויש לומר שסבר גמ’ שזה רק שיטת ר"ג.
** משים –
יש לדון אם ר"ל שלכן נתנו עליו יותר חומר או שלכן הזכירו אותו חומר. יל"ד, שכ’ גבי תפילה.
** כיון דתקינו –
לכאו’, לא ר"ל שענינם שווה, שא"כ מה לנו שתקנים זה קרוב לזה (ואולי צריך שניהם), וצריך לבאר מה לנו בתקנת חז"ל. וי"ל שר"ל שכיון שמוכרחים להיות חיד אחר חברו, נחשבים כחד, עוי"ל  שכ’ שאומר שכיון שרבנן הוא שתקנוהו, תק’ להיות חד ברכה (וקצ"ב מה זה "תקנוהוה להיות חד ברכה"). ותחשב.
** מובטח לו –
לשון "לו" קצת מוזר.
** נימא –
ק"ק לל"א שזה יש בו סדר א-ב, ואין בו נון.
** נימא –
הומ"ל שרוצה א, ומיד אחריו ב, ודלא כקיט’.
** במערבא –
וא"ת א"כ, נוכל לומר נון באשרי. ויש לומר שאכתי יש בו מילת נפילה. ויש לדון.
** אם ר"י וריב"ל –
חול’ מסברה, צריך ביאור למה יהיה חייב לומר תפילה קודם ק"ש. (אולי אין חיוב.) ותחשב. אולי יש שום סיבה אחרת למה תפילה יקדים.
** רש"י המוכר –
לכאו’, אין טעם זה (שמכרו מחמת דחקו) בדר"כ שייך במתנה.
** מתנות –
עכשיו, קורא לתורה מתנה. אולי מכוון למש"א שמי שמקבל יסורים יש לו תורה המתקיים בידו. ק"ק מש"א שניתן לכל ישראל. יש לומר שכל אחד יכול לקחתו אם נעשה צדיק. ותחשב.
* ה.
** אלא תורה –
אם כן, אצ"ל ק"ש בדוקא, אלא יכול להיות כל ת"ת.
** בענין ק"ש שעה"מ
, נראה שמסתבר שיש בו ענין כיון שזמנו הוא זמן שכיבה. זמן שכיבה של העולם די לזה, אבל לכל אחד ואחד, זכן שכיבה שלו הוא הכי טוב. (אבל, יש לדון למה, אז, אין כנגדו בבוקר.) עוד יש לומר שיש ענין בקיום קרא כפשוטו. (אלו דומים, ולא נראה שהם שווים). יש להעיר ע"ז כמו שהערנו על הראשון.
** מוכר –
עיין במה שהק’ לעיל שי"ל נותן. ויש לדון, שאולי מכירה היא (כדאמר "לקח"), שבני ישראל נעשים עבדים לה’ בחילוף זה. אבל, יש לדון אם זה באמת בחילףוף מתנת התורה.
** -שנאמר "כי את" –
צריך ביאור מה רואים מכאן.
* ה:
** בנים זכרים –
יש לדון אם זה סימן או סיבה להנהגת אבא בנימין.
** נגעים ובנים –
היה אפשר לומר שהוא אליבא דרביה (ע’ ב"ב קטז.).
** רש"י וגברא –
עיין ברשב"ם (ב"ב קטז.) שחלק בביאור זה.
** רש"י דהוו-
ק"ק למה לא אמר שהוא מכפר כיון שיסורים הוא ממה שאין לו בנים. אולי כיון שהוא אותו צער של מי שאין לו בנים כלל, זה א"א.
** ודאי –
נמצא ש"ודאי" רצה לומר "נבין אותה בזה.” יל"ד, שאולי היה מנסה למצוא על מה בכה (?), והיה דוחה על צד שלו.
** רשי שכינה –
עיין ב"ב כה.
* ו.
** ה’ עוז –
לא הבנתי למה צריך קרא לזה, שאינו מגלה כלל, לכאו’, שתפילין נקראו עוז.
* ו:
** משאיל –
מוזר מה שלא אמר "שואל.” ותו"ת.
** ולא מצא –
לכאו’, ר"ל בעת תפילה. ונראה שאין לפרש שר"ל בכל זמן, ושהוא מפני שצריך עשרה בטלנים, שלכא’ הם לומדים, וא"כ יהיו בבית המדרש, ולא בביה"כ.
** למיפק –
וא"ת זה פשוט, שהרי רק אמר "היוצא.” אולי הו"א שהסיבה לדין זה הוא שאינו כבוד לרוץ קרוב לביה"כ (אלא שאכתי ק"ק מה שנקט יוצא). ויש לדון למס’ אם חוזר מזה (כ"נ מרש"י) או שמתיר לעיל בריצה כיון שטוב שיועיל במהירות (ונדחה). גם נ’ שי"ל שמתיר יוצא כדלעיל (ודנו אחרונים בזה).
כמו כן, יש לומר צד שבעצם ה"ה בזיון לרוץ קרוב לביה"כ, אבל קודם שמגלה בו רצון לכנס, אין בזיון בזה. ותחשב.
** ככרום –
יש לדון אם ר"ל שנ’ ככרום או שכמו שכרום מהפך, כ"כ מהר ובכ"כ שיעור, כך פניו מהפכות.
** כדי בר –
וא"ת אינו נ’ כמאמין בשני רשויות, אלא ברשות חלוק משל שאר בני אדם. ויש לומר שרק גילה שמאמין ברשות חלוק, ולא נניח שלא מאמין בה’, ולא נחשוב אותו ככופר. עוד יש לומר שאמר לו, “אטו יש להם רשות אחר משלך,” דהיינו שיש לך ללמוד מהם. ודחוק.
* ז.
** פני ילכו –
קשה, שאיזה רגע של אף, כבר יעברו משאמר כן.
** ניים –
ק"ק איך אמר שאז ניים (שהוא ישן). וצ"ל שראה שאר הזמן, ולא ראה את הסימן.
* ז:
** לבכירותיה –
יש לדון, שמסיק גמ’ ב"ב שלא היה ראוי לבכורה. ע"ש.
** וישמע ראובן –
משמע שכבר ידע שבכורתו ניטלת ליוסף אז.
* ח.
** רש"י עת רצון –
עיין במש"כ. לולי רש"י, נראה שאפשר לומר שגמ’ מפרש ש"עת רצון" רצה לומר "עת של רצון,” שהוא זמן שבו מתפללים ציבור, שה’ מרצה להם.
** כריב"ל –
ואם תאמר כבר היה בא”י. וי"ל שאכתי זה מחייב אותו יותר. (א. באורך יותר. ב. יש יותר יכולת שיאריך ימים.)
** וטוב לך –
זה מעניין, שלכאו’ הו"א שיותר יש סיבה שיהיה בעוה"ב. נראה, אולי, שכיון שיש רק חד הנשאר, להכי דורשים.
** ד"א –
עיין במגילה (יג.) “מגוי שבחו שלא היה משתמש ביום.”)
** הל’ כרבים –
הם אומ’ כן, אבל ר"ע לא סבר כן, שטעם יחיד מסתבר.
** פסח –
ק"ק, שדילמא נתרבה בכלל "נאכלים ליום אחד.” ויש לדון.
* ט.
** השכיבנו –
משמע שלפני עה"ש, יכול לומר כן. וק"ק, שאף אז, לכאו’ הוא זמן סוף שכיבה.
* ט:
** בע"כ דישראל –
לכאו’, היה אפשר לפרשו ע"פ מש"א דבי רי ינאי (ונראה שצריך לדון למה יצרכו לשבות. (א. לשאול. ב. כיון שיש משוי), ומהו סברות גמ’ דשמוי (א. קשה. ב. לאט).
** מפלתם –
לכאו’, זה כר"מ, ולא כאשתו.
* י.
** כל פרשה –
מניח גמ’ שזה היה חביב לדוד. אולי מימרא נאמר על זה (אז, מביא ראיה מן המאמר באופן דיירקט).
** כלום יש –
לא הבנתי למה ירצו להכחיש רק חד, ולא תרי, ואולי ר"ל שמלמד נגד הכחשרת בני אדם בזמן דוד, והם ידעו בבירור מעשה דאבשלום.
** תולה בעצמו –
יש להעיר למד"א שהתפלל על עסקי קיר.
** ספר רפואות –
נראה שהיה אומר טענה שהיה יכול להתרפאות אם לא שחש לכבוד ה’ (שגנז אותו לכבוד ה’). ועוד, שאולי לא רק היה יכול לפני זמן אם לא גזנו, אלא היה יכול אז, שהרי הוא גנז אותו, ומסתמא הוא ידע את מקומו. ותחשב.
** גנזו –
קצת צריך לבאר מה קרה, שמשמע שהוא רק חד copy שלו. אולי רק היה אחד בכל הארץ. צריך ביאור למה לא עשו שני. אולי מלך לא הניח להם להם. גם אפשר שגנז כל copy.
* יא.
** ב"ש מ"ט –
יש לדון מה אומר בב"ה:
א. אומר כן מפני שרק אז מפרש שני הטעמים (ר"ל שני הקראי).
ב. אומר כן מפני שמפרש טעם של ב"ש באופן אחר (וזה יכול להיות מפני שכן מסתבר ומשמע לו).
גם יש לומר שלא ר"ל "יודעים למה ב"ה לא סבר כב"ש; למה ב"ש לא סובר כב"ה?” אלא ש"מצאנו שפי’ ב"ה את קרא של ב"ש באופן אחר; למה לא פירשו ב"ש כן?” זה לא נראה כ"כ, שא"כ לשון "קמפרשי טעמייהו" אינו שייך.
** דקאזיל –
משמע שאף הכשר מצוה, כמו הליכה, יפטור.
** ובקומך –
משמע שעמידה נחשב קימה (דאל"ה יצטרך לקרוא אותו כשקם). ואולי מה שזה קשה (שקימה, בדר"כ, לא תופס כ"כ זמן) אומר שעל כל פנים לענין זה, ר"ל עמידה. יש לדון אם יהיה כן לשאר דינים. עיין בעה"ש (נח, ו). ותחשב.
** במה שצ"ל טרוד,
יש לחקור אם הענין הוא שצריך טרדא, שאז יש יותר שמרחיק אותו מעשיית מצוות (ואז, מה שע"י מעשה יותר נח’ טרוד הוא שאז יותר קשה לו) או שאז יותר מיוחס הוא למצווה (ואז ע"י מעשה כיון שטורח במעשה (ועוד, וצ"ב ל"ל אומר כן רש,י, מה שטורד ועי"ז גורם ליכולת למצוה) יותר מיחס למצוה. (כשכתבתי מעשה, נ’ שר"ל מצוה.) ונ’ שק’ גמ’ מטבעה ספינה מניח כראשון. אבל, יש דלון מהו תשובתו.
** רש"י אחת –
היה אפשר לומר שקאי על שלפניו.
* יא:
** כדי להזכיר –
נמצא – ונ"ל שזה קצת מחודש, שאף שכבר נזכר דבר שאינו לשון מעליא, אכתי רוצה לומר לשון מעליא. ותו"ת. אולי כיון שעושה דבר נצרך נח’ מעליותא.
** רש"י יוצר –
מז’ רש"י החי’ (“שהוא… פסוד"ז") ונפ"מ (“ויכול לקראתו"). יש לדון אם צריך שני (שאולי בלי נ"מ, היה משנה כוללם). ותחשב.
** לימא נוגה –
מענין מה שמקשה על זה תחילה:
א. שבפשטות, הו"א שברה חיצונה הוא לומר כדרכה.
ב. שאם מק’ על השני, יכול להק’ ממה שכבר הוזכר (ר"ל, אף שלא הוזכר כבר בתפילה, כאילו הוז’, שכדי להגיע לשני, צריך לומר ראשון. ותו"ת.)
** הלכך –
יש לדון אם ר"ה אמר כן או גמ’ אמר כן.
** ברכות –
ר"ל, שאי אמר יוצר אור, אז צ"ל שלאיזה סיבה, לא צריך לומר א"ר. סיבה זו, מניח גמ’, יהא אף לאח"כ, ונמצא שלא יאמר א"ר כל. אבל, אם לא אומר, יוצא, יודעים את הסיבה, והוא שאינו זמנו, וזה לא שייך לאחר זמן. ותו"ת. (גם יש לומר צד שפשוט שאינו מעכב אם רק אפשר לומר חד. ותחשב.)
* יב:
** בת קול –
צריך ביאור למה צריך נקודה זו, שהרי קרא קורא אותו בחיר ה’. ותחשב. עיין ברש"י. ויש לחשוב.
* יג.
** והיה שמך –
ק"ק שלא אמר "תקרא אברהם,” אלא שכן יהיה שמו. אם כן, הקרוא אותו אברם לא עושה נגד זה. ויש לדון. אולי משנה אותו קצת, ועושה שאינו כל כך שמו, ששמו קצת תלוי במה שאומר.
** אברם … נביא –
נ’ שזה מקור למה שבני אדם אומרים שמות רבים בלי שם רב כשמספר על קטנותם.
** התם קב"ה –
צריך ביאור מהו תי’ זה. ותחשב. אולי ר"ל שנאמר רק לאברהם או שחזר ה’ מדאמר "שרי אשתך" (ויש לדון אם ידע גמ’ סברה זו. ואולי שאני הכא שזה בעת נתינת שם. זה יכול להיות לשני הצדדים.)
** שהכל –
נראה לכ’ כמה צדדים:
א. דן גמ’ אם תחילתו או סופו קובע (וסופו יקבע או מפני שסוף הוא או מפני שנאמר). אז, ממילא דיון זה שייך רק אם תחלתו פסול.
ב. סבר גמ’ שתחילה קובעת תחילה וסוף קובע סוף, אלא אז, יפסל כיון שחלקו אינו טוב. אם יכול לצאת בו, נמצא שכולו טוב.
ג. כיון שמח’ בתחילה ובסוף חלוקים (או מפני 2), אינם מצטרפים להיות ברכה אחת. מה שלענין מה שנאמר עליו ה"ה שוים גורם שיכולים לצרף. (ועוד, שאז לא קרה דבר חשוב (שינוי דעת) ביניהם, שאינו מוכרח לגרום חילוק במה יעשה).
