* ב.
** לא קרינו -
ואם תאמר למה היו שואלים לו; קל מאד לומר קריאת שמע. אף אם אין מצווה, מה איכפת להם, שלא חסרים. ויש לומר שהיו שואלים על הברכות, אם עוד יכולים לומר הברכות. (ויש לדון בזה, שבקריאת שמע של שחר, יכולים לומר הברכות, אף אחר זמן קריאת שמע. אבל, יש לדון בזה, שאולי אפשר לחלק. דבר ראשון, יש לומר שזה רק מפני שהוא זמן קימה, במה שבני אדם הם כבר קמים (לא עושים מעשה קימה, אלא כבר קמו). ותחשב. גם יש לציין למאירי, שמצדד שרק יכולים לברך בתוך זמן תפילה. (צריך לעיין שם, שאיני יודעד למה, אבל אולי זה יהיה שייך לכאן.) ותחשב.) גם יש לומר שהיו שכורים, מחמת המשתה. השאלה היה אם יפיגו את שכרות שלהם (גמ' נותן אופנים איך לעשות כן) כדי שיוכלו לקרוא קריאת שמע. זה, באמת, לא היה כל כך קל להם, ואז לא רק עשו כן, אלא שאלו עליו. ותחשב.
** ואי בעית אימא -
עיין במה שכתבנו בגלגל ששי (על הנייר), שהקשינו איך לפי בית שמאי יש מקור שקוראים שמע בזמן שכיבה ובזמן קימה (כיון שדורשים מאותו קרא שצריכים לשכוב ולקום). נראה אולי לבאר שגמ' כאן לא רק נותן תשובה שנית לקושיה אחת, אלא לשתי הקושיות. אומר שרואים מן הקרא ששני "זמנים" של היום הם ערב ובוקר. מצוה כקריאת שמע מסתבר להיות, אז, בבקר ובערב, אחרי שנאמר סתם. ותחשב על זה.
** רש"י ד"ה כדי להרחיק -
והקטר חלבים…- ואם תאמר הרי מה שמצוות של לילה הולכים כל הלילה לא שייך לכאן, שאין שמע מצווה של הלילה, אלא של זמן שכיבה. ויש לומר שכוונת הגמ' כאן הוא להמשיך שעושים קנס. מביאים מקור של קנס כזה, ובתוך אותו מקור, צריכים להוכיח שנוהג, מדאו', כל הלילה. לכן, מביאים מכאן שמצוות הלילה נוהג כל הלילה. ותחשב.
** הקטר חלבים -
אם הייתי ישיביש, הייתי טוען ככה. קשה למה לא גזרו על זה כמו על דברים אחרים. יש לומר שהוא מפני שבדברים אחרים, יש רק מצווה אחד, מצד טובת החפץ. אבל, כאן יש גם מצווה מטובת המזבח, וזה לא בטל בזמן. אז, אין כל כך צורך להם לגזור. אבל, אין לי מקור לזה, וגם לא נראה מסברה, כיון שאין אני ישיביש. יותר מסתבר לומר שלא גזרו כיון שכהנים זריזים בעבודה שלהם.
* ג.
** אי קסבר שלש -
ואם תאמר לא צריך לדון כמה משמרות יש בלילה, שבין כך ובין כך, יאמר מנין שעות. ויש לומר שאילו לא היה מנין שלם של שעות, לא קשה שינקוט משמרות, שהוא מנין שלם, ולא שעות. גם יש לומר שאילו לפעמים היו שלש משמרות ולפעמים היו ארבע משמרות, לא היה קשה שינקט משמרות, שבאמת, לא תלוי בשעות כלל, אלא תלוי במשמרות. (במילים אחרים, רק צריכים לדעת המשמרות, אבל ידיעת השעות לא מספיק.) ותחשב.
** על כל משמר -
יש לדון אם רצה לומר בזמן המשמר (ואז, יש לדון אם רצה לומר בתחילתו, בסופו, באמצע שלו, בזמן אחד בו, בכולו, או בסוף אמצע ותחילה) או שרצה לומר שעושה כן על המלאכים השומרים (שזהו משמר) (ועדיין יש לדון מתי עושה כן עליהם בכל משמר). ותחשב ותבין.
** למיקרי קריאת שמע -
פלא הוא, שאין זה זמן קריאת שמע של שחר, אלא צריך לחכות עד זמן שאומר משנה לקמן. וצריך ביאור. צריך לומר שמתחילים בעלות, ואם הוא קם מחמתם ושומע אותם, כבר אחרי עלות הוא. אבל, צריך ביאור.
* ג:
** אין אומרים בפני המת -
יש לדון מהו הגדר של לפני המת, אם הוא, כמו כמה דיני לועג לרש, רק בתוך ד"א או יותר או פחות מזה. גם יש לדון אם זה אסור גם בבית הקברות.
** רבי זירא אמר -
נראה שיש הרבה קושיות חזקות. דבר ראשון, קשה איך יפרש רב אשי מה שאמר שיקום בחצי לילה. גם קשה לפלי רב אושעיא למה נקט חצות, שכל הלילה לא עבר בזמן שהוא שכב, והיה לו לנקוט זמן יותר מוקדם. נראה לבאר שסגנון של הגמ' אינו מחלקת, אלא ר' אושעיא אמר תי', וכולי עלמא מודים לזה. אבל, צריכים לפרש מה קרה בחצות, ולמה נקט חצות. אז, אומר שני פירושים לבאר זה. (באמת, היה אפשר לומר שר"ז מת' בפני עצמו, אבל זה אי אפשר בהמשך הגמ', לפי מה שפי'. אז, צריך לומר שלא היה קורא לזה קם, שמתנמנם לא ישן.) ותחשב על זה.
** כחצות -
קצת צריך ביאור למה לא פי' שאמר "כחצות" כיון שלא יקרה בחצות, אלא כחצות. ונראה שהוא מפני שקרא אומר שה' הכה כל בכור בחצי הלילה. אז, צריך לומר שאינו כחצות אלא בחצות.
** סימנא -
יש להעיר שאף אם היה יודע, אם היה ישן אז (או אולי אף אם היה מנמם), היה צריך זה כיון שלא היה מבחין בשינתו. ותו"ת. (אולי זה חלק מכוונת גמ' כשאומר שהיה צריך כדי לעורר אותו משינתו.)
* ד.
** יושבים אגודות -
יש לדון אם רצה לומר שהם יושבים ביחד באגודות או שיושבים אגודות של שרים לפניהם לכבד אותם.
** בני -
נמצא שיש חידה כאן: מי קרה לאח שלו בנו? שלמה.
** נס -
יש לדון למה זה יהיה יותר טוב. אולי יהיה יותר קל, ואולי יראה חביבות ה' להם.
** ראויים -
לכאו', רצה לומר היה סיבה, אלא שהחטא היה מניעה. אבל, לפעמים, אין אף סיבה שיהיה נס, ואף שאין אדם חוטא.
* ד:
** אליהו -
יש לדון אם זה אליהו הנביא או אליהו המלאך (רש"י (נ"ל בקידושין) אומר שיש מלאך שנקרא אליהו, וזה לא אליהו הנביא).
* ה.
** חד פסוקא -
אפשר לפרש שכוונתו לומר שצריך לומר חד פסוק של תורה כעין פסוק זה. ותו"ת. (ועיין במה שדנינו בזה בתוך גלגל ששי על הנייר.)
** זו משנה -
קצת צריך ביאור, שמשנה כולל הרבה תורה כבר. אולי רצה לומר שה' לא רק נתן תורה, אלא הסביר אותו, ואמר משנה עליו. ותחשב. ודע שאפשר שזה כולל גם בריי', שהרבה פעמים נקראים גם משניות.
** תוכחות מוסר -
איני יודע מהיכי תיתי שזה יסורים, שאולי הוא רק שצריך להוכיח את עצמו, וזה קשה. ותחשב.
* ה:
** ההוא סבא -
עיין בתוס' בחולין שמביא שבדרך כלל "ההוא סבא" הוא אליהו הנביא. אז, מעניין שמביא דבר מרבי שמעון בר יוחאי. ותחשב.
** מי חשיד -
צריך ביאור למה לא חששו שהוא יסורים של אהבה. נראה שראו שהיה מבטל אותו מתלמוד תורה. ותחשב על זה.
** מצוי -
נראה שכולו המשך אחד, ורצה לומר- כיון שה' מקדים ובא, ורגילים עשר לבוא לבית הכנסת, אז ה' מצוי בבית הכנסת, אף כשאין שם עשר. ותו"ת.
** עוז -
מעניין, שדורשים מ"זרוע עוזו," אבל "עוז" הוא תפילין של ראש, כמו שאומר גמ'. אולי רצה לומר "זרוע ועוזו." ותחשב.
* ו:
** משאיל -
נראה שהענין הוא שה' גורם שאחרים שואלים (שזה לשון "משאיל"), והוא שלא מעניש אותו מיד, אלא נותן לו זמן כדי שאלה. יותר מכך, נותן לו שאלה, כדי לעורר אותו. ותו"ת.
** קא מחליין -
משמע שחילול דרבנן נקרא "חילול."
** לא נברא אלא בשביל זה -
נראה שהענין הוא שכיון שהעולם צריך להיות הולך באופן רגיל, כל העולם היה צריך להיות נברא כדי שהוא ייברא. אבל, אינם כדי להנות אותו כלל. ותו"ת.
** נקרא גזלן -
יש לדון מה גזל, אם הוא שלום של חברו (שנותן לו בדעת שיענה שלום, אבל לא ענה) או שלום שלו, שלא נתן. בדרך כלל, לא קוראים למה שלא נתן דבר גזילה, ואז משמע כצד ראשון. ותחשב.
* ז.
** אלמלי -
במקום אחר, הקשיתי שלא היו כל כך הרבה ימים, ואז לשון גמ' קצת מוזר. ויש לדון. נראה שאולי בלעם המשיך לקלל אותם אף לאחר שנתן עצה (שלמה לא יקלל כיון שהיה שונא אותם). ותחשב.
** כשרציתי -
נ' שעל נקודה זו היא המחלקת, אם ה' רצה או לא. רק יכולים לומר שיבוא למשה שכר על זה אם נאמר שה' לא באמת רצה. ותו"ת.
** שאלמלי -
עיין בתוס'. לכאו', יש ראיה  לזה ממה שיש ענין להתפלל בהנץ החמה, שאף שם, רק מתחיל. ותחשב.
** משה -
יש להעיר שבלי זה, כמעט מוכרח שיהיו לו בנים כזה, שהרי אחרי אלפים שנה, לכל יש כזה. ויש לדון. אגב, כעין זה, צריך ביאור למה אין הכל מתים ילדים, כי כולם בני עלי. אולי אינו הולך אחר הנקבה (אבל זה תלוי באם היה רבא, אם היה מבני עלי, כהן. ותו"ת.).
* ז:
** לא נענה -
מעניין שדן במה שנענה, אבל מביא קרא שמדבר על תפלתו.
** ראו -
כל דבר כעין זה צריך ביאור, שצריך לומר, לכאו', שהיה כבר מוכרח שיקרה. קצת קשה, שתלוי בעבירה. (באמת, צריך לע' בגמ' בב"ב שמשמע שלא נקט אותו מראובן, אלא תמיד היה של יוסף. וצריך לעיין שם.)
** ראובן -
היה אפשר לחלק לומר שראובן הכיר שזה היה פי"ר, שידע בעוונו, ולכן לא שנא את יוסף. אבל, עשו חשב שלא היה פיי"ר, שלא יהיה בכור, אף שמכר אותו. ויש לדון.
** שטר חוב -
כמובן, יש לציין לגמ' בעבודה זרה גבי "שמח הוא לאחר זמן."
* ח.
** אלא ארבע אמות -
היה אפשר לטעון שרצה לומר שמהלכה רק יש לו ארבע אמות. אבל, כל הגמ' לא משמע כן. ותחשב.
** שלש עשרה בית הכנסות -
יש לדון אם רצה לומר שרק היה מתפלל באחד, איפה שהיה לומד, ולא היה מסתובב לאחרים, או שאף לא היה הולך לביה"כ בכלל. אם נאמר כשני, נמצא שיש יוצא מן הכלל של ענין השכן רע שמזכיר גמ' לעיל.
** סכנה -
ע' בשבת, שיש דיון שם (ואולי נוכל לעשות את זה מחלקת, אם נניח שהשואל והמשיב חולקים) אם מכה של יד (אבל שם גב היד הוא) הוא סכנה. אולי זה גם תלוי בזה. אבל, יש לדון, כיון שסכנה יכול להיות רק סכנת אבר. ותחשב.
** אסור -
נמצא שהיה מזהיר אותם על מה שאסור ממש. אפשר שלשון של האוסר הוא לאו דווקא, ורק רצה לומר שלא לעשות את זה. ותו"ת.
* ט.
** ויחיד ורבים -
יש להעיר שגמ' לעיל (ד:) היה מקשה איך אפשר להיות ככה. אז, היה מוכרח כתשובת רבן גמליאל.
** אכילת -
ואם תאמר למה צריך למנות את הכל. וי"ל שאם מנה אף מה שאין בו גזי' בוודאי ימנה את זה שמסתמא יהיה בו גזי'. ויש לדון אם באמת יש בו גזי' (לפי מי שמתיר עד עלות השחר).
* ט:
** לימרו מעיקרא -
יש לדון למה זה יותר טוב; היה אפשר לשאול איך בחר, אבל קושיה זו לא נראה לי כ"כ. ותחשב על זה.
* י.
** סמוכים -
צריך לע' בפסוקים, שממה שמביא גמ' לא מבין את התשו', שלא ענה כלום לשאלת הגמ'.
** בן אחאב -
ואל תדחה שכיון שהיה רשע, היה צריך ללכת, שאליהו הלך לאחאב. אבל, היה אפשר לדחות להיפך, שאחאב היה יותר רע, ולכן לא היה מסכים לבוא. ויש לדון, שגמ' אומר שהיה מאד מכבד ת"ח (אני חושב).
* י:
** כי ברוב -
משמע שצריכים להמשיך להתפלל רק מפני שאולי לא קבוע. אפשר לומר שאין קביעות כזה כל כך קובע, כיון שלא מראים אותו באופן שהוא כל כך וודאי. ותו"ת.
** על אחת -
יש לדון, שאלישע יותר היה צריך את הבית, שהיה בשר ודם. ויש לדון.
** מלאך -
נראה שהענין הוא שמראה את עצמו ללמאך שמוכרח לעשות מה שרוצה ה'.
* יא.
** אבל -
ק"ק מהי"ת שזה לא רק עושה שמותר להם ללבוש תפילין, מה שאין כן ביחזקאל שנאסר. ותחשב.
* יא:
** יום -
מעניין, שיום ולילה ואור וחשך לא ממש תלויים. ותו"ת.
* יב.
** וכי מטא -
איני יודע למה לא אמרו ברכה האחרת. מסתבר שלא היה להם זמן. אז, בין כך ובין כך יש להקשות שאולי אמרו אותו אחר כך. ותחשב.
[אגב, יש לדון למה יש דברים שהמוצא אותם יכול להשאר לעצמו, כיון שלא הול' בממון בתר רוב. כמו"כ, יש לדון למה לא חוששים שת"ח הוא הבעל, ויש לו טב"ע.)
* יב:
** צריך שיכוון -
יש לדון אם זה לכולו או רק לשני פרשיות ראשונות. לשני, יש לדון אם זה אותו שיטה שיובא לקמן או לא. נראה שאינו אותו שיטה, שלפי שיטה זו, משמע שהוא קורא (שכן הוא לשונו). ותחשב.
** כוונה -
קשה, שאף לזה אין מקור. וי"ל שרק רצה לומר שיש רק מצוות תל' תורה, ולזה רק צ' כוונה. ויש לדון. ותחשב.
** משיב מחמת מאי -
יש לדון, שהיה אפשר לומר שמשיב לכל, ולכן אמר אותו סתם. ותחשב.
* יד.
** טועם -
ע' בתוס'. נ' שתוס' גרס שמה שאין הנאה הוא הצד שמתיר. ותו"ת.
* יד:
** דבר -
לא כל כך פשוט לי למה יזכיר כל זה כלל.
** אמת -
נראה שיש יותר צד שצריך לחזור כיון שהוא כבר מחובר לדבר אחר. ותחשב.
** דאמר הכי -
אפשר לפרש שכוונתו לומר שרק אמר ככה אם כבר אמר…. אבל, דחוק הוא, ומסתמא רצה לומר שיאמר הכי….
** ותיפוק -
אפשר שגמ' לקמן ממשיך לומר שאולי לא תיפ"ק, שאולי מש"א ר"י הוא מחודש, ומח' הוא.
** ולמדתם -
ק"ק, שזה מדבר על קריאה. צריך ביאור ל"ל לומד מ"ודברתם."
* טז.
** אלו לא באנו -
שגם עזר שניהם לו, כמו שמספר בתחי' הסיפור.
** ר"ג -
היה אפשר לומר ששניהם ר"י, וכאן דם אם מותר להפתלל ארוכה או לא. ותו"ת.
* טז:
** ליטול את השם -
לשון זה קצת מוזר, וצ"ב.
** מה הנחת -
יש לציין לגמ' לעיל, שיותר טוב מירא שמים.
** תרבה גבולינו -
איפה עוד נמצא לשון זה בש"ס? בתמורה (קרוב לטז).
** קצוצי -
ע' בשבת ממה עזר לו, שלא היו מהנים קצוצי לזה, תחי' כיון שהיה לשון הרע, ושני כיון שלא היו שומרים אותו אם היה ממזר ולא נשיא.
* יז.
** לא הק' -
היה יותר אם הק' את הכל. אבל, כאן, י"ל שרק לא היו הרבה שהק' לו שלום.
* יז:
** פניו -
מענין שבכלל לא מזכיר הרחקת ד"א כאן. אולי אומרים שכל הבית כד"א. ותו"ת.
* יח.
** מי גרע -
היה אפשר לומר שגרע, שאולי גבי עצמות הוא מזיק למי שהוא, אבל גבי ס"ת, למי מזיק. ותחשב.
** כדי שלא יאמרו -
נראה ששניהם מודים לדין, אבל רק היו חוליקם (רק שאל) על טעם שלו. ותו"ת.
** שנית -
אולי הוא מפני שאתה לא מבין (שאם היית חוזר, היית מבין יותר) או שאתה לא זוכר קרא זה. ותחשב. (באמת, אולי זה תלוי באם "אם קרית," רצה לומר "אם קרית," או "אף שקרית.")
* יח:
** לא במק' שני -
מעניין, שזה לא מעלה כל כך, שהיו מאד שפלים ביותר במק' שני. ויש לדון.
** דילמא איניש -
ואם תאמר מוכרח כן ממה שלא הבינה לפני כן. וי"ל שלא איכפת להם לפני כן, עד שקרה ממנו דבר רע. ותו"ת.
