** ב. ודאית ליה -
משמע רק שאם יש מוקצה צריך להיות שיש נולד. לא מוכרח מזה שאם יש נולד צריך להיות שיש מוקצה.[fn:1] עיין בגמרא לקמן שאומר שבית הלל סובר שיש מוקצה. קשה, אז, למה צריך להניח כן. אין לומר שהוא רק אגב מה שאומר שבית שמאי סובר שאין מוקצה, שהרי על זה מקשה גמרא עד שדוחה פשט זה. עיין לקמן.
אין לומר שאין הכי נמי, לא היה הכרח לומר כן, אלא כן היה נראה לרב נחמן, שאם כן, אמורא אחר יתרץ המשנה על דרכו, ולא יאמר הנחה זה. צריך לומר שלכולי עלמא מסתבר הנחה זה של ר“נ. תחשב למה.
** ב: בשבת -
לכאורה, היה אפשר לתרץ לקושיה על ר“נ על ידי זה בעצמו (ורק על ידי זה), שמה שאמר ר“נ לת‛ הוא רק שיש סתירה אף בסתם משניות. הכוונה הוא שאז אין להקשות רק לו, אלא מוכרח שיש תירוץ. גמרא חוזר לבאר מהו התירוץ. ויש לדון, שלא משמע שידע גמרא שיש קושיה המוכרחת עד שאומר, ”מכדי….“ לכאורה, אז, צריך לומר שזה חלק ממה שאומר התרצן (שאין לומר שהתרצן רק אמר שבין כך ובין כך הוא סתירה, ואחר כך דן גמרא באותו סתירה, שהרי משמע שנקודה זה ”מכדי…“ הוא המחדש הקושיה. ותו"ת.).
** לאכילה -
היה אפשר לומר שעומד לגדל ביצים, ואין מוקצה, אלא שכבר יש סתם שאומר שיש מוקצה ביו“ט.
** מילתא דלא שכיחא -
יש להעיר שלכאורה, אף יום טוב שאחר השבת אינו כל כך שכיח. יש לדון אם הענין הוא שהוא שכיח בציורים ביו“ט או שהוא שכיח בימים. ותו"ת.
** והכינו -
לכאורה, מחודש הוא שלא רק אסור להכין, אלא אסור להנות ממה שהוכן (כיון שזה עושה שהיה הכנה). ותחשב.
** ג: ר“י לטעמיה -
נמצא שסובר כר“נ (שבלי ר“נ, כולי עלמא יודו לזה).
** אודו -
נמצא, לכאורה, שאומרים שלשון הודאה אף אם אין סברת ההודאה שווה לסברות החולק בציור של מחלקת. ואולי ”מודה ר‛…“ חלוק מ“אודו לי….“
** דרבנן -
צריך ביאור מה סובר רב פפא, שמודה שלא בטל; וקשה, שמה לנו בביטול שלו, שהרי ספק הוא, וספק מותר. צריך לומר שספק דרבנן על דבר חשוב מותר. צריך ביאור למה יהיה כן.
כעין זה יש להקשות איך אומר רש"י שמביא רב אשי ראיה ממה שלא בטל, שקשה איך יודע שלא בטל אם לא שיש לו מקור, והרי אותו מקור יהיה גם כן הוכחה לדין שאומר בעצמו, שאין נפק"מ אילו אין ספק מותר.
** ד. הובררה -
מחודש שאומרים שדבר הוברר להיות עומד. ותו”ת.
** ד: לחומרה -
יש להעיר שמברך בשם, ואם רק עושה חומרות, קשה למה לא חש לברכה לבטלה. ואולי למסקנת גמרא לא בירך, אלא אמר אותו בלי שם, ורק חשב שאמר אותו בשם בקושיה.
** וקא עבדינן -
מניח גמרא שאילו היה ספק, יהיו כשני ימים, ואילו היה תקנה, יהיה שיום אחד. אם כן, כיון שמוכיח שאינו ספק, אלא תקנה, מסתבר כרב אסי.
ההוכחה לרב הוא שמצאנו שהיו סומכים על משואות, ואז צריך לומר שאז לא תקנו רבנן, ואף אחר כן, לא נניח שתקנו רבנן. קשה מה לומד מן המשנה, שאינו אומר שלא יתקנו רבנן. נראה שאומר שלא תקנו מחמת שאין בית דין יכול להגיע להם. אולי מניח שכיון שלא תקנו על זה, צריך לומר שכשיש בעיה, לא רק תקנו רבנן שאז צריך לעולם שני ימים, אלא הוא נחשב ספק, ובכל מקום שיש לפושטו, פושטים. ותחשב.
קשה, שמצאנו שתקנו רבנן, שחששו שמא יבוא מלכות. אז, נאמר שכיון שתקנו, תקנו שהוא יום אחד. אם נאמר נגד זה, אז קשה מהו הראיה לרב אסי. ותחשב.
אם נאמר כמה שכתבנו- שדיון גמרא הוא אם הוא תקנה או רק ספק- אז מובן ראיה של גמרא גבי ראש השנה. שם, בהכרח הוא תקנה דרבנן. יש להעיר שרק רואים שהוא תקנה כשבאים מן המנחה, אבל לא אם לא באים. לכאורה, יש לומר שאל מסתבר שיהיה יותר חמור אם באים מאם לא באים, שאז אם יודעים שאינו יום טוב יותר חמור מאם הוא ספק. ויש לדון. גם יש לומר שמטעם לא פלוג רצו להשוות אותם.[fn:2]
** חבירך -
לכאורה, אינו חברו, אלא רבו. ונראה שאינו כבוד לרב, אולי, לומר שיש לו מי שעל גביו, ואז אומר עליו שהוא חבר, ולא רב.
** ה: וכי תימא -
קשה, שכבר היו מצווים על פרו ורבו. ואולי הוה אמינא שמי שרוצה להיות פרוש כמו משה יכול לעבור על צווי זה. ודחוק.
** ו. כחול שוויה -
יש לדון למה יעשו כן.
** ו: זה מוכן אגב אמו -
א“צ זה, שיש עוד סיבה שנית שאומר.
** ברייתא -
לא הבנתי, שברייתא הוא כשלא יוצא ביום טוב, אבל אולי אומר שמותר כשנגמר לפני יום טוב, ואסור אם לא נגמר, אבל רק אם יוצא. לא נראה, שאז לא מוסיף כלום.
** אלא הא -
מניח שלא ירצה לומר שאין הלכה כשני הברייתות, אף שהיה יכול לומר ששניהם אותו תנא ששיבש (או חלק על) מה שאמר רבי. ותו"ת.
** ומגדלת -
לשון גמרא ורש"י בביאור דינו מעניין, שמשמע שהחידוש הוא שרק זה מגדל, אבל באמת חידושו הוא שכשאומר לשון זה, מכוון לביצה שמגדל. ותו"ת.
היה אפשר לומר שמשמיע מה מוליד, וכשמקשה גמרא שם ”פשיטא,“ אינו מקשה על דין זה, אלא על דין של רבי אמי, ולמה היה צריך לומר כן, שהרי כבר היה ידוע שאינם מולידים. יש לדון, שאולי מורה שאין מולידים. ותחשב על זה.
** ז. נולד בין ביום -
יש לדון אם תלוי עדיין מתי אמו שימש באותו זמן שנתעבר או לא. ותו"ת. (הנחתי ש“תשמיש“ רצה לומר ביאה, אבל אינו מוכרח כן, שאפשר שמשמע שאז נעור.)
** ז: מיצרא -
עיין כעין זה בב“ב גבי לימוד תינוקות.
** אימא מאתמול -
מניח שספיקו מותר. על“ע, שחלקו בזה. שו“ר בתוס‛ כאן (ונראה שלזה מכוון רש"י).
** קל וחומר -
ואם תאמר אין מזהירים מן הדין. ויש לומר ששאור הוא אותו דבר של חמץ, אלא שיש לו חימוץ יותר, והיה עדיין נכלל בכללו. עיין בגמרא מנחות ופסחים שדנים בזה. גם יש לומר שרק דן למה צריך קרא לשיעורו, ולא למהו. וצריך לעיין בקראי בזה.
** לענין אכילה -
לא הבנתי (ואולי צריך לעיין בקרא), שנראה שבאכילה ובראייה, יש קרא שאומר שאור וקרא שאומר חמץ. אם כן, צריך ביאור למה באחד אומרים שהם ששיעורם שווה, ובשני אומרים שאומר ששיעורו חלוק לבית שמאי. נראה שבראשון אומר שניהם על צווי אחד, ואז יותר כולל אותם לחד כלל. ותחשב.
** צריך ביאור
למה צריך קרא לכלל שאר וחמץ בחד קרא, שכבר פשוט שיש להם אותו שיעור.
** ח: תסתיים -
לכאורה, רצה לומר שאם אחד הוא רבא, נתסיים…. לכאורה, לא אומר שנוכיח מזה שהאחר הוא רבא, ולא אביו, שהרי אפשר שיש אחר שסובר כרבא בזה. אולי אומר שכיון שיודעים שרבא יש לו שיטה בזה, היה להם להביא דעת רבא. ודחוק, שרגיל ת“י שלא להביא דעת רבא.
** דבהדי -
ק"ק ל"ל חוששים שלא יעשה כך (כמו שחשו שיכוש, אף שהיה אסור).
** צואה… רבא -
מניח גמרא שאם חושש לספק, ואז מכניס עפר, חושש לכל ספק.
** ט: לא אמר -
רצה לומר שאולי אין מח‛ אלו תלויים על זה, שאולי אין צד השווה במחלוקתם, שהצד יהיה או כמה חמור איסורו יו“ט או כמה טוב הוא שמחת יו“ט. אולי כאן לא חולקים בזה, אלא חולקים בדיני מוקצה או כדו‛.
** מוחלפת -
יש לדון ממה מוחלף מה שאומר כאן:
1. מוחלף ממה שאומר במשנה אחר.
2. מוחלף משיטתו האמיתי.
יש חילוק- אם יכולים לומר לשון זה על שני המשניות. ותו"ת.
גם יש להעיר שלולי רש"י היה יכול לומר שאומר שמוחלפת השיטה מזה, שאין השיטה (של משנה אחר או שיטה אמיתי) זה. עיין ברש"י כאן, שלא פירש כן.
** י. כולם טמאים -
נמצא שמניחים שמה שהוא טמא אינו רק מה שיהיה הדרך שממנו יצא, אלא מה שיכול להיות אותו דרך. ותו"ת.
** אף משימות -
קשה איך, אז, יהיה דין ראשון נוגע, שלכאורה, לעולם חושב לבסוף להוציא בפתח אחד. אולי נוגע אם יוצא מקצתו מפתח זה ומקצתו מפתח זה. ותחשב.
** י: אתי לאמנועי -
עיין ברש"י. משמע שהוא בעיה של מוקצה. לולי זה, היה נראה לדייק מלשון ”אתי לאמנועי“ שחוששים שלא ישמח ביופ טוב, ואז אין ב“ש חולקים מחמת דין מוקצה, אלא מחמת חשש לשמחת יום טוב.
יש להעיר שאם חוששים בית שמאי לדין מוקצה, יהיה קשה על ר“נ בתחילת מסכתא. ותחשב.
** הא איכא חד -
משמע שספק מוקצה אסור.
** שלש -
יש לדון למה לא אומרים שכשם שאחד יצא, כך שנים אלו יצאו:
1. אולי לא כל כך מסתבר שכולם יצאו.
2. אולי לא יכולים להניח שאחרים באו כיון שלא רואים שום באים. ותחשב.
** בדף -
מעניין שזה מהני, אף אם אין שם כשיוצא. ואולי מיירי בשיש שם. סתום הוא, אז.
** יש לדון
אם מצא אותם גוזלות שמצא קשורים. אם נאמר שהיו קשורים, לכאורה, זה היה ראיה שהם אותם גוזלות. אם לא, צריך לומר שמניחים ששחררו את עצמם.
** יא. כיון ששחטה -
לא הבנתי, שאולי יחתוך בתברא אחר, שלכאורה, הענין הוא שחש על אותו תברא. ותחשב.
** יא: דאין בנין -
על“ע, שכן אמר גמרא. ואולי הוא צירוף.
** יב. הותרה -
לכאורה, זה מוכיח שאוכל נפש דוחה איסור יום טוב, שאם האיסור הוא רק הותר, איך נאמר שמגו התירו ידחה איסור שני שבת. יש שני דרכים לדחות את זה:
1. אף מלאכה שלא לצורך הותרה (אין סיבת האיסור). ויש לדון, ש“מתוך…“ לא משמע כן, שלכאורה, לא יודעים למה לא יהיה סיבת איסור. ויש לדון, שאולי יודעים שענין מלאכה הוא דבר שנגרם בזהירות על כל כלל המלאכה.
2. היתר יכול להיות סיבה לדיחוי (רצה לומר, מה שאין סיבת איסור, או מה שאין איסור, על הכל עושה שלא יצווה תורה על שאר, ואולי מחמת לא פלוג או כדומה). ותחשב.
עדיין יש לדון צריך צורך קצת. וצריך לחשוב על כל זה. שוב ראיתי שרש"י אומר שהוא רק גזירה. אם כן, אין להוכיח ממנו כלום.
** יג: הואיל ויצא -
קצ“ב מה מוסיף.
** יד. מוריקא -
נראה שהחולק יסבור שאף שחייב אדם לדעת מה יאכל, ואז אף על מוריגא אוסר.
** יד: רב פפי -
יש להעיר שמיד אחר שאומר גמרא שאין לחוש בבבל, מביא מעשה בבבל של אותו חשש. נראה שאולי מכוון לומר שרק בבית מר שמואל היה כן, ומשמע שבשאר מקומות, לא היה כן. ותחשב. (ועוד שללשון ראשון, רק מפני שראה חשש. ודע שאפר לנו לדחות שלשון שי הוא כתירוץ ראשון של גמרא, שלא אומר שעבידם הם טובים בחו“ל מבא“י.)
פריצותא- לכאורה, ר"ל שעוברים על דין תורה. לשון ”פריצותא“ מעניין. ותחשב.
** טז: לדידך -
צריך ביאור למה לא יכוון להם, שכיון שסומכים עליו, נמצא שאינם פושעים. וי“ל שיותר טוב לעשות עירוב לעצמו. ותחשב.
** יז. בזמן שהתנור מלא -
משמע שצריך להיות יותר טוב כשמרבה במלאכה. יש לדון, אז, מהו יותר טוב אם יש יותר מים. ותחשב.
** יז: תקנתא -
לכאורה, אומר שהוא ”דאי.“ (ויש לדון אם אף צריך לזה, שאולי אף בלי כלל זה, אין זה נכנס למה שכוון תנא לומר, שרק כוון לומר אופנים מותרים. ותו"ת.)
** דאית ליה -
יש לדון הגדר של זה, ואם צריך כאן שממש יתענה. ותחשב.
** יח. וכיון דלית ליה -
יש לדון ל"ל אומרים כן גם גבי כלי, שממה שטובל כלי זה, צריך לומר שאין לו כלי אחר, ואז שומר עליו שלא יטמא. ותחשב.
** לית ליה -
יש לדון אם מוכיח ממה שמותר להשיק או ממה שרוצה להשיק.
** בולד -
לא הבנתי, שאם החשש הוא שמא יעבר ד“א, מה לנו כמה טמא הוא. ותחשב. ואולי אותו חשש של ד"א הוא רק בשבת, שביו“ט הותרה הוצאה (”מתוך“).
** יח: בימות הגשמים -
לכאורה, יהיה נמצא שבימות הגשמים במים רעים לא יהיה מותר. ואולי לפעמים יהיו יותר נקיים ממנו.
** מלוכלך -
יש להעיר:
1. מוזר שיהיה מלוכלך כך בשבת.
2. מוזר שלא יראו שלא מלוכלך. ואולי צריך להיות מלוכלך.
** הדר ביה -
יש לדון, אז, למה אינו אחד מן היע“ל קג“ם. אולי הוא מפני שחזר בו רבא. אם כן, צריך לומר שאף כשיש תיובתא לא חזר בו (ואולי לא שמע את התיובתא). גם יש לומר שחזר בו קודם שדנו עליו בבית מדרש. ותחשב. גם יש לומר שחזר בו מסברתו, ולא מברייתא. גם יש לומר שחזר בו מסברתו, ולא מקושיית אחר.
** יט. תנאי שקלת -
יש לדון איך לפרש את זה:
1. אם היית אומר שהוא מחלקת תאני, אטו שקלת תנאים מעלמא- אטו בראת תנאים מאפס.[fn:3]
2. אטו כל התנאים תטלו מן העולם עד שלא נדע שזה כבר מחלקת תנאים.
** הואיל -
יש לדון למה מקילים בהואיל, ולא מחמירים.
** כ. תלמיד אחד -
לכאורה, אף היה רב יוחנן החורני (סוף פרק ראשון של יבמות). אולי היה אחר בת קול (תלוי, לכאורה, בחשבונות של אותו סוגיה, אם הוא אחר בת קול, או לפני בת קול. ועיין בשיח שי.
** כ: אינו דין שמותר -
לכאורה, נאמר על זה דיו.
** במאי קמפלגי -
לכאורה, אין הכרח לזה, שיש לומר שחולקים אם אמר בית שמאי כן, או הבינו מדעתם מה ישיבו בית הלל. ויש לומר שלא היו שני התנאים משנים מהדדי אילו לא רצו להגיד לנו דבר. ויל"ד.
** כא: רבא -
לכאורה, לא היה מר שמואל שמואל, או לא היה רבא רבא סתם, שלכאורה לא ראה רבא את שמואל, שחי אחר רב הרבה שנים. ותחשב.
** לא יחם -
לכאורה, זה מחלקת של ”מתוך“שאמר לעיל. קשה לצד שאמר לעיל שאולי לא חולקים במתוך. באמת, גם צריך ביאור למה צריך שני מחלוקות במתוך. ותחשב.
ונראה שהיה אפשר לומר שכאן חולקים אם זה נחשב עונג של יום טוב. אם חולקים לעיל במתוך, צריך ביאור למה צריך בית הלל להודיע כן. אולי מחדש שנחשב צורך כלל.
** מדורה -
צריך ביאור למה יאמר כן בית הלל, שכבר השמיע לנו אבר אחד. יש לומר שאולי הנאת אבר אחד בחמים יותר טוב מכל גופו במדורה. גם יש לומר שהוא זו ואצ“ל זו (ואולי אף להודיע שבית שמאי חולקים. לא נראה כן, שאם כן לכאו‛ היה לו לתנא להיות יותר בהיר כשאומר מי אמר זה.)
** כב. חנניה -
מסתמא, רבא ישיב שכמו שחזקיה חולק על רבנן בשיטת בית שמאי באם יש תבשיל אחד, אם מותר לאפות, כך חולק בזה. נראה שאביי לא רצה לומר כן כיון שראינו שחזקיה מחמיר. ותחשב.
** אין בנין בכלים -
לכאורה, זה לשיטתם (אולי, ותלוי בביאור גמרא לעיל. לכאורה, לביאור אחר הוא נגד שיטת בית הלל שם; וצריך לחלק בין כלים גדולים לקטנים או כדומה.) במה שאומר לעיל בחלונות של חנויות.
** הכלי -
קשה, שזה יכבה אותו. אולי ר"ל כלי שיש בו אויר. אף שאור יצא, אולי לא יצא אור די לאסור. גם יש לומר שרק גרמא הוא, ואז מותר.
** אפשר -
ק"ק ל"ל אומר שאפשר לעשות כרבי ולתת על עצמו דבר כדי שלא יראה.
** מסייע אין בו ממש -
ק"ק, שלכאורה לא אומרים כן במקיף וניקף. ואולי הוא מפני שיש שם לאו מיוחד. לא נראה כן, שאולי הוא לאו שאין בו מעשה. אולי לא כל כך מסתבר לתורה לתת לאו בלי מעשה. דחוק.
** כה: רעבתן -
יש לדון אם אומר שנראה כרעבתן או שלא היה רוצה לראות כן או לעבור אם לא שלא יכול לעמוד על עצמו שלא לאכול. אם כן, צריך לומר שהוא רעבתן. ותחשב.
** למר שמואל -
היה אפשר להביא ראיה מכאן שהיה רב נחמן בר יצחק תלמיד של שמואל (או, על כל פנים, חי בזמנו), ואז שייך שהיה רבו של רבא, ורב נחמן סתם. יש להעיר שאולי אין מר שמואל שמואל. יש לציין לגמרא לעיל יד: וכא:, ששם מבואר שאולי מר שמואל אינו שמואל. אבל, גם יש לציין לרש"י ב"ב קמט. גבי בנות של שמואל, שקורא לשמואל מר שמואל. ותחשב.
ויש לציין לגמרא (ב“מ, אני חושב) שאומר שרב נחמן בר יצחק היה בן של סופר בבית שמואל.
** כז: כל מום -
מעניין, שאף ש“כל“ קאי על מום, דורשים אותו על נתינות חלוקים. אינו כל כך מוזר, שאף זה קרק‛ של מום. ותו"ת.
** כט: סכום מדה -
יש לדון אם זה שמזכיר, ”על הכל, צריך אני כור אוכלים,“ או שאומר, ”על הכל, צריך אני קב מזה, וקביים מזה….“ (אלא מזכיר צריך אני קביים מזה. גם צריך אני קב מזה…). ותחשב.
לכאורה, מוזר להזכיר הראשון כלל, שלמה אדם יסכם כך. אז, נראה כשני. אבל, מעניין שיש לחלק בין אמירה בדרך זה לאמירה בדרך אחר (שכתבנו בתוך הפארינטיטיים). אז, צריך ביאור.
* Footnotes
[fn:1] גם לא מוכרח שאם אין נולד, אין מוקצה, אלא שמן ההוה אמינא של גמרא נראה שנולד יותר אסור. אז, לא נראה לשנות כל כך מן ההוה אמינא. אבל, ענין ראשון שכתבנו הוא, להיפך, שינוי יותר קטן. ותו"ת.
[fn:2] ועיין ברש"י שקצת משמע שאולי אין הכי נמי בירולשיםי דין זה רק בבאים אחר מנחה, וגמרא רק בא לבאר דין של בני בבל, שלא ידעו, וצריכים לחוש שבאו אחר מנחה. יש לדון למה אין אומרים שזה ספק דרבנן (ומסתמא אף מיעוט לומר שכן קרה).
[fn:3] אז, לשון מעלמא הוא כמו ”מעלמא אתו,“ שהוא ”ממקום אחר.“ ותחשב.
