** ב. קס“ד -
עיין במה שבאר בדעת רבי שמעון. אם כן, לא חולקים בדין מוקצה, אלא חולקים אם הוא מוקצה. כן שממע מלשון גמרא של ”אית ליה“ או ”לית לה“ מוקצה. יש להעיר שמה שאמר רש"י הוא רק בהוה אמינא; יש לדון מהו המסקנא של רב נחמן:
1. אולי הוא שדעת אדם הוא אף על מה שנולד, אלא שאי אפשר להשתמש בו בע“ש, כיון שהוא אז אינו בעולם. אם כן, הוא דומה לדבר מוקצה.
2. אולי אין זה יסוד שיטת רבי שמעון, אלא סובר שאף שאין דעת אדם עליו כל כך, אין איסור. אם כן, אף כאן, אף שלא חשב עליו כלל, כיון שלא הקצה בידיים, אינו אסור.
מה שדייקנו מלשון גמרא של ”אית ליה“ ו“לית ליה“ לא משמע כפשט זה.
** ואמר ר“נ -
אלא כך שמעתי- עיין לקמן ברש"י שכש‛ שעשה כן כדי שלא נקשה הלכתא אהלכתא. אין שני טעמים אלו סותרים אהדדי:
1. אולי כך שנה לו רבו לתרץ לאותו קושיה. עדיין ק"ק איך נדע שלמד כן מרבותיו, ולא שאמר כן מדעתו.
2. אולי זהו גופא השינוי של מסקנת גמרא, שהוא שאמר כן רק מפני סתם משנה שמוכיח כן, שהוה אמינא רק לא הניח כן מפני שלא ידע את הסתם משנה.
** ב: מאן סתם -
במש“כ ששנה בשם רבים כדי שיהיה נראה כאילו רבים אמר כן, נראה שיש לציין לגמרא בגיטין שעשה כן אחד לשיטת רבי. נראה שעשה כן כיון שידע שרבי עושה כן. ותחשב.
** ולא אתי -
לשון רש"י קצת מעניין, שלכאורה, אין הענין שכיון שמקלים בזה, יקלו בדרים אחרים, אלא שכיון שלא מחמירים בזה, אין דבר שיכריח אותם להחמיר בזה[fn:1]. ויש לדון.
** דהתירא -
לכאורה, יש דרך אחר לבאר, והוא שאילו לא היינו יודעים שהוא מחמיר, נניח להחמיר, אבל אם לא יודעים שהוא מקל, אל נקל, אלא נחמיר. ויש לדון, שזה רק בדינים דאו‛. ויש לדון, באמת, למה סברת רש"י נכון גבי דרבנן בכלל. וצריך לומר שכשיש לתלמיד חכם ספק בסברה, לא מקל בדרבנן. זה מחודש. ואולי הענין הוא שאם חשב, ולא פשוט לו להקל, ולא עיין כל צרכו, אין להקל, אף בדרבנן. ותחשב.
ויש להעיר שאולי לא אומרים אותו בדרבנן, אלא שכאן, כיון שספיקו אסרו, כמו שיאמר לקמן, אומרים כן. ועיין שם.
** והתניא -
יש לדון למה נוקים אותו כן כדי להקשות ממנו. ואולי בלי זה, הוא פשוט. גם יש לומר שידע גמרא על מה קאי. ודחוק.
** ג. מתנה -
במק“א, הערנו שאין צורך לתנאי שני, שיכול לעשר, שאם הוא יום טוב, כבר חל מעשר, ואינו טבל.
** ג: אפילו באלף -
ע‛ במש“כ שהוא מדרבנן. יש להעיר שיש שני ענינים[fn:2]:
1. ביטול ברוב.
2. כל דפריש מרובא פריש.
לכאורה, החילוק הוא שראשון הוא רק אם יש חפץ שאינו כל כך חשוב בתערובת. שני הוא לעולם. ראשון הוא אף בקבוע.
לכאורה, קרא של ”אחרי רבים“ אומר שבספק, יש לנטות אחרי רבים. אם כן, זה לכאורה, אומר כלל שני. אז, קשה מהו המקור שמדאורייתא בטל ברוב.
** אפילו באלף -
לכאורה, זה אומר שאף בביטול, יש קצת ס“ר.
** ד. גוזמא -
משמע מרש”י שחולק על בית הלל. יש לדון, שאולי רק סובר שלא חולקים בזה. אולי כן כוונת רש”י, ורצה לומר שחולק על בית הלל של משנתינו.
** ד: ונתקלקלו -
יש לדון מה אומר לבאר למה אין שחרית בעיה. משמע שהענין הוא שלא תקנו שום שיר בשחר כלל, שלא לעולם באים אז. אם כן, קשה למה לא רק מתקנים שלא לעשות שיר לשל בין הערביים גם כן, ואז אין לנו בעיה. אולי כיון שכבר נתקן, קשה יותר לסלק אותו. ותחשב.
לולי רש"י, היה אפשר לומר שיש אותו בעיה בשיר של שחר, אלא לא יוכלו לתקן כך, שאז בכל שנה הוא שני ימים, ורצו שיהיה השנה כראוי ברוב שנים. ותו"ת.
** ה. כרם רבעי -
יש לדון למה חוץ מעיר אחד אין חייבים:
1. לא יהיו הפירות כל כך טובים כשבאים.
2. הוא טורח להם להביאם.
** עיין במה
שכ‛ רש"י לבאר למה בחו“ל עדיין אסור. צריך ביאור קצת, שמרש“י לעיל היה משמע שלא היה שום תקנה לענין חו“ל, אלא שתקנו שלא לקדש, אלא לנהוג שני הימים מחמת ספק, וכיון שאולי זה קרה, ואז היה תקנת רבנן שייך, חוששים מספק בבבל. אז, כיון שלא חוששים לזה בא“י, לא נחוש לו בבבל. ותחשב.
** ו. דאיכא חברי -
רש"י משמע שחוששים מלקבור. לולי זה, היה אפשר לומר שרק קאי על מה שהוא כחול ממש.
** דאיכא -
ואם יראו- יש לדון מהו החשש:
1. לא יבינו שיש חילוק בין אם יש צורך לאם אין צורך. אז, יכוף אותנו.
2. יבינו דין כשיש צורך, ואז יעשו שיש צורך על ידי כפייתם.
** הטרפה -
ירך אמו- עיין במקום אחר שכתבנו צד שאיסור טרפה הוא שאופן מיתתו אינו טוב, שאין שחיטה עושה כל כך. אם כן, לכאורה היה לו לרש"י לומר כן כאן, שלא קרה שחיטה, ולכן אסור, ולא מפני שהוא ירך אמו. לא נראה כן, שנראה שצד זה אומר שאותו שחיטה היה שחיטה כשורה, אלא רק פסול כיון שלא היה אותו שחיטה מה שהמית אותו. אם כן, לעובר, שהיה מה שהמית לו, יכשר. ותו"ת.
באמת, אם אין האיסור בא ממה שהוא טרפה, אלא ממה שאין בו מיתה כראוי, יש לדון אם נאמר שעובר ירך אמו, שכאן האיסור רק בא במיתה, צריך לומר שעובר ירך אמו לאחר מוות. ואולי רק רצה לומר שסיבה שאין שחיטה בא מזה לזה, וכמו שנחשב זה כבר מת קצת, כך זה נחשב כן. לא נראה מסברה. ותחשב.
** ז. ספנא -
ולקמן- ראה שאומר כן לבאר איך יהיה ידוע איזה מין הוא איזה.
** ז: דשמעה -
גם היה אפשר לפרש ש“ביממא“ רצה לומר מה שקורא כשבא יום. אולי זה יותר נשמע. ותו"ת.
** דרבי יוחן -
שכיח טפי- ק"ק, שאצ“ל טפי, אלא שווה, כמה שאמר ד“ה אימא. ואולי בא לבאר לשני השיטות (שיטה שמתיר ספק ושיטה שאוסר. ותו"ת.).
** שיעורו -
הל“מ- קשה, אם כן, למה צריך קרא. אולי רצה לומר שכל היכולות של שיעורים הם מהלכה למשה מסיני.
** והא קעביד -
ואם תאמר ל"ל בא עשה לדחות לאו. ויש לומר שהוא לאו ועשה כמו שאומר לקמן.
** ח: ודאי נמי -
לולי רש"י, היה אפשר לומר שגמרא אומר שלא גוזרים מחמתו כיון שהוא מותר. אז, לא רק לא גוזרים מחמתו, אלא מתירים אותו.
מרש"י, נראה שלא גוזרים מחמתו, אבל הוא אסור, שאומר, ”שאי נמי כותש….“ גם יש להעיר על לשון ”אין איסורא דאורייתא“ שאומר. צריך לבאר באיזה ציור דנים:
1. אם אפשר לקיים שניהם- אז, קשה למה לא יחייב לקיים שניהם. משמע שרש"י סובר שכשאפשר לקיים שניהם, יש עדיין קצת דחייה.
2. אם אי אפשר לקיים שניהם- קשה למה לא יבוא עשה לדחות לאו. אולי יודע שהוא לאו שיש בו עשה, ורק סובר שאף שהוא אסור, אין האיסור כל כך חמור. ותחשב.
** הא -
על זו- עיין בב“ח. לכאורה, זה תלוי באיזה משנה. יש להעיר שלכאורה, לא יכול לשנות משנה ראשונה של הפרק, שכל המשנה דן בהכרח בקולותיו של בית שמאי. אז, צריך לומר שמקל שם. ויש לדון, שאולי זה רק רישא של משנה, אבל שאר חלקי משנה הם כעין שאר שמניות של הפרק. ותו"ת.
** יב: מתנות -
לא הבנתי מה אומר באיסור אכילה, שלא אוכל מתנות, אלא שאר הבשר. ותחשב.
** יג. קנסא -
יש לדון אם הלוי עובר על הלאו או המעשר (או שניהם), ולוי רק עובר על לפני עוור. ותחשב. לכאורה, אין כאן לפני עוור, שאינו בתרי עברי נהר. אולי, אז, הוא רק גורם איסור. ותחשב.
** יד. תרתי -
לא זה דומה- ק"ק, שלכאורה, מפרש שמקשה שחולקים, ולא שאין דומים. ואולי כן כוונתו.
** תרתח -
נראה שרש"י מפרש שמקשה גמרא שהם תרתי, והוא שהם שני דברים, ולא אחד, שאינם שווים, אלא חולקים, ואז הוא סתירה. לולי זה, היה נראה לומר שאומר כן בלשון תמיהה, ומהקשה, ”אטו תרתי נכונים,“ ששניהם סותרים זא“ז. ותחשב.
** יד: אף לא -
דרכו- מרמז למה שיבאר גמרא לקמן במחלקת ר"י ור“י.
** טו: תחלת -
ע‛ במש“פ. לולי זה, היה אפשר לומר שצריך שאין זה תחילת בישולו, שכבר בשל עירוב תבשילין.
** יז: ואם איתא -
נמי- לולי רש"י, היה אפשר לומר שמקשה לומר רק תקנה זה של איסור, כיון שהוא קל ביותר. ויש לדון אם הוא קל ביותר, שיש בו איסור.
** יח. דלא שכיחא -
נראה שאפשר שאומר כאן שני דברים, שלא שכיח כיון שאין כל כך חפצים טמאים, ועוד שזהיר מלטמא אותו. ותחשב.
** כ. נזיר -
עיין במה שבאר. לולי זה, היה נראה לומר שהוא מפני שאין אדם מתנה על מה שכתבו בתורה. ותחשב. ולפי רש"י, צריך ביאור ל"ל אומרים כן בכל שיור. ואולי לעולם צריך להפך הלשון.
** כג. אלמלי תודוס -
אומר כמסקנת גמרא בפסחים.
** במאי -
יש לדון אם חלק מן הגי‛ היה ”כולה לישנא,“ ואמור שלא לגרוס אותו הוספה, או כל זה, או אם אומר שמילים אלו כל גירסא לא גורס. ותחשב.
** כג: טמאה מדרס -
עיין איך באר. לולי זה, היה נראה לומר שמחדש שהוא סומך עליו, וכיון שהוא סומך, נמצא שהוא מושב, אם הוא זב. אולי גם רש"י סובר שזה החידוש, ורק בא לתרץ קושיה (ואגב זה גם מסלק קושיה אחרת שיכול להימצא).
** כה: כדתניא -
משמע שבא להוכיח שראוי לשנות דינים אלו. גם היה אפשר לומר שמוכיח שראוי להקפיד על אלו.
** כו. אם יש בו -
יש להעיר שגמרא דן מה סובר רבי בענין מוקצה, ולא מביא ראיה מזה.
** אמר ליה הרי אמרו -
עיין במה שמפרש רש"י. ק"ק למה אומר לשון רבים, שלכאורה רק מכוון לאחד (רבי שמעון).
** כו: אדא בר אוכמי -
גם היה אפשר לומר שכשסבר שאין המשנה נכון, היה משבש אותו, לומר שבהכרח הוא משובש, והיה משנה מה אומר. ויש לדון, שאולי לשון משבש לא משמע כן. גם יש לומר שלא מסתבר שיש מי שיעשה כן מדעתו. ונראה שאין מסתבר שמי שיעשה כן ישנה משניות, שמה ילמד לו משניות, שהוא משנה את המשנה אם לא מודה לו. ויש לדון, שאולי המשנה מעורר לו דברים, ואחר ששומע אותם הוא מודה להם. ויש לדון.
** כז: ופרטיה -
שלעולם הוא ניכר- לכאורה, רש"י מבאר בזה למה נחשב מום, והוא שמום הוא דבר רע שניכר. ותחשב.
** כט. בסורא -
יש לדון אם אלו הם שיעורים שווים עם שמות חלוקים או שיעורים חלוקים (ולכן יש להם שמות חלוקים).
** כט: כל שכן שאסור -
לכאורה, ר"ל שיותר יש סיבה לאסרו, שיותר נראה כאותו אב. ואם תאמר הרי אף נראה כמרקד, שהרי רואים שהאבן נשאר. ויש לדון, שבדרך כלל, לא מרקדים רק לאבן אחד. אז, לא נראה שהוא מרקד. גם יש לומר שכיון שלא רואה מה יוצא ומה נשאר כל הזמן, אלא מזמן לזמן רואה. כיון שרק נשאר אבן אחד, מסתבר שלא יראה. ותחשב על זה.
* Footnotes
[fn:1] הראשון משמע זה הדבר שגורם שיקלו. השני משמע שמקלים כיון שהם אינם בני מצוות, ובאים לידי זה כיון שאין חומרא. ותו"ת.
[fn:2] זה מבואר מגמרא בזבחים (עיין בסוגיית ביטול שם).
