גמ’ בבכורות (יג.) מביא בריי’ שקשה להבין. הבריי’ מדבר בישראל שקונה עבודה זרה מגוי. הרי, עבודה זרה אסורה בהנאה, ואם קנה אותו, אסור למכור אותו לגוי. במשנה זה, הדיון הוא אם לא קנה, ואז יכול לחזור בו ולקבל את מעותיו, או קנה, ואז לא יכול לחזור בו, כי זה רק נעשה על ידי מכירה לו, ונמצא שנהנה מע"ז.
המשנה:
הלוקח גרוטאות מן העובד כוכבים ומצא בהן עבודת כוכבים:
1. אם עד שלא נתן מעות משך יחזיר (נקרא לזה רישא)
2. ואם משנתן מעות משך יוליך הנאה לים המלח (נקרא לזה סיפא).
הביאורים:
יש שלש ביאורים לבריי’ זה:
ביאור אביי:
קונה מגוי במשיכה. (יכול להיות שני סיבות לזה. סיבה ראשונה הוא שכן הוא הדין, שקונים מישראל (מן התורה) בכסף, וכ’, “עמיתך" למעט גוי, לומר שמגוי רק קונים במשיכה. סיבה שנית הוא שדנים בציור שקבלו עליהם לדון בדיני ישראל[fn:1].[fn:2]) אז, נפרש רישא וסיפא:
1. אם עד שלא נתן מעות משך יחזיר, כיון שהוא מקח טעות.
2. אם משנתן מעות משך לא יחזיר, שכיון שנתן מעות, היה לו לעיין על זה אם מקפיד.[fn:3]
ביאור רבא:
קונה מגוי במשיכה. (יכול להיות שני סיבות לזה. סיבה ראשונה הוא שכן הוא הדין, שקונים מישראל (מן התורה) בכסף, וכ’, “עמיתך" למעט גוי, לומר שמגוי רק קונים במשיכה. סיבה שנית הוא שדנים בציור שקבלו עליהם לדון שמשיכה קונה.) אז, נפרש רישא וסיפא:
1. אם עד שלא נתן מעות משך יחזיר, כיון שהוא מקח טעות.
2. אם משנתן מעות משך לא יחזיר, אף שהוא מקח טעות, כיון שבנתינת הכסף עם משיכה[fn:4], נ’ כקונה ע"ז.
ביאור רב אשי:
לא קונה מגוי במשיכה. (יכול להיות שני סיבות לזה. סיבה ראשונה הוא שכן הוא הדין. אולי המקור לזה הוא שקונים מישראל במשיכה (שכ’, “יד ביד"), וכ’, “לעמיתך,” למעט קנין מגוי, ואולי המקור לזה הוא רק שאין מקור לקנות במשיכה (שאף שישראל קונה בכסף, וכ’, “לעמיתך,” זה בא למעט גוי מאונאה). סיבה שנית הוא שקבלו על עצמם לדון כאילו משיכה לא קונה.) אז, נפרש רישא וסיפא.
1. אם עד שלא נתן מעות משך יחזיר, כיון שלא עשה בו קנין.
2. אם משנתן מעות משך לא יחזיר, כיון שקנה אותו. וא"ת למה אומר שמשך. וי"ל שהוא אגב רישא.
* Footnotes
[fn:1] נמצא, לכאו’, שקבלה זו עושה שקנין תלוי במשיכה.
[fn:2] גמ’ אומר שקבלו על עצמם לדון בדיני ישראל. אף אם נאמר שמשיכה לא קונה מדאו’ בישראל או בגוי, נוכל להוקים את המשנה כן, כיון שקונה מדרבנן. נ’ שאף בלי זה היה אפשר להוקים את המשנה כן, שיקבלו על עצמם שמשיכה קונה, אף שאין דין של אף אחד כן.
[fn:3] לכאו’, זה מוכיח שענין של מקח טעות אינו שאין חלות המיוסד על טעות חל, אלא הוא שתקן תורה שלטובת לוקח, לא יבוא לו רע שלא היה יכול למנוע. ויש לדחות שממה שלא בדק, צריך לומר שלא מקפיד.
[fn:4] גמ’ לא מזכיר נקודה זו, אבל נראה שצריך אותו, שאם לא כן, קשה למה מזכיר משיכה בסיפא. בין אם משך בין אם לא משך לא קנה, שהרי מקח טעות היתה, והכל תלוי במה יחשוב הרואה.
