1. פרק ראשון[fn:1]
משנה א[fn:2]
[fn:3]הכל שוחטין[fn:4] ושחיטתן כשרה[fn:5], חוץ מחרש שוטה וקטן, שמא יקלקלו[fn:6] בשחיטתן. וכולן ששחטו ואחרים רואין אותן, שחיטתן כשרה[fn:7][fn:8].
שחיטת נכרי[fn:9] נבלה[fn:10][fn:11] ומטמאה במשא[fn:12].
השוחט בלילה[fn:13], וכן הסומא ששחט שחיטתו כשרה[fn:14].
השוחט בשבת[fn:15], וביום הכפורים[fn:16][fn:17], אף על פי שמתחייב בנפשו[fn:18][fn:19], שחיטתו כשרה[fn:20].[fn:21]
משנה ב[fn:22]
השוחט במגל יד[fn:23], בצור[fn:24], ובקנה[fn:25] שחיטתו כשרה.
הכל שוחטין[fn:26] ולעולם שוחטין[fn:27], ובכל שוחטין[fn:28], חוץ ממגל קציר[fn:29], והמגירה[fn:30], והשינים[fn:31], והציפורן[fn:32], מפני שהן חונקין[fn:33][fn:34].
השוחט במגל קציר[fn:35][fn:36] בדרך הליכתה- בית שמאי פוסלין[fn:37], ובית הלל מכשירין[fn:38].
ואם החליקו שיניה[fn:39], הרי היא כסכין.
משנה ג[fn:40]
השוחט מתוך הטבעת ושייר בה מלא החוט על פני כולה, שחיטתו כשרה.
רבי יוסי ברבי יהודה אומר, מלא החוט על פני רובה.
משנה ד[fn:41]
השוחט מן הצדדין -- שחיטתו כשרה.
המולק מן הצדדין -- מליקתו פסולה.
השוחט מן העורף -- שחיטתו פסולה.
המולק מן העורף -- מליקתו כשרה.
השוחט מן הצואר -- שחיטתו כשרה.
המולק מן הצואר -- מליקתו פסולה,
שכל העורף כשר למליקה, וכל הצואר כשר לשחיטה.
נמצא, כשר בשחיטה, פסול במליקה. כשר במליקה, פסול בשחיטה.
משנה ה[fn:42]
כשר בתורין -- פסול בבני יונה. כשר בבני יונה -- פסול בתורין.
תחלת הציהוב בזה ובזה -- פסול.
משנה ו[fn:43]
כשר בפרה, פסול בעגלה. כשר בעגלה, פסול בפרה.
כשר בכהנים, פסול בלוים. כשר בלוים, פסול בכהנים.
טהור בכלי חרש, טמא בכל הכלים. טהור בכל הכלים טמא בכלי חרש.
טהור בכלי עץ, טמא בכלי מתכות. טהור בכלי מתכות, טמא בכלי עץ.
החייב בשקדים המרים, פטור במתוקים. החייב במתוקים, פטור במרים.
משנה ז[fn:44]
התמד, עד שלא החמיץ, אינו ניקח בכסף מעשר, ופוסל את המקוה. משהחמיץ, ניקח בכסף מעשר, ואינו פוסל את המקוה.
האחין השותפין -- כשחייבין בקלבון, פטורין ממעשר בהמה. כשחייבין במעשר בהמה -- פטורים מן הקלבון.
כל מקום שיש מכר, אין קנס. וכל מקום שיש קנס, אין מכר.
כל מקום שיש מיאון, אין חליצה. וכל מקום שיש חליצה, אין מיאון.
כל מקום שיש תקיעה, אין הבדלה. וכל מקום שיש הבדלה, אין תקיעה.
יום טוב שחל להיות בערב שבת, תוקעין ולא מבדילין. במוצאי שבת, מבדילין ולא תוקעין.
כיצד מבדילין? המבדיל בין קדש לקדש.     רבי דוסא אומר, בין קדש חמור לקדש הקל.
א
לא בדיוק אומר כן גמ’. גמ’ בתחילה חושב שמשמעות של סיגנון זה (“הכל שוחטים") אומר הכשר לכתחילה, אבל מוכיח נגד זה מן המשנה בערכין שאומר ש"הכל מעריכים….” הרי, שם מדבר אף במי שאומר "הרי עלי,” וכיון שיש עליו חיוב אחריות, בוודאי אין לעשות כן. אז, מוכיח גמ’ שזה לכתחילה ממה שאומר כן אף שסיפא כבר אומר הכשר בדיעבד. היה אפשר לתרץ באופן אחר, והוא שצריך שניהם כדי לרבות שני הכשרים בדיעבד. נראה שגמ’ לא עושה כן כיון שאם כן היה לו לומר שני הלשונות. ממה ששינה ללשון שקצת יותר משמע הכשר לכתחילה, רואים שמכוון לרבות ציור להכשר לכתחילה.
ב
מסתבר לומר כן. אז, מה שאומר גמ’ גבי שאלה וראיית אדם נוגעים אף כאן. החילוק בין בדיעבד ללכתחילה, אז, הוא אם מותר לשחוט ככה או אסור לשחוט ככה, מחשש שמא יטמא אותו.
ג
לכאו’, הביאור הוא שהכותי מכיר שהישראל יוצא ונכנס, ויודע שירצה לתת אותו לבני ישראל, ואז שוחט באופן שיכול לתת אותו. יש לדון, שאפשר לומר שלא יודע שייתן אותו לבני ישראל. אלא, אולי הענין הוא שיירא מלשקר, שיודע שיראל ראה אותו מקצת הזמן. (יש לדון, שאולי יוכיח שישראל לא ראה אותו כשפסל אותו, ממה ששואלים לו. לא מוכרח כן.)
ד
רבא לא אומר כן בפירוש. רב אשי אומר פשט זה, ומיוסד על מה שאמר רבא. שואל גמ’ למה לא אמר רבא כן, ומבאר שרבא רק אמר כאביי לבאר איך יכולים לפרש בסגנון של אביי כפי הדינים שסובר רבא. אז, באמת, אפשר שרבא יאמר כשום אחד מן שאר בפשטים. אבל, אין סיבה שלא יאמר כזה, כפי מה שאומר גמ’. (יש לדון, שהיה אפשר לומר שלשון סיפא של המשנה קשיא לו, ושהוא רק נחית לומר כן בפשט שלו כיון שלא סובר שזה הפשט, אלא רק בא להוסיף על אביי ולתקן למה שאומר. ותחשב.)
ה
מן הגמ’ (ג:) מבואר שיש חולק על מה שאמר רבא (ומסכים לו רב אשי). לא פשוט מהו הסברה לחלוק על רבא. לכאו’, הביאור הוא שחוששים שיש טורח במניעה שלו מדברים הפסולים את השחיטה (כמו הדרסה ושהייה), וחוששים שמחמת תאווה שלו, יעבור עליהם.
יש להעיר שגמ’ מביא ראיה לרבא מן המשנה (גבי מי שעבר עליו הפסח, ונשאר אצלו חמץ). צריך לומר שדוחים כמו שדוחה אותו גמ’, אף שאותה דהחייה נדחית.
ו
יש להעיר שקצת מעניין מה שגמ’ אומר ש"רוב מצויים אצל שחיטה מומחים,” וש"לא חוששים שיתעלף,” ולא ש"רוב מצויים אצל שחיטה לא מתעלפים.” אפשר לומר שלא צריך לבאר המקור לו לומר שיש רוב להכשיר, כיון שכבר באר כן כשאמר ש"רוב מצויים אצל שחיטה מומחים.” זה דחוק. יותר נראה שאין סומכים על ראיה זה בעילוף. אפשר לומר שאין צריכים הוכחה זו, אבל קשה מהיכי תיתי לגמ’ כן, ולא נרחיב את המחלקת להיות כל כך מן הקצה עד הקצה. אלא, נראה שאדם לא יודע קודם שחיטה אם יתעלף או לא יתעלף, ואז אין להוכיח שלא יתעלף ממה שבחר לשחוט. רק יכולים להוכיח כמה ידע, שאף מי שלא יודע דברים, לכאו’ מכיר שיש דברים בשחיטה שהוא לא יודע. ותחשב.
ז
יש דברים שנתרבים מן הריבוי של בדיעבד שאולי אין בהם איסור, אלא מחדשים היתר שבא אחרי השחיטה. אבל, לא מוכרח כן, שיש לומר שבכולם, כיון שלא ידוע לפני שחיטה אם ימצא להיות מותר, אסור למסור לו לשחוט לכתחילה, מחמת בל תשחית.
ח.
מן הגמ’ (יב:) יוצא שמרבים ממנו קטן. יש להעיר שאפשר לומר שזה רק רבא שמדבר שם, ואצלו מוכרח, כיון שמפרש את המשנה או כאביי או כרב אשי (יש לדון, שלא ממש מוכרח שיפרש אותו כן, כמו שהערנו לעיל בהוספות). ע’ לקמן בגמ’, שמוציא חידוש ממה שאומר רבא כן, ולא מפרש שהוא מפני שהיה אפשר לומר שלא מרבה קטן. אז, נראה שלכ"ע מרבה קטן. לכאו’, הטעמים שכתבנו נכונים.
ט.
גמ' לא מפרש מהו המקור לפסול שחיטת כותי.  (אף כשנמצא מקור למעט אותו, יהיה קשה למה לא פירש אותו הגמ'. יהיה טוב אם נוכל למצוא מקור שנאמר שבעצם פירש אותו גמ', כמו אם נמצא דרך לומר שהוא בכלל דרשה אחרת שמזכיר גמ'.) עיין בתוי"ט שכ',
"שחיטת נכרי נבלה. כתב הר"ב אפי' כהלכתה וישראל עומד על גביו. וכפירש"י. ומסיים הר"ן שאין שחיטה אלא בישראל אבל נכרי כיון דלאו בתורת שחיטה הוא כששחטה הויא לה כמתה מאליה. ע"כ. וכיוצא בזה כתב בית יוסף סימן ב' בשם ר"י. משום דכתיב וזבחת ואכלת אותו שהוא בר זביחה אכול מזבחו. ע"כ. ובכ"מ ספ"ב מהלכות אבה"ט. כתב הא דר"י בשם התוספתא דתניא בה וזבחת ואכלת ולא שזבח הנכרי לא שזבח הקוף. ע"כ. ועיין במשנה ג' פרק ב'. והרמב"ם כתב בפ"ד מה"ש. שנאמר (שמות ל״ד:ט״ו) וקרא לך ואכלת מזבחו. מאחר שהזהיר שמא יאכל מזבחו אתה למד שזבחו אסור. ואינו דומה לישראל שאינו יודע הלכות שחיטה. וגדר גדול גדרו בדבר. שאפילו נכרי שאינו עובד ע"ז שחיטתו נבילה ע"כ [ואעפ"י שהרא"ש כתב עליו שאינם דברים של טעם הנה בספרי ספר מעדני מלך כתבתי בפירקין סימן ה' דהכי דייק מקרא דכתיב וזבחו לאלהים אחרים וקרא לך ואכלת מזבחו. ואי איתא דלא אתי אלא להזהיר שלא יאכל ממה שזבח בתוך ביתו לא היה צריך לכתוב מזבחו. אלא ואכלת עמו. דהא רישא דקרא ה"ק וזבחו לאלהים אחרים אלא להכי מהדר וקאמר ואכלת מזבחו לומר שכל זבחו שהוא זובח אפי' שלא בתוך ביתו אסור] ומ"ש הר"ב אבל אינה אסורה בהנאה. כלומר כתקרובת ע"ז דאסורה בהנאה. כדתנן במ"ג פ"ב דע"ז. ומ"ש הר"ב דדיקא שחיטת מין האדוק לע"ז. וזה לשון הרמב"ם לפי שעובדי ע"ז נחלקים לב' חלקים. האחד מהן היודעין לעשות אותה. ר"ל להביט אל המזלות הצומחים לצורך מלאכתם ולהוריד הרוחניות בהן ושאר אותן שטויות שמטנפים השכל כמו שמאמינים בעלי האמונה ההיא כו'. והחלק השני הן העובדין לאותן הצורות הידועות כפי מה שלמדו מחכמיהם בלבד. וכן הם רוב עובדי ע"ז. והחלק הזה האחרון עליו אמרו חכמים ז"ל בלשון הזה. נכרים שבח"ל לאו עובדי ע"ז הם אלא מעשה אבותיהם בידיהם. ע"כ:"
ועיין במאירי שלשון שלו קצת משמע שפסול במחשבה הוא. וע"ש.
י.
לכאו’, הלימוד לפי זה יהיה שאומר "מטמא במשא" בלי צורך. כיון שאין צורך שייאמר על נבלה של המשנה, צריך לומר שהוא נאמר על דבר אחר, והוא תקרובת עבודה זרה. מצאנו כעין זה בתורה, והוא נקרא "תניהו ענין לזה.” (עיין במקום אחר בשי"ח ש"י שחידשנו שגמרא ומשניות ינקטו לשון כדרשות. וצלע"ש.)
יא.
הגמ’ אומר שלפעמים לא נותנים לאדם בהמה לשחוט בלילה. לכאו’, חוששים שיפסל אותו. יש לדון אם חוששים שיפסל אותו ולא יבין, ונמצא שאוכל איסור, או שחוששים שיפסל אותו ויעור על בל תשחית (כמו שאמר גמ’ לעיל גבי קטן).
יב.
עיין בגמ’ לעיל (ט.) שאומר שהשוחט צריך לבדוק את הסימנים. אז, צריך לומר שרק מכשיר כאן אם בודקים את הסימנים על ידי אדם שאינו סומא וביום (או כנגד אבוקה).
יג.
גם נראה שיש לדון אם צריך להיות שאומר ששחט כראוי, והחידוש הוא שנאמן, או שהוא אף אם לא אומר כן, אם אומרים שרוב מצויים אצל שחיטה כשרים, ואף כאן, מסתמא מצא אופן שישחט בכשרות.
יד.
גמ’ מביא ראיה שאין מוקצה בבהמות כיון שיכולים לאכול אותם בי"ט. יש לדון מהו הראיה, שאולי לא יכולים לאכול אותם בי"ט. אפשר שהמקור הוא הפסוק, שמתיר אוכל נפש. אבל, אין זה ראיה, שאיסור מוקצה הוא מדאו’. אפשר שהמקור הוא המשניות שמזכירים אכילת בהמה בי"ט, אבל נוכל לדחות שהם רבי שמעון. לאו’, לא מסתבר שכל המשניות שאומרים כן הם רבי שמעון, ורבי יהודה לא חש לחלוק בפירוש.
אבל, יש להעיר שיש חילוק גדול בזה, כיון שאוכל נפש הוא. אולי נכון שמוקצה הוא, אבל מותר לצורך אוכל נפש. צריך לומר שידוע לגמ’ שאין מוקצה מותרת אף לצורך אוכל נפש. ותחשב.
טו.
יש להגדיר דיחוי בידים. כתבנו שהוא שהנהנה גרם שיבוא האיסור. אבל, יש לדון אם הוא כן, שאולי הוא כל זמן ששום אדם גרם שיבוא האיסור, ולא בא ממילא. אולי מה שבא בבחירה וברצון שום אדם מספיק לעשות בו מוקצה. ותחשב.
טז.
כן אומר גמ’, אבל קשה להבין, כיון שלאחר זה כנראה מהפך. אומר גמ’ שאסור הוא משום מוקצה מחמת איסור, ומקשה מן המשנה. מתרץ שמשנה שלנו מדבר במי שהיה בביתו חולה בביה"ש (אבל, לא מותר לשחוט בזמן שחיטה, שכבר נתרפא החולק; קצת קשה למה לא תולים את זה בדיון בגמ’ בביצה ב"מוקצה לחצי שבת"). אולי צריך לומר שחוזר בו גמ’. אבל, אז קשה למה לא אמר שרב אומר שהולך כשיטת רבי יהודה כיון שסובר שיש מוקצה מחמת איסור. אפשר לומר שעכשיו התשובה יהיה שלא נוכל להוכיח שהוא אסור בו ביום, כיון שאין להוכיח שמדובר במי שאין לו חולה בביתו בבין השמשות. (הענין יהיה שאף בזה צריך להיות דומה ליום הכיפורים.) דחוק, שכמעט כל בני אדם אין להם חולה שיש בו סכנה בבתיהם בבין השמשות. יותר נראה לומר שצריך למצוא מקור לרב לחשוב שרבי יהודה הוא, ולא שו תנא אחר. אז, רוצים למצוא בריי’ שאומר שיטה של רבי יהודה שהוא שיטת המשנה. אבל, אם רק מצדדים כן, ויש דרך לדחות אותו מן מה שאומר רבי יוסי במשנה, אז אין סיבה לומר שהוא רבי יהודה יותר משום תנא אחר. אבל, אז צריך ביאור מהיכי תיתי לרב שרבי יהודה היא בדווקא, ולא שרבי מאיר הוא, ובזה הוא דומה ליה"כ. אולי צריך לומר שלא למד אותו מן דמיון ליה"כ, אלא היה לו מסורה בזה. אבל, מן הגמ’ לא נראה כן, שמקשה מהי"ת שרבי יהודה, ולא תנא אחר הוא. אז, צריך לעיין בזה.
יז.
במקום אחר כתבנו טבלא זה:אז, אם היינו עושים טבלא ממה שיודעים עכשיו, היה יוצא כזה:
1. רבי מאיר-
  1. שוגג:
    1. הוא-
      1. בו ביום- מותר.
רש"י בחולין ותוס’ כ’ שהוא מותר.
כן נראה מן הגמ’ בחולין, שאי לאו הכי קשה למה לא נמצא איסור בשבת בשוגג לרבי מאיר.  כן נ’ מגמ’ בשבת, שמביא משנה שמדבר (אולי) על אכילה בשבת, ומזכיר שרבי מאיר מתיר.
      1. במוצאי שבת- מותר.
אם בו ביום מותר, בוודאי במ"ש מותר. גם אם מותר במ"ש במזיד, בוודאי בשוגג מותר.
    1. אחרים-
      1. בו ביום- מותר.
אם לעצמו מותר, כל שכן שלאחרים מותר.
      1. במוצאי שבת- מותר.
מוכרח שהוא מותר, שזהו הציור הכי מותר.
  1. מזיד:
    1. הוא-
      1. בו ביום- אסור.
מוכרח שהוא אסור, שזהו הציור הכי אסור.
      1. במוצאי שבת- מחלקת.
רש"י בחולין ותוס’ בכ"מ כ’ שהוא מותר. כן נ’ מגמ’ בחולין, שגמ’ אומר ש"שחיטתו כשרה" משמע שמכשיר לכ"ע, ועדיין מצדד שהמשנה הוא כשיטת רבי מאיר. יש לדחות שאולי לא ידע כן גמ’ כשצידד שרבי מאיר הוא.
רש"י בכתובות כ’ שהוא אסור.
    1. אחרים-
      1. בו ביום- אסור.
רש"י בחולין ותוס’ בכ”מ כ’ שהוא מותר. כ"נ מגמ’ בחולין, שאומר שם שצריך להיות אותו משנה דומה ליה"כ, ועדיין מצדד שמשנה כרבי מאיר. שכדי לדמות ליה”כ, צריך להיות שאסור בין לו בין לאחרים. יש לדון, שאולי בזה לא צריך להיות דומה. גם, אולי לא ידע גמ’ שצריך להיות דומה בכלל כשאמר שאולי הוא ר”מ.
      1. במוצאי שבת- מותר.
רש"י ותוס’ מתירים. כן נראה מגמ’ בחולין, שמנסה להוקים משנה שאומר כן כרבי מאיר. (יש לדחות שרק סובר שרבי מאיר סובר כן כדי להוקים את המשנה כן.)
1. רבי יהודה-
  1. שוגג:
    1. הוא-
      1. בו ביום- אסור.
כן אומר בפירוש.
      1. במוצאי שבת- מותר.
רש"י ותוס’ כ’ שהוא מותר. כן מוכרח מגמ’ בחולין שמוקים משנה שאומר ששחיטת שבת כשרה במ"ש (וגמ’ מפרש שר"ל לכ"ע) כרבי יהודה.
    1. אחרים-
      1. בו ביום- אסור.
רש"י בחולין ותוס’ כ’ שאסור. כן נ’ מגמ’ בחולין, שכדי לדמות ליה"כ, צ"ל אסור לכ"ע. יל"ד, שאולי לא צ"ל דומה ליה"כ בזה.
      1. במוצאי שבת- מותר.
\כן מוכרח, שהוא הכי מותר.
  1. מזיד:
    1. הוא-
      1. בו ביום- אסור.
כן מוכרח, שאף בשוגג אסור.
      1. במוצאי שבת- אסור.
כן מוכרח, שהוא הכי אסור.
    1. אחרים-
      1. בו ביום- אסור.
כן מוכרח, מכל שכן בשוגג.
      1. במוצאי שבת- מותר.
כן כ’ תוס’. (רש"י לא גילה את דעתו.) פי’ שצ"ל כן, שאל"ה שווה למזיד של ריב"נ (ומוכיח נג"ז מגמ’).
1. רבי יוחנן הסנדלר-
  1. שוגג:
    1. הוא-
      1. בו ביום- אסור.
      2. במוצאי שבת- אסור.
    2. אחרים-
      1. בו ביום- אסור.
      2. במוצאי שבת- מותר.
  2. מזיד:
    1. הוא-
      1. בו ביום- אסור.
      2. במוצאי שבת- אסור.
    2. אחרים-
      1. בו ביום- אסור.
      2. במוצאי שבת- אסור.
יח.
יש לדון מה סובר רבי יוחנן הסנדלר בזה, אם אוסר מדאו’ (או אוסר תמיד) מעשה יוה"כ כמעשה שבת. לא מצאנו שזה נמנה לחילוק בין יוה"כ לשבת). יש להעיר שאם נאמר כן, אולי יש עוד חילוק בהוספת ציור זה, והוא שכאן אף רבי יוחנן הסנדלר מודה לזה, ודין זה אינו רק לפי שיטת רבי יהודה.
יט.
לא כל כך פשוט לי מה מרבה בזה. הגמ’ אומר שמרבה "בין ביום ובין בלילה בין בראש הגג בין בראש הספינה.” מבריי’ שהובא בגמ’ (יג:). יש להעיר שיש בזה שני דינים חלוקים. דין ראשון הוא ששוחטים אפילו בלילה, כשאבוקה כנגדו (כמו שמבאר הגמ’ שם), שלא קל לראות, יכולים לשחוט. דין שני הוא שאפילו בראש הגג ובראש הספינה, שקצת נראה כשוחט לעבודה זרה, מותר לשחוט. (אגב, יש להעיר שב"בין" ראשון אין חידוש אלא בצד אחד של ה"בין,” אבל בשני, יש חידוש לשני הצדדים של ה"בין.”) אז, יש שני דינים עם שני הו"א שונים. יש לדון אם מכוון לומר שהמשנה מרבה את שניהם או רק אחד מהם (והביא שאר הבריי’ אגב). אם נאמר שמרבה את שניהם, צריך לומר שלעולם משמע לרבות כל דבר, ויכול לרבות, אז, יותר מדבר אחד. צריך להגדיר את זה. אם נאמר שמרבה רק אחד, יש לדון איזה אחד מרבה. אולי הוא רק מרבה הראשון, שכן משמע לשון שלו. הרי, אומר שלעולם שוחטים, וזה משמע ששוחטים בכל עת. אבל, יש לדון, שלעולם יכול להיות משמע שבכל מצב הדין קיים. אולי הוא רק מרבה השני, שהראשון קצת נזכר במשנה שלפני כן (שדן בשחיטת לילה); אם היה רוצה להוסיף לו דין, היה לו להוסיף אותו שם. ותחשב על כל זה.
כ.
לכאו’, אין הוכחה שזה נוהג בכל דבר מחובר, שאפשר שהוא רק בתלוש שחבר אותו. אבל, אין סיבה לחשוב כן, ואחרי שהגמ’ לא מחלק, לא נראה שנחלק.
כא.
גמ’ אומר דין שחיטה בקנה בשני מקומות. במשנה שלנו אומר: “השוחט… בקנה, שחיטתו כשרה.” בדברים אחרים שבאותו בבא, גמ’ מדייק שאסור לכתחילה. לכאו’, גם זה כן. (דחוק לומר שהוא נשנה כאן לומר ששחיטתו כשרה, ואף מותר לכתחילה, אלא שאמר לשון זה אגב שני הדברים ששחיטתם כשרה רק בדיעבד.) מקשה גמ’ ממשנה אחר, שאומר ש"בכל שוחטים… בין בקרומית של קנה.” משיב שכאן מדברים בקנה מחובר.
לכאו’, יש תשובה יותר קלה, והוא שאסור לשחוט כן לכתחילה, שמא יסכן לאחרים, כיון שקנה נעשה לחתיכות קטנות. נראה שיכול להיות שני תי’ פשוטים. אפשר לומר שזה רק בקרומית של קנה, אבל לא בקנה. גם אפשר לומר שרואים מזה שאם שחט בה, ועושה סכנה, כיון שיש בו חתיכות קטנות, אסור אפילו בדיעבד. (עיין בלשון גמ’ לקמן, שרק אוסר לכתחילה.) אז, צריך לומר שמדברים שקנה שלא עשוה חתיכות קטנות, כמו שימצא גמ’ ציור לקמן.
אבל, נראה שיש דרך אחר, ואולי שתי’ של גמ’ זה הוא רק קודם אותו גמ’. אבל, אחרי שגמ’ מחדש איסור לחתוך בקנה, נוכל לומר שזהו הפי’ במשנה, ולא נצטרך לומר ששני הציורים אומרים דין שווה. אז, אולי מה שפירשנו במשנה הוא רק נכון בהו"א, ולא במסקנא.
כב.
אין זה כל כך ברור לי. ממחלקת בית שמאי ובית הלל, רואים שיש צד שהבהמה נבלה. צריך ביאור איך יהיה נבלה. הרי, חתך את שני הסימנים, אלא שעשה אותה נקובת הוושט קודם לכן. נראה שיכול להיות שני צדדים. הראשון הוא שבנקיבתו לא רק עשה אותו טריפה, אלא נבלה, שעשה הרבה נקבים, עד שהוא כמעט מת. השני הוא שלא חתך את הסימנים אלא קרע אותם, עד כדי שלא נחשב שחיטה. אז, לא מת על ידי שחיטה. (לשון משנה מעניין, שאומר שחונק הוא. הנחתי שרצה לומר שעושה נקבים בוושט, עד שלא בא לו רוח, ואז הוא מת בחניקה. אבל, אז אי אפשר לומר כצד שני, שלא מזכיר אותו בכלל, וגם לא משמע כצד ראשון, שכיון שלא מת אלא ממה שאי אפשר לו לנשום, מסתמא כבר נשחט קודם שנחשב מת. ותחשב. ועיין ברש”י על אותם המילים (טו:) שנראה שמפרש כצד שני שלנו. איני יודע איך רואה כן בלשון המשנה.)
כג.
כך נראה מן הגמ’, אבל איני מבין את המציאות הזה כל כך, שלא צריכים להיות שתי הפגימות תכופים זו לזו. אז, מה שנחלש על ידי פגימה הראשונה אינו מגיע לפגימה שנית. אז, קשה איך יצטרפו לנקוב. ותחשב.
כד.
אין כל זה כ"כ פשוט לי. לכאו’, לא כשר אא"כ לא שוחט עוד אחרי הפגם. עדיין, צריך לומר שהוא עובר על הפגם, ולא רק שעוצר כיון שמגיע לסוף הסכין (שזהו הפגם), שאם לא כן, בוודאי לא ינקוב. צריך ביאור למה אין לכל סכין פגם בסופו, שלכאו’, תמיד כן הוא המציאות. צריך לומר שרק אם יש לו פגם שלא כדרך עשייתו יש בעיה, שרק אז יעבור עליו (או מפני שעובר עליו אם ממשיך דרך הילוך של הסכין או מפני שלא מכיר שעובר על פגם). ותחשב. אבל, צריך ביאור איפה נוגע פסול של שני עוקצים, שאם הוא ממשיך לשחוט בו, אף אם יש עוקץ אחד פסול, ואם לא ממשיך לשחוט בו, מה לנו בעוקץ שני. צריך לומר שהוא פוסק אחרי שמגיע לפגם. אבל, הוא כבר מגיע- ולא ממשיך- לעוקץ שני, וכיון שעוקץ הוא, גורם נקב. צריך ביאור.
כה.
איני מבין איך יחשוב צד אחד שפגם בצד פוסל. מבין אני איך יכול להיות הו"א כזה גבי ליבון, שליבון של חלק זה של ושט יעשה ליבון של מקום אחר, ויהרוג את הבהמה. אבל, אין לומר כן בנקב. אז, כיון שהצדדים הם למעלה מן הסימן, רק יגע במקום שכבר שחט. אז, קשה איך זה יפסול את השחיטה. אולי צריך לומר שחושש שינקוב אותו קודם ששחט את רובו. עדיין, לא נראה שיעשה אותה לנבלה, אלא חושש שיעשה אותה לטריפה. ותחשב.
כו.
בעיקר מדברים כאן בפגם הנכנס (שחסר חלק מן הסכין). איני יודע הדין של פגם היוצא (שניתוסף על הסכין). ותחשב.
1. כז.
עיין בגמ’. המשנה אומר לשון רביעי. רבי יוחנן מתחיל את הגמ’ ואומר שחולקים רק בדבר השלישי. (לא מפרש למה בית הלל מחמירים בדבר ראשון ושני. אולי אסור מטעם גזירה או כיון שעושה אותו טריפה (אבל לא נבלה). גם אפשר שאסור כיון שיש לו חזקת איסור (כמו שאמר גמ’ לעיל (ט.)). אבל, אז ייתלה במחלקת שם אם אומרים כן גם לענין טומאה וטהרה (ולא משמע שהגמ’ תולה אותו).) ממשיך הגמ’ ומביא ראיה מלשון של המשנה, שנקט לשון רביעי.( לא כל כך פשוט מהו הראיה, ולמה חשב שמוכיח שום דבר. ותחשב.) דוחה הגמ’ שאין הלשון משמע שחולקים בשלישי, אלא צריך לומר שאף שאומר לשון רביעי, חולקים בשני. יש לדון אם כוונת הגמ’ הוא לומר שבין כך ובין כך אין הלשון מפורש, ואז נוכל לומר שחולקים בשני כמו שנוכל לומר שחולקים בשלישי, או שרצה לומר שהלשון משמע שחולקים בשני. ותחשב. (לפי שני, נמצא שמה שאומר רש"י שרבי יוחנן אומר כן ממסורה, ולא נדחה, אומר שהמסורה דוחה את משמעות של המשנה.) אז, באמת, יש שלש צדדים- אולי חולקים רק בשלישי, אולי חולקים רק בשני, ואולי חולקים בין בשני ובין בשלישי.
(נראה שיש לציין כאן לרע"ב, שגורס בדברי בית שמאי שנבילה היא. מסתבר לומר (אבל לא מוכרח) שידוע מעולם שיטת בית שמאי, ורק דן אם בית הלל גם מתיר באכילה או לא מתיר באכילה. יש להעיר שאז מסתבר לומר כרבי יוחנן, כדי שלא לרבות את המחלקת.)
* Footnotes
[fn:1] פרק ראשון
[fn:2] משנה א
[fn:3] משנה זה יבאר מי יכול לשחוט- לכתחילה, ובדיעבד. גם יבאר מתי יכולים לשחוט- באיזה זמן, ובאיזה יום.
[fn:4] גמ’ מפרש (ב:) שלשון זה בא לרבות שחיטה שכשרה לעשות לכתחילה. (לומדים כן ממה שאחר כך אומרים "שחיטתם כשרה.” אם היה מכוון לומר הכשר בדיעבד, לא היה אומר לשון זה (ע’ בהוספות אות א).)חולקים מה מרבים מזה (ב:, ג):רבה בר עולא אומר שמרבה טמא ששחט חולין בלי נגיעה (ע’ בהוספות אות ב.) שנעשה על טהרת הקודש. יכול להיות שתי סיבות לזה:אין טהרת הקודש עושה לדבר דינים של קודש.אף שעושה לו דינים של קודש, לא כל דינים של קודש באים לו. חששות לא באים לו, ולכן מותר לשחוט, אם לא נוגע.וא"ת איך זה קורה; בהכרח, כשיגע בסכין, יטמא את האוכל. יש לומר שמדברים בטמא שרץ, שלא מטמא את הכלי הנוגע. גם יש לומר שמדברים בסכין שלא מקבל טומאה, כמו קרומית של קנה.גמ’ מפרש ששאר הפשטים במשנה לא חולקים על דין זה.אביי ורבא אומרים שמרבה כותי ששחט עם שמירה מישראל הרואה אותו. אבל, חולקים כמה שמירה צריך כדי להתיר אותו:אביי אומר שכיון שהכותי נוגע בבהמה, צריך להיות שיראל רואה אותו בכל משך השחיטה.רבא אומר שרק צריכים שהישראל יוצא ונכנס. כיון שהכותי מכיר שיכול להיות שהישראל יכיר אותו, נשמר כראוי. (עיין בהוספות אות ג.)גמ’ מפרש ששאר הפשטים לא חולקים על דין זה (אלא סוברים או כאביי או כרבא).דין כותי בשחיטה לא פשוט. במק"א, בס"ד, נבאר את הדין שלו. הסיכום הקצר יהיה שכפי מקצת (ואולי כל) השיטות, נשתנה דינו לחומרא, ולכל השיטות שאומרים שנשתנה (אף שיש לשיטה אחת הו"א נגד זה), נאסר תמיד.רב אשי ורבא (עיין בהוספות אות ד.) אומרים שבא לרבות מומר לתאבון שנבדק סכין שלו קודם שחיטה. כיון שיש לו סכין כשרה, מניחים שישחוט כראוי, שרק לתאבון אוכל איסור.גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר ששחיטת מומר לתאבון לא כשר, אף אם נבדק הסכין שלו. (עיין בהוספות אות ה.) רבינא (א) אומר שבא לרבות מומחה (ידוע שיודע הלכות שחיטה), אף שאינו מוחזק שלא להתעלף באמצע השחיטה. (אם מתעלף, עלול לפסול את השחיטה בשהייה.)גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר שרוב המצויים אצל שחיטה הם מומחים.רבינא (ב) אומר שבא לרבות מי שמוחזק שלא להתעלף, אף שלא ידוע שיודע הלכות שחיטה.גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר שלא חוששים שבני אדם מתעלפים. (עיין בהוספות אות ו.)
[fn:5] גמ’ (ב:, ג) מפרש שלשון זה בא לרבות שחיטה שכשרה בדיעבד. הציור יהיה כנגד ציור שריבה לכתחילה, ואז נפרש אותו כפי מה שבארנו לעיל:רבה בר עולא אומר שמרבה טמא ששחט קדשים. אף שאסור לשחוט ככה, אם שחט כן, ואמר שלא טימא אותו, כשר.אביי ורבא אומרים שאם כותי שחט בלי שמירה, ואכל ממה ששחט, כשר.רב אשי ורבא אומרים שאם מומר שחט קודם שבדקו את הסכין שלו, ואחרי השחיטה בדקו את הסכין שלו, ונמצא שהוא כשר, כשר.רבינא (א) אומר שאם אדם לא מוחזק שלא להתעלף, ואומר שברי לו שלא התעלף, כשר.רבינא (ב) אומר שאם אדם לא ידוע להיות מומחה, ובודקים אותו אחרי השחיטה, ורואים שהוא מומחה, כשר. (עיין בהוספות אות ז.)
[fn:6] גמ’ (יב:) מבאר שלשון "יקלקלו,” שהוא בלשון עתיד, משמע שאף אסור למסור להם, שמניחים שיקלקלו.
[fn:7] חולקים (ב:, ג) על מה זה קאי, ונפרש על פי השיטות שמנינו לעיל:רבה בר עולא אומר שמרבה שני ציורים:חשו"ק. לכאו’, מניחים שמרבה אותו כיון שנאמר אצלו, וכיון שאומר "כולם,” וכיון שמסתבר שיתיר אותו, כיון שכל החשש היה שיקלקל. (עיין בהוספות אות ח.)טמא ששחט את הקדים, ולא יכולים לשאול לו אם נגע בו. מוכיח שאף מרבה את זה כיון שאם היה קאי רק על הקטן, היה אומר "ואם שחטו…,” כיון שאצלו נאמר.אביי ורבא אומרים שמרבה חשו"ק. אז, לשון הגמ’ שמוכיח לרבה בר עולא ולרבינא (א, ב) את ציור השני הוא קשה להם.רבא ורב אשי אומרים שמרבה חשו"ק. אז, לשון הגמ’ שמוכיח לרבה בר עולא ולרבינא (א, ב) את ציור השני הוא קשה להם.רבינא (א) אומר שמרבה שני ציורים:חשו"ק. לכאו’, מניחים שמרבה אותו כיון שנאמר אצלו, וכיון שמסתבר שיתיר אותו, כיון שכל החשש היה שיקלק.מי שלא ידוע אם הוא מומחה ששחט, שאם רואים ששחט בכשרות, אף אם לא יכולים לשאול אותו, להבחין אם מומחה הוא, שחיטתו כשרה.רבינא (ב) אומר שמרבה שני ציורים:חשו"ק. לכאו’, מניחים שמרבה אותו כיון שנאמר אצלו, וכיון שמסתבר שיתיר אותו, כיון שכל החשש היה שיקלק.מי שלא מוחזק שלא להתעלף שרואים שלא התעלף. אז, אף אם אינו שם לשאול אותו, כשר.
[fn:8] כמו שכתבנו לעיל, זה מרבה קטן ששחט כשגדול רואה את השחיטה. אבל, יש שני דברים לדעת בשחיטה כזו:חולקים תנאים אם היא כשרה. משנה שמכשיר אותו הולכת עם שיטת רבי נתן, אבל רבנן חולקים ופוסלים אותו. (יג.)שחיטה כזו רק כשרה בחולין. אבל, בקדשים, לא כשרה, כיון שכ’, “ושחט את בן הבקר,” שאומר שהשחיטה צ"ל לשם בן בקר, ו"לרצונכם,” שמשמע שצריכים לשחוט אותו לדעת השוחט. כיון שהצורך לדעת נכפל, מעכב. (יג.)
[fn:9] שחיטת נכרי, אף אם לא קרה בו שום פסול אלא מה שנעשה ע"י נכרי, הוא פסול. (רש"י יג.) לא מפרש גמ’ המקור לזה. (עיין בהוספות אות ט.)
[fn:10] מדייק גמ’ (יג.) מזה שרק נבילה היא, ולא חוששים שכיוון לשם עבודה זרה (ותקרובת ע"ז היא). אם היתה תק’ עבודה זרה, היה הדין שלו שונה בשני דרכים:היה אסור בהנאה, ולא רק באכילה.אולי היה מטמא אף באהל. עיין לקמן (במה שנכתב על סוף המשנה), שנבאר שזה מחלקת תנאים.נקודה זו מחלקת תנאים היא, שאף שרבנן סוברים כן, רבי אליעזר חולק, ואומר שסתם מחשבת עובד כוכבים הוא לעבודת כוכבים.
[fn:11] בארנו שזה רק פסול, ואינו תקרובת ע"ז. אבל, אם הגוי הוא מין (וכן הוא הדין בישראל מין), שהוא אדוק בע"ז, בוודאי מניחים ששחט לשם ע"ז, ונחשב תק’ ע"ז. אבל, בדר"כ אין הגויים מינים. (יג)
[fn:12] הפסוק אומר בפירוש שכל נבלה מטמא במשא. אז, גמ’ לומד דיוק ממה שמזכיר אותו המשנה. יש שני לשונות, ושניהם נוגעים למחלקת תנאים בנוגע טומאת תקרובת עבודת כוכבים. תק’ ע"ז טמא, אבל חלקו כמה טמא הוא. רבנן אומרים שמטמא במגע ובמשא, ורבי יהודה בן בתירה (יג:) אומר שגם מטמא באהל. (המקור של רבי יהודה הוא שנקרא "זבחי מתים,” להקיש אותו למת, שמטמא באהל.) שני הלשונות הם:לשון ראשון הוא שמשמע שרק זה מטמא רק במשא, אבל לא תקרובת עבודה זרה (קל למעט אותו, כיון שהזכיר אותו מיד לעיל, במיעוט, כמו שבאנו שם), שמטמא אף באהל.לשון שני הוא שמשמע לרבות עוד ציור שמטמא רק במשא, והוא תקרובת עבודה זרה, שלא מטמא באהל. (ע’ בהוספות אות י.)
[fn:13] לשון המשנה משמע ששחיטתו רק כשרה בדיעבד, אבל לא מרש"ים לו לשחוט לכתחילה (עיין בהוספות אות יא). גמ’ (יג:) מבאר שזה רק אם אין אבוקה כנגדו. אבל, אם יש אבוקה כנגדו, יכול לראות את השחיטה, ואז השחיטה כשרה. (עיין בהוספות אות יב.) לכן, אומר אותו עם סומא, כדי שנלמד עליו שהוא רק אם אין לו אור, והוא דומה לסומא.
[fn:14] אף שלא יכולים לראות, לא חוששים שפסלו את השחיטה. (עיין בהוספות אות יג.)
[fn:15] גמ’ אומר (יד, טו) שאף שהשחיטה כשרה, אינו נאכל באותו היום לשום אדם. לומד כן מסמיכות שלו לבשר שנשחט ביוה"כ, שלא נאכל באותו היום (כיון שאסור לאכול ביום הכיפורים). מזכיר גמ’ שלש איסורים שיכולים לעשות איסור לאכול בו ביום:מוקצה. אסור לטלטל ולאכול דבר שלא הוכן מבעוד יום. יש הרבה מינים של מוקצה- יש כמה דרכים שבו נאמר שדבר לא מוכן- וגמ’ מזכיר כמה צדדים למצוא איזה מין מוקצה הוא ציור זה:אין הבהמה עומדת להיאכל (שבהמות עומדות לעבודה, ולא לשחיטה), ואז נמצא שעושים בו דבר שלא היה תשמיש שלו לפני שבת.דוחה גמ’ שאם נכון הוא שאין שחיטה ואכילה תשמיש של בהמה, לא יהיה מותר לשחוט בהמה בי"ט (עיין בהוספות אות יד).נולד הוא. כיון שלא היה שם בין השמשות- שאז לא היה בשר, אלא היה בהמה- לא היה מוכן ביה"ש. אז, מוקצה היא.דוחה גמ’ שאין זה נולד, אלא היה בעולם בתחילת שבת, כיון שהיה חלק מן הבהמה. הרי, הבהמה היא אוכל (אולי מפני שהוכחנו ששחיטה ואכילה הוא תשמיש שלו), וגם הבשר אוכל, ואז לא קרה לו שינוי גדול.מוקצה מחמת איסור הוא. בבין השמשות, היה אסור לשחוט אותו, וממילא לא היה דרך לאכול אותו. אז, הבשר שלו לא מוכן.דוחה גמ’ שאין רבי יהודה אוסר מוקצה מחמת איסור אלא אם כן הנהנה גרם שיבוא איסור (עיין בהוספות אות טו). אבל, כאן, שבא האיסור ממילא (שהאיסור בא מן הצורך לשחיטה ומן האיסור לשחוט בשבת), אינו מוקצה. (עיין בהוספות אות טז.)גזירה הוא שמא יבוא לשחוט את הבהמה. חולקים אמוראים אם גוזרים כן.מעשה שבת. לפעמים, אסור לאכול מה שבא ע"י איסור שבת. יש שלש שיטות בזה:רבי מאיר אומר שבשוגג מותר לאכול, ובמזיד אסור לאכול בו ביום. אין המשנה יכול להיות כרבי מאיר, שהדמיון ליוה"כ משמע שאסור לאכול אותו אף אם נשחט בשוגג.רבי יהודה אומר שבשוגג אסור לאכול בו ביום, ובמזיד אסור לו לאכול לעולם.ר"י הסנדלר אומר שבשוגג אסור לו לאכול לעולם (ולאחרים אסור בו ביום), ובמזיד תמיד אסור לכ"ע. אין המשנה יכול להיות כר"י הסנדלר, שאומר שהשחיטה כשרה. לר"י הסנדלר, לא כשר לכ"ע.לפי רבי מאיר ורבי יהודה איסור זה בוודאי הוא מדרבנן, אבל חולקים אמוראים לפי ר"י הסנדלר אם הוא מדרבנן או לפעמים מדאו’. (עיין בהוספות אות יז.)
[fn:16] לכאו’, אין סיבה להזכיר אותו אלא ללמד ששחיטת שבת אסור בו ביום (עיין לעיל, שבארנו את זה). אבל, בלי זה, אין בו צורך, שהוא יותר קל משבת. אם שחיטת שבת אינה אסורה, אז גם שחיטת יה"כ אינה אסורה. (עיין בהוספות אות יח.)
[fn:17] עיין בהוספות אות יח.
[fn:18] השוחט בשבת במזיד חייב מיתה והשוחט ביה"כ במזיד חייב כרת.
[fn:19] לקמן, נוכיח שמשנה שלנו מדבר במי ששוחט בשוגג. אם כן, קשה איך יאמר שמתחייב בנפשו. צריך לומר שלא מכוון לומר שהוא ממש חייב בנשפו, אלא שהוא עושה עבירה שיש בו חיוב מיתה, אם היה עושה אותו במזיד. (טו.)
[fn:20] מבאר גמ’ שרצה לומר ששחיטתו כשרה לכולי עלמא, ואף למי ששוחט אותו. זה רק נמצא במי ששוחט בשוגג לפי רבי יהודה או לפי רבי מאיר. משנה שלנו לא יכול להיות כרבי מאיר, כמו שבארנו לעיל, ואז צריך להיות כצד ראשון. (טו.)
[fn:21] דינים היוצאים מן המשנה:משנה מרבה ציור אחד לשחיטה לכתחילה. חולקים מהו:רבה בר עולא אומר שמרבה טמא ששחט חולין בלי נגיעה שנעשה על טהרת הקודש. יכול להיות שתי סיבות לזה:אין טהרת הקודש עושה לדבר דינים של קודש.אף שעושה לו דינים של קודש, לא כל דינים של קודש באים לו. חששות לא באים לו, ולכן מותר לשחוט, אם לא נוגע.גמ’ מפרש ששאר הפשטים במשנה לא חולקים על דין זה.אביי ורבא אומרים שמרבה כותי ששחט עם שמירה מישראל הרואה אותו. אבל, חולקים כמה שמירה צריך כדי להתיר אותו:אביי אומר שכיון שהכותי נוגע בבהמה, צריך להיות שיראל רואה אותו בכל משך השחיטה.רבא אומר שרק צריכים שהישראל יוצא ונכנס. כיון שהכותי מכיר שיכול להיות שהישראל יכיר אותו, נשמר כראוי. גמ’ מפרש ששאר הפשטים לא חולקים על דין זה (אלא סוברים או כאביי או כרבא).אפשר שאין אותו הדין נוהג עוד, והיום שחיטת כותי אסורה, שנמצא שהם עובדי עבודה זרה.רב אשי ורבא אומרים שבא לרבות מומר לתאבון שנבדק סכין שלו קודם שחיטה. כיון שיש לו סכין כשרה, מניחים שישחוט כראוי, שרק לתאבון אוכל איסור.גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר ששחיטת מומר לתאבון לא כשר, אף אם נבדק הסכין שלו. רבינא (א) אומר שבא לרבות מומחה (ידוע שיודע הלכות שחיטה), אף שאינו מוחזק שלא להתעלף באמצע השחיטה. (אם מתעלף, עלול לפסול את השחיטה בשהייה.)גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר שרוב המצויים אצל שחיטה הם מומחים.רבינא (ב) אומר שבא לרבות מי שמוחזק שלא להתעלף, אף שלא ידוע שיודע הלכות שחיטה.גמ’ מפרש שמי שלא אומר כן חולק על הדין, וסובר שלא חוששים שבני אדם מתעלפים. יש שכשרים בדיעבד:השוחט בשבת. חולקים תנאים אם מותר הוא לאכול. אף אם מותר הוא, יש שסוברים שאסור לאכול אותו בשבת.השוחט ביום הכיפורים. דין שלו שווה לדין של שוחט בשבת. (עיין בהוספות אות יח.)יש שכשרים בדיעבד רק עם הוכחה:רבה בר עולא אומר שטמא ששחט קדשים. אף שאסור לשחוט ככה, אם שחט כן, ואמר שלא טימא אותו, כשר.אם ראה ישראל אדם טמא ששחט ולא נגע, שחיטתו כשרה, ואינו טמא.אביי ורבא אומרים שאם כותי שחט בלי שמירה, ואכל ממה ששחט, כשר.רב אשי ורבא אומרים שאם מומר שחט קודם שבדקו את הסכין שלו, ואחרי השחיטה בדקו את הסכין שלו, ונמצא שהוא כשר, כשר.רבינא (א) אומר שאם אדם לא מוחזק שלא להתעלף, ואומר שברי לו שלא התעלף, כשר.רבינא (א) אומר שאם אדם לא מוחזק שלא להתעלף, וישראל ראה שלא התעלף, כשר.רבינא (ב) אומר שאם אדם לא ידוע להיות מומחה, ובודקים אותו אחרי השחיטה, ורואים שהוא מומחה, כשר. רבינא (ב) אומר שאם אדם לא ידוע להיות מומחה, וישראל ראה ששחט כהלכה, כשראם חשו"ק שחט, וישראל ראה שלא קלקלו, משנה אומר שכשר. אבל, חולקים תנאים בזה.אם סומא שחט, ואמר שכשר הוא, נאמן, והשחיטה כשרה. (עיין בהוספות אות יג.)אם אדם שחט בלילה, בלי אבוקה כנגדו, ואמר שכשר הוא, נאמן, והשחיטה כשרה. (עיין בהוספות אות יג.)יש שלא כשרים בשחיטה:שחיטת גוי פסולה. יש שתי סיבות לזה:הוא מכוון לעבודה זרה. (ע' לקמן.)אינו בר זביחה, שאינו מצווה לזבוח מה שרוצה לאכול.שחיטה לשם עבודה זרה (כמו שחיטת מין) פסולה, ואף אוסרת בהנאה.כל בהמה שנשחטה בשחיטה פסולה נעשה נבלה, ומטמא במשא.
[fn:22] משנה ב
[fn:23] יש שני פיות לו. לפה אחת, יש פגימות, ואז אסור לשחוט בו, והאחר חלק, וכשר לשחוט בו. לא פוסלים את השחיטה בגזרה על צד החלק מחמת צד הפגום. אבל, לכתחילה, אין לשחוט בו, מחמת אותו הזגרה. (טו:)
[fn:24] גמ’ לומד מלשון זה שאסור לשחוט בו. אבל, אם שחט בו, שחיטתו כשרה. מבאר שמדובר כאן בצור שנתלש ונתחבר, ואז נבאר דין של שחיטה במחובר:שיטת רבי חייא- תמיד מותר לשחוט בדבר המחובר. (עיין בהוספות אות כ.)שיטת רבי-בדבר שתמיד היה מחובר- שחיטתו פסולה. (גמ’ מביא מקור אחד לרבי (שמצאנו שחיטה בתורה שקורה בדבר התלוש, אבל אומר שאינו מקור אמיתי. לא מבאר מקור אחר.)בדבר תלוש שנתחבר-בדבר שלא מבטל לקרקע- אסור לשחוט, אבל שחיטתו כשרה. (לכאו’, אסור לכת’ מחמת גזי’ אטו דבר שתמיד היה מחובר.) ציור של זה הוא סכין, ואולי צור.בדבר שמבטל לקרקע- גמ’ מסופק בזה. (יש לדון אם הצד לפסול הוא משום גזי’ מחמת דבר שתמיד היה מחובר או מפני שהוא שווה לדבר במחובר.)(יש עוד דין שנוהג בשוחט במחובר, והוא שלא יכול לשחוט בסכין למטה מצוואר בהמה, שמא ידרוס, אלא בסכין למעלה מצוואר בהמה. חולקים אמוראים אם זה נוהג גם בעוף (שכיון שהוא קליל, לא כ"כ מצוי שידרוס). ק"ק ל"ל אומר שההיתר בדיעבד הוא כששחט עם צוואר בהמה למעלה, ואומר שברי לו שלא דרס.) (טז:))כדי למצוא ששחיטה בצור יהיה אסור וכשר, צריך להיות כרבי, וצריך להיות שהיה תלוש. אולי לא בטל לקרקע או אולי בטל (ונפשט שאלת גמ’ לומר שדבר הבטל לקרקע, כיון שהיה תלוש, כשר בשחיטה). (טו:, טז)
[fn:25] גמרא מבאר (טו:) שגם זה אסור וכשר, מפני שהוא מחובר. אז, מה שבארנו בצור נוהג גם בקנה. אז, יש לדון למה שונה את שניהם.וא"ת ייאסר כיון שהקנה נעשה חתיכות קטנות, ונמצא שגורם סכנה למי שאוכל אותו, שמא יבוא לגרונו חתיכה קטנה של קנה. גם יש לומר שכאן מדובר במין מיוחד של קנים שלא מתחלקים לחלקים קטנים. (טז:) (עיין בהוספות אות כא.)
[fn:26] דן גמ’ (ט:) מה מרבים מזה:בא לומר שכל דבר צריך שחיטה. בא לרבות עוף. חולקים אם זה מדאו’ או מדרבנן. גמ’ דוחה פשט זו, שמוכיח ששאר מאמרי המשנה בבבא לא מדברים על השחוט, אלא על השוחט.בא לומר שכל אדם יכלו לשחוט. כבר ריבה אחד לעיל (משנה א), והבאנו למטה שחולקים מה מרבה. בין שני המשניות, מרבים שני דברים מאותם הדברים שמנינו שם.
[fn:27] דן גמ’ (טז:, יז.) מה מרבים מזה:מרבה שבשר מותר היום- אחרי חורבן בית המקדש- בשחיטה. וא"ת למה לא יהיה מותר. יש לומר שהולך כשיטת רבי ישמעאל. רבי ישמעאל דורש את מה שכתיב, “כי ירחיב ה’ אלקיך את גבולך… ואמרת אוכלה בשר…,” לומר שמתיר לאכול בשר תאווה בשחיטה אחרי שבאו בני ישראל לארץ, והוקם משכן קבוע. אבל, כשלא היה משכן קבוע- בזמן שהיו במדבר- לא היה בשר תאווה מותר. (אבל, בשר של בהמה שלא ראויה להקרבה, כמו חיה או בעלת מום, מותר לאכול לתאווה.) אז, הו"א שהיום, שאין משכן קבוע, ייאסר אכילת בשאר תאווה.דוחה גמ’ שהסיבה שנאסר בשר תאווה כשהיו בני ישראל במדבר אינו מפני שלא היה להם משכן קבוע, אלא היה מפני שכולם דרו קרוב למשכן. אז, כיון שהיה קל להם להביא קרבן, לא היה מותר להם לאכול בשר תאווה. אז, כיון שהיום אין אפשרות להביא קרבן, פשוט שבשר תאווה מותר.מרבה שבשר צריך שחיטה היום- אחרי החורבן. וא"ת למה לא יצטרך שחיטה. יש לומר שהולך כשיטת רבי עקיבא. רבי עקיבא דורש את מה שכ’, “כי ירחיב… ואמרת אוכלה בשר…,” לומר שמחייב לשחוט בשר אם רוצה לאכול אותו, כשמגיעים לארץ ישראל. נמצא שלפי רבי עקיבא, רק היו חייבים בשחיטת בשר כשבאו למשכן קבוע. אז, הו"א שכיון שאין לנו משכן קבוע היום, לא צריכים לשחוט כדי לאכול בשר.דוחה גמ’ את פשט זו, שמוכיח ששאר מאמרי המשנה בבבא לא מדברים על השוחט, אלא השוחט. בא לרבות שחיטה בכל מקום ובכל זמן. (עיין בהוספות אות יט.)
[fn:28] גמ’ מבאר (יז.) שלש ציורים שמרבים מזה:שוחט בצור. משנה הזכיר דין זה לעיל. קצת קשה למה כופלים עליו. (אולי כשגמ’ אומר שמרבים אותו, אינו דווקא, ובא גב שאר הדינים שמרבה.)קרומית של קנה. גם דין זה הוזכר לעיל במשנה.זכוכית.
[fn:29] הוא מין סכין שבו קוצרים תבואה, ויש בו פגימות (נבאר אותו יותר לקמן למטה בע"ה).
[fn:30] הוא מין סכין שיש לו פגימות.
[fn:31] גמ’ מפרש (יח.) שמדברים בשני שיניים התחובות בלחי. כיון שיש רווח ביניהם, נמצא שיש פגימה, ואז השחיטה חונק.
[fn:32] גמ’ מפרש (יח.) שמדברים בצפורן המחובר לאדם. אין שוחטים בדבר המחובר לאדם, ואז שחיטה הזו פסולה. (לכאו’, רק רבי חייא (עיין לעיל למטה, בביאור תחילת המשנה) פוסל שחיטה במה שמחובר לאדם.)
[fn:33] זה רק מסביר סיבת הפסול לשלשה הציורים הראשונים- שוחט במגל קציר, במגירה, ובשיניים- ולא לציור אחרון- שוחט בצפורן. (אז, אף שהוא הסמוך לו (שהוא ציור האחרון), נמצא שאינו מתפרש על ידו.)
[fn:34] דברים אלו פסולים כיון שלא עושים שחיטה, אלא נוקבים את הסימנים, ואז לא שוחט את הבהמה עד שעושה נקבים בו. (עיין בהוספות אות כב.) לא רק באלו שלשה דברים שחיטה אסורה, אלא אלו הם ציורים של סכינים שיש בו פגימות; כל סכין שיש בו פגם פסול. אבל, אין הדינים כל כך פשוט, ואז נבאר מה אומר הגמ’ (יז) בביאור איזה פגימות (עיין בהוספות אות כו.) פוסלים:אם יש שתי פגימות או יותר, פסול. פגימה ראשון מחליש את הסימן, ופגימה השנית נוקב. (עיין בהוספות אות כג.)אם יש פגימה אחת עם שני עוקצים, פסול. עוקץ ראשון מחליש את הסימן, ועוקץ שני נוקב.אם יש פגימה אחת עם עוקץ אחד שהוא באמצע הסכין, פסול. העוקץ מחליש אותו, ונפילתו לתוך הסכין נוקב. (עיין בהוספות אות כד.)אם יש פגימה אחת עם עוקץ אחד בסוף סכין, והוליך והביא, פסול. ההליכה מחליש אותו, וההבאה נוקב.יש להוסיף שאף אם אין בו אחד מאלו, אסור לכתחילה (אולי יש חשש שמא ינקוב, ואולי יש חשש שמא יטעה בין מיני פגימות). היוצא מכלל זה הוא םגם שעולה ויורד בו. הכוונה היא שאין הסכין חלקה, אבל הפגימה גדולה מאד, והולך בכולו, עד שלא אפשר לו לנקוב.חולקים איפה פגם פוסל, אם הוא רק בחודו של הסכין או אף בצדדיו. הצד להתיר פגימה בצדדים הוא שבית השחיטה נתרחב, כיון שנשחט, ואז אינו נוגע בצדדים. אז, אין פגם שם יכול לנקוב. (עיין בהוספות אות כה.)מצאנו חמשה דרכים לבדוק סכין (ולא פשוט מי חולק עם מי):בשמש:לשון ראשון של רש"י מפרש שנותנים אותה לפני החמה, ורואים את החוד שלה לפני החמה. (לכאו’, רואה אם החמה מגיע לו מן הכין במקום יותר נמוך או גבוה, שמזה נראה שיש פגימה באותו המקום.)לשון שני של רש"י הוא שרואה את ציל שלה. כיון שציל יכול להיות יותר גדול מן החפץ עצמו, גם הפגם יהיה יותר גדול, ויותר קל לבדוק לו.במים:נותן את חודה למטה, ומוליך אותו על מים. רואה חריץ במקום פגם.נותן את חודה למעלה, ונותן טיפה של מים על חוד שלה. אם יש פגם, המים יתעכב שם, ולא יגיע עד ראשה.בבשר. גמ’ נותן שני ציורים. (קצת משמע מן הגמ’ שיש שסוברים שרק הראשון מהני, ויש שסוברים ששניהם מהני.):לשון.אצבע.בחוט השערה.בצפורן.
[fn:35] כמו שבארנו לעיל, מגל קציר יש בו פגימות, שיש בו כמה שיניים. אבל, הם כפופים מאד, עד שלא קורע כל כך. לכן, יש צד להקל בו. (רש"י יח.)
[fn:36] אין המציאות כל כך ברור לי; הרי, כבר בארנו לעיל הפגימות הפוסלות, ורק נבדוק אם זה נכנס לכלל הפוסלות. ותחשב.
[fn:37] יש לדון אם חולקים מדין או מפני גזירה.
[fn:38] יש להקדים שיש שלש דברים שנוכל לומר בשחיטה להקל:מותר לשחוט.מותר לאכול מאותו שחיטה.בהמה שנשחטה בו אינו מטמא.יש ארבע לשונות שנוכל לומר כדי להקל בשחיטה:מותר לשחוט.השחיטת מתיר.השחיטה מטהר.השחיטה כשרה.משנה שלנו מזכיר מחלקת בשלישי- אם מטמא או לא מטמא. הגמ’ מנסה להוכיח כן ממה שנקט לשון רביעי, אבל דוחה שאין לשון זה משמע שחולקים רק בשלישי, שהיה אפשר לפרש אותו גם לומר שחולקים בשני. אבל, לרבי יוחנן היה מסורה שחולקים בשלישי. (יח.) (עיין בהוספות אות כז.)
[fn:39] לכאו’, רצה לומר שהוא כפוף עד שנוגע. אז, הוא ממש כסכין. אבל, קשה, שאז פשוט שדין שלו כסכין, שהוא ממש סכין. גם קשה למה יעשו שינים כפופים כל כך, ולא רק יעשה אותו פשוט, שכמו שכתבנו ממש שווה הוא.
[fn:40] משנה ג
[fn:41] משנה ד
[fn:42] משנה ה
[fn:43] משנה ו
[fn:44] משנה ז
