* ג:
** טעמא דר"י -
לכאו', ההוכחה היא ממה שאמר "טעמא דרבי יהודה,” ולא אמר "טעמא דרבו של רבי יהודה.” אין זה הוכחה גדולה, שיש לומר שנקט השם של מי שאמר אותו. עדיין קשה למה הביא המאמר הראשון של רבי יוחנן. נראה שגם אפשר שלשון "טעמא ד[תנא אחד]” משמע שלא פסק כמותו. ויש לדון. ותחשב.
* ד.
** חביבך -
עיין בקרבן העדה שפי' שר"ל "דודך.” כמו כן מצאנו ברב שקרא לדודו רב חייא בשם "חביבי.”
** שתי חדשים -
עיין בגמרא בשבת (ל:). צריך לומר שזה מדבר כשכבר גדול, שמוציא בכל יום, וכאן מדבר כמה זמן צריך מנטיעה עד שנותן פירות.
** לפי -
צריך ביאור מה משמעות מילת "לפי" כאן.
* ד:
** לברכות -
יש לדון אם זה גם לברכות או רק לברכות. מקושיית הגמרא (שסתירה היא) צריך לומר שעכ"פ אחד מהם הוא "רק.” כיון שנאמר בלשון אחד, מסתבר ששניהם "רק.” ותחשב.
* ה.
** חד בר נש -
וא"ת אטו אחרים לא שמרו מעשרות. צריך לומר שזה החמיר על עצמו ביותר (ושזה דבר טוב) או שזה מסר את נפשו עליהם יותר. ותחשב.
* ה:
** אמר ליה -
לשם שמים -
צריך ביאור איך בהשכרת זונות היה עושה לשם שמים. אולי היה משכיר אותם לבני אדם שאינם כל כך אסורים להם (ר"ל, ישראלים כשרים, ולא גויים או ממזרים). ותחשב.
** אלא -
עיין בקרבן העדה. לשונו ל"ד, שצריך להיות בלשון נקבה, שדבר אל אשתו.
** ישן ועמד -
נמצא שלא כמו שמשמע מן הבבלי, אלא שאם ישן ולא התנה, רק אסור מקרות הגבר. ותחשב.
