* ב.
** ולא זו –
יש לדון מי אומר זה (ר"ג או משנה). גם יש לדון אם נאמר לראייה שעושים כן רבנן או ללמד דין אגב דין זה. ותו"ת.
** אי בעית אימא –
קצת צריך לבאר למה יחלקו אהדדי. כמו כן, צריך לדון למה מניח גמרא שיהא של שחר קודם (ואולי רק אגב משנה שנית. אם כן, תי’ אחרון של גמ’ יתרץ.)
** רש"י אם כן –
וא"ת למה רק דן באכילתו, ולא בהעלתו. נראה שכולל אכילה והעלאה בלשון אכילה, כמו שמצאנו לענין פיגול בזבחים (כח:). נראה שכללם כדי לקצר. שו"ר שסבר שלא אמרו כן רבנן בהקטר. אבל, עדיין נוגע לדין עלות, שרש"י כ’ שהוא עיקר של המשנה. ותחשב.
** רש"י כדי –
ויתחייב כרת – משמע שהענין הוא להרחיקו מן החיוב, ולא מן העבירה (כלשון גמ’). אולי רק סימן אמר. ק"ק למה לא יאמר העבירה עצמה. אולי רצה לומר "יעבור על איסור שיש בו ח"כ.” קצת יש לדון, שגמ’ אומר (יבמות פב., קיט.) שאין לחלק.
** רש"י כדי –
עיין בראייתו. לכאו’, מביא ראיה ממה שאין זמנו עד חצות. אין לדחות שדן רק בזמן דאו’, דלא מנה ק"ש ואכילת קרבנות, וצריך לומר שהוא מפני הגזירה.
* ב:
** מבריי’ –
צריך ביאור למה לא פשטו אותו ממשנה. יש לומר שדנו בו קודם כתיבת המשנה. (ההוכחה מן המשנה יהיה שבוודאי משנה דן בלילה. אולי יש לומר שהיה צד ומר שקרא אומר שקיעה, ורצה לומר בזמן שאכתי יש שמש, ויכול להקריב את הקרבן, והוא קצת לפני שקיעה. ותחשב.)
** לא עני –
קשה, מה נתרווח בזה, שבין כך ובין כך יש מחלקת. יש לומר שרצה שלא יהיה תנא חולק על סתם משנה. קשה, שעדיין יש תנא החולק, ואף אם שני הבריי’ מסכימים, היהי תנא אחד חולק. יש לדון, שיש לומר שמדאמר אחד באופן חלוק, שני תנאים בחד שיטה הוא. ויש לומר שרוצה למעט בבריי’ נגד משנה. קצת יש לדון למה. יש לומר שאם יש יותר בריי’ נראה שהשיטה יותר נתקבל.
** נכנס –
בכ"ז, לשון נכנס מיותר.
* ג.
** קסבר שלש –
יש לדון מהי"ת, שאולי יש ארבע, ומראה לנו אותו ענין. יש לומר שרק בשלש אפשרד לומר שיש בארץ, שרק בזה תני במשנה, ורק בזה מוצאים במציאות. גי"ל שלפי אמת יש שלש, כמו שיביא מבריי’, ועל זה סומך.
** דאיכא -
יש לדון מה מלמד:
א. יש ממשרות בארץ. כן נראה מרש"י.
ב. יש משמרות ברקיע. לפי זה, קוראים גמ’ "קמ"ל שיש משמרות ברקיע (ולשון ברקיע קצת מיותר), ואגב גם יש….”
ג. מראה לנו א וב.
** ועל כל משמר -
לשון זה מעניין, וצריך ביאור מה משמעות שלו. אולי רצה לומר בתחילה, בסוף, או באמצע, אבל לשון "על" לא משמע כן כל כך. אולי רצה לומר בכולו, ויש הו"א שלחם מהם פסק למקצת זמן. קצת משמע שבוכה עליהם, והוא שמשמרות ה"ה יותר טובים, לשום סיבה, כשבני ישראל היו בביה"מ, ואז על כל המשמרות יושב ובוכה.
** רש"י לאו –
נמצא שר"T ותנא דעני סוברים שסוף זמנו הוא סוף זמן שבו בנ"א הולכים לשכוב. קשה אז איך יש שיעורים כל כך חלוקים. ותחשב. הנחתי שעומד עני מאד לפני שליש הליה. כן נראה, שלא נראה שאוכל לקרוב לשלש שעות. יש להעיר שברש"י כ’ שני לשונות בר"א: “זמן התחלת שכיבה,” שמשמע שכולל אף זמן שבני אדם כבר שוכבים מעט, ו"שבנ"א הולכים לשכוב,” שהוא לפני זמן שכיבה. אגב, נראה שלולי רשי יש לומר שכולי עלמא מודו שבנ"א שוכבים בצאת, ורק דנים אם מחשבים זמן ששוכבים או שהולכים לשכוב בתחילת הזמן. אפשר שר"ל כראשון ולכן חולק על תנא דעני, וכולל שניהם, ושני מקדים הזמן תחיללה. גם יש לומר שר"ל השני, וראשון מבאר למה כל כך מאוחר הוא, אם בנ"א הולכים לשכוב בצאת, ומבאר שיש שמאחרים. ותחשב.
** דאיכא –
וא"ת איך יודעים עיקר שיטתו. יש לומר שיודעים אותו ממק"א – או דין ק"ש או דין משמרות.) כמובן, דחוק. עוד יש לומר שחי’ וקמK זו רק אפשר אם יש שלש משמרות.
** בית אפל –
לכאו’, זה יכול אף במשמר ראשון, ובתחילתו. יש לומר שאין כל כך חשש שיעבור זמן, שזמנו יותר ארוך, ויכיר בזמן. יש לדון שלר"א אינו כ"כ יותר ארוך. ותחשב.
* ג:
** מעולם –
נראה שאז ק"ק למה נקט חצות. יש לומר שנקט שום זמן שבעולם. עוד יש לומר שבחצות רגילים כל בני אדם לישון, שיש שישנים עד חצות, ויש שישנים מחצות (יש לדון, שגמ’ שממע גבי תנא דעני ור"א שההול’ לישון כלים יותר לפני זה. אולי עכ"פ יש יחידים שלא נוהגים כן.) אבל, בחצות כמעט כו"ע ישנים.
** ודוד –
כ"ז צ"ב, שמה"ת שדוד ידע, שאולי רק אמר שחצות, באיזה זמן שהוא, לא עבר עליו. גם צריך ביאור למה אי אפשר למשה לומר חצות אם אינו יודע מהו, שאף על פי כן, יודע שאז יקרה. עיין ברש"י. לא הבנתי מה אומר ליישב את זה (שנ’ שזה כוונתו לעשות). אולי חשש שיחשבו שיודע וינסו אותו. וחדוק (שיאמר להם שוהא לא יידע אבל ה’ ידע.)
** דוד סימנא –
ק"ק ל"ל היה יכול משה לעשות כן. אולי היה צריך לדעת מתי יגיע חצות קודם חצות. דחוק. ותחשב.
** אין הבור –
משמע שאמרו כן לו בכל יום ויום; זה נראה קצת מוזר; עטו עשו מלחמה בכל יום!
** ודוד –
מניח גמ’ שאין יותר חכם ממשנה. במק"א בגמ’ (סוכה) זה מח’ רב ושמואל.
* ד.
** רש"י אביתר –
זה קודם מעשה של אבשלום בהכרח, שהרי שאלו לאחיתופל, ולאחר מעשה אבשלום, כבר מת אחיתופל.
** רש"י עורה –
עיין בלשונו. נראה שמכוון במה שאומר לשני דרשות מלשון "כבודי":
א. אל תתכבד.
ב. אף שמכובד אני, קום (וזהו הקוטרראסט שמז’ בינו לשאר מלאכים).
** שמא תתכבד –
אם מביא סיוע מכאן, צריך לומר שטעמו אינו מחמת חשש שאינך נכון, שאז באמת אינך יודע, אלא שחבירך לא ידע שאתה נכון. נראה שכן לשון תתבדה, שר"ל שתעשה בודה (כמו לשון אדם הבודה מלבו, שר"ל לעשות דבר על פי מוחו בלי שום הוכחה.) ולשון שנעשה כן משמע שחבירו עשהו כן, דהיינו שחבירו מחשיב כן, אבל אינו, באמת, כן (שאל"ה, מבדה א"ע.) ויש לדון, שמוציאים לשון זה נאמר על אדם עצמו, כמו מתלבשת.
** דנתי –
קצת צריך ביאור למה צריך זה כאן, שכבר יש חיוב ופטור.
** יפה –
קצת קשה ל"ל מז’ איסור והיתר (ואין לומר שדנתי מוסיף זה, שאכתי ק"ק למה לשונו כ"כ חלוק, ולא אמר "אסרתי.. התרתי.”).
** מבייש פני –
יש להעיר שכולל בשם זה רק מה שמפיו היה בשת, וחסר מה שלדוד המלך החשוב היה בשת.
** שמא יגרום –
קצת צריך ביאור מה ר"ל. נראה שר"ל שאף שעכשיו צדיק הוא, שמא לאחר זמן יחטא, ולא יהיה צדיק.
** שכל מלכי
0 על פי זה, מסתבר מה שנקט משמרותיו כנגד מלכים, שכל זה היה contrast להשכמתם. אולי שני דיונים אלו תלויים בהדדי.
* ד:
** ואי כר"ג –
אכתי, צריך ביאור מה חשבו בני ר"ג (שלא היה פשוט להם שרבנן מודו לר"ג).
** אבל אדם –
משמע שדין ק"ש גורם שיעשה כל הני דברים טובים. ותח’ למה.
** מקיש –
יש לדון מה הוה ההו"א. אשפר שכ"א סובר מסברה חיצונה כחברו. גם יש לומר שכ"א סובר בהו"א שאין קפידא (ואגב, יש להעיר שלכאו’ זה, הקפידא שיהיו תפילות באמצע, ה"ה החי’ בין שני מהלכים (ולריב"ל). ויש לדחות שאם אין קפידה, יקדים, שתדיר הוא (ויש לדוןשתפילות חול אולי אינו יותר מצוי. ונראה שבין הכל הוא יותר מצוי, שבשנה יש 708 ק"שו814 שמ"ע של חול (ועוד שאולי כל תפלה שווה). ותחשב. גם יש לדון, שק"ש דאו’, ועוד שהוא כל יום, אף אם לא קורה יותר.
** רש"י זה –
יש להעיר שבספרי (שלז) כ’ שיוצא בחצי היום (וכ"כ רש"י בסוף האזינו (כן הראה לי א.מ.וו., ומזה מצאתי הספרי). אם כן, לא יצאו בזמן הראוי לק"ש של שחר. יש לומר שאף על פי כן, הגאולה היה בזמן היותר קרוב והיותר דומה לזמן ק"ש של שחר. יש לומר שבקר היה קצת התחלה, יותר מלילה (לא נראה כן מלשון רש”י, מקרא שהביא). ודע שאם זמן ק"ש עד הנץ, אינו כל כך יותר קרוב.
** כיון שתקנו –
צריך לחשוב מה ר"ל. אולי ר"ל שכיון שקבוע שם מיוחס מאד לגאולה, ואינו מפסיק. ותחשב. סברה זו רק התחלה קצת, וצריך לחשוב.
** מפני מה –
כיון שהגענו לזה, יש לומר שמה שחשוב באשרי הוא שאין בו נון.
* ה.
** אמר אביי –
יש לדון אם ר"נ חולק על זה.
** אדם מוכר –
בגלגל אחר הקשינו למה לא דן במתנה, שתורה ניתן. אגב יש להעיר שקראו נתינה, ומביא "לקח טוב,” שמשמע שהוא לקיחה. יש לדון, שאולי אין לשון מקח משמע מכירה. יש לומר שקו"ח אמר.
** מוכר -
ע יין בנדרים, שדן בזה.
* ה:
** רש"י דהוו להו –
הק’ לי א.ד.ר. שלעיל אמר רש"י שניתן לו אף בלי עוונות. נראה שאפשר שמבאר שמיתת הבן ה"ה יסורים של אהבה, והוא מדכבר כפר אבלות (ר"ל שאז יש קצת הוכחה שיסורים של אהבה באים עליו, שאין צריך עוד כפרה.) וא"ת אולי חטא יותר. וי"ל שבר"י דן.
** מזבח כפרה –
יש לדון מהו החי’:
א. יש לומר שמז’ כפרה ר"ל שמכפרים, וייסורים של אהבה ר"ל שאינם באים על עונש.
ב. יש לומר שעושים דבר אחד, אלא יסורים של אהבה עושהו יותר טוב.
בהו"א, יש לדון אם סבר שחד דבר הם, או שמה שהוא מזבח כפרה מגלה שגם יכולים להיות יש"א.
** להאי שופרא –
צריך ביאור מה ר"ל.
** דיינא בלא –
לא הבנתי, שאולי יש"א היו, ואף שהיה לו לבדוק, כמו שאמר גמ’ לעיל, אין להקשות שעושה דין בלי סיבה.
** וימלאו –
וא"ת נלמד מזה שיהיו זכרים. ויש לומר שלא לומד כל מה שהוה אז, שהרי לא לומד שיהיו תאומים. ויש לדון איך יודעים מה ללמוד. גם יש לומר שלא נל’ ששם לא היו נפלים, אלא ממה שכ’, “וימלאו ימיה.”
** טורפים תפלתו –
צריך ביאור מה ר"ל "בפניו.” נראה שר"ל שאף אם כבר ניתן לו סימן שיצליח, לא יצליח. ותח’.
** למיחזינהו –
וא"ת הרי לא יעמוד. ויש לומר שאה"נ, וזהו ההיזק שדן לקמן, אולי. גם יש לומר שכאן רואה בלי רשות. ויש לדון ודחוק. גם יש לומר ש"עין לראות" רצה לומר עין מזיקין.
** שלש שיושבים בדין –
לכאו’, לא מז’ שנים או אחד לפי שלא מהני או שהיה חצוף. עיין בתחילת סנהדרין, שאין זה נכון לכל התנאים.
** חטיבה –
לא הבנתי איך רואים שנשבח ה’ בשבח ישראל, שרק רואים שהשביח ה’ את ישראל כיון שהשביחו. אפשר שר"ל שמה שבנ"י ה"ה עם מיוחד ה"ה ביחסם לה’, ובמה שמשבחים לה’ (וזה נלמד מאגדתא זו), ואם כן, שבח ישראל (שמשבחים אותם מחמת יחסם לה’) ממילא הוא שבח לה’.
* ז:
** רש"י אגרא –
העיר א.ד.ר. שנמצא שבכעין זה אין שכר לימוד. וי"ל שאין שכר לימוד כ"כ. גי"ל שיצא שכרו בהפסדו, שהיה לו ללמוד דבר שיבין.
** רשי אגרא –
רש"י פי’ שזה עיקר קבלתו. הו"מ לומר שאין קבלה חוץ מזה.
** שקול –
וא"ת מה אם יש שלש יראי שמים, שזה אינו שקול כנגד שניהם, וכן מה אם חד ירא שמים ות"ח וזה רק יר"ש (ויש לדון, שאולי זה יגלה שזה יותר ירא). ויש לומר שענין שקול ה"ה שגדלותם ביר"ש כ"כ גדול לנגד שאר קרק’ עד שהם כמעט שווים. למשל, כולם 99 מח’ יר"ש, והאחד שמוסיף ת"ח או כל שאר מדה טובה לא מעלה ולא מורד. (יש לדון, שמי יימר שתרי יותר טוב מחד. ותחשב. נראה שעל פי זה יכולים לבאר משנה באבות, שיש לומר שר"א נגד כה"ע וראב"ע נגד כה"ע היו, שהרי נגד מה שהיה כבר בהם, שווה, והשאר לא מוסיף כ"כ. ותחשב.) גם יש לומר שר"ל ששקול נגד כל שאינם יראים.
** רש"י אחורי –
והא דר"ה – זה בפי’ בגמ’, ולכאו’ צ"ב מה מוסיף.
** קמחללים –
נמצא שאף ע"ז נאמר לשון חילול שבת. עיין גם כן בשבת (קיט:). יש להעיר ששם ג"כ ר"ז היה. אולי שם "תחללנוה" קאי על עונג, ולא על שבת. וא"ת לשון נקבה היא. ויש לומר שעל סעודה הולך. אולי זה יותר טוב, שלא פשוט אם שבת הוא לשון נקבה או היא לשון זכר.
* ז.
** רגע –
קצת קשה איך בתוך הזמן אמר שיחכה, שקטן הוא. ותח’. ויש לומר שר"ל שכמו שמרגז אז, מרגז בעוד זמנים, כמו כשחטאו ישראל. ועיין לקמן.
** רבי מאיר –
וא"ת אם כן נודע מתי הוא – בשלש שעות. עיין לעיל. ונראה, אולי, שהוא זמן אחר שדרכו לרגז (ורק על גויים, ולכן לא הועיל לבדיק ולישראל), ורק הביאו כאן אגב שאר רגזנותוו ולהוכיח שמרגז. עיין בד"ה רגע.
** צדיק גמור -
קשה, שאכתי יש יסורים של אהבה. אולי צדיק גמור ממש א"צ אף יש"א.
** והסרתי –
ק"ק איך לומדים כן מכאן. נראה שק’ לו מה לנו הסרת כף, ומת’ שראה הסרת כף (ר"ל אחורי כפיו). ותחשב.
** פרו –
ק"ק, שהיו יותר ויותר מס’ רבוא, שרבים ורבים מתו במצרים.
** ראובן -
קשה מגמ’ ב"ב (קכג.).
** גרים –
משמע שהוה סיבה. בפשטות, רק מגלה מה קרה.
** שמח –
עיין בע"ז, שדן בזה. ובגמ’, מתחילתו משמע שר"ל ששמח במה שגיירו, שכן הוא, לכאו’, בשטר חוב, אבל לא ממשיך כן. וצריך ביאור. [איני יודע מה זה אומר; תעיין.]
** שאינו גמור –
קצת קשה למה לא מוקים קרא ד"אל תתחר" בזה (ולמה דורשים) ואולי סבר שמסתמא קרא דן בכל אדם, ואומר זה וזה. ודחוק. ותחשב.
* ח.
** תנ"ה –
זה משמע שקאי על תפלת רבים. גמ’ לעיל היה דן בתפילה בזמן רבים. נראה שק’ ר"נ היה "מאי כולי האי,” ולא למה יחשב כלל לתפלה, והוא שהניח שיש שום יחס על ידי תפלה בחד זמן, אלא שסבר שמסתמא אינו מועיל כל כך כיון שאין כל ענין תיבור עושה הרבה. דוחה גמ’ שתפילה בציבור מועיל הרבה, ולכן מקצתו (דהיינו, תפילה בעת תפילת רבים) גם כן מועיל קצת.
** ארבע אמות –
העיר לי א.מ.וו. בדיחה, שהיה לנו חבר (א.י.ש.) שהיה קצת אדוק אל מסכת פסחים, והעיר לי א.מ.וו. שבב"ב אומר ש"ארבע אמות שאמרו חוץ מן הפתחים (פסחים).
** גדול הנהנה –
קשה מסברה, וגם קשה ממש"א גמ’ בירא שמים שכ"א שקול לכה"ע כולו. ונ’ שכמה מאלו מניח שום מדרגב בסיסי של יר"ש או יגיעה, ורק דן בהוספה על זה. ותחשב.
גם יש לומר שמדובר במי שידוע להיות זה ולא ידוע לזה, שממה שהוא נהנה מיגיעו, מניחים שהוא גם ירא שמים (או שיהיה ירא שמים).
** רש"י ראו –
עיין במש"כ. אז, א"א ששם סיבה, שא"כ היה גלגל החוזר. יש לומר שהו"ל שום פוטאנשי"ל לזה, ושם גורם שיוציאנו. ותחשב.
* ח:
** לוחות ושברי לוחות –
מעניין מה שג"כ צריך להזכיר לוחות; הענין יהיה רק מה ששברי לוחות חשובים עד שהם בארון. אולי יש עוד ראיה לגדלותם ממה שהם עם הלוחות. גם יש לומר שר"ל שהיה חשוב כת"ח (לוחות), שהרי לא חילק ביניהם. (אגב, עיין רש"י שנ’ שלא גרס אלא שברי לוחות.)
** לילה הוא –
עיין בגמ’ לעיל (ב:). וצ"ב.
** מאי דקרי –
לשיטה שקוראים ק"ש של שחר עד הנץ, נמצא שאינו נקרא ביום כלל.
* ט.
** ועברתי –
זה, לכאו’, בחצות. אז:
א. לשון גמ’ "מה כאן עד חצות" קצ"ב.
ב. ק"ק איך נל’ ממנו. אולי רק לומ’ שחצות הוא זמן חשוב בו, ומסתבר שיהיה זמן סוף שלו.
** ואילו –
קשה למה אינו אפשר שהוא בכלל הנאכלים ליום אחד. צריך לומר שכיון שרק בלילה נאכל, אינו בכלל זה. ותחשב.
** ומועד -
משמע שיצאו בבקר (ששורפים, לכאו’, מיד). עיין בספרי (שלז) שכ’ שיצאו בחצי היום.
** מאי חפזון –
וא"ת הרי ראב"ע דרשו מקרא אחר. ויש לומר שבא לבאר איך מבאר קרא דחפזון. לולי זה, הו"א שאין הוכחה שבאמירת "חפזון" אומר זמן קרבן פסח.
** תנ"ה –
יש לדון מה זה מסייע:
א. חושב שהיה חפזון בלילה, שסבר שאז התחיל גאולה. דנים רק אם חפזון דקרא הוא אותו חפזון.
ב. חושב שהיה גאולה בלילה. אז, יש צד שהיה חפזון בלילה. אם כן, יכול להיות ששני התנאים מסכימים לבריי’, ודנים רק אם אף הוה חפזון.
ותחשב עוד על כל זה.
** רש"י ובלבד –
תחלת – אם כן, יפסקו אחר משמר ראשון. ותחשב.
* ט:
** כמצולה –
לא נראה שדורש "וינצל" להיות לשון מצולה, שאין זה משמע מה שרק הוא. וצריך לומר ש"וינצל" רצה לומר וירקן, כמו ללשון ראשון. אפשר שסובר שגם מרמז למצולה, שכיון שכבר גילה שנתרוקנו, זה משל טוב. ותחשב.
** רש"י בין –
יש לדון מה, לרש"י, הוא ענין של תי’ הגמ:
א. כיון שהם קרובים זה לזה, יותר קשה לדעת איזה תכלת ואיזה לבן. יש לדון אם זה אמת.
ב. כיון שהם בחד עמרא, השינוי ביניהם הוא gradual, ולכן קשה לחלק ביניהםי.
ג. הגוונים יותר קטנים, שהם כולם בעמרא אחד.
לולי רש"י, היה אפשר לומר ש"בה" קאי על הציצית. הענין יכול להיות כראשון או כשלישי. עיין בירושלמי, שמשמע כצד זה.
** דאמר רשב"נ –
מביא ראיה למה שהם חד פרשה בתוך דבר שהביא לראיה. ותו"ת.
** ורשעים –
צריך ביאור מהו ההוכחה מכאן, שאף אם יתמו חוטאים, רשעים עוד אינם. אפשר שאז כופל את עצמו, שזה אותו דבר.
** גג ומגוג –
קשה, שנאחר אף זה (א. אז, יהא מעשה אבשלום מאוחר. ב. מעשה גג ומגוג יאחר). ויש לומר שלא דן מתי אירע מתי שעליו נאמר פרק, אלא מתי נאמר פרק (אלא שידוע שמה שאמר בו "בברחו" נאמר בעת ברחו).
** קמיה דר"ש –
יש לדון מי הוא האומר לו. משמע שר"י הוא שאמר לו. צריך ביאור למה האחר הוזכר כאן כלל. ותחשב.
** תולה לו –
יש לדון אם ר"ל שלכך תולים או שכך אומר ה’ (וחסר כבוד). וא"ת איך צד שני אפשר, שא"כ נמצא שתורה מוציא שקר. ויש לומר שבזכות שניהם יהא, ותורה מז’ רק אחד. לראשון, קשה למה ירצה שיעשה בזכותו. אפשר שהוא לשני. גם יש לומר שאז נח’ סיבה לכל הטוב הבא ממנו. ותחשב.
** לשלום מר –
נראה שר"ל שלפעמים ה’ עונה שלום ועונה לתפלות במררות, ולא תולה בזכות המתפלל.
** מקריב תמידים –
קצת קשה למה נקט לשון רבים, שקרא רק נקט לשון "תמיד.” ותחשב.
** מאי לא הפסיד –
אם כן, הדמיון ללומד תורה צריך ביאור. נראה שיש מצווה וענין בלימוד ק"ש, ואז מברכים. עדיין הלשון צריך ביאור.
** בערב-
מעניין שכאן מקדים ערב, ולא כלקמן שמקדים שחר. עיין בגמ’ בריש המס’. צריך ביאור.
** אם כן –
קשה שלעיל לומד גמ’ נפ"מ מדכ’ "שכיבה" ו"קימה" (ע"ש). אולי ב"ש לא סובר כן. ק"ק מהי"ת שלא לדרוש כן. יש לומר שסבר שלא מסתבר שיהיה דבר התלוי בזמן אפשר רק בזמן קימה, למשל, שנמצא אז שיש לילה המועיל ויש יום המועיל, ויש יום שלא מועיל ויש ילה שלא מועיל, ונמצא שיהא חלק מיום וחלק מלילה. ותחשב. עדיין צריך ביאור, אז, מהי"ת שיקרא בלילה וביום. ויש לומר שלא מס’ שכ’ זה רק לומר איך לקרוא, שאז היה לו לומר לשכוב. אלא, גילה את הזמן. עדיין לשון "בשכבך" קשה, שהיה לו לומר יום ולילה, או, על כל פנים, בוקר ולילה. אז, דורש גם את זה. ותחשב. אם כן, אולי תחילת זמן ק"ש תלוי בזה. אם כן, ההמשך מובן.
** דקאזיל –
קצת קשה, שנימא "מה דרך שאינו מצווה (אלא, אולי הכשר)….” משמע שרוצה מקור אף לפטור הכשר מצווה. ותחשב.
** לא קיימת
0 כמובן, צריך ביאור, שזה בחומ’, וזה בקולא.
** ובקומך –
מקשים העלום ל"ל קורא ק"ש כל היום, שכולו זמן קימה, כמו שכל הלילה זמן שכיבה. יש שמת’ שששכיבה רצה לומר להיות ישן, וקימה ר"ל לעשות מעשה קימה. אם כן, אכתי קשה, שב"ש, שרק אומר שצריך להיות עומד, ואם כן נמצא שסבר שקימה ר"ל עלייה, ואכתי כ’ שהו"ל לקרא לומר "בוקר.” נראה שאולי מפרש קרא באופן חלוק, כיון שלא קאי על זמנו, שאז מוכרח שר"ל עמידה, שלא נראה שאדם יקרא אותו כשקם. ותחשב.
** מקרא –
קצת צריך ביאור למה יותר יצטרך בו ברכה:
א. אפשר שהוא יותר קדוש, ולכן לימוד שלו יותר קדוש (עיין לקמן), ואז יש יותר צורך ללמוד.
ב. אפשר שנלמד על ידי קריאה. זה אופן חשוב של לימוד, ורק על כעין זה מברכים.
- בענין ברכת התורה, הפשטות הוא שמברך על מצוות לימוד תורה. זה דחוק, שאינו נראה כן מלשון שלו. עוד, שאז קשה מהו הצד לחלק בין מיני תורה, שבוודאי מקיים לימוד תורה בלימוד כולם. צריך ביאור אים זה אמת, לא לא יהיה ברכת מצווה. אולי לא רצו לחלק בין ברכות לתורות חלוקות, שיתקנו רק ברכה למה שלא כבר תקנו עליו ברכת התורה, שיקיים ענין ברכת המצווה. ויש לדון, שהרי תקנו ברכה רק לחלק אחד. אפשר שאין צווי של לימוד תורה מוסיף כל כך קדושה, שבין כך ובין כך היה צריך ללמוד כדי לדעת ולקיים. יש לומר צד שתורה ה"ה של ה’ (אלא, שצל"ע בקידושין בפ"ק), וכיון שאדם משתמש עמו, צריך לברך, כמו על פרי, והוא שכשחפץ הוא של ה’, יש חיוב לברך לה’ כדי להשתמש בה. לכאו’, רצה לומר שנותן לה’ שבח, ובחילוף נותן לו ה’ רשות. לכן, אם לא נותן, מחשיבות גמ’ לגזילה. ודע שבתורה על כל פנים, יש לומר שכיון שרצה ללומדה, ומגלה כן על ידי ברכה האומר כמה רוצה, ורק א"א כיון שנאנס במה ששל ה’ הוא, נח’ כקיימו קצת, שה’ מצטרף מח’ למעשה, ונעשה שלו, כבקידושין, ואז אפשר. ותחשב. על כל פנים, אם נאמר כן, אולי ענין מקרא הוא שזה יותר של ה’, שאינו בא מדעת בני אדם כלל.
גם צריך לבאר למה יש הו"א שרק מדרש צריך. אפשר שמדרש ג"כ חושב, וחשוב יותר ממשנה. מה שקאי על קראי הוא סיבה לחשיבות שלו, והוא שעושה טובת התורה (או, עכ"פ, שייך לברכה) יותר מפני יחס למקרא, או שנכלל בדין מפני יחסו לתורה, והוא כעין לא פלוג (ודחוק). לצד שאינו מח’ חשיבות התורה, אלא מח’ שנל’ ע"י קריאה, צריך לומר שמדרש בא בל"פ. לצד שתורה יותר הוא של ה’, יש לומר שכיון שבא יותר (ר"ל יותר דייקרט) מתורה הכתובה, יותר הוא של ה’. ודע שבמש"כ בקנוי לה’, צריך לבאר למה זה יהיה רק בקראי, ולא בהל"מ, אם לא שנאמר שכיון שהם בכלל תורה שבע"פ יש לא פלוג או שנאמר שכיון שזכרון בני אדם קיים אותו, יותר נחשב של בני אדם.
** השכים –
לשון השכים כאן משמע שלא היה דרכם להשכם כ"כ (שאל"ה, לכאו’ היה לו לומר "קודם ק"ש.”)
** מאי מברך –
קצת צריך לדון מה ידעו, שאי לא ידעו הברכה כלל, הו"ל לומר כל נוסח הברכה. אם ידעוהו כבר, נצטרך לומר שידעוהו, אבל לא ידעו מתי נאמר. ותחשב.
** יוצר אור –
קצת מעניין מה שמק’ על זה ראשון, שהרי זה כקרא (ולכאן’, הפשטות ה"ה לעשות כקרא). ועוד, שזה קמא, והו"א שזה קובע. ותחשב.
** רש"י ד"ה אף –
שהוא עיקר – וא"ת א"כ למה הוא אף. וי"ל שמה שהוא עיקר התורה אינו הפקטור היחידי לברכה. עיין לעיל. ותחשב. גם יש לומר שרק בא להוסיף על שאר אמוראים, ולכן אומר "אף.” ותחשב.
** מפני –
וא"ת הרי קוראים שאר שמע. ואולי לא ישמעו כל מחה שקוראים.
** כי קאמר –
מעניין, שאף בכ"ז, לא מהני חד ברכה לחברו, ואז נמצא שכיוון לדבר שלא מהני. אפשר שיהיה יותר טוב אם נאמר, שהבעיה בשינוי ברכות אינו שאין ברכת שחר טוב לערב (ר"ל שלא כולל כ"כ עניני ערב), אלא שכולל דברים הרעים בערב, והוא כ"כ הזכרות שחר. אם כן, נמצא שכיוון למה שנצרך לערב, אלא שאף כיוון למה שרע לו. אולי זה עושה גמ’ יותר מסתבר. ותחשב.
** כשהוא כורע –
קצת קשה למה לא אומר "המתפלל כורע.” מרש"י נראה שאז היה משמע שעושה כן בכל ברוך.
** רשי שאני התם –
יש להעיר שני הערות על זה:
א. אם כן, נמצא שיוצא במה שמכוון להיות מקצת ברכה. אין זה בעיה, אלא קצת מחודש.
ב. לשון "שאני התם" מעניין, שמשמע קצת שמתים הם, ולכן יש לזה אותו דיון שדנים בו בשני (יש לדון. ותחשב.). לרש"י, אינו כן כ"כ, שדינו חלוק, שלא אזלינן בתר סופו, אלא בסופו יוצא.
אז, לולי רש"י הו"מ לומר שאולי כאן אזלינן בתר סופו, כיון שסופו חשוב במה שיכול להיות ברכה בפני עצמה. ותחשב.
* יג.
** כי כרע –
קצת קשה למה צ"ל "כי כרי.” הניחא לרב, כיון שאמר "ברוך" היה משמע שקאי על כל ברוך, ואז צריך לפרש. ר"ש לא מזכיר שום זמן, ואז פשוט שר"ל "כורע [בזמן שצ’ לכרוע] כחוורא.” אולי הוא רק אגב לשון רב (אולי אמרו אכן או אולי גמ’ הביאו כן אגב לשון רב). ותחשב.
** עמי –
וא"ת מהי"ת שמחלו לו על כל עוונות שול, ולא רק נעשה יותר זכאי מחייב. ויש לומר שאכתי לא יהיה במדרגת שמואל אז (עיין בחגיגה ה).
** יצתה –
לכאו’, א"צ זה לראיה, שממה שקראו כן קרא יש לזה ראיה. ועיין בדיבור הבא.
** יצתה בת קול –
לכאו’, זה לא נל’ מקרא, אלא קבלה הוא. ויש לדון. יש לומר שלא היה קרא מבאר תואר שאול בתוך דיבור גבעונים. ותו"ת.
** רבית –
וא"ת למה פרשת רבית יותר טוב. ויש לומר שלא יודע גמ’ מה יותר טוב, ואז דן איזה נבחר. גם יש לומר שרבית יותר טוב שגם מלמד דינים. עוי"ל שרבית יותר טוב שלא נהפך לקללות כברכות בלעם.
** חמשה –
מונה ששה (וראיתי שי"ג ששה). אולי מונה הרהור עבירה וע"ז לחד. דחוק. וא"ת ל"ל מונה מינות עמהם. וי"ל שזה לחשוב שמינות נכון, אבל אלו (הרהור עבירה וע"ז) הוא לחשוב כמה רוצה לעבור.
** רש"י ד"ה זקיף –
כמש"א – הו"מ לומר שזה ג"כ סיבה למה כורע כחוורא. מדלא אמרו רש"י שם, קצת משמע שאינו הסיבה (שכבר יש סיבה אחרת). צריך לדון מהו.
** רשי בקשו –
עיין במש"כ. וא"ת אם כן נחושב לתרעומת המינים. ושי לומר שלא יכירו מינים במה שיש בו עשרת הדברות. עוד יש לומר שלא יוכלו להכיר עשרת הדברות כי אם בק"ש, וא"כ, ידעו שיש אף שמע (כמש"כ לעיל בד"ה מפני). עוי"לש אל ידעו שהוא מרומז שאר מצוות (שהניחא אם נאמרו עשה"ד, בוודאי יהיה להם יתרון, שרק הם נאמרו בפירוש, אבל כאן, שרק מרומזים, מי אומר שרק אלו מרומזים).
** הרי אני כבן –
צריך ביאור למה זה שייך. אולי ר"ל "אף שחשוב אני, לא היה ביכולתי לעשות שבני אדם יעשו כמותי.” דחוק.
** משכחת –
משל זו, לכאו’, הוא לבן זומא. אולי לרבנן הוא, ור"ל שנשתכח מפי בני אדם, ואכתי יש חיוב ק"ש, ועל שכחת בנ"א, חוץ מבק"ש, דן קרא.)
** פרק שני:
* יג.
** יראה-
יש לדון למה הותר:דחויה. ב. הותרה (והוא, שיש הפסק קצת באמירת שלום. אם עושה כן בדעת, ומכוון להפסיק, מפסיק יותר, שמראה בעצמו שסובר שאינו בעיה להפסיק שאינם כ"כ מיוחסים. כאן, אין הוספה זו, שיש לומר שמשיב לו או שואל לו כיון שהוא חשוב (שנדחה). ותחשב.
** באמצע -
לכאו’, הענין הוא שאז אין צריך רק חבור ברכה זה לזה אלא אף חבור ברכה לעצמה. ותחשב. אפשר שכדי לעשות חד ברכה חד, צריך יחס יותר חזק, ואז צריך יותר שלא להפסיק. גם יש לומר שיותר גרוע אם אין ברכה אחת אחד מאם אין ברכות מיוחסות זו לזו. גם יש לומר שחצי ברכה לא כל כך מיוחס לחצי אחר, שברכה מיוחס לברכה במה שעושה דבר שווה, זה רק בברכות, שכ"א עושה דבר, אף עם ההפסק. אבל, בחצי ברכה, שרק חצי הוא, ואינו עושה כלום בלתי חבירו, אינם שווים בתוצאתם עד שמחבר אותם. ותחשב.
** להגיה-
יש לדון למה צריך לכוון לקרא:
א. אפשר שבלי זה, נחוש שלא קרא כולו. (כן נראה מרש"י ר"ה, וע’ בתוס’ כעין זה.)
ב. אולי ליחס למעשיו, צריך לכוון על כל פנים לעשות אותו. נראה שאפשר שכן הענין של מצוות צריכות כוונה, שסבר שכדי ליחס למעשיו, צריך שיכוון לעשות אותו, ומעשה מצווה חלוק ממעשה שאינו של מצווה. לכן, אם לא מכוון למצווה, ונמצא שלא מכוון למעשיו (דנים, אז, או כמה חלוק הוא או כמה חלוק יכול להיות). ותחשב.
** כיוון לבו -
קשה למה לא מתרצים שרצה לומר שצריך כוונה לפי’ מילים (כר"א ור"ע לקמן). ותחשב.
** על לבביך יכול-
ר"ל על לבבך [-צריך כוונה] יכול…, אלא שהדרשה כ"כ פשוט שאין צריך לכתוב אותו. ותחשב.
** לה"ק -
יש לדון אם היותו באותו לשון ה"ה הסבה או שבכתיבת שמע יש שום ד"א טוב, ובתרגומו לא יימצא (למשל, מנןי האותיות הוא תרי"ג או כדומה).
** ואצ"ל -
צריך ביאור בכל כזה למה, אז, אומרו. וקצת משמע שאין בעיה באמירת דבר שאין בו חידוש, שאולי הוא יותר בהיר אם נאמר, ויש בעיה רק שבני אדם יחשבו שיש בו חידוש. אבל, יש לדון למה יחשבו כן אחרי שנודע שלא צריך להיות חידוש בדבר כדי לומר אותו. כנראה, טועים לחשוב שיש הכרח לחידוש. אז, לא יאמר אותו אלא אם כן אומר עמו שאין בו חידוש. ותחשב.
** ע"כ צריכה (ר”מ)-
קצת צריך ביאור מהו מקורו (א. מהיכי תיתי שצריך כוונה כלל. ב. מהיכי תיתי שרק זה צריך כוונה.) אפשר שמסברה הכיר שענין המצווה הוה לקבל עול מלכות שמים, ואז פשוט שהדבור בעצמו לא יצא מה שהוא רק בראשון ה"ה מפני או כמו שיטה שלקמן שיש צורך רק בקרא ראשון. ותחשב.
** רשי ובדל"ת -
עד כשיעור-מה שלא אמר "עד שיעשנו" משמע שאין הענין שצריך להאריך עד שהמליכו, אלא מאריך אותו זמן. ותחשב. ויש לדון.
** לייט –
קצת קשה למה לא מתרץ גמרא שזה רק בישן (שכן היה נראה מטעם שכ’ רש"י).
** בעל כשר –
כמובן, יש לדון אם נדחה מחמת צערו או הותר (שאז לא נראה כגאווה).
** יטעום –
לכאו’, אכילה ר"ל "אכילה שבו מכוון להנאה הבא מן המאכל" והוא שמדרהר אני שהנאת אכילה או מעיים יותר דיירקט, משא"כ ידיעה שרק גורם שיעשה תבשיל טוב, ובאכילתו, יהנה. כמו כן יש לומר שאכילה ר"ל לאותו צורך שבני אדם בדר"כ אוכלים.
* יד:
** ללמוד –
נראה שני מהלכים בזה:
א. ללמוד ה"ה הכי חשוב (יש לדון), ואז אומרו ראשון.
ב. ללמוד, כמובן, צריך להיות נעשה ראשון. לזה, קשה למה ללמד קודם לעשות. לזה, נמצטרך לומר כראשון או שלישי.
ג. פרשה שיש בו שלש חשוב משיש בו שנים.
לראשון ושני, נצטרך לומר שק’ גמ’ הוא שכיון שיש ג"כ ללמד ולעשות, היה לו למנותו. ודחוק, אלא שלכאו’, כו"ע צריך להסכים לזה, שאל"כ איך נפרש הק’ על ההו"א. ויש לדון, שלשלישי, יש לדון שמק’ לל"א שלישי.
** נראה
שיש לדון בקדימת פרשה, אם הענין הוא שכל הפרשה נחשבת במה שיש, למשל, לימוד בו או שקרא או ציווי של לימוד נתחשב, וקודם. שאר הפרשה צריך להיות עמו, ואז אף הוא קודם. לשלישי שלעיל, לכאו’ צריך להיות כראשון. ויש לדון. הדרך לדחות הוא לומר שאם יש רק סיבה לנתק הפרשה ולהקדים אותו, לא יקדים, ואי יש יותר, כמו אם יש צורך להקדים כמה קראי, אז ננתק. ויש לדון.
** כאילו מעיד -
רצה לומר שגלה שלא מאמין מה שמעיד בק"ש, שהרי לא מניח תפילין הכתובים. ואגב, ק"ק לל"א כן גבי מזוזה. גם קשה למה לא מעיד עד"ש שיש לומר שימתין ויניח תפילין לאחר זמן. ותחשב.
** רבינא לרבא –
יש להעיר שביום שמת רבא נולד רב אשי (רבו של רבינא). אולי זה רבינא או רבא אחר, ודחוק. שו"ר שתוס’ אומר שיש שני רבינא. עוד יש לומר שרבינא היה קשיש מר"א. כעין זה, מצאנו ברהבדר"י ור"פ שהיו תלמידי רבא (עירובין כו.), והיו קשיש מיניה (גיטין עג.). ותחשב.
** דיעבד –
וא"ת כבר אמר שבדרבנן סבר ר"י שלא מעכב. יש לומר שלעיל רק ר"ל שברכה לא מעכב. הסיבה לזה הוא שמדברנן הוא. אבל אי לעולם לא מקיים אותו דין דרבנן. גם יש לומר שמגולה ה"ה מדברי נביאים. גם ישלומר שאין צריך צד זו בר’ יוסי כיון שמצאנו תנא אחר האומר כן. ולא נראה כן, שאינו נראה שגמ’ אומרו מן הדחק. ותחשב. צריך לתקן את הלשון.
* טו:
** שאר מצות –
אז זה דוחה כמה מן התליות ונדונים לעיל.
** מכאן –
לכאו’, רצה לומר מדרשה זו, ולא מקל וחומר זו.ויש לדון, שאולי בלי קל וחומר, הו"א שמכוון לגלגולים (ובמס’או יש ג"כ תחיית המתים או אין גלגולים כלל).
** עושים –
צריך לחשוב על זה, שלכאו’, החידוש הוא רק בכמה שכרו. אם כן, הו"מ לחלק בין נוטל מנה למאתים (אלא שאמת נקט, שזהו הגדר שנקטו חז,ל. ותו"ת.)
* יח.
** באמת –
יש להעיר שמשנה של מתו דן בציור שהיה בתוך דור בית. משמע שא"א לענין זה שכל הבית כד"א. צריך לתקן.
* יח:
** רש"י ונחת -
קשה, שקודם לעזרא היה, ולא גזרו כבר. ואולי ידע סיבת עזרא, ולכן החמיר בעצמו. ויש לומר, ואולי זה שווה, שהיה כעין קיים עירוב תחומים של האבות. שוב ראיתי בגליון הש"ס. ועיין שם.
** רש"י חצר –
היה אפשר לפרש, ואולי כן מפרש, שהוא חצר המת המוזכר בב"ב (קא).
* יט.
** רשי על כולם –
גם היה מצי לומר, ולא נראה כן מרש"י, שרצה לומר שבצירוף כולם, לא היה כ"כ חכמה ויראה כעקביה (וענין צירוף זו ה"ה לצרך מעלות כל אחד למעלות חבירו). ותו"ת.
** אין עזרה ננעלת –
יש לדון אם רצה לומר בחד פעם או בין כולם (שננעל יותר מחד פעם ביום ערב פסח). וזה רק נוגע לפשט שכ’ בד"ה על כולם, ולא לפשט שכ’ רש"י.
** נט"י –
וא"ת יהא כן על כל דרבנן, ואם כן, בוודאי היה יותר מכד’. ויש לומר ששאני נט"י שכ"כ קל הוא (עיין בכורות (ל:), ולכן אם לא עושהו מגלה יותר בזיון לרבנן. ותחשב. (בענין מקבל לכנפים.)
** רש"י אילמלא -
יש לדון מהו כוונת רש"י:נראה שהיה קשה לרש"י איך זה סיבה שלא ינדוהו. אז, תי’:כבר יצא שמו לטוב, ויהיה נראה רע לנדותו. ב. כבר יוצא שמו לטוב, ואז ידע שהיה איש טוב, ולא רצה לבזות ה’. ג. כבר יצא שמו לטוב, ולא ביזה ה’, שכו"ע ידעו שלא היה עושה כן, ואז הבינו שמעשיו היו בכבוד.
** אלמלא –
נמצא שבכלל "כבוד הרב" הוא כבוד ה’. הו"מ לגמ’ לדחות הנחה זו. ותו"ת.
** מה אעשה… שאתה מתחטא -
יש להעיר שמרש"י נראה שהסיבה אינו זה, אלא מה שכבר יצא שמו לטוב. אולי ע"ז - מה שנענה תפילתו כ"כ כמה פעמים – יצא שמו לטוב. ותחשב.
** לכבוד-
יש לדון מה רצה לומר: כדי שלא יבזוהו עוד. ב. לגלות שראוי ליכבד (שהמגלהו נענש). וא"ת אם הענין הוא שמגלה שהמבזה ראוי לענש, היה לו לענשו מחמת זה. וצריך לומר שיש שני סיבות, ודחוק. ואולי צריך צירוף זה.
** אלמלא חוני –
עיין במה שהקשינו לעיל על רש"י. ויש להעיר שלכאו’ קצת קשה מגמ’ עצמו המזכיר "אילמלא חוני,” ו"כבן….” שלכאו’ אין צריך שניהם.
** גוזרני –
מניח גמ’ שבכל אלו ציורים, נדו לכבוד רב, ולא מפני שאי לאו הכי, יזלזלו יותר ויותר בנט"י או פסח, וזה רע. ותחשב.
** רש"י מדמה –
ראוי –
יש לדון אם מנה אף מקומות הראויים או שמנה מקמות שנדו, אלא שכיון שראויים היו, הניח שנדו. לראשון, ק’ פשוט שינדוהו אם ראוי הוא, דאל"ה, אינו ראוי. וצריך לדחות שראוי הוא רצה לומר בעיקר קרק’, או שר"ל שיש סיבה (ואולי אף יש מניעה). ודע שאם נאמר כראשון, הומ"ל שלא חול’ אם לדין למקום אחר לומר שראוי הוא, אלא שסבר שלא למנות ראוים. ונראה שכיון שריב"ל הוא המונה, פשוט שהמנין ניתן שם ממנו, ואי אפשר לחלק על מה הוא המנין. צריך לתקן.
** בכד –
יש להעיר שחושב אני ריב,ל הוא האומר שבכד מקומות כהנים נקראו לויים. אולי זה נאמר אגב זה. ותחשב.
** כבוד לרב –
מניח גמ’ שנל’ זה מזה. ודע שלכאו’ יכול לקרא לדרוש על כל אחד מהם. ותחשב.
** מדלגים –
קצת קשה מהיכי תיתי כל הני דטומאה היו באיסור דאו’ לכהן ליטמא, ולא באי’ דרבנן לכ,א ליטמא (ע’ בכורות ל. ברש"י, ועיין ברש"י בשבת (יג).) ואף אם אינו דרבנן, אולי אלו הקפידו. ואולי זה יש לדחות לומר שא"כ פשוט הוא. ואולי ידוע היה שראב"צ היה כהן. ויש לדון, שאכתי אולי ראשון קשה. ותחשב.
** ומשום כבודו –
לכאו’, רצה לומר שלא גזור כלל, וממילא הותר. לכאו’, זה עיקר התי’. צריך ביאור למה צריך, “כל מילי" אולי רק בא לבאר שדן באיסורי דרבנן, ולא באיסור דאו’, שלא לשמוע לב"ד.
[אגב, שמעתי שאלה בציור שכל אדם היה זכאי בשני טיקיטים לגורל, וכולם נטלו אחד, מהו הדין, שנמצא שלפני שתפס חד לזכות בגורל, אין נפקא מינא בהיותם אחד או שני קטיקטים, שכל אחד יש לו אותו אפשרות לזכות כאילו היה ניתן שנים. אבל, לאחריו, נמצא שמי שזכה רק זכה כיון שרק אחד ניתן, ולא שנים, שאם היו שנים ניתנים, אותו טיקי"ט שהעלה היה שייך לאחר. ותחשב. ]
[גם, אגב, מעניין מה שלא מצאנו שום משנה מבאר מה אומר בקריאת שמע. ותחשב.]
** תרנגול -
לכאו’, ההו"א הוא שנהרג כדי שלא יהרג עוד, וזה לא מצוי שיהרג. המסקנא הוא או שלא מפני זה נהרג (נראה שנהרג מפני יחסוו רע להריגת אדם), או שלא פלוג הוא, או שאף בתרנגול חוששים שיהרג קטן אחר. ותחשב.
** בקר-
צריך ביאור למה מניח גמרא שבקר וזמן תפילה של שחר שווים. שוב הבנתי שהוא מפני שזמן תפילה תלוי בזמן התמיד (ובזה, באמת, חולקים במשנה, שחולקים מהו זמן תמיד), ובתמיד כתיב בוקר.)
** שמע מינא הלכה כרבי יהודה -
אם נאמר שבתוספת שבת אדם עושה אותו לשבת, ולא רק מתחיל לנהוג דינים של שבת, אז הראיה מכאן צריך ביאור, שאולי יכול רק מפני שעשה אותו כבר שבת. צריך לומר שאף אם יכול לעשות אותו כבר שבת, לא יכול לעשות אותו כבר לילה, והרי צריך להתפלל בלילה, לפי החכמים.
* כז:
** אמליך -
משמע שאשתו בכלל בני ביתו. (עיין לעיל כד.).
* כח.
** הוה -
יש לדון אם רצה לומר שכן נתוספו או שכן היו אחר שנתספו.
** ונקרא פושע -
יש לדון מה רצה לומר:
1. נקרא פושע אם מאחר, ואף שמקיים אותו, והוא שגילה בעצמו שרגיל לפשוע, שפשע לאחר כל כך, ואף שרגיל שאז יאבד מצווה זו.
2. אם פשע ולבסוף נאנס, נקרא פושע. מדאמרו כאן, משמע שזה רק כאן, שפשיעתו מרובה, שהו"ל כל כך זמן.
** הל’ מתפלל -
ק"ק ל"ל אמר שהל’ כרבנן.
** א"ל -
צריך ביאור למה היה כל כך מרגיז על ר"י; אטו לא הניח לשום אדם לחלוק עליו. וקשה, אז, איך מצאנו כ"כ מח’ עם ר"ג. ואולי הו"ל לר"י לשאול לר"ג. אם כן, לכאו’, אף אם הו"א חוב, היה נענש. גם יש לומר שידע ר"ג שר"י ידע שחלק עם ר"ג, ולא היה מניח לשום אדם לחלוק עליו בהוראה למעשה. גם יש לומר שהיה לו להזכיר לתלמיד שר"ג חולק.
** מעלים -
לכאו’, אכתי יש בעיה זו למסקנא.
** רש"י נקרא -
משמע כצד ראשון שכתבנו.
** תברא… צער -
לא הבנתי מהיכי תיתי לשנות.
* כח:
** כיון שראה -
יש לדון למה עשה כן רק כשבאו תלמידים. אפשר שעד כאן, לא הכיר שהיה עומד למות.
* כט.
** טעה שאני -
לכאו’, רצה לומר שרק בדיעבד הוא, כשטעה, ולא לכתחילה. גם יש לומר שעברה על אמירתו בברכת השנים בדעת מראה שאינו. ולא נראה, שכאן אנוס הוא, שא"א לאמרו, ואיך נלמד מיניה משמעות.
** ונימרה -
אף בסוף לא נטרד.
** בציבור -
קצת יש לדון למה זה יחלק בין הזכרה לשאלה.
* כט:
** עברה -
מגמרא נראה שני דרשות ממנו (“עברה" ו"כאשה עוברה"). ותחשב.
** מכוון -
לא הבנתי למה אין (הגמ’ אומר ש)כ"ע מכוונים לכפרת. ותחשב.
** רש"י עד פרסה -
הניחא לצד שני, שיעורו מסתבר, שאם קטן הוא, אי"צ כל כך תפילה, שאינו מצב סכנה כל כך. לפשט ראשון, צריך ביאור. אולי רצה לומר שכבר נפסק דין על הליכתו. גם יש לומר – וכן נראה מלשון גמרא – שתפילה זו עושה שאלת רשות, והוא שהוא כמו שאומר, “יודע אני שאני צריך לה’ בהליכה זו.” כיון שכבר הלך פרסה, גילה דעתו נגד זה, שהוא לא צריך שאלת רשות, ואין עוד צורך גדול בברכה זו.
[[כאן כתבתי כמה נקודות שנוגע לסיכום שכתבתי.
אם קריאת שמע מדרבנן (כר"י (כא.)), קשה מה עושה עם כל הדרשות מ"בשכבך.” אפשר שהם אסמכתות, ואסמכו רבנן לומר שקאי על קריאת שמע. דחוק. עדיין, אז, אותו הקושיה קשה, אלא שעכשיו קשה לכולי עלמא, שכולי עלמא צריכים דרשות משם (או לומר שאין מהם משמעות). אולי חוטלק רק בשאר קריאת שמע, אבל מודה שפסוק ראשון האו חיוב מדאו’. ויש לדון, שמהיכי נלמוד (ואם לא נל’ מ"בשכבך ובקומך,” כמו שמוכרח מקושיית גמרא, לא יתרץ קושייתינו.) ותחשב. (זה נוגע לI שבסיכומים.)
** יש לדון לצד
שהוא מדרבנן, מה חייב לקרוא מדרבנן. (זה שייך לII שבסיכומים.) אפשר שמדרבנן "דורשים" כאילו "בשכבך ובקומך" או שאר דרשות הגמרא. אז, אולי הדינים שווים.
** לרבי
(יג:), יש לדון אם חייב בשאר מדרבנן, וכמה חייב. נראה שיש חיוב (על כל פנים לר"נ) מדרצה לקראתו אם אינו מצער. ויש לדחות. זה שייך לIII שבסיכומים.
נראה שחיוב דאו’ של קריאת שמע הבא מ"בשכבך ובקומך" יהיה נצטווה על ידי "ודברת בם,” שקאי על "הדברים האלה.” אז, יתלה במחלקת מה הם הדברים האלה, שהביא גמרא למחלקת מה צריך כוונה. (זה נוגע לIV שבסיכומים.)
אגב, קשה לל"א בריש פרק שני שצריך כוונה לפירוש מילים.
אגב, יש להקשות לל"א ריב"ק שראשון מקדים כיון שהוא מדאו’. אפשר שהוא מפני שכבר מצאנו שאף ש"ויאמר" מדאו’, כיון שיש בו יציאת מצרים, לא מקדים. ויש לדון, שאולי צריך להיות בסוף, כדי להתחבר לואמת ויציב. גם יש לומר ששאני "ויאמר" שאין החיוב לומר אותו פרשה, אלא לומר אותו ענין. כמו"כ, יש לומר ששאני "ויאמר" שיכול לקיים אותו באמירת דבר אחר, כמו אמת ויציב. עוד יש לומר ששאני ויאמר שיש לו בעיות אחרות. מה שלא מנאם בשמע ה"ה שהיותם אינו סיבה להקדים, אלא עושה שאין סיבה לאחר. (יש לומר שהיותו מדאו’ אינו סיבה כלל להקדים.) יש לומר שסבר שכולו מדרבנן. עוד יש לומר שסבר שכולו (על כל פנים פרקים ראשון ושני) מדאו’, ואז, כיון שיש בויאמר גאולת מצרים, כולו מדאו’. נראה שאם נאמר שמוכרח שסבר שכולו מדרבנן, נוכל לתרץ מה שהקשינו לעיל בד"ה יש לדון לצד, שאין הכי נמי, חולק על כל דרשות אלו, אלא שסבר שתנאי הוא, והולך כריב"ק.
אגב, קצת צריך ביאור מהו דרשת רבי עקיבא (יג:).
הקורא את שמע, צריך שיכוון (יג:) - צריך ביאור מהו המקור לזה. גם צריך ביאור מהיכי תיתי לרש"י שזה אינו אף ב"ויאמר.” גם צריך ביאור אם "ויאמר" הוא חיוב מדרבנן או רק חיוב מחמת גאולה. נראה כראשון, שאם לא כן, למה יחייב לסמוך אותם זה לזה ולומר "ויאמר" מיד לאחר "והיה.” כל זה שייך לV ולVI שבסיכומים. שוב הבנתי שנלמד מדכתיב לדבר בם (רצה לומר, זהו המקור שצריך לכוון.) נמצא, לכאו’, שיש צד שחצי ראשון ושני מדאו’.
קצת קשה מהיכי תיתי לרבי יאשיה שיש מצוות כוונה. ותחשב. זה שייך לVII שבסכומים. ודע שאם כן, אפשר שלשיטות שאין דיבור קאי על כל פרק קמא, אכתי צריך כוונה. ותחשב. שוב הבנתי שדורש "על לבבכם.” זה אי אפשר בפרשה ראשונה, ששם קאי על "דברים אלה,” כמו מצוות דיבור.
צריך לבאר מקור במחלקת ר"י ור"י באם יצא אם לא השמיע לאזנו (ששניהם דורשים מ"שמע"). באמת, קצת קשה למה לא יהיה מעכב, שבדרך כלל, דין הנאמר נאמר לעיכוב. ותחשב. אפשר שר’ יהודה סובר שהוא רק דין דרבנן לעשות כמשמעות הפסוק שאומר "שמע,” ואף שלא דורש כן, אלא כרבנן (יג.). זה שייך לVIII שבסיכומים.
במקור של רבי מאיר, יש לדון אם צריך לדברו. נראה שצריך, מדכ’, “ודברת,” וכוונה רק ממעט שאינו צריך לשמוע, וצריך לח’ איך ממעט. זה שייך לIX שבסכומים. גם צריך להעיר שהול"ל שר"מ כבר דורש שמע לשיטת רבנן.
יש לדון אם "בין תכלת לכרתי" הוא בתכלת שבה, מדסמכו לשיטת רבנן. ונראה שכן הוא. לכאו’, אין הכרח גמרא שייך לו, שדומים הם עד שאינו אפשר בלילה. ודע שתלוי בזה יהיה אם זמן ר"א קודם זמן רבנן. זה שייך לXI שבסיכומים.
מקיש זמן קימה (ה.) – זה צריך להיות אסמכתא, שדין תפילה וסמיכת גאולה לתפילה הוא רק דרבנן.
כשמתו מוטל לפניו לקבור, כ’ רש"י שפטור מטעם טירדא דקבורה. בשאר פטורים (מוטל באותו חדר ומשמר), יש לדון. לכאו’, מר"א נראה שבמשנה לא מוטל עליו לקבור (אלא אם כן נאמר שלזה מכוון כשאומר "לפניו"); אם כן, צריך לומר שפטור אף בזה מחמת טירדא. צריך לבאר, באמת, למה יפטר, שאינו עומד לקברו. אולי ירא שמא יצטרך, שהרי הוא שם. ותחשב. גם היה אפשר לומר שהוא לועג לרש, כיון שהוא עושה מעשה בפני המת. זה נוגע לXIII.
יש לדון אם יש חולק על ר"א (יח.)
ק"ש פשיטא (כ:) 0 קשה לצד שהוא מדרבנן למה כל כך פשוט הוא. צריך לומר שרבנן פטרו נשים ממצות עשה שהם זמן גרמא, אף שהמצוות הם רק מדרבנן.  ותחשב.
הרהור – אם כן, שהרהור הוא כדיבור, קשה מברי’ שאומר "עד כאן מצוות דיבור.” לכאו’, צריך לומר או שיש מצווה דרבנן לדבר, ובזה מדבר בריי’ (ולא משמע כן, שדורש מפסוקים), או שיש חילוק בין הרהור לכוונה הנאמרת שם. אפשר לומר שצריך לדבר, ורק דנים כמה טוב הוא הרהור, אם הוא כמעט כדיבור או רחוק ממנו. ותחשב. הראיה עוד שדיבור יותר טוב מהרהור הוא ממה שלר"י, יש דברים שמדבר, ואף שיכול להרהר אותם. (נקודה זו מש.ק.) וכל זה דחוק. (שייך לXVI).
ר"ח (כ:) - מעניין למחוא מחלקת ר"ח ורבינא.
ר"ח – לכאו’, צריך לומר כצד שקריאת שמע דאו’. נמצצא שיש קדומים מרבינא חולקים על ר"ח.
בלילה – צריך ביאור למה אינו נל’מ"חפזון,” שאומר שרק עד שעת חפזון נאכל. יש לומר שבא לרבות מראב"ע, ולומר שאף עד חפזון נאכל, ולא נרדש כראב"ע. אם כן, כיון שיודעים דלא כר"א, דילמא הוה כקק"ל. עוד יש לומר שבלי "בלילה,” לא היינו דורשים בחפזון. (זה שייך לXVII)
יש לדון אם דרשת ר"א ור"י הוא מקור או שרק מפרשים שהקרא יבואר בדרך אחר על פי שיטה הנל’ ממקור אחר. זה שייך לXVIII.
וכי יש טבילה בחמין (יב.) – עיין יומא (פא:?) שאומר שאם כה"ג חולה, מחמים לו מים. וצריך ביאור. ויש לומר שרק מפיגים צינתם, ולא ממש נעשים חמים. ודע שהיום הכל נוהגים לטבול בחמים.
אתבר חצביה – יש להעיר שלרבא אכתי נצרך לבריא לאונסו. אולי אף זה לא מצוי.
כלי … מים שאובים – יש לדון אם כ"ז לר"י.
מ"מ – מגמרא נראה שמ"מ קאי על איזה טבילה כשרה. כן נראה מרש"י. קצת קשה למה מובא בבריי’ זו, שאינו כל כך שייך לרישא. גם ק"ק לל"א גמרא צד שר"ל שלעולם צריך ארבעים סאה.
כל שלא אמר.. להגיד (יב.) – קשה, שלרש"י, זה אומר חיוב הז’ יצ"מ; כבר נדרש, ולא מקרא זה:
1. זה קרא בנביא היותר ברור, ומגלה שיש דין זה בתורה, הנל’ מקרא של ראב"ע. דחוק, שהיה לו לציין למשנה.
2. זה לרבנן, ואומר שאף שאין חיוב מן התורה, יש חיוב מדברי קבלה. לא נראה כן מלשון ראב"ע, דלא זכה שייאמר משמע שלא אמרו אותו כלל. ויש לדון, שאולי אם הוא רק חיוב דרבנן, לא קבעו אותו רבנן ב"ויאמר,” ואז אולי רצה לומר שלא זכה שיאמרו אותו בקריאת שמע, ב"ויאמר.” אבל, הלשון שלו לא משמע כן. ותחשב.
3. לראב"ע הוא, וחייב להזכיר כמה חסד היה, ולא רק להזכיר שהיה יציאה. (ואם תאמר למה צריך דין ראב"ע. ויש לומר שרק זה מדאו’.)
בנקון (טו.) – כיון שדורשים כן, קצת קשה מהיכי תיתי שמים יותר טובים לתפילה. יש לומר שלשון רחיצה משמע כן.
את העם (יא:) - לכאו’, קאי על אמת ויציב, רצה, וברכת כהנים. קשה איך נכלל ברכת כהנים:
1. אינו, לכאו’, ברכה, כי אם תפילה. ויש לומר שנקרא ברכה מפני שמברך בנ"י, ולא כמו ברכת נהנים.
2. איך ברכו את העם; הא רק כהנים מברכים. אולי היו כהנים בעם. יש לדון בזה. גם יש לומר שבזה "עם העם" לאו דווקא. ותחשב. זה שייך לXXIV)
נראה צד שרשב"ג מחמיר בקריאת שמע לבני אדם אחרים, כיון שידע שאינו שייך לשאר בני אדם, שהוא הכיר במעלת אביו. לא נראה כן מגמרא, שנראה שחולקים בגדר יוהרא. ותחשב.
קבל תנחומין – קצת קשה למה באו לנחם אותו. הניחא בציור דגמ’ שנשמר, יש לומר שלמדו מר"ג. אבל, בר"ג, צריך ביאור למה באו.
* כב:
** רבי מאיר אומר -
יש לדון אם רצה לומר בגמגום או לא. אם רצה לומר בגמגום, נמצא שתנא קמא סובר שיכול לקרא יותר. אם רצה לומר בלי גמגום, יש לדון אם תנא קמא סובר שיכול לעשות יותר או לא. ותחשב.
גם יש לדון אם רבי מאיר הוא רק אי כבר התחיל.
גם יש לדון אם השלש קראי כולל מה שכבר אמר. מרש"י נראה שכוללו. ותחשב.
* יט.
** שאין עזרה -
נראה שר"ל או שלא ינדוהו מפני גדול (כתודוס) או שלא מסתבר שיחטא כל כך עד שינדו אותו.
בקושיה מר"א – יש לדון ששאני התם שהיתירו אותו במיתתו, ולא סיקלו את ארונו.
כ’ בגמ’ (במשנה) שקטנים פטורים מתפילין. יש להעיר שא"א לומר שרק ר"ל מדאו’, שאם כן, פטור על הכל. צריך לומר שר"ל שפטור מדרבנן. קשה, שבערכין אומר שחייב. אולי רצה לומר שסתם קטן לא הגיע לגיל שיכול לשמור תפילין. אם כן, חידוש המשנה הוא שגיל גדול הוא, לכאו’. גם יש לומר שאין בו חי’, ונשנה אגב אשה.
[אגב, קשה גמרא חגיגה (ד.) מדמיון עבד לאשה מענין, שלא מצאנו לימוד זו במקום אחר לענין מצוות, וכאן, לא רק מביא אותו, אלא מקשה ממנו, כאילו פשוט הוא. ותחשב. ויש לדון.]
* כג.
** גברא דחיא -
צריך ביאור מהו מחלקת זה. לכאו’, חולקים במי שא"א לעצור את עצמו, אם יצא או לא במה שאמר ק’, שבריי’ בפי’ אמר שלא יצא. אפשר ששאני הכא שהוה יכול לעצור א"ע, אלא שלא עצר. צריך ביאור, אז למה לא יצא, שמה לנו אם עצר או לא עצר. ויש לומר שחולקים איזה דברים הולכים לדגר ראוי (שכמובן, ממה שלא עצר, מוכרח שלא היה ראוי לעצור.) מה שבדרך כלל בני אדם קוראים "ראוי" הוא שקרק’ חשובים וידועים של המצב יהיה בדר"כ יכולים לעצור. אז, יש לומר שחולקים באיזה קרק’ נדון בראוי לענין זה. ותחשב. גם אפשר שחולקים אם פסול כיון שמקצתו או רובו היה עדיין בהכשר. ותחשב.
יש לדון מהי"ת שלא יצא. נראה שלשון "תועבה" משמע שנל’ מ"זבח רשעים תועבה.” ויש לדון.
אם יכול לשהות – יש לדון אם זה לכת’ או בדיעבד. אולי זה נפקא מינא בין שני הלשונות. ולא נראה.
* כג.
** בחורים.. בה"כ -
נראה שיש לדון מי אומר כן:
1. רק ר"ע. נמצא, אז, שחולק על ב"ה בשני דברים.
2. ר"ע וב"ה. והוא, שמשנה חוזר על שניהם לומר זה.
** התקינו -
בריי’ אומר שיניחוהו בחורין הסמוכים לבית הכסא. בריי’ זה אומר שתקנו נגד זה. יש לדון איך לדחות הסתירה:
1. יש לומר שבריי’ שני רק ב"ה.
2. יש לומר שבריי’ הוא קודם התקנה. אם כן, אכתי יש לדון במש"כ בד"ה בחורין. יש לדון למה לבית הלל יותר:
  1. מפני תקנה. אז, מח’ ב"ה ור"ע ה"ה מתי היה להם לתקן (בזמנם, לא היה כ"כ סיבה, וחלק אם זה מספיק).
  2. מפני סיבה אחרת. אם כן, בריי’ ר"ע.
** בביאור
דין ר’ מיאשא (גולל תפילין):
1. יש לדון אם זה רק לבית הלל, אבל לרבי עקיבא כיןו שבין כך ובין כך מכניס אותו בבגדו או מכניס אותו בחורין, אין צריכים לזה; או שזה רק לרבי עקיבא, שכבר מצאנו שסבר שידו בפני עצמו לא מהני (זה לא נראה כל כך); או שאומר כן לשניהם.
2. גם יש לדון אם אומר שכן אוחז אותם או שאם צריך להניח אותם בחורין, כן יכנסם.
3. לצד שקאי על רבי עקיבא (או על בית הלל לצד שצריך להכניס אותם לחורין), יש לדון אם אמר שצריך שניהם או שאף זה יהני (זה, כמובן כא שבב’), שאז א"צ להכניס אותם לחורין.
** אין עוד זמן להניחם -
לכאו’, הענין הוא שבדר"כ א"צ לעשות כן כיון שטורח להוציא אותם. כאן, ישארו שם, ואז אין בו טירחא יתירא. יש לדון אם צ"ל נגללים (כר"מ).
** יש לדון
אם מותר להשתין מים כשאוחז תפילים בביה"כ קבוע. צריך ביאור למה לא. אולי דרכו לישב, ואין נצוצות, וזה שאלה, באמת, במציאות. לשון גמרא משמע שיש חילוק, ואולי זה רק סימן לחי’ קטנים וגדלים. לא נראה כן ממה שאמר גמרא חי’ קטנים וגדולים וכותבו באותו לשון. ותחשב.
** יש לדון
בדין "אינו מניחם עוד" בבית הכנסת עראי. ותחשב.
** בדין אשתו,
צריך ביאור למה מניח רבא שאיתותב שמואל, שלכאו’ תנאי היא. אולי לא מניח כן, ורק דן אם יהיה מסופק בדין (ואולי יפסק כר"י, שמסתבר, אולי, והבתרא) או שיהיה פשוט שהל’ כשמואל.
** יש לדון
מה יש בה איסור ראיית ערווה אם לא מכוון. לכאו’, יש שיש בו איסור (שכ"כ רש"י). אז, נראה ששווה לקריאת שמע. קשה, אז, למה לא אמר כן לדין טפח. יש לומר שאם כן אין דין שוק שייך. וצריך לומר שאין דמיונו לקריאת שמע בכל. לא נראה כן מרש"י, שמשמע שדין דוק שייך לקריאת שמע. אפשר שאין איסור (וכ"נ מגמ’ שמז’ מעשה דאמורא, שראה נשים רוחצות) אם לא מכוון, ורק שחוששים שיכוון. אין זה משנה החשבון כאן.
** בדין
ראיית ערווה לקריאת שמע, יש לדון אם מעכב. גם יש לדון אם רק צריך שלא נראות או אם אף צריך הפסק בצוואר, כמו שצריך בלבו. מסתמא, שאני לבו שאינו רואה ממש. ויש לדון.
** במה
שאינו מותר לתת תחת ראשו ממש, יש לדון אם זה רק אם אשתו עמו. ותחשב.
** יש לדון
מה יעשה אם שכח אדם חפתיו, והתחיל להשתין.
** אם רק ידו
בבית הכסא, צריך ביאור, שכבר הוא בד"א. אולי מדובר בשיש מחיצה, וסובר שמחיצה יהני. גם יש להק’ גבי צואה על בשרו כעין זה. גם יש נפקא מינא שם, אולי, אם מכוסה.
** עומד -
גבי מבוי המטונף, נראה שיש לדון למה חלוק:
1. במהלך, חושב על הילוך.
2. במהלך, אינו לכל כך זמן.
3. במהלך, יש לו יותר צורך.
* כד:
** רבי... למטה -
ק"ק איך היכרו אם אין קול.
** נראה
שמח’ מה יעשה אם צ’ להתעטש חולקים אם צריך להרחיק ממקום התחלת הריח. צריך ביאור עד מתי; אטו לעוללם יאסר באותו מקום. אוליהוא עד שכלה הריח. ותחשב.
* כג:
** אפשר אכתי
שקאי על גדולים וקטנים, שאין זה מיישב בריי’. וצריך ביאור.
** גם
צריך ביאור חי’ בין טעם לפירכא. ותחשב.
* כו.
** יהבי -
לשון רבים (כן אני חושב) מעניין.
** תשלומין -
יש לדון מהו הענין:
1. מקיים את ענין תפילה, אבל לא כל כך טוב, שאינו בזמן הראוי כל כך. אפשר שזמנו כשר רק מפני יחסו לזמן הכשר. ותחשב.
2. אפשר שמסלק ס"ר הבאים ממה שלא עשה ענין תפילה. זה או ענין רוחני או שמגלה שרוצה בס"ט. לשון "שכר תפילה" לא משמע כצד זה.
מה שיש צד שצ"ל בחד יום לו הוא לעשות אותו זמן יותר כשר. לשני, הוא מפני שאולי בכלות היום כבר נעשו ס"ר, ואי אפשר לסלק אותם. ותחשב.
** מזיד -
יש לדון למה. לראשון, יש לומר שקנס הוא. גם יש לומר שאם נאנס, אין זמן תפילה, נחשב זמן הכי טוב לו להתפלל, שאי אפשר לו להתפלל אז. אז, יש מעלה בזמן שלאחריו, שלא מצוי מצוי במזיד, והאו היותו זמן הכי טוב. לשני, יש לומר שקנס הוא. גם יש לומר שיותר קשה לתקן. גם יש לומר שא"א לגלות שרוצה בס"ט, כיון שבמזיד בטל אותם. ותחשב.
** וכו"ע -
רצה לומר, אז מוכרח שמשנה לותיקין, ואז ק’ ראשונה קשה.
** תוס’ ואין -
צריך ביאור מהו תירוץ שלו. אפשר (ואכתי זה לא מבאר תי’ כ"כ) שנל’ מפני שיש רק חד פי’ שיכול בשני המקומות או שגמ’ חול’. ותחשב.
** הואיל ותנן בבחירתא כוותיה -
יש לדון למה:
1. העידו כן. אם כן, “הואיל" הוא רק סימן.
2. מדסדר אותו רבי שם, צריך לומר שבר שכן הלכה, שידוע לנו שרק סדר שם מימרות שסבר שהלכה כמותם.
** השתא -
יש לדון מה רצה לומר:
1. נמצא שרב פסק חלוק מר"ה ורבנן. אז, יכול אדם לנהוג איך שרוצה. לשון "כיון שלא נאמר" אז רצה לומר שאין יודעים אם הלכה כר"ה או כרב.
2. חוזר גמרא לומר שרב לא פסק כן (לכאו’, שסבר שמדר"ה ורבנן חל’, לא נראה שסבר שכן הל’), אלא עשה כן מפני שיכול אדם לעשות מה שרוצה. אם כן, הוה ליה לומר "אלא" (אלא שסתם גמרא הוא (עיין ברא"ש בנזיר, ובראשונים בב"ב).
* כז:
** שלא שמע -
קצת קשה, שעל זה חולקים שאר רבנן. לכאו’, וא"כ, אולי חול’ על שאר (שלכאו’, זה מיוחס לשיטתו). ותחשב.
** לפני גזירה -
עיין בשבת (מ:) שמניח על משנה שקרה ברבי במרחץ שהיה לאחר גזירה. אולי ידע (ידע שהיו גזרות חלוקות).
** קדושה על הכוס -
לכאו’, הצד שלא יוכל ה"ה שמדאו’ הוא. ויש לדון, שאצ"ל על הכוס מדאו’ (עיין בתחילת נדרים), ואז, היה לו לדין אם צריך לומר לשון קדוש אחריו.
** רשות -
נמצא שאף שרבי היה נוקם בכבוד ביתו (עיין בסוף הוריות), סתם ופסק נגד ר"ג במח’ גדולה זו. ואולי ר"ג היה אבי אביו, ולא אביו, כמו בהוריות, ואז לא נקם כל כך. עוד יש לומר שר"ג בעצמו מחל. ותחשב.
** לכאו’,
נמצא שאביי נגד סתם משנה. אולי דיוק מסתם משנה שונה. (זה ידחה דיבור שלפני זה, שאז רבי לא סתם נגד ר"ג. עוד יש להעיר שרק קשה איך רבי יסתום נגד רבן גמליאל אם נאמר שרבי סתם את המשניות, כרש"י, ולא שסתם אותם על פי פסק הרבים. עיין בשבועות ובביצה, שמשמע כרש"י.) עיין בחולין, בתחילת פרק שלישי, שלא משמע שדיוק שונה. ותחשב.
** לישתמיש איניש -
קצת צריך ביאור מהו הצד נגד זה:
1. יהיה מצער אם מעבירים אותו, שיהיה אקספאקטינג טוב שלא בא. לזה, השיב שלא יצער, אלא בין הכל, יבין שהיה טוב לו.
2. היה רע הבא ממנו (למשל, נראה כמחוצף). דנו אם זה שווה להיות נשיא ליום אחד, ואומר שיותר טוב להיות נשיא לקצת זמן.
ותחשב עוד.
** לשתמש -
קצת קשה למה דחה שאין מורידים בקדש.
** כבן -
יש לשאול אז מה לו בהיותו כבן שבעים שנה. יש לומר שאמר שהיה מחודד כל כך שהיה נשיא בגיל קטן, ושה’ רצה שיהיה נשיא, ונעשה לו נס.
** אחזו… ולא היא -
קצת קשה איך יעשו כן אם יחזר להיות נשיא, וימנע בנ"א מבית המדרש. מכאן רואים כמה רע הוא להיות לו מער לאדם. ויש לדון, שאולי הסכים שישארו בבית מדרש.
** מאן נזיל -
צריך ביאור למה לא היה רבי יהושע עצמו יכול ללכת. אולי חשבו שהיה עוד מפחד מרבן גמליאל. (יש להעיר שהוא לא מחה על כבודו, ורק אחרים מחו על כבודו. אז, אולי לא יאמינו שבאמת ר"ג שאל מחילתו.)
** ר"נ בן הקנה -
ההמשך למשנה זו קצת מוזר. אפשר שר"ל, “כמו שיש אלו שקבוע להם זמן, יש עוד תפילות שלא קבוע להם זמן.” וקצת קשה למה לא הקדים משניות הדנים בתפילות שקבוע להם זמן (כמו משנה שדן מה אומר). ותחשב.
** דעו לפני -
לכן אומר, נראה, שה’ עושה תפלתו. רצה לומר, לשיטתו הוא.
** וישמחו -
קשה למה צריך לזה, כיון שכבר התפלל שלא יכשל. יש לומר שמרצה דברים לה’ לומר, לומר שיש שני צריכים בבקשתו. גם יש לומר שמתפלל שלא יכשל ועל כל פנים לא ישמח חבירו.
** רש"י ולא-
מש"כ, “ואגרום שיענשו,” ולא רק "ויענשו" משמע שאין הרע שיענשו, אלא שהוא יגרום עונש שלהם. זה מעניין, שלא עשה איסור על ידי זה, שהיה לו להם ליזהר. אולי יש בזה לפני עוור, אף שלא כוון לזה.
** מעין יח -
לכאו’, מודה שיש יח’ שנכ’ על ידי אנשי כנסת הגדולה, שאם לא כן, זה לא ייקרא מעין יח’ (אלא שיש לומר שיש בו יח’ ענינים, כנגד יח’ חוליות או כדומה; גם אפשר שלא סובר שנקרא כן, אלא אומר אותו על שם מה שאמר ת"ק יח’). אז, קשה למי תקנו אותו. יש לומר שמשנה דן רק בחוב, אבל יש מעלה באמירת כל שמונה עשרה.
** שבקריאת שמע -
לכאו’, יחס קריאת שמע לתפילה הוא מה שצריך לסמוך גאולה לתפילה, וגאולה נאמר על קריאת שמע. ותחשב.
** ר"ת בריה דריב"ל -
פשוט לומר שלשיטתו הוא.
* כט.
** וא"ל ריב"ל -
לכאו’, זה במקוםם ר"י אמר רב, ולא במקום רב, שלא מצאנו שיאמר ר"י בשם ריב"ל.
** כל… חוץ -
משמע שר"ב ור"נ חולקים, שאם לא כן, אינו "כל.” ויש לומר שר"נ רצה לומר שאין יום משבוע נתמעט חוץ מזה ור"ב אמר שאין חדשים או תקופות נתמעטים חוץ מזה, ואולי זהו מה שמניח גמ’ שאין בעיה בהבדלה לר"ב.
** מחזירים -
יש לדון למה נחזיר אותו, ולמה לא יכול לאמרו בשומע תפילה:
1. אפשר שיש מעלה חשובה (יש לדון אם בלי זה יוצא) במה ששאלת גשמרים בברכה ששיך לו.
2. יש בעיה בברכה בלי הוספה זו. צד כעין זה שמעתי מרש"ש שליט"א.
3. אפשר שאמירתו בש"ת עושה רע לש"ת, שצריך להיות על תפילה בכלל.
הדיון יכול להיות כמה גדול אחד, שני, ושלישי (ודע שאפשר לצרף אותם), או כמה רע הוא לחזור לברך עליו (יכול להיות שלש רעות – מרבה בברכות (כעין ברכה לבטלה), עושה קצת הפסק, וטורח לו.)
וא"ת הרי יכול אדם לשאול צרכיו בש"ת (זה רק קאי על ראשון ושלישי). ויש לומר שאינו כל כך רע, אבל נחזיר אותו, מפני שיותר טוב. גם יש לומר ששאני בקשה שהוא חייב לומר. ותחשב.
** הבדלה -
אולי משמע מגמרא שצד שמחזירים בכולם ישווה. יש לדון. אם כן, צריך לומר שהא דהבדלה ה"ה הפשט בשאלה והזכרה. יש לדון מהו הפשט בהבדלה. מה שאמר, “מפני שיכול לאמרה על הכוס" משמע שהבעיה הוא שצריך לומר ההוספה. כן נראה, באמת, מלשון "מחזירים,” ולא "יצא.” ודע שאפשר שמה שצריך לברכה עושה שברכה צריכה לו, שאז אין הברכה עושה כל מה שיכול לעשות, שיכול לחזק דיבור זו. ותחשב. אם כן, אין ראיה.
** אביי -
מצאנו אביי לייט בכמה מקומות.
** צדיק מעיקרו -
צריך לפרש גדר זה, שפשוט שאף אם עושה איש מצווה מיד כשנעשה בן יג’, ומחכה עד שבא לידו עבירה, אינו בטוח שלא יעשה עבירה עוד. ותחשב.
** לייט רש"י -
יש לדון מה רצה לומר:
1. מדלג חלק גדול מן הברכות.
2. עושה שבע ברכות, ולא שמונה עשרה ברכות.
אפשר שאומר שניהם. ודע שלשני קצת קשה למה לא יתקנו שמונה עשרה ברכות יותר קצרות. ותחשב. דע שלשון מדלג הברכות, ולא בברכות, משמשע כשני.
** אי הכי -
מילים אלו לכאו’ הם מיותרים, והיה לו לומר, “מ"ט… הא אמר…" ואפשר שמ"ט חלק מתי’, ועל זה מקשה שאם כן, קשה….
** ש"ת -
מה שלא חוזר לשומע תפילה קצת צריך ביאור. לא טורח יותר, ולא אומר יותר ברכות מכאילו היה חזור לברכת השנים כשטורח אחריו.
** עם דמדומי -
יש לומר שרק רצה לומר לסמוך גאולה לתפילה, ור"א לשיטתו, שסובר שקריאת שמע רק עד הנת החמה (ואין להתפלל לכתחילה קודם הנץ החמה). ותחשב.
* ל.
** בין מעומד -
לכאו’, לא חלקו בזה. ואולי קאי על תפילת הדרך (או שמח’ קאי, באמת, (אף) על זה.).
** יכוון -
לכאו’, כשאומר "יכוון,” לפעמים רצה לומר שנוטה גופו, ולפעמים רצה לומר שחושב ומכוון.
** רש"י בשבתא -
עיין בבכורות בשיח ש"י ס.
** ולעבד מר -
עיין ברש"י. מעניין מה שמניח שכיון שקודם ק"ש הוא, אין ענין בסמיכת גאולה לתפילה, שבפשטות הו"א שענין סמיכת גאולה לתפילה הוא שעושה טוב ומעלה בק"ש או תפילה. אם כן, אם לא סמך אותם, כמו כאן, לא עושה אותו טוב. ותחשב.
** ר"ח בר רב -
מצאנו בכמה מקומות (למשל, שבת (סט:)) שנקרא חייא בר רב. אפשר שכשנתגדל בתורה נקרא בשם רב. גם יש לומר שהיו אמוראים שקראו זה והיו אחרים שקראו זה. גם יש לומר שלא היה ראוי לשם כל כך נכבד. אז, בא"י שהיו גדולים נקראים "רבי,” נקרא רב. בבל, לא היה נקרא רב, שהגדולים היו נקראים בשם רב.
** שאין מקדשים -
או ר"ל שלכן אינו כ"כ ר"ח אז או ר"ל שמחלק ממה שהז’ עושה הוא דומה למה שקדוש עושה. כיוןש קדוש אי אפשר בלילה, יתכן שאף זכירה אי אפשר. ותחשב.
* כח:
** העושה תפילתו -
יש לדון אם זה קאי על תפילת חובות מחמת זמן או שאר. מסברה נראה שהוא אמת בשניהם, אבל מצוי יותר בתפילות החיובים. ותחשב.
* ל.
** אין עומדים -
יש לדון אם זה חיוב (א. חייב אדם להתפלל, ולהתפלל בדרך טוב, בדרך שיגרם שתפלו יעשה מה שצריך לעשות. זה נעשה יותר אם מתפלל מתוך כובד ראש. ב. בזיון הוא להתפלל שלא מתוך כובד ראש.) או מעלה (משני סיבות שזכרנו) או עצה טוב (שאז ישמע ה’ את תפילתו יותר, מפני אותם צדדים שכתבנו).
** מצער -
יש לדון מה ר"ל -
1. היה ירא מפני שבא לפני מי שלו יתפלל, ולא כדי להתפלל. היה ירא מפני שבקש רחמים עד שהיה מצער נפשיה.
2. לו היה חיוב מפני שהיה מצטער כל כך. אז, אם לא היה מכובד ראש, היה בזיון.
3. רק כשאדם מצער נפשו מהני, אולי.
4. אולי לא התפלל יותר, אלא רצה לומר שדילמא רק עצה טובה, ולא חוב. צריך לומר שמניח שמשנה אומר חוב. זה מפני לשון או ממה שנשנה במשנה. ויש לדון, שמביא מר"א ש"אין תפלתו תחנונים.” כיון שהגענו לזה, נוכל לומר שהרבה בתפילה, ושזה סימן שהיה עושה יותר מן הדין. אז, אולי אף זה יותר מן הדין.
** מציין -
קצת קשה, שזה כבר נלמד מהכון בשבת. אולי לרבא שם צריך קרא לציין את נפשו. נצטרך לומר אז שסובר שהכון אומר שצריך להכין את עצמו ולהראות את עצמו כעבד, וקרא זה אומר שצריך להדר את עצמו. כדי ליישב את הסתירה, נצטרך לומר או שהם בזמנים אחרים כהמשך הגמרא שם או שקצת צריך לעשות זה וקצת צריך לעשות זה. אולי אז צריך אותו קרא (עיין בשבת בשיח שי במש"כ שם). ותחשב.
מעניין שלא מביא אותם מעשים של גמרא שבת כאן. אולי מחפשים דרכים אחרים של ציינת אדם. ותחשב מה רצה לומר.
** רש"י עבדו -
יש לדון מהו הדרשה:
1. קרא אומר שעבודה צריך להיות ביראה. כיון שתפילה במקום קרבן, אף הוא נקרא עבודה, ומסתמא נכלל בכלל קרא.
2. קרא קאי על עבודת קרבן. כיון שתפילה במקום קרבן, ורבנן השוו דיניהם, גם תפילה צריך להיות ביראה.
* לא.
** כבריי’ -
קשה איך יפסוק כבריי’ נגד משנה. אפשר שסבר (וק"ק מהי"ת) שלא חולקים, אלא שיכול לעשות כאיזה שירצה. ותחשב. עיין בתוד"ה רבנן עבדי שלא משמע כן. ויש לדון, שאולי קיי"ל  שלהם לא רצה לומר לדין, אלא שסוברים שזהו הכי טוב. ותחשב. ודע שאם חיוב הוא, שני הדרגות קל להבין, שבשניהם יוצא, אבל אחד יותר טוב. אם לא כן, צריך לומר שהענין הוא ששניהם טוב, אבל אחד יותר טוב. ותחשב.
** אלא מתוך הלכה -
לכאו’, רצה לומר שני דברים בזה:
1. אין עומדים מתוך…
2. אין עומדים מתוך הלכה..  (רצה לומר, גם מחדש איסור דבר הצריך עיון, וגם מחדש היתר דבר שא"צ עיון, ומחדש לכאו’ שזה טוב.)
** אין -
קצת קשה למה לא אומר היותר מחודש, והאו ש"לא מתוך כובד ראש.” אפשר שלא חולק על המשנה. גם אפשר שאין רע בזה, אלא שאינו כל כך טוב. רצה לומר, יש טוב שבא מתפילה מתוך שום דבר (אילו היה דבר זה אפשר). מונה דברים הרעים מזה, ולא מונה כובד ראש שלא רע מזה, ואולי שקצת טוב מזה. וק"ק ל"ל ימנה אלו שאסור להתפלל מתוכם, שכלאו’ דין בא לומר, ולא רק רע. ויש לדון. אם אינו חיוב, לא כל כך קשה. נראה שי"ל שאילו א"א לצרף עם שמחת מצוה, משא"כ בכובד ראש, ולכן לא מזכיר כובד ראש, שלפעמים יתפלל ממנו.
** וכן … דב"ה -
ה"וכן" צריך ביאור. עיין בגר"א. לכאו’, לכן שינה אותו. אפשר שר"ל ששוים במה שיש אלו הרעים. ותחשב על זה. וכן ה"שכן מצינו" צריך ביאור. לזה, תי’ שכתבנו לא יהני.) ודע שמבא דברי בריה דר"ה נראה שר"ל דב"ה (ששם לכאו’, קאי על דב"הף שזהו דבר נזכר. ותחשב. וכן נראה ממעשה.) וע’ בגר"א שג"כ לא גורס "וכן.” אפשר לגרוס "וכן" ולומר שקאי על לעיל. אם כן, צריך לומר שיש סיבה לסיים בדבר הלכה, ולא רק שאין איסור. עיין לעיל.
** צריך שיכוון לבו לשמים -
צריך ביאור מה זה רצה לומר. אולי רק רצה לומר שכוונה בתפילה (מסתמא שעומד לפני ה’) הוא חיוב. אולי אף יכול להיות שאומר שטוב הוא. ויש לדון, שזה פשוט לכאורה. אגב, נראה שאולי אין גמרא יודע אם דין משנה חוב או לא, וייתלה על המקור. ותחשב.
** פרק אין עומדים
* ל:
** מרת -
וא"ת איך יישב הברייתא שמצריך שמחה של מצוה. אפשר שאנוסה היתה. גם אפשר שלא חולקים, אלא יכול לעשות מה שרוצה. (יש להוסיף שיש, לכאו’, שלש דרכים ליישב סתירת ברייתא ומשנה:
א. צריך שניהם. מה שמביא מהנהגות אמוראים לא משמע כן.
ב. חולקים.
ג. צריך רק אחד מהם. מוזר, אז, למה לא יאמר ברייתא ומשנה שניהם (שהניחא בראשון, יש רק דין אחר להוסיף, ואולי לא באר כל דיניו, אבל בזה, זה גופא חלק מן הדין, שצריך לבאר מתי נוהג.))
** מצער נפשיה -
יש לדון אם אומר זה לסימן או לסיבה.
** אל תקרי -
שאל לי א.ד.ר. מהו ענין "אל תקרי." נראה לי ארבע צדדים:
א. אפשר שכל "אל תקרי" הוא מסורה.
ב. אפשר שהקרא מיותר, ודורשים אותו בדרך "אל תקרי.”
ג. אפשר שכל קרא שאפשר לומר כן עליו בהכרח מיותר, שהיה לו לומר בלשון שאינו יכול להיפרש כן. (הוא מפני שיש קצת משמעות לדרשה. ואולי משמע כן רק מפני שבדבר מיותר דורשים "אל תקרי.”)
ד. אולי כלל הוא (כמו "לחומרה מקשינן" או כעין זה.
צריך להגדיר, שפשוט שיש מילים שלא נדרשים כן. אין זה קשה לא או לב. לג, נ’ שאפשר שההגדרה הוא כל מקום שיש יכולת לומר דבר אחר. לד, צריך יותר לדון.
וצריך לדון בהו"א ומס’ של גמ’ זה.
** צריך לבאר מהו
כובד ראש, שרש"י אומר שהוא הכנעה ובגמ’ משמע שהוא יראה (או אולי דבר הבא מיראה או הגורם יראה. אז אולי שוים. ואפשר שהכנעה ויראה כמעט שוים.).
* לא.
** ר"ל -
קורא לר"י רבו. ע’ לעיל (כן אני חושב) שאמר כן על גמ’ אחר.
** אדכרתן -
מעניין מה שלכאו’ מחשיב את זה לדבר הלכה.
** זוכרהו -
נ’ שמנביא רק רואים שעל ידי שמז’ דבר הלכה נזכר.
** רינה זו תפלה -
ואם תאמר דלמא תפלה זו היא תפלה. ויש לומר שאי אפשר לרינה להשמיע בקשה, ואפשר לתפלה להשמיע שניהם.
** להוכיחו -
קשה, שזה קרא בפירוש (“הוכיח תוכיח"). ואולי הוה אמינא שזה רשות (ותורה רק נותן היתר). וא"ת מהיכי תיתי מכאן שהוא חוב. ויש לומר שממה שהפסיק את תפלתו, רואים שהיא חוב. ויש לדון אם יש הוכחה שהפסיק את תפילתה. עוד יש לומר שרק מזכיר מה שיכולים ללמוד מכאן, ואף שהוא כבר ידועה. ולא נראה, שלא מזכיר מה שהוא טוב להתפלל. ויל"ד. ושוב ראיתי בתוספות.
* לב.
** זכור -
לא הבנתי למה נחשב נגד שבועתו אם יגדיל את משה וינחיל את הארץ. גם לא הבנתי איך יהא מקום לומר שאין כח לה’ לכבוש מלכי כנען, שיכבשוהו למשה ולבניו.
* לב:
** גדולה -
משמע שענין צדקה הוא חסרין ממון. ותחשב. וצריך ביאור.
** מאריך ומעיין -
מאריך, לכאו’, לאו דוקא, אלא שלכאו’, לא יעיין עם לא האריך.
** כתבתי לעיל
(גלגל ראשון) שלשון "מה אומר" הוא פייגיוריטי"ב. אולי אחר שימות ידבר עמם. (כמובן, יש לציין לגמרא מכות ו.)
* לג.
** קרניו -
נראה שזה אולי מקור למה שבני אדם מציירים ליצר הרע להיות בריה קטנה שמרקד על כתפים, והוא שבשור, זה קרוב לבין קרניו. ויש לדון.
** בתחייה"מ -
בכל אלו, יש לדון אם הוספה זה נתהנה מן הברכה או מהנה הברכה או שיפגע או שייפגע בברכה שוינו שלו. ותחשב.
** עם בינות -
משמע שדיעה ובינה שווים.
** בתחלה -
נראה לפרש על פי מש"כ רש"י בהביננו, שיותר קל לכוון בתחלה מבאמצע.
