** א.
- עד אימתי – יש להקשות על זה "תנא מהיכא סליק," כמו שמקשה הבבלי בתחילת ברכות, שלא שנה כבר שיש דין של הוספת שביעית. צריך לומר שכיון שכבר ידוע דין שביעית, ורק שואל מתי מתחיל דין שביעית – אף שחידוש הוא שצריכים לשאול, שהיינו סוברים שמתחיל בתחילת שנה שביעית - לא כל כך קשה. אבל, עדיין צריך להיות שידע כבר דין שביעית. אבל, לזה יש אותו תי' שנתן בברכות, שתנא מניח שיודעים פסוקים. ותחשב.
- עד העצרת- עיין במה שאומר פני משה. נמצא ששניהם אומרים שהוא כל זמן שטוב החרישה לפירות של ששית, אבל רק חולקים מתי זה קורה.
אם כן, יש לדון מהיכי תיתי שבית שמאי חולקים על בית הלל. אולי הוא רק מפני שתנא שנה אותם ביחד. יש לדון מהיכי תיתי לתנא. אולי ידע ממה שהשיב בית שמאי לבית הלל. אם כן, צריך לומר שבית הלל אמר דבריהם ראשון, שאילו לאו הכי, לא יידעו שבית שמאי חולקים עליהם. אבל, גם אפשר שבית שמאי דברו ראשון, ובית הלל לא רק אמרו שהשיעור הוא עצרת, אלא אמרו שהדין הוא שמתחיל בעצרת, ומובן שבאו לחלוק. ותחשב.
גם קל לומר שהדיוק הוא ממה שבית שמאי לא מזכיר היום, אלא השיעור. היה לו לומר השיעור אילו הוא יום מיוחד. צריך לומר או שאינו יום קבוע, ויכול לשנות, או שאינו יוםו כל כך מיוחד, ששבועות הוא יום מיוחד, אבל ט בסיון אינו כל כך מיוחד. אז, לא הזכירו. ויש לדון.
שוב ראיתי שגמרא אומר כן בפירוש. גם ראיתי שבית שמאי לא אומר יום מיוחד, אלא אומר שתלוי בשנה.
לכאו', החילוק בין שיטת בית שמאי לבית הלל הוא שבית הלל תולה אותו באופן כללי, ואומר שהוא עד היום שהוא בדר"כ טוב לשנה שעברה, והוא שקבעו רבנן או תורה יום אחד לכל שנים. אבל, בית שמאי מאמד אותו בכל שנה (ואולי גם בכל שדה ושדה), איזה זמן עדיין טוב לחרוש לפירות. ותחשב.
- אם אינו ענין- נראה שלא צריכים “אם אינו ענין” כאן, שכלל זה מוסיף שיכולים לעשות שאין מקרא מדבר במה שקאי עליו, אלא בדבר אחר. כאן, הוא סתום, ולא מפרש על מה קאי (ולכן לא הזכיר אותו עןל הצד שקאי על שביעית). ויש לדון בזה.
- אין בית דין יכול לבטל- ואם תאמר הרי זה דין דאורייתא. צריך ביאור. ראיתי שגר”א כתב שכיון שבטל מדרבנן (כמו שמפרש פני משה לעיל), צריך לומר שמה שבטלו הוא דין דרבנן. יש לדון עדיין מהיכי תיתי שהיה דין דרבנן שהתירו ולא רק חלקו בדרשת הקראי (כמו שיאמר גמרא לקמן). ויש לדון אם זה קשה. ותחשב.
- עד שתשקע החמה- לכאורה, סובר שאין תוספת שבת מדאורייתא. כן אומר פני משה. אפשר לדחות שאף אם הוא מדאורייתא מחייב אדם לקבל שבת מוקדם (אולי), אבל כאן דנים אם אסור לעשות מלאכה לימים קודם, ואף בלי קבלה.
אבל, אז ק"ק ל"ל אומר משנה שצריך לקבל ימים קודם. אז, לא נראה שאפשר לומר כמו שכתבנו.
- ובקציר- מפרש פני משה שאסור לחרוש בשביל מה שיקצור במוצאי שביעית. לולי זה, היה נראה לומר שלא יקצר מה שנחרש בשביעית. כן משמע מלשון גמרא, וכן נראה מלשון הקרא. צריך ביאור מהיכי תיתי שאינו כן ולמה לא יהיה כן. ותחשב.
שוב עיינתי ונראה שפני משה רק בא לבאר שכיון שהוא אסור בחרישה, גם אסור בקצירה. אז, באמת אומר שאסור לקצור אחרי שביעית.
ודע שיש לדון אם זה מפני איסור קרקע או איסור קצירה. במילים אחרים, יש לדון אם הענין הוא שעל הקרקע ועל הפירות יש דין שביעית, ולכן אסור לקצור אותם או לחרוש קודם שביעית או מפני שכמו שיש קדושה לשביעית שאוסר קצירה וחרישה, יש מקצת קדושה כזה ללפני שביעית ולאחר שביעית. ותחשב.
- רבי קרוספי- מעניין שזה לא נחשב עוקר לגמרי, שמה השאירו, שלעולם מי שמחמיר יכול להחמיר. אולי עדיין אמרו שהוא דבר טוב לעשות. ותחשב, שלכאורה, אין משתמשים בשום כוח כשעושים כן. אם כן, עוקרים לגמרי, ורק מעוררים מעלה בדין. ויש לדון אם זה קשה. ותחשב.
עיין לקמן בד”ה שאם בקשו השני.
- שאם בקשו- אולי ר"ל שעשו שאין בעיה של מבטל דברי בית דין חברו אם רוצים לחזור לו. אם כן, צריך לומר שיש כלל כך אף בחוזר לאסור מן היתר שנמנה. גם יש לומר שרק הודיעו כיון שאפשר שדורות ירצו (ויש לדון למה) לעשות כמו שהחמירו דורות ראשונים כיון שהחמירו דורות ראשונים.
- שאם בקשו- פני משה מזכיר שני דברים, והוא מה שאם רוצים להחמיר יחמיר, והוא מה שהוא רק לזמן. יש לדון ביחס שני דינים אלו. ותחשב על זה.
- שאם בקשו – משמע שלולי זה לא היו יכולים להחמיר. אז, משמע שאף כדי להחמיר על בית דין צריך להיות גדול מהם במנין ובחכמה. אבל, יש לדון, שאולי אף שאינו צריך להיות, יהיו רבנים שיראו שרבנים אחרים התירו, ויקשיבו להם, ויתירו. אז, היה צריך לעשות חלק מן הדין שמי שרוצה להחמיר יחמיר, ולא יביא ראיה ממנו, שהוא רק הקיל לזמן. ותחשב.
- מכאן ואילך הוא מנבל- ואם תאמר איך תולה אותו בחד יום; לכאורה, פשוט שיהיה תלוי בשנה, כמו שאומר בית שמאי. נראה שיש שלש תירוצים פשוטים לומר. אפשר לומר שהוא לא פלוג. אז, אף שלפעמים לא נתקיים סיבת הגזירה, עשו רבנן חד יום. יש לדון אם נקטו יום שבאמצע, יום שבדרך כלל הוא הנכון, יום הכי חמור, או יום הכי קל. בדרך כלל, לא פלוג מחמיר (עיין ברשי בגיטין (יז.) בביאור סברת לא פלוג, שמשמע שהוא סיבה להחמיר). אם כן, צריך לומר שמחמירים כאן, ואז צריך לומר שחולקים בית הלל ובית שמאי מה הוא הזמן הכי חמור. ותחשב. גם אפשר שכיון שרוב שנים כן, בני אדם לא חושבים עליו למלאכת שביעית (ופני משה משמע שהבעיה כאן הוא שנראה לבני אדם כעבודה לשביעית). גם יש לומר שחולקים על בית שמאי בענין הניבול שצריך לקרות, ויוצא מחמת זה זמן חלוק, וזמן של בית הלל הוא קבוע. זה אומרש בית הלל דן בניבול אחר, וניבול זה ממש קורה בעצרת בכל שנה ושנה. ותו”ת.
- ויחרוש- צריך ביאור מה סבר. לכאורה, היה לו להקשות לאידך גיסא, שיהיה אסור, שהרי פשוט שלא עושה מחמת האילן (וצריך ביאור מהו התירוץ לזה). צריך לומר שפשוט לגמרא שיש שום טוב לו (למשל, עושה בו יותר עץ).
אבל, עדיין צריך ביאור למה קושייתו קשה, שהרי אומר בפירוש למה אסור. ויש לומר שלא כל כך פשוט לגמרא שזה רע די לאסור (שהרי אינו מתיש פירות). ותחשב.
צריך לומר, אז, שלא קשה לגמרא שטוב כזה הוא טוב די; רק קשה שהרע הוא רע די. נראה שאולי אין זה כל כך מוזר,
ויש להעיר שלכאורה, היה נראה לומר שאף בלי שום רע, כיון שאין טוב, צריך לומר שעושה כן לזרעים, שהם של שביעית, שאי לאו הכי, למה יטרח. ויש לדון, שאולי עדיין נעשה שום טוב. דחוק.
- פעמים שאין- יש לדון אם ר"ל שעל הכל לא יוצא שמחמירים, או שרק מונים אותם שבית שמאי לעולם מקילים, או שכשנשאל, נשאל בשנה שבו היה בית שמאי חומרה (כמו שאומר בבלי ביומא). לא נראה כתירוץ שלישי, שאז הוא, לכאורה, סתום.
- התיב רבי יונה- יש, לכאורה, לדמות למה שאומר גמרא בסנהדרין גבי בן סורר ומורה וגבי עיר הנידחת. יש לחלק ששם דינים אלו הם דינים שחייבים לעשות, אלא שלא קרים. אבל, דין זה אינו דין שחייב לעשות. ותחשב על זה.
ואגב, ראיתי שבעוז והדר ציינו לגמרא ביומא (ה:). גם יש לציין לגמרא חגיגה (ו:). ויש להעיר שאולי כאן יש אותו נפק”מ, והוא אם אדם רוצה להחמיר על עצמו (שהרי גמרא אומר שיש טוב), מה שאין כן ביומא, שלכאורה אין שום סיבה שירצה אדם לעשות כן, שאינו עושה כן לאהרן הכהן, ואינו מקדיש כהנים. ותחשב.
- מפני שעד כאן- עיין במה שאומר פני משה שהבעיה הוא שנראה כחורש לשנה שבא. מעניין שתלוי במה שנראה. אפשר לפרש שרק בא לבאר למה הוא בכלל הקרא, והוא שקרא אומר חרישה לקצירת שביעית, וזה רצה לומר חרישה שהוא נראה שהוא לקצירת שביעית. צריך ביאור למה יאמר כן, שהייתי אומר שהוא חרישה שבו מכוון לקצירת שביעית. אולי, אז, הוא שסובר שהוא מפני שנראה כקוצר לשביעית. זה מעניין. ותחשב. (ודע שאז, לכאורה, יוצא שקצירה לשביעית, ואף לפני כן, אסור. ותחשב.)
- רבן גמליאל ובית דינו- יש לדון איך ידע גמרא שלא חזר עוד בית דין לגזור (שהרי יכולים, כמו שאומר גמרא), ומשנה כאותו בית דין. אולי היה חי שם, וידע שכן הוא. גם יש לומר שרבן גמליאל זה הוא ר”ג בן רבי (חושב אני שכן כתב הגר”א). אז, לא היה משנה שונה מה שקרה אחר תקנתו. קשה, שלכאורה, אף משנה לא היה שונה מה שקרה בתקנתו. ותחשב.[fn:1]
- רבי אחא – צריך ביאור מה מוסיף על פי' ראשון. לכאו', הוא אומר שחולקים בביאור פסוק. הרי, כולי עלמא מודו שפסוק הוא שאומר שלא לחרוש קודם שביעית. אם כן, אף לצד ראשון יוצא שחולקים בביאור פסוק.
נראה שצריך לומר שהחילוק ביניהם הוא מהו עיקר התי'. לפי צד זה, כיון שחולקים בפסוק, לא נוהג בזה כלל שאין ב"ד מתיר דברי ב"ד, שלא דנים בתקנה, אלא בדין שנלמד מפסוקים. אבל, טעם ראשון לא סובר כן, אלא מוצא טעם אחר למה היה יכול לחלוק עליהם. ותחשב.
- איטלקי – עיין במה שכתב פני משה שתלה בהם כיון שהיו בימי משה. הקשה לי א.מ.וו. שלא היה איטליא של יון בימי משה, שנברא בימי שלמה (כשנשא את בת פרעה). נראה שהרומיים שבאיטליא לקחו את מנה שלהם מאחרים, ואחרים היו בימי משה. (כן נראה, שהרי גמ' אומר שרומיים גם לקחו לשונם מאחרים.)
** א:
- תמן איתאמרת- מפני משה יוצא שבשורה הם יותר קרובים. לא נראה כן, שלכאורה, “כדי שיהא הבקר עובר” הוא בין כל אילן ואילן. אם כן, הם יותר קרובים אם הם כצבור, שאז כל אחד קרוב לשנים, מאם הם כשורה, שאז רק אחד קרוב לשנים. אולי כיון שאותו אחד קרוב לשנים בשני צדדים הפוכים עומד יותר ליעקר. דחוק. ותחשב.
- כדי שיהא הבקר עובר- פני משה מפרש שתשובת גמרא הוא שאין הכי נמי, לענין מה שהם קרובים, אין חילוק, ויש חילוק רק לענין מה שנראים כאחד, שבשורה יותר נראים כאחד. קצת צריך ביאור איך מפרש כן בלשון גמרא. ותחשב.
- היו נתונים- הדין הוא (מבאר במשנה לקמן) שאם אינו עושה כשיעור זה, אז נותן להם תחתיהם וחוצה להם. דן כאן אם זה אף אם תחתיהם הוא בית סאתיים. (לכאורה, הוא מפני שיש צד שצריך מקום היתר של דבר שאינו עושה כשיעור להיות פחות ממקום היתר של מקום שעושה כשיעור.) גמרא זה מניח שיש לו סאה לכל צד (גמרא לקמן ידון בזה).
- רחוקים – לכאו', לא רצה לומר שיכול להיות רחוקים כשלש הכי רחוקים שבעשרה לבית סאה, שאז רק יאמר שצריך להיות בית סאה. אלא, צריך להיות שאינם רחוקים יותר משלש קרובים בבית סאה; במילים אחרים, צריך שיכול לצריף את אלו לבית סאה בלי הוספת אילנות ביניהם.
- תמן – אבל, לא דן במשנה שלנו, שמשנה שלנו יש לו גדר אחר,  שהוא שלש בבית סאה. כנראה, אז יכולים לפשוט. יש לדון כמי נפשוט.
- גדר – נראה שגמ' מוכיח משאלה של גדר בצד אילן שסובר השואל שנותן בית סאה בשני הצדדים, ממה שפשוט שאם יש רק בית סאה אחד, פשוט שנתחיל אותו בית סאה (שלא קבוע מהו) מן הגדר בצד של האילנות. אז, מה שיש לשאול הוא רק אם נסבור שיש עוד בית סאה שנוסיף אחרי האילנות. ותחשב.
- אין בעי- אינו כל כך ברור לי מהו הציור כאן. מגמרא עצמו היה נראה לומר שיש רק גפן אחת. אבל, פני משה משמע שיש יותר מאחד, וגם אומר שלא עושה ששים. אילו היה רק אחד, לכאורה, אף אם עשה ששים, לא היה לו דין שלש, שהרי אין שלש (שאילו לאו הכי, היה לו למשנה להזכיר אחד עד שלש). אז, נראה שיש שלש גפנים.
- גפן- יש להעיר שמה שתחתיו הוא בית סאתים, ולא מה שחוצה לו. אם כן, צריך לומר שהולך על כל בית סאתים. אם כן, גדול הוא מאד. ויש לדון מה נחשב תחתיו, אם צריך להיות ממש על כל טפח וטפח. ותחשב.
- רבי מנא- צריך ביאור למה אינו קשה בין כך ובין כך, שבשניהם אומר שיעור זה. אומר כן כאן לענין קנין, ואומר כן לקמן לענין שביעית. צריך ביאור, אז, למה אין זה קושיה בדרך כלל. אולי איה”נ, הוא קושיה על הכל. ותחשב.
** ב.
- כשם- לכאורה, היה אפשר לומר שאף לר”ח כן הוא, שהרי בשניהם יש בעיה שעושה עפר תיחוח. אבל, נראה שהלשון דחוק, שאומר שאותו בעיה שיש בלמעלה, יש אף בלמטה. הבעיה היותר פשוטה בלמעלה הוא שרשים. אז, כשאומר שהבעיה שיש למעלה יש אף למטה, עושה טעות בדעת בני אדם, שהרי חושבים שנדון בבעיה הכי ידועה, והוא שרשים. ויש לדון.
- אמר ר”ח בר אדא- יש לדון מה אומר. אולי אומר שיעור שווה, והוא שרואים אותו כאילו יש עליו תאנים. דנים רק מהו המעלה בתאנים, אם הוא שהם יותר גדולים או שהם שווים ככל שנה, ולא צריכים לתת לו רק אבארי”ג’. אם כן, אולי לא חולקים, אלא מוסיף עוד מעלה.
גם אפשר שאומר שמה שראוים אותו כתאנה לא ר"ל שרואים שיש עליו תאנים, אלא רואים שכל פירותיו הוא כשנה הכי טובה. אם כן, עדיין קשה גבי אילן סרק. ותחשב.
- רואים ... תאנים – נראה שרצה לומר שרואים אם תאנים בגודל זה יכולים עשות שיעור זה של פירות. גם אפשר שלא רק רואים את הגדול, אלא גם את הגיל, שאולי צריך לגדל כמה שנים עד שיכול לעשות הרבה פירות. (אבל, אין גיל ממעט את מנין הפירות, כמו שיאמר הגמרא.)
- רואים את האמצעים- יש להעיר שלכאורה זה רק  יעשה שאותם שנים נחשבים כאחד. כיון שפני משה משמע שממשיכים אותו ציור, אז יהיו חמש. אולי ר"ל שכיון שנוטלים אחד, נוטלים כולם. הסברה לזה יהיה שרואים שנוטע לבטלה, ואז יכולים לומר על כולם שיעקור אותם. דחוק, שלכאורה, רק יכול להיות שיעקור אותם, אבל לא עומדים לכך. ותחשב על כל זה, שדחוק.
שוב נראה שהענין הוא שלפי רבנן, נוטלים אחד מהיניהם, ונשאר ארבע. לרבי שמעון, לא מחישיבים אותם שנים בכלל, ונמצא שיש שלש. לכאו', גם יהיה נפ"מ כמה עושה, שלא מחשיבים את אלו שלא מונים. אז, נמצא שלרבנן עושה יותר משעושה לפי רבי שמעון. ותחשב.
- אין חורשים אלא צורכם- מפרשים כתבו שר"ל שרק חורשים תחתיהם וחוצה להם כמלוא אורה וסלו. לולי זה, היה אפשר לומר ש”לצורכם” רצה לומר כל זמן שיש צורך, ולא אחר כך, אבל אלו הוא אף אחר שיש צורך, כל זמן שיש קצת ענין להם. דחוק.
- ודלא כר”ע- חושב אני שיש שכתבו על הבבלי שכולי עלמא מודו שהוא הלכה למשה מסיני, אלא שיש שהוסיפו דרשה מקראי (ולמדו ממנו דינים). לא משמע כן מגמרא כאן. אולי יש לדחות שגמרא כאן משמע שהוא רק נלמד מהלכה למשה מסיני. דחוק.
- בשעה שניתנה- ק"ק ל"ל אומר שכבר התיר ר”ג אותו.
- בשעה שניתנה הלכה- עיין במה שפירש פני משה. לכאורה, אין הענין רק שניתן להם שמותר, שאז לא ניתן להם שום דין כלל (אולי רק ניתן להם שהוא דבר טוב), אלא לכאורה הוא רק שלא להוציא בני אדם מלעשות כן. ותחשב.
** אף אנן -
לכאורה, צריך ביאור למה הוא יותר מחודש. ותחשב.
** של אחר -
נראה שהחידוש הוא שאף שכשבעל קרקע חורש, לא נראה שחורש לאילנות, שאינם םשלו, עדיין מותר.
- מה ופליגי- נביאים אחרונים- צריך ביאור מה אומר בזה, שלכאורה, אז, נביאים ראשונים לא עושים כלום. אולי אף אז נשכח וחזרו ויסדום. אז, צריך ביאור איפה רואה נביאים אחרונים כלל. ותחשב.
אולי קורא לנביאים ראשונים נביאים אחרונים. כמובן, צריך ביאור למה יעשה כן. ותחשב.
** ב: -כדעתיה -
לכאו', הביאור הוא שלא מסתבר שהתורה תאמר שדוחה את השבת אם הוא דבר מאוד קל לעשות, שיכול להביא אף מסוריה. אז, כיון שדוחה, מסתבר שלא יכול להביא מסוריה. גם יש לפרש שלומדים מפסוק שהוא דוחה, ולומדים סברה ג"כ לזה. הסברה היא שהיא דבר קשה, ויש צורך לעשות אותו בשבת. אילו היה אפשר להביא מסוריה, לא היה כן. ותחשב. (תחשב על שנים אלו, שבעיקר הם שווים.)
ודע שתורה כתובה קודם שסוריה היתה נכבשת. צריך לחשוב על זה. על הצדדים שכתבנו, מובן שאחרי שנכבש סוריה ההלכה ישתנה, שתלוי בסברה. ותחשב.
- לפום כן- נמצא, לכאורה, שדין ילדות שנראים כזקנים הוא כזקנים, אלא שאין להקל כך מפני מראית עין, ודין זקנים שנראים כילדים הוא כילדים. צריך ביאור למה יכולים להקל כילדים, אבל בנראים כזקנים אי אפשר להקל כזקנים. (ויש לדון אם זה כל כך קשה, שאולי היות זקן חלוק מהיות ילד, ודין שלש חלוק מדין עשר.)
- שדה קינים- עיין במה שאומר. לכאורה, אז, הענין הוא שכאן מחמירים. אם כן, צריך ביאור מה אומר, “אפילו יותר…,” שלכאורה, אם הוא על יותר, זה יותר סיבה להחמיר. ותחשב על זה.
** ג.
- רבי ליעזר- לכאורה, ר"ל "לעזר,” שבדרך כלל, נקרא רבי אלעזר בן עזריה.
- שיחולו- יש לגמרא צד שר"ל שיחלל אותם. לכאורה, לא צריך לחלל אותם, אלא שיהיו ראויים לכך. ותו"ת.
- ג’ קישועין- אם כן, לא צריכים רוב, אלא פלוראליט"י.
- אם כן- נמצא, אז, שיש בעיה כעין "אם כן נתת דבריך לשיעורים" אף כאן, אף שלכאורה אי אפשר לפרש כמו ששמעתי מר"ק, שמקשה מן הלשון. אפשר שלהיפך, לכן לא משתמש באותו לשון כאן.
** -פני משה
באר שמחלקת שבמשנה הוא רק בזמן המקדש, שאחרי זה כבר גזרו רבן גלמיאל ובית דינו לבטל איסור זו. יש להעיר שר"ג היה קצת אחרי החורבן (שבשעת החורבן, ריב"ז היה הנשיא). אז, הוא קצת לאו דווקא.
** ג: לא סוף דבר -
אם כן, צריך ביאור מהו קשיית רבי שמעון, שאינו תלוי בכל אחד ואחד, אלא תלוי בזמן האחרון. ויש לדון, שעדיין כל שנה חלוקה, ועוד שצריכים לסמוך על מה שאומרים בני אדם שעדיין יש ליחה.
** גמרא
מניח שבית שמאי מיקל. לכאורה, צריך לומר ששיטתם יוצא לפסול יותר. ואם תאמר הרי גמרא לעיל באר שאין זה מקולי בית שמאי. ויש לומר שר"ל שהוא רק נמנה אם הוא לעולם מקולי בית שמאי, וכאן הוא רק בדרך כלל קולא. גם יש לומר שכשנשאל, נשאל בציור שהיה חומרא לבית שמאי, כמו שמבאר בבלי ביומא.
** לכאורה,
נמצא מגמרא זה ששניהם או סוברים כבית שמאי או חולקים אליבא דבית שמאי. שניהם מוזרים. ותחשב.
** ד. שרשים -
מעניין שמניח בפשטות שלא ישרש בכך, ושרק הממהרים ישרש אחר שלש חדשים, שבבלי מזכיר שיטה שדברים נשרשים בשלש ימים. ותחשב.
** אבן -
נראה שהיו עשוים שהאבן הוא גדול עד שלא יכול האילן להפוך לצד שהיה נוטה ולקחת האבן עמו. אז, נמצא שאבן נשאר על צד האחר, ותלוי למעלה מן הקרקע, ועושה שהאילן כפוף היפך ממה שהיה כפוף לפני כן. ותו"ת.
- מתניתא- לא הבנתי מה אומר כאן, שברייתא אומר שרשב”א מתיר סמים בשביעית. פני משה כ’ שסמים הוא זיהום. אם כן, קשה איך יהיה משנה כמותו. וצריך לבאר.
** ה. כשנטעו לפני ר"ה -
משמע שזה רק אם ראש השנה עשה שלש שנים שלמות. לכאורה, יכול להיות שנעשה שלש שנים שלמות קודם ט"ו בשבט, אבל לא בראש השנה. משמע שאז עדיין אסור.
ותחשב על כל זה.
** חונא -
צריך ביאור למה גוזז ה"רבי" משמו.
** את כל תבואות -
היה אפשר לומר שדורשים מ"יוצא השדה.”
** מעשר אחד -
לכאורה, ר"ל שחולק על זה.
** ו. מכיון שהוקשו -
לכאורה, ר"ל שמשנה אומר טעמו כשאומר כן, ולא מוסיף עוד פרט.
** מושכים -
נמצא שאף רבי אב"י מתיר, אלא שהוא רק מותר שורה אחת מזה לזה. משנה שלנו משמע שמשקים את כולו, ולא רק עושים שורה אחת.
** ו: כמה דראב"י -
לכאורה, ר"ל שכמו שאומר כן ראב"י במרווחים שלו, שהוא עשר לבית סאה….
** משיקשור -
עיין במה שבאר פני משה. אם כן, לכאורה, זמן זה אינו זמן בשנה אלא זמן שתלוי בזבל עצמו, והוא חלוק לכל חלק של זבל.
** אין מוסיפים על האשפתות -
סברה אומר שיכולים לפחת, שאז בוודאי לא נראה כמפזר. אם כן, נמצא שלר"ש אין שיעור כלל למנין אשפתות.
** מראית עין -
יש להעיר שבוודאי יש מראית עין, שכל איסור זה נאסר מחמת מראית עין. לכאורה, ר"ל שאם חוששים כל כך למראית עין, אז נחוש אף לזה.
** משיקשר -
כהמפוזר- לכאורה, משמע שחושבים בני אדם שלא עומד לפזר אותו. זה אומר שאילו חשבו כן (שיפזר אותו), אז אין חשד, שיודעים שהוא רק מכין. הבעיה הוא שיחשבו שבזה פיזר.
יש לומר שמפוזר כאן ר"ל מין זבל אחר, שאינו מקושר, אבל לא פיזור על השדה. דחוק. גם יש לומר שאין הכי נמי, ויש מעלה בזבל, אף אם לא מפזרו בשדה. חושבים בני אדם שזה מה שעשה. נמצא, אז, לכאורה, שהיה אסור לעשות כן אם הוא מכוון לפזר, אבל היה מותר לעשות כן אם רק מכין. וצריך ביאור.
** שאל לר"ח בר בא -
עיין בגירסת עוז והדר (שכן פירש פני משה).
יש להעיר שלכאורה, אין הוכחה שחולקים בדין, שאפשר שרק חולקים אם חשב שילעיזו עליו מתחילה או לא. ותו"ת.
** אם יש לו בית השלחים -
נמצא, אז, שכשמשנה אומר, “עובדי עבודה" ר"ל עובדי עבודה של אותו מין שדה שיש לו.
** תוספת שביעית -
עיין במה שבאר פני משה לקמן, והוא ששאלת גמרא הוא שמיוסד השאלה על מה שרק דרבנן הוא. לכאורה, יהיה עדיין אותו סיבה לחשוב שהוא מזבל שדהו אז. אולי לא חוששים לזה, כיון שהוא רק מדרבנן, ואז החשש הוא שיחשבו שהוא יזבל בשביעית. דן אם חוששים לזה. ותחשב.
ודע שמחודש לומר שהוא גזירה, שלכאורה נדרש הוא מקרא. ותו"ת. ועיין בתחילת פרק ראשון, שהיה דיון.
** והורי -
יש לדון למה היה צריך לאסור ולצאת. נראה שהיה צריך לצאת כדי שלא ילעיזו עליו לומר שעדיין כך היה עושה מתחילה, אלא שעשה כן מפני שהבינו מה שעשה. אז, היה צריך להוכיח שלא רצה שום מעשרות, שזה יחסר כל מעשרות שהיו באים לו. ויש לדון. גם צריך ביאור למה צריך לאסור. ויש לומר שבני אדם עדיין יחשבו שהתיר לעצמו, אבל רק פחות מבני אדם שהיו חושבים כן אילו לא יצא. אז, עדיין צריך לצאת. ותחשב.
** ז. הא לצאת -
יש להעיר שעדיין אסור להוציא גבי גט; נראה שאמר דבר שאסרו בשניהם.
** בפוחת -
ר"ל שמה שאסר משנה להוסיף על האשפתות הוא רק אם הוא מוסיף על האשפלות. אם כן, לכאורה, לא היה לו לומר ששנים מותר, אלא שאף שלש מותר, שאי לאו הכי, אף אם לא מוסיף על אשפתות אסור. ותחשב. ונראה שאולי דרך של התנא לומר שפוחת מן האשפלות הוא לומר שמוסיף על אשפתות. אבל, קשה, אז, מהו הדיוק ששנים מותר. אולי לא מדייק כן ממשנה, אלא שכן סובר. דחוק.
** כאן בפחות -
לכאורה, תירוץ זה לא מהני לרבי ירמיה לעיל, שסובר שרק אסרו רבנן בפחות מכאן. ותחשב.
** ז: בעושה יותר -
לכאורה, זה קאי על רבי מאיר של המשנה. (לא נראה שפני משה מפרש כן- ועיין במה שמפרש על רבנן במשנה- אבל נראה שזהו הפשטות.)
** נמצא מזבל אותו מקום -
לא הבנתי את זה כל כך, שבין אם מוציא ובין אם לא מוציא, נמצא שזיבל אותו מקום. ותחשב.
** פתרין -
לא הבנתי כל כך החילוק בין שני הפתרים. לכאורה, הראשון הוא שכבר היה לו קצת בתוך שדה שלו בשביעית, ודן אם יכולים להוסיף עליו או לא.בשני, אומר שהוא שהיה לו קצת בביתו בערב שביעית, ורוצה להוציא אותו בשביעית. לכאורה, רק ר"ל שעושה אשפה מתחילה במעט מעט בשביעית. אם כן, מה שהיה לו אותו מעט מערב שביעית לכאורה לא שייך. ותחשב.
** אפילו ג’ חבלים -
עיין במה שבאר שזה רק לענין דין שבת (עיין). ויש לדון, שלכאורה, אף כאן צריכים שלא יצא גדי. ויש לדון, שאולי לא חוששים לאחד שיצא, שלא נראה שמכוון שיזבל את שדהו. גם יש לומר שמבאר שזה לא נוהג בכל זמן גבי זיבול (ורק אם יש לו גדיים).
** אפילו ג’ חבלים -
ח’ סאים- לכאורה, צריך להרחיק שיעור שמותר מכאן ולהבא, שהוא שמנה או שנים. לא הבנתי כל כך למה זהו השיעור. אולי נראה ששמנה כולל מה שידייר, ואז אולי הסברה הוא שמניחים שבני אדם יעשו כל הזיבול במקום אחד; אז, אם מרחיקים יותר מזה, מוכרח שיזבלו יותר משיעור המותר.
ויש לדון, שלכאורה לר”ש, לא יכולים לזבל הכל בהמשך, אלא צריך להיות כעין cross, כמו שפירש פני משה.
** ח. אם רצה -
עיןי במה שבאר. לכאורה, מה שאומר ר”ש כאן הוא שיקבע יתד באמצע, ויסבב אותו. אז, צורתו הוא כך. קצת קשה, שעל המשנה לא פירש שיטת רשב”ג כך, אלא שהוא כעין cross, ויש בו, אז, עוד בית סאתים. ותחשב.
** ריקה -
עיין בפני משה. נראה שכוונתו לומר שכבר התחילו לחצב מכאן, ואז הוה אמינא שמותר, אבל אין אבנים שנשארים שם, ואז אסור הוא.
** ח: יותר -
ר"ל, אף אם אין אבנים כך. נראה ש"יותר" כאן ר"ל יותר מעשר, ואז מותר כפחות מעשר, והוא שמותר אף בלי אבנים.
** שנים -
יש לדון אם ר"ל שכשיש שנים, כולם (יש לדון מה בכלל זה) ינטלו, או שר"ל שכשיש שנים, אותם ינטלו.
** זאת אומרת -
יש להעיר שממשנה אכן רואים שרוצה אדם באבנים שלו, אבל לא שרוצה בו לצורך של מה שכתב גמרא, שהוא כדי לתת מה שמנכש, שהרי שביעית הוא, ולא מותר לו לנכש.
** ט. מתניתא -
עיין במה שבאר פ"מ בקושיית גמרא. קשה, שהיה אפשר לומר שיש, בדרך כלל, ראיה ממה שלא שהה. רק אחר זמן עבודת שנה שביעית, שמוכרח שעושה לשמינית, מותר. ותחשב.
** מתניתא
- בגוף- צריך ביאור, עדיין, שהרי מגדיר הוא מה בכלל האיסור, אבל לא מבאר מהו החילוק בין גזירת תחילתו לגזרת סופו.
** אבני כתף באות -
קשה, שבמשנה לעיל אמר, “אבנים שזעזעתם….” צריך ביאור איך ליישב שני המשניות. ותחשב.
** כל שהן -
יש לדון מה ר"ל:
1. אם שלש צריך כתף, אז ניטלים. אם לא צריכים כתף עד יותר מזה, לא ניטלים.
2. אם הם דרכם בכתף, אף שלא צריך, יכול להגביה, ואף יכול להגביה כמה מהם.
לא נראה כצד זה, שאז מה שמזכיר (כמה מהם) לא שייך למה שהזכיר ת"ק. ותחשב.
** ט: קרוב… מצוי -
איני יודע מהו זה.
** י. חילוף -
יש לדון אם חולק על שני או על שניהם. (אבל אין לשונו משמע שחולק על ראשון.) עיין בפני משה. לשונו קצת משמע שחולק רק על שני, אבל יש לדון.
** או שנדיירה -
עיין במש"כ. גם מצוי אם גדרו, ולא הניח מקום. (ויש לדון, שואלי סבר שלא גזרו על זה).
** י: על קידוש השם -
דן בעבודה זרה, ואז צריך לומר או שכולל אותו דין בשם קידוש ה’ (ולא רק דין של לפני עשר) או שאף אותו דין אין לגויים.
** לינא אכיל -
יש לדון איך היה מותר לו לעשות כן כיון שאמר לו שהיה הורג אותו. ויש לומר שלא היה מותר, וטעה, או חלק לומר שאף על זה יכולים להמית.[fn:2] גם יש לומר שהכיר שלא היה הורג אותו.
** יא. חוכרים נירים -
עיין בגרח"ק. נראה שאין פני משה אומר כן, שפ"מ משמע שהוא קנס. לר"ח, אצ"ל שהוא קנס, אלא הוא כדי שלא יגרום לו לעבוד.
** אולפן -
צריך ביאור ל"ל ציינו למשנה שלנו.
** יגום -
ר"ל, נוטל זית שלם. דנים איך חותך אותו זית שנוטל. ותו"ת.
** יא: משלשה -
לכאורה, מונה הנשארים, שאם מונה מה שהיו קודם שהחליק, הרי לפעמים לא החליק, שאין נשארים. ותחשב.
** עד תשעה -
אם יש יותר, לכאורה, אז יש יותר צורך לו להחליק, ואז מותר לשרש. גי"ל שאז לא מועיל, ואז אסור אף לגוד.
גי"ל שמשנה רק מתיר להחליק שלש, אבל לא ארבע. אבל, אם יש יותר, אף ארבע מותר. ותחשב.
** מאימתי -
היסוד כאן הוא שמותר לאכול, אבל לא מותר להפסיד. כל זמן שהנאה אחרת הוא יותר טוב, אז, אי אפשר לאכול כיון שנחשב הפסד.
יש לדון למה, לפעמים, יהיה מותר רק לאכול בשדה, ולא בבית. נראה לומר:
1. אולי צריך לאכול באופן שיתן לו הנאה ביותר. אכילה בבית כשנגמר יתן לו הרבה הנאה, ואכילה בשדה בכל זמן יתן לו הרבה הנאה, שאוכל שם כיון שהוא יותר רעב.
2. אולי יכול להנות באיזה מין הנאה שירצה, אבל צריך להיות הכי טוב באותו מין. בשדה, לא מדקדק כל כך באכילתו, ואף שלא נתבשל כל כך, נחשב הכי טוב. אבל, בבית, מדקדק ביותר, ואז צריך לשהות כדי שיהיה הכי טוב.
וצריך ביאור למה יהיה הדין כך.
1. אולי לא מחשבים במה שיקרה. אז, רק צריך להיות שזה הדבר הכי טוב עכשיו. אז, דנים בשהייתו על אילן נגד אכילתו. אז, אף שאין אכילה בשדה כל כך טוב כמו שיהיה אכילה כשממש נגמר, עדיין הוא טוב יותר משהייה על אילן. (במילים אחרים, אף שאינו כל כך טוב כשהייה, יש בו מעלה במה שהוא עכשיו.) רק אכילה בשדה באותו זמן, שלא מדקדק כל כך, הוא יותר טוב משהייתו.
וצריך ביאור למה יהיה הדין כך.
ויש להעיר שדיון גמרא של מלוגמא מעניין על פי זה. לכאורה, יש רק צד אחד שבו יכולים לדון שמלוגמא יהיה מותר, והוא צד שלישי. ותחשב.
** יב. תני כאן מיד -
לא הבנתי שקלא וטריא של גמרא זה כלל. היה נראה לומר שר"ע אומר דין, גמ’ אומר שהוא אף מיד, ומקשה שמשנה שלנו לא אומר כן. אז, מתרץ שאומר כמשנה שלנו, אבל הוא אומר כן רק בתאנים, אבל בשאר פגים, הוא עונת מעשרות. צריך ביאור, שלא צריך כלל לחלק, שכיון שחוזר ואומר שהוא כמשנה שלנו, אין עוד קושיה. גם צריך ביאור מהו החילוק, שמשנה זה אומר שהוא עונת מעשרות. וצריך ביאור.
** בשביעית -
יש לדון אם הוא דין אגב (ממה שלא נחשב אכילה לענין שביעית…) או מחמת שאי אפשר לאכול אותו. ויש לדון אם זה מקדים זמן או מאחר זמן. תלוי בביאור גמרא לעיל שלא הבנתי.
** קור -
היה אפשר לומר שהחידוש הוא שהוא כעץ. אז, קשה איך מביא ראיה מכאן.
** יב: הכניסו שליש -
משמע שאומר שהוא שליש הלוג. אם כן, הוא פחות משיעור שנמנה לפניו; צריך לומר שלא מונה כסדר, וצריך לומר שסיכה, ואף סיכה בשדה, צריך שעושה יותר.
** כתיב יובל -
כל זה צריך ביאור:
1. צריך ביאור למה מביא קרא של יובל, שמשנה לא דן כלל ביובל. ראיתי לאחד מן המפרשים שכתבו שלומדים דיני שביעית מדיני יובל.
2. צריך ביאור למה צריך קרא זה, שכבר הביא שני קראי לעיל (בהלכה שלפני זה).
** כתיב כי יובל -
עיין במה שבאר פני משה בדרשה. אין זה כל כך פשוט, שצריך לדון מה מקיש. אולי מקיש לו ארץ בעת יובל. אם כן, קצת מוזר שדן גמ’ בקדושת א”י של כל הזמן. אפשר שמקיש קדושת א”י בכל זמן. מעניין שמניחים שקאי על זה, שקרא רק קאי על יובל. ותחשב. אולי מניחים שקדושת הארץ לא משתנה.
** יג. כיצה הוא יודע -
צריך ביאור איך יודע בכל זמן מתי נגמרים (שצריך לדעת כן כדי לקחת אותם). מה שעושה אז, יעשה עכשיו. ותו"ת.
** ט”ו בשבט -
אם שנתו למעשר מתחיל מאז, צריך לדון מתי נחשב שביעית של מעשר, שהרי שנה שביעית מתחיל מראש השנה. ותחשב על זה.
** מה -
עיין במה שבאר פ”מ. הצד שעושה אחת לשלש שנים, וחייב כיון שלא יעשה עד אז, אף שלא התחיל, הוא מחודש ומעניין. ותחשב.
** יג: אם חל לתוכם -
לשון זה קצת מוזר; ר"ל שמונה מאת ימים, ואז יודע מתי חנטה.
** מעתה -
עיין במה שבאר למה חלוק הוא מחנטה. יש להעיר שלכאורה, לא באר למה בחנטה יותר מסתבר שיהיה הכל הולך אחר שעת חניטה, אלא רק מפרש שאם אומרים שהולך אחר חנטה, מוכרח שגם אומרים שהכל הולך אחר חנטה. אז, לכאורה, צריך לומר שיש שום מקור לומר כן, ורק שואל איך יודע מה אומר המקור. ותו"ת.
** אמר ליה -
אולי ר"ל שהשאר עומד לבוא, ולכן נחשב שכבר בא. ותחשב.
** טו: מאבותיך -
לכאורה, זה יהיה מקור רק לחילוק אחד. אז, צריך ביאור איך לומדים מזה יותר מחילוק אחת.
** רבי אליעזר -
נמצא שהיה בית מקדש אף בלי קדושת א"י.
** טז: גניא -
קשה, שאולי משנה הוא רק אחר שגזרו. ותחשב.
** וילכד -
עדיין אפשר לומר שלא כבשו אותו בבית שני.
** משתשהה -
עיין במה שבאר פני משה. צריך לומר שאותם שיודעים זה ראשון לא יודעים גזירה אחרת ראשון. ותחשב.
גם צריך ביאור מה נהנה בזה, שהרי לאותם ארבעים יום, סוברים דברים חלוקים.
** עד בואי -
נמצא שאפריקי טוב כא"י. נראה שזה מעניין, על פי מה שקרה ביוגנדא.
** מעתה -
עיין בפ"מ שכ’ שסבר גמ’ שטעם ההיתר הוא משום שכותים גויים. קשה, שאז איך נהגו כן מימות יהושע, שלא היו כותים שם אז.
** צריך ביאור
מהו תירוץ גמרא, שרק משנה למה אין תו"מ, אבל עדיין לא באר למה מחמירים בחלה. וכ"ז צ"ב.
** יז. מהו לטחון -
נראה אולי שהשאלה הוא אם יש ס"ר באיסור של גוי.
** מתניתין -
קל לדחות שמתיר בסוריא כשאינו של גוי. אולי היה לו לפרש. דחוק.
** יז: לא הבנתי
כל כך את המחלקת בין ר”ז לר”ל ור”א. לכאורה, חולקים אם העיקר נשתנה על ידי מה שגדל. אז, לר”ז, הבנתי את המשנה, שאומר שהולך אחר מה שגדל. לא הבנתי המשנה לפי החולקים; פני משה כ’ שסוברים שמשנה הוא כשהולך משנה ששית לשנה שמינית. צריך ביאור, אז, לאיזה נפקא מינא הולכים בתר מה שגדל, שדינו שווה. אולי הולכים אחריו למעשה, שהכל ניתן לאותו מעשר. צריך ביאור, אז, למה הדין הוא כן, ולמה לזה הולכים בתר הגדל יותר מלדיני שביעית. וצריך לחשוב.
** מתקיים -
צריך להעיר שהיה נראה לומר שבעצם, יש לו ביעור, אלא שיש לו ביעור רק כשהוא כלה, ולעולם לא כלה. לא נראה כן, שהרי כלה אם כבר נטלו כולם. ויש לדון, שאולי לא נאסר כשממש לא נשאר, אלא כשהיה כלה מעצמו[fn:3]. ותו"ת.
** היא שביעית -
עיין בר”ן בנדרים על גמרא כעין זה (גבי נדרים) שמפרש שעדיין מה שהוא מותר בא”י עדיין נתחשב. (מסתמא, הוא מפני שיותר קל להשיג אותו, שלא צריך להביא מחו”ל.)
** יח. קליפי רמון -
יש לציין לתוס’ גיטין (יט:).
** צבעים לאדם -
לכאורה, כבר יודע שיש על מיני צובעים קדושת שביעית, שכן אומר משנה. נראה שזה חלוק ממיני צבעים, שמיני צבעים היו לצבוע בגדים וכדומה, אבל זה הוא לצבוע לאדם. לכאורה, זה לא חשוב, או מפני שלא עושה כל כך שינוי באדם, או מפני שלא ישאר באדם[fn:4], אלא יאבד אותו מיד. ותו"ת.
גם צריך להעיר שבגמרא זה נראה שדן אם מותר לצבוע בו. יכול להיות שני פירושים למה זה שייך לנידון של גמרא אם יש לו קדושת שביעית:
1. אם הוא צורך מעליא, עד שיכול לעשות כן בדבר שראוי לאכילת אדם, אז בודאי יש לדמיו קדושת שביעית. ויש להעיר שגמרא כבר פושט שיכול לצבוע במה שמיוחד לבהמה, אף שיש למאכל בהמה שביעית. אז, מעניין שלא יכול לפשט כבר משם.
2. אולי דן אם יש בו קדושה ואז אסור לצבוע בו, אף שעיקרו הוא לצבוע, כיון שאף ראוי למאכל.
וצריך לעיין בגמרא לראות איזה מאלו נכון.
** צבעים לבהמה -
לכאורה, בו צובעים בהמות. כמובן, זה דבר מוזר לעשות.
** יט. היין -
עיין במה שבאר. לכאו’, לא תלוי בקיום היין, אלא במתי נמצא זיתים (או ענבים) בשדה.
** ושרע
- עיין במש"פ. לולי זה, היה נראה לומר שלא פ’ אותו כיון שלא שווה בכל אלו. וצ’ לעיין יותר בדברים שנז’.
** ושרע -
הוא מלשון "או שרוע או קלוט….”
** כ. למיתן -
נמצא שזה יותר טוב לעניים. יש לדון, אז, ל"ל עשו ארצות שנזכרו בתחילת חגיגה לא"י בשביעית. ותו"ת. אולי רק ר"ל
שחייבים הם במעשרות, אבל עדיין יש שביעית מדרבנן. ותחשב.
** כ: הלכה -
נמצא שפשוט לירושלמי שהלכה כת"ק של סתם משנה, אף שיש אחריו חולק. לכאורה, צריך לומר או שחולק על מה שאומר הבבלי בזה ביבמות או שסובר כמה שאומר תוס’ שם (שעדיין הסתם הוא רבים).
** כא. רבי יוחנן -
מעניין, שבבלי אומר (פרק המפקיד) שר"י לא רוצה להקים משניות כשני אמוראים.
** כא: אר"מ -
נמצא שבמיעוט אחר מיעוט, השני הוא הריבוי. ותו"ת.
** כב. תובע -
יש לדון איך ללמוד מציור שאמר לזה, שכאן לא מסתבר שחזר בו מחמת זה.
** כב: במרחץ -
לכאו’, יוצא מזה שפירות שביעית לא רק אסורים, אלא קדושים.
** קורד’ -
נראה שאולי משם באו הKurds, והוא Kurdistan.
** כה: כלה לחיה -
מגמרא יוצא, לכאורה, שמה שאין חיה יכול לחיות על פירות שבמקום אחר הוא מפני שלא ילך ולא ישהה שם.
** תמרים -
ממשע מפני משה שהענין הוא שרגילים להביאם ממקום למקום, ואז נמצא לחיה. וצריך לגדר, שהרי לא מביא לצורך חיה, אלא לצורך עצמו. מה שיכול לתת לחיה לא מהני, שהרי יכול לתת לעולם. אולי מאד הובא, ומסתמא ימצא חיה מקצתו. דחוק.
** שפלה שבהר -
אל הבננתי איזה נפקא מינא יש, שאין נפק"מ בין הר לשפלה, אלא בין יהודה, גליל, ועבר הירדן. אולי אומר זה לפי ר"ש, שיש נפק"מ.
** קפודקאי -
משמע שלא היה אף שלש מהם, שאי לאו הכי, תקתם קל.
** כו: קדושת שביעית -
לא הבנתי כל כך מה זה אומר. אין לפרש, לכאו’, שאומר שהיתר לשרוף אותו ר"ל לבער אותו על ידי שריפה, שאם כן קשה למה עושה כן רק עד רביעה שניה. אז, צריך ביאור מה אומר.
** אין שורים -
לא בטל- יש לדון מהו הציור, ולמה ביטול מותר. אולי דן אם זה נחשב מאבד אותו. אולי נתינתו בטיט נחשב איבוד שלו, אבל אם אינו שם, אינו איבוד, שעשייה שדבר אינו בעולם אינו איבוד. ותחשב. בביאור הדבר, נראה שאולי בעיה של איבוד הוא שהוא בזיון לפרי. אז, צ"ל פרי במצב שלא ראוי לאכילה להיות בעיה. אולי מצאנו כעין זה ברש"י עירובין כשמבאר (גבי הלכות ברכת שהחיינו (תן חלק לשמנה)) למה צריך לשתות מכוס של ברכה. ותחשב.
** אין שורים
- עיין במה שאומר. קשה, שאומר שהבעיה הוא שלא בטל, אבל אחר כך אומר גמ’ שהוא בטל. נראה שצריך לומר אחד משני דרכים:
1. קצת בטל; בטל די להתיר בדיעבד אבל לא לכתחילה. דחוק שלא יזכיר זה.
2. יש חילוק בין אם גבלו או לא. קשה, אז, למה גמ’ חילק אף בין לכת’ לבדיעבד. אולי יש סיבה להתיר בדיעבד, שלא רק דן אם מותר לעשות כן בשביעת (על"ע) אלא בדינו אחר ביעור. ותחשב.
לולי מש"א פ"מ, היה נראה לומר שאסור כיון שמאבד אותו, אבל בדיעבד מותר, שהרי אינו שם, שבטל.
** כז. מי שהיו -
צריך ביאור למה מה שאינם מקפידים על שביעית עושה שלא מחזיקים לו טובה על זה. ותחשב.
** דהוא שמותי -
משמע שלשון זה אומר שהוא מבית שמאי. עיין בשבת (קל:) ומק"א שדנו בזה ראשונים[fn:5]. אולי כשאומר ירושלמי מילה זה, אין כוונתו למה שמכוון בבלי, אבל לא נראה כן.
** כז: בשאין לו קרקע -
עיין במש"כ. לא הבנתי כל כך מה ר"ל. לולי זה, הייתי אומר שגמ’ אומר שאף יכול להיות כרבנן, ובציור שאין לו קרקע לשעבד.
** כח. ר"י -
משמע- נ’ שהמשמעות הוא מלשון פוסקת, שמשמע שהפסיקו בעל כורחו, שהיה רוצה שיעבד יותר, אלא שנאסר.
** כח: ולא רבי יוסי כר"י -
ע’ במה שמפרש. לכאו’, אז, ר"ל שרבי יהודה לא סובר כרבי יוסי.
** אחר עבורו -
צריך ביאור מה יהיה הנפק"מ, שכבר הוא מעובר. יש לומר שלא עיברו אחר כך, אלא קדשו אחר כך. לא נראה כן מלשון גמ’. גי"ל שכבר קדשו אותו. אם כן, קשה למה תולה אותו במה שהוא ביום לב. משמע שיכול ביום לא. זה מחודש.
* Footnotes
[fn:1] ויש להעיר שהיה נראה לומר שאולי כשגמרא אומר שלא רוצה לומר שהוא אסור, אינו מפני שהותר, אלא שלא רוצה לקבוע אותו בדין, כיון שיכול להיות אסור. ותחשב. ויש לדון, שאז מסתבר למה כתב אותו במשנה. ותחשב.
[fn:2] אינו קשה להניח שחלק או טעה, כיון שגמרא מזכיר חולק.
[fn:3] אולי הענין הוא שכלה בפ”ע, ואולי הענין הוא שמוכרח להיות כלה. ותו"ת.
[fn:4] ואולי זהו הבעיה, ופשוט שמותר לצבוע אדם, אבל אולי אסור אחר כך לאסדו.
[fn:5] עיין בתוס’ שמביא מירושלמי שר"ל שהיה מבית שמאי, אבל לא מביא ראיה זה.
