** ב. כתחלתה -
אם סובר שהוא כתחילתה, ק"ק ל"ל לומד ממה שמשכן נתחנך בניסן, ואז, בהכרח, התחילו להביא קרבנות חדשות ממון של אותו זמן.
נראה ש"מתחילתו" לא ר"ל שמדמים אותו לתחילתו, שמהיכי תיתי לדמות כן, אלא ר"ל שהוא נלמד (בגזרה שווה) מתחילתו. גזירה שווה הוא לקרא שמזכיר באיזה חדש נותנים.
** דל כן -
עיין במה שכתב. אז, לכאורה, ר"ל שהוה אמינא שרק צריך לתת, אבל לא צריך להביא הקרבן מזה.
יש לדון איך אף נדע שצריך לתת מן החדש, שאותו קרא לא אומר שצריך לתת, אלא דן בהקרבת הקרבן. ותחשב.
** אף שימוע -
קל לומר שלא מנה אותם כיון שאין זה זמנם מחמת שהוא אדר, אלא מחמת קורבתו לזמן אחר. (ועיין בבבלי, שדן שם בקריאת פרשיות מיוחדים. ויש להעיר שיש מהם שהם גם כן מחמת קרובת הזמן לחדשים אחרים.)
** ויאות -
יש לדון מהו הצד שנאמר אותו בראשון (או בשניהם). ותחשב.
** עד כדון... דקיקין -
עיין במה שכתב קרבן העדה. יש לדון למה לא יכולים להכיר:
1. אולי לא יכירו שהם גדלים.
2. אולי לא יכירו מאיזה מין הם.
3. אולי לא יכירו שיעור שלהם (אם הם יותר משיעור כלאים או לא).
** בבל -
משמע שגמרא מצדד שאולי יש טעם אחר להשמיע על שקלים. (כן נראה מקרבן העדה. לולי זה, היה אפשר לומר שגמרא מצדד שאומרים לא פלוג, ואז תלוי הוא באדר, ואולי נאמר אותו בשני האדרים או רק באדר ראשון.) יש לדון מהו אותו טעם אחר. אולי הוא רק שבני אדם ישכחו אותו הדין אם לא מזכירים אותו, וחז"ל בחרו זמן להזכיר אותם. הזמן שבחרו היה אדר, אבל לא שייך למה שהוא קרוב לזמן שנותנים שקלים. ותחשב.
** ב: ולמה אמרו בשלש -
אין כל זה ברור לי כל כך.לכאורה, קושיית גמרא ראשונה הוא שאם כן- שזמן הכרזה הוא כדי שיתנו בזמנם- צריך להיות זמן ההכרזה יותר מוקדם לבני בבל[fn:1]. גמרא אומר שאולי הוא קרוב די לזמן שצריכים להביא, שהרי תורמים בשלש זמנים. (וקשה לי, אז, מה הוא המקור, שהרי מצאנו מקור שצריכים לתת בניסן, אבל מקור זה יאמר שצריכים לתת בניסן, ולא בשאר חדשים.) דוחה שתורמים רק בזמן אחד.
איני יודע, באמת, מה הוא ה"תורמים" שמזכיר. פשוט שאינו זמן שצריך להביא, שאז דיחוי גמרא אחרון לא מסתבר. גם, אז, יהיה פשוט מה אומר המשנה.
ראיתי בארטסקרול משניות שהוא הזמן שלוקחים שקלים ונותנים אותם בשופרות של קרבן ציבור.
אז, גמ' מוכיח ממה שתורמים עוד שנותנים לאחר זמן, ולכן צריך לתרום. (קשה, שעדיין לא רוצים שטוב להם לעשות כן, אלא שכן עושים; אבל, אולי היה להם להביא קודם אותו זמן, והיה לנו להכריז קודם לכן.) אז, דוחה שלא צריכים להביא אחר כן, ותרומה ראשונה עולה להם. אז, לא היה לנו להכריז. (לכאורה, זה רק טוב אם קושיית גמרא הוא שלא להכריז, ולא להכריז מקודם, שלכאורה, טוב שיכריזו לפני זמן, שטוב שיתנו משלא יתנו. ותחשב.)
וכל זה צריך ביאור. ותחשב.
** יד כולם שווים -
נראה שרצה לומר שעדיין יהיה לכל אחד חלק שווה בקרבן. ויש לדון למה זה כן, שהרי אחד גרם הקרבן יותר משאר. נראה שיחס החשוב לקרבן (שגורם כפרה) אינו מה שגרם לקרבן שיבוא, אלא שבא מממון שלו (אולי זה מה שגרם שיבוא, אלא שהוא גרמא יותר דיירקט). אם כן, כיון שכאן מסור לציבור הוא, הרי הם בכללו רק מפני שהם בכלל ציבור. אם כן, כולם שווים, שבהיות בכלל ציבור, כולם שווים.
** לא בא אלא -
אי נמי- לכאורה, זה אי אפשר לפירוש שאמר ליישב זה עם מה שאמר בפ"ק דמגילה שמלמד שצריך לקרוא אותו באדר שני, שאז משנה מדוייק. אז, לפירוש זה, צריך לומר שזמניהם אומר שיכול לבחור לקרוא בראשון או בשני, כפשט אחר שכתב.
** להבא -
לפשט שני של קרבן העדה, נראה שאומר שדורשים קרא של "זמניהם" לומר דין לכתחילה, ואז לא קשה למה צריך לקרוא לו בשני.
ויש לדון למה נבחר לדרוש אותו קרא לכתחילה, ולא בדיעיבד. ותחשב.
** לא אמר אלא הנהיג -
עיןי במה שפירש קרבן העדה. מחודש לומר שלא מורים כן אבל הנהיג כן. לכאורה, סובר ש"הנהיג" רק ר"ל שהניח אותו מנהג. עדיין קשה, שמי אמר לגמרא שכן ר"ל ולדייק כן. וצריך ביאור. ותחשב.
** כותבים -
עיין במה שפירש. מלשון גמרא שלנו, היה נראה יותר לומר שכותבים אדר ראשון "אדר ראשון," ואדר שני "אדר," ובזה חולקים, שרי"א שלראשון נקרא "אדר" סתם.
** סתם -
יש לדון למה ראשון נקרא סתם:
1. בא ראשון. אז, אין צורך לפרש אלא מחמת ביאת שני, ואז מפרשים אותו. ותחשב על סברה זה, אבל נראה לי שכן מדרהרים בני אדם.
2. כל אדר הוא אדר ראשון, אבל לכל אדר לא נקרא אדר ראשון, אלא אדר. אז, מוזר לבני אדם לקרוא לאדר זה אדר ראשון. ותחשב.
יש לדון למה שני נקרא סתם:
1. מצוות נאדר והגות בו.
2. מסתמא, בני אדם מתחילים לדון באדר ראשון קודם שדנים באדר שני. אז, צריך לבאר מהו. כיון שדנים במאדר שני, כבר נקרא שם אחר לאדר ראשון, ואז נקרא זה אדר שני. ותחשב.
** ג. דנים דיני -
הייתי סבור שהדין הוא שכל זמן שיש שני עדים שראו דבר, באים לפני בית דין, ודנים בו. כנראה, אין זה הדין.
באמת, צריך להגדיר כל זה, שהרי אין דנים שני מיתות בחד יום, ואם כן, צריך לומר שדנו ביותר ימים. אולי ר"ל שמתחילים מאז, והולכים עד שנגמרו כל מי שצריכים ליהרג.
וצריך ביאור למה ישהו עד כאן. אולי עשו דברים אחרים בשאר השנה. יש לדון מה עשו.
גם יש להעיר שגמרא דן בדיון ביום טוב וכדומה (כן אני חושב). לכאורה, צריך לומר שר"ל פסח, והוא כשעדיין לא כלו הדיונים. ותו"ת.
ודע שאינו מסתבר שמי שתובע את חבירו צריך לשהות עד  אותו זמן. אולי ראו לפני כן אם יש צורך לעשות אותו מיד. ותחשב.
** בר בת יעקב -
מצאנו אמוראים שנקראים על שם אמם. רש"י מבאר לפעמים גבי רב מרי בר רחל שהיה אביו גוי בשעת הורתו.
נראה שאפשר לומר כאן על פי מש"כ תורה תמימה בשם מדרש הגדול, והוא שעכשיו קוראים אחר שם זקנים כדי להורות הייחוס. נראה שכדי להורות ייחוס של רבי יעקב, היו קוראים אותו רבי יעקב בר בת יעקב, להורות שהוא אותו יעקב, שעל ידי כן שם עושה שנזכר ייחוסו. אז, נמצא שכך היה נקרא.
גם אפשר שהיה אמורא אחר עם אב שהיה לו אותו שם של אב של רבי יעקב. לא מצאתי כל כך אמוראים באותו שם (יעקב), ואז לא כל כך מסתבר.
** מנין לציון -
נראה שהמשיב שאל כן, שבלי זה, לכאורה, היה נראה שידוע מסברה, שהרי צריך כהן להרחיק מטומאה, ואז צריך לדעת איפה הוא הטומאה.
** וטמא -
ואם תאמר הרי צריך לגופו. ויש לומר שאין הכי נמי, ורק אסמכוהו עליו. זה מטעים טוב עם מש"כ לעיל שכבר ידוע מסברה. גם יש לומר שלומד ממה שצריך מצורע להזהיר שבא, והוא, גמרא מניח, מפני שמטמא בביאה.
** שתהא טומאה -
לכאורה, היה נראה לומר שרק לומד מן הענין, כמו שכתבנו למעלה. אבל, לשון הדרשה משמע שדורש שהטמא קורא טמא, והוא שהטומאה קורא טמא. ותחשב.
** והיה נתון תחתיה -
עיין במה שבאר קרבן נתנאל. לא הבנתי למה צריך להיות תחתיו ממש, שיכול להיות רק מקצת ממנו תחתיו ועדיין יטמא. אם כן, צריך ביאור מה אומר. ותחשב.
** שני שמחות -
לכאורה, ממה ששמחו על מה שהיו מנכשים להם, צריך לומר שלא רצו באותם כלאים, אלא שרק לא רצו לנכש אותם. אם כן, משנה שלנו צריך להיות כרבי עקיבה, שסובר שאסור לקיים כלאים. גם יש לומר שנמצא שחורש להם, ולכן אסור. עיין בתחילת פרק ראשון של מועד קטן.
גם יש לומר שרוצה שיהיו שם, שרוצה לעקור אותם קודם שיזקו לשדה שלו. לא היה צריך לכך, שהרי בית דין עקרו להם. ותחשב.
לכאורה, רואים נגד זה ממה שהיו שמחים שמחה אחת, והוא שאם זרעו אותם, נמצא שהיו אובדים אותם. ויש לדון, שאולי ר"ל שרק היו נחסרים מעט, ואז עשו אותו כיון שאולי לא ימצאו בית דין. דחוק, שלא משמע כן.
** לא פטור ממעשרות -
קשה, שאף משנים דינים דאורייתא שם, ואף בקום ועשה. אז, צריך לומר שבעיבור יש להם יותר כוח מן הרגיל. אז, קשה מהו הראיה מכאן. (עיין בגמרא לקמן, שידחה כן, אבל לא יביא ראיה כמו שכתבנו, אלא מביא ראיה מקרא.)
** וחדש אחד -
עיין במה שפירש. לכאורה, לולי זה, הייתי אומר שהראיה שגמרא מניח (וצריך ביאור למה) שאותו חדש שמוסיפים פטור ממעשרות. מביא ראיה מאותו דין.
לא נראה כן מקרבן העדה, שמבאר שהראיה הוא ממה שמעובר. (אולי יש לדחוק שאומר שהראיה הוא ממה שהוא מעובר לענין מעשר). משמע שסובר שהיה לו להיות שלא נעשה מעובר, כיון שלא יכולים לשנות את כל הדינים. ותחשב למה יהיה כן. אולי לא היו רבנן עושים דין למקצת, ואם לא חל כולו כדין תורה, לא רוצים לעשות כן (ויהיה כעין לא פלוג).
** אין השנין כתיקנם -
הענין הוא שאין אנו יכולים לסבול שלא יהיה מעובר, שנצרך לחשבון שלנו. לכאורה, "אין השנים כתקנם" ר"ל שאם לא נעבר אותו, יהיה נמצא שאין השנים כתיקנם. עיין בקרבן העדה, שקצת קשה ל"ל מפרש את זה.
** ג: משום קנסא -
לכאורה, לא ר"ל שעשו פטור מעשרות מקנס, אלא ר"ל שפטור ממעשרות מחמת אותו קנס שעשו להפקיר אותו.
** בית שמאי -
מחלקת בית שמאי ובית הלל הוא בפאה, והוא אם הפקר לעניים הוא הפקר או לא. אז, לכאורה התלייה הוא כך:
לבית שמאי, יש לומר שמחייבים אותו להפקיר לעניים. אז, יהיה פטור מן המעשר, שהפקר כזה חל ופוטר ממעשר. אבל, זה אינו אפשר לבית הלל, שבית הלל סובר שאין אדם יכול להפקיר לעניים ולא לעשירים.
יש לדון מה סבר בית הלל. יש לדון אם סובר שאינו הפקר (לא חל הפקר כזה), או סובר שהפקר הוא, אלא שלא פטור ממעשר.
אם נאמר כראשון, יש לדון איך מתרץ על פי כלל זה של הפקר בית דין הפקר. אולי הוא שאז בית דין עושים חלות זה. יש לדון, שזה מניח שיש לבית דין יותר כוח מאיש בעצמו. גם יש לומר שמתרץ שעשו שאי אפשר לעשיר לקנות אותו. עדיין ק"ק, שזה לא יפסק עשיר מלאכול אותו. גם קשה, שהיה אפשר לעשות איסור לו לקחת אותו, אף בלי זה.
לצד שני, גם כן צריך ביאור, שרבנן יש להם כוח להפקיר, אבל לא לפטור ממעשר. אולי יכולים להפקיע כוח וזכות הלויים, וממילא אין חיוב מעשר. זה מחודש.
** שוב אינו פוסק -
קשה למה, שאם חושב בתחילה שחייב לשקול בשביל בנו (מסתמא, הוא מטעם חינוך), וחוזר בו אחר שנה, למה לא יפטור.
** ישבו במקדש -
עיין במה שפרש קרבן העדה. צריך ביאור למה זה יעשה שבני אדם יביאו יותר מהר. נראה שאולי בני אדם לא רוצים שאף לא התחילו. אז, יבואו לשולחנות, אבל עדיים לא באו למקדש לתת. כאן, כיון שהם כבר במקדש לשולחנות, יתנו.
** לעצמם -
של ישראל- עיין במה שפירש. יש לדון איך נדע ממה בא. יותר היה נראה לומר שכיון שנתנו לציבור, נעשה של ציבור. אז, אינו עוד של כהן.
ודע שמהוה אמינא זה (וכן מלשונות מקרבן העדה לקמן) משמע שציבור הוא שותפות גדול, ולא שהוא מין אחר של קנין (אומרים צד שהוא קנין למושג של ציבור).
** אין ממשכנים -
בכל אלו, יש לדון אם הוא מפני כמה קשה הוא למשכן או כמה קל הוא שלא לקבל משכון. בתוך צד שני, נראה שיש לדון אם הוא מפני שמשכון לא יועיל כ"כ לנתינת שקל או שנתינת שקל אינו כל כך טוב. ותו"ת.
** ולמשכן -
שניו- עיין במה שכתב. אם כן, עיקר חסר מן הספר, שכאן לא ר"ל שהביא שערות, אלא שבא לכלל שניו.
** ולמשכן -
לצד ראשון, רואים שהוא חייב לתת קודם שיגיע לכלל שנים, כיון שיש לו סימן. אין זה כל כך פשוט; על כל פנים, הוא מחלקת תנאים בנדה. ותחשב.
** כיני מתניתין -
עיין בפשט ראשון שמערב בו שלום. נראה שהפשט הוא שעיקר הענין הוא דרכי שלום- אלא שהוא מפני דרכי כבוד. זה אומר שמה שצריך להיות שלום ביניהם ובין בית דין הוא מפני שמקריבים קרבנות שלנו. (עדיין ק"ק, שמשמע שהענין הוא שמקריבים קרבנות, ולא התוצאה, שאז צריכים לנהוג בהם כבוד. לשון גמרא לא משמע כן.) אם נאמר שרע להיות במחלקת עמם כיון שצריך לכבד אותם, אם כן, רק בנקודה זה צריך להיות פשט שני חולק על פשט ראשון, ולא כל כך משמע שרק חולק על נקודה אחת, אלא יותר משמע שחולק על כולו. ויש לדון בזה.
** הוא מותיב -
נראה שתירוץ של גמרא הוא שהשיבו רבנן לשיטתם, ולא לשיטת רבי יהודה, כיון שרבי יהודה היה מקשה לשיטתם, ולא לשיטתו.
עדיין קצת צריך ביאור, שלא היה להם להקשות לו, אז, ששל ציבור חלוק אף כאן, שהוא אף כבר הניח זה, אלא היה להם להקשות, כמו שאומר גמרא לקמן, שזה נחשב של ציבור. אז, עדיין קושיה זו צריך ביואור.
** כל שנידר -
צריך לעיין בהלכות אלו. גמרא יבאר שיש מהם שרק מתקיימים בתחילה. יש לדון אם זה אף בשאר קרבנות או לא.
** ד. קלבון -
כל סוגיית קלבון מבולבל לי מאד. מגמרא לקמן, נראה שיוצא ארבע זמנים שחייבים קלבון:
1. חייבים קלבון כשהקדש צריך לשנות את המטבע. אז, כשנותן חצי שקל, חייב קלבון.
2. חייב קלבון כשנותן מטבע שאינה נכונה. כן אומר רב לקמן (ויש חולק עליו). זה מעניין, שהקדש לא רוצים מטבע חצי שקל- להיפך, הם עושים ממנו מטבע אחר- אבל עדיין צריך לשלם.
3. חייב קלבון כשמקבל מהם מטבע אחר, שהם שמשמו לו כשולחני.
4. חייב קלבון בכל מקום כדי לדמות לשקל של אש (ר"ל, כיון שהיה שלם, ושלנו אינו שלם, צריך קלבון). כן סובר רבי מאיר, וחכמים חלקו עליו.
אז, יש כמה דברים שצריכים לבאר.
אם נותן אדם שקל בעד חבירו (ואינו מתנה), חלקו חכמים ורבי יהודה אם חייב אחת או שנים. צריך לבאר שני דברים:
1. איך נתן שני השקלים- נתן סלע שלם או נתן שני שקלים.
2. כשמחייבים אותו קלבון או שני קלבונות, האם זה על של חברו או על שלו ושל חברו.
אם לא נאמר כרב, ואם נאמר שנתן סלע שלם, אז, אין חיוב ראשון, אין חיוב שני, ואין חיוב שלישי. נשאר רק חיוב רביעי. אז, אולי מובן איך רבי מאיר יחייב שנים, שהרי צריך לתת בעדו ובעד חברו, אבל לא מובן למה רבנן יחייבו אחת (אם לא שנאמר שרבנן אלו סוברים כעין רבי מאיר, אלא שמחייבים אחד בכל זמן שנותן, ולא בכל שקל שנותן. צריך ביאור למה יהיה כן. לא נראה כן כלל.)
אם נאמר שנתן שקל ושקל, אז מחמת הראשון יחייב שני קלבונות, ומחמת השני יפטור (שעכשיו אין אנו ברב), ומחמת השלישי יפטור, ומחמת רביעי, רק רבי מאיר יחייב. אז, רבנן יחייבו שני קלבונות, ורבי מאיר יחייב שני קלבונות (ואם נאמר שמודה למה שאומרים רבנן, אז יחייב ארבע קלבונות, ויהיה מחייב כבל איש מישראל שנותן שני קלבונות). אם כן, יש לומר שחולקים מה יתן בעד חברו (ולא לעצמו), אלא שאז היה אפשר להם לחלוק מה יתן כל יחיד בעד עצמו, שהוא אותו מחלקת. אולי אין הכי נמי, אבל רצה להודיע חידוש אחר, והוא דין נותן בעד חברו (שלא פטור אם הלווה).
אם נאמר כרב, ונאמר שנתן סלע שלם, אז יהיה פטור מדין ראשון, ויהיה חייב מדין שני, ויהיה פטור מדין שלישי, ולדין רביעי יהיה חייב רב לרבי מאיר. אז, לרבנן יחייב רק אחד בכלל ולרבי מאיר יחייב שלש בכלל, שהרי חייב קלבון לכל אחד, וגם קלבון למה שנתן מטבע שאינו נכון. אולי אפשר לומר שדנים בחיובים שיש בעד חברו, שאחד של רבנן הוא אף בעד חברו. ודחוק.
אם נאמר שנתן שקל ושקל, אז יהיה חייב שים מדין ראשון, ויהיה פטור מדין שני, ויהיה פטור מדין שלישי, ויהיה חייב בדין רביעי רק לפי רבי מאיר. אז, זה שווה לאילו לא סוברים כרב. אז, יכולים לומר כן, וכמה שכתבנו לעיל.
גם אומר גמרא שאם נותן סלע ונוטל שקל חייב שנים. יש חשבון אף בזה, אבל גמרא, באמת, עושה אותו חשבון.
אם לא נאמר כרב, אז לרבנן יחייב אחד (שלישי), ולרבי מאיר יחייב שנים (שלישי ורביעי). אם נאמר כרב, אז לרבנן יחייב שנים (שני ושלישי), ולרבי מאיר יחייב שלש (שני, שלישי, ורביעי).
גמרא מדייק שמשנה שלנו הוא כרבי מאיר, שמשמע שבכל זמן חייב קלבון שלו. צריך ביאור מהו "בכל זמן," שלכאורה, בא לרבות נותן סלע, שאז לא צריך לפי רבנן. אבל, קשה, שאז אף נוטל שקל, ואז ממילא חייב אחד. אולי הציור הוא שנתן סלע, ואמר שחצי השקל יהיה להקדש. ויש לדון, ששם משתמש בשולחני להקדש. יש לדון, אז, אם חייב בשלישי. נניח שלא חייב. עדיין, לפי רב, יחייב אחד (אין זה קשה, שאולי רב חולק על זה), ואז משנה יכול להיות כרבנן לפי רב.
** הא לתבוע -
הא לתבוע- יש לדון מהו הדיוק. אולי הוא ממה שרק אמר שאם נתנו…, ולא אמר שלא תובעים. גם יש לומר שהוא מה שמזכיר דין זה כלל, אחר שכבר יש לדייק שהם חייבים ממה שאמר שלא ממשכנים.
** נידרים -
היה קל לומר שאומר שאדם יכול לתת דמיהם אם רוצה. תירוצו הוא כעין זה. נראה שמה שלא רוצה לומר כן ממש הוא מפני שרישא דן בנדר להקריב עולה. אז, מסתבר לגמרא שאף סיפא דן בזה.
** אבל לא כהנים -
לכאורה, פוטר אותם מפני כבודם, כמו לעיל.
** ה. רמ"א לשקלים -
נראה שהוא לשיטתו, שסובר שהוא כדי לדמות למה שאמר ה' שצריך לתת לשקל.
ודע שלמי שלא אומר כר"מ, וגם לא אומר שצירך כדי שיהיה להקדש דמי שקל (שיש אומרים שצריך כדי לפרט וכדומה), צריך ביאור מהיכי תיתי שצריך לתת אותם.
** ה: כר"מ -
נמצא שגמ' מקשה ממה שסתם משנה כרבי מאיר. צריך ביאור, שהרי "סתם משנה רבי מאיר," כמו שאומר גמרא בסנהדרין (פו.). אולי ירושלמי חולק על זה. ותחשב.
באמת, צריך ביאור איך ליישב אותו כלל עם הכלל ש"הלכה כסתם משנה." אולי הם חולקים, ואז לא כל כך קשה לומר שאף ירולשמי חולק על כלל שסתם משנה הוא רבי מאיר. ותחשב.
* Footnotes
[fn:1] לכאורה, ההוכחה שאינו יותר מוקדם הוא שמשנה רק מזכיר זמן אחד. קרבן העדה גם מזכיר צד שקושיית גמרא הוא למה מזכירים בבבל. יש לדון מהיכי תיתי שמזכירים. ותחשב.
