** ב. אלא שהכפרים -
לשון "אלא" קצת מעניין, שמשמע שהאמור נכון, אבל לא כל כך. יש לומר שר"ל שכן עיקר דינו (ר"ל, זמן שבו מצווה יתקיים הכי טוב), אלא…. גם יש לומר שמקיים באלו ימים מפני יחסם ליום יד. תחשב. ועיין בשיח שי בפסחים כעין זה. אז, רק יד זמנו. ותחשב. כמו כן, יש לומר שר"ל שבא לזכור מה שקרה ביום יד, ולא מה שקרה ביום טו.
עיין ברש"י, שנראה שבא לבאר את זה. צריך ביאור מה אומר.
** לא פחות -
לשון "פחות" ו"יותר" קצת מעניין, שהיה לו לומר לא לפני כן ולא לאחר כן.
** כימים -
נראה שאולי יש חילוק יסודי בין שני הדרשות. דרשה ראשונה בא מקרא שאומר הזמן לחוג חג פורים. דרשה שניה בא מקרא שאומר סיבת פורים (הוא כימים אשר נחו). אולי, אז, קרא שני מרבה שיש ענין לא רק להיות כנגד יד, אלא אף כנגד יא (שאף זה נחשב כנגד הנס). אולי אינו כן לצד ראשון, שאולי לצד ראשון, החידוש הוא שיכול להיות יא כנגד יד. ותחשב. ואפשר לדחות את זה.
** זמן קהילה לכל -
ותחשב על זה. וצריך ביאור, שאינו כשר לשאר בני אדם.
** ב: ולאו ישראל -
צריך לחשוב מהו קושיה זה, שיש לומר שרק ישראלים מיוחדים נתחייבו. אולי קרא האומר ציווי אומר שהוא על ישראל. גם יש לומר שאומר שסיבת החיוב שייך להם, שאף להם היה הנס.
** ואמרי לה כדי -
מעניין שמצאנו בכמה מקומות שכדי נחלף עם רבא (כן אני חושב). אם היה אדם ששמו כדי (כחד צד ברש"י), אז אולי היה שום דמיון בין אותו איש לרבא. אם רק ר"ל "שום ת"ח.” צריך ביאור. אולי שם רבא (אבא) היה מצוי, ואז אחר, ששמו אבא, נשכח. ותחשב.
** פרזי פרזי -
ק"ק למה צריך שום קרא, שחילק בין פרזים לכרכים בפירוש במגילה (וכל דיניה נלמדו לעיל). אולי צריך להזכירו ללמד שאר דיני מקרא זה.
לולי רש"י, הוה מצי לומר שמדינה מיותר לחד דין דר’ יהושע, ויש עוד מיותר ללמד דין שני. לא נראה, ששני "העיר"ים הם, לכאורה, מיותרים. ותחשב.
** ג. עתיד -
לעיל, אמר רשאי. לכאורה, כאן ר"ל שאין נביאות שמחדש דבר מגיע לו. ממילא, כיון שאין לו נביאות, אסור לו, שנמצא שמשקר בנביאות.
** ישראל במעמדן -
לא הזכיר גמרא את זה לעיל; רק הזכיר כהן ולוי.
** תניא נמי הכי -
מעניין שאומר לשון ברייתא ממש, ולא מביא ברייתא. אולי למדו מרבו כן, ולא ידע שהוא ברייתא. אכתי ק"ק ל"ל הביא רבו את הברייתא. עיין במקום אחר שדיננו בזה (מסתמא, במרגנליא).
** מבטלים ת"ת -
וא"ת יוצאים ת"ת על ידי שמיעת מגילה. ויש לומר שחשש שלא יבואו כולם. ונראה אולי שלכן לא נחשב ביטול תורה דרבים, שרבים ילמדו בין כך ובין כך, ורק נחסרו יחידים). ותחשב.
** שם שמים -
משמע ששדים מצווים, ולא רוצים לעבור על מצוות. ויש לדון, שאולי כך נבראו (שזה אי אפשר להם). יש להעיר שמצאנו שכר לשידין (גטין) ושד שנתחייב ממון (חולין?).
** לבטלה -
ר"ל בשקר. ומעניין שמוצאים לשון שוא לבטלה (כמו שבועת שוא או שם ה’ לשוא בעשרת הדברות) ושקר (כמו עדות שוא). ותו"ת.
** ג: כרך איצטריכא -
צריך ביאור למה פשוט לגמרא שכרך צריך להיות עיר גדול.
** מהק’ תמידים -
אולי יש לחלק בין הק’ של בית המקדש לשל במה.
** צריך ביאור שאם
כל יחיד צריך לבטל, אם כן של ציבור בטל. לפי מש"כ לעיל, לא קשה, שרוב לא בטלים, אלא שומעים למגילה. גם יש לומר שלא מבטלים כי אם אי אין רבים לומדים.
** כרך -
יש לדון איך נדע (שבאים מזמן מוקדם).
** שחרב מעשרה -
אם כן, קשה למה צריך שני מאמרים. וצריך לומר שאמוראי חלוקים אמרו שניהם וחד דין הם. ויש לדון, שיש לומר שמחדש דין ישב.
** ד. ולטעמיך -
1. זה קשה על מש"א שאלפעל בנה אותו.
2. היה לו להקשות מזה (מצינו לטעמיך כעין זה בכ"מ).
** משה תיקן -
מק’ העולם שהרי צריך ללמוד שלושים יום קודם. יש לומר שהוה אמינא שביום טוב אין צריכים ללמוד, שכבר למד. ותחשב.
** ד: לא תקינו -
ר"ל, לא התירו בני אכה"ג. אולי מכוון לרכ"ג או ר"ל רבנן והוא מפני כן.
** ת"ש -
אכתי ק"ק ל"ל. וי"ל שזה קרוב לזמן הנס.
** שמספקים -
כיון שהגענו לזה, יש לומר שחוששים שלא יספקו בלי שכר זו.
** מיום הכניסה -
צ"ב ל"ל. יש לומר שחלק מן סיבת התקנה היה שיותר קל להם. ק’ אז ל"ל דוחים של ר"י כך.
** דלא אפשר -
לכאורה, חולקים איזה יותר נחשב דמיון חשוב.
** אף כאן -
צריך ביאור למה כופל על כל זה.
** ידחו -
יש לדון למה יותר טוב לדחותם יותר. גם יש לודן ל"ל אומרים שיג’ יותר טוב כיון שהוא זמן קהלה לכל.
** ה. בזמנו -
לכאורה, ר"ל בזמנו כבר יש פירסום, שיש הרבה קוראים אותו.
** וכי פשיטא -
ק"ק ל"ל נאמר שפשוט שהוא של יד.
** לא נהוג -
גם יש לומר שלא היו עמי הארץ, ולא היה בעיה זה. עיין שם בפסחים שכן אומר (שיש בעיה רק במקום של עמי הארץ).
** משום הכי מספקא -
ק"ק שנל’ ג"ש.
** ו. ריקנים -
ק"ק, שגמ’ אומר כן בסוף חגיגה על כל פושעי ישראל. ויש להעיר שיש גמרא שחולק (כן מצאתי, אבל שכחתי איפה. ציינתי שם.)
** פרקמטיא -
יש לדון אם לא מצליח במה שנוטל או בכל דבר. לצד ראשון, יש לדון מה אם רק לקח מעצמו. ויש לומר שצביעה לא יהני, ואז יצטרך ליקח. גם אפשר שאף יעשה הבגד יותר רע. גם יש לומר שאף שלא נקנס כל כך, אין חוששים ליחיד שבא, שהרי  יחיד מסתמא יקח. רק אם לוקח לרבים, יגזול, והרי הוא יפסיד, שנמצא שלא מוכר לזמן רב, ואחר כך יהיה יותר קשה למכור.
עיין ברש"י שכ’ כצד ראשון.
** רשע -
נמצא שידע יצחק שהיה עשו רשע.
** ו: ואילו סדר… לא מיירי -
נראה שר"ל שרק דן בדיני פורים. יש לדון אם לא ידע כן מתחילה, או סבר שהוא דין פורים. אם נאמר כשני, יש לדון אם מחדש שאינו דין פורים, או שרק דן בדיני פורים על פורים. ותחשב.
** דאין מעבירים -
ק"ק, אז, למה צריך קרא. אולי קרא מגלה שיכול. אז, יש לדון מה יהיה בלי הקרא. מגמרא לקמן נראה שהוה אמינא שצריך לקרוא בשניהם.
** ז. קבעוני -
לשון זה מעניין.
** ויוודע הדבר -
קשה, שזה רק אומר שהיה למרדכי רוח הקודש, אבל לא אומר שהיה לו רוח הקודש בכתיבת מגילה.
** כאומתו -
ואם תאמר איך ידע זה. ויש לומר ששמעה מהם. אם כן, היה אפשר לומר כן אף על פשטות הקרא. אולי יותר מסתבר לומר כן על זה, שיבואו לחלוק כל אחד על זה.
** שלחו -
ק"ק, שאולי שקרו.
** ז: בנו -
צריך ביאור למה אמר לשון רבים.
** קיימת -
לא הבנתי, שגמ’ רק הזכיר חד אדם. אולי חולק על מה שאמור לעיל.
** הא לענין -
היה אפשר לדחות שלא מנה את זה כיון שהוא תוצאה של דין כרת.[fn:1]
** ח. נדר -
יש להעיר שלשון "הרי עלי" נשמע יותר כשבוע. חושב אני שדן גמ’ בכעי"ז. במק"א.
** ונרצה לו -
יש לדון מהו ההוה אמינא:
1. שניהם חייבים באחריותו. הוה אמינא זה מעניין, שאמר, "זו.” יש להעיר שממה שמפרש במס’, לא נראה שזהו ההוה אמינא.
2. שניהם א"ח.
3. רק "זו" חייב באחריות. צריך ביאור למה נחשוב כן.
** עד שלא הגיע לשלוש -
יש לדון מה היה ההוה אמינא:
1. אולי לא היה הוה אמינא כל כך חזקה.
2. אולי הוה אמינא שראיית זיב הם סימנים. כיון שכן, אולי אם ראה שלוש, נמצא שלא היה סימן של ראיית שני פעמים.
3. יש לדון מהו הדיחוי לזה:
  1. אין ראיית זוב סימן. חסר מן הספר.
  2. אף שהוא סימן, בכלל שלוש יש סימן של שנים. ויש לדון.
  3. כיון שכבר נתחייב בקרבן, לא יפטור אותו תורה. יש לדון בזה, ראשון, שנמצא שלא היה לו סיבת החיוב, ושני מפני שלא נתחייב ממש עד שנטהר. ותו"ת.
** ט. מאי תרגום -
היה אפשר לומר שיש "טוטפות" לפי רבי עקיבה שהוא משני מילים שאומרים שנים. אולי תרגום משמע לשון ארמי בדווקא. ותו"ת.
גם יש להעיר שלפי השיטות שמצאנו לשונות שהם מאומות אחרות בתורה מפני שבאו מלשון הקודש, ובאו לאותם אומות בימי מגדל בבל, אינו תרגום. ותחשב.
** נושא בני אדם -
יש לדון לל"כ גמל. אולי אז לא היו צריכים לשקר.
** ט: לא חמד -
ממה שכל השינויים האלו הם בתורה, ולא בנביאים, משמע שרק כתבו לו תורה, שיש הרבה דברים בנביאים שהם מאד יותר קשים להבין כפי האמת מקראי הללו. ותו"ת.
** מ"ט דרשב"ג -
ק"ק לל"א שטעמו הוא כמו שאמר גמ’ לעיל (שתלמי המלך תרגם כך). נראה שהוא מפני שלשונו משמע שמודה לת"ק, אלא שלא אומר דינו בכל ציור, אלא רק ביוונית. אם כן, צריך לומר שחל מדין תורה, ולא מחמת דבר שנשתנה אחר כך. ותחשב.
** רבי היא -
נראה שהחילוק בין שני הלשונות הוא אם רבי פסק כן, וכתבו במשנה שלו, ושוב כשקבעו סתמות, קבעו כאותו משנה שלו, או אם מצאו סתם שכתוב מקצתו כזה ומקצתו כזה, וקבעו כמותו. זה אפשר אף אם נאמר כרש"י שרבי קבע את הסתמות כפי מה שנראה לו, והדיון הוא רק אם היה סובר כן רק בקביעות הסתמות או אף קודם לכן[fn:2]. ותחשב.
** י. ועוד תנן -
ואם תאמר איך שכח שני משניות. ויש לומר שידע שתנאי הוא. ואם תאמר אם כן למה חזר בו. ויש לומר שהבין לפסוק כסתם משניות או כשני סתמות.
** קידשה לשעתה -
יש לדון אם אומר שחלק ממה שמקדיש ארץ ישראל הוא בית המקדש[fn:3] או שה’ (או מי שקדש א"י[fn:4]) לא קידש א"י אלא לזמן שבהמ"ק שם. ותו"ת.
** קדושה ראשונה -
רק רואים כן על קדושת בית ראשון. כדי לסבור כר"י, צריך לומר כן אף על קדושת בית שני. אולי מניח גמרא שתלויים זה בזה.
** י: אף על פי שאין -
צריך ביאור מה רואים מזה, שדין זה שייך, אולי בזמן קדושת הבית, במקום שנפל כבר חומתו. ותחשב. אולי לשון "עכשיו" לא משמע כן. גם יש לומר שמדייק מן הדין, שממה שחומה נשאר, קדושת א"י נשאר. דחוק, שבוודאי קדושת שילה לא נשאר.
** ויהי בימי -
קצת צריך ביאור למה דנים בכל זה כאן (למה דנים בו כלל, ולמה כאן).
** לשון צער -
יש לדון אם זה אומר שנתן תורה מילה זה כדי להודיע שיהיה צער שבא, או שכל זמן ה’ אומר אותו מילה בעצבון (לא להודיע, אלא שכך עושה כשידבר על צער).
** אלא לאו ש"מ -
אם כן, אין צריכים מסורת שבידינו. אולי מסורת רק ר"ל שידעו שמי שחי לפני זמן ארוך אמר ראיה זה. ודחוק.
** יא. אחאב -
קשה, שלא מלך על יהודה. אולי אם היה רוצה לעשות להם כל דבר, היה יכול. זה נחשב מלכות עליהם. ויש לדון.
** רב מתנה אמר מהכא -
יש גו’ אמר, ויש שלא גו’. אם גו’, אומר שלא פתח מכאן, אלא אמר שראוי לפתוח מכאן. אם לא גו’, אומר שפתח מכאן. ואם תאמר אם ראוי ל"ל פתח. ויש לומר שכבר היה מנהג אחר. גם יש לומר שלא היה פותח כלל, שלא היה דורש.
** אחיו -
קצת צ"ב מהו החילוק בין אח של אדם ובן גילו בכעין זה. ותו"ת.
** יא: מאה ועשרים -
קשה, והא אחשורוש רק מלך על מאה, כמו שדרש גמ’ לעיל. ויש לומר ששם כשאומר, “מתחילה…" קאי על מה שהוסיף. אז, נמצא שמלך על מאה ועשרים ושבע. כן צריך לומר ג"כ לפי מש"א חז"ל שמלכה אסתר כנגד שני חיי שרה.
גם היה אפשר לומר שאף מאה היה כעשרים, שרק מלך רק זה לזמן, אבל אחר כך, כבש כל העולם, כמו שאומר קרא. סדר הקרא לא משמע כן.
** השתא -
ואם תאמר אם האמין שה’ שקר בזה, אולי שקר במה שאמר שיהיה אחר שבעים שנה. ויש לומר שרק חשש כיון שה’ אמר שיציל את בני ישראל. כיון שראה שה’ משקר, אין סיבה לו להניח שה’ יציל אותם. גם יש לומר שלמד מזה שגרם החטא. כיון שנדחה הזמן, אמר לעצמו, נדחה הגאולה.
** יב. וכי משוא -
לכאורה, זה היה קשה בין כך ובין כך.
** איהו בקרי -
נראה שיש בזה קצת פו"ן, שדן בביאה. ותו"ת.
** יב: יום השביעי -
אז, הדיון אינו שאז טוב לב, אלא ששל המלך טוב ביין, אבל של בני ישראל לא היה טוב ביין, שהם היו לומדים.
** כל איש… פשיטא -
יש לדון אם ר"ל שאז לא חשבו שהמלך היה כל כך חכם, או שאז הבינו שלא כן היה במלך, שלא היה מולך כל כך על ביתו, וזה היה גנאי למלך. רש"י משמע כצד ראשון.
** מכאן שההדיוט -
יש לדון אם לומד מכאן שבעת הצורך, יכול הדיוט לקפוץ, או שאומר שדרך הדיוט הוא לקפוץ (ואז הוא רע). ותו"ת.
** לא נשתייר -
עיין במה שמבאר רש"י. נראה בביאור זה שמוזר שירצה שיעשו כן בזמן מיוחד. אז, יחשבו שלא מקפיד על הזמן. אבל, כיון שרואים ששולח גזרות מוזרות, חשבו שהקפיד על הזמן, ואז שהו. ותו"ת.
** יג. דלא קטליה -
ק"ק לל"א ממה שבנימין הוליד את מרדכי.
** בימיו -
ועוד שהיה בזכותו.
** לבית -
העיר לי ע.י.ג. לפני זמן שאם כן, קשה למה לקח אותה אחשורוש.
** יג: לא יגרע מצדיק עיניו -
נראה שהיה אפשר לפרש שדורש מזה "עניו" (מ"עיניו"), אבל לא נראה שרש"י אומר כן. ותחשב. גם היה אפשר לומר שנוטל שכר על מה שאין בני אדם נותנים עיניהם בו. ותו"ת.
** דם נדה לחכמים -
יש לדון איזה נפק"מ יהיה, שהיתה כבר מסוכנת לבעול. ויש לומר שצריך כדי שתשוב למרדכי. אף אם לא תשוב מיד, צריכה לפתח נדותה.
** יד. שבחו"ל -
ק"ק, שזה יפריך הקל וחומר. צריך לומר שמה שאי אפשר לומר הלל הוא בעיה בהלל, ולא בשירה (ומניחים כן כיון שהקל וחומר נראה נכון).
** יד: נשים רחמניות -
קשה מה לנו בזה, שבין כך ובין כך תאמר מה שה’ אומרת לו לומר. יש לומר שאז יהיה יותר סיבה לה’ שלא לומר דבר רע, כיון שהוא מצער נביאה. דחוק, שנראה קטן, ועוד שצריכים להניח שאילו לא גילה לה נבואה זה, אלא לנביא אחר, לא היתה שומעת. אולי לא היתה מרגשת כל כך. ויל"ד.
** בני בניו -
ר"ל בני בנותיו. ונראה שאף בניו השני קאי על בני בנותיו. אז, אולי אינו כל כך קשה. ותו"ת.
** בבית אל -
קשה ל"ל אומרים שלקח אותו קרקע אחר שנאבד חיל סנחרב.
** טו. רשע בן רשע -
נראה כעין מה שאומר גמרא חולין שתורה אומר מפרש המעוטים, ולא המרובים. ממה שמפרשים מקצת שמות,
** טו: וכן אתה מוצא -
לכאורה, לא רק קאי על שיעור של ששים. יש לדון אם הוא חלק מן הברייתא. ותו"ת. עיין ברש"י שאומר שקאי על ששים.
** טז: רמז -
יש לדון מהו תרוץ זה:
1. היה צורך לייתור בגדים, ודחה הבעיה.
2. היה צורך, וכיון שהכירו אחים בו (מניח שהכירו בו), ידעו שרק בא לרמז לו, ולא מחמת אהבה יתירה.
3. נתן חמש שלא היו, בין כולם, יותר טובים. ואם תאמר א"כ למה נתנם. לזה, משיב שהיה מרמז. חושב אני שכן אומר רש"י (שבת).
** מה עשרה -
לכאורה, זה סותר מה שאמר מקודם, והוא שאמר שמה’ היה הדבר. אז, זה אומרש בעצם, אולי, היו יכולים, אלא שלא היה ה’ רוצה בזה. אם כן, אם אינו כן גביהם, אולי יוכל יוסף להרוג אותם. ותחשב.
נראה שאולי אומר שיש סיבה ראשונה, ואף אם לא היה אומר כן, הרי יש סיבה שניה. אז, סיבה ראשונה בא כשאין סיבה ראשונה, ואז אין בעיה במה שסותר אותו.
** תעלא -
ק"ק לל"א שהיה נחשב כן כיון שהיה אח הקטן.
** וי"ו -
לא הבנתי, שמרשי נראה שדין זה הוא שצריך שיהיו כולם בזקיפה אחת. אם כן, קשה למה מזכיר וי"ו של ויזתא בדווקא.
** כאמיתה -
יש לדון מה זה אומר:
1. כמו תורה, שהיא אמת.
2. כמו ההלכה למשה מסיני שנאמר בתורה[fn:5]. אולי לשון אמת מרמז להלכה למשה מסיני. מסתמא, זה מפני שאי אפשר לדון בו לומר שאולי אינו נכון, אלא בוודאי הוא נכון.[fn:6]
** יז: מה ראו -
לכאורה, השואל יודע התשובה, שאי לאו הכי, קשה איך ידע מתי ישאל על פי מה בא לפניו ומתי שואל על פי מנין. ותו"ת.
** יח. חלגלוגית -
יל"ד ל"ל שאלו את רבי, שהוא כ’ המשניות ויידע. ויש לדון. אולי רק סדר אותם משניות, ואף ה וא לא ידע מהו.[fn:7]
* Footnotes
[fn:1] ויש להעיר שהיה אפשר לדחות כן, אולי, אף גבי פרשיות לעיל.
[fn:2] אם אם כתב משנה על פי שיטתו המוקדם. ותו"ת.
[fn:3] אם כן, אי אפשר החולק יסבור שהמקדש של א"י לא תלוי בבית המקדש, שהרי לא קידש לפני כן. יש לדחות שסובר שלא קדש ה’ עד אז. גם יש לומר שמה שהיה בית המקדש הוא המקדש את ארץ ישראל. גם יש לומר שמה שעומד להיות בית המקדש השלישי הוא המקדש ארץ ישראל (וצריך לומר שאחר שילה לא היה עומד להיות בית המקדש, או שאותו בית המקדש שהיה עומד לו לא היה קדוש די לקדש).
[fn:4] אולי אברהם
[fn:5] עיין ברש"י, שאפשר שקצת משמע כן.
[fn:6] ויש לציין לגמרא ב"מ שאומר ש"באמת" הלכה היא. לא נראה, ששם לכאורה, רק אומר שההלכה כן, ולא שהוא הלכה למשה מסיני. עיין בב"מ ס. ועיין.
[fn:7] אולי לא רצו לשאול לו כיון שאין לשאול על מסכתא אחר, כומ שאומר בשבת ובמק"א.
