** ב. סתימתאה -
ויש מפרשים- לא ר"ל שסתם משניות כמותו (שכ’ "תלמידיו"), אלא שאף ברייתא וכדומה כמותו. קצת צריך ביאור למה יזכיר גמרא את זה בענין בתם משנה כמותו.
** בזמן -
נמצא שר"י איתותב רק לשיטתו, שאי אין מתנימין ר"ע, יש לומר שלפני זמן הוא, ומשנה סובר כרבי יהודה.
** ב: זכירה -
קריאת- משמע שהמצווה הוא לקרוא ולא לשמוע. יש להעיר שלשון זכירה משמע שהענין הוא שמיעה, שהוא גורם זכירה.
** פרזי -
כופל את דיבורו כאן. גם יש להעיר שכשאומר "אלא אם כן קיבל,” לא קאי אומר ציור שיכול אדם לדון גזירה שווה מעצמו, שאין זה מעצמו, אלא אומר ציור שיכול לדון גזירה שווה. ותו"ת.
** ג. דאינהו -
מעניין, שאומר שהיה נביא, אבל לא נשתלח. אולי ראייה זה היה נבואה.
** ג: ת"ת דיחיד -
יש לדון אם למעשה מבטלים ת"ת דרבים למגילה. מרש"י נראה שלא מבטלים. כן נראה, שאף שאין לנו מקור שלא לבטל, אין לנו מקור לבטל. אז, לכאורה, נניח שמצווה דאו’ עדיף. ותחשב.
** את לא תעשה -
לא נראה כן מגמרא שם, אלא נראה שקאי על דינים דרבנן (והלאו הוא לא תסור). ע"ש.
** שישב -
צריך ביאור למה אמרו רק לענין זה, שלכאורה, הוא אף למגילה, שנלמד ממנו. אולי אמר דין שאף רבי יהושע יאמר. ותו"ת.
** ד. שואלים ודורשים -
אגרת פורים- לכאורה, זה המגלה. אם כן, משמע שלא דנים בהלכות שלו, אלא במגילה.
** ולשנותה -
היה אפשר לומר כן אף אם היה בארמי, שאז היה אומר, “למתנייה.” ותחשב.
** ולשנותה -
אף שאין קוראים ביום זעקתם, צריך לומר שיש שייכות (וכן רואים בחד פירוש של "יום כניסה" (רא"ש?) שפירש שהיה יום שבו התפללו. ותו"ת.
** סבור מינה - למיתני -
אם למדו בלשון הקודש, צריך ביאור למה כתבו ש"ס (ובפרט אלו, שכ’, לכאורה, ירושלמי, בארמי. ותו"ת. אולי רצו שיבינו המון העם זה ולא זה. ודחוק.
ק"ק מה עשו קודם שהיה להם משנה. ויש לומר שהוצרכו לחזור על ההלכות שידעו.
** יזמרך -
יש לציין לגמ’ ערכין (י:?) שאומר שקריאת מגילה הוא הלל של פורים.
** ה. ורב אסי -
שאין איסור- משמע שלא מקיים כלל.
** וחגיגה -
למחר- הוא אחר יו"ט קצת, שק’ אחת הוא. ויש לדון אם צריך להיות אחר יום טוב או באותו יום בחדש. ותחשב.
** ה: טובים -
ואם תאמר טוב השני, ולא השנים. ויש לומר שהשני לא ידע שאר הדינים. ויש לדון אם זה קשה בכלל, שפשוט שהכל משכחים, וצריך שני, וזה היה פעם ששנים טובים, שאותו דין ששנים טובים היה נראה, שאמר זה מה ששכח חברו. ותחשב.
** ו: סייעתא -
משמע שעדיין לא ימצא אם לא מיגע. יש לדון, שאולי מה שרש"י אומר הוא הכי מחודש. ותו"ת.
** ט: כהן המשמש -
כגון שאירע- משמע שאין צריך להיות כן, אלא זה רק ציור. יש לדון איזה הוא ציור שאינו כן. אולי אם הוא רחוק, בית דין עושים כן. צריך להגדיר מילת "פסול" לבאר למה אין ריחוקו נחשב פסול. ותו"ת.
** י: פתח -
יש לדון למה קורא לו אגרת פורים, ולא מגילה, כלשון המשנה.
** יג: כתלי -
עיין בתוס’, שחולק ע"ז.
** יד. חוץ ממקרא -
אבל בזמן מרדכי- יש להעיר שהיו מרדכי ואסתר גם כן נביאים. אולי לא אומר מרדכי כיון שהוא כבר, אולי, מלאכי.
יש להעיר גם כן שהיה מרדכי עדיין קיים בזמן בית דין שני (עיין מנחות בדיון איזה יין ותבואה כשר).
** טו. ועכשיו -
מכאן ואילך- קשה למה תהיה מדעתו יותר מאותו פעם אחת שהוצרכה. גם צריך ביאור ל"ל נחשב אונס כיון שהוצרכה כן להציל בני ישראל. אם נאמר שאין ג"ע מותר להציל כל בני ישראל, אז קשה למה עשה אותה. צריך לומר שבכעין זה נדחה האיסור, ועדיין יש איסור לבעל. זה מעניין. צריך ביאור מהו החילוק בין זה לאונס.
** טו: וכי גזרי -
קשה, שאם כן, למה הוצרכו לבקש עוד גזרה מאת אחשורוש, שכיון שמת המן, הרי בטל.
** טז. שמשי -
כיון שהיה שונא יהודים, קשה למה כתב מתחילה. אולי לא היה הסופר היחידי, ואחר, שלא שנא את היהודים, כתב אותו. גם יש לומר שאז היה מלך זוכר אותו, ואז היה חש מפניו. עכשיו, כבר שכח המלך.
