פרק ראשון[fn:1]
משנה א[fn:2]
מָבוֹי[fn:3] שֶׁהוּא גָבוֹהַּ לְמַעְלָה מֵעֶשְׂרִים אַמָּה[fn:4][fn:5], יְמַעֵט[fn:6][fn:7][fn:8]. רַבִּי יְהוּדָה אוֹמֵר, אֵינוֹ צָרִיךְ[fn:9]. וְהָרָחָב מֵעֶשֶׂר אַמּוֹת[fn:10], יְמַעֵט[fn:11]. וְאִם יֶשׁ לוֹ צוּרַת הַפֶּתַח[fn:12], אַף עַל פִּי שֶׁהוּא רָחָב מֵעֶשֶׂר אַמּוֹת[fn:13], אֵין צָרִיךְ לְמַעֵט[fn:14][fn:15]:
משנה ב[fn:16]
הֶכְשֵׁר מָבוֹי[fn:17], בֵּית שַׁמַּאי אוֹמְרִים, לֶחִי וְקוֹרָה, וּבֵית הִלֵּל אוֹמְרִים, לֶחִי אוֹ קוֹרָה. רַבִּי אֱלִיעֶזֶר אוֹמֵר, לְחָיַיִן. מִשּׁוּם רַבִּי יִשְׁמָעֵאל אָמַר תַּלְמִיד אֶחָד לִפְנֵי רַבִּי עֲקִיבָא, לֹא נֶחְלְקוּ בֵּית שַׁמַּאי וּבֵית הִלֵּל עַל מָבוֹי שֶׁהוּא פָחוֹת מֵאַרְבַּע אַמּוֹת, שֶׁהוּא אוֹ בְלֶחִי אוֹ בְקוֹרָה. עַל מַה נֶּחְלְקוּ, עַל רָחָב מֵאַרְבַּע אַמּוֹת וְעַד עֶשֶׂר, שֶׁבֵּית שַׁמַּאי אוֹמְרִים, לֶחִי וְקוֹרָה, וּבֵית הִלֵּל אוֹמְרִים, אוֹ לֶחִי אוֹ קוֹרָה. אָמַר רַבִּי עֲקִיבָא, עַל זֶה וְעַל זֶה נֶחֱלָקוּ:
משנה ג
הַקּוֹרָה שֶׁאָמְרוּ, רְחָבָה כְּדֵי לְקַבֵּל אָרִיחַ. וְאָרִיחַ, חֲצִי לְבֵנָה שֶׁל שְׁלֹשָׁה טְפָחִים. דַּיָּה לַקּוֹרָה שֶׁתְּהֵא רְחָבָה טֶפַח, כְּדֵי לְקַבֵּל אָרִיחַ לְאָרְכּוֹ {ו}:
משנה ד
רְחָבָה, כְּדֵי לְקַבֵּל אָרִיחַ, וּבְרִיאָה, כְּדֵי לְקַבֵּל אָרִיחַ. רַבִּי יְהוּדָה אוֹמֵר, רְחָבָה אַף עַל פִּי שֶׁאֵין בְּרִיאָה:
משנה ה
הָיְתָה שֶׁל קַשׁ אוֹ שֶׁל קָנִים, רוֹאִין אוֹתָהּ כְּאִלּוּ הִיא שֶׁל מַתֶּכֶת. עֲקֻמָּה, רוֹאִין אוֹתָהּ כְּאִלּוּ הִיא פְשׁוּטָה. עֲגֻלָּה, רוֹאִין אוֹתָהּ כְּאִלּוּ הִיא מְרֻבַּעַת. כֹּל שֶׁיֵּשׁ בְּהֶקֵּפוֹ שְׁלֹשָׁה טְפָחִים, יֶשׁ בּוֹ רֹחַב טָפַח:
משנה ו
לְחָיַיִן שֶׁאָמְרוּ, גָּבְהָן עֲשָׂרָה טְפָחִים, וְרָחְבָּן וְעָבְיָן כָּל שֶׁהוּא. רַבִּי יוֹסֵי אוֹמֵר, רָחְבָּן שְׁלֹשָׁה טְפָחִים:
משנה ז
בַּכֹּל עוֹשִׂין לְחָיַיִן, אֲפִלּוּ בְדָבָר שֶׁיֶּשׁ בּוֹ רוּחַ חַיִּים {י}. וְרַבִּי יוֹסֵי אוֹסֵר. וּמְטַמֵּא מִשּׁוּם גּוֹלֵל, וְרַבִּי מֵאִיר מְטַהֵר. וְכוֹתְבִין עָלָיו גִּטֵּי נָשִׁים, וְרַבִּי יוֹסֵי הַגְּלִילִי פוֹסֵל:
משנה ח
שַׁיָּרָא {יד} שֶׁחָנְתָה בְּבִקְעָה וְהִקִּיפוּהָ {טו} בִכְלֵי בְהֵמָה, מְטַלְטְלִין בְּתוֹכָהּ, וּבִלְבַד שֶׁיְּהֵא גָדֵר גָּבוֹהַּ עֲשָׂרָה טְפָחִים {טז}, וְלֹא יִהְיוּ פְרָצוֹת יְתֵרוֹת עַל הַבִּנְיָן. כָּל פִּרְצָה שֶׁהִיא כְעֶשֶׂר אַמּוֹת, מֻתֶּרֶת, מִפְּנֵי שֶׁהִיא כְפֶתַח. יָתֵר מִכָּאן, אָסוּר:
משנה ט
מַקִּיפִין שְׁלֹשָׁה חֲבָלִים, זֶה לְמַעְלָה מִזֶּה וְזֶה לְמַעְלָה מִזֶּה, וּבִלְבַד שֶׁלֹּא יְהֵא בֵּין חֶבֶל לַחֲבֵרוֹ שְׁלֹשָׁה טְפָחִים. שִׁעוּר חֲבָלִים וְעָבְיָן, יָתֵר עַל טֶפַח, כְּדֵי שֶׁיְּהֵא הַכֹּל עֲשָׂרָה טְפָחִים:
משנה י
מַקִּיפִין בְּקָנִים, וּבִלְבַד שֶׁלֹּא יְהֵא בֵין קָנֶה לַחֲבֵרוֹ שְׁלֹשָׁה טְפָחִים. בְּשַׁיָּרָא דִבְּרוּ, דִּבְרֵי רַבִּי יְהוּדָה. וַחֲכָמִים אוֹמְרִים, לֹא דִבְּרוּ בְשַׁיָּרָא אֶלָּא בַהֹוֶה. כָּל מְחִצָּה שֶׁאֵינָהּ שֶׁל שְׁתִי וְשֶׁל עֵרֶב, אֵינָהּ מְחִצָּה, דִּבְרֵי רַבִּי יוֹסֵי בַּר רַבִּי יְהוּדָה. וַחֲכָמִים אוֹמְרִים, אֶחָד מִשְּׁנֵי דְבָרִים. אַרְבָּעָה דְבָרִים פָּטְרוּ בַמַּחֲנֶה, מְבִיאִין עֵצִים מִכָּל מָקוֹם, וּפְטוּרִים מֵרְחִיצַת יָדַיִם, וּמִדְּמַאי {יח}, וּמִלְּעָרֵב:
--------------------------------------------------------------------------------
פרק ב
--------------------------------------------------------------------------------
פרק ב - משנה א
עוֹשִׂין פַּסִּין לַבֵּירָאוֹת אַרְבָּעָה דְיוּמְדִין, נִרְאִין כִּשְׁמֹנָה, דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי מֵאִיר אוֹמֵר, שְׁמֹנָה, נִרְאִין כִּשְׁנֵים עָשָׂר, אַרְבָּעָה דְיוּמְדִין וְאַרְבָּעָה פְשׁוּטִין. גָּבְהָן עֲשָׂרָה טְפָחִים {א}, וְרָחְבָּן שִׁשָּׁה, וְעָבְיָן כָּל שֶׁהוּא, וּבֵינֵיהֶן כִּמְלֹא שְׁתֵּי רְבָקוֹת שֶׁל שָׁלֹשׁ שָׁלֹשׁ בָּקָר, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, שֶׁל אַרְבַּע אַרְבַּע, קְשׁוּרוֹת {ב} וְלֹא מֻתָּרוֹת, אַחַת נִכְנֶסֶת וְאַחַת יוֹצֵאת:
--------------------------------------------------------------------------------
פרק ב - משנה ב
מֻתָּר לְהַקְרִיב לַבְּאֵר, וּבִלְבַד שֶׁתְּהֵא פָרָה רֹאשָׁהּ וְרֻבָּהּ בִּפְנִים וְשׁוֹתָה. מֻתָּר לְהַרְחִיק כָּל שֶׁהוּא, וּבִלְבַד שֶׁיַּרְבֶּה בְּפַסִּין:
--------------------------------------------------------------------------------
פרק ב - משנה ג
רַבִּי יְהוּדָה אוֹמֵר, עַד בֵּית סָאתָיִם. אָמְרוּ לוֹ, לֹא אָמְרוּ בֵית סָאתַיִם אֶלָּא לְגִנָּה וּלְקַרְפֵּף, אֲבָל אִם הָיָה דִּיר אוֹ סַחַר {ה}, אוֹ מֻקְצֶה אוֹ חָצֵר, אֲפִלּוּ בֵית חֲמֵשֶׁת כּוֹרִין, אֲפִלּוּ בֵית עֲשָׂרָה כּוֹרִין, מֻתָּר. וּמֻתָּר לְהַרְחִיק כָּל שֶׁהוּא, וּבִלְבַד שֶׁיַּרְבֶּה בְּפַסִּין:
--------------------------------------------------------------------------------
פרק ב - משנה ד
רַבִּי יְהוּדָה אוֹמֵר, אִם הָיְתָה דֶרֶךְ הָרַבִּים מַפְסַקְתָּן, יְסַלְּקֶנָּה לַצְּדָדִין. וַחֲכָמִים אוֹמְרִים, אֵינוֹ צָרִיךְ. אֶחָד בּוֹר {ח} הָרַבִּים, וּבְאֵר הָרַבִּים, וּבְאֵר הַיָּחִיד, עוֹשִׂין לָהֶן פַּסִּין, אֲבָל לְבוֹר הַיָּחִיד עוֹשִׂין לוֹ מְחִצָּה גָבוֹהַּ עֲשָׂרָה טְפָחִים, דִּבְרֵי רַבִּי עֲקִיבָא. רַבִּי יְהוּדָה בֶן בָּבָא אוֹמֵר, אֵין עוֹשִׂין פַּסִּין אֶלָּא לִבְאֵר הָרַבִּים בִּלְבַד, וְלַשְּׁאָר עוֹשִׂין חֲגוֹרָה {יא} גָבוֹהַּ עֲשָׂרָה טְפָחִים:
--------------------------------------------------------------------------------
פרק ב - משנה ה
וְעוֹד אָמַר רַבִּי יְהוּדָה בֶן בָּבָא, הַגִּנָּה וְהַקַּרְפֵּף שֶׁהֵן שִׁבְעִים אַמָּה וְשִׁירַיִם עַל שִׁבְעִים אַמָּה וְשִׁירַיִם, מֻקֶּפֶת גָּדֵר גָּבוֹהַּ עֲשָׂרָה טְפָחִים, מְטַלְטְלִין בְּתוֹכָהּ, וּבִלְבַד שֶׁיְּהֵא בָהּ שׁוֹמֵירָה {יג} אוֹ בֵית דִּירָה, אוֹ שֶׁתְּהֵא סְמוּכָה לָעִיר. רַבִּי יְהוּדָה אוֹמֵר, אֲפִלּוּ אֵין בָּהּ אֶלָּא בוֹר {יד} וְשִׁיחַ וּמְעָרָה, מְטַלְטְלִין בְּתוֹכָהּ. רַבִּי עֲקִיבָא אוֹמֵר, אֲפִלּוּ אֵין בָּהּ אַחַת מִכָּל אֵלּוּ, מְטַלְטְלִין בְּתוֹכָהּ, וּבִלְבַד שֶׁיְּהֵא בָהּ שִׁבְעִים אַמָּה וְשִׁירַיִם עַל שִׁבְעִים אַמָּה וְשִׁירָיִם. רַבִּי אֱלִיעֶזֶר אוֹמֵר, אִם הָיָה אָרְכָּהּ יָתֵר עַל רָחְבָּהּ אֲפִלּוּ אַמָּה אַחַת, אֵין מְטַלְטְלִין בְּתוֹכָהּ. רַבִּי יוֹסֵי אוֹמֵר, אֲפִלּוּ אָרְכָּהּ פִּי שְׁנַיִם בְּרָחְבָּהּ, מְטַלְטְלִין בְּתוֹכָהּ:
--------------------------------------------------------------------------------
פרק ב - משנה ו
אָמַר רַבִּי אִלָּעִאי, שָׁמַעְתִּי מֵרַבִּי אֱלִיעֶזֶר, וַאֲפִלּוּ הִיא כְּבֵית כּוֹר {טז}. וְכֵן שָׁמַעְתִּי מִמֶּנּוּ, אַנְשֵׁי חָצֵר שֶׁשָּׁכַח אַחַד מֵהֶן וְלֹא עֵרֵב, בֵּיתוֹ אָסוּר {יח} מִלְּהַכְנִיס וּלְהוֹצִיא, לוֹ, אֲבָל לָהֶם מֻתָּר. וְכֵן שָׁמַעְתִּי מִמֶּנּוּ, שֶׁיּוֹצְאִין בְּעַקְרַבְנִים בְּפֶסַח. וְחִזַּרְתִּי עַל כָּל תַּלְמִידָיו וּבִקַּשְׁתִּי לִי חָבֵר, וְלֹא מָצָאתִי:
--------------------------------------------------------------------------------
פרק ג
--------------------------------------------------------------------------------
פרק ג - משנה א
בַּכֹּל מְעָרְבִין וּמִשְׁתַּתְּפִים, חוּץ {ב} מִן הַמַּיִם וּמִן הַמֶּלַח. וְהַכֹּל נִקָּח בְּכֶסֶף מַעֲשֵׂר, חוּץ מִן הַמַּיִם וּמִן הַמֶּלַח. הַנּוֹדֵר מִן הַמָּזוֹן, מֻתָּר בְּמַיִם וּבְמֶלַח. מְעָרְבִין לְנָזִיר בְּיַיִן וּלְיִשְׂרָאֵל בִּתְרוּמָה. סוּמְכוֹס אוֹמֵר, בְּחֻלִּין. וּלְכֹהֵן בְּבֵית הַפְּרָס. רַבִּי יְהוּדָה אוֹמֵר, אֲפִלּוּ בְּבֵית הַקְּבָרוֹת, מִפְּנֵי שֶׁיָּכוֹל לֵילֵךְ לָחוֹץ וְלֶאֱכֹל:
--------------------------------------------------------------------------------
פרק ג - משנה ב
מְעָרְבִין בִּדְמַאי, וּבְמַעֲשֵׂר רִאשׁוֹן שֶׁנִטְּלָה תְרוּמָתוֹ, וּבְמַעֲשֵׂר שֵׁנִי וְהֶקְדֵּשׁ שֶׁנִּפְדּוּ. וְהַכֹּהֲנִים, בְּחַלָּה וּבִתְרוּמָה {ו}. אֲבָל לֹא בְטֶבֶל, וְלֹא בְמַעֲשֵׂר רִאשׁוֹן שֶׁלֹּא נִטְּלָה תְרוּמָתוֹ, וְלֹא בְמַעֲשֵׂר שֵׁנִי וְהֶקְדֵּשׁ שֶׁלֹּא נִפְדּוּ. הַשּׁוֹלֵחַ עֵרוּבוֹ בְּיַד חֵרֵשׁ, שׁוֹטֶה וְקָטָן, אוֹ בְיַד מִי שֶׁאֵינוֹ מוֹדֶה בָעֵרוּב, אֵינוֹ עֵרוּב. וְאִם אָמַר לְאַחֵר לְקַבְּלוֹ מִמֶּנּוּ, הֲרֵי זֶה עֵרוּב:
--------------------------------------------------------------------------------
פרק ג - משנה ג
נְתָנוֹ בְאִילָן, לְמַעְלָה מֵעֲשָׂרָה טְפָחִים, אֵין עֵרוּבוֹ עֵרוּב. לְמַטָּה מֵעֲשָׂרָה טְפָחִים, עֵרוּבוֹ עֵרוּב. נְתָנוֹ בְּבוֹר, אֲפִלּוּ עָמוֹק מֵאָה אַמָּה, עֵרוּבוֹ עֵרוּב. נְתָנוֹ בְרֹאשׁ הַקָּנֶה אוֹ בְרֹאשׁ הַקֻּנְדָּס בִּזְמַן שֶׁהוּא תָלוּשׁ וְנָעוּץ, אֲפִלּוּ גָבוֹהַּ מֵאָה אַמָּה, הֲרֵי זֶה עֵרוּב. נְתָנוֹ בְמִגְדָּל וְאָבַד הַמַּפְתֵּחַ, הֲרֵי זֶה עֵרוּב. רַבִּי אֱלִיעֶזֶר אוֹמֵר, אִם אֵינוֹ יוֹדֵעַ שֶׁהַמַּפְתֵּחַ בִּמְקוֹמוֹ, אֵינוֹ עֵרוּב:
--------------------------------------------------------------------------------
פרק ג - משנה ד
נִתְגַּלְגֵּל חוּץ לַתְּחוּם {י}, וְנָפַל עָלָיו גַּל, אוֹ נִשְׂרַף, אוֹ תְרוּמָה וְנִטְמֵאת, מִבְּעוֹד יוֹם, אֵינוֹ עֵרוּב, מִשֶּׁחֲשֵׁכָה, הֲרֵי זֶה עֵרוּב. אִם סָפֵק, רַבִּי מֵאִיר וְרַבִּי יְהוּדָה אוֹמְרִים, הֲרֵי זֶה חַמָּר גַּמָּל {יג}. רַבִּי יוֹסֵי וְרַבִּי שִׁמְעוֹן אוֹמְרִים, סְפֵק עֵרוּב, כָּשֵׁר. אָמַר רַבִּי יוֹסֵי, אַבְטוֹלְמוֹס הֵעִיד מִשּׁוּם חֲמִשָּׁה זְקֵנִים עַל סְפֵק עֵרוּב שֶׁכָּשֵׁר:
--------------------------------------------------------------------------------
פרק ג - משנה ה
מַתְנֶה אָדָם עַל עֵרוּבוֹ וְאוֹמֵר, אִם בָּאוּ גוֹיִים מִן הַמִּזְרָח, עֵרוּבִי לַמַּעֲרָב. מִן הַמַּעֲרָב, עֵרוּבִי לַמִּזְרָח. אִם בָּאוּ מִכָּאן וּמִכָּאן, לִמְקוֹם שֶׁאֶרְצֶה אֵלֵךְ. לֹא בָאוּ לֹא מִכָּאן וְלֹא מִכָּאן, הֲרֵינִי כִבְנֵי עִירִי. אִם בָּא חָכָם מִן הַמִּזְרָח, עֵרוּבִי לַמִּזְרָח. מִן הַמַּעֲרָב, עֵרוּבִי לַמַּעֲרָב. בָּא לְכָאן וּלְכָאן, לִמְקוֹם שֶׁאֶרְצֶה אֵלֵךְ. לֹא לְכָאן וְלֹא לְכָאן, הֲרֵינִי כִבְנֵי עִירִי. רַבִּי יְהוּדָה אוֹמֵר, אִם הָיָה אֶחָד מֵהֶן רַבּוֹ, הוֹלֵךְ אֵצֶל רַבּוֹ, וְאִם הָיוּ שְׁנֵיהֶם רַבּוֹתָיו {טז}, לִמְקוֹם שֶׁיִּרְצֶה יֵלֵךְ:
--------------------------------------------------------------------------------
פרק ג - משנה ו
רַבִּי אֱלִיעֶזֶר אוֹמֵר, יוֹם טוֹב הַסָּמוּךְ לְשַׁבָּת, בֵּין מִלְּפָנֶיהָ וּבֵין מִלְּאַחֲרֶיהָ, מְעָרֵב אָדָם שְׁנֵי עֵרוּבִין {יז} וְאוֹמֵר, עֵרוּבִי הָרִאשׁוֹן לַמִּזְרָח, וְהַשֵּׁנִי לַמַּעֲרָב. הָרִאשׁוֹן לַמַּעֲרָב, וְהַשֵּׁנִי לַמִּזְרָח. עֵרוּבִי הָרִאשׁוֹן, וְהַשֵּׁנִי כִּבְנֵי עִירִי. עֵרוּבִי הַשֵּׁנִי, וְהָרִאשׁוֹן כִּבְנֵי עִירִי. וַחֲכָמִים אוֹמְרִים, מְעָרֵב לְרוּחַ אַחַת, אוֹ אֵינוֹ מְעָרֵב כָּל עִקָּר. אוֹ מְעָרֵב לִשְׁנֵי יָמִים, אוֹ אֵינוֹ מְעָרֵב כָּל עִקָּר. כֵּיצַד יַעֲשֶׂה. מוֹלִיכוֹ בָרִאשׁוֹן, וּמַחְשִׁיךְ עָלָיו וְנוֹטְלוֹ וּבָא לוֹ. בַּשֵּׁנִי מַחְשִׁיךְ עָלָיו וְאוֹכְלוֹ. וְנִמְצָא מִשְׂתַּכֵּר {כא} בַּהֲלִיכָתוֹ וּמִשְׂתַּכֵּר בְּעֵרוּבוֹ. נֶאֱכַל בָּרִאשׁוֹן, עֵרוּבוֹ לָרִאשׁוֹן וְאֵינוֹ עֵרוּב לַשֵּׁנִי. אָמַר לָהֶם רַבִּי אֱלִיעֶזֶר, מוֹדִים אַתֶּם לִי שֶׁהֵן שְׁתֵּי קְדֻשּׁוֹת:
--------------------------------------------------------------------------------
פרק ג - משנה ז
רַבִּי יְהוּדָה אוֹמֵר, רֹאשׁ הַשָּׁנָה, שֶׁהָיָה יָרֵא שֶׁמָּא תִּתְעַבֵּר, מְעָרֵב אָדָם שְׁנֵי עֵרוּבִין וְאוֹמֵר, עֵרוּבִי בָרִאשׁוֹן לַמִּזְרָח וּבַשֵּׁנִי לַמַּעֲרָב, בָּרִאשׁוֹן לַמַּעֲרָב וּבַשֵּׁנִי לַמִּזְרָח. עֵרוּבִי בָּרִאשׁוֹן, וּבַשֵּׁנִי כִּבְנֵי עִירִי. עֵרוּבִי בַּשֵּׁנִי, וּבָרִאשׁוֹן כִּבְנֵי עִירִי. וְלֹא הוֹדוּ לוֹ חֲכָמִים:
--------------------------------------------------------------------------------
פרק ג - משנה ח
וְעוֹד אָמַר רַבִּי יְהוּדָה {כג}, מַתְנֶה אָדָם עַל הַכַּלְכָּלָה בְּיוֹם טוֹב רִאשׁוֹן וְאוֹכְלָהּ בַּשֵּׁנִי. וְכֵן בֵּיצָה שֶׁנּוֹלְדָה בָרִאשׁוֹן, תֵּאָכֵל בַּשֵּׁנִי. וְלֹא הוֹדוּ לוֹ חֲכָמִים:
--------------------------------------------------------------------------------
פרק ג - משנה ט
רַבִּי דוֹסָא בֶן הַרְכִּינָס אוֹמֵר, הָעוֹבֵר לִפְנֵי הַתֵּבָה בְּיוֹם טוֹב שֶׁל רֹאשׁ הַשָּׁנָה אוֹמֵר, הַחֲלִיצֵנוּ ה' אֱלֹהֵינוּ אֶת יוֹם רֹאשׁ חֹדֶשׁ הַזֶּה, אִם הַיּוֹם, אִם לְמָחָר {כו}. וּלְמָחָר הוּא אוֹמֵר, אִם הַיּוֹם, אִם אֶמֶשׁ. וְלֹא הוֹדוּ לוֹ חֲכָמִים:
--------------------------------------------------------------------------------
פרק ד
--------------------------------------------------------------------------------
פרק ד - משנה א
מִי שֶׁהוֹצִיאוּהוּ גוֹיִם אוֹ רוּחַ רָעָה, אֵין לוֹ אֶלָּא אַרְבַּע אַמּוֹת. הֶחֱזִירוּהוּ, כְּאִלּוּ לֹא יָצָא. הוֹלִיכוּהוּ לְעִיר אַחֶרֶת. נְתָנוּהוּ {א} בְדִיר אוֹ בְסַהַר, רַבָּן גַּמְלִיאֵל וְרַבִּי אֶלְעָזָר בֶּן עֲזַרְיָה אוֹמְרִים, מְהַלֵּךְ אֶת כֻּלָּהּ. רַבִּי יְהוֹשֻׁעַ וְרַבִּי עֲקִיבָא אוֹמְרִים, אֵין לוֹ אֶלָּא אַרְבַּע אַמּוֹת. מַעֲשֶׂה שֶׁבָּאוּ מִפְּרַנְדִּיסִין וְהִפְלִיגָה סְפִינָתָם בַּיָּם. רַבָּן גַּמְלִיאֵל וְרַבִּי אֶלְעָזָר בֶּן עֲזַרְיָה הִלְּכוּ אֶת כֻּלָּהּ. רַבִּי יְהוֹשֻׁעַ וְרַבִּי עֲקִיבָא לֹא זָזוּ מֵאַרְבַּע אַמּוֹת, שֶׁרָצוּ לְהַחֲמִיר עַל עַצְמָן:
--------------------------------------------------------------------------------
פרק ד - משנה ב
פַּעַם אַחַת לֹא נִכְנְסוּ לַנָּמָל עַד שֶׁחֲשֵׁכָה. אָמְרוּ לוֹ לְרַבָּן גַּמְלִיאֵל, מָה אָנוּ לֵירֵד. אָמַר לָהֶן, מֻתָּר אַתֶּם, שֶׁכְּבָר הָיִיתִי מִסְתַּכֵּל, וְהָיִינוּ בְתוֹךְ הַתְּחוּם עַד שֶׁלֹּא חֲשֵׁכָה:
--------------------------------------------------------------------------------
פרק ד - משנה ג
מִי שֶׁיָּצָא בִרְשׁוּת וְאָמְרוּ לוֹ, כְּבָר נַעֲשָׂה מַעֲשֶׂה, יֶשׁ לוֹ אַלְפַּיִם אַמָּה לְכָל רוּחַ. אִם הָיָה בְתוֹךְ הַתְּחוּם, כְּאִלּוּ לֹא יָצָא, שֶׁכָּל הַיּוֹצְאִים לְהַצִּיל, חוֹזְרִין לִמְקוֹמָן:
--------------------------------------------------------------------------------
פרק ד - משנה ד
מִי שֶׁיָּשַׁב בַּדֶּרֶךְ, וְעָמַד, וְרָאָה וַהֲרֵי הוּא סָמוּךְ לָעִיר, הוֹאִיל וְלֹא הָיְתָה כַוָּנָתוֹ לְכָךְ, לֹא יִכָּנֵס, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, יִכָּנֵס {ז}. אָמַר רַבִּי יְהוּדָה, מַעֲשֶׂה הָיָה, וְנִכְנַס רַבִּי טַרְפוֹן בְּלֹא מִתְכַּוֵּן:
--------------------------------------------------------------------------------
פרק ד - משנה ה
מִי שֶׁיָּשֵׁן בַּדֶּרֶךְ וְלֹא יָדַע שֶׁחֲשֵׁכָה, יֵשׁ לוֹ אַלְפַּיִם אַמָּה לְכָל רוּחַ, דִּבְרֵי רַבִּי יוֹחָנָן בֶּן נוּרִי. וַחֲכָמִים אוֹמְרִים, אֵין לוֹ אֶלָּא אַרְבַּע אַמּוֹת. רַבִּי אֱלִיעֶזֶר אוֹמֵר, וְהוּא בְאֶמְצָעָן {י}. רַבִּי יְהוּדָה אוֹמֵר, לְאֵיזֶה רוּחַ שֶׁיִּרְצֶה יֵלֵךְ. וּמוֹדֶה רַבִּי יְהוּדָה {יא} שֶׁאִם בֵּרֵר לוֹ, שֶׁאֵינוֹ יָכוֹל לַחֲזֹר בּוֹ:
--------------------------------------------------------------------------------
פרק ד - משנה ו
הָיוּ שְׁנַיִם, מִקְצָת אַמּוֹתָיו שֶׁל זֶה בְּתוֹךְ אַמּוֹתָיו שֶׁל זֶה, מְבִיאִין וְאוֹכְלִין בָּאֶמְצַע, וּבִלְבַד שֶׁלֹּא יוֹצִיא זֶה מִתּוֹךְ שֶׁלּוֹ לְתוֹךְ שֶׁל חֲבֵרוֹ. הָיוּ שְׁלֹשָׁה, וְהָאֶמְצָעִי מֻבְלָע בֵּינֵיהֶן, הוּא מֻתָּר עִמָּהֶן וְהֵן מֻתָּרִין עִמּוֹ, וּשְׁנַיִם הַחִיצוֹנִים אֲסוּרִים זֶה עִם זֶה. אָמַר רַבִּי שִׁמְעוֹן, לְמָה הַדָּבָר דּוֹמֶה, לְשָׁלֹשׁ חֲצֵרוֹת הַפְּתוּחוֹת זוֹ לָזוֹ וּפְתוּחוֹת לִרְשׁוּת הָרַבִּים, עֵרְבוּ שְׁתֵּיהֶן עִם הָאֶמְצָעִית, הִיא מֻתֶּרֶת עִמָּהֶם וְהֵן מֻתָּרוֹת עִמָּהּ, וּשְׁתַּיִם הַחִיצוֹנוֹת אֲסוּרוֹת זוֹ עִם זוֹ:
--------------------------------------------------------------------------------
פרק ד - משנה ז
מִי שֶׁבָּא בַדֶּרֶךְ וְחָשְׁכָה לוֹ, וְהָיָה מַכִּיר אִילָן אוֹ גָדֵר, וְאָמַר, שְׁבִיתָתִי תַחְתָּיו, לֹא אָמַר כְּלוּם. שְׁבִיתָתִי בְעִקָּרוֹ, מְהַלֵּךְ מִמְּקוֹם רַגְלָיו וְעַד עִקָּרוֹ אַלְפַּיִם אַמָּה, וּמֵעִקָּרוֹ וְעַד בֵּיתוֹ אַלְפַּיִם אַמָּה {טו}. נִמְצָא מְהַלֵּךְ מִשֶּׁחֲשֵׁכָה אַרְבַּעַת אֲלָפִים אַמָּה:
--------------------------------------------------------------------------------
פרק ד - משנה ח
אִם אֵינוֹ מַכִּיר, אוֹ שֶׁאֵינוֹ בָקִי בַהֲלָכָה, וְאָמַר, שְׁבִיתָתִי בִמְקוֹמִי, זָכָה לוֹ {טז} מְקוֹמוֹ אַלְפַּיִם אַמָּה לְכָל רוּחַ. עֲגֻלּוֹת, דִּבְרֵי רַבִּי חֲנִינָא בֶן אַנְטִיגְנוֹס. וַחֲכָמִים אוֹמְרִים, מְרֻבָּעוֹת, כְּטַבְלָא מְרֻבַּעַת, כְּדֵי שֶׁיְּהֵא נִשְׂכָּר לַזָּוִיּוֹת:
--------------------------------------------------------------------------------
פרק ד - משנה ט
וְזוֹ הִיא שֶׁאָמְרוּ, הֶעָנִי {כ} מְעָרֵב בְּרַגְלָיו. אָמַר רַבִּי מֵאִיר, אָנוּ אֵין לָנוּ אֶלָּא עָנִי. רַבִּי יְהוּדָה אוֹמֵר, אֶחָד עָנִי וְאֶחָד עָשִׁיר, לֹא אָמְרוּ מְעָרְבִין בְּפַת אֶלָּא לְהָקֵל עַל הֶעָשִׁיר, שֶׁלֹּא יֵצֵא וִיעָרֵב בְּרַגְלָיו:
--------------------------------------------------------------------------------
פרק ד - משנה י
מִי שֶׁיָּצָא לֵילֵךְ בְּעִיר שֶׁמְּעָרְבִין בָּהּ וְהֶחֱזִירוֹ חֲבֵרוֹ, הוּא מֻתָּר לֵילֵךְ וְכָל בְּנֵי הָעִיר אֲסוּרִין, דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי מֵאִיר אוֹמֵר, כֹּל שֶׁהוּא יָכוֹל לְעָרֵב וְלֹא עֵרֵב, הֲרֵי זֶה חַמָּר גַּמָּל:
--------------------------------------------------------------------------------
פרק ד - משנה יא
מִי שֶׁיָּצָא חוּץ לַתְּחוּם, אֲפִלּוּ אַמָּה אַחַת, לֹא יִכָּנֵס. רַבִּי אֱלִיעֶזֶר אוֹמֵר, שְׁתַּיִם, יִכָּנֵס, שָׁלֹשׁ, לֹא יִכָּנֵס. מִי שֶׁהֶחְשִׁיךְ חוּץ לַתְּחוּם, אֲפִלּוּ אַמָּה אַחַת, לֹא יִכָּנֵס. רַבִּי שִׁמְעוֹן אוֹמֵר, אֲפִלּוּ חֲמֵשׁ עֶשְׂרֵה אַמּוֹת, יִכָּנֵס, שֶׁאֵין הַמָּשׁוֹחוֹת מְמַצִּין אֶת הַמִּדּוֹת, מִפְּנֵי הַטּוֹעִין:
--------------------------------------------------------------------------------
פרק ה
--------------------------------------------------------------------------------
פרק ה - משנה א
כֵּיצַד מְעַבְּרִין אֶת הֶעָרִים, בַּיִת נִכְנָס בַּיִת יוֹצֵא, פָּגוּם נִכְנָס פָּגוּם יוֹצֵא. הָיוּ שָׁם גְּדוּדִיּוֹת גְּבוֹהוֹת עֲשָׂרָה טְפָחִים, וּגְשָׁרִים {ג} וּנְפָשׁוֹת, שֶׁיֵּשׁ בָּהֶן בֵּית דִּירָה, מוֹצִיאִין אֶת הַמִּדָּה כְנֶגְדָּן, וְעוֹשִׂין אוֹתָהּ כְּמִין טַבְלָא מְרֻבַּעַת {ו}, כְּדֵי שֶׁיְּהֵא נִשְׂכָּר אֶת הַזָּוִיּוֹת:
--------------------------------------------------------------------------------
פרק ה - משנה ב
נוֹתְנִין קַרְפֵּף {ז} לָעִיר, דִּבְרֵי רַבִּי מֵאִיר. וַחֲכָמִים אוֹמְרִים, לֹא אָמְרוּ קַרְפֵּף אֶלָּא בֵין שְׁתֵּי עֲיָרוֹת, אִם יֵשׁ לָזוֹ שִׁבְעִים אַמָּה וְשִׁירַיִם, וְלָזוֹ שִׁבְעִים אַמָּה וְשִׁירַיִם, עוֹשֶׂה קַרְפֵּף לִשְׁתֵּיהֶן לִהְיוֹתָן כְּאֶחָת:
--------------------------------------------------------------------------------
פרק ה - משנה ג
וְכֵן שְׁלֹשָׁה כְפָרִים הַמְּשֻׁלָּשִׁין, אִם יֵשׁ בֵּין שְׁנַיִם הַחִיצוֹנִים מֵאָה וְאַרְבָּעִים וְאֶחָד וּשְׁלִישׁ, עָשָׂה אֶמְצָעִי אֶת שְׁלָשְׁתָּן לִהְיוֹתָן כְּאֶחָד:
--------------------------------------------------------------------------------
פרק ה - משנה ד
אֵין מוֹדְדִין אֶלָּא בְחֶבֶל שֶׁל חֲמִשִּׁים אַמָּה {ט}, לֹא פָחוֹת וְלֹא יוֹתֵר. וְלֹא יִמְדּוֹד אֶלָּא כְנֶגֶד לִבּוֹ. הָיָה מוֹדֵד וְהִגִּיעַ לְגַיְא אוֹ לְגָדֵר, מַבְלִיעוֹ וְחוֹזֵר לְמִדָּתוֹ. הִגִּיעַ לְהָר, מַבְלִיעוֹ {יב} וְחוֹזֵר לְמִדָּתוֹ, וּבִלְבַד שֶׁלֹּא יֵצֵא חוּץ לַתְּחוּם. אִם אֵינוֹ יָכוֹל לְהַבְלִיעוֹ {יד}, בָּזוֹ אָמַר רַבִּי דוֹסְתַּאי בַּר רַבִּי יַנַּאי מִשּׁוּם רַבִּי מֵאִיר, שָׁמַעְתִּי שֶׁמְּקַדְּרִין בֶּהָרִים:
--------------------------------------------------------------------------------
פרק ה - משנה ה
אֵין מוֹדְדִין אֶלָּא מִן הַמֻּמְחֶה. רִבָּה לְמָקוֹם אֶחָד וּמִעֵט לְמָקוֹם אַחֵר, שׁוֹמְעִין לִמְקוֹם שֶׁרִבָּה. רִבָּה לְאֶחָד וּמִעֵט לְאַחֵר, שׁוֹמְעִין לַמְרֻבֶּה. אֲפִלּוּ עֶבֶד, אֲפִלּוּ שִׁפְחָה, נֶאֱמָנִין לוֹמַר, עַד כָּאן תְּחוּם שַׁבָּת, שֶׁלֹּא אָמְרוּ חֲכָמִים {יז} אֶת הַדָּבָר לְהַחֲמִיר אֶלָּא לְהָקֵל:
--------------------------------------------------------------------------------
פרק ה - משנה ו
עִיר שֶׁל יָחִיד וְנַעֲשֵׂית שֶׁל רַבִּים, מְעָרְבִין אֶת כֻּלָּהּ. וְשֶׁל רַבִּים וְנַעֲשֵׂית שֶׁל יָחִיד, אֵין מְעָרְבִין אֶת כֻּלָּהּ, אֶלָּא אִם כֵּן עָשָׂה חוּצָה לָהּ כְּעִיר חֲדָשָׁה שֶׁבִּיהוּדָה, שֶׁיֵּשׁ בָּהּ חֲמִשִּׁים דִּיוּרִים, דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי שִׁמְעוֹן אוֹמֵר, שָׁלֹשׁ חֲצֵרוֹת שֶׁל שְׁנֵי בָתִּים:
--------------------------------------------------------------------------------
פרק ה - משנה ז
מִי שֶׁהָיָה בַמִּזְרָח וְאָמַר לִבְנוֹ {כ}, עָרֵב לִי בַמַּעֲרָב, בַּמַּעֲרָב וְאָמַר לִבְנוֹ, עָרֵב לִי בַמִּזְרָח, אִם יֵשׁ הֵימֶנּוּ וּלְבֵיתוֹ אַלְפַּיִם אַמּוֹת, וּלְעֵרוּבוֹ יוֹתֵר מִכָּאן, מֻתָּר לְבֵיתוֹ וְאָסוּר לְעֵרוּבוֹ. לְעֵרוּבוֹ אַלְפַּיִם אַמָּה, וּלְבֵיתוֹ יוֹתֵר מִכָּאן {כא}, אָסוּר לְבֵיתוֹ וּמֻתָּר לְעֵרוּבוֹ. הַנּוֹתֵן אֶת עֵרוּבוֹ בְעִבּוּרָהּ שֶׁל עִיר, לֹא עָשָׂה וְלֹא כְלוּם. נְתָנוֹ חוּץ לַתְּחוּם, אֲפִלּוּ אַמָּה אַחַת, מַה שֶׁנִּשְׂכָּר הוּא מַפְסִיד:
--------------------------------------------------------------------------------
פרק ה - משנה ח
אַנְשֵׁי עִיר גְּדוֹלָה מְהַלְּכִין אֶת כָּל עִיר קְטַנָּה, וְאֵין אַנְשֵׁי עִיר קְטַנָּה מְהַלְּכִין אֶת כָּל עִיר גְּדוֹלָה. כֵּיצַד. מִי שֶׁהָיָה בְעִיר גְּדוֹלָה וְנָתַן אֶת עֵרוּבוֹ בְעִיר קְטַנָּה, בְּעִיר קְטַנָּה וְנָתַן אֶת עֵרוּבוֹ בְעִיר גְּדוֹלָה, מְהַלֵּךְ אֶת כֻּלָּהּ וְחוּצָה לָהּ אַלְפַּיִם אַמָּה. וְרַבִּי עֲקִיבָא אוֹמֵר, אֵין לוֹ אֶלָּא מִמְּקוֹם עֵרוּבוֹ אַלְפַּיִם אַמָּה:
--------------------------------------------------------------------------------
פרק ה - משנה ט
אָמַר לָהֶן רַבִּי עֲקִיבָא, אִי אַתֶּם מוֹדִים לִי בְנוֹתֵן עֵרוּבוֹ בִמְעָרָה, שֶׁאֵין לוֹ מִמְּקוֹם עֵרוּבוֹ אֶלָּא אַלְפַּיִם אַמָּה. אָמְרוּ לוֹ, אֵימָתַי, בִּזְמַן שֶׁאֵין בָּהּ דִּיוּרִין, אֲבָל יֶשׁ בָּהּ דִּיוּרִין, מְהַלֵּךְ אֶת כֻּלָּהּ וְחוּצָה לָהּ אַלְפַּיִם אַמָּה. נִמְצָא, קַל תּוֹכָהּ מֵעַל גַּבָּהּ. וְלַמּוֹדֵד שֶׁאָמְרוּ נוֹתְנִין לוֹ אַלְפַּיִם, שֶׁאֲפִלּוּ סוֹף מִדָּתוֹ כָּלֶה בִמְעָרָה:
--------------------------------------------------------------------------------
פרק ו
--------------------------------------------------------------------------------
פרק ו - משנה א
הַדָּר עִם הַנָּכְרִי בֶחָצֵר, אוֹ עִם מִי שֶׁאֵינוֹ מוֹדֶה בָעֵרוּב {א}, הֲרֵי זֶה אוֹסֵר עָלָיו, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי אֱלִיעֶזֶר בֶּן יַעֲקֹב אוֹמֵר, לְעוֹלָם אֵינוֹ אוֹסֵר עַד שֶׁיְּהוּ שְׁנֵי יִשְׂרְאֵלִים אוֹסְרִין זֶה עַל זֶה:
--------------------------------------------------------------------------------
פרק ו - משנה ב
אָמַר רַבָּן גַּמְלִיאֵל, מַעֲשֶׂה בִצְדוֹקִי אֶחָד, שֶׁהָיָה דָר עִמָּנוּ בְּמָבוֹי {ד} בִּירוּשָׁלַיִם, וְאָמַר לָנוּ אַבָּא, מַהֲרוּ וְהוֹצִיאוּ אֶת כָּל הַכֵּלִים {ה} לַמָּבוֹי, עַד שֶׁלֹּא יוֹצִיא וְיֶאֱסֹר עֲלֵיכֶם. רַבִּי יְהוּדָה אוֹמֵר בְּלָשׁוֹן אַחֵר, מַהֲרוּ וַעֲשׂוּ צָרְכֵיכֶם בַּמָּבוֹי עַד שֶׁלֹּא יוֹצִיא וְיֶאֱסֹר עֲלֵיכֶם:
--------------------------------------------------------------------------------
פרק ו - משנה ג
אַנְשֵׁי חָצֵר שֶׁשָּׁכַח אַחַד מֵהֶן וְלֹא עֵרֵב, בֵּיתוֹ אָסוּר מִלְּהַכְנִיס וּמִלְּהוֹצִיא, לוֹ וְלָהֶם, וְשֶׁלָּהֶם מֻתָּרִין, לוֹ וְלָהֶם. נָתְנוּ לוֹ רְשׁוּתָן, הוּא מֻתָּר וְהֵן אֲסוּרִין. הָיוּ שְׁנַיִם, אוֹסְרִין זֶה עַל זֶה, שֶׁאֶחָד נוֹתֵן {ז} רְשׁוּת וְנוֹטֵל רְשׁוּת, שְׁנַיִם נוֹתְנִים רְשׁוּת וְאֵין נוֹטְלִין רְשׁוּת:
--------------------------------------------------------------------------------
פרק ו - משנה ד
מֵאֵימָתַי נוֹתְנִין רְשׁוּת. בֵּית שַׁמַּאי אוֹמְרִים, מִבְּעוֹד יוֹם, וּבֵית הִלֵּל אוֹמְרִים, מִשֶּׁחֲשֵׁכָה. מִי שֶׁנָּתַן רְשׁוּתוֹ וְהוֹצִיא, בֵּין בְּשׁוֹגֵג בֵּין בְּמֵזִיד, הֲרֵי זֶה אוֹסֵר, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, בְּמֵזִיד אוֹסֵר {ח}, בְּשׁוֹגֵג אֵינוֹ אוֹסֵר:
--------------------------------------------------------------------------------
פרק ו - משנה ה
בַּעַל הַבַּיִת שֶׁהָיָה שֻׁתָּף לִשְׁכֵנִים, לָזֶה בְיַיִן וְלָזֶה בְיַיִן, אֵינָם צְרִיכִים לְעָרֵב. לָזֶה בְיַיִן וְלָזֶה בְשֶׁמֶן, צְרִיכִים לְעָרֵב. רַבִּי שִׁמְעוֹן אוֹמֵר, אֶחָד זֶה וְאֶחָד זֶה, אֵינָם צְרִיכִים לְעָרֵב:
--------------------------------------------------------------------------------
פרק ו - משנה ו
חָמֵשׁ חֲבוּרוֹת שֶׁשָּׁבְתוּ בִטְרַקְלִין אֶחָד, בֵּית שַׁמַּאי אוֹמְרִים, עֵרוּב לְכָל חֲבוּרָה וַחֲבוּרָה. וּבֵית הִלֵּל אוֹמְרִים, עֵרוּב אֶחָד לְכֻלָּן. וּמוֹדִים, בִּזְמַן שֶׁמִּקְצָתָן שְׁרוּיִן בַּחֲדָרִים אוֹ בַעֲלִיּוֹת, שֶׁהֵן צְרִיכִין עֵרוּב לְכָל חֲבוּרָה וַחֲבוּרָה:
--------------------------------------------------------------------------------
פרק ו - משנה ז
הָאַחִין הַשֻּׁתָּפִין שֶׁהָיוּ אוֹכְלִין עַל שֻׁלְחַן אֲבִיהֶם וִישֵׁנִים בְּבָתֵּיהֶם, צְרִיכִין עֵרוּב לְכָל אֶחָד וְאֶחָד. לְפִיכָךְ, אִם שָׁכַח אֶחָד מֵהֶם וְלֹא עֵרֵב, מְבַטֵּל אֶת רְשׁוּתוֹ. אֵימָתַי, בִּזְמַן שֶׁמּוֹלִיכִין עֵרוּבָן בְּמָקוֹם אַחֵר, אֲבָל אִם הָיָה עֵרוּב בָּא אֶצְלָן, אוֹ שֶׁאֵין עִמָּהֶן דִּיוּרִין בֶּחָצֵר, אֵינָן צְרִיכִין לְעָרֵב:
--------------------------------------------------------------------------------
פרק ו - משנה ח
חָמֵשׁ חֲצֵרוֹת פְּתוּחוֹת זוֹ לָזוֹ וּפְתוּחוֹת לְמָבוֹי, עֵרְבוּ בַחֲצֵרוֹת וְלֹא נִשְׁתַּתְּפוּ בַמָּבוֹי, מֻתָּרִין בַּחֲצֵרוֹת וַאֲסוּרִין בַּמָּבוֹי. וְאִם נִשְׁתַּתְּפוּ בַמָּבוֹי, מֻתָּרִין כָּאן וָכָאן. עֵרְבוּ בַחֲצֵרוֹת וְנִשְׁתַּתְּפוּ בַמָּבוֹי, וְשָׁכַח אֶחָד מִבְּנֵי חָצֵר וְלֹא עֵרֵב, מֻתָּרִין כָּאן וָכָאן. מִבְּנֵי מָבוֹי וְלֹא נִשְׁתַּתֵּף, מֻתָּרִין בַּחֲצֵרוֹת וַאֲסוּרִין בַּמָּבוֹי {יז}, שֶׁהַמָּבוֹי לַחֲצֵרוֹת כֶּחָצֵר לַבָּתִּים:
--------------------------------------------------------------------------------
פרק ו - משנה ט
שְׁתֵּי חֲצֵרוֹת, זוֹ לִפְנִים מִזּוֹ, עֵרְבָה הַפְּנִימִית וְלֹא עֵרְבָה הַחִיצוֹנָה, הַפְּנִימִית מֻתֶּרֶת וְהַחִיצוֹנָה אֲסוּרָה. הַחִיצוֹנָה, וְלֹא הַפְּנִימִית, שְׁתֵּיהֶן אֲסוּרוֹת. עֵרְבָה זוֹ לְעַצְמָהּ וְזוֹ לְעַצְמָהּ, זוֹ מֻתֶּרֶת בִּפְנֵי עַצְמָהּ וְזוֹ מֻתֶּרֶת בִּפְנֵי עַצְמָהּ. רַבִּי עֲקִיבָא אוֹסֵר הַחִיצוֹנָה, שֶׁדְּרִיסַת הָרֶגֶל אוֹסַרְתָּהּ. וַחֲכָמִים אוֹמְרִים, אֵין דְּרִיסַת הָרֶגֶל אוֹסַרְתָּהּ:
--------------------------------------------------------------------------------
פרק ו - משנה י
שָׁכַח אַחַד מִן הַחִיצוֹנָה וְלֹא עֵרֵב, הַפְּנִימִית מֻתֶּרֶת וְהַחִיצוֹנָה אֲסוּרָה. מִן הַפְּנִימִית וְלֹא עֵרֵב, שְׁתֵּיהֶן אֲסוּרוֹת. נָתְנוּ עֵרוּבָן בְּמָקוֹם אֶחָד, וְשָׁכַח אֶחָד, בֵּין מִן הַפְּנִימִית בֵּין מִן הַחִיצוֹנָה, וְלֹא עֵרֵב, שְׁתֵּיהֶן אֲסוּרוֹת. וְאִם הָיוּ שֶׁל יְחִידִים, אֵינָן צְרִיכִין לְעָרֵב:
--------------------------------------------------------------------------------
פרק ז
--------------------------------------------------------------------------------
פרק ז - משנה א
חַלּוֹן שֶׁבֵּין שְׁתֵּי חֲצֵרוֹת, אַרְבָּעָה עַל אַרְבָּעָה, בְּתוֹךְ עֲשָׂרָה, מְעָרְבִין שְׁנַיִם, וְאִם רָצוּ, מְעָרְבִין אֶחָד. פָּחוֹת מֵאַרְבָּעָה עַל אַרְבָּעָה, אוֹ לְמַעְלָה מֵעֲשָׂרָה, מְעָרְבִין שְׁנַיִם וְאֵין מְעָרְבִין אֶחָד:
--------------------------------------------------------------------------------
פרק ז - משנה ב
כֹּתֶל שֶׁבֵּין שְׁתֵּי חֲצֵרוֹת גָּבוֹהַּ עֲשָׂרָה וְרָחָב אַרְבָּעָה, מְעָרְבִין שְׁנַיִם וְאֵין מְעָרְבִין אֶחָד. הָיוּ בְרֹאשׁוֹ פֵרוֹת, אֵלּוּ עוֹלִין מִכָּאן וְאוֹכְלִין, וְאֵלּוּ עוֹלִין מִכָּאן וְאוֹכְלִין, וּבִלְבַד שֶׁלֹּא יוֹרִידוּ לְמַטָּה. נִפְרְצָה הַכֹּתֶל עַד עֶשֶׂר אַמּוֹת {ד}, מְעָרְבִין שְׁנַיִם, וְאִם רָצוּ מְעָרְבִין אֶחָד, מִפְּנֵי שֶׁהוּא כְפֶתַח. יוֹתֵר מִכָּאן, מְעָרְבִין אֶחָד וְאֵין מְעָרְבִין שְׁנָיִם:
--------------------------------------------------------------------------------
פרק ז - משנה ג
חָרִיץ שֶׁבֵּין שְׁתֵּי חֲצֵרוֹת עָמוֹק עֲשָׂרָה וְרָחָב אַרְבַּע {ה}, מְעָרְבִין שְׁנַיִם וְאֵין מְעָרְבִין אֶחָד, אֲפִלּוּ מָלֵא קַשׁ אוֹ תֶבֶן. מָלֵא עָפָר {ז}, אוֹ צְרוֹרוֹת, מְעָרְבִין אֶחָד, וְאֵין מְעָרְבִין שְׁנָיִם:
--------------------------------------------------------------------------------
פרק ז - משנה ד
נָתַן עָלָיו נֶסֶר שֶׁהוּא רָחָב אַרְבָּעָה טְפָחִים, וְכֵן שְׁתֵּי גְזֻזְטְרָאוֹת זוֹ כְנֶגֶד זוֹ, מְעָרְבִין שְׁנַיִם {ח}, וְאִם רָצוּ, מְעָרְבִין אֶחָד. פָּחוֹת מִכָּאן, מְעָרְבִין שְׁנַיִם וְאֵין מְעָרְבִין אֶחָד:
--------------------------------------------------------------------------------
פרק ז - משנה ה
מַתְבֵּן שֶׁבֵּין שְׁתֵּי חֲצֵרוֹת, גָּבוֹהַּ עֲשָׂרָה טְפָחִים, מְעָרְבִין שְׁנַיִם וְאֵין מְעָרְבִין אֶחָד. אֵלּוּ מַאֲכִילִין מִכָּאן וְאֵלּוּ מַאֲכִילִין מִכָּאן. נִתְמַעֵט הַתֶּבֶן מֵעֲשָׂרָה טְפָחִים, מְעָרְבִין אֶחָד וְאֵין מְעָרְבִין שְׁנָיִם:
--------------------------------------------------------------------------------
פרק ז - משנה ו
כֵּיצַד מִשְׁתַּתְּפִין בַּמָּבוֹי. מֵנִיחַ אֶת הֶחָבִית וְאוֹמֵר, הֲרֵי זוֹ לְכָל בְּנֵי מָבוֹי, וּמְזַכֶּה לָהֶן עַל יְדֵי בְנוֹ וּבִתּוֹ הַגְּדוֹלִים {י} וְעַל יְדֵי עַבְדּוֹ וְשִׁפְחָתוֹ הָעִבְרִים {יא} וְעַל יְדֵי אִשְׁתּוֹ {יב}, אֲבָל אֵינוֹ מְזַכֶּה לֹא עַל יְדֵי בְנוֹ וּבִתּוֹ הַקְּטַנִּים וְלֹא עַל יְדֵי עַבְדּוֹ וְשִׁפְחָתוֹ הַכְּנַעֲנִים, מִפְּנֵי שֶׁיָּדָן {יג} כְּיָדוֹ:
--------------------------------------------------------------------------------
פרק ז - משנה ז
נִתְמַעֵט {יד} הָאֹכֶל, מוֹסִיף וּמְזַכֶּה, וְאֵין צָרִיךְ לְהוֹדִיעַ. נִתּוֹסְפוּ עֲלֵיהֶם, מוֹסִיף וּמְזַכֶּה, וְצָרִיךְ לְהוֹדִיעַ:
--------------------------------------------------------------------------------
פרק ז - משנה ח
כַּמָּה {יז} הוּא שִׁעוּרוֹ. בִּזְמַן שֶׁהֵן מְרֻבִּין, מְזוֹן שְׁתֵּי סְעוּדוֹת {יט} לְכֻלָּם. בִּזְמַן שֶׁהֵן מֻעָטִין, כִּגְרוֹגֶרֶת לְהוֹצָאַת שַׁבָּת לְכָל אֶחָד וְאֶחָד:
--------------------------------------------------------------------------------
פרק ז - משנה ט
אָמַר רַבִּי יוֹסֵי, בַּמֶּה דְבָרִים אֲמוּרִים, בִּתְחִלַּת עֵרוּב. אֲבָל בִּשְׁיָרֵי עֵרוּב, כָּל שֶׁהוּא. וְלֹא אָמְרוּ לְעָרֵב בַּחֲצֵרוֹת אֶלָּא כְדֵי שֶׁלֹּא לְשַׁכֵּחַ אֶת הַתִּינוֹקוֹת:
--------------------------------------------------------------------------------
פרק ז - משנה י
בַּכֹּל מְעָרְבִין וּמִשְׁתַּתְּפִין, חוּץ מִן הַמַּיִם וּמִן הַמֶּלַח, דִּבְרֵי רַבִּי אֱלִיעֶזֶר. רַבִּי יְהוֹשֻׁעַ אוֹמֵר, כִּכָּר הוּא עֵרוּב. אֲפִלּוּ מַאֲפֵה סְאָה וְהִיא פְרוּסָה, אֵין מְעָרְבִין בָּהּ. כִּכָּר בְּאִסָּר וְהוּא שָׁלֵם, מְעָרְבִין בּוֹ:
--------------------------------------------------------------------------------
פרק ז - משנה יא
נוֹתֵן אָדָם מָעָה לְחֶנְוָנִי וּלְנַחְתּוֹם כְּדֵי שֶׁיִּזְכֶּה לוֹ עֵרוּב, דִּבְרֵי רַבִּי אֱלִיעֶזֶר {כב}. וַחֲכָמִים אוֹמְרִים, לֹא זָכוּ לוֹ מְעוֹתָיו. וּמוֹדִים בִּשְׁאָר כָּל אָדָם שֶׁזָּכוּ לוֹ מְעוֹתָיו, שֶׁאֵין מְעָרְבִין לְאָדָם אֶלָּא מִדַּעְתּוֹ. אָמַר רַבִּי יְהוּדָה, בַּמֶּה דְבָרִים אֲמוּרִים, בְּעֵרוּבֵי תְחוּמִין, אֲבָל בְּעֵרוּבֵי חֲצֵרוֹת {כו}, מְעָרְבִין לְדַעְתּוֹ וְשֶׁלֹּא לְדַעְתּוֹ, לְפִי שֶׁזָּכִין לְאָדָם שֶׁלֹּא בְּפָנָיו, וְאֵין חָבִין לְאָדָם שֶׁלֹּא בְּפָנָיו:
--------------------------------------------------------------------------------
פרק ח
--------------------------------------------------------------------------------
פרק ח - משנה א
כֵּיצַד מִשְׁתַּתְּפִין בַּתְּחוּמִין. מֵנִיחַ {א} אֶת הֶחָבִית וְאוֹמֵר, הֲרֵי זֶה לְכָל בְּנֵי עִירִי, לְכָל מִי שֶׁיֵּלֵךְ לְבֵית הָאֵבֶל אוֹ לְבֵית הַמִּשְׁתֶּה. וְכֹל שֶׁקִּבֵּל עָלָיו מִבְּעוֹד יוֹם, מֻתָּר. מִשֶּׁתֶּחְשַׁךְ, אָסוּר, שֶׁאֵין מְעָרְבִין מִשֶּׁתֶּחְשָׁךְ:
--------------------------------------------------------------------------------
פרק ח - משנה ב
כַּמָּה הוּא שִׁעוּרוֹ, מְזוֹן שְׁתֵּי סְעוּדוֹת לְכָל אֶחָד. מְזוֹנוֹ לְחֹל וְלֹא לְשַׁבָּת, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, לְשַׁבָּת וְלֹא לְחֹל. וְזֶה וָזֶה מִתְכַּוְּנִין לְהָקֵל. רַבִּי יוֹחָנָן בֶּן בְּרוֹקָה אוֹמֵר, מִכִּכָּר {ז} בְּפֻנְדְּיוֹן, מֵאַרְבַּע סְאִין בְּסֶלַע. רַבִּי שִׁמְעוֹן אוֹמֵר, שְׁתֵּי יָדוֹת לְכִכָּר מִשָּׁלֹשׁ לְקָב. חֶצְיָהּ לְבַיִת הַמְנֻגָּע, וַחֲצִי חֶצְיָהּ לִפְסֹל אֶת הַגְּוִיָּה:
--------------------------------------------------------------------------------
פרק ח - משנה ג
אַנְשֵׁי חָצֵר וְאַנְשֵׁי מִרְפֶּסֶת שֶׁשָּׁכְחוּ {ט} וְלֹא עֵרְבוּ, כֹּל שֶׁגָּבוֹהַּ עֲשָׂרָה טְפָחִים, לַמִּרְפֶּסֶת. פָּחוֹת מִכָּאן, לֶחָצֵר {י}. חֻלְיַת הַבּוֹר וְהַסֶּלַע, גְּבוֹהִים עֲשָׂרָה טְפָחִים, לַמִּרְפֶּסֶת. פָּחוֹת מִכָּאן, לֶחָצֵר. בַּמֶּה דְבָרִים אֲמוּרִים {יג}, בִּסְמוּכָה. אֲבָל בְּמֻפְלֶגֶת, אֲפִלּוּ גָבוֹהַּ עֲשָׂרָה טְפָחִים, לֶחָצֵר. וְאֵיזוֹ הִיא סְמוּכָה, כֹּל שֶׁאֵינָהּ רְחוֹקָה אַרְבָּעָה טְפָחִים:
--------------------------------------------------------------------------------
פרק ח - משנה ד
הַנּוֹתֵן אֶת עֵרוּבוֹ בְּבֵית שַׁעַר {יד}, אַכְסַדְרָה וּמִרְפֶּסֶת {טו}, אֵינוֹ עֵרוּב. וְהַדָּר שָׁם, אֵינוֹ אוֹסֵר עָלָיו. בְּבֵית הַתֶּבֶן וּבְבֵית הַבָּקָר וּבְבֵית הָעֵצִים וּבְבֵית הָאוֹצָרוֹת, הֲרֵי זֶה עֵרוּב. וְהַדָּר שָׁם, אוֹסֵר עָלָיו. רַבִּי יְהוּדָה אוֹמֵר, אִם יֶשׁ שָׁם תְּפִיסַת יָד שֶׁל בַּעַל הַבַּיִת, אֵינוֹ אוֹסֵר עָלָיו:
--------------------------------------------------------------------------------
פרק ח - משנה ה
הַמַּנִּיחַ בֵּיתוֹ וְהָלַךְ לִשְׁבּוֹת בְּעִיר אַחֶרֶת, אֶחָד נָכְרִי וְאֶחָד יִשְׂרָאֵל, הֲרֵי זֶה אוֹסֵר, דִּבְרֵי רַבִּי מֵאִיר. רַבִּי יְהוּדָה אוֹמֵר, אֵינוֹ אוֹסֵר. רַבִּי יוֹסֵי אוֹמֵר, נָכְרִי אוֹסֵר, יִשְׂרָאֵל אֵינוֹ אוֹסֵר, שֶׁאֵין דֶּרֶךְ יִשְׂרָאֵל לָבֹא בְשַׁבָּת. רַבִּי שִׁמְעוֹן אוֹמֵר, אֲפִלּוּ הִנִּיחַ בֵּיתוֹ וְהָלַךְ לִשְׁבּוֹת אֵצֶל בִּתּוֹ בְאוֹתָהּ הָעִיר, אֵינוֹ אוֹסֵר, שֶׁכְּבָר הִסִּיעַ מִלִּבּוֹ:
--------------------------------------------------------------------------------
פרק ח - משנה ו
בּוֹר שֶׁבֵּין שְׁתֵּי חֲצֵרוֹת, אֵין מְמַלְּאִין מִמֶּנּוּ בְשַׁבָּת, אֶלָּא אִם כֵּן עָשׂוּ לוֹ מְחִצָּה גָבוֹהַּ עֲשָׂרָה טְפָחִים בֵּין מִלְמַעְלָה, בֵּין מִלְּמַטָּה, בֵּין מִתּוֹךְ אֹגְנוֹ. רַבָּן שִׁמְעוֹן בֶּן גַּמְלִיאֵל אוֹמֵר, בֵּית שַׁמַּאי אוֹמְרִים, מִלְּמַטָּה. וּבֵית הִלֵּל אוֹמְרִים, מִלְמָעְלָה. אָמַר רַבִּי יְהוּדָה, לֹא תְהֵא מְחִצָּה גְדוֹלָה מִן הַכֹּתֶל שֶׁבֵּינֵיהֶם:
--------------------------------------------------------------------------------
פרק ח - משנה ז
אַמַּת הַמַּיִם שֶׁהִיא עוֹבֶרֶת בֶּחָצֵר, אֵין מְמַלְּאִין הֵימֶנָּה בְשַׁבָּת, אֶלָּא אִם כֵּן עָשׂוּ לָהּ מְחִצָּה גָבוֹהַּ עֲשָׂרָה טְפָחִים בַּכְּנִיסָה וּבַיְצִיאָה. רַבִּי יְהוּדָה אוֹמֵר, כֹּתֶל שֶׁעַל גַּבָּהּ תִּדּוֹן מִשּׁוּם מְחִצָּה. אָמַר רַבִּי יְהוּדָה, מַעֲשֶׂה {יט} בָאַמָּה שֶׁל אָבֵל שֶׁהָיוּ מְמַלְּאִין מִמֶּנָּה עַל פִּי זְקֵנִים בְּשַׁבָּת. אָמְרוּ לוֹ, מִפְּנֵי שֶׁלֹּא הָיָה בָהּ כַּשִּׁעוּר:
--------------------------------------------------------------------------------
פרק ח - משנה ח
גְּזֻזְטְרָא שֶׁהִיא לְמַעְלָה מִן הַמַּיִם, אֵין מְמַלְּאִין הֵימֶנָּה בְשַׁבָּת, אֶלָּא אִם כֵּן עָשׂוּ לָהּ מְחִצָּה גָבוֹהַּ עֲשָׂרָה טְפָחִים, בֵּין מִלְמַעְלָה בֵּין מִלְּמַטָּה. וְכֵן שְׁתֵּי גְזֻזְטְרָאוֹת זוֹ לְמַעְלָה מִזּוֹ. עָשׂוּ לָעֶלְיוֹנָה וְלֹא עָשׂוּ לַתַּחְתּוֹנָה {כד}, שְׁתֵּיהֶן אֲסוּרוֹת עַד שֶׁיְּעָרֵבוּ:
--------------------------------------------------------------------------------
פרק ח - משנה ט
חָצֵר שֶׁהִיא פְחוּתָה מֵאַרְבַּע אַמּוֹת {כו}, אֵין שׁוֹפְכִין בְּתוֹכָהּ מַיִם בְּשַׁבָּת, אֶלָּא אִם כֵּן עָשׂוּ לָהּ עוּקָה מַחֲזֶקֶת סָאתַיִם {כח} מִן הַנֶּקֶב וּלְמַטָּה, בֵּין מִבַּחוּץ בֵּין מִבִּפְנִים, אֶלָּא שֶׁמִּבַּחוּץ צָרִיךְ לִקְמוֹר, מִבִּפְנִים אֵין צָרִיךְ לִקְמוֹר:
--------------------------------------------------------------------------------
פרק ח - משנה י
רַבִּי אֱלִיעֶזֶר בֶּן יַעֲקֹב אוֹמֵר, בִּיב שֶׁהוּא קָמוּר אַרְבַּע אַמּוֹת בִּרְשׁוּת הָרַבִּים, שׁוֹפְכִין לְתוֹכוֹ מַיִם בְּשַׁבָּת. וַחֲכָמִים אוֹמְרִים, אֲפִלּוּ גַג אוֹ חָצֵר מֵאָה אַמָּה, לֹא יִשְׁפֹּךְ עַל פִּי הַבִּיב, אֲבָל שׁוֹפֵךְ מִגַּג לְגַג {לג}, וְהַמַּיִם יוֹרְדִין לַבִּיב. הֶחָצֵר וְהָאַכְסַדְרָה מִצְטָרְפִין לְאַרְבַּע אַמּוֹת:
--------------------------------------------------------------------------------
פרק ח - משנה יא
וְכֵן שְׁתֵּי דְיוֹטָאוֹת זוֹ כְנֶגֶד זוֹ, מִקְצָתָן עָשׂוּ עוּקָה וּמִקְצָתָן לֹא עָשׂוּ עוּקָה, אֶת שֶׁעָשׂוּ עוּקָה, מֻתָּרִין, וְאֶת שֶׁלֹּא עָשׂוּ עוּקָה, אֲסוּרִין:
--------------------------------------------------------------------------------
פרק ט
--------------------------------------------------------------------------------
פרק ט - משנה א
כָּל גַּגּוֹת הָעִיר, רְשׁוּת אַחַת, וּבִלְבַד שֶׁלֹּא יְהֵא גַג גָּבוֹהַּ עֲשָׂרָה אוֹ נָמוֹךְ {ב} עֲשָׂרָה, דִּבְרֵי רַבִּי מֵאִיר. וַחֲכָמִים אוֹמְרִים, כָּל אֶחָד וְאֶחָד רְשׁוּת בִּפְנֵי עַצְמוֹ. רַבִּי שִׁמְעוֹן אוֹמֵר, אֶחָד גַּגּוֹת וְאֶחָד חֲצֵרוֹת וְאֶחָד קַרְפֵּיפוֹת, רְשׁוּת אֶחָד לַכֵּלִים שֶׁשָּׁבְתוּ לְתוֹכָן, וְלֹא לַכֵּלִים שֶׁשָּׁבְתוּ בְתוֹךְ הַבָּיִת:
--------------------------------------------------------------------------------
פרק ט - משנה ב
גַּג גָּדוֹל {ו} סָמוּךְ לְקָטָן, הַגָּדוֹל מֻתָּר וְהַקָּטָן אָסוּר. חָצֵר גְּדוֹלָה שֶׁנִּפְרְצָה לִקְטַנָּה, גְּדוֹלָה מֻתֶּרֶת {ט}, וּקְטַנָּה אֲסוּרָה, מִפְּנֵי שֶׁהִיא כְפִתְחָהּ שֶׁל גְּדוֹלָה. חָצֵר שֶׁנִּפְרְצָה לִרְשׁוּת הָרַבִּים {י}, הַמַּכְנִיס מִתּוֹכָהּ לִרְשׁוּת הַיָּחִיד, אוֹ מֵרְשׁוּת הַיָּחִיד לְתוֹכָהּ, חַיָּב, דִּבְרֵי רַבִּי אֱלִיעֶזֶר. וַחֲכָמִים אוֹמְרִים, מִתּוֹכָהּ לִרְשׁוּת הָרַבִּים {יא}, אוֹ מֵרְשׁוּת הָרַבִּים לְתוֹכָהּ, פָּטוּר, מִפְּנֵי שֶׁהִיא כְּכַרְמְלִית:
--------------------------------------------------------------------------------
פרק ט - משנה ג
חָצֵר שֶׁנִּפְרְצָה לִרְשׁוּת הָרַבִּים מִשְּׁתֵּי רוּחוֹתֶיהָ, וְכֵן בַּיִת שֶׁנִּפְרַץ מִשְּׁתֵּי רוּחוֹתָיו, וְכֵן מָבוֹי שֶׁנִּטְּלוּ קוֹרוֹתָיו אוֹ לְחָיָיו, מֻתָּרִין בְּאוֹתוֹ שַׁבָּת וַאֲסוּרִין לֶעָתִיד לָבֹא, דִּבְרֵי רַבִּי יְהוּדָה. רַבִּי יוֹסֵי אוֹמֵר, אִם מֻתָּרִין לְאוֹתוֹ שַׁבָּת, מֻתָּרִין לֶעָתִיד לָבֹא. וְאִם אֲסוּרִין לֶעָתִיד לָבֹא, אֲסוּרִין לְאוֹתוֹ שַׁבָּת:
--------------------------------------------------------------------------------
פרק ט - משנה ד
הַבּוֹנֶה עֲלִיָּה עַל גַּבֵּי שְׁנֵי בָתִּים, וְכֵן גְּשָׁרִים הַמְפֻלָּשִׁים, מְטַלְטְלִין תַּחְתֵּיהֶן בְּשַׁבָּת, דִּבְרֵי רַבִּי יְהוּדָה. וַחֲכָמִים אוֹסְרִין {יד}. וְעוֹד אָמַר רַבִּי יְהוּדָה {טו}, מְעָרְבִין {טז} לְמָבוֹי הַמְפֻלָּשׁ. וַחֲכָמִים אוֹסְרִין:
--------------------------------------------------------------------------------
פרק י
--------------------------------------------------------------------------------
פרק י - משנה א
הַמּוֹצֵא תְפִלִּין, מַכְנִיסָן זוּג זוּג. רַבָּן גַּמְלִיאֵל אוֹמֵר, שְׁנַיִם שְׁנָיִם. בַּמֶּה דְבָרִים אֲמוּרִים, בִּישָׁנוֹת, אֲבָל בַּחֲדָשׁוֹת, פָּטוּר. מְצָאָן צְבָתִים אוֹ כְרִיכוֹת, מַחְשִׁיךְ עֲלֵיהֶן וּמְבִיאָן. וּבַסַּכָּנָה, מְכַסָּן וְהוֹלֵךְ לוֹ:
--------------------------------------------------------------------------------
פרק י - משנה ב
רַבִּי שִׁמְעוֹן אוֹמֵר, נוֹתְנָן לַחֲבֵרוֹ {ז}, וַחֲבֵרוֹ לַחֲבֵרוֹ, עַד שֶׁמַּגִּיעַ לֶחָצֵר הַחִיצוֹנָה. וְכֵן בְּנוֹ {ח}, נוֹתְנוֹ לַחֲבֵרוֹ, וַחֲבֵרוֹ לַחֲבֵרוֹ, אֲפִלּוּ מֵאָה {ט}. רַבִּי יְהוּדָה אוֹמֵר, נוֹתֵן אָדָם חָבִית לַחֲבֵרוֹ, וַחֲבֵרוֹ לַחֲבֵרוֹ, אֲפִלּוּ חוּץ לַתְּחוּם. אָמְרוּ לוֹ, לֹא תְהַלֵּךְ זוֹ יוֹתֵר מֵרַגְלֵי בְעָלֶיהָ:
--------------------------------------------------------------------------------
פרק י - משנה ג
הָיָה קוֹרֵא בַסֵּפֶר עַל הָאַסְקֻפָּה, נִתְגַּלְגֵּל הַסֵּפֶר מִיָּדוֹ, גּוֹלְלוֹ אֶצְלוֹ. הָיָה קוֹרֵא בְרֹאשׁ הַגַּג וְנִתְגַּלְגֵּל הַסֵּפֶר מִיָּדוֹ, עַד שֶׁלֹּא הִגִּיעַ לַעֲשָׂרָה טְפָחִים, גּוֹלְלוֹ אֶצְלוֹ. מִשֶּׁהִגִּיעַ לַעֲשָׂרָה טְפָחִים, הוֹפְכוֹ עַל הַכְּתָב. רַבִּי יְהוּדָה אוֹמֵר, אֲפִלּוּ אֵין מְסֻלָּק מִן הָאָרֶץ אֶלָּא כִמְלֹא מַחַט, גּוֹלְלוֹ אֶצְלוֹ. רַבִּי שִׁמְעוֹן אוֹמֵר, אֲפִלּוּ בָאָרֶץ עַצְמוֹ גּוֹלְלוֹ אֶצְלוֹ, שֶׁאֵין לְךָ דָּבָר מִשּׁוּם שְׁבוּת עוֹמֵד בִּפְנֵי כִתְבֵי הַקֹּדֶשׁ:
--------------------------------------------------------------------------------
פרק י - משנה ד
זִיז שֶׁלִּפְנֵי חַלּוֹן, נוֹתְנִין עָלָיו וְנוֹטְלִין מִמֶּנּוּ בְשַׁבָּת. עוֹמֵד אָדָם בִּרְשׁוּת הַיָּחִיד וּמְטַלְטֵל בִּרְשׁוּת הָרַבִּים, בִּרְשׁוּת הָרַבִּים וּמְטַלְטֵל בִּרְשׁוּת הַיָּחִיד, וּבִלְבַד שֶׁלֹּא יוֹצִיא {יד} חוּץ מֵאַרְבַּע אַמּוֹת:
--------------------------------------------------------------------------------
פרק י - משנה ה
לֹא יַעֲמֹד אָדָם בִּרְשׁוּת הַיָּחִיד וְיַשְׁתִּין בִּרְשׁוּת הָרַבִּים, בִּרְשׁוּת הָרַבִּים וְיַשְׁתִּין בִּרְשׁוּת הַיָּחִיד. וְכֵן לֹא יָרֹק. רַבִּי יְהוּדָה אוֹמֵר, אַף מִשֶּׁנִּתְלַשׁ רֻקּוֹ בְּפִיו, לֹא יְהַלֵּךְ אַרְבַּע אַמּוֹת עַד שֶׁיָרֹק:
--------------------------------------------------------------------------------
פרק י - משנה ו
לֹא יַעֲמֹד אָדָם בִּרְשׁוּת הַיָחִיד וְיִשְׁתֶּה בִרְשׁוּת הָרַבִּים, בִּרְשׁוּת הָרַבִּים וְיִשְׁתֶּה בִרְשׁוּת הַיָחִיד, אֶלָּא אִם כֵּן הִכְנִיס רֹאשׁוֹ וְרֻבּוֹ לִמְקוֹם שֶׁהוּא שׁוֹתֶה. וְכֵן בְּגַת. קוֹלֵט אָדָם מִן הַמַּזְחֵלָה לְמַטָּה מֵעֲשָׂרָה טְפָחִים. וּמִן הַצִּנּוֹר, מִכָּל מָקוֹם שׁוֹתֶה:
--------------------------------------------------------------------------------
פרק י - משנה ז
בּוֹר בִּרְשׁוּת הָרַבִּים, וְחֻלְיָתוֹ גְבוֹהָה עֲשָׂרָה טְפָחִים, חַלּוֹן שֶׁעַל גַּבָּיו מְמַלְּאִין הֵימֶנּוּ בְשַׁבָּת. אַשְׁפָּה בִרְשׁוּת הָרַבִּים גְּבוֹהָה עֲשָׂרָה טְפָחִים, חַלּוֹן שֶׁעַל גַּבָּהּ שׁוֹפְכִין לְתוֹכָהּ מַיִם בְּשַׁבָּת:
--------------------------------------------------------------------------------
פרק י - משנה ח
אִילָן שֶׁהוּא מֵסֵךְ עַל הָאָרֶץ, אִם אֵין נוֹפוֹ גָבוֹהַּ מִן הָאָרֶץ שְׁלֹשָׁה טְפָחִים, מְטַלְטְלִין תַּחְתָּיו. שָׁרָשָׁיו {כו} גְּבוֹהִין מִן הָאָרֶץ שְׁלֹשָׁה טְפָחִים, לֹא יֵשֵׁב עֲלֵיהֶן. הַדֶּלֶת שֶׁבַּמֻּקְצֶה וַחֲדָקִים שֶׁבַּפִּרְצָה וּמַחֲצָלוֹת, אֵין נוֹעֲלִין {כח} בָּהֶן, אֶלָּא אִם כֵּן גְּבוֹהִים {כט} מִן הָאָרֶץ:
--------------------------------------------------------------------------------
פרק י - משנה ט
לֹא יַעֲמֹד אָדָם בִּרְשׁוּת הַיָּחִיד וְיִפְתַּח בִּרְשׁוּת הָרַבִּים, בִּרְשׁוּת הָרַבִּים וְיִפְתַּח בִּרְשׁוּת הַיָּחִיד, אֶלָּא אִם כֵּן {ל} עָשָׂה מְחִצָּה גְבוֹהָה עֲשָׂרָה טְפָחִים, דִּבְרֵי רַבִּי מֵאִיר {לא}. אָמְרוּ לוֹ, מַעֲשֶׂה בְשׁוּק שֶׁל פַּטָּמִין שֶׁהָיָה בִירוּשָׁלַיִם, שֶׁהָיוּ נוֹעֲלִין וּמַנִּיחִין אֶת הַמַּפְתֵּחַ בַּחַלּוֹן שֶׁעַל גַּבֵּי הַפֶּתַח. רַבִּי יוֹסֵי אוֹמֵר {לג}, שׁוּק שֶׁל צַמָּרִים הָיָה:
--------------------------------------------------------------------------------
פרק י - משנה י
נֶגֶר שֶׁיֵּשׁ בְּרֹאשׁוֹ גְלֻסְטְרָא, רַבִּי אֱלִיעֶזֶר אוֹסֵר, וְרַבִּי יוֹסֵי מַתִּיר {לד}. אָמַר רַבִּי אֱלִיעֶזֶר, מַעֲשֶׂה בַכְּנֶסֶת שֶׁבִּטְבֶרְיָא שֶׁהָיוּ נוֹהֲגִין בּוֹ הֶתֵּר, עַד שֶׁבָּא רַבָּן גַּמְלִיאֵל וְהַזְּקֵנִים וְאָסְרוּ לָהֶן. רַבִּי יוֹסֵי אוֹמֵר, אִסּוּר נָהֲגוּ בָהּ, בָּא רַבָּן גַּמְלִיאֵל וְהַזְּקֵנִים וְהִתִּירוּ לָהֶן:
--------------------------------------------------------------------------------
פרק י - משנה יא
נֶגֶר הַנִּגְרָר, נוֹעֲלִים בּוֹ בַמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. וְהַמֻּנָּח, כָּאן וָכָאן אָסוּר. רַבִּי יְהוּדָה אוֹמֵר, הַמֻּנָּח מֻתָּר בַּמִּקְדָּשׁ, וְהַנִּגְרָר בַּמְּדִינָה:
--------------------------------------------------------------------------------
פרק י - משנה יב
מַחֲזִירִין צִיר {לז} הַתַּחְתּוֹן בַּמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. וְהָעֶלְיוֹן, כָּאן וְכָאן אָסוּר. רַבִּי יְהוּדָה אוֹמֵר, הָעֶלְיוֹן בַּמִּקְדָּשׁ, וְהַתַּחְתּוֹן בַּמְּדִינָה:
--------------------------------------------------------------------------------
פרק י - משנה יג
מַחֲזִירִין רְטִיָּה בַמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. אִם בַּתְּחִלָּה, כָּאן וְכָאן אָסוּר. קוֹשְׁרִין נִימָא בַמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. אִם בַּתְּחִלָּה, כָּאן וְכָאן אָסוּר. חוֹתְכִין יַבֶּלֶת {מו} בַּמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. וְאִם בִּכְלִי, כָּאן וְכָאן אָסוּר:
--------------------------------------------------------------------------------
פרק י - משנה יד
כֹּהֵן שֶׁלָּקָה בְאֶצְבָּעוֹ, כּוֹרֵךְ {מז} עָלֶיהָ גֶמִי בַמִּקְדָּשׁ, אֲבָל לֹא בַמְּדִינָה. אִם לְהוֹצִיא דָם, כָּאן וְכָאן אָסוּר. בּוֹזְקִין מֶלַח עַל גַּבֵּי כֶבֶשׁ בִּשְׁבִיל שֶׁלֹּא יַחֲלִיקוּ, וּמְמַלְּאִים מִבּוֹר הַגּוֹלָה וּמִבּוֹר הַגָּדוֹל בַּגַּלְגַּל בְּשַׁבָּת, וּמִבְּאֵר הַקַּר בְּיוֹם טוֹב:
--------------------------------------------------------------------------------
פרק י - משנה טו
שֶׁרֶץ שֶׁנִּמְצָא {נב} בַמִּקְדָּשׁ, כֹּהֵן מוֹצִיאוֹ בְהֶמְיָנוֹ, שֶׁלֹּא לְשַׁהוֹת אֶת הַטֻּמְאָה, דִּבְרֵי רַבִּי יוֹחָנָן בֶּן בְּרוֹקָה. רַבִּי יְהוּדָה אוֹמֵר, בִּצְבָת שֶׁל עֵץ, שֶׁלֹּא לְרַבּוֹת אֶת הַטֻּמְאָה. מֵהֵיכָן מוֹצִיאִין אוֹתוֹ, מִן הַהֵיכָל וּמִן הָאוּלָם וּמִבֵּין הָאוּלָם וְלַמִּזְבֵּחַ {נד}, דִּבְרֵי רַבִּי שִׁמְעוֹן בֶּן נַנָּס. רַבִּי עֲקִיבָא אוֹמֵר, מְקוֹם שֶׁחַיָּבִין עַל זְדוֹנוֹ כָּרֵת וְעַל שִׁגְגָתוֹ חַטָּאת, מִשָּׁם מוֹצִיאִין אוֹתוֹ, וּשְׁאָר כָּל הַמְּקוֹמוֹת כּוֹפִין עָלָיו פְּסַכְתֵּר. רַבִּי שִׁמְעוֹן אוֹמֵר, מְקוֹם שֶׁהִתִּירוּ לְךָ חֲכָמִים, מִשֶּׁלְּךָ נָתְנוּ לְךָ, שֶׁלֹּא הִתִּירוּ לְךָ אֶלָּא מִשּׁוּם שְׁבוּת:
הלשמות
אות א
גמרא מביא מחלקת אם חודו החיצון יורד וסותם או חודו הפנימי יורד וסותם. תולה על זה מחלקת אם צריך להיות הממעט טפח אחד או ארבע טפחים. מפרש רש"י שצ"ל טפח אחד כיון שחודו החיצון יורד וסותם, כיון שאז מותר להשמתמש תחתיו, יכול להיות אותו טפח מקום של היכר. כיון שיש היכר, מותר להשתמש במבוי. צ"ל ארבע טפחים כיון שחודו הפנימי יורד וסותם, ואז אסור להשתמש תחתיו. אז, צריך שיהיה הגובה בתוך המבוי, ולא רק תחת קורה, ולכן צריך להיות ארבע טפחים. לא כל כך פשוט למה צריך להיות, אז, שלש טפחים. מרשי נראה שיש חשיבות של תחת קורה, ויש חשיבות של ד"ט (כיון שהוא בכ"מ רשות), ואין חשיבות של דבר שהוא בין שניהם. אז, כל דין ניתן הגדרה של דבר אחד חשוב. כיון שלא יכול להיות טפח אחת תחת הקורה, צריך להיות ארבע טפחים. (ויש לדון אם ארבע טפחים כולל תחת הקורה או לא. לא נראה שכולל אותו, שהרי מה שתחת הקורה לא מהני להיות היכר.) אז, נמצא שיש שני מח' כאן: גודלו ומקומו.)
אות ב
גמרא מזכיר ארבע צדדים בביאור מחלקת אם צריך ארבע טפחים או קפח אחד למעט קורה. יש לדון אם מודים זה לזה או חולקים, ואחד סובר שיכול להיות שקורה משום מחיצה, ואף על פי כן, רק צריכים טפח אחד. ותחשב.
אות ג
גמרא מקשה על רב (שסובר שר"י רק מכשיר בפתח של ארבעים אמה, שלומד מאולם) מבריי' שמזכיר שני שיעורים:
1. ארבעים או חמישים אמה. צריך ביאור למה מזכיר שניהם. עיין בתחילת פרק שמנה עשרה של שבת.
2. מאה אמה. גמרא נחית לומר שזה רק גוזמא. (משמע שלא נחית לומר שהראשון הוא גוזמא. יש לדחות שרק מכוון לומר שאי אפשר לרב לטעון שהראשון הוא גוזמא, שרב סובר שהשיעור הוא ארבעים, ואז היה לו לומר רק ארבעים, ולא להוסיף "או" עליו. כמו"כ, יש לומר שלא יגזם על ידי הוספת עשר. אבל, אולי אם לא נאמר כרב, אפשר שמגזם, ושיעורו הוא רק עשרים וחמש אמות. ותחשב.)
גמרא מסיק שלומד מפתחי מלכים. יש להעיר שרנב"י מצדד ששיעור עשרים בא ממה שצריך להיות היכר. לכא', יש לדון אז מה סובר רבי יהודה. נראה שהשני דרכים הם או שסובר שלא צריכים היכר, או שסובר שיש היכר אף בזה. (יש להעיר שרבי יהודה חולק אף בסוכה. אז, יותר טוב לומר דבר שיבאר שניהם באחד, כדי שנמעט את המחלקת. נראה שזה יותר טוב אם נאמר כצד שני שכתבנו. ותו"ת.)
אות ד
גמ' מפ' שאם פתוח יותר מעשר אמות, לא מהני לחי וקורה להתיר אותה. רב לומד את זה מפתחו של היכל, וגמרא לא מזכיר חולק. משמע שאף רנב"י מודה לזה. קצ"ב מה לנו בזה אם אין צורך לעשיית מחיצה, אלא להיכר. אולי צריך לומר שסובר שיש צורך לשניהם, וגודל המבוי עושה מחיצה. אז, קורה רק צריך לעשות היכר.
אות ה
גמרא מפרש שני דברים שמתירים במבוי גדול, ודן באיזה מיני מבוי מתירים בו. יש להעיר שלכאו', צריך להיות כרנב"י, שלרב, לא מהני כלל. אז, צ"ל כרנב"י. אם כן, מעניין שיתיר רוחבו; שהרי לא מצאנו פתח עם אותו רוחב אף בצורת הפתח. אז, צריך לומר שהוא היכר. מעניין שבעיית עשר אמות הוא שאין היכר די. (אפשר לדחות שסובר שצריך פתח, אבל לומד פתח מסברה שלו, ולא מהיכל. ותחשב.)
אות ו
יש לדון אם צורת הפתח מתיר בפני עצמה או רק עם לחי וקורה. ואם תאמר הרי לעולם יהיה הוא לחי ושני קורות. ויש לדון, שאולי לחי צריך ליהות יותר דבוק לכותל מצורת הפתח.
גם יש לדון אם, כשמתיר, מתיר מתורת שני לחים וקורה או מתורת צורת הפתח. במילים אחרים, יש לדון אם עושה מה שעושה לחי עם מה שעושה לחי עם מה שעושה קרי או שעושה דבר אחר להתיר. נראה להביא ראיה ממה שצריכים להיות נוגעים זה בזה וממה שלא יכול להיות מחובר מן הצד. אבל, יש אמוראים שחול' וסוברים שלא צריך להיות אחד מדברים אלו. יש לדון, עדיין, אם צריך להיות מחובר (עיין שם, בציור שלא נחשב נוגעים). ותחשב.
אות ז
גמ' אומר שקני עופות מתירים מבוי, אף למעלה מעשרים. יש לדון אם צריכים להיות על קורה או לא. לכאו', הדיון הוא אם מה שעושים הוא רק שעושים את הקורה ניכר או שמה שעושים הוא שעושים את המבוי ניכר.  (גם יש לצדד שמצרפים עם מה שעושה קורה. נראה שאולי יש עוד נפקא מינא שיצא, והוא שיש לדון אם מהני אם עושים אותו עם לחי.)
לצד שני (שעושים את המבוי ניכר), יש לדון אם אף צריך להיות שם קורה או לא. ותחשב.
יש לדון כל דיונים אלו גם בקורה גדולה. ותחשב.
* Footnotes
[fn:1] פרק ראשון
[fn:2] משנה א
[fn:3] מבוי הוא רשות שיש לו שלש מחיצות סתומות ואחד שפתוח לרשות הרבים (רש"י ב.), שפותחים בו חצרות ובתים. (ה.) (באר). אותו שפתוח לרשות הרבים יהותר בלחי וקורה, כמו שיבאר משניות. ענין הלחי והקורה הוא דיון בגמ' (ג., ה.?), שחל' אם הוא היכר או מחיצה (ואין הוכחה שהם שווים).משנה יבאר שיעור פתח המבוי, אבל לא מבאר שיעור המבוי עצמו. מקום גבוה עשרה טפחים שהוא משוך ארבע טפחים (לרב יוסף) או ארבע אמות (לאביי) ורחב פחות מארכו.נבאר כל דין ודין:שיעור גובה הוא עשרה טפחים מפני שכל מחיצה ורשות חשוב הוא עשרה טפחים. יש שני מקורות לזה:ארון עם כפורת היה, לתנא אחד, עשרה טפחים. ה' לא ירד למטה משם, ואז רואים שהוא רשות לפ"ע.הלכה למשה מסיני הוא. (ד:)שיעור משכו הוא ארבע אמות או ארבע טפחים בתחילה (?). אבל, אם כבר היה כשיעור ונפחת (ר"ל, פתח אחר נפתח בתוך המבוי), כוע"מ שרק צ' ארבע טפחים. (שם)שיעור רחבו צ"ל פחות ממשכו. אם אינו כן, נקרא חצר. (ה.) דיני חצר חלוקים, ולא הותר בלחי וקורה. (ה:) יש שני דרכים להתיר חצר (אם רחבו לא גדול מעשר):עומד מרובה על הפרוץ, אם אין שני פרצים שבצדי העומד רבים מן העומד(?). (ה:) חול' אם צ"ל עומד מרובה על הפרוץ או שווה לפרוץ. (?) גם חולקים אם מצרפים פרוץ של שני צדדים לבטל את הפרוץ. (?)פס. תלוי בשני דברים:כמה פסים יש. אם יש שני פסים (אחד בכל צד?) כשר אף אם הם רק טפח. (?)גודל הפסים. אם יש שני פסים, כבר כ' השיעור. אם יש פס אחת, חולק אם יכו"ל טפח או צ"ל ארבע טפחים. (?) (אם צריך להיות טפח, מהו הח' בין זה ללחי?).יש עוד שני מיני מבוי, ומשנה לא דן בהם:מבוי מפולש. זהו מבוי שהוא מפולש בשני צדדים לרשות הרבים (אבל לא לכרמלית (?)). דינו הוא מחלקת תנאים. (?) (באר)מבוי עקום. חול' רב ושמואל מהו דינו. רב סובר שדינו כלחי מפולש, כיון שהוא מפולש לשני רה"ר. שמואל סובר שכיון שעקום בינתים, אין דינו כמבוי מפולש, אלא רק צריך לחי בכל פתח. (רש"י מביא שני צדדים איפה צריכים שני הלחיים, אם צריך אחד בכל פתח או צריך אחד בפתח ואחד באמצע לאותו מבוי, וכמו כן למבוי השני של העיקום).
[fn:4] יש שני נידונים בשיעור עשרים אמה:יש לדוון אם צריך להיות בתוך עשרים אמה או בסוף עשרים אמה. גמרא מסיק (ג:) שצריך להיות בסוף עשרים אמה.אבל, לכאו', גם נזכר שיטה שסובר שצריך להיות בתוך עשרים אמה. (ג.)יש לדון אם צריך להיות כולו שם או רק מקצתו. גמרא מסיק (ג:) שצריך להיות רק מקצתו שם.אבל, גם נזכר שיטה שסובר שצריך להיות כולו שם. (ג.)
[fn:5] יש שני מיני אמה:אמה של חמשה טפחים. אמת יסוד וסובב היו כן. (ד.) רבי יהודה סובר שכל אמות כלי שרת היו כן. (ד:)אמרה ששה טפחים. רוב אמות של בנין היו כן. (ד.) רבי מאיר סובר שכל אמות כלי שרת היו כן. (ד:)
[fn:6] גמרא מזכיר שני סיבות לזה:רב אומר שחולקים ברייתות בזה. (ג.) בריי' אחד אומר שלא נחשב פתח. לחי וקורה לא מתירים אם המבוי נבקע לרה"ר, אלא רק אם פתוח לרה"ר. לא מצאנו שדבר נקרא פתח ביותר מעשרים  אמה (אבל מצאנו שפתח היכל, שהוא עשרים אמה, נקרא פתח). (ב.) בריי' שני אומר כרנב"י.רב נחמן בר יצחק סובר שכוע"מ שהקורה צ"ל ניכר לבני המבוי (סובר שקורה מתיר כיון שהוא היכר). לא מכירים אותו אם אינו בתוך עשרים אמה. (ג.)חולקים כאן באיזה אמה מודדים. אביי אומר שחל' רשב"ג ורבנן אם מודדים בשל חמש או בשל שש, ואומר בשם ר"נ  שמודדים בשל חמש (לחומרא). רבא אומר שמודדים בשל שש (בטפחים קטנים). (ג:)
[fn:7] ואם תאמר ל"ל אומר שהוא פסול, אלא אומר תקנה. ויש לומר:כיון שהוא רק מדרבנן, ולא השביע כבר שיעור שלו, לא יכול לומר שהוא פסול. לעולם יותר טוב לומר תקנה (אא"כ עי"ז ישכח על מה היה קאי משנה, כמו כשמשנה היא ארוכה). (ב.)
[fn:8] יש שני דרכים למעט מבוי:יכול לתת קורה במקום הנכון.יכול להגביה את קרקע המבוי. חולקים ברוחב (ולא מבאר האורך) כמה צריך להגביה אותו:טפח אחת. מזכיר גמרא שצריך לסבור ארבע דברים:חודו החיצון סותם. אז, מותר לטלטל תחת הקורה, ויהיה היכר למי שעומד תחת קורה ומטלטל. (עיין בהלשמות אות א.)קורה הוא משום היכר (ויש היכר למי שעובר תחתיו).היכר של מטה הוא כהיכר של מטה.לא גוזרים שמא יפחות וימעט מטפח.ארבע טפחים. יכול לחלוק על אחד מהנחות אלו. (עיין בהשמטות אות ב) כיון שצ"ל יותר מתחת הקורה, צ"ל ארבע טפחים, כשיעור מקום חשוב. (ה.)
[fn:9] חולקים מה סובר רבי יהודה:רב סובר שרבי יהודה מכשיר עד גובה של ארבעים אמות. לומד כן מפתח של אולם. (אז, מח' ר"י ורבנן הוא אם פתח של אולם נקרא פתח או לא. תלוי בביאור קראי.) (ב.)גמ' מצדד שר"י מכשיר עד יותר מזה. נראה שלש סיבות:לא סובר שצ"ל ניכר. אז, יכול להיות כל גובה שבעולם.סובר שניכר אף ביותר מעשרים אמה. (עיין בהשלמות אות ג.)גמ' מצדד שלומ' מפתחי מלכים (שנקראים פתחים אף שהם גדולים). (ב:)נראה שיש שלש דברים בשיטת ר"י שאינם פשוטים:למה חולק.איזה שיעור נותן.למה פוסל באותו שיעור.
[fn:10] אחר עשר אמות, לא נחשב פתח. (הדבר הכי גדול שמצאנו נקרא פתח הוא פתח ההיכל, והיה רחב עשר אמות). (ב.) (עיין בהשלמות אות ד.)
[fn:11] לא מבאר גמ' כמה צריך למעט. לכאו', ימעט גובה עשרה טפחים (שהוא שיעור מחיצה (ד:)).
[fn:12] מבאר גמרא כמה פרטים בצורת הפתח:צורת הפתח יש בו שלש קורות: שנים בכל צד, ואחד לתקרה. אותו שלתקרה צ"ל על השנים, ולא מחובר לצדם. אין זה פשוט, אלא יש שלש צדדים:לעולם צריך להיות על גביו.לפעמים (עיין לקמן) צ"ל על גביו.לעולם לא צריך להיות על גביו, ויכו"ל על צדו. (יא)צריך ששלש הקנים יגעו זל"ז. חולקים בזה ר"ש ור"ח, שר"ש סובר שצ' ליגע ור"ח סובר שלא צ' ליגע. מוכיח גמ' מבריי' שלא צריכים ליגע. (יש לדון אם מהני אם סומכים על לבוד.)צריך להיות בריאה עד כדי להעמיד דלת.צריך היכר ציר (היינ"ג). אם אינו פתח בלי חקיקה, לא מהני. חלקו בזה רבנן, שסוברים שלא מהני, ור"מ, שסבר שמהני. (יא:)
[fn:13] כמו כן, אם גו' שמהני צוה"פ כאן, מהני צורת הפתח למבוי גבוה מעשרים טפחים. (י:)
[fn:14] דנים אמוראים (ב., יא.) אם לגרוס שמתיר (כן סבר רב יהודה) או שלא מתיר (כן סובר רב). יש שנ' שסובר (פשט שני של גמ' לפי ריש לקיש, אחר שח' גמ' (יא:)) שמהני רק אם התקרה הוא על גבו, ולא מחובר לצדדיו.
[fn:15] גמרא מזכיר (ב:) שר"י חולק בזה. סובר שקרא תורה לפתח אולם- שהיה רחוב עשרים אמה- פתח, ואז עד עשרים אמה נקרא פתח. (נכון?)
[fn:16] משנה ב
[fn:17] חוץ מהכשירי מבוי שמצאנו במשנה זה, יש עוד ארבע הכשירי מבוי:צורת הפתח. במשנה לעיל, הזכרנו שדנים אמוראים אם מתיר אף אם הוא יותר מעשר וגבוה מעשרים. (עיין בהשלמות אות ה.) (עיין בהשלמות אות ו.) (ב., ב:, יא.)קני עופות. כיון שהם בולטים וחשובים, הם מתירים את המובוי, ואף אם הוא גבוה מעשרים אמות. דן גמ' אם מהני אם המבוי רחב מעשר. (עיין בהשלמות אות ז.)רב סובר שחל' תנאים בזה. (ג.)קורות ארוכות. מתיר את המבוי, ואף אם הוא גבוה מעשרים אמות. חולקים למה מתירים:כיון שהוא ארוך. דוחה גמ' שאם כן סכך, שהוא ארוך, יהיה מותר למעלה מעשרים אמות.כיון שהוא חשוב.יש שסוברים שזה לא מהני לכ"ע, יש שסוברים שזה מחלקת תנאים, ויש שסוברים שזה מהני לכ"ע. (ג.)עומד מרובה על הפרוץ. לומ' שמהני מקל וחומר בחצר, שבו לא מהני לחי וקורה. (ה:) עיין לעיל בדיני חצר (בארנו אותו על משנה ראשונה) שבארנו דיני עומד מרובה על הפרוץ.
